### ISSUE TITLE
👑 [需求] 期望ProTable组件列设置信息可以记录到localStorage， 刷新的时候能保持这个信息

### ISSUE THREAD

**Issue by yibingxiong** [ant-design/pro-components#1000]
非常感谢贵团队开发出如此优秀的组件库和框架，我们在使用中遇到一点问题，期望你们能够评估下看能否支持，我给出了两个方案，如果可行话，若需要，本人可以支持下这个需求。

### 🥰 需求描述

目前我们有一个需求，要求ProTable那个显示列的设置更改后，下次进来还有效，目前发现除了改你们的源码外没有其他可行方法。

### 🧐 解决方案

有如下两种方案，期望你们能评估下

1. `packages/table/src/component/ColumnSetting/index.tsx`这个里边的setColumnsMap方法调用后能够给用户一个回调，把列配置信息暴露出去，这样用户就能做一些定制化需求了，还要支持传入初始的列配置信息
2. 和上边类似，不过setColumnsMap调用时将列配置信息直接放到localStorage中， ProTable创建时能够读取之前存储的配置信息

### 🚑 其他信息

上文所述列配置指的是图中这个东西， 就是说第一次进来我配置了显示A列B列， 刷新后仍然要求显示A列B列（保持住设置的信息）， 而不是所有
![image](https://user-images.githubusercontent.com/20298674/99372715-89e01b00-28fb-11eb-8228-334e8c6e4344.png)

@chenshuai2144

**Comment by xiexingen** [comment]
我理解的这个目前就可以做到的，有个columnsStateMap和onColumnsStateChange 可以通过这两个来实现到你要的效果

**Comment by yibingxiong** [comment]
@xiexingen 我找找看，多谢

**Comment by chenshuai2144** [comment]
@yibingxiong columnsStateMap 还有点问题，不支持嵌套

**Comment by yibingxiong** [comment]
> 我理解的这个目前就可以做到的，有个columnsStateMap和onColumnsStateChange 可以通过这两个来实现到你要的效果
@xiexingen 确实可以做到，而且文档里写了的，没注意到，尴了个尬

**Comment by xiexingen** [comment]
@chenshuai2144  是不是重新open改下标题，标记下 层级的情况还有问题

**Comment by yibingxiong** [comment]
@xiexingen 请问层级问题是啥意思啊，没太懂

**Comment by xiexingen** [comment]
> @xiexingen 请问层级问题是啥意思啊，没太懂

表头分组的情况，如：
![image](https://user-images.githubusercontent.com/7939085/99503512-4350f600-29b9-11eb-8902-94e8fe8c053f.png)

**Comment by chenshuai2144** [comment]
在这里统一控制吧
https://github.com/ant-design/pro-components/issues/416

**Comment by queuemax** [comment]
有办法 再重置旁边加个【保存】吗？ 重置 事件能自己控制吗？

**Comment by baibaibai455** [comment]
> > 我理解的这个目前就可以做到的，有个columnsStateMap和onColumnsStateChange 可以通过这两个来实现到你要的效果
> > @xiexingen 确实可以做到，而且文档里写了的，没注意到，尴了个尬😅，谢谢
> > @chenshuai2144 先关了，打扰~

麻烦问下文档在哪里了？方便发下链接么
