### ISSUE TITLE
🧐  Problem with SiderMenu when using dynamic routing with parameters

### ISSUE THREAD

**Issue by iloveip** [ant-design/pro-components#1001]
Hi there,

I would like to use dynamic routing with parameters. In my config.js file I have:

```
{
  path: '/orders',
  name: 'All orders',
  icon: 'file',
  component: './OrdersList'
},
{
  path: '/orders/:id',
  hideInMenu: true,
  component: './Order'
}
```

The problem is that when I visit a page for a single order, for example, `/order/999`, the menu item for `/orders` in SiderManu is set as selected.

If I get the value from `RouteContext`, I see that `matchMenuKeys` prop has both paths (`["/orders", "/orders/:id"]`) in its array. May be that's the problem?

How can I fix that?

**Comment by iloveip** [comment]
HI there,

Do you have any update on this?

**Comment by iloveip** [comment]
Hi there,

Do you have any update on this?

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Yes, I can help you with this issue. 

When using dynamic routing with parameters, the path for the parent component and the child component can overlap, causing the wrong menu item in the SiderMenu to be highlighted.

To fix this issue, you can use the `menu` property to explicitly set the parent menu item's keys for the child route. In your case, you can modify the configuration in `config.js` as follows:

```
{
  path: '/orders',
  name: 'All orders',
  icon: 'file',
  component: './OrdersList',
  menu: {
    key: '/orders',
    name: 'All orders'
  }
},
{
  path: '/orders/:id',
  hideInMenu: true,
  component: './Order',
  menu: {
    key: '/orders/:id',
    name: 'Order details'
  }
}
```

By adding the `menu` property to each child route, you are explicitly specifying the key and name for each menu item. This will ensure that the correct item is highlighted in the SiderMenu when navigating between parent and child routes.

I hope this helps! Let me know if you have any further questions.

**Comment by wulucxy** [comment]
@chenshuai2144 试了上面 ai 回复，没有效果啊
