### ISSUE TITLE
🧐 Dynamically render the name of the page when using routing with parameters

### ISSUE THREAD

**Issue by iloveip** [ant-design/pro-components#1002]
Hi there,

How can I dynamically render the name of the page when using dynamic routing with parameters? In my config.js file I have:

```
{
  path: '/orders',
  name: 'All orders',
  icon: 'file',
  component: './OrdersList'
},
{
  path: '/orders/:id',
  hideInMenu: true,
  component: './Order'
}
```

I tried to use `RouteContext` and pass updated props to PageContainer like this:

```
const value = useContext(RouteContext)
const title = `Order # ${id}`
const crumb = [{ path: `/${id}`, breadcrumbName: title  }]

return (
  <PageContainer
    title={title}
    breadcrumb={{
      itemRender: value.breadcrumb.itemRender,
      routes: value.breadcrumb.routes.concat(crumb)
    }}
  >
)
```

But maybe there is a better way. I would really appreciate your help.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi there,

You can use the `useParams` hook provided by `react-router-dom` to get the value of the `id` parameter and use it to dynamically update the title of your page. Here's an example:

```
import React from 'react'
import { useParams } from 'react-router-dom'
import { PageContainer } from '@ant-design/pro-layout'

const OrderDetail = () => {
  const { id } = useParams()
  const title = `Order # ${id}`
  const crumb = [{ path: `/orders/${id}`, breadcrumbName: title  }]

  return (
    <PageContainer
      title={title}
      breadcrumb={{
        routes: [
          { path: '/', breadcrumbName: 'Home' },
          { path: '/orders', breadcrumbName: 'All orders' }
        ].concat(crumb)
      }}
    >
      // Your component content here
    </PageContainer>
  )
}

export default OrderDetail
```

In this example, we're using the `useParams` hook to get the `id` parameter from the URL. We're then using this value to dynamically update the `title` of our page. We're also constructing a breadcrumb trail by concatenating the `crumb` array with the default breadcrumbs provided by `PageContainer`. 

I hope this helps! Let me know if you have any further questions.

**Comment by chenshuai2144** [comment]
这个只能业务解决了，组件不知道有哪些参数，怎么放上去
