### ISSUE TITLE
🐛[BUG] table 的initiaValue 到底怎么设置

### ISSUE THREAD

**Issue by coderlfm** [ant-design/pro-components#1003]
### 🐛 bug 描述

我复制了官网上的高级表格实例，代码一模一样，运行起来报如下错误

 **Warning: Multiple Field with path 'state' set 'initialValue'. Can not decide which one to pick.**
以下的代码是复制官网例子的

{
        title: '状态',
        dataIndex: 'state',
        initialValue: 'open',
        filters: true,
        valueEnum: {
            all: {
                text: '全部',
                status: 'Default',
            },
            open: {
                text: '未解决',
                status: 'Error',
            },
            closed: {
                text: '已解决',
                status: 'Success',
            },
            processing: {
                text: '解决中',
                status: 'Processing',
            },
        },
    },

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by LichiaMa** [comment]
同问，这种设置，在request中并没有带过默认参数
```
// columns
{
      title: '子节点',
      dataIndex: 'showSubNode',
      hideInTable: true,
      valueType: 'radioButton',
      initialValue: '0',
      valueEnum: {
        '1': { text: '显示' },
        '0': { text: '隐藏' },
      },
    },
// table
<ProTable<PromoteListItem, PromoteListParams>
      scroll={{ x: 1700 }}
      columns={columns}
      request={(params) => {
        return fetchList(
         {
              ...params, // params中没有showSubNode 这个参数在加载页面的请求中
              pageNumber: params.current || 1,
              pageSize: params.pageSize || 10,
            }
        );
      }}
      rowKey="id"
      dateFormatter="string"
      search={{
        defaultCollapsed: false,
      }}
    />
```

**Comment by chenshuai2144** [comment]
是不是最新的版本呢？

**Comment by LichiaMa** [comment]
> 是不是最新的版本呢？

是的，v2.11.1, 这个初始值在页面第一次加载请求数据是没有的，但点击搜索按钮是可以带过去的

**Comment by chenshuai2144** [comment]
@LichiaMa 用 form.initialValues 好了，一定没问题
