### ISSUE TITLE
🧐[问题]ProForm中的onFinish中保存为null或者undefined的字段

### ISSUE THREAD

**Issue by joyerli** [ant-design/pro-components#1005]
### 🧐 问题描述
ProForm中的onFinish函数默认会把值为nil的字段给清掉, 是否可以提供选项保留他们(维持antd中的表单一样的行为)呢? 

因为做修改操作的时候, 需要这些空值来告诉后端一些字段需要置为空.

### 🚑 其他信息
[源码地址](https://github.com/ant-design/pro-components/blob/master/packages/form/src/BaseForm/index.tsx#L336)
```
await rest.onFinish(
  transformKeySubmitValue(
    conversionSubmitValue(values, dateFormatter, fieldsValueType.current),
      ransformKeyRef.current,
   ),
);
```

**Comment by chenshuai2144** [comment]
我这边的后端会把 '' 认为是报错

**Comment by joyerli** [comment]
''为清空数据库的数据

**Comment by chenshuai2144** [comment]
这个好像不是很好做，你有什么想法？
增加一个新的api？

**Comment by joyerli** [comment]
感觉需要提供一个新的api来转换这个onFinish的这个formData, 如果没有传, 就用你们默认的.

我当前在项目里面解决的方式是, 写一个基于ProForm的高阶组件, 包装一层onFinish, 使用form.getFieldsValue()替换掉原函数传递过来的formData. 这样就符合我的需求了.

**Comment by zhj778930960** [comment]
我觉得还是原样返回笔记好，我们这边如果没有的值 是需要传null 过去的， 我也遇到这个问题了，莫名的少字段，我们这边的规范是null  所以我觉得给开发返回完全的字段就可以，用不用取决于开发者自己

**Comment by winter-ice** [comment]
+1, 同样的需求。

另外我还有个问题，如果表单项的name为数组嵌套的话，还会吧对象内的值拿到对象外，例如：

```
<ModalForm>
   <ProFormText
        name="level"
      />
   <ProFormText
        name=['settings','name']
      />
   <ProFormText
       name=['settings','title']
      />
</ModalForm>
```

`onFinished` 期望拿到的格式 `{ level: 'level', settings:{ name: 'name', title: 'title' }}`
实际拿到的格式 `{ level: 'level', name: 'name', title: 'title', settings:{ name: 'name', title: 'title' }}`

二级的数据被提到顶层了。

**Comment by chenshuai2144** [comment]
二级的数据被提到顶层了。 这个是个 bug，会修掉
