### ISSUE TITLE
🐛[BUG]ProForm collapse状态的元素还可以获取到值

### ISSUE THREAD

**Issue by xiexingen** [ant-design/pro-components#1006]
### 🐛 bug 描述

QueryFilter有折叠模式和非折叠模式，按正常理解如果点击搜索那么搜索的值应该只会搜索可见的表单元素(折叠的值不应该出现在搜索条件中)
### 📷 复现步骤

https://codesandbox.io/s/o15sb?file=/App.tsx
1.修改代码 为QueryFilter增加onFinish={async (values) => console.log(values)}  方便log查看
2.点击展开 录入创建时间
![image](https://user-images.githubusercontent.com/7939085/99387048-4c38bd80-290e-11eb-8580-02247741aec7.png)

3.切换到折叠状态，点击搜索
![image](https://user-images.githubusercontent.com/7939085/99387087-5c509d00-290e-11eb-8d7a-81ed4ca14f86.png)
获取到的value值不应该包含不可见的表单元素项，这样容易造成误解

### 🏞 期望结果
考虑到有些场景可能就是以表单为中心，而不管是否可见
所以是否在QueryFilter增加一个属性配置，然后根据属性配置来获取全部或者可见部分的元素项的值

### 💻 复现代码

https://codesandbox.io/s/o15sb?file=/App.tsx:151-162
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个是因为有人觉得拿不到很奇怪，才做成现在的样子

**Comment by xiexingen** [comment]
所以是不是增加一个配置项来满足不同情况的需要
