### ISSUE TITLE
🧐[问题] proTable中form表单值类型与table原有数据类型不一致

### ISSUE THREAD

**Issue by u-hey** [ant-design/pro-components#1009]
### 🧐 问题描述

表单触发表格查询(request)时，request接收的参数contentType，其值为string类型，如何与原有table中数据类型保持一致？

### 💻 示例代码

`
const tableData = [{ contentType: 1 }, { contentType: 2 }]

const columns =  [{
          title: "策略类型",
          dataIndex: "contentType",
          valueEnum: {
            0: {
              text: '策略'
            },
            1: {
              text: '建议'
            },
            2: {
              text: '活动'
            },
          },
        }]
`

除了在request中格式化入参以外，protable是否有其他解决方式？

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/18671673/99403849-e48e6c80-2925-11eb-93ab-eade8708e1d4.png)

**Comment by chenshuai2144** [comment]
@u-hey  用 map， 因为 object 是不允许 number 当 key的。

**Comment by u-hey** [comment]
> @ u-hey 用图，因为object是容许编号当key的。用number当key非常危险，因为js会帮你自动转，很麻烦

valueEnum: [{ text：'策略', value: 0 }]
这种格式也不能使表单value的值为number类型，必须是string类型吗？

**Comment by u-hey** [comment]
> @u-hey 用 map， 因为 object 是不允许 number 当 key的。用number 当 key 非常危险，因为 js 会帮你自动转，很麻烦

已解决，谢谢🙏
