### ISSUE TITLE
🐛[BUG]ProTable显示数字自动四舍五入了

### ISSUE THREAD

**Issue by zc1175** [ant-design/pro-components#1010]
### 🐛 bug 描述

数据库存储的数据为：1328639298966151170
ProTable展示数据为： 1328639298966151200

### 📷 复现步骤

将很长的数字让ProTable展示就可以出现这个问题

**Comment by chenshuai2144** [comment]
这是js 的功能，js 有最大的数字限制，转成 string 再展示

![Uploading image.png…]()
