### ISSUE TITLE
ProTable自定义的问题

### ISSUE THREAD

**Issue by darkfiredarkhalo** [ant-design/pro-components#1013]
### 🧐 问题描述

你好, 首先非常感谢你们, 因为项目中大部分都是表格加搜索,一直使用 Protable,大大节省了工作量。

但是目前遇到了一个问题, 就是在搜索栏的某个位置需要触发一个自定义的 Modal 组件, modal 中又是一个带搜索和表格的组件(没使用 Protable), 在自定义的 modal 中选择数据之后会通过回调把数据抛出,然后页面接收这些数据。

现在有同事反映, 在 ProTable 中没法使用自定义的 Modal 组件,因为 ProTable 是通过配置`Columns `去定义搜索栏的外观和行为的,看了看 ProTable 的文档, 发现可以使用 `renderFormItem` 去自定义搜索栏中的组件,但是自定义 modal 组件的返回值(通过回调接收)ProTable 要怎么接收?这是一种可能可行的解决方案。

另外一种我不知道是否可行: `Columns`中有一个配置项`valueType `,不同的 valueType 会在搜索栏出现不同的组件,能不能通过对 ProTable 再做一层封装,多添加一种 valueType,这种 valueType 可以实现在搜索栏添加自定义组件, 如果可行的话,有没有可用的方案或者教程?

总结一下:

- `renderFormItem`返回自定义组件, 自定义组件的返回值(回调)如何传递给 ProTable?
- 如果对`ProTable`再做一次封装, 对`Columns`的配置项`valueType`多加一种值类型, 是否可行? 如果可行的话有没有相关示例或者教程?

### 🚑 其他信息

使用的是`v5`

**Comment by chenshuai2144** [comment]
renderFormItem 和  FormItem 的行为是一致的，只要有 value 和 onchange 就能绑定数据。你可以把 modal 做成支持 value 和 onChange,如果值改变触发一下 props.onChange

**Comment by DCLangX** [comment]
![image](https://user-images.githubusercontent.com/19513657/99479180-9febeb00-2990-11eb-9888-eea4fca8e811.png)
文档给个例子多好，我也是搜半天，才明白像这样直接透传所有属性和方法给组件就行了

**Comment by darkfiredarkhalo** [comment]
> > 注意一下排版和标点
> 
> renderFormItem 和 FormItem 的行为是一致的，只要有 value 和 onchange 就能绑定数据。你可以把 modal 做成支持 value 和 onChange,如果值改变触发一下 props.onChange

😀, 不好意思,下次注意  
我按照这种方案去试试, 不过这种方案其他同事还是有一定的工作量, 有没有对Protable进行再次封装的示例?😀

**Comment by darkfiredarkhalo** [comment]
> ![image](https://user-images.githubusercontent.com/19513657/99479180-9febeb00-2990-11eb-9888-eea4fca8e811.png)
> 文档给个例子多好，我也是搜半天，才明白像这样直接透传所有属性和方法给组件就行了

非常感谢兄弟👍, 我也去试试

**Comment by chenshuai2144** [comment]
我给你写一个，今天搞上去。
现在的太简单

**Comment by darkfiredarkhalo** [comment]
> 我给你写一个，今天搞上去。
> 现在的太简单

太感谢了Thanks♪(･ω･)ﾉ

**Comment by chenshuai2144** [comment]
已经增加了更多的demo

**Comment by zuoLingLing** [comment]
{
            title: "月份",
            dataIndex: "month",
            key: "month",
            ellipsis: true,
            renderFormItem: (item, { type, defaultRender, formItemProps, fieldProps, ...rest }, form) => {
                console.log(defaultRender);
                if (type === 'form') {
                    return null;
                }
                return <DatePicker {...rest} picker="month" format="YYYY-MM" />
                
            },
        },
![image](https://user-images.githubusercontent.com/43109688/110059262-d8c49a00-7d9e-11eb-8566-4390746212cc.png)
为什么不能将值返回到form表单中，不知道为题出在哪，怎么解决

**Comment by chenshuai2144** [comment]
...rest 是不是有 value 和 onchange ，console 一下

**Comment by zuoLingLing** [comment]
打印出来是underfinde ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;陈帅&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月5日(星期五) 下午4:53
收件人:&nbsp;&quot;ant-design/pro-components&quot;<pro-components@noreply.github.com&gt;;
抄送:&nbsp;&quot;zuoLingLing&quot;<2440829953@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/pro-components] ProTable自定义的问题 (#1013)

**Comment by chenshuai2144** [comment]
现在改了实现方式，只要不手动设置 value 和 onchange 就可以

**Comment by zuoLingLing** [comment]
就是不行，我也不知道怎么回事，是能重绘，但是就是我问题图中的问题，不知道怎么解决------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;陈帅&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月8日(星期一) 中午1:23
收件人:&nbsp;&quot;ant-design/pro-components&quot;<pro-components@noreply.github.com&gt;;
抄送:&nbsp;&quot;zuoLingLing&quot;<2440829953@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/pro-components] ProTable自定义的问题 (#1013)
