### ISSUE TITLE
🧐[问题] Protable formItemProps rules在新建表单生效,但查询表单中不应该生效,如何取消?

### ISSUE THREAD

**Issue by ruanhailiang** [ant-design/pro-components#1014]
### 🧐 问题描述

使用protable的过程中,配置columns的字段的属性formItemProps时,添加了rules为required: true时,设置form模式时,新建表单出现为必填项,但查询表单中此字段同时也标识为必填项,个人觉得不应该会这样的.但不清楚哪里出现了问题.

### 💻 示例代码
{
      title: '启用状态',
      dataIndex: 'enabled',
      valueEnum: EnabledEnum,
      formItemProps: {
        rules: [
          {
            required: true,
            message: '启用状态为必填项',
          },
        ],
      },
      // search: false,
      renderFormItem: (item, { defaultRender, ...rest }) => {
        return <Select
          allowClear
          placeholder="请分配启用状态!"
          options={EnabledOptions}
          {...rest}
        > </Select >
      },
    },

### 🚑 其他信息

![2020-11-18 11-19-43 的屏幕截图](https://user-images.githubusercontent.com/15086045/99478855-1d632b80-2990-11eb-9be2-15755f40a501.png)
![2020-11-18 11-19-57 的屏幕截图](https://user-images.githubusercontent.com/15086045/99478917-3966cd00-2990-11eb-8ab8-219f937faf86.png)

**Comment by chenshuai2144** [comment]
是个 bug
https://github.com/ant-design/pro-components/issues/696

看这里，有兴趣提个 pr 吗
