### ISSUE TITLE
🧐[问题]对于多页面通用的表格搜索下拉选项，该如何使用state+fieldProps.options动态更新下拉?

### ISSUE THREAD

**Issue by zhangxiangqiang** [ant-design/pro-components#1015]
### 🧐 问题描述

 根据文档https://procomponents.ant.design/components/field/#%E8%BF%9C%E7%A8%8B%E6%95%B0%E6%8D%AE，ProTable 的select搜索目前动态更新的方式是在select上加request，这可以解决本页面下拉列表动态更新问题，但是不能使用状态state去更新fieldProps.options，fieldProps.options只渲染初始的值，并不能动态更新， 如果是多页面使用的下拉列表数据，我希望只请求一次，并且fieldProps.options始终是最新值，该如何做呢

### 🚑 其他信息
下面这种方案似乎只能解决本页面的下拉数据更新问题，有使用状态去更新下拉列表的方法么

{
      title: '一级类型',
      dataIndex: 'createTaskType1',
      valueType: 'select',
      placeholder: '请选择一级类型',
      hideInTable: true,
      param: {},
      request: async () => [],
      },

**Comment by ofavor** [comment]
正好今天要实现一个类似的功能，使用的state更新，如下：

```
const [members, setMembers] = useState<API.Member[]>([]);
```

useEffect去请求member数据：

```
useEffect(() => {
    async function fetchMembers() {
      const { data } = await queryMember(currentProject?.id!, { page: 1, page_size: 100 });

      setMembers(data.list!);
    }
    if (project === undefined) {
      setProject(currentProject);
      setTimeout(() => {
        fetchMembers();
      }, 1000);
    } 
  });
...
```
Column:

```
    {
      title: '用户名',
      dataIndex: 'user_id',
      render: (_, entity) => {
        return <a onClick={() => setRow(entity)}>{entity.user?.username}</a>;
      },
      renderText: (_, entity) => {
        return <a onClick={() => setRow(entity)}>{entity.user?.username}</a>;
      },
      valueType: 'select',
      fieldProps: {
        options: members.map((m) => ({ label: m.user?.username, value: m.user?.id })),
      },
    },
```

但是遇到一个问题，第一次显示页面，虽然members取到数据，但是渲染出来的select为空（无数据），之前用renderFormItem的时候发现正常渲染之后间隔很少的一个时间renderFormItem会再次被调用，并且取到的member数据为空。

目前应急处理是在第一次获取members的时候增加了一个延时。

**Comment by zhangxiangqiang** [comment]
@ofavor 延时是可以的，我之前考虑过这种方法，只是为了渲染数据特意延时数据的返回刷新，总觉得不太对，而且必须延时1s以上，短了也渲染不出来，只能作为应急处理而不能作为常规方案。request如果不考虑重复请求也是可以的，缺点就是对一个接口返回多个下拉列表，或者多页面使用一个接口返回的下拉，会重复请求。

**Comment by chenshuai2144** [comment]
fieldProps.options 改变应该触发更新的，没更新是我的bug。

**Comment by chenshuai2144** [comment]
改掉了，原来不知道为啥写了个 setTimeOut
