### ISSUE TITLE
🐛[BUG] ProTableForm 渲染时候 dateTime 获取到的数据是 Date

### ISSUE THREAD

**Issue by zhengchalei** [ant-design/pro-components#1016]
### 🐛 bug 描述

如标题所示

### 📷 复现步骤

        {
            title: '过期时间',
            tip: '当前租户截止使用期',
            dataIndex: 'expirationTime',
            valueType: 'dateTime',
            search: false,
        }

![](https://ftp.bmp.ovh/imgs/2020/11/1212d4c8c4c46961.png)

**Comment by chenshuai2144** [comment]
fixed in  2.17
