### ISSUE TITLE
🧐 'hideInSearch' will be deprecated, please use 'search'

### ISSUE THREAD

**Issue by aweiu** [ant-design/pro-components#1017]
### 🧐 问题描述

当设置 'hideInSearch' 时候工作台会出如标题内容的警告

### 💻 示例代码

https://github.com/ant-design/pro-components/commit/10519e9bdbc4cfcec58aee476933c626d5625f8f#r44253655

**Comment by JoyceLizhuo** [comment]
+1

**Comment by chenshuai2144** [comment]
use` search:false`

**Comment by youngclean** [comment]
如果设置 search:true，会报错：search.transform is not a function
![647E61ED-5FF5-40B2-AA64-3677EC4CCBC4](https://user-images.githubusercontent.com/2239335/102582672-09048100-413e-11eb-8067-2c4bee5cdd42.png)
