### ISSUE TITLE
Form Button 对齐问题🐛[BUG]

### ISSUE THREAD

**Issue by quarkcms** [ant-design/pro-components#1018]
@chenshuai2144 这个问题并没有修复，https://github.com/ant-design/pro-components/issues/956

**Comment by chenshuai2144** [comment]
已经修了，给个重现

**Comment by quarkcms** [comment]
![image](https://user-images.githubusercontent.com/60868863/99616799-dee57380-2a58-11eb-903d-02699044c861.png)
@chenshuai2144 刚更新的依赖

**Comment by quarkcms** [comment]
我看代码里是不是只修改QueryFilter组件啊

**Comment by quarkcms** [comment]
刚才看代码master版本并没有更改。

**Comment by chenshuai2144** [comment]
看这个哥们的
https://github.com/ant-design/pro-components/issues/1027

**Comment by quarkcms** [comment]
额，他这么用当然可以；但是内置上会不会更好呢...

**Comment by quarkcms** [comment]
@chenshuai2144 可以给button单独一个api，来设置布局

**Comment by quarkcms** [comment]
先这样吧，问题解决了

**Comment by chenshuai2144** [comment]
可以用 submiter 的 render 来包裹一下
