### ISSUE TITLE
QueryFilter的两个margin-bottom🧐[问题]

### ISSUE THREAD

**Issue by ccc-rrr** [ant-design/pro-components#1029]
### 🧐 问题描述

form/src/layouts/QueryFilter/index.tsx  line 323:  marginBottom: 24  会导致两个margin-bottom: 24px(外层已经有ant-form-item了)

### 💻 示例代码
                    style={{
                        // 当表单是垂直布局且提交按钮不是独自在一行的情况下需要设置一个 paddingTop 使得与控件对齐
                        paddingTop: layout === 'vertical' && totalSpan % 24 ? 30 : 0,
                        // marginBottom 是为了和 FormItem 统一让下方保留一个 24px 的距离
                        marginBottom: 24,
                      }}

**Comment by chenshuai2144** [comment]
有兴趣来个 pr 吗？

**Comment by chenshuai2144** [comment]
fixed
