### ISSUE TITLE
🐛搜索项如果只选择起始日期时，会出现Invalid Date

### ISSUE THREAD

**Issue by ly4236** [ant-design/pro-components#103]
### 🐛 bug 描述

pro-table相关。
valueType为dateRange，搜索项如果只选择起始日期时，提交，会出现['Invalid Date', 'yyyy-MM-dd']这样值。结束日期也一样。
导致请求连接为：http://localhost:8000/api/services/app/User/GetAll?creationTime=2020-08-05&creationTime=Invalid%20date&_timestamp=1596613814213&skipCount=0&maxResultCount=20

### 📷 复现步骤

ProColumns配置为：
```
 {
      title: '创建时间',
      dataIndex: 'creationTime',
      valueType: 'dateRange',
      hideInForm: true,
      formItemProps: {
        allowEmpty: [true, true],
      },
},
```
仅选择起始/结束日期，点击搜索

### 🏞 期望结果

希望请求连接为： http://localhost:8000/api/services/app/User/GetAll?creationTime=2020-08-05&creationTime=&_timestamp=1596613814213&skipCount=0&maxResultCount=20

### 原因

查看了源代码

/pakeages/table/src/form/index.tsx 中 的 conversionValue方法
```
    // 这里是日期数组
    if (Array.isArray(itemValue) && itemValue.length === 2 && dateFormatter) {
      if (dateFormatter === 'string') {
        const formatString = dateFormatterMap[valueType as 'dateTime'];
        const [startValue, endValue] = itemValue;
    // 这里为空时，返回空字符串即可。或者可以进行配置。
        tmpValue[key] = [
          moment(startValue as Moment).format(formatString || 'YYYY-MM-DD HH:mm:ss'),
          moment(endValue as Moment).format(formatString || 'YYYY-MM-DD HH:mm:ss'),
        ];
        return;
      }
      if (dateFormatter === 'number') {
        const [startValue, endValue] = itemValue;
        tmpValue[key] = [
          moment(startValue as Moment).valueOf(),
          moment(endValue as Moment).valueOf(),
        ];
      }
    }
```

### © 版本信息

- Ant Design Pro 版本: 4.1.0
- 浏览器环境 chrome
- 开发环境  windows 10

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/6881279/89387531-2e679400-d735-11ea-9ffc-4dc191b9a857.png)

**Comment by chenshuai2144** [comment]
有兴趣给提供一个 pr 吗？

**Comment by ly4236** [comment]
> 有兴趣给提供一个 pr 吗？

好啊好啊。
