### ISSUE TITLE
🧐[问题]想用proList  ProFrom  在老项目里

### ISSUE THREAD

**Issue by tenkiss258** [ant-design/pro-components#1030]
### 💻 示例代码
头大了，我通过yarn create umi 新创建的项目可以用，但老项目就是跑不起来。可以给我个兼容吗？它和哪里兼容呢？或者可否向下兼容呀。一天一版本，而且安装依赖都是“^”这个符号，可能重新装一次依赖，项目废了，跑不起来了。烦躁呀。

![image](https://user-images.githubusercontent.com/23648420/99632269-e9633580-2a77-11eb-84a1-dc913b4cffeb.png)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23648420/99632431-2a5b4a00-2a78-11eb-8582-48ee9711b36b.png)

**Comment by chenshuai2144** [comment]
antd 的版本升级到最新，这个问题有好多 issue了，你搜一下就知道

**Comment by tenkiss258** [comment]
> antd 的版本升级到最新，这个问题有好多 issue了，你搜一下就知道
![image](https://user-images.githubusercontent.com/23648420/99636198-1581b500-2a7e-11eb-91a6-bba411962056.png)
antd 换成4.8.4然而没什么用，还是报着一样的错
