### ISSUE TITLE
🐛[BUG][ProTable]使用columnsStateMap自定义列排序不生效

### ISSUE THREAD

**Issue by sushengren** [ant-design/pro-components#1034]
### 🐛 bug 描述

使用ProTable的columnsStateMap自定义列排序初次渲染不生效，需要手动点击列设置【显示/隐藏】后前面设置的排序才生效

### 💻 复现代码

```
  const [columnsStateMap, setColumnsStateMap] = useState<{ [key: string]: ColumnsState }>({
    itemName: {order: 0},
    option: {order: 7},
    payEnum: {order: 4},
    planBatch: {order: 2},
    planYear: {order: 1},
    price: {order: 5},
    proofPath: {order: 3},
    remark: {order: 6},
  });

  <ProTable
    columnsStateMap={columnsStateMap}
    onColumnsStateChange={map => {
      setColumnsStateMap(map);
    }}
    ...
```

### © 版本信息

- ProComponents 版本: pro-table@^2.5.14
- umi 版本 ^3.2.7
- 浏览器环境 Google Chrome 86.0.4240.75
- 开发环境 windows10

### 🚑 其他信息

![test](https://user-images.githubusercontent.com/30110602/99636938-1bc46100-2a7f-11eb-8f81-bab4cb8366ea.gif)

**Comment by HdjPoppy** [comment]
可以生效的

**Comment by chenshuai2144** [comment]
这个一般是 key 设置的问题
