### ISSUE TITLE
🐛[BUG] ProTable, type="form"时，如果输入回车键提交，onSubmit会执行两次

### ISSUE THREAD

**Issue by xspacer** [ant-design/pro-components#1038]
### 🐛 bug 描述
升级ProTable后,  type="form"时，如果输入回车键提交，onSubmit会执行两次

### 📷 复现步骤
以 antd pro中的查询表格页为例，点击新建，然后输入回车提交，会执行两次添加

### © 版本信息

- ProComponents 版本: "@ant-design/pro-table": "^2.11.2",
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个可重现的 demo

**Comment by xspacer** [comment]
> 来个可重现的 demo

就把 ant-design/ant-design-pro 项目中的"@ant-design/pro-table" 依赖升级到新版本， 比如2.11.2，然后打开该项目中的查询表格页，点击新建，然后输入回车提交，就会发现执行了两次添加

**Comment by chenshuai2144** [comment]
emmm
