### ISSUE TITLE
🐛[BUG] pro-table 使用时遇到的几个BUG 

### ISSUE THREAD

**Issue by Lnncoco** [ant-design/pro-components#104]
### 🐛 bug 描述
使用时遇到的几个BUG

1. 当表格第一列设置为hideInTable(`{ title: 'ID', dataIndex: 'id', hideInTable: true }`),最后一列设置为valueType: 'option' (`{ title: '操作', valueType: 'option'}`),最后一列会跑到第一列

2. 当表格rowKey设置的字段有重复值时,  改变请求参数, 使用`actionRef?.current?.reloadAndRest()`或`actionRef?.current?.reload()`刷新表单获取其他数据, 重复的数据会被保留下来与最新请求的数据一起显示出来

复测了一下, 删除了一条

### © 版本信息

- Ant Design Pro 版本: 4.5.2
- umi 版本 3.2.14
- pro-table 版本 2.4.4

**Comment by chenshuai2144** [comment]
> 当表格rowKey设置的字段有重复值时

这个无解的，不然 react怎么知道应该更新哪一行

**Comment by Lnncoco** [comment]
> > 当表格rowKey设置的字段有重复值时
> 
> 这个无解的，不然 react怎么知道应该更新哪一行

但我重新请求数据，直观理解上不是应该旧数据全部清除掉，展现新数据吗
类似Table 把dataSource的引用的变量替换成新值  新数据就直接展现了  不会有旧数据存在

**Comment by chenshuai2144** [comment]
@Lnncoco  这个就是 table 的优化的，现在每行都会有条件重新 render。

除非我每次 reload 之前先设置一个空 [], 然后在设置真正的数据。最好自己处理一下，为什么 key 相同数据却不同呢？

**Comment by Lnncoco** [comment]
> @Lnncoco 这个就是 table 的优化的，现在每行都会有条件重新 render。
> 
> 除非我每次 reload 之前先设置一个空 [], 然后在设置真正的数据。最好自己处理一下，为什么 key 相同数据却不同呢？

👌 ，仔细考虑了一下，我碰上这问题也是因为测试服务器部署数据出差异，导致指定的key数据重复。正常情况不会出现。
之前是想万一小概率出什么状况，前端页面可以兜底一下，保证渲染正常不受影响。如果为了兜底放弃table优化的话，那我还是选择优化吧
