### ISSUE TITLE
🐛[BUG]Modal 表单中，trigger 显示一个按钮，可以点击空白处，也能触发事件。

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#1040]
### 🐛 bug 描述

Modal 表单中，trigger 显示一个按钮，可以点击空白处，也能触发事件。
![123](https://user-images.githubusercontent.com/34436863/99765932-13c9f700-2b3b-11eb-9789-a76f0c0ed021.png)

### 📷 复现步骤

第一步：打开下面连接
https://procomponents.ant.design/components/form#modal-%E8%A1%A8%E5%8D%95

第二步：滚动到Modal 表单 ，在按钮的右侧空白处，点击也能触发事件。看这个图。

应该把样式设置成`    display: inline-block;`

**Comment by chenshuai2144** [comment]
来个 pr 吧
