### ISSUE TITLE
🐛[BUG] 动态菜单下，快速切换路由，ProTable 报useEffect 错误

### ISSUE THREAD

**Issue by zhj778930960** [ant-design/pro-components#1041]
### 🐛 bug 描述
动态菜单下，快速切换路由，ProTable 报useEffect 错误

1. 我设置的路由菜单，是由后端来的，ProLayout动态生成的
2. 每个页面都使用了ProTable
3. 当我快速切换路由时，出现如下错误
![image](https://user-images.githubusercontent.com/23496206/99766370-ea5d9b00-2b3b-11eb-9b17-1d4a62225340.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

![image](https://user-images.githubusercontent.com/23496206/99766417-05300f80-2b3c-11eb-8954-1d841b6d067b.png)

### 🚑 其他信息

我自己有测试过，当我注释掉proTable的代码时，快速切换则不会报错

**Comment by zhj778930960** [comment]
补充： 我自己测试，感觉是columns 在渲染时候的问题，快速的切换路由，导致，还么有渲染完就销毁了组件，所以报错了  这个问题应该怎么进行解决 ？？

**Comment by chenshuai2144** [comment]
加个去抖吧，网络请求又断不掉。这个是因为组件解除了渲染，但是还是在 setState

**Comment by zhj778930960** [comment]
> 加个去抖吧，网络请求又断不掉。这个是因为组件解除了渲染，但是还是在 setState

OK
