### ISSUE TITLE
🧐[问题]ProTable默认展开的个数

### ISSUE THREAD

**Issue by Augustzyh** [ant-design/pro-components#1042]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/38031220/99767286-c307cd80-2b3d-11eb-9da0-4904b5b45683.png)

请问ProTable查询表格，可以设置未展开状态下，查询框的数目吗

**Comment by zhj778930960** [comment]
好像不行

**Comment by chenshuai2144** [comment]
不行的，有个 issue 提了需求，设计师正在考虑了

**Comment by chenshuai2144** [comment]
ref  https://github.com/ant-design/pro-components/pull/1245

这个 pr 好了之后，就可以用` form={{ defaultColsNumber: 3 }} `来设置了
