### ISSUE TITLE
🐛[BUG] Warning: React does not recognize the `formItemProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `formitemprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#1043]
Warning: React does not recognize the `formItemProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `formitemprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

![image](https://user-images.githubusercontent.com/30397655/99768325-863cd600-2b3f-11eb-9575-95b062b4e2d7.png)

**Comment by zhj778930960** [comment]
![image](https://user-images.githubusercontent.com/23496206/99768556-ee8bb780-2b3f-11eb-818c-ab3746b06d19.png)
我这样使用可以  我用fieldProps 不行

**Comment by chenshuai2144** [comment]
try update to  latest version

**Comment by ZhiGang-Fang** [comment]
https://codesandbox.io/s/pensive-goldwasser-u66bm?file=/App.tsx  这个demo 也有同样的错误！
[官方api](https://procomponents.ant.design/components/table#%E6%90%9C%E7%B4%A2%E8%A1%A8%E5%8D%95%E8%87%AA%E5%AE%9A%E4%B9%89)

**Comment by chenshuai2144** [comment]
![Uploading image.png…]()

？

**Comment by leshalv** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/99880832-cc358f00-2c50-11eb-8c3f-0451aa10c638.png)
> 
> ？

![image](https://user-images.githubusercontent.com/30397655/99921967-c501a480-2d68-11eb-85cc-a52a2021755e.png)

选择查询条件会报错。

**Comment by chenshuai2144** [comment]
没法，来个 repo把，可能是依赖更新了

**Comment by leshalv** [comment]
感觉像是rc的问题

**Comment by leshalv** [comment]
问题找到了，自定义搜索表单时renderFormItem 透传 {...rest} 导致的

**Comment by ZhiGang-Fang** [comment]
> 问题找到了，自定义搜索表单时renderFormItem 透传 {...rest} 中包含formItemProps导致的

不传递{...rest}  也一样报错哦

**Comment by chenshuai2144** [comment]
@ZhiGang-Fang  更新版本

**Comment by jinjinwa** [comment]
更新到了最新也一样报错。"@ant-design/pro-table": "^2.12.0"

**Comment by chenshuai2144** [comment]
@jinjinwa   "@ant-design/pro-table": "^2.12.1"

**Comment by zhou0818** [comment]
@chenshuai2144 "@ant-design/pro-table": "^2.12.1" 还是有错

![image](https://user-images.githubusercontent.com/25949890/100710492-c5deaa00-33ea-11eb-9a9f-b0d12dc7f2ae.png)

![image](https://user-images.githubusercontent.com/25949890/100710601-edce0d80-33ea-11eb-9143-9a0e67b9d3cf.png)

**Comment by chenshuai2144** [comment]
showSearch 是 谁的api？

**Comment by yinxiangyin** [comment]
这个问题解决了吗？proTable版本是"@ant-design/pro-table": "^2.18.1",
![image](https://user-images.githubusercontent.com/35419493/103328978-ccb61680-4a95-11eb-968d-68a6ea551a04.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/103451302-2bc99480-4cfd-11eb-9d16-a46708ac699b.png)

**Comment by yinxiangyin** [comment]
升级proTable版本至v2.19.0，经验证已解决！

> 这个问题解决了吗？升级proTable版本至"@ant-design/pro-table": "^2.18.1",仍然有这个问题。
> ![image](https://user-images.githubusercontent.com/35419493/103328978-ccb61680-4a95-11eb-968d-68a6ea551a04.png)

升级proTable版本至v2.19.0，经验证已解决！

**Comment by zhou0818** [comment]
> showSearch 是 谁的api？

升级到2.19.1还是这个问题，showSearch 是 select 的

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/103499958-e46e1000-4e84-11eb-9468-0b9177332ba6.png)


看看是不是这个yuan'y原因

**Comment by zhou0818** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/103499958-e46e1000-4e84-11eb-9468-0b9177332ba6.png)
> 
> 看看是不是这个yuan'y原因

设置了 valueType: 'select'，就不报警告了。。之前只设置了valueEnum

**Comment by kiana-god** [comment]
我升级了ant 版本。antd": "4.16.13，依旧有这个问题，直到我升级了 pro-layout 的最新版本就没这个问题
