### ISSUE TITLE
state+fieldProps.option出现闪退🐛[BUG]

### ISSUE THREAD

**Issue by coloryjl** [ant-design/pro-components#1046]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
祥细说明一下

**Comment by coloryjl** [comment]
就是使用hook的useState定义一个变量options，然后通过useEffect去set值，然后使用这个options放到columns

**Comment by coloryjl** [comment]
然后刷新一下，出现一秒就消失了

**Comment by chenshuai2144** [comment]
来个重现把，你这个听起来是渲染的问题

**Comment by coloryjl** [comment]
[重现记录的demo.zip](https://github.com/ant-design/pro-components/files/5572701/demo.zip)

**Comment by coloryjl** [comment]
想问一下，state+fieldProps.option是支持通过远程数据获取的吗，就是利用useEffect发送请求，获取options的值，然后将该options的值作为column的值

**Comment by chenshuai2144** [comment]
可以的

**Comment by coloryjl** [comment]
但是都不生效，下拉框没有出来值，而且按照文档说的，直接使用的 options = ['aaa', 'bbb']也并不能生效，只能是 options = [{label: 'aaa',value: 'bbb'}]的这种形式

**Comment by chenshuai2144** [comment]
兄弟 我想要你的代码
