### ISSUE TITLE
昨天创建的项目，从服务器获取菜单，能正常获取并渲染，但是在地址栏输入其他路由时，左侧的菜单不渲染了🐛[BUG]

### ISSUE THREAD

**Issue by cdxcom** [ant-design/pro-components#1049]
### 🐛 bug 描述
11.19号新创建的项目，从服务器获取菜单正常，左侧也有菜单显示出来，但是在地址栏输入其他路由地址时，左侧的菜单不显示了

### 💻 复现代码
提供我的BasicLayout.jsx代码：

```
import ProLayout, { DefaultFooter, SettingDrawer } from '@ant-design/pro-layout';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useIntl, connect, history } from 'umi';
import { GithubOutlined } from '@ant-design/icons';
import { Result, Button } from 'antd';
import Authorized from '@/utils/Authorized';
import RightContent from '@/components/GlobalHeader/RightContent';
import { getMatchMenu } from '@umijs/route-utils';
import logo from '../assets/logo.svg';

```
```
const noMatch = (
  <Result
    status={403}
    title="403"
    subTitle="Sorry, you are not authorized to access this page."
    extra={
      <Button type="primary">
        <Link to="/user/login">Go Login</Link>
      </Button>
    }
  />
);
```

```
/**
 * use Authorized check all menu item
 */
const menuDataRender = (menulist) =>
  menulist.map((item) => {
    const localItem = {
      ...item,
      children: item.children ? menuDataRender(item.children) : undefined,
    };

    console.log('33333', menulist);

    return Authorized.check(item.authority, localItem, null);
  });
```

```
const defaultFooterDom = (
  <DefaultFooter
    copyright={`${new Date().getFullYear()} 蚂蚁集团体验技术部出品`}
    links={[
      {
        key: 'Ant Design Pro',
        title: 'Ant Design Pro',
        href: 'https://pro.ant.design',
        blankTarget: true,
      },
      {
        key: 'github',
        title: <GithubOutlined />,
        href: 'https://github.com/ant-design/ant-design-pro',
        blankTarget: true,
      },
      {
        key: 'Ant Design',
        title: 'Ant Design',
        href: 'https://ant.design',
        blankTarget: true,
      },
    ]}
  />
);
```

```
const BasicLayout = (props) => {
  const {
    dispatch,
    children,
    settings,
    location = {
      pathname: '/',
    },
    menulist,
  } = props;

  const menuDataRef = useRef([]);
  console.log('111', menuDataRef);

  useEffect(() => {
    if (dispatch) {
      dispatch({
        type: 'menu/getmenulist',
        payload: {}
      });

      dispatch({
        type: 'user/fetchCurrent',
      });
    }
  }, []);
  /**
   * init variables
   */

  const handleMenuCollapse = (payload) => {
    if (dispatch) {
      dispatch({
        type: 'global/changeLayoutCollapsed',
        payload,
      });
    }
  }; // get children authority

  const authorized = useMemo(
    () =>
      getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
        authority: undefined,
      },
    [location.pathname],
  );
  
  console.log('222', menulist);
  const { formatMessage } = useIntl();

  return (
    <>
      <ProLayout
        logo={logo}
        formatMessage={formatMessage}
        {...props}
        {...settings}
        onCollapse={handleMenuCollapse}
        onMenuHeaderClick={() => history.push('/')}
        menuItemRender={(menuItemProps, defaultDom) => {
          if (menuItemProps.isUrl || !menuItemProps.path) {
            return defaultDom;
          }
          return <Link to={menuItemProps.path}>{defaultDom}</Link>;
        }}
        breadcrumbRender={(routers = []) => [
          {
            path: '/',
            breadcrumbName: formatMessage({
              id: 'menu.home',
            }),
          },
          ...routers,
        ]}
        itemRender={(route, params, routes, paths) => {
          const first = routes.indexOf(route) === 0;
          return first ? (
            <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
          ) : (
              <span>{route.breadcrumbName}</span>
            );
        }}
        footerRender={() => defaultFooterDom}
        menuDataRender={() => menuDataRender(menulist)}
        rightContentRender={() => <RightContent />}
      // postMenuData={(menuData) => {
      //   menuDataRef.current = menuData || [];
      //   return menuData || [];
      // }}
      >
        <Authorized authority={authorized.authority} noMatch={noMatch}>
          {children}
        </Authorized>
      </ProLayout>
      <SettingDrawer
        settings={settings}
        onSettingChange={(config) =>
          dispatch({
            type: 'settings/changeSetting',
            payload: config,
          })
        }
      />
    </>
  );
};
```

```
export default connect(({ global, settings, menu }) => ({
  collapsed: global.collapsed,
  settings,
  menulist: menu.menulist,
}))(BasicLayout);

```
-->

### © 版本信息

- umi 版本 3.2.27
- 浏览器环境  chrome 87
- 开发环境 [e.g. mac OS] windows 10
ant design pro版本：V4，基于Javascript（非Typescript）
pro-layout版本：6.5.15

### 🚑 其他信息

第一次进去后可以正常显示菜单，如下图：
![image](https://user-images.githubusercontent.com/64385313/99822899-b95a8600-2b8e-11eb-9892-7b64c21d65b9.png)

但是我在地址位输入其他网址，左右的菜单不显示了，如下图：

![image](https://user-images.githubusercontent.com/64385313/99823232-17876900-2b8f-11eb-84e4-9dc033b0317c.png)

**Comment by cdxcom** [comment]
BasicLayout.jsx代码：
import ProLayout, { DefaultFooter, SettingDrawer } from '@ant-design/pro-layout';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useIntl, connect, history } from 'umi';
import { GithubOutlined } from '@ant-design/icons';
import { Result, Button } from 'antd';
import Authorized from '@/utils/Authorized';
import RightContent from '@/components/GlobalHeader/RightContent';
import { getMatchMenu } from '@umijs/route-utils';
import logo from '../assets/logo.svg';

const noMatch = (
  <Result
    status={403}
    title="403"
    subTitle="Sorry, you are not authorized to access this page."
    extra={
      <Button type="primary">
        <Link to="/user/login">Go Login</Link>
      </Button>
    }
  />
);

/**
 * use Authorized check all menu item
 */
const menuDataRender = (menulist) =>
  menulist.map((item) => {
    const localItem = {
      ...item,
      children: item.children ? menuDataRender(item.children) : undefined,
    };

    console.log('33333', menulist);

    return Authorized.check(item.authority, localItem, null);
  });

const defaultFooterDom = (
  <DefaultFooter
    copyright={`${new Date().getFullYear()} 蚂蚁集团体验技术部出品`}
    links={[
      {
        key: 'Ant Design Pro',
        title: 'Ant Design Pro',
        href: 'https://pro.ant.design',
        blankTarget: true,
      },
      {
        key: 'github',
        title: <GithubOutlined />,
        href: 'https://github.com/ant-design/ant-design-pro',
        blankTarget: true,
      },
      {
        key: 'Ant Design',
        title: 'Ant Design',
        href: 'https://ant.design',
        blankTarget: true,
      },
    ]}
  />
);

const BasicLayout = (props) => {
  const {
    dispatch,
    children,
    settings,
    location = {
      pathname: '/',
    },
    menulist,
  } = props;

  const menuDataRef = useRef([]);
  console.log('111', menuDataRef);

  useEffect(() => {
    if (dispatch) {
      dispatch({
        type: 'menu/getmenulist',
        payload: {}
      });

      dispatch({
        type: 'user/fetchCurrent',
      });
    }
  }, []);
  /**
   * init variables
   */

  const handleMenuCollapse = (payload) => {
    if (dispatch) {
      dispatch({
        type: 'global/changeLayoutCollapsed',
        payload,
      });
    }
  }; // get children authority

  const authorized = useMemo(
    () =>
      getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
        authority: undefined,
      },
    [location.pathname],
  );
  
  console.log('222', menulist);
  const { formatMessage } = useIntl();

  return (
    <>
      <ProLayout
        logo={logo}
        formatMessage={formatMessage}
        {...props}
        {...settings}
        onCollapse={handleMenuCollapse}
        onMenuHeaderClick={() => history.push('/')}
        menuItemRender={(menuItemProps, defaultDom) => {
          if (menuItemProps.isUrl || !menuItemProps.path) {
            return defaultDom;
          }
          return <Link to={menuItemProps.path}>{defaultDom}</Link>;
        }}
        breadcrumbRender={(routers = []) => [
          {
            path: '/',
            breadcrumbName: formatMessage({
              id: 'menu.home',
            }),
          },
          ...routers,
        ]}
        itemRender={(route, params, routes, paths) => {
          const first = routes.indexOf(route) === 0;
          return first ? (
            <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
          ) : (
              <span>{route.breadcrumbName}</span>
            );
        }}
        footerRender={() => defaultFooterDom}
        menuDataRender={() => menuDataRender(menulist)}
        rightContentRender={() => <RightContent />}
      // postMenuData={(menuData) => {
      //   menuDataRef.current = menuData || [];
      //   return menuData || [];
      // }}
      >
        <Authorized authority={authorized.authority} noMatch={noMatch}>
          {children}
        </Authorized>
      </ProLayout>
      <SettingDrawer
        settings={settings}
        onSettingChange={(config) =>
          dispatch({
            type: 'settings/changeSetting',
            payload: config,
          })
        }
      />
    </>
  );
};

export default connect(({ global, settings, menu }) => ({
  collapsed: global.collapsed,
  settings,
  menulist: menu.menulist,
}))(BasicLayout);

**Comment by cdxcom** [comment]
今天特意更新了下npm包，发现用pro-layout的6.5.0之前的版本（我只试过一个6.4.3），同样的代码，一切正常
然后用6.5.6版本也试了下，发现了同样的问题。
所以请大佬可否帮忙看下，是我写法哪里不对还是什么问题？
非常感谢ant-design的开源，让我们这些非专业前端也能玩起这么高大上的东西

**Comment by chenshuai2144** [comment]
路由配置 也贴一下

**Comment by cdxcom** [comment]
import { defineConfig } from 'umi';
import defaultSettings from './defaultSettings';
import proxy from './proxy';
const { REACT_APP_ENV } = process.env;
export default defineConfig({
  hash: true,
  antd: {},
  dva: {
    hmr: true,
  },
  history: {
    type: 'browser',
  },
  locale: {
    // default zh-CN
    default: 'zh-CN',
    antd: true,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: true,
  },
  dynamicImport: {
    loading: '@/components/PageLoading/index',
  },
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  routes: [
    {
      path: '/',
      component: '../layouts/BlankLayout',
      routes: [
        {
          path: '/user',
          component: '../layouts/UserLayout',
          routes: [
            {
              path: '/user',
              redirect: '/user/login',
            },
            {
              name: 'login',
              icon: 'smile',
              path: '/user/login',
              component: './user/login',
            },
            {
              name: 'register-result',
              icon: 'smile',
              path: '/user/register-result',
              component: './user/register-result',
            },
            {
              name: 'register',
              icon: 'smile',
              path: '/user/register',
              component: './user/register',
            },
            {
              component: '404',
            },
          ],
        },
        {
          path: '/',
          // component: '../layouts/BasicLayoutOri',
          component: '../layouts/BasicLayoutJob',
          Routes: ['src/pages/Authorized'],
          // authority: ['admin', 'user'],
          routes: [
            {
              path: '/',
              redirect: '/home/jobhome',
            },
            {
              path: '/home',
              name: '首页',
              icon: 'home',
              routes: [
                {
                  path: '/',
                  redirect: '/home/jobhome',
                },
                {
                  name: 'Job Home',
                  icon: 'smile',
                  path: '/home/jobhome',
                  component: './home/jobhome',
                },
                {
                  name: 'Other Home',
                  icon: 'smile',
                  path: '/home/otherhome',
                  component: './home/otherhome',
                },
              ],
            },
            {
              path: '/jobtask',
              name: '任务管理',
              icon: 'dashboard',
              routes: [
                {
                  path: '/',
                  redirect: '/jobtask/jobquery',
                },
                {
                  name: '任务查询',
                  icon: 'smile',
                  path: '/jobtask/jobquery',
                  component: './jobtask/jobquery',
                },
                {
                  name: '任务管理',
                  icon: 'smile',
                  path: '/jobtask/dbjob',
                  component: './jobtask/dbjob',
                },
                {
                  name: '其他任务',
                  icon: 'smile',
                  path: '/jobtask/otherjob',
                  component: './jobtask/otherjob',
                },
              ],
            },
            {
              path: '/power',
              name: '权限管理',
              icon: 'dashboard',
              routes: [
                {
                  path: '/',
                  redirect: '/power/role',
                },
                {
                  name: '菜单管理',
                  icon: 'smile',
                  path: '/power/menu',
                  component: './power/menu',
                },
                {
                  name: '角色管理',
                  icon: 'smile',
                  path: '/power/role',
                  component: './power/role',
                },
                {
                  name: '用户管理',
                  icon: 'smile',
                  path: '/power/user',
                  component: './power/user',
                },
              ],
            },
            {
              path: '/dashboard',
              name: 'dashboard',
              icon: 'dashboard',
              routes: [
                {
                  path: '/',
                  redirect: '/dashboard/analysis',
                },
                {
                  name: 'analysis',
                  icon: 'smile',
                  path: '/dashboard/analysis',
                  component: './dashboard/analysis',
                },
                {
                  name: 'monitor',
                  icon: 'smile',
                  path: '/dashboard/monitor',
                  component: './dashboard/monitor',
                },
                {
                  name: 'workplace',
                  icon: 'smile',
                  path: '/dashboard/workplace',
                  component: './dashboard/workplace',
                },
              ],
            },
            {
              path: '/form',
              name: 'form',
              icon: 'form',
              routes: [
                {
                  path: '/',
                  redirect: '/form/basic-form',
                },
                {
                  name: 'basic-form',
                  icon: 'smile',
                  path: '/form/basic-form',
                  component: './form/basic-form',
                },
                {
                  name: 'step-form',
                  icon: 'smile',
                  path: '/form/step-form',
                  component: './form/step-form',
                },
                {
                  name: 'advanced-form',
                  icon: 'smile',
                  path: '/form/advanced-form',
                  component: './form/advanced-form',
                },
              ],
            },
            {
              path: '/list',
              name: 'list',
              icon: 'table',
              routes: [
                {
                  path: '/list/search',
                  name: 'search-list',
                  component: './list/search',
                  routes: [
                    {
                      path: '/list/search',
                      redirect: '/list/search/articles',
                    },
                    {
                      name: 'articles',
                      icon: 'smile',
                      path: '/list/search/articles',
                      component: './list/search/articles',
                    },
                    {
                      name: 'projects',
                      icon: 'smile',
                      path: '/list/search/projects',
                      component: './list/search/projects',
                    },
                    {
                      name: 'applications',
                      icon: 'smile',
                      path: '/list/search/applications',
                      component: './list/search/applications',
                    },
                  ],
                },
                {
                  path: '/',
                  redirect: '/list/table-list',
                },
                {
                  name: 'table-list',
                  icon: 'smile',
                  path: '/list/table-list',
                  component: './list/table-list',
                },
                {
                  name: 'basic-list',
                  icon: 'smile',
                  path: '/list/basic-list',
                  component: './list/basic-list',
                },
                {
                  name: 'card-list',
                  icon: 'smile',
                  path: '/list/card-list',
                  component: './list/card-list',
                },
              ],
            },
            {
              path: '/exception',
              name: 'exception',
              icon: 'warning',
              routes: [
                {
                  path: '/',
                  redirect: '/exception/403',
                },
                {
                  name: '403',
                  icon: 'smile',
                  path: '/exception/403',
                  component: './exception/403',
                },
                {
                  name: '404',
                  icon: 'smile',
                  path: '/exception/404',
                  component: './exception/404',
                },
                {
                  name: '500',
                  icon: 'smile',
                  path: '/exception/500',
                  component: './exception/500',
                },
              ],
            },
            {
              name: 'account',
              path: '/account',
              icon: 'user',
              routes: [
                {
                  path: '/',
                  redirect: '/account/center',
                },
                {
                  name: 'center',
                  icon: 'smile',
                  path: '/account/center',
                  component: './account/center',
                },
                {
                  name: 'settings',
                  icon: 'smile',
                  path: '/account/settings',
                  component: './account/settings',
                },
              ],
            },
            {
              component: '404',
            },
          ],
        },
      ],
    },
  ],
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    'primary-color': defaultSettings.primaryColor,
  },
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  manifest: {
    basePath: '/',
  },
  exportStatic: {},
  esbuild: {},
});

**Comment by chenshuai2144** [comment]
来个repo 吧。没看出来问题。估计是路由匹配的问题

**Comment by cdxcom** [comment]
目前6.5.0版本可以满足我的要求了，我就先用这个版本吧，等后续再有新版之后我再更新试下。
repo我没怎么弄过，不太会上传，不过我这个里面除了config.js和basiclayout.jsx这两个文件有改动（当然也加了menu的services和model，加了几个page），其他均没有变化。
谢谢大佬的回复。

**Comment by binyellow** [comment]
这个地方其实是有bug的，是由于下面的memo带来的authorized获取迟滞
```js
const authorized = useMemo(
    () => getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
      authority: undefined,
    },
    [location.pathname],
  );
```
解决办法是
```js
  useEffect(() => {
    setAuthorized(getMatchMenu(location.pathname || '/', menuDataRef.current, true, true).pop() as any || {
      authority: undefined,
    });
  }, [location.pathname, menuDataRef.current?.length]);
```

**Comment by chenshuai2144** [comment]
@binyellow 老哥来个 pr？ 或者直接取消 memo 了

**Comment by free-pan** [comment]
我也遇到类似问题。我的情况是动态菜单，菜单数据从服务器加载, 当加载到菜单数据之后，左侧菜单未显示。后台我看了pro-layout的源码, 发现是`getMenuData`那未重新计算最新的菜单(因为入参未改变，所以用的是缓存结果)

```
// pro-layout的BasicLayout.tsx

....
const [menuInfoData, setMenuInfoData] = useMergedState<{
    breadcrumb?: Record<string, MenuDataItem>;
    breadcrumbMap?: Map<string, MenuDataItem>;
    menuData?: MenuDataItem[];
  }>(() => getMenuData(route?.routes || [], menu, formatMessage, menuDataRender));
....
```

发现了原因，是因为入参未改变，所以使用了缓存，那么只要入参与上一次不同，自然就会重新计算了。而getMenuData有3个参数, 第三，第四个参数为函数，没法使函数变得不一样，第一，第二个参数为对象，因此这要这两个参数的其中一个变得不一样，这样就不会使用缓存了。因此这是我的做法(注意`useEffect`和`route={customRoute}`):

```
const Index: React.FC<IndexProps> = (props) => {
...
const [customRoute,setCustomRoute] = useState<any>(null);

  const dispatch = useDispatch();
  const effectMethods = {
    searchMenuList: 'GlobalModel/searchMenuList',
    setSelectedMenuAndBreadcrumb: 'GlobalModel/setSelectedMenuAndBreadcrumb',
  };
// @ts-ignore
  const loadingEffect = useSelector((state) => state.loading);
  // 获取菜单数据加载状态
  const menuLoading = loadingEffect.effects[effectMethods.searchMenuList];
  // 获取菜单数据
  // @ts-ignore
  const menuList = useSelector((state) => state.GlobalModel.menuList);

// 仅在组件第一次初始化时调用
  useEffect(() => {
    dispatch({
      type: effectMethods.searchMenuList,
      payload: {pathname: history.location.pathname},
    });
  }, []);

  useEffect(()=>{
    console.log('menuList',menuList,menuLoading)
    // 当菜单加载完毕,则更新自定路由数据(重点在这个d属性),使得pro-layout的菜单能够更新为最新菜单
    setCustomRoute({routes:[],d:new Date()})
  },[menuLoading])

return (
    <ConfigProvider locale={loadLocaleByCode(languageCode)}>
      <ProLayout
        route={customRoute}
        menu={{locale: false}}
        fixedHeader={true}
        fixSiderbar={true}
        headerRender={() => customHeader}
        menuContentRender={(_, dom) =>
          menuLoading ? (
            <div
              style={{
                padding: '24px 0',
              }}
            >
              <Spin tip="菜单加载中">{dom}</Spin>
            </div>
          ) : (
            dom
          )
        }
        title="后台管理模板"
        logo="https://gw.alipayobjects.com/mdn/rms_b5fcc5/afts/img/A*1NHAQYduQiQAAAAAAAAAAABkARQnAQ"
        location={{
          pathname: history.location.pathname,
        }}
        menuDataRender={() => {
          return loopMenuItem(menuList)
        }}
        menuProps={{
          onOpenChange: (keyArr) => {
            // @ts-ignore
            setOpenKeys([...keyArr]);
          },
          openKeys: openKeys,
          selectedKeys: [history.location.pathname],
          /**
           * 监听菜单项点击
           * @param key
           * @param keyPath
           */
          onClick: function ({key, keyPath, item, domEvent}) {
            dispatch({
              type: effectMethods.setSelectedMenuAndBreadcrumb,
              payload: {selectedMenuItemPath: key},
            });
            history.push(key);
          },
        }}
      >
        {props.children}
      </ProLayout>
    </ConfigProvider>
  );
...
};
```

详细代码可以参考我的开源项目:
https://gitee.com/free_pan/pzy-easy-pro

**Comment by MeatZun** [comment]
升级了版本后，我也遇到了同样的问题，希望官方还是给个解决方案吧。

**Comment by chenshuai2144** [comment]
试试新的 api，request

https://procomponents.ant.design/components/layout#layout-dynamicmenu

**Comment by weed-x** [comment]
> 试试新的 api，request
> 
> https://procomponents.ant.design/components/layout#layout-dynamicmenu

我也碰到类似的问题了，使用menuDataRender或者menu的request都无法正常渲染左侧菜单树，下面是我BasicLayout的代码：
```
import ProLayout from '@ant-design/pro-layout';
import React, {useEffect} from 'react';
import {connect } from 'dva';
import {Link, history } from "umi";
import logo from '@/assets/images/logo.png';
import { SmileOutlined, HeartOutlined } from '@ant-design/icons';
const IconMap = {
  smile: <SmileOutlined />,
  heart: <HeartOutlined />,
};
  

const BasicLayout = (props) => {
  const {
    dispatch,
    children,
    settings,
    menus,
    location = {
      pathname: '/',
    },
  } = props;

  const loopMenuItem = (menu) => {
    console.log('处理菜单ing,menu is:',menu);
    return menu.map(({ icon, routes, ...item }) => ({  
      ...item,
      icon: icon && IconMap[icon],
      routes: routes && loopMenuItem(routes),
    }));
  }

  console.log('页面渲染ing, menus is:', menus);

  useEffect(() => {
    dispatch({
      type: 'user/fetchMenu',
    });
  }, []);

  const handleMenuCollapse = (payload) => {
    if (dispatch) {
      dispatch({
        type: 'global/changeLayoutCollapsed',
        payload,
      });
    }
  }; 

  return (
    <React.Fragment>
      <ProLayout
        style={{
          height: '100vh'
        }}
        logo={logo}
        {...settings}
        onCollapse={handleMenuCollapse}
        onMenuHeaderClick={() => history.push('/')}
        menuItemRender={(menuItemProps, defaultDom) => {
          if (
            menuItemProps.isUrl ||
            !menuItemProps.path ||
            location.pathname === menuItemProps.path
          ) {
            return defaultDom;
          }

          return <Link to={menuItemProps.path}>{defaultDom}</Link>;
        }}
        breadcrumbRender={(routers = []) => {
          return [
            {
              path: '/',
              breadcrumbName: '首页',
            },
            ...routers,
          ]
        }}
        itemRender={(route, params, routes, paths) => {
          const first = routes.indexOf(route) === 0;
          return first ? (
            <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
          ) : (
            <span>{route.breadcrumbName}</span>
          );
        }}
        // menu={{
        //   request: async () => {
        //     // await waitTime(2000);
        //     return loopMenuItem(menus);
        //   },
        // }}
        menuDataRender={() => loopMenuItem(menus)}
      >
      </ProLayout>
    </React.Fragment>
  );
};

export default connect(({ global, settings, user }) => ({
 collapsed: global.collapsed,
 settings,
 menus: user.menu
}))(BasicLayout);
```
控制台打印的结果是：
![image](https://user-images.githubusercontent.com/66823026/114515947-7d27df00-9c6f-11eb-898c-c7f2d2ee62bb.png)
发现当store中state改变时并没有重新渲染左侧菜单

**Comment by DevXiaolan** [comment]
希望重新打开问题，官方还没给出一个简单的修复方案
