### ISSUE TITLE
pro-table 设置locale 中 emptyText 无效

### ISSUE THREAD

**Issue by wxf-start** [ant-design/pro-components#105]
### 🐛 bug 描述
pro-table 设置locale 中 emptyText 无效

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/37679380/89392966-c321c000-d73c-11ea-81e5-4906fed232d0.png)
![image](https://user-images.githubusercontent.com/37679380/89392981-cae16480-d73c-11ea-8c29-680e1dabc44f.png)

### 🏞 期望结果
期望emptyText有改变

### 💻 复现代码

    locale={{
          emptyText:'请先选择搜索条件'
        }}

### © 版本信息

  "@ant-design/pro-table": "^2.4.2",
  "@umijs/preset-react": "^1.5.6",
  "@umijs/test": "^3.2.3",
 开发环境：windows

**Comment by chenshuai2144** [comment]
emmm, 这个不是在 pro- table 中控制的，要在这里使用
https://ant.design/components/config-provider-cn/

我们现在还没有 api 来自定义这个属性。

**Comment by wxf-start** [comment]
哦哦，好的谢谢啦，哈哈哈哈
