### ISSUE TITLE
🧐[问题]请问proform 能和 antd form 一样吗， label 和输入组件显示在通一行

### ISSUE THREAD

**Issue by ZhiGang-Fang** [ant-design/pro-components#1051]
### 🧐 问题描述

在使用proform 时发现label 的值和 输入的组件是换行的， 请问可以现在在同一行吗？ 我看到api 中看到 支持除 wrapperCol | labelCol | layout 外的其他 antd Form 组件参数， 请问有什么方法可以显示在同一行呢？ 还是说目前proform 不支持这样显示（至少我在demo 中没有看到），谢谢

需要显示效果： https://codesandbox.io/s/uw90g

**Comment by chenshuai2144** [comment]
试试这个 API

layout | 表单布局 |` horizontal \| vertical \| inline | horizontal`
-- | -- | -- | --


https://ant.design/components/form-cn/#API

**Comment by hongmaoxiao** [comment]
> ### 🧐 问题描述
> 在使用proform 时发现label 的值和 输入的组件是换行的， 请问可以现在在同一行吗？ 我看到api 中看到 支持除 wrapperCol | labelCol | layout 外的其他 antd Form 组件参数， 请问有什么方法可以显示在同一行呢？ 还是说目前proform 不支持这样显示（至少我在demo 中没有看到），谢谢
> 
> 需要显示效果： https://codesandbox.io/s/uw90g

点赞是有用了吗？我用了这个api，发现没有起效果呢

**Comment by hongmaoxiao** [comment]
> ### 🧐 问题描述
> 在使用proform 时发现label 的值和 输入的组件是换行的， 请问可以现在在同一行吗？ 我看到api 中看到 支持除 wrapperCol | labelCol | layout 外的其他 antd Form 组件参数， 请问有什么方法可以显示在同一行呢？ 还是说目前proform 不支持这样显示（至少我在demo 中没有看到），谢谢
> 
> 需要显示效果： https://codesandbox.io/s/uw90g

用错地方了，有效果了

**Comment by my9988** [comment]
> 
> 
> > ### 🧐 问题描述
> > 在使用proform 时发现label 的值和 输入的组件是换行的， 请问可以现在在同一行吗？ 我看到api 中看到 支持除 wrapperCol | labelCol | layout 外的其他 antd Form 组件参数， 请问有什么方法可以显示在同一行呢？ 还是说目前proform 不支持这样显示（至少我在demo 中没有看到），谢谢
> > 需要显示效果： https://codesandbox.io/s/uw90g
> 
> 用错地方了，有效果了

@hongmaoxiao 我也有此需求，能否分享下代码？

**Comment by chenshuai2144** [comment]
写到第一级

**Comment by fullee** [comment]
黑人❓

**Comment by fullee** [comment]
这样是正常的
```jsx
<ProForm<{
    name: string;
    company?: string;
    useMode?: string;
}>
    form={form}
    size={'small'}
    layout="horizontal"
    request={async () => {
        return {
            name: '蚂蚁设计有限公司',
            useMode: 'chapter',
        };
    }}
>
```
![image](https://user-images.githubusercontent.com/11188837/120274994-3c4d5d80-c2e3-11eb-92b3-38a941245dc2.png)
