### ISSUE TITLE
👑 [需求]ProCard不支持暗黑模式

### ISSUE THREAD

**Issue by baiheinet** [ant-design/pro-components#1053]
### 🥰 需求描述

Card 支持暗黑模式，ProCard不支持暗黑模式

### 🚑 其他信息

[image](https://user-images.githubusercontent.com/900786/99890265-6967e600-2c98-11eb-9bb9-7c2ae7d4ae52.png)

**Comment by chenshuai2144** [comment]
fixed，已经发版本了

**Comment by changlin0501** [comment]
请问哪个版主ProCard支持暗黑模式呢

**Comment by chenshuai2144** [comment]
直接用最新的
