### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by VingoChen** [ant-design/pro-components#1059]
### 🐛 bug 描述

  组件中引入后提示 需要类型声明
```
/node_modules/@ant-design/pro-field/lib/index.d.ts(15,1):
Declaration or statement expected.  TS1128

    13 | import FiledSelect, { ProFieldValueEnumType, ProFieldRequestData, proFieldParsingText, proFieldParsingValueEnumToArray } from './components/Select';
    14 | export declare type ProFieldTextType = React.ReactNode | React.ReactNode[] | Moment | Moment[];
  > 15 | export type { ProFieldValueEnumType };
       | ^
    16 | export declare type ProFieldEmptyText = string | false;
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Mis-tian** [comment]
> ### 🐛 bug 描述
> 组件中引入后提示 需要类型声明
> 
> ```
> /node_modules/@ant-design/pro-field/lib/index.d.ts(15,1):
> Declaration or statement expected.  TS1128
> 
>     13 | import FiledSelect, { ProFieldValueEnumType, ProFieldRequestData, proFieldParsingText, proFieldParsingValueEnumToArray } from './components/Select';
>     14 | export declare type ProFieldTextType = React.ReactNode | React.ReactNode[] | Moment | Moment[];
>   > 15 | export type { ProFieldValueEnumType };
>        | ^
>     16 | export declare type ProFieldEmptyText = string | false;
> ```
> 
> ### 📷 复现步骤
> ### 🏞 期望结果
> ### 💻 复现代码
> ### © 版本信息
> * ProComponents 版本: [e.g. 4.0.0]
> * umi 版本
> * 浏览器环境
> * 开发环境 [e.g. mac OS]
> 
> ### 🚑 其他信息
