### ISSUE TITLE
🧐[问题] CreateForm新增数据的时候，怎么重置某个字段的值？

### ISSUE THREAD

**Issue by yangdachu** [ant-design/pro-components#1060]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/23580181/99941196-91466f00-2da8-11eb-90ea-16c5378db337.png)
![image](https://user-images.githubusercontent.com/23580181/99941981-e3d45b00-2da9-11eb-81d3-b4269696536f.png)

品牌数据清空后，怎么删除之前选择的默认值？

**Comment by binvb** [comment]
你可以用renderFormItem自定义渲染的输入项，然后通过onchange事件去修改其他关联选项，但其实这个renderFormItem不太好用，还有些bug，比较复杂的表单建议自己写。

**Comment by chenshuai2144** [comment]
`  formRef.current?.resetFields();` 可以用这个
