### ISSUE TITLE
🧐[问题] layout menu 报错 TypeError: Can only call Window.cancelAnimationFrame on instances of Window

### ISSUE THREAD

**Issue by bxvs888** [ant-design/pro-components#1061]
### 🧐 问题描述

 TypeError: Can only call Window.cancelAnimationFrame on instances of Window

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/298322/99946640-a4aa0800-2db1-11eb-8b57-b09df6b488c6.png)

**Comment by bxvs888** [comment]
TypeError: Can only call Window.cancelAnimationFrame on instances of Window

![image](https://user-images.githubusercontent.com/298322/99946747-dc18b480-2db1-11eb-9f01-5c12d3e74d08.png)

**Comment by chenshuai2144** [comment]
去 antd 问问把 [ `window.cancelAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelAnimationFrame) 是个常见的API，估计是什么配置错误了。
