### ISSUE TITLE
🐛[BUG] ProFormDigit点击右侧的加减变更值时无法触发ProForm的onChange事件

### ISSUE THREAD

**Issue by James-Beaan** [ant-design/pro-components#1064]
ProFormDigit组件在点击如下图指示的增加或减少digit数值时，无法触发ProForm的onChange事件，但在数值输入数值时onChange触发正常

![image](https://user-images.githubusercontent.com/74655789/99980580-5a417f00-2de3-11eb-93bb-ddbc67814e25.png)

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
