### ISSUE TITLE
🐛[BUG] valueType="date"，再设置ellipsis后tooltip的显示为时间戳

### ISSUE THREAD

**Issue by Willworkgogogo** [ant-design/pro-components#1065]
### 🐛 bug 描述
ProTable的Column设置valueType="date"，再设置ellipsis后tooltip的显示为时间戳

### 📷 复现步骤

1. 设置valueType: "date"
2. 添加ellipsis: true
3. 鼠标悬浮内容显示错误

### 🏞 期望结果

tooltip显示内容和render的内容一致

### 💻 复现代码

https://codesandbox.io/s/falling-tdd-s0upv?fontsize=14&hidenavigation=1&theme=dark

### © 版本信息

- ProComponents 版本: ProTable 2.9.16
- umi 版本 umi@3.2.23
- 浏览器环境 Chrome86.0.4240.183
- 开发环境 mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20815934/100038015-365f5700-2e3e-11eb-8946-e6585209e739.png)

**Comment by chenshuai2144** [comment]
想了一下，tooltip 就应该展示原本的值方便 copy
