### ISSUE TITLE
🐛[BUG] pro-layout@6.5.15 会导致右侧菜单栏选中多个

### ISSUE THREAD

**Issue by AsherSun** [ant-design/pro-components#1066]
### 🐛 bug 描述

`pro-layout@6.5.15` 会导致右侧菜单栏选中多个，如图：
![image](https://user-images.githubusercontent.com/28916706/100042627-cdc8a800-2e46-11eb-9d91-007d75e83c3a.png)

版本降级不会出现这个问题,目前我是降级到`6.4.16`

### 📷 复现步骤

- 设置路由: 
```javascript
{
path: '/material/list',
},

{
 path: '/material/list/stock',
}
```

如果路由走 `/material/list/stock` 菜单栏也会匹配到 `/material/list`

### 🏞 期望结果
期望和之前一样，版本升级不会影响到现有业务逻辑

### 💻 复现代码

```javascript
{
path: '/material/list',
},

{
 path: '/material/list/stock',
}
```

**Comment by chenshuai2144** [comment]
你这个太像了，prolayout认为是子节点，你专门设置一下key把
