### ISSUE TITLE
🐛[BUG]layout的收缩按钮失效

### ISSUE THREAD

**Issue by phoema** [ant-design/pro-components#1067]
### 🐛 bug 描述
pro-layout@6.5.15
ant design 4.8.5
在ant design pro的源码下，升级到ant design 4.8.5
layout的收缩按钮失效

### 📷 复现步骤
回退到ant design 4.8.4正常
在ant design 4.8.5的layout基础组件，收缩正常
https://codesandbox.io/s/so44g?file=/index.js

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
测试用例看起来没问题，执行 `git clean -dfx` 再安装一下依赖好了。

**Comment by phoema** [comment]
#1076

**Comment by phoema** [comment]
https://github.com/ant-design/ant-design-pro/issues/7652
