### ISSUE TITLE
🐛[BUG] 官方文档中提供的过滤无效

### ISSUE THREAD

**Issue by zhuqiu** [ant-design/pro-components#1071]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30789023/100065087-527aec80-2e6e-11eb-8cf0-69cab82fc304.png)

**Comment by chenshuai2144** [comment]
2.10.0 默认打开了
