### ISSUE TITLE
🧐[问题]请求结束之前，有办法打断当前request重新发一个request吗

### ISSUE THREAD

**Issue by zstiu** [ant-design/pro-components#1072]
### 🧐 [问题]

如果接口请求比较慢，在请求结束之前，有办法打断当前request重新发一个request吗？
目前我尝试的点击search或者reset都无法重新发请求，包括手动触发reload方法。

**Comment by chenshuai2144** [comment]
暂时是不行的，你可以包装一下fetch，加个超时时间

**Comment by insistenceZHUO** [comment]
> ### 🧐 [问题]
> 如果接口请求比较慢，在请求结束之前，有办法打断当前request重新发一个request吗？
> 目前我尝试的点击search或者reset都无法重新发请求，包括手动触发reload方法。

你的问题解决了吗？作者说用fetch包装下，没明白意思？要怎么做

**Comment by chenshuai2144** [comment]
http://blog.yidengxuetang.com/post/202003/23/

看看这个文章，其实就是让请求库支持

**Comment by KellenHe** [comment]
> 暂时是不行的，你可以包装一下fetch，加个超时时间

包装一个fetch，怎么取到request里的参数？
