### ISSUE TITLE
🐛[BUG] pro-layout 版本为6.5.15 左侧菜单底部缩回按钮点击无效，侧边栏无法收回

### ISSUE THREAD

**Issue by pzc666** [ant-design/pro-components#1076]
### 🐛 bug 描述
pro-layout 版本为6.5.15 左侧菜单底部缩回按钮点击无效，侧边栏无法收回
### 📷 复现步骤
ant design pro preview 和 pro-components  preview 页面稳定复现
https://preview.pro.ant.design/dashboard/analysis?splitMenus=false&primaryColor=daybreak&navTheme=light
https://procomponents.ant.design/components/layout

### 🏞 期望结果
侧边栏可以正常收回展开

### 💻 复现代码
https://preview.pro.ant.design/dashboard/analysis?splitMenus=false&primaryColor=daybreak&navTheme=light
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- pro-layout 版本 6.5.15
- umi 版本 3.2.28
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
abtd 的锅，可以设置 breakpoint={false} 先绕过一下，下周一就会修复

**Comment by chenshuai2144** [comment]
antd 发布了，大家更新版本
