### ISSUE TITLE
🐛[BUG]ProFormSwitch readonly状态下显示错误

### ISSUE THREAD

**Issue by BooYeu** [ant-design/pro-components#1077]
### 🐛 bug 描述

readonly下一直显示unCheckedChildren的内容

### 📷 复现步骤

              <ProFormSwitch
                readonly
                name="show"
                label="对不对"
                checkedChildren="对"
                unCheckedChildren="错"
                fieldProps={{defaultChecked: true}}
              />
显示“错”
### 🏞 期望结果

defaultChecked为true时显示checkedChildren的内容

### 💻 复现代码

             <ProFormSwitch
                readonly
                name="show"
                label="对不对"
                checkedChildren="对"
                unCheckedChildren="错"
                fieldProps={{defaultChecked: true}}
              />

### © 版本信息

- ProComponents 版本: 4.8.5
- umi 版本 3.2.28
- 浏览器环境 Edge
- 开发环境 windows

##🚑 其他信息

无

**Comment by BooYeu** [comment]
<ProFormSwitch
            readonly
            name="show"
            label="对不对"
            checkedChildren="对"
            unCheckedChildren="错"
            initialValue='checked'
          /> 和
<ProFormSwitch
            readonly
            name="show"
            label="对不对"
            checkedChildren="对"
            unCheckedChildren="错"
            initialValue
          />
也不行 也是显示“错”

**Comment by chenshuai2144** [comment]
`<ProFormSwitch readonly name="show" label="对不对" checkedChildren="对" unCheckedChildren="错" initialValue={true} />`

这样呢

**Comment by BooYeu** [comment]
> `<ProFormSwitch readonly name="show" label="对不对" checkedChildren="对" unCheckedChildren="错" initialValue={true} />`
> 
> 这样呢

还是不行的

**Comment by BooYeu** [comment]
我看proformswitch和profield源文件有个text判断
但只是判断了value 没有intialvalue的判断？

**Comment by BooYeu** [comment]
`
<ProFormSwitch readonly name="show" label="对不对" checkedChildren="对" unCheckedChildren="错" proFieldProps={{checked: false}} />
`

然后pro-form的Switch里的text属性拉出来，改为：
`
  return /*#__PURE__*/React.createElement(ProField, _extends({
    valueType: "switch",
    mode: "edit",
    fieldProps: _objectSpread( fieldProps, {}, {
      unCheckedChildren: unCheckedChildren,
      checkedChildren: checkedChildren
    }),
    text: fieldProps === null || fieldProps === void 0 ? void 0 : fieldProps.checked,
    ref: ref
  }, proFieldProps));
`
这样可以解决，但是加了proformfield属性 ide或报错不友好？

**Comment by BooYeu** [comment]
#1082
