### ISSUE TITLE
👑 [需求] 请统一ProForm组件onFinish类型返回布尔或泛型.

### ISSUE THREAD

**Issue by KumaCool** [ant-design/pro-components#1080]
### 🥰 需求描述

`ProForm` 组件的`onFinish`监听道具实现泛型返回值或使用布尔返回值

```typescript
// Type run: (params: any) => any | boolean
const {run} = useRequest(service)
<ProForm onFinish={run} />
```
实际使用中一般api接口不会处理返回数据,`onFinish`根据返回的布尔类型来与按钮loading交互,所以配合的包装处理成返回布尔类型
但理想情况是应该是接口状态结束就应该改变loading状态.
否则我们要针对性的做个包装处理,很麻烦.
不处理报红看着也不爽.

`ProForm | ModalForm | DrawerForm` 等`onFinish`的类型也不是统一的...

**Comment by chenshuai2144** [comment]
`ModalForm | DrawerForm` 返回 boolean 会关闭弹框。

ProForm 是不需要的。boolean 是用 promise 来实现的。

**Comment by KumaCool** [comment]
感谢回复.
我觉得的在实际场景中大部分请求都不需要处理.
请求肯定会有返回值的,然而`onFinish`又强调 `=> Promise<void>`,这时为了ide不报红,就必须要强行包一层.
我觉得`Promise`状态结束时,就自动处理loading或弹框状态是最方便的,不应该还要由开发者再操心这些状态.
`Promise.finally()`直接通过它管理状态不好吗?

**Comment by chenshuai2144** [comment]
返回值和loading没有关系的 返回值控制的是viisit

**Comment by KumaCool** [comment]
```typescript
const fetch: (params: any) => Promise<any>
<ProForm onFinish={async () => {fetch}}>
<ModalForm onFinish={(params) => fetch(params).then(R.T).catch(R.F)} />
```
api接口一般都有返回值.
按照目前的类型定义,我必须要包一层才能让IDE不报错及满足组件交互条件.
我觉得没必要再让开发者做这些处理.

**Comment by chenshuai2144** [comment]
ModalForm 有特殊的逻辑，如果你想兼容我推荐你这么写。

`<ModalForm onFinish={await (values)=>{ await fetch(values) }} />`

为了少写一个方法体的偷懒没有意义的
