### ISSUE TITLE
🐛[BUG]ModalForm的initialValues指定常量没问题，从远程获取数据赋值就不行

### ISSUE THREAD

**Issue by hongmaoxiao** [ant-design/pro-components#1084]
### 🐛 bug 描述
如题，所以我目前只能在ProFormText的fieldProps里去设置defaultValue了，然后会一直提示去用initialValues，而不是用defaultValue

### 📷 复现步骤
正常构建路径，没啥特殊的

### © 版本信息

- ProComponents 版本: "@ant-design/pro-form": "1.6.2",
- umi 版本：umi@3.2.28
- 浏览器环境: chrome  87.0.4280.67
- 开发环境 [e.g. mac OS]: mac OS Catalina 10.15.7

**Comment by chenshuai2144** [comment]
initialValues 就是初始化才生效的意思，必须要在 初始化之前设置。
你可以 resetField 的来强行设置一下

**Comment by hongmaoxiao** [comment]
> initialValues 就是初始化才生效的意思，必须要在 初始化之前设置。
> 你可以 resetField 的来强行设置一下

好的

**Comment by JessieHelloWorld** [comment]
> initialValues 就是初始化才生效的意思，必须要在 初始化之前设置。
> 你可以 resetField 的来强行设置一下

请问具体怎么实现呢?

**Comment by JessieHelloWorld** [comment]
> initialValues 就是初始化才生效的意思，必须要在 初始化之前设置。
> 你可以 resetField 的来强行设置一下

ModalForm怎么获取的这个form实例？

**Comment by zy135516** [comment]
你好这个问题解决了吗？难倒要有值的时候才渲染modelForm吗

**Comment by chenshuai2144** [comment]
@zy135516  为什么不试试 setFieldValues 呢，什么时候都可以使用

**Comment by zy135516** [comment]
@chenshuai2144 使用用这个，但是用ref获取ModelForm的实例会报错

**Comment by zy135516** [comment]
@chenshuai2144 试过用这个，但是用ref获取ModelForm的实例会报错。也尝试过ant design的actionRef同样会报错

**Comment by chenshuai2144** [comment]
不会的吧。，报错什么？

**Comment by zy135516** [comment]
@chenshuai2144 使用ref报错Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()，

**Comment by zy135516** [comment]
@chenshuai2144 我用的useRef，绑定ref的时候没有传值会报错Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()，给定一个空字符串或者null,绑定在ModelForm上时值为undefined

**Comment by zy135516** [comment]
@chenshuai2144 报错Function components cannot be given refs，尝试过单独的demo来尝试获取，函数组件和类组件都获取不到，类组件直接用ref = {this.getRef}, getRef方法同样获取不到。你这边有什么好的方法获取吗？

**Comment by chenshuai2144** [comment]
```
const ref = React.createRef();
const ref = useRef();

<ModalForm  formRef={ref}/>
```

**Comment by zjxpcyc** [comment]
@chenshuai2144 给你们提个建议。这API真的要统一一下。其他的 Form 都是 Form.useForm()  来指定实例。这个却是 useRef()

**Comment by chenshuai2144** [comment]
```
const [form] = Form.useForm() ;

<ModalForm  formRef={form}/>

```
这个也可以的，useRef 是方便一点,因为 ref 可以一致变化，所以总是可以 get 到最新的值，但是 useForm 只能 set，不能 get
