### ISSUE TITLE
👑 [需求] ProTable columns copyable是否可以自定义复制文字格式或是按record生成字符串

### ISSUE THREAD

**Issue by shaojava** [ant-design/pro-components#1085]
### 🥰 需求描述
ProTable columns copyable是否可以自定义复制文字格式或是按record生成字符串

**Comment by chenshuai2144** [comment]
可以用 `renderText` 来自定义，暂时不支持别的的详细配置

**Comment by shaojava** [comment]
如果使用renderText那样会显示在table里 但需要复制的内容可能不需要显示。类似推广口令的文字只显示个推广口令就可以了 点击复制会是具体分享的口令内容这样子。

**Comment by chenshuai2144** [comment]
建议自行实现以下，protable 不好做这种超级灵活的

**Comment by shaojava** [comment]
恩自己实现了 谢谢
