### ISSUE TITLE
🧐[问题] protable 表格，当设置valueType: dataTimeRange时，在时间选择器上设置时间后日期后面的小时，分，秒被隐藏

### ISSUE THREAD

**Issue by shwin0901** [ant-design/pro-components#109]
### 🚑 其他信息

![1596618492997](https://user-images.githubusercontent.com/50405001/89439425-c0df5600-d77c-11ea-9a1a-00f89a2cb79e.jpg)

**Comment by shwin0901** [comment]
protable 表格，当设置valueType: dataTimeRange时，在时间选择器上设置时间后日期后面的小时，分，秒被隐藏；
该怎么解决这个问题，求解答！

**Comment by chenshuai2144** [comment]
设置 search.span 可以控制列数，你可以把列数设置为 3，这样就不会遮挡了

**Comment by shwin0901** [comment]
> 设置 search.span 可以控制列数，你可以把列数设置为 3，这样就不会遮挡了

谢谢解答，但设置 search={{span: 3}} ，都挤到一起了

**Comment by chenshuai2144** [comment]
来个截图

**Comment by shwin0901** [comment]
![1596695965882](https://user-images.githubusercontent.com/50405001/89500350-2f132f80-d7f4-11ea-81ab-f7c39f1ba1bc.jpg)

**Comment by shwin0901** [comment]
![1596695965882](https://user-images.githubusercontent.com/50405001/89500429-536f0c00-d7f4-11ea-8b82-f4c623a9aa4b.jpg)

**Comment by shwin0901** [comment]
> 来个截图

![1596695965882](https://user-images.githubusercontent.com/50405001/89500793-dabc7f80-d7f4-11ea-8399-e7445c2231e3.jpg)

**Comment by wugxone** [comment]
楼主，这个日期选择变成带时间的选择在哪里设置？
![image](https://github.com/ant-design/pro-components/assets/19504824/165070c1-8524-48a2-bc3c-83ed24f88e53)

**Comment by wugxone** [comment]
> 楼主，这个日期选择变成带时间的选择在哪里设置？ ![image](https://user-images.githubusercontent.com/19504824/278777429-165070c1-8524-48a2-bc3c-83ed24f88e53.png)
![image](https://github.com/ant-design/pro-components/assets/19504824/d2b4bdbc-7f79-41bd-bd18-d59804e77900)
问题已解决，此处设置
