### ISSUE TITLE
🐛[BUG] ProFormSelect 如果初始化Value，显示的Value值，而不是Label。

### ISSUE THREAD

**Issue by kenzheng2020** [ant-design/pro-components#1090]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/54108006/100297372-80287880-2fc9-11eb-901e-bafe59ee50ec.png)

初始化Value如果是2，期待显示“关闭“，实际界面显示的是2.

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/54108006/100297339-6b4be500-2fc9-11eb-8101-155d886ca5ec.png)

### 🏞 期望结果
期待显示Label值，而不是Value。

### © 版本信息

- ProComponents 版本: [1.4.1]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
可重现的代码来一下

**Comment by kenzheng2020** [comment]
import { ContentItem } from '@/models/cms';
import ProForm, {
  ProFormDateTimePicker,
  ProFormDigit,
  ProFormSelect,
  ProFormText,
} from '@ant-design/pro-form';
import { Editor } from '@tinymce/tinymce-react';
import { Form, Input } from 'antd';
import React, { useEffect, useState } from 'react';
import { ConnectProps, Dispatch } from 'umi';
import UploadCover from '../Upload/UploadCover';

export interface ContentProps extends Partial<ConnectProps> {
  dispatch: Dispatch;
  content?: ContentItem;
}

const formLayout = {
  labelCol: { span: 8 },
  wrapperCol: { span: 32 },
};

const ContentForm: React.FC<ContentProps> = (props) => {
  const { dispatch, content } = props;
  const [form] = Form.useForm();
  const [coverUrl, setCoverUrl] = useState('');

  useEffect(() => {
    form.setFieldsValue(content);
    setCoverUrl(content?.coverUrl || '');
  }, [content]);

  const onFinish = async (values: any) => {
    console.log('onFinish:', values);
    if (dispatch) {
      dispatch({
        type: 'content/saveOrUpdateContentData',
        payload: {
          ...values,
          coverUrl,
        },
      });
    }
  };

  return (
    <ProForm {...formLayout} onFinish={onFinish} form={form} scrollToFirstError>
      <ProFormText label="ID" name="id" hidden />
      <ProFormText label="栏目ID" name="categoryId" hidden />
      <ProFormText label="內容栏目" name="categoryName" disabled />
      <UploadCover coverUrl={coverUrl} setCoverUrl={setCoverUrl} />
      <ProFormText
        label="內容标题"
        name="contentTitle"
        rules={[
          {
            required: true,
            message: '需要填写标题',
          },
        ]}
        hasFeedback
      >
        <Input />
      </ProFormText>

      <ProFormText label="內容描述" name="contentDesc" hasFeedback />

      <Form.Item label="内容编辑">
        <Editor
          initialValue={content?.contentBody}
          init={{
            height: 500,
            language: 'zh_CN',
            menubar: true,
            plugins: [
              'advlist autolink lists link image charmap print preview anchor',
              'searchreplace visualblocks code fullscreen',
              'insertdatetime media table paste code help wordcount',
            ],
            toolbar:
              'undo redo|formatselect|bold italic backcolor|alignleft aligncenter alignright alignjustify|bullist numlist outdent indent|removeformat',
          }}
        />
      </Form.Item>
      <ProForm.Group>
        <ProFormDigit
          label="排序"
          name="sort"
          min={1}
          max={99}
          fieldProps={{ precision: 0 }}
          width="s"
          hasFeedback
        />
        <ProFormDigit
          label="点击次数"
          name="clickCount"
          min={1}
          fieldProps={{ precision: 0 }}
          width="s"
          hasFeedback
        />
        <ProFormDigit
          label="点赞次数"
          name="likeCount"
          min={1}
          fieldProps={{ precision: 0 }}
          width="s"
          hasFeedback
        />
      </ProForm.Group>

      <ProFormSelect
        label="状态"
        name="status"
        request={async () => [
          { label: '正常', value: '1' },
          { label: '关闭', value: '2' },
        ]}
        width="m"
        hasFeedback
        rules={[{ required: true }]}
      />

      <ProForm.Group>
        <ProFormDateTimePicker label="创建日期" name="createTime" width="s" />
        <ProFormText label="创建者ID" name="createBy" hidden width="s" />
        <ProFormText label="创建者" name="createByName" disabled width="s" />
      </ProForm.Group>
      <ProForm.Group>
        <ProFormDateTimePicker label="修改日期" name="updateTime" width="s" />
        <ProFormText label="修改者ID" name="updateBy" hidden width="s" />
        <ProFormText label="修改者" name="updateByName" disabled width="s" />
      </ProForm.Group>
    </ProForm>
  );
};

export default ContentForm;

**Comment by kenzheng2020** [comment]
content 数据

status: 1

**Comment by kenzheng2020** [comment]
另外这里有个Bug
ProFormSelect 
width="m" 这里不生效

**Comment by chenshuai2144** [comment]
不生效的问题升级一下版本

**Comment by kenzheng2020** [comment]
没解决问题啊

**Comment by chenshuai2144** [comment]
注意一下key的问题 2 和 '2'不一样 而且js还会帮你自动转化

**Comment by yangqi12345** [comment]
> 没解决问题啊

要转换成字符串 “2” 而不是number类型的 2

**Comment by chenshuai2144** [comment]
这个很模糊的，@yangqi12345  你要不试试用 Map
