### ISSUE TITLE
🧐[问题]重置查询search.transform未对查询参数key进行转换。

### ISSUE THREAD

**Issue by 985563349** [ant-design/pro-components#1092]
### 🧐 问题描述
使用search.transform进行查询操作能实现对查询参数key的转换，而使用重置按钮查询时却未能对key进行转换。

### 💻 示例代码
https://codesandbox.io/s/trusting-river-ipzco?file=/App.tsx

**Comment by chenshuai2144** [comment]
reset 需要转化？

**Comment by 985563349** [comment]
reset会自动调用request，如果search.transform是实现对查询参数key的转换，可能还是期望能够进行转换的。如果不支持，那此类场景是否提供了解决方案？

**Comment by chenshuai2144** [comment]
你的场景是 reset 的时候有默认值是吗？

**Comment by 985563349** [comment]
感谢您的回复！查询参数具有默认值应该是很常见的场景，目前我的处理方案是在request的绑定函数中手动去判断处理。
