### ISSUE TITLE
🧐[问题]pro-table在个别电脑上使用谷歌浏览器遇到报错“无法在节点上执行removeChild，要删除的节点不是该节点的子节点”

### ISSUE THREAD

**Issue by ray1347227** [ant-design/pro-components#1093]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/21354564/100303643-f03dfb00-2fd7-11eb-934f-619349986093.png)

**Comment by chenshuai2144** [comment]
关闭掉 google  翻译就好了

**Comment by ray1347227** [comment]
> 关闭掉 google 翻译就好了
> 
> google 翻译会修改dom，导致react 不认识这个 dom了

好了 感谢

**Comment by baixiaosh** [comment]
注意一下写法，应该能避免 https://github.com/facebook/react/issues/11538
