### ISSUE TITLE
【问题】【ProList】如何手动触发 request

### ISSUE THREAD

**Issue by sapphirezzz** [ant-design/pro-components#1094]
如何进行手动触发`ProList`的`request`？
比如消息列表，会有“一键已读”的功能，点击之后需要重新获取数据刷新`UI`。

**Comment by BooYeu** [comment]
actionRef可以用，但是书写会报错，像ProTable一样使用actionRef current reloadAndRest就可以啦~

**Comment by sapphirezzz** [comment]
> actionRef可以用，但是书写会报错，像ProTable一样使用actionRef current reloadAndRest就可以啦~

可以了，谢谢～
