### ISSUE TITLE
🐛[BUG]pro-layout文档的md是不是格式有问题

### ISSUE THREAD

**Issue by coderlfm** [ant-design/pro-components#1098]
https://procomponents.ant.design/components/layout#prolayout 
文档的这个位置是不是格式有问题，我这边看到的时候有问题的，本来要找菜单点击的回调事件的，没找到，发现了页面的这个问题

**Comment by coderlfm** [comment]
从服务器获取的菜单怎么监听菜单的点击事件然后跳转到对应的组件呢

**Comment by chenshuai2144** [comment]
menuItemRender ,试试这个api
