### ISSUE TITLE
[BUG] Form.List 与 ProFormDateTimePicker 一起使用导致value值为 Moment对象,传至后台格式有误

### ISSUE THREAD

**Issue by zhangjinqi51** [ant-design/pro-components#1100]
🐛 bug 描述
在表单中使用了<Form.List>中嵌套<ProFormDateTimePicker> 在提交时发现日期格式并不是 “YYYY-MM-DD HH:mm:ss”，导致后台报错
📷 复现步骤
Code:
![image](https://user-images.githubusercontent.com/28681308/100333060-1af67680-300d-11eb-8aea-953ced0faa28.png)
Console:
![image](https://user-images.githubusercontent.com/28681308/100333697-dfa87780-300d-11eb-9962-22ea4a83ea3c.png)
Network:
![image](https://user-images.githubusercontent.com/28681308/100333876-0c5c8f00-300e-11eb-8764-47a0534fd624.png)

🏞 期望结果
Form.List 中的对象能与其他日期控件format结果一致

💻 复现代码
© 版本信息
ProComponents 版本: [1.1.2]
umi 版本[3.2.24]
浏览器环境[版本 87.0.4280.67（正式版本） (x86_64)]
开发环境 [mac OS bigSur]
🚑 其他信息 
尝试指定format="YYYY-MM-DD HH:mm:ss",测试无效

**Comment by zhangjinqi51** [comment]
尝试修改@ant-design/pro-utils 中 conversionSubmitValue 方法可以暂时解决我的问题

**Comment by zhangjinqi51** [comment]
![Uploading image.png…]()

**Comment by chenshuai2144** [comment]
要自己转化一下了

**Comment by zhangjinqi51** [comment]
官网没计划在这里兼容一下Array吗？

**Comment by chenshuai2144** [comment]
@zhangjinqi51 我们会出自己的 list 的，上面会做封装
