### ISSUE TITLE
👑 [需求]ProList能否支持翻转倒序

### ISSUE THREAD

**Issue by BooYeu** [ant-design/pro-components#1103]
### 🥰 需求描述

在做网页工单系统时，需要优先显示与用户最后的交流内容，不知道prolist组件能否支持倒叙，上拉加载内容？

### 🧐 解决方案

scale 是不是设置为-1 这样？

### 🚑 其他信息

类似react native flatlist的inverted属性？

**Comment by chenshuai2144** [comment]
```tsx
postData={dataSource=>dataSource.reverse()}
```
你这个需求太奇怪了，为何不让后端直接排序呢，你拿不到所有的数据的。
