### ISSUE TITLE
🧐[问题] 关于pro-table 的 settings 问题

### ISSUE THREAD

**Issue by AsherSun** [ant-design/pro-components#1108]
### 🧐 问题描述

我看了文档，没有找到`settings`功能中的一些信息介绍，所以过来求助下各位大佬。谢谢🙏

我想知道`settings`功能中的勾选交互有事件可以监听到吗😭😭？

+ 我需要知道用户勾选的是哪个

**如图：**
![image](https://user-images.githubusercontent.com/28916706/100403333-9d2c7c80-3099-11eb-875b-478aa33df192.png)

**Comment by chenshuai2144** [comment]
| columnsStateMap | columns 的状态枚举 | {key:{ show,fixed }}} | - | 
| onColumnsStateChange | columns 状态发生改变 | (props: {key:{ show,fixed }}}) => void | - |

用这个api，这里有个文档
https://procomponents.ant.design/components/table#%E5%8F%97%E6%8E%A7%E7%9A%84%E8%A1%A8%E6%A0%BC%E8%AE%BE%E7%BD%AE%E6%A0%8F
