### ISSUE TITLE
🐛[BUG]  Protable 搜索表单自定义 Input组件传进去后报 warning

### ISSUE THREAD

**Issue by ccloveak** [ant-design/pro-components#1109]
### 🐛 bug 描述

* Protable 搜索表单自定义 Input组件传进去后报 warning

### 📷 复现步骤

* 需要对搜索输入框的 placeholder 进行编辑，参考了官网自定义表单的样例

### 🏞 期望结果

* 没有 warning

### 💻 复现代码

https://github.com/ccloveak/reportissue/tree/main/protable_demo

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] protable 2.11.4 & 2.9.10
- umi 版本
- 浏览器环境  chrome
- 开发环境 [e.g. mac OS]
- react 版本 16.13.1 

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/38686314/100411336-d4f4ed80-30b4-11eb-9344-eebaff3bf96d.png)

**Comment by chenshuai2144** [comment]
更新一下版本，我记得是个 bug。

**Comment by ccloveak** [comment]
> 更新一下版本，我记得是个 bug。

在pro-table 2.11.4上也存在这个警告信息...

**Comment by chenshuai2144** [comment]
这样写
```tsx | pure
renderFormItem: (_, { type, defaultRender, formItemProps, fieldProps, ...rest }, form) => {
  if (type === 'form') {
    return null;
  }
  // const status = form.getFieldValue('state');
  // if (status !== 'open') {
  return <Input {...rest.fieldProps} placeholder="请输入test" />;
  // }
  // return defaultRender(_);
};
```
