### ISSUE TITLE
🧐[问题] 修改表单里默认值为name,提交表单的时候想拿到id而不是name，请问怎么做呢

### ISSUE THREAD

**Issue by yangdachu** [ant-design/pro-components#1110]
### 🧐 问题描述

 修改表单里默认值为name,提交表单的时候想拿到id而不是name，请问怎么做呢

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23580181/100414698-4634a080-30b5-11eb-947e-0ce86599acfe.png)
![image](https://user-images.githubusercontent.com/23580181/100414706-4c2a8180-30b5-11eb-8c2e-33c7193ab01d.png)

![image](https://user-images.githubusercontent.com/23580181/100414683-3f0d9280-30b5-11eb-916f-86953830abb3.png)

**Comment by yangdachu** [comment]
@chenshuai2144 大佬有空的话帮忙看下这个问题可以吗

**Comment by chenshuai2144** [comment]
你可以用 `formRef.resetField` 来重置值
