### ISSUE TITLE
🧐[问题]ProTable：批量操作的问题？在特殊情况下，不能保存上一页选中的内容

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#1111]
### 🧐 问题描述

ProTable不一次把全部数据检索出来，而是分页检索时，批量操作在第一页选中，然后跳转到第二页，在选择其他记录时，就清空上次选择的内容。

我看了Demo中的Table批量操作没有问题，demo是一次把所有数据给取出来，我是点击分页按钮时候，取出数据。
![123222](https://user-images.githubusercontent.com/34436863/100416366-4171eb80-30b9-11eb-96f8-6f0ec67db834.png)

### 💻 示例代码
每次点击分页时，将当前页传递给服务器。

```tsx
    <ProTable<AppItem>
      headerTitle="批量操作"
      rowSelection={{
        // 自定义选择项参考: https://ant.design/components/table-cn/#components-table-demo-row-selection-custom
        // 注释该行则默认不显示下拉选项
        selections: [Table.SELECTION_ALL, Table.SELECTION_INVERT],
        onChange: (selectedRowKeys: any, selectedRows: any) => {
          console.log(selectedRowKeys, selectedRows);
        },
      }}
      options={false}
      rowKey="key"
      search={false}
      toolBarRender={() => [<Button key="show">查看日志</Button>]}
      columns={columns}
      pagination={{ pageSize: 5 }}
      request={async (params, sorter, filter) => {
        //console.log(params, sorter, filter);
        const result = await getAppList({
          current: params.current,
          pageSize: params.pageSize,
        });
        //console.log(result);
        return {
          data: result.list,
          total: result.total,
          success: true,
        };
      }}
    />

```

**Comment by fanhualei** [comment]
在Pro5演示版上，也能重现这个问题。 具体地址是：https://preview.pro.ant.design/list/table-list

**Comment by chenshuai2144** [comment]
与 antd 是相同的
![image](https://user-images.githubusercontent.com/8186664/100490198-9282ed80-3154-11eb-955c-acc02589af5c.png)

**Comment by chenshuai2144** [comment]
自己拼一下吧，翻一页可能key都不一样了。。

**Comment by sharh** [comment]
@fanhualei 
rowSelection={{
  // 自定义选择项参考: https://ant.design/components/table-cn/#components-table-demo-row-selection-custom
  // 注释该行则默认不显示下拉选项
  selections: [Table.SELECTION_ALL, Table.SELECTION_INVERT],
  // 添加这个属性，就会保持之前选择的，因为远程加载的话没有在缓存里面，默认会过滤不在DataSource中的选中项。
  preserveSelectedRowKeys: true,
  onChange: (selectedRowKeys: any, selectedRows: any) => {
    console.log(selectedRowKeys, selectedRows);
  },
}},
