### ISSUE TITLE
🐛[BUG]ProTable中枚举枚举对象设置initialValue后提示有多个initialValue

### ISSUE THREAD

**Issue by wehuss** [ant-design/pro-components#1112]
### 🐛 bug 描述

ProTable中枚举枚举对象设置initialValue后提示有多个initialValue

### 📷 复现步骤

设置initialValue为"0"
![image](https://user-images.githubusercontent.com/48681136/100424872-3030db00-30c9-11eb-8104-990a1adcce6c.png)

选然后提示有多个initialValue
![image](https://user-images.githubusercontent.com/48681136/100424947-4f2f6d00-30c9-11eb-9f54-111571f8ade7.png)

### 🏞 期望结果

无报错

**Comment by chenshuai2144** [comment]
不要既在全局设置，又在列中设置 initialValue
