### ISSUE TITLE
👑 [需求]ModalForm 移除trigger外围生成的<div>标签

### ISSUE THREAD

**Issue by gguan** [ant-design/pro-components#1115]
### 🥰 需求描述

需要在链接文字点击时弹出modal form，可是modal form自动生成的dom在按钮外增加了个div导致里面的样式错乱

### 🧐 解决方案

不要在trigger外添加div，可以添加空标签<></>

**Comment by chenshuai2144** [comment]
空标签<></> 没法触发 onClick 的
