### ISSUE TITLE
🐛[BUG] Cannot update a component (`BaseForm`) while rendering a different component (`Field`). To locate the bad setState() call inside `Field`, follow the stack trace as described in

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#1116]
Cannot update a component (`BaseForm`) while rendering a different component (`Field`). To locate the bad setState() call inside `Field`, follow the stack trace as described in

![image](https://user-images.githubusercontent.com/30397655/100437011-21ebba80-30db-11eb-8f79-42ee3179c8cb.png)

**Comment by laozhu** [comment]
The same problem after upgrade

**Comment by changjunhao** [comment]
Problem version @ant-design/pro-table@2.12.0
