### ISSUE TITLE
表格自带的密度调整无效 🐛[BUG]

### ISSUE THREAD

**Issue by VingoChen** [ant-design/pro-components#1117]
### 🐛 bug 描述

版本：
"@ant-design/pro-form": "^1.7.0",
 "@ant-design/pro-table": "2.9.1",

toolBar 自带的 密度调整 无效。

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
官方代码没有问题，升级版本吧
