### ISSUE TITLE
我在使用antd Table 组件配置colums的时候，在某一列配置sorter属性；  视图中更改筛选条件，表格会刷新，但是表格列上的排序的状态还在。  怎么在每次表格刷新后，重置表格列上的排序状态？

### ISSUE THREAD

**Issue by wxf-start** [ant-design/pro-components#112]
### 🧐 问题描述

我在使用antd Table 组件配置colums的时候，在某一列配置sorter属性；

视图中更改筛选条件，表格会刷新，但是表格列上的排序的状态还在。

怎么在每次表格刷新后，重置表格列上的排序状态？

应该怎么设置参数？

table 的onChange事件，第三个参数sort的字段让他为空呢？

### 💻 示例代码

![image](https://user-images.githubusercontent.com/37679380/89485746-07ac6a80-d7d4-11ea-98d6-345c6a3e9904.png)

### 🚑 其他信息

情景：
1.自定义Form对pro-table数据进行查询
2.对pro-table的某一列进行排序
3.重新选择自定义Form表单数据进行pro-table的渲染
4.原先的sort还是会存在
5.请问如何对columns设置，将之前的sort排序清空呐
6.我已尝试设置了sortOrder=false ，只能使高亮效果消失，而pro-table的第三个参数sort还是存在字段显示，请问如何操作？
期望结果
设置一个属性，pro-table onChange事件的sort参数为空，列排序高亮效果消失

**Comment by wxf-start** [comment]
emmmmm....这个都木有人搭理的吗哈哈哈哈

**Comment by qiuziGirl** [comment]
> emmmmm....这个都木有人搭理的吗哈哈哈哈

遇到同样问题，请问最后解决了吗
