### ISSUE TITLE
👑 [需求]Layout多标签

### ISSUE THREAD

**Issue by phoema** [ant-design/pro-components#1123]
### 🥰 需求描述
vue的架子的这种多标签挺好的，尤其是作为管理系统时，多打开几个页面，有助于切换查看
ProLayout是否考虑原生支持
https://chu1204505056.gitee.io/vue-admin-beautiful-pro/#/index

**Comment by chenshuai2144** [comment]
好多同样的 issue了
https://github.com/ant-design/pro-components/issues/439

**Comment by phoema** [comment]
是呀，积沙成塔嘛。
