### ISSUE TITLE
🐛[BUG] Whitespace text nodes cannot appear as a child of <thead>

### ISSUE THREAD

**Issue by SynHao** [ant-design/pro-components#1124]
### 🐛 bug 描述 Whitespace text nodes cannot appear as a child of <thead>

![image](https://user-images.githubusercontent.com/8100653/100518759-90f60b80-31ce-11eb-8e3e-d223518684fb.png)

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/8100653/100518769-a23f1800-31ce-11eb-8cd9-b9a7a06c645c.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
为什么要  ignore？
