### ISSUE TITLE
🐛[BUG]pro-table使用renderFormItem时return组件带入外部参数最后参数会被置为null

### ISSUE THREAD

**Issue by qinxiangling** [ant-design/pro-components#1126]
### 🐛 bug 描述

pro-table使用renderFormItem时return自定义组件带入外部参数最后参数会被置为null
打印DataSource会显示正确值一次后马上变为null，渲染成功后，操作一下其他的form后又变为正常值

### 📷  复现代码

{
      title: '答题时间',
      dataIndex: 'reportDate',
      render: (value) => {
        if (isNaN(value) === false) {
          return moment(value).format('YYYY-MM-DD');
        }
        return '';
      },
      renderFormItem: () => {
        //打印DataSource会显示一次正确值后马上变为null，渲染成功后，操作一下其他的form后又变为正常值
        console.log(DataSource)
        return <RangeData value={DataSource} />;
      },
    },

### © 版本信息

@ant-design/pro-table": "^2.8.1",

**Comment by qinxiangling** [comment]
{
      title: '答题时间',
      dataIndex: 'reportDate',
      render: (value) => {
        if (isNaN(value) === false) {
          return moment(value).format('YYYY-MM-DD');
        }
        return '';
      },
      renderFormItem: () => {
        //打印DataSource会显示正确值一次后马上变为null，渲染成功后，操作一下其他的form后又变为正常值
        console.log(DataSource)
        return <RangeData value={DataSource} />;
      },
    },

**Comment by qinxiangling** [comment]
// title: '答题时间',
      // dataIndex: 'reportDate',
      // render: (value) => {
      //   if (isNaN(value) === false) {
      //     return moment(value).format('YYYY-MM-DD');
      //   }
      //   return '';
      //},
      // renderFormItem: () => {
      // 打印DataSource会显示正确值一次后马上变为null，渲染成功后，操作一下其他的form后又变为正常值
      // console.log(DataSource)
      // return <RangeData value={DataSource} />;

**Comment by chenshuai2144** [comment]
升级到最新的版本。原来有个 setTimeout闭包了

**Comment by qinxiangling** [comment]
> 升级到最新的版本。原来有个setTimeout闭包了

好的，十分感谢，太开心了，我还以为是我用的方式不对 ///(^v^)\\\
