### ISSUE TITLE
🐛[BUG][pro-table]toolbar中的search以及filter怎么跟table中的状态关联起来

### ISSUE THREAD

**Issue by xiexingen** [ant-design/pro-components#1128]
### 🐛 bug 描述

以官方的demo为例，https://codesandbox.io/s/nuuwj
当禁用table的search使用toolbar的search或者filter的时候，怎么获取到request中传入的参数(分页参数、排序参数等)
比如:想在onSearch中使用search中的输入+排序条件+当前页来像后端请求，这个时候是不是应该可以触发到request方法

![image](https://user-images.githubusercontent.com/7939085/100541218-3ebff380-327d-11eb-8e4a-ce5b1ab96077.png)

### 💻 复现代码

https://codesandbox.io/s/nuuwj

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
keyWords 的配置会自动的出发 request。 你可以使用 params， 把 onSearch中的值存到 state中，然后配置 

```
params={{ keyWords }}
```

params 中的值变化会自动触发 request。

**Comment by xiexingen** [comment]
也可以咯
