### ISSUE TITLE
proTabl分页问题🐛[BUG]

### ISSUE THREAD

**Issue by dj835638078** [ant-design/pro-components#113]
使用protable时，改变页面的currentPage时能重新调用接口，改变pageSize时，只在第一次改变时将currentPage和pageSize改成默认值后调用接口，后续再改pageSize则无效

**Comment by chenshuai2144** [comment]
升级一下 protable 和 antd 的版本, 有一个版本 antd 修改了 onchange 的调用参数导致 table 挂掉了

**Comment by thomasliew** [comment]
不要设置pageSize: 10，要用defaultPageSize: 10
