### ISSUE TITLE
👑 [需求]Protable，当检索条件一行时，与下面的间隔太大了，能不能把高度修改一下。

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#1130]
### 🥰 需求描述

Protable，当检索条件一行时，与下面的间隔太大了，能不能把高度修改一下。

![11111](https://user-images.githubusercontent.com/34436863/100561054-af552780-32f2-11eb-8cfc-27288bf64196.png)

**Comment by chenshuai2144** [comment]
有个 bug，修完 bug，这个就解决了

**Comment by chenshuai2144** [comment]
fixed, 最好改一下背景颜色，查询表单和table 是两个card
