### ISSUE TITLE
🧐[问题]ProTable type="form" 弹出的modal异常关闭

### ISSUE THREAD

**Issue by waylon-gmail** [ant-design/pro-components#1132]
### 🧐 问题描述

ProTable type="form" 弹出的modal中有选择控件(比如：时间，valueEnum)等，当点击确定的时候modal会关闭掉。

比如modal中有个时间选择控件，点击“此刻”按钮，modal就被关掉了。

之前的版本没有这个问题。

**Comment by chenshuai2144** [comment]
来个重现

**Comment by waylon-gmail** [comment]
更新了依赖后正常了，无法重现。想要恢复到之前有问题的状态，恢复不出来了。
