### ISSUE TITLE
@ant-design/pro-form 1.7.0 出现的报错

### ISSUE THREAD

**Issue by zhouzyc** [ant-design/pro-components#1134]
### 🐛 描述

使用ModalForm弹窗组件
```
Warning: Cannot update a component (`BaseForm`) while rendering a different component (`Field`). To locate the bad setState() call inside `Field`, follow the stack trace as described in https://fb.me/setstate-in-render
```
###复现步骤

[文档高级表单-Modal 表单](https://procomponents.ant.design/components/form
)：例子可以复现。

### 🏞 期望结果

不出现此提醒
### 🚑 其他信息

测试后
@ant-design/pro-form 1.6.2 无问题。升级1.7.0出现。

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/pro-components/issues/1116
