### ISSUE TITLE
🐛[BUG]EditableProTable onChange方法未正常触发

### ISSUE THREAD

**Issue by eric-chaw** [ant-design/pro-components#1140]
### 🐛 bug 描述

在`EditableProTable`中新增或编辑一行时, 本行中任何内容发生变化 (输入或下拉选择) 后, 无论是`EditableProTable#onChange`方法, 或 `EditableProTable.editable#onChange` 均未正常触发.

### 📷 复现步骤

1. 新增一行
2. 任意列中输入内容, `onChange` 方法未触发

### 🏞 期望结果
- 类似`form#onValuesChange` 的功能, 在任意项输入内容发生变化时, 能获取到当前发生变化的值, 及当前行的全部内容.
- 获取到当前变化的值后, 可根据当前的值, 关联设置其他列的值. (如: **性别**设置为 **男**, 昵称自动设置为 **Tony**)

### 💻 复现代码

```
    <EditableProTable<ExpandedProfileWidget>
          rowKey="sequence"
          value={[...widgets.values()]}
          onChange={onTableChange}
          editable={{
            editableKeys,
            type: 'singe',
            onChange: onRowChange
          }}
    .......
```

```
const onTableChange = (rows: ExpandedProfileWidget[]) => {
    console.info(rows.length);
}

const onRowChange = (editableKeys: React.Key[], editableRows: ExpandedProfileWidget[]) => {
    setEditableRowKeys(editableKeys);
    console.info(editableKeys.length);
}
```

### © 版本信息

- ProTable 版本: 2.12.0

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
这是设计，新增一行的数据是存在缓存里面的。只有点击保存的时候才会存到 dataSource 中去，不然点击取消之后这一行还是在

**Comment by eric-chaw** [comment]
> 这是设计，新增一行的数据是存在缓存里面的。只有点击保存的时候才会存到 dataSource 中去，不然点击取消之后这一行还是会存到 dataSouce 中，我们还要人工将其删除。
> 
> update 和 new 的逻辑是有一些不同的

所以, 这不是个问题?
那如果现在想要类似 Form的onValuesChange 方法的效果, 应该用什么API呢?

**Comment by chenshuai2144** [comment]
竟然不支持，你要实现什么需求

**Comment by eric-chaw** [comment]
Form中经常会有联动的需求的，比如EditableProTable中第一列是下拉框, 选择了职业 '码农', 第二列的性别联动设置默认值为 '男', 类似功能. 那就需要类似Form的onValuesChange的方法支持获取列的数据变化

**Comment by chenshuai2144** [comment]
可以用fieldProps里面的onChangr

**Comment by eric-chaw** [comment]
fieldProps 不是 { [prop: string]: any } 类型吗? 里面没有找到 onChange 方法的相关说明

**Comment by eric-chaw** [comment]
```
const onChangeValue = (val: any) => {
    console.info(val)
}
```

```
{
  title: '名称',
  dataIndex: 'name',
  fieldProps: {
    onChange: onChangeValue
  }
}
```
试了试, 没有反应!

**Comment by chenshuai2144** [comment]
@eric-chaw  demo 里试了试没有问题
```
{
    title: '活动名称',
    dataIndex: 'title',
    fieldProps: {
      onChange: (e: ChangeEvent<HTMLInputElement>) => console.log(e.target.value),
    },
    formItemProps: {
      rules: [
        {
          required: true,
          message: '此项为必填项',
        },
      ],
    },
    width: '30%',
  },
```

**Comment by SomeOneNoBrain** [comment]
@chenshuai2144 这个如果做级联还是不行吗

**Comment by chenshuai2144** [comment]
还没发布 等我休假结束

**Comment by pangxiaolong** [comment]
> 还没发布等我休假结束

今天做到最后一步了才发现，editable里的onChange事件竟然是要保存才能触发的，因为做的是没有打算使用操作中的保存和取消操作，我周二回来，能发吗:(

**Comment by chenshuai2144** [comment]
用操作中的保存和取消操作 

这个会加一个onValueChange的，不然render 太频繁，性能顶不住

**Comment by pangxiaolong** [comment]
> 用操作中的保存和取消操作
> 
> 这个会加一个onValueChange的，不然render太太，性能顶不住

大概什么时候发布onvaluechange的属性，等你呦

**Comment by pangxiaolong** [comment]
@chenshuai2144 onValueChange的api什么时候可以发呢 :(

**Comment by chenshuai2144** [comment]
onValueChange 还没写，提个功能请求 issue 吧
