### ISSUE TITLE
ProTable valueType percent field can not recognize "-"🧐[问题]

### ISSUE THREAD

**Issue by matianhe3** [ant-design/pro-components#1141]
### 🧐 问题描述
高级表格的 valueType 设置为 percent 时, 不能显示正负值, -0.81还会转换成 81%.

**Comment by chenshuai2144** [comment]
试了一下没有问题，来个重现

**Comment by matianhe3** [comment]
showSymbol: true 检查了一遍,显示符号设置了false.
`valueType: () => ({type: "percent", showSymbol: true})`
