### ISSUE TITLE
🧐[问题] 按照最新的文档 对搜索表单进行设置， 报warning

### ISSUE THREAD

**Issue by ccloveak** [ant-design/pro-components#1144]
### 🧐 问题描述

* 按照最新的文档 对搜索表单进行设置， 报warning

### 💻 示例代码
https://github.com/ccloveak/reportissue/blob/d00c6e9d7b4ed31e8395596a7a7bd42d515e3c35/protable_demo/src/template/index.js#L18

### 期望
* 有没有没有警告的写法

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/38686314/100593810-35499080-333c-11eb-8510-10ee7f92ccde.png)

**Comment by chenshuai2144** [comment]
报错什么warning？

**Comment by ccloveak** [comment]
@chenshuai2144 
1. `Warning: Cannot update a component (`BaseForm`) while rendering a different component (`Field`). To locate the bad setState() call inside `Field`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render`
2. `Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of ResizeObserver which is inside StrictMode. Instead, add a ref directly to the element you want to reference. `

**Comment by fangniu** [comment]
+1

**Comment by chenshuai2144** [comment]
更新一下版本好了，我昨天发布了新的版本。
祥细的情况看这里。
https://github.com/ant-design/pro-components/pulls?q=is%3Apr+is%3Aclosed

**Comment by zjz236** [comment]
今天更新了版本 还是报了相同警告 @chenshuai2144

**Comment by chenshuai2144** [comment]
版本要2.12.1

**Comment by oliviaxtli** [comment]
> 版本要2.12.1

你好，我使用pro-layout：6.16.1，antd：4.15.0版本，开启搜索表单之后，在React.StrictMode模式下还是会报
![image](https://user-images.githubusercontent.com/31402051/114826788-809ba180-9dfa-11eb-9bf0-1b82433af1b0.png)

**Comment by chenshuai2144** [comment]
findDOMNode  是什么功能？
这个东西现在被废弃了

**Comment by oliviaxtli** [comment]
> findDOMNode 是什么功能？
> 这个东西现在被废弃了

不是我的代码中使用的findDOMNode，我仅在**严格模式**下使用了pro-table（版本2.33.0）的EditableProTable，开启了搜索表单之后就报错了，不开启搜索表单不会报错
- index.tsx
```
ReactDOM.render(
    <React.StrictMode>
            <App />
    </React.StrictMode>,
    document.getElementById("root")
);
```
- App.tsx
```
<EditableProTable<TDemoTableItem>
            columns={columns}
            actionRef={actionRef}
            search={{
                labelWidth: "auto",
            }}
            ...
/>
```

**Comment by chenshuai2144** [comment]
应该是 antd 内部的动画还用了这个东西。
豆酱老师正在清理中

**Comment by yurizhang** [comment]
![image](https://user-images.githubusercontent.com/20555332/140699268-34e8dc87-c440-4385-a9b5-d934fbf69c3e.png)
是这个rc-motion这个里面在使用
@chenshuai2144

**Comment by Over-reaction** [comment]
怎么还没有解决 现在还是报这个错误

**Comment by dzcpy** [comment]
2024年了，还是在报错
