### ISSUE TITLE
🧐[问题]使用  onValuesChange 去处理protable的搜索项联动，onValuesChange这个属性应该加在哪里呢 

### ISSUE THREAD

**Issue by zhangxiangqiang** [ant-design/pro-components#1145]
### 🧐 问题描述

protable里不建议用onChange处理搜索表单项联动，使用  onValuesChange 去处理protable的搜索项联动，onValuesChange这个属性应该加在哪里呢 ， 它是form的属性好像加在哪里都不合适

### 💻 示例代码

```
{
      title: '项目名称',
      dataIndex: 'projectId',
      valueType: 'select',
      fieldProps: {
        // onValuesChange: () => {console.log(11)},
        options: projectList,
        optionFilterProp: 'label',
        showSearch: true,
        // onChange: (id:any) => {
        //   console.log(id, 99)
        //   deviceLocation({id}).then((res)=>{
        //     if(res.status !== 'ok') return;
        //     setDeviceLocationArr(res?.data);
        //   });
        // }
      },
    },
    {
      title: '设备位置',
      dataIndex: 'publicOrRoom',
      valueType: 'select',
      hideInTable: true,
      fieldProps: {
        // options: iwant.array(deviceLocationArr),
      },
    },

```

### 🚑 其他信息

"@ant-design/pro-layout": "^6.5.15",
    "@ant-design/pro-table": "^2.11.4",
    "@formily/antd": "^1.3.8",

**Comment by chenshuai2144** [comment]
在 ProTable的form上，表单联动onChange 也无法解决吧？

**Comment by zhangxiangqiang** [comment]
proTable 的 form 没试过，antdesign4.x 正常的formItem  是可以使用onChange做联动的 @chenshuai2144

**Comment by chenshuai2144** [comment]
@zhangxiangqiang  你的需求是什么？

**Comment by zhangxiangqiang** [comment]
在处理protable的搜索表单项时，联动该如何做，比如上面的写的实例代码，项目名称变化，我要去请求设备位置的下拉列表，该怎么去监听项目名称变化 @chenshuai2144

**Comment by chenshuai2144** [comment]
@zhangxiangqiang  那就需要存一下值了，或者封装一下设备位置的下拉列表。

```
const DeviceSelect: React.FC<{
  deviceName: string;
}> = ({ deviceName }) => {
  const [options, setOptions] = useState([]);
  useEffect(() => {
    get({
      deviceName,
    }).then((res) => {
      setOptions(res.data);
    });
  }, [deviceName]);

  return <Select options={options} />;
};

const columns: ProColumns<TableListItem>[] = [
  {
    title: "项目名称",
    dataIndex: "projectId",
    valueType: "select",
  },
  {
    title: "设备位置",
    dataIndex: "publicOrRoom",
    valueType: "select",
    hideInTable: true,
    renderFormItem: (item, config, form) => {
      const deviceName = form.getFieldValue("projectId");
      return <DeviceSelect deviceName={deviceName} />;
    },
  },
];

```

这样写性能和可维护性都很高

**Comment by zhangxiangqiang** [comment]
好的，这样确实可行，每次表单项改变的时候renderFormItem会重新执行，谢谢大佬。

**Comment by JessieHelloWorld** [comment]
> @zhangxiangqiang 那就需要存一下值了，或者封装一下设备位置的下拉列表。
> 
> ```
> const DeviceSelect: React.FC<{
>   deviceName: string;
> }> = ({ deviceName, ...rest }) => {
>   const [options, setOptions] = useState([]);
>   useEffect(() => {
>     get({
>       deviceName,
>     }).then((res) => {
>       setOptions(res.data);
>     });
>   }, [deviceName]);
> 
>   return <Select options={options} {...rest} />;
> };
> 
> const columns: ProColumns<TableListItem>[] = [
>   {
>     title: "项目名称",
>     dataIndex: "projectId",
>     valueType: "select",
>   },
>   {
>     title: "设备位置",
>     dataIndex: "publicOrRoom",
>     valueType: "select",
>     hideInTable: true,
>     renderFormItem: (item, config, form) => {
>       const deviceName = form.getFieldValue("projectId");
>       return <DeviceSelect deviceName={deviceName} />;
>     },
>   },
> ];
> ```
> 
> 这样写性能和可维护性都很高

请问在父select变化时，子的已选中值的怎么清空呢？

**Comment by zhangxiangqiang** [comment]
@JessieHelloWorld 每次表单项改变的时候renderFormItem会重新执行，清空可以在select下拉请求回来后做，form.setFieldsValue({ xxx: undefined });

**Comment by Hnnphone** [comment]
formRef.current?.resetFields(); 点击重置，上面的 deviceName 并不可靠
