### ISSUE TITLE
👑 [需求]完善EditableProTable文档与代码

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#1146]
### 🥰 需求描述

希望能完善EditableProTable文档与代码，例如通过codesandbox 提供一个示例的代码

**Comment by chenshuai2144** [comment]
提供了相应的demo和文档了， 哪里有问题可以提出来

**Comment by fanhualei** [comment]
> 提供了相应的demo和文档了， 哪里有问题可以提出来

看到文档与demo了，学习中...

**Comment by fanhualei** [comment]
> 提供了相应的demo和文档了， 哪里有问题可以提出来


如何进行设置字段的校验规则？希望能给出相关示例。

`rules={[{ required: true }]}`



Demo代码中删除`editableKeys`代码，这个属性好像是多余的，不知道用的场景是那些？


文件中建议追加使用限制：下面功能不建议使用：
* 检索Form
* ToolBar
* 分页

**Comment by fanhualei** [comment]
![111111](https://user-images.githubusercontent.com/34436863/100707394-92e5e780-33e5-11eb-8041-e1b334d3a370.png)

如何追加输入框的校验？ 还没有弄明白。

另外除了整行编辑，单个字段编辑的功能有吗？  单个字段编辑，实际上不复杂，自己也可以实现，所以没有这个功能也行。
