### ISSUE TITLE
protable 搜索表单的optionRender里的form获取为空🧐[问题]

### ISSUE THREAD

**Issue by qingfengdai** [ant-design/pro-components#1148]
### 🧐 问题描述

功能是把search表单的按钮重置和查询按钮位置对调,重置与提交按钮点了没反应,查了下以前用的2.9的版本的没有问题,现在2.11版本的同样写法就不行了

### 💻 示例代码
    <ProTable<TableListItem>
        actionRef={actionRef}
        formRef={ref}
        className={styles.table}
        headerTitle={
          <Button
            icon={<PlusOutlined />}
            type="primary"
            onClick={() => {
              setModalType('add');
              setModalTitle('添加');
              setModalVisible(true);
            }}
          >
            新增
          </Button>
        }
        request={(params: TableListParams) => {
          let canton = ''
          if (params?.canton) {
            canton = (params?.canton[params.canton.length - 1]);
          }
          const paramsData = canton ? { ...params, canton } : { ...params }
          return getPage(paramsData)
        }}
        pagination={{ defaultPageSize: 10 }}
        rowKey="id"
        form={{ labelAlign: 'left', wrapperCol: { span: 16 } }}
        options={false}
        search={{
          collapsed: false,
          span: 8,
          collapseRender: () => null,
          optionRender: ({ searchText, resetText }, { form }) => {
            return [
              <Button
                key="searchText"
                type="primary"
                onClick={() => {
                  form?.submit();
                }}
              >
                {searchText}
              </Button>,
              <Button
                key="resetText"
                onClick={() => {
                  form?.resetFields();
                  form?.submit();
                }}
              >
                {resetText}
              </Button>,
            ];
          },
        }}
        columns={columns}
      />

**Comment by qingfengdai** [comment]
目前这么处理的
          optionRender: (searchConfig, props, dom) => {
            return [
              dom[1], dom[0]
            ];
          },

**Comment by youngclean** [comment]
我也有这个问题，升级后不能查询了

**Comment by chenshuai2144** [comment]
这里修了https://github.com/ant-design/pro-components/pull/1147

可以先用 formRef 来绕过一下

**Comment by lizhongyue248** [comment]
> 这里修了#1147
> 
> 可以先用 formRef 来绕过一下

请问预计多久发布更新？

**Comment by chenshuai2144** [comment]
明天
