### ISSUE TITLE
🐛[BUG] 【proTable】valueEnum定义的数据，在select里没有按顺序排列，而是按照key的大小排列的

### ISSUE THREAD

**Issue by dmdoit** [ant-design/pro-components#115]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/19385704/89499793-2ec66480-d7f3-11ea-802c-712f71f8c1a4.png)
![image](https://user-images.githubusercontent.com/19385704/89499943-6fbe7900-d7f3-11ea-8ef0-d9c4face4ea0.png)

### 📷 复现步骤
valueEnum定义的数据，在select里没有按书写的顺序排列，而是按照key的大小排列的

### 🏞 期望结果
不要按照key来排列

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
Object 是不能保证顺序的，请使用 Map

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by chenshuai2144** [comment]
把类型写对就好了，

`new Map<string,any>`
