### ISSUE TITLE
🐛[BUG]EditableProTable 中 startEditable 方法传入number类型的key值为0时无法编辑

### ISSUE THREAD

**Issue by eric-chaw** [ant-design/pro-components#1155]
### 🐛 bug 描述
EditableProTable 中点击编辑调用 `actionRef.current.startEditable(key)`, 当 `key` 值为0时, 无法正常编辑, 不显示输入框

### 📷 复现步骤
1. EditableProTable 中点击编辑
2. 调用 `actionRef.current.startEditable(key)`
3. 仅当`key`值为0时, 无法正常编辑, 不显示输入框

### 🏞 期望结果
key值为0时, 也能正常编辑

### 💻 复现代码
```
// key = 0
`actionRef.current.startEditable(key)`
```

### © 版本信息

- ProTable 版本: [e.g. 2.12.1]
- umi 版本 3.2.14
- 浏览器环境: Chrome 87.0.4280.66
- 开发环境 Win10

### 🚑 其他信息
无

**Comment by chenshuai2144** [comment]
超级隐蔽的bug，非常感谢，但是推荐你还是不要用 index 当key，非常危险

**Comment by 123789jiangwei123789** [comment]
当设置id为key的时候，id和行索引一样的时候，调用这个方法，会出现和id一样的索引行也会触发编辑，麻烦跟踪一下这个问题
