### ISSUE TITLE
🐛[BUG] 列表清理选中项相关问题

### ISSUE THREAD

**Issue by fangzhengjin** [ant-design/pro-components#1156]
### 🐛 bug 描述

1. 列表翻页时, 勾选项没有清理
2. 列表刷新时, 勾选项没有清理
4. 调用ref中的clearSelected时, 必定会重定向至第一页
3. 在request中http请求前, 调用ref的clearSelected时, 如果当前页不是第一个会导致选中页一直重复请求数据

### 💻 复现代码

[![Edit cool-tharp-nvvdu](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-tharp-nvvdu?fontsize=14&hidenavigation=1&theme=dark)
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fangzhengjin** [comment]
1. 如果有跨页勾选需求的话, 能不能考虑做成配置, 如果不开启的话默认就是清空选中项
2. clearSelected 不应该每次都跳转到第一页, 如果有调整需求的话, 是不是可以考虑在调用时传一个页码进去?

**Comment by chenshuai2144** [comment]
需要又自定义的业务逻辑，推荐直接使用antd 的 ，这个demo里可以完全自定义所有逻辑

https://ant.design/components/table-cn/#components-table-demo-row-selection-and-operation
