### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by Wmstone** [ant-design/pro-components#1159]
### 🧐 问题描述
我今天安装了一次pro-form，然后pro-form和pro-table中的表单样式全部变成了垂直布局，Input表单高度也变大了。
之后再卸载掉pro-form后仍然没有效果。而且我在config中配置了  theme: { 'border-radius-base': '0' },现在Button中也无法生效

### 💻 示例代码

```
 <ProTable<BackupJobItem>
        columns={columns}
        actionRef={ref}
        rowKey="id"
        columnsStateMap={columnsStateMap}
        onColumnsStateChange={map => setColumnsStateMap(map)}
        request={async (params = {}) => {
          setPageNum(params.current || 1);
          setPageSize(params.pageSize || 10);
          getStatisticsCount();
          const BackupJobList = await queryBackupJobList({
            ...params,
            pageNum: params.current,
            pageSize: params.pageSize,
          });
          return {
            success: BackupJobList.success,
            data: BackupJobList?.retValue?.list,
            total: BackupJobList?.retValue?.total,
          };
        }}
        scroll={{ x: columns.reduce((p, e) => p + ((e.width as number) || 120), 0) }}
      />
```
### 🚑 其他信息
原始样式
![image](https://user-images.githubusercontent.com/32698341/100733698-85daef80-3409-11eb-9d43-d1d246ee65b0.png)
现在样式
![image](https://user-images.githubusercontent.com/32698341/100733744-9db27380-3409-11eb-9b23-0811b2aefad7.png)

### 版本信息：
umi : 3.2.1
antd: 4.6.4
ant-design/pro-table: 2.8.1
ant-design/pro-form: 1.7.1（已卸载）
操作系统 windows10

**Comment by chenshuai2144** [comment]
垂直布局估计时因为 api 改变，你升级到最新版本试试

按钮不生效时什么意思？

**Comment by chenshuai2144** [comment]
重新提个写了标题的issue

**Comment by Wmstone** [comment]
@chenshuai2144 您好标题重新更改了，按钮的直角全部变成了圆角

**Comment by Wmstone** [comment]
我把ant-design/pro-table 升级到2.12.0 可以了，我昨天升级到2.12.1（npm上最新版本）却不行，谢谢 @chenshuai2144

**Comment by chenshuai2144** [comment]
圆角和直角的问题估计是antd.的版本问题

**Comment by titld** [comment]
pro-form组件从1.x升级到2.2.7，formRef透传给子组件，从子组件中formRef.current.setFieldsValue({name: 'xxx'})；1.x版本没有问题，但是升级到2.x后就无法从父组件拿到子组件赋值的数据；
