### ISSUE TITLE
使用request绑定数据时如何获取绑定的dataSource？🧐[问题]

### ISSUE THREAD

**Issue by DreamParadise** [ant-design/pro-components#116]
### 🧐 问题描述

1. 使用request绑定数据时如何获取绑定的dataSource？
2. 删除了一行数据时我想直接通过修改绑定的dataSource来更新表格内容而不要reload来刷新，这要怎么设置？

**Comment by chenshuai2144** [comment]
> 使用request绑定数据时如何获取绑定的dataSource

postData 会把 dataSource 给你


> 删除了一行数据时我想直接通过修改绑定的dataSource来更新表格内容而不要reload来刷新，这要怎么设置？

那你岂不是少了一行了，这种需求有点奇怪

**Comment by DreamParadise** [comment]
> > 使用request绑定数据时如何获取绑定的dataSource
> 
> postData 会把 dataSource 给你
> 
> postData	对通过 request 获取的数据进行处理	(data: T[]) => T[]	-
> > 删除了一行数据时我想直接通过修改绑定的dataSource来更新表格内容而不要reload来刷新，这要怎么设置？
> 
> 那你岂不是少了一行了，这种需求有点奇怪

就是表格的最后一列有一个删除按钮，我点击删除，如果服务器返回成功的话我想直接把dataSource中对应的那一行删掉。然后界面上表格中的那一行就也没了，比如删之前表格中有20行，删除后就剩下19行。如果不通过dataSource修改的话那得多请求一次服务器的接口才能刷新表格。

**Comment by wushuang3625** [comment]
不用request，直接用DataSource，这样就可以控制DataSource直接控制datasource

**Comment by DreamParadise** [comment]
> 不用request，直接用DataSource，这样就可以控制DataSource直接控制datasource

这是我试过了是可以，不过这样好像翻页的功能还有自带的搜索表单功能都用不了要自己重新实现吧？🤔

**Comment by chenshuai2144** [comment]
> 就是表格的最后一列有一个删除按钮，我点击删除，如果服务器返回成功的话我想直接把dataSource中对应的那一行删掉。然后界面上表格中的那一行就也没了，比如删之前表格中有20行，删除后就剩下19行。如果不通过dataSource修改的话那得多请求一次服务器的接口才能刷新表格。

这样没什么优势的，还可能造成和数据库里的数据不对应，反而会有更多的麻烦
