### ISSUE TITLE
🐛[BUG]Modal里面的Select组件选项值滚动,

### ISSUE THREAD

**Issue by hesummerzh** [ant-design/pro-components#1163]
### © 版本信息

- ProComponents 版本: [1.7.0]
- umi 版本
- 浏览器环境

### 🚑 其他信息

![bug](https://user-images.githubusercontent.com/39561300/100818525-4c47ca00-3485-11eb-86d5-ea635c87aa84.png)

**Comment by hesummerzh** [comment]
![Uploading bug.png…]()

**Comment by chenshuai2144** [comment]
这个是 antd 的常见问题，用 configProvide 配置一下 getPopupContainer 到当前的 dom。

https://ant.design/components/config-provider-cn/
