### ISSUE TITLE
🧐[问题]ProFormSelect在获取数据源之后设置initialValue不生效，该如何使用？

### ISSUE THREAD

**Issue by Web-Delevan** [ant-design/pro-components#1164]
### 💻
```
<ProFormSelect
                width="s"
                name="formatID"
                label="版式"
                allowClear={false}
                rules={[{ required: true }]}
                options={FormatList}
                initialValue={FormatList[0] && FormatList[0].value}
                fieldProps={{
                  onSelect: (e) => {
                    console.log(e);
                  },
                }}
              />
```

**Comment by chenshuai2144** [comment]
FormatList 没回来的时候不要渲染 ProFormSelect

**Comment by Web-Delevan** [comment]
> FormatList 没回来的时候不要渲染 ProFormSelect

已解决

**Comment by vuvivian** [comment]
怎么解决的？

**Comment by Web-Delevan** [comment]
> 怎么解决的？

{FormatList.length ? (
              <ProFormSelect
                width="s"
                name="formatID"
                label="版式"
                allowClear={false}
                rules={[{ required: true }]}
                options={FormatList}
                initialValue={FormatList[0].value}
                fieldProps={{
                  onSelect: (e) => {
                    formData = {
                      ...formData,
                      formatID: e,
                    }
                    PID = '0'
                    setSelectedKeys([])
                    GetCatgTree(e, { current: 1 })
                  },
                }}
              />
            ) : (
              <></>
            )}

数据源有数据时在显示ProFormSelect
