### ISSUE TITLE
protable 表单查询，使用valueEnum去配置select下拉框，如何在选择完成后立即request

### ISSUE THREAD

**Issue by insistenceZHUO** [ant-design/pro-components#1166]
protable 表单查询，使用valueEnum去配置select下拉框，如何在选择完成后立即request，而不是选择完成后，需要点击成查询按钮触发request

**Comment by chenshuai2144** [comment]
可以使用 form.onValueChanger 监控 select 改变，然后触发submit

**Comment by insistenceZHUO** [comment]
请问下如何触发submit？监听到值变化后，使用ref.current.reload()刷新table，select的值没有更新，还是要点击查询按钮

**Comment by chenshuai2144** [comment]
@insistenceZHUO  `formRef.submit()` 就可以提交查询表单了

**Comment by AmbitionJs** [comment]
> onValueChanger

form.onValueChanger 具体怎么使用呢
