### ISSUE TITLE
🧐[问题]如何实现一个自定义的ProForm组件

### ISSUE THREAD

**Issue by cybermot** [ant-design/pro-components#1167]
### 🧐 问题描述

接入了一个MarkdownEditor和一个GraphEditor，
想要和ProFormText ProFormSelect ProFormTextArea一样作为ProForm组件使用，有参照的例子的文档吗，谢谢！

**Comment by chenshuai2144** [comment]
这样搞就好了，ProFormText  只是个 input 的快捷键，
```tsx
<FormItem>
   <GraphEditor />
</FormItem>
```

**Comment by peterzhai** [comment]
但是width不生效
