### ISSUE TITLE
🐛[BUG]  生产环境下 ProTable search 中form.getFieldsvalue() 为undefined

### ISSUE THREAD

**Issue by hazeFlame** [ant-design/pro-components#1168]
### 🐛 bug 描述

开发环境无异常
生产环境拿不到form

### © 版本信息

- "@ant-design/pro-table": "^2.4.0",
- umi 版本 3.2.3
- 浏览器环境 google 87.0.4280.66（正式版本） （64 位）
- 开发环境 [e.g. w10]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/21263459/100839850-e1f84f00-34af-11eb-959f-dcf18dbf9cac.png)
![image](https://user-images.githubusercontent.com/21263459/100839904-f4728880-34af-11eb-92d0-b9ca0c8cf81c.png)

**Comment by chenshuai2144** [comment]
是个bug，已经修了，今天会发版本

**Comment by chenshuai2144** [comment]
`npm i @ant-design/pro-table@2.12.2`

**Comment by hazeFlame** [comment]
> 已发布 `npm i @ant-design/pro-table@2.12.2`

我看optionRender里边也抛出form了呀，怎么2.12.1就没有呢

**Comment by hazeFlame** [comment]
> 已发布 `npm i @ant-design/pro-table@2.12.2`

![image](https://user-images.githubusercontent.com/21263459/100857822-1d067c80-34c8-11eb-9636-82856fa46fcb.png)
我本地是2.7 结果线上是2.12.1 这里边类型也没改变呀

**Comment by chenshuai2144** [comment]
类型没改，实现改了，为了减少 render 的次数
