### ISSUE TITLE
👑 [需求] 使用表头分组情况下、编辑功能好像并没有生效

### ISSUE THREAD

**Issue by summerboys** [ant-design/pro-components#1169]
### 🥰 需求描述
使用表头分组情况下、编辑功能好像没有生效

### 🧐 解决方案
期望能够支持表头分组的情况下编辑

**Comment by chenshuai2144** [comment]
有个pr帮忙支持了 发了版本应该能看到

**Comment by summerboys** [comment]
> 有个pr帮忙支持了 发了版本应该能看到

看到pr了、npm发包是什么节奏哈

**Comment by chenshuai2144** [comment]
发布了，可以看看了
