### ISSUE TITLE
👑 [支持标签栏导航]

### ISSUE THREAD

**Issue by liubin595338764** [ant-design/pro-components#1170]
### 🥰 能否支持标签栏导航

![image](https://user-images.githubusercontent.com/5274428/100850039-30144f00-34be-11eb-876a-c74783a744db.png)

[https://panjiachen.github.io/vue-element-admin/](https://panjiachen.github.io/vue-element-admin/)

像vue-element-admin后台管理系统一样，支持标签栏导航，可以快速记住打开过的页面。不然如果左侧菜单栏比较复杂，每次切换页面需要去菜单找二级甚至三级导航，也是比较费事的交互。

### 🧐 解决方案

在 `basiclayout.jsx` 里面的 `ProLayout`新增可以控制是否显示标签栏导航的配置项。

标签栏导航可以显示在现在的面包屑的位置。

**Comment by chenshuai2144** [comment]
在 umi 不支持 keeplive的 情况下，prolayout不会支持的。

你的需求可以用面包屑来实现的
