### ISSUE TITLE
🧐[问题]请问怎么样能修改 section 的样式，覆盖掉默认的 overflow 属性呢？

### ISSUE THREAD

**Issue by sunwenli** [ant-design/pro-components#1172]
### 🧐 问题描述 

我想修改内容区的 overflow 属性，但是在在 BasicLayout.jsx 里获取不到 section 组件

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/14137823/100859106-cf8b0f00-34c9-11eb-8b38-e4293b27f674.png)

**Comment by chenshuai2144** [comment]
这是 antd 的功能，为什么需要改？

**Comment by sunwenli** [comment]
> 这是 antd 的功能，为什么需要改？

我在用 ali-react-table 这个组件，他有个「表头吸顶」的功能，这个组件的父组件不能有 overflow:auto/hidden 属性，否则吸顶功能就失效了，这个 section 就是 ali-react-table 组件的父组件，所以我需要覆盖掉那个 overflow:hidden 属性

**Comment by chenshuai2144** [comment]
等 antd 解决吧，不然整个 layout 会挂掉，会乱出滚动条

**Comment by sunwenli** [comment]
找到了个临时的解决办法，手动修改 dom 🤣
```
modifySectionLayout = (tagName) => {
    // tagName = "section"
    let sectionDom = document.getElementsByTagName(tagName);
    if (sectionDom && sectionDom.length > 1) {
      let tableSection = sectionDom[1]
      ReactDOM.findDOMNode(tableSection).style.overflowX = "visible";
    }
  }
```

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design/issues/28154#issuecomment-738633127

这里antd 修了，可以去掉黑科技了
