### ISSUE TITLE
the property 'messageVariables' is added by mistake in QueryFilter

### ISSUE THREAD

**Issue by light0515** [ant-design/pro-components#1175]
When I try to add a ProText in a QueryFilter(ProForm 1.7.2), there is always an error like the following:
   _React does not recognize the `messageVariables` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `messagevariables` instead. If you accidentally passed it from a parent component, remove it from the DOM element._

and I found that: messageVariables is added to div

**Comment by chenshuai2144** [comment]
try use `fieldProps.messageVariables`
