### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#1185]
PorCard tabs使用报错

![image](https://user-images.githubusercontent.com/30397655/101022387-4bf61e80-35ac-11eb-9147-e04f6de41d9d.png)
Warning: Received `false` for a non-boolean attribute `animated`.

If you want to write it to the DOM, pass a string instead: animated="false" or animated={value.toString()}.

If you used to conditionally omit it with animated={condition && value}, pass animated={condition ? value : undefined} instead.

**Comment by rdmclin2** [comment]
收到
