### ISSUE TITLE
🧐[问题] proTAble如何手动实现onReset

### ISSUE THREAD

**Issue by Augustzyh** [ant-design/pro-components#1186]
### 🧐 问题描述

请教：onRest函数如何实现才能够清空request的查询参数？

**Comment by chenshuai2144** [comment]
你想清空什么内容？

**Comment by Augustzyh** [comment]
是这样的，这个issue可能把我的详情吃了。。。我再发一下

我们做的页面普遍需要吧状态放到dva管理，包括查询参数、分页信息等等，在request执行时做记录，当点击重置的时候，自然是要清空表单+request查询参数入参+dva管理的状态的，目前我在执行onRest的时候，通过dispatch更新了管理状态+通过formRef.current.restFeilds()清空了查询表单，按理说request此时的回参应该也是清空状态，但是却保存了重置前的参数状态，导致后面翻页查询请求没有办法正常进行

所以，想请问一下，如何手动清空request函数的params参数

我尝试过：
1、我有通过手动set params这个props吧查询字段全部置undefined，但是每次执行表格会刷新两次，并且还是清不掉request的回参，
2、也尝试过在beforeRequsetParams里对onRest做处理，但组件内置的执行顺序是 beforeRequsetParams -> onRest，导致我无法知道此次request是reset还是query

目前解决方法：
在onRest和onSubmit两个方法执行时区别状态，在request中手动deal params，可想是比较麻烦的额外使用了三个状态：查询、重置、重置后的页码切换，来区别三者

**Comment by chenshuai2144** [comment]
如果使用了dva，我建议你不要用proTable 的 request，就用的 dataSource 的方式来搞就好了。

request 唯一的方式就是帮你代理状态，现在你要自己做，反而变得更加麻烦了。

**Comment by Augustzyh** [comment]
是这样的，一开始理解的onRest内置方法是可以清空查询表单和参数才这么做的，后来才遇到查询参数清不掉的问题，所以来问一下有没有清空查询参数的方法，如果没有暴露这种方法且需求量不大的话，我还是换回dataSource吧，但是个人感觉，加上这种方法会让proTable变得更灵活且方便

**Comment by chenshuai2144** [comment]
这个很复杂， 因为数据来至很多地方，比如  分页器， 用户子的params， keywords， 查询表单的参数。这几个状态管起来超级复杂，这样就背离了 ProTable 的初衷了，我们本来就是为了减少状态

**Comment by Augustzyh** [comment]
emmm，request里的params回参不是只有查询表单关联的吗，清空params指的仅仅是protable原有的重置，因为原有的重置就是会清空表单及表单查询参数，现在想要手动清空只能清空表单，所以我觉得还是需要暴露一个可以手动清空表单查询参数的方法，当然也会重置分页器，这些其实都是回参里需要的，至于子params，和其他的归用户管理的不属于protable的状态，都是可以在request里二次添加的，两者并不影响哇

**Comment by chenshuai2144** [comment]
如果只想清空查询表单还是比较简单的，可以用 `formRef` 当成 antd 的 form 来操作查询表单

**Comment by Augustzyh** [comment]
你可以看看我最开始的描述，我就是用formRef.current.restFeilds()来清空查询表单的，但是requset里的回参并没有清空，我可以理解成这是一个bug嘛，清空查询表单并不能清空查询参数

**Comment by chenshuai2144** [comment]
还要调用一下submit

**Comment by Augustzyh** [comment]
我刚刚还去看了下源码，是这个样子没错。。是我脑子短路了。。。多谢了

**Comment by ccloveak** [comment]
> 还要调用一下submit

又学到一招

**Comment by qwe5117022** [comment]
> 还要调用一下submit

我这里
![image](https://user-images.githubusercontent.com/93125879/162404062-4152708b-e633-4467-9647-f668f7f92171.png)

**Comment by qwe5117022** [comment]
你好，我这样调用之后，还是无法清除表单的参数
