### ISSUE TITLE
🐛[BUG] 可编辑表格新增第二行时，第一行同时处于编辑状态

### ISSUE THREAD

**Issue by Nokecy** [ant-design/pro-components#1189]
https://codesandbox.io/s/patient-paper-nhz7c?file=/App.tsx

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/101130225-0aae4f00-363e-11eb-84da-8a5fe14ab9dc.png)

**Comment by chenshuai2144** [comment]
懂你意思了，因为两行用的 key 是相同的，所以都开始编辑了

**Comment by fanhualei** [comment]
> 懂你意思了，因为两行用的 key 是相同的，所以都开始编辑了

这个不应该是bug吧，key本来就不一样

**Comment by Nokecy** [comment]
应该是要生成不同的key吧

**Comment by chenshuai2144** [comment]
是 demo 的bug，在保存之后触发一下重新生成
