### ISSUE TITLE
🐛[BUG] 在使用ProTable 时， 参数 fieldProps 中设置的值, 部分不生效

### ISSUE THREAD

**Issue by ZhiGang-Fang** [ant-design/pro-components#1193]
### 🐛 bug 描述

使用在使用ProTable 时，
` fieldProps: {
        noStyle: true
      }, `
 参数 fieldProps 中设置的值， 不生效， 在官方的demo也加， 没有作用

### 🏞 期望结果

希望能和 Form 一样，添加noStyle: true 时， 只显示一个纯控件

### © 版本信息

- ProComponents 版本: [2.12.0]
- @ant-design/pro-table": "2.12.0"
- umi 版本
- 浏览器环境 [chrome: 87]
- 开发环境 [mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/24228407/101152591-435e2080-365e-11eb-82ee-3c423f3153fa.png)

通过renderFormItem 自定义表单项

![image](https://user-images.githubusercontent.com/24228407/101155688-70accd80-3662-11eb-9b72-c998260ad956.png)

**Comment by chenshuai2144** [comment]
`noStyle `是 `FormItem` 的属性， 应该用 `formItemProps`

**Comment by ZhiGang-Fang** [comment]
> `noStyle `是 `FormItem` 的属性， 应该用 `formItemProps`

请看我的第二张图片， 依然不能生效哦！！！ 谢谢

**Comment by ZhiGang-Fang** [comment]
> `noStyle `是 `FormItem` 的属性， 应该用 `formItemProps`

 https://codesandbox.io/s/restless-hooks-vyrm1?file=/App.tsx  请看这个demo 中的 动态表单， 设置了formItemProps ，依然没有效果， 麻烦帮忙看看，谢谢了

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/101327313-7cd69c00-38a9-11eb-98ff-4ef3b3ebd043.png)

你是锁包了吗?

**Comment by chenshuai2144** [comment]
看到了，自定义组件不能使用，我修一下
