### ISSUE TITLE
👑 [需求] ProCard 组件能否支持colSpan=0 , 以及grow属性

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#1195]
### 🥰 需求描述

* colSpan可以设置0，例如在某个尺寸就不显示：`colSpan={{ xs: 3, sm: 3, md: 3, lg: 3, xl: 0 }}`

* 增加grow属性:放大比例，默认为`0`，即如果存在剩余空间，也不放大。如果所有项目的`grow`属性都为1，则它们将等分剩余空间（如果有的话）。如果一个项目的`grow`属性为2，其他项目都为1，则前者占据的剩余空间将比其他项多一倍。

就是建议，后来想想，不增加这两个属性也行，平时用到的也不多。

**Comment by rdmclin2** [comment]
colSpan = 0 的时候 可以 'display: none'

**Comment by rdmclin2** [comment]
grow 的根据场景其实都有，差别不大，grow 的话 card 会挤占剩余空间，不设置的话就像div一样设置多宽就是多宽。我倾向于不做意外的举动，如果需要可以传递 style 进来。
