### ISSUE TITLE
hash路由下面包屑生成路径问题👑 [需求]

### ISSUE THREAD

**Issue by Picsong** [ant-design/pro-components#1197]
### 🥰 需求描述
能否给PageContainer组件增加一个面包屑配置，就是让面包屑的path前面加不加#号

**Comment by chenshuai2144** [comment]
PageContainer 本质上是 pageHeader，所以你可以用它的任何 api

https://ant.design/components/page-header-cn/#API

**Comment by Picsong** [comment]
谢谢了，还是文档看少了哈哈


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 下午4:45
收件人:&nbsp;"ant-design/pro-components"<pro-components@noreply.github.com&gt;;
抄送:&nbsp;"Picsong"<312465087@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/pro-components] hash路由下面包屑生成路径问题👑 [需求] (#1197)





 
PageContainer 本质上是 pageHeader，所以你可以用它的任何 api
 
https://ant.design/components/page-header-cn/#API
