### ISSUE TITLE
ModalForm不支持footer属性吗？🧐[问题]

### ISSUE THREAD

**Issue by Web-Delevan** [ant-design/pro-components#1202]
### 🧐 问题描述

ModalForm不支持footer属性吗？想在下面自定义3个按钮，如何设置？

### 💻 示例代码
<ModalForm
      title={isEdit ? '编辑内容管理' : '添加内容管理'}
      layout="horizontal"
      visible={editData.visible}
      labelCol={{ span: 4, offset: 4 }}
      onVisibleChange={(values) => onVisibleChange(values)}
      onFinish={changeSave}
      modalProps={{
        footer: [
          <Button key='0'>取消</Button>,
          <Button key='1'>保存</Button>,
          <Button key='2'>发布</Button>,
        ]
      }}
>

**Comment by chenshuai2144** [comment]
ModalForm 是个 form 用 proform的api 来自定义。

看看这个demo
https://procomponents.ant.design/components/form#%E8%A1%A8%E5%8D%95%E8%81%94%E5%8A%A8


```
submitter={{
          render: ({ form, onSubmit, step, onPre }) => {
            return [
              <Button
                key="rest"
                onClick={() => {
                  form?.resetFields();
                }}
              >
                重置
              </Button>,
              step > 0 && (
                <Button
                  key="pre"
                  onClick={() => {
                    onPre?.();
                  }}
                >
                  上一步
                </Button>
              ),
              <Button
                key="next"
                loading={loading}
                type="primary"
                onClick={() => {
                  onSubmit?.();
                }}
              >
                下一步
              </Button>,
            ];
          },
        }}

```
