### ISSUE TITLE
👑 [需求]ProTable是否可以支持隐藏th，也就是columns第一列，当`expandable={{ expandedRowRender }}`渲染嵌套Table为同一个的Table的场景

### ISSUE THREAD

**Issue by cybermot** [ant-design/pro-components#1206]
### 🥰 需求描述

ProTable是否可以支持隐藏th header行 也就是Table的第一列。
当`expandable={{ expandedRowRender }}`渲染嵌套Table是同一个Table的时候，columns重复的显示问题。
hideHeaderColumns
希望可以支持这个选项。

**Comment by cybermot** [comment]
现在是判断是嵌套Table之后 加额外的样式的
```
.table th {
  display: none;
}
```

**Comment by chenshuai2144** [comment]
https://ant.design/components/table-cn/#components-table-demo-dynamic-settings

antd 是支持的，你看看这里

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/101283260-37b45a80-3814-11eb-9c93-1bca6546a17a.png)
