### ISSUE TITLE
🐛[BUG] ProTable页面刷新或者切换时，产生 Can't perform a React state update on an unmounted component.🧐[问题]

### ISSUE THREAD

**Issue by cycloud1897** [ant-design/pro-components#121]
### 🐛 bug 描述
1. 使用简单的proTable的request为简单的请求服务端数据，发现页面刷新或者切换时，有时会产生 Can't perform a React state update on an unmounted component.的错误。
2. 这部分组件卸载处理需要开发者手动处理吗？

### 📷 复现步骤
1. 尝试多次刷新页面或者来回切换组件；
2. console产生日志警告；
![image](https://user-images.githubusercontent.com/34804246/89532963-37d02980-d825-11ea-9008-ba1e629dce76.png)

### 🏞 期望结果

无该警告。

### 💻 复现代码
1. 代码如下
![image](https://user-images.githubusercontent.com/34804246/89532595-9e087c80-d824-11ea-90fc-568e27e07373.png)
![image](https://user-images.githubusercontent.com/34804246/89532627-afea1f80-d824-11ea-9efb-35fa0a1ecd15.png)
2. 堆栈追踪
![image](https://user-images.githubusercontent.com/34804246/89533067-651cd780-d825-11ea-8a6a-4097c8b69656.png)
其中_callee$ | @ | useFetchData.js:130
![image](https://user-images.githubusercontent.com/34804246/89533136-854c9680-d825-11ea-8649-a9412b55e417.png)

### © 版本信息

- Ant Design Pro 版本: 4.1.0
- umi 版本 3.2.0
- 浏览器环境 chrome
- 开发环境 mac OS

**Comment by wly314** [comment]
对ProTable使用request异步请求数据时，在请求结果返回之前切换路由，因为组件卸载，但异步请求未中断，在返回数据之后引起该异常，应该是内部调用了setState。

**Comment by chenshuai2144** [comment]
ref https://github.com/ant-design/pro-components/pull/693
