### ISSUE TITLE
ProTable组件需要在查询后提示消息， 请问如何做？👑 [需求]

### ISSUE THREAD

**Issue by egene-huang** [ant-design/pro-components#1210]
### 🥰 需求描述

ProTable组件 设置manualRequest={true} 如果服务端返回了错误消息 需要提示到页面上

### 🧐 解决方案

 我建议在 onLoad函数参数不要只是 data 应该是服务端返回的整个对象 这样用户可以自定义处理 是否提示

**Comment by chenshuai2144** [comment]
@egene-huang   request 是你配置的， 你 catch 一下应该就好了吧

**Comment by egene-huang** [comment]
> @egene-huang request 是你配置的， 你 catch 一下应该就好了吧

嗯嗯 我最后想了 是的 我应该在request里 添加调用链 .then来处理  onLoad会调用多次 加这里不好  昨晚想撤销这个来着 给忘记了
