### ISSUE TITLE
ProTable请问如何自定义校验参数呢？🧐[问题]

### ISSUE THREAD

**Issue by egene-huang** [ant-design/pro-components#1212]
### 🧐 问题描述
我需要在输入参数校验通过后才会提交搜索请求？ 我找了一遍没有找到应该如何配置，谢谢了

**Comment by chenshuai2144** [comment]
不支持的，queryForm 不推荐使用 rules，我们推荐使用 默认值

**Comment by ccloveak** [comment]
把校验工作交给后端同学，省下时间泡杯咖啡

**Comment by egene-huang** [comment]
> 把校验工作交给后端同学，省下时间泡杯咖啡

😂  好吧 谢谢
