### ISSUE TITLE
🧐[问题]：ProTable的新增和修改能否用同一个组件？不想在表格里修改数据

### ISSUE THREAD

**Issue by fivefog** [ant-design/pro-components#1214]
### 🧐 问题描述

官方的例子是新增在CreateForm 组件，如何实现新增和修改都共用该组件？

### 💻 示例代码
   <CreateForm onCancel={() => handleModalVisible(false)} modalVisible={createModalVisible}>
        <ProTable<TableListItem, TableListItem>
          onSubmit={async (value) => {
            const success = await handleAdd(value);
            if (success) {
              handleModalVisible(false);
              if (actionRef.current) {
                actionRef.current.reload();
              }
            }
          }}
          rowKey="key"
          type="form"
          columns={columns}
        />
      </CreateForm>
      {stepFormValues && Object.keys(stepFormValues).length ? (
        <UpdateForm
          onSubmit={async (value) => {
            const success = await handleUpdate(value);
            if (success) {
              handleUpdateModalVisible(false);
              setStepFormValues({});
              if (actionRef.current) {
                actionRef.current.reload();
              }
            }
          }}
          onCancel={() => {
            handleUpdateModalVisible(false);
            setStepFormValues({});
          }}
          updateModalVisible={updateModalVisible}
          values={stepFormValues}
        />
      ) : null}

**Comment by ezdevelop** [comment]
官方例子里，标准列表（http://localhost:8000/list/basic-list）就是共用form组件

**Comment by fivefog** [comment]
> 官方例子里，标准列表（[http://localhost:8000/list/basic-list）就是共用form组件](http://localhost:8000/list/basic-list%EF%BC%89%E5%B0%B1%E6%98%AF%E5%85%B1%E7%94%A8form%E7%BB%84%E4%BB%B6)

那个标准列表是all-blocks分支的，ProComponents不能实现吗？

**Comment by chenshuai2144** [comment]
@fivefog  有的，在基本的demo里。

https://procomponents.ant.design/components#crud
