### ISSUE TITLE
🐛[BUG] ProLayout menu 属性中没有loading 例子上却有

### ISSUE THREAD

**Issue by hazeFlame** [ant-design/pro-components#1216]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/21263459/101304553-75000300-387b-11eb-88ea-dece88c22e94.png)
![image](https://user-images.githubusercontent.com/21263459/101304566-7c271100-387b-11eb-8207-0bf3015cfe16.png)

**Comment by chenshuai2144** [comment]
升级下你的 layout 版本吧

**Comment by hazeFlame** [comment]
> 升级下你的 layout 版本吧

我现在6.4.15

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/101314330-3f671400-3893-11eb-9a25-87f5ee3e8ca7.png)


新版本的提示是这样的, 你应该是安装了多份的代码

**Comment by hazeFlame** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/101314330-3f671400-3893-11eb-9a25-87f5ee3e8ca7.png)
> 
> 新版本的提示是这样的, 你应该是安装了多份的代码

![image](https://user-images.githubusercontent.com/21263459/101314440-83f2af80-3893-11eb-8396-8053551517ed.png)
用的是这个

**Comment by chenshuai2144** [comment]
去看看package.json。 这个明显是低版本的

**Comment by hazeFlame** [comment]
> 去看看package.json。 这个明显是低版本的

![image](https://user-images.githubusercontent.com/21263459/101314794-49d5dd80-3894-11eb-8693-fd48c7bc0195.png)
![image](https://user-images.githubusercontent.com/21263459/101314807-4f332800-3894-11eb-9858-fdb79a533494.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/101314927-8bff1f00-3894-11eb-96ea-4d80835f9dd7.png)

**Comment by hazeFlame** [comment]
好了
