### ISSUE TITLE
👑 [需求] ProForm中extra的显示位置，是否可以有多种选择？

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#1217]
### 🥰 需求描述
ProForm中extra的显示位置，是否可以有多种选择？

现在 extra 的位置在输入组件的下方，如果是从上往下的排序，太占地方，能不能放在右侧？例如下图。【也不知道这个想法成熟不，如果按照我的想法，布局上可能会很麻烦，或者我在原有的组件上进行继承与包装，然后把extra放在右侧，我再研究研究】

当前的布局：
![form-current](https://user-images.githubusercontent.com/34436863/101304977-7e3d9f80-387c-11eb-82a1-b0416ed98e85.png)

设想的布局：
![form](https://user-images.githubusercontent.com/34436863/101304989-8564ad80-387c-11eb-96ea-e90c913a2dae.png)

**Comment by chenshuai2144** [comment]
你的这个设计太丑了，我们估计不会实现。

用 Space 包一下 FormItem 就实现了
