### ISSUE TITLE
🧐[问题] ProLayout 怎么实现菜单分组?

### ISSUE THREAD

**Issue by shiny** [ant-design/pro-components#1219]
### 🧐 问题描述

类似于 ant pro 里这个 issue, https://github.com/ant-design/ant-design-pro/issues/5541 
同样的结构实测 ProLayout 无法实现 Menu.ItemGroup 功能，请问如何才能做到菜单分组呢？

### 💻 示例代码
```

export default {
  route: {
    name: 'Navigation one',
    routes: [
      {
        name: '操作',
        routes: [
          {
            name: '首页1',
            path: "/1"
          },
          {
            name: '首页2',
            path: "/2"
          }
        ]
      }
    ]
  }
}
```
![image](https://user-images.githubusercontent.com/117487/101313743-d7fc9480-3891-11eb-8106-0eca9f1d7ea6.png)

**Comment by chenshuai2144** [comment]
现在时不支持的，你有兴趣帮忙支持一下吗？

**Comment by shiny** [comment]
@chenshuai2144 试着自己改了下源码，现在比较困惑的地方是用户可能想要一个 SubMenu 也可能想要的是 Menu.ItemGroup，如何在 MenuDataItem 结构中区分，比如加一个 isItemGroup 属性？
```
 /**
   * @name 设置为分组标题
   */
  isItemGroup?: boolean;
```

代码
```
export default {
  route: {
    path: '/',
    routes: [
      {
        name: 'Navigation one',
        icon: <CrownOutlined />,
        routes: [
          {
            name: '操作',
            isItemGroup: true,
            routes: [
              {
                name: '首页1',
                path: "/1"
              },
              {
                name: '首页2',
                path: "/2"
              }
            ]
          }
        ]
      }
    ]
  }
}
```
实现了效果
<img width="203" alt="image" src="https://user-images.githubusercontent.com/117487/101329946-fde36280-38ac-11eb-8cef-6155caf8f323.png">

**Comment by chenshuai2144** [comment]
menu 中增加一个` type: 'sub'| 'group'`

这样应该就能解决问题了，不过openKeys 是不是就不需要了

**Comment by shiny** [comment]
直接在 ProLayout 的 menu 中新增 type 统一用某个类型的话，就无法实现 SubMenu 与 Menu.ItemGroup 组合使用的需求了，类似 antd 文档中的效果。

**Comment by chenshuai2144** [comment]
这个就有点复杂了 除非做成动态设置的

**Comment by shiny** [comment]
> 这个就有点复杂了 除非做成动态设置的

可以在 router 里指定类型，然后在这块区域根据类型生成  SubMenu 或 Menu.ItemGroup https://github.com/ant-design/pro-components/blob/804232ba4706bbde9875eb0642e53654ac2aa4e5/packages/layout/src/SiderMenu/BaseMenu.tsx#L102

**Comment by chenshuai2144** [comment]
那就复杂了，先支持一下全局切换吧，我记得有个别的issue 也要求支持

**Comment by hsbtr** [comment]
`subMenuItemRender` 这个自行实现得话似乎是可以实现这种效果得
