### ISSUE TITLE
👑 [需求]EditableProTable在新建行和编辑行时，需要联动

### ISSUE THREAD

**Issue by JTenacity** [ant-design/pro-components#1220]
### 🥰 需求描述

新建编辑数据时，第一列是一个下拉，如下拉值为标准，则后面第二列的输入框不允许输入。并且需要清空输入框的值。

### 🧐 解决方案
目前我在fieldProps中加了disabled发现不可用

### 🚑 其他信息
版本信息：
"@ant-design/pro-table": "^2.13.1",
"antd": "^4.9.1",
开发环境： mac

**Comment by chenshuai2144** [comment]
@JTenacity  用 renderFormItem 和 onChange 来实现吧

**Comment by JTenacity** [comment]
@chenshuai2144 还有一个需求，搜索的label我不想要，我重新用renderFormItem写<Input>还是会有label名称

**Comment by chenshuai2144** [comment]
这样来一下  `formItemProps:{ noStyle:true }`

**Comment by chenshuai2144** [comment]
提供了一个新方案，明天来了试一试

**Comment by JTenacity** [comment]
@chenshuai2144 有这样一个情况，valueType为money时，有￥符号，不想要，如果用reder自己处理，编辑时又会有问题。

**Comment by chenshuai2144** [comment]
valueType 支持传入函数的，可以根据不行的类型展示不同的 valueType

**Comment by 13632632437** [comment]
renderFormItem 

> @JTenacity 用 renderFormItem 和 onChange 来实现吧
renderFormItem返回的元素希望可以使用dependencies或者shouldUpdate一样响应其他列的变化，目前没有任何作用，就算将
renderFormItem:(_,record) => <我的组件 record/> 我的组件只有在首次加载时渲染一次，record无论如何变化我的组件都接收不到，没有重新渲染
