### ISSUE TITLE
👑 [需求]prolist内部item显示优化

### ISSUE THREAD

**Issue by BooYeu** [ant-design/pro-components#1226]
### 🥰 需求描述

ProList左边的部分竖直排序时，若存在图片， actions不能在底部

### 🧐 解决方案

能否在左边部分使用flex布局而非block布局，然后space-between

### 🚑 其他信息

![屏幕截图 2020-12-07 180710](https://user-images.githubusercontent.com/16587763/101337909-3ab45700-38b7-11eb-9c05-bfad1b9170a5.png)

**Comment by chenshuai2144** [comment]
这个好像是为了兼容 ie11，等 antd 的解决方案吧
