### ISSUE TITLE
🐛[BUG]ProTable: options字段里面添加 search 点击搜索分页current依旧为当前页

### ISSUE THREAD

**Issue by pollux2015** [ant-design/pro-components#1230]
### 🐛 bug 描述
1.  ProTable： options字段里面添加 search
2. 将表格翻页到第3页, 点击options里面的搜索
3. 在request函数里面返回的参数 params: current 依旧为第3页， 不是应该返回第1页?

### 🏞 期望结果
params: current 依旧为第3页， 不是应该返回第1页?
1. 如果要将分页重置为第1页， 应该怎么处理呢
2. 如果options的search字段的onSearch函数内actionRef.current?.reloadAndRest()又会将search输入的内容清空

### 💻 复现代码
![image](https://user-images.githubusercontent.com/11935278/101430558-33855b80-3940-11eb-927b-0a7d7f3c4de4.png)

### © 版本信息

- ProComponents 版本: [^2.9.5]
- umi 版本 ^3.2.14
- 浏览器环境  chrome 87.0.4280.88
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
现在好像不支持这样的操作，你估计要受控 current 和 pageSize .

**Comment by pollux2015** [comment]
@chenshuai2144 怎么手动设置 table 的 pageSize 和 current
怎么获取proTable里面的pagination ？？

**Comment by chenshuai2144** [comment]
和antd的配置相同

**Comment by ccloveak** [comment]
亲身经验，要是不想对代码改动太多，又想控制当前页显示的话，建议把版本升为2.9.10

**Comment by pollux2015** [comment]
只需在onsearch的时候， 手动设置 pagination.current设置为1就行了
