### ISSUE TITLE
🧐[问题]ProFormCheckbox.Group 能快速实现全选功能吗？

### ISSUE THREAD

**Issue by nylqd** [ant-design/pro-components#1231]
### 🧐 问题描述

ProFormCheckbox.Group 能快速实现全选功能吗？

目前自己参考checkbox的全选通过fieldProps里面设置value的形式实现了全选效果，但是在ProForm提交的时候校验required不通过，似乎form没有拿到里面的值，是否有哪位大佬实践过，指导一二？

**Comment by agansd123** [comment]
`const PermissionItem = (props) => {
  const {title,name, options,defaultValues = [],form} = props;
  const [indeterminate,setIndeterminate] = useState(true);
  const [checkAll,setCheckAll] = useState(false);

  useEffect(() => {
    // 设置默认值
    form.setFieldsValue({
      [name]: defaultValues
    })
  },[])

  // 修改item项时
  const onChange = list => {
    setIndeterminate(!!list.length && list.length < options.length);
    setCheckAll(list.length === options.length)
  }

  // 选择全部时
  const onCheckAllChange = e => {
    form.setFieldsValue({
      [name]: e.target.checked ? options : []
    })
    setIndeterminate(false);
    setCheckAll(e.target.checked);
  }

  return  <ProForm.Group title={title}>
    <ProFormCheckbox.Group
      name={name}
      label={<Checkbox indeterminate={indeterminate} onChange={onCheckAllChange} checked={checkAll}>全部</Checkbox>}
      options={options}
      onChange={onChange}
    />
  </ProForm.Group>
}`

使用 `form.setFieldsValue`设置对应项的值

![image](https://user-images.githubusercontent.com/51066798/119329057-62f20f80-bcb7-11eb-87e6-2c98b2a93c37.png)

这是我的做法，目前看起来运行的不错
