### ISSUE TITLE
🧐[问题] 如何修改proTable的params参数字段?

### ISSUE THREAD

**Issue by fivefog** [ant-design/pro-components#1232]
### 🧐 问题描述

怎样把current更改为pageNum?
在data.d.ts定义了, 请求传参处如何更改

### 💻 示例代码

 request={async (
    // 第一个参数 params 查询表单和 params 参数的结合
    // 第一个参数中一定会有 pageSize 和  current ，这两个参数是 antd 的规范
    params: T & {
      pageSize: number;
      current: number;
    }

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/53244212/101445546-a7356180-395c-11eb-9fbc-99dcc176961f.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/101459717-8f1d0c80-3973-11eb-8dce-2bc7cbe45f3e.png)

你在这里转一下不就好了

**Comment by samllLuck** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/101459717-8f1d0c80-3973-11eb-8dce-2bc7cbe45f3e.png)
> 
> 你在这里转一下不就好了

图片看不到啊
