### ISSUE TITLE
🧐[问题]pro-form和antd的form有啥区别？有没有使用的文档？

### ISSUE THREAD

**Issue by calmchang** [ant-design/pro-components#1236]
pro-form和antd的form有啥区别？有没有使用的文档？

**Comment by calmchang** [comment]
何为重型组件？什么场景下使用比较合适？如何确定使用pro-compoents组件还是使用antd原始组件？

**Comment by DerrickTel** [comment]
> pro-form和antd的form有啥区别？有没有使用的文档？
https://procomponents.ant.design/components/form

> 何为重型组件？什么场景下使用比较合适？如何确定使用pro-compoents组件还是使用antd原始组件？
重型组件：我说一下我个人的理解吧。我觉得是一个会依赖很多组件的组件，简单举个例子，比如说antd 的 Table 组件，他不单单是一个表格，附带了分页，筛选，选择等功能。
后面两个问题pro-compoents的官网有说明。
https://procomponents.ant.design/components/
