### ISSUE TITLE
👑 [需求] protable外面的card组件带上边框需求

### ISSUE THREAD

**Issue by KellenHe** [ant-design/pro-components#1237]
### 🥰 需求描述

protable外面的card组件能否带上边框，默认不带边框。
或者提供api可以设置带不带。

还有table的大小，antd提供了middle，default和size。pro table默认使用了middle。请问能否提供修改size的接口

**Comment by chenshuai2144** [comment]
table的都支持，card 你可以来个pr。

先看看文档
