### ISSUE TITLE
编辑表单如何获取 到ID🧐[问题]

### ISSUE THREAD

**Issue by MoonSeeing** [ant-design/pro-components#1240]
### 🧐 问题描述
从列表页到编辑表单弹窗，表单使用StepsForm，如果只需编辑name,code两个字段。但是因为更新需要用到id,那id 如何隐藏在表单中呢，在提交数据的时候带上id?

**Comment by chenshuai2144** [comment]
id 是什么鬼？

编辑不应该用 name

**Comment by MoonSeeing** [comment]
> id 是什么鬼？
> 
> 编辑不应该用 name
修改name 的接口不得有id 后台才能识别吗？没看到 id 怎么放到 form 中去 form提交的时候只能提交表单的field吗？

**Comment by chenshuai2144** [comment]
name 决定了你的key， 比如` <FormItem name="username"/> `, 提交的数据就是 ` { username: ""  }`

id 是用来标定页面元素的，和表单没有关系

**Comment by MoonSeeing** [comment]
> name 决定了你的key， 比如`<FormItem name="username"/>`, 提交的数据就是 ` { username: "" }`
> 
> id 是用来标定页面元素的，和表单没有关系
所以假设更新接口 需要用到 id ，自己把id 和表单数据 整合  调用 后台接口咯

**Comment by chenshuai2144** [comment]
你搞一个看不见的 input 就好了

**Comment by MoonSeeing** [comment]
> 你搞一个看不见的 input 就好了，或者用 initialValues

在stepForm 中尝试了设置 initialValues={id:1233}，但是 提交表单时数据里面并没有包含id这个属性，隐藏的input倒是可以但是比较不优雅，哈哈

**Comment by chenshuai2144** [comment]
initialValues 应该生效的， 隐藏 input 可是在03年开始就一直在用的超级技能，input 专门出了个hidden属性

**Comment by MoonSeeing** [comment]
> initialValues 应该生效的， 隐藏 input 可是在03年开始就一直在用的超级技能，input 专门出了个hidden属性
谢谢

**Comment by LeeeMooo** [comment]
> initialValues 应该生效的， 隐藏 input 可是在03年开始就一直在用的超级技能，input 专门出了个hidden属性

initialValues设置了还是无效, 只能用隐藏form了, 太不优雅了
