### ISSUE TITLE
🧐[问题] access设置菜单权限，需要刷新页面才生效

### ISSUE THREAD

**Issue by Augustzyh** [ant-design/pro-components#1241]

**Comment by Augustzyh** [comment]
。。。。这个提交会吃描述啊 卧槽
重新写一下吧

问题描述：
如下代码，在access中设置菜单权限，登陆前打印行值为false，登陆后打印为true，但是看不到home页面，此时刷新页面，打印为true，home页才出现

所以，每次登陆需要刷新一下才能加载菜单权限嘛，请问这个是怎么处理的

代码：
access.ts
export default function access(initialState: { currentUser?: API.CurrentUser | undefined }) {
  const { currentUser } = initialState || {};
  console.log(Boolean(currentUser && currentUser.status === 1)) // 打印 true or false
  return {
    allMenuAccess: Boolean(currentUser && currentUser.status === 1)
  };
}

路由之一： 
{
  path: '/HOME',
  name: 'home',
  icon: 'HomeOutlined',
  component: './Home',
  access: 'allMenuAccess',
}

**Comment by Augustzyh** [comment]
initialState是通过umi  useModel 更新的

**Comment by chenshuai2144** [comment]
我记得在某个版本中修复了，你试试更新以下所有的依赖
