### ISSUE TITLE
👑 [需求] EditableProTable支持添加一行数据Button文字自定义

### ISSUE THREAD

**Issue by JTenacity** [ant-design/pro-components#1242]
### 🥰 需求描述
希望EditableProTable的recordCreatorProps Api中可以加入对添加一行数据按钮的文字自定义传入

### 🚑 其他信息

"antd": "^4.9.1",
 "@ant-design/pro-table": "^2.13.1",

**Comment by chenshuai2144** [comment]
看起来是可以 run 的
```tsx
  recordCreatorProps={{
          position,
          record: newRecord,
          creatorButtonText: '测试',
        }}
```

**Comment by JTenacity** [comment]
@chenshuai2144 EditableProTable中editable Api重写了actionRender，新建一行数据，点击取消如何清除新建的那一行
![Uploading image.png…]()

**Comment by BigFaceMaster** [comment]
![Uploading image.png…]()

**Comment by chenshuai2144** [comment]
`  actionRef?.current?.cancelEditable` 用这个就好了
