### ISSUE TITLE
🐛[BUG]开发环境热更新时经常报错，表格加载失败

### ISSUE THREAD

**Issue by oldturkey** [ant-design/pro-components#1244]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/23737028/101615529-3324b780-3a49-11eb-85ed-40051136053b.png)
![image](https://user-images.githubusercontent.com/23737028/101615545-3750d500-3a49-11eb-8b98-b58dde81046a.png)

### 📷 复现步骤
刷新页面能正常获取到表格，但是修改代码热更新的时候页面直接报错，报useEdit 错误时表格数据获取失败

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境 
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
可能状态太复杂了，热更新只能更新部分状态，导致数据不及时

**Comment by oldturkey** [comment]
> 可能状态太复杂了，热更新只能更新部分状态，导致数据不及时

这种情况有什么好的避免排查方式么，最近准备项目里重度使用pro-table，可以请教请教嘛

**Comment by chenshuai2144** [comment]
这个需要热更新的框架解决了，你们用什么热更新的框架？

**Comment by oldturkey** [comment]
> 这个需要热更新的框架解决了，你们用什么热更新的框架？
我加你钉钉了，有空的话请教一下。。

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
