### ISSUE TITLE
🐛[BUG]ProTable scroll 失效，表格被撑开

### ISSUE THREAD

**Issue by didi5683** [ant-design/pro-components#1249]
### 🐛 bug 描述

更新最新版本后，ProTable scroll 属性失效，表格没法横向滚动

**Comment by DerrickTel** [comment]
给个可以复现的demo。

**Comment by didi5683** [comment]
> 给个可以复现的demo。

现在已经退回之前的版本了，测试了一下，应该是更新了 antd 之后出现的问题。

设置 table 的 scroll 属性就可以看到效果。
scroll={ { x: 1300 } }

正常表现应该是表格出现横向滚动条，但是目前的状态是没有出现滚动条，而是整个表格被撑开，超出了屏幕的可视范围。
