### ISSUE TITLE
🐛[BUG]ProLayout 6.6.0 的样式 ant-pro-global-header 失效

### ISSUE THREAD

**Issue by magiclee203** [ant-design/pro-components#1253]
### 🐛 bug 描述

ProLayout 6.6.0 的样式 ant-pro-global-header 失效，导致 Header 和页面其他部分无法区分

### 📷 复现步骤

升级 ProLayout 至 6.6.0 即可复现，ProLayout 官网文档也存在该问题

### © 版本信息

- ProLayout 版本: 6.6.0

### 🚑 其他信息

<img width="993" alt="截屏2020-12-10 上午12 06 29" src="https://user-images.githubusercontent.com/14924792/101655070-253c5a00-3a7c-11eb-92db-ce57df546dfb.png">

**Comment by chenshuai2144** [comment]
这里修掉了 
https://github.com/ant-design/pro-components/pull/1252
