### ISSUE TITLE
🐛[BUG] 在使用 pro-form 的 QueryFilter 时， ProFormText   fieldProps 的 addonBefore 验证不能全部标红 

### ISSUE THREAD

**Issue by ZhiGang-Fang** [ant-design/pro-components#1261]
### 🐛 bug 描述

在使用 pro-form 的 QueryFilter 时， ProFormText  fieldProps  addonBefore 验证不能全部标红 

### 🏞 期望结果
在校验时能将其addonBefore 给的组件一起标红哦

![image](https://user-images.githubusercontent.com/24228407/101725213-2eb0db00-3aeb-11eb-9dc7-f28a36b380de.png)

### 💻 复现代码
`

https://codesandbox.io/s/boring-shamir-g0j9h?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/24228407/101725142-0a54fe80-3aeb-11eb-8e0a-8cff4788d4bf.png)

**Comment by DerrickTel** [comment]
antd 的 bug。。。
https://codesandbox.io/s/5l3sw?file=/index.js:4630-4641
官方的demo里面有一个+86 那个，一模一样的bug

**Comment by chenshuai2144** [comment]
Antd就是这样的 毕竟是自己粘的组件可以需要自己实现一下了
