### ISSUE TITLE
🐛[BUG] ProTable查询搜索会报错search.transform is not a function

### ISSUE THREAD

**Issue by wscart** [ant-design/pro-components#1262]
### 🐛 bug 描述

```
{
  title: item.alias,
  dataIndex: item.field,
  search: item.search,（关键的问题）
  hideInTable: item.hideInTable,
  render: (dom: any, entity: any) => {
      return ProFormItem(item, entity, index, 'list');
  },
  renderFormItem: (_: any, { type, defaultRender, ...rest }: any) => {
      if (type === 'form') {
          return null;
      }
      return FormItem(item, _, rest, index);
  }
}
```

目前问题是，
1、其中search属性有存在，会报错的，没办法去查询请求一下。（search.transform is not a function）
2、当去掉search属性，一切都正常查询的，没报错的。

### © 版本信息

- pro-table 版本: 2.15.1
- umi 版本： 3.3.1
- 浏览器环境： chrome
- 开发环境: macOS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/3970076/101727739-09729b80-3af0-11eb-9332-91db0bcc6df6.png)

**Comment by wscart** [comment]
我用错了，将 search换成hideInSearch 就好

**Comment by youngclean** [comment]
用hideInSearch会有警告提示

**Comment by wscart** [comment]
我注意到了这个警告也得换search， 还没明白什么问题导致的。
暂时先用hideInSearch

**Comment by chenshuai2144** [comment]
@wscart  用 search =false，两个是反的
