### ISSUE TITLE
🧐ModalForm中使用useForm报错

### ISSUE THREAD

**Issue by MachiBarton** [ant-design/pro-components#1263]
### 🧐 问题描述

想在打开modal时候使用 `form.setFieldsValue` 来设置修改值
但是会报 
_Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
    in Unknown (at FunctionCase/index.tsx:73)_

### 💻 示例代码
 ` if(props.initialValues){
    form.setFieldsValue(props.initialValues)
  }`

**Comment by chenshuai2144** [comment]
组件还没挂在你就要更新人家

**Comment by chenshuai2144** [comment]
试试 formRef
