### ISSUE TITLE
【BUG】【ProTable】ProTable中的查询字段，当下拉列表数据是服务器获取时，首次不渲染

### ISSUE THREAD

**Issue by chenghangcong** [ant-design/pro-components#1264]
const columns = [
   {
      title: 'A', 
      dataIndex: 'value'
      , renderFormItem: () => {
        return <Select allowClear placeholder="请选择">
          {Astate.map(item => 
                <Select.Option key={dict.value} value={item.value}>{item.name}</Select.Option>)
          }
        </Select>;
      }
      , render: (dom: React.ReactNode, entity) => {
        const find = Astate?.find(item => item.value === entity.value);
        return find?.name;
      }
    },
]

Astate  数据从服务器加载。
Protable 首次渲染后 搜索栏的下拉列表没值

**Comment by HQ1363** [comment]
同样遇到了 首页进入页面，protable数据不渲染问题，必须 点下 刷新table，才可以看到数据

**Comment by Cewr** [comment]
> 同样遇到了 首次进入页面，protable数据不渲染问题，必须 点下 刷新table，才可以看到数据
> `request={async () => { return { data: list, success: true, }; }}`

拉到搜索项再渲染表格就好了
![image](https://user-images.githubusercontent.com/51740945/101755478-e1933000-3b0f-11eb-8ce7-2cef55a4c738.png)

**Comment by chenshuai2144** [comment]
用request 或者options

**Comment by HQ1363** [comment]
> 用request 或者options

不是很明白，request和options指的是proTable的参数吗？这个我本来就都有在用啊

**Comment by HQ1363** [comment]
> > 同样遇到了 首次进入页面，protable数据不渲染问题，必须 点下 刷新table，才可以看到数据
> > `request={async () => { return { data: list, success: true, }; }}`
> 
> 拉到搜索项再渲染表格就好了
> ![image](https://user-images.githubusercontent.com/51740945/101755478-e1933000-3b0f-11eb-8ce7-2cef55a4c738.png)

多谢，效果已达到

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/field#%E8%BF%9C%E7%A8%8B%E6%95%B0%E6%8D%AE

**Comment by HQ1363** [comment]
> https://procomponents.ant.design/components/field#%E8%BF%9C%E7%A8%8B%E6%95%B0%E6%8D%AE

不对啊，你这个是表字段的更新问题，反馈的问题是整张表整体数据刷新问题
