### ISSUE TITLE
ProTable列顺序兼容问题🐛[BUG]

### ISSUE THREAD

**Issue by Noah-1994** [ant-design/pro-components#1265]
### 🐛 bug 描述

同样的列数组配置，在chrome下的顺序是对的，在360极速版下是另一个顺序

### © 版本信息

- pro-table [2.10.1]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
😂 360极速版和chrome的sort算法实现不一致吗

**Comment by Noah-1994** [comment]
貌似就特定版本有问题，别人的设备毕现，这个传进去的columns做了什么特殊处理吗，还是默认sort了一下，我吧optios都关了

**Comment by chenshuai2144** [comment]
默认有个排序，你可以麻烦一下 order 都写上，数字越大越在前面

**Comment by daiwenyu** [comment]
问题必现，Chrome68与89版本能复现
