### ISSUE TITLE
🐛[BUG]搜索框的label被遮挡

### ISSUE THREAD

**Issue by hyyqcweb** [ant-design/pro-components#1266]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/17583072/101749188-6d08c300-3b08-11eb-924e-16b1ec55e994.png)

**Comment by hyyqcweb** [comment]
如果搜索条件的label很长, 定义search.span为3列 ? 2列? 有没有更好的解决方法

**Comment by hyyqcweb** [comment]
```
fieldProps: {
  style: {
     width: 'xs'
   }
 }
```
好像不起作用???

**Comment by Cewr** [comment]
> ```
> fieldProps: {
>   style: {
>      width: 'xs'
>    }
>  }
> ```
> 
> 好像不起作用???

可以设置 labelWidth
![image](https://user-images.githubusercontent.com/51740945/101754482-c116a600-3b0e-11eb-8eb2-5ad65a399699.png)

**Comment by hyyqcweb** [comment]
> > ```
> > fieldProps: {
> >   style: {
> >      width: 'xs'
> >    }
> >  }
> > ```
> > 
> > 
> > 好像不起作用???
> 
> 可以设置labelWidth
> ![图片](https://user-images.githubusercontent.com/51740945/101754482-c116a600-3b0e-11eb-8eb2-5ad65a399699.png)

如果单独设置某一个字段, 应该怎么设置?

**Comment by Cewr** [comment]
> > > ```
> > > fieldProps: {
> > >   style: {
> > >      width: 'xs'
> > >    }
> > >  }
> > > ```
> > > 
> > > 
> > > 好像不起作用???
> > 
> > 
> > 可以设置labelWidth
> > ![图片](https://user-images.githubusercontent.com/51740945/101754482-c116a600-3b0e-11eb-8eb2-5ad65a399699.png)
> 
> 如果单独设置某一个字段, 应该怎么设置?

有auto项可以用
![image](https://user-images.githubusercontent.com/51740945/101755982-7c8c0a00-3b10-11eb-90ad-44a8df09e46f.png)

**Comment by hyyqcweb** [comment]
> > > > ```
> > > > fieldProps: {
> > > >   style: {
> > > >      width: 'xs'
> > > >    }
> > > >  }
> > > > ```
> > > > 
> > > > 
> > > > 好像不起作用???
> > > 
> > > 
> > > 可以设置labelWidth
> > > ![图片](https://user-images.githubusercontent.com/51740945/101754482-c116a600-3b0e-11eb-8eb2-5ad65a399699.png)
> > 
> > 
> > 如果单独设置某一个字段, 应该怎么设置?
> 
> 有auto项可以用
> ![image](https://user-images.githubusercontent.com/51740945/101755982-7c8c0a00-3b10-11eb-90ad-44a8df09e46f.png)

如果我有4个搜索条件, 一个label 8个字, 一个label 4个字, 二个label 2个字, 设置auto, 就不会工整了

**Comment by Cewr** [comment]
> > > > > ```
> > > > > fieldProps: {
> > > > >   style: {
> > > > >      width: 'xs'
> > > > >    }
> > > > >  }
> > > > > ```
> > > > > 
> > > > > 
> > > > > 好像不起作用???
> > > > 
> > > > 
> > > > 可以设置labelWidth
> > > > ![图片](https://user-images.githubusercontent.com/51740945/101754482-c116a600-3b0e-11eb-8eb2-5ad65a399699.png)
> > > 
> > > 
> > > 如果单独设置某一个字段, 应该怎么设置?
> > 
> > 
> > 有auto项可以用
> > ![image](https://user-images.githubusercontent.com/51740945/101755982-7c8c0a00-3b10-11eb-90ad-44a8df09e46f.png)
> 
> 如果我有4个搜索条件, 一个label 8个字, 一个label 4个字, 二个label 2个字, 设置auto, 就不会工整了

那应该没有吧，直接就写样式吧，选择器挨个改就是了~

**Comment by hyyqcweb** [comment]
@Cewr 可能我就想要单独对一列起效果的, 不过我看了一下api, 并没有这样设计的, fieldProps 好像也无法穿透下去, 也许还有一种方式是可以css 设置, 但是我觉得那样不好

**Comment by chenshuai2144** [comment]
可以用formInputProps自定义一下，这种差距很大的建议用上lable下输入框的模式

**Comment by hyyqcweb** [comment]
> formInputProps

formInputProps 应该怎么用呢. 是这样使用吗? 
```
fieldProps: {
  formInputProps: {width: xxx}
},
```

**Comment by chenshuai2144** [comment]
和fieldProps同级的

**Comment by bxj936176690** [comment]
<ProTable
  search={{
    labelWidth: 'auto'
  }}
/>
