### ISSUE TITLE
👑 [实现多标签页切换]

### ISSUE THREAD

**Issue by qianqianboy** [ant-design/pro-components#1267]
### 🥰 需求描述

Ant Design Pro这么优秀的脚手架工具，没有理由不支持点击菜单，右侧内容区顶部弹出Tab标签页，并支持切换标签页，右键关闭、关闭所有等这些常用等功能哇！！使用者自己实现一套有点麻烦，还不一定具有通有性。

### 🧐 解决方案

我大致的思路是先找到点击菜单时触发执行的监听函数，好像是onPageChange(),还有一些其他的监听函数，然后进行处理，根据路由信息，获取菜单信息，另外还得为所有page的最外面包裹一层tab组件，这点我在V5版本不知道该咋操作，最后还得实现标签页切换后会重新刷新，并支持右键关闭、关闭所有等功能。对大佬们来说，应该是小菜一碟啦哈哈哈哈哈

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/45479479/101755512-ea840180-3b0f-11eb-94fa-075cd294f327.png)

**Comment by chenshuai2144** [comment]
有重复的 这个问题出现好多次了
