### ISSUE TITLE
👑 [需求]关于 @ant-design/pro-layout的 breadcrumbRender 需求

### ISSUE THREAD

**Issue by huohongchang1026** [ant-design/pro-components#1269]
### 🥰 需求描述

使用prov5的时候 我的路由有 /a 和/a/b 的父子路由  但是/a没有具体页面，在配置里面也就没有写path 他只是为了在menu菜单当一级展示，现在我想在 PageContainer 里面自定义面包屑 在所有的页面上都加一个 首页   { path: '/', breadcrumbName: '首页' }，
我也想把/a的加上去，但是因为没有设置path所以不会有他，设置了path他又可以点击 然后跑到404页面 能不能加个功能 支持path没有配置 为不可点击的面包屑 或者把itemRender加上去 可以自定义 

### 🧐 解决方案

也可能我没有get到用法 希望有解决方案的可以告诉我一下

**Comment by chenshuai2144** [comment]
breadcrumbRender 就是itemRender 的，解决不了你的问题吗

**Comment by huohongchang1026** [comment]
> breadcrumbRender 就是itemRender 的，解决不了你的问题吗

 breadcrumbRender?: (routers: AntdBreadcrumbProps['routes']) => AntdBreadcrumbProps['routes'];  这是他的类型 只有routes 没有 itemRender 属性  我的版本是6.4.19

**Comment by chenshuai2144** [comment]
@huohongchang1026   支持了 breadcrumbProps 可以自定义了，会全部放到 子组件里
