### ISSUE TITLE
🐛[BUG]pro-layout 6.6.0开始，界面高度计算错误

### ISSUE THREAD

**Issue by quicklearning123** [ant-design/pro-components#1271]
### 🐛 bug 描述

更新后界面下方出现一块灰色区域。还原回6.5.19正常。6.6.0和6.6.1都有问题。

### 📷 复现步骤

必现

### 🏞 期望结果

界面正常

### 💻 复现代码

暂无

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] pro-layout 6.6.0
- umi 版本 3
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS] mac

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/70048681/101772633-96384c00-3b26-11eb-9363-746133261030.png)

**Comment by chenshuai2144** [comment]
是高度没有撑开吗？

**Comment by quicklearning123** [comment]
> 是高度没有撑开吗？

看起来是的，我们旁边有个折叠菜单，展开之后如果触及到灰色块区域时，灰色块就会下移。

**Comment by chenshuai2144** [comment]
来个重现地址吧，我试试为什么 dom 变了

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
