### ISSUE TITLE
🐛[BUG] 之前修复了 #713 有导致了另外一个问题

### ISSUE THREAD

**Issue by chenzhenjia** [ant-design/pro-components#1278]
### 🐛 bug 描述
当antd 全局配置 
```
getPopupContainer: (node) => {
    if (node && node.parentElement) {
      return node.parentElement;
    }
    return document.body;
  },
```
的时候会发生select下拉菜单中的值被隐藏，发现是之前修复 #713 bug导致select被 hidden 了
### 🏞 期望结果

设置 getPopupContainer 也可以下拉选择

### © 版本信息

- proTable 版本: [2.15.0]
- umi 版本 3.1.2
- 浏览器环境 chrome
- 开发环境 [windows]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/11611967/101866909-fc6bb000-3bb4-11eb-9e3e-1fb6bb9f3bca.png)

**Comment by chenshuai2144** [comment]
`node.parentElement.parentElement`

这样呢，如果不加那个样式 别的样式会报错

**Comment by chenzhenjia** [comment]
> `node.parentElement.parentElement`
> 
> 这样呢，如果不加那个样式 别的样式会报错

这样也不行，因为是样式是设置在formitem上，必须连着 parent 6次以上才可以。但是这样的话代码会变的好长。

**Comment by chenzhenjia** [comment]
提供两种解决办法
1. 第一种查找父元素找到form-item-control 的parentElement 就可以了，但是这种方式需要避免自己修改less 变量`ant-prefix`，并且 closest 也有可能有的浏览器不支持。
```
  getPopupContainer: (node) => {
    if (node) {
      const formItem = node.closest<HTMLElement>(".ant-form-item-control");
      const n = formItem || node;
      if (n.parentElement) {
        return n.parentElement;
      }
    }
    return document.body;
  },
```
2. 第二种就是把pro-table 里面的css给覆盖掉
```
@import "~@ant-design/pro-table/es/Form/index";

.@{pro-table-search-prefix-cls} {
  .@{ant-prefix}-form-horizontal .@{ant-prefix}-form-item-control {
    overflow: visible !important;
  }
}
```
