### ISSUE TITLE
🐛[BUG] ProFormSelect组件，valueEnum的值有变化时 页面不会重新渲染（和map对象有关）

### ISSUE THREAD

**Issue by zakrivi** [ant-design/pro-components#1282]
### 🐛 bug 描述
useDeepCompareEffect调用的isDeepEqual方法不会对map对象做判断
后果是一直为true，无法更新valueEnum
可改为fast-deep-equal/es6

### 💻 复现代码
https://codesandbox.io/s/interesting-burnell-mzps9?file=/src/App.js

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
有兴趣来个 pr 吗？

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/1302
