### ISSUE TITLE
响应式断点规则CONFIG_SPAN_BREAKPOINTS配置xl和lg的值一样，导致大部分取到是lg，并非xl🐛[BUG]

### ISSUE THREAD

**Issue by fisher-zwl** [ant-design/pro-components#1283]
### 🐛 bug 描述
代码：https://github.com/ant-design/pro-components/blob/master/packages/form/src/layouts/QueryFilter/index.tsx
const CONFIG_SPAN_BREAKPOINTS = {
  xs: 513,
  sm: 513,
  md: 785,
  lg: 1057,
  xl: 1057,
  xxl: Infinity,
};
lg和xl的值一致
const spanConfig = span
    ? Object.keys(span).map((key) => [CONFIG_SPAN_BREAKPOINTS[key], 24 / span[key], 'horizontal'])
    : BREAKPOINTS[layout || 'default'];

  const breakPoint = (spanConfig || BREAKPOINTS.default).find(
    (item: [number, number, FormProps['layout']]) => width < item[0] + 16, // 16 = 2 * (ant-row -8px margin)
   // 这里的判断很明显对xl和lg的取值会不准确
  );
  return {
    span: 24 / breakPoint[1],
    layout: breakPoint[2],
  };
上述代码width < item[0] + 16的判断，导致xl和lg取值间距只差了16，跟栅格定义中xl和lg不通
### 🏞 期望结果

根据视口大小，结合栅格定义的宽度范围做响应式调整

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- @ant-design/pro-form： 1.9.0
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
欢迎来个 pr
