### ISSUE TITLE
🐛[BUG]ProList不支持动态pagination

### ISSUE THREAD

**Issue by BooYeu** [ant-design/pro-components#1284]
### 🐛 bug 描述

ProList不支持request里的total数据来实现动态页码

### 📷 复现步骤

手动添加pagination，但只显示一页

### 🏞 期望结果

类似protable

### 💻 复现代码

`<ProList itemLayout="vertical" pagination={{ showTotal:true, defaultPageSize: 20, showSizeChanger: true, }} request={(params) =>({data:[{},{}],success:true,total:2})} />`

### © 版本信息

- ProComponents 版本: prolist 1.1.9
- umi 版本 3.3.1
- 浏览器环境 edge
- 开发环境 [e.g. mac OS] windows

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
fixed

**Comment by BooYeu** [comment]
> fixed in #1393

现在好像还是不支持类似protable的动态pagination？（在request里返回total自动生成分页）

**Comment by chenshuai2144** [comment]
支持了，用的同样的配置了
