### ISSUE TITLE
🧐[问题]CountDown倒计时组件的target参数不管给目标时间戳还是日期都导致页面直接加载不进去

### ISSUE THREAD

**Issue by RandolphCYG** [ant-design/pro-components#1289]
### 🧐 问题描述

表格某列渲染为CountDown组件，target参数给什么比较好？

### 💻 示例代码

```
{
      title: '过期时间',
      dataIndex: 'accountExpires',
      hideInForm: true,
      width: 120,
      render: (text: number) => {
        console.log(text, typeof text)
        if (text === -1) {
        return <Tag>{'永不过期'}</Tag>;
        } else {
          return <Tag><CountDown style={{ fontSize: 20 }} target={text} /></Tag>;
        }
      },
    },
```

这里我先将Tag中的CountDown注释掉，能走进去，看到打的日志是
![image](https://user-images.githubusercontent.com/31581116/101990117-cd059200-3cdf-11eb-9b06-79dfb7aa9407.png)
然后我将倒计时组件放进去，刷新页面，页面一直是加载状态？

后端也传过时间试验过日期字符串过来，一样操作后还是加载不出来页面了。

求助大伙儿，一般如何使用倒计时组件，并传什么更好一些？谢谢

**Comment by chenshuai2144** [comment]
https://ant.design/components/statistic-cn/
用这个把，那个已经停止维护了

**Comment by RandolphCYG** [comment]
ok 那文档可以给个提示，现在都不知道怎么选择更合适 （pro组件和antd组件）
