### ISSUE TITLE
列展示-能否配置默认展示列👑 [需求]

### ISSUE THREAD

**Issue by jassonxian** [ant-design/pro-components#129]
### 🥰 需求描述

在开启列设置的情况下，能否配置默认展示列
### 🧐 解决方案
Columns中是否有设置当前列默认是否展示的属性

### 🚑 其他信息
如：初始化时就不展示“进度”和“金额”
![image](https://user-images.githubusercontent.com/21199561/89631785-d2874180-d8d3-11ea-8823-3ee4e95ef41f.png)

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/table#%E5%8F%97%E6%8E%A7%E7%9A%84%E5%88%97%E6%98%BE%E7%A4%BA%E9%9A%90%E8%97%8F

可以用这种方式来显示，但是暂时不支持排序
