### ISSUE TITLE
🧐[问题]ProTable onCleanSelected 疑问

### ISSUE THREAD

**Issue by ezdevelop** [ant-design/pro-components#1291]
https://github.com/ant-design/pro-components/blob/406272522cb9d19fbe1ce68e100c200724c37d4f/packages/table/src/Table.tsx#L239-L250

为什么要把清空筛选、清空排序以及重置页码这些脱离字面意思的操作放在onCleanSelected方法，而不是放到reset去？

我的需求就是简单的取消选择，reload时并不想丢失筛选、排序参数或者重置页码

**Comment by chenshuai2144** [comment]
来个pr帮忙改一下？

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/107169406-b8e8c300-69f8-11eb-9257-73f8fd8c45b6.png)


改了
