### ISSUE TITLE
🐛[BUG] 查询表格中的搜索表单项输入文本再删除时查询参数仍然存在

### ISSUE THREAD

**Issue by zhengshubin** [ant-design/pro-components#1293]
### 🐛 bug 描述

 查询表格中的搜索表单项输入文本再删除时查询参数仍然存在
### 📷 复现步骤

 查询表格中的搜索表单输入文本再删除时查询参数仍然存在，但没有值。
### 🏞 期望结果

搜索项有值时才添加参数。
### 💻 复现代码

https://procomponents.ant.design/components/table
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来点祥细描述吧，没看懂

**Comment by zhengshubin** [comment]
> 来点祥细描述吧，没看懂

就是在搜索项输入文本 后再删除文本，点击查询后 url 会有该项的key，但没有值

**Comment by zhengshubin** [comment]
> 来点祥细描述吧，没看懂

比如 我 在  姓名项 输入文本，然后删除，点击搜索  请求  url 就是  xxxx.com?name=&group=xxx

**Comment by ccloveak** [comment]
我猜这个应该跟业务代码有关。。。你自己加个判断，搜索项的值为''时,不要往url上加查询参数

**Comment by chenshuai2144** [comment]
这个没什么好办法，你自己处理一下吧，还有人嫌我们把数据删掉了

**Comment by chenshuai2144** [comment]
这里有个算法，可以自己加一下
```
const omitUndefined = <T>(obj: T): T => {
  const newObj = {} as T;
  Object.keys(obj || {}).forEach((key) => {
    if (obj[key] !== undefined) {
      newObj[key] = obj[key];
    }
  });
  return newObj;
};

export default omitUndefined;

```
