### ISSUE TITLE
🐛[BUG] ProTable searchText 不生效

### ISSUE THREAD

**Issue by pentyh** [ant-design/pro-components#1294]
### 🐛 bug 描述

pro-table: 2.15.1 search
设置 searchText, resetText不生效

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 3.3.1
- 浏览器环境 chrome 最新
- 开发环境 [e.g. mac OS] windows 10

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/1872
