### ISSUE TITLE
🐛[BUG]protable将一个时间的查询重新渲染成区间查询，会影响行编辑功能

### ISSUE THREAD

**Issue by RandolphCYG** [ant-design/pro-components#1298]
### 🐛 bug 描述
为了方便查询，将对应的一个时间类型的查询表单改成了时间范围查询
![image](https://user-images.githubusercontent.com/31581116/102066027-44e4d100-3e34-11eb-9af4-447497e8b905.png)

但是这会影响行编辑功能

![image](https://user-images.githubusercontent.com/31581116/102066133-6b0a7100-3e34-11eb-8742-842c45e4f965.png)

### 📷 复现步骤

点击行上的编辑就会报错

### 🏞 期望结果

这样看来，我重新渲染查询表单，改掉了类型，都会导致表格行编辑报错，不知道如果能有一个字段控制是不是可以编辑某列，就能避开重新渲染的不需要编辑的列了

### 💻 复现代码

```
cosnt columns: ProColumns<T>[] = [
...
{
      title: '创建时间',
      dataIndex: 'whenCreated',
      hideInForm: true,
      width: 150,
      ellipsis: true,    // 省略过长文本
      valueType: 'dateTime',
      renderFormItem: () => {
        // 重写时间框选替代时间搜索
        return <RangePicker
          ranges={{
            '最近三月': [moment().subtract(3, 'months'), moment()],
            '最近三周': [moment().subtract(3, 'weeks'), moment()],
            '最近三天': [moment().subtract(3, 'days'), moment()],
            '今天': [moment().startOf('day'), moment()],
            '最近一小时': [moment().subtract(1, 'hours'), moment()],
          }}
          showTime
          format="YYYY/MM/DD HH:mm:ss"
        />;
      }
    },
{
      title: '操作',
      // dataIndex: 'options',
      valueType: 'option',
      tooltip: "高危操作都有二次确认弹窗!",
      hideInForm: true,
      search: false,
      fixed: 'right',
      width: 220,
      render: (text, record, _, action) => {
        return (
          [
            <a
              key="editable"
              onClick={() => {
                action.startEditable?.(record.sAMAccountName);
              }}
            >
              编辑
            </a>
          ]
        )
      }
]
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境 谷歌
- 开发环境 [win10]
- "@ant-design/pro-table": "^2.4.0"

**Comment by chenshuai2144** [comment]
renderText 把 列配置转换成 moment 试试，因为不是moment 的数组不适合RangePicker

或者你可以用renderFormItem 里的参数判断是编辑模式，就换成 defaultRender

**Comment by RandolphCYG** [comment]
OK 感谢 我试一下

在 2020年12月14日，19:55，陈帅 <notifications@github.com> 写道：

﻿

renderText 把 列配置转换成 moment 试试，因为不是moment 的数组不适合RangePicker

或者你可以用renderFormItem 里的参数判断是编辑模式，就换成 defaultRender
