### ISSUE TITLE
ProFormSelect通过value赋值，值赋上了但是没有显示🧐[问题]

### ISSUE THREAD

**Issue by vuvivian** [ant-design/pro-components#1299]
### 🧐 问题描述
在编辑的情况下 给state.currentWorkflowID赋上值了，但是没有显示出来

### 💻 示例代码
<ProFormSelect
                    name={item.typeId}
                    layout="vertical"
                    label={item.name}
                    rules={[{ required: true, message: `请选择${item.name}` }]}
                    request={async () => generateOptions(item.id)}
                    placeholder={`请选择${item.name}`}
                    fieldProps={{
                      onChange: handleTempChange,
                      allowClear: false,
                    }}
                    value={state.currentWorkflowID}
                  />

```
                           <ProFormSelect
				name={item.typeId}
				layout="vertical"
				label={item.name}
				rules={[{ required: true, message: `请选择${item.name}` }]}
				request={async () => generateOptions(item.id)}
				placeholder={`请选择${item.name}`}
				fieldProps={{
					onChange: handleTempChange,
					allowClear: false,
					value: state.currentWorkflowID
			      }}
                             value={state.currentWorkflowID}
									/>
```
给fieldProps中的value也赋上值就好了

```### 🚑 其他信息

<!--
如截图等其他信息可以贴在这里
-->

**Comment by chenshuai2144** [comment]
<ProFormXXX 要理解成 FormItem， FieldProps 才是内部的组件
