### ISSUE TITLE
🧐[问题] Protable 翻页时总是出现 VM19:1 Uncaught TypeError: Cannot read property 'match' of null

### ISSUE THREAD

**Issue by lizhongyue248** [ant-design/pro-components#1301]
### 🧐 问题描述

例如官网[实例1](https://procomponents.ant.design/components/list#%E5%B8%A6%E7%AD%9B%E9%80%89%E5%92%8C%E5%BC%82%E6%AD%A5%E8%AF%B7%E6%B1%82%E7%9A%84%E5%88%97%E8%A1%A8)

[实例 2](https://procomponents.ant.design/components/table#%E5%80%BC%E7%B1%BB%E5%9E%8B%E7%A4%BA%E4%BE%8B)

![image](https://user-images.githubusercontent.com/29678316/102098406-24cc0680-3e62-11eb-9da4-8b3b3b50a851.png)

![image](https://user-images.githubusercontent.com/29678316/102098885-a91e8980-3e62-11eb-9729-938aad3ebd11.png)

### 💻 示例代码

例如官网[实例1](https://procomponents.ant.design/components/list#%E5%B8%A6%E7%AD%9B%E9%80%89%E5%92%8C%E5%BC%82%E6%AD%A5%E8%AF%B7%E6%B1%82%E7%9A%84%E5%88%97%E8%A1%A8)

[实例 2](https://procomponents.ant.design/components/table#%E5%80%BC%E7%B1%BB%E5%9E%8B%E7%A4%BA%E4%BE%8B)

**Comment by chenshuai2144** [comment]
升级一下antd把，这个我记得是个antd的bug，正则没写好

**Comment by lizhongyue248** [comment]
> 升级一下antd把，这个我记得是个antd的bug，正则没写好

升级了依旧出现

```
    "@ant-design/colors": "^5.0.1",
    "@ant-design/icons": "^4.3.0",
    "@ant-design/pro-card": "^1.8.0",
    "@ant-design/pro-descriptions": "^1.2.0",
    "@ant-design/pro-form": "^1.10.4",
    "@ant-design/pro-layout": "^6.8.0",
    "@ant-design/pro-list": "^1.1.14",
    "@ant-design/pro-table": "^2.16.4",
    "antd": "^4.9.4",
```

![image](https://user-images.githubusercontent.com/29678316/102953675-d2977f00-450c-11eb-82a1-9992c4e18908.png)

**Comment by lizhongyue248** [comment]
https://user-images.githubusercontent.com/29678316/102954056-a4666f00-450d-11eb-9ac3-39145731b21f.mp4

**Comment by chenshuai2144** [comment]
那就是你的浏览器插件的锅了，你翻译了文档还是用了选中获取的插件
