### ISSUE TITLE
引入 @ant-design/pro-table 报错

### ISSUE THREAD

**Issue by im-not-a-programmer** [ant-design/pro-components#1303]
### 🐛 bug 描述

TypeScript error in E:/hitcxedu-web_3.0/node_modules/@ant-design/pro-field/lib/index.d.ts(87,1):
Declaration or statement expected.  TS1128

    85 | } & RenderProps;
    86 | export { FieldPercent, FieldIndexColumn, FieldProgress, FieldMoney, FieldDatePicker, FieldRangePicker, FieldCode, FieldTimePicker, FieldText, FieldStatus, FiledSelect, proFieldParsingText, proFieldParsingValueEnumToArray, };numToArray, };
  > 87 | export type { ProFieldValueType };
       | ^
    88 | declare const _default: React.ForwardRefRenderFunction<any, ProFieldPropsType>;
    89 | export default _default;

### 📷 复现步骤

正常引入 import ProTable from '@ant-design/pro-table';

### 🏞 可正常使用 ProTable组件

不报错

### 💻 复现代码

import ProTable from '@ant-design/pro-table';

### © 版本信息

- ProComponents 版本: [2.16.0]
- Google Chrome 87.0.4280.88（正式版本）

**Comment by chenshuai2144** [comment]
错误日志也不给？

**Comment by im-not-a-programmer** [comment]
不好意思，我确实粘贴了错误日志没有显示出来
TypeScript error in E:/hitcxedu-web_3.0/node_modules/@ant-design/pro-field/lib/index.d.ts(87,1):
Declaration or statement expected.  TS1128

    85 | } & RenderProps;
    86 | export { FieldPercent, FieldIndexColumn, FieldProgress, FieldMoney, FieldDatePicker, FieldRangePicker, FieldCode, FieldTimePicker, FieldText, FieldStatus, FiledSelect, proFieldParsingText, proFieldParsingValueEnumToArray, };numToArray, };
  > 87 | export type { ProFieldValueType };
       | ^
    88 | declare const _default: React.ForwardRefRenderFunction<any, ProFieldPropsType>;
    89 | export default _default;
    90 |

**Comment by chenshuai2144** [comment]
升级一下你的 ts 版本，用了一个 3.8 的新功能

**Comment by im-not-a-programmer** [comment]
问题已经解决，感谢大佬！
