### ISSUE TITLE
🐛[BUG] editTable 使用了 fieldProps 的onChange，导致无法输入数据

### ISSUE THREAD

**Issue by zbl400** [ant-design/pro-components#1304]
### 🐛 bug 描述

使用 protable 中的可编辑表格功能，在 column定义中使用了 fieldProps 的onChange。
导致在输入框中无法输入数据

### 📷 复现步骤

使用ProTable 的 可编辑表格 Demo
增加onChange配置如下：
```
  {
    title: '活动名称',
    dataIndex: 'title',
    fieldProps: {
      onChange: (e) => console.log('onChange', e)
    },
```

### 🏞 期望结果

用户输入正常显示，console日志中输出事件参数

### 💻 复现代码

https://codesandbox.io/s/brave-gareth-mztt6?file=/App.tsx

### © 版本信息

如文档Demo

**Comment by chenshuai2144** [comment]
不能使用 onChange 的，你会覆盖掉默认组件的，尽量用 onValueChange
