### ISSUE TITLE
bordered 参数失效

### ISSUE THREAD

**Issue by im-not-a-programmer** [ant-design/pro-components#1305]
### 🐛 bug 描述

bordered 参数传入组件ProTable 失效

### 🏞 期望结果
bordered=true 时 table 显示边框
![image](https://user-images.githubusercontent.com/32587004/102176844-3c94a080-3edd-11eb-9e8a-41710b56e9d2.png)
![image](https://user-images.githubusercontent.com/32587004/102176867-49b18f80-3edd-11eb-910d-b28d2503f849.png)

### 得到的结果
bordered=true
不显示边框
![image](https://user-images.githubusercontent.com/32587004/102176958-74034d00-3edd-11eb-8a6a-fe30e52aae80.png)

### © 版本信息

- ProComponents 版本: [2.16.0]

**Comment by chenshuai2144** [comment]
这个是新加的 api，要升级到最新的版本

**Comment by im-not-a-programmer** [comment]
ProComponents 已是最新版本 2.16.0
antd 版本为4.7.3 单独使用 antd 组件是支持 bordered=true 参数
