### ISSUE TITLE
🧐[问题]EditableProTable 如何添加多行

### ISSUE THREAD

**Issue by JTenacity** [ant-design/pro-components#1306]
### 🧐 问题描述
EditableProTable当新增的一行不保存时无法继续添加

现在需要多行同时添加一起保存时如何操作

import React, { useState } from 'react';
import { EditableProTable } from '@ant-design/pro-table';
import ProField from '@ant-design/pro-field';
import { ProFormRadio } from '@ant-design/pro-form';
import ProCard from '@ant-design/pro-card';

const waitTime = (time = 100) =>
  new Promise(resolve => {
    setTimeout(() => {
      resolve(true);
    }, time);
  });

const defaultData = [
  {
    id: 624748504,
    title: '活动名称一',
    decs: '这个活动真好玩',
    created_at: '2020-05-26T09:42:56Z',
  },
  {
    id: 624691229,
    title: '活动名称二',
    decs: '这个活动真好玩',
    created_at: '2020-05-26T08:19:22Z',
  },
];
const columns = [
  {
    title: '活动名称',
    dataIndex: 'title',
    formItemProps: {
      rules: [
        {
          required: true,
          message: '此项为必填项',
        },
      ],
    },
    editable: (text, record, index) => index === 1,
    width: '30%',
  },
  {
    title: '描述',
    dataIndex: 'decs',
    fieldProps: (from, { rowKey }) => {
      if (from.getFieldValue([rowKey || '', 'title']) === '不好玩') {
        return {
          disabled: true,
        };
      }

      return {};
    },
  },
  {
    title: '操作',
    valueType: 'option',
    width: 200,
    render: (text, record, _, action) => [
      <a
        key="editable"
        onClick={() => {
          action.startEditable?.(record.id);
        }}
      >
        编辑
      </a>,
    ],
  },
];
export default () => {
  const [editableKeys, setEditableRowKeys] = useState([]);
  const [dataSource, setDataSource] = useState([]);
  const [position, setPosition] = useState('top');
  const [newRecord, setNewRecord] = useState({
    id: (Math.random() * 1000000).toFixed(0),
  });
  return (
    <>
      <EditableProTable
        rowKey="id"
        headerTitle="可编辑表格"
        maxLength={5}
        recordCreatorProps={{
          position,
          record: newRecord,
        }}
        toolBarRender={() => [
          <ProFormRadio.Group
            key="render"
            fieldProps={{
              value: position,
              onChange: e => setPosition(e.target.value),
            }}
            options={[
              {
                label: '添加到顶部',
                value: 'top',
              },
              {
                label: '添加到底部',
                value: 'end',
              },
            ]}
          />,
        ]}
        columns={columns}
        request={async () => ({
          data: defaultData,
          total: 3,
          success: true,
        })}
        value={dataSource}
        onChange={setDataSource}
        editable={{
          editableKeys,
          onSave: async () => {
            await waitTime(2000);
            setNewRecord({
              id: (Math.random() * 1000000).toFixed(0),
            });
          },
          onChange: setEditableRowKeys,
        }}
      />
      <ProCard title="表格数据" headerBordered collapsible defaultCollapsed>
        <ProField
          fieldProps={{
            style: {
              width: '100%',
            },
          }}
          mode="read"
          valueType="jsonCode"
          text={JSON.stringify(dataSource)}
        />
      </ProCard>
    </>
  );
};

**Comment by chenshuai2144** [comment]
这样
```
  editable={{
        type: 'multiple',
      }}
```

**Comment by JTenacity** [comment]
@chenshuai2144 试了这样可以编辑多行，我添加一行，如果不保存，是不能再添加的

**Comment by chenshuai2144** [comment]
添加行还不支持多行 太复杂了 你有兴趣实现吗？
或者hack一点你插入一个空的数据

**Comment by JTenacity** [comment]
@chenshuai2144 我其实对EditableProTable表格编辑时，鼠标移入才显示rules校验后错误信息比较好奇，help设置为空让输入框下方不显示，那个错误信息是怎么获取的，当编辑这个字段的时候我发现form. getFieldError并取不到错误信息

**Comment by chenshuai2144** [comment]
用了一个不对外的api你可以去看源码
