### ISSUE TITLE
🐛[BUG] ProList pageSize 在request中拿到的pagesize始终是20   

### ISSUE THREAD

**Issue by leesama** [ant-design/pro-components#1307]

**Comment by zhangheng0317** [comment]
我遇到了和你相同的问题,pagesize始终为20,并且total没有生效,分页失效
![20201222100824](https://user-images.githubusercontent.com/76459860/102842323-abc04680-4441-11eb-941e-0d465b30b239.png)
![20201222100944](https://user-images.githubusercontent.com/76459860/102842325-ac58dd00-4441-11eb-83aa-9b89897e7a52.png)
![20201222101015](https://user-images.githubusercontent.com/76459860/102842328-acf17380-4441-11eb-874f-2246f0244b93.png)
![20201222101137](https://user-images.githubusercontent.com/76459860/102842330-ad8a0a00-4441-11eb-867c-bf3621e31fc6.png)

**Comment by leesama** [comment]
我已经换成普通list了😂

**Comment by chhpt-blog** [comment]
1.2.5 版本中仍然存在这个问题
