### ISSUE TITLE
pro-list actionRef属性🧐[问题]

### ISSUE THREAD

**Issue by o-shoushouya** [ant-design/pro-components#1308]
### 🧐 问题描述

请问pro-list没有像table那样的actionRef属性吗？

**Comment by chenshuai2144** [comment]
有的 一抹一样

**Comment by o-shoushouya** [comment]
> 有的 一抹一样

```
<ProList<ContentTableListItem>
          actionRef={actionRef}
/>
```
类型“IntrinsicAttributes & ProListProps<ContentTableListItem, {}>”上不存在属性“actionRef”

可是我这样写报错说没有这个属性，对不起我刚开始学着做前端可能问了个蠢问题，给您添麻烦了qaq，另外目前我的prolist版本是1.1.10
![image](https://user-images.githubusercontent.com/48269451/102192876-4f679f00-3ef6-11eb-99a3-90e0b2a62ca5.png)

**Comment by chenshuai2144** [comment]
可能类型没写上去你先用

**Comment by o-shoushouya** [comment]
> 可能类型没写上去你先用

嗯嗯好的 谢谢您
