### ISSUE TITLE
🧐[问题] ProComponents border 参数 不生效

### ISSUE THREAD

**Issue by im-not-a-programmer** [ant-design/pro-components#1310]
### 🧐 问题描述
ProTable border=true 时不显示表格边框

### 🚑 其他信息

ProComponents 已是最新版本 2.16.0
antd 版本为4.7.3 单独使用 antd 组件是支持 bordered=true 参数

看了 ProComponent Table 源码 border=true 的参数作用在了 Card 组件上，请问 table 的 border 参数还会迭代吗？如果要迭代 请问是什么时候？

**Comment by chenshuai2144** [comment]
2.16 是可以生效的，生效不了的来个复现

**Comment by im-not-a-programmer** [comment]
我可能没有描述清楚，是Table 组件 边框不生效。
目前生效的是 Card 组件。
同时 源码里面 table 组件也是没有接收 bordered这个参数的

复现
<ProTable bordered={true}  />
