### ISSUE TITLE
🐛[BUG]ProForm的文档错误

### ISSUE THREAD

**Issue by VittorioYan** [ant-design/pro-components#1315]
### 🐛 bug 描述

DrawerForm的文档，这里应该是Drawer的属性
![image](https://user-images.githubusercontent.com/18114631/102196277-a7080980-3efa-11eb-8796-d3bd5899904f.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个pr帮忙改进一下把
