### ISSUE TITLE
🐛下拉列表请求远程数据来填充，页面初始化调用多次

### ISSUE THREAD

**Issue by LMZ1997** [ant-design/pro-components#1320]
### 🐛 bug 描述

  如下代码，下拉列表筛选框 “财年” 需要调用异步接口填充，页面初始化后发现多次调用了fn中的接口 

### 💻 复现代码

  const getYear = async ()=>{
    return fn().then((res:any)=>{
      return [ { label:"张三",value:"1"},{ label:"李四",value:"2" } ]
    })
  }
  const columns: ProColumns<TargetSetting>[] = [
    {
      title: '财年',
      dataIndex: 'year',
      width: 140,
      valueType: 'select',
      request: getYear,
      params: {key:"year"},
    },
]

### 如果把getYear写在useEffect中的话，是只请求了一次接口，但是下拉列表select中就没有数据了
![image](https://user-images.githubusercontent.com/37367543/102211293-5f8b7880-3f0e-11eb-968f-6eb739996f86.png)

**Comment by chenshuai2144** [comment]
试试options

**Comment by LMZ1997** [comment]
基于上述，我发现用request+params填充下拉列表，若表格数据dataSource中没有对应那列("year")的数据，就不会出现多次触发request的情况，不知此场景您是否测试过

**Comment by LMZ1997** [comment]
> 试试options
> https://procomponents.ant.design/components/field#%E8%BF%9C%E7%A8%8B%E6%95%B0%E6%8D%AE
> 
> 这里有个指引可以看看

**Comment by LMZ1997** [comment]
> 试试options
> https://procomponents.ant.design/components/field#%E8%BF%9C%E7%A8%8B%E6%95%B0%E6%8D%AE
> 
> 这里有个指引可以看看
基于上述，我发现用request+params填充下拉列表，若表格数据dataSource中没有对应那列("year")的数据，就不会出现多次触发request的情况，反过来说dataSoure有多少条数据，就相应触发了多少次request。不知此场景您是否测试过

**Comment by chenshuai2144** [comment]
request 在 ProForm 中用起来更方便一点，你可以试试 options

> 基于上述，我发现用request+params填充下拉列表，若表格数据dataSource中没有对应那列("year")的数据，就不会出现多次触发request的情况，反过来说dataSoure有多少条数据，就相应触发了多少次request。不知此场景您是否测试过

这里是用 dataIndex 来当 key 缓存的，如果 dataIndex 重复就会出现这个问题
