### ISSUE TITLE
🧐[问题]ProFormSelect配置模糊搜索无效

### ISSUE THREAD

**Issue by storageChu** [ant-design/pro-components#1321]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/20637438/102218464-efcebb00-3f18-11eb-912a-f5cc45bb04bc.png)
![image](https://user-images.githubusercontent.com/20637438/102218486-fa895000-3f18-11eb-81eb-b40c6567a4ca.png)

![image](https://user-images.githubusercontent.com/20637438/102218314-bb5aff00-3f18-11eb-918b-f3c4240e20e6.png)
如图配置了搜索规则，想让select可按label进行筛选，配置后无作用，不知道哪里没有配对

**Comment by chenshuai2144** [comment]
用fieldProps 配置原有组件的原来的props。
![image](https://user-images.githubusercontent.com/8186664/102227621-bf8d1980-3f24-11eb-81dc-9692b20f7ce2.png)

**Comment by chenshuai2144** [comment]
刚做了一个业务，是可以实现的

**Comment by wangzi1204** [comment]
> 刚做了一个业务，是可以实现的

 请问是如何实现的呢，同样有根据label模糊查询的需求

**Comment by CrassusX** [comment]
@wangzi1204 
我这样查询就可以了
fieldProps={{
                    optionFilterProp: 'children',
                    filterOption: (input, option) => {
                        return option.label.includes(input)
                    },
                }}

![image](https://user-images.githubusercontent.com/2889738/112963021-8bf39980-9179-11eb-9d20-889689b0c041.png)
