### ISSUE TITLE
🧐[问题]StepsForm auto reset to step one onCancel

### ISSUE THREAD

**Issue by storageChu** [ant-design/pro-components#1324]
### 🧐 问题描述
关闭窗口后再次打开时  仍保留了之前关闭时的step，如何让我关闭窗口时可重置到第一步呢？

### 💻 示例代码
https://procomponents.ant.design/components/form/#%E5%88%86%E6%AD%A5%E8%A1%A8%E5%8D%95-%E4%B8%8E-model-%E9%85%8D%E5%90%88%E4%BD%BF%E7%94%A8

官方示例中就有类似情况

**Comment by storageChu** [comment]
再注明下，同时也重置清空form表单的值

**Comment by chenshuai2144** [comment]
fixed in 
![image](https://user-images.githubusercontent.com/8186664/107150894-01719380-699b-11eb-8c72-41cfaead03c1.png)

**Comment by bhh123** [comment]
![image](https://user-images.githubusercontent.com/31943761/140952746-ddd00225-c3ac-4e64-a825-8c6b2065eb65.png)
我使用的是把modal放在StepsForm外面，设置 footer={false}
