### ISSUE TITLE
🐛[BUG]  pro-table 设置 pagination pageSize 问题

### ISSUE THREAD

**Issue by 18613109040** [ant-design/pro-components#1326]
### 💻 复现代码
useFetchData.tsx 中 reset 方法中 setPageInfo 方法 

- [ ] pageSize 未设置 options?.pageSize

reset: () => {
      setPageInfo({
        page: options?.defaultCurrent || 1,
        total: 0,
        pageSize: options?.pageSize || options?.defaultPageSize || 10
      });
    }
<img width="1156" alt="1608097865289_C6B8869C-EEA9-4739-BB63-F00DF08ADCDD" src="https://user-images.githubusercontent.com/18108674/102310840-ba70ae80-3fa6-11eb-8fc8-1c4cdad223ec.png">

**Comment by chenshuai2144** [comment]
看看这里的代码

https://procomponents.ant.design/components/table#%E6%9F%A5%E8%AF%A2%E8%A1%A8%E6%A0%BC

都是用的 pageSize

**Comment by ccloveak** [comment]
你用useState存一下pageSize（默认值写10？） ，直接放到pageSize这个位置 `pageSize: pageSize` ， 在onChange事件里去设置pageSize

**Comment by chenshuai2144** [comment]
懂你意思了，你觉得这个 pageSize  的 reset 行为不合理是吗？

**Comment by chenshuai2144** [comment]
fixed
