### ISSUE TITLE
🐛[BUG]pro-layout 使用postMenuData={() => menuData} 来获取服务器菜单，对于hideInMenu: true的菜单没有隐藏

### ISSUE THREAD

**Issue by kiwikaki** [ant-design/pro-components#1327]
### 🐛 bug 描述

pro-layout 使用postMenuData={() => menuData} 来获取服务器菜单，对于hideInMenu: true的菜单没有隐藏

### 📷 复现步骤

设置一个菜单.js 对某一个菜单设置hideInMenu: true
BasicLayout.jsx 通过postMenuData={() => menuData}  获取菜单

### © 版本信息

- ProComponents 版本: [pro-layou :6.6.2]

**Comment by chenshuai2144** [comment]
@kiwikaki  用 menuDataRender， postMenuData 里面的数据不做任何处理就会处理到 layout上，用来实现 layout 不支持的功能

**Comment by kiwikaki** [comment]
明白了
