### ISSUE TITLE
👑 [需求] 能不能在ProTable中追加也给可以编辑单元格的例子

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#1329]
### 🥰 需求描述

能不能在ProTable中追加也给可以编辑单元格的例子

在项目中编辑单元格的场景会经常用，

* 例如这个图，更改排序：https://gitlab.redhtc.com/antd/editTable1.png
* 例如这个图，更改佣金：https://gitlab.redhtc.com/antd/editTable2.png

[antDesign的文档有类似的例子](https://ant.design/components/table-cn/#components-table-demo-edit-cell)

![editTable1](https://user-images.githubusercontent.com/34436863/102352688-09d4d000-3fe3-11eb-8b3c-92853ada9402.png)
![editTable2](https://user-images.githubusercontent.com/34436863/102352710-12c5a180-3fe3-11eb-9512-be04e2c405cd.png)

**Comment by chenshuai2144** [comment]
意义好像不大，用 editor:false 来控制的
