### ISSUE TITLE
🐛[BUG] ProProvider 组件源码 intlMap 拼写错误 导致日语国际化 ja-JP 设置不生效 

### ISSUE THREAD

**Issue by lkspc** [ant-design/pro-components#1330]
查看源代码发现，是 pro-provider 的 intlMap 拼写错了:
https://github.com/ant-design/pro-components/blob/27ed75a6bf25d63179a265bd981fe4c663d119c8/packages/provider/src/index.tsx#L75

希望尽快能够发版修复。

**Comment by chenshuai2144** [comment]
这个是个日本小哥写的，你要不要看看他的 pr，我也搞不懂日本的叫什么

**Comment by lkspc** [comment]
> 这个是个日本小哥写的，你要不要看看他的 pr，我也搞不懂日本的叫什么

日语应该就是 ja-JP 吧，这里写成 js-JP 去了，antd 那边也用的 ja-JP，至少要一致吧，不然我 antd 那边是日语，pro 这边是中文。

**Comment by chenshuai2144** [comment]
你提个 pr 改一下，顺便@一下小哥。是不是他笔误了

**Comment by lkspc** [comment]
是哪个小哥？跟我们这边的日语PM确认了下就是 ja-JP。要不你们改吧，我这个 clone 下来又要搞半天，工作有点忙，见谅。

**Comment by chenshuai2144** [comment]
不用那么麻烦的，你可以找到这个文件右上角有个编辑，点一下就能在线修改
修改提个 pr 我帮你@小哥

**Comment by lkspc** [comment]
好了，尽快处理下，谢谢

**Comment by lkspc** [comment]
#1331
