### ISSUE TITLE
🐛[BUG] 将**protable**使用在乾坤(**qiankun**)微应用中，使用**ellipsis: true**后，会造成**tooltip** 闪跳一下

### ISSUE THREAD

**Issue by BigFaceMaster** [ant-design/pro-components#1332]
### 🐛 bug 描述
将**protable**使用在乾坤(**qiankun**)微应用中，使用**ellipsis: true**后，会造成**tooltip** 闪跳一下，从上方然后跳动到正确位置，单独在微应用中使用，无此问题；根据分析是**Tooltip**的位置计算原因，建议将**getPopupContainer** 能够传入**LabelIconTip**组件中，来实现此问题，或者 如全屏时一样

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
LabelIconTip  是支持  getPopupContainer  的，估计是 css 的影响问题吧

不过这个问题好眼熟，好像哪个 antd 的版本见过

**Comment by BigFaceMaster** [comment]
应该是没有传入的
在**packages/table/src/utils.tsx**第**219**行 可以看出
```tsx
/**
 * render title
 * @description 增加了 icon 的功能
 * @param item
 */
export const renderColumnsTitle = (item: ProColumns<any>) => {
  const { title } = item;
  if (title && typeof title === 'function') {
    return title(item, 'table', <LabelIconTip label={title} tooltip={item.tooltip || item.tip} />);
  }
  return <LabelIconTip label={title} tooltip={item.tooltip || item.tip} />;
};

```

![image](https://user-images.githubusercontent.com/15710933/102707810-202ba600-42d9-11eb-9c80-a9f062c63d7d.png)

然而 只有在`table.tsx`中才有`getPopupContainer`

在`packages/table/src/Table.tsx` 的592行

```tsx
// 如果不需要的全屏，ConfigProvider 没有意义
  if (!options || !options?.fullScreen) {
    return proTableDom;
  }
  return (
    <ConfigProvider
      getPopupContainer={() => ((rootRef.current || document.body) as any) as HTMLElement}
    >
      {proTableDom}
    </ConfigProvider>
  );
```

![image](https://user-images.githubusercontent.com/15710933/102708146-b660cb80-42db-11eb-9d47-87f1598e1c58.png)

**Comment by chenshuai2144** [comment]
去 qiankun 去问吧，pro去掉了这个代码
