### ISSUE TITLE
🐛[BUG]ProTable设置pagesize后，点查询或者重置时，返回的pagesize总是默认值

### ISSUE THREAD

**Issue by pyang30** [ant-design/pro-components#1335]
### 🐛 bug 描述

ProTable设置pagesize后，点查询或者重置时，返回的pagesize总是默认值

### 📷 复现步骤

用官网例子举例
https://procomponents.ant.design/components/table

拿第一个例子看，pagesize默认值是5，选择10，然后点最上面的查询或者重置，pagesize会变回5。即，pagesize不会保存。

### 🏞 期望结果

我拿之前的老版本2.9.5测试，是可以保存pagesize的，不知道从哪个版本开始不保存了。

经测试 2.11.3是正确的，2.12以后就不能保存pagesize了

### 💻 复现代码

https://procomponents.ant.design/components/table

### © 版本信息

@ant-design/pro-table@2.16.1

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
看下一下代码？
