### ISSUE TITLE
🐛[BUG] ProTable 执行actionRef.current. reloadAndRest()方法不会清空表单的值

### ISSUE THREAD

**Issue by xccxcs** [ant-design/pro-components#1336]
### 🐛 bug 描述
ProTable 执行actionRef.current. reloadAndRest()方法不会清空表单的值

### 📷 复现步骤

在表单中输入值 点击查询 然后再点击测试按钮 F12中接口的参数还是带着表单中的值

### 💻 复现代码
https://codesandbox.io/s/suspicious-meadow-458ir

### © 版本信息

    "react": "16.14.0",
    "react-dom": ">=16.9.0",
    "antd": "4.9.2",
    "@ant-design/icons": "4.3.0",
    "@ant-design/pro-table": "2.16.2", 本地开发出现的版本是2.15.1
    "umi-request": "1.3.5"

**Comment by ccloveak** [comment]
`actionRef.current. reloadAndRest()` 是对整个pro-table的操作。。。为了实现你的需求，你可能得看一下 `renderFormItem`这个api。

**Comment by xccxcs** [comment]
> `actionRef.current. reloadAndRest()`[pro 表][，]`renderFormItem`

我是想回到第一页并清空search表单请求 之前是在一个关闭的issuse中提到说用这个方法 [#885](https://github.com/ant-design/pro-components/issues/885) 在我自己尝试过程中发现没有重置 所以提出这个来

**Comment by chenshuai2144** [comment]
只关了 table 的事情，没有管 form 的是应该支持一下

**Comment by z-lionel** [comment]
> 只关了 table 的事情，没有管 form 的是应该支持一下

现在是还没修复吗？目前更新到最新版的，使用 reloadAndRest，还是没有清空搜索框的内容。

现在遇到的问题的是，在顶部做了个tab切换请求列表的数据，只修改了传参，但同时想清空搜索框之前填的内容，
现在有没有什么方法能清空表单的数据？

**Comment by chenshuai2144** [comment]
`formRef.resetFileds()`  可以用 formRef 来操作
