### ISSUE TITLE
ProFormRadio.Group如何实现复杂的单选组，并且垂直排列？

### ISSUE THREAD

**Issue by fengstorm888** [ant-design/pro-components#1338]
需求是有一组单选，垂直排列，每一个单选按钮后面又有自己对应的其他组件，请问这种应该怎么实现啊？还望指教！

**Comment by fengstorm888** [comment]
而且layout="vertical"似乎并没有效果

**Comment by chenshuai2144** [comment]
看了一下还挺不好实现的，单纯的 render 会导致值丢失。
你有好想法吗？
