### ISSUE TITLE
🐛[BUG] React does not recognize the `colSize` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `colsize` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#1339]
React does not recognize the `colSize` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `colsize` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

![image](https://user-images.githubusercontent.com/30397655/102571813-7526bb00-4125-11eb-91b1-2cc957c2de30.png)

不想说话了，升个版本，就出个这种问题，每次还都是我提交这种BUG。

**Comment by ccloveak** [comment]
* +1 问题不大 我也正在找没有warning的protable版本。。。
![image](https://user-images.githubusercontent.com/38686314/102582391-d6f71d00-4145-11eb-8b4a-f9cec5e7f95d.png)

**Comment by chenshuai2144** [comment]
测试用例测试不来这种 warning，被你人肉发现了

**Comment by chenshuai2144** [comment]
我复现不了这个问题，怎么能复现以下

**Comment by ccloveak** [comment]
@chenshuai2144  
* https://github.com/ccloveak/reportissue/tree/main/memberstable  这个应该就能复现这个warning
* 项目之前用的是2.6.3  现在是2.9.10（中途版本不需要太大的变更） 目前正计划更新protable的版本 。现在在抽离其他业务逻辑，找个没有报错的protable版本。

**Comment by chenshuai2144** [comment]
不行诶，是一定要用 cra 吗？

**Comment by ccloveak** [comment]
这么说我突然意识到可能问题出在项目搭建上了。。。我是按照`https://ant.design/docs/react/use-in-typescript-cn` 的顺序搭建的sample。。你们搭项目框架是怎么搭的？

**Comment by chenshuai2144** [comment]
-  yarn  create umi

然后选 v5 分支

**Comment by changjunhao** [comment]
renderFormItem 中使用 Cascader 会出现这个警告
![Uploading 截屏2020-12-22 上午11.22.07.png…]()

**Comment by bluescurry** [comment]
使用 renderFormItem 属性自定义表单项就可以复现，希望尽快解决下吧
`
{
      title: '城市',
      dataIndex: 'city_name',
      order: 2,
      renderFormItem: (_, { type, defaultRender, ...rest }) => {
        if (type === 'form') {
          return null;
        }
        return <Input {...rest} placeholder="请选择城市" />;
      }
    },
`

**Comment by chenshuai2144** [comment]
找到了问题，今天发版本

**Comment by ccloveak** [comment]
![image](https://user-images.githubusercontent.com/38686314/103119403-88520180-46b6-11eb-83db-7168f45638d9.png)
喜大普奔
