### ISSUE TITLE
🐛[BUG] ProTable -> Editable -> ActionRender

### ISSUE THREAD

**Issue by yanglu758** [ant-design/pro-components#1343]
### 🐛 bug 描述

我想要用ProTable里的editable，让row可以被编辑。我的网站是全英文的，是给英文客户开发的，所以不能有中文出现。但是如图所示，编辑按钮都是中文的。我看文档里的Editable属性里有一个ActionRender，但是好像ActionRender不能覆盖编辑按钮的ReactNode。如果ActionRender不能覆盖，还有什么方法可以把他们变成英文的呢？

### 📷 复现步骤

用一下ProTable -> editable -> ActionRender

### 🏞 期望结果

覆盖三个编辑按钮让他们变成英文。

### 💻 复现代码

`<ProTable editable={{ actionRender: () => [<a>Confirm</a>,<a>Cancel</a>]}}/>`

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![1](https://user-images.githubusercontent.com/12844206/102577225-c21d8800-414b-11eb-84c8-bc4e4a7806f4.JPG)

**Comment by ccloveak** [comment]
巧了，我的网站是全日文的、也不能有中文出现，你看看locale能满足你的需求么

**Comment by yang07ly** [comment]
我在`config/config.ts`里的locale里已经设置：
```
locale: {
  default: 'en-us'
}
```
但还是会啊。请问你是在哪里设置locale的？

**Comment by chenshuai2144** [comment]
这个还不支持国际化，你要不要来个 pr？

**Comment by ccloveak** [comment]
好心人做个日语版的吧😘😘😘

**Comment by hellow7758521** [comment]
我也遇到上述问题了，Pro-Table版本号 2.16.2，但是演示中的是没问题的。

**Comment by ccloveak** [comment]
> 我在`config/config.ts`里的locale里已经设置：
> 
> ```
> locale: {
>   default: 'en-US'
> }
> ```
> 
> 但还是会啊。请问你是在哪里设置locale的？

你会发现 locale 无处不在 你在具体组件那一层去单独找 locale 试试呢。。。。我   也是找找找 找到了 ` 20 /page`这个的 配置 藏得太深了

**Comment by yang07ly** [comment]
@chenshuai2144 所以ActionRender也是有bug吧，因为预期效果应该是覆盖ReactNode才对啊

**Comment by yanglu758** [comment]
ActionRender可以用了，但是editabletable的国际化好像在 pro-table@2.19.1还不支持，三个action的按钮还是中文的

**Comment by chenshuai2144** [comment]
@yanglu758  来个 pr 吧，我最近一直休假估计也没空管

**Comment by yanglu758** [comment]
@chenshuai2144 我做了一个PR #1491 ，你看看吧
