### ISSUE TITLE
🐛[BUG] proTable中columns中显示定义search:true js报错:search.transform is not a function

### ISSUE THREAD

**Issue by youngclean** [ant-design/pro-components#1345]
### 🐛 bug 描述

因为需求，columns中某列在情况1下要在表单中显示，在情况2下又不要显示，所以search的值会变，当显示设为 true时，js报错了，导致查询不了
[
search.transform is not a function
....
]
### 💻 复现代码
[示例](https://codesandbox.io/s/youthful-mayer-vlcyw)

### © 版本信息

- ProTable 版本: 2.16.0
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![647E61ED-5FF5-40B2-AA64-3677EC4CCBC4](https://user-images.githubusercontent.com/2239335/102583374-8f6d9280-413f-11eb-96f0-bacbb1132128.png)

**Comment by chenshuai2144** [comment]
`search? search?undefind:false`

这样写，不要给 true

**Comment by wulinjie122** [comment]
> `search? search?undefind:false`
> 
> 这样写，不要给 true

意思是，先判断有没有search属性，然后有的话给undefined，没有的话给false?

**Comment by wulinjie122** [comment]
> `search? search?undefind:false`
> 
> 这样写，不要给 true

我估计这样改，对我的源码要改很多地方了，现在项目中大面积使用pro-table，一改一大片。

**Comment by chenshuai2144** [comment]
那就继续用 hide 好了，这个 api 很久都会一直存在

**Comment by youngclean** [comment]
我只想说 那个判断逻辑有问题，正常设置一个布尔类型的变量，不是false就是true，undefined很少用到

**Comment by chenshuai2144** [comment]
undefined 代表不存在，false 代表关掉，不过新版兼容了一下如果是 true，自动转化为 undefined，更新之后即可生效
