### ISSUE TITLE
关于ProForm的一些疑惑

### ISSUE THREAD

**Issue by my9988** [ant-design/pro-components#1353]
@chenshuai2144 本以为加了Pro是更高级，但看文档也看不懂，咨询一下以下疑惑：

1.  是不是在ProForm里只能用Pro组件，否则提交时参数里没有值？比如用checkbox  代替ProFormCheckbox

2.关于ProFormCheckBox ,文档里说和checkbox相同，我就怕这样的语言。比如checkbox可以加checked={true},但我这么加就没啥作用，还有layout,我估计是我加错了，可是我从DEMO及文档里都获取不到相关信息，只有个<ProFormCheckbox.Group ，q请给个正确的写法，就是想用ProFormCheckBox 有初始值和 水平显示
![image](https://user-images.githubusercontent.com/17469220/102686604-c8286d00-420e-11eb-94c6-2ff9b02d6967.png)

谢谢！

**Comment by chenshuai2144** [comment]
ProForm 是 form，所以必须要用Form的方式，默认值要用 initiaValues。

如果要自定义的组件需要用 Form.Item 包裹。  ProForm 没有魔法。试试 Form 上面做了点预设

**Comment by my9988** [comment]
还是没明白ProFormCheckbox label 想水平布局怎么配置，先放放这个问题了。

**Comment by Aneyetosee** [comment]
layout="horizontal"
![image](https://user-images.githubusercontent.com/48241433/103761905-652e3700-5052-11eb-9a5e-7520b282d2ae.png)
