### ISSUE TITLE
modalForm没有验证

### ISSUE THREAD

**Issue by mtiger95** [ant-design/pro-components#1354]
{
      label: '类型名称',
      name: 'typeName',
      type: 'text',
      labelCol: { span: 3 },
      fieldProps: {
        rules: [
          {
            required: true,
            message: '此项为必填项',
          },
        ],
      }
    }, 

 const onModalFinish = async values => {
    let result = await form.validateFields();
    let hasEmptyField = Object.keys(result).some(k => !result[k] )
    if(hasEmptyField){
      return false;
    }
    debugger
    onModalOk && onModalOk(values);
    resetStatus();
    return Promise.resolve();
  }

点击modalForm的确认按钮，不能做表单验证，自己用form ref 做也不能触发。希望加上表单验证。

**Comment by chenshuai2144** [comment]
用 onFinsh ，如果通不过验证 onFinsh 是不会触发的的
