### ISSUE TITLE
🐛[BUG]ProFormCaptcha没有实现对手机号的校验，手机号未填写也能触发获取验证码倒计时。

### ISSUE THREAD

**Issue by qingmumao** [ant-design/pro-components#1356]
### 🐛 bug 描述

ProFormCaptcha没有实现对手机号的校验，手机号未填写也能触发获取验证码倒计时。

### 🏞 期望结果
再没有填写手机号的情况下点击获取验证码提示输入手机号。或者触发表单的格式校验。通过则继续，不通过则停止触发获取验证码和倒计时

**Comment by ccloveak** [comment]
看一下你的rules是咋写的。。。

**Comment by qingmumao** [comment]
{type === 'mobile' && (
              <>
                <ProFormText
                  fieldProps={{
                    size: 'large',
                    prefix: <MobileTwoTone className={styles.prefixIcon} />,
                  }}
                  name="mobile"
                  placeholder={intl.formatMessage({
                    id: 'pages.login.phoneNumber.placeholder',
                    defaultMessage: '请输入手机号',
                  })}
                  rules={[
                    {
                      required: true,
                      message: (
                        <FormattedMessage
                          id="pages.login.phoneNumber.required"
                          defaultMessage="请输入手机号！"
                        />
                      ),
                    },
                    {
                      pattern: /^1\d{10}$/,
                      message: (
                        <FormattedMessage
                          id="pages.login.phoneNumber.invalid"
                          defaultMessage="手机号格式错误！"
                        />
                      ),
                    },
                  ]}
                />
                <ProFormCaptcha
                  fieldProps={{
                    size: 'large',
                    prefix: <MailTwoTone className={styles.prefixIcon} />,
                    
                  }}
                  captchaProps={{
                    size: 'large'           
                  }}
                  placeholder={intl.formatMessage({
                    id: 'pages.login.captcha.placeholder',
                    defaultMessage: '请输入验证码',
                  })}
                  captchaTextRender={(timing, count) => timing
                      ? `${count} ${intl.formatMessage({
                          id: 'pages.getCaptchaSecondText',
                          defaultMessage: '获取验证码',
                        })}`
                      : intl.formatMessage({
                          id: 'pages.login.phoneLogin.getVerificationCode',
                          defaultMessage: '获取验证码',
                        })
                      
                  }
                  name="verifyCode"
                  rules={[
                    {
                      required: true,
                      message: (
                        <FormattedMessage
                          id="pages.login.captcha.required"
                          defaultMessage="请输入验证码！"
                        />
                      ),
                    },
                  ]}
                  onGetCaptcha={async (mobile) => {
                    if(!/^[1-9]\d{10}$/.test(mobile)){
                      message.warning('请输入正确的手机号');
                      return 
                    }
                    await post('base.smsSend', {
                      mobile,
                      template: 'login'
                    });
                    message.success('验证码已发送，请注意查收');
                  }}
                  
                />
              </>
            )}

**Comment by qingmumao** [comment]
message里的被github过滤掉了。基本是按ant-design-pro的登录表单。
这是pro-form的源码
var getFieldValue = _ref2.getFieldValue;
    return /*#__PURE__*/_react.default.createElement("div", {
      style: _objectSpread(_objectSpread({}, fieldProps === null || fieldProps === void 0 ? void 0 : fieldProps.style), {}, {
        display: 'flex',
        alignItems: 'center'
      }),
      ref: ref
    }, /*#__PURE__*/_react.default.createElement(_input.default, _extends({}, fieldProps, {
      style: {
        flex: 1,
        transition: 'width .3s',
        marginRight: 8
      },
      value: value,
      onChange: onChange
    })), /*#__PURE__*/_react.default.createElement(_button.default, _extends({
      style: {
        display: 'block'
      },
      disabled: timing,
      loading: loading
    }, captchaProps, {
      onClick: function onClick() {
          var mobile = getFieldValue('mobile');
          onGetCaptcha(mobile);
      }
    }), captchaTextRender(timing, count)));
  });
是否应该改成
onClick: function onClick() {
        _ref2.validateFields(['mobile'])
        .then(()=> {
          var mobile = getFieldValue('mobile');
          onGetCaptcha(mobile);
        })
        
      }
增加促发获取验证码前校验mobile

**Comment by chenshuai2144** [comment]
来个pr?
