### ISSUE TITLE
[BUG]自定义Tree组件, 传入value值无效, 一直是undefined

### ISSUE THREAD

**Issue by LeeeMooo** [ant-design/pro-components#1359]
### 🐛 bug 描述
formitem里面tree无法获取到value值,需要自定义组件
https://github.com/ant-design/pro-components/issues/1149#issuecomment-736199917

### 🏞 期望结果
获取到value值

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![2020-12-21 10-17-51屏幕截图](https://user-images.githubusercontent.com/23691333/102732499-dc3aae80-4375-11eb-9b85-b6ade2e5873e.png)

![2020-12-21 10-18-54屏幕截图](https://user-images.githubusercontent.com/23691333/102732549-f3799c00-4375-11eb-868a-b9cbef755d86.png)
这里value一直是undefined, data是有值的

**Comment by chenshuai2144** [comment]
你不能覆盖 form 的值，value 和 onchange 是默认注入的

![image](https://user-images.githubusercontent.com/8186664/103058976-af3d0480-45de-11eb-8dfd-a72c9c4533b0.png)
