### ISSUE TITLE
🐛[BUG]Mix 和SplitMenus下，小屏幕下主菜单不见了

### ISSUE THREAD

**Issue by onecmd** [ant-design/pro-components#136]
### 🐛 bug 描述
Mix 和SplitMenus下，小屏幕下主菜单不见了，点击缩略图只列出子菜单，这样就不能导航到其它主菜单了
![image](https://user-images.githubusercontent.com/3389081/89730886-5af11800-da75-11ea-86f8-e4c00711781c.png)

### 📷 复现步骤

https://preview.pro.ant.design/dashboard/analysis?navTheme=light&primaryColor=daybreak&layout=mix&splitMenus=true
把浏览器缩小

### 🏞 期望结果
![image](https://user-images.githubusercontent.com/3389081/89730847-12395f00-da75-11ea-9d07-13e63a04bb9c.png)

**Comment by chenshuai2144** [comment]
看起来好像没问题
![image](https://user-images.githubusercontent.com/8186664/89749288-a220ec80-daf9-11ea-83b2-77bcd789b265.png)

**Comment by onecmd** [comment]
再缩小一些，左边菜单就会消失，顶部的也会，如我的第一张图所示。我用的是chrome浏览器，版本：Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by onecmd** [comment]
但我在苹果手机上访问，点log旁边的按钮会列出完整的菜单，但是我用浏览器缩小成很小的时候，点log旁边的按钮列出的是子菜单的：
![image](https://user-images.githubusercontent.com/3389081/89765375-c516c500-db28-11ea-9397-60bbb218c9b7.png)
