### ISSUE TITLE
🐛[BUG] layout菜单和头部导航高亮重复点击

### ISSUE THREAD

**Issue by RIPm** [ant-design/pro-components#1360]
### 🐛 bug 描述
菜单和头部导航高亮时点击，会加入路由栈。
导致路由不断叠加，退回的时候要点到叠加次数为止

### 🏞 期望结果

高亮重复点击，不加入路由栈

### © 版本信息

- ProComponents 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by mtiger95** [comment]
我们现在开发中的ERP项目用的antd 4.9.1 的版本也有这个问题。
不过一般不会去点浏览器的返回吧，自己在页面上做返回按钮，直接跳目标路由。

**Comment by RIPm** [comment]
> 我们现在开发中的ERP项目用的antd 4.9.1 的版本也有这个问题。
> 不过一般不会去点浏览器的返回吧，自己在页面上做返回按钮，直接跳目标路由。

也少人会重复点击，但用户怎么使用就很难说了

**Comment by chenshuai2144** [comment]
从业务上解决了，pro 中加了重复判断
