### ISSUE TITLE
🧐[问题]ProTable search span设置为2 用colSize来控制form中的宽度 然后 搜索和重置按钮会超宽

### ISSUE THREAD

**Issue by xccxcs** [ant-design/pro-components#1364]
### 🧐 问题描述
ProTable search span设置为2 用colSize来控制form中的宽度 然后 搜索和重置按钮会撑开盒子
还有一个问题是设置了colSize后 renderFormItem 后colSize失效 当时renderFormItem的元素会被包在col-{span}的里面

### 💻 示例代码
https://codesandbox.io/s/ecstatic-curie-rrz7u?file=/App.tsx

**Comment by xccxcs** [comment]
我的临时方案是用了设置span为8 colSize 为 3/4这种去解决

**Comment by xccxcs** [comment]
有没有人来说一下

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/103059396-f37cd480-45df-11eb-87fb-2a995942c734.png)


你这个排版搞得太狠了，每个 col 都非常小。默认是 8，你最少也应该使用 4 或者 6

**Comment by xccxcs** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/103059396-f37cd480-45df-11eb-87fb-2a995942c734.png)
> 
> 你这个排版搞得太狠了，每个 col 都非常小。默认是 8，你最少也应该使用 4 或者 6

我现在的解决方法是span 设置为8 然后 colSize设置为3/4

**Comment by chenshuai2144** [comment]
renderFormItem 的 item 自定义了，你可以人肉设置上去试试

**Comment by chenshuai2144** [comment]
span不能设置为2 ，因为 actions 的 span 不能设置，你可以设置 0.x 的 colSize
