### ISSUE TITLE
🧐[问题]ProTable如何添加其它的筛选条件？同时希望添加将重置和查询按钮左浮动挨着最后一个筛选表单的配置项

### ISSUE THREAD

**Issue by mtiger95** [ant-design/pro-components#1369]
### 🧐 问题描述
🧐[问题1]ProTable的columns中没有设置search为false的都会自动作为表单筛选条件，请问如何再另外加自己其它的筛选条件？

🧐[问题2] 当筛选表单折行后只有一个时，因为屏幕大，重置和查询按钮放最后离的太远，影响操作体验，希望添加一个可将重置和查询按钮左浮动挨着最后一个筛选表单元素的可配置项

![image](https://user-images.githubusercontent.com/23418622/102770306-e208b200-43be-11eb-8fbe-7534856fb1a7.png)

**Comment by chenshuai2144** [comment]
hideIntable 就只显示在 form 中不显示在表单中。


> 🧐[问题2] 当筛选表单折行后只有一个时，因为屏幕大，重置和查询按钮放最后离的太远，影响操作体验，希望添加一个可将重置和查询按钮左浮动挨着最后一个筛选表单元素的可配置项

这个不会实现的， 很少有人这么大的屏幕，而且如果在乎这个应该限制内容区域为 1200，而不是拉这么长

**Comment by mtiger95** [comment]
好的，谢谢回复。
