### ISSUE TITLE
👑 [需求] 强烈建议表格的tableAlertRender加上边框或者给予自定义渲染

### ISSUE THREAD

**Issue by yunuo-tech** [ant-design/pro-components#137]
### 🥰 需求描述

目前的tableAlertRender的默认宽度是100%，并且不能自定义，所以会造成页面很不协调。虽然可以通过一些办法调整一下，但是又会影响到其他地方的样式。比如用Card套用后，100%的问题是解决了，但是搜索和表格中间的空隙又没了。
### 🧐 解决方案

![image](https://user-images.githubusercontent.com/5960864/89746492-7a775780-daec-11ea-8f01-fdb07d4b9476.png)

**Comment by Lnncoco** [comment]
这同意，之前用过一次，发现实际放到页面样式很突兀，而且没选择的时候也始终存在，很吸引注意力分散重点，最后把这条删了

**Comment by WynterDing** [comment]
![image](https://user-images.githubusercontent.com/11213298/89929072-4d858a80-dc3b-11ea-9de0-0cfdcd8523eb.png)

看了下，好像已经修复掉了

**Comment by h389735** [comment]
@chenshuai2144 , 针对样式问题，建议最好不要写在style里面，最近升级发现Pro-Table 的搜索样式又变了， 而且写在style里面，之前写好的样式又失效了，这样不利于样式定制
