### ISSUE TITLE
proTable，在设置了table的size后，toolbar的高度并不能变小👑 [需求]

### ISSUE THREAD

**Issue by HunterHeroHan** [ant-design/pro-components#1375]
### 🥰 需求描述
工具栏和标题能不能同时根据table的尺寸变化宽度以及字号

**Comment by CalmErkai** [comment]
抱歉，表格这边暂时不会给出这个方案。理由：

这是个系统问题，不是单点问题。如果这里调了，那页面中不属于表格的其它组件和区块要不要调（比如同样都是标题，同样都是工具栏）。

不过：未来可能会考虑，如果是紧凑版，整体都会更紧凑，字体更小。

谢谢你的建议
