### ISSUE TITLE
🧐[问题]protable的key报错，批量操作也无法使用，求助

### ISSUE THREAD

**Issue by Veexx** [ant-design/pro-components#1381]
### 💻 示例代码
import { PlusOutlined } from '@ant-design/icons';
import { Button, Divider, message, Input, DatePicker, Image, Checkbox } from 'antd';
import React, { useState, useRef } from 'react';
import { FooterToolbar } from '@ant-design/pro-layout';
import ProTable from '@ant-design/pro-table';
import Wangeditor from '@/components/Wangeditor';
import UploadImg from '@/components/UploadImg';
import CreateForm from '@/components/GlobalForm';
import { queryRule, removeRule, addRule } from './service';

/**
 * 添加节点
 * @param fields
 */

const { RangePicker } = DatePicker;
/**
 *  删除节点
 * @param selectedRows
 */

const handleRemove = async (selectedRows) => {
  const hide = message.loading('正在删除');
  if (!selectedRows) return true;

  try {
    await removeRule({
      key: selectedRows.map((row) => row.key),
    });
    hide();
    message.success('删除成功，即将刷新');
    return true;
  } catch (error) {
    hide();
    message.error('删除失败，请重试');
    return false;
  }
};
const handleAdd = async (fields) => {
  const hide = message.loading('正在添加');

  try {
    await addRule({ ...fields });
    hide();
    message.success('添加成功');
    return true;
  } catch (error) {
    hide();
    message.error('添加失败请重试！');
    return false;
  }
};
const valueEnum = {
  1: { text: '置顶该资讯' },
};
const EnterpriseNewsList = () => {
  const [createModalVisible, handleModalVisible] = useState(false);
  const actionRef = useRef();
  const formRef = useRef();
  const [row, setRow] = useState();
  const [selectedRowsState, setSelectedRows] = useState([]);
  const columns = [
    {
      title: '资讯ID',
      dataIndex: 'id',
      search: false,
      hideInForm: true,
      width: 100,
    },
    {
      search: false,
      title: '资讯标题',
      dataIndex: 'title',
      formItemProps: {
        rules: [
          {
            required: true,
            message: '资讯标题不能为空',
          },
        ],
      },
      width: 280,
      ellipsis: true,
    },
    {
      title: '封面图',
      search: false,
      dataIndex: 'cover',
      formItemProps: {
        extra: '图片大小：2M内，JPG/JPEG/PNG图片（建议16:9图片）',
        rules: [
          {
            required: true,
            message: '封面图不能为空',
          },
        ],
      },
      valueType: 'avatar',
      width: 100,
      render: (val) => {
        return <Image width={25} src={val.props.text} />;
      },
      renderFormItem: (item, props, form) => {
        return <UploadImg {...props} />;
      },
    },
    {
      title: '资讯简介',
      search: false,
      dataIndex: 'introduction',
      valueType: 'textarea',
      formItemProps: {
        rules: [
          {
            required: true,
            message: '资讯简介不能为空',
          },
        ],
      },
      width: 340,
      ellipsis: true,
    },
    {
      title: '发布者',
      search: false,
      hideInForm: true,
      dataIndex: 'publisher',
      width: 150,
    },
    {
      title: '发布时间',
      dataIndex: 'created_at',
      valueType: 'dateTime',
      search: {
        transform: (fields) => {
          return {
            startTime: fields[0],
            endTime: fields[1],
          };
        },
      },
      hideInForm: true,
      width: 200,
      renderFormItem: (item, props, form) => {
        return <RangePicker {...props} />;
      },
    },
    {
      title: '阅读量/次',
      search: false,
      dataIndex: 'pviews',
      sorter: true,
      width: 150,
    },
    {
      title: '操作',
      dataIndex: 'option',
      valueType: 'option',
      hideInDescriptions: true,
      fixed: 'right',
      width: 180,
      render: (_, record) => (
        <>
          <a
            onClick={() => {
              setRow(record);
            }}
            key="link"
          >
            详情
          </a>
          <Divider key="line1" type="vertical" />
          <a
            key="link1"

            onClick={() => {
              setRow(record);
            }}
          >
            上架
          </a>
          <Divider key="line2" type="vertical" />
          <a
            key="link2"

            onClick={() => {
              setRow(record);
              handleModalVisible(true);
              setTimeout(() => {
                formRef.current?.setFieldsValue?.(record);
              }, 100);
            }}
          >
            编辑
          </a>
          <Divider  key="line3" type="vertical" />
          <a
            key="link3"

            onClick={() => {
              handleRemove(record);
            }}
          >
            删除
          </a>
        </>
      ),
    },
    {
      dataIndex: 'keywords',
      hideInForm: true,
      hideInTable: true,
      fieldProps: {
        placeholder: '资讯ID/标题/简介',
      },
    },
    {
      dataIndex: 'content',
      title: '资讯内容',
      key: 'content',
      search: false,
      hideInTable: true,
      formItemProps: {
        rules: [
          {
            required: true,
            message: '资讯内容不能为空',
          },
        ],
      },
      renderFormItem: (item, props, form) => {
        return <Wangeditor {...props} />;
      },
    },
    {
      search: false,
      //   valueType: 'checkbox',
      hideInTable: true,
      dataIndex: 'istop',
      renderFormItem: (_, { type, defaultRender, formItemProps, fieldProps, ...rest }, form) => {
        return (
          <Checkbox {...fieldProps} {...rest}>
            置顶该资讯
          </Checkbox>
        );
      },
      width: 150,
    },
  ];
  return (
    <div>
      <ProTable
        actionRef={actionRef}
        scroll={{ x: 1200 }}
        rowKey="key"
        search={{
          labelWidth: 90,
          width: 100,
          span: 6,
        }}
        toolBarRender={() => [
          <Button
            key="createbutton"
            onClick={() => {
              handleModalVisible(true);
              setRow(undefined);
            }}
            icon={<PlusOutlined />}
            type="primary"
          >
            发布资讯
          </Button>,
        ]}
        request={async (params, sorter) => {
          const res = await queryRule({
            page: params.current,
            pageSize: params.pageSize,
            cate: 0, //0-企业资讯 1-行业动态
            sorter,
          });
          return {
            data: res.data,
            success: true,
            total: res.total,
          };
        }}
        columns={columns}
        rowSelection={{
          onChange: (_, selectedRows) =>{
             setSelectedRows(selectedRows)
          }
        }}
      />
      {selectedRowsState?.length > 0 && (
        <FooterToolbar
          extra={
            <div>
              已选择{' '}
              <a
                style={{
                  fontWeight: 600,
                }}
              >
                {selectedRowsState.length}
              </a>{' '}
              项&nbsp;&nbsp;
            </div>
          }
        >
          <Button
            onClick={async () => {
              await handleRemove(selectedRowsState);
              setSelectedRows([]);
              actionRef.current?.reloadAndRest?.();
            }}
          >
            批量删除
          </Button>
        </FooterToolbar>
      )}
      <CreateForm
        onCancel={() => handleModalVisible(false)}
        title={row ? '编辑资讯' : '发布资讯'}
        modalVisible={createModalVisible}
      >
        <ProTable
          formRef={formRef}
          onSubmit={async (value) => {
            const success = await handleAdd(value);

            if (success) {
              handleModalVisible(false);

              if (actionRef.current) {
                actionRef.current.reload();
              }
            }
          }}
          rowKey="key"
          type="form"
          columns={columns}
        />
      </CreateForm>
      {/* </PageContainer> */}
    </div>
  );
};

export default EnterpriseNewsList;

pro-table版本已经更新到最新的2.16.4，还是会报这个错，批量选择勾一个会默认勾选全部，但实际只选中了一个，不明白哪里出错了，求助
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/32189627/102870433-f8bf0f80-4477-11eb-9e01-535d2012a5a7.png)
![image](https://user-images.githubusercontent.com/32189627/102870447-fe1c5a00-4477-11eb-818e-241a66f57dad.png)

**Comment by chenshuai2144** [comment]
你的代码格式就是个灾难。这谁能看懂。

这个问题一般是 rowkey 设置错了，自行排查一下吧
