### ISSUE TITLE
🐛[BUG] pro-table 初始化页码，data 为 null 时报错

### ISSUE THREAD

**Issue by lizhongyue248** [ant-design/pro-components#1386]
### 🐛 bug 描述

后端接口在没有数据以后返回的是 `null` 而不是 `[]`，初始化是符合预期的

但是当初始化的 `pagination` 的 `current` 不是 1 的时候，点击查询、重置就会直接报错。

### 🏞 期望结果

目前只能够通过以下方式规避这个问题

```
postData={(data) => data || []}
```

期望不需要进行额外处理

### 💻 复现代码

https://codesandbox.io/s/antd-pro-table-bug-yeylt

点击查询、重置都会报错。

### © 版本信息

- ProComponents 版本: @ant-design/pro-table 2.16.4
- umi 版本 3.3.3

**Comment by chenshuai2144** [comment]
返回 null，不就是用来报错的吗？table 需要的是一个数组，返回 null 说明后端什么逻辑报错了吧

> 值 null 是一个字面量，不像 undefined，它不是全局对象的一个属性。null 是表示缺少的标识，指示变量未指向任何对象。把 null 作为尚未创建的对象，也许更好理解。在 API 中，null 常在返回类型应是一个对象，但没有关联的值的地方使用。

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/null
