### ISSUE TITLE
🐛[BUG] PageLoading re-render indefinitely 

### ISSUE THREAD

**Issue by danvln** [ant-design/pro-components#1387]
There is an issue with the current implementation of PageLoading.

([This the code I am referring to:](https://github.com/ant-design/pro-components/blob/0ac3c7c9315604f08f9c864c01ce536cf37c9c0c/packages/layout/src/BasicLayout.tsx#L474))  

In every page there is a loading part like for the component mounting:

```
useEffect(() => {
 // load data 
 // once finished send an action that the loading is complete
},[])
```

If the above code will set the "loading" to false then the component is unmounted, and and when the loading is done, the component is mounted back. But mounting it back means "useEffect []" is called again. Hence, there is an infinite loop due to this part.

```
 {loading ? <PageLoading /> : children}

```

There are hacks to make it working, but checking the loading in useEffect but that means starting to use anti-patterns, for what should be working differently. 

How do you suggest avoiding this problem? Maybe I am missing something. 

Thanks for building this great library! It's quite awesome! 

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
Trying to do a joint determination using load and data is empty?
`{loading && !data ? <PageLoading /> : children}`

**Comment by danvln** [comment]
Thanks for the reply. The loading has the right value true or false. The problem is that this line could generate mount & unmount of the children based on loading. And if the children - page has a mounting load to determine the state of loading then there is a continuous loop. Let me know if this helps, or I can add more details.

**Comment by chenshuai2144** [comment]
If this is the case, I wouldn't recommend setting up pageloading, or you could leave the loaded data to the layout instead of the child node。

**Comment by danvln** [comment]
Thanks @chenshuai2144!
