### ISSUE TITLE
🐛[BUG] 不希望刚进页面时protable就自动查询

### ISSUE THREAD

**Issue by snake11am** [ant-design/pro-components#139]
### 🐛 bug 描述

不希望刚进页面时protable就自动查询，用了manualRequest={true}希望手都触发第一次查询这个属性不起作用

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
记得写标题，不写标题没有进来看的动力的

**Comment by chenshuai2144** [comment]
manualRequest 还没发布，发布之后就可以用了

**Comment by snake11am** [comment]
好吧，临时找了个方法解决这个问题了，在request里刚开始做空属性判断直接return了。- -！
