### ISSUE TITLE
🐛[BUG] ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js),Variable @margin-md is undefined

### ISSUE THREAD

**Issue by promotion-xu** [ant-design/pro-components#1391]
### 🐛 bug 描述
安装pro-table后，引入demo报错

### 📷 复现步骤
1.yarn add @ant-design/pro-table
2.引入官网demo

### 🏞 期望结果
与官网demo呈现一致

### 💻 复现代码
```
import React from 'react'
import { Button, Tooltip } from 'antd'
import { QuestionCircleOutlined } from '@ant-design/icons'
import { ProColumns } from '@ant-design/pro-table'
import ProTable, { TableDropdown } from '@ant-design/pro-table'
import '@ant-design/pro-form/dist/form.css'
import '@ant-design/pro-table/dist/table.css'
import '@ant-design/pro-layout/dist/layout.css'
export interface TableListItem {
  key: number
  name: string
  creator: string
  createdAt: number
}
const tableListDataSource: TableListItem[] = []
const creators = ['付小小', '曲丽丽', '林东东', '陈帅帅', '兼某某']
for (let i = 0; i < 5; i += 1) {
  tableListDataSource.push({
    key: i,
    name: 'AppName',
    creator: creators[Math.floor(Math.random() * creators.length)],
    createdAt: Date.now() - Math.floor(Math.random() * 100000)
  })
}
const columns: ProColumns<TableListItem>[] = [
  {
    title: '应用名称',
    dataIndex: 'name',
    render: _ => <a>{_}</a>
  },
  {
    title: '创建者',
    dataIndex: 'creator',
    valueType: 'select',
    valueEnum: {
      all: { text: '全部' },
      付小小: { text: '付小小' },
      曲丽丽: { text: '曲丽丽' },
      林东东: { text: '林东东' },
      陈帅帅: { text: '陈帅帅' },
      兼某某: { text: '兼某某' }
    }
  },
  {
    title: (
      <>
        创建时间
        <Tooltip placement="top" title="这是一段描述">
          <QuestionCircleOutlined style={{ marginLeft: 4 }} />
        </Tooltip>
      </>
    ),
    key: 'since',
    dataIndex: 'createdAt',
    valueType: 'date',
    sorter: (a, b) => a.createdAt - b.createdAt
  },
  {
    title: '操作',
    width: '164px',
    key: 'option',
    valueType: 'option',
    render: () => [
      <a key="link">链路</a>,
      <a key="link2">报警</a>,
      <a key="link3">监控</a>,
      <TableDropdown
        key="actionGroup"
        menus={[
          { key: 'copy', name: '复制' },
          { key: 'delete', name: '删除' }
        ]}
      />
    ]
  }
]

const UserPage = props => {
  return (
    <div>
      user-page
      <ProTable
        columns={columns}
        request={(params, sorter, filter) => {
          // 表单搜索项会从 params 传入，传递给后端接口。
          console.log(params, sorter, filter)
          return Promise.resolve({
            data: tableListDataSource,
            success: true
          })
        }}
        rowKey="key"
        pagination={{
          showQuickJumper: true
        }}
        search={{
          filterType: 'light'
        }}
        dateFormatter="string"
        headerTitle="表格标题"
        toolBarRender={() => [
          <Button key="show">查看日志</Button>,
          <Button type="primary" key="primary">
            创建应用
          </Button>
        ]}
      />
    </div>
  )
}
export default UserPage
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]  "@ant-design/pro-table": "^2.16.4"
- umi 版本 2.4.4
- 浏览器环境 Google
- 开发环境 [e.g. mac OS] mac OS

**Comment by chenshuai2144** [comment]
休息antd的版本要在4.9以上

**Comment by Thisismy0312** [comment]
**still not work**

`ERROR in ./node_modules/@ant-design/pro-table/es/components/Form/index.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):



  .clearfix;
         ^
Unrecognized input. Possibly missing '(' in mixin call.
      in /Users/xuwenjie/Projects/gitea/node_modules/@ant-design/pro-table/es/components/Form/index.less (line 14, column 11)
    at processResult (/Users/xuwenjie/Projects/gitea/node_modules/webpack/lib/NormalModule.js:583:19)
    at /Users/xuwenjie/Projects/gitea/node_modules/webpack/lib/NormalModule.js:676:5
    at /Users/xuwenjie/Projects/gitea/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/xuwenjie/Projects/gitea/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/xuwenjie/Projects/gitea/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./node_modules/@ant-design/pro-table/es/components/Form/index.js 39:0-22
 @ ./node_modules/@ant-design/pro-table/es/index.js 6:0-39 9:0-392
 @ ./web_src/js/features/points/Points/sprints.js 24:0-45
 @ ./web_src/js/features/points/index.jsx 13:0-53 46:15-22
 @ ./web_src/js/points.js 4:0-53 10:10-20

1 ERROR in child compilations
webpack 5.11.0 compiled with 2 errors in 61592 ms`

my antd version is 4.11.2

**Comment by chenshuai2144** [comment]
没安装antd 导致的把

**Comment by Thisismy0312** [comment]
> 没安装antd 导致的把

安装了，找到原因了，升级mini-css-extract-plugin后就成功引入了，但是有一个新的问题，表格的样式似乎没有起到作用

![screenshot-20210214-075046](https://user-images.githubusercontent.com/15723059/107871461-c1e80180-6edc-11eb-8ac4-7d9437edfcc1.png)

![screenshot-20210214-075342](https://user-images.githubusercontent.com/15723059/107871466-d4fad180-6edc-11eb-844d-b951df04c61c.png)

![screenshot-20210214-075415](https://user-images.githubusercontent.com/15723059/107871473-e80da180-6edc-11eb-86b7-377e668a54cf.png)

**Comment by Thisismy0312** [comment]
> 没安装antd 导致的把

升级MiniCssExtractPlugin后问题解决了，谢谢
