### ISSUE TITLE
装包的时候报错🐛[BUG]

### ISSUE THREAD

**Issue by LichiaMa** [ant-design/pro-components#1398]
### 🐛 bug 描述
装包的时候报错， @ant-design/pro-provider@1.2.6 不存在

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![20201224171544](https://user-images.githubusercontent.com/17775060/103077910-b2021e80-460b-11eb-9c48-316f2a09726b.jpg)

**Comment by chenshuai2144** [comment]
使用了淘宝源码？
那需要等一下了，同步需要个过程
