### ISSUE TITLE
🧐[问题] renderFormItem 中使用 ...rest，在 ts 定义中并不能拿到 onChange 和 value 导致 ts 类型报错

### ISSUE THREAD

**Issue by bluescurry** [ant-design/pro-components#1399]
### 🧐 问题描述
renderFormItem 中使用 ...rest，将 rest 传入到自定义组件中，在 ts 定义中并不能拿到 onChange 和 value 导致 ts 类型报错

### 💻 示例代码
```
renderFormItem: (_, { type, defaultRender, ...rest }) => {
    if (type === 'form') {
      return null;
    }
    return <DatePickerLimit {...rest} />;
  }
```
![image](https://user-images.githubusercontent.com/19237129/103078242-6603a980-460c-11eb-979c-9fd353a033b9.png)
![image](https://user-images.githubusercontent.com/19237129/103078254-6dc34e00-460c-11eb-9333-dc991c80d780.png)

**Comment by chenshuai2144** [comment]
新版本不需要了，你可以设置为非必选。value 和  onChange 会由 FormItem 注入给你

**Comment by bluescurry** [comment]
![image](https://user-images.githubusercontent.com/19237129/103086363-6bb6ba80-461f-11eb-8b08-1e0baec507b5.png)
加上这两个属性就可以了，ts报错的意思应该是传参和类型一点对不上。。。
