### ISSUE TITLE
👑 [需求]ProTable中的title使用function时type参数希望增加一种

### ISSUE THREAD

**Issue by ty-bt** [ant-design/pro-components#1400]
### 🥰 需求描述
我的需求是，表格列头做复杂展示，form和齿轮按钮展开界面中希望列头是纯文本展示

### 🧐 解决方案
[需求]ProTable中的title使用function时type参数希望增加一种
form: 搜索栏title
table: 表格表头title
// 新增一种，
xxxx: 设置图标展开时的title

**Comment by chenshuai2144** [comment]
`xxxx: 设置图标展开时的title`

这个是什么场景？

**Comment by ty-bt** [comment]
> `xxxx: 设置图标展开时的title`
> 
> 这个是什么场景？

![image](https://user-images.githubusercontent.com/7368072/103089011-9f95de00-4627-11eb-8cf8-c3aa1b35025c.png)
'xxxx'是我不会起名字， 希望这个位置 title渲染方法提供不一样的type,可以渲染不同的结构

**Comment by chenshuai2144** [comment]
看了下还挺难实现的，这个是因为 setting 里面的 title 直接用的 dom，没有处理过
