### ISSUE TITLE
🧐[问题] package.json 没有找到文档对应的 tsc 命令

### ISSUE THREAD

**Issue by tongyu-public** [ant-design/pro-components#1401]
### 🧐 问题描述

http://pro-components.tongyu.tech/docs/intro#%E5%BC%80%E5%8F%91%E5%B7%A5%E4%BD%9C%E6%B5%81

### 💻 示例代码

https://github.com/ant-design/pro-components/blob/master/package.json

**Comment by chenshuai2144** [comment]
http://pro-components.tongyu.tech 这是哪里来的网站？

**Comment by tongyu-public** [comment]
不好意思 这是内网地址 文档是这里 https://github.com/ant-design/pro-components/blob/35d2dd7a4014fde15b9206b274f9cb98020bef6c/docs/intro.md#%E5%BC%80%E5%8F%91%E5%B7%A5%E4%BD%9C%E6%B5%81

**Comment by chenshuai2144** [comment]
试试 `yarn run tsc --noEmit` ,在 ci 中增加了，但是源码中没有添加。
