### ISSUE TITLE
🐛[BUG] ProTable column 同时设置 ellipsis,copyable, 在浏览器或系统放大125%时ellipsis失效

### ISSUE THREAD

**Issue by ty-bt** [ant-design/pro-components#1405]
### 🐛 bug 描述
ProTable column 同时设置 ellipsis,copyable, 在浏览器或系统放大125%时ellipsis失效

### 📷 复现步骤
进入官网ProTable第一个示例，将浏览器缩放调整至125%，可以发现ellipsis失效

### 🏞 期望结果
ellipsis生效，内容不能换行

### 💻 复现代码
https://procomponents.ant.design/components/table/

### © 版本信息
window10 , chrome 87.0.4280.88

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/7368072/103116883-f42a6f00-46a2-11eb-83f6-aedc905f3efc.png)

**Comment by chenshuai2144** [comment]
去 antd 提吧。这里解决不了。

你提了一个超屌的问题

**Comment by ty-bt** [comment]
> 去 antd 提吧。这里解决不了。
> 
> 你提了一个超屌的问题

单独使用ellipsis是没问题的
只有同时设置 ellipsis,copyable才有这个问题， antd那没有copyable属性
antd那边我不知道咋重现啊，不重现我怕他们打我，确定要提到那边去？

**Comment by chenshuai2144** [comment]
是 Typography的问题 大胆提吧
