### ISSUE TITLE
🐛[BUG]ProTable的actionRef.current.reload(true)中的resetIndex无效

### ISSUE THREAD

**Issue by hellow7758521** [ant-design/pro-components#1406]
reload时重置页码这个参数失效
proTable 2.16.2是好的，2.16.3开始出问题的，2.17.0也有问题

**Comment by chenshuai2144** [comment]
actionRef.current.reloadAndRest()

用这个

**Comment by hellow7758521** [comment]
@chenshuai2144  那actionRef.current.reloadAndRest()这个是无效的。测试版本2.17.2

**Comment by chenshuai2144** [comment]
reloadAndRest 会充值掉受控的任何东西。

https://github.com/ant-design/pro-components/blob/4fb9e4b8a85a1374ab0d0710b6796d3b09ced06a/packages/table/src/Table.tsx#L266-L276

**Comment by hellow7758521** [comment]
> reloadAndRest 会重置受控的任何东西。
> 
> https://github.com/ant-design/pro-components/blob/4fb9e4b8a85a1374ab0d0710b6796d3b09ced06a/packages/table/src/Table.tsx#L266-L276

@chenshuai2144  actionRef.current.reloadAndRest()这个中的重置页码是无效的，我做了一个demo用来验证的 https://codesandbox.io/s/silly-cartwright-0wo6z?file=/App.tsx

**Comment by chenshuai2144** [comment]
`actionRef.current.reset()`

你试试这个，有点奇怪。

**Comment by hellow7758521** [comment]
> `actionRef.current.reset()`
> 
> 你试试这个，有点奇怪。

actionRef.current.reset()是好的，只是用户选择的页数什么会被重置了。

**Comment by wood3n** [comment]
`2.18.1`也有这个问题，`reloadAndRest`无法重置`current`

**Comment by chenshuai2144** [comment]
reload 是刷新，reloadAndRest 是 刷新重置页数。reset 会重置form，页面，选择器这写所有的

**Comment by wood3n** [comment]
目前的解决方法是用`reset`，同时设置`pagination`的`defaultCurrent`和`defaultPageSize`
