### ISSUE TITLE
ProTable 全屏显示后 Modal 弹窗被覆盖，没有显示在最顶层

### ISSUE THREAD

**Issue by zmj0920** [ant-design/pro-components#1409]
### 🐛 bug 描述

ProTable 全屏显示后 Modal 弹窗被覆盖，没有显示在最顶层

### 📷 复现步骤

全屏点击添加

### 🏞 期望结果

全屏后弹窗正常显示

### 💻 复现代码

import React from 'react';
import { Button, Modal } from 'antd';
import ProTable from '@ant-design/pro-table';

export const CreateForm = (props) => {
  const { modalVisible, onCancel, modalTitle } = props;
  return (
    <Modal
      destroyOnClose
      title={modalTitle}
      visible={modalVisible}
      onCancel={() => onCancel()}
      footer={null}
    >
      {props.children}
    </Modal>
  );
};

class ProTableDemo extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      createModalVisible: false,
    };
  }

  getColumn = () => [
    {
      title: '编号',
      dataIndex: 'id',
      width: 60,
      valueType: 'indexBorder',
    },
    {
      title: '标题',
      width: 60,
      align: 'center',
      hideInForm: true,
      // search:false,
      children: [
        {
          title: '金额',
          dataIndex: 'money',
          width: 60,
          valueType: 'money',
        },
        {
          title: '姓名',
          width: 60,
          dataIndex: 'name',
          valueType: 'text',
        },
      ],
    },
    {
      title: '城市',
      dataIndex: 'city',
      width: 60,
      align: 'center',
      hideInForm: true,
    },
    {
      title: '描述',
      dataIndex: 'desc',
      width: 80,
      align: 'center',
      copyable: true, //是否支持复制
      ellipsis: true, //是否自动缩略
      tooltip: '会在 title 之后展示一个 icon，hover 之后提示一些信息',
    },
    {
      title: '时间区间',
      key: 'dateTimeRange',
      width: 100,
      align: 'center',
      dataIndex: 'createdAtRange',
      valueType: 'dateTimeRange',
      search: {
        transform: (value) => ({
          startTime: value[0],
          endTime: value[1],
        }),
      },
    },
    {
      title: '服务调用次数',
      dataIndex: 'callNo',
      width: 100,
      align: 'center',
      sorter: true,
      hideInForm: true,
      renderText: (val) => `${val} 万`,
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      align: 'center',
      filters: true,
      hideInForm: true,
      initialValue: ['1', '2'],
      valueType: 'checkbox', //多选
      valueEnum: {
        0: { text: '关闭', status: 'Default' },
        1: { text: '运行中', status: 'Processing' },
        2: { text: '已上线', status: 'Success' },
        3: { text: '异常', status: 'Error' },
      },
    },
    {
      title: '上次调度时间',
      dataIndex: 'updatedAt',
      align: 'center',
      width: 100,
      sorter: true,
      valueType: 'dateTime',
      sorter: (a, b) => a.createdAt - b.createdAt,
      hideInForm: false,
    },
  ];

  getRequest = (params, sorter, filter) => {
    let paramsData = Object.assign(params, sorter, filter);
    return testData({ ...paramsData });
  };
  /*
   * 新增弹框
   */
  onAdd = (visible) => {
    this.setState({ createModalVisible: visible });
  };

  render() {
    const { createModalVisible } = this.state;

    return (
      <>
        <ProTable
          columns={this.getColumn()}
          options={{ fullScreen: true, reload: true, setting: true }}
          toolbar={{
            actions: [
              <Button key="key" type="primary" onClick={() => this.onAdd(true)}>
                添加
              </Button>
            ],
          }}
        />

        <CreateForm
          onCancel={() => this.onAdd(false)}
          modalVisible={createModalVisible}
          modalTitle={'新建表单'}
        >
          <ProTable
            onSubmit={(value) => {
              this.handleAdd(value);
            }}
            rowKey="key"
            type="form"
            columns={this.getColumn()}
          />
        </CreateForm>
      </>
    );
  }
}

export default ProTableDemo;

### © 版本信息

- "@ant-design/pro-table": "^2.17.1",
- "umi": "^3.2.28",
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/42410507/103122666-25fbff80-46bc-11eb-976a-2d3a1aec4d7f.png)

**Comment by chenshuai2144** [comment]
这个是个全屏api的设计，你要重新render 一下 modal 的位置


```tsx
<ConfigProvider getPopupContainer={()=>document.getElementById("ant-design-pro-table")}>
  <ProTable />
  <Modal />
</ConfigProvider>
```
