### ISSUE TITLE
👑 [需求]需要ProLayout的collapse自定义位置，大屏项目时，底部的按钮不明显，想放在title下面

### ISSUE THREAD

**Issue by DevilMayDead** [ant-design/pro-components#1410]

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/layout#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-collapsed
看这个 demo

**Comment by DevilMayDead** [comment]
> https://procomponents.ant.design/components/layout#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-collapsed
> 看这个 demo

您好，请问在Antd Pro里面如何使用呢？
export const layout = ({
  initialState,
}: {
  initialState: { settings?: LayoutSettings; currentUser?: API.CurrentUser };
}): BasicLayoutProps & {
  childrenRender?: (dom: JSX.Element) => React.ReactNode;
} => {
  return {
    collapsedButtonRender: (collapsed) => (
      <div
        onClick={() => {}}
        style={{
          height: '35px',
          width: '100%',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          cursor: 'pointer',
          background: 'hsla(0,0%,100%,.15)',
        }}
      >
        <span style={{ fontSize: 20, color: 'rgb(216, 221, 229)' }}>
          <MyIcon type="icon-cebianlanzhedie" />
        </span>
      </div>
    ),
    disableMobile: true,
    disableContentMargin: true,

    // collapsedButtonRender: (collapsed) => (
    //   <Button
    //     onClick={() => {
    //       collapsed = !collapsed;
    //     }}
    //   >
    //     123
    //   </Button>
    // ),

    onPageChange: () => {
      // const { currentUser } = initialState;
      // const { location } = history;
      // 如果没有登录，重定向到 login
      // if (!currentUser && location.pathname !== '/user/login') {
      //   history.push('/user/login');
      // }
    },
    menuHeaderRender: undefined,
    ...initialState?.settings,
  };
};

**Comment by chenshuai2144** [comment]
主要是这里 
![image](https://user-images.githubusercontent.com/8186664/103130686-acbed580-46d8-11eb-9de9-ac64c73e5977.png)

注意一下格式化，这个没法看的

**Comment by DevilMayDead** [comment]
> 主要是这里
> ![image](https://user-images.githubusercontent.com/8186664/103130686-acbed580-46d8-11eb-9de9-ac64c73e5977.png)
> 
> 注意一下格式化，这个没法看的



> 主要是这里
> ![image](https://user-images.githubusercontent.com/8186664/103130686-acbed580-46d8-11eb-9de9-ac64c73e5977.png)
> 
> 注意一下格式化，这个没法看的

```
export const layout = ({initialState,}: {initialState: { settings?: LayoutSettings; currentUser?: API.CurrentUser };}) => {
  return {
    collapsedButtonRender: (collapsed) => (
      <div
        onClick={() => {}}
        style={{
          height: '35px',
          width: '100%',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          cursor: 'pointer',
          background: 'hsla(0,0%,100%,.15)',
        }}
      >
        <span style={{ fontSize: 20, color: 'rgb(216, 221, 229)' }}>
          <MyIcon type="icon-cebianlanzhedie" />
        </span>
      </div>
    ),
    disableMobile: true,
    disableContentMargin: true,

    onPageChange: () => {},
    menuHeaderRender: undefined,
    ...initialState?.settings,
  };
};
```
![7D8C4FBC-E551-44e2-B7C6-0B9A6D681718](https://user-images.githubusercontent.com/36238435/103130799-2a82e100-46d9-11eb-9c0d-4f05ad6f6b18.png)

**Comment by DevilMayDead** [comment]
> 主要是这里
> ![image](https://user-images.githubusercontent.com/8186664/103130686-acbed580-46d8-11eb-9de9-ac64c73e5977.png)
> 
> 注意一下格式化，这个没法看的

![Dingtalk_20201225175728](https://user-images.githubusercontent.com/36238435/103131191-b9442d80-46da-11eb-9176-cee01d2f1356.jpg)
类似于这样
