### ISSUE TITLE
🐛[BUG]ProCard split模式和PageContainer样式冲突 

### ISSUE THREAD

**Issue by Sean1514** [ant-design/pro-components#1411]
### 🐛 bug 描述

将ProCard设置split模式，包裹在PageContainer容器里，导致ProCard css错乱。

### 💻 复现代码
![image](https://user-images.githubusercontent.com/48789222/103131023-0b388380-46da-11eb-8917-0a54e39780af.png)

### © 版本信息

- ProComponents 版本: [   "@ant-design/pro-layout": "^6.5.0",  "@ant-design/pro-card": "^1.8.2",]

**Comment by rdmclin2** [comment]
是指 有padding吗？ PageContainer 默认会对内容加 padding ， 这个不是bug，如果是觉得上面白底下面没有的话，可以给 PageContainer 添加 ghost 属性。

```
    <PageContainer title="左右结构" ghost>
      <ProCard split="vertical">
        <ProCard colSpan="384px" ghost>
          <IPList onChange={(cIp) => setIp(cIp)} ip={ip} />
        </ProCard>
        <ProCard title={ip}>
          <DetailList ip={ip} />
        </ProCard>
      </ProCard>
    </PageContainer>
```

![image](https://user-images.githubusercontent.com/4705237/105287007-55862500-5bf2-11eb-96ea-cb65e4df980f.png)

**Comment by Sean1514** [comment]
> 是指 有padding吗？ PageContainer 默认会对内容加 padding ， 这个不是bug，如果是觉得上面白底下面没有的话，可以给 PageContainer 添加 ghost 属性。
> 
> ```
>     <PageContainer title="左右结构" ghost>
>       <ProCard split="vertical">
>         <ProCard colSpan="384px" ghost>
>           <IPList onChange={(cIp) => setIp(cIp)} ip={ip} />
>         </ProCard>
>         <ProCard title={ip}>
>           <DetailList ip={ip} />
>         </ProCard>
>       </ProCard>
>     </PageContainer>
> ```
> 
> ![image](https://user-images.githubusercontent.com/4705237/105287007-55862500-5bf2-11eb-96ea-cb65e4df980f.png)

不是padding 是布局方式 flex布局无法穿透

**Comment by rdmclin2** [comment]
可以给个css 错乱的例子或者截图吗？

**Comment by Sean1514** [comment]
> 可以给个css 错乱的例子或者截图吗？

不好意思 更新了版本以后就没问题了  您可以试试"@ant-design/pro-layout": "^6.5.0",这个版本

**Comment by rdmclin2** [comment]
了解了
