### ISSUE TITLE
🐛[BUG]ProFormTextArea中的autoSize不生效

### ISSUE THREAD

**Issue by su1329** [ant-design/pro-components#1413]
### 🐛 bug 描述

ProFormTextArea中的autoSize不生效，输入超过3行，默认的文字框的属性一直都是rows=3

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/13175074/103136501-f1a83380-46fb-11eb-81f6-f5e53c3f9a52.png)

### 🏞 期望结果

希望可以根据文字行数自动调整文字框的高度

### 💻 复现代码
`<ProFormTextArea placeholder="UUIDs" autoSize />`

### © 版本信息

- "@ant-design/pro-form": "^1.3.0"
- "umi": "^3.2.14",
- Edge版本 87.0.664.66
- Win10

**Comment by chenshuai2144** [comment]
`<ProFormTextArea placeholder="UUIDs"  fieldProps={{ autoSize:true }}/>`



![image](https://user-images.githubusercontent.com/8186664/103146986-65455180-478b-11eb-8ba7-a8fb7fb13592.png)
