### ISSUE TITLE
🐛[BUG] SettingDrawer组件导致锚点丢失

### ISSUE THREAD

**Issue by chengjiantong1005** [ant-design/pro-components#142]
### 🐛 bug 描述
SettingDrawer组件导致锚点丢失

使用SettingDrawer组件后，使用主题切换等功能时执行broswerHistory.replace方法 导致页面上的hash丢失？
### 📷 复现步骤
browserHistory.replace({
      search: stringify(diffParams),
    });

执行该语句，会把url上原有的hash清空
### 🏞 期望结果
希望不要清空

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
记得写 title

**Comment by chenshuai2144** [comment]
来个 pr?
