### ISSUE TITLE
🐛[BUG] ProTable 中的 expandable defaultExpandAllRows 失效

### ISSUE THREAD

**Issue by AmagiDDmxh** [ant-design/pro-components#1427]
### 🐛 bug 描述

ProTable 中的 expandable-defaultExpandAllRows 属性失效

### 📷 复现步骤
输入 `expandable={{ defaultExpandAllRows: true }}`
### 🏞 期望结果
像 ant-design table 一样展开所有
[CodeSanbox 期望结果](https://codesandbox.io/s/tree-data-antd494-forked-vshg1)
### 💻 复现代码
代码与期望结果无差，但 proTable 并没有展开 rows
[CodeSanbox 代码](https://codesandbox.io/s/crimson-smoke-1o25r?file=/App.tsx)

### © 版本信息

- pro-table 版本: [2.17.2]
- umi 版本
- 浏览器环境
- 开发环境 [Arch Linux]

### 🚑 其他信息
无

**Comment by chenshuai2144** [comment]
defaultExpandAllRows 只有在table初始化的时候才生效。

如果想要它生效最好在dataSource 的数据请求回来之后再渲染 table的dom 节点。


如果用了request，可以用 onLoad 里拿到 dataSource 里面的数据，然后自己拼接 keys
