### ISSUE TITLE
👑 [需求] 支持 EditableProTabs 

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/pro-components#1429]
### 🥰 需求描述

类似编辑表格，如果传递 editable，开启行编辑模式，但是表格的布局是一维的，受到很大限制，如果是 tabs 则不需要

### 🧐 解决方案

增加 EdtiableTabs 组件，接受单个 children 参数，接受 editable 配置参数，编辑模式下可以增加，保存，删除“页”数据

**Comment by chenshuai2144** [comment]
来个截图？

**Comment by tolerance-go** [comment]
@chenshuai2144 之后提一个 PR 上来

**Comment by chenshuai2144** [comment]
暂时没有看到使用场景，先关掉了
