### ISSUE TITLE
🐛[BUG] ProTable 升级到2.5.* 之后会报错，回退到2.4.*则正常

### ISSUE THREAD

**Issue by youshao** [ant-design/pro-components#143]
### 🐛 bug 描述

ProTable 升级到2.5.* 之后会报错，回退到2.4.*则正常。错误截图如下：
![image](https://user-images.githubusercontent.com/11664572/89778264-c6072100-db3f-11ea-9903-2b37a1d9c7ad.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
多 repo 发包的有问题，重新安装就依赖就好了。


![image](https://user-images.githubusercontent.com/8186664/89856156-0c559200-dbcb-11ea-9ce8-022a325344cd.png)

**Comment by youshao** [comment]
> 多 repo 发包的有问题，重新安装就依赖就好了。
> 
> ![image](https://user-images.githubusercontent.com/8186664/89856156-0c559200-dbcb-11ea-9ce8-022a325344cd.png)

昨晚11点多改为使用【~】来锁定版本了，不太敢用【^】。列表遍历的时候会自动将值为0的项渲染成列表的索引（0，1，2，3，4，。。。）
