### ISSUE TITLE
`onValueChange`  和  `setFieldsValue `  配合使用，尽量使用中心化的方式

### ISSUE THREAD

**Issue by liuht777** [ant-design/pro-components#1434]
`onValueChange`  和  `setFieldsValue `  配合使用，尽量使用中心化的方式

_Originally posted by @chenshuai2144 in https://github.com/ant-design/pro-components/issues/741#issuecomment-709382900_

文档里面也没看到 onValueChange啊，onValueChange 怎么使用

**Comment by ccloveak** [comment]
看你数据源是哪的，从数据源取数据，设置到form里

**Comment by ccloveak** [comment]
> 看你数据源是哪的，从数据源取数据，设置到form里

咦 ，貌似有歧义，再补充下，简单来说就是你找个东西暂存下你的输入（我一般都是存在url上，也可以放在某个state里），尽量符合 single source of truth

**Comment by chenshuai2144** [comment]
https://ant.design/components/form-cn/#Form.Item

 onValueChanges 是 antd Form 的功能

**Comment by ccloveak** [comment]
> https://ant.design/components/form-cn/#Form.Item
> 
> onValueChanges 是 antd Form 的功能

....onValuesChange
