### ISSUE TITLE
👑 [需求] 需要在手机的输入框，输完之后显示搜索

### ISSUE THREAD

**Issue by ccloveak** [ant-design/pro-components#1438]
### 🥰 需求描述
* 特别是在ios下需要出现搜索（实际测试了一下，给input加search属性后能在安卓机上出现搜索）
* 类似这样的
![image](https://user-images.githubusercontent.com/38686314/103201291-e559eb80-4932-11eb-9393-5aa7a5271a66.png)

### 🧐 解决方案
给外层的form加个action
或者是其他途径实现

### 🚑 其他信息
新年快乐！

**Comment by chenshuai2144** [comment]
soga，可以手动加的吧

**Comment by chenshuai2144** [comment]
手动加一下吧，用 fieldProps，不然可能会影响别的用户
