### ISSUE TITLE
🧐[问题]很疑惑 pro-layout 的菜单是出于什么原因把子级菜单的缩进给取消掉了？

### ISSUE THREAD

**Issue by mzl980425** [ant-design/pro-components#1439]
### 🧐 问题描述

很疑惑 pro-layout 的菜单是出于什么原因把子级菜单的缩进给取消掉了？

以前有缩进，层级很清晰。现在取消缩进以后，二级菜单看起来跟三级菜单简直一模一样

### 🚑 其他信息

👇 这个是现在的
![image](https://user-images.githubusercontent.com/22958600/103204971-70d37c80-4933-11eb-9002-8c7d9e182c0e.png)

👇 这个是以前的
![image](https://user-images.githubusercontent.com/22958600/103205105-c871e800-4933-11eb-8a20-a4deca192172.png)

**Comment by chenshuai2144** [comment]
是 bug 导致的，更新到 v6.9.5 这个问题就会消失掉
