### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by nameJw** [ant-design/pro-components#144]
### 🐛 bug 描述
<ProLayout>menuDataRender加载后台返回数据菜单栏初始时不会展开已经打开已经页面的菜单选项

### 📷 复现步骤
就是权限控制，使用后台返回的菜单数据，能正常渲染，但是菜单没有展开对应已经打开页面的菜单（就是折叠状态）,然后打开其他菜单页面，页面打开后菜单又自动折叠起来

### 🏞 期望结果

菜单展开已经开打的页面

### 💻 复现代码
其中menuData 为后台返回的菜单数据
`
<ProLayout
    menuDataRender={!isSuperAdmin ? () => menuData : null}
/>
`

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
-antd: "^4.5.2"
-pro-layout：5.0.0
- umi 版本: 2.13.13
- 浏览器环境：谷歌
- 开发环境 [e.g. windows]

### 🚑 其他信息
使用本地config/config.js 文件下routes下的菜单正常，使用后台返回的数据就就不能展开。是我哪里没有正确设置还是框架的bug？

**Comment by nameJw** [comment]
> ### 🐛 bug 描述
> menuDataRender加载后台返回数据菜单栏初始时不会展开已经打开已经页面的菜单选项
> 
> ### 📷 复现步骤
> 就是权限控制，使用后台返回的菜单数据，能正常渲染，但是菜单没有展开对应已经打开页面的菜单（就是折叠状态）,然后打开其他菜单页面，页面打开后菜单又自动折叠起来
> 
> ### 🏞 期望结果
> 菜单展开已经开打的页面
> 
> ### 💻 复现代码
> 其中menuData 为后台返回的菜单数据
> `<ProLayout menuDataRender={!isSuperAdmin ? () => menuData : null} />`
> 
> ### © 版本信息
> * Ant Design Pro 版本: [e.g. 4.0.0]
>   -antd: "^4.5.2"
>   -pro-layout：5.0.0
> * umi 版本: 2.13.13
> * 浏览器环境：谷歌
> * 开发环境 [e.g. windows]
> 
> ### 🚑 其他信息
> 使用本地config/config.js 文件下routes下的菜单正常，使用后台返回的数据就就不能展开。是我哪里没有正确设置还是框架的bug？

**Comment by nameJw** [comment]
在已废弃的仓库也有类似问题

**Comment by nameJw** [comment]
在https://github.com/ant-design/ant-design-pro-layout/issues/580已废弃的仓库中也存在类似的issue

**Comment by nameJw** [comment]
在已废弃的仓库中也存在类似的issue
[https://github.com/ant-design/ant-design-pro-layout/issues/580](url)

**Comment by FLEasy** [comment]
请问 这个问题解决了吗？ 我也遇到了这样的情况

**Comment by tuonioooo** [comment]
同上，有解决的方式么

**Comment by FLEasy** [comment]
@tuonioooo 我之后是通过另一种方式解决的 就是 在你的菜单数据没有请求出来前  不要展示ProLayout

**Comment by nameJw** [comment]
> 同上，有解决的方式么

我的问题是因为后台返回多了一个key字段，我觉得和框架本身的key冲突了，于是我重洗数据，把key去掉，然后就可以了

**Comment by nameJw** [comment]
> > 同上，有解决的方式么
> 
> 我的问题是因为后台返回多了一个key字段，我觉得和框架本身的key冲突了，于是我重洗数据，把key去掉，然后就可以了

也可以叫后台把key去掉返回，但是在做权限分配的权限树的时候，key还是必须需要的，我的项目这两个地方用的同一个接口，所以菜单是我自己洗数据，没叫后台搞。
