### ISSUE TITLE
🐛[BUG] React does not recognize the `scrollLocker` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `scrolllocker` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#1440]
React does not recognize the `scrollLocker` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `scrolllocker` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
![image](https://user-images.githubusercontent.com/30397655/103215409-388d6780-494e-11eb-8cf4-2da76f76a400.png)

**Comment by ccloveak** [comment]
。。。我还以为是我一个人，是什么组件使用不当导致的，正在努力找哪里出了问题。。。。隐约感觉是侧边栏那

**Comment by chenshuai2144** [comment]
antd 的 drawer 的问题，等待下次发版本吧

**Comment by chenshuai2144** [comment]
close by https://github.com/react-component/drawer/pull/120
