### ISSUE TITLE
👑 [需求]ProTable搜索表单每个搜索项目可以自定义宽度

### ISSUE THREAD

**Issue by JTenacity** [ant-design/pro-components#1441]
### 🥰 需求描述
ProTable中的搜索表单目前可以通过search里span达到每一行固定几列，现在需要不同和列是不同宽度。类似于下图这样的效果

![image](https://user-images.githubusercontent.com/19601885/103255588-cd32ac80-49c4-11eb-9e64-f152c9007f4e.png)

**Comment by scyx** [comment]
附议

**Comment by chenshuai2144** [comment]
colSize 可以配置占用的格子比例。


colSize | 一个表单项占用的格子数量, 占比= colSize*span，colSize 默认为 1 ，span 为 8，span是form={{span:8}} 全局设置的 | number | -
-- | -- | -- | --

**Comment by hebye3548** [comment]
@chenshuai2144 更新版本后colSize失效了

**Comment by scyx** [comment]
> @chenshuai2144 更新版本后colSize失效了

附议

**Comment by JTenacity** [comment]
@chenshuai2144 试了感觉不好使啊
使用的版本：
"@ant-design/pro-form": "^1.10.0",
"@ant-design/pro-layout": "^6.6.1",
"@ant-design/pro-table": "^2.15.0",
"antd": "^4.9.1",
代码如下:
`import React, { useState, useEffect, useRef } from 'react';
import { Select, Button, Modal, Input, ConfigProvider } from 'antd';
import { connect } from 'umi';
import { PlusOutlined } from '@ant-design/icons';
import { PageContainer } from '@ant-design/pro-layout';
import ProTable from '@ant-design/pro-table';

const mapState = ({ }) => {
  return {};
};
export default connect(mapState)((props) => {
  const { dispatch } = props;
  const [reload, setReload] = useState(false);

  const ref = useRef();

  const searchFormColumns = [
    {
      title: '关键词搜索',
      dataIndex: 'keywords',
      hideInTable: true,
      renderFormItem: (_, { type, defaultRender, formItemProps, fieldProps, ...rest }, form) => {
        if (type === 'form') {
          return null;
        }
        return <Input {...rest.fieldProps} placeholder="关键词搜索" />;
      },
      colSize: 2,
    },
    {
      title: '选择一级所属行业',
      dataIndex: 'trade1',
      hideInTable: true,
      valueEnum: {
        0: { text: '草稿', status: 'Warning' },
        1: { text: '待审核', status: 'Processing' },
        2: { text: '启用', status: 'Success' },
        3: { text: '停用', status: 'Error' },
      },
    },
    {
      title: '选择二级所属行业',
      dataIndex: 'trade2',
      hideInTable: true,
      valueEnum: {
        0: { text: '草稿', status: 'Warning' },
        1: { text: '待审核', status: 'Processing' },
        2: { text: '启用', status: 'Success' },
        3: { text: '停用', status: 'Error' },
      },
    },
    {
      title: '选择账号属性',
      dataIndex: 'property',
      hideInTable: true,
      valueEnum: {
        0: { text: '草稿', status: 'Warning' },
        1: { text: '待审核', status: 'Processing' },
        2: { text: '启用', status: 'Success' },
        3: { text: '停用', status: 'Error' },
      },
    },
    {
      title: '客服邮箱',
      dataIndex: 'trade1',
      hideInTable: true,
      renderFormItem: (_, { type, defaultRender, formItemProps, fieldProps, ...rest }, form) => {
        if (type === 'form') {
          return null;
        }
        return <Input {...rest.fieldProps} placeholder="客服邮箱" />;
      },
    },
    {
      title: '选择客服属性',
      dataIndex: 'client',
      hideInTable: true,
      valueEnum: {
        0: { text: '草稿', status: 'Warning' },
        1: { text: '待审核', status: 'Processing' },
        2: { text: '启用', status: 'Success' },
        3: { text: '停用', status: 'Error' },
      },
    },
    {
      title: '选择售后人员',
      dataIndex: 'aftersale',
      hideInTable: true,
      valueEnum: {
        0: { text: '草稿', status: 'Warning' },
        1: { text: '待审核', status: 'Processing' },
        2: { text: '启用', status: 'Success' },
        3: { text: '停用', status: 'Error' },
      },
    },
    {
      title: '到期时间',
      dataIndex: 'endTime',
      hideInTable: true,
      valueType: 'dateRange',
    },
    {
      title: '总到期时间',
      dataIndex: 'allEndTime',
      hideInTable: true,
      valueType: 'dateRange',
    },
    {
      title: '选择产品',
      dataIndex: 'product',
      hideInTable: true,
      valueEnum: {
        0: { text: '草稿', status: 'Warning' },
        1: { text: '待审核', status: 'Processing' },
        2: { text: '启用', status: 'Success' },
        3: { text: '停用', status: 'Error' },
      },
    },
  ];

  const columns = [
    ...searchFormColumns,
    {
      title: '操作员ID',
      dataIndex: 'id',
      search: false,
    },
    {
      title: '操作员姓名',
      dataIndex: 'realName',
      renderFormItem: (_, { type, defaultRender, formItemProps, fieldProps, ...rest }, form) => {
        if (type === 'form') {
          return null;
        }
        return <Input {...rest.fieldProps} placeholder="操作员姓名" />;
      },
    },
    {
      title: '手机号',
      dataIndex: 'phone',
      search: false,
    },
    {
      title: '邮箱',
      dataIndex: 'account',
      renderFormItem: (_, { type, defaultRender, formItemProps, fieldProps, ...rest }, form) => {
        if (type === 'form') {
          return null;
        }
        return <Input {...rest.fieldProps} placeholder="操作员邮箱" />;
      },
    },
    {
      title: '角色',
      dataIndex: 'roleName',
      search: false,
    },
    {
      title: '状态',
      dataIndex: 'status',
      valueEnum: {
        0: { text: '草稿', status: 'Warning' },
        1: { text: '待审核', status: 'Processing' },
        2: { text: '启用', status: 'Success' },
        3: { text: '停用', status: 'Error' },
      },
      search: false,
    },
    
  ];

  

  return (
    <div className={styles.bossAccount}>
      <PageContainer>
        <ProTable
          columns={columns}
          headerTitle="账号列表"
          options={false}
          actionRef={ref}
          rowKey="id"
          form={{
            wrapperCol: {
              span: 24,
            },
          }}
        />
      </PageContainer>
    </div>
  );
});
`
