### ISSUE TITLE
🐛[BUG]ProTable 页面第一次加载时 initialValue 设置不生效

### ISSUE THREAD

**Issue by bluescurry** [ant-design/pro-components#1446]
### 🐛 bug 描述
整体页面刷新时，第一次 pro-table 发出的请求并不没有带 initialValue 设置的参数，点击“查询”时 initialValue 才生效

### 📷 复现步骤

刷新页面，在 network 中查看接口请求

### 🏞 期望结果

请求：https://proapi.azurewebsites.net/github/issues?current=1&pageSize=5&state=open

### 💻 复现代码

https://codesandbox.io/s/vigilant-villani-gxtqt?file=/App.tsx
![flutter-share](https://user-images.githubusercontent.com/19237129/103285712-dac65180-4a19-11eb-98df-f40ad02853bb.gif)
![pro-table](https://user-images.githubusercontent.com/19237129/103285853-2416a100-4a1a-11eb-8938-4432d51a1297.gif)

### © 版本信息

- ProComponents 版本: pro-table：2.18.1
- umi 版本：3.3.3
- 浏览器环境 chrome
- 开发环境 mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/19237129/103285267-9d14f900-4a18-11eb-975c-f3259730eee6.png)

**Comment by ccloveak** [comment]
你最好能描述下具体的业务场景。。。从我能理解的角度，你是希望页面刷新的时候，表单里带上之前的查询条件？你可以从这方面搜一下之前的issue。

**Comment by bluescurry** [comment]
> 你最好能描述下具体的业务场景。。。从我能理解的角度，你是希望页面刷新的时候，表单里带上之前的查询条件？你可以从这方面搜一下之前的issue。

业务场景是打开一个列表页，希望在 initialValues 设置的初始值在进入页面第一次请求列表数据的时候就带着设置的初始值，目前的现象是第一次请求的时候并没有initialValues设置的值

**Comment by bluescurry** [comment]
我理解是不是第一个请求时从 form 中获取数据和 form 设置 initialValues 是异步进行的，有可能在首次请求的时候，form  还没有initialValues完毕，所以获取不到初始的参数

**Comment by ccloveak** [comment]
#### 问题简化一下
*  表单的初始值已经赋值了，但是数据并不是根据表单来获取的
#### 需要确认
* 找后端同学要个实际的接口测试一下。
* 看你们的项目结构，datasorce是从其他地方处理好了传给protable的，还是protable发request请求获取的。
   * protable的request 的参数不一定跟你后端提供的参数一致
#### 解决方案
1. 比较理想的是按照正常思维，根据查询表单获取数据，改变查询表单改变查询参数，重新获取数据
2. 时间紧任务重的话，你根据事先设定的查询条件，手动设置 `defaultData`

**Comment by bluescurry** [comment]
> #### 问题简化一下
> * 表单的初始值已经赋值了，但是数据并不是根据表单来获取的
> 
> #### 需要确认
> * 找后端同学要个实际的接口测试一下。
> * 看你们的项目结构，datasorce是从其他地方处理好了传给protable的，还是protable发request请求获取的。
>   
>   * protable的request 的参数不一定跟你后端提供的参数一致
> 
> #### 解决方案
> 1. 比较理想的是按照正常思维，根据查询表单获取数据，改变查询表单改变查询参数，重新获取数据
> 2. 时间紧任务重的话，你根据事先设定的查询条件，手动设置 `defaultData`

你好，感谢你的问题梳理，不过我觉得你误解我的意思了，我理解这个可能是一个bug，或者是我用法上的问题，你的所答并非我的所问

**Comment by shuxiaoman** [comment]
同样的问题；
在第一次进入页面，自动执行request，但request的第一个参数params里面没有columns里的initialValues的值

**Comment by cuihq2005** [comment]
> 同样的问题；
> 在第一次进入页面，自动执行request，但request的第一个参数params里面没有columns里的initialValues的值

同样的问题

**Comment by cuihq2005** [comment]
![image](https://user-images.githubusercontent.com/6793036/103401840-8dff8980-4b85-11eb-8928-fb51f0c3589e.png)
2.5.6分支在初始化FormSearch的时候使用了form. initialValues,当前版本不见了，希望能够恢复

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/103403156-31eb3400-4b8a-11eb-867a-624f13c9bacb.png)


试了一下可以的，你的 initialValues 是不是异步设置上去的？

**Comment by cuihq2005** [comment]
```
<ProTable
        actionRef={actionRef}
        rowKey={(r) => r.id}
        loading={loading}
        search={{ span: defaultSearchColConfig, optionRender: defaultOptionRender }}
        request={(params) => queryVsmsTpl(params)}
        columnEmptyText=""
        columns={columns}
        rowSelection={false}
        toolBarRender={() => [
          <Button key="new" type="primary" onClick={onCreate}>
            <PlusOutlined /> 新建
          </Button>,
        ]}
        tableAlertRender={false}
        form={{ initialValues: { status: ['0', '1'] } }}
      />
```
其中使用 **form={{ initialValues: { status: ['0', '1'] } }}**为form设置初始值。赋值后打开页面的第一次查询无法将initialValues发送到后端，点击查询按钮可以

从ProTable的代码里看，formSearch初始为空，
```
  const [formSearch, setFormSearch] = useMountMergeState<Record<string, unknown> | undefined>(
    undefined,
  );
```
在为action赋值，发起第一次查询的时候formSearch没有被赋值，所以不会把initialValues带到后端，我不清楚您的参数是怎么带上去的
```
const action = useFetchData(...)
```
这个功能以前是ok的，我看2.5.6分支的代码，初始化formSearch的时候使用了form.initialValues
```
  const [formSearch, setFormSearch] = useState<{}>(() => rest.form?.initialValues);
```
上诉请参考

**Comment by chenshuai2144** [comment]
来个重现的代码吧，useState<{}>(() => rest.form?.initialValues); 这个数据没经过转化，所以我在初始化的时候执行了一次 submit

**Comment by bluescurry** [comment]
> 来个重现的代码吧，useState<{}>(() => rest.form?.initialValues); 这个数据没经过转化，所以我在初始化的时候执行了一次 submit

https://codesandbox.io/s/vigilant-villani-gxtqt?file=/App.tsx

**Comment by cuihq2005** [comment]
https://codesandbox.io/s/busy-edison-ypofx?file=/App.tsx
 刷新页面，第一次没有（刷新页面太慢了，我删了一个item，强制刷新的）
![image](https://user-images.githubusercontent.com/6793036/103405257-775f2f80-4b91-11eb-80b9-330752d176f3.png)
点击查询按钮的查询可以
![image](https://user-images.githubusercontent.com/6793036/103405327-a70e3780-4b91-11eb-9037-f01882639d15.png)

**Comment by bluescurry** [comment]
> https://codesandbox.io/s/busy-edison-ypofx?file=/App.tsx
> 刷新页面，第一次没有（刷新页面太慢了，我删了一个item，强制刷新的）
> ![image](https://user-images.githubusercontent.com/6793036/103405257-775f2f80-4b91-11eb-80b9-330752d176f3.png)
> 点击查询按钮的查询可以
> ![image](https://user-images.githubusercontent.com/6793036/103405327-a70e3780-4b91-11eb-9037-f01882639d15.png)

热更新是没问题的，问题就是在第一次渲染pro-table的时候，可以在本地创建一个空项目试试。。。

**Comment by cheer001** [comment]
> 来个重现的代码吧，useState<{}>(() => rest.form?.initialValues); 这个数据没经过转化，所以我在初始化的时候执行了一次 submit

我跟楼主遇到同样的问题， 第一次加载页面有时候拿不到initialValues的值

**Comment by cheer001** [comment]
> 来个重现的代码吧，useState<{}>(() => rest.form?.initialValues); 这个数据没经过转化，所以我在初始化的时候执行了一次 submit

![image](https://user-images.githubusercontent.com/62379123/103407658-66ff8280-4b9a-11eb-9d7e-77e446ed9f0f.png)

**Comment by chenshuai2144** [comment]
试试这个，延迟了一下submit 的时间

https://github.com/ant-design/pro-components/pull/1466

**Comment by cheer001** [comment]
> 试试这个，延迟了一下submit 的时间
> 
> #1466

![image](https://user-images.githubusercontent.com/62379123/103450374-64af3c80-4cf0-11eb-8a5a-d89942712c9d.png)
还是获取不到protable的表单初始化值

**Comment by cheer001** [comment]
> 试试这个，延迟了一下submit 的时间
> 
> #1466

![image](https://user-images.githubusercontent.com/62379123/103450419-0b93d880-4cf1-11eb-9f1a-068abe08b1cf.png)
还是获取不到protable的表单初始化值

**Comment by chenshuai2144** [comment]
你这个太奇怪了，是不是没写name 之类的

**Comment by bluescurry** [comment]
> 试试这个，延迟了一下submit 的时间
> 
> #1466

我这边更新pro-table的包试了下，没问题了，看了下源码，是 submit 触发时机那块做了修改是吗

**Comment by bluescurry** [comment]
> > 试试这个，延迟了一下submit 的时间
> > #1466
> 
> ![image](https://user-images.githubusercontent.com/62379123/103450419-0b93d880-4cf1-11eb-9f1a-068abe08b1cf.png)
> 还是获取不到protable的表单初始化值

你把pro-table版本更新到最新的2.19.0了吗，我试了下，问题是好了的

**Comment by cheer001** [comment]
> > > 试试这个，延迟了一下submit 的时间
> > > #1466
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/62379123/103450419-0b93d880-4cf1-11eb-9f1a-068abe08b1cf.png)
> > 还是获取不到protable的表单初始化值
> 
> 你把pro-table版本更新到最新的2.19.0了吗，我试了下，问题是好了的

升级到这个版本了，还是会出现获取不到初始化值的问题

**Comment by cheer001** [comment]
> > > 试试这个，延迟了一下submit 的时间
> > > #1466
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/62379123/103450419-0b93d880-4cf1-11eb-9f1a-068abe08b1cf.png)
> > 还是获取不到protable的表单初始化值
> 
> 你把pro-table版本更新到最新的2.19.0了吗，我试了下，问题是好了的

![image](https://user-images.githubusercontent.com/62379123/103453286-59b9d380-4d13-11eb-8b5b-844ef1a36df0.png)
![image](https://user-images.githubusercontent.com/62379123/103453297-6fc79400-4d13-11eb-8e90-5720f9278575.png)

**Comment by cheer001** [comment]
> 你这个太奇怪了，是不是没写 name 之类的手动触发submit是可以拿到表单初始化值的

**Comment by cheer001** [comment]
> 你这个太奇怪了，是不是没写 name 之类的

手动触发submit是可以拿到表单初始化值的

**Comment by bluescurry** [comment]
> > 你这个太奇怪了，是不是没写 name 之类的
> 
> 手动触发submit是可以拿到表单初始化值的
> ![image](https://user-images.githubusercontent.com/62379123/103453463-28da9e00-4d15-11eb-8c94-60b7638f742e.png)

能贴一些关键代码吗，我是把一些 pro-components 的包一起升级的，不知道是否会有影响
```
yarn upgrade @ant-design/pro-form @ant-design/pro-table
```

**Comment by cheer001** [comment]
> @ant-design/pro-form

我升级一下proform看下

**Comment by bluescurry** [comment]
> > @ant-design/pro-form
> 
> 我升级一下proform看下

请问你那问题解决了吗，解决了的话我就把issue close了

**Comment by mumu0125** [comment]
"node_modules/@ant-design/pro-components": {
      "version": "2.6.35",
      "resolved": "https://registry.npmmirror.com/@ant-design/pro-components/-/pro-components-2.6.35.tgz",
      "integrity": "sha512-2TKg2yWDZGLnntH4R/tgfNJGn8sU6j92jqkJAoSqIo5h3Zdl0PVSbHo6m+oFuAjF7Pst5kikTR2fPqw3g872xA==",
      "dependencies": {
        "@ant-design/pro-card": "2.5.24",
        "@ant-design/pro-descriptions": "2.5.19",
        "@ant-design/pro-field": "2.13.5",
        "@ant-design/pro-form": "2.21.6",
        "@ant-design/pro-layout": "7.17.13",
        "@ant-design/pro-list": "2.5.34",
        "@ant-design/pro-provider": "2.13.3",
        "@ant-design/pro-skeleton": "2.1.9",
        "@ant-design/pro-table": "3.13.3",
        "@ant-design/pro-utils": "2.14.12",
        "@babel/runtime": "^7.16.3"
      }
      我用的这个版本，这个问题还在
