### ISSUE TITLE
Pro-Table 列拖拽排序时丢失固定列设置

### ISSUE THREAD

**Issue by Nokecy** [ant-design/pro-components#1448]
https://github.com/ant-design/pro-components/blob/deb0a08272c2b162bb34f6355fc93ddc22e02f77/packages/table/src/components/ColumnSetting/index.tsx#L149

在有固定列的情况下，拖拽排序，这行代码会丢失列的固定列状态。

**Comment by Nokecy** [comment]
newMap 在初始情况下为{}

**Comment by chenshuai2144** [comment]
都找到问题了，直接来个pr吧

**Comment by Amy-Tan** [comment]
请问问题解决了吗? 我也遇到同样的问题了

**Comment by chenshuai2144** [comment]
还没，你要提个pr吗？

**Comment by chenshuai2144** [comment]
fixed in new props
