### ISSUE TITLE
🐛[BUG] ProTable升级到2.17.3的时候泛型提示错误

### ISSUE THREAD

**Issue by egene-huang** [ant-design/pro-components#1449]
### 🐛 bug 描述

在我将 ProTable升级到2.17.3之后， 在 原来的代码 ProTable<TableItem> 提示泛型参数错误
TS2344 Type `TableItem` does not staisfy the constraint 'Record<String, unknown>'.  index signature is missing in type 'TableItem'

请问是怎么回事啊？ 我是一个后端研发， 麻烦帮我看看 多谢了  我自己一直没有找到解决的办法

### © 版本信息

- ProComponents 版本如下: 
    "@ant-design/pro-descriptions": "1.2.0",
    "@ant-design/pro-form": "1.11.3",
    "@ant-design/pro-layout": "6.9.3",
    "@ant-design/pro-table": "2.17.3",
- 开发环境 [e.g. mac OS]
  windows + webstorm2020
antd:  "antd": "4.9.0"
"react": "^16.8.6"
"typescript": "^4.0.3"
"eslint": "^7.1.0"

**Comment by JoyceLizhuo** [comment]
+1

**Comment by chenshuai2144** [comment]
改了，我改成了any， unknown 还是有一些限制的，更新就好了。

为你重视 typescript 点赞
