### ISSUE TITLE
Pro-Table🐛[BUG]表头夸列的情况，显示隐藏无效

### ISSUE THREAD

**Issue by xiexingen** [ant-design/pro-components#145]
### 🐛 bug 描述
当pro-table表头有合并列的情况显示隐藏列两个问题
1.没有体现出层级
2.勾选、取消勾选 表格中列一直都在

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个列配置吧

**Comment by xiexingen** [comment]
![image](https://user-images.githubusercontent.com/7939085/93407501-f3748680-f8c4-11ea-988d-53b00b4083e6.png)
配置列
const columns=[
{
      title: '个人信息',
      children: [
        {
          title: '姓名',
          dataIndex: 'name',
          width: 200,
          sorter: true,
          sortOrder: sorter.field === 'name' && sorter.order,
        },
        {
          title: '薪资(k)',
          dataIndex: 'progress',
          width: 200,
          sorter: true,
          sortOrder: sorter.field === 'progress' && sorter.order,
        },
      ],
    },
]

**Comment by rdmclin2** [comment]
![image](https://user-images.githubusercontent.com/4705237/95967200-8fe76580-0e3e-11eb-93f1-da97d0838ff2.png)

@xiexingen 再试一下呢，我这边尝试是好的呢

**Comment by xiexingen** [comment]
> ![image](https://user-images.githubusercontent.com/4705237/95967200-8fe76580-0e3e-11eb-93f1-da97d0838ff2.png)
> 
> @xiexingen 再试一下呢，我这边尝试是好的呢

是控制Pro-Table的列显示隐藏的时候

**Comment by rdmclin2** [comment]
恩，我这边尝试列显示隐藏是可以隐藏的，可以check一下这个code sandbox : https://codesandbox.io/s/competent-moore-4qrcu?file=/App.tsx

**Comment by rdmclin2** [comment]
要在列配置中显示层级的话就比较复杂了，目前的设计可能无法满足这样的需求。

**Comment by xiexingen** [comment]
看到了，可能我版本问题  相当于层级的只会显示最顶层，然后通过最顶层来控制显示隐藏

**Comment by chenshuai2144** [comment]
统一在这里吧 

https://github.com/ant-design/pro-components/issues/416
