### ISSUE TITLE
🧐[问题]ProFormDateRangePicker的placeholder，ProFormDigit的precision，ts有问题

### ISSUE THREAD

**Issue by kiana-god** [ant-design/pro-components#1451]
### 🧐 问题描述
在接入ts后，我发现有ProFormDateRangePicker和precision有点问题

### 💻 示例代码
<ProFormDateTimeRangePicker
              name="effBeginAndEnd"
              label="优惠生效日期设置"
              rules={[
                {
                  required: true,
                  message: '请设置优惠生效时间',
                },
              ]}
              fieldProps={{
                placeholder: ['请选择生效日期', '请选择截止日期'],
                // placeholder: '请选择生效日期',
              }}
              width="m"
            />

<ProFormDigit
              name="discountCnyRate"
              label="折扣金额（人民币）"
              tooltip="折扣人民币折扣率 例如：98%"
              max={100}
              placeholder="折扣金额（人民币）"
              rules={[
                {
                  required: true,
                  message: '请按提示输入折扣金额（人民币）占比',
                },
              ]}
              fieldProps={{
                // precision: false, // 不支持小数
                precision: 0, // 不支持小数
                // todo
                formatter: (value) => `${value}%`,
              }}
            />

**Comment by kiana-god** [comment]
1、在DatePicker中，placeholder的类型为： string | [string, string]
2、在ProFormDateRangePicker中placeholder类型为：placeholder?: string ;
从而导致接入 ts的时候，placeholder: ['请选择生效日期', '请选择截止日期'],会报错

3、ProFormDigit也有类似的问题？

**Comment by kiana-god** [comment]
ProFormDateRangePicker的问题解决了。placeholder不要设置在fieldProps中，直接在设置在ProFormDateRangePicker即可。
现在问题是ProFormDigit，根据官网写的：与 inputNumber 相同。它自带了一个格式化(保留 2 位小数，最小值为 0)，有需要你可以关掉它。我设置成 precision: false ，有小效果。但是ts报错

**Comment by chenshuai2144** [comment]
ts 可能没写对，你 用 filedProps 吧，我补一下类型

**Comment by chenshuai2144** [comment]
precision 不应该有有效果的，我看了一下只支持 min 和 max

**Comment by kiana-god** [comment]
> precision 不应该有有效果的，我看了一下只支持 min 和 max

那，请问如何关闭呢？

**Comment by chenshuai2144** [comment]
fieldProps={}

用这个应该可以吧

**Comment by dompling** [comment]
> fieldProps={}
> 
> 用这个应该可以吧

 fieldProps={{
            picker: 'month',
            format: 'YYYY-MM',
          }}

**Comment by chenshuai2144** [comment]
我们有专门的 month 组件，直接用那个吧
