### ISSUE TITLE
代码写死了，请支持下国际化

### ISSUE THREAD

**Issue by TivonJJ** [ant-design/pro-components#1452]
https://github.com/ant-design/pro-components/blob/deb0a08272c2b162bb34f6355fc93ddc22e02f77/packages/form/src/layouts/DrawerForm/index.tsx#L117

**Comment by chenshuai2144** [comment]
欢迎来个pr，你已经找到位置了

**Comment by chenshuai2144** [comment]
有别人支持了，

close by https://github.com/ant-design/pro-components/pull/1491
