### ISSUE TITLE
请问pro-table中boolean类型查询条件valueEnum怎么直接使用呢？🧐[问题]

### ISSUE THREAD

**Issue by starhu521** [ant-design/pro-components#1455]
### 🧐 问题描述

pro-table中，下拉选择select等查询条件，key直接以true和false，怎么设置呢？

**Comment by chenshuai2144** [comment]
```
valueEnum={{
  true:true,
  false:false
}}
```

或者用 valueType="switch"

**Comment by starhu521** [comment]
> ```
> valueEnum={{
>   true:true,
>   false:false
> }}
> ```
> 
> 或者用 valueType="switch"

都不能直接只用，boolean都会当作string读出来，只能再做转化。

**Comment by chenshuai2144** [comment]
因为 object 只支持用string 当key。如果想用boolean，就用 Map 吧

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by starhu521** [comment]
> 因为 object 只支持用string 当key。如果想用boolean，就用 Map 吧
> 
> https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Map

多谢，这个我也试过，咱们的ts应该是过不去的，boolean和reactText。
