### ISSUE TITLE
🧐[问题] ProList的高度怎么控制

### ISSUE THREAD

**Issue by Nokecy** [ant-design/pro-components#1461]

**Comment by chenshuai2144** [comment]
`style={{ height: 100 }}`

不是这样吗？

**Comment by Nokecy** [comment]
没有效果~~~

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/103460741-c2c13b80-4d53-11eb-9de1-1a607e9d124e.png)

是可以的，你是不是版本有问题
