### ISSUE TITLE
StepsForm.StepForm 设置status报错

### ISSUE THREAD

**Issue by FreeCodersix** [ant-design/pro-components#1462]
在步骤条组件里，设置status为什么会报错啊
![image](https://user-images.githubusercontent.com/33892855/103400912-c7ce9100-4b81-11eb-92da-18d8c429beff.png)
![image](https://user-images.githubusercontent.com/33892855/103400919-d1f08f80-4b81-11eb-9792-fcb26553a1a8.png)

**Comment by chenshuai2144** [comment]
status 是什么功能 ? 是指 step 的 status 吗？

| stepsProps | StepsForm 自带的 Steps 的 props，使用方式与 [antd](https://ant.design/components/steps-cn/) 相同，但是去掉了 current 和 onChange | [props](https://ant.design/components/steps-cn/#API) | - | 

你估计想要这个api

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
