### ISSUE TITLE
🐛[BUG]ProTable中添加loading属性后，查询时loading不生效

### ISSUE THREAD

**Issue by cuihq2005** [ant-design/pro-components#1464]
### 🐛 bug 描述

ProTable中如果定义了loading（false）属性，点击查询按钮时，table不显示loading图标。删除ProTable的loading属性时，能显示loading图标
```
<ProTable
        actionRef={actionRef}
        rowKey={(r) => r.id}
        loading={loading} <!--这个loading=false时，会导致查询时table不显示loading图标-->
/>
```
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

从代码上看，当前版本的action赋值如下：
```
  const action = useFetchData(
    async (pageParams) => {...},
    defaultData,
    {
      ...fetchPagination,
      loading: props.loading,
      ...
    },
  );
```
props.loading的属性会覆盖useFetchData中async操作返回的loading属性，导致table的loading不生效

另外，新版tableProps中的loading为action.loading
```
   loading: action.loading,
```
2.5.6版本为
```
loading={action.loading || props.loading}
```
不清楚为什么做这个更改，这个更改导致原先很多页面异常，希望能恢复，谢谢

**Comment by chenshuai2144** [comment]
为了受控loading，你可以用 `onLoadingChange` 使用受控的方式来使用它

**Comment by cuihq2005** [comment]
> 为了受控loading，你可以用 `onLoadingChange` 使用受控的方式来使用它
> 
> 如果不需要，最好不要控制loading，这个loading是为了让不使用 request 的用户来使用的

![image](https://user-images.githubusercontent.com/6793036/103471143-39dbeb80-4db7-11eb-9027-daaa90292c1b.png)

表单的删除、禁用操作一般都会在当前页面完成，删除、禁用过程中，我需要表单显示loading状态，查询时也需要显示loading状态。原先很容易通过action.loading和props.loading配合完成，很多页面都这样做完了。这个实现改了后，很多页面需要从新改，希望能考虑恢复原先的功能

**Comment by chenshuai2144** [comment]
那你就不需要的时候设置为了 undefined，如果该成原来的好多内部项目的 loading 就坏了。

**Comment by chenshuai2144** [comment]
那你就不需要的时候设置为了 undefined，如果该成原来的好多内部项目的 loading 就坏了。

**Comment by cuihq2005** [comment]
> 那你就不需要的时候设置为了 undefined，如果该成原来的好多内部项目的 loading 就坏了。

好久没更新了，看changelog原来2.9.0就改了，我先退回去慢慢改吧，谢谢了

**Comment by chenshuai2144** [comment]
感觉你用了一个bug，实现了一个牛逼的 featrue
