### ISSUE TITLE
🐛[BUG]@ant-design/pro-form onGetCaptcha获取不到mobile的值

### ISSUE THREAD

**Issue by hongmaoxiao** [ant-design/pro-components#1465]
### 🐛 bug 描述

@ant-design/pro-form 更新到最新版1.11.7后 onGetCaptcha获取不到mobile的值
### 📷 复现步骤

正常启动

### 🏞 期望结果
正确获取mobile的值

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]1.11.7
- umi 版本 3.3.3
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]  mac OS

**Comment by chenshuai2144** [comment]
phoneName 配置一下这个，原来写死了 phone 是个bug

**Comment by hongmaoxiao** [comment]
> phoneName 配置一下这个，原来写死了 phone 是个bug

👌

**Comment by BodhiHu** [comment]
遇到同样的问题，```phoneName```需要与手机号字段的```name```一致
