### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by cui-stack** [ant-design/pro-components#1467]
### 🧐 问题描述
手动设置查询条件，并触发查询（比如用按钮设置查询条件）

### 💻 示例代码
fromRef.current.setFieldsValue({title：‘test’}) 设置参数
actionRef.current?.reload(); 触发查询
request={(params: any) => {}
在params 里面 拿不到title 参数和数据

**Comment by chenshuai2144** [comment]
要先submit，才会被table 记住
