### ISSUE TITLE
🐛[BUG] Navbar white on overflow and mobile

### ISSUE THREAD

**Issue by elie222** [ant-design/pro-components#147]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

Sorry, I don't speak Chinese.

When the nav overflows it looks like this (on @ant-design/pro-layout 6.3.0 and 5.0.5):

![image](https://user-images.githubusercontent.com/3090527/89210301-8c2a9d80-d5c8-11ea-97ce-6d1533c57728.png)

And on mobile it looks like this (on @ant-design/pro-layout 6.3.0. It was fine on 5.0.5):

![image](https://user-images.githubusercontent.com/3090527/89210411-bb410f00-d5c8-11ea-8a13-a41a8d6a688f.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
fiexd in new version
