### ISSUE TITLE
🐛[BUG] ProCard does not work correctly in AntD dark theme mode

### ISSUE THREAD

**Issue by KrishnaPG** [ant-design/pro-components#1473]
### 🐛 bug 描述
ProCard in `dark` theme has white background

### 📷 复现步骤

1. Create a new umi based application
2. Set antd mode to `dark` as below in the umi configuration
````js
  antd: {
    dark: true,
    compact: false,
  }
````
3. Import the pro-card as below:
````js
import ProCard from '@ant-design/pro-card';

      <ProCard
        title="some title"
        headerBordered
        collapsible
        defaultCollapsed
        onCollapse={(collapse) => console.log(collapse)}
      >
        Pro Card
      </ProCard>
````
4. Run the app and you will see a white background on dark mode as shown below (you would not see the title)

![image](https://user-images.githubusercontent.com/4610831/103451072-4c85f000-4ce5-11eb-9a14-e1fcddf2278d.png)

### 🏞 期望结果

Pro Card should work nicely with the AntD dark mode. 

### 💻 复现代码

Currently, in the pro card the background is being hard coded to be white, as: https://github.com/ant-design/pro-components/blob/c9267281e09642e0c7b8c852a6f3abcb8881a2a9/packages/card/src/style/index.less#L5-L8

### © 版本信息

````js
{
    "@ant-design/icons": "^4.3.0",
    "@ant-design/pro-card": "^1.9.2",
    "@ant-design/pro-descriptions": "^1.1.2",
    "@ant-design/pro-form": "^1.10.2",
    "@ant-design/pro-layout": "^6.7.0",
    "@ant-design/pro-table": "^2.16.2",
    "@umijs/route-utils": "^1.0.33",
    "antd": "^4.9.4",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet-async": "^1.0.4",
    "react-text-annotate": "0.3.0",
    "umi": "^3.2.14",
    "umi-request": "^1.0.8",
}
````

**Comment by KrishnaPG** [comment]
Unfortunately this did not fix the issue. The background is still coming as white.

In the **dark mode** the background should be **dark** (not white).

https://github.com/ant-design/pro-components/blob/e8c69f5c1686ac5cb8ebdfc59ab0af014f43644e/packages/card/src/style/index.less#L5-L8

![image](https://user-images.githubusercontent.com/4610831/103506821-aae8d500-4e83-11eb-999b-64133086d57e.png)

**Comment by yuxiang2629** [comment]
Having the same issuse here @chenshuai2144, bug still exist

**Comment by chenshuai2144** [comment]
headerTheme | 顶部导航的主题，mix 模式生效 | light \| dark | dark
-- | -- | -- | --




try this api
