### ISSUE TITLE
ProForm如何获取数据域

### ISSUE THREAD

**Issue by shaojava** [ant-design/pro-components#1477]
使用React.createRef获取到的ref.current = null
有什么方法可以获取到ProForm的数据域

**Comment by chenshuai2144** [comment]
数据域是个什么概念？ `FormInstance` 吗？

**Comment by shaojava** [comment]
就是获取这个Form的instance可以手动调用验证方法进行表单处理

**Comment by chenshuai2144** [comment]
formRef 可以拿到，或者直接用 useForm
