### ISSUE TITLE
组件文档的国内镜像是什么🧐[问题]

### ISSUE THREAD

**Issue by DrMuda** [ant-design/pro-components#1478]
### 🧐 问题描述

https://procomponents.ant.design/ 是antd-pro的组件文档的网站，这个网站的国内镜像是什么？通过百度等方式，我只能找到https://ant-design-pro.gitee.io/，而在这个网站里又没有找到能跳转到组件文档的链接

**Comment by ccloveak** [comment]
https://procomponents.ant.design/components 这个？

**Comment by DrMuda** [comment]
@ccloveak 不是这个，这个访问速度很慢

**Comment by ccloveak** [comment]
`git clone https://github.com/ant-design/pro-components.git` 里面有个docs文件夹

**Comment by DrMuda** [comment]
@ccloveak 非常感谢，虽然这个文件夹并不是组件文档，不过我顺着这个思路在其他文件夹找到了文档
