### ISSUE TITLE
👑 [需求] 修复修改面包屑的样式separator。

### ISSUE THREAD

**Issue by chenkaixia** [ant-design/pro-components#1485]
### 🥰 需求描述
使用PageContainer组件作为页面的容器，不设置任务参数时可以自动生成面包屑，但是如果需要修改面包屑的分隔符或是修改面包屑的样式，可以设置breadcrumb属性，由于重置breadcrumb
![image](https://user-images.githubusercontent.com/8789497/103506830-a37ff680-4e98-11eb-97a9-b16858ab69d4.png)
原有组件计算的routes属性无法获取。这边是否有比较好的扩展面包屑样式的方法

**Comment by chenshuai2144** [comment]
breadcrumbRender | 自定义面包屑的数据 | (route)=>route | -
-- | -- | -- | --




有这个api 用来专门处理面包屑

**Comment by chenkaixia** [comment]
这个是哪个组件的api？breadcrumbRender ，不在PageContainer 内吧

**Comment by chenkaixia** [comment]
> breadcrumbRender	自定义面包屑的数据	(route)=>route	-
> 有这个api 用来专门处理面包屑

这个是哪个组件的api？breadcrumbRender ，不在PageContainer 内吧

**Comment by chenshuai2144** [comment]
在 ProLayout 上

**Comment by chenkaixia** [comment]
> 在 ProLayout 上
用的5.0的脚手架，没有显示映入ProLayout，如何设置这个属性

**Comment by chenshuai2144** [comment]
App.tsx里面有个layout的配置 

放到里面好了

**Comment by chenkaixia** [comment]
> App.tsx里面有个layout的配置
> 
> 放到里面好了

其实我还是不太明白这么设置
![image](https://user-images.githubusercontent.com/8789497/103514584-e39aa580-4ea7-11eb-8d8a-9bcc1d347fdc.png)
这个只是修改routes一个函数，如何修改 这个分隔符？

**Comment by chenshuai2144** [comment]
breadcrumbProps 支持了这个api，能满足你的需求
