### ISSUE TITLE
🐛[BUG]切换PageSize后，点击查询，PageSize重置为20

### ISSUE THREAD

**Issue by AmberJyh** [ant-design/pro-components#1486]
### 🐛 bug 描述

Protable查询页面中，当切换PageSize为50后，再次点击查询按钮，此时查询条件的pageSize重置为20

### 🏞 期望结果

Protable查询页面中，当切换PageSize为50后，点击查询paseSize依然为50。除非页面进行刷新，pageSize才会被重置。

### 💻 复现代码

`import React, { useRef, useState } from 'react';
import { Button } from 'antd';
import type { ProColumns } from '@ant-design/pro-table';
import ProTable from '@ant-design/pro-table';
import type { FormInstance } from 'antd/lib/form';

export type TableListItem = {
  key: number;
  name: string;
};
const columns: ProColumns<TableListItem>[] = [
  {
    title: '标题',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: '创建时间',
    key: 'since',
    dataIndex: 'createdAt',
    valueType: 'dateTime',
  },
];

export default () => {
  const ref = useRef<FormInstance>();
  const [collapsed, setCollapsed] = useState(false);
  return (
    <ProTable<TableListItem>
      columns={columns}
      request={/* 查询函数 */}
      rowKey="key"
      pagination={{
        showSizeChanger: true,
      }}
      search={{
        collapsed,
        onCollapse: setCollapsed,
      }}
      formRef={ref}
      toolBarRender={() => [
        <Button
          key="set"
          onClick={() => {
            if (ref.current) {
              ref.current.setFieldsValue({
                name: 'test-xxx',
              });
            }
          }}
        >
          赋值
        </Button>,
      ]}
      options={false}
      dateFormatter="string"
      headerTitle="表单赋值"
    />
  );
};
`

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] "@ant-design/pro-table": "2.12.0",
- umi 版本  "umi": "3.2.28",
- 浏览器环境 Google chrome 版本 87.0.4280.88
- 开发环境:windows10

**Comment by chenshuai2144** [comment]
好久之前好像有这个bug ，要不先升级版本试试

**Comment by AmberJyh** [comment]
> 好久之前好像有这个bug ，要不先升级版本试试

protable版本是2.12.0，一个月前刚升级的，也没有很久吧

**Comment by cc7gs** [comment]
> > 好久之前好像有这个bug ，要不先升级版本试试
> 
> protable版本是2.12.0，一个月前刚升级的，也没有很久吧

 #1352 要么升到v2.16.3以上 要么退到v2.12以下

**Comment by AmberJyh** [comment]
![image](https://user-images.githubusercontent.com/19634446/103747481-b253de00-503d-11eb-805a-02269844cb7e.png)
已升级到最新版本，如上图所示。但是启动后，出现如下报错，麻烦请查看。如有需要，可以重新提issue。
![image](https://user-images.githubusercontent.com/19634446/103747553-cef01600-503d-11eb-95eb-e6bee75c6e4d.png)
![image](https://user-images.githubusercontent.com/19634446/103747575-d8797e00-503d-11eb-8976-1f6337ecb4c0.png)
![image](https://user-images.githubusercontent.com/19634446/103747721-0959b300-503e-11eb-8b43-72cceda1eb91.png)

**Comment by cc7gs** [comment]
> ![image](https://user-images.githubusercontent.com/19634446/103747481-b253de00-503d-11eb-805a-02269844cb7e.png)
> 已升级到最新版本，如上图所示。但是启动后，出现如下报错，麻烦请查看。如有需要，可以重新提issue。
> ![image](https://user-images.githubusercontent.com/19634446/103747553-cef01600-503d-11eb-95eb-e6bee75c6e4d.png)
> ![image](https://user-images.githubusercontent.com/19634446/103747575-d8797e00-503d-11eb-8976-1f6337ecb4c0.png)
> ![image](https://user-images.githubusercontent.com/19634446/103747721-0959b300-503e-11eb-8b43-72cceda1eb91.png)

你升级下 antd版本吧。类似问题--> #836

**Comment by chenshuai2144** [comment]
是我的判断问题，如果 provide 版本不相同，valueTypeMap 可能为空的

**Comment by AmberJyh** [comment]
> 是我的判断问题，如果 provide 版本不相同，valueTypeMap 可能为空的

Probider具体需要什么版本呢？现在的版本配套如下，经过测试，还是有如上页面报错的问题。
    "@ant-design/pro-table": "2.22.0",
    "@ant-design/pro-field": "1.8.2",
    "@ant-design/pro-form": "1.13.5",
    "@ant-design/pro-provider": "1.4.1",
    "@ant-design/pro-utils": "1.10.1",
    "antd": "4.10.0",

**Comment by chenshuai2144** [comment]
你删掉声明 不要自己写死

**Comment by rockyxiaogang** [comment]
试试这样写
<ProTable
        headerTitle="查询新闻"
        actionRef={actionRef}
        rowKey="id"
        **pagination={{
          pageSize: 5,
        }}**
       ...
/>

**Comment by chenshuai2144** [comment]
新版已经解决，更新下依赖吧
