### ISSUE TITLE
ProTable 设置为 form 时，能否自定义提交按钮和重置？

### ISSUE THREAD

**Issue by free-D** [ant-design/pro-components#1488]
在部分需求中，有时候会选择弹出层或者Drawer，而 protable type 为form 时自带的样式文案等，可能并不是很符合，那么需要自定义一些按钮。希望可以通过设置去掉自带的按钮，或者可以重定义该按钮组

**Comment by chenshuai2144** [comment]
和proForm用法一样 ，proTable有个form的props

**Comment by free-D** [comment]
> 和proForm用法一样 ，proTable有个form的props

看到了通过submitter可以设置。

另外我尝试使用了一下其他的设置，发现不生效，目前还是不支持全部的formprops吗？ 例如layout
```
form={{
  layout: 'horizontal',
  colon: true,
  submitter: false,
}}
```

**Comment by chenshuai2144** [comment]
ts 类型支持的应该都支持的。

**Comment by chenshuai2144** [comment]
看这个 https://procomponents.ant.design/components/table#datasource

**Comment by jockey100332** [comment]
> 看这个 https://procomponents.ant.design/components/table#datasource
不支持 type='form' 时的layout，只支持默认的vertical
