### ISSUE TITLE
🧐ProTable搜索表单自定义后，请问怎么自定义查询表单的值？

### ISSUE THREAD

**Issue by yangjiaqiao** [ant-design/pro-components#1489]
### 🧐 问题描述

在ProTable - 高级表格中对搜索表单自定义，往往一个字段查询表单对应了一个组件，我自己定义组件，可以在查询字段中，多了一个表单组件，请问怎么自定义查询表单的值？

### 💻 示例代码
自定义查询表单：
![image](https://user-images.githubusercontent.com/51978469/103547747-c681c900-4edf-11eb-9519-0f67ef8a5e51.png)
这是我们自动定义的表单组件：
![image](https://user-images.githubusercontent.com/51978469/103547908-f3ce7700-4edf-11eb-8e9b-8c715efedac6.png)
实现效果：
![image](https://user-images.githubusercontent.com/51978469/103548043-2b3d2380-4ee0-11eb-87d4-c0402783718d.png)
点击查询的时候，无法获取动态展示的日期选择的值：
![image](https://user-images.githubusercontent.com/51978469/103548155-53c51d80-4ee0-11eb-92fa-24f2b02c5da9.png)
只能获取到，第一个Select组件的值

**Comment by chenshuai2144** [comment]
![Uploading image.png…]()

试试这个组件吧

**Comment by Rt821940205** [comment]
![image](https://user-images.githubusercontent.com/26640133/133540858-c01da778-dfbf-41f4-a05e-91c959e7fc39.png)
打印出来为什么第一个值会是empty

**Comment by chenshuai2144** [comment]
没设置就是空，这个是数组的表示方式，不是里面真的有值

**Comment by Rt821940205** [comment]
感谢大佬
