### ISSUE TITLE
🐛[BUG] pro-form width number 无用？

### ISSUE THREAD

**Issue by sunyonghua** [ant-design/pro-components#1498]
### 🐛 bug 描述

在文档中显示 width 的类型是 number | "xs" | "s" | "m" | "l" | "x"
实际不支持number

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/26454332/103629534-6476a180-4f7b-11eb-8bbf-d6edfd32cff3.png)

### 🏞 期望结果

期望number生效 因为默认的枚举类型不能支持特定的宽度设置

### 💻 复现代码
开发代码
```javascript
<ProFormSelect
  name={[field.name, 'var']}
  width={80}  // 无效
  // formItemProps={{ style: { width: 80 } }}
  request={requestVariable}
  rules={[{ required: true, message: '请选择变量' }]}
/>
<ProFormSelect
  name={[field.name, 'opr']}
  options={expression}
  width="xs"  // 有效
  rules={[{ required: true, message: '请选择操作符' }]}
/>
```
组件源码
![image](https://user-images.githubusercontent.com/26454332/103630417-963c3800-4f7c-11eb-9b1b-1edd9502ae1b.png)
width 类型为number的时候 类名不生效

### © 版本信息

- ProForm 版本: [e.g. 1.10.4]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
😯 用 fieldProps.width, 忘了这个 case 了，我加一下
