### ISSUE TITLE
proTable 动态赋值 valueEnum不生效

### ISSUE THREAD

**Issue by liupei1995** [ant-design/pro-components#150]
### 🐛 bug 描述

valueEnum通过接口动态赋值，没有下拉数据

### 📷 复现步骤

20200811下午3点左右重新安装了依赖，就不行了，之前是可以的

### 🏞 期望结果

可以动态赋值

### © 版本信息

"@ant-design/pro-table": "^2.0.0",

**Comment by chenshuai2144** [comment]
展示一个你的代码？

**Comment by liupei1995** [comment]
> 展示一个你的代码？
https://codesandbox.io/s/beautiful-khorana-kx9vg?file=/demo.tsx

**Comment by momo085** [comment]
同样遇到这个问题  version 2.5.4

**Comment by chenshuai2144** [comment]
https://codesandbox.io/s/empty-night-63j8j?file=/demo.tsx


测试的 demo 看起来没问题，我加了个测试用例，大家可以看看

https://github.com/ant-design/pro-components/pull/190

**Comment by liupei1995** [comment]
> https://codesandbox.io/s/empty-night-63j8j?file=/demo.tsx
> 
> 测试的 demo 看起来没问题，我加了个测试用例，大家可以看看
> 
> #190

在table里面可以展示出来，但是生成的select下拉数据没有
![微信图片_20200814105754](https://user-images.githubusercontent.com/21356797/90209262-7b2a2980-de1d-11ea-8d9c-e190ce5607ac.png)

**Comment by pandaXiong01** [comment]
我也碰到这个问题，这也没解决方案就关了？

**Comment by liupei1995** [comment]
> 我也碰到这个问题，这也没解决方案就关了？

更新版本就好了

**Comment by zhoufeii** [comment]
> > 我也碰到这个问题，这也没解决方案就关了？
> 
> 更新版本就好了

我把@ant-design/pro-table更新到最新版本了还是存在这个问题

**Comment by chenshuai2144** [comment]
那要给一个重现了！测试用例是可以过的

**Comment by drunkWindy** [comment]
请问上面的问题有解决方案

**Comment by lisong2010** [comment]
最新版本一直存在，请问怎么解决？

**Comment by cccccui** [comment]
不好意思，之前说加 await可以解决的答案，是错的。。

**Comment by cccccui** [comment]
用 useLayoutEffect  测试有效。。。。。。。。。

**Comment by yangyan123** [comment]
> https://codesandbox.io/s/empty-night-63j8j?file=/demo.tsx
> 
> 测试的 demo 看起来没问题，我加了个测试用例，大家可以看看
> 
> #190

话说你这测试用例不行呀，用你的代码都展示不出来呀
![image](https://user-images.githubusercontent.com/10812007/99971494-2f056280-2dd8-11eb-8ec6-d70ed70122b2.png)

**Comment by drunkWindy** [comment]
这种方式测试无效，请问你是怎么操作的呢



在 2020-11-21 16:06:30，"cccccui" <notifications@github.com> 写道：

用 useLayoutEffect 测试有效。。。。。。。。。

**Comment by drunkWindy** [comment]
我之前也是这么解决的，用定时器，但是我发现个问题，我定时器的时间如果设置几百ms就不行。一直没找个什么原因。请问你了解这是为什么吗？



在 2020-11-23 22:07:32，"yangyan" <notifications@github.com> 写道：

https://codesandbox.io/s/empty-night-63j8j?file=/demo.tsx

测试的 demo 看起来没问题，我加了个测试用例，大家可以看看

#190

话说你这测试用例不行呀，用你的代码都展示不出来呀

**Comment by w345731923** [comment]
const valueEnum = {};
    this.state.roleList.map((item, index) => {
      const text = item.roleName;
      valueEnum[item.roleId] = {text};
    })

      {
        title: '角色',
        dataIndex: 'roleId',
        align: 'center',
        render: (dom, record, index, action) => {
          const text = record.roleList.map((item, index) => {
            return item.roleName + ' ';
          })
          return text;
        },
        onFilter: true,
        valueType: 'select',
        valueEnum: valueEnum,
      },
