### ISSUE TITLE
EditableProTable 支持多行编辑

### ISSUE THREAD

**Issue by 38606277** [ant-design/pro-components#1501]
EditableProTable 支持多行编辑

只支持一行编辑，会降低用户的体验，有时用户想先增加自己需要的空行，再编辑。

**Comment by chenshuai2144** [comment]
现在支持多行的。
```

editable={
{   type:"multiple" }
}
```


type | 可编辑表格的类型，单行编辑或者多行编辑 | single \| multiple | -
-- | -- | -- | --
