### ISSUE TITLE
🧐[问题]proTable搜索项

### ISSUE THREAD

**Issue by zy135516** [ant-design/pro-components#1502]
### 🧐 问题描述
不需要太多的搜索项，使用hideInSearch，会报错'hideInSearch' will be deprecated, please use 'search'。是要自定义了吗？

**Comment by chenshuai2144** [comment]
`search:false`
这样配置，你可以更新一下版本

**Comment by zy135516** [comment]
> `search:false`
> 这样配置，你可以更新一下版本

已经查看文档改成这样了，谢谢
