### ISSUE TITLE
🐛[BUG]ProTable 的column.dataIndex为数组时, column的search.transform不起作用

### ISSUE THREAD

**Issue by lioaphy** [ant-design/pro-components#1504]
### 🐛 bug 描述

当ProTable 的column.dataIndex为数组时, column的search.transform不起作用

### 📷 复现步骤
const regexTransform=(value: any, field: string, object: any) => {
  console.log(field);
  return value;
}

const columns: ProColumns<any>[] = [
{ title: 'item.code', dataIndex: ['item', 'code'], sorter: true, search: { transform: regexTransform } },
]

**Comment by lioaphy** [comment]
你好,已经看到transform起作用, 但是 传进来的field只有最后一个路径. 如上面的dataIndex: ['item', 'code'], 在field中只有‘code’
对于transform的实现来说不够.

**Comment by chenshuai2144** [comment]
是个bug，跟i性能一下版本
