### ISSUE TITLE
🐛[BUG]current.reloadAndRest()只会刷新，不会重置表格页码到第一页

### ISSUE THREAD

**Issue by lanbin1017** [ant-design/pro-components#1505]
### 🐛 bug 描述

this.state.TableEl.current.reloadAndRest();只会刷新，不会重置表格页码到第一页
### 📷 复现步骤

this.state.TableEl.current.reloadAndRest();只会刷新，不会重置表格页码到第一页
### 🏞 期望结果

this.state.TableEl.current.reloadAndRest();只会刷新，不会重置表格页码到第一页
### 💻 复现代码
this.state.TableEl.current.reloadAndRest();只会刷新，不会重置表格页码到第一页

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by pangxiaolong** [comment]
确实存在这个问题， 很久了，而且现在最新版本的.current.reset()也没有清空搜索表单

**Comment by chenshuai2144** [comment]
fixed in https://github.com/ant-design/pro-components/issues/1518
