### ISSUE TITLE
🐛[BUG]ProFormCaptcha 输入了手机号 还是无法触发onGetCaptcha

### ISSUE THREAD

**Issue by BooYeu** [ant-design/pro-components#1509]
### 🐛 bug 描述

设置了phoneName属性

### 📷 复现步骤

官方ProForm Demo即可复现

### 🏞 期望结果

填写手机号后，可以触发onGetCaptcha

### 💻 复现代码

https://procomponents.ant.design/components/form/
登录示例

### © 版本信息

- ProComponents 版本: pro-from 1.13.4
- umi 版本 3.3.3
- 浏览器环境 Edge
- 开发环境 windows 10

### 🚑 其他信息

后台打印logo显示 请输入undefined

**Comment by chenshuai2144** [comment]
可以的，你是不是不合法的手机号？ 还是没加载成功

**Comment by BooYeu** [comment]
可能本地有缓存、、现在好啦～～
