### ISSUE TITLE
🧐[问题] 找不到PageHeaderWrapper的相关API

### ISSUE THREAD

**Issue by fivefog** [ant-design/pro-components#1510]
### 🧐 问题描述

问题虽简单，也很重要~ [捂脸]
在ProComponents找了一圈也没找到PageHeaderWrapper 的相关描述，搜素也木有，请问是在哪的？
```tsx
import { PageHeaderWrapper } from '@ant-design/pro-layout';
```

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/53244212/103753342-e501d480-5045-11eb-8f21-a5d535f45a6d.png)
![image](https://user-images.githubusercontent.com/53244212/103753490-0b277480-5046-11eb-9617-2df8f61fa9a2.png)

**Comment by chenshuai2144** [comment]
该名成 PageContainer 了
