### ISSUE TITLE
🐛[BUG] EditableProTable 编辑时必填校验输入中文之后还会提示必填

### ISSUE THREAD

**Issue by yybin** [ant-design/pro-components#1512]
### 🐛 bug 描述
EditableProTable 编辑时必填校验输入中文之后还会提示必填

### 📷 复现步骤
  1、字段检验规则设置为必填
  2、 输入中文，通过回车删除输入的内容触发必填校验
  3、 再次输入中文，必填校验的提示还在，输入框校验未通过

### 🏞 期望结果
修复校验

### © 版本信息

- @ant-design/pro-table  版本: [2.21.1]
- umi 2.8.7
- 浏览器环境  Chrome 版本 87.0.4280.88（正式版本） (x86_64)
- 开发环境 [ mac OS]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/12003051/103767513-bbec3e80-505b-11eb-9e4e-9e1593adefe0.png)
官网的这个案例把文案删除之后，中文输入不进去

**Comment by chenshuai2144** [comment]
是个bug，明天发布
