### ISSUE TITLE
🐛[BUG]可编辑表格，多行编辑模式，同时有新增和编辑，在保存时会莫名多一行数据

### ISSUE THREAD

**Issue by zbl400** [ant-design/pro-components#1513]
### 🐛 bug 描述

使用可编辑表格，配置为多行编辑，如果同时有新增行，及编辑行，在保存编辑行时，表格数据条数会多一行，多的一行即编辑行的编辑前数据

### 📷 复现步骤
1. 使用文档样例
2. 配置为多行编辑 type: 'multiple',
3. 新增一行（先不保存）
4. 点击前一行的编辑按钮
5. 编辑并保存 步骤4 的编辑行，此时会多一行

### 🏞 期望结果
保存后数据行数不变，数据内容为更新后的数据

### 💻 复现代码

https://codesandbox.io/s/zidingyikebianjibiaoge-forked-6h3vw?file=/App.tsx

### © 版本信息

- ProComponents 版本: pro-table@2.21.1
- umi 版本
- 浏览器环境： chrome 87， edge 87
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/2020731/103767913-75e3aa80-505c-11eb-96b8-fb55281b3302.png)

![image](https://user-images.githubusercontent.com/2020731/103768011-a9bed000-505c-11eb-9e93-74a07b913732.png)

**Comment by chenshuai2144** [comment]
string 和 number 的问题，已经解决
