### ISSUE TITLE
🐛[BUG] ProFormText 组件 先输入数字在输入中文，中文无法输入，然后此输入不能输入任何内容了

### ISSUE THREAD

**Issue by cuoluanleshiguang** [ant-design/pro-components#1514]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
修复了，明天早上发版本，不同的浏览器事件顺序不以言
