### ISSUE TITLE
How to create menu combine sub menu and group menu in antd prolayout

### ISSUE THREAD

**Issue by AimerX** [ant-design/pro-components#1519]
I need to create a menu combine SubMenu and Menu.Itemgroup like ant design menu.
Example: https://codesandbox.io/s/gfsvw
With umi, at defaultSettings, only type 'sub' or ' group' can be set to menu type, in routes.ts and  interface MenuDataItem.  I can't find the attribute specified for menu type
I need help.
Sorry for my English. I hope you can understand my issue.
Thank you

**Comment by chenshuai2144** [comment]
We do not support mixed use at this time, only ItemGroup or subItem

If you are interested you can create a pr
