### ISSUE TITLE
🐛[BUG] pro-form的ProFormText必填项校验问题

### ISSUE THREAD

**Issue by Augustzyh** [ant-design/pro-components#1520]
### 🐛 bug 描述

线上proform输入框ProFormText必填选项无法校验中文输入，本地没有问题

### 📷 复现步骤

随便找一个必填输入框-》随便输入内容-》手动逐次清空至校验出现-》输入中文-》两种错误随机出现：1、无法输入，不触发onChange；2、可以输入但校验不会通过，删除一个字符或添加英文字符则触发校验

### 🏞 期望结果

可输入中文且通过校验

### 💻 复现代码

https://procomponents.ant.design/changelog/pro-form
官方demo即可

### © 版本信息

- ProComponents 版本: @ant-design/pro-form@1.13.4
- umi 版本: @3.3.3
- 浏览器环境: any
- 开发环境 development

**Comment by Augustzyh** [comment]
![image](https://user-images.githubusercontent.com/38031220/103841471-9f3d1e80-50ce-11eb-985d-e4e0cfd6d258.png)
好像就是这几次发版出的问题，但是没看到相关修改。。。。陈帅兄麻烦看一下

**Comment by Augustzyh** [comment]
官方是无法输入
![image](https://user-images.githubusercontent.com/38031220/103841744-4326ca00-50cf-11eb-9912-8b202b1f597c.png)
我发到线上是输入不校验：
![image](https://user-images.githubusercontent.com/38031220/103841783-589bf400-50cf-11eb-821c-85971bfa21ac.png)
但是本地没有问题：
![image](https://user-images.githubusercontent.com/38031220/103841805-66517980-50cf-11eb-8cb0-c0a06f763c24.png)

**Comment by Augustzyh** [comment]
。。。
🐛 fix(form): add footer warning #1469 @chenshuai2144
https://github.com/ant-design/pro-components/pull/1469
好像是这个提交，导致formRef没有链接上

**Comment by chenshuai2144** [comment]
版本已经发布了，是因为事件执行顺序的问题，重新发布一下线上

**Comment by Augustzyh** [comment]
多谢
