### ISSUE TITLE
🐛[BUG] pro-table v2.17.0+ search.defaultColsNumber不工作

### ISSUE THREAD

**Issue by meyerlee** [ant-design/pro-components#1521]
### 🐛 bug 描述

v2.12.0， 设置search.defaultColsNumber=7，会搜索条件会有两行，显示7个控件。
现在测试下来 v2.17.3 以上的版本会只出一行。
几乎试过了 2.17.3+ 以上的所有版本都不行

2.17.3 以下的版本 onFilter或pageSize不工作，我都不能用。就没有试。

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/8414971/103841584-e1666000-50ce-11eb-9952-11bc855d4701.png)

![image](https://user-images.githubusercontent.com/8414971/103841649-078c0000-50cf-11eb-9104-4a67b3aca998.png)

**Comment by chenshuai2144** [comment]
要不升级到最新版本吧，我试了一下不会的

**Comment by meyerlee** [comment]
尝试了新鲜出炉的V2.22.0，貌似没有解决

sample code
`import { PageHeaderWrapper } from '@ant-design/pro-layout';
import ProTable from '@ant-design/pro-table';
import React from 'react';

const EditTable: React.FC = () => {
  const props = {
    size: 'small',
    bordered: true,
    manualRequest: true,
    form: {
      colon: false,
    },
    columns: [
      {
        dataIndex: 'c1',
        title: 'Table No',
        valueType: 'text',
        key: 'c1',
      },
      {
        dataIndex: 'c2',
        title: 'Table No',
        valueType: 'text',
        key: 'c2',
      },
      {
        dataIndex: 'c3',
        title: 'Table No',
        valueType: 'text',
        key: 'c3',
      },
      {
        dataIndex: 'c4',
        title: 'Table No',
        valueType: 'text',
        key: 'c4',
      },
      {
        dataIndex: 'c5',
        title: 'Table No',
        valueType: 'text',
        key: 'c5',
      },
      {
        dataIndex: 'c6',
        title: 'Table No',
        valueType: 'text',
        key: 'c6',
      },
      {
        dataIndex: 'c7',
        title: 'Table No',
        valueType: 'text',
        key: 'c7',
      },
      {
        dataIndex: 'c8',
        title: 'Table No',
        valueType: 'text',
        key: 'c8',
      },
      {
        dataIndex: 'c9',
        title: 'Table No',
        valueType: 'text',
        key: 'c9',
      },
    ],

    search: {
      defaultColsNumber: 5,
    },
  };

  return (
    <PageHeaderWrapper title={false}>
      <ProTable {...props} />
    </PageHeaderWrapper>
  );
};

export default EditTable;
`


![image](https://user-images.githubusercontent.com/8414971/103856177-31551f00-50ef-11eb-9e83-52da5b4b52a8.png)

**Comment by chenshuai2144** [comment]
只测试了比默认的小的数字，没有测试比默认的大的，翻车了
