### ISSUE TITLE
🧐[问题] 想咨询一下类似支持模糊搜索的 select 在不在该项目的范围

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/pro-components#1526]
### 🧐 问题描述

pro-components 我理解是 antd 的增强和扩展，antd 中的大量的实用性 demo 是不是可以有机会的集成进来

### 💻 示例代码

传递 searchable 开启模糊搜索

```tsx
<ProField valueType='select' searchable request={serviceA} /> 
```

**Comment by chenshuai2144** [comment]
`<ProField valueType='select'  fieldProps={{searchable : true}} request={serviceA} /> `

这样写就透传了，

![image](https://user-images.githubusercontent.com/8186664/103873487-d3cecb80-510a-11eb-95fb-d735936ccc2f.png)
