### ISSUE TITLE
🐛[BUG]EditableProTable设置 valueType: 'money',输入后输出错误

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#1528]
### 🐛 bug 描述
代码：
![image](https://user-images.githubusercontent.com/12421552/103858605-9e6ab380-50f3-11eb-8af3-d2926e98fad3.png)

![image](https://user-images.githubusercontent.com/12421552/103858653-b3474700-50f3-11eb-84a9-6e297513ab86.png)

![image](https://user-images.githubusercontent.com/12421552/103858697-c78b4400-50f3-11eb-82a0-afbe0823f3c9.png)

这时候计提费用基数为空，我输入一次1，他会输出11

![image](https://user-images.githubusercontent.com/12421552/103858758-dd990480-50f3-11eb-9b38-40d9323a085d.png)

**Comment by chenshuai2144** [comment]
没有复现，先升级依赖到最新版本吧

**Comment by edifangyi** [comment]
@chenshuai2144 还是有问题，使用的最新版的   "@ant-design/pro-table": "^2.22.1",，，在我的项目里直接复制Demo，会重现

**Comment by edifangyi** [comment]
@chenshuai2144 ![image](https://user-images.githubusercontent.com/12421552/104116757-7cbd3680-5356-11eb-971c-51ed70c30592.png)

我使用 Demo 页面的网页输入也会这样个样子，使用了干净的浏览器，无任何多余插件

**Comment by chenshuai2144** [comment]
我是不会的，你是用了输入法吗？

**Comment by edifangyi** [comment]
@chenshuai2144 哈，莫名其妙的又好了~谢谢
