### ISSUE TITLE
🧐[问题]pro-table查询区域内背景会随着输入框高度的增加而增加，如何解决？？

### ISSUE THREAD

**Issue by HdjPoppy** [ant-design/pro-components#1529]

**Comment by chenshuai2144** [comment]
来个实例有点没看懂

**Comment by HdjPoppy** [comment]
就是这个样子





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "陈帅"<notifications@github.com&gt;; 
发送时间: 2021年1月7日(星期四) 下午5:20
收件人: "ant-design/pro-components"<pro-components@noreply.github.com&gt;; 
抄送: "Loli Poppy"<1059232133@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ant-design/pro-components] 🧐[问题]pro-table查询区域内背景会随着输入框高度的增加而增加，如何解决？？ (#1529)





 
来个实例有点没看懂

**Comment by chenshuai2144** [comment]
等别的同学碰到问题再看把，太抽象了

**Comment by HdjPoppy** [comment]
样式问题而已  默认那隐藏在table下面搞了个层级------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;陈帅&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月7日(星期四) 晚上7:08
收件人:&nbsp;&quot;ant-design/pro-components&quot;<pro-components@noreply.github.com&gt;;
抄送:&nbsp;&quot;HdjPoppy&quot;<1059232133@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 🧐[问题]pro-table查询区域内背景会随着输入框高度的增加而增加，如何解决？？ (#1529)

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
