### ISSUE TITLE
👑 [需求] 希望tableAlertRender再暴露个onSelected

### ISSUE THREAD

**Issue by xch1029** [ant-design/pro-components#1531]
### 🥰 需求描述

暴露onSelected后，就可以自行控制选中项了，目前暴露的onCleanSelected可以看做是onSelected的一个子集

### 🧐 解决方案

第一步：Table.tsx的index.tsx 438行加一行 onSelected={rowSelection.onChange}

![企业微信截图_1610006965998](https://user-images.githubusercontent.com/20165584/103867841-f957d700-5102-11eb-9795-09dedbe964c7.png)

第二步：Alert的index.tsx 62行传入onSelected字段

![企业微信截图_1610006978116](https://user-images.githubusercontent.com/20165584/103867823-f3fa8c80-5102-11eb-9c28-a2d2a31eda90.png)

### 🚑 其他信息

actionRef是不是也应该暴露下onSelected

**Comment by chenshuai2144** [comment]
onSelected 这个功能具体是用来做什么的？

**Comment by xch1029** [comment]
> onSelected 这个功能具体是用来做什么的？可以展开描述一下吗？

主要就是为了在tableAlertRender中控制选中项，大概是这样：

```
    <ProTable
          tableAlertRender={({ selectedRowKeys, selectedRows, onCleanSelected, onSelected }) => (
            <Space>
              <span>已勾选本页 25 封邮件</span>
              <Button
                onClick={async () => {
                  // TODO: 获取全部的数据，再调用onSelected以选中所有项
                  const allData = await queryAllData();
                  const allKeys = allData.map(({ key }) => key);
                  
                  onSelected(allKeys, allData);
                }}
              >
                勾选"收件箱"中全部 3321 封邮件
              </Button>
            </Space>
          )}
    />
```

其实我是想实现类似QQ邮箱的全选功能，你看看是否合适
![QQ截图20210107172754](https://user-images.githubusercontent.com/20165584/103875674-b18a7d00-510d-11eb-8235-1fe6e09c9cd9.png)

**Comment by xch1029** [comment]
你对全选所有数据有什么好的实践吗，通过rowSelection来写受控组件吗

**Comment by chenshuai2144** [comment]
不建议这么实现，你应该用 rowSelection 来实现，不然就不受控了

**Comment by xch1029** [comment]
> 不建议这么实现，你应该用 rowSelection 来实现，不然就不受控了

好的
