### ISSUE TITLE
🧐[问题]renderFormItem自定义表单项监听onChange

### ISSUE THREAD

**Issue by SilentFlute** [ant-design/pro-components#1535]
### 🧐 问题描述
首先感谢你们提供了那么好用的react的组件, 我在上家公司用antd(没用pro-components)从0到1重构了一个用了4-5年的jq+jsp的管理后台, 感受及收获颇丰, 现在新单位也需要做个管理后台, 我接手的是一个离职的人写的, 写了一部分, 然后我接着迭代, 同时他里面使用了pro-components, pro-table封装了查询表单和下方的表格, 比之前自己用antd封装方便多了
他在页面上使用的是function component, 我个人不喜欢在顶级页面使用function component, 只喜欢在展示型的组件或者逻辑比较简单的组件中使用function component, 因此我在顶级页面使用了class组件, 但同样的功能我却, 没法在renderFormItem渲染的组件中监听onChange(他在function component中监听onChange成功了)

### 💻 示例代码
首先是我的代码:
页面:
![image](https://user-images.githubusercontent.com/28900312/103869245-0675c580-5105-11eb-8744-a0acdff94e70.png)
以状态这个单选按钮为例:
组件render方法:
![image](https://user-images.githubusercontent.com/28900312/103870149-49846880-5106-11eb-950f-204c38c0f1ff.png)
由于页面上有多于一个数据来源, 因此我在所有数据请求完毕之后才渲染表格
状态单选按钮的columns:
![image](https://user-images.githubusercontent.com/28900312/103869436-4046cc00-5105-11eb-9ad8-68e055055c4c.png)
我在onChange的时候去设置表单项的值, 但这样写页面上的按钮点击之后不会发生变化, 点击之后renderFormItem不会执行!
但当我把renderFormItem中返回的组件中的value和onChange删掉之后则一切正常: 按钮点击之后会有选中的变化, 以及renderFormItem也被执行了, 我看了renderFormItem的声明文件, 里面提到"返回一个node，会自动包裹 value 和 onChange", 但我理解我覆盖了value和onChange, 而且onChange里面还用form设置了表单项的值, onChange也确实是执行了, 为何不起作用呢?
以及我把这个value放到了state中, onChange里面setState了依旧不行!
主要我这里需要监听onChange, 在单选按钮变更的时候去请求数据
以及我翻issue的时候看到了这个问题: #167, 让我醍醐灌顶, 但试了之后我发现renderFormItem的第二个参数里面并没有onChange, 以及其他相关的issue我也看了, 大家都是用的function component的写法, 和我这个不是太符合, 我改成fc的形式也行, 但这个问题实在是让我比较好奇, 也让我摸不着头脑, 故恳请解答
那个离职的同事的代码如下:
他没有用class而是用的function component, 以及他页面的数据源就一个, 使用了ProTable的request, 我所有的操作需要自己处理
![image](https://user-images.githubusercontent.com/28900312/103870459-b1d34a00-5106-11eb-8921-479edd01a104.png)
![image](https://user-images.githubusercontent.com/28900312/103870482-bc8ddf00-5106-11eb-9a45-7b7f976c5249.png)
他的这个写法就完全没问题
而且我还发现, 他拿到的formRef和我拿到的formRef不一样, 他的有current这个字段, 而我的没有, 不过他是用的react的useRef获得的, 我是传了一个方法进去, 将该方法参数中获得的formRef赋值给一个变量
希望能得到大佬的帮助, 再次感谢
### 🚑 其他信息
```
    win10系统
    node版本v12.16.3
    "@ant-design/icons": "^4.3.0",
    "@ant-design/pro-layout": "^6.10.2",
    "@ant-design/pro-table": "^2.20.1",
    "antd": "^4.10.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "umi": "^3.2.0",
```

**Comment by SilentFlute** [comment]
@chenshuai2144 手动召唤大佬

**Comment by chenshuai2144** [comment]
你的文字好多，看的我好累。

你把你要自定义的组件抽象一下把。做成一个临时组件。


```
const MyGourp = ({value,onChange,form}=>{
   return <Ridio.Group onChaneg={ (e)=>{
         // do something
        onChange(e);
     } }/>
}

```

**Comment by SilentFlute** [comment]
@chenshuai2144 哈哈哈, 好嘛, 下次我言简意赅点, 我看了下文档中fieldProps的用法, 然后我在代码中使用如下, 可是config中没有fieldProps啊, 是怎么回事:
![image](https://user-images.githubusercontent.com/28900312/103877704-658d0780-5110-11eb-9a29-1cd36d3ebf07.png)
![image](https://user-images.githubusercontent.com/28900312/103877916-aedd5700-5110-11eb-9986-e7ff1113f77b.png)
是哪里没写对吗?求指点

**Comment by chenshuai2144** [comment]
那个会自动注入的，不是显式的使用

**Comment by SilentFlute** [comment]
@chenshuai2144 哦, 好的, 了解了, 我试了下, 可以了, 点击按钮按钮做了相应的变化, 同时这个fieldProps里的onChange还执行了, 但为何点击按钮的时候这个onChange会执行两遍呢?是我哪里没写对吗?

**Comment by SilentFlute** [comment]
用你说的第一种方法倒是只会执行一次, 求指点:
![image](https://user-images.githubusercontent.com/28900312/103965603-0c1ceb00-5199-11eb-98b9-df352fc8f7a0.png)

**Comment by chenshuai2144** [comment]
看起来是个 bug，被触发了凉席

**Comment by SilentFlute** [comment]
@chenshuai2144 哦哦, 好嘛
另外还要再麻烦你帮忙看一下, 单选按钮是ok了, 但是多选的select有问题, 多选select现在成单选了, 我点选一项, 然后下拉列表就会立刻收起来
![image](https://user-images.githubusercontent.com/28900312/103971262-062d0700-51a5-11eb-94f7-7c2b286f51d5.png)

**Comment by chenshuai2144** [comment]
哥哥呀，不要在方法里重新定义组件，每次render 都会销毁你的组件的

**Comment by SilentFlute** [comment]
> 哥哥呀，不要在方法里重新定义组件，每次render 都会销毁你的组件的

哈哈哈, 好嘛, 厉害, 大佬就是大佬, 一眼就看出问题所在, 学到了, 再次感谢

**Comment by 0x219** [comment]
@chenshuai2144  好像直接render组件也会卸载的

**Comment by SilentFlute** [comment]
@0x219 定义在外部, 使得父组件re-render的时候你定义的组件不会被重新定义即可, 然后就能解决这个问题了

**Comment by 0x219** [comment]
> @0x219 定义在外部, 使得父组件re-render的时候你定义的组件不会被重新定义即可, 然后就能解决这个问题了

明白你的意思了

**Comment by 0x219** [comment]
> @0x219 定义在外部, 使得父组件re-render的时候你定义的组件不会被重新定义即可, 然后就能解决这个问题了

头秃。有些可以，有些不行
