### ISSUE TITLE
🐛[BUG]ProTable 右上角工具栏图标 鼠标在图标边缘位置点击 虽然出现hover效果，但是无法触发单击事件

### ISSUE THREAD

**Issue by ty-bt** [ant-design/pro-components#1536]
### 🐛 bug 描述

ProTable 右上角工具栏图标 鼠标在图标边缘位置点击 虽然出现hover效果，但是无法点击

### 📷 复现步骤

https://procomponents.ant.design/components/table/
鼠标移动到齿轮图标边缘位置，刚好可以触发hover效果的位置
单击

### 🏞 期望结果
正常触发单击

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
真列文虎克！
