### ISSUE TITLE
🧐[问题]相互依赖的表单默认值

### ISSUE THREAD

**Issue by Mustard404** [ant-design/pro-components#1547]
### 🧐 问题描述

官方样例中，相互依赖的表单可以根据输入内容修改其他的title，想根据输入的内容生成默认值。

### 💻 示例代码

https://codesandbox.io/s/shy-haze-ou02q?file=/App.tsx

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/14071947/103961763-26060000-5190-11eb-8a3f-27501997d344.png)
想将inpu1的内容作为input2的默认值，查看官方说明不能用initialValues作为动态更新，只能使用setFieldsValue。
希望帮忙写个例子供参考

**Comment by chenshuai2144** [comment]
这个太黑了，为什么会需要这个功能？

**Comment by Mustard404** [comment]
![image](https://user-images.githubusercontent.com/14071947/103967469-088b6300-519d-11eb-9045-b10efb2b72f9.png)
我想通过选择漏洞类型去联动漏洞名称及修复建议，减少使用者的输入及增加修复建议的规范性，同时还能对默认值进行修改

**Comment by chenshuai2144** [comment]
onChange 时 setState 吧
