### ISSUE TITLE
🐛[BUG] ProTable 有横向滚动条时，滚动条拖动到最后，右侧阴影不会消失

### ISSUE THREAD

**Issue by ty-bt** [ant-design/pro-components#1548]
### 🐛 bug 描述
ProTable 有横向滚动条时，滚动条拖动到最后，右侧阴影不会消失

### 📷 复现步骤
https://codesandbox.io/s/quizzical-germain-91c6f?file=/App.tsx
ProTable 有横向滚动条时，滚动条拖动到最后，右侧阴影不会消失

### 🏞 期望结果
滚动条拖动到最后，阴影消失

### 💻 复现代码

https://codesandbox.io/s/quizzical-germain-91c6f?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/103967438-f7425680-519c-11eb-93b9-81d3ccadf30c.png)

？？？

**Comment by ty-bt** [comment]
@chenshuai2144  好像又是放大的问题 
![image](https://user-images.githubusercontent.com/7368072/103968005-1a213a80-519e-11eb-89b0-43767a46bc7c.png)
放大125%后，吧浏览器窗口调小，滚动条拉到最后面，然后拉宽浏览器，某些大小就会出现阴影

**Comment by chenshuai2144** [comment]
这种的，提给 antd 吧，听起来没法解决
