### ISSUE TITLE
🐛[BUG]表格defaultExpandAllRows为ture的配置失效

### ISSUE THREAD

**Issue by oldturkey** [ant-design/pro-components#1549]
### 🐛 bug 描述
表格无法配置默认展开defaultExpandAllRows为ture的配置失效
https://codesandbox.io/s/agitated-shockley-9mfyi

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
ProTable 的 request 和 defaultExpandAllRows 有冲突，你必须要要设置 dataSource 才能使用 defaultExpandAllRows
