### ISSUE TITLE
🐛[BUG] 最新版ProTable Columns如果不加dataIndex会默认在最左侧

### ISSUE THREAD

**Issue by Lnncoco** [ant-design/pro-components#155]
### 🐛 bug 描述
Columns有的时候不一定是用单一字段需要多个字段处理加工，没有填写dataIndex，旧版会正常排序并渲染，新版会默认顶在最左侧。
同时，不加dataIndex的时候，使用renderText则不会执行renderText里面代码，使用render是会如预期执行（但列显示是在最左侧），加上dataIndex属性则都正常

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个列配置，或者给个最小的重现

**Comment by Lnncoco** [comment]
> 来个列配置，或者给个最小的重现

https://codesandbox.io/s/sad-turing-yq2w1?file=/demo.tsx

ProTable的codesandbox预览中没有加proTable依赖，默认点开是报错的

**Comment by Lnncoco** [comment]
![image](https://user-images.githubusercontent.com/57341815/90098317-8708e380-dd6a-11ea-8f19-8b42a999e3a3.png)
补个图

**Comment by chenshuai2144** [comment]
fixed
