### ISSUE TITLE
👑 [需求] 对ProTable的rowSelection再扩充一个字段: onCleanSelected

### ISSUE THREAD

**Issue by xch1029** [ant-design/pro-components#1550]
### 🥰 需求描述

actionRef上面的很多方法在内部都调用了onCleanSelected方法，外层业务代码需要对其进行监听：

```
<ProTable 
    rowSelection={{
        onCleanSelected: () => {console.log('清空选中项')}
    }}
/>
```
这么做的目的是因为在实现‘跨页选择功能’时，仅使用rowSelection.onChange无法判断是否调用了'取消全部选中'
### 🧐 解决方案

修改Table.tsx的202行：

```
  /** 清空所有的选中项 */
  const onCleanSelected = useCallback(() => {
    propsRowSelection?.onChange?.([], [])
    propsRowSelection?.onCleanSelected?.()
    setSelectedRowsAndKey([], []);
  }, [propsRowSelection, setSelectedRowsAndKey]);
```

**Comment by chenshuai2144** [comment]
rowSelection 可以判断的。如果 keys =[], 就是清空选中项，增加多余的 api 意义不大，在一个api 里处理就好了

**Comment by xch1029** [comment]
> rowSelection 可以判断的。如果 keys =[], 就是清空选中项，增加多余的 api 意义不大，在一个api 里处理就好了

 keys =[]只能说明是当前页面清空了，不能代表selectedRowKeys是空的，这不就是跨页全选的特点嘛

**Comment by chenshuai2144** [comment]
selectedRowKeys  应该就是你选中的所有 keys，无论是否跨页

**Comment by xch1029** [comment]
> selectedRowKeys 应该就是你选中的所有 keys，无论是否跨页

https://ant.design/components/table-cn/#rowSelection
rowSelection.onChange的第一个参数确实只是当前页的选中项，你可以验证下onChange. 我真觉得需要这个钩子，不仅对于我而言

**Comment by xch1029** [comment]
算了，我换种思路吧，邮箱发起来不太好沟通。谢谢你的解答！
