### ISSUE TITLE
🐛[BUG]ProFormSelect组件的onSearch失效

### ISSUE THREAD

**Issue by zy135516** [ant-design/pro-components#1552]
### 🐛 bug 描述
ProFormSelect组件上设置showSearch={true}， onSearch回调不触发

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
`fieldProps`

![image](https://user-images.githubusercontent.com/8186664/103990130-b281e400-51cb-11eb-88d1-7fa6dea718a7.png)
