### ISSUE TITLE
🧐[问题]VSCode下提示错误但是可以build

### ISSUE THREAD

**Issue by leonkong** [ant-design/pro-components#1553]
### 🧐 问题描述
使用ProFormText,ProFormDateRangePicker等组件在VSCode报错，但是可以正常编译。

![image](https://user-images.githubusercontent.com/26429579/103987097-dc84d780-51c6-11eb-8514-64c96eee7065.png)
![image](https://user-images.githubusercontent.com/26429579/103987838-0ee30480-51c8-11eb-833d-fea69c460f68.png)

错误提示
Type '{ width: string; name: string; label: string; }' is missing the following properties from type 'Pick<any, "children" | "width" | "className" | "id" | "name" | "prefixCls" | "style" | "extra" | "label" | "hidden" | "placeholder" | "onReset" | "validateTrigger" | "preserve" | ... 37 more ... | "status">': children, className, id, prefixCls, and 45 more.
Type '{ width: string; label: string; name: string; placeholder: string; }' is missing the following properties from type 'Pick<any, "children" | "width" | "className" | "id" | "name" | "prefixCls" | "style" | "extra" | "label" | "hidden" | "placeholder" | "onReset" | "validateTrigger" | "preserve" | ... 37 more ... | "status">': children, className, id, prefixCls, and 44 more.
### 🚑 其他信息
macOS: 10.15.7
VSCode Version: 1.52.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0

antdesign等版本
@ant-design/pro-form: 1.13.5
antd: 4.6.4,
react: 16.13.1

**Comment by chenshuai2144** [comment]
给一下 hover 之后的截图，看起来像是 必填的属性没有天

**Comment by leonkong** [comment]
![image](https://user-images.githubusercontent.com/26429579/104000799-bc124880-51d9-11eb-99ba-4b21e3be58f3.png)

**Comment by chenshuai2144** [comment]
看报错是说有变量没有使用，是不是更新一下依赖

**Comment by leonkong** [comment]
找到问题了，antd的版本需要升级，原来我是4.4.0。理论上需要升到4.8.6之上

**Comment by birdycn** [comment]
> 找到问题了，antd的版本需要升级，原来我是4.4.0。理论上需要升到4.8.6之上

我已经是^4.10.3了，依然提示这个错误

**Comment by leonkong** [comment]
> > 找到问题了，antd的版本需要升级，原来我是4.4.0。理论上需要升到4.8.6之上
> 
> 我已经是^4.10.3了，依然提示这个错误

我这也是这个，是没有问题的。你看看是不是其他依赖库的问题，我发下我这package.json

"dependencies": {
    "@ant-design/compatible": "^1.0.4",
    "@ant-design/icons": "^4.2.1",
    "@ant-design/pro-form": "^1.13.5",
    "@ant-design/pro-layout": "^6.0.0",
    "@ant-design/pro-table": "^2.4.4",
    "@antv/data-set": "^0.11.0",
    "@antv/l7-react": "^2.1.9",
    "@types/lodash.debounce": "^4.0.6",
    "@types/lodash.isequal": "^4.5.5",
    "antd": "^4.10.2",
    "array-move": "^3.0.1",
    "bizcharts": "^3.5.9",
    "bizcharts-plugin-slider": "^2.1.1-beta.1",
    "classnames": "^2.2.6",
    "dva": "^2.4.0",
    "gg-editor": "^2.0.2",
    "lodash": "^4.17.19",
    "lodash-decorators": "^6.0.0",
    "lodash.debounce": "^4.0.8",
    "lodash.isequal": "^4.5.0",
    "mockjs": "^1.0.1-beta3",
    "moment": "^2.27.0",
    "numeral": "^2.0.6",
    "nzh": "^1.0.3",
    "omit.js": "^1.0.2",
    "path-to-regexp": "2.4.0",
    "prop-types": "^15.5.10",
    "qs": "^6.9.4",
    "react": "^16.8.6",
    "react-audio-player": "^0.13.0",
    "react-dom": "^16.8.6",
    "react-fittext": "^1.0.0",
    "react-helmet-async": "^1.0.6",
    "react-player": "^1.15.3",
    "react-router": "^4.3.1",
    "react-sortable-hoc": "^1.11.0",
    "umi": "^3.2.0",
    "umi-request": "^1.3.5",
    "use-merge-value": "^1.0.2"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^1.0.22",
    "@types/classnames": "^2.2.7",
    "@types/express": "^4.17.7",
    "@types/history": "^4.7.7",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.158",
    "@types/qs": "^6.9.4",
    "@types/react": "^16.9.43",
    "@types/react-audio-player": "^0.11.0",
    "@types/react-dom": "^16.9.8",
    "@types/react-helmet": "^5.0.16",
    "@umijs/fabric": "^2.2.2",
    "@umijs/plugin-blocks": "^2.2.1",
    "@umijs/preset-ant-design-pro": "^1.2.2",
    "@umijs/preset-react": "^1.5.19",
    "@umijs/preset-ui": "^2.2.2",
    "carlo": "^0.9.46",
    "chalk": "^4.1.0",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "enzyme": "^3.11.0",
    "eslint": "^7.1.0",
    "express": "^4.17.1",
    "gh-pages": "^3.0.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.2.11",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.0.5",
    "pro-download": "1.0.1",
    "puppeteer-core": "^4.0.1",
    "stylelint": "^13.6.1"
  },
