### ISSUE TITLE
protable column render 导致项目无法启动🐛[BUG]

### ISSUE THREAD

**Issue by Cooolyu** [ant-design/pro-components#1554]
### 🐛 bug 描述
列表中的值需要转换成icon，使用render后，导致项目无法启动
### 💻 复现代码

`            one.render = (_, record) => {
              if (record[columnTable[columnIndex].column]) {
                return <CheckOutlined />;
              }
              return <CloseOutlined />;
            };
`

### © 版本信息

- pro-table@^2.21.1
- @umijs/ast@3.3.3

### 🚑 其他信息

![02](https://user-images.githubusercontent.com/16718459/103993216-38079300-51d0-11eb-988c-2db696f00703.png)

**Comment by chenshuai2144** [comment]
看起来是简单地语法错误

**Comment by Cooolyu** [comment]
我知道提示的是语法错误，但是官网给的例子也是这样写的
![image](https://user-images.githubusercontent.com/16718459/104141065-bb52ff80-53ef-11eb-877e-c08ad89a9217.png)

**Comment by chenshuai2144** [comment]
官网的是labels 是个数组，你们的数据不是数组吧
