### ISSUE TITLE
🧐[问题] ModalForm 中我要怎么把底部的取消和确认按钮去掉

### ISSUE THREAD

**Issue by 520dong** [ant-design/pro-components#1556]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/52030677/104001118-288d4780-51da-11eb-968e-e4a4ab8d6147.png)

下面这里添加
modalProps={{
          footer: null
        }}
这个没用
![image](https://user-images.githubusercontent.com/52030677/104001384-89b51b00-51da-11eb-8397-343733aa7f08.png)

**Comment by chenshuai2144** [comment]
ModalForm 是个form，新版本有了提示了。你可以使用 `submiter.render=false`
