### ISSUE TITLE
👑 [需求]还能继续优化这几个组件的大小吗？

### ISSUE THREAD

**Issue by ghost** [ant-design/pro-components#1557]
### 🥰 需求描述
发现仅仅使用pro-form和pro-layout，parsed size 就超过了400kb了，快赶上ant-design.min.js的一半大小了。我没看源码，但我想知道这两个组件还有优化的空间吗？

**Comment by chenshuai2144** [comment]
有了treeshaking 不应该这么大的，你给我看看你的截图

**Comment by shx996** [comment]
![image](https://user-images.githubusercontent.com/45812479/104148364-f6aff700-540c-11eb-80d3-013bf896c9de.png)
![image](https://user-images.githubusercontent.com/45812479/104148372-fe6f9b80-540c-11eb-848a-a96aa810c1b5.png)

**Comment by shx996** [comment]
我上传了发现显示不出来，pro-layout+pro-form，排除一些依赖的东西，parsed size 也有370kb

**Comment by chenshuai2144** [comment]
看样子没有 treeshaking，好多没用的东西也被引入了

**Comment by chenshuai2144** [comment]
treeshaking 是自动的，我想办法优化一下

**Comment by shx996** [comment]
好的

**Comment by shx996** [comment]
请问下进展如何？

**Comment by chenshuai2144** [comment]
小了几十 k， 还是继续优化
