### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by 1257960069** [ant-design/pro-components#1558]
### 🧐 问题描述
react中使用了antd的紧凑主题,但是跳转到antd-pro-table页面,紧凑主题失效了,

antd-pro-table页面未引用任何css,less.
自己的项目的layout页面中使用了@import '~antd/dist/antd.compact.less';
antd-pro-table页面是 使用react-loadable异步加载的页面
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/31265244/104004147-5f655c80-51de-11eb-9c9f-884a6cc68d93.png)
![image](https://user-images.githubusercontent.com/31265244/104004246-7c9a2b00-51de-11eb-95b5-5fe93fbd131f.png)

**Comment by 1257960069** [comment]
为什么没有答复

**Comment by chenshuai2144** [comment]
不写标题，直接关
