### ISSUE TITLE
👑 [需求]ProField是否可以增加遮蔽显示的组件

### ISSUE THREAD

**Issue by xiexingen** [ant-design/pro-components#1559]
### 🥰 需求描述
ProField是否可以增加遮蔽显示的组件

某些场合下，有些敏感信息需要遮蔽显示，比如手机号码、身份证、邮箱地址、银行卡号、电话号码等，
这类型的显示的时候带遮蔽信息的，有些可以点击查看显示更多，有些完全不允许查看更多信息
需要支持的功能
- 按类型遮蔽显示部分信息(可能每个企业规则不同，这需要可以自定义遮蔽位置)
   1. 手机号码  比如:185****0930 
   2. 电话号码  如:0739-422****64  
- 有个查看图标，点击可以看全(但是可能存在某些信息是完全不允许看的，所以要可以配置是否支持查看)
### 🧐 解决方案

看ProFile的用法类似这样
``` jsx
<Field 
     text="18888888888" 
     valueType={{
        type: 'phone', // 电话号码类型的遮蔽,实际显示的时候 1888****888
        format:(v)=>"", // 用来自定义格式化值
        original: true, // 是否允许查看原始数据，false表示不显示查看全部手机号码的按钮
      }}
      mode="read"
 />
```

这是目前能想到的办法，看各位大佬有没更好点的灵活性高点的方案

**Comment by chenshuai2144** [comment]
可以让设计师安排一下
