### ISSUE TITLE
🐛[BUG]hash模式面包屑导航栏跳转错误

### ISSUE THREAD

**Issue by lirenhao** [ant-design/pro-components#156]
### 🐛 bug 描述

导航栏的跳转方式是a标签，当history使用hash时，导航栏跳转错误

### 📷 复现步骤

-- 路由跳转方式设置为hash
```
history: {
    type: 'hash'
  },
```

-- 设置publicPath
```
publicPath: '/test/',
```

-- 启动项目后，点击一个菜单，之后点击该页面当导航栏

### 🏞 期望结果

history设置为hash时，点击导航栏能正常跳转

### 💻 复现代码

无

### © 版本信息

- @ant-design/pro-layout:6.0.0 版本
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
自己 render 一下吧，layout 组件没法知道你是用什么方式跳转的。

**Comment by lirenhao** [comment]
那把layout提出来还有什么意思？

**Comment by chenshuai2144** [comment]
脚手架更加清爽，你可以用 plugin 插件，插件知道你用的是什么模式

**Comment by lirenhao** [comment]
什么意思？antd pro v5用的不就是layout插件吗？

**Comment by chenshuai2144** [comment]
https://github.com/umijs/plugins/blob/master/packages/plugin-layout/src/layout/index.tsx#L89

插件是没有问题

**Comment by lirenhao** [comment]
没描述清楚这个是我的问题，我用antd pro v5构建的项目，当history设置为hash时，面包屑的导航错误（菜单的链接没有问题）

**Comment by chenshuai2144** [comment]
看了一下没做处理，你有兴趣提个 pr 吗？

**Comment by lirenhao** [comment]
好啊，不过没用过pr可能会慢点

**Comment by lirenhao** [comment]
临时解决方案：
在使用antd pro v5时，在layout的配置中添加```itemRender: route => (<Link to={route.path}>{route.breadcrumbName}</Link>) ```，暂时不使用默认的defaultItemRender
