### ISSUE TITLE
🐛[BUG] ProFormFieldSet内部组件无法使用hidden等相关属性.

### ISSUE THREAD

**Issue by KumaCool** [ant-design/pro-components#1560]
### 🐛 bug 描述

内部的表单组件无法使用hidden进行隐藏或使用name来取值

### 🏞 期望结果

我的一组表单值如: `{ list: ["a", "b", "c"] }`
在业务中会根据状态显示/修改相关的组件中部分表单
如果用`if`方法渲染子组件我必须手动的维护值的索引,因为目前`ProFormFieldSet`只会根据内部渲染的组件来合并值.
所以我想在子组件上使用hidden进行占位或使用name来取值,但发现这些属性都是无效的.

### 💻 复现代码

https://codesandbox.io/s/proformfieldset-bug-o4xuf?file=/App.tsx

### © 版本信息

- ProForm 版本: [e.g. 1.13.6]
- React 版本: [e.g. 17.0.1]
- 浏览器环境 Chome [87.0.4280.88]
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
可以加个featrue， hidden 的时候可以判断是否取值

**Comment by KumaCool** [comment]
不太理解您的这句话.是指需要开发新功能吗?
如果是的话为什么不能支持其它的属性呢?如 name 有可能在业务中指定其它字段的值.虽然常规情况下不会.

**Comment by chenshuai2144** [comment]
ProFormFieldSet 是为了解决多个 input 框公用一个 name 的问题，如果是多个输入框对多个 name 建议用 Form.list

**Comment by Hnnphone** [comment]
一个输入框 对应 多个 name 的情况呢

**Comment by chenshuai2144** [comment]
一个输入框 对应 多个 name ，这个是 transform

**Comment by chenshuai2144** [comment]
发现用 display:none 就能解决，没必要加新功能
