### ISSUE TITLE
🧐[问题]class组件中使用formRef从ProTable中获取form引用

### ISSUE THREAD

**Issue by SilentFlute** [ant-design/pro-components#1561]
### 🧐 问题描述
如何在class组件中使用formRef从ProTable中获取form引用呢?

### 💻 示例代码

关键代码如下:
```
import React, { PureComponent, ReactNode, MutableRefObject } from 'react';
import type { FormInstance } from 'antd/lib/form';

// form引用
let formRef: MutableRefObject<FormInstance> = {
  current: {}
};

// 处理form实例的方法
const handleFormRef = (form: MutableRefObject<FormInstance>): MutableRefObject<FormInstance> => {
  formRef = form;
  return formRef;
}

class Index extends PureComponent {
//...
            <ProTable
              rowKey="id"
              loading={tableLoading}
              columns={this.columns}
              formRef={handleFormRef}
              dataSource={tableData.rows}
              onReset={this.handleOnReset}
              onSubmit={this.handleOnSumbit}
              options={{
                fullScreen: false,
                reload: this.handleTableRefresh
              }}
              toolBarRender={this.handleRenderToolBar}
            />
//...
}
```
一开始我是写一个函数, 然后将ProTable formRef api回调回来的formRef赋值给一个变量是可以的, 能正常使用, 但是ts老给报错, 然后我尝试着改了改, 最后改成上面那样, 但ts依旧报错, 上方定义和render方法里调用都报错, 第一次尝试使用ts, 求指点, 感谢:
![image](https://user-images.githubusercontent.com/28900312/104083966-ecabbe00-527d-11eb-9696-62ad4965ca5d.png)
![image](https://user-images.githubusercontent.com/28900312/104083973-00572480-527e-11eb-8ffc-b580a9332978.png)

**Comment by SilentFlute** [comment]
@chenshuai2144 求指点, 感谢!

**Comment by SilentFlute** [comment]
我一开始是这么写的:
![image](https://user-images.githubusercontent.com/28900312/104084806-7a3edc00-5285-11eb-83a3-af9d26caeff4.png)
然后ts提示如下:
![image](https://user-images.githubusercontent.com/28900312/104084815-93478d00-5285-11eb-8dab-8f1e379a65f9.png)

**Comment by chenshuai2144** [comment]
```
class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.myRef = React.createRef();
  }
  render() {
    return <div ref={this.myRef} />;
  }
}
```

这样写，官方推荐

**Comment by SilentFlute** [comment]
@chenshuai2144 哦哦, 感谢回复, 但我这么写了之后ts还是报错, 我没有将ref定义在constructor中, 而是写在了class外面, 但这个应该不影响嘛, 就是这个ref是否是实例的一个属性的区别对吧?
```
// form引用
const formRef = createRef();
//...
            <ProTable
              rowKey="id"
              loading={tableLoading}
              columns={this.columns}
              formRef={formRef}
//...
```
这个写法在From组件中是ok的, 但是用在ProTable上ts就报错了:
![image](https://user-images.githubusercontent.com/28900312/104141389-64e6c080-53f1-11eb-8072-891fd5e0ae7d.png)

**Comment by chenshuai2144** [comment]
`const formRef = createRef<类型>();`

你没写泛型

**Comment by SilentFlute** [comment]
@chenshuai2144 我写了之后也还是一样的
```
import type { FormInstance } from 'antd/lib/form';
const formRef = createRef<FormInstance>();
```
![image](https://user-images.githubusercontent.com/28900312/104263178-06d6dd80-54c4-11eb-997e-5efc25b2004f.png)

**Comment by chenshuai2144** [comment]
类型用错了，你 as 一下吧。

**Comment by SilentFlute** [comment]
@chenshuai2144 我还说再问你下怎么使用类型断言, 后来看了下react的ts声明文件, 发现:
```
function createRef<T>(): RefObject<T>;
function useRef<T>(initialValue: T): MutableRefObject<T>;
```
只有useRef才会返回MutableRefObject, 然后终于明白你说的类型断言怎么用了:
```
const formRef = createRef<FormInstance>() as MutableRefObject<FormInstance>;
```
再次感谢, 第一次用ts, 各种报错

**Comment by meditatorzhang** [comment]
函数组件中我是这样写的，没有报错
```
import type { FormInstance } from 'antd/lib/form';
const formRef = useRef<FormInstance>();

const exportList = () => {
  formRef.current?.validateFields().then(
    ......
  );
};

<ProTable<TableListItem>
  formRef={formRef}
  ......
```
