### ISSUE TITLE
🐛[BUG] ProFormText，使用右侧的清除按钮后，无法再输入中文

### ISSUE THREAD

**Issue by gaven004** [ant-design/pro-components#1562]
### 🐛 bug 描述

ProFormText，输入内容后，使用右侧的清除按钮清除内容，之后无法直接输入中文，然后会导航再无法输入

### 📷 复现步骤

1、在ProFormText的输入框，输入任意内容
2、使用右侧的清除按钮清除内容
3、在框内再输入中文，此时无响应，之后输入任何内容都不再有响应

### 💻 复现代码

        <ProFormText
          name="id"
          label="分类ID"
          rules={[
            {
              required: true,
              message: '分类ID为必填项',
            },
          ]}
        />
        <ProFormText
          name="name"
          label="分类名称"
          rules={[
            {
              required: true,
              message: '分类名称为必填项',
            },
          ]}
        />

### © 版本信息

- ProComponents 版本: 5.0.0-beta.2
- umi 版本: 3.3.2
- 浏览器环境: Microsoft Edge 87.0.664.75
- 开发环境: mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/9878331/104095652-03303480-52d3-11eb-922e-5489a487478e.png)

**Comment by chenshuai2144** [comment]
更新一下版本，浏览器对输入法的兼容性不是很统一，我关掉了这个功能

**Comment by gaven004** [comment]
更新过后，问题解决了，多谢！
________________________________
发件人: 陈帅 <notifications@github.com>
发送时间: 2021年1月13日 10:59
收件人: ant-design/pro-components <pro-components@noreply.github.com>
抄送: gaven004 <gaven004@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [ant-design/pro-components] 🐛[BUG] ProFormText，使用右侧的清除按钮后，无法再输入中文 (#1562)


更新一下版本，浏览器对输入法的兼容性不是很统一，我关掉了这个功能
