### ISSUE TITLE
🐛[BUG] proTable 列样式

### ISSUE THREAD

**Issue by qq382724935** [ant-design/pro-components#1563]
### 🐛 bug 描述

proTable 当设置 scroll={{y:350}}，在dataSource等于空数组的情况下，y不等于undefind的值会出现列样式错误，第一列会占满宽度
### 💻 复现代码
https://codesandbox.io/s/quiet-meadow-8xgn7?file=/index.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by qq382724935** [comment]
在提个umi-pro5的疑问，后台系统登录后每个账号有多个角色，点击切换角色会在当前页面显示弹出框，选择新的角色登录。假设停留的页面为home。
1. 看了文档菜单控制可在layout中改变，但是如果新角色没有当前页面访问权限？选择新角色后应该显示403，我尝试使用umijs/plugin-initial-state插件的refresh和setInitialState视乎没用，是否是我逻辑问题？
2. 如果新角色有权限访问home页面，但是列表页数据会不同，同1使用umijs/plugin-initial-state插件的refresh和setInitialState页面状态不会改变？请问umi3中是否有良好的解决方法实现？

**Comment by chenshuai2144** [comment]
复杂的地方可以用 window.reload ，不然这些权限管理很复杂

**Comment by chenshuai2144** [comment]
`scroll={{y:350}}`
设置之后记得要设置每行的长度，不然样式很有可能很复杂

**Comment by qq382724935** [comment]
> 复杂的地方可以用window.reload，不然这些权限管理很复杂

嗯，尝试了reload比较快速方便

**Comment by qq382724935** [comment]
> > 复杂的地方可以用window.reload，不然这些权限管理很复杂
> 
> 嗯，尝试了reload比较快速方便

是的设宽度没问题，那这属于bug吗，不属于close了

**Comment by chenshuai2144** [comment]
是 table 的 dom 默认行为
