### ISSUE TITLE
👑 [需求] EditProTable希望onSave时，支持传入单行数据

### ISSUE THREAD

**Issue by q1557050025** [ant-design/pro-components#1564]
### 🥰 需求描述

EditProTable现版本单行新增时onSave方法只能返回boolean值，如果一行数据的某些字段，例如id是由后台自动生成的，无法将新的数据传入表格数据中
### 🧐 解决方案
希望onSave方法可以支持返回数据传入新增行中

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/43104602/104104895-b013ad00-52e5-11eb-80b0-4965727f2133.png)

>

**Comment by q1557050025** [comment]
![image](https://user-images.githubusercontent.com/43104602/104105427-f28ab900-52e8-11eb-920e-01fbcef492d1.png)
用editable.actionRender实现了类似的功能，不过稍微多了几个麻烦的步骤

**Comment by q1557050025** [comment]
```
 editable={{
          actionRender: (row, config) => [
            <a
              key="save"
              onClick={async () => {
                const values = omit(
                  ["index", "_id"],
                  config.form.getFieldValue("new")
                );
                await createPost(values as PostEntity).then((res) => {
                  config?.onSave?.(config.recordKey, { ...values, ...res });
                });
              }}
            >
              保存
            </a>,
            <a key="cancel">取消</a>,
          ],
        }}
```

**Comment by n0tKnow** [comment]
发现一种更简易的方法
`
editable={{
    onSave: async (rowKey, data, row) => {
        return request(data).then(r => {
            //replace id
            data.id = r?.data?.id
            return true
        })
    },
}}
`
