### ISSUE TITLE
👑 [需求]ProFormSelect通过valueEnum禁用某一项

### ISSUE THREAD

**Issue by yangqi12345** [ant-design/pro-components#1565]
### 🥰 需求描述

需求同：#486，然后发现有更新：#548
但是#548 并未实现此功能，不知道是因为版本问题还是什么
目前使用了@ant-design/pro-form" 1.13.3 版本，看到valueEnum中已经有了#548的代码，可以设置disabled
但是实际使用中ProFormSelect并未实现指定项disabled的功能

### 🧐 解决方案

暂无解决方案，望高人指点

### 🚑 其他信息

![1](https://user-images.githubusercontent.com/16695153/104113648-9484c280-5336-11eb-877c-0ae4542aef66.jpg)
![2](https://user-images.githubusercontent.com/16695153/104113649-964e8600-5336-11eb-8b4c-5d8e32e3a0f7.jpg)
![3](https://user-images.githubusercontent.com/16695153/104113650-96e71c80-5336-11eb-9d8e-94c2624e4a22.jpg)

**Comment by yangqi12345** [comment]
补充一下，图二是在@pro-utils的typing.d.ts中找到的

**Comment by chenshuai2144** [comment]
这个功能我记得有人支持了，你没有生效吗？

**Comment by yangqi12345** [comment]
发现你已修复，过段时间我更新包之后试试
