### ISSUE TITLE
不要再升级小版本了，和原来的版本有不兼容，各种报错🐛[BUG]

### ISSUE THREAD

**Issue by LichiaMa** [ant-design/pro-components#1577]
### 🐛 bug 描述
最新的 pro form stepform 和原来的版本不兼容，formList 无法使用，在onfinish里面拿不到数据，之前的版本是可以的

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by LichiaMa** [comment]
本来项目用的好好的，结果重新部署了一次到处报错，已经两次了

**Comment by chenshuai2144** [comment]
报错搞出来试试？这个库专门抽出来就是为了随时发版本

**Comment by LichiaMa** [comment]
我发现不是formlist不能用了，是name属性是数组的都不能用了，在onfinish里面拿不到值 1.13.7

**Comment by LichiaMa** [comment]
![20210111160700](https://user-images.githubusercontent.com/17775060/104157900-118f6500-5427-11eb-93dc-3416a2f6d55c.jpg)
类似这种写法，在onfinish里面都拿不到值，不光是stepForm，普通的proform也不行

**Comment by LichiaMa** [comment]
![20210111160924](https://user-images.githubusercontent.com/17775060/104158004-629f5900-5427-11eb-98b1-1ee188baa30c.jpg)
类似这种

**Comment by LichiaMa** [comment]
> 报错搞出来试试？这个库专门抽出来就是为了随时发版本

发版本可以，但尽量别影响之前的版本，这样本来之前好的功能，版本自动升级了之后就有问题了，会影响使用的

**Comment by chenshuai2144** [comment]
没有这个测试用例，我加个看看

**Comment by LichiaMa** [comment]
> 没有这个测试用例，我加个看看

这个最近的哪个版本是没有问题的，我回退到1.12.0是可以的，还有新的版本吗，我回退一下

**Comment by LichiaMa** [comment]
我试了1.13.5是没问题的，1.13.6和1.13.7都有问题

**Comment by cuihq2005** [comment]
每次升级都是一场战斗....

**Comment by chenshuai2144** [comment]
加了个测试用例，更新下版本就ok了。

欢迎贡献你们的使用场景，我们可以加到测试用例里

**Comment by askurat** [comment]
There is still an issue with the latest release.
I have a pro select field like below: 
```
<ProFormSelect
          width="md"
          name={['source', 'id']}
          label="Source"
          placeholder="Please select a source"
          options={sourcesOptions}
        />
```
When calling `OnFinish`, it adds an `id' field and 'source.id` field. Both have the same id:
```
id: "4a8a5df6-3614-4092-ac3f-fd5345202ae4"
source: {id: "4a8a5df6-3614-4092-ac3f-fd5345202ae4"}
```
It should just have `source.id`.
