### ISSUE TITLE
[Pro-Layout]👑 [需求] PageContainer支持自定义头部容器

### ISSUE THREAD

**Issue by xiexingen** [ant-design/pro-components#158]
### 🥰 需求描述
期望可以支持固定头部，当页码滚动的时候头部一直可见状态
![image](https://user-images.githubusercontent.com/7939085/89978937-311c3900-dca1-11ea-9ecb-c23e68607e9e.png)

### 🧐 解决方案
建议跟antd里面弹窗那种类似，提供一个getContainer的方式，然后开发者自己控制fixePageHeader

**Comment by rdmclin2** [comment]
ProLayout支持 fixedHeader 了，https://procomponents.ant.design/components/layout#pagecontainer
