### ISSUE TITLE
🧐[问题]ProTable更新2.22.1版本无法初始化查询表单值

### ISSUE THREAD

**Issue by yuanjiahui** [ant-design/pro-components#1582]
### 🧐 问题描述

useEffect中无法给ProTable的查询表单赋值，版本2.22.1以上的存在此问题，之前的版本可以赋值

### 💻 示例代码
https://codesandbox.io/s/protable-mgrt6?file=/index.js

**Comment by chenshuai2144** [comment]
用 initValues 呢？
