### ISSUE TITLE
Table中valueType为indexBorder时，dataIndex不起作用🐛[BUG]

### ISSUE THREAD

**Issue by LichiaMa** [ant-design/pro-components#1586]
### 🐛 bug 描述
最新版本的ProTable中，在columns中配置了valueType:'indexBorder',后dataIndex就不起作用了，显示的不是dataIndex配置的数据，而是1，2，3...等等

### 💻 复现代码
{
      title: 'ID',
      dataIndex: 'id',
      key: 'ipId',
      valueType: 'indexBorder'
},

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
```
{
    title: 'ID',
    dataIndex: 'id',
    key: 'ipId',
  },
```
![20210112151350](https://user-images.githubusercontent.com/17775060/104281679-d5243d80-54e8-11eb-8252-238b1c6eecd5.jpg)
```
{
  title: 'ID',
  dataIndex: 'id',
  key: 'ipId',
  valueType: 'indexBorder'
},
```
![20210112151313](https://user-images.githubusercontent.com/17775060/104281698-d9e8f180-54e8-11eb-9cc7-6dbba6166461.jpg)

**Comment by chenshuai2144** [comment]
这个是个 featrue，indexBorder 就是只显示行号

**Comment by flowerDAI** [comment]
> 这个是个 featrue，indexBorder 就是只显示行号

这个行号的颜色或是样式，能自定义吗？

**Comment by chenshuai2144** [comment]
不能的 这个是预设的
