### ISSUE TITLE
🧐[问题]升级到了表格最新版 功能出现

### ISSUE THREAD

**Issue by jinhongjie007** [ant-design/pro-components#1588]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/10215848/104286874-9c886200-54f0-11eb-83a8-0bd555e22b21.png)
在表格中显示树选择，原来是正常渲染的，但是升级以后不渲染了。变成了input
![image](https://user-images.githubusercontent.com/10215848/104287145-fee16280-54f0-11eb-8ed8-b66d92b3df71.png)
在input中随便输入点东西，树选择才渲染出来
![image](https://user-images.githubusercontent.com/10215848/104287211-17517d00-54f1-11eb-9199-9683b6f0a421.png)

### 💻 示例代码
```
{
      title: '上级分类',
      dataIndex: 'parent_id',
      hideInTable: true,
      renderFormItem: () => {
        return (
          <TreeSelect
            treeData={convertData(tableData)}
            style={{width: '100%'}}
            dropdownStyle={{maxHeight: 400, overflow: 'auto'}}
            placeholder="请选择"
            treeDefaultExpandAll
          />
        );
      },
    },

```

**Comment by chenshuai2144** [comment]
你用了 request 还是 dataSource？

**Comment by jinhongjie007** [comment]
用了request远程请求
