### ISSUE TITLE
🐛[BUG]pro-layout:从服务器加载menu，刷新页面当前菜单不能默认选中高亮并展开

### ISSUE THREAD

**Issue by perany** [ant-design/pro-components#159]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个重现？

**Comment by nameJw** [comment]
> 来个重现？

`<ProLayout menuDataRender={!isSuperAdmin ? () => menuData : null}>`
**menuData**是从服务器来的菜单数据，可以渲染，但是不会默认展开，手动展开菜单，打开一个页面，页面打开后菜单全部又缩回去了，prolayout 版本从5.x开始就有问题了

**Comment by chenshuai2144** [comment]
额，最好把菜单配置也打出来，开发者每天要处理很多 issue，不可能有精力一个个的构造重现条件的

**Comment by nameJw** [comment]
> 额，最好把菜单配置也打出来，开发者每天要处理很多 issue，不可能有精力一个个的构造重现条件的

嗯，我这没问题了，是返回的菜单数据的中有个属性为key的问题

**Comment by jlq023** [comment]
> 额，最好把菜单配置也打出来，开发者每天要处理很多 issue，不可能有精力一个个的构造重现条件的

我和他遇到了一样的问题，后台获取菜单数据,以及按f5刷新，我们不能控制menu的selectedKeys，

**Comment by jlq023** [comment]
> 额，最好把菜单配置也打出来，开发者每天要处理很多 issue，不可能有精力一个个的构造重现条件的

刷新时， 以及不能控制menu的openKeys

**Comment by johnnylc** [comment]
同样的问题

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/advanced-menu-cn

**Comment by lspeer** [comment]
> > 额，最好把菜单配置也打出来，开发者每天要处理很多 issue，不可能有精力一个个的构造重现条件的
> 
> 我和他遇到了一样的问题，后台获取菜单数据,以及按f5刷新，我们不能控制menu的selectedKeys，
现在解决了么，我也遇到同样的问题

**Comment by lspeer** [comment]
> 同样的问题

我也遇到这样的问题，不知道怎么解决
