### ISSUE TITLE
🐛[BUG] protable 将界面上所有column的search设置为false，protable查询部分不重绘

### ISSUE THREAD

**Issue by meyerlee** [ant-design/pro-components#1594]
### 🐛 bug 描述

protable 将界面上所有column的search设置为flase时，protable查询部分不重绘

### 📷 复现步骤

输入3时 会关闭3个显示5-3=2个，这个正确。
输入5时 就不会变化，实际应该不显示任何查询控件

### 💻 复现代码

````
import ProTable from "@ant-design/pro-table";
import { Button, InputNumber } from "antd";
import React, { useState } from "react";

export default function App() {
  const buildColumns = (count: number) => {
    const cols = [];
    for (let i = 0; i < count; i++) {
      cols.push({
        dataIndex: `c${i}`,
        title: `title${i}`,
        key: `c${i}`,
        search: false
      });
    }

    return cols;
  };

  const [columns, SetColumns] = useState<any[]>(buildColumns(5));

  const disable = () => {
    // eslint-disable-next-line no-return-assign
    columns.forEach((e) => (e.search = false));
    SetColumns(columns.slice(0));
  };

  const enable = () => {
    // eslint-disable-next-line no-return-assign
    columns.forEach((e) => (e.search = {}));
    SetColumns(columns.slice(0));
  };

  const disableOne = (count: number) => {
    for (let i = 0; i < columns.length; i++) {
      const e = columns[i];
      if (i < count) {
        e.search = false;
      } else {
        e.search = {};
      }
    }

    SetColumns(columns.slice(0));
  };

  return (
    <>
      <Button onClick={() => disable()}>disable all</Button>
      <Button onClick={() => enable()}>enable all</Button>
      <InputNumber onChange={(e) => disableOne(Number(e))} />
      <ProTable columns={columns} search={{ defaultCollapsed: false }} />
    </>
  );
}


````

### © 版本信息

- ProTable 版本: [2.23.0]

![image](https://user-images.githubusercontent.com/8414971/104309129-a1f3a580-550c-11eb-8084-d357b4dad165.png)
![image](https://user-images.githubusercontent.com/8414971/104309176-b8016600-550c-11eb-8920-7d15697519f2.png)

**Comment by chenshuai2144** [comment]
查询不重绘是什么意思？

**Comment by meyerlee** [comment]
通过state更新columns

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/104442374-ee53e980-55cf-11eb-912a-51b8229fbe26.png)


大小写写错了？

**Comment by meyerlee** [comment]
测试代码，试试就知道了。 
是控件的判断逻辑有问题
所有的列都设置为不查询，就会有问题，部分设置为不查询能正常工作。

**Comment by meyerlee** [comment]
修改了一下代码，可以在  https://codesandbox.io/  上运行
结果如下：  

![image](https://user-images.githubusercontent.com/8414971/104612585-559d9680-56c1-11eb-84bb-a27e6a6e4c6a.png)

**Comment by meyerlee** [comment]
我这边图片都看不到。。。。。。

**Comment by ccloveak** [comment]
> 修改了一下代码，可以在 https://codesandbox.io/ 上运行
> 结果如下：
> 
> ![image](https://user-images.githubusercontent.com/8414971/104612585-559d9680-56c1-11eb-84bb-a27e6a6e4c6a.png)

图片能看到，就是看不到代码。。。我也想学习一下。。。。

**Comment by meyerlee** [comment]
@ccloveak  把代码拷贝进去，  
加上protable和antd的依赖就可以运行了

**Comment by chenshuai2144** [comment]
感觉没什么意义，你自己玩吧。我也复现不了。先关了
