### ISSUE TITLE
🧐[问题]hooks怎么动态修改ProFormCheckbox.Group的选中

### ISSUE THREAD

**Issue by StruggleHH** [ant-design/pro-components#1595]
### 🧐 问题描述

hooks怎么动态修改ProFormCheckbox.Group的选项

### 💻 示例代码
<ProFormCheckbox.Group
                        name="testCheck"
                        label="测试"
                        width="xl"
                        options={[{ label: '测试1', value: 1 },{ label: '测试2', value: 2 },{ label: '测试3', value: 3 }]}
                        rules={[{ required: true, message: '测试' }]}
                    />

**Comment by chenshuai2144** [comment]
用` fromRef.setxxx` ,ProFormXXX 都是 form
