### ISSUE TITLE
🐛[BUG] protable使用sorter后点击排序重新请求接口

### ISSUE THREAD

**Issue by webguicai** [ant-design/pro-components#1597]
### 🐛 bug 描述

protable使用sorter后点击排序重新请求接口

  "dependencies": {
    "@alipay/bigfish": "^3.6.0",
    "@alipay/tech-ui": "^1.25.1",
    "@alipay/techui-form": "^2.3.18",
    "@ant-design/charts": "^1.0.2",
    "@ant-design/compatible": "^1.0.4",
    "@ant-design/icons": "^4.2.1",
    "@ant-design/pro-form": "^1.2.1",
    "@ant-design/pro-table": "2.4.4",
    "@antv/g2": "^4.0.13",
    "@umijs/route-utils": "^1.0.34",
    "ant-design-pro": "^2.3.2",
    "antd": "^4.4.2",
    "bizcharts": "^4.0.11",
    "china-division": "^2.3.1",
    "copy-to-clipboard": "3.3.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "umi-request": "^1.3.5",
    "xlsx": "^0.16.8"
  }

**Comment by chenshuai2144** [comment]
dup of  https://github.com/ant-design/pro-components/issues/1581
