### ISSUE TITLE
🧐[问题]ProTable, 如果用dataSource模式,是不是ref.current?.reload() 无效啊?

### ISSUE THREAD

**Issue by l745230** [ant-design/pro-components#160]
### 🚑 其他信息

一直无法触发表格重新查询.

**Comment by l745230** [comment]
点protable自带的刷新图标能正常调用.
通过ref调用,控制台输出警告,然后没调用成功.
![image](https://user-images.githubusercontent.com/15940920/89993265-03db8500-dcb9-11ea-9535-582cd62dcdb5.png)

![image](https://user-images.githubusercontent.com/15940920/89993142-dabaf480-dcb8-11ea-8d51-949dfc4b1047.png)

**Comment by chenshuai2144** [comment]
需要自己实现的，protable 不知道你是怎么更新 dataSource

**Comment by l745230** [comment]
@chenshuai2144 在哪里定义reload的方法? 

ref.current?.reload() 触发不到options中reload()

**Comment by chenshuai2144** [comment]
action肯定不能用了！要自己实现了

**Comment by l745230** [comment]
呃,那就是说不是用ref.current?.reload() ,而是自己写个reload方法吗?

**Comment by l745230** [comment]
能不能ref.current?.reload()  使用options中定义的reload方法?

**Comment by chenshuai2144** [comment]
用了dataSource都要自己管的 和antd用法9一样

**Comment by l745230** [comment]
好吧....
