### ISSUE TITLE
🧐[问题] proTable更新到2.22.1以上版本之后，初始化无法给表单赋值

### ISSUE THREAD

**Issue by songzhen5656** [ant-design/pro-components#1601]
### 💻 示例代码
https://codesandbox.io/s/heuristic-leftpad-o0ldc?file=/App.tsx

**Comment by chenshuai2144** [comment]
不用 initValues 吗?
form 是异步生成的，速度可能没法保证

https://procomponents.ant.design/components/table#%E6%9F%A5%E8%AF%A2%E8%A1%A8%E6%A0%BC

**Comment by songzhen5656** [comment]
我这边需求是在当前页面通过表单查询，跳转到另一个页面在返回来，依旧可以看到之前查询的条件和数据，如果用initValues，不就每次都是原来的默认值吗

**Comment by chenshuai2144** [comment]
initValues 不行的，我修改了实现，你可以继续用了
