### ISSUE TITLE
👑 [需求]EditableProTable增加一个onValueChange用于监听编辑列发生变化的事件

### ISSUE THREAD

**Issue by pangxiaolong** [ant-design/pro-components#1603]
### 🥰 需求描述
![需求截图](https://s3.ax1x.com/2021/01/13/sNm0Z8.png)
多列编辑时，需要根据某一编辑列的编辑时，实时将右边一列单元格修改为总价-编辑列的值 ，例如第一列是100，第二列为编辑列，第三列为0，当编辑第二列为50时，需要将第三列修改为50（由100-50得出）。当前的属性onChange只支持保存时去得到修改的数据，没有办法实现。
### 🧐 解决方案

希望可以加入onValueChange的事件，去监听编辑列的变化，因为有多列，可能需要至少两个参数(value,record)=>{}，record用于判断修改的是哪一行

### 🚑 其他信息

捉急:(

**Comment by chenshuai2144** [comment]
其实现在可以通过 renderFormItem 来实现的

**Comment by HuYuee** [comment]
可以给个简单的demo吗？

**Comment by HuYuee** [comment]
@chenshuai2144 我们现在这边的业务场景是在第一列下拉选择之后，需要去请求后台接口，然后再将结果联动到其他列上面

**Comment by pangxiaolong** [comment]
> @chenshuai2144 我们现在这边的业务场景是在第一列下拉选择之后，需要去请求后台接口，然后再将结果联动到其他列上面

已经增加了onvaluechange事件了啊

**Comment by HuYuee** [comment]
我写了个示例，不知道是否可以这么操作。但是这个功能实现之后是有bug的，输入第一行第一列之后，再输入第二行第二列，多执行几下这个操作会导致，后面列的数据紊乱。https://codesandbox.io/s/shishibaocundebianjibiaoge-forked-is8pu?file=/App.tsx

**Comment by pangxiaolong** [comment]
> 我写了个示例，不知道是否可以这么操作。但是这个功能实现之后是有bug的，输入第一行第一列之后，再输入第二行第二列，多执行几下这个操作会导致，后面列的数据紊乱。https://codesandbox.io/s/shishibaocundebianjibiaoge-forked-is8pu?file=/App.tsx

虽然不知道你要表达具体的错误情景，但是看来你的操作符合你的代码逻辑，也许你是否应该检查一下for中，是否应该使用一个唯一标示的属性去判断操作的是哪一列，而不是用title这一列的值去判断，假设你每一列title都输入为1，你的代码可能就不会符合你的预期。

**Comment by h1nson** [comment]
请问有解决方案了吗，能分享一下吗、？
