### ISSUE TITLE
🧐[问题]页面初始化无法获取到ref.current中的属性

### ISSUE THREAD

**Issue by songzhen5656** [ant-design/pro-components#1604]
### 🧐 问题描述
我在页面初始化时使用useEffect给table的查询条件赋值，但是打印出来ref.current属性为undefined

### 💻 示例代码
const ref = useRef();
useEffect（（）=>{
   ref.current.setFiledsValue({
       name: 'xxx',
   })
}）

### 🚑 其他信息
proTable 2.22.1以上版本出现此问题

**Comment by chenshuai2144** [comment]
ProTable 的 form 都是懒加载的，你要用 initValues 来设置默认值

**Comment by Twisted12138** [comment]
如果不是要设置默认值而是保存搜索条件呢

**Comment by Twisted12138** [comment]
如果不是要设置默认值而是保存上一次的搜索条件呢，   在table初次渲染的时候无法获取ref吗？@chenshuai2144



> ProTable 的 form 都是懒加载的，你要用 initValues 来设置默认值

如果不是要设置默认值而是保存上一次的搜索条件呢，   在table初次渲染的时候无法获取ref吗？@chenshuai2144

**Comment by Twisted12138** [comment]
> 如果不是要设置默认值而是保存上一次的搜索条件呢， 在table初次渲染的时候无法获取ref吗？@chenshuai2144
> 
> > ProTable 的 form 都是懒加载的，你要用 initValues 来设置默认值
> 
> 如果不是要设置默认值而是保存上一次的搜索条件呢， 在table初次渲染的时候无法获取ref吗？@chenshuai2144

  useEffect(() => {
    console.log(Ref.current);
  }, [Ref.current]);

- 
![image](https://user-images.githubusercontent.com/46923858/104426505-fe160280-55bc-11eb-8521-c7adb1b45381.png)

**Comment by songzhen5656** [comment]
你这么做可能会造成初始化多次加载，会产生bug
