### ISSUE TITLE
🧐[问题]搜索表单自定义，如何清空选项的已选值

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#1605]
### 🧐 问题描述
根据Demo，编写的代码，现在碰到这样一个问题，

假设：'type'：固定资产有，'category'： 四个子项目，
![image](https://user-images.githubusercontent.com/12421552/104423334-ec326080-55b8-11eb-900a-dc12b5cc2837.png)

我切换 固定资产  到 商务礼品，它有三个子项
![image](https://user-images.githubusercontent.com/12421552/104423496-226fe000-55b9-11eb-9007-37c35af99fab.png)

那么 传递 过来的props.value 还是之前的固定资产中的四个，不符合需求。

现在可否有办法在这里对 dataIndex: 'category',的值修改，使传递到CategorySelect组件里的props.value最起码我可以设置为空，使选择框清空也好。
![image](https://user-images.githubusercontent.com/12421552/104423630-4a5f4380-55b9-11eb-9519-ad1fd1c7ef12.png)

### 💻 示例代码

![image](https://user-images.githubusercontent.com/12421552/104423985-b641ac00-55b9-11eb-9059-2d88b8866b93.png)
![image](https://user-images.githubusercontent.com/12421552/104424107-e5581d80-55b9-11eb-89d0-523963d10185.png)

![image](https://user-images.githubusercontent.com/12421552/104424009-c2c60480-55b9-11eb-9d42-1e5441e7975e.png)

**Comment by chenshuai2144** [comment]
```
 formRef.current?.setFieldsValue({
                  name:xxx
});
```

这样就可以想设什么设置什么了

**Comment by edifangyi** [comment]
@chenshuai2144  谢谢~~(●ˇ∀ˇ●)
