### ISSUE TITLE
🧐[问题]ProTable查询表格后跳转页面再回来保持查询的条件

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/pro-components#1606]
### 🧐 问题描述
我在当前页面通过搜素条件查询后，跳转到另一个页面在回到之前搜索过的页面，如何然搜索条件保持在搜索后的值

**Comment by chenshuai2144** [comment]
可以用 react-router 把参数保存到 url上，这样就不会有问题了

**Comment by PLUTO06210331** [comment]
不是很清楚怎么操作，麻烦指导下

**Comment by PLUTO06210331** [comment]
我使用的是umi的hisory，而且是通过菜单跳转，不清楚怎么保存在url

**Comment by Augustzyh** [comment]
那就用dva就行了

**Comment by Augustzyh** [comment]
或者自己存会话窗口，方法很多

**Comment by PLUTO06210331** [comment]
用dva的话只能通过存在model里，需要调用接口传参

**Comment by Augustzyh** [comment]
你回来的时候在吧model里的记录回写到initialValue就可以了

**Comment by Augustzyh** [comment]
陈帅说的 history.push({ pathname: '', query: {} }); 也能做到，你不想记录到url上就自己找地方记呗

**Comment by chenshuai2144** [comment]
楼上正解
