### ISSUE TITLE
proTable的搜索表单，怎么样可以让选择框可以搜索？🧐[问题]

### ISSUE THREAD

**Issue by Zoe-Lu** [ant-design/pro-components#1608]

**Comment by chenshuai2144** [comment]
点一下查询按钮？

这个地方有demo ，用 filedProps 设置进去
https://ant.design/components/select-cn/

**Comment by Zoe-Lu** [comment]
不是  搜索表单里的select选择器，怎么可以支持多选或者列表搜索

![image](https://user-images.githubusercontent.com/77383426/104690324-32b1c780-573f-11eb-9281-6bac48a0c638.png)

**Comment by chenshuai2144** [comment]
用fieldProps设置一下 和antd用法一样了
