### ISSUE TITLE
🐛[BUG] 升级到最新版在renderFormItem里面写入Input.Group相关代码不生效

### ISSUE THREAD

**Issue by zhengdongzhe** [ant-design/pro-components#1609]
### 🐛 bug 描述

在升级最新版之前renderFormItem里面写入InputGroup是可以正常回去参数以及值。但是升级之后获取不到任何值
```
<Input.Group compact>
      <Form.Item name={['talkDuration', 'small']} noStyle>
        <Input allowClear placeholder=">=" style={{ width: '30%', marginRight: 5 }} />
      </Form.Item>
      <Form.Item name={['talkDuration', 'big']} noStyle>
        <Input allowClear placeholder="<=" style={{ width: '30%' }} />
      </Form.Item>
    </Input.Group>
```
这是renderFormItem里面相关代码。

### 🏞 期望结果

输入值点击查询后期望获得{ talkDuration: { small: 1, big: 2 } }

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个写法是真牛

**Comment by zhengdongzhe** [comment]
此写法现在是走不通了？

**Comment by chenshuai2144** [comment]
我看看没试过，理论上要可以的

**Comment by zhengdongzhe** [comment]
> 这个写法是真牛

现在这种方式走不通了？

**Comment by zhengdongzhe** [comment]
> 我看看没试过，理论上要可以的

之前是可以获取到值。但是更新到最新版之后不行了...

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/104436797-fbb9a580-55c8-11eb-8a19-8ec5767e4440.png)


是不是有什么没有同步更新，我发现你的这种能跑

**Comment by zhengdongzhe** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/104436797-fbb9a580-55c8-11eb-8a19-8ec5767e4440.png)
> 
> 是不是有什么没有同步更新，我发现你的这种能跑

我刚刚试了一下。在search里面可以获取到 但是在beforeSearchSubmit里面获取不到.

**Comment by chenshuai2144** [comment]
(⊙﹏⊙) ，我试试

**Comment by zhengdongzhe** [comment]
> (⊙﹏⊙) ，我试试， 一样可以的。
> 
> 可能是另外的bug，前天修了的，再更新一下版本

ok  已解决  感谢感谢

**Comment by HAOYI99** [comment]
@zhengdongzhe 感谢大佬的代码，我终于搞懂怎么弄自己的digit range了
感动死我了！原来要加个formitem才能在space compact底下穿数值上去！
