### ISSUE TITLE
2.5.4当值为null的时候显示序号123456🐛[BUG]

### ISSUE THREAD

**Issue by zyh2123606** [ant-design/pro-components#161]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by jassonxian** [comment]
@chenshuai2144 
急需解决下

**Comment by youshao** [comment]
> @chenshuai2144
> 急需解决下

我昨晚也发现这个问题了，临时锁定版本为2.4.*来解决。

**Comment by chenshuai2144** [comment]
今晚发版本。

**Comment by chenshuai2144** [comment]
已发布
