### ISSUE TITLE
🧐[问题]EditableProTable没有设置rowKey的时候直接失效，没有按照index控制

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/pro-components#1616]
### 🧐 问题描述
可编辑表格需要做新增操作，但是不能自定义id，想通过index控制，文档显示不写rowkey就按照index控制，实际上并没有

**Comment by chenshuai2144** [comment]
虽然我会修，但是建议设置 rowKey。 index 有超多问题

**Comment by PLUTO06210331** [comment]
主要是需求让我可以在一个表格里增删改，新增的没有唯一标识就很坑，用模拟id又怕重复

**Comment by chenshuai2144** [comment]
用 Math 生成上一个，一般不会重复的

**Comment by PLUTO06210331** [comment]
好的 谢谢 可以额=关闭了
