### ISSUE TITLE
🐛[BUG] ProForm的upload组件405了

### ISSUE THREAD

**Issue by Augustzyh** [ant-design/pro-components#1617]
### 🧐 问题描述

ProForm的upload405上传线上405了，线上修改nginx配置过滤405，无法加载响应数据，可能是中间某个版本又改到这块了？

### 💻 示例代码

官方文档案例 https://procomponents.ant.design/components/form

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/38031220/104542843-3a01a400-565f-11eb-9b98-a5bbc3756299.png)

![image](https://user-images.githubusercontent.com/38031220/104542726-0de62300-565f-11eb-94d8-4fd3f37083be.png)

**Comment by chenshuai2144** [comment]
405 是一般是因为请求方法的问题，比如服务端是 get，你用了 post 这种的。

上传文件只能是 post ，去问问你们的后端吧，这种事情一般和前端无关

**Comment by Augustzyh** [comment]
不是到，帅兄，还没到后端，就是前端线上选择文件，截图不知道怎么了可能看不到，你可以试一下官方文档里的，我看好像是pro-form1.9几的版本之后就出现这个问题了
![image](https://user-images.githubusercontent.com/38031220/104564898-6f6db800-5686-11eb-8dc7-16998a05d9cb.png)

**Comment by Augustzyh** [comment]
https://codesandbox.io/s/quirky-faraday-mjk1e?file=/App.tsx 这个可以试一下，会报

html> <head><title>405 Not Allowed</title></head> <body> <center><h1>405 Not Allowed</h1></center> <hr><center>nginx/1.16.1</center> </body> </html>  <!-- a padding to disable MSIE。。。。。

**Comment by Augustzyh** [comment]
https://codesandbox.io/s/quirky-faraday-mjk1e?file=/App.tsx  1.9.0的版本以前是没有的

**Comment by chenshuai2144** [comment]
这是个演示网站不是真实的，cdn 只支持 get ，不支持 post，所以会挂掉

**Comment by Augustzyh** [comment]
但我看源码也就是对antd Upload包了一小层，找不到啥问题，同样的线上环境antd的Upload和低版本的pro-form就不会报405，1.9.0及其以后的版本就全都这样了，我改自己项目的nginx发现无济于事，然后试了下官方的组件，发现的确是这样的，所以来问问你

**Comment by chenshuai2144** [comment]
action 的配置不一样吧，我们没配置 aciton，所以访问的是自己，你要配置 action 为自己的 url

**Comment by Augustzyh** [comment]
https://codesandbox.io/s/quirky-faraday-mjk1e?file=/App.tsx  1.8.1的pro-form就不存在这个问题，我这个项目都是前端存的file最后随表单统一上传，所以不存在action

**Comment by chenshuai2144** [comment]
那你把 aciton 给一个 null 试试，或者关掉自定义的上传逻辑

**Comment by Augustzyh** [comment]
本地是没有问题的，线上我试过了。。。没有用，只有使用1.9.0 pro-form以前的版本暂时不会有这个问题，直接在codesandbox里面改下版本就能复现这个问题

**Comment by Augustzyh** [comment]
截图显示不出来，不好描述，意思就是<ProFormUploadDragger max={4} label="Dragger" name="dragger" />
1.9.0以及更高版本的pro-form单独这样用也405...

**Comment by Augustzyh** [comment]
``` <ProFormUploadDragger max={4} label="Dragger" name="dragger" /> ```

**Comment by Augustzyh** [comment]
![image](https://user-images.githubusercontent.com/38031220/104581140-207d4e00-5699-11eb-9497-3a2780cadc2c.png)
```
Request URL: https://procomponents.ant.design/components/form
Request Method: POST
Status Code: 405 
Remote Address: 104.27.189.194:443
Referrer Policy: strict-origin-when-cross-origin
```
为什么pro组件里的上传会先调一下这个接口，这个接口和action没关系，正常的upload不应该会有这一步呀，现在就是这一步出错了，源码里也没找到写在哪里的

**Comment by Augustzyh** [comment]
图片加载不出来，这个放到项目里的情况就是URL会替换成我当前的href

**Comment by jiawenbin2013** [comment]
我也遇到这种情况了，dev环境没问题，生产环境就报405错误，请问您解决了吗？

> ![image](https://user-images.githubusercontent.com/38031220/104581140-207d4e00-5699-11eb-9497-3a2780cadc2c.png)
> 
> ```
> Request URL: https://procomponents.ant.design/components/form
> Request Method: POST
> Status Code: 405 
> Remote Address: 104.27.189.194:443
> Referrer Policy: strict-origin-when-cross-origin
> ```
> 
> 为什么pro组件里的上传会先调一下这个接口，这个接口和action没关系，正常的upload不应该会有这一步呀，现在就是这一步出错了，源码里也没找到写在哪里的

**Comment by jiawenbin2013** [comment]
我加上action之后(没什么作用)，解决了405的问题，但是服务器会接收两个文件，其中一个为空文件，搞不懂为什么。

**Comment by kisslove** [comment]
从上看下来，明明是封装组件封装的问题，要让服务器处理post的405。
1.首先，就应该将antd的beforeUpload参数放出来，用户支持手动上传。
2.其次，让设置action为null,根本就不了解action内部是如何处理的。
3.再者，随意closed掉提出的issue，是不负责任的表现。
...
算了，不喷了，开源项目也需要有人维护的

**Comment by kisslove** [comment]
@jiawenbin2013 试试配置fieldProps={{ beforeUpload: () => false }}去开启自定义上传
