### ISSUE TITLE
🐛[BUG] EditableProTable分页表格新增的问题

### ISSUE THREAD

**Issue by azx1985** [ant-design/pro-components#1621]
### 🐛 bug 描述
如果分页设置了10条数据，当前页也已经是10条数据了，点击新增就不能正常显示了

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
没考虑分页的情况，是个 bug

**Comment by chenshuai2144** [comment]
发现我自己是没办法实现这个功能的，太灵活了，而且性能不好。
用顶部添加吧

**Comment by azx1985** [comment]
我想用toolBarRender的自定义添加按钮，用recordCreatorProps里面position顶部添加没用
![image](https://user-images.githubusercontent.com/25195734/104875591-9c74e000-5990-11eb-9c96-d4cecd6dd64b.png)

**Comment by azx1985** [comment]
我想用toolBarRender自定义新增按钮，用recordCreatorProps里面的position添加顶部没用
![4B1A1DAB-A0E0-4d86-9222-4DBD1213F15C](https://user-images.githubusercontent.com/25195734/104875764-0beacf80-5991-11eb-9112-995e94b73126.png)
![6E220A4D-ABC8-4467-BCB2-3388ECF3CADB](https://user-images.githubusercontent.com/25195734/104875774-11481a00-5991-11eb-838e-9eaab1b68fa8.png)

**Comment by chenshuai2144** [comment]
是的，在这个地方配置一下  
```
 actionRef.current?.addEditRecord?.({
            id: (Math.random() * 1000000).toFixed(0),
            title: '新的一行',
           position:"top"
});
```

**Comment by azx1985** [comment]
还是不行，我用的是jsx,

 _b.call(_a, {
                    id: -1,
                    title: '新的一行',
                    position: 'top',
                  });

必填用formItemProps: { rules: [{ required: true, message: '此项为必填项' }] },取消点击没反应了

**Comment by chenshuai2144** [comment]
你这是写了个什么，乱码吗？

**Comment by azx1985** [comment]
。。。。按照第二个demo的js，添加了在call里添加了position: 'top',在columns里面添加了formItemProps: { rules: [{ required: true, message: '此项为必填项' }] }

**Comment by chenshuai2144** [comment]
call 是什么东西？

**Comment by BenLakes** [comment]
@chenshuai2144  这个编辑表格的分页功能  组件库可以加上 或开发者需要的话 有什么比较灵活的办法加上吗？

**Comment by chenshuai2144** [comment]
@BenLakes已经做了，等待明天发版本
