### ISSUE TITLE
👑 [需求]EditableProTable有没有api新增的时候直接能在第一行添加，不用在最后一行添加？

### ISSUE THREAD

**Issue by azx1985** [ant-design/pro-components#1622]

**Comment by chenshuai2144** [comment]
哪个组件要写清楚呀

**Comment by chenshuai2144** [comment]
改的真快，看一下 demo，第一个 demo 里面就有

**Comment by azx1985** [comment]
如果用第一个demo的recordCreatorProps是可以，我用的是自定义按钮recordCreatorProps就是false，就没办法设置position吧？

**Comment by chenshuai2144** [comment]
```
可以的

```typescript
recordCreatorProps = {
  // 顶部添加还是末尾添加
  position: 'end',
  // 不写 key ，会使用 index 当行 id
  record: {},
  // https://ant.design/components/button-cn/#API
  style:{
    display:"none"
  },
};
```
```

**Comment by azx1985** [comment]
好像不行，文档应该用双大括号吧

recordCreatorProps={{
          style: {
            display: 'none',
          },
          position: 'top',
        }}

**Comment by liangxp** [comment]
recordCreatorProps 指定 position: 'top', 确实好像不行！

**Comment by chenshuai2144** [comment]
使用的方式贴一下

**Comment by liangxp** [comment]
@chenshuai2144 <EditableProTable rowKey="skuId" 
                
                columns={skuColumns} 
                scroll={{ y: 300 }}
                recordCreatorProps={{
                  newRecordType: 'dataSource',
                  position: 'top',
                  creatorButtonText: '添加规格',
                  record: () => ({
                      skuId: Date.now(),
                  })
                }} 
                editable={{
                  editableKeys,
                  onChange: setEditableRowKeys,
                  actionRender: (row, _, dom) => [dom.save,dom.delete, dom.cancel]
                }}/>
            </ProForm.Item>

**Comment by chenshuai2144** [comment]
看起来没什么问题，这样应该是能跑起来的
