### ISSUE TITLE
请问支持antd-pro  v3版本吗？🧐[问题]

### ISSUE THREAD

**Issue by lishaoh** [ant-design/pro-components#1624]

**Comment by chenshuai2144** [comment]
需要antd@4.0, 对 pro 的版本没有关系

**Comment by lishaoh** [comment]
@chenshuai2144 pro现在是v3版本，对应的antd也是v3版本，如果想使用ProTable等依赖包需要将antd升级到@4.0？那样对于v3版本的pro就会不兼容吧

**Comment by chenshuai2144** [comment]
V3和v4可以用兼容包来解决

**Comment by lishaoh** [comment]
@chenshuai2144 请问有兼容包地址吗

**Comment by chenshuai2144** [comment]
@lishaoh  去antd 官网看看，完善的迁移方案
