### ISSUE TITLE
🧐[问题] Pro Layout 的二級選單的 selected 能否與一級選單一致？

### ISSUE THREAD

**Issue by kudorori** [ant-design/pro-components#1626]
### 🧐 问题描述

Pro Layout 的二級選單的 selected 能否與一級選單一致？

### 💻 示例代码

https://codesandbox.io/s/ant-pro-layout-issue-ozlfg?file=/src/App.js

### 🚑 其他信息

預期：
當url = "/a/b"的時候，只亮起 2 -> 2-3 的 Menu

結果：
當url = "/a/b"的時候，卻亮起了 2 -> 2-1, 2-3 的Menu

**Comment by chenshuai2144** [comment]
不行的，你搞得不一样一些吧，这种规则没有任何规律。

你可以用openKeys 来自定义的，全受控的
