### ISSUE TITLE
🐛[BUG] Pro-Table 2.4.4版本和v2.5.4打包的大小相差1M

### ISSUE THREAD

**Issue by Nokecy** [ant-design/pro-components#163]
v2.5.4
![image](https://user-images.githubusercontent.com/12318131/89992663-2ae58700-dcb8-11ea-8b70-19bba14e5ff9.png)
v2.4.4
![image](https://user-images.githubusercontent.com/12318131/89992750-4e103680-dcb8-11ea-9320-a21da5abd683.png)

**Comment by afc163** [comment]
size-limit 没起到作用。@WynterDing

**Comment by Nokecy** [comment]
引入pro-layout 也是一样，pro-table和pro-layout 任意引入一个
![image](https://user-images.githubusercontent.com/12318131/89992997-aba48300-dcb8-11ea-94cf-514e3bb7d8d2.png)

**Comment by chenshuai2144** [comment]
@Nokecy 没有默认使用 es 导致的，是 package.json 配置错了

**Comment by Nokecy** [comment]
@chenshuai2144  最新版pro-table没有问题了，但是pro-layout好像还是有问题。
![image](https://user-images.githubusercontent.com/12318131/90081917-139eac00-dd41-11ea-8d3f-e69f6602b6a7.png)

**Comment by Nokecy** [comment]
使用的是UMI最新版本的的layout插件

**Comment by chenshuai2144** [comment]
再试试 treeshaking应该已经生效了

**Comment by Nokecy** [comment]
应该是umi中的layout插件的锅~~~~~
