### ISSUE TITLE
👑 [需求] Protable columns dataIndex参数增强类型

### ISSUE THREAD

**Issue by newketom** [ant-design/pro-components#1630]
### 🥰 需求描述
背景:
项目使用[NSwag](https://github.com/RicoSuter/NSwag/wiki/TypeScriptClientGenerator)从后端openapi生成typescript接口和类。
当表格数据属性发生改变的时候，由于columns的dataIndex是字符串类型，所以无法及时爆红。

### 🧐 解决方案

dataIndex取自ProColumns<T>的泛型接口
通常来说可以反射其属性名
目前使用ts-simple-nameof npm包可满足需求，但不够优雅
```
    {
      title: '分类',
      dataIndex: nameof<ISearchCommodityResponse>(x=>x.categoryName),
      search: false,
      render: (_, record) => [<a key="link">{record.categoryName}</a>],
    },
```

期望可以内置此方法

**Comment by chenshuai2144** [comment]
这个的确是可以考虑一下，做个提示出来，你可以去antd 那边搞一下，从底层上解决这个问题

**Comment by chenshuai2144** [comment]
这个是做不了的，如果这样做了那么必须就要用写死的类型了，不能自定义了

**Comment by newketom** [comment]
我的理解: 
![image](https://user-images.githubusercontent.com/56467036/108220353-9b8ec400-7171-11eb-8123-a82b9bcb751d.png)

**Comment by chenshuai2144** [comment]
这个有点复杂了，等 typescript 想办法吧
