### ISSUE TITLE
🐛[BUG]ProTable使用renderFormItem自定义渲染时rules会应用到查询表单

### ISSUE THREAD

**Issue by ChenCheng220** [ant-design/pro-components#1633]
### 🐛 bug 描述

#696 这个Bug貌似在最新版本依旧存在

### 📷 复现步骤

column中使用renderFormItem并定义formItemProps.rules

### 🏞 期望结果

查询表单不应该显示*（必选）

### 💻 复现代码

```
 {
      title: '所属机构',
      dataIndex: 'departmentId',
      renderFormItem: () => <TreeSelect treeData={treeData} allowClear placeholder="请选择" />,
      formItemProps: { rules: [{ required: true }] },
 }
```

### © 版本信息

- ProTable 版本: 2.25.1
- umi 版本
- 浏览器环境 Chrome
- 开发环境 mac OS

### 🚑 其他信息

<img width="359" alt="截屏2021-01-15 上午9 45 51" src="https://user-images.githubusercontent.com/45256920/104670273-7b08bf80-5716-11eb-8029-0ca4c10d65e6.png">

**Comment by chenshuai2144** [comment]
这个是用来开口子的，我提供一个开发的方法吧
