### ISSUE TITLE
🧐[问题] protable 页面加载会有闪烁感，有什么办法优化吗？

### ISSUE THREAD

**Issue by wecliang** [ant-design/pro-components#1637]
### 🧐 问题描述
protable 切换页面时会先显示空白页，后刷新出搜索列和table内容，来回切换页面闪烁感很严重

### 🚑 其他信息
当前使用版本 
@ant-design/pro-layout": "^6.9.7
@ant-design/pro-table": "^2.19.0

**Comment by chenshuai2144** [comment]
来个 diff？

**Comment by wecliang** [comment]
嗯，组件优化吗?   protable 有没有阉割版本，会不会好一些？

**Comment by chenshuai2144** [comment]
看个图片试试，我看看什么在卡顿

**Comment by wecliang** [comment]
> 看个图片试试，我看看什么在卡顿

form 表单第一时间没有加载出来，后续加载会造成页面闪动

![image](https://user-images.githubusercontent.com/45417192/104861657-b8b25600-596b-11eb-9662-9d2ecdf9fadf.png)
![image](https://user-images.githubusercontent.com/45417192/104861556-46da0c80-596b-11eb-8871-dacba193a0c6.png)

**Comment by chenshuai2144** [comment]
升级一下版本吧。新版本 useEffect 之前表单就初始化成功了。

原来是在 useEffect  之后

**Comment by wecliang** [comment]
> 升级一下版本吧。新版本 useEffect 之前表单就初始化成功了。
> 
> 原来是在 useEffect 之后

我现在升级最新版本2.26.0 ，还是会有此问题，
![image](https://user-images.githubusercontent.com/45417192/104878118-4b67ea80-5996-11eb-81c9-bc9c2e37e93c.png)
使用 renderToString 渲染的富文本中依然没有表单内容

**Comment by chenshuai2144** [comment]
renderToString  需要用 value 和 onchange 封装。和 antd 的 form 是相同的

**Comment by wecliang** [comment]
现在有个问题我使用protable 页面切换时，这个form还是会后加载，没和table同步渲染。我该怎么去消除这个影响呢

**Comment by wecliang** [comment]
> renderToString 需要用 value 和 onchange 封装。和 antd 的 form 是相同的

那要怎么去做呢，没有思路。现在form表单还是会异步加载，没有和table同步渲染，切换起来会产生闪烁感
