### ISSUE TITLE
👑 [需求]ProForm支持泛型

### ISSUE THREAD

**Issue by y-young** [ant-design/pro-components#1638]
### 🥰 需求描述

目前ProForm的onFinish参数类型为`Record<string, any>`，希望ProForm能像ProTable一样支持泛型，如：
```tsx
<ProForm<DataType> .../>
```
这样`onFinish`有明确的参数类型，便于适配API，如：
```typescript
const onFinish = (formData: DataType) => {
    await api.send(formData)
}
```

### 🧐 解决方案

适配Ant Design Form的泛型

### 🚑 其他信息

ref: [feat: Form support generic type](https://github.com/ant-design/ant-design/pull/25937/)

**Comment by chenshuai2144** [comment]
ProForm 创建的太久了，不支持还能不能支持上来
