### ISSUE TITLE
🐛[BUG] [Pro-Layout] 在IOS系统上展开二级菜单，会导致动画渲染崩溃

### ISSUE THREAD

**Issue by bandaot** [ant-design/pro-components#164]
### 🐛 bug 描述

在IOS系统上展开二级菜单，会导致动画渲染崩溃

### 📷 复现步骤

1. 使用iPhone手机浏览器（Chrome或者Safari）打开 https://preview.pro.ant.design/dashboard/analysis 页面
2. 点开Menu
3. 点开二级菜单，直到出现滚动条
4. 看到菜单渲染崩溃了，内容出现白屏

### 🏞 期望结果

菜单能够正常渲染

### 💻 复现代码

通过下面的代码可以hot fix掉这个问题：

    .ant-menu-submenu-arrow,
    .ant-menu-submenu-arrow::before,
    .ant-menu-submenu-arrow::after {
      transition: none !important;
    }

感觉是箭头动画和滚动条出现有冲突，导致浏览器渲染崩溃了。

### © 版本信息

- ProLayout 版本:  6.2.1
- umi 版本 3.2.13
- 浏览器环境 Safari/Chrome
- 开发环境 IOS

### 🚑 其他信息

![WeChat Image_20200812173709](https://user-images.githubusercontent.com/4526370/90000272-861c7700-dcc2-11ea-8b6c-199abb0a91e8.jpg)

**Comment by chenshuai2144** [comment]
关掉了全部的动画应该没问题了
