### ISSUE TITLE
🐛[BUG]调用setLoading后，再次调用await actionRef.current.reload()，查询操作不触发

### ISSUE THREAD

**Issue by cuihq2005** [ant-design/pro-components#1643]
### 🐛 bug 描述

在protable中删除行时，调用setLoading设置loading动画，loading过程冲执行删除，删除成功后重新reload，reload结束后，设置loading=false。该行为以前是ok的，最近升级版本，发现删除后reload操作不刷新页面。代码如下

```
  const onDelete = async (record) => {
    setLoading(true);
    try {
      const response = await remove(record);
      if (response.success) {
        await actionRef.current.reloadAndRest();
      }
    } finally {
      if (!unmounted.current) setLoading(false);
    }
  };
```

在复现bug的过程中，发现只要setLoading了，actionRef.current.reloadAndRest()操作就不会触发,即下面的代码不会触发reload
```
  const onDelete = async (record) => {
    setLoading(true);
    try {
      await actionRef.current.reload();
    } finally {
      if (!unmounted.current) setLoading(false);
    }
  };
```

如果我去除reload上的await，reload可正确执行刷新的动作，但loading的动画会在reload执行完成前结束，这不是我期望的结果（我选择自己控制loading，以防止delele和reload之间roading动画会短暂中断）

```
  const onDelete = async (record) => {
    setLoading(true);
    try {
      actionRef.current.reload();
    } finally {
      if (!unmounted.current) setLoading(false);
    }
  };
```

而如果我不设置setLoading，reload也可以正确触发

```
  const onDelete = async (record) => {
    try {
      actionRef.current.reload();
    } finally {
    }
  };
```

### 🏞 期望结果

期望reload可正确触发

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] 
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by cuihq2005** [comment]
试着退了几次版本，protable 2.9.12是好使的，2.15.0有问题。网速太慢，中间的没有试

**Comment by chenshuai2144** [comment]
看起来你把 bug 当成 feature 了。 来个示例代码？

**Comment by cuihq2005** [comment]
> 看起来你把 bug 当成 feature 了。 来个示例代码？

这个真没觉得是bug，reload出不来东西才是bug吧

示例代码：https://codesandbox.io/s/zen-khayyam-f5jgy

![image](https://user-images.githubusercontent.com/6793036/104978153-32197980-5a3c-11eb-9a3e-2910a7341849.png)

上图圈起来的await删除掉后，新建和删除能刷新出数据；留着刷新不出来数据

**Comment by chenshuai2144** [comment]
await 可能挂了。你 catch 一下错误是什么？

**Comment by cuihq2005** [comment]
> await 可能挂了。你 catch 一下错误是什么？

![image](https://user-images.githubusercontent.com/6793036/104978904-ee277400-5a3d-11eb-9572-e6e52c45450f.png)
加了try catch，控制台什么都没有

**Comment by chenshuai2144** [comment]
你在 await 下面写个console，看看是不是被堵塞了

**Comment by cuihq2005** [comment]
> 你在 await 下面写个console，看看是不是被堵塞了

应该不是，阻塞了的话，finally里的setLoading(false)不会被调用，动画消失不了。不过以前尝试过调用reset，好像动画一直不消失，我试一下

**Comment by cuihq2005** [comment]
> > 你在 await 下面写个console，看看是不是被堵塞了
> 
> 应该不是，阻塞了的话，finally里的setLoading(false)不会被调用，动画消失不了。不过以前尝试过调用reset，好像动画一直不消失，我试一下

![image](https://user-images.githubusercontent.com/6793036/105005139-de288800-5a6f-11eb-86cb-6b3729bf4e8e.png)

reload不足塞，但也不刷新；reset阻塞

**Comment by chenshuai2144** [comment]
👌，我理一下这个 aync，里面请求有点乱

**Comment by chenshuai2144** [comment]
已经修复了，全部处理了一下
