### ISSUE TITLE
🐛[BUG]浮层表单 Modal 表单项width的bug

### ISSUE THREAD

**Issue by gujiwuqing** [ant-design/pro-components#1646]
### 🐛 bug 描述

浮层表单 Modal 表单项有些width为md，sm等，vscode提示只有m。s等，没有md，sm
### 📷 复现步骤

复制代码去编辑器，就能发现提示的报错了
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
更新一下依赖吧，依赖可能太老了。和 antd 统一了一下用法
