### ISSUE TITLE
🐛[BUG]ModalForm浮层表单，如果采用state来控制的话onVisibleChange接收不到visible==true的情况

### ISSUE THREAD

**Issue by zplzpl** [ant-design/pro-components#1649]
### 🐛 bug 描述

使用 state 来控制可以使用 visible 和 onVisibleChange 来控制打开与关闭
ModalForm的onVisibleChange 方法，是接收不到，打开的情况，只能接收到关闭的情况(visible==false)

### 🏞 期望结果

使用 state 来控制可以使用 visible 和 onVisibleChange 来控制打开与关闭
onVisibleChange 方法能接收打开、关闭的状态

### 💻 复现代码

```
<ModalForm
            title={renderTitle()}
            trigger
            visible={modalVisible}
            onVisibleChange={onVisibleChange}
            modalProps={{
                onCancel: () => {
                    handleModalVisible()
                },
            }}
            initialValues={{
                hidden: 0,
            }}
            onFinish={handleOnFinish}
        >
            {renderContent()}
        </ModalForm >
```

### © 版本信息

- ProComponents 版本: "@ant-design/pro-form": "^1.13.10",
- umi 版本 "umi": "^3.3.5"
- 浏览器环境 chrome
- 开发环境 windows

**Comment by sputnikW** [comment]
fix 这个 bug带来了一个breaking change：之前刚打开一个DrawerForm时不会调用onVisibleChange，现在却会了。

在这种情况下会导致BUG：之前可以把onVisibleChange当作onClose使用（因为第一次打开不会调用它），现在这种用法会导致无法正常打开Drawer（刚打开就调用了onVisibleChange）。

**Comment by chenshuai2144** [comment]
onVisibleChange 里面判断一下 visible 是 true 还是 false
