### ISSUE TITLE
🧐[问题]valueType=dateRange的疑问

### ISSUE THREAD

**Issue by zim-lee** [ant-design/pro-components#165]
### 🧐 问题描述

以前的用法就是查询表单可以选择查询某个时间端的数据，这在我这里算是正常的业务逻辑，现在新版本的居然变成了表格中的数据也展示成一个区间，这是什么业务才有的数据展现模式，非常不理解为什么要改成这样！！

**Comment by chenshuai2144** [comment]
dateRange 代表时间区间，应该是 ` [startTime,endTime]`

**Comment by blinkMyEyesConsciously** [comment]
![image](https://user-images.githubusercontent.com/38968979/90090543-dc3afa00-dd56-11ea-8b0b-45211f52e8e2.png)
之前列表里是直接显示字符的;使用renderText也改不了.    之前是可以显示的

**Comment by chenshuai2144** [comment]
来个配置

**Comment by blinkMyEyesConsciously** [comment]
![image](https://user-images.githubusercontent.com/38968979/90090697-48b5f900-dd57-11ea-9c45-df52bfd50a3a.png)
@chenshuai2144

**Comment by blinkMyEyesConsciously** [comment]
![image](https://user-images.githubusercontent.com/38968979/90091616-73a14c80-dd59-11ea-9e2c-3bd8e2da9610.png)
如果 valueType是dateRange  那renderText必须返回一个数组才生效

**Comment by blinkMyEyesConsciously** [comment]
![image](https://user-images.githubusercontent.com/38968979/90107025-d2c38900-dd7a-11ea-83e5-3b8260b0cde5.png)
如果我给他提供了renderText ,就不应该再执行defaultRenderText的类型转换. 或者defaultRenderText传入的valueType 应该为text.

**Comment by l745230** [comment]
在2.4.2 版本还是正常的.

顺便问下,你这个写法,传到后端的createDateTime[0]=2020-08-11 createDateTime[1]=2020-08-30  这种参数,后端是怎么处理的..

**Comment by blinkMyEyesConsciously** [comment]
@l745230  在beforeSearchSubmit 在个函数里面处理将他的值改变
![image](https://user-images.githubusercontent.com/38968979/90112530-b1ff3180-dd82-11ea-939d-17a979d96f0b.png)

**Comment by l745230** [comment]
@blinkMyEyesConsciously 学习了! 原来还有这么个方法可以手动处理参数的.

**Comment by meyerlee** [comment]
2.4的逻辑比较合理， Range表示是范围查询，显示还是一个字段。

**Comment by blinkMyEyesConsciously** [comment]
请换成render方法使用, 不再使用renderText .  2.4版本那是个bug

**Comment by l745230** [comment]
> 请换成render方法使用, 不再使用renderText . 2.4版本那是个bug

这个是不是在文档上给个demo说明下啊.  个人也觉得2.4.2的处理更符合常人的理解.

**Comment by chenshuai2144** [comment]
renderText 的文档上写的是 render 之前的处理

**Comment by dmdoit** [comment]
跟你遇到一摸一样的问题，我也觉得2.4的版本对dateRange这是时间范围的处理更合理一些，
我们后台给我返回的是毫秒时间戳，现在table使用时间范围展示，不太合理，我觉得像时间范围这种展示的格式我们可以自己用renderText定义，然后只需要把serach搜索里根据valueType: 'dateRange' 变成时间范围组件，不要限制的太死，通用性还是很重要的

**Comment by dmdoit** [comment]
比如我是下单时间是一个具体的时间，但是我搜索时需要的是搜索某一个时间段内的下单数据

**Comment by mapleflow** [comment]
render 大法好
@l745230 后端 split 一样处理，前后端谁处理都行
```
{
      title: '创建时间',
      dataIndex: 'create_time',
      valueType: 'dateRange',
      render: (_: string, record: object) => (
        record['create_time']
      ),
},
```

**Comment by zim-lee** [comment]
看来大家的业务基本都是如此啊，也不知道大佬改成这样是基于什么业务场景定的:smirk:
