### ISSUE TITLE
🧐[问题]使用ProForm包裹<Form.Item <ProTable页面只能刷新首次添加的数据

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#1655]
### 🧐 问题描述

页面只能加载出来首次添加的数据，首次添加如果1条就显示1条，5条就显示5条，后续添加form.getFieldValue('goodss')是有数据的，但是ProTable没显示出来，求解~~

ProForm配置如下
![image](https://user-images.githubusercontent.com/12421552/104842782-f24e7700-5901-11eb-9081-b4fb2a543296.png)

Form.Item和ProTable配置如下
### 💻 示例代码
![微信图片_20210117202231](https://user-images.githubusercontent.com/12421552/104842759-c9c67d00-5901-11eb-8b1a-63cce88c4297.png)

**Comment by chenshuai2144** [comment]
如果你不是很懂 form是这么绑定数据的，用可编辑表格吧，他会自动绑定value 和 onChange。

如果你要使用默认的 table 的，需要配置 valuePropName 和 trigger 

https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

**Comment by edifangyi** [comment]
@chenshuai2144  
![image](https://user-images.githubusercontent.com/12421552/104864267-74c34f00-5973-11eb-8c68-2e7ea0dfe310.png)
我直接这么使用好像不对吧

**Comment by edifangyi** [comment]
![image](https://user-images.githubusercontent.com/12421552/104864930-7a219900-5975-11eb-8829-1b6ec85831a3.png)

@chenshuai2144 
请问这么操作对吗？？？
我看了关于From.Item
被设置了 name 属性的 Form.Item 包装的控件，表单控件会自动添加 value（或 valuePropName 指定的其他属性） onChange（或 trigger 指定的其他属性），数据同步将被 Form 接管，
你不能用控件的 value 或 defaultValue 等属性来设置表单域的值，默认值可以用 Form 里的 initialValues 来设置。注意 initialValues 不能被 setState 动态更新，你需要用 setFieldsValue 来更新。
你不应该用 setState，可以使用 form.setFieldsValue 来动态改变表单值。

**Comment by chenshuai2144** [comment]
这样操作是对的。表单数据是双向绑定的和 react 默认的有点不同

**Comment by edifangyi** [comment]
@chenshuai2144 不得行~还是刷新不出来，问题还是只加载第一次录入数据

**Comment by edifangyi** [comment]
![image](https://user-images.githubusercontent.com/12421552/104978517-f206c680-5a3c-11eb-833f-8bb0a0a75738.png)
@chenshuai2144  我把Table单独提出来，
![image](https://user-images.githubusercontent.com/12421552/104978543-ff23b580-5a3c-11eb-94ef-6f08652b18e2.png)
添加数据，useEffect只会更新一次，似乎
          form.setFieldsValue({
            goodss: dataSource,
          });
只执行了一次
![image](https://user-images.githubusercontent.com/12421552/104978615-31351780-5a3d-11eb-9a76-7122c5582c50.png)

**Comment by chenshuai2144** [comment]
是不是form 不对呀，你操作一下表单，应该会触发onChanger

**Comment by edifangyi** [comment]
![image](https://user-images.githubusercontent.com/12421552/104999750-555a1e00-5a68-11eb-8d2f-df44c65fd87c.png)
@chenshuai2144 列表第一次录入数据，onValuesChange就没有执行。
![image](https://user-images.githubusercontent.com/12421552/104999860-88041680-5a68-11eb-9881-3bad9bc12685.png)
![image](https://user-images.githubusercontent.com/12421552/104999898-93574200-5a68-11eb-89ae-25183728fa06.png)
