### ISSUE TITLE
🐛[BUG]proListmeta应该为可选

### ISSUE THREAD

**Issue by yehuozhili** [ant-design/pro-components#1656]
### 🐛 bug 描述

 使用官方例子粘贴来 ts会报错：
类型“{ dataIndex: string; search: string; title: string; }”缺少类型“Pick<any, "title" | "search" | "dataIndex" | "valueType" | "render" | "valueEnum">”中的以下属性: valueType, render, valueEnumt

传递metas属性是发生

https://github.com/ant-design/pro-components/blob/master/packages/list/src/index.tsx#L16

**Comment by chenshuai2144** [comment]
这个类型看起来没问题，应该是你写死了 utils 的版本，删除掉再安装一下试试

**Comment by yehuozhili** [comment]
确实是这样
