### ISSUE TITLE
🐛[BUG] Layout 6.4.4 菜单点击其它项不立即收起原已展开的

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#166]
### 💻 复现代码

Preview 也会这情况
https://preview.pro.ant.design

### © 版本信息

- ProComponents 版本: 6.4.4
- umi 版本 3.2.14
- 浏览器环境 Chrome 86
- 开发环境 Windows 10

**Comment by hihuangwei** [comment]
@chenshuai2144 V6.4.4 问题依旧存在

**Comment by chenshuai2144** [comment]
还没发版本 今天早上发 还有别的bug要修

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/175
