### ISSUE TITLE
🧐[问题]ProTable组件如何实现替换整个搜索栏，自定义的搜索栏如何配合request属性进行查询 

### ISSUE THREAD

**Issue by wmf508** [ant-design/pro-components#1660]
### 🧐 问题描述
其实就是如何手动触发搜索并且传入搜索参数

**Comment by chenshuai2144** [comment]
tableRender | 自定义渲染表格函数 | (props,dom,domList:{ toolbar,alert,table}) => ReactNode | -
params | 用于 request 查询的额外参数，一旦变化会触发重新加载 | object | -
-- | -- | -- | --


搭配起来使用一下。

不建议自定义，自定义不一定会好，但是默认的一定不坏

**Comment by leonardo-zhu** [comment]
如果我需要往添加一个额外的表单搜索项，那我该如何操作？目前看来是只能基于 column 去生成? @chenshuai2144

**Comment by chenshuai2144** [comment]
可以dataIndex 配置 hideInTable ，renderFormItem 自定义一把

**Comment by MilkJie** [comment]
ProTable如何设置搜索框收起的时候第一行第三个搜索框不被搜索查询遮盖?
