### ISSUE TITLE
🐛[BUG]Pro V5版本TS下使用Drawer组件控制台报warning

### ISSUE THREAD

**Issue by wmf508** [ant-design/pro-components#1661]
### 🐛 bug 描述
Warning: React does not recognize the `scrollLocker` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `scrolllocker` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
_

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
更新antd ，antd 引入的属性泄露
