### ISSUE TITLE
🧐[问题]renderFormItem必须要将 props 中的 value 和 onChange 必须要被赋值，跪求路过的好心人，写半天怎么写都不对

### ISSUE THREAD

**Issue by ray1347227** [ant-design/pro-components#167]
### 🧐 问题描述

我卡住了，不知道怎么写才是对的，必须要被赋值是怎么赋值，求助各位好心人

### 💻 示例代码
1、这样写onChange可以执行，但是request的params里拿不到参数
![image](https://user-images.githubusercontent.com/21354564/90013907-c25ad200-dcd8-11ea-8b3a-40dbf897f6d8.png)
2、这样写request的params里能拿到参数，但是自己的onChange事件不执行
![image](https://user-images.githubusercontent.com/21354564/90014085-0f3ea880-dcd9-11ea-9239-7ddf4ef29be4.png)

**Comment by chenshuai2144** [comment]
你忘了给 onChange 参数了

```
{
  renderFormItem: (item, { onChange }) => (
    <Input
      onChange={(e) => {
        onChange(e);
        onmyChange(e);
      }}
    />
  );
}
```

**Comment by ray1347227** [comment]
> 你忘了给 onChange 参数了
> 
> ```
> {
>   renderFormItem: (item, { onChange }) => (
>     <Input
>       onChange={(e) => {
>         onChange(e);
>         onmyChange(e);
>       }}
>     />
>   );
> }
> ```

感谢，以解决

**Comment by wenbolwm** [comment]
我也遇到同样的问题，谢谢解答
