### ISSUE TITLE
👑 [需求]如何设置查询列表 查询项为必填

### ISSUE THREAD

**Issue by ZhengHuang-20** [ant-design/pro-components#1671]
如何设置查询列表 查询项为必填
[https://github.com/ant-design/ant-design/discussions/28907](url)

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/table#%E5%BF%85%E5%A1%AB%E7%9A%84%E6%9F%A5%E8%AF%A2%E8%A1%A8%E5%8D%95

刚加的新功能

**Comment by ZhengHuang-20** [comment]
”form={{
ignoreRules: false,
}}

刚加的新功能“   这句话没太懂 是在ProTable属性中配置吗？当前版本能够使用吗

**Comment by chenshuai2144** [comment]
嗯，是的。
在 ProTable 中设置 

```
form={{
  ignoreRules: false,
}}
```
