### ISSUE TITLE
👑 [需求]EditableProTable 如何获取到form的validateFields和其他属性

### ISSUE THREAD

**Issue by fatesq** [ant-design/pro-components#1674]

**Comment by chenshuai2144** [comment]
为什么要这么做呢？

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it

**Comment by fatesq** [comment]
> 为什么要这样做呢？

就是整个表单中有一部分是表格形式的表单，需要随着整个表单校验提交

**Comment by chenshuai2144** [comment]
支持了 form，你可以配置一下form 然后操作编辑表格

**Comment by zhuiluo0987** [comment]
> 支持了 form，你可以配置一下form 然后操作编辑表格

一列一列的校验方式有吗？我校验一列名称不重复。我第一行第一列输入‘AA’， 第二行第一列输入‘AA’【此时校验失败，出现红框】。此时修改第一行第一列‘AA’为‘BB’。 如何让第二列红框消失
