### ISSUE TITLE
👑 [需求] 支持获取 Pro Table 的baseTableDom -form实例

### ISSUE THREAD

**Issue by Veath** [ant-design/pro-components#1675]
### 场景
自定义 `table title`，实现`form search`。当添加`Form.Item`到`columns.title`后。因为下面的代码，无法获取到对应`Form`实例。从而无法实现`title form`重置和搜索功能。
```js
 /** 默认的 table dom，如果是编辑模式，外面还要包个 form */
  const baseTableDom = (
    <Form component={false} onValuesChange={editableUtils.onValuesChange}>
      <Table<T> {...tableProps} rowKey={rowKey} tableLayout={tableLayout} />
    </Form>
  );
```
### 🧐 解决方案
希望上面`baseTableDom`支持传入ref 哈

**Comment by Veath** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
这个form 是用来做可编辑表格的，不能被你修改掉。

你想实现的效果方便给个 giff 吗？

**Comment by Veath** [comment]
![image](https://user-images.githubusercontent.com/15187953/104978501-e87d5e80-5a3c-11eb-81c2-8fdea044ecfb.png)
嗯嗯，我想实现在表头添加form search 功能

**Comment by chenshuai2144** [comment]
。。。这个交互的太鬼畜了把

**Comment by Veath** [comment]
@chenshuai2144 请问可以加吗？ 或者给个name 属性， 然后我通过Form.Provider 获取

**Comment by chenshuai2144** [comment]
我正在想办法，可编译表格也需要这个 form，我到时候一起处理进去

**Comment by chenshuai2144** [comment]
支持了 看看这个 
https://github.com/ant-design/pro-components/pull/1879
