### ISSUE TITLE
🧐ModalForm设置initialValues有延迟

### ISSUE THREAD

**Issue by zhang0ZGC** [ant-design/pro-components#1676]
### 🧐 问题描述

我想做表格数据的编辑表单，点击编辑时，ModalForm的initialValues设置为本次的数据，但是点击打开后，表单值还是第一次的初始值。

但是点击Modal的『取消』按钮再打开就是后面设置的那个值，如果多次点取消打开，表单的值一直是前一次设置的数据。

另外如果点击ModalForm右上角的『x』或者点击Modal外面关闭，下次打开，表单数据还是之前的数据。

### 💻 示例代码

https://codesandbox.io/s/fervent-mendel-c2x6l?file=/App.tsx

### 🚑 其他信息

![aaa](https://user-images.githubusercontent.com/10346399/104915666-f0e98100-59cb-11eb-95bd-ad2ed94029e4.gif)

**Comment by zhang0ZGC** [comment]
可能是我理解的有问题，点击取消会重置表单，但不是销毁，打开表单的时候并不会先重置表单，所以会出现这个情况，所以就直接使用一个formRef传进去，点击修改的时候使用通过form修改值吧

**Comment by cocochenandlily** [comment]
@zhang0ZGC  你好，我也遇到了类似的问题，就是通过state改变数据后，form中的字段值没有立刻更新，但是点击关闭后数据会更新上去，我目前的解决方法是通过是否可见来决定是否需要重新渲染form，但是这样子加载起来稍微有点慢，我不是专业的前端，我想问下你前面的方法具体是怎么写来着

**Comment by chenshuai2144** [comment]
@cocochenandlily 可以用 `formRef.current.setFieldvalues`

**Comment by zhang0ZGC** [comment]
> @zhang0ZGC 你好，我也遇到了类似的问题，就是通过state改变数据后，form中的字段值没有立刻更新，但是点击关闭后数据会更新上去，我目前的解决方法是通过是否可见来决定是否需要重新渲染form，但是这样子加载起来稍微有点慢，我不是专业的前端，我想问下你前面的方法具体是怎么写来着

如陈帅所说的
```jsx
const formRef = useRef();

return (<ModalForm form={formRef} >...</ModalForm>);
```
编辑的时候用 `formRef.current.setFieldvalues({...})`  手动设置一下表单的值

关闭 Modal 的时候根据可能有重置表单的操作，这个反正看需要吧

**Comment by cocochenandlily** [comment]
> @cocochenandlily
> 
> 如陈帅所说的
> 
> ```js-jsx
> const formRef = useRef();
> 
> return (<ModalForm form={formRef} >...</ModalForm>);
> ```
> 
> 编辑的时候用 `formRef.current.setFieldvalues({...})` 手动设置一下表单的值
> 
> 关闭 Modal 的时候根据可能有重置表单的操作，这个反正看需要吧

哦哦 谢谢 老哥

**Comment by itsXX** [comment]
加上这个就好了
`useEffect(() => {
        form.resetFields();
        form.setFieldsValue(props.values);
    })`
