### ISSUE TITLE
🧐[问题]如何在antd Pro v5里面修改 header 的background-color

### ISSUE THREAD

**Issue by yilo** [ant-design/pro-components#1678]
### 🧐 问题描述

在antd v5 pro 里面src下面没有layouts 目录了，default就使用了 pro-layout，现在找不到如何修改 layout header
的background-color
### 💻 示例代码

![image](https://user-images.githubusercontent.com/3793679/104919417-2ba1e800-59d1-11eb-9ec0-19d3def2d0f4.png)

![image](https://user-images.githubusercontent.com/3793679/104919469-42e0d580-59d1-11eb-9c97-e4d01597abbe.png)

**Comment by Znonymous29** [comment]
看[说明文档](https://beta-pro.ant.design/docs/style-cn#%E8%A6%86%E7%9B%96%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F)，可以覆盖[组件样式](https://github.com/ant-design/pro-components/blob/76b3f2929c5a5dcd4ed78e723b2a01e3a5cdfbf5/packages/layout/src/components/GlobalHeader/index.less)。

**Comment by chenshuai2144** [comment]
用css 硬写就好了
