### ISSUE TITLE
🐛[BUG] ProComponent Protable Demo展示 样式缺失

### ISSUE THREAD

**Issue by BigFaceMaster** [ant-design/pro-components#1680]
### 🐛 bug 描述
如题
https://procomponents.ant.design/components/table/
![image](https://user-images.githubusercontent.com/15710933/104982922-a0633980-5a46-11eb-9cc9-3b004dfa9f72.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by BigFaceMaster** [comment]
同时，从展示下方跳转到 codesandbox 发现 codesandbox中package.json 缺少@ant-design/pro-table

**Comment by chenshuai2144** [comment]
重新部署了一下，看起来触发了一个 dumi 的bug

**Comment by chenshuai2144** [comment]
> 同时，从展示下方跳转到 codesandbox 发现 codesandbox中package.json 缺少@ant-design/pro-table

这个 dumi 会改的

**Comment by BigFaceMaster** [comment]
好嘞
