### ISSUE TITLE
ProTable组件查询参数没有和URL参数同步🐛[BUG]

### ISSUE THREAD

**Issue by beysong** [ant-design/pro-components#1681]
### 🐛 bug 描述

重置按钮没有同步清除查询参数
#317 

### 📷 复现步骤

搜索后，点击重置按钮

### 🏞 期望结果

清空搜索表单

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="690" alt="截屏2021-01-19 下午12 40 56" src="https://user-images.githubusercontent.com/5705613/104988698-b9261c00-5a53-11eb-83f6-70f35c101ade.png">

**Comment by ccloveak** [comment]
你select应该是期望回到默认值吧？

**Comment by chenshuai2144** [comment]
fixed  in https://github.com/ant-design/pro-components/pull/1709
