### ISSUE TITLE
实时保存的编辑表格🐛[BUG]

### ISSUE THREAD

**Issue by 1195002442** [ant-design/pro-components#1682]
### 🐛 bug 描述

“保存数据”按钮无反应

### 🏞 期望结果

点击“保存数据”按钮，获取全部的已修改后的数据，并且表格不可编辑

### 💻 复现代码

https://codesandbox.io/s/tender-herschel-7mvu4?file=/App.tsx

**Comment by chenshuai2144** [comment]
加了个 console
