### ISSUE TITLE
自定义组件用Form.Item包裹后，该自定义项不能被form表单管理

### ISSUE THREAD

**Issue by Huangruolan** [ant-design/pro-components#1687]
自定义组件用Form.Item包裹后，之前这个自定义项还能被form表单管理，从昨天开始突然不行了，直接复制文档上的混合使用部分代码，直接就没有暴露组件了

**Comment by chenshuai2144** [comment]
看看你的 value 和 change 是不是被重写了

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
