### ISSUE TITLE
🧐 ProTable 的 `formRef` ts 类型描述可能不当

### ISSUE THREAD

**Issue by aweiu** [ant-design/pro-components#1688]
### 🧐 问题描述

ProTable 的 `formRef` ts 类型描述可能不当

### 💻 示例代码

见此条 [comment](https://github.com/ant-design/pro-components/commit/b4b218fb68c6f30d1428ec5c4ff085f87d960ac5#r46099755)

**Comment by chenshuai2144** [comment]
就是为了不让别的用fuction，已经不适合这个版本了
