### ISSUE TITLE
protable怎么能够通过拖拽表格改变列宽🧐[问题]

### ISSUE THREAD

**Issue by walry** [ant-design/pro-components#1701]
### 🧐 问题描述

antd里的table组件不支持拖拽调整列宽，我看elementui的table就能，请问这个功能为什么不实现出来呢

**Comment by chenshuai2144** [comment]
抄一下 antd 的 demo 吧。这种功能都是华而不实的，几乎没啥用

**Comment by walry** [comment]
> 抄一下 antd 的 demo 吧。这种功能都是华而不实的，几乎没啥用，只能满足 pd 的虚荣心

没懂楼上的意思啊，是说antd已经实现了而是我没找到？

**Comment by DerrickTel** [comment]
https://3x.ant.design/components/table-cn/#components-table-demo-resizable-column

我也不知道为什么第四版没有了这个，但是源码都在里面，应该还是可以运行的

**Comment by walry** [comment]
> https://3x.ant.design/components/table-cn/#components-table-demo-resizable-column
> 
> 我也不知道为什么第四版没有了这个，但是源码都在里面，应该还是可以运行的

多谢。
