### ISSUE TITLE
👑 [需求]ProLayout的侧边栏是否可以支持自动拉伸

### ISSUE THREAD

**Issue by 1Lin1** [ant-design/pro-components#1702]
### 🥰 需求描述
ProLayout的侧边栏是否可以支持自动左右拉伸

当侧边栏的菜单过长时，可以支持让用户去拉伸

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/43231475/105119071-8428d080-5b0a-11eb-92d4-bbc7ef81a2b4.png)

**Comment by chenshuai2144** [comment]
我尝试过，动画不好做，你可以设置的更长一点

**Comment by 1Lin1** [comment]
> 我尝试过，动画不好做，你可以设置的更长一点

是让用户可以左右拉伸 这个好做么

**Comment by chenshuai2144** [comment]
可以用 menuRender 搞一下，性能和动画问题有点难搞
