### ISSUE TITLE
👑 [需求] 抽象出自定义ProTable 的类型

### ISSUE THREAD

**Issue by jockey100332** [ant-design/pro-components#1703]
项目中有很多需要自定义的类型，我想将自定义的类型统一的抽象在一个组件中，这样在调用的时候只需要注明类型即可。
但是在引用时发现了以下图片中的警告，能否做一下兼容，将传入的类型作为非必填项
```
export declare type ProValueType = 'link';
export declare type ValueTypeMapType = Record<string, ProRenderFieldPropsType>;

const valueTypeMap: ValueTypeMapType  = {
  link: {
    render: (text) => <a>{text}</a>,
    renderFormItem: (text, props) => <a>{text}</a>,
  },
}

function Table<T, U = T, ValueType = 'text'>(props: ProTableProps<T, U, ValueType>){
  const values = useContext(ProProvider);
  return (
    <ProProvider.Provider
      value={{
        ...values,
        valueTypeMap
      }}
    >
      <ProTable<T, U, ValueType>
        {...props}
      />
    </ProProvider.Provider>
  );
}
```
![image](https://user-images.githubusercontent.com/63291240/105125446-55fdbd80-5b17-11eb-933c-a044ed186ee4.png)

**Comment by chenshuai2144** [comment]
这个报错是 Link 报错的，你一定要设置 to ，和类型没有关系

**Comment by jockey100332** [comment]
> 这个报错是 Link 报错的，你一定要设置 to ，和类型没有关系

文档上木有，https://procomponents.ant.design/components/table#%E8%87%AA%E5%AE%9A%E4%B9%89-valuetype， 能给个demo 吗

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/105172659-e8738080-5b5a-11eb-9ee2-efe6dcbbe294.png)


这个就是字面意思，估计不是Table 搞得，是别的组件搞出来的warning
