### ISSUE TITLE
🐛[BUG] ModalForm  -initialValues 无法实时渲染

### ISSUE THREAD

**Issue by xiaojun1314** [ant-design/pro-components#1704]
### 🐛 bug 描述
树型点击赋值 变量作为 弹出框初始值 ，打开ModalForm  无法获取当前值

**Comment by chenshuai2144** [comment]
来个重现的 demo 把

**Comment by xiaojun1314** [comment]
https://1ki19.csb.app/

**Comment by xiaojun1314** [comment]
看一下这个 写的一个例子https://1ki19.csb.app/

**Comment by xiaojun1314** [comment]
点击属性任意选项  state initValue赋值  
        <ModalForm
          trigger={<Button type="primary">编辑</Button>}
          initialValues={initValue}
        >
          <ProFormText name="name" label="名称" placeholder="请输入名称" />
        </ModalForm>
打开 ModalForm 值没有带出
https://codesandbox.io/s/romantic-mclaren-1ki19?file=/index.js:317-326

**Comment by xiaojun1314** [comment]
> 来个重现的 demo 把

点击属性任意选项 state initValue赋值
<ModalForm
trigger={编辑}
initialValues={initValue}
>


打开 ModalForm 值没有带出
https://codesandbox.io/s/romantic-mclaren-1ki19?file=/index.js:317-326

**Comment by xiaojun1314** [comment]
> 来个重现的 demo 把
现在只能 重置表单的方式 才能 在打开的时候加载 initialValues 这个方法 看着 另类  
onVisibleChange={(visible: boolean) => visible&&(formRef.current!.resetFields())}

**Comment by chenshuai2144** [comment]
initValue 是后面才有值的那。这个只有第一次会用到

**Comment by xiaojun1314** [comment]
> initValue 是后面才有值的那。这个只有第一次会用到
我又写了一个例子，既然  ModalForm 是 modal form 的封装 name 使用 ant 原生 modal form 给initialValues 赋值就是可以用的
麻烦你再看下 这个例子
https://codesandbox.io/s/romantic-mclaren-1ki19?file=/index.js
与原生使用上 是有一些区别 还是加载机制 有些不同

**Comment by xiaojun1314** [comment]
> initValue 是后面才有值的那。这个只有第一次会用到

我又写了一个例子，既然 ModalForm 是 modal form 的封装 name 使用 ant 原生 modal form 给initialValues 赋值就是可以用的
麻烦你再看下 这个例子
https://codesandbox.io/s/romantic-mclaren-1ki19?file=/index.js
与原生使用上 是有一些区别 还是加载机制 有些不同

**Comment by chenshuai2144** [comment]
initValue 必须要在在 form 初始化的时候存在， modalForm 是个 form 不是 Modal，你打开 modal 之前 form 就存在了。

initValue又不是受控的，用 setFields 来处理这种需要动态更新的值的问题
