### ISSUE TITLE
🧐[问题] ModalForm 的编辑场景有推荐写法吗？

### ISSUE THREAD

**Issue by winter-ice** [ant-design/pro-components#1706]
### 🧐 问题描述

文档中没找到 ModalForm 结合 Table 的编辑场景实现 ,  求一个官方推荐写法

**Comment by xiaojun1314** [comment]
就因为 initialValues 无法实时渲染 所以 都打算放弃用 ModalForm做编辑了 ，希望 BUG修复一下

**Comment by chenshuai2144** [comment]
initialValues  本来就不是实时渲染的。

init 样式就是初始化的意思，只有在初始化的时候能用

**Comment by winter-ice** [comment]
这个issue 和这次提交有什么关联么？

**Comment by chenshuai2144** [comment]
加了个 demo

**Comment by winter-ice** [comment]
> 加了个 demo

Demo 里也不是ModalForm 呀

**Comment by chenshuai2144** [comment]
是 Form 结合 Table 的编辑场景，ModalForm 就是一个 form

**Comment by winter-ice** [comment]
没找到..  而且table 也只找到editabletable 的相关提交，这个不是行内编辑吗？如果只是自定义action列的按钮呢

**Comment by chenshuai2144** [comment]
按照 api 来接就行了，主要是 trigger 有点不同

**Comment by ideaviewes** [comment]
讲真，我还是没看懂到底这种场景要怎么用，我最后的的办法是
`
{
    updateModalVisible && <ModalForm/>
}
`

**Comment by guwan** [comment]
> 讲真，我还是没看懂到底这种场景要怎么用，我最后的的办法是
> `{ updateModalVisible && <ModalForm/> }`

原来这样啊，刚入门ant design，搞这个搞了一天。设计得很不好啊

**Comment by sunzhongwei** [comment]
非常不实用
