### ISSUE TITLE
🐛[BUG] EditableProTable  onChange事件传入的参数格式不对

### ISSUE THREAD

**Issue by DreamParadise** [ant-design/pro-components#1716]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/3191003/105277167-d686f180-5bdd-11eb-8914-5ac8503675e6.png)

### 📷 复现步骤

直接用你们官网里面的demo就能测试出来

### © 版本信息

在线版本或者本地V2.26.1的ProTable都是这样的问题

**Comment by chenshuai2144** [comment]
哪里不对呀 哥哥

**Comment by chenshuai2144** [comment]
看起来是文档里的算法错了，换了个写法。

**Comment by DreamParadise** [comment]
> 看起来是文档里的算法错了，换了个写法。

`onChange: (value:T[])=>void`

这个value数组新增出来的数据和原来的数据格式不应该是一样的吗？同一个数据里面的存的对象居然是不同的格式？
你们是不是会通过发布新版本来更新掉？
这是已有数据的格式：
```json
{
  "id": 624691229
  "title": "活动名称二"
  "labels": Array(1)
  "state": "closed"
  "created_at": "2020-05-26T08:19:22Z"
}
```
这是新增数据的格式：
```json
{
  "674648": {
    "title": "新的一行"
    "state": "open"
    "labels": undefined
  }
  "id": "674648"
  "title": "新的一行"
  "index": 2
}
```
