### ISSUE TITLE
🐛[BUG]pro table的复制完成无法消失

### ISSUE THREAD

**Issue by yeomanyang** [ant-design/pro-components#1720]
### 🐛 bug 描述
依次点击pro table的复制按钮，就会出现一大片复制不消失的情况。

### 📷 复现步骤

依次点击pro table的复制按钮，就可以复现。

### 🏞 期望结果

复制图标可以依次消失

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] @alipay/tech-ui@1.25.4
- umi 版本
- 浏览器环境 Chrome  87.0.4280.88
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/19544191/105320243-e8c65700-5c00-11eb-8bd9-d0a49a6019da.png)

**Comment by chenshuai2144** [comment]
你是不是做了什么配置，我试了一下是可以的
