### ISSUE TITLE
🐛[BUG] windows下构建报错

### ISSUE THREAD

**Issue by beeant0512** [ant-design/pro-components#1721]
### 🐛 bug 描述

操作系统：windows10
node： 14.7.0
版本：master

使用yarn run deploy的时候报错

![image](https://user-images.githubusercontent.com/6050235/105322532-faf5c480-5c03-11eb-87a9-01333eaf1c8e.png)

**Comment by chenshuai2144** [comment]
这个仓库不支持 windows 的，你可能需要找个 linux 环境了
