### ISSUE TITLE
🧐[问题]pro-table例子用为什么有的边框聚焦的时候有外阴影，有的没有

### ISSUE THREAD

**Issue by s464446877** [ant-design/pro-components#1725]
### 🧐 问题描述

pro-table例子用为什么有的边框聚焦的时候有外阴影，有的没有。直接写表单组件聚焦的时候就会有外阴影，protable搜索表单里就没有外阴影，不是很统一，难受

**Comment by chenshuai2144** [comment]
你说的是 foucs 阴影吧，ProTable 里面比较紧凑，其实是有的，只是被挡住了

**Comment by s464446877** [comment]
这个问题我们后期会优化吗，或者目前有什么解决办法吗

**Comment by s464446877** [comment]
因为我现在配置antd的主题，protable没办法和其他组件样式统一

**Comment by chenshuai2144** [comment]
后面看看，可能问题比较多。
一般不过发现吧
