### ISSUE TITLE
🐛[BUG] EditableProTable 只能增加一行

### ISSUE THREAD

**Issue by dercaft** [ant-design/pro-components#1726]
### 🐛 bug 描述

EditableProTable 只能增加一行。
在Proform和EditableProtable文档页面中可以增加多行，但把代码复制到我的本地工程中就只能增加一行。

#### 在[Proform和EditableProTable](https://procomponents.ant.design/components/form#proform-%E5%92%8C-editabletable-%E5%90%8C%E6%97%B6%E4%BD%BF%E7%94%A8)中可以新增多行
![proform](https://user-images.githubusercontent.com/22705102/105414765-e270c300-5c72-11eb-93e3-c0a14bc53be2.png)

#### 将代码复制添加到我本地工程，就只能新增一行
![只能新增一行2](https://user-images.githubusercontent.com/22705102/105414092-fcf66c80-5c71-11eb-888c-8f42d4b4ac3d.png)

请问这是出了什么问题呢？感觉像是在本地工程中组件的key被赋值成相同的值。
以及antd5.0中，EditableProTable Props recordCreatorProps 没有 newRecordType 这个参数，
会报React does not recognize the `newRecordType` prop on a DOM element.错误
### © 版本信息

- antd-design-pro : 5.0.0-beta.0
- ant-design/pro-card@1.9.11
- ant-design/pro-descriptions@1.4.7
- ant-design/pro-form@1.15.1
- ant-design/pro-layout@6.10.9
- ant-design/pro-list@1.2.20
- ant-design/pro-skeleton@1.0.0-beta.2
- ant-design/pro-table@2.25.1
- umi 3.3.5
- 浏览器环境 Edge 版本 87.0.664.75 (官方内部版本) (64 位)
- 开发环境 ubuntu 16.04 远程连接

**Comment by auyo18** [comment]
![image](https://user-images.githubusercontent.com/23635064/105489350-0c1b0000-5cee-11eb-85cd-34b8425d1641.png)

**Comment by chenshuai2144** [comment]
```
recordCreatorProps={{
          newRecordType: 'dataSource',
          record: () => ({
            id: Date.now(),
          }),
        }}
```

newRecordType 设置成 dataSource 就可以无限行添加了，但是会导致取消之后有一条新数据

**Comment by dercaft** [comment]
你好，type设置成single或multiple，都还是只能添加一行

**Comment by dercaft** [comment]
> ```
> recordCreatorProps={{
>           newRecordType: 'dataSource',
>           record: () => ({
>             id: Date.now(),
>           }),
>         }}
> ```
> 
> newRecordType 设置成 dataSource 就可以无限行添加了，但是会导致取消之后有一条新数据

您好，感谢回复。
1. 我这个环境下recordCreatorProps 没有 newRecordType 这个参数，浏览器会报React does not recognize the newRecordType prop on a DOM element.错误
   
![不识别_参数](https://user-images.githubusercontent.com/22705102/105630573-f4c24b00-5e84-11eb-90d7-a5375f660406.png)


2. ```typescript
   record: () => ({ id: Date.now(),}), //record这样写时
   ```

   会出现

   
![record函数](https://user-images.githubusercontent.com/22705102/105630647-508cd400-5e85-11eb-9af7-05ae08714eeb.png)


   然后

   1. 新建条目时就会在参数名字段出现“record”，如图

      
![record问题](https://user-images.githubusercontent.com/22705102/105630607-20ddcc00-5e85-11eb-9d7c-8fc0bc3e96cc.png)


   2. 浏览器console报错：“Warning: Each child in a list should have a unique "key" prop.”如图：
![key问题](https://user-images.githubusercontent.com/22705102/105630610-2509e980-5e85-11eb-8d70-1e03523aaf87.png)

**Comment by chenshuai2144** [comment]
按照提示来，这个 record 是你新建行的数据，我的主键是id，但是你的不是id，你要用自己的demo来

**Comment by chenshuai2144** [comment]
按照提示来，这个 record 是你新建行的数据，我的主键是id，但是你的不是id，你要用自己的demo来

**Comment by chenshuai2144** [comment]
> 我这个环境下recordCreatorProps 没有 newRecordType 这个参数，浏览器会报React does not recognize the newRecordType prop on a DOM element.错误

你要更新版本到最新

**Comment by dercaft** [comment]
> > 我这个环境下recordCreatorProps 没有 newRecordType 这个参数，浏览器会报React does not recognize the newRecordType prop on a DOM element.错误
> 
> 你要更新版本到最新

更新版本到最新之后可以正常添加新行了，“没有 newRecordType 参数”的报错也消失了，以后我多注意更新版本，感谢您的帮助。

**Comment by gujiwuqing** [comment]
自定义编辑表格 只能一次同时一行，大佬们如何解决

**Comment by image72** [comment]
需要先保存一次表格

**Comment by liushuhui** [comment]
![image](https://user-images.githubusercontent.com/26155477/201583846-05b8eae0-3569-4062-ac14-0e2e7d4e9a7e.png)
应该更新到哪个版本呢
