### ISSUE TITLE
🧐[问题]关于pro table 几个使用的问题！搜索框 placeholder 搜索条件排序

### ISSUE THREAD

**Issue by codedart2018** [ant-design/pro-components#1727]
有如下几个问题，请需要请教下！
一、pro table
1.关于搜索条件的placeholder 没有看到在哪里有设置它。
2.搜索条件是否可以排序调换位置
3.搜索条件默认超过一行才能展开，如何设置成超过2行才能展开呢。
二、pro modal
既然都用了modal希望把ant modal所有的属性都继承过来吧。发现ant modal有的属性在pro modal from里没有的！

**Comment by chenshuai2144** [comment]
> 1.关于搜索条件的placeholder 没有看到在哪里有设置它。

`filedProps.placeholder`

> 2.搜索条件是否可以排序调换位置

支持 sort

> 3.搜索条件默认超过一行才能展开，如何设置成超过2行才能展开呢。

这个不支持


> 既然都用了modal希望把ant modal所有的属性都继承过来吧。发现ant modal有的属性在pro modal from里没有的！


ModalFrom 有 modalProps

**Comment by klay1994** [comment]
proTable里面单个筛选条件的placeholder怎么不生效的大佬，我是这样写的
filedProps: {
        placeholder: '上报人',
      },

**Comment by guoqqqi** [comment]
嗨，有相关的使用例子吗？我也遇到了这个问题

**Comment by guoqqqi** [comment]
在 #324 找到了解决方案
