### ISSUE TITLE
👑 [需求]proform没有labelWidth: 'auto'

### ISSUE THREAD

**Issue by topwood** [ant-design/pro-components#1728]
### 🥰 需求描述

protable的search有labelWidth: 'auto'，解决标签看不见的问题。 proform没有labelWidth: 'auto'，也需要支持，否则会被遮挡

### 🧐 解决方案
proform支持labelWidth: 'auto'

**Comment by chenshuai2144** [comment]
这个不行的，要定宽，QueryForm 和 ProForm 不一样的

**Comment by chenshuai2144** [comment]
设计师不是很支持这种行为，这个需求不做了
