### ISSUE TITLE
👑 [需求] ProLayout可以设置iconfont图标的前缀

### ISSUE THREAD

**Issue by qianxiaowu** [ant-design/pro-components#1729]

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/layout#%E4%BD%BF%E7%94%A8-iconfont

看这里

**Comment by qianxiaowu** [comment]
@chenshuai2144 
翻了下组件代码
    if (icon.startsWith('icon-')) {
      return <IconFont type={icon} />;
    }
只有当icon以icon-命名开头才渲染iconfont图标
后来我是通过iconfont上修改了FontClass/Symbol前缀
希望文档里能说明下
(●'◡'●)
