### ISSUE TITLE
👑 [需求]希望支持 Excel 重型组件

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/pro-components#1733]
### 🥰 需求描述

web excel 不属于 antd 基本组件，不知道属不属于该库的范畴。。。

**Comment by chenshuai2144** [comment]
也不属于这个太难了
靠我一个人做不到 如果有一亿美金 再有一个团队就可以了
________________________________

**Comment by tolerance-go** [comment]
哈哈，这个库已经超级好用了
