### ISSUE TITLE
🧐[问题]pro-layout 如果需要传入外面的hash路由，如何使用。

### ISSUE THREAD

**Issue by lxkun** [ant-design/pro-components#1735]
### 🧐 问题描述
pro-layout 如果需要传入外面的hash路由，如何使用。
我需要传进路由，但是我的路由是hash路由，传入进去的时候，不能让菜单选中。

我需要传进路由，但是我的路由是hash路由，传入进去的时候，不能让菜单选中。

**Comment by lxkun** [comment]
{
        exact: true,
        path: '/#/home',
        name: '工作台',
        icon: <HomeOutlined/>,
  },
这样传入会让所有菜单都会处于选中状态

**Comment by chenshuai2144** [comment]
继续用pathname 就好了，对于应用来说 hash 路由和正常路区别不大

**Comment by 662** [comment]
路由用的是BrowserRouter，但是菜单上有hash，即便申明了 `location={{pathname: location.pathname+location.hash }}` 似乎也无法工作。
