### ISSUE TITLE
👑 [需求]ModalForm点击取消时想做一层拦截提示

### ISSUE THREAD

**Issue by JTenacity** [ant-design/pro-components#1736]
### 🥰 需求描述
ModalForm点击取消时想做一层拦截提示，onVisibleChange无法获取是确定还是取消。modalProps中传入onCancel无法使用

**Comment by chenshuai2144** [comment]
试着更新一下版本，这两个bug 都修复了。

onVisibleChange 会传一个 boolean，可以在这里判断

**Comment by JTenacity** [comment]
@chenshuai2144 onVisibleChange我点确定还是取消拿到的都是一样的，怎么判断是点击哪个，只有在取消时处理二次确认
