### ISSUE TITLE
👑 [需求]ProDescriptions一部分columns, 一部分自定义,自定义的能放在后面吗?

### ISSUE THREAD

**Issue by zhang-mol** [ant-design/pro-components#1738]
### 🥰 需求描述
自定义的DescriptionItem放在后面, 或者给个api能控制是在前面添加还是末尾添加

**Comment by chenshuai2144** [comment]
这个有点麻烦，你是为了满足什么需求？

**Comment by zhang-mol** [comment]
比如：基本信息一列可展示，展示一些复杂的数据，需要自定义（不在columns中render），比如把数据变为树展示，此时放在最前面略显奇怪

**Comment by zhang-mol** [comment]
> 这个有点麻烦，你是为了满足什么需求？

比如：基本信息一列可展示，展示一些复杂的数据，需要自定义（不在columns中render），比如把数据变为树展示，此时放在最前面略显奇怪，目前文档默认是放在最前面的。

**Comment by chenshuai2144** [comment]
ok, 我修改一下，这个组件使用的人不多，我直接改默认逻辑吧。

如果想自定义可以用 order 配置
