### ISSUE TITLE
🧐[问题]ProFormSelect中如果option的文本太长，选中后会导致label和input变成上下排列

### ISSUE THREAD

**Issue by wmf508** [ant-design/pro-components#1741]
### 🧐 问题描述
我是在QueryFilter组件中使用的ProFormSelect中如果option的文本太长，选中后会导致label和input变成上下排列，求问如何解决？

**Comment by chenshuai2144** [comment]
这个有点不好解决，你是想设置成什么样子的？

**Comment by wmf508** [comment]
> 这个有点不好解决，你是想设置成什么样子的？

就是保持水平排列，可以接受选项超出部分省略显示

**Comment by chenshuai2144** [comment]
这几个api可以满足你的需求，如果只是像省略的话，可以用  Typography 包一下 label



maxTagCount | 最多显示多少个 tag，响应式模式会对性能产生损耗 | number \| responsive | - | responsive: 4.10
maxTagPlaceholder | 隐藏 tag 时显示的内容 | ReactNode \| function(omittedValues) | - |  
maxTagTextLength | 最大显示的 tag 文本长度 | number | -

**Comment by changjunhao** [comment]
> 这几个api可以满足你的需求，如果只是像省略的话，可以用
> 
> maxTagCount | 最多显示多少个标签，响应模式模式性能产生的损耗| 编号| 响应式| -| 响应式：4.10
> maxTagPlaceholder | 隐藏标签时显示的内容| ReactNode | 函数（省略值）| -|  
> maxTagTextLength | 最大显示的标签文本长度| 编号| --

不是这个问题

<img width="391" alt="截屏2021-02-22 下午8 06 19" src="https://user-images.githubusercontent.com/7688639/108706472-a36faf00-7549-11eb-9e13-1a44ffd6bf82.png">

**Comment by changjunhao** [comment]
这个问题又出现了，"@ant-design/pro-table": "2.50.0",

**Comment by jingxiawl** [comment]
@chenshuai2144  这个解决了么。换行样式太丑了

**Comment by chenshuai2144** [comment]
antd 官方解决了，升级一下antd 版本/
