### ISSUE TITLE
🐛[BUG]proTable 搜索表单点击「重置」后，分页器的每页显示条数被设置为1

### ISSUE THREAD

**Issue by didi5683** [ant-design/pro-components#1742]
### 🐛 bug 描述

proTable 搜索表单点击「重置」后，分页器的每页显示条数被设置为1（正常默认值为20）

版本： @ant-design/pro-table@2.27.0  / @ant-design/pro-table@2.27.1

![image](https://user-images.githubusercontent.com/67136183/105568394-fc45ff00-5d73-11eb-8e80-eef272f3e794.png)

**Comment by chenshuai2144** [comment]
更新到 @ant-design/pro-table@2.27.1 。

2.27.1 就是为了解决这个问题
