### ISSUE TITLE
🐛[BUG]ProFormText组件提示错误

### ISSUE THREAD

**Issue by birdycn** [ant-design/pro-components#1746]
```
          <ProFormText fieldProps={{ size: 'large', prefix: <MobileTwoTone /> }}
                  name="phone"
                  placeholder="请输入手机号"
                  rules={[
                    {
                      required: true,
                      message: '请输入手机号!',
                    },
                    {
                      pattern: /^1\d{10}$/,
                      message: '不合法的手机号格式!',
                    },
                  ]}
                />
```

报错：类型“{ fieldProps: { size: string; prefix: Element; }; name: string; placeholder: string; rules: ({ required: boolean; message: string; } | { pattern: RegExp; message: string; })[]; }”缺少类型“Pick<any, "label" | "style" | "children" | "valuePropName" | "id" | "disabled" | "className" | "placeholder" | "bordered" | "name" | "dependencies" | "getValueFromEvent" | "normalize" | ... 38 more ... | "status">”的以下属性: label, style, children, valuePropName 及其他 44 项。ts(2740)

antd版本已经是4.10.3了

**Comment by chenshuai2144** [comment]
你的这个意思是类型组合有问题，你清空一下依赖重新安装把。
官网有 tsc 的测试的，几乎不会犯这种低级问题。

```
git clean -dfx
rm -rf  yarn.lock 
yarn
```

**Comment by birdycn** [comment]
> 你的这个意思是类型组合有问题，你清空一下依赖重新安装把。
> 官网有 tsc 的测试的，几乎不会犯这种低级问题。
> 
> ```
> git clean -dfx
> rm -rf  yarn.lock 
> yarn
> ```

解决了感谢~~
