### ISSUE TITLE
🐛[BUG]ProFormTimePicker 赋默认值 输入框显示 Invalid date 未显示从接口获取的值

### ISSUE THREAD

**Issue by daaamiao** [ant-design/pro-components#1748]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/45863491/105650886-2a504e00-5ef0-11eb-96ee-d0076e1e6b77.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你的类型是什么？这个是 moment 识别不了导致的，你最好自己用 moment 包一下

**Comment by daaamiao** [comment]
已解决 谢谢

**Comment by changlin0501** [comment]
> 已解决 谢谢

您好，请问最后你是如何处理得，我也遇到相同问题

**Comment by changmen1** [comment]
怎么解决的可以贴出来吗🥹
