### ISSUE TITLE
🧐[问题]v5-breadcrumbRender添加一级报错

### ISSUE THREAD

**Issue by jpdan** [ant-design/pro-components#1749]
![image](https://user-images.githubusercontent.com/3361732/105655404-f4fd2d80-5efa-11eb-8b52-a07c690d07d7.png)
![image](https://user-images.githubusercontent.com/3361732/105655429-fe869580-5efa-11eb-9807-3af51da8ac11.png)

**Comment by ifyour** [comment]
在处理了，稍安勿躁，Issue #1751

**Comment by chenshuai2144** [comment]
重新安装把
