### ISSUE TITLE
升级到4.11.1版本后 breadcrumbRender可能会跟ProLayout里面的属性冲突 导致路由直接报错

### ISSUE THREAD

**Issue by ILoveChy** [ant-design/pro-components#1751]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
总体就是升级完prolayout 和 antd后 出现的问题 报错提示大改是 
nonIterableSpread.js:2 Uncaught TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
提示位置是proLayout的代码 外面包裹着 ConfigProvider组件
breadcrumbRender属性删除后问题就不存在了 或者把antd回退到4.10.3就OK了 
所以我觉得是breadcrumbRender属性冲突或者ConfigProvider配置导致的

### What is expected?
使用正常

### What is actually happening?
路由错误

| Environment | Info |
|---|---|
| antd | 4.11.1 |
| React | 17.0.1 |
| System | win10 |
| Browser | chrome90 |

---
公司项目 实在没法整个单独的仓库出来...地址就随便写了个..

**Comment by JoyceLizhuo** [comment]
遇到了同样的问题，是不是因为antd的4.11.1版本的PageHeader组件支持了breadcrumbRender这个参数导致的呀

**Comment by yiluxiangbei87110** [comment]
我也遇到这个问题

**Comment by LiUhoNgDan222** [comment]
我也遇到了这个问题，

**Comment by mengxuhui** [comment]
1

**Comment by chenshuai2144** [comment]
修掉了，重新安装把

**Comment by WaiKoeng** [comment]
> 修掉了，重新安装把

请问怎么重新安装呢？

**Comment by ILoveChy** [comment]
可以了

**Comment by WaiKoeng** [comment]
> 可以了

4.11.2吗？为什么我还是有这个问题

**Comment by ILoveChy** [comment]
> > 可以了
> 
> 4.11.2吗？为什么我还是有这个问题
 "antd": "4.11.2",
"@ant-design/pro-layout": "6.13.0",
2个都得更新

**Comment by WaiKoeng** [comment]
> > > 可以了
> > 
> > 
> > 4.11.2吗？为什么我还是有这个问题
> 
> "antd": "4.11.2",
> "@ant-design/pro-layout": "6.13.0",
> 2个都得更新

可以了，谢谢

**Comment by mylovehai** [comment]
`"@ant-design/pro-layout": "^4.10.0"` 大版本4也存在同样的问题，升级 prolayout 会导致整体布局的改变，这是不希望的。
但是不升级，antd 版本只能用 4.11.0 之前的，这时候又想引入 proform，但是 proform 又依赖的 antd 的新版本特性，也不知道哪一个版本的 proform 可使用~~~~~~~~
