### ISSUE TITLE
🧐[问题]ProForm的LightFilter模式中 ProFormDateRangePicker选择日期很难使用

### ISSUE THREAD

**Issue by hzAlanLee** [ant-design/pro-components#1753]
ProFormDateRangePicker的allowClear设置为false以后 很难选择到特定时间段

**Comment by chenshuai2144** [comment]
去 antd 提交吧，这个交互一直是个难题

**Comment by hzAlanLee** [comment]
antd中的时间段选择控件并没有问题
antd中也没有看到类似LightFilter模式下的时间段选择控件
这个问题应该是pro做定制控件的时候的Bug  出现了交互问题

**Comment by chenshuai2144** [comment]
方便来个gif吗
