### ISSUE TITLE
🐛[BUG]Modal中form的initialValues延迟

### ISSUE THREAD

**Issue by cuihq2005** [ant-design/pro-components#1758]
### 🐛 bug 描述

在issues看到过几个ModalForm中关于initialValues延迟的bug，但都被无情的close了，希望大大能坚持看完

https://codesandbox.io/s/testmodal464-ubc7f

这是使用antd4.6.4版本的示例，在页面中点查看、编辑或者新建，都能得到正确的结果

https://codesandbox.io/s/testmodal484-g5rlp
这个是antd4.8.4的示例，在这个页面中，只是修改了antd的依赖，无任何代码更改。但页面只有第一次点开查看才能看到值，后续由于form.resetFields,无论点什么都没有值

https://codesandbox.io/s/testmodal4102-j32f1
这个使用了antd4.10.2版本的示例，4.11.1也试过，同样的效果。当点第一个查询时，能显示正确的值，后续再点，只能显示上次的。比如先点第一个的查询，显示第一条的记录；再点第二个，显示第一条；再点第二个一次，又显示第二个的值；再点新建，不是空页面，而是第二个的值；再次点新建，这次是空页面。

这个问题导致目前我所有页面只能在打开modal时使用form.setFieldsValue(initialValues())强制设置form的值，但这样设置值会导致form.isFieldsTouched()判断不准确，影响页面效果（无任何field更新时，我这边确认按钮不可用，只显示取消按钮）

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
ModalForm 是 Form 不是modal，在modal打开时不会重新生成Form 对象。

如果想达到相同的效果。

建议 initialValues && ModalForm  ， 保证 让 ModalForm 多次销毁并重建。

**Comment by cuihq2005** [comment]
> ModalForm 是 Form 不是modal，在modal打开时不会重新生成Form 对象。
> 
> 如果想达到相同的效果。
> 
> 建议 initialValues && ModalForm ， 保证 让 ModalForm 多次销毁并重建。

我试试ModalForm，但有个问题，如果说不会重新生成Form对象，为什么会显示前一次打开的值。按这个说法，form的initialValues的应该一直不变才对
