### ISSUE TITLE
2.5.7解决了值为null显示序号的问题，但是当值为null时也不会显示'-'了

### ISSUE THREAD

**Issue by zyh2123606** [ant-design/pro-components#176]

**Comment by chenshuai2144** [comment]
来个 demo？

**Comment by zyh2123606** [comment]
当值为null时，2.4.*都会默认显示‘-’，现在2.5.7不会显示'-'这个了，代码都是一样的

**Comment by chenshuai2144** [comment]
show 一下你的代码， 我们的测试用例可能没覆盖

**Comment by zyh2123606** [comment]
<ProTable
				actionRef={tabRef}
				request={getData}
				rowKey='id'
				columns={columns}
				size="small"
				scroll={{ x: 1000 }}
				options={{
					density: false
				}}
				toolBarRender={() => [
					<Button
						key={1}
						onClick={() => setWin({ contractId: undefined, disabled: false, visible: true, title: '新增合同' })}
						type='primary' ghost icon={<PlusOutlined />}>新增合同</Button>
				]}
				tableAlertRender={false}
				search={false}
				pagination={{
					defaultPageSize,
					pageSizeOptions: sizeOption.current,
					showQuickJumper: true,
					size: 'default'
				}}/>

**Comment by DeyuanTan** [comment]
遇到同样的问题

**Comment by gguan** [comment]
能不能把空值显示逻辑确定了不要改来改去了 一升级库数据全乱了

**Comment by chenshuai2144** [comment]
列配置展示一下
