### ISSUE TITLE
🐛[BUG] pro-table polling 停止后再启动轮询不生效

### ISSUE THREAD

**Issue by bluescurry** [ant-design/pro-components#1760]
### 🐛 bug 描述

1. 如题，官网上的代码示例是有问题的，停止轮询再开启轮询后不生效。
2. 还有一个问题，在 Modal 中使用 pro-table，setPolling(undefined); 不生效

### 📷 复现代码

https://procomponents.ant.design/components/table/#%E8%A1%A8%E6%A0%BC%E8%BD%AE%E8%AF%A2

### 🏞 期望结果

可以灵活地控制轮询时间

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
写标题

**Comment by bluescurry** [comment]
> 写标题

什么意思？没懂。。。

**Comment by chenshuai2144** [comment]
回复错了，sorry，网路太差了

**Comment by night1008** [comment]
这个问题是不是还存在，没有解决？

**Comment by 51070147** [comment]
我也碰到这个问题了，这个问题是不是解决不了？官网的例子都是错的？
