### ISSUE TITLE
[需求]ModalForm点击取消时想做一层拦截提示 

### ISSUE THREAD

**Issue by JTenacity** [ant-design/pro-components#1762]
需要在取消时做拦截提示，现在onVisibleChange中返回的只有visible，无法区分是点击的确认还是取消。

希望可以在onVisibleChange中可以获取是取消按，还是确认按钮

**Comment by chenshuai2144** [comment]
visible 只有 true 和 false，onVisibleChange 应该尽量纯粹一点

你要需要自定义就用 onCancel 和 onFinsh 进行拦截
