### ISSUE TITLE
visible 只有 true 和 false，onVisibleChange 应该尽量纯粹一点

### ISSUE THREAD

**Issue by JTenacity** [ant-design/pro-components#1766]
visible 只有 true 和 false，onVisibleChange 应该尽量纯粹一点

你要需要自定义就用 onCancel 和 onFinsh 进行拦截

_Originally posted by @chenshuai2144 in https://github.com/ant-design/pro-components/issues/1762#issuecomment-767505421_

目前modalProps中的onCancel无法拦截弹窗关闭。

<ModalForm
      title={title}
      // visible={visible}
      trigger={
        <Button type="primary">
          新建表单
        </Button>
      }
      width={638}
      form={form}
      className={classNames(styles.allotAfter, { [styles.bigPadding]: !relCompanyName })}
      initialValues={initialValues}
      labelCol={{ span: 7 }}
      wrapperCol={{ span: 14 }}
      layout="horizontal"
      validateMessages={{
        required: '${label}不能为空',
      }}
      modalProps={{
        width: 638,
        maskClosable: false,
        onCance: () => {
          console.log(1)
        }
      }}
      onVisibleChange={(visible) => {
        // setVisible(visible);
      }}
      onFinish={async (values) => {
                return true;
      }}
    >
      <Form.Item>
123123
      </Form.Item>
    </ModalForm>

**Comment by chenshuai2144** [comment]
用受控模式呀，你设置 visible-true, 谁能关掉你。
