### ISSUE TITLE
🧐[问题]umi项目中使用pro-table在ie11中页面打开报错

### ISSUE THREAD

**Issue by zy940815** [ant-design/pro-components#1768]
### 🧐 问题描述
umi项目中使用pro-table在ie11中页面打开报错

已经在.umirc.js中配置targets: {ie: 11,}。报错信息是pro-utils中引用的fast-deep-equal导致。
尝试把pro-table版本降低到2.7.4（pro-utils还未引用fast-deep-equal），ie11可以正常打开页面。

### 💻 版本信息
umi：2.13.13
@ant-design/pro-table: ^2.27.0
antd: ^4.7.0

### 🚑 报错截图
![image](https://user-images.githubusercontent.com/62635163/105957956-e9edfd00-60b4-11eb-8bd4-a64c0dcc62f5.png)
![image](https://user-images.githubusercontent.com/62635163/105958128-2e799880-60b5-11eb-8924-e91508b439cf.png)
![image](https://user-images.githubusercontent.com/62635163/105958163-376a6a00-60b5-11eb-844e-e52814700314.png)

**Comment by chenshuai2144** [comment]
你打开 umi 的 nodemodulestransform 配置，可以编译 nodemodules

https://umijs.org/zh-CN/config#nodemodulestransform

**Comment by zy940815** [comment]
umi2.x好像是没有nodemodulestransform配置，通过webpack相关配置对报错文件进行重新编译后，解决了此问题

**Comment by calefy-chen** [comment]
> umi2.x好像是没有nodemodulestransform配置，通过webpack相关配置对报错文件进行重新编译后，解决了此问题

请问是怎么配置的？现在用最新的打包也遇到了这个同样的报错，umi3+最新pro-table。

之前umi2也有这个问题，只要增加到babel转换中就可以了：`extraBabelIncludes: ['fast-deep-equal']`。
但是现在用umi3脚手架即使配置了`nodeModulesTransform: {type:'all'}` 也不行。
现在只能寄希望于 chainWebpack的改变配置了。

**Comment by calefy-chen** [comment]
通过这个方式解决了（IE浏览器缓存太厉害，ctrl+f5都不应是最新的，我通过换端口实现禁止缓存）：
`nodeModulesTransform: {
    type: 'none',
    // 下面两个包有ie11不支持的语法，需要做编译
    exclude: ['@umijs/use-params', 'fast-deep-equal'],
  }`
