### ISSUE TITLE
🧐[问题] 如何隐藏 ProTable 生成的搜索的 label？

### ISSUE THREAD

**Issue by linxianxi** [ant-design/pro-components#1769]
如何隐藏输入框的 label

![image](https://user-images.githubusercontent.com/47104575/105959695-389c9680-60b7-11eb-8086-a248659f92d8.png)

**Comment by chenshuai2144** [comment]
columns 的 title 支持 function的，你可以这样写

```
title: (_, type) => {
              if (type === 'table') {
                return '标题';
              }
              return null;
            },
```

你这个查询表单做的挺好看的

**Comment by linxianxi** [comment]
> columns 的 title 支持 function的，你可以这样写
> 
> ```
> title: (_, type) => {
>               if (type === 'table') {
>                 return '标题';
>               }
>               return null;
>             },
> ```
> 
> 你这个查询表单做的挺好看的

第一次用，api 太多太复杂了，文档看的头都晕了

**Comment by chenshuai2144** [comment]
模板组件都是这样的，熟练了才能很爽

**Comment by weistrong** [comment]
这个有文档吗？遇到问题官网找不到，一搜就是一半个小时，效率太低了。
