### ISSUE TITLE
🐛[BUG]官网示例问题 ProForm.Group

### ISSUE THREAD

**Issue by topwood** [ant-design/pro-components#1770]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/13791267/105960163-caa49f00-60b7-11eb-8cfe-9e7aac2c8e59.png)

最新版本的Group由ProForm直接导出 
```
import {
  ProFormGroup
} from '@ant-design/pro-form';
```

无法通过ProForm.Group引用，希望修正示例

### 🏞 期望结果

修改demo

### © 版本信息

- ProForm 版本: 1.15.2

**Comment by topwood** [comment]
搞错了

**Comment by chenshuai2144** [comment]
都支持的
