### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by im-not-a-programmer** [ant-design/pro-components#1772]
### 📷 复现步骤

column 配置
{
    title: '状态',
    dataIndex: 'status',
    initialValue: 'all',
    valueType: 'radioButton',
    valueEnum: {
      all: { text: '全部', status: 'all' },
      close: { text: '待发布', status: 'Default' },
      running: { text: '发布中', status: 'Processing' },
      online: { text: '发布成功', status: 'Success' },
      error: { text: '发布失败', status: 'Error' },
   },
 }

### 🏞 期望结果
按照官方文档期望得到 状态的文字以及 不同颜色的小圆点显示，但并未按预定显示 直接显示了 status值

### © 版本信息

- ProComponents 版本: [2.27.2]
- antd 版本：[4.11.2]

**Comment by chenshuai2144** [comment]
写标题
