### ISSUE TITLE
🧐[问题] ProTable 生成的搜索项怎么配置每个控件再每个屏幕宽度下的 span

### ISSUE THREAD

**Issue by linxianxi** [ant-design/pro-components#1774]
怎么单独配置每个输入框的栅格，我只找到文档里配置整个表格的 span: defaultColConfig，不能单独配置。单独只能配置 colSize，不能根据屏幕宽度变化
![image](https://user-images.githubusercontent.com/47104575/105961845-05a7d200-60ba-11eb-9e2a-916e8ee9d02e.png)

**Comment by chenshuai2144** [comment]
这个只支持一定模式的，不支持每个控件的宽度，只能设置是几倍宽度
