### ISSUE TITLE
ModalForm中在modalProps的onCancel中拿不到表单数据

### ISSUE THREAD

**Issue by JTenacity** [ant-design/pro-components#1775]
### 🐛 bug 描述
ModalForm采用受控模式，当表单数据发生过更改后，点出取消要进行拦截。目前在modalProps中onCancel事件中无法通过form实例方法拿到最新的数据。因为表单被重置了

### 💻 复现代码

import React, { useState } from 'react'
import { Button, message, Space, form } from 'antd'
import ProForm, {
  ModalForm,
  ProFormText,
  ProFormDateRangePicker,
  ProFormSelect,
  DrawerForm,
} from '@ant-design/pro-form'
import { PlusOutlined } from '@ant-design/icons'
export default () => {
  const [modalVisit, setModalVisit] = useState(false)
  const [form] = Form.useForm()
  return (
    <>
      <Space>
        <Button
          type='primary'
          onClick={() => {
            setModalVisit(true)
          }}
        >
          <PlusOutlined />
          Modal 展示
        </Button>
      </Space>
      <ModalForm
        title='新建表单'
        visible={modalVisit}
        form={form}
        onFinish={async () => {
          message.success('提交成功')
          setModalVisit(false)
        }}
        modalProps={{
          onCancel: () => {
            let n = form.getFieldValue('name')
          },
        }}
      >
        <ProForm.Group>
          <ProFormText
            width='md'
            name='name'
            label='签约客户名称'
            tooltip='最长为 24 位'
            placeholder='请输入名称'
          />
          <ProFormText
            width='md'
            name='company'
            label='我方公司名称'
            placeholder='请输入名称'
          />
        </ProForm.Group>
        <ProForm.Group>
          <ProFormText
            width='md'
            name='contract'
            label='合同名称'
            placeholder='请输入名称'
          />
          <ProFormDateRangePicker name='contractTime' label='合同生效时间' />
        </ProForm.Group>
        <ProForm.Group>
          <ProFormSelect
            options={[
              {
                value: 'chapter',
                label: '盖章后生效',
              },
            ]}
            width='xs'
            name='useMode'
            label='合同约定生效方式'
          />
          <ProFormSelect
            width='xs'
            options={[
              {
                value: 'time',
                label: '履行完终止',
              },
            ]}
            name='unusedMode'
            label='合同约定失效效方式'
          />
        </ProForm.Group>
        <ProFormText width='sm' name='id' label='主合同编号' />
        <ProFormText
          name='project'
          disabled
          label='项目名称'
          initialValue='xxxx项目'
        />
        <ProFormText
          width='xs'
          name='mangerName'
          disabled
          label='商务经理'
          initialValue='启途'
        />
      </ModalForm>
    </>
  )
}

![image](https://user-images.githubusercontent.com/19601885/105964776-a2b83a00-60bd-11eb-81c6-6be6735bee3a.png)
![image](https://user-images.githubusercontent.com/19601885/105964816-aea3fc00-60bd-11eb-8921-09e2615f5e36.png)

### © 版本信息

- "@ant-design/pro-card": "^1.4.5",
  "@ant-design/pro-descriptions": "^1.0.19",
  "@ant-design/pro-form": "^1.15.1",
  "@ant-design/pro-layout": "^6.6.1",
  "@ant-design/pro-table": "2.26.0",
- umi 版本 "umi": "^3.3.1",
- 浏览器环境 chrome 
- 开发环境 Mac os

**Comment by chenshuai2144** [comment]
用formRef 拿一下，api 都是尽量简单的

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/105975368-d8fbb680-60c9-11eb-9a18-1e126747feca.png)
