### ISSUE TITLE
table 里的状态 小圆点如何通过配置显示

### ISSUE THREAD

**Issue by im-not-a-programmer** [ant-design/pro-components#1777]
📷 复现步骤
column 配置
{
title: '状态',
dataIndex: 'status',
initialValue: 'all',
valueType: 'radioButton',
valueEnum: {
all: { text: '全部', status: 'all' },
close: { text: '待发布', status: 'Default' },
running: { text: '发布中', status: 'Processing' },
online: { text: '发布成功', status: 'Success' },
error: { text: '发布失败', status: 'Error' },
},
}

🏞 期望结果
按照官方文档期望得到 状态的文字以及 不同颜色的小圆点显示，但并未按预定显示 直接显示了 status值

© 版本信息
ProComponents 版本: [2.27.2]
antd 版本：[4.11.2]

**Comment by chenshuai2144** [comment]
来个重现把，这个功能官网表现很正常

**Comment by im-not-a-programmer** [comment]
重现 就是上面的重现配置，配置后列表里面不会按照  valueEnum 显示 小圆点以及 valueEnum里面不同状态的 text

**Comment by kaoding** [comment]
> 重现 就是上面的重现配置，配置后列表里面不会按照 valueEnum 显示 小圆点以及 valueEnum里面不同状态的 text

给代码重现。

**Comment by im-not-a-programmer** [comment]
import React from 'react';
import { PlusOutlined } from '@ant-design/icons';
import { Button, Tag, Space } from 'antd';
import type { ProColumns } from '@ant-design/pro-table';
import ProTable from '@ant-design/pro-table';
import request from 'umi-request';
type GithubIssueItem = {
  url: string;
  id: number;
  number: number;
  title: string;
  labels: {
    name: string;
    color: string;
  }[];
  state: string;
  comments: number;
  created_at: string;
  updated_at: string;
  closed_at?: string;
};
const columns: ProColumns<GithubIssueItem>[] = [
  {
    title: '标题',
    dataIndex: 'title',
    copyable: true,
    ellipsis: true,
    tip: '标题过长会自动收缩',
    formItemProps: {
      rules: [
        {
          required: true,
          message: '此项为必填项',
        },
      ],
    },
    width: '30%',
  },
  {
    title: '状态',
    dataIndex: 'state',
    filters: true,
    onFilter: true,
    valueType: 'select',
    formItemProps: {
      rules: [
        {
          required: true,
          message: '此项为必填项',
        },
      ],
    },
    valueEnum: {
      all: { text: '全部', status: 'Default' },
      open: {
        text: '未解决',
        status: 'Error',
      },
      closed: {
        text: '已解决',
        status: 'Success',
        disabled: true,
      },
      processing: {
        text: '解决中',
        status: 'Processing',
      },
    },
  },
  {
    title: '标签',
    dataIndex: 'labels',
    search: false,
    formItemProps: {
      rules: [
        {
          required: true,
          message: '此项为必填项',
        },
      ],
    },
    renderFormItem: (_, { defaultRender }) => {
      return defaultRender(_);
    },
    render: (_, record) => (
      <Space>
        {record.labels.map(({ name, color }) => (
          <Tag color={color} key={name}>
            {name}
          </Tag>
        ))}
      </Space>
    ),
  },
  {
    title: '创建时间',
    key: 'showTime',
    dataIndex: 'created_at',
    valueType: 'date',
    hideInSearch: true,
    formItemProps: {
      rules: [
        {
          required: true,
          message: '此项为必填项',
        },
      ],
    },
  },
];
export default () => {
  return (
    <ProTable<GithubIssueItem>
      columns={columns}
      request={async (params = {}) =>
        request<{
          data: GithubIssueItem[];
        }>('https://proapi.azurewebsites.net/github/issues', {
          params,
        })
      }
      rowKey="id"
      search={{
        labelWidth: 'auto',
      }}
      form={{
        ignoreRules: false,
      }}
      pagination={{
        pageSize: 5,
      }}
      dateFormatter="string"
      headerTitle="高级表格"
      toolBarRender={() => [
        <Button key="button" icon={<PlusOutlined />} type="primary">
          新建
        </Button>,
      ]}
    />
  );
};

**Comment by im-not-a-programmer** [comment]
直接拷贝官方例子  就和官方展示出来的不一致呀

**Comment by chenshuai2144** [comment]
所以你要给我们复现环境，让我们知道你为啥和官方不一样，是自定义了什么导致的

**Comment by im-not-a-programmer** [comment]
没有自定义  就和上面代码一样

**Comment by kaoding** [comment]
> 没有自定义 就和上面代码一样

用这个，能直接看到代码运行的。
https://codesandbox.io/
