### ISSUE TITLE
点击取消时，formRef也没拿到数据，还是被重置了

### ISSUE THREAD

**Issue by JTenacity** [ant-design/pro-components#1778]
![image](https://user-images.githubusercontent.com/8186664/105975368-d8fbb680-60c9-11eb-9a18-1e126747feca.png)

_Originally posted by @chenshuai2144 in https://github.com/ant-design/pro-components/issues/1775#issuecomment-768174810_

@chenshuai2144 我用了formRef还是不好使，而且我把destroyOnClose改成false了点击取消表单还是重置了

const onCancel = () => {
    console.log(ref.current.getFieldsValue());
    const values = form.getFieldsValue();
    const isSame = checkSame(values);
}

<ModalForm
      title="编辑企业信息"
      visible={visible}
      width={638}
      className={styles.editEnterprise}
      form={form}
      formRef={ref}
      labelCol={{ span: 7 }}
      wrapperCol={{ span: 15 }}
      layout="horizontal"
      validateMessages={{
        required: '${label}不能为空',
      }}
      modalProps={{
        width: 638,
        maskClosable: false,
        onCancel: onCancel,
        destroyOnClose: false,
      }}
      onFinish={async (values) => {
        let success = await editSubmit(values);
        if (success) {
          setReload && setReload(true);
          setVisible(!success);
        }
      }}
    >
 ....
</ModalForm>

**Comment by chenshuai2144** [comment]
不要重复提同样的issue

**Comment by JTenacity** [comment]
@chenshuai2144 你说用formRef数据，我在modalProps的onCancel中用formRef.current.getFieldsValue()，可是拿到的都是undefined，表单数据被重置了

**Comment by chenshuai2144** [comment]
不应该的，清空了 dom 或销毁了 dom
