### ISSUE TITLE
🧐[问题] ProTable 重置和查询按钮布局问题， 按钮应该和搜索框在同一高度

### ISSUE THREAD

**Issue by linxianxi** [ant-design/pro-components#1780]
这个不在同一高度
![image](https://user-images.githubusercontent.com/47104575/106076874-6b906a00-614b-11eb-8a9c-45822e7b3429.png)

还有这个能不能在最右边
![image](https://user-images.githubusercontent.com/47104575/106076901-7c40e000-614b-11eb-97a4-36c9c51c5ec3.png)

**Comment by chenshuai2144** [comment]
配置拉一下给我，代码是很久之前写的只服务于几个人，所以问题有点多

**Comment by linxianxi** [comment]
> 配置拉一下给我，代码是很久之前写的只服务于几个人，所以问题有点多

https://codesandbox.io/s/floral-feather-1ssff?file=/App.tsx

要全屏才能复现 
![image](https://user-images.githubusercontent.com/47104575/106102936-19ffd380-617b-11eb-98b8-d0aaa020af11.png)

**Comment by chenshuai2144** [comment]
。。。宽度算错了，哈哈这个就比较难
