### ISSUE TITLE
🧐[问题] ProTable 的 pageSize 从大变成小，例如 50 变成 10，控制台报错

### ISSUE THREAD

**Issue by linxianxi** [ant-design/pro-components#1783]
![image](https://user-images.githubusercontent.com/47104575/106091739-fb441180-6167-11eb-9a52-a548fc16649b.png)

你们的文档沙盒地址，pageSize 先切换到50，再切换到10
https://codesandbox.io/s/dazzling-ishizaka-3r3xu

**Comment by chenshuai2144** [comment]
新版本解决了，是 state 更新的问题，你可以先忽略掉

**Comment by linxianxi** [comment]
> 新版本解决了，是 state 更新的问题，你可以先忽略掉

还没发布是么

**Comment by chenshuai2144** [comment]
嗯，这个的意思是当前的数据比 pageSize 大。
pageSize  50->10 的时候数据没有清空，所以有一点时间 dataSource 大于 pageSize

**Comment by fenglijunnb** [comment]
@chenshuai2144 请问一下这个问题是升到第几个版本就解决了呢，是仅仅需要升级pro-table的就行吗
