### ISSUE TITLE
🧐[问题]请教一个关于表格编辑事件的问题。

### ISSUE THREAD

**Issue by oak-c** [ant-design/pro-components#1785]
### 🧐 问题描述

您好，
在editable 编辑行配置里面的几个事件，比如：
onDelete    |     删除一行的时候触发     |     `(key: Key, row: T) => Promise<boolean>`
返回true或者false的时候好像没什么区别呢，那如果服务端删除失败了，本地怎么拦截表格的删除动作呢？
保存同理。

### 💻 示例代码

```typescript
<ProTable<IT.IConfig>
  {...{
    columns,
    rowKey: 'id',
    bordered: true,
    dateFormatter: 'string',
    headerTitle: '配置管理',
    search: { labelWidth: 'auto' },
    pagination: { pageSize: 50 },
    request: async (params = {}) => await HttpQueryConfig(params),
    editable: {
      type: 'multiple',
      onDelete, // 这个方法是一个promise，会返回Boolean。
      onSave, // 这个方法是一个promise，会返回Boolean。
    },
  }}
/>
```

### 🚑 其他信息

"@ant-design/pro-table": "^2.27.2"

**Comment by chenshuai2144** [comment]
Promise 有错误处理的，

`throw new Error("发生了错误")` 就可以打断。

**Comment by oak-c** [comment]
> Promise 有错误处理的，
> 
> `throw new Error("发生了错误")` 就可以打断。
> 或者 `return Promise((res,rej)=>rej(”错误“))`

谢谢指点
