### ISSUE TITLE
@umijs/pro-layout 文档优化

### ISSUE THREAD

**Issue by afc163** [ant-design/pro-components#1786]
https://github.com/umijs/umi/blob/master/docs/plugins/plugin-layout.zh-CN.md#%E6%89%A9%E5%B1%95%E7%9A%84%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE

- [x] `新增如下配置` 的描述很奇怪，这里是文档不是 changelog。最好不要写这样的语句。

<img width="242" alt="图片" src="https://user-images.githubusercontent.com/507615/106107403-db214c00-6181-11eb-86ab-ea240588170e.png">

- [x] target 属性很常用，我补充在 https://github.com/umijs/umi/pull/6087 里了。
- [x] 下面的 `name` `icon` 和其他两个属性的层级不是同一级，放在一起非常奇怪。需要拉出两个层级。
- [x] 下面的 menu 里的 name icon 和 flatMenu/access 只有一共四个属性的说明，其他的没有，比较奇怪，建议都补全。

**Comment by chenshuai2144** [comment]
menu 要同时支持一下吗，这个是plugin插件支持的，我更推荐打平直接写

**Comment by afc163** [comment]
> menu 要同时支持一下吗，这个是plugin插件支持的，我更推荐打平直接写

啥意思？

**Comment by chenshuai2144** [comment]
这样的方式
```tsx
menu : {
 name: string
},
name:string
```

**Comment by afc163** [comment]
打平比较好

**Comment by chenshuai2144** [comment]
我删掉了非打平的用法
