### ISSUE TITLE
👑 [需求] ModalForm

### ISSUE THREAD

**Issue by 569202812** [ant-design/pro-components#1787]
### 🥰 需求描述
 ModalForm支持 maskClosable 禁止击蒙层是否允许关闭

**Comment by JunlinZhu-Tommy** [comment]
你可以使用 `modalProps` 来实现该需求. [文档](https://procomponents.ant.design/components/modal-form#modalform)

例子:
```javascript
      modalProps={{
        keyboard: false,
        mask: false,
        maskClosable: false,
      }}
```

**Comment by 569202812** [comment]
> 你可以使用 `modalProps` 来实现该需求. [文档](https://procomponents.ant.design/components/modal-form#modalform)
> 
> 例子:
> 
> ```js
>       modalProps={{
>         keyboard: false,
>         mask: false,
>         maskClosable: false,
>       }}
> ```
好的感谢
