### ISSUE TITLE
🐛[BUG]【PRO_LAYOUT】菜单和点亮关闭问题

### ISSUE THREAD

**Issue by TernenceWu0702** [ant-design/pro-components#179]
### 🐛 bug 描述
在两个有二级菜单的一级菜单间点击会出现菜单点亮错误以及以及菜单关闭的错误

### 📷 复现步骤
1.点击一个二级菜单
<img width="1116" alt="WX20200813-111954@2x" src="https://user-images.githubusercontent.com/50820522/90090576-f4ab1480-dd56-11ea-8b02-ab3e4f9bc93e.png">
2.在点击另一菜单下的二级菜单，发现之前的以及菜单并未合并
<img width="1034" alt="WX20200813-112547@2x" src="https://user-images.githubusercontent.com/50820522/90090906-c548d780-dd57-11ea-8491-b6a443a65871.png">
3.再点击一个二级菜单，之前的一级菜单会关闭，如果点击的是前一个二级菜单，关闭以及菜单，这就是相当严重的BUG了
<img width="1160" alt="WX20200813-113055@2x" src="https://user-images.githubusercontent.com/50820522/90091255-7ea7ad00-dd58-11ea-9a60-86cd0c4bb0e5.png">

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你是用翻译器翻译的中文吗？可以用英文的
