### ISSUE TITLE
🧐[问题]ProTable自动生成“新建”页面时，怎么输出TreeSelect？

### ISSUE THREAD

**Issue by fengnex** [ant-design/pro-components#1792]
### 🧐 问题描述
当需要生成的新建form中有属性具有多层级父子关系时，需要使用TreeSelect，这样才能方便地支持在新建、编辑页面上调整对应的熟悉数据的值。

这种情况下，通过ProTable<TableListItem, TableListItem>来自动生成CreateForm组件时，怎么才能生成TreeSelect组件？

能否通过 const columns: ProColumns<TableListItem>[] = []
在这里定义适当的column的{}来实现？如果可以，应该怎么写？

最好能提供实例，谢谢

**Comment by fengnex** [comment]
有人遇到这个问题了没？

**Comment by fengnex** [comment]
官方有人看看吗？

**Comment by ChenCheng220** [comment]
可以通过renderFormItem自定义渲染：
```
{
    title: '所属机构',
    dataIndex: 'did',
    renderFormItem: (_, { type, defaultRender, ...rest }) => {
      const treeData = getTreeData();
      return <TreeSelect treeData={treeData} allowClear placeholder="请选择" {...rest} />;
    },
}
```

**Comment by xoptimal** [comment]
@ChenCheng220  为什么我使用了, 选中后, 并没有绑定好 value,  选完是个空的

**Comment by fengnex** [comment]
@ChenCheng220 选中一个选项后，保存数据的时候获取不了选中的值，怎么办呢？

**Comment by xoptimal** [comment]
@fengnex   你的也是自定义的吗 ~   我是自定义的select了, 不是自定义没有这个问题~

**Comment by fengnex** [comment]
没有自定义，就用了TreeSelect
@xoptimal

**Comment by xoptimal** [comment]
我自定义的   <TreeSelect {...params} {...other}>{list.map(renderTreeItem)}</TreeSelect> 就不行, 不能回显

**Comment by xoptimal** [comment]
你咋写的, 我看看 ~ 我用自带验证过, 是可以回显的~

**Comment by fengnex** [comment]
```
{title: 'test', dataIndex: 'parentId', hideInSearch:true, 
      renderFormItem: (_, { ...rest }) => {        
        return <TreeSelect treeData={deptTreeSelect} showSearch={true} 
        treeDefaultExpandAll={true}
        allowClear placeholder="请选择" />;
      },
    },
```

**Comment by xoptimal** [comment]
你再去试试, 缺少了 rest
```
{
  title: 'test', 
  dataIndex: 'parentId', hideInSearch:true, 
  renderFormItem: (_, { ...rest }) => {        
    return <TreeSelect treeData={deptTreeSelect} showSearch={true} treeDefaultExpandAll={true} allowClear placeholder="请选择" {...rest} />;
  }
},
```

**Comment by fengnex** [comment]
可以了，谢谢@xoptimal

**Comment by xoptimal** [comment]
我的也可以了, 发觉问题出在自定义render item 上了
现在初步做了data格式化成treedata ~ 不过不利于自定义item , 还望看看咋回事 @chenshuai2144 

@fengnex  想在item加一些东西, 所以用了自定义 item -> node item 自己实现了, 没想到search上有坑

**Comment by fengnex** [comment]
点赞@xoptimal
代码能否分享下？

**Comment by xoptimal** [comment]
```
{
  key: 'departmentIds',
  label: 'department',
  columnsProps: {
	hideInTable: true,
    renderFormItem: (_, {type, defaultRender, ...rest}) => (
		<ExTreeSelect options={departmentList} fieldNames={{label: 'name', value: 'id', children: 'children'}} {...rest} />
	)
  }
}
```
@fengnex  以前我写了个类似pro的, 不过很古老了, 现在基于pro 又迭代了一个版本, 有兴趣可以可以看看后续我准备开源的 remjs ,  配置精简,  更便捷, 专注于业务层开发~ 定义了很多模板库,  也基于ant 组件做的一层基础完备, 类似现在提倡原子组件思想

**Comment by ChenCheng220** [comment]
@fengnex rest里面有value和onChange需要传给组件

**Comment by fengnex** [comment]
@ChenCheng220 谢谢！
@xoptimal 期待你的大作！
同时期待Pro发展快一点！
