### ISSUE TITLE
🐛[BUG]EditTable onSave返回类型与文档不一致

### ISSUE THREAD

**Issue by jefn76** [ant-design/pro-components#1795]
### 🐛 bug 描述
EditTable onSave返回类型与文档不一致

文档：https://procomponents.ant.design/components/editable-table#editable-编辑行配置
onSave返回类型写的是() => Promise<boolean>
实际源代码：
/** 行保存的时候 */
    onSave?: (key: RecordKey, row: T & {
        index?: number;
    }, newLineConfig?: NewLineConfig<T>) => Promise<any | void>;
### 🏞 期望结果
我这边后端都返回错误了，onSave还能顺利添加。希望能和文档保持一致，返回一个boolean类型的。

### © 版本信息
pro-table@2.27.2
antd: @4.11.2

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本: 3.3.7
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by DerrickTel** [comment]
后端报错了，不应该走resolve吧？不走resolve就不会顺利添加了。
不过，这里确实也有问题。
