### ISSUE TITLE
🧐[问题] ProTable 怎么手动触发查询并带上 form 查询参数和分页参数

### ISSUE THREAD

**Issue by linxianxi** [ant-design/pro-components#1799]
现在有一个需求，我先跳到 100页，更新一条数据，然后要重新请求这页。我用 ref.current.submit() 不会带上分页的参数。怎么把 form 参数和分页参数一起带上。    

触发 request 的 保存 params 到 state 行不通，因为 data 是在 request 中 return 的。还是要通过触发 request 来更新数据

**Comment by linxianxi** [comment]
@chenshuai2144 帅哥有什么办法吗

**Comment by linxianxi** [comment]
ref.current.reload

**Comment by siifan168** [comment]
兄弟问题解决了吗

**Comment by GOUYONGCHAO** [comment]
然而并没有

**Comment by CcLmL** [comment]
![image](https://github.com/user-attachments/assets/6587bf30-e257-4746-817e-9752993f368f)
这个是不是你要的？
