### ISSUE TITLE
👑 [需求]ProTable 日期区间支持自定义参数名称.

### ISSUE THREAD

**Issue by l745230** [ant-design/pro-components#180]
### 🥰 需求描述

{
      title: '创建时间',
      dataIndex: 'createTime',
      width: 160,
      valueType: 'dateRange',
      rangeStart:'beginCreateTime', // 添加类似的设置
      rangeEnd:'endCreateTime',  //  添加类似的设置
    },

目前生成的为
createTime[0]: 2020-08-01
createTime[1]: 2020-08-30

希望能够进行自定义,
beginCreateTime:2020-08-01
endCreateTime:2020-08-01

**Comment by chenshuai2144** [comment]
来个 pr？

**Comment by l745230** [comment]
有大佬感兴趣来pr吗~~后端程序猿表示对前端仅仅处于会用的程度...

**Comment by chenshuai2144** [comment]
😁 描述的越详细越容易被实现

**Comment by l745230** [comment]
功能描述:
后端接口,表格列名称与列查询名称不同.根据key/dataIndex 自动生成的参数名称无法使用.

场景
1.接口返回用户信息字段为 account(账号名),nickname(昵称), 使用name做为关键词 模糊查询account,nickname.
2.接口返回用户创建时间 createTIme.  使用startTime,endTIme 两个字段区间查询createTIme.

需求:
Columns 列定义添加支持自定义参数名称.

思路参考:
Columns添加paramName,paramName2作为自定义参数名称
paramName 为空,走旧逻辑使用key/dataIndex作为参数名
paramName 不为空,作为参数名
paramName2, 当为区间组件时, paramName与paramName2不为空. 分别替换key[0]  key[1]

API示例:
{
title: '账号名',
dataIndex: 'account',
hideInSearch: true,
},
{
title: '昵称',
dataIndex: 'nickname',
paramName:'name',
},
{
title: '创建时间',
dataIndex: 'createTime',
valueType: 'dateRange',
paramName:'startTIme',
paramName2:'endTine',
},

访问url
配置前
/userList?nickname=张三&createTime[0]=2020-08-13&createTime[1]=2020-08-30
配置自定义参数名称后
/userList?name=张三&startTime=2020-08-13&endTime=2020-08-30

**Comment by WoodsLiu** [comment]
我的想法给`ProTable`增加一个`props`属性: `renameReqKeyMap`,然后在`submit`的时候可以获取`formValue`, 对`key`进行`rename`操作,当然这个`rename`操作是在`beforeSearchSubmit`之前的,也就是说在`beforeSearchSubmit`中可以获取到`rename key`的对象, 我这边已经实现了
这个是我的思路, 或者还有更好的实现方法?

**Comment by WoodsLiu** [comment]
我的想法给`ProTable`增加一个`props`属性: `renameReqKeyMap`,然后在`submit`的时候可以获取`formValue`, 对`key`进行`rename`操作,当然这个`rename`操作是在`beforeSearchSubmit`之前的,也就是说在`beforeSearchSubmit`中可以获取到`rename key`的对象.

但是它需要满足一定的规定比如说:

- 如果只是需要将`key a` -> `key b` 只需要`{ a: 'b' }`

举个栗子

```js
const formValue = {
  name: 'lsl',
  age: 10,
};
const renameReqKeyMap = {
  name: 'name1',
};
// 最终结果为 { name1: 'lsl', age: 10 }
```

- 如果是嵌套对象 `key 'a.b.c' -> key 'f.b.c'` 只需要`{ 'a.b.c' : ['f'] }` 以此类推

**举个例子**

```js
const formValue = {
  a: {
    b: { c: 1 },
  },
  age: 10,
};
const renameReqKeyMap1 = {
  'a.b.c': ['f'],
};
// 最终结果为 { f:{ b: { c: 1 } }, age: 10 }

const renameReqKeyMap2 = {
  'a.b.c': ['f', 'g'],
};
// 最终结果为 { f:{ g: { c: 1 } }, age: 10 }
// 以此类推
```

- 如果是`formValue`的`key [x,xx]`映射成`{a:x,b:xx}`,则需要传入一个数组,并且**保证传入的顺序**

**举个例子**

```js
const formValue = {
  createdAt: ['2020-8-20', '2020-8-27'],
  age: 10,
};
const renameReqKeyMap = {
  createdAt: ['startTime', 'endTime'],
};
// 最终结果为 { startTime: '2020-8-20',endTime: '2020-8-27', age:10 }
```

- 但是有个其他情况就是: 假如说用户在传入数组的时候多传入或者少传入,这样子应该怎么去处理呢

```js
// 多传入
const formValue = {
  status: [1, 2, 3, 4, 5],
};
const renameReqKeyMap = {
  status: ['startTime', 'endTime'],
};
// 省略: { startTime: 1, endTime: 2 }
// 利用原来的字段: { startTime:1, endTime: 2, list: [3, 4, 5] }

// 少传入
const formValue = {
  status: [1],
  age: 10,
};
const renameReqKeyMap = {
  status: ['startTime', 'endTime'],
};
// 省略: { startTime: 1 }
```

应该怎么去处理转换呢? 省略掉? 还是利用原来的字段? 或者有其他思路

我这边已经实现前面两种情况,但是最后一种情况,不可控因素有点多 <img width="569" alt="Screen Shot 2020-08-14 at 6 53 34 PM" src="https://user-images.githubusercontent.com/40518195/90242361-771efb80-de5f-11ea-930c-27cfe9af0e29.png"> ![Screen Shot 2020-08-14 at 6 56 16 PM](https://user-images.githubusercontent.com/40518195/90242552-da109280-de5f-11ea-843d-53e0eec35d5b.png)

这个是我的思路, 或者还有更好的实现方法或者其他思路?

**Comment by WoodsLiu** [comment]
或者把这个属性拆分到每一个`column`,需要`rename key`的属性列在其 Column 中定义

```js
const columns = [
  {
    title: '创建时间',
    key: 'since',
    dataIndex: 'createdAt',
    valueType: 'dateTime',
    // 转换成{ transformSince:'' }
    renameKey: 'transformSince',
  },
  {
    title: '日期区间',
    key: 'createdAtRange',
    dataIndex: 'createdAtRange',
    valueType: 'dateRange',
    // 转换成 { startTime:'', endTime:'' }
    renameKey: ['startTime', 'endTime'],
  },
  {
    title: '更新时间',
    key: 'since2',
    dataIndex: 'createdAt',
    valueType: 'date',
  },
];
```

**Comment by l745230** [comment]
https://github.com/ant-design/pro-components/issues/247

**Comment by l745230** [comment]
@chenshuai2144  我尝试结合 @WoodsLiu 的思路,封装了下. 
目前是能实现提交的时候根据映射关系,自动处理参数, 与url自动将参数回显. 


 // 日期参数映射关系
  dateParamKeyMap?: [
    {
      key: String; // 参数名称
      valueType: 'dateRange'; // 日期类型(目前只实现区间日期类型)
      startTime?: String; // 区间日期,重命名开始参数名
      endTime?: String; // 区间日期,重命名结束参数名
      dateTime?: String; // 单个日期,重命名参数名
    },
  ];

调用:
dateParamKeyMap={[
          {
            key: 'createTime',
            valueType: 'dateRange',
            startTime: 'startTime',
            endTime: 'endTime',
          },
        ]}

提交处理:
const onSubmit = (params: any) => {
    // 处理日期参数提交值
    if (dateParamKeyMap) {
      dateParamKeyMap.map(item => {
        if (item.valueType === 'dateRange') {
          if (item.startTime) {
            params[`${item.startTime}`] = params[`${item.key}`]?.[0];
          }
          if (item.endTime) {
            params[`${item.endTime}`] = params[`${item.key}`]?.[1];
          }
          delete params[`${item.key}`];
        }
      });
    }
}

Url回显:
http://localhost:8000/#/List?startTime=2020-08-01&endTime=2020-08-02

 // 处理日期参数初始值
  let othersQuery = {};
  if (query && dateParamKeyMap) {
    dateParamKeyMap.map(item => {
      if (item.valueType === 'dateRange') {
        if (query[`${item.startTime}`] && query[`${item.endTime}`]) {
          othersQuery[`${item.key}`] = [
            moment(query[`${item.startTime}`], 'YYYY-MM-DD'),
            moment(query[`${item.endTime}`], 'YYYY-MM-DD'),
          ];
        }
      }
    });
  }

form={{
          initialValues: { 
            ...othersQuery,
          },
        }}

**Comment by l745230** [comment]
虽然效果实现了,但是封装的很粗陋, 还是期望能用上官方提供的.

**Comment by dmdoit** [comment]
我觉得默认应该是
createTime[0]: 2020-08-01
createTime[1]: 2020-08-30

如果你需要startTime和endTime这样的格式的话，可以在beforeSearchSubmit 这个api中手动转化一下

**Comment by zmj0920** [comment]
{
      title: '时间区间',
      key: 'dateTimeRange',
      width: 100,
      align: 'center',
      dataIndex: 'createdAtRange',
      valueType: 'dateTimeRange',
      // hideInForm: true,
      // initialValue: [moment('2019-11-16 12:50:26'), moment('2019-11-16 12:50:26')],
      fieldProps: {
        className: `${style.pre}`,
      },
      search: {
        transform: (value) => ({
          //转化值的 key, 一般用于事件区间的转化
          startTime: value[0],
          endTime: value[1],
        }),
      },

**Comment by zmj0920** [comment]
![Uploading image.png…]()

**Comment by zmj0920** [comment]
![image](https://user-images.githubusercontent.com/42410507/98004444-e8e95e80-1e2a-11eb-846c-9fd882ce64bb.png)

**Comment by xgj1988** [comment]
这个问题还没解决？

**Comment by watsonhaw5566** [comment]
> search: {
>         transform: (value) => ({
>           //转化值的 key, 一般用于事件区间的转化
>           startTime: value[0],
>           endTime: value[1],
>         }),
>       },

解决了，用 zjm0920 的方案就好
