### ISSUE TITLE
🧐[问题]pro-table怎样监听排序sort change事件，想在点击排序后把分页改为从1开始

### ISSUE THREAD

**Issue by wmy1992** [ant-design/pro-components#1801]
### 🧐 问题描述

pro-table怎样监听排序sort change事件，想在点击排序后把分页改为从1开始

**Comment by chenshuai2144** [comment]
直接监听table的 onChange，里面是有 sorter的。


onChange | 分页、排序、筛选变化时触发 | function(pagination, filters, sorter, extra: { currentDataSource: [], action: paginate \| sort \| filter }) | -
-- | -- | -- | --
