### ISSUE TITLE
🧐[问题] ProFormText设置onChange事件后，属性值无法更改

### ISSUE THREAD

**Issue by gaven004** [ant-design/pro-components#1803]
### 🧐 问题描述

ProFormText设置onChange事件后，属性值无法更改，一直是原来的值，是否需要返回什么值，或回调什么函数？

### 💻 示例代码

<ProForm.Group>
<ProFormText
  name="icon"
  label="图标"
  width="md"
  fieldProps={{
    prefix: iconPrefix,
    onChange: (e) => {
      const {value} = e.target;
      console.log(value);
    }
  }}
/>

### 🚑 其他信息

  "dependencies": {
    "@ant-design/icons": "^4.4.0",
    "@ant-design/pro-descriptions": "^1.14.0",
    "@ant-design/pro-form": "^1.15.0",
    "@ant-design/pro-field": "^1.9.0",
    "@ant-design/pro-layout": "^6.12.0",
    "@ant-design/pro-table": "^2.27.0",
    "@umijs/route-utils": "^1.0.33",
    "antd": "^4.10.0",
    "classnames": "^2.2.6",
    "dva": "^2.4.0",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "qs": "^6.9.6",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.1.4",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "react-icons": "^4.1.0",
    "umi": "^3.3.7",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"
  },

**Comment by chenshuai2144** [comment]
你不能设置 onChange，有需要建议使用 ProForm onValuesChange

**Comment by zhangli20080808** [comment]
比如 我想改变提交的文字 或者 隐藏 重置 按钮 这种操作可以嘛
