### ISSUE TITLE
搜索表单自定义ProColumns使用renderFormItem并添加formItemProps必填规则后，搜索表单上也添加了必填条件

### ISSUE THREAD

**Issue by cui-stack** [ant-design/pro-components#1808]
![微信图片_20210130175549](https://user-images.githubusercontent.com/9345023/106353343-d5b03700-6324-11eb-9489-f5013f1c0080.png)
![微信图片_202101301755491](https://user-images.githubusercontent.com/9345023/106353347-d6e16400-6324-11eb-9b77-17eede3789a2.png)
![微信图片_202101301755492](https://user-images.githubusercontent.com/9345023/106353348-d779fa80-6324-11eb-8ed0-6746338fe02d.png)

**Comment by chenshuai2144** [comment]
@cui-stack  是个bug，升级一下你的 ProTable 版本
