### ISSUE TITLE
👑 [需求]Form表单如何实现手动触发校验？

### ISSUE THREAD

**Issue by wmf508** [ant-design/pro-components#1809]
### 🥰 需求描述

想要实现在提交表单后根据返回的errorCode判断是否显示用户名已存在的校验，3.x版本是用force来手动触发，4.x不知道如何实现

**Comment by chenshuai2144** [comment]
validateFields | 触发表单验证 | (nameList?: NamePath[]) => Promise
-- | -- | --


https://ant.design/components/form-cn/#API

认真读一下文档会受益匪浅

**Comment by junkeLee** [comment]
使用 setFields 方法。例如需要校验的字段是name，提交到服务器后，服务器返回”此名称已存在“，那么就可以使用 setFields 方法进行校验：
`
form.setFields([
    errors: ['此名称已存在'],
    name: 'name',
    value: 'value'
])
`
