### ISSUE TITLE
🐛[BUG] ProTable v2.5.7 initialValue 无效

### ISSUE THREAD

**Issue by DeyuanTan** [ant-design/pro-components#181]
### 🐛 bug 描述

columns 中设置initialValue 没有自动填充到搜索表单中

### 📷 复现步骤

1、设置ProColumns [{title: 'ID', dataIndex: 'id', initialValue: 1}]

### 🏞 期望结果

搜索表单中 ID 默认值为1

### © 版本信息

- ProTable v2.5.7
- umi 版本 v3.x
- 浏览器环境 chrome 
- 开发环境 [ mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/8966624/90093016-22935780-dd5d-11ea-9ca9-8db4d114d9a1.png)

![image](https://user-images.githubusercontent.com/8966624/90093047-3474fa80-dd5d-11ea-8ea9-92715bf9c1c3.png)

**Comment by chenshuai2144** [comment]
最好用 From 的规范用法，用 form 里的配置 `initialValues`

**Comment by DeyuanTan** [comment]
initialValue 这个是要废弃掉了吗？

首先这个initialValue 我是在官方 demo里看到可以这样配置的：
![image](https://user-images.githubusercontent.com/8966624/90104496-f389df80-dd76-11ea-8b48-e90cc31113da.png)

然后发现有问题的时候我看Table.d.ts里也注明这个是可以设置默认值的
![image](https://user-images.githubusercontent.com/8966624/90104586-1e743380-dd77-11ea-8abe-f083b533811e.png)

但是实际使用的时候却是用不了？

个人觉得在配置表格列的时候配置用initialValue还是挺简单明了的，希望能保留这个配置。如果确定废弃的话，最好在相关的声明文件中删除相关说明。
