### ISSUE TITLE
🧐[问题]可编辑表格EditableProTable  编辑状态下的 text文本 保存 取消 删除 在哪里可以更改

### ISSUE THREAD

**Issue by 271915902** [ant-design/pro-components#1810]
### 💻 示例代码

>

**Comment by 271915902** [comment]
![image](https://user-images.githubusercontent.com/70524941/106375446-ffba3580-63c6-11eb-9f14-b4b4300b0dfa.png)

**Comment by 271915902** [comment]
看了更新日志 提供了action的国际化

**Comment by JunlinZhu-Tommy** [comment]
有例子么．
