### ISSUE TITLE
🧐[问题] 使用 page-container 的时候，宽度设置的问题

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/pro-components#1811]
### 🧐 问题描述

设置 content 内容会超出容器显示，修改 css  ant-pro-page-container-content 为 width: 100%，就正常了

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/37258382/106377654-7ceea600-63d9-11eb-905f-d1112f1f7291.png)

**Comment by chenshuai2144** [comment]
我看看是不是加个 max-width
