### ISSUE TITLE
🧐[问题]EditableProTable 实时保存的编辑表格如何通过外部保存按钮触发表单验证？

### ISSUE THREAD

**Issue by aoyeQ** [ant-design/pro-components#1814]
### 🧐 问题描述
在文档示例中的【实时保存的编辑表格】demo要如何触发验证规则

### 💻 示例代码
同文档示例中的【实时保存的编辑表格】

有试过在外部保存editable中的form，但是会触发死循环

**Comment by chenshuai2144** [comment]
外部拿不到表格的实例的，我加个新的api吧

**Comment by h-ping** [comment]
刚好最近用到这个功能，请问什么时候发布呢？

**Comment by chenshuai2144** [comment]
周三左右发布，支持了一下 useForm

**Comment by wmy1992** [comment]
问一下这个发布了吗，更新到2.29.0还是没有起作用呢
