### ISSUE TITLE
🐛[BUG] ProFormSelect options数据返回驼峰字段控制台报错

### ISSUE THREAD

**Issue by qq382724935** [ant-design/pro-components#1817]
### 🐛 bug 描述

options返回数组，当对象中包含驼峰字段时控制台会报错
### 📷 复现步骤
打开codesandbox点击下拉框控制台会报错

### 💻 复现代码
https://codesandbox.io/s/cold-cloud-yd4us?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
因为我们会把所有的option 的内容注入到dom上，你可以把不需要的筛选掉
