### ISSUE TITLE
🐛[BUG]EditableProTable的rowKey为string类型时，无法修改数据

### ISSUE THREAD

**Issue by yycdaizi** [ant-design/pro-components#1819]
### 🐛 bug 描述

EditableProTable的rowKey为string类型时，无法修改数据。从源码里看，rowKey都会强制转成number

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/7036329/106544668-e6d68f00-6542-11eb-9b28-7bf6b61158d2.png)

**Comment by chenshuai2144** [comment]
你的数据给一下看看

**Comment by chenshuai2144** [comment]
试着升级一般版本，最好用真实的id
