### ISSUE TITLE
🧐[问题]EditableProTable保存失败后，能否保持该行仍是编辑状态？？？

### ISSUE THREAD

**Issue by qianlulu** [ant-design/pro-components#1823]

**Comment by DerrickTel** [comment]
保存失败，应该不走resolve呀...这样的话就可以保持在编辑状态。

**Comment by qianlulu** [comment]
@DerrickTel 是校验重复性数据那种

**Comment by DerrickTel** [comment]
方便给一个`codesandbox`之类的，可示例的吗？

**Comment by qianlulu** [comment]
@DerrickTel 触发onSave事件后，默认取消编辑此行

**Comment by chenshuai2144** [comment]
onSave 必须要等用户的 onSave 成功之后 才会取消的，你是不是成功失败都用了 resolve

**Comment by qianlulu** [comment]
@chenshuai2144 [https://codesandbox.io/s/kebianjibiaoge-forked-whyug?file=/App.tsx](url)

**Comment by qianlulu** [comment]
@chenshuai2144 https://codesandbox.io/s/kebianjibiaoge-forked-whyug?file=/App.tsx

**Comment by chenshuai2144** [comment]
这个看起来好像没问题，失败了虽然没有提示，但是保存状态还是在的
