### ISSUE TITLE
QueryFilter 点击查询按钮会出现加载效果，无法关闭🐛[BUG]

### ISSUE THREAD

**Issue by MrArky** [ant-design/pro-components#1825]
QueryFilter 点击查询按钮会出现加载效果，无法关闭

**Comment by chenshuai2144** [comment]
来个重现，是因为onFinsh吗？

**Comment by MrArky** [comment]
> Hello @MrArky. Please provide a online reproduction by forking this link https://codesandbox.io/ or a minimal GitHub repository.
> 
> 你好 @MrArky, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

来个重现，是因为onFinsh吗？

Originally posted by @chenshuai2144 in #1825 (comment)

之前提这个问题，是因为我有两个页面，一个能正常运行执行查询，另一个即使完全按照官方代码进行copy，整个页面只有QueryFilter一个组件，点击查询时，查询按钮左边会出现一个加载loading效果。无论是返回true、false、undefined（onFinsh回调方法已标记为async）还是Promise.resolve(true)、Promise.resolve(false)、undefined（onFinsh回调方法未标记为async）等等都会出现。
解决方式：
1.将ant升级到最新
2.将@ant-design/pro-form、@ant-design/pro-layout、@ant-design/pro-table升级到最新
问题：为什么在升级前会出现两个页面，同样的代码，却一个有loading一个没有呢？
不过感谢你的回复，希望我的反馈对兼容性改进有用。

**Comment by MrArky** [comment]
> Hello @MrArky. Please provide a online reproduction by forking this link https://codesandbox.io/ or a minimal GitHub repository.
> 
> 你好 @MrArky, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

之前提这个问题，是因为我有两个页面，一个能正常运行执行查询，另一个即使完全按照官方代码进行copy，整个页面只有QueryFilter一个组件，点击查询时，查询按钮左边会出现一个加载loading效果。无论是返回true、false、undefined（onFinsh回调方法已标记为async）还是Promise.resolve(true)、Promise.resolve(false)、undefined（onFinsh回调方法未标记为async）等等都会出现。
解决方式：
1.将ant升级到最新
2.将@ant-design/pro-form、@ant-design/pro-layout、@ant-design/pro-table升级到最新
问题：为什么在升级前会出现两个页面，同样的代码，却一个有loading一个没有呢？
不过感谢你的回复，希望我的反馈对兼容性改进有用。

**Comment by MrArky** [comment]
> Hello @MrArky. Please provide a online reproduction by forking this link https://codesandbox.io/ or a minimal GitHub repository.
> 
> 你好 @MrArky, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)



> 来个重现，是因为onFinsh吗？

之前提这个问题，是因为我有两个页面，一个能正常运行执行查询，另一个即使完全按照官方代码进行copy，整个页面只有QueryFilter一个组件，点击查询时，查询按钮左边会出现一个加载loading效果。无论是返回true、false、undefined（onFinsh回调方法已标记为async）还是Promise.resolve(true)、Promise.resolve(false)、undefined（onFinsh回调方法未标记为async）等等都会出现。
解决方式：
1.将ant升级到最新
2.将@ant-design/pro-form、@ant-design/pro-layout、@ant-design/pro-table升级到最新
问题：为什么在升级前会出现两个页面，同样的代码，却一个有loading一个没有呢？
不过感谢你的回复，希望我的反馈对兼容性改进有用。
