### ISSUE TITLE
EditableProTable使用string作为id时编辑会刷出来许多列🐛[BUG]

### ISSUE THREAD

**Issue by chengqigang** [ant-design/pro-components#1826]
### 🐛 bug 描述
EditableProTable使用string作为id时，在列的输入框里输入一个字符就刷出来许多列

### 💻 复现代码
recordCreatorProps={{
          newRecordType: 'dataSource',
          record: () => ({
            id: Date.now().toString(),
          }),
        }}
这个id为String的话就会发生异常，以下链接发生的时提交的数据有问题，id和其它数据分开组成了数组
![image](https://user-images.githubusercontent.com/29392211/106578193-38e6d700-657a-11eb-90b2-f1d68badca08.png)

https://codesandbox.io/s/shishibaocundebianjibiaoge-forked-k1b8q?file=/index.tsx

我本地的异常如下
![image](https://user-images.githubusercontent.com/29392211/106577878-dc83b780-6579-11eb-92ff-3378252950e1.png)

### © 版本信息

 "@ant-design/pro-table": "2.27.2",
    "antd": "4.11.2",
    "react": "17.0.1",
    "react-dom": "17.0.1"

**Comment by chenshuai2144** [comment]
看你的报错是因为用了 index 的问题导致的

**Comment by chengqigang** [comment]
> 看你的报错是因为用了 index 的问题导致的
> 
> 你是不是没有设置 rowKey

有设置rowKey的，从官方的例子改过来的
`const EditTable = (props: EditTableProps) => {
  const [editableKeys, setEditableRowKeys] = useState<React.Key[]>([]);
  return (
    <EditableProTable
      rowKey="id"
      bordered={true}
      toolBarRender={false}
      columns={props.columns}
      recordCreatorProps={{
        newRecordType: "dataSource",
        record: () => ({
          id: Date.now().toString()
        })
      }}
      onValuesChange={(values: any[], record: any) => {
        console.log(values);
        setEditableRowKeys(values.map((e) => e.id));
      }}
      editable={{
        type: "multiple",
        editableKeys: editableKeys,
        onChange: setEditableRowKeys,
        actionRender: (row, _, dom) => {
          return [dom.delete];
        }
      }}
    />
  );
};`

**Comment by chenshuai2144** [comment]
你的 value 是什么？

**Comment by Big-Bear-2019** [comment]
请问题主，这个问题是否已经解决，我也遇到这个问题，这个问题搞的我脑壳疼，示例地址如下：
https://codesandbox.io/s/elastic-mclaren-hxrfl?file=/src/EditTable.tsx

**Comment by chengqigang** [comment]
...没有解决，暂时没搞这个，忙忘了

**Comment by mathcw** [comment]
同样遇到这个问题 rowkey的value设置为string的时候 onValuesChange收到的recordlist很奇怪

**Comment by chenshuai2144** [comment]
@mathcw  不要用 string number，要么用number，要么用string

**Comment by Big-Bear-2019** [comment]
> @mathcw 不要用 string number，要么用number，要么用string

我这边都是返回的string，前端设置的也是string，都是不行的，我写了个例子，https://codesandbox.io/s/elastic-mclaren-hxrfl?file=/src/EditTable.tsx 可否指点下你是怎么设置的？前提是要设置列表数据可控的
