### ISSUE TITLE
🐛[BUG] 发现ProTable的pagination  国际化跟antdesign的有出入 

### ISSUE THREAD

**Issue by KingDracula** [ant-design/pro-components#1831]
### 🐛 bug 描述
使用ProTable的时候取消国际化，默认使用zh-CN 发现 pageSize 列表不显示 条/页  而是 /page

发现少了items_per_page 这一项，不知道是我使用问题还是组件本身问题
脚手架创建的ant-design-pro   5.0.0-beta.2 

![image](https://user-images.githubusercontent.com/13584613/106607674-8d03b280-659e-11eb-957d-52a8273f6d9a.png)
Pro-provider 中的中文文案
![image](https://user-images.githubusercontent.com/13584613/106607748-a1e04600-659e-11eb-8b50-65dc828989d5.png)
ant-design 中的中文文案
![image](https://user-images.githubusercontent.com/13584613/106607934-d0f6b780-659e-11eb-8f9f-9c2f3f91edce.png)

**Comment by chenshuai2144** [comment]
你需要设置 一下 ConfigProvide，ProTable 会跟着 antd 的 ConfigProvide 走

**Comment by KingDracula** [comment]
我是在ant design pro 中使用的，不是使用的项目的local，还得需要单独设置吗？

**Comment by chenshuai2144** [comment]
嗯，最好开一下 locale 插件，它会自动处理，不然你还会碰到 moment 的问题
