### ISSUE TITLE
ProTable 组件高级表格Demo中，表头配置了搜索项标题为必填项，但是并没有生效🐛[BUG]

### ISSUE THREAD

**Issue by overcastsky** [ant-design/pro-components#1837]
### 🐛 bug 描述
ProTable 组件高级表格Demo中，表头配置了搜索项标题为必填项，但是并没有生效

### 📷 复现步骤
文档中的DEMO

### 🏞 期望结果
配置了必填项，查询时如果没有填写，应该给予错误提示

### 💻 复现代码
https://procomponents.ant.design/components/table       查询表格DEMO

### © 版本信息
官网DEMO

**Comment by chenshuai2144** [comment]
查询表单不推荐使用rules，搜一下历史issue。
