### ISSUE TITLE
ProTable 怎么配置 columnStateMap 的默认值？

### ISSUE THREAD

**Issue by Artoria-0x04** [ant-design/pro-components#1838]
找了半天才找到隐藏列显示是用 columnStateMap，结果这是个受控的状态？我只是要初始隐藏某些列，不想去控制他的状态，要怎么实现？

**Comment by chenshuai2144** [comment]
受控就用 onChange，两个是一对的

**Comment by zhubufang** [comment]
![image](https://user-images.githubusercontent.com/40162775/140492476-9f5da2ea-096c-4ae5-9d4b-282655c4a89c.png)
为什么修改column显示隐藏  会返回不同结构的值

**Comment by chenshuai2144** [comment]
rowkey 发生了改变了吧
