### ISSUE TITLE
🐛[BUG] proTable组件  defaultExpandAllRows无效

### ISSUE THREAD

**Issue by dmdoit** [ant-design/pro-components#184]
### 🐛 bug 描述
defaultExpandAllRows 默认展开无效

```
expandable={{
  defaultExpandAllRows: true,
  expandedRowRender
}}
```

### 🏞 期望结果

和table一样正常使用

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
必须要要在 table 渲染前才能用，还不能异步加载数据，最好用 expandedRowKeys 来做展开
