### ISSUE TITLE
最近升级 Pro 组件遇到 “Cannot read property 'Provider' of undefined” 看这里  🐛[BUG]

### ISSUE THREAD

**Issue by aweiu** [ant-design/pro-components#1844]
### 🐛 bug 描述
很多包含最新 Pro 组件的页面崩溃并报错：`Cannot read property 'Provider' of undefined`

### 📷 复现步骤

- Antd 版本 < `4.11.1`
- 使用了诸如 ProTable、ProForm 等最新版本的 Pro 组件

### 🏞 期望结果

网页正常运行不报错。2 个建议

1. 建议给所有依赖 [antd/ConfigProvider.SizeProvider](https://github.com/ant-design/ant-design/blob/master/components/config-provider/index.tsx#L223) 的组件都通过 `peerDependencies` 来表明项目依赖 Antd 的最低版本应为: `4.11.1`。或者在官网醒目位置标注一下，以免其他人再踩坑
2. 或者现有代码兼容一下老版本 Antd

### 💻 复现代码

[见此](https://codesandbox.io/s/autumn-star-0i8qi?fontsize=14&hidenavigation=1&theme=dark)

**Comment by mdddj** [comment]
同样遇到这个问题,解决了吗
![image](https://user-images.githubusercontent.com/29020213/106729913-f7712d00-6648-11eb-8752-2f3f85d06a95.png)

**Comment by aweiu** [comment]
> 同样遇到这个问题,解决了吗
> ![image](https://user-images.githubusercontent.com/29020213/106729913-f7712d00-6648-11eb-8752-2f3f85d06a95.png)

暂时可以升级 Antd 到 `4.11.1` 以上，或者锁死相关的 Pro 组件版本（昨天以前的版本应该就可以）

**Comment by chenshuai2144** [comment]
你们是怎么做到只升级pro-compentts的版本，却不升级antd 的版本的？

**Comment by aweiu** [comment]
> 你们是怎么做到只升级pro-compentts的版本，却不升级antd 的版本的？

比如 ProForm 的 [dependencies](https://github.com/ant-design/pro-components/blob/master/packages/form/package.json#L35) 里并没有指定 Antd 啊（事实上，也不应该

所以升级相关 Pro 组件为什么会升级 Antd 版本呢？

**Comment by chenshuai2144** [comment]
因为它依赖 antd ，用了 antd 的新特性。

**Comment by MoonSeeing** [comment]
> > 你们是怎么做到只升级pro-compentts的版本，却不升级antd 的版本的？
> 
> 比如 ProForm 的 [dependencies](https://github.com/ant-design/pro-components/blob/master/packages/form/package.json#L35) 里并没有指定 Antd 啊（事实上，也不应该
> 
> 所以升级相关 Pro 组件为什么会升级 Antd 版本呢？



> > 你们是怎么做到只升级pro-compentts的版本，却不升级antd 的版本的？
> 
> 比如 ProForm 的 [dependencies](https://github.com/ant-design/pro-components/blob/master/packages/form/package.json#L35) 里并没有指定 Antd 啊（事实上，也不应该
> 
> 所以升级相关 Pro 组件为什么会升级 Antd 版本呢？

peerdepencier 指定了antd ，那运行时 就会取宿主的antd 版本，如果宿主（你自己的项目）antd 版本过低，然而 该组件 升级了 依赖了antd 的 新特性你就必须也升级宿主的版本了。
