### ISSUE TITLE
🐛[BUG]EditableProTable用自定义新建按钮 实现从第一行开始添加 设置了positon 不起作用

### ISSUE THREAD

**Issue by 271915902** [ant-design/pro-components#1848]
### 💻 复现代码

 recordCreatorProps={{
          style: {
            display: 'none',
          },
          position: 'top',
        }}

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by 271915902** [comment]
actionRef.current?.addEditRecord?.({
                position:'top',
                addOrUpdate:false,
                id: Date.now(),
                state:false,
               
              });  在这里配置也不生效

**Comment by chenshuai2144** [comment]
兄弟，用 typescript 把， position 是第二个参数里面的

` actionRef?.current?.addEditRecord(record, { position, newRecordType });`

**Comment by chenshuai2144** [comment]
兄弟，用 typescript 把， position 是第二个参数里面的

` actionRef?.current?.addEditRecord(record, { position, newRecordType });`
