### ISSUE TITLE
🐛[BUG] Cannot read property 'Provider' of undefined

### ISSUE THREAD

**Issue by mdddj** [ant-design/pro-components#1849]
### 🐛 bug 描述

使用表格后提示
![image](https://user-images.githubusercontent.com/29020213/106730183-4323d680-6649-11eb-9e04-abdfa3dc75fc.png)

### 📷 复现步骤

安装最新版

### 🏞 期望结果

正常显示

### 💻 复现代码

```
    <ProTable<BlogObject> columns={BlogTableColumn} rowKey={'id'} request={async (params) => {
              const data = await getBlogList({page: 0, pageSize: params.pageSize});
              return {data: data.data.content, success: data && data.state == 200};
            }}>
    
    </ProTable>
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/issues/1844
