### ISSUE TITLE
🧐[问题]ProLayout 与 umi 配合使用有示例吗？

### ISSUE THREAD

**Issue by galleonsZcc** [ant-design/pro-components#1853]
### 🧐 问题描述

看到官方文档上在介绍ProLayout时有一段ProLayout与umi配合使用的说明，用到了MenuDataItem，但是umi config的routes配置字段与这个是不一样的，有点疑惑要怎么用，有使用示例吗？

**Comment by chenshuai2144** [comment]
https://pro.ant.design/

就是ant-design-pro 啦
