### ISSUE TITLE
🐛[BUG]可编辑表格中的实时保存的编辑表格,string类型的id,编辑出现bug

### ISSUE THREAD

**Issue by 1257960069** [ant-design/pro-components#1854]
### 🐛 bug 描述

数据的id为string类型时会出现bug,number类型无问题
### 📷 复现步骤
1.将实例代码中的defaultData中的id加上单引号,变为string类型
2.在右侧编辑框中输入类
3.即可看到错误数据的新增

### 🏞 期望结果
支持string类型的id数据,因为某些id时guid类型的string

### 💻 复现代码
![image](https://user-images.githubusercontent.com/31265244/106859294-cc94e080-66fd-11eb-86d8-9edb67bfe076.png)

https://codesandbox.io/s/omd9l
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/31265244/106859294-cc94e080-66fd-11eb-86d8-9edb67bfe076.png)

**Comment by chenshuai2144** [comment]
id 为 string，尽量用 0 开头，不然 pro 分不清楚是数字还是字符串

**Comment by 1257960069** [comment]
js肯定有办法区分是string还是number,最好源代码中检测下传入的类型,或给出设置的地方,解决这个问题.不然只能自己map一遍id.而且文档中并没指出"id 为 string，尽量用 0 开头，不然 pro 分不清楚是数字还是字符串"

**Comment by 1257960069** [comment]
![image](https://user-images.githubusercontent.com/31265244/106872219-079f1000-670e-11eb-915b-28922f763331.png)
按照你的做法,依旧有bug

**Comment by chenshuai2144** [comment]
是有办法，但是太复杂了，object 的 key 只能是 string，我每次都会转化一下，你如果要用string，就用真正的 string

**Comment by 1257960069** [comment]
![image](https://user-images.githubusercontent.com/31265244/106872865-c3f8d600-670e-11eb-8e93-5c251daa501b.png)
![image](https://user-images.githubusercontent.com/31265244/106872883-cbb87a80-670e-11eb-99b8-48d66b9e5ef5.png)
我水平较低,主要研究后端,还望大佬解决,不yuanyi,我折中了一下,取gethashcode转成数字了.虽然有概率碰撞.

**Comment by chenshuai2144** [comment]
id 一般来自后端，rowkey 直接设置为 id 就好了
