### ISSUE TITLE
🧐[问题]protable工具栏列设置的状态怎么持久化啊

### ISSUE THREAD

**Issue by walry** [ant-design/pro-components#1855]
### 🧐 问题描述

需求要把设置完哪些列可见哪些列不可见的状态保存到数据库，怎么拿到这么这些状态呢

**Comment by chenshuai2144** [comment]
columnsStateMap | columns 的状态枚举 | {key:{ show,fixed }}} | -
-- | -- | -- | --
onColumnsStateChange | columns 状态发生改变 | (props: {key:{ show,fixed }}}) => void | -


试试这个

**Comment by walry** [comment]
nice

**Comment by queuemax** [comment]
这样做完 重置就不好用了。我想在重置按钮旁加个保存按钮，有办法加上吗？

**Comment by jiangyh1024** [comment]
+1 
@queuemax   如果存到 localstorage - 点重置 会变成 localstorage存的状态

我想的重置 是 回到最初的状态

**Comment by PeakFish** [comment]
@Caladog @jiangyh1024 实现思路可以调整， 重置 按钮，回掉函数 接收到的参数是空对象{}， 可以自己清空存储状态

**Comment by PeakFish** [comment]
确实有这个情况 ， toolbar 可以在外面再加个按钮 恢复默认列设置 清空本地缓存
