### ISSUE TITLE
ProTable中 查询表单 不支持修改 查询字段的label👑 [需求]

### ISSUE THREAD

**Issue by MoonSeeing** [ant-design/pro-components#1856]
### 🥰 需求描述
在table中的查询字段需要自定义  输入框的label ,但目前只能取 columns的title字段 和table显示的标题必须一致了。

### 🧐 解决方案
看 源码 FormSearch 组件  label 是被写死了始终和 配置中的 title 一致的
```
  const getTitle = () => {
    if (rest.title && typeof rest.title === 'function') {
      return rest.title(item, 'form', '');
    }
    return rest.title;
  };
  const dom = formInputRender({
    item,
    type,
    intl,
    form: formInstance,
    label: getTitle(),
    request,
    params,
    formItemProps,
    colSize,
  });
  if (!dom) {
    return null;
  }

  return dom;
};
```

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/19420622/106873873-e17a6f80-670f-11eb-8958-f9cc6c9a9593.png)

**Comment by chenshuai2144** [comment]
title 支持 funtion 的, 你可以通过 function 来根据不同的 type 来生成不同配置。

```
   title: (_, type) => (type === 'table' ? '状态' : '列表状态'),
```

**Comment by MoonSeeing** [comment]
> title 支持 funtion 的, 你可以通过 function 来根据不同的 type 来生成不同配置。
> 
> ```
>    title: (_, type) => (type === 'table' ? '状态' : '列表状态'),
> ```

看了 下 确实可以 ，🐂🍺
