### ISSUE TITLE
有时候想参与到这个项目组件的一些优化开发 提供pr,但是却不知道采用何种方式调试代码并修改代码比较合适🧐[问题]

### ISSUE THREAD

**Issue by MoonSeeing** [ant-design/pro-components#1857]
### 🧐 问题描述
我这边比如想给table 提供新特性，我从 pro-components仓库这边已经download 一份代码 。接下来 我 找到 table 组件加了一些新的特性，直接在src中 更改了部分组件。那接下来 我 该如何测试这个组件呢，想法是 建一个小的demo 项目 ，可以直接将 table 组件 引用进来。可是 如何做比较优雅呢。是否有一个比较完整快捷的 给组件提供 pr的方式？

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/docs/intro#%E5%8F%82%E4%B8%8E%E8%B4%A1%E7%8C%AE

看看这里

**Comment by MoonSeeing** [comment]
@chenshuai2144 你意思用 src 下面的demo  测试就好？ yarn start 启动 项目？

**Comment by MoonSeeing** [comment]
> https://procomponents.ant.design/docs/intro#%E5%8F%82%E4%B8%8E%E8%B4%A1%E7%8C%AE
> 
> 看看这里，直接启动我们的官网，如果只想调试一个demo，可以点击一下demo下面的打开按钮，就只展示一个demo了

谢谢哈 可行
