### ISSUE TITLE
🐛[BUG]ProFormDependency 和ProFormSelect一起使用且ProFormSelect存在onChange时，依赖会无效

### ISSUE THREAD

**Issue by galleonsZcc** [ant-design/pro-components#1864]
### 🐛 bug 描述

同时使用ProFormSelect和ProFormDependency，且ProFormDependency依赖ProFormSelect的值，同时ProFormSelect配置fieldProps={{onChange: handleChange}}，handleChange可以捕获select的变化，但是ProFormDependency中失效。
如果使用antd Select组件则不存在该问题。

### © 版本信息

- @ant-design/pro-form@1.15.3
- umi 版本[3.3.1]
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
尽量不要这样用，性能会问题，不过我也支持了一下

close by https://github.com/ant-design/pro-components/pull/1886
