### ISSUE TITLE
👑 [需求] EditableProTable 如何让一个外部按钮触发表单的校验--(附曲线救国的方案)

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#1866]
### 🥰 需求描述

编辑表格经常需要一个外部按钮来进行检验。看这个图吧，不看图说不清楚。

> 例如下图是会员的等级，在保存时，要判断等级的经验值是从小到大排序。

![mall-member-gradle](https://user-images.githubusercontent.com/34436863/107118881-c26e1000-68be-11eb-8537-dd23f8f9f247.png)

### 🧐 解决方案

直接在EditableProTable 属性中，给一个form的ref就可以了。 

### 🚑 曲线救国的方案

在columns得到form，但是这样效率太低，因为columns的刷新次数太多。
```
formItemProps: (form, { rowIndex }) => {
    formRef.current = form;
```

然后外边Button的submit中调用formRef.validateFields，进行校验。
```
  const onSubmit = () => {
    formRef.current
      ?.validateFields()
      .then((values) => {
        // console.log(values);
      })
      .catch((errorInfo) => {
        // console.log(errorInfo);
      });
  };
```

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/107144284-23581f80-6975-11eb-9e02-6ea65c080b4c.png)


支持了一下 useForm 的配置

**Comment by itxve** [comment]
EditableProTable上的formRef 为什么不行，不给升级版本，看来只能曲线救国了。
