### ISSUE TITLE
initialValues中携带id值，但form表单没有name=id组件会导致提交表单丢失ID字段

### ISSUE THREAD

**Issue by birdycn** [ant-design/pro-components#1869]
之前用formily时，initialValues携带id字段，提交表单也会保留id字段，当然initialVaules有时候还会携带createdAt等参数导致提交表单过于冗余，除了添加一个hidden的item组件，能否考虑设置保留某些initialValues存在的字段？

initialValues 应该生效的， 隐藏 input 可是在03年开始就一直在用的超级技能，input 专门出了个hidden属性

_Originally posted by @chenshuai2144 in https://github.com/ant-design/pro-components/issues/1240#issuecomment-741815826_

**Comment by chenshuai2144** [comment]
发现是antd 干的，你试试 


preserve | 当字段被删除时保留字段值 | boolean | true | 4.4.0
-- | -- | -- | -- | --




如果不行，给antd 的form 提个issue吧

**Comment by ccloveak** [comment]
。。我当初也遇到过这种情况，还以为是自己的问题。。。在表单上面又封装了一层数据层。。这样antd就沦为了比较纯粹的展示工具
