### ISSUE TITLE
Protable 升级到2.5.7版本，设置每页显示数量的下拉菜单点击无效🐛[BUG]

### ISSUE THREAD

**Issue by yinbiao** [ant-design/pro-components#187]
### 🐛 bug 描述

点击分页栏目的“20条/页，50条/页...“的下拉按钮，没有任何效果。

### 📷 复现步骤

我初始化时的@ant-design/pro-table 这个版本是2.1.11，由于这个版本多选时有一个数据重复的BUG，因此单独升级该组件到2.5.7版本。
升级后，那个设置每页多少条的下拉按钮就失效了。失效的意思，就是点了没有任何反应。

### © 版本信息

- antd-pro 4.0.0
- umi 3.2.14
- Chrome 64.0.3282.186（
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/90140449-5c3f7f00-ddac-11ea-8018-46e34519e7b9.png)


看起来没问题
