### ISSUE TITLE
EditableProTable : How to listen to valueEnum (select type) type cell onChange ?

### ISSUE THREAD

**Issue by NisugaJ** [ant-design/pro-components#1874]
### 🧐 问题描述(Problem Description)
Hi ,
I want to update the `contract status` field of a record as mentioned in the below image. I want to listen to onChange of `select` and send a POST Request to update with the selected status with a confirmation. Thereafter I have to reload the page.

My Question is on stackoverflow: (Still no one has answered) [https://stackoverflow.com/questions/66071231/in-ant-design-editableprotable-how-to-listen-to-onchange-of-a-valueenum-type](https://stackoverflow.com/questions/66071231/in-ant-design-editableprotable-how-to-listen-to-onchange-of-a-valueenum-type)
### 💻 示例代码 (Sample code)

```
 {
      title: 'Contract Status',
      dataIndex: 'ConStatus',
      valueType: 'select',
      key: 'ConStatus',
      filters: true,
      valueEnum: {
        Pending: { text: 'Pending', status: 'Warning' },
        Completed: { text: 'Completed', status: 'Success' },
        Terminated: { text: 'Terminated', status: 'Error' },
      },
      render: (_) => <a>{_}</a>,
      onCell:
        (record: PlantationListItem, rowIndex: any) => { 
          return {
             onChange: (e: any) => {                        <------------------------------------------ not listening
              alert(JSON.stringify(record.ConStatus)); //  not working

              //send POST REQUEST 

              // Refresh page
            },
            
          };
        }
    },
```

### 🚑 其他信息 (other information)
![image](https://user-images.githubusercontent.com/44756803/107137059-cfc2e300-692e-11eb-8af4-58804e240507.png)

**Comment by chenshuai2144** [comment]
What function are you trying to achieve, this is a bit difficult to achieve

**Comment by NisugaJ** [comment]
after selecting a new status item, a PopConfirm should be shown and new status should be updated to the backend after clicking OK.

**Comment by NisugaJ** [comment]
I could achieve it using `renderFormItem` like below.

```

  const  ContractStatusSelector = ({token, value}: any) => {
    const [visible, setVisible] = useState(false);
    const[selected,setSelected] = useState(value);

    function handleChange(selectedValue: any) {
      setSelected(selectedValue);
      if(!visible) setVisible(true);
    }
    
    return (
      <Popconfirm
        key={token}
        visible={visible}
        title="Are you sure want to update this status ?"
        onConfirm={async ()=>{
            // POST request to API
            const update = await updateContractStatus(token, selected);
            if(update)
              dispatch({
                type: 'dashboardSummary/fetchSummary',
              });
        }}
        okText="Yes"
        cancelText="No"
        onCancel={() => setVisible(false)}
      >
        <Select key={`${token}ContractStatusSelector`} value={selected} defaultValue="Pending" style={{ width: 120 }} onChange={handleChange}>
          <Option value="Pending"><Badge status="warning" />Pending</Option>
          <Option value="Completed"><Badge status="success" />Completed</Option>
          <Option value="Terminated"><Badge status="error" />Terminated</Option>
        </Select>
      </Popconfirm>
    );
  };

    {
      title: 'Contract Status',
      dataIndex: 'ConStatus',
      valueType:'select',
      key: 'ConStatus',
      filters: true,
      renderFormItem: (schema, config, form) => <ContractStatusSelector  key={schema.key+form.value} token={schema.key} value={form.value} />
    },



```

**Comment by NisugaJ** [comment]
@chenshuai2144 Hi Chenshuai, however, it would be easy if we can directly do it without using customization like this. Hope you will improve this.

**Comment by NisugaJ** [comment]
@chenshuai2144  I'm still facing and issue. How can I access `row key` inside `renderFormItem` ? only` schema, config, form` are available as params.

renderFormItem: (schema, config, form) => {
        console.log(schema.params);
        
        return <ContractStatusSelector token={schema.index} value={form.value} />;
      },

**Comment by NisugaJ** [comment]
renderFormItem: (schema, config, form) => <ContractStatusSelector token={((Object.entries(form.getFieldsValue()).map((item: 
    any) => item))[schema.index]||[])[0] || schema.index} value={form.value} />,

@chenshuai2144 I Fixed it. I had to use `form.getFieldsValue()` to access `key` value of a row.

`Row key = ((Object.entries(form.getFieldsValue()).map((item: any) => item))[schema.index]||[])[0] `

**Comment by chenshuai2144** [comment]
form.getFieldsValue() is a better way, I gave you the rowkey, you can use it directly

**Comment by NisugaJ** [comment]
> form.getFieldsValue() is a better way, I gave you the rowkey, you can use it directly

Thanks a lot @chenshuai2144. Can you mention the commit?

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/107325842-6e914000-6ae5-11eb-8bda-28e4365682c2.png)


look here
