### ISSUE TITLE
👑 [需求] ProComponents源码中一些可以改进的小细节

### ISSUE THREAD

**Issue by itsuki0927** [ant-design/pro-components#1880]
### 🥰 需求描述

在研究pro-components源码的时候发现了一些可以优化的点, 所以想提出来讨论一下.

1. `ProForm`的基本使用(`demo/base.tsx`)示例上, name和嵌套name的问题, 我测试了一下用`Antd Form`也是同样的情况, 我不确定这是不是bug.
<img width="1265" alt="截屏2021-02-07 下午4 06 20" src="https://user-images.githubusercontent.com/40518195/107140794-7b842700-695f-11eb-9f17-8f603fdc7586.png">
<img width="1304" alt="7FDBB693-938C-421D-9656-88C7EBC06B36" src="https://user-images.githubusercontent.com/40518195/107140798-80e17180-695f-11eb-8dcd-a933a48d14c2.png">

2. `field/index.tsx`组件拼写错误.
![F3A9347B-5C0F-4833-BB83-8FC58FF35711](https://user-images.githubusercontent.com/40518195/107140824-cf8f0b80-695f-11eb-87af-b086ecbe52dc.png)

3. `utils/getFieldPropsOrFormItemProps` 逻辑可以复用`runFunction`.

`getFieldPropsOrFormItemProps`方法:
<img width="901" alt="截屏2021-02-07 下午7 22 29" src="https://user-images.githubusercontent.com/40518195/107145055-1ee23580-697a-11eb-9f95-0fd211093733.png">

`runFunction`方法:
<img width="1165" alt="截屏2021-02-07 下午7 30 21" src="https://user-images.githubusercontent.com/40518195/107145191-f0188f00-697a-11eb-96b0-3f646a43b39f.png">

复用了`runFunction`后的`getFieldPropsOrFormItemProps`: 
<img width="1025" alt="截屏2021-02-07 下午7 25 31" src="https://user-images.githubusercontent.com/40518195/107145104-6c5ea280-697a-11eb-9685-d62ac8cb4558.png">

**Comment by chenshuai2144** [comment]
来个pr把，提的都很合理
