### ISSUE TITLE
🐛[BUG]ProFormSelect 设置onChange 之后，校验不起作用

### ISSUE THREAD

**Issue by dong136279559** [ant-design/pro-components#1881]
### 🐛 bug 描述

<img width="629" alt="image" src="https://user-images.githubusercontent.com/20337504/107145639-04aa5680-697e-11eb-88e8-8199ae776d5a.png">

当我在ProFormSelect中使用onChange时，导致验证rules不起作用。
使用onSelect时，验证生效，但是不满足项目需要，无法实现功能。

### 🏞 期望结果

我期望使用onChange时，校验能起作用

### 💻 复现代码

{
      dataIndex: 'projectIds',
      hideInTable:true,
      hideInSearch:true,
      renderFormItem: (r, { type, defaultRender}) => {
        if (type === 'form') {
          return  <ProFormSelect
          label="项目信息"
          name="projectIds"
          mode="multiple"
          showSearch
          hasFeedback
          valueEnum={{'0':'全部','1':'张三','2':'李四'}}
          placeholder="请选择"
          rules={[{ required: true, message: '请选择'}]}
          fieldProps={{onChange:handleProjectChange,value:(projectData||[])}}
          />
        }
        return defaultRender(r);
      },
    },

最新 © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="496" alt="image" src="https://user-images.githubusercontent.com/20337504/107145772-cf523880-697e-11eb-9821-a1df38642fe0.png">

**Comment by chenshuai2144** [comment]
不要设置onChange ，会覆盖掉默认的

**Comment by dong136279559** [comment]
可是我需要用到这个功能，我应该怎么做呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 陈帅 <notifications@github.com&gt;
发送时间: 2021年2月7日 21:24
收件人: ant-design/pro-components <pro-components@noreply.github.com&gt;
抄送: dong136279559 <136279559@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ant-design/pro-components] ��[BUG]ProFormSelect 设置onChange 之后，校验不起作用 (#1881)

**Comment by chenshuai2144** [comment]
你要实现什么功能，监听 select 改变设置 别的控件吗？

ProFormDependency 是最好的办法

**Comment by dong136279559** [comment]
好的，非常感谢，感谢您的解答，这对我很有帮助



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 陈帅 <notifications@github.com&gt;
发送时间: 2021年2月7日 21:37
收件人: ant-design/pro-components <pro-components@noreply.github.com&gt;
抄送: dong136279559 <136279559@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ant-design/pro-components] ��[BUG]ProFormSelect 设置onChange 之后，校验不起作用 (#1881)
