### ISSUE TITLE
🐛[BUG] 可以编辑表格的rowKey只能为number类型，如果是string就出现数据错误

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#1883]
### 🐛 bug 描述

 可以编辑表格的rowKey只能为number类型，如果是string就出现数据错误

#### 第一步

[在官方例子上将id修改成string](https://procomponents.ant.design/components/editable-table#%E5%AE%9E%E6%97%B6%E4%BF%9D%E5%AD%98%E7%9A%84%E7%BC%96%E8%BE%91%E8%A1%A8%E6%A0%BC)

```tsx
[
  {
    "id": "624748504",
    "title": "活动名称一",
    "decs": "这个活动真好玩",
    "state": "open",
    "created_at": "2020-05-26T09:42:56Z"
  },
  {
    "id": "624691229",
    "title": "活动名称二",
    "decs": "这个活动真好玩",
    "state": "closed",
    "created_at": "2020-05-26T08:19:22Z"
  }
]

```

#### 第二步 修改表格中的任意一个数值
在onValuesChange就能看到数据错乱了

```
      editable={{
        type: 'multiple',
        editableKeys,
        onValuesChange: (record, recordList) => {
          console.log(record);
          console.log(recordList);
        },
      }}
```

### 🏞 期望结果

当rowKey为string类型时，也可以正常编辑

**Comment by chenshuai2144** [comment]
用真正的id，不要用分不清楚是number 还是 stirng 的，你给加个0， 或者加个字母

**Comment by fanhualei** [comment]
> 用真正的id，不要用分不清楚是number 还是 stirng 的，你给加个0， 或者加个字母

Java的雪花ID时Long型，在前台只能转换成String类型，因为JS的精度不够，所以在前台，用String做ID的情况还挺多的。

**Comment by fanhualei** [comment]
https://github.com/ant-design/pro-components/blob/master/packages/utils/src/useEditableArray/index.tsx

做个记录吧，当前的这个设计还是有点问题的。

export const toNumber = (recordKey: string) => {
  if (recordKey.startsWith('0')) {
    return recordKey;
  }
  return Number.isNaN((recordKey as unknown) as number) ? recordKey : Number(recordKey);
};

**Comment by fanhualei** [comment]
有些数据结构，在设计的时候，是用一个有意义的key作为主键的，这样在使用过程中，就不能用了。
组件一旦设计的复制就难以操作了。

[
{rowId: "login", value: 5}，
{rowId: "comments", value: 10}，
{rowId: "order_rate", value: 1}，
]

**Comment by chenshuai2144** [comment]
那就用number好了

**Comment by chenshuai2144** [comment]
不要用string number组件分不清楚

**Comment by fanhualei** [comment]
> 不要用string number组件分不清楚

好的，我现在还没遇到这个问题，今后遇到了再说，因为发现系统中用到的可编辑表格的情况不多。

现在为了适应高性能分布式存储，主键都使用了雪花ID，这个ID在Js会自动被转成string, 用js的number会丢失精度。 
担心这个坑。

感觉在可编辑表格中，可以用数组的index，来代替主键，看了一下proTable的代码，rowKey涉及的地方还挺多的，一改可能引起其他连锁的问题。

> 雪花ID

```
Twitter在把存储系统从MySQL迁移到Cassandra的过程中，由于Cassandra没有顺序ID生成机制，于是自己开发了一套全局唯一ID生成服务：Snowflake。优点是：高性能，低延迟；独立的应用；按时间有序。
```

**Comment by chenshuai2144** [comment]
前面加个0好了

**Comment by ZhangJiL** [comment]
你好，protable 版本是 2.27.2，老项目不让升级。可以编辑表格的 rowKey 是 string 时，在 onValuesChange 中数据错乱了，请问有什么方法解决吗。 `var toNumber = function toNumber(recordKey) {
  return Number.isNaN(recordKey) ? recordKey : Number(recordKey);
};`

**Comment by ZhangJiL** [comment]
@chenshuai2144
