### ISSUE TITLE
🧐[问题]snowpack 项目在集成pro-layout 无法运行

### ISSUE THREAD

**Issue by wlc534** [ant-design/pro-components#1885]
### 🧐 问题描述

snowpack 项目在集成pro-layout 无法运行，在集成antd 能正常运行。并且已安装对应插件
  plugins: ['@snowpack/plugin-react-refresh', '@snowpack/plugin-dotenv','snowpack-plugin-less'],

[snowpack] ! building dependencies...
[snowpack] Failed to load node_modules/@ant-design/pro-layout/es/Header.less
  Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)

### 💻 示例代码
import ProLayout, { PageContainer, SettingDrawer } from '@ant-design/pro-layout';
import defaultProps from './_defaultProps'; 

### 🚑 其他信息

[snowpack] ! building dependencies...
[snowpack] Failed to load node_modules/@ant-design/pro-layout/es/Header.less
  Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
![image](https://user-images.githubusercontent.com/26006959/107203073-ea33b400-6a35-11eb-9af8-76dfe11e1639.png)

**Comment by chenshuai2144** [comment]
配置一下 https://github.com/moonrailgun/snowpack-plugin-less/blob/master/plugin.js

它是支持的，要打开 lessinJavascript

**Comment by wlc534** [comment]
打开了 还是报错
![image](https://user-images.githubusercontent.com/26006959/107232593-8bcdfc00-6a5c-11eb-9040-f81a34f43a89.png)
