### ISSUE TITLE
🧐[问题] 怎么给protable的form加个action？

### ISSUE THREAD

**Issue by ccloveak** [ant-design/pro-components#1887]
### 🧐 问题描述 

想给protable的form加个action

### 💻 示例代码
找了一个官方的例子，应该不会受其他方面的影响。。
[例子](https://github.com/ccloveak/Components_Demo/tree/main/protable_from_issue)

### 🚑 其他信息
![IMG_7891](https://user-images.githubusercontent.com/38686314/107261295-7ec40380-6a82-11eb-8ece-b17f381279da.PNG)

1. 从[issue](https://github.com/ant-design/pro-components/issues/1438#issue-775281382)知道是加通过fieldProps加，有更具体的使用方法么。。
2. 官方有提供类似的用法么。。[目前找到的说明](https://procomponents.ant.design/components/table#%E6%90%9C%E7%B4%A2%E8%A1%A8%E5%8D%95%E8%87%AA%E5%AE%9A%E4%B9%89) 这个看了也不太会用啊。。。
3. 下了班后在鼓捣这个，头发都快薅没了，求帮助啊

**Comment by chenshuai2144** [comment]
为什么要加 action ？

**Comment by ccloveak** [comment]
> 为什么要加 action ？
@chenshuai2144 
为了把苹果手机界面的`换行`换成 `搜索 `...小项目，用response给手机做适配，没用RN。。。

**Comment by chenshuai2144** [comment]
没搞懂，换行和搜索是什么东西，来个效果图吧。

**Comment by ccloveak** [comment]
<img width="387" alt="WeChat6fe0a4430442771ca8ae3f881f97dede" src="https://user-images.githubusercontent.com/38686314/107332454-8b367380-6af7-11eb-817d-9bacce92c6b4.png">
这个输完内容后键盘上出来“搜索”字样。
<img width="488" alt="WeChat0e4a2ec682c17b1d734bdb2d93f0a625" src="https://user-images.githubusercontent.com/38686314/107332534-a43f2480-6af7-11eb-8281-983efbe9a5a4.png">
这个输完内容后键盘上出来“换行”字样。--可能跟回车是一个意思？

**Comment by chenshuai2144** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

 你说的是这个吧， 这是浏览器默认的行为，你可能要查一下的 ios的api了
