### ISSUE TITLE
🧐[问题] 如何限制Record中key的取值范围？

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#1892]
### 🧐 问题描述

如何限制Record中key的取值范围？
看在ant里面有很多这样的限制，但是不知道怎么做？

例如下面的代码，我想让key只能在：[A B C] 三个中选择 。 但是现在代码报错，必须把三个给写全了。

### 💻 示例代码

```tsx
type keys =   'A' | 'B' | 'C';
const result: Record< keys, number> = {
  A: 1,
  B: 2,
};
```

**Comment by chenshuai2144** [comment]
Record key 要求必须要存在的，因为你定义了。这个看起来只能用map 或者用一些黑科技。

`const result :{[key in keys]?:number } `

然后搞点默认值

**Comment by fanhualei** [comment]
谢谢，明白了。
