### ISSUE TITLE
🐛[BUG] EditableProTable 无法使用英文？

### ISSUE THREAD

**Issue by yilo** [ant-design/pro-components#1893]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/3793679/107461903-e9199880-6b95-11eb-9049-6d3486049401.png)

使用了 ConfigProvider 也无法替换 Button 为英文。 
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来一下你的代码吧，日本小哥看起来用的没问题

**Comment by yilo** [comment]
> 来一下你的代码吧，日本小哥看起来用的没问题
import enUSIntl from 'antd/lib/locale/en_US';
import { ConfigProvider } from 'antd';
import { ActionType, EditableProTable } from '@ant-design/pro-table';

 <ConfigProvider locale={enUSIntl}>
                <EditableProTable
                    rowKey="id"
                    actionRef={actionRef}
                    maxLength={5}
                    recordCreatorProps={false}
                    columns={props.columns}
                    request={async () => ({
                        data: props.data,
                        total: 3,
                        success: true,
                    })}
                    value={dataSource}
                    onChange={setDataSource}
                    editable={{
                        editableKeys,
                        onSave: async () => {
                            // await waitTime(2000);
                            setNewRecord({
                                id: (Math.random() * 1000000).toFixed(0),
                              });
                        },
                        onChange: setEditableRowKeys,
                        actionRender: (row, config, dom) => [dom.save, dom.cancel],
                    }}
                    pagination={{
                        showQuickJumper: true,
                      }}
                /></ConfigProvider>

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/107726869-0466de00-6d25-11eb-9eb2-fc1257ce6361.png)


是可以正常工作的

**Comment by chenshuai2144** [comment]
![Uploading image.png…]()

**Comment by chenshuai2144** [comment]
![Uploading image.png…]()

**Comment by renanwilliam** [comment]
The existing table lines it's fine to translate but for new entries It's not work if it is not translated in ant-designd/pro-components - Chinese is the fallback language in these cases

For example: https://codesandbox.io/s/pro-table-bug-forked-pob9o

Existing items are in Portuguese/English but when add item button is pressed, there's no translations and fallbacks to Chinese. I have addressed it in a pull request for pt_BR: https://github.com/ant-design/pro-components/pull/2018

I think that needs to have a way to translate it for what user wants but can't find how do it.

**Comment by renanwilliam** [comment]
I have spent some time on this subject today and found that it can be handled in editable.actionRender property.
```typescript
actionRender: (row, config) => {
    const configLocal = {...config};

    configLocal.cancelText = intl.formatMessage({
      id: 'common.protable.editable.action.cancel',
      defaultMessage: config.cancelText as string
    });
    configLocal.saveText = intl.formatMessage({
      id: 'common.protable.editable.action.save',
      defaultMessage: config.saveText as string
    });
    configLocal.deleteText = intl.formatMessage({
      id: 'common.protable.editable.action.delete',
      defaultMessage: config.deleteText as string
    });

    return defaultActionRender(row, configLocal).filter(value => {
      return value?.key !== 'delete'
    });
}
```

**Comment by JessicaFournier** [comment]
I'm starting with Ant EditableProTable and I try to translate buttons action (save, cancel, delete) when I edit a Row. I don't understand how to change default locale in fr_FR. I've also seen that in "fr_FR.js" in @ant-design/pro-provider, these buttons have no translation.

**Comment by renanwilliam** [comment]
@JessicaFournier I'm using the actionRender method on EditableProTable.editable property

**Comment by jalopez526** [comment]
> I have spent some time on this subject today and found that it can be handled in editable.actionRender property.
> 
> ```ts
> actionRender: (row, config) => {
>     const configLocal = {...config};
> 
>     configLocal.cancelText = intl.formatMessage({
>       id: 'common.protable.editable.action.cancel',
>       defaultMessage: config.cancelText as string
>     });
>     configLocal.saveText = intl.formatMessage({
>       id: 'common.protable.editable.action.save',
>       defaultMessage: config.saveText as string
>     });
>     configLocal.deleteText = intl.formatMessage({
>       id: 'common.protable.editable.action.delete',
>       defaultMessage: config.deleteText as string
>     });
> 
>     return defaultActionRender(row, configLocal).filter(value => {
>       return value?.key !== 'delete'
>     });
> }
> ```

Could you share the complete chunk of this? I haven been able to make this work. Where does the `defaultActionRender` comes from?

**Comment by renanwilliam** [comment]
@jalopez526 

```typescript
import {defaultActionRender} from "@ant-design/pro-utils/es/useEditableArray";
```

**Comment by jalopez526** [comment]
> @jalopez526
> 
> ```ts
> import {defaultActionRender} from "@ant-design/pro-utils/es/useEditableArray";
> ```

Not working for me, im getting:
```
TypeError: path.replace is not a function
```

My code:
```js
actionRender: (row, config, defaultDom) => {
          const configLocal = { ...config };
          console.log(config.cancelText)
          configLocal.cancelText = intl.getMessage({
            id: 'common.protable.editable.action.cancel',
            defaultMessage: config.cancelText
          });
          configLocal.saveText = intl.getMessage({
            id: 'common.protable.editable.action.save',
            defaultMessage: config.saveText
          });
          configLocal.deleteText = intl.getMessage({
            id: 'common.protable.editable.action.delete',
            defaultMessage: config.deleteText
          });

          return defaultActionRender(row, configLocal).filter(value => {
            return value?.key !== 'delete'
          });
        },
```
