### ISSUE TITLE
单独在项目中使用ProTable 时间筛选框默认是英文，文档也没有给出怎么设置，出现🐛[BUG]

### ISSUE THREAD

**Issue by lihaidong123** [ant-design/pro-components#1897]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://ant.design/components/config-provider-cn/#components-config-provider-demo-locale
框是antd的，用antd 的方法，并且设置好moment。
