### ISSUE TITLE
🐛[BUG]ProTable 的 cloumns 属性 valueEnum 不支持 namespace 中声明的枚举类型

### ISSUE THREAD

**Issue by lin-mt** [ant-design/pro-components#1898]
### 🐛 bug 描述

valueEnum 不支持 namespace 中声明的枚举类型

### 📷 复现步骤

在一个namespace中声明一个枚举类型，在protable的columns的valueEnum使用该枚举

### 🏞 期望结果

正常根据枚举的设置显示值

### 💻 复现代码
columns 声明该字段的枚举类型
![image](https://user-images.githubusercontent.com/58337359/107721950-de3b4100-6d18-11eb-8c65-639652e6fd01.png)
该枚举类型的定义
![image](https://user-images.githubusercontent.com/58337359/107721984-f01ce400-6d18-11eb-98de-1acee97a01fe.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 "umi": "^3.2.14"
- 浏览器环境 chrome 88.0.4324.150
- 开发环境 mac OS
- "@ant-design/pro-table": "^2.9.16"

**Comment by chenshuai2144** [comment]
d.ts 只是类型 不能放变量使用
