### ISSUE TITLE
👑 [建议] ModalForm中对Modal外层div增加禁止点击事件向上传播的建议

### ISSUE THREAD

**Issue by TerraLian** [ant-design/pro-components#1901]
### 🥰 需求描述
考虑以下场景：
- Table组件有一个右侧操作列，且设置了onRow，使得可点击行进行勾选
- 操作列有一个编辑按钮，作为ModalForm组件的trigger，点击时弹出编辑弹出框
- 此时，在弹出框中进行任意点击，都会使Table对应行被勾选/取消勾选

### 🧐 解决方案
``` js
{createPortal(
        <div onClick={(e) => e.stopPropagation()}>
          <Modal
```
该问题可以在ModalForm源码中增加点击事件禁止传播进行解决，如上。

### 🚑 其他信息
在使用时发现的问题，若有其他考量，或其他好的解决方法，则无视。

**Comment by chenshuai2144** [comment]
很好的想法。
