### ISSUE TITLE
🧐[问题] ProTable columns 的 order 属性使用问题

### ISSUE THREAD

**Issue by ChenWeihua123** [ant-design/pro-components#1902]
### 🧐 问题描述
在使用 ProTable 时 想使用 order 属性 调整 搜索表单的排列顺序，但又不想破坏 新建和更新表单的默认排列顺序
请问这种情况可以做到吗

**Comment by chenshuai2144** [comment]
现在不行 要用就要一起用了

**Comment by ChenWeihua123** [comment]
> stateMap

嗯嗯谢谢

**Comment by ChenWeihua123** [comment]
> 现在不行 要用就要一起用了
> 
> 试一试 stateMap 能暂时缓解

嗯嗯谢谢
