### ISSUE TITLE
🐛[Bug] ant design GitHub repo disappeared!!

### ISSUE THREAD

**Issue by raptoria** [ant-design/pro-components#1904]
The entire ant design repo and website are missing https://ant.design

please help, I can’t live without it

**Comment by xinghul** [comment]
Panic mode! what happened?

**Comment by Endevir** [comment]
+++
What has happened? Entire antd repo is unavailable 😭

**Comment by raptoria** [comment]
They seem to have an alternate link:
https://3x.ant.design/docs/react/introduce

more:
https://www.reddit.com/r/reactjs/comments/ljt54q/ant_design_library_gone/

**Comment by laneme** [comment]
> https://3x.ant.design/docs/react/introduce

As a side note, The alternate link is for v3, which is an older version. They also have one for x2. Whats down is the latest version, 4x. You'll find it on top right.

**Comment by yesmeck** [comment]
We are investigating the cause.

**Comment by ellioseven** [comment]
@yesmeck Any updates?

**Comment by yesmeck** [comment]
We are contacting GitHub to restore the repository.

**Comment by DavidNorena** [comment]
@yesmeck I love you buddy :)

**Comment by ParasKatwal** [comment]
They are in gitee 
https://gitee.com/ant-design/ant-design

and website 
https://ant-design.gitee.io/

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design-pro/issues/8086#issuecomment-778891249
