### ISSUE TITLE
单独在项目中使用ProTable时间选择框怎么改成中文现实🧐[问题]

### ISSUE THREAD

**Issue by lihaidong123** [ant-design/pro-components#1909]
### 💻 示例代码  我根据antd国际化配置配置成中文显示，依然没有用
```
import React, {useState} from 'react';
import {Button, ConfigProvider, Result, Avatar, Space, Statistic} from 'antd';
import {LikeOutlined, UserOutlined} from '@ant-design/icons';
import type {ProSettings} from '@ant-design/pro-layout';
import ProLayout, {PageContainer, SettingDrawer} from '@ant-design/pro-layout';
import defaultProps from './_defaultProps';
import logo from './logo.svg'
import IcbcResult from "./IcbcResult";

import zhCN from 'antd/lib/locale/zh_CN';
import moment from 'moment';
import 'moment/locale/zh-cn';


import Demo1 from "./Demo1";

moment.locale('zh-cn');
export default () => {
    const [settings, setSetting] = useState<Partial<ProSettings> | undefined>(undefined);
    const [pathname, setPathname] = useState('/demo');
    return (

        <div
            id="test-pro-layout"
            style={{
                height: '100vh',
            }}
        >
            <ProLayout
                {...defaultProps}
                location={{
                    pathname,
                }}
                fixSiderbar
                onMenuHeaderClick={(e) => console.log(e)}
                menuItemRender={(item, dom) => (
                    <a
                        onClick={() => {
                            setPathname(item.path || '/demo');
                        }}
                    >
                        {dom}
                    </a>
                )}
                // rightContentRender={() => (
                //     <div>
                //         {/*<Avatar shape="square" size="small" icon={<UserOutlined />} />*/}
                //     </div>
                // )}
                headerRender={false}
                footerRender={false}
                {...settings}
                title={'开票管理'}
                locale={'zh-CN'}
            >
                <PageContainer
                >
                    {/*<div>1111</div>*/}
                    <ConfigProvider locale={zhCN}>
                        <Demo1/>
                    </ConfigProvider>
                </PageContainer>
            </ProLayout>
            <SettingDrawer
                pathname={pathname}
                getContainer={() => document.getElementById('test-pro-layout')}
                settings={settings}
                onSettingChange={(changeSetting) => setSetting(changeSetting)}
            />
        </div>


    );
};
```

**Comment by chenshuai2144** [comment]
来个重现，感觉没什么问题

**Comment by lihaidong123** [comment]
我可以直接发代码给你吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "陈帅"<notifications@github.com&gt;; 
发送时间: 2021年2月22日(星期一) 上午10:07
收件人: "ant-design/pro-components"<pro-components@noreply.github.com&gt;; 
抄送: "京东工作邀请涵"<151268525@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/pro-components] 单独在项目中使用ProTable时间选择框怎么改成中文现实🧐[问题] (#1909)





 
来个重现，感觉没什么问题

**Comment by lihaidong123** [comment]
我可以直接给你发代码吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月22日(星期一) 上午10:07
收件人:&nbsp;"ant-design/pro-components"<pro-components@noreply.github.com&gt;;
抄送:&nbsp;"京东工作邀请涵"<151268525@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 单独在项目中使用ProTable时间选择框怎么改成中文现实🧐[问题] (#1909)





 
来个重现，感觉没什么问题

**Comment by lihaidong123** [comment]
https://github.com/lihaidong123/pay_h5.git&nbsp; 这个是我的代码地址






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月22日(星期一) 上午10:07
收件人:&nbsp;"ant-design/pro-components"<pro-components@noreply.github.com&gt;;
抄送:&nbsp;"京东工作邀请涵"<151268525@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 单独在项目中使用ProTable时间选择框怎么改成中文现实🧐[问题] (#1909)





 
Hello @lihaidong123. Please provide a online reproduction by forking this link https://codesandbox.io/ or a minimal GitHub repository.
 
你好 @lihaidong123, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 此处 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。

**Comment by lihaidong123** [comment]
这个是我的代码地址&nbsp;https://github.com/lihaidong123/pay_h5.git




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月22日(星期一) 上午10:07
收件人:&nbsp;"ant-design/pro-components"<pro-components@noreply.github.com&gt;;
抄送:&nbsp;"京东工作邀请涵"<151268525@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 单独在项目中使用ProTable时间选择框怎么改成中文现实🧐[问题] (#1909)





 
来个重现，感觉没什么问题

**Comment by chenshuai2144** [comment]
默认设置了中文你可以试试了

**Comment by chenshuai2144** [comment]
```
import moment from 'moment';
import 'moment/locale/zh-cn';
moment.locale('zh-cn');
```

一行都不能少

**Comment by hsbtr** [comment]
> ```
> import moment from 'moment';
> import 'moment/locale/zh-cn';
> moment.locale('zh-cn');
> ```
> 
> 一行都不能少

这个方案并不能解决`ProFormDateTimeRangePicker`出现中英文混合问题，即使全局配置了configProvider configProvederWrap，这个问题在pro-components官网也有体现，如果没有时间解决这个问题是否能给一些思路由其他人提pr修复这个问题

**Comment by lilililee** [comment]
@chenshuai2144 升级了最新的 pro-components 和 antd 也有问题，pro-components 官网确实也有存在这个问题，尝试设置 umi ，moment，dayjs 的多语言均不生效

"@ant-design/pro-components": "2.3.39",
"antd": "5.0.3",

![image](https://user-images.githubusercontent.com/24242242/205538222-25aef414-a9fb-4674-9782-0017e9f1f837.png)
![image](https://user-images.githubusercontent.com/24242242/205538439-dfd27ae9-b117-4c23-b297-99c11c983f5e.png)
![image](https://user-images.githubusercontent.com/24242242/205538481-824afaf3-0329-4562-a852-f6271e5916ca.png)

**Comment by lilililee** [comment]
> @chenshuai2144 升级了最新的 pro-components 和 antd 也有问题，pro-components 官网确实也有存在这个问题，尝试设置 umi ，moment，dayjs 的多语言均不生效
> 
> "@ant-design/pro-components": "2.3.39", "antd": "5.0.3",
> 
> ![image](https://user-images.githubusercontent.com/24242242/205538222-25aef414-a9fb-4674-9782-0017e9f1f837.png) ![image](https://user-images.githubusercontent.com/24242242/205538439-dfd27ae9-b117-4c23-b297-99c11c983f5e.png) ![image](https://user-images.githubusercontent.com/24242242/205538481-824afaf3-0329-4562-a852-f6271e5916ca.png)


2022-15-05 更新：
增加 import 'dayjs/locale/zh-cn'  可解决，猜测原因是 umi 的多语言设置依旧是设置的 moment 的

![image](https://user-images.githubusercontent.com/24242242/205541279-18031123-fc32-4ff5-b129-74ad00727941.png)
![image](https://user-images.githubusercontent.com/24242242/205541480-0a59b4b2-8661-44a2-a167-be5ab78892ad.png)
