### ISSUE TITLE
ProTable搜索表单条件改变自动触发查询 查询和重置按钮支持隐藏和开启👑 [需求]

### ISSUE THREAD

**Issue by xusheng960119** [ant-design/pro-components#191]

**Comment by chenshuai2144** [comment]
> ProTable搜索表单条件改变自动触发查询 

这个不会支持的，我们还是期望宜提交为主，不过你可以设置 filedValueChange ，然后调用 formRef.submit 去更新

> 查询和重置按钮支持隐藏和开启

现在已经支持可以使用了 


optionRender | 操作栏的 render | (( searchConfig: Omit<SearchConfig, 'optionRender'>, props: Omit<FormOptionProps, 'searchConfig'>, ) => React.ReactNode) \\| false; | -
-- | -- | -- | --

**Comment by cloudsnet** [comment]
这个我也想实现，不知道 @DejaVu-Xu 解决了吗

**Comment by littlepoolshark** [comment]
@chenshuai2144 , 为什么不考虑支持呢？是因为你们要坚守这个场景下的交互设计理念吗？其实，我也赞同「还是期望以提交为主」这种交互设计的理念。但是极端情况，开发者需要这个功能 。既然你的用户（开发者）有这种需求（添加一个「一键开启自动搜索」的开关），为什么不能满足呢？如果你们觉得这与你们交互设计理念是冲突的，你作个文字说明，不建议开发滥用，不就行了吗?

**Comment by chenshuai2144** [comment]
因为自己能实现，而且我们不推荐这个用法，所以不会做成默认
