### ISSUE TITLE
🧐[问题]如何设置复杂表头？

### ISSUE THREAD

**Issue by liuht777** [ant-design/pro-components#1915]
### 🧐 问题描述
如何设置复杂表头，文档中没有涉及到

### 🚑 其他信息

![1613617953(1)](https://user-images.githubusercontent.com/16394462/108299889-42a74600-71da-11eb-8b0e-33b489ca24c5.jpg)

**Comment by chenshuai2144** [comment]
看一下 antd 的

https://ant.design/components/table-cn/

**Comment by liuht777** [comment]
> 看一下 antd 的
> 
> https://ant.design/components/table-cn/

意思就是用antd的? 用不了重型table了?

**Comment by chenshuai2144** [comment]
ProTable 是 antd 的皮肤，两个是一样的。
