### ISSUE TITLE
🧐[问题]Protable中renderFormItem自定义异步数据时，初始化时应该怎么设置查询默认值

### ISSUE THREAD

**Issue by fatesq** [ant-design/pro-components#1917]
### 🧐 问题描述

例如自定义了一个select，异步获取了选项。
初始化表格时，如何在获取选项后默认设置第一个值进行搜索。

**Comment by chenshuai2144** [comment]
自定义一下select 的组件，renderFormItem 给了一个 form，你可以在值设置完成之后调用 form.submit
