### ISSUE TITLE
👑 [需求]ProFormFieldSet可以支持namepath吗

### ISSUE THREAD

**Issue by fatesq** [ant-design/pro-components#1918]
### 🥰 需求描述

ProFormFieldSet可以支持namepath吗
现在有一组表单 ['user', 'A'] ['user', 'B'] ['user', 'C']
其中['user', 'B']想使用ProFormFieldSet做拆解,但是发现会变成{B， user: {A, C}}
如何变成{user: {A, b1, b2,C}}

**Comment by chenshuai2144** [comment]
ProFormFieldSet 是支持 namepath 的，你是怎么用的？
