### ISSUE TITLE
🐛[BUG] dateFormatter 无效

### ISSUE THREAD

**Issue by yaoguoba** [ant-design/pro-components#192]
### 🐛 bug 描述

dateFormatter 默认无效，指定为String，依然无效
查询时，dateRange的类型都是moment

### © 版本信息

- ProComponents 版本: 2.5.7+
- umi 版本: 3.2.14
- 浏览器环境: edge

**Comment by blinkMyEyesConsciously** [comment]
之前  是默认制定String的  我不知道哪个版本将这个bug  修复了  导致现在所有表格的时间查询都不能用了

**Comment by yaoguoba** [comment]
> 之前 是默认制定String的 我不知道哪个版本将这个bug 修复了 导致现在所有表格的时间查询都不能用了

默认就是String，不是bug，2.5.7开始这个默认值失效了

**Comment by chenshuai2144** [comment]
重写了一下这个问题解掉了。判断过于负责，也没有加测试，现在都加上了

**Comment by yaoguoba** [comment]
working fine!

**Comment by xoptimal** [comment]
@chenshuai2144   更新到最新的 pro-form 1.7.4 , 该问题依然无效, 返回的是 moment对象, 而不是字符串, 需要配置啥吗, 不是默认返回 string 吗
