### ISSUE TITLE
🐛[BUG] pro-table偶发性不发起请求

### ISSUE THREAD

**Issue by ouzhou** [ant-design/pro-components#1921]
### 🐛 bug 描述

在频繁切换页面的情况下，pro-table会偶发性不发起请求，并一直保持在loading状态，且不会有任何报错

### 📷 复现步骤
复现仓库
https://github.com/ouzhou/bug-report

操作流程
启动后 频繁点击左侧的按钮切换页面

### 💻 复现代码

复现仓库
https://github.com/ouzhou/bug-report

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by ouzhou** [comment]
@chenshuai2144

**Comment by wuyf123** [comment]
遇到同样的bug, 请问有解决方案吗？
