### ISSUE TITLE
🧐[问题]左下角的收缩按钮怎么默认展示出来的，

### ISSUE THREAD

**Issue by ParkerTzh** [ant-design/pro-components#1925]
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/42679837/108595708-56aa9d80-73bc-11eb-9089-08ac66825b1a.png)

**Comment by ParkerTzh** [comment]
<ProLayout
      siderWidth={220}
      disableContentMargin
      logo={logo}
      onCollapse={handleMenuCollapse}
      headerRender={false}
   
      menuItemRender={(menuItemProps, defaultDom) => {
        if (menuItemProps.isUrl) {
          return defaultDom;
        }

        return <Link to={menuItemProps.path}>{defaultDom}</Link>;
      }}
      breadcrumbRender={(routers = []) => [
        {
          path: '/',
          breadcrumbName: formatMessage({
            id: 'menu.home',
            defaultMessage: 'Home',
          }),
        },
        ...routers,
      ]}
      itemRender={(route, params, routes, paths) => {
        const first = routes.indexOf(route) === 0;
        return first ? (
          <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
        ) : (
          <span>{route.breadcrumbName}</span>
        );
      }}
      footerRender={footerRender}
      menuDataRender={menuDataRender}
      formatMessage={formatMessage}
      {...props}
      {...settings}
    >
      <Authorized
        authority={authorized.path}
        noMatch={<NoAuthPage applyUrl={(authInfo && authInfo.applyUrl) || ''} />}
      >
        <div
          style={{
            padding: 24,
            height: 'calc(100vh - 108px)',
            overflowY: 'auto',
            paddingTop: 10,
            paddingBottom: 0,
          }}
        >
          {children}
        </div>
      </Authorized>
    </ProLayout>

**Comment by ParkerTzh** [comment]
<ProLayout
      siderWidth={220}
      disableContentMargin
      logo={logo}
      onCollapse={handleMenuCollapse}
      headerRender={false}
      // postMenuData={(menuData) => {
      //   return [
      //     {
      //       icon: props.collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />,
      //       name: ' ',
      //       onTitleClick: () => handleMenuCollapse,
      //     },
      //     ...(menuData || []),
      //   ];
      // }}
      menuItemRender={(menuItemProps, defaultDom) => {
        if (menuItemProps.isUrl) {
          return defaultDom;
        }

        return <Link to={menuItemProps.path}>{defaultDom}</Link>;
      }}
      breadcrumbRender={(routers = []) => [
        {
          path: '/',
          breadcrumbName: formatMessage({
            id: 'menu.home',
            defaultMessage: 'Home',
          }),
        },
        ...routers,
      ]}
      itemRender={(route, params, routes, paths) => {
        const first = routes.indexOf(route) === 0;
        return first ? (
          <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
        ) : (
          <span>{route.breadcrumbName}</span>
        );
      }}
      footerRender={footerRender}
      menuDataRender={menuDataRender}
      formatMessage={formatMessage}
      {...props}
      {...settings}
    >
      <Authorized
        authority={authorized.path}
        noMatch={<NoAuthPage applyUrl={(authInfo && authInfo.applyUrl) || ''} />}
      >
        <div
          style={{
            padding: 24,
            height: 'calc(100vh - 108px)',
            overflowY: 'auto',
            paddingTop: 10,
            paddingBottom: 0,
          }}
        >
          {children}
        </div>
      </Authorized>
    </ProLayout>

**Comment by chenshuai2144** [comment]
默认就是展示的， 你是希望删掉它吗？

**Comment by ParkerTzh** [comment]
现在就是没有展示出来，如果headerRender显示，那么收缩按钮会显示到headerRender里，headerRender=false，菜单左下也没有显示， 如果默认是展示的，我希望删掉它，是哪个参数呢？ @chenshuai2144

**Comment by ParkerTzh** [comment]
没有设置collapsedButtonRender={false}， 左下没有收缩按钮

**Comment by chenshuai2144** [comment]
来个重现吧，这个按钮总是在的

**Comment by ParkerTzh** [comment]
版本升级：
"@ant-design/pro-layout": "^5.0.19" => "@ant-design/pro-layout": "^6.14.2",
"antd": "^4.2.3" => "antd": "^4.6.4",
如果antd4.2.3会报错Uncaught TypeError: Cannot read property '_context' of undefined
升级版本才默认显示，已解决，谢谢 @chenshuai2144
