### ISSUE TITLE
请问dateTimeRange如何去掉秒选择?  format无效

### ISSUE THREAD

**Issue by laolaolulu** [ant-design/pro-components#1927]
![微信截图_20210221144107](https://user-images.githubusercontent.com/33310261/108617733-a6887380-7453-11eb-9abe-b7c4e1d17179.png)

**Comment by chenshuai2144** [comment]
为什么不用 dateRanger？

**Comment by cc7gs** [comment]
你的format已经不符合预期内置的[valueType](https://procomponents.ant.design/components/table#valuetype-%E5%80%BC%E7%B1%BB%E5%9E%8B)了，通过自定义render吧

**Comment by laolaolulu** [comment]
> 为什么不用 dateRanger？

因为我需要选择小时部分,不需要分钟与秒

**Comment by chenshuai2144** [comment]
filedProps 里自定义 formart
