### ISSUE TITLE
🐛[BUG]拷贝设置到defaultSettings.js中后，内容区域部分的配置没有生效

### ISSUE THREAD

**Issue by zzhlife** [ant-design/pro-components#1928]
### 🐛 bug 描述

开发模式下，在页面中修改内容区域**关闭**展示顶栏、页脚、菜单和菜单头这几个选项的配置后，拷贝配置到defaultSettings.js中更新，重启后刷新页面，之前的配置没有生效。再次打开右侧的配置抽屉，这几个选项被默认为true（URL中能看到相关字段的值为false）。

### © 版本信息

- "@ant-design/pro-layout": "^6.9.0",
- 浏览器环境 Google Chrome 87.0.4280.141（正式版本） （64 位）
- 开发环境 windows

### 🚑 初步定位

1.通过断点setting.js中的changeSetting方法，发现首次调用时传入的state正确无误，修改右侧抽屉中配置时，state中的内容，包含Render字段的值被置为了undefined；
2.而后断点BasicLayout.jsx中组件SettingDrawer的onSettingChange回调方法发现，页面加载时这个回调就会被触发一次，而且传入的settings参数就是如上面所说，包含Render字段的值都是undefined，这个回调注释后功能就如预期了。初步判断这个是组件本身的BUG导致的问题；
3.翻看源码，先查看本地包中的代码，找到了怀疑的对象，如下图
![image](https://user-images.githubusercontent.com/5916125/108627244-7363d580-748f-11eb-9919-fce0c5cdb85b.png)
在initState方法中，对于带Render的字段有特殊判断，若为字符串的false，则转为boolean类型的false，但是问题在于，在方法的入参中，已经由getParamsFromUrl方法将路由参数中的字符串true/false转为了布尔值，也就会导致上面的判断失效，从而导致带Render的字段被置为了undefined，从表现上来看与BUG是相符的。
4.最后查看了一下github上pro-layout组件6.9.7版本以及6.14.0版本，发现貌似这个问题还是存在的
而在最新的6.14.1版本的一个test: add more test (#1900) 提交中对之前这部分代码都做了修改，但是这次删除了getParamsFromUrl中字符串类型转布尔类型的代码，又删除了initState方法中带Render字段的转换，这么一想是不是负负得正了(手动滑稽)。这样修改之后，onSettingChange传递出去的settings中，带Render的字段值可能会是字符串类型的true/false，依旧不能如预期那样。。。（关于最新的6.14.1版本仅为推测，没有对实际代码进行测试）

**Comment by chenshuai2144** [comment]
发布了，可以试试了

**Comment by zzhlife** [comment]
> 发布了，可以试试了

试了一下，6.14.0版本的包中仍存在这个问题，替换为最新的6.14.2后问题被修复
