### ISSUE TITLE
🐛[BUG] 选择合同生效时间后，合同名称变为 [object Object]

### ISSUE THREAD

**Issue by afc163** [ant-design/pro-components#1929]
https://procomponents.ant.design/components/form

<img width="1062" alt="图片" src="https://user-images.githubusercontent.com/507615/108628342-59c58c80-7495-11eb-98c9-64b6a2b664ad.png">

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/1882
