### ISSUE TITLE
2.4.1升级到2.4.2以上，valueEnum的过滤就没有了🐛[BUG]

### ISSUE THREAD

**Issue by meyerlee** [ant-design/pro-components#193]
### 🚑 其他信息

![comp](https://user-images.githubusercontent.com/8414971/90210714-5041d480-de21-11ea-94bc-ca90a45a61de.png)

**Comment by chenshuai2144** [comment]
默认给关掉了，用户觉得配置了  valueEnum 就出有点丑，你可以设置 filters=true 打开

**Comment by meyerlee** [comment]
ok , 使用filters=true确实可以打开过滤了，但是刚试了一下2.5.8的过滤失效了。2.4.2可以过滤
renderText 中的入参也不一样了，又需要做什么设置吗？
renderText = (text: any) => {
  console.debug('renderText', text);
  return text;        
};

![image](https://user-images.githubusercontent.com/8414971/90221264-7b85ed00-de3c-11ea-9a33-7516a043f1bb.png)
