### ISSUE TITLE
🐛[BUG]ProForm表单initialValues属性设置动态数据无法回显

### ISSUE THREAD

**Issue by yi-boide** [ant-design/pro-components#1931]
### 🐛 bug 描述

ProForm表单initialValues属性设置动态数据无法回显

![image](https://user-images.githubusercontent.com/63292605/108602980-34c31200-73e0-11eb-9bcb-6644f0555866.png)

![image](https://user-images.githubusercontent.com/63292605/108602767-c467c100-73de-11eb-8b44-ff25c613ef4c.png)

![image](https://user-images.githubusercontent.com/63292605/108602817-23c5d100-73df-11eb-921d-e9c24a45d3dd.png)

上面的输出是获取到了值的
奇怪的是不会回显到页面上面去，我将值写死放在initialValues里面是能够回显出来的

**Comment by chenshuai2144** [comment]
initialValues 不支持动态

initial 是初始化的意思，你加载回来数据之前不要渲染ProForm，回来了在渲染就可以让第一次渲染就有值了

**Comment by kmoon216kmoon** [comment]
> initialValues 不支持动态
> 
> initial 是初始化的意思，你加载回来数据之前不要渲染ProForm，回来了在渲染就可以让第一次渲染就有值了

怎么让proform回来了再渲染

**Comment by yi-boide** [comment]
> 怎么让proform回来了再渲染
加个判断就可以了
`
{formVal?.title &&  <ProForm></ProForm>}
`
或者给proform加一个key每次请求更改key的值
`
<ProForm key={key}></ProForm>
`
