### ISSUE TITLE
👑 [需求]ProLayout  增加菜单之间的分隔

### ISSUE THREAD

**Issue by k983551019** [ant-design/pro-components#1932]
### 🥰 需求描述
ProLayout  增加菜单之间的分隔
设计 设计了一个在菜单中间的分隔效果，
能不能增加个api在指定菜单下添加一个渲染区域

### 🚑 其他信息
![QQ截图20210222105145](https://user-images.githubusercontent.com/48147837/108651372-937dae00-74fc-11eb-9298-647bcaecb348.png)

**Comment by chenshuai2144** [comment]
看起来有点丑，不过应该是可以支持的

**Comment by chenshuai2144** [comment]
可以使用分组模式来使用这个能力了
