### ISSUE TITLE
👑 [需求] 移除*.less中的@import ~ 前置符号，兼容ESM构建工具

### ISSUE THREAD

**Issue by tianxing0923** [ant-design/pro-components#1933]
### 🥰 需求描述

移除*.less中的@import <code>~</code>前置符号，兼容ESM构建工具，例如：Vite

### 🧐 解决方案

less-loader 现在也推荐移除 <code>~</code> 符号
https://github.com/webpack-contrib/less-loader#imports

**Comment by chenshuai2144** [comment]
来个pr支持一下？

**Comment by wlc534** [comment]
在snowpack项目中也是无法运行， https://github.com/ant-design/pro-components/issues/1885

**Comment by theprimone** [comment]
还没搞定？

**Comment by theprimone** [comment]
暂时通过这个方式解决：https://github.com/vitejs/vite/issues/2185#issuecomment-784637827 \_(:3J∠)\_

**Comment by chenshuai2144** [comment]
要 umi 提个 pr，我一直没空搞

**Comment by theprimone** [comment]
> 要 umi 提个 pr，我一直没空搞

这是什么意思？跟 umi 有什么关系吗？:joy:

**Comment by chenshuai2144** [comment]
我们项目使用 umi做脚手架的，改了之后我们的项目就跑不起来

**Comment by theprimone** [comment]
> 我们项目使用 umi做脚手架的，改了之后我们的项目就跑不起来

这样啊，那我觉得 vite 用我楼上的临时方案也挺好的。umi 要做这个支持改动大吗？不太了解这一块。

**Comment by chenshuai2144** [comment]
不大，增加个预设就行了，兼容原来的

**Comment by chenshuai2144** [comment]
```
module.exports = {
  module: {
    rules: [
      {
        test: /\.less$/i,
        use: [
          {
            loader: "style-loader",
          },
          {
            loader: "css-loader",
          },
          {
            loader: "less-loader",
            options: {
              lessOptions: {
                paths: [path.resolve(__dirname, "node_modules")],
              },
            },
          },
        ],
      },
    ],
  },
};
```

这行加进去，你有兴趣可以试试

**Comment by theprimone** [comment]
好像在这里 https://github.com/umijs/umi/blob/master/packages/bundler-webpack/src/getConfig/css.ts#L173 修改就行了，有时间的话争取本周搞定。

> [less-options-include-paths](http://lesscss.org/usage/#less-options-include-paths)

**Comment by theprimone** [comment]
@chenshuai2144 大佬看看这样处理对吗？这个没有测试用例

**Comment by chenshuai2144** [comment]
link 到 项目中试试呢？

pro 项目就是用来做这种测试的

**Comment by theprimone** [comment]
@chenshuai2144 好像问题挺大的，先在本地 link 试了一下，解析失败。重新研究了相关文档，最后看了 less-loader 的 [release](https://github.com/webpack-contrib/less-loader/releases/tag/v8.0.0) 发现了问题：

> ⚠ BREAKING CHANGES
> minimum supported webpack version is 5

如果按照 release 的说法的话，`less-loader@8.x` 配合 `webpack@5.x` 的话，应该是啥都不用改的 :joy: 那现在 umi 还兼容 `webpack@4.x`，考虑到大量的遗留代码的话，这个问题好像不太好搞。

至于像 Vite 之类的构建工具的话，短期来看可能还是上面提到的通过 alias 的方式更有效：

```ts
export default defineConfig({
  // ...
  resolve: {
    alias: [
      { find: /^~/, replacement: '' }
    ],
  }
});
```

**Comment by chenshuai2144** [comment]
这个看来还需要一段时间才能实现

**Comment by Justinidlerz** [comment]
The `less-transformer` of the Parcel v2 has the same problem.
And that will throw an error see like:
```
@parcel/transformer-less: The @import path "~antd/es/style/themes/index.less" is using webpack specific syntax, which isn't supported by Parcel.

To @import files from node_modules, use "antd/es/style/themes/index.less"
```

Actually, the import is coming from this library, I cannot modify the import path directly.

Do we have some news on the issue?

**Comment by yunsii** [comment]
> 已经告别了 less了，现在可以很简单的使用了

看起来 pro-components 也重构成 cssinjs 了，那服务端渲染是不是要做特殊处理才行？

**Comment by wzlwangzhilin** [comment]
> 我们的项目用umi做脚手架的，改了之后我们的项目就跑不起来

这个有解决吗？
