### ISSUE TITLE
👑 [需求] ProTable 是否可以给下value字段，允许操作 dataSource

### ISSUE THREAD

**Issue by lifegit** [ant-design/pro-components#1935]
### 🥰 需求描述

ProTable 为什么不给value字段呢？
1. 当需要本地对dataSource进行修改时（例图：状态：启用/禁用、删除 等等）只能向后台修改了数据后再ref.current.action.reload()，但是重新请求接口刷新后会导致该条数据在表格中位置变动啊，给人感觉像是丢失了，并且也会出现一个loading，体验不好。

2. 因为表格中的字段很多，上述方案采用 ref.current.startEditable(rowKey); 没法解决我的需求（体验不好，会非常臃肿）。所以想自己实现：编辑（跳转新界面）、修改状态（向后台发送请求后，修改本地dataSource）、删除（向后台发送请求后，dataSource删除key），但是现在没有value，没法操作 dataSource

3. ProTable 在设计时，考虑到了增加 [procomponents](https://procomponents.ant.design/components/table#recordcreator) ，但是修改与删除应该考虑下（最好还是开放dataSource）。

### 解决方案
就像是EditableProTable给了value多好呀！

![image](https://user-images.githubusercontent.com/33006878/108662767-f9bcfd80-7509-11eb-8d0f-4b973622b887.png)

**Comment by lifegit** [comment]
ProTable 真的非常舒适，现在也非常影响业务（可能ProTable用不了了）。开发组同学们，看到这个问题，我们可以商量一下吗？真的很希望你们能帮助我！谢谢

**Comment by lifegit** [comment]
ProTable 真的非常舒适，现在也非常影响业务（可能ProTable用不了了）。开发组同学们，看到这个问题，我们可以商量一下吗？真的很希望你们能帮助我！谢谢

**Comment by chenshuai2144** [comment]
写标题

**Comment by lifegit** [comment]
不好意思。粗心了。

**Comment by lifegit** [comment]
这个 issues 状态还修改到open吗？

**Comment by chenshuai2144** [comment]
onChange 里面就有value了吧，而且还是受控的

**Comment by luna825** [comment]
@lifegit 能不能请教下你这个需求实现了么，怎么实现的？

**Comment by lifegit** [comment]
@ChenCheng220，请教一下哪个地方的onChange？

**Comment by lifegit** [comment]
> @lifegit能不能请教下你这个需求实现了么，怎么实现的？

没有实现呢，现在临时使用 ref.current.action.reload（）。如果你有好方法，可以告诉我一下吗？

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/109470990-15e11180-7aab-11eb-9ad5-d6caaf0d22ca.png)

```tsx
<EditableProTable<DataSourceType>
  headerTitle="可编辑表格"
  rowKey="id"
  value={dataSource}
  onChange={setDataSource}
  columns={columns}
/>;
```

**Comment by lifegit** [comment]
_可编辑表格 EditableProTable 与 ProTable 的功能基本相同，为了方便使用 EditableProTable 增加了一些预设，关掉了查询表单和操作栏，同时修改了 value 和 onChange 使其可以方便的继承到 antd 的 Form 中。_

EditableProTable 没有查询表单功能呀！

**Comment by chenshuai2144** [comment]
可以打开的

**Comment by chenyu1990** [comment]
> 可以打开的

请问如何打开？

**Comment by chenyu1990** [comment]
> _可编辑表格 EditableProTable 与 ProTable 的功能基本相同，为了方便使用 EditableProTable 增加了一些预设，关掉了查询表单和操作栏，同时修改了 value 和 onChange 使其可以方便的继承到 antd 的 Form 中。_
> 
> EditableProTable 没有查询表单功能呀！

你好，请问你这个问题解决了吗？

**Comment by AlanKnightly** [comment]
> > @lifegit能不能请教下你这个需求实现了么，怎么实现的？
> 
> 没有实现呢，现在临时使用 ref.current.action.reload（）。如果你有好方法，可以告诉我一下吗？

@lifegit 谢谢老哥！遇到类似的场景，才发现portable无法直接改request方法返回的数据，你这个启发了我，可以自己包裹一下ref.current.action.reload（），1-按需要触发实际请求，2-缓存上一次的结果，再merge要更新的数据，再传给table。现在知道怎么解决了～～

**Comment by lifegit** [comment]
> > > @lifegit能不能请教下你这个需求实现了么，怎么实现的？
> > 
> > 
> > 没有实现呢，现在临时使用 ref.current.action.reload（）。如果你有好方法，可以告诉我一下吗？
> 
> @lifegit 谢谢老哥！遇到类似的场景，才发现portable无法直接改request方法返回的数据，你这个启发了我，可以自己包裹一下ref.current.action.reload（），1-按需要触发实际请求，2-缓存上一次的结果，再merge要更新的数据，再传给table。现在知道怎么解决了～～

request 方法后面 .then 是不是可以解决问题？
