### ISSUE TITLE
🧐[问题]AutoCompelete配合ProForm.Item 和ProForm.Group不会自动调整宽度

### ISSUE THREAD

**Issue by birdycn** [ant-design/pro-components#1936]
```
 <ProForm.Group>
       <ProFormText />
       <ProForm.Item>
         <AutoComplete />
        </ProForm.Item>
 </ProForm.Group>
```

AutoComplete 不会自动调整宽度，需要手动设置，请问proForm的宽度设置是怎么样的，我现在是按F12对比其他组件然后手动设置style width = =

**Comment by chenshuai2144** [comment]
是人肉写死上去的，你的方法是对的。


在某些场景下，我们需要根据页面展示效果对输入框进行自适应处理，除此以外一个表单区域应默认使用定宽规则。

width info

XS=104px 适用于短数字、短文本或选项。
SM=216px 适用于较短字段录入、如姓名、电话、ID 等。
MD=328px 标准宽度，适用于大部分字段长度。
LG=440px 适用于较长字段录入，如长网址、标签组、文件路径等。
XL=552px 适用于长文本录入，如长链接、描述、备注等，通常搭配自适应多行输入框或定高文本域使用。
