### ISSUE TITLE
👑 [需求]prolayout右侧内容不能多tabs就不能支持下吗？

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-components#1938]
### 🥰 需求描述

 prolayout如何支持多tabs

### 🧐 解决方案

增加一个参数，tab = true | false
### 🚑 其他信息
 无

**Comment by chenshuai2144** [comment]
这个做起来很麻烦还有性能问题，去隔壁ant design pro 看看issue，有很多讨论也有不少方案了

**Comment by xgj1988** [comment]
@chenshuai2144  现在新的antd pro 用的是 pro-layout，根本没办法改，，你说的以前那种，我们自己都撸了一套出来。。

**Comment by Jeijie** [comment]
+1

**Comment by chenshuai2144** [comment]
老问题了 不要总是开新的
