### ISSUE TITLE
🧐[问题] How to configure the collapse button(Text and Icon) in the QueryFilter component

### ISSUE THREAD

**Issue by vembarrajan** [ant-design/pro-components#1940]
### 🧐 问题描述

Thanks for the library. 

I'm trying to customize the QueryFilter component. I want to change the collapse button text and icon. Can some one help me with how to customize the collapse button ?

### 💻 示例代码

`<QueryFilter
        defaultCollapsed
        layout="vertical"
        onFinish={async (values) => console.log(values)}
        submitter={{
          searchConfig: {
            resetText: 'Reset',
            submitText: 'Confirm'
          }
        }}
      >
        <ProFormText name="name" label="Name" />
        <ProFormDatePicker name="createDate" label="createDate" />
        <ProFormText name="status" label="createDate" />
        <ProFormDatePicker name="replyDate" label="createDate" />
        <ProFormDatePicker name="enddate" label="createDate" />
      </QueryFilter>`

![image](https://user-images.githubusercontent.com/13500667/108680964-85d42280-7514-11eb-8848-96aa2830951a.png)

**Comment by chenshuai2144** [comment]
like here
```tsx
 submitter={{
          resetButtonProps: {
            icon: '',
          },
          submitButtonProps: {
            icon: '',
          },
}}
```

**Comment by vembarrajan** [comment]
@chenshuai2144 Thanks for your response. 
Can you share the props to customize the collapse button ?. I have marked in the below image.  

![image](https://user-images.githubusercontent.com/13500667/108684086-69d28000-7518-11eb-9013-501e97174810.png)

**Comment by chenshuai2144** [comment]
you can use `collapseRender`

`<QueryFilter   collapseRender={(collapse)=> collapse?"打开":"关闭"} />`

**Comment by vembarrajan** [comment]
Thanks, @chenshuai2144  It worked.
