### ISSUE TITLE
希望支持列设置的自定义👑 [需求]

### ISSUE THREAD

**Issue by jockey100332** [ant-design/pro-components#1945]
### 🥰 需求描述
部分表格的列不希望一次性全部展现出来,只展示部分关键列数据.

其他非关键数据则在列设置中显示,当勾选时在进行进行展示数据

**Comment by chenshuai2144** [comment]
columnsStateMap | columns 的状态枚举 | {key:{ show,fixed }}} | -
-- | -- | -- | --
onColumnsStateChange | columns 状态发生改变 | (props: {key:{ show,fixed }}}) => void | -



https://procomponents.ant.design/components/table#%E5%8F%97%E6%8E%A7%E7%9A%84%E8%A1%A8%E6%A0%BC%E8%AE%BE%E7%BD%AE%E6%A0%8F

看看这里
