### ISSUE TITLE
🧐[问题]pro-layout 6.14.0 导致 地址栏有问题把defaultSetting的参数全部带进来了

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-components#1948]
### 🧐 问题描述
pro-layout 最新版本地址栏有问题把defaultSetting的参数全部带进来了 ，版本是：@ant-design/pro-layout": "6.14.0",

### 💻 示例代码

具体可能下图
### 🚑 其他信息
具体可能下图

![image](https://user-images.githubusercontent.com/8272614/108711136-e46ac200-754f-11eb-8bb5-050c99397b34.png)

**Comment by xgj1988** [comment]
@chenshuai2144  更新到6.14.3，还是没解决这个问题

**Comment by chenshuai2144** [comment]
来个重现试试，是不是修改了很多默认值？

**Comment by xgj1988** [comment]
@chenshuai2144  我的配置如下
```
export default {
  navTheme: 'dark',
  // 拂晓蓝
  primaryColor: '#1890ff',
  layout: 'sidemenu',
  contentWidth: 'Fluid',
  fixedHeader: false,
  autoHideHeader: false,
  fixSiderbar: false,
  colorWeak: false,
  menu: {
    locale: false,
  },
  title: '富贵账本系统',
  pwa: false,
  iconfontUrl: '',
  // siderWidth: 420,
  projectName: '富贵账本系统',
  projectSubTitle: '富贵账本系统',
  sideMenuName: '富贵账本系统', // 最多7个中文
  supportGeetest: false,
  copyrightLink: 'https://www.baidu..com',
  copyrightName: '富贵',
};
```

**Comment by chenshuai2144** [comment]
这个，主要配置了的都会被处理，你下面的这些能放到别的地方吗？

![image](https://user-images.githubusercontent.com/8186664/108961054-c4531400-76b1-11eb-9ba8-75b98968dd24.png)

**Comment by xgj1988** [comment]
@chenshuai2144  你的意思是自定义参数 卸载里面 ，都会被处理吗?但是 primaryColor，layout这些参数 是自带的撒。

**Comment by chenshuai2144** [comment]
只要是 setting 就会被 layout 处理掉

**Comment by xgj1988** [comment]
你的意思是我把 config 下面的defaultSettings.js 这个文件里面的内容全部删了，就没问题了吗？

**Comment by chenshuai2144** [comment]
嗯，你用别的配置文件来配置这些地方
