### ISSUE TITLE
🧐[问题]可编辑表格没有类似于高级表格中的ellipsis超出隐藏列属性吗

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/pro-components#1949]
### 🧐 问题描述
想要给可编辑表格的某个列加上超出隐藏的属性，但是使用了ellipsis并没有起作用

### 💻 示例代码
{
      title: '通知角色',
      dataIndex: 'roleIds',
      width: 300,
      ellipsis: true,
}

**Comment by chenshuai2144** [comment]
这个估计不行，因为可编辑表格里面的内容都是组件，你可以在组件上加一下这些功能，或者直接包一下 overflow:"hidden"
