### ISSUE TITLE
filter有clear方法么？没有的话可以在ActionRef中增加clearFilters方法吗🧐[问题]

### ISSUE THREAD

**Issue by meyerlee** [ant-design/pro-components#195]
### 🧐 问题描述
使用了过滤之后，去setting中设置去掉这列，但是filter还是一直生效，就会很疑惑。
在onColumnsStateChange控制filter的列不能隐藏，但也会不舒服。
受控的filter还可以通过记录props来清除， valueEnum自动生成的filter也就不行了。

ActionRef中增加clearFilters(key?:string) 这样可以清除指定或所有column的filter是不是可以有。

**Comment by chenshuai2144** [comment]
我们会在 reloadAndRest 中支持，会清空掉所有的配置。
