### ISSUE TITLE
🐛[BUG]ProLanyout   fixedHeader: true, 动画消失

### ISSUE THREAD

**Issue by k983551019** [ant-design/pro-components#1951]
### 🐛 bug 描述
固定haeader后， 关闭开启collapsed 
collapsed 打开后haeader的动画消失

### 📷 复现步骤
 fixedHeader:这值为true,
然后点击collapsed 

### 💻 复现代码
 fixedHeader: true,

### © 版本信息

- pro-layout版本: 6.9.0
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![aa0](https://user-images.githubusercontent.com/48147837/108795936-76abae00-75c2-11eb-9f99-136825e301e0.png)

**Comment by k983551019** [comment]
V5预览就有 https://preview.pro.ant.design/dashboard/analysis?fixSiderbar=true&colorWeak=false&pwa=false&fixedHeader=true
点击collapsed 打开的时候就会出现

**Comment by chenshuai2144** [comment]
是有的，最好来个gif，然后告诉我们具体是什么地方有问题

**Comment by k983551019** [comment]
> 是有的，最好来个gif，然后告诉我们具体是什么地方有问题


https://user-images.githubusercontent.com/48147837/108819583-fd2db300-75f5-11eb-9a8c-e9f1de0ee677.mp4

**Comment by k983551019** [comment]
https://user-images.githubusercontent.com/48147837/108819984-847b2680-75f6-11eb-8cfd-33601835c96b.mp4

**Comment by k983551019** [comment]
> 是有的，最好来个gif，然后告诉我们具体是什么地方有问题

![108819583-fd2db300-75f5-11eb-9a8c-e9f1de0ee677](https://user-images.githubusercontent.com/48147837/108930556-192a6680-7681-11eb-94dc-1a6eb606bfc4.gif)

**Comment by chenshuai2144** [comment]
感觉还挺流畅的

**Comment by k983551019** [comment]
> 感觉还挺流畅的
 
😤 关注那个头  打开的时候缺失了  antdesignpro  右边

**Comment by chenshuai2144** [comment]
fixed
