### ISSUE TITLE
🧐[问题]EditTable的使用问题

### ISSUE THREAD

**Issue by mathcw** [ant-design/pro-components#1952]
### 🧐 问题描述
       EditTable的使用中遇到了一个问题：受控的EditTable 我在table的外部对DataSource的可编辑字段进行更新
      表格并没有更新显示最新的数据 ，但是不可编辑的字段可以显示最新的数据
      感觉是EditTable接管了对可编辑字段的更新，那我应该怎么做呢 要使用form.setvalue()这样的方法吗？

### 💻 示例代码
https://codesandbox.io/s/shishibaocundebianjibiaoge-forked-ngxu9

**Comment by chenshuai2144** [comment]
`dataSource={...DataSource}`

告诉表格你更新了数据

**Comment by mathcw** [comment]
好像还是不行啊大佬 麻烦看一下 https://codesandbox.io/s/shishibaocundebianjibiaoge-forked-ngxu9 这个代码
我设置了datasource 在更新完数据后 表格依然没刷新

**Comment by mathcw** [comment]
> `dataSource={...DataSource}`
> 
> 告诉表格你更新了数据，每次更新数据的时候浅拷贝一下

好像还是不行啊大佬 麻烦看一下 https://codesandbox.io/s/shishibaocundebianjibiaoge-forked-ngxu9 这个代码
我设置了datasource 在更新完数据后 表格依然没刷新

**Comment by chenshuai2144** [comment]
把 DataSource存到 state里面，你不能这种修改的。

**Comment by ibryanwu** [comment]
我之前也遇到了这个问题，你把可编辑行想成一个form 用useForm得到这个form，完了去更新这个form就行了，不能直接修改datasource 要不form不会知道要重新渲染

**Comment by mathcw** [comment]
> 我之前也遇到了这个问题，你把可编辑行想成一个form 用useForm得到这个form，完了去更新这个form就行了，不能直接修改datasource 要不form不会知道要重新渲染

嗯嗯是的 我看#1866里面可以获取到form了 就OK了
