### ISSUE TITLE
🐛[BUG] onChange事件获取不到filters了

### ISSUE THREAD

**Issue by beeant0512** [ant-design/pro-components#1953]
### 🐛 bug 描述

查询框搜索过后，点击分页切换，onChange事件的 filters没有查询框的搜索值了

### 📷 复现步骤

 <ProTable
            actionRef={actionRef}
            onChange={(_page, _filter, _sorter, _extra) => {
                setPage({ current: _page.current, pageSize: _page.pageSize });
                actionRef.current = _page.current;
                const sorterResult = _sorter;
                if (sorterResult.field) {
                    if (sorterResult.order) {
                        setSorter(`${sorterResult.field}_${sorterResult.order}`);
                    } else {
                        setSorter(`${sorterResult.field}`);
                    }
                }
                setFilter({ ...filter, ..._filter });
            }}
            loading={loading}
            dataSource={data.list}
            pagination={pagination}
/>

### 🏞 期望结果

春节前还是可以的，但是节后就出现了异常

### © 版本信息

- ProComponents 版本: @ant-design/pro-table:2.2.2
- umi 版本 3.2.22
- 浏览器环境 版本 88.0.4324.150（正式版本） （64 位）
- 开发环境 windows10

**Comment by beeant0512** [comment]
自定义组件代码如下：

import React, { useEffect, useRef, useState } from "react";
import ProTable from "@ant-design/pro-table";
import { Button } from "antd";

const rootKey = undefined;
const Protable = (props) => {
  const {
    columns,
    loading,
    data,
    fetch,
    type,
    reload,
    rowKey,
    rootId,
    ...rest
  } = props;

  if (type === "form") {
    return (
      <ProTable
        {...props}
        form={{
          layout: "horizontal",
          labelCol: {
            span: 4,
          },
          wrapperCol: {
            span: 20,
          },
          ...props.form,
        }}
      />
    );
  }

  const [sorter, setSorter] = useState("");
  const [page, setPage] = useState({ current: 1 });
  const [filter, setFilter] = useState({});
  const actionRef = useRef();
  const [size, setSize] = useState("small");
  const [timestamp, setTimestamp] = useState(0);

  useEffect(() => {
    if (rootId === rootKey) {
      setPage({ ...page, current: 1 });
    } else {
      if (fetch) {
        fetch(page, sorter, filter);
      }
    }
  }, [page, sorter, filter, reload, timestamp]);

  const reloadTable = () => {
    setTimestamp(parseInt(`${new Date().getTime() / 1000}`, 10));
  };
  let pagination = {};
  if (props.pagination !== undefined) {
    pagination = props.pagination;
  } else {
    pagination = {
      current: page.current,
      total: data.pagination.total,
      defaultCurrent: page.current,
      showSizeChanger: true,
      showQuickJumper: true,
      defaultPageSize: 10,
    };
  }
  return (
    <ProTable
      actionRef={actionRef}
      onChange={(_page, _filter, _sorter, _extra) => {
        setPage({ current: _page.current, pageSize: _page.pageSize });
        actionRef.current = _page.current;
        const sorterResult = _sorter;
        if (sorterResult.field) {
          if (sorterResult.order) {
            setSorter(`${sorterResult.field}_${sorterResult.order}`);
          } else {
            setSorter(`${sorterResult.field}`);
          }
        }
        setFilter({ ...filter, ..._filter });
      }}
      tableAlertRender={false}
      columns={columns}
      size={size}
      bordered
      onSizeChange={(val) => setSize(val)}
      search={{
        labelWidth: "auto",
        optionRender: ({ searchText, resetText }, { form: _form }) => (
          <>
            <Button
              type="primary"
              onClick={() => {
                actionRef.current = 1;
                setPage({ ...page, current: 1 });
                setFilter(_form.getFieldsValue());
              }}
            >
              {searchText}
            </Button>
            <Button
              style={{ marginLeft: 8 }}
              onClick={() => {
                _form.resetFields();
                setFilter({});
              }}
            >
              {resetText}
            </Button>
          </>
        ),
      }}
      form={{
        labelCol: { span: 10 },
      }}
      options={{
        fullScreen: true,
        setting: true,
        density: false,
        reload: () => {
          reloadTable();
        },
      }}
      rowKey={rowKey}
      {...rest}
      loading={loading}
      dataSource={data.list}
      pagination={pagination}
    />
  );
};

export default Protable;

在之前的版本2.2.1 onChange={(_page, _filter, _sorter, _extra) => {} 都是可以正常获取filter的值的，升级后就不行了

**Comment by chenshuai2144** [comment]
是不是 antd 的版本没跟上，我试了下是可以的

**Comment by beeant0512** [comment]
用的antd的哪个版本？

**Comment by chenshuai2144** [comment]
我用的latest
