### ISSUE TITLE
🐛[BUG]EditableProTable 的editable中已经拿到了form实例，可以重置行等，但不可以getFieldValue或者setsetFieldsValue

### ISSUE THREAD

**Issue by ibryanwu** [ant-design/pro-components#1954]
### 📷 复现步骤
1、const [form] = Form.useForm();
2、绑定form
3、在column中的某个列中使用
const columns = [
    {
      title: '活动名称',
      dataIndex: 'title',
      fieldProps:{
        onChange:(val)=>{
          console.log('val',val)
          form.getFieldValue('state')// 返回 undefined  ？
          form.setFieldsValue({desc:'XXX'}) // 不起作用 ？
        },
      },

### 🏞 期望结果

当EditableProTable 的 row 为编辑form时，可以通过改变一个字段的值，计算出结果set到另一个字段中
举例， 录入 【数量字段】 可以get到【价格】字段的值，然后计算出金额，set到金额字段中

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
一个table只有一个form，get 的时候要用 form.getFieldValue([rowKey,'state'])

```
form.getFieldValue([config.recordKey || config.index,'sate'])
```

**Comment by ibryanwu** [comment]
@chenshuai2144 多谢多谢 解决困扰我很久的问题 刚试了已经可以get值了，那如何set值呢？form.setFieldsValue 也要加rowKey么？要怎么写？

**Comment by chenshuai2144** [comment]
一个table只有一个form，get 的时候要用 form.getFieldValue([rowKey,'state'])
