### ISSUE TITLE
🐛[BUG]EditableProTable中key的值为0时，激活编辑状态不显示默认选项

### ISSUE THREAD

**Issue by aoyeQ** [ant-design/pro-components#1960]
### 🐛 bug 描述

当key的值不显示默认值

### 📷 复现步骤

1. valueType='select'， valueEnum类型为Map<number, string>、值存在0=>'xxx'，
2. key的值为0时，激活编辑状态select没有显示默认值，通过fieldProps来控制能显示但是不能通过校验

### 🏞 期望结果

当值为0是显示并绑定默认的选项

### 💻 复现代码

title: '是否必传',
        dataIndex: 'fieldType',
        formItemProps: {
          rules: [
            {
              required: true,
              message: '必填项',
            },
          ],
        },
        valueType: 'select',
        valueEnum: new Map<number, string>([
  [0, '否'],
  [1, '是'],
]),

### © 版本信息

- ProComponents 版本: [2.30.0]
- umi 版本:3.3.7
- 浏览器环境： 版本：88.0.4324.146
- 开发环境 [Windows]

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
来个在线的重现吧，让我可以直接看的

**Comment by aoyeQ** [comment]
reproduce：[code](https://codesandbox.io/s/crazy-swanson-rnhoz?fontsize=14&hidenavigation=1&theme=dark)
期望结果：isRequired的默认值为`0`应默认显示`否`

**Comment by colorbitch** [comment]
确实有这个问题，望解决一下。场景：返回的数据中，key不是字符串的时候，无法在编辑模式中默认值显示text，而是直接显示value了。
valueEnum   eg {
                0: {text: '是', status: 'Success'},
                1: {text: '否', status: 'Error'},
            },

编辑之前显示“是”或“否”，点编辑之后默认值就是0和1，如图

![image](https://user-images.githubusercontent.com/8054331/111906065-c8dcd380-8a89-11eb-9a17-d1631e168655.png)

**Comment by chenshuai2144** [comment]
key 只能是字符串，不能是 number，你最好人肉转一下
