### ISSUE TITLE
🐛[BUG] EditableProTable 的editable中已经拿到了form实例 无法setFieldsValue 

### ISSUE THREAD

**Issue by ibryanwu** [ant-design/pro-components#1962]
### 🐛 bug 描述
EditableProTable 的editable中已经拿到了form实例 可以通过getFieldValue 获取值，但无法setFieldsValue 给其他Field

### 📷 复现步骤
1. 绑定form
2. form.getFieldValue([rowKey,'state'])----ok
3. form.setFieldsValue({state:"closed"}) // 不起作用

### 🏞 期望结果
A-Field的值根据另外一个B-Field值的变化而计算，结果Set到A-Field 中

### 💻 复现代码
const columns = [
    {
      title: '活动名称',
      dataIndex: 'title',
      fieldProps:{
        onChange:(val)=>{
          //console.log('val',val)
          //console.log(form.getFieldsValue(true))
          console.log(form.getFieldValue([624748504,'state']))// --------OK
          form.setFieldsValue({state:"closed"}) // =======不起作用
        },
      },

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
```
form.setFieldsValue({rowKey :{state:"closed"}}}
```

rowKey  总是必须要的

**Comment by ibryanwu** [comment]
@chenshuai2144 解决了，多谢啦
