### ISSUE TITLE
希望在protable中 可以获取到form 的实例

### ISSUE THREAD

**Issue by jockey100332** [ant-design/pro-components#197]
### 🥰 需求描述

在项目中，创建与编辑 的表单项大多相同，而编辑功能仅是比创建多一步需要对formItem进行赋值，希望可以通过ref 获取到form 表单的实例方法
这样仅需要编写对应的数据格式即可通过变量判断进行不同操作了

**Comment by chenshuai2144** [comment]
formRef 是可以获得的，只是文档中没有露出
