### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by 782042369** [ant-design/pro-components#1970]
### 📷 复现步骤
{
    title: '广告位',
    dataIndex: 'slotIds',
    key: 'slotIds',
    hideInTable: true,
    request: async () => handleGetOpt(),
    valueType: 'select',
    fieldProps: {
      placeholder: '请选择广告位',
      showSearch: true,
      optionFilterProp: 'children',
    },
}
1.protable fieldProps select 设置 showSearch 为true 搜索展示错误
![image](https://user-images.githubusercontent.com/28727900/108831344-f2c6e580-7604-11eb-82df-8d6162f3dd5d.png)
正常应该为
![image](https://user-images.githubusercontent.com/28727900/108831308-e6db2380-7604-11eb-9042-22a65825dd33.png)

2.每次输入都会会触发request 请求
![image](https://user-images.githubusercontent.com/28727900/108831394-05d9b580-7605-11eb-98e5-e368dfce762d.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 3.3.7
- 浏览器环境 谷歌 88.0
- 开发环境 [e.g. mac OS]

**Comment by weiqishang** [comment]
同样遇到每次输入都会会触发request 请求，版本也升为最新，请问如何解决
