### ISSUE TITLE
umi 中升级最新的ant-design/pro-layout 报错🐛[BUG]

### ISSUE THREAD

**Issue by MoonSeeing** [ant-design/pro-components#1972]
### 🐛 bug 描述
用 ant designer pro 脚手架搭建了 一个项目 目前已在线上使用。鉴于需要使用 pro组件的新特性。故想升级所有pro 组件。升级后报错 Error: Cannot find module '@ant-design/pro-layout'

### 📷 复现步骤
1.删除原ant designer pro 项目的 yarn.lock
2.重新 yarn install
3.启动项目

### 🏞 报错信息
![image](https://user-images.githubusercontent.com/19420622/108932644-ab803980-7684-11eb-8020-849346562d0e.png)
![image](https://user-images.githubusercontent.com/19420622/108932679-baff8280-7684-11eb-84c5-e66689a49b73.png)

### © 版本信息

-
- umi 版本
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]
![image](https://user-images.githubusercontent.com/19420622/108932770-df5b5f00-7684-11eb-97b9-1fd9b444e771.png)

### 🚑 其他信息
如截图等其他信息可以贴在这里
-->

**Comment by MoonSeeing** [comment]
是否是因为 pro-layout 升级了 导致@umijs/plugin-layout  找不到 改组件。我这边做的仅仅是在原项目上 重新安装了 依赖

**Comment by yutingzhao1991** [comment]
是更新了 plugin-layout 吗？最新版本不直接依赖 @ant-design/pro-layout，手动安装下 @ant-design/pro-layout 应该就好了。

**Comment by MoonSeeing** [comment]
> 是更新了 plugin-layout 吗？最新版本不直接依赖 @ant-design/pro-layout，手动安装下 @ant-design/pro-layout 应该就好了。

还在找原因 ，我这边使用了monorepo 的方式 管理两个 umi 项目。本来都是 可以使用的 ，这边是想把所有的pro-components全部升级到最新咯。单个升级 怕会有些组件依赖版本不匹配。
![image](https://user-images.githubusercontent.com/19420622/108933669-81c81200-7686-11eb-9ed1-4fade793cce0.png)

**Comment by MoonSeeing** [comment]
w
