### ISSUE TITLE
ProFormList 如何配置点击添加的默认数据？🧐[问题]

### ISSUE THREAD

**Issue by kzcPo** [ant-design/pro-components#1974]
### 🧐 问题描述

ProFormList 官方示例有initialValue，可配置初始化的第一条数据。
那么如何配置添加一行时的默认数据呢？
Form.List 可以调用add方法，传入参数，指定添加一行的默认数据，ProFormList哪里可以调用add方法呢？

需求是：添加一行，默认传入数据{ 'condition': true, 'symbol': '==' }

### 💻 示例代码
```
<ProFormList
        name={[field.name, "expresses"]}
        creatorButtonProps={{
          creatorButtonText: '添加条件',
        }}
      >
        <ProFormSwitch
          name={'condition'}
          checkedChildren={'且'}
          unCheckedChildren={'或'}
        // fieldProps={{
        //   defaultChecked: true
        // }}
        />

        <ProFormText
          name={'tagKey'}
          placeholder="请输入标签key"
          rules={[{ required: true, message: '请输入标签key' }]}
        />

        <ProFormSelect
          name={'symbol'}
          width={"xs"}
          valueEnum={AlarmMergeSymbolMap}
        />

        <ProFormText
          name={'tagValue'}
          width={"sm"}
          placeholder="请输入标签value"
          rules={[{ required: true, message: '请输入标签value' }]}
        />
</ProFormList>
```

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/16077203/108940826-0028b200-768f-11eb-850b-9f7a673c5464.png)

**Comment by chenshuai2144** [comment]
有个 creatorRecord 属性，你先配置一下，我加个 demo

**Comment by chenshuai2144** [comment]
### ProFormList API

| 参数 | 说明 | 类型 | 默认值 |
| --- | --- | --- | --- |
| creatorRecord | 新建一行的默认值 | `Record<string, any>` | - |
| creatorButtonProps | 新建一行按钮的配置 | `buttonProps & { creatorButtonText:string,position:"top"\|"bottom" }` | `{creatorButtonText:"新建一行"}` |
| label | 与 From.Item 相同 | `ReactNode` | - |
| name | list 在 form 中的值，必填项 | `NamePath` | - |

**Comment by seveneElevenup** [comment]
想问一下单行可以添加，多行怎么添加呀？

**Comment by kzcPo** [comment]
你好，我已经收到邮件！

**Comment by seveneElevenup** [comment]
> 有个 creatorRecord 属性，你先配置一下，我加个 demo

是的，单行可以添加，请问一下点击一次如何添加多行，文档上这里不能传数组的

**Comment by V1nnnnnnn** [comment]
> 有个creatorRecord属性，你先配置一下，我加个demo

creatorRecord添加默认值我想拿到当前record的index怎么解决？

**Comment by xinzai2014** [comment]
同问：creatorRecord添加默认值我想拿到当前record的index怎么解决？
