### ISSUE TITLE
🐛[BUG] prolist筛选项文本显示异常

### ISSUE THREAD

**Issue by kyouhoo** [ant-design/pro-components#1975]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/37536435/108944068-00c44700-7695-11eb-8363-086c4dd58b9d.png)

![image](https://user-images.githubusercontent.com/37536435/108944148-310be580-7695-11eb-9ad5-985fa47a28e8.png)
这里的筛选项文本应该显示为 「状态」

### 📷 复现步骤

文档示例 #带筛选和异步请求的列表 中就有这个bug，
[https://procomponents.ant.design/components/list#%E5%B8%A6%E7%AD%9B%E9%80%89%E5%92%8C%E5%BC%82%E6%AD%A5%E8%AF%B7%E6%B1%82%E7%9A%84%E5%88%97%E8%A1%A8](url)

### 🏞 期望结果

显示正确的筛选项文本

### 💻 复现代码

参考文档示例 #带筛选和异步请求的列表，
[https://procomponents.ant.design/components/list#%E5%B8%A6%E7%AD%9B%E9%80%89%E5%92%8C%E5%BC%82%E6%AD%A5%E8%AF%B7%E6%B1%82%E7%9A%84%E5%88%97%E8%A1%A8](url)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
无

**Comment by kyouhoo** [comment]
LightFilter好像都有这个问题

**Comment by chenshuai2144** [comment]
我不知道正常的结果是什么？最好给个正常的版本

**Comment by kyouhoo** [comment]
> 我不知道正常的结果是什么？最好给个正常的版本

切了很多版本，搞不出正常结果的截图，下图红框部分应该是显示 『状态』 而不是 『请输入』
![image](https://user-images.githubusercontent.com/37536435/108986256-e8701e80-76cc-11eb-85a6-a32d01b83119.png)

import React from 'react';
import { Button, Tag, Space } from 'antd';
import ProList from '@ant-design/pro-list';
import request from 'umi-request';

type GithubIssueItem = {
  url: string;
  id: number;
  number: number;
  title: string;
  labels: {
    name: string;
    color: string;
  }[];
  state: string;
  comments: number;
  created_at: string;
  updated_at: string;
  closed_at?: string;
};

export default () => (
  <ProList<GithubIssueItem>
    toolBarRender={() => {
      return [
        <Button key="3" type="primary">
          新建
        </Button>,
      ];
    }}
    search={{
      filterType: 'light',
    }}
    rowKey="name"
    headerTitle="基础列表"
    request={async (params = {}) =>
      request<{
        data: GithubIssueItem[];
      }>('https://proapi.azurewebsites.net/github/issues', {
        params,
      })
    }
    pagination={{
      pageSize: 5,
    }}
    showActions="hover"
    metas={{
      title: {
        dataIndex: 'user',
        title: '用户',
      },
      avatar: {
        dataIndex: 'avatar',
        search: false,
      },
      description: {
        dataIndex: 'title',
        search: false,
      },
      subTitle: {
        dataIndex: 'labels',
        render: (_, row) => {
          return (
            <Space size={0}>
              {row.labels?.map((label: { name: string }) => (
                <Tag color="blue" key={label.name}>
                  {label.name}
                </Tag>
              ))}
            </Space>
          );
        },
        search: false,
      },
      actions: {
        render: (text, row) => [
          <a href={row.url} target="_blank" rel="noopener noreferrer" key="link">
            链路
          </a>,
          <a href={row.url} target="_blank" rel="noopener noreferrer" key="warning">
            报警
          </a>,
          <a href={row.url} target="_blank" rel="noopener noreferrer" key="view">
            查看
          </a>,
        ],
        search: false,
      },
      status: {
        // 自己扩展的字段，主要用于筛选，不在列表中显示
        title: '状态',
        valueType: 'select',
        valueEnum: {
          all: { text: '全部', status: 'Default' },
          open: {
            text: '未解决',
            status: 'Error',
          },
          closed: {
            text: '已解决',
            status: 'Success',
          },
          processing: {
            text: '解决中',
            status: 'Processing',
          },
        },
      },
    }}
  />
);

**Comment by kyouhoo** [comment]
> 我不知道正常的结果是什么？最好给个正常的版本

valueType为dateRange还是有问题，会直接显示
![image](https://user-images.githubusercontent.com/37536435/109292637-a4fce800-7865-11eb-9368-03b56f7ccdb2.png)
预期应该是
![image](https://user-images.githubusercontent.com/37536435/109292662-af1ee680-7865-11eb-8f7d-bbd17a57bc95.png)
点开之后在展示日期选择框

**Comment by chenshuai2144** [comment]
试了下没有问题，测试用例也没出现问题

**Comment by kyouhoo** [comment]
> 试了下没有问题，测试用例也没出现问题

在ProList中配置 filterType: 'light', 然后meta 中配置valueType: "dateRange", 就会出现上面的问题；
prolist版本是1.5.6，antd版本4.13.1。

```
const metas = {
  updated_at: {
    title: '更新日期',
    valueType: "dateRange",
  },
}
```
