### ISSUE TITLE
假设我要升级项目中的form 组件我该如何正确的进行升级呢，🧐[问题]

### ISSUE THREAD

**Issue by MoonSeeing** [ant-design/pro-components#1976]
### 🧐 问题描述
umi 启动的项目中依赖了 table ,form 等pro组件，现在因为 form 有新特性 想支持 该如何升级form ,但又使得其他的组件依赖并不会受到影响呢

**Comment by chenshuai2144** [comment]
这好像不行，要升级就要一起升级的。全家桶

**Comment by MoonSeeing** [comment]
> 这好像不行，要升级就要一起升级的。全家桶

能请教下，你们一般是如何在一个项目中针对这些组件进行统一升级到最新呢，从而很好的 修整 yarn.lock的版本锁定

**Comment by chenshuai2144** [comment]
删掉 lock，重新生成一下。

lock 是停止维护的项目 才会用的

**Comment by MoonSeeing** [comment]
> 删掉 lock，重新生成一下。
> 
> lock 是停止维护的项目 才会用的

我之前试过这个 方式 ，但是好可怕的是导致了 别的致命错误 #1972

**Comment by chenshuai2144** [comment]
看了下报错，有个依赖没装。 你是有多久没有更新依赖了
