### ISSUE TITLE
👑 [建议]ProTable的search属性里响应式span的值与antd的Col的不一致，以及不设置xxl时可能会导致页面出错

### ISSUE THREAD

**Issue by jmxiang** [ant-design/pro-components#1977]
### 🥰 需求描述

根据antd的[Col](https://ant.design/components/grid-cn/#Col)文档，响应式的断点划分是：
![image](https://user-images.githubusercontent.com/30228128/108945256-4550e200-7697-11eb-97a5-efc2c2889970.png)
pro-form的是：
![image](https://user-images.githubusercontent.com/30228128/108945377-79c49e00-7697-11eb-8af8-2b2fe79d9632.png)
导致查询表格的表单区域布局与预期不一致，代码如下：
![image](https://user-images.githubusercontent.com/30228128/108945481-a5e01f00-7697-11eb-9d02-7c28a94766fc.png)

另外当未设置xxl值时，页面过宽时会报错(Cannot read property 'breakPoint[1]' of undefined)，希望可以解决一下
![image](https://user-images.githubusercontent.com/30228128/108945750-26068480-7698-11eb-86c2-50addc212aa5.png)

### 🚑 其他信息

ant-design-pro版本：5.0.0-beta.2

**Comment by chenshuai2144** [comment]
来个 pr 吧

**Comment by jmxiang** [comment]
> 来个 pr 吧

- -! 很惭愧水平有限   fork后尝试npm start没跑起来，没验证。应该把‘CONFIG_SPAN_BREAKPOINTS’修改成
- `const CONFIG_SPAN_BREAKPOINTS = {
  xs: 576,
  sm: 768,
  md: 992,
  lg: 1200,
  xl: 1600,
  xxl: Infinity,
};`
‘breakPoint’做下容错？
还是麻烦你处理一下吧
