### ISSUE TITLE
🐛[BUG] Prolayout's collapsed sidebar can't be closed on mobile view

### ISSUE THREAD

**Issue by arifszn** [ant-design/pro-components#1982]
### 🐛 bug 描述

The [customized collapsed](https://procomponents.ant.design/en-US/components/layout#customized-collapsed) can't be closed on mobile view.

![image](https://user-images.githubusercontent.com/45073703/108952404-99f25e00-7693-11eb-9ae8-7fc5f7dbf86b.png)

Nothing happens when you click outside to close.

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
look is good

https://procomponents.ant.design/~demos/layout-base-1

**Comment by arifszn** [comment]
Please visit the page on mobile view.
https://procomponents.ant.design/~demos/layout-customize-collapsed

**Comment by arifszn** [comment]
> look is good
> 
> https://procomponents.ant.design/~demos/layout-base-1

Please visit the page on mobile view.
https://procomponents.ant.design/~demos/layout-customize-collapsed

**Comment by chenshuai2144** [comment]
i updated demo

**Comment by xXAvoraXx** [comment]
Unable to close menu mobile while it is on the screen.
