### ISSUE TITLE
form 使用 syncToUlr 在 reset 时无法清除数据🐛[BUG]

### ISSUE THREAD

**Issue by MoonSeeing** [ant-design/pro-components#1986]
### 🐛 bug 描述
https://procomponents.ant.design/~demos/form-sync-to-url-1?useMode=chapter&startTime=2021-02-25&endTime=2021-03-25&name=%E8%9A%82%E8%9A%81%E8%AE%BE%E8%AE%A1%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8

### 📷 复现步骤
点击上诉链接进入 页面 点击 重置按钮  时间数据无法清空

**Comment by chenshuai2144** [comment]
这个有点不好处理，表单不知道该删除哪些数据

**Comment by MoonSeeing** [comment]
> 这个有点不好处理，表单不知道该删除哪些数据

我这边写了一个 将 url 同步的功能 在table中实现，能够解决这个bug,我提个pr 看是否可行，这边已经在本地demo 中测试过了.
目前我暂时只实现了 查询字段的同步，sort 和pagination的信息应该也是可以实现的。

**Comment by JunlinZhu-Tommy** [comment]
我在有`ProFormDateRangePicker`的表单里面使用reset时也遇到了同样的问题，例如:
`ProFormDateRangePicker`的`name` 为: dateRange
但是需要同步到url上的字符串通常为: `startDate`, `endDate`分别指向`dateRange`里面的开始时间。

在使用onFinish时调用[`syncToUrl`](https://github.com/ant-design/pro-components/blob/master/packages/form/src/BaseForm/index.tsx#L220)钩子可以自定义同步到url上面的内容。

但是在onReset时，当有用户定义的`syncToUrl`时，确只是[用了表单ref清空后的fieldsValue](https://github.com/ant-design/pro-components/blob/master/packages/form/src/BaseForm/index.tsx#L138)。

是否可以在onReset里面也调用`setUrlSearch(genParams(syncToUrl, params, 'set'));` 当 `typeof syncToUrl === 'function'` 时。

这个需求刚好是我这周的一个kpi哈哈。

@chenshuai2144

**Comment by chenshuai2144** [comment]
欢迎来个 pr

**Comment by JunlinZhu-Tommy** [comment]
I will.

**Comment by gxb1998** [comment]
<img width="419" alt="image" src="https://user-images.githubusercontent.com/52820524/223080791-538b55b0-7671-4b0f-8f76-69f53c552d0f.png">
设置syncToInitialValues false
