### ISSUE TITLE
当设置了查询表单colSize 为 3后，搜索重置列布局出现问题🐛[BUG]

### ISSUE THREAD

**Issue by zhangxiangqiang** [ant-design/pro-components#1987]
### 🐛 bug 描述

当设置了上一个查询表单项colSize 为 3， 独占一行后，搜索重置列布局出现问题，它排列在下一行的左侧，看起来非常怪。

我希望它排列在右侧

或者有什么办法可以 让我单独为搜索重置列自定义布局么？

### 💻 复现代码

```
const buttonValueEnum = {
   ALL: '全部',
   LESS_THAN_ONE_MONTH:  '开业1个月以内',
   ONE_TO_THREE_MONTH:  '开业1~3个月',
   THREE_TO_SIX_MONTH:  '开业3~6个月',
   SIX_TO_TWELVE_MONTH:  '开业6~12个月',
   MORE_THAN_TWELVE_MONTH:  '开业12个月以上',
  };


const columns = [
{
      title: '门店阶段',
      dataIndex: 'openDurationTypes',
      hideInTable: true,
      valueType: 'radioButton',
      width: 100,
      valueEnum: buttonValueEnum,
      colSize: 3,
    },

]


<ProTable
  columns={columns}
  ...
/>

```
### © 版本信息
"@ant-design/pro-table": "^2.12.1",
- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30229705/108966184-d71d1700-76b8-11eb-822c-3a7b7b88847a.png)

**Comment by chenshuai2144** [comment]
这个是个bug，我们会处理
