### ISSUE TITLE
🐛[BUG]ProTable工具栏中的密度只能正常点击一次，再次点击会出现密度下拉框闪烁并消失

### ISSUE THREAD

**Issue by lichangchao15442** [ant-design/pro-components#1988]
### 🐛 bug 描述

ProTable工具栏中的密度只能正常点击一次，再次点击会出现密度下拉框闪烁并消失

### 📷 复现步骤

代码copy自官网示例中的 查询表格 模块

### 🏞 期望结果

正常使用 ProTable 工具栏中的密度功能

### © 版本信息

- ProComponents 版本: ["@ant-design/pro-table": "^2.30.0"]
- umi 版本: [ "^3.3.7"]
- 浏览器环境:[Chrome]
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
@zombieJ  这个你看看，我发现 select 总是这样，必须要点另外一个才能完成恢复正常，是不是有什么改动
