### ISSUE TITLE
👑 [需求]ProLayout  在headerContentRender中使用 breadcrumbRender的route

### ISSUE THREAD

**Issue by k983551019** [ant-design/pro-components#1989]
### 🥰 需求描述
需要在header中生成面包屑
如题 在headerContentRender中使用 breadcrumbRender的route
在我分别打印breadcrumbRender的routr和headerContentRender 的props
发现breadcrumbRender的router先出。
headerContentRender的props里并没有breadcrumbRender的router的数据

### 🧐 解决方案
所以能不能把breadcrumbRender的router数据放到BasicLayoutProps里

### 🚑 其他信息
![mbx](https://user-images.githubusercontent.com/48147837/108971430-44cb4200-76bd-11eb-9ff7-81afefacb711.jpg)
途中空白是headerContentRender的props里并没有可以直接食用的面包屑数据

**Comment by chenshuai2144** [comment]
好像不能这么搞，要通过  RouteContext来解决。

RouteContext
RouteContext 可以提供 Layout 的内置的数据。例如 isMobile 和 collapsed，你可以消费这些数据来自定义一些行为。
```

import { RouteContext, RouteContextType } from '@ant-design/pro-layout';
const Page = () => (
  <RouteContext.Consumer>
    {(value: RouteContextType) => {
      return value.title;
    }}
  </RouteContext.Consumer>
);
```

**Comment by k983551019** [comment]
ok
解决
使用   breadcrumbRender: (route) => { return route },返回面包屑数据
可以在RouteContext  value里获取到 breadcrumb.routes 来使用

**Comment by k983551019** [comment]
> 好像不能这么搞，要通过 RouteContext来解决。
> 
> RouteContext
> RouteContext 可以提供 Layout 的内置的数据。例如 isMobile 和 collapsed，你可以消费这些数据来自定义一些行为。
> 
> ```
> 
> import { RouteContext, RouteContextType } from '@ant-design/pro-layout';
> const Page = () => (
>   <RouteContext.Consumer>
>     {(value: RouteContextType) => {
>       return value.title;
>     }}
>   </RouteContext.Consumer>
> );
> ```

![1111](https://user-images.githubusercontent.com/48147837/108986510-2a996000-76cd-11eb-92dd-be7273b4dd25.jpg)
一级菜单没有子路由的  RouteContext里也获取不到
![2222](https://user-images.githubusercontent.com/48147837/108986526-2d945080-76cd-11eb-9b47-39c20205da46.jpg)

**Comment by wanglianjie91** [comment]
同样，RouteContext拿不到bread的数据。
按照官网教程直接把PageContainer作为layout的子节点， 也出不来面包屑。
bug多多。

**Comment by k983551019** [comment]
> 同样，RouteContext拿不到bread的数据。
> 按照官网教程直接把PageContainer作为layout的子节点， 也出不来面包屑。
> bug多多。

多级菜单可以拿到，一级的就自己判断下吧
要拿到面包屑 需要 
 breadcrumbRender: (route) => { return route },

**Comment by wanglianjie91** [comment]
> > 同样，RouteContext拿不到bread的数据。
> > 按照官网教程直接把PageContainer作为layout的子节点， 也出不来面包屑。
> > bug多多。
> 
> 多级菜单可以拿到，一级的就自己判断下吧
> 要拿到面包屑 需要
> breadcrumbRender: (route) => { return route },

扒完源码回来了， 只有一级的时候隐藏面包屑。
那么问题又来了。

routes.ts

`  export default [{
    path:'/',
    name: '首页',
    component:'@/layouts/basiclayout',
    // hideInMenu:true,
    routes:[
      {
        path:'/banner',
        name: 'banner ',
        component:'./banner'
      }
}]`


layout.ts

`
<ProLayout
      route={{routes}}
      breadcrumbRender={route=> 为何只能拿到一级导航，也是banner， 首页拿不到}
/>
`
