### ISSUE TITLE
二级路由高亮的对外方法

### ISSUE THREAD

**Issue by nohavebug** [ant-design/pro-components#199]
### 🧐 问题描述

我想知道路由的高亮有报漏出来的方法吗？
我是二级路由列表进入编辑/新建页面（使用的是动态路由 :id），这时候如何让二级路由高亮呢

**Comment by chenshuai2144** [comment]
你可以用 parentKeys=['key'],强行设置它归属于某个子节点

**Comment by zim-lee** [comment]
文档没看到有parentKeys的使用描述（经验证，放路由上），我记得之前版本的Layout在下级路由不显示的情况下不会清空前一个路由的高亮，难道这算是个bug被修复了？:joy: :joy:

**Comment by chenshuai2144** [comment]
应该是某种 bug，现在选中很灵活，你可以写个复现，我们会支持的
