### ISSUE TITLE
🧐[问题]proTable升级新版本后，EditableProTable无法使用index作为判断标准

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/pro-components#1990]
### 🧐 问题描述

1.ProTable升级到2.30之后，EditableProTable和之前一样无法使用index作为唯一值判断。
2.希望能完善下proTable的API，感觉有很多属性在例子中能看到，但是API中没有，谢谢

**Comment by chenshuai2144** [comment]
最好能直接pr，这样最好了
