### ISSUE TITLE
🐛[BUG] ant-design-pro 安装之后无法运行

### ISSUE THREAD

**Issue by excxapp** [ant-design/pro-components#1997]
### 📷 复现步骤
`
Cannot read property 'Provider' of undefined
`

### 🏞 期望结果

期望组件可以正常使用，现在新安装的组建直接无法使用。

### © 版本信息

- ProComponents 版本: 2.24 最新版
- umi 版本 
- 浏览器环境 chrome
- 开发环境 mac OS

`
 "dependencies": {
    "@ant-design/charts": "^0.9.6",
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-descriptions": "^1.2.0",
    "@ant-design/pro-field": "^1.10.1",
    "@ant-design/pro-form": "^1.3.0",
    "@ant-design/pro-layout": "^6.9.0",
    "@ant-design/pro-table": "^2.30.1",
    "@umijs/route-utils": "^1.0.33",
    "antd": "^4.9.4",
    "classnames": "^2.2.6",
    "dva": "^2.4.0",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "qs": "^6.9.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.2.14",
    "umi-request": "^1.0.8"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.0.2",
    "@types/classnames": "^2.2.7",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.144",
    "@types/qs": "^6.5.3",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.4.0",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.1",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-dumi": "^1.1.0-rc.6",
    "@umijs/preset-react": "^1.7.4",
    "@umijs/preset-ui": "^2.2.9",
    "@umijs/yorkie": "^2.0.3",
    "carlo": "^0.9.46",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "enzyme": "^3.11.0",
    "eslint": "^7.1.0",
    "express": "^4.17.1",
    "gh-pages": "^3.0.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.0.1",
    "prettier-plugin-style-order": "^0.2.2",
    "pro-download": "1.0.1",
    "puppeteer-core": "^5.0.0",
    "stylelint": "^13.0.0",
    "typescript": "^4.0.3"
  },
`

**Comment by chenshuai2144** [comment]
升级antd，不要用缓存安装

**Comment by CrassusX** [comment]
解决了么，antd需要升级到什么版本呢，我目前是4.3.3，用Protable显示search就报这个错误，把serach禁用就可以
