### ISSUE TITLE
Module not found: Can't resolve 'antd/es/avatar' in 'C:\path\node_modules\@ant-design\pro-field\es' Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp' 🐛[BUG]

### ISSUE THREAD

**Issue by AnasAlamin** [ant-design/pro-components#1999]
### 🐛 bug 描述
i got this error after installing Pro-descriptions
Module not found: Can't resolve 'antd/es/avatar' in 'C:\path\node_modules\@ant-design\pro-field\es'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
`git clean -dfx` 然后重装依赖。

你的文件系统损坏了
