### ISSUE TITLE
👑 [需求][ProLayout]能否支持左右布局模式

### ISSUE THREAD

**Issue by xiexingen** [ant-design/pro-components#2000]
### 🥰 需求描述

看到vue有一个布局，感觉挺实用的；我们antd也不能缺，看是不是支持一个
如图所示：
![image](https://user-images.githubusercontent.com/7939085/109087549-a389cd80-7748-11eb-83c7-75c44a5b0274.png)

**Comment by chenshuai2144** [comment]
好像有 issue 过，这个 antd 里没有默认样式，就一直没做

**Comment by xiexingen** [comment]
对，也是我提的；但是后面找不到了

**Comment by xiexingen** [comment]
这个还有计划没

**Comment by chenshuai2144** [comment]
准备做了。10月底发布

**Comment by xiexingen** [comment]
> 准备做了。10月底发布

坐等，虽然公司用的vue 但是还是更偏爱react一些

**Comment by chenshuai2144** [comment]
已经支持了，demo中可以看到这个模式
