### ISSUE TITLE
👑 [需求]pro components后续是否可以考虑将样式抽离出来单独引用？

### ISSUE THREAD

**Issue by HEJIN2016** [ant-design/pro-components#2007]
### 🥰 需求描述
pro components后续是否可以考虑将样式抽离出来单独引用。当前pro库自身引用了'~antd/es/style/themes/default.less'。由于项目中原来存在很多直接覆盖ant design的样式，如今再次引用proTable的时候，原先覆盖ant的原始样式，再次被pro包里的原始样式所覆盖，导致项目中原本根本项目不同的UI要求而改过的很多样式变回了ant的原始样式

### 🧐 解决方案
建议能在用户使用pro包的时候，自行引入样式，而不是通过pro自动就把样式引入进来了

**Comment by wangxiaogang94** [comment]
同求

**Comment by chenshuai2144** [comment]
@sorrycc  云谦老师，能不能把 global.less 里面less 最后加载

**Comment by zplzpl** [comment]
这个自己弄的话怎么弄

**Comment by secreter** [comment]
mark

**Comment by AITuring** [comment]
非常需要

**Comment by Liu-Ya** [comment]
@chenshuai2144 没有任何进展吗

**Comment by chenshuai2144** [comment]
再搞 umi-next，没空搞这个，有兴趣你们可以自己搞下

**Comment by chenshuai2144** [comment]
使用了 css in js 现在没有这个问题了
