### ISSUE TITLE
🧐[问题] 在父组件中怎么获取到 QueryFilter 的ref呢 

### ISSUE THREAD

**Issue by Zoe-Lu** [ant-design/pro-components#2008]
![image](https://user-images.githubusercontent.com/77383426/109121103-c7b5d080-7781-11eb-8c0e-dfa397627d72.png)
![image](https://user-images.githubusercontent.com/77383426/109121214-f3d15180-7781-11eb-9f14-01b0f9956a10.png)

**Comment by chenshuai2144** [comment]
ref 好像没传下去，你要ref 做什么？

**Comment by Zoe-Lu** [comment]
想要在父组件中获取到表单的内容

**Comment by chenshuai2144** [comment]
QueryFilter  上面不是有formref 吗？

**Comment by Zoe-Lu** [comment]
嗯， 是这样
但是我想要在 QueryFilter 的父组件里通过 formRef 获取到表单内容

**Comment by chenshuai2144** [comment]
那应该是你自己处理的， QueryFilter formref 肯定是能用的
