### ISSUE TITLE
👑 [需求]可否提供一个带request和翻页的自定义列表渲染组件

### ISSUE THREAD

**Issue by birdycn** [ant-design/pro-components#2009]
protable的request params 和翻页器用着很方便，能否单独抽出这一块的代码，然后允许用户对data内容进行渲染

我想把表格渲染替换成其他组件，比如对评论列表进行渲染

**Comment by chenshuai2144** [comment]
这个是有相关api的。去看看 ProList 是怎么实现的。

https://github.com/ant-design/pro-components/blob/b1b168664ccca70b3a5bf45096f5744e42605a94/packages/list/src/index.tsx#L125-L180

**Comment by birdycn** [comment]
大佬牛逼！！！！！！

**Comment by yotcap** [comment]
> 大佬牛逼！！！！！！

确实
