### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by erichDuanET** [ant-design/pro-components#201]
### 🐛 bug 描述
属性为null、'', valueType非 function时，该单元格展示row的下标index
### 📷 复现步骤

提供一列为空字符的数据

### 🏞 期望结果
正常显示空状态默认的 '-'

### 💻 复现代码
在defaultRender源码中，
```js
/**
 * 根据不同的类型来转化数值
 * @param text
 * @param valueType
 */

var defaultRenderText = function defaultRenderText(text, valueType, index, item, columnEmptyText) {
  if (typeof valueType === 'function' && item) {
    var value = valueType(item);

    if (!value) {
      return columnEmptyText;
    }

    return defaultRenderText(text, value, index);
  }

  return /*#__PURE__*/React.createElement(ProField, {
    text: text || index,
    mode: "read",
    columnEmptyText: columnEmptyText,
    valueType: valueType
  });
};

export default defaultRenderText;
```

 text: text || index,  text为空后，index非0时，columnEmptyText失效，列表显示 2 3 4 5 6.。。

### © 版本信息

- ProComponents 版本:
@ant-design/pro-table@2.5.4

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20224790/90232470-50f15f80-de4f-11ea-8077-d52c8ebac435.png)
![image](https://user-images.githubusercontent.com/20224790/90232545-6ebec480-de4f-11ea-91f3-c83ec5bae064.png)

**Comment by chenshuai2144** [comment]
写 title

**Comment by afc163** [comment]
[如何向开源社区提问题](https://github.com/seajs/seajs/issues/545)

**Comment by erichDuanET** [comment]
写 title是啥意思？

后续版本fix了,如下，就是因为这种问题更新版本库，风险有点高😂
```js
  return /*#__PURE__*/React.createElement(ProField, _extends({}, props, {
    text: valueType === 'index' || valueType === 'indexBorder' ? index : text,
    mode: "read",
    columnEmptyText: columnEmptyText,
    render: undefined,
    renderFormItem: undefined,
    valueType: valueType
  }));
```

**Comment by erichDuanET** [comment]
不好意思，忘了写issue的title了，下次一定注意
