### ISSUE TITLE
🐛[BUG] ProTable 自定义 valueType 同时开启 ellipsis: true 报错 

### ISSUE THREAD

**Issue by SturdyCat** [ant-design/pro-components#2014]
### 🐛 bug 描述

ProTable 自定义 valueType 同时开启 ellipsis: true  报错
以下提供 bug 示例注销 106 行恢复正常

### 🏞 期望结果

工作正常

### 💻 复现代码
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/04pi2?file=/App.tsx)

**Comment by chenshuai2144** [comment]
ellipsis 只能用于 string， tags 是没法用的。

**Comment by SturdyCat** [comment]
@chenshuai2144 
但是我 render 返回的就是字符串

**Comment by chenshuai2144** [comment]
@SturdyCat  renderText 要返回字符串

**Comment by SturdyCat** [comment]
renderText 要返回字符串.
const columns: ProColumns<RecordType>[] = [
    {
      title: '按钮',
      dataIndex: 'tags',
      ellipsis: true,         // 自动溢出省略
      valueType: 'tags', // 自定义 valueType
      hideInSearch: true,
    }
]

```
 <ProProvider.Provider
      value={{
        ...values,
        valueTypeMap: {
          tags: {
            // 这里将 render 改成 renderText 也无效
            renderText: (list) => {
              return list.map((item) => item.label).join(",");
            },
          }
        }
      }}
    >
```

@chenshuai2144  renderText 如何使用
