### ISSUE TITLE
🧐[问题] 为什么 SettingDrawer 要通过查询参数配置呢？

### ISSUE THREAD

**Issue by theprimone** [ant-design/pro-components#2016]
### 🧐 问题描述

如果在生产环境也要使用的话，那会导致 url 很长，给人的感觉很不好 😂 比如：

https://theprimone.top/ant-design-pro-plus/route-tabs-demo/result?id=&query=yes&primaryColor=%231890ff&autoHideHeader=false&fixSiderbar=true&colorWeak=false&pwa=false&routeTabsMode=route&fixedRouteTabs=false&reloadTab=true

### 💻 示例代码

考虑通过 React.Context 解决？

**Comment by chenshuai2144** [comment]
为了方便你copy给别人看样子。主要是为了方便设计师

**Comment by theprimone** [comment]
@chenshuai2144 如果生产环境我也要用这个组件来配置呢？那这样 url 还是不合理吧，还是说自己再实现一个配置功能？

**Comment by chenshuai2144** [comment]
可以来个pr 关掉这个功能

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by theprimone** [comment]
好的，那我试试
