### ISSUE TITLE
👑 【建议】用了pro components,antd没法treeshaking或者external。

### ISSUE THREAD

**Issue by Ives7** [ant-design/pro-components#2024]
### 🥰 需求描述

pro component 引入的antd组件打包后，基本都是如下的形式。
`
import _Checkbox from "antd/es/checkbox";
`

我看了下，是因为自己定制了个babel插件replaceLib，做了类似babel-plugin-import的事情。

这样的话，假设两种场景。

1：如果我只用了webpack的treeshaking，就会导致同样的组件重复打包，因为pro components打包出来的，哪怕是es module产物包，也没有使用tree shaking的语法。antd的包，肯定是客户在引用，所以是否需要babel-plugin-import的功能，应该交给使用者，也就是项目决定。

2：结合实际场景来讲，在antd里引入个table，引入个form，再用个布局，就基本上跟全量引入差距不大了，并且如果利用babel-plugin-import，每次新增的组件不一样，导致vendor chunk重新打包生成hash，失去缓存，其实是得不偿失的。所以如果公司很多web应用都在用antd的话，完全是可以external出去，通过script引入，利用好cdn缓存，还能提升打包效率。如果客户进过A系统，再进B系统，antd的js都不需要重新加载了，因为antd的js被浏览器缓存了。

基于上面的场景，如果使用了antd/es的引入方式，就没法external掉了。因为from "antd"可以被external，但 from "antd/es"无法externl。

无论上述哪种场景，都不会被支持。

### 🧐 解决方案

正常使用es module的导入语法，不要用replaceLib去改ast了。

**Comment by chenshuai2144** [comment]
你把 pro components  也可以 external 掉，转化成es 就是为了自动 treeshaking。如果不这么做不 external  的用户都会打入全量的antd

**Comment by Ives7** [comment]
> 你把 pro components 也可以 external 掉，转化成es 就是为了自动 treeshaking。如果不这么做不 external 的用户都会打入全量的antd

不会的呀，因为antd现在也是支持esm了，可以treeshaking的呀。就是不用全路径引法，而是{}语法？

**Comment by chenshuai2144** [comment]
不编译 node_mouldes 的，所以一定要精确引用

**Comment by fayeah** [comment]
> 

请问可以给一个demo，或者代码片段吗？怎么样external掉呢？我也遇到了这一个问题，pro的组件以及icon全部被打包了。

**Comment by chenshuai2144** [comment]
```
module.exports = {
  //...
  externals: /^(jquery|\$)$/i,
};
```
