### ISSUE TITLE
更新时间显示错误

### ISSUE THREAD

**Issue by jiangqidu** [ant-design/pro-components#2026]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://procomponents.ant.design/components/form](https://procomponents.ant.design/components/form)

### Steps to reproduce
滑动到最底部就行了

### What is expected?
时分秒前面有间隔

### What is actually happening?
间隔取消了

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 16.8 |
| System | window10 |
| Browser | 谷歌 |

**Comment by xrkffgg** [comment]
dumi 1.1.4 修复了

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/109269823-0f9f2b00-7848-11eb-8187-675fa7328952.png)
没错误

**Comment by afc163** [comment]
有问题，重现方式：

1. 进入 https://procomponents.ant.design/components/form ，滚动到底部，此时找不到更新时间。
2. 左侧随便点击另一个菜单项，滚动到底部，此时更新时间出现，日期和时间直接没有空格。

<img width="288" alt="图片" src="https://user-images.githubusercontent.com/507615/109270166-9b18bc00-7848-11eb-9a67-b65a150646e0.png">

**Comment by chenshuai2144** [comment]
升级版本并且重新部署了
