### ISSUE TITLE
👑 [需求]电脑的屏幕很宽，type="form"能不能分2列或者3列显示

### ISSUE THREAD

**Issue by waylon-edmodo** [ant-design/pro-components#203]
### 🥰 需求描述

电脑的屏幕很宽，protable, type="form"能不能分2列或者3列显示

**Comment by chenshuai2144** [comment]
暂时还不支持，正在做了

**Comment by meyerlee** [comment]
输入时数据有很多的关联性，form支持多列布局，如能指定行列号就漂亮了。

**Comment by chenshuai2144** [comment]
@meyerlee 可以来提 pr，或者做一个祥细的 RFC

**Comment by mrhsiang** [comment]
> 暂时还不支持，正在做了
> 
> #211

您好，请问现在是否支持多列了呢？现在确实只有一列显得有点单一

**Comment by mrhsiang** [comment]
> 暂时还不支持，正在做了
> 
> #211
@chenshuai2144 
 您好，请问现在是否支持多列了呢？现在确实只有一列显得有点单一

**Comment by chenshuai2144** [comment]
不支持配置，要自己写代码了。

底层是这个 https://procomponents.ant.design/components/form

**Comment by rdmclin2** [comment]
这个是不是用 `span` 配置就好了

**Comment by lizhongyue248** [comment]
这个是否有考虑支持呢？两个月了

**Comment by chenshuai2144** [comment]
配置 colSize，勉强能支持了

**Comment by chenshuai2144** [comment]
```
 form={{
        span: 12,
      }}
```

可以用这个来配置出来了，但是不支持一个个配置

**Comment by mumashanren** [comment]
> ```
>  form={{
>         span: 12,
>       }}
> ```
> 
> 可以用这个来配置出来了，但是不支持一个个配置

这个似乎只有 search 表单支持， type="form" 设置这个无效。

**Comment by chenshuai2144** [comment]
type="form" 可能要等实现表单 search 的时候才能实现了

**Comment by mumashanren** [comment]
需要江湖救急的同学，可以试试这个
```
.two-col-table-form .ant-row,
.three-col-table-form .ant-row,
.four-col-table-form .ant-row {
    float: left;
    padding-left: 15px;
    padding-right: 15px;
}
.two-col-table-form .ant-row {
    width: 50%;
}
.three-col-table-form .ant-row {
    width: 33.33%;
}
.four-col-table-form .ant-row {
    width: 25%;
}
```
再在 ProTable 上添加 `className="four-col-table-form"`

**Comment by wzwlhc** [comment]
能不能做成一个一个自定义的， 没有自定义的取search对象里面的span 不然响应式colSize实现不了

**Comment by knight-peter** [comment]
请问现在BetaSchemaForm支持分列了吗

**Comment by kalavt** [comment]
请问现在BetaSchemaForm支持分列了吗

**Comment by chenshuai2144** [comment]
`valueType:"group"` 这样搞
