### ISSUE TITLE
🐛[BUG] 在pro-table中，当valueType设置为select，下拉选择中有“全部”字段的key为空字符串，其余为数字时，下拉选项排序有问题

### ISSUE THREAD

**Issue by CrownNight** [ant-design/pro-components#2036]
### 🐛 bug 描述

valueType设置为select，valueEnum:{'': '全部', 1: 1, 2: 2}，此时渲染出来的下拉选项，全部字段会渲染在最后

### 🏞 期望结果

下拉渲染按枚举顺序展示

### 💻 复现代码

column配置
```js
 {
    title: '测试',
    dataIndex: 'test',
    valueType: 'select',
    fieldProps: { placeholder: '测试' },
    initialValue: '',
    valueEnum: {
      '': '全部',
      1: 1,
      2: 2,
      3: 3,
    },
  },
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
<img width="288" alt="测试1" src="https://user-images.githubusercontent.com/32128133/109384269-a7734680-7926-11eb-8289-4a0c17b9b9b8.png">

**Comment by CrownNight** [comment]
![bug](https://user-images.githubusercontent.com/32128133/109384294-cbcf2300-7926-11eb-8b2a-4d3945666199.png)

**Comment by chenshuai2144** [comment]
为什么要这么做？

**Comment by CrownNight** [comment]
> 为什么要这么做？ object是没有顺序的，如果要排序用 array

最后通过request返回一个数组解决了这个问题。
object的for...in 在chrome中是根据key值的parseFloat值为非负整数的属性，然后根据数字顺序对属性排序首先遍历出来，然后按照对象定义的顺序遍历余下的所有属性
 但是文档中valueEnum给人的感觉或者说让人理解的是按用户输入的样子呈现出来，但是实际情况是输入和输出不一致，希望在文档中补充说明一下

**Comment by chenshuai2144** [comment]
这个应该是基本支持，object 是没有顺序的

**Comment by drizzlesconsin** [comment]
> 为什么要这么做？ object是没有顺序的，如果要排序用 array

@chenshuai2144 

使用数组
```ts
valueEnum: [
  { text: '是', value: 1 },
  { text: '否', value: 0 },
]
```

`value` 似乎没有用到

https://github.com/ant-design/pro-components/blob/423f4761eecde5a62c4a8476441aa0484ff94711/packages/field/src/components/Select/index.tsx#L170-L191

**Comment by chenshuai2144** [comment]
valueEnum 不支持数组，要用 options
