### ISSUE TITLE
🧐[问题]@ant-design/pro-layout v5到v6有破坏性的更新吗？

### ISSUE THREAD

**Issue by HarveyZgit** [ant-design/pro-components#2038]
### 🧐 问题描述

@ant-design/pro-layout v5和v6有破坏性的更新吗？之前的项目里使用了v5的版本，而且用的地方比较多。如果直接升级v6版本，成本会很大吗？

### 🚑 其他信息

PageContainer 看起来挺不错的，想用~

**Comment by chenshuai2144** [comment]
有的 样式变化很大 你可以试试

**Comment by HarveyZgit** [comment]
> 有的 样式变化很大 你可以试试

样式变化还好，主要是有没有API的更替呢？

**Comment by chenshuai2144** [comment]
没有变更，只有新增
