### ISSUE TITLE
🐛[BUG]ProFormFieldSet的transform属性如何使用

### ISSUE THREAD

**Issue by yandt** [ant-design/pro-components#2042]
### 🐛 bug 描述

```
<ProFormFieldSet label="显示行数" name="autoSize" transform={(value: any) => ({ minRows: value[0], maxRows: value[1] })}>
                        <ProFormDigit placeholder="最小行数"/>
                        <ProFormDigit placeholder="最大行数"/>
                    </ProFormFieldSet>
```

transform并不调用，使用过程中还会报错！
react-dom.development.js:4091 Uncaught TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个详细报错，这个看起来不是我们的，是你把一个对象当成数组处理了

**Comment by liangxp** [comment]
同样transform配置后无任何无效果，但也没报错！

**Comment by hhlcom** [comment]
我是在线编译没问题，打包字段没了

**Comment by hhlcom** [comment]
> 来个详细报错，这个不是我们的，是你把一个对象当成数组处理了
![image](https://user-images.githubusercontent.com/71809799/126253376-bef701c1-2dac-4b40-971b-75d9e4e39ea1.png)

数组不是官网这么写的么
