### ISSUE TITLE
🧐[问题]protable滚动的时候，能否自动更新url的hash部分

### ISSUE THREAD

**Issue by ccloveak** [ant-design/pro-components#2045]
### 🧐 问题描述
protable滚动的时候，能否自动更新url的hash部分 
需求是从详情页按浏览器的back按钮也能跳转到列表页的相关内容

### 🚑 其他信息

类似这个网站 [javalin](https://javalin.io/documentation#access-manager)

**Comment by chenshuai2144** [comment]
这个需要自己实现了，一般人不用的。

试试这个库，实现起来超简单

https://github.com/rudyhuynh/use-url-search-params

**Comment by ccloveak** [comment]
> 这个需要自己实现了，一般人不用的。
> 
> 试试这个库，实现起来超简单
> 
> https://github.com/rudyhuynh/use-url-search-params

好人呐 谢谢谢谢谢🙏
