### ISSUE TITLE
[BUG]引用pro-table时，antd的menu样式出现异常

### ISSUE THREAD

**Issue by wangxiaogang94** [ant-design/pro-components#2049]
直接复制了demo的代码进来，就导致了样式异常如图
<img width="197" alt="6926EFE0-D175-427F-82E4-83153A7DA2B6" src="https://user-images.githubusercontent.com/51105411/109462790-fa700980-7a9e-11eb-801e-60aff76cf669.png">

**Comment by chenshuai2144** [comment]
估计是antd 版本混用了，黑色主题容易出这个问题。
