### ISSUE TITLE
🐛[BUG]ProFormSelect options 没有及时刷新

### ISSUE THREAD

**Issue by bowencool** [ant-design/pro-components#2052]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/20217146/109474631-ac173680-7aaf-11eb-8d8d-6918723984fd.png)

### 📷 复现步骤

``` jsx
    <ProFormSelect
      width="md"
      options={gitlabUsers?.map((u) => ({ value: u.id, label: u.name })) || []}
      name="assignee_id"
      label="跟进人"
      fieldProps={{
        allowClear: true,
        showSearch: true,
        filterOption: false,
        onSearch,
        loading,
        // children: (
        //   <>
        //     {gitlabUsers?.map((u) => (
        //       <Select.Option key={u.id} value={u.id}>{u.name}</Select.Option>
        //     ))}
        //   </>
        // ),
      }}
      rules={[
        {
          required: true,
          message: '请选择跟进人',
        },
      ]}
    />
```

### 🏞 期望结果

@ant-design/pro-form@1.6.1是好的，1.16.1是坏的，不知道哪个具体版本出来的

### © 版本信息

- ProComponents 版本: @ant-design/pro-form@1.16.1
- umi 版本 3.3.9
- 浏览器环境 `Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36`
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

当组件blur再focus（popover消失再出现），是会更新的。但这样就丢失了搜索关键词及搜索结果。

**Comment by chenshuai2144** [comment]
试试 1.16.3 ，最近有个bug，导致覆盖了不少默认值。


可以执行 git clean -dfx ，来保证肯定更新到了

**Comment by chenshuai2144** [comment]
代码给全一下，gitlabUsers 更新是不是没有触发useState。

我试了一下是可以的

**Comment by bowencool** [comment]
好麻烦，可以帮我解决下这个吗，https://codesandbox.io/s/pensive-kepler-4s4ky?file=/src/App.js

**Comment by chenshuai2144** [comment]
因为没法复现，所以比较麻烦

**Comment by oxygen-xx** [comment]
@chenshuai2144   @ant-design/pro-form 1.20.0 都没有解决这个问题，这个确实比较紧急。

**Comment by chenshuai2144** [comment]
filterOption 设置成 false。

设置了 onSearch 会自带一个filter

**Comment by liuzhenji** [comment]
> 个filt

我也遇到这个问题了。好像就是filterOption的问题，但是设置fieldProps.filterOption并没有用，还是会filter
