### ISSUE TITLE
🐛[BUG] ProFormDigit rules不生效

### ISSUE THREAD

**Issue by kzcPo** [ant-design/pro-components#2053]
### 🐛 bug 描述

ProFormDigit rules不生效。重写validator方法，传入callback，界面上未显示提示信息，控制台有信息。

### 💻 复现代码

```
const validatorDigit = (rule: any, value: any, callback: (message?: string) => void) => {
    console.log(">>>> validatorDigit", rule, value)
    if (value === undefined) {
      callback('请输入时间');
    } else {
      callback();
    }
  };

return (
     <ProForm
        form={form}
        onFinish={onFinish}
      >
        
          <ProFormDigit
            name={"interval"}
            noStyle
            width={80}
            min={0}
            rules={[{ required: true, validator: validatorDigit }]}
          />
    </ProForm>
)
```

### © 版本信息

- "@ant-design/pro-form": "^1.16.3"
- umi 版本 3.3.9
- 浏览器环境 88.0.4324.96（正式版本） (x86_64)
- 开发环境 mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/16077203/109488396-79296e80-7ac0-11eb-9c40-bb5df31aad3f.png)
![image](https://user-images.githubusercontent.com/16077203/109488471-92cab600-7ac0-11eb-99da-c73e77b6d1f0.png)

**Comment by chenshuai2144** [comment]
antd@4 不是这么用的，要用 promise 来实现，而不是用 callback
