### ISSUE TITLE
🐛[BUG] ProFormItem Focus to another Form Item After Hover 表单栏在光标移动后聚焦到另一个表单栏

### ISSUE THREAD

**Issue by yanglu758** [ant-design/pro-components#2059]
### 🐛 bug 描述

Suppose I have 2 Form Items "Name" and "Username". I key in some information into the field "Username". I use cursor to select the information I just keyed in in the field "Username". While I'm selecting "Username" with my cursor, I accidentally move my cursor to the neighbouring field "Name". As a result, the Name field become focused and I just lost all the selected text in "Username".
假设两个表单栏“姓名”和"用户名”在同一行里。我在”用户名“栏里输入信息，我想用光标全选我刚填的“用户名”内容然后复制黏贴，但是我的光标我不小心移到隔壁的”姓名“栏里，结果”姓名“栏被聚焦，我的全选也没了。

### 📷 复现步骤
Select all text in one field and move cursor to another field without releasing the mouse key.
全选一个表单栏里的内容时将光标移动到旁边的表单栏。

### 🏞 期望结果
当用户全选一个表单栏的内容时不小心移动光标到另一个表单栏时，聚焦应该还在原来的表单栏而不应该自动把聚焦移到另一个表单栏。
When User is selecting content in one Form Field while accidentally moving the cursor to the neighbouring field, the focus should still be in the original Form Field instead of automatically changing the focus to the neighbouring field.

### 💻 复现代码

Can replicate in Documentation page Ant Pro Components at https://procomponents.ant.design/components/form#layouts-api.
可以在 https://procomponents.ant.design/components/form#layouts-api 这里找到这个问题。

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![Capture](https://user-images.githubusercontent.com/12844206/109583306-d1f61700-7b53-11eb-80a4-1540a6fd675f.JPG)

**Comment by chenshuai2144** [comment]
你这是两个框的name相同导致的。他们两个id生成的都一样。

name 最好不要重复

**Comment by yanglu758** [comment]
Protable Column API 里没有name这个配置啊。
如果你说的是data index, 我的dataIndex都不一样
```
{
      title: 'ID',
      dataIndex: 'id',
      hideInForm: true,
      editable: false,
      sorter: true,
      width: "2.5%"
    },
    {
      title: 'Name',
      dataIndex: 'name',
      sorter: true,
      editable: true,
      tooltip: "Use % for contains (LIKE) search.",
      formItemProps: {
        rules: [{ required: true, message: 'Please enter this field!' }]
      },
      width: "7.5%"
    },
```
