### ISSUE TITLE
👑 [需求]pro-layout组件中,希望可以加入展开目录树的回调函数

### ISSUE THREAD

**Issue by PluviaCon** [ant-design/pro-components#206]
### 🥰 需求描述
在`antd` 的 `tree`组件中,就有`onExpand` 和 `onSelect` 方法来提供回调函数,而在`pro-layout`就没有相应的方法
具体来说,在`pro-layout`生成的树节点里,只能根据已有的`route`来生成,而不可以只点击树节点右侧的箭头展开来异步获取

### 🧐 解决方案

可以考虑`antd` `tree`组件的回调方式实现一下

### 🚑 其他信息
![antdtree回调](https://user-images.githubusercontent.com/42147639/90252435-13ea9480-de72-11ea-90b9-2b62359f40ce.png)

**Comment by chenshuai2144** [comment]
```
 handleOpenChange?: (openKeys: string[]) => void;
  openKeys?: WithFalse<string[]> | undefined;
```
有这个的。

**Comment by PluviaCon** [comment]
> ```
>  handleOpenChange?: (openKeys: string[]) => void;
>  openKeys?: WithFalse<string[]> | undefined;
> ```
> 
> 有这个的。

我只找到了`menuProps`里的[onOpenChange](https://3x.ant.design/components/menu-cn/#Menu)方法,你说的那个能举个例子吗?

**Comment by PluviaCon** [comment]
在源码里,他们是不是指向同一个方法?
![选区_009](https://user-images.githubusercontent.com/42147639/90310766-46a29480-df27-11ea-91bd-cb5b489c3a1a.png)

**Comment by chenshuai2144** [comment]
是个别名，可以只在 layout 上配置
