### ISSUE TITLE
🐛[BUG] ProFormDigit 组件 设置最小值30 第一次输入7，会自动填充为30

### ISSUE THREAD

**Issue by wangyongsong** [ant-design/pro-components#2060]
### 🐛 bug 描述

ProFormDigit 组件 min={30} 第一次输入7（小于30的），会自动填充为30

### 📷 复现步骤

```js
        <ProFormDigit
          width="sm"
          label="任务截止时间进度"
          name="deadlinePercent"
          min={30}
          max={90}
        />
```

### 🏞 期望结果

输入框失去焦点的时候，进行格式化操作

### © 版本信息

- "@ant-design/pro-form" "1.16.3"
- 浏览器环境  chrome
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![Mar-02-2021 10-17-41](https://user-images.githubusercontent.com/58172091/109586948-3491e780-7b41-11eb-81f8-8d35ce9c670d.gif)

**Comment by wangyongsong** [comment]
描述补充： 如果用户想输入的是70，当输入7的时候就自动变为30

**Comment by chenshuai2144** [comment]
antd 修改了格式化的时机

**Comment by wangyongsong** [comment]
```js
              <ProFormDigit
                width="sm"
                label="任务截止时间进度（%）"
                name="deadlinePercent"
                min={30}
                max={90}
                validateTrigger={['onBlur']}
              />
```
我修改了校验方式，`validateTrigger={['onBlur']}`还是不行， 有什么方法吗

**Comment by chenshuai2144** [comment]
等我具体debug一下修修

**Comment by chenshuai2144** [comment]
更新一下依赖吧。antd 更新以后性能就好了
