### ISSUE TITLE
👑 [需求] EditableProTable中设置某列valueType为'select'型，valueEnum的Key希望除了String外支持其他类型，比如数字和布尔型

### ISSUE THREAD

**Issue by ibryanwu** [ant-design/pro-components#2063]
### 🥰 需求描述
EditableProTable中设置某列valueType为'select'型，valueEnum的Key希望除了String外支持其他类型

因为很多时候，数据的值（比如id）是数字型，这时column中的valueEnum下拉key只能是String就很难受，接口的赋值和取值还要再转换一遍非常麻烦
### 🧐 解决方案
能不能key支持可以是数字或布尔型就方便多了

### 🚑 其他信息
interface IValueEnum {
  [key: string]:--------------------支持数字和布尔型
    | ReactNode
    | {
        text: ReactNode;
        status: 'Success' | 'Error' | 'Processing' | 'Warning' | 'Default';
      };
}

谢谢

**Comment by chenshuai2144** [comment]
用Map 就可以，object 的 key 只能是string

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Map
