### ISSUE TITLE
🧐[问题] ProFormSelect 如何展示一个OptGroup

### ISSUE THREAD

**Issue by qiaodaima** [ant-design/pro-components#2066]
### 🧐 问题描述
`ProFormSelect ` 的下拉选项 需要分组，
不知数据格式是怎么样的

**Comment by SeanBurt** [comment]
> ### 🧐 问题描述
> `ProFormSelect ` 的下拉选项 需要分组，
> 不知数据格式是怎么样的
> 
> ### 💻 示例代码
> ### 🚑 其他信息

你这个问题解决了吗？

**Comment by SeanBurt** [comment]
这个问题解决了？

**Comment by qiaodaima** [comment]
> 这个问题解决了？

这个问题我还没解决，我用了 `antd` 的 OptGroup 来先代替下

**Comment by chenshuai2144** [comment]
还没发布，发布了就可以用了
