### ISSUE TITLE
🧐[问题] PageContainer 包裹的区域有一个24间隔，如何更改

### ISSUE THREAD

**Issue by kiwikaki** [ant-design/pro-components#2068]
![QQ截图20210302172757](https://user-images.githubusercontent.com/5789944/109627774-edc1e300-7b7c-11eb-9733-518a3cd68e6d.png)

**Comment by chenshuai2144** [comment]
这个 PageContainer  的设计，只能通过覆盖css的方式去除，如果只是一个页面需要去掉，推荐 

`margin:-24px`

**Comment by kiwikaki** [comment]
> 这个 PageContainer 的设计，只能通过覆盖css的方式去除，如果只是一个页面需要去掉，推荐
> 
> `margin:-24px`

明白了，后期可不可以加个card组件那样的bodyStyle 配置
