### ISSUE TITLE
[需求]pro-table 搜索表单 收起状态时，通过formRef操作表单只能操作展示出来部分的表单

### ISSUE THREAD

**Issue by DeyuanTan** [ant-design/pro-components#207]
### 🐛 bug 描述

pro-table 搜索表单 收起状态时，通过formRef操作表单只能操作展示出来部分的表单

### 📷 复现步骤

1、ProTable组件，默认收起状态展示3个搜索条件
2、通过formRef 得到form实例
3、**展开** 搜索表单。此时 formRef.current.getFieldsValue  可以获取整到整个表单的值
4、**收起** 搜索表单。此时 formRef.current.getFieldsValue 只能获取到部分表单的值。

### 🏞 期望结果

在 **收起** 搜索表单时，能操作整个表单，而不是只展示出来的部分

需求背景：
首次进入页面时表单 默认值需要从URL上获取。
但是点击重置时需要把这些值清除
在onReset中试图通过 setFieldsValue设置搜索表单的值，发现只有在**展开**状态下能设置。

### 💻 复现代码
用的是antd-pro中的示例

![image](https://user-images.githubusercontent.com/8966624/90303745-2ea92180-dee3-11ea-9c9c-3b3a2c4a2e55.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 3.x
- 浏览器环境 Chrome
- 开发环境 [mac OS]

### 🚑 其他信息
 **展开状态运行效果**
![image](https://user-images.githubusercontent.com/8966624/90303768-6b751880-dee3-11ea-9b1a-db91b2212ef7.png)
**收起状态结果**
![image](https://user-images.githubusercontent.com/8966624/90303786-919ab880-dee3-11ea-9fec-240a0c245755.png)

**Comment by chenshuai2144** [comment]
因为这个表单已经不存在了
