### ISSUE TITLE
🐛[BUG] 使用 ProTable type=form 时 上传文件类型的值有问题

### ISSUE THREAD

**Issue by ChenWeihua123** [ant-design/pro-components#2071]
### 🐛 bug 描述
使用的依赖都是当前最新版本

如果是字段中的值是单个 File 文件 则 onSubmit 中可以正常获取到 File 对象
如果用数组包裹上 File 文件 则 onSubmit 中的返回值中 该数据中的值都是空对象

截图：
通过 Upload 组件生成的文件
![image](https://user-images.githubusercontent.com/33150900/109673036-950c3d80-7bb0-11eb-81ff-c8be54cc0b28.png)
自己 new File 创建的 File 文件
![image](https://user-images.githubusercontent.com/33150900/109673199-bec56480-7bb0-11eb-8f02-db28b0d13ae5.png)

不使用数组包裹 可正常获取到
![image](https://user-images.githubusercontent.com/33150900/109673339-e61c3180-7bb0-11eb-9526-aa4c3f9424ea.png)

### 📷 复现步骤

使用 antd 的 Upload 组件获取 file 或者是自己创建的File 文件 然后手动 onChange 到 form 中

### 🏞 期望结果

需要同时拿到多个文件，所有需要 array 类型，怎样才能获取到 File 文件

### © 版本信息

- ProComponents 版本: 最新版本
- umi 版本
- 浏览器环境 新版Edge
- 开发环境 [windows 10]

**Comment by ChenWeihua123** [comment]
同样的操作在老版本中是没有问题的
ProTable@2.11.4
ProForm@1.6.2

**Comment by ChenWeihua123** [comment]
我确认了一下 是 pro-utils 的问题， 是这里处理的问题
但是小弟不知道怎么改，还望大神们帮忙看下~~

```typescript
/**
 * 这里主要是来转化一下数据 将 moment 转化为 string 将 all 默认删除
 *
 * @param value
 * @param dateFormatter
 * @param proColumnsMap
 */
const conversionSubmitValue = <T = any>(
  value: T,
  dateFormatter: DateFormatter,
  valueTypeMap: Record<string, any>,
  omitNil?: boolean,
  parentKey?: string[],
): T => {
  const tmpValue = {} as T;
  // 如果 value 是 string 或者null，直接返回
  if (typeof value !== 'object' || isNil(value)) {
    return value;
  }

  Object.keys(value).forEach((key) => {
    const namePath = parentKey ? [parentKey, key].flat(1) : [key];
    const valueType = get(valueTypeMap, namePath) || 'text';
    const itemValue = value[key];
    if (isNil(itemValue) && omitNil) {
      return;
    }
    // 处理嵌套的情况
    if (
      isPlainObject(itemValue) &&
      // 不是数组
      !Array.isArray(itemValue) &&
      // 不是 moment
      !moment.isMoment(itemValue)
    ) {
      tmpValue[key] = conversionSubmitValue(itemValue, dateFormatter, valueTypeMap, omitNil, [key]);
      return;
    }
    // 处理 FormList 的 value
    if (Array.isArray(itemValue)) {
      tmpValue[key] = itemValue.map((arrayValue, index) => {
        if (moment.isMoment(arrayValue)) {
          return conversionMoment(arrayValue, dateFormatter, valueType);
        }
        return conversionSubmitValue(arrayValue, dateFormatter, valueTypeMap, omitNil, [
          key,
          `${index}`,
        ]);
      });
      return;
    }
    tmpValue[key] = conversionMoment(itemValue, dateFormatter, valueType);
  });
  return tmpValue;
};
```

**Comment by chenshuai2144** [comment]
来个重现 demo，让大家试试

**Comment by ChenWeihua123** [comment]
我做了一个简单的判断, 判断 value 是否是 Blob 类型
我传入的是数组类型的值 File[]，所以第一次会走到 Array.isArray 这里
![微信图片_20210304102842](https://user-images.githubusercontent.com/33150900/109911583-4e6c2f80-7ce5-11eb-94ad-707f6c488535.png)
