### ISSUE TITLE
🧐[问题] table column setting 拖拽图标有歧义

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/pro-components#2083]
### 🧐 问题描述

现在拖拽图标是无法响应拖动的，给人一种反直觉，甚至有悬停鼠标的变化

### 💻 示例代码

![image](https://user-images.githubusercontent.com/37258382/109915887-95f6b980-7ced-11eb-8084-c8a78d65a22d.png)

**Comment by azcdazq** [comment]
现在我想显示怎么设置呢

**Comment by blueman-lsl** [comment]
> 

可以显示了吗。
