### ISSUE TITLE
🧐[问题]defaultSettings的配置会被显示在URL中,能够不在URL中显示吗？

### ISSUE THREAD

**Issue by kevin-penn** [ant-design/pro-components#2085]
### 🧐 问题描述
defaultSettings的配置会被显示在URL中，如下，能够不在URL中显示吗？

http://localhost:8000/dashboard/analysis?navTheme=light&primaryColor=%23009926&layout=mix&fixedHeader=true&fixSiderbar=true&colorWeak=false&title=Test&pwa=false

### 期望效果
http://localhost:8000/dashboard/analysis

**Comment by chenshuai2144** [comment]
来个 pr 吧，让可以关掉这个效果
