### ISSUE TITLE
🧐[问题] ProFormText 和 ProFormCaptcha 输入框表现不一致

### ISSUE THREAD

**Issue by senique** [ant-design/pro-components#2087]
### 🧐 ProFormText 和 ProFormCaptcha 输入框表现不一致，求推荐更好的方法，谢谢
  如图相同宽度的 ProFormText 比 ProFormCaptcha 要少显示一个字。
 
尝试：
- ProFormText 设置 suffix 如下无效，也没有找到可以去掉默认 suffix的方法
`
<ProFormText  
    fieldProps={{  
      suffix: undefined  
    }}  
  ...  
`
- ProFormCaptcha 设置 suffix 如下，可以和 ProFormText 保持显示一致
`
<ProFormCaptcha  
    fieldProps={{  
      suffix: <span>&nbsp;&nbsp;&nbsp;</span>,  
    }}   
  ...  
`

### 🚑 截图

![ProFormCaptcha_ProFormText](https://user-images.githubusercontent.com/11310116/109928871-dc094880-7d00-11eb-848d-662c9f79a988.png)

**Comment by chenshuai2144** [comment]
这个是 allowClear 导致的，你把 allowClear 关掉。
不是 suffix  的原因
