### ISSUE TITLE
🐛[BUG] ProDescriptions 当valueType为Select且字段值为number时，默认选中异常。

### ISSUE THREAD

**Issue by vegawong** [ant-design/pro-components#2088]
### 🐛 bug 描述

ProDescriptions 当valueType为Select且字段值为number时，进入编辑模式时，select组件默认选中异常。

### 📷 复现步骤

1. 声明一个column的valuType为select, valueEnum为{1: '男', 2: '女'},  key为'sex'
2. 声明dataSource为{sex: 1}
3. 打开ProDescriptions的editable
4. 点击字段进入编辑

### 🏞 期望结果

当字段值类型是number时，编辑时可以正常显示默认选中值。

### 💻 复现代码

codesanbox: https://codesandbox.io/s/sweet-bas-jupis?file=/src/App.js

### © 版本信息

- ProComponents 版本: @ant-design/pro-descriptions@1.6.3
- umi 版本: 无
- 浏览器环境：chrome
- 开发环境 任意

**Comment by chenshuai2144** [comment]
这个日经问题了，object 的 key 只是是 stirng，要解决问题就用 Map，或者自己转化一下。

**Comment by iloveip** [comment]
Hi @vegawong 
I have the same problem. How did you fix this?

**Comment by chenshuai2144** [comment]
This is a Nikkei problem. The key of the object is just stirng. To solve the problem, use Map, or transform it yourself.

**Comment by KingAmo** [comment]
use Map like this:
```
valueEnum: new Map([
   [0, '男'],
   [1, '女'],
 ]),
```
