### ISSUE TITLE
🧐[问题]react lowercase warning 

### ISSUE THREAD

**Issue by csc-bo** [ant-design/pro-components#2094]
### 🧐 问题描述
更新pro-table版本之后, console 出现了warning，不知道是不是正常的

index.js:1 Warning: React does not recognize the `valueEnum` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `valueenum` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in input (created by InputNumber)
    in div (created by InputNumber)
    in div (created by InputNumber)
    in InputNumber (created by ForwardRef)
    in ForwardRef (created by ForwardRef(FieldMoney))
    in ForwardRef(FieldMoney) (created by ForwardRef(ProField))
    in ForwardRef(ProField) (created by ProFormField)
    in ProFormField (created by FieldWithContext)
    in LightWrapper (created by FieldWithContext)
    in Unknown
    in Unknown (created by Field)
    in div (created by FormItemInput)
    in div (created by FormItemInput)
    in div (created by Col)
    in Col (created by FormItemInput)
    in FormItemInput (created by Field)
    in div (created by Row)
    in Row (created by Field)
    in Field (created by WrapperField)
    in WrapperField (created by FormItem)
    in FormItem (created by FieldWithContext)
    in FieldWithContext (created by FormSearch)
    in div (created by Row)
    in Row (created by QueryFilterContent)
    in QueryFilterContent (created by BaseForm)
    in form (created by ForwardRef(Form))
    in ForwardRef(Form) (created by ForwardRef(InternalForm))
    in SizeContextProvider (created by ForwardRef(InternalForm))
    in ForwardRef(InternalForm) (created by BaseForm)
    in ConfigProviderWrap (created by BaseForm)
    in BaseForm (created by QueryFilter)
    in ResizeObserver (created by QueryFilter)
    in QueryFilter (created by FormSearch)
    in div (created by FormSearch)
    in FormSearch (created by ProTable)
    in div (created by ProTable)
    in ProTable (created by ProviderWarp)
    in ErrorBoundary (created by ProviderWarp)
    in ConfigProviderWrap (created by ProviderWarp)
    in Provider (created by ProviderWarp)
    in ProviderWarp (at purSta/index.js:86)
    in ProductList (at routes.js:57)
    in Outlet (at layout/index.js:84)
    in main (created by Basic)
    in Basic (created by Content)
    in Content (created by WrapContent)
    in FormProvider (created by ProviderChildren)
    in LocaleProvider (created by ProviderChildren)
    in ProviderChildren (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (created by Context.Consumer)
    in ConfigProviderWrap (created by WrapContent)
    in WrapContent (created by BasicLayout)
    in div (created by BasicLayout)
    in section (created by BasicLayout)
    in BasicLayout (created by Layout)
    in Layout (created by BasicLayout)
    in div (created by BasicLayout)
    in Provider (created by BasicLayout)
    in BasicLayout (at layout/index.js:52)
    in Navbar (at routes.js:52)
    in header (at App.js:12)
    in div (at App.js:11)
    in App (at src/index.js:11)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:10)

**Comment by chenshuai2144** [comment]
fixed，publish will on Monday
