### ISSUE TITLE
🐛[BUG] EditableProTable如果rowKey对应的值是字符串类型时，实际保存的编辑表格会出现错误

### ISSUE THREAD

**Issue by blackraindrop** [ant-design/pro-components#2095]
### 🐛 bug 描述

根据官网案例修改id从number类型换成string类型，每编辑一下会额外出现两行数据

重现地址 https://codesandbox.io/s/shishibaocundebianjibiaoge-forked-epznm

```typescript
const defaultData: DataSourceType[] = [
  {
    id: "624748504",
    title: "活动名称一",
    decs: "这个活动真好玩",
    state: "open",
    created_at: "2020-05-26T09:42:56Z"
  },
  {
    id: "624691229",
    title: "活动名称二",
    decs: "这个活动真好玩",
    state: "closed",
    created_at: "2020-05-26T08:19:22Z"
  }
];
```

![image](https://user-images.githubusercontent.com/1668029/109988979-054ac880-7d43-11eb-9852-86a8a3eb3dad.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
不要用 number string，直接用 string 或者 number

**Comment by blackraindrop** [comment]
服务端返回字符串类型的id 这个是一个很正常的需求吧。而且既然是字符串，就不需要在乎字符串里面是不是数字，主要问题是里面强转导致的。

**Comment by chenshuai2144** [comment]
这个也是最麻烦的点，要么转化，要么完成不支持 number

**Comment by blackraindrop** [comment]
现在就算是字符串 “a” , "b" 当rowKey 也同样问题

**Comment by blackraindrop** [comment]
@chenshuai2144 
utils/useEditableArray 中
```TypeScript
export type RecordKey = React.Key | React.Key[];
```
定义RecordKey的作用是什么？为什么会出现React.Key[] 数组这种情况？

![image](https://user-images.githubusercontent.com/1668029/110342270-2a527a80-8066-11eb-9844-6c32ccfe29e0.png)

类似这里startEditable 接受的是React.Key，而cancelEditable接受的是RecordKey。

我理解这里的recordKey应该就是rowKey，rowKey的类型应该只会是React.Key。


![image](https://user-images.githubusercontent.com/1668029/110342535-7ac9d800-8066-11eb-87ad-50d56bef4b2f.png)
这里如果使用的是Map，那么它的键就不仅仅可以是string了，也可以放number进去，导致{"1":  xxx, 1: xxx}会共存。

第一种方案：去掉toNumber以及recordKeyToString使用的地方，kvMap都用string 类型作为key。
![image](https://user-images.githubusercontent.com/1668029/110343016-02afe200-8067-11eb-9d5e-f327f3514910.png)
![image](https://user-images.githubusercontent.com/1668029/110343069-13605800-8067-11eb-9f2d-223eaebb02e7.png)

第二种方案：是否能使用Form.List的方式，这样就不需要用rowKey作为对象的key，然后在反向转回数组。
