### ISSUE TITLE
🐛[BUG] ProTable表格列的筛选下拉菜单会跟着父元素Content区域滚动

### ISSUE THREAD

**Issue by wood3n** [ant-design/pro-components#2105]
### 🐛 bug 描述

ProTable表格列的筛选下拉菜单会跟着父元素Content区域滚动

### 💻 复现代码

[![Edit 查询表格 (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/chaxunbiaoge-forked-dl9sh?fontsize=14&hidenavigation=1&theme=dark)

### © 版本信息

- ProTable 版本: latest

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/31716713/110072890-7331d700-7db9-11eb-8f98-a09c29cee4ae.png)

**Comment by chenshuai2144** [comment]
antd 的常规问题。注意一下滚动条。解决办法是配置 configProvide 


getPopupContainer | To set the container of the popup element. The default is to create a div element in body | function(triggerNode) | () => document.body |  
-- | -- | -- | -- | --
getTargetContainer | Config Affix, Anchor scroll target container | () => HTMLElement | () => window | 4.2.0
