### ISSUE TITLE
ProTable如何保持搜索状态【包括PageSize和PageNum】（从详情返回列表）

### ISSUE THREAD

**Issue by lichangchao15442** [ant-design/pro-components#2109]
### 🥰 需求描述
从详情返回列表时，如何保持上一次的搜索条件。我知道可以通过
路由传参，但是目前似乎只能保持搜索条件的状态，对于PageSize和PageNum还是会回到初始值。
### 🧐 解决方案
有尝试过使用umi-plugin-keep-alive插件，但是包裹ProTable组件之后会报错。

**Comment by yacolin** [comment]
可以用参考[useAntdTable](https://ahooks.js.org/zh-CN/hooks/table/use-antd-table/)  的数据缓存得到这种效果，不过这样就用不到ProTable的request，直接用dataSource绑定，代码实例可参考[demo](https://codesandbox.io/s/trusting-wind-q4sni?file=/src/components/index.js)。
不过目前ProTable更新到2.30.5  会出现获取不到ProTable的formData的情况，该情况下我的解决方案是ProTable切回到了2.13.3
具体可见该[issue](https://github.com/ant-design/pro-components/issues/2173)

**Comment by yacolin** [comment]
在日常开发中，保留了pageSize和pageNum的情况下，都会再去保留搜索表单数据的。
目前自己所用的方案是搭配  useAntdTable来实现的，但是ProTable@2.14.0开始 formData获取不到，详情可见该 [issue](https://github.com/ant-design/pro-components/issues/2173)

**Comment by dengshicheng1996** [comment]
> ### 🥰 需求描述
> 从详情返回列表时，如何保持上一次的搜索条件。我知道可以通过
> 路由传参，但是目前似乎只能保持搜索条件的状态，对于PageSize和PageNum还是会回到初始值。
> 
> ### 🧐 解决方案
> 有尝试过使用umi-plugin-keep-alive插件，但是包裹ProTable组件之后会报错。
> 
> ### 🚑 其他信息

是否解决了？

**Comment by lichangchao15442** [comment]
> > ### 🥰 需求描述
> > 从详情返回列表时，如何保持上一次的搜索条件。我知道可以通过
> > 路由传参，但是目前似乎只能保持搜索条件的状态，对于PageSize和PageNum还是会回到初始值。
> > ### 🧐 解决方案
> > 有尝试过使用umi-plugin-keep-alive插件，但是包裹ProTable组件之后会报错。
> > ### 🚑 其他信息
> 
> 是否解决了？

解决了，是umi-plugin-keep-alive插件的问题，这个插件升级导致的报错，降低一下版本就可以了。我用的这个    "umi-plugin-keep-alive": "0.0.1-beta.21",
