### ISSUE TITLE
🐛[BUG] ProFormSelect加上.SearchSelect后initialValues无效

### ISSUE THREAD

**Issue by huangkaibo** [ant-design/pro-components#2110]
### 🐛 bug 描述

使用`<ProFormSelect>`时, initialValues有效
改为`<ProFormSelect.SearchSelect>`后, initialValues无效

### 📷 复现步骤

增删.SearchSelect可以看到效果

### 🏞 期望结果

`<ProFormSelect.SearchSelect>`也支持initialValues

### 💻 复现代码

https://codesandbox.io/s/antd-reproduction-template-forked-gkq32?file=/index.js

### © 版本信息

- ProComponents 版本: pro-form 1.16.3

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/19745373/110088760-3e7d4a00-7dd0-11eb-9188-33ab09a254bf.png)

**Comment by chenshuai2144** [comment]
SearchSelect 默认打开了 lableInValue，你可以关掉之后再用这种方式使用。
