### ISSUE TITLE
👑 [需求] ProColumns 的 valueType: 'select' 能否支持参数showSearch

### ISSUE THREAD

**Issue by kzcPo** [ant-design/pro-components#2112]
### 🧐 问题描述

ProColumns 的 valueType: 'select' 能否支持参数showSearch，
select 标签有参数showSearch 可以支持搜索，但ProTable的ProColumns 好像不支持这个参数，能否增加下支持。

**Comment by chenshuai2144** [comment]
用 filedProps配置就能使用

**Comment by ZhengHuang-20** [comment]
> filedProps

怎么配置能否说一下没找到文档

**Comment by chenshuai2144** [comment]
你搜一下 demo。

![image](https://user-images.githubusercontent.com/8186664/112249863-740ca900-8c93-11eb-8ce6-5d49e4835812.png)

**Comment by kzcPo** [comment]
@ZhengHuang-20 
```
{
      title: 'key',
      dataIndex: 'key',
      width: 180,
      valueType: 'select',
      valueEnum: labelsMap,
      fieldProps: {
        showSearch: true,
      },
},
```

**Comment by guwan** [comment]
> @ZhengHuang-20
> 
> ```
> {
>       title: 'key',
>       dataIndex: 'key',
>       width: 180,
>       valueType: 'select',
>       valueEnum: labelsMap,
>       fieldProps: {
>         showSearch: true,
>       },
> },
> ```

谢谢，找了半天文档没找到，你这里的答案终于有用了。
