### ISSUE TITLE
ProFormDigit name属性报React does not recognize the `proFieldKey` prop on a DOM element..🧐[问题]

### ISSUE THREAD

**Issue by ZzTaidhm** [ant-design/pro-components#2113]
![image](https://user-images.githubusercontent.com/20452344/110106274-72626a80-7de4-11eb-9222-129c5fb254bf.png)
 将name=“delay-time”也同样错误

**Comment by chenshuai2144** [comment]
已经修复了，等待周一发布

**Comment by wangyazhen** [comment]
hi   我这个版本还是有这个错误，清除缓存了还是不行，请问下怎么操作。


![image](https://user-images.githubusercontent.com/5687531/111245916-5e1e3900-8640-11eb-9cd5-c32d12645a66.png)

**Comment by chenshuai2144** [comment]
哪个组件呢？

**Comment by wangyazhen** [comment]
`ProFormDigit` 这个

**Comment by codedart2018** [comment]
ProFormDigit　2021-04-07同样复现此问题。只能用form.item自己去包裹inputnumber组件

**Comment by chenshuai2144** [comment]
这个修掉了，可以升级到昨天的版本
