### ISSUE TITLE
🐛[BUG] 可编辑表格中，在进行编辑时， 如果编辑项目是一个下拉框时并且value时number类型时，不能正确显示

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#2114]
### 🐛 bug 描述

实际项目中，数据库一个表存一个number类型字段， 用来关联另外一个表的主键。

在【编辑表格】使用 valueEnum，有以下问题：
1、在编辑状态，下来框不能正常显示text信息，而是直接显示value。
2、每次编辑完毕后，保存的时一个string类型，还要转成number类型

是否在valueEnum之外，提供原始的`options` 参数 ， 这样操作就更简单了。

在使用过程中，感觉`valueEnum` 这个设计不好，为了显示状态，把原有的`select`功能模糊化了。 

建议分成两个valueType，一个就是最初的select， 一个是带状态的select，然后分别设置不同的数值参数。

### 重现步骤

在【编辑表格】官方的例子中，把key改成数字，并且将 【defaultData】中 对应的字段改成number类型。
然后点击编辑按钮，就可以看到显示不正常了。

```tsx
valueEnum: {
      all: { text: '全部',  },
      open: {
        text: '未解决',
      },
      closed: {
        text: '已解决',
      },
    },
  },
```

**Comment by fanhualei** [comment]
![editTable](https://user-images.githubusercontent.com/34436863/110193541-712a4f80-7e6f-11eb-90cd-d0a06c23b185.png)

这是bug的图片，不知道能不能看到， github图片一般显示不正常

**Comment by li379395535** [comment]
> ![editTable](https://user-images.githubusercontent.com/34436863/110193541-712a4f80-7e6f-11eb-90cd-d0a06c23b185.png)
> 
> 这是bug的图片，不知道能不能看到， github图片一般显示不正常

有好的实践么？
