### ISSUE TITLE
👑 [需求]列表表单-有几个默认的外观，例如一个外观像：可编辑Table

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#2116]
### 🥰 需求描述
列表表单-有几个默认的外观，例如一个外观像：可编辑Table。

列表表单，简单使用了一下，感觉比可编辑表单简单。但是也有如下的样式问题：
1：每多一行，就多一行tilte，看起来有点乱。
2：每列对齐不标准。

所以能不能有一种布局，像可编辑表格一样，排列的整齐一点。

**Comment by chenshuai2144** [comment]
有 ProFormGourp 的，那个更简单
