### ISSUE TITLE
🧐[问题] ProTable中，boolean类型的数据列，不能直接展示？

### ISSUE THREAD

**Issue by gaven004** [ant-design/pro-components#2119]
### 🧐 问题描述

ProTable中，boolean类型的数据列，不能直接展示？

![image](https://user-images.githubusercontent.com/9878331/110232812-05bdac00-7f5b-11eb-97ff-f146d808d270.png)

表格中对应的数据：
{
  "id": "100000000000000000",
  "resource": "/refresh-token",
  "method": "ALL",
  "description": "令牌刷新",
  "permitAll": true,
  "status": "VALID"
}
其中permitAll为那一没显示的数据列

对应的column定义代码：
    {
      title: '任意访问',
      dataIndex: 'permitAll',
      width: '8%',
    },

**Comment by chenshuai2144** [comment]
用  `renderText = (text:boolean)=>text.toString()`

boolean 当成组件渲染的时候会变成空
