### ISSUE TITLE
🐛[BUG] ProForm class组件使用formRef 拿到的是 {current: null}

### ISSUE THREAD

**Issue by huangkaibo** [ant-design/pro-components#2121]
### 🐛 bug 描述

依照issue https://github.com/ant-design/pro-components/issues/1561 中官方给的代码
```js
class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.myRef = React.createRef();
  }
  render() {
    return <div ref={this.myRef} />;
  }
}
```
带入`<ProForm>`中发现拿到的formRef是 {current: null}
如果换为`<Form>`就正常了

### 💻 复现代码

https://codesandbox.io/s/antd-reproduction-template-forked-0w0ko?file=/index.js
点下测试按钮, console里可以看到 {current: null}
`<ProForm>`换为`<Form>`就正常了

### © 版本信息

- ProComponents 版本: 1.16.3

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/19745373/110237860-43313200-7f79-11eb-8b85-d60fb52a8c24.png)

**Comment by ChenWeihua123** [comment]
是 formRef

**Comment by huangkaibo** [comment]
> 是 formRef

好的  感谢

**Comment by huangkaibo** [comment]
> 是 formRef

好的 感谢, `<ProForm ref={this.myRef}>`改为`<ProForm formRef={this.myRef}>`后可以了
不过很奇怪,  `<Form>`的官网案例里是ref
![image](https://user-images.githubusercontent.com/19745373/110267535-f9892b80-7ffa-11eb-97cd-2d53b2f7f39c.png)

`<ProForm>` issue https://github.com/ant-design/pro-components/issues/1561 中官方给的也是ref
![image](https://user-images.githubusercontent.com/19745373/110267599-20dff880-7ffb-11eb-82e3-0e41121d5837.png)

**Comment by ChenWeihua123** [comment]
issue#1561 说的是 React 官方推荐写法吧
两个组件导出方式不同，antd Form 是 通过 React.forwardRef 导出的
ProForm 是自定义的一个 formRef 属性
