### ISSUE TITLE
🐛[BUG]pro-layout混合布局menuHeaderRender=false不生效

### ISSUE THREAD

**Issue by yongliangliu** [ant-design/pro-components#2127]
### 🐛 bug 描述

pro-layout混合布局menuHeaderRender=false不生效
版本： @ant-design/pro-layout": "^6.14.4
配置：
fixSiderbar: true,
navTheme: "light",
fixedHeader: true,
primaryColor: "#007ad3",
layout: "mix",
contentWidth: "Fluid",
splitMenus: true,
menuHeaderRender: false,

![image](https://user-images.githubusercontent.com/19800207/110264253-dc049380-7ff3-11eb-8fc6-b2bd13073cfc.png)

**Comment by chenshuai2144** [comment]
`| headerTitleRender | 自定义头标题的方法,mix 模式下生效 | `(logo,title,props)=>ReactNode` | - |`

要用这个 mix 比较特殊

**Comment by yongliangliu** [comment]
设置后，logo的位置依然存在，菜单栏无法左移

**Comment by yongliangliu** [comment]
设置后，logo的位置依然存在，菜单栏无法左移
![Uploading image.png…]()

**Comment by yongliangliu** [comment]
设置后，标题栏位置不变，期望是左移
![image](https://user-images.githubusercontent.com/19800207/111076044-9e3cc900-8525-11eb-9eef-bf515d5d4adc.png)

**Comment by chenshuai2144** [comment]
headerTitleRender ={false}
