### ISSUE TITLE
🐛[BUG] EditableProTable，只有数值为0时，在编辑状态时，不能赋值到编辑控件。

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#2129]
### 🐛 bug 描述

 EditableProTable，只有数值为0时，在编辑状态时，不能赋值到编辑控件。

例如下面的代码，当是0的情况下，不能赋值到编辑控件。

```tsx
      {
        title: '排序',
        key: 'slideSort',
        dataIndex: 'slideSort',
        valueType: 'digit',
        width: '80px',
      },
```

如果能看到下面的图片，就能更快的理解我描述的问题了。

![1](https://user-images.githubusercontent.com/34436863/110281903-842c5380-8018-11eb-83e3-7b732b3ff82b.png)
![2](https://user-images.githubusercontent.com/34436863/110281907-868ead80-8018-11eb-832a-3164b8723c87.png)

**Comment by fanhualei** [comment]
只有0才出现这个情况，如果是1,2,3其他的数就没有这种情况。

还有当异步得到数据时，例如在编辑表格中使用了`valueType: 'select'` 时 ，下拉框显示不正常，后来我发现是第一次初始化控件时，没有获取到下拉框数据，后来通过useState得到数据后，也没有刷新控件。 我通过曲线救国的方法搞定了，但是这个坑，也花费我好多时间，去排查这个问题。

**Comment by chenshuai2144** [comment]
看起来没什么问题，我试了几遍
