### ISSUE TITLE
🐛[BUG]钉钉升级到最新版本protable报错

### ISSUE THREAD

**Issue by dj356988** [ant-design/pro-components#2130]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/24800947/110289487-7381da80-8024-11eb-9b5c-d1398ce36454.png)

**Comment by chenshuai2144** [comment]
加个  Polyfill 吧，看起来是把发布的新功能又吃了回去

https://segmentfault.com/a/1190000010106158
