### ISSUE TITLE
🐛[BUG]可编辑表格样式问题

### ISSUE THREAD

**Issue by txp1035** [ant-design/pro-components#2140]
### 🐛 bug 可编辑表格样式问题

表单项不居中
![image](https://user-images.githubusercontent.com/9554297/110597790-f8ebc300-81bb-11eb-84c7-64bc9fcd5890.png)

### 📷 复现步骤

官方文档可以复现问题
 

### 🏞 期望结果
垂直居中

**Comment by txp1035** [comment]
校验位置，暂时没有更好的方案

**Comment by chenshuai2144** [comment]
这个正在做方案，做了另外的一种错误提示方案
