### ISSUE TITLE
兄弟，这个 ProList 怎么永远都有checkbox在前面啊，这个能去掉吗？🧐[问题]

### ISSUE THREAD

**Issue by Zach-Lu** [ant-design/pro-components#2142]
### 💻 示例代码
`<ProList<{ id: string; title: string; desc: string }>
            split
            rowKey="id"
            headerTitle="进行中的任务"
            dataSource={dataSource}
            metas={{
              title: {},
              description: {
                render: (_, record) => <>{record.desc}</>,
              },
              actions: {
                render: () => [<a key="warning">报警</a>, <a key="view">查看</a>],
              },
            }}
          />`

### 🚑 其他信息

都已经这样了，还是有checkbox 在前面，文档里也没有说明怎么去掉，快疯了。

**Comment by xiaohuoni** [comment]
rowSelection 不配置就没有选中，你看看你的版本是不是最新的。

**Comment by xiaohuoni** [comment]
https://procomponents.ant.design/components/list#%E6%94%AF%E6%8C%81%E9%80%89%E4%B8%AD%E7%9A%84%E5%88%97%E8%A1%A8

**Comment by Zach-Lu** [comment]
我是 1.15 最新的，不配置rowSelection 也没用。

**Comment by chenshuai2144** [comment]
修了，我更新了一下
