### ISSUE TITLE
ProFormList内自定义的item，任何操作都会导致上传内容数据丢了

### ISSUE THREAD

**Issue by ZzTaidhm** [ant-design/pro-components#2143]
![image](https://user-images.githubusercontent.com/20452344/110601197-a6aca100-81bf-11eb-841e-a7e2e9c71037.png)

在ProFormList中，每次添加一行或删除一行或在任何输入框内修改数据都会导致我上传的内容置空，每次修改输入框看到itemRender都会刷新，请问如何处理，急！！！
备注：截图代码是ProFormList的item

**Comment by chenshuai2144** [comment]
来个重现，因为每次输入都会触发 rerender，可能导致你的组件被释放掉了

**Comment by B-sirius** [comment]
一个类似的问题：

https://codesandbox.io/s/nested-smko1?file=/src/App.js

`SublicenseTime`是一个值为对象的自定义组件，在单条记录操作、新健记录的时候都会有异常现象

**Comment by theBestNotes** [comment]
遇到类似问题+1；
自定义的组件在ProFormList中，onFieldsChange时候 ，正常的返回值一般是 [row_name, index, sub_row_name]，
而自定义的组件返回值没有index值，只返回了 [row_name, sub_row_name].

**Comment by whinc** [comment]
> > 遇到类似问题+1；
> > 自定义的组件在ProFormList中，onFieldsChange时候 ，正常的返回值一般是 [row_name, index, sub_row_name]，
> > 而自定义的组件返回值没有index值，只返回了 [row_name, sub_row_name].
> 
> pro-form[12.0版本](https://procomponents.ant.design/changelog/pro-form)已经修复该问题；
> 
> 另外注意在ProForm中使用自定义组件，需要用`ProForm.Item`而不是antd的`Form.Item`进行包裹

文档中增加下说明吧
