### ISSUE TITLE
【bug】proLayout layout=mix 模式下，点击顶端导航菜单后如何做到不匹配路由，只改变左侧菜单？

### ISSUE THREAD

**Issue by ahnuljz** [ant-design/pro-components#2147]
【bug】如果在 layout=side 模式下，点击一级导航后是不匹配路由，只改变左侧菜单的，这与mix下的变现不一致。

一般多级导航中，有的菜单不用加载路由，只有叶子节点才需要加载路由

**Comment by chenshuai2144** [comment]
这个可以用重定向的，重定向到某一页，如果完全不跳转是做不到的。
