### ISSUE TITLE
🐛[BUG]protable的options.setting的拖拽是不是不好使了？

### ISSUE THREAD

**Issue by jiqishoubi** [ant-design/pro-components#2148]
### 🐛 bug 描述

protable的options.setting设置为true，列固定左右侧生效，但是拖拽列的顺序不生效

### © 版本信息

- @ant-design/pro-table": "2.29.0
- "umi": "^3.2.14",
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26373119/110722155-cc33bc00-824c-11eb-939e-08c0843e9063.png)

![image](https://user-images.githubusercontent.com/26373119/110722213-e1104f80-824c-11eb-901f-02d3872c4951.png)

**Comment by chenshuai2144** [comment]
已修复了，换了 antd 的 tree，没用额外的组件
