### ISSUE TITLE
🐛[BUG]ProTable form搜索使用valueEnum的时候，连续点击下拉框的时候会闪烁

### ISSUE THREAD

**Issue by sifongithub** [ant-design/pro-components#2149]
### 🐛 bug 描述

ProTable form搜索使用valueEnum的时候，连续点击下拉框的时候会闪烁，使用request也是这种情况

### 📷 复现步骤
![image](https://s31.aconvert.com/convert/p3r68-cdx67/8l4c1-gpgec.gif)

`
{
      title: '功能',
      dataIndex: 'stableCategory',
      // valueEnum: BreedingStableBreedingStableTypeNamesObj,
      valueEnum: {
        0: {
          text: 'hello',
        },
        1: {
          text: 'world',
        },
      },
    },

`
### 🏞 期望结果

连续点击的时候不再上下跳动，每次点击都可以选择

### 💻 复现代码

![image](https://user-images.githubusercontent.com/40592376/110727483-55032580-8256-11eb-9b3c-7a2289220fac.png)

### © 版本信息
`"dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-descriptions": "^1.2.0",
    "@ant-design/pro-form": "^1.3.0",
    "@ant-design/pro-layout": "^6.9.0",
    "@ant-design/pro-table": "^2.17.0",
    "@microsoft/signalr": "^5.0.3",
    "@types/accounting": "^0.4.1",
    "@types/js-cookie": "^2.2.6",
    "@umijs/plugin-openapi": "^1.0.1",
    "@umijs/route-utils": "^1.0.33",
    "accounting": "^0.4.1",
    "ahooks": "^2.9.6",
    "antd": "^4.9.4",
    "classnames": "^2.2.6",
    "ezuikit-js": "^0.2.3",
    "js-cookie": "^2.2.1",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "qs": "^6.9.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.2.14",
    "umi-request": "^1.0.8"
  },`
- 浏览器环境chrome最新版
- 开发环境 [e.g. Win]

**Comment by sifongithub** [comment]
也不算是很快的点击，上边的截图点击太快了，上传新的
<img src="https://s31.aconvert.com/convert/p3r68-cdx67/b5ti4-0q547.gif" width="50%">

**Comment by chenshuai2144** [comment]
图图都挂了

**Comment by sifongithub** [comment]
> 图图都挂了

没有呀，可能我是因为挂了代理上传的，又上传了一次![](https://ftp.bmp.ovh/imgs/2021/03/c6c5b21981ea4de0.gif)

**Comment by chenshuai2144** [comment]
看起来有点像 dom 的问题，我来看看

**Comment by dengshicheng1996** [comment]
> > 图图都挂了
> 
> 没有呀，可能我是因为挂了代理上传的，又上传了一次![](https://camo.githubusercontent.com/ad1b47284a225da4d197ab47c2806ea4bd697d6697c4382cf5ee0aab227c241b/68747470733a2f2f6674702e626d702e6f76682f696d67732f323032312f30332f633663356232313938316561346465302e676966)

你是自定义了valueType 吧, 我在自定义vlaueType的时候也出现了类似的问题,直接使用的valueEnum 就不会存在该问题

**Comment by sifongithub** [comment]
> > > 图图都挂了
> > 
> > 
> > 没有呀，可能我是因为挂了代理上传的，又上传了一次![](https://camo.githubusercontent.com/ad1b47284a225da4d197ab47c2806ea4bd697d6697c4382cf5ee0aab227c241b/68747470733a2f2f6674702e626d702e6f76682f696d67732f323032312f30332f633663356232313938316561346465302e676966)
> 
> 你是自定义了valueType 吧, 我在自定义vlaueType的时候也出现了类似的问题,直接使用的valueEnum 就不会存在该问题

没有的，使用的valueEnum，请求回来的数据也不行

**Comment by sifongithub** [comment]
yarn upgrade之后就没有这个问题了
