### ISSUE TITLE
👑 [需求]protable的valueType 值类型希望可以增加一个整数类型的值

### ISSUE THREAD

**Issue by pangxiaolong** [ant-design/pro-components#2152]
### 🥰 需求描述

现有的digit支持数字类型，但是不支持控制小数点精度和位数

**Comment by chenshuai2144** [comment]
可以在 fieldProps 里配置一下。


precision | 数值精度，配置 formatter 时会以 formatter 为准 | number | - | -
-- | -- | -- | -- | --

**Comment by pangxiaolong** [comment]
> 可以在fieldProps里配置一下。
> 
> 精确	数值精度，配置formatter时会以formatter为准	数字	--	--

beat服
