### ISSUE TITLE
🐛[BUG]EditableProTable 新版本如果rowKey是number类型在实时编辑时会出现错误

### ISSUE THREAD

**Issue by blackraindrop** [ant-design/pro-components#2153]
### 🐛 bug 描述

之前rowkey是number类型正常而string类型出现类似错误，新版本是number类型错误string类型正确

![image](https://user-images.githubusercontent.com/1668029/110342535-7ac9d800-8066-11eb-87ad-50d56bef4b2f.png)
这里如果使用的是Map，那么它的键就不仅仅可以是string了，也可以放number进去，导致{"1":  xxx, 1: xxx}会共存。

第一种方案：去掉toNumber以及recordKeyToString使用的地方，kvMap都用string 类型作为key。
第二种方案：是否能使用Form.List的方式，这样就不需要用rowKey作为对象的key，然后在反向转回数组。

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
修复了，我全部使用了  string，会自动转化一下
