### ISSUE TITLE
🧐[问题] <ProFormSelect>不支持labelInValue, 请问怎样可以拿到选中的label

### ISSUE THREAD

**Issue by huangkaibo** [ant-design/pro-components#2156]
### 🧐 问题描述

`<ProFormSelect>` 不支持labelInValue, 请问下怎样可以拿到选中的label
另外`<ProFormCheckbox.Group>` 也有同样的疑问, 都想拿到选中的label

**Comment by chenshuai2144** [comment]
支持的，配置 labelInValue

![image](https://user-images.githubusercontent.com/8186664/110920724-b0b5d780-8358-11eb-8ea0-7338ff1a936b.png)
