### ISSUE TITLE
🧐[问题] 请问下ProFormText如何设置值?

### ISSUE THREAD

**Issue by huangkaibo** [ant-design/pro-components#2157]
### 🧐 问题描述

请问下ProFormText如何设置值, 试了value/defaultValue都不行
![image](https://user-images.githubusercontent.com/19745373/110789988-72161380-82ab-11eb-9b16-5c6cf854af78.png)

**Comment by huangkaibo** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-szicd?file=/index.js

**Comment by chenshuai2144** [comment]
用 filedProps 或者 initiavalues。

![image](https://user-images.githubusercontent.com/8186664/110928966-69344900-8362-11eb-8ff1-466d854ef5cd.png)
