### ISSUE TITLE
👑 [需求]如何设置某个列默认不展示，但允许通过setting（列展示）勾选出来

### ISSUE THREAD

**Issue by birdycn** [ant-design/pro-components#2159]
也就是说，列默认不展示，但用户在列展示按钮里，勾选后也可以显示

哪个属性可以实现这个要求呢

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/table#%E5%8F%97%E6%8E%A7%E7%9A%84%E8%A1%A8%E6%A0%BC%E8%AE%BE%E7%BD%AE%E6%A0%8F




columnsStateMap | columns 的状态枚举 | {key:{ show,fixed }}} | -
-- | -- | -- | --
onColumnsStateChange | columns 状态发生改变 | (props: {key:{ show,fixed }}}) => void | -

**Comment by lyx-js** [comment]
通过columnsState控制列的隐藏，会导致table的params发生变化，刷新列表。对应的setting列表里的选项，每修改一个都会刷新关闭列表，但实际上params没变化。所以，怎么在受控的模式下，不因选择setting，而导致列表刷新？

**Comment by chenshuai2144** [comment]
新开个迭代吧

**Comment by lyx-js** [comment]
> 新开个issue吧

并非组件问题，已经解决了，谢谢~
