### ISSUE TITLE
👑 [需求] ProTable::options::setting 增加持久化支持

### ISSUE THREAD

**Issue by panxiuqing** [ant-design/pro-components#2160]
### 🥰 需求描述

为表格列设置增加持久化支持。多数情况下，列设置完后，用户刷新页面时都希望保留设置。

### 🧐 解决方案

setting 可增加接受选项，由用户提供持久化读取（读取可能不需要，用户自行处理 ProTable::columns 参数即可）和写入的实现。

### 🚑 其他信息

或者目前已有相应的事件回调等我没看到，可以帮忙指出。

**Comment by jiqishoubi** [comment]
onColumnsStateChange  试试这个 兄dei
