### ISSUE TITLE
🐛[BUG] ProTable的request访问的URL报HTTP错误时，组件崩溃

### ISSUE THREAD

**Issue by xjb258** [ant-design/pro-components#2161]
### 🐛 bug 描述

ProTable 的 request 属性调用 request 接口访问后台api，当api不可访问或者返回其它http错误码，组件会崩溃。

request={async (params = {}) => {
    return request<{ data: DataSourceType[];}>('/api/setting/servicelist', { params, });
}}

### 📷 复现步骤

必现。

### 🏞 期望结果

希望在调用 request 出现http错误时，能像其它地方调用一样，能被 antd-pro 中 app.tsx 中的 errorHandler 捕获：

export const request: RequestConfig = {
    errorHandler,
};

如此在网络出错时，用户可以看到 notification 弹出的出错提示。

### © 版本信息

@ant-design/pro-table@2.30.4
其它组件均是2021-03-07以后的版本。

**Comment by chenshuai2144** [comment]
报错信息贴出来
