### ISSUE TITLE
🧐[问题]ProFormList 子元素的 label 不显示

### ISSUE THREAD

**Issue by wywppkd** [ant-design/pro-components#2162]
### 🧐 问题描述

- 如题, 示例代码中 ProFormText 的 label 不显示

### 💻 示例代码

```js
import React from 'react';
import ProForm, { ProFormList, ProFormText } from '@ant-design/pro-form';

export default () => (
  <ProForm
    onFinish={async (values) => {
      console.log('Received values of form:', values);
    }}
  >
    <ProFormList name="users" label="用户信息">
      <ProFormText name="labels" label="姓名" />
    </ProFormList>
  </ProForm>
);
```

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20620574/110884040-6106ea00-831f-11eb-9097-a7aedbb950ff.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/110929100-9123ac80-8362-11eb-9486-38d37713aa5e.png)


是不是有什么样式冲突

**Comment by wywppkd** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/110929100-9123ac80-8362-11eb-9486-38d37713aa5e.png)
> 
> 是不是有什么样式冲突

找到原因了, V5 模板的 global.less 样式冲突

```js
ul,
ol {
  list-style: none;
}
```

**Comment by wywppkd** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/110929100-9123ac80-8362-11eb-9486-38d37713aa5e.png)
> 
> 是不是有什么样式冲突

在 codesandbox 试了没有问题, 在 V5 模板中使用就有问题
我现在用的 5.0.0-beta.0 和 最新的 5.0.0-beta.2 都有会出现上述问题

**Comment by chenshuai2144** [comment]
看样子是样式冲突了，来个重现的 repo 吧

**Comment by wywppkd** [comment]
> 看样子是样式冲突了，来个重现的 repo 吧

https://github.com/wywppkd/pro5-test

**Comment by wywppkd** [comment]
Welcome 页

**Comment by newketom** [comment]
嵌套还是存在问题
[官方示例](https://procomponents.ant.design/components/group/#%E8%A1%A8%E5%8D%95%E4%BA%92%E7%9B%B8%E5%B5%8C%E5%A5%97)
![image](https://user-images.githubusercontent.com/56467036/112345710-3c881600-8d00-11eb-842b-8df9c3a31609.png)
![image](https://user-images.githubusercontent.com/56467036/112345791-50337c80-8d00-11eb-88ba-84a04f6d97ac.png)

**Comment by newketom** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
再试试 样式设计改了 应该不会了

**Comment by newketom** [comment]
> 再试试 样式设计改了 应该不会了

上边那位简单的demo，确实修复了，但是官网复杂嵌套的demo抄下来还是有问题，版本1.18.4

**Comment by newketom** [comment]
@chenshuai2144 

Demo
https://github.com/newketom/pro5-proform-test

**Comment by chenshuai2144** [comment]
css 写的不好

**Comment by leftjoinandinnerjoin** [comment]
@chenshuai2144 同样的问题，解决了吗？

**Comment by raotaohub** [comment]
> "@ant-design/pro-components": "^2.7.0", 依旧存在这个问题， 嵌套的 formList 新增一行数据后，label 不显示~

![image](https://github.com/ant-design/pro-components/assets/66949076/a81e60ae-1ff4-49c3-9479-8fc4634bfc7a)

**Comment by raotaohub** [comment]
目前在使用的 2.7.0版本 有 alwaysShowItemLabel : boolean 属性， 是否总是显示 label ，默认第一条有label 后续新增的没有
