### ISSUE TITLE
editTable column 中自定义渲染拿不到完整的整行数据

### ISSUE THREAD

**Issue by real-jacket** [ant-design/pro-components#2165]
### 🧐 问题描述

editable column 中 render 自定义渲染拿不到完整的 record

### 💻 示例代码
![image](https://user-images.githubusercontent.com/36723264/110578662-44907380-81a0-11eb-8267-9bb44a52c171.png)
这里缺少我需要的一整行数据，根据我 log 的数据来看，这个 record 被封装了一层，里面只有表单 form 的数据，没有这一行的其它数据

**Comment by chenshuai2144** [comment]
用 form 获得一下吧，record 计算有一定的延迟。

第三个参数就是 form

**Comment by real-jacket** [comment]
你可能误解了，我需要的是 record 完整的一行数据，去动态的传参 给我的组件，不是 form 的。我的理解是 editTable 先是一个 table ，不该跟正常的 table 使用割裂开。record 里的数据单行是下图的数据

![image](https://user-images.githubusercontent.com/36723264/111026035-1bcbe080-8423-11eb-88b3-2f6174271dc4.png)

而自定义渲染的 renderFormItem 第二个参数 record 会丢失除表单数据外的其它所有数据（比如 desc、state、create_at），我需要拿到这行的其它数据传参给自定义的组件！

![image](https://user-images.githubusercontent.com/36723264/111026090-7107f200-8423-11eb-8960-05b9b671ce5d.png)
![image](https://user-images.githubusercontent.com/36723264/111026103-80873b00-8423-11eb-8a50-ff90edb4cdef.png)

**Comment by real-jacket** [comment]
你可能误解了，我需要的是 record 完整的一行数据，去动态的传参 给我的组件，不是 form 的。我的理解是 editTable 先是一个 table ，不该跟正常的 table 使用割裂开。record 里的数据单行是下图的数据

![image](https://user-images.githubusercontent.com/36723264/111026035-1bcbe080-8423-11eb-88b3-2f6174271dc4.png)

而自定义渲染的 renderFormItem 第二个参数 record 会丢失除表单数据外的其它所有数据（比如 desc、state、create_at），我需要拿到这行的其它数据传参给自定义的组件！

![image](https://user-images.githubusercontent.com/36723264/111026090-7107f200-8423-11eb-8960-05b9b671ce5d.png)
![image](https://user-images.githubusercontent.com/36723264/111026103-80873b00-8423-11eb-8a50-ff90edb4cdef.png)
