### ISSUE TITLE
🐛[BUG] proTable 的form 在父容器 dispaly:none 后会闪动

### ISSUE THREAD

**Issue by p354139076** [ant-design/pro-components#2167]
### 🐛 bug 描述

proTable 的form 在父容器 dispaly:none 后会闪动

### 📷 复现步骤

proTable 的form元素在父容器display：none的时候 ，class为 ant-form-inline
父容器正常显示的时候 class为 ant-form-horizontal ,会造成 from item闪动

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![](https://ftp.bmp.ovh/imgs/2021/03/ddcdfc576f67c7c2.jpg)
![](https://i.bmp.ovh/imgs/2021/03/b2115d94a12d1bd7.png)

**Comment by chenshuai2144** [comment]
宽度自动计算导致

**Comment by p354139076** [comment]
这个闪动当前版本有可用的解决方案么

**Comment by chenshuai2144** [comment]
不要用 display，直接把dom给删掉。性能会差一些

**Comment by p354139076** [comment]
类似 antdesign中的tabs，会在切换tabs的时候加上display,  react-router-cache-route 也会采用display方案，这个方式兼容性不高呢。

**Comment by p354139076** [comment]
希望尽快修复

**Comment by p354139076** [comment]
[![66H6gA.png](https://s3.ax1x.com/2021/03/17/66H6gA.png)](https://imgtu.com/i/66H6gA)
[![66HD4e.png](https://s3.ax1x.com/2021/03/17/66HD4e.png)](https://imgtu.com/i/66HD4e)
更新后还是存在闪动的问题

**Comment by p354139076** [comment]
[![66bciF.png](https://s3.ax1x.com/2021/03/17/66bciF.png)](https://imgtu.com/i/66bciF)

**Comment by chenshuai2144** [comment]
版本已经发布了，你人肉设置上一个 layou。

**Comment by p354139076** [comment]
from 元素是正常了，但是from item的栅格还是会先从col-8 变更为配置后的col, 从视觉上看还是会闪动一下。

**Comment by p354139076** [comment]
举个例子，会从col-8 变成col-6。

**Comment by chenshuai2144** [comment]
看起来还蛮难解决的，你要配置死行数

**Comment by p354139076** [comment]
我尝试使用了form={{span:5}}，依旧还是会先是col-8，然后变成5

**Comment by chenshuai2144** [comment]
明天发个版本。这个计算逻辑比较蛋疼

**Comment by p354139076** [comment]
辛苦啦～

**Comment by chenshuai2144** [comment]
发了新版本，应该是解决了
