### ISSUE TITLE
关于StepsForm和Modal配合使用的问题

### ISSUE THREAD

**Issue by my9988** [ant-design/pro-components#2169]
@chenshuai2144  V5最新，ProTable ProForm都是最新的版本，几乎是照DEMO来的，就是不对，ModalForm 在第二步或最后一步的时候Close后，在弹出的ModalForm还是停在退出时的状态，不是像新建的一样，从第一步开始。
![image](https://user-images.githubusercontent.com/17469220/109323549-96b8c700-7879-11eb-8c36-1e08ae80ab5f.png)
![image](https://user-images.githubusercontent.com/17469220/109323662-b819b300-7879-11eb-82fe-89dd95018de5.png)
好像destroyOnClose没起作用，如此的话我提交数据总有问题。

再补充下，刚才测试了ProComponents的DEMO也是如此，既然是新建表单，怎么停在上次退出的状态呢。
![image](https://user-images.githubusercontent.com/17469220/109324805-2f037b80-787b-11eb-8371-fc490c24da98.png)

我的代码有走完OnFinish()了，也返回return true了
![image](https://user-images.githubusercontent.com/17469220/109326114-c4ebd600-787c-11eb-9542-b82661a36376.png)

**Comment by my9988** [comment]
any update?

**Comment by my9988** [comment]
@chenshuai2144 关于StepsForm的问题还没有开始修复？

**Comment by chenshuai2144** [comment]
还没最近精力有点不够

**Comment by my9988** [comment]
> 
> 
> 还没最近精力有点不够

@chenshuai2144 麻烦还是看看这个问题，感觉对你们来说很容易处理的，目标就是每次打开modelsform的时候像是一个新建的就可以。目前不只是Feature的问题，实际上第二次打开取值也是有问题的，非得回到第一步，然后再回到最后点提交才能得到值

**Comment by gaonq** [comment]
有解决么？同样问题

**Comment by songfaqi** [comment]
有解决么？同样问题

**Comment by songfaqi** [comment]
有解决么？同样问题

**Comment by DerrickTel** [comment]
@songfaqi @gaonq @my9988 我看了一下代码，你们在onFinish里面`return true`就会自动把变成第一步。确实文档有疏忽，我补一下。

**Comment by zpaimon** [comment]
重新打开 modal，就回到初始状态而不是最后的关闭状态，有啥好办法？

**Comment by Jacob-tu** [comment]
最近我也遇到了这样的问题，StepsForm 和 Modal 配合使用时，Modal 取消后表单无法不能回到第一步。后来尝试用 current 参数控制 step，思路是给每个 StepForm 配置 onFinish 参数，中间每个 StepForm 提交时 current + 1，由于是 current 控制 step，所以最后一个 StepForm 提交时 current 置为 0，Modal onCancel 时 current 置为 0；另外还需要自定义 submitter 使之可以返回上一步，可参考官方文档 [自定义分布表单按钮](https://procomponents.ant.design/components/steps-form#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%86%E6%AD%A5%E8%A1%A8%E5%8D%95%E6%8C%89%E9%92%AE)
codesandbox: [https://codesandbox.io/s/fen-bu-biao-dan-yu-modal-pei-he-shi-yong-forked-djqrss?file=/App.tsx](https://codesandbox.io/s/fen-bu-biao-dan-yu-modal-pei-he-shi-yong-forked-djqrss?file=/App.tsx)

**Comment by LEEJLU** [comment]
> 最近我也遇到了这样的问题，StepsForm 和 Modal 配合使用时，Modal 取消后表单无法不能回到第一步。后来尝试用 current 参数控制 step，思路是给每个 StepForm 配置 onFinish 参数，中间每个 StepForm 提交时 current + 1，由于是 current 控制 step，所以最后一个 StepForm 提交时 current 置为 0，Modal onCancel 时 current 置为 0；另外还需要自定义 submitter 使之可以返回上一步，可参考官方文档 [自定义分布表单按钮](https://procomponents.ant.design/components/steps-form#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%86%E6%AD%A5%E8%A1%A8%E5%8D%95%E6%8C%89%E9%92%AE) codesandbox: https://codesandbox.io/s/fen-bu-biao-dan-yu-modal-pei-he-shi-yong-forked-djqrss?file=/App.tsx

Thanks! bro!

**Comment by Gip886** [comment]
经过测试，发现可以这样处理可以在modal重新打开时候状态重置。
把那个demo 里面StepsForm属性去掉，自己把那个modal套在StepsForm外面就可以了，modal那个destroyOnClose有效果

**Comment by ylmint** [comment]
> 经过测试，发现可以这样处理可以在modal重新打开时候状态重置。 把那个demo 里面StepsForm属性去掉，自己把那个modal套在StepsForm外面就可以了，modal那个destroyOnClose有效果

请问具体怎么操作（小白一枚）？

**Comment by GOUYONGCHAO** [comment]
> 经过测试，发现可以这样处理可以在modal重新打开时候状态重置。 把那个demo 里面StepsForm属性去掉，自己把那个modal套在StepsForm外面就可以了，modal那个destroyOnClose有效果



> > 经过测试，发现可以这样处理可以在modal重新打开时候状态重置。 把那个demo 里面StepsForm属性去掉，自己把那个modal套在StepsForm外面就可以了，modal那个destroyOnClose有效果
> 
> 请问具体怎么操作（小白一枚）？

就是将demo中的
```
stepsFormRender={(dom, submitter) => {
        return (
          <Modal
            width={1000}
            bodyStyle={{ padding: '32px 40px 48px' }}
            destroyOnClose
            title={intl.formatMessage({
              id: 'pages.searchTable.updateKeywords',
              defaultMessage: '更新关键词',
            })}
            open={props.updateModalOpen}
            footer={submitter}
            onCancel={() => {
              props.onCancel();
            }}
          >
            {dom}
          </Modal>
        );
      }}
```
删除掉，然后再在stepform外面嵌套一层modal

**Comment by wk544863858** [comment]
封装一个组件，可以全局使用
`import {FC, useRef, useState} from "react";
import {FormInstance, Modal} from "antd";
import {StepsForm} from "@ant-design/pro-form";

interface Props {
  onFinish: (values: any) => Promise<boolean | void>;
  open: boolean;
  onCancel: (params: boolean) => void
  children?: any
}

const StepFormPlus: FC<Props> = ({onFinish, children, open, onCancel}) => {
  const [current, setCurrent] = useState(0)
  const formRef = useRef<FormInstance>()
  return <>
    <StepsForm onFinish={onFinish}
               current={current}
               formRef={formRef}
               onCurrentChange={setCurrent}
               stepsProps={{
                 size: 'small',
               }}
               formProps={{
                 layout: 'horizontal',
                 labelCol: {span: 6},
                 wrapperCol: {span: 18},
               }}
               stepsFormRender={(dom, submitter) => {
                 return <Modal width={800}
                               destroyOnClose
                               maskClosable={false}
                               open={open}
                               onCancel={() => {
                                 if (onCancel !== undefined) {
                                   onCancel(false)
                                 }
                                 setCurrent(0)
                                 if (formRef) {
                                   formRef?.current?.resetFields()
                                 }
                               }}
                               footer={submitter}>
                   {dom}
                 </Modal>
               }}>
      {children}
    </StepsForm>
  </>
};

export default StepFormPlus;
`
这样使用
`
const [openEdit, setOpenEdit] = useState(false);
....

<StepFormPlus onFinish={submitEditClientFunc}
                  open={openEdit}
                  onCancel={setOpenEdit}>
      <StepsForm.StepForm title="基础信息"
                          name="basicFields"
                          request={queryClientFunc}
                          params={{id: id}}
                          layout={'horizontal'}>
        <ProFormText name="name"
                     width="lg"
                     label="客户名称"
                     placeholder="请准确填写客户主体名称，禁止简写和随意填写"
                     rules={[{required: true}]}/>
     <StepsForm.StepForm/>
<StepFormPlus/>
`
