### ISSUE TITLE
🧐[问题] ProTable 中 Search 展开按钮的提交逻辑问题

### ISSUE THREAD

**Issue by MrZhouChiBang** [ant-design/pro-components#217]
### 🧐 问题描述

Search 中的展示按钮实现原理是通过 filter 筛选 FormItem 项，来实现展开和收起。

这样会导致一个问题：
1、点击”展开“按钮
2、在展开的 FormItem 中输入值后，点击提交按钮，得到检索后的table
3、点击”收起“按钮，再点一下提交按钮，**检索不会带上之前输入的值**
4、点击”展开“按钮，**之前输入的值又能展示**

这样的检索逻辑是否有问题？
我觉得在提交时应该保留之前输入的值

**Comment by chenshuai2144** [comment]
新版本已经改了，变成了 `display:none`
