### ISSUE TITLE
🐛[BUG] ProTable 搭配useAntdTable  获取不到查询表单的字段数据

### ISSUE THREAD

**Issue by yacolin** [ant-design/pro-components#2173]
### 🐛 bug 描述
ProTable搭配useAntdTable  进行数据查询，查询数据函数的formData为空。
经测试该问题出现在ProTable@2.14..0开始的版本， 在ProTable@2.13.3的版本是可以获取到formData

### 🏞 期望结果
ProTable@2.14.0开始的版本搭配useAntdTable的formData参数不为空，可以和ProTable@2.13.3版本一样获取到formData的相关字段

### 💻 复现代码
[https://codesandbox.io/s/trusting-wind-q4sni?file=/src/components/index.js](https://codesandbox.io/s/trusting-wind-q4sni?file=/src/components/index.js)

### © 版本信息

- ProComponents 版本: 
   -  @ant-design/pro-table@2.30.5
   -   ahooks@2.9.4
- 浏览器环境  Chrome 88.0.4324.190（正式版本） （64 位）
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
没用过这个工具，有兴趣帮忙排查一下吗？

**Comment by yacolin** [comment]
> 没用过这个工具，有兴趣帮忙排查一下吗？

从目前的表现上来看，是formRef绑定后   useAntdTable  内部通过  formRef.current没有获取到表单的各个字段字段值。
昨天对比看了下，ProTable@2.13.3  和 ProTable@2.14.0 Table相关的文件变化不大

**Comment by chenshuai2144** [comment]
第一次的时候的确看不到的，useAntdTable 的能强制刷新一下 ref 吗

**Comment by yacolin** [comment]
> 第一次的时候的确看不到的，useAntdTable 的能强制刷新一下 ref 吗

具体的表现差异是在点击查询主动出发的时候，2.13.3的版本是能在查询的时候拿到查询表单字段参数的，而2.14.0之后的版本是拿不到的，可以两个链接对照看一下 [https://codesandbox.io/s/icy-feather-vbxtm?file=/src/components/index.js](https://codesandbox.io/s/icy-feather-vbxtm?file=/src/components/index.js)

**Comment by downhill6** [comment]
@yacolin 你好，同样遇到了这个问题，请问现在有解决方法了吗？

**Comment by yacolin** [comment]
> @yacolin 你好，同样遇到了这个问题，请问现在有解决方法了吗？
选的方案是降级

**Comment by chenshuai2144** [comment]
protable 不保证和 useAntdTable  能兼容，不可兼得
