### ISSUE TITLE
🧐[请问怎么设置默认表头加载时隐藏某些列？]

### ISSUE THREAD

**Issue by ado5** [ant-design/pro-components#2178]
在 列设置 里，数据列默认是全部显示的，通过勾选动态设置需要 显示隐藏 表数据列，请问可以直接在ProTable里预设 隐藏某一列吗？

**Comment by chenshuai2144** [comment]
columnsStateMap | columns 的状态枚举 | {key:{ show,fixed }}} | -
-- | -- | -- | --
onColumnsStateChange | columns 状态发生改变 | (props: {key:{ show,fixed }}}) => void | -



看看这个

**Comment by zhubufang** [comment]
可以设置一些列不可操作  不要出现在列设置中吗
