### ISSUE TITLE
👑 [需求] ProTable 可否增加默认显示 FormItem 的数量

### ISSUE THREAD

**Issue by MrZhouChiBang** [ant-design/pro-components#218]
### 🥰 需求描述

项目中需要默认展示两行检索条件，超过两行再显示”展开“按钮

**Comment by chenshuai2144** [comment]
应该不会支持的，你的需求是什么？

**Comment by MrZhouChiBang** [comment]
![image](https://user-images.githubusercontent.com/17632172/90463776-5942e680-e13e-11ea-8f7c-80bfd255ea5b.png)

目前是只能修改 span 来控制默认展示 formItem 数量
我这边需要默认展示两行（7项，超出两行才显示 ”展开“ 按钮），就没法用 span 来调整

**Comment by chenshuai2144** [comment]
可以用 form={{ span: 12 }}， 默认的列是 24/span 个

**Comment by Asence** [comment]
@chenshuai2144  我有一个新的需求
![image](https://github.com/ant-design/pro-components/assets/45235142/26adc4cb-4e3f-479b-92ad-9dad285e44c6)

公司这边希望收起的时候默认显示2行。这个版本这两天要上线了，我想问下有什么解决这个需求的办法吗？
"@ant-design/pro-table": "^2.25.1",
