### ISSUE TITLE
👑 [需求] antdpro 可编辑表格

### ISSUE THREAD

**Issue by gujiwuqing** [ant-design/pro-components#2184]
### 🥰 需求描述

 可编辑表格为什么只能同时编辑一行啊 我不能新增多行嘛？

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/editable-table#%E5%AE%9E%E6%97%B6%E4%BF%9D%E5%AD%98%E7%9A%84%E7%BC%96%E8%BE%91%E8%A1%A8%E6%A0%BC

这个模式就可以同时新增多行了，同时新增多行在取消的时候很麻烦，你注意一下
