### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by yaojin2070** [ant-design/pro-components#2186]
### 🐛 bug 描述

在 **javascript(JSX文件)** 中使用RouteContext是空的对象, 用RouteContext.Consumer也是

### 📷 复现步骤

生成一个函数组件, 引入useContext  和 RouteContext 使用 ,详细下方代码

### 🏞 期望结果
获取到值

### 💻 复现代码

```
import React, { useContext } from 'react';
import { RouteContext } from '@ant-design/pro-layout';
let SmallSettingDrawer = (props) => {
const value = useContext(RouteContext)
  console.log(value) // {}
}
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 ^3.2.14
- 浏览器环境 谷歌
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/48686959/111104160-f954d700-858a-11eb-915a-09438d1f3ac2.png)

**Comment by chenshuai2144** [comment]
只有在 pro layout 包裹中的组件才能使用。

context 必须要是一对的
