### ISSUE TITLE
👑 [需求]ProTable-Combination search

### ISSUE THREAD

**Issue by DerrickTel** [ant-design/pro-components#2192]
### 🥰 需求描述

![image](https://user-images.githubusercontent.com/24643779/111125914-17333380-85ad-11eb-83dc-b430f682fdbe.png)

### 🧐 解决方案

valueType add one

### 🚑 其他信息

无

**Comment by DerrickTel** [comment]
目前可以用`renderFormItem`解决

**Comment by chenshuai2144** [comment]
继续这样解决吧，看起来挺不好抽象的
