### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by paddingC** [ant-design/pro-components#2193]
### 🐛 bug 描述
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports

### 📷 复现步骤

引入pro组件报错
![image](https://user-images.githubusercontent.com/28521120/111126710-f7e8d600-85ad-11eb-9aad-092dea1b2cdd.png)

### © 版本信息
antd 4.8.5
pro-table 2.12.1
- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
重新更新一下你的依赖的。摸不着头脑的报错都可以用重装解决
