### ISSUE TITLE
引入protable组件报错🐛[BUG]

### ISSUE THREAD

**Issue by paddingC** [ant-design/pro-components#2194]
### 🐛 bug 描述

antd 4.8.5
pro-table 2.12.1
![image](https://user-images.githubusercontent.com/28521120/111127259-92491980-85ae-11eb-90ba-d68087e7ea11.png)

### 📷 复现步骤

引入protable组件报错
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
摸不着的头脑的问题，一般都建议重装依赖

**Comment by paddingC** [comment]
> 摸不着的头脑的问题，一般都建议重装依赖

之前我们没用到pro，现在想在项目里添加pro组件，直接npm protable2.12.1，启动后进入相应页面报错，重装依赖是把所有的包都删掉重新install吗？不是版本不匹配的问题吧

**Comment by chenshuai2144** [comment]
最好clean 之后安装 可能是babel runtime
