### ISSUE TITLE
table 中 comcolumns 配置 tip 可以显示tip 但会在查询表单和table 同时出现👑 [需求]

### ISSUE THREAD

**Issue by anewcoder1992** [ant-design/pro-components#2195]
### 🥰 需求描述

tip 可分别配置表单和 列表头。大部分场景 查询表表单的提示 有可能和table的是不一样的

### 🧐 解决方案
增加配置

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


可以在表单和表格的配置中分别指定 `comcolumns` 中的 `tip` 内容。

示例代码：

```jsx
// 表单中的配置
const formConfig = [
  {
    label: "姓名",
    name: "name",
    component: "Input",
    comcolumns: {
      tip: "请输入您的姓名",
    },
  },
  // 其他表单项配置
];

// 表格中的配置
const tableConfig = {
  columns: [
    {
      title: "姓名",
      dataIndex: "name",
      key: "name",
      comcolumns: {
        tip: "这是姓名一列的提示",
      },
      // 其他列的配置
    },
  ],
  // 其他表格配置
};
```

同时需要注意，不同的组件库可能在表单或表格中的配置格式略有不同，具体可以参考相应的文档。例如，使用 antd 的表单组件，可以在 `fieldDecorator` 的 `options` 中设置 `comcolumns` 属性，而在表格中，可以在 `columns` 的配置中设置。

**Comment by chenshuai2144** [comment]
可以通过设置 tooltip 为一个方法来实现了。
