### ISSUE TITLE
🐛[BUG] EditableProTable 编辑已有的数据，保存，会多出一行。

### ISSUE THREAD

**Issue by shinkeika** [ant-design/pro-components#2197]
### 🐛 bug 描述

https://procomponents.ant.design/components/editable-table
就直接看这个例子，我编辑了一列。
![image](https://user-images.githubusercontent.com/29203912/111151366-51f79480-85ca-11eb-92e6-5f7275f531b3.png)
然后点了保存，就多出一行，如图。
![image](https://user-images.githubusercontent.com/29203912/111151651-b6b2ef00-85ca-11eb-9fd0-0d13ca5189a1.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Clarence-Kong** [comment]
猜一下 每一行的key的问题

**Comment by shinkeika** [comment]
看了下官网例子，已经修好了

**Comment by shinkeika** [comment]
@chenshuai2144 请问你们是怎么解决的呢？感觉莫名其妙好了，想问问原因。

**Comment by chenshuai2144** [comment]
是 number和string的问题 

form不支持number当name 会自动转化成string

**Comment by shinkeika** [comment]
@chenshuai2144 听起来还是不太懂呢？能再提示点吗？

**Comment by chenshuai2144** [comment]
{1:"dd"} 和 { "1": "dd" } 是等价的，
但是 1!=="1" table 就认为他一直在新增数据
