### ISSUE TITLE
👑 [需求] 卡片列表的prolist设置rowSelection没效果

### ISSUE THREAD

**Issue by weirui88888** [ant-design/pro-components#2199]
### 🥰 需求描述

我想用prolist的**卡片列表**格式，但是设置了rowSelection后，复选框并没有出来。是不支持卡片列表的复选吗？

### 🚑 其他信息

![截图](https://m0-file2.bybutter.com/uploaded/toaster/d813ae5b4465453ab601fdbf59de7fe9.png)

**Comment by chenshuai2144** [comment]
是的，暂时还不支持

**Comment by DerrickTel** [comment]
可以关闭了，好像已经支持了。
https://procomponents.ant.design/components/list

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常感谢您的提醒，确实现在 ProList 的卡片列表格式支持 rowSelection 了。如果您在使用中还有其他问题，欢迎随时向我们反馈。
