### ISSUE TITLE
🐛[BUG] [ProLayout] Document title changed to 'Ant Design Pro' when route.name is not a string.

### ISSUE THREAD

**Issue by chiaweilee** [ant-design/pro-components#2200]
### 📷 复现步骤

```jsx
routes: [
    {
      path: "/welcome",
      name: <div>欢迎</div>, // 👈 here
      icon: <CrownOutlined />,
      component: "./Welcome"
    },
    {
      path: "/admin/sub-page2",
      name: "二级页面",
      icon: <UserOutlined />,
      component: "./Welcome"
    },
    {
      path: "/admin/sub-page3",
      name: "三级页面",
      icon: <SmileOutlined />,
      component: "./Welcome"
    }
  ];
```

### 🏞 期望结果

`document.title` should not changed to `Ant Design Pro`.

### 💻 复现代码

https://codesandbox.io/s/chenjinshidaohang-forked-v1x7b?file=/App.tsx:284-669

### © 版本信息

- ProComponents 版本: latest
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
What do you think should be changed？

We now use the title of ProLayout

**Comment by chiaweilee** [comment]
> What do you think should be changed？
> 
> We now use the title of ProLayout

Well. Every project have a default title, right? like 'Taobao'.
Then, out of nowhere, 'Taobao' changed to 'Ant Design Pro'.

💣 Boom!! The developer of this project will be fired.

I believe, `document.title` **shouldn't be changed** if ProLayout can not get a string content from `route.name`.

![image](https://user-images.githubusercontent.com/29817353/111438923-c9026980-873f-11eb-9e35-ccac981d17d4.png)

**Comment by chenshuai2144** [comment]
I did not understand what you said, do you think we should not set default values?

**Comment by chiaweilee** [comment]
> I did not understand what you said, do you think we should not set default values?

When `route.name` is NOT a `string`,

```jsx
routes: [
    {
      path: "/welcome",
      name: <div>欢迎</div>, // 👈 here
    }
]
```

`BasicLayout` got `props.title` which is `false`.

```jsx
useDocumentTitle(pageTitleInfo, props.title || defaultSettings.title);
```

`defaultSettings.title` in `defaultSettings.js` which is `Ant Design Pro`

👆 This is what happend.
It is depressing, I have to do this:

```jsx
new MutationObserver(function(mutationsList) {
  mutationsList.forEach(function(item) {
    if (item.target.innerHTML === 'Ant Design Pro') {
      document.title = 'My Project Title';
    }
    }
  });
}).observe(document.querySelector('title'), {
  attributes: false,
  childList: true,
  subtree: false,
});
```

**Comment by chenshuai2144** [comment]
You can set props.title to avoid this problem. 

If you have an idea, you can come to pr to modify it

**Comment by mouthguo** [comment]
one said 
> `BasicLayout` got `props.title` which is `false`.

and it can be set `false`, also the `useDocumentTitle ` .

it needs to modify `useDocumentTitle(pageTitleInfo, props.title || defaultSettings.title);` to recognize `false`, right ?

maybe, i guess, there is a case: not everyone need to set props.title,  only logo can be satisfied.

**Comment by chenshuai2144** [comment]
If props.title is false, it should not. I think this is a bug. Can you help me with a pr?

**Comment by mouthguo** [comment]
if there will be a pr to fix the bug,
maybe some action should be declared.

we already known that:

>  `props.title` got `false`, `useDocumentTitle(pageTitleInfo, props.title || defaultSettings.title)` should recognize `false`.

just `props.title === false ? false : (props.title || defaultSettings.title)` will be enough,
its easy to fix.
but, firstly, `route.name` should be a `string` type as what `MenuDataItem` declared in `layout/src/typings.ts`.

if `route.name` got a `string` type as what it declared, fix the bug, perfect !

but the author use `route.name` NOT a `string`, fix the bug, when `path` is `/welcome`, it will be the previous title:

```bash
# step 1. enter to sub-page2
/admin/sub-page2 # -> document.title is '二级页面'
# step 2. jump to welcome
/admin/sub-page2 -> /welcome # -> document.title is '二级页面'
```

`props.title` is `false`, there is NOT a `'My Project Title'` string to fallback, it seems that we can not know the project title.

if we modify `useDocumentTitle` to record the origin title before 'the first time to modify document.title', its a bit of weird.

any idea ?

**Comment by chenshuai2144** [comment]
I think it's better to do nothing
