### ISSUE TITLE
🧐[问题] ModalForm/DrawerForm 如何重置表单并关闭

### ISSUE THREAD

**Issue by wangming-0215** [ant-design/pro-components#2203]

**Comment by mouthguo** [comment]
直接给你上一段 `ModalForm` 里面的代码哈

```jsx
/** 如果 destroyOnClose ，重置一下表单 */
  useEffect(() => {
    if (visible) {
      isFirstRender.current = false;
    }
    // 再打开的时候重新刷新，会让 initialValues 生效
    if (visible && modalProps?.destroyOnClose) {
      formRef.current?.resetFields();
    }
  }, [modalProps?.destroyOnClose, visible]);
```

**Comment by wangming-0215** [comment]
> 直接给你上一段 `ModalForm` 里面的代码哈
> 
> ```js
> /** 如果 destroyOnClose ，重置一下表单 */
>   useEffect(() => {
>     if (visible) {
>       isFirstRender.current = false;
>     }
>     // 再打开的时候重新刷新，会让 initialValues 生效
>     if (visible && modalProps?.destroyOnClose) {
>       formRef.current?.resetFields();
>     }
>   }, [modalProps?.destroyOnClose, visible]);
> ```

怪我没说清楚。源码我看了，但是上面的代码不是我想要的，我想要的是点击“重置”按钮时，重置表单并关闭模态框，同时刷新URL，不是在模态框关闭的时候重置表单。

**Comment by mouthguo** [comment]
> 我想要的是点击“重置”按钮时，重置表单并关闭模态框，同时刷新URL

`刷新URL`没理解什么意思；单纯从 `重置表单并关闭模态框`来看，应该就是需要下次弹出时是重置过的值吧。

有先后操作顺序的需求的话，可以通过`formRef`来拿到`FormInstance `，手动操作也可以的哦

**Comment by zhangheng0317** [comment]
onReset

**Comment by wangming-0215** [comment]
> > 我想要的是点击“重置”按钮时，重置表单并关闭模态框，同时刷新URL
> 
> `刷新URL`没理解什么意思；单纯从 `重置表单并关闭模态框`来看，应该就是需要下次弹出时是重置过的值吧。
> 
> 有先后操作顺序的需求的话，可以通过`formRef`来拿到`FormInstance `，手动操作也可以的哦

我先简单描述一下我的场景：就是实现一个高级搜索功能，高级搜索的表单时使用`DrawerForm`实现的，有两个按钮，“重置”和“确定”，点击确定后将搜索条件同步到URL，点击“重置”按钮，会将搜索条件清空，也就是重置表单。我是了`onReset`，但是没有效果。

**Comment by wangming-0215** [comment]
> onReset

`onReset`试了，没效果啊

**Comment by zhangheng0317** [comment]
看来得这么写
submitter={{
        resetButtonProps: {
          onClick: onReset,
        },
      }}

**Comment by mouthguo** [comment]
> > > 我想要的是点击“重置”按钮时，重置表单并关闭模态框，同时刷新URL
> > 
> > 
> > `刷新URL`没理解什么意思；单纯从 `重置表单并关闭模态框`来看，应该就是需要下次弹出时是重置过的值吧。
> > 有先后操作顺序的需求的话，可以通过`formRef`来拿到`FormInstance `，手动操作也可以的哦
> 
> 我先简单描述一下我的场景：就是实现一个高级搜索功能，高级搜索的表单时使用`DrawerForm`实现的，有两个按钮，“重置”和“确定”，点击确定后将搜索条件同步到URL，点击“重置”按钮，会将搜索条件清空，也就是重置表单。我是了`onReset`，但是没有效果。

如果只是要重置，`submitter` 是可以满足的
```
// 1. 最简单的方式，这个最终会调用 Submitter 组件内的 reset 方法
submitter={{
    searchConfig: {
        resetText: '重置'
    }
    resetButtonProps: {
        preventDefault: false
    }
}}

// 2. onClick 事件里面做重置， formRef 是从 ModalForm 那里拿到的
submitter={{
    searchConfig: {
        resetText: '重置'
    }
    resetButtonProps: {
        onClick: () => {
            formRef.current?.resetFields()
        }
    }
}}
```

如果要重置之后弹窗也消失
```
// 在这里操作一下比较省事
modalProps={{
    onCancel: (e) => {
        formRef.current?.resetFields()
    },
}}
```

同步到URL指的是 `syncToUrl` 吗？这个我需要看看 `URLSearchParams` 先

**Comment by chenshuai2144** [comment]
@mouthguo  有兴趣搞个demo吗？

**Comment by mouthguo** [comment]
@chenshuai2144 请问是在这里提供一个 `codeSandBox` ，还是说在文档那边加一个示例呢？

**Comment by chenshuai2144** [comment]
文档那边加个demo吧 怎么样

**Comment by mouthguo** [comment]
好啊，我周末看看搞一下

**Comment by chenshuai2144** [comment]
感谢 @mouthguo
