### ISSUE TITLE
🐛[BUG]PageContainer滚动页和ModalForm结合使用时,设置getContainer导致form样式失效

### ISSUE THREAD

**Issue by zhangheng0317** [ant-design/pro-components#2207]
### 🐛 bug 描述

页面有滚动条,在弹出ModalForm后,弹出层后的内容还可以滚动(官网的案例也有同样问题)
为了不让后面的内容滚动,我在ModalForm的modalProps中加入了getContainer: () => document.body.
确实阻止了内容滚动,但同时ModalForm中的表单组件样式丢失,width='sm/md/...'无效, 设置layout='vertical'也无效

### 📷 复现步骤

`<ModalForm
      visible={visible}
      title="编辑组织"
      initialValues={data ?? undefined}
      layout="vertical"
      modalProps={{
        onCancel: () => onClose(),
        destroyOnClose: true,
        getContainer: () => document.body,
      }}
      onFinish={onFinish}
    >
  <ProFormText label="组织机构名称" name="name" width="md" />
</ModalForm>`

### 🏞 期望结果

既可以阻止页面滚动,同时保持原有样式不变

### © 版本信息

- ProComponents 版本: 5
- umi 版本 3.2
- 浏览器环境 edge
- 开发环境 win

### 🚑 其他信息

得到效果
![image](https://user-images.githubusercontent.com/76459860/111270754-37292c80-866b-11eb-8faf-ec524b355b03.png)
![image](https://user-images.githubusercontent.com/76459860/111271380-11e8ee00-866c-11eb-8c04-7799b8f72661.png)

原来效果
![image](https://user-images.githubusercontent.com/76459860/111271564-55435c80-866c-11eb-8212-d6c5ffb6ff40.png)
![image](https://user-images.githubusercontent.com/76459860/111271475-3218ad00-866c-11eb-99eb-28deee651639.png)

**Comment by chenshuai2144** [comment]
这个是因为不在form里面了，你自定义以下宽度吧，我来想想怎么处理这种情况
