### ISSUE TITLE
ProDescriptions 操作按钮如何显示在左上角 extra 默认显示在右上角👑 [需求]

### ISSUE THREAD

**Issue by MoonSeeing** [ant-design/pro-components#2208]
### 🥰 需求描述

extra 默认 是显示在右上角 不是很灵活 有时候会跟 drawer或者modal重合，是否可以显示在左上角呢

### 🧐 解决方案

umi 项目中 在global.less 添加 
```
.ant-descriptions-extra {
  margin-left: 0px !important;
}
```
是否 合理?
而文档中提到覆盖样式的方式 却不生效
![image](https://user-images.githubusercontent.com/19420622/111291700-69925400-8682-11eb-8b82-065013b64f92.png)

```
:global {
  .ant-descriptions-extra {
    margin-left: 0px ;
  }
}
```

**Comment by mouthguo** [comment]
ProDescription 这边只做了个简单的样式调整。你这个还是属于antd的范畴，去看了下那边的代码，
因为`ant-descriptions-title`的`flex: auto`把左侧撑开了，单纯只修改 `ant-descriptions-extra` 的确是不会生效的哈

**Comment by MoonSeeing** [comment]
> ProDescription 这边只做了个简单的样式调整。你这个还是属于antd的范畴，去看了下那边的代码，
> 因为`ant-descriptions-title`的`flex: auto`把左侧撑开了，单纯只修改 `ant-descriptions-extra` 的确是不会生效的哈

我的意思是 添加的 margin-left: 0px  并没有覆盖.ant-descriptions-extra默认的 margin-left：'auto'

**Comment by mouthguo** [comment]
不好意思，应该是文档提供代码示例没有更新，造成误解了。
`pro` 是基于 `umi` 脚手架搭建的，可以看一下这边提供的示例[assets-css](https://umijs.org/zh-CN/docs/assets-css)

`:global` 是 [css modules](https://github.com/css-modules/css-modules) 提供的，而 `global.less` 并不是以 `css modules` 的方式引入的

另外，关于是否合理，要看你的项目意图，整体设计方案等，来决定是否需要做全局覆盖。
举个例子：
```
// global.less
// 比如加个作用域
.foo {
     .ant-descriptions-extra {
        margin-left: 0px;
    }
}

// page.jsx

// 有需要的就用
<Descriptions className="foo" />
// 没有需要的，不受影响
<Descriptions />

```
