### ISSUE TITLE
👑 [需求] ProFormList - support multilanguage for action tooltip  

### ISSUE THREAD

**Issue by lukenvn** [ant-design/pro-components#2209]
### 🥰 需求描述
Hi guys, 

Thank you so much for your effort on pro components, I really love your products.
While using the ProFormList component for our project, I just found out the action tooltips still in Chinese when I change the language.
![image](https://user-images.githubusercontent.com/7608032/111295459-f8e93880-867d-11eb-811b-65e5049959bf.png)

 So is it possible that we can change it?

### 🧐 解决方案
a new property for ProfFormList for custom action properties
ex:
```
actionProps={
  deleteTitle:'custom title',
  duplicateTitle:'custom title'.
}
```
Or it will be better if you guy apply multi language support default for that actions, 
### 🚑 其他信息
Here is my current workaround solution but i'm not so sure, is there any side effect for it 
![image](https://user-images.githubusercontent.com/7608032/111295599-27ffaa00-867e-11eb-8d9a-57b21439fa4f.png)

**Comment by chenshuai2144** [comment]
```
  copyIconProps = {
    Icon: CopyOutlined,
    tooltipText: '复制此行',
  },
  deleteIconProps = {
    Icon: DeleteOutlined,
    tooltipText: '删除此行',
  },
```

look here
