### ISSUE TITLE
🧐[问题]protable树状数据，期望能通过onExpand动态请求数据

### ISSUE THREAD

**Issue by 2470589018** [ant-design/pro-components#221]
### 🧐 问题描述

最近有个需求是关于表格树状数据展示的，初始数据是通过request，点击加号展开时动态请求接口获取子级数据，可以用onExpand监听到展开事件，但是发现不知道怎么赋值，想问下各位大佬，用了request就无法使用dataSource吗？我怎么能实现动态请求树状数据？如能指教感激不尽，祝各位2020一切安好！

**Comment by chenshuai2144** [comment]
嵌套多个 table 呢？

**Comment by 2470589018** [comment]
> 嵌套多个 table 呢？

感谢大佬指教，通过递归嵌套table实现了，在公司不方便贴代码，再次感谢大佬的帮助！
