### ISSUE TITLE
🐛[BUG] EditableProtable column 表单校验失败无法与 Form 关联问题

### ISSUE THREAD

**Issue by jianghai** [ant-design/pro-components#2210]
### 🐛 bug 描述

EditableProtable column 表单校验失败，Form onFinish 仍然执行了回调

### 📷 复现步骤

标题设置必填，执行 submit，onFinish 执行回调

### 🏞 期望结果

Form onFinish 可以等待 EditableProtable 校验成功后执行回调

### 💻 复现代码

```tsx
import React, { useState } from 'react';
import { Button, Input, Form } from 'antd';
import { EditableProTable } from '@ant-design/pro-table';

function Test() {
  const initialValues = {
    username: 'aa',
    list: [{
      id: 1,
      title: 'xxx'
    }]
  };
  const [editableKeys, setEditableKeys] = useState(initialValues.list.map(item => item.id));
  return (
    <Form
      name="basic"
      onFinish={(values) => {
        console.log(values, '表单内容');
      }}
      initialValues={initialValues}
      onFinishFailed={(err) => {
        console.log(err, '表单校验失败信息');
      }}
    >
      <Form.Item
        label="Username"
        name="username"
        rules={[{ required: true, message: 'Please input your username!' }]}
      >
        <Input />
      </Form.Item>
      <Form.Item label="list" name="list" trigger="onValuesChange" rules={[{
        required: true,
      }, {
        max: 2
      }]}>
        <EditableProTable
          // maxLength={2}
          columns={[{
            title: '标题',
            dataIndex: 'title',
            editable: true,
            formItemProps: {
              rules: [{
                required: true
              }]
            }
          }, {
            title: '操作',
            valueType: 'option',
            render(text, record) {
              return null;
            }
          }]}
          rowKey="id"
          recordCreatorProps={{
            newRecordType: 'dataSource',
            record: () => ({
              id: Date.now(),
            }),
          }}
          toolBarRender={false}
          editable={{
            type: 'multiple',
            editableKeys,
            onChange: setEditableKeys,
            actionRender: (row: any, config, defaultDoms) => {
              return [defaultDoms.delete];
            }
          }}
        />
      </Form.Item>
      <Form.Item>
        <Button type="primary" htmlType="submit">
          Submit
        </Button>
      </Form.Item>
    </Form>
  );
}

Test.displayName = 'TableForm';

export default Test;

```

### © 版本信息

- @ant-design/pro-table 版本: 2.30.4
- umi 版本
- 浏览器环境 chrome
- 开发环境 mac OS

**Comment by chenshuai2144** [comment]
因为不是一个表单，这个的确有点麻烦，你有好的想法吗

**Comment by jianghai** [comment]
理论上被 Form.Item 包的组件都可以共享一个 form 吧，组件内部不能拿到 context form ?

**Comment by chenshuai2144** [comment]
因为 ProTable 其实是

```
<Form>
   <Table/>
</Form>
```

form 被阻断了，是为了做可编辑表格

**Comment by minuux** [comment]
参考了list的样例，可以校验到是否维护了数据，但每一行中的item各自的rule,好像只能手动处理了，
没有找到类似 `form.setFieldserror`的操作手动设置上错误信息

```js
<ProForm.Item
rules={[
        {
          validator: async (_, values) => {
    
            if (values.length === 0) {
         
              throw new Error('请至少维护一条数据！');
            }

        },
      ]}
>
<EditableProTable/>
</Form.item>
```

**Comment by IversonTian** [comment]
> 因为不是一个Form 实例，这个的确有点麻烦，你有好的想法吗

可以看看我写的这个 Demo：
https://blog.csdn.net/Iversons/article/details/116237226

**Comment by LoveEocding** [comment]
使用Form.item 自定义单选选验证，在里面触发edittable实例的验证。把触发时机改成none 就只会在提交的时候出发全局验证

**Comment by BeatsKitano** [comment]
办法之一：
const [tableForm] = Form.useForm();
<EditableProTable 
    rowKey="id"
    controlled 
    editable={{
      form: tableForm, // 一定要设置form
      type: 'multiple',
      editableKeys,
      actionRender: (row, config, defaultDoms) => {
        return [defaultDoms.delete];
      },
      onChange: setEditableRowKeys,
    }}
</EditableProTable>
在提交时主动await 触发校验

onFinish={async (values) => {
            try {
              await tableForm.validateFields();
            } catch {
              return Promise.reject(false);
            }

            try {
              await opsClient.BatchUpdateLinkSalesConfig(values);
              message.success('配置成功');
              props.onFinished?.();
              return true;
            } catch (err) {
              message.error('配置失败'+ err.message);
              return false;
            }
          }}
