### ISSUE TITLE
🧐ProList 怎么设置行的点击事件？？？

### ISSUE THREAD

**Issue by zhj778930960** [ant-design/pro-components#2213]

**Comment by chenshuai2144** [comment]
现在还不支持有兴趣搞个pr吗？

**Comment by zhj778930960** [comment]
> 现在还不支持有兴趣搞个pr吗？
可以啊

**Comment by zhj778930960** [comment]
不好意思  最近一直在写业务  暂时没啥时间了  后端跑路了 接手了后端的活
________________________________
发件人: 陈帅 ***@***.***>
发送时间: 2021年4月20日 14:25
收件人: ant-design/pro-components ***@***.***>
抄送: 张豪杰 ***@***.***>; Author ***@***.***>
主题: Re: [ant-design/pro-components] 🧐ProList 怎么设置行的点击事件？？？ (#2213)


Closed #2213<https://github.com/ant-design/pro-components/issues/2213> via #2543<https://github.com/ant-design/pro-components/pull/2543>.
