### ISSUE TITLE
🐛[BUG] ProFormText通过fieldProps赋值后, getFieldsValue就获取不到数据了

### ISSUE THREAD

**Issue by huangkaibo** [ant-design/pro-components#2216]
### 🐛 bug 描述

`<ProFormText>`通过`fieldProps={{ value: "text2" }}`赋值后, getFieldsValue就获取不到数据了

### 💻 复现代码

https://codesandbox.io/s/antd-reproduction-template-forked-szicd?file=/index.js

点下提交按钮, console里看能看出来

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/19745373/111445146-1255b780-8746-11eb-99f0-d8c37c5846e6.png)

**Comment by chenshuai2144** [comment]
不要覆盖 onChange 和 value。
