### ISSUE TITLE
👑 [需求]pro-table 能否增加虚拟滚动

### ISSUE THREAD

**Issue by Petter-li** [ant-design/pro-components#2217]
### 🥰 需求描述
固定表格高度，实现虚拟滚动

**Comment by chenshuai2144** [comment]
最好不要一页展示太多，分页就是一种虚拟滚动。


我记得 antd 有demo，你试试

**Comment by chenshuai2144** [comment]
antd @5 支持了，可以试试了

**Comment by tylerrrkd** [comment]
> > antd [@5](https://github.com/5) 支持了，可以试试了
> 
> antd5 是支持了， 为什么ProTable 传 virtual 没用效果~

@LukerSpringtree 需要结合 `scroll.x` 和 `scroll.y` 使用
