### ISSUE TITLE
🐛[BUG] ProFormTimePicker，设置format问题

### ISSUE THREAD

**Issue by 569202812** [ant-design/pro-components#2230]
### 🐛 bug 描述
ProFormTimePicker.RangePicker 设置了```format="HH:mm"```,返回的信息结构是HH:mm:ss，```antd```里面的TimePicker.RangePicker却是正常的

### 🚑 其他信息
[线上地址](https://codesandbox.io/s/fanweixuanzeqi-antd4140-forked-sb9l7?file=/index.js:563-574)

**Comment by chenshuai2144** [comment]
用 ` fileProps={{ format : HH:mm}}`

**Comment by chenshuai2144** [comment]
好像不行，因为提交的时候我没有读取，所以它总是会被格式化为 HH:mm:ss

**Comment by 569202812** [comment]
> 好像不行，因为提交的时候我没有读取，所以它总是会被格式化为 HH:mm:ss

是的我就是```fileProps={{ format : HH:mm}}```写的

**Comment by chenshuai2144** [comment]
实现起来还挺复杂的，先忍忍

**Comment by 569202812** [comment]
> 实现起来还挺复杂的，先忍忍

嗯嗯目前可以再用moment处理一下
