### ISSUE TITLE
Protable 搜索表单下拉选项过长，选中后，表单布局错乱

### ISSUE THREAD

**Issue by zhangxiangqiang** [ant-design/pro-components#2232]
### 🐛 bug 描述
Protable 搜索表单下拉选项过长，选中一项后，当前下拉表单项布局会掉落下来

### 🏞 期望结果

希望选中过长选项时，多余部分以省略号显示，而不是改变布局

### 💻 复现代码

常规protable 下拉

```
{
      title: '所属门店',
      dataIndex: 'projectId',
      valueType: 'select',
      hideInTable: true,
      fieldProps: {
        placeholder: '请选择所属门店',
        allowClear: true,
        showSearch: true,
        optionFilterProp: 'label',
        options: projectList,
      },
    },

```

### © 版本信息

- ProComponents 版本: "@ant-design/pro-table": "2.30.6"
- umi 版本
- 浏览器环
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30229705/111606211-f3245c00-8811-11eb-8283-208b09894ce1.png)

**Comment by chenshuai2144** [comment]
你给加个 style 吧，这是 antd 常见问题了。但是在这个里面不好改，因为我们不知道剩下了多少。

你可以给个 max-width:100%

**Comment by zhangxiangqiang** [comment]
我试了一下，一层层加max-width:100%，都不行，好像不全是antd的问题，是由横向布局变成了纵向布局，不知你的具体思路是什么；不过我使用 对.ant-form-item用 flex: nowrap;   对.ant-form-item-label用 flex-shrink: 0; 对.ant-form-item-control: flex-grow: 1; min-width: 0; 这样好像是可以的@chenshuai2144
