### ISSUE TITLE
🧐[问题] ProLayout 菜单滚动条如何隐藏

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#2234]
### 🧐 问题描述

菜单滚动条如何隐藏

![mmexport1616067398793](https://user-images.githubusercontent.com/3166799/111636220-39d67e00-8833-11eb-949d-dac05bf028f3.png)

**Comment by chenshuai2144** [comment]
少写点菜单？

如果隐藏了用户怎么滑动滚动条？

**Comment by hihuangwei** [comment]
> 少写点菜单？
> 
> 如果隐藏了用户怎么滑动滚动条？

在收缩情况下影响美观，隐藏后不影响滚动，一般不会按住滚动条滑动，都是用鼠标滚轮，建议增加可以隐藏的api

**Comment by chenshuai2144** [comment]
我们不会修改浏览器的默认行为的

如果想要这样做用css强制覆盖吧  我不推荐这么多菜单 用户体验太差了。隐藏进度条用户会以为无法滑动的

**Comment by hihuangwei** [comment]
> 我们不会修改浏览器的默认行为的
> 
> 如果想要这样做用css强制覆盖吧 我不推荐这么多菜单 用户体验太差了。隐藏进度条用户会以为无法滑动的

如何修改样式，再global.less 覆盖无效

**Comment by chenshuai2144** [comment]
important 无脑上
