### ISSUE TITLE
🐛[BUG]DrwerForm 双滚动条问题，ant的Drawer没有这个问题

### ISSUE THREAD

**Issue by mmjj** [ant-design/pro-components#2236]
### 🏞 期望结果
如何快速解决

### 💻 复现代码
https://procomponents.ant.design/components/modal-form

### © 版本信息

- ProComponents 版本: @ant-design/pro-form@^1.3.0
- umi 版本
- 浏览器环境
- 开发环境 [ mac OS]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/7391697/111644341-b456cc00-883a-11eb-9940-dc0cce00cf8f.png)

**Comment by chenshuai2144** [comment]
dup of  https://github.com/ant-design/pro-components/issues/2398
