### ISSUE TITLE
🧐[问题]request自动重试机制，能否自定义配置，不让其无限重试

### ISSUE THREAD

**Issue by itxve** [ant-design/pro-components#2241]
### 🧐 问题描述
当遇到请求接口不通时，request会每隔几秒触发一次

**Comment by chenshuai2144** [comment]
我记得好像没做重试功能，你是说 table 的吗?

**Comment by yingzhiji** [comment]
@chenshuai2144 我觉得应该是 swr 自带的功能

**Comment by yingzhiji** [comment]
@itxve 是不是 Select 组件？

**Comment by chenshuai2144** [comment]
来个重现，我好像没做这个功能。

**Comment by itxve** [comment]
> @itxve 是不是 Select 组件？

是的

**Comment by yingzhiji** [comment]
@itxve 我看最新的代码里已经去掉了自动重试，你再试试？
![image](https://user-images.githubusercontent.com/21698836/113480896-52989200-94c9-11eb-885c-caad820ac576.png)

**Comment by itxve** [comment]
> @itxve 我看最新的代码里已经去掉了自动重试，你再试试？
> ![image](https://user-images.githubusercontent.com/21698836/113480896-52989200-94c9-11eb-885c-caad820ac576.png)
多谢，明白了，可能是版本底原因

**Comment by jiyingzhi** [comment]
可以的，看这个 https://swr.vercel.app/zh-CN/docs/global-configuration
