### ISSUE TITLE
🐛[BUG] Not able to set default locale for Pro Table

### ISSUE THREAD

**Issue by pawansharma777** [ant-design/pro-components#2243]
### 🐛 bug 描述

There should be an option to set the default locale. e.g. en-US

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/en-US/components/table#internationalization-related-configuration


look here
