### ISSUE TITLE
🐛[BUG] EditableProTable 有数据但是表格显示不出来

### ISSUE THREAD

**Issue by huangkaibo** [ant-design/pro-components#2244]
### 🐛 bug 描述

在constructor里初始化state时填数据, 就能正常显示
但是如果在componentDidMount里setState填数据, 能发现数据有了, 但是表格不显示

### 💻 复现代码

https://codesandbox.io/s/shishibaocundebianjibiaoge-forked-rnnei?file=/App.jsx

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/19745373/111733146-346c4880-88b2-11eb-8dbe-df7b4143cb9c.png)

**Comment by chenshuai2144** [comment]
因为是用 initialvalues 实现的，你最好把 id 换一下，不然她不会重新生成行
