### ISSUE TITLE
🐛[BUG]protable 分页onChange事件所获取的值跟实际的不符

### ISSUE THREAD

**Issue by ccloveak** [ant-design/pro-components#2245]
### 🐛 bug 描述

```
onChange={(pagination, filters, sorter) => {
                    console.log(pagination);
                }}
```
* pagination的值跟实际的有差异

### 📷 复现步骤

https://user-images.githubusercontent.com/38686314/111732849-d5123680-88b9-11eb-8c61-1c0ef72464cb.mp4

请看页面右边log里current的值跟 有左边页面上的当前页显示
目前是只在切换pagesize的时候发生

### 🏞 期望结果

切换pagesize的时候的时候 current自动变为1

### © 版本信息

- "@ant-design/pro-table": "^2.17.0",
- "antd": "^4.12.3",
- 浏览器环境 chrome
- 开发环境 [ mac OS]

**Comment by ccloveak** [comment]
![image](https://user-images.githubusercontent.com/38686314/112438718-908c0c80-8d8b-11eb-9c24-dd741dfc2b58.png)
 在 onChange 里加其他的方法也不是实时触发的 期望实时反馈 所见即所得

**Comment by chenshuai2144** [comment]
这个是因为我重置了一下页面，因为换了pageSize，这一行不一定存在，我会做一下处理

**Comment by chenshuai2144** [comment]
这个暂时无解，你可以先用 pagination.onChange ，我会每次修改都触发 onChange
