### ISSUE TITLE
🐛[BUG]Pro-table: pro-table在升级到2.5.13时，出现Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by laoxubuer** [ant-design/pro-components#225]
### 🐛 bug 描述
使用block开发模式生成的查询表格，pro-table在升级到2.5.13时，出现以下标红的warning信息，更换旧版本不会报错，但是dateRange会出问题

devScripts.js:5836 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `FormSearch`. See https://fb.me/react-warning-keys for more information.
    in FieldWithContext (created by FormSearch)
    in FormSearch (created by ProTable)
    in div (created by ProTable) 
......

devScripts.js:5836 Warning: React does not recognize the `labelCol` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `labelcol` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by ForwardRef(Select))
    in ForwardRef(Select) (created by Select)
    in Select (created by Context.Consumer)
    in Select (created by ForwardRef(FieldSelect))
......

### 📷 复现步骤

使用block开发模式生成的查询表格，pro-table在升级到2.5.13时

### 🏞 期望结果

消除warning，且valueType为dateRange类型的col不出问题

### © 版本信息

- Antd Pro 版本： 4.2.0

- ProComponents 版本: 
    "@ant-design/pro-descriptions": "^1.0.1",
    "@ant-design/pro-layout": "^6.4.1",
    "@ant-design/pro-table": "^2.5.13",

- umi 版本 ^3.2.14

- 浏览器环境 Chrome latest

- 开发环境 Windows 10

- Node 版本： v12.16.2

**Comment by yaoguoba** [comment]
同样问题

**Comment by HengCC** [comment]
经过验证 从2.5.10 之后会有问题. 2.5.10不会有问题.  我看了下依赖似乎是换成了pro-form导致的.  建议 临时降版本解决

**Comment by laoxubuer** [comment]
> 经过验证 从2.5.10 之后会有问题. 2.5.10不会有问题. 我看了下依赖似乎是换成了pro-form导致的. 建议 临时降版本解决

我试过2.5.10会导致查询和重置按钮发送请求失效；另外dateRange的问题好像还是存在。主要封装得台厉害，不太好改动。实在不行，后面考虑直接用antd得table

**Comment by leohxj** [comment]
吐槽一句，更新的 bug 比 feature 多。

**Comment by laoxubuer** [comment]
更新2.5.14后，原有warning error未消失，另外增加如下warning error

devScripts.js:5836 Warning: React does not recognize the `isDefaultDom` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdefaultdom` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
......

**Comment by 4tj** [comment]
遇到同样问题，用官方的演示例子 https://codesandbox.io/s/modest-kilby-zds9w 会有3个warning

1. `Each child in a list should have a unique "key" prop.` 
2. ` React does not recognize the `labelCol` prop on a DOM element.`
3. `React does not recognize the `isDefaultDom` prop on a DOM element.`

**Comment by aLIEzsss4** [comment]
没有解决啊，"@ant-design/pro-table": "^2.5.15" 依旧报错 @chenshuai2144

**Comment by aLIEzsss4** [comment]
> 没有解决啊，"@ant-design/pro-table": "^2.5.15" 依旧报错 @chenshuai2144

重启服务解决了
