### ISSUE TITLE
🐛[BUG]ProTable 的搜索表单ProForm ProFormText 

### ISSUE THREAD

**Issue by langengel** [ant-design/pro-components#2250]
### 🐛 bug 描述

```
size="small"
          pagination={{ pageSize: 10 }}
          request={async (params: User.QueryForm, sort, filter) => {
            if(!params.u_phone){
              unset(params,'u_phone')
            }
            if(!params.full_name){
              unset(params,'full_name')
            }
            
            window.console.log(params, sort, filter)
            return await admin_list(params)
          }}
          form={{ ignoreRules: false }}
```

我在设计组合表单的查询参数时，由于某些条件时可选项，非必须填写的，首页渲染页面后没有将必填字段传递给params,这是正确的，但是输入框获得焦点后，不管输入框内是否有值，该字段依然被以空置的形式传递给params.

我尝试过点击充值表单后，此现象消失，可选字段不会被传递到params，我找不到是因什么问题导致，也查询过一下资料，并没有得到解决，所以我只好将我到代码修改成了以上到判断方式进行表单提交查询

不知官方有没有更好的解决方案 
谢谢🙏

**Comment by chenshuai2144** [comment]
form没有绑定到吧，你是不是一个formItemRender 引入了两个 input，并且没有公用 onchange

**Comment by langengel** [comment]
是ProTable自带的搜索表单 我并没有改造它，我只是在Columns中配置了而已，配置不配置效果都一样呢
`<ProTable
          actionRef={actionRef}
          columns={Columns}
          scroll={{ x: 1400 }}
          size="small"
          pagination={{ pageSize: 10 }}
          request={async (params: User.QueryForm) => {
            return await admin_list(params)
          }}
          form={{ ignoreRules: false }}
          search={{
            defaultCollapsed: true,
            labelWidth: 'auto',
            optionRender: ({ searchText, resetText }, { form }) => {
              return [
                <Button
                  key="searchText"
                  type="primary"
                  onClick={() => {
                    form?.submit();
                  }}
                >
                  {searchText}
                </Button>,
                <Button
                  key="resetText"
                  onClick={() => {
                    form?.resetFields();
                  }}
                >
                  {resetText}
                </Button>,
                <Button key="out" onClick={Export}>导出</Button>,
              ];
            },
          }}
          toolBarRender={() => [
            <Button key="add_user" type="primary" onClick={addadmin}>
              <PlusOutlined />
            添加管理员
          </Button>,
          ]}
        // 多选操作
        // rowSelection={{ selections: [Table.SELECTION_ALL, Table.SELECTION_INVERT] }}
        >
        </ProTable>`

**Comment by chenshuai2144** [comment]
Columns 配置让我看看

**Comment by langengel** [comment]
```
const Columns: ProColumnType<User.UserData>[] = [
    { title: "头像", dataIndex: "headimgurl", width: 50, valueType: "avatar", hideInSearch: true },
    {
      title: "姓名", dataIndex: "full_name", valueType: "text",
      formItemProps: {
        rules: [
          { pattern: /^[\u4E00-\u9FA5]{2,}/, message: "请输入中文姓名" }
        ]
      }
    },
    { title: "昵称", dataIndex: "nickname", valueType: "text", hideInSearch: true },
    { title: "备注", dataIndex: "remarks", valueType: "text", hideInSearch: true },
    {
      title: "手机号", dataIndex: "u_phone", width: 150, valueType: "text", copyable: true,
      formItemProps: {
        rules: [
          { pattern: /^1[34567890]\d{9}/, message: "请填写正确的手机号" },
        ],

      }
    },
    { title: "创建时间", dataIndex: "create_time", width: 150, valueType: "dateTime", hideInSearch: true },
    { title: "创建时间", dataIndex: "create_time", valueType: "dateTimeRange", hideInTable: true },
    { title: "更新时间", dataIndex: "update_time", width: 150, valueType: "dateTime", hideInSearch: true },
    {
      title: "用户状态",
      dataIndex: "u_status",
      hideInSearch: true,
      width: 80,
      valueEnum: {
        1: { text: '已启用', status: 'Success' },
        2: { text: '已禁用', status: 'Error' },
        0: { text: '未激活', status: 'Default' }
      },
      order: 1
    },
    {
      title: "操作", fixed: 'right', valueType: "option", render: (r, d) => [
        <Tooltip key={"tipbind"} placement="topLeft" title={"更换管理员微信"}>
          <Button key={"tipbind"} size="small" type="dashed" onClick={async () => bind_user(d)}>更换</Button>
        </Tooltip>,
        <Tooltip key={"tipenable"} placement="topLeft" title={"启用管理员"}>
          <Button key="enabel" size="small" onClick={async () => {
            await userEnable(d)
          }} hidden={!(d.u_status === 0 || d.u_status === 2)} disabled={d.type} type="primary">启用</Button>
        </Tooltip>,
        <Tooltip key={"tipdisable"} placement="topLeft" title={"禁用管理员"}>
          <Button key="disabel" size="small" onClick={async () => {
            await userDisabled(d)
          }} hidden={(d.u_status !== 1)} disabled={d.type} danger>禁用</Button></Tooltip>,
        <Tooltip key={"tipedit"} placement="topLeft" title={"编辑管理员"}>
          <Button key="edit" size="small" onClick={async () => { await editAdmin(d) }}>编辑</Button>
        </Tooltip>,
        <Tooltip key={"tipdel"} placement="topLeft" title={"删除管理员"}>
          <Popconfirm key={d.id} placement="topLeft" title={`确定删除 ${d.full_name} 管理员吗`} onConfirm={async () => { await userDelete(d) }}
            okText="Yes"
            cancelText="No"
          >
            <Button key="deleteuser" size="small" disabled={d.type} danger>删除</Button>
          </Popconfirm>
        </Tooltip>,
      ]
    },
  ]
```

**Comment by langengel** [comment]
情况是 当搜索表单中text字段 当输入框获得焦点后 在没有输入任何值当时候 点击查询按钮触发请求 它就会带上 full_name="" 或者 u_phone="" 这种参数过去 点击重置之后 再点查询 就没有这两个字段 因为我这两个是可选参数  这种情况带到接口上就触发我到422机制了😄 那个时间组件就不会 时间组件也是可选 但是时间组件是点击清空那个图标就不会带上参数去查询 这个text就会  其它带类型我没有用到 暂时就没有测试 你研究研究看看是bug还是设计初衷就是这样子的 今年正式投入使用antd 有些问题在升级后得到解决 我们尽可能的把发现的问题反馈给你们  不代表全是问题 有时候是不了解组件的设计初衷导致

**Comment by chenshuai2144** [comment]
这个感觉是 onchange 触发了什么导致的，我认真看看，你可以先 omit 一下

**Comment by langengel** [comment]
👌
