### ISSUE TITLE
🐛[BUG] ProFormText 设置 fieldProps.type = hidden 无效

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/pro-components#2253]
### 📷 复现步骤

![image](https://user-images.githubusercontent.com/24469601/111865099-05340500-89a0-11eb-9599-0dbb9a32bd9d.png)

### 💻 复现代码

<ProFormText
        name='version'
        label='version'
        fieldProps={{
          type: 'hidden'
        }}
      />

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
antd 不支持的，用 htmlType
