### ISSUE TITLE
🐛[BUG]ProFormSelect 单选搜索模式，清除搜索选中项后，下拉框仍然保留搜索值

### ISSUE THREAD

**Issue by birdycn** [ant-design/pro-components#2255]
```
          <ProFormSelect
                name="id"
                showSearch
                fieldProps={{ filterOption: false }}
                request={async ({ keyWords }) => {
                  return ....
                }}
              />
```

```
          <ProFormSelect
                name="id"
                showSearch
                fieldProps={{ filterOption: false,onSearch:()=>{...},onClear:()=>{...} }}
                options={...}
              />
```

![QQ截图20210320223042](https://user-images.githubusercontent.com/32201961/111873659-59ed7500-89cc-11eb-9055-66d2a4e6614a.png)
![2](https://user-images.githubusercontent.com/32201961/111873663-5ce86580-89cc-11eb-9206-303d47a5db99.png)

第一步，搜索管理，出现管理员后，选中管理员，点击右侧清除框，再次下拉，高亮“管理”两个字，无法恢复默认选项（request方式清除选中的时候不会触发，使用onClear配合options模式也不行）

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/pro-components/issues/2288
