### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by Chris-LuYi** [ant-design/pro-components#2256]
### 🐛 bug 描述
在 ProForm.Item 里使用 EditableProTable，如果Form.Item配置了name属性，console那边就会有warning,
如果按照提示拿掉name，EditableProTable就无法正常工作（加载和更新）

### © 版本信息

- ProComponents 版本:  @ant-design/pro-table@2.31.0
- umi 版本 umi@3.4.3
- 浏览器环境 Chrome
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/21095553/111893570-948ff580-8a3e-11eb-8eff-5f82947068e1.png)
![image](https://user-images.githubusercontent.com/21095553/111893690-62cb5e80-8a3f-11eb-9b3f-9a8bcd14e693.png)

**Comment by chenshuai2144** [comment]
你忘记包 form 了吧

**Comment by Chris-LuYi** [comment]
肯定包了的   这个表单里还有很多其他控件 都没问题
