### ISSUE TITLE
🧐[问题]EditableProTable和ProTable为什么不合并成一个组件呢？

### ISSUE THREAD

**Issue by birdycn** [ant-design/pro-components#2257]
你好，目前在使用ProTable，本地又组装了一些功能，现在需要用到可编辑表格，发现EditableProTable和ProTable是2个组件，因为对ts语法不熟悉，本地尝试合并2个组件的时候有一些ts错误不会处理。

请问为什么不考虑在Protable通过editbale控制编辑呢？是出于什么考量呢？

**Comment by chenshuai2144** [comment]
就是一个组件，你看看源码，做了一点点预设
