### ISSUE TITLE
🐛[BUG]stepForm最后一步提交表单受控数据无效

### ISSUE THREAD

**Issue by hongmaoxiao** [ant-design/pro-components#2259]
### 🐛 bug 描述

有点莫名其妙的bug，找了好几个小时仍然没能定位问题出在哪里

表单有四步，前三步受控表单数据和非受控表单数据都可以正常获取

最后一步提交的时候，非受控表单数据可以正常获取，受控表单数据为空，而调试的时候，数据已经赋值了，在表单上相应位置也展示出来了

采用的调试方法
```
 1. 交换第三步和第四步
 2. 正常流程去填写表单数据
 3. 发现原来的第四步无法获取的受控表单数据这个时候可以正常获取，而原来第三步能正常获取的受控表单数据无法获取。
 4. 由此可知，本身受控表单数据的赋值逻辑没有问题，问题在于最后一步，不知道最后一步处理上有啥问题
```

### 🏞 期望结果
正常获取最后一步的受控数据

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] "@ant-design/pro-card": "^1.11.4",
    "@ant-design/pro-descriptions": "^1.6.9",
    "@ant-design/pro-form": "^1.18.4",
    "@ant-design/pro-layout": "^6.15.4",
    "@ant-design/pro-list": "^1.5.10",
    "@ant-design/pro-table": "^2.31.0",
- umi 版本 "umi": "3.4.2",
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS] mac

**Comment by hongmaoxiao** [comment]
暂时的一个解决方案是把表单最后一步的受控数据用redux去管理

这个问题暂时没有能力深究了

**Comment by chenshuai2144** [comment]
来个可重现的 demo 吧。
