### ISSUE TITLE
🧐[ProLayout] @ant-design/pro-layout/typings 安装405

### ISSUE THREAD

**Issue by laomaner** [ant-design/pro-components#226]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/32118623/90472125-c2d0ee00-e15a-11ea-9a5d-f2466bf74678.png)
@ant-design/pro-layout/typings 这个包是不是没有暴露出来啊？npm包和yarn包里面都找不到。

**Comment by xrkffgg** [comment]
https://www.npmjs.com/package/@ant-design/pro-layout

**Comment by laomaner** [comment]
> https://www.npmjs.com/package/@ant-design/pro-layout

感谢回复~

![image](https://user-images.githubusercontent.com/32118623/90473727-94eda880-e15e-11ea-82df-37e44282f7b7.png)
不过，不是这样用的吗？pro-layout的包是有的，包含RouterTypes类型定义的这个包没有。或者说，是不是我引用方法错了？

**Comment by xrkffgg** [comment]
Try

`import { RouterTypes } from '@ant-design/pro-layout/lib/typings/'`

**Comment by laomaner** [comment]
> import { RouterTypes } from '@ant-design/pro-layout/lib/typings';

可以了，非常感谢~

**Comment by xrkffgg** [comment]
@chenshuai2144 Is this a typo ?

**Comment by afc163** [comment]
@xrkffgg 来个 PR
