### ISSUE TITLE
🐛[BUG] ProTable  & EditableProTable  树形结构下编辑顶层数据，重新 reload() 会出现重复数据

### ISSUE THREAD

**Issue by wangAhStar** [ant-design/pro-components#2264]
### 🐛 bug  ProTable  & EditableProTable  树形结构下编辑顶层数据Bug

    ProTable 和 EditableProTable 组件，数据（10条）为树形结构， 编辑一级数据（最顶层的数据）成功后 tableRef.current.cancelEditable(key)  &  reloadAndRest()，此时如果接口返回数据（10条）顺序发生变更。则编辑的行会留在Table内，reload 出的新数据也会留在Table内，导致一个Table内出现 2行 一样的数据（共计11条数据）。

### 📷 复现步骤

1、树形结构的数据以及Table
2、编辑一级数据，即Table最顶层的数据。
3、编辑成功后，cancelEditable(key) & reloadAndRest() 接口返回的新数据顺序变更。

### 🏞 期望结果

重新reloadAndRest() 以后，编辑的行，不应该再出现在Table中，而是由新数据全部重新渲染覆盖。

### © 版本信息

- @ant-design/pro-table@2.30.6
- umi 版本
- Chrome
- win 10

**Comment by wangAhStar** [comment]
bug  ProTable  & EditableProTable  树形结构下编辑顶层数据Bug

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


ProTable和EditableProTable树形结构下编辑顶层数据，reload后出现重复数据的Bug

**Comment by chenshuai2144** [comment]
应该是rowkey重复了
