### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by ibryanwu** [ant-design/pro-components#2269]
### 🧐 问题描述
背景：
使用<EditableProTable>时，editable中我使用并绑定了form, 在编辑某行时，当我更新一个字段【数量】，并setFieldsValue另外一个字段的值【金额】，然后每次使用onValueChange将recordList赋值给一个对象数组

问题：
我发现用setFieldsValue赋值【金额】无法触发onValueChange，导致我无法将最新的【金额】字段值时时保存到结果对象中。
请问如何才能在setFieldsValue 一个字段的时候触发onValueChange事件，或者实现某个字段的类似shouldupdate的功能？

### 💻 示例代码
<EditableProTable
。。。
editable={{
          form,
          type: "single",
          editableKeys,
          onValuesChange: (record, recordList) => {
            console.log("onValuesChange", record, recordList);
            setItemTable(recordList);
          },

注:每次值通过操作改变的时候可触发onValuesChange，然后通过setItemTable 保存到一个对象数组中，但setFieldsValue的值就无法被recordList获取到。

**Comment by chenshuai2144** [comment]
setFieldsValue 不能触发 onValueChange 是设计，antd 一直以来都是这样的
