### ISSUE TITLE
🧐[问题]ProTable request的params为什么会有一个_timestamp属性？

### ISSUE THREAD

**Issue by HHHui** [ant-design/pro-components#227]
### 🧐 问题描述

request回调函数第一个参数params会有一个_timestamp属性。

### 💻 示例代码

```js
{ current: page, pageSize: size, ...rest }, sort, filter) => {   }
```
如果没有_timestamp，rest里就是我所有的过滤条件，可以统一转换成后台需要的格式。但是现在多了个_timestamp，而且还不在类型定义里，无法在destruction中剔除.

请问这个_timestamp作用是什么？

**Comment by chenshuai2144** [comment]
是为了 每次 set 必定会触发 reload，我们在框架层面筛一下

**Comment by lyck40012** [comment]
> 是为了 每次 set 必定会触发 reload，我们在框架层面筛一下

我目前是pro-components": "^2.3.57"版本的，为什么查询的时候还会有_timestamp
