### ISSUE TITLE
🧐[问题]EditableProTable：请问如何才能在form.setFieldsValue 一个字段的时候让其触发onValueChange事件，或者实现某个字段的类似shouldupdate的功能

### ISSUE THREAD

**Issue by ibryanwu** [ant-design/pro-components#2270]
### 🧐 问题描述
背景：
使用**EditableProTable**时，editable中我使用并绑定了form, 在编辑某行时，当我更新一个字段【数量】，并setFieldsValue另外一个字段的值【金额】，然后每次使用onValueChange将recordList赋值给一个对象数组

问题：
我发现用setFieldsValue赋值【金额】**无法触发onValueChange**，导致我无法将最新的【金额】字段值时时保存到结果对象中。
请问如何才能在setFieldsValue 一个字段的时候触发onValueChange事件，或者实现某个字段的类似shouldupdate的功能？

急等，谢谢了

### 💻 示例代码
<EditableProTable
。。。
editable={{
          form,
          type: "single",
          editableKeys,
          **onValuesChange: (record, recordList) => {**
            console.log("onValuesChange", record, recordList);
            setItemTable(recordList);
          },

注:每次值通过操作改变的时候可触发onValuesChange，然后通过setItemTable 保存到一个对象数组中，但setFieldsValue的值就无法被recordList获取到。

**Comment by chenshuai2144** [comment]
setFieldsValue 不能触发 onValueChange 是设计，antd 一直以来都是这样的

你都主动 setFieldsValue， antd 认为你知道设么时候处理

**Comment by ibryanwu** [comment]
其实我的需求简单说就是【单价】X【数量】=【金额】，我直接用hook，setXXX来接收整个结果对象数组。
当改变【数量】-cell时，setFieldsValue值【金额=数量X单价】
这时数量的改变用onValueChange能拿到改变后的值，但是【金额】中还是以前的值
所以按你的说法，我要手动再更改一次最终的结果对象数组中对应rowKey的那个对象的金额值，就显得很麻烦了

另外问下 shouldCellUpdate可以解决这个问题么？我虽然试了，但是还是拿不到最新的setFieldsValue后的值
@chenshuai2144

**Comment by chenshuai2144** [comment]
那你通过自定义formItem来实现吧 里面能拿到最新的form

**Comment by ibryanwu** [comment]
刚试了好像不行，在哪里面能拿到最新的form呢？

下面是我column中要set的【金额】，用了renderFormItem ，完了 我从别的cell onChange事件中给它set值，在哪里能拿到最新值呢？
{
      title: "金额",
      tip: "单价 x 主数量 = 金额",
      dataIndex: "amount",
      editable: true,
      key: "amount",
      valueType: "digit",
      align: "right",
      width: 150,
      renderFormItem: () => <Input placeholder="0" />,

      fieldProps: {
        formatter: (value) =>
          `$ ${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ","),
        parser: (value) => value.replace(/\$\s?|(,*)/g, ""),
        precision: 2,

        allowClear: false,
      },
    },

**Comment by chenshuai2144** [comment]
`fieldProps={(form)=> form.xxx }`

这样写
