### ISSUE TITLE
👑 [需求] ValueType='dateTange'或者‘dateTimeRange’ 在轻量筛选中无法显示label

### ISSUE THREAD

**Issue by p354139076** [ant-design/pro-components#2274]
🥰 需求描述

[![6oEnTH.png](https://z3.ax1x.com/2021/03/22/6oEnTH.png)](https://imgtu.com/i/6oEnTH)

希望可以新增label

**Comment by DerrickTel** [comment]
这个好像已经改了，可以关掉了@chenshuai2144
