### ISSUE TITLE
求助哇 这个proupload 选择完文件就红了🧐[问题]

### ISSUE THREAD

**Issue by sunmingyu-Ken** [ant-design/pro-components#2275]
<img width="944" alt="1" src="https://user-images.githubusercontent.com/74940253/111957196-a5b43180-8b26-11eb-994c-f7a1f079ef6c.png">
proupload 选择完文件 报错 但是可以正常请求后台上传

**Comment by chenshuai2144** [comment]
你没写 action 吧，看起来 404 了

**Comment by sunmingyu-Ken** [comment]
是的我不知道他是一步提交的
感谢

**Comment by chenshuai2144** [comment]
去 antd 看看，这玩意写起来还挺复杂的

**Comment by sunmingyu-Ken** [comment]
已经搞定了 给他写了个action 随便返回个东西200就行的,我再点提交送出 OK了
