### ISSUE TITLE
🧐[问题]pro-layout@6.15.3中app.ts中的layout可以通过自定义layout文件替换掉吗? 配置式的许多样式没法调整

### ISSUE THREAD

**Issue by darkfiredarkhalo** [ant-design/pro-components#2277]
### 🧐 问题描述

初次接触`antd-pro`, 的确非常强大哦, 但是也有很多疑惑之处, 有没有相关的群可以进去跟大家讨论下问题的解决方式? 使用v5版本的时候, 要更改顶部导航栏的高度, 但是`app.ts`中的layout不是组件,是配置式的,尝试了添加`style`/`class`/使用`headerTitleRender`, 都无法改变它的高度.   
看文档, 配置式的路由是可以为子路由指定统一的layout, 想问问`app.ts`的作用是什么? 最终是在哪被引用了?整个项目的执行流程是什么?这个`app.ts`并不是一个入口,而是一个配置

**Comment by chenshuai2144** [comment]
app.tsx 是  umi 约定的 runtime 的配置文件，在插件启动的时候会从  app.tsx 读取相关配置。

app.tsx 的 layout 是个配置，不是 layout 的的 dom 本身，你可以理解为是 layout 的 props，所以如果组件不支持你就不能配置。

layout 的配置可以在这里搞 

https://procomponents.ant.design/components/layout
