### ISSUE TITLE
🧐[问题] ProFormList里面自定义表单组件onChange无法改变表单项的值

### ISSUE THREAD

**Issue by xiaoyifan6** [ant-design/pro-components#2278]
### 🧐 问题描述

ProFormList里面自定义表单组件onChange无法改变表单项的值，表单项实现是通过value,onChange改变的，然而在ProFormList里面确无法更新修改的值

### 💻 示例代码

```
<ProFormList>
<ProFormGroup>
                  <ProFormText  name="desc" label="内容描述" required />
<Form.Item name="image" lable="图片上传"> <自定义组件 />  </Form.Item>
</ProFormGroup>
</ProFormList>
```

### 🚑 其他信息

请问ProFormList里面自定义组件咋实现，文档里面并没有详细说明，现在感觉这个ProFormList好难用啊，规则都弄不清楚。

难道不是实现onChange就能改变值吗？？

**Comment by chenshuai2144** [comment]
你的 name 不对，如果不用我们自己的封装就要用 antd 自己的实现方式。


https://ant.design/components/form-cn/#components-form-demo-dynamic-form-items

看看这个 demo，写起来的确是有点蛋疼。

**Comment by zpaimon** [comment]
我用createField来创建的自定义组件，在Form里面没有问题，但是在List里面没有得到值，仔细查看，正确的组件会把key变为 _0_xxx ，而我的组件的key没有变化，请问一下这个需要注意什么？那个地方能改变，找了好半天也没有找到。

**Comment by zpaimon** [comment]
我去，debug了一晚上发现

`import createField from '@ant-design/pro-form/es/BaseForm/createField';
`
`import createField from '@ant-design/pro-form/lib/BaseForm/createField';
`

这两个的效果完全不一样

**Comment by chenshuai2144** [comment]
你发现了webpack 打包的秘密

**Comment by XinYueXiao** [comment]
> ### 🧐 问题描述
> ProFormList里面自定义表单组件onChange�无法改变表单项的值，表单项实现是通过value,onChange改变的，然而在ProFormList里面确无法更新修改的值
> 
> ### 💻 示例代码
> ```
> <ProFormList>
> <ProFormGroup>
>                   <ProFormText  name="desc" label="内容描述" required />
> <Form.Item name="image" lable="图片上传"> <自定义组件 />  </Form.Item>
> </ProFormGroup>
> </ProFormList>
> ```
> 
> ### 🚑 其他信息
> 请问ProFormList里面自定义组件咋实现，文档里面并没有详细说明，现在感觉这个ProFormList好难用啊，规则都弄不清楚。
> 
> 难道不是实现onChange就能改变值吗？？

你解决了吗？我也遇到了这个问题

**Comment by chenshuai2144** [comment]
@XinYueXiao 是因为context的原因拉，你打包两份相同的代码进去了。然后context 互相不认识
