### ISSUE TITLE
🐛[BUG]: Pro-form syncToUrl在hash模式异常

### ISSUE THREAD

**Issue by Hipotecas** [ant-design/pro-components#2279]
### 🐛 bug 描述
官网在history为hash模式下

点击**同步提交结果到url** 点击查询，url异常结果如下

![image](https://user-images.githubusercontent.com/80826665/112014444-dcf60300-8b65-11eb-9e2c-0f048e8e9043.png)

### 🏞 期望结果

URL应该如下：
```js
/#/components/form?name=蚂蚁设计有限公司&useMode=chapter#同步提交结果到-url
```

### 💻 复现代码

无
### © 版本信息

- ProComponents 版本:  pro-form@1.18.4
- umi 版本 @3.4.0
- 浏览器环境 chrome@89
- 开发环境 [mac OS@11.2.1]

**Comment by chenshuai2144** [comment]
这个要修改实现起来有点复杂了

**Comment by quarkcms** [comment]
@chenshuai2144 还有一个问题，最好将pageSize和page这两个参数也加入到syncToUrl上

**Comment by vegawong** [comment]
同样的issue

**Comment by whinc** [comment]
遇到同样的问题，目前 hash 模式的使用还是非常广泛的，有必要支持同步参数时在  history 和 hash 模式中进行切换

**Comment by whinc** [comment]
> 这个要修改实现起来有点复杂了

这块的实现暴露给用户会更灵活些，用户可以自行控制如何序列化和解析 URL 参数

**Comment by feibi** [comment]
> > 这个要修改实现起来有点复杂了
> 
> 这块的实现暴露给用户会更灵活些，用户可以自行控制如何序列化和解析 URL 参数

+1，当值为数组只有一个值时会有问题

**Comment by dingtianxiu** [comment]
hash和search位置不影响应用，插件并不依赖于react context和history去做处理，不支持props获取参数，可通过window.location获取参数

**Comment by zjxpcyc** [comment]
> hash和search位置不影响应用，插件并不依赖于react context和history去做处理，不支持props获取参数，可通过window.location获取参数

是影响的，不一样的模式，切换个地址立马暴露问题。
我感觉这个实现是不是可以放开自定义，这样框架里面也不需要加配置，也不需要加依赖

**Comment by RickieWoo** [comment]
真服了 2025了还没解决？
