### ISSUE TITLE
🐛[BUG]ProTable升级至2.5.14，搜索自定义表单项config中取不到onChange方法

### ISSUE THREAD

**Issue by TernenceWu0702** [ant-design/pro-components#228]
### 🐛 bug 描述
<img width="1004" alt="WX20200818-141051@2x" src="https://user-images.githubusercontent.com/50820522/90476737-aafa6980-e15c-11ea-8bf2-25fa7152067a.png">

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by TernenceWu0702** [comment]
自定义表单项是不需要在绑定vlaue和onChange了吗？

**Comment by chenshuai2144** [comment]
最新版本会帮你自动绑定一下，onChange 不在的问题有点麻烦，稍后会想想办法

**Comment by TernenceWu0702** [comment]
> 最新版本会帮你自动绑定一下，onChange 不在的问题有点麻烦，稍后会想想办法

好的，谢谢
