### ISSUE TITLE
👑 [需求]能否提供统一的less入口文件？

### ISSUE THREAD

**Issue by Ives7** [ant-design/pro-components#2286]
### 🥰 需求描述

类似像`antd/dist/antd.less`这样。

不然的要像下面这样，全部引入。

![image](https://user-images.githubusercontent.com/24537993/112121732-85ee3d80-8bfa-11eb-9990-75472cd135e2.png)

umd虽然提供了全部css，但会导致一个问题，无法订制类似basicLayout-prefix-cls这样的less变量了。

需求背景是，我把procomponents都给external的js部分external掉了，但是每个业务项目可能会有自己的订制皮肤。

所以还是要引用less做一些订制，因为样式文件就不会去external。

但先下没有一个入口样式文件，就要手动逐个引入，需要到源码中查看，非常复杂。

### 🧐 解决方案
增加入口less文件，引入全部的less。

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/24537993/112121701-7bcc3f00-8bfa-11eb-9f82-c64dcecfe72c.png)

**Comment by chenshuai2144** [comment]
https://unpkg.com/browse/@ant-design/pro-table@2.34.4/dist/table.less

提供了
