### ISSUE TITLE
🐛[BUG]proTable全屏后modal弹窗中的form表单保存后，message提示被遮挡问题

### ISSUE THREAD

**Issue by huangzongming** [ant-design/pro-components#2291]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个几乎无解，你需要把全屏的dom设置成任何 dom 的渲染路径。

**Comment by huangzongming** [comment]
啥意思？怎么设置

**Comment by chenshuai2144** [comment]
getPopupContainer | 弹出框（Select, Tooltip, Menu 等等）渲染父节点，默认渲染到 body 上。 | function(triggerNode) | () => document.body |  
-- | -- | -- | -- | --
getTargetContainer | 配置 Affix、Anchor 滚动监听容器。 | () => HTMLElement | () => window | 4.2.0

**Comment by chenshuai2144** [comment]
https://ant.design/components/config-provider-cn/

**Comment by huangzongming** [comment]
好的，已经解决了。多谢~
