### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by zongzheng123** [ant-design/pro-components#2295]
### 🧐 问题描述

当我在ProTable外部套一个antd的Form，proTable的search设置的false,但是外层自定义的form无法控制ProTable的column中render的表单项

### 💻 示例代码
      <Form labelAlign="right" onValuesChange={handleValuesChange} form={form} >
        <ProTable {...tableProps}/>
      </Form>

**Comment by chenshuai2144** [comment]
protable 自己报了个 form，所以你做不到，你可以用 `editable={{ form }}` 来控制
