### ISSUE TITLE
IntlProvider 国际化语言sort不生效

### ISSUE THREAD

**Issue by 1Lin1** [ant-design/pro-components#2305]
![image](https://user-images.githubusercontent.com/43231475/112286139-f746f280-8cc5-11eb-87b6-4742d376b02d.png)
![image](https://user-images.githubusercontent.com/43231475/112286219-0fb70d00-8cc6-11eb-9884-1c21b83f62b0.png)
![image](https://user-images.githubusercontent.com/43231475/112286241-15145780-8cc6-11eb-9cf5-3082b7bf8d49.png)

**Comment by mouthguo** [comment]
参考下这两个例子

> https://procomponents.ant.design/components/table#%E5%9B%BD%E9%99%85%E5%8C%96%E7%9B%B8%E5%85%B3%E7%9A%84%E9%85%8D%E7%BD%AE

> https://procomponents.ant.design/components/table#rtl-%D8%A7%D9%84%D9%86%D8%B3%D8%AE%D8%A9-%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9

**Comment by chenshuai2144** [comment]
antd 的国际化要用 antd 的配置了；
