### ISSUE TITLE
引入pro-table,pro-form打包编译要好几分钟🧐[问题]

### ISSUE THREAD

**Issue by biglemontree** [ant-design/pro-components#2309]
### 🧐 问题描述

打包的大小
![image](https://user-images.githubusercontent.com/13833202/112415246-7ab42280-8d5e-11eb-8834-796c6a45b8a7.png)
![image](https://user-images.githubusercontent.com/13833202/112415478-d4b4e800-8d5e-11eb-8966-fb3603a9099a.png)
打包所花费的时间
![image](https://user-images.githubusercontent.com/13833202/112415653-23628200-8d5f-11eb-9421-8e2372133bd9.png)

### 🚑 其他信息
期望打包体积变小，或是提供可优化的方案

**Comment by chenshuai2144** [comment]
你这个用的不是 umi 是吗？ 来个重现仓库吧

**Comment by biglemontree** [comment]
> 你这个用的不是 umi 是吗？ 来个重现仓库吧

这个是公司内部的脚手架，不太好部署，打包出来都比antd大，不太正常吧

**Comment by chenshuai2144** [comment]
是不太正常，估计是哪里要特殊配置一下

**Comment by jinyu73** [comment]
接手了一个项目，打包后的文件54M，，，，，

**Comment by jinyu73** [comment]
新公司的项目，打包后文件54M。。。。。。

**Comment by chenshuai2144** [comment]
你怎么做到的？

**Comment by jinyu73** [comment]
> 你怎么做到的？

里面的文件被重复打包

**Comment by chenshuai2144** [comment]
做一下分包管理吧，我看你每个包都打包了pro-xxx

**Comment by ycshill** [comment]
我打出来的包也很大，最后问题，怎么解决了呢？
