### ISSUE TITLE
🐛[BUG]当scroll设置x值为'max-content'的同时设置y值,会导致table无数据的时候表头消失

### ISSUE THREAD

**Issue by Hypocrisy-Cc** [ant-design/pro-components#231]
### 🐛 bug 描述

当设置x值为'max-content'的同时设置y值,会导致table无数据的时候表头消失

### 💻 复现代码

e.g. scroll={{ x: 'max-content', y: '500px' }}

<img width="1375" alt="WX20200818-171607@2x" src="https://user-images.githubusercontent.com/17758795/90494981-a5aa1880-e176-11ea-8664-57923c0a8020.png">

### © 版本信息

- pro-table 版本: [2.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
去 antd 提一下吧，看起来是 antd 的逻辑
