### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by yuanye4017** [ant-design/pro-components#2310]
### 🐛 bug 描述
在高级表格中删除最后一页的最后一项时，页码显示不正确。

### 🏞 期望结果
显示当前页或者回到上一页

### © 版本信息

- Protable 版本: ^2.17.0
- umi 版本 3.x
- 浏览器环境 chrome
- 开发环境 mac OS

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/43987769/112431863-03d95280-8d7b-11eb-9f67-88512f458553.png)

**Comment by baiDog** [comment]
使用formRef?.current?.submit() 会回到 第一页。
使用actionRef?.current?.reload() 页面会刷新，但页码没有回到上一页

shite
