### ISSUE TITLE
🐛[BUG] <ProFormSelect.SearchSelect> 输入\字符, 页面就挂掉

### ISSUE THREAD

**Issue by huangkaibo** [ant-design/pro-components#2311]
### 🐛 bug 描述

<ProFormSelect.SearchSelect> 输入\字符, 页面就挂掉

### 🏞 期望结果

如果是bug, 期望修复
如果不打算支持特殊字符, 期望至少不要这么暴力的页面挂掉

### 💻 复现代码

https://codesandbox.io/s/0w0ko?file=/index.js

**Comment by chenshuai2144** [comment]
你正好卡主了一个正则表达式
