### ISSUE TITLE
🐛[BUG] ProFormSwitch 没办法回显数据

### ISSUE THREAD

**Issue by shanzhaozhen** [ant-design/pro-components#2314]
### 🐛 bug 描述

ProFormSwitch 没办法回显数据，设置了defaultChecked: true之后无论是编辑还是新增都是选中状态，不会按照对表单项回显是否选中

### 📷 复现步骤

使用ProFormSwitch组件作为某表单项

### 🏞 期望结果

编辑的时候可以按照表单项的值回显数据

### 💻 复现代码

```
<ProFormSwitch
  name="open"
  label="开启状态"
  checkedChildren="开启"
  unCheckedChildren="停止"
  fieldProps={{defaultChecked: true}}
/>
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/29800728/112487887-0e660d00-8db8-11eb-876b-8fc0c3b0f34d.png)

**Comment by chenshuai2144** [comment]
用  initialValue , initialValue 是归 form 管的， default 不是。
