### ISSUE TITLE
🐛[BUG] ProForm中EditableTable的Input输入框按回车会导致整个ProForm进行提交

### ISSUE THREAD

**Issue by sanmaopep** [ant-design/pro-components#2317]
### 🐛 bug 描述

ProForm中EditableTable的Input输入框按回车会导致整个ProForm进行提交

### 📷 复现步骤

[官方 ProForm和EditableTable联动例子](https://procomponents.ant.design/components/form#proform-%E5%92%8C-editabletable-%E5%90%8C%E6%97%B6%E4%BD%BF%E7%94%A8)

![image](https://user-images.githubusercontent.com/12333609/112587646-f2ef1680-8e38-11eb-9321-0deef590b2a2.png)

### 🏞 期望结果

按回车不会导致ProForm的自动提交

### 💻 复现代码

[官方 ProForm和EditableTable联动例子](https://procomponents.ant.design/components/form#proform-%E5%92%8C-editabletable-%E5%90%8C%E6%97%B6%E4%BD%BF%E7%94%A8)

### © 版本信息

- @ant-design/pro-table@2.30.8
- @ant-design/pro-form@1.18.1

### 🚑 其他信息
无

**Comment by sanmaopep** [comment]
刚看了下，应该是antd form的原因，antd form中的任何一个Input按回车都会触发整个form的submit行为

**Comment by chenshuai2144** [comment]
这个是浏览器的行为，form 的规范就这样的
