### ISSUE TITLE
EditableProTable中当columns中的valueType为checkbox时，不能显示🐛[BUG]

### ISSUE THREAD

**Issue by henryleecn** [ant-design/pro-components#2322]
### 🐛 bug 描述
```
type DataSourceType = {
  id: React.Key;
  selectable?: boolean;
  decs?: string;
};

const defaultData: DataSourceType[] = [
  {
    id: 624748504,
    selectable: true,
    decs: '这个活动真好玩',
  },
  {
    id: 624691229,
    selectable: false,
    decs: '这个活动真好玩',
  },
];


const columns: ProColumns<DataSourceType>[] = [
    {
      title: '是否选择',
      dataIndex: 'selectable',
      valueType: 'checkbox',
      width: '30%',
    },
    {
      title: '描述',
      dataIndex: 'decs',
    },
  ];

<EditableProTable<EditableTableData>
      headerTitle="可编辑表格"
      columns={columns}
      rowKey="id"
      value={dataSource}
      recordCreatorProps={false}
      editable={{
        type: 'multiple',
        editableKeys,
        onValuesChange: (record, recordList) => {
          setDataSource(record);
        },
        onChange: setEditableRowKeys,
      }}
    />

```

### 🏞 期望结果
在是否选择列能显示正常的Checkbox控件

### © 版本信息
    "@ant-design/icons": "^4.5.0",
    "@ant-design/pro-descriptions": "^1.6.9",
    "@ant-design/pro-field": "^1.12.0",
    "@ant-design/pro-form": "^1.18.4",
    "@ant-design/pro-layout": "^6.15.4",
    "@ant-design/pro-table": "^2.31.0",
    "@umijs/plugin-openapi": "^1.0.1",
    "@umijs/route-utils": "^1.0.33",
    "antd": "4.13.0",

**Comment by chenshuai2144** [comment]
valueType=checkbox  的时候要配置 valueEnum，不然不知道怎么生成多选项的

**Comment by datoou** [comment]
@chenshuai2144  如果是一个复选框需要怎么设置？只需要true和false

**Comment by wdage1973** [comment]
在列中渲染即可
 render: (_, record) => (<Checkbox checked={record.channel_flag} disabled />)
![image](https://github.com/ant-design/pro-components/assets/34084699/f2d25481-d296-469b-be53-86872ea574ce)
