### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by paddingC** [ant-design/pro-components#2324]
### 🐛 bug 描述
引入proTable报错

ERROR in ./node_modules/@ant-design/pro-table/es/components/Form/index.js
Module not found: Error: Can't resolve 'fast-deep-equal/es6/react' in '/Users/chaier/react-demo/node_modules/@ant-design/pro-table/es/components/Form'
 @ ./node_modules/@ant-design/pro-table/es/components/Form/index.js 27:0-57 137:14-30
 @ ./node_modules/@ant-design/pro-table/es/index.js
 @ ./src/sui/example/general/pro/index.js
 @ ./src/sui/menus/route.js
 @ ./src/sui/menus/index.js
 @ ./src/sui/index.js
 @ ./src/layout/pages/index.js
 @ ./src/project/crm/pages/index.js
 @ ./src/project/crm/routers/index.js
 @ ./src/project/crm/index.js
 @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js @babel/polyfill ./src/project/crm/index.js
### 📷 复现步骤
![image](https://user-images.githubusercontent.com/28521120/112620732-e207ca80-8e63-11eb-8061-b303c39687b9.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- ^2.31.0
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by tianwawawa** [comment]
怎么改 急！
