### ISSUE TITLE
🐛[BUG]引入proTable报错

### ISSUE THREAD

**Issue by paddingC** [ant-design/pro-components#2325]
### 🐛 bug 描述
引入proTable报错Can't resolve 'fast-deep-equal/es6/react'

ERROR in ./node_modules/@ant-design/pro-table/es/components/Form/index.js
Module not found: Error: Can't resolve 'fast-deep-equal/es6/react' in '/Users/cashd/demo/node_modules/@ant-design/pro-table/es/components/Form'
 @ ./node_modules/@ant-design/pro-table/es/components/Form/index.js 27:0-57 137:14-30
 @ ./node_modules/@ant-design/pro-table/es/index.js
 @ ./src/demo/example/general/pro/index.js
 @ ./src/demo/menus/route.js
 @ ./src/demo/menus/index.js
 @ ./src/demo/index.js
 @ ./src/layout/pages/index.js
 @ ./src/project/crm/pages/index.js
 @ ./src/project/crm/routers/index.js
 @ ./src/project/crm/index.js
 @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js @babel/polyfill ./src/project/index.js
### 📷 复现步骤

)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by MaskHao** [comment]
相同问题，没有使用UMI 和ant-design-pro 脚手架直接引入会有这问题。

**Comment by MaskHao** [comment]
相同问题，没有使用UMI 和ant-design-pro 脚手架直接引入会有这问题。

**Comment by chenshuai2144** [comment]
@ant-design/pro-utils 锁包了？
