### ISSUE TITLE
ProFrom  ProFormSelect组件 showSearch 不合理以及request 返回的新数组无法改变下拉选择框的值🐛[BUG]

### ISSUE THREAD

**Issue by mou-Jia** [ant-design/pro-components#2326]
### 🐛 bug 描述

>  首先,ProFormSelect 使用showSearch 是单选搜索 Demo 中传入的格式为
`[{value:'value',label:'label'}]`
按照通常逻辑,label 属于用户看的到的Text,理应根据**label**进行筛选.
但是现在代码实际是以**value**字段进行筛选.

> 再者,使用ProFormSelect.SearchSelect 完全是Tag的模式,没有单选模式.
这个组件下的筛选却是根据label字段进行的

> 最后,在ProFormSelect request 返回的新数组 无法改变搜索结果.没有设置 option  or valueEnum 值
` request={async(key)=>{
     console.log(key)
     return [{value:1,label:"123"}]
 }}`
按照逻辑来讲reque返回的是最终筛选结果,但是你们的处理流程视乎会在走一遍筛选,就是在request返回的结果根据里面的value在进行筛选.

### © 版本信息

-  @ant-design/pro-form:1.18.4
- umi 版本 3.4.4
- 浏览器环境 chrome
- 开发环境 win10
-

**Comment by mou-Jia** [comment]
`
 fieldProps={{
                        filterOption:() =>{
                          return true
                        },
                      }}
`

最后使用设置如下上,才会是这样的数据格式[{value:'value',label:'label'}] 正常展示正常筛选,正常的将vlaue值返回去onFinish 中!

**Comment by chenshuai2144** [comment]
有兴趣来个pr吗？我觉得你说的很有道理

**Comment by mou-Jia** [comment]
好

**Comment by mou-Jia** [comment]
> 有兴趣来个pr吗？我觉得你说的很有道理
好

**Comment by mou-Jia** [comment]
> 有兴趣来个pr吗？我觉得你说的很有道理

好

**Comment by jiyingzhi** [comment]
第一个问题 #2413 已经解决了，后面两个问题可以来这里 #2527 讨论
