### ISSUE TITLE
🧐[问题] protable树状数据如何实现懒加载子节点

### ISSUE THREAD

**Issue by shanzhaozhen** [ant-design/pro-components#2332]
### 🧐 问题描述

protable树状数据如何实现冷加载。能否强制添加展开按钮，通过点击展开按钮触发后台请求获取子节点，更新在表格对应节点的children里面

### 🚑 其他信息

按照文档实现，必须存在expandedRowRender才会出现展开按钮，而且在展开的时候出现了全部节点都展开的问题。

```
expandable={{
  expandedRowRender: record => <p style={{ margin: 0 }}>{record.description}</p>,
  rowExpandable: record => record.name !== 'Not Expandable',
}}
```

![image](https://user-images.githubusercontent.com/29800728/112730970-7dd22d00-8f6f-11eb-9f0a-7b44dab7d12c.png)

**Comment by chenshuai2144** [comment]
注意一下 rowkey 是不能相同的

**Comment by shanzhaozhen** [comment]
> 注意一下 rowkey 是不能相同的

又关闭了？处理这个rowkey呢，怎么实现表格树的懒加载呢

**Comment by chenshuai2144** [comment]
这个要你自己去拼 dataSource了，是个纯业务的东西。

我推荐你用嵌套表格，虽然对不齐，但是里面有生命周期，可以进行异步的操作

**Comment by shanzhaozhen** [comment]
> 这个要你自己去拼 dataSource了，是个纯业务的东西。
> 
> 我推荐你用嵌套表格，虽然对不齐，但是里面有生命周期，可以进行异步的操作

好吧，其实我实际上也是这样子实现了，如果可以的话希望官网可以给出一个demo，也说明一下吧，DataSource里面的数据中存在children字段时，就会出现[+]按钮，可以用于对树形表格做展开，当children为undefined时[+]将会不显示，因此可以利用该点做树形表格。关键代码和效果请看下面：

![image](https://user-images.githubusercontent.com/29800728/113087681-bc3d4580-9216-11eb-9e34-5fa8f897dca3.png)

```
const [dictionaryData, setDictionaryData] = useState<DictionaryVO[]>([]);

// 更新子节点到表格中
const updateDictionaryData = (list: DictionaryVO[], key: number | undefined, children: DictionaryVO[]): DictionaryVO[] => {
  return list.map(node => {
    if (node.id === key) {
      if (children && children.length > 0) {
        return {
          ...node,
          children,
        };
      }
      return {
        ...node,
        children: undefined
      };
    }
    if (node.children) {
      return {
        ...node,
        children: updateDictionaryData(node.children, key, children),
      };
    }
    return node;
  });
}

// 加载子节点
const onLoadDictionaryChildren = async (expanded: boolean, record: DictionaryVO) => {
  if (expanded && record && record.id) {
    const data = await getDictionaryChildrenById(record.id);    // 通过id获取子节点
    setDictionaryData(origin => updateDictionaryData(origin, record.id, data.map(item => ({ ...item, children: item.hasChildren ? [] : undefined }))));
  }
}

<PageContainer>
  <ProTable<DictionaryVO>
    rowKey="id"
    onExpand={onLoadDictionaryChildren}
    request={async (params, sort) => {
      const res = await getDictionaryRootPage(getPageParams(params), getSortOrder(sort));
      const data = res.records ? res.records.map(item => ({ ...item, children: item.hasChildren ? [] : undefined })) : []
      setDictionaryData(data)
      return {
        total: res.total
      };
    }}
    dataSource={dictionaryData}
    columns={columns}
  />
</PageContainer>

```

**Comment by zhuguangyue** [comment]
> > 这个要你自己去拼 dataSource了，是个纯业务的东西。
> > 我推荐你用嵌套表格，虽然对不齐，但是里面有生命周期，可以进行异步的操作
> 
> 好吧，其实我实际上也是这样子实现了，如果可以的话希望官网可以给出一个demo，也说明一下吧，DataSource里面的数据中存在children字段时，就会出现[+]按钮，可以用于对树形表格做展开，当children为undefined时[+]将会不显示，因此可以利用该点做树形表格。关键代码和效果请看下面：
> 
> ![image](https://user-images.githubusercontent.com/29800728/113087681-bc3d4580-9216-11eb-9e34-5fa8f897dca3.png)
> 
> ```
> const [dictionaryData, setDictionaryData] = useState<DictionaryVO[]>([]);
> 
> // 更新子节点到表格中
> const updateDictionaryData = (list: DictionaryVO[], key: number | undefined, children: DictionaryVO[]): DictionaryVO[] => {
>   return list.map(node => {
>     if (node.id === key) {
>       if (children && children.length > 0) {
>         return {
>           ...node,
>           children,
>         };
>       }
>       return {
>         ...node,
>         children: undefined
>       };
>     }
>     if (node.children) {
>       return {
>         ...node,
>         children: updateDictionaryData(node.children, key, children),
>       };
>     }
>     return node;
>   });
> }
> 
> // 加载子节点
> const onLoadDictionaryChildren = async (expanded: boolean, record: DictionaryVO) => {
>   if (expanded && record && record.id) {
>     const data = await getDictionaryChildrenById(record.id);    // 通过id获取子节点
>     setDictionaryData(origin => updateDictionaryData(origin, record.id, data.map(item => ({ ...item, children: item.hasChildren ? [] : undefined }))));
>   }
> }
> 
> <PageContainer>
>   <ProTable<DictionaryVO>
>     rowKey="id"
>     onExpand={onLoadDictionaryChildren}
>     request={async (params, sort) => {
>       const res = await getDictionaryRootPage(getPageParams(params), getSortOrder(sort));   // 只获取根部节点
>       const data = res.records ? res.records.map(item => ({ ...item, children: item.hasChildren ? [] : undefined })) : []
>       setDictionaryData(data)
>       return {
>         total: res.total
>       };
>     }}
>     dataSource={dictionaryData}
>     columns={columns}
>   />
> </PageContainer>
> ```

你好请问有没有解决方案了啊

**Comment by shanzhaozhen** [comment]
> > > 这个要你自己去拼 dataSource了，是个纯业务的东西。
> > > 我推荐你用嵌套表格，虽然对不齐，但是里面有生命周期，可以进行异步的操作
> > 
> > 
> > 好吧，其实我实际上也是这样子实现了，如果可以的话希望官网可以给出一个demo，也说明一下吧，DataSource里面的数据中存在children字段时，就会出现[+]按钮，可以用于对树形表格做展开，当children为undefined时[+]将会不显示，因此可以利用该点做树形表格。关键代码和效果请看下面：
> > ![image](https://user-images.githubusercontent.com/29800728/113087681-bc3d4580-9216-11eb-9e34-5fa8f897dca3.png)
> > ```
> > const [dictionaryData, setDictionaryData] = useState<DictionaryVO[]>([]);
> > 
> > // 更新子节点到表格中
> > const updateDictionaryData = (list: DictionaryVO[], key: number | undefined, children: DictionaryVO[]): DictionaryVO[] => {
> >   return list.map(node => {
> >     if (node.id === key) {
> >       if (children && children.length > 0) {
> >         return {
> >           ...node,
> >           children,
> >         };
> >       }
> >       return {
> >         ...node,
> >         children: undefined
> >       };
> >     }
> >     if (node.children) {
> >       return {
> >         ...node,
> >         children: updateDictionaryData(node.children, key, children),
> >       };
> >     }
> >     return node;
> >   });
> > }
> > 
> > // 加载子节点
> > const onLoadDictionaryChildren = async (expanded: boolean, record: DictionaryVO) => {
> >   if (expanded && record && record.id) {
> >     const data = await getDictionaryChildrenById(record.id);    // 通过id获取子节点
> >     setDictionaryData(origin => updateDictionaryData(origin, record.id, data.map(item => ({ ...item, children: item.hasChildren ? [] : undefined }))));
> >   }
> > }
> > 
> > <PageContainer>
> >   <ProTable<DictionaryVO>
> >     rowKey="id"
> >     onExpand={onLoadDictionaryChildren}
> >     request={async (params, sort) => {
> >       const res = await getDictionaryRootPage(getPageParams(params), getSortOrder(sort));   // 只获取根部节点
> >       const data = res.records ? res.records.map(item => ({ ...item, children: item.hasChildren ? [] : undefined })) : []
> >       setDictionaryData(data)
> >       return {
> >         total: res.total
> >       };
> >     }}
> >     dataSource={dictionaryData}
> >     columns={columns}
> >   />
> > </PageContainer>
> > ```
> 
> 你好请问有没有解决方案了啊

代码都写出来了，照抄就行
