### ISSUE TITLE
👑 [需求]服务端渲染出错

### ISSUE THREAD

**Issue by nolure** [ant-design/pro-components#2333]
### 🥰 需求描述

希望能在nextjs中使用，支持服务端渲染，目前引入模块直接报错
光是引入，不使用也会报错
import ProLayout, {getMenuData} from '@ant-design/pro-layout'

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/2524840/112779869-3ab0b080-907a-11eb-8e55-73efced0a04f.png)

**Comment by mouthguo** [comment]
可以参考一下 `nextjs` 的 [examples](https://github.com/vercel/next.js/blob/canary/examples)
里面有 `antd` 团队提交的接入 DEMO， 比如[这个](https://github.com/vercel/next.js/blob/canary/examples/with-ant-design-pro-layout-less/next.config.js)

**Comment by nolure** [comment]
@mouthguo antd我知道怎么引入，使用没有问题，就是@ant-design/pro-layout引入就报错

**Comment by chenshuai2144** [comment]
@ant-design/pro-layout 和 antd 的是一样的，同样的配置就可以了

` const antStyles = /antd\/.*?\/style.*?/` 把这个正则写的宽泛一点

**Comment by nolure** [comment]
嗯，配置我是按这个来写的，但是引入pro-layout就是报错：
webpack : (config, {isServer}) => {
    if (isServer) {
      const antStyles = /antd\/.*?\/style.*?/
      const origExternals = [...config.externals]
      config.externals = [
        (context, request, callback) => {
          if (request.match(antStyles)) return callback()
          if (typeof origExternals[0] === 'function') {
            origExternals[0](context, request, callback)
          } else {
            callback()
          }
        },
        ...(typeof origExternals[0] === 'function' ? [] : origExternals),
      ]

      config.module.rules.unshift({
        test: antStyles,
        use: 'null-loader',
      })
    }
    
    config.resolve.alias['@'] = path.join(__dirname, 'src')  
    
    config.module.rules.push(
      {
        test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
        use: [
          {
            loader: 'babel-loader',
          },
          {
            loader: '@svgr/webpack',
            options: {
              babel: false,
              icon: true,
            },
          },
        ],
      }
    )
    
  	return config
  }

我看你们官方例子也是客户端异步加载的，没有使用ssr:
https://github.com/vercel/next.js/blob/canary/examples/with-ant-design-pro-layout-less/layouts/main.tsx

const ProLayout = dynamic(() => import('@ant-design/pro-layout'), {
  ssr: false,
})
这样使用倒是没问题

**Comment by nolure** [comment]
不好意思，这个代码发出来始终有问题，还是上图精确点
![image](https://user-images.githubusercontent.com/2524840/112923746-68acf800-9141-11eb-8ff6-47d0e48486d8.png)

**Comment by ziyingjing** [comment]
+1,  const ProLayout = dynamic(() => import('@ant-design/pro-layout'), { ssr: false, })能正常引入，import ProLayout from '@ant-design/pro-layout';会报错

**Comment by 3lang3** [comment]
能否支持[动态主题](https://ant.design/docs/react/customize-theme-variable-cn)

**Comment by u3u** [comment]
服务端渲染报错是因为输出的 `cjs` 引用了 `esm` 可以试试终端 node 直接执行 `require('@ant-design/pro-layout')`

<img width="665" alt="image" src="https://user-images.githubusercontent.com/20062482/174037698-30067117-adba-4dbb-82c1-e46d8004a9ad.png">

编译后的 `lib/BasicLayout.js` 应该输出 `require('antd/lib/layout')` 而不是 `require('antd/es/layout')`

<img width="730" alt="image" src="https://user-images.githubusercontent.com/20062482/174037487-866851eb-8823-4ad3-bf3f-118a3a5e5a97.png">

应该还有其他模块引入也有问题 比如 `@ant-design/icons` 和 `rc-util` 等等
浏览器环境由 webpack 打包之后不会有问题 所以通过 `dynamic import ssr: false` 可以正常引入
如果想在服务端渲染需要用 [`next-transpile-modules`](https://www.npmjs.com/package/next-transpile-modules) 重新编译 并且还需要把 `cjs` 中意外引入的 `esm` 模块全部定义一遍

```js
// next.config.js
const withTM = require('next-transpile-modules')([
  '@ant-design/pro-card',
  '@ant-design/pro-components',
  '@ant-design/pro-descriptions',
  '@ant-design/pro-field',
  '@ant-design/pro-form',
  '@ant-design/pro-layout',
  '@ant-design/pro-list',
  '@ant-design/pro-provider',
  '@ant-design/pro-skeleton',
  '@ant-design/pro-table',
  '@ant-design/pro-utils',
  '@ant-design/icons',
  'antd',
  // ...
])

module.exports = withTM(nextConfig)
```

https://github.com/ant-design/pro-components/blob/cf511755b738beb5bcb42b5bcf8393d55b83f722/.fatherrc.ts#L29-L39

这里在 `lib` 模式下设置的 `libraryDirectory` 是 `es` 和这里有关吗？

**Comment by u3u** [comment]
是的，样式文件应该让用户手动引入，这样 `next` 端可以选择引入 `css` 文件，而不是去配置 `less`

**Comment by 3lang3** [comment]
最近没时间，不然可以弄下这方面的pr

**Comment by chenshuai2144** [comment]
ok了，我们已经转向了 css in js
