### ISSUE TITLE
🧐[问题]proTable查询后点击输入框清除按钮或者使用键盘清空后，无法再次输入。（ps:本地项目无问题，打包部署后才出现）

### ISSUE THREAD

**Issue by huangzongming** [ant-design/pro-components#2334]

**Comment by huangzongming** [comment]
![image](https://user-images.githubusercontent.com/37889515/112781892-57e77e00-907e-11eb-8f02-d300ff25fff3.png)

**Comment by DerrickTel** [comment]
> 本地项目无问题，打包部署后才出现
建议检查一下package.json，或者加package.json-lock和yarn.lock

**Comment by huangzongming** [comment]
![Uploading GIF 2021-3-29 11-08-27.gif…]()

**Comment by huangzongming** [comment]
@DerrickTel   package.json没有问题，package.json-lock也一直加有。使用Jenkins构建的，代码来自于gitLab上的。

**Comment by DerrickTel** [comment]
那你本地环境build有问题吗？

**Comment by huangzongming** [comment]
本地打包后居然没问题。。只有线上那个出现Bug

**Comment by huangzongming** [comment]
@DerrickTel 本地build没有问题，只是线上出问题

**Comment by chenshuai2144** [comment]
把锁包去掉？ 可能底层库更新了

**Comment by huangzongming** [comment]
@chenshuai2144  又重新搭个环境，一套有问题，一套没问题。。

**Comment by huangzongming** [comment]
@chenshuai2144 @DerrickTel  更新依赖后可以了~
