### ISSUE TITLE
🐛[BUG]  https://procomponents.ant.design/ 打不开了

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/pro-components#2338]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by wyg2103** [comment]
https://procomponents.gitee.io/

**Comment by dreamline2** [comment]
@wyg2103 感謝提供。我也遇上了這個問題，原頁面仍無法訪問

**Comment by DerekHQ** [comment]
gitee.io上的是老版本，等待中...

**Comment by wangcailin** [comment]
遇到了同样的问题，等待中...

**Comment by uliian** [comment]
已经几个小时了

**Comment by hengkx** [comment]
已经恢复
