### ISSUE TITLE
🐛[BUG] Layout 是用 section 元素导致 H1 比 H2 小

### ISSUE THREAD

**Issue by crazyair** [ant-design/pro-components#234]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/7971419/90503092-7947c980-e181-11ea-943a-ba7e1c1e67ab.png)

h1 本来是 2em 大小，但是被上面的覆盖了，而 section 是 layout 中的
![image](https://user-images.githubusercontent.com/7971419/90503181-97adc500-e181-11ea-95d0-8ed3e582605c.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by crazyair** [comment]
https://blog.csdn.net/q_giorgio/article/details/101174030

**Comment by chenshuai2144** [comment]
可以去 antd 中提一下，这个元素是 antd 做的

**Comment by crazyair** [comment]
@afc163
