### ISSUE TITLE
🧐[问题] Protable - How to set default column display

### ISSUE THREAD

**Issue by toquanghieu** [ant-design/pro-components#2340]
### 🧐 问题描述

I have data with 10 columns, but I just want display 5 columns on load, and user can click to setting button and choose hide or show more columns in 10 columns.
I tried to find some API from portable columns setting but nothing suitable.
- hideInSearch
- hideInTable
- hideInForm
Actually, I want when I load table, I will show some columns like below:
![image](https://user-images.githubusercontent.com/15702509/112806036-8bd39b00-90a0-11eb-99ff-f9da61bb2b3e.png)

**Comment by chenshuai2144** [comment]
you need  https://procomponents.ant.design/en-US/components/table#controlled-table-settings-columns this demo

**Comment by toquanghieu** [comment]
Thanksssssss
