### ISSUE TITLE
🐛[BUG] EditableProTable 增加onValuesChange属性后。新增行自动消失了。

### ISSUE THREAD

**Issue by CodeByZack** [ant-design/pro-components#2346]
### 🐛 bug 描述

EditableProTable 增加onValuesChange属性后。新增行自动消失了。

### 📷 复现步骤

1.新增一行
2.任意编辑新增行中一个值

结果新增行自动消失了。

### 🏞 期望结果

可正常编辑值。

### 💻 复现代码

https://codesandbox.io/s/polished-https-uitig?file=/src/App.tsx:107-123

### © 版本信息

- Pro-Table 版本: [2.32.0]
- umi 版本
- 浏览器环境
- 开发环境 [mac OS]

**Comment by CodeByZack** [comment]
![T}Q}`YD@NATK92`@XEQ69QW](https://user-images.githubusercontent.com/17472882/112855561-82b6ee00-90e1-11eb-8ebb-2c122e10a517.png)

简单看了下，上图中的cancelEditable，直接把newLineRecord置为undefined了。
接着的startEditable，只是设置了EditKey。newLineRecord已经不存在了。导致之后计算数据源时少了一条。

但我对代码不熟，不知道为啥这要先cancel再start。

**Comment by chenshuai2144** [comment]
onValuesChange 需要用受控的方式来处理值。


具体实现看这个 demo
http://localhost:8000/components/editable-table#%E5%AE%9E%E6%97%B6%E4%BF%9D%E5%AD%98%E7%9A%84%E7%BC%96%E8%BE%91%E8%A1%A8%E6%A0%BC
