### ISSUE TITLE
🐛[BUG]如何解决分页国际化

### ISSUE THREAD

**Issue by paddingC** [ant-design/pro-components#2352]
### 🐛 bug 描述

proTable版本2.12.0出现英文page，ConfigProvider也设置了
![image](https://user-images.githubusercontent.com/28521120/112949744-2220c300-916c-11eb-99ff-e9f12f11ad75.png)
![image](https://user-images.githubusercontent.com/28521120/112949835-3c5aa100-916c-11eb-81ec-46cb102fc5ee.png)

### 🏞 期望结果
2.12.0版本也能正常显示

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个一般是因为 打包了两份 antd 导致的。处理下你的打包工具吧

**Comment by paddingC** [comment]
> 这个一般是因为 打包了两份 antd 导致的。处理下你的打包工具吧
但是我们是多项目入口，怎么解啊

**Comment by paddingC** [comment]
> 这个一般是因为 打包了两份 antd 导致的。处理下你的打包工具吧

antd其他组件可以正常显示，pro的为什么没有作用呢？

**Comment by chenshuai2144** [comment]
pro的是直接import es 了，你可以升级到最新版本，或者强制设置 使用es版本的js
