### ISSUE TITLE
🐛[BUG] proLayout 在配置splitMenus为true的同时配置openKeys为false，会导致左侧menu渲染一级菜单。

### ISSUE THREAD

**Issue by AoaoMH** [ant-design/pro-components#2358]
### 🐛 bug 描述

proLayout  在配置splitMenus为true的同时配置openKeys为false，会导致左侧menu渲染一级菜单。

### 📷 复现步骤

umi创建antdpro后在defaultSetting或者BasicLayout的ProLayout组件属性配置
```
{
splitMenus: true,
openKeys: false
}
```

### 🏞 期望结果

splitMenus会将一级菜单转移到顶部，左侧不应该展示才对

### 💻 复现代码

umi创建antdpro后在defaultSetting或者BasicLayout的ProLayout组件属性配置
```
{
splitMenus: true,
openKeys: false
}
```

### © 版本信息

- ProComponents 版本:"@ant-design/pro-layout": "^6.9.0"
- umi 版本  "umi": "^3.4.1"
- 浏览器环境  chrome  87.0.4280.88
- 开发环境 win10

**Comment by chenshuai2144** [comment]
layout="mix"

**Comment by AoaoMH** [comment]
> layout="mix"

并不能解决这个问题，以上内容建立在layout:'mix'的基础上。

**Comment by mumu-baba** [comment]
此问题我也遇到了。也提了bug

**Comment by chenshuai2144** [comment]
@mumu-baba issue 链接一下

**Comment by mumu-baba** [comment]
https://github.com/ant-design/pro-components/issues/2471

**Comment by qingwenje2008** [comment]
这个bug关了吗，没看到咋解决这个问题啊，我也遇到了这样的问题，怎么解决呢

**Comment by chenshuai2144** [comment]
更新版本到最新
