### ISSUE TITLE
🧐[问题]formItemProps的校验提示怎么取消呢？只在校验不符合rule时才展示

### ISSUE THREAD

**Issue by 269117220** [ant-design/pro-components#2361]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/17564264/112984167-26130c00-9191-11eb-8d86-f9e7cb322855.png)
![image](https://user-images.githubusercontent.com/17564264/112984214-31fece00-9191-11eb-92b3-1c199c81bc80.png)
![image](https://user-images.githubusercontent.com/17564264/112984229-39be7280-9191-11eb-8226-01f325697c71.png)
为什么在输入时也显示提示呢，只想在validate时触发校验，必填的展示message，别的情况不展示，怎么设置呢？

**Comment by chenshuai2144** [comment]
只有一个规则的时候我们修改一下，展示为简单模式
