### ISSUE TITLE
🧐Style of settings modal

### ISSUE THREAD

**Issue by olgacherkasenko** [ant-design/pro-components#2362]
### 🧐 问题描述
A modal window with settings that opens on click SettingOutlined button has a different appearance than the modal window in the examples.

Setting modal looks like this in your demo in docs: 
<img width="224" alt="Снимок экрана 2021-03-30 в 17 39 24" src="https://user-images.githubusercontent.com/47739528/113007540-fb1fbc80-917e-11eb-9687-9adc15ae8235.png">
But if I open one of examples in code sandbox the modal looks like this:
<img width="196" alt="Снимок экрана 2021-03-30 в 17 43 30" src="https://user-images.githubusercontent.com/47739528/113008203-80a36c80-917f-11eb-85e8-77521575fbac.png">

How can I fix this? I need the modal looks like in your demo example.
### 💻 示例代码
https://codesandbox.io/s/j8w09

**Comment by chenshuai2144** [comment]
sandbox no import protable style
