### ISSUE TITLE
🐛[BUG] 【ProTable】 when the browser resize,  ellipsis does not change dynamically

### ISSUE THREAD

**Issue by cuichenchen** [ant-design/pro-components#2373]
### 🐛 bug 描述

       浏览器由大变小后，显示不下信息...，由小变大后，...不消失

### 📷 复现步骤

      改变浏览器大小

### 🏞 期望结果

        浏览器变化后，...根据内容大小自动消失

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
听起来好难。。 哈哈 先记下来

**Comment by chenshuai2144** [comment]
做起来太难了，而且意义不大，先关了
