### ISSUE TITLE
🐛[BUG]在嵌套结构的ProFormList中使用ProFormDependency无法获取数据

### ISSUE THREAD

**Issue by edgarsilk** [ant-design/pro-components#2374]
### 🐛 bug 描述

ProFormList的name使用嵌套层级后，使用ProFormDependency无法获取list中的数据

### 📷 复现步骤

https://codesandbox.io/s/dawn-cherry-ugdxv?file=/src/App.js

### 🏞 期望结果

在嵌套结构的ProFormList中使用ProFormDependency能正确获取数据

### © 版本信息

- ProComponents 版本: "@ant-design/pro-form": "^1.19.1"
- 浏览器环境 chrome 89.0.4389.90
- 开发环境 win10

**Comment by samdebug** [comment]
@chenshuai2144 问题解决了吗？我看proform@1.23.0还有这个问题

**Comment by chenshuai2144** [comment]
刚发了版本
