### ISSUE TITLE
👑 [需求] ProFormList的creatorRecord支持Function动态生成初始值

### ISSUE THREAD

**Issue by 6ok** [ant-design/pro-components#2378]
### 场景描述

业务场景：添加多个商品规格
实现思路：每个商品规格需要隐藏一个随机GUID列，尝试使用creatorRecord给新行赋随机GUID，发现creatorRecord不支持函数

###  需求描述
使ProFormList的creatorRecord支持传入Function，实现动态生成初始值

### 代码
![image](https://user-images.githubusercontent.com/56467036/113169424-2a662480-9278-11eb-93bd-c09feb912df3.png)

**Comment by chenshuai2144** [comment]
优秀的同学

**Comment by WuJiY** [comment]
怎么实现的 我这样写 还是不刷新

```
creatorRecord={{
            id: nanoid(),
            name: '',
            remark: '',
          }}
``

**Comment by scrapstation** [comment]
> 怎么实现的 我这样写 还是不刷新
> 
> 
> 
> ```
> 
> creatorRecord={{
> 
>             id: nanoid(),
> 
>             name: '',
> 
>             remark: '',
> 
>           }}
> 
> ``

你现在传进去的是对象，换成函数就行了()=>obj

**Comment by WuJiY** [comment]
+1 谢谢  ok 了

**Comment by WuJiY** [comment]
你sku 用的EditableProTable 吗 ？

**Comment by scrapstation** [comment]
> 你sku 用的EditableProTable 吗 ？

我之前提了一个PR到proform，在demo的最下方，你可以参考一下

**Comment by WuJiY** [comment]
规格生成是ok了 我现在是通过生成的规格 计算出sku列 然后是用的EditableProTable 显示，但是EditableProTable 里的验证规格影响了生成的数据

**Comment by scrapstation** [comment]
> 规格生成是ok了 我现在是通过生成的规格 计算出sku列 然后是用的EditableProTable 显示，但是EditableProTable 里的验证规格影响了生成的数据

我做过这个东西，我主页有个Taro的仓库，readme有我的联系方式

**Comment by WuJiY** [comment]
ok
