### ISSUE TITLE
🧐[问题]pro-table 2.5.14下拉框通过formItemProps设置的mode: 'multiple'多选不生效了，有人遇到吗

### ISSUE THREAD

**Issue by ray1347227** [ant-design/pro-components#238]
### 🧐 问题描述

pro-table 2.5.14下拉框通过formItemProps设置的mode: 'multiple'多选不生效了

### 💻 示例代码
{
        title: '分期',
        dataIndex: 'phaseId',
        render: (val, row) => row.phaseName,
        order: 5,
        valueEnum: formatValueEnum(phases, 'id', 'phaseName'),
        formItemProps: {
          showSearch: true,
          mode: 'multiple',
          maxTagCount: 1,
          maxTagTextLength: 6,
          filterOption: (input, option) => option.children.toLowerCase().indexOf(input.toLowerCase()) >= 0,
          allowClear: true,
          onChange: this.handlePhaseChange,
        },
 },

**Comment by chenshuai2144** [comment]
show your code

**Comment by ray1347227** [comment]
> show your code
![image](https://user-images.githubusercontent.com/21354564/90597323-6c7bb200-e223-11ea-96e6-dd853d7682ff.png)

**Comment by ray1347227** [comment]
2.4.4 =>
![image](https://user-images.githubusercontent.com/21354564/90597955-b31ddc00-e224-11ea-9dcf-44a6e74f2432.png)
2.5.14 =>
![image](https://user-images.githubusercontent.com/21354564/90598183-27587f80-e225-11ea-9ea5-724b95995996.png)

**Comment by chenshuai2144** [comment]
直接把代码贴出来，我方便做重现

**Comment by ray1347227** [comment]
> 直接把代码贴出来，我方便做重现

{
        title: '分期',
        dataIndex: 'phaseId',
        render: (val, row) => row.phaseName,
        order: 5,
        valueEnum: formatValueEnum(phases, 'id', 'phaseName'),
        formItemProps: {
          showSearch: true,
          mode: 'multiple',
          maxTagCount: 1,
          maxTagTextLength: 6,
          filterOption: (input, option) => option.children.toLowerCase().indexOf(input.toLowerCase()) >= 0,
          allowClear: true,
          onChange: this.handlePhaseChange,
        },
      },

**Comment by insistenceZHUO** [comment]
> 直接把代码贴出来，我方便做重现

这个问题解决了吗？ portable2.15.1也出现了这个问题
https://codesandbox.io/s/sad-lehmann-2wlii?file=/App.tsx:1384-1392

**Comment by chenshuai2144** [comment]
用 filedProps.mode
