### ISSUE TITLE
ProTable希望能增增加一个可以监听到列顺序变化的API👑 [需求]

### ISSUE THREAD

**Issue by Harvey-zhu** [ant-design/pro-components#2381]
### 🥰 需求描述

ProTable希望能增增加一个可以监听到列顺序变化的API
类似onColumnsOrderChange: (newColumns, oldColums) => {
}这样

**Comment by Harvey-zhu** [comment]
类似onColumnsOrderChange: (newColumns,oldColumns) => {
    //doSomething
}这样

**Comment by chenshuai2144** [comment]
这个是为了实现什么功能？

**Comment by Harvey-zhu** [comment]
> 这个是为了实现什么功能？
我们这边有个需求是记录用户对列的操作，下次进入表格的时候还原

**Comment by chenshuai2144** [comment]
columnsStateMap | columns 的状态枚举 | {key:{ show,fixed }}} | -
-- | -- | -- | --
onColumnsStateChange | columns 状态发生改变 | (props: {key:{ show,fixed }}}) => void | -


那就是这个了
