### ISSUE TITLE
ProTable 查询项中当valueType = 'date'时  取值取的时‘2021-03-25 17:24:31’

### ISSUE THREAD

**Issue by ZhengHuang-20** [ant-design/pro-components#2382]
ProTable 查询项中当valueType = 'date'时  取值取的时‘2021-03-25 17:24:31’  如果只想取日期 该如何配置

**Comment by voidzlfan** [comment]
按照文档 columns 设置`valueType = 'date'`，应该显示的就是 yyyy-mm-dd 的格式

我自己试了下，没问题吧

mock 数据
![image](https://user-images.githubusercontent.com/38897523/113398067-98bdfa80-93d0-11eb-98a0-31a0af233e96.png)

显示：
![image](https://user-images.githubusercontent.com/38897523/113398146-b3906f00-93d0-11eb-9f8b-b493182929ff.png)

你问题描述太模糊了，环境，代码都没贴，找不到问题呀

**Comment by minuux** [comment]
https://codesandbox.io/s/proform-he-editabletable-tongshishiyong-forked-08ppp?file=/App.tsx

官网上的例子，修改了一个字段类型为date,直接点击提交按钮，数据正常，新增一行数据后，得到的date字段内容包含时间

**Comment by qq919623547** [comment]
pro-table@2.33.0 后 在column 里设置搜索时间时，valuetype 使用 date 但是通过request获取的值却是 2021-04-08 ：09：06：55 按理说应该是2021-04-08 同样当 valuetype 设置为time 时，也会把全部的时间都给返回来。

**Comment by iambool** [comment]
同问，持续关注
