### ISSUE TITLE
🐛[BUG] prolayout autoclose 文档写的默认值是 true，实际填任何值都未生效

### ISSUE THREAD

**Issue by liyupi** [ant-design/pro-components#2388]
### 🐛 bug 描述

文档地址：https://procomponents.ant.design/components/layout#menu

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
autoclose 你的理解是什么？

我这里是做了一下 merge，打开了之后 layout 就不会打开菜单的时候关闭其他所有的菜单

**Comment by liyupi** [comment]
抱歉我理解错了，请问有考虑支持移动端点击后自动折叠菜单么

**Comment by chenshuai2144** [comment]
这个不会的，你可以试试 menuItemRender

**Comment by jakecastelli** [comment]
Hi there 👋 

In docs its written `autoClose` its default to `true` but in code it looks different:
![Screen Shot 2021-06-28 at 12 14 19 am](https://user-images.githubusercontent.com/38635403/123548873-ca631980-d7a5-11eb-8be1-23b1b6b797c8.png)

From my understanding `autoClose` was supposed to close the side menu on the mobile screen when the user selects an item.

Cheers

**Comment by wuhao930406** [comment]
> 抱歉我理解错了，请问有考虑支持移动端点击后自动折叠菜单么
可以在 app.ts 
`export async function getInitialState() {
  return {
    name: '@umijs/max',
    collapsed: false,
  };
}

export const layout = ({ initialState, setInitialState }) => {
  return {
    logo: Settings?.logo,
    collapsed: initialState?.collapsed,
    onCollapse: (collapsed) => {
      setInitialState((s) => ({
        ...s,
        collapsed,
      }));
    },
    onPageChange:()=>{
      setInitialState((s) => ({
        ...s,
        collapsed:true,
      }));
    },
    menu: {
      locale: false,
    },
  };
};
`
onPageChange时强制收起菜单
