### ISSUE TITLE
🐛[BUG] ProTable，双击刷新按钮报错

### ISSUE THREAD

**Issue by Lukiya** [ant-design/pro-components#2391]
### 🐛 bug 描述

ProTable，双击刷新按钮报错

### 📷 复现步骤

访问  https://procomponents.ant.design/components/table
找到任意刷新按钮，双击后报错。

### 🏞 期望结果

期望双击不报错。

### 💻 复现代码

访问  https://procomponents.ant.design/components/table
找到任意刷新按钮，双击后报错。

### © 版本信息

- ProComponents 版本: 1.18.2
- umi 版本  3.4.1
- 浏览器环境 Edge
- 开发环境  Win10

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/2961561/113446670-1f60e080-93ad-11eb-9249-2c4d4e1198fd.png)

**Comment by chenshuai2144** [comment]
你做了什么，为什么会导致 jquery 报错？

**Comment by Lukiya** [comment]
我是在https://procomponents.ant.design/components/table这个你们的网站测试出来的问题，不是我自己的开发环境。你试下呢

**Comment by chenshuai2144** [comment]
那就是你的插件了，我们怎么会用 jquery 写代码
