### ISSUE TITLE
👑 [需求] ConfigProvider 全局配置组件

### ISSUE THREAD

**Issue by jiyingzhi** [ant-design/pro-components#2393]
### 🥰 需求描述

能不能像 ConfigProvider 一样提供一个全局配置组件的地方，比如 ProTable 的 pageSize、返回数据的格式规范等，有些属性每个地方都要传递会比较繁琐。

### 🧐 解决方案

暂时没有想到。

**Comment by chenshuai2144** [comment]
做个 rfc 吧，祥细一点，现在的 provide 只支持传入 valueType
