### ISSUE TITLE
👑 [需求] 关于 SWR

### ISSUE THREAD

**Issue by jiyingzhi** [ant-design/pro-components#2395]
### 🥰 需求描述

1. ProComponents 里 Select 组件使用了 SWR，SWR 提供了很多有用的功能，比如错误重试、请求去重等。现在只有 Select 使用了 SWR，我觉得其他支持 request 的组件都需要统一使用 SWR 提供更好的请求体验。比如在一个 CRUD 页面中，ProTable、ProForm 等地方都会用到 radio、checkbox 的 request，可能会有重复请求。之前使用 valueType: 'select' 的时候就遇到了这个问题，本来想自己处理的，后来发现 SWR 提供了这个功能。所以其他涉及到 request 的组件也可以使用 SWR。另外，ProTable 提供了请求节流、轮询等功能，这些功能 SWR 直接就支持，而且还有更多功能：错误重试、页面聚焦重新请求、断网重联时重新请求、缓存等功能。

2. 看到很多人会提问，比如为什么请求失败后一直重试、怎么关掉等等，对于这个，可以在文档中说明这是 SWR 的功能，怎么配置，SWR 也提供了全局配置的方式：
```js
function App () {
  return (
    <SWRConfig 
      value={{
        refreshInterval: 3000,
        fetcher: (resource, init) => fetch(resource, init).then(res => res.json())
      }}
    >
      <Dashboard />
    </SWRConfig>
  )
}
```

**Comment by chenshuai2144** [comment]
我也打算都替换一下，但是有些代码老了一些，迁移起来有点慢
