### ISSUE TITLE
👑 [需求]ProTable 根据colmuns生成的查询条件能自定义顺序吗?

### ISSUE THREAD

**Issue by l745230** [ant-design/pro-components#240]
### 🚑 其他信息

现在是按colmuns的顺序来生成的.

比如日期字段一般放在表格右边显示. 但是查询条件的时候,希望第一个查询框就是查询时间.

**Comment by ray1347227** [comment]
用order属性就可以吧

**Comment by l745230** [comment]
> 用order属性就可以吧

真可以.. 原来文档上已经有了,我再去读几遍...
