### ISSUE TITLE
🧐[问题] 有没有办法定义ProForm submitButton里的文本?

### ISSUE THREAD

**Issue by nxboo** [ant-design/pro-components#2401]
### 🧐 问题描述

我想使用ProForm中的提交功能，但要定义submitButton里的文本， 有没有办法实现？
1. 我不想用submitter.render,因为这样我要自己管理按扭的loading

### 💻 示例代码

<ProForm
        form={form}
        name="control-ref"
        onFinish={handlePay}
        submitter={{
          submitButtonProps: {
            icon: <AlipayOutlined/>,
            size: 'large',
            value: '前往支付宝',
            children: '前往支付宝',
          },
          resetButtonProps: false,

**Comment by jiyingzhi** [comment]
![image](https://user-images.githubusercontent.com/21698836/113657461-93162c80-96d0-11eb-911f-3a8983d1ea9f.png)

**Comment by nxboo** [comment]
可以，谢谢
