### ISSUE TITLE
🧐[问题] @ant-design/pro-form 包里没有 BetaSchemaForm 模块呢？

### ISSUE THREAD

**Issue by 0xe69e97** [ant-design/pro-components#2403]
### 🧐 问题描述

使用的[官网的案例](https://procomponents.ant.design/components/schema-form)，但是当我引入到项目当中的时候，出现报错：`Attempted import error: 'BetaSchemaForm' is not exported from '@ant-design/pro-form'.`

看了一下源码文件当中也没发现 `BetaSchemaForm` 模块（大概看的）

麻烦请问一下是我使用方式不对吗？

### 💻 示例代码

``` js
import { BetaSchemaForm } from '@ant-design/pro-form'

// render code
<BetaSchemaForm
    trigger={<a>点击我</a>}
    layoutType='ProForm'
    onFinish={async values => {
      console.log(values)
    }}
    columns={columns}
/>
```

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30501422/113671017-64a44b80-96e8-11eb-9c99-2aef80709a47.png)

**Comment by chenshuai2144** [comment]
还没发，坐等吧

**Comment by 0xe69e97** [comment]
> 还没发，坐等吧

好的 谢谢了，辛苦。自己先写了简易版本
