### ISSUE TITLE
🧐[问题]为什么安装pro-table 使用会报错

### ISSUE THREAD

**Issue by liyuling486** [ant-design/pro-components#2404]
### 🧐 问题描述

使用会报错

![image](https://user-images.githubusercontent.com/42409013/113682207-7b9d6a80-96f5-11eb-8078-a99e733f5591.png)
### 💻 示例代码
这样使用
import ProTable from '@ant-design/pro-table'

**Comment by luy19** [comment]
你可能没有安装[antd](https://www.npmjs.com/package/antd)，或者[antd](https://www.npmjs.com/package/antd)的版本过低
