### ISSUE TITLE
🧐[问题]ProFormSelect showSearch时 requst方法如何做到防抖？

### ISSUE THREAD

**Issue by konayukis** [ant-design/pro-components#2406]
### 🧐 问题描述

1.  requst 如何做到防抖？
2. requst 返回新数组后option不更新

### 💻 示例代码

```js
<ProFormSelect
      label="xxx"
      showSearch
      request={lodash.debounce(async ({keyWords}) => {
        if(!keyWords) return []
        const res = await queryStaff({ keyword: keyWords });
        if (res.status === 200) {
          console.log(res.data.map(({ name, id }) => ({ label: name, value: id})))
          return res.data.map(({ name, id }) => ({ label: name, value: id}));
        }
        return [];
      })}
 />
```

**Comment by jiyingzhi** [comment]
防抖就用你这个方法是可以的

**Comment by mouthguo** [comment]
示例代码没有设置 wait 哦，参考下[文档](https://lodash.com/docs/4.17.15#debounce)默认值为 0 的。

> request 返回新数组后 option 不更新

这个看了下，失去焦点再出现的时候，有了，好像是 bug

**Comment by chenshuai2144** [comment]
不会实时刷新是吗？

**Comment by mouthguo** [comment]
嗯，请求结果没有实时出现在下拉框里面。

**Comment by oxygen-xx** [comment]
@chenshuai2144  这个问题，我也发现了，总之是通过查询更新options，下拉框没有更新，需要失去焦点，再得到焦点的时候，数据才会刷新出来。

**Comment by chenshuai2144** [comment]
这个也是没有复现，我搞了个demo，发现效果还是可以的，来个重现吧

**Comment by lucoxlee** [comment]
同求

**Comment by MonsterTan** [comment]
> @chenshuai2144 这个问题，我也发现了，总之是通过查询更新options，下拉框没有更新，需要失去焦点，再得到焦点的时候，数据才会刷新出来。

@chenshuai2144 发现+1。 也是通过request去请求获取数据，第一次能获取ok。但是当输入后，可以发现给后端请求并成功返回，但是select框并没有筛选后的数据.

**Comment by jzsn2018** [comment]
> > @chenshuai2144 这个问题，我也发现了，总之是通过查询更新options，下拉框没有更新，需要失去焦点，再得到焦点的时候，数据才会刷新出来。
> 
> @chenshuai2144 发现+1。 也是通过request去请求获取数据，第一次能获取ok。但是当输入后，可以发现给后端请求并成功返回，但是select框并没有筛选后的数据.

同样的问题+1,请问你解决了吗?

**Comment by qiangxinglin** [comment]
+1

**Comment by weiqishang** [comment]
同问，已经升级到最新版本，还是没解决

**Comment by DenseW** [comment]
options没有更新的原因是因为用了lodash.debounce方法，return有问题，直接配置debounceTime={毫秒}就可以实现options更了，且能防抖
![image](https://github.com/ant-design/pro-components/assets/46704005/8dcd8a6e-57c6-42f1-8548-ce26ddef535c)
