### ISSUE TITLE
Profiled 如何收集数据做提交

### ISSUE THREAD

**Issue by ZhengHuang-20** [ant-design/pro-components#2408]
Profiled 如何收集数据做提交

**Comment by ZhengHuang-20** [comment]
valueType为text时 onChange事件获取不到改变后的值

**Comment by ZhengHuang-20** [comment]
还有 valueType 为checkbox 时，点击复选不能选中

**Comment by luy19** [comment]
该组件为内部组件，请勿直接使用。
[ProField](https://procomponents.ant.design/components/field)

**Comment by chenshuai2144** [comment]
@ZhengHuang-20  用 ProFormFiled
