### ISSUE TITLE
🧐[问题] Pagination  for EditableTable

### ISSUE THREAD

**Issue by lukenvn** [ant-design/pro-components#2409]
Hi Guys, 

is there any way that I can config/setup the pagination when using the EditableTable of ProTable?

**Comment by luy19** [comment]
I think this is an unusual requirement.

**Comment by mouthguo** [comment]
we can see the declaration, its implements [TableProps](https://github.com/ant-design/pro-components/blob/8bee408cb83b5070150296f64c896003afd85adb/packages/table/src/typing.ts#L306)

and we can find editableTable just omit [`onChange`](https://github.com/ant-design/pro-components/blob/master/packages/table/src/components/EditableTable/index.tsx#L23-L25)

**Comment by mouthguo** [comment]
[this util](https://github.com/ant-design/pro-components/blob/8bee408cb83b5070150296f64c896003afd85adb/packages/table/src/utils/index.ts#L22-L55) may help u
