### ISSUE TITLE
🧐[问题] 使用 PageContainer 时会有默认的水印

### ISSUE THREAD

**Issue by mrchenxxx** [ant-design/pro-components#2414]
### 🧐 问题描述

![水印1](https://user-images.githubusercontent.com/44868578/113801944-6cb5c700-978c-11eb-9721-2cb0c6d3da9b.png)
![水印2](https://user-images.githubusercontent.com/44868578/113801949-6de6f400-978c-11eb-8a8c-0cf98a471557.png)

**Comment by mrchenxxx** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [#1811][🧐[问题] 使用 page-container 的时候，宽度设置的问题][70%]

不行啊  我这个是有水印

**Comment by mouthguo** [comment]
你检查下看看，是不是哪里没有注意做了设置呢？`waterMakProps`的声明，说是可选的，不设置就是 `undefined`。代码里面有做[判定处理](https://github.com/ant-design/pro-components/blob/d5c0f149b5acd1233a711b1659f243238d012d67/packages/layout/src/components/PageContainer/index.tsx#L242-L245)的，没有设置不会包水印的
