### ISSUE TITLE
🧐菜单icon无法居中

### ISSUE THREAD

**Issue by Xiaochena** [ant-design/pro-components#2416]
### 🧐 问题 描述
🧐二级菜单中有一个padding-left: 24px;在打开后收起的情况下无法消失，只有当鼠标移上去时才会消失，造成图标icon不居中

**Comment by chenshuai2144** [comment]
更新下依赖

听起来像是依赖之间不匹配造成 css 样式混乱了

**Comment by Xiaochena** [comment]
官方文档中有一个demo有同样的问题

**Comment by Xiaochena** [comment]
> 更新下依赖
> 
> 听起来像是依赖之间不匹配造成css样式混乱了



> 更新下依赖
> 
> 听起来像是依赖之间不匹配造成 css 样式混乱了

官方文档中有一个demo有同样的问题

**Comment by Xiaochena** [comment]
官方文档中有一个地方有同样的问题

**Comment by chenshuai2144** [comment]
豆酱老师要重写 menu 了，到时候再看吧
