### ISSUE TITLE
ProTabel设置layout: 'horizontal'有bug

### ISSUE THREAD

**Issue by jan18320685018** [ant-design/pro-components#2418]
### 🐛 bug 描述
ProTable里设置search={{layout: 'horizontal', span:  [4}}，然后打开谷歌的调试器的时候，出现布局错乱的情况，宽度还是每个相等。设置layout: 'vertical'竖着的时候就很正常了。

**Comment by jan18320685018** [comment]
会出现前面几个的label和wrapper还是水平的，但wrapper的宽度是小了很多，后面几个就变垂直了，wrapper的宽度100%

**Comment by jan18320685018** [comment]
![image](https://user-images.githubusercontent.com/68332121/113830926-a8b35100-97b9-11eb-8eed-33e93e65adfb.png)

**Comment by chenshuai2144** [comment]
这个是因为 select 的最小宽度导致的吧，


你这里是 antd@3 吗？

**Comment by jan18320685018** [comment]
***@***.***,antd的Select也没有默认min-width吧,我刚看了一遍,没有发现



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月8日(星期四) 上午9:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/pro-components] ProTabel设置layout: &#39;horizontal&#39;有bug (#2418)





 
这个是因为 select 的最小宽度导致的吧，
 
你这里是 ***@***.*** 吗？

**Comment by jan18320685018** [comment]
@chenshuai2144 我这是4.0

**Comment by chenshuai2144** [comment]
你debug 一下，可能是样式污染什么的
