### ISSUE TITLE
🐛[BUG]proForm使用labelAlign没有任何效果

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/pro-components#2420]
### 🐛 bug 描述

我使用proForm的时候，设置layout=‘inline’起了作用，但是文档显示不支持layout，我设置labelAlign却不起作用
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
layout 支持的，他就是一个 form。labelAlign 是 FormItem 的。
https://github.com/ant-design/ant-design/issues/16067
