### ISSUE TITLE
🐛[BUG]JSON   SchemaForm生成表单 官网demo报错

### ISSUE THREAD

**Issue by xiangtianli** [ant-design/pro-components#2421]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/49628940/113822169-ae0b9e00-97af-11eb-8644-a41a9707bc34.png)

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/49628940/113822241-c5e32200-97af-11eb-8553-b660ac37c7f6.png)

### © 版本信息

- "@ant-design/pro-form": "^1.3.0",
- "antd": "^4.12.0",
- "umi": "^3.4.1",
- 开发环境  mac OS

**Comment by jiyingzhi** [comment]
SchemaForm 还没有正式发布
