### ISSUE TITLE
🐛[BUG]ProTable设置ellipsis后，缩放浏览器失效

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/pro-components#2422]
### 🐛 bug 描述

在columns中设置ellipsis后，浏览器100%显示没问题，但是ctrl+滚轮缩放的时候回失效
### 📷 复现步骤

{
      title: '模型名称',
      dataIndex: 'name',
      ellipsis: true,
      fixed: 'left',
      width: 180,
    },
    {
      title: '模型描述',
      dataIndex: 'description',
      ellipsis: true,
      width: 180,
    },
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by mouthguo** [comment]
#2373

**Comment by chenshuai2144** [comment]
实现原理导致的，不能支持浏览器缩放
