### ISSUE TITLE
👑 [需求] renderFormItem 中怎么拿到所有的表格数据呢？

### ISSUE THREAD

**Issue by mtrucc** [ant-design/pro-components#2426]
### 🧐 问题描述

我期望在 `renderFormItem` 中能拿到整个表格的数据 `dataSource`，我的写法似乎有问题，`dataSource`为空数组。

### 💻 示例代码

期望在输入框事件监听中能拿到表格数据并更新表格

```
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInputValue(e.target.value);
    // 我期望在这能拿到表格数据并进行修改表格
    console.log(dataSource)
  };
```

完整代码
```
const TagList: React.FC<{
  value?: {
    key: string;
    label: string;
  }[];
  onChange?: (
    value: {
      key: string;
      label: string;
    }[],
  ) => void;
}> = ({ value, onChange, dataSource}) => {
  const ref = useRef<Input | null>(null);
  const [newTags, setNewTags] = useState<
    {
      key: string;
      label: string;
    }[]
  >([]);
  const [inputValue, setInputValue] = useState<string>('');

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInputValue(e.target.value);
    // 我期望在这能拿到表格数据并进行修改表格
    console.log(dataSource)
  };

  const handleInputConfirm = () => {
    let tempsTags = [...(value || [])];
    if (inputValue && tempsTags.filter((tag) => tag.label === inputValue).length === 0) {
      tempsTags = [...tempsTags, { key: `new-${tempsTags.length}`, label: inputValue }];
    }
    onChange?.(tempsTags);
    setNewTags([]);
    setInputValue('');
  };

  return (
    <Space>
      {(value || []).concat(newTags).map((item) => (
        <Tag key={item.key}>{item.label}</Tag>
      ))}
      <Input
        ref={ref}
        type="text"
        size="small"
        style={{ width: 78 }}
        value={inputValue}
        onChange={handleInputChange}
        onBlur={handleInputConfirm}
        onPressEnter={handleInputConfirm}
      />
    </Space>
  );
};



const [editableKeys, setEditableRowKeys] = useState<React.Key[]>([]);
const [dataSource, setDataSource] = useState<DataSourceType[]>([]);

const columns: ProColumns<DataSourceType>[] = [
  {
    title: '活动名称',
    dataIndex: 'title',
    formItemProps: {
      rules: [
        {
          required: true,
          message: '此项为必填项',
        },
      ],
    },
  },
  {
    title: '标签',
    dataIndex: 'labels',
    width: '40%',
    renderFormItem: () => <TagList dataSource={dataSource}/>,
    render: (_, row) => row?.labels?.map((item) => <Tag key={item.key}>{item.label}</Tag>),
  },
  {
    title: '操作',
    valueType: 'option',
    render: (text, record, _, action) => [
      <a
        key="editable"
        onClick={() => {
          action.startEditable?.(record.id);
        }}
      >
        编辑
      </a>,
    ],
  },
];

<EditableProTable<DataSourceType>
  rowKey="id"
  headerTitle="可编辑表格"
  columns={columns}
  value={dataSource}
  onChange={setDataSource}
  recordCreatorProps={{
    position: 'end',
    record: { id: (Math.random() * 1000000).toFixed(0) },
  }}
  editable={{
    editableKeys,
    onChange: setEditableRowKeys,
  }}
/>;
```

**Comment by luy19** [comment]
或许你可以考虑用`onValuesChange`， [示例代码](https://procomponents.ant.design/components/editable-table#%E5%AE%9E%E6%97%B6%E4%BF%9D%E5%AD%98%E7%9A%84%E7%BC%96%E8%BE%91%E8%A1%A8%E6%A0%BC)

**Comment by mtrucc** [comment]
> 或许你可以考虑用`onValuesChange`， [示例代码](https://procomponents.ant.design/components/editable-table#%E5%AE%9E%E6%97%B6%E4%BF%9D%E5%AD%98%E7%9A%84%E7%BC%96%E8%BE%91%E8%A1%A8%E6%A0%BC)

非常感谢你的回复，我的数据是树状的，然后我做了一个下拉框，选择其中的一个值的时候，需要在下方插入一个数据，也就是在children：[]中插入数据，然后我是通过id找到这个children的，让人哭笑不得的是，renderFormItem方法中没法获取这一行的id，只有表单对应的key，翻了一下，参数中有recordKey。
目前我是无法拿到所有的表格数据进行数据上的联动。
![image](https://user-images.githubusercontent.com/16724665/114039656-83a40880-98b5-11eb-9d93-1318b7ff58e2.png)

**Comment by chenshuai2144** [comment]
用 dataSource 和 onDataSourceChange 来实现吧。

**Comment by mtrucc** [comment]
https://github.com/ant-design/pro-components/issues/2201
我也有他这种问题，并且拿不到所有的表格数据

**Comment by mtrucc** [comment]
> 用 dataSource 和 onDataSourceChange 来实现吧。

嗯。目前是这么一个思路，也是这么写的，只是拿不到对应行的所有属性，后来我干脆给所有数据中加入了rowKey：recordKey 这样的属性，然后进行判断。
这是笨办法，只能做参考，不要学我，，，

**Comment by mtrucc** [comment]
> 用 dataSource 和 onDataSourceChange 来实现吧。

还有个问题就是，不仅拿不到，数据好像还是被冻结的，比如我调用了`setState`方法更新了表格，在`renderFormItem`里面打印表格数据`dataSource`是个空数组😭

**Comment by chenshuai2144** [comment]
用 ref

**Comment by mtrucc** [comment]
> 用 ref

高人啊，我咋就没想到，明天试试

**Comment by chenshuai2144** [comment]
ref 在 hooks 中相当于 this.xx

**Comment by chenshuai2144** [comment]
```
const ref = useRef();

<EditableProTable<DataSourceType>
  ref={ref}
  headerTitle="可编辑表格"
  columns={columns}
  rowKey="id"
  value={dataSource}
  onChange={(data) => {
    setDataSource(data);
    ref.current = data;
  }}
  // recordCreatorProps={false}
  recordCreatorProps={{
    newRecordType: "dataSource",
    record: () => ({
      id: Date.now(),
    }),
  }}
  toolBarRender={() => {
    return [
      <Button type="primary" key="save" onClick={() => {}}>
        保存数据
      </Button>,
    ];
  }}
  editable={false}
/>;


```

**Comment by chenshuai2144** [comment]
你看一下，onchange 里面用 ref，这样就可以保证 ref 里面的每次都是新的

**Comment by Hideer** [comment]
@mtrucc 哈喽，我和你的需求一样，也同样遇到了这个问题，简述下需求（在变更一个支持树状的可编辑表格场景下，当变更某列下的某行属性，需要获取当前行唯一标识）

columns：
<img width="524" alt="image" src="https://github.com/ant-design/pro-components/assets/31301552/66bc526d-635b-4599-84c6-73a062586191">

field 方法：
<img width="846" alt="image" src="https://github.com/ant-design/pro-components/assets/31301552/1a8b9254-c9a6-40e6-a869-8ab7847941c9">

通过图中这些方法都获取不了非form关联的数据


环境：
"@ant-design/pro-components": "2.6.8",
"antd": "5.4.7",

**Comment by mtrucc** [comment]
> @mtrucc 哈喽，我和你的需求一样，也同样遇到了这个问题，简述下需求（在变更一个支持树状的可编辑表格场景下，当变更某列下的某行属性，需要获取当前行唯一标识）
> 
> columns： <img alt="image" width="524" src="https://user-images.githubusercontent.com/31301552/277545764-66bc526d-635b-4599-84c6-73a062586191.png">
> 
> field 方法： <img alt="image" width="846" src="https://user-images.githubusercontent.com/31301552/277545911-1a8b9254-c9a6-40e6-a869-8ab7847941c9.png">
> 
> 通过图中这些方法都获取不了非form关联的数据
> 
> 环境： "@ant-design/pro-components": "2.6.8", "antd": "5.4.7",

你好，我是自己给每个obj下生成了一个key作为标识的，然后手动搜索树去修改其中的值
