### ISSUE TITLE
🐛[BUG]Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by swustzzh** [ant-design/pro-components#2428]
### 🐛 bug 描述

Warning: Each child in a list should have a unique "key" prop.
Check the render method of `Cell`. See https://reactjs.org/link/warning-keys for more information.

设置了rowKey="id"，但是一直提示这个bug，

### 📷 复现步骤

<ProTable<SourceListItem>
  headerTitle="查询表格"
  actionRef={actionRef}
  rowKey="id"
  search={{ labelWidth: 120 }}
  toolBarRender={false}
  request={({ pageSize, ...params }, sorter) =>
    queryList({ size: pageSize, ...params, ...sorter })
  }
  columns={columns}
  scroll={{ x: 1500 }}
  pagination={{ showTotal: (total) => `共 ${total} 条` }}

其中：id是不重复的

### 🏞 期望结果

无警告

### © 版本信息

- ProComponents 版本: 
    "@ant-design/pro-table": "^2.33.0", 2.17.0也有这个问题
- umi 版本：3.2.14
- 浏览器环境：Chrome89
- 开发环境: mac OS

**Comment by jiyingzhi** [comment]
这个 Cell 应该不是 Table 本身的，检查一下操作列的 render 或者 toolBarRender 之类的有没有加 key

**Comment by swustzzh** [comment]
确实是因为columns里面的option用了数组，Popconfirm组件没有指定key，加上key或者用Fragment包裹就没问题了，谢谢！ @jiyingzhi

**Comment by ZmSama** [comment]
@swustzzh 太棒了，果然是option里面用了数组导致的。找了半天，最后用Space组件包裹一下就好了

**Comment by h93910** [comment]
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `LabelIconTip`.
我的问题是在headerTitle 里用了Space包裹Button ，在Space上加key就不报错了

**Comment by swustzzh** [comment]
您的邮件已收到。----------------------张智慧----------------------
