### ISSUE TITLE
Table search不支持表单验证

### ISSUE THREAD

**Issue by LiHwsqh** [ant-design/pro-components#243]
https://github.com/ant-design/pro-components/blob/e9b44dea61cb5d6e95d4525c7557ecd4e42894c7/packages/table/src/Form/index.tsx#L192
看代码里如果不是form类型直接就跳过字段认证了，但是如果表格查询需要限制用户输入应该怎么办呢，感觉可以放开这个限制

**Comment by yangzhenwang** [comment]
如果需求是查询的时候需要必须项 怎么解决呢
