### ISSUE TITLE
👑 [需求] 希望ProFormFields加入Input.Group支持

### ISSUE THREAD

**Issue by shanzhaozhen** [ant-design/pro-components#2434]
### 🥰 需求描述

希望ProFormFields加入Input.Group支持，有些地方希望可以跟其他组件组合一起使用

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/29800728/114118350-43777100-991b-11eb-8612-5f62cec9a771.png)

**Comment by IversonTian** [comment]
+1
