### ISSUE TITLE
🧐[需求] 目前的tableAlertRender无法控制其显示或隐藏

### ISSUE THREAD

**Issue by LiangGu** [ant-design/pro-components#2439]
### 🧐 问题描述
当页面涉及到主子表格嵌套，且两个表格都需要批量选择的功能，希望能自定义`tableAlertRender`的显示内容，以及**控制其显示或隐藏的状态，以满足实际业务需求**。但目前的`tableAlertRender`好像无法控制其显示或隐藏，只能勾选了对应table组件的行之后，才会出现。

### 💻 示例代码
```
const parentRowSelection = {
        selectedRowKeys: parentSelectedRowKeys,
        onSelect: (record: any, selected: any, selectedRows: any) => {
            onParentSelectChange(
                record, 
                selected, 
                selectedRows, 
                parentSelectedRowKeys, 
                childSelectedRows,
                childSelectedRowKeys, 
                setParentSelectedRowKeys, 
                setChildSelectedRows,
                setChildSelectedRowKeys,
            )
        },
        onSelectAll: (selected: any, selectedRows: any, changeRows: any) => {
            onParentSelectAll(
                selected, 
                selectedRows, 
                changeRows, 
                parentSelectedRowKeys, 
                setParentSelectedRowKeys, 
                setChildSelectedRows,
                setChildSelectedRowKeys,
            )
        },
    }

    const childRowSelection = {
        selectedRowKeys: childSelectedRowKeys,
        hideSelectAll: true,
        onSelect: (record: any, selected: any, selectedRows: any) => {
            onChildSelectChange(
                record, 
                selected, 
                selectedRows, 
                dataSource,
                parentSelectedRowKeys, 
                childSelectedRows,
                childSelectedRowKeys, 
                setParentSelectedRowKeys, 
                setChildSelectedRows,
                setChildSelectedRowKeys,
            )
        },
    }

    const expandedRowRender = (record: any, index: any, indent: any, expanded: any) => {
        const ExpandedData = record.ChildList || [];
        return (
            <ProTable
                rowKey='ID'
                columns={subColumns}
                headerTitle={false}
                search={false}
                options={false}
                dataSource={ExpandedData}
                rowSelection={childRowSelection}
                tableAlertRender={false}
                tableAlertOptionRender={false}
                pagination={false}
                scroll={{ x: 100 }}
            />
        );
    };

    return (
        <PageContainer>
            <ProTable<TableItem>
                rowKey='ID'
                rowSelection={parentRowSelection}
                tableAlertRender={({ selectedRowKeys, selectedRows, onCleanSelected }) => {
                   // How to control here for show or hide ?
                }}
                expandable={{ expandedRowRender }}
                columns={columns}
            />
        </PageContainer>
```

### 🚑 其他信息

**Comment by LiangGu** [comment]
@craxyz

**Comment by LiangGu** [comment]
@chenshuai2144

**Comment by LiangGu** [comment]
> ### 🧐 问题描述
> 当页面涉及到主子表格嵌套，且两个表格都需要批量选择的功能，**希望能自定义`tableAlertRender`的显示内容，以及控制其显示或隐藏的状态，以满足实际业务需求**。但目前的`tableAlertRender`好像无法控制其显示或隐藏，只能勾选了对应table组件的行之后，才会出现。
> 
> ### 💻 示例代码
> ```
> const parentRowSelection = {
>         selectedRowKeys: parentSelectedRowKeys,
>         onSelect: (record: any, selected: any, selectedRows: any) => {
>             onParentSelectChange(
>                 record, 
>                 selected, 
>                 selectedRows, 
>                 parentSelectedRowKeys, 
>                 childSelectedRows,
>                 childSelectedRowKeys, 
>                 setParentSelectedRowKeys, 
>                 setChildSelectedRows,
>                 setChildSelectedRowKeys,
>             )
>         },
>         onSelectAll: (selected: any, selectedRows: any, changeRows: any) => {
>             onParentSelectAll(
>                 selected, 
>                 selectedRows, 
>                 changeRows, 
>                 parentSelectedRowKeys, 
>                 setParentSelectedRowKeys, 
>                 setChildSelectedRows,
>                 setChildSelectedRowKeys,
>             )
>         },
>     }
> 
>     const childRowSelection = {
>         selectedRowKeys: childSelectedRowKeys,
>         hideSelectAll: true,
>         onSelect: (record: any, selected: any, selectedRows: any) => {
>             onChildSelectChange(
>                 record, 
>                 selected, 
>                 selectedRows, 
>                 dataSource,
>                 parentSelectedRowKeys, 
>                 childSelectedRows,
>                 childSelectedRowKeys, 
>                 setParentSelectedRowKeys, 
>                 setChildSelectedRows,
>                 setChildSelectedRowKeys,
>             )
>         },
>     }
> 
>     const expandedRowRender = (record: any, index: any, indent: any, expanded: any) => {
>         const ExpandedData = record.ChildList || [];
>         return (
>             <ProTable
>                 rowKey='ID'
>                 columns={subColumns}
>                 headerTitle={false}
>                 search={false}
>                 options={false}
>                 dataSource={ExpandedData}
>                 rowSelection={childRowSelection}
>                 tableAlertRender={false}
>                 tableAlertOptionRender={false}
>                 pagination={false}
>                 scroll={{ x: 100 }}
>             />
>         );
>     };
> 
>     return (
>         <PageContainer>
>             <ProTable<TableItem>
>                 rowKey='ID'
>                 rowSelection={parentRowSelection}
>                 tableAlertRender={({ selectedRowKeys, selectedRows, onCleanSelected }) => {
>                    // How to control here for show or hide ?
>                 }}
>                 expandable={{ expandedRowRender }}
>                 columns={columns}
>             />
>         </PageContainer>
> ```
> 
> ### 🚑 其他信息

**Comment by LiangGu** [comment]
Waiting for resolutions

> ### 🧐 问题描述
> 当页面涉及到主子表格嵌套，且两个表格都需要批量选择的功能，**希望能自定义`tableAlertRender`的显示内容，以及控制其显示或隐藏的状态，以满足实际业务需求**。但目前的`tableAlertRender`好像无法控制其显示或隐藏，只能勾选了对应table组件的行之后，才会出现。
> 
> ### 💻 示例代码
> ```
> const parentRowSelection = {
>         selectedRowKeys: parentSelectedRowKeys,
>         onSelect: (record: any, selected: any, selectedRows: any) => {
>             onParentSelectChange(
>                 record, 
>                 selected, 
>                 selectedRows, 
>                 parentSelectedRowKeys, 
>                 childSelectedRows,
>                 childSelectedRowKeys, 
>                 setParentSelectedRowKeys, 
>                 setChildSelectedRows,
>                 setChildSelectedRowKeys,
>             )
>         },
>         onSelectAll: (selected: any, selectedRows: any, changeRows: any) => {
>             onParentSelectAll(
>                 selected, 
>                 selectedRows, 
>                 changeRows, 
>                 parentSelectedRowKeys, 
>                 setParentSelectedRowKeys, 
>                 setChildSelectedRows,
>                 setChildSelectedRowKeys,
>             )
>         },
>     }
> 
>     const childRowSelection = {
>         selectedRowKeys: childSelectedRowKeys,
>         hideSelectAll: true,
>         onSelect: (record: any, selected: any, selectedRows: any) => {
>             onChildSelectChange(
>                 record, 
>                 selected, 
>                 selectedRows, 
>                 dataSource,
>                 parentSelectedRowKeys, 
>                 childSelectedRows,
>                 childSelectedRowKeys, 
>                 setParentSelectedRowKeys, 
>                 setChildSelectedRows,
>                 setChildSelectedRowKeys,
>             )
>         },
>     }
> 
>     const expandedRowRender = (record: any, index: any, indent: any, expanded: any) => {
>         const ExpandedData = record.ChildList || [];
>         return (
>             <ProTable
>                 rowKey='ID'
>                 columns={subColumns}
>                 headerTitle={false}
>                 search={false}
>                 options={false}
>                 dataSource={ExpandedData}
>                 rowSelection={childRowSelection}
>                 tableAlertRender={false}
>                 tableAlertOptionRender={false}
>                 pagination={false}
>                 scroll={{ x: 100 }}
>             />
>         );
>     };
> 
>     return (
>         <PageContainer>
>             <ProTable<TableItem>
>                 rowKey='ID'
>                 rowSelection={parentRowSelection}
>                 tableAlertRender={({ selectedRowKeys, selectedRows, onCleanSelected }) => {
>                    // How to control here for show or hide ?
>                 }}
>                 expandable={{ expandedRowRender }}
>                 columns={columns}
>             />
>         </PageContainer>
> ```
> 
> ### 🚑 其他信息

**Comment by LiangGu** [comment]
未处理，等待中......

**Comment by chenshuai2144** [comment]
`tableAlertRender={()=>false}
`
这样就能隐藏，没选择是不会显示的

**Comment by DJGDragon** [comment]
想要默认就显示一行提示内容怎么弄呢

**Comment by chenshuai2144** [comment]
@DJGDragon  新开个issue，并且详细描述一下

**Comment by DJGDragon** [comment]
> @DJGDragon 新开个issue，并且详细描述一下

https://github.com/ant-design/pro-components/issues/3316
