### ISSUE TITLE
🧐[问题]Table search不支持表单验证

### ISSUE THREAD

**Issue by LiHwsqh** [ant-design/pro-components#244]
### 🧐 问题描述

protable的search表单用的是form组件，而form组件会判断type，如果type不是form直接就跳过字段校验了，但是现在表格查询需要限制用户的输入应该怎么办呢，比如输入数字范围，最小值不能超过最大值，这时候需要配合validator做校验，感觉可以放开这个限制

### 🚑 其他信息

https://github.com/ant-design/pro-components/blob/e9b44dea61cb5d6e95d4525c7557ecd4e42894c7/packages/table/src/Form/index.tsx#L192

**Comment by chenshuai2144** [comment]
这个是设计，我找设计师对依稀爱

**Comment by LiHwsqh** [comment]
@chenshuai2144 你好，设计怎么说

**Comment by chenshuai2144** [comment]
下个大版本会打开，@LiHwsqh
