### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by flowerDAI** [ant-design/pro-components#2440]
### 🧐 问题描述

想给  ProFormText  设置  valueType=‘money’，但是好像没有这个参数。怎么样才能对ProFormText设置输入限制

### 💻 示例代码

<ProForm.Group>
        <ProFormDateTimePicker required width="md" name="applyTime" label="申请时间" />
        <ProFormText
          required
          width="md"
          name="contract"
          label="出金金额（美元）"
          placeholder="请输入出金金额"
          valueType="money"   // 这个问题
          fieldProps={{

          }}
        />
</ProForm.Group>

**Comment by chenshuai2144** [comment]
可以用 ProFormFiled
