### ISSUE TITLE
🐛[BUG] ProTable设置valueType为dateRange时，request的时间区间会带时分秒

### ISSUE THREAD

**Issue by iambool** [ant-design/pro-components#2442]
### 🐛 bug 描述
参考文档说明，当设置查询字段的valueType类型为dateRange时，获取到的时间格式为 YYYY-MM-DD，但实际获取到的带上了时分秒
![image](https://user-images.githubusercontent.com/30134533/114159670-9a4f6b80-9958-11eb-8ef9-69102e2d68fe.png)

### 🏞 期望结果
期望时间格式同文档说明

### 💻 复现代码
复现示例：https://codesandbox.io/s/chaxunbiaoge-forked-l5c4c?file=/App.tsx

### © 版本信息

- ProComponents 版本:  @ant-design/pro-table: 2.33.0
- umi 版本: 3.4.8
- 浏览器环境: Chrome最新版本
- 开发环境: windows

### 🚑 其他信息
似乎是最近几天才出现的问题（刚发现的）

**Comment by America-first-melon** [comment]
+ 1

**Comment by America-first-melon** [comment]
＋1

**Comment by wanglianjie91** [comment]
+1
