### ISSUE TITLE
🐛[BUG] umi-plugin-antd-icon-config 绝对路径

### ISSUE THREAD

**Issue by lunhui1994** [ant-design/pro-components#2444]
### 🐛 bug 描述

打包文件中存在/node_modules/umi-plugin-antd-icon-config/lib/app.js这样的绝对路径，暴露了服务器的目录路径。应该是跟Pro-Layout有关系。
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lunhui1994** [comment]
是在preset-ant-design-pro中引用的。
![image](https://user-images.githubusercontent.com/18746902/114168641-1e0e5580-9963-11eb-8854-e43b56083e43.png)
![image](https://user-images.githubusercontent.com/18746902/114168718-35e5d980-9963-11eb-8e90-564c63e8bcae.png)

**Comment by chenshuai2144** [comment]
倒是有可能有这样的安全问题。不过编译之后就没了。你们这个是什么场景？

**Comment by lunhui1994** [comment]
> 倒是有可能有这样的安全问题。不过编译之后就没了。你们这个是什么场景？

但是我这边编译之后在 dist 包内会存在类似/Users/xxx 或者在服务器上编辑会存在 类似'/opt/xxx' 这样的绝对路径。想问一下如何避免生成这样的绝对路径。

**Comment by lunhui1994** [comment]
> 倒是有可能有这样的安全问题。不过编译之后就没了。你们这个是什么场景？

因为是对外的项目，所以需要避免出现这样的绝对路径。

**Comment by chenshuai2144** [comment]
你可以需要改下依赖包了。你的 dist 的方便发出来看看吗。

你是没有压缩代码的吗

**Comment by lunhui1994** [comment]
![image](https://user-images.githubusercontent.com/18746902/114828271-48955e00-9dfc-11eb-9fbd-9f4c43e83915.png)
在打包出来umi.js 中会出现类似这样的。

**Comment by lunhui1994** [comment]
> 你可以需要改下依赖包了。你的 dist 的方便发出来看看吗。
> 
> 你是没有压缩代码的吗

![Uploading image.png…]()

**Comment by lunhui1994** [comment]
> 你可以需要改下依赖包了。你的 dist 的方便发出来看看吗。
> 
> 你是没有压缩代码的吗

请教下这个是应该怎么修改？

**Comment by chenshuai2144** [comment]
https://github.com/umijs/plugins

这里有源码，你可以看看这里，在 plugin-layout中

**Comment by chenshuai2144** [comment]
你可能需要给 umi 提pr了，umi 中有很多绝对路径，可能要下个大版本才能解决

**Comment by lunhui1994** [comment]
> 你可能需要给 umi 提pr了，umi 中有很多绝对路径，可能要下个大版本才能解决

好的，感谢～
