### ISSUE TITLE
🧐[问题]protable 如果父组件传值的形式 protable reqest 接受参数，为什么页面数据为空？

### ISSUE THREAD

**Issue by jwptl** [ant-design/pro-components#2445]
### 💻 示例代码
tableData//这个参数是父组件 异步请求拿到数据传过来的
 const getList = async (params: any, sorter: any, filter: any) => {
    return {...params, sorter, filter, data: tableData, success: true}
  }
  return (
    <ProTable<TableListItem>
      headerTitle="公众号健康状态"
      columnEmptyText="-"
      rowKey="id"
      search={false}
      columns={columns}
      scroll={{x: 860}}
      request={(params, sorter, filter) => getList(params, sorter, filter)}
      pagination={{defaultPageSize: 5}}
    />

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/37426271/114162512-bdc7e580-995b-11eb-9efa-a17400afc1dc.png)

**Comment by 15755037307** [comment]
![image](https://user-images.githubusercontent.com/37426271/114162638-df28d180-995b-11eb-9493-8c8b4bb970f5.png)
第一次加载没数据，刷新之后就有数据了，怎么回事呢？

**Comment by chenshuai2144** [comment]
request 是惰性的，不会每次render都出发，你可以每次更新出发一下reload，就会执行了。

这种情况直接用datasource 就好了 request 会带来数据不同步的问题

**Comment by jwptl** [comment]
> request 是惰性的，不会每次render都出发，你可以每次更新出发一下reload，就会执行了。
> 
> 这种情况直接用datasource 就好了 request 会带来数据不同步的问题

好的，已经用了datasource 只是不理解为啥拿不到数据，多谢大佬解开我的疑惑
