### ISSUE TITLE
🧐[protable的pagesize大于100时点击复选框特别卡]

### ISSUE THREAD

**Issue by chenjunjia97** [ant-design/pro-components#2448]
### 🧐 问题描述

数据量小于50的时候没有明显的卡顿，但是大于100时候会有1s的延迟才被选中

**Comment by panchangcheng** [comment]
同问，表格列表字段超过20个，pagesize大于100时候页面渲染很慢，而且点复选框有几秒钟的延迟

**Comment by calefy-chen** [comment]
同问，另外如果列表数据设为100条，接口返回后需要5、6秒才渲染；如果是500条的数据，接口返回后要等待10秒左右才渲染上。
即使去掉columns配置中的所有render还是一样慢。

**Comment by chenjunjia97** [comment]
> 同问，另外如果列表数据设为100条，接口返回后需要5、6秒才渲染；如果是500条的数据，接口返回后要等待10秒左右才渲染上。
> 即使去掉columns配置中的所有render还是一样慢。

是的protable性能没那么好，看看能不能改用普通的table来实现吧，之前查过吧动画取消感觉也没好多少
`.table {
    :global {
        .ant-checkbox-checked .ant-checkbox-inner::after {
            transition: none;
        }
        
        .ant-checkbox-checked::after { 
            animation: none;
        }
    }
}`
最好就是换成Table，然后优化行显示的内容

**Comment by chenshuai2144** [comment]
# 为什么 更新 state 会导致全表渲染？


由于 columns 支持 render 方法，因而 Table 无法知道哪些单元会受到影响。你可以通过 column.shouldCellUpdate 来控制单元格的渲染。

用这个东西吧，能显著的优化性能

**Comment by a1473838623** [comment]
同问。protable应该是table的优化才对，pagesize切换时没有table渲染得快。而且如果输入很大的数字，等待的时间会随着pagesize的数字的增大而增大或者卡死，不管数据有多少。
