### ISSUE TITLE
🐛[BUG]页面组件引用ProLayout如何继承原来的配置？

### ISSUE THREAD

**Issue by birdycn** [ant-design/pro-components#2449]
已经在routes里配置页面组件layout:false

希望能够在页面组件捏，引用Prolayout的同时，继承全局配置，然后部分修改。

已知在app.tsx的layout可以修改，但总觉得不太方便、

比如页面组件触发修改菜单，在app.tsx配置就觉得不太优雅。请问有什么好的办法。

**Comment by chenshuai2144** [comment]
自定义layout

https://beta-pro.ant.design/docs/my-layout-cn
