### ISSUE TITLE
🧐[问题] Less parsing error with new project

### ISSUE THREAD

**Issue by utabuso** [ant-design/pro-components#2450]
### 🧐 问题描述

I tried again with a new, empty create-react-app project:

1. `npx create-react-app testapp`
2. `yarn add antd`
3. `yarn add @ant-design/pro-layout`
4. `yarn add @craco/craco`, `yarn add craco-less`, add `craco.config.js`, `App.css` -> `App.less`, `CracoLessPlugin`, etc. (from https://ant.design/docs/react/use-with-create-react-app)
5. `import '@ant-design/pro-layout/dist/layout.less'` in `App.js`

But same error:

```
./node_modules/@ant-design/pro-layout/dist/layout.less

@import "../es/components/SiderMenu/index.less";
@import "../es/components/TopNavHeader/index.less"
^
Missing semi-colon or unrecognised media features on import
```

I don't have problems with [Ant Design](https://github.com/ant-design/ant-design/), only [ProComponents](https://github.com/ant-design/pro-components).

❓

**Comment by utabuso** [comment]
I followed the directions at https://procomponents.ant.design/en-US/docs/getting-started:

`All our packages use less for style management and easy theme customization. If you don't have less-loader...`
`It is recommended to use less...`

But less-loader can't parse `node_modules/@ant-design/pro-layout/dist/layout.less` due to the above error, which occurs because the filenames are [joined](https://github.com/ant-design/pro-components/blob/master/scripts/gen_less_entry.js#L20) with a semicolon. So the last line does not end with a semicolon.

How does anyone use Less with ProComponents, then, if the less-loader parser fails on the distribution stylesheet?

**Comment by chenshuai2144** [comment]
I remember to configure less-loader.
You can go to umi to ask, I don’t know webpack very well

**Comment by mouthguo** [comment]
#2519 看起来这里已经修复合并了
