### ISSUE TITLE
🧐[问题] How to add form-pro to antd (not antd-pro)

### ISSUE THREAD

**Issue by ducchungtx** [ant-design/pro-components#2455]
### 🧐 问题描述
When I try to install @ant-design/pro-form and using in the project has antd it returns the error.

### 💻 示例代码
I follow this demo: 
https://procomponents.ant.design/components/modal-form

Error message:
TypeError: Cannot read property 'Provider' of undefined
![image](https://user-images.githubusercontent.com/552883/114261560-5ebeab00-9a05-11eb-8845-121765fdfff0.png)

Thanks.

**Comment by AmagiDDmxh** [comment]
I got the same, it's actually causing by ProForm component

**Comment by drizzlesconsin** [comment]
@ducchungtx Please format the code. Or provide [codesandbox](https://codesandbox.io/) example.

**Comment by AmagiDDmxh** [comment]
Using 'antd' package with minor version >= `14.1` fix the problem, checkout this: [https://codesandbox.io/s/proformlist-forked-o5cvn?file=/App.tsx](https://codesandbox.io/s/proformlist-forked-o5cvn?file=/App.tsx)

**Comment by ducchungtx** [comment]
@AmagiDDmxh Just upgrade the library and working perfectly. Thanks very much.
