### ISSUE TITLE
🐛[BUG]pro-table， valueType: 'select'时，针对select进行搜索的时候，数据没有立刻显示出来

### ISSUE THREAD

**Issue by oxygen-xx** [ant-design/pro-components#2456]
### 🐛 bug 描述

在antd pro V5（最新版本，5.0 beta2）的项目下发生的

pro-table的columns定义的片段如下：

      title: '产品选择',
      width: 120,
      dataIndex: 'product_id',
      valueType: 'select',
      hideInTable: true,
      fieldProps: {
        showSearch: true,
        options: productsOptions,
        onSearch: (key: string) => {
          if (key.length > 2) {
            productFetcher(key)
          }
        },
      },
这时候生成的具有搜索功能的select，我们用productFetcher去更新了productsOptions以后，下拉框没有立刻出现搜索出来的数据，这时候其实数据是正确的，需要把下拉框再一次打开，搜索出来的数据才能显示出来。
这里可以确认的是数据已经通过state更新了，所以options: productsOptions中的数据是搜索出来的新数据 。

组件版本：
"@ant-design/pro-form": "^1.20.0",
 "@ant-design/pro-table": "^2.33.0",

### 🚑 其他信息
还试过另一个方案，用组件的request，其实request也在搜索时自动调用了，返回的数据也是正确的。
所以怀疑，当select在pro-table中时，搜索后，数据更新后，select没有立刻刷新。

根据其它人反应的bug，pro-form退到1.6.1版本就解决这个问题了，这个问题，应该存在好久了。几个月了。希望能修复一下。

**Comment by chenshuai2144** [comment]
这个是因为触发了 form 内置的筛选工具，设置了 onSearch 我应该关掉它的。
