### ISSUE TITLE
🧐[问题] ProCard 如何将此padding 设为0

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#2458]
### 🧐 问题描述

![QQ浏览器截图20210411122131](https://user-images.githubusercontent.com/3166799/114292379-be2dc100-9ac0-11eb-99f2-20fac3e58c0f.png)

**Comment by jiyingzhi** [comment]
有个 bodyStyle

**Comment by hihuangwei** [comment]
> 有个 bodyStyle

Card 可以 但 ProCard 不行

**Comment by jiyingzhi** [comment]
`bodyStyle={{ padding: 0 }}` 我试了下是可以的
