### ISSUE TITLE
👑 [需求] 请把Footer组件默认的“Copyright”字样移除，谢谢

### ISSUE THREAD

**Issue by xjb258** [ant-design/pro-components#2459]
### 🥰 需求描述

Footer 组件现在版权的显示样式为：“Copyright @2021 XXXX 公司”，实际上“Copyright”与“@”是同一个意思，存在一个即可。
看看各大公司的官网版权都是这样显示的：“@2021 华为技术有限公司”。而且在多语言下，固定写死一个英文“Copyright”也不好处理。

### 🧐 解决方案

@ant-design\pro-layout\es\Footer.js 文件最后一行修改如下：

copyright: copyright === false ? null : /*#__PURE__*/React.createElement(Fragment, null, **_/*"Copyright ", */_**/*#__PURE__*/React.createElement(CopyrightOutlined, null), " ", copyright || defaultCopyright)

### 🚑 其他信息

最新版本。

**Comment by chenshuai2144** [comment]
感觉是个约定俗称的东西，不过组件的确应该通用一点默认去掉好了
