### ISSUE TITLE
🧐[问题]pro-layout文档中“多个路由对应一个菜单项”例子不完整

### ISSUE THREAD

**Issue by jiachaosun** [ant-design/pro-components#246]
### 🧐 问题描述

1.首先codesandbox中的demo跑不起来
```
Could not find dependency: '@ant-design/pro-layout' relative to '/demo.tsx'
```
<img width="521" alt="图片" src="https://user-images.githubusercontent.com/859382/90616172-af4b8300-e23f-11ea-927f-a48b569cd8e5.png">

2.ProLayout.routes配置中的好几项都有component参数，这块不是很理解，demo项目中根本没有这些components

<img width="222" alt="图片" src="https://user-images.githubusercontent.com/859382/90616114-99d65900-e23f-11ea-908e-a2c8098188a7.png">

**Comment by jiachaosun** [comment]
补充一下，网络环境（iplc专线）肯定是没问题的，所以codesandbox是加载正常

**Comment by jiachaosun** [comment]
补充一下，网络环境（iplc专线）肯定是没问题的，所以codesandbox是加载正常

**Comment by HHHui** [comment]
我知道一个手动修复的办法：
点一下蓝色的那个按钮，添加依赖，然后倒入一下css
import React from 'react';
import ProTable from '@ant-design/pro-table';
import 'antd/dist/antd.css';
import '@ant-design/pro-table/dist/table.css'

**Comment by chenshuai2144** [comment]
components 是 umi 给的，很多例子是直接从 umi 中抠的

**Comment by chenshuai2144** [comment]
indexRouter 不支持了

**Comment by fanck0605** [comment]
@Shunjun 请问有解决方案吗，重定向似乎完成不了相同的事情啊。
