### ISSUE TITLE
🧐[问题] 如何把ProFormText的label 和input 放到同一行？

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#2460]
### 🧐 问题描述
ProFormText的label 和input 缺省不在同一行
有时需要把他们放在同一行

如何把他们放到同一行？

**Comment by drizzlesconsin** [comment]
```ts
layout="horizontal"
```

**Comment by z836454898** [comment]
> ```ts
> <ProForm
>   layout="horizontal"
> />
> ```

没用

**Comment by zoulinchuan** [comment]
这个问题应该在Pro的浮层表单中
放弃使用<ProForm><ProForm>使用 
<ModalForm
     layout='horizontal'
>
      <Row><Col>
<ModalForm>
布局
