### ISSUE TITLE
🐛[BUG] EditableProTable自动分页后切换pageSize导致列表数据清空

### ISSUE THREAD

**Issue by zlllya** [ant-design/pro-components#2464]
### 🐛 bug 描述

EditableProTable配置pagination，分页后切换页面条数导致列表数据清空

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/6331020/114338282-58efd380-9b85-11eb-8e80-01fd53218f4a.png)
![image](https://user-images.githubusercontent.com/6331020/114338390-8f2d5300-9b85-11eb-86d5-23a7c7208a99.png)
如上图，切换到第二页后，再切换页面条数到10页，会触发table的onChange，并且返回的vlaue为空数组，导致列表数据丢失

### 💻 复现代码
官网演示代码配置自动分页，进行分页操作就会复现

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
切换页容器会触发 request 来重新请求网络，所以要先清空数组，估计所以才碰到了这个问题。

有点不好修
