### ISSUE TITLE
🐛[BUG]ProFormTextArea maxLength不生效，未校验

### ISSUE THREAD

**Issue by wangyongsong** [ant-design/pro-components#2465]
### 🐛 bug 描述

设置maxLength = 500 ，超过500仍可输入，并且无校验信息，提交表单也无校验

### 💻 复现代码

```tsx
        <ProFormTextArea
          fieldProps={{
            showCount: true,
            maxLength: 500,
          }}
          name="operateDesc"
          width="xl"
          label="商品描述"
          rules={[{ required: true }]}
        />
```

![image](https://user-images.githubusercontent.com/58172091/114482843-d9700c00-9c39-11eb-86cf-970cf6383f77.png)

### © 版本信息

- ProComponents 版本:  
"@ant-design/pro-form@1.20.0", "@ant-design/pro-form@^1.3.0":
  version "1.20.0"
  resolved "https://registry.npm.taobao.org/@ant-design/pro-form/download/@ant-design/pro-form-1.20.0.tgz#1d72bf013be116af3cb9062d4bf0fed545d0d84a"
  integrity sha1-HXK/ATvhFq88uQYtS/D+1UXQ2Eo=
  dependencies:
    "@ant-design/icons" "^4.2.1"
    "@ant-design/pro-field" "1.14.1"
    "@ant-design/pro-provider" "1.4.9"
    "@ant-design/pro-utils" "1.15.3"
    "@umijs/use-params" "^1.0.2"
    classnames "^2.2.6"
    omit.js "^2.0.2"
    rc-resize-observer "^0.2.3"
    rc-util "^5.0.6"
    use-media-antd-query "^1.0.6"
- 开发环境 [e.g. mac OS]

**Comment by luy19** [comment]
请注意antd的版本是否>=4.7.0，[Input.TextArea](https://ant.design/components/input-cn/#Input.TextArea)

**Comment by wangyongsong** [comment]
第二天早上看了下，已经又生效了，close
