### ISSUE TITLE
🧐[问题] ProTable 自定义筛选，如何将值合并到filter Json 里去

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#2466]
### 🧐 问题描述
将input 里的name 值 合并到下列json
````
filter: {"name":null,"department":["158"]} 
````
![QQ浏览器截图20210412150126](https://user-images.githubusercontent.com/3166799/114353795-066fe080-9ba0-11eb-9eb0-00fcf4ab5441.png)

**Comment by chenshuai2144** [comment]
这个需要自己存起来了，我记得实现超麻烦。
