### ISSUE TITLE
🧐[问题] 用bizcharts 还是 Ant Design Charts？

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#2468]
### 🧐 问题描述

# 图表用那个？bizcharts 还是  Ant Design Charts？

* Ant Design Pro 中用的是：bizcharts 

* ProComponents  中用的是：Ant Design Charts

# 到底选那个好呢？ 

以前都是参考Ant Design Pro中的代码， 但是发现ProComponents用的是Ant Design Charts，是不是未来都会用Ant Design Charts？

所以准备放弃bizcharts， 试着将AntDesignPro中的bizcharts用Ant Design Charts实现。

**Comment by luy19** [comment]
[不要再问G2、G2Plot、Ant Design Charts什么关系了](https://www.yuque.com/antv/g2plot/iqimgm)

**Comment by fanhualei** [comment]
> [不要再问G2、G2Plot、Ant Design Charts什么关系了](https://www.yuque.com/antv/g2plot/iqimgm)

bizcharts  还推荐使用吗？

**Comment by chenshuai2144** [comment]
不推荐了，Ant Design Charts 维护力度更大一点
