### ISSUE TITLE
🧐[问题] proTable 如何获取search.transform 之后的参数

### ISSUE THREAD

**Issue by aLIEzsss4** [ant-design/pro-components#2469]
### 🧐 问题描述

目前只有request的第一个参数会获取到，能不能通过其他方式获取

### 💻 示例代码

```

 formRef={ref}
 
 ref.current.getFieldsValue() 是没转换之前的
```

**Comment by aLIEzsss4** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
onSoubmit中会返回。 不能用 getFieldsValue，getFieldsValue 是最原始的数据

**Comment by aLIEzsss4** [comment]
能不能通过其他途径获取呢，onSubmit 跟request 要触发才能获取到。
业务上可能会出现的场景：第一次进去，选了几个筛选条件，不点查询，直接点导出

**Comment by aLIEzsss4** [comment]
> onSoubmit中会返回。 不能用 getFieldsValue，getFieldsValue 是最原始的数据

能不能通过其他途径获取呢，onSubmit 跟request 要触发才能获取到params。
业务上可能会出现的场景：第一次进去，选了几个筛选条件，不点查询，直接点导出

**Comment by chenshuai2144** [comment]
导出也应该提交一下的，不然不知道导出的是什么了

**Comment by chenshuai2144** [comment]
导出也应该提交一下的，不然不知道导出的是什么了

**Comment by lhzbxx** [comment]
> 导出也应该提交一下的，不然不知道导出的是什么了

如果表单中有 initialValue，这种场景要怎么通过 formRef 获取 transform 后的表单内容呢？

**Comment by chenshuai2144** [comment]
执行以下submit ，然后onSubmit 中能拿到
