### ISSUE TITLE
🧐[问题]ProTable如何设置日期格式的initialValues?

### ISSUE THREAD

**Issue by l745230** [ant-design/pro-components#247]
### 🚑 其他信息

需求:从其他页面带参数访问列表页面,把参数回显到对应的查询框上.

需要帮助:参数日期格式的值进行回显,一直没有尝试出来,文档翻了几遍也没有找到说明.

{
      title: '创建时间',
      dataIndex: 'createTime',
      valueType: 'dateRange',
},

 form={{
          initialValues: {
            // createTime:['2020-08-01','2020-08-03']
            // createTime[0]:'2020-08-01',
            // createTime[1]:'2020-08-03',
            // createTime: [Date.now(), Date.now()],
          },
        }}

一直没有尝试出来, 另外URL要如何拼接createTime的参数?

**Comment by l745230** [comment]
form={{
          initialValues: {
            createTime: [moment().add(1, 'months'), moment().add(6, 'months')],
          },
        }}

在AntDesign文档中查到了. 使用moment格式.

**Comment by chenshuai2144** [comment]
接下来会做个 feature 转化一下
