### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by mumu-baba** [ant-design/pro-components#2471]
### 🐛 bug 描述
prolayout mix模式 openKeys=false 失效

把所有菜单全部在左侧展开了
### 📷 复现步骤
官方例子可复现

prolayout 设置mix 模式。 配置 openKeys=false
### 🏞 期望结果
只展开对应的二级菜单

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Lcj-space** [comment]
兄弟同情你
