### ISSUE TITLE
👑 [需求]前几天看到文档出现的schema-form，怎么不见了~~

### ISSUE THREAD

**Issue by beyond-life-flux** [ant-design/pro-components#2473]
### 🥰 需求描述

希望能出现配置参数生成ProForm的那种schema-form组件，现在的ProForm还支持了ProFormList，融合在一起变成schema-form就很强大了。

### 🚑 其他信息
前几天出现了神奇的SchemaForm的文档
https://procomponents.ant.design/components/schema-form

<img width="654" alt="WechatIMG36334" src="https://user-images.githubusercontent.com/30022286/114507061-2f0dde00-9c65-11eb-8e7d-2220cc679700.png">
<img width="734" alt="WechatIMG36335" src="https://user-images.githubusercontent.com/30022286/114507069-3208ce80-9c65-11eb-930f-2d68781c4875.png">

**Comment by jiyingzhi** [comment]
还没有正式发布
