### ISSUE TITLE
🐛[BUG]ant-design-prov5无法正常使用

### ISSUE THREAD

**Issue by sidely-zzx** [ant-design/pro-components#2474]
### 🐛 bug 描述
ant-design-prov5，react17无法正常安装

### 📷 复现步骤
npm install --save  @ant-design/pro-card
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ant-design-pro@5.0.0-beta.2
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.0" from the root project
npm ERR!   peer react@">=16.9.0" from antd@4.15.1
npm ERR!   node_modules/antd
npm ERR!     antd@"^4.14.0" from the root project
npm ERR!     peer antd@"4.x" from @ant-design/pro-card@1.11.7
npm ERR!     node_modules/@ant-design/pro-card
npm ERR!       @ant-design/pro-card@"*" from the root project
npm ERR!   1 more (react-dom)
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.x" from @ant-design/pro-card@1.11.7
npm ERR! node_modules/@ant-design/pro-card
npm ERR!   @ant-design/pro-card@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### © 版本信息

- ProComponents 版本: [5]
- umi 版本 3
- 浏览器环境 
- 开发环境 [windows npm 7.9]

**Comment by chenshuai2144** [comment]
降级一下npm 或者使用yarn吧。他说以来不兼容，就不让你装了
