### ISSUE TITLE
Sorting on ProTable

### ISSUE THREAD

**Issue by lx9182** [ant-design/pro-components#2478]
Hi all, I have a ProTable and I want to sort by some columns, I can see table will trigger request to get data again then sorting them. And i want to table will sort by current data source, because data will be modified after get from request. Any ideas? 
Thanks

**Comment by KrishnaPG** [comment]
Looking for similar information on **how to sort a ProTable on more than one column**?

Currently when we have multiple sortable columns, only one column is getting sorted. When clicking on the other column, previous sorted columns goes back to normal.

![image](https://user-images.githubusercontent.com/4610831/116965876-89cab080-accc-11eb-87df-03a59b3363f1.png)
