### ISSUE TITLE
🧐[问题] 表格中标签如何自动换行呢？

### ISSUE THREAD

**Issue by nangongmo** [ant-design/pro-components#2479]
### 🚑 其他信息

<img width="1040" alt="Jietu20210414-145218" src="https://user-images.githubusercontent.com/74093067/114666730-2b478d80-9d31-11eb-970d-c26cd46b599a.png">

**Comment by chenshuai2144** [comment]
外面包个 flex。

```
display: flex;
4     flex-wrap: wrap;
```
