### ISSUE TITLE
🐛[BUG] es module 和cjs 混用

### ISSUE THREAD

**Issue by secreter** [ant-design/pro-components#2487]
### 🐛 bug 描述
在使用cjs 引入包时，我期望的是加载'main':'lib/index.js'。并且里面的代码都符合cjs 规范。目前虽然lib/index.js 里面的代码符合cjs。但文件中又引用了antd 的es 文件，antd/es/xx/index。导致项目打包不符合预期

### 📷 复现步骤
查看代码。
![image](https://user-images.githubusercontent.com/10734397/114690503-576f0880-9d49-11eb-9ece-7d72e96a2542.png)

### 🏞 期望结果
'lib/index.js 里面引用的文件也应该引用所依赖包的lib 

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by jernkuan** [comment]
Is there some webpack config or babel plugin import configuration that would help to resolve this from es -> lib?

I notice there is this https://github.com/ant-design/ant-design/issues/22802#issuecomment-607850954 but this didn't seem to help either.

I think I'm having this exact problem using pro-table with next.js.

**Comment by chenshuai2144** [comment]
The latest version has fixed the problem

For a long time, I didn't care about lib

**Comment by chenshuai2144** [comment]
https://unpkg.com/browse/@ant-design/pro-table@2.34.4/lib/utils/columnRender.js


`var _get = _interopRequireDefault(require("rc-util/lib/utils/get"));`

**Comment by fix777** [comment]
[@ant-design/pro-table@2.72.0](https://unpkg.com/browse/@ant-design/pro-table@2.72.0/lib/components/EditableTable/index.js)

Still has `antd/es` imports in the latest version under `lib` code.

**Comment by jaryway** [comment]
js中是改了，但是inde.less  文件中没有用改，导致前缀没有修改成功
[@ant-design/pro-table@2.78.2](https://unpkg.com/browse/@ant-design/pro-table@2.78.2/lib/index.less)
