### ISSUE TITLE
🧐[问题]pro-table表单label字数较多时显示不全

### ISSUE THREAD

**Issue by ray1347227** [ant-design/pro-components#249]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/21354564/90628043-7f0be080-e24f-11ea-92cf-582ccef77634.png)

**Comment by jerryluo852** [comment]
我也有显示不全的问题，字数就两个单词
<img width="1177" alt="Screenshot 2020-08-20 at 9 52 43 AM" src="https://user-images.githubusercontent.com/50260842/90707901-28dc8300-e2cb-11ea-9658-4292dedb9027.png">

**Comment by chenshuai2144** [comment]
可以 设置  `search.labelWidth` 来配置，这样可以显示的很整齐

**Comment by chenshuai2144** [comment]
@erichDuanET  可以用 css hack 一下，或者使用我们最新提供的

http://localhost:8000/components/form#%E6%9F%A5%E8%AF%A2%E7%AD%9B%E9%80%89-%E5%9E%82%E7%9B%B4%E5%B8%83%E5%B1%80

**Comment by gongmin00** [comment]
> 个别字段较长的，统一处理了labelWidth，会有点丑，输入框太短，前面空太多；
> 
> 这个事情很难均衡. **是否可以保留原方案作为可选择的配置呢？**

直接labelWith:'auto'自动适配就好，不用统一长度
