### ISSUE TITLE
🧐[问题]ProTable能否修改筛选表单的按钮和收起位置

### ISSUE THREAD

**Issue by AoaoMH** [ant-design/pro-components#2492]
### 🧐 问题描述

ProTable能否修改筛选表单的按钮和收起位置？
如下图。

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/29968512/114804042-2cc99200-9dd3-11eb-800f-d1057be7a24e.png)

**Comment by chenshuai2144** [comment]
你这个是触发了bug了吧。不应该在中间的

**Comment by chenshuai2144** [comment]
看懂了，你想自定义，是可以做到但是很复杂，我建议不要搞这种微创新，没有带来任何进步。只是能满足一下设计师的个人审美

**Comment by AoaoMH** [comment]
> 看懂了，你想自定义，是可以做到但是很复杂，我建议不要搞这种微创新，没有带来任何进步。只是能满足一下设计师的个人审美

谢谢

**Comment by AoaoMH** [comment]
> 看懂了，你想自定义，是可以做到但是很复杂，我建议不要搞这种微创新，没有带来任何进步。只是能满足一下设计师的个人审美

能给一个实现思路吗。

**Comment by chenshuai2144** [comment]
用 antd 自己搭建算了。
或者默认的按钮隐藏掉自己控制收起展开和提交
