### ISSUE TITLE
👑 [需求] ProCard 无法响应式布局

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#2497]
### 🥰 需求描述
![Screenshot_2021-04-15-13-28-21-443_com android chrome](https://user-images.githubusercontent.com/3166799/114818571-94410b00-9dee-11eb-9f09-7683bb89070e.jpg)
![Screenshot_2021-04-15-13-26-38-643_com android chrome](https://user-images.githubusercontent.com/3166799/114818586-9b681900-9dee-11eb-8d06-c08701b958ac.jpg)
在大屏幕下左右分栏，在小屏幕下上下分栏

**Comment by rdmclin2** [comment]
官网已添加响应式布局案例。

**Comment by hihuangwei** [comment]
> 官网已添加响应式布局案例。

没找到是哪个案例

**Comment by rdmclin2** [comment]
> > 官网已添加响应式布局案例。
> 
> 没找到是哪个案例

https://procomponents.ant.design/components/card#card-split 

我基本缩小了都看了一遍，把需要响应式布局的示例都加了一下。
