### ISSUE TITLE
🐛[BUG] ProTable 默认筛选发出请求带上了默认值，而默认选项未高亮

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#2498]
### 🐛 bug 描述

![mmexport1618464769467](https://user-images.githubusercontent.com/3166799/114818863-13ceda00-9def-11eb-8a19-a345f3c7a514.png)

**Comment by chenshuai2144** [comment]
这个可能是设置到 antd里，antd 的筛选我记得不是受控的

**Comment by hihuangwei** [comment]
> 这个可能是设置到 antd里，antd 的筛选我记得不是受控的

翻页后，默认值就不会带着请求

**Comment by chenshuai2144** [comment]
我们暂时不会处理这个问题，等待antd@5
