### ISSUE TITLE
🧐[问题] ProTable 怎么在一个请求还没回来时，再次触发 request？

### ISSUE THREAD

**Issue by linxianxi** [ant-design/pro-components#2499]
### 🧐 问题描述

https://codesandbox.io/s/chaxunbiaoge-forked-cbr7c?file=/App.tsx

一直点击查询，只有当请求结束时才能触发下一次请求。
场景：例如我改变一个条件查询，请求还没回来，这时候我又改变了一个条件，却触发不了查询。

**Comment by linxianxi** [comment]
@chenshuai2144 看一下能做吗

**Comment by chenshuai2144** [comment]
为什么要这么做呢？

**Comment by linxianxi** [comment]
> 为什么要这么做呢？

上面写了。就是请求还没结束的时候用户又触发了一次请求，这时候没有执行最新的请求。请求的时候把这些控件都 disabled 感觉不太好，需要等待。

**Comment by linxianxi** [comment]
> 为什么要这么做呢？

看了源码，这里注释掉就可以了，不知道会造成什么影响（bug）吗
![image](https://user-images.githubusercontent.com/47104575/114824359-598fa080-9df7-11eb-91db-a77028eda0b5.png)

**Comment by linxianxi** [comment]
> > 为什么要这么做呢？
> 
> 看了源码，这里注释掉就可以了，不知道会造成什么影响（bug）吗
> ![image](https://user-images.githubusercontent.com/47104575/114824359-598fa080-9df7-11eb-91db-a77028eda0b5.png)

改动之后 loading 出现了问题。第一次请求结束后 loading 就为 false 了。目前就发现这个问题，后面的请求的 loading 在设置为 false 之前就设置 true 了。

**Comment by linxianxi** [comment]
改动之后 loading 出现了问题。第一次请求结束后 loading 就为 false 了。目前就发现这个问题，后面的请求的 loading 在设置为 false 之前就设置 true 了。

**Comment by linxianxi** [comment]
这样子 loading 的计算会有问题

**Comment by chenshuai2144** [comment]
按钮一直在loading状态中，你没法出发新的更新的

**Comment by linxianxi** [comment]
> 按钮一直在 loading 状态中，你没法触发的，protable 里面的是去抖，不是节流可能满足不了你的需求

因为设置了按钮的loading 为 false 或者轻量筛选。以后能加个节流 api 就好了。目前我自己改了代码

**Comment by chenshuai2144** [comment]
protable 自带的就是防抖，你可以设置为 0 试试

**Comment by linxianxi** [comment]
> protable 自带的就是防抖，你可以设置为 0 试试

但是protable的在loading的时候不会触发 request。并没用。我fork的代码改成了有多个请求时，前面的 success 为 false，最后一个为 true。loading 也是最后请求完才为 false。

**Comment by mouthguo** [comment]
理一理需求，就是：
1. 点击查询后，查询按钮可以继续点
2. 防抖还是需要的 ，300过后，可以进行下一次点击请求，此时，如果上一次请求没有返回，就不要上一次的请求了，始终是以最后、最新的一次请求为准的。

关于第 1 条，你已经通过设置 loading 为 false 解决了；
第 2条，现在是改了源码实现的；
可以参考陈帅大大的，把防抖 polling 设置为 0，然后，自己搞个 带防抖的 request 就好了

```js
// 以 axios 举个例子
const CancelToken = axios.CancelToken;

const cancelToken = useRef(null);
// lodash 的 debounce 就可以哈，自己写也可以
const debouncedRequest = useCallback(debounce((params) => {
    // 新请求来了，发现上次请求还没结束，就取消了
    if (cancelToken.current) {
        cancelToken.current('new request coming, cancel prev request.');
    }
    return axios.get('/api/foo', {
        params,
        cancelToken: new CancelToken(function executor(c) {
            // 请求发出去的时候，把取消记下来
            cancelToken.current = c;
        })
    }).then((res) => {
        // 请求返回了，就清除标记
        cancelToken.current = null;
        // 有需要，就处理一下返回值
        return res;
    }).catch((e) => {
        // 被取消的请求,想拦截了这里拦截一下，不想拦截就不拦了
        if (axios.isCancel(e)) {
            return emptyRes; // 可以返回个需要的空值什么的
        }
        throw e;
    });
}, 300), []);
```

**Comment by hemengke1997** [comment]
插眼

**Comment by xian107** [comment]
> 理一理需求，就是：
> 
> 1. 点击查询后，查询按钮可以继续点
> 2. 防抖还是需要的 ，300过后，可以进行下一次点击请求，此时，如果上一次请求没有返回，就不要上一次的请求了，始终是以最后、最新的一次请求为准的。
> 
> 关于第 1 条，你已经通过设置 loading 为 false 解决了； 第 2条，现在是改了源码实现的； 可以参考陈帅大大的，把防抖 polling 设置为 0，然后，自己搞个 带防抖的 request 就好了
> 
> ```js
> // 以 axios 举个例子
> const CancelToken = axios.CancelToken;
> 
> const cancelToken = useRef(null);
> // lodash 的 debounce 就可以哈，自己写也可以
> const debouncedRequest = useCallback(debounce((params) => {
>     // 新请求来了，发现上次请求还没结束，就取消了
>     if (cancelToken.current) {
>         cancelToken.current('new request coming, cancel prev request.');
>     }
>     return axios.get('/api/foo', {
>         params,
>         cancelToken: new CancelToken(function executor(c) {
>             // 请求发出去的时候，把取消记下来
>             cancelToken.current = c;
>         })
>     }).then((res) => {
>         // 请求返回了，就清除标记
>         cancelToken.current = null;
>         // 有需要，就处理一下返回值
>         return res;
>     }).catch((e) => {
>         // 被取消的请求,想拦截了这里拦截一下，不想拦截就不拦了
>         if (axios.isCancel(e)) {
>             return emptyRes; // 可以返回个需要的空值什么的
>         }
>         throw e;
>     });
> }, 300), []);
> `

当还在请求中时候，改变params的值，request函数没有重新触发，请问应该怎么解决啊？求大神们指点
