### ISSUE TITLE
🐛[BUG]ProTable 轻量筛选时用renderFormItem定义的输入框无法清除

### ISSUE THREAD

**Issue by davidjia1972** [ant-design/pro-components#2501]
### 🐛 bug 描述

在column中定义了这样一列

    {
      title: '身份证号',
      dataIndex: 'identityNumber',
      renderFormItem: (item, { type, defaultRender, ...rest }, form) => {
        if (type === 'form') {
          return null;
        }

        return (
          <Form.Item {...rest} rules={[...fieldRuls['identity']]} label="" name="identityNumber">
              <Input autoComplete="off"/>
          </Form.Item>
        )
      },

当ProTable中 filterType: 'light' 按清除按钮没有效果，但是如果设置成 filterType: 'query'的时候，重置按钮是工作的

当然，这两种模式的查询都是工作的。

### © 版本信息

- ant-design/pro-table版本 2.34.0
- antd版本 4.15.1 
- umi 版本 3.4.8 
- 浏览器环境 Google Chrome 版本 89.0.4389.114
- 开发环境  macOS

**Comment by davidjia1972** [comment]
抱歉我继续用中文了。

GitHub repository 在https://github.com/davidjia1972/AndDesignProPractice

运行起来并且登录以后，点击”会员列表“，在表头的轻量筛选那里，身份证号和手机号在输入了内容以后，点击”清除“都没有效果。但是如果把src/pages/MemberList/index.tsx第283行改成filterType: 'query'，也就是普通的form，这时”重置“按钮工作是正常的。

另外，我给Form.Item加的rules属性，用pro-table 2.33的时候是工作正常的，但升级到2.34以后校验规则就不工作了，请一并看一下吧。多谢了

**Comment by chenshuai2144** [comment]
```
{
  title: '身份证号',
  dataIndex: 'identityNumber',
  renderFormItem: (item, { type, defaultRender, ...rest }, form) => {
    if (type === 'form') {
      return null;
    }

    return (  
          <Input autoComplete="off"/>
    )
  },
```


这样感觉就可以了
