### ISSUE TITLE
ProForm下的ProFormText placeholder配置无效 🐛[BUG]

### ISSUE THREAD

**Issue by GaoQi2019** [ant-design/pro-components#2502]
### 🐛 bug 描述

ProForm下的ProFormText placeholder配置无效

### 🏞 期望结果

希望  proformtext里的"请输入"变为 “公司Beacon账号互通”

### 💻 复现代码

 <ProForm
        submitter={{
          render: (_, dom) => dom.pop(),
          submitButtonProps: {
            loading: loading,
            size: 'large',
            style: {
              width: '100%',
            },
          },
        }}
        onFinish={(values) => {
          handleSubmit(values);
          return Promise.resolve();
        }}
      >
        {status < 0 && !loading && (
          <LoginMessage
            content={intl.formatMessage({id:`${intlString}accountLogin.tab`})}
          />
        )}

        <ProFormText
          name="userName"
          fieldProps={{
            size: 'large',
            prefix: <UserOutlined className={styles.prefixIcon} />,
          }}
          placeholder="公司Beacon账号互通"
          rules={[
            {
              required: true,
              message: (
                <FormattedMessage
                  id={`${intlString}username.required`}
                />
              ),
            },
          ]}
        />
        <ProFormText.Password
          name="password"
          placeholder = "公司Beacon账号互通"
          fieldProps={{
            size: 'large',
            prefix: <LockTwoTone className={styles.prefixIcon} />,
          }}

          rules={[
            {
              required: true,
              message: (
                <FormattedMessage
                  id={`${intlString}password.required`}
                />
              ),
            },
          ]}
        />
      </ProForm>

### © 版本信息

- ProComponents 版本:  "@ant-design/pro-form": "^1.3.0",
- umi 版本 3.2.14
- 浏览器环境 Google 89
- 开发环境 [windows]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/52390280/114824474-804dd700-9df7-11eb-9abb-c6c2fe295c68.png)

**Comment by chenshuai2144** [comment]
```
fieldProps={
{    placeholder:"公司Beacon账号互通" }
}
```

先这样绕开一下，我看看为什么不生效

**Comment by GaoQi2019** [comment]
> ```
> fieldProps={
> {    placeholder:"公司Beacon账号互通" }
> }
> ```
> 
> 先这样绕开一下，我看看为什么不体现

嗯嗯，这样可以啦，谢谢，是不能像我之前那样写嘛

**Comment by chenshuai2144** [comment]
能的，应该可以，但是可能现在被覆盖了

**Comment by chenshuai2144** [comment]
我测试了一下没这个问题，估计是你版本的问题
