### ISSUE TITLE
🐛[BUG] ProTable columns 更新后 hideInSearch 失效

### ISSUE THREAD

**Issue by SturdyCat** [ant-design/pro-components#2503]
### 🐛 bug 描述

 ProTable columns 更新后 hideInSearch 失效

### 📷 复现步骤

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/04pi2?file=/App.tsx)

### 🏞 期望结果
columns 中的 hideInSearch 正常

**Comment by chenshuai2144** [comment]
你的 demo 和我的测试用例都没有问题。你要复现方式吗？

吓死我了

**Comment by SturdyCat** [comment]
@chenshuai2144 是看不到我的demo，还是你点击按钮后没看到效果？
点击我设置的按钮
```
 {
    title: "状态",
    dataIndex: "state",
    valueType: "select",
    hideInSearch: false  // 点击按钮后这个属性会被设置true，但是无效 toolBar 仍然显示
  },
```

**Comment by luy19** [comment]
确实有这个问题，可以通过设置key的方式来修复：
```
63 -     <>
63 +    <React.Fragment key={newColumns ? 1 : 2}>
            ......
103 -    </>
103 +   </React.Fragment>
```

**Comment by chenshuai2144** [comment]
我点击之后是能work的，你是不是版本问题

**Comment by SturdyCat** [comment]
> 我点击之后是能work的，你是不是版本问题

@chenshuai2144 

我将 antd 和 @ant-design/pro-table 都将版本设置为最新版
我浏览器测试了 chrome 和 safari 
操作系统测试了 mac 和 windows 
都是同样问题

![WX20210419-144507](https://user-images.githubusercontent.com/16874676/115192740-cd92b700-a11d-11eb-9a97-95eb1e57abdd.png)

如果工作正常这里应该回消失

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/04pi2?file=/App.tsx)

**Comment by chenshuai2144** [comment]
试了下没有问题
