### ISSUE TITLE
🐛[BUG] ProTable-search-optionRender 自定义重置按钮之后，搜索表单清空了，但是request的方法还是把填过的值返回来了

### ISSUE THREAD

**Issue by z-lionel** [ant-design/pro-components#2504]
如题，
ProTable-search-optionRender 自定义重置按钮之后，搜索表单清空了，但是request的方法还是把填过的值返回来了，
但是我再request方法里面用formRef getfieldsValue去获取表单的值，已经是重置后的值.
```
 optionRender: ({ searchText, resetText }, { form }) => [
                        <Button
                            key="search"
                            type="primary"
                            onClick={() => {
                                form?.submit();
                            }}
                        >
                            {searchText}
                        </Button>,
                        <Button
                            key="rest"
                            onClick={() => {
                                form?.resetFields();
                                const reloadAndRest = actionRef?.current?.reloadAndRest;
                                reloadAndRest && reloadAndRest();
                            }}
                        >
                            {resetText}
                        </Button>,
]

```

**Comment by davidjia1972** [comment]
抱歉我继续用中文了。

GitHub repository 在https://github.com/davidjia1972/AndDesignProPractice

运行起来并且登录以后，点击”会员列表“，在表头的轻量筛选那里，身份证号和手机号在输入了内容以后，点击”清除“都没有效果。但是如果把src/pages/MemberList/index.tsx第283行改成filterType: 'query'，也就是普通的form，这时”重置“按钮工作是正常的。

另外，我给Form.Item加的rules属性，用pro-table 2.33的时候是工作正常的，但升级到2.34以后校验规则就不工作了，请一并看一下吧。多谢了

**Comment by z-lionel** [comment]
> Hello @z-lionel. Please provide a online reproduction by forking this link https://codesandbox.io/ or a minimal GitHub repository.
> 
> 你好 @z-lionel, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/protable-s8jj3?file=/src/App.tsx
输入参数点击搜索之后，再点击重置，可以看到打印出来的参数还带有上次输入的结果

**Comment by mouthguo** [comment]
看起来没有调用 [reset](https://github.com/ant-design/pro-components/blob/a930e1f141ee0c87e9e373bc4efe76ba3faff9f7/packages/table/src/utils/index.ts#L94-L100) 的样子

**Comment by chenshuai2144** [comment]
使用 reset 吧，不要用 reloadAndRest

reloadAndRest 只是清空页码

**Comment by z-lionel** [comment]
> 使用 reset 吧，不要用 reloadAndRest
> 
> reloadAndRest 只是清空页码

这又有问题了，如果有个select有个默认值，用reset就会导致默认值也清空了

**Comment by chenshuai2144** [comment]
不是用的 initlvalues 赋值的吗？

**Comment by z-lionel** [comment]
> 不是用的 initlvalues 赋值的吗？

更新了，可以看看，就是想达没有添加optionRender默认时候的效果
https://codesandbox.io/s/protable-s8jj3?file=/src/App.tsx

**Comment by jiyingzhi** [comment]
@z-lionel 其实 optionRender 还有第三个参数，文档里没有体现出来，如果想要没有添加 optionRender 时的效果可以这样：
![image](https://user-images.githubusercontent.com/21698836/115208656-60881d00-a12f-11eb-9edf-5a4014463fc1.png)

**Comment by z-lionel** [comment]
> @z-lionel 其实 optionRender 还有第三个参数，文档里没有体现出来，如果想要没有添加 optionRender 时的效果可以这样：
> 
> ![image](https://user-images.githubusercontent.com/21698836/115208656-60881d00-a12f-11eb-9edf-5a4014463fc1.png)

谢了大兄弟，这个方法可行
