### ISSUE TITLE
🐛[BUG]ProTable Form查询时formItemProps.rules不起作用

### ISSUE THREAD

**Issue by davidjia1972** [ant-design/pro-components#2506]
### 🐛 bug 描述

做这样儿一个列定义

    {
      title: '手机号码',
      dataIndex: 'mobile',
      formItemProps: {
        rules: [{
          required: false,
          pattern: new RegExp(/^1[3-9]\d{9}$/, "g"),
          message: '请输入正确的手机号码'
        }],
      },
    },

上面定义了一个rules，当ProForm的search.filterType为light（也就是轻量模式）的时候，这个规则时工作的，但当它处于query的模式的时候，这个规则就不工作了。

### © 版本信息

- ProComponents 版本:  pro-table 2.33
- antd版本 4.15.1
- umi 版本 3.4.8
- 浏览器环境 Google Chrome 版本 89.0.4389.114
- 开发环境 macOS

<img width="716" alt="截屏2021-04-15 下午6 40 55" src="https://user-images.githubusercontent.com/37530927/114856965-4cd07400-9e1a-11eb-9fdc-56188cee0d33.png">
<img width="721" alt="截屏2021-04-15 下午6 40 27" src="https://user-images.githubusercontent.com/37530927/114856997-5659dc00-9e1a-11eb-88bd-82ca05dd5630.png">

**Comment by davidjia1972** [comment]
总体上感觉ProTable 的这两个search.filterType的处理逻辑不一致

**Comment by chenshuai2144** [comment]
这个是故意这么做的，你可以通过 ignoreRules 这个props 来控制
