### ISSUE TITLE
👑 [需求] ProDescriptions 建议增加 value 对齐的样式

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#2508]
### 🥰 需求描述

类似这样的
![QQ浏览器截图20210415185830](https://user-images.githubusercontent.com/3166799/114859221-06c8df80-9e1d-11eb-968a-67b8fe12fbf7.png)

**Comment by gaohongwei** [comment]
同问。ProFormText也有这种需求。

**Comment by chenshuai2144** [comment]
设计稿来一下

**Comment by mouthguo** [comment]
额，这个需求是很普遍的哈
看起来和 antd Descriptions 添加 [bordered](https://ant.design/components/descriptions-cn/#components-descriptions-demo-border) 属性类似哦。
bordered 设置为 true 时，label 和 content 都被视作表格的列来设置，通过表格来实现对齐，工作量看起来最小；

不然的话，就是
1. 给 label 设置定宽
2. 搞栅栏布局

对于 1 来说，业务侧更容易掌握状况，通过合理设置来保证足够的位置；
对于 2 来说，内部设置的话，不设置缺省的比例没有意义，设置的话，同样也会遇到 1 的问题。

回过来看，如果是组件侧来做，还是通过表格来，兼容性更高；
那么就可以认为，是需要一个纯粹来对齐而不需要 设置 border 的行为。

这样的话，个人感觉，[去 antd 提 Descriptions 的需求](https://github.com/ant-design/ant-design/issues)，更合适一些。 从 pro-components 这里来做的话，对样式入侵性太强了

**Comment by hihuangwei** [comment]
> 设计稿来一下

这样的
![QQ浏览器截图20210416120212](https://user-images.githubusercontent.com/3166799/114969963-075c8700-9eac-11eb-94d4-f1cfff7c9b34.png)

**Comment by chenshuai2144** [comment]
这个现在就是这样的吧

**Comment by hihuangwei** [comment]
搞定 via  https://github.com/ant-design/ant-design/issues/30170#event-4607430261
