### ISSUE TITLE
🐛[BUG] ProLayout 当父级菜单与子菜单相似匹配时，菜单选中多个

### ISSUE THREAD

**Issue by Moln** [ant-design/pro-components#2511]
### 🐛 bug 描述

见  [复现代码](https://codesandbox.io/s/pro-layout-menu-bug-z42gr) 菜单: `Project`, `Setting > Members` 被选中. 
调试查看 `<Menu />` 组件 `selectedKeys` 属性值不应该是 `["/project","/project/setting/members"]`.

```
  const menus = [
    {
      path: "/project",  // 父菜单链接
      exact: true, 
      name: "Project"
    },
    {
      name: "Setting",
      children: [
        {
          name: "Members",
          path: "/project/setting/members",  // 子菜单链接
          exact: true
        },
        {
          name: "Roles",
          path: "/project/setting/roles", 
          exact: true
        }
      ]
    }
  ];
```

```
<Menu selectedKeys={["/project","/project/setting/members"]} ... />
```

### 📷 复现步骤

https://codesandbox.io/s/pro-layout-menu-bug-z42gr

### 🏞 期望结果

https://github.com/ant-design/pro-components/blob/master/packages/layout/src/BasicLayout.tsx#L327-L329

`matchMenus` 值应该只有 `"/project/setting/members"`.

```
<Menu selectedKeys={["/project/setting/members"]} ... />
```

### 💻 复现代码

https://codesandbox.io/s/pro-layout-menu-bug-z42gr

### © 版本信息

- @ant-design/pro-layout: 6.16.2

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/2050694/114900690-b49cb400-9e46-11eb-92eb-c5b40862281e.png)

**Comment by Moln** [comment]
其它类似问题: #1001 #1002

**Comment by chenshuai2144** [comment]
这个是featrue，我们是通过路径的相关性来计算选中的。我觉得你的菜单设置是有问题的。
/project 应该是 project/home 之类的，而不是一个超级大的父亲最为平级节点。

当然也是有解决办法的，就是设置不同的key，我们会优先使用key

**Comment by oyhk** [comment]
@chenshuai2144 具体代码是怎么实现的呢？为什么我加了key还是会选中多个菜单

**Comment by chenshuai2144** [comment]
调换一下顺序呢？

**Comment by oyhk** [comment]
@chenshuai2144 试过了

**Comment by chenshuai2144** [comment]
能给个仓库吗？ 我debug一下算法

**Comment by oyhk** [comment]
@chenshuai2144 暂时没有

**Comment by cuijiudai** [comment]
> 这个是featrue，我们是通过路径的相关性来计算选中的。我觉得你的菜单设置是有问题的。 /project 应该是 project/home 之类的，而不是一个超级大的父亲最为平级节点。
> 
> 当然也是有解决办法的，就是设置不同的key，我们会优先使用key

能关掉这个feature 吗，上下级应该根据routes 的嵌套来确定。

**Comment by cuijiudai** [comment]
@oyhk 实现出来了吗？
