### ISSUE TITLE
🐛[BUG] EditableProTable 分页 点击新建按钮 列表消失

### ISSUE THREAD

**Issue by JoeXin** [ant-design/pro-components#2512]
### 🐛 bug 描述

EditableProTable配置pagination后，新建一行列表消失

### 📷 复现步骤

地址：https://codesandbox.io/s/zidingyikebianjibiaoge-forked-h1x8b

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/2529
