### ISSUE TITLE
🐛[BUG]ProFormSelect单选搜索问题

### ISSUE THREAD

**Issue by davidjia1972** [ant-design/pro-components#2517]
### 🐛 bug 描述

[Issues 2288](https://github.com/ant-design/pro-components/issues/2288)提出的Bug其实不仅仅在Clear的时候存在。如果不点Clear图标，直接点击组件激活下拉列表，此时用来搜索的输入框已经没有内容，但仍旧是只能看到上次搜索的结果，还是需要输入任何字符再删除才能看到全部列表。

### 🏞 期望结果
搜索并选中内容之后清除搜索状态，再次点击的时候可以看到全部列表内容

### © 版本信息
ant-design_pro-form 1.21.1

### 🚑 其他信息
<img width="188" alt="截屏2021-04-16 下午3 04 05" src="https://user-images.githubusercontent.com/37530927/114985394-55ca4f80-9ec5-11eb-95b8-1f0d4ff63604.png">
看上面这个Select，本来56个民族都在的，搜索汉族并选择之后，再点击就只能看到汉族了。和之前Clear的Bug一样，要随便输入内容再删除才能重新看到全部。

**Comment by davidjia1972** [comment]
不知道是不是应该在onDropdownVisibleChange里面也执行一下onClear

**Comment by chenshuai2144** [comment]
顺便在这里修掉了

https://github.com/ant-design/pro-components/pull/2531

**Comment by xiaojun1314** [comment]
这个问题多选应该也存在
