### ISSUE TITLE
👑 [需求]金额配置相关

### ISSUE THREAD

**Issue by txp1035** [ant-design/pro-components#2520]
### 🥰 需求描述

![image](https://user-images.githubusercontent.com/9554297/114993207-2a982e00-9ece-11eb-95da-aea9dbe6e487.png)
每次想使用金额类型但是多了个人民币符号就很难受，格式化是肯定有用的，币种强制加上就比较奇怪，多币种的情况就不能使用了

### 🧐 解决方案

去掉人民币符号

**Comment by chenshuai2144** [comment]
这个其实是跟着国际化配置改的
