### ISSUE TITLE
🐛[BUG] ProFormSwitch 设置 checkedChildren 失效

### ISSUE THREAD

**Issue by zjxpcyc** [ant-design/pro-components#2523]
### 🐛 bug 描述

`ProFormSwitch` 如果通过 `fieldProps` 透传 `checkedChildren` 属性会失败

### 📷 复现步骤

```javascript
<ProFormSwitch
        label="视频"
        name="isVideo"
        fieldProps={{
          checkedChildren: "视频",
          unCheckedChildren: "图文",
        }}
      />
```

如上设置会失败

### 🏞 期望结果

不需要将  `checkedChildren` 等属性透传给 `ProFormSwitch` 。

因为官网文档上有说明 (每个表单项都支持 fieldProps 属性来支持设置输入组件的props) [https://procomponents.ant.design/components/field-set] .

而且，我觉得这样也挺好，规范，统一。要不然，你根本不知道哪个 `procomponents` 的属性没有走 `fieldProps`

就像我上面实例代码一样，能正常使用最好

### © 版本信息

- ProComponents 版本: [ 不清楚, 官网没有地方说明 ]
- umi 版本 3.4.1
- 浏览器环境 Chrome90
- 开发环境 win10

**Comment by chenshuai2144** [comment]
修改了一下优先级，我们这边都有ts，ts会提示你有哪些的
