### ISSUE TITLE
🧐[问题]设置searchValue，筛选结果关键字没有高亮显示

### ISSUE THREAD

**Issue by BabyFriedCake** [ant-design/pro-components#2530]
### 🧐 问题描述
点击关键字“c”，设置searchValue控制open，筛选结果关键字没有高亮显示

### 💻 示例代码
        import React, { useState } from "react";
        import { ProFormSelect } from "@ant-design/pro-form";
        import "antd/dist/antd.css";
        import "./styles.css";
        
        export default function App() {
          const [searchValue, setSearchValue] = useState("");
          const [selectOpen, setSelectOpen] = useState(false);
        
          function onBlur() {
            setSelectOpen(false);
          }
        
          function onFocus() {
            setSelectOpen(true);
          }
        
          /** 点击常用关键字的字母 */
          function onClick(e: any) {
            const text = e.target as HTMLSpanElement;
            // 更改搜索框文字
            setSearchValue(text.innerText);
            onFocus();
          }
        
          /** 下拉搜索 */
          function onSearch(value: string) {
            setSearchValue(value);
          }
        
          /** 下拉选中 */
          function onSelect() {
            onBlur();
          }
        
          return (
            <div>
              <ProFormSelect
                name="name"
                placeholder="请输入搜索关键字"
                allowClear
                width={330}
                secondary
                valueEnum={{
                  1001: "jack",
                  1002: "lucy",
                  1003: "emliy"
                }}
                fieldProps={{
                  showArrow: false,
                  showSearch: true, // 使单选模式可搜索
                  dropdownMatchSelectWidth: false,
                  optionFilterProp: "label", // 搜索时过滤对应的 option 属性
                  optionLabelProp: "label", // 回填到选择框的 Option 的属性值
                  searchValue,
                  open: selectOpen,
                  onBlur: () => onBlur(),
                  onFocus: () => onFocus(),
                  onSearch: (val) => onSearch(val),
                  onSelect: () => onSelect()
                }}
              />
              <div className="keys">
                <b>常用关键字：</b>
                {["l", "c", "a"].map((item) => {
                  return (
                    <span key={item} onClick={onClick}>
                      {item}
                    </span>
                  );
                })}
              </div>
            </div>
          );
        }

### 🚑 其他信息
代码
https://codesandbox.io/s/holy-water-qxq1j?file=/src/App.tsx

**Comment by chenshuai2144** [comment]
searchValue 这个props 是什么意思？
