### ISSUE TITLE
🧐[问题]ProForm 里面的Item 的 label 是否能对齐？

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#2533]
### 🧐 问题描述

ProForm 里面有多个Item，
采用 layout="horizontal"
希望每个item 的 label 对齐，宽度相同
试了 labelStyle={{ width: "100px" }}, 不管用

下图中的  label 没对齐，不好看

![image](https://user-images.githubusercontent.com/5349879/115185896-9a0c4a00-a095-11eb-82af-9fb8736e8569.png)

**Comment by jiyingzhi** [comment]
用 labelCol：
```js
labelCol={{ span: 6 }}
```

**Comment by chenshuai2144** [comment]
或者可以设置 labelStyle 来个最小宽度

**Comment by kiwikaki** [comment]
> labelStyle

labelStyle属性那里能看到，官网没找介绍

**Comment by zlllya** [comment]
上面都试了，labelCol没效果，labelStyle没有这个属性，目前采用的方法是label用div设置最小宽度传入

**Comment by chenshuai2144** [comment]
layout="horizontal" 好像都不支持，要用 inline

**Comment by harry0071** [comment]
试试 ： <ProForm layout="horizontal" labelCol={{ span: 3 }} > ......  </ProForm>
