### ISSUE TITLE
🐛[BUG] ProDescriptions valueType="money" 不显示¥和保留两位小数的问题

### ISSUE THREAD

**Issue by wangyongsong** [ant-design/pro-components#2535]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/58172091/115209437-2b2fff00-a130-11eb-8438-91126d48b67e.png)

### 🏞 期望结果

![image](https://user-images.githubusercontent.com/58172091/115209507-400c9280-a130-11eb-9847-d95365ba1236.png)

### 💻 复现代码

```tsx
      <ProDescriptions.Item label="供货价" span={2} valueType="money">
        {info?.supplyPrice / 100}
      </ProDescriptions.Item>
```

### © 版本信息

- ProComponents 版本: 最新版 
- 当前时间：2021年04月19日16:57:15（我看了下35分钟前有过一次更新）
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by wangyongsong** [comment]
有群吗，感觉最近bug有点多，github反馈周期太长了，能手动艾特吗

**Comment by jiyingzhi** [comment]
不想要货币符号可以不用 money 这个 valueType，digit 应该有同样的效果吧

**Comment by wangyongsong** [comment]
> 不想要货币符号可以不用 money 这个 valueType，digit 应该有同样的效果吧

你理解反了，我期望的结果是货币符号，我反馈的是bug

**Comment by jiyingzhi** [comment]
最新版的确实有问题
![image](https://user-images.githubusercontent.com/21698836/115218687-65ea6500-a139-11eb-9b9a-0bfa82d62aa9.png)

**Comment by chenshuai2144** [comment]
```
   fieldProps: {
           moneySymbol:"$",
 },
```
先这样处理一下

**Comment by wangyongsong** [comment]
没事，这个不是很急，方便的话能看下 [#8358](https://github.com/ant-design/ant-design-pro/issues/8358) 这个问题吗

**Comment by chenshuai2144** [comment]
这个问题有很多 issue 了，去搜一下吧
