### ISSUE TITLE
🐛[BUG] ProTable  ref.current  TS2532: Object is possibly 'undefined'.

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#2538]
### 🐛 bug 描述

````TS2532: Object is possibly 'undefined'.````

![QQ浏览器截图20210419183028](https://user-images.githubusercontent.com/3166799/115222538-6ab11800-a13d-11eb-8617-3e007e1dbc5f.png)

**Comment by chenshuai2144** [comment]
`ref.current?.reload()`

**Comment by hihuangwei** [comment]
> `ref.current?.reload()`

````TS2339: Property 'reload' does not exist on type 'never'.````

依然报错 @chenshuai2144 
![QQ浏览器截图20210419190220](https://user-images.githubusercontent.com/3166799/115226598-017fd380-a142-11eb-8562-8a73c0b7d257.png)

**Comment by chenshuai2144** [comment]
我只是给了你个示例，
这个 ts 错误的意思你调用了一个可能为空的方法 ?. 是可以短路调用的。

第二次的错误是类型写的不对，你要配置泛型

```
import type { ProColumns, ActionType } from '@ant-design/pro-table';
const actionRef = useRef<ActionType>()
```
