### ISSUE TITLE
👑 [需求]搜索表单 是否能快捷的默认隐藏所有项 手动指定显示项

### ISSUE THREAD

**Issue by Lnncoco** [ant-design/pro-components#254]
### 🥰 需求描述
可能是应用场景不一样，使用到的搜索字段很少，一般一个表格就两三项，总共有十几个字段，目前文档里好像没看到，每次只能一个个手动添加`hideInSearch: true`很繁琐，如果能有更方便的方式就好了。

**Comment by chenshuai2144** [comment]
应该不会支持的，无论全部显示和全部不显示都满足不了某些用户，全部显示的用户会比较多一些，所以我们选择了全部显示

**Comment by zim-lee** [comment]
能否考虑接受一个数组，如果数组给定了具体值就显示相应字段的搜索表单，否则显示全部字段的搜索表单
