### ISSUE TITLE
🧐[问题]一个组件同时提供选择和输入功能，可能吗？

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#2542]
使用场景是这样
数据可能是 A,B, C,D 之一
也可能是用户的任意输入，事先不知。

所以想提供选择，同时提供输入。输入或查询，二选一。

提供两个组件界面有点乱
能不能用一个组件同时提供选择和输入功能？

**Comment by jiyingzhi** [comment]
你需要 [AutoComplete](https://ant-design.gitee.io/components/auto-complete-cn/)

**Comment by gaohongwei** [comment]
好像跟AutoComplete有点不一样，AutoComplete是先输入，再查询。我是希望输入或查询。

**Comment by chenshuai2144** [comment]
那什么时候选择，什么时候查询呢？

**Comment by gaohongwei** [comment]
> 那什么时候选择，什么时候查询呢？

一般是选择中没有用户想要的值时，再输入。

**Comment by chenshuai2144** [comment]
如果你自己都没办法详细的描述需求，那么 代码一般也是实现不了的

**Comment by gaohongwei** [comment]
> 如果你自己都没办法详细的描述需求，那么 代码一般也是实现不了的

需求是这样，当选择项只有ABCD，而用户要F时，他必须要输入。

**Comment by chenshuai2144** [comment]
试试antd的select 的tag 模式

**Comment by gaohongwei** [comment]
> 试试antd的select 的tag 模式

试了select 的tag 模式，是可以。select 的tag 模式似乎是多选模型，它能否支持单一选择和输入？如果不支持单选，有什么建议？

**Comment by chenshuai2144** [comment]
你可以用受控的模式让 tag 只支持单选，

`onchange=(value)=> setValue([value.pop()])`
