### ISSUE TITLE
👑 [需求] ProFormTextArea 不提供ref属性吗

### ISSUE THREAD

**Issue by 569202812** [ant-design/pro-components#2544]
### 🥰 需求描述
ProFormTextArea 提供ref属性用于触发聚焦等方法

**Comment by chenshuai2144** [comment]
filedProps 用这个api

**Comment by 569202812** [comment]
> `filedProps `用这个api

使用了这个api里面也没有暴露的只有个```itemRef```

**Comment by chenshuai2144** [comment]
那就id来一把把。好像是套的太深ref 拿不出来

**Comment by 569202812** [comment]
> 那就id来一把把。好像是套的太深ref 拿不出来

搜的系内
