### ISSUE TITLE
🐛[BUG]Pro-table2.5.15中的两个问题

### ISSUE THREAD

**Issue by eaglewa** [ant-design/pro-components#255]
🐛 bug 描述
2.5.15版本

1. 点击全屏按钮无效

2. Pro-table设置为表单模式时，rule的检查规则无效

**Comment by chenshuai2144** [comment]
> 点击全屏按钮无效

bug， 刚刚修了

> Pro-table设置为表单模式时，rule的检查规则无效

是个 feature

**Comment by doingdone** [comment]
> > 点击全屏按钮无效
> 
> bug， 刚刚修了
> 
> > Pro-table设置为表单模式时，rule的检查规则无效
> 
> 是个 feature

这个rule 的 feature，什么时候会更新

**Comment by eaglewa** [comment]
2.5.10版本以及之前的版本都是支持都，应该是迁移了pro-form后没有支持了

**Comment by chenshuai2144** [comment]
> 这个rule 的 feature，什么时候会更新

feature 就是 查询表单不支持 rule，具体看设计师的决策

**Comment by eaglewa** [comment]
> > 这个rule 的 feature，什么时候会更新
> 
> feature 就是 查询表单不支持 rule，具体看设计师的决策

我提的bug并不是【table】上的查询表单不支持rule，而是【新增】的这种也不支持rule，2.5.10版本是支持的
![image](https://user-images.githubusercontent.com/1741081/90766346-f3ad5080-e31d-11ea-8b06-88cb4b4737b9.png)

**Comment by doingdone** [comment]
> > > 这个rule 的 feature，什么时候会更新
> > 
> > 
> > feature 就是 查询表单不支持 rule，具体看设计师的决策
> 
> 我提的bug并不是【table】上的查询表单不支持rule，而是【新增】的这种提交表单不支持rule，2.5.10版本是支持的
> ![image](https://user-images.githubusercontent.com/1741081/90766500-353dfb80-e31e-11ea-83d9-76f99d33091e.png)

2.5.10可以吗？我想用这个功能。表单不复杂，不想自己写Form了。
