### ISSUE TITLE
我的数据是通过websocket被动接收的。如何每次拿到数据响应到Protable界面上，不能用ref.current.reload();感觉交互是通过主动拉取的

### ISSUE THREAD

**Issue by Jaasdsa** [ant-design/pro-components#2550]

**Comment by chenshuai2144** [comment]
直接用 dataSource 好了，这种情况不应该用 request 的

**Comment by Jaasdsa** [comment]
非常感谢得您得及时回复，我昨晚用又声明了一个用row.key做得state。每次消息到来维护这个state。下方是动态数据绑定关系解决了
` colums = [{
      title: '当前值',
      dataIndex: 'value',
      render: (_, row, index, action) => <>{this.state.sensorValueCache[row.key].value}</>,
    }]`
