### ISSUE TITLE
🐛[BUG] Modal/Drawer浮层表单，为ProFormSelect时，required提示应为请选择XXX

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#2552]
### 🐛 bug 描述
Modal/Drawer浮层表单，为ProFormSelect时，required提示应为请选择XXX
![QQ浏览器截图20210420213740](https://user-images.githubusercontent.com/3166799/115405976-50506a80-a221-11eb-9155-25fa27935e00.png)

**Comment by chenshuai2144** [comment]
是你自己的输入的，form 没有做相关的设置

**Comment by hihuangwei** [comment]
@chenshuai2144 我并没有自定义 message ，仅仅是required:true 在多语言下都是请输入的意思

**Comment by jiyingzhi** [comment]
这个是通过 [validateMessages](https://ant-design.gitee.io/components/form-cn/#validateMessages) 设置的
