### ISSUE TITLE
🧐[问题]ProCard 封装后gutter不生效

### ISSUE THREAD

**Issue by lin-mt** [ant-design/pro-components#2553]
### 🧐 问题描述

将 ProCard 封装成一个组件后，结合卡片组进行展示，gutter 不生效 ProjectCard 连在一起了

### 💻 示例代码

```typescrip

<ProCard gutter={24}>
   <ProjectCard></ProjectCard>
   <ProjectCard></ProjectCard>
</ProCard>
```
```typescrip
type ProjectCardProps = {
  editable?: boolean;
  cardSize?: 'default' | 'small';
};

const ProjectCard: React.FC<ProjectCardProps> = (props) => {
return (
  <ProCard>
    ...other
  </ProCard>
  )
}
```

![image](https://user-images.githubusercontent.com/58337359/115480949-21b4ad00-a27e-11eb-83ca-74029933840a.png)

### 🚑 其他信息
macOS 11.2.3
chrome 89.0.4389.128（正式版本） (x86_64)
"@ant-design/pro-card": "^1.11.7",

**Comment by chenshuai2144** [comment]
procard 是通过 children 来设置样式的，你包了一下就失效了。

应该支持一下

**Comment by rdmclin2** [comment]
ProCard 目前通过一种非常简单的方式即类型中有没有 `isProCard` 来确定嵌套的是 ProCard。暂时你可以通过设置这个 statistic 变量来让 ProCard 认得你：
![image](https://user-images.githubusercontent.com/4705237/115649489-fef7c680-a359-11eb-985c-929425cc9774.png)

我们再考虑一种更合适的方式。

**Comment by chenshuai2144** [comment]
最好的办法是不封装procard ，只封装 children

**Comment by xiaojun1994** [comment]
根据楼上所说，我最终这么解决
```js
const MyProCard = (props) => <ProCard {...props} />
export default Object.assign(MyProCard, ProCard);
```
