### ISSUE TITLE
🐛[BUG] 切换分页，request方法获取到的sort参数为undefined

### ISSUE THREAD

**Issue by zrr2000620** [ant-design/pro-components#2554]
### 🐛 bug 描述
初次请求sort参数有值，切换分页之后sort为undefined

### 🏞 期望结果
sort参数应该不为undefined

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/46221926/115487701-cdb0c500-a28b-11eb-8fac-1f009de91b05.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，根据你的描述，看起来是在分页切换时未传入正确的sort参数导致其undefined。你可以检查一下你的代码，如果是使用Ant Design Pro中的ProTable组件，可以在请求列表数据的地方，在参数中添加sort参数，以确保每次请求都传入正确的sort参数。

以下是示例代码：

```js
import { request } from 'umi';

const fetchData = async (params) => {
  const { current, pageSize, sort } = params;
  const res = await request('/api/data', {
    method: 'get',
    params: {
      current,
      pageSize,
      sort,
    },
  });
  return res;
};

// 在表格组件中传入fetchData函数，以确保每次请求都传入正确的sort参数
<ProTable
  request={fetchData}
  columns={columns}
  pagination={{
    pageSize: 10,
  }}
/>
```

另外，您可以参考Ant Design Pro中的官方文档：[ProTable](https://pro.ant.design/components/table-cn/)。如果您使用的是其他框架或组件库，可以在其官方文档中寻找相应的使用方法。

希望能帮到您解决问题，如果您还有其他疑问，请随时在github issue中提问。
