### ISSUE TITLE
👑 [需求]带搜索框的select希望选中后可以失去焦点

### ISSUE THREAD

**Issue by BabyFriedCake** [ant-design/pro-components#2555]
### 🥰 需求描述
1.带搜索框的select希望选中后可以失去焦点，目前状态是选中后再次点击下拉框不显示。
![image](https://user-images.githubusercontent.com/33448924/115849665-b0305680-a457-11eb-9f3e-955f7e0848c1.png)

2.搜索"所有"，搜索结果没有超出省略号显示，过长的内容被隐藏，划过没有提示。
![image](https://user-images.githubusercontent.com/33448924/115849606-a0187700-a457-11eb-93c5-6dc26d1c1379.png)

### 🚑 其他信息
代码：https://codesandbox.io/s/holy-water-qxq1j?file=/src/App.tsx

**Comment by DerrickTel** [comment]
```
open: selectOpen,
onBlur: () => onBlur(),
onFocus: () => onFocus(),
```
不知道为什么你要自己控制这个，我试了一下，这个注释了，让他自己选择的话，你的问题1 是解决了的。是有什么场景吗？
问题2我提个PR
