### ISSUE TITLE
🧐[问题]table固定列和rowSelection问题

### ISSUE THREAD

**Issue by thelaurelyy** [ant-design/pro-components#2556]
### 🧐 问题描述

单独使用rowSelection的fixed 属性是有效的，但是当table 中有一列使用fiexd属性时，rowSelection的固定就失效了。在 ant-design 表格中曾经出现这样的问题，在高级表格中需要如何处理呢？

### 🚑 其他信息
ant-design 中查到的issue如下：
https://github.com/ant-design/ant-design/issues/1829

**Comment by chenshuai2144** [comment]
和antd 处理方法是一样的。
不过antd@4已经没有这个问题了
