### ISSUE TITLE
🧐[问题]Proform item 布局，横向和纵向混合排列，以及对齐。

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#2557]
**请问Proform 的多个item能否使用不同的布局？**
比如：
一组Radio Group 的label 和radio横向排列
Input 的label 和 input 纵向排列

**还有，如果横向排列，ProForm 里面的多个Item 的 label 怎么对齐？**
其他的问题中提到这个答案
labelCol={{ span: 6 }}

试了试，还像没管用。
能否提供一段示例代码。

**Comment by chenshuai2144** [comment]
现在是不支持hi混合使用的
