### ISSUE TITLE
🧐[问题]查询表格里嵌套子表，点击展开后有请求数据，第二次点击不再请求子表的请求接口

### ISSUE THREAD

**Issue by flowerDAI** [ant-design/pro-components#2558]
### 🧐 问题描述

一个查询表格，有时间筛选。我先操作筛选时间后，再点开子表的展开，数据正常。我再修改时间查询数据，主表有重新请求接口，子表点击展开不再请求。
我想实现，主表查询后，子表在点击展开时，可以也重新请求数据

### 💻 示例代码

![image](https://user-images.githubusercontent.com/25717606/115503723-791c4280-a2a9-11eb-9a98-bbc6033ea75d.png)

![image](https://user-images.githubusercontent.com/25717606/115503817-9e10b580-a2a9-11eb-83af-957dac0a4ea1.png)

**Comment by chenshuai2144** [comment]
这个要自己控制了，因为两个table 隔离了，最好的办法是 parmas 里面设置个dataTime，这样每次都能刷新
