### ISSUE TITLE
🧐[问题]pro-table 2.5.15，formItemProps里onChange事件不生效，是必须手动renderFormItem吗

### ISSUE THREAD

**Issue by ray1347227** [ant-design/pro-components#256]
### 💻 示例代码
![image](https://user-images.githubusercontent.com/21354564/90714769-fc306780-e2da-11ea-882c-b0ffd70baa99.png)

**Comment by ray1347227** [comment]
{
        title: '业态类型',
        dataIndex: 'format',
        render: (val, row) => row.formatName,
        order: 2,
        valueEnum: formatValueEnum(formats, 'value', 'desc'),
        formItemProps: {
          allowClear: true,
          onChange: () => console.log('onChange'),
        },
}

**Comment by ray1347227** [comment]
`
{
        title: '业态类型',
        dataIndex: 'format',
        render: (val, row) => row.formatName,
        order: 2,
        valueEnum: formatValueEnum(formats, 'value', 'desc'),
        formItemProps: {
          allowClear: true,
          onChange: () => console.log('onChange'),
        },
      }
`

**Comment by chenshuai2144** [comment]
应该是生效的，我透传了下去，我来试试

**Comment by ray1347227** [comment]
> 应该是生效的，我透传了下去，我来试试

咋样小哥，是问题吗

**Comment by chenshuai2144** [comment]
我试了一下是生效的，试着完全更新一下依赖

**Comment by ray1347227** [comment]
> 我试了一下是生效的，试着完全更新一下依赖

我把node_modules和lock文件全删了重装了依赖，还是不行。。。

**Comment by ray1347227** [comment]
antd也是最新的
![image](https://user-images.githubusercontent.com/21354564/90842959-188fdb00-e393-11ea-9071-cce2510cf71f.png)

**Comment by xa2mc** [comment]
formItemProps里onChange事件同样不生效 @chenshuai2144 可以提供下package么

**Comment by mayday7** [comment]
查询表单的 props，会透传给表单项？这个怎么透传啊，自定义的查询组件搜索时候props怎么设置啊
