### ISSUE TITLE
🐛[BUG]new EditableProTable formItem rules poprover indicator fail to handle validator properly

### ISSUE THREAD

**Issue by Fleeting198** [ant-design/pro-components#2560]
### 🐛 bug 描述

使用 EditableProTable 时，通过设置 validator 类型的 的 formItemProps.rules 实现自定义校验，校验失败的浮窗提示没有显示失败原因。
![截屏2021-04-21 18 18 41](https://user-images.githubusercontent.com/11594213/115538261-46d10c00-a2ce-11eb-8143-c1c823b93d52.jpg)

### 📷 复现步骤

```js 

<EditableProTable
  columns={[
    {
      dataIndex: "name",
      title: "name",
      valueType: "text",
      formItemProps: {
        rules: [
          { required: true, message: "empty" },
          {
            validator: async (rule, value) => {
              if (value === "42") {
                return;
              }
              throw new Error("wrong");
            }
          }
        ]
      }
    }
  ]}
/>

```

### 🏞 期望结果

校验结果悬浮窗能显示 validator 返回的错误信息。或者，应该如何编写 validator 以使得浮窗能够正确提示？

### 💻 复现代码

https://codesandbox.io/s/editableprotablevalidatorissue-gn3xt?file=/src/App.js

### © 版本信息

pro-table 2.34.4
antd 4.15.2
react 17.0.2
react-dom 17.0.2

**Comment by Fleeting198** [comment]
回退pro-table到 2.30.x 没有出现这个问题。不过需要鼠标悬停在输入框才会弹出popover
![截屏2021-04-22 09 52 22](https://user-images.githubusercontent.com/11594213/115643913-36617580-a350-11eb-8721-2730b432effc.jpg)

**Comment by chenshuai2144** [comment]
在antd 完成改造前。message 是必须要配置的，

**Comment by tanjunfeng** [comment]
> 在antd 完成改造前。message 是必须要配置的，

请问，validator: async (rule, value) => {
              if (value === "42") {
                return;
              }
              throw new Error("wrong");
            }
这种写法怎么再抛出message来正常显示

**Comment by chenshuai2144** [comment]
直接写个通用的 meessage 吧。
