### ISSUE TITLE
🐛[BUG]ProDescriptions.Item的span不生效

### ISSUE THREAD

**Issue by ghostogre** [ant-design/pro-components#2561]
### 🐛 bug 描述

如题，我无论设置 span 是多少都不会生效，无论是直接在 ProDescriptions.Item 组件上还是在 columns 配置里

**Comment by chenshuai2144** [comment]
试了下是可以的，你可以用 npm  ls 一下是不是有些包被锁住了

![image](https://user-images.githubusercontent.com/8186664/115650040-12576180-a35b-11eb-9727-6c01a87d503e.png)
