### ISSUE TITLE
点击新增报错🐛[BUG]

### ISSUE THREAD

**Issue by paddingC** [ant-design/pro-components#2563]
### 🐛 bug 描述

React does not recognize the `_internalItemRender` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `_internalitemrender` instead. If you accidentally passed it from a parent component, remove it from the DOM element
### 📷 复现步骤

可编辑表格actionRef.current?.addEditRecord?.( )
![image](https://user-images.githubusercontent.com/28521120/115552973-7b00f880-a2df-11eb-9467-4569120a35b7.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
pro 30版本 antd2.9.0
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
升级一下antd 的版本，这个是因为你的antd 还不支持这个 api

**Comment by paddingC** [comment]
> 升级一下antd 的版本，这个是因为你的antd 还不支持这个 api

我升级到最新了还是有这个问题

**Comment by chenshuai2144** [comment]
npm ls 一下看看你的版本

**Comment by paddingC** [comment]
> npm ls 一下看看你的版本

我删除了antd之后重新安的4.15.2版本，proTable是2.30.0版本，还是存在这个问题

**Comment by chenshuai2144** [comment]
你的安装的和启动的不一定是一个版本，你有没有 用 cdn 什么的？

**Comment by paddingC** [comment]
> 你的安装的和启动的不一定是一个版本，你有没有 用 cdn 什么的？

没有，我们全部用的yarn

**Comment by paddingC** [comment]
> 你的安装的和启动的不一定是一个版本，你有没有 用 cdn 什么的？

特意去node_modules里面的包看了一下，是最新版本的antd

**Comment by chenshuai2144** [comment]
https://umijs.org/config#externals

你是不是用了这个

**Comment by paddingC** [comment]
> https://umijs.org/config#externals
> 
> 你是不是用了这个

没有用umi，也没有用这种引入方式。。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design/blob/13a829d20c8a1a83c3bfa1f9d7c30d95659f5b57/components/form/FormItemInput.tsx#L21

代码是在这里引入的，你看看你有没有

**Comment by paddingC** [comment]
> https://github.com/ant-design/ant-design/blob/13a829d20c8a1a83c3bfa1f9d7c30d95659f5b57/components/form/FormItemInput.tsx#L21
> 
> 代码是在这里引入的，你看看你有没有

![image](https://user-images.githubusercontent.com/28521120/115989281-37183700-a5f0-11eb-9b0b-7eceaddeb2b9.png)
有的

**Comment by chenshuai2144** [comment]
那就只可能是用了 umd 了，来个重写的仓库吧
