### ISSUE TITLE
🧐[问题]ProTable的文档好像落后挺多的，找不到ProFieldValueType=switch的文档

### ISSUE THREAD

**Issue by lin-mt** [ant-design/pro-components#2565]
### 🧐 问题描述

找不到 `valueType: 'switch'`  的相关文档，需要自己添加 render 属性吗，这样子的话就有点麻烦了，因为 switch 就两种状态。

### 🚑 其他信息

官方文档：
![image](https://user-images.githubusercontent.com/58337359/115635443-4e2ffe00-a33e-11eb-8dcc-fa4bfe84146d.png)

框架源码：
```typescrip
export declare type ProFieldValueType = 'password' | 'money' | 'textarea' | 'option' | 'date' | 'dateWeek' | 'dateMonth' | 'dateQuarter' | 'dateYear' | 'dateRange' | 'dateTimeRange' | 'dateTime' | 'time' | 'timeRange' | 'text' | 'select' | 'checkbox' | 'rate' | 'radio' | 'radioButton' | 'index' | 'indexBorder' | 'progress' | 'percent' | 'digit' | 'second' | 'avatar' | 'code' | 'switch' | 'fromNow' | 'image' | 'jsonCode' | 'color';
```

**Comment by lin-mt** [comment]
"@ant-design/pro-table": "^2.30.8"

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/schema#valuetype


在这里

**Comment by lin-mt** [comment]
> https://procomponents.ant.design/components/schema#valuetype
> 
> 在这里

这个是不是有点问题
![image](https://user-images.githubusercontent.com/58337359/115647058-c5bd5780-a355-11eb-87eb-e2cd4d5629d4.png)

**Comment by chenshuai2144** [comment]
是的。if 写的不对，新版本修了等发布就可以了

**Comment by lin-mt** [comment]
> 是的。if 写的不对，新版本修了等发布就可以了

顺便问下，这个 switch 支持哪几种类型呢，`'open'、'close'、true、false、1、0`，都可以吗

**Comment by chenshuai2144** [comment]
只有boolean，要用别的可以renderText 转下数据
