### ISSUE TITLE
🐛[BUG] mix模式下, splitMenus:true, 给菜单设置defaultOpenAll为true, sub菜单并没有默认全部展开

### ISSUE THREAD

**Issue by qingwenje2008** [ant-design/pro-components#2569]
### 🐛 bug 描述
mix模式下，splitMenus:true,   menu:{defaultOpenAll:true,autoClose:false}, 并不是每个子菜单都能默认展开
如图：

点击病案审核菜单，其子菜单能全部展开

![c](https://user-images.githubusercontent.com/8563448/115642561-c651f000-a34d-11eb-84f3-75870cd8d1d8.png)

但是，再次点击统计分析菜单，其子菜单不能全部展开
![b](https://user-images.githubusercontent.com/8563448/115642283-42980380-a34d-11eb-8cb8-723ef058760c.png)

### 🏞 期望结果

期望每个菜单都能默认展开

### © 版本信息
-  ant pro5

**Comment by chenshuai2144** [comment]
defaultOpenAll 只会处理首次加载时的菜单。splitMenus:true 模式下每次都会刷一下，所以 defaultOpenAll  失效了。

这种情况比较难处理，你可以受控一下openKeys，或者直接设置 openKeys 为所有菜单项

**Comment by qingwenje2008** [comment]
> defaultOpenAll 只会处理首次加载时的菜单。splitMenus:true 模式下每次都会刷一下，所以 defaultOpenAll 失效了。
> 
> 这种情况比较难处理，你可以受控一下openKeys，或者直接设置 openKeys 为所有菜单项

openKeys 怎么受控，app.tsx下暴露出来的是个layout配置，本来想用 useModel('@@initialState') 缓存呢，但没法调用hooks，而且这个配置应该是首次进入程序的时候才调用，所以想问下这个受控的openKeys应该怎么写 
![e](https://user-images.githubusercontent.com/8563448/116017268-b9950b00-a671-11eb-87f8-41bd4e14d9c7.png)

**Comment by chenshuai2144** [comment]
`openKeys={initialstate.openKeys}`

openKeys 设置为所有 menu 的 key

**Comment by qingwenje2008** [comment]
> `openKeys={initialstate.openKeys}`
> 
> openKeys 设置为所有 menu 的 key

可以这样设置， 目前的问题是怎么让layout配置触发更新？   总结一下有两个问题：
  1， 在onOpenChage方法触发时怎么更新initialstate？
  2，更新了initialstate里的openKeys，layout会触发刷新吗（这个我验证过不太清楚）

本来我想用actionRef试试reload。结果还是hooks只能在组件里调用的问题，没法给actionRef传值。
