### ISSUE TITLE
👑 [需求] Pro-Table 能否主动支持可编辑行

### ISSUE THREAD

**Issue by 4tj** [ant-design/pro-components#257]
### 🥰 需求描述
目前 ProTable 可以通过antd/table的 `component` 的方式支持可编辑行这一功能，Pro-Table能否考虑也封装进去。

### 🧐 解决方案
通过`columns.valueEnum`判断字段类型和组件，通过新增`columns.editable`判断是否可编辑。

**Comment by kaoding** [comment]
通过columns.valueType 判断字段类型和组件，通过新增columns.editable判断是否可编辑。

**Comment by chenshuai2144** [comment]
架构升级告一段落之后就会开始做客编辑表格

**Comment by DieterLi** [comment]
能否临时放开DataSource的控制，antd的Table是直接支持useState数据源编辑显示；但是在Pro-Table里面通过useState数据源，还是useRef对数据源进行即时的引用，通过useEffect更新，都不能触发界面的重新渲染把修改的结果显示出来；但是对应的数据源数据已经改变了。

**Comment by wxf-start** [comment]
希望早点开发出来！

**Comment by Hikarien** [comment]
同希望早点开发出来！

**Comment by chenshuai2144** [comment]
done
