### ISSUE TITLE
🧐[问题]EditableProTable 问题请教

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#2576]
EditableProTable 问题请教

1.  假设其中一列为state, 为select。select的option 能否根据每行的数据确定，实验1的state 的select option为 1，2；实验2的select option为为3，4.
2. 同一行各列间的关系。 假设各行的状态可以从select选择，但是也允许用户输入，选择或输入，二者只能选一个，怎么控制？

![image](https://user-images.githubusercontent.com/5349879/115661114-d5a35000-a2f1-11eb-9fbb-200dd5918b17.png)

**Comment by chenshuai2144** [comment]
可以用 `fieldProps = ()=>{ return { options:[] } }`


  /** 自定义的 fieldProps render */
```
  fieldProps?:
    | ((
        form: FormInstance<any>,
        config: ProSchema<Entity, ExtraProps> & {
          type: ComponentsType;
          isEditable?: boolean;
          rowKey?: string;
          rowIndex: number;
          entity: Entity;
        },
      ) => Record<string, any>)
    | Record<string, any>;
```
