### ISSUE TITLE
👑 【需求】ProTable alert显示逻辑问题

### ISSUE THREAD

**Issue by TernenceWu0702** [ant-design/pro-components#258]
### 🥰 需求描述
ProTable 在设置了rowSelection 以及tableAlertRender的前提条件下，只有在进行勾选行alert信息才会出现，可不可以让在设置完以后，就显示alert信息，而勾选行只是修改其中的内容。

**Comment by chenshuai2144** [comment]
原来是这样的，设计师觉得很突兀

**Comment by zsxing99** [comment]
这里可不可以加一个变量呢？ True就默认显示 False就选中才显示

**Comment by chenshuai2144** [comment]
已经修改优化

**Comment by eJayYoung** [comment]
> 已经修改优化

请问修改成哪个prop可以控制alert的显示隐藏呢？在哪个版本？谢谢

**Comment by chenshuai2144** [comment]
render 结尾的 api 返回一个 false 就能 run

![image](https://user-images.githubusercontent.com/8186664/98790620-f57b4180-243e-11eb-85a1-eecfd13e1322.png)

**Comment by eJayYoung** [comment]
> render 结尾的 api 返回一个 false 就能 run
> 
> ![image](https://user-images.githubusercontent.com/8186664/98790620-f57b4180-243e-11eb-85a1-eecfd13e1322.png)

render返回false只能隐藏alert，但是想让alert直接显示如何控制呢？我这边也是用户说点击勾选后再显示alert的交互有点隐藏了
