### ISSUE TITLE
🐛[BUG] valueType 为 money的时候 表格无法显示货币符号,编辑时为undefined

### ISSUE THREAD

**Issue by ylw1997** [ant-design/pro-components#2580]
### 🐛 bug 描述 

valueType 为 money的时候 表格无法显示货币符号,编辑时为undefined

### 📷 复现步骤

显示的时候:
![image](https://user-images.githubusercontent.com/19940543/115644466-3615aa00-a351-11eb-9a79-5f32b210d11d.png)
编辑的时候:
![image](https://user-images.githubusercontent.com/19940543/115644511-49c11080-a351-11eb-855c-37d3af0c5099.png)

值得一提的是:protable官方示例也为undefined
![image](https://user-images.githubusercontent.com/19940543/115644595-707f4700-a351-11eb-985b-a9f90c2b6d5a.png)

### 🏞 期望结果 

正常显示货币符号

### 💻 复现代码

```javascript
const columns: ProColumns<any>[] = [
    {
      dataIndex: 'productPrice',
      title: '购买价格',
      valueType: 'money',
    },
    {
      dataIndex: 'productDenomination',
      title: '面额',
      valueType: 'money',
    }]
```

### © 版本信息

- Ant Design Pro 版本: 4.15.2
- umi 版本 : 3.4.11
- 浏览器环境 chrome
- 开发环境 windows 10

### 🚑 其他信息 

依赖:
```
"@ant-design/icons": "^4.6.2",
    "@ant-design/pro-form": "^1.21.4",
    "@ant-design/pro-layout": "^6.16.6",
    "@ant-design/pro-table": "^2.34.4",
    "@umijs/preset-react": "1.8.6",
    "antd": "^4.15.2",
    "moment": "^2.29.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "redux-actions": "^2.6.5",
    "secure-ls": "^1.2.6",
    "umi": "^3.4.11"

```

**Comment by chenshuai2144** [comment]
更新一下版本，已经发布了

**Comment by ylw1997** [comment]
好的,感谢

**Comment by ylw1997** [comment]
> 更新一下版本，已经发布了

感谢
