### ISSUE TITLE
🐛[BUG]上传组件不能触发onDownload的API

### ISSUE THREAD

**Issue by shanzhaozhen** [ant-design/pro-components#2585]
### 🐛 bug 描述

上传组件不能触发onDownload的API，使用showDownloadIcon也没有下载按钮

### 📷 复现步骤

使用onDownload不能正常触发方法

### 🏞 期望结果

能正常触发下载方法，打印123

### 💻 复现代码

```
<ProFormUploadDragger
  fieldProps={{
    // listType: 'picture',
    fileList,
    showUploadList: {
      showDownloadIcon: true
    },
    customRequest,
    onDownload,
  }}
/>

const onDownload = async (file: UploadFile) => {
  console.log('123')
};

```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
antd 没有这个api的，你在哪里看到的、

**Comment by shanzhaozhen** [comment]
> antd 没有这个api的，你在哪里看到的、

![Uploading image.png…]()

**Comment by chenshuai2144** [comment]
竟然真的有，我看看

**Comment by chenshuai2144** [comment]
都是直接透传的，你看看你的antd的版本吧
