### ISSUE TITLE
👑 [需求] 希望将 <ProFormColorPicker /> 也作为一个组件

### ISSUE THREAD

**Issue by lin-mt** [ant-design/pro-components#2587]
### 🥰 需求描述

发现 ProTable 支持 color，发现了这个组件，正好也需要，希望可以加点功能，比如 onChange 之类的方法

### 🚑 其他信息

这样就不需要额外引入其他的拾色器组件了

**Comment by lin-mt** [comment]
目前找到了一种方式：

```typescrip
<ProFormColorPicker
  fieldProps={{
    onChange: (va: any) => {
      console.log(va);
    },
  }}
/>
```

**Comment by chenshuai2144** [comment]
就是这样的用法，fieldProps 就是为了给 colorPicker 设置配置

**Comment by xiaohuoni** [comment]
他的意思应该是独立出来，单独安装使用

**Comment by lin-mt** [comment]
> 就是这样的用法，fieldProps 就是为了给 colorPicker 设置配置

initialValue 好像没有生效

```typescrip
<ProFormColorPicker initialValue={'#712732'}/>
```

![image](https://user-images.githubusercontent.com/58337359/115846214-3fd40600-a454-11eb-850f-a4459268d670.png)
