### ISSUE TITLE
🐛[BUG] ProForm 表单项 样式问题

### ISSUE THREAD

**Issue by 569202812** [ant-design/pro-components#2588]
### 🐛 bug 描述

`ProForm` 表单项设置 `className` 和 `style` 不生效，而 `Form.Item` 设置可以

### 💻 复现代码
[复现地址](https://codesandbox.io/s/denglu-forked-f5buv?file=/App.tsx:492-533)

**Comment by chenshuai2144** [comment]
```
formItemProps={{
        style:{ background: "red" }
      }}

```

先这个样绕开一下，有几个属性被覆盖了

**Comment by 569202812** [comment]
> ```
> formItemProps={{
>         style:{ background: "red" }
>       }}
> ```
> 
> 先这个样绕开一下，有几个属性被覆盖了

好的，我看着`ProFormSelect`和`ProFormCheckbox`的ts类型没写

**Comment by chenshuai2144** [comment]
@569202812 可以来个 pr

**Comment by 569202812** [comment]
> @569202812 可以来个 pr

已经提交了
