### ISSUE TITLE
👑 [需求] 这位设计师的想法，怎么样？

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-components#259]
https://zhuanlan.zhihu.com/p/188693322

**Comment by chenshuai2144** [comment]
这个就是我们的设计师，ListToolBar  很快会有大更新

**Comment by kaoding** [comment]
我已经在这和干了，呵呵。
![image](https://user-images.githubusercontent.com/18542211/90763174-cc07b980-e318-11ea-9aee-292e660eeafc.png)

**Comment by chenshuai2144** [comment]
@kaoding  是要给我提 pr 的意思吗？

**Comment by kaoding** [comment]
> @kaoding 是要给我提 pr 的意思吗？

能提 PR 的，一定会提上去的。

**Comment by kaoding** [comment]
想法： https://github.com/ant-design/pro-components/issues/4

还有打算提一个，ProTree ，如下：

![image](https://user-images.githubusercontent.com/18542211/90843942-555cd180-e395-11ea-9243-b05778982c39.png)

![image](https://user-images.githubusercontent.com/18542211/90843995-78878100-e395-11ea-8048-ac5a04c006f6.png)

**Comment by chenshuai2144** [comment]
可以做个 demo 出来，或者你有兴趣搞个 protree 吗

**Comment by kaoding** [comment]
> 可以做个 demo 出来，或者你有兴趣搞个 protree 吗

空的话，先弄一个 demo 出来给你们先看一看，要不要做成 ProTree，大家评估一下。

**Comment by quarkcms** [comment]
![image](https://user-images.githubusercontent.com/60868863/91286247-c995db80-e7c0-11ea-99c9-c7c8218e3127.png)
我的布局是这样的，不知道这种方案怎么样

**Comment by quarkcms** [comment]
新的样式，什么时候发布？

**Comment by MaskHao** [comment]
protable 如果也能整合出一个proTreeSelect 那就更强大了

**Comment by chenshuai2144** [comment]
已经实现了

**Comment by leshalv** [comment]
> 已经实现了
在哪里实现的，我想看看去

**Comment by leshalv** [comment]
> > 可以做个 demo 出来，或者你有兴趣搞个 protree 吗
> 
> 空的话，先弄一个 demo 出来给你们先看一看，要不要做成 ProTree，大家评估一下。

大佬，目前有demo吗？

**Comment by kaoding** [comment]
> > 已经实现了
> > 在哪里实现的，我想看看去

已经实现了说的是这个 https://zhuanlan.zhihu.com/p/188693322

**Comment by chenshuai2144** [comment]
就是 protable 的 listtoolbar，有多行模式

**Comment by leshalv** [comment]
protree有计划吗？感觉中后台，比较常用呢

**Comment by kaoding** [comment]
> > > 可以做个 demo 出来，或者你有兴趣搞个 protree 吗
> > 
> > 
> > 空的话，先弄一个 demo 出来给你们先看一看，要不要做成 ProTree，大家评估一下。
> 
> 大佬，目前有demo吗？

这个一直没有空弄，只是在自己的产品和项目中在使用，要弄也要符合pro-components整体设计才行。
