### ISSUE TITLE
ProComponents官网打不开？

### ISSUE THREAD

**Issue by my9988** [ant-design/pro-components#2591]
我是在印度访问，出现如下错误，什么原因呢？
![image](https://user-images.githubusercontent.com/17469220/115868128-955ee180-a459-11eb-90bd-21d514dfb6f5.png)

**Comment by my9988** [comment]
https://gw.alipayobjects.com/os/antfincdn/fdj3WlJd5c/darkreader.js

可能印度阻止了这个网址

**Comment by chenshuai2144** [comment]
这个使用我们的cdn，印度应该封了阿里了吧
