### ISSUE TITLE
🧐[问题] ProTable 轻量筛选如何触发确认按钮

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#2592]
### 🧐 问题描述
ProTable 轻量筛选如何触发确认按钮

![QQ浏览器截图20210423202849](https://user-images.githubusercontent.com/3166799/115878711-6e190c00-a47b-11eb-991f-f06758927c51.png)

**Comment by chenshuai2144** [comment]
`onValuesChange ` 

点击确定会触发一下表单的 onChange 的，你也可以在 fieldProps 上监听 onChange 来解决
