### ISSUE TITLE
🧐[问题]ProFormCaptcha 如何禁用或自定义倒计时？

### ISSUE THREAD

**Issue by BeYoug** [ant-design/pro-components#2594]
### 🧐 问题描述

ProFormCaptcha 如何禁用或自定义倒计时？按钮的disable状态如何修改呢？

**Comment by chenshuai2144** [comment]
| 参数 | 说明 | 类型 | 默认值 |
| --- | --- | --- | --- |
| onGetCaptcha | 点击获取验证码的事件，如果配置了 phoneName 会自动注入 | `(phone)=>Promise<any>` | - |
| captchaProps | 获取验证码按钮的 props，与 antd 的 props 相同 | `ButtonProps` | - |
| countDown | 倒计时的秒数 | number | 60 |
| captchaTextRender | 渲染计时的文案 | `(timing: boolean, count: number) => React.ReactNode` | - |


captchaProps 就是按钮的props，你可以用 antd 的任何配置，包括 disable
