### ISSUE TITLE
🐛[BUG] ProTable从版本2.30.4以后校验失败气泡文本不显示

### ISSUE THREAD

**Issue by xjb258** [ant-design/pro-components#2596]
### 🐛 bug 描述

ProTable进入行编辑状态，当某些字段校验失败时，以前字段边框会红色显示，鼠标移过去会有气泡提示。
从版本2.30.4以后，文本提示内容变成了一个灰色圆点，官方每发布一个版本我都会试一下，一直没修复。**之前只要鼠标移过去就会显示，现在必须点击才会显示。**

如下图：
![1](https://user-images.githubusercontent.com/12584516/115971721-b10ed880-a57c-11eb-8cc5-448ad28f27ff.png)
![2](https://user-images.githubusercontent.com/12584516/115971722-b2400580-a57c-11eb-93ef-9aff42c90fbe.png)

另外：还有两个问题：
1、ProTable 升级到最新本，每次显示前都会先显示“暂无数据”才刷新出正常数据。
2、loading={true} 设置为true时一直在转圈圈。

### 📷 复现步骤

Pro系列组件全部为最新版本，antd为最新的4.15.2，pro-table不升级到最新一切正常，升级完就会出现。

### 💻 复现代码

必现！

### © 版本信息

- ProComponents 版本: 全部最新。
- umi 版本：最新。
- 浏览器环境：edge 最新90版
- 开发环境：win10 最新版

**Comment by chenshuai2144** [comment]
是不是没设置 message/

**Comment by meyerlee** [comment]
> 是不是没设置 message?

rule 必须设置message吗，其实一些常规的验证信息，
希望和antd一样，出默认的信息就可以了。 比如某字段不能为空等。

**Comment by xjb258** [comment]
到今天止的最新版本仍然没有解决，直接新建一个antd pro v5 项目，所有依赖全部最新，仍然有问题，之前是显示一个小圆点，现在是啥都不显示。

**Comment by xjb258** [comment]
{
            //业务名称
            title: lstr('app.settings.service.ServiceName'),
            dataIndex: 'ServiceName',
            ellipsis: false,
            sorter: {
                compare: (a, b) => {
                    return Common.stringSort(a.ServiceName, b.ServiceName);
                }
            },
            showSorterTooltip: false,
            formItemProps: {
                rules: [
                    {
                        required: true,
                        type: 'string',

                        //自定义校验，存在则其它默认校验参数失效
                        validator: async (rule, value, callback) => {
                            value = value ? value : '';

                            //前后不能有空格
                            if (!(new RegExp(/^(?!\s)(?!.*\s$)/)).test(value)) {
                                return Promise.reject(new Error(lstr('component.NoSpaces')));
                            }

                            //业务名称不允许出现特殊字符
                            if ((new RegExp(/[\[\]{}]+/g)).test(value)) {
                                return Promise.reject(new Error(lstr('component.NoSpecialCharacters')));
                            }

                            if (value.length < 1 || value.length > 128)
                                return Promise.reject(new Error('不能为空，长度范围'));

                            return Promise.resolve();
                        },
                    },
                ],
            },
        },

**Comment by chenshuai2144** [comment]
浮动上去也不显示吗？

**Comment by chenshuai2144** [comment]
已经修复了，不得已换了新的方案
