### ISSUE TITLE
🐛[BUG] ProFormSelect多选搜索问题

### ISSUE THREAD

**Issue by xiaojun1314** [ant-design/pro-components#2597]
### 🐛 bug 描述

ProFormSelect多选搜索 集成弹出框进行改造，回写数据存在一些

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/40731269/115976660-c1d24500-a5a2-11eb-9b7c-5b024a88c67b.png)
![image](https://user-images.githubusercontent.com/40731269/115976665-cf87ca80-a5a2-11eb-9edc-0a9f4970af52.png)
![image](https://user-images.githubusercontent.com/40731269/115976674-e2020400-a5a2-11eb-9fdb-0fe7ccd63d03.png)
弹出框回填数据
![image](https://user-images.githubusercontent.com/40731269/115976684-f2b27a00-a5a2-11eb-8410-2bdc55d9b4bb.png)
![image](https://user-images.githubusercontent.com/40731269/115976688-fd6d0f00-a5a2-11eb-8e87-e2ca25a942ed.png)
label 内容没有回显，之前 ProFormSelect单选搜索 也存在该问题由于 @ant-design/pro-form@1.21.2 修复了 单选没问题
![image](https://user-images.githubusercontent.com/40731269/115976696-21305500-a5a3-11eb-821b-8795b832446d.png)
代码日志如下
弹出框回显 代码
![image](https://user-images.githubusercontent.com/40731269/115976706-43c26e00-a5a3-11eb-8966-02cbb2efb63a.png)
多选回显 代码 正常
![image](https://user-images.githubusercontent.com/40731269/115976710-589f0180-a5a3-11eb-89f0-9f9eb85003e3.png)
弹出框回显日志正常
![image](https://user-images.githubusercontent.com/40731269/115976719-72404900-a5a3-11eb-8dc1-a0b8c0ee1aab.png)
回显异常
![image](https://user-images.githubusercontent.com/40731269/115976723-7d937480-a5a3-11eb-972d-611e204ed9c3.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by xiaojun1314** [comment]
![image](https://user-images.githubusercontent.com/40731269/115976743-a0258d80-a5a3-11eb-8e08-fb9d75545c7e.png)
多选也存在 该 BUG 希望查看 谢谢  感恩。。

**Comment by xiaojun1314** [comment]
能否修复一下

**Comment by chenshuai2144** [comment]
来个重现，我没理解问题
