### ISSUE TITLE
🧐[问题]ProFormSelect 可以用ref控制下拉框么？

### ISSUE THREAD

**Issue by BabyFriedCake** [ant-design/pro-components#2598]
### 🧐 问题描述
ProFormSelect 可以用ref控制下拉框么？怎么实现？

**Comment by DerrickTel** [comment]
您好，能说一下场景吗？

**Comment by chenshuai2144** [comment]
可以用 fieldProps 受控的控制

**Comment by BabyFriedCake** [comment]
> 可以用 fieldProps 受控的控制
有报错：对象文字可以只指定已知属性，并且“ref”不在类型“FieldProps & SelectProps<any> & { searchOnFocus?: boolean | undefined; resetAfterSelect?: boolean | undefined; }”中。ts(2322)
![image](https://user-images.githubusercontent.com/33448924/116664941-b7adad80-a9cb-11eb-828d-4a5d3020eea0.png)

**Comment by chenshuai2144** [comment]
ref 是不支持的，你可以用 open 和 onOpenChange 两个联合起来搞
