### ISSUE TITLE
🐛[BUG] pro-table sticky参数开启样式错乱

### ISSUE THREAD

**Issue by ouzhou** [ant-design/pro-components#2600]
在datasource为空的状态下，开启sticky, 样式有问题， 第一格占据了100%宽度，其他的被挤出去了

复现仓库
https://codesandbox.io/s/qingliangshaixuantihuanchaxunbiaodan-forked-vbp1k?file=/App.tsx

**Comment by ouzhou** [comment]
@chenshuai2144 样式的问题
如果数据源为空，并设置了sticky就会这样

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/116491508-9ade8080-a8cc-11eb-8fb0-2870618c7643.png)

**Comment by ouzhou** [comment]
@chenshuai2144 这个图片的table栏明显高度不对，而且本身有4个Column但是这里只展示出了2行
