### ISSUE TITLE
🐛[BUG]可编辑表单，气泡提示的时候，会重叠，还有的就是滚动的时候，气泡没有跟着滚动。可以在输入框下方显示错误提示吗？

### ISSUE THREAD

**Issue by mtrucc** [ant-design/pro-components#2602]
### 🐛 bug 描述
可以自定义提示方式吗？
![image](https://user-images.githubusercontent.com/16724665/115987089-2d89d180-a5e6-11eb-8096-242bcd2a727a.png)
我还是比较期望能够在输入框下方显示错误信息

### 📷 复现步骤
https://codesandbox.io/s/shishibaocundebianjibiaoge-forked-8pz5f

第一个输入框没有值 第二个输入框值不合法的时候 会弹出两个气泡
页面滚动的时候，气泡没有跟着滚动（暂时无法复现，可以在我自己的工程中复现）
### 🏞 期望结果

在输入框下方显示错误提示，或者自定义错误提示组件
### 💻 复现代码

https://codesandbox.io/s/shishibaocundebianjibiaoge-forked-8pz5f
### © 版本信息
    "@ant-design/pro-card": "^1.11.11",
    "@ant-design/pro-descriptions": "^1.7.5",
    "@ant-design/pro-form": "^1.21.5",
    "@ant-design/pro-layout": "^6.17.0",
    "@ant-design/pro-list": "^1.7.0",
    "@ant-design/pro-skeleton": "^1.0.1",
    "@ant-design/pro-table": "^2.34.5",

**Comment by chenshuai2144** [comment]
> 可以在我自己的工程中复现

这个估计是因为你的进度条不在 dom 上面，所以浮动定位乱了

> 在输入框下方显示错误提示

下面会把整个表格弄乱的，最好不要这么搞，你可以用 configProvide 把 dom 渲染地址放到你出滚动条的地方

**Comment by mtrucc** [comment]
> 这个估计是因为你的进度条不在 dom 上面，所以浮动定位乱了

的确，我检查了一下dom，气泡框跑到了body下。

那这个怎么修复呢？

> 你可以用 configProvide 把 dom 渲染地址放到你出滚动条的地方

没有头绪

**Comment by chenshuai2144** [comment]
https://ant.design/components/config-provider-cn/


getPopupContainer | 弹出框（Select, Tooltip, Menu 等等）渲染父节点，默认渲染到 body 上。 | function(triggerNode) | () => document.body |  
-- | -- | -- | -- | --
getTargetContainer | 配置 Affix、Anchor 滚动监听容器。 | () => HTMLElement | () => window | 4.2.0

**Comment by mtrucc** [comment]
> https://ant.design/components/config-provider-cn/
> 
> getPopupContainer	弹出框（Select, Tooltip, Menu 等等）渲染父节点，默认渲染到 body 上。	function(triggerNode)	() => document.body	 
> getTargetContainer	配置 Affix、Anchor 滚动监听容器。	() => HTMLElement	() => window	4.2.0

```
    <ConfigProvider
      locale={locale}
      getPopupContainer={() => document.getElementById('right-layout')}>
      <Provider store={store}>
        <AppRouter />
      </Provider>
    </ConfigProvider>
```
我这么写了，也在组件上这么写了，还是没有效果，是不是应该在你那边的气泡组件上加上
`getPopupContainer={triggerNode => triggerNode.parentNode}`
这段代码才可以生效？

**Comment by chenshuai2144** [comment]
getPopupContainer 应该是你现在滚动条的出现的 dom 的问题，或者直接用 ref 搞个 div，不是 parentNode

**Comment by mtrucc** [comment]
感谢，应该是我这边的问题，但是这个参数好像不好使，我先自己排查一下。

**Comment by LittleChives** [comment]
@mtrucc 请问你后来怎么解决了呢，我现在也是getPopupContainer不生效，在里面包裹ConfigProviderWraper也不行
