### ISSUE TITLE
🐛[BUG]可编辑表格数据量过大，卡顿

### ISSUE THREAD

**Issue by jaw52** [ant-design/pro-components#2603]
### 🐛 bug 描述

根据官网提供的 实时保存的编辑表格 的例子运用到实践中发现，数据量如果过大，输入的时候会很卡顿
![image](https://user-images.githubusercontent.com/53564781/115987500-e6044500-a5e7-11eb-9ff1-99a91f101f09.png)

### 🏞 期望结果

能够变流畅

### © 版本信息

- ProComponents 版本:pro-table 最新版

**Comment by chenshuai2144** [comment]
这个是的，因为每次输入都会触发 onchange ，然后渲染整个表格，可以做个优化，只重新渲染这一样

**Comment by jaw52** [comment]
> 这个是的，因为每次输入都会触发 onchange ，然后渲染整个表格，可以做个优化，只重新渲染这一样

请问一下，之后版本更新会带上这个实时保存中数据量大的优化吗

**Comment by chenshuai2144** [comment]
应该会一起解决掉，因为 实时保存 的问题也是重复渲染导致的

**Comment by liangxp** [comment]
我还以为是我自己的问题，搞半天，卡死个人，isSure解惑了

**Comment by jaw52** [comment]
> 我还以为是我自己的问题，搞半天，卡死个人，isSure解惑了

这个着实影响使用了。能早点修复就好了

**Comment by jaw52** [comment]
数据量大还是卡

**Comment by jaw52** [comment]
> 应该会一起解决掉，因为 实时保存 的问题也是重复渲染导致的

现在数据量大，还是卡

**Comment by chenshuai2144** [comment]
只能优化部分，最好的办法还是虚拟滚动，1000 个格子，每个 dom 光 diff 就要 1s。

**Comment by NemoZhong** [comment]
一次加载150条数据，每行数据有30个字段左右，rowSelection选中数据有500ms左右的延时，体验不太好，因为要使用protable的列设置，按antd的table的虚拟列表配置，结果发现不支持。请问有没有什么好的解决选中卡顿的办法

**Comment by NemoZhong** [comment]
> 一次加载150条数据，每行数据有30个字段左右，rowSelection选中数据有500ms左右的延时，体验不太好，因为要使用protable的列设置，按antd的table的虚拟列表配置，结果发现不支持。请问有没有什么好的解决选中卡顿的办法

数据量少的时候(<20条) ，选中效果正常

**Comment by relines** [comment]
马上2023年了，还是卡
