### ISSUE TITLE
useRef与hooks的冲突

### ISSUE THREAD

**Issue by s-t-a-r-0** [ant-design/pro-components#2604]
在应用proTable时引入useRef，结果在提交时eslint检测报错error  React Hook "useRef" is called in function "actionTable: ConnectRC<PageProps>" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter  react-hooks/rules-of-hooks (​ https://reactjs.org/docs/hooks-rules.html#eslint-plugin ​)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/115987770-0385de80-a5e9-11eb-8824-1df74efde149.png)


大小写问题
