### ISSUE TITLE
如何取消或者定制PageLoading 页面？？？🧐[问题]

### ISSUE THREAD

**Issue by g00152362** [ant-design/pro-components#2607]

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/title-landing-cn

看这里

**Comment by g00152362** [comment]
谢谢
















在 2021-04-27 08:58:10，"陈帅" ***@***.***> 写道：

https://beta-pro.ant.design/docs/title-landing-cn

看这里
