### ISSUE TITLE
🐛[BUG] toolBarRender里的selectedRowKeys, selectRows总是显示上一次的状态

### ISSUE THREAD

**Issue by yaoguoba** [ant-design/pro-components#261]
### 🐛 bug 描述

第一次选中一行时：
selectedRowKeys: undefined
selectRows: []

第二次选中一行时：
selectedRowKeys: 第一次选中的那个key
selectRows: [ 第一次选中的record ]

感觉像是使用了useState去变更这两个值，但是在方法中使用setState之后这个值实际还没变化。
这时触发toolBarRender时，这两个值还是上一次的状态。

### © 版本信息

- ProTable版本: 2.5.15
- umi 版本: 3.2.16
- 浏览器环境 edge

**Comment by zim-lee** [comment]
我也遇到了这个问题，不同的是`selectedRowKeys`正常，`selectRows`显示上一次的状态

**Comment by liangxp** [comment]
同样的问题，我不知道怎么突然就这样了，一脸懵逼

**Comment by zim-lee** [comment]
@chenshuai2144 大佬，2.6.0的包是不是没发布这个issue的修复
