### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by fybchristasker** [ant-design/pro-components#2612]
### 🐛 bug 描述

- [ ] 

- [ ] 
<img width="547" alt="截屏2021-04-26 下午4 08 28" src="https://user-images.githubusercontent.com/46596982/116050424-05fc3d00-a6aa-11eb-9323-f8e81fcd3e90.png">

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]
@ant-design/pro-card: "1.11.0",
umi: "^3.4.0",
chrome浏览器
macOS

**Comment by chenshuai2144** [comment]
看起来是 antd 的版本有问题。指标卡需要 antd@4

**Comment by fybchristasker** [comment]
@chenshuai2144 我用的antd版本是4.15.2，应该够的，现在就是从引入了指标卡的页面跳转到使用了ProCard的页面就会报错，我把ProCard用花括号引入就没有报错了，不知道有没有系统方案
