### ISSUE TITLE
🧐[问题] ProFormSelect 使用 request 加载 options，但是加载的 options会更新，该如何重新请求？

### ISSUE THREAD

**Issue by 7ynstar** [ant-design/pro-components#2614]
### 🧐 问题描述

如题，`ProFormSelect` 使用 `request` 加载的 `options` 会更新，如果重新请求数据以更新 options ？

**Comment by chenshuai2144** [comment]
可以用 actionRef 和 修改 params ，看看下面的章节，应该能解决你的问题

https://procomponents.ant.design/components/schema#%E8%BF%9C%E7%A8%8B%E6%95%B0%E6%8D%AE
