### ISSUE TITLE
🧐[问题]想知道EditableProTable变化的列名

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#2616]
### 🧐 问题描述

1。 怎么知道是哪一列的数据变化？ 因为需要根据列名增加一些检测和运算。
2。 怎么定义一行数据列的关联性。 例如，column2 = column1 + 1， 当column1 变化是，自动设置column2

感谢大侠们回答问题。
有的问题对大侠们可能很简单，我们还是会磨一阵阵。
如果能有点代码或链接，就太好了。

### 💻 示例代码
```   
 const onRowChange = (record) => {
    console.log("onRowChange", record);
  };
  return (
    <>
      <EditableProTable<DataSourceType>
        headerTitle="填充数据"
        columns={columns}
        rowKey="column_name"
        value={dataSource}
        onChange={setDataSource}
        recordCreatorProps={false}
        editable={{
          type: "multiple",
          editableKeys,
          onValuesChange: onValuesChange,
        }}
      />
      <Divider />
    </>
  );

```

**Comment by gaohongwei** [comment]
- [ ] 

- [ ] `  const onRowChange = (record) => {
    console.log("onRowChange", record);
  };
  return (
    <>
      <EditableProTable<DataSourceType>
        headerTitle="填充数据"
        columns={columns}
        rowKey="column_name"
        value={dataSource}
        onChange={setDataSource}
        recordCreatorProps={false}
        editable={{
          type: "multiple",
          editableKeys,
          onValuesChange: onValuesChange,
        }}
      />
      <Divider />
    </>
  );`

**Comment by chenshuai2144** [comment]
第一个参数是当前编辑的数据，第二个是总的数据

**Comment by gaohongwei** [comment]
const onValuesChange = (record, recordList) => {
    console.log("record", record);
    console.log("recordList", recordList);
    setDataSource(recordList);
  };
record是当前编辑的数据，recordList是总的数据
这个是的
但是都得变化后的数据
我的问题是，怎么知道哪个列发生了变化？

**Comment by chenshuai2144** [comment]
record 里面有你的rowkey的

**Comment by gaohongwei** [comment]
@chenshuai2144 我还是没明白。
以文档的例子为例，
rowKey="id"
onValuesChange 抓到的record新值为
  {
    id: 624691229,
    title: '活动名称abc',
    decs: '这个活动真好玩abc',
    state: 'closed',
    created_at: '2020-05-26T08:19:22Z',
  },

我怎么知道是title 变化了，还是decs 变化了？

**Comment by chenshuai2144** [comment]
这个我也不知道的，每次改变我都是全量获取数据
