### ISSUE TITLE
🧐[问题] BetaSchemaForm 是一个测试版本吗？ 什么时候会发正式版

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#2618]
### 🧐 问题描述

BetaSchemaForm 是一个测试版本吗？ 什么时候会发正式版。

看完 BetaSchemaForm，感觉以前写的代码又要重构了。 

BetaSchemaForm，让可定制化界面成为一个可选项，如果这样的的话，今后很多界面都可以根据后台定义来实现了。

**Comment by chenshuai2144** [comment]
暂时不会，但是可能有大的 api 修改，比如重新实现定义
