### ISSUE TITLE
🐛[BUG] @ant-design/pro-form@1.0.0-beta.17 的表单项只填写 rules 的 required 会造成 请输入undefined 的提示

### ISSUE THREAD

**Issue by huang6349** [ant-design/pro-components#262]
### 🐛 bug 描述

@ant-design/pro-form@1.0.0-beta.17 的表单项只填写 rules 的 required 会造成 请输入undefined 的提示

### 📷 复现步骤

```js
<ProFormText
  label="姓名"
  name="name"
  placeholder="请输入姓名"
  rules={[{ required: !0 }]}
/>
```

必填提示会显示为： 请输入undefined

### 🏞 期望结果

必填提示会显示为：请输入姓名

### 💻 复现代码

无

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] @ant-design/pro-form@1.0.0-beta.17
- umi 版本 3.1.4
- 浏览器环境 chrome 84
- 开发环境 [e.g. mac OS] win10

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
终于有 from 的 issue 了。让人欣慰

**Comment by huang6349** [comment]
应该是 pro-form 还在 beta 阶段，用的人不太多吧

**Comment by meyerlee** [comment]
这个的原因应该是现在的label不是纯字符串， antd的的报错信息取lable就出问题了。
我也遇到了，好像也没有很好的办法解决
可能需要antd增加title字段？ 在错误信息里使用  title ?? lable来取字段的显示名

**Comment by huang6349** [comment]
在纯 ANTD 的 form 里，这样子写是可以的，我觉得不是 lable 的值未能获取的原因

**Comment by chenshuai2144** [comment]
lable  我们包了一下导致的，label 必定是个 dom结构，我们想个办法

**Comment by chenshuai2144** [comment]
解决了

**Comment by huang6349** [comment]
大佬威武
