### ISSUE TITLE
👑 [需求] valueType: 'digit' 支持传入国际化参数

### ISSUE THREAD

**Issue by jiyingzhi** [ant-design/pro-components#2620]
### 🥰 需求描述

比如需要 123万、13亿这种格式，就需要传入特定的参数：

```js
new Intl.NumberFormat('zh-CN', {
  notation: 'compact',
})
```

**Comment by chenshuai2144** [comment]
是有fieldProps的，你可以来个pr

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您的回复。根据您的回复，我需要提交一个 PR 来解决这个问题，并且提供必要的文档、测试用例等。

我了解到这个问题是关于 `valueType: 'digit'` 支持传入 `Intl.NumberFormat` 的国际化参数，以便支持 `notation: 'compact'` 的格式。因此，我可以针对这个问题提供以下解决方案：

#### 方案

在 `antd/lib/input-number.d.ts` 文件中，添加以下属性定义：

```typescript
export interface InputNumberProps extends AbstractInputNumberProps {
  //...
  fieldProps?: {
    [name: string]: unknown;
  };
}
```

在 `antd/lib/input-number/InputNumber.tsx` 文件中，针对 `fieldProps` 定义的参数，通过 `React.useMemo` 将需要传入 `Intl.NumberFormat` 的参数进行处理，然后在 `formatNumberString` 方法中直接使用即可。

示例代码：

```typescript
const formatNumberString = (num: string) => {
  if (!num) return '';
  if (
    // Make sure it only matches the first +
    '+'.indexOf(num) === 0 &&
    '+'.indexOf(num) !== -1
  ) {
    return num;
  }
  const {
    fieldProps: { locale, compactDisplay = 'short' },
  } = props;

  return new Intl.NumberFormat(locale, {
    notation: 'compact',
    compactDisplay,
  }).format(Number(num) || 0);
};

const [inputValue, setInputValue] = React.useState(formatNumberString(val));

React.useEffect(() => {
  setInputValue(formatNumberString(val));
}, [val]);
```

这样，当 `fieldProps` 传入以下参数时，`valueType: 'digit'` 就可支持传入 `Intl.NumberFormat` 参数：

```json
{
  "fieldProps": {
    "locale": "zh-CN",
    "compactedDisplay": "short"
  }
}
```

这个 PR 可以自动触发 CI 测试，测试用例需要考虑 `valueType: 'digit'` 时传入 `compactedDisplay` 参数。同时需要在文档中说明这个新加的属性和传参规则等。

请让我知道您的意见，谢谢。
