### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by lovesL** [ant-design/pro-components#2622]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/27960630/116195993-82a02180-a765-11eb-9170-b8a2f7bf02d4.png)
![image](https://user-images.githubusercontent.com/27960630/116196029-8df34d00-a765-11eb-894f-fa43f84434d4.png)
这个收起的时候是怎么知道该隐藏后面哪个几个input 然后 。 我看你们是用的antd 的栅格，我没想出是怎么实现的 如果有时间的 给个思路就行了

**Comment by chenshuai2144** [comment]
算出来，代码看这里，map的时候 计算index，index>2 的就不展示

https://github.com/ant-design/pro-components/blob/master/packages/form/src/layouts/QueryFilter/index.tsx

**Comment by lovesL** [comment]
老哥。。。牛批
