### ISSUE TITLE
🧐[问题]  ProList 设置expandable的expandedRowRender返回的组件无法在行的下方显示

### ISSUE THREAD

**Issue by osCaiwei** [ant-design/pro-components#2623]
### 🧐 问题描述

设置了expandable的expandedRowRender 返回一个p标签 返回的内容与行的内容并排显示

### 💻 示例代码

expandable={{
              expandRowByClick: true,
              columnWidth: 200,
              expandedRowRender: (record) => {
                return (
                    <p>12312333321312312</p>
                );
              },
            }}

<img width="401" alt="截屏2021-04-27 16 54 41" src="https://user-images.githubusercontent.com/53340705/116214567-68703e80-a779-11eb-8353-fb647e613f64.png">

**Comment by chenshuai2144** [comment]
看看你的依赖或者样式是不是被重写了。

这种问一般都是被覆盖了导致的
