### ISSUE TITLE
🧐[官网又进不去了]

### ISSUE THREAD

**Issue by xykjlcx** [ant-design/pro-components#2627]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/32430701/116330476-37871c80-a800-11eb-988f-b925ca708aea.png)

**Comment by chenshuai2144** [comment]
看了下没什么问题，你打开你的network看看是有什么东西不对

**Comment by xykjlcx** [comment]
> 看了下没什么问题，你打开你的network看看是有什么东西不对

![image](https://user-images.githubusercontent.com/32430701/116330728-b8deaf00-a800-11eb-9b39-298a5511e293.png)

**Comment by xykjlcx** [comment]
> 看了下没什么问题，你打开你的network看看是有什么东西不对

sorry,关闭cache后好了；是我的问题
