### ISSUE TITLE
Pro Table和Modal一起用的时候有冲突🐛[BUG]

### ISSUE THREAD

**Issue by DreamParadise** [ant-design/pro-components#263]
### 🐛 bug 描述
当设置了固定列到左侧或者右侧时，再点击按钮显示Modal会导致固定列显示位置错误。

具体见下面的GIF

### © 版本信息

- Ant Design Pro Table 版本: 2.5.15
- Ant Design 版本: 4.5.2
- 浏览器环境: Chromium 80.0.3987.163
- 开发环境: Windows 10

### 🚑 其他信息
图片是直接上传到Github的，要翻墙才能看到……
![iii](https://user-images.githubusercontent.com/3191003/90757949-d8881400-e310-11ea-8e4a-3c3de1cf7655.gif)

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它

——


We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
