### ISSUE TITLE
table在可编辑状态下怎么自定义删除操作的按钮#2630🧐[问题]

### ISSUE THREAD

**Issue by youngList** [ant-design/pro-components#2631]
### 🧐 问题描述
#2630 第一次提issue，见谅

**Comment by chenshuai2144** [comment]
actionRender | 自定义编辑模式的操作栏 | (row: T, config: ActionRenderConfig<T>) => ReactNode[] | -
-- | -- | -- | --


这个api

**Comment by youngList** [comment]
> actionRender	自定义编辑模式的操作栏	(row: T, config: ActionRenderConfig) => ReactNode[]	-
> 这个api

您好，感谢大佬回复。
我这块还有点疑问，我理解actionRender这个api提供了保存，删除 和   取消三个快捷功能(或者有其他妙用我没发现)，我想要自定义一个其他的操作，我在代码示例中
Duplicate of #2630 贴了代码片段，我在render里边实现，但是在编辑的时候我自定义的按钮不生效

**Comment by youngList** [comment]
> actionRender	自定义编辑模式的操作栏	(row: T, config: ActionRenderConfig) => ReactNode[]	-
> 这个api

感谢大佬提示。
我这里还有个疑问，就是我自定义的删除必须通过直接设置dataSource来实现吗？有没有什么其他的替代方式？

**Comment by chenshuai2144** [comment]
config 里面有删除的方法，你看看

**Comment by youngList** [comment]
> config 里面有删除的方法，你看看

看了下config，里边的onDelete方法是删除的回调函数，删除方法没有找到。。。

**Comment by chenshuai2144** [comment]
`(row: T, config: ActionRenderConfig<T>,defaultDom) => ReactNode[]`


defaultDom.delete 就是删除的 dom

**Comment by youngList** [comment]
我其实想要的是我自定义一个删除，删除的时候执行一些其他的操作，最后在调用protable默认的删除方法发自我的华为手机-------- 原始邮件 --------发件人： 陈帅 ***@***.***>日期： 2021年5月23日周日 中午12:57收件人： ant-design/pro-components ***@***.***>抄送： youngJson ***@***.***>, Author ***@***.***>主    题： Re: [ant-design/pro-components] table在可编辑状态下怎么自定义删除操作的按钮#2630🧐[问题] (#2631)

(row: T, config: ActionRenderConfig<T>,defaultDom) => ReactNode[]

defaultDom.delete 就是删除的 dom

**Comment by chenshuai2144** [comment]
那你要自己实现了，默认的删除要用到 hooks，不能写成方法
