### ISSUE TITLE
🧐[问题] 在使用 Protable 是如果同时配置了expandable 和 rowSelection，expand icon 和 checkbox 的位置是否可以支持调换

### ISSUE THREAD

**Issue by kiyass** [ant-design/pro-components#2632]
### 🧐 问题描述

如题，在使用 Protable 是如果同时配置了expandable 和 rowSelection，expand icon 列会出现在 checkbox 列之前，但想要 checkbox 在前。想问这两列的顺序是否支持配置呢，或者我可以以哪种方式去调换他们的顺序呢？

### 💻 示例代码

[codesandbox.io](https://codesandbox.io/s/clever-jang-5u745)

**Comment by chenshuai2144** [comment]
这是antd设计的，不能修改
