### ISSUE TITLE
🐛[BUG] colSize 可以不是整数吗？现在不是整数的情况下，查询、重置按钮会错位

### ISSUE THREAD

**Issue by jiyingzhi** [ant-design/pro-components#2633]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
不行的，如果你想要这样搞，可以把 span 设置为 1，然后分别设置 colsize
