### ISSUE TITLE
ProTable column配置项 search.transform 当自定义renderFormItem输入组件的时候，不生效

### ISSUE THREAD

**Issue by brownbo** [ant-design/pro-components#2634]
### 🧐 问题描述
search.transform 当自定义renderFormItem输入组件的时候，不生效
版本号@ant-design/pro-table@2.27.1

### 💻 示例代码
```
 {
    title: '更新时间',
    key: 'time',
    hideInTable: true,
    renderFormItem: () => {
      return <RangePickerWith2Comp />;
    },
    search: {
      //不生效
      transform: (value: any) => {
        return {
          d: moment(value.startDate).format('YYYY-MM-DD'),
          b: moment(value.endDate).format('YYYY-MM-DD'),
        };
      },
    },
  }
```

**Comment by brownbo** [comment]
![image](https://user-images.githubusercontent.com/11483459/116383636-9ae96c80-a849-11eb-86d7-d0815caa46c2.png)
看源代码，有个这个注释，然后修改成数组后，解决问题。

**Comment by binbin1015** [comment]
可以贴一下具体解决代码吗

**Comment by LLmoskk** [comment]
> 可以贴一下具体解决代码吗
把你的自定义renderFormItem返回的数据结构改成数组就好
![image](https://github.com/user-attachments/assets/b65e1954-b4cc-4d1b-bb2e-9cec9f698d7e)
