### ISSUE TITLE
🐛[BUG] 在QueryFilter中使用ProForm.Group出了问题

### ISSUE THREAD

**Issue by hemengke1997** [ant-design/pro-components#2639]
### 🐛 bug 描述
1. 在`QueryFilter`中使用`ProForm.Group`，若`ProForm.Group`不添加title，则ProForm.Group失效，且不会在dom上渲染。
2. 若添加title，分组成功，但是`QueryFilter`的样式会乱

### 📷 复现步骤

使用官方例子，把title去掉即可复现问题[1]  https://procomponents.ant.design/components/query-filter#%E6%9F%A5%E8%AF%A2%E7%AD%9B%E9%80%89-%E6%90%9C%E7%B4%A2
上述例子，添加submitter配置即可复现问题[2]

### 💻 复现代码

`<QueryFilter
        span={24}
        labelWidth="auto"
        split
        onChange={onFilterChange}
        className={styles.filter}
      >
        <ProForm.Group>
          <ProFormText name="name" />
        </ProForm.Group>
        <ProForm.Group>
          <ProFormText name="age" label="年龄" />
          <ProFormDatePicker name="birth" label="生日" />
        </ProForm.Group>
      </QueryFilter>`

### © 版本信息

- "@ant-design/pro-form": "^1.21.5",
- "umi": "^3.2.14",
- chrome
- Windows

**Comment by chenshuai2144** [comment]
这是故意这么设计的 ProForm.Group 不应该在 QueryFilter 中使用

**Comment by hemengke1997** [comment]
那官方例子里面在QueryFilter中使用了ProForm.Group，就迷惑人了.. @chenshuai2144

**Comment by chenshuai2144** [comment]
那个是为了方便变形
