### ISSUE TITLE
🧐[问题]使用pro-component中pro-table 搜索表单例子demo中有警告

### ISSUE THREAD

**Issue by zhangfan19970406** [ant-design/pro-components#264]
### 🧐 问题描述
使用pro-table 搜索表单例子demo时，复制代码再本地跑，控制台有警告，请教下如何解决？
![image](https://user-images.githubusercontent.com/37012223/90760391-66b1c980-e314-11ea-8eb7-04d5125ed7a0.png)
![image](https://user-images.githubusercontent.com/37012223/90760430-75987c00-e314-11ea-9df1-785bdc086135.png)

**Comment by chenshuai2144** [comment]
更新一下本地的依赖

**Comment by zhangfan19970406** [comment]
![image](https://user-images.githubusercontent.com/37012223/90843799-0c0c8200-e395-11ea-9090-15937f5dd9f1.png)
上图是我今天根据github上yarn安装的依赖，每个是最新的吗？ 但是我运行项目还是有警告
警告如下
![image](https://user-images.githubusercontent.com/37012223/90843917-42e29800-e395-11ea-8f41-47e9ad649339.png)
