### ISSUE TITLE
🐛[BUG]表格查询条件收起展示有误

### ISSUE THREAD

**Issue by jaw52** [ant-design/pro-components#2642]
### 🐛 bug 描述
展开时
![图片](https://user-images.githubusercontent.com/53564781/116501580-b7d27e00-a8e3-11eb-8b82-2de186980225.png)

收起时
![图片](https://user-images.githubusercontent.com/53564781/116501558-abe6bc00-a8e3-11eb-85ad-e963afa17392.png)

### 💻 复现代码

https://codesandbox.io/s/valuetype-xuanzelei-forked-8gp9e?file=/App.tsx

### © 版本信息

- ProComponents 版本:最新版本

**Comment by chenshuai2144** [comment]
不要配置 colSize ？

**Comment by jaw52** [comment]
> 
> 
> 不要配置 colSize ？

是这样的，我们需求中有独占一行的查询选项，翻了一下api，只找到设置colSize来实现

**Comment by chenshuai2144** [comment]
那你本地跑一下，codebox 不会自动加载样式

**Comment by jaw52** [comment]
> 
> 
> 那你本地跑一下，codebox 不会自动加载


> 
> 
> 那你本地跑一下，codebox 不会自动加载样式



> 
> 
> 那你本地跑一下，codebox 不会自动加载样式

我刚本地试了一下也不行。
codebox 我应该手动引入了样式，codebox 的代码是我将官网的例子修改出来的，官网的收起时正确的，我自己改后 收起就展示两行了

**Comment by chenshuai2144** [comment]
试着升级一下版本，应该是版本的问题
