### ISSUE TITLE
👑 [需求] 怎么样才能主动触发EditableProTable的表单验证的tooltip 

### ISSUE THREAD

**Issue by smile2233514516** [ant-design/pro-components#2643]
### 🥰 需求描述
EditableProTable的自动表单验证的
![image](https://user-images.githubusercontent.com/50870976/116506551-1a317b80-a8f0-11eb-9443-55d93df6db18.png)
改怎么控制它的显示和隐藏

**Comment by smile2233514516** [comment]
![image](https://user-images.githubusercontent.com/50870976/116506182-50223000-a8ef-11eb-885f-9bdbbaa46d9c.png)
因为我想在点击新增的时候进行第一行数据的验证，主动触发这个必填验证，但是这个tooltip，只是在编辑之后，再清空数据，然后才能触发tooltip

**Comment by smile2233514516** [comment]
利用 editable form进行表单验证只会标红，而不会出现tooltip
![image](https://user-images.githubusercontent.com/50870976/116506425-d179c280-a8ef-11eb-871a-d5d04d946357.png)

**Comment by chenshuai2144** [comment]
validateFields | 触发表单验证 | (nameList?: NamePath[]) => Promise
-- | -- | --


<br class="Apple-interchange-newline">

这个 api 不可以吗？

**Comment by smile2233514516** [comment]
> validateFields	触发表单验证	(nameList?: NamePath[]) => Promise
> 这个 api 不可以吗？
使用的就是validateFields，但是不起作用，只会标红，不会显示tooltip，看上面那个代码，保存时候触发，editable 的 form验证，而且直接在EditableProTable使用 formref ，是不起作用的，current为空

**Comment by smile2233514516** [comment]
> validateFields	触发表单验证	(nameList?: NamePath[]) => Promise
> 这个 api 不可以吗？

还有个奇怪的问题，就是我使用了editable 的 form，就会不断的去验证rule，弹出tooltip在表格上闪动

**Comment by smile2233514516** [comment]
> validateFields	触发表单验证	(nameList?: NamePath[]) => Promise
> 这个 api 不可以吗？

使用的就是validateFields，但是不起作用，只会标红，不会显示tooltip，看上面那个代码，保存时候触发，editable 的 form验证，而且直接在EditableProTable使用 formref ，是不起作用的，current为空

**Comment by xykjlcx** [comment]
> > validateFields	触发表单验证	(nameList?: NamePath[]) => Promise
> > 这个 api 不可以吗？
> 
> 使用的就是validateFields，但是不起作用，只会标红，不会显示tooltip，看上面那个代码，保存时候触发，editable 的 form验证，而且直接在EditableProTable使用 formref ，是不起作用的，current为空

貌似是获取焦点后才显示tooltip
