### ISSUE TITLE
🐛[BUG]config里面设置base时，面包屑拼出的地址里面有两个重复的base

### ISSUE THREAD

**Issue by quicklearning123** [ant-design/pro-components#2645]
### 🐛 bug 描述
config:
```
  base: '/workbench1/',
  publicPath: '/workbench2/',
```
routes.ts:
```
{
    name: 'audit',
    icon: 'icon-anquan',
    key: '/audit',
    path: '/Audit',
    routes: [
      {
        path:'.',
        redirect: '/Audit/AuditList',
      },
      {
        name: 'auditlist',
        path: '/Audit/AuditList',
        key: '/audit',
        component: './AuditList',
      },
    ]
  },
```
![image](https://user-images.githubusercontent.com/70048681/116558607-31915880-a932-11eb-94e9-c6fc5052ef6a.png)

### 🏞 期望结果

路径正常

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]     "@ant-design/pro-layout":    "version": "6.16.0"
- umi 版本 3.3
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS] mac

**Comment by liruiqiang666** [comment]
我也遇到了，请问最后问题解决没？
