### ISSUE TITLE
🧐[问题] SchemaForm是否有支持string[]和int[]的valueType

### ISSUE THREAD

**Issue by bambookai** [ant-design/pro-components#2647]
### 💻 示例代码
目前采用formList
```
[
  {
    "title": "API网关名",
    "dataIndex": [
      "OpenApiNames"
    ],
    "valueType": "formList",
    "columns": [
      {
        "valueType": "text"
      }
    ],
    "tip": "",
    "formItemProps": {
      "rules": []
    },
    "width": "m"
  },
  {
    "title": "RPC网关名",
    "dataIndex": [
      "OpenRpcNames"
    ],
    "valueType": "formList",
    "columns": [
      {
        "valueType": "text"
      }
    ],
    "tip": "",
    "formItemProps": {
      "rules": []
    },
    "width": "m"
  },
]
```
有什么办法可以解决

### 🚑 现在效果

![image](https://user-images.githubusercontent.com/35288939/116638768-8fa55680-a999-11eb-9e05-1bb85c8f15c9.png)
![image](https://user-images.githubusercontent.com/35288939/116638797-9b911880-a999-11eb-88fe-4ddb3a90c070.png)
### 🚑  期望格式
![image](https://user-images.githubusercontent.com/35288939/116639543-5968d680-a99b-11eb-8783-a26b2b403a02.png)

**Comment by chenshuai2144** [comment]
`valueType: 'formSet',`

这个 api 就是用来处理一维度数组的
