### ISSUE TITLE
[BUG]ProTable 使用request获取数据后expandable设置defaultExpandAllRows无效

### ISSUE THREAD

**Issue by qingfengdai** [ant-design/pro-components#2648]
### ProTable 使用request获取数据后expandable设置defaultExpandAllRows无效

      <ProTable<TableListItem>
        actionRef={actionRef}
        formRef={ref}
        className={styles.table}
        headerTitle={<div style={{ fontWeight: 'bold' }}>监督动态监管</div>}
        form={{ labelAlign: 'right', initialValues: { xxjdName: '非中止' } }}
        request={(params: TableListParams) => {
          if (engId) params.id = engId
          return getPage({ ...params })
        }}
        postData={(data) => {
          setDatasource(data)
          return data
        }}
        pagination={{ defaultPageSize: 10 }}
        rowKey="id"
        columns={columns}
        expandable={{
          defaultExpandAllRows:true,
          expandedRowRender,
        }}
        size='small'
      />

**Comment by chenshuai2144** [comment]
defaultExpandAllRows 当然不生效了，因为他的功能就是字面的意思，z

你如果非要用就 

```
data& <ProTable/> 
```

这样使用
