### ISSUE TITLE
🧐[问题]npm latest version 疑问

### ISSUE THREAD

**Issue by laoxubuer** [ant-design/pro-components#265]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/7135991/90841694-d87b2900-e38f-11ea-84c4-682460d24dd2.png)

版本从2.x又回退至1.x，是有何用意么，另外1.2.4是最新的内容么，还是仅仅针对1.2.3的一个patch。

1.2.4看下来了，之前有的一些bug，比如国际化失效等，都不存在了。但是依旧有一些warning error。

### 💻 示例代码

无

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
发了个 bugfix，导致我latest 被冲掉了
