### ISSUE TITLE
🧐[问题] EditableProTable其中一栏用renderFormItem渲染自动完成搜索框，最后所选value如何被Form获取？

### ISSUE THREAD

**Issue by timzhangau** [ant-design/pro-components#2653]
### 🧐 问题描述

想实现在表单中加入一个可编辑表格，其中表格的一栏设为搜索选项。但是最后提交时表单中的value跟所选不一样。如何能更新表单value？

我可以实现搜索，用antd的AutoComplete 和Input
![image](https://user-images.githubusercontent.com/9265586/116706980-8952c100-aa11-11eb-950d-e12ee1a7736c.png)

成功选取搜索选项
![image](https://user-images.githubusercontent.com/9265586/116707053-9a033700-aa11-11eb-975c-e1b4321b9fbd.png)

但是表单onFinish拿不到所选value，其他栏用的非自定义的valueType，比如说日期就可以正常更新。
![image](https://user-images.githubusercontent.com/9265586/116707683-49400e00-aa12-11eb-9fdd-68e735384ec0.png)

### 💻 示例代码
```
## 表格栏，第一栏为AutoComplete搜索框， 第二栏为日期选择
const columns: ProColumns<TransactionType>[] = [
  {
    title: 'Instrument Code',
    dataIndex: 'instrumentCode',
    width: '30%',
    renderFormItem: () => (
        <AutoComplete
            options={options}
            onSearch={handleSearch}
        >
              <Input placeholder="Search instrument" />
       </AutoComplete>
),
  },
  {
    title: 'Date',
    dataIndex: 'transactionDate',
    width: '15%',
    valueType: 'date',
  },
]


## 表单下的可标记表格
<ProForm.Item
    label="Transactions"
    name="transactions"
    trigger="onValuesChange"
>
    <EditableProTable<TransactionType>
    rowKey="id"
    toolBarRender={false}
    columns={columns}
    recordCreatorProps={
        {
        newRecordType: 'dataSource',
        position: 'bottom',
        creatorButtonText: 'Add a new transaction',
        }
    }
    />
</ProForm.Item>

```

**Comment by timzhangau** [comment]
我知道怎么做了， 要自己setFieldsValue，谢谢

**Comment by h1nson** [comment]
有解决方案了吗，能分享一下吗？

**Comment by h1nson** [comment]
`fieldProps: (form, {rowKey}) => {
          form.setFieldsValue({[rowKey]: {
            name: '',
            weight: ''
          }})
      }`
