### ISSUE TITLE
🐛[BUG]配置ConfigProvider的prefixCls在Proform无效

### ISSUE THREAD

**Issue by birdycn** [ant-design/pro-components#2658]
```
  <ConfigProvider prefixCls="my">
      <div className={styles.container}>
        <div className={styles.login}>
          <ProForm
```
![image](https://user-images.githubusercontent.com/32201961/116863449-e67c8b80-ac38-11eb-8fd0-5e879916658d.png)

这可咋整。。。Proform不支持prefix吗？

**Comment by chenshuai2144** [comment]
检查一下是不是打包了两份不同的 antd

**Comment by renyuzh** [comment]
可以直观的从.lock文件中检查是否打包了两份不同的antd

**Comment by lzghost** [comment]
> Refere

我找了一圈，也没发现两个antd的问题啊

**Comment by lzghost** [comment]
> 检查一下是不是打包了两份不同的 antd

我找了一圈也没有发现两个antd的问题

**Comment by lzghost** [comment]
> 可以直观的从.lock文件中检查是否打包了两份不同的antd

这个问题你也遇到了。解决了吗？
