### ISSUE TITLE
🐛[BUG] Pro-Table : v2.5.15版本 defaultCollapsed 无效

### ISSUE THREAD

**Issue by dmdoit** [ant-design/pro-components#266]
### 🐛 bug 描述
```
search={{
     defaultCollapsed: true,
}}
```
无效

### 🏞 期望结果

可以正常使用

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by MrZhouChiBang** [comment]
同问

**Comment by jockey100332** [comment]
> ### 🐛 bug 描述
> ```
> search={{
>      defaultCollapsed: true,
> }}
> ```
> 
> 无效
> 
> ### 📷 复现步骤
> ### 🏞 期望结果
> 可以正常使用
> 
> ### 💻 复现代码
> ### © 版本信息
> * ProComponents 版本: [e.g. 4.0.0]
> * umi 版本
> * 浏览器环境
> * 开发环境 [e.g. mac OS]

设置false为打开， 但是设置完成后，在生产环境下所有查询条件是情况状态！
