### ISSUE TITLE
🧐[问题] ProFormSelect 怎么修改搜索结果高亮的颜色？

### ISSUE THREAD

**Issue by BabyFriedCake** [ant-design/pro-components#2667]
### 🧐 问题描述

ProFormSelect 怎么修改搜索结果高亮的颜色

**Comment by jiyingzhi** [comment]
看了一下，代码里是写死的
![image](https://user-images.githubusercontent.com/21698836/117237785-3ab48500-ae5e-11eb-9b47-8e525417c9f7.png)

**Comment by jiyingzhi** [comment]
@chenshuai2144 我觉得可以加一个 optionHighlightColor 的 prop

**Comment by chenshuai2144** [comment]
我支持一下 less 吧，加那么多 api 不好维护
