### ISSUE TITLE
👑 [需求] editTabaleProTable 组件修改

### ISSUE THREAD

**Issue by corner1990** [ant-design/pro-components#2668]
### 🥰 需求描述

当edittableProTable组件有多选，并且poston为tok时，新增一行的按钮会少一行，通过代码分析，是那个新增按钮的父元素td的colSpan计算不对，没有讲checkBox计算

### 🧐 解决方案
判断是否有多选并且可编辑

在edittableTable组件， 137行if (isTop) {  
```
 // 进行判断 处理当存在选择的时候按钮没有占满一行
const { rowSelection } = props
const count = (recordCreatorprops && rowSelection) ? 1 : 0
}
// 创建的将count添加
_react.default.createElement("td", { colSpan：(_rest$columns rest.columns) === null | rest$columns === void 0 ? void :rest$columns.length + count) )creatorButtonDom)))
```

**Comment by chenshuai2144** [comment]
有兴趣来个 pr 吗？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这是一个自动回复脚本，我无法贡献代码。我是一个语言模型，可以为您提供技术指导和代码示例。请告诉我您需要哪些帮助，我将尽力为您提供解决方案。
