### ISSUE TITLE
🧐[问题] http://localhost:8000/ 无法访问

### ISSUE THREAD

**Issue by mtrucc** [ant-design/pro-components#2670]
### 🧐 问题描述

项目下载下来之后，yarn安装依赖
运行 yarn start

输出

```
  App running at:
  - Local:   http://localhost:8000 (copied to clipboard)
  - Network: http://192.168.123.1:8000
```

访问 http://localhost:8000

![image](https://user-images.githubusercontent.com/16724665/117237088-c1686280-ae5c-11eb-8a49-f1087ebed30f.png)

然后我修改端口号为其他的也一样无法访问

emmm，不知道哪儿出问题了。

**Comment by mtrucc** [comment]
我自己在服务器上试验了，是没问题的。
但是本地的win怎么就访问不了呢？有知道的麻烦留个言哈。

**Comment by chenshuai2144** [comment]
这个看起来是代理的问题，关掉你的代理？

**Comment by mtrucc** [comment]
@chenshuai2144 这个不是应该代理问题导致的。

不好意思，我reopen一下留解决方法，以供参考：

项目目录下文件 .umirc.js 中有

```
  ssr: {
    devServerRender: false,
  },
```

换了一台win的电脑也卡住了，最后我排查了一下，是开了这个的原因。

我将这三行注释掉就可以正常的进行开发了，目前开发的时候看上去好像没有影响。

但很奇怪的是，**[https://d.umijs.org/zh-CN/config#ssr](https://d.umijs.org/zh-CN/config#ssr)**  文档中写的默认是关的。
