### ISSUE TITLE
components升级到最新后启动编译错误🐛[BUG]

### ISSUE THREAD

**Issue by egene-huang** [ant-design/pro-components#2674]
### 🐛 bug 描述

我使用了以下组件: 
- pro-card
- pro-descriptions
- pro-form
- pro-layout
- pro-table
升级到最新后(操作时间: 2021-05-06 ) 启动好像有umi的错误，
```log
This dependency was not found:
node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/createForOfIteratorHelper in ./node_modules/fast-deep-equal/es6/index.js
To install it, you can run: npm install --save /projects/xxx/node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/createForOfIteratorHelper
```
好像需要升级 umi版本吗？  我有一个建议， 就是 组件升级希望可以附带依赖版本要求说明

着急使用,我暂时回退了版本，不知道怎么解决

我升级大原因是看到 DrawerForm组件使用的时候添加了泛型支持，但是我本地编写代码的时候，提示这个不支持这个泛型， 所以我想会不会是版本需要升级，于是就就这样了
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
看起来是因为babel的更新问题，删除lock 再来一次

**Comment by xijin** [comment]
也遇到这个坑了，看起来里面的某个包锁死了版本了， 锁死 "@babel/runtime": "7.14.0" 到这个ok了

**Comment by charithjayasanka** [comment]
Solutions ?

**Comment by xsjcTony** [comment]
any solutions?
