### ISSUE TITLE
👑 [需求]EditableProTable 可以用原来Form提示信息样式，而不是tooltip 样式

### ISSUE THREAD

**Issue by jackluson** [ant-design/pro-components#2676]
### 🥰 需求描述
现在的验证是tooltip形式，可以配置用原来form的验证样式吗
![image](https://user-images.githubusercontent.com/36684351/117294326-16c86200-aea5-11eb-8cac-80c5f447a0f0.png)

**Comment by chenshuai2144** [comment]
还是推荐 tooltip。不然表格大小会受影响
