### ISSUE TITLE
🐛[BUG] Problem with input value in editable ProDescriptions when there is validation

### ISSUE THREAD

**Issue by iloveip** [ant-design/pro-components#2678]
There is a problem with input value in editable ProDescriptions when the field has validation rules.

**Steps to reproduce**:

1. Go to [codesanbox](https://codesandbox.io/s/kebianjidedingyiliebiao-forked-cnllx?file=/App.tsx) (forked example from ProDescriptions site).
2. Click to edit any field.
3. Clear the value of the input. You will see the validation message, which says that the field is required.
4. Click Cancel. You will see the former value in the field.
5. Click edit again. There will be no value in the input.

**What is the expected behavior**:
On Step 5, after clicking the edit icon, you should see the same value in the input as in Step 4.

@ant-design/pro-descriptions v1.7.7
antd v4.15.3

**Comment by chenshuai2144** [comment]
The default value is always run only once. 😭

**Comment by iloveip** [comment]
Thank you very much 🙏 When is this going to be released?
