### ISSUE TITLE
🧐[问题]  ProFormFields 下的  ProFormCaptcha是不是没有做国际化

### ISSUE THREAD

**Issue by GamesSoul** [ant-design/pro-components#2680]
![图片](https://user-images.githubusercontent.com/37973776/117384101-c7ba1580-af14-11eb-8f9c-c85eb0a1672a.png)
如图  获取验证码在切换为 英文后  并没有切换为英文  是没有适配国际化还是需要传入什么参数支持？

**Comment by chenshuai2144** [comment]
是的，



参数 | 说明 | 类型 | 默认值
-- | -- | -- | --
onGetCaptcha | 点击获取验证码的事件，如果配置了 phoneName 会自动注入 | (phone)=>Promise<any> | -
captchaProps | 获取验证码按钮的 props，与 antd 的 props 相同 | ButtonProps | -
countDown | 倒计时的秒数 | number | 60
captchaTextRender | 渲染计时的文案 | (timing: boolean, count: number) => React.ReactNode | -



可以通过这些 api 来自定义
