### ISSUE TITLE
🐛[BUG] ProTable=>renderFormItem=>defaultRender 重复渲染 Double Form Label Rendering

### ISSUE THREAD

**Issue by yanglu758** [ant-design/pro-components#2685]
### 🐛 bug 描述
更新pro-table到"@ant-design/pro-table": "^2.16.2" 后在pro-table的搜素栏和表单里开始出现问题，Form Label会重复渲染。估计`defaultRender`里会重复渲染。

### 💻 复现代码
Column:
```
{
      title: 'Account',
      dataIndex: 'account_username',
      ellipsis: true,
      sorter: true,
      tooltip: "Use % for contains (LIKE) search.",
      editable: (text, record, _) => 
        !["BNC", "BMX", "DBT"].includes(record.exchange_id),
      renderFormItem: (_, { type, defaultRender }, form) => {
        const exchange = form.getFieldValue("exchange_id")
        if (["BNC","DBT", "BMX"].includes(exchange) &&
          type === 'form') {
          return undefined
        } else {
          return defaultRender(_)
        }
      }
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]
```
    "@ant-design/icons": "^4.3.0",
    "@ant-design/pro-descriptions": "^1.1.2",
    "@ant-design/pro-form": "^1.10.2",
    "@ant-design/pro-layout": "^6.7.0",
    "@ant-design/pro-table": "^2.16.2",
```
### 🚑 其他信息

![Capture3](https://user-images.githubusercontent.com/12844206/117400984-0bc60e00-af47-11eb-87e5-937eee81dc7f.JPG)
![Capture2](https://user-images.githubusercontent.com/12844206/117400988-0c5ea480-af47-11eb-87f5-5ecfd9a970dd.JPG)

**Comment by Hikarien** [comment]
更新到 2.35.1后，这个bug仍然存在  @chenshuai2144

**Comment by jeffWorker** [comment]
一样遇到这个问题

**Comment by jeffWorker** [comment]
"@ant-design/pro-table": "^2.35.1"
 {
      dataIndex: "mobile",
      title: "手机号码",
      key: 'mobile',
      formItemProps: {
        rules: [
          {
            required: true,
            message: '此项为必填项',
          },
          {
            pattern: /^1[3|4|5|6|7|8|9][0-9]\d{8}$/, message: '请输入正确的手机号'
          }
        ],
      },
      renderFormItem: (_, { type, defaultRender, formItemProps, fieldProps, ...rest }, form) => {
        if (type === 'form') {
          return Object.keys(stepFormValues).length > 0 ? null : defaultRender(_);
        }
        return defaultRender(_);
      }
    }
![image](https://user-images.githubusercontent.com/21035691/117441649-4e4c1280-af68-11eb-97cd-8c3c98e04c8b.png)

**Comment by chenshuai2144** [comment]
fixed，昨天刚发的版本
