### ISSUE TITLE
🐛[BUG] 可编辑表单，修改时，单选没有把值带过来

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#2686]
![image](https://user-images.githubusercontent.com/30397655/117402796-a0297400-af39-11eb-97f9-459530dd0579.png)

**Comment by DerrickTel** [comment]
https://codesandbox.io/s/kebianjibiaoge-forked-gsd3e?file=/App.tsx
这里可以带的。你看看是不是少了什么。（不知道为什么样式丢了...但是不影响最终结果
