### ISSUE TITLE
🧐[问题]ProFormDependency 报错Maximum update depth exceeded

### ISSUE THREAD

**Issue by elainezhou0419** [ant-design/pro-components#2688]
### 🧐 问题描述
ProFormDependency使用这个组件的时候，情况是这样的输入框A依赖B，B依赖C，这样使用的时候报错
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
如果把form.setFieldsValue({ lineLength: res }); 这行注释掉错误就没了。所以这里该怎么处理。如果这样赋值是有问题的，怎样提供一个ProFormDependency组件外部可以得到的lineLength结果。

### 💻 示例代码
```

<ProFormDependency name={[ 'linesThickness' ]}>
{( { linesThickness}, form,) => {
const res = linesThickness * 1.5
form.setFieldsValue({ lineLength: res });
return (
<ProFormDigit
name="lineLength"
fieldProps={{ precision: 2, step: 0.01 }}
noStyle
readonly
/>
);
}}

<ProFormDependency name={['lineArea', 'lineLength']}>
{({ ironColumnNumber, lineArea, lineLength }, form) => {
const res = (lineArea * lineLength ) ;
form.setFieldsValue({ lineWeight: Number(res.toFixed(2)) });
return (
<ProFormDigit
name="lineWeight"
fieldProps={{ precision: 2, step: 0.01 }}
noStyle
readonly
/>
);
}}

```

**Comment by chenshuai2144** [comment]
用 formRef 吧，你在依赖a 的逻辑里面设置 a 总是会报错的

**Comment by WuJiY** [comment]
好像不能在依赖里面进行setFieldValue吧
