### ISSUE TITLE
dateRange无法选择日期🧐[问题]

### ISSUE THREAD

**Issue by guogeer** [ant-design/pro-components#2689]
### 🧐 问题描述

无法选中日期

### 💻 示例代码

    {
      title: '发送时间',
      dataIndex: 'create_time',
      valueType: 'dateRange',
      hideInTable: true,
      initialValue: defaultParams.create_time.map((v) => moment(v, dateFmt)),
      renderFormItem: (item, { defaultRender, ...rest }) => {
        return <DatePicker.RangePicker picker="date" {...rest} />;
      },
    },
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/5010851/117426790-e3dea680-af56-11eb-945f-da26ebff725d.png)
![image](https://user-images.githubusercontent.com/5010851/117428714-e80bc380-af58-11eb-86e8-8bd60239c0c0.png)

**Comment by guogeer** [comment]
@chenshuai2144 
https://codesandbox.io/s/chaxunbiaoge-forked-83116

**Comment by chenshuai2144** [comment]
return <DatePicker.RangePicker picker="date" {...rest} />;

试着去掉 rest 里面是不是放了东西

**Comment by guogeer** [comment]
感谢回复！https://codesandbox.io/s/chaxunbiaoge-forked-83116。可以显示了
上面的例子去掉rest试了下，可以。就是样式有点怪
![image](https://user-images.githubusercontent.com/5010851/118069751-4ca2a480-b3d7-11eb-8c59-a1337e31f9cb.png)
下图是比较常见的显示：
![image](https://user-images.githubusercontent.com/5010851/118069927-9c816b80-b3d7-11eb-965f-3e3ef88f94c6.png)

**Comment by chenshuai2144** [comment]
自己设置一下 placeholder
