### ISSUE TITLE
👑 [需求] ProDescriptions 增加可选货币标识. e.g. 美元$, 英镑，欧元, ISK这种

### ISSUE THREAD

**Issue by Dragon201701** [ant-design/pro-components#2695]
### 🥰 需求描述

默认的是人民币，比如我想设置成美元，就直接把$传进去，想设置成其他的就把对应的符号传进去

### 🧐 解决方案

比如这样：
`<ProDescriptions.Item label="Invoice" valueType="money" moneySymbol="$"> {formVals.amount}</ProDescriptions.Item>
`
默认￥

**Comment by DerrickTel** [comment]
`<ProDescriptions.Item label="Invoice"> ${formVals.amount}</ProDescriptions.Item>`

**Comment by Dragon201701** [comment]
我目前就是先这样暂时解决问题。。。

**Comment by chenshuai2144** [comment]
现在是通过locale 来实现的，你可以再filedProps 中配置locale，会设置号 货币符号

**Comment by hanwenbo** [comment]
> locale

无效  试了
