### ISSUE TITLE
ProDescriptions字段动态无法处理

### ISSUE THREAD

**Issue by tigerxiongj** [ant-design/pro-components#270]
request和columns无法处理字段动态的情况。
columns下定义的字段都是已知的。

**Comment by chenshuai2144** [comment]
祥细描述下你的需求?

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
