### ISSUE TITLE
🧐[问题] EditableProTable如何主动触发保存（不点击保存按钮）？

### ISSUE THREAD

**Issue by xykjlcx** [ant-design/pro-components#2711]
### 🧐 问题描述

想要实现Pro V4的高级表单中，可编辑表格的编辑行回车自动保存
如何实现，不点击下图的保存按钮，通过回车（或者其他方式），主动触发onSave

### 💻 示例代码

看源码里，在`actionRender`方法的`config`中是可以拿到`onSave`回调的，比如想要在`renderFormItem`中使用，如何获取到呢？

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/32430701/117634417-77abaf00-b1b1-11eb-94bc-6c7e754308a9.png)

**Comment by ibryanwu** [comment]
请问，你解决了吗？怎么解决的呢？

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/issues/3133
