### ISSUE TITLE
ProFormText组件，max校验有bug🐛[BUG]

### ISSUE THREAD

**Issue by whaty** [ant-design/pro-components#2712]
### 🐛 bug 描述

ProFormText组件，从零开始输入，校验是正常的，但是输入完，做修改功能的时候，字段长度没有超长，也会提示字段超长。只要开始往框里输入任何信息之后，提示就没有了。目前我解决不了这个bug，得修改底层代码。

![image](https://user-images.githubusercontent.com/26294919/117643463-feb15500-b1ba-11eb-8e8c-1d793967c570.png)

![image](https://user-images.githubusercontent.com/26294919/117643476-053fcc80-b1bb-11eb-9907-3b2d5008860f.png)

**Comment by DerrickTel** [comment]
怎么复现，我试了一下你的代码，我是没毛病的...

**Comment by whaty** [comment]
我这设计到要从远程获取数据，没法放到外面演示，但是你方便远程我嘛？我给你演示，你直接看

**Comment by whaty** [comment]
> 怎么复现，我试了一下你的代码，我是没毛病的...看样子像是antd的bug，可以看看你的版本号之类的吗？或者给一个codesandbox

我这涉及到要从远程获取数据，没法放到外面演示，但是你方便远程我嘛？我给你演示，你直接看

**Comment by chenshuai2144** [comment]
看起来是因为 string 变成了一个 object。我这里也是无法复现

**Comment by whaty** [comment]
> Hello @whaty. Please provide a online reproduction by forking this link https://codesandbox.io/ or a minimal GitHub repository.
> 
> 你好 @whaty, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)


麻烦看下吧
https://codesandbox.io/s/thirsty-monad-rozi1?file=/App.tsx

**Comment by whaty** [comment]
> 看起来是因为 string 变成了一个 object。我这里也是无法复现

https://codesandbox.io/s/thirsty-monad-rozi1?file=/App.tsx

麻烦看下吧，这个是必现的！点击新建表单》确定，现象就出来了

**Comment by whaty** [comment]
> > Hello @whaty. Please provide a online reproduction by forking this link https://codesandbox.io/ or a minimal GitHub repository.
> > 你好 @whaty, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。
> > ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)
> 
> 麻烦看下吧
> https://codesandbox.io/s/thirsty-monad-rozi1?file=/App.tsx

麻烦看下吧，这个是必现的！点击新建表单》确定，现象就出来了

**Comment by whaty** [comment]
> 怎么复现，我试了一下你的代码，我是没毛病的...看样子像是antd的bug，可以看看你的版本号之类的吗？或者给一个codesandbox

https://codesandbox.io/s/thirsty-monad-rozi1?file=/App.tsx

麻烦看下吧，这个是必现的！点击新建表单》确定，现象就出来了

**Comment by chenshuai2144** [comment]
点进去看了看好像没问题，是不是还有什么隐含条件

![image](https://user-images.githubusercontent.com/8186664/118063907-93d76800-b3cc-11eb-85b9-f527afad5767.png)

**Comment by DerrickTel** [comment]
`<ProFormText 
            label={"age"}
            name="age"
            placeholder="请输入"
            tooltip="最长为 10 字符"
            formItemProps={{
              rules: [
                {
                  max: 10 ,
                  message: '不能大于 10 个字符',
                  type: 'string',
                },
              ],
            }}

          />`

**Comment by DerrickTel** [comment]
因为你的age传过来是一个number，他的max按数字的最大值10来取了，而你的默认值又是28.所以在number中是10<number所以校验没过。你的max应该是希望是stirng的长度吧？类型限制一下就好了 @whaty 。看看这样有没有解决你的问题。还是我理解错了？

**Comment by whaty** [comment]
> 因为你的age传过来是一个number，他的max按数字的最大值10来取了，而你的默认值又是28.所以在number中是10<28所以校验没过。你的max应该是希望是stirng的长度吧？类型限制一下就好了 @whaty 。看看这样有没有解决你的问题。还是我理解错了？

应该就是你说的这个问题了，我试过把age变成字符串，就不会报错了

**Comment by whaty** [comment]
> 点进去看了看好像没问题，是不是还有什么隐含条件
> 
> ![image](https://user-images.githubusercontent.com/8186664/118063907-93d76800-b3cc-11eb-85b9-f527afad5767.png)

https://codesandbox.io/s/thirsty-monad-rozi1?file=/App.tsx:122-134，现象还在的呀！很简单的就浮现了，你别把代码复制到你本地去看，从你发的图片可以看出，你没有在我发的地址中查看。请看：https://codesandbox.io/s/thirsty-monad-rozi1?file=/App.tsx:122-134   
![image](https://user-images.githubusercontent.com/26294919/118119562-21dd3e00-b421-11eb-8554-db38e01ceef1.png)

**Comment by whaty** [comment]
> 因为你的age传过来是一个number，他的max按数字的最大值10来取了，而你的默认值又是28.所以在number中是10<28所以校验没过。你的max应该是希望是stirng的长度吧？类型限制一下就好了 @whaty 。看看这样有没有解决你的问题。还是我理解错了？

![image](https://user-images.githubusercontent.com/26294919/118119940-b8116400-b421-11eb-9d96-a924eced1c35.png)

**Comment by whaty** [comment]
> 因为你的age传过来是一个number，他的max按数字的最大值10来取了，而你的默认值又是28.所以在number中是10<28所以校验没过。你的max应该是希望是stirng的长度吧？类型限制一下就好了 @whaty 。看看这样有没有解决你的问题。还是我理解错了？

可以仔细看下红框里的内容，提示不是标准的string？应该不支持在rule里面修改类型吧！对于number类型的，该怎么限制最大长度呢？

![image](https://user-images.githubusercontent.com/26294919/118120228-1fc7af00-b422-11eb-8453-eabefb3bbae5.png)

**Comment by DerrickTel** [comment]
![image](https://user-images.githubusercontent.com/24643779/118204822-aff10d00-b491-11eb-9d0f-3ca59027f2d6.png)

**Comment by DerrickTel** [comment]
我感觉antd的文档算写的很帅的了。你可以先阅读一下文档。我的时间无所谓，蚂蚁的大佬们只有有空的时候才会帮忙解答，而且也不是义务解答....其实我也是帮你在文档上面找你的需求...

**Comment by DerrickTel** [comment]
或者上面有一个正则匹配也可以试试看

**Comment by whaty** [comment]
> 或者上面有一个正则匹配，len都可以试试看

好的，多谢啦！你截图的url地址能发出来吗

**Comment by DerrickTel** [comment]
https://ant.design/components/form-cn/#Rule

**Comment by whaty** [comment]
> https://ant.design/components/form-cn/#Rule

多谢，我这也是算阿里系列的深度用户了，ant design +ant design pro +proComponet + landing + dmui ，全部都用上了

**Comment by DerrickTel** [comment]
那你更要好好看文档了，大佬们辛辛苦苦写的文档和代码。解决完问题关一下issue哦
