### ISSUE TITLE
ProLayout 页面刷新菜单丢失🐛[BUG]

### ISSUE THREAD

**Issue by w345731923** [ant-design/pro-components#2716]
### 🐛 bug 描述

1、使用antd-pro v4 js版本
2、登录后左侧菜单显示正常（edge登录页不显示）
3、F5刷新页面左侧菜单丢失
已经清理过浏览器缓存。
### 📷 复现步骤

注：如果menuList是固定值，则不会丢失。
menuList的值在外部可以打印，在menu={{}}打印是空数组

通过打印发现，外部的state更新了，但是prolayout并没有更新
### 💻 复现代码

    <ProLayout
        logo={logo}
        formatMessage={formatMessage}
        // {...props}
        {...settings}
        onCollapse={handleMenuCollapse}
        onMenuHeaderClick={() => history.push('/')}
        rightContentRender={() => <RightContent />}
        postMenuData={(menuData) => {
          menuDataRef.current = menuData || [];
          return menuData || [];
        }}
        menu={{
          request: async () => {
            await waitTime(2000);
            // return [
            //   {
            //     path: '/',
            //     name: 'welcome',
            //     children: [
            //       {
            //         path: '/welcome',
            //         name: 'one',
            //         children: [
            //           {
            //             path: '/welcome/welcome',
            //             name: 'two',
            //             exact: true,
            //           },
            //         ],
            //       },
            //     ],
            //   },
            //   {
            //     path: '/demo',
            //     name: 'demo',
            //   },
            // ];
            console.log('request menuList ',menuList)
            return menuList;
          },
        }}        
      >
        {children}
      </ProLayout>

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] 6.17.1
- umi 版本 3.2.14
- 浏览器环境 搜狗v10
- 开发环境 [e.g. mac OS] win10

**Comment by DevXiaolan** [comment]
关注着问题
