### ISSUE TITLE
🧐[问题]ProtableuseEffect设置查询条件，request请求没有查询条件

### ISSUE THREAD

**Issue by JackRoy1992** [ant-design/pro-components#2718]
### 🧐 问题描述

需求实现查询条件缓存，离开列表页后，回到列表页，查询条件还在。现在通过ref.current.setFeildsValue将sessionstorage里的查询条件设置给了表单，都很正常，但是进入页面时第一次的request请求内容中没有查询条件

**Comment by chenshuai2144** [comment]
试试将查询条件缓存到 url 中呢
```tsx
<ProTable form={{syncToUrl:true}}/>
```




syncToUrl | 同步参数到 url 上,url 只支持 string，在使用之前最好读一下url 中的参数类型 | true \| (values,type)=>values | -
-- | -- | -- | --
