### ISSUE TITLE
🐛[BUG] ProLayout mix 模式下navTheme 有问题

### ISSUE THREAD

**Issue by mumu-baba** [ant-design/pro-components#2720]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/33894127/117780795-88702980-b272-11eb-8492-40a89c35fc66.png)

![image](https://user-images.githubusercontent.com/33894127/117780682-70000f00-b272-11eb-9b54-d23edacb67e4.png)
![image](https://user-images.githubusercontent.com/33894127/117780747-7f7f5800-b272-11eb-8347-0f65b5e322c0.png)

实际情况和api文档不符合
### © 版本信息

- pro-layout 版本: 6.16.1
- umi 版本 3.4.7
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个是个 bug，在新版本中修复了，安装最新的版本将会修复它
