### ISSUE TITLE
🐛[BUG] [功能需求] ProCard 的 wrap 无效，并且该属性不好用

### ISSUE THREAD

**Issue by lin-mt** [ant-design/pro-components#2721]
### 🐛 bug 描述

bug：设置了 wrap={true} 属性，并没有实现自动换行
功能需求：wrap是否可以改成 number 类型，比如 wrap={5} ，那么子卡片每五个一行，这样用起来是不是更加清晰了呢

### 📷 复现步骤

直接用官网的例子即可：

```typescript
<ProCard style={{ marginTop: 8 }} gutter={[16, 16]} wrap title="换行">
        <ProCard colSpan={{ xs: 24, sm: 12, md: 12, lg: 12, xl: 12 }} layout="center" bordered>
          Col
        </ProCard>
        <ProCard colSpan={{ xs: 24, sm: 12, md: 12, lg: 12, xl: 12 }} layout="center" bordered>
          Col
        </ProCard>
        <ProCard colSpan={{ xs: 24, sm: 12, md: 12, lg: 12, xl: 12 }} layout="center" bordered>
          Col
        </ProCard>
        <ProCard colSpan={{ xs: 24, sm: 12, md: 12, lg: 12, xl: 12 }} layout="center" bordered>
          Col
        </ProCard>
</ProCard>
```

### 🏞 期望结果

自动换行

### 💻 复现代码

```typescript
<ProCard style={{ marginTop: 8 }} gutter={[16, 16]} wrap title="换行">
        <ProCard colSpan={{ xs: 24, sm: 12, md: 12, lg: 12, xl: 12 }} layout="center" bordered>
          Col
        </ProCard>
        <ProCard colSpan={{ xs: 24, sm: 12, md: 12, lg: 12, xl: 12 }} layout="center" bordered>
          Col
        </ProCard>
        <ProCard colSpan={{ xs: 24, sm: 12, md: 12, lg: 12, xl: 12 }} layout="center" bordered>
          Col
        </ProCard>
        <ProCard colSpan={{ xs: 24, sm: 12, md: 12, lg: 12, xl: 12 }} layout="center" bordered>
          Col
        </ProCard>
</ProCard>
```

### © 版本信息

    "@ant-design/icons": "^4.5.0",
    "@ant-design/pro-card": "^1.11.12",
    "@ant-design/pro-descriptions": "^1.6.8",
    "@ant-design/pro-form": "^1.18.3",
    "@ant-design/pro-layout": "^6.15.3",
    "@ant-design/pro-table": "^2.30.8",
    "@umijs/route-utils": "^1.0.36",
    "antd": "^4.14.0",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "react": "^17.0.0",
    "react-beautiful-dnd": "^13.1.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "styled-components": "^5.2.3",
    "umi": "^3.4.0",
    "umi-request": "^1.0.8"
- 浏览器环境：chrome 90.0.4430.93（正式版本） (x86_64)
- 开发环境：mac OS

### 🚑 其他信息

并无自动换行：
![image](https://user-images.githubusercontent.com/58337359/117791320-c3775a80-b27c-11eb-80bd-3770d4ee276e.png)

**Comment by rdmclin2** [comment]
@DerrickTel 版本更新了吗？要 1.12.0 版本以上才支持

**Comment by rdmclin2** [comment]
![image](https://user-images.githubusercontent.com/4705237/117950843-2d0f6b80-b346-11eb-981a-4aaffcb5896a.png)

内部测试了下，没有复现。

**Comment by rdmclin2** [comment]
1. wrap 改成 number 跟 ant-design 中的 24 栅格设计系统不一致。
2. wrap 改成 number 只能用于平分卡片宽度的情况下，无法支持每个卡片有自己的宽度，更加灵活的宽度配置的情况。
3. 目前 设置 wrap，然后通过 colSpan 配置Col 宽度的实现和 ant-design 中 Row + Col 的配置是一致的。

**Comment by lin-mt** [comment]
> 1. wrap 改成 number 跟 ant-design 中的 24 栅格设计系统不一致。
> 2. wrap 改成 number 只能用于平分卡片宽度的情况下，无法支持每个卡片有自己的宽度，更加灵活的宽度配置的情况。
> 3. 目前 设置 wrap，然后通过 colSpan 配置Col 宽度的实现和 ant-design 中 Row + Col 的配置是一致的。

1. 升级版本，清空缓存之后可以自动换行了
2. 我也理解配置的一致性，但是这时候 colSpan 必须满足 `14 % colSpan = 0` ，也就是 1、2、3、4、6、7、8、12、24 ，然而设置 4 的时候卡片太小了，设置 6 的时候卡片太大了，这就很尴尬。。。

**Comment by rdmclin2** [comment]
@lin-mt 是有不满足的情况，可以直接用 grid 布局或者 flex 布局自己实现，也不复杂的。

**Comment by lin-mt** [comment]
> @lin-mt 是有不满足的情况，可以直接用 grid 布局或者 flex 布局自己实现，也不复杂的。

![image](https://user-images.githubusercontent.com/58337359/118104652-fb61d780-b40d-11eb-9dd1-d1e060c56826.png)

ant design 的 grid 是支持百分比的，是否可以再考虑下呢。
