### ISSUE TITLE
🐛[BUG] 官网的 codesandbox 基本处于瘫痪状态

### ISSUE THREAD

**Issue by lin-mt** [ant-design/pro-components#2722]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/58337359/117792167-9e371c00-b27d-11eb-9754-b69f0160ee16.png)

![image](https://user-images.githubusercontent.com/58337359/117792206-a98a4780-b27d-11eb-87cf-0d16e51632fe.png)

### 📷 复现步骤

点开官网任意一个 codesandbox

### 🏞 期望结果

正常使用

### 🚑 其他信息

难不成只有我才有这个问题吗。。。

**Comment by xiaohuoni** [comment]
我看下
