### ISSUE TITLE
🧐[问题]一直不理解Antd UploadFile的设计思想

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#2724]
一直不理解Antd UploadFile的设计思想
Antd UploadFile的功能，例如，Upload，ProFormUploadButton 在选择文件的同时，就直接调用了POST API。
一直不理解为什么这么设计，有什么好处？
能科普一下吗？

很多时候，除了文件，用户还需要给一些其他的输入，
这些一起作为一个数据整体。这样似乎更合理。

`<Upload name="logo" action="/upload.do" listType="picture">
  <Button icon={<UploadOutlined />}>Click to upload</Button>
</Upload>`

**Comment by chenshuai2144** [comment]
UploadFile 的思路是和后端交互，前端只存一个文件的 cdn 地址。

cdn 在中大型公司是标配，系统里不会存文件本身的。
