### ISSUE TITLE
👑 [需求]ProFormUploadButton文件多选功能

### ISSUE THREAD

**Issue by MTmatao** [ant-design/pro-components#2726]
### 🥰 需求描述

ProFormUploadButton能不能加上multiple

**Comment by DerrickTel** [comment]
fieldProps={{
          multiple: true
        }}

**Comment by MTmatao** [comment]
收到，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月12日(星期三) 下午4:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/pro-components] 👑 [需求]ProFormUploadButton文件多选功能 (#2726)





 
<ProFormUploadButton
 name="upload"
 label="Upload"
 max={2}
 fieldProps={{
 name: 'file',
 multiple: true
 }}
 action="/upload.do"
 extra="longgggggggggggggggggggggggggggggggggg"
 /&gt;
