### ISSUE TITLE
🐛[BUG] ProFormUploadButton上传超过大小限制仍然可以上传

### ISSUE THREAD

**Issue by qiaodaima** [ant-design/pro-components#2737]
### 🐛 bug 描述
[之前提过这个bug, 被关闭，但是我测试发现没改好](https://github.com/ant-design/pro-components/issues/2672)

 
### 📷 复现步骤
- 上传一个超过大小限制的文件 （这个时候发现可以被上传，其实不应该被上传的）
- 然后把上传的文件进行删除，再次上传超过大小限制的文件（这个时候表现正常，上传不了）
 

### 🏞 期望结果
超过大小限制，不应该被上传
 

### 💻 复现代码
[这里有一个在线链接](https://codesandbox.io/s/jibenshiyong-forked-78i7g?file=/App.tsx)
 

### © 版本信息
```
"antd": "4.x",
"react": ">=16.9.0",
"@ant-design/pro-form": "1.23.0",
```

**Comment by qiaodaima** [comment]
@DerrickTel  你提的PR 有问题

**Comment by DerrickTel** [comment]
确实有这个问题。
https://codesandbox.io/s/dianjishangchuan-antd4155-forked-jx1cd
看起来像antd的。我下午抽空看看原因

**Comment by DerrickTel** [comment]
https://github.com/ant-design/ant-design/issues/15561#issuecomment-475108235

**Comment by DerrickTel** [comment]
![image](https://user-images.githubusercontent.com/24643779/118093827-90f66a80-b400-11eb-912f-2666cdf85a8f.png)

**Comment by qiaodaima** [comment]
试了下， 可以了 
![image](https://user-images.githubusercontent.com/81732419/118099646-17627a80-b408-11eb-899f-5ae471284b7c.png)
