### ISSUE TITLE
🐛[BUG] React does not recognize the `isLoading` prop on a DOM element.

### ISSUE THREAD

**Issue by wangxin305** [ant-design/pro-components#2742]
### 🐛 bug 描述
React does not recognize the `isLoading` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `pastdelay` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
React does not recognize the `pastDelay` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `pastdelay` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

@ant-design/pro-layout 6.18.0 版本 会提示以上错误

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 3.4.20
- 浏览器环境 google
- 开发环境 [e.g. mac OS]

**Comment by KrishnaPG** [comment]
This is coming from `umi` and I guess this started coming after  https://github.com/ant-design/pro-components/commit/e2e0232adda8d94b5cf0d40497dee01cebf2af73 

Passing all parameters to `Spin` is causing React to complain about the extract parameters that `Spin` do not understand.

Problem is: `UMI` is passing different parameter names (as shown below) that are not compatible with Spin:
````
      return /*#__PURE__*/createElement(opts.loading, {
        isLoading: state.loading,
        pastDelay: state.pastDelay,
        timedOut: state.timedOut,
        error: state.error,
        retry: subscription.retry
      });
````

Probably FIX is to change the UMI parameter names to be compatible with Spin names, such as `isLoading` -> `spinning`, `pastDelay` -> `delay` etc. and there has to be some other way to consume the extra params and ignore them

**Comment by 17628368021** [comment]
我也遇到相同的我问题，尝试了很久，最后我将 @ant-design/pro-layout 的版本升级到了 “6.17.0” 就解决了，但不一定是这个版本，也许更往前也能解决，可以都试试

**Comment by KrishnaPG** [comment]
The exists in "@ant-design/pro-layout": "^6.18.0" (the latest current one).   The way to solve it is by passing explicitly only the props required for spin as below:


````js
const PageLoading: React.FC<SpinProps> = ({ indicator, size, spinning, tip, ...rest }) => (
  const spinProps = { indicator, size, spinning, tip };  //<<-- filter only the needed props like this

  <div style={{ paddingTop: 100, textAlign: 'center' }}>
    <Spin size="large" {...spinProps } />
  </div>
);
````

Here is the original code currently: https://github.com/ant-design/pro-components/blob/e2e0232adda8d94b5cf0d40497dee01cebf2af73/packages/layout/src/components/PageLoading/index.tsx#L5-L10

**Comment by chenshuai2144** [comment]
已经发布，更新版本即可
