### ISSUE TITLE
🧐[问题]EditableProTable如何动态设置表格的数据呢？

### ISSUE THREAD

**Issue by ITyaoji** [ant-design/pro-components#2743]
### 🧐 问题描述
我有两个表格，左右结构，点击左侧某一行去请求接口返回数据渲染右侧EditableProTable，页面加载时能正常渲染，但以后每一次接口返回数据，EditableProTable 的value属性对应的变量已经改变。可是EditableProTable并没有重新渲染

### 💻 示例代码
![image](https://user-images.githubusercontent.com/24262180/118210793-9229a500-b49d-11eb-8d6e-b0186ff115c3.png)

![image](https://user-images.githubusercontent.com/24262180/118210666-5c84bc00-b49d-11eb-86eb-d4ea3735017b.png)

**Comment by chenshuai2144** [comment]
用form.set 一下，或者等数据回来之后再渲染 table

**Comment by ITyaoji** [comment]
setFieldsValue不行啊，直接就报错了。数据回来只会再渲染table 我用actionRef的reload()。尝试过了 没用

**Comment by chenshuai2144** [comment]
```const [form] = form.useForm()

editable={
 form,
}

form. setFieldsValue
```

**Comment by ilikecandice** [comment]
EditableProTable，使用request加载数据，点击行的时候，监控数据变化，数据变化了，调用 actionRef  的reload方法
