### ISSUE TITLE
🐛[BUG]EditableProTable value属性变更了，但UI未渲染

### ISSUE THREAD

**Issue by ITyaoji** [ant-design/pro-components#2747]
### 🐛 bug 描述

EditableProTable value属性变更了，但UI未渲染

### 📷 复现步骤
1、两个表格 左右结构
2、点击左侧某一行 请求接口返回数据 渲染右侧EditableProTable 
3、UI未渲染，打开react-developer-tools EditableProTable 的value属性以及改变

### 🏞 期望结果
value属性改变 后可以重新渲染表格、

### 💻 复现代码
![image](https://user-images.githubusercontent.com/24262180/118238068-9c15cd00-b4ca-11eb-8666-2f4dd22fd5bd.png)

### © 版本信息

- ProComponents 版本: 2.17.0
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
给个重现吧

**Comment by CaicoLeung** [comment]
我也有这个问题

**Comment by chenshuai2144** [comment]
最新的版本已经解决，可以安装后重试了
