### ISSUE TITLE
🐛[BUG]导航栏菜单与右上角个人信息重叠

### ISSUE THREAD

**Issue by fog3211** [ant-design/pro-components#275]
### 🐛 bug 描述

导航栏菜单与右上角个人信息重叠
### 📷 复现步骤
antdpro官网预览：切换为light主题、top导航模式，可视窗口宽度较小时，Menu菜单会被覆盖

### 🏞 期望结果
Menu长度过长时自动收起

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 3
- 浏览器环境 chrome84
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
安装antd 4.4.x版本及以下时不会出现此bug

![D20AD6A8-8C5E-4AA0-BDF2-59FFBFFEF6B3](https://user-images.githubusercontent.com/23151576/90953926-3861f480-e4a2-11ea-9bc5-2c219fc0450b.png)

**Comment by chenshuai2144** [comment]
fixed，是 原来样式写的有问题
