### ISSUE TITLE
🐛[BUG]pro-table中如果request中有await，当params变更后不会再次触发request

### ISSUE THREAD

**Issue by trlanfeng** [ant-design/pro-components#2750]
### 🐛 bug 描述

pro-table使用params来给request传递参数，当params变更后，如果request中没有异步await操作，则request会被正常触发。
但如果request中有await操作，params变更时，第一轮的request还没有完成，request不会被再次触发。

打印结果是 log1 , params变更, log2

### 🏞 期望结果

params变更后正常触发request函数

### 💻 复现代码

```javascript
const requestParams = useMemo(() => {
  const params = {
    patientUserId: medicalCareContext.patientUserId || 0,
    orMedicalCareId: medicalCareContext.id,
  };
  console.log('params变更', params);
  return params;
}, [medicalCareContext]);

...

<ProTable
  rowKey="id"
  columns={columns}
  params={requestParams}
  request={async (params) => {
    console.log('log1');
    const res = await request('/MedicalSupport/Revisit/Page', { params });
    console.log('log2');
    return {
      data: res.data,
      success: true,
      total: res.total,
    };
  }}
/>
```

### © 版本信息

- ProComponents 版本: 2.36.0
- umi 版本: 3.4.20
- 浏览器环境: edge 90
- 开发环境: macOS

**Comment by chenshuai2144** [comment]
await不就是为了堵塞后续的请求？

**Comment by trlanfeng** [comment]
我理解的是，在request执行期间，如果params更改了，不是应该发起一次新的request吗？目前如果request还在执行，那不管params怎么变，都不会影响结果，也不会等当前request执行后再次执行

**Comment by chenshuai2144** [comment]
正在加载中不会发起加载的，不然容易多次重复调用

**Comment by hemengke1997** [comment]
> 我理解的是，在request执行期间，如果params更改了，不是应该发起一次新的request吗？目前如果request还在执行，那不管params怎么变，都不会再次执行request

把await改成 xxx.then() 就不会阻塞了

**Comment by Alt-er** [comment]
@trlanfeng 请问最后有找到解决方法吗？

**Comment by hemengke1997** [comment]
我也觉得应该是这个逻辑… 我看了源码，request传入进去后，被一个async异步函数await执行了，但是没有理解下次请求是如何阻塞掉的。 我目前的做法是不使用request，手动实现请求，控制pagination和loading。

**Comment by hemengke1997** [comment]
阻塞请求，在网速慢，或者用户操作快的情况下，就会导致ui跟数据不一致… 或许在下一次请求来，上一次还没得到结果的时候，就应该把上次请求给取消掉…

**Comment by Alt-er** [comment]
我还是先简单处理一下 ，点击按钮后延迟2秒再设置下参数，如果参数没变化protable是不会发送请求的，如果变化了说明之前的操作被打断了这时protable就会重新请求了

**Comment by hemengke1997** [comment]
![image](https://user-images.githubusercontent.com/49073282/121621786-6ea74980-ca9f-11eb-8bd5-3834fe4fdbc2.png)

**Comment by Alt-er** [comment]
@chenshuai2144 能否解决这个问题？

**Comment by trlanfeng** [comment]
> @trlanfeng 请问最后有找到解决方法吗？

我封装了一层，加了一个验证逻辑，只有验证通过才进行请求，否则直接return

**Comment by tunshiyu** [comment]
`     params={{ serviceTenantCode: serviceTenantCode }}
          options={false}
          columns={columns}
          request={async (params: any) => {
            // 表单搜索项会从 params 传入，传递给后端接口。
            if (!serviceTenantCode) return;
            const { ruleDTOList = [] } = (await ruleSearch({ ...params })) || {};
            return { data: ruleDTOList, success: true };
          }}`

我这边遇到一个类似场景。首先有个异步下拉和一个列表，下拉的值作为列表接口的type参数，并且异步下拉默认选中第一个。

所以，刚进入这个页面，需要请求下拉并且默认设置第一个。因为默认设置第一个使用的是useEffect，所以过程是serviceTenantCode从  undefined => 第一个下拉的value。由于这个变化过程很快，所以就遇到大家说的我的请求只执行一次，并且serviceTenantCode是undefined，所以我加了` if (!serviceTenantCode) return;`解决这个问题。
请问大家我这个是最佳实践吗？我总感觉怪怪的。期待讨论。

**Comment by chenshuai2144** [comment]
这个还是对的，不然就要保证 params 永远有值

**Comment by wh1teYu** [comment]
@Alt-er 

> 我也遇到了这个问题，比如用户点了按钮1将会查询id1的数据 ，还在等待数据时，用户点了按钮2这时应该查询id2的数据，但是protable直接无视了按钮2的操作，正常逻辑不应该是放弃第一次的加载，重新加载最新参数的数据吗？
> 让人疑惑的是参数修改为id2了，但是显示的数据却是之前的第一次id1的数据

这个问题，可以解决吗。我目前也是遇到此问题了

**Comment by sheben404** [comment]
@wh1teYu 可以通过设置 Protable 的 debounceTime 来解决，不过如果网络请求时间太长，还是会出现这个问题
