### ISSUE TITLE
🐛[BUG]v4暗黑模式EditableProTable设置formItemProps.rules后，字体颜色不符合预期

### ISSUE THREAD

**Issue by yongliangliu** [ant-design/pro-components#2751]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/19800207/118257324-13565b80-b4e1-11eb-9253-193984d21815.png)

**Comment by chenshuai2144** [comment]
fixed in https://github.com/ant-design/pro-components/pull/3232
