### ISSUE TITLE
🐛[BUG]ProFormText生成的input元素没有name属性

### ISSUE THREAD

**Issue by HengzheLi** [ant-design/pro-components#2753]
### 🐛 bug 描述
渲染的jsx如下:
```
<QueryFilter labelWidth="auto" onFinish={async (values)=> onFinishCallback(values)}><ProFormText name="DisplayText" {...formItemProps.props} /></QueryFilter>
```
生成的html如下:
```
<input placeholder="请输入" id="DisplayText" class="ant-input" type="text" value="">
```
### 🏞 期望结果
```
<input placeholder="请输入" name="DisplayText" id="DisplayText" class="ant-input" type="text" value="">
```
### © 版本信息
protable 1.23.0

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/118399479-e4cab300-b68f-11eb-9cab-034358b6c5b1.png)




<html>
<body>


name | 所有 | input表单控件的名字。以名字/值对的形式随表单一起提交
-- | -- | --



</body>
</html>


name 加了可能会造成表单的重复提交，antd 也是没有加的
