### ISSUE TITLE
🧐[问题] 如何让protable中的input文字从右侧输入？

### ISSUE THREAD

**Issue by ibryanwu** [ant-design/pro-components#2754]
### 🧐 问题描述
我有个Protable，行编辑的时候需要录入数字，如何设置列才能让input文字从右侧输入？另外如何把className样式写入组件中呢？

这是列设置中 一个字段
```
{
      title: "基准进价",
      dataIndex: "basePurchPrice",
      valueType: "digit",
      fieldProps: {
        className: styles.inputRight,//不行
        align:"right"// 不行
      },
    },
```
### 🚑 其他信息
请问该如何写呢？

**Comment by chenshuai2144** [comment]
你说的是 rtl 吗？


https://ant.design/components/config-provider-cn/#components-config-provider-demo-direction

**Comment by ibryanwu** [comment]
> 你说的是 rtl 吗？
> 
> https://ant.design/components/config-provider-cn/#components-config-provider-demo-direction

不是，就是有个录入数字的字段，希望可以从右侧开始输入，类似计算器那种输入方式， 比如  13.5  在input右侧录入

**Comment by jiyingzhi** [comment]
这种用 textAlign: right 应该可以

**Comment by chenshuai2144** [comment]
```tsx
fieldProps:{
 style:{
   textAlign: right
 }
}
```

**Comment by ibryanwu** [comment]
> ```tsx
> fieldProps:{
>  style:{
>    textAlign: right
>  }
> }
> ```

不起作用哇 ==!
 {
      title: "单价",
      dataIndex: "price",
      tip: "主计量单位的单价",
      key: "price",
      valueType: "digit",
      align: "right",
      width: 100,
      fieldProps: {
        style: {
          textAlign: "right",
        },
        onChange: () => {
          console.log("单价-onChange");
          calForQtyPrice();
          getEditRowData();
        },

        allowClear: false,
      },
    },

**Comment by jiyingzhi** [comment]
这个 style 没有设置在 input 上，可以用 class：
```css
.ant-input {
  text-align: right;
}
```

**Comment by chenshuai2144** [comment]
设置dir="rtl"  也可以

**Comment by ibryanwu** [comment]
@chenshuai2144 @jiyingzhi   都试了 全都不行
{
      title: "基准进价",
      dataIndex: "basePurchPrice",
      valueType: "digit",
      class: styles.inputRight,//不行
      dir: "rtl",//不行
      fieldProps: {
        className: styles.inputRight, //不行
        dir: "rtl", // 不行
      },
    },

**Comment by 0x457** [comment]
是啊，根本不起作用，无语～～

**Comment by 0x457** [comment]
input，默认的已经存在，根本透不下来
.ant-input-number-input { 
    text-align: left; 
}
