### ISSUE TITLE
模板组件是什么？

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/pro-components#2755]
https://user-images.githubusercontent.com/8186664/118386452-1f116180-b64a-11eb-8e77-90b9d4dfe8c0.mov

**Comment by hemengke1997** [comment]
大佬，这个视频看不见内容，请问是如何上传视频到issuse的？

**Comment by jiyingzhi** [comment]
github 最近加了上次音视频的功能

**Comment by hemengke1997** [comment]
> github 最近加了上次音视频的功能

issue输入框右上角没有上传按钮呀，请问在哪上传
