### ISSUE TITLE
🧐[问题]pro-list组件如何设置可编辑的字段?

### ISSUE THREAD

**Issue by jinhgg** [ant-design/pro-components#2757]
### 🧐 问题描述
点击编辑后所有字段都变成输入框,如何自定义可编辑的字段呢

### 🚑 其他信息
文档地址:https://procomponents.ant.design/components/list

![image](https://user-images.githubusercontent.com/33146207/118397878-aed60080-b688-11eb-9298-686b5ecefd0b.png)

**Comment by chenshuai2144** [comment]
<html>
<body>


editable | 在编辑表格中是否可编辑的，函数的参数和 table 的 render 一样 | false \| (text: any, record: T,index: number) => boolean | true
-- | -- | -- | --



</body>
</html>


和table的是一样的
