### ISSUE TITLE
🐛[BUG]@ant-design/pro-form@1.0.0-beta.17 轻量模式（LightFilter）不可用

### ISSUE THREAD

**Issue by hzwzw** [ant-design/pro-components#276]
### 🐛 bug 描述

@ant-design/pro-form@1.0.0-beta.17 轻量模式（LightFilter）不生效

### 💻 复现代码

https://codesandbox.io/s/frosty-chaum-u74zw
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 截图

<img width="1105" alt="Screen Shot 2020-08-22 at 12 06 09 PM" src="https://user-images.githubusercontent.com/3191122/90948318-eef8b180-e46f-11ea-8fb1-e792f4900ba7.png">

查了代码是因为给 pro-field, 传的`light: true`未生效。请查一下pro-field 最新的版本 0.0.19 是否有支持 light 属性。
谢谢！

**Comment by chenshuai2144** [comment]
竟然这么快开始用了，需要等一下，有些功能还没有完成，今天会发新版本，你说的这个问题就可以修掉了

**Comment by hzwzw** [comment]
@chenshuai2144 
谢谢，我喜欢pro-field的轻量模式，
整个查询筛选form中有些重要的item是正常模式，有些轻量的选项可以用到这个轻量模式，占的位置小，体验很好。
