### ISSUE TITLE
ProTable的columns如果单独设置一个输入框可以做校验码

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/pro-components#2760]
项目需求在表格中可以有编辑列，但是用可编辑表格的话有点多余，想问下单独设置input可以做校验码，还是需要自定义一个Form组件才可以校验
![image](https://user-images.githubusercontent.com/33271366/118422575-10808400-b6f6-11eb-9058-dbc40a87b791.png)

**Comment by chenshuai2144** [comment]
你可以用可编辑表单，然后其他列的 editor 都设置成 false，这样就能实现了

**Comment by PLUTO06210331** [comment]
我试试

**Comment by PLUTO06210331** [comment]
是可编辑表格吧，我觉得有点大材小用了哈哈

**Comment by chenshuai2144** [comment]
可以的，实现怎么简单怎么来

**Comment by PLUTO06210331** [comment]
@chenshuai2144  大佬，话说可编辑表单是什么 还有editor这个属性在哪啊 也没找到麻烦给个入口吧

**Comment by chenshuai2144** [comment]
在列配置里


editable | 在编辑表格中是否可编辑的，函数的参数和 table 的 render 一样 | false&nbsp;\|&nbsp;(text: any, record: T,index: number) =&gt; boolean | true
-- | -- | -- | --

**Comment by PLUTO06210331** [comment]
谢谢你的回复，刚看到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月23日(星期天) 中午12:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/pro-components] ProTable的columns如果单独设置一个输入框可以做校验码 (#2760)





 
在列配置里
    editable 在编辑表格中是否可编辑的，函数的参数和 table 的 render 一样 false&nbsp;|&nbsp;(text: any, record: T,index: number) =&gt; boolean true
