### ISSUE TITLE
🐛[BUG]ProForm 和 EditableTable 同时使用的编辑问题

### ISSUE THREAD

**Issue by Tracy1McGrady** [ant-design/pro-components#2761]
### 🐛 bug 描述

后台请求的数据form.setFieldsValue，表单数据都赋值上去了，EditableTable里的数据也有了，但是不会自动触发编辑，且操作栏的删除按钮也没有，只有新增一行的数据才正常
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![QQ图片20210517101649](https://user-images.githubusercontent.com/44604549/118424155-378c8500-b6f9-11eb-83bf-163451ee7bbc.png)

**Comment by Tracy1McGrady** [comment]
![image](https://user-images.githubusercontent.com/44604549/118443665-c2cc4180-b71e-11eb-8f58-ed9ffe32b911.png)
大致是这样，获取后台数据后给表单赋值后，EditableTable里的数据也有了，但是内容不可以编辑，且操作栏的删除按钮也没有，只有新增的数据才正常

**Comment by chenshuai2144** [comment]
重新 set 一下 `editablekeys`,编辑是用 editablekeys 控制的
