### ISSUE TITLE
🐛[BUG] ProForm放置在ModalForm中时layout="horizontal"不生效

### ISSUE THREAD

**Issue by tongjun741** [ant-design/pro-components#2768]
### 🐛 bug 描述
我使用了ProForm，希望Label与输入框在同一行中显示，效果如下：
![image](https://user-images.githubusercontent.com/6827111/118596663-40a35200-b7de-11eb-9778-dd655e8f919c.png)
通过在ProForm增加layout="horizontal"属性可以实现。
但如果ProForm是在ModalForm中的话就不生效了：

![image](https://user-images.githubusercontent.com/6827111/118585723-0e88f480-b7cc-11eb-9831-413b98ffb674.png)

### 💻 复现代码
https://github.com/tongjun741/ModalForm-ProForm-layout-horizontal-demo

### © 版本信息

- pro-form: 1.18.3
- umi 版本: 3.4.0
- 浏览器环境: Chrome 90.0.4430.212
- 开发环境: mac OS 10.14.6

**Comment by tongjun741** [comment]
应该是我的问题，把ModalForm换成Modal就可以了。两种Form不能混用

**Comment by t880216t** [comment]
ModalForm 的 trigger 属性挺好的，不能用可惜了。
