### ISSUE TITLE
👑 [需求] 希望能添加一个页面缓存功能

### ISSUE THREAD

**Issue by liujianchaogit** [ant-design/pro-components#2769]
### 🥰 需求描述

希望在header下面能添加一个页面缓存功能，可以直接切换页面，如图

### 🧐 解决方案

![image](https://user-images.githubusercontent.com/39163696/118645199-38b0d580-b811-11eb-8a11-d814191a082f.png)

**Comment by chenshuai2144** [comment]
我们暂时不会支持多页签，可以去 pro 搜一下做过说明的

**Comment by Aaron52077** [comment]
> 我们暂时不会支持多页签，可以去 pro 搜一下做过说明的

https://wuli-admin.gitee.io/react-antd-template/#/dashboard 个人实践
