### ISSUE TITLE
🐛[BUG] 使用可编辑表格的单行编辑模式時，無法編輯第二筆資料

### ISSUE THREAD

**Issue by KuanYinChen-Houzz** [ant-design/pro-components#2770]
### 🐛 bug 描述

使用可编辑表格的单行编辑模式時，無法編輯第二筆資料

### 📷 复现步骤

使用官方文件的 - 「自定义可编辑表格」 即可重現
https://procomponents.ant.design/components/editable-table

1. 點選 [活动名称一] 的 [编辑]
2. 點選 [活动名称一] 的 [保存]
3. 點選 [活动名称二] 的 [编辑] 此時顯示錯誤 [只能同时编辑一行]

### 🏞 期望结果

保存第一筆行後應可繼續編輯第二行資料

### © 版本信息

- ProComponents 版本: 2.37.0
- umi 版本: null
- 浏览器环境: firefox
- 开发环境: mac os

**Comment by lbjlsy** [comment]
@chenshuai2144 大佬来看看呀，在单行编辑模式的时候，我取消或者保存一行，无法编辑另外一行了

**Comment by lbjlsy** [comment]
在 useEditableArray.tsx 文件中的 cancelEditable 函数
`
   const cancelEditable = (recordKey: RecordKey) => {
    // 防止多次渲染
    ReactDOM.unstable_batchedUpdates(() => {
      /** 如果这个是 new Line 直接删除 */
      if (newLineRecord && newLineRecord.options.recordKey === recordKey) {
        setNewLineRecord(undefined);
      }
      editableKeysSet.delete(recordKeyToString(recordKey));
      setEditableRowKeys(Array.from(editableKeysSet));
      console.log(recordKeyToString(recordKey), '123')
      console.log(editableKeysSet.size, 'editableKeysSet.size cancel after')
    });
    return true;
  };
`
这段代码中这两行代码调用之后
`
    editableKeysSet.delete(recordKeyToString(recordKey));
    setEditableRowKeys(Array.from(editableKeysSet));
`
在下一次 startEditable 函数调用的时候，editableKeysSet还保存着上一次缓存的key，导致在 editableType 为 single 的时候判断条件还有一行正在编辑中。

使用的是 render 函数内的 action 调用编辑的 startEditable 函数

**Comment by lbjlsy** [comment]
使用 actionRef 调用 startEditable 函数之后，表格表现正常

**Comment by Chastrlove** [comment]
@chenshuai2144 bug依旧存在

**Comment by chenshuai2144** [comment]
注意下你的key不要重复

**Comment by Chastrlove** [comment]
> 注意下你的key不要重复

id是随机生成,应该不存在重复的吧
