### ISSUE TITLE
🐛[BUG]问题反复了，<EditableProTable> 中配置列为select类型后，用optionFilterProp 指定options中对象的任意属性，过滤又不起作用了

### ISSUE THREAD

**Issue by ibryanwu** [ant-design/pro-components#2771]
### 🐛 bug 描述

这两天更新了组件，之前bug又反复了，
原问题描述：
EditableProTable中配置列为select类型后，用optionFilterProp 指定options中的query属性（query是我自己定义用做模糊查询）作为查询字段，而不是默认”Label“，之前改了，现在又不起作用了，麻烦帮忙看下，谢谢了 

之前Bug链接 请参考
(https://github.com/ant-design/ant-design-pro/issues/8136)
https://github.com/ant-design/ant-design-pro/issues/8136
### 📷 复现步骤
```
{
      title: "商品",
      width: 300,
      dataIndex: "productId",
      key: "productId",
      align: "left",
      ellipsis: true,
      valueType: "select",
      valueEnum: productValueEnum,
      formItemProps: {
        rules: [
          {
            required: true,
            message: "此项为必填项",
          },
        ],
        fixed: "left",
      },
      // 改变商品值的计算
      fieldProps: {
        allowClear: false,
        defaultActiveFirstOption: true,
        showSearch: true,
        //filterOption: false,
        **options: productRefSelectOption,
        optionFilterProp: "query", // 注：指定模糊过滤的字段**
        onFocus: (value, option) => {
          setRow(value, option, editableKeys);
        },
        onSelect: (_, option) => {
          console.log("商品变化", option);
          productResetField(); 
          getAidQtyDisable(); //判断是否开启辅数量
          
          getEditRowData();
        },
      },
    },
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
` optionFilterProp: "query",` 设置了自定义的filer参数就要自定义 filter的方法了，不能用自带的了

**Comment by ibryanwu** [comment]
> ` optionFilterProp: "query",` 设置了自定义的filer参数就要自定义 filter的方法了，不能用自带的了
> 
> filterOption	是否根据输入项进行筛选。当其为一个函数时，会接收 inputValue option 两个参数，当 option 符合筛选条件时，应返回 true，反之则返回 false	boolean | function(inputValue, option)	true

老大，你的方案应该只适用于 按Label 做过滤，我如果想按option中的query字段做过滤 是不行的! 我验证过很多次，确实有问题
，如果设置成我自己的query字段，还是先按label过滤
fieldProps: {
        allowClear: false,
        defaultActiveFirstOption: true,
        showSearch: true,
        optionFilterProp: "query", // 注：query是我自己加到options对象中的一个查询属性，比如query值为label的拼音首字母
        filterOption: (inputValue, option) => {
          if (option.query.includes(inputValue)) {   //注意，这里我使用了option.query.  是不起作用的，换句话说filterOption没起作用
            console.log("filterOption==============", option);
            return true;
          } else return false;
          // return option.query.includes("。。。。");
        },


验证过很多次，请您再看看是不是bug，谢谢了

**Comment by chenshuai2144** [comment]
console 一下 filterOption ，默认的 filterOption  的会覆盖掉我们的。

建议用 prettier，你的排版有点奇怪

**Comment by ibryanwu** [comment]
> console 一下 filterOption ，默认的 filterOption 的会覆盖掉我们的。

没太明白，如何避免filterOption 被默认的覆盖呢？或者我那里写的不对？  我这里商品上千种 ，靠商品拼音首字母做检索，这个不是selectOption 中的value也不是label，是我自己加的query字段，现在只能过滤label中的内容，非常麻烦，请帮忙解决一下谢谢了 @chenshuai2144 
`{
      title: "商品",
      width: 300,
      dataIndex: "productId",
      key: "productId",
      align: "left",
      ellipsis: true,
      valueType: "select",
      //valueEnum: productValueEnum,
      formItemProps: {
        rules: [
          {
            required: true,
            message: "此项为必填项",
          },
        ],
        fixed: "left",
      },
      // 改变商品值的计算
      fieldProps: {
        allowClear: false,
        defaultActiveFirstOption: true,
        showSearch: true,
        optionFilterProp: "query", // 注：我需要制定query为过滤的字段
        options: productRefSelectOption,
        filterOption: (inputValue, option) => {
          if (option.query.includes(inputValue)) {
            //console.log("filterOption==============", option);
            return true;
          } else return false;
          // return option.query.includes("。。。。");
        },

        onFocus: (value, option) => {
          setRow(value, option, editableKeys);
        },
        onSelect: (_, option) => {
          console.log("商品变化", option);
         
        },
      },
    },`

**Comment by chenshuai2144** [comment]
你用 select 来试试

**Comment by ibryanwu** [comment]
解决了，之前没往renderFormItem 上面想。。。。  多谢了
