### ISSUE TITLE
🧐[问题]如何在FieldPassword中监听onChange事件

### ISSUE THREAD

**Issue by ZhangXY-Magic** [ant-design/pro-components#2772]
### 🧐 问题描述
业务对密码输入有复杂度提示的需求，需要在FieldPassword监听onChange事件判断value的密码复杂度，若在FieldPassword中键入onChange监听，则在表单校验时会取不到值

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/25630228/118699812-901c6900-b844-11eb-9356-8b7e5d347be9.png)
![image](https://user-images.githubusercontent.com/25630228/118699953-b04c2800-b844-11eb-9313-2857be4337c4.png)
![image](https://user-images.githubusercontent.com/25630228/118700085-db367c00-b844-11eb-9860-fa8d5a3cc15f.png)

**Comment by ZhangXY-Magic** [comment]
![image](https://user-images.githubusercontent.com/25630228/118743160-684cf580-b884-11eb-96ac-b6e91484afa2.png)
这样可以解决 不清楚符不符合设计

**Comment by chenshuai2144** [comment]
试试在 filedProps 中配置 onchange ，这样可以兼顾
