### ISSUE TITLE
editableProtable我不想要这种tooltips了

### ISSUE THREAD

**Issue by JackRoy1992** [ant-design/pro-components#2774]
表单全部校验不通过时，所有的tooltips都展示，样式重叠覆盖，很丑，能只标红，我自己给提示

**Comment by JackRoy1992** [comment]
![企业微信截图_20210519132820](https://user-images.githubusercontent.com/49305419/118762335-9a704e80-b8a8-11eb-8a25-64556fe20880.png)

**Comment by chenshuai2144** [comment]
升级最新版本，他想不会自动跑出来提示你了
