### ISSUE TITLE
👑 [需求] EditableProTable设置disabled

### ISSUE THREAD

**Issue by smile2233514516** [ant-design/pro-components#2778]
### 🥰 需求描述
部分情况下，后面的表单数据是根据第一个FormItem选择之后自动填入，不允许用户进行输入，

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/50870976/118783611-ce0ba280-b8c1-11eb-9ae8-bac24109de6a.png)
![image](https://user-images.githubusercontent.com/50870976/118783643-d532b080-b8c1-11eb-988c-5faed9b0254a.png)

**Comment by smile2233514516** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [#1942][🧐[问题]EditableProTable可编辑表格设置必填项][62%]
no

**Comment by jiangyh1024** [comment]
renderFormItem 自定义 目前看来 只能

**Comment by smile2233514516** [comment]
> renderFormItem 自定义 目前看来 只能

....，那也太难了吧

**Comment by jiangyh1024** [comment]
不难 我也有这种情况
我是这样写的
![image](https://user-images.githubusercontent.com/34930870/118787160-209a8e00-b8c5-11eb-80f3-c216afc80ec0.png)

![image](https://user-images.githubusercontent.com/34930870/118787319-4d4ea580-b8c5-11eb-95b6-c88d7c75f915.png)

**Comment by jiangyh1024** [comment]
你那种就 把后面几个 写成readonly就行了

**Comment by smile2233514516** [comment]
> 你那种就 把后面几个 写成readonly就行了

readonly这参数写在哪

**Comment by smile2233514516** [comment]
> 不难 我也有这种情况
> 我是这样写的
> ![image](https://user-images.githubusercontent.com/34930870/118787160-209a8e00-b8c5-11eb-80f3-c216afc80ec0.png)
> 
> ![image](https://user-images.githubusercontent.com/34930870/118787319-4d4ea580-b8c5-11eb-95b6-c88d7c75f915.png)

你这样写好棒，我写的比较粗糙一些 了，我照这个改一下

**Comment by jiangyh1024** [comment]
RenderFormItem 里面 自己 return <Input />  就可以写 readonly了  不过要记得 对datasource 和 form 赋值 来更新这些数据

**Comment by smile2233514516** [comment]
> RenderFormItem 里面 自己 return input 就可以写 readonly了 不过要记得 对datasource 和 form 赋值 来更新这些数据

哦哦那还是自己做了，就想着有个这个参数，偷懒一下，哈哈哈
