### ISSUE TITLE
🧐[问题]  想做一个代码生成器，在前端有那种模板引擎没？像后端的velocity， 用来生成代码

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#2781]
### 🧐 问题描述

 想做一个代码生成器，在前端有那种模板引擎没？像后端的velocity， 用来生成代码。

```
Velocity是一个基于Java的模板引擎，通过特定的语法，Velocity可以获取在java语言中定义的对象，从而实现界面和java代码的真正分离，这意味着可以使用velocity替代jsp的开发模式了(实际上笔者所在的公司已经这么做了)。这使得前端开发人员可以和 Java 程序开发人员同步开发一个遵循 MVC 架构的 web 站点，在实际应用中，velocity还可以应用于很多其他的场景.
```
![qqq](https://user-images.githubusercontent.com/34436863/118811679-dd99e400-b8df-11eb-825d-94eb7614d7e7.png)

**Comment by chenshuai2144** [comment]
现在其实没什么好的方案。你可能要自己搭建一个。

我这里人力不是很够，做这个东西很难

**Comment by fanhualei** [comment]
看到网上推荐了这几个模板引擎，想问一下那个好用。

```
1. Art-template
2. DOT
3. JavaScript-Templates
4. Template.js
5. Tempo
6. ECT
7. Dot Dom
8. Template7
9. Bunny
10. Squirrelly
```



我的代码生成器是给自己用的，想到那里就做到那里，以减少工作量为主，让那些重复的工作，用生成器自动生成。



另外我从哪没有想做一个完整的、通过的代码生成器。 一个是开发难度比较大，另外一个是生成的代码，不是那么好维护。



我采取的策略是70%自动生成，个性化的，手工优化的，就自己写代码。

所以我主要做下面三方面，自动生成：

* data.ts 数据结构
* service接口
* 一些基本的框架页面
* pro中的Column
  * 每次定义column都很烦，因为重复的工作太多了。
  * Pro把column做成跨组件化了，给后台代码生成提供更多的便利，这点要点赞

**Comment by fanhualei** [comment]
舍近求远了，react就是一个模板引擎。下面是生成的service代码
![aaa](https://user-images.githubusercontent.com/34436863/119093289-1ce04600-ba42-11eb-931e-b1ae2489c7b2.png)
