### ISSUE TITLE
🐛[BUG] StepsForm无法获取到formRef

### ISSUE THREAD

**Issue by sondoh** [ant-design/pro-components#2784]
### 🐛 bug 描述

官方demo中分布表单初次提交时无法获取到formRef，得到的为undefined
https://procomponents.ant.design/components/steps-form/#%E5%88%86%E6%AD%A5%E8%A1%A8%E5%8D%95
![image](https://user-images.githubusercontent.com/36026840/118911094-35743180-b958-11eb-9c99-158128ccf845.png)

### 📷 复现步骤

录入必填项，点击“下一步“按钮
![image](https://user-images.githubusercontent.com/36026840/118911158-550b5a00-b958-11eb-9392-22d939631384.png)

### 🏞 期望结果
可获取到formRef

### 💻 复现代码
https://procomponents.ant.design/components/steps-form/#%E5%88%86%E6%AD%A5%E8%A1%A8%E5%8D%95

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by my9988** [comment]
希望完善StepsForm的BUG
