### ISSUE TITLE
这是缓存的原因吗，怎么清除呀

### ISSUE THREAD

**Issue by Tz2318387771** [ant-design/pro-components#2785]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/48540843/118911484-d4009280-b958-11eb-8516-4d8cd8c67147.png)
![image](https://user-images.githubusercontent.com/48540843/118911707-3a85b080-b959-11eb-82d7-a45d9d5742db.png)

如图，在“列表显示”下点击新增后，直接切换tab至“查询配置”，再切换到“列表显示”，会出现这个问题，试了reload等api都不行呀

**Comment by chenshuai2144** [comment]
是编辑状态被清楚了，应该是数据回滚了
