### ISSUE TITLE
🧐[问题]1、ProFormUploadButton与ImgCrop搭配使用问题？

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#2788]
### 🧐 问题描述

1、根据ImgCrop使用方式，直接嵌套住ProFormUploadButton没作用。

2、改用 Form.Item>ImgCrop>Upload 方式使用 ImgCrop，在 ProForm 中不显示。

引入了CSS文件
![image](https://user-images.githubusercontent.com/12421552/118913868-d95fdc00-b95c-11eb-98c8-c666c19636d0.png)
代码如图
![image](https://user-images.githubusercontent.com/12421552/118913891-e54b9e00-b95c-11eb-8721-f99b56b60ee7.png)
效果如图
![image](https://user-images.githubusercontent.com/12421552/118913939-f8f70480-b95c-11eb-8282-cafcf00a735c.png)

**Comment by edifangyi** [comment]
问题2 找到原因了，没有在 Upload 中 添加显示列表

**Comment by chenshuai2144** [comment]
ProFormUploadButton 和 ImgCrop 看起来不能嵌套。ProFormUploadButton 是个 formItem 不是Upload。你还是先用 antd 的方式吧
