### ISSUE TITLE
pro-table 设置 pagination={false} 不需要分页时，请求数据不需要带参数current，pageSize

### ISSUE THREAD

**Issue by meijuji202** [ant-design/pro-components#279]
pro-table 设置 pagination={false} 不需要分页时，请求数据不需要带参数current，pageSize

**Comment by chenshuai2144** [comment]
来个 pr？

**Comment by LeeHarlan** [comment]
设置 pagination 的 pageSize 属性也不起作用
```
pagination={{ pageSize: 10 }}
```

**Comment by meijuji202** [comment]
> 设置 pagination 的 pageSize 属性也不起作用
> 
> ```
> pagination={{ pageSize: 10 }}
> ```
pagination={{ defaultPageSize: 10 }}

**Comment by LeeHarlan** [comment]
> > 设置 pagination 的 pageSize 属性也不起作用
> > ```
> > pagination={{ pageSize: 10 }}
> > ```
> 
> pagination={{ defaultPageSize: 10 }}

看了下源码，才发现还有一个 defaultPageSize，设置这个才起作用

**Comment by zhushenhang** [comment]
找到答案了，感谢！

**Comment by biel-fyq** [comment]
分页没有做到置底的操作吗?要自己写样式固定分页在底部吗?应该如何去写呢?方案一:直接操作dom,方案二:自己写分页,然后分页组件置底,哪一种方法好一点呢?
