### ISSUE TITLE
🧐[问题]Antd config.ts  layout 中的name如何支持I18n?

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#2790]
Antd layout 中的name如何支持I18n?
//  file: config.ts
  layout: {
    name: "Auto ML",
    locale: true,
    siderWidth: 208,
  },

**Comment by chenshuai2144** [comment]
在 app.tsx 中，用运行时配置就能使用 dom 了
https://beta-pro.ant.design/config/runtime-api-cn#layout
