### ISSUE TITLE
🧐[问题] EditableProTable 中如何点击某个文本框 选中全部文字?

### ISSUE THREAD

**Issue by ibryanwu** [ant-design/pro-components#2791]
### 🧐 问题描述
EditableProTable 中如何点击某个文本框 选中全部文字?

我在定义column的时候该如何写 ？

{
      title: "数量",
    
      dataIndex: "qty",
      key: "qty",
      valueType: "digit",
      align: "right",
      width: 100,
      allowClear: false,
      fieldProps: {
        onFocus://点击后进入文本框，默认选中全部文字，该怎么 写？？？？？？？？
      },
    },

**Comment by shirley5li** [comment]
可以试试下面的方式
```js
{
  title: "数量",
  dataIndex: "qty",
  key: "qty",
  valueType: "digit",
  align: "right",
  width: 100,
  allowClear: false,
  render: (text, record, index, action) => (
     <div onClick={() => action?.startEditable?.(record.id)}>{record.qty}</div>
  ),
  fieldProps: {
     onMouseOver: (e) => {
          e?.target?.focus?.();
          e?.target?.select?.();
      },
  },
},
```

**Comment by ibryanwu** [comment]
> 可以试试下面的方式
> 
> ```js
> {
>   title: "数量",
>   dataIndex: "qty",
>   key: "qty",
>   valueType: "digit",
>   align: "right",
>   width: 100,
>   allowClear: false,
>   render: (text, record, index, action) => (
>      <div onClick={() => action?.startEditable?.(record.id)}>{record.qty}</div>
>   ),
>   fieldProps: {
>      onMouseOver: (e) => {
>           e?.target?.focus?.();
>           e?.target?.select?.();
>       },
>   },
> },
> ```

搞定了 ，流泪感谢 ！！！！！！
