### ISSUE TITLE
🐛[BUG] editableKeys为所有数组keys的情况下, EditableProTable组件的value改变后, UI未渲染

### ISSUE THREAD

**Issue by CaicoLeung** [ant-design/pro-components#2792]
### 🐛 bug 描述

EditableProTable组件的value改变后, 表格UI的数据没改变

### 📷 复现步骤

EditableProTable的value接收数组变量datasource, editableKeys为datasource的所有id时, datasource改变, UI数据没有变化

### 🏞 期望结果

EditableProTable的UI数据和接收的value同步

### 💻 复现代码

仓库: https://github.com/CaicoLeung/pro-component-bug.git

### © 版本信息

- ProComponents 版本: [2.35.1]
- umi 版本 [3.2.14]
- 浏览器环境 [Google Chrome 91]
- 开发环境 [mac OS]

**Comment by CaicoLeung** [comment]
> ### 🐛 bug 描述
editableKeys为所有数组keys的情况下, EditableProTable组件的value改变后, UI未渲染
> ### 📷 复现步骤
EditableProTable的value接收数组变量datasource, editableKeys为datasource的所有id时, datasource改变, UI数据没有变化
> ### 🏞 期望结果
> EditableProTable的UI数据和接收的value同步
> 
> ### 💻 复现代码
> 仓库: https://github.com/CaicoLeung/pro-component-bug.git
> 
> ### © 版本信息
> * ProComponents 版本: [2.35.1]
> * umi 版本 [3.2.14]
> * 浏览器环境 [Google Chrome 91]
> * 开发环境 [mac OS]
> 
> ### 🚑 其他信息

**Comment by chenshuai2144** [comment]
已经删除缓存，更新依赖后解决

**Comment by CaicoLeung** [comment]
我更新了@ant-design/pro-table至最新版本, 还是有问题呀, 复现代码仓库我已更新

**Comment by CaicoLeung** [comment]
> 已经删除缓存，更新依赖后解决

我更新@ant-design/pro-table至最新版了, 但是还有老问题; 复现代码的仓库依赖我已更新

**Comment by chenshuai2144** [comment]
要这个版本

**Comment by CaicoLeung** [comment]
> 要这个版本
> 
> https://www.npmjs.com/package/@ant-design/pro-table

已经是这个版本了, 问题仍未解决
![image](https://user-images.githubusercontent.com/36806569/119306873-6aa4ba80-bc9d-11eb-9a67-92e34e5bcb95.png)

**Comment by chenshuai2144** [comment]
你要调用下 form.set了

**Comment by CaicoLeung** [comment]
> 你要调用下 form.set 了
> 
> table 的 form 是两个系统，不互通，form 也不支持全受控模式

这个方法我也试过, 但是也没有效果; 非editable状态下的cell才有效, form cell都无效;
![image](https://user-images.githubusercontent.com/36806569/119450992-4ca38c80-bd67-11eb-932b-b6df5cb23bb0.png)

**Comment by xclw2000** [comment]
我也遇到了这个问题，当所有行都处于编辑状态下时，修改EditableProTable的value,界面上不会更新，我写了一个重现代码
[https://codesandbox.io/s/shishibaocundebianjibiaoge-forked-8ndgu](url)
在只读模式下，点击修改数据，可以看到表格里的数据是变的，在编辑模式下，点击修改数据，界面上没有变化，实际上数据已经变了

**Comment by CaicoLeung** [comment]
> 我也遇到了这个问题，当所有行都处于编辑状态下时，修改EditableProTable的value,界面上不会更新，我写了一个重现代码
> 
> [https://codesandbox.io/s/shishibaocundebianjibiaoge-forked-8ndgu](url)
> 
> 在只读模式下，点击修改数据，可以看到表格里的数据是变的，在编辑模式下，点击修改数据，界面上没有变化，实际上数据已经变了

我记得后面修复了，你更新依赖版本至最新试试

**Comment by chenshuai2144** [comment]
需要打开受控模式 因为form和value不是完全对应的 不然你多行编辑肯定会被覆盖掉数据

**Comment by xclw2000** [comment]
> 需要打开受控模式 因为form和value不是完全对应的 不然你多行编辑肯定会被覆盖掉数据

怎么打开受控模式，你看一下我发的codesandbox的代码，能改一下例子出来吗？

**Comment by xclw2000** [comment]
> > 我也遇到了这个问题，当所有行都处于编辑状态下时，修改EditableProTable的value,界面上不会更新，我写了一个重现代码
> > [https://codesandbox.io/s/shishibaocundebianjibiaoge-forked-8ndgu](url)
> > 在只读模式下，点击修改数据，可以看到表格里的数据是变的，在编辑模式下，点击修改数据，界面上没有变化，实际上数据已经变了
> 
> 我记得后面修复了，你更新依赖版本至最新试试

已经升级到2.41.0，问题依旧

**Comment by tong233** [comment]
我也遇到了，单独使用EditableProTable开启受控模式，修改value也没有重新渲染，版本"@ant-design/pro-table": "^2.42.1"

**Comment by tong233** [comment]
加这个属性就可以了，controlled | 是否受控, 如果受控每次编辑都会修改 dataSource

**Comment by xclw2000** [comment]
> 加这个属性就可以了，controlled | 是否受控, 如果受控每次编辑都会修改 dataSource

果然是这样, 谢谢
结单！！！
