### ISSUE TITLE
🐛[BUG] EditTable valueType 设置 date类型，保存得到的结果是 'YYYY-MM-DD HH:mm:ss'

### ISSUE THREAD

**Issue by poyiding** [ant-design/pro-components#2793]
### 📷 复现步骤
EditTable valueType 设置 date类型，正常应该是 'YYYY-MM-DD' ，结果是 'YYYY-MM-DD HH:mm:ss'
初步排查是zhe这行代码问题
![image](https://user-images.githubusercontent.com/15643321/118938939-c0b5ed00-b981-11eb-9611-ba0ce3de044a.png)

### 🏞 期望结果
返回正常的日期类型格式

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/15643321/118938647-759bda00-b981-11eb-8e3b-8e2eaa14fed6.png)

**Comment by hui5** [comment]
上面提到的格式转换，大部分情况下，是在点击查询、保存按钮时做的 ， 像form的保存
 `          const finalValues = transformKey(formRef.current.getFieldsValue(), omitNil);
                  await rest.onFinish(finalValues);`
在可编辑表格， onSave, onCancel ,里面也会有转换。
中间都是以 moment对象存在 ，  上面console， 是不是在这个时候打出来的？  

onValuesChange， onChange  里面应该是没有转换， 不知道，这是不是有意为之？

**Comment by hui5** [comment]
这个我昨天试了一下，  在 table  cellRenderToFromItem文件里，  在 ` <Form.Item`   外面包一下， ProFormFieldContext  是form里面的FieldContext，上面的日期是会正常装换的。
```
    const FromItemWrapper = ({ name, valueType, children }) => {
      const { setFieldValueType } = React.useContext(ProFormFieldContext);
      if (setFieldValueType && name) {
        setFieldValueType(name, {
          valueType: (valueType as any) || 'text',
        });
      }
      return children;
    };
```

**Comment by hui5** [comment]
@chenshuai2144   昨天看代码，日期转换， form 的所有数据出口都要转换， 进入 Form.Item 前也要设置valueType， 相关的Context 就有两个。

如果日期组件的 onChange，出来的值就是转换过的， 就不需要上面的逻辑了 ， 也不容易出问题   ?
