### ISSUE TITLE
👑 [需求]如何自定义或增加query-filter轻量筛选弹出输入项的footer内容？

### ISSUE THREAD

**Issue by birdycn** [ant-design/pro-components#2794]
![image](https://user-images.githubusercontent.com/32201961/118939317-21452a00-b982-11eb-9864-95a02bfaa554.png)

如图，有一个清除的按钮，想增加其他文字功能，应该在哪里设置？

**Comment by mouthguo** [comment]
看起来没提供额外修改，只处理了[事件](https://github.com/ant-design/pro-components/blob/master/packages/form/src/BaseForm/LightWrapper/index.tsx#L124-L130)
