### ISSUE TITLE
🐛[BUG] modalForm的setFieldsValue无效。

### ISSUE THREAD

**Issue by wanglianjie91** [ant-design/pro-components#2795]
### 🐛 bug 描述

modalForm的setFieldsValue无效。
### 💻 复现代码
const UpdateForm: React.FC<updateFormProps> = ({ visible, onCancel, onSubmit, defaultFields }) => {
  const formRef = useRef<any>();

  useEffect(()=>{
    formRef?.current?.setFieldsValue(defaultFields)
  }, [defaultFields]);

  return (
    <ModalForm
      title="修改标签"
      visible={visible}
      modalProps={{
        onCancel,
        destroyOnClose: true,
        width: 500
      }}
      formRef={formRef}
      onFinish={async (values) => {
        onSubmit(values);
      }}
    >
      <ProFormText name="id" hidden />
      <ProFormText width="lg" name="name" label="名称" placeholder="请输入名称" />
      <ProFormText width="lg" name="keywords" label="关键字" placeholder="请输入关键字" />
      <ProFormText width="lg" name="description" label="描述" placeholder="请输入描述" />
    </ModalForm>
  );
};

### © 版本信息

- @ant-design/pro-form 版本: [^1.3.0]
- umi 版本 3.4.21
- 浏览器环境 chrome stable
- 开发环境 [mac OS]

**Comment by ibandeng** [comment]
请问是怎么解决的？

**Comment by chenshuai2144** [comment]
用 initialValues 设置
