### ISSUE TITLE
ProTable copyable:true,ellipsis: true,使用render后，copyable无效，ellipsis无效,（必须使用render，dataIndex不满足需求）

### ISSUE THREAD

**Issue by wyg2103** [ant-design/pro-components#2796]
![image](https://user-images.githubusercontent.com/17972908/118960985-683d1a80-b996-11eb-9559-9d68afacdb76.png)

**Comment by chenshuai2144** [comment]
如果只是想修改文案 用 renderText， render 需要自定义任何东西包括 copyable 和 ellipsis
