### ISSUE TITLE
🐛[BUG] ProCard 排版錯誤

### ISSUE THREAD

**Issue by KuanYinChen-Houzz** [ant-design/pro-components#2799]
### 🐛 bug 描述
官網 - 基础卡片

<img width="518" alt="截圖 2021-05-20 下午9 32 09" src="https://user-images.githubusercontent.com/76982730/118987441-d7286c80-b9b2-11eb-8f97-809bf3580158.png">

Codesandbox - 基础卡片

<img width="1480" alt="截圖 2021-05-20 下午9 32 40" src="https://user-images.githubusercontent.com/76982730/118987516-e90a0f80-b9b2-11eb-8828-0527a162abaf.png">

### 📷 复现步骤

打開官方提供的 codesandbox 即可呈現 https://codesandbox.io/s/dqn0f

### 🏞 期望结果

<img width="518" alt="截圖 2021-05-20 下午9 32 09" src="https://user-images.githubusercontent.com/76982730/118987441-d7286c80-b9b2-11eb-8f97-809bf3580158.png">

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] @ant-design/pro-card 1.12.0
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by mouthguo** [comment]
这个问题之前也有人提过，好像才做了合并 #2783

**Comment by KuanYinChen-Houzz** [comment]
我在本地端也有一樣的問題，也是跟引入 CSS 有關嗎？

**Comment by KuanYinChen-Houzz** [comment]
目前手動引入 css 可解決
`import '@ant-design/pro-card/dist/card.css'`

**Comment by chenshuai2144** [comment]
先手动引入一下吧，有空我发一下官网
