### ISSUE TITLE
🐛[BUG]pro-table 时间范围选择筛选，placeholder显示有问题

### ISSUE THREAD

**Issue by zhupp034** [ant-design/pro-components#2802]
### 🐛 bug 描述

pro-table 时间范围选择筛选，设置为时间范围筛选类型，显示的placeholer有问题，第一个框显示请，dierg第二个显示输

### 📷 复现步骤
pro-table 时间范围选择筛选，设置为时间范围筛选类型

### 🏞 期望结果

显示开始时间-结束时间placeholder

### 💻 复现代码

![image](https://user-images.githubusercontent.com/33925263/119075754-ee537280-ba23-11eb-8305-dcaace0e3799.png)

在2.34.0之后的版本都能复现，我看那个版本日志有修复valueType

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]
pro-table版本2.36.0版本

### 🚑 其他信息

在2.34.0之前正常

**Comment by chenshuai2144** [comment]
看了下不能复现，你应该是自己设置了  placeholder

**Comment by zhupp034** [comment]
> 看了下不能复现，你应该是自己设置了 placeholder
> 
> https://procomponents.ant.design/~demos/table-single?current=1&pageSize=5
> 
> 看看这个demo

https://codesandbox.io/s/chaxunbiaoge-forked-ugsi4?file=/App.tsx 这是重现demo
自定义了渲染
![image](https://user-images.githubusercontent.com/33925263/119301702-7ab89c00-bc95-11eb-97b2-5b750af97b79.png)

**Comment by zhupp034** [comment]
> 看了下不能复现，你应该是自己设置了 placeholder
> 
> https://procomponents.ant.design/~demos/table-single?current=1&pageSize=5
> 
> 看看这个demo

![image](https://user-images.githubusercontent.com/33925263/119301748-8c01a880-bc95-11eb-911c-5d417b8ba383.png)

**Comment by chenshuai2144** [comment]
你自定义的就自己处理，table 不知道你 renderFormItem 返回的是什么

**Comment by edifangyi** [comment]
{
      title: '日期',
      dataIndex: 'releaseDate',
      hideInTable: true,
      valueType: 'dateRange',
      renderFormItem: (item, { type, defaultRender, ...rest }, form) => {
        return (
          <DatePicker.RangePicker
            picker="month"
            placeholder={["开始月份","结束月份"]} />
        );
      },
    },
