### ISSUE TITLE
🐛[BUG] ProFormDigit在readonly下格式化展示无效果

### ISSUE THREAD

**Issue by zlllya** [ant-design/pro-components#2804]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/6331020/119078079-147b1180-ba28-11eb-9c5b-0724bab0c742.png)
ProFormDigit配置格式化展示，没有设置readonly的时候与期望相符，设置readonly后，则格式化效果没有了

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/6331020/119078308-84899780-ba28-11eb-915b-0ad90ba4f289.png)
未配置readonly状态

![image](https://user-images.githubusercontent.com/6331020/119078332-8eab9600-ba28-11eb-9d41-e00101614f9b.png)
配置readonly状态

### 🏞 期望结果

![image](https://user-images.githubusercontent.com/6331020/119078420-bc90da80-ba28-11eb-96d4-ea3286a48d51.png)
配置readonly也能显示格式化部分

### 💻 复现代码

官网相关展示例子可复现

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
使用render自定义一下吧，digit 格式化功能只支持数字 

1000 会格式化为 1,000
