### ISSUE TITLE
🐛[BUG] Stepsform not accepting locale from configprovider

### ISSUE THREAD

**Issue by ajayar** [ant-design/pro-components#2805]
### 🐛 bug 描述
Even after setting the locale in configprovider to enUS, the Stepsform next and prev buttons labels are displaying default Chinese text. 

below is the code...

```
import { ConfigProvider } from "antd";
import enUS from "antd/lib/locale/en_US";
import ProForm, { StepsForm } from "@ant-design/pro-form";
<ConfigProvider locale={enUS}>
	<StepsForm> .... </StepsForm>
</ConfigProvider>
```

**Comment by AbderrazzakB** [comment]
> ### 🐛 bug 描述
> Even after setting the locale in configprovider to enUS, the Stepsform next and prev buttons labels are displaying default Chinese text.
> 
> below is the code...
> 
> ```
> import { ConfigProvider } from "antd";
> import enUS from "antd/lib/locale/en_US";
> import ProForm, { StepsForm } from "@ant-design/pro-form";
> <ConfigProvider locale={enUS}>
> 	<StepsForm> .... </StepsForm>
> </ConfigProvider>
> ```

I have the same issue, did you found any solution?

**Comment by AbderrazzakB** [comment]
Hi @chenshuai2144,  the Stepsform next and prev buttons labels are still displaying default Chinese text, even after settings the locale to enUS.
I did reproduce the issue at this [github repo](https://github.com/AbderrazzakB/reproduce-antd-pro-form-issue-2805)

**Comment by ajayar** [comment]
While the buttons got fixed but the placeholders are still in Chinese  

![image](https://user-images.githubusercontent.com/2200669/121362577-d0f33380-c953-11eb-9d33-df92cc0ec26e.png)

**Comment by ajayar** [comment]
same problem exists with this button text too

![image](https://user-images.githubusercontent.com/2200669/121363197-5676e380-c954-11eb-9114-d0e35b721382.png)
