### ISSUE TITLE
🐛[BUG] Protable删除

### ISSUE THREAD

**Issue by jiangyh1024** [ant-design/pro-components#2808]
步骤

1. 创建11条数据 分页是每页10条
2. 跳到第二页 - 此时显示一条数据
3. 删除该数据 调用actionRef.current.reload()

这时 request里面的 param 的 current 依旧是2  而不是1

**Comment by jiangyh1024** [comment]
上面 自动提示的 没有相关的

**Comment by jiangyh1024** [comment]
应该要我自己处理 先关了

**Comment by chenshuai2144** [comment]
试试 reloadAndRest
