### ISSUE TITLE
🐛[BUG]使用renderFormItem，值改变的时候已调用form.submit()，但是没有触发新的更新

### ISSUE THREAD

**Issue by hp725** [ant-design/pro-components#2810]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by hp725** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [#2809][🐛[BUG]使用renderFormItem，值改变的时候已调用form.submit()，但是没有触发新的更新][100%]

这个bug也是我提的，格式不正确被你们强行关闭了

**Comment by chenshuai2144** [comment]
试着更新一下最新版，最新版本去掉了 性能优化

**Comment by chenshuai2144** [comment]
> 这个bug也是我提的，格式不正确被你们强行关闭了

是机器人，没必要跟机器人怄气，前几天有人和机器人吵架。。。
