### ISSUE TITLE
🐛[BUG] 构建出来的产物自动引入了 antd 的样式

### ISSUE THREAD

**Issue by liuweiGL** [ant-design/pro-components#2811]
### 🐛 bug 描述
@ant-design/layout 包构建出来的产物自动引入了 antd 的样式，在不使用 antd 的默认主题时（比如 compact ）导致样式重复加载，并且会带来副作用（样式覆盖）。

![image](https://user-images.githubusercontent.com/21048878/119229186-4cc64100-bb49-11eb-94a1-ccb5dd010732.png)

### 📷 复现步骤

查看 @design/layout/es/components 下的构建产物。

### 🏞 期望结果

不要自动引入 antd 的样式。

### © 版本信息

```node
 "@ant-design/pro-layout": "^6.18.2"
```

**Comment by chenshuai2144** [comment]
这个是故意的，为了减少使用成本

不然老有人问，为什么样式没了

**Comment by shiye515** [comment]
> 这个是故意的，为了减少使用成本
> 
> 不然老有人问，为什么样式没了

@chenshuai2144 这样本来自定义的主题都失效了

**Comment by rhyme97** [comment]
> 

找了一下午问题，原来这样。。，现在看起来即使配置了antd的主题，但还是要手写覆盖procomponent的样式。

**Comment by rhyme97** [comment]
> 

找了一下午问题，原来这样。。，现在看起来即使配置了antd的主题，但还是要手写覆盖procomponent的样式。

**Comment by liuweiGL** [comment]
我后面没用 pro 系列的组件了
