### ISSUE TITLE
🐛[BUG] StatisticCard暗黑模式字体颜色问题

### ISSUE THREAD

**Issue by ApsarasX** [ant-design/pro-components#2814]
版本：@ant-design/pro-card 1.12.1

普通模式下效果
<img width="1207" alt="截屏2021-05-23 下午12 10 01" src="https://user-images.githubusercontent.com/24390069/119247898-07912600-bbc0-11eb-8263-bf2e7dd85230.png">

暗黑模式下效果
<img width="1207" alt="截屏2021-05-23 下午12 10 07" src="https://user-images.githubusercontent.com/24390069/119247904-0f50ca80-bbc0-11eb-90bc-dd836cb427ba.png">

**Comment by langengel** [comment]
我早就发现了 只是我没有提😄

**Comment by ApsarasX** [comment]
当前bug在@ant-design/pro-card 1.12.2版本下尚未修复
