### ISSUE TITLE
🐛[BUG]Pro-table: 时间字段valueType为dateTimeRange，默认和renderText都不生效，会显示两个 - 

### ISSUE THREAD

**Issue by qqack** [ant-design/pro-components#282]
### 🐛 bug 描述
protable bug:
columns中的字段valueType为dateTimeRange，默认和renderText都不生效，会显示两个 - , 用render才能显
<!-
### 📷 复现步骤
代码:
    {
      title: '申请时间',
      dataIndex: 'createdAt',
      align: 'left',
      copyable: false,
      valueType: 'dateTimeRange',
    },
页面效果：
![image](https://user-images.githubusercontent.com/11495559/91016625-9f58e800-e61f-11ea-8b60-d17c2dd9f079.png)

展示正确的需要加上render:
    {
      title: '操作时间',
      dataIndex: 'createdAt',
      align: 'left',
      copyable: false,
      valueType: 'dateTimeRange',
      render: (_, record) => date.formatDate(record.createdAt || '', 'YYYY-MM-DD HH:mm:ss'),
    },
这样才会显示正确

### 🏞 期望结果
既可以在表单中显示日期范围选择框，也可以在表格中显示正确时间
![image](https://user-images.githubusercontent.com/11495559/91017043-48074780-e620-11ea-97da-de961e1074a3.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 win 10

**Comment by qqack** [comment]
升级到最新版本出现的问题

**Comment by chenshuai2144** [comment]
你的数据格式是什么样子？

**Comment by qqack** [comment]
![image](https://user-images.githubusercontent.com/11495559/91028209-b9022b80-e62f-11ea-9d70-0592924a755c.png)

**Comment by qqack** [comment]
> 你的数据格式是什么样子？

![image](https://user-images.githubusercontent.com/11495559/91028243-c6b7b100-e62f-11ea-921e-1d779f66c7b9.png)

**Comment by chenshuai2144** [comment]
你需要用 renderText 转化成 string[]，不然是不能使用的

**Comment by qqack** [comment]
> 你需要用 renderText 转化成 string[]，不然是不能使用
这个字段是要在表格中展示一个时间而不是两个时间， 然后在搜索表单里展示时间范围选择框，之前默认和写renderText可以的， 升级后到2.5.15之后就只能用render，render和renderText的区别是什么呢？

**Comment by chenshuai2144** [comment]
renderText 可以拼接成 valueType 需要的值。上个版本是个 bug ，dateTimeRange 被误认为是 dataTime 了

**Comment by meyerlee** [comment]
这个issue，我还想抢救一下。
目前protable主要使用在查询场景，对于时间的查询，理论上都是查的时间范围，只有很少的业务是取快照的。
那么势必照成，更多的使用情况是 查询条件是范围，查询结果是单个时间。
比如订单时间：查询条件是范围，比如最近3天；查询的结果就是订单时间，而不是范围。
所有我觉得dateRange, datetimeRange，可以考虑支持这种场景。
如果字段是数组就按range来渲染，如果不是数组就安装日期来渲染。

**Comment by dmdoit** [comment]
> 这个issue，我还想抢救一下。
> 目前protable主要使用在查询场景，对于时间的查询，理论上都是查的时间范围，只有很少的业务是取快照的。
> 那么势必照成，更多的使用情况是 查询条件是范围，查询结果是单个时间。
> 比如订单时间：查询条件是范围，比如最近3天；查询的结果就是订单时间，而不是范围。
> 所有我觉得dateRange, datetimeRange，可以考虑支持这种场景。
> 如果字段是数组就按range来渲染，如果不是数组就安装日期来渲染。

支持你的说法，做的大部分业务都是table展示的是一个时间值，而search查询的是一个时间范围。
比如下单时间是createdAt，
```
{
    title: '下单时间',
    dataIndex: 'createdAt',
    key: 'createdAt',
    valueType: 'dateRange',
},
```
一条table数据，后台会返回一个具体的下单时间，而不是一个下单时间范围，所以后台返回的是string或者number，
而前台要求的是[]，那么就不满足table里valueType: 'dateRange时要求是一个[]的条件，就会显示两条杠，这时候用renderText因为数据不对，table里也会不显示，只能使用
`
render: (_, record) => dateTime(record.createdAt),
`
来解析。

**Comment by l745230** [comment]
相比之下我更好奇的是,啥业务后端是返回时间区间的形式. 
聚划算的生效时间,后端也是得用2个字段去存放吧?

单个字段存2个时间值,后端也不好处理吧.

**Comment by hengkx** [comment]
建议 
```
searh:{type:'dateTimeRange'}
```
支持

**Comment by liuwin7** [comment]
官方给的例子里面，有这种情况，[表格查询](https://codesandbox.io/s/61qvs?file=/App.tsx)。
配置列的时候，创建两个拥有相同data_index的column，只不过，一个在search里隐藏，一个在table里隐藏。

```javascript
{
    title: '创建时间',
    key: 'showTime',
    dataIndex: 'created_at',
    valueType: 'date',
    hideInSearch: true,
  },
  {
    title: '创建时间',
    dataIndex: 'created_at',
    valueType: 'dateRange',
    hideInTable: true,
    search: {
      transform: (value) => {
        return {
          startTime: value[0],
          endTime: value[1],
        };
      },
    },
  },
```

**Comment by tanhaixiang** [comment]
如果只是通过render进行渲染的话，表格显示的问题是解决了，但是个问题，行内编辑还是会显示dateRange，这样也是不满足要求的。提供一个新思路，valueType设置为date/dataTime，然后配置renderFormItem，通过判断isEditable进行渲染组件。
`{
      title: '创建时间',
      dataIndex: 'createTime',
      valueType: 'dateTime',
      renderFormItem: (_, { isEditable, defaultRender }) => {
        const { RangePicker } = DatePicker;
        return isEditable ? (
          defaultRender(_)
        ) : (
          <RangePicker placeholder={['开始日期', '结束日期']} />
        );
      },
    },`

**Comment by smiler1203** [comment]
> 官方给的例子里面，有这种情况，[表格查询](https://codesandbox.io/s/61qvs?file=/App.tsx)。 配置列的时候，创建两个拥有相同data_index的column，只不过，一个在search里隐藏，一个在table里隐藏。
> 
> ```js
> {
>     title: '创建时间',
>     key: 'showTime',
>     dataIndex: 'created_at',
>     valueType: 'date',
>     hideInSearch: true,
>   },
>   {
>     title: '创建时间',
>     dataIndex: 'created_at',
>     valueType: 'dateRange',
>     hideInTable: true,
>     search: {
>       transform: (value) => {
>         return {
>           startTime: value[0],
>           endTime: value[1],
>         };
>       },
>     },
>   },
> ```

这是正解！
但我怀疑这是ant的团队帮助广大码农增加代码量的一种方法
