### ISSUE TITLE
🐛[BUG] EditTable 删除bug

### ISSUE THREAD

**Issue by poyiding** [ant-design/pro-components#2820]
### 🐛 bug 描述

可编辑表格官网第一个例子：新增一行，保存，点击第一行删除，结果删除了两行。

### 📷 复现步骤

1.  新增一行
2. 保存
3. 删除第一行或者第二行
结果删除了两行。

### 🏞 期望结果

不管新增保存还是 取消，删除结果应该正常
### 💻 复现代码

https://codesandbox.io/s/c6l0x
### © 版本信息

- ProComponents 版本: ProTable 2.37.1

- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
也是缓存问题，已经删掉了
