### ISSUE TITLE
🐛[BUG] UploadButton组件不使用上传行为的实现问题

### ISSUE THREAD

**Issue by qiaoyuwen** [ant-design/pro-components#2825]
### 🐛 bug 描述

由于我所需业务的特殊，不希望选择文件时执行上传操作，在@ant-design/pro-form@1.23.0版本以前，我是设置beforeUpload: () => false，让它直接返回false来阻止上传操作，1.23.0版本中 https://github.com/ant-design/pro-components/pull/2700 的这个修改，造成我这样去做的话表单是不会设置选中的文件的值的，想请问一下我这个需求现在应该如何实现

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by DerrickTel** [comment]
beforeUpload的参数就是你的文件，你可以存下来。然后需要的时候，再调用请求。
https://ant.design/components/upload-cn/#API
