### ISSUE TITLE
🐛[BUG] antd更新4.16.0后 layout报错

### ISSUE THREAD

**Issue by hemengke1997** [ant-design/pro-components#2827]
### 🐛 bug 描述

`MenuItem or SubMenu should not leave undefined `key`.`

### 📷 报错截图

![image](https://user-images.githubusercontent.com/49073282/119429267-1c48f780-bd41-11eb-94ee-868c94f7d8e9.png)

### 💻 复现代码

https://github.com/hemengke1997/testAntd.git

### © 版本信息

- ProComponents 版本: 最新
- umi 版本 最新
- 浏览器环境 chrome
- 开发环境  windows

**Comment by hemengke1997** [comment]
一个疑问：
这种bug，我该怎么去调试解决，从报错的调用栈来看，封装层有点儿多，不知道从哪下手.. （想自己解决顺便学学pr）

**Comment by chenshuai2144** [comment]
key 的问题要在 devtools 里面看。这是因为每个 menuitem 都需要一个 key

**Comment by vvni** [comment]
?我也遇到了

**Comment by hemengke1997** [comment]
> ?我也遇到了

`https://github.com/ant-design/pro-components/commit/e06baa38da899b04b41b64b6967b84a8e459f773`

最新的一次commit，我看到已经解决这个问题了，不过package还没更新，估计等package更新了就行了

**Comment by jnerul** [comment]
Menu.Divider 也要加key，加上就不报错了

**Comment by hemengke1997** [comment]
> Menu.Divider 也要加key，加上就不报错了

是的，不过pro-layout封装了menu，我用的layout插件，就没法改。现在这个问题已经修复了。

**Comment by JessYan0913** [comment]
@hemengke1997 怎么修复的？我debug原因是InternalMenuItem的props没有warnKey属性，在dev模式下就会出错：
![截屏2021-12-23 下午5 51 31](https://user-images.githubusercontent.com/52144974/147222789-5cb30eee-73aa-43a9-b8e2-99e9263bbb5a.png)
