### ISSUE TITLE
👑 [需求]stepTable的onFinish能否deep merge子form的value？

### ISSUE THREAD

**Issue by jueinin** [ant-design/pro-components#2829]
### 🥰 需求描述

现在是几个子form浅合并的，会存在一些value被覆盖的场景。

举个例子： `{a: {b: 'xxx'}}`和`{a: {c: "yyy"}}`，最后StepForm的onFinish拿到的值是 `{a: {c: "yyy"}}`

**Comment by chenshuai2144** [comment]
有兴趣可以来个pr

**Comment by jueinin** [comment]
好的  一会儿PR

**Comment by jueinin** [comment]
@chenshuai2144 可否发个新版本？

**Comment by Artoria-0x04** [comment]
#2836 发布的 v1.27.0 有依赖问题
