### ISSUE TITLE
🧐[问题]ProTable打包体积很大，如何优化？一个组件比一个组件库的体积都大

### ISSUE THREAD

**Issue by bingo618** [ant-design/pro-components#283]
### 🧐 问题描述

ProTable打包体积优化方法？

### 🚑 其他信息

<img width="738" alt="WX20200824-154443@2x" src="https://user-images.githubusercontent.com/20422686/91017450-d8de2300-e620-11ea-8869-201b86a7bc2f.png">

**Comment by chenshuai2144** [comment]
有 300 个 moudle 被打了进去，有点奇怪

**Comment by goodve** [comment]
把依赖全部放  devDependencies 试试

**Comment by chenshuai2144** [comment]
试了一下 ok 了， sideEffect 真好用

**Comment by superlpff** [comment]
> 试了一下 ok 了， sideEffect 真好用

请问，是在哪里配置的啊？

**Comment by a992681784** [comment]
> 

请问 找到在哪配了吗？我这边打包后体积很大

**Comment by a992681784** [comment]
> > 试了一下 ok 了， sideEffect 真好用
> 
> 请问，是在哪里配置的啊？


请问 找到在哪配了吗？我这边打包后体积很大
