### ISSUE TITLE
🐛[BUG]  ProTable search.filterType = "light" 轻量模式下 columns.valueType = "dateRange" 渲染异常

### ISSUE THREAD

**Issue by wuhao930406** [ant-design/pro-components#2837]
### 🐛 bug 描述

ProTable search.filterType = "light" 轻量模式下 columns.valueType = "dateRange" 渲染异常
![image](https://user-images.githubusercontent.com/18044670/119463234-2506f100-bd74-11eb-8605-42a6438c3b8d.png)

### 📷 复现步骤
let columns = {
   {
      "title": "报修时间",
      "dataIndex": "dateRange",
      "key": "dateRange",
      "valueType": "dateRange",
    }
}

<ProTable
    columns={columns}
    search={{
      filterType: 'light',//轻量模式
    }}
    path="/api/list"
  ></ProTable>

### 🏞 期望结果

![image](https://user-images.githubusercontent.com/18044670/119463349-4536b000-bd74-11eb-843b-364a388b86b2.png)

### 💻 复现代码

let columns = {
   {
      "title": "报修时间",
      "dataIndex": "dateRange",
      "key": "dateRange",
      "valueType": "dateRange",
    }
}

<ProTable
    columns={columns}
    search={{
      filterType: 'light',//轻量模式
    }}
    path="/api/list"
  ></ProTable>

### © 版本信息

- ProComponents 版本: "@ant-design/pro-table": "^2.38.0"
- umi 版本 "umi": "^3.4.22"
- 浏览器环境 Google Chrome 版本 90.0.4430.93
- 开发环境  win10

### 🚑 其他信息

自定义renderFormItem 时也会出现这样的渲染结果

**Comment by dingtianxiu** [comment]
https://github.com/ant-design/pro-components/pull/2867
