### ISSUE TITLE
🐛[BUG] EditableProTable columns设置 hideInForm，出现错位

### ISSUE THREAD

**Issue by smile2233514516** [ant-design/pro-components#2838]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/50870976/119464004-e9b8f200-bd74-11eb-830f-2856dba6ecb6.png)

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/50870976/119464141-09501a80-bd75-11eb-99f8-6d814d8217eb.png)

### 🏞 期望结果
hideInForm为true，表格不显示，form赋值的时候可以进行setFieldsValue，可是现在设置hideInForm为true就会显示，只有设置hideInTable为true才会隐藏，但是这时候form.setFieldsValue设置不了值了。

### © 版本信息

- ProComponents 版本: [^2.38.0]
- umi 版本
- 浏览器环境 谷歌浏览器
- 开发环境 [e.g. mac OS]  win10

**Comment by chenshuai2144** [comment]
hideInForm 本来就不会生效，用 hideInSearch  把

**Comment by smile2233514516** [comment]
> hideInForm 本来就不会生效，用 hideInSearch 把

。。。。这个命名有问题吧

**Comment by smile2233514516** [comment]
> hideInForm 本来就不会生效，用 hideInSearch 把

![image](https://user-images.githubusercontent.com/50870976/119634493-64514280-be45-11eb-8bc8-7e1589e73e6e.png)

**Comment by smile2233514516** [comment]
出现的重影，鼠标悬浮又消失了

**Comment by smile2233514516** [comment]
![image](https://user-images.githubusercontent.com/50870976/119634859-b72afa00-be45-11eb-9b87-dd4747c10321.png)

**Comment by chenshuai2144** [comment]
搞一下你的列把，我觉得你的css 或者 width 写的有问题。和table 没关系

**Comment by chenshuai2144** [comment]
> 。。。。这个命名有问题吧

hideInForm  被别人用了。

**Comment by smile2233514516** [comment]
好

**Comment by 349989153** [comment]
> 



> > 。。。。这个命名有问题吧
> 
> hideInForm 被别人用了。

所以hideInForm到底有什么用，文档也没细说，例子也没有
设为true貌似也没什么效果，还是显示在表格和查询栏里，还是会传给request作为查询条件
