### ISSUE TITLE
🐛[BUG] ProformSelect onClear清空时，会执行request

### ISSUE THREAD

**Issue by hemengke1997** [ant-design/pro-components#2839]
### 🐛 bug 描述

ProformSelect onClear清空时，会执行request

### 🏞 期望结果

单选、无搜索的ProformSelect清除时不执行request

### 💻 复现代码
```
const request = async () => {
  await sleep(3000);
  return [
    {
      label: 'test',
      value: 'test'
    }
  ]
}

<ProFormSelect
    request={request}
 ></ProFormSelect>
```
### © 版本信息

-"@ant-design/pro-form": "^1.25.0",
- umi 版本 最新
- 浏览器环境 chrome
- 开发环境  windows

### 🚑 其他信息

![动画5](https://user-images.githubusercontent.com/49073282/119467381-0c98d580-bd78-11eb-93d8-899e14f60a78.gif)

**Comment by DerrickTel** [comment]
你可以把你请求到的值放到option里面，不要使用request
```
<ProFormSelect
          options={
            [
              {
                label: 'test',
                value: 'test'
              }
            ]
          }
      />
```
或者你可以说一下你的场景。

**Comment by hemengke1997** [comment]
> 或者你可以说一下你的场景。
> option可以放到state里面去

场景： 远程获取options，所以需要用到request

疑惑：为什么在清除选择的option后，会重新request，感觉这是不必要的网络浪费

**Comment by DerrickTel** [comment]
场景不一样，为了应对搜索的那种情况。你的情况大概就是只请求一次对吧？那就可以放到state里面去了

**Comment by hemengke1997** [comment]
> 场景不一样，为了应对搜索的那种情况。你的情况大概就是只请求一次对吧？那就可以放到state里面去了。如果不请求，用户清空了输入搜索的内容，下拉框的内容不会变。

感谢帅哥，已解决
