### ISSUE TITLE
这个是个全屏api的设计，你要重新render 一下 modal 的位置

### ISSUE THREAD

**Issue by lzb-libra** [ant-design/pro-components#2843]
这个是个全屏api的设计，你要重新render 一下 modal 的位置

```tsx
<ConfigProvider getPopupContainer={()=>document.getElementById("ant-design-pro-table")}>
  <ProTable />
  <Modal />
</ConfigProvider>
```

_Originally posted by @chenshuai2144 in https://github.com/ant-design/pro-components/issues/1409#issuecomment-753490871_

我参考你的代码试了一下发现全屏后还是没有出现modal呀
![image](https://user-images.githubusercontent.com/63389341/119479075-dc0a6900-bd82-11eb-8683-a0c95b067f63.png)

**Comment by chenshuai2144** [comment]
console一下是不是刚开始 `document.getElementById("ant-design-pro-table")` 来不存在

**Comment by lzb-libra** [comment]
这个不管这么都是null
![image](https://user-images.githubusercontent.com/63389341/119485829-1fb4a100-bd8a-11eb-9e0b-1b9b369f9146.png)

**Comment by chenshuai2144** [comment]
给个table 设置个自定义的id试试

**Comment by elfiala** [comment]
<ConfigProvider getPopupContainer={() => document.querySelector('.ant-pro-table')}></ConfigProvider>
message.config({ getContainer: () => document.querySelector('.ant-pro-table')});
Modal.confirm({ getContainer: () => document.querySelector('.ant-pro-table')});
配置渲染节点的输出位置
