### ISSUE TITLE
🧐[问题]使用protable的全屏后modal无法显示

### ISSUE THREAD

**Issue by lzb-libra** [ant-design/pro-components#2846]
项目中使用了react-design-pro v5, 在点击了table右上角的全屏按钮后在点击新建按钮，无法正常弹出modal，关闭table的全屏后，发现弹窗modal已经弹出了，只是没有展示到table的顶层，问了大神后说要重新渲染什么的，不是很理解，等在想详细问一下时直接就将我的问题给关闭了。真的是百思不得其解，我是第一次使用这个框架，有好多不懂的地方，还有没有大神指点一二，最好是有个dom就更好了。谢谢m(__)m
![20210526101810](https://user-images.githubusercontent.com/63389341/119592819-c5f4bb00-be0b-11eb-8925-b0715d676ae1.png)

**Comment by chenshuai2144** [comment]
太长了，不想看。。


全屏本质上是个 通过一个 zindex为最高的dom来挡住所有的组件，所以你要把 modal 和 drawer 渲染到全屏的dom上。

所以你需要在modal 和 drawer 上设置 
```
 getContainer={() => document.getElementById('pro-layout')}
```
