### ISSUE TITLE
🧐[问题] ProTable renderText 的返回值是 any 类型，是预期行为吗？不是 string 吗？

### ISSUE THREAD

**Issue by linxianxi** [ant-design/pro-components#2847]

**Comment by linxianxi** [comment]
@chenshuai2144  文档中说明必须为 string 类型，但是使用时 return ReactNode 也没有问题。怎么说呢

**Comment by DerrickTel** [comment]
在编辑表格里面，ReactNode就会出毛病的。纯展示得益于jsx的帮助所以没事，最好情况就是string哦

**Comment by chenshuai2144** [comment]
renderText  是看 valueType 的，不同的valueType 需要的有点不同，所以给了any。能跑就是能用
