### ISSUE TITLE
[pro-table] 🧐  DatePicker displays an Arabic numbers

### ISSUE THREAD

**Issue by cielblog** [ant-design/pro-components#285]
### 🧐 问题描述

At RTL version of my project, the DatePicker in search section displays Arabic numbers and those numbers cause an error in the backend.

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/16566503/91022846-6eb48680-e5fe-11ea-87c6-b4132ec66e6c.png)

**Comment by chenshuai2144** [comment]
give a pr？ i don't konw RTL

**Comment by cielblog** [comment]
> give a pr？ i don't konw RTL

Yes, pro-table does not support RTL (Right-to-Left locales), so I made some changes:

in Table.tsx I wrapped the value of tableDom with this:
`<ConfigProvider direction={getLocale() === 'ar-EG' ? 'rtl' : 'ltr'}>...</ConfigProvider>`

I did the same in toolBar and form components.
So now the table completely looks great on RTL.

The only problem now on DataPicker, if the language is Arabic.

Here I imported the table from `@ant-design/pro-table` and still the same problem:
![image](https://user-images.githubusercontent.com/16566503/91030836-6e20ed80-e608-11ea-9a0f-20381e76059a.png)


+ I really respect how you guys support your language, but please give some attention to other languages <3.

**Comment by chenshuai2144** [comment]
look here http://localhost:8000/components/table#rtl-%D8%A7%D9%84%D9%86%D8%B3%D8%AE%D8%A9-%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9
