### ISSUE TITLE
🐛[BUG]使用 Schema Form (< BetaSchemaForm />)组件时，hideInForm 参数不生效

### ISSUE THREAD

**Issue by xminc** [ant-design/pro-components#2854]
### 🐛 bug 描述

使用 Schema Form `<BetaSchemaForm />`组件时，hideInForm 参数不生效

### 📷 复现步骤
```
{
    title: '测试',
    dataIndex: 'a1',
    width: 'md',
    hideInForm: true
 },
```

### 🏞 期望结果

在显示表单隐藏对应的 字段行

### 💻 复现代码
如上 在  `<BetaSchemaForm/> `columns 里配置

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] 
    "@ant-design/pro-descriptions": "1.7.7",
    "@ant-design/pro-form": "1.26.0",
    "@ant-design/pro-layout": "6.17.1",
    "@ant-design/pro-list": "1.7.2",
    "@ant-design/pro-table": "2.35.1",
- umi 版本 3.4.18
- 浏览器环境 chrome 90.0.4430.212
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
无

**Comment by mctl** [comment]
我是这样临时用的
{
        title: 'id',
        width: 480,
        dataIndex: 'id',
        // 不生效
        hideInForm: true,
        fieldProps: {
          disabled: true,
        },
       // 这样写可以生效
        formItemProps: {
          hidden: true
        }
      },

**Comment by mctl** [comment]
我是这样临时用的

> {
title: 'id',
width: 480,
dataIndex: 'id',
// 不生效
hideInForm: true,
fieldProps: {
disabled: true,
},
// 这样写可以生效
formItemProps: {
hidden: true
}
},
