### ISSUE TITLE
🧐[问题] ProLayout 有提供路由功能吗，还是依赖umijs的路由组件

### ISSUE THREAD

**Issue by fullee** [ant-design/pro-components#2855]
### 🧐 问题描述

使用route这个prop，可以让ProLayout渲染出菜单，但是点击的菜单具体路由到哪个组件文档上没有说明。

### 💻 示例代码

下面的代码来自https://procomponents.ant.design/components/layout#route
```ts
export interface Route {
  path: string;
  routes: Array<{
    exact?: boolean;
    icon: string;
    name: string;
    path: string;
    // 可选二级菜单
    children?: Route['routes'];
  }>;
}
```

上面的代码也没有component字段可以路由到相关组件，目前可以想到使用react-router实现路由功能，或者ProLayout有什么方法可以实现这样的需求

**Comment by chenshuai2144** [comment]
不支持，它只是个ui库，不和具体实现耦合
