### ISSUE TITLE
🐛[BUG]官网ProTable实例 "左右结构" 在本地，左侧点击onRow会执行一边request

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#2856]
### 🐛 bug 描述

完全拷贝官网ProTable实例 "左右结构" 在本地，左侧点击onRow会执行一边request

官网代码：

![image](https://user-images.githubusercontent.com/12421552/119651709-dd599580-be57-11eb-80cc-5ca428dba0af.png)

本人项目代码：

![image](https://user-images.githubusercontent.com/12421552/119651665-d2066a00-be57-11eb-8810-816d031186d4.png)

### © 版本信息

  "antd": "^4.14.0",
  "@ant-design/pro-table": "^2.30.8",
  "umi": "^3.4.0",

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by edifangyi** [comment]
更新到最新的"@ant-design/pro-table": "^2.39.0",还是有这个问题

**Comment by chenshuai2144** [comment]
request 不会执行的，但是dom会被  render， 因为props 改变了
