### ISSUE TITLE
🐛[BUG] pro-table 2.39.0  tree模式下，节点展开后无法收缩

### ISSUE THREAD

**Issue by Hikarien** [ant-design/pro-components#2857]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/41961907/119683718-7697a480-be76-11eb-9483-fb9caaf64d85.png)

### 📷 复现步骤

就是普通的Table的Tree数据模式，不知道是不是因为之前优化了按需渲染的原因，最近经常发现有的单元格数据没及时更新

### 🏞 期望结果

能够正常展开收缩

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] pro-table 2.39.0
- umi 版本
- 浏览器环境 Chrome
- 开发环境 [e.g. mac OS] macOS

**Comment by ralph-wh** [comment]
遇到了同样的问题，展开和折叠没有antd的Table顺滑，而且展开一个的同时会导致另一行折叠

**Comment by xykjlcx** [comment]
> 遇到了同样的问题，展开和折叠没有antd的Table顺滑，而且展开一个的同时会导致另一行折叠

+1 也遇到了同样的问题

## 问题描述

- 展开、收缩动画没有了
- 无法收缩了
- 只能展开一级，会自动收缩其他展开行
- 展开后图标显示仍是+号

代码如下：
```
import type { ProColumns } from '@ant-design/pro-table';
import ProTable from '@ant-design/pro-table';
import React from 'react';
import type { DeptListItemType } from '@/pages/system/dept/data';

const TreeTable = () => {
  const columns: ProColumns<DeptListItemType>[] = [
    {
      title: '部门名称',
      width: '60%',
      dataIndex: 'deptName',
    },
  ];

  const dataSource = [
    {
      id: 1,
      deptName: 'qwe',
    },
    {
      id: 2,
      deptName: 'ad',
      children: [
        {
          id: 22,
          deptName: '2222',
        },
        {
          id: 23,
          deptName: '232323',
        },
      ],
    },
    {
      id: 3,
      deptName: '111',
    },
  ];

  return (
    <>
      <ProTable<DeptListItemType> rowKey={'id'} columns={columns} dataSource={dataSource} />
    </>
  );
};

export default React.memo(TreeTable);
```

效果如图：

![image](https://user-images.githubusercontent.com/32430701/120268716-ed9ac600-c2d8-11eb-8d78-5ad70a51e091.png)

**Comment by Hikarien** [comment]
https://codesandbox.io/s/pro-table-tree-repo-39jcw

@chenshuai2144  做了个repo 看看能不能用
