### ISSUE TITLE
🐛[BUG] 嵌套表格收起时，无法校验已收起内容

### ISSUE THREAD

**Issue by bWhirring** [ant-design/pro-components#2863]
### 📷 复现步骤

1. 新增嵌套表格
2. 收起表格
3. 保存校验时无法校验新增嵌套表格是否符合rules

### 🏞 期望结果

校验表格的时候收起的嵌套表格也能按照rules校验是否正确

### 💻 复现代码

https://codesandbox.io/s/zidingyikebianjibiaoge-forked-urjwm?file=/App.tsx

### © 版本信息

- pro-table 版本: 2.31.0
- 浏览器环境 Chrome 90.0.4430.212
- 开发环境 mac OS

**Comment by chenshuai2144** [comment]
收起来的时候dom直接不存在了，你要不设置不允许收起好了。不然这个问题解决不了

**Comment by bWhirring** [comment]
> 收起来的时候dom直接不存在了，你要不设置不允许收起好了。不然这个问题解决不了

我提交的时候先把table展开了。然后就能校验到了
