### ISSUE TITLE
Warning: [antd: Typography] `ellipsis` should use string as children only.

### ISSUE THREAD

**Issue by Liuxl1996** [ant-design/pro-components#2864]
### 🐛 bug 描述

当所有column加入ellipsis:true属性时，浏览器会出去此异常警告

### © 版本信息

- ProComponents 版本: 2.37.0
- umi 版本 无
- 浏览器环境 Edge
- 开发环境  Windows

**Comment by hemengke1997** [comment]
你的某些columns的值不是string，要先转成string再用嗷

```
ellipsis: true,
render: (_, reocrd) => String(someVal)
```

**Comment by LXiaoLONG1** [comment]
> 你的某些columns的值不是string，要先转成string再用嗷
> 
> ```
> ellipsis: true,
> render: (_, reocrd) => String(someVal)
> ```

无render，代码如下：
`column: [
                    { title: "ID", dataIndex: "id", sorter: { order: 1 },ellipsis:true },
                    { title: "Name", dataIndex: "name", sorter: { order: 2 },ellipsis:true }
                ]`

**Comment by hemengke1997** [comment]
猜测接口返回的id是number类型的

**Comment by Liuxl1996** [comment]
> 猜测接口返回的id是number类型的
是的，不可思议，那不然所有非字符串类型的都要转换成字符串
