### ISSUE TITLE
👑 [需求]ProTable 表头tip支持组件或者html

### ISSUE THREAD

**Issue by mrhuang2365** [ant-design/pro-components#2866]
### 🥰 需求描述

![image](https://user-images.githubusercontent.com/28747238/119792615-6a5c2780-bf08-11eb-98e1-ba86e3cb31b3.png)
现在只支持字符串，现在我想实现字符换行展示，如下图所示，在红圈处换行
![image](https://user-images.githubusercontent.com/28747238/119793153-e9516000-bf08-11eb-8779-2b828910214d.png)

### 🧐 解决方案

希望tip可以支持组件

**Comment by hemengke1997** [comment]
临时解决的话可以使用 `\n` 换行， 然后tooltip的样式改成 `white-space: pre-wrap`

**Comment by mrhuang2365** [comment]
> 临时解决的话可以使用 `\n` 换行， 然后tooltip的样式改成 `white-space: pre-wrap`
非常感谢，已采纳为临时方案。

**Comment by chenshuai2144** [comment]
其实支持组件的，我打开一下的 ts 的配置
