### ISSUE TITLE
🐛[BUG] ProForm 使用 onValuesChange 监听值变化，在 ProFormSelect 被清空的时候，只收到一个空的 {}，没有 key

### ISSUE THREAD

**Issue by jasonscript** [ant-design/pro-components#2868]

**Comment by hemengke1997** [comment]
+1  "@ant-design/pro-form": "^1.25.0" 版本可以复现

**Comment by hemengke1997** [comment]
使用antd的form是可以拿到key的

**Comment by hemengke1997** [comment]
```
<ProForm omitNil={false}>
</ProForm>
```

即可解决

**Comment by hemengke1997** [comment]
![image](https://user-images.githubusercontent.com/49073282/119806697-05f39500-bf15-11eb-82da-dd005cd8804b.png)

![image](https://user-images.githubusercontent.com/49073282/119806764-173ca180-bf15-11eb-8c28-02a04369f15b.png)


proform会在onValuesChange时格式化数据

**Comment by jasonscript** [comment]
omitNil 确实可以解决这个问题

**Comment by feibi** [comment]
omitNil 设置了false，ProFormSelect可以，但ProFormDate清空只收到一个空的 {}，没有 key

**Comment by hemengke1997** [comment]
> omitNil 设置了false，ProFormSelect可以，但ProFormDate清空只收到一个空的 {}，没有 key

![动画7](https://user-images.githubusercontent.com/49073282/120293388-c9021680-c2f7-11eb-887e-d06d1bb5c8f2.gif)

无法复现。检查一下你的FormItem是否有`name`属性

**Comment by feibi** [comment]
> > omitNil 设置了false，ProFormSelect可以，但ProFormDate清空只收到一个空的 {}，没有 key
> 
> ![动画7](https://user-images.githubusercontent.com/49073282/120293388-c9021680-c2f7-11eb-887e-d06d1bb5c8f2.gif)
> 
> 无法复现。检查一下你的FormItem是否有`name`属性

增加各RangePicker,  name为数组形式或有transform时，看下这个例子
https://codesandbox.io/s/gudingyejiao-forked-9jx6l?file=/App.tsx

**Comment by hemengke1997** [comment]
> 增加个RangePicker, name为数组形式或有transform时，看下这个例子
> https://codesandbox.io/s/gudingyejiao-forked-9jx6l?file=/App.tsx

新开个issue吧，我先排查一下源码

**Comment by feibi** [comment]
> > 增加个RangePicker, name为数组形式或有transform时，看下这个例子
> > https://codesandbox.io/s/gudingyejiao-forked-9jx6l?file=/App.tsx
> 
> 新开个issue吧，我先排查一下源码

ok，另外SchemaForm的onValuesChange会执行两次。https://codesandbox.io/s/schema-biaodan-forked-3vfwf?file=/App.tsx
