### ISSUE TITLE
🐛[BUG]Pro-table: 升级后点击全屏按钮无效

### ISSUE THREAD

**Issue by qqack** [ant-design/pro-components#287]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/11495559/91028805-91f82980-e630-11ea-924f-13ab79c1864d.png)
点击后无效，不显示全屏

### © 版本信息

- ProComponents 版本: protable: 2.5.15 同事没升级前能全屏的protable版本为2.4.4
- umi 版本
- 浏览器环境 谷歌浏览器
- 开发环境  win10

**Comment by qqack** [comment]
需要再升级到新的版本

**Comment by FinchJohnRen** [comment]
> 需要再升级到新的版本

2.9.13也无效
