### ISSUE TITLE
🧐[问题] schema Form中可以使用dependencies吗？联动表单如何实现

### ISSUE THREAD

**Issue by mctl** [ant-design/pro-components#2872]
### 🧐 问题描述

我的需求是当表单项A（下拉选择），选择了某个选项，然后增加表单项B，否则不出现B。

目前看通过form的dependencies应该能实现，请问schema Form中的写法应该是怎么样？

或者有没有其他解决方案

### 💻 示例代码

无

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
暂时不支持的，你现在只能用 fieldProps  和 formitemProps 组合来实现

```
fieldProps ={(form)=>{} }
formitemProps ={(form)=>{} }
```

**Comment by meowmiaomiaomiao** [comment]
https://x-render.gitee.io/form-render/advanced/function/
我看了下 x-render 使用占位符实现的，不知道有没有实现这个功能的排期？

**Comment by meowmiaomiaomiao** [comment]
> 暂时不支持的，你现在只能用 fieldProps 和 formitemProps 组合来实现
> 
> ```
> fieldProps ={(form)=>{} }
> formitemProps ={(form)=>{} }
> ```

我用的ModalForm一个表单项更改后好像并不会触发fieldProps ={(form)=>{} } formitemProps ={(form)=>{} }
能否像https://x-render.gitee.io/form-render/advanced/function 一样提供简单的占位符实现呢？

**Comment by chenshuai2144** [comment]
不搞不能 ts 自动提示的语法。

**Comment by chenshuai2144** [comment]
> 我用的ModalForm一个表单项更改后好像并不会触发fieldProps ={(form)=>{} } formitemProps ={(form)=>{} }

来个重现，我跟进一下

**Comment by meowmiaomiaomiao** [comment]
在 valueType 为 'group' 的时候必须声明一下  formItemProps 才会触发， 参考下这个变量，如果没有 formItemProps 下面的联动就不会触发

`
const columns: ProFormColumnsType[] = [
  {
    valueType: 'group',
    formItemProps: (form, config) => {
      return {};
    },
    columns: [
      {
        title: '布局类型',
        dataIndex: 'type',
        valueType: 'select',
        initialValue: '1',
        // valueEnum,
        // options: [{a:1}]
        width: 100,
        valueEnum: {
          1: '自适应画布',
          2: '精确画布',
        },
      },
      {
        title: '比例',
        dataIndex: 'ratio',
        valueType: 'radioButton',
        initialValue: '16:9',
        valueEnum: {
          '16:9': '16:9',
          '4:3': '4:3',
          '1:1': '1:1',
          '3:4': '3:4',
          '9:16': '9:16',
        },
        formItemProps: (form) => {
          return {
            style: form.getFieldValue('type') === '2' ? { display: 'none' } : {},
            rules: [
              {
                required: true,
                message: '此项为必填项',
              },
            ],
          };
        },
      },
      {
        title: '宽度',
        dataIndex: 'width',
        initialValue: 1920,
        width: 120,
        // fieldProps: (form)=>{
        //   // console.log(form, 'console.log(form)')
        //   return {}
        // },
        formItemProps: (form) => {
          return {
            style: form.getFieldValue('type') === '1' ? { display: 'none' } : {},
            rules: [
              {
                required: true,
                message: '此项为必填项',
              },
            ],
          };
        },
      },
      {
        title: '高度',
        dataIndex: 'height',
        initialValue: 1080,
        width: 120,
        formItemProps: (form, config) => {
          return {
            style: form.getFieldValue('type') === '1' ? { display: 'none' } : {},
            rules: [
              {
                required: true,
                message: '此项为必2填项',
              },
            ],
          };
        },
      },
    ],
  },
]
`

**Comment by meowmiaomiaomiao** [comment]
> > 我用的ModalForm一个表单项更改后好像并不会触发fieldProps ={(form)=>{} } formitemProps ={(form)=>{} }
> 
> 来个重现，我跟进一下

在 valueType 为 'group' 的时候必须声明一下 formItemProps 才会触发， 参考下这个变量，如果没有 formItemProps 下面的联动就不会触发
`const columns: ProFormColumnsType[] = [ { valueType: 'group', formItemProps: (form, config) => { return {}; }, columns: [ { title: '布局类型', dataIndex: 'type', valueType: 'select', initialValue: '1', // valueEnum, // options: [{a:1}] width: 100, valueEnum: { 1: '自适应画布', 2: '精确画布', }, }, { title: '比例', dataIndex: 'ratio', valueType: 'radioButton', initialValue: '16:9', valueEnum: { '16:9': '16:9', '4:3': '4:3', '1:1': '1:1', '3:4': '3:4', '9:16': '9:16', }, formItemProps: (form) => { return { style: form.getFieldValue('type') === '2' ? { display: 'none' } : {}, rules: [ { required: true, message: '此项为必填项', }, ], }; }, }, { title: '宽度', dataIndex: 'width', initialValue: 1920, width: 120, // fieldProps: (form)=>{ // // console.log(form, 'console.log(form)') // return {} // }, formItemProps: (form) => { return { style: form.getFieldValue('type') === '1' ? { display: 'none' } : {}, rules: [ { required: true, message: '此项为必填项', }, ], }; }, }, { title: '高度', dataIndex: 'height', initialValue: 1080, width: 120, formItemProps: (form, config) => { return { style: form.getFieldValue('type') === '1' ? { display: 'none' } : {}, rules: [ { required: true, message: '此项为必2填项', }, ], }; }, }, ], }, ]`
