### ISSUE TITLE
🧐[问题] 文档缺少了只读模式，设置footer={null}未生效

### ISSUE THREAD

**Issue by diaomina** [ant-design/pro-components#2873]
### 🧐 问题描述

1、尝试使用ModalForm封装一个自定义的表单，但是编写查看表单部分时，发现文档缺少了，文档连接如下：
[https://ant-design-pro-components-preview-pr-963.surge.sh/components/form#%E5%8F%AA%E8%AF%BB%E6%A8%A1%E5%BC%8F](url)
想问一下，怎么设置整个表单都为只读的，

2、参考文档将footer设置null，但是默认的确认、取消按钮并没有消失
### 💻 示例代码

```
<ModalForm
      form={form}
      title={getTitle()}
      width={width}
      visible={visible}
      onVisibleChange={(newVisible) => {
        if (!newVisible) handleCancel();
      }}
      onFinish={onFinish}
      modalProps={{
        footer: null,
      }}
    >
      {formContent()}
    </ModalForm>
```

**Comment by DerrickTel** [comment]
https://procomponents.ant.design/components/modal-form

**Comment by diaomina** [comment]
> https://procomponents.ant.design/components/modal-form

谢谢~页脚的按钮成功去掉啦，请问一下设置整个表单只读的话，只能在每个表单项内设置mode='read'嘛，是否存在直接再表单上统一设置的配置（在组件文档内没有找到相关配置），或者说可以通过获取该表单内所有表单项的方法，遍历这些表单项进行mode='read'的设置

**Comment by chenshuai2144** [comment]
现在是没有的，如果都是只读的，何不用descriptions

https://procomponents.ant.design/components/descriptions

**Comment by diaomina** [comment]
> 现在是没有的，如果都是只读的，何不用descriptions
> 
> https://procomponents.ant.design/components/descriptions

你好，我想实现的是在read模式下是只读的，但是edit和create模式下还是可编辑的
