### ISSUE TITLE
🧐[问题]请教两个项目合并的问题。

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#2874]
我有两个项目
一个是新的，基于 umi 和  antd pro的APP
一个是旧的，基于 react class components, non-umijs APP

我现在需要把两个项目合并， 
最好是把老项目作为新项目这一个子集，
尽量少改代码。

能不能提供一下指导性的意见。

**Comment by jueinin** [comment]
一点小建议。方便改动的话，把老项目打个Systemjs的bundle，放CDN上，配合single-spa在新项目中用Systemjs引入老项目即可。开发部署都还算方便。中间会踩一些webpack和webpack-dev-server的坑。

或者用qiankun那一套搞搞看。没用过不敢评价。总之就是微前端呗
