### ISSUE TITLE
👑 [需求]在mix布局中，左侧菜单希望可以设置有图标

### ISSUE THREAD

**Issue by ixi** [ant-design/pro-components#2875]
### 🥰 需求描述
目前代码里的逻辑是：只要是子菜单就不显示图标

但是在Mix布局里，左侧菜单(二级、三级)，即使config.ts里设置了icon，图标也不能显示出来。

**实际情况，Mix布局中左侧菜单，相当于一级，是需要图标的。**

### 🧐 解决方案
方案1、【子菜单就不显示图标】的逻辑，改为【配置了icon项，就显示图标】
方案2、增加一个配置项【是否显示子菜单图标】或 【是否显示图标】

**Comment by poyiding** [comment]
二级、三级菜单不支持Icon；这是设计定的；如果你非要实现，可以在 menuItemRender 这个函数自定义实现。
