### ISSUE TITLE
🐛[BUG]2.6.0 Pro-Table TypeScript formItemProps  丢失mode属性

### ISSUE THREAD

**Issue by laoxubuer** [ant-design/pro-components#288]
### 🐛 bug 描述

2.6.0 Pro-Table TypeScript formItemProps  丢失mode属性

### 📷 复现步骤

更新pro-table 为 2.6.0 

### 🏞 期望结果

支持mode配置

### © 版本信息

- ProComponents 版本: 2.6.0
- umi 版本： 3.x
- 浏览器环境 Chrome
- 开发环境 mac OS
- AntdPro Version: 4.2.0

**Comment by laoxubuer** [comment]
每次更新，都会有各种问题出现，都不敢更新了，但是现有版本也是有一堆问题的。真的有点尴尬。

**Comment by chenshuai2144** [comment]
formItemProps 不支持了，用 fieldProps
