### ISSUE TITLE
🧐[问题]如何用antd 建立umijs 的菜单系统？

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#2881]
umijs 的菜单系统 很方便，但不想用umijs
如何用antd 组件建立umijs 的菜单系统，
比如，从json 文件中读取菜单定义等？

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/layout#menudataitem

这里有个数据结构。 路由定义生成 routers 的代码要自己实现了。umi并没有标准。
