### ISSUE TITLE
🐛[BUG] ProForm mutates custom control values

### ISSUE THREAD

**Issue by Adskoy** [ant-design/pro-components#2886]
### 🐛 bug description

When using ProForm, some values changed unexpectedly after execution of getValueFromEvent

### 📷 re-emergence steps

1. Create custom control which returns object with array of arrays field (part of geojson in my case): 
`{type: "Polygon"; coordinates: [ [42.0, 42.0], [41.0, 41.0], [40.0, 40.0],  [42.0, 42.0] ]}`
2. Place it in Form.Item 
3. Now all the values emitted by that control will be broken as array of arrays becomes an array with one object in form values:
`{
    "coordinates": [
        {
            "0": [
                42.0,
               42.0
            ],
            "1": [
                41.0,
                41.0
            ],
            "2": [
                40.0,
               40.0
            ],
            "3": [
               42.0,
                42.0
            ]
        }
    ],
    "type": "Polygon"
}`

### 🏞 expected behavior 

supposedly value should remain unchanged

### 💻 reproduction steps

[CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-25rv0?file=/index.js)

### © environment

- ProForm 1.27.1
- umi 3.4.11
- Edge 91 / Chrome 90
- Windows 10 21H1

### 🚑 additional info

Everything works as intended if using standard form from antd

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/3011
