### ISSUE TITLE
🐛[BUG] ProFormDependency 包含多个嵌套依赖项时无法正确获取依赖项的值

### ISSUE THREAD

**Issue by whinc** [ant-design/pro-components#2888]
### 🐛 bug 描述

使用`<ProFormDependency>`时，如果依赖两个或以上的嵌套依赖项时，会出现依赖项覆盖，导致只能取到最后一个嵌套依赖项。

### 📷 复现步骤

例如下面代码中：
```tsx
const Demo = () => {
  return (
    <ProForm
      initialValues={{
        a: 1,
        b: 2,
        c: {
          a: 3,
          b: 4,
          c: {
            a: 5,
          }
        },
      }}
    >
      <ProFormGroup>
        <ProFormText name="a" label="a" />
        <ProFormText name="b" label="b" />
        <ProFormText name={['c', 'a']} label="c.a" />
        <ProFormText name={['c', 'b']} label="c.b" />
        <ProFormText name={['c', 'c', 'a']} label="c.c.a" />
      </ProFormGroup>
      <ProFormDependency name={['a', 'b', ['c', 'a'], ['c', 'b'], ['c', 'c', 'a']]}>
        {(depValues) => (
          <pre>
            <code>{JSON.stringify(depValues, null, 2)}</code>
          </pre>
        )}
      </ProFormDependency>
    </ProForm>
  );
};
```
最终实际显示的结果如下，丢失` ['c', 'a']`和`['c', 'b']`两个依赖项的值
```json
{
  "a": 1,
  "b": 2,
  "c": {
    "c": {
      "a": "55"
    }
  }
}
```

### 🏞 期望结果

```json
{
  "a": 1,
  "b": 2,
  "c": {
    "a": 3,
    "b": 4,
    "c": {
      "a": 5
    }
  }
}
```

`<ProFormDependency>`的 name 属性声明的 namepath 应当可以按照声明的结构取到值

### 💻 复现代码

https://codesandbox.io/s/proformdependency-qiantaoyilaixiangquzhiwenti-ofipn

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] pro-form 1.24.0
- umi 版本 3.4.0
- 浏览器环境 chrome 90
- 开发环境 [e.g. mac OS] linux

### 🚑 其他信息
 
经过分析问题根源在于源码中 packages/form/src/components/Dependency/index.tsx ，此处`values`包含正确的依赖值，而`nameValues` 覆盖了正确的取值导致出现上述问题，这样展开很容易出现冲突覆盖问题，请问这里的`nameValues`的作用是什么？
![image](https://user-images.githubusercontent.com/5096493/120197746-e7163b00-c253-11eb-92f9-687b04967837.png)

**Comment by whinc** [comment]
希望能解释下这里的意图，我愿意提 PR 修复该问题，前提是需要确定影响面

**Comment by chenshuai2144** [comment]
用 loadsh merge  merge 一下吧，是一个多级嵌套的问题

**Comment by whinc** [comment]
有几个疑问：
1. 上面截图中的`values`已经拿到了依赖项的值，并且是正确的嵌套关系， nameValues 是否是多余？作用是什么呢？
2. 上面生成 `values` 时 `{...pre, ...noFormatValue, ...Value}`，这里这样展开可能会出现覆盖
3. `{...values, ...nameValues}`展开也可能会出现覆盖

这里的几种可能出现展开的情况，是否分开成三个独立对象存储会更好些？这样不会因展开对象时覆盖导致丢失信息

**Comment by chenshuai2144** [comment]
> 上面截图中的values已经拿到了依赖项的值，并且是正确的嵌套关系， nameValues 是否是多余？作用是什么呢？

里面是所有的值，不是当前依赖的值，所以需要计算一下

> 覆盖

覆盖的问题用  loadsh merge  来解决一下，因为name是相似的

**Comment by whinc** [comment]
好的，我抽空再看下后更新PR

**Comment by whinc** [comment]
这里我梳理了下，分为一下几种情况：
- `<ProFormDependency>`**不在**`<ProFormList>`中：根据`name`声明的依赖项，从全局取值（情形 1）
- `<ProFormDependency>`**在**`<ProFormList>`中
  - `<ProFormDependency>`的`ignoreFormListField`为`true`：根据`name`声明的依赖项，从全局取值（情形 2）
  - `<ProFormDependency>`的`ignoreFormListField`为`false`：根据`name`声明的依赖项，从局部取值（情形 3）

其中情形3目前的处理是只从局部取值。

更好的处理可能是优先从局部取值，取不到时再从全局取值，不过这个需要知道当前 依赖项有哪些是出现在局部哪些不是，这次PR先不涉及。

这个 PR 同时修复了

**Comment by whinc** [comment]
这个 PR 同时修复了另一个bug
![image](https://user-images.githubusercontent.com/5096493/121326226-ef9dfe00-c944-11eb-8177-a67d69fccc8b.png)
![image](https://user-images.githubusercontent.com/5096493/121326290-ffb5dd80-c944-11eb-986b-fab73f7c38ec.png)

**Comment by furylee** [comment]
但是直接传C好像也行

**Comment by whinc** [comment]
> 但是直接传C好像也行

能否贴下代码？

**Comment by furylee** [comment]
```{
  "a": 1,
  "b": 2,
  "c": {
    "c": {
      "a": "55"
    }
  }
}

<ProFormDependency name={['a', 'b', ['c']]}>
```
这样子

**Comment by whinc** [comment]
> ```
>   "a": 1,
>   "b": 2,
>   "c": {
>     "c": {
>       "a": "55"
>     }
>   }
> }
> 
> <ProFormDependency name={['a', 'b', ['c']]}>
> ```
> 
> 这样子

传"c"获取的是整个c字段值，可以达到目的（其实通过第二个参数form.getFiledsValue可以获取表单任意值）。不过该issue的主要问题是，第一个参数与文档描述的用法不一致问题，根据文档第一个参数应该包含name所声明的依赖参数，并且这些依赖参数变化时自动触发当前表单字段的更新
