### ISSUE TITLE
👑 [需求]ProTable 枚举值是对象的情况如何处理？

### ISSUE THREAD

**Issue by Lind-pro** [ant-design/pro-components#2895]
### 🥰 需求描述
![image](https://user-images.githubusercontent.com/18098618/120290022-812dc000-c2f4-11eb-9e79-d8693f24633d.png)

看到官网都是如下情况，想问一下，如果值是上图对象的这种情况，valueEnum应该怎么处理呢？
```tsx
const valueEnum = {
  all: { text: '全部', status: 'Default' },
  running: { text: '运行中', status: 'Processing' },
  online: { text: '已上线', status: 'Success' },
  error: { text: '异常', status: 'Error' },
};

const columns: ProColumns<TableListItem>[] = [
  {
    title: '状态',
    key: 'select',
    valueType: 'select',
    dataIndex: 'status',
    initialValue: ['all'],
    width: 100,
    valueEnum,
  }]
```

**Comment by chenshuai2144** [comment]
用 renderText 试试

`renderText={(item)=>item.value}`

**Comment by Lind-pro** [comment]
> 用 renderText 试试
> 
> `renderText={(item)=>item.value}`

这样表格展示是没问题，但是枚举是对象自动生成的搜索表单就不行了。下拉选项就不能根据枚举渲染了

**Comment by chenshuai2144** [comment]
那你还是 map 下 datasource 吧，不然很难处理

**Comment by Lind-pro** [comment]
> 那你还是 map 下 datasource 吧，不然很难处理

好吧，那也就是说接口返回的数据不支持对象枚举吧。。。
每个接口去map一下也不太靠谱，应该看看这么改造一下支持对象枚举

**Comment by chenshuai2144** [comment]
让你们后端改一下呢？

**Comment by Lind-pro** [comment]
> 让你们后端改一下呢？

后端返回枚举对象应该很常见吧。我还是自己改造一下ProTable试试。

**Comment by chenshuai2144** [comment]
一般不会存对象的，这样sql 就不好写了，也不方便接入别人家的系统

**Comment by Lind-pro** [comment]
> 一般不会存对象的，这样sql 就不好写了，也不方便接入别人家的系统

后端无法修改。存数据库实际上是存的字符串，再查询出来的时候做了数据转换，因为后端系统不仅仅只是给前端用，还有一些其他情况
