### ISSUE TITLE
🐛[BUG] ProTable columns ellipsis  在字体小于14px的情况下出现问题

### ISSUE THREAD

**Issue by hemengke1997** [ant-design/pro-components#2898]
### 🐛 bug 描述

ProTable columns ellipsis  在字体小于14px的情况下出现问题

### 📷 复现仓库

https://github.com/hemengke1997/testAntd.git

### 💻 复现代码

```
import ProTable from '@ant-design/pro-table';
import './index.module.less';

const B = () => {
  const columns = [
    {
      dataIndex: 'a',
      title: '测试1',
      ellipsis: true,
      width: 120,
    },
    {
      dataIndex: 'b',
      title: '测试2',
    },
  ];
  const dataSource = [
    {
      a: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      b: 'xxxxxxxxxxxxxxxxxxx',
    },
    {
      a: 'mmmmmmmm',
      b: 'yyyyyyyyyyyyyyyyy',
    },
  ];

  return (
    <div>
      <ProTable columns={columns} dataSource={dataSource}></ProTable>
    </div>
  );
};
```

### © 版本信息

- "@ant-design/pro-table": "^2.30.8"
- "umi": "^3.4.0",
- 浏览器环境 chrome
- 开发环境 windows

### 🚑 其他信息

![动画7](https://user-images.githubusercontent.com/49073282/120297210-74f93100-c2fb-11eb-93b0-312eb23f2096.gif)

**Comment by hemengke1997** [comment]
@chenshuai2144  @xiaohuoni   用antd的table，无法复现，所以把issue提这儿来的，麻烦两位帅哥帮帮

**Comment by hemengke1997** [comment]
@yoyo837  https://github.com/ant-design/ant-design/issues/13825#issue-393945737
兄弟，我发现这个issuse还是你提的，曾经提问题的人，已经进蚂蚁了，厉害啊。。

**Comment by yoyo837** [comment]
没在蚂蚁，在“宇宙第一城”某个角落打临工。

**Comment by hemengke1997** [comment]
> 没在蚂蚁，在“宇宙第一城”某个角落打临工。

大哥，能教教我怎么pr吗，我想帮忙解决问题，一直搞不明白这个pr是怎么操作的。

**Comment by yoyo837** [comment]
先fork出来，在你的分支改好，push到你的分支，然后来

![image](https://user-images.githubusercontent.com/6134547/120303158-264e9580-c301-11eb-9cbd-49cbb8df06f5.png)

**Comment by DerrickTel** [comment]
https://codesandbox.io/s/7bf4g?file=/index.js
老铁，是antd的bug

**Comment by hemengke1997** [comment]
> 老铁，是antd的bug

对头，应该是计算字体大小没对导致的问题
