### ISSUE TITLE
🐛[BUG] pro-table 的 ellipsis = true， 会出现多个tooltip

### ISSUE THREAD

**Issue by codering** [ant-design/pro-components#29]
### 🐛 bug 描述

pro-table 的 ellipsis = true， 会出现多个tooltip

### 📷 复现步骤

设置column的ellipsis=true；

const columns = [{
      title: 'xx信息',
      dataIndex: 'content',
      ellipsis: true,
      copyable: true,
      width: 400,
},
xxxx,
xxxx,
]

### 🏞 期望结果

去掉Tooltip，直接用antd自带的即可。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/2271825/88554886-a2c97580-d059-11ea-93a5-eb034e55a0c7.png)

**Comment by chenshuai2144** [comment]
antd 没有自带的，那个是浏览器的 title。

这个的确是个问题， 在antd中有讨论

**Comment by codering** [comment]
我看最新的antd已经时可配置的了 https://ant-design.gitee.io/components/table-cn/#components-table-demo-ellipsis-custom-tooltip。

是pro-table实现的时候忽略了 `showTitle` 属性才会导致这个问题吧。


我个人偏向于先用原生的title属性，然后才是Tooltip组件，这样过渡比较自然些。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/25775 这个怎么不搞了？

**Comment by chenshuai2144** [comment]
ref https://github.com/ant-design/ant-design/pull/26173

**Comment by chenshuai2144** [comment]
已经修复，并且发布到最新版本

**Comment by zim-lee** [comment]
大佬，修复了么，为啥我这里还显示两个，浏览器原生的title依然存在，而且pro的`ellipsis`只能用Boolean值，不能设置`showTitle`
