### ISSUE TITLE
👑 [需求]ProTable Form是否可以分别设置新增和编辑时的fieldProps

### ISSUE THREAD

**Issue by liuyang-1990** [ant-design/pro-components#2900]
### 🥰 需求描述

使用ProTable快速实现增删改查时，遇到以下问题：
   当type='form'时，设置的fielProps 用于生成的搜索表单和新增/编辑表单，
 比如某一个字段可以搜索，可以新增，但不能编辑，此时我设置这一列的disabled为true,则三个表单都不能操作这个字段。

期望能区分

**Comment by chenshuai2144** [comment]
fieldProps  支持 function 的




fieldProps | (form,config)=&gt;fieldProps\|&nbsp;fieldProps | 传给渲染的组件的 props，自定义的时候也会传递
-- | -- | --
