### ISSUE TITLE
🧐[问题]ProFormList 添加读写模式的切换

### ISSUE THREAD

**Issue by myzhoulang** [ant-design/pro-components#2904]
### 🧐 问题描述

使用ProFormList，会有对每一组数据有 读和写的模式，在actionRender自定义了一个编辑操作，这个编辑操作如何空值读写模式的切换

### 💻 示例代码

[示例代码](https://codesandbox.io/s/shuzushujuduxiemoshi-tiw7s?file=/App.tsx)

**Comment by chenshuai2144** [comment]
看起来只能封装一下，这个做的优点蛋疼，要不直接用的 可编辑表格算了
