### ISSUE TITLE
🧐[问题]PageContainer 默认带了水印 不需要怎么去掉

### ISSUE THREAD

**Issue by elainezhou0419** [ant-design/pro-components#2906]
### 🧐 问题描述
PageContainer 默认带了水印 如果不需要的页面怎么去掉

**Comment by chenshuai2144** [comment]
waterMarkProps | 配置水印，水印是 PageContainer 的功能，layout 只是透传给 PageContainer | WaterMarkProps | -
-- | -- | -- | --






在  prolayout 上去掉这个配置
