### ISSUE TITLE
有没有办法拿到pro table里面的搜索框的值🧐[问题]

### ISSUE THREAD

**Issue by babizhu** [ant-design/pro-components#2908]
### 🧐 问题描述

我想做一个搜索并导出excel的功能，所以希望能拿到protable自带的搜索关键字
 不知道有没有办法能拿到

**Comment by whinc** [comment]
request 的第一个参数中的 `keyword` 字段即为搜索关键字

**Comment by babizhu** [comment]
> props 中的`request` 的第一个参数中的 `keyword` 字段即为搜索关键字

我是想拿到搜索的组合条件

**Comment by oxygen-xx** [comment]
@babizhu ,请问最后是如何得到这些参数的。

**Comment by chenshuai2144** [comment]
用formRef 可以 get 到的。

**Comment by qq1170623178** [comment]
@chenshuai2144  如果设置search=false ，formRef。current为空，这时候怎么获取keyword的值
