### ISSUE TITLE
🧐[问题]  使用ProDescriptions，设置loading 等于 true 后，request就不再请求数据了，页面始终处于loading状态

### ISSUE THREAD

**Issue by suu1923** [ant-design/pro-components#2911]
### 💻 示例代码

`const [loading,setLoading] = useState<boolean>(true)
    <ProDescriptions
      title="产品详情页"
      size="middle"
      column={2}
      loading={loading}
      bordered={true}
      params={{
        product_id: product_id, 
        merge: merge?merge:false
      }}
      request={fetchProductInfoData}
      columns={columns}
    />`

**Comment by chenshuai2144** [comment]
loading 是受控的，并且在loading
期间不会发起请求，你需要配合 onLoadingChange 一起使用
