### ISSUE TITLE
👑  ProDescriptions 标签对齐

### ISSUE THREAD

**Issue by chkaos** [ant-design/pro-components#2912]
### 🥰 需求描述

希望提供 ProDescriptions 标签对齐，和表单一样

**Comment by chenshuai2144** [comment]
需要自己写样式的，看看 antd 的  descriptions。我们这里只能做一些预设

https://ant.design/components/descriptions-cn/#API

**Comment by chenshuai2144** [comment]
需要自己写样式的，看看 antd的  descriptions

https://ant.design/components/descriptions-cn/#API
