### ISSUE TITLE
🐛[BUG]新版Chrome下ProTable左右结构布局bug

### ISSUE THREAD

**Issue by johnninja** [ant-design/pro-components#2915]
### 🐛 bug 描述
左右结构的ProTable布局撑破了。
以前是没问题的，我最近也没更新代码库，所以怀疑是Chrome升级导致的？

### 📷 复现步骤

Chrome更新到最新版，然后查看官网地址：[左右结构](https://procomponents.ant.design/components/table#%E5%B7%A6%E5%8F%B3%E7%BB%93%E6%9E%84)

### © 版本信息

- ProComponents 版本: 官网版本
- umi 版本：官网版本
- 浏览器环境：Chrome 91.0.4472.77（正式版本） (x86_64)
- 开发环境：mac OS

**Comment by chenshuai2144** [comment]
等 antd 修把，改动挺大的。
