### ISSUE TITLE
🧐[问题]EditableProTable 实时保存的编辑表格中如何新增的多个数据如何变成可编辑行

### ISSUE THREAD

**Issue by G21iwenjun** [ant-design/pro-components#2919]
### 🧐 问题描述

EditableProTable 实时保存的编辑表格中如何新增的多个数据如何变成可编辑行

### 🚑 其他信息

<img width="724" alt="Snipaste_2021-06-03_22-50-07" src="https://user-images.githubusercontent.com/25291272/120665205-2647c480-c4be-11eb-9c3d-e42a5462defe.png">
<img width="559" alt="Snipaste_2021-06-03_22-52-36" src="https://user-images.githubusercontent.com/25291272/120665527-6f981400-c4be-11eb-833f-d6e275a742ea.png">

**Comment by G21iwenjun** [comment]
没明白，是setState改变的state之后EditableProTable 不会重新渲染吗，还是说要用什么语法让新增的数据成可编辑行。

**Comment by chenshuai2144** [comment]
editableKeys | 正在编辑的行，受控属性。 默认&nbsp;key&nbsp;会使用&nbsp;rowKey&nbsp;的配置，如果没有配置会使用&nbsp;index，建议使用 rowKey | Key[] | -
-- | -- | -- | --




同时操作一下 editableKeys，把 key 同步设置进来
