### ISSUE TITLE
🐛[BUG]ellipsis的内容过多时，会撑满整个浏览器的高度还多，建议给ellipsis配置高度限定或字数限定属性

### ISSUE THREAD

**Issue by WaiKoeng** [ant-design/pro-components#2923]
### 🐛 bug 描述

ellipsis的内容过多时，会撑满整个浏览器的高度还多，建议给ellipsis配置高度限定或字数限定属性

### 📷 复现步骤

字段输入内容非常多时，
![image](https://user-images.githubusercontent.com/17409271/120758593-9ac54680-c544-11eb-9d6b-05d5527641b5.png)

### 🏞 期望结果

ellipsis属性支持高度或者限定字数

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你可以直接控制数据来实现，框架做什么多很容易出问题

**Comment by WaiKoeng** [comment]
> 你可以直接控制数据来实现，框架做什么多很容易出问题

好像对于后台返回的数据在columns中对text进行截断的render处理，并不会在ellilpsis 的悬浮框中生效。是否ellipsis的操作对象还是text本身，而无法对render后的数据进行ellipsis呢？

**Comment by chenshuai2144** [comment]
renderText 可以单独做处理

**Comment by WaiKoeng** [comment]
> renderText 可以单独做处理

可以了。感谢！
