### ISSUE TITLE
🐛[BUG]支持按需加载吗？

### ISSUE THREAD

**Issue by Liuxl1996** [ant-design/pro-components#2926]
["import",{
        "libraryName": "@ant-design/pro-table",
        "libraryDirectory": "lib"
      },"ant-design"
    ]

**Comment by chenshuai2144** [comment]
不支持的，我们用的是 tree shaking

**Comment by Liuxl1996** [comment]
> 不支持的，我们用的是 tree shaking

那需要添加按需引入ant-design依赖怎么办呢？

**Comment by Liuxl1996** [comment]
> 不支持的，我们用的是 tree shaking

好的，谢谢
