### ISSUE TITLE
🧐[问题]repo合并之后如何更加方便的查看每一个component的changelog?

### ISSUE THREAD

**Issue by nylqd** [ant-design/pro-components#293]
### 🧐 问题描述

Repo合并之后，如何方便的查看每一个component的changelog?

现在repo合并的这种发版模式，很难在release页面查看changelog

**Comment by ray1347227** [comment]
![image](https://user-images.githubusercontent.com/21354564/91115790-974f8580-e6bd-11ea-9799-2c315ed8502f.png)
是说这个么

**Comment by chenshuai2144** [comment]
人肉维护了一份。
https://procomponents.ant.design/changelog/pro-card
