### ISSUE TITLE
🐛[BUG]只要在`protable`中使用`loading`这个接口，右上角刷新`reload`要点两次才会触发

### ISSUE THREAD

**Issue by aiyuchen** [ant-design/pro-components#2938]
### 🐛 bug 描述
只要在`protable`中使用`loading`这个接口，右上角刷新`reload`要点两次才会触发

### 📷 复现步骤
下面有提供在线演示链接
```
export default () => {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    setTimeout(() => setLoading(false), 3000);   // 3秒后结束loading
  }, []);
  return (
   <ProTable<TableListItem>
      manualRequest={true}
      columns={columns}
      loading={loading}    // 使用这个接口会造成reload要点2次才能触发，去掉后正常
   />
  );
}
```

### 🏞 期望结果
无论是否使用`loading`这个接口，右上角刷新`reload`每次点击都会触发

### 💻 复现代码
在线演示：https://codesandbox.io/embed/wuchaxunbiaodan-forked-7u9qj?fontsize=14&hidenavigation=1&theme=dark

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]  @ant-design/pro-table: 2.39.2
- umi 版本 --
- 浏览器环境. chrome
- 开发环境 [e.g. mac OS].  codesandbox

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/578141/120883567-7767cd80-c610-11eb-93bf-3921aeaec728.png)

**Comment by chenshuai2144** [comment]
loading 期间是不会发起新的网络请求的，不然会造成很多重复的请求对服务器来说也是个压力

**Comment by aiyuchen** [comment]
@chenshuai2144 不是loading期间，是loading之后，再点刷新，要点2次才能触发
