### ISSUE TITLE
🐛[BUG] 在手机上组件的内部设置像重置，确认只能显示成中文

### ISSUE THREAD

**Issue by gachen95** [ant-design/pro-components#2939]
### 🐛 bug 描述

希望PROTABLE的第 1-5 条/总共 100 条在手机上只能显示成英文

### 📷 复现步骤
已经
export default {
  locale: {
    default: 'en-US',
    antd: false,
    title: false,
    baseNavigator: true,
    baseSeparator: '-',
  },
};
电脑上显示为英文， 手机上一直为中文

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
应该是 api 不支持， 搞个 profill 吧
