### ISSUE TITLE
🐛[BUG]pro-table 2.6.1， fieldProps 中设置 rules 不生效？还有 form 模式有labelWidth 和 defaultCollapsed 的警告。

### ISSUE THREAD

**Issue by zhou0818** [ant-design/pro-components#294]
### 🐛 bug 描述

fieldProps 中设置 rules 不生效，用 formItemProps 可以设置，但是又提示 formItemProps 即将废弃。
第一次切到 form 模式，有警告：
```
Warning: React does not recognize the `defaultCollapsed` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `defaultcollapsed` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
```
Warning: React does not recognize the `labelWidth` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `labelwidth` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
### 📷 复现步骤

pro-table 的 form 模式，type 设置为 form
### 🏞 期望结果

不要报警告
### © 版本信息

- umi 版本 3.2.0
- 浏览器环境 Chrome
- 开发环境 [e.g. mac OS]

**Comment by yaoguoba** [comment]
2.6.1为啥在我这里fieldProps又恢复成formItemProps了...，刚从2.6.0改过来

**Comment by zhou0818** [comment]
> 2.6.1为啥在我这里fieldProps又恢复成formItemProps了...，刚从2.6.0改过来

而且会有个警告，说是别用 formItemProps

**Comment by yaoguoba** [comment]
> > 2.6.1为啥在我这里fieldProps又恢复成formItemProps了...，刚从2.6.0改过来
> 
> 而且会有个警告，说是别用 formItemProps

估计是回滚了

**Comment by chenshuai2144** [comment]
from 模式凑合用一下，bug 估计挺多的，等 proForm 完全完成之后可能才能变得完美

**Comment by yangzhenwang** [comment]
fieldProps 中设置 rules 不生效，用 formItemProps 可以设置，但是又提示 formItemProps 即将废弃。这两个api到底使用哪一个 而且会有个警告，说是别用 formItemProps 
![image](https://user-images.githubusercontent.com/22334521/91386257-2f3ba380-e865-11ea-9a3c-97f2805d307f.png)

**Comment by zhou0818** [comment]
> from 模式凑合用一下，bug 估计挺多的，等 proForm 完全完成之后可能才能变得完美

proForm完成以后不用这个form模式了吗？

**Comment by chenshuai2144** [comment]
Form 模式是用ProForm实现的
________________________________

**Comment by HengCC** [comment]
我想说这个也凑活不了啊..能修吗

**Comment by itsuki0927** [comment]
我一直都没搞懂`formItemProps`和`fieldProps`的区别
