### ISSUE TITLE
🐛[BUG] valueType: 'date', 本地测试 时间不带时分秒，但是到了生产环境，自动带上了当前的时分秒

### ISSUE THREAD

**Issue by ParkerTzh** [ant-design/pro-components#2942]
### 🐛 bug 描述

本地测试 时间不带时分秒，但是到了生产环境，自动带上了当前的时分秒

本地的：
![image](https://user-images.githubusercontent.com/42679837/120919913-c2581280-c6ee-11eb-9382-83f9318befe7.png)

线上的：

![image](https://user-images.githubusercontent.com/42679837/120919899-ae141580-c6ee-11eb-907f-b133cc448aef.png)

代码：
`{
      title: '创建时间',
      dataIndex: 'createTime',
      key: 'createTime',
      tip: '创建时间',
      valueType: 'date',
    },`

**Comment by chenshuai2144** [comment]
更新下依赖试试看起来是 valuetype 失效了
