### ISSUE TITLE
👑 [需求] 希望form增加valueType='card'类型，对布局提供支持，

### ISSUE THREAD

**Issue by meyerlee** [ant-design/pro-components#2944]
### 🥰 需求描述
最近在重构以前做的一个自动生成Form的东西，
试用了SchemaForm感觉不错，现在能通过 json+valueType 做很多工作了。
目前遇到的问题是SchemaForm对布局支持不太好，
比如要实现多列的布局就不好处理

1， 想要生成一个没有lable的元素， 或 水平布局的时候偶尔有个垂直布局的元素,
现在一定会生成  lable: item 的格式
可能要支持另外一个render方法，让用户可以完全定制一个form.item的生成， 

2.  似乎可以增加ProCard的支持，让用户端可以控制布局。

### 🧐 解决方案

          if (item.valueType === 'card') {
            if (!item.columns) return null;
            return (
              <ProCard key={key} label={item.title} {...item.fieldProps}>
                {genItems(item.columns)}
              </ProCard>
            );
          }

-- 类似group的支持
          if (item.valueType === 'group') {
            if (!item.columns) return null;
            return (
              <ProFormGroup key={key} label={item.title} {...item.fieldProps}>
                {genItems(item.columns)}
              </ProFormGroup>
            );
          }

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/8414971/120950067-88cbe980-c778-11eb-887d-c6f254de0660.png)

![image](https://user-images.githubusercontent.com/8414971/120951278-0c86d580-c77b-11eb-883a-c015af305950.png)

**Comment by chenshuai2144** [comment]
暂时没有安排，如果有人想 pr 直接提交
