### ISSUE TITLE
🐛[BUG]EditableProTable 清除日期框内容，对应字段无法清除

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#2946]
原有数据，清除日期选择框后保存，没有覆盖掉
![image](https://user-images.githubusercontent.com/12421552/120952316-5cff3280-c77d-11eb-9100-be42cd014eeb.png)
![image](https://user-images.githubusercontent.com/12421552/120952347-6b4d4e80-c77d-11eb-8d32-5dbbe65719ba.png)
![image](https://user-images.githubusercontent.com/12421552/120952365-71dbc600-c77d-11eb-860f-92b797eec76d.png)
![image](https://user-images.githubusercontent.com/12421552/120952382-7dc78800-c77d-11eb-8668-421827795cce.png)

**Comment by edifangyi** [comment]
"@ant-design/pro-table": "^2.39.0",

**Comment by chenshuai2144** [comment]
为空的确不会默认覆盖，这个需要改一下
