### ISSUE TITLE
🐛[BUG] ProTable ellipsis 为true 不跟随浏览器宽度恢复展示

### ISSUE THREAD

**Issue by codering** [ant-design/pro-components#2948]
### 🐛 bug 描述
ProTable Column 设置 ellipsis 为 true后，在宽度不够时会自动显示省略，但宽度够时，却依然显示省略。这个和antd table 表现不一致。

### 📷 复现步骤

通过目前官网demo可以复现，改变浏览器窗口宽度即可复现。
如 https://g8uf5.csb.app

### 🏞 期望结果

和antd table 表现一致。

### 💻 复现代码

https://codesandbox.io/s/datasource-forked-g8uf5?file=/App.tsx:2097-2105

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by jiyingzhi** [comment]
+1

**Comment by DerrickTel** [comment]
https://github.com/ant-design/ant-design/issues/30894
