### ISSUE TITLE
🧐[问题]搜索表单配置月份区间

### ISSUE THREAD

**Issue by YunSmile** [ant-design/pro-components#295]
### 🧐 问题描述

搜索表单配置月份区间，但是传来的参数是日期时间格式

### 💻 示例代码
 {
      title: '账期',
      dataIndex: 'billMonth',
      valueType: "dateRange",
      fieldProps: {
        picker: "month",
      },
      render: (text, record) => {
        return record.billMonth
      }
    },
![image](https://user-images.githubusercontent.com/18326947/91125790-27e59000-e6d5-11ea-94a4-f63fb2d02e37.png)

![image](https://user-images.githubusercontent.com/18326947/91125774-1b613780-e6d5-11ea-8c2a-46052e18b49b.png)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/18326947/91125732-fa98e200-e6d4-11ea-89ed-5b3b706910d9.png)

**Comment by YunSmile** [comment]
![image](https://user-images.githubusercontent.com/18326947/91125872-57949800-e6d5-11ea-858f-75ff3c3180c9.png)
补充下，选择面板显示月份，但是值填入后变日期格式

**Comment by chenshuai2144** [comment]
我们现在还不支持月份，你有兴趣支持一下吗？
类似 valueType=month

**Comment by l745230** [comment]
@YunSmile 这个水印效果,能分享下吗~~

**Comment by YunSmile** [comment]
> @YunSmile 这个水印效果,能分享下吗~~
npm 搜 “web-watermark"

**Comment by chenshuai2144** [comment]
close  by https://github.com/ant-design/pro-components/pull/385

我们支持了 周和月
