### ISSUE TITLE
🐛[BUG] 在EditableProTable中setFieldsValue更新数据没有同步到value

### ISSUE THREAD

**Issue by ashen114** [ant-design/pro-components#2950]
### 🐛 bug 描述

通过fieldProps中from.setFieldsValue设置当前行数据，行数据被更新且同步UI了，但是EditableProTable的value值没有被同步到，即图中的dataSource

![image](https://user-images.githubusercontent.com/28629247/120959346-20870300-c78c-11eb-9012-4175b2d27f17.png)
![image](https://user-images.githubusercontent.com/28629247/120968053-f1c45900-c79a-11eb-9136-94dd516aaea0.png)

### 🏞 期望结果

from.setFieldsValue设置的值能同步到dataSource

### © 版本信息

- ProComponents 版本:    "@ant-design/pro-table": "2.39.2",
- umi 版本:    "umi": "^3.4.0",
- 浏览器环境:  Chrome/90.0.4430.212
- 开发环境: win10

**Comment by ashen114** [comment]
setDataSource(from.getFieldsValue(true))可以了

**Comment by ayaayaayaai** [comment]
setDataSoure 用在onValuesChange里吗 使用from.getFieldsValue(true)获取的setFieldsValue值还不是最新的
