### ISSUE TITLE
🐛[BUG]EditableProTable可编辑表格分页的onChange事件被调用了2次

### ISSUE THREAD

**Issue by xxxxue** [ant-design/pro-components#2955]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/32764266/121006408-72974b00-c7c3-11eb-8cbc-3a7c27867ade.png)

### 📷 复现步骤

下面是 pagination  ↓
-----------------------

pagination={
                    {
                        total: 100,
                        defaultPageSize: 20,
                        size: 'default',
                        position: ["bottomCenter"],
                        showQuickJumper:true,
                        onChange:(pageIndex,pageSize)=>{
                            console.log('pageOnChange:',pageIndex,pageSize)
                        },
                    }
}

### 🏞 期望结果

发生改变后, onChange 只被调用一次
### © 版本信息

- ProComponents 版本:  ["@ant-design/pro-table": "^2.39.2",]
- umi 版本  无
- 浏览器环境  Edge 谷歌内核 版本 91.0.864.41 (官方内部版本) (64 位)
- 开发环境 [win 10]

**Comment by chenshuai2144** [comment]
fixed in 2.24.0
