### ISSUE TITLE
🧐[问题] ProDescriptions editable 可编辑模式的一些疑问

### ISSUE THREAD

**Issue by duwei54** [ant-design/pro-components#2956]
### 🧐 问题描述

小伙伴们大家好, 今天尝试了一下ProDescriptions editable 可编辑模式.有一些疑问.
先说一下需求, 传入一些初始化数据,部分仅展示,部分展示且可编辑,然后提交编辑后的数据到后端.

1. 设置了dataSource之后,编辑后的项,保存后展示还是原来的.只能用request返回才可以.
2. 想统一获取所有表单数据. 看了文档可以使用`Form.useForm` 生成引用传入editable.但是编辑保存完成后,通过`form.getFieldsValue()`获取的值是空. 当某个项处于编辑状态是调用`form.getFieldsValue()`能获取当前正在编辑项的值.  这个是正常表现吗?如果是正常表现,那如何才能一次获取所有表单项值.
3. 如果想像Form表单那样,控制某些项的验证规则,错误时给与提示.应该如何做呢.

[示例代码](https://codesandbox.io/s/kebianjidedingyiliebiao-forked-2tgl1?file=/App.tsx)

**Comment by chenshuai2144** [comment]
`设置了dataSource之后,编辑后的项,保存后展示还是原来的.只能用request返回才可以.
`

这个需要使用 onSave 获得保存以后的数据的

**Comment by duwei54** [comment]
@chenshuai2144 感谢大佬答疑.   能否帮忙看看后面两个呢 😄

**Comment by sunxia628** [comment]
> `设置了dataSource之后,编辑后的项,保存后展示还是原来的.只能用request返回才可以. `
> 
> 这个需要使用 onSave 获得保存以后的数据的
类组件如何获取form实例，为了设置可编辑项的值，最后用到了getValueFromEvent（绕过了form.setFieldsValue）；
但是校验的时候formItemProps的rules不能接受validator的错误信息，虽然校验规则生效了，但在表格的tooltip中只展示一个小圆点？

**Comment by duwei54** [comment]
> > 类组件如何获取form实例，为了设置可编辑项的值，最后用到了getValueFromEvent（绕过了form.setFieldsValue）；
> > 但是校验的时候formItemProps的rules不能接受validator的错误信息，虽然校验规则生效了，但在表格的tooltip中只展示一个小圆点？
> 
> [#3131 (comment)](https://github.com/ant-design/pro-components/issues/3131#issue-933476954)

没看明白.  这两个问题有关联还是啥?

**Comment by chenshuai2144** [comment]
>  设置了dataSource之后,编辑后的项,保存后展示还是原来的.只能用request返回才可以.

<html>
<body>


controlled | 是否受控, 如果受控每次编辑都会触发 onChange，并且会修改 dataSource | boolean | false
-- | -- | -- | --



</body>
</html>


> 想统一获取所有表单数据. 看了文档可以使用Form.useForm 生成引用传入editable.但是编辑保存完成后,通过form.getFieldsValue()获取的值是空. 当某个项处于编辑状态是调用form.getFieldsValue()能获取当前正在编辑项的值. 这个是正常表现吗?如果是正常表现,那如何才能一次获取所有表单项值.

是的

**Comment by duwei54** [comment]
@chenshuai2144 没看明白 `controlled` 这个属性在文档和 `ProDescriptionsProps`中都没看到呢.
