### ISSUE TITLE
🐛[BUG]只要在`protable`中使用`loading`这个接口，右上角刷新`reload`要点两次才会触发

### ISSUE THREAD

**Issue by aiyuchen** [ant-design/pro-components#2957]
### 🐛 bug 描述
只要在`protable`中使用`loading`这个接口，右上角刷新`reload`要点两次才会触发
>#和问题2938一样，但是开发人员显然理解错了意思，不是在loading中刷新，而是在loding结束后点刷新要点2次才能触发
> https://github.com/ant-design/pro-components/issues/2938

### 📷 复现步骤
下面有提供在线演示链接
```
export default () => {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    setTimeout(() => setLoading(false), 3000);   // 3秒后结束loading
  }, []);
  return (
   <ProTable<TableListItem>
      manualRequest={true}
      columns={columns}
      loading={loading}    // 使用这个接口会造成reload要点2次才能触发，去掉后正常
   />
  );
}
```

### 🏞 期望结果
无论是否使用`loading`这个接口，右上角刷新`reload`每次点击都会触发

### 💻 复现代码
在线演示：https://codesandbox.io/embed/wuchaxunbiaodan-forked-7u9qj?fontsize=14&hidenavigation=1&theme=dark

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]  @ant-design/pro-table: 2.39.2
- umi 版本 --
- 浏览器环境. chrome
- 开发环境 [e.g. mac OS].  codesandbox

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/578141/120883567-7767cd80-c610-11eb-93bf-3921aeaec728.png)

**Comment by aiyuchen** [comment]
> Hello @aiyuchen. Please provide a online reproduction by forking this link https://codesandbox.io/ or a minimal GitHub repository.
> 
> 你好 @aiyuchen, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

在线演示：https://codesandbox.io/embed/wuchaxunbiaodan-forked-7u9qj?fontsize=14&hidenavigation=1&theme=dark

**Comment by chenshuai2144** [comment]
loading过程中没法刷新的。
