### ISSUE TITLE
dateFormatter="string" dateRange 显示格式问题

### ISSUE THREAD

**Issue by wuhao930406** [ant-design/pro-components#2961]
dateFormatter="string" dateRange 显示格式问题

**Comment by wuhao930406** [comment]
🐛 bug 描述
ProTable search.filterType = "light" , dateFormatter="string" 轻量模式下 columns.valueType = "dateRange"  渲染异常

![image](https://user-images.githubusercontent.com/18044670/121110975-b2e8de80-c840-11eb-8b10-51074c2d5af3.png)



📷 复现步骤
let columns = {
  {
            "title": "团队领导",
            "dataIndex": "dateRange",
            "key": "dateRange",
            "valueType": "dateRange"
  }
}

<ProTable
columns={columns}
search={{
filterType: 'light',//轻量模式
}}
dateFormatter="string"//moment转化 string
path="/api/list"
/>

🏞 期望结果
![image](https://user-images.githubusercontent.com/18044670/121111413-67830000-c841-11eb-9046-59f178c05b44.png)



💻 复现代码
let columns = {
  {
            "title": "团队领导",
            "dataIndex": "dateRange",
            "key": "dateRange",
            "valueType": "dateRange"
  }
}

<ProTable
columns={columns}
search={{
filterType: 'light',//轻量模式
}}
dateFormatter="string"//moment转化 string
path="/api/list"
/>

© 版本信息
ProComponents 版本: "@ant-design/pro-table": "^2.39.2"
umi 版本 "umi": "^3.4.22"
浏览器环境 Google Chrome 版本 90.0.4430.93
开发环境 win10
🚑 其他信息
valueType 为 dateTimeRange 同样存在此问题

**Comment by chenshuai2144** [comment]
修掉了，等发布

**Comment by chenshuai2144** [comment]
close https://github.com/ant-design/pro-components/pull/2867
