### ISSUE TITLE
🧐layout 的 menuItem 对 icon 的处理 为什么和antd menu不一致

### ISSUE THREAD

**Issue by kkaaddff** [ant-design/pro-components#2962]
### 🧐 问题描述

🧐layout 的 menuItem 对 icon 的处理 为什么和antd menu不一致细地描述问题，pro 中直接生成了icon在span中，将整个span传给了menuItem ，这个处理逻辑大致看起来没问题，但是对于需要定制一下menuRender来说就难满足需求了，特别是收缩起来之后
是否可以修改实现将icon传给Menu？ 是有什么其他考虑么？

### 💻 示例代码
` <span className={`${prefixCls}-menu-item`}>
        {icon}
        <span className={`${prefixCls}-menu-item-title`}>{name}</span>
      </span>`

**Comment by chenshuai2144** [comment]
这个是因为prolayout 在写的时候 antd 还不支持 MenuItem 的 icon 属性，所以变成了现在的样子。

**Comment by kkaaddff** [comment]
那现在可以修改一下了嘛？或者PR？

**Comment by chenshuai2144** [comment]
直接上 pr 吧
