### ISSUE TITLE
🐛[BUG] ProFormCaptcha 组件在输入内容后提交会提示未输入内容

### ISSUE THREAD

**Issue by quyuxuan** [ant-design/pro-components#2968]
### 🐛 bug 描述

ProFormCaptcha 组件在输入内容后提交会提示未输入内容

### 📷 复现步骤

给组件添加 Name & rules(required为true)

### 🏞 期望结果
onFinish 可以校验通过

### 💻 复现代码

`<ProFormCaptcha
                        fieldProps={{
                            size: 'large',
                            prefix: <LockOutlined className={styles.prefixIcon} />,
                        }}
                        captchaProps={{
                            size: 'large',
                        }}
                        placeholder='请输入验证码'
                        captchaTextRender={(timing, count) => {
                            if (timing) {
                                return '获取验证码';
                            }
                            return '获取验证码';
                        }}
                        name="code"
                        phoneName='phone'
                        rules={[
                            {
                                required: true,
                                message: (
                                    <FormattedMessage
                                        id="pages.login.captcha.required"
                                        defaultMessage="请输入验证码！"
                                    />
                                ),
                            },
                        ]}
                        countDown="60"
                        onGetCaptcha={async (phone) => {
                            const result = await getPhoneSendMsg({
                                phone,
                            });
                            if (result === false) {
                                return;
                            }
                            message.success('获取验证码成功！');
                        }}
                    />`
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 ^3.4.0
- 浏览器环境
- 开发环境 [e.g. mac OS]
- @ant-design/pro-form": "1.28.0",

**Comment by s464446877** [comment]
遇到同样问题，文档上的例子也是有这个问题

**Comment by 0x30** [comment]
遇到同样的问题

以前就是如下使用的是可以正常

```ts
<ProForm>
     <ProFormCaptcha ...props />
</ProForm>
```

不记得什么版本之后了，上面的就出现问题，获取不到值 即使设置了 name，发现是 value 和 onchange 都未定义

**Comment by harryliuy** [comment]
遇到同样问题

**Comment by quyuxuan** [comment]
我的解决方案是将ant-design/pro-form 固定为1.24.0
