### ISSUE TITLE
Antd ProTable 数据量并不大，显示的字段比较多，有11个，显示数据的速度慢，需要2s左右

### ISSUE THREAD

**Issue by aoyinke** [ant-design/pro-components#297]
### 🧐 问题描述
Antd ProTable 数据量并不大，但是加载速度慢，需要2-3s
并不是接口的问题，接口测速只需要300ms
而且勾选的时候也出现了卡顿
我用Antd Table自己封装了一个功能一模一样的组件，几乎秒显。。。
请问大家有啥可以优化的方法吗

**Comment by chenshuai2144** [comment]
pro-table 里面有个去抖，导致至少需要 200ms 才显示

**Comment by bingo618** [comment]
> pro-table 里面有个去抖，导致至少需要 200ms 才显示

可以配置去掉200ms延迟吗？ProTable布局挺好看，感觉很卡顿。

**Comment by chenshuai2144** [comment]
把你的配置和数据 show 一下，我 debug 一下，200ms 应该无感的

**Comment by chenshuai2144** [comment]
dep of  https://github.com/ant-design/pro-components/issues/297

**Comment by aoyinke** [comment]
麻烦了
"dependencies": {
    "@ant-design/icons": "^4.2.2",
    "@ant-design/pro-layout": "^6.4.8",
    "@ant-design/pro-table": "^2.5.13",
    "@types/lodash.isequal": "^4.5.5",
    "antd": "^4.5.4",
    "classnames": "^2.2.6",
    "js-base64": "^3.4.5",
    "less": "^3.12.2",
    "lodash": "^4.17.20",
    "lodash.isequal": "^4.5.0",
    "moment": "^2.25.3",
    "numeral": "^2.0.6",
    "omit.js": "^2.0.2",
    "path-to-regexp": "2.4.0",
    "qs": "^6.9.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet-async": "^1.0.4",
    "react-router": "^4.3.1",
    "umi": "^3.2.16",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^1.0.18",
    "@types/classnames": "^2.2.7",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.7",
    "@types/jest": "^26.0.10",
    "@types/lodash": "^4.14.159",
    "@types/qs": "^6.9.4",
    "@types/react": "^16.9.46",
    "@types/react-dom": "^16.8.4",
    "@types/react-helmet": "^5.0.13",
    "@umijs/fabric": "^2.2.0",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-react": "^1.5.21",
    "@umijs/preset-ui": "^2.2.6",
    "carlo": "^0.9.46",
    "chalk": "^4.0.0",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "enzyme": "^3.11.0",
    "eslint": "^7.7.0",
    "express": "^4.17.1",
    "gh-pages": "^3.0.0",
    "husky": "^4.0.7",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.0.1",
    "pro-download": "1.0.1",
    "puppeteer-core": "^5.0.0",
    "stylelint": "^13.0.0"
  }
// 数据，每页20条
createTime: "2020-08-21 15:47:06"
createUser: "shenx"
id: 119
imsi: "6666666666666"
insideId: "6666666666666"
macId: "6666666666666"
model: "FW6666666666666"
modelName: "fwe6666666666666"
modifyTime: "2020-08-26 14:29:33"
modifyUser: "admin"
name: "测试6666666666666"
outsideId: "6666666666666"
period: "0"
printMacId: "6666666666666"
status: "3"
typeId: 21
typeName: "水淹6666666666666"

<ProTable
        columns={columns(options, equipValueEnum)}
        pagination={{
          showQuickJumper: true,
        }}                                                                                                                
        actionRef={actionRef}
        request={async (params) => {
          const par = params;
          par.pageNum = params.current;
          try {
            const res = await getAgeingTest(params);
            if (res.code !== 200) {
              message.error(`页面请求数据失败，状态码：${res.code || '网关错误'}`);
            } else {
              return Promise.resolve({
                data: res.data.rows,
                success: true,
                total: res.data.total,
              });
            }
          } catch (error) {
            console.log(error);
          }
          return Promise.resolve({
            success: true,
          });
        }}
        rowKey="id"
        rowSelection={{
          onChange: (selectedRowKeys, selectedRows) => {
            handleSelectedEquip(() => selectedRows);
          },
        }}
        dateFormatter="string"
        toolBarRender={() => [
          <Button
            key="3"
            type="primary"
            onClick={() => {
              dispatch({
                type: 'GlobalModel/changeCreateModalVisible',
                payload: true,
              });
            }}
          >
            开始老化
          </Button>,
        ]}
      />

**Comment by chenshuai2144** [comment]
延迟减少了，但是还是需要1s 左右，因为我们的数据实在 useEffect 才读取的，而table的数据是立马就准备好的，性能上还是有一些差距

**Comment by aoyinke** [comment]
好的，谢谢

**Comment by zhangjingl02** [comment]
@aoyinke  怎么解决的啊？

**Comment by zhangjingl02** [comment]
我也是遇到同样的问题，table  几乎没又延迟的加载，pro table 2-3秒

**Comment by chenshuai2144** [comment]
更新下版本，是因为protable 发起请求比较慢

**Comment by Asence** [comment]
@chenshuai2144 帅哥  我发现一个问题  就是我表格头部搜索是个下拉框  接口返回的特别快  但是下拉框里面值加载出来特别慢，需要5s

**Comment by chenshuai2144** [comment]
是没有触发渲染把，可以把下拉框封成组件，就可以精确控制它的渲染了

**Comment by Asence** [comment]
渲染很慢 好像是等表格数据渲染完毕以后才去渲染的头部的下拉框

**Comment by pollux2015** [comment]
我的表格字段有30多项， 根本没法用， 如果当前页面有input 都输入不了

**Comment by jsonchou** [comment]
31 * 10 的干净表格
render 函数执行了1400次，页面非常卡，代码如下：
``` js
 render: (txt, row, index, action) => }
    console.log('render', 1)
    return null
}
```
注释上述代码，采用默认 valueType，页面渲染性能卓越，开启debounceTime=300 也无用。

**Comment by chenshuai2144** [comment]
render 这个很蛋疼的，因为render 的结果没法缓存，所以每次都要执行，如果需要性能好的话，一定要设施好

**Comment by nkHub** [comment]
我的显示23个字段，，有多个筛选，，开启了省略，加载要6、7秒。。无语了😐

**Comment by Aaron-skech** [comment]
18列 100条数据加载要8到9秒 卡死了

**Comment by zhangjiana** [comment]
我的也出现了这个问题， columns是动态的，接口返回的很快。我把columns 给到之后， 还是加载很慢

**Comment by zhangjiana** [comment]
关闭了`省略`，就好多了。

**Comment by zhoubaibai** [comment]
> 关闭了`省略`，就好多了。

关闭了省略是啥意思呀....

**Comment by hpf0532** [comment]
> > 关闭了`省略`，就好多了。
> 
> 关闭了省略是啥意思呀....

ellipsis: false

**Comment by NARUTOyuyang** [comment]
> 延迟减少了，但是还是需要1s 左右，因为我们的数据实在 useEffect 才读取的，而table的数据是立马就准备好的，性能上还是有一些差距

这优化不了了吗？数据早就返回了，protable 还是在 loading 很久才渲染出来

**Comment by NARUTOyuyang** [comment]
> 好的，谢谢

所以你的渲染慢的问题是怎么解决呢？我 20 个字段，10 个需要 render ，卡的很

**Comment by wx9999** [comment]
> 

你这边解决了嘛

**Comment by wx9999** [comment]
> > 好的，谢谢
> 
> 所以你的渲染慢的问题是怎么解决呢？我 20 个字段，10 个需要 render ，卡的很

请问你解决了嘛

**Comment by xiaoxuehai** [comment]
2024了   遇到同样的问题  这问题解决了吗？

**Comment by XuChaow** [comment]
> pro-table 30列 切换分页很卡很卡

**Comment by XuChaow** [comment]
> > > 好的，谢谢
> > 
> > 
> > 那么你的渲染慢的问题怎么解决？我20个字段，10个需要渲染，卡的很
> 
> 请问你找到我吗
请问你们解决了吗

**Comment by Enoye-ovo** [comment]
能解决的办法是tableRender重新渲染个普通表格，但是protable的toolbar等属性就不能用了

**Comment by webshy** [comment]
我2025年遇到了，500条一页。接口时间500ms，页面需要5、6s才能渲染完成。怎么破，大佬们

**Comment by xiaoxuehai** [comment]
> 我2025年遇到了，500条一页。接口时间500ms，页面需要5、6s才能渲染完成。怎么破，大佬们

看下列是不是加了ellipsis: true，我去掉这个之后，加载速度会快一点，这个用的tooltip导致性能很差

**Comment by webshy** [comment]
> > 我2025年遇到了，500条一页。接口时间500ms，页面需要5、6s才能渲染完成。怎么破，大佬们
> 
> 看下列是不是加了ellipsis: true，我去掉这个之后，加载速度会快一点，这个用的tooltip导致性能很差

我没有加ellipsis: true 这个属性

**Comment by xiaoxuehai** [comment]
> > > 我2025年遇到了，500条一页。接口时间500ms，页面需要5、6s才能渲染完成。怎么破，大佬们
> > 
> > 
> > 看下列是不是加了ellipsis: true，我去掉这个之后，加载速度会快一点，这个用的tooltip导致性能很差
> 
> 我没有加ellipsis: true 这个属性

500行就卡了，你有多少列，贴代码吧

**Comment by webshy** [comment]
> > > > 我2025年遇到了，500条一页。接口时间500ms，页面需要5、6s才能渲染完成。怎么破，大佬们
> > > 
> > > 
> > > 看下列是不是加了ellipsis: true，我去掉这个之后，加载速度会快一点，这个用的tooltip导致性能很差
> > 
> > 
> > 我没有加ellipsis: true 这个属性
> 
> 500行就卡了，你有多少列，贴代码吧
  有18列

 const columns: ProColumns[] = [
    { title: '1', dataIndex: '1' },
    { title: '2', dataIndex: '2', hideInSearch: true, render: (text, record) => <VulTag type={record.a}>{text}</VulTag> },
    { title: '3', dataIndex: '3', hideInSearch: true },
    {
      title: '4', dataIndex: '4', hideInSearch: false, hideInTable: true,
      fieldProps: { showSearch: true },
      valueType: 'select', request: async () => {
        let result: any[] = [];
        await services.LoopController.GetSystemAffected().then((res: any) => {
          if (res.success) {
            if (res?.data) {
              result = res?.data.map((r: any) => {
                return { label: r.name, value: r.id }
              });
            }
          }
        });
        return result;
      }
    },
    { title: '5', dataIndex: '5', hideInSearch: true },
    {
      title: '6', dataIndex: '6', hideInSearch: false,
      renderFormItem: () => {
        return (
          <TreeSelect
            showSearch
            placeholder="请选择"
            dropdownStyle={{ maxHeight: 400, overflow: 'auto' }}
            allowClear
            treeDefaultExpandAll
            treeNodeFilterProp="name"
            showCheckedStrategy="SHOW_ALL"
            treeData={departmentData}
            fieldNames={{ label: 'name', value: 'path' }}
          />
        );
      },
    },
    { title: '7', dataIndex: '7', hideInSearch: true },
    { title: '8', dataIndex: '8', hideInSearch: true },
    { title: '9', dataIndex: '9', hideInSearch: false },
    { title: '10', dataIndex: '10', hideInSearch: true },
    { title: '11', dataIndex: '11', hideInSearch: true },
    { title: '12', dataIndex: '12', hideInSearch: true },
    {
      title: '13', dataIndex: '13', hideInSearch: true, render: (_: any, record: any, index: number) => {
        return <div><Popover title="附件" content={
          <>
            {record?.attachmentFile?.map((attr: any) => {
              return <div style={{ marginTop: '12px' }}>
                <a onClick={() =>
                  services.ExportTaskController.newDownload(attr.id).then((res: any) => {
                    const reader = new FileReader();
                    reader.readAsText(res)
                    reader.onload = function (event) {
                      try {
                        const errorData = JSON.parse(event.target.result);
                        if (errorData.success === false && errorData.errMessage != "" && errorData.errorCode == "ERROR") {
                          message.error(errorData.errMessage)
                        } else {
                          fileDownload(res, `${attr.fileName}`);
                        }
                      } catch (e) {
                        fileDownload(res, `${attr.fileName}`);
                      }
                    }
                  })
                  // href={`${BASE}system-service/attachment/upload/${attr.id}`}
                } >{attr.fileName}</a>
              </div>
            })
            }
          </>
        }
          placement="top" overlayClassName="assets-info-source-popover" >
          <a title={record?.attachmentFile?.length}>{record?.attachmentFile?.length}</a>
        </Popover>
          {
            ['1', '2'].includes(roleName) && <><ImportPenetrationAttachmentForm
              value={record.id}
              trigger={<a style={{ cursor: 'pointer' }}> + </a>}
              onFinish={() => {
                message.success('附件上传成功');
                tableActionRef.current.reloadAndRest();
              }}
            />
              {record?.attachmentFile?.length > 0 && <a style={{ marginLeft: '8px' }} title="删除附件" onClick={() => {
                confirm(record.id)
              }}> -</a>

              }</>}
        </div>
      }
    },
    { title: '14', dataIndex: '14', hideInSearch: true },
    {
      title: '15',
      dataIndex: '15',
      renderFormItem: () => (
        <Select
          showSearch
          mode="multiple"
          allowClear
          placeholder="请选择"
          optionFilterProp="label"
          maxTagCount={2}
          options={dictionaryModel.}
        ></Select>
      ),
      hideInTable: true,
    },
    { title: '16', dataIndex: 'createAt', hideInSearch: true },
    {
      title: '17',
      valueType: 'dateTimeRange',
      hideInTable: true,
      search: {
        transform: (value: any) => ({
          createAtStart: value[0],
          createAtEnd: value[1],
        }),
      },
    },
    {
      title: '18',
      width: 355,
      key: 'option',
      valueType: 'option',
      fixed: 'right',
      render: (text, record) => [
        <Space key="1" size="middle">
          <PenetrationInfo record={record} trigger={<a>详情</a>} />
          {record.status == 1 && <>
            <SubsidiarySystemForm
              title={"所"}
              id={record.id}
              trigger={<a type="primary">11</a>}
              onFinish={() => {
                message.success('所!');
                tableActionRef.current.reloadAndRest();
              }}
            ></SubsidiarySystemForm>
            <LevelAdjustmentForm
              title={"调级"}
              id={record.id}
              trigger={<a type="primary">22</a>}
              onFinish={() => {
                message.success('整成功!');
                tableActionRef.current.reloadAndRest();
              }}
            ></LevelAdjustmentForm>
          </>}
          {(!record.vulConfirm) && <>
            <Access accessible={verify(VulnerabilityCode.UPenetration)}>
              <PenetrationListAddForm
                edit={true}
                value={record.id}
                trigger={<a type="primary">编辑</a>}
                onFinish={() => {
                  tableActionRef.current.reloadAndRest();
                  message.success('编辑成功');
                }}
              />
            </Access>
            <Access accessible={verify(VulnerabilityCode.UPenetration)}>
              <a onClick={() => actions.confirmRequest([record.id])} >33</a>
            </Access>
          </>
          }
          {record.status == 3 && (
            <Access accessible={verify(VulnerabilityCode.UPenetration)}>
              <a onClick={() => actions.viewSureAsset(record)}>44</a>
            </Access>
          )}
          {record.status == 2 &&
            (record.targetType == 1 ? (
              <Access accessible={verify(VulnerabilityCode.COriginal)}>
                <AssetsForm
                  tag="ip"
                  type={formType.add}
                  penetrationFlag={true}
                  value={{ ip_address: record.targetScan, connection_application: [record.applicationName] }}
                  onFinish={() => {
                    message.success('添加成功');
                    tableActionRef.current.reloadAndRest();
                  }}
                  trigger={<a>44</a>}
                />
              </Access>
            ) : (
              <Access accessible={verify(VulnerabilityCode.COriginal)}>
                <AssetsForm
                  tag="url"
                  type={formType.add}
                  penetrationFlag={true}
                  value={{ website_address: record.targetScan, connection_application: [record.applicationName] }}
                  onFinish={() => {
                    message.success('添加成功');
                    tableActionRef.current.reloadAndRest();
                  }}
                  trigger={<a>添加资产</a>}
                />
              </Access>
            ))}
          {parseInt(record.status) !== 4 && (
            <DelConfirm
              text="删除"
              side={true}
              onConfirm={() => actions.delRequest(record.id)}
              access={verify(VulnerabilityCode.DPenetration)}
            />
          )}
          {(['1'].includes(roleName) && record.statusName == '1' && record.disposalStatusName == '2') && <PermeationDisposeForm
            open={dispositionFlag}
            batch={false}
            id={record.id}
            onFinish={() => {
              setDispositionFlag(false)
              message.success('成功');
              tableActionRef.current.reload();
            }}
            trigger={
              <a>55</a>
            }
            onCancel={() => {
              setDispositionFlag(false)
            }}
          />}
        </Space>,
      ],
    },
  ];

**Comment by tylerrrkd** [comment]
> > > > > 我2025年遇到了，500条一页。接口时间500ms，页面需要5、6s才能渲染完成。怎么破，大佬们
> > > > 
> > > > 
> > > > 看下列是不是加了ellipsis: true，我去掉这个之后，加载速度会快一点，这个用的tooltip导致性能很差
> > > 
> > > 
> > > 我没有加ellipsis: true 这个属性
> > 
> > 
> > 500行就卡了，你有多少列，贴代码吧
> > 解决了，使用虚拟滚动

@webshy 大佬，虚拟滚动是内置还是自己手写的方案？

**Comment by webshy** [comment]
> > > > > > 我2025年遇到了，500条一页。接口时间500ms，页面需要5、6s才能渲染完成。怎么破，大佬们
> > > > > 
> > > > > 
> > > > > 看下列是不是加了ellipsis: true，我去掉这个之后，加载速度会快一点，这个用的tooltip导致性能很差
> > > > 
> > > > 
> > > > 我没有加ellipsis: true 这个属性
> > > 
> > > 
> > > 500行就卡了，你有多少列，贴代码吧
> > > 解决了，使用虚拟滚动
> 
> [@webshy](https://github.com/webshy) 大佬，虚拟滚动是内置还是自己手写的方案？

5.9以后版本增加了虚拟滚动设置。如果没可以手写
