### ISSUE TITLE
🧐[问题]: 在ProForm中收集到的值异常

### ISSUE THREAD

**Issue by osCaiwei** [ant-design/pro-components#2971]
### 🧐 问题描述
在modalForm中用Form.Item做了一个联动组件 表单提交时，联动组件内的值被套了一层对象结构

### 💻 示例代码

<ModalForm
      trigger={<Input value={props.value.formulaStr}  />}
      modalProps={{destroyOnClose:true}}
      formRef={formRef}
      title={'计算公式'}
      onFinish={(formValue) => {
        console.log(formValue);
        return Promise.resolve(true)
      }}
    >
      <Form.Item label='选择公式' name='selectFormula'>
        <CommonTableSelect widget='formula'/>
      </Form.Item>
      <Form.Item noStyle shouldUpdate>
        {(form) => {
          const selectFormulaData = form.getFieldsValue(["selectFormula"]).selectFormula;
          if(selectFormulaData){
            const args = JSON.parse(selectFormulaData.args)
            if(args.length>0) {
              return (
                <>
                  {args.map((arg: any) => (
                    <ProForm.Item
                      name={arg.name}
                      label={arg.name}
                      initialValue={[]}
                    >
                      <CustomSelectView type="VARIABLE_MODEL" multiple={false}/>
                    </ProForm.Item>
                  ))}
                  <ProFormSelect label='判断条件' name={`condition`} options={[
                    {label: '等于', value: '='},
                    {label: '大于', value: '>'},
                    {label: '小于', value: '<'},
                    {label: '大于或等于', value: '>='},
                    {label: '小于或等于', value: '<='},
                    {label: '不等于', value: '!='},
                  ]}/>
                  <ProFormText name={`conditionValue`} label={'条件值'} placeholder={'值'}/>
                </>
              );
            }
          }
          return null;
        }}
      </Form.Item>
    </ModalForm>

### 🚑 其他信息

在做组件时 在ProFormList中嵌套一个输入框   但在组件内部使用ModalForm时ProFormDependency无法监听到数据变化 于是改为formItem自定义监听 在收集数据时发现formItem子项被套了一层对象  且回显异常

![截屏2021-06-09 10 59 04](https://user-images.githubusercontent.com/53340705/121285956-c152fb00-c911-11eb-973c-5a7a7a0aa848.png)
![截屏2021-06-09 10 59 58](https://user-images.githubusercontent.com/53340705/121286025-d891e880-c911-11eb-9084-e45b22adf0bb.png)

**Comment by chenshuai2144** [comment]
你自定拼接的数据是怎样的？

**Comment by osCaiwei** [comment]
已经解决了

**Comment by iHDJ** [comment]
> 已经解决了

怎么解决的，我也遇到这种问题

**Comment by wenlin126** [comment]
> > 已经解决了
> 
> 怎么解决的，我也遇到这种问题

我也遇到这个问题了，老哥，你解决了吗？
