### ISSUE TITLE
🐛[BUG] 可编辑表格删除一行时 onDelete 方法没有触发

### ISSUE THREAD

**Issue by rdmclin2** [ant-design/pro-components#2974]
### 📷 复现步骤

https://codesandbox.io/s/kebianjibiaoge-forked-msylh?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by rdmclin2** [comment]
@chenshuai2144 需求比较紧迫

**Comment by chenshuai2144** [comment]
```
<a
          key="delete"
          onClick={() => {
            setDataSource(dataSource.filter((item) => item.id !== record.id));
          }}
        >
          删除
        </a>,
```

删除是自己实现的，框架自然拿不到

**Comment by HWTsang** [comment]
> ```
> <a
>           key="delete"
>           onClick={() => {
>             setDataSource(dataSource.filter((item) => item.id !== record.id));
>           }}
>         >
>           删除
>         </a>,
> ```
> 
> 删除是自己实现的，框架自然拿不到

那为什么api有这个呢
![image](https://github.com/ant-design/pro-components/assets/47599239/c4d5fc03-bbad-4b6e-8fec-b68a4ff52a83)
