### ISSUE TITLE
👑 [需求]valueType = 'image'或者'file'时,希望在Form模式下是文件上传控件

### ISSUE THREAD

**Issue by kilik52** [ant-design/pro-components#2976]
### 🥰 需求描述

valueType = 'image'或者'file'时,希望在Form模式下是文件上传控件

### 🧐 解决方案

renderFormItem是Upload。

当然，我可以自己自定义valueType。但我觉得可以放进现有的image里面是更好的方案。

**Comment by chenshuai2144** [comment]
现在实现不了，因为 Upload 特别复杂，等我们拥有了文件中心这种功能时候才会做
