### ISSUE TITLE
🐛[BUG]ProTable列属性ellipsis在某些分辨率下失效

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/pro-components#2979]
### 🐛 bug 描述

官网的Demo和本地项目使用了列属性ellipsis后出现了图中样式
![image](https://user-images.githubusercontent.com/33271366/121314648-23275b00-c93a-11eb-8a5f-f5b324a2b767.png)

**Comment by PLUTO06210331** [comment]
需要一个解决方案

**Comment by chenshuai2144** [comment]
缩放浏览器并不在支持范围内，去 antd 问问。

这个恭喜很复杂和字体 操作系统 浏览器都有关系。 要支持浏览器缩放有点不可能
