### ISSUE TITLE
👑 [需求] stepsform 支持配置内容width的大小，统一好不同step步骤的基本样式

### ISSUE THREAD

**Issue by X-neuron** [ant-design/pro-components#2988]
### 🥰 需求描述

stepsform 支持配置width大小。至少也要和props里width的一致吧?
两个不同的step  占的面板宽度居然不一样。 
step1 里的空间挤压的快窒息了

### 🚑 其他信息

<img src="https://i.postimg.cc/bvV8sW6T/1.png" >
<img src="https://i.postimg.cc/ZKPSrC70/2.png" >

**Comment by chenshuai2144** [comment]
要每个 stepform 单独设置了。

**Comment by X-neuron** [comment]
stepform  一般会和 modal 配合使用。 或者 stepsform 里 配好了，props 不阻断 width的 传递，且一致生效就可以哇~

**Comment by chenshuai2144** [comment]
可以来个pr，我看看方案好不好

**Comment by DerrickTel** [comment]
`<StepsForm containerStyle={{width: '100%'}}><StepsForm />`

**Comment by scrapstation** [comment]
有没有单个StepForm的宽度配置？
