### ISSUE TITLE
🧐[问题]columns定义中多个列需要request获取数据，但只能定义一个request

### ISSUE THREAD

**Issue by dongtao0725** [ant-design/pro-components#2994]
### 🧐 问题描述

https://procomponents.ant.design/components/schema#request-%E5%92%8C-params
columns定义中多个列需要request获取数据，但只能定义一个request，请问需如何解决

**Comment by chenshuai2144** [comment]
可以多个列的。

[ {request},{request},{request}, ]

**Comment by dongtao0725** [comment]
你好，我不同列需要request不同的API，所以request应该需要不一样，但columns中的好像必须已request命名，请问需要如何定义request，谢谢
 const columns = [    {
      title: '专业',
      dataIndex: 'tag',
      valueType:'checkbox',
      request,  //需要request await queryTags();
      params: {param:'tag'},
    },
    {
      title: '用户组',
      dataIndex: 'role',
      valueType:'select',
      request, //需要request await queryRoles();
      params: {param:'role'},
    }]
