### ISSUE TITLE
给ProTable列属性添加ellipsis后页面展示异常

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/pro-components#2995]
电脑分辨率是2560x1440，在浏览器没有进行缩放的情况下ellipsis属性失效
![image](https://user-images.githubusercontent.com/33271366/121483073-5af8d600-ca00-11eb-95cd-08ae7e532395.png)

**Comment by hemengke1997** [comment]
https://github.com/ant-design/pro-components/issues/2898#issue-908076529

**Comment by chenshuai2144** [comment]
升级antd的版本把，这个 antd 修掉了

**Comment by swustzzh** [comment]
> 升级antd的版本把，这个 antd 修掉了

但是页面放大缩小(如放大到125%)，ProTable的ellipsis还是存在显示异常的问题，ProTable(v2.41.0)和antd(4.16.3)的版本都是最新的，也存在，Procomponents官网的组件也存在这个问题。

![image](https://user-images.githubusercontent.com/13358053/122327244-2638d180-cf60-11eb-8f69-8078c5e623d8.png)
