### ISSUE TITLE
🐛[BUG] summary不支持<Table.Summary>

### ISSUE THREAD

**Issue by youngList** [ant-design/pro-components#2996]
### 🐛 bug 描述
使用Table.Summary的时候会报错，图在后边

![image](https://user-images.githubusercontent.com/35622799/121482638-ea51b980-c9ff-11eb-891d-b30115c09a5a.png)
![image](https://user-images.githubusercontent.com/35622799/121482772-048b9780-ca00-11eb-9320-e13e7f0ae778.png)
![image](https://user-images.githubusercontent.com/35622799/121482791-0c4b3c00-ca00-11eb-8efe-12db61780166.png)
### 📷 复现步骤

添加summary时，如果用到<Table.Summary>会报错，直接用<Table.Summary.Row>是可以的
### 🏞 期望结果

期望<Table.Summary fixed>可以起作用
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by hemengke1997** [comment]
升级 antd 升级 pro-table
