### ISSUE TITLE
🧐[问题]ProFormField 设置默认值不生效，只显示出来第一个字符

### ISSUE THREAD

**Issue by suu1923** [ant-design/pro-components#2997]
### 🧐 问题描述
使用了ProFormField 用于编辑页面
结果设置默认值设置不上去，只显示第一个字，去掉该组件，直接使用Protext是可以的
而且我使用了该组件之后，子组件不能设置默认值
请问这是什么原因。

### 💻 示例代码
```
<ProForm onFinish={props.onSubmit} initialValues={{ product_name: props.values.product_name,
}}>
    <ProFormGroup>
        <ProFormFieldSet 
            name='product_name' 
            label="产品名" 
            type='group' 
            transform={(value: string)=>({ product_name: value[0] })} 
            rules={[ { required: true, }, ]} 
            >
                <ProFormText name="product_name" label="产品名" width='xl' />
                <Button type="primary" style={{ position: 'absolute', top: 0, right:'-25px', zIndex: 999 }}>
                按钮
            </Button>
        </ProFormFieldSet>
    </ProFormGroup>
</ProForm>
<!--
```
如果你有解决方案，在这里清晰地阐述
-->

### 🚑 其他信息
获取数据是可以获取到的
![image](https://user-images.githubusercontent.com/21141087/121484687-0ce4d200-ca02-11eb-8a1c-57db897a091c.png)

![image](https://user-images.githubusercontent.com/21141087/121484205-92b44d80-ca01-11eb-8dab-f0750628b632.png)

**Comment by chenshuai2144** [comment]
```tsx
<ProForm onFinish={props.onSubmit} initialValues={{ product_name: [props.values.product_name],
}}>
```

这样搞

**Comment by suu1923** [comment]
> ```tsx
> ```tsx
> <ProForm onFinish={props.onSubmit} initialValues={{ product_name: [props.values.product_name],
> }}>
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 这样搞
> ```

感谢
