### ISSUE TITLE
🧐[问题]columns request多个不同API

### ISSUE THREAD

**Issue by dongtao0725** [ant-design/pro-components#3002]
你好，我不同列需要request不同的API，所以request应该需要不一样，但columns中的好像必须已request命名，请问需要如何定义request，谢谢

const request = async () =>{
  const list = await queryRoles();
      return list.data.map((item) => {
        return {
          label:item.nameZh,
          value:item.id
        }
    })
};

const columns = [ {
title: '专业',
dataIndex: 'tag',
valueType:'checkbox',
request, //需要request await queryTags();
params: {param:'tag'},
},
{
title: '用户组',
dataIndex: 'role',
valueType:'select',
request, //需要request await queryRoles();
params: {param:'role'},
}]

**Comment by cc7gs** [comment]
```tsx
```
