### ISSUE TITLE
🐛[BUG] valueType一些不太好用的地方

### ISSUE THREAD

**Issue by meyerlee** [ant-design/pro-components#3005]
### 🐛 bug 描述

valueType
switch:  
以前是不支持的，因为switch不走value走check所以要另外定制， 
现在有了内置支持但我觉得应该屏蔽掉 width=100%的宽度控制，
只读模式下 switch 无论什么语言都会显示中文的 成功/失败， 
bool值显示文字，实际上是需要根据语境变化的
 是/否  yes/no   启用/禁用  enable/disable   ......

money:
在英文环境下，money类型的货币符号，在表格显示的时候是 CNY,在编辑的时候又变成了 USD。
估计是只读模式下固定输出了 CNY,  编辑控件又根据当前语言选择了货币符号

实际上钱的货币符号不应该跟语言环境走，更不应该固定，而应该是根据金额的币种走。
因此这个货币符号应该通过props来控制。
使用方通过设置 fieldProps的属性控制货币符号（也可以控制不显示货币符号）和小数位。
人民币，美元是2位小数， 日元是圆整到个位。

date/dateTime 日期系列
日期在表格中显示的时候固定是 yyyy-MM-dd的格式，如果需要根据语言文化来变化的话
通过valueTypeMap全局定制了 render方法， 这个时候在edittable中，日期就不能编辑了。

### © 版本信息

- Protable 版本: [2.39.2]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/8414971/121617616-f0937480-ca97-11eb-9047-2d71af68fa77.png)

**Comment by flowerDAI** [comment]
valueType: 'money', 请问这个，现在有什么解决的，
以前好像可以这样写，但是升级后，就报错
valueType: (item)=>({   
        type:'money',
        locale:'en_US',   // 会报错
      }),

**Comment by dingtianxiu** [comment]
money:
locale:枚举 zh-Hans-CN  en-US ru-RU ms-MY sr-RS
小数点 fieldProps.precision

date/dateTime:
render针对mode === read
renderFormItem针对mode === edit || update
