### ISSUE TITLE
🧐[问题]ProTable里collapseRender关于返回值

### ISSUE THREAD

**Issue by zhaoqiqang199** [ant-design/pro-components#3006]
### 🧐 问题描述

在ProTable中定义collapseRender的返回值为一个ReactNode，当返回值为一个false时会隐藏展示按钮，但此api在文档中并未提到，相反在demo中可以看到此处为false，文档是否可以提供一个维护的地方来纠结和补充一些错误
组件地址：https://procomponents.ant.design/components/table?current=1&pageSize=5

### 💻 示例代码
search: {
    span: 6,
    collapseRender:false,
    labelWidth: 80,
    filterType: 'query',
    layout: 'horizontal',
  }

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/26315518/121623311-06a63280-caa2-11eb-9587-5e2ce0a47439.png)

**Comment by chenshuai2144** [comment]
这个是个约定，所有 render 结尾的按钮都支持 false
xxxRender=false，

至于 返回ReactNode，false 也是 ReactNode。

`type ReactNode = ReactChild | ReactFragment | ReactPortal | boolean | null | undefined;`

**Comment by zhaoqiqang199** [comment]
antd开源的框架非常好，支持多种语言，但个我愚见目前vue也好react也好入门难度并不高，对于像我这样主后端语言来讲，前端生态与规约了解的不并不多，但由于工作需有时候还是需要写一些前端，如果文档中可以对细节及内部约定成俗的规约多说明一下，对于新入手antd的同学会很友好，也可以像其它框架的wiki一样，开放一个github维护地址，可以方便其他同学对文档进行补充。
ps：感谢阿里的工程师们对于开源的支持，但工作中接触到的其它中间件对于文档确实惨不忍睹，antd感觉是最好的一个文档，像dubbo，nacos等文档可能停留在好几个版本前了。举个例子：前几天在调研nacos与eureka同步时发现，官方说不支持nacos同步eureka集群但实际不论是最新版本的readme中还是查看历史release更新记录对于nacos同步eureka集群在十几版本前就已经支持，文档已经落后很多。
