### ISSUE TITLE
🐛[BUG]给搜索表单配置初始值，但是重置之后params为空，但是表单依然展示初始值

### ISSUE THREAD

**Issue by YunSmile** [ant-design/pro-components#301]
### 🐛 bug 描述

给搜索表单配置初始值，查询没有问题，但是重置时，params传过来是空的，但是表单的值还显示着

### 🏞 期望结果

希望重置的时候表单的初始值传参能回来

### 💻 复现代码

 <ProTable
        beforeSearchSubmit={params => { console.log('beforeSearchSubmit', params) }}
        form={{ initialValues: query }}
/>

点击重置
![image](https://user-images.githubusercontent.com/18326947/91144532-be6e7d00-e6e6-11ea-9625-a11883a075c6.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] 2.6.1
- umi 版本 3.1.2
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS] window

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/18326947/91144641-e6f67700-e6e6-11ea-9cec-f5158f2aef28.png)

**Comment by chenshuai2144** [comment]
重置时，protable 自己设置了一个{},应该从 form 拿值的
