### ISSUE TITLE
🐛[BUG] Problem with AutoComplete width in editable ProDescriptions

### ISSUE THREAD

**Issue by iloveip** [ant-design/pro-components#3019]
I have a custom component which uses antd AutoComplete. It's width is set to 100 % — `style={{ width: '100%' }}`. But when I use this custom component in `renderFormItem` for the column, it shrinks and I can see only paddings.

Here is a link to [codesandbox](https://codesandbox.io/s/prodescriptions-autocomplete-zflxx?file=/App.tsx:1270-1284). You can see that AutoComplete component outside ProDescriptions works fine and has 100 % width. But the same AutoComplete in `renderFormItem` shrinks when you try to edit it.

Unfortunately, I can't change the `style` in my custom component to a fixed width (as it's used in other projects as well). If it's not a bug, could you please share, how can I fix that?

**Comment by chenshuai2144** [comment]
you should set min-width, width:100% is no work.
Because the width of the ProDescriptions is not set

**Comment by iloveip** [comment]
Thank you very much!

**Comment by iloveip** [comment]
Thank you very much!
