### ISSUE TITLE
ProTable列超长隐藏功能失效🐛[BUG]

### ISSUE THREAD

**Issue by songhechuan** [ant-design/pro-components#3021]
列字段超长不自动缩略功能问题，ellipsis 属性失效。
查看官方功能也是此问题

### 📷 复现步骤

请看官方组件展示连接：
ProTable - 高级表格 - 查询表格
https://procomponents.ant.design/components/table#%E6%9F%A5%E8%AF%A2%E8%A1%A8%E6%A0%BC

### 🏞 期望结果

原来是列超长后会缩略，用省略号代替超长的内容

### © 版本信息

- ProComponents 版本: 最新
- 浏览器环境 chrome 90.0.4430.93

![image](https://user-images.githubusercontent.com/85599708/121987114-65351e80-cdca-11eb-9700-e5951eb169dd.png)

**Comment by johnninja** [comment]
我也刚发现😂

**Comment by swustzzh** [comment]
我被这个问题困扰一两个周了，有点难受~

**Comment by DerrickTel** [comment]
我在我的mac和家里的Windows看了没啥毛病...有试过清除一下缓存之类的吗？

**Comment by changjunhao** [comment]
某些分辨率下会出问题

> 我在我的mac和家里的Windows看了没啥毛病...有试过清除一下缓存之类的吗？

**Comment by DerrickTel** [comment]
> 某些分辨率下会出问题
> 
> > 我在我的mac和家里的Windows看了没啥毛病...有试过清除一下缓存之类的吗？

具体是多少，我调试一下

**Comment by changjunhao** [comment]
> > 某些分辨率下会出问题
> > > 我在我的mac和家里的Windows看了没啥毛病...有试过清除一下缓存之类的吗？
> 
> 具体是多少，我调试一下
Windows 10 中 显示设置有个缩放与布局，如果不选择推荐比例（不一定是100%），会出现该问题
![Uploading 2021622-162357.png…]()

**Comment by changjunhao** [comment]
> > 某些分辨率下会出问题
> > > 我在我的mac和家里的Windows看了没啥毛病...有试过清除一下缓存之类的吗？
> 
> 具体是多少，我调试一下

Windows 10 中 显示设置有个缩放与布局，如果不选择推荐比例（不一定是100%），会出现该问题
![2021624-155638](https://user-images.githubusercontent.com/7688639/123224950-d67c7c00-d504-11eb-8a85-518f67ca2e05.png)

**Comment by ntso-k** [comment]
设置 scroll={{ x: 'max-content' }} 或 scroll={{ x: true }} 可复现。
修改为scroll={{ x: '100%' }} 似乎可解决问题。

**Comment by johnninja** [comment]
> 设置 scroll={{ x: 'max-content' }} 或 scroll={{ x: true }} 可复现。
> 修改为scroll={{ x: '100%' }} 似乎可解决问题。

感谢感谢，有用😂

**Comment by chenshuai2144** [comment]
等antd 修复吧。这个问题要去antd 提交
