### ISSUE TITLE
🧐[问题] 请问如何关闭DrawerForm的时候重置表单数据

### ISSUE THREAD

**Issue by FirstSeeing** [ant-design/pro-components#3023]
### 🧐 问题描述
我的场景是使用DrawerForm编辑ProTable的条目，使用initialValues初始化的方式不能达到预期的效果
```
props.values && <DrawerForm initialValues={props.values}></DrawerForm>
```
随后我又试了initialValue
```
<DrawerForm>
<ProFormText
          name="tag"
          initialValue={props.values.tag}
        />
</DrawerForm>
```
可以达到预期效果，但是点击其他条目后显示的仍然是第一次的，请问如何实现显示我点击的条目的数据？
也就是说我需要关闭DrawerForm的时候初始化数据

**Comment by cc7gs** [comment]
1. initialValues 中 props.values不应该从 useState中获取，它应该是常量.
2. 如果你更改props.values 还需要 ProFormText内容更改，则需要通过 from.setFieldValues({tag:props.values.tag}),而不是通过 initialValue
