### ISSUE TITLE
🧐[问题]如何实现响应式的ProTable？

### ISSUE THREAD

**Issue by Ranylx** [ant-design/pro-components#3025]
使用protable的时候，如果页面调整，可能出现右侧工具栏溢出问题

**Comment by chenshuai2144** [comment]
来个截图，默认的我们都处理过了。


列可以用这个



responsive | 响应式 breakpoint 配置列表。未设置则始终可见。 | Breakpoint[] | - | 4.2.0
-- | -- | -- | -- | --

**Comment by Ranylx** [comment]
感谢，就是在部分缩放比、分辨率的情况下会出现溢出的情况
