### ISSUE TITLE
👑 [需求] 请问 ProList Metas.[Meta] 中能否支持 sorter

### ISSUE THREAD

**Issue by Kerlli** [ant-design/pro-components#3035]

**Comment by Kerlli** [comment]
能否支持一下对列表项进行一下排序,谢谢

**Comment by chenshuai2144** [comment]
现在好像不支持，着急的话可以自己来个 pr，我们这里对 list 的使用需求比较少。

**Comment by Kerlli** [comment]
> 现在好像不支持，着急的话可以自己来个 pr，我们这里对 list 的使用需求比较少。
> 
> 支持的力度也比较小

感谢回复，暂时用ProTable替代了。
