### ISSUE TITLE
🧐[问题]JSON 表单的Schema如何实现Input的disabled

### ISSUE THREAD

**Issue by EdisonFan** [ant-design/pro-components#3036]
### 🧐 问题描述

JSON 表单的Schema如何实现Input的disabled
`{
    title: '标题',
    dataIndex: 'title',
    formItemProps: {
      rules: [
        {
          required: true,
          message: '此项为必填项',
        },
      ],
    },
    width: 'm',
    disabled:true //不起作用
  },`

**Comment by chenshuai2144** [comment]
```
fieldProps: {
  disabled:true //起作用
}
```

**Comment by maplehsu** [comment]
> 要放到 fieldProps
> 
> ```
> fieldProps: {
>   disabled:true //起作用
> }
> ```

麻烦更新到文档里面吧，这样找太麻烦了。
https://procomponents.ant.design/components/schema-form
