### ISSUE TITLE
👑 [需求]How could I render icon/img in "select" value type's table column?

### ISSUE THREAD

**Issue by beyond-life-flux** [ant-design/pro-components#3042]
### 🥰 需求描述

I want to render some feature icons/images in some table columns, just like that

```
{
  title: 'ContentType',
  dataIndex: 'ctype',
  valueType: 'select',
  width: 200
  valueEnum: {
    group: { text: 'Group', status: 'Info', prefix: <MyCustomIcon /> },
    multiple: { text: 'Multiple', status: 'Info', prefix: <MyCustomIcon2 /> },
    h5: { text: 'H5 Link', status: 'Info', prefix: <MyCustomIcon2 /> },
    ...otherOptions,
  }
}
```
Basiclly looks like 

![image](https://user-images.githubusercontent.com/30022286/122361884-41b8d200-cf8a-11eb-875e-f24f135a667b.png)

### 🧐 解决方案

Supports enum options to render react component (prefix, tail etc...) to the`valueEnum` which is based on key-value object.

**Comment by chenshuai2144** [comment]
Text can be React node
you can try this featrue

**Comment by Evanlai8** [comment]
I Use React node like this in ProList -> metas -> options

```
options: [{
    label: <Space><Avatar size={28} src={member.user.photoUrl}/>{member.user.name}</Space>,
    value: member.userId,
}]
```
List render is ok ,  but when I chose an Item, the value is not show corectly

![image](https://user-images.githubusercontent.com/20983292/141948241-d6403cb2-c847-4a2e-b5ed-96c361c23699.png)

Choose an item, get the value “Object”
![image](https://user-images.githubusercontent.com/20983292/141948778-986bf386-e6b9-4a69-8476-0bdc3584008d.png)

**Comment by chenshuai2144** [comment]
Wow, looks awesome。

You can use this api to complete your artwork

```
<ProFormSlider
        lightProps={{
          formatter: (value) => `${value}%`,
        }}
        name="range"
        label="范围"
      />
```
