### ISSUE TITLE
👑 [需求]ProDescriptions支持动态隐藏整列包裹title

### ISSUE THREAD

**Issue by 1247748612** [ant-design/pro-components#3049]
### 🥰 需求描述
ProDescriptions column渲染时，有时候需要根据状态控制列的隐藏并且连title都不展示，就是整一个column都过滤掉。目前发现用renderText、render都不能把title都隐藏。

### 🧐 解决方案

1. hideInDescription参数支持传递函数接受entify参数返回boolean
2. render支持隐藏整列的功能

### 🚑 其他信息

看图对比效果
![image](https://user-images.githubusercontent.com/29533304/122529009-8c505200-d04f-11eb-9782-a51eac9fad14.png)
![image](https://user-images.githubusercontent.com/29533304/122529132-b7d33c80-d04f-11eb-9065-a2d00f0d1995.png)

**Comment by DerrickTel** [comment]
```
const [a, setA] = useState(false)
[
        {
          title: '文本',
          key: 'text',
          dataIndex: 'id',
          hideInDescriptions: a,
        },
]
```

**Comment by 1247748612** [comment]
> const [a, setA] = useState(false)
> [
>         {
>           title: '文本',
>           key: 'text',
>           dataIndex: 'id',
>           hideInDescriptions: a,
>         },
> ]

如果有多个字段要判断是否隐藏，就需要维护多个状态了，有没有更简便的方案

**Comment by DerrickTel** [comment]
const [a, setA] = useState<'a' | 'b'>('a')
[
{
title: '文本',
key: 'text',
dataIndex: 'id',
hideInDescriptions: a === 'a',
},
{
title: '文本',
key: 'text',
dataIndex: 'id',
hideInDescriptions: a === 'b',
},
]

**Comment by 1247748612** [comment]
> const [a, setA] = useState<'a' | 'b'>('a')
> [
> {
> title: '文本',
> key: 'text',
> dataIndex: 'id',
> hideInDescriptions: a === 'a',
> },
> {
> title: '文本',
> key: 'text',
> dataIndex: 'id',
> hideInDescriptions: a === 'b',
> },
> ]

我现在的用法是columns作为常量放在hooks外面的

**Comment by DerrickTel** [comment]
稍微改一下，应该就好了。
```
const columns = (a) => [
{
title: '文本',
key: 'text',
dataIndex: 'id',
hideInDescriptions: a,
},
]
```

**Comment by 1247748612** [comment]
> 稍微改一下，应该就好了。
> 
> ```
> const columns = (a) => [
> {
> title: '文本',
> key: 'text',
> dataIndex: 'id',
> hideInDescriptions: a,
> },
> ]
> ```

嗯嗯感谢，都是些有用的解决方案。其实我更倾向于在hideInDescription提供函数的方式，columns就可以不经过处理直接使用了。

**Comment by chenshuai2144** [comment]
最好还是外面处理，用render 来处理很难区分为空的场景
