### ISSUE TITLE
🐛[BUG]EditableProTable中使用select的tags模式移除已有值出现异常

### ISSUE THREAD

**Issue by LyndonXiao** [ant-design/pro-components#3052]
### 🐛 bug 描述

在EditableProTable中，有一个列使用的valueType为select，fieldProps的mode设置为tags，当进入编辑模式时展现形式正确，添加值也正常，想添加重复值时也会变为不选中这个值，如预期。当保存后重新编辑，展现值正确，但是当我叉掉第一个值时，展示形式是这个值消失，组件上的onChange事件也是拿到正确的剩余的值，但是点击保存时在editable的onSave处拿到的data值异常。如果是从最后面开始移除元素，保存时直接不变，还是原来没移除前的值...

### 📷 复现步骤

如上描述

### 🏞 期望结果

在editable的onSave处拿到的值与组件的onChange回调值一致

### 💻 复现代码

columns处代码
```
{
      title: '尺码表',
      dataIndex: 'props',
      align: 'center',
      hideInSearch: true,
      formItemProps: {
        rules: [{ min: 1, message: '尺码表最少一项', type: 'array' }],
      },
      valueType: 'select',
      fieldProps: { mode: 'tags' },
    },
```
EditableProTable处代码
```
<EditableProTable<DataSourceType>
        headerTitle="列表"
        actionRef={actionRef}
        rowKey="id"
        options={false}
        request={queryList}
        columns={columns}
        value={dataSource}
        onChange={setDataSource}
        recordCreatorProps={false}
        editable={{
          form,
          editableKeys,
          onSave: async (rowKey, data, row) => {
// 此处打印保存回调值
            console.log(rowKey, data.props, row.props);
            const success = await handleSave({ id: data.id, title: data.title, props: data.props });
            if (success) actionRef.current?.reload();
          },
          onChange: setEditableRowKeys,
          actionRender: (row, config, defaultDom) => [defaultDom.save, defaultDom.cancel],
        }}
      />
```

### © 版本信息

- ProComponents 版本: 6.15.3
- umi 版本: 3.4.0
- 浏览器环: Edge
- 开发环境 mac OS 11.4

### 🚑 其他信息

<img width="1343" alt="j1" src="https://user-images.githubusercontent.com/15028509/122563675-0ea03c80-d077-11eb-90f7-8a449611b88f.png">
一开始有两个值
<img width="1339" alt="j2" src="https://user-images.githubusercontent.com/15028509/122563689-119b2d00-d077-11eb-957b-17baaa6f0edd.png">
删掉前面那个值
<img width="1333" alt="j3" src="https://user-images.githubusercontent.com/15028509/122563691-12cc5a00-d077-11eb-9bbd-8cfe076bc812.png">
下方控制台输出为贴出代码中打印onSave回调值，此处出现异常，select中只有一个值，却在回调中出现两个重复值（列表中一个值为手动过滤重复值结果），匪夷所思

**Comment by chenshuai2144** [comment]
controlled	

是否受控, 如果受控每次编辑都会修改 dataSource，且 value 改变会修改表格内容


试试这个
