### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by chenronghui** [ant-design/pro-components#3055]
### 🐛 bug 描述

ProLayout  组件性能差，具体体现在 移动鼠标时，高频触发重绘重排，cpu飙升

### 📷 复现步骤

已 MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports). 2 GHz 四核Intel Core i5 16 GB 3733 MHz LPDDR4X,
打开chrome performance monitor, 每次移动鼠标，都能看到 style 上升， cpu usage 上升

### 🏞 期望结果

移动鼠标不应该出发点重绘崇排

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/29672107/122670354-454f9180-d1f4-11eb-9cb8-2cb027c1cc13.png)

**Comment by binvb** [comment]
这个是antd的问题
