### ISSUE TITLE
👑 [需求] ProDescriptions右上方的操作按钮extra区域能否控制不显示

### ISSUE THREAD

**Issue by dmdoit** [ant-design/pro-components#3056]
### 🥰 需求描述
ProDescriptions右上方的操作按钮extra区域能否控制不显示

**Comment by DerrickTel** [comment]
现在不传值就是不显示吧？具体是哪方面？稍微具体一点

**Comment by dmdoit** [comment]
> 现在不传值就是不显示吧？具体是哪方面？稍微具体一点

是的，我共用了proTable的columns，所以才会显示，其实可以在ProDescriptions的columns里提前把valueType: 'option' 处理掉就好了
