### ISSUE TITLE
🐛[BUG] ProLayout 组件性能问题

### ISSUE THREAD

**Issue by chenronghui** [ant-design/pro-components#3057]
### 🐛 bug 描述

ProLayout  组件性能差，具体体现在 移动鼠标时，高频触发重绘重排，cpu飙升

### 📷 复现步骤

已 MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports). 2 GHz 四核Intel Core i5 16 GB 3733 MHz LPDDR4X,
打开chrome performance monitor, 每次移动鼠标，都能看到 style 上升， cpu usage 上升

### 🏞 期望结果

移动鼠标不应该出发点重绘崇排

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/29672107/122670354-454f9180-d1f4-11eb-9cb8-2cb027c1cc13.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢反馈问题！

你所描述的情况可能是因为 ProLayout 组件的实现原理导致的。为了解决这个问题，建议尝试使用以下方法：

1. 升级 ProLayout 版本到最新的版本，看看是否有已知的性能优化问题被解决了。

2. 检查你是否使用了大量无意义的渲染，如将组件包裹在 `Fragment` 或 `div` 中时，如果你使用了 `Fragment` 或 `div` 包裹组件，建议使用 `React.Fragment` 或 `<>` 来代替。

3. 将需要渲染的组件拆分成更小的组件，避免不必要的计算。此外，React.memo 可以优化无状态组件的渲染，React.useCallback 可以优化回调函数的渲染。

4. 如果以上方法不能解决问题，可以尝试在React组件中使用 React Window 或 react-virtualized 来处理非常多的页面内容。

最后，如果以上方法都不能解决问题，请告知具体的使用场景以及你的代码示例，我们将在接下来的讨论中帮助你解决问题。
