### ISSUE TITLE
EditableProTable，如何区分增加或修改状态，并通过代码修改纪录内容。 

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#3060]
这是我想做的：

1. 通过选择下拉菜单给EditableProTable增加新记录。
2. 在Save新纪录前，重新选择（上次选择错误）
3. 一次只能增加一新行。

具体步骤：

1. 从Select 选择一项option1
2. 增加新Record
3. 使用选中的选项给新Record 赋值，
4. 在Save新纪录前，
5. 从Select 选择一项option2
6. 改变新Record的数值
7. Save

问题，

1. 在以上步骤中，如何在第二次选择前，清理第一次选择，并给新纪录赋值？
2. 如何知道当前是增加或修改状态？
3. 增加了新Record，但未保存。此时想修改新Record，属于增加还是修改？
4. 如何拿到新纪录，以便修改？

**Comment by chenshuai2144** [comment]
<html>
<body>


controlled | 是否受控, 如果受控每次编辑都会修改 dataSource | boolean | false
-- | -- | -- | --



</body>
</html>

试试这个api，可以完全受控的处理 可编辑表格
