### ISSUE TITLE
🐛[BUG] Protable columns 配置 request 枚举值在表格中值未进行映射

### ISSUE THREAD

**Issue by cc7gs** [ant-design/pro-components#3063]
### 🐛 bug 描述
从服务端获取枚举值后，表格中数据未进行枚举映射

### 📷 复现步骤

```tsx
const columns=[
 {
    title: "状态",
    dataIndex: "state",
    filters: true,
    onFilter: true,
    valueType: "select",
    request: queryState
  },
]
```

### 🏞 期望结果

异步获取枚举值后，在表格中字段可以正常映射

### 💻 复现代码

[codesandbox](https://codesandbox.io/s/chaxunbiaoge-forked-97sh6?file=/App.tsx:1157-1292)

### © 版本信息

- ProTable 版本: [2.41]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

临时方案通过renderText进行显示，官方能否自动映射

**Comment by DerrickTel** [comment]
async function queryState() {
  await sleep(1000);
  return [
    {
      label: "未解决",
      value: "open"
    }
  ];
}

**Comment by DerrickTel** [comment]
好像缺了文档，我补一下

**Comment by cc7gs** [comment]
oops...sorry @DerrickTel
