### ISSUE TITLE
🐛[BUG]@ant-design/pro-table  light 模式下 自定义Select 并使用valueEnum 显示值有误

### ISSUE THREAD

**Issue by wuhao930406** [ant-design/pro-components#3066]
### 🐛 bug 描述

@ant-design/pro-table  light 模式下 自定义Select 并使用valueEnum 显示值有误
![image](https://user-images.githubusercontent.com/18044670/122867645-6632f680-d35c-11eb-98d0-cc379dac51d9.png)

### 📷 复现步骤
```
columns =  {
            "title": "车间",
            "dataIndex": "shop",
            "key": "shop",
            "valueType": "cascaders",
            renderFormItem: (item, { type, defaultRender, fieldProps, ...rest }, form) => {
                return <Select  options={[{ label: "test", value: "value" }]} {...rest}></Select>
            },
            valueEnum: {
                "value": {
                    text: "test"
                }
            }
   }
```

### 🏞 期望结果

![image](https://user-images.githubusercontent.com/18044670/122867686-7a76f380-d35c-11eb-864e-9e00e5116998.png)

### 💻 复现代码

columns =  {
            "title": "车间",
            "dataIndex": "shop",
            "key": "shop",
            "valueType": "cascaders",
            renderFormItem: (item, { type, defaultRender, fieldProps, ...rest }, form) => {
                return <Select  options={[{ label: "test", value: "value" }]} {...rest}></Select>
            },
            valueEnum: {
                "value": {
                    text: "test"
                }
            }
   }

### © 版本信息

- ProComponents 版本: "@ant-design/pro-table": "^2.41.0"
- umi 版本  "^3.4.22"
- 浏览器环境 Google Chrome 版本 90.0.4430.93
- 开发环境  win10

### 🚑 其他信息

如何正确显示label值？

**Comment by MittWillson** [comment]
同样的问题也出现在 ProList

**Comment by chenshuai2144** [comment]
@MittWillson  开新 issue 给复现

**Comment by MittWillson** [comment]
> @MittWillson 开新 issue 给复现

复现和问题与本Issue一致

**Comment by wuxuejie** [comment]
我也遇到同样的问题，怎么解决的？

**Comment by wuhao930406** [comment]
> 我也遇到同样的问题，怎么解决的？
暂时没办法解决 升级到最新版本 "@ant-design/pro-table": "^2.48.0" 依旧存在此问题

**Comment by chenshuai2144** [comment]
要自定义一下了，这种转化只有valueType="select" 才会生效
