### ISSUE TITLE
👑 [需求]pro-form轻量模式（LightFilter）中能否再加入ProFormCheckbox和ProFormSwitch的轻量模式？

### ISSUE THREAD

**Issue by hzwzw** [ant-design/pro-components#307]
### 🥰 需求描述
轻量模式对于筛选非常有帮助。

比如对于男、女属性，用普通的switch筛选男或女。不需要筛选性别项的时候，就要额外设计UI来表示不筛选，而轻量模式每个筛选项后面的X就很好的解决了这个问题。

**Comment by chenshuai2144** [comment]
会加的，或者你可以提个 pr

**Comment by yutingzhao1991** [comment]
对于男、女属性应该就用 ProFormSelect 就好了，这个后面会加上。

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/385

我们已经全部支持

**Comment by hzwzw** [comment]
非常NICE！！！
