### ISSUE TITLE
🐛[BUG] pro-provider, pro-utils, 与官方文档中的类型定义不一致

### ISSUE THREAD

**Issue by Artoria-0x04** [ant-design/pro-components#3071]
### 🐛 bug 描述

目前在尝试使用 SchemaForm 和配一些自定义级联组件，发现 @ant-design/pro-utils，@ant-design/pro-provider 和文档上面提供的类型并不一致，每个地方都使用了自己定义的类型，导致自定义 valueType 的 render 方法时签名对不上。
感觉这部分设计很混乱。

### 📷 复现步骤

-

### 🏞 期望结果

相同的 Field JSON 模型使用相同的类型定义

### 💻 复现代码

pro-provider/lib/index.d.ts (v1.14.13)
![image](https://user-images.githubusercontent.com/1183568/123048175-b3809800-d430-11eb-87b1-814db9e3051b.png)

pro-utils/lib/typing.d.ts (v1.19.0)
![image](https://user-images.githubusercontent.com/1183568/123048330-dd39bf00-d430-11eb-84e7-0393971167a5.png)

[文档](https://procomponents.ant.design/components/schema#%E8%87%AA%E5%AE%9A%E4%B9%89-valuetype) at **5/26/2021 17:16:38**
![image](https://user-images.githubusercontent.com/1183568/123048662-37d31b00-d431-11eb-88e5-c86e021240f6.png)

### © 版本信息

- ProComponents 版本: pro-form@1.28.1
- umi 版本 N/A
- 浏览器环境 Chrome v91
- 开发环境 mac OS

**Comment by preservance717** [comment]
您好，您本地可以自定义valueType吗，能成功的显示出对应的自定义组件吗？ @ @Artoria-0x04

**Comment by Artoria-0x04** [comment]
> 您好，您本地可以自定义valueType吗，能成功的显示出对应的自定义组件吗？ @ @Artoria-0x04

我没有直接使用 SchemaForm，而是把源码中的 `genItem()` 抄了一个 hook。没什么问题，Cascader 和 TreeSelect 都正常。

**Comment by chenshuai2144** [comment]
已经实现了，无需跟踪了
