### ISSUE TITLE
🐛[BUG]Protable ellipsis: true

### ISSUE THREAD

**Issue by MxUninpho** [ant-design/pro-components#3075]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/27352039/123073357-eafb3e80-d448-11eb-8022-c45a1be4c999.png)

存在样式不收缩的bug
### 📷 复现步骤
在官网示例主页即可发现

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by ntso-k** [comment]
设置 scroll={{ x: 'max-content' }} 或 scroll={{ x: true }} 可复现。
修改为scroll={{ x: '100%' }} 似乎可解决问题。

**Comment by chenshuai2144** [comment]
等 antd 修复吧
