### ISSUE TITLE
🐛[BUG] ProLayout/HeaderView collapse/onCollapse does not become false again after visitor re-expands window (responsive)

### ISSUE THREAD

**Issue by ceefour** [ant-design/pro-components#3077]
### 🐛 bug description

ProLayout/HeaderView collapse/onCollapse  does not become `false` again after visitor re-expands window (responsive)

### 📷 Steps to reproduce

1. Resize window to narrow so that responsive ProLayout collapses, header becomes `GlobalHeader`
2. Expand window again so that responsive ProLayout expands, header becomes `TopNavHeader` again, however it is not reflected in `collapsed` state

### 🏞 Expected results

1. When window is narrow, collapsed => `true` (working)
2. When window expands again, collapsed should be `false` but still `true` (not working)

### 💻 Reproduce the code

```tsx
<ProLayout onCollapse={collapsed => console.log(collapsed)} />
```

This can be verified using React Developer Tools in `HeaderView` component:

![image](https://user-images.githubusercontent.com/24123/123156627-b496e100-d493-11eb-8628-a8527485a28d.png)

### © Version Information

-ProComponents version: 6.19.7

```
├─ @ant-design/pro-layout@6.19.7
│  ├─ @ant-design/icons@^4.0.0
│  ├─ @ant-design/pro-provider@1.4.14
│  ├─ @ant-design/pro-utils@1.19.2
│  ├─ @umijs/route-utils@^1.0.35
│  ├─ @umijs/use-params@^1.0.2
│  ├─ classnames@^2.2.6
│  ├─ omit.js@^2.0.2
│  ├─ path-to-regexp@2.4.0
│  ├─ path-to-regexp@2.4.0
│  ├─ rc-resize-observer@^0.2.1
│  ├─ rc-resize-observer@0.2.6
│  │  ├─ @babel/runtime@^7.10.1
│  │  ├─ classnames@^2.2.1
│  │  ├─ rc-util@^5.0.0
│  │  └─ resize-observer-polyfill@^1.5.1
│  ├─ rc-util@^5.0.6
│  ├─ swr@^0.5.6
│  ├─ unstated-next@^1.1.0
│  ├─ use-json-comparison@^1.0.3
│  ├─ use-media-antd-query@^1.0.6
│  └─ warning@^4.0.3
```

-umi version: 3.4.25

```
├─ umi@3.4.25
│  ├─ @umijs/bundler-webpack@3.4.25
│  ├─ @umijs/core@3.4.25
│  ├─ @umijs/deps@3.4.25
│  ├─ @umijs/preset-built-in@3.4.25
│  ├─ @umijs/runtime@3.4.25
│  ├─ @umijs/types@3.4.25
│  ├─ @umijs/utils@3.4.25
│  ├─ react-dom@16.14.0
│  │  ├─ loose-envify@^1.1.0
│  │  ├─ object-assign@^4.1.1
│  │  ├─ prop-types@^15.6.2
│  │  └─ scheduler@^0.19.1
│  ├─ react-dom@16.x
│  ├─ react@16.14.0
│  │  ├─ loose-envify@^1.1.0
│  │  ├─ object-assign@^4.1.1
│  │  └─ prop-types@^15.6.2
│  ├─ react@16.x
│  ├─ scheduler@0.19.1
│  │  ├─ loose-envify@^1.1.0
│  │  └─ object-assign@^4.1.1
│  └─ v8-compile-cache@2.3.0
```

-Browser environment: Chrome
-Development environment [e.g. mac OS]: Ubuntu 20.04

### 🚑 Other information

Related to #340, #2800

**Comment by chenshuai2144** [comment]
fixed
