### ISSUE TITLE
通过数组遍历出来的自定义可编辑表格怎么使用actionRef

### ISSUE THREAD

**Issue by robin536180** [ant-design/pro-components#3078]
`````
const actionRef = useRef();
<ProCard
    key={item.title}
    title={item.title}
    headerBordered
    size="small"
    extra={
      <Button size="small" onClick={() => {
        actionRef.current.addEditRecord({
          id: uuid(),
          title: '新的一行'
        })
      }}
        type="primary" icon={<PlusOutlined />}>新增一行</Button>
    }
  >
    <EditableProTable
      actionRef={actionRef}
      rowKey="id"
      maxLength={5}
      size="small"
      recordCreatorProps={false}
      columns={[...indexColumns, ...columns, ...actionColumns]}
      request={async () => ({
        data: [],
        total: 3,
        success: true,
      })}
      value={item.content}
      onChange={setDataSource}
      editable={{
        type: 'multiple',
        form,
        editableKeys,
        onSave: async () => console.log('save'),
        onChange: setEditableRowKeys,
        actionRender: (row, config, dom) => [dom.save, dom.cancel],
      }}
    />
  </ProCard>
`````

怎么能在遍历出来的 每一个表格 定义出actionRef ,能让新建按钮 调用当前table里面的actionRef的方法

**Comment by robin536180** [comment]
`const actionRef = useRef();`
`<ProCard
key={item.title}
title={item.title}
headerBordered
size="small"
extra={
<Button size="small" onClick={() => {
actionRef.current.addEditRecord({
id: uuid(),
title: '新的一行'
})
}}
type="primary" icon={}>新增一行
}
>
<EditableProTable
actionRef={actionRef}
rowKey="id"
maxLength={5}
size="small"
recordCreatorProps={false}
columns={[...indexColumns, ...columns, ...actionColumns]}
request={async () => ({
data: [],
total: 3,
success: true,
})}
value={item.content}
onChange={setDataSource}
editable={{
type: 'multiple',
form,
editableKeys,
onSave: async () => console.log('save'),
onChange: setEditableRowKeys,
actionRender: (row, config, dom) => [dom.save, dom.cancel],
}}
/>`

**Comment by chenshuai2144** [comment]
用数组存一下 

`actionRef.current[0] = ref`

**Comment by robin536180** [comment]
多谢 问题已经解决啦 谢啦
