### ISSUE TITLE
ProTable 的 columns 怎么使用 TreeSelect 呢？🧐[问题]

### ISSUE THREAD

**Issue by iiuhuy** [ant-design/pro-components#3079]
### 🧐 问题描述

ProTable 的 columns 能使用 TreeSelect 吗？

需求：

- 在 ProTable 列表 columns  中使用 TreeSelect 修改区域数据时，onChange 之后列表的其他行的区域数据也会跟着变化。

正确使用 TreeSelect 的方式是怎样的呢？😣

### 💻 示例代码

 > https://codesandbox.io/s/biaogepiliangcaozuo-forked-kw59i?file=/App.js

**Comment by chenshuai2144** [comment]
如果不用我们封装的组件，我们无法确认内容是什么，所以也不会自动格式化
