### ISSUE TITLE
ProTable 中 RecordCreator props 没有

### ISSUE THREAD

**Issue by wenp** [ant-design/pro-components#3080]
### 🧐 问题描述
我在使用`ProTable`的的时候，没有在官方的地址中找到这个属性。https://procomponents.ant.design/components/table#recordcreator
请问下 这个是设置到哪里？

**Comment by wenp** [comment]
RecordCreator

**Comment by wenp** [comment]
我想设置添加一行按钮。我看到EditableProTable里面是有的。ProTable 也有 但是 EditableProTable我找到了设置的位置。找不到 ProTable 中设置的位置

**Comment by wenp** [comment]
难道是我眼瞎 求来人啊

**Comment by wenp** [comment]
已经找到解决方案了

**Comment by Jealh-h** [comment]
> 已经找到解决方案了

请问下是怎解决的呢
