### ISSUE TITLE
👑 ProForm onFinish 去除对非原生对象值的处理

### ISSUE THREAD

**Issue by cc7gs** [ant-design/pro-components#3084]
### 🥰 需求描述
目前用自定义日期控件集成ProForm中，提交时 `{dateRange:[dayjs,dayjs]}` 该类型被当作普通对象过滤了，因此丢失原型

## 复现

[sandbox](https://codesandbox.io/s/riqibiaodan-forked-qht6d?file=/App.tsx)

### 🧐 解决方案
```ts
// utils/conversionSubmitValue
  if (typeof value !== 'object' || isNil(value) || value instanceof Blob || Array.isArray(value)|| !isPlainObject(value)) {
    return value;
  }
```

**Comment by chenshuai2144** [comment]
dayjs 已经支持了
