### ISSUE TITLE
🧐[问题]ProForm.Item 如何将自定义的子组件的数据放入到form里

### ISSUE THREAD

**Issue by yongliangliu** [ant-design/pro-components#3087]
### 🧐 问题描述

如图所示，希望想UploadImg的fileKeys，保存到ProForm的img字段，请教下，如何实现

![image](https://user-images.githubusercontent.com/19800207/123293185-5e36aa80-d546-11eb-85c0-25ff91b882c7.png)

**Comment by zhousufa** [comment]
为啥关了

**Comment by liangxp** [comment]
真直接！
