### ISSUE TITLE
👑 [需求] document title 不根据 layout title 自动生成

### ISSUE THREAD

**Issue by Baoyx007** [ant-design/pro-components#3088]
### 🥰 需求描述

项目中的 document.title 不需要和路由中的  layout 的 title 保持一致.

### 🧐 解决方案

`getPageTitle` 可以通过配置传进去

**Comment by chenshuai2144** [comment]
`| pageTitleRender | 自定义页面标题的显示方法 | `(props: BasicLayoutProps) => string` | - |`

用这个 api

**Comment by 20VanPersie** [comment]
pageTitleRender还是无法将document.title和PageContainer title分开
