### ISSUE TITLE
🐛[BUG]ProTable排序问题，配置defaultSortOrder后不生效

### ISSUE THREAD

**Issue by TLOVET** [ant-design/pro-components#309]
### 🐛 bug 描述
注意：ProTable版本2.5.4无此BUG
columns配置defaultSortOrder不生效

### 🏞 期望结果
columns配置defaultSortOrder时能显示默认排序

### 💻 复现代码
{
      title: '服务调用次数',
      dataIndex: 'callNo',
      sorter: true,
      hideInForm: true,
      defaultSortOrder: 'descend',
      renderText: (val) => `${val} 万`,
    },

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- ant-design/pro-table 版本: [2.6.1]
- umi 版本 [3.2.16]
- 浏览器环境[Chrome 84.0.4147.135]
- 开发环境 [mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/3888718/91252897-195cae80-e791-11ea-9e9a-f24fb8277881.png)

**Comment by chenshuai2144** [comment]
在这里一起跟踪吧 
https://github.com/ant-design/pro-components/issues/358

**Comment by evin2333** [comment]
马上2020了好像还有问题，显示上已经有效了，初始化请求sorter是null
