### ISSUE TITLE
🧐[问题] Prolist 中 同时设置 grid 和 rowSelection ，并不会出现多选框

### ISSUE THREAD

**Issue by weijie-he** [ant-design/pro-components#3094]
### 🧐 问题描述

 Prolist 中 同时设置 grid 和 rowSelection ，并不会出现多选框

### 💻 示例代码

无

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/16081489/123408200-52e38d80-d5df-11eb-9803-9e8ce3b89024.png)

**Comment by chenshuai2144** [comment]
这个是符合预期的设计

**Comment by xinmayzhang** [comment]
有解决办法吗？
