### ISSUE TITLE
🐛[BUG] pagination 自定义左侧和右侧空间

### ISSUE THREAD

**Issue by tong233** [ant-design/pro-components#3095]
### 🥰 需求描述

pagination独自占掉一行，却只利用1/3的空间，左侧可以像toolbar一样放一些按钮 文案什么的

### 🧐 解决方案

建议pagination提供配置左侧和右侧render

### 🚑 其他信息

感谢大佬，很多组件挺好用的

**Comment by chenshuai2144** [comment]
现在是没有这样的api的，你可以通过 showTotal 来进行一些自定义。

<html>
<body>


showTotal | 用于显示数据总量和当前数据顺序 | function(total, range) | -
-- | -- | -- | --



</body>
</html>
