### ISSUE TITLE
🧐[问题]在layout:"mix",splitMenus:true,怎么设置二级路由及以下隐藏，一级菜单显示

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/pro-components#3098]
### 🧐 问题描述

如图，在进入某二级路由时，想隐藏左侧导航

### 代码
![image](https://user-images.githubusercontent.com/30942709/123510055-eedacb00-d6ab-11eb-81dd-3895589c75ef.png)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30942709/123509417-fa2bf780-d6a7-11eb-8195-6463a3086539.png)

**Comment by ISBN9527** [comment]
烦请大佬指点一二

**Comment by chenshuai2144** [comment]
在子路由第一级加 hideInMenu ?

**Comment by ISBN9527** [comment]
> 在子路由第一级加 hideInMenu ?

左侧导航全部隐藏，不是需要都要加这个嘛

**Comment by chenshuai2144** [comment]
你可以 menuDataRender 自定义一下, 把所有的 chilren 全部删除

```
menuDataRender = (data)=>{
   return {...data,children:null}
}
```
