### ISSUE TITLE
🧐[问题] layout-nested with multiple routes

### ISSUE THREAD

**Issue by 3hson** [ant-design/pro-components#3101]
i'm using antd-pro + umijs. I need to implement a nested menu that any item of the main menu has a different routes list.
sample:

![simplescreenrecorder (1)](https://user-images.githubusercontent.com/36244081/123537937-6578d680-d747-11eb-8996-d795dd91c5c3.gif)

is there any way to do this?

**Comment by chenshuai2144** [comment]
You can use nested routes to implement them

https://procomponents.ant.design/~demos/layout-immersive-navigation
https://procomponents.ant.design/components/layout#%E5%A4%9A%E7%BA%A7%E7%AB%99%E7%82%B9%E5%AF%BC%E8%88%AA
