### ISSUE TITLE
当form表单被ProForm.Group包裹，且表单是hidden状态时，initialValue不起作用🐛[BUG]

### ISSUE THREAD

**Issue by lichia9527** [ant-design/pro-components#3107]
### 💻 复现代码
```
<ProForm
        onFinish={async (v) => {
          console.log(v); // 输出 {}, 期望输出 {name: "Jack"}
        }}
      >
        <ProForm.Group>
          <ProFormText name="name" hidden initialValue="Jack" />
        </ProForm.Group>

 </ProForm>
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
hidden 的组件在 ProForm.Group 直接不渲染的。你想达到什么效果？

**Comment by LichiaMa** [comment]
> hidden 的组件在 ProForm.Group 直接不渲染的。你想达到什么效果？
> 如果想设置默认值，最好在全局设置

全局设置也一样的，我用ProForm.Group是用来的布局的哈，就是让表单项处于同一行，这个Group默认是不显示的，但是表单是需要搜集默认值的，所以我设置了hidden属性，我还有一个按钮，点击以后hidden会变成false，然后这个group就显示出来了，但现在就有问题了，被ProForm.Group包裹的东西如果是hidden表单就不会搜集值。现在只能不用ProForm.Group这个，然后自己改样式了。难道ProForm.Group这个的作用不是布局用的么，为什么会影响表单收集表单值呢

**Comment by chenshuai2144** [comment]
dom 不渲染就会导致值搜集不到的，所以推荐你统一管理值。

hidden 和 display:none 表现是不同的

**Comment by LichiaMa** [comment]
> dom 不渲染就会导致值搜集不到的，所以推荐你统一管理值。
> 
> hidden 和 display:none 表现是不同的

这个和统一不统一管理值有什么关系，难道这样就会渲染么？
···
<ProForm
       initialValue={{name: "Jack"}}
        onFinish={async (v) => {
          console.log(v); // 输出 {}, 期望输出 {name: "Jack"}
        }}
      >
        <ProForm.Group>
          <ProFormText name="name" hidden  />
        </ProForm.Group>

 </ProForm>
···
<ProFormText name="name" hidden  /> 这个如果不放到 ProForm.Group 这个里面就是等于display:none啊，为什么放到ProForm.Group这个里面就直接不渲染了，你不觉得这个设计很奇怪么

**Comment by chenshuai2144** [comment]
ProGruop中使用了space 不显示的dom也会触发padding 可能会导致padding重复的问题 所以直接不渲染了

你的问题可以通过display:none 来解决

**Comment by whinc** [comment]
> hidden 的组件在 ProForm.Group 直接不渲染的。你想达到什么效果？
> 如果想设置默认值，最好在全局设置

这里为什么不与  antd 的行为保持一致呢？
![image](https://user-images.githubusercontent.com/5096493/127337230-0c82fb56-e34b-4afd-aefc-6e514c782295.png)
