### ISSUE TITLE
🐛[BUG] ProForm 中的 EditableProTable 对 setFieldsValue 没有正确响应

### ISSUE THREAD

**Issue by IronKinoko** [ant-design/pro-components#3109]
### 🐛 bug 描述

简单描述，处于编辑状态的ProTable数据，不会响应`form.setFieldsValue()`

1. `ProForm`中的`EditableProTable`在的编辑状态的时候，调用`form.setFieldsValue()` 界面数据不会变化。
2. 如果先调用`form.resetFields()`再调用`form.setFieldsValue()`  界面又正常了。

不知道这个是设计预期还是bug

### 🏞 期望结果

按理来说，直接调用`form.setFieldsValue()` 就应该产生变化的

### 💻 复现代码

https://codesandbox.io/s/proform-he-editabletable-tongshishiyong-forked-ct3m8

### © 版本信息

- ProComponents 版本: `form@1.29.1`  `table@2.42.1`
- umi 版本 
- 浏览器环境 chrome 90
- 开发环境 mac

**Comment by chenshuai2144** [comment]
<html>
<body>


controlled | 是否受控, 如果受控每次编辑都会触发 onChange，并且会修改 dataSource | boolean | false
-- | -- | -- | --



</body>
</html>


打开这个模式
