### ISSUE TITLE
🐛[BUG] pro-table 2.43.0 版本中设置pagination不生效

### ISSUE THREAD

**Issue by McCarthey** [ant-design/pro-components#3110]
### 🐛 bug 描述
pro-table 2.43.0 版本中设置pagination不生效，发现是合并了这个[PR](https://github.com/ant-design/pro-components/pull/3050)导致的，现在必须手动管理Pagination才可以，也因此官网上的一些demo的分页配置也都失效了

SHA：5df2144136f1588b5116f4c6d1aea2d4ebbdc472

### 💻 复现代码
[官网文档](https://procomponents.ant.design/components/table/#%E6%9F%A5%E8%AF%A2%E8%A1%A8%E6%A0%BC)
[官网文档的Sandbox](https://codesandbox.io/s/l2lzg)

### © 版本信息

- pro-table 版本: 2.43.0

**Comment by umeshn1** [comment]
@chenshuai2144 这个问题仍然存在，并且 onChange() 在使用 dataSource 时被调用了两次
https://codesandbox.io/s/biao-ge-pi-liang-cao-zuo-forked-15lx8o?file=/App.tsx

**Comment by chenshuai2144** [comment]
fixed
