### ISSUE TITLE
🧐[问题]proLayout配合proTable使用的界面，侧边栏展开与收缩很卡

### ISSUE THREAD

**Issue by didashine** [ant-design/pro-components#3113]
### 🧐 问题描述
在页面中存在table组件的情况下，侧边栏伸缩都会有卡顿出现，把table注释掉后就正常了；想问下这种情况有什么好的优化方法吗？

### 💻 示例代码
无
### 🚑 其他信息
无

**Comment by chenshuai2144** [comment]
这个估计是因为table 会根据宽度触发重新渲染导致的。

你可以用 shouldcomponentupdate 来控制更新频率
