### ISSUE TITLE
🧐[问题]v5版本下嵌套布局如何配置

### ISSUE THREAD

**Issue by fangqibin** [ant-design/pro-components#3115]
### 🧐 问题描述
如果是嵌套的layout，app.tsx里面的layout如何配置。我想实现的效果是https://procomponents.ant.design/~demos/layout-nested

**Comment by fangqibin** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
有个叫 childrenRender 的api。

`childrenRender :(children)=>React.Node`
