### ISSUE TITLE
🐛[BUG]  layout: 'mix',   splitMenus: true条件下，重定向三级菜单组件渲染错误

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/pro-components#3116]
### 🐛 bug 描述
mix模式下，重定向成功，但是三级菜单组件无渲染,而是渲染的一级菜单内容

### 💻 复现代码

链接仓库
https://github.com/ISBN9527/pro-mix

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本: 3.4.0
- 浏览器环境 ： 谷歌
- 开发环境 [e.g. mac OS]   mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30942709/123751175-01424800-d8ea-11eb-8139-25b860b7544b.png)

**Comment by ISBN9527** [comment]
@chenshuai2144

**Comment by binvb** [comment]
你第一层写了一个不存在的路由组件
```
    path: '/one',
    name: 'one',
    component: './One',
```

**Comment by ISBN9527** [comment]
> 你第一层写了一个不存在的路由组件，去掉应该就好了
> 
> ```
>     path: '/one',
>     name: 'one',
>     component: './One',
> ```

去掉直接就不显示了

**Comment by ISBN9527** [comment]
![image](https://user-images.githubusercontent.com/30942709/123756005-11a8f180-d8ef-11eb-9af1-e83c38e912e3.png)
![image](https://user-images.githubusercontent.com/30942709/123756026-18376900-d8ef-11eb-9d1a-5e2573dde7b7.png)

**Comment by binvb** [comment]
试了下，这样是好的, redirect应该不会继续往下面走了
```
  {
    path: '/one',
    name: 'one',
    routes: [
      {
        path: '/one/two',
        name: 'two',
        routes: [
          {
            path: '/one/two/three',
            name: 'three',
            component: './One/Three',
          },
        ],
      },
    ],
  },
```

**Comment by ISBN9527** [comment]
> 试了下，这样是好的, redirect放在每一层最后一个路由，或者不用设置了吧，放到前面就不继续走下去了
> 
> ```
>   {
>     path: '/one',
>     name: 'one',
>     routes: [
>       {
>         path: '/one/two',
>         name: 'two',
>         routes: [
>           {
>             path: '/one/two/three',
>             name: 'three',
>             component: './One/Three',
>           },
>         ],
>       },
>     ],
>   },
> ```

我加上重定向就不行了，`redirect: '/one/two/three' `

**Comment by binvb** [comment]
你重定向放到第二层头部，走不到第三层了

**Comment by ISBN9527** [comment]
> 你重定向放到第二层头部，走不到第三层了

哥，那我应该放到第几层才能起到重定向作用，我现在是放到第几层都不行

**Comment by binvb** [comment]
> > 你重定向放到第二层头部，走不到第三层了
> 
> 哥，那我应该放到第几层才能起到重定向作用，我现在是放到第几层都不行

我不确定你的需求是怎么样的，我举个例子，例如，如果只需要兼容三级路由可能会出现出错的路由，我在三级路由后面加个重定向：  
```
  {
    path: '/one',
    name: 'one',
    routes: [
      {
        path: '/one/two',
        name: 'two',
        routes: [
          {
            path: '/one/two/three',
            name: 'three',
            component: './One/Three',
          },
          {
            path: '/one/two/*',
            redirect: '/one/two/three'
          },
        ],
      },
    ],
  },
```

**Comment by ralph-wh** [comment]
redirec后的节点不在继续匹配，放到需要重定向菜单的最后一级。例如mix模式下放到第二层的最后一个
