### ISSUE TITLE
ModalForm 和 DrawerForm 内嵌ProTable 查询框会错位🐛[BUG]

### ISSUE THREAD

**Issue by benson-singapore** [ant-design/pro-components#3122]
### 🐛 bug 描述

ModalForm 和 DrawerForm 内嵌ProTable 查询框会错位🐛[BUG]

> 
![WX20210630-122325](https://user-images.githubusercontent.com/24889151/123901696-0234b180-d99e-11eb-924e-b3afba72f296.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by CaicoLeung** [comment]
这个问题很久了

**Comment by CaicoLeung** [comment]
labelWidth设为0样式好了,  但是layout设置无效
