### ISSUE TITLE
🧐[问题] 安装 `@ant-design/pro-form` 后使用 `ProForm` 系列组件报错： Module not found: Can't resolve 'rc-util/es/Dom/scrollLocker'

### ISSUE THREAD

**Issue by glk-hll** [ant-design/pro-components#3124]
![image](https://user-images.githubusercontent.com/44257305/123907405-6c525400-d9a8-11eb-924b-e8cc235d76f0.png)

**Comment by glk-hll** [comment]
为什么安装 `pro` 系列的模板组件运行都几乎都是依赖包报错，`pro` 系列各个包不是相互独立的吗？整了一天都是缺少什么什么包。。。

**Comment by chenshuai2144** [comment]
。。。是不是网络有抖动，这些包都是存在的。

你可以使用 tyarn

**Comment by maozhenyu123** [comment]
@chenshuai2144 rc-util 当前使用的版本5.4.0(pro-field 里定义的)，没有scrollLocker，在5.6.0之后才有，请检查。
