### ISSUE TITLE
ProLayout

### ISSUE THREAD

**Issue by jqueryandphp** [ant-design/pro-components#3126]
![image](https://user-images.githubusercontent.com/37691340/123910389-f13f6c80-d9ac-11eb-9655-3d6d864dc44d.png)
能不能把这个高度做成自适应的, 并且头部固定, 我传了headerHeight={"auto"}之后, 高度确实自适应了, 但是主体部分缺与header部分重合了
![image](https://user-images.githubusercontent.com/37691340/123910646-57c48a80-d9ad-11eb-85e4-caf1cff66cd9.png)
导致主体部分被掩盖, 我想做成头部自适应, 并且头部和主体不重合的, 这个有办法吗

**Comment by chenshuai2144** [comment]
动态计算高度吧，暂时没办法的，我们是写死的一个高度
