### ISSUE TITLE
🐛[BUG]ProTable在Modal里使用react-sortable-hoc来排序样式有问题

### ISSUE THREAD

**Issue by leonkong** [ant-design/pro-components#313]
### 🐛 bug 描述
按照AntDesign里样例使用react-sortable-hoc对ProTable内容排序，普通页面上使用函数组件创建页面排序没问题。但是当把ProTable放在Modal组件里作为弹窗弹出排序时，点击开始拖动和拖动过程中被排序的row空白，直到拖动结束释放鼠标才会显示，排序本身是对的。

### 📷 复现步骤
排序时移动鼠标到需要排序的行手柄处，按下鼠标左键后，当前行内容就消失空白了。拖动过程也是空白，直到最后移动到目标位置后释放鼠标，才会重新显示。

### 💻 复现代码

return (
    <Modal
      destroyOnClose
      title='排序'
      width='60%'
      visible={modalVisible}
      confirmLoading={loading}
      onOk={onOk}
      onCancel={() => onCancel()}
    >
      <ProTable<PackageCourseDetail>
        headerTitle=''
        search={false}
        pagination={false}
        rowKey='id'
        columns={columns}
        components={{
          body: {
            wrapper: DraggableContainer,
            row: DraggableBodyRow,
          },
        }}
        dataSource={dataList}
        options={false}
      />
    </Modal>
  );
};

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] ProTable 2.4.4和2.61都不行。ant Design 4.5.2和4.6.1都不行。
- umi 版本 3.2.16 
- 浏览器环境 Chrome和Edge最新版
- 开发环境 [e.g. mac OS]
macOS Mojave 10.15.6
VSCode Version: 1.48.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26429579/91257920-9e4dc500-e79d-11ea-98db-ebe15ce22038.png)

**Comment by chenshuai2144** [comment]
没用过这个工具，protable 自己是支持排序的，最好用自己的

**Comment by leonkong** [comment]
> 没用过这个工具，protable 自己是支持排序的，最好用自己的

ProTable支持鼠标拖动行排序么？我好像没找到文档说明支持这个啊

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/91540514-7ac97c80-e94d-11ea-9c38-00bbd1dfaaea.png)


可以用这个，做的太花不一定是好的

**Comment by leonkong** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/91540514-7ac97c80-e94d-11ea-9c38-00bbd1dfaaea.png)
> 
> 可以用这个，做的太花不一定是好的

这个是列排序吧？我想要的是行排序。。。ProTable我看之前的issue里讨论好像还是不支持行排序的吧？

**Comment by chenshuai2144** [comment]
那你可能需要用table了，protable的行受控起来比较麻烦

**Comment by HoroXu** [comment]
我也遇到这种问题 modal框里 添加table 拖动导致不显示 不知道解决没有啊

**Comment by HoroXu** [comment]
我解决了 ，antd modal的z-index应该是999 所以外面补充个样式z-index大过modal就好了 z-index：9999

**Comment by Evelyn1210** [comment]
> 我解决了 ，antd modal的z-index应该是999 所以外面补充个样式z-index大过modal就好了 z-index：9999

请问是在哪里补充样式，我在modal外补充样式大过modal的z-index，依然不起效果

**Comment by Evelyn1210** [comment]
已解决，SortableElement里的tr设置为超过Modal的z-index:999即。1000或者9999都ok
