### ISSUE TITLE
🐛Form中  ProFormField  如何设置能够将label和控件变成同一行

### ISSUE THREAD

**Issue by ZhengHuang-20** [ant-design/pro-components#3130]
### 🧐 问题描述
目前Form中嵌套ProFormField使用，无论如何改变Form中的layout  页面表单项显示都是lable占用一行，控件占用一行
![image](https://user-images.githubusercontent.com/61463534/123926649-aaf30900-d9be-11eb-873a-f3d96b36c5f3.png)

**Comment by 0x219** [comment]
ProForm组件的layout属性

**Comment by ZhengHuang-20** [comment]
> ProForm组件的layout属性

试了不行

**Comment by 0x219** [comment]
show code

**Comment by ZhengHuang-20** [comment]
`  <ProForm
            {...{
              labelCol: { span: 8 },
              wrapperCol: { span: 16 },
            }}
            layout="horizontal"
            key={index}
            requiredMark={true}
            form={form}
            style={{ marginBottom: '20px' }}
          >
            {tpItem.columns.map((columnsItem, index) => {
              if (columnsItem.valueType) {
                if (columnsItem.enumType || columnsItem.searchHelp) {
                  return (
                    <ProFormField
                      style={{ flexDirection: 'row' }}
                      key={`columnsItem.dataIndex${index}`}
                      label={columnsItem.title}
                      name={columnsItem.dataIndex}
                      fieldProps={{
                        showSearch: true,
                        optionFilterProp: 'label',
                        // filterOption: (input, option) => { return option.props.children.indexOf(input) >= 0 },
                        allowClear: true,
                      }}
                      rules={
                        columnsItem.required
                          ? [{ required: true, message: `请输入 ${columnsItem.title}!` }]
                          : []
                      }
                      mode={columnsItem.readOnly ? 'read' : 'edit'}
                      placeholder="模糊搜索"
                      valueType={columnsItem.valueType}
                      width="md"
                      onChange={(code, obj) => {
                        if (columnsItem.child) {
                          changeColumns(columnsItem.child, columnsItem.dataIndex);
                        }
                        // debugger
                        if (columnsItem.searchHelp || columnsItem.enumType) {
                          let codeKey = `${columnsItem.dataIndex.replace('Code', '')}Name`;
                          // debugger
                          if (columnsItem.valueType === 'select') {
                            if (obj) {
                              nameObj[codeKey] = obj['data-item'].label;
                            }
                          } else if (columnsItem.valueType === 'radio') {
                            if (code) {
                              nameObj[codeKey] = code.target.label;
                            }
                          }
                          setNameObj({ ...nameObj });
                        }
                      }}
                      request={async ({ keyWords }) => {
                        if (columnsItem.enumType) {
                          let enumArr = await getDicEnum(columnsItem.enumType);
                          new Promise((resolve) => {
                            recordEnum(columnsItem, enumArr.arr);
                            resolve();
                          }).then(() => {
                            console.log('确定执行完啦');
                          });

                          return enumArr.arr;
                        }
                        if (columnsItem.searchHelp && !columnsItem.parent) {
                          let enumArr = await getSearchHelpArr(columnsItem.searchHelp, {
                            name: keyWords,
                          });
                          new Promise((resolve) => {
                            recordEnum(columnsItem, enumArr);
                            resolve();
                          }).then(() => {
                            console.log('确定执行完啦');
                          });

                          return enumArr;
                        } else {
                          return [];
                        }
                      }}
                    />
                  );
                } else {
                  return (
                    <ProFormField
                      key={index}
                      label={columnsItem.title}
                      name={columnsItem.dataIndex}
                      rules={
                        columnsItem.required
                          ? [{ required: true, message: `请输入 ${columnsItem.title}!` }]
                          : []
                      }
                      mode={columnsItem.readOnly ? 'read' : 'edit'}
                      valueType={columnsItem.valueType}
                      width="md"
                      onChange={(...a) => {
                        if (columnsItem.valueType.indexOf('date') != -1) {
                          setTimeout(() => {
                            form.setFieldsValue({ [columnsItem.dataIndex]: a[1] });
                          }, 0);
                        }
                      }}
                    />
                  );
                }
              }
            })}
          </ProForm> `

**Comment by 0x219** [comment]
直接脑溢血...

**Comment by chenshuai2144** [comment]
试了一下可以的，来个 codesandbox 把

**Comment by ZhengHuang-20** [comment]
> 试了一下可以的，来个 codesandbox 把

解决了 layout应该在Modal进行设置，ProForm外边还有一个Modal

**Comment by zzzy1826** [comment]
> > 试了一下可以的，来个 codesandbox 把
> 
> 解决了 layout应该在Modal进行设置，ProForm外边还有一个Modal

可以问下如何解决的吗，我用的ModalForm，使用layout，但里面的ProFormDigit表单项和label还是不在一行
