### ISSUE TITLE
🧐[EditableProTable中onChange和editable如何使用？]

### ISSUE THREAD

**Issue by sunxia628** [ant-design/pro-components#3131]
### 🧐 EditableProTable中onChange无法触发，editable中onChange不生效但onValuesChange却可以使用
1.EditableProTable中onChange没有生效；
2.EditableProTable中editable的onChange不生效但onValuesChange却可以使用（文档中没有这个API）

### 💻 示例代码
        <EditableProTable
          headerTitle="地震工作量年计划"
          columns={columns}
          rowKey="DBID"
          form={this.formRef}
          value={dataSource}
          onChange={this.setDataSource}
          recordCreatorProps={false} // 新建一行数据的相关配置
          toolBarRender={() => {
            return [
              <DatePicker
                picker="year"
                onChange={this.handleYearChange}
                value={moment(nf, "YYYY")}
              />,
              <Button
                type="primary"
                key="save"
                onClick={this.handleSave}
                icon={<SaveOutlined />}
              >
                保存
              </Button>,
              <span>
                入库状态: <span>{nf === year ? "已入库" : "未入库"}</span>
              </span>,
            ];
          }}
          editable={{
            type: "multiple",
            editableKeys: editableKeys,
            onChange: this.setEditableRowKeys,
            onValuesChange: this.handleValuesChange,
          }}
        />

使用setDataSource修改dataSource数据源可以满足我的需求，但是不够精细（比如：我的首行数据是根据下方行的数据累加的结果，对应列累加，由于获取不到当前更改的列标识，我只能将所有列累加一边-多余，虽然react的diff做了优化，但是开发工程师却和前台却写了多余的代码和计算）

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26341016/123934764-315f1900-d9c6-11eb-8578-5ef5d5740077.png)
![image](https://user-images.githubusercontent.com/26341016/123934912-518ed800-d9c6-11eb-99d6-73ee5412b825.png)

**Comment by chenshuai2144** [comment]
<html>
<body>


controlled | 是否受控, 如果受控每次编辑都会修改 dataSource | boolean | false
-- | -- | -- | --



</body>
</html>


controlled  打开就会触发 onchange

**Comment by sunxia628** [comment]
<div className={styles['content-warp']}>
        <h3 className={styles['table-title']}>地震工作量年计划</h3>
        <h4 className={styles['table-subtitle']}>油田事业部生产运行处</h4>
        <div className={styles['custom-header']}>{toolBarRender}</div>
        <EditableProTable
          // controlled={true}
          // headerTitle={"地震工作量年计划-油田事业部生产运行处"}
          debounceTime={200}
          loading={loading}
          columns={columns}
          rowKey="DBID"
          value={dataSource}
          onValuesChange={this.onValuesChange}
          recordCreatorProps={false} // 新建一行数据的相关配置
          // toolBarRender={() => {
          //   return toolBarRender;
          // }}
          editable={{
            type: "multiple",
            editableKeys: editableKeys,
            // onValuesChange: this.handleValuesChange,
          }}
        />
      </div>
