### ISSUE TITLE
🧐[问题] EditableProTable 如何从组件外部触发行保存

### ISSUE THREAD

**Issue by fangzhengjin** [ant-design/pro-components#3133]
### 🧐 问题描述
EditableProTable 如何从组件外部触发行保存?
从外部开启行编辑可以用editableKeys, actionRef但是如果更改editableKeys, 只是取消编辑, 数据不会留存, actionRef没有提供触发行保存的方法, 应该如何操作呢?

**Comment by glk-hll** [comment]
@fangzhengjin 请问我安装 `@ant-design/pro-form` 之后使用相关的`ProForm` 组件就会报错：
![error](https://user-images.githubusercontent.com/44257305/123907405-6c525400-d9a8-11eb-924b-e8cc235d76f0.png)

是怎么回事，这些 `Pro` 系列的模板组件不都是独立的包么？安装使用怎么会报依赖的错。

**Comment by chenshuai2144** [comment]
@glk-hll 试试重新安装所有依赖，这个问题是某个依赖没装上

**Comment by chenshuai2144** [comment]
可以用 `form.submit()`
```
const [form] = Form.useForm()
<ProTable
 editable={{
        type: 'multiple',
        form,
      }}
/>
form.submit()
```

**Comment by chenshuai2144** [comment]
打开一下受控模式呢。

**Comment by rickythink** [comment]
可以采用最新的api
https://github.com/ant-design/pro-components/pull/6081

**Comment by 250king** [comment]
> 打开一下受控模式呢。

打开了也没有啊
