### ISSUE TITLE
EditableProTable translation of add button🧐[问题]

### ISSUE THREAD

**Issue by JessicaFournier** [ant-design/pro-components#3142]
How can I translate the add button which is appear when recordCreatorProps={true} in <EditableProTable/> ? All my application is in French and this button is in chinese.
![ant_proTable](https://user-images.githubusercontent.com/69592411/124151465-de9f6300-da92-11eb-9c7c-d34232957f89.png)

**Comment by binvb** [comment]
you can set the buttuon with recordCreatorProps props, e.g.
```
        recordCreatorProps={
          position !== 'hidden'
            ? {
                creatorButtonText: 'Ajouter une nouvelle ligne',
                position: position as 'top',
                record: () => ({ id: (Math.random() * 1000000).toFixed(0) }),
              }
            : false
        }
```

**Comment by JessicaFournier** [comment]
Thank you For you response !
