### ISSUE TITLE
🧐[问题] 请问pro-table可以自己管理数据源吗？就是不用配置request属性，手动管理远程数据的获取、处理

### ISSUE THREAD

**Issue by effapp** [ant-design/pro-components#3144]
### 🧐 问题描述

请问pro-table可以自己管理数据源吗？就是不用配置request属性，手动管理远程数据的获取、处理

**Comment by B-sirius** [comment]
![image](https://user-images.githubusercontent.com/15071193/124215926-9aaa6d80-db27-11eb-89c9-3e5954316a9a.png)

可以的，API和antd相同
