### ISSUE TITLE
🧐[问题] pro-form的transform跳过对象的转换

### ISSUE THREAD

**Issue by RIPm** [ant-design/pro-components#3145]
### 🧐 问题描述
* transform对基本返回值类型都进行转换是合理的吧？
* 这里为什么要跳过对对象类型的转换，是遇到什么场景所以才决定跳过？

### 💻 示例代码
transform 源码：
```js
const gen = (tempValues: T, parentsKey?: React.Key[]) => {
    let result = {} as T;

    if (tempValues == null || tempValues === undefined) {
      return result;
    }
    Object.keys(tempValues).forEach((entryKey) => {
      const key = parentsKey ? [parentsKey, entryKey].flat(1) : [entryKey].flat(1);
      const itemValue = tempValues[entryKey];
      if (
        typeof itemValue === 'object' &&
        !Array.isArray(itemValue) &&
        !React.isValidElement(itemValue) && // ignore walk throungh React Element
        !(itemValue instanceof Blob) // ignore walk throungh Blob
      ) {
        const genValues = gen(itemValue, key);
        if (Object.keys(genValues).length < 1) {
          return;
        }
        result = namePathSet(result, [entryKey], genValues);
        return;
      }
      const transformFunction = get(dataFormatMap, key);
      const tempKey =
        typeof transformFunction === 'function'
          ? transformFunction?.(itemValue, entryKey, tempValues)
          : entryKey;
      // { [key:string]:any } 数组也能通过编译
      if (Array.isArray(tempKey)) {
        result = namePathSet(result, tempKey, itemValue);
        return;
      }
      if (typeof tempKey === 'object') {
        finalValues = {
          ...finalValues,
          ...tempKey,
        };
      } else if (tempKey) {
        result = namePathSet(result, [tempKey], itemValue);
      }
    });
    // namePath、transform在omit为false时需正常返回 https://github.com/ant-design/pro-components/issues/2901#issue-908097115
    return omit ? result : tempValues;
  };

  finalValues = merge(gen(values), finalValues);

  return finalValues;
};
```
跳过了对象的处理
```js
typeof itemValue === 'object' &&
!Array.isArray(itemValue) &&
```

**Comment by chenshuai2144** [comment]
我们的目标是只对 数据对象做处理，别的都不会做处理

**Comment by jddxf** [comment]
`Select` 在 `labelInValue` 模式下的值是对象形式的，该怎么进行 transform 呢

**Comment by RIPm** [comment]
> `Select` 在 `labelInValue` 模式下的值是对象形式的，该怎么进行 transform 呢

没法`transform`。他们设计就是不支持

**Comment by jddxf** [comment]
@RIPm 这样子。。那你知道 transform 的使用场景吗？我本来以为是用于将表单数据转换成请求参数的，那样的话应该请求前 transform 一下就行了，但是发现每次值改变都会调用 transform。

**Comment by RIPm** [comment]
改了吗？ 值改变不会触发的

> @RIPm 这样子。。那你知道 transform 的使用场景吗？我本来以为是用于将表单数据转换成请求参数的，那样的话应该请求前 transform 一下就行了，但是发现每次值改变都会调用 transform。

**Comment by jddxf** [comment]
会的，可以加 console.log 试下。 https://codesandbox.io/s/etlig?file=/App.tsx:1991-2005

**Comment by zwmmm** [comment]
> @RIPm 这样子。。那你知道 transform 的使用场景吗？我本来以为是用于将表单数据转换成请求参数的，那样的话应该请求前 transform 一下就行了，但是发现每次值改变都会调用 transform。

我理解也是这个意思 但实际上这个transform锤子用没有 各种不生效 组件本身值改变也会触发 看文档的意思又是提交数据的时候触发

**Comment by PEDx** [comment]
> `Select` 在 `labelInValue` 模式下的值是对象形式的，该怎么进行 transform 呢

<img width="409" alt="截屏2023-11-29 15 23 16" src="https://github.com/ant-design/pro-components/assets/16054017/06a1438d-62c8-445c-8e66-9e098982b379">

**Comment by one-pieces** [comment]
> > @RIPm 这样子。。那你知道 transform 的使用场景吗？我本来以为是用于将表单数据转换成请求参数的，那样的话应该请求前 transform 一下就行了，但是发现每次值改变都会调用 transform。
> 
> 我理解也是这个意思 但实际上这个transform锤子用没有 各种不生效 组件本身值改变也会触发 看文档的意思又是提交数据的时候触发

是的，乱七八糟的，各种不 work
