### ISSUE TITLE
👑 [需求]布局内容区域是否可以像浏览器标签页一样的功能

### ISSUE THREAD

**Issue by robin536180** [ant-design/pro-components#3146]
### 🥰 需求描述
点击左侧路由，右侧可以新建个便签页，在路由上配置是否可以添加至标签页

### 🧐 解决方案
可以在onPageChange的时候在cookie里面存一个变量，把当前的地址存进去
但是切换标签页的时候怎么切换里面的内容？匹配route里面的component?

### 🚑 其他信息
<img width="847" alt="截屏2021-07-02 上午11 21 08" src="https://user-images.githubusercontent.com/8565176/124217202-7a2fe280-db2a-11eb-8a07-7e620ce7271e.png">

**Comment by chenshuai2144** [comment]
这个讨论很久了，社区有方案，但是有严重的性能问题所以官方不会内置也不推荐. 官方需要等 react 出现与 vue keeplive  同样的功能才会开始考虑

`umi-plugin-keeplive`
