### ISSUE TITLE
🐛[BUG]麻烦把最近新架构调整后同步更新一下文档，最好能标注出来那些地方是本次修改的

### ISSUE THREAD

**Issue by gameruleCEO** [ant-design/pro-components#315]
### 🐛 bug 描述
[官网文档](https://procomponents.ant.design/)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
期望是无感的，现在看来改动不是很很大。
你可以看看 https://procomponents.ant.design/changelog/pro-table
