### ISSUE TITLE
🐛[BUG] ProTable 在编辑保存时，当前修改的行的值与原始值相同

### ISSUE THREAD

**Issue by tazyong** [ant-design/pro-components#3150]
### 🐛 bug 描述

ProTable 在编辑保存时，当前修改的行的值与原始值相同，导致无法比较更新了哪些字段。

代码地址：https://codesandbox.io/s/table-demo-to1p2?file=/src/pages/index.tsx
文档地址：https://procomponents.ant.design/components/editable-table/#editable-编辑行配置

还有以下问题如果解决？
![image](https://user-images.githubusercontent.com/24738011/124256072-78334700-db5d-11eb-8f5c-0aa9268f27b2.png)

### 📷 复现步骤

任何时候。

### 🏞 期望结果

希望可以输出不同对象，可以比较属性变化。

### 💻 复现代码

描述中有代码地址。

### © 版本信息

- ProTable 版本: 2.43.3
- umi 版本: 3.5.0
- 浏览器环境: Chrome 91.0.4472.114
- 开发环境: Windows 10

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/24738011/124255072-571e2680-db5c-11eb-96a6-df705d60447a.png)
![image](https://user-images.githubusercontent.com/24738011/124255211-7fa62080-db5c-11eb-979c-5bc1a3d0df25.png)
![image](https://user-images.githubusercontent.com/24738011/124255478-c85dd980-db5c-11eb-9ced-bfd713296486.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/124360328-bf076680-dc5b-11eb-9571-da8872f69c91.png)


不要重复设置 initialvalues 可以解决

**Comment by Mrjen** [comment]
同样的问题， record 和 originRow 相同

**Comment by colorbitch** [comment]
是不是自定义的组件，如果没有实现onChange和value的话，row里对应那一列的值不会更新的。

不过我这的情况是originRow每次都拿不到，不知道啥情况😂

**Comment by chj-damon** [comment]
我在EditableProTable 里面也发现一样的问题。https://github.com/ant-design/pro-components/issues/8125
