### ISSUE TITLE
👑 [Feature Request] ProTable: Implement Grouping

### ISSUE THREAD

**Issue by spencer741** [ant-design/pro-components#3153]
### Description of Requirement

Ability for columns to be grouped via dragging.

Group rows together that share a column value, this creates a visible header for each group and allows the end-user to collapse groups that they don't want to see.

**Examples:**
- https://www.ag-grid.com/javascript-grid-grouping/
- https://material-table.com/#/docs/features/grouping
- https://www.telerik.com/kendo-react-ui/components/grid/grouping/
- https://ej2.syncfusion.com/react/demos/#/material/grid/aggregate-group
- https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/grouping/
- http://tabulator.info/docs/4.5/group
- https://www.infragistics.com/products/ignite-ui-react/react/components/data-grid-row-grouping.html
- https://adazzle.github.io/react-data-grid/docs/examples/basic-grouping

Here is a pretty good UX guideline from AirTable:
https://support.airtable.com/hc/en-us/articles/221747587-Guide-to-grouped-records

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，我的回复似乎与用户问题不太相关。以下是一个针对此问题的更加得体的回复：

你好！感谢您将问题反馈给我们。作为 GitHub issue 助理，我们只能处理关于 React 的前端问题。对于您提出的功能请求，我们非常乐意接受您的贡献。如果您打算通过编写代码来添加此功能，请遵循我们的 [贡献指南](https://github.com/ant-design/ant-design-pro-table/blob/master/.github/CONTRIBUTING.md)，确保您的代码与其他部分的工作顺利合并。如果您遇到任何困难，请随时联系我们寻求帮助。 谢谢！
