### ISSUE TITLE
🐛[BUG] autoClose on menu is not working as expected

### ISSUE THREAD

**Issue by jakecastelli** [ant-design/pro-components#3157]
### 🐛 bug 描述

In the [documentation](https://procomponents.ant.design/components/layout) it says `autoClose` its default to `true` and according to the doc, it supposes to close the menu on the small screen when the user clicks the menu item. But in reality, its not closing the side menu after clicks and the type seems incorrect, it only has `false | undefined`
![Screen Shot 2021-07-04 at 12 20 31 am](https://user-images.githubusercontent.com/38635403/124358052-a730e200-dc5d-11eb-9e71-872998fbc3c6.png)

Ref: https://github.com/ant-design/pro-components/issues/2388
### 🏞 期望结果
Type for autoClose should be `true | false` and when the user clicks the item within the sidebar the side bar should close

### 💻 复现代码
` menu={{autoClose}}`

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
It is not compatible with the use of mix
