### ISSUE TITLE
🐛[BUG] ProFormSelect 使用 request api 会报 ‘Can't perform a React state update on an unmounted component’ 错

### ISSUE THREAD

**Issue by shanzhaozhen** [ant-design/pro-components#3158]
### 🐛 bug 描述
ProFormSelect 使用 request api 会报 ‘Can't perform a React state update on an unmounted component’ 错

### 📷 复现步骤
ProFormSelect 使用 request api

### 🏞 期望结果
console干干净净不报错

### 💻 复现代码
```
<ProFormSelect
  width="sm"
  name="depId"
  label="部门"
  rules={[{ required: false, message: '请选择部门' }]}
  request={async () => {
    const { data } = await getAllDepartments();
    return data ? data.map(item => ({
      value: item.id,
      label: item.name
    })) : []
  }}
/>
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/29800728/124362230-48bc3180-dc66-11eb-8e83-e694c65a161e.png)

**Comment by binvb** [comment]
request | 从网络请求枚举数据 | ()=>Promise<{[key:string\|number]:any}>
-- | -- | --

**Comment by binvb** [comment]
这里需要返回的是promise或者是数组，e.g.
```
          request={async () => {
            const data = await getAllDepartments();
            return new Promise((resolve, reject) => {
              resolve(data ? data : [])
            })
          }}
```
