### ISSUE TITLE
🧐[问题]pro-table自带的form模式，在columns里配置rules不生效

### ISSUE THREAD

**Issue by Hikarien** [ant-design/pro-components#316]
### 🧐 问题描述

pro-table自带的form模式，在columns里配置rules不生效

### 💻 示例代码
```js
const columns = [
    {
        title: '类型代码',
        dataIndex: 'code',
        sorter: 'true',
        rules: [{ required: true, message: '请输入用户编号！' }]
    },
    {
        title: '包装类型',
        dataIndex: 'name',
        sorter: 'true'
    }
]
```
配置了rules后，表单展示的时候没有把code字段作为必填项，不知道现在是不是要在别的地方配置？
以上用法在pro-table 2.3.1版本是可以的，目前用2.6.1无效了
### 🚑 其他信息
![image](https://user-images.githubusercontent.com/41961907/91268652-4b2d3f80-e7a8-11ea-9fed-171ca80715bc.png)

**Comment by aoyinke** [comment]
同问，而且样式也变了

**Comment by chenshuai2144** [comment]
用 formItemProps

**Comment by Hikarien** [comment]
@chenshuai2144  之前试了fieldProps没成功，现在好了，多谢！

**Comment by wanqi87** [comment]
![image](https://user-images.githubusercontent.com/3838237/103440914-a6a29900-4c84-11eb-94e7-9a310426b8a4.png)
