### ISSUE TITLE
🐛[BUG]在Modal组件里，Protable 的search 显示 0

### ISSUE THREAD

**Issue by gaspire** [ant-design/pro-components#3160]
### 🐛 bug 描述

在Modal组件里，Protable 的search 显示 0, 在开发者工具里，修改下 ant-modal-body的padding，就显示出查询表单了

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/49259119/124422549-0a259480-dd96-11eb-9ed1-3a157e5230e0.png)

### 🏞 期望结果
期望显示查询表单

### © 版本信息

- @ant-design/pro-table 版本: [2.17.0]
- umi 版本 [3.2.14]
- 浏览器环境 [chrome]
- 开发环境 [mac OS]

**Comment by xccxcs** [comment]
+1 本地代码没问题 线上自动打包 每次会更新组件 出现相同问题
