### ISSUE TITLE
🧐[问题] SchemaForm和ModalForm能否一起使用

### ISSUE THREAD

**Issue by 1247748612** [ant-design/pro-components#3163]
### 🧐 问题描述
想要使用ModalForm，但是想以SchemaForm的形式渲染成表单

**Comment by chenshuai2144** [comment]
```
/** ProForm 的特色 layout */
export type ProFormLayoutType =
  | 'Form'
  | 'ModalForm'
  | 'DrawerForm'
  | 'StepsForm'
  | 'StepForm'
  | 'LightFilter'
  | 'QueryFilter'
  | 'Embed';

```

可以配置 layoutType 支持以上类型

**Comment by chenshuai2144** [comment]
## ProFormLayoutType

| 字段名称 | 说明 |
| --- | --- |
| `Form` | [ProForm](/components/form) 是基本的表单类型 |
| `ModalForm` | 弹框表单，配置之后支持 [ModalForm](/components/modal-form) 的所有配置 |
| `DrawerForm` | 抽屉表单，配置之后支持 [DrawerForm](/components/modal-form) 的所有配置 |
| `StepsForm`\|`StepForm` | 配置之后为分步表单，有两种模式一种使用 `steps` 和 `columns` 来生成，一种是通过 `layoutType=StepsForm` 嵌套 `layoutType=StepForm` 来实现 |
| `LightFilter` | 轻量筛选，配置之后支持 [`LightFilter`](/components/query-filter) 的所有配置 |
| `QueryFilter` | 查询表单，配置之后支持 [`QueryFilter`](/components/query-filter) 的所有配置 |
| `Embed` | 内嵌模式，只生成表单项，不生成 Form 可以混合使用 |
