### ISSUE TITLE
🐛[BUG] Solved getPopupContainer bug has been found in new version

### ISSUE THREAD

**Issue by j137228135** [ant-design/pro-components#3165]
### 🐛 bug 描述

[This bug](https://github.com/ant-design/pro-components/issues/1278) has been solved in pro-table 2.29.0, but it has been found in new version 2.43.3 (maybe earlier).

### 📷 复现步骤

set getPopupContainer in ConfigProvider

### 🏞 期望结果

Dropdown can be shown after setting getPopupContainer

### 💻 复现代码

https://codesandbox.io/s/chaxunbiaoge-forked-ksu01?file=/App.tsx

### © 版本信息

- Protable 版本:  2.43.3
- 浏览器环境 chrome
- 开发环境 mac OS

### 🚑 其他信息

remove overflow:hidden
```
.ant-pro-form-query-filter .ant-form-item-control {
    /* overflow: hidden; */
}
```

**Comment by j137228135** [comment]
@chenshuai2144  https://codesandbox.io/s/pro-components-issues-3165-ksu01 麻烦看一下，谢谢

**Comment by ZJL8** [comment]
.ant-form-horizontal .ant-form-item-control {
  flex: 1;
} 
// 该样式有产生影响

**Comment by chenshuai2144** [comment]
新版本就会修复
