### ISSUE TITLE
👑 [需求]table组件可以保存筛选条件到query上

### ISSUE THREAD

**Issue by jiaicon** [ant-design/pro-components#317]
通常table的行操作，都是跳转页面实现的，就要求在用户回退时，可以重新渲染到跳转前的数据。
一般都是保存筛选、分页到url上，但antd的table不支持，希望组件可以实现这一点。

**Comment by beysong** [comment]
能补个文档吗，如何使用的😁

**Comment by ouzhou** [comment]
自己实现的话，就是在url加query,  组件第一次加载的时候先阻止查询，读取query然后调用一下设置搜索表单的默认值，再调用搜索

至于要不要每一次搜索都要改变url的query就看产品的需求了，毕竟一般常见的场景都是带参数跳转到table页面

**Comment by hengkx** [comment]
@chenshuai2144 any progress?

**Comment by beysong** [comment]
试了下，功能有了，但是重置按钮失效了，清不掉搜索条件

**Comment by chenshuai2144** [comment]
@beysong  提个bug，应该是和url 同步的问题
