### ISSUE TITLE
如何进行本地调试开发？

### ISSUE THREAD

**Issue by Lind-pro** [ant-design/pro-components#3174]
### Discussed in https://github.com/ant-design/pro-components/discussions/3172

<div type='discussions-op-text'>

<sup>Originally posted by **Lind-pro** July  7, 2021</sup>
想修改源码发现每次修改之后demo不生效，只能重新build才生效。但是build的时间也太长了吧。</div>

**Comment by chenshuai2144** [comment]
会自动更新的，你没有使用  yarn 安装还是大小写有问题

**Comment by Lind-pro** [comment]
研究了一下是如果没有build，直接start是可以热更新的。但是一旦执行过build，热更新就不行了，执行build之后似乎是运行的build之后的代码。
