### ISSUE TITLE
🧐[问题] ProForm 中不管有多少个 Input，只要聚焦在 Input 上按下回车就会触发提交

### ISSUE THREAD

**Issue by ETRick** [ant-design/pro-components#3179]
### 🧐 问题描述
 ProForm 中 在聚焦的 input 上按下回车就会触发 form 表单的提交。这个和一般的规范是不符的，不知为什么要这么设计。

https://github.com/ant-design/pro-components/blob/a313d70e154e3a069dbd729f16fe0f580da9d493/packages/form/src/BaseForm/index.tsx#L304-L308

**Comment by chenshuai2144** [comment]
是为了方便queryFilter 和 登录表单，你是什么场景？

**Comment by ETRick** [comment]
> 是为了方便queryFilter 和 登录表单，你是什么场景？

我这边就是用了 ProForm 出现了 Input 中回车导致整个 Form 提交。产品觉得这个很奇怪。我这边现在手动复写了 ProForm 的 onKeyPress 来规避这个问题。

**Comment by chenshuai2144** [comment]
产品的心思你看不懂，回车提交表单还是很好用的。
或者有什么两全的方案可以试着提出来
