### ISSUE TITLE
👑 [需求] pro-table v2.6.1 关于时间范围筛选的问题，搜索值不是一个数组

### ISSUE THREAD

**Issue by dmdoit** [ant-design/pro-components#318]
### 🥰 需求描述
后台返回的数据是，createdAt: 1598425754000，是一个时间戳
此处前端代码
```
{
    title: '下单时间',
    dataIndex: 'createdAt',
    key: 'createdAt',
    valueType: 'dateRange',
    render: (_, record) => dateTime(record.createdAt, 'YYYY-MM-DD HH:mm:ss'),
}
```
筛选时查询提交的params参数是
```
createdAt: 2020-08-25
createdAt: 2020-08-26
```
而不是
```
createdAt[]: 2020-08-25
createdAt[]: 2020-08-26
```
或者
```
createdStart: 2020-08-25
createdEnd: 2020-08-26
```

**请问应该如何处理，我相信大部分的业务需求都是如此吧！**

![image](https://user-images.githubusercontent.com/19385704/91273552-01e0ee00-e7b0-11ea-88b8-a3cea7b8c520.png)

### 🧐 解决方案
希望搜索参数变成
```
createdAt[]: 2020-08-25
createdAt[]: 2020-08-26
```
或者
```
createdStart: 2020-08-25
createdEnd: 2020-08-26
```
Table中的createdAt 最后是一个值显示，而不是一个[]，如果后台传的不是数组，现在还需要用render渲染，用renderText都不起作用

**Comment by chenshuai2144** [comment]
> Table中的createdAt 最后是一个值显示，而不是一个[]，如果后台传的不是数组，现在还需要用render渲染，用renderText都不起作用

有兴趣搞个 pr 吗？ 做个降级方案 如果 createdAt 不是数组，就当成默认的 dataTime 来处理

**Comment by dmdoit** [comment]
发现了一个问题， 我在beforeSearchSubmit里打印了createdAt
```
beforeSearchSubmit={(params) => console.log(params)}
```
发现createdAt是一个数组
```
{createdAt: ["2020-08-25", "2020-08-26"]}
```
那么原因就是在request中被转化了
```
import request from '../utils/request';
import { stringify } from 'qs';
export async function queryOrdersList(params) {
  return request(`/api/orders?${stringify(params, {arrayFormat: 'brackets'})}`);
}
```
使用stringify重新定义一下就可以了。
现在的请求参数就是
```
createdAt[]: 2020-08-25
createdAt[]: 2020-08-26
```

原来的有问题的写法是下边这样写的：
```
export async function queryOrdersList(params) {
  return request('/api/orders', {params});
}
```
我看到Issues里好多人反馈这个问题，我也被困扰了，不知道有没有其他的解决办法.

**Comment by chenshuai2144** [comment]
需要一个新的方案，其实最好是 startTime 和 endTime

**Comment by lm356536** [comment]
级联组件也有这个问题.  比如三级地区选择的那个会显示三个出来.

**Comment by chenshuai2144** [comment]
ref https://github.com/ant-design/pro-components/pull/426
