### ISSUE TITLE
ProTable中既有formRef 用来提交表单 又需要actionRef来刷新页面 怎么引入

### ISSUE THREAD

**Issue by robin536180** [ant-design/pro-components#3180]

**Comment by DerrickTel** [comment]
https://procomponents.ant.design/components/table/#%E6%9F%A5%E8%AF%A2%E8%A1%A8%E6%A0%BC
第一个例子就有呀，还是我理解错了？稍微具体一点

**Comment by robin536180** [comment]
<img width="1412" alt="截屏2021-07-08 下午2 57 53" src="https://user-images.githubusercontent.com/8565176/124876742-ef088e00-dffc-11eb-8fdb-2c65e2534932.png">
列表: <ProTable formRef={ref} /> 
点击新建的时候 <<ModalForm onFinish={() => ref.current.方法}><ProTable actionRef={ref} /> </<ModalForm> 用模态框包了一层  现在关闭模态框后 我需要刷新列表 需要调用actionRef.current.reload() 就是不知道怎么写

**Comment by DerrickTel** [comment]
https://codesandbox.io/s/chaxunbiaoge-forked-q4d2s?file=/App.tsx

**Comment by robin536180** [comment]
https://codesandbox.io/s/chaxunbiaoge-forked-xeo9f?file=/App.tsx
您在帮我看下，如果是这种情况，我在模态框怎么调用表单提交方法

**Comment by DerrickTel** [comment]
> https://codesandbox.io/s/chaxunbiaoge-forked-xeo9f?file=/App.tsx
> 您在帮我看下，如果是这种情况，我在模态框怎么调用表单提交方法

不是很理解你现在的场景，方便说一下需求吗？我看这代码云里雾里的
