### ISSUE TITLE
🧐[问题] 请问如何去掉地址栏中的 分页信息

### ISSUE THREAD

**Issue by wyjie** [ant-design/pro-components#3183]
### 🧐 问题描述

在页面中使用pro table后，浏览器地址栏会自动添加分页数据 ： ?current=1&pageSize=50, 可以设置去除吗？

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/13830998/124903391-80d0c500-e016-11eb-83b6-c6cebe902558.png)

**Comment by chenshuai2144** [comment]
<html>
<body>


syncToUrl | 同步参数到 url 上,url 只支持 string，在使用之前最好读一下url 中的参数类型 | true \| (values,type)=>values | -
-- | -- | -- | --
syncToInitialValues | 同步结果到 initialValues,默认为 true 如果为 false，form.reset 的时将会忽略从 url 上获取的数据 | boolean | true


</body>
</html>

**Comment by wyjie** [comment]
@chenshuai2144 感谢
