### ISSUE TITLE
🐛[BUG] menuDataRender 不会跟随主题切换而触发 再次渲染

### ISSUE THREAD

**Issue by leehomeok** [ant-design/pro-components#3187]
### 🐛 bug 描述

现在我们有一个主题切换的场景 ，需要根据主题色 切换不同主题下的icon，
也就是需要动态变换icon，
但是主题切换了，没有执行menuDataRender 方法

### 🏞 期望结果

menuDataRender  会随着主题切换而触发执行

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
执行以下 reload, 刷新整个页面，或者用useModel 搞个变量强制触发一些组件更新。

不然 主题更改只是纯粹的 css 渲染不会更改的到menuItemRender的

**Comment by leehomeok** [comment]
> useModel
是 menuDataRender 方法，不是 menuItemRender ，
请问如果用 useMode 触发组件更新 需要怎么改？

**Comment by chenshuai2144** [comment]
在 useMode  里面存一个key，需要强制刷新就设置一 下key
