### ISSUE TITLE
🐛[BUG] prolayout的title传入ReactNode时页面标题显示不正确

### ISSUE THREAD

**Issue by Trick93** [ant-design/pro-components#319]
### 🐛 bug 描述

`ProLayout` 组件，如果 `title` 属性传入一个 `ReactNode`，页面标题也就是 `document.title` 会变成 `[Object Object]`

### 📷 复现步骤

`title`属性传入 `ReactNode`

### 🏞 期望结果

标题应该正常显示

### 💻 复现代码

https://codesandbox.io/s/sleepy-bardeen-urbft?file=/index.js

### © 版本信息

- pro-layout 版本: [^6.4.11]
- 浏览器环境
- 开发环境 [win]

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/91289564-18457480-e7c5-11ea-8c4a-fd6d72aa580c.png)

显示的不对吗？

**Comment by Trick93** [comment]
> ![image](https://user-images.githubusercontent.com/29775873/91289564-18457480-e7c5-11ea-8c4a-fd6d72aa580c.png)
> 
> 显示的不对吗？

不是这个标题 是 document.title 标签页上的标题，你在新窗口运行就能看到

**Comment by chenshuai2144** [comment]
那个不支持 reactNode 的，用 pageTitleRender 自己修改一下吧
