### ISSUE TITLE
👑 [需求] Pro-Table.查询数据带了默认参数，怎么处理？

### ISSUE THREAD

**Issue by Lind-pro** [ant-design/pro-components#3190]
### 🥰 需求描述
进入表格时URL带了默认参数，希望在重置时不把默认参数删掉

**Comment by chenshuai2144** [comment]
<html>
<body>


syncToUrl | 同步参数到 url 上,url 只支持 string，在使用之前最好读一下url 中的参数类型 | true \| (values,type)=>values | -
-- | -- | -- | --
syncToInitialValues | 同步结果到 initialValues,默认为 true 如果为 false，form.reset 的时将会忽略从 url 上获取的数据 | boolean | true


</body>
</html>

**Comment by chenshuai2144** [comment]
看看这个api

**Comment by ideaviewes** [comment]
@chenshuai2144 ，没有在文档中找到syncToUrl和syncToInitialValues，请问这两个配置项，要配置在哪里？

**Comment by chenshuai2144** [comment]
在 form 配置上，因为form的配置比较多，需要跳转页面查看

**Comment by ideaviewes** [comment]
@chenshuai2144 ，谢谢，这个需求应该是table用的多吧，我一时没反应过来，在table的配置项中找了半天

**Comment by chenshuai2144** [comment]
文档链接没做好

**Comment by BarryLiu1995** [comment]
> antd 的form api中我也没找到

应该是要去 ProForm api 去找

**Comment by whuwangyong** [comment]
> syncToUrl	同步参数到 url 上,url 只支持 string，在使用之前最好读一下url 中的参数类型	true | (values,type)=>values	-
> syncToInitialValues	同步结果到 initialValues,默认为 true 如果为 false，form.reset 的时将会忽略从 url 上获取的数据	boolean	true

帮大忙了，非常感谢。自己写了半天拿不到URL参数，没想到有现成的配置！
