### ISSUE TITLE
👑 [actionRef能否暴露query方法和点击查询按钮一样，获取search查询参数，调用request查询table数据]

### ISSUE THREAD

**Issue by sunxia628** [ant-design/pro-components#3192]
### 🥰 需求描述

actionRef能否暴露query方法和点击查询按钮一样，获取search查询参数，调用request查询table数据]
目前actionRef.current只有reload，reset，reloadAndRest查询
![C15A1EAD-E429-40df-B993-2AD053382B8E](https://user-images.githubusercontent.com/26341016/125018758-516a9880-e0a8-11eb-9c3b-4c89d90dd5bf.png)
我的查询参数需要先通过接口1获取下拉选项列表，然后formRef.current.setFieldsValue设置初始值；
通过设置全局变量isMounted，我可以在componentDidMount调用接口更新数据；
但是无论defaultData还是怎样，由于request初始化没有获取到数据，就不触发更新了；
所以我需要在isMounted时调用actionRef的内置方法取触发request查询更新table数据，但是不能通过reload将查询参数丢失；

### 🧐 解决方案

目前没有找的解决方案，刚想到了利用session存储reload前存储查询参数，每次查询获取上一次缓存的查询参数，但是这也太low了，希望可以有更好的解决方案

**Comment by chenshuai2144** [comment]
使用 `formRef.current.submit()` 就可以触发提交按钮

**Comment by sunxia628** [comment]
非常感谢，没有想到form和table是独立可触发的！
