### ISSUE TITLE
如何用dayjs替换momentjs

### ISSUE THREAD

**Issue by superlbr** [ant-design/pro-components#3194]
rt

**Comment by Shenlu1** [comment]
chainWebpack(memo) {
        //  使用day.js替换moment.js
        memo.plugin('AntdDayjsWebpackPlugin').use(AntdDayjsWebpackPlugin);
},

**Comment by superlbr** [comment]
umi 开mfsu会报错

**Comment by 3hson** [comment]
i have same problem after enabling msfu:

`Uncaught TypeError: moment__WEBPACK_IMPORTED_MODULE_0___default(...).isMoment is not a function`

**Comment by JoyceLizhuo** [comment]
同问，期望能够使用dayjs替换moment

**Comment by chenshuai2144** [comment]
2.0 版本默认使用了 dayjs 已经可以开始了
