### ISSUE TITLE
👑 [需求] editableProTable自定义组件onSave拿不到最新的值

### ISSUE THREAD

**Issue by Shenlu1** [ant-design/pro-components#3196]
### 🥰 需求描述
    使用editableProTable时，columns不同字段的renderFormItem有联动关系的时候，通过自定义组件的onChange方法来使用form修改value，点击保存的时候参数r拿不到最新值
   
### 🧐 解决方案
   目前是通过rowKey获取当前行的form值合并，但是这样做感觉不太好，希望能有更好的解决方案
    onSave: async (k, r) => {
          const row=form.getFieldValue(k)
          onTableSave({...r,...row})
    }
### 🚑 其他信息

希望editableProTable可以支持
1.renderFormItem和render通过属性展示同样的DOM，以checkBox为例
2.columns不同字段之间存在依赖关系的情况，希望能考虑完善一下相关API

谢谢~

**Comment by chenshuai2144** [comment]
```
 onSave?: (
    /** 行 id，一般是唯一id */
    key: RecordKey,
    /** 当前修改的行的值，只有 form 在内的会被设置 */
    record: T & { index?: number },
    /** 原始值，可以用于判断是否修改 */
    originRow: T & { index?: number },
    /** 新建一行的配置，一般无用 */
    newLineConfig?: NewLineConfig<T>,
  ) => Promise<any | void>;
```

试试这个方式

**Comment by Shenlu1** [comment]
> ```
>  onSave?: (
>     /** 行 id，一般是唯一id */
>     key: RecordKey,
>     /** 当前修改的行的值，只有 form 在内的会被设置 */
>     record: T & { index?: number },
>     /** 原始值，可以用于判断是否修改 */
>     originRow: T & { index?: number },
>     /** 新建一行的配置，一般无用 */
>     newLineConfig?: NewLineConfig<T>,
>   ) => Promise<any | void>;
> ```
> 
> 试试这个方式

就是onSave方法，record打印出来不是最新值，跟form获取的值不一致，也是在form里的字段

**Comment by chenshuai2144** [comment]
那不大可能呀，record 也是用form.getFieldValue 拿出来的，你来个重现吧

**Comment by chenshuai2144** [comment]
发布了新版本，试一下

**Comment by xiaomansjw** [comment]
> 那不大可能呀，record 也是用form.getFieldValue 拿出来的，你来个重现吧

record拿到的确实不是最新的值

**Comment by kgloveyou** [comment]
遇到同样的问题，"@ant-design/pro-table": "^2.56.8",

**Comment by Nemowxy** [comment]
+1

**Comment by Nemowxy** [comment]
第一次保存onSave可以拿到最新的值，编辑后再保存拿到的就不是最新的了

**Comment by siifan168** [comment]
为什么每次都拿不到新的值呢，每次onSave只能拿到初始化设置进去的值，再修改都没有用，点击编辑的时候原来的值也会清空看不见
![image](https://github.com/ant-design/pro-components/assets/81421749/6c23e802-2d18-459c-a379-75e7af415008)
