### ISSUE TITLE
🐛[BUG] 文字是不是写错了 还是就这样的

### ISSUE THREAD

**Issue by wu-xiaowei** [ant-design/pro-components#3197]
### 🐛 bug 描述

icon的文字错了吧....

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/29117317/125051354-71648100-e0d5-11eb-81b7-06577d4880fa.png)

**Comment by chenshuai2144** [comment]
写错了，感谢指出
