### ISSUE TITLE
🐛[BUG] ProTable的Form里设置fieldProps控制台报错

### ISSUE THREAD

**Issue by yaoguoba** [ant-design/pro-components#320]
### 🐛 bug 描述

相邻两个Column， fieldProps设置相同：
fieldProps: { mode: 'multiple', showArrow: true },
第一个报错，第二个不报错。

代码：
![image](https://user-images.githubusercontent.com/18393410/91292697-76745680-e7c9-11ea-91bd-7ef068c6333e.png)

显示效果：
![image](https://user-images.githubusercontent.com/18393410/91292834-a7ed2200-e7c9-11ea-98e7-8a526b13eaa2.png)

![image](https://user-images.githubusercontent.com/18393410/91292732-83914580-e7c9-11ea-822f-db037908e03f.png)

控制台报错：
devScripts.js:5836 Warning: React does not recognize the `showArrow` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `showarrow` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in input (created by Context.Consumer)
    in ClearableLabeledInput (created by Context.Consumer)
    in Input (created by ForwardRef(FieldText))
    in ForwardRef(FieldText) (created by ForwardRef(Field))
    in ForwardRef(Field) (created by Field)
    in Unknown
    in Unknown (created by Field)
    in div (created by FormItemInput)
    in div (created by FormItemInput)
    in div (created by Context.Consumer)
    in Col (created by FormItemInput)
    in FormItemInput (created by Field)
    in div (created by Context.Consumer)
    in Row (created by Field)
    in Field (created by WrapperField)
    in WrapperField (created by FormItem)
    in FormItem (created by ForwardRef)
    in ForwardRef (created by FieldWithContext)
    in FieldWithContext (created by FormSearch)
    in div (created by Context.Consumer)
    in Row (created by ResizeObserver)
    in ResizeObserver (created by BaseForm)
    in form (created by ForwardRef(Form))
    in ForwardRef(Form) (created by ForwardRef(InternalForm))
    in SizeContextProvider (created by ForwardRef(InternalForm))
    in ForwardRef(InternalForm) (created by BaseForm)
    in ConfigProviderWarp (created by BaseForm)
    in BaseForm (created by QueryFilter)
    in QueryFilter (created by FormSearch)
    in div (created by FormSearch)
    in FormSearch (created by ProTable)
    in div (created by ProTable)
    in LocaleProvider (created by Context.Consumer)
    in SizeContextProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (created by ProTable)
    in ProTable (created by ProviderWarp)
    in ErrorBoundary (created by ProviderWarp)
    in ConfigProviderWarp (created by ProviderWarp)
    in Provider (created by ProviderWarp)
    in ProviderWarp (at SearchTable/index.tsx:116)
    in SearchTable (at product/index.tsx:525)
    in div (created by PageContainer)
    in div (created by PageContainer)
    in div (created by GridContent)
    in div (created by GridContent)
    in GridContent (created by PageContainer)
    in div (created by PageContainer)
    in PageContainer (at product/index.tsx:524)
    in CompProduct (created by ConnectFunction)
    in ConnectFunction (created by LoadableComponent)
    in LoadableComponent (created by Context.Consumer)
    in Route (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in Route (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in Authorized (at BasicLayout.tsx:183)
    in main (created by Basic)
    in Basic (created by Context.Consumer)
    in Content (created by WrapContent)
    in ConfigProviderWarp (created by WrapContent)
    in WrapContent (created by BasicLayout)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Layout (created by BasicLayout)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Layout (created by BasicLayout)
    in div (created by BasicLayout)
    in Provider (created by BasicLayout)
    in BasicLayout (at BasicLayout.tsx:142)
    in BasicLayout (created by ConnectFunction)
    in ConnectFunction (created by LoadableComponent)
    in LoadableComponent (created by Context.Consumer)
    in Route (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in SecurityLayout (created by ConnectFunction)
    in ConnectFunction (created by LoadableComponent)
    in LoadableComponent (created by Context.Consumer)
    in Route (created by RouterComponent)
    in Switch (created by RouterComponent)
    in Router (created by RouterComponent)
    in RouterComponent
    in Provider (created by _DvaContainer)
    in _DvaContainer
    in Unknown
    in FormProvider (created by Context.Consumer)
    in LocaleProvider (created by Context.Consumer)
    in SizeContextProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (at locale.tsx:47)
    in _LocaleContainer
    in Unknown

### © 版本信息

- ProTable版本: 2.6.2

**Comment by chenshuai2144** [comment]
在 render 的外包包个` <></>` 试试，看不出来问题是什么

**Comment by yaoguoba** [comment]
> 在 render 的外包包个` <></>` 试试，看不出来问题是什么

不好用，把render删了都不好用。只要把第一个的showArrow配置删了，就好了。
等下一个版本再看吧

**Comment by chenshuai2144** [comment]
试了几次都无法复现，估计是因为你的版本问题，试试最新的2.6.4

**Comment by lm356536** [comment]
> 试了几次都无法复现，估计是因为你的版本问题，试试最新的2.6.4

目前 npm 上最新的事 2.6.3  版本的. 最新版本,今天能上吗? fieldProps里面设置value 和 onChange 还是没有效果.

**Comment by yaoguoba** [comment]
> > 试了几次都无法复现，估计是因为你的版本问题，试试最新的2.6.4
> 
> 目前 npm 上最新的事 2.6.3 版本的. 最新版本,今天能上吗? fieldProps里面设置value 和 onChange 还是没有效果.

是valueEnum的初始化问题，当undefined时就会报这个错，我觉得是不是应该加个判断？
