### ISSUE TITLE
🐛[BUG]使用menuItemRender ，菜单收起的时候，鼠标hover上去会有2个tooltip

### ISSUE THREAD

**Issue by leehomeok** [ant-design/pro-components#3201]
### 🐛 bug 描述
使用menuItemRender 渲染菜单项，菜单收起的时候，鼠标hover上去会有2个tooltip

### 📷 复现步骤

[](url)

### 💻 复现代码
```
 menuItemRender={(menuItemProps, defaultDom, props) => {
        //console.log(menuItemProps, defaultDom)
        // 目录
        if (menuItemProps.isUrl || !menuItemProps.path || location.pathname === menuItemProps.path) {
          return renderMenuItem(menuItemProps, !!menuItemProps.icon) //defaultDom
        } else {
          // 菜单
          return (
            <Link
              to={menuItemProps.path}
              onClick={() => {
                handleMenuClick(menuItemProps)
              }}
            >
              {renderMenuItem(menuItemProps, !!menuItemProps.icon)}
            </Link>
          )
        }
      }}

const renderMenuItem = (menu, hasIcon?: boolean) => {
    let menuName = format(menu)
    let icon = hasIcon || !!menu.icon ? renderImg(menu, hasIcon) : null
    return (
      <Menu.Item key={menu.key || menu.path} icon={icon} onClick={e => handleMenuClick(e, menu)}>
        {menuName}
      </Menu.Item>
    )
  }

```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![Snipaste_2021-07-09_20-10-59](https://user-images.githubusercontent.com/13464485/125076068-07a6a000-e0f2-11eb-8b7b-5fda6273a5ba.png)

**Comment by chenshuai2144** [comment]
renderMenu 的返回会使用mennItem 先包裹一下，自然会有两层，这里建议icon使用约定的方式，第一个dom是icon 第二个是文案。

**Comment by leehomeok** [comment]
> renderMenu 的返回会使用 menuItem 先包裹一下，自然会有两层，这里建议icon使用约定的方式，第一个dom是 icon 第二个是文案。
> 
> ```
>  menuItemRender={(menuItemProps, defaultDom) => {
>         if (menuItemProps.isUrl || menuItemProps.children) {
>           return defaultDom;
>         }
>         if (menuItemProps.path && location.pathname !== menuItemProps.path) {
>           return (
>             <Link to={menuItemProps.path} target={menuItemProps.target}>
>               {defaultDom}
>             </Link>
>           );
>         }
>         return defaultDom;
>       }}
> ```

icon 需要动态渲染，所以用了 Menu.Item
