### ISSUE TITLE
ProTable查询中，如何将自定义的参数放入查询条件？

### ISSUE THREAD

**Issue by YC725968** [ant-design/pro-components#3203]
### 🥰 需求描述
ProTable查询中，如何将自定义的参数放入查询条件？比如点击左侧的组织架构，查询该组织架构下的人员，并且带分页

**Comment by YC725968** [comment]
![image](https://user-images.githubusercontent.com/51156342/125152350-98c35880-e17e-11eb-940d-f0830283c8c4.png)

**Comment by chenshuai2144** [comment]
<html>
<body>


params | 用于 request 查询的额外参数，一旦变化会触发重新加载 | object | -
-- | -- | -- | --



</body>
</html>



request
request 是 ProTable 最重要的 API，request 会接收一个对象。对象中必须要有 data 和 success，如果需要手动分页 total 也是必需的。request 会接管 loading 的设置，同时在查询表单查询和 params 参数发生修改时重新执行。同时 查询表单的值和 params 参数也会带入。

https://procomponents.ant.design/components/table?current=1&pageSize=5
