### ISSUE TITLE
ModalForm 提交数据时触发，如果返回一个 true，关掉弹框并且重置表单失效

### ISSUE THREAD

**Issue by YC725968** [ant-design/pro-components#3204]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by YC725968** [comment]
ModalForm 提交数据时触发，如果返回一个 true，关掉弹框并且重置表单失效，返回了true，表单并没有重置

**Comment by YC725968** [comment]
问题已解决，不好意思！

**Comment by caidesen** [comment]
> 问题已解决，不好意思！

我也遇到了，请问是如何解决的呢？

**Comment by caidesen** [comment]
看了下源码，需要设置 destroyOnClose=true，建议文档上说明下

**Comment by chenshuai2144** [comment]
` if (modalProps?.destroyOnClose) formRef.current?.resetFields();`
