### ISSUE TITLE
🧐[问题] 在使用onPageChange跳转路由时报错

### ISSUE THREAD

**Issue by RedsMario** [ant-design/pro-components#3207]
### 🧐 问题描述
我使用ProLayout的onPageChange属性进行路由重定向时，发生了错误，React提示不能再已卸载的组件中更新状态。虽然能通过异步解决，但是我想知道这是什么问题？

### 💻 示例代码
        onPageChange={() => {
          const isLogin = false;
          const { location } = props;
          // 如果没有登录，重定向到 login
          if (!isLogin && location.pathname !== "/login") {
            // 报错： 无法在已卸载的组件中执行状态更新
            props.history.push("/login");
          }
        }}

            // 不报错
            setTimeout(() => {
              props.history.push("/login");
            }, 0);
### 🚑 其他信息

代码链接： https://codesandbox.io/s/jichushiyong-forked-5zrck?file=/Layout.tsx

**Comment by chenshuai2144** [comment]
```
   // 不报错
        setTimeout(() => {
          props.history.push("/login");
        }, 0);
```

暂时只能这样了，需要在plugin 层面支持以下，不过现在没有计划
