### ISSUE TITLE
🐛[BUG] ProList编辑后,onSave无法获取更新后的值

### ISSUE THREAD

**Issue by dlspacezero** [ant-design/pro-components#3209]
### 🐛 bug 描述

ProList行内表单编辑后保存，在onSave中无法获取到更新后的值。

### 🏞 期望结果

能够正常获取更新后的值

### 💻 复现代码

onSave: (key, record, originRow) => {
        console.log(key, record, originRow, 'data');
        return true;
      },

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by rdmclin2** [comment]
@chenshuai2144 看一下这个问题，有两个同学反馈了

**Comment by dlspacezero** [comment]
@chenshuai2144 https://codesandbox.io/s/bianjiliebiao-forked-ucyvc?file=/App.tsx  麻烦大佬看看

**Comment by lhzbxx** [comment]
@chenshuai2144 什么时候发新版本解决一下这个问题啊？

**Comment by zspishere** [comment]
Hi @lhzbxx @dlspacezero ，基于[Prolist编辑列表Demo](https://procomponents.ant.design/components/list/#%E7%BC%96%E8%BE%91%E5%88%97%E8%A1%A8)的实现，编辑后，onSave`可以`获取更新后的值。（注意是`async`）

```
      editable={{
        onSave: async (key, record, originRow) => {
          console.log(key, record, originRow);
          return true;
        },
      }}
```

不确定是Bug已修改，还是楼主没有`async`的原因。希望有帮助。

**Comment by dlspacezero** [comment]
> Hi @lhzbxx @dlspacezero ，基于[Prolist编辑列表Demo](https://procomponents.ant.design/components/list/#%E7%BC%96%E8%BE%91%E5%88%97%E8%A1%A8)的实现，编辑后，onSave`可以`获取更新后的值。（注意是`async`）
> 
> ```
>       editable={{
>         onSave: async (key, record, originRow) => {
>           console.log(key, record, originRow);
>           return true;
>         },
>       }}
> ```
> 
> 不确定是Bug已修改，还是楼主没有`async`的原因。希望有帮助。

是已经修复了
