### ISSUE TITLE
👑 [需求]在ProTable中可以同时支持FormRef和ActionRef吗？

### ISSUE THREAD

**Issue by YC725968** [ant-design/pro-components#3211]
### 🥰 需求描述
在ProTable中可以同时支持FormRef和ActionRef，因自定义了查询，在添加数据后需要刷新表格，但使用formRef.submit页面会跳转到首页，不在当前页

**Comment by chenshuai2144** [comment]
可以的，demo 中就有的

**Comment by YC725968** [comment]
谢谢啊，找到了，写错了名字。还有一个问题，FormItem中对于{job:{id:1}}这种嵌套的的字典如何引入？

**Comment by YC725968** [comment]
再次感谢大佬，没好好看文档，找到解决办法了，谢谢谢谢，大佬厉害！
