### ISSUE TITLE
StepForm没有stepProps属性么？

### ISSUE THREAD

**Issue by gs600981** [ant-design/pro-components#3214]
### 🧐 问题描述

StepsForm组件有stepsProps属性，但是其子组件StepForm确没有stepProps属性，那么我想更改StepForm的title和subTitle应该怎么办？

**Comment by chenshuai2144** [comment]
StepForm 只支持 title 的， 你要自定义的话需要用 stepsRender 来实现了。有兴趣可以来个 pr，支持一下 stepProps

**Comment by gs600981** [comment]
我才接触react1个月，有心无力，只能改用antd的step了。感谢所有开发者提供这么方便的组件。

**Comment by chenshuai2144** [comment]
想法挺好的， 可以让别人支持一下
