### ISSUE TITLE
ProTable列设置ellipsis后，首次渲染会有一闪而逝的全字段到省略字段🐛[BUG]

### ISSUE THREAD

**Issue by gitlwz** [ant-design/pro-components#3216]
### 🐛 bug 描述

ProTable列设置ellipsis后，首次渲染会有一闪而逝的全字段到省略字段的一个过程，虽然很快但是确实会出现，当数据越多时出现的越明显

### 📷 复现步骤

https://codesandbox.io/s/chaxunbiaoge-forked-j3ziv?file=/App.tsx

点击查询不会出现，一定要刷新页面，第一次渲染会出现，实际项目我做了页面缓存，切回来同样会出现

### 🏞 期望结果

不出现一闪而逝的效果

### 💻 复现代码

https://codesandbox.io/s/chaxunbiaoge-forked-j3ziv?file=/App.tsx

### © 版本信息

最新版本

**Comment by chenshuai2144** [comment]
useEffect 总是慢一点的，这个无解。你可以去 antd 那里试试
