### ISSUE TITLE
🧐[问题]  ProFormSelect 开启showSearch 后，设置默认值显示value

### ISSUE THREAD

**Issue by wangzhoubin** [ant-design/pro-components#3217]
### 🧐 问题描述

ProFormSelect 开启showSearch 后，设置默认值显示value

### 💻 示例代码
`

 <ProFormSelect
          key={index}
          name={item.name}
          label={item.label}
          showSearch
          initialValue="asda"
          request={async (params) => {
              // 设置了默认值，初始化的时候会发起请求，但是 params,keyWords 是undefined
            console.log(params);
            if (params.keyWords) {
              const {data} = await searchRelProduct(params);
              return data;
            }
            return [];
          }}
          rules={[{required: true}]}
        />

`

### 🚑 其他信息
![FN{UX6EUR~{6FZMR9HMHZB6](https://user-images.githubusercontent.com/86712634/125387924-344c0780-e3d1-11eb-9403-dae42c8187d7.png)

**Comment by chenshuai2144** [comment]
showSearch 打开之后会自动打开 labelInValue，你这里可能要适配一下了

**Comment by wangzhoubin** [comment]
已经处理了，这样的，如果有默认值的时候，在初始化时，必须保证返回的列表中包含 默认值的对应项。也可以再初始化时手动检查select是否有默认值，如果有就在request 中手动处理一下。
