### ISSUE TITLE
表头搜索输入框必填时，触发会出现个小红框

### ISSUE THREAD

**Issue by Davide-pg** [ant-design/pro-components#3219]
### 🐛 bug 描述
当设置搜索项为必填时，点击搜索时会触发必填样式，但是必填框中会出现小红框

### 🏞 期望结果

不希望会出现小红框

### 💻 复现代码

```
const colums=[{
      title: 'id',
      dataIndex: 'xxx',
      formItemProps: {
        rules: [
          {
            required: true,
            message: '此项为必填项',
          },
        ],
      },
    }]

<ProTable
        headerTitle="应用列表"
        actionRef={actionRef}
        form={{
          ignoreRules: false,
        }}
       colums={colums}
       ...
/>
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/61934046/125406362-56eb1a00-e3eb-11eb-97cc-51751dccc3de.png)

**Comment by DerrickTel** [comment]
有demo可以看看吗？
我看官网的好像没啥毛病。
https://procomponents.ant.design/components/table#%E5%BF%85%E5%A1%AB%E7%9A%84%E6%9F%A5%E8%AF%A2%E8%A1%A8%E5%8D%95

**Comment by chenshuai2144** [comment]
我的电脑上复现了，看起来是个样式生效层级太高的问题

**Comment by codedart2018** [comment]
我的也出现了　这个是ant的问题。

**Comment by codedart2018** [comment]
> 有demo可以看看吗？
> 我看官网的好像没啥毛病。
> https://procomponents.ant.design/components/table#%E5%BF%85%E5%A1%AB%E7%9A%84%E6%9F%A5%E8%AF%A2%E8%A1%A8%E5%8D%95

ant 官网的我也看了　本身就有问题

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/pro-components/issues/3265
