### ISSUE TITLE
🧐[问题]ProTable中更改查询条件后点击刷新，表单提交的时候查询条件是更改查询条件之前的参数

### ISSUE THREAD

**Issue by TengChongChong** [ant-design/pro-components#322]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/11783658/91319765-548dca80-e7ef-11ea-9208-bc8dae97f649.png)

### 🚑 其他信息
pro-table 2.6.1

**Comment by chenshuai2144** [comment]
不点查询按钮，数据就不会被同步的。
你你可以通过 formRef 来人工触发 submit

**Comment by TengChongChong** [comment]
好的，谢谢
