### ISSUE TITLE
🐛[BUG]umi的msfu模式报错，提示moment.isMoment is not a function

### ISSUE THREAD

**Issue by victorWuxz** [ant-design/pro-components#3220]
### 📷 复现步骤

yarn create umi
配置umi的msfu模式
yarn add
yarn add @ant-design/proform
yarn start

### 🏞 期望结果

正常启动

### 💻 复现代码

无

### © 版本信息

- ProComponents 版本: form：1.31.2
- umi 版本 3.5.8
- 浏览器环境 chrome 9.1
- 开发环境 macos

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/36194121/125422247-323de831-5c6d-43b6-a52f-f43b6d3104ae.png)

**Comment by victorWuxz** [comment]
https://github.com/victorWuxz/umi-bug
@chenshuai2144

**Comment by victorWuxz** [comment]
只要给ProForm传递initialValues就会必现

**Comment by victorWuxz** [comment]
> Hello @victorWuxz. Please provide a online reproduction by forking this link https://codesandbox.io/ or a minimal GitHub repository.
> 
> 你好 @victorWuxz, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

**Comment by victorWuxz** [comment]
误操作关闭了

**Comment by victorWuxz** [comment]
> 只要给ProForm传递initialValues就会必现

**Comment by victorWuxz** [comment]
> Hello @victorWuxz. Please provide a online reproduction by forking this link https://codesandbox.io/ or a minimal GitHub repository.
> 
> 你好 @victorWuxz, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

最小化的 GitHub 仓库:
https://github.com/victorWuxz/umi-bug

**Comment by chenshuai2144** [comment]
还不支持替换为dayjs，要用dayjs 先关掉mfsu吧
