### ISSUE TITLE
pro-table组件和react-activation一起使用的时候显示有问题 🐛[BUG]

### ISSUE THREAD

**Issue by 767746649zyy** [ant-design/pro-components#3223]
ant-design/pro-table组件外使用KeepAlive，从缓存读取的pro-table时，里面的数据样式发生改变，里面的“...”应该显示完整数据，pro-table的column中没有设置ellipsis属性的字段，则没有这个问题，求解决方案
正确情况下使这样的
![image](https://user-images.githubusercontent.com/23164065/125434795-284fec14-a15f-4873-8325-02e4aa9ffa0f.png)

详细问题查看https://github.com/CJY0208/react-activation/issues/129

**Comment by chenshuai2144** [comment]
估计是 css 的问题，你要不自定义一把，table 没有重新渲染不会重新计算 ellipsis

**Comment by biggbb777** [comment]
@767746649zyy antd更新到最新版问题解决
