### ISSUE TITLE
🐛[BUG]ProTable组件设置ellipsis会导致移动端样式错乱

### ISSUE THREAD

**Issue by JinShuohang** [ant-design/pro-components#3228]
加了ellipsis:
![image](https://user-images.githubusercontent.com/49704308/125550928-b098a61d-8be4-4655-b829-69cb8c6b97a6.png)
![image](https://user-images.githubusercontent.com/49704308/125550931-6f4ad6ab-62cf-4609-a27e-d7d60ae3b71a.png)
不加:
![image](https://user-images.githubusercontent.com/49704308/125550948-db9ad5bd-6ee4-4b89-bd3b-819ec1c820d0.png)

**Comment by Ranylx** [comment]
ellipsis老问题了
