### ISSUE TITLE
🐛[BUG]升级最新版本后，ProFormText加hidden属性，initialValues无法赋值

### ISSUE THREAD

**Issue by dongtao0725** [ant-design/pro-components#3229]
### 🐛 bug 描述

🐛[BUG]升级最新版本后，ProFormText加hidden属性，initialValues无法赋值
<ProFormText width="md" name="id" label="id" hidden fieldProps={{ disabled: true}} />

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by dongtao0725** [comment]
<ProForm initialValues={values}>
           <ProForm.Group>
                    <ProFormText width="md" name="id" label="id" fieldProps={{ disabled: true}} />
           </ProForm.Group>
        </ProForm>

![image](https://user-images.githubusercontent.com/30116184/125572625-9dedd549-1354-447e-8a18-228d2875d881.png)
![image](https://user-images.githubusercontent.com/30116184/125572680-788e2551-1c67-4067-84a9-546fc736918c.png)

加入hidden属性后<ProFormText width="md" name="id" label="id" hidden fieldProps={{ disabled: true}} />
![image](https://user-images.githubusercontent.com/30116184/125573180-b121c5ef-822a-40a6-8a57-192cd7af8d74.png)
id初始值无法赋值value

将<ProFormText width="md" name="id" label="id" fieldProps={{ disabled: true}} />移除<ProForm.Group>后赋值正常2
![image](https://user-images.githubusercontent.com/30116184/125573392-be54d2c5-027e-4074-a809-f0867eab02c2.png)

**Comment by chenshuai2144** [comment]
ProForm.Group 对于hidden 的标签直接不渲染，你要是单纯的想隐藏可以配置 style ,  `display:none`

但是会有 padding 的问题

**Comment by whaty** [comment]
> 
之前是可以渲染的，更新到新版本不行了，导致所有项目更新接口失败，因为id设定的hidden，好坑啊

**Comment by chenshuai2144** [comment]
你用display:none 把

**Comment by codedart2018** [comment]
> 你用display:none 把

这明显不合理呀　我们也是很多id hidden 如果是这样好坑人啊

**Comment by moluzhui** [comment]
> 你用display:none 把

`display:none`似乎并没有生效
```
// style.less
.notshow{
  display: none;
}
```
```
// modal.tsx
<ProFormText
            className={styles.notshow}
            name="id"
            label="id"
            placeholder="请输入"
          />
```

**Comment by moluzhui** [comment]
> > 你用display:none 把
> 
> `display:none`似乎并没有生效
> 
> ```
> // style.less
> .notshow{
>   display: none;
> }
> ```
> 
> ```
> // modal.tsx
> <ProFormText
>             className={styles.notshow}
>             name="id"
>             label="id"
>             placeholder="请输入"
>           />
> ```

v5好像支持hidden设置
```
<ProFormText
            hidden={true}
            name="id"
            label="id"
            placeholder="请输入"
          />
```
