### ISSUE TITLE
🧐[问题]ProTable 字段过多，导致屏幕分别率变小的时候，table被撑爆

### ISSUE THREAD

**Issue by aoyinke** [ant-design/pro-components#323]
### 🧐 问题描述
ProTable 字段过多，一共需要展现出12个字段，导致屏幕分别率变小的时候，table被撑爆
请问有啥优化方案吗？

### 💻 示例代码
columns
[
    {
      title: '开始时间',
      dataIndex: 'createFrom',
      valueType: 'dateTime',
      hideInTable: true,
    },
    {
      title: '结束时间',
      dataIndex: 'createTo',
      valueType: 'dateTime',
      hideInTable: true,
    },
    {
      title: '名称',
      dataIndex: 'name',
      ellipsis: true,
      width: '7%',
      formItemProps: {
        responsive: ['md']
      },
    },
    {
      title: '内部Id',
      dataIndex: 'insideId',
      ellipsis: true,
      width: '7%',
      formItemProps: {
        responsive: ['md']
      },
    },
    {
      title: '外部Id',
      dataIndex: 'outsideId',
      ellipsis: true,
      width: '7%',
      formItemProps: {
        responsive: ['md']
      },
    },
    {
      title: 'imsi',
      dataIndex: 'imsi',
      ellipsis: true,
      width: '7%',
      formItemProps: {
        responsive: ['md']
      },
    },
    {
      title: '设备机号',
      dataIndex: 'macId',
      ellipsis: true,
      width: '4%',
      formItemProps: {
        responsive: ['md']
      },
    },
    {
      title: '打印机号',
      dataIndex: 'printMacId',
      ellipsis: true,
      width: '4%',
      formItemProps: {
        responsive: ['md']
      },
    },
    {
      title: '型号',
      dataIndex: 'model',
      ellipsis: true,
      width: '7%',
      hideInSearch: true,
      formItemProps: {
        responsive: ['md']
      },
    },
    {
      title: '型号名',
      dataIndex: 'modelName',
      ellipsis: true,
      hideInSearch: true,
      width: '7%',
      formItemProps: {
        responsive: ['md']
      },
    },
    {
      title: '类型名称',
      dataIndex: 'typeName',
      ellipsis: true,
      width: '7%',
      hideInSearch: true,
      formItemProps: {
        responsive: ['md']
      },
    },
    {
      title: '状态',
      dataIndex: 'status',
      ellipsis: true,
      valueEnum: equipValueEnum,
      formItemProps: {
        responsive: ['md']
      },
      width: '7%',
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      width: '7%',
      ellipsis: true,
      hideInSearch: true,
      formItemProps: {
        responsive: ['md']
      },
    },
    {
      title: '操作',
      width: '7%',
      valueType: 'option',
      render: options
    },
  ];

### 🚑 其他信息

![20200827101156](https://user-images.githubusercontent.com/50656241/91375760-170c5a00-e84e-11ea-8faa-c29e2d25dfcf.png)
![20200827101218](https://user-images.githubusercontent.com/50656241/91375778-1d9ad180-e84e-11ea-92ab-f47d68903339.png)

**Comment by chenshuai2144** [comment]
出滚动条

**Comment by aoyinke** [comment]
好的，谢谢！
