### ISSUE TITLE
🐛[BUG]Pro组件中的上传组件上传成功后会触发两次onchange

### ISSUE THREAD

**Issue by shanzhaozhen** [ant-design/pro-components#3231]
### 🐛 bug 描述

Pro组件中的上传组件上传成功后会触发两次onchange

### 📷 复现步骤
使用ProFormUploadDragger和Dragger组件做对比

### 🏞 期望结果
使用ProFormUploadDragger组件完成上传后只触发一次

### 💻 复现代码

```
<ProFormUploadDragger
  fieldProps={{
    onChange: (info) => {
      const { status } = info.file;
      if (status === 'done') {
        message.success(`${info.file.name} file uploaded successfully.`);
      } else if (status === 'error') {
        message.error(`${info.file.name} file upload failed.`);
      }
    }
  }}
/>

<Dragger
  onChange={(info) => {
    const { status } = info.file;
    if (status === 'done') {
      message.success(`${info.file.name} file uploaded successfully.`);
    } else if (status === 'error') {
      message.error(`${info.file.name} file upload failed.`);
    }
  }}
/>
```

### 🚑 其他信息
第一张图为antd Pro组件上传后的状态，第二张图是antd组件上传后的状态
![image](https://user-images.githubusercontent.com/29800728/125571543-452bc454-512b-4e13-b110-60bbd554177f.png)
![image](https://user-images.githubusercontent.com/29800728/125571573-79d964b9-bcb7-446a-b7df-dcef0a898743.png)

**Comment by yaobiao131** [comment]
同样出现

**Comment by HQDragon** [comment]
11月11日仍然会出现，而且为什么移除了bug label啊

**Comment by yaobiao131** [comment]
> 11月11日仍然会出现，而且为什么移除了bug label啊

onChange放在fieldProps中就好了

**Comment by HQDragon** [comment]
@chenshuai2144 昨晚有人给我发邮件，说是将onchange写在fieldprops内就不会有这个bug，我做完测试了，确实可以解决双重触发的问题。可能需要更新文档或者改进直接写onchange的触发

**Comment by shanzhaozhen** [comment]
> @chenshuai2144 昨晚有人给我发邮件，说是将onchange写在fieldprops内就不会有这个bug，我做完测试了，确实可以解决双重触发的问题。可能需要更新文档或者改进直接写onchange的触发

那可能是了，那时候解决不了我重新用非pro的封装了一次就能正常用了

**Comment by juneszh** [comment]
@chenshuai2144 这触发两次onChange问题在最新的版本又复现了，而且onChange放在fieldprops里也不行，会报错

> <ProFormUploadDragger
>     name={schema.dataIndex}
>     fieldProps={{
>         name: 'file',
>         listType: 'picture',
>         action: global.adminPath + '/upload',
>         maxCount: schema.fieldProps.multiple ? 0 : 1,
>         onChange: ({ file, fileList }) => {
>             if (file.status === 'done') {
>                 console.log(file, fileList);
>             } else if (file.status === 'error') {
>                 message.error(`${file.name} file upload failed.`);
>             }
>         },
>         ...schema.fieldProps,
>     }}
> />

![图片](https://user-images.githubusercontent.com/2436252/173051445-1fcae019-d52a-4c40-a836-b58c3b020cdd.png)

**Comment by HQDragon** [comment]
![image](https://user-images.githubusercontent.com/15418465/173261758-fd165a66-3bfc-4a84-be90-6a93c176947a.png)
用自己的代码试了一下，没有复现，而且你这个有typeerror。
请通过以下情况测试一下：
1、更新proform到1.69.3，看是否已消除bug
2、检查自己的react语法，是否是笔误

**Comment by juneszh** [comment]
> ![image](https://user-images.githubusercontent.com/15418465/173261758-fd165a66-3bfc-4a84-be90-6a93c176947a.png) ![image](https://user-images.githubusercontent.com/15418465/173261891-30d29d5f-5038-4979-a548-f923521b7aee.png) ![image](https://user-images.githubusercontent.com/15418465/173262323-f6d54aaa-dc61-4b7e-9975-7abcba76304c.png)
> 
> 用自己的代码试了一下fieldProps模式，没有复现，每次触发事件仅log一次，这个typeerror你得自己检查下。直接写onchange版本没有源码，暂不测试 请通过以下情况测试一下： 1、更新proform到1.69.3，看是否已消除bug 2、检查自己的react语法，是否是笔误

谢谢你的测试，关于你提出的两个可能性
1. 已尝试过npm update，没有得到解决
2. 只是将onChange放在不同位置，应该不会是语法问题，而且build也没有错误。

因为我是在schemaForm的renderFormItem里使用的ProFormUploadDragger，与直接使用ProFormUploadDragger可能存在差别，怀疑这是诱发点，稍后我测试不在schemaForm里使用是否就没问题。

**Comment by juneszh** [comment]
@HQDragon 不幸地，我将代码精简到只剩ProFormUploadDragger仍然会复现onChange两次触发

但我注意到我们的组件版本有些许不一样：
![图片](https://user-images.githubusercontent.com/2436252/173279451-593e6025-a3e5-4158-bc1c-2d653cb9ffaa.png)

就是antd我这边用的是最新的4.21.0，然后我尝试降到antd@4.20.0，问题仍然复现，最后尝试antd@4.19.5，但提示：

`npm ERR! Could not resolve dependency:`
`npm ERR! peer antd@">=4.20.0" from @ant-design/pro-form@1.69.3`

可见pro-form@1.69.3不能兼容antd@4.20.0以下版本，你是如何做到的？

**Comment by HQDragon** [comment]
![image](https://user-images.githubusercontent.com/15418465/173979908-72f2cb47-ad45-4370-9f94-09f3419a2093.png)
![image](https://user-images.githubusercontent.com/15418465/173979942-8a26d04f-0109-4703-8f63-59c043aa32a6.png)
emmm，要不你去掉@ant-desian/pro-form这个依赖，因为现在pro-component已经包含了其它pro组件了，然后用yarn管理依赖？我是按照官方推荐的tyarn做的管理。之前用pnpm管理，很多peer dep不会安装，我就放弃了pnpm。
另外，antd版本升级并没有造成重复触发事件的问题呀。

**Comment by HQDragon** [comment]
@juneszh @chenshuai2144 不过，今天测试了直接onchange的方法写事件，确实发生了两次触发，这个bug又回来了= =！
![image](https://user-images.githubusercontent.com/15418465/173980653-70451c10-e58c-4709-9657-847b82ed9bf4.png)
![image](https://user-images.githubusercontent.com/15418465/173980702-ab1dd087-c1c1-44c0-a288-c2640a8c70b1.png)

**Comment by juneszh** [comment]
复现了就好XD

我这边也找到了onChange报错的原因，是schemaForm的renderFormItem会自动赋值顶级标签props，导致的冲突，需要外层加个包裹就解决：
<><ProFormUploadDragger fieldProps={...schema.fieldProps} /></>

**Comment by HQDragon** [comment]
> 

那是不是意味着，你使用fieldProps模式也可以避免重复触发的问题，其实从去年发现这个问题起，我所有的pro组件的状态事件都写在这个里面了，之前有一位貌似是开发组大佬的任务给我发邮件，建议我这么做。

**Comment by juneszh** [comment]
> > 
> 
> 那是不是意味着，你使用fieldProps模式也可以避免重复触发的问题，其实从去年发现这个问题起，我所有的pro组件的状态事件都写在这个里面了，之前有一位貌似是开发组大佬的任务给我发邮件，建议我这么做。

是的，现在已经可以使用fieldProps的onChange先解决，剩下就等大佬慢慢修复bug了

**Comment by aspirantzhang** [comment]
还真有这个问题。。用 fieldProps 的 onChange 就没毛病。
