### ISSUE TITLE
ProForm中使用自定义组件样式问题

### ISSUE THREAD

**Issue by zhouchunguang2020** [ant-design/pro-components#3234]
在ProForm中，使用自定义组件，怎么实现 和 ProFormText等系统组件类似的样式

**Comment by zhouchunguang2020** [comment]
我说的这种是在QueryFilter中，使用自定义组件，例如：

`<Form.Item className="test" label="测试一下" name="aaa">
       <Input />
  </Form.Item>`

这时候的label文字和系统定义的ProFormText、ProFormSelect的label样式对应的不整齐。
系统单行展示表单列数小于等于2时，默认布局为vertical，此时
![image](https://user-images.githubusercontent.com/68039784/125717706-e64b9b5b-81a5-497b-9eac-2b76a0ae4710.png)
红框标注的属性是没有的，由文档得知这个容器宽度断点为701px。所以解决方法为
![image](https://user-images.githubusercontent.com/68039784/125718253-44cb6dc4-f842-49ae-b071-f22af8be59c9.png)
大家如果有更好的方法，欢迎发言。

**Comment by zhouchunguang2020** [comment]
自定义的组件在QueryFilter中，label与ProFormText样式对应不上

**Comment by chenshuai2144** [comment]
要用 ProForm.Item，不过要自定义的确有点难。现在还没有开相应的口子

**Comment by zhouchunguang2020** [comment]
针对我提出的问题，通过F12看一下ProForm中的label宽度，会发现屏幕大小变化，其宽保持不变，所以把自己定义的label设置为div，宽度保持一致，问题解决。
