### ISSUE TITLE
👑 [需求] 希望文档可以补充Columns 列定义中sorter字段的解析

### ISSUE THREAD

**Issue by shanzhaozhen** [ant-design/pro-components#3235]
### 🥰 需求描述

希望文档可以补充Columns 列定义中sorter字段的解析，之前以为sorter只能是boolean类型，忽略了可以设置成字符串替换dataIndex作为排序字段，今天为了解决这个问题所以看了一下源码才发现可以这么用。

### 🧐 解决方案

增加sorter解析

属性 | 描述 | 类型 | 默认值
-- | -- | -- | --
sorter| 与 antd 中基本相同，但是支持通过传入字符串更改排序字段的关键字 | - | -

不太会表达....

**Comment by DerrickTel** [comment]
https://ant.design/components/table-cn/#Column
antd里面定义了，这里就不重复解释了。

**Comment by swuecho** [comment]
能举个例子么。好像用法就这两种？` sorter: boolean |  (a, b) => boolean`

**Comment by chenshuai2144** [comment]
https://ant-design.gitee.io/components/table-cn/#components-table-demo-custom-filter-panel

看这里
