### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by QWYZ** [ant-design/pro-components#3243]
### 🐛 bug 描述

用 ProTable 展示的树形数据无法正常展开收起，(Table可以)

### 🚑 其他信息

展开状态截图
![image](https://user-images.githubusercontent.com/61998381/125756351-b998a67f-7ae9-4c82-9765-2e61616991c2.png)

**Comment by KellenHe** [comment]
我也出现这个问题了，发现是valueEnum如果是null就无法展开

**Comment by vjzning** [comment]
我也这个问题，怎么解决的？

**Comment by vjzning** [comment]
发现是在DragSortTable 里面 用展开就 收不起来了

**Comment by wuranxu** [comment]
> 发现是在DragSortTable 里面 用展开就 收不起来了

是的， 你最后解决了不？
