### ISSUE TITLE
🧐[问题]请教一下 EditableProTable 添加一行时怎么把上一行的数据带入到新的一行中

### ISSUE THREAD

**Issue by weiqr** [ant-design/pro-components#3245]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/87416134/125759524-380aedde-91f2-48b3-8e40-f3411f83fdc2.png)
点击添加一行后，怎么把紧邻的上一行的数据信息带入到新的一行中呢？
我在recordCreatorProps 配置项中把record属性设置好的默认值，在点击添加一行的时候把上一行的值重新赋值给record，但是渲染出来的新一行还是之前的默认值，再次添加一行的时候才会上次赋的值给代入，效果相当于“延时”了一次，该怎么解决呢？

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/87416134/125762077-e34863ea-0bfd-4d4b-aabd-420ef87ceed2.png)

**Comment by chenshuai2144** [comment]
你存一下dataSource，然后 
```tsx
recordCreatorProps = {
  newRecordType: "dataSource",
  position: "top",
  record: () => dataSource[dataSource.length-1],
};

```
