### ISSUE TITLE
🐛[BUG]使用SettingDrawer后，LayoutSettings都带进链接里了

### ISSUE THREAD

**Issue by lufinka** [ant-design/pro-components#3248]
### 🐛 bug 描述

"umi-plugin-setting-drawer": "^1.0.3"
安装后所有页面链接会自动加上config/defaultSettings.ts中LayoutSettings的配置项：http://localhost:8000/antdpro/manage/user/info?navTheme=light&layout=top&fixSiderbar=true&title=%E6%99%BA%E8%83%BD%E5%AE%A1%E6%A0%B8&primaryColor=%231890ff&colorWeak=false&pwa=false&logo=https%3A%2F%2Fgw.alipayobjects.com%2Fzos%2Frmsportal%2FKDpgvguMpGfqaHPjicRK.svg

### 🏞 期望结果

期望不粗线在url中，不影响路由传参

### © 版本信息

- ProComponents 版本: pro-layout": "6.21.1",
- umi 版本："3.5.10",
- 浏览器环境：chrome最新版
- 开发环境 [win10]

**Comment by chenshuai2144** [comment]
<html>
<body>
<h3 id="settingdrawer" style="box-sizing: border-box; margin: 42px 0px 18px; color: rgb(69, 77, 100); font-weight: 500; line-height: 1.40625; font-size: 20px; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">SettingDrawer</h3><blockquote style="box-sizing: border-box; margin: 16px 0px; padding: 0px 24px; color: rgba(69, 77, 100, 0.7); border-left: 4px solid rgb(235, 237, 241); overflow: hidden; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin: 16px 0px;">SettingDrawer 提供了一个图形界面来设置 layout 的配置。不建议在正式环境中使用。</p></blockquote>

参数 | 说明 | 类型 | 默认值
-- | -- | -- | --
settings | layout 的设置 | Settings \| Settings | -
onSettingChange | Settings 发生更改事件 | (settings: [Settings](#Settings) ) => void | -
hideHintAlert | 删除下方的提示信息 | boolean | -
disableUrlParams | 禁止同步设置到查询参数 | boolean | false


</body>
</html>

**Comment by lufinka** [comment]
@chenshuai2144 antd pro V5中安装插件就直接显示了SettingDrawer，大佬哪里设置disableUrlParams这个参数？

**Comment by chenshuai2144** [comment]
在initialValues.setting 里设置一下

**Comment by lufinka** [comment]
> 在initialValues.setting 里设置一下

没有找到配置入口，请问在哪里设置？

**Comment by chenshuai2144** [comment]
`src/app.tsx`
```
export async function getInitialState(): Promise<{
  settings?: Partial<LayoutSettings>;
  currentUser?: API.CurrentUser;
  fetchUserInfo?: () => Promise<API.CurrentUser | undefined>;
}> 
  return {
    fetchUserInfo,
    settings: { disableUrlParams },
  };
}
```

**Comment by lufinka** [comment]
> `src/app.tsx`
> 
> ```
> export async function getInitialState(): Promise<{
>   settings?: Partial<LayoutSettings>;
>   currentUser?: API.CurrentUser;
>   fetchUserInfo?: () => Promise<API.CurrentUser | undefined>;
> }> 
>   return {
>     fetchUserInfo,
>     settings: { disableUrlParams },
>   };
> }
> ```

settings与disableUrlParams是平级关系，不能在settings中设置呀？

**Comment by chenshuai2144** [comment]
`  settings: { disableUrlParams },
`
不是平级的
