### ISSUE TITLE
🐛[BUG] pro-table 日期区间未更新

### ISSUE THREAD

**Issue by huhm** [ant-design/pro-components#325]
### 🐛 bug 描述

pro-table组件，使用RangePicker组件第一次设置时间区间点查询，可以查询。
第二次设置时间区间，点击查询没有触发request，此时点击
@ant-design/pro-table 2.5.15版本有问题
@ant-design/pro-table 2.5.8版本正常

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- @ant-design/pro-table [2.5.15]
- umi 版本[3.2.14]
- 浏览器环境[Chrome]
- 开发环境 [e.g. mac OS]

**Comment by huhm** [comment]
附异常package-lock文件
[package-lock.json.txt](https://github.com/ant-design/pro-components/files/5133926/package-lock.json.txt)

**Comment by huhm** [comment]
已经找到原因是新版本修改了pro-table组件的request方法的param返回中的日期控件的值导致的。
由于代码处理的是Moment的值，新版改成了string ,request方法执行异常会导致按钮点击没有反应

**Comment by huhm** [comment]
这种不兼容的修改有没有地方查看？

**Comment by chenshuai2144** [comment]
没听懂？有重现吗？
