### ISSUE TITLE
🐛[BUG]ProTable valueType:'select' 不触发查询

### ISSUE THREAD

**Issue by wangyongsong** [ant-design/pro-components#3252]
### 🐛 bug 描述

valueType:'select' 选中下拉项，点击查询，不会触发table的request

### 💻 复现代码

```tsx
    {
      title: '名称',
      dataIndex: 'name',
      valueType: 'select',
      fieldProps: {
        options: [ { value: 1, label: 1}],
      }
      // renderFormItem: () => <Select options={[ { value: 1, label: 1}]} />
    },
```

### © 版本信息
- "@ant-design/pro-form": "1.19.1",
-  "@ant-design/pro-table": "2.30.8",

**Comment by wangyongsong** [comment]
补充： 以前的解决办法使用valueEnum，但是会有一种风险，如果valueEnum的length > 1000，就会导致页面卡死

**Comment by chenshuai2144** [comment]
只有 submit 才会触发查询，你可以用onSelect 然后触发` formRef.current.submit()`

**Comment by wangyongsong** [comment]
> 只有 submit 才会触发查询，你可以用 onSelect 然后触发` formRef.current.submit()`

不对吧，我就是用submit触发的

```tsx
<ProTable
        headerTitle=""
        debounceTime={0}
        rowKey="id"
        scroll={{ x: 1000 }}
        actionRef={actionRef}
        beforeSearchSubmit={(params: any) => omitBy({ ...params }, isEmpty)}
        search={{
          labelWidth: 120,
          optionRender: ({ searchText, resetText }, { form }) => [
            access.store_exportStore && (
              <Button key="out" onClick={() => exportFn()}>
                导出
              </Button>
            ),
            <Button
              key="rest"
              onClick={() => {
                form?.resetFields();
                form?.submit();
              }}
            >
              {resetText}
            </Button>,
            <Button
              key="search"
              type="primary"
              onClick={() => {
                form?.submit();
              }}
            >
              {searchText}
            </Button>,
          ],
        }}
        toolBarRender={() => [
          <Button type="primary" key="add" onClick={() => addAgencyRef.current.open()}>
            添加
          </Button>,
        ]}
        request={async (params) => {
          const res = await shAgencyFindByPage(params);
          setsearchFormData({ ...params, total: res.data?.total });
          return res?.data;
        }}
        columns={columns}
        pagination={{
          showQuickJumper: true,
        }}
      />
```

**Comment by chenshuai2144** [comment]
列配置呢？

**Comment by wangyongsong** [comment]
> > 只有 submit 才会触发查询，你可以用 onSelect 然后触发` formRef.current.submit()`
> 
> 不对吧，我就是用submit触发的
> 
> ```tsx
>      <ProTable
>         headerTitle=""
>         debounceTime={0}
>         rowKey="id"
>         scroll={{ x: 1000 }}
>         actionRef={actionRef}
>         beforeSearchSubmit={(params: any) => omitBy({ ...params }, isEmpty)}
>         search={{
>           labelWidth: 120,
>           optionRender: ({ searchText, resetText }, { form }) => [
>             access.store_exportStore && (
>               <Button key="out" onClick={() => exportFn()}>
>                 导出
>               </Button>
>             ),
>             <Button
>               key="rest"
>               onClick={() => {
>                 form?.resetFields();
>                 form?.submit();
>               }}
>             >
>               {resetText}
>             </Button>,
>             <Button
>               key="search"
>               type="primary"
>               onClick={() => {
>                 form?.submit();
>               }}
>             >
>               {searchText}
>             </Button>,
>           ],
>         }}
>         toolBarRender={() => [
>           <Button type="primary" key="add" onClick={() => addAgencyRef.current.open()}>
>             添加
>           </Button>,
>         ]}
>         request={async (params) => {
>           const res = await shAgencyFindByPage(params);
>           setsearchFormData({ ...params, total: res.data?.total });
>           return res?.data;
>         }}
>         columns={columns}
>         pagination={{
>           showQuickJumper: true,
>         }}
>       />
> ```

从代码里可以看到我是调用form?.submit();

**Comment by wangyongsong** [comment]
```tsx
const columns: any[] = [
    {
      title: '名称',
      dataIndex: 'name',
      valueType: 'select',
      fieldProps: {
        options: [ { value: 1, label: 1}],
      }
      // renderFormItem: () => <Select options={[ { value: 1, label: 1}]} />
    },
]

  columns = columns.filter((item: any) => {
    if (item.access) return access[item.access];
    return true;
  });
````

**Comment by chenshuai2144** [comment]
你可以用 onSelect 然后触发 formRef.current.submit()，你没触发 formRef 的 submit

**Comment by wangyongsong** [comment]
```tsx
const columns: any[] = [
    {
      title: '名称',
      dataIndex: 'name',
      valueType: 'select',
      fieldProps: {
        options: [ { value: 1, label: 1}],
        onSelect: () => formRef.current.submit(),
      }
    },
];


<ProTable 
   ...
   formRef={formRef}
/>
```
这样好像也不行

**Comment by chenshuai2144** [comment]
把formRef 输出一下，在控制台执行试试看

**Comment by wangyongsong** [comment]
今天找到问题的原因了，是我在搜索条件前加了一层过滤导致的。
![image](https://user-images.githubusercontent.com/58172091/126426118-44cd6168-7ecd-4508-982b-01c81eb78d8d.png)
@chenshuai2144 感谢回复！
