### ISSUE TITLE
🐛[BUG]SchemaForm 的表单数据初始化无效

### ISSUE THREAD

**Issue by giamchen** [ant-design/pro-components#3255]
### 🐛 bug 描述

使用SchemaForm 的表单属性initialValues 初始化数据，没有把数据填充到表单输入框，是目前测试版还没支持吗？

### 🏞 期望结果
initialValues赋值能够吧数据填充的表单

### 💻 复现代码
`
<BetaSchemaForm<DataItem>
    layoutType="ModalForm"
    onVisibleChange={visible => showAppModal(visible)}
    visible={appModalVisible}
    initialValues={appFormData}
    onFinish={async (values) => {
      console.log(values);
    }}
    columns={columns}
  />
`

### © 版本信息

- ProComponents 版本: 1.18.3
- umi 版本 [3.4.0]
- 浏览器环境 [Chrome]
- 开发环境 [windows]

**Comment by giamchen** [comment]
换个写法就好了，应该是initialValues创建之后就不能改变了

**Comment by chenyu1990** [comment]
> 换个写法就好了，应该是initialValues创建之后就不能改变了

换了啥写法，说一下啊

**Comment by chenshuai2144** [comment]
`initialValues && Form`
