### ISSUE TITLE
🧐[问题]valueType='date'时，edit之后，onSave里取到的日期字段是moment对象嘛？

### ISSUE THREAD

**Issue by BongBongBang** [ant-design/pro-components#3256]
### 🧐 问题描述

测试过各种moment对象的方法，都是Undefined的方法，实在是迷糊了

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/10750792/126024581-4a72eadc-56a4-4669-bf8d-e5260c8efd52.png)
![image](https://user-images.githubusercontent.com/10750792/126024598-c4daac13-c993-4d2b-99d2-c9db690feb70.png)

**Comment by liuzhenji** [comment]
文档找遍了，也没有说明，实在搞不动了。。。

**Comment by BongBongBang** [comment]
很莫名其妙地好了。。。。

**Comment by BongBongBang** [comment]
很莫名其妙地好了。。。。

**Comment by BongBongBang** [comment]
很莫名其妙地好了。。。。首先，对象类型就是moment对象类型。其次，为啥就好了，我也是迷的。如遇到同样情况，删掉node_modules，重新装一遍吧。别相信之前装依赖时“已经成功了”，这玩意儿有时候真不可靠，所以多试几次。
另外，记得要自己装一下moment包。
以上

**Comment by BongBongBang** [comment]
> 很莫名其妙地好了。。。。首先，对象类型就是moment对象类型。其次，为啥就好了，我也是迷的。如遇到同样情况，删掉node_modules，重新装一遍吧。别相信之前装依赖时“已经成功了”，这玩意儿有时候真不可靠，所以多试几次。
> 另外，记得要自己装一下moment包。
> 以上

在mac上好使，WIN上不行。

**Comment by BongBongBang** [comment]
版本问题，还在测试

**Comment by BongBongBang** [comment]
pro-field@1.15.5是没有问题的。
