### ISSUE TITLE
🧐[问题]怎么创建一个自己的类似pro-components的库

### ISSUE THREAD

**Issue by xiexingen** [ant-design/pro-components#326]
### 🧐 问题描述
怎么创建一个自己的组件库
- 可以包含多个子组件库(pro-list、pro-layout)
- 发布的时候怎么自动发布(比如，只发布pro-list)
有没这块资料参考参考的

**Comment by HHHui** [comment]
你可以看下 https://github.com/lerna/lerna ，看看是不是你想要的

**Comment by juzhiyuan** [comment]
@xiexingen https://github.com/api7/api7-dashboard

使用 lerna + yarn workspaces 即可，发布时在包里独立发布。

**Comment by xiexingen** [comment]
对对对 就是这种的类型，只是没的啥串起来的文档

**Comment by juzhiyuan** [comment]
可以 fork 仓库后，把 packages 目录中除了 boilerplate 外的 package 都移除掉，然后添加你自己的包。

本地调试时，用 npm link 方式即可。

**Comment by xiexingen** [comment]
我看pro-components没有手动去npm link；个人也感觉npm link太麻烦了
然后往packages添加仓库应该是通过lerna去操作的 
我之前是单个的仓库 然后通过github的actions去自动发布到npm 如果是lerna 怎么来做自动发布，怎么来确定要发布哪些包

**Comment by juzhiyuan** [comment]
通过版本号确定，npm 会限制如果同版本将被拒绝。

**Comment by xiexingen** [comment]
1.每个包的版本号是手动去改package.json文件还是有其他操作方式
2.如果是想通过一些CI自动发布(比如github workflow) 是否方便集成

**Comment by chenshuai2144** [comment]
@xiexingen 看看 learn，有全套解决方案的

**Comment by xiexingen** [comment]
好的  谢谢

**Comment by chenshuai2144** [comment]
@xiexingen 有兴趣给个联系方式吗？

`qixian.cs&outlook.com`

**Comment by xiexingen** [comment]
> qixian.cs&outlook.com

我的qq邮箱: 1002275364@qq.com

**Comment by xiexingen** [comment]
> @xiexingen 有兴趣给个联系方式吗？
> 
> 我的邮箱 `qixian.cs&outlook.com`

你的邮箱好高端，都没@符号的

**Comment by chenshuai2144** [comment]
是为了防止被爬虫爬到，发垃圾邮件

**Comment by xiexingen** [comment]
> 是为了防止被爬虫爬到，发垃圾邮件，我帮你删掉了

多谢多谢
