### ISSUE TITLE
Qt应用程序加载ProTable组件

### ISSUE THREAD

**Issue by mar348** [ant-design/pro-components#3261]
你好，

请问ProTable可以用在Qt应用程序里吗， 像加载其他的js或者css样式一样的轻松方便。
有什么例子可参考吗， 因为网上基本都是基于网页或前段vue react的例子。

谢谢了

**Comment by chenshuai2144** [comment]
这个可能要基于网页了，Qt 应该也是个 webview把，没有了解过
