### ISSUE TITLE
🐛[BUG] [ProForm] antd 版本大于 4.16.6 时表单校验错误会多一层边框

### ISSUE THREAD

**Issue by lwQin** [ant-design/pro-components#3265]
### 🐛 bug 描述

antd 版本大于 ```4.16.6``` 时表单校验错误会多一层边框

### 💻 复现代码

[正常(antd 4.16.6)](https://codesandbox.io/s/pro-form-validate-style-successantd-4166-tfv7s)
[异常(antd 4.16.8)](https://codesandbox.io/s/pro-form-validate-style-errorantd-4168-f6d49)

### © 版本信息

- ProComponents 版本: pro-form 1.32.0
- umi 版本 3.5.13
- 浏览器环境 chrome 91.0
- 开发环境 mac OS Big Sur 11.4

### 🚑 其他信息

<img width="504" alt="Xnip2021-07-19_17-01-44" src="https://user-images.githubusercontent.com/11586662/126133971-bf94de01-8c54-47f1-ae70-4ebfb03e05a9.png">
<img width="522" alt="Xnip2021-07-19_17-01-51" src="https://user-images.githubusercontent.com/11586662/126133986-4b6455f0-ca56-4eae-952d-e578f4c68e6f.png">

**Comment by chenshuai2144** [comment]
antd 会修的，坐等就好了
