### ISSUE TITLE
👑 [需求]mix模式希望在不设置跳转时，默认跳转第一个有页面的菜单

### ISSUE THREAD

**Issue by phoema** [ant-design/pro-components#3266]
### 🥰 需求描述
原帮助文档
自动切割菜单
自动切割菜单是 mix 模式专属的能力，他可以把第一级的菜单放置到顶栏中。我们可以设置 splitMenus=true 来打开它，为了体验良好最好给每个一级菜单都设置一个重定向,这样可以防止切换到白屏页面。

### 🧐 解决方案
自动切割菜单是 mix 模式专属的能力，他可以把第一级的菜单放置到顶栏中。我们可以设置 splitMenus=true 来打开它，为了体验良好最好给每个一级菜单都设置一个重定向,这样可以防止切换到白屏页面，如果分割的菜单未设置redirect，则自动跳转到当前分割导航中第一个有页面的菜单。（这样配置更友好吧，毕竟动态菜单算这个还得写函数。。。）

**Comment by chenshuai2144** [comment]
这个太灵活了，动态菜单该怎么取值呢？如果取第一个，第一个是hideInMenu 或者带参数的要不要跳转

在路由中设置 redirect 是最简单的，成本最低的方式了

**Comment by xkrumeng** [comment]
> ### 🥰 需求描述
> 原帮助文档 自动切割菜单 自动切割菜单是 mix 模式专属的能力，他可以把第一级的菜单放置到顶栏中。我们可以设置 splitMenus=true 来打开它，为了体验良好最好给每个一级菜单都设置一个重定向,这样可以防止切换到白屏页面。
> 
> ### 🧐 解决方案
> 自动切割菜单是 mix 模式专属的能力，他可以把第一级的菜单放置到顶栏中。我们可以设置 splitMenus=true 来打开它，为了体验良好最好给每个一级菜单都设置一个重定向,这样可以防止切换到白屏页面，如果分割的菜单未设置redirect，则自动跳转到当前分割导航中第一个有页面的菜单。（这样配置更友好吧，毕竟动态菜单算这个还得写函数。。。）
> 
> ### 🚑 其他信息
如果给每个一级菜单都设置一个重定向？ 如果一级菜单设置了重定向，则其子节点都忽略了，也就没有了对应的二级菜单了。
