### ISSUE TITLE
🧐[问题]ProFormFields如何带单位？

### ISSUE THREAD

**Issue by jqhr** [ant-design/pro-components#3267]
### 🧐 问题描述

ProFormFields如何带单位？比如ProFormDigit？如果直接在后面带单位，那会导致不对齐

**Comment by chenshuai2144** [comment]
<html>
<body>




addonAfter | 带标签的 input，设置后置标签 | ReactNode | - |  
addonBefore | 带标签的 input，设置前置标签 | ReactNode | -

<br class="Apple-interchange-newline">
</body>
</html>

如果要修改值，就需要自定义 value 和 onchange了，或者直接用 ProFormDigit，有 formart 的 api
