### ISSUE TITLE
👑 [需求]EditableProTable在expandable的情况下怎么添加子的一行？

### ISSUE THREAD

**Issue by jetBn** [ant-design/pro-components#3269]
EditableProTable在expandable的情况下怎么添加子的一行？

**Comment by chenshuai2144** [comment]
现在还不支持，可能要自己拼一下数据了

**Comment by jetBn** [comment]
> 现在还不支持，可能要自己拼一下dataSoucre 数据了

就是我点击往children中添加数据 ？但是我这个点了添加子字段如何然后一添加就处于编辑状态  就跟最外层添加一行数据一样 ？

**Comment by chenshuai2144** [comment]
是的，大概是这样的 

```
dataSoucre.map((item) => {
  if (item.id === id) return { ...item, children: [newItem] };
  return item;
});

```

**Comment by jetBn** [comment]
> 是的，大概是这样的
> 
> ```
> dataSoucre.map((item) => {
>   if (item.id === id) return { ...item, children: [newItem] };
>   return item;
> });
> ```
我这样添加不是 就添加了一行数据吗？但是我想的是效果跟你外层一样那种点击添加效果呢 这个newItem该怎么操作 ？

**Comment by jetBn** [comment]
通过addEditRecord  api添加是最外行的

**Comment by chenshuai2144** [comment]
你自定义一下按钮的click行为。newitem 自定义一下

**Comment by jetBn** [comment]
> 你自定义一下按钮的click行为。newitem 自定义一下

就是我现在是在子添加了 然后通过的是action 的startEditable 把id传进去可实现一创建就处于编辑状态 但是我点击取消 为什么这行没有删除 ，点击删除又是可以删除本行的，，最外层的点击取消会删除当前所处添加的行

**Comment by chenshuai2144** [comment]
新开的pr把，弄个重现的demo，我帮你看看怎么内置支持一下

**Comment by jetBn** [comment]
帮忙看下呗

**Comment by chenshuai2144** [comment]
做了个新的 demo，去看看

**Comment by jetBn** [comment]
这个好像也没有实现点击取消然后能 删除了 子的一行吧 ？然后我想的是在操作一列中点击插入一行这样的， 当然 底部插入的按钮还是插入最外层 一行 就是又可以插入子行 又可以插入最外层

**Comment by chenshuai2144** [comment]
这种灵活的还是要自定义，或者通过嵌套表格来实现，一个表格估计做不到
