### ISSUE TITLE
建议在 layout 的文档中新增关于 location 的配置说明

### ISSUE THREAD

**Issue by bigbigbo** [ant-design/pro-components#327]
如果我自己创建了一个 history 并指定了 basename:
```js
history: createBrowserHistory({
    basename: '/app1',
}),
```
此时 [window.location](https://github.com/ant-design/pro-components/blob/d9fc8d3adc53b45a6d7cb4d02145b02edb6a1e72/packages/layout/src/BasicLayout.tsx#L438) 并不是 layout 组件所需的 location（如果不指定的话，菜单高亮判断的规则就会失效）, 需要显式的传入 props.location，但是文档没有说明，建议添加相关的说明

**Comment by chenshuai2144** [comment]
来个 pr?

**Comment by whinc** [comment]
ProLayout 考虑增加一个 basename 属性来设置路由的基准路径
