### ISSUE TITLE
🧐[问题]如何全局修改ProComponents中Spin的指示符

### ISSUE THREAD

**Issue by samotoo** [ant-design/pro-components#3270]
### 🧐 问题描述

在antd中可以通过`Spin.setDefaultIndicator(indicator: ReactNode)`全局修改加载指示符，请问如何在ProComponents的组件中达到相同的效果呢？

**Comment by chenshuai2144** [comment]
可以的，都是用的 Spin

**Comment by chenshuai2144** [comment]
是不是es 和 lib 的问题，用的不是一个antd 实例

**Comment by samotoo** [comment]
感谢提示，babel-plugin-import插件中设置导入es目录之后解决了。
