### ISSUE TITLE
打包后放在服务器上，在QueryFilter中使用ProFormFieldSet无效

### ISSUE THREAD

**Issue by hhlcom** [ant-design/pro-components#3272]
### 📷 复现步骤
在云效运行本地开发好的代码时，去环境查看的时候，发现没有触发校验以及transformm,    具体原因不知，本地调试ok,之前也没问题，就昨天突然不行了，是不是版本更新涉及到了

### 🏞 期望结果
回到前天的版本

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个重现环境把，你这种描述没法debug的
