### ISSUE TITLE
🐛[BUG] ProTable 的搜索表单项响应式 span 无效

### ISSUE THREAD

**Issue by hauer9** [ant-design/pro-components#328]
### 🐛 bug 描述
`ProTable` 的搜索表单项响应式 `span` 无效，设置 `span` 等于单个数值会生效，设置响应式的时候会失效。在所有宽度下都会等于6，有时候会是3

![image](https://user-images.githubusercontent.com/38620097/91413788-36bb7680-e87e-11ea-9be0-fe0b38c11753.png)

接口声明是表示支持响应式设置的

### 📷 代码

![image](https://user-images.githubusercontent.com/38620097/91412079-d62b3a00-e87b-11ea-9873-e8d3667f4cda.png)

### 结果
设置了所有屏幕大小对应的宽度，但结果似乎变成了失去响应式，并在所有宽度下都会等于6

![image](https://user-images.githubusercontent.com/38620097/91412464-6a959c80-e87c-11ea-9e50-582883de8c95.png)

![image](https://user-images.githubusercontent.com/38620097/91412938-01faef80-e87d-11ea-8faf-cb26105cc943.png)

### 🏞 期望结果

修复搜索表单的响应式 `span`

### © 版本信息

- antd: "^4.5.3"
- pro-layout: "^6.4.1"
- pro-table: "^2.5.3"
- 浏览器环境：firefox
- 开发环境：mac

**Comment by chenshuai2144** [comment]
算法可能有点 bug，你有兴趣提我们修一下吗?

https://github.com/ant-design/pro-components/blob/d9fc8d3adc53b45a6d7cb4d02145b02edb6a1e72/packages/form/src/layouts/QueryFilter/index.tsx#L45

代码再这里

**Comment by chenshuai2144** [comment]
Pr已经提了  #334
