### ISSUE TITLE
🧐ProFormList希望暴露出来一个序号，这样我们新增的表单就能给标题表单一，表单二。。。。

### ISSUE THREAD

**Issue by JackRoy1992** [ant-design/pro-components#3280]
rt

**Comment by yinpeng633** [comment]
+1

**Comment by yinpeng633** [comment]
`itemRender={({ listDom, action }, { field }) => {
          return (
            <ProFormGroup size={20}>
              <ProFormText
                rules={[
                  {
                    required: true,
                  },
                ]}
                name="text-index"
                width={50}
                readonly
                initialValue={field.name + 1}
              />
              {listDom}
              {action}
            </ProFormGroup>
          );
        }}`
这样写能 field.name就是序号，只不过复制删除时不会刷新，不知道有没有其他方法
