### ISSUE TITLE
ProFormSelect自己配置搜索以及搜索条件会每次都请求接口

### ISSUE THREAD

**Issue by hhlcom** [ant-design/pro-components#3284]
### 🥰 需求描述

希望不用每次都请求，
以下是我的代码，有不对的可以指点一下
  <ProFormSelect
        fieldProps={{
          showSearch: true,
          filterOption: methods.filterOption
        }}
        request={async () => {
          return await Api.selectArtist();
        }}
        placeholder="请输入"
      />

**Comment by chenshuai2144** [comment]
每次请求时什么意思，每次 render 都会发起吗？

**Comment by hhlcom** [comment]
> 每次请求时什么英文，每次都打发城市倡议吗？

重新请求后端接口，就好比我上面写的Api.selectArtist();这个接口，我开启搜索，每输入一次，这个接口就会重新请求一次

**Comment by chenshuai2144** [comment]
输入是会的，没有去抖。因为输入会变成参数

**Comment by hhlcom** [comment]
> 输入是会的，没有去抖。因为输入会变成参数

但是设置属性为多选的时候似乎并不会请求，而且自带搜索,单选也能这样么

**Comment by chenshuai2144** [comment]
我来优化一下，这个功能是要打来labelin value 然后多选
