### ISSUE TITLE
node版本为v15.14.0，安装pro-layout会要求ant版本为4.x

### ISSUE THREAD

**Issue by gaozhidf** [ant-design/pro-components#3287]
### 🐛 bug 描述

node版本为v15.14.0，安装pro-layout会要求ant版本为4.x，但node版本v14.17.3就没问题
![image](https://user-images.githubusercontent.com/5724898/126600681-c1fa8803-7b90-4bf6-9e3e-884ceb024c08.png)

### 📷 复现步骤

```bash
nvm use v15.14.0
npm install
```

### 🏞 期望结果

可以正常启动工程

### 💻 复现代码

没有

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
 ```
"@ant-design/pro-layout": "^4.5.16",
"@ant-design/pro-table": "^1.2.9"
```
- umi 版本 ^2.9.6
- 浏览器环境 无关
- 开发环境

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/5724898/126617243-3dbed492-215e-40a5-a704-7af5cdce1c5d.png)

**Comment by chenshuai2144** [comment]
是npm的要求，npm 最新版本检查以来很严格，我都不敢升级上去
