### ISSUE TITLE
👑 有办法将按tap键实现聚焦到下一个表单项改为按enter键吗

### ISSUE THREAD

**Issue by ZhaoXiJiuCao** [ant-design/pro-components#3289]
### 🥰 需求描述

由于是旧系统升级，用户已经习惯回车键聚焦下一表单项的操作，因此要求延续这一功能。

### 🧐 方案
antd pro里面enter键会自动触发提交功能，因此使用了在ProForm 加了onKeyPress方法【这个方法是碰巧试出来的】阻止了enter键触发提交。
对需要聚焦的字段改为<ProForm.Item><Input>(或select)</ProForm.Item>并加上ref属性 onKeyUp方法中调用ref.current.foucus方法进行了聚焦。

### 问题
由于业务上的情况，并不是所有表单都一直可编辑，会存在默认情况下需要foucus到A表单项，但实际A表单项已经是disabled了，需要focus到下一个可编辑的表单项。字段50多个的情况下就会产生大量判断，修改起来也比较麻烦。

所以希望可以有办法将按tap键实现聚焦到下一个表单项改为按enter键 
或者 不知道有没有能够获取表单中所有表单项的方法，遍历数组，根据表单项中属性disabled为false来进行focus

**Comment by chenshuai2144** [comment]
这个估计要用原生了，而且自定义这些东西会增加用户的学习成本。建议不要做

**Comment by tunshiyu** [comment]
> 

请问ref.current.foucus是当前表单，你是怎么回车让下一个表单focus的，获取了dom元素吗
