### ISSUE TITLE
分页功能的问题🐛[BUG]

### ISSUE THREAD

**Issue by paddingC** [ant-design/pro-components#3292]
### 🐛 bug 描述
当数据中有11条数据时，删除最后一条并刷新不会自动回到第一页，currentPage还是2

### 🏞 期望结果
删除最后一条并刷新并且重新请求第一页数据

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
自己处理一下把，组件也不知道该怎么处理这种问题

**Comment by yangxuefneng** [comment]
楼主，问题解决了么？我也遇到了

**Comment by wjf40390** [comment]
我写了一个工具方法，可以参考下https://github.com/ant-design/pro-components/issues/72#issuecomment-1439358372
