### ISSUE TITLE
schema Form 例子中Input组件样式存在问题，具体见截图🐛[BUG]

### ISSUE THREAD

**Issue by mctl** [ant-design/pro-components#3293]
### 🐛 bug 描述

本地开发在ProForm也出现过，官方文档中的链接，：
https://codesandbox.io/s/xbcc2?file=/App.tsx

### 📷 复现步骤

error激活，鼠标force即可出现

### 🏞 期望结果

没有输入框里面的红框

### 💻 复现代码

![image](https://user-images.githubusercontent.com/20489167/126732711-b5072bf2-cfa5-46aa-834e-54f15af324ed.png)

**Comment by DerrickTel** [comment]
等antd修复

**Comment by DerrickTel** [comment]
https://github.com/ant-design/pro-components/issues/3265
