### ISSUE TITLE
🐛[BUG] ModalForm 组件中modalProps 某些属性设置无效

### ISSUE THREAD

**Issue by liweiSm** [ant-design/pro-components#3295]
### 🐛 bug 描述

在ModalForm 组件中，我想实现一个自定义的foolter，所以我在modalProps 中设置 footer = null，
然而footer 并产生应有的结果

### 📷 复现步骤

<ModalForm 
  modalProps={{
      footer: null
  }}
>

### 🏞 期望结果

能正常的控制footer 的展示效果

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by DerrickTel** [comment]
> ModalForm 和 DrawerForm 是 ProForm 的一个变体，本质上仍然是个表单。所以无法通过 footer 来自定义页脚,如果要定义页脚需要使用 submitter.render 来进行自定义。这两个表单的表现与 ProForm 相同，可以从 ProForm 直接修改而来。

https://procomponents.ant.design/components/modal-form

**Comment by liweiSm** [comment]
> > ModalForm 和 DrawerForm 是 ProForm 的一个变体，本质上仍然是个表单。所以无法通过 footer 来自定义页脚,如果要定义页脚需要使用 submitter.render 来进行自定义。这两个表单的表现与 ProForm 相同，可以从 ProForm 直接修改而来。
> 
> https://procomponents.ant.design/components/modal-form

好的，检查了一下，发现是我本地版本太低了，升级后是能通过这个属性设置关闭footer
