### ISSUE TITLE
🐛[BUG] ProTable 2.44.0 ellipsis: true 表格内容穿透，依然没有修复

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#3302]
### 🐛 bug 描述

Windwos10同样的浏览器和同样的系统默认缩放情况下，浏览器缩放100%，ant design 没有问题，显示正常，ant design pro 则出现溢出情况
![QQ浏览器截图20210724142439](https://user-images.githubusercontent.com/3166799/126859643-bc82e7c5-19a6-4eba-9c92-0bb3de0f1271.png)

https://procomponents.ant.design/components/table#%E6%9F%A5%E8%AF%A2%E8%A1%A8%E6%A0%BC
![QQ浏览器截图20210724141528](https://user-images.githubusercontent.com/3166799/126859528-36d469d9-f848-4ace-8b3a-d5e083a27254.png)

https://ant.design/components/table-cn/#components-table-demo-ellipsis
![QQ浏览器截图20210724141541](https://user-images.githubusercontent.com/3166799/126859530-1c26431c-fec9-47e6-b86b-aa586939777b.png)

**Comment by chenshuai2144** [comment]
antd 的最新版本说是修了，你更新下依赖再试试

**Comment by hihuangwei** [comment]
已经OK

**Comment by Ranylx** [comment]
我antd是4.16.9，protable是2.43.4都不行。。

**Comment by luobinhang** [comment]
> antd 的最新版本说是修了，你更新下依赖再试试

@chenshuai2144 更新了还是没用嘞  antd 4.16.9  pro-table 2.47.1  macos 11.4  chorme 92
![image](https://user-images.githubusercontent.com/22189838/130014866-4bd3046a-ef0f-4f2d-872d-7f6e1f2cc7a7.png)
