### ISSUE TITLE
🧐[ProFormList的子元素如何获取到index]

### ISSUE THREAD

**Issue by XuZhaoTong** [ant-design/pro-components#3304]
### 🧐 ProFormList的子元素如何获取到index

```
itemRender={({ listDom, action }, { field }) => {
      return (
        <ProCard
          extra={field.name !== 0 && action}
          title={`成员${field.name + 1}信息`}
        >
          {listDom}
        </ProCard>
      );
    }}
```
不知道如何在listDom中获取到Index

**Comment by JackRoy1992** [comment]
解决了吗，我也遇到需要在list里面的子元素需要index

**Comment by XuZhaoTong** [comment]
> 解决了吗，我也遇到需要在list里面的子元素需要index

还是不知道怎么弄，只能不用listDom了，现在是把listDom的所有内容都放到ProCard中了

**Comment by JackRoy1992** [comment]
> > 解决了吗，我也遇到需要在list里面的子元素需要index
> 
> 还是不知道怎么弄，只能不用listDom了，现在是把listDom的所有内容都放到ProCard中了

然后用record.field.name来做index吗

**Comment by XuZhaoTong** [comment]
> > > 解决了吗，我也遇到需要在list里面的子元素需要index
> > 
> > 
> > 还是不知道怎么弄，只能不用listDom了，现在是把listDom的所有内容都放到ProCard中了
> 
> 然后用record.field.name来做index吗

嗯是，也没找到别的方法了
