### ISSUE TITLE
👑 菜单组件不支持图标显示（子菜单）

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/pro-components#3307]
### 🥰 需求描述

菜单组件不支持图标显示（子菜单）

### 🧐 解决方案

升级依赖包版本后，看了源码，子菜单已经不支持图标显示，请问可以通过配置控制是否显示吗？

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/37643958/126950053-a5c8f3af-753f-4578-9af3-f33c05f05df3.png)

**Comment by chenshuai2144** [comment]
通过menuItemRender自定义一下

**Comment by woojufon** [comment]
楼上答非所问

**Comment by woojufon** [comment]
@chenshuai2144

**Comment by woojufon** [comment]
pro-layout没有menuItemRender，为什么会查看这个地址ant-design/ant-design-pro#8101
