### ISSUE TITLE
🧐[问题] EditableProTable中后一项值于前一项值进行比较大小，rules怎么处理，且怎么拿到彼此是哪一行的数据？

### ISSUE THREAD

**Issue by tanjunfeng** [ant-design/pro-components#3308]
### 🧐 问题描述
🧐[问题] EditableProTable中后一项值于前一项值进行比较大小，rules怎么处理，且怎么拿到彼此是哪一行的数据？

### 💻 示例代码
{
      title: '采购数量',
      dataIndex: 'purchase_count',
      editable: false,
      render: (t, r) => {
        return r?.purchase_count
      }
    },
    {
      title: '拆出数量',
      dataIndex: 'acount',
      formItemProps: {
        rules: [
          {
            required: true,
            message: '请输入拆出数量',
          },
        ],
      },
      renderFormItem: (t, r, form) => {
        return <Input placeholder="请输入拆出数量" />
      },
    },

**Comment by chenshuai2144** [comment]
formItem 支持是一个function的。

第一个参数就是form实例
