### ISSUE TITLE
🐛[BUG]ModalForm增加resetButtonProps使取消失效

### ISSUE THREAD

**Issue by k983551019** [ant-design/pro-components#3309]
### 🐛 bug 描述
当submitter加上
```
 resetButtonProps: {
searchConfig: {
          submitText: "确认",
          resetText: "取消",
        },
           resetButtonProps: {
          style: {
            width: "80px",
          },
        },
        },
```
取消会变成重置效果
去掉resetButtonProps
效果会从重置变成取消

### 📷 复现步骤
submitter={{
        searchConfig: {
          submitText: "确认",
          resetText: "取消",
        },
        submitButtonProps: {
          style: {
            width: "80px",
          },
        },
        resetButtonProps: {
          style: {
            width: "80px",
          },
        },
      }}

### 🏞 期望结果
 取消的效果是取消

### 💻 复现代码
https://codesandbox.io/s/zidingyi-modal-biaodananniu-forked-t2v0j?file=/App.tsx

### © 版本信息

- ProComponents 版本: @ant-design/pro-form@1.28.1
- umi 版本 3.4.25
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
目测是因为 onClick 没了
