### ISSUE TITLE
[pro-component 的设计资源]

### ISSUE THREAD

**Issue by shuwenjunn** [ant-design/pro-components#3311]
官网没有找到，proComponent 的设计资源，sketch 资源?

**Comment by chenshuai2144** [comment]
是没有的，等我们做好了之后才会公布，现在可以用antd的拼一下

**Comment by Deer404** [comment]
@chenshuai2144  2023了 还有可能公布吗，组件还是很好用的，就是设计要是直接设计成你们这样就更方便了
