### ISSUE TITLE
🧐[问题] Prottable 中增加自定义的查询条件，如何监听点击了默认的 `重置` 或 `查询`按钮？在 `Search` 配置中未找到相关事件。

### ISSUE THREAD

**Issue by glk-hll** [ant-design/pro-components#3315]
### 🧐 问题描述
目前点击 `查询` 按钮是可以正常去重新请求数据的，这里的 `重置` 按钮是重置了哪些地方的数据？

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/44257305/127099747-fb2e5ee2-5c78-4a10-a1c9-e8b37b91783b.png)

**Comment by chenshuai2144** [comment]
<html>
<body>


form | antd form 的配置 | FormProps | -
-- | -- | -- | --
onSubmit | 提交表单时触发 | (params: U) => void | -
onReset | 重置表单时触发 | () => void | -


</body>
</html>

直接在table上，

因为比较常用一些，所以放到了第一级

**Comment by glk-hll** [comment]
OK  蟹蟹~
