### ISSUE TITLE
🧐[问题]如何设置嵌套的默认值？如何设置ProText不显示？

### ISSUE THREAD

**Issue by YC725968** [ant-design/pro-components#3319]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/51156342/127120290-542851d3-1016-4685-8e0f-6c06df029d38.png)
![image](https://user-images.githubusercontent.com/51156342/127120334-c88c900c-c69a-4b79-9e25-215ec5d38ed9.png)
类似于以上的嵌套数组该如何设置默认值，设置display=node，还是不显示，该如何设置表单不显示？

**Comment by chenshuai2144** [comment]
`formRef.current?.setFieldsValue({ sysEmpInfo:{ orgName: orgName} })`
这样，嵌套的

**Comment by YC725968** [comment]
已解决，谢谢大佬！，设置当前行不显示，不能用display=‘none’么
