### ISSUE TITLE
🧐[问题]schema-form  layoutType="LightFilter"的时候折叠功能无效 collapse不允许被使用

### ISSUE THREAD

**Issue by weiman-133** [ant-design/pro-components#3320]
### 🧐 问题描述

schema-form  layoutType="LightFilter"的时候折叠功能无效 collapse不允许被使用

希望能实现schema-form时使用LightFilter功能

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/86717611/127120529-26fac2a6-38b1-4439-9695-d14ca1f85efb.png)
![image](https://user-images.githubusercontent.com/86717611/127120611-63f37cc2-afb9-41af-85cc-8a4d55d42b07.png)
![image](https://user-images.githubusercontent.com/86717611/127120749-6d114cd2-4533-4b43-af52-008b702d5878.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 💡 解决方案

在使用 `layoutType="LightFilter"` 时，需要在相应的 schema 中添加 `collapsible:true` 来使折叠功能生效，否则折叠将不允许使用。

示例代码：

```js
const schema = {
  type: "object",
  properties: {
    filterField: {
      type: "string",
      title: "Filter Field",
      collapsible: true // 添加该属性
    }
  }
};
```

参考文档：

- [LightFilter layout](https://uformjs.org/#/schema-form/controls/LightFilter)

**Comment by chenshuai2144** [comment]
实现起来太复杂了，有空搞个pr吧。官方不打算支持
