### ISSUE TITLE
🧐[问题] 使用BetaSchemaForm的时候，如何配置只读模式

### ISSUE THREAD

**Issue by GitKou** [ant-design/pro-components#3323]
### 🧐 问题描述
我想使用ProFormField的只读模式，在和BetaSchemaForm一起使用的时候，配置不生效：
```tsx
 const columns: ProFormColumnsType<IAuthOrgFormValue>[] = [
    {
      title: '用户名',
      dataIndex: 'username',
      fieldProps: {
        mode: 'read',
        isEditable: false,
        // disabled: true,
      },
      width: 'm',
    }
];
 <BetaSchemaForm     columns={columns} />
```
![image](https://user-images.githubusercontent.com/7437397/127250085-09cfa556-c2d3-4293-82bb-d28cde3c70d9.png)

然后我试了其他的，直接用ProFormField是生效的
```tsx
  <ProFormField 
        mode="read" 
            name="username"
            label="用户名"
            placeholder="请输入用户名" />
```

但是用ProFormText不生效
![image](https://user-images.githubusercontent.com/7437397/127249623-da71f9fd-4d1a-4134-8b7f-382e75b5452f.png)
文档里没找到关于只读模式的说明，这个issue里我看已经解决了https://github.com/ant-design/pro-components/issues/915 ，能补充下如何使用的文档吗

**Comment by GitKou** [comment]
看了下代码
https://github.com/ant-design/pro-components/blob/fc9e4487ef0ba661dc9e8c2e9470773d7e246eb0/packages/form/src/components/SchemaForm/index.tsx#L160-L183
这里漏掉了mode
```ts
const item = omitUndefined({
     mode: originItem.mode,
     ......
});
```

**Comment by DerrickTel** [comment]
```
<ProFormText
          proFieldProps={{mode:'read'}}
          ...
/>
```
