### ISSUE TITLE
🧐[问题] class类组件，怎么使用useIntl

### ISSUE THREAD

**Issue by jmy1944311667** [ant-design/pro-components#3324]
### 🧐 问题描述

我现在改造我的项目，使用useIntl进行语言切换，但是我在类组件中，使用useIntl一直报错，想知道这个怎么使用？

### 💻 示例代码
import {LogoutOutlined, SettingOutlined, UserOutlined} from '@ant-design/icons';
import {Avatar, Menu, Spin} from 'antd';
import React from 'react';
import {history, connect, useIntl} from 'umi';
import HeaderDropdown from '../HeaderDropdown';
import styles from './index.less';
import {getResultButton} from '@/utils/utils';
import {setSession} from "@/utils/authority";

class AvatarDropdown extends React.Component {
  onMenuClick = (event) => {
    const {key} = event;

    if (key === 'logout') {
      const {dispatch} = this.props;

      if (dispatch) {
        dispatch({
          type: 'login/logout',
        });
      }

      return;
    }

    if (key === 'settings') {
      // 个人设置
      setSession('buttonCode', 'public.personal.setting');
    }

    history.push(`/userInfo/${key}`);
  };

  render() {
    const {
      currentUser = {
        avatar: '',
        name: '',
      },
      menu,
    } = this.props;
    const menuHeaderDropdown = (
      <Menu className={styles.menu} selectedKeys={[]} onClick={this.onMenuClick}>
        {/* {menu && (
          <Menu.Item key="center">
            <UserOutlined />
            个人中心
          </Menu.Item>
        )} */}
        {menu && (getResultButton('public.personal.setting')) && (
          <Menu.Item key="settings">
            <SettingOutlined/>
            {useIntl.formatMessage({id: 'menu.account.settings'})}
          </Menu.Item>
        )}
        {menu && <Menu.Divider/>}
        <Menu.Item key="logout">
          <LogoutOutlined/>
          {useIntl.formatMessage({id: 'menu.account.logout'})}
        </Menu.Item>
      </Menu>
    );
    return currentUser && currentUser.contacts ? (
      <HeaderDropdown overlay={menuHeaderDropdown}>
        <span className={`${styles.action} ${styles.account}`}>
          <Avatar size="small" className={styles.avatar}
                  src={currentUser.avatar || "https://gw.alipayobjects.com/zos/antfincdn/XAosXuNZyF/BiazfanxmamNRoxxVxka.png"}
                  alt="avatar"/>
          <span className={`${styles.name} anticon`}>{currentUser.contacts}</span>
        </span>
      </HeaderDropdown>
    ) : (
      <span className={`${styles.action} ${styles.account}`}>
        <Spin
          size="small"
          style={{
            marginLeft: 8,
            marginRight: 8,
          }}
        />
      </span>
    );
  }
}

export default connect(({user}) => ({
  currentUser: user.currentUser,
}))(AvatarDropdown);

**Comment by chenshuai2144** [comment]
injectIntl 一下，然后在 props 中拿
```
const FunctionalComponent: React.FC<Props> = props => {
  const {
    date,
    intl, // Injected by `injectIntl`
  } = props
  return (
    <span title={intl.formatDate(date)}>
      <FormattedDate value={date} />
    </span>
  )
}

export default injectIntl(FunctionalComponent)
```

**Comment by jmy1944311667** [comment]
> injectIntl​​ 一下，然后在 props 中拿
> 
> ```
> const FunctionalComponent: React.FC<Props> = props => {
>   const {
>     date,
>     intl, // Injected by `injectIntl`
>   } = props
>   return (
>     <span title={intl.formatDate(date)}>
>       <FormattedDate value={date} />
>     </span>
>   )
> }
> 
> export default injectIntl(FunctionalComponent)
> ```

我是js的，你这个写法是ts的吧，js 的怎么写呢？

**Comment by jmy1944311667** [comment]
> injectIntl

对了，我是不是还需要下载依赖包呢？

**Comment by chenshuai2144** [comment]
从umi中引入一下

**Comment by jmy1944311667** [comment]
> 从umi中引入一下
大佬，那这个js要怎么写呢？ 我看你上面说的那个是ts的，我现在这个是js的，不知道应该怎么写

**Comment by chenshuai2144** [comment]
```
import { injectIntl } form  'umi';

export default injectIntl(Page)
```

**Comment by jmy1944311667** [comment]
> ```
> import { injectIntl } form  'umi';
> 
> export default injectIntl(Page)
> ```

export default connect(Page)
我现在项目是这样的，一个类中可以有两个export default 吗？或者怎么吧connect 和 injectIntl联合在一起呢？   这个框架刚开始搞，不太懂

**Comment by chenshuai2144** [comment]
`connect()(injectIntl(page))`

**Comment by jmy1944311667** [comment]
> `connect()(injectIntl(page))`

好的，我试一下。非常感谢

**Comment by jmy1944311667** [comment]
> `connect()(injectIntl(page))`
可以显示了，谢谢
