### ISSUE TITLE
🧐[问题]EditableProTable - 可编辑表格-怎么表格内处理联动

### ISSUE THREAD

**Issue by robin536180** [ant-design/pro-components#3326]
### 🧐 问题描述

<img width="664" alt="截屏2021-07-28 下午2 01 53" src="https://user-images.githubusercontent.com/8565176/127271957-4bdaf41b-d79a-4486-b8af-fb9322b6b311.png">

当我上传文件之后 后台会返回一个 fileId
在EditableProTable onChange的时候需要提交给后台
我setFieldsValue再获取 都获取不到

### 💻 示例代码

https://codesandbox.io/s/gmtci?file=/App.tsx
### 🚑 其他信息

麻烦帮我看下  怎么处理

**Comment by chenshuai2144** [comment]
```
<ProFormLits>
{(filed)=><Input/> }
</ProFormLits>
```

**Comment by yuanjinxiugithub** [comment]
<img width="628" alt="image" src="https://user-images.githubusercontent.com/26770535/189050989-c747d539-e14e-46e2-89d7-89d9840e7529.png">
加个controlled 属性
