### ISSUE TITLE
🧐[问题]ProTable目前如何透传formItem的校验规则？

### ISSUE THREAD

**Issue by BongBongBang** [ant-design/pro-components#3327]
### 🧐 问题描述

根据现有文档描述，直接通过formItemProps进行传递，但并没有卵用。。看到过几个相关issue，是2020年的，
版本号更是坟墓级别的了。那现在是怎么传

pro-table: 2.43.5

### 💻 示例代码
{
      key: 'xxx',
      title: 'xxx',
      dataIndex: 'xxxx',
      fieldProps: {
        rules: [
          {
            required: false,
            message: '此项为必填项',
          },
        ],
      },
    }

**Comment by BongBongBang** [comment]
看了源码才发现有个ignoreRules属性在控制。回过头来从文档搜索，确实有这个东东，具体如图：
![image](https://user-images.githubusercontent.com/10750792/127290058-59211548-827c-4c08-a3d9-169f2ac335e9.png)

**Comment by BongBongBang** [comment]
我原以为问题就这么结束了，但并不是。。。。继续看源码。。。

**Comment by BongBongBang** [comment]
按照文档的要求，给proTable加form : {{ignoreRules: false}} 或者search: {{ignoreRules:false}}都没用。。。

**Comment by chenshuai2144** [comment]
query 类型的表单的最好不要加 rule

**Comment by BongBongBang** [comment]
> query 类型的表单的最好不要加 rule

现在是加了也么用，那“最好”是啥意思，不支持这个功能么？

**Comment by BongBongBang** [comment]
我现在看到从FieldContext获取的fieldItemProps属性，可从chrome调试工具看，相应Item的Context里，fieldItemProps并没有我传递的值

**Comment by chenshuai2144** [comment]
@BongBongBang  有些特殊场景要用，所以开了个口子，你可能需要更新一下依赖的版本

**Comment by BongBongBang** [comment]
> @BongBongBang 有些特殊场景要用，所以开了个口子，你可能需要更新一下依赖的版本

目前只有Pro-Table相对应升级到比较新的2.43.5版本。既如此，我再升级下其他组件的版本看看。。。

**Comment by chenshuai2144** [comment]
```
git clean -dfx 
yarn
```

这样最爽一次搞定
