### ISSUE TITLE
在ProFormFieldSet中使用ProFormDatePicker拿不到值

### ISSUE THREAD

**Issue by hhlcom** [ant-design/pro-components#3329]
### 🧐 问题描述

根据现有文档描述，直接通过ProFormFieldSet包裹ProFormDatePicker组件，在提交时transform的值为空
 <ProFormFieldSet
        name="list"
        label="创建时间"
        transform={(value: any) => {
          console.log(value, 'value');
          return { startTime: value[0], endTime: value[1] };
        }}
      >
        <ProFormDatePicker width="md" />
        <ProFormText width="md" />
        <ProFormText width="md" />
      </ProFormFieldSet>

### 🚑 其他信息
输入所有的值后时间框的值为空
![image](https://user-images.githubusercontent.com/71809799/127280656-7b460560-026c-4206-9306-e76eb6e21506.png)

**Comment by chenshuai2144** [comment]
这里修了

https://github.com/ant-design/pro-components/pull/3321

**Comment by hhlcom** [comment]
> 这里修了
> 
> [第3321章](https://github.com/ant-design/pro-components/pull/3321)
更新了依赖好像还是无效，会不会是因为我得是放在QueryFilter里面的，然后好像有许多组件在ProFormFieldSet都拿不到值
