### ISSUE TITLE
🐛[BUG]@ant-design/pro-table 从2.43.6升级至2.45.0，多级表头的子列，第一列会默认左固定

### ISSUE THREAD

**Issue by thelaurelyy** [ant-design/pro-components#3336]
### 🐛 bug 描述
将依赖@ant-design/pro-table 的版本从2.43.6升级至2.45.0，表格使用多级表头，子列的第一列默认会展示fixed:left 的效果，左滑固定，所有的第一个子列均有该效果；

### 📷 复现步骤
将依赖@ant-design/pro-table 的版本从2.43.6升级至2.45.0，表格使用多级表头即可复现

### 🏞 期望结果
取消对应属性或者能提供API供配置

### 💻 复现代码
企业项目不方便提供代码，但是复现步骤很简单，期待回复，感谢~

### © 版本信息

- ProComponents 版本:  2.45.0
- umi 版本  3.4.18
- 浏览器环境 Chrome 91.0.4472.164
- 开发环境 [e.g. Windows]

**Comment by HappyManYun** [comment]
是这个现象吧 #3441
