### ISSUE TITLE
ModalForm 问题

### ISSUE THREAD

**Issue by lovesL** [ant-design/pro-components#3340]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/27960630/127584465-a707c9fd-7300-4f70-bc69-afd688a84a81.png)
为什么在return 前面写if判断  ModalForm就不消失了 return 必须写在 if前面才管用

**Comment by DerrickTel** [comment]
没法复现，可以给个demo看看嘛？

**Comment by lovesL** [comment]
> 没法复现，可以给个demo看看嘛？

好的 我抽时间写一个看看能不能复现

**Comment by lovesL** [comment]
> > 没法复现，可以给个demo看看嘛？
> 
> 好的 我抽时间写一个看看能不能复现

问题找到了 message 没从 antd  导出来  很奇怪 它也一直没报错....
