### ISSUE TITLE
🧐[问题]如何通过EditableProTable.RecordCreator 添加表格的子列

### ISSUE THREAD

**Issue by jiazhuangle** [ant-design/pro-components#3342]
### 🧐 问题描述
[https://procomponents.ant.design/components/editable-table/#%E6%9C%89%E5%AD%90%E5%88%97%E7%9A%84%E8%A1%A8%E6%A0%BC%E5%A2%9E%E5%8A%A0](url)  有子列的表格增加的例子中,在recordCreatorProps中设置了parentKey 

使用EditableProTable.RecordCreator 如何实现
```
 <EditableProTable.RecordCreator
        key="copy"
       **parentKey ={xxxx}**
        record={{
          id:111
        }}
      >
        <a>添加子列</a>
      </EditableProTable.RecordCreator>,
```

发现没有parentKey属性

**Comment by chenshuai2144** [comment]
升级一下版本哦，是最近新加的功能

**Comment by jiazhuangle** [comment]
谢谢

**Comment by superAo005** [comment]
目前可以添加子列  不过添加的子列不能继续添加子列

**Comment by chenshuai2144** [comment]
可以的，但是key要自己算，算起来还挺麻烦的
