### ISSUE TITLE
🧐[问题]stepsForm三个表单获取详情需要调三次接口？

### ISSUE THREAD

**Issue by JackRoy1992** [ant-design/pro-components#3343]
### 🧐 问题描述
使用步骤器提交表单，查看详情也要使用步骤器展示，我每个表单都需要request来获取数据？可我接口只有一个，这调用多次？
### 代码示例
```
<StepsForm
      formRef={formRef}
      submitter={{
        render: (props, dom) => {
          if (props.step === 0) {
            return (
              <Button type='primary' onClick={() => props.onSubmit?.()} loading={isLoading}>{pageStatus === 'detail' ? '查看下一页' : '下一步，配置活动内容'}</Button>
            )
          }
          if (props.step === 1) {
            return [
              <Button key='pre' onClick={() => props.onPre?.()} disabled={isLoading}>上一步</Button>,
              <Button key='next' type='primary' onClick={() => props.onSubmit?.()} loading={isLoading}>{pageStatus === 'detail' ? '查看下一页' : '下一步，配置活动规则'}</Button>
            ]
          }
          if (props.step === 2) {
            return [
              <Button key='pre' onClick={() => props.onPre?.()} disabled={isLoading}>上一步</Button>,
              pageStatus !== 'detail' && <Button key='next' type='primary' onClick={() => props.onSubmit?.()} loading={isLoading}>提交</Button>
            ]
          }
        }
      }}
    >
      <StepsForm.StepForm
        name='basic'
        title='填写基本信息'
        // params={activityId}
        request={async () => {
          let res = await APIs.getActivityDetail(activityId)
          const { success, data, message } = res
          if (success) {
            const { healthActivityBaseInfo,
              healthActivityConfigurationList,
              healthActivityPopUpsConfigurationList, healthActivityRule } = data
            return {
              data: healthActivityBaseInfo
            }
          } else {
            Message.error(message, 3)
          }
        }}
        onFinish={async (values) => {
          return true;
        }}
        initialValues={basicFormData}
        onValuesChange={checkChange}
      >
        <BasicForm
        ></BasicForm>
      </StepsForm.StepForm>
      <StepsForm.StepForm
        name='lottery'
        title='配置活动内容'
        request={async () => {
          let res = await APIs.getActivityDetail(activityId)
          const { success, data, message } = res
          if (success) {
            const { healthActivityBaseInfo,
              healthActivityConfigurationList,
              healthActivityPopUpsConfigurationList, healthActivityRule } = data
            return {
              data: healthActivityConfigurationList
            }
          } else {
            Message.error(message, 3)
          }
        }}
        // validateTrigger='onSubmit'
        // layout='vertical'
        initialValues={lotteryFormData}
      >
        <LotteryForm
        ></LotteryForm>
      </StepsForm.StepForm>
      <StepsForm.StepForm
        name='rules'
        title='配置活动规则'
        layout='horizontal'
        initialValues={rulesFormData}
        request={async () => {
          let res = await APIs.getActivityDetail(activityId)
          const { success, data, message } = res
          if (success) {
            const { healthActivityBaseInfo,
              healthActivityConfigurationList,
              healthActivityPopUpsConfigurationList, healthActivityRule } = data
            return {
              data: healthActivityPopUpsConfigurationList
            }
          } else {
            Message.error(message, 3)
          }
        }}
      >
        <RulesForm
        ></RulesForm>
      </StepsForm.StepForm>
    </StepsForm>
```

**Comment by JackRoy1992** [comment]
`<StepsForm
      formRef={formRef}
      submitter={{
        render: (props, dom) => {
          if (props.step === 0) {
            return (
              <Button type='primary' onClick={() => props.onSubmit?.()} loading={isLoading}>{pageStatus === 'detail' ? '查看下一页' : '下一步，配置活动内容'}</Button>
            )
          }
          if (props.step === 1) {
            return [
              <Button key='pre' onClick={() => props.onPre?.()} disabled={isLoading}>上一步</Button>,
              <Button key='next' type='primary' onClick={() => props.onSubmit?.()} loading={isLoading}>{pageStatus === 'detail' ? '查看下一页' : '下一步，配置活动规则'}</Button>
            ]
          }
          if (props.step === 2) {
            return [
              <Button key='pre' onClick={() => props.onPre?.()} disabled={isLoading}>上一步</Button>,
              pageStatus !== 'detail' && <Button key='next' type='primary' onClick={() => props.onSubmit?.()} loading={isLoading}>提交</Button>
            ]
          }
        }
      }}
    >
      <StepsForm.StepForm
        name='basic'
        title='填写基本信息'
        // params={activityId}
        request={async () => {
          let res = await APIs.getActivityDetail(activityId)
          const { success, data, message } = res
          if (success) {
            const { healthActivityBaseInfo,
              healthActivityConfigurationList,
              healthActivityPopUpsConfigurationList, healthActivityRule } = data
            return {
              data: healthActivityBaseInfo
            }
          } else {
            Message.error(message, 3)
          }
        }}
        onFinish={async (values) => {
          return true;
        }}
        initialValues={basicFormData}
        onValuesChange={checkChange}
      >
        <BasicForm
        ></BasicForm>
      </StepsForm.StepForm>
      <StepsForm.StepForm
        name='lottery'
        title='配置活动内容'
        request={async () => {
          let res = await APIs.getActivityDetail(activityId)
          const { success, data, message } = res
          if (success) {
            const { healthActivityBaseInfo,
              healthActivityConfigurationList,
              healthActivityPopUpsConfigurationList, healthActivityRule } = data
            return {
              data: healthActivityConfigurationList
            }
          } else {
            Message.error(message, 3)
          }
        }}
        // validateTrigger='onSubmit'
        // layout='vertical'
        initialValues={lotteryFormData}
      >
        <LotteryForm
        ></LotteryForm>
      </StepsForm.StepForm>
      <StepsForm.StepForm
        name='rules'
        title='配置活动规则'
        layout='horizontal'
        initialValues={rulesFormData}
        request={async () => {
          let res = await APIs.getActivityDetail(activityId)
          const { success, data, message } = res
          if (success) {
            const { healthActivityBaseInfo,
              healthActivityConfigurationList,
              healthActivityPopUpsConfigurationList, healthActivityRule } = data
            return {
              data: healthActivityPopUpsConfigurationList
            }
          } else {
            Message.error(message, 3)
          }
        }}
      >
        <RulesForm
        ></RulesForm>
      </StepsForm.StepForm>
    </StepsForm>
    `

**Comment by chenshuai2144** [comment]
StepsForm.StepForm 有自己的默认值的。也可以统一使用一个默认值。看你需求。
