### ISSUE TITLE
🐛[BUG]<ProForm.Group />默认同时有水平间距和垂直间距

### ISSUE THREAD

**Issue by sunyongming** [ant-design/pro-components#3344]
### 🐛 bug 描述

在1.31.2版本<ProForm.Group />默认同时有水平间距和垂直间距，必须设置如：size={[32,0]}才能消除垂直间距，这应该是新版本的bug，之前版本没有这个问题

### 📷 复现步骤

官网例子即可复现：https://procomponents.ant.design/~demos/fieldset-components-other

### 🏞 期望结果

<ProForm.Group />默认只有水平间距，并且设置size="small"时只设置水平间距

### © 版本信息

- pro-form 版本: 1.31.2
- umi 版本: 3.2.14
- 浏览器环境 : Google Chrome
- 开发环境 : win

**Comment by chenshuai2144** [comment]
你说的垂直间距是不是 formitem 的间距，来个截图吧。

diff 了下 dom 看起来没问题

**Comment by sunyongming** [comment]
![image](https://user-images.githubusercontent.com/40694337/127967521-7d370107-e5d5-47d5-b357-51331f7d02d6.png)
这个间距，记得之前版本没有这个间距

**Comment by sunyongming** [comment]
![image](https://user-images.githubusercontent.com/40694337/127967659-728ad2d0-3cab-44ce-8a80-bae6495688cb.png)
现在换行的话，默认就会显的计较宽

**Comment by sunyongming** [comment]
查看了以前版本也有这个间距😓，我的错

**Comment by chenshuai2144** [comment]
来个 pr 支持下配置？
