### ISSUE TITLE
👑 [需求] Protable 工具栏建议

### ISSUE THREAD

**Issue by linchenhuicn** [ant-design/pro-components#3346]
### 🥰 需求描述
fullScreen和reload 是否能加一个回调
另外density 能否加一个初始值设置

**Comment by 690591397** [comment]
> ### 🥰 需求描述
> fullScreen和reload 是否能加一个回调
> 另外density 能否加一个初始值设置

+1

**Comment by chenshuai2144** [comment]
* 另外density 能否加一个初始值设置

这个配置 size 来实现

* fullScreen和reload 是否能加一个回调

fullScreen 可以通过浏览器事件，reload 这个可以 await

**Comment by 690591397** [comment]
> * 另外density 能否加一个初始值设置
> 
> 这个配置 size 来实现
> 
> * fullScreen和reload 是否能加一个回调
> 
> fullScreen 可以通过浏览器事件，reload 这个可以 await

配置了size，切换density，size不改变。
期望有一个defaultDensity，使得能设置density的初始值，而不是提供一个“默认”。
文档第一个例子可复现。
```js
  size: 'small',
  options: {
    show: true,
    density: true,
    fullScreen: true,
    setting: true,
  },
```
https://procomponents.ant.design/components/table/?current=1&pageSize=5

**Comment by linchenhuicn** [comment]
> * 另外density 能否加一个初始值设置
> 
> 这个配置 size 来实现
> 
> * fullScreen和reload 是否能加一个回调
> 
> fullScreen 可以通过浏览器事件，reload 这个可以 await

fullScreen绑定浏览器事件也是有弊端，如果当前页面有多个table，而你仅仅想某一个table全屏时触发，就不好判断了
