### ISSUE TITLE
pro-components能不能兼容一下  版本为47的火狐浏览器 ？

### ISSUE THREAD

**Issue by jonny201251** [ant-design/pro-components#3350]
![兼容低版本火狐](https://user-images.githubusercontent.com/16256433/127637387-55ef9937-cd0f-4fb7-ae9b-bcafdeaf7b22.jpg)

从下面网址，下载 版本为47的火狐浏览器
http://ftp.mozilla.org/pub/firefox/releases/47.0/win32/zh-CN/
http://ftp.mozilla.org/pub/firefox/releases/47.0/win64/zh-CN/

**Comment by jonny201251** [comment]
第一步：从下面网址，下载 版本为47的火狐浏览器
http://ftp.mozilla.org/pub/firefox/releases/47.0/win32/zh-CN/
http://ftp.mozilla.org/pub/firefox/releases/47.0/win64/zh-CN/
第二步：安装完成后，先断网，防止火狐浏览器自动更新，接着设置浏览器不更新为最新版本
![2](https://user-images.githubusercontent.com/16256433/127637694-12c24e79-2095-4ba6-ad2a-260ac72bdf55.jpg)

**Comment by jueinin** [comment]
47支持es6的吧，而且pro-components打出来的是es5的语法啊

**Comment by chenshuai2144** [comment]
你可以配置一下编译 node_modules里面的内容，然后编译到低版本。

https://umijs.org/zh-CN/config#nodemodulestransform
