### ISSUE TITLE
🧐[问题] 如何设置header zindex层级高度呀！

### ISSUE THREAD

**Issue by codedart2018** [ant-design/pro-components#3351]
### 🧐 问题描述

有些变态毛病的第三方把层级写在style里面，无法通过class自定义style来修改zindex.　就导致页面滚动的时候这个盖住了冲部栏很不好看。无奈只能问问antd-pro了。我也是找了很多文档资料都没办法修改。而且在atnd-pro里的　layout-header 的zindex 层级是100也是写在style里的。希望增加一个参数能自己修改。

**Comment by binvb** [comment]
没啥办法，这种用 important 覆盖吧

**Comment by binvb** [comment]
没啥办法，这种用 important 覆盖吧

**Comment by chenshuai2144** [comment]
important 一把梭，不行 js 直接改 dom
