### ISSUE TITLE
🐛[BUG] EditableProTable 调用form.setFieldsValue 没有效果

### ISSUE THREAD

**Issue by linchenhuicn** [ant-design/pro-components#3352]
### 🐛 bug 描述

从2.43.6@ant-design/pro-table版本开始，EditableProTable 调用form.setFieldsValue 没有效果

![image](https://user-images.githubusercontent.com/21193805/127796158-5385e072-9efe-4817-97b1-0816d3f135e2.png)

### © 版本信息

- @ant-design/pro-table: 2.43.6
- umi 3.5.14
- 开发环境 [e.g. mac OS]

**Comment by zscgxs** [comment]
<Input
                        onBlur={() => {
                            let currentRow = form.getFieldsValue()
                            let currentRowKey = Object.keys(currentRow)[0]
                            let currentRowValue = currentRow[Object.keys(currentRow)[0]]
                            if (currentRowValue.serialNumber && currentRowValue.serialNumber.length < 4) {
                                currentRowValue.serialNumber = currentRowValue.serialNumber.padStart(4, '0')
                            }
                            form.setFieldsValue({ [currentRowKey]: { ...currentRowValue } })
                        }}
                        placeholder="请输入"
                    />

**Comment by zscgxs** [comment]
![image](https://user-images.githubusercontent.com/52776819/128680544-e3d6478c-2078-4269-abc9-3c8159a52c52.png)
数据是这样的

**Comment by chenshuai2144** [comment]
当前行的key你是怎么拿到的，看起来不搭对

**Comment by superAo005** [comment]
当前行的key你是怎么拿到的

**Comment by chenshuai2144** [comment]
就是你设置的rowKey，rowKey.dataIndex就是你的name
