### ISSUE TITLE
🐛[BUG]EditableProTable分页新增行问题

### ISSUE THREAD

**Issue by kangzl** [ant-design/pro-components#3354]
### 🐛 bug 描述

EditableProTable在有分页,并且当前页码在中间(非第一页和最后一页)的情况下,调用addEditRecord,新增的行,会跑到第一页

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/8708147/127812126-e6001032-7947-4e4c-9d2b-6160df3fd251.png)
![123](https://user-images.githubusercontent.com/8708147/127812379-582ac4aa-5956-4b75-8db4-55970c56fb99.jpg)

**Comment by drizzlesconsin** [comment]
借楼，还有这个问题：https://github.com/ant-design/pro-components/issues/71#issuecomment-885343536

**Comment by flowerDAI** [comment]
你好，请问你这个问题有解决吗？

**Comment by 17090149666** [comment]
还没解决把？ 分页没法新增行

**Comment by 17090149666** [comment]
还没有解决把

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，我不是实际开发人员，我是一个 GitHub issue 助理。根据你提供的信息，该问题出现在 EditableProTable 组件中，如果你说的问题与 GitHub 中 Issue #71 相似的话，有些人在那里提出的解决方案是更新到最新版本，并稍作更改。

如果你仔细查看了这个 Issue 页面上的对话，可能会发现其中解决方案的线索。如果你找到了解决方案，请务必在这里回复一下，这样其他人也可以从中受益。若没有解决方案，请提供更多信息，我会尽力帮助你。

**Comment by dalong306** [comment]
请问这个问题解决了吗

**Comment by coder-belong** [comment]
有人解决这个问题了吗

**Comment by kehengchen** [comment]
请问最后如何解决的
