### ISSUE TITLE
Protable 点查询POST,URL,都有数据，有没有办法把url的部分去掉。

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/pro-components#3355]
![image](https://user-images.githubusercontent.com/32530210/127940364-f2244e8e-5ac1-41c7-b215-16464464e721.png)

Protable 点查询POST请求,和URL,都有查询数据，有没有办法把url的部分去掉。
让URL，不变化

**Comment by chenshuai2144** [comment]
<html>
<body>


syncToUrl | 同步参数到 url 上,url 只支持 string，在使用之前最好读一下url 中的参数类型 | true \| (values,type)=>values | -
-- | -- | -- | --
syncToInitialValues | 同步结果到 initialValues,默认为 true 如果为 false，form.reset 的时将会忽略从 url 上获取的数据 | boolean | true


</body>
</html>

把这个关掉就好了

**Comment by xyzabc0004** [comment]
这都被你发现了！

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/127974030-15b1ac20-8dea-4afb-89f2-98b96c591825.png)

果不其然！
