### ISSUE TITLE
🧐[问题]EditableProTable 实时保存如何实现在输入框失去焦点后才保存

### ISSUE THREAD

**Issue by ai180508** [ant-design/pro-components#3358]
### 🧐 问题描述

EditableProTable 实时保存如何实现在输入框失去焦点后才保存
### 💻 示例代码
![image](https://user-images.githubusercontent.com/77037794/127949475-aac1b855-873f-4c7a-a952-b800f10b9701.png)

**Comment by chenshuai2144** [comment]
<html>
<body>


validateTrigger | 统一设置字段触发验证的时机 | string \| string[] | onChange | 4.3.0
-- | -- | -- | -- | --



</body>
</html>

可以试试这个功能，

额，可能要等等了，我还没实现

**Comment by t880216t** [comment]
renderFormItem 也可以呀
`
{
      title: '值',
      dataIndex: 'xxxx',
      width: '30%',
      renderFormItem: (text, { record }) =>  <Input defaultValue={text} onBlur={() => handleInputChange(record)} />
}
`
