### ISSUE TITLE
🐛[BUG] pro-table v2.6.1 某些原因导致的request失败，table就会一直处于loading状态

### ISSUE THREAD

**Issue by dmdoit** [ant-design/pro-components#336]
### 🐛 bug 描述
比如请求参数错误，或者后台错误，table会一直处于loading状态
![image](https://user-images.githubusercontent.com/19385704/91533984-61bbce00-e943-11ea-8e0f-44eafeffbf5d.png)

### 📷 复现步骤
让request请求失败，就会复现这个问题

### 🏞 期望结果
即使table的request失败，也会自动终止table的loading状态

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个 pr 吧。看起来不是很难解决
