### ISSUE TITLE
🐛[BUG] ProTable 设置 manualRequest 后 tableExtraRender 不会渲染

### ISSUE THREAD

**Issue by jiyingzhi** [ant-design/pro-components#3360]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by pipihua666** [comment]
+1

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/blob/0cb6adaddb730813b35b1fea73cc931881ddfb27/packages/table/src/Table.tsx#L338-L342

发现是故意这么做的，给个 dataSource 的默认值试试
