### ISSUE TITLE
DrawerForm有没有from.setFieldsValue(initValues)的用法

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/pro-components#3362]
DrawerForm有没有from.setFieldsValue(initValues)的用法？

像这样：
![image](https://user-images.githubusercontent.com/32530210/127970509-9e074327-9063-47af-8049-a7c6c5ec4cd3.png)
会根据initValues里面的属性，自动绑定form里面的item.

能这样不？

**Comment by chenshuai2144** [comment]
DrawerForm 用formRef 来操作，功能是完全对齐的

**Comment by xyzabc0004** [comment]
OK，我再看看

**Comment by xyzabc0004** [comment]
成本还有点大
