### ISSUE TITLE
🐛[BUG] ProTable 中 ProColumns 类型错误

### ISSUE THREAD

**Issue by changjunhao** [ant-design/pro-components#3365]
### 📷 复现步骤
将 @ant-design/pro-table 升级到 2.47.0 后，ProColumns 类型出现错误

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
  "@ant-design/pro-table": "^2.47.0",
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

TS2322: Type '{ fixed: "left"; title: string; dataIndex: string; order: number; width: number; }' is not assignable to type 'ProColumns<ListItem, "text">'.   Type '{ fixed: "left"; title: string; dataIndex: string; order: number; width: number; }' is not assignable to type 'ProColumnType<ListItem, "text">'.     Property 'proFieldProps' is missing in type '{ fixed: "left"; title: string; dataIndex: string; order: number; width: number; }' but required in type 'Pick<any, "proFieldProps">'.

**Comment by 1467602180** [comment]
在package.json中加上此代码覆盖包内依赖版本可暂时解决问题

`"resolutions": {
    "@ant-design/**/@ant-design/pro-utils": "1.20.1"
  }`

**Comment by changjunhao** [comment]
@ant-design/pro-table@2.47.1 已修复
