### ISSUE TITLE
🐛[BUG] ProTable 分页器触发多次

### ISSUE THREAD

**Issue by GuoKeMPF** [ant-design/pro-components#3367]
### 🐛 bug 描述

pagination中的 onChange 和 onShowSizeChange会触发多次

![image](https://user-images.githubusercontent.com/33691310/127993649-ada12176-1224-47ba-a009-1661e8b6d732.png)
![image](https://user-images.githubusercontent.com/33691310/127993768-0f9dd87b-fc01-46ca-9c90-9f9afac9e0df.png)

### 📷 复现步骤

定义分页器改变时触发的函数并配置到 ProTable pagination 中
```jsx

  const onChangePage = (page: number, size?: number) => {
    console.log("onChangePage");
    console.log(page, size);
  };

  ...

  pagination: {
     ...
    onChange: onChangePage,
    onShowSizeChange: onChangePage,
  },
```
挂载和修改分页数据时函数多次触发

### 🏞 期望结果

挂载的时候不触发，修改的时候触发一次。

### 💻 复现代码

https://codesandbox.io/s/shuxingzhanshi-forked-u9gc3?file=/App.tsx:2212-2328

### © 版本信息

- @ant-design/pro-table 版本: [ 2.47.0]
- 开发环境 [linux]

**Comment by jiachaosun** [comment]
我也能复现

```
const onChangePageBill = (page) => {
    console.log(1);
};

pagination={{
    showQuickJumper: false,
    showSizeChanger: false,
    total: totalCount,
    current: pageIndex,
    pageSize: 1,
    onChange: onChangePageBill,       <----- 这里执行了两边
}}
```

**Comment by jiachaosun** [comment]
LZ已经贴了https://codesandbox.io/s/shuxingzhanshi-forked-u9gc3?file=/App.tsx:2212-2328

打开cab的控制台就能看见

**Comment by GuoKeMPF** [comment]
> Hello @GuoKeMPF. Please provide a online reproduction by forking this link https://codesandbox.io/ or a minimal GitHub repository.
> 
> 你好 @GuoKeMPF, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。 如何写个好问题？https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

您好，这个在线实例可以复现上述问题。
https://codesandbox.io/embed/shu-xing-zhan-shi-forked-m3n2f?fontsize=14&hidenavigation=1&theme=dark
在通过分页器修改pageSize时，App.tsx 中的 onChangePage 被多次调用。

**Comment by chenshuai2144** [comment]
> @jiachaosun LZ已经贴了https://codesandbox.io/s/shuxingzhanshi-forked-u9gc3?file=/App.tsx:2212-2328
打开cab的控制台就能看见


不能用，先关了

**Comment by jiachaosun** [comment]
https://user-images.githubusercontent.com/859382/146744985-3857712a-e9da-44ff-89af-ed3f03b460a9.mp4

The video above was just from the reply you closed.

@chenshuai2144

**Comment by chenshuai2144** [comment]
没办法对着 视频 debug的。
