### ISSUE TITLE
@umijs/use-params 1.0.3 SSR error 🐛[BUG]

### ISSUE THREAD

**Issue by h2oiswater** [ant-design/pro-components#3369]
### 🐛 bug 描述

pro-components中，from与layout均依赖了@umijs/use-params.
@umijs/use-params在SSR中会报错。

### 📷 复现步骤

1. 新建nextjs工程
2. 使用 "next-plugin-antd-less": "^1.3.0"
3. 引入"antd": "^4.16.9", "@ant-design/pro-layout": "^6.23.3"
4. 使用pro-layout

### 🏞 期望结果

SSR时可以使用pro-layout , pro-form.

### 💻 复现代码

暂无

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- 使用 "next-plugin-antd-less": "^1.3.0"
- 引入"antd": "^4.16.9", "@ant-design/pro-layout": "^6.23.3"
- macOS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/5397807/128064483-bef05fda-6311-49b6-85ef-de57d523f352.png)

```javascript

var locationSearch = (_a = window === null || window === void 0 ? void 0 : window.location) === null || _a === void 0 ? void 0 : _a.search;

```

这一段报错 window is not defined.

**Comment by chenshuai2144** [comment]
fixed, 判断没写好
