### ISSUE TITLE
🐛[BUG] table 2.43.5 小屏幕下溢出，水平滚动条缺失

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#3370]
### 🐛 bug 描述
![IMG_20210804_101428](https://user-images.githubusercontent.com/3166799/128111212-57c91db0-629e-489b-a9c3-f5b9a64b128a.jpg)

**Comment by chenshuai2144** [comment]
我这里的没有好的办法，你如果有好的方法欢迎 pr

**Comment by hihuangwei** [comment]
> 我这里的没有好的办法，你如果有好的方法欢迎 pr
> 
> 我们暂时没有精力提供手机端的良好体验

在2.43.5版本之前是有水平滚动条的
