### ISSUE TITLE
🐛[BUG] pnpm安装依赖，pro-utils下typing.d.ts无法解析到相对路径的ProFormItemProps

### ISSUE THREAD

**Issue by lucasllin** [ant-design/pro-components#3371]
### 🐛 bug 描述

pnpm安装依赖，pro-utils下typing.d.ts无法解析到相对路径的ProFormItemProps

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/10697191/128113616-f6c48755-71e2-4606-83c4-7a6ee3216bde.png)
![image](https://user-images.githubusercontent.com/10697191/128113744-92adbcab-300d-49e3-a350-3602590ce02d.png)

**Comment by b1ngx** [comment]
不能将类型“{ title: string; dataIndex: string;}”分配给类型“ProColumns<any, "text">”。
  不能将类型“{ title: string; dataIndex: string;}”分配给类型“ProColumnType<any, "text">”。
    类型 "{ title: string; dataIndex: string;}" 中缺少属性 "proFieldProps"，但类型 "Pick<any, "proFieldProps">" 中需要该属性。ts(2322)

**Comment by rds57826** [comment]
原因在于@ant-design/pro-utils包升级到1.20.2后，typing.d.ts文件的最后增加了一句`& Pick<ProFormItemProps, 'proFieldProps'>`，导致proFieldProps成为必选项，望尽快修复

**Comment by 0x219** [comment]
https://github.com/ant-design/pro-components/issues/3372 应该与这个问题相同，已经修复了。
