### ISSUE TITLE
🐛[BUG] ProColumns 中缺少属性 "proFieldProps"，但类型 "Pick<any, "proFieldProps">" 中需要该属性

### ISSUE THREAD

**Issue by b1ngx** [ant-design/pro-components#3372]
### 🐛 bug 描述

ProColumns 中缺少属性 "proFieldProps"，但类型 "Pick<any, "proFieldProps">" 中需要该属性。ts(2322)

### © 版本信息

- @ant-design/pro-table 版本: 2.47.0,
- umi 版本: 3.5.15
- 浏览器环境: Microsoft Edge 版本 92.0.902.62
- 开发环境: Windows 10 20H2

**Comment by laozhu** [comment]
一样的问题，升级后出现。

**Comment by Merely-chao** [comment]
我也遇到了，但是不影响使用，强迫症的话可以下面这样。
 `proFieldProps:{ 
      //可以把自定义渲染放进来
        renderFormItem:()=>{
.......
}
}`


可以看看这个 #3347

**Comment by YangYuHub** [comment]
我也遇到了 ，有没有好一点解决方案呢
![image](https://user-images.githubusercontent.com/63183404/128135458-30e8f954-ef9f-432d-a4dc-81a15364134e.png)
