### ISSUE TITLE
ProTabel采用models过来的[]，datasource方式显示，总显示上一次查询的[]

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/pro-components#3373]
我还是先上两个图，
models是这样的，
![image](https://user-images.githubusercontent.com/32530210/128120914-ccda0315-5443-48e7-b0ef-13964a79a740.png)

protabel显示页面
![image](https://user-images.githubusercontent.com/32530210/128121084-0d927af3-76d4-407f-9b61-1ae17d6bb9de.png)

这样点查询老是显示上一次查询的结果。
不知道是哪里错了，还是我理念就错了，不应该这么来。

请专家指点下下。

**Comment by jiazhuangle** [comment]
useeffect 变化的时候更新一下呢

**Comment by chenshuai2144** [comment]
request 是惰性的，你把值直接给了 params 好了

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/128988220-2a61fd85-6b9a-4582-9262-207e009dd1b7.png)
我是这么来了下。
这个搞法可能不是正规的玩法。

**Comment by chenshuai2144** [comment]
用params吧，这样的方式数据流向太不直观了

**Comment by xyzabc0004** [comment]
好，你这么一说，有点小感觉了。后面我再试哈。
