### ISSUE TITLE
ProTable在哪里去掉，第一次加载的时候，查询。

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/pro-components#3378]
ProTable在哪里去掉，第一次加载的时候，查询。

每次打开，他ProTable都跟我查询了一次，我想不要。
不知道哪里的机关。去掉。

**Comment by fhyfhytt** [comment]
request:false

**Comment by xyzabc0004** [comment]
manualRequest={true}
是这个吧。

**Comment by 0x219** [comment]
> manualRequest={true}
> 是这个吧。

对的

**Comment by xyzabc0004** [comment]
> > manualRequest={true}
> > 是这个吧。
> 
> 对的

ok !
