### ISSUE TITLE
🐛[BUG] pro-table 表格穿透的情况依然存在

### ISSUE THREAD

**Issue by Anonymity94** [ant-design/pro-components#3380]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/13148447/128291815-adb97b31-f6a9-4a1b-af48-ab5154c4ab30.png)

### 📷 复现步骤
https://codesandbox.io/s/mih1r

![image](https://user-images.githubusercontent.com/13148447/128297155-f067e0fc-5067-46fb-96d2-abeb3290e6a0.png)

### © 版本信息

  - "@ant-design/pro-table": "^2.47.1"
  - "antd": "^4.16.10",
  -  "umi": "^3.5.8",
  - 开发环境： MacOS
  - 浏览器：Chrome 版本 92.0.4515.107（正式版本） (x86_64)

**Comment by Ranylx** [comment]
我这边看是正常的，但是在浏览器缩放比降低的情况下就会发生溢出

**Comment by chenshuai2144** [comment]
去antd 问问把，这个能力是antd 提供的。

**Comment by Anonymity94** [comment]
好的~
