### ISSUE TITLE
🐛[BUG] ProList的SubTitle在内容超长的时候会溢出页面

### ISSUE THREAD

**Issue by Ranylx** [ant-design/pro-components#3382]
和PR #3059修复的问题类似
另外希望prolist能适配移动端，提供ellipsis功能

**Comment by chenshuai2144** [comment]
开源项目可以自己提pr的哦

**Comment by DerrickTel** [comment]
subtitle可以render一个带有ellipsis的组件。我觉得应该改为可以换行而不是加一个ellipsis功能进去。不然会越来越重 @chenshuai2144

**Comment by chenshuai2144** [comment]
@DerrickTel  换行就好了，ellipsis用 css 的能力吧。

js 的 ellipsis bug 也挺多的

**Comment by DerrickTel** [comment]
主标题和副标题是同一行是UI设计的吗？
我在想极端情况的控制，主标题过长和副标题过长。他们换行都不太美观的样子。。。
这种设计风格可以吗？
![image](https://user-images.githubusercontent.com/24643779/128671722-d27f3698-6ac4-4717-8032-7fe653c53def.png)

**Comment by chenshuai2144** [comment]
可以的，没啥问题。开发者自己应该控制标题长度的
