### ISSUE TITLE
🧐[问题] 我想可以得到rootRef ，问下要怎么做比较好

### ISSUE THREAD

**Issue by zhangle1** [ant-design/pro-components#3385]
### 🧐 问题描述

var rootRef=useRef

<ProTablerootRef={rootRef} > </ProTable>

**Comment by chenshuai2144** [comment]
rootRef 要干什么？

**Comment by DerrickTel** [comment]
可以在外面包裹一个div之类的标签，这样就可以拿到了。假如满足需求的话
