### ISSUE TITLE
🧐[问题] EditableProTable 如何实现表格中编辑字段通过A字段给B、C字段赋值，并可以正常显示

### ISSUE THREAD

**Issue by czf0321** [ant-design/pro-components#3390]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/30063100/128442852-27b93e92-4e3b-429b-b5a5-fc3098048179.png)

目前情况通过setDataSource 可以更新值到数组中，但是前端页面不显示数据
### 🧐 示例代码
![image](https://user-images.githubusercontent.com/30063100/128443681-c159c2c7-bb64-4782-ba60-aac0358e8bd6.png)

**Comment by chenshuai2144** [comment]
要用 `form.setFieldValue `，或者打开受控模式
