### ISSUE TITLE
🧐[问题]protable 本地筛选不生效

### ISSUE THREAD

**Issue by JimLeeee** [ant-design/pro-components#3392]
### 💻 示例代码
import ProTable from '@ant-design/pro-table';
import React, { useState, useEffect, useRef} from 'react';
import { querySparkRunningApps, queryNslist, querySvcs } from '../service';

const LogEtl = () => {
  const formRef = useRef()
  const columns = [
    {
      title: '应用ID',
      dataIndex: 'id',
      key: 'id',
      hideInSearch: true,
    //   width: 100,
    },
    {
      title: '应用',
      dataIndex: 'name',
      key: 'name',
      // onFilter: true,
      onFilter: (value, record) => record.name.includes(value),
      // filters: [
      //   { text: 'nginx', value: 'nginx' },
      //   { text: 'fluent', value: 'fluent' },
      // ],
    },
    {
      title: '启动时间',
      dataIndex: 'starttime',
      key: 'starttime',
      valueType:'dateTime',
      hideInSearch: true,
      sorter: (a, b) => a.starttime - b.starttime,
    },
    {
        title: '状态',
        dataIndex: 'state',
        key: 'state',
        hideInSearch: true,
    },
    {
        title: '占用核数',
        dataIndex: 'cores',
        key: 'cores',
        hideInSearch: true,
        sorter: (a, b) => a.cores - b.cores,
    },
    {
        title: 'Memory per Executor',
        dataIndex: 'memoryperslave',
        key: 'memoryperslave',
        hideInSearch: true,
    },
    {
        title: '运行时间',
        dataIndex: 'duration',
        key: 'duration',
        hideInSearch: true,
        sorter: (a, b) => a.duration - b.duration,
        render: text => Math.floor(text/1000/3600 * 100) / 100 + 'h'
        // render: text => {
        //     let t = moment.duration(text)
        //     console.log(t)
        //     return t.get('hours') + '时' + t.get('minutes') + '分' + t.get('seconds') + '秒'
        // }
    },
    {
        title: '用户',
        dataIndex: 'user',
        key: 'user',
        hideInSearch: true,
    },
    {
      title: '操作',
      dataIndex: 'option',
      valueType: 'option',
      align: 'center',
      render: (text, record, _, action) => [
        <a
          key="operation"
          onClick={async () => {

          }}
        >
          添加操作
        </a>,
      ],
    },
  ];
  
  return (
      <ProTable
        formRef={formRef}
        // search={false}
        search={{
            filterType: 'light',
        }}
        headerTitle="正在运行的应用"
        form={{
          ignoreRules: false,
          submitter: {
            resetButtonProps: {
              style: {
                // 隐藏重置按钮
                // display: 'none',
              },
            },
          }
        }}
        pagination={{
          pageSize: 50
        }}
        rowKey="id"
        options={{
          // show: false,
          // search:true,
          density: true,
          fullScreen: true,
          setting: true,
        }}
        request={async (params,sorter,filter) => querySparkRunningApps(params,sorter,filter)}
        columns={columns}
      />
  )
}
export default LogEtl

**Comment by chenshuai2144** [comment]
filters 也是必填的。
