### ISSUE TITLE
ProTabel表单自定义renderFormItem,只要Form里面有一点变化，他都执行了一次

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/pro-components#3396]
![image](https://user-images.githubusercontent.com/32530210/128540990-5bd0a7eb-2ba9-4a41-96dc-e46276aa79ed.png)

还是上图，
ProTabel表单自定义renderFormItem, 只要Form里面其它text有一点变化，他都执行了一次
其实，我只想一个分类下拉列表变化，才执行，绑定第二个下拉列表。
不然，其它text变化时，第二个列表是动态从数据库里面取话的，他会绑定很多次。

这个该怎么来下？

**Comment by xyzabc0004** [comment]
我感觉做联动的表单，还得用ProForm，ProTable分开，走DataSource

**Comment by chenshuai2144** [comment]
为了方便做循环以来，这点性能没啥的，dom没有更新
