### ISSUE TITLE
🧐请问如何设置ProTable表格数据中，每一行或者每一个格子的颜色

### ISSUE THREAD

**Issue by colorbitch** [ant-design/pro-components#3397]
### 🧐 问题描述

问题如标题，希望通过每一行的值，去判断当前行/当前格子的颜色。目前有在andt的文档中看到rowClassName，可以设置行的颜色，但是这个属性如何在ProTable中使用呢？另外antd中也没有找到格子的配置方式，麻烦看下，谢谢！

**Comment by drizzlesconsin** [comment]
```ts
...
render: (text) => {
  return {
     children: text,
      props: {
          style: { background: 'red' }
      }
  }
}
```

**Comment by colorbitch** [comment]
> ```ts
> ...
> render: (text) => {
>   return {
>      children: text,
>       props: {
>           style: { background: 'red' }
>       }
>   }
> }
> ```

非非非常感谢，能不能再指导下，整个row变色要怎么写，拜托拜托🙏

**Comment by colorbitch** [comment]
> ```ts
> ...
> render: (text) => {
>   return {
>      children: text,
>       props: {
>           style: { background: 'red' }
>       }
>   }
> }
> ```

非常感谢🙏

**Comment by zyk2891** [comment]
单行的颜色怎么加？
