### ISSUE TITLE
🐛[BUG] ProFormSelect 默认提示应为 请选择

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#3398]
### 🐛 bug 描述

![QQ浏览器截图20210807205323](https://user-images.githubusercontent.com/3166799/128600838-033eb897-5402-480c-9934-b4691df644ca.png)

**Comment by drizzlesconsin** [comment]
这个如果不配置 message, 可以考虑把 ProFormSelect 包装一层。
```ts
const { required, label } = props;
{ required, message: `请选择${label}` }
```

**Comment by chenshuai2144** [comment]
我们没有默认设置rule，所以需要你自己设置了
