### ISSUE TITLE
🐛[BUG]ProTable中的列类型为timerange时，添加行会报错

### ISSUE THREAD

**Issue by JoeyGaojingxing** [ant-design/pro-components#3399]
### 🐛 bug 描述

editable Protable，`time range` 类型无法正常新建和编辑。

### 📷 复现步骤

使用Protable，且列类型为timerange（目测时间组件都有问题），后端获取数据类型必须为number的时间戳，如果为 `12:11:23` 会显示 `Invalid date`。而目前的问题是，新建一行，默认数据类型也是 “hh:mm:ss” 字符串格式的，而非时间戳，所以直接使用组件创建行会导致显示问题。现在这部分需要手动重写

### 🏞 期望结果

使用默认组件即可创建保存

### © 版本信息

- ProComponents 版本:  5.0.0
- umi 版本：1.0.36
- 浏览器环境：chrome
- 开发环境：windows10

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/15071824/128633206-70832191-4cf7-4b49-9864-f7bf2a41f04f.png)
![image](https://user-images.githubusercontent.com/15071824/128633248-5390e16d-f10a-4a34-ad3d-0ba58d298200.png)
![image](https://user-images.githubusercontent.com/15071824/128633270-18c59498-4642-458f-838a-a9151abf8b19.png)

**Comment by JoeyGaojingxing** [comment]
大佬们项目结构的确组织的很好，我自己重写修改逻辑就解决了。还是希望大佬们抽时间看看，我也尽量学习下项目结构看看能不能提个pr

**Comment by chenshuai2144** [comment]
应该是没有自动转化为moment导致的

**Comment by chenshuai2144** [comment]
只有 hh:mm:ss 信息太少了，moment 无法的正确的格式化。

建议后端至少也要存 时间戳，不然格式化会变得很麻烦
