### ISSUE TITLE
ProLayout 在设置 collapsed 为 true 时，首次载入会触发 onCollapse false 回调 🐛[BUG]

### ISSUE THREAD

**Issue by aweiu** [ant-design/pro-components#340]
### 🐛 bug 描述

项目的菜单折叠展开状态会记录到 LocalStorage 中，这需要使用 ProLayout 的 `collapsed` 和 `onCollapse` 来控制。
如此，刷新页面后，如果上次的状态是折叠，那传入的 `collapsed` 则为 `true`，但是 `onCollapse` 会立即再回调一个 `false`，
这会触发菜单折叠状态的更新，从而导致菜单又被展开。
 
### 📷 复现步骤

```
<ProLayout collapsed onCollapse={collapsed => console.log(collapsed)} />
```
如此，你会在 `collapsed` 被设置为 `true` 的情况下，收到一个 `false` 的回调

### 🏞 期望结果

只有当点击菜单控制器的时候再触发 `onCollapse` 或者使其回调结果严格等于 `collapsed`

### 💻 复现代码

```
<ProLayout collapsed onCollapse={collapsed => console.log(collapsed)} />
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://ant.design/components/layout-cn/#Layout.Sider

看看这里，layout 也有相关配置 ，你可以直接关掉它

**Comment by aweiu** [comment]
> https://ant.design/components/layout-cn/#Layout.Sider
> 
> 看看这里，layout 也有相关配置 ，你可以直接关掉它

不好意思，没明白。「关掉」是指？或者说如何通过 AntLayout 的配置解决我提的问题呢？

**Comment by WangJM001** [comment]
同样的问题
@chenshuai2144 再看下问题你理解错意思了吧，其他现在就是没法默认是折叠状态

**Comment by WangJM001** [comment]
@aweiu 同样的需求
不要使用onCollapse了，重写collapsedButtonRender方法吧
![image](https://user-images.githubusercontent.com/20501316/92066913-9f05dd00-edd5-11ea-84f3-8f86be70050f.png)

**Comment by chenshuai2144** [comment]
breakpoint | 触发响应式布局的断点 | Enum { 'xs', 'sm', 'md', 'lg', 'xl', 'xxl' } | lg
-- | -- | -- | --




是这个

**Comment by zhanchengkun** [comment]
不应该是 把breakpoint更改后的属性值 开放出来？
