### ISSUE TITLE
🧐ProTable的搜索栏是radioButton类型，实现点击button触发查询遇到问题

### ISSUE THREAD

**Issue by colorbitch** [ant-design/pro-components#3400]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/8054331/128633876-1701f939-d323-4c5c-8eed-e71362f3853e.png)

如图，点击分组需直接触发查询，于是拓展onChange函数，把结果setFieldsValue，这个过程也成功触发查询，但是此次查询的传参不正确；也试过用value，setState的形式，也是不对。而在点击【查询】按钮时，传参的值又是正确的，不知道是哪里问题。

请问如何解决这个问题？

### 💻 示例代码

> {
            title: '分组',
            key: 'idDivisor',
            valueType: 'radioButton',
            hideInTable: true,
            initialValue: window.localStorage.getItem('idDivisor'),
            valueEnum: commonEnums.KEFU_ID_DIVISOR_ENUM,
            fieldProps: {
                value: idDivisor,
                onChange: async (e) => {
                    // 这样不行
                    formRef?.current.setFieldsValue('idDivisor', e.target.value);
                    // 这样也不行
                    setIdDivisor(e.target.value);
                    actionRef?.current.reload();
                }
            }

**Comment by DerrickTel** [comment]
把radio的值放到request里面去，请求都是调用的request的请求。你setFieldsValue只是修改form的值，目前没有做这方面的监听，但是调用request的时候会去取form里面的值。

**Comment by colorbitch** [comment]
谢谢！
