### ISSUE TITLE
ProForm中两个ProFormSelect联动

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/pro-components#3401]
按照文档提示，第一个select变化时，第二个select的label是有变化，没有问题。
![image](https://user-images.githubusercontent.com/32530210/128635372-a1a8d21e-ebfd-4a54-ba15-4dc86f0d63b4.png)

现在想拿到的categoryid值，最数组放到第二个select 里面。
![image](https://user-images.githubusercontent.com/32530210/128635414-fe6c111d-46f8-48b0-ae80-5f273c52a580.png)
经过多次的测试，这里面的request中的代码，只有在组件第一次加载时，执行了下。后面变化，不执行。

还请老师们指点下。

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/128649939-af302f0c-1331-48e8-ac44-895d3e4a5e0f.png)
![image](https://user-images.githubusercontent.com/32530210/128649994-de1d9cde-ce27-4546-a6aa-4b1e7a125d0d.png)

改成
onValuesChange,
setFieldsValue
方式后，ProFormText，都可以设置值，ProFormSelect不能被给值。

**Comment by xyzabc0004** [comment]
感觉用setFieldsValue不太对，我现在的需求是第二个select要初化值。而setFieldsValue是设置选中值。
方向感觉错了。

**Comment by chenshuai2144** [comment]
setFieldsValues 是对的。不然就要频繁销毁了。试试 ProFormDependency ，更加方便一点


ProFormDependency
ProFormDependency 是一个简化版本的 Form.Item，它默认内置了 noStyle 与 shouldUpdate，我们只需要配置 name 来确定我们依赖哪个数据，ProFormDependency 会自动处理 diff 和并且从表单中提取相应的值。

name 参数必须要是一个数组，如果是嵌套的结构可以这样配置 name={['name', ['name2', 'text']]}。配置的 name 的值会在 renderProps 中传入。name={['name', ['name2', 'text']]} 传入的 values 的值 为 { name: string,name2: { text:string } }。

**Comment by xyzabc0004** [comment]
> setFieldsValues 是对的。不然就要频繁销毁了。试试 ProFormDependency ，更加方便一点
> 
> ProFormDependency
> ProFormDependency 是一个简化版本的 Form.Item，它默认内置了 noStyle 与 shouldUpdate，我们只需要配置 name 来确定我们依赖哪个数据，ProFormDependency 会自动处理 diff 和并且从表单中提取相应的值。
> 
> name 参数必须要是一个数组，如果是嵌套的结构可以这样配置 name={['name', ['name2', 'text']]}。配置的 name 的值会在 renderProps 中传入。name={['name', ['name2', 'text']]} 传入的 values 的值 为 { name: string,name2: { text:string } }。

OK，谢谢，我再试试！

**Comment by xyzabc0004** [comment]
经过无数次的试验：

代码如下：
![image](https://user-images.githubusercontent.com/32530210/129048005-62567985-c03d-4ccc-b4f5-54cb99f7c095.png)
第一次打开的界面：正常
![image](https://user-images.githubusercontent.com/32530210/129048152-af793457-a3c0-4d81-be6b-fd212585f62c.png)
第一次更改分类选顶，出来的界面，课本列表正常
![image](https://user-images.githubusercontent.com/32530210/129048267-d601726d-c637-48c5-a79b-96b5edf6f6c8.png)
当我再次更改分类选项时，第二个ProSelect课本列表无变化，
![image](https://user-images.githubusercontent.com/32530210/129048438-70410732-6112-42fe-9d1c-eb6240352928.png)

是不是哪里还有机关。

**Comment by chenshuai2144** [comment]
key 重复了把，没有触发重新更新

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/129328974-015a436b-901e-407c-95c4-2be6c7609e5b.png)

**Comment by chenshuai2144** [comment]
那就是没设置key？

**Comment by xyzabc0004** [comment]
我确实没有配置第二个ProSelect的key 属性。
![image](https://user-images.githubusercontent.com/32530210/129506364-3d19e1b4-0920-4924-801a-d45ca74bc93c.png)
需要加个Key吗

**Comment by xyzabc0004** [comment]
还是说request 返回数组里面每个对象加个key？

**Comment by chenshuai2144** [comment]
![Uploading image.png…]()


给这个上面价格key吧

**Comment by xyzabc0004** [comment]
我试哈看

**Comment by xyzabc0004** [comment]
![1629102631(1)](https://user-images.githubusercontent.com/32530210/129535504-27751743-05ac-4d91-b068-8d4294541f97.png)

太难了，有点想放弃了。`

**Comment by xyzabc0004** [comment]
妈呀！！！
机关在这里！！！
原来！！！
![image](https://user-images.githubusercontent.com/32530210/129573274-13f6be3b-d0da-4d45-a918-4742f2e31733.png)

**Comment by xyzabc0004** [comment]
看文档还是很重要！
