### ISSUE TITLE
🐛[BUG]pro table rowKey默认值的问题

### ISSUE THREAD

**Issue by luxiangxiong** [ant-design/pro-components#3402]
### 🐛 bug 描述

在使用pro table的tableAlertRender时，如果pro table没设置rowKey，rowKey默认值似乎不会生效，以至于tableAlertRender里面的参数selectedRows undefined

### 📷 复现步骤

https://codesandbox.io/s/biao-ge-pi-liang-cao-zuo-forked-rhmov?file=/App.tsx

### 🏞 期望结果

rowKey默认值修复

### 💻 复现代码

https://codesandbox.io/s/biao-ge-pi-liang-cao-zuo-forked-rhmov?file=/App.tsx

### © 版本信息

- ProComponents 版本: "@ant-design/pro-table": "^2.47.1"
- 浏览器环境：chrom最新版
- 开发环境 ：mac OS

### 🚑 其他信息

![A2708797-5298-4D8E-A178-8636FAD3222F](https://user-images.githubusercontent.com/65578067/128653289-9eb813a0-d28d-4cd4-9c14-145d54cca8b1.png)

**Comment by DerrickTel** [comment]
兄弟，我找了好久....我才发现你的文档截图是antd的。
antd的文档应该是写错了。
https://codesandbox.io/s/zh474?file=/index.js:1157-1171
这个官方的例子选中的key是index。所以他们默认是index。
然后你log的东西，是因为你`setSelectRowKeys([record.key]);`设置的原因，我一直以为是ProTable自带设置错误的...各种调试。。。

**Comment by luxiangxiong** [comment]
> 兄弟，我找了好久....我才发现你的文档截图是antd的。
> antd的文档应该是写错了。
> https://codesandbox.io/s/zh474?file=/index.js:1157-1171
> 这个官方的例子选中的key是index。所以他们默认是index。
> 然后你log的东西，是因为你`setSelectRowKeys([record.key]);`设置的原因，我一直以为是ProTable自带设置错误的...各种调试。。。

不是这样的吧- -这个默认值应该是属性key的意思吧，而不是key: value中的value值吧

**Comment by DerrickTel** [comment]
> > 兄弟，我找了好久....我才发现你的文档截图是antd的。
> > antd的文档应该是写错了。
> > https://codesandbox.io/s/zh474?file=/index.js:1157-1171
> > 这个官方的例子选中的key是index。所以他们默认是index。
> > 然后你log的东西，是因为你`setSelectRowKeys([record.key]);`设置的原因，我一直以为是ProTable自带设置错误的...各种调试。。。
> 
> 不是这样的吧- -这个默认值应该是属性key的意思吧，而不是key: value中的value值吧

哦哦，是的。真的是key的意思。我看糊了，抱歉
