### ISSUE TITLE
🐛[BUG]Protable 表格列fixed渲染问题

### ISSUE THREAD

**Issue by jaw52** [ant-design/pro-components#3403]
### 🐛 bug 描述
具体我的表格数据column是处理好的，配置column中的fixed的参数为false，表格渲染出现问题。在React Developer Tools中查看，我传递的参数
![image](https://user-images.githubusercontent.com/53564781/128654174-80b70bdd-62e3-4852-b519-46760d853801.png)

但是渲染出来的fixed变为了right

![image](https://user-images.githubusercontent.com/53564781/128654289-3ddd103c-1a39-4f52-9dca-3d8cf0113333.png)

### 🏞 期望结果

之前的procomponent版本没有问题

### © 版本信息

- ProComponents 最新版本
- edge最新版本
- 开发环境 Windows

**Comment by jaw52** [comment]
确认了之前的版本没有问题

**Comment by chenshuai2144** [comment]
没有 fixed:false，直接用 undfinded

**Comment by jaw52** [comment]
> 没有 fixed:false，直接用 undfinded
配置column中的fixed的参数为undfinded
![image](https://user-images.githubusercontent.com/53564781/129124389-c791df1e-4a54-4121-bf65-d8a154a9e3b1.png)
渲染出来仍为right
![image](https://user-images.githubusercontent.com/53564781/129124586-897ffe85-387d-49ec-9cc0-6eba5daa60a3.png)

Protable 2.43.4版本无这个问题
