### ISSUE TITLE
🧐[问题]自定义可编辑表格只能新增一行吗？

### ISSUE THREAD

**Issue by gracexiong** [ant-design/pro-components#3404]
### 🧐 自定义表格怎么才能支持新建多行？

![image](https://user-images.githubusercontent.com/23145977/128675059-fd8e0737-895a-4e10-b46e-43367c951c42.png)

**Comment by chenshuai2144** [comment]
暂时不支持的。数据过于复杂，维护不了。

你可以打开受控模式，用dataSource  和 editorRowKeys 来自行控制
