### ISSUE TITLE
🧐[问题]感觉proTable接收的数据格式和统一的数据格式有冲突

### ISSUE THREAD

**Issue by GitKou** [ant-design/pro-components#3405]
### 🧐 问题描述
umi推荐的数据格式如下（以下称作格式A）:
![image](https://user-images.githubusercontent.com/7437397/128676127-a56c0847-9a4e-46f8-833a-a1b7e1cba514.png)
可见data中指的是后端返回的原始数据, eg: ```{code: '200', data: {list:[], current: 1, total: 10}}```；

而proTable接收的格式如下，其中data是list，total和data是同级，（以下称作格式B）:
```ts
    return {
      data: msg.result,
      // success 请返回 true，
      // 不然 table 会停止解析数据，即使有数据
      success: boolean,
      // 不传会使用 data 的长度，如果是分页一定要传
      total: number,
    };
```
；
这样造成个问题，当我全局设置了responsenterceptor来将reponse转成proTable接收的格式B之后，使用umi中useRequest会丢失page的信息，因为umi的useRequest内置了```formResult:(res=>res.data)```
感觉这两种规范对于data的定义存在不一致

**Comment by chenshuai2144** [comment]
useRequest 不推荐和protable 一起用，两个功能是重复的

**Comment by GitKou** [comment]
> useRequest 不推荐和protable 一起用，两个功能是重复的

所以你们一般项目里，response是什么格式的呀

**Comment by chenshuai2144** [comment]
```
{
  data:{}[]
  total:number;
  page:number
}
```

一般是这样的
