### ISSUE TITLE
🐛[BUG]ProLayout二级之后的菜单icon无效不渲染

### ISSUE THREAD

**Issue by Minfee** [ant-design/pro-components#3409]
### 🐛 bug 描述
ProLayout二级之后的菜单icon无效不渲染

### 📷 复现步骤
见复现代码

### 🏞 期望结果
二级及以下菜单配置icon后可以正常渲染

### 💻 复现代码
https://codesandbox.io/s/6qeu6?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这是个featrue，是设计师专门做的
