### ISSUE TITLE
👑 [需求] valueType的数字和金额展示的一点建议

### ISSUE THREAD

**Issue by GamesSoul** [ant-design/pro-components#3411]
现在valueType的money类型可以加一个去掉货币种类的api么，或者digit类型可以加一个精度控制么？

                           🙏蟹蟹了

**Comment by chenshuai2144** [comment]
```tsx
valueType='money'
filedProps={{
   moneySymbol:false,
  precision:2
}}
```

**Comment by Renderz** [comment]
> ```tsx
> valueType='money'
> filedProps={{
>    moneySymbol:false,
>   precision:2
> }}
> ```

fieldProps是查询表单的透传参数吧，不是表格展示的参数吧。

**Comment by chenshuai2144** [comment]
表格展示靠的就是filed

**Comment by GamesSoul** [comment]
> 表格展示靠的就是filed

老哥  最近更新的pro-table又让这个货币符号api失效了

**Comment by chenshuai2144** [comment]
来个重现

**Comment by GamesSoul** [comment]
> 来个重现
![5464244E-922E-46C7-BD13-237A0BB346AB](https://user-images.githubusercontent.com/37973776/145341227-1632ea48-f121-4034-a4de-ac8f848946ec.png)
"@ant-design/pro-table": "^2.57.2",

**Comment by GamesSoul** [comment]
> 来个重现

渣渣封闭式开发的破网终于能登上 codesandbox了  我用写了个dome 老哥你看下   https://codesandbox.io/s/wu-cha-xun-biao-dan-forked-g4wq5?file=/App.tsx

**Comment by Renderz** [comment]
> > 来个重现
> 
> 渣渣封闭式开发的破网终于能登上 codesandbox了 我用写了个dome 老哥你看下 https://codesandbox.io/s/wu-cha-xun-biao-dan-forked-g4wq5?file=/App.tsx

直接用digit看看呢？
```
{
    title: "金额",
    dataIndex: "amount",
    align: "right",
    valueType: "digit",
    fieldProps: {
      minimumFractionDigits: 4,
      maximumFractionDigits: 4
      // moneySymbol: false,
      // precision: 4
    }
  }
```

**Comment by GamesSoul** [comment]
> > > 来个重现
> > 
> > 
> > 渣渣封闭式开发的破网终于能登上 codesandbox了 我用写了个dome 老哥你看下 https://codesandbox.io/s/wu-cha-xun-biao-dan-forked-g4wq5?file=/App.tsx
> 
> 直接用digit看看呢？
> 
> ```
> {
>     title: "金额",
>     dataIndex: "amount",
>     align: "right",
>     valueType: "digit",
>     fieldProps: {
>       minimumFractionDigits: 4,
>       maximumFractionDigits: 4
>       // moneySymbol: false,
>       // precision: 4
>     }
>   }
> ```

我改了下我的代码   digit  用来表示体积， 重量还可以，而且这个digit 在精度方面不能严格控制在小数点后4位这个地步， 如果用来表示金额的话 也会没有千分位的显示过滤了https://codesandbox.io/s/wu-cha-xun-biao-dan-forked-qcj1u?file=/App.tsx

**Comment by Renderz** [comment]
> 

看了下ProFieldMoney组件，用于展示金额Symbol依赖locale参数，但是这个组件并没有从fieldProps内透传过来，而是用的默认值”zh-Hans-CN“。

**Comment by chenshuai2144** [comment]
moneySymbol 设置为false 就会消失掉的

**Comment by Renderz** [comment]
> moneySymbol 设置为false 就会消失掉的

```
const getTextByLocale = (
  localeStr: string | false,
  paramsText: number | string | undefined,
  precision: number,
  config?: any,
) => {
  let moneyText = paramsText;
  if (typeof moneyText === 'string') {
    moneyText = Number(moneyText);
  }

  if (!moneyText && moneyText !== 0) return '';

  // 这里传入的localeStr是undefined的话，会默认给zh-Hans-CN
  return new Intl.NumberFormat(localeStr || 'zh-Hans-CN', {
    ...(intlMap[localeStr || 'zh-Hans-CN'] || intlMap['zh-Hans-CN']),
    maximumFractionDigits: precision,
    ...config,
  }).format(moneyText);
};
```

fieldProps.moneySymbol = false的情况下，NumberFormat的参数一样会拿到{currency: 'CNY', style: 'currency'}。

**Comment by GamesSoul** [comment]
> moneySymbol 设置为false 就会消失掉的

看了下源码  问题在 packages/field/src/components/Money/index.tsx 的 88 ～89行  88行

**Comment by WuJiY** [comment]
问题还存在吧
