### ISSUE TITLE
👑 [需求]EditableProTable 可编辑表格编辑状态下是否可以实现拖拽排序

### ISSUE THREAD

**Issue by czf0321** [ant-design/pro-components#3414]
### 🥰 需求描述

可编辑表格是否可以实现拖拽排序，能否帮忙做个实例

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30063100/128959363-54888cf6-646b-46ec-8fcc-6a386fe60dea.png)
![image](https://user-images.githubusercontent.com/30063100/128959403-5c1ccfd1-dda2-4845-b3c1-b9b8ac4ad92b.png)

**Comment by chenshuai2144** [comment]
可以的。不过数据要你自己想办法处理一下来，区别不大

**Comment by luopojianshi** [comment]
可编辑表格的拖拽排序，你实现了吗？

**Comment by 251205668** [comment]
> ### 🥰 需求描述
> 可编辑表格是否可以实现拖拽排序，能否帮忙做个实例
> 
> ### 🚑 其他信息
> ![image](https://user-images.githubusercontent.com/30063100/128959363-54888cf6-646b-46ec-8fcc-6a386fe60dea.png) ![image](https://user-images.githubusercontent.com/30063100/128959403-5c1ccfd1-dda2-4845-b3c1-b9b8ac4ad92b.png)

请问最后是怎么实现的呢

**Comment by yuan-ze** [comment]
有没有人实现过……

**Comment by Wesley-GONG** [comment]
如何实现？给个demo或代码片段啊

**Comment by seveneElevenup** [comment]
请问有实现吗

**Comment by seveneElevenup** [comment]
> 有没有人实现过……

有实现吗？

**Comment by whqgo** [comment]
?????? 莫名其妙的关了咋 所以到底有没有实现过的 啊 马勒戈壁的

**Comment by beikeliu** [comment]
可以看下我这个示例https://github.com/beikeliu/editable-sort-table
