### ISSUE TITLE
🧐Pro组件接管loading状态后，如果请求失败，会卡loading，这个要怎么处理呢

### ISSUE THREAD

**Issue by colorbitch** [ant-design/pro-components#3415]
### 🧐 问题描述

文档里没找到相关信息，现在请求失败就卡在loading，不知道怎么处理😂

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/8054331/128965888-784bd360-75f3-4ee4-9870-6bf44acea7aa.png)

**Comment by chenshuai2144** [comment]
throw 一个 error 出来，这样搞一下
```
onFinish={async (values) => {
              await handleSubmit(values as API.LoginParams);
            }}
```

**Comment by colorbitch** [comment]
> throw 一个 error 出来，这样搞一下
> 
> ```
> onFinish={async (values) => {
>               await handleSubmit(values as API.LoginParams);
>             }}
> ```
你好，不是很理解哈，现在我也是类似写法，但是不对：

```
const onFinish = async (values) => {
        const {username, password} = values;

        try {
            await sleep(500);
            const result = await request.get(API.login, {username: username, password: password});
        } catch (e) {
            return false;
        }
        return true;
    };

**Comment by chenshuai2144** [comment]
直接这个就好了

await request.get(API.login, {username: username, password: password})

**Comment by colorbitch** [comment]
> 直接这个就好了
> 
> await request.get(API.login, {username: username, password: password})

感谢回复，因为拿到这个请求结果的result之后，还有一些业务逻辑要处理，那这些逻辑是要放别处去做吗？

**Comment by chenshuai2144** [comment]
也可以的，只要保证是一个promise 然后有返回就好了

**Comment by colorbitch** [comment]
了解了，是之前请求异常的时候没有返回promise，非常感谢！
