### ISSUE TITLE
🐛[BUG]EditableProTable里valueType为checkbox时不能拿到正确的选中值数组

### ISSUE THREAD

**Issue by gracexiong** [ant-design/pro-components#3416]
### 🐛 bug 描述
EditableProTable里valueType为checkbox时不能拿到正确的选中值数组

### 💻 复现代码
https://codesandbox.io/s/ke-bian-ji-biao-ge-forked-ilroh?file=/App.tsx

### © 版本信息
 "react": ">=16.9.0",
    "@ant-design/pro-table": "2.47.1",
    "@ant-design/pro-field": "1.18.16",
    "@ant-design/pro-form": "1.33.1",
    "@ant-design/pro-card": "1.14.11",
    "antd": "4.x",
    "react-dom": ">=16.9.0"

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23145977/128978134-2b0e8e14-4f9e-494e-b66e-bbd4d584e4e8.png)

**Comment by chenshuai2144** [comment]
看起来是对的，能展开详细说说吗

**Comment by gracexiong** [comment]
> 看起来是对的，能展开详细说说吗

我选择是的 add和 del两个，但是在onSave方法里拿到的row数据是add、del、change、search四个
