### ISSUE TITLE
🐛[BUG]ProTable配置 copyable: true, ellipsis: true,失效，鼠标移动无法显示标题过长的内容

### ISSUE THREAD

**Issue by YC725968** [ant-design/pro-components#3417]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/51156342/128990992-695b36e5-9272-4f99-bdeb-d753c49064c4.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Kyseme** [comment]
pro-table 2.47.1 仍然存在这个问题 
![image](https://user-images.githubusercontent.com/22660458/129702334-ca4a0eb2-ddd3-4723-8eb2-88e93aed23f0.png)

  {
    title: '内容',
    dataIndex: 'text',
    width: 120,
    ellipsis: true,
    search: false,
  },

**Comment by Kyseme** [comment]
@ant-design/pro-table@2.47.1 仍然存在这个问题
