### ISSUE TITLE
layout中 menuRender怎么定义使用

### ISSUE THREAD

**Issue by Loomark** [ant-design/pro-components#3418]
使用的antd pro v5， 想自定义左侧菜单样式，看文档需要配置menuRender， 但是没有找到怎么写menuRender。 请求大同学给个模板，谢谢

**Comment by Loomark** [comment]
@chenshuai2144  求救大佬

**Comment by chenshuai2144** [comment]
在 app.tsx 中有layout的配置的

**Comment by chenshuai2144** [comment]
官网有相关的demo，你先自己debug一下吧。

**Comment by Loomark** [comment]
> 官网有相关的demo，你先自己debug一下吧。

嗯嗯 谢谢了 我先自己调下， 但是官网只是提了一下使用menuRender可以自定义菜单，但是没有展示它的用法

**Comment by Loomark** [comment]
> 官网有相关的demo，你先自己debug一下吧。

解决了，用了menuProps属性做的透传

**Comment by WilliamCheen** [comment]
怎么透穿的啊，请问能贴一下代码吗？

**Comment by lizhi9213** [comment]
> 怎么透穿的啊，请问能贴一下代码吗？

menuRender: (props: HeaderViewProps, defaultDom: React.ReactNode) => {
     //  ...custom code
     return defaultDom
},
