### ISSUE TITLE
🐛[BUG] pro-table 2.7.4 Localization Problem

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/pro-components#342]
### 🐛 bug 描述
I use to Ant design pro v5
When I change Lang setttings to en-EN, Pro table locale does not change from 'zh-CN' to 'en-EN', How can I solve this ?

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by xXAvoraXx** [comment]
The pro table is not detecting the languages ​​in the locales folder.

**Comment by xXAvoraXx** [comment]
still same problem

**Comment by johnnylc** [comment]
same problem in pro-table v2.6.3

**Comment by xXAvoraXx** [comment]
Is there any improvement?

**Comment by xXAvoraXx** [comment]
same problem in available version 2.7.4

**Comment by chenshuai2144** [comment]
ref https://github.com/ant-design/pro-components/pull/504

ref https://github.com/ant-design/pro-components/pull/507

**Comment by xXAvoraXx** [comment]
> ref #504
> 
> ref #507

what exactly means ?

**Comment by jncscr** [comment]
still same problem

**Comment by chenshuai2144** [comment]
fixed in 2021-06-03
