### ISSUE TITLE
🧐[问题]EditableProTable 在dataSource数据多，multiple模式下input框有明显延迟

### ISSUE THREAD

**Issue by NoManPlay** [ant-design/pro-components#3427]
### 🧐 问题描述

EditableProTable 在dataSource数据多，multiple模式下input框有明显卡顿延迟大于0.5s

### 💻 示例代码
https://codesandbox.io/s/nostalgic-raman-juivz

**Comment by chenshuai2144** [comment]
不要搞太多或者 shouldCellUpdate  来一发



shouldCellUpdate | 自定义单元格渲染时机 | (record, prevRecord) => boolean | - | 4.3.0
-- | -- | -- | -- | --

**Comment by NoManPlay** [comment]
> 不要搞太多或者 shouldCellUpdate 来一发
> 
> shouldCellUpdate	自定义单元格渲染时机	(record, prevRecord) => boolean	-	4.3.0



> 不要搞太多或者 shouldCellUpdate 来一发
> 
> shouldCellUpdate	自定义单元格渲染时机	(record, prevRecord) => boolean	-	4.3.0
 请问EditableProTable中使用shouldCellUpdate是要在renderFormItem中封装使用，还是在formItemProps中配置使用

**Comment by NoManPlay** [comment]
> 不要搞太多或者 shouldCellUpdate 来一发
> 
> shouldCellUpdate	自定义单元格渲染时机	(record, prevRecord) => boolean	-	4.3.0

请问EditableProTable中使用shouldCellUpdate是要在renderFormItem中封装使用，还是在formItemProps中配置使用

**Comment by chenshuai2144** [comment]
shouldCellUpdate 是列的配置

**Comment by NoManPlay** [comment]
> shouldCellUpdate 是列的配置

列里面之前也试过了，protable里面不生效，而且procolumns类型里面好像还没加上

**Comment by chenshuai2144** [comment]
是支持的，我测试过。
