### ISSUE TITLE
🐛[BUG]表单默认值-valueEnum失效

### ISSUE THREAD

**Issue by zhouzyc** [ant-design/pro-components#3429]
### 🐛 bug 描述
表单默认赋值

### 🏞 期望结果
能正确显示

### 💻 复现代码
https://codesandbox.io/s/biao-dan-mo-ren-zhi-valueenumshi-xiao-tfei9

**Comment by chenshuai2144** [comment]
看一下控制台

```
Warning: initialValues 只在 form 初始化时生效，如果你需要异步加载推荐使用 request，或者 initialValues?<Form/>:null 
Warning: The initialValues only take effect when the form is initialized, if you need to load asynchronously recommended request, or the initialValues?<Form/>:null 
```

**Comment by zhouzyc** [comment]
如果你需要异步加载推荐使用 request.
如果我没理解错，我demo里面是运行的:
request={async (params: any) => {
          return {
            datetime: "2006-02-03 21:30:57",
            description: "确天确年",
            id: 262,
            status: 2,
            title: "确天确年",
            type: 2
          };
        }}
我还是不太明白推荐使用request还是不行。

**Comment by zhouzyc** [comment]
> 看一下控制台
> 
> ```
> Warning: initialValues 只在 form 初始化时生效，如果你需要异步加载推荐使用 request，或者 initialValues?<Form/>:null 
> Warning: The initialValues only take effect when the form is initialized, if you need to load asynchronously recommended request, or the initialValues?<Form/>:null 
> ```
> 
> 另外 2 和 "2" 是不同的，要注意一下

如果你需要异步加载推荐使用 request.
如果我没理解错，我demo里面是运行的:
request={async (params: any) => {
          return {
            datetime: "2006-02-03 21:30:57",
            description: "确天确年",
            id: 262,
            status: 2,
            title: "确天确年",
            type: 2
          };
        }}
我还是不太明白推荐使用request还是不行。

**Comment by chenshuai2144** [comment]
更新一下版本。
你的问题是  2 和 "2"  的问题

**Comment by zhouzyc** [comment]
好的谢谢，我在看看

趾蝣一粷`~怼卜戚~我~愛`YOU


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月13日(星期五) 下午3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 🐛[BUG]表单默认值-valueEnum失效 (#3429)





 
更新一下版本。
 你的问题是  2 和 "2"  的问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
