### ISSUE TITLE
🧐[问题] ProList是不支持翻页和选中同时使用吗？

### ISSUE THREAD

**Issue by BoWang816** [ant-design/pro-components#3430]
### 🧐 问题描述

设置了翻页，同时设置了选中，但是如果选择第一页，翻页后再选中，第一页数据会丢失，是因为不支持这个功能吗？

### 🚑 其他信息

![pic](https://user-images.githubusercontent.com/26587649/129173431-f034aae2-d1c7-4fdf-86c6-ad3a8254c645.gif)

**Comment by chenshuai2144** [comment]
preserveSelectedRowKeys | 当数据被删除时仍然保留选项的 key | boolean | - | 4.4.0
-- | -- | -- | -- | --
