### ISSUE TITLE
pro-table  initialValues 只在 form 初始化时生效，如果你需要异步加载推荐使用 request，或者 initialValues ? <Form/> : null  

### ISSUE THREAD

**Issue by ddbinliang** [ant-design/pro-components#3431]
pro-table  2.30.8 设置表格搜索项报警告 initialValues 只在 form 初始化时生效，如果你需要异步加载推荐使用 request，或者 initialValues ? <Form/> : null  

![image](https://user-images.githubusercontent.com/26667620/129200603-61c74bab-2a0e-464e-86a3-140134e06c1f.png)
![image](https://user-images.githubusercontent.com/26667620/129200682-b2632551-6bb0-4371-b6c1-1deb631ce1ef.png)

我是用仓库的代码，本地运行也会报这个警告，这个要怎么处理或者关掉？

**Comment by chenshuai2144** [comment]
这个修掉了，有点误报。更新依赖好了

**Comment by biggun1860** [comment]
pro-table 2.48.0 目前的最新版还是有这个问题

**Comment by codedart2018** [comment]
> pro-table 2.48.0 目前的最新版还是有这个问题

今天晚上删除了node_modles重新安装全部都是这个报错。　我把form替换成了　ant 这边的就没有问题。用proFrom就有问题。
proTable 列表也是
 "@ant-design/pro-form": "^1.18.3",
"@ant-design/pro-table": "^2.30.8",

**Comment by codedart2018** [comment]
> pro-table 2.48.0 目前的最新版还是有这个问题

我暂时固定了版本。太坑了，一开始我还以为我写的不规范导致的。后面我去看别的页面也有问题，我才发现是他们版本问题。坑死了　！固定死版本！后面再说
  "@ant-design/pro-form": "1.33.0",
  "@ant-design/pro-table": "2.47.0",
