### ISSUE TITLE
🧐[问题]EditableProTable实时编辑通过request请求的数据editableKeys该如何处理呢

### ISSUE THREAD

**Issue by ai180508** [ant-design/pro-components#3433]
### 🧐 问题描述

实时编辑通过request请求的数据editableKeys该如何处理呢，试过几个地方处理表格都是不可编辑状态

### 💻 示例代码

<EditableProTable
      bordered
      columns={columns}
      actionRef={actionRef}
      rowKey="onlyKey"
      scroll={{ y: '60vh' }}
      request={(params) => {
        const data = {
          ...params,
          orgId,
        };
        return queryHz({ ...data });
      }}
      recordCreatorProps={false}
      postData={(data) => {
        console.log('data', data);
        setEditableRowKeys(() => data.map((item) => item.id));
        return data;
      }}
      editable={{
        type: 'single',
        editableKeys,
        onValuesChange: (record, recordList) => {
          console.log(recordList);
        },
        onChange: setEditableRowKeys,
      }}
      pagination={{
        size: 'small',
        showQuickJumper: true,
        showSizeChanger: true,
        onChange: () => setSelectedKeys([]),
        showTotal: (total) => '共' + `${total}` + '条',
      }}
    />

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/77037794/129303149-f8933da1-49ab-4562-b382-256310278757.png)

![image](https://user-images.githubusercontent.com/77037794/129303294-dcfb4871-be99-45f1-8295-4e39469fffc1.png)

**Comment by chenshuai2144** [comment]
在 request 种处理，要注意注意一下rowkey，不能一个用id，一个用onlyKey
