### ISSUE TITLE
🐛[BUG] [antd: Table] `dataSource` length is less than `pagination.total` but large than `pagination.pageSize`. Please make sure your config correct data with async mode. 

### ISSUE THREAD

**Issue by happyhuizai** [ant-design/pro-components#3436]
### 🐛 bug 描述

警告信息：[antd: Table] `dataSource` length is less than `pagination.total` but large than `pagination.pageSize`. Please make sure your config correct data with async mode. 
### 📷 复现步骤

1、pagination初始数据，current为1，pageSize为20，request 后返回20条数据
2、切换pageSize为10，控制台出现警告信息

经查[源码](https://github1s.com/ant-design/pro-components/blob/HEAD/packages/table/src/Table.tsx) 
发现经过1，2 步骤，命中了条件1 
并没有走条件2清空dataSource，而dataSource的长度比pageSize大，所以出现警告

![image](https://user-images.githubusercontent.com/29218617/129312881-9de28ee4-acf1-441f-8fa7-f87fbb26239f.png)

### © 版本信息

- pro-table 版本: [2.43.4]
- umi 版本: [3.5.5]
- 浏览器环境: Chrome
- 开发环境 [mac OS]

**Comment by happyhuizai** [comment]
。。。

**Comment by chenshuai2144** [comment]
这个就是字面意思，因为切换的时候data还在。
data.length > total 导致的，切换完就好了，可以先忽略一下。

设置到setstate时序的事情，搞起来比较麻烦

**Comment by anjing0524** [comment]
什么时候可以解决啊，大佬 @chenshuai2144

**Comment by chenshuai2144** [comment]
没必要解决，warning 也不影响。

解决成本又非常高，要自定义antd的表格

**Comment by SilentFlute** [comment]
@chenshuai2144 大佬, 我这也是遇到这个问题, 但已经是一个错误信息了, 虽然还是叫`warning`但在`chrome`里面是红色的`error`了, 过滤级别选成`Errors only`它也会出现:
![image](https://user-images.githubusercontent.com/28900312/144174495-8df3ca74-8468-428b-bf1e-ea73086a9919.png)
切换完页码, 然后比如查询表单被修改了, 需要重新查询, 使用`formRef.current?.submit();`, 此时就不会发送请求了...

新的页面使用`class`的形式写, 将`ProTable`用作受控的倒是没有这个问题, 但是相对繁琐, 毕竟好多东西都要自己实现, 但这还好, 蛋疼的是以前的`hooks`形式的写法比较多, 改起来就蛋疼了...

**Comment by SilentFlute** [comment]
这里贴一个我自己的解决方法: 无论是`class`形式的还是`hooks`的代码, 都改成`受控组件`的形式, 并且不再使用`formRef.current?.submit();`和`actionRef.current?.reload();`去查询数据和重查数据, 全部做成受控的, 查数据统一使用`handleRetrieveTableData`去请求

`handleRetrieveTableData`:
```
const { current } = formRef;
const { getFieldsValue } = current;
const fieldsValue = getFieldsValue();

// 使用fieldsValue和(或)state中设置的参数去请求数据

// 将请求回来的数据设置到state中
```

`handleTableOnChange`:
```
// 清空dataSource(重点!!!!!!!!!!!!!!!!!!!!!)

// 将table onChange之后的相关参数设置到state中

// 然后再请求数据, 请求数据可以在componentDidUpdate中做或者上面setState的回调中做
```

```
<ProTable
  rowKey="id"
  formRef={formRef}
  actionRef={actionRef}
  columns={this.columns}
  loading={tableLoading}
  dataSource={tableData.rows}
  onReset={this.handleOnReset}
  onSubmit={this.handleOnSumbit}
  pagination={{
    current: page,
    total: tableData.count
  }}
  options={{
    fullScreen: false,
    reload: this.handleTableRefresh
  }}
  search={{ defaultCollapsed: false }}
  rowSelection={{ selections: false }}
  toolBarRender={this.handleRenderToolBar}
  tableAlertRender={this.handleRenderBatchToolBarLeft}
  tableAlertOptionRender={this.handleRenderBatchToolBarRight}
  onChange={(pagination, filters, sorter, extra) => {
    this.handleTableOnChange({pagination, filters, sorter, extra})
  }}
/>
```
```
<ProTable
  rowKey="id"
  formRef={formRef}
  columns={columns}
  actionRef={actionRef}
  dataSource={tableData}
  pagination={{
    total,
    pageSize,
    current: page
  }}
  onReset={handleOnReset}
  onSubmit={handleOnSumbit}
  options={{
    fullScreen: false,
    reload: handleTableRefresh
  }}
  search={{ defaultCollapsed: false }}
  rowSelection={{ selections: false }}
  toolBarRender={handleRenderToolBar}
  tableAlertRender={handleRenderBatchToolBarLeft}
  tableAlertOptionRender={handleRenderBatchToolBarRight}
  onChange={(pagination, filters, sorter, extra) => {
    handleTableOnChange({ pagination, filters, sorter, extra })
  }}
/>
```
后面的代码是`hooks`形式的, 我传了`pageSize`进去, 也可以不传, 第一个`class`形式的就没传, 关键代码在于`onChange`, 就是我们点表格右下角的`xx条/页`的时候, 在`handleTableOnChange`中将`dataSource`置空, 然后再走请求数据的逻辑就行了

这个错是因为我们修改`pageSize`的时候, `pageSize`变了, 但`dataSource`没有被清空 没变, 这使得二者大小不一样, 因此我们手动清空`dataSource`就行了, 也就是做成受控的

**Comment by xieyangxing** [comment]
> 什么时候可以解决啊，大佬 @chenshuai2144

获取数据后，表格赋值前，进行置空数据

**Comment by blackrock33** [comment]
我把Table和Pagination 分开解决了这个报错，用单独<Pagination />组件，不用Table内置的 Pagination
