### ISSUE TITLE
压缩的时候 报 'fast-deep-equal/es6/react' 

### ISSUE THREAD

**Issue by tianwawawa** [ant-design/pro-components#3438]
### © 版本信息

- Protable 2.48.0

- 浏览器环境 chrom
- 开发环境 [e.g. mac OS]

**Comment by calefy-chen** [comment]
需要在.umrc.ts中修改配置，来支持IE11：
`nodeModulesTransform: {
    type: 'none',
    // 下面两个包有ie11不支持的语法，需要做编译
    exclude: ['@umijs/use-params', 'fast-deep-equal'],
  }`
