### ISSUE TITLE
👑 [需求] ProTable的列设置功能，能不能加个可控属性

### ISSUE THREAD

**Issue by yaoguoba** [ant-design/pro-components#344]
### 🥰 需求描述

可以默认控制列的初始化隐藏。

![image](https://user-images.githubusercontent.com/18393410/91653471-d6257700-ead3-11ea-86b6-b0bb7f23ed36.png)

### 🧐 解决方案

可不可以在Column的属性中加一个'hideInDefault'的属性，可以控制默认不显示，但是可以通过列设置来显示。

**Comment by chenshuai2144** [comment]
已经支持了，可以看看 demo

https://procomponents.ant.design/components/table#%E5%8F%97%E6%8E%A7%E7%9A%84%E5%88%97%E6%98%BE%E7%A4%BA%E9%9A%90%E8%97%8F

https://procomponents.ant.design/_demos/columns-state-map

**Comment by sinpor** [comment]
> 已经支持了，可以看看 demo
> 
> https://procomponents.ant.design/components/table#%E5%8F%97%E6%8E%A7%E7%9A%84%E5%88%97%E6%98%BE%E7%A4%BA%E9%9A%90%E8%97%8F
> 
> https://procomponents.ant.design/_demos/columns-state-map

这两个链接的demo都没找到。。

写了个[demo](https://codesandbox.io/s/protablecolumnsstatedemo-lq6gf?file=/src/App.js)

**Comment by chenshuai2144** [comment]
提个pr，放到官网上去？
