### ISSUE TITLE
protable设置scroll x时有children的表头会出现重叠🐛[BUG] 

### ISSUE THREAD

**Issue by HappyManYun** [ant-design/pro-components#3441]
### 🐛 bug 描述

设置scroll x时横向滚动有children的表头会出现重叠

📷 复现步骤
https://codesandbox.io/embed/cha-xun-biao-ge-forked-5j25r?fontsize=14&hidenavigation=1&theme=dark

🏞 期望结果
表头不重叠

💻 复现代码
https://codesandbox.io/embed/cha-xun-biao-ge-forked-5j25r?fontsize=14&hidenavigation=1&theme=dark

🚑 其他信息
我观察到children里position属性是relative的表现正常，stick的表现异常
![image](https://user-images.githubusercontent.com/25782292/129370475-b63f5d76-15d8-4c84-acc7-ba0a610da595.png)

**Comment by HappyManYun** [comment]
那个issues是我提的忘记写标题了，所以重新提了这个

**Comment by chenshuai2144** [comment]
不能这样用的，要把 fixed 放到最左边，而且 带children 也要配置，antd 对 分组table支持的不是很好。

**Comment by HappyManYun** [comment]
![image](https://user-images.githubusercontent.com/25782292/129859550-a183f255-24e9-4f5e-849b-6e937bd5c5dc.png)
只有第一列fixed，而且fixed是最左边的。我用and的table就没问题，protable会出现这种问题

**Comment by chenshuai2144** [comment]
看了下是继承的问题。
