### ISSUE TITLE
🧐[问题]ProFormSelect设置showSearch，使用request获取数据，默认的查询字段是keyWords，如何修改这个字段名称？

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/pro-components#3443]
### 🧐 问题描述

🧐[问题]ProFormSelect设置showSearch，使用request获取数据，默认的查询字段是keyWords，如何修改这个字段名称？

### 💻 示例代码

![image](https://user-images.githubusercontent.com/5431843/129430780-203ecc22-ac71-4e0a-a7b5-4d23278b94c8.png)
queryUnions函数接收到的参数，除了status=1之外，还是有keyWords=输入的值，怎么把keywrods这个字段名称给修改下
### 🚑 其他信息
pro-form版本号1.18.3

**Comment by drizzlesconsin** [comment]
这个似乎不支持修改，可以这样：
```ts
request={async ({ keyWords }) => await query({ name: keyWords })}
```
