### ISSUE TITLE
🧐关于ProForm的onFinish重复提交（tab移动到按钮后回车）

### ISSUE THREAD

**Issue by ygxw** [ant-design/pro-components#3451]
### 🧐 问题描述

搜索了下，看到了之前有这个issue：#3147
虽然这个问题出现的几率很小，但是肯定会有这个概率。如果发生这种情况，一些场景下会造成数据的重复。
虽然我可以在页面内想办法控制，但是这样我需要每次都去人为控制。官方能不能评估下，通过ant本身来防止这种情况发生。

### 💻 示例代码
官方demo，或者任何proform的页面就能重现该问题。

**Comment by chenshuai2144** [comment]
这个的解法已经发布了的样子

**Comment by ygxw** [comment]
感觉是loading前就提交了两次，我在服务端故意堵塞3秒，然后发现前端也是停顿了3秒。。说明前端是并发一起提交的。。。你可以去你们官方的“文档->组件”，里面的所有实例中，tab移动到按钮上回车，都会提交2次。
