### ISSUE TITLE
🐛[BUG]LightFilter组件的onValuesChange方法在未开启collapse的情况下,返回值不正确

### ISSUE THREAD

**Issue by ILoveChy** [ant-design/pro-components#3452]
### 📷 复现步骤
假设有个筛选属性为a,先选中a为某值,再点击右上角的删除的叉子,onValuesChange返回的changedValues为空对象{}
但是如果开启了collapse属性,上述操作返回值为正确的{a:{}}

### 🏞 期望结果
我不知道是不是正常的,如果非正常onValuesChange不受其他属性影响才对;
如果正常,那当我关闭collapse属性时,删除操作的返回值需要拿到key是什么,方便后续的redux操作,如果有其他属性方法可以得到请告知

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by tAQiAN** [comment]
同问

**Comment by chenshuai2144** [comment]
来个gif吧，没有看懂

**Comment by ILoveChy** [comment]
_**开启collapse**_


![1](https://user-images.githubusercontent.com/37863087/130035899-e38c75a1-65dc-4175-a2a4-e8feb8087672.png)
![2](https://user-images.githubusercontent.com/37863087/130035919-208ca7fe-7262-47a5-b2d4-85fda8232dba.png)

**_不开_**


![3](https://user-images.githubusercontent.com/37863087/130036045-b7f157a8-42d7-46bd-835d-488387ff8b7d.png)
![4](https://user-images.githubusercontent.com/37863087/130036048-2dedeaa8-fb78-4704-82ae-9096c2ae1e61.png)


@chenshuai2144

**Comment by chenshuai2144** [comment]
来个demo

**Comment by ILoveChy** [comment]
@chenshuai2144  https://codesandbox.io/s/proform-list-forked-d40gf

**Comment by ILoveChy** [comment]
好像新的版本开不开启collapse属性,onValuesChange返回值都是空对象了😂,虽然加上omitNil={false}能解决这个问题,但是还是没有理解为什么默认要过滤掉值为null或者undefined的属性值,删除的时候不是很方便.

**Comment by chenshuai2144** [comment]
有兴趣来个pr吗？

**Comment by ILoveChy** [comment]
[https://github.com/ant-design/pro-components/issues/1005](url)
看了下当时omitNil属性默认true的原因,你们后端认为''是报错,只是我这边业务需要知道删除了什么属性,既然有omitNil了,所以这个改不改对我其实也影响不大,顶多就是少写一行属性.
