### ISSUE TITLE
🐛[BUG] Using ~ for @import is deprecated in webpack

### ISSUE THREAD

**Issue by slaypni** [ant-design/pro-components#3457]
### 🐛 bug 描述

The use of `~` for `@import` in less files is deprecated in webpack.

https://webpack.js.org/loaders/less-loader/#webpack-resolver

Especially in parcel 2, `parcel build` fails if a package is using pro-components since it dropped the support of `~`.

### 🏞 期望

Drop `~` from `@import` as it is recommended.

**Comment by chenshuai2144** [comment]
This discussion is opposed, umi has not yet sent support.

dup of https://github.com/ant-design/pro-components/issues/1933
