### ISSUE TITLE
EditableProTable如何新增多行可编辑数据🧐[问题]

### ISSUE THREAD

**Issue by a330202207** [ant-design/pro-components#3458]
### 🧐 问题描述
我有一个ProForm表单，里面有两个表单项，一个是新增按钮，一个是EditableProTable，我想通过点击新增按钮来控制EditableProTable中可以编辑的数据，但是现在提示只能只能新增一行(EditableProTable可以通过actionRef.current?.addEditRecord(row)  来触发新建行)

我的期望：
点击新增按钮以后EditableProTable出现一条可编辑数据，再次点击，再次出现一条可编辑数据

**Comment by chenshuai2144** [comment]
通过 dataSource 和 editorRowKeys 自己拼一下吧，
同时新增多行需要复杂的逻辑，所以protable 没有实现
