### ISSUE TITLE
关于ProField-Percent及antd的InputNumber🧐[问题]

### ISSUE THREAD

**Issue by yangger6** [ant-design/pro-components#3459]
### 🧐 问题描述

在尝试用vue仿照pro-components的`pro-field`的`percent`组件的时候，意外发现使用`???`作为prefix测试组件时，发现无法触发`InputNumber`的`formatter`事件, 可能是因为pro-field-percent组件paser事件的正则判断有问题。

### 💻 示例代码

[codesandbox示例](https://codesandbox.io/s/ge-shi-hua-zhan-shi-antd-4-16-12-forked-59nri?file=/index.js)

暂时解决方案（用字符串替换代替正则匹配prefix）: 

```
// before
parser: function parser(value) {
        return value ? value.replace(new RegExp(`\\${prefix}\\s?|(,*)`, 'g'), '') : '';
},
// after
parser: function parser(value) {
        return value ? value.replace(prefix, '').replace(/\s|,/g, "")
},
```

## 在prefix为`???`的时候运行效果

![image](https://user-images.githubusercontent.com/23329645/129700201-6c56b331-0873-4538-a28a-654a9c5db728.png)

**Comment by yangger6** [comment]
补充一下： pro-field-percent的代码正常是因为antd的InputNumber组件parser函数返回不正确的结果导致formatter只会运行一次，所以pro-field-percent才会运行正常，这一点我对比了很多次才发现，因为antdv的formatter即使paser返回错误的结果也会运行

**Comment by chenshuai2144** [comment]
这个要不要去antd 提一下。

**Comment by yangger6** [comment]
> 这个要不要去antd 提一下。

我觉得应该是`pro-field-percent`的正则要修改一下, 不过用`???`做prefix确实是刁钻了：）

调试了一下`rc-input-number`的源码, 在 parser的正则有问题没返回数字为`NaN`情况下， 不会触发`triggerValueUpdate`方法
，也就不会触发formatter，所以`pro-field-percent`的formatter才会以bug的形式“正常展示”。

```javascript
  var collectInputValue = function collectInputValue(inputStr) {
    debugger
    recordCursor(); // Update inputValue incase input can not parse as number

    setInternalInputValue(inputStr); // Parse number

    if (!compositionRef.current) {
      var finalValue = mergedParser(inputStr);
      var finalDecimal = getMiniDecimal(finalValue);

      if (!finalDecimal.isNaN()) { // parser返回非数字的情况下不会进入下面这一行⚠️
        triggerValueUpdate(finalDecimal, true);
      }
    }
  }; // >>> Composition
```

**Comment by chenshuai2144** [comment]
我不是很擅长正则，你有兴趣搞个pr吗？

**Comment by yangger6** [comment]
> 我不是很擅长正则，你有兴趣搞个pr吗？


prefix由任意字符串组成`218937kjdhaskjh???? @#@# da)!@U#HN`

当用户键入数字时示例: '218937kjdhaskjh???? @#@# da)!@U#HN 123,456,203'

```
"???1? 12312 41231d *)@!^#^ ????  12312,21312,123,3123,3s".replace(/.*\s|,/g, '') // 123122131212331233s
```

应该没问题  明天弄点测试用例再提pr吧
