### ISSUE TITLE
🐛[BUG]pro-table的search表单，如果有多行的情况，并且第一行有一个字段占据了2，则操作按钮被挤到第二行。

### ISSUE THREAD

**Issue by fayeah** [ant-design/pro-components#3468]
### 🐛 bug 描述

使用了pro-table这个ui库，在用search表单的时候，有个字段需要设置为占据2行：colSize: 2，然后表单本身有多行，在最初折叠的情况下，操作按钮被下移到第二行，比较占用空间。如果不设置colSize: 2，操作按钮是在第一行没有问题的。

### 📷 复现步骤

引入pro-table，使用该组件，对某个搜索字段设置为colSize: 2，此时查询操作按钮下移。

### 🏞 期望结果

操作按钮被下移，而期望操作按钮还在第一行。

### 💻 复现代码

```
const columns: ProColumns<any>[] = [
    {
      title: 'aa',
      colSize: 2,
    },
    {
      title: 'b',
    },
    {
      title: 'c',
    },
    {
      title: 'd',
    },
    {
      title: 'e',
    },
    {
      title: 'f',
    },
    {
      title: 'g',
    },
    {
      title: 'h',
    },
  ];

<ProTable<TJob>
        columns={columns}
        editable={{
          type: 'multiple',
        }}
        rowKey="name"
        search={{
          span: 4,
          labelWidth: 'auto',
          collapseRender: collapsed => (
            <>{collapsed ? <DownOutlined /> : <UpOutlined />}</>
          ),
          className: styles.searchContainer,
        }}
      />
```

### © 版本信息

- Ant Table 版本: 2.40.1
- umi 版本: 无
- 浏览器环境:chrome
- 开发环境 : mac OS

### 🚑 其他信息

<img width="1427" alt="WeChatWorkScreenshot_04031542-0b58-4bab-86d9-aae6bf22ce3d" src="https://user-images.githubusercontent.com/29644978/129851648-bfcafb54-4524-431e-b106-04305dff2080.png">

**Comment by chenshuai2144** [comment]
一行只有24个格子放不下就会移到新的行呢

**Comment by fayeah** [comment]
> 一行只有24个格子放不下就会移到新的行呢
但是没有设置就是在一行的额，那如果我要实现怎么做呢？

**Comment by chenshuai2144** [comment]
span 配置一下，让一行多放点。



span | 表单项宽度 | number[0 - 24]
-- | -- | --



你可以span 设置为3

**Comment by fayeah** [comment]
设置span的话，一行确实多放了，但那是后面的col放进来了，操作按钮依然还在第二行。除非的话，就是把span设置尽可能小，将所有的搜索字段都放在一行，操作按钮才有可能被移到第一行。但是这样的话样式不太行了就。
