### ISSUE TITLE
🧐[问题] stepsForm怎么在步骤之间通信？

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/pro-components#3469]
### 🧐 问题描述

譬如说steps有三步，第一步中有个form表单，其中一个表单name为goal；
点击下一步后，到如何拿到第一步的表单字段goal，来控制第二部的某些表单显示与否；就像antd的Form的shouldUpdate

### 💻 示例代码
`  <StepsForm>`
`<StepsForm.StepForm name="step1" title="基础策略" labelCol={{span: 4}} layout={"horizontal"} >`
  `<Form.Item label={"投放目标"} name={"goal"}>`
           ` <Radio.Group>`
             ` <Radio value={1}>转化量</Radio>`
             ` <Radio value={2}>点击量</Radio>`
             ` <Radio value={3}>展示量</Radio>`
         `   </Radio.Group>`
      `    </Form.Item>`
` </StepsForm.StepForm>`
  `<StepsForm.StepForm name="step2" title="出价与预算" labelCol={{span: 4}} layout={"horizontal"}>`
          `怎么在第二步，根据第一步的goal字段动态显示该显示的东东`
 `</StepsForm.StepForm>`
`</StepsForm>`
### 🚑 其他信息
![image](https://user-images.githubusercontent.com/30942709/129853565-355f2805-bfee-4b92-8c9b-0349de3a41dd.png)
![image](https://user-images.githubusercontent.com/30942709/129853722-91524339-415f-4781-8f59-0b3061df65b5.png)

**Comment by ISBN9527** [comment]
@chenshuai2144 请各位大佬赐教，急！

**Comment by chenshuai2144** [comment]
`<StepsForm.StepForm onFinish={e=>console.log(e)}/>`

也有onFinish的，你可以在里面把数据存下来

**Comment by ISBN9527** [comment]
哥，还有别的办法吗？那我编辑表单的时候也还需要setState下数据

**Comment by chenshuai2144** [comment]
因为跨表单了，现在也没有比较好的办法。

> 那我编辑表单的时候也还需要setState下数据

可以用 onValueChaneg
