### ISSUE TITLE
👑 [需求] ProList可以支持像table一样的全选功能吗？

### ISSUE THREAD

**Issue by helenschen** [ant-design/pro-components#3470]
### 🥰 需求描述

像table一样最上面有个可以全选的checkbox

![F6DE1D8D-67B6-4048-A35B-80D20CC7C736](https://user-images.githubusercontent.com/53027032/129854079-71b88554-1a45-4da1-9f9f-117ec2e9d426.png)

**Comment by chenshuai2144** [comment]
估计要自己实现了一下了，我这里没法支持，因为list的没有header的
