### ISSUE TITLE
🧐[问题] ProTable的rowSelection的事件onSelectNone什么情况下触发?

### ISSUE THREAD

**Issue by CaicoLeung** [ant-design/pro-components#3472]
### 🧐 问题描述

看pro-table的声明类型, rowSelection有个onSelectNone事件, 按字面意思应该是点击"取消选择"时触发, 但是没有触发

### 💻 示例代码
![image](https://user-images.githubusercontent.com/36806569/129864247-fa47cd6c-411c-485c-83c7-d02ca6cf362e.png)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/36806569/129864473-69fbe7b8-2b1d-4d50-a5a8-1e1cb873be7c.png)

**Comment by chenshuai2144** [comment]
这个是内部使用的，外部不支持使用。你可以看看源码。用起来估计有坑

**Comment by CaicoLeung** [comment]
自行接管selectedRowKeys后, 点击取消选择怎么实现可控?

**Comment by chenshuai2144** [comment]
是个setState 你想怎么干就怎么干
