### ISSUE TITLE
pro-table form 中设置valueType=dateRange ，表现异常的问题

### ISSUE THREAD

**Issue by jockey100332** [ant-design/pro-components#348]
### 🐛 bug 描述
在初始化完毕后，聚焦时会一瞬间展示一下值，默认是空的展示

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
"@ant-design/pro-table": "^2.3.5",

**Comment by chenshuai2144** [comment]
详细一点？  你是指valueType 设置为 空吗

**Comment by jockey100332** [comment]
> 详细一点？ 你是指valueType 设置为 空吗

```
{
      title: '时间筛选',
      dataIndex: 'dateRange',
      valueType: 'dateRange',
      hideInTable: true
    },
```
这是我编写的代码，
1. 在鼠标聚焦该formQuery时，在input框内会瞬间出现一个时间值，此时对时间卡片是未做选择的。 
2. 选择后进行查询结果，再次清空该项选择的数值进行查询，在request 的params 中 会出现 dateRange = null 的参数。


antd: "^4.6.1"
@ant-design/pro-table: "^2.3.5",

**Comment by chenshuai2144** [comment]
复现不了，是不是 antd 的版本问题？

**Comment by jockey100332** [comment]
> 复现不了，是不是 antd 的版本问题？

antd 版本我已经做了升级，但是还是存在该问题。 在prod 的模式下不存在问题1，  在dev 模式下 问题1，2 都存在

**Comment by chenshuai2144** [comment]
可能是这个的问题 https://github.com/ant-design/pro-components/pull/382

**Comment by qyq1114** [comment]
请问这个问题是怎么解决的？
