### ISSUE TITLE
自定义菜单的 icon 无法使用本地图片

### ISSUE THREAD

**Issue by Pzx1997** [ant-design/pro-components#3482]
### 🧐 问题描述
自定义菜单的 icon 无法使用本地图片

直接引入本地图片使用报错， 我看文档只有使用antd自带的icon 和 iconfont 。 
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/71321033/130005780-103b25d7-8419-4eb2-a7e9-5c0ef2e66527.png)

**Comment by chenshuai2144** [comment]
用cdn是可以的，不过没有选中效果了。

你还是用的iconfont 吧


文档的问题可以来个pr。很快的。
