### ISSUE TITLE
🐛[BUG] 面包屑父级菜单应为不可点击，看起来是灰色的，实际是可点击，跳到404页

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#3484]
### 🐛 bug 描述

![QQ浏览器截图20210819144945](https://user-images.githubusercontent.com/3166799/130021657-30ad3b9b-f036-4c26-ac0f-53288156a454.png)

**Comment by chenshuai2144** [comment]
你配置一下重定向，或者手动render一下，因为这个是自动生成的。
