### ISSUE TITLE
🐛[BUG] ProFormSwitch 指定 width="md" 无效

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#3486]
### 🐛 bug 描述

````
<ProFormSwitch width="md" name="is_multiple_login" label="多端同时登录" />
<ProFormSwitch width="md" name="is_mfa" label="MFA身份认证" />
````
![QQ浏览器截图20210819162244](https://user-images.githubusercontent.com/3166799/130034567-7628465e-c23f-41f8-931a-b046930121f3.png)

**Comment by chenshuai2144** [comment]
这东西也要整这么宽吗？

它外面没有包东西，你想实现什么功能？

**Comment by hihuangwei** [comment]
> 这东西也要整这么宽吗？
> 
> 它外面没有包东西，你想实现什么功能？

不对齐，不美观呀

**Comment by chenshuai2144** [comment]
这叫错落有致

**Comment by hihuangwei** [comment]
可以不指定width时，让它错落有致🤔

**Comment by chenshuai2144** [comment]
我打了bug的标签但是我没想好怎么修复一下。你有兴趣来个pr吧

**Comment by chenshuai2144** [comment]
看起来这个不是个严重的问题
