### ISSUE TITLE
🧐[小提示] pro-table v2.6.1  valueType: 'dateRange'时，columns有无key 造成的影响，要注意了！

### ISSUE THREAD

**Issue by dmdoit** [ant-design/pro-components#349]
### 🧐 问题描述

valueType: 'dateRange'时，
如果columns没有给key值，search条件会变成 ['YYYY-MM-DD HH:mm:ss', 'YYYY-MM-DD HH:mm:ss']
如果columns给了key值，search条件就是正常的  ['YYYY-MM-DD', 'YYYY-MM-DD']

**Comment by chenshuai2144** [comment]
看起来是个很严重的bug 

应该全部是 `['YYYY-MM-DD', 'YYYY-MM-DD']`

**Comment by WoodsLiu** [comment]
@chenshuai2144 #375 提了issue, 找到了原因
