### ISSUE TITLE
🧐[问题]ProTable查询表单的参数如何受控来实现列表页搜索参数缓存？

### ISSUE THREAD

**Issue by JoernLee** [ant-design/pro-components#3490]
### 🧐 问题描述
我这边为了作基于ProTable实现的列表页页面缓存功能，需要记忆搜索参数，翻了官方文档后计划通过改变params字段来实现，在request方法时拿到最新的searchParams，然后缓存住，back列表页时传入ProTable中来实现。
但是测试下来似乎没有用，不知道为何request方法回调中拿到的seachParams不是最新的，而是当前受控状态？
不知道有没有大大遇到过类似的场景或者是不是我的使用方式有问题？

**Comment by chenshuai2144** [comment]
因为request是闭包的，你可以把值 扔给form，然后触发submit。

或者直接用protable 内置的同步参到url的功能。
