### ISSUE TITLE
🐛[BUG] ProTable Columns ellipsis浏览器缩放样式穿透

### ISSUE THREAD

**Issue by luobinhang** [ant-design/pro-components#3503]
### 🐛 bug 描述

ProTable Columns设置ellipsis浏览器缩放的情况下会发生文字穿透的样式问题，原因是使用了 Typography.Text
 ellipsis属性设置tooltip导致，放大未发现异常

### 🏞 期望结果

缩小后可以正常显示

### © 版本信息

- ProTable 版本: [e.g. 2.47.1]
- Ant-Design版本: [e.g. 4.16.12]
- 浏览器环境 Chrome[e.g 92.x]
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/22189838/130183798-82c1f54d-219e-4282-aebd-7969af1d9ab2.png)

![image](https://user-images.githubusercontent.com/22189838/130183678-6adabad3-ec3d-4247-8cb1-bf824949535a.png)

**Comment by luobinhang** [comment]
@chenshuai2144 
https://codesandbox.io/s/rl88y?file=/App.tsx:300-335  官方文档上面就有这个问题

![image](https://user-images.githubusercontent.com/22189838/130398870-997823ab-cc76-472c-a82e-6450bb7f44ec.png)

**Comment by chenshuai2144** [comment]
我这里并不行，你们是不是没有更新到最新的版本？

**Comment by luobinhang** [comment]
> 我这里并不行，你们是不是没有更新到最新的版本？

![image](https://user-images.githubusercontent.com/22189838/131450682-068e48b8-926f-4c4a-a19a-729e43308326.png)
antd和pro-table都升级到了最新的版本 依然存在这个问题

**Comment by luobinhang** [comment]
https://codesandbox.io/s/cha-xun-biao-ge-forked-9l1ik?file=/App.tsx

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/131460987-1063010c-99fb-4e36-9c8d-407eb4bcae71.png)

**Comment by chenshuai2144** [comment]
是浏览器的版本太低了？

**Comment by luobinhang** [comment]
> 是浏览器的版本太低了？

最新版本的Chrome了
![image](https://user-images.githubusercontent.com/22189838/131462280-fc85e5c5-66db-443d-b7cb-7f310cc4918b.png)

用浏览器缩放了吗？
![image](https://user-images.githubusercontent.com/22189838/131462373-3f6648a7-78a7-4b8d-9b14-fef09cd4fbc0.png)

**Comment by geneprophet** [comment]
是的，缩放后就有问题了:
![image](https://user-images.githubusercontent.com/26180057/131468285-ba3e67ef-1a84-42de-b8d1-edaceadea697.png)

**Comment by StoneCode5** [comment]
我的项目中也遇到了这个问题

**Comment by StoneCode5** [comment]
![image](https://user-images.githubusercontent.com/27874392/135213934-94a2520c-7bba-4cc7-b782-5e5c0fb814f7.png)
![image](https://user-images.githubusercontent.com/27874392/135213972-43b7c56e-e7b5-49bf-9f3c-0d219c07bdc1.png)
![image](https://user-images.githubusercontent.com/27874392/135214211-24f38dfb-9167-4978-aad7-d98330712a18.png)

操作系统：win10
react: 17.0.2
@ant-design/pro-table： 2.48.0

浏览器缩放就会有问题

**Comment by luobinhang** [comment]
![image](https://user-images.githubusercontent.com/22189838/141737985-1b9c507a-e7bb-4297-accf-d4200f55a609.png)
实测在antd > 4.17.0-alpha.8的版本中，已经得到解决，不过antd和pro在打包过程中 有less变量问题，这个issues有解决办法
[32195](https://github.com/ant-design/ant-design/issues/32195)

**Comment by luobinhang** [comment]
不过scroll x 使用max-content会导致ellipsis失效，改用scroll x 100%解决
