### ISSUE TITLE
🧐[问题]ProTable组件如何使pagination分页号受控？

### ISSUE THREAD

**Issue by JoernLee** [ant-design/pro-components#3506]
### 🧐 问题描述
这边尝试在ProTable的pagination内部通过控制current字段来控制分页号位置（参考Antd的pagination组件），但是结果没有生效，即便写死初始值为2，刷新后还是在1页，请问如何可以控制pagination的分页号呢？

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/19668821/130190809-09948567-7d6a-4e85-ac5c-17489efd1d06.png)

**Comment by chenshuai2144** [comment]
是不是params里面设置了 current？

**Comment by JoernLee** [comment]
我使用的时候并没有指定params属性：
![image](https://user-images.githubusercontent.com/19668821/130380734-0cef7503-0fb0-49aa-aee4-c266b4079699.png)

**Comment by jiechud** [comment]
https://codesandbox.io/s/wu-cha-xun-biao-dan-forked-2399n  @chenshuai2144 @cc7gs  可以看下这个demo ， onChange受控了，每次current 2 。但是底部分页还是不会受控

**Comment by cc7gs** [comment]
> https://codesandbox.io/s/wu-cha-xun-biao-dan-forked-2399n @chenshuai2144 @cc7gs 可以看下这个demo ， onChange受控了，每次current 2 。但是底部分页还是不会受控

看了下你的demo，你初始化current:2, `onChange`事件set值也是2;组件认为没有变更，就走非受控了 所以感觉没有受控；
