### ISSUE TITLE
🧐[问题]pro-layout中菜单折叠按钮位置是否可配置

### ISSUE THREAD

**Issue by jiangmengdi** [ant-design/pro-components#3508]
### 🧐 问题描述
pro-layout中菜单折叠按钮位置是否可配置

如图
![image](https://user-images.githubusercontent.com/23158665/130349296-e77c0c22-f6f7-4c97-ab90-183a13cb3765.png)
![image](https://user-images.githubusercontent.com/23158665/130349330-f181ebcc-2433-404e-8137-1b596fdbc9a4.png)

**Comment by chenshuai2144** [comment]
官网有demo
