### ISSUE TITLE
EditableProTable 中Column Request 如何获取当前行的数据，实现两列的数据联动加载

### ISSUE THREAD

**Issue by laosandegudai** [ant-design/pro-components#3509]
### 🧐 问题描述
编辑表格的两个列有联动关系，两个列都是远程请求数据，第二个列依赖第一个列的数据，如何在第二个列的request配置拿到当前行第一个列的数据

### 💻 示例代码
  {
            title: '引用模型属性',
            dataIndex: 'referenceModelItemId',
            valueType: 'select',
            hideInTable: hideInPage(),
            request:getModelItems.run,
            params:tableRef.current?.preEditableKeys
        },

我想通过 tableRef.current?.preEditableKeys 获取当前操作行的key，但是发现在request 方法里面 tableRef.current?.preEditableKeys是空数组。目前我通过表格的onChange方法手动更新列的 options达到数据加载，但是在表格显示的时候无法回显（能想到用自定义render实现，感觉不方便），求教如何实现？

**Comment by LoveEocding** [comment]
> ### 🧐 问题描述
> 编辑表格的两个列有联动关系，两个列都是远程请求数据，第二个列依赖第一个列的数据，如何在第二个列的request配置拿到当前行第一个列的数据
> 
> ### 💻 示例代码
> { title: '引用模型属性', dataIndex: 'referenceModelItemId', valueType: 'select', hideInTable: hideInPage(), request:getModelItems.run, params:tableRef.current?.preEditableKeys },
> 
> 我想通过 tableRef.current?.preEditableKeys 获取当前操作行的key，但是发现在request 方法里面 tableRef.current?.preEditableKeys是空数组。目前我通过表格的onChange方法手动更新列的 options达到数据加载，但是在表格显示的时候无法回显（能想到用自定义render实现，感觉不方便），求教如何实现？
