### ISSUE TITLE
🧐[问题] 我在使用ProTable时，有时候会遇到,后端返回数据是3条，但是页面展示的时候，会展示6条重复数据，这个是为什么？

### ISSUE THREAD

**Issue by jmy1944311667** [ant-design/pro-components#3510]
### 🧐 问题描述

我在使用ProTable时，使用request从后端获取数据，并打印出来获取到的data数据，我获取到的数据是3条，但是我打印出来看到，一共打印了两次结果，第一次是3条数据的展示，第二次是在第一次的基础上，又重新吧这三条数据累加起来，也就是第二次是这三条数据的重复累加，这个是为什么？对了，这个不是一定会出现

### 💻 示例代码
<ProTable
          actionRef={actionRef}
          rowKey={record => record.id}
          search={{
            labelWidth: 120,
            collapsed: collapsedVisible,
            onCollapse: (collapsed) => {
              setCollapsedVisible(collapsed)
            },
          }}
          pagination={{
            show: true,
          }}
          bordered={true}
          scroll={{x: 1200}}
          request={async (params) => {
				
			......

            let result;
            if (activekey === 'carton') {
              result = await getListByCartonNo({
                ...params,
                warehouseId: currentUser.userType != '3' ? warehouseId : undefined,
              });
            } else {
              result = await getListByPalletNo({
                ...params,
                warehouseId: currentUser.userType != '3' ? warehouseId : undefined,
              });
            }
           
            if (result.success) {
              let resultData = result.data.data;
              if (currentUser.userType !== 0 && currentUser.userType !== 1) {
                resultData = resultData.filter(item => item.status != 30);
              }
              console.log(resultData);
              return {
                data: resultData,
                success: true,
                total: resultData.total,
              };
            }
            message.error(JSON.stringify(result.message));
            return {
              data: [],
              success: true,
              total: 0
            }
          }}
          
          columns={cartonColumns}
        />

### 🚑 其他信息

打印出来的数据
![image](https://user-images.githubusercontent.com/29156872/130381993-a49b7cdc-4a7c-4fd5-9957-2acdb4c2be5d.png)

页面展示
![image](https://user-images.githubusercontent.com/29156872/130382259-ecf4a6b0-ec64-4e4c-936e-da5e3538fd8c.png)

**Comment by chenshuai2144** [comment]
这种事情一般是行好设置的重复了，导致 react diff 出问题了
