### ISSUE TITLE
ProCard无法适应黑色背景🐛[BUG]

### ISSUE THREAD

**Issue by ChenWes** [ant-design/pro-components#3511]
### 🐛 bug 描述

开发时使用ProTable，ProList，ProCard等，增加了SettingDrawer让系统可以自定义主题及颜色，也实现了主题的切换，
ProTable和ProList能够适应黑色主题，只有ProCard的页面，背景依然是白色

### 🏞 期望结果

正常来说，ProTable和ProCard应该都可以正常获取到黑色背景，ProCard显示不正常

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 3.5.17
- 浏览器环境 Chrome 92.0.4515.159
- 开发环境 [e.g. Windows 10]
- 依赖列表
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-card": "^1.14.13",
    "@ant-design/pro-descriptions": "^1.9.6",
    "@ant-design/pro-form": "^1.35.0",
    "@ant-design/pro-layout": "^6.24.1",
    "@ant-design/pro-list": "^1.12.1",
    "@ant-design/pro-table": "^2.49.0",
    "@umijs/route-utils": "^1.0.33",
    "antd": "^4.16.12",
    "classnames": "^2.2.6",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "umi": "^3.5.17",
    "umi-plugin-antd-theme": "^2.1.2",

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/13687430/130386910-e3567c63-5662-4329-8207-408be67ffa20.png)

**Comment by chenshuai2144** [comment]
你是不是引入了 css 样式？看了下procard是支持的

**Comment by ChenWes** [comment]
@chenshuai2144 感谢你的解答，正在尝试处理

**Comment by Symous** [comment]
@ChenWes 你好，后续怎么处理的？
