### ISSUE TITLE
👑 ProTable组件的Toolbar中的显示列设置支持从Cookie中读取初始值，提供设置初始值的接口

### ISSUE THREAD

**Issue by ld19950725** [ant-design/pro-components#3512]
### 🥰 需求描述

ProTable组件里，工具菜单栏中的列设置可以设置显示列，但是每次刷新页面，显示列设置又会被初始成全选。而且暂时未能找到对这个列设置配置初始默认值的接口，如果有这样的接口，求大佬告知。

### 🧐 解决方案

配置个Cookie中读取默认初始值的属性。

**Comment by chenshuai2144** [comment]
columnsStateMap | columns 的状态枚举 | {key:{ show,fixed }}} | -
-- | -- | -- | --
onColumnsStateChange | columns 状态发生改变 | (props: {key:{ show,fixed }}}) => void | -
