### ISSUE TITLE
🐛[BUG] ProTable组件使用renderFormItem自定义搜索 渲染多次内容

### ISSUE THREAD

**Issue by liusure** [ant-design/pro-components#3514]
### 🐛 bug 描述

使用renderFormItem时莫名的渲染很多次，如果返回null渲染次数正常，一旦返回任意组件渲染次数就会急剧增加。影响性能

### 📷 复现步骤

ProTable自定义搜索组件，renderFormItem返回任意内容

### 💻 复现代码

见截图，或者直接使用 [官方demo](https://codesandbox.io/s/tig1d?file=/App.tsx) 输出一下就可以看到渲染了7次

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
<img width="209" alt="WX20210823-142502@2x" src="https://user-images.githubusercontent.com/10415021/130401637-15a2b8c8-1bea-4f66-bcb3-25c0c0742330.png">
<img width="269" alt="WX20210823-142533@2x" src="https://user-images.githubusercontent.com/10415021/130401462-0b6a1237-d362-42ac-b649-97796f0437d8.png">
正常的情况↑↑↑↑↑↑
返回任意内容的情况↓↓↓↓↓↓
<img width="211" alt="WX20210823-142641@2x" src="https://user-images.githubusercontent.com/10415021/130401481-ba466985-50bb-43bc-af2c-8465a33f471c.png">
<img width="297" alt="WX20210823-142659@2x" src="https://user-images.githubusercontent.com/10415021/130401485-0e5d5afa-fa08-494b-8b39-080f33e6ecd8.png">

**Comment by chenshuai2144** [comment]
没必要关系这个，为了保证渲染的准确性，每次都会重新render
