### ISSUE TITLE
🧐[问题]求一个 匹配可正常使用的@ant-design/pro-form版本号！

### ISSUE THREAD

**Issue by pxim** [ant-design/pro-components#3516]
### 🧐 问题描述

我现在使用的ant pro里 @ant-design ProComponents 相关组件版本是这些
![image](https://user-images.githubusercontent.com/5111701/130421938-96940655-1ee3-4e93-9471-21bc3cb008ce.png)
![image](https://user-images.githubusercontent.com/5111701/130422092-1400a45c-8a47-4a98-96f8-4fce1c31569f.png)
我现在 npm i @ant-design/pro-form --save 发现最近的版本在我现在的环境中，不兼容；
运行一大堆错误，所以请问 pro-form 哪个版本和我 配置上的版本匹配；
https://github.com/ant-design/ant-design-pro/issues/8959

**Comment by chenshuai2144** [comment]
你都升级到最新版本呗，这个看起来是你的antd 太老了，不支持 image 组件
