### ISSUE TITLE
🧐[问题]ProTable的搜索栏支持更改样式吗，经理想用protable渲染表格，但是想用自己的UI

### ISSUE THREAD

**Issue by Fengjing95** [ant-design/pro-components#3517]
![image](https://user-images.githubusercontent.com/51731411/130428778-deb62784-e96a-4181-85c6-18699cc95f05.png)
样式长这样

**Comment by chenshuai2144** [comment]
toolbarRender，有这样的api的。最简单的方式是隐藏掉然后用procard 做一个出来。
