### ISSUE TITLE
🧐[问题]有没有办法全局配置ProContainer的一些props

### ISSUE THREAD

**Issue by GitKou** [ant-design/pro-components#3519]
### 🧐 问题描述

想实现下图所示的`PageHeader`
![image](https://user-images.githubusercontent.com/7437397/130451996-27bd7525-29f9-4fc2-9afb-e85b353d2136.png)

我参考了Demo[面包屑显示在顶部](https://procomponents.ant.design/components/layout#%E9%9D%A2%E5%8C%85%E5%B1%91%E6%98%BE%E7%A4%BA%E5%9C%A8%E9%A1%B6%E9%83%A8)，通过自定义```headerRender```来实现(BTW，好像headerContentRender和headerRender重复了)
```tsx
 <ProLayout
      headerContentRender={() => <ProBreadcrumb />}
  //...
</ProLayout>
```

但是这样需要每一个页面的`PageContainer`都配置``` breadcrumbRender={false}```:
```tsx
    <PageContainer content="欢迎使用" breadcrumbRender={false}>
        <div>Hello World</div>
    </PageContainer>
```
请问有没有类似如下，可全局的[ConfigProvider](https://ant.design/components/config-provider-cn/#header)的方式进行统一配置:
```tsx
<ConfigProvider
    pageContainer={{
    breadcrumbRender: false
  }}
   //....
  >
</ConfigProvider>
```

**Comment by chenshuai2144** [comment]
ProLayout 中有一个 breadcrumbRender，设置为false，每个页面就都消失了。也可以通过 breadcrumbRender={(props)}

props 里面有当前的pathname

**Comment by GitKou** [comment]
> ProLayout 中有一个 breadcrumbRender，设置为false，每个页面就都消失了。也可以通过 breadcrumbRender={(props)}
> 
> props 里面有当前的pathname

感谢及时的恢复🙏。我可能没表达清楚，不是不要面包屑，而是想在header中展示面包屑，而不是默认的在pageContainer中

🔗[codesanbox](https://codesandbox.io/s/mian-bao-xie-xian-shi-zai-ding-bu-forked-lhz48?file=/App.tsx)

下图的pageContainer中的`breadcrumbRender={false}`有没有办法提升一个层级统一配置？

![image](https://user-images.githubusercontent.com/7437397/130540093-f2980bee-2973-4f98-80fa-fed1127bc2b9.png)

**Comment by chenshuai2144** [comment]
支持的，在layout中配置这个

**Comment by GitKou** [comment]
> 支持的，在layout中配置这个api

可是这样不是顶部的面包屑也没了吗？
![image](https://user-images.githubusercontent.com/7437397/130541203-9daea608-29da-45e3-841e-b8f651d8448d.png)

**Comment by GitKou** [comment]
`<ProBreadcrumb `需要透传哪些props吗？demo里面没有写

**Comment by chenshuai2144** [comment]
和 Breadcrumb 相同，只是会自动帮你计算面包屑
