### ISSUE TITLE
🐛[BUG]ProTable的筛选表单自定义Select组件无法回显值

### ISSUE THREAD

**Issue by WanAn0902** [ant-design/pro-components#3520]
### 🐛 bug 描述

ProTable的筛选表单自定义Select组件无法回显值

### 📷 复现步骤

ProTable的筛选表单自定义组件直接使用Select，无法选择下拉选项，使用Input就可以的

### 🏞 期望结果

ProTable的筛选表单自定义Select组件能够像使用Input一样自动回显值

### 💻 复现代码

const columns: ProColumns<GithubIssueItem>[] = [
  {
    title: '标题',
    dataIndex: 'title',
    copyable: true,
    ellipsis: true,
    tip: '标题过长会自动收缩',
    renderFormItem: (item, { type, defaultRender, ...rest }, form) => {
      if (type === 'form') {
        return null;
      }
      return (
        <Input
          {...rest}
        />
      );
    },
  },
  {
    title: '状态',
    dataIndex: 'state',
    filters: true,
    onFilter: true,
    valueType: 'select',
    renderFormItem: (item, { type, defaultRender, ...rest }, form) => {
      if (type === 'form') {
        return null;
      }
      return (
        <Select
          {...rest}
          options={[{key:1, label:"xx1"}]}
        />
      );
    },
  },
];

### © 版本信息

-@ant-design/pro-table 版本：2.49.0

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境 【谷歌】
- 开发环境 [win10]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/38753567/130543533-7e6bdcaa-c742-4acd-b61c-d1d6e900b890.png)

**Comment by kiner-tang** [comment]
@WanAn0902 兄弟，你的options没有配置value呀，你尝试这样配置试试
```tsx

    renderFormItem: (item, { type, defaultRender, ...rest }, form) => {
      if (type === 'form') {
        return null;
      }
      return <Select {...rest} options={[{key: 1, value: 1, label: "111"}]} />;
    },
```

**Comment by WanAn0902** [comment]
> @WanAn0902 兄弟，你的options没有配置value呀，你尝试这样配置试试
> 
> ```tsx
>     renderFormItem: (item, { type, defaultRender, ...rest }, form) => {
>       if (type === 'form') {
>         return null;
>       }
>       return <Select {...rest} options={[{key: 1, value: 1, label: "111"}]} />;
>     },
> ```

真的是，谢谢，我太大意了
