### ISSUE TITLE
🧐[问题] ProFormList 组件 如何自定义操作按钮

### ISSUE THREAD

**Issue by sogud** [ant-design/pro-components#3521]
### 🧐 问题描述

ProFormList 组件 如何自定义操作按钮：删除和复制，并且自带了了一个新建一行按钮。如何自定义样式？，或从外部调用函数。

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/group#%E8%87%AA%E5%AE%9A%E4%B9%89-list


看这个demo，所有的东西都可以自定义的

**Comment by sogud** [comment]
> https://procomponents.ant.design/components/group#%E8%87%AA%E5%AE%9A%E4%B9%89-list
> 
> 看这个demo，所有的东西都可以自定义的
文档示例只能更改文字与图标，我想使用自定义组件调用删除或复制，如Popconfirm组件二次确认，如何解决？

**Comment by chenshuai2144** [comment]
Popconfirm 也可以自己加上去的，action 也吐出来了，可以通过action 来控制

**Comment by 0x457** [comment]
> 到底咋如何自定义操作按钮啊！好烦啊 ，阿里的东西，都这么残次品吗！用了阿里的好几个东西，都是初次看起来很好，深入之后很多坑，从weex'到ant design 到pro component！别说你们的demo什么都可以自定义，其实不可以。如何用自己的组件替换新增，放在render内部，会出现多个新增，放在外部，又无法调用action！烦死啦

不要好好看文档，兄弟不要急～～
 actionRender={(props, action, defaultActionDom) => {
    return [<PlusCircleOutlined key='add' onClick={() => action.add()} />, ...defaultActionDom]
  }}

**Comment by cangsnage** [comment]
> 

可以问下这个怎么新增三行呢新增多行呢
