### ISSUE TITLE
🧐[问题]使用 @midwayjs/faas 2.0 一体化开发，采用了vite 但现在无法加载less

### ISSUE THREAD

**Issue by jlala** [ant-design/pro-components#3537]
### 🧐 问题描述

使用@midwayjs/faas 一体化开发项目  因为前端是用的vite
现在在运行的时候遇到了问题

![image](https://user-images.githubusercontent.com/8163601/130961049-f76104d3-cf56-42fa-a452-39e227db9a33.png)

**Comment by chenshuai2144** [comment]
现在还不支持vite，因为我们的项目中有一些不规范的东西去不掉

**Comment by foresightyj** [comment]
一样的问题，很可惜啊。

**Comment by foresightyj** [comment]
https://github.com/ant-design/pro-components/issues/1933
https://github.com/vitejs/vite/issues/2185

这样可以。
