### ISSUE TITLE
🐛[BUG] 非form模式下，fieldProps字段设置rules不能生效

### ISSUE THREAD

**Issue by zhangtang1** [ant-design/pro-components#354]
### 🐛 bug 描述
非form模式下，fieldProps字段设置rules不能生效

### 📷 复现步骤
设置proTable的type为非form模式，
表单项设置fieldProps: { rules: [ { required: true, message: '此项为必填项'}] }，
点击查询
为空也可以查询

### 🏞 期望结果
为空不能查询，rules校验能生效

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本3.2.0
- 浏览器环境
- 开发环境 [e.g. mac OS]
- proTable 2.6.3版本

**Comment by afc163** [comment]
请填写合适的 title。

**Comment by chenshuai2144** [comment]
这个是设计， query 应该没有rules 的，但是最近应该会打开，设计师有新的想法

**Comment by zhangtang1** [comment]
> 这个是设计， query 应该没有rules 的，但是最近应该会打开，设计师有新的想法

三克油    期待新想法落地
