### ISSUE TITLE
🐛[BUG] ProTable 固定列 会出现错位的情况

### ISSUE THREAD

**Issue by linchenhuicn** [ant-design/pro-components#3540]
### 📷 复现步骤

![image](https://user-images.githubusercontent.com/21193805/130944679-05f0c300-b49e-42c5-9180-e32f69dbfb54.png)

实际上只有第一列设置固定左边，但第二列也变成固定了

![image](https://user-images.githubusercontent.com/21193805/130944455-a52fdce3-93ab-4da7-b3d4-256959e92fc6.png)

### © 版本信息

- ProTable 2.50.0
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
是个bug，已经修复了
