### ISSUE TITLE
🧐[问题]ant design pro 菜单栏路由图标使用 iconfont ，但是在选中的时候字体图标的颜色没有改变？

### ISSUE THREAD

**Issue by ddbinliang** [ant-design/pro-components#3542]
### 🧐 问题描述

ant design pro 菜单栏路由图标使用 iconfont ，，在app.tsx中也配置好了，但是在选中菜单的时候字体图标的颜色没有改变，这个要怎么处理？
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26667620/130969802-f88615ba-fd1f-42b8-898b-9e3a7908a01e.png)
![image](https://user-images.githubusercontent.com/26667620/130970100-17521b9e-c333-4b39-91fb-6e59a8d77520.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/131437457-01ac140c-7e3b-44a9-b582-3c1415307afb.png)


看看你的icon 里面有没有这个东西，如果没有重新生成一下

**Comment by Youmyin** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/131437457-01ac140c-7e3b-44a9-b582-3c1415307afb.png)
> 
> 看看你的icon 里面有没有这个东西，如果没有重新生成一下

有这个属性，但是仍然不变色，请问怎么解决呢？
![image](https://user-images.githubusercontent.com/54265150/146502645-2a50de59-8082-4e3a-b100-8f64e4af2633.png)
![image](https://user-images.githubusercontent.com/54265150/146502705-7231f474-0d35-42f5-a1b4-76b185d50ca5.png)

**Comment by chenshuai2144** [comment]
这个icon在内部写死了颜色了吧。这种的只能要求重新制作了

**Comment by Youmyin** [comment]
> 这个icon在内部写死了颜色了吧。这种的只能要求重新制作了

找到原因了，因为iconfont项目力里放的图标被改过颜色，所以变成这样，重新下载一遍就可以了，感谢指点！
