### ISSUE TITLE
🐛[BUG]【ProTable】syncToUrl模式下，搜索表单项为dateRange类型时，清空日期段再点击查询，页面url的日期段参数没有被清除

### ISSUE THREAD

**Issue by Mr-Alexx** [ant-design/pro-components#3547]
### 🐛 bug 描述

【ProTable】组件，在syncToUrl模式下，dateRange类型为搜索参数时：
1. 选择日期段，点击查询按钮，日期段正常映射到url上
2. 点击日期段组件清除按钮时（清空日期段），再点击查询按钮，url上的日期段没有被清除，还是上一次的结果

### 📷 复现步骤

该bug在官方demo内复现，[codesandbox地址](https://codesandbox.io/s/y82iq?file=/App.tsx)  
点击日期段组件清除按钮时（清空日期段），再点击查询按钮，url上的日期段没有被清除，还是上一次的结果

### 🏞 期望结果

期望当dateRange清除数据再点击查询时，url上的日期段也被清除

### 💻 复现代码

[codesandbox地址](https://codesandbox.io/s/y82iq?file=/App.tsx)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![示例图](https://i0.hdslb.com/bfs/album/7bb49529a9cc545e7b2373e161b97643e1dec218.png)

**Comment by mianlang** [comment]
pro-table v2.57.2 问题依然存在。
疑似点击清空时，value 不存在导致 transform 抛错，查询字段没有重置为 undefined。
如下处理可正确清除日期参数：
```
...
  search: {
    transform: (value) => ({
      startTime: value?.[0], // <- 可选链，或 value && value[0]
      endTime: value?.[1],
    }),
  },
...
```
