### ISSUE TITLE
ProFormSelect，是不是不能使用 dropdownRender 

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/pro-components#3549]
ProFormSelect，是不是不能使用 dropdownRender 
我想用 ProFormSelect 做一个
![image](https://user-images.githubusercontent.com/32530210/131106937-f70d562e-ea0f-4b5a-b4b0-84c88c8cbe82.png)
的效果。
![image](https://user-images.githubusercontent.com/32530210/131107155-af25e006-ea92-4858-9eee-4e7377ad9ce5.png)

![image](https://user-images.githubusercontent.com/32530210/131107000-87cb25b1-48bf-4a2b-8cc5-13e577c8bcf0.png)

感觉ProFormSelect不能这么用

**Comment by chenshuai2144** [comment]
filedProps

**Comment by erichow** [comment]
好像又不行了。。

https://codesandbox.io/s/qing-liang-shai-xuan-bian-kuang-mo-shi-forked-bq5x5c?file=/App.tsx
