### ISSUE TITLE
🐛[BUG] Can't resolve 'react-sortable-hoc' after updating to latest pro table version

### ISSUE THREAD

**Issue by arifszn** [ant-design/pro-components#3560]
After updating to the latest pro table(2.51.0), seeing this error

![image](https://user-images.githubusercontent.com/45073703/131308276-7b12a9d3-1f07-499b-b0fe-16147b84393b.png)

**ERROR in ./node_modules/@ant-design/pro-table/es/utils/useDragSort.js 15:0-72
Module not found: Error: Can't resolve 'react-sortable-hoc' in 'E:\Work\laragon\www\ezfolio\node_modules\@ant-design\pro-table\es\utils'**

This #3420 is causing it.

**Comment by chenshuai2144** [comment]
fixed
