### ISSUE TITLE
🐛[BUG]select 等组件清空之后，onSave值未改变

### ISSUE THREAD

**Issue by RyanLu911** [ant-design/pro-components#3563]
### 🐛 bug 描述
select 等组件清空之后，onSave值未改变

参考了很多其他的issue改为controlled之后，确实能解决edit。但是新增行的时候却有问题。输入之后立马变成非编辑了。
### 🏞 期望结果
onSave中data.status应该为空

不加controlled的情况下，清空select之后，onSave中的data.status为空
或者
加controlled之后，新增行的编辑行为是正常的。
### 💻 复现代码

官方demo
https://codesandbox.io/s/vyg93

增加了controlled
https://codesandbox.io/s/ke-bian-ji-biao-ge-forked-4t7q4?file=/App.tsx
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]
都是最新版本

**Comment by RyanLu911** [comment]
@chenshuai2144 麻烦问下,如果是bug的话,这个有计划fix码?谢谢

**Comment by ohhoney1** [comment]
https://github.com/ant-design/pro-components/blob/f77f6e2d7ac041a7804af1aaa3612068bc539c0d/packages/utils/src/useEditableArray/index.tsx#L257

**Comment by chenshuai2144** [comment]
fix了，换了一个新的算法

**Comment by RyanLu911** [comment]
👍
