### ISSUE TITLE
👑 [需求] QueryFilter组件选中文案区域可自定义

### ISSUE THREAD

**Issue by nxboo** [ant-design/pro-components#3564]
### 🥰 需求描述

QueryFilter组件选中文案区域可自定义
一个例字，可以说明问题

https://codesandbox.io/s/throbbing-water-4usts?file=/App.tsx

### 🚑 其他信息

<img width="319" alt="WX20210830-184906@2x" src="https://user-images.githubusercontent.com/4253172/131328319-fed82da4-d9ee-4434-932a-0bede80cdccd.png">

<img width="359" alt="WX20210830-184327@2x" src="https://user-images.githubusercontent.com/4253172/131328224-920dcf4a-6a8b-4618-a6c1-84e6ba79ac65.png">

**Comment by chenshuai2144** [comment]
看起来是个误用, 不过是有的

```tsx
  lightProps={{
            labelFormatter: () => 'xx',
          }}
```

**Comment by qiangxinglin** [comment]
> 看起来是个误用, 不过是有的
> 
> ```tsx
>   lightProps={{
>             labelFormatter: () => 'xx',
>           }}
> ```
加了没有效果呀 @chenshuai2144 
```
<ProFormSlider
  name="range"
  label="活跃时间"
  range
  fieldProps={{
    min: 1000000000,
    max: 2000000000,
    tipFormatter: (v: number | undefined) => (
      <div>{v ? moment.unix(v).format("YYYY-MM-DD HH:mm") : 0}</div>
    )
  }}
  lightProps={{
    labelFormatter: (value) => "abc",
  }}
/>
```

**Comment by nxboo** [comment]
> 看起来是个误用, 不过是有的
> 
> ```tsx
>   lightProps={{
>             labelFormatter: () => 'xx',
>           }}
> ```

感谢

但是没有效果，能不能帮忙看看是什么问题？
https://codesandbox.io/s/throbbing-water-4usts?file=/App.tsx

这个不是误用。
我们的业务场景是有个时间段的筛选功能。
80%情况下时间段限制为几个小时
但也有少量情况会长达数天，或更长时间
所以相比采用“日期时间”组件，进度条组件操作更简单一些。
