### ISSUE TITLE
🧐[问题]相对时间，有什么工具函数吗？

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#3567]
Antd的 文档有谈到相对时间，例如
1 分钟以内的时间	刚刚
1 小时以内的时间	N 分钟前
24 小时以内的时间	N 小时前
24 小时以外的时间	用 mm-dd HH:mm 的形式表示，即 12-08 08:00
超过一年的时间	用 yyyy-mm-dd HH:mm 的形式表示，即 2019-12-08 08:00

有什么工具函数吗？
我没找到。

**Comment by chenshuai2144** [comment]
`  {moment(text).fromNow()}`
