### ISSUE TITLE
🧐[问题]在EditableProTable组件中使用react-sortable-hoc来进行排序，每次输入一个值，输入框焦点就丢失了

### ISSUE THREAD

**Issue by tinyzh** [ant-design/pro-components#3568]
### 🧐 问题描述
输入框每次输入一个值之后，输入框的焦点就丢失了

### 💻 示例代码
[代码地址 codesandbox](https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-x6frl?file=/App.tsx)

### 🚑 其他信息

![](https://user-images.githubusercontent.com/8346841/131436547-187859f3-604c-46f3-a0c4-339e10d85779.gif)

**Comment by fengliner** [comment]
same question。How to solve it?

**Comment by tinyzh** [comment]
> same question。How to solve it?

上面实例已经解决了，只在排序后才更新SortableItem
