### ISSUE TITLE
👑 [需求] EditableProTable 支持各种 locale

### ISSUE THREAD

**Issue by qiangxinglin** [ant-design/pro-components#3570]
### 🥰 需求描述

EditableProTable 支持各种 locale.
### 🧐 解决方案
我现在全局加了 `<ConfigProvider locale={enUS}>{dom}</ConfigProvider>`, 但是各种提示字符仍然是中文的, 我知道可以通过修改 `deletePopconfirmMessage | onlyOneLineEditorAlertMessage | onlyAddOneLineAlertMessage` 来达到目的, 但是更期望有官方全球化

**Comment by china-english** [comment]
同样遇到此类问题，请问有全局解决提示字符无法国际化的解决方案吗？而不是通过 `deletePopconfirmMessage | onlyOneLineEditorAlertMessage | onlyAddOneLineAlertMessage`传参解决

**Comment by chenshuai2144** [comment]
已经支持的差不多了，可以试试了
