### ISSUE TITLE
🧐[问题] valueType = ‘money’ 时，页面展示是以￥展示的，这个能否我设置展示符号？  比如使用$

### ISSUE THREAD

**Issue by jmy1944311667** [ant-design/pro-components#3572]
### 🧐 问题描述

valueType = ‘money’ 时，页面展示是以￥展示的，这个能否我设置展示符号？  比如使用$

### 💻 示例代码

const columns = [
    {
      title: formatMessage({id: 'warehouseManager.public.id'}),
      align: 'center',
      dataIndex: 'id',
    },
    {
      title: "总金额",
      align: 'center',
      valueType: 'money',
      dataIndex: 'totalAmt',
      filedProps: {
        moneySymbol: false,
        precision: 2
      },
    },
    {
      title: "可用金额",
      align: 'center',
      valueType: 'money',
      dataIndex: 'freeAmt',
      filedProps: {
        moneySymbol: false,
        precision: 2
      },
    },
    {
      title: "其他金额",
      align: 'center',
      valueType: 'money',
      dataIndex: 'otherAmt',
      filedProps: {
        moneySymbol: false,
        precision: 2
      },
    },
    {
      title: "币种",
      align: 'center',
      dataIndex: 'currency',
    },
    {
      title: formatMessage({id: 'baseManageer.permissionManageer.status.placeholder'}),
      dataIndex: 'status',
      align: 'center',
      valueEnum: {
        0: {
          text: formatMessage({id: 'baseManageer.permissionManageer.status.normal'}),
        },
        1: {
          text: formatMessage({id: 'baseManageer.permissionManageer.status.disable'}),
        },
        2: {
          text: formatMessage({id: 'baseManageer.permissionManageer.status.deleted'}),
        },
      },
    },
  ];

### 🚑 其他信息

页面展示
![image](https://user-images.githubusercontent.com/29156872/131473210-5b718a09-4fc8-4f14-a829-64d72505dca7.png)

**Comment by jmy1944311667** [comment]
补充：我使用    
...
{
      title: formatMessage({id: 'amt.totalAmt'}),
      align: 'center',
      valueType: 'money',
      dataIndex: 'totalAmt',
      filedProps: {
        moneySymbol: "$",
        precision: 2
      },
    },
...
这样的设置，没有效果


...
{
      title: formatMessage({id: 'amt.totalAmt'}),
      align: 'center',
      valueType: {
        type:'money',
        moneySymbol: "$",
      },
      dataIndex: 'totalAmt',
    },
...

这样的也没效果

**Comment by kiner-tang** [comment]
你可以使用修改人民币符号为美元符号，locale代表地区，不同的地区使用的货币符号不同：
```tsx
      valueType: {
        type: "money",
        locale: "en_US"
      },
```
附上目前支持的地区货币符号：
```json
{
    "ar_EG": "$",
    "de_DE": "€",
    "en_GB": "£",
    "en_US": "$",
    "es_ES": "€",
    "fa_IR": "تومان",
    "fr_FR": "€",
    "id_ID": "RP",
    "it_IT": "€",
    "ja_JP": "¥",
    "ko_KR": "₩",
    "ms_MY": "RM",
    "pl_PL": "zł",
    "pt_BR": "R$",
    "ru_RU": "₽",
    "sr_RS": "RSD",
    "tr_TR": "$",
    "vi_VN": "₫",
    "zh_CN": "¥",
    "zh_TW": "$"
}
```

**Comment by jmy1944311667** [comment]
> 你可以使用修改人民币符号为美元符号，locale代表地区，不同的地区使用的货币符号不同：
> 
> ```tsx
>       valueType : { 
>         type : "money" , 
>         locale : "en_US" 
>       } ,
> ```

![image](https://user-images.githubusercontent.com/29156872/131775429-5b9d40fd-39cb-4c58-967c-6f505278730b.png)

我改成这个之后，页面直接报错了

![image](https://user-images.githubusercontent.com/29156872/131775485-57fd5aa6-f46a-417a-816f-37215c3da409.png)
![image](https://user-images.githubusercontent.com/29156872/131775501-f4aff2f1-35c5-4eb5-b3bf-f265dafeef44.png)

，这个写法不对吧，还是我写错了

**Comment by kiner-tang** [comment]
尝试把locale换成`en-US`看看

**Comment by jmy1944311667** [comment]
> 尝试把locale换成`en-US`看看
{
      title: formatMessage({id: 'amt.totalAmt'}),
      align: 'center',
      valueType: {
        type:'money',
        en_US:'en_US',
      },
      dataIndex: 'totalAmt',
    },
是这样吗？
![image](https://user-images.githubusercontent.com/29156872/131792495-96babed8-e15a-4ff7-8eb7-234204112224.png)
这个也是不行

**Comment by kiner-tang** [comment]
```tsx
 valueType : { 
        type : "money" , 
        locale : "en-US" 
      } ,
```

**Comment by jmy1944311667** [comment]
> ```tsx
>  valueType : { 
>         type : "money" , 
>         locale : "en-US" 
>       } ,
> ```

对了，这个是只能通过这种方式来改变符号的吗？   有没有我通过字段的类型，来自动改变单位的？

**Comment by jmy1944311667** [comment]
> ```tsx
>  valueType : { 
>         type : "money" , 
>         locale : "en-US" 
>       } ,
> ```

因为，我现在需要展示两条数据，一条是人民币的，一条是美元的

**Comment by rimsila** [comment]
> 

How can we change en-Us as default ?

**Comment by chenshuai2144** [comment]
看这个 

https://github.com/ant-design/pro-components/issues/4577
