### ISSUE TITLE
🐛[BUG] EditableProTable嵌套内层EditableProTable有问题

### ISSUE THREAD

**Issue by qiangxinglin** [ant-design/pro-components#3576]
### 🐛 bug 描述

在外层 `EditableProTable` 的 `expandable.expandedRowRender` 嵌套再一层 `EditableProTable`, 会导致内层表格为空, 并且内层表格宽度非常大, 页面卡顿几秒 (估计是渲染新的超宽表格导致)

如果把内层换成普通的 `ProTable` 则没有任何问题

之前遇到过一次用Antd的list嵌套, 内层list props无效的问题 ant-design/ant-design#31571, 当时给的回复是样式继承, 不知道这个是不是类似状况

![image](https://user-images.githubusercontent.com/20382522/131507537-e6819c0d-1314-4d75-a259-71c51f88b97c.png)
### 📷 复现步骤
如上所述

### 🏞 期望结果
内层表格渲染正常

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个可能暂时无解。

**Comment by ATacoo** [comment]
有解决方案嘛。 EditableProTable的expandedRowRender嵌套EditableProTable。

**Comment by ATacoo** [comment]
@chenshuai2144 哈喽你好 EditableProTable的expandedRowRender嵌套EditableProTable 有解决方案嘛。

**Comment by xXAvoraXx** [comment]
When the state of the table changes, the expanded row render is not refreshed.

**Comment by xXAvoraXx** [comment]
There are too many problems with the nested editable table. For example, when the cancel button is clicked while creating a new row in the inner table, it creates a copy of the top row in the table twice.

**Comment by chenshuai2144** [comment]
已经修复，重新安装

**Comment by Tinyuen** [comment]
EditableProTable 嵌套 EditableProTable  在 ProForm 中使用的 Demo 有吗？

**Comment by Tinyuen** [comment]
@chenshuai2144   大佬有相关的demo可以参考下么，EditableProTable 嵌套 EditableProTable 在 ProForm 中使用的 Demo ，
