### ISSUE TITLE
👑 [需求]Pro-table新增對Antd Table 的defaultSortOrder 和 defaultFilteredValue 的支持

### ISSUE THREAD

**Issue by jackykwandesign** [ant-design/pro-components#358]
### 🥰 需求描述

Pro-table 裡面能否新增對 類似Antd Table 的defaultSortOrder 和 defaultFilteredValue 的支持
例如打開表格時預設某列已筛选或已排序

**Comment by chenshuai2144** [comment]
应该支持的，不支持是bug

**Comment by America-first-melon** [comment]
我用defaultSortOrder也没生效。

**Comment by HHHui** [comment]
我今天在做页面回退时，回复Table状态时也遇到这个问题了。

**Comment by chenshuai2144** [comment]
antd 的 table 有问题，我透传了也没用。提给antd 的

**Comment by America-first-melon** [comment]
这回退到底如何做， 设置了form initialValues初始值， 按钮不管用了，重新formRef.setFieldsValue 也不行，，，

**Comment by America-first-melon** [comment]
升级到antd 4.7 protable 2.8 怎么没作用？  不是直接在column里写      `defaultSortOrder: 'descend',` 吗？

**Comment by America-first-melon** [comment]
![image](https://user-images.githubusercontent.com/21686182/95940834-ec805b80-0e11-11eb-8e9b-0375234f47a6.png)

**Comment by Hikarien** [comment]
有解决了的吗？ 临时方案也好啊😭😭😭

**Comment by jackykwandesign** [comment]
等antd 那邊更新吧，不是這邊的鍋

**Comment by fengzhenfz** [comment]
将defaultSortOrder 换成 sortOrder

**Comment by fengzhenfz** [comment]
> 有解决了的吗？ 临时方案也好啊😭😭😭

**Comment by David2k13** [comment]
看了下antd那边最新的是可以用啊

**Comment by ZifengChen** [comment]
> 将defaultSortOrder 换成 sortOrder

这样别的列就没法排序了 我也遇到了同样的问题

**Comment by SH748** [comment]
我对antd的table进行了二次封装，default也不生效了

**Comment by kilingzhang** [comment]
请问一下 这个bug解决了吗 我看已经 closed了 没看到被解决的fixed发布到了哪个版本。

**Comment by LiuZHolmes** [comment]
同问，有follow的issue或者其他吗
