### ISSUE TITLE
🐛[BUG] ProForm 监听某个值时， onValuesChange总是触发两次，

### ISSUE THREAD

**Issue by keeperdog** [ant-design/pro-components#3580]
### © 版本信息

- ProComponents 版本:     "@ant-design/pro-form": "^1.38.1",
- umi 版本 3.x
- 浏览器环境 chrom
- 开发环境 [e.g. mac OS]

**Comment by Liu-Ya** [comment]
[![Edit 基本使用 (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-forked-9mkej?fontsize=14&hidenavigation=1&theme=dark)

复现 @chenshuai2144

**Comment by jiujiaonuannan** [comment]
+1

**Comment by chenshuai2144** [comment]
修掉了，升级新版本吧
