### ISSUE TITLE
🐛[BUG]Pro-table 配置超长省略的列,在浏览器缩放(缩小)的状态下,会重叠

### ISSUE THREAD

**Issue by maxborts** [ant-design/pro-components#3582]
### 🐛 bug 描述
Pro-table 配置超长省略的列,在浏览器缩放(缩小)的状态下,会重叠
如图
![QQ图片20210901110822](https://user-images.githubusercontent.com/18714762/131605527-aa47a20d-9c69-47f2-b42f-5b617a4931a5.png)

**Comment by chenshuai2144** [comment]
同类issue 很多了，不要乱提

**Comment by maxborts** [comment]
不好意思,缩放状态下浏览官网的时候发现的,随手提了下
没有搜索相关issues




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月22日(星期三) 中午12:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 🐛[BUG]Pro-table 配置超长省略的列,在浏览器缩放(缩小)的状态下,会重叠 (#3582)





 
同类issue 很多了，不要乱提
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
