### ISSUE TITLE
EditableProTable如何通过外部组件修改其中的值

### ISSUE THREAD

**Issue by ai180508** [ant-design/pro-components#3584]
### 🧐 问题描述

    点击EditableProTable某一列后会弹出一个Modal，选择Modal中的值后修改EditableProTable中的值

### 🚑 其他信息
![131607966-3c0f6ac9-973a-4493-b766-218584dacc8d](https://user-images.githubusercontent.com/77037794/131628331-6f5342fb-5d9d-4e4c-b5e3-b6eb2e84be3b.png)

**Comment by chenshuai2144** [comment]
当成一个form来用就好了，form.setFieldValue
