### ISSUE TITLE
🐛[BUG] umijs3 ie11 报错

### ISSUE THREAD

**Issue by Niofh** [ant-design/pro-components#3586]
### 🐛 bug 描述

SCRIPT1004: 缺少 ';'

### 📷 复现步骤

 umijs3 引入 andt-pro 表格不支持ie11

### 🏞 期望结果

支持ie11

### © 版本信息

- ProComponents 版本: @ant-design/pro-table ^2.47.0
- umi 版本 3.0
- 浏览器环境 ie11
- 开发环境 [e.g. mac OS]  windows

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/15324717/131654210-87649b44-f9ad-49b9-91ee-2b865bff5162.png)

**Comment by chenshuai2144** [comment]
不要用异步加载，ie不支持。
