### ISSUE TITLE
🧐[问题]ProFormSelect 使用filterOption这个过滤下拉选项的时候，输入中文无法正常过滤

### ISSUE THREAD

**Issue by WailessXie** [ant-design/pro-components#3587]
### 🧐 问题描述
这里我是使用了valueEnum 来生成下拉选项的，搜索的时候输入中文就不进去filterOption这个方法里，输入数字才会正常进去。请各位大大帮忙解答下。或者有其他的解决方法也不吝赐教。

### 💻 示例代码
```ts
<ProFormSelect
          width="md"
          showSearch
          fieldProps={{
            optionFilterProp: "children",
            filterOption: (input, options) => {
              console.log(input)
              console.log(options)
              return false;
            }
          }}
          valueEnum={{
            101: (<span>101-实例101</span>),
            202: (<span>202-实例202</span>),
            303: (<span>303-实例303</span>),
            404: (<span>404-实例303</span>),
          }}
          name="list"
          label="列表"
/>
```
[源码](https://www.typescriptlang.org/zh/play?skipLibCheck=true&jsx=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoUSWOABRwDFoQAaOAb3oiahAHEcAVzBsuPEAGUkAGyQYWAXzjZcBAAIoAdjAC0AEyQBnYAHNNAejA4dmZmXLkkAD2rw0ETYfgB3FMBgAKqBIcAC8cAAUMMEAXHCagiAARkhQYXAAjAAMWQCUYQB8HORwcEQwglCa8UjedDggwIZIERFEhhDSAG5I+aFF7CWlcM2BwRCCMK19A0PDZUadPVFQgr0U8wps0SDrQwq5FAoU5O6e8AAiSCAQ6REzkUMAPHrAXXMjMACesqHsg-NSmAUHpXpoTHEAEwAFhYHwUCiGBQ+TzEzA+pU0KF2oQARF0UNJgHoUDAkAB9CAwAAWqVxH2RgLgqMYzAEEzAjKZzLRvCksgwGMB3mJNLxID09O5w0M1Ig3ikKCgaGpQvmmGAMj0XDAhj+AOlwwgYGiHgYwGkZKgOriuJVFr0RE0uLhhuGGstqQA8ibgB44hFgJowJM2MbTZ4Hga3aUzh1ZAA6aQQEyB4OTXJq7lxzpIJMpiLhv2RrNM8qVaqYQnNDYxxFuhGluAE6RrACiCRA+qbpWyGQDT0MwM0BT7OkAedqAaPk+09zEOtAVcq6Y5CspCB-OR6vIRPJ9vZ5vF8u3QBmLInjfDgpnk+7m8Hq9LntwaFZaGXhev6F388PhdPht60NLEcVxIkvClQ1pBQFJpDxQB0JUACwjIKZcwuXmWdeX4IROQcDDzCwrlZ1eLpkUOBxnFcOADCrQRLTgK4bgoIA)

### 🚑 其他信息
输中文不打印任何信息。
![image](https://user-images.githubusercontent.com/26828807/131677197-90a2be74-cec5-4ec4-ac33-671ccc485a01.png)

**Comment by chenshuai2144** [comment]
直接来个demo 吧

**Comment by WailessXie** [comment]
> 直接来个demo 吧
demo在源码那个链接

**Comment by WailessXie** [comment]
https://github.com/WailessXie/simple

**Comment by chenshuai2144** [comment]
来个code box不是仓库

**Comment by WailessXie** [comment]
codebox依赖都拉不了
