### ISSUE TITLE
🧐[问题]ProTable的搜索表单，如果是Select如何设置默认选中某一项

### ISSUE THREAD

**Issue by sanwanliu** [ant-design/pro-components#359]
### 🧐 问题描述

如图，我需要默认选择其中一项，有这个功能吗

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23079982/91785352-c2932100-ec37-11ea-9b16-d332a67677a8.png)

**Comment by dmdoit** [comment]
在ProTable里设置 form={{ initialValues: {status: '7'} }}
```
<ProTable
        rowKey="key"
        actionRef={actionRef}
        formRef={formRef}
        form={{ initialValues: {status: '7'} }}
/>
```

**Comment by sanwanliu** [comment]
> 在ProTable里设置 form={{ initialValues: {status: '7'} }}
> 
> ```
> <ProTable
>         rowKey="key"
>         actionRef={actionRef}
>         formRef={formRef}
>         form={{ initialValues: {status: '7'} }}
> />
> ```

可以了，谢谢
