### ISSUE TITLE
🐛[BUG]protable更新后，下拉select列表内容宽度超过表单格子宽度时，会多一行

### ISSUE THREAD

**Issue by JimLeeee** [ant-design/pro-components#3592]
### 🐛 bug 描述

如下图，protable更新后，下拉select列表内容宽度超过表单格子宽度时，选择后表单多了一行 
![image](https://user-images.githubusercontent.com/46155146/131776396-f627c3dc-d891-4fc3-8228-98fd3af3238c.png)
设置了dropdownMatchSelectWidth:false,之前的版本没有这个问题，选择后，可以自动省略，表单行数不变

### 🏞 期望结果
选择后，选择的列表自动省略，表单行数不变
![image](https://user-images.githubusercontent.com/46155146/131776578-736c7cc2-ea6e-4f6e-8c7b-f6ba962c7607.png)

### 💻 复现代码
{
      title: '表名',
      dataIndex: 'tablename', 
      key: 'tablename',
      tip: '以namepace+nginx名字命名',
      hideInTable: true,
      formItemProps: {
        rules: [
          {
            required: true,
            message: '必须输入tablename',
          },
        ],
      },
      valueType: 'select',
      request: requestTable,
      fieldProps: {
        showSearch: true,
        dropdownMatchSelectWidth:false,
      },
      order: 8,
    },

### © 版本信息

- ProComponents 版本: "@ant-design/pro-table": "^2.37.2","antd": "^4.15.6",
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by JimLeeee** [comment]
经过各种调试，配置里加上wrapperCol，指定span后会正常，但是当浏览器缩小到一定程度后，还是会出现跨行，现在问题是正常大小的浏览器都会出现跨行，所以这个bug猜测是新版本改了什么配置导致的？

form={{
          ignoreRules: false,
          wrapperCol: {
            span: 18,
          },
        }}

**Comment by bruceliu68** [comment]
最新版也有这个问题，请问有解决方案吗

**Comment by changjunhao** [comment]
加 CSS
`
.ant-pro-table-search-query-filter {
  .ant-form-item-control {
    overflow: hidden;
  }
}
`
