### ISSUE TITLE
🧐[问题]如何去掉ProTable里面的ant-card-body的padding-left和padding-right

### ISSUE THREAD

**Issue by kilik52** [ant-design/pro-components#3597]
### 🧐 问题描述

ProTable里面会包一个Card，默认有左右padding，我不希望有这左右padding请问是否有参数可以设置。我只看到ProTable里面有tableStyle参数，没有cardStyle参数

**Comment by Artoria-0x04** [comment]
在没有 search 的时候确实有点烦人

**Comment by chenshuai2144** [comment]
cardProps 这个配置

**Comment by Artoria-0x04** [comment]
文档里没看到这个配置，但是 2.52 代码里有了，新功能吗？

**Comment by kilik52** [comment]
> cardProps 这个配置

感谢。借地再问一下，StatisticCard也有这个问题。但是似乎并没有cardProps属性。
