### ISSUE TITLE
🐛[BUG]protable使用过滤(filter),翻页器没有更新页数

### ISSUE THREAD

**Issue by meyerlee** [ant-design/pro-components#3598]
### 🐛 bug 描述
protable使用过滤(filter)数据只有1页了
但是翻页器还是显示全量的页数,很多页面点击进去都是空的，感官不好。

使用官网的样例就能看到效果

### 🏞 期望结果

希望filter之后更新翻页器的total

![image](https://user-images.githubusercontent.com/8414971/131985231-42d38feb-7dab-405f-a8f9-e382db87b217.png)

**Comment by kiner-tang** [comment]
官方示例没有将筛选条件传递给接口，让接口进行筛选，因此，接口筛选的结果还是一样存在30条数据，实际开发时，应与服务端配合，通过`request`方法传递的filterOption传给服务端进行实际筛选操作，筛选之后页码自然便会更新。

**Comment by meyerlee** [comment]
我了解查询（重新调用request）之后会更新页信息。
我说的filter，在浏览器端做了过滤之后，数据发生了变化，但是分页器没有跟随数据的变化。
会造成使用者疑惑。

**Comment by meyerlee** [comment]
> 官方示例没有将筛选条件传递给接口，让接口进行筛选，因此，接口筛选的结果还是一样存在30条数据，实际开发时，应与服务端配合，通过`request`方法传递的filterOption传给服务端进行实际筛选操作，筛选之后页码自然便会更新。

你说的是服务端过滤的情况，我使用的本地过滤

**Comment by chenshuai2144** [comment]
本地过滤修改一下 dataSource 即可。不过翻页还是不会自动替你翻页。
