### ISSUE TITLE
🐛[BUG] pro-table v2.6.3 request初次加载参数params!.current为undefined ，点击查询后正常

### ISSUE THREAD

**Issue by Nokecy** [ant-design/pro-components#360]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
fixed in 2.6.4

**Comment by iamgian-coder** [comment]
能重开吗，2.7.0版本依旧有这个问题

**Comment by Nokecy** [comment]
最新版本依旧存在问题 @chenshuai2144

**Comment by chenshuai2144** [comment]
给我来个复现的demo吧

**Comment by iamgian-coder** [comment]
> 给我来个复现的demo吧

给你复现repo:https://github.com/iamgian-coder/reproducebug.git

**Comment by chenshuai2144** [comment]
发布了，新版本不会了
