### ISSUE TITLE
🧐[问题]给Tabs.TabPane 加 data-test，似乎不管用，有办法吗？

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#3600]
### 🧐 问题描述

想给Tabs.TabPane 加 data-test
以用于自动测试
似乎不管用。
有没有办法给Tabs.TabPane 加 data-test id？

**Comment by chenshuai2144** [comment]
去antd的问题把，我记得好像不行。TabPane  不是一个真实的dom
