### ISSUE TITLE
🐛[BUG] ProFormDigit使用addonBefore或者addonAfter，校验错误信息出现两条

### ISSUE THREAD

**Issue by GuiGu0101** [ant-design/pro-components#3601]
### 🐛 bug 描述

当ProFormDigit组件使用addonBefore或者addonAfter添加前后缀时，校验的错误信息会重复出现两条

### 📷 复现步骤
给ProFormDigit组件添加addonBefore或者addonAfter，触发校验异常状态，例如必填不填。校验信息出现两条

### 🏞 期望结果

仅有一条校验结果

### 💻 复现代码

```jsx
<ProFormDigit
  label="成本价"
  name="price"
  addonBefore="￥"
  fieldProps={{ precision: 2 }}
  rules={[
    {
      required: true,
    },
  ]}
 />
```

### © 版本信息

- ProComponents 版本: 1.38.1
- umi 版本
- 浏览器环境
- 开发环境 mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/11514093/132125362-c9126634-1c9f-4ad0-8da7-1ae5592ade7e.png)

**Comment by ILoveChy** [comment]
https://codesandbox.io/s/ji-ben-shi-yong-forked-cueui?file=/package.json
proForm的组件下删除修改 onValuesChange会触发2次
加上addonBefore或者addonAfter后,删除会触发2次,修改会直接触发3次回调

**Comment by ajesses** [comment]
这bug解决了吗？
