### ISSUE TITLE
🧐[问题] 想請問在 Antd 中使用了 ProLayout 的樣式覆蓋問題

### ISSUE THREAD

**Issue by HKChen** [ant-design/pro-components#3603]
### 🧐 问题描述

原先只有使用 **Antd** 的 **Layout**，但因為在佈局上不是想要的。後來在 **Antd Pro** 看到了 **ProLayout**，
也成功的顯示理想中的佈局，但目前遇到了引用 **ProLayout** 後 **CSS** 樣式把原本自定義的主題顏色都
覆蓋掉了的樣子。原本下方代碼大部分的變數都吃不到，**primary color** 也只能顯示部份的地方，想
請教當我引用了 **ProLayout** 之後我的 **CSS** 樣式該怎麼去處理？目前我找不到可以相設定的方式去處理全局
的樣式，或是可以修改加載 component 的優先順序之類的？目前頂多只能在 **global.less** 去看對應的類別，例如
header 改顏色
```css
#root .ant-pro-global-header-layout-mix {
    background-color: red !important;
}
```

我是使用 vite 開發

### 💻 示例代码

custom-antd.less

```css
@import 'antd/lib/style/themes/default.less';
@import 'antd/dist/antd.dark.less';

@body-background:#172331;

@menu-dark-bg:#151d26;

@layout-sider-background:#151d26;
@layout-trigger-background:#161d30;

@primary-color: #198964; // 綠色
```

### 🚑 其他信息
**Primary Color** 是設定綠色的，**background**、**Sider** 以及 **Menu** 的也是額外自定義
[之前用 Layout]
![圖片](https://user-images.githubusercontent.com/4105970/132184987-15c59cc3-c4ed-4d11-8032-07cbaff6c6ff.png)
---
但用了 **ProLayout** 後只有 **Table** 中那個勾選的有吃到其中 **Primary Color** 其他應該都是被覆蓋了
[用了 ProLayout]
![圖片](https://user-images.githubusercontent.com/4105970/132184483-75d6714b-36f1-496e-a176-0d663116a6b2.png)

**Comment by chenshuai2144** [comment]
来个重现地址吗？

**Comment by shiye515** [comment]
遇到了同样的问题

**Comment by JayMo666** [comment]
+1

**Comment by HKChen** [comment]
@shiye515 @JayMo666 這邊提供我目前的解法，但要去看 theme.less 的一些 **@param** 去對應
在 vite.config.js 底下設定 modifyVars 去 custom 需要的參數，蠻多都要處理的，用的挺煩躁。而且
最近的版本把一些 layout css 又改掉跑版，只能鎖到 minor 版號，在不行就要鎖死了。

**vite.config.js**
`
import { defineConfig } from "vite";
...
const path = require("path");

export default defineConfig({
    css: {
        preprocessorOptions: {
            less: {
                javascriptEnabled: true,
                modifyVars: {
                    "@primary-color": "#198964",
                    "@body-background": "#172331",
                    "@page-header-heading-title": "@heading-3-size",
                    "@component-background": "#141414",
                    "@icon-color-hover": "fade(@white, 75%)",
                    "@heading-color": "white",
                    "@text-color": "fade(@white, 65%)",
                    "@text-color-secondary": "fade(@white, 45%)",
                    "@border-color-base": "#434343",
                    "@border-color-split": "@popover-background",
                    "@border-style-base": "solid",
                    "@layout-body-background": "@body-background",
                    "@layout-header-background": "@component-background",
                    "@layout-sider-background": "@component-background",
                    "@layout-trigger-background": "@component-background",
                    "@font-feature-settings-base": "tnum",
                    "@disabled-color": "fade(@white, 30%)",
                    "@disabled-color-dark": "fade(@white, 30%)",
                    "@outline-blur-size": "0",
                    "@background-color-light": "fade(@white, 4%)",
                    "@background-color-base": "fade(@white, 8%)",
                    "@item-hover-bg": "fade(@white, 8%)",
                    "@shadow-color": "rgba(0, 0, 0, 0.45)",
                    "@btn-default-bg": "transparent",
                    "@input-placeholder-color": "fade(@white, 30%)",
                    "@input-bg": "transparent",
                    "@input-number-handler-active-bg": "@popover-background",
                    "@select-item-selected-font-weight": "600",
                    "@select-item-selected-bg": "@primary-color",
                    "@tooltip-bg": "#434343",
                    "@popover-bg": "@popover-background",
                    "@modal-header-bg": "@popover-background",
                    "@menu-popup-bg": "@popover-background",
                    "@menu-dark-submenu-bg": "@black",
                    "@table-header-bg": "#1d1d1d",
                    "@table-header-sort-bg": "#262626",
                    "@table-body-sort-bg": "fade(@white, 1%)",
                    "@table-row-hover-bg": "#262626",
                    "@badge-text-color": "@white",
                    "@card-actions-background": "fade(@white, 4%)",
                    "@avatar-bg": "#5a5a5a",
                    "@pagination-item-bg-active": "transparent",
                    "@slider-rail-background-color": "fade(@white, 20%)",
                    "@slider-rail-background-color-hover": " @slider-rail-background-color",
                    "@slider-track-background-color": "@primary-color",
                    "@slider-handle-color": "@primary-color",
                    "@skeleton-color": "#303030",
                    "@alert-success-border-color": "@green-3",
                    "@alert-success-bg-color": "@green-1",
                    "@alert-info-border-color": "@blue-3",
                    "@alert-info-bg-color": "@blue-1",
                    "@alert-warning-border-color": "@gold-3",
                    "@alert-warning-bg-color": "@gold-1",
                    "@alert-error-border-color": "@red-3",
                    "@alert-error-bg-color": "@red-1",
                    "@card-shadow": "0 1px 2px -2px rgba(0, 0, 0, 0.48), 0 3px 6px 0 rgba(0, 0, 0, 0.36), 0 5px 12px 4px rgba(0, 0, 0, 0.27)",
                    "@select-background": "@component-background"
                },
            },
        },
    },
    ...
});

`
