### ISSUE TITLE
🧐[问题] Protable 中 在option中使用TableDropdown，怎么使用点击事件？

### ISSUE THREAD

**Issue by jmy1944311667** [ant-design/pro-components#3604]
### 🧐 问题描述

我现在使用Protable的option中使用TableDropdown组件，但是不知道怎么添加点击事件，官方文档组件使用说明里面也找不到(https://procomponents.ant.design/components/table#%E6%9F%A5%E8%AF%A2%E8%A1%A8%E6%A0%BC-1),这个不知道怎么搞？

### 💻 示例代码

。。。
{
    title: '操作',
    width: 180,
    key: 'option',
    valueType: 'option',
    render: () => [
      <a key="link">链路</a>,
      <a key="link2">报警</a>,
      <a key="link3">监控</a>,
      <TableDropdown
        key="actionGroup"
        menus={[
          { key: 'copy', name: '复制' },
          { key: 'delete', name: '删除' },
        ]}
      />,
    ],
  },
。。。

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/29156872/132273937-4608adc5-eb94-4494-b07f-7d4a48207a66.png)

我想实现，点击复制可以操作

**Comment by zsj1029** [comment]
咨询同样的问题，tabledropmenu 定义onclick，也拿不到点击事件

**Comment by Es-Rell** [comment]
TS 有提示
onSelect={(key)=>{}}
