### ISSUE TITLE
🐛[BUG]ProFormList在ProForm中嵌套使用时，宽度变窄

### ISSUE THREAD

**Issue by SpiritJoey** [ant-design/pro-components#3605]
### 🐛 bug 描述

在ProForm中嵌套使用ProFormList时，ProFormList的宽度会变窄，无法占满整行

### 🏞 期望结果

在ProForm中嵌套使用ProFormList时，ProFormList的能够占满整行

### 💻 复现代码

import React from 'react';
import ProForm, { ProFormGroup, ProFormList, ProFormText } from '@ant-design/pro-form';
import ProCard from '@ant-design/pro-card';

const Demo = () => {
  return (
    <ProForm onFinish={async (e) => console.log(e)}>
      <ProFormText name="name" label="姓名" />
      <ProFormList
        name="users"
        label="用户信息"
        initialValue={[
          {
            name: '1111',
          },
        ]}
        itemRender={({ listDom, action }, { record }) => {
          return (
            <ProCard
              bordered
              extra={action}
              title={record?.name}
              style={{
                marginBottom: 8,
              }}
            >
              {listDom}
            </ProCard>
          );
        }}
      >
        <ProFormGroup>
          <ProFormText name="name" label="姓名" />
          <ProFormText name="nickName" label="昵称" />
        </ProFormGroup>
        <ProFormList
          name="labels"
          label="用户信息"
          initialValue={[
            {
              value: '333',
              label: '333',
            },
          ]}
          copyIconProps={{
            tooltipText: '复制此行到末尾',
          }}
          deleteIconProps={{
            tooltipText: '不需要这行了',
          }}
        >
          <ProFormGroup>
            <ProFormText name="value" label="值" />
            <ProFormText name="label" label="显示名称" />
          </ProFormGroup>
        </ProFormList>
      </ProFormList>
    </ProForm>
  );
};

export default Demo;

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/11434122/132273809-158ddd0a-f1f2-474a-9b0e-0a4f2d65712e.png)

**Comment by rdmclin2** [comment]
好的，问题已收到

**Comment by andwell** [comment]
> 好的，问题已收到

我也遇到这个问题，请问有其他办法解决吗？

**Comment by andwell** [comment]
@chenshuai2144 请问这个问题修复了吗？我看去年11月份closed

**Comment by purple-force** [comment]
> @chenshuai2144 请问这个问题修复了吗？我看去年11月份closed

可以通过给 ProFormList 传 containerStyle={{ width: '100%' }} 实现 @andwell
