### ISSUE TITLE
🐛[BUG] ProTable 中 request 和 fieldProps.options 无法启用筛选功能

### ISSUE THREAD

**Issue by Artoria-0x04** [ant-design/pro-components#3607]
### 🐛 bug 描述

只有 valueEnum 会启用列筛选功能，同样的 request 和 fieldProps.options 却不生效

### 📷 复现步骤

https://codesandbox.io/s/compassionate-knuth-t9obe?file=/App.tsx
对比官方文档 https://procomponents.ant.design/components/table#%E5%8F%97%E6%8E%A7%E7%9A%84%E8%A1%A8%E6%A0%BC%E8%AE%BE%E7%BD%AE%E6%A0%8F

### 🏞 期望结果

配置了 request 或 fieldProps.options 后可以启用筛选

### 💻 复现代码

https://codesandbox.io/s/compassionate-knuth-t9obe?file=/App.tsx

### © 版本信息

- ProComponents 版本: @ant-design/pro-table@2.51.2
- umi 版本: NA
- 浏览器环境: Chrome v92
- 开发环境 [e.g. mac OS] macOS 11.5.2

**Comment by chenshuai2144** [comment]
异步过来的当然不行了，手动设置几个进去把

**Comment by Artoria-0x04** [comment]
> 异步过来的当然不行了，手动设置几个进去把

https://codesandbox.io/s/pro-table-filters-from-request-options-t5wqe?file=/index.js
手滑把 sandbox 改了，重新弄了一个
fieldProps.options 无关异步，也不生效。而 request 既然可以用于格式化数据，那异步就不应该是问题，不能异步使用不太合理

**Comment by chenshuai2144** [comment]
这个不好搞。筛选要在 table 初始化的时候就定义好的，你要动态就需要重新设置列配置了。

你可以 loading&&<Table/>

**Comment by Artoria-0x04** [comment]
options 总应该没问题吧，我现在得把原来的 options 请求回来再转换成 valueEnum，太麻烦了

**Comment by chenshuai2144** [comment]
options 现在是没问题的，因为另外一个组件的维度了

**Comment by Artoria-0x04** [comment]
哦，那我试试

**Comment by chenshuai2144** [comment]
这其实也是我的问题， options 和  valueEnum 应该是table维度的，但是我为了降低复杂度变成了列维度的，导致无法复用，有时候还要重复加载

**Comment by Artoria-0x04** [comment]
2.53.1，直接 `filter:true` 也没生效？要发新版吗

**Comment by chenshuai2144** [comment]
用法是什么？ 默认就支持的。 用 request 来动态获取 options

**Comment by Artoria-0x04** [comment]
我是指用 options 启用筛选

这样可以
```tsx
{
    title: "Address",
    dataIndex: "address",
    valueType: "select",
    filters: true,
    onFilter: true,
    // fieldProps: {
    //   options
    // }
    valueEnum: {
      london: {
        text: "伦敦"
      },
      "New York": {
        text: "纽约"
      }
    }
}
```

这样不行
```tsx
{
    title: "Address",
    dataIndex: "address",
    valueType: "select",
    filters: true,
    onFilter: true,
    fieldProps: {
      options
    }
}
```

**Comment by chenshuai2144** [comment]
options 没法启用的。。。因为需要 key-value 格式的数据

**Comment by Artoria-0x04** [comment]
ProTable 做了额外改造吗，毕竟原版 Table 的 filters 也是传一个 options。我是觉得这种类似的功能在用法和效果上保持一致比较好，只有 valueEnum 用着比较难受，经常要转换

**Comment by chenshuai2144** [comment]
为了受控做了一些奇怪的设置

**Comment by Artoria-0x04** [comment]
受控具体是指什么受控，列定义吗？现在的话没有特殊筛选需求还是把 options 转换成 valueEnum 简单一些

**Comment by Artoria-0x04** [comment]
如果 options 这样流向你觉得可行吗
```
--- User API        options / valueEnum / request
                          \       |       /
--- ProTable              Promise<proState>
                                  |
--- Table                      columns
```
