### ISSUE TITLE
ProTable在浏览器缩放时会出现遮挡🐛[BUG]

### ISSUE THREAD

**Issue by xiaojugit** [ant-design/pro-components#3608]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/13246850/132300505-834abbfa-28c8-46ff-931c-1fd1c6416e18.png)

**Comment by timeLorder** [comment]
不管是antd也好，啥组件库也好，一般都不能保证所有组件在缩放情况下还能正常展示。只能跟用户说让他们最好不要缩放。

**Comment by chenshuai2144** [comment]
这个设计到浏览器的问题了，不是很好修。

最好直接用css 来实现
