### ISSUE TITLE
🐛[BUG] PageContainer是个什么玩劣份子。header头怎么都干不掉呢！

### ISSUE THREAD

**Issue by codedart2018** [ant-design/pro-components#3613]
直接上图吧！
![图片](http://oss.jibei.ycoto.cn/temp/WX20210908-104019%402x.png)
红圈那块。我在app.tsx里设置了
```
  breadcrumbRender: false,
```
同时也设置了
```
<PageContainer title={false} ghost={false} header={undefined} breadcrumbRender={false}>
</PageContainer>
```
它还是显示留白，就想问下这狗皮膏药如何去掉，我不想显示它！

控制台查看节点
```
<div class="ant-pro-page-container">
  <div class="ant-pro-page-container-warp">
  <div class="ant-page-header"></div>
  </div>
  <div class="ant-pro-grid-content">
  </div>
</div>
```

© 版本信息
Ant Design Pro 版本: [e.g. 5.0.0]
umi 版本:[3.5.17]
浏览器环境: chrome(最新)
开发环境 [macos]

**Comment by kaoding** [comment]
都不想显示了，就直接不了这个玩劣份子就行。

**Comment by kaoding** [comment]
https://github.com/ant-design/pro-components/pull/3631

**Comment by chenshuai2144** [comment]
@codedart2018  更新下以来就好了，不要重复提issue
