### ISSUE TITLE
🐛[BUG]ProTable点击收起，自定义的查询条件组件被卸载掉

### ISSUE THREAD

**Issue by jaw52** [ant-design/pro-components#3616]
### 🐛 bug 描述

ProTable点击收起时，renderFormItem里自定义的查询条件会被卸载掉。会时组件出现一些错误

### 🏞 期望结果
ProTable点击收起时，只是隐藏renderFormItem里的条件，而不是直接卸载掉

**Comment by chenshuai2144** [comment]
建议让组件幂等掉，每次 render 和卸载不应该有副作用，不然react18升级不上去的
