### ISSUE TITLE
🐛[BUG] ProCard 的使用 ghost={true} 去除背景白色不生效

### ISSUE THREAD

**Issue by QiuMing** [ant-design/pro-components#3619]
### 🧐 问题描述

我的页面有多个 ProCard ，期望去除ProCard 间隔之间的白色。现官方文档的demo ，其实符合要求，使用 ghost={true} 即可，但实际使用后，白色并没有取消。

### 💻 示例代码

demo 见：https://codesandbox.io/s/ji-chu-qia-pian-forked-4plwq?file=/App.tsx

**Comment by chenshuai2144** [comment]
fixed
