### ISSUE TITLE
🧐[问题]minor版本升级带来的使用上不兼容问题

### ISSUE THREAD

**Issue by zhangtang1** [ant-design/pro-components#362]
### 🧐 问题描述
从2.4.x升级到2.5.x的时候，发现
（1）2.4.x版本search的collapseRender项是支持Boolean类型的，在最2.5.x后变成了Function类型
（2）2.4.x版本table操作项render方法的第一个参数是数据对象，而2.5.x后第二个参数才是数据对象
这带来已用项目的一些问题

目前是lock锁轻易不升级，想问下未来minor和patch迭代是否会保证已有功能不受影响，还是这种是属于正常minor的迭代（我理解的minor是功能和使用上都不会改变）

最后，感谢亲们提供的组件，给我的开发带来了很大的便利

**Comment by chenshuai2144** [comment]
这是因为那几个版本正在切架构，2.6.1之后便会稳定下来，如果是bug的话，可以提个相应的issue，我们会很快跟进的

**Comment by chenshuai2144** [comment]
> 2.4.x版本table操作项render方法的第一个参数是数据对象，而2.5.x后第二个参数才是数据对象

这个是个bug。2.5 的表现才是对的

> 2.4.x版本search的collapseRender项是支持Boolean类型的，在最2.5.x后变成了Function类型

现在仍然是支持的，类型有问题，会修一下

**Comment by zhangtang1** [comment]
三克油~
