### ISSUE TITLE
🐛[BUG] ProTable onFilter本地过滤总是会触发request远程请求

### ISSUE THREAD

**Issue by Jay-G2017** [ant-design/pro-components#3623]
### 🐛 bug 描述

ProTable在配置了request的情况下, 假设某一列想做本地过滤, 在列上设置了`onfilter: () => someLogic return true`, 但是总是会触发request远程请求

### 🏞 期望结果

开启本地过滤的时候不要触发远程请求. 只有在onfilter为false时才远程请求.

### © 版本信息

- ProComponents 版本: [ProTable. 2.52.0]

**Comment by chenshuai2144** [comment]
```
  /** 如果所有列中的 filters=true| undefined 说明是用的是本地筛选 任何一列配置 filters=false，就能绕过这个判断 */
  const useLocaleFilter = useMemo(
    () =>
      columns?.every(
        (column) =>
          (column.filters === true && column.onFilter === true) ||
          (column.filters === undefined && column.onFilter === undefined),
      ),
    [columns],
  );

```

看看配置

**Comment by Jay-G2017** [comment]
这样的设计感觉会增加使用的难度, 为了一列开启本地搜索, 还要给其它列都加上filters和onFilter. 

另外尽管都定义了filters和onFilter, 也还是触发了远程请求.  看一下下面这个例子 @chenshuai2144 .
https://codesandbox.io/s/cha-xun-biao-ge-forked-01xlw?file=/App.tsx

**Comment by ldwonday** [comment]
这个bug啥时候修复啊

**Comment by ldwonday** [comment]
![image](https://user-images.githubusercontent.com/4630157/143391395-85495084-5156-4379-8750-94c66772b5b9.png)
由源码可以知道，无论如何设置几乎都不能实现本地筛选，因为不可能每个列都设置valueEnum。

**Comment by ldwonday** [comment]
@chenshuai2144 这个问题看看吧

**Comment by tanabalu** [comment]
+1

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您提供的问题描述和代码示例，经过查阅文档和源码，我发现这个问题是已知问题。

目前 ProTable 的 `onFilter` 属性在本地过滤时存在问题，无法完全避免远程请求。而且在使用 filters 时限制较多，尤其是在使用选择器时需要定义 ValueEnum 静态属性。对此，我建议看一下这个相关 issue：[#2878](https://github.com/ant-design/pro-components/issues/2878)

目前，我们可以通过自己实现 `onFilter`，来手动处理本地过滤。例如：

```tsx
<ProTable
  columns={columns}
  request={getData}
  rowKey="key"
  pagination={false}
  onFilter={(value, record) => {
    if (!value) return true;
    return (
      record.name.includes(value) ||
      record.address.includes(value) ||
      record.tags.includes(value)
    );
  }}
/>
```

这里的 `onFilter` 是一个自定义过滤函数，可以根据自己的需求进行逻辑处理。而不依赖于 `filters` 的设置。

希望以上内容能够帮到您，如果还有其他问题，请随时提出。
