### ISSUE TITLE
🧐[问题] EditableProTable表格行内联动处理，如取消后再编辑，被联动的单元格初值未重置，应怎么处理

### ISSUE THREAD

**Issue by liwxzju** [ant-design/pro-components#3624]
### 🧐 问题描述
在ProForm.Item中使用EditableProTable。在Column"编号"组件的onChange函数中使用form.setFieldsValue对“名称”列的单元格进行联动修改。点击取消不保存后，表格内容显示正常为修改前内容。 但再次点击编辑后，“名称”列的单元格的内容仍显示为联动修改的内容。

请问应怎么重置“名称”列单元格的内容为未修改前内容，谢谢！

### 🚑 其他信息
**初始**

![image](https://user-images.githubusercontent.com/6504981/132632147-98dcd9d0-0282-443c-bd05-7c904cede2d1.png)

**点击编辑，联动修改”编号“和”名称“列： “新编号”->“新名称”** 

![image](https://user-images.githubusercontent.com/6504981/132632265-2dd4f704-adaa-4c14-9bb5-d9c5165e77bf.png)

**取消后再次点击编辑，”名称”列仍显示为联动修改的内容：“新名称”， 正常应为 “原名称”**

![image](https://user-images.githubusercontent.com/6504981/132632683-762142c1-af7f-4170-8781-590d0fdf70b7.png)

**Comment by liwxzju** [comment]
通过
const [editForm] = Form.useForm()

editable:{{
    ...
    form: editForm,
    ...
onCancel: (rowKey, row, originRow ) => {
    editForm.resetFields();
}
}}
好像解决了。不知道对不对。

文档说明太有限了，只能猜着试。

**Comment by liwxzju** [comment]
通过
const [editForm] = Form.useForm()

editable:{{
    ...
    form: editForm,
    ...
onCancel: (rowKey, row, originRow ) => {
    editForm.resetFields();
}
}}
好像解决了。不知道对不对。

文档说明太有限了，只能猜着试。

**Comment by kaoding** [comment]
https://codesandbox.io/

**Comment by AnteeHub** [comment]
> 通过
> 
> ```
> const [editForm] = Form.useForm()
> 
> editable:{{
>     ...
>     form: editForm,
>     ...
> onCancel: (rowKey, row, originRow ) => {
>     editForm.resetFields();
> }
> }}
> ```
> 
> 好像解决了。不知道对不对。
> 
> 文档说明太有限了，只能猜着试。

思路是正解，之前有过issue提到过一样的问题，改进的更好方式是：
```ts
const [editForm] = Form.useForm()

editable:{{
   // ...
    form: editForm,
    //...
    onCancel: (rowKey, row, originRow ) => {
        editForm.resetFields([rowKey]);        // 只重置当前行  reset only the current row
    }
}}
```
