### ISSUE TITLE
🐛[BUG]ModalForm onFinish方法无法正常关闭

### ISSUE THREAD

**Issue by qingfengdai** [ant-design/pro-components#3627]
### 🐛 bug 描述
ModalForm 的 onFinish方法,给了return true,也没有控制visible,无法正常关闭 

### 📷 复现步骤
ModalForm 的 onFinish方法,无论是否成功都会return true,,遇到无法关闭的现象 

### 🏞 期望结果
调用onFinish后能够关闭

### 💻 复现代码

```
const editForm = (id?: string) => <ModalForm
    key='editFrom'
    className={styles.editForm}
    title={id ? '查看' : '新增'}
    form={form}
    trigger={
      id ?
        <Button type="link" size="small" onClick={() => { get(id) }}>
          <EditOutlined />
          查看
        </Button> :
        <Button
          onClick={() => { form.resetFields() }}
          icon={<PlusOutlined />}
          type="primary"
        >
          新建
        </Button>
    }
    submitter={{
      submitButtonProps: {
        style: {
          display: readOnly ? 'none' : 'inline',
        },
      },
    }}
    onFinish={async (value: DataType) => {
      if (value?.id) {
        const res = await update(value)
        if (res?.code === 0) {
          message.success('更新成功!')
          actionRef.current?.reload()
        } else {
          message.error(res?.msg)
        }
      } else {
        const res = await save(value)
        if (res?.code === 0) {
          message.success('保存成功!')
          actionRef.current?.reload()
        } else {
          message.error(res?.msg)
        }
      }

      return true
    }}
  >
    <ProFormText name='id' hidden />
    <ProFormText name='orgId' hidden />
    <ProFormText name='name' label='片区名称' rules={[{ required: true, message: '必填' }]} />
    <ProFormSelect
      name='orgName'
      label='所属企业'
      rules={[{ required: true, message: '必填' }]}
      showSearch={true}
      fieldProps={{
        onSearch: async (value) => {
          const reg = new RegExp(/^[\u4e00-\u9fa5]+$/);
          if (reg.test(value) && value.length >= 2) {
            const res = await getOrgPage({ name: value })
            if (res?.data && res?.data?.length > 0) {
              setOrgList(res?.data)
            }
          }
        },
        onSelect: (value, option) => {
          const orgId = option['data-item']?.key;
          form.setFieldsValue({ orgId })
        }
      }}
      options={orgList?.map((v) => ({ label: v?.name || '', value: v?.name || '', key: v?.id }))}
    />
    <ProFormText name='fzr' label='片区负责人' rules={[{ required: true, message: '必填' }]} />
    <ProFormText name='fzrPhone' label='联系电话' rules={[{ required: true, pattern: /^1[23456789]\d{9}$/, message: '手机号码格式不正确' }]} />
    <ProFormTextArea name='remark' label='备注' fieldProps={{ autoSize: { minRows: 2, maxRows: 6 } }} />
  </ModalForm>
```

### © 版本信息

- ant-design/pro-form 1.38.1,
- umi 3.5.17
- google

**Comment by lovesL** [comment]
你看看你的message 有没有导入  没导入 不会报错 但是会影响后面代码执行

**Comment by qingfengdai** [comment]
> 你看看你的message 有没有导入 没导入 不会报错 但是会影响后面代码执行

message是导入了的, 跟message没关系,试了下modalForm里的组件使用了异步与state就触发这样的问题

**Comment by chenshuai2144** [comment]
应该是await 每结束导致的。

**Comment by qingfengdai** [comment]
> 应该是await 每结束导致的。

触发onFinish的时候异步都已经结束了

**Comment by chenshuai2144** [comment]
onFinish 里面的await没结束，我写的代码是 await onFinish，结束之后才触发关闭

**Comment by qingfengdai** [comment]
> 我写的代码是 await onFinish，结束之后才触发关闭
换了写法,在拿到await 返回值后return true,  还是不行
    onFinish={async (value: DataType) => {
      if (value?.id) {
        const res = await update(value)
        if (res?.code === 0) {
          message.success('更新成功!')
          actionRef.current?.reload()
          return true
        }
        message.error(res?.msg)
        return true
      }
      const res = await save(value)
      if (res?.code === 0) {
        message.success('保存成功!')
        actionRef.current?.reload()
        return true
      }
      message.error(res?.msg)
      return true
    }}

**Comment by chenshuai2144** [comment]
所以我说你await 没跑完，你可以用trycatch 包一下，应该就能找到问题

**Comment by qingfengdai** [comment]
> 所以我说你await 没跑完，你可以用trycatch 包一下，应该就能找到问题
大佬,这样还是没效果
`      try {
        if (value?.id) {
          const res = await update(value)
          if (res?.code === 0) {
            message.success('更新成功!')
            actionRef.current?.reload()
          }
          message.error(res?.msg)
        } else {
          const res = await save(value)
          if (res?.code === 0) {
            message.success('保存成功!')
            actionRef.current?.reload()
          }
          message.error(res?.msg)
        }
      } finally {
        // eslint-disable-next-line no-unsafe-finally
        return true
      }`

**Comment by chenshuai2144** [comment]
注意一下你的 issue 格式。

```
   } finally {
        // eslint-disable-next-line no-unsafe-finally
        return true
      }`
```

你 catch 下报了什么错误，处理一下，提交出问题了本来就不应该关闭

**Comment by qingfengdai** [comment]
![image](https://user-images.githubusercontent.com/38605341/133020242-42a6ac6f-e12c-4b0d-806c-907c712670d4.png)
打印了没有报错信息,接口也正常

**Comment by chenshuai2144** [comment]
写个最小重现吧。

**Comment by qingfengdai** [comment]
[问题重现](https://codesandbox.io/s/modal-biao-dan-forked-os161?file=/App.tsx)
本意是打算一个页面修改 新增都共用一个ModalForm,找到问题所在,共用ModalForm时form属性必须绑定两个不同的属性 from={id?editform:addform} 不然就会出现无法关闭的问题.

**Comment by chenshuai2144** [comment]
直接用formRef 不好吗？

**Comment by qingfengdai** [comment]
> 直接用formRef 不好吗？
直接用在ProFormSelect 里使用 formRef.current?.setFieldsValue()  是无效的,所以用的form
