### ISSUE TITLE
🐛[BUG]  ProForm preserve=false ProFormList 数据错误

### ISSUE THREAD

**Issue by zhangruican** [ant-design/pro-components#3628]
### 🐛 bug 描述

ProForm 配置 preserve={false}  的时候 ProFormList 数据删除控制出错

### 📷 复现步骤

ProFormList  删除所有项

### 🏞 期望结果

全删除后数据应该为空 

### 💻 复现代码
```react
<ProForm initialValues={
              {
                users: [
                  {
                    name: '1111',
                  },
                  {
                    name: '2222',
                  },
                  {
                    name: '3333',
                  },
                ]
              }
            }
            preserve={false} 
            onFinish={(values) => {
                console.log(values)
        }}>
          <ProFormList
            name="users"
            label="用户信息"
            creatorButtonProps={{
              position: 'bottom',
            }}
          >
            <ProForm.Group size={8}>
              <ProFormText name="name" label="姓名" />
            </ProForm.Group>
          </ProFormList>
        </ProForm>
```
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/11135716/132657005-1f6e2440-d8bd-49c4-8c51-4ead1efa44ec.png)

**Comment by chenshuai2144** [comment]
preserve={false}  的意思就是删除了数据还要存在的。不可兼得了

**Comment by zhangruican** [comment]
preserve={true} 才是字段删除 数据还存在，
这个问题是
![image](https://user-images.githubusercontent.com/11135716/132819901-4a61eebb-4bdc-4d9a-8b42-23b6d576541d.png)
要key={field.name}改为key={field.key}
