### ISSUE TITLE
🧐QueryFilter 的表单能够手动添加值吗，如果有，请麻烦告诉一下方法呢

### ISSUE THREAD

**Issue by Lxianglong** [ant-design/pro-components#3629]

**Comment by chenshuai2144** [comment]
> 手动添加值吗

详细描述下你的需求

**Comment by Lxianglong** [comment]
> > 手动添加值吗
> 
> 详细描述下你的需求

很高兴您能回复我！  就是我在列表页做查询，然后跳转详情页，从详情页跳转回来的时候，需要回显上次的查询参数，查询参数能够拿到，但是无法 在QueryFilter组件内手动赋值给输入框。

**Comment by chenshuai2144** [comment]
<html>
<body>


syncToUrl | 同步参数到 url 上,url 只支持 string，在使用之前最好读一下url 中的参数类型 | true \| (values,type)=>values | -
-- | -- | -- | --
syncToInitialValues | 同步结果到 initialValues,默认为 true 如果为 false，form.reset 的时将会忽略从 url 上获取的数据 | boolean | true


</body>
</html>


试试这个api，或者需要灵活一点的试试 formRef
