### ISSUE TITLE
pro-layout  menuDataRender 菜单多层级子层级icon图标不渲染

### ISSUE THREAD

**Issue by wxf-start** [ant-design/pro-components#363]
### 🐛 bug 描述
1. 使用lpro-layout 的 menuDataRender 时，自定义菜单， 菜单多层级子层级icon图标不渲染，icon 和name应该一样，都有数据的话要都渲染出来
### 📷 复现步骤
1.使用pro-layout
2.使用api menuDataRender 

### 🏞 期望结果

icon 和name应该一样，都有数据的话子级也要都渲染出来，目前只渲染了最外层的父级

### 💻 复现代码

![image](https://user-images.githubusercontent.com/37679380/91817789-f7b76780-ec67-11ea-8d5b-25a6459dfcdb.png)
![image](https://user-images.githubusercontent.com/37679380/91817911-fede7580-ec67-11ea-90d0-a763f848fe1b.png)
![image](https://user-images.githubusercontent.com/37679380/91818190-13227280-ec68-11ea-882c-c44210f271bd.png)

### © 版本信息

-   "@ant-design/pro-layout": "^6.4.1",
- umi 3
- 谷歌
- windows7

**Comment by chenshuai2144** [comment]
去看看历史issue，这个是设计，故意的，

**Comment by wxf-start** [comment]
> 去看看历史issue，这个是设计，故意的，

好吧~~

**Comment by zhangshuling** [comment]
请问一下，你这个图标不显示的问题最后怎么解决的呢？
我现在是在 config.ts 里面配的菜单， icon 能正常显示，如果我把 菜单数据，直接写死，移到 menuDataRender 里面，虽然菜单能出来，但是 icon 出不来

`    menuDataRender: (menuData) => {
      // console.log(menuData);
      return [
        {
          path: '/home',
          name: '首页',
          icon: 'smile',
          component: './Home'
        }, {
          name: '系统管理',
          icon: 'crown',
          path: '/system',
          access: 'canAdmin',
          routes: [
            {
              path: '/system/application',
              name: '应用管理',
              component: './System/Application',
            },
            {
              path: '/system/region',
              name: '地区管理',
              component: './System/Region',
            }
          ]
        },]`
![image](https://user-images.githubusercontent.com/15334960/99209869-2f619480-27ff-11eb-939e-11e9db013539.png)

**Comment by lesinliu** [comment]
> 请问一下，你这个图标不显示的问题最后怎么解决的呢？
> 我现在是在 config.ts 里面配的菜单， icon 能正常显示，如果我把 菜单数据，直接写死，移到 menuDataRender 里面，虽然菜单能出来，但是 icon 出不来
> 
> ![image](https://user-images.githubusercontent.com/15334960/99209869-2f619480-27ff-11eb-939e-11e9db013539.png)

这个是因为，接口返回的icon绘制时是string类型，需要自己做一个转换
你可以在utils文件夹下新建一个fixMenuItemIcon.ts文件

```import React from 'react';
import { MenuDataItem } from '@ant-design/pro-layout';
import * as allIcons from '@ant-design/icons';

// FIX从接口获取菜单时icon为string类型
const fixMenuItemIcon = (menus: MenuDataItem[], iconType='Outlined'): MenuDataItem[] => {
  menus.forEach((item) => {
    const {icon, children} = item
    if (typeof icon === 'string') {
      let fixIconName = icon.slice(0,1).toLocaleUpperCase()+icon.slice(1) + iconType
      item.icon = React.createElement(allIcons[fixIconName] || allIcons[icon])
    }
    children && children.length>0 ? item.children = fixMenuItemIcon(children) : null
  });
  return menus
};

export default fixMenuItemIcon;
```
然后在app.tsx引入 `import fixMenuItemIcon from './utils/fixMenuItemIcon'`并修改其中的
```
menuDataRender: () => {
      return fixMenuItemIcon(initialState.menuData)
},
```

**Comment by zhangshuling** [comment]
> React.createElement(allIcons[fixIconName] || allIcons[icon])

感谢了，已解决

**Comment by zhangshuling** [comment]
> > 请问一下，你这个图标不显示的问题最后怎么解决的呢？
> > 我现在是在 config.ts 里面配的菜单， icon 能正常显示，如果我把 菜单数据，直接写死，移到 menuDataRender 里面，虽然菜单能出来，但是 icon 出不来
> > ![image](https://user-images.githubusercontent.com/15334960/99209869-2f619480-27ff-11eb-939e-11e9db013539.png)
> 
> 这个是因为，接口返回的icon绘制时是string类型，需要自己做一个转换
> 你可以在utils文件夹下新建一个fixMenuItemIcon.ts文件
> 
> ```
> import { MenuDataItem } from '@ant-design/pro-layout';
> import * as allIcons from '@ant-design/icons';
> 
> // FIX从接口获取菜单时icon为string类型
> const fixMenuItemIcon = (menus: MenuDataItem[], iconType='Outlined'): MenuDataItem[] => {
>   menus.forEach((item) => {
>     const {icon, children} = item
>     if (typeof icon === 'string') {
>       let fixIconName = icon.slice(0,1).toLocaleUpperCase()+icon.slice(1) + iconType
>       item.icon = React.createElement(allIcons[fixIconName] || allIcons[icon])
>     }
>     children && children.length>0 ? item.children = fixMenuItemIcon(children) : null
>   });
>   return menus
> };
> 
> export default fixMenuItemIcon;
> ```
> 
> 然后在app.tsx引入 `import fixMenuItemIcon from './utils/fixMenuItemIcon'`并修改其中的
> 
> ```
> menuDataRender: () => {
>       return fixMenuItemIcon(initialState.menuData)
> },
> ```

感谢了，已解决

**Comment by chenshuai2144** [comment]
这样打包大小会大很多

**Comment by zhangshuling** [comment]
> 这样打包大小会大很多

是因为 import * as allIcons from '@ant-design/icons' 的原因导致打包“体积” 变大么？
那合理的方法该如何显示 这个菜单图标呢 ？

**Comment by chenshuai2144** [comment]
做一个map，你要声明你要用什么

**Comment by dealdot** [comment]
ProLayout添加以下函数即可解决，Link之间返回的是 {defaultDom}

menuItemRender={(menuItemProps, defaultDom) => {
return {defaultDom};
}}

**Comment by xiaodin1** [comment]
> > 请问一下，你这个图标不显示的问题最后怎么解决的呢？
> > 我现在是在 config.ts 里面配的菜单， icon 能正常显示，如果我把 菜单数据，直接写死，移到 menuDataRender 里面，虽然菜单能出来，但是 icon 出不来
> > ![image](https://user-images.githubusercontent.com/15334960/99209869-2f619480-27ff-11eb-939e-11e9db013539.png)
> 
> 这个是因为，接口返回的icon绘制时是string类型，需要自己做一个转换 你可以在utils文件夹下新建一个fixMenuItemIcon.ts文件
> 
> ```
> import { MenuDataItem } from '@ant-design/pro-layout';
> import * as allIcons from '@ant-design/icons';
> 
> // FIX从接口获取菜单时icon为string类型
> const fixMenuItemIcon = (menus: MenuDataItem[], iconType='Outlined'): MenuDataItem[] => {
>   menus.forEach((item) => {
>     const {icon, children} = item
>     if (typeof icon === 'string') {
>       let fixIconName = icon.slice(0,1).toLocaleUpperCase()+icon.slice(1) + iconType
>       item.icon = React.createElement(allIcons[fixIconName] || allIcons[icon])
>     }
>     children && children.length>0 ? item.children = fixMenuItemIcon(children) : null
>   });
>   return menus
> };
> 
> export default fixMenuItemIcon;
> ```
> 
> 然后在app.tsx引入 `import fixMenuItemIcon from './utils/fixMenuItemIcon'`并修改其中的
> 
> ```
> menuDataRender: () => {
>       return fixMenuItemIcon(initialState.menuData)
> },
> ```

menuItemRender: (menuItemProps, defaultDom) => {
      if (menuItemProps.isUrl || !menuItemProps.path) {
        return defaultDom;
      }
      // 支持二级菜单显示icon
      return (
        <Link to={menuItemProps.path}>
          {menuItemProps.pro_layout_parentKeys &&
            menuItemProps.pro_layout_parentKeys.length > 0 &&
            menuItemProps.icon}
          {defaultDom}
        </Link>
      );
    },

加上这个二级菜单也可以显示了

**Comment by zhangshuling** [comment]
时间久了记不清了，好像就是按他们的回复改好的，但是我已经弃用了 antd 了，现在用的vue相关的








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 中午11:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/pro-components] pro-layout  menuDataRender 菜单多层级子层级icon图标不渲染 (#363)





   
请问一下，你这个图标不显示的问题最后怎么解决的呢？
 我现在是在 config.ts 里面配的菜单， icon 能正常显示，如果我把 菜单数据，直接写死，移到 menuDataRender 里面，虽然菜单能出来，但是 icon 出不来
 
  
这个是因为，接口返回的icon绘制时是string类型，需要自己做一个转换 你可以在utils文件夹下新建一个fixMenuItemIcon.ts文件
 import { MenuDataItem } from ***@***.***/pro-layout'; import * as allIcons from ***@***.***/icons'; // FIX从接口获取菜单时icon为string类型 const fixMenuItemIcon = (menus: MenuDataItem[], iconType='Outlined'): MenuDataItem[] =&gt; {   menus.forEach((item) =&gt; {     const {icon, children} = item     if (typeof icon === 'string') {       let fixIconName = icon.slice(0,1).toLocaleUpperCase()+icon.slice(1) + iconType       item.icon = React.createElement(allIcons[fixIconName] || allIcons[icon])     }     children &amp;&amp; children.length&gt;0 ? item.children = fixMenuItemIcon(children) : null   });   return menus }; export default fixMenuItemIcon;  
然后在app.tsx引入 import fixMenuItemIcon from './utils/fixMenuItemIcon'并修改其中的
 menuDataRender: () =&gt; {       return fixMenuItemIcon(initialState.menuData) },   
menuItemRender: (menuItemProps, defaultDom) =&gt; {
 if (menuItemProps.isUrl || !menuItemProps.path) {
 return defaultDom;
 }
 // 支持二级菜单显示icon
 return (
 
 {menuItemProps.pro_layout_parentKeys &amp;&amp;
 menuItemProps.pro_layout_parentKeys.length &gt; 0 &amp;&amp;
 menuItemProps.icon}
 {defaultDom}
 
 );
 },
 
加上这个二级菜单也可以显示了
