### ISSUE TITLE
🧐[问题] 升级到 antd 最新版 4.17.0-alpha 版后启动报错

### ISSUE THREAD

**Issue by timeLorder** [ant-design/pro-components#3632]
### 🧐 问题描述
项目升级到 antd 最新版 4.17.0-alpha 版后启动报错，报错截图见“其他信息”。希望作者有空能跟进下

### 💻 示例代码
猜测是 antd 为了动态主题改造成 css variables 模式后，ProTable 这边跨包引用导致的问题

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/40885641/132702450-1eff4236-037f-4c88-ad40-a0f169524a89.png)

**Comment by chenshuai2144** [comment]
还没兼容，working

**Comment by Nokecy** [comment]
~~~ 大概什么时候可以支持一波

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design/issues/32195
