### ISSUE TITLE
🐛[BUG]Protable文档文字描述有误

### ISSUE THREAD

**Issue by LSRPrice** [ant-design/pro-components#3633]
### 🐛 bug 描述

search.transform属性用途文字有误
### 🏞 期望结果
一般用于时间区间的转化

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/14809505/132707655-a2a7e61a-62e8-4da6-a41f-d007c6f29e0d.png)

**Comment by chenshuai2144** [comment]
直接来个pr吧。
