### ISSUE TITLE
🧐[问题] 查询（无按钮）表格上怎么触发request？

### ISSUE THREAD

**Issue by ingdaeho** [ant-design/pro-components#3634]
### 🧐 问题描述

![스크린샷 2021-09-10 오전 10 05 49](https://user-images.githubusercontent.com/62834439/132782352-5b35aa6e-41aa-4f0f-a1ef-3096dfbf97f8.png)
选创建时间之后，怎么让表格发request呢？
表格request params里没有我选的date

**Comment by chenshuai2144** [comment]
你让form onChange 的时候触发一个 `form.submit`

**Comment by mianlang** [comment]
设置了 formRef，实测 form 的 onChange 可以监听 Input 和 Radio，监听不到 DatePicker 变化。
form 的 onValuesChange 都可以。
