### ISSUE TITLE
🐛[BUG] pro-table 在 roadhog 搭建的项目编译时报错

### ISSUE THREAD

**Issue by zcorw** [ant-design/pro-components#364]
### 🐛 bug 描述

我在用 roadhog 搭建的项目中引入 pro-table 进过编译后运行时报错
<img width="685" alt="Snipaste_2020-09-01_15-06-25" src="https://user-images.githubusercontent.com/13196293/91813304-1bc57980-ec65-11ea-8b7e-0938cf94154c.png">
我发现 unstated-next 这个包被编译为 base64
<img width="652" alt="Snipaste_2020-09-01_15-34-59" src="https://user-images.githubusercontent.com/13196293/91820894-ef136100-ec68-11ea-8b5b-01d8e2a8e939.png">

### 🏞 期望结果

能在 roadhog 中正常运行

### 💻 复现代码

.webpackrc
```
{
  "devtool": "cheap-module-source-map",
  "theme": {
    "@primary-color": "#08BD53"
  },
  "extraBabelPlugins": [
    ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": true}]
  ]
}
```
webpack.config.js
```
module.exports = (webpackConfig, env) => {
  (webpackConfig.resolve.alias = {
    "@": `${__dirname}/src`,
  });
  return webpackConfig;
};
```
package.json
```
{
  "dependencies": {
      "@ant-design/pro-table": "^2.6.2"
  },
  "devDependencies": {
      "roadhog": "^2.5.0-beta.4"
  }
}
```

**Comment by chenshuai2144** [comment]
需要自己配置一下babel了 roadhog 好久没有更新了，尽快迁移吧
