### ISSUE TITLE
🐛[BUG]Cannot find name 'ProFieldValueType'

### ISSUE THREAD

**Issue by tool-service** [ant-design/pro-components#3646]
### 🐛 bug 描述
@ant-design/pro-form,version is >= 1.37.0,and the latest version 1.40.0 is also error.

yarn build error,

Cannot find name 'ProFieldValueType'

the all error info:

<img width="790" alt="image" src="https://user-images.githubusercontent.com/72132293/132950025-a3a9c254-5d37-44bc-8144-172208c5f6ca.png">

### 📷 复现步骤
1. yarn add @ant-design/pro-form@1.37.0
when  >=1.37.0 is error,<=1.36.0 is success.

2. yarn build

### 🏞 期望结果
yarn build success

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="703" alt="image" src="https://user-images.githubusercontent.com/72132293/132950040-d7f2e4fd-468e-4b28-b29b-ccbbdf7b6007.png">

**Comment by chenshuai2144** [comment]
发现d.ts 的tsc 有点问题。你先` "skipLibCheck": true,` 等我们修复一下
