### ISSUE TITLE
🧐[问题]ant design pro 里面如何让两个ProFormText联动

### ISSUE THREAD

**Issue by bieshaoxiong** [ant-design/pro-components#3655]
我想在一个 ProFormText输入某个字符的时候，另一个ProFormText根据一些规则自动输入某个字符。

我在第一个ProFormText里面加入了onChange事件来改变第二个ProFormText的值，我是这样操作的：
### 💻 示例代码
 <ProFormText
          name="customerProductCode"
          width={200}
          onChange={(event) => transformationCode(event)}
          rules={[
            {
              required: true,
              message:
                intl.formatMessage({ id: 'pages.customerProductCode' }) +
                intl.formatMessage({ id: 'pages.CannotBeempty' }),
            },
          ]}
          label={intl.formatMessage({ id: 'pages.customerProductCode' })}
          placeholder={intl.formatMessage({ id: 'pages.customerProductCode' })}
        />

const [INCCode, setIN3Code] = useState();

  const transformationCode = (event) => {
    let customeCode = '';
    let IN3Code = '';
    if (event && event.target && event.target.value) {
      customeCode = event.target.value;
    }
    let customeCodeLength = customeCode.length;
    for (var i = 0; i < customeCodeLength; i++) {
      const char = customeCode.substring(i, i + 1).toUpperCase();
      const item = codeRules[char];
      if (item) {
        IN3Code += item;
      } else {
        IN3Code += char;
      }
    }
    setIN3Code(IN3Code);
  };

<ProFormText
          name="productCode"
           value ={INCCode}
          disabled={true}
          tooltip={intl.formatMessage({ id: 'pages.productCodeTooltip' })}
          rules={[
            {
              required: true,
              message:
                intl.formatMessage({ id: 'pages.productCode' }) +
                intl.formatMessage({ id: 'pages.CannotBeempty' }),
            },
          ]}
          label={intl.formatMessage({ id: 'pages.productCode' })}
          placeholder={intl.formatMessage({ id: 'pages.productCode' })}
        />

这样操作，页面上可以显示出来数据，但是点击提交的时候无法通过验证，提示文本框不能为空。

后面我又用setFieldsValue:
### 💻 示例代码
 const transformationCode = (event) => {
    let customeCode = '';
    let IN3Code = '';
    if (event && event.target && event.target.value) {
      customeCode = event.target.value;
    }
    let customeCodeLength = customeCode.length;
    for (var i = 0; i < customeCodeLength; i++) {
      const char = customeCode.substring(i, i + 1).toUpperCase();
      const item = codeRules[char];
      if (item) {
        IN3Code += item;
      } else {
        IN3Code += char;
      }
    }
    form.setFieldsValue({ test: 'ABC' });
  };
<ProFormText
          name="productCode"          
          initialValues={form.getFieldValue('test')}
          disabled={true}
          tooltip={intl.formatMessage({ id: 'pages.productCodeTooltip' })}
          rules={[
            {
              required: true,
              message:
                intl.formatMessage({ id: 'pages.productCode' }) +
                intl.formatMessage({ id: 'pages.CannotBeempty' }),
            },
          ]}
          label={intl.formatMessage({ id: 'pages.productCode' })}
          placeholder={intl.formatMessage({ id: 'pages.productCode' })}
        />

这样 ProFormText里面根本就没有数据显示，但是把initialValues 换成value的话又有值显示，也是无法通过验证，请问我该怎么解决这个问题

**Comment by chenshuai2144** [comment]
```tsx
        <ProFormText name="name" label="姓名" />
        <ProFormText name="nickName" label="昵称" />
        <ProFormDependency name={['name']} ignoreFormListField>
          {({ name }) => {
            if (!name) {
              return null;
            }
            return <ProFormText name="remark" label="昵称详情" />;
          }}
        </ProFormDependency>

```
试试这个api

**Comment by bieshaoxiong** [comment]
> ```tsx
>         < ProFormText  name = "name"  label = "姓名"  / > 
>         < ProFormText  name = "nickName"  label = "昵称"  / > 
>         < ProFormDependency  name = { [ 'name' ] }  ignoreFormListField > 
>           { ( { name } )  =>  {
>             如果 （！名称） {
>               返回 空值；
>             }
>             返回 < name = "remark"  label = "昵称详情"  / > ; 
>           } } 
>         < / ProFormDependency >
> ```
> 
> 用这个api

如果我是想把 “remark”的数据赋值给“remark”应该怎么操作，我刚刚试了下
<ProFormText name="name" label="姓名" />
        <ProFormText name="nickName" label="昵称" />
        <ProFormDependency name={['name']} ignoreFormListField>
          {({ name }) => {
            debugger
            if (!name) {
              return null;
            }
            return <ProFormText name="remark" 
            rules={[
              {
                required: true,
                message:'不能为空',
              },
            ]}label="昵称详情"  value={name}/>;
          }}
        </ProFormDependency>
这样也是不能通过验证的。
![1631511838(1)](https://user-images.githubusercontent.com/64937534/133030020-36557dd3-b068-4e39-8701-5434d418feae.jpg)


使用 initialValue只有第一个字符能赋值成功：
        <ProFormText name="name" label="姓名" />
        <ProFormText name="nickName" label="昵称" />
        <ProFormDependency name={['name']} ignoreFormListField>
          {({ name }) => {
            debugger
            if (!name) {
              return null;
            }
            return <ProFormText name="remark" 
            rules={[
              {
                required: true,
                message:'不能为空',
              },
            ]}label="昵称详情"  initialValue={name}/>;
          }}
        </ProFormDependency>
![1631511892(1)](https://user-images.githubusercontent.com/64937534/133030070-12913cda-0b69-48fe-9517-eafde13c4ebf.jpg)

**Comment by tylerrrkd** [comment]
the same problem with you, and how did you solve it?

> > ```tsx
> >         < ProFormText  name = "name"  label = "姓名"  / > 
> >         < ProFormText  name = "nickName"  label = "昵称"  / > 
> >         < ProFormDependency  name = { [ 'name' ] }  ignoreFormListField > 
> >           { ( { name } )  =>  {
> >             如果 （！名称） {
> >               返回 空值；
> >             }
> >             返回 < name = "remark"  label = "昵称详情"  / > ; 
> >           } } 
> >         < / ProFormDependency >
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 用这个api
> 
> 如果我是想把 “remark”的数据赋值给“remark”应该怎么操作，我刚刚试了下 <ProFormDependency name={['name']} ignoreFormListField> {({ name }) => { debugger if (!name) { return null; } return <ProFormText name="remark" rules={[ { required: true, message:'不能为空', }, ]}label="昵称详情" value={name}/>; }} 这样也是不能通过验证的。 ![1631511838(1)](https://user-images.githubusercontent.com/64937534/133030020-36557dd3-b068-4e39-8701-5434d418feae.jpg)
> 
> 使用 initialValue只有第一个字符能赋值成功： <ProFormDependency name={['name']} ignoreFormListField> {({ name }) => { debugger if (!name) { return null; } return <ProFormText name="remark" rules={[ { required: true, message:'不能为空', }, ]}label="昵称详情" initialValue={name}/>; }} ![1631511892(1)](https://user-images.githubusercontent.com/64937534/133030070-12913cda-0b69-48fe-9517-eafde13c4ebf.jpg)

**Comment by tylerrrkd** [comment]
[FAQ: 当我动态改变 defaultValue 的时候它并没有生效](https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82)
