### ISSUE TITLE
🐛[BUG]ProTable Columns dataIndex重复导致request调用错误

### ISSUE THREAD

**Issue by luobinhang** [ant-design/pro-components#3658]
### 🐛 bug 描述
ProTable Columns dataIndex重复导致request调用错误

### 💻 示例代码
https://codesandbox.io/s/toolbar-zi-ding-yi-forked-z8o9v?file=/App.tsx
切换tab的时候 应该调用对应的request，但是他们走了相同的cache

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/22189838/133046784-eba1a051-b306-4e37-9a9e-e7ecbaa35e65.png)

这里的proFieldKey  dataIndex的优先级高于 key，我觉得自定义key的优先级应该更高才对

**Comment by chenshuai2144** [comment]
听起来name不应该相同。

**Comment by luobinhang** [comment]
> 听起来name不应该相同。

这个不太好避免呢，因为多个tab切换的时候 容易碰到dataIndex重复的情况 这个时候就会写不同的key，我觉得这个proFieldKey应该以key为主的 对吧

**Comment by luobinhang** [comment]
因为我看其他部分的代码逻辑都是以key值为主呢
![image](https://user-images.githubusercontent.com/22189838/133064476-ee09c49c-c7db-478f-893b-b21abb1fd38c.png)
![Uploading image.png…]()

**Comment by chenshuai2144** [comment]
有兴趣来个pr吗？
