### ISSUE TITLE
🧐[问题]使用ProFormDependency的时候，有没有办法在被依赖项改变的时候，将依赖项的value设置为初始值

### ISSUE THREAD

**Issue by GitKou** [ant-design/pro-components#3663]
## 代码示例
🔗：https://codesandbox.io/s/proformdependency-29jrv?file=/App.tsx
## 截图
ProSelect的options依赖于name的值，当name的值更改后，期望select已选的值能够清空

![image](https://user-images.githubusercontent.com/7437397/133210554-307d5623-0656-4a52-a862-23a380352bbf.png)

**Comment by chenshuai2144** [comment]
第二个参数是form，直接 reset 好了

**Comment by GitKou** [comment]
> 第二个参数是form，直接 form.reset 好了

谢谢回复。
在ProFormList里如何确定当前的namepath？

**Comment by chenshuai2144** [comment]
还没实现，现在只能自己算了

**Comment by sunnala** [comment]
可以通过在姓名组件上增加onChange事件，通过action.setCurrentRowData()方法清空
`
action.setCurrentRowData({
 user: null
})
`

**Comment by ScotchPie** [comment]
新版本的ProformList暴露了field和index字段，可以通过list名称+index定位目标字段了
`<ProFormList>
     { ( field, index ) => <ProFormDependency /> }
</ProFormList>`

大致思路
![无标题](https://github.com/ant-design/pro-components/assets/109577566/869bbde7-e1c3-4fda-9b63-874f8add5795)
