### ISSUE TITLE
ProFormUploadButton组件在编辑时怎么赋值给file

### ISSUE THREAD

**Issue by huangguangpo** [ant-design/pro-components#3668]
<ProFormUploadButton
              name="upload"
              label="卡牌图片"
              max={1}
              fieldProps={{
                name: 'file',
                listType: 'picture-card',
                maxCount: 1,
                // https://github.com/ant-design/pro-components/issues/794 自定义添加请求头
                headers: { 
                  Authentication: Cookies.get('token'),
                },
              }}
              action="/api/v2/nft/cardImage"
              rules={[{ required: true, message: '请上传卡牌图片' }]} 
              onChange={onChange}
            />

设置了max 为 1 ，在编辑回显时，尝试用了fileList 来赋值，但是会多出上传图片的按钮，有什么办法直接赋值给file吗

**Comment by chenshuai2144** [comment]
fieldProps 里面得 value 重置一下

**Comment by hst-Sunday** [comment]
请问具体的操作方法有吗？我现在也卡在这一步了！@chenshuai2144
