### ISSUE TITLE
🐛[BUG] ProTable 使用 renderFormItem 自定义搜索表单,点击重置按钮,会重复触发自定义组件的useEffect

### ISSUE THREAD

**Issue by furylee** [ant-design/pro-components#3675]
### 🐛 bug 描述
ProTable 使用 renderFormItem 自定义搜索表单,点击重置按钮,会重复触发自定义组件的useEffect
```
const CInput = (props) => {
  useEffect(() => {
    console.log("重复触发");
  }, [1]);

  return <Input {...props} />;
};

{
    title: "自定义组件会重复触发",
    dataIndex: "test",
    hideInTable: true,
    renderFormItem: (
      _,
      { type, defaultRender, formItemProps, fieldProps, ...rest }
    ) => {
      return <CInput {...rest} />;
    }
  },
```

### 📷 复现步骤
点击重置,查看控制台

### 🏞 期望结果
不会重复触发

### 💻 复现代码
https://codesandbox.io/embed/cha-xun-biao-ge-forked-n9tpb?fontsize=14&hidenavigation=1&theme=dark

### © 版本信息

- ProComponents 版本: [e.g. 2.53.1]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
重置会导致组件销毁，因为key改变了，这是个性能问题。
