### ISSUE TITLE
🐛[BUG]prolayout组件无法兼容IE11

### ISSUE THREAD

**Issue by ALL-STACK** [ant-design/pro-components#3677]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/24264872/133414122-9fc54986-6241-49ec-9797-4fac85d5d5aa.png)

### 📷 复现步骤
https://github.com/ALL-STACK/umi-web.git

**Comment by chenshuai2144** [comment]
为啥不兼容 最好找下原因

我们现在没有Ie设备

**Comment by ALL-STACK** [comment]
> 为啥不兼容 最好找下原因
> 
> 我们现在没有Ie设备

![image](https://user-images.githubusercontent.com/24264872/133533036-1fb115f6-927a-450b-9273-8c062a5f69cd.png)
![image](https://user-images.githubusercontent.com/24264872/133533066-d6f163da-b454-4596-a7c4-f4ae8bb82f8b.png)

**Comment by chenshuai2144** [comment]
已经修复了，可以更新依赖重新打包了，
是swr 的问题
