### ISSUE TITLE
🐛[BUG]antd pro components 切换分页请求缓慢

### ISSUE THREAD

**Issue by shixxbi131** [ant-design/pro-components#3681]
### 🐛 bug 描述

当设置每页条数超过20条，去切换分页，触发后端请求缓慢，并且控制台打印出延迟信息

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/13976483/133586083-e93f44b5-33e3-4940-b0d7-987fa3fabf57.png)

### 🏞 期望结果

快速触发

### © 版本信息

- ProComponents 版本: 最新版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
是行数太少导致页面卡住了吗？

**Comment by shixxbi131** [comment]
不是，是行数很多呢，每页20条或者50条这种特别卡，但是每页5条，去分页请求触发就很快

**Comment by shixxbi131** [comment]
> 是行数太少导致页面卡住了吗？ 延迟1000ms 这个卡顿很厉害了

在切换页数时，比如从2到3，反应就很慢，页数差不多1000ms后才变成选中3，然后去请求后端资源，现在看的表现是前端切页数反应很慢，发送请求到后端返回请求速度很快的。

**Comment by shixxbi131** [comment]
![image](https://user-images.githubusercontent.com/13976483/134792239-c0ddbf28-7e6c-421c-b814-0609dc951a7a.png)
越来越慢了，希望尽快帮忙看下问题

**Comment by defolly** [comment]
每页显示300条记录，表格的选择行基本用不了，卡得不要不要的
