### ISSUE TITLE
👑 [需求]Protable收起按钮，如何只对指定条件收起呢

### ISSUE THREAD

**Issue by jaw52** [ant-design/pro-components#3682]
### 🧐 问题描述
有没有办法实现，点击Protable收起按钮，收起指定的部分查询条件，而保留部分条件呢？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 💡 解决方案
可以通过在 `Protable` 的 `searchConfig` 属性中使用 `fields` 属性来实现收起部分查询条件的功能。

具体来说，可以将需要收起的查询条件通过 `fields` 属性的 `hideInTable` 字段隐藏起来，然后在页面中添加一个收起按钮，通过监听点击事件来控制哪些条件需要被收起。

下面是一个示例代码：

```jsx
import React, { useState } from 'react';
import ProTable from '@ant-design/pro-table';

const columns = [
  {
    title: '编号',
    dataIndex: 'id',
    hideInSearch: true,
  },
  {
    title: '名称',
    dataIndex: 'name',
  },
  {
    title: '状态',
    dataIndex: 'status',
    hideInSearch: true,
  },
  {
    title: '创建时间',
    dataIndex: 'createdAt',
    hideInSearch: true,
  },
];

const data = [
  {
    id: 1,
    name: '测试1',
    status: '已启用',
    createdAt: '2021-01-01',
  },
  {
    id: 2,
    name: '测试2',
    status: '已禁用',
    createdAt: '2021-01-02',
  },
];

export default function MyTable() {
  const [fields, setFields] = useState([]);

  const handleToggleFields = () => {
    setFields(prevFields => {
      if (prevFields.length === 0) {
        // 如果当前没有隐藏字段，则添加需要隐藏的字段
        return [
          {
            name: 'status', // 需要隐藏的查询条件的name
            key: 'status',
            hideInTable: true,
          },
          {
            name: 'createdAt',
            key: 'createdAt',
            hideInTable: true,
          },
        ];
      } else {
        // 如果当前有隐藏字段，则移除所有隐藏字段
        return [];
      }
    });
  };

  return (
    <div>
      <button onClick={handleToggleFields}>收起/展开</button>
      <ProTable
        columns={columns}
        dataSource={data}
        search={{ fields }}
      />
    </div>
  );
}
```

在代码中，我们定义了一个 `fields` 状态，用于保存需要被隐藏的查询条件。当点击收起按钮时，我们根据当前的 `fields` 状态来判断执行收起或展开逻辑。

当需要隐藏字段时，我们通过 `setFields` 函数修改 `fields` 的值，将需要被隐藏的 `status` 和 `createdAt` 添加到 `fields` 中。

在 `ProTable` 组件中，我们通过 `search` 属性将 `fields` 传递给 `ProTable`，并配置了 `status` 和 `createdAt` 的 `hideInTable` 属性，使它们可以被收起。

这样，当点击收起按钮时，对应的查询条件就会被隐藏或展开。

### 📚 相关文档
- ProTable文档：https://procomponents.ant.design/components/table#searchprops

**Comment by chenshuai2144** [comment]
不支持，也不推荐这样使用
