### ISSUE TITLE
🧐[问题]通过webpack externals 引入 PorTable、ProForm 报错

### ISSUE THREAD

**Issue by gitlwz** [ant-design/pro-components#3686]
### 🧐 问题描述

项目特殊需求需要通过外链的形式引入，在引入ProTable，ProForm使用会报错

### 💻 示例代码
####html
  <script src="https://cdn.jsdelivr.net/npm/react@17.0.2/umd/react.development.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/react-dom@17.0.2/umd/react-dom.development.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/moment@2.29.1/moment.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/moment@2.29.1/locale/zh-cn.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@ant-design/icons@4.6.4/dist/index.umd.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/antd@4.6.3/dist/antd.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@ant-design/pro-form@1.40.0/dist/form.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@ant-design/pro-provider@1.4.17/dist/provider.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@ant-design/pro-table@2.53.1/dist/table.js"></script>
#### webpack

    react: "React",
    "react-dom": "ReactDOM",
    moment: "moment",
    "@ant-design/icons": "icons",
    antd: "antd",
    "@ant-design/pro-table": "ProTable",
    "@ant-design/pro-provider": "ProProvider",
    "@ant-design/pro-form": "ProForm",

antd、icon 都没问题，只有pro-table、pro-form 有问题
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23609865/133726393-8ce74adf-57ba-407a-9e16-ee031e203d7b.png)

**Comment by chenshuai2144** [comment]
antd 的版本太低了，用最新版
