### ISSUE TITLE
🧐[问题] 拖拽排序与嵌套子表格产生干涉

### ISSUE THREAD

**Issue by hairanze** [ant-design/pro-components#3687]
#### 我参考了protable里面的“拖拽排序”部分的演示代码，参考于https://codesandbox.io/s/6rj4g ，也实现了这部分的功能，但是对原有expand功能产生了影响，表现为：只能展开，不能关闭子表格。

我在查了elemens后对比了前后两种情况，这一张是未加入sorting时候的结构
<img width="617" alt="截屏2021-09-17 下午2 50 08" src="https://user-images.githubusercontent.com/43596168/133737628-3cb2327a-4af9-46a4-bf78-e2992be08259.png">

这张是加入了sorting的结构
<img width="1033" alt="截屏2021-09-17 下午2 50 26" src="https://user-images.githubusercontent.com/43596168/133737651-62876bf3-79d9-4bea-83d4-76f80a388a0f.png">
>

感觉是加入的这部分影响了原有antd-expand-row-level的级别
<img width="786" alt="截屏2021-09-17 下午2 57 32" src="https://user-images.githubusercontent.com/43596168/133738652-7c31e207-67e7-40c8-bb31-f4906c204883.png">

**Comment by chenshuai2144** [comment]
https://codesandbox.io/s/tuo-zhuai-pai-xu-forked-gm2j2

看起来是可以用的，但是样式有点问题

**Comment by hairanze** [comment]
> https://codesandbox.io/s/tuo-zhuai-pai-xu-forked-gm2j2
> 
> 看起来是可以用的，但是样式有点问题

我实际测试的时候，只能展开嵌套表格，但是不能闭合嵌套表格

**Comment by hairanze** [comment]
> https://codesandbox.io/s/tuo-zhuai-pai-xu-forked-gm2j2
> 
> 看起来是可以用的，但是样式有点问题

https://codesandbox.io/s/tuo-zhuai-pai-xu-forked-mbh6k?file=/App.tsx
我改用了我在project里面的写法，用expandedRowRender去渲染一个嵌套表格，codesandbox实测可以复现只能展开，不能闭合
