### ISSUE TITLE
ProForm触发request以后，展示内容不刷新🧐[问题]

### ISSUE THREAD

**Issue by cui-xxu** [ant-design/pro-components#3688]
### 🧐 问题描述

一个机构维护功能，左侧机构树，右侧机构维护表单。
假设机构树有4个机构，点击机构1、机构2都正常，再点击机构1，后台服务和DevTools都能看出request被正常调用，但是右侧表单内容未刷新，还是显示机构2的信息。

### 💻 示例代码

```
function getDetail(body: BASEFRAME.SysOrganizationModel,
  options?: Record<string, any>) {
    return request<BASEFRAME.SysOrganizationModel>('/api/admin/orgmanage/getDetail.do', {
      method: 'POST',
      data: body,
      ...(options || {}),
    });
}
const OrgMng: React.FC = () => {
  /** 当前机构对象，查询详细信息使用 */
  const [curOrg, setCurOrg] = useState<BASEFRAME.SysOrganizationModel>();
  /** 登录后初始化的前台全局变量 */
  const { initialState } = useModel('@@initialState');

  return (
    <PageContainer>
      <ProCard split="vertical">
        <ProCard title="机构列表" colSpan="20%">
          <Tree
            treeData={initialState?.orgDict}
            defaultExpandAll
            showLine
            onSelect={(_, info) => {
              setCurOrg({ orgcode: info.node.key as string });
            }}
          />
        </ProCard>
        <ProCard title="机构信息维护" headerBordered>
            <ProForm
              layout="horizontal"
              params={curOrg}
              request={getDetail}
              onFinish={save}
            >
              <ProFormText name='orgcode' label='机构编号' />
              <ProFormText name='orgname' label='机构名称' />
              <ProFormText name='orgshortname' label='机构简称'  />
              <ProFormText name='superorgcode' label='上级机构编号' />
              <ProFormText name='superorgname' label='上级机构名称'  />
              <ProFormText name='adminRegion' label='行政区划' />
              <ProFormText name='orgdesc' label='机构描述' />
            </ProForm>
        </ProCard>
      </ProCard>
    </PageContainer>
  );
};
export default OrgMng;
```

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/134308358-b0247a78-410f-40ef-bc01-f48228dc62e1.png)

**Comment by cui-xxu** [comment]
额，不是request的执行结果，自动赋给initvalue吗

**Comment by chenshuai2144** [comment]
他也是惰性的，只会用第一次,你最好用params重新触发一下，

**Comment by cui-xxu** [comment]
> 他也是惰性的，只会用第一次,你最好用params重新触发一下，

在tree的onSelect里更新params了，后台服务和DevTools都能看出request被触发了，但是form显示的内容没有刷新

**Comment by chenshuai2144** [comment]
只有第一次才会生效 毕竟是initial values

**Comment by cui-xxu** [comment]
感谢您的回答！那我这种点击树节点刷新form的需求，就不能用params/request机制实现了是吧，只能拿formRef调用setFieldsValue？

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/134530995-f2a8e8d1-cf27-4d3c-b224-daf2fe0e0dc6.png)

![image](https://user-images.githubusercontent.com/32530210/134531141-543bea0d-fbdb-467c-bb84-0b7c5a1d578b.png)

**Comment by cui-xxu** [comment]
不好意思，没看明白怎么能解决我的问题*_* 我现在点击树节点以后更新params，自动触发request，这个过程是没问题的，问题是收到request的应答数据以后，form的内容没有刷新

**Comment by chenshuai2144** [comment]
rquest 请求的是 initvalues，他只会第一次生效，你强制把form初始化一下

**Comment by hanwenbo** [comment]
> 给他设置一个key。key 变化就会清空重来

@chenshuai2144 不行   我试了下给form加key   request不会重新执行

**Comment by chenshuai2144** [comment]
那就是数据问题了，

https://github.com/ant-design/pro-components/issues/4521?notification_referrer_id=NT_kwDOAHzrKLIyOTkyNjk2NTE1OjgxODY2NjQ&notifications_query=is%3Aunread


看看这个

**Comment by hesetiema** [comment]
我遇到了 formKey 设置为常量，request虽然请求了最新的数据，但 initialData 并未设置进去，去除 formKey 即可。

**Comment by AburronKing** [comment]
给Form表单价格key={xxxx} 我这边是解决了
