### ISSUE TITLE
🐛[BUG] protable 拖拽只能work一次

### ISSUE THREAD

**Issue by jiamianmao** [ant-design/pro-components#3689]
### 🐛 bug 描述

使用 pro-table 的内部拖拽表格时候，如果把 column 写在组件内部，拖拽一次后，拖拽按钮就消失不见

### 📷 复现步骤

https://codesandbox.io/s/y65ny  只需要把  column 和 columns 放到 export default 内部 即可

### 🏞 期望结果

一直可以使用拖拽功能

### © 版本信息

- protable 2.54.0

**Comment by jiamianmao** [comment]
为什么使用 useMemo 即可 work success

**Comment by kiner-tang** [comment]
> 为什么使用 useMemo 即可 work success

正常情况下`columns`在生成表格前就是确定的，为什么要放在export default中，每次渲染都重新赋值呢？如果一定要放在内部，使用`useMemo`包裹进行缓存，不至于每一次渲染都重新解析。如果有特殊情况，你可以详细描述你的使用场景。

**Comment by jiamianmao** [comment]
现在还是有问题~~
我看你提交的merged后的代码里，在 columns 里使用 state，拿不到最新的值。
