### ISSUE TITLE
🐛[BUG]protable 2.6.3 columnEmptyText设置不生效

### ISSUE THREAD

**Issue by betty0417** [ant-design/pro-components#369]
### 🐛 bug 描述

proTable 2.6.3版本 设置columnEmptyText={false}或columnEmptyText={"---"}后，空值字段值都显示为空，并没有显示成"-"

### 🏞 期望结果

空值显示成“-”

### © 版本信息

proTable 2.6.3
OS:maxOS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/58725690/91934900-0c0a6b80-ed1f-11ea-908a-fc02d60914f1.png)

**Comment by WoodsLiu** [comment]
columnEmptyText如果是false的话,是默认显示"-"吗?

**Comment by chenshuai2144** [comment]
会什么都不显示

**Comment by WoodsLiu** [comment]
还是有一个问题吧, 假如说有一个字段值是`undefined`,我们理所当然的默认显示`columnEmptyText`,但是如果字段值是`''`、`null`、`false`呢,在React jsx渲染中`''`、`null`和`false`都不会进行渲染,然后就会出现空白的效果,就会给用户带来一个疑惑,我明明设置了`columnEmptyText`,但怎么不显示呢?这种情况是原样显示成空白,还是显示`columnEmptyText`

**Comment by WoodsLiu** [comment]
还有两种情况没有考虑:
1. 如果`valueType`是`text`,源码中不会走render, 此时如果text是undefined的话, 不会显示`columnEmptyText`
2. 如果`valueType`是函数, 这个时候如果text是undefined的值, 也不会显示`columnEmptyText`

所以我的意见是, 如果是 `''`、`null`、`undefined`、`false`都显示默认的`columnEmptyText`.

```tsx
const defaultRender = () => {
  // 如果 valueType === text ，没必要多走一次 render
  if ((!valueType || valueType === 'text') && !props?.valueEnum) {
    // 如果是''、null、undefined、false 显示columnEmptyText
    return [false, '', null, undefined].includes(text as any) ? columnEmptyText : text;
  }

  if (typeof valueType === 'function' && item) {
    const value = valueType(item);
    if (!value) {
      return columnEmptyText;
    }
    // 防止valueType是函数,并且text是false、null、undefined、''跳过显式设置的emptyText
    return defaultRenderText(text, value as ProFieldValueType, index, item, columnEmptyText, props);
  }
};
```
