### ISSUE TITLE
🧐[问题] 有关Protable的渲染使用问题

### ISSUE THREAD

**Issue by suguer** [ant-design/pro-components#3698]
### 🧐 问题描述
官方文档 https://procomponents.ant.design/components/table#valueEnum
在protable的columns的render里面,可以正常渲染Tag 标签,但是我引用的时候就会提示 报错
  {
    title: '标签',
    dataIndex: 'labels',
    search: false,
    renderFormItem: (_, { defaultRender }) => {
      return defaultRender(_);
    },
    render: (_, record) => (
      <Space>
        {record.labels.map(({ name, color }) => (
          <Tag color={color} key={name}>
            {name}
          </Tag>
        ))}
      </Space>
    ),
  },

报错信息 
devScripts.js:6523 [@umijs/runtime] load component failed Error: Module "./antd/es/tag/style" does not exist in container.
while loading "./antd/es/tag/style" from webpack/container/reference/mf
    at mf-va_remoteEntry.js:717

Uncaught (in promise) Error: Module "./antd/es/tag/style" does not exist in container.
while loading "./antd/es/tag/style" from webpack/container/reference/mf
    at mf-va_remoteEntry.js:717

### 💻 示例代码

{
      title: '状态',
      dataIndex: 'Status',
      search: false,
      render: (_, entity) => {
        let intStatus = 1;
        if (entity.Action && entity.Action.IDAAction) {
          intStatus = parseInt(entity.Action.intStatus, 10);
        }
        return (
            <Tag>{(intStatus === 0 ? (
              '未交费'
            ) : (
              <FormattedMessage id={`domain.dns.status.${entity.Status}`} />
            ))}
            </Tag>
          )
      },

**Comment by chenshuai2144** [comment]
mfsu的问题，删除 .umi 文件夹，然后重新启动一下
