### ISSUE TITLE
👑 [需求] ProField 叫 原子组件

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-components#37]
ProField 叫 原子组件，这个名字有没有一个更合适点的叫法啊？

**Comment by chenshuai2144** [comment]
你可以直接来 pr，这个名字的确不是很好

**Comment by kaoding** [comment]
我也没有太想叫什么名字，想了一个叫：值域

**Comment by WynterDing** [comment]
`值域` 颇有些 old-school 的味道，感觉叫 `字段` 也没毛病

**Comment by rdmclin2** [comment]
字段 + 1

**Comment by yutingzhao1991** [comment]
这个应该就不要对外暴露了。理论上我们是不希望开发者直接使用的，考虑是不是直接从菜单里面移除。
