### ISSUE TITLE
🧐[问题] lightProps 如何使用？

### ISSUE THREAD

**Issue by nxboo** [ant-design/pro-components#3700]
### 🧐 问题描述

https://github.com/ant-design/pro-components/issues/3564

@chenshuai2144 在这个issue里说用 

lightProps={{
            labelFormatter: () => 'xx',
          }}

但无论加到什么位置都没有效果

**Comment by chenshuai2144** [comment]
加到formItem上面

**Comment by qiangxinglin** [comment]
@nxboo 老哥你要是解决了发个demo吧

**Comment by nxboo** [comment]
@qiangxinglin 没解决啊，老弟。我先用时间日期组件了。很无耐啊
@chenshuai2144 首先感谢你的回复
我理解应该加在这个位置，但没有作用，能不能帮我看一下？

<img width="1328" alt="WX20210924-154214@2x" src="https://user-images.githubusercontent.com/4253172/134637626-79e941ef-654d-40b9-992a-eac44b8cebf2.png">

https://codesandbox.io/s/throbbing-water-4usts?file=/App.tsx
