### ISSUE TITLE
hidden in ProFormText, value can't get in formRef.current?.getFieldsValue()

### ISSUE THREAD

**Issue by narayandreamer** [ant-design/pro-components#3703]
### 🐛 bug 描述

When hidden true is set in ProFormText it hides the UI but drawback is that the value doesn't come when called by

`formRef.current?.getFieldsValue()`

          
### 💻 复现代码

```
</Form.Item>
          <ProFormText
            name="profile_pics"
            label="Profile Pic"
            width="md"
            hidden
            style={{'height': 0, 'width': 0}}
            placeholder="Profile Pic Object"
            rules={[{ required: true }]}
          />
```

### © 版本信息

- ProComponents 4.0.0
- @ant-design/pro-form: 1.32.1
- antd
- mac OS

**Comment by chenshuai2144** [comment]
you can use `formRef.current?.getFieldsValue(true)`， it will get all fileds
