### ISSUE TITLE
🧐[问题] column定义中用了valueType: 'textarea'，没效果

### ISSUE THREAD

**Issue by hairanze** [ant-design/pro-components#3707]
### 🧐 问题描述

我本地测试了pro-tabe里面用valueType: 'textarea'，希望得到类似于antd中input的textarea的效果，但是测试几次都只是普通的text输入框，并不是textarea的效果。下面是我在code sandbox里面写的用例

### 💻 示例代码
  {
    title: '姓名',
    dataIndex: 'name',
    hideInTable: true,
    valueType: 'textarea',
 }

https://codesandbox.io/s/columnzhong-textareabu-sheng-xiao-v03yq?file=/App.tsx

**Comment by chenshuai2144** [comment]
列配置里面的 textarea 就是 text， 查询表单里面放不下那么大的框

**Comment by ldwonday** [comment]
@chenshuai2144 这个希望可以支持，目前做的需求里面，好多需要查询里出现textarea。

**Comment by chenshuai2144** [comment]
为什么会需要 textarea ，放不下吧？

**Comment by Scarlett-Liang-huatek** [comment]
我也在查询条件中需要用文本域，这个一直不展示的问题，原来是因为这个，害我找了好长时间

**Comment by LK19931225** [comment]
我也是查询表单需要textArea文本域效果，然后设置了valueType为textarea不生效，展示还是input输入框的效果，希望支持
