### ISSUE TITLE
请让 ProLayout 支持ssr

### ISSUE THREAD

**Issue by stfenjobs** [ant-design/pro-components#371]
### 🥰 需求描述
ProLayout 支持ssr

**Comment by chenshuai2144** [comment]
需要做什么？

**Comment by stfenjobs** [comment]
谢谢回复  @chenshuai2144 

因为我用的是nextjs,需要服务端渲染功能，  但是我测试中，发现 ProLayout 不支持服务端渲染

这里有个例子 https://github.com/vercel/next.js/blob/canary/examples/with-ant-design-pro-layout-less/layouts/main.tsx#L13 ，
但也不支持服务端渲染，他用的异步导入， 我改成普通导入后，执行会报错，

我在 以前的 旧仓库搜到了一些 issue ，https://github.com/ant-design/ant-design-pro-layout/issues/96   发现ProLayout确实不支持ssr（服务端渲染）

参考：
https://github.com/ant-design/ant-design-pro-layout/search?q=ssr&type=Issues

**Comment by chenshuai2144** [comment]
你要列举出来，我们已经注意了Windows的使用 不清楚还有哪里有问题

**Comment by dzcpy** [comment]
为啥关了？想问下楼主解决问题了吗？我也要在 Next.js 里用感觉好多问题

**Comment by dzcpy** [comment]
@chenshuai2144 比如这里有直接对 document.body 的引用。导致无法支持 ssr
想问下会考虑修复吗？或者，愿意接受 pr 吗？
https://github.com/ant-design/pro-components/blob/fda307d11c849a02c9d30e1c5a876588f532609d/packages/layout/src/demos/base.tsx#L307

**Comment by dzcpy** [comment]
@chenshuai2144 比如这里有直接对 document.body 的引用。导致无法支持 ssr
想问下会考虑修复吗？或者，愿意接受 pr 吗？

https://github.com/ant-design/pro-components/blob/master/packages/layout/src/components/FooterToolbar/index.tsx#L63

**Comment by chenshuai2144** [comment]
直接pr吧
