### ISSUE TITLE
🐛[BUG] 存在分组表头的情况下，子级表头设置ellipsiss属性时，未自动设置tableLayout为fixed

### ISSUE THREAD

**Issue by rumunanfeng** [ant-design/pro-components#3714]
### 🐛 bug 描述

存在分组表头的情况下，子级表头设置ellipsiss属性时，未自动设置tableLayout为fixed
验证过ant design无此问题

### 📷 复现步骤

设置子级表头ellipsiss属性时
![image](https://user-images.githubusercontent.com/37805363/134300454-42a07cd7-4b50-4598-9b2e-39460f0445b3.png)

发现表格的tableLayout未变成fixed
但是当设置父级表头ellipsiss属性时
![image](https://user-images.githubusercontent.com/37805363/134300522-80732235-118d-480b-8f39-610e005629fa.png)

### 🏞 期望结果

无论是设置父级表头还是子级表头的ellipsiss属性，tableLayout均可以默认修改为fixed

### 💻 复现代码

https://codesandbox.io/s/cha-xun-biao-ge-forked-qmwdc?file=/App.tsx

### © 版本信息

- ProComponents 版本: [@ant-design/pro-table：2.53.1]
- umi 版本
- 浏览器环境
- 开发环境 [windows]

**Comment by chenshuai2144** [comment]
修复咯。可以更新版本了

**Comment by chenshuai2144** [comment]
看CSS里面变了
