### ISSUE TITLE
protable 的 search dateTime 中英文混合🐛[BUG]

### ISSUE THREAD

**Issue by haydenull** [ant-design/pro-components#3717]
### 🐛 bug 描述

proTable 的 search，其中之一为 dateTime 时，该dateTime组件为中英文混合状态

### 📷 复现步骤

点击「创建时间」

### 🏞 期望结果

显示中文月份及星期

### 💻 复现代码

https://codesandbox.io/s/t7fvh?file=/package.json

### © 版本信息

- ProComponents 版本: [ 2.54.2]
- umi 版本 3.5.19
- 浏览器环境 chrome 93.0.4577.82
- 开发环境 [mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/17695989/134315258-dfc061f0-44e1-4397-95d1-5fedf50f52a1.png)

**Comment by chenshuai2144** [comment]
你应该是moment的配置问题 去设置下moment的Locale
