### ISSUE TITLE
🧐[问题]ProFormSelect labelInValue属性无效

### ISSUE THREAD

**Issue by bieshaoxiong** [ant-design/pro-components#3725]
### 🧐 问题描述
labelInValue属性无效

### 💻 示例代码
 <ProFormSelect
         width={200}
          name="poductId"
          optionLabelProp="children"
          showSearch
          labelInValue
          onChange={poductCodeChange}
          filterOption={(input, option) =>
            option.children.toLowerCase().indexOf(input.toLowerCase()) >= 0
          }
          rules={[
            {
              required: true,
              message:
                intl.formatMessage({ id: 'pages.selectProductCode' }) +
                intl.formatMessage({ id: 'pages.CannotBeempty' }),
            },
          ]}
          label={intl.formatMessage({ id: 'pages.selectProductCode' })}
          placeholder={intl.formatMessage({ id: 'pages.selectProductCode' })}
          request={async () => {
            let params = await getProductsAll();
            let res = [];
            params.data.map((item) => {
              let temp = {};
              temp['label'] = item.productCode;
              temp['value'] = item.id;
              res.push(temp);
            });
            return res;
          }}
        />

  const poductCodeChange=(value)=>
  {
    const text=value
    debugger
  }

poductCodeChange方法里面的参数只有ProFormSelect value的值

**Comment by chenshuai2144** [comment]
fieldProps

**Comment by bieshaoxiong** [comment]
哥  没懂什么意思  意思是让我用fieldProps绑定数据吗？
我刚刚试着用fieldProps绑定数据， 可是onchang 传的值还是value,还是去不到lable

**Comment by bieshaoxiong** [comment]
> 字段道具

哥 没懂什么意思 意思是让我用fieldProps绑定数据吗？
我刚刚试着用fieldProps绑定数据， 可是onchang 传的值还是value,还是去不到lable

**Comment by bieshaoxiong** [comment]
> fieldProps

![image](https://user-images.githubusercontent.com/64937534/134461705-668804b7-47cd-4077-b33a-34e868a9c54b.png)
写成这样也不行

**Comment by bieshaoxiong** [comment]
![image](https://user-images.githubusercontent.com/64937534/134463787-df5c03e2-a5c2-4cc3-a2d7-30c397111c52.png)
emmmmmmmmmmmmmmm可以了
