### ISSUE TITLE
🐛[BUG] ProList 卡片列表没有description

### ISSUE THREAD

**Issue by stormrise** [ant-design/pro-components#3726]
### 🐛 bug 描述

ProList 卡片列表没有description
onRow也不生效

### 💻 复现代码
https://codesandbox.io/s/qia-pian-lie-biao-forked-5txjb?file=/App.tsx

### © 版本信息

- ProComponents 版本: "@ant-design/pro-list": "^1.14.3",
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Tokiomi** [comment]
我也遇到了。。求修复

**Comment by chenshuai2144** [comment]
现在只支持 content 因为内容不知道怎么格式化

**Comment by Tokiomi** [comment]
ProList卡片列表，的onRow不生效，求修复

**Comment by stormrise** [comment]
> 现在只支持 content 因为内容不知道怎么格式化

收到，我改用普通的list了

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


关于 ProList 卡片列表的 onRow 不生效的问题，该问题在 ProList 的 GitHub Issue 中也有提到，可参考该链接中的讨论 https://github.com/ant-design/ant-design-pro/issues/7886。

欢迎提供 Pull Request 来解决问题，贡献您的代码解决这个问题。同时，如果您需要使用类似的功能，我们建议您可以尝试通过使用 Ant Design 的 List 组件来实现类似的效果。Ant Design 的 List 组件中，可以通过设置 List.Item 的属性来达到类似 onRow 的效果，具体可参考该链接中的内容 https://ant.design/components/list-cn/#List.Item。

如果您对于以上信息有任何疑问或需要帮助，请回复并说明您的具体情况，我会尽力为您提供帮助。

**Comment by Yojay97** [comment]
这个问题现在是不修复了吗还是？目前2.6.11还是没有描述呢
