### ISSUE TITLE
🧐[问题]怎么阻止ProTable 搜索回车提交表单

### ISSUE THREAD

**Issue by BabyFriedCake** [ant-design/pro-components#3729]
### 🧐 问题描述

ProTable 的search是ModalForm，点回车时候，ProTable执行request
### 💻 示例代码
https://codesandbox.io/s/shi-yong-visible-he-onvisiblechange-forked-dukqv?file=/App.tsx:1182-1202

"@ant-design/pro-form": "^1.41.2",
"@ant-design/pro-table": "^2.54.2",
虽然更新版本以后，ModalForm回车时候不提交表单搜索了，但是ProTable执行了request。
关闭弹窗输入后回车搜索，params也未改变，params还是弹窗内的values。
### 🚑 其他信息

https://user-images.githubusercontent.com/33448924/134613179-af53379d-4552-49fb-b52b-3541ef2308ec.mp4

**Comment by chenshuai2144** [comment]
试试在 form 中配置 isKeyPressSubmit 为false

**Comment by BabyFriedCake** [comment]
> 试试在 form 中配置 isKeyPressSubmit 为false

他默认不是false么？ProTable 怎么设置？
