### ISSUE TITLE
🧐[问题]ProCard无法绑定 id 

### ISSUE THREAD

**Issue by wangxin305** [ant-design/pro-components#3733]
### 🧐 问题描述

发现ProCard 无法绑定 id , 查看源码发现，id 被忽略掉了，请为这是为什么？
### 💻 示例代码
https://github.com/ant-design/pro-components/blob/master/packages/card/src/components/Card/index.tsx

能否不忽略
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/39551146/134612324-7b954f05-aca8-4577-bccf-3a2471c81b74.png)

**Comment by HaoLJ** [comment]
同文，有办法解决吗，不然锚点用不了

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，ProCard 组件是基于 Ant Design 的 Card 组件进行开发的，而 Card 组件在`<Card>`标签中不接收 id 这个 props。所以，在 ProCard 组件中继承该行为导致 id 被忽略了。

如果想要给 ProCard 组件设置 id，可以设置 id 为外部容器的 id，比如使用 div 包裹 ProCard 组件，将 id 设置在 div 上，然后使用锚点链接到该 div 上面即可。

示例代码：

```
<div id="my-card">
  <ProCard>...</ProCard>
</div>
```

如果想要直接在 ProCard 组件上设置 id ，可以将 id 改为大写字母 ID，因为 ProCard 组件中对大写字母 ID 进行了特殊处理，可以正常传入并渲染。

示例代码：

```
<ProCard ID='xxx'></ProCard>
```


希望能够解决你的问题。
