### ISSUE TITLE
🧐[问题]Schema Form - JSON 表单 不能直接使用json数据生成表单？

### ISSUE THREAD

**Issue by pxim** [ant-design/pro-components#3738]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/5111701/134633189-c27b4760-37d4-4a5e-9da1-622d7ec37d1d.png)
![image](https://user-images.githubusercontent.com/5111701/134633154-d137fdb5-8fb1-455a-82da-eddace8f9ccd.png)
渲染变成这样
![image](https://user-images.githubusercontent.com/5111701/134633276-a51b24e0-539b-4956-bcf1-fb8ff9f828b2.png)

如果我用同样的json数据，
在这个库里https://github.com/json-editor/json-editor
![image](https://user-images.githubusercontent.com/5111701/134633449-2092c9d6-55d7-4dcf-b338-7336c803cfc3.png)
可以直接用纯粹的json生成表单；

**Comment by chenshuai2144** [comment]
你至少尊重一下我们的语法呀

**Comment by pxim** [comment]
> 你至少尊重一下我们的语法呀

好吧
