### ISSUE TITLE
🐛[BUG] Adding `search` prop causes warning

### ISSUE THREAD

**Issue by rchavik** [ant-design/pro-components#374]
### 🐛 bug 描述

Warning in console: "Warning: React does not recognize the `searchText` prop on a DOM element."

### 📷 复现步骤

Add the following to a working table:

```diff
diff --git a/src/MyTable.tsx b/src/MyTable.tsx
index fd008ed..047e53c 100644
--- a/src/MyTable.tsx
+++ b/src/MyTable.tsx
@@ -86,6 +86,7 @@ export default () => (
       }}
       rowKey="key"
       headerTitle="日期类"
+      search={{ searchText: 'Search' }}
     />
   </>
 );
```

### 🏞 期望结果

No warning generated

### 💻 复现代码

https://github.com/rchavik/repro-protable.git

### © 版本信息

- pro-table ^2.6.3
- umi - N/A
- firefox
- linux

**Comment by forzalianjunting** [comment]
+1
