### ISSUE TITLE
👑 [需求]ProTable删除一行或是更新一行的数据的时候，在不重载表格的情况下刷新到列表中？

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/pro-components#3740]
### 🥰 需求描述

ProTable删除一行或是更新一行的数据的时候，在不重载表格的情况下刷新到列表中？

### 🧐 解决方案

应该方案应该是把datasouce给暴露出来，然后修改下datasouce。

**Comment by kanhebei** [comment]
pro-table 用的userequest 怎么暴露

**Comment by ideaviewes** [comment]
@kanhebei ,我也不知道，所以要问下
这种需求很常见吧

**Comment by ideaviewes** [comment]
@chenshuai2144 ,您好，具体场景是
点删除，删除了一行数据，怎么能在不reload刷新整个table的情况下，把这行数据从table中删除掉
onDateSourceChange 怎么实现呢？
