### ISSUE TITLE
🧐[问题]ProTable中key在`column`和搜索表单中表现是否一致?

### ISSUE THREAD

**Issue by WoodsLiu** [ant-design/pro-components#375]
### 🧐 问题描述

`key`的作用,在`column`和搜索表单中表现是否一致?

在研究`ProTable`的源码的时候看到, `valueTypeRef`是根据`column`中定义的`key`和`index`生成的唯一 key 与`valueType`组成的对象,如果不写`key`的话,就是`undefined`,然后就会出现`{undefined: undefined}`的对象值,但是在生成表单的时候又是根据`dataIndex`来生成的对象,最终就会不一致.

这样就导致了`conversionSubmitValue`转换`moment -> string`的时候有一种错觉,`conversionSubmitValue(values, dataFormatter, valueTypeRef)`这个`valueTypeRef`起到作用了,我根据调试之后发现这个`valueTypeRef`其实并没有起作用,就好像俏皮的跟你说: "嘿,其实我没有生效呢,我就是一个'幌子'".

### 💻 示例代码

```jsx
const columns = [
  {
    // 没有设置key, 所以在valueType表现为undefined
    title: '状态',
    dataIndex: 'status',
    initialValue: 'all',
    valueEnum: {
      all: { text: '全部', status: 'Default' },
      close: { text: '关闭', status: 'Default' },
    },
  },
  {
    title: '进度',
    key: 'progress',
    dataIndex: 'progress',
    valueType: item => ({
      type: 'progress',
      status: item.status !== 'error' ? 'active' : 'exception',
    }),
  },
  {
    title: '更新时间',
    key: 'since2', // 注意这里,设置了key,所以在valueType中的key是since2,而不是createdAt
    dataIndex: 'createdAt',
    // 注意这里,这是dateRange, 也就是说格式化成字符串的时间应该为['2020-09-05','2020-10-08']
    valueType: 'dateRange',
  },
]
```

所以生成的`valueTypeRef`以及输入值之后的`values`的值如下(下面有图片)

```js
// valueTypeRef
const valueTypeRef = {
  progress: item => {},
  since2: 'dateRange',
  undefined: undefined,
}
// value
const values = {
  createdAt: ['2020-09-05 13:10:34', '2020-10-08 13:10:34'],
  progress: 1,
  status: 'all',
}
```

这里就有点可疑,`createdAt`格式化的时间与视图展示的时间(见下图)不一样,**视图展示的没有时分秒**,而在**取值的时候有这个时分秒**.
为什么会有数据与视图的差异呢?因为`valueTypeRef`没有起作用,所以将 Moment 转换为字符串时是按照默认的`YYYY-MM-DD HH:mm:ss`进行转换的.

```js
// 简化这里的代码
// Moment -> string | number
const conversionMoment = (value, dateFormatter, valueType) => {
  if (dateFormatter === 'number') {
    return value.valueOf()
  }
  return value.format(dateFormatterMap[valueType] || 'YYYY-MM-DD HH:mm:ss')
}

const conversionSubmitValue = (value, dateFormatter, valueTypeMap) => {
  const tmpValue = {}
  Object.keys(value).forEach(key => {
    const valueType = valueTypeMap[key] || 'text'
    const itemValue = value[key]
    if (itemValue === undefined || itemValue === null) {
      return
    }
    // 都没命中，原样返回
    tmpValue[key] = conversionMoment(itemValue, dateFormatter, valueType)
  })
  return tmpValue
}
```

通过`Object.keys(values)`得到的 key 数组是`['createdAt','progress','status']`,而 valueTypeRef 的 key 数组是`['undefined','since2','progress']`,
所以在通过`valueTypeMap[key] || 'text'`获取 valueType,**永远都是 text**,所以在`conversionMoment`转换的时候一直都是默认格式`'YYYY-MM-DD HH:mm:ss'`进行转换的.
不管有没有设置`key`!!!

其实就是在`genColumnKey`的时候出现了问题,这也是纠结我的地方,这个`key`的作用到底是???,或者说生成唯一的 columnKey 到底应该依据什么,我在 antd table 文档中找到`column key`的描述

> key: React 需要的 key，如果已经设置了唯一的 dataIndex，可以忽略这个属性

那么这样子的话,是不是只要将`valueTypeRef`与`values`字段保持一致就可以解决问题了,这样就有两种方式:

1. 第一种: 先把所有的`column dataIndex`组成一个对象,如果有重复的`dataIndex`,则采用`key`,如果没有重复的`dataIndex`,直接采用`dataIndex`
2. 第二种: 规定column key是唯一的,所有优先以column key为主,如果没有key则已dataIndex为主,也就是在`<Form.Item name={key || dataIndex}></Form.Item>`以达到`valueTypeRef`与`values`字段的统一.

```tsx

// 第一种(这种可能会因为没有传入dataIndex、key、index,出现未知问题)
const dataInxMap = counter.proColumns.reduce((result, item) => {
  const { key, dataIndex } = item
  // 有重复的采用key、否则采用dataIndex作为唯一key
  result[dataIndex] = result[dataIndex] ? key : dataIndex
  return result
}, {})

counter.proColumns.forEach(item => {
  const { dataIndex, key, index, valueType } = item
  // tempMap[genColumnKey(key, index)] = valueType
  tempMap[genColumnKey(dataInxMap[dataIndex], index)] = valueType
})

// 第二种
counter.proColumns.forEach(item => {
  const { dataIndex, key, index, valueType } = item
  tempMap[genColumnKey(key || dataIndex, index)] = valueType
})

<Form.Item name={key || dataIndex}></Form.Item>
```

### 🚑 其他信息

这些就是我在看源码以及写代码的时候出现的问题,这些只是我的一些个人观点和解决方案,或者有更好的方案呢.

<img width="1652" alt="Screen Shot 2020-09-03 at 1 10 49 PM" src="https://user-images.githubusercontent.com/40518195/92074525-dcc03100-ede8-11ea-9742-54c1dc79d296.png">

**Comment by chenshuai2144** [comment]
来个 pr？

**Comment by WoodsLiu** [comment]
@chenshuai2144 已提交pr
