### ISSUE TITLE
🐛[BUG] [EditableProTable]表单联动获取不到实时值

### ISSUE THREAD

**Issue by ayaayaayaai** [ant-design/pro-components#3750]
### 🐛 bug 描述
通过form.setFieldsValue 联动写值
onValuesChange中通过 form.getFieldsValue 获取不到实时值
### 📷 复现步骤

![image](https://user-images.githubusercontent.com/45863356/134878674-02fb55d7-f594-4113-a5c4-d0393cab8a82.png)

![image](https://user-images.githubusercontent.com/45863356/134878865-bd52ea91-5ac8-49cd-89e5-02a59ec63a9e.png)
![image](https://user-images.githubusercontent.com/45863356/134879399-3337d77f-8687-42b3-9a45-cc7f5f6f102c.png)

### © 版本信息
官网 EditableProTable 实时保存的编辑表格例子

**Comment by chenshuai2144** [comment]
set 不会触发 onValuesChange 的，你的需求估计实现不了

**Comment by superAo005** [comment]
为何我form.setFieldsValue之后 就会报错呢
![image](https://user-images.githubusercontent.com/22334521/145809126-db3c1a85-85c3-4156-85f2-eb4d640b36b3.png)
