### ISSUE TITLE
🧐[问题] 如何得到 ProFormFields 内的ref

### ISSUE THREAD

**Issue by qiangxinglin** [ant-design/pro-components#3753]
### 🧐 问题描述
现在有一个 ModalForm, 我想做成点开时自动聚焦到第一个 ProFormText 上
但是看了看, 好像没法得到内部 Input 的ref, 请问怎么实现呢?

**Comment by chenshuai2144** [comment]
fieldProps 然后用 ref

**Comment by qiangxinglin** [comment]
@chenshuai2144 没有这个prop
![image](https://user-images.githubusercontent.com/20382522/135044177-741ce877-fc38-460c-8d3b-4391e79a22a8.png)
