### ISSUE TITLE
🧐[问题] ProFormList 组件中使用ProFormDependency 做 ProFormSelect联动如何清理已经选中的值

### ISSUE THREAD

**Issue by zanmeipaul** [ant-design/pro-components#3756]
### 🧐 问题 ProFormList 组件中使用ProFormDependency 做 ProFormSelect联动如何清理已经选中的值

ProFormList 里面嵌套了 ProFormSelect 和 ProFormDependency 做联动， 当第一个ProFormSelect 改变选择值的时候, 第二个ProFormSelect 里面已经选择的值还存在没有被清空。 是否是因为 form 里面之前选择的数据还存在？  该如何清理？ 因为在ProFormDependency无法拿到当前index 所有也不好在 form 获取数据来删除 FieldsValue 中的数据

**Comment by chenshuai2144** [comment]
```
<ProFormList >
<></>
{(filed)=><ProFormDependency />}
</ProFormList >
```
用这种方式吧，也是支持自动filed注入的

**Comment by zanmeipaul** [comment]
@chenshuai2144    我目前就是用这种方式的，问题在于，我改变了 ProFormDependency 里面的 ProFormSelect 列表数据，可是之前选中的数据还在，如果ProFormDependency 里面表单的组件是根据联动选择的字段变动的话。 因之前选择的数据还在，ProFormDependency里面改变成新的组件，数据不兼容就会出错。 所有我有一个疑问，当 ProFormDependency 重新渲染的时候，之前选择的 form.getFieldValue 中数据如何指定 ProFormList 中某一条数据某一个字段置空，这样避免报错

**Comment by zanmeipaul** [comment]
@chenshuai2144    我使用你提供的 `<ProFormList >
     {(filed)=><ProFormDependency />}
</ProFormList >`  在 ProFormList 嵌套的时候，好像有问题，显示不出来。

**Comment by darkfiredarkhalo** [comment]
的确是个比较麻烦的问题, 官网的例子也不能做到Dependency变化清空原值, 只能把select的value设置为受控的, 挺麻烦的

**Comment by darkfiredarkhalo** [comment]
> ```
> <ProFormList >
>      {(filed)=><ProFormDependency />}
> </ProFormList >
> ```
> 
> 用这种方式吧，也是支持自动filed注入的

实现不了`Dependency变化清空原值`的需求

**Comment by Eileen-v** [comment]
遇到了同样的问题，请问大家是如何解决的呀

**Comment by zanmeipaul** [comment]
> 遇到同样的问题，请问大家是如何解决的呀
我忘了怎么解决了，时间比较长了。 我把代码粘贴给你，你有需要就看一下找找灵感

`<ProForm.Group>
          <ProFormList
            name="rules"
            label="规则"
            creatorButtonProps={{
              creatorButtonText: '新增OR关系规则',
            }}
            itemRender={({ listDom, action }, { record, fields, index }) => {
              return (
                <>
                  <ProCard
                    bordered
                    extra={action}
                    title={record?.name}
                    style={{
                      marginBottom: 8,
                    }}
                  >
                    {listDom}
                  </ProCard>
                  {fields.length !== index + 1 && <span style={{ color: 'red' }}>OR</span>}
                </>
              );
            }}
          >
            <></>
            {(filedOr, indexOr: any) => {
              return (
                <ProFormList
                  name="or"
                  label="AND规则信息"
                  copyIconProps={{
                    tooltipText: '复制',
                  }}
                  deleteIconProps={{
                    tooltipText: '删除',
                  }}
                  creatorButtonProps={{
                    creatorButtonText: '新增AND关系规则',
                  }}
                  itemContainerRender={(doms) => {
                    return <ProForm.Group>{doms}</ProForm.Group>;
                  }}
                >
                  <ProFormSelect
                    name="decisionCode"
                    label="决策变量"
                    request={async () => {
                      return props?.initDecisionData?.map((d: any) => {
                        return { label: d?.decisionName, value: d?.decisionCode };
                      });
                    }}
                    placeholder="请选择决策变量"
                    rules={[{ required: true, message: '请选择决策变量' }]}
                  />
                  {(filed: any, index: any) => {
                    let isRow: boolean = false;
                    if (
                      rulesIndex.length > indexOr &&
                      rulesIndex[indexOr].length > index &&
                      rulesIndex[indexOr][index] === filed?.key
                    ) {
                      // 本行改变
                      isRow = true;
                    } else {
                      if (rulesIndex.length > indexOr && rulesIndex[indexOr].length > index) {
                        rulesIndex[indexOr][index] = filed?.key;
                      } else if (rulesIndex.length > indexOr) {
                        rulesIndex[indexOr].splice(index, 0, filed?.key);
                      } else {
                        const d = [filed?.key];
                        rulesIndex.splice(indexOr, 0, d);
                      }
                    }

                    return (
                      <>
                        <ProFormDependency name={['decisionCode']}>
                          {(_, form) => {
                            const ruleItem = form.getFieldValue('rules')[indexOr]?.or[index];

                            return (
                              <ProFormSelect
                                name="operator"
                                label="符号"
                                params={{
                                  rulesOrIndex: indexOr,
                                  rulesAndIndex: index,
                                  decisionCode: ruleItem?.decisionCode,
                                }}
                                request={(value) => {
                                  console.log('operator request 执行;', isRow, value);
                                  if (isRow) {
                                    const rulesData = form.getFieldValue('rules');
                                    rulesData[value?.rulesOrIndex]['or'][value?.rulesAndIndex][
                                      'operator'
                                    ] = undefined;
                                    rulesData[value?.rulesOrIndex]['or'][value?.rulesAndIndex][
                                      'value'
                                    ] = undefined;
                                    form.setFieldsValue({ rules: rulesData });
                                  }

                                  if (value?.decisionCode) {
                                    const ar = props?.initDecisionData?.find(
                                      (elem: any) => elem?.decisionCode === value?.decisionCode,
                                    );

                                    return JSON.parse(ar?.operator);
                                  } else {
                                    return [];
                                  }
                                }}
                                placeholder="请选择符号"
                                rules={[{ required: true, message: '请选择符号' }]}
                              />
                            );
                          }}
                        </ProFormDependency>

                        <ProFormDependency name={['decisionCode']}>
                          {(_, form) => {
                            const ruleItem = form.getFieldValue('rules')[indexOr]?.or[index];
                            const ar = props?.initDecisionData?.find(
                              (elem: any) => elem?.decisionCode === ruleItem?.decisionCode,
                            );

                            if (ar?.valueType === '00') {
                              //文本
                              return (
                                <ProFormText
                                  name="value"
                                  label="值"
                                  rules={[{ required: true, message: '请输入值' }]}
                                />
                              );
                            } else if (ar?.valueType === '01') {
                              //输入数字
                              return (
                                <ProFormDigit
                                  name="value"
                                  label="值"
                                  rules={[{ required: true, message: '请输入值' }]}
                                />
                              );
                            } else if (ar?.valueType === '02') {
                              // 下拉选择
                              return (
                                <ProFormSelect
                                  name="value"
                                  label="值"
                                  rules={[{ required: true, message: '请输入值' }]}
                                  placeholder="请选择值"
                                  params={{
                                    decisionCode: ar?.decisionCode,
                                    valueSource: ar?.valueSource,
                                  }}
                                  request={async (value) => {
                                    return await getChannelDecisionValues(value);
                                  }}
                                />
                              );
                            } else if (ar?.valueType === '03') {
                              console.log('moment', moment('12:08:23', 'HH:mm:ss'));
                              // 日期
                              return (
                                <ProFormTimePicker.RangePicker
                                  name="value"
                                  label="值"
                                  rules={[{ required: true, message: '请输入值' }]}
                                  fieldProps={{
                                    format: 'HH:mm:ss',
                                  }}
                                />
                              );
                            } else if (ar?.valueType === '04') {
                              // 多个输入值文本框
                              return (
                                <ProFormSelect
                                  name="value"
                                  label="值"
                                  mode="tags"
                                  width="sm"
                                  fieldProps={{
                                    open: false,
                                  }}
                                />
                              );
                            } else if (ar?.valueType === '05') {
                              // 多个输入值下拉框
                              return (
                                <ProFormSelect
                                  name="value"
                                  label="值"
                                  mode="multiple"
                                  rules={[{ required: true, message: '请输入值' }]}
                                  placeholder="请选择值"
                                  params={{
                                    decisionCode: ar?.decisionCode,
                                    valueSource: ar?.valueSource,
                                  }}
                                  request={async (value) => {
                                    return await getChannelDecisionValues(value);
                                  }}
                                />
                              );
                            }

                            return (
                              <ProFormText
                                name="value"
                                label="值"
                                rules={[{ required: true, message: '请输入值' }]}
                              />
                            );
                          }}
                        </ProFormDependency>
                      </>
                    );
                  }}
                </ProFormList>
              );
            }}
          </ProFormList>
        </ProForm.Group>`

效果就是这样
<img width="723" alt="image" src="https://github.com/ant-design/pro-components/assets/20592867/cfcd1a8f-6d18-4b16-8bdc-d63b73442a23">

**Comment by ScotchPie** [comment]
> 遇到了同样的问题，请问大家是如何解决的呀
类似的问题我通过奇怪的方式解决了，思路大概是这样的，可以参考一下
![无标题](https://github.com/ant-design/pro-components/assets/109577566/ceee16ae-0d50-4739-8133-574d7ae62986)
