### ISSUE TITLE
🐛[BUG]ProForm中的 ProFormDigit表单项无法通过fieldProps设置controls属性

### ISSUE THREAD

**Issue by 980061076** [ant-design/pro-components#3757]
### 🐛 bug 描述
ProForm中的 ProFormDigit表单项无法通过fieldProps设置controls属性

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/62498523/135056352-68d73a6c-6a2c-467c-9317-e0b05a19d183.png)

### 🏞 期望结果
解决问题

### 💻 复现代码
<ProFormDigit fieldProps={{
          controls:false
        }} name="tel" rules={[{ required: true }]} label="手机号" width={'sm'} placeholder="请输入" />

### © 版本信息

- ProComponents 版本: [e.g. 5.0.0]
- umi 版本  [e.g. 3.5.0]
- 浏览器环境 谷歌浏览器
- 开发环境 [e.g.window10]

**Comment by chenshuai2144** [comment]
controls:false

这个是谁的api？ react 的吗？ 没见过这个属性

**Comment by chenshuai2144** [comment]
看了下是类型没写，但是内容是可以生效的，我改下

**Comment by 980061076** [comment]
> 看了下是类型没写
> 
> 看起来是新版本删除掉了 ，类型里面没有，去antd 问问？

antd中的InputNumber的这个api我试过了，是可以正常使用的，所以我才想会不会是proform的问题 =-=，我明天把antd的版本从4.14升到4.17试试？
