### ISSUE TITLE
🧐[问题]ProLayout中的menu异步的情况下如何设置展开呢?

### ISSUE THREAD

**Issue by Bendjen** [ant-design/pro-components#3760]
文档中写：
defaultOpenAll | 默认打开所有的菜单项，要注意只有 layout 挂载之前生效，异步加载菜单是不支持的。
那异步时有办法手动打开或者什么方法之类的吗？

**Comment by chenshuai2144** [comment]
受控的 openkeys 展示，或者在异步菜单回来之前不要渲染 prolayout
