### ISSUE TITLE
👑 [需求] BetaSchemaForm 的 column 如何根据某一项表单的值隐藏另一个表单？

### ISSUE THREAD

**Issue by jiyingzhi** [ant-design/pro-components#3776]

**Comment by jiyingzhi** [comment]
hidenInForm 可以支持函数吗

**Comment by chenshuai2144** [comment]
fieldProps  搞个 display 应该可以吧

**Comment by jiyingzhi** [comment]
可以

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


`BetaSchemaForm` 的 `columns` 支持通过 `hidden` 属性来隐藏某一个列:

```javascript
{
  type: 'input',
  label: '输入框',
  name: 'input',
  hidden: true, // 隐藏当前列
}
```

若需要基于其它 `column` 的值来确定是否隐藏一个 `column`，我们可以通过 `getValueFromFormValues` 来获取当前所有 `column` 的值，并用返回的数据来判断是否隐藏目标 `column`。

例如，如下的 `codeSandbox` 链接里有一个表单，右侧有一个 `hiddenInput` 当 `input` 的值包含 `'123'`时隐藏，不含时显示。你可以在这个栗子上做扩展来满足你的需求。

- [hiddenFieldRenderer](https://codesandbox.io/s/beta-schema-form-sandbox5-reducehiddenfields-84ion?file=/src/App.tsx)
