### ISSUE TITLE
👑 [需求] ProDescriptions 的 loading 建议新增 Spin 样式

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#3790]
### 🥰 需求描述

ProDescriptions 的 loading 建议新增 Spin 样式

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### ✨ 解决方案

你可以通过以下步骤为 ProDescriptions 组件新增 Spin 样式的 loading 动效：

1. 新增 Spin 组件

在 ProDescriptions 组件中，它本身并没有提供 Spin 样式的 loading 动效，因此我们需要先引入 Antd 的 Spin 组件。

在组件引入部分，你可以添加如下代码：

```javascript
import { Spin } from 'antd';
```

2. 定义 loading 函数

定义一个 loading 函数，用来展示 loading 动效。在 loading 函数中，我们可以将 Spin 样式的 loading 动效直接渲染到 ProDescriptions 组件的 loading 状态下。

```javascript
const renderLoading = () => {
  return (
    <div style={{ justifyContent: 'center', display: 'flex', alignItems: 'center' }}>
      <Spin />
    </div>
  );
};
```

3. 在 ProDescriptions 组件中调用 loading 函数

最后，在 ProDescriptions 组件中，只需要将我们定义好的 loading 函数通过 loading 属性传递给组件即可。

```javascript
<ProDescriptions
  loading={renderLoading}
  /* other props */
>
  /* 每一行的描述配置 */
</ProDescriptions>
```

这样，你便可以为 ProDescriptions 组件新增 Spin 样式的 loading 动效了。

更详细的信息，可以参见 Antd 的 Spin 组件文档：
https://ant.design/components/spin-cn/
