### ISSUE TITLE
请问怎样自由配置工具栏🧐[问题]

### ISSUE THREAD

**Issue by astudentat** [ant-design/pro-components#3795]
### 💻 示例代码
<ProTable
        {...props}
        rowKey={props.rowKey}
        scroll={{x:'100%',y:550}}
        search={false}
        columns={tableColumns}
        dataSource={genData(props|| 10)}
      />

**Comment by astudentat** [comment]
![image](https://user-images.githubusercontent.com/40906200/136642718-2573b02d-f364-444b-b988-2629357a5482.png)
我想只保留<列设置>,取消刷新和密度设置

**Comment by astudentat** [comment]
已解决

**Comment by LGHhua** [comment]
你好，怎么解决的，能指导一下？

**Comment by astudentat** [comment]
> dataSource={genData(props|| 10)}

protable 有个options里面可以设置

**Comment by astudentat** [comment]
> 你好，怎么解决的，能指导一下？

protable 有个**options**里面可以设置
