### ISSUE TITLE
🐛[BUG]EditableProTable的summary无法获取到最新的pageData

### ISSUE THREAD

**Issue by chanTanya** [ant-design/pro-components#3797]
### 🐛 bug 描述
1. summary的pageData获取的amt"金额"字段总是上一次变化的值
2. 经测试只在 "@ant-design/pro-table": "2.53.2"及其之后的版本才会出现上述问题

### 📷 复现步骤
点辑“数量”的 + 按钮 更改数量，观察“总额”的变化

### 🏞 期望结果
更改“数量”，实时计算出当前“总额”
https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-d2qzj?file=/App.tsx

### 💻 复现代码
https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-y2c54?file=/App.tsx

**Comment by chenshuai2144** [comment]
这个描述有问题，应该是的 inputnumber 没支持 onblur导致的
