### ISSUE TITLE
🧐[问题]工具栏-列设置-可否增加slot

### ISSUE THREAD

**Issue by astudentat** [ant-design/pro-components#3799]
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/40906200/136654040-e108fe67-41b7-4777-afaf-d977855a4800.png)

**Comment by astudentat** [comment]
想在底部添加一个确认按钮，用于在所有勾选操作结束后统一处理隐藏和显示，请问现在可以实现吗

**Comment by chenshuai2144** [comment]
不支持的，有兴趣来个pr

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/3808
