### ISSUE TITLE
👑 [需求]建议优化DrawerForm的视觉效果

### ISSUE THREAD

**Issue by cloudsnet** [ant-design/pro-components#3807]
### 🥰 需求描述

DrawerForm 通过request获取初始化值时，再显示之前，是先获取初始化值后才初始化Drawer组件显示，获取request返回比较慢时，体验很不友好，通过onFinish提交数据到后端时，loading的状态显示也不友好。

### 🧐 解决方案

1、应该先显示Drawer，若通过request初始化值，可在Drawer组件上显示loading的状态
2、通过onFinish提交数据时，loading的状态状态应该显示在Drawer组件上
这样的体验才更友好，现在感觉loading和DrawerForm分离了，虽然公用一个dom位置，可视觉体验上很差，会破坏布局

**Comment by chenshuai2144** [comment]
这个是因为request 拿到的是initialvalues，只有在组件初始化时才会生效，所以必须要这么搞

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


确实，您提出的优化方案很不错。可以先呈现Drawer的外观，而不是等待初始数据加载完成后再呈现，这样可以提高用户的体验。同时，在Drawer内部加入 Spin 组件，可以营造出更好的交互效果。关于实现过程，建议在Drawer组件初始化时请求数据，同时展示Spin组件，数据加载完成后再对表单进行渲染和初始值的赋值。代码示例如下：

```jsx
import React, { useState, useEffect } from 'react';
import { Form, Drawer, Spin } from 'antd';

const DrawerForm = ({ visible, onClose, onFinish }) => {
  const [form] = Form.useForm();
  const [loading, setLoading] = useState(true); // 设置加载状态， 默认为true

  useEffect(() => {
    initFormValues(); // 表格数据初始化
  }, []);

  const initFormValues = async () => {
    // 使用async/await异步获取数据
    const values = await request(url); // url是你请求数据的api接口
    form.setFieldsValue(values); // 设置初始化值
    setLoading(false); // 数据加载完成后，修改状态为false
  };

  return (
    <Drawer visible={visible} onClose={onClose}>
      {loading ? ( // 如果数据未加载完成，则显示Spin
        <Spin />
      ) : (
        <Form form={form} onFinish={onFinish}>
          {/* form表单组件 */}
        </Form>
      )}
    </Drawer>
  );
};

export default DrawerForm;
```

这样效果就会和您的需求一样了。希望能够帮到您。

**Comment by chenshuai2144** [comment]
已经修复了，可以试试了
