### ISSUE TITLE
🐛[BUG]切换到2.4.2以上valueEnum过滤失效

### ISSUE THREAD

**Issue by meyerlee** [ant-design/pro-components#381]
### 🐛 bug 描述
2.4.2以上的版本，包括现在的2.6.3， valueEnum过滤失效。

### 📷 复现步骤
当前 https://procomponents.ant.design/components/table
范例里的，解决、未解决的过滤就有问题。

应该是 2.4.3+ 版本valueEnum的列实现改变照成的。
rendText函数中
2.4.2-:  text 参数是 valueEnum.text
2.4.3+: text 参数是 valueEnum.key

https://github.com/ant-design/pro-components/issues/193#issuecomment-673916902

### © 版本信息

- protable 2.4.3+
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
配置 filters 为 true，现在默认关掉了，大家纷纷表示不需要

**Comment by meyerlee** [comment]
设置filters 为true是显示了过滤条件的面板，
问题是条件出来了不能过滤，选择了条件数据没有过滤。
选了条件不能过滤数据

**Comment by meyerlee** [comment]
如果只是不出现面板框， 我不会再开一个issue的

**Comment by meyerlee** [comment]
![image](https://user-images.githubusercontent.com/8414971/92350556-ea88f580-f10b-11ea-9803-fe489f62f1fd.png)

**Comment by chenshuai2144** [comment]
你用了 requet 的方式就不支持本地的 filter 了；

**Comment by meyerlee** [comment]
filter只在 datasource的时候有效？
valueEnum的过滤功能还挺好的。

我现在的处理方式上， filter是前台行为， search是后台行为。

从2.3 的时候， fitler不触发request
2.4.2之前  fitler会触发request，但还是会对返回的数据做过滤

如果是改了行为的话，就只能自己来实现过滤了。
