### ISSUE TITLE
🐛[BUG]ProFormSelect设置labelInValue为true时，onClear触发后select的值非undefined

### ISSUE THREAD

**Issue by chanTanya** [ant-design/pro-components#3810]
### 🐛 bug 描述
选择一个选项，触发select的onClear之后没有触发form的必填校验，因为onClear之后该select的值为{} ，导致了必填项为空却能提交表单

### 📷 复现步骤
选择一个select选项，触发select的onClear,提交表单

### 🏞 期望结果
labelInValue为true时，onClear触发后select的值为undefined
https://stackblitz.com/edit/react-izrbwt

### 💻 复现代码
https://codesandbox.io/s/tong-bu-ti-jiao-jie-guo-dao-url-forked-h0m96?file=/App.tsx

**Comment by yangxuefneng** [comment]
我也遇到了同样的问题

**Comment by chenshuai2144** [comment]
onClear 之后的值都应该是 undefined，有问题的是没处理好空值

**Comment by Sharklegs** [comment]
@chenshuai2144  单独使用清空没问题，放在form中 清空拿到的是{}空对象，（影响正常placeholder）怎么处理

**Comment by zxllzw** [comment]
> @chenshuai2144 单独使用清空没问题，放在form中 清空拿到的是{}空对象，（影响正常placeholder和校验）怎么处理

+1
