### ISSUE TITLE
🐛[BUG] 报错：heap out of memory

### ISSUE THREAD

**Issue by monkey7777** [ant-design/pro-components#3813]
### 🐛 bug 描述

项目有使用editableProTable，首次运行npm run start 可以变成成功，正常运行。
但是修改一些代码保存后，自动编译时，报错退出。

### 📷 复现步骤

错误信息：
![image](https://user-images.githubusercontent.com/7223480/136761897-2e93be32-c083-48ad-81b8-53a547769a98.png)

**Comment by chenshuai2144** [comment]
去对应的脚手架github问问，我这里没做什么特殊处理
