### ISSUE TITLE
🐛[BUG] 特定的 options 给 radio 会失效，其他组件正常

### ISSUE THREAD

**Issue by Artoria-0x04** [ant-design/pro-components#3825]
### 🐛 bug 描述

为了简化数据处理，统一给组件传递了树形数据结构，在特定情况下 radio 会无法工作，select 正常

```ts
type Dictionary<T = string | number> = {
  value: T;
  label: string | React.ReactNode;
  children?: null | undefined | Dictionary<T>[];
  [other: string]: any;
};
```

### 📷 复现步骤

具体地，数据类型为
```ts
const options = [
  { label: "A （2）", value: 1, type: 1 },
  { label: "B （5）", value: 2, type: 1 },
  { label: "C （1）", value: 3, type: 1 },
  { label: "D （2）", value: 4, type: 1 }
];
```
时，radio 不工作

### 💻 复现代码

https://codesandbox.io/s/te-ding-de-radio-options-shi-xiao-dan-qi-ta-zu-jian-zheng-chang-zwl6e?file=/App.tsx

### © 版本信息

- ProComponents 版本: pro-form@1.42.0
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by DerrickTel** [comment]
antd的大佬已经修复了，应该等下一个antd版本发布就好了，这个不是ProComponent的bug。不过还是很感谢您的在线例子~

**Comment by Artoria-0x04** [comment]
好的。我一开始也是用 Radio.Group 试的，没试出 bug。
