### ISSUE TITLE
🧐[问题]EditableProTable添加拖拽排序后渲染异常

### ISSUE THREAD

**Issue by gracexiong** [ant-design/pro-components#3828]
### 🧐 问题描述
EditableProTable添加拖拽排序后， onSortEnd方法拿不到正确的oldIndex, newIndex 

### 💻 示例代码

https://codesandbox.io/s/ke-bian-ji-biao-ge-forked-fwhqp?file=/App.tsx

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23145977/136970417-b968d629-900c-41ac-8642-76c92ff1275b.png)

**Comment by superAo005** [comment]
> 

如果添加了子节点 index如何设置呢
