### ISSUE TITLE
🧐[问题]同时设置manualRequest和initialValues时manualRequest无效

### ISSUE THREAD

**Issue by cuihq2005** [ant-design/pro-components#383]
### 🧐 问题描述

在ProTable中设置manualRequest后，打开页面后还是自动发起了查询。查看了下ProTable的代码，发现设置了form.initialValue后，manualRequest无效，代码如下：
```
      const [formSearch, setFormSearch] = useState<{}>(() => rest.form?.initialValues);
````

```
     // 需要手动触发的首次请求
      const needManualFirstReq = manualRequest && !formSearch;

      if (!request || needManualFirstReq) {
        return {
          data: props.dataSource || [],
          success: true,
        } as RequestData<T>;
      }
```
不清楚为什么这样设计，期望needManualFirstReq值只由manualRequest确定

**Comment by WynterDing** [comment]
manualRequest 只作用于 空的 form，一旦你设置了form 的初始值，又不去触发，会给用户一种这就是当前初始值搜索对应结果的误解。

可能我多想了一层，这个逻辑应该交给用户去决定，最近修复一下

**Comment by cuihq2005** [comment]
这个有计划吗？😂

**Comment by chenshuai2144** [comment]
在这里重构掉了
https://github.com/ant-design/pro-components/issues/564
