### ISSUE TITLE
🧐[问题]表格-columnsState-默认值可否等待接口返回数据后再渲染？

### ISSUE THREAD

**Issue by astudentat** [ant-design/pro-components#3832]
### 🧐 问题描述

目前可以做到浏览器永久存储，但是换个浏览器或者设备就无法保留。思路是将当前设置的state保存到数据库。可是要怎样在接口返回数据之后再设置 defaultValue/value？
### 直接定义变量赋值是可以的:
        let columnsState = { name:{show:false}}
         columnsState: {
              defaultValue: columnsState,
              value: columnsState,
            }

**Comment by chenshuai2144** [comment]
请求接口的时候loading住table。

`<protable  loading={loading} />`

不然数据不一定及时回来的

**Comment by chenshuai2144** [comment]
`loading && <Protable />`
