### ISSUE TITLE
🐛[BUG] EditableProTable通过form.setFieldsValue无法正常修改值

### ISSUE THREAD

**Issue by liangxp** [ant-design/pro-components#3836]
### 🐛 bug 描述
🐛[BUG] EditableProTable通过form.setFieldsValue无法正常修改值

### 📷 复现步骤
点击样例代码中“手动修改值”按钮

### 💻 复现代码

https://codesandbox.io/s/proform-he-editabletable-tong-shi-shi-yong-forked-9t7q7

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
注意一下form  和 name。你挂错位置了
