### ISSUE TITLE
editable-table在msfu模式下编译报错

### ISSUE THREAD

**Issue by leeweather** [ant-design/pro-components#3837]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://procomponents.ant.design/components/editable-table](https://procomponents.ant.design/components/editable-table)

### Steps to reproduce
4.17.0编译时会提示缺少变量，但4.16.13是正常的

### What is expected?
可以正常编译

### What is actually happening?
可以正常编译

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.18 |
| System | macOs bigSur |
| Browser | Chorm |

---
 ERROR  Failed to compile with 1 errors                                                                                                                                                                       15:03:04

 error  in ./node_modules/@ant-design/pro-table/es/components/Form/index.less

Module build failed (from ./node_modules/@umijs/bundler-webpack/lib/webpack/plugins/mini-css-extract-plugin/src/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@umijs/deps/compiled/less-loader/cjs.js):

// @import './variable.less';
@import './@{root-entry-name}.less';
      ^
Variable @root-entry-name is undefined
      in /Users/mac/Desktop/work-project/diyuan-admin/node_modules/antd/es/style/themes/index.less (line 7, column 8)
    at processResult (/Users/mac/Desktop/work-project/diyuan-admin/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115794:19)
    at /Users/mac/Desktop/work-project/diyuan-admin/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115900:5
    at /Users/mac/Desktop/work-project/diyuan-admin/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:35125:11
    at /Users/mac/Desktop/work-project/diyuan-admin/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34977:18
    at context.callback (/Users/mac/Desktop/work-project/diyuan-admin/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34850:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by chenshuai2144** [comment]
这是antd 的新版本依赖问题。

看这里

https://github.com/ant-design/ant-design/issues/32195
