### ISSUE TITLE
🧐[问题]侧边导航收缩之后再展开，右侧页面被覆盖了。

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/pro-components#384]
![image](https://user-images.githubusercontent.com/50793943/92196002-d55c5e80-eea0-11ea-922b-0cdcc1981c94.png)

是啥原因啊？

**Comment by chenshuai2144** [comment]
你是不是修改了我们的 css？

**Comment by shaohuatsou** [comment]
> 你是不是修改了我们的 css？

我检查过没有修改，能跟我说一下怎么排查这个问题吗？

**Comment by chenshuai2144** [comment]
@shaohuatsou   看看 siderMenu 的 style ，是不是被覆盖掉了，默认应该只是浮动的

**Comment by shaohuatsou** [comment]
@chenshuai2144  好奇怪啊，我在prolayout上加siderWidth='208' 导致页面被覆盖，我去掉这句就好了，是BUG吗？

**Comment by chenshuai2144** [comment]
额 是的

**Comment by chenshuai2144** [comment]
siderWidth 用number就好了。 ts 应该会给你报错
