### ISSUE TITLE
🧐[问题] EditableProTable 中valueType: 'select'时，新增一行时如何设置默认值

### ISSUE THREAD

**Issue by ai180508** [ant-design/pro-components#3843]
### 🧐 问题描述

试过在columns中使用initialValue，但是并未起作用
通过recordCreatorProps设置时，页面显示的是value，并非text

### 💻 示例代码
const columns = [
{
      title: '医嘱类型',
      dataIndex: 'orderType',
      key: 'orderType',
      align: 'center',
      initialValue: 0,
      width: 120,
      valueEnum: {
        0: { text: '长期' },
        1: { text: '临时' },
      },
    },
]
<EditableProTable
      value={dataSource}
      rowKey={(record) => {
        return record.orderId;
      }}
      bordered
      scroll={{ x: 1200, y: 500 }}
      columns={columns}
      onChange={setDataSource}
      recordCreatorProps={{
        record: {
          orderId: (Math.random() * 1000000).toFixed(0),
          orderType: 0
        },
      }}
      editable={{
        type: 'multiple',
        form: proTableForm,
        editableKeys,
        onSave: async (rowKey, data, row) => {
              console.log(rowKey, data, row);
        },
        onChange: setEditableRowKeys,
      }}
    />

![image](https://user-images.githubusercontent.com/77037794/137453624-9fe6bdd6-b03f-4ab2-a3ff-e775a053dbb2.png)

**Comment by chenshuai2144** [comment]
注意 string 和 number 的问题。

**Comment by KingAmo** [comment]
use Map like this:
```
valueEnum: new Map([
   [0, '男'],
   [1, '女'],
 ]),
```
