### ISSUE TITLE
👑 [需求] 范例代码让设置后台大标题很困难

### ISSUE THREAD

**Issue by hoist1999** [ant-design/pro-components#3844]
### 🥰 需求描述
pro-components非常棒，在使用你们的范例代码的时候，想修改一下后台大标题“ Ant Design Pro“，修改为自己项目的标题。但是发现非常难以修改。
是的, <ProLayout title="title_here" pageTitleRender={ (prop) => 'title_here' } ></ProLayout>
这两个属性都是可以设置标题的，但是我发现无法设置成功。
最后发现defaultSettings在影响。

### 🧐 解决方案
```
      <ProLayout
        {...defaultProps}
 

        rightContentRender={() => (
          <div>
            <Avatar shape="square" size="small" icon={<UserOutlined />} />
          </div>
        )}
        {...settings}
      >
```

这里的{...settings}应该移动到标签头 
```
      <ProLayout
        {...settings}
        {...defaultProps}
        title="我们的后台大标题"
 
        rightContentRender={() => (
          <div>
            <Avatar shape="square" size="small" icon={<UserOutlined />} />
          </div>
        )}

      >
```

这样，我们在后面标签设置的信息才不会被覆盖，才可以成功设置标题。

### 🚑 其他信息
希望antd团队可以优化一下文档，将设置title这个内容讲一下。谢谢。

**Comment by chenshuai2144** [comment]
这个是为了保证 settting 的代码是优先级最高的。我觉得这个应该很好debug的。 
就按照这样搞得

**Comment by hoist1999** [comment]
保证 settting 的代码是优先级最高的，这出发点不错。就是文档关于标题设置方面，可以细化一些。设置标题的需求挺大的，避免大家去debug走弯路。毕竟，procomponent的亮点是：开箱即用。不是debug才能用。
