### ISSUE TITLE
👑 [需求] 怎么根据actionRef获取dataSource，包含哪些被选中的。如果没有，是否可以增加。谢谢

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-components#3846]
### 🥰 需求描述

怎么根据actionRef获取dataSource，包含哪些被选中的。如果没有，是否可以增加。谢谢

### 🧐 解决方案

tableRef.current.dataSource ，dataSource应该有一个extra属性，里面包含了是否选中，是否disabled 等。

**Comment by chenshuai2144** [comment]
react 的设计哲学就是状态机，数据要受控。actionRef 本身就不是很合适的用法。 

尽量配合编程范式把，不然下个版本的react 就升级不上去了

**Comment by algz** [comment]
应该提供一个获取datasource的方法。

**Comment by chenshuai2144** [comment]
<html>
<body>


dataSource | Table 的数据，protable 推荐使用 request 来加载 | T[] | -
-- | -- | -- | --
onDataSourceChange | Table 的数据发生改变时触发 | (dataSource: T[]) => void | -


</body>
</html>
