### ISSUE TITLE
🐛[BUG] pro-table表头设置sticky，loading状态出现闪烁

### ISSUE THREAD

**Issue by 985563349** [ant-design/pro-components#3857]
### 🐛 bug 描述
pro-table表头设置sticky，loading状态出现闪烁。

loading中表头位置：
<img width="422" alt="截屏2021-10-19 15 09 42" src="https://user-images.githubusercontent.com/36779802/137861042-e234e166-a1fd-4afa-8c74-d35eced51325.png">

loading后表头位置：
<img width="532" alt="截屏2021-10-19 15 10 46" src="https://user-images.githubusercontent.com/36779802/137861133-3b986cf2-0195-42c7-be99-cb4247e62190.png">

### 🏞 期望结果
希望表头loading前后位置能保持一致。

### 💻 复现代码
https://codesandbox.io/s/cha-xun-biao-ge-forked-w9u0v?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
antd 中已经修复
