### ISSUE TITLE
👑 [需求] ProColumns对象里面实现动态className

### ISSUE THREAD

**Issue by linchCN** [ant-design/pro-components#3858]
### 🥰 需求描述

![image](https://user-images.githubusercontent.com/21193805/137881271-43515218-c275-4c0a-bd2f-f3b103dd70b4.png)
定义写死了，不够灵活

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🌈 解决方案

要实现ProColumns对象内的动态className，可以通过定义一个函数，根据传入的参数动态返回className。以下是一个示例代码：

```jsx
const columns = [
  {
    title: '姓名',
    dataIndex: 'name',
    key: 'name',
    className: (record) => {
      if (record.age > 30) {
        return 'bold-text';
      }
      return 'normal-text';
    },
  },
  {
    title: '年龄',
    dataIndex: 'age',
    key: 'age',
  },
  {
    title: '地址',
    dataIndex: 'address',
    key: 'address',
  },
];
```

在这个示例中，我们定义了一个 `bold-text` 的className，当记录的 `age` 大于 `30` 时应用这个className，否则应用 `normal-text` 的className。你可以根据实际需求在函数中编写逻辑进行优化。

这里还有相应的文档介绍：[ProTable API - columns](https://procomponents.ant.design/components/table-cn/#API)，你可以查看其中关于 `className` 属性的说明。

### 📚 相关文档

- [Ant Design ProTable](https://procomponents.ant.design/components/table-cn/)

**Comment by chenshuai2144** [comment]
现在也是支持的，可以参考下斑马线的实线
