### ISSUE TITLE
在NPM包里需要i18n，但不想绑定某个i18n库。建议？

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#3861]
想创建NPM包， 
在其中定制一个组件，里面要用到i18n
可是我又不想在这个组件里指定i18n库。
因为使用该NPM包的应用可能使用umi的i18n或i18next
有什么好的做法？

**Comment by chenshuai2144** [comment]
自己写一个呗，手动注入一下。
或者像layout 一样让导入 formartMessage
