### ISSUE TITLE
👑 [需求] ProFormRadio.Group Support width

### ISSUE THREAD

**Issue by drizzlesconsin** [ant-design/pro-components#3869]
### 🥰 需求描述

在 [ProFormFields](https://procomponents.ant.design/components/field-set) 组件中，好像只有 **ProFormRadio.Group** 不支持 `width` 属性。

<h3 id="通用的属性" style="box-sizing: border-box; margin: 42px 0px 18px; color: rgb(69, 77, 100); font-weight: 500; line-height: 1.40625; font-size: 20px; font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">通用的属性</h3>

参数 | 说明 | 类型 | 默认值
-- | -- | -- | --
width | Field 的长度，我们归纳了常用的 Field 长度以及适合的场景，支持了一些枚举 "xs" , "sm" , "md" ,"lg" , "xl" | number \| "xs" \| "sm" \| "md" \| "lg" \| "xl" | -

### 🧐 解决方案

期望能支持 `width`, 是 bug? 不过看源码应该不是。
https://github.com/ant-design/pro-components/blob/master/packages/form/src/components/Radio/index.tsx#L56-L59

在这种 [官方DEMO: 表单项](https://procomponents.ant.design/en-US/components/field-set#full-amount-of-form-field) 布局，有时候需要列对齐(整整齐齐....

### 🚑 其他信息

```
"@ant-design/pro-form": "^1.43.5"
```

**Comment by drizzlesconsin** [comment]
更新了，写漏了 😅

**Comment by chenshuai2144** [comment]
设计师觉得最重要，哈哈

**Comment by zhuwei** [comment]
什么时候能支持定宽哦，或者width100%

**Comment by hihuangwei** [comment]
width 属性 依然无效，希望支持
