### ISSUE TITLE
👑 [需求] 骨架屏幕能发一下版么? npm 上的版本落后于文档了

### ISSUE THREAD

**Issue by Stupidism** [ant-design/pro-components#387]

**Comment by chenshuai2144** [comment]
骨架屏的代码已经很久没更新了，是最新的版本的。你是哪里不对吗

**Comment by Stupidism** [comment]
噢噢 默认按照的是 latest, 我换 next 安装吧
![image](https://user-images.githubusercontent.com/5801015/92352804-79e4d780-f111-11ea-9887-41e3dc2223ae.png)
