### ISSUE TITLE
[🐛 bug ]DrawerForm加上关闭销毁的属性后，关闭时候没有了过渡动画

### ISSUE THREAD

**Issue by linkjane** [ant-design/pro-components#3878]
### 🐛 bug 描述
最新版，DrawerForm加上destroyOnClose属性之后，关闭Drawer时没有过场动画，突然消失

### 🏞 期望结果

Drawer关闭时候有过渡动画

### 💻 复现代码

``` Javascript
<DrawerForm
    drawerProps={{
      destroyOnClose: true,
    }}
    trigger={<button>click</button>}
  >
    hello
  </DrawerForm>
```

- ProComponents 版本: [目前最新TechUI]

**Comment by samotoo** [comment]
借地反馈一个类似的问题，使用pro-form 1.46.0版本，点击footer的取消有过渡动画，但是点击右上角的关闭图标drawer就立刻消失了，没有过渡动画，目前官网上的demo就能复现。
