### ISSUE TITLE
🧐[问题]在EditableProTable中，希望实现添加子项的功能，但是parentKey不生效。

### ISSUE THREAD

**Issue by Tyler-li** [ant-design/pro-components#3881]
刚刚接触EditableProTable，希望实现点击添加子项。但是无论是action?.addEditRecord还是EditableProTable.RecordCreator其中的parentKey都不生效，都只能添加到表格的最外层。应该应该如何实现该功能？谢谢。

期望的效果：在行后有“添加子项”按钮，点击后在该项下创建一个新的子项。

<img width="860" alt="step1" src="https://user-images.githubusercontent.com/4723689/138588128-ea469cee-c417-4ade-a921-443003540192.png">
<img width="845" alt="step2" src="https://user-images.githubusercontent.com/4723689/138588136-2a4f4471-6013-411d-bdae-723c9fbc3586.png">

附上我在codesandbox上的测试：
[https://codesandbox.io/s/bian-ji-you-zi-lie-de-biao-ge-bb2c2?file=/App.tsx](https://codesandbox.io/s/bian-ji-you-zi-lie-de-biao-ge-bb2c2?file=/App.tsx)

**Comment by superAo005** [comment]
现在：在行后有“添加子项”按钮，点击后在该项下创建一个新的子项。目前在添加的子项再次添加子项 不成功
