### ISSUE TITLE
🧐[问题]proTable toolBar 如何新增一个工具图标

### ISSUE THREAD

**Issue by cloudsnet** [ant-design/pro-components#3887]
### 🧐 问题描述

我想在proTable toolBar 如何新增一个工具图标，通过toolBarRender补充的图标在dom结构内是不在一起的，并且样式上也存在差异，
通过toolbar->settings定义的化又会覆盖原有定义的，
为了方便我想直接在工具栏内补充新的进去，达到不需要重复定义样式，整体一致的感觉

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/17145414/138608005-1048516f-a251-40db-9494-239d8d546798.png)

**Comment by cloudsnet** [comment]
> 这个地方还没有开放自定义，你有什么需要吗？

我想在这里新增一个下载图标，新增图标，将按钮图标化处理

**Comment by chenshuai2144** [comment]
来个图片吧
