### ISSUE TITLE
🐛[BUG]ProTable@2.6.3 数据类型valueType == date 返回格式错误

### ISSUE THREAD

**Issue by yigexiaoairen** [ant-design/pro-components#389]
### 🐛 bug 描述

ProTable@2.6.3 数据类型valueType == date 返回格式错误，当前版本request返回格式： 2020-09-10 19:42:14，正确格式应该为：2020-09-10

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
好好写标题

**Comment by itsuki0927** [comment]
新版本解决了这个问题, 升级一下就可以了, 想了解更多看#382
