### ISSUE TITLE
👑 表单项 readonly 的一些思考

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-components#3893]
- 现在还有部分表单项没有实现 readonly 
- readonly 现在比较单调（都是以“文本”的方式显示的）
- 给readonly 加一个底色，并且保持长度属性和非readonly 下一样（这样不会导致界面变化很难控制）

**Comment by Liu-Ya** [comment]
> 这个readony 本身就是好看看的

![image](https://user-images.githubusercontent.com/23520283/141393377-1e9a7031-565a-4d6f-be4d-a2c20a357118.png)

比如上面的例子  readonly 没有宽度，第一行跟随了label宽度，之后就是看字符串长度了，这排版太乱了

**Comment by Liu-Ya** [comment]
使用 `disabled` 的排版
![image](https://user-images.githubusercontent.com/23520283/141393728-16e3485d-25f2-45e2-ac3c-35df81ae9b25.png)

**Comment by zhfish** [comment]
![image](https://user-images.githubusercontent.com/287033/142023732-b7d58168-a9ee-4af9-9cac-f55f5110829c.png)
![image](https://user-images.githubusercontent.com/287033/142023787-21efd72f-e81e-4876-aaf3-67c61e593569.png)
确实是太缺辨识度了...

**Comment by chenshuai2144** [comment]
有道理，感觉还对齐好看。应该继承编辑组件的宽度

**Comment by zhfish** [comment]
我只是自己做状态切换的时候，都是用desc组件，key🈶底色，可以考虑

**Comment by leshalv** [comment]
表单项 readonly 后，是否可以添加copy功能？

**Comment by nabaonan** [comment]
<img width="382" alt="image" src="https://user-images.githubusercontent.com/17247526/156807079-a0962894-dfe2-4810-8028-d234db6cb475.png">
ProFormDateTimeRangePicker   设置完readonly   如何让他在一行里，设置了className不生效

**Comment by fatesq** [comment]
> Contributor
大约什么时候支持呢

**Comment by fatesq** [comment]
> 有道理，感觉还对齐好看。应该继承编辑组件的宽度

大约什么时候支持呢
