### ISSUE TITLE
🐛[BUG]EditableProTable组件，当传入的某列的dataIndex是数组且valueType为date时，获取到的dataSource中该值对应的类型是datetime（带时分秒）

### ISSUE THREAD

**Issue by GODSEULGI** [ant-design/pro-components#3902]
### 🐛 bug 描述

EditableProTable组件，当传入的某列的`dataIndex`是数组且`valueType`为`date`时，获取到的dataSource中该值对应的类型是`datetime`（带时分秒）

### 📷 复现步骤

给某行的datepicker选择任意时间，点击保存数据，查看控制台打印

### 🏞 期望结果

获取到的dataSource中该值对应的类型是`date`（不带时分秒）

### 💻 复现代码

https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-u4w2q?file=/App.tsx

### © 版本信息

- ProComponents 版本: @ant-design/pro-table 2.56.3
- umi 版本
- 浏览器环境: Chrome 94.0.4606.81
- 开发环境: macOS Big Sur

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/15797337/138907976-d9cb004f-4496-424f-8469-60690308aa28.png)

**Comment by chenshuai2144** [comment]
修复咯，可以试试了

**Comment by GODSEULGI** [comment]
您的邮件我已收到喔,谢谢O(∩_∩)O么么哒
