### ISSUE TITLE
🐛[BUG] 使用cdn资源在body前引入会报错

### ISSUE THREAD

**Issue by zzfzfz** [ant-design/pro-components#3903]
### 🐛 bug 描述
使用cdn引入`https://unpkg.com/@ant-design/pro-table@2.56.3/dist/table.min.js` 
在body前引入报错
```
// xxx.html
<script src="https://unpkg.com/@ant-design/pro-table@2.56.3/dist/table.min.js"></script>
<body>
</body>
```
报错信息
```
Uncaught TypeError: Cannot read properties of null (reading 'clientWidth')
```

### 原因
```
// packages/form/src/layouts/QueryFilter/index.tsx:310
const defaultWidth = isBrowser() ? document.body.clientWidth : 1024;
```

还有一个问题就是，能否提供无`antd css`版本的`js`文件，目前通过`link`标签引入自定义主题css，需要放到`table.min.js`后面才会生效，否则会被覆盖掉

**Comment by lsjwzh** [comment]
hi 我在使用 使用cdn引入 的时候，
import { ProTable, TableDropdown } from '@ant-design/pro-components';

这段在<script></script>应该怎么写啊

**Comment by chenshuai2144** [comment]
umd 尽量放到 body 后面，umd 引入的内容都在window 上挂着，你在windows 行输出下就能看到了
