### ISSUE TITLE
🐛[BUG] ProFormSelect.SearchSelect 多次触发request 请求

### ISSUE THREAD

**Issue by hanalice** [ant-design/pro-components#3905]
### 🐛 bug 描述

使用ProFormSelect.SearchSelect 的时候，配置一个request 请求, 在渲染的输入框中输入单个字符d，控制台会打印两次
疑问：为啥每次都打印上次值和当前值？ 也就是request 了两次。

### 📷 复现步骤

在渲染的输入框中输入单个字符d，控制台会打印两次，如下截图：
![image](https://user-images.githubusercontent.com/18046501/139008882-af7cdcda-0445-4943-93d0-a5a6fbe433d0.png)

### 🏞 期望结果

期望只请求一次，在当前例子中也就是只会打印一条，且显示的是当前值 `{text: '所有的', keyWords: 'd'}`

### 💻 复现代码

```javascript

import React from "react";
import ProForm, { ProFormText, ProFormSelect } from "@ant-design/pro-form";

const request = async (params) => {
  console.log(params);
  return [
    { label: “全部”, value: "all" },
    { label: "未解决", value: "open" },
    { label: "已解决", value: "closed" },
    { label: "解决中", value: "processing" }
  ];
};

export default () => (
  <ProForm>
    <ProFormSelect.SearchSelect
      name="select"
      label="Select"
      valueType="select"
      request={request}
      placeholder="Please select a country"
    />
  </ProForm>
);
```

### © 版本信息

- ProComponents 版本: 1.18.3 和1.43.5
- umi 版本： 3.5.0
- 浏览器环境： chrome 最新版本
- 开发环境 [e.g. mac OS]： windows

**Comment by drizzlesconsin** [comment]
静态数据直接配置 `options` 就行了

**Comment by hanalice** [comment]
@chenshuai2144 文档上的示例就可以看到效果的，链接： https://codesandbox.io/s/zs2gs?file=/App.tsx

**Comment by hanalice** [comment]
@chenshuai2144 hello，此问题有啥进展么？

**Comment by chenshuai2144** [comment]
给个能用的 codebox，不要让我自己去写
