### ISSUE TITLE
🧐[问题] Custom display text (next, previous, ...) of StepsForm

### ISSUE THREAD

**Issue by htphuocdl** [ant-design/pro-components#3909]
### 🧐 Problem description
![image](https://user-images.githubusercontent.com/13588794/139056295-b7f65dea-4326-4cc5-88c6-d8d0fbaf919d.png)

**Comment by yzwxk** [comment]
This can be closed?
https://procomponents.ant.design/components/steps-form#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%86%E6%AD%A5%E8%A1%A8%E5%8D%95%E6%8C%89%E9%92%AE

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Yes, according to the documentation of Ant Design Pro Components, the Step Form component does support customizing the display text of previous and next buttons. Here is an example from the documentation:

```jsx
// Custom text for "previous" and "next" buttons
const [stepForm] = Form.useForm();
const [currentStep, setCurrentStep] = useState(0);
<StepsForm
  form={stepForm}
  current={currentStep}
  onCurrentChange={setCurrentStep}
  labelWidth="100">
  <StepsForm.Step
    title="Step 1"
    subTitle="This is a subtitle">
    {/* form fields go here */}
    <Button type="primary" onClick={() => setCurrentStep(1)}>Next</Button>
  </StepsForm.Step>
  <StepsForm.Step
    title="Step 2"
    subTitle="This is a subtitle">
    {/* form fields go here */}
    <Button onClick={() => setCurrentStep(0)}>Previous</Button>
    <Button type="primary" onClick={() => setCurrentStep(2)}>Next</Button>
  </StepsForm.Step>
  <StepsForm.Step
    title="Step 3"
    subTitle="This is a subtitle">
    {/* form fields go here */}
    <Button onClick={() => setCurrentStep(1)}>Previous</Button>
    <Button type="primary" htmlType="submit">Submit</Button>
  </StepsForm.Step>
</StepsForm>
``` 

In this example, the "Next" and "Previous" buttons have been customized using `Button` components from Ant Design. You can replace the text of these buttons with your own custom text or any other button component you prefer.
