### ISSUE TITLE
🧐[问题]EditableProTable 可编辑表格新添加一行onSave后如何替代本地临时生成的id？

### ISSUE THREAD

**Issue by yuzhigang** [ant-design/pro-components#3910]
### 🧐 问题描述

EditableProTable - 可编辑表格新添加一行时，一般会默认指定一个 id作为该行的key，这个id可能是临时生成的，并不符合后台要求，当使用onSave方法保存后，后台会返回一个真实的id，用户可能在随后的操作中使用该id作为后端编辑和删除的依据。

现在的问题是： onSave返回后，临时生成的id不知如何被取代。 使用setDataSource更新数据源不起作用。

期望： onSave后本地临时生成的id能被后台返回的id取代。

### 💻 示例代码

示例代码请查看 [codesandbox.io](https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-bxcsk?file=/App.tsx)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/2541149/139174983-1bf38438-ea03-4a27-a9b3-d9f92ed84d23.png)

**Comment by chenshuai2144** [comment]
试试配置 controlled

**Comment by wh77572** [comment]
> 配置 controlled也不行   现在只能先reload解决一下   save的时候把id更新过去了   change的时候values的值没有及时更新   这里可能需要解决一下

**Comment by wh77572** [comment]
> 试试配置 controlled

配置 controlled也不行 现在只能先reload解决一下 save的时候把id更新过去了 change的时候values的值没有及时更新 这里可能需要解决一下

**Comment by Yezhuming** [comment]
同样遇到这个问题，在onSave里setDataSource了，但是onChange的参数value数据是旧的，并不是onSave里setDataSource的数据😩

**Comment by n0tKnow** [comment]
```
editable={{
    onSave: async (rowKey, data, row) => {
        return post(`task` + (data.id ? `/${data.id}` : ""), data).then(r => {
            //replace id
            data.id = r?.data?.id
            return true
        })
    },
}}
```

**Comment by chenshuai2144** [comment]
@n0tKnow 这个有点危险，还是推荐直接reload、
