### ISSUE TITLE
EditableProTable子列的表格增加层级达到二级后无法添加🐛[BUG]

### ISSUE THREAD

**Issue by dengrujie** [ant-design/pro-components#3914]
### 🐛 bug 描述

EditableProTable子列的表格增加功能，在二级之后添加就失败了，但是依旧返回true。即使parentKeys传入React.key数组，也不能对应成功
### 🏞 期望结果
EditableProTable子列的表格增加功能没有层级限制

### 💻 复现代码
![image](https://user-images.githubusercontent.com/32860180/139199732-be27e775-448e-41ac-a0c2-e496ed46e4cb.png)
![image](https://user-images.githubusercontent.com/32860180/139199769-56c42fea-0708-4c90-a952-348b6ee40e28.png)
![image](https://user-images.githubusercontent.com/32860180/139199858-a5c0834f-1fe1-4d5b-8697-352490b22df8.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by superAo005** [comment]
EditableProTable子列的表格增加功能没有层级限制 这个实现了吗

**Comment by chenshuai2144** [comment]
注意下string和number的区别

**Comment by dengrujie** [comment]
> 注意下string和number的区别

更新protable版本后，可以实现子列无层级限制了，但是只支持position为top的情况下，不支持bottom

**Comment by Yezhuming** [comment]
> 更新protable版本后，可以实现子列无层级限制了，但是只支持position为top的情况下，不支持bottom

我能问下为什么不支持bottom吗？0.0

**Comment by wenhuacode** [comment]
更新了最新版本protable，还是会无法新增二层以上的子列
