### ISSUE TITLE
🐛[BUG] `IntlProvider` Type 'IntlType' is missing the following properties from type 'ConfigContextPropsType': intl, valueTypeMap

### ISSUE THREAD

**Issue by NE-SmallTown** [ant-design/pro-components#3915]
### 🐛 bug 描述

`IntlProvider` 的 TS 类型为 [`ConfigContextPropsType`](https://github.com/ant-design/pro-components/blob/master/packages/provider/src/index.tsx#L199) , 所以传给 `IntlProvider` 的 `value` 的值必须符合这个类型。但是[官方示例](https://procomponents.ant.design/components/table#%E5%9B%BD%E9%99%85%E5%8C%96%E7%9B%B8%E5%85%B3%E7%9A%84%E9%85%8D%E7%BD%AE)或者包里面 export 出来的语言（如 [`enUSIntl`](https://github.com/ant-design/pro-components/blob/master/packages/provider/src/index.tsx#L128)）都是 [`IntlType`](https://github.com/ant-design/pro-components/blob/master/packages/provider/src/index.tsx#L89)  类型。

这两个类型，即 `ConfigContextPropsType` 和 `IntlType` 是**不匹配的**，所以 TS 会报错：`TS2739: Type 'IntlType' is missing the following properties from type 'ConfigContextPropsType': intl, valueTypeMap`

另外：

![image](https://user-images.githubusercontent.com/18418010/139393676-4104bd35-6529-475f-8ca3-8e8593934f44.png)

这个示例前后的代码段是互相矛盾的，一个在用 `IntlProvider`，一个在用 `ConfigProvider`，实测来看，后者才能正常工作，前者是无效的。可能文档也需要更新一哈？

### 📷 复现步骤

```
import ProTable, { IntlProvider, enUSIntl } from '@ant-design/pro-table';

<IntlProvider value={ enUSIntl }>
  <ProTable />
</IntlProvider>
```

### 🏞 期望结果

不报错

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by eduardoperezitop** [comment]
I have the same problem, anyone knows how to solve it?

**Comment by vagnerlandio** [comment]
@eduardoperezitop you are using the IntlProvider or GlobalProvider?

**Comment by syssam** [comment]
any update?

**Comment by chenshuai2144** [comment]
文档已经更新。

```
import ConfigProvider form '@ant-design/pro-provide'
// use
<ConfigProvider
  value={{
    intl: enUSIntl,
  }}
>
  <ProTable />
</ConfigProvider>;
```

**Comment by yaohwu** [comment]
What does the "valueTypeMap" means in 'ConfigContextPropsType'? And  I don't found any document about that.
<img width="839" alt="image" src="https://user-images.githubusercontent.com/9320666/173790838-39c47022-9743-4229-a7c5-4f6ebad01dd5.png">

**Comment by chenshuai2144** [comment]
@yaohwu  valueTypeMap:{}

valueTypeMap alway need
