### ISSUE TITLE
🧐[问题]请问 table 如何显示Switch

### ISSUE THREAD

**Issue by PlutoCA** [ant-design/pro-components#3919]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
请问 table 如何显示Switch

![image](https://user-images.githubusercontent.com/31099607/139244712-550d1691-a3ac-4bbb-b37d-0935e4b15be9.png)
### 💻 示例代码
```javascript
  {
    title: 'Enable',
    dataIndex: 'enable',
    key: 'enable',
    valueType: 'switch',
  }
```
![image](https://user-images.githubusercontent.com/31099607/139244819-b6757251-73d9-4bdb-9281-7089c4c4242c.png)

如何才能正常显示 开关
![image](https://user-images.githubusercontent.com/31099607/139250748-c0ac07aa-4bb3-48fa-8bef-8d91fa2da6bf.png)

**Comment by chenshuai2144** [comment]
也可以用 renderText 返回成 boolean

**Comment by kgloveyou** [comment]
@chen-ccll @chenshuai2144 能给个例子吗？发现开启编辑后，显示又变成了默认值。

**Comment by chenshuai2144** [comment]
来个新issue 搞个重现出来

**Comment by kgloveyou** [comment]
> 来个新issue 搞个重现出来

https://codesandbox.io/s/ke-bian-ji-biao-ge-forked-4yvkg，可以点击【编辑】看看效果。

**Comment by chenshuai2144** [comment]
搞个新issue

**Comment by kgloveyou** [comment]
> 搞个新issue

在这里，https://github.com/ant-design/pro-components/issues/4076
