### ISSUE TITLE
🧐[问题] layout 设置成mix后，如果只有一级菜单怎么才能自动隐藏侧边栏

### ISSUE THREAD

**Issue by minm2015** [ant-design/pro-components#392]
- [ ] ### 🧐 问题描述
  layout 设置成mix后，如何在只有一级菜单的时候自动隐藏侧边栏。

如何在只有一级菜单的情况下隐藏侧边栏
![image](https://user-images.githubusercontent.com/19508192/92309027-77309800-efd4-11ea-96e6-4cdbff904f01.png)

**Comment by chenshuai2144** [comment]
还不支持这个功能，倒是个好点子
