### ISSUE TITLE
🧐[问题]LoginForm的登录按钮的文字是否可以国际化？

### ISSUE THREAD

**Issue by DengJie001** [ant-design/pro-components#3924]
### 🧐 问题描述
我真的有认真的看文档。
问题：LoginForm默认的登录按钮的文字是否可以国际化？如果可以是需要通过submitter重写，还是有更简单的处理方法，例如设置某个属性，我尝试过使用submitter->searchConfig->submitText进行实现，但是这会导致格式变得奇怪(但是可以写style控制)。而且我注意到官方的示例上，当切换国际化语言时，登录表单的登录按钮文字依然是登录。
版本：v5

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/41319355/139382979-1844d568-463a-4f83-9a3d-d3d70ad070c9.png)

**Comment by DengJie001** [comment]
除了自己重写按钮，还有解决方案嘛

**Comment by chenshuai2144** [comment]
已经有pr了，现在支持了国际化了

**Comment by frank-liu** [comment]
> 

So， 怎么做呢？

**Comment by DengJie001** [comment]
> > 
> 
> So， 怎么做呢？

我不知道我的实现方法是不是陈帅说的那种支持国际化。
我的做法是：
再LoginForm组件的submitter中，配置searchConfig，然后重写按钮的样式，将reset按钮隐藏，具体如下：
![image](https://user-images.githubusercontent.com/41319355/144220281-f33248a7-90c7-44cc-9233-a108d9c500e1.png)
如果有更好的方法也可以说一下

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/blob/5e46321e45a123f098664aa49776194f81f6e443/packages/form/src/layouts/LoginForm/index.tsx#L24

**Comment by qqjay2017** [comment]
这么写成功了  
```tsx
submitter={{
            searchConfig:{
              submitText:intl.formatMessage({ id: 'login.LogIn' }),
             
            },
            submitButtonProps:{
              style:{
                width:'100%'
              }
            },
            resetButtonProps:false
          }}
```

**Comment by frank-liu** [comment]
> > > 
> > 
> > 
> > So， 怎么做呢？
> 
> 我不知道我的实现方法是不是陈帅说的那种支持国际化。 我的做法是： 再LoginForm组件的submitter中，配置searchConfig，然后重写按钮的样式，将reset按钮隐藏，具体如下： ![image](https://user-images.githubusercontent.com/41319355/144220281-f33248a7-90c7-44cc-9233-a108d9c500e1.png) 如果有更好的方法也可以说一下

非常感谢。我是用的是antd Pro V5. 里面集成了antd pro component. 我在node_modules里找到了你说的组件，也按照你的方法修改了。但是，登录按钮还是中文。我有下面几个问题：
1 针对antd Pro V5的这个问题，我觉得是不是要重新编译node才可以使我的修改生效？
2. 如果需要重新编译node，那如果我将项目在其它地方重新部署的时候，岂不要再一次修改node_modules里的组件，再一次重新编译？

**Comment by h93910** [comment]
> 这么写成功了
> 
> ```tsx
> submitter={{
>             searchConfig:{
>               submitText:intl.formatMessage({ id: 'login.LogIn' }),
>              
>             },
>             submitButtonProps:{
>               style:{
>                 width:'100%'
>               }
>             },
>             resetButtonProps:false
>           }}
> ```

谢谢

**Comment by ByYogi** [comment]
我是来找如何改变LoginFrom控件的提交文本。
找来找去最终还是这里。谢谢你们的指引。给和我一样只想改下文本的人一个参考
`      <LoginForm    
submitter={{
  searchConfig: {
  submitText: 'Login',
  },
 }}>`

**Comment by yetrun** [comment]
> 我是来找如何改变LoginFrom控件的提交文本。 找来找去最终还是这里。谢谢你们的指引。给和我一样只想改下文本的人一个参考 ` <LoginForm submitter={{ searchConfig: { submitText: 'Login', }, }}>`

为什么文档中没有体现？

**Comment by ByYogi** [comment]
> 
> 为什么文档中没有体现？

文档中有，只是文档没有关联引导

在以下页面找`submitText`有说明
https://procomponents.ant.design/components/table?current=1&pageSize=5#search-%E6%90%9C%E7%B4%A2%E8%A1%A8%E5%8D%95

**Comment by yanxuzi** [comment]
> > 为什么文件中没有实体？
> 
> 文档中有，只是文档没有关联引导
> 
> 在下面页面找到`submitText`说明 [https://procomponents.ant.design/components/table?current=1&pageSize=5#search-%E6%90%9C%E7%B4%A2%E8%A1%A8%E5%8D %95](https://procomponents.ant.design/components/table?current=1&pageSize=5#search-%E6%90%9C%E7%B4%A2%E8%A1%A8%E5%8D%95)

有用的连接，感谢！
