### ISSUE TITLE
ProFormList的actionRender，自定义删除时传入的值非fieldKey,而是序列号index

### ISSUE THREAD

**Issue by victorli** [ant-design/pro-components#3925]
按照官方写法 ``action?.remove(props.key)`` 在乱序删除时会导致会有剩余item删除不掉，应该是个bug

目前解决方案是在传入的 ``dom`` 中取 ``index`` 值： dom[0]['_owner']['index']

**Comment by chenshuai2144** [comment]
是不是key重复了？
