### ISSUE TITLE
文档站无法加载

### ISSUE THREAD

**Issue by PeanutQAQ** [ant-design/pro-components#393]
### 🧐 问题描述
https://procomponents.ant.design/components/list 官方文档站无法加载

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/25059001/92316666-23509e00-f02a-11ea-9318-a180745bd564.png)

**Comment by RBowind** [comment]
同上

**Comment by tangyusi97** [comment]
+1

**Comment by xiefeng95** [comment]
+1

**Comment by bestdqf** [comment]
+1

**Comment by kcunitary** [comment]
+1

**Comment by archerz26** [comment]
+1

**Comment by ColouredGlaze** [comment]
@chenshuai2144 这个问题已经好几天了哈

**Comment by lm356536** [comment]
除了 ProForm 和 ProTable 可以打开,其他都打不开了.难道在升级?

**Comment by chenshuai2144** [comment]
fixed. 升级了dumi 触发了 一个github的规则
