### ISSUE TITLE
🐛[BUG]ModalForm设置destroyOnClose后,关闭动画失效

### ISSUE THREAD

**Issue by zhangheng0317** [ant-design/pro-components#3931]
### 🐛 bug 描述

如题

### 📷 复现步骤

不设置destroyOnClose时,开启和关闭动画都有,但设置了destroyOnClose后关闭ModalForm直接就没了,

### 🏞 期望结果

动画生效

### 💻 复现代码

<ModalForm
      form={form}
      visible={visible}
      title="关联审批流程"
      width={1080}
      onFinish={onFinish}
      modalProps={{
        onCancel: () => {
          onClose();
          form.resetFields();
        },
        maskClosable: false,
        destroyOnClose: true, //---这里
      }}
    >

### © 版本信息

- "@ant-design/pro-form": "^1.18.3"
- "umi": "^3.5.0",
- windows Edge
- win

**Comment by DerrickTel** [comment]
https://codesandbox.io/s/modal-biao-dan-forked-v3iq7?file=/App.tsx
目前看起来好像没啥毛病，可以出一下在线的例子吗？

**Comment by zhangheng0317** [comment]
沙盒确实没毛病,我是把ModalForm单独封装成了一个Component,用visible控制开关,就会出现动画消失问题
那就有可能是我自己的问题了.....

**Comment by chenshuai2144** [comment]
更新一下依赖呢？我感觉应该是卸载速度太快导致的

**Comment by zhangheng0317** [comment]
依赖更新后好使了,感谢🙇‍

**Comment by std4453** [comment]
> https://codesandbox.io/s/modal-biao-dan-forked-v3iq7?file=/App.tsx 目前看起来好像没啥毛病，可以出一下在线的例子吗？

你这根本没设置上 `destroyOnClose` 啊

**Comment by std4453** [comment]
https://github.com/ant-design/pro-components/issues/4405
和版本有关系 pro-form 1.45.0 没问题 最新版有问题
