### ISSUE TITLE
🐛[BUG] ModalForm的左右间距不一致

### ISSUE THREAD

**Issue by hoist1999** [ant-design/pro-components#3932]
### 🐛 bug 描述

地址：https://procomponents.ant.design/components/modal-form
问题：使用文档的范例代码，使用了ModalForm，发现表单的左右间距不一致，请问如何调整才能保持一致？谢谢。

![Snip20211101_4](https://user-images.githubusercontent.com/665212/139614315-20ed2419-30c0-4d7f-8ed0-85e7212cadf5.png)

**Comment by DerrickTel** [comment]
因为他是自动换行的，如果一定要看起来一致，可以通过class样式覆盖，写死宽度，如calc。然后又要自适应又要顶格，就要通过媒体大小来控制了。

**Comment by DerrickTel** [comment]
左右padding是一样的，可以通过
![image](https://user-images.githubusercontent.com/24643779/139636714-5c4563ba-b72c-4620-91a5-5b688546e9dd.png)
看出来

**Comment by chenshuai2144** [comment]
左右间距不一致是设计原因。
form 现在追求的是错落有致，不是整整齐齐
