### ISSUE TITLE
🐛[BUG]ProTable自带keyword搜索跟其他筛选存在冲突

### ISSUE THREAD

**Issue by ILoveChy** [ant-design/pro-components#3933]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

最近使用ProTable发现了一直存在的一个问题.
options里的serach属性自带的keyword,在存在别的筛选项时,会相互冲突,相互覆盖,
params返回的属性会丢失掉

### 🏞 期望结果

params返回的对象应合并

### 💻 复现代码

https://codesandbox.io/s/shi-yong-zi-dai-keywords-sou-suo-de-table-forked-c03ko

### © 版本信息

- "@ant-design/pro-table": "^2.54.3",
- "umi": " 3.5.20",
- 浏览器环境 chrome
- 开发环境 win11

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/37863087/139615133-9d9b744d-7419-4f16-8021-373c980b9f5f.png)
![image](https://user-images.githubusercontent.com/37863087/139615146-5c6fdc00-b2a9-41b8-95e1-7234c4a06225.png)

**Comment by tong233** [comment]
+1  v2.56.6

**Comment by chenshuai2144** [comment]
你可以自定义他
```tsx
 options={{
            search: {
              name: 'keyxxxx',
            },
          }}
```

**Comment by chenshuai2144** [comment]
理解错了，看起来是数据没有深度拷贝的原因

**Comment by chenshuai2144** [comment]
b

**Comment by ILoveChy** [comment]
@chenshuai2144  这个问题近期有计划要改不,因为这边需求还是比较希望用这个自带的搜索框的,求求了😂

**Comment by chenshuai2144** [comment]
最近会修掉了

**Comment by ILoveChy** [comment]
@chenshuai2144  这个并没有修复掉  默认的search搜索框不会覆盖轻量筛选的参数,但是筛选那块儿会把搜索框的参数覆盖掉
![image](https://user-images.githubusercontent.com/37863087/158098258-1f511b14-a2ba-4bb8-8ba5-fde230118302.png)

**Comment by ILoveChy** [comment]
用的是最新的protable

**Comment by chenshuai2144** [comment]
来个重现吧，轻量筛选没试过

**Comment by ILoveChy** [comment]
@chenshuai2144  https://codesandbox.io/s/shi-yong-zi-dai-keywords-sou-suo-de-table-forked-m0kxbw?file=/App.tsx 这个 先输入框点击搜索 再选轻量 log输出的参数就能看到被覆盖

**Comment by wangmeijian** [comment]
尝试修复中……

**Comment by wangmeijian** [comment]
已修复
