### ISSUE TITLE
🧐[问题]ProTable里面的Columns属性hideInSearch必填且必为true，否则报Object(...) is not a function

### ISSUE THREAD

**Issue by nianqingrenganmane** [ant-design/pro-components#3934]
### 🧐 问题描述

项目在同事电脑运行毫无问题，拉取下来无修改，在我的电脑运行就会出现Something went wrong.的页面，排除问题最后发现ProTable里面的Columns属性hideInSearch必须设置为true，false和不设置都会造成上述错误。node版本目前是14.0.0

### 🚑 其他信息
依赖信息
 "@ant-design/compatible": "^1.0.5",
    "@ant-design/icons": "^4.5.0",
    "@ant-design/pro-form": "1.16.2",
    "@ant-design/pro-table": "2.6.2",
    "@antv/data-set": "^0.10.1",
    "ali-oss": "^6.12.0",
    "antd": "4.7.3",
    "bizcharts": "3.5.3",
    "bizcharts-plugin-slider": "^2.1.1",
    "bpmn-js": "^6.5.1",
    "bpmn-js-properties-panel": "^0.33.2",
    "braft-editor": "^2.3.9",
    "camunda-bpmn-moddle": "^4.4.0",
    "classnames": "^2.2.6",
    "dva": "^2.4.1",
    "echarts": "^5.0.2",
    "echarts-for-react": "^3.0.1",
    "enquire-js": "^0.2.1",
    "file-saver": "^2.0.2",
    "gg-editor": "^2.0.2",
    "lodash": "^4.17.15",
    "lodash-decorators": "^6.0.1",
    "memoize-one": "^5.1.1",
    "moment": "^2.29.1",
    "netlify-lambda": "^1.6.3",
    "numeral": "^2.0.6",
    "nzh": "^1.0.4",
    "omit.js": "^1.0.0",
    "path-to-regexp": "^3.2.0",
    "prop-types": "^15.6.2",
    "qrcode.react": "^1.0.0",
    "qrcodejs2": "^0.0.2",
    "qs": "^6.9.4",
    "rc-animate": "^2.11.1",
    "react": "16.8.6",
    "react-chat-widget": "^2.1.5",
    "react-container-query": "^0.11.2",
    "react-copy-to-clipboard": "^5.0.2",
    "react-document-title": "^2.0.3",
    "react-dom": "16.8.6",
    "react-fittext": "^1.0.0",
    "react-full-screen": "^0.2.4",
    "react-media": "^1.10.0",
    "react-quill": "^1.3.5",
    "react-ueditor-wrap": "^1.0.8",
    "react-viewer": "^3.2.2",
    "resize-observer-polyfill": "^1.5.1",
    "umi": "2.8.20",
    "umi-plugin-compact": "^0.1.2",
    "umi-plugin-react": "^1.15.8",
    "umi-request": "^1.2.6",
    "video.js": "^7.14.0"

其中一个hideInSearch为false，效果下图。  在同事电脑上同样的代码就不会出现问题
![image](https://user-images.githubusercontent.com/46517903/139650908-6603fbd6-fc7e-46ba-98b5-781240a3c7cc.png)

所有的hideInSearch都为true就是正常的
![image](https://user-images.githubusercontent.com/46517903/139651103-f01519e5-6dc3-41b3-a0f7-54f5251fff4b.png)

**Comment by nianqingrenganmane** [comment]
改为undefined也是同样的报错，最头大的是只有我自己的电脑会出现这个问题，同事同样的代码就不会有问题，node环境也已经卸载换了好几个版本了
![1635814977(1)](https://user-images.githubusercontent.com/46517903/139770298-8136908c-e1ff-4191-abce-870abd9c1096.jpg)

**Comment by chen-ccll** [comment]
columns可以用serch:false不展示此搜索条件

**Comment by nianqingrenganmane** [comment]
> columns可以用serch:false不展示此搜索条件

设置了ProTable的search是有用的，hideInSearch为false也可以正常显示了，疑惑地是同事为什么不用设置也可以正常显示，头大

**Comment by chen-ccll** [comment]
search一般用得比较多，不写的话，默认值是true
