### ISSUE TITLE
🐛[BUG] Warning: Form already set 'initialValues' with path 'xxx'. Field can not overwrite it.

### ISSUE THREAD

**Issue by poyiding** [ant-design/pro-components#3936]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

Warning: Form already set 'initialValues' with path 'xxx'. Field can not overwrite it.

### 📷 复现步骤
ProForm 的Item 设置了initialValue，然后 request里做表单回显，报Warning: Form already set 'initialValues' with path 'xxx'. Field can not overwrite it. 警告

### 🏞 期望结果
设置了initialValue，在request里做表单回显不报Warning

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]

"@ant-design/pro-form": "^1.43.5",

- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![Uploading image.png…]()

**Comment by chenshuai2144** [comment]
initialValue 和 initialValues 不推荐共用的

**Comment by EcoIris** [comment]
> 
遇到同样的问题,只用initialValue给ProFormSelect或ProFormText设默认值,再在pro-form的request中请求数据回显就会报这个警告,设置默认值是为了非必填项在提交的时候也会也字段提交

**Comment by ytking** [comment]
注释// initialValue={xxx}
