### ISSUE TITLE
🐛[BUG] Editable官网例子都有问题了

### ISSUE THREAD

**Issue by 17zmhuang2** [ant-design/pro-components#3937]
### 🐛 bug 描述
点击新增后，每输入一个字符，都自动新建一行

### 📷 复现步骤

例子：
https://procomponents.ant.design/components/editable-table/#%E4%B8%8E-formitem

![image](https://user-images.githubusercontent.com/39021733/139655412-bff90dbb-fefd-401c-bcb4-d59ae7ecdd90.png)

**Comment by foreverstars** [comment]
我也出现了这个问题，为啥有的又是正常的

**Comment by chenshuai2144** [comment]
配置了name的都会有问题，我在找根因

**Comment by 17zmhuang2** [comment]
> 配置了name的都会有问题，我在找根因

Editable还有个比较严重的问题是——表格一开始没有数据时，新增一条数据，很多Bugs！官方的例子你也可以数据全删了再新增试试

**Comment by DerrickTel** [comment]
查了一下，两个原因导致的：
1.数据没有根据table这个特殊的key进行清洗（这个已经清洗了，但是会留下两个一模一样的数据在table里面，原因看第二条
2.正在输入的是一个DataSource，但是又需要和FormItem进行交互，提前打进去一个，这table里面会有两条一模一样的数据。（正在想办法

**Comment by DerrickTel** [comment]
一旦开始输入，就会因为controlled的关系，给Table打一行数据进去（A），我们正在编辑的（B）。这个AB会一直存在，并且重复，这个问题能破局，这个问题就可以解决了。
我能想到就一个方案
1.不要实时把数据更新给FormItem，只要在保存成功的时候更新给FormItem

**Comment by DerrickTel** [comment]
> 一旦开始输入，就会因为controlled的关系，给Table打一行数据进去（A），我们正在编辑的（B）。这个AB会一直存在，并且重复，这个问题能破局，这个问题就可以解决了。 我能想到就一个方案 1.不要实时把数据更新给FormItem，只要在保存成功的时候更新给FormItem

这样的话可能数据都不用清洗了

**Comment by Liu-Ya** [comment]
#3965 没有解决问题啊，为什么关闭呢 @chenshuai2144

**Comment by chenshuai2144** [comment]
@Liu-Ya  重写了一下性能应该好多了
