### ISSUE TITLE
🧐[问题]protable分页多选，之前选择的会被当前页选择项覆盖

### ISSUE THREAD

**Issue by taofeifanIT** [ant-design/pro-components#3939]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 💻 示例代码
` <ProTable
        rowSelection={{
          selections: [Table.SELECTION_ALL, Table.SELECTION_INVERT],
          selectedRowKeys,
          onChange: (rowKeys: any[],row: any) => {
            setSelectedRowKeys(rowKeys);
            setCheckedRow(row)
          },
        }}
        size="small"
        bordered
        columns={columns(api, refresh, isAuth,selfShow,showPop,hasDescription)}
        actionRef={actionRef}
        formRef={ref}
        request={async (params = {}) =>
          new Promise((resolve) => {
            const tempParams = {
              ...params,
              // ...sortParams,
              page: params.current,
              limit: params.pageSize,
            };
            api.listApi(tempParams).then(
              (res: {
                data: {
                  list: any[];
                  total: number;
                };
                code: number;
              }) => {
                setTempData(res.data.list)
                resolve({
                  data: res.data.list,
                  // success 请返回 true，
                  // 不然 table 会停止解析数据，即使有数据
                  success: !!res.code,
                  // 不传会使用 data 的长度，如果是分页一定要传
                  total: res.data.total,
                });
              },
            );
          })
        }
        editable={{
          type: 'multiple',
        }}
        rowKey="id"
        search={{
          labelWidth: 'auto',
          span: {
            xs: 14,
            sm: 24,
            md: 12,
            lg: 12,
            xl: 8,
            xxl: 6,
          },
        }}
        pagination={{
          pageSize: 30,
          pageSizeOptions:['10', '20','30','50','100','200'],
          showQuickJumper: true
        }}
        options={{
          search: false,
        }}
        // eslint-disable-next-line @typescript-eslint/no-shadow
        onRow={(record: { id: number; notes: string; vendor_sku: string; ts_sku: string }) => {
          return {
            // eslint-disable-next-line @typescript-eslint/no-unused-vars
            onDoubleClick: (event): void => {
              setDrawerVisible(true);
              setRecord({
                id: record.id,
                content: record.notes || '',
                title: record.ts_sku,
              });
            },
            onClick: () => {
              if (drawerVisible) {
                setRecord({
                  id: record.id,
                  content: record.notes || '',
                  title: record.ts_sku,
                });
              }
            },
          };
        }}
        dateFormatter="string"
        headerTitle={<span style={{ fontFamily: 'fantasy' }}>{title}</span>}
        toolBarRender={() => [
          <Input key='tempselect' style={{width: '80px'}} onChange={e => {
            setSelectNum(parseInt(e.target.value))
          }} addonAfter={<CheckSquareOutlined onClick={(e) => {
             let tempSelectData:{id:number, vendor_sku: string}[] = JSON.parse(JSON.stringify(tempData))
              tempSelectData.length = selectNum
              let ids = tempSelectData.map(itemIds => {
                return itemIds.id
              })
              setSelectedRowKeys(ids)
          }}  />} defaultValue={selectNum} />,
          <Button
            key="uploadAndDown"
            disabled={!selectedRowKeys.length}
            style={{display:  initialState?.currentUser?.auth_group?.title !== 'Outsourcer' ? 'inline-block' : 'none'}}
            onClick={() => {
              setConfigurationVisible(true)
            }}
            icon={<ProfileOutlined />}
          >
            Batch list
        </Button>,
          initialState?.currentUser?.auth_group?.title !== 'Outsourcer' ? (<Button
            onClick={() => {
              const valObj = ref.current?.getFieldsValue();
              let tempParams: any = '';
              let index = 0;
              for (const key in valObj) {
                if (valObj[key]) {
                  const paramsStr = `${key}=${valObj[key]}`;
                  if (index === 1) {  
                    tempParams += `${paramsStr}`;
                  } else {
                    tempParams += '&' + paramsStr;
                  }
                }
                index++;
              }
              if (tempParams) {
                tempParams = `${api.downloadApi()  }?${  tempParams  }&is_download=1`;
              } else {
                tempParams = `${api.downloadApi()  }?is_download=1`;
              }
              createDownload(`test.csv`, tempParams);
              // console.log(tempParams)
            }}
          >
            Download
          </Button>) : null
          ,
          <Button disabled={!selectedRowKeys.length} key='toolDelete' danger type='primary' onClick={() => {
            deleteListItem()
          }}>Delete</Button>
        ]}
      />`

### 🚑 其他信息

首先点到第一页全选
![image](https://user-images.githubusercontent.com/42193371/139781319-44531c99-7093-4cca-9695-dbbb04469ac0.png)
然后点到第二页
![image](https://user-images.githubusercontent.com/42193371/139780900-92f615e0-041b-4612-8e4e-c568eb88f0ee.png)
再选择一个
![image](https://user-images.githubusercontent.com/42193371/139781420-9efaa752-d561-4f69-9f9f-dc4413ae15d3.png)
就直接被覆盖了，一脸懵逼，不知道是不是我哪里配置的问题

**Comment by chenshuai2144** [comment]
每次选择都是只对于当前的页面的，因为上一页已经被销毁了

**Comment by taofeifanIT** [comment]
如何才能跨页多选啊

**Comment by chenshuai2144** [comment]
自己存一下多选的内容，并且做一下去重

**Comment by taofeifanIT** [comment]
好的，感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月17日(星期五) 晚上7:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/pro-components] 🧐[问题]protable分页多选，之前选择的会被当前页选择项覆盖 (Issue #3939)





 
自己存一下多选的内容，并且做一下去重
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
