### ISSUE TITLE
❓ codesanbox dependency issues

### ISSUE THREAD

**Issue by bianzheCN** [ant-design/pro-components#3944]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

I am currently learning the encapsulation skills from `pro-table` and I keep seeing dependency bugs in codesandbox.
Is it caused by some bugs?

### 💻 示例代码

https://codesandbox.io/s/bl8tw?file=/App.tsx

### 🚑 其他信息

Please check out the link above, and I would appreciate it if it helps, thanks!

**Comment by DerrickTel** [comment]
![image](https://user-images.githubusercontent.com/24643779/139810904-b4c0cf00-f02f-4aca-b2b6-d59c51a49e24.png)
可以先把这个改成4.1.0

**Comment by bianzheCN** [comment]
> ![image](https://user-images.githubusercontent.com/24643779/139810904-b4c0cf00-f02f-4aca-b2b6-d59c51a49e24.png) 可以先把这个改成4.1.0

谢谢！
