### ISSUE TITLE
EditableProTable自定义编辑组件onsave的时候取值取不到

### ISSUE THREAD

**Issue by yhwtest** [ant-design/pro-components#3946]
EditableProTable自定义编辑组件onsave的时候取值取不到

https://codesandbox.io/s/ke-bian-ji-biao-ge-forked-86wg5?file=/App.tsx

**Comment by chenshuai2144** [comment]
不要加<> 和其他的类型的包裹，不然是 value和 onchange 注入了了

**Comment by yhwtest** [comment]
> 不要加<>和其他的类型的包围，用的是价值和变化注入了

感谢，是我自己操作错了
