### ISSUE TITLE
ProFormList 中 配置 creatorButtonProps={position: 'top'} 会导致 list 中的每一项重渲🐛[BUG]

### ISSUE THREAD

**Issue by Aliveing** [ant-design/pro-components#3947]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

如题，在 ProFormList  中设置添加按钮到顶部，会让列表里每一个 div 都重新渲染，在 30+ 以上的列表 item 时会有明显卡顿，而设为 bottom 的卡顿明显小很多

### 📷 复现步骤

下方复现代码中上方是默认 position='bottom' 的新增按钮，下方是设置 position='top' 的新增按钮，此时打开 chrome 开发者工具，分别检查这两个 list 中单个 item，chrome 的 elements 在 dom 节点重渲时会有高亮显示，这时分别点击两个 list 的 添加按钮，发现 position='bottom' 的添加按钮只会重渲新添加的 dom 节点，而 top 的添加按钮会重新渲染 list 下所有的 dom 节点，详细请看下方复现代码以及录屏。

### 🏞 期望结果

在开发使用中有两点期望：
1. 配置 creatorButtonProps={position: 'top'} 性能可以接近 'bottom'
2. ProFormList 的添加按钮希望可以增加脱离列表滚动的配置，要不然浏览数据后要添加一条数据每次都要滚动到最上面或者最下面添加，交互上挺麻烦

### 💻 复现代码

复现代码是从 [官方文档](https://procomponents.ant.design/components/group#%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8) 的 CodeSandBox 中 fork 过去的，在线示例：[CodeSandBox](https://codesandbox.io/s/proform-list-forked-nx2sd?file=/App.tsx)
### © 版本信息
```json
    "react": ">=16.9.0",
    "@ant-design/pro-form": "1.45.0",
    "antd": "4.x",
    "react-dom": ">=16.9.0"
```
版本信息具体在：[CodeSandBox package.json](https://codesandbox.io/s/proform-list-forked-nx2sd?file=/package.json)
### 🚑 其他信息

https://user-images.githubusercontent.com/11768879/139795585-4088308a-f8d7-4661-b91b-c64abb29c2c0.mov

**Comment by chenshuai2144** [comment]
这个问题提的挺好的

**Comment by chenshuai2144** [comment]
问题应该是这边使用了index 来当 key 导致的，我们会map一下然后渲染导致key 被刷新了
