### ISSUE TITLE
建议添加外部控制按哪行排序功能👑 [需求]

### ISSUE THREAD

**Issue by wzn7423162** [ant-design/pro-components#3952]
建议添加外部控制按哪行排序，比如列标题栏自定义一个下拉选择框，并且将值传入request（通过params传入），当按此方法传入时，可以控制order的参数也按本列传入，并控制本列排序的按钮选中。

**Comment by chenshuai2144** [comment]
展开聊一下？我没有听懂你的诉求

**Comment by wzn7423162** [comment]
就是实现下面网址中antd中table实现的效果。表单外部组件控制表单按哪一列排序
https://www.jb51.net/article/199874.htm
我想用antProTable实现下面的效果：（之前点的其他列，按其他列来排序）选择select时，自动按照本列排序![image](https://user-images.githubusercontent.com/83341407/140039251-3a5ea6cc-d2f4-4611-adb3-e45a4463ccbf.png)

**Comment by chenshuai2144** [comment]
antd已经有这个demo了呀。


我觉得这个交互怪怪的，还丢失掉了标题的信息，不会成为内置的规范的
