### ISSUE TITLE
🐛[BUG]在 ProTable 的 render 里使用 ModalForm 的 request 的问题

### ISSUE THREAD

**Issue by jiyingzhi** [ant-design/pro-components#3953]
在 ProTable 的 render 里使用 ModalForm 的 request，在页面加载时，request 就会被调用，如果表格有20行，就会一开始调用20次接口，应该在 Modal 被打开的时候才触发 request

**Comment by drizzlesconsin** [comment]
加 visible 控制

{visible && <ModalForm visible />}

**Comment by chenshuai2144** [comment]
@jiyingzhi modal 不应该设置到行里面的，这样是巨大的性能浪费

**Comment by jiyingzhi** [comment]
那应该怎么做

**Comment by chenshuai2144** [comment]
用visible 来控制，所有的行公用一个，用state来传递速度

**Comment by lifegit** [comment]
总觉得是ModalForm的设计问题。应该触发了trigger后再request。

**Comment by lifegit** [comment]
目前看到：当页面首次render时，会触发一次request。当点击trigger时，request又触发了一次。

**Comment by chenshuai2144** [comment]
手动判断一下呢。useEffect 总是触发的。

**Comment by Miever1** [comment]
我感觉这个设计确实不太合理，如果首次render时触发一次request，那这个trigger多半时候是废的，弹窗一边都会有请求的
