### ISSUE TITLE
pro-table中的搜索栏当valueType='dateTimeRange'的时候，search中的transform在哪一个步骤转换的？

### ISSUE THREAD

**Issue by MachoManCk** [ant-design/pro-components#3954]
pro-table中的搜索栏当valueType='dateTimeRange'的时候，search中的transform在哪一个步骤转换的？
可否提供代码看一下，找了半天没看到
 {
    title: '下单时间',
    dataIndex: '下单时间',
    hideInTable: true,
    valueType: 'dateTimeRange',
    search: {
      transform: (value) => ({ startTime: value[0], endTime: value[1] }),
    },
  },

**Comment by chenshuai2144** [comment]
在  proform 的 onfinsh 里面处理的哦。

https://github.com/ant-design/pro-components/blob/2cabc431021ccba48c53ec86421b6ce0ee267dbe/packages/form/src/BaseForm/index.tsx#L401-L410
