### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by zyanfly** [ant-design/pro-components#3955]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

使用ProTable时，希望select的状态工具条能一直展示，但是在rowSelection中配置alwaysShowAlert提示无此属性
### 💻 复现代码

![image](https://user-images.githubusercontent.com/26576825/140017578-9f68e400-4574-4345-862f-fb1b0cc127f3.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by drizzlesconsin** [comment]
proTable 什么版本

**Comment by zyanfly** [comment]
sorry，找到问题了，升级到最新版本后问题没有了。
