### ISSUE TITLE
🧐[问题]Form设置默认值initialValues可以对其进行预处理吗

### ISSUE THREAD

**Issue by 17zmhuang2** [ant-design/pro-components#3957]
### 🧐 问题描述

Form.Item中有使用到TimePicker，设置的initialValues中TimePicker的默认值为字符串类型，Form中可以对其预处理吗？还是说只能在外面进行处理后再传进去？

**Comment by chenshuai2144** [comment]
<html>
<body>


etValueProps | 为子元素添加额外的属性 | (value: any) => any | - | 4.2.0
-- | -- | -- | -- | --



</body>
</html>

`用这个   (value: any) => ({value:"处理以后的value "})`
