### ISSUE TITLE
🐛[BUG]Pro Form中使用request去请求，发现本地请求了一次，但是线上会去请求两次

### ISSUE THREAD

**Issue by lkzwc** [ant-design/pro-components#3959]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🏞 期望结果

![image](https://user-images.githubusercontent.com/84896877/140052384-20cd4ad4-725e-4838-8a36-197db0863326.png)

![image](https://user-images.githubusercontent.com/84896877/140052456-68e8f7ca-a03e-4de3-8a66-a96560b96186.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] 2.3.1
- umi 版本 ^3.2.14
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by codedart2018** [comment]
本地也两次请求，我删除干净代码就执行request 也发现是两次请求

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/4074
