### ISSUE TITLE
🧐[问题]Table的expandable有没有方法可以控制'+'这个展开按钮？有些记录是不需要展开的。

### ISSUE THREAD

**Issue by oxygen-xx** [ant-design/pro-components#3960]
### 🧐 问题描述

Table的expandable有没有方法可以控制'+'这个展开按钮？有些记录是不需要展开的。
一直没找到控制‘+’按钮的方法。现在只能在expandedRowRender中返回null，但这会形成一个不美观的空行。如果能根据属性去判断是否需要显示'+'按钮，还能控制expandedRowRender返回的如果是Null不增加空行，会更好一些。

**Comment by chenshuai2144** [comment]
https://ant.design/components/table-cn/#expandable

试试这个属性

<html>
<body>


rowExpandable | 设置是否允许行展开 | (record) => boolean | -
-- | -- | -- | --



</body>
</html>

**Comment by superAo005** [comment]
用了这个属性不起作用是什么原因呢
antd：4.14
pro-table：2.57.1
