### ISSUE TITLE
🐛[BUG]水印穿透，应如何防穿透

### ISSUE THREAD

**Issue by zly-smile** [ant-design/pro-components#3961]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

引用水印时，发现水印穿透，遮住了现有文案

### 🏞 期望结果

期望 能有一个属性来支持防穿透。

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
调整下水印的密度和透明度把，这种没啥办法的。动态更新水印的层级性能又太差了
