### ISSUE TITLE
🧐[问题] protable 中使用了select与dependencies,request属性，被依赖的选项变化了之后，没有清空依赖链路的选择值

### ISSUE THREAD

**Issue by peng19860226** [ant-design/pro-components#3963]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
protable 中使用了select与dependencies属性，被依赖的选项变化了之后，没有清空依赖链路的选择值：
省，市，区 3个维度，省选择了，request过滤市，市选择了过滤区；
省市区都选择了，再改变省，如何才能清空后面两个已经选择的值

![image](https://user-images.githubusercontent.com/47234766/140266761-418f86f7-144d-4b67-b39c-d13a53206e19.png)
![image](https://user-images.githubusercontent.com/47234766/140266863-04e3623f-a6f4-4547-a29c-acfb3085f566.png)

**Comment by chenshuai2144** [comment]
现在是没有的，要在renderForm里面自定义了
