### ISSUE TITLE
👑 [需求] ProTable的性能问题

### ISSUE THREAD

**Issue by zyanfly** [ant-design/pro-components#3964]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
使用ProTable的过程中确实体会到插件用心了，节省了很多代码，但是在动态columns并且自定义了valueType的情况下，切换tabs触发请求需要2秒左右，测试自定义valueType时，render函数不断的渲染

### 🏞 期望结果
table性能可以和antd中的table差不多

### © 版本信息
"@ant-design/pro-table": "^2.56.7",
- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 3.4.0
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS] macOs

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26576825/140269612-b3691e84-b120-4a99-b41a-4a3684127565.png)
![image](https://user-images.githubusercontent.com/26576825/140269646-5705235e-081e-4369-853d-b7810861234a.png)

**Comment by kaoding** [comment]
mfsu禁掉试试看。

**Comment by zyanfly** [comment]
> mfsu禁掉试试看。

没用

**Comment by chenshuai2144** [comment]
一列被渲染了三次。pro的老问题了 可以应shouldcellupdate来缓解一下

**Comment by zyanfly** [comment]
> 一列被渲染了三次。pro的老问题了 可以应shouldcellupdate来缓解一下

感觉不是更新的问题，而是初始渲染的执行问题，切换tab请求数据有延迟

**Comment by Wd3Curry30** [comment]
> 一列被渲染了三次。pro的老问题了 可以应shouldcellupdate来缓解一下

大神，请教一下，我也遇到了类似的问题，造成了输入卡顿。
但我设置了shouldcellupdate貌似只影响了render，
看了此前issue的回复，也设置了shouldupdate，但renderFormUpdate还是会重新渲染
```
{
      title: '工作描述',
      dataIndex: 'task',
      key: 'task',
      width: '11%',
      shouldCellUpdate:(record, prev) => record.task !== prev.task,
      formItemProps: {
        shouldUpdate: (record, prev) => {return record.task !== prev.task},
        rules: [
          {
            required: true,
            message: '此项为必填项',
          },
          {
            max: 512,
            whitespace: true,
            message: '最长为512位，且不能全为空格/换行',
          },
        ],
      },
      renderFormItem: () => {return <ProFormTextArea />},
      render: (_, record) => <span className={styles.cell}>{record.task}</span>
    },
```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，`shouldCellUpdate` 确实只影响了单元格的渲染，如果要影响整个列，需要在列的配置项中设置 `shouldUpdate`。

在你提供的代码中，似乎列的 `shouldUpdate` 已经被正确设置了，不过你提到 `renderFormUpdate` 会重新渲染，这是因为 `renderFormUpdate` 是一个函数，函数在每次刷新时都会重新执行，和 `shouldUpdate` 并没有直接的关系。

你可以尝试在 `renderFormUpdate` 中使用 `React.memo` 来缓存组件。例如：

```
const MemoProFormTextArea = React.memo(ProFormTextArea)

{
  title: '工作描述',
  dataIndex: 'task',
  key: 'task',
  width: '11%',
  shouldCellUpdate: (record, prev) => record.task !== prev.task,
  formItemProps: {
    shouldUpdate: (record, prev) => record.task !== prev.task,
    rules: [
      {
        required: true,
        message: '此项为必填项',
      },
      {
        max: 512,
        whitespace: true,
        message: '最长为512位，且不能全为空格/换行',
      },
    ],
  },
  renderFormItem: () => <MemoProFormTextArea />,
  render: (_, record) => <span className={styles.cell}>{record.task}</span>
}
```

这样，每次数据更新时，如果 `task` 没有变化，`ProFormTextArea` 组件就不会被重新渲染。

**Comment by XinYueXiao** [comment]
可以尝试使用以下方案
https://juejin.cn/post/7276257954297479220
