### ISSUE TITLE
👑 [需求] 改进 ProComponent官方文档网站的搜索显示

### ISSUE THREAD

**Issue by AnteeHub** [ant-design/pro-components#3968]
### 🥰 需求描述

ProComponent 官方文档站顶部的搜索栏进行搜索后会显示候选列表，但在点击候选项跳转后或者清空搜索栏内容时，候选列表不会关闭。这一点比较影响文档的阅读。这个情况可以在浏览 [官方文档](https://procomponents.ant.design) 搜索任意内容时复现。

### 🧐 解决方案

清空搜索内容或者点击候选列表跳转后，搜索栏的候选列表自动关闭。

### 🚑 其他信息

补充截图：

![图片](https://user-images.githubusercontent.com/55703989/140447436-99c5b2d7-19d5-4754-ada7-11581a89441e.png)
![Kapture 2021-11-05 at 11 44 44](https://user-images.githubusercontent.com/55703989/140455231-30a2b6ea-c306-4eb1-9eb7-42c8c94537e0.gif)

**Comment by chenshuai2144** [comment]
@PeachScript  来看看

**Comment by PeachScript** [comment]
dumi 文档无法复现，pro 文档可以复现，感觉是和 pro 站点的某些功能冲突了？

**Comment by chenshuai2144** [comment]
umi 也是这样的哦

**Comment by PeachScript** [comment]
> umi 也是这样的哦

是怎么操作的，我试了一下正常的？

**Comment by chenshuai2144** [comment]
现在可以了，估计是什么东西没加载回来。
家里的网络umi 一直挂
