### ISSUE TITLE
🐛[BUG] valueType money 去掉货币符号前缀后 precision 失效

### ISSUE THREAD

**Issue by GamesSoul** [ant-design/pro-components#3971]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
table的 valueType设置

### 📷 复现步骤
配置table的 columns 时 给金额配置的是  
![图片](https://user-images.githubusercontent.com/37973776/140476310-c164ba6d-880e-4ee8-b8b1-a7d4ff5b5700.png)
但是将moneySymbol 设置为true时  precision就生效 设置为false 就失效了

### 🏞 期望结果

该段落保留小数点后两位

### 💻 复现代码

![图片](https://user-images.githubusercontent.com/37973776/140476310-c164ba6d-880e-4ee8-b8b1-a7d4ff5b5700.png)

### © 版本信息

- ProComponents 版本: 
-  "@ant-design/pro-card": "^1.16.2",
    "@ant-design/pro-descriptions": "^1.9.28",
    "@ant-design/pro-form": "^1.46.0",
    "@ant-design/pro-layout": "^6.27.2",
    "@ant-design/pro-list": "^1.17.7",
    "@ant-design/pro-table": "^2.56.7",

**Comment by DerrickTel** [comment]
https://codesandbox.io/s/cha-xun-biao-ge-forked-v0tps

你出个demo吧

**Comment by GamesSoul** [comment]
> [https://codesandbox.io/s/cha-xun-biao-ge-forked-v0tps ](https://codesandbox.io/s/cha-xun-biao-ge-forked-v0tps)
> 
> 你出个demo吧

![图片](https://user-images.githubusercontent.com/37973776/140692103-4f03ef8f-ec34-4742-bbe8-c6240ad6b8d3.png)
老哥 你给的demo 就已经显示不正常了  保留两位小数 展示的却是三位的，这里还有个问题 如果我保留四位小数 在readonly模式下 也是三位  就很尴尬

**Comment by DerrickTel** [comment]
其实我也不知道你说的失效是什么意思，我随便把你的代码拉出去放到沙盒里面去而已，不过现在就清晰多了。定位问题什么的就方便多了，希望以后可以附上demo和稍微具体错误的地方...不然找起来很麻烦。

**Comment by GamesSoul** [comment]
> 其实我也不知道你说的失效是什么意思，我随便把你的代码拉出去放到沙盒里面去而已，不过现在就清晰多了。定位问题什么的就方便多了，希望以后可以附上demo和稍微具体错误的地方...不然找起来很麻烦。

感谢，  失效那个是保留小数点后几位有问题 无法保留设定的小数点后几位

**Comment by chenshuai2144** [comment]
这两个用了同一个api，所以才会这样的。是个bug
