### ISSUE TITLE
🧐[问题]  最新版本的proTable 组件

### ISSUE THREAD

**Issue by zhubufang** [ant-design/pro-components#3974]
### 🧐 问题描述

最新版本的proTable 组件  改变隐藏列的时候 ColumnState onChange 没有触发 

新版本的proTable 组件  改变隐藏列的时候 ColumnState onChange 没有触发  请问这个onChange是要如何触发

### 💻 示例代码
![image](https://user-images.githubusercontent.com/40162775/140488447-f1e463d1-1941-4108-969b-8c108b1f293d.png)

![image](https://user-images.githubusercontent.com/40162775/140488050-cc18c0fe-0bad-4bd7-b6dd-57ab6eab33b4.png)
![image](https://user-images.githubusercontent.com/40162775/140488215-598dea66-8f6b-4187-98f4-a0282eb93a74.png)

**Comment by chenshuai2144** [comment]
大小写写错了。

**Comment by zhubufang** [comment]
![image](https://user-images.githubusercontent.com/40162775/143672658-530f9262-8506-4945-9509-ae6ddd5c1eb2.png)
能否设置某些列不出现在settings中
