### ISSUE TITLE
👑 [需求]能不能搞个和 form-generator 的功能呢？

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-components#3977]
参考：https://gitee.com/mrhj/form-generator 这个搞一个系统，表单自动编辑器撒。

**Comment by kaoding** [comment]
https://github.com/alibaba/x-render

**Comment by xgj1988** [comment]
@kaoding  XRender这个是基于antd的吗？

**Comment by drizzlesconsin** [comment]
https://x-render.gitee.io/form-render/
> FormRender 1.0 是下一代的 React.js 表单解决方案。
