### ISSUE TITLE
🐛[BUG] BetaSchemaForm 表单中的使用formRef无法获取

### ISSUE THREAD

**Issue by zhouzyc** [ant-design/pro-components#3979]
### 🐛 bug 描述
 以下代码中无法获取formRef，去掉 request={request} 注释获取不到。下面有具体的codesandbox

  `<>
      <BetaSchemaForm<DataItem>
        formRef={formRef}
       // request={request}
        visible={true}
        layoutType="ModalForm"
        onFinish={async (values) => {
          console.log(formRef);
        }}
        columns={columns}
      />
    </>`

> 

### 🏞 期望结果
期望可以获取到
### 💻 复现代码
https://codesandbox.io/embed/schema-biao-dan-forked-n0zfj?fontsize=14&hidenavigation=1&theme=dark

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
看了下没啥问题，你有其他限制条件吗？

**Comment by zhouzyc** [comment]
需要吧这个注释打开


趾蝣一粷`~怼卜戚~我~愛`YOU



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月9日(星期二) 下午5:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 🐛[BUG] BetaSchemaForm 表单中的使用formRef无法获取 (Issue #3979)





 
看了下没啥问题，你有其他限制条件吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhouzyc** [comment]
> 看了下没啥问题，你有其他限制条件吗？
// request={request} 这个注释打开

**Comment by chenshuai2144** [comment]
打开了也没问题。
![image](https://user-images.githubusercontent.com/8186664/140900163-88bfffd0-4d8f-4fa9-be7b-6a5a2d876cd1.png)

**Comment by zhouzyc** [comment]
是因为我电脑关系？




趾蝣一粷`~怼卜戚~我~愛`YOU


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月9日(星期二) 下午5:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 🐛[BUG] BetaSchemaForm 表单中的使用formRef无法获取 (Issue #3979)





 
打开了也没问题。
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhouzyc** [comment]
是真的有问题，请注释了打开，打开了注释多试几遍看看

趾蝣一粷`~怼卜戚~我~愛`YOU


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月9日(星期二) 下午5:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 🐛[BUG] BetaSchemaForm 表单中的使用formRef无法获取 (Issue #3979)





 
打开了也没问题。
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenshuai2144** [comment]
搞个稳定复现吧，我在本地也不可以

**Comment by MXWXZ** [comment]
还是有问题的，L60 
```
onFinish={async (values) => {
          console.log(formRef.current?.getFieldsValue());
}}
```
在不使用request的时候可以获得表单值，去掉注释后就变成undefined了。其他几个函数比如setFieldsValue似乎也无效，貌似只要request和formref一起使用就会出问题
