### ISSUE TITLE
🐛[BUG] Pro layout menu items do not render links when path starts with /

### ISSUE THREAD

**Issue by ops1ops** [ant-design/pro-components#3986]
https://github.com/ant-design/pro-components/blob/master/packages/layout/src/components/SiderMenu/BaseMenu.tsx#L175

Current behavior: Menu items are only rendered as links when path is http url

Expected behavior: path can start with / (for example /home, /items and etc)

**Comment by chenshuai2144** [comment]
We cannot distinguish absolute paths from relative paths if we support "/"

**Comment by ops1ops** [comment]
but does it really matter? why don't you let developer to choose which path to use

**Comment by chenshuai2144** [comment]
you can use menuItemRender   choose which path to use

**Comment by ops1ops** [comment]
but if i only need to change path in your link element, i will have to duplicate your structure and classes in my implementation just to use relative path

can you explain whats the problem when developer chooses which path to use?

**Comment by chenshuai2144** [comment]
You can use menuItemRender to customize any behavior of the jump.

We have no way of knowing whether you want to use react-router redirect or href redirect, we need a rule.
So we chose URLs that start with http, thinking they need to use href to jump. The rest is to use react-router to jump
