### ISSUE TITLE
🧐[问题] 请问如何动态改变proTable中某列的「filter: 表头的筛选菜单项」？

### ISSUE THREAD

**Issue by OldPilot** [ant-design/pro-components#3988]
### 🧐 问题描述
目前在编写一个简单的表格页面，用了protable，数据量不大所以一次性全部从后端请求到，由前端进行排序筛选

表格中部分列需要提供前端表格内的筛选，既下图中的筛选能力
![image](https://user-images.githubusercontent.com/18022813/140758871-c2775e90-32de-42af-84c7-7b0a33eba388.png)

我希望此处能自动根据目前得到的数据的该列全部数据进行筛选项的调整，想了解该如何做到。

**Comment by chenshuai2144** [comment]
https://ant.design/components/table-cn/#components-table-demo-reset-filter

看这个demo吧。需要手动配置的

**Comment by OldPilot** [comment]
> https://ant.design/components/table-cn/#components-table-demo-reset-filter
> 
> 看这个demo吧。需要手动配置的

😭因为手动配置不符合需要所以想探究一下怎么自动适配

**Comment by Amigosen** [comment]
这也没解决啊，如何根据表格里的数据自动生成筛选项呢？在我做前端的分页的情况下可以拿到所有表格数据
