### ISSUE TITLE
列表点击编辑弹出浮层表单，并填充上当前行的值🧐[问题]

### ISSUE THREAD

**Issue by linghuchong-123** [ant-design/pro-components#3989]
### 🧐 问题描述

我想实现列表点击编辑弹出浮层表单，并填充上当前行的值，现在用的是initialValues，但是这个是一加载就渲染，而列表是异步获取，所以拿不到当前行的值，应该怎么实现这个功能；
2.setFieldsValue 这个属性在哪个位置可以设置，我在modalform里设置提示没有这个属性；
3.render属性在哪个表单中有

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/67812417/140858042-745e8526-8a05-44d4-a365-1dee92a2f4e4.png)

![image](https://user-images.githubusercontent.com/67812417/140857474-a7f09f88-73ab-4abc-897f-8fad16697c14.png)

**Comment by chenshuai2144** [comment]
modal form有个request 的 api 来帮你实现个功能

**Comment by linghuchong-123** [comment]
> modal form 有个 request 的 api 来帮你实现这个功能
> 
> `reuqest={async ()=> initialValues}`

您的意思是重新请求一遍后端接口吗

**Comment by chenshuai2144** [comment]
initialValues 可以是任何地方来的数据的。 reuqest 会销毁 form的。
