### ISSUE TITLE
🧐[问题]'description' does not exist in type 'ListToolBarProps'

### ISSUE THREAD

**Issue by wenxiayili** [ant-design/pro-components#3990]
### 🧐 问题描述

ProTable，'description' does not exist in type 'ListToolBarProps'。

### 💻 示例代码
```
<EditableProTable<LabelColumnType>
        toolbar={{
          title: '标签列表',
          subTitle: 'ListToolBar',
          description: '12312', 
        }}
```

**Comment by wenxiayili** [comment]
这个属性是否删除了？我看代码中ListToolBarProps的定义，没有description这个属性

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/blob/cf23e82dcd4263dd40a912ed6acebb8f9da3bf5e/packages/table/src/components/ListToolBar/index.tsx#L38-L64

他是在的哦

**Comment by wenxiayili** [comment]
> https://github.com/ant-design/pro-components/blob/cf23e82dcd4263dd40a912ed6acebb8f9da3bf5e/packages/table/src/components/ListToolBar/index.tsx#L38-L64
> 
> 他是在的哦

description这个属性在哪定义的呢？您给的代码真没看到...

**Comment by chenshuai2144** [comment]
不支持 description 的，你用 subTitle 代替把。我看错了。以为你说的是subtitle

**Comment by wenxiayili** [comment]
> 不支持 description 的，你用 subTitle 代替把。我看错了。以为你说的是subtitle

好的，谢谢您
