### ISSUE TITLE
🧐[问题]默认整体风格(navTheme)下切换主题色，刷新页面后会重置成默认主题色

### ISSUE THREAD

**Issue by yuuunagi** [ant-design/pro-components#3991]
### 🧐 问题描述
如题，是特意设定成这样的吗?

![图片](https://user-images.githubusercontent.com/51359328/140884239-c0892420-1785-4b5d-9943-f6d15b5df86e.png)

**Comment by chenshuai2144** [comment]
你和默认的一样当然没必要重新加载咯

**Comment by yuuunagi** [comment]
> 
> 
> 你和默认的一样当然没必要重新加载咯
但是我修改了主题色从原来的拂晓蓝改成了比如说火山，再刷新页面，主题色回到了拂晓蓝
