### ISSUE TITLE
🧐[问题]edietprotable中，columns使用了renderFormItem，配置了shouldUpdate但仍旧每个cell全部重新渲染

### ISSUE THREAD

**Issue by Wd3Curry30** [ant-design/pro-components#3994]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
可编辑表格中，当列数较多，数据量稍大，如3行10列，进行输入时明显卡顿
配置shouldCellUpdate，只能影响render
formItemProps写了shouldUpdate但似乎没起作用？

### 💻 示例代码
```
{
      title: '工作描述',
      dataIndex: 'task',
      key: 'task',
      width: '11%',
      shouldCellUpdate:(record, prev) => record.task !== prev.task,
      formItemProps: {
        shouldUpdate: (record, prev) => {return record.task !== prev.task},
        rules: [
          {
            required: true,
            message: '此项为必填项',
          },
          {
            max: 512,
            whitespace: true,
            message: '最长为512位，且不能全为空格/换行',
          },
        ],
      },
      renderFormItem: () => {return <ProFormTextArea />},
      render: (_, record) => <span className={styles.cell}>{record.task}</span>
    },
```

**Comment by chenshuai2144** [comment]
shouldUpdate 直接写成false 试试呢，理论上是不会更新的

**Comment by Wd3Curry30** [comment]
> shouldUpdate 直接写成false 试试呢，理论上是不会更新的

[复现demo](https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-test-render-formitem-ulvdq?file=/App.tsx)
用官网editprotable的例子写了个复现demo，增加了renderFormItem，render时有consolelog，已设置shouldUpdate: false
编辑某一个单元格时，会触发全部单元格render
麻烦有空再帮忙解答下，感谢~

**Comment by chenshuai2144** [comment]
我还以为是给 table 设置了，给  formItem 是没用的，因为renderFromItem的 formitem 每次都会被销毁

**Comment by Wd3Curry30** [comment]
> 我还以为是给 table 设置了，给 formItem 是没用的，因为renderFromItem的 formitem 每次都会被销毁

谢谢大神~那请问实时保存的可编辑表格（用来formItem），可以通过怎么设置，避免输入时卡顿？
我现在先改成“点击编辑”——进入“编辑状态”的方式规避了

**Comment by chenshuai2144** [comment]
这个你估计没有什么好办法， 需要靠我了，性能优化我会尽快想办法。

**Comment by Wd3Curry30** [comment]
> 这个你估计没有什么好办法， 需要靠我了，性能优化我会尽快想办法。

谢谢，静候佳音~

**Comment by ldwonday** [comment]
这个解决了吗？SchemaForm有大量的renderFormItem会导致输入框很卡

**Comment by chenshuai2144** [comment]
现在有新的方案了，升级到最新版本然后手动精细管理

**Comment by HowieChy** [comment]
> 

请问新的方案有例子吗，能具体说说吗？谢谢！

**Comment by xinyiPig** [comment]
@chenshuai2144 @afc163 @nikogu  在column中设置shouldCellUpdate以后还是会重新渲染，具体情况情况[demo](https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-test-render-formitem-forked-cwxjni?file=/App.tsx:2385-2401)，新方案是啥？能具体说说吗？

**Comment by xinyiPig** [comment]
@Wd3Curry30 是在table上设置shouldUpdate?
