### ISSUE TITLE
🧐[问题] 如何通过API设置ProTable的sorter参数？

### ISSUE THREAD

**Issue by zpaimon** [ant-design/pro-components#3995]
需要在toolbar上面添加一个按钮(快捷键)，点击按钮响应不同的搜索参数以及排序参数，目前通过formRef来设置查询条件，但是sort不知道如何通过API设置

**Comment by chenshuai2144** [comment]
https://ant.design/components/table-cn/#components-table-demo-reset-filter

看这里

**Comment by zpaimon** [comment]
Thanks
