### ISSUE TITLE
有提供离线文档吗？🧐[问题]

### ISSUE THREAD

**Issue by mabelyong** [ant-design/pro-components#3996]
### 🧐 问题描述

因为是内外开发，不能连互联网，所以需要离线文档！

已经尝试过本地拉取仓库代码，并安装了依赖，运行`npm run site`或者`npm start`启动不了，有其他方法吗？

**Comment by chenshuai2144** [comment]
你可以下载 https://github.com/ant-design/pro-components/tree/gh-pages

这个分支然后启动用serve 启动，是纯静态的
