### ISSUE TITLE
🧐[问题]ProTable嵌套表格，子Table的样式问题

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#3998]
![image](https://user-images.githubusercontent.com/12421552/141045224-32af37be-a1c2-4282-9097-845edb963637.png)
![image](https://user-images.githubusercontent.com/12421552/141045260-0d1280cf-c828-4710-963a-520f6d2e115e.png)

我想让 子Table中的item 占满整行，
但是给子Table添加 className 不起作用。
不清楚是我写的不对吗？

引入了card-body-expanded，但是我没有在页面里有搜到
![image](https://user-images.githubusercontent.com/12421552/141045535-96e946b2-d3cd-42a1-b55c-0ff89e40fe2c.png)

**Comment by chenshuai2144** [comment]
设置cardProps = false ，就可以不渲染这个card了
