### ISSUE TITLE
🧐[问题]vite集成@ant-design/pro-form

### ISSUE THREAD

**Issue by Dai-ldm** [ant-design/pro-components#3999]
我在vite中安装了@ant-design/pro-form的依赖并使用
开发环境：正常使用;
打包生产环境代码的时候：报错，错误信息如下
![141049152-ec776951-1185-43c7-9eb8-6d21ff3d3756](https://user-images.githubusercontent.com/53032797/141051210-44503962-1f0f-4c8f-b7dd-737cb20a4080.png)

请问这个是需要配置什么声明还是pro只能在umi下使用呢？
如果是声明等配置，这个得怎么处理呢？

**Comment by chenshuai2144** [comment]
是个bug，已经有记录了，但是挺不好修的就一直放到了现在
