### ISSUE TITLE
🐛[BUG]ProTable的bug

### ISSUE THREAD

**Issue by xiexingen** [ant-design/pro-components#40]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/7939085/88629482-e5cf2b80-d0e1-11ea-8010-c6ed85e859af.png)
如图，antd的本地化变成了英文，这个地方应该显示的是中文

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
配置一下 configProvide 

https://ant.design/components/config-provider-cn/
