### ISSUE TITLE
🧐[问题] 折叠的formItem用法

### ISSUE THREAD

**Issue by jiaicon** [ant-design/pro-components#4003]
### 🧐 问题描述
1. 怎样控制是否折叠。
2. 当关闭折叠面板时，提交数据获取不到折叠起来的数据。

### 💻 示例代码
demo地址：https://codesandbox.io/s/schema-biao-dan-forked-mdgog?file=/App.tsx

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/34124517/141066988-b4bf1613-0810-4c0c-a6d3-1188650e97e6.png)

**Comment by chenshuai2144** [comment]
组件被销毁了，这个用法没有经过测试。不是很好用
