### ISSUE TITLE
🐛[BUG]ProForm request请求两次

### ISSUE THREAD

**Issue by codedart2018** [ant-design/pro-components#4007]
### 🐛 bug 描述

使用ProForm request的时候发现进行了两次请求。

### 📷 复现步骤

```
    <ProForm request={async () => {
      console.log(1)
        return {}
      }}>
      
    </ProForm>
```

### 🏞 期望结果

只期望请求一次

### © 版本信息

- ProComponents 版本: [e.g. 1.46.0]
- umi 版本: [e.g. 3.5.18]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/12706830/141248211-0c910d57-2972-4767-b6a2-e2d81959f455.png)

![image](https://user-images.githubusercontent.com/12706830/141248236-b1d513eb-b1de-4087-95a9-8449c6517246.png)

**Comment by zhfish** [comment]
mark下，同样问题

**Comment by ldwonday** [comment]
确实有两次，我还以为我自己代码有问题

**Comment by yuntuzhuiyi** [comment]
我也有同样问题，马克下

**Comment by chuion** [comment]
依然没有解决

**Comment by codedart2018** [comment]
> 1.50.0 依然没有解决

之前提的1.46.0两次请求，我装到1.49.6没问题。1.50.0没有试
