### ISSUE TITLE
🧐[问题]EditableProTable能在中间添加行吗？后者自定义添加行的位置

### ISSUE THREAD

**Issue by mooncareer** [ant-design/pro-components#4012]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

我的需求：最后有两条总结行，每次添加行，总结行都是最后两行

**Comment by chenshuai2144** [comment]
不支持的，但是你可以自己实现以下。

table是根据dataSource 来渲染的，你可以动态的操作dataSource来设置新建的行插入在哪里
