### ISSUE TITLE
🧐[问题] ProFormSelect如何使用OptGroup进行选项分组

### ISSUE THREAD

**Issue by hanjeahwan** [ant-design/pro-components#4014]
### 🧐 问题描述

请问有什么办法能用ProFormSelect然后OptGroup进行选项分组

### 💻 示例代码

```
<Select defaultValue="lucy" style={{ width: 200 }} onChange={handleChange}>
    <OptGroup label="Manager">
      <Option value="jack">Jack</Option>
      <Option value="lucy">Lucy</Option>
    </OptGroup>
    <OptGroup label="Engineer">
      <Option value="Yiminghe">yiminghe</Option>
    </OptGroup>
 </Select>
```

```
<ProFormSelect
    name="select"
    label="Select"
    valueEnum={{
      open: '未解决',
      closed: '已解决',
    }}
    placeholder="Please select a country"
    rules={[{ required: true, message: 'Please select your country!' }]}
 />
```

**Comment by chenshuai2144** [comment]
用这个方法
```tsx
 request={async () => {
              return [
                { label: '全部', value: 'all' },
                { label: '未解决', value: 'open' },
                { label: '已解决', value: 'closed' },
                { label: '解决中', value: 'processing' },
                {
                  label: '特殊选项',
                  value: 'optGroup',
                  optionType: 'optGroup',
                  options: [
                    { label: '不解决', value: 'no' },
                    { label: '已废弃', value: 'clear' },
                  ],
                },
              ];
            }}
```

**Comment by XiaoXiaoWu98** [comment]
> 用这个方法
> 
> ```tsx
>  request={async () => {
>               return [
>                 { label: '全部', value: 'all' },
>                 { label: '未解决', value: 'open' },
>                 { label: '已解决', value: 'closed' },
>                 { label: '解决中', value: 'processing' },
>                 {
>                   label: '特殊选项',
>                   value: 'optGroup',
>                   optionType: 'optGroup',
>                   options: [
>                     { label: '不解决', value: 'no' },
>                     { label: '已废弃', value: 'clear' },
>                   ],
>                 },
>               ];
>             }}
> ```

Uploading 屏幕录制2024-04-16 10.27.12.mov…


我用Procomponents 里面的Schema Form，valueType: select, 使用request也没有生效，下拉会出现重复分组，使用options也会有同样的问题，请问有什么实现方式，还是只能用自定义的
