### ISSUE TITLE
🧐[问题]ProTable 配置添加(或修改)form表单问题

### ISSUE THREAD

**Issue by jlq023** [ant-design/pro-components#402]
### 🧐 问题描述

一：配置添加或修改form表单时，请问如何设置右下角的文字，或者我想把重置的功能，设置为取消（目前公司项目添加form弹出层，左面按钮是取消的功能，没有重置）
我试了optionRender配置项，无效。

二：目前添加（或修改）使用proTable，弹出层的modal，会根据高度动态变一次，体验很差，请问如何配置，能够避免弹出层高度被动态改变

### 💻 示例代码

问题一代码如下：
ProTable
          onSubmit={async value => {
            const success = await handleAdd(value);
            if (success) {
              handleModalVisible(false);
              if (actionRef.current) {
                actionRef.current.reload();
              }
            }
          }}
          rowKey="key"
          type="form"
          columns={columns}
          rowSelection={{}}
          optionRender={({ searchText, resetText }, { form }) => (
            <>
              <Button onClick={() => {
                form.resetFields();
              }}>取消1</Button>
              <Button style={{ marginLeft: "10px" }} type={"primary"} onClick={() => {
                form.submit();
              }}>提交2</Button>
              </>
             )}

问题二代码我稍作修改，第一次打开,提交和重置按钮，还是动态改变了位置，体验很不好.
<Modal
      // destroyOnClose
      title="新建规则1"
      visible={modalVisible}
      onCancel={() => onCancel()}
      footer={null}
    >
      <div style={{ minHeight: "300px" }}>
        {props.children}
      </div>
    </Modal>

**Comment by jlq023** [comment]
问题一的图片：
![guizi](https://user-images.githubusercontent.com/32348538/92346397-426d2f80-f0ff-11ea-92a8-7357bb014e3b.png)

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/table#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%8D%95%E9%A1%B9

看这个demo 是支持自定义的

**Comment by jlq023** [comment]
> https://procomponents.ant.design/components/table#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%8D%95%E9%A1%B9
> 
> 看这个demo 是支持自定义的

谢谢你，请问modal高度问题，有没有办法解决，或者思路？

**Comment by chenshuai2144** [comment]
@jlq023  给个 min-height 好了

**Comment by ChenWeihua123** [comment]
@jlq023 请问你是怎么自定义 ProTable modal 下的按钮的

**Comment by jlq023** [comment]
> @jlq023 请问你是怎么自定义 ProTable modal 下的按钮的

https://github.com/ant-design/pro-components/issues/402#issuecomment-713410627
看这个例子

**Comment by jlq023** [comment]
https://procomponents.ant.design/components/table#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%8D%95%E9%A1%B9
这是地址
