### ISSUE TITLE
🐛[BUG] 二级菜单无法点击

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#4026]
🐛[BUG] 二级菜单无法点击 "@ant-design/pro-layout": "^6.28.0" 版本

**Comment by leshalv** [comment]
@chenshuai2144

**Comment by Liu-Ya** [comment]
+1

**Comment by giscafer** [comment]
same issue in production .

锁定版本正常 ` "@ant-design/pro-layout": "6.15.3"`

**Comment by chenshuai2144** [comment]
已经修复了，各位更新一下版本。
插件中判断写错了

**Comment by giscafer** [comment]
分页组件遇到类似的情况，无法点击分页

**Comment by chenshuai2144** [comment]
分页组件无法点击和这个没关系，菜单无法点击时layout的问题。你排查一下一般哪里没写配置

**Comment by giscafer** [comment]
> 分页组件无法点击和这个没关系，菜单无法点击时layout的问题。你排查一下一般哪里没写配置

rc组件那边做了字符串判断，这个应该帮转一下的。没必要直接判断 integer

![wecom-temp-877f9953a93ab242e91e6c925e777ce0](https://user-images.githubusercontent.com/8676711/142015944-314740f1-6726-416d-ae13-6d45fc14f423.png)

因为后端用的框架分页是Long型到前端就string了，这个问题排查了好久，主要是想不到这个情况。也是突发的。之前一直可用

**Comment by chenshuai2144** [comment]
竟然还有这种奇怪的事情。不过一般我们不敢自动转，一不小心就白屏

**Comment by giscafer** [comment]
看到已转换修改，这才合理点。https://github.com/react-component/pagination/pull/357/files
