### ISSUE TITLE
🧐[问题]pro-layout v6.28.0导航样式

### ISSUE THREAD

**Issue by cloudsnet** [ant-design/pro-components#4029]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/17145414/141613231-81b261d7-aa71-42ea-ad1f-28980875358d.png)

更新到pro-layout v6.28.0 导航样式显示如上图，配置如下
layout: 'mix',
splitMenus: true,
怎么让他不让顶部下垂的效果，不跟随点击侧栏同步出现，是增加了什么参数？，现在点击一下侧栏导航，顶部就同步跟随显示对应的，头大，

还有一个问题就是头部一级导航点击无效了，只出现下拉选择二级导航....

**Comment by chenshuai2144** [comment]
fixed， 清空以依赖然后重新更新即可
