### ISSUE TITLE
🧐[问题] ProCard左右布局+ProTable开启scroll:x导致双滚动条问题

### ISSUE THREAD

**Issue by zhangheng0317** [ant-design/pro-components#4031]
### 🧐 问题描述

业务需求是这样的
左侧是一个树,右侧是table由于展示数据过多需要开启scroll横向滚动
但二者结合使用后,在最外层还会出现滚动条,table内容溢出屏幕
我通过调整style也没有得到很好的解决办法,除非写死table的width.
请问还有其他更好的解决办法吗?
![image](https://user-images.githubusercontent.com/76459860/141718867-1d0b1d45-6acc-447c-9b91-73a45a35689d.png)

### 💻 示例代码

![image](https://user-images.githubusercontent.com/76459860/141718902-2a9c08f7-1244-412c-a915-3fb128555c76.png)

**Comment by chenshuai2144** [comment]
写死table把 max-width也可以，然后用scroll:x来滚动内部，不然没什么特别好的办法。

**Comment by zhangheng0317** [comment]
3Q

**Comment by 1024wxx** [comment]
> 写死表把max-width也可以，然后用scroll:x来滚动内部，不太好办法。
写死table的width会导致点击侧边导航的触发器后，当侧边导航缩进时，table内容无法根据浏览器终端进行自适应，不能提高横向空间的使用率。希望能尽快修复“ProTable开启scroll:x导致双滚动条问题”，期待您的答复，非常感谢！

**Comment by 1024wxx** [comment]
![image](https://user-images.githubusercontent.com/61932817/178646414-8061a2d5-6620-48b4-add1-0c2c0990aac5.png)
这边通过自定义触发器onClick事件，分别在侧边导航展开和缩进时，修改右侧table内容的最大宽度设置，可以暂时规避触发“双滚动条问题"

**Comment by lixingjuan** [comment]
可以在数据更新完成之后，触发resize 事件
```js
const { data, loading, error } = useRequest(() => getCZBiddingTableData(params), {
    refreshDeps: [params],
    onSuccess: () => {
+      const myEvent = new Event('resize');
+      window.dispatchEvent(myEvent);
    },
  });
```
