### ISSUE TITLE
🐛[BUG]当valueEnum设置为map，且map的key为数组的时候，select显示不正确

### ISSUE THREAD

**Issue by ldwonday** [ant-design/pro-components#4032]
例子如下：
https://codesandbox.io/s/unruffled-mcnulty-zyiz0?file=/App.tsx

**Comment by ldwonday** [comment]
@andriijas

**Comment by chenshuai2144** [comment]
不支持key为数组的。你想实现什么需求？

**Comment by ldwonday** [comment]
@chenshuai2144 和demo里的一样，下拉框里的选项是预设好的区间，例如用户的粉丝可能几十万，搜索的时候，预设几个区间0-99，100-999等等，当选择0-99最终搜索的条件为：{fans: [0, 99]}

**Comment by chenshuai2144** [comment]
这个，我们还不支持这种用法。在submit的时候处理一下呢？
