### ISSUE TITLE
🧐[问题]proTable数据loading过程中怎么配置不显示空状态

### ISSUE THREAD

**Issue by aphen** [ant-design/pro-components#4035]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

pro-table中request数据过程当中，如果网络较慢，会同时出现loading与空状态，截图信息如下，
如何配置才能让loading过程中，不出现空状态，请求成功能后，根据数据结果来显示？

### 🚑 其他信息

![16369659122753](https://user-images.githubusercontent.com/8229846/141751065-89d8ddac-27d5-4942-b7dc-c57f9eccab97.jpg)

**Comment by chenshuai2144** [comment]
这看起来是电脑太卡了吧，dom切换没完成。


要更改在这里

https://ant.design/components/empty-cn/#components-empty-demo-config-provider

**Comment by aphen** [comment]
1.不是卡，在数据加载的过程中，如果网络慢，接口未返回结果时就会同时出现这两个（快的时候也会闪现），  官网只是改图标，loading过程中怎么隐藏“暂无数据的提示”？  
2.用ConfigProvider更改为自定义的，  但是antd-pro的这个还是会显示的，如何隐藏？
 @chenshuai2144

**Comment by chenshuai2144** [comment]
ConfigProvider 和 pro 的这个是相同的

**Comment by aphen** [comment]
![Inked2225](https://user-images.githubusercontent.com/8229846/142148750-bc8edac1-61a6-47a7-b789-ee08fff674d0.jpg)
去掉table不符合需求了，因为是表格数据的loading,   你看官网的表格，网速调慢之后也是出现重叠的两个，  我用的是pro-table, 是不是不能根据自定义条件隐藏掉”暂无数据（包含图标）“？
 或者是否有其它方式做到？
@chenshuai2144

**Comment by chenshuai2144** [comment]
现在没有这种功能，去antd 提一个吧
