### ISSUE TITLE
🧐[问题] DrawerForm的onVisibleChange里setFieldsValue没有成功

### ISSUE THREAD

**Issue by hanjeahwan** [ant-design/pro-components#4036]
### 🧐 问题描述
`@ant-design/pro-form`的版本`1.47.0`在`onVisibleChange`里`setFieldsValue`没有反应 可是在版本`1.46.0`可行. 在最新版本我试把
setFieldsValue放setTimeout里就可行. 想请教下这是对的写法吗?

### 🚑 其他信息
https://codesandbox.io/s/drawer-biao-dan-forked-e0ztx?file=/App.tsx

**Comment by chenshuai2144** [comment]
是正确的，但是行为上有点奇怪

**Comment by hanjeahwan** [comment]
> 是正确的，但是行为上有点奇怪

是指在onVisibleChange里做setFieldsValue吗? 我试搬去useEffect里做效果一样 如果你有更好的建议 谢谢指教 🧡

**Comment by chenshuai2144** [comment]
useEffect 里面可能比较合适一些。
他是这样的，打开的时候会重置form，你需要等form初始化成功才能设置。我想改一下，但是没什么特别好的办法。

**Comment by hanjeahwan** [comment]
> useEffect 里面可能比较合适一些。 他是这样的，打开的时候会重置form，你需要等form初始化成功才能设置。我想改一下，但是没什么特别好的办法。

明白 谢谢你 😉

**Comment by zhubufang** [comment]
我也遇到这个问题了  有的页面可以设置上 有的不行  是因为页面结构少的时候 form初始化快一点吗

**Comment by chenshuai2144** [comment]
应该用init values不要和用户赌他们的电脑快不快
