### ISSUE TITLE
🧐[问题] 滚动条样式如何自定义

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#404]
### 🧐 问题描述

![QQ浏览器截图20200907124118](https://user-images.githubusercontent.com/3166799/92349482-d1cb1080-f108-11ea-815e-8bfa2cc94e54.png)

**Comment by chenshuai2144** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Scrollbars
还在实验中，只支持 chrome 系列

**Comment by hihuangwei** [comment]
> https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Scrollbars
> 还在实验中，只支持 chrome 系列

要在哪里修改

**Comment by wlxkzyq** [comment]
@hihuangwei 
通过调整以下css可以达到修改滚动条样式的效果.
![image](https://user-images.githubusercontent.com/17799945/101589294-20978780-3a23-11eb-8cb7-503a65959e1b.png)
