### ISSUE TITLE
🧐[问题] protable内valuetype为'digit'时，小数点超过3位，会被转换，不是原有值

### ISSUE THREAD

**Issue by wangxin305** [ant-design/pro-components#4040]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 💻 示例代码
https://nkfyy.csb.app/

![image](https://user-images.githubusercontent.com/39551146/141901318-f675afea-f04f-474c-a769-2c093c15ccfa.png)

**Comment by chenshuai2144** [comment]
`new Intl.NumberFormat(undefined, {}).format(0.00384);`

这个东西精度有点低，我找找为啥

**Comment by chenshuai2144** [comment]
找到了 `new Intl.NumberFormat('zh-Hans-CN', {minimumSignificantDigits:1}).format(0.00384)`
