### ISSUE TITLE
🐛[BUG]editableProTable自定义组件 编辑保存后值无法保存

### ISSUE THREAD

**Issue by coulis1018** [ant-design/pro-components#4048]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

`EditableProTable` 作为 `ProForm` 的一个表单项，使用自定义组件其值无法保存，预置类型表单组件的值可以正常保存。

### 📷 复现步骤

`EditableProTable` 作为 `ProForm` 的一个表单项，为其设置 `name` 参数（例如：`"table"`）。`EditableProTable` 的 `columns` 中分别添加默认类型和自定义组件的配置。

编辑完行数据后，点击保存，自定义组件 cell 编辑值丢失。

经过调试发现，自定义组件在 `form` 中注册的 `name` 不正确，缺少 `EditableProTable` 的 `name`。（详见 react devtools 截图）

### 🏞 期望结果

自定义组件 cell 值正确显示。

### 💻 复现代码

[codesandbox](https://codesandbox.io/s/ke-bian-ji-biao-ge-forked-h7jsj?file=/App.tsx)

### © 版本信息

- ProComponents 版本:
  - ProForm 1.47.0
  - ProTable 2.56.9

#### 编辑状态

<img width="1511" alt="lALPJxuMOhm46FDNBf7NC84_3022_1534" src="https://user-images.githubusercontent.com/54612727/141983280-b1b9fe9b-21db-4689-86a5-af6e209f1acd.png">

#### 自定义组件（缺失 `"table"`）

<img width="1306" alt="lALPJx8ZuL6BFoHNBzLNCjQ_2612_1842" src="https://user-images.githubusercontent.com/54612727/141983677-4036c0a3-2a15-4833-a64e-0bc51c40cfd0.png">

#### 预置组件（正确）

<img width="1306" alt="lALPJxf-u3T4ZXnNBzLNCjQ_2612_1842" src="https://user-images.githubusercontent.com/54612727/141983755-fbb63473-343c-432b-93c6-b29c74425dd9.png">

**Comment by chenshuai2144** [comment]
来个重现吧。

**Comment by coulis1018** [comment]
> 来个重现吧。

https://codesandbox.io/embed/ke-bian-ji-biao-ge-forked-h7jsj?file=/App.tsx&codemirror=1

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


看起来问题是在 `CustomTag` 组件上，因为在编辑行数据时，`CustomTag` 组件中的值丢失了，并且导致我们不能正确地保存数据。

通过在带有 `value` 的 `input` 中使用 `onChange`，可以解决掉 `CustomTag` 组件中的问题。例如：

```tsx
const CustomTag: React.FC<TagProps> = ({ value = '', onChange }) => {
  const [inputValue, setInputValue] = useState<string>(value);

  return (
    <div onClick={(e) => e.stopPropagation()}>
      <Input
        onPressEnter={(e) => {
          e.preventDefault();
          setInputValue(e.currentTarget.value);
          onChange(e.currentTarget.value); // 保存更改
        }}
        onBlur={(e) => {
          setInputValue(e.currentTarget.value);
          onChange(e.currentTarget.value); // 保存更改
        }}
        defaultValue={inputValue}
      />
    </div>
  );
};
```

像上述例子中一样的 `onChange` 方法确保我们将更改保存在 `EditableProTable` 表单项中。
