### ISSUE TITLE
🐛[BUG]ProTable 分页点击无效果。

### ISSUE THREAD

**Issue by peter-liluping** [ant-design/pro-components#4049]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

今天部署发现之前能正常使用的ProTable分页，发布后分页点击无效果，点击分页后并没有触发：onChange 、 onShowSizeChange 事件，第一次加载能够正常触发，修改pageSize也能正常触发。
![image](https://user-images.githubusercontent.com/29751025/141988408-b9aeb9ae-3aef-4bf7-a4e2-bcd9d4c3a242.png)

通过升级、指定版本修改： antd \ pro-table 也不行。

### 💻 复现代码

const queryRule = async (params?: TableListParams) => {
      var param;
      if (params) {
        param = {
          pageSize: params.pageSize,
          pageNo: params.current
        }

      const res = await queryItem(param);
      if (res) {
        return {
          data: res.result,
          total: res.totalCount,
          success: true
        }
      } else {
        return null
      }
  }

<ProTable<TableListItem>
        headerTitle="报表)"
        actionRef={actionRef}
        rowKey="key"
        request={(params, sorter, filter) => queryRule({ ...params, sorter, filter })}
        columns={columns}
/>

### © 版本信息

- pro-table: 2.57.0
- antd: 4.16.13

**Comment by peter-liluping** [comment]
找到问题了，查询数据返回的total是字符串导致分页点击无效。

**Comment by Jibinghao** [comment]
> 找到问题了，查询数据返回的total是字符串导致分页点击无效。

牛逼，确实就是这个问题
