### ISSUE TITLE
🐛[BUG] Protable ellipsis 为 true ，导致render的value 是一个对象。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-components#4052]
### 🐛 bug 描述

Protable ellipsis 为 true ，导致render的value 是一个对象。

### 📷 复现步骤
打开我的提供的codesanbox 地址，提供了两个table,一个是protable,一个是antd table， 可以看到第一个 hasChild的render conslog是一个对象，第二个是真实的值，但是把ellipsis去掉之后，都一样，所以应该是protable ellipsis封装了，导致把value 指覆盖了

### 🏞 期望结果

不应该覆盖原本的value值，这样对用户来说框架已经参与业务了。

### 💻 复现代码

https://codesandbox.io/s/protable-ellpsis-fu-gai-renderwen-ti-646p5

### © 版本信息

- ProComponents 版本:  protable:2.57.1
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
 
![image](https://user-images.githubusercontent.com/8272614/142116251-e1ab8727-ded0-454e-9b21-6de888df2cd2.png)

**Comment by chenshuai2144** [comment]
render的 第一个是dom，和antd的table 是不同的。

你可以用renderText 来处理字符串修改的问题。或者直接用 render(dom,row)=>row.dataIndex

**Comment by xgj1988** [comment]
这个做法有问题吧，我记得以前都是好好的撒。。我们自己写的代码生成器突然就不能用了。我们现在 是后端返回一个url 地址，前端用render 来渲染下载，原本这个attachment是一个url 地址，那现在是不是就搞不定这个需求了？
不可能让我写成 uiUtils.renderDownload(record.attachment)。感觉框架的设计，已经驾驭在业务本身上面了。不纯了。 
```
  {
      title: '附件',
      key: 'attachment',
      dataIndex: 'attachment',
      search: false,
      ellipsis: true,
      render: (value) => uiUtils.renderDownload(value)
    },
```

**Comment by xgj1988** [comment]
关键是以前都是好的。。现在已升级就不能用了。。最起码要向下兼容一下吧。

**Comment by chenshuai2144** [comment]
从第一个版本开始一直都是这样的，都是dom。

**Comment by chenshuai2144** [comment]
一直都是这样的，都是dom，你肯定的

**Comment by xgj1988** [comment]
额。。可能是加了ellipsis的原因。没加ellipsis就不是dom 了。

**Comment by mumu0125** [comment]
![image](https://github.com/user-attachments/assets/eccd4d70-1706-44e1-9316-15c6baac72a8)
上面是源码截图，我也遇到同样的问题，ellipsis为true时，第一个值就是dom，为false时就是text，变来变去的，我用的版本很新了，
![image](https://github.com/user-attachments/assets/7b80f72a-ccf2-42a9-9a86-abcb03172ccc)
这样写的话，如果值为空字符串，默认'_'的功能就失效了，为什么加了属性值，render接受的参数类型会变，很不理解啊
