### ISSUE TITLE
🧐[问题] ProTable怎么直接传入columns

### ISSUE THREAD

**Issue by oneluxyou** [ant-design/pro-components#4053]
### 🧐 问题描述
由于定义的表头比较长，title字段还希望能够实时变动。
想知道columns怎样才能像data一样通过request去后端实时的取数据

### 💻 示例代码

    <ProTable
      scroll={{ x: 1000, y: 400 }}
      request={async () => get_zhouzhuan_data()}
      columns = {column1}
    />

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/77523920/142114701-e578da58-5875-459a-979b-6a716cda4bdd.png)

**Comment by chenshuai2144** [comment]
要自己写了哦，官方没有自带的这个功能的

**Comment by oneluxyou** [comment]
> 要自己写了哦，官方没有自带的这个功能的
> 
> 用 useRequest 然后1s刷新一次好了
![企业微信截图_1637123410750](https://user-images.githubusercontent.com/77523920/142163974-51ace11d-4b4a-4c11-944d-1218f07f9cd7.png)
![企业微信截图_16371234214247](https://user-images.githubusercontent.com/77523920/142163988-9481685c-7617-4414-aa3a-2bd3e49d7585.png)
![企业微信截图_16371234595721](https://user-images.githubusercontent.com/77523920/142164012-97c2a3b1-bfdf-4e61-8895-d012ab175603.png)
大佬顺便再帮忙看下，我这样好像有问题，但是我不知道该怎么去修正
