### ISSUE TITLE
👑 [需求] pro-layout支持传入props到SubMenu

### ISSUE THREAD

**Issue by feibi** [ant-design/pro-components#4057]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述

Menu.SubMenu需要设置popupOffset来自定义间距，目前只能自定义title
```tsx
const MenuComponents: React.ElementType = menu?.type === 'group' ? ItemGroup : SubMenu;
return (
  <MenuComponents title={title} key={item.key || item.path} onTitleClick={item.onTitleClick}>
    {this.getNavMenuItems(item.routes, true)}
  </MenuComponents>
```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，对于您的需求，可以通过自定义SubMenu组件来实现传入popupOffset的功能。具体可以按如下步骤操作：

1. 创建自定义SubMenu组件，例如在components目录下创建CustomSubMenu.tsx：

```tsx
import { Menu } from 'antd';
import React from 'react';

interface CustomSubMenuProps {
  popupOffset?: [number, number];
  title: string | React.ReactNode;
  key: string;
  onTitleClick?: (e: React.MouseEvent<HTMLDivElement>) => void;
}

class CustomSubMenu extends React.Component<CustomSubMenuProps> {
  render() {
    return <Menu.SubMenu popupOffset={this.props.popupOffset} {...this.props} />;
  }
}

export default CustomSubMenu;
```

其中，CustomSubMenu继承自React.Component，props包含popupOffset、title、key、onTitleClick等属性，同时也继承了Menu.SubMenu的其他属性。在render函数中，直接通过<Menu.SubMenu>来渲染SubMenu组件，同时将父组件传递进来的props传入。

2. 在使用Menu时，将SubMenu替换成自定义的CustomSubMenu即可：

```tsx
import CustomSubMenu from './components/CustomSubMenu';

//...

<Menu mode="inline">
  <CustomSubMenu title="SubMenu 1" popupOffset={[10, 10]}>
    <Menu.Item key="sub1-1">Sub 1-1</Menu.Item>
    <Menu.Item key="sub1-2">Sub 1-2</Menu.Item>
  </CustomSubMenu>
</Menu>
```

其中，使用CustomSubMenu替换SubMenu，并将popupOffset传入CustomSubMenu组件即可实现自定义间距的效果。

值得注意的是，Ant Design中SubMenu组件确实没有提供直接传入popupOffset的属性，但是通过自定义组件，我们可以继承SubMenu组件的其他属性同时增加popupOffset属性，以实现自定义的目的。
