### ISSUE TITLE
🐛[BUG] ProFormFields级联选择的demo有问题.

### ISSUE THREAD

**Issue by ldwonday** [ant-design/pro-components#4064]
文档有错，配置的是ProFormSwitch。
配置成ProFormCascader，级联选择器的下拉框没有选项出来
```tsx
<ProFormCascader
  name="area"
  label="区域"
  options={[
    {
      value: "zhejiang",
      label: "Zhejiang",
      children: [
        {
          value: "hangzhou",
          label: "Hangzhou",
          children: [
            {
              value: "xihu",
              label: "West Lake"
            }
          ]
        }
      ]
    }
  ]}
/>
```
https://codesandbox.io/s/shang-chuan-biao-dan-forked-zz283?file=/App.tsx

**Comment by chenshuai2144** [comment]
直接来个pr吧，成为名望程序员第一步

**Comment by johnwayen** [comment]
文档还不更新下吗 这么明显的错误

**Comment by songhaipeng** [comment]
options需要使用fieldProps来实现，如果还是不行，就需要把pro-form升级到1.47.0才可以。
 <ProForm>
      <ProFormCascader
        name="area"
        label="区域"
        fieldProps={{
          options:options,
        }}
      />
    </ProForm>

**Comment by chenshuai2144** [comment]
有好心人帮我们更新了
