### ISSUE TITLE
🧐[问题]ProForm表单里如何保留各输入框的历史记录

### ISSUE THREAD

**Issue by oneluxyou** [ant-design/pro-components#4065]
### 🧐 问题描述
ProForm表单里如何保留各输入框的历史记录

### 🚑 其他信息
![企业微信截图_1637140632807](https://user-images.githubusercontent.com/77523920/142172748-a9cc7b4c-155c-4202-be83-566f4b228d54.png)
像这样就没有保留历史的输入记录

**Comment by chenshuai2144** [comment]
存到 url 或者存到 localStorage，然后用 initialvalues 在设置回来。
操作起来还是很简单的
