### ISSUE TITLE
🐛[BUG]Protable column列表项配置copyable后 信息的显示和复制 在hover时会重叠 

### ISSUE THREAD

**Issue by CiciIvory** [ant-design/pro-components#407]
### 🏞 期望结果
复制的情况多为复制单号，一般只会有一行，数字有部分会被遮挡住
希望可以出一个方案

显示如下

![image](https://user-images.githubusercontent.com/40973214/91834189-48d05700-ec7a-11ea-97ee-0cd0051b07e4.png)

**Comment by chenshuai2144** [comment]
升级一下 antd，我们关掉了 copy 的 tooltip

**Comment by CiciIvory** [comment]
![image](https://user-images.githubusercontent.com/40973214/92452061-24cbc300-f1f0-11ea-92f4-8cf03464ffeb.png)
这个问题还是存在的呀 Protable官网的例子还是有这个bug的

**Comment by CiciIvory** [comment]
> 升级一下 antd，我们关掉了 copy 的 tooltip



> ![image](https://user-images.githubusercontent.com/40973214/92452061-24cbc300-f1f0-11ea-92f4-8cf03464ffeb.png)
> 这个问题还是存在的呀 Protable官网的例子还是有这个bug的
