### ISSUE TITLE
🐛[BUG] pro-table， pro-form的问题

### ISSUE THREAD

**Issue by GamesSoul** [ant-design/pro-components#4071]
### 🐛 bug 描述

1、protable 给配置了 valueType: 'money'  fieldProps: { moneySymbol: false } 无法取出rmb符号
2、proform ProFormDigit给配置小数精度为4时 只读模式下 依旧是保留三位小数
3、proform ProFormDependency 的 name 无法配置多项三个层级监听 多项监听只能取到最后一个监听设置的值

### 📷 复现步骤
codesandbox 我这边网络无法登陆 只能以截图形式展示

### 💻 复现代码
![图片](https://user-images.githubusercontent.com/37973776/142363072-11d9e629-be43-43f6-abee-8ca2ee32044b.png)
![图片](https://user-images.githubusercontent.com/37973776/142364595-cdffa467-b85f-4690-aff7-8b0ddbd05fe2.png)

### © 版本信息

    "@ant-design/pro-form": "^1.49.0",
    "@ant-design/pro-table": "^2.57.2",

**Comment by GamesSoul** [comment]
ProField的 valueType="money" fieldProps={{ moneySymbol: false }}  也有过滤不掉rmb符号的问题 应该跟protable的valueType用的是一个控件吧。 (ps：网络不行, 传截图传不上去)

**Comment by chenshuai2144** [comment]
fixed in https://github.com/ant-design/pro-components/commit/398415cd79318d6e56340d0a60f5d5bea40c0684
