### ISSUE TITLE
表格设置icon[问题]

### ISSUE THREAD

**Issue by azcdazq** [ant-design/pro-components#4073]
一直找不到设置此icon的配置

### 🧐 问题描述

![image](https://user-images.githubusercontent.com/90182205/142373377-1381934c-4f67-49c9-bba6-17f516d27209.png)

**Comment by chenshuai2144** [comment]
这个不支持设置的，拉手都是同样一个

**Comment by azcdazq** [comment]
关键是默认的没展示出来，我用的最新版本，是版本的原因吗

**Comment by azcdazq** [comment]
> 这个不支持设置的，拉手都是同样一个icon。暂时也不会支持定制的

关键是默认的没展示出来，我用的最新版本，是版本的原因吗

**Comment by azcdazq** [comment]
![image](https://user-images.githubusercontent.com/90182205/142390843-3aee59d2-f411-45c6-82a5-0ea59adb9ad6.png)
