### ISSUE TITLE
🧐[问题]EditableProTable 中使用Switch，点击【编辑】，该列会变回默认值。

### ISSUE THREAD

**Issue by kgloveyou** [ant-design/pro-components#4076]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

EditableProTable 中使用Switch，对已有行，点击【编辑】，switch列会变回默认值。

### 💻 示例代码

示例代码，参见：https://codesandbox.io/s/ke-bian-ji-biao-ge-forked-4yvkg

**Comment by kiner-tang** [comment]
为什么要指定
```tsx
formItemProps: {
  valuePropName: "checked",
  initialValue: true
},
```
去掉就可以了
https://codesandbox.io/s/ke-bian-ji-biao-ge-forked-k8irh3
