### ISSUE TITLE
draggable-icon🧐[问题]

### ISSUE THREAD

**Issue by azcdazq** [ant-design/pro-components#4078]
![image](https://user-images.githubusercontent.com/90182205/142551113-97fe24b4-0b5f-43fb-a91a-3759e4796539.png)
如图，官网默认的动态列是有这个icon的，无需配置（之前官网明明没有这个icon）
最近我升级了版本，但是怎么弄自己这边都没有icon，不知道是版本的原因，还是我需要额外配置option
![image](https://user-images.githubusercontent.com/90182205/142551280-530c3fa8-aa67-498b-927f-d311d8d499b8.png)
目前我的版本是/pro-table:^2.57.2

**Comment by chenshuai2144** [comment]
更新一下依赖就好了
