### ISSUE TITLE
🐛[BUG] EditableTable 新增一行时编辑行数据时会一直新增行

### ISSUE THREAD

**Issue by 1247748612** [ant-design/pro-components#4079]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

bug情况：

https://user-images.githubusercontent.com/29533304/142556800-f28c4674-7069-4424-a7ce-40653d779962.mp4

使用如下：

![code](https://user-images.githubusercontent.com/29533304/142557039-6f34613a-1bb4-4a86-bccc-43a2d9b59d55.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
修掉了，更新一下依赖

**Comment by 1247748612** [comment]
> 修掉了，更新一下依赖

可以了

看了下源码，行保存onSave事件不能根据返回值为false而取消事件继续执行，目前需要依赖保存被执行后调用后端方法确定数据是否合法

**Comment by chenshuai2144** [comment]
@1247748612  应该用rule 保证数据合法不合法
