### ISSUE TITLE
🐛[BUG] @ant-design/pro-form@1.49.0 部分bug

### ISSUE THREAD

**Issue by explorefit** [ant-design/pro-components#4080]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
使用  @ant-design/pro-form@1.49.0 中的组件 ProFormSelect  的request的方式请求数据，数据不显示

### 📷 复现步骤

<ProFormSelect
    name="select2"
    label="Select"
    request={async () => [
      { label: '全部', value: 'all' },
      { label: '未解决', value: 'open' },
      { label: '已解决', value: 'closed' },
      { label: '解决中', value: 'processing' },
    ]}
    placeholder="Please select a country"
    rules={[{ required: true, message: 'Please select your country!' }]}
  />
这个是官网的例子，但是不显示，
### 🏞 期望结果

图我是恢复到 1.39.0 版本的结果，
![image](https://user-images.githubusercontent.com/24665389/142570083-9bcbc19a-3471-4292-aac0-8ce8ffaa834f.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lzbabd** [comment]
怀疑和 #4106 是一个问题
