### ISSUE TITLE
🐛[BUG]有子列的EditableProTable在子列没有展开时编辑的问题

### ISSUE THREAD

**Issue by Liu-GITD** [ant-design/pro-components#4086]
### 🐛 bug 描述

使用EditableProTable，在子列没有展开时去编辑某一行的内容，onValuesChange回调的dataSource会在原有默认的dataSource的基础上加上几行内容

### 💻 复现代码

import React, { useState, useCallback } from 'react'
import CustomTags from '@/components/CustomTags'
import { PageContainer } from '@ant-design/pro-layout'
import Remark from '@/components/RemarkMarkdown'
import type { ProColumns } from '@ant-design/pro-table'
import { EditableProTable } from '@ant-design/pro-table'
import { Card, Form, Input, Row, Col, Select, Button } from 'antd'
import { pageJump } from '@/utils/list'

import { PROJECTS } from '@/constant/model'
import { flattenDeep } from 'lodash'

const mockData = {
  fields: [
    {
      name: '字段名1',
      required: 1,
      digits: 2,
      minValue: '1',
      maxValue: '100',
      expression: 'expression',
      defaultValue: 'defaultValue'
    },
    {
      name: '字段名2',
      required: 1,
      digits: 2,
      minValue: '1',
      maxValue: '100',
      expression: 'expression',
      defaultValue: 'defaultValue'
    },
    {
      name: '字段名3',
      required: 1,
      digits: 2,
      minValue: '1',
      maxValue: '100',
      expression: 'expression',
      defaultValue: 'defaultValue',
      subFields: [
        {
          name: '子字段名1',
          required: 1,
          digits: 2,
          minValue: '1',
          maxValue: '100',
          expression: 'expression',
          defaultValue: 'defaultValue',
          subFields: [
            {
              name: '子zi字段名1',
              required: 1,
              digits: 2,
              minValue: '1',
              maxValue: '100',
              expression: 'expression',
              defaultValue: 'defaultValue'
            },
          ],
        },
      ],
    },
  ]
}

type DataSourceType = {
  id?: React.Key
  name?: string
  required?: number
  digits?: number
  minValue?: string
  maxValue?: string
  expression?: string
  defaultValue?: string
  children?: DataSourceType[]
  subFields?: DataSourceType[]
}

const loopChildData = (data:DataSourceType[]):DataSourceType[] => {
  return data?.map((item)=>{
    const { name, required, digits, minValue, maxValue, expression, defaultValue, subFields } = item
    const all = {
      name,
      required,
      digits,
      minValue,
      maxValue,
      expression,
      defaultValue,
      id: (Math.random() * 1000000).toFixed(0).toString(),
    }
    if(subFields){
      const newChild = loopChildData(subFields as DataSourceType[])
      return {
        ...all,
        children:newChild,
      }
    }
    return all
  })
}

const loopRowKeys= (dataSource:DataSourceType[]):string[] => {
  const data = dataSource.map(item=>{
    let tmp = [item.id]

    if(item.children){
      const newArr = loopRowKeys(item.children)
      tmp = tmp.concat(newArr)
    }
    return tmp
  })
  return flattenDeep(data) as string[]
}

const defaultData: DataSourceType[] = mockData.fields.map((item) => {
  const { name, required, digits, minValue, maxValue, expression, defaultValue,subFields } = item
  return {
    id: (Math.random() * 1000000).toFixed(0).toString(),
    name,
    required,
    digits,
    minValue,
    maxValue,
    expression,
    defaultValue,
    children: loopChildData(subFields as DataSourceType[]),
  }
})

const Home: React.FC = () => {
  const [form] = Form.useForm()
  const { Option } = Select
  const [editableKeys, setEditableRowKeys] = useState<React.Key[]>(() =>
    loopRowKeys(defaultData),
  )
  const [dataSource, setDataSource] = useState<DataSourceType[]>(() => defaultData)
  const defaultLength = defaultData.length
  console.log('dataSource',dataSource)
  const columns: ProColumns<DataSourceType>[] = [
    {
      title: '字段',
      dataIndex: 'name',
    },
    {
      title: '必填',
      dataIndex: 'required',
      valueType: 'radioButton',
      valueEnum: {
        1: {
          text: '否'
        },
        0: {
          text: '是'
        }
      }
    },
    {
      title: '小数位',
      dataIndex: 'digits',
    },
    {
      title: '最小值',
      dataIndex: 'minValue',
    },
    {
      title: '最大值',
      dataIndex: 'maxValue',
    },
    {
      title: '表达式',
      dataIndex: 'expression'
    },
    {
      title: '默认值',
      dataIndex: 'defaultValue'
    },

  ]
  const handleCancle = useCallback(() => {
    pageJump('list')
  }, [])
  const handleSumit = useCallback(() => {
    form
      .validateFields()
      .then(() => {
        // eslint-disable-next-line no-console
        console.log('form values', form.getFieldsValue())
        console.log('dataSource', dataSource)
      })
      .catch(() => {
        // eslint-disable-next-line no-console
        console.log('error', form.getFieldsValue())
      })
  }, [form, dataSource])

  const onChangeValue = (value) => {

    console.log(value)
    setDataSource(value)

  }
  return <PageContainer footer={
    [
      <Button key="cancle" onClick={handleCancle}>
        取消
      </Button>,
      <Button key="submit" type="primary" onClick={handleSumit}>
        提交
      </Button>,
    ]
  }>
    <Form form={form}>
      <>
        <EditableProTable

          headerTitle=""
          columns={columns}
          rowKey="id"
          value={dataSource}
          onChange={onChangeValue}
          recordCreatorProps={false}
          editable={{
            type: 'multiple',
            editableKeys,

            onValuesChange: (record, recordList) => {
              onChangeValue(recordList)
            },
            onChange: setEditableRowKeys,
          }}
        />
      </>
    </Form>
  </PageContainer>
}

export default Home

### © 版本信息

-     "@ant-design/pro-card": "^1.18.2",
    "@ant-design/pro-layout": "^6.26.6",
    "@ant-design/pro-table": "^2.57.2",
- umi 版本
- 浏览器环境 chrome
- 开发环境 [mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/39366031/142713078-f62fc074-62e1-45ed-ae76-e80fbd42332b.png)

**Comment by kchjxxgh** [comment]
遇到同样的问题，但想新建个最小化的项目，又重现不了了。
