### ISSUE TITLE
👑 [需求]CheckCard组件的样式是否支持自定义？

### ISSUE THREAD

**Issue by YC725968** [ant-design/pro-components#4089]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述
CheckCard组件的样式是否支持自定义？

**Comment by chenshuai2144** [comment]
详细描述一下

**Comment by YC725968** [comment]
比如 如何修改整个card的背景颜色，点击选中时如何获取选中行的数据呀



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月23日(星期二) 上午10:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/pro-components] 👑 [需求]CheckCard组件的样式是否支持自定义？ (Issue #4089)





 
详细描述一下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenshuai2144** [comment]
选中的颜色不允许改的。选取的数据可以用 rowSelection 的里面拿
