### ISSUE TITLE
🐛[BUG] protable自定义表单项的onChange事件为空

### ISSUE THREAD

**Issue by chenchi2038** [ant-design/pro-components#409]
### 🐛 bug 描述

在column定义中通过`renderFormItem`来自定义表单项时，onChange时间为空，

```
    {
      title: '商户',
      dataIndex: 'merchantId',
      hideInTable: true,
      renderFormItem: (_, { type, defaultRender, ...rest }, form) => {
        console.log('rest', rest);
        return <Input {...rest} />;
      },
    },
```
上面代码中的rest没有值
### 💻 复现代码

https://codesandbox.io/s/great-bogdan-p0ywc?file=/index.tsx
查看控制台打印的config信息，里面没有onChange字段

### © 版本信息

- ProComponents 版本: 2.5.9
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

从2.5.9版本开始出现这个bug

**Comment by chenchi2038** [comment]
2.7.1版本并没有解决问题
@chenshuai2144

**Comment by itsuki0927** [comment]
@chenchi2038 表面上没有`value`和`onChange`,  但是实际上已经注入进去了, 因为调用`renderFormItem`函数的地方在注入之前,所以就没得这两个`props`, 如果是之前的版本自定义`renderFormItem`在`onSubmit`回调中是获取不到相对应字段值的, 但是已经修复了, 所以在`onSubmit`中是有对应字段值的,你可以自己在`onSubmit`中试试.

至于你说的这个问题, 其实我个人感觉不太好解决, 但是实际上已经给你自动注入进去了, 这样子像是给使用者在`renderFormItem`省略了手动注入`value`和`onChange`的操作,就不需要在写`<Input  value={values} onChange={onChange}/>`这样子的代码了,直接`<Input/>`就可以了, 可能是最新文档对这方面没有进行相对应的更新.

**Comment by chenchi2038** [comment]
我验证了下，确实自动注入了`value`和`onChange`，谢谢！

**Comment by tyGavinZJU** [comment]
请问一下，如何在保证form正常绑定数据的情况下，在onChange中添加新的逻辑？

**Comment by chenshuai2144** [comment]
@tyGavinZJU 使用 form的 onValueChange
