### ISSUE TITLE
🧐[问题]Protable如何重置选择的行状态？

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#4090]
Protable里面 选择了一些行，进行操作。
操作完成后，如何在代码里重置选择状态？

![image](https://user-images.githubusercontent.com/5349879/142805124-8b468cd5-f742-4ca4-945b-d01da8639869.png)

**Comment by chenshuai2144** [comment]
selectedKeys 可以受控的取消

**Comment by gaohongwei** [comment]
@chenshuai2144 陈帅, 请问你是说在代码里取消吗？能不能给个小例子？
 我知道界面可以清空。
