### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by oneMoreTime1357** [ant-design/pro-components#4092]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
使用LightFilter组件，添加日期选择器，设置选择month，筛选出正确的月份，但展示确实日期年月日，而不是年-月

### 📷 复现步骤

![截屏2021-11-22 下午2 29 09](https://user-images.githubusercontent.com/14797594/142813637-5ca29775-4c16-4167-a134-6a1c37acec85.png)

https://codesandbox.io/s/qing-liang-shai-xuan-forked-gc7pi?file=/App.tsx

### 🏞 期望结果
期望和组件设置的展示一致

### 💻 复现代码

```react
<ProFormDateRangePicker
          name="date"
          label="日期范围"
          fieldProps={{
            picker: "month",
            format: "YYYY-MM"
          }}
     />
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by mjkohoh** [comment]
我遇到了相同的问题
