### ISSUE TITLE
🧐[问题] ProFormSelect 中使用搜索，是不支持对label的搜索对吗

### ISSUE THREAD

**Issue by ximendatie** [ant-design/pro-components#4094]
### 🧐 问题描述

尝试了ProFormSelect 中的搜索功能，但是目前看只能对options的value进行搜索，想通过filterOption对label或者children搜索是做不到的，不知道我操作方法问题还是组件问题。

改成了ProForm.Item包裹Select的形式就解决了这个问题，我理解是ProFormSelect 本身功能还不够完善？

**Comment by chenshuai2144** [comment]
记得用 fieldProps
