### ISSUE TITLE
🐛[BUG]官网首页CSS挂了

### ISSUE THREAD

**Issue by topwood** [ant-design/pro-components#4099]
### 🐛 bug 描述
首页CSS挂了

### 📷 复现步骤
打开 https://procomponents.ant.design/

### 🏞 期望结果

页面正常

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/13791267/142978426-822c2227-15fa-4cbe-b1a6-690fecf1ad04.png)

procomponents.ant.design/:14 GET https://procomponents.ant.design/umi.f04d009b.css net::ERR_ABORTED 404

**Comment by chenshuai2144** [comment]
看来来恢复了，像是github 抽了一下

**Comment by DerrickTel** [comment]
可以close了
