### ISSUE TITLE
ProTable组件，默认收起状态如何展示两行搜索条件 🧐[问题]

### ISSUE THREAD

**Issue by MeiJunNa** [ant-design/pro-components#4100]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

目前protable组件，搜索栏收起状态下，只展示一行搜索框。但是我的需求是，默认收起状态下，能够展示两行搜索框，方便用户查看。

**Comment by chenshuai2144** [comment]
现在还不支持的，有兴趣可以来个pr。
