### ISSUE TITLE
🧐[问题]EditableProTable的onSave方法，发送请求得到失败结果时，希望能保持当前行编辑

### ISSUE THREAD

**Issue by haungxinyan** [ant-design/pro-components#4101]
### 🧐 问题描述
点击新增一行数据，填写数据后，点击保存按钮，进入onSave()方法，发送新增请求，得到新增失败请求（编号重复等错误），如何终止接下来的setEditableRowKeys([]),或者如何在save结束后再次进入编辑状态

### 💻 示例代码
editable={{
          form:formEditable,
          editableKeys,
          onChange: setEditableRowKeys,
          onSave: (key, record) => {
            if (record.id == 'new') {
              return handleAdd({record})
            }

通过抛出错误终止了后续的关闭编辑
const handleAdd = async (fields) => {
    const result = await addNode(fields);
    if (result.code == '1') {
      message.success(
        intl.formatMessage({
          id: 'common.created.successfully',
          defaultMessage: 'Created successfully.'
        })
      );
    } else {
      message.error('erroe' );
      throw new Error(result.detail)
    }
  };

**Comment by haungxinyan** [comment]
救救我救救我  
可能我需要停下来去写其他页面了
卡一天了
每天都因为太菜承受各种代码的伤害

**Comment by chen-ccll** [comment]
重新reload()一下

**Comment by 0x457** [comment]
> 重新reload()一下

数据多，不想reload

**Comment by 0x457** [comment]
![image](https://user-images.githubusercontent.com/5813610/143163306-3e844669-ae19-4b65-a7d9-e404e7c909da.png)

**Comment by 0x457** [comment]
> ![image](https://user-images.githubusercontent.com/5813610/143163306-3e844669-ae19-4b65-a7d9-e404e7c909da.png)
thanks , I've found out which.

**Comment by 0x457** [comment]
> > 重新reload()一下
> 
> 数据多，不想reload

thanks , I've found out which.

**Comment by haungxinyan** [comment]
>

**Comment by haungxinyan** [comment]
并没有解决  可能需要想办法在editable onChange来设置了

**Comment by 0x457** [comment]
> 并没有解决 可能需要想办法在editable onChange来设置了

我已经解决了，cancelEditable一下，然后reject就可以了

**Comment by haungxinyan** [comment]
> 
可以贴段代码吗

**Comment by haungxinyan** [comment]
> > 并没有解决 可能需要想办法在editable onChange来设置了
> 
> 我已经解决了，cancelEditable一下，然后reject就可以了

可以贴一段代码吗

**Comment by haungxinyan** [comment]
> > > 并没有解决 可能需要想办法在editable onChange来设置了
> > 
> > 
> > 我已经解决了，cancelEditable一下，然后reject就可以了
> 
> 可以贴一段代码吗
o(╥﹏╥)o

**Comment by 0x457** [comment]
> > > > 并没有解决 可能需要想办法在editable onChange来设置了
> > > 
> > > 
> > > 我已经解决了，cancelEditable一下，然后reject就可以了
> > 
> > 
> > 可以贴一段代码吗
> > o(╥﹏╥)o
actionRef.current?.cancelEditable(rowKey) 
return Promise.reject()

**Comment by lck123357** [comment]
actionRef.current?.cancelEditable(rowKey)
return Promise.reject()
请问这段代码是写在哪里呢？

**Comment by chenshuai2144** [comment]
onSave 里面，也可以直接用 throw new Error

**Comment by h1nson** [comment]
解决了我的疑惑，谢谢大家。

**Comment by ErazerControl** [comment]
> Promise.reject() 之后，点取消再编辑的话 编辑框里还是reject时候的状态 不是应该是初始值的状态吗 离谱

+1。我也遇到这个问题了。
