### ISSUE TITLE
🧐[问题]Proform和Protable的autocomplete功能失效，表单无法显示历史记录

### ISSUE THREAD

**Issue by ClydeZwei** [ant-design/pro-components#4104]
### 🧐 问题描述

Proform和Protable的autocomplete功能失效，填写表单的时候不会出现以前的历史记录。
如何将之前填过的历史记录在表单的下拉框中显现出来

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/62864474/143006172-7ce1efa7-7b63-4160-9065-49500c628f29.png)
![image](https://user-images.githubusercontent.com/62864474/143006587-83598650-047c-498c-8287-f0078b289205.png)
![image](https://user-images.githubusercontent.com/62864474/143006327-1a300e39-8aa3-46b7-9844-b7910c2f595f.png)

**Comment by ClydeZwei** [comment]
图1和图2是历史记录失效的情况，图三是官网中有历史记录的实例

**Comment by chenshuai2144** [comment]
```
  <ConfigProviderWrap>
      <BaseForm
        autocompleted="off"
        {...rest}
        initialValues={{
          ...initialValues,
          ...initialData,
        }}
      />
    </ConfigProviderWrap>
```
手动打开一下 autoComplete 吧
