### ISSUE TITLE
🐛[BUG][pro-form] select request 不执行；没有展示下拉数据

### ISSUE THREAD

**Issue by lzbabd** [ant-design/pro-components#4106]
### 🐛 bug 描述
在配合ModelForm 使用 ProFormSelect 组件的并且配置了 ` destroyOnClose: true ` 时候； request 没有执行；下方有详细的复现代码。一下只是我测试出来的案例，可能不是唯一出现的场景；

### 💻 复现代码

https://codesandbox.io/s/biao-dan-xiang-forked-ojs56

### © 版本信息

- pro-form 版本: 1.49.3

![image](https://user-images.githubusercontent.com/15899833/143046837-9193bf00-0340-42c8-ad8d-ec692740f837.png)

**Comment by lzbabd** [comment]
没人遇到这个问题吗？

**Comment by chenshuai2144** [comment]
有的，已经修复了。重新安装下依赖。
原因是 我们做了去抖，导致 swr 缓存了一个错误的promise。
