### ISSUE TITLE
🐛[BUG] Issue with new lightProps property

### ISSUE THREAD

**Issue by eddyLazar** [ant-design/pro-components#4109]
unfortunately `lightProps` does not work if field has valueType: "date" labelFormatter is not called with this valueType and looks like with any other specific valueType.

**Comment by eddyLazar** [comment]
Okay, so after this fix https://github.com/ant-design/pro-components/pull/4068 we now have a new property `lightProps`

According to the example when I'm using it like this 
```
{
    ...
    formItemProps: {
      lightProps: {
        labelFormatter: (value) => `app-${value}`,
      },
    },
   ...
}
```

It works fine, but when I'm using it with some `valueType`

```
{
    ...
    valueType: "date",
    formItemProps: {
      lightProps: {
        labelFormatter: (value) => `app-${value}`,
      },
    },
   ...
}
```

lightProps do not work any more. 

Is this enough or some GitHub repo or code sandbox is needed?

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/blob/master/packages/table/src/demos/lightfilter.tsx

fixed

**Comment by sAs59** [comment]
at which version was it fixed?
