### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by lizengjia** [ant-design/pro-components#4111]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProTable中 
配置了params， 通过改变params来重新请求数据时，页码没有从第一页开始
### 🏞 期望结果

通过改变params来重新请求数据时，页码从第一页开始

### © 版本信息

 "name": "@ant-design/pro-table",
  "version": "2.58.1",

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/15901115/143192402-ed8a7fa4-2fe0-48c1-b4f8-d708627dacbf.png)

**Comment by qq1170623178** [comment]
@lizengjia  你解决了吗，为啥我升级到最新版本还是有问题

**Comment by chenshuai2144** [comment]
代码被我删除了，有兴趣来个pr
