### ISSUE TITLE
🧐[问题]关于ProLayout中的getMenuData方法返回数据问题

### ISSUE THREAD

**Issue by zhangheng0317** [ant-design/pro-components#4114]
### 🧐 问题描述

问题是这样的
我和我的同事用同样的代码但不同的IDE(我VScode 他WebStorm),
调用getMenuData,返回menuData的格式却不一样,我返回的子路由是children,他的却是routes
因为这个问题导致后续判断子路由出现BUG
我查了半天实在没看出来是哪里出的问题,只好麻烦你们了

### 💻 示例代码
我的代码返回
![image](https://user-images.githubusercontent.com/76459860/143210153-e29b0690-9d0e-404f-bd16-84281eec764e.png)
同事的代码返回
![lQLPDhrl6SGj7iTNAtHNBhCwlYc_akvRBhoBpe2uMYA8AA_1552_721](https://user-images.githubusercontent.com/76459860/143210022-2e84d2ed-0503-46d0-ae27-b87ebb32baaa.png)

**Comment by night-karas** [comment]
包版本的问题，我看了一下最新的包（6.31.2），两个都有返回（routes，children）。
![image](https://user-images.githubusercontent.com/26538290/143796195-cb4d7662-e552-4ff4-b7ae-e26ff9703f36.png)

**Comment by chenshuai2144** [comment]
children 被废弃了，在新版本umi中不支持这种用法了。
