### ISSUE TITLE
🧐[问题]我在fieldProps设置了筛选项的初始值defaultValue或者value，为什么在request看不到这个参数呢？

### ISSUE THREAD

**Issue by 2470589018** [ant-design/pro-components#412]
### 🧐 问题描述

大佬好，我在fieldProps设置了筛选项的初始值defaultValue或者value，为什么在request看不到这个参数呢？
是我遗漏了什么属性还是暂不支持，感谢大佬指教。

### 💻 示例代码

 {
      title: 'ID',
      dataIndex: 'id',
      fieldProps: { value: '1' }
 },
 request={(params) => {
       console.log(params)
 }}
打印的结果只有{current:1,pageSize:20}

**Comment by chenshuai2144** [comment]
使用 form 的方式，而不是这种 hack 的方式。用 initvalues

**Comment by 2470589018** [comment]
> 使用 form.initialValues 的方式，而不是这种 hack 的方式。
> 
> ```
>  initialValues={{
>           name1: 'yutingzhao1991',
>           name3: '2020-08-19',
>         }}
> ```

谢谢大佬，完美解决
