### ISSUE TITLE
antd pro v5版本protable在列大于50之后，翻页会出现明显的卡顿现象，网络请求时间<100ms🐛[BUG]

### ISSUE THREAD

**Issue by peng19860226** [ant-design/pro-components#4125]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤

protable在列大于50之后，翻页会出现明显的卡顿现象，网络请求时间<100ms，使用antd 的table组件明显效率要高很多，这个问题能优化一下吗，毕竟还是希望使用protable，毕竟工程化比较好

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
因为protable自定义的render了。render速度还挺慢的。你可以用shoudCellRender

**Comment by peng19860226** [comment]
> houdCellRender

帅哥，这个shoudcellrender没找到呢，是column下面的属性吗

**Comment by chenshuai2144** [comment]
shouldCellUpdate | 自定义单元格渲染时机 | (record, prevRecord) => boolean | - | 4.3.0
-- | -- | -- | -- | --
