### ISSUE TITLE
🧐[问题] pro-table 的列使用ellipsis，为什么会默认增加tooltips

### ISSUE THREAD

**Issue by darknessjs** [ant-design/pro-components#4128]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

会出现两个弹窗的现象，一个是tooltips，一个是省略号span的title

### 🚑 其他信息

https://github.com/ant-design/pro-components/blob/104610914eedfecd88ceb2e38d86c47ff8b2fc89/packages/utils/src/genCopyable/index.tsx#L35

**Comment by darknessjs** [comment]
有人能给个回复吗。。。

**Comment by chenshuai2144** [comment]
那个title 是为了 可访问性。为了 视障人士 你就忍耐一下吧
