### ISSUE TITLE
🐛[BUG] ProFormMoney组件添加addonAfter属性，增加rules属性之后，label前面不会出现*号

### ISSUE THREAD

**Issue by yang-chuanjiang** [ant-design/pro-components#4129]

**Comment by yang-chuanjiang** [comment]
@chenshuai2144 你好，我看这个问题已经merge了，请问我应该怎样修改呢
![image](https://user-images.githubusercontent.com/38531906/144014359-01c5b0db-dcdb-4ee0-b3ca-f24a9422a362.png)

**Comment by chenshuai2144** [comment]
发布了，可以重新安装试试
