### ISSUE TITLE
🧐[问题] 最新版本的antd ModalForm 报 bad setState() 警告

### ISSUE THREAD

**Issue by Poker-Faces** [ant-design/pro-components#4132]
### 🧐 问题描述

最新版本的antd-pro ModalForm 报 bad setState() 警告

### 💻 示例代码

[https://gitee.com/gongdesheng/public/blob/master/antdformWarning.jsx](https://gitee.com/gongdesheng/public/blob/master/antdformWarning.jsx)

### 🚑 其他信息

问题截图 1
![image](https://user-images.githubusercontent.com/33587459/143561627-679c4591-5c72-45bd-811e-335140c7f0e3.png)
问题截图 2
![image](https://user-images.githubusercontent.com/33587459/143562503-1feff530-5aea-4c2a-9fb6-4eade95cbbec.png)

**Comment by chenshuai2144** [comment]
修复了，重新更新一下
