### ISSUE TITLE
添加了动态菜单，菜单切换卡顿，延迟至少1秒以上🐛[BUG]

### ISSUE THREAD

**Issue by peng19860226** [ant-design/pro-components#4134]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
添加了动态菜单，菜单切换卡顿，延迟至少1秒以上
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/47234766/143566693-52fdc706-7154-40e8-ac06-4bac1c70a2a8.png)

https://user-images.githubusercontent.com/47234766/143567039-29b0af4f-f2af-4e4d-af4c-678688055f9d.mp4

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
删除掉chidren再试试 我感觉是table卡住了
