### ISSUE TITLE
🧐[问题]Checkbox.Group/Checkbox checked 不管用，不知为什么

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#4135]
Checkbox checked 不管用，不知为什么
`<Checkbox value={item.value} checked={true}>`
即使把checked设为true，Checkbox也没有选择，

```
const fCheckBoxGroup = ({ options, defaultValue }) => {
  return (
    <Checkbox.Group>
      {options.map((item) => {
        const checked = true;
        return (
          <Row key={item.value}>
            <Checkbox value={item.value} checked={checked}>
              {item.label}
            </Checkbox>
          </Row>
        );
      })}
    </Checkbox.Group>
  );
};
```

**Comment by chenshuai2144** [comment]
Checkbox.Group  的 checkbox 被Checkbox.Group 接管了，用 Checkbox.Group 的value 来控制

**Comment by jonny-xhl** [comment]
使用**ProField**设置**valueType**为**checkbox**时也需要通过控制Field的value来默认选中吗？
<Field mode="edit" valueType='checkbox' request={async () => [{ label: 'test', value: 'test', checked: true }]} />
