### ISSUE TITLE
👑 [需求] dateFormatter 属性建议支持自定义方法，

### ISSUE THREAD

**Issue by justLearner** [ant-design/pro-components#4137]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


为了更好的理解用户的需求，我假设这个需求是：

用户现在正在使用一个日期格式化的库，但是这个库只支持一些固定的日期格式，用户希望这个库能够支持用户自定义的日期格式。用户提出了建议：给dateFormatter属性增加一个可自定义的方法，让用户能够使用自定义的日期格式。现在需求就是增加一个自定义方法的功能。 

以下是我的解决方案：

1. 首先在组件中新增一个名为“customDateFormatter”的属性

2. 让用户在这个属性上定义他们自己的日期格式化方法

3. 在组件内部根据用户是否定义了customDateFormatter属性来判断使用哪个日期格式化方法

4. 如果用户定义了customDateFormatter属性，则使用其定义的方法进行日期格式化

5. 如果用户没有定义customDateFormatter属性，则使用默认的日期格式化方法

代码示例：

```jsx
import React from 'react'
import PropTypes from 'prop-types'
import moment from 'moment'

class DateDisplay extends React.Component {
  static propTypes = {
    date: PropTypes.instanceOf(Date).isRequired,
    customDateFormatter: PropTypes.func,
  }

  static defaultProps = {
    customDateFormatter: null,
  }

  render() {
    const { date, customDateFormatter } = this.props
    const formattedDate = customDateFormatter
      ? customDateFormatter(date)
      : moment(date).format('YYYY-MM-DD')
    return <div>{formattedDate}</div>
  }
}
```

文档提供：

1. moment（日期格式化库）官网：https://momentjs.com/docs/

2. PropTypes（React组件属性类型检查）官网：https://reactjs.org/docs/typechecking-with-proptypes.html

**Comment by chenshuai2144** [comment]
支持啦
