### ISSUE TITLE
🐛[BUG]proTable  valueType: 'digit' -  整数 会被强制 + 个 .0

### ISSUE THREAD

**Issue by Banlangenn** [ant-design/pro-components#4138]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

例如 6 会被转换为 6.0

### 🏞 期望结果

不需要转换

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
加了小数点配置了？

**Comment by Banlangenn** [comment]
![image](https://user-images.githubusercontent.com/19684540/143681485-bd047a61-886e-4a35-8590-1890433f3a43.png)

[点我复现codesandbox](https://codesandbox.io/s/valuetype-shu-zi-lei-forked-u9341?file=/App.tsx)

**Comment by Banlangenn** [comment]
备注： 复现的过程中 ，发现 小于10 会-出现

**Comment by chenshuai2144** [comment]
配置一下 

```、
fieldProps: {

intlProps: { minimumSignificantDigits: 1 }

}
```


我想想怎么一劳永逸的解决这个问题

**Comment by chenshuai2144** [comment]
修复已经发布
