### ISSUE TITLE
🐛[BUG] @ant-design/pro-form 1.49.3 ProFormCascader fieldProps parmas ts飘红

### ISSUE THREAD

**Issue by codedart2018** [ant-design/pro-components#4139]
### 🐛 bug 描述

在 @ant-design/pro-form 1.49.3 ProFormCascader 组件上给　fieldProps 参数的时候会导致ts检测不过飘红。

### 📷 复现步骤

```
     <ProFormCascader
              label='所属区域'
              name='region_ids'
              rules={[
                {
                  required: true,
                  message: '请选择所属区域'
                }
              ]}
              wrapperCol={{ span: 16 }}
              fieldProps={{ placeholder: '请选择所属区域', showSearch: { filter: filterCascader } }}
              request={async () => {
                return region;
              }}
            />
```
![image](https://user-images.githubusercontent.com/12706830/143683214-32a930e0-ddca-4a6b-b566-de2deed33703.png)

### 🏞 期望结果
通过检测不飘红

### © 版本信息
-@ant-design/pro-form 1.49.3版本
- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
发现是antd 改了类型，现在需要手动传个范型了，我加了个any先

**Comment by ATacoo** [comment]
@codedart2018  哈喽  
rules={[
                {
                  required: true,
                  message: '请选择所属区域'
                }
              ]}

加了校验 有用吗。我怎么这样写 不起作用

**Comment by chenshuai2144** [comment]
他可能是个数组你自定义一下为空的判断

**Comment by codedart2018** [comment]
> @codedart2018 哈喽
> 
> ```
> rules={[
>                 {
>                   required: true,
>                   message: '请选择所属区域'
>                 }
>               ]}
> ```
> 
> 加了校验 有用吗。我怎么这样写 不起作用

有用的

**Comment by ATacoo** [comment]
@chenshuai2144  @codedart2018    请问下ProForm 里嵌套个 proTable。怎么触发 proTable的空的校验啊 

<ProFormDependency name={['radio51']}>
              {({ radio51 }) => {
                const selectStoreFlag = radio51 === 'c';
                const selectRegionFlag = radio51 === 'b';
                return (
                  <>
                    {selectStoreFlag && (
                      <ProForm.Item name="DS" trigger="onDataSourceChange">
                        <ProTable
                          rowKey="code"
                          search={false}
                          options={false}
                          dataSource={[
                            { code: '111', address: '龙峰' },
                            { code: '222', address: '龙峰' },
                          ]}
                          columns={[
                            {
                              title: '门店code',
                              dataIndex: 'code',
                            },
                            {
                              title: '门店地址',
                              dataIndex: 'address',
                            },
                            {
                              title: '操作',
                              valueType: 'option',
                              width: 100,
                              render: (text, record, _, action) => [
                                <a
                                  key="editable"
                                  onClick={() => {
                                    action?.startEditable?.(record.code);
                                  }}
                                >
                                  删除
                                </a>,
                              ],
                            },
                          ]}
                          toolBarRender={() => [
                            <Button key="primary" type="primary" onClick={() => selectStore()}>
                              <SearchOutlined />
                              选择门店
                            </Button>,
                          ]}
                        />
                      </ProForm.Item>
                    )}
                  </>
                );
              }}
            </ProFormDependency>
