### ISSUE TITLE
DrawerForm属性destroyOnClose会触发两次request🐛[BUG]

### ISSUE THREAD

**Issue by cloudsnet** [ant-design/pro-components#4140]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

DrawerForm属性
drawerProps={{
 destroyOnClose:true
}}
初始化会触发DrawerForm两次request请求

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by DerrickTel** [comment]
https://codesandbox.io/s/dpqjn

**Comment by cloudsnet** [comment]
> https://codesandbox.io/s/dpqjn '4444' 只输出一次...你改改这个demo看看？

根据你的代码我测了一下，确实没出现BUG 你将他嵌套到表格 试试，我是在表格基础上使用的

**Comment by DerrickTel** [comment]
> > https://codesandbox.io/s/dpqjn '4444' 只输出一次...你改改这个demo看看？
> 
> 根据你的代码我测了一下，确实没出现BUG 你将他嵌套到表格 试试，我是在protable基础上使用的，并且为了代码方便，以及默认值，我将DrawerForm又封装一个层

或者你改一下，方便我们找问题。

**Comment by cloudsnet** [comment]
> > > https://codesandbox.io/s/dpqjn '4444' 只输出一次...你改改这个demo看看？
> > 
> > 
> > 可知你的代码我测了一下，确实没有出现BUG 你将他隐藏到表格中，巧妙的我是在可移植的基础上使用的，并且为了代码方便，以及默认值，我将DrawerForm又封装了一层
> 
> 或者你改一下，方便我们找问题。

我好像发现是我的父子传值导致了重复渲染，还不确定，我先改改我的项目代码，后面再观察看看
