### ISSUE TITLE
🧐[问题]使用prolayout加响应式布局时出现屏幕闪烁

### ISSUE THREAD

**Issue by a2670392079** [ant-design/pro-components#4144]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
当layout的子组件中有高度随宽度变化的组件A时，在特定的分辨率下会导致 屏幕宽度变大->A组件高度变大->body出现纵向滚动条(导致屏幕宽度变小)->A组件高度变小->纵向滚动条消失->屏幕宽度变大。最终显示出来就会导致屏幕闪烁。
引起这个的原因是ProLayout中使用ResizeObserver动态设置内容高度：

### 💻 示例代码

```ts
<ProLayout>
    {/* 宽高成比例的组件 */}
    <Components />
</ProLayout>
```

给body设置为overflow: overlay可以解决但是某些浏览器不兼容这个属性

**Comment by chenshuai2144** [comment]
layout 已经去掉了 ResizeObserver 设置高度的功能。bug太多了
