### ISSUE TITLE
🐛[BUG] antProTable 使用树形表格时，点击任意一个展开都会全部展开

### ISSUE THREAD

**Issue by Jackwew** [ant-design/pro-components#4145]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

antProTable 使用树形表格时，点击任意一个展开都会全部展开。
同理收起时点击任意一行的收起会全部收起
![image](https://user-images.githubusercontent.com/50656464/143842981-3af46de8-9d9e-4143-b035-ede0c10bef5e.png)

### 📷 复现步骤

使用antProTable组件，数据使用包含children的数据

### © 版本信息

- "@ant-design/pro-table": "^2.56.0",
- "umi": "^3.5.0",
- chrome Version 96.0.4664.45 (Official Build) (64-bit)
- 开发环境 [window11]

**Comment by chenshuai2144** [comment]
这个一般都是key重复了
