### ISSUE TITLE
🐛[BUG] pro-table2.7.0，request首次加载current为undefined；分页设置多个值不生效

### ISSUE THREAD

**Issue by iamgian-coder** [ant-design/pro-components#415]
### 🐛 bug 描述

request方法params的current首次加载依然是undefined;
分页设置 position: ["bottomRight", "topRight"], bottomRight的正常显示，topRight”看不见“，F12之后发现是css属性float属性导致元素看不到

### 📷 复现步骤

create-react-app + antd + pro-table

### 🏞 期望结果

首次加载,request方法的参数params带有正常值；
分页设置多个位置的时候能正常工作

### © 版本信息

- ProComponents 版本: [pro-table:2.7.0]
- umi 版本
- 浏览器环境 chrome
- 开发环境 [win10 + vscode]

### 🚑 其他信息

![a](https://user-images.githubusercontent.com/26590255/92442417-6e151600-f1e2-11ea-8ab1-a960109cd5eb.png)

**Comment by chenshuai2144** [comment]
试了一下是可以的，来个 repo？

**Comment by iamgian-coder** [comment]
> 试了一下是可以的，来个 repo？

刚创建了一个 https://github.com/iamgian-coder/reproducebug.git

**Comment by iamgian-coder** [comment]
@chenshuai2144 提供了repo

**Comment by iamgian-coder** [comment]
@chenshuai2144 能抽空看看吗？

**Comment by chenshuai2144** [comment]
明天发个版本
