### ISSUE TITLE
🧐[想咨询如何在打包的时候排除antd的样式]

### ISSUE THREAD

**Issue by iven35** [ant-design/pro-components#4150]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

我的项目中使用了antd Protable，想咨询一下在打包的时候可不可以不打包antd的样式，因为会造成样式污染

**Comment by chenshuai2144** [comment]
用prefixCls 隔离一下把。不打包可能会有别的问题的。

**Comment by iven35** [comment]
> 用 `prefixCls `隔离一下把。不打包可能会有别的问题的。

感谢大佬的回复，问题已经解决
