### ISSUE TITLE
RangePicker组件在rederFormItem中使用报错 且样式也错误

### ISSUE THREAD

**Issue by zhubufang** [ant-design/pro-components#4153]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🏞 期望结果

样式错误
![image](https://user-images.githubusercontent.com/40162775/143987359-baee121a-e483-4138-b6bd-39ad583409b3.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- 
![image](https://user-images.githubusercontent.com/40162775/143987141-33411386-40ca-4d19-82b1-5956c4663df6.png)

- umi 版本 ^3.5.0
- 浏览器环境. 谷歌浏览器
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/40162775/143986996-b165646a-2db6-4a30-bd40-5efbc95c48d7.png)
![image](https://user-images.githubusercontent.com/40162775/143987020-34bccc34-421a-48e2-909c-e558c8cbb971.png)

**Comment by zhubufang** [comment]
![1638282047(1)](https://user-images.githubusercontent.com/40162775/144064373-3350cfe6-dc12-488e-8db4-064d50b75ce3.png)
@cc7gs

**Comment by chenshuai2144** [comment]
你要手动处理一下 dataRanger 要求必须是moment的。
你自定义render，我们不知道你到底使用的是什么，所以没办法自动处理
