### ISSUE TITLE
🐛[BUG]   关于table的bug

### ISSUE THREAD

**Issue by yxkt** [ant-design/pro-components#4155]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/72731590/144017808-cdfcc601-df7b-402d-bc8b-be10d8aa8060.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
升级下antd，。antd 已经修掉了
