### ISSUE TITLE
🐛[BUG]export 'genCopyable' (imported as 'genCopyable') was not found in '@ant-design/pro-table'

### ISSUE THREAD

**Issue by GitKou** [ant-design/pro-components#4156]
线上遇到这个问题，
![image](https://user-images.githubusercontent.com/7437397/144023846-b1e5eeec-4309-430f-9c15-30b14548f8be.png)

查看日志，发现打包并没有报错，只是给了个warning
![image](https://user-images.githubusercontent.com/7437397/144023743-e91148b3-8a7d-4685-97a7-cb9a582b986c.png)

顺着找下去，发现应该是这次更新导致的（看起来是把genCopyable方法从table抽取到了utils中）
https://github.com/ant-design/pro-components/pull/4062
我的@ant-design/pro-descriptions还是@1.10.0版本，而@ant-design/pro-table更新了，就导致@ant-design/pro-descriptions中找不到genCopyable

最后update了下@ant-design/pro-descriptions就好了，但是排查废了一定时间。
请问有没有什么好办法！

**Comment by chenshuai2144** [comment]
不要锁包，每次全量安装
