### ISSUE TITLE
🧐[问题]，菜单栏折叠后，鼠标悬浮二级菜单不显示

### ISSUE THREAD

**Issue by Tigerremy** [ant-design/pro-components#4157]
![image](https://user-images.githubusercontent.com/29435792/144037283-40ea7599-81d6-4745-bd58-e2826b0c1dda.png)
![image](https://user-images.githubusercontent.com/29435792/144037313-2ac8008c-e9dc-480e-b16a-eec0578c6d94.png)
![image](https://user-images.githubusercontent.com/29435792/144037379-0191cad4-f630-4794-b3b2-b4d336c9af76.png)

**Comment by chenshuai2144** [comment]
> 只是个提示和内容无关

 routes 不要用children了，不兼容了。
