### ISSUE TITLE
🐛[BUG] ProForm.Group 的 align 默认值设置成 start，导致无法设置成初始状态

### ISSUE THREAD

**Issue by taixw2** [ant-design/pro-components#4160]
### 🐛 bug 描述
RT

Group 接收 align 传给 Space, 实际上 Space 的 align 有五种模式，`start | end |center |baseline|未赋值的初始状态`, 初始状态的 `Space Item` 会占满整行

https://github.com/ant-design/pro-components/blob/c3851a57f54109e1348ee445034605dbf42f7e08/packages/form/src/components/Group/index.tsx#L19-L21

https://github.com/ant-design/pro-components/blob/c3851a57f54109e1348ee445034605dbf42f7e08/packages/form/src/components/Group/index.tsx#L122-L131

**目前只能通过 spaceProps.style.alignItems 覆盖 align, 如果这个 issue 是预期行为，请关闭**

### 🏞 期望结果

**默认值为空**

### 💻 复现代码

https://stackblitz.com/edit/react-npihre?file=index.js

### © 版本信息

- ProComponents 版本:  `"@ant-design/pro-form": "^1.32.4",`

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/12482817/144068760-e3047c2d-613f-48c0-b0b9-f0254420c2fc.png)

**Comment by chenshuai2144** [comment]
这个是为了保证高度不一样的 filed baseline 是相同的，不然就变成居中了。

如果需要。可以给个快捷方式来设置

**Comment by taixw2** [comment]
那还是通过 `spaceProps.style.alignItems` 来修改吧
