### ISSUE TITLE
🐛[BUG]table数据多的时候，菜单展开收缩，非常卡

### ISSUE THREAD

**Issue by zhangyugeng** [ant-design/pro-components#4164]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
ref https://github.com/ant-design/pro-components/issues/4127
ref https://github.com/ant-design/pro-components/issues/4122

**Comment by chenshuai2144** [comment]
标题问题：要看具体情况了，初步判断是protable是重型组件，数据多了确实可能会卡
菜单问题：你可以打开控制台找找dom节点之类，看看是什么情况。
