### ISSUE TITLE
🐛[BUG]点击展开全屏报错

### ISSUE THREAD

**Issue by zhouzhiyang-git** [ant-design/pro-components#417]
### 🐛 bug 描述
"@ant-design/pro-table": "2.5.6",
点击展开全屏报错，错误如下：
![image](https://user-images.githubusercontent.com/68043832/92444733-e4674780-f1e5-11ea-8426-a6dad66b6f88.png)
2.5.4版本无问题

### 💻 复现代码
更换到2.5.6版本

**Comment by afc163** [comment]
请写好标题。

**Comment by zhouzhiyang-git** [comment]
升级umi到最新版后问题不复现
