### ISSUE TITLE
🧐[问题] @ant-design/pro-table 2.59.0  自动开启了屏幕聚焦重新请求这个api，请问如何关闭

### ISSUE THREAD

**Issue by Sean1514** [ant-design/pro-components#4171]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

protable 是不是内置了useRequest ，最新版本默认打开了屏幕聚焦重新请求的功能，请问如何关闭

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/48789222/144198113-6e4b6456-203b-4c34-8af8-0f4705d19bc7.png)

**Comment by chenshuai2144** [comment]
revalidateOnFocus ｜ 窗口聚焦时自动重新请求 ｜ boolean | - |

**Comment by Sean1514** [comment]
> revalidateOnFocus ｜ 窗口聚焦时自动重新请求 ｜ boolean | - |

刚刚看到文档了 但是试用了一下无效

**Comment by chenshuai2144** [comment]
更新一下依赖
