### ISSUE TITLE
🧐[问题]pro-table 开始sticky参数没有吸顶(粘性头部)效果

### ISSUE THREAD

**Issue by zhangxiangqiang** [ant-design/pro-components#4174]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

pro-table 开始sticky参数想使用吸顶效果，发现不生效，antd里就添加一个sticky就开启了啊，pro-table 里难道有什么特别的方法？

### 💻 示例代码

```
<ProTable
        sticky
        scroll={{ x: 'max-content' }}
        size={size}
        options={false}
        actionRef={actionRefCurrent}
        formRef={formRefCurrent}
        columns={columnsPro}
        dateFormatter="number"
        request={...}
       ...
      />

```

### 🚑 其他信息
 "@ant-design/pro-table": "^2.59.2",

**Comment by DerrickTel** [comment]
有demo吗？我这里有的
![image](https://user-images.githubusercontent.com/24643779/144557595-2a815d92-a5c5-4e54-a3b6-6b52a1951a1d.png)

**Comment by zhangxiangqiang** [comment]
嗯嗯，是有效果的，与我外面包了太多层有关系

**Comment by NARUTOyuyang** [comment]
> 嗯嗯，是有效果的，与我外面包了太多层有关系

为啥我没有效果啊?

<img width="630" alt="image" src="https://user-images.githubusercontent.com/22002078/197958831-db7e4fa5-1f50-4f99-8f34-7a81f175b957.png">

**Comment by LLmoskk** [comment]
> > 嗯嗯，是有效果的，与我外面包了太多层有关系
> 
> 为啥我没有效果啊?
> 
> <img alt="image" width="630" src="https://user-images.githubusercontent.com/22002078/197958831-db7e4fa5-1f50-4f99-8f34-7a81f175b957.png">

@NARUTOyuyang 检查一下外层有没有 overflow: hidden
