### ISSUE TITLE
🧐[问题]EditableProTable编辑表格组件，在编辑的状态下点击保存的时候做校验，判断是否允许新增/修改

### ISSUE THREAD

**Issue by PearpearS** [ant-design/pro-components#4175]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

需求是这样的，在新增/编辑的时候，不允许出现一模一样的数据，所以我想在点击“保存”的时候，去判断dataSource中是否已出现一致的数据，如果出现一致的数据，则禁止新增或编辑成功，我看了下api，onSave好像并不能满足我的需求，请问我该如何处理？

**Comment by 1247748612** [comment]
1. onSave方法throw new Error('error')可以阻止方法执行

2. 也可以重新save dom的onSave事件，onRowSave则是你的逻辑，返回false就结束运行了
```typescript

  const onRowSave: RowEditableConfig<any>['onSave'] = (key, record: ParseSourceOfGoodsItem) => {
    return validator({
    })
      .then(() => {})
      .catch(() => false);
  };


  const onSave = async (
    config: ActionRenderConfig<any, NewLineConfig<any>>,
    recordKey: RecordKey,
    editRow: any,
    originRow: any,
    newLine: NewLineConfig<any>,
  ) => {
    const { options } = newLine || {};
    const res = await onRowSave(recordKey, editRow, originRow, newLine);

    if (res === false) {
      return false;
    }

    // 保存时解除编辑模式
    config.cancelEditable(recordKey);
    if (newLine && options?.recordKey === recordKey) {
      if (options?.position === 'top') {
        setValue((lastValue) => [res, ...lastValue]);
      } else {
        setValue((lastValue) => [...lastValue, res]);
      }
      return res;
    }
  };

  editable={{
    form,
    actionRender: (row, config, defaultDom) => {
      return [
        React.cloneElement(defaultDom.save as React.ReactElement, {
          onSave: onSave.bind(null, config),
        }),
        defaultDom.save,
        defaultDom.cancel,
        defaultDom.delete,
      ];
    },
  }}
```

**Comment by PearpearS** [comment]
> 

非常非常非常感谢，瞬间茅塞顿开了

**Comment by PearpearS** [comment]
> 1. onSave方法throw new Error('error')可以阻止方法执行
> 2. 也可以重新save dom的onSave事件，onRowSave则是你的逻辑，返回false就结束运行了
> 
> ```ts
>   const onRowSave: RowEditableConfig<any>['onSave'] = (key, record: ParseSourceOfGoodsItem) => {
>     return validator({
>     })
>       .then(() => {})
>       .catch(() => false);
>   };
> 
> 
>   const onSave = async (
>     config: ActionRenderConfig<any, NewLineConfig<any>>,
>     recordKey: RecordKey,
>     editRow: any,
>     originRow: any,
>     newLine: NewLineConfig<any>,
>   ) => {
>     const { options } = newLine || {};
>     const res = await onRowSave(recordKey, editRow, originRow, newLine);
> 
>     if (res === false) {
>       return false;
>     }
> 
>     // 保存时解除编辑模式
>     config.cancelEditable(recordKey);
>     if (newLine && options?.recordKey === recordKey) {
>       if (options?.position === 'top') {
>         setValue((lastValue) => [res, ...lastValue]);
>       } else {
>         setValue((lastValue) => [...lastValue, res]);
>       }
>       return res;
>     }
>   };
> 
>   editable={{
>     form,
>     actionRender: (row, config, defaultDom) => {
>       return [
>         React.cloneElement(defaultDom.save as React.ReactElement, {
>           onSave: onSave.bind(null, config),
>         }),
>         defaultDom.save,
>         defaultDom.cancel,
>         defaultDom.delete,
>       ];
>     },
>   }}
> ```

非常非常非常感谢，瞬间茅塞顿开了
