### ISSUE TITLE
🐛[BUG]ProTable 拖动列设置产生了死循环问题

### ISSUE THREAD

**Issue by LYP949839107** [ant-design/pro-components#4180]
### 🐛 bug 描述

使用 ProTable 的列设置功能，当我试图将某一列从 ”固定在左侧“ 移动到 ”不固定“ 时 控制台开始出现死循环报错，或者开始无限访问 umi.js

### 📷 复现步骤

1. 使用 ProTable 创建一个表格
2. 设置某列数据为 ”固定在左侧“
3. 使用拖拽功能拉动该列进入”不固定“
4. 无须松手，问题即出现

![image](https://user-images.githubusercontent.com/25222375/144384720-47f3b35f-d37e-4632-ba58-bcdb4b68e1da.png)
![image](https://user-images.githubusercontent.com/25222375/144385062-87a84a00-575a-488b-b96c-199cf02ce59e.png)

### 🏞 期望结果

不应该出现无限循环的情况，如不支持本操作，请禁止。

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
  "@ant-design/pro-table": "^2.56.3",
- umi 版本
- 浏览器环境  
  Chrome 95.0.4638.69（正式版本）
- 开发环境
   [e.g. mac OS]

**Comment by chenshuai2144** [comment]
antd 有个小bug，我先绕过去。我的交互也有点问题
