### ISSUE TITLE
EditableProTable编辑向后端发送请求，编辑成功后，刷新table，再次点编辑 值并不是最新的，依旧是上一次自己手动编辑的值

### ISSUE THREAD

**Issue by yhwtest** [ant-design/pro-components#4182]
如题
EditableProTable编辑向后端发送请求，编辑成功后，刷新table，再次点编辑 值并不是最新的，依旧是上一次自己手动编辑的值
![image](https://user-images.githubusercontent.com/86184329/144539258-3c09263f-279e-4da5-8cb8-07e8e6d0dcbe.png)
是一个select，托管了onchange,value

          <Select
            key="searchSelect"
            showSearch
            placeholder="请选择业务线"
            filterOption={false}
            onFocus={handleSearch}
          >
            {deptInfo.map((item, i) => {
              return (
                <Select.Option index={i} value={item.id} key={item.id}>
                  {item.dept_name}
                </Select.Option>
              );
            })}
          </Select>

**Comment by 1247748612** [comment]
其他字段都有更新吗？

select 可以使用valueType: 'select'

onSave函数需返回record
