### ISSUE TITLE
🧐[问题] pro-*组件在打包的时候会把下面模块一起打包，导致打包体积增加？

### ISSUE THREAD

**Issue by yuanye4017** [ant-design/pro-components#4183]
### 🧐 问题描述

通过`yarn analyze`分析发现在使用`pro-form`后会将其下的所有模块统统打包进来，导致打包体积过大，这种现象是否正常？正常的话能不能避免？

### 💻 示例代码
```js
import { QueryFilter, ProFormDateRangePicker, ProFormText } from '@ant-design/pro-form';
 <QueryFilter>
    <ProFormText name="name" label="企业" />
    <ProFormDateRangePicker name="create" label="分析区间" />
</QueryFilter>
```
### 🚑 其他信息
![image](https://user-images.githubusercontent.com/43987769/144541676-c06e9e2b-adc5-49e1-9905-44619c5afdf3.png)
![image](https://user-images.githubusercontent.com/43987769/144542050-7b62579d-101b-4bd2-a95a-f96e06079529.png)

比如`pro-form`为例，使用了其中的两个`modules`，但是打包却把355个`modules`全部打包？但是具体到某一个使用`pro-form`的组件发现也进行了一次按需加载？这个话355个`modules`感觉有点不必要呢？

**Comment by chenshuai2144** [comment]
umi@4会考虑优化

**Comment by zwmmm** [comment]
解决了么 我看umi@4发布了

**Comment by chenshuai2144** [comment]
会的，暂时没有很好的解法。
