### ISSUE TITLE
https://github.com/ant-design/pro-components/blob/5e46321e45a123f098664aa49776194f81f6e443/packages/form/src/layouts/LoginForm/index.tsx#L24

### ISSUE THREAD

**Issue by jmy1944311667** [ant-design/pro-components#4186]
这个切换语言，提交一直是中文的，这个说明没看明白什么意思，请问应该怎么改？

https://github.com/ant-design/pro-components/blob/5e46321e45a123f098664aa49776194f81f6e443/packages/form/src/layouts/LoginForm/index.tsx#L24

_Originally posted by @chenshuai2144 in https://github.com/ant-design/pro-components/issues/3924#issuecomment-983517558_

**Comment by chenshuai2144** [comment]
一般来说都是因为你有多份antd 导致数据不通 组件走了默认
