### ISSUE TITLE
👑 [需求]ProDescription的编辑模式支持监听onEnter

### ISSUE THREAD

**Issue by yykoypj** [ant-design/pro-components#4187]
### 🥰 需求描述
ProDescriptions组件在编辑模式下，无法使用Enter键触发提交。
已经试过在renderFormItem方法中使用form.submit()但是不起效；
![image](https://user-images.githubusercontent.com/15713772/144577607-38ce7b41-4f6f-446f-8514-634c744734a7.png)

### 🧐 解决方案

renderFormItem的第二个参数config里面有没有可能将onSave函数传进来,这样我就可以手工调用了。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


可以通过自定义renderFormItem属性来解决这个问题，利用antd的Form组件的onPressEnter属性监听Enter键事件，在回调函数中手动提交表单。代码示例如下：

```jsx
import { Form } from 'antd';
import ProDescriptions from '@ant-design/pro-descriptions';

const CustomRenderFormItem = (item, config, form) => {
  return (
    <Form.Item
      {...config}
      onPressEnter={() => {
        form.submit();
      }}
    >
      {item.render ? item.render(form) : form.getFieldDecorator(item.key, item.options)(item.inputRender?.())}
    </Form.Item>
  );
};

<ProDescriptions
  column={1}
  dataSource={{
    key: 'value',
  }}
  columns={[
    {
      dataIndex: 'key',
      label: 'Key',
      valueType: 'text',
      editable: true,
      renderFormItem: CustomRenderFormItem, // 自定义renderFormItem属性
    },
    {
      dataIndex: 'value',
      label: 'Value',
      valueType: 'text',
      editable: true,
      renderFormItem: CustomRenderFormItem, // 自定义renderFormItem属性
    },
  ]}
/>
```

以上代码中，CustomRenderFormItem返回一个定制化的表单组件，它接收三个参数：item、config和form。其中item是对应的表头项，config是渲染表单组件相关的配置，form则是antd的Form组件对象，可以用来手动提交表单。在这个定制化的表单组件中，我们传入onPressEnter属性，以监听Enter键事件。

相关文档：[Antd Form](https://ant.design/components/form-cn/)

**Comment by chenshuai2144** [comment]
https://ant-design.antgroup.com/components/form-cn#formusewatch
用这个试试
