### ISSUE TITLE
🐛[BUG]ProTable 外层会包一层ProCard，其内边距是否改为可自定义设置？

### ISSUE THREAD

**Issue by VanLee1212** [ant-design/pro-components#4188]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by huadream** [comment]
https://github.com/ant-design/pro-components/blob/db9b8ad1ec10d4de1416b00ce79071b098e32f0a/packages/table/src/Table.tsx#L249

使用cardProps进行配置，cardProps={false} 则不会包裹Card
