### ISSUE TITLE
🧐[问题] 使用ProTable组件，不分页时，数据多时怎么回去顶部

### ISSUE THREAD

**Issue by explorefit** [ant-design/pro-components#4189]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

使用ProTable组件，在不分页时，数据多时，在看最下面的数据时怎么快速回到顶部，使用 BackTop 组件 在这里面不起作用，
我看代码是 Pro Table里封装的

**Comment by chenshuai2144** [comment]
BackTop   要自定义滚动的dom的，你的滚动条应该是个没设置到 body上面
