### ISSUE TITLE
🧐[问题] ProFormList中复制一行的数据能否放在当前行的下方

### ISSUE THREAD

**Issue by zpaimon** [ant-design/pro-components#4190]
目前看样例在ProFormList中，点击 “复制” 按钮复制的数据都是放在最下方，能否有办法设置放在当前行的下方，有的时候编辑列表数据，想在中间插入一行。谢谢！

**Comment by ai180508** [comment]
同问

**Comment by DerrickTel** [comment]
假如点的是一页的最后一行，那当前行或者复制出来的一行就要有一行要去下一页了（**这里可能会有歧义，不同的产品之间的理解可能会有不同**）。这个比较难处理。但是如果是添加在最后就直接把最后一行数据给挤到后面一页就好了。

**Comment by zpaimon** [comment]
> 假如点的是一页的最后一行，那当前行或者复制出来的一行就要有一行要去下一页了（**这里可能会有歧义，不同的产品之间的理解可能会有不同**）。这个比较难处理。但是如果是添加在最后就直接把最后一行数据给挤到后面一页就好了。


目前没有分页的情况吧。只是想在 某一行的下方插入，譬如：我想增加有序的东西，增加完N行后，想在中间的某一行的下方增加一个事情，目前做法是让人把下面的都重新输入，这个用户体验非常不好。还望能有好的解决方法.

**Comment by chenshuai2144** [comment]
除非能自动滚动到这一行，不然往下增加的问题会有很多。

**Comment by zpaimon** [comment]
> 除非能自动滚动到这一行，不然往下增加的问题会有很多。

有啥等价的方法吗?

**Comment by chenshuai2144** [comment]
没什么好办法，要搞的话就自己实现一下吧
