### ISSUE TITLE
🧐[问题]protable中hideInForm有啥用？

### ISSUE THREAD

**Issue by itzhoujun** [ant-design/pro-components#4193]
### 🧐 问题描述

protable的column有hideInForm属性，但是没明白是干啥用的。原本以为是用于隐藏查询表单字段用的，后来发现hideInSearch才是

### 💻 示例代码

无

### 🚑 其他信息

无

**Comment by DerrickTel** [comment]
https://procomponents.ant.design/components/schema-form
