### ISSUE TITLE
🧐[问题] 可编辑的表格select

### ISSUE THREAD

**Issue by kuangxz** [ant-design/pro-components#4194]
### 🧐 问题描述

在可编辑的表格中下拉列表中使用valueEnum带有状态字段可以显示状态，但是在修改的时候无法回显，必须写上fieldProps.options才可以正确的回显

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/36146123/144742240-44265b35-d53d-4171-92a9-de8e001fdd2e.png)
![image](https://user-images.githubusercontent.com/36146123/144742257-495c6a6d-15ac-4e6a-8324-d942c8724479.png)

**Comment by chenshuai2144** [comment]
注意一下number 和 string， object 的key是不能是 number
