### ISSUE TITLE
🧐[问题]ProList 怎么操作刷新，类似Protable 通过actionRef

### ISSUE THREAD

**Issue by gaspire** [ant-design/pro-components#4195]
### 🧐 问题描述
ProList 怎么操作刷新，类似Protable 通过actionRef

**Comment by DerrickTel** [comment]
也是传入actionRef

**Comment by gaspire** [comment]
提示类型不对

**Comment by DerrickTel** [comment]
> 提示类型不对

哪个不对
![image](https://user-images.githubusercontent.com/24643779/144970965-96bc7465-2209-4b93-b55c-4216ce8b47c3.png)

**Comment by gaspire** [comment]
![image](https://user-images.githubusercontent.com/49259119/144974737-d404782d-bc26-4508-876f-99a36cabed7e.png)
![image](https://user-images.githubusercontent.com/49259119/144974775-69b85d4b-0b95-4ec5-8eed-2ae349c6b909.png)
版本如下：
"antd": "4.15.0",
"@ant-design/pro-list": "^1.20.0",
 "@ant-design/pro-table": "2.33.0",

**Comment by DerrickTel** [comment]
看看提示的最下面

**Comment by gaspire** [comment]
![image](https://user-images.githubusercontent.com/49259119/144983021-d188d2b2-8a7d-47c9-83be-1049e14da777.png)

**Comment by DerrickTel** [comment]
升下版本

**Comment by gaspire** [comment]
升级@ant-design/pro-list？

**Comment by gaspire** [comment]
actionRef.current?.reload()
