### ISSUE TITLE
🧐[问题]ProFormList如何通过外部组件修改其中某一项的值

### ISSUE THREAD

**Issue by ai180508** [ant-design/pro-components#4198]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
示例：
https://codesandbox.io/s/proform-list-forked-7mzr6?file=/App.tsx

点击姓名后会有一个弹窗，请问如何用弹窗中选中的值改变ProFormList中的值

**Comment by DerrickTel** [comment]
不是有一个form的ref吗？

**Comment by ai180508** [comment]
> 不是有一个form的ref吗？

我试过也不行呢，可能是我的处理的方式不对，但是我确实不知道该如何处理

**Comment by chenshuai2144** [comment]
在react devtool里面看看 name是什么。一般都是 name 没找对

**Comment by zeewell** [comment]
新手，类似的问题，比如 @ai180508 说的这个例子，怎么定位到某一行的数据呢？能不能详细说说呢？
