### ISSUE TITLE
👑 [需求]pro-layout是否可以支持上下形式的

### ISSUE THREAD

**Issue by xiexingen** [ant-design/pro-components#42]
### 🥰 需求描述
![image](https://user-images.githubusercontent.com/7939085/88644485-9b57aa00-d0f5-11ea-9d3c-912090b61a4b.png)
如图，现在是side模式 左侧会占一整列，有时候需要头部是占用整行屏幕的

**Comment by WynterDing** [comment]
亲，mix 模式 了解一下？

**Comment by xiexingen** [comment]
side、top、mix
mix不同，mix是 上 和 左侧

**Comment by xiexingen** [comment]
这种相当于 上下结构   下面分成左右  左边菜单、右边内容，  然后折叠菜单的时候顶部的不受影响

**Comment by xiexingen** [comment]
> 亲，mix 模式 了解一下？
> 
> https://preview.pro.ant.design/dashboard/analysis?navTheme=light&splitMenus=false&layout=mix

其实相当于在mix的基础上 可以不要顶部的菜单 只要左侧的，这种可以控制到吗

**Comment by manan1234** [comment]
麻烦问一下mix模式的代码去哪里可以看到
