### ISSUE TITLE
ProTable 不能触发重新获取数据

### ISSUE THREAD

**Issue by mengxk123** [ant-design/pro-components#420]
一般操作栏会有编辑，删除，禁用，启用等操作，如果操作过后应该从新获取数据，ProTable居然没有js实现的方法

**Comment by chenshuai2144** [comment]
看这个 api

actionRef | Table action 的引用，便于自定义触发 | React.MutableRefObject<FormInstance> \| ((actionRef: ActionType) => void) | -
-- | -- | -- | --
