### ISSUE TITLE
🐛[BUG] 使用ProTable时，BackTop 组件失效

### ISSUE THREAD

**Issue by explorefit** [ant-design/pro-components#4203]
### 🐛 bug 描述
在使用 ProTable 组件时，一页内容过多时，想通过antd的 BackTop 组件返回table的顶部，这个返回顶部组件失效

### 🏞 期望结果

内容过多时怎么快速回到顶部

### © 版本信息

- ProComponents 版本: @ant-design/pro-form": "1.35.0"
- umi 版本
- 浏览器环境 Google Chrome  95.0.4638.69
- 开发环境 window10

**Comment by DerrickTel** [comment]
https://codesandbox.io/s/tg2lv?file=/App.tsx

**Comment by explorefit** [comment]
> https://codesandbox.io/s/tg2lv?file=/App.tsx

![image](https://user-images.githubusercontent.com/24665389/145000957-dba19440-3e97-4441-8fac-e01555d077c7.png)
我使用的antdpro的内容区的滚动条在一个容器里了，和官网的不一样，这个滚动条没在页面外层的容器中，不知道为什么会变为这样的
