### ISSUE TITLE
prolist 卡片列表的 actions 和 extra 不能同时存在吗？怎样设置extra🧐[问题]

### ISSUE THREAD

**Issue by zf12322222131231231** [ant-design/pro-components#4204]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
| 参数 | 说明 | 类型 | 默认值 |
| :-- | :-- | :-- | :-- |
| itemCardProps | 自定义卡片列表的 proCard props，只在卡片列表下生效 | - | - |


用这个 API吧

**Comment by zf12322222131231231** [comment]
![image](https://user-images.githubusercontent.com/95677884/145162146-d0d66b1d-acc6-43b4-998f-d03013cb105d.png)
这样写不对，要怎样使用呢？

**Comment by chenshuai2144** [comment]
看看 antd 试试

**Comment by zf12322222131231231** [comment]
设置 itemCardProps 没有用 cardActionProps 也不能实现同时存在 action 和 extra

**Comment by chenshuai2144** [comment]
itemCardProps 可以自己设置action的。设置了就同时存在了
