### ISSUE TITLE
🐛[BUG] BetaSchemaForm 和 ProProvider.Provider 自定义的 valueTypeMap 无效

### ISSUE THREAD

**Issue by hocgin** [ant-design/pro-components#4211]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
配置自定义的 valueTypeMap 在使用的时候没有生效，分析后发现 ProProvider.Provider 设置的值没有传送到 ProProvider.Consumer 这边不清楚为什么设置没法生效。

另外，我这边是嵌套在 ProTable 的 toolBarRender 场景下失效的，如果没有嵌套的话是正常的不知道这点是否是问题产生的原因。

### 📷 复现步骤
```tsx
import React, { useContext } from 'react';
import ProProvider from '@ant-design/pro-provider';
import { BetaSchemaForm } from '@ant-design/pro-form';
import type { FormSchema } from '@ant-design/pro-form/lib/components/SchemaForm';
import {
  SchemeColumns,
  handleSchemeColumns,
} from '../scheme';

// @formatter: off
const ArchiveSchema: React.FC<FormSchema> = ({
                                               columns = [],
                                               trigger,
                                               title,
                                               onFinish,
                                               params,
                                               request,
                                               layoutType,
                                               visible,
                                               onVisibleChange,
                                             }) => {
  // @formatter: on
  const values = useContext(ProProvider);

  let value = {
    ...values,
    valueTypeMap: {
      ...SchemeColumns,
    },
  };

  return (
    <ProProvider.Provider value={value}>
      <BetaSchemaForm columns={handleSchemeColumns(columns)}
                      visible={visible}
                      layoutType={layoutType}
                      params={params}
                      title={title}
                      onVisibleChange={onVisibleChange}
                      request={request}
                      onFinish={onFinish}
                      trigger={trigger} />
    </ProProvider.Provider>
  );
};

export default ArchiveSchema;

```

```tsx

export const SchemeColumns: Record<string, ProRenderFieldPropsType> = {
  [prefix('select')]: {
    render: (text: any, props: any) => {
      console.log('select render', text, props);
      return <div>{text}</div>;
    },
    renderFormItem: (text: any, props: any) => {
      console.log('select renderFormItem', text, props);
      let params: SelectParam = props?.params || {};
      return (
        <Promise.Select multiple={params?.multiple ?? false} useAction={params.useAction} {...props?.fieldProps} />
      );
    },
  },
  // ...
};
```

### 🏞 期望结果
期望是自定义 valueTypeMap 能够正常运行。

异常点: 很奇怪，此处 Context.Consumer 无法读取到 Context.Provider 的 valueTypeMap 的配置。

#### Context.Provider
![image](https://user-images.githubusercontent.com/16535610/145000906-7d231a0c-bbab-446f-89f3-765344d184e4.png)

#### Context.Consumer
![image](https://user-images.githubusercontent.com/16535610/145000834-06618c79-8831-448d-a83a-4ca3480c88c5.png)

我这边在源码断点调试上查看变量。
![image](https://user-images.githubusercontent.com/16535610/145001959-dd3421cd-ec4a-492b-b64d-ec6b76b9d939.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
    "@ant-design/pro-descriptions": "^1.9.13",
    "@ant-design/pro-field": "^1.22.1",
    "@ant-design/pro-form": "^1.43.2",
    "@ant-design/pro-layout": "^6.25.4",
    "@ant-design/pro-table": "^2.53.1",
- umi 版本  "umi": "^3.2.27"
- 浏览器环境 Chrome
- 开发环境 mac OS

**Comment by hocgin** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [[🐛[BUG]BetaSchemaForm和ProProvider.Provider 自定义的valueTypeMap无效 #3798](https://github.com/ant-design/pro-components/issues/3798)][🐛[BUG]BetaSchemaForm和ProProvider.Provider 自定义的valueTypeMap无效][100%]
> * [[🐛[BUG]自定义valueTypeMap失败 #3874](https://github.com/ant-design/pro-components/issues/3874)][🐛[BUG]自定义valueTypeMap失败][68%]


以上 issues 我参考了，应该不是同一个问题?  我这边使用的是
```ts
import ProProvider from '@ant-design/pro-provider';
```
应该是和官方 demo 一致的。

**Comment by 1247748612** [comment]
toolBarRender 是一个函数调用

**Comment by hocgin** [comment]
> toolBarRender 是一个函数调用

你好，是通过一个组件项目把这部分代码包装为组件并发布的，在这个项目的 demo 中自定义组件是可以正常使用的。[Demo](https://ui.hocg.in/components/complex/promise-table)
然后，我另外一个开发项目在使用这个组件的时候出现了上面的异常情况。

尝试了几个方式都没处理这个问题，不知道大佬能否提供一些思路。

**Comment by 1247748612** [comment]
我试了下我这的toolBarRender是正常的

你这个可能是被覆盖了
![image](https://user-images.githubusercontent.com/29533304/145179795-2a4e0322-ce8d-47b3-a7c0-68bca384f293.png)

或者提供一个codesandbox的reproduce我看看

**Comment by hocgin** [comment]
> 我试了下我这的toolBarRender是正常的
> 
> 你这个可能是被覆盖了 ![image](https://user-images.githubusercontent.com/29533304/145179795-2a4e0322-ce8d-47b3-a7c0-68bca384f293.png)
> 
> 或者提供一个codesandbox的reproduce我看看

你好👋，刚整理出一个复现该问题的 [示例](https://codesandbox.io/s/umi-rd8oy?file=/src/pages/index.config.table.tsx)，麻烦了哈。

**Comment by chenshuai2144** [comment]
多份 antd 实例的问题，注意一下lib和 es的问题

**Comment by hocgin** [comment]
> 多份 antd 实例的问题，注意一下lib和 es的问题

你好，这个要怎么做处理呢？需要调整引入 provider 的方式吗？我目前是这么使用是不可以的？
`import ProProvider from '@ant-design/pro-provider';`

**Comment by chenshuai2144** [comment]
在source面板里看看，估计要什么检查吗。

**Comment by hocgin** [comment]
> 在source面板里看看，估计是你包装的组件有什么问题

完全按照官网的.. 这问题可太恶心了..

**Comment by 674237232** [comment]
> > 在source面板里看看，估计是你包装的组件有什么问题
> 
> 完全按照官网的.. 这问题可太恶心了..

我是头一天还好好的，第二天启动项目就不生效了，感觉像是pro-form版本的问题，现在也解决不了。

**Comment by 1247748612** [comment]
![image](https://user-images.githubusercontent.com/29533304/145523724-9efd04e0-1dac-4a3c-9eb6-4c9fd9929af6.png)

从使用的组件往上找，发现这里的context valueTypeMap为空，所以拿不到

**Comment by hocgin** [comment]
> > > 在source面板里看看，估计是你包装的组件有什么问题
> > 
> > 
> > 完全按照官网的.. 这问题可太恶心了..
> 
> 我是头一天还好好的，第二天启动项目就不生效了，感觉像是pro-form版本的问题，现在也解决不了。

提供一个思路，暂时规避该问题：
```ts
export const handleSchemeColumns = (columns: any[]): any[] => {
  return columns.map(handleSchemeColumn);
};

const handleSchemeColumn = (column: any): any => {
  // fixme 20211209: 这边是用来兼容 antd pro 组件 valueTypeMaps 不生效的问题
  let valueType = `${column?.valueType}`;
  let isCustom = valueType.startsWith(Dom.COLUMN_PREFIX);
  if (!isCustom) {
    return column;
  }
  let schemeColumn = SchemeColumns[valueType];
  column.renderFormItem = (item: any, config: any, form: any) => {
    let text = config?.value;
    return schemeColumn?.renderFormItem?.(text, item, form);
  };
  column.render = (
    dom: any,
    entity: any,
    index: number,
    action: any,
    schema: any,
  ) => {
    return schemeColumn?.render?.(
      schema?.text,
      { mode: schema?.mode, ...column },
      dom,
    );
  };
  return column;
};
```
目前我通过该方式，把函数在 columns 上挂载可以暂时规避掉读取不到 valueTypeMaps 的问题。
后面等发现 issues 问题再进行调整吧 ..

**Comment by jiaicon** [comment]
> > > 在source面板里看看，估计是你包装的组件有什么问题
> > 
> > 
> > 完全按照官网的.. 这问题可太恶心了..
> 
> 我是头一天还好好的，第二天启动项目就不生效了，感觉像是pro-form版本的问题，现在也解决不了。

我暂时用得1.46.0，没问题。可以试试，记得删package-lock.json（手贱升级了下版本，出现问题了）
