### ISSUE TITLE
🧐[问题]ProTable actionRef的reload方法传参无法回到首页

### ISSUE THREAD

**Issue by Sh0214** [ant-design/pro-components#4218]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

actionRef reload方法传true后pageInfo.current不会变为1
看源码好像目前传true之后只会清空选择
看tags protable@2.5.6中以前有resetPageIndex方法
想问下是设计有变化吗 还是我使用有误

### 🚑 其他信息
master分支上的代码
![1638934664(1)](https://user-images.githubusercontent.com/40195143/145144095-833782ab-2f7b-4f11-bcd1-806b419aefd0.jpg)
tags protable@2.5.6上的代码
![1638934734(1)](https://user-images.githubusercontent.com/40195143/145144213-7061a09f-20c0-4ee2-ac9e-ab2790b9927a.jpg)

**Comment by chenshuai2144** [comment]
```
```tsx | pure
interface ActionType {
  reload: (resetPageIndex?: boolean) => void;
  reloadAndRest: () => void;
  reset: () => void;
  clearSelected?: () => void;
  startEditable: (rowKey: Key) => boolean;
  cancelEditable: (rowKey: Key) => boolean;
}

const ref = useRef<ActionType>();

<ProTable actionRef={ref} />;

// refresh
ref.current.reload();

// Refresh and clear, the page number will also be reset, excluding the form
ref.current.reloadAndRest();

// Reset to default values, including forms
ref.current.reset();

// Clear the selected item
ref.current.clearSelected();

// start editing
ref.current.startEditable(rowKey);

// end editing
ref.current.cancelEditable(rowKey);
```


加个 true 就可以了

**Comment by Sh0214** [comment]
加true了 但是没效果所以才来问的。。

**Comment by ooPG233** [comment]
结果并没有解决问题

**Comment by Sh0214** [comment]
> 结果并没有解决问题

![image](https://user-images.githubusercontent.com/40195143/146141430-323c2b93-72f0-4d45-a5f4-0e8f6514f201.png)
这样子能解决这个问题 但是确实reload方法传参数没效果。。

**Comment by ooPG233** [comment]
> 

从源码上看这显然应该是一个bug，重新提一个issue?

**Comment by chenshuai2144** [comment]
直接来个pr吧
