### ISSUE TITLE
🧐[问题] EditableProTable 分页的时候，提交数据的时候如何检验其他行的数据，目前只能检验当前行的数据

### ISSUE THREAD

**Issue by killdada** [ant-design/pro-components#4219]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
这个估计不行，因为dom被销毁了。建议一行一行的校验。
然后在提交之前再进行整体校验

**Comment by killdada** [comment]
en ，目前看只能这样处理了，
