### ISSUE TITLE
👑 [需求]可以设置Schema Form 的某项 只读么

### ISSUE THREAD

**Issue by pxim** [ant-design/pro-components#4221]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述

![image](https://user-images.githubusercontent.com/5111701/145188114-bfbbdf33-ba4b-467d-8cf2-1bc56439ccf0.png)
![image](https://user-images.githubusercontent.com/5111701/145188163-e8ce4127-e037-454f-903c-830f1005cf73.png)

```

  {
        title: '模型名称（在max或者unity里的name）',
        dataIndex: 'title',
        valueType: 'text',
        initialValue: data.key,
        width: "m",
    },
```
可以在这里面设置 只读属性么，还有像ProField 字段的名称和值，在一行显示；
Schema Form里都是换行显示

**Comment by chenshuai2144** [comment]
配置一下 readonly 就可以了
