### ISSUE TITLE
🐛[BUG]EditableProTable 通过自定义actionRender新建一行数据，突然不支持连续创建多条数据，请问是什么原因？

### ISSUE THREAD

**Issue by yangyan123** [ant-design/pro-components#4222]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
EditableProTable 通过自定义actionRender
 <EditableProTable.RecordCreator
                      key="add"
                      newRecordType="dataSource"
                      record={{ id:Date.now()}}
                    >
                      <a>新建</a>
                    </EditableProTable.RecordCreator>
新建一行数据，突然不支持连续创建多条数据，请问是什么原因？

### 💻 复现代码

<EditableProTable
          columns={columns}
          value={dataSource}
          rowKey="id"
          actionRef={actionRef}
          scroll={{ x: 720 }}
          recordCreatorProps={false}
          onChange={setDataSource}
          editable={{
            type: 'multiple',
            editableKeys,
            actionRender: (row, config, defaultDoms) => {
              return [
                config.index === 0 ? (
                  <EditableProTable.RecordCreator
                    key="add"
                    newRecordType="dataSource"
                    record={defaultDataItem}
                  >
                    <a>新建</a>
                  </EditableProTable.RecordCreator>
                ) : (
                  defaultDoms.delete
                ),
              ];
            },
            onValuesChange: (record, recordList) => {
              console.log(record);
              setDataSource(recordList);
            },
            onChange: setEditableRowKeys,
          }}
        />

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by yangyan123** [comment]
昨天https://procomponents.ant.design/components/table/?current=1&pageSize=5挂了，跟你们发新版有关系吗？

**Comment by chenshuai2144** [comment]
是个bug，为了优化性能不小心闭包了。现在已经修复了，可以更新依赖了。

**Comment by chenshuai2144** [comment]
> 昨天https://procomponents.ant.design/components/table/?current=1&pageSize=5挂了，跟你们发新版有关系吗？


sir 挂了。已经修复了

**Comment by yangyan123** [comment]
> 
亲，更新了一下依赖，依旧不行呢

**Comment by chenshuai2144** [comment]
来个重现

**Comment by yangyan123** [comment]
`const textConfig = () => {
    // 默认数据
    const defaultData: DataSourceType[] = [
      {
        id: Date.now(),
        code: undefined,
        text: '',
      },
    ];
    const [id, setId] = useState<string>('');

    // aiAppraisalTexts
    const [editableKeys, setEditableRowKeys] = useState<React.Key[]>(() =>
      // 详情时不可编辑
      defaultData.map((item) => item.id),
    );
    // 表格数据
    const [dataSource, setDataSource] = useState<DataSourceType[]>(
      () => defaultData,
    );
    const columns: ProColumns<DataSourceType>[] = [
      {
        title: '接口返回值',
        dataIndex: 'code',
        align: 'center',
        formItemProps: {
          rules: [
            {
              required: true,
              message: '此项是必填项',
            },
          ],
        },
      },
      {
        title: '结果文案',
        dataIndex: 'text',
        align: 'center',
        formItemProps: {
          rules: [
            {
              required: true,
              message: '此项是必填项',
            },
          ],
        },
      },
      {
        title: '操作',
        width: 100,
        align: 'center',
        valueType: 'option',
        render: () => null,
      },
    ];

    // 初始化详情
    const initAiAppraisalTexts = async (obj: any) => {
      const res: any = await aiAppraisalTexts(obj);
      setId(res?.id);
      if (res?.configs) {
        setDataSource(
          res?.configs?.map((item: any, index: number) => ({
            ...item,
            id: index,
          })),
        );
        setEditableRowKeys(() =>
          res?.configs?.map((item: any, index: number) => index),
        );
      }
    };

    // 初始化详情
    const save = async () => {
      const res: any = await aiAppraisalTexts({
        method: 'PUT',
        id,
        configs: dataSource.map((item: any) => {
          return { code: item.code, text: item.text };
        }),
      });
      if (res?.code === '0' || res?.code === '200') {
        message.success('保存成功', 1.5, () => {
          setTextConfigModalVisible(false);
        });
      }
    };

    useEffect(() => {
      (async () => {
        // AI文案配置
        if (textConfigModalVisible) {
          await initAiAppraisalTexts({ method: 'GET' });
        }
      })();
    }, [textConfigModalVisible]);

    return (
      <Modal
        title="文案配置"
        destroyOnClose
        width={820}
        visible={textConfigModalVisible}
        onCancel={() => {
          setTextConfigModalVisible(false);
        }}
        onOk={async () => {
          save();
        }}
      >
        <EditableProTable
          columns={columns}
          value={dataSource}
          rowKey="id"
          actionRef={actionRef}
          scroll={{ x: 720 }}
          recordCreatorProps={false}
          onChange={setDataSource}
          editable={{
            type: 'multiple',
            editableKeys,
            actionRender: (row, config, defaultDoms) => {
              return [
                config.index === 0 ? (
                  <EditableProTable.RecordCreator
                    key="add"
                    newRecordType="dataSource"
                    record={{
                      id: Date.now(),
                      code: undefined,
                      text: '',
                    }}
                  >
                    <a>新建</a>
                  </EditableProTable.RecordCreator>
                ) : (
                  defaultDoms.delete
                ),
              ];
            },
            onValuesChange: (record, recordList) => {
              setDataSource(recordList);
            },
            onChange: setEditableRowKeys,
          }}
        />
      </Modal>
    );
  };`

**Comment by yangyan123** [comment]
![image](https://user-images.githubusercontent.com/10812007/145350615-8b8d17b8-afd5-483d-8761-5c1ceb33e5c0.png)

**Comment by yangyan123** [comment]
只能新建1条

**Comment by yangyan123** [comment]
我又实验了一把，    "@ant-design/pro-form": "^1.34.0",搭配    "@ant-design/pro-table": "^2.58.1",是可以实现新建多条的，版本不对就不行了
https://codesandbox.io/s/fragrant-river-rl52m?file=/App.tsx

**Comment by yangyan123** [comment]
![image](https://user-images.githubusercontent.com/10812007/145532892-ef79a82f-e5b8-42c0-8503-4506e7462b88.png)
两次不同时段创建的，取的Dtae.now()，是一样的，这块是不是也有问题
![image](https://user-images.githubusercontent.com/10812007/145533079-dc66ad55-ccca-444c-ac22-4c2b13cc749d.png)
都是最新的

**Comment by yangyan123** [comment]
沙盒环境和我本地展示也不同，我本地包管理是yarn

**Comment by chenshuai2144** [comment]
删除lock在试试。不好复线呀
