### ISSUE TITLE
🐛[BUG] EditableProTable新增多行时，原来新增的数据，默认变成默认值

### ISSUE THREAD

**Issue by flowerDAI** [ant-design/pro-components#4225]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
EditableProTable 新增多行时，我先添加2行，填入数据后，再点击新增一行，原来的两行数据，时间和下拉框选择的数据变成设置的默认值, 但是文本框不变。
原来都正常的，突然出现这个情况。

### 📷 复现步骤
1、 先新增2行数据，填写内容后
![1639018374740_AA0DD5A9-C7CE-46d0-8E54-E9E240E146BB](https://user-images.githubusercontent.com/25717606/145326090-810bf87e-3ff0-40bf-850d-f46940232437.png)

2、再点 “新增一行” ，原来两行的数据，红框内的数据自动变成默认值了
![1639018406384_F8938F7F-8DF3-4580-B648-8784E7FC0DC0](https://user-images.githubusercontent.com/25717606/145326249-42826138-ff80-434e-b904-280e7288e23f.png)

### 🏞 期望结果

期望原来的数据保持不变

### 💻 复现代码

#
<EditableProTable   

        id={'id'}
        key={`id`}
        rowKey={'id'}
        bordered={true}
        form={{ignoreRules:false}}
        formRef={formRef}  
        defaultSize={'small'}
        actionRef={actionType}
        columns={columns}
        components={components}
        columnsStateMap={columnsStateMap}
        onColumnsStateChange={(map) => {
          setColumnsStateMap(map);
        }}
        options={{}}
        search={{
          filterType: 'light',
        }}
        request={async (params, sort, filter) => {       
          try {        
            const { data, total, success } = await GetList(
              {...params })
            return {
              data:data,
              success:success,
              total:total
            }
          }catch (e) {
            message.error("查询失败")
            return {}
          }
        }}
        pagination={{
          pageSize: 20,
        }}
        expandable={{
          expandedRowRender: (props) => <ExpandTable {...props} />
        }}
        controlled={true}
        editable={{
          type: 'multiple',
          form:editBillForm,
          editableKeys,
          actionRender:(row, config, defaultDom)=>{
            return [defaultDom.save,defaultDom.delete];
          },
          onSave: (rowKey, data, row) => {
            return handleSaveSingle(rowKey, data, row);
          },
          onChange: (editableKeys, editableRows)=>{
            return  setEditableRowKeys(editableKeys);
          },
        }}
        recordCreatorProps={
          Number(cardId.current) > 0
            ? {
              newRecordType: 'dataSource',
              record: () => ({
                id: (Math.random() * -1000000).toFixed(0),
                billDate: moment(new Date()).format('YYYY-MM-DD HH:mm:ss'),
                billIncome:0,
                billPay:0,
                reasonType:"1",
                accId:0,
                accRemarks:0,
              }),
            } : false
        }
      />

#

### © 版本信息

- ProComponents 版本:   ["@ant-design/pro-table": "^2.59.2"]  
- umi 版本     :  ["umi": "^3.5.20",]
- 浏览器环境    ：[谷歌浏览器]
- 开发环境 [e.g. mac OS]  ： [window]

**Comment by chenshuai2144** [comment]
修复了
是闭包的问题。更新依赖重新安装就能解决

**Comment by flowerDAI** [comment]
我更新了包，不过还是这样

**Comment by flowerDAI** [comment]
> 修复了 是闭包的问题。更新依赖重新安装就能解决

我更新了包，不过还是这样

**Comment by chenshuai2144** [comment]
来个重现
