### ISSUE TITLE
🐛[BUG] DatePicker在Protable里面无不能选中

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-components#4226]
1:codesandbox地址：https://codesandbox.io/s/datepickerzai-bsictableli-mian-wu-bu-neng-xuan-zhong-25j03?file=/index.tsx

打开地址，在search 的选项里面日期不能选择，但是把{...rest}取消就可以了。。这个代码我们一直都没该过。现在为什么现在不行了。是不是升级出现了BUG。

```
     <DatePicker
          {...rest}
          allowClear
          showTime={{
            hideDisabledOptions: true
          }}
          format="YYYY-MM-DD HH:mm:ss"
        />
```

**Comment by chenshuai2144** [comment]
{...rest} 里面是不是放了 value 了。

**Comment by xgj1988** [comment]
这个是参考官网的例子。就加了一个renderItem，其他什么都没动。

**Comment by chenshuai2144** [comment]
不要设置value就可以了。

**Comment by xgj1988** [comment]
没有设置value 啊

**Comment by chenshuai2144** [comment]
rest 里面有 pick 出来

**Comment by xgj1988** [comment]
关键是以前我代码都好好的。。没动过。今天就不行了。。
