### ISSUE TITLE
日期时间区间搜索👑 [需求]

### ISSUE THREAD

**Issue by Venus-WXP** [ant-design/pro-components#423]
### 🥰 需求描述

数据字段是一个日期或者日期时间类型，那么，正常的表格展示是日期或日期时间字符串，那么搜索表单需要使用日期或日期时间范围搜索，而更新表单则依旧使用普通的日期或日期时间进行选择填写。这个需求该如何实现？

### 🧐 解决方案

可以分别给搜索表单和更新表单对应字段不同于表格的类型（表格中是valueType），这样可以解决，但是这个只是个别字段需求，那么让组件默认情况下使用和表格中指定的类型一样的表单控件，当有需求时可以分别在search表单和update表单分别指定类型，就类似：hideInSearch、hideInForm、hideInTable，指定：searchValueType、formValueType

### 🚑 其他信息

谢谢！！！

**Comment by chenshuai2144** [comment]
valueType 支持function ，你用function 就可以了

**Comment by goodve** [comment]
> valueType 支持function ，你用function 就可以了
> 
> 不然枚举不完，为了可能有很多的，比如 list cardlist

`export declare type ProFieldValueTypeFunction<T> = (item: T) => ProFieldValueType | ProFieldValueObjectType;`

这个函数的参数 没办法判断 item 是在table里 还是 form，search 里

**Comment by Venus-WXP** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    谢谢哈
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2929923469
                            
                    
                        
                            
                                    2929923469@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年09月9日 17:40，goodve<notifications@github.com> 写道： 






valueType 支持function ，你用function 就可以了

不然枚举不完，为了可能有很多的，比如 list cardlist



export declare type ProFieldValueTypeFunction<T> = (item: T) => ProFieldValueType | ProFieldValueObjectType;

这个函数的参数 没办法判断 item 是在table里 还是 form，search 里



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by goodve** [comment]
> valueType 支持function ，你用function 就可以了
> 
> 不然枚举不完，为了可能有很多的，比如 list cardlist

![image](https://user-images.githubusercontent.com/17634299/92671763-ab47e800-f349-11ea-8e55-6508e1f245ab.png)
2.7.1  的  valueType  方法好像是没有实现的 ？？？

**Comment by itsuki0927** [comment]
@goodve 它的实现在`defaultRenderText`.

正如你所说在如果是函数的话, 在formInputRender 将valueType置为`{}`,然后结合下面的代码就好理解了.

```tsx
const defaultRenderText = ()=>{
  if (typeof valueType === 'object') {
    return defaultRenderTextByObject(text, valueType, props);
  }
}

```

**Comment by Venus-WXP** [comment]
> > valueType 支持function ，你用function 就可以了
> > 不然枚举不完，为了可能有很多的，比如 list cardlist
> 
> `export declare type ProFieldValueTypeFunction<T> = (item: T) => ProFieldValueType | ProFieldValueObjectType;`
> 
> 这个函数的参数 没办法判断 item 是在table里 还是 form，search 里

请问找到解决办法了吗？我也不知道在函数中如何区分是table、form还是search

**Comment by chenshuai2144** [comment]
valueType 支持function ，参数中会传出来
