### ISSUE TITLE
🧐[问题]自定义的valueType不生效，renderFormItem不会执行

### ISSUE THREAD

**Issue by 674237232** [ant-design/pro-components#4231]
### 🧐 问题描述

_不好意思，刚才填错了tag。_
使用ProProvider.Provider 和 BetaSchemaForm 的自定义valueType时，定义的函数不生效，渲染成了默认的Text输入框。
昨天在测试的时候是可以的，可以正常渲染出想要的表单组件，今天早上打开项目就不生效了，不知道是不是我组件版本的问题。
<br />
简单做了一个示例，renderFormItem没有执行，控制台没有输出
### 💻 示例代码
```javascript
import { memo, useContext } from "react";

import { Button } from "antd";
import { PlusOutlined } from "@ant-design/icons";
import ProProvider from "@ant-design/pro-provider";
import { BetaSchemaForm } from "@ant-design/pro-form";

const CreateRecordModal = memo((props) => {
  const values = useContext(ProProvider);

  const columns = [
    {
      title: "你好啊",
      dataIndex: "test",
      valueType: "upload",
    },
  ];

  return (
    <ProProvider.Provider
      value={{
        ...values,
        valueTypeMap: {
          upload: {
            renderFormItem(text, props) {
              console.log(props);
              console.log("渲染自定义valueType");
              return <Button>上传按钮</Button>;
            },
          },
        },
      }}
    >
      <BetaSchemaForm
        columns={columns}
        layoutType="ModalForm"
        title="新增记录"
        layout="horizontal"
        labelCol={{ span: 5 }}
        trigger={
          <Button type="primary" shape="round">
            <PlusOutlined />
            新建
          </Button>
        }
        autoFocusFirstInput
        modalProps={{ destroyOnClose: true, maskClosable: false, width: 700 }}
      />
    </ProProvider.Provider>
  );
});

export default CreateRecordModal;

```

### 🚑 其他信息
ProComponents版本信息
![image](https://user-images.githubusercontent.com/39240626/145329874-ae349709-f413-4ae1-a989-443aa7aa45ec.png)
效果
![image](https://user-images.githubusercontent.com/39240626/145330218-9f497f46-703a-494e-8485-cc12d5c2d171.png)

**Comment by chenshuai2144** [comment]
一般都是lib和 es 打包了两份的问题

**Comment by 674237232** [comment]
不是啊大哥，不太明白你的意思，我应该怎么做才能正常渲染呢

**Comment by 674237232** [comment]
```javascript
```

**Comment by 674237232** [comment]
```javascript
import ProProvider from "@ant-design/pro-provider";
import { BetaSchemaForm } from "@ant-design/pro-form";
```
这个不是es引入吗，没有引入过lib下的文件，应该不是这个问题吧

**Comment by chenshuai2144** [comment]
打开source 面板看看

**Comment by 674237232** [comment]
> 打开source 面板看看

我不是很明白，是Chrome的source吗
![image](https://user-images.githubusercontent.com/39240626/145357109-8e96a977-c56a-41dc-a531-ef5d293d6ef0.png)
![image](https://user-images.githubusercontent.com/39240626/145357178-b024da2e-ae87-46be-a4e7-b5cadfb30a86.png)

**Comment by 674237232** [comment]
![image](https://user-images.githubusercontent.com/39240626/145358075-dc506907-8e01-4e63-9e92-560afc2404d8.png)
搜了一下，没有从lib下引入的组件

**Comment by chenshuai2144** [comment]
是 react 的 devtools

**Comment by 0fan** [comment]
我也遇到了这个问题，BetaSchemaForm和ProDescriptionsProps组件不生效

**Comment by CREATE-AI** [comment]
+1

**Comment by xiaomansjw** [comment]
+1

**Comment by stznsln-damn** [comment]
把pro-form和pro-provider升级到最新版本之后问题解决了，看来是版本的问题

**Comment by stznsln-damn** [comment]
pro-form版本：1.50.0

pro-provider版本：1.5.4
![image](https://user-images.githubusercontent.com/39240626/150498990-628b2851-c889-4b43-b25a-e64cc372351b.png)
![image](https://user-images.githubusercontent.com/39240626/150499039-98dd67b7-02bc-410d-b37a-0f9e9e8b3fe9.png)
