### ISSUE TITLE
ProTable的搜索输入框实现onChange和value之后，无法使用撤销（command/ctrl+z）获得上一次输入的内容🐛[BUG]

### ISSUE THREAD

**Issue by colorbeach** [ant-design/pro-components#4232]
### 🐛 bug 描述

正常情况下，输入框先输入123，过两秒后输入456，那么最终结果是123456，此时撤销(command+z)，会使结果变成123。
在ProTable中定义了输入框搜索域之后，如果在filedProps中同时实现了onChange和value方法，发现就无法撤销了。

### 💻 复现代码
const [username, setUsername] = useState();
搜索的column定义如下：
{
            title: '用户名',
            dataIndex: 'username',
            fieldProps: {
                onChange: (e) => {
                    setUsername(e.target.value.replace(/\s+/g, ""));
                },
                value: username
}

### © 版本信息

- chrome浏览器
- mac OS 11.6
- @ant-design/pro-table: ^2.26.1
- @ant-design/pro-form: ^1.13.7,
- antd: ^4.17.0-alpha.7,
- react: ^17.0.1,

**Comment by colorbitch** [comment]
> c提问前先看看：
> 
> https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
> 
> ### 🐛 bug 描述
> 正常情况下，输入框先输入123，过两秒后输入456，那么最终结果是123456，此时撤销(command+z)，会使结果变成123。 在ProTable中定义了输入框搜索域之后，如果在filedProps中同时实现了onChange和value方法，发现就无法撤销了。
> 
> ### 💻 复现代码
> const [username, setUsername] = useState(); 搜索的column定义如下： { title: '用户名', dataIndex: 'username', fieldProps: { onChange: (e) => { setUsername(e.target.value.replace(/\s+/g, "")); }, value: username }
> 
> ### © 版本信息
> * chrome浏览器
> * mac OS 11.6
> * @ant-design/pro-table: ^2.26.1
> * @ant-design/pro-form: ^1.13.7,
> * antd: ^4.17.0-alpha.7,
> * react: ^17.0.1,

后面用codesandbox试了一下，居然是好的。

用Safari尝试，结果和Chrome不太一样。Safari在失去输入框焦点之后，无论是否实现value和onChange方法，都无法撤销；而存在焦点时，仅不实现value和onChange才能撤销。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这可能是浏览器的一个bug，不同的浏览器可能会有不同的表现。不过，可以尝试在ProTable的搜索框中使用React-Redux或Context API来管理搜索框的值，避免直接通过useState进行状态管理。这样做可以避免浏览器和React之间的差异导致的问题。

具体地，可以创建一个全局的搜索框状态管理，将搜索框的值作为状态的一部分，然后将这个状态提供给ProTable的搜索框组件。这样，即使在失去焦点之后也能够保留搜索框的值，并可以通过Redux DevTools等工具来调试问题。

下面是代码示例：

```jsx
// 搜索框状态管理
import { createContext, useContext, useReducer } from 'react';

const SearchContext = createContext();

export function SearchProvider({ children }) {
  const [state, dispatch] = useReducer(
    (prevState, action) => {
      switch (action.type) {
        case 'SET_KEYWORD':
          return { ...prevState, keyword: action.payload };
        default:
          return prevState;
      }
    },
    { keyword: '' }
  );

  return (
    <SearchContext.Provider value={{ state, dispatch }}>
      {children}
    </SearchContext.Provider>
  );
}

export function useSearch() {
  return useContext(SearchContext);
}

// 使用搜索框
import { useSearch } from './search';

// ...

const { state, dispatch } = useSearch();
const handleChange = e => {
  dispatch({ type: 'SET_KEYWORD', payload: e.target.value.replace(/\s+/g, '') });
}

return (
  <ProTable
    // ...
    columns={[
      // ...
      { 
        title: '用户名', 
        dataIndex: 'username',
        fieldProps: { onChange: handleChange, value: state.keyword }
      },
      // ...
    ]}
    // ...
  />
);
``` 

需要注意，该代码可能需要调整你的现有代码，特别是在组件层次结构方面。
