### ISSUE TITLE
👑 [需求]ModalForm 和 DrawerForm支持Schema Form 

### ISSUE THREAD

**Issue by jianghanyue** [ant-design/pro-components#4233]
### 🥰 需求描述
在ModalForm 和 DrawerForm里面写长串的数据感觉不大优雅，可不可以在里面实现Schema Form ，通过传入json数据生成表单

### 🧐 解决方案
我可以提交PR

**Comment by chenshuai2144** [comment]
欢迎！

**Comment by 674237232** [comment]
Schema Form 可以配置 layoutType 为 modal、抽屉、步骤表单等等。

**Comment by jianghanyue** [comment]
> Schema Form 配置layoutType 为modal、表单、步骤表单等。

找到解决办法了，感谢！
