### ISSUE TITLE
🧐[问题]  pro table  配置了搜索项，如何不让搜索值默认添加到url的params中？

### ISSUE THREAD

**Issue by dataknower** [ant-design/pro-components#4234]
![image](https://user-images.githubusercontent.com/19550451/145341435-37d2b626-253b-4574-899d-bc9301cb0dc8.png)
url不需要拼接这些params,因为完全是走的service的api

**Comment by chenshuai2144** [comment]
syncToUrl | 同步参数到 url 上,url 只支持 string，在使用之前最好读一下url 中的参数类型 | true \| (values,type)=>values | -
-- | -- | -- | --




设置成false

**Comment by dataknower** [comment]
thx
