### ISSUE TITLE
🧐[问题]protable 的包没做兼容处理，低版本浏览器一堆es6 语法无法解析报错

### ISSUE THREAD

**Issue by zhangxiangqiang** [ant-design/pro-components#4239]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
protable 的包没做兼容处理，低版本浏览器（360）一堆es6 语法无法解析报错， 想flatMap, flat 等方法都没做兼容处理；线上一堆用户报错，有什么好的办法可以处理下这个问题么？希望大佬给点建议

### 💻 示例代码
使用protable就报错

### 🚑 其他信息
"@ant-design/pro-table": "2.56.3",

**Comment by chenshuai2144** [comment]
你的项目没有配置 profill吗？

**Comment by zhangxiangqiang** [comment]
> 你的项目没有配置 profill吗？

之前一直做甲方，不用考虑兼容性，忽然变成乙方，要兼容低版本浏览器有点不适应。求助一下帅哥，对于第三方包如何做profill，因为我无法确定哪个包用了什么新语法或者新api, 想来也不能每个包我都去在用babel 处理一下，因为包太多了。

这边有几个初步想法(webpack 这块是薄弱项，还没来及试试行不行)，请帅哥指点一下：

1. 第一种想法，我只对protable 进行再编译（类似下面这样，用babel处理一下），不过这种有局限性，万一别的包用了新api，项目还是有隐患
```
{
              test: require.resolve('@ant-design/pro-table'), 
              use: []
            },
```
2. 第二种想法，我在项目里直接引入整个profill的包，不过这样会让最终的项目体积变大; 
3. 第三种想法，由于项目是用的微应用架构，我在主应用的最终html里，用链接方式直接引入整个 profill的包

以上是我的初步想法，有可能解决目前遇到的问题，隐患就是profill 只能解决新api问题，万一因为新语法报错，还是处理不了。

帅哥有什么建议没

**Comment by chenshuai2144** [comment]
不行就直接用webpack 编译一下整个 nodeMoudles
