### ISSUE TITLE
🐛[BUG]ProTable的columns属性render键，会渲染很多次

### ISSUE THREAD

**Issue by ZYyyh-cool** [ant-design/pro-components#4240]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤
<ProTable
request={async (params: any) => {
        const result = await 接口()
        result?.data?.forEach((i: any, e: any) => {
          i.key = i.id
        });
        return Promise.resolve({
          data: result?.data || [],
          success: result?.status === 'success' ? true : false,
          total: result?.data?.total
        });
      }}
 columns={  {
      title: '操作',
      search: false,
      render: (_, row: any) => {
console.log(row); //数据越多渲染越多次，影响性能
}}
/>

### 🏞 期望结果
希望能优化，只渲染一次

### © 版本信息

- ProComponents 版本: 2.56.3
- umi 版本3.5.0
- 浏览器环境 
- 开发环境 Win10

**Comment by chenshuai2144** [comment]
那怎么可能，如果不是每行渲染一次，岂不每次都一样

**Comment by cuicuiworld** [comment]
请问一下你这个问题解决了吗？我也遇到这个问题了。。。有多少条数据就渲染多少次。
