### ISSUE TITLE
🐛[BUG]ProList expandable renderItem 同时用 expandable 展开会失效

### ISSUE THREAD

**Issue by mayday7** [ant-design/pro-components#4242]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

* ProList expandable renderItem 同时用 expandable 展开会失效，如下图
* 用了renderItem  样式会乱，如下图
* 不支持List的header，下图写了header，确没有渲染出来
 
![image](https://user-images.githubusercontent.com/17946590/145546833-90c1c6fd-bd8b-48e2-a541-2641d3cd0c78.png)

### 🏞 期望结果

想做一个支持展开项同时类似于表格样式的可滚动加载列表，列表字段比较多。用List组件样式是正常的（renderItem ，header都是正常显示的），但是List不支持expandable展开项配置

### 💻 复现代码
https://codesandbox.io/s/jia-zai-geng-duo-antd-4-17-3-forked-r1qj1?file=/index.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]"@ant-design/pro-list": "^1.13.2",
- umi 版本 "umi": "^3.5.0",
- 浏览器环境 谷歌浏览器版本 94.0.4606.61
- 开发环境 [e.g. mac OS] window10
 
### 🚑 其他信息

下图为用List的效果
![image](https://user-images.githubusercontent.com/17946590/145547866-0f36f048-4b40-4db5-85e4-62a7874b612c.png)

**Comment by chenshuai2144** [comment]
renderItem  就是要全部自定义，

你用 itemHeaderRender 试试
