### ISSUE TITLE
🧐[问题]ProFormText 组件 initialValue 设置currentRow 每次操作之后 再次从其他行打开 还是上次操作的值，能否像 input的value一样 选中哪行显示哪行

### ISSUE THREAD

**Issue by dlzxiaoming** [ant-design/pro-components#4244]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by dlzxiaoming** [comment]
ProFormText initialValue 默认值问题

**Comment by chenshuai2144** [comment]
initialValue 只有第一次生效，你要是需要一直设置最好每次都reset一下

**Comment by wanglihuaya** [comment]
Modal 加上 destroyOnClose: true
