### ISSUE TITLE
🐛[BUG]]在EditableProTable中添加子项，子项可以添加成功 不过添加的子项不能继续添加子项 parentKey不生效。

### ISSUE THREAD

**Issue by superAo005** [ant-design/pro-components#4246]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
希望实现添加子项的功能，子项可以添加子项的子项 不过添加的子项不能继续添加子项 parentKey不生效。

刚刚接触EditableProTable，希望实现点击添加子项。但是无论是action?.addEditRecord还是EditableProTable.RecordCreator其中的parentKey都不生效，添加子项过后 添加的子项不能自己添加子项

### 📷 复现步骤
[](url)

### 🏞 期望结果
在行后有“添加子项”按钮，点击后在该项下创建一个新的子项 新的子项可以继续添加子项

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
附上我在codesandbox上的测试：
https://codesandbox.io/s/bian-ji-you-zi-lie-de-biao-ge-bb2c2?file=/App.tsx

![image](https://user-images.githubusercontent.com/22334521/145565028-94ef7876-f9d1-4cfd-868e-0eb98095efca.png)

**Comment by chenshuai2144** [comment]
试了下你的demo是可以的。

**Comment by superAo005** [comment]
大佬我的意思是 添加的子项可以继续添加子项的子项 也就是多层嵌套 目前是通过修改dataSource来实现

**Comment by chenshuai2144** [comment]
只要key是对的，是可以的

**Comment by liushan-github** [comment]
无意中发现，把bottom改成top可行
![image](https://user-images.githubusercontent.com/45805157/146731866-d3a9fe22-0a88-4c87-b1f5-a7de4a108184.png)

![image](https://user-images.githubusercontent.com/45805157/146731760-b2a4b428-d305-4453-ba7e-0dc2ace27057.png)

**Comment by agileago** [comment]
@chenshuai2144 postion: bottom 是二级子项不能再添加子项了

**Comment by dengrujie** [comment]
将@ant-design/pro-table和antd升级版最新版就可以了

**Comment by q389491729** [comment]
这个bug有进展吗
