### ISSUE TITLE
🐛[BUG] 动态路由下出现内存泄漏

### ISSUE THREAD

**Issue by pincman** [ant-design/pro-components#4248]
### 🐛 bug 描述

目前路由根据登录和权限来生成配置后再一次性渲染，比如这样
```tsx
export const RouterWrapper: FC = () => {
    const { generated } = useRouter();
    useEffect(() => {
        console.log(`generated: ${generated}`);
    }, [generated]);
    return generated ? <RouterInit /> : <div>加载中{`${generated}`}</div>;
};
export const Router = <T extends Record<string, any>>({ config }: { config: RouterConfig<T> }) => {
    useSetupRouter<T>(config);
    useSetupMenu();
    return <RouterWrapper />;
};
export const RouterInit: FC = () => {
    const {
        config: { basePath: basename, hash, window },
        renders,
    } = useRouter();
    return hash ? (
        <HashRouter {...{ window, basename }}>
            <RoutesList routes={renders} />
        </HashRouter>
    ) : (
        <BrowserRouter {...{ window, basename }}>
            <RoutesList routes={renders} />
        </BrowserRouter>
    );
};
```
但是在更改顶层App组件的时候出现重复渲染导出内存泄漏的警告
```
react_devtools_backend.js:2540 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at PageHeader2 (http://localhost:3100/node_modules/.vite/chunk-NJUUKFDW.js?v=4dc8f2bc:5141:33)
    at div
    at ProPageHeader2 (http://localhost:3100/node_modules/.vite/@ant-design_pro-layout.js?t=1639163759505&v=4dc8f2bc:4384:45)
    at div
    at PageContainer2 (http://localhost:3100/node_modules/.vite/@ant-design_pro-layout.js?t=1639163759505&v=4dc8f2bc:4427:24)
   ...
    at Loadable
    at RoutesList (http://localhost:3100/src/components/Router/provider.tsx?t=1639164004509:22:3)
    at Router (http://localhost:3100/node_modules/.vite/react-router-dom.js?v=4dc8f2bc:428:15)
    at BrowserRouter (http://localhost:3100/node_modules/.vite/react-router-dom.js?v=4dc8f2bc:961:5)
    at RouterInit (http://localhost:3100/src/components/Router/provider.tsx?t=1639164004509:40:7)
```
应该是组件内部某个`setState`导致的，请修复一下

### 📷 复现步骤

使用react router v6版本，通过一个`generated`值来控制路由生成

### 🏞 期望结果

当前不影响使用，但是会比较难受，希望修复

### © 版本信息

- ProComponents 版本: [6.31.5]
- umi 版本: vite
- 浏览器环境: chrome
- 开发环境: macos

### 🚑 其他信息

...

**Comment by wangzhaoqiang** [comment]
请问如何解决的，我也遇到这个问。

**Comment by chenshuai2144** [comment]
这个要自己处理了，这个的意思是组件卸载后你也进行setState 了

**Comment by pincman** [comment]
@chenshuai2144 @wangzhaoqiang 已经解决了，这个问题是由于pro layout会自己修改传入的route,非常奇怪,使用react router v5正常,v6因为不兼容就会这样,目前的解决办法是自己写个路由+菜单功能,然后pro layout只用来加载菜单` menuDataRender={() => menus}`,这样就Ok了
建议早点升级到v6

**Comment by wangzhaoqiang** [comment]
@pincman 
我在pro中将"@umijs/route-utils"升级为"@umijs/route-utils": "^2.0.3"，就不在出现这个错误了，但是由于我对react属于初级阶段，不是太明白原因。

`{
  "name": "ant-design-pro",
  "version": "5.0.0",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
  "scripts": {
    "analyze": "cross-env ANALYZE=1 umi build",
    "build": "umi build",
    "deploy": "npm run build && npm run gh-pages",
    "dev": "npm run start:dev",
    "gh-pages": "gh-pages -d dist",
    "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
    "postinstall": "umi g tmp",
    "lint": "umi g tmp && npm run lint:js && npm run lint:style && npm run lint:prettier && npm run tsc",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src && npm run lint:style",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "prettier -c --write \"src/**/*\" --end-of-line auto",
    "lint:style": "stylelint --fix \"src/**/*.less\" --syntax less",
    "openapi": "umi openapi",
    "precommit": "lint-staged",
    "prettier": "prettier -c --write \"src/**/*\"",
    "serve": "umi-serve",
    "start": "cross-env UMI_ENV=dev umi dev",
    "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev umi dev",
    "start:no-mock": "cross-env MOCK=none UMI_ENV=dev umi dev",
    "start:no-ui": "cross-env UMI_UI=none UMI_ENV=dev umi dev",
    "start:pre": "cross-env REACT_APP_ENV=pre UMI_ENV=dev umi dev",
    "start:test": "cross-env REACT_APP_ENV=test MOCK=none UMI_ENV=dev umi dev",
    "pretest": "node ./tests/beforeTest",
    "test": "umi test",
    "test:all": "node ./tests/run-tests.js",
    "test:component": "umi test ./src/components",
    "tsc": "tsc --noEmit"
  },
  "lint-staged": {
    "**/*.less": "stylelint --syntax less",
    "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
    "**/*.{js,jsx,tsx,ts,less,md,json}": ["prettier --write"]
  },
  "browserslist": ["> 1%", "last 2 versions", "not ie <= 10"],
  "dependencies": {
    "@ant-design/charts": "^0.9.4",
    "@ant-design/icons": "^4.5.0",
    "@ant-design/pro-descriptions": "^1.6.8",
    "@ant-design/pro-form": "^1.18.3",
    "@ant-design/pro-layout": "^6.15.3",
    "@ant-design/pro-table": "^2.30.8",
    "@antv/data-set": "^0.11.0",
    "@antv/l7": "^2.3.7",
    "@antv/l7-maps": "^2.3.7",
    "@antv/l7-react": "^2.1.9",
    "@umijs/route-utils": "^2.0.3",
    "ahooks": "^2.0.0",
    "antd": "^4.14.0",
    "bizcharts": "^3.5.3-beta.0",
    "bizcharts-plugin-slider": "^2.1.1-beta.1",
    "classnames": "^2.2.6",
    "gg-editor": "^2.0.2",
    "lodash": "^4.17.11",
    "lodash-decorators": "^6.0.0",
    "moment": "^2.25.3",
    "numeral": "^2.0.6",
    "nzh": "^1.0.3",
    "omit.js": "^2.0.2",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-fittext": "^1.0.0",
    "react-helmet-async": "^1.0.4",
    "react-router": "^4.3.1",
    "umi": "^3.5.0",
    "umi-serve": "^1.9.10"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.0.2",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.144",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.6.2",
    "@umijs/openapi": "^1.1.14",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.1",
    "@umijs/plugin-openapi": "^1.2.0",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-dumi": "^1.1.7",
    "@umijs/preset-react": "^1.8.17",
    "@umijs/yorkie": "^2.0.3",
    "carlo": "^0.9.46",
    "compression-webpack-plugin": "^9.0.1",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "enzyme": "^3.11.0",
    "eslint": "^7.1.0",
    "express": "^4.17.1",
    "gh-pages": "^3.0.0",
    "js-cookie": "^3.0.1",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.3.2",
    "puppeteer-core": "^8.0.0",
    "stylelint": "^13.0.0",
    "typescript": "^4.2.2"
  },
  "engines": { "node": ">=10.0.0" },
  "gitHooks": { "commit-msg": "fabric verify-commit" }
}
`

**Comment by pincman** [comment]
@wangzhaoqiang umi太不灵活了，大项目求稳还是不错的，不过中小型项目可以尝试一下vite,很轻量实用

**Comment by zhenyu-dev** [comment]
> 于我对react属于初级阶

我项目是2.2.2仍然有这个问题
