### ISSUE TITLE
🐛[BUG] useDebounceFn导致columns中的request没有执行

### ISSUE THREAD

**Issue by 1247748612** [ant-design/pro-components#4252]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

> 在ProDescription中columns配置了request，有8个配置了request方法的column会执行其中1~3个配置的request方法

使用方式：
```
<PageContainer onBack={history.goBack} loading={isLoading}>
      <ProDescriptions
        dataSource={data}
        title="..."
        column={{ xs: 1, md: 2 }}
        columns={infoColumns}
      />
</PageContainer>
```

> 当我把PageContainer去掉，成功执行的request达到7个，还是会有不执行的情况

没在codesandbox复现成功

### 总结

> useDebounceFn返回了一个一直处于pending状态的promise，导致SWR一直复用这个请求，一直没调用request方法

### 排查

所有request最终都会在useFieldFetchData中请求

https://github.com/ant-design/pro-components/blob/8e907d8bbe48848c37e8ce1d5a584880e181f250/packages/field/src/components/Select/index.tsx#L253-L379

使用了SWR进行接口缓存，会执行第二个参数的方法

https://github.com/ant-design/pro-components/blob/8e907d8bbe48848c37e8ce1d5a584880e181f250/packages/field/src/components/Select/index.tsx#L314-L331

到这里，我发现fetchData一开始是只要有request都会执行一次，在此之后都没被执行了，应该是SWR缓存了
fetchData虽然被执行了，但是我传入的request并没有被执行调用，那原因可能就在fetchData中了。fetchData返回了一个promise，但这个结果promise自始至终都处于pending状态。

这个fetchData是useDebounceFn包裹的，返回了一个promise，promise的结果就是request执行的结果

https://github.com/ant-design/pro-components/blob/8e907d8bbe48848c37e8ce1d5a584880e181f250/packages/field/src/components/Select/index.tsx#L302-L312

useDebounceFn实现
https://github.com/ant-design/pro-components/blob/8e907d8bbe48848c37e8ce1d5a584880e181f250/packages/utils/src/hooks/useDebounceFn/index.ts#L22-L67

useDebounceFn内部实现返回了一个Promise，其中resolve是在setTimout内部中调用的，没被执行的话也就是cancel被执行了，调用了clearTimeout导致fetchData一直处于pending状态

有3个地方调用了cancel
1. promise内部，debounce的关键，取消上一个请求
2. useUpdateEffect的返回值，deps变动会执行
3. useEffect(() => cancel, []); 中执行

这三个地方都会导致fetchData处于pending状态，在其他使用场景下可能不会有影响，在SWR下问题就大了
同一个key下，返回的结果是一个自始至终都处于pending状态的promise，在SWR下次要执行fetcher方法时，[此key有正在执行的promise，就会复用上一次调用的promise](https://github.dev/vercel/swr/blob/b78937ffd6b732003a79d7566f0a3822b939bd52/src/use-swr.ts#L139-L142)，永远不会有结果出现

### workaround

只要SWR的key不是一样的就不会复用上次的请求，在params给随机参数

### 🏞 期望结果

正常执行request

### © 版本信息

latest

**Comment by chenshuai2144** [comment]
分析的很正确，我默认不clear掉缓存了。这样也可以稍微优化下性能
