### ISSUE TITLE
🐛[BUG] pro-table filters placeholder 没有国际化。

### ISSUE THREAD

**Issue by conviva-zyang** [ant-design/pro-components#4255]
### 🐛 bug 描述
umi脚手架，使用pro-table，在config.js中配置了locale为英语，但是table filters里的placeholder还是中文。

### 📷 复现步骤
`
#config/config.ts
locale: {
    default: 'en-US',
    antd: true,
  },
 `
 table用官方文档最简单table

### 🏞 期望结果
与[文档](https://procomponents.ant.design/components/table#%E5%9B%BD%E9%99%85%E5%8C%96%E7%9B%B8%E5%85%B3%E7%9A%84%E9%85%8D%E7%BD%AE)中国际化效果一样 

### 💻 复现代码
![image](https://user-images.githubusercontent.com/44760558/145761579-c204d204-17ef-4f73-83ec-01425065be72.png)

### © 版本信息

- ProComponents 版本: "@ant-design/pro-table": "^2.59.10"
- umi 版本: "umi": "^3.5.20"
- 开发环境：mac os

### 🚑 其他信息
文档中效果：
![image](https://user-images.githubusercontent.com/44760558/145761672-a4a7f5fd-c167-41bc-821e-a286b58e45be.png)

**Comment by chenshuai2144** [comment]
一般都是多份 antd 实例的问题。用devtool检查一下

**Comment by conviva-zyang** [comment]
就是一份antd啊，最简单的一个umi demo项目

**Comment by iceycc** [comment]
国际化设置无刷新切换到时候，默认的placeholder文案不会变。刷新页面就生效了
