### ISSUE TITLE
🧐[问题] 只要页面出错就会进入Something went wrong 页面，pro里自带的这个错误提示页面有办法自定义么？

### ISSUE THREAD

**Issue by zhangxiangqiang** [ant-design/pro-components#4256]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
只要页面出错就会进入Something went wrong 页面，pro里自带的这个错误提示页面有办法自定义么？

并且我只是在页面用了下，ProTable 组件，没有用ProLayout。

这个页面虽然防止了白屏，但是一出错，就是明明白白的，前端崩了的错误提醒，特别醒目，大佬们不懂技术，也不管啥原因，就认为是用pro造成的。我希望能自定义这个页面，或者把它去掉，直接白屏也能接受，有什么办法吗

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30229705/145771041-48ce6fd1-73ca-4725-896f-2d46d46fc013.png)

**Comment by chenshuai2144** [comment]
一般都是因为数据没处理好导致的，你可以try catch 一下自定义他的错误信息。

> emmm，换个工作吧。

**Comment by zhangxiangqiang** [comment]
> 

大环境不好，不好乱跑啊，我想到一个好办法，直接css 隐藏掉
