### ISSUE TITLE
🐛[BUG] ProTable 设置pagination里的pageSize为10，执行actionRef.current.reload();恢复成20。

### ISSUE THREAD

**Issue by stonyme** [ant-design/pro-components#4257]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

如题,bug比较简单，题目已经描述清楚。也提供了复现地址。
### 📷 复现步骤
如下图，点击就能看到复现。
![image](https://user-images.githubusercontent.com/21095021/145789739-301a2180-6d26-4ba5-9c43-c4b347f072b3.png)

### 🏞 期望结果
设置pageSize后，就算reset，依然是10.

### 💻 复现代码
https://codesandbox.io/s/wu-cha-xun-biao-dan-forked-qeh0r?file=/App.tsx

### © 版本信息
ProTable最新版本2.56.3也有同样问题。
- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by DerrickTel** [comment]
[pagination](https://ant.design/components/pagination-cn/#API)
你需要设置的是defaultPageSize，而不是pageSize

**Comment by DerrickTel** [comment]
https://codesandbox.io/s/wu-cha-xun-biao-dan-forked-iqdmn?file=/App.tsx
