### ISSUE TITLE
🐛[BUG]BetaSchemaForm在使用QueryFilter模式下，syncToUrl无法set

### ISSUE THREAD

**Issue by galleonsZcc** [ant-design/pro-components#4258]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

问题比较简单，BetaSchemaForm组件同时配置layoutType={'QueryFilter'} 和syncToUrl，syncToUrl的get可以执行，set不会执行。

### 💻 复现代码

[线上示例](https://codesandbox.io/s/schema-biao-dan-forked-kij19?file=/index.tsx)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] 
"@ant-design/pro-form": "^1.49.0",
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/4296
