### ISSUE TITLE
🧐通过form.setFieldsValue 联动写值 结果网页报错 [问题]

### ISSUE THREAD

**Issue by superAo005** [ant-design/pro-components#4259]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
通过form.setFieldsValue 联动写值 

结果网页崩溃
![image](https://user-images.githubusercontent.com/22334521/145809464-8eb340a5-bbe3-4c31-92cb-3882feeae2c2.png)
![image](https://user-images.githubusercontent.com/22334521/145809627-d9bfc454-02b3-48a2-aeab-0226767ee129.png)

### 💻 示例代码
![image](https://user-images.githubusercontent.com/22334521/145809391-2b296688-47b5-4278-b204-ff9cd393c6f7.png)

**Comment by chenshuai2144** [comment]
get 完set，写出死循环了吧

**Comment by superAo005** [comment]
表单联动 先获取对应字段名的值 然后设置联动表单的值 怎么直接死循环了  表单联动不就是这样set的吗

**Comment by superAo005** [comment]
已解决

**Comment by chenshuai2144** [comment]
写出来你的解决过程吧
