### ISSUE TITLE
🧐[问题]ProCard中嵌入表单项，下方有很大的空白区域，怎么处理

### ISSUE THREAD

**Issue by zwjsoft** [ant-design/pro-components#4260]
代码如下：

![image](https://user-images.githubusercontent.com/35764692/145836509-2bdd63a8-03fc-4b74-bf63-9aab2cfb30a7.png)

显示结果如下：
![image](https://user-images.githubusercontent.com/35764692/145813878-615aa9b5-986c-4ce0-9de2-2d06de902205.png)

**Comment by zwjsoft** [comment]
<ProCard direction="row" wrap ="true">
      <ProCard colSpan={12} bordered  size="small">
        <ProFormText 
          title="test"
          name="test"
        />
      </ProCard>
      <ProCard colSpan={12} bordered  size="small">
      <ProFormText bordered
          title="test2"
          name="test2"
        />
      </ProCard>    
      <ProCard colSpan={12} bordered >
        <ProFormText 
          title="test3"
          name="test3"
        />
      </ProCard>
      <ProCard colSpan={12} bordered >
      <ProFormText 
          title="test4"
          name="test4"
        />
      </ProCard>      
    </ProCard>

**Comment by chenshuai2144** [comment]
这个是用来展示错误信息的，你删除掉就没法展示错误信息了

**Comment by zwjsoft** [comment]
展示表单项的输入错误？我不用ProCard，用一个普通的div包就没有这个空白区域。

**Comment by chenshuai2144** [comment]
来个重现？表单项都应该有marginBottom 的

**Comment by zwjsoft** [comment]
用ProCard包裹
![image](https://user-images.githubusercontent.com/35764692/145928827-d17c62e8-c912-45e4-ab79-f87a4d15cb6a.png)
把错误显示出来后，也高了很多
用div包裹
![image](https://user-images.githubusercontent.com/35764692/145929003-c38cef2c-3906-4b33-94db-935eaddf7249.png)
高度刚刚好！

**Comment by zwjsoft** [comment]
ghost模式好了
