### ISSUE TITLE
👑 [需求]  合并行或列 

### ISSUE THREAD

**Issue by lovesL** [ant-design/pro-components#4262]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述
![image](https://user-images.githubusercontent.com/27960630/145825804-37067309-d79a-41d0-9efa-f08b169312b2.png)
比如当某列的每行的内容都是一样的 可以提供一个属性 自动去合并

### 🧐 解决方案
https://ali-react-table.js.org/docs/pipeline/features/auto-row-span/
可参考一下这个

**Comment by chenshuai2144** [comment]
ant 已经支持了，去看看antd 的table文档吧。
我们是基于antd的table做的

**Comment by ldwonday** [comment]
@chenshuai2144 antd我看是写了onCell进行合并的，为什么我在ProTable的columns上写了onCell没有用呢？姿势不对吗

**Comment by ldwonday** [comment]
@chenshuai2144 这个问题麻烦看下，怎么配置表格的合并

**Comment by 16slowly** [comment]
> https://ali-react-table.js.org/docs/pipeline/features/auto-row-span/

我写了也没用，是版本的问题吗？
```json
"antd": "^4.2.0",
"@ant-design/pro-table": "^2.0.0",
```
@chenshuai2144

**Comment by chenshuai2144** [comment]
是 return 一个 object  实现的。

https://ant.design/components/table-cn/#components-table-demo-colspan-rowspan

表头只支持列合并，使用 column 里的 colSpan 进行设置。

表格支持行/列合并，使用 render 里的单元格属性 colSpan 或者 rowSpan 设值为 0 时，设置的表格不会渲染。
