### ISSUE TITLE
官网点击prolayout的固定几个锚点，导致官网页面白屏🐛[BUG]

### ISSUE THREAD

**Issue by zhdxcz** [ant-design/pro-components#4268]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/31975873/145967287-0be0903d-1c71-43af-a60d-0ab469f9e2d0.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 各个浏览器均这样
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
fixed
