### ISSUE TITLE
🐛[BUG] ProForm syncToUrl 检索两次，url 结果会被删除

### ISSUE THREAD

**Issue by alvin0216** [ant-design/pro-components#4269]
如视屏，点击查询两次，第一次 syncToUrl 正确，在点击一次，发现 url 上的参数呗删除了。

https://user-images.githubusercontent.com/34113677/145980778-9a8df018-e4dc-4226-ad91-f343d504bca5.mov

关键代码：

```tsx
 <ProTable<GithubIssueItem>
      form={{
        syncToUrl: true,
      }}
/>
```

**Comment by zzcan** [comment]
看起来是这串代码的问题

**Comment by zzcan** [comment]
看起来是这串代码的问题
![image](https://user-images.githubusercontent.com/24263554/146363895-7b2d0eba-3c9e-4684-9552-6aab598d1fcb.png)

**Comment by alvin0216** [comment]
> 看起来是这串代码的问题 ![image](https://user-images.githubusercontent.com/24263554/146363895-7b2d0eba-3c9e-4684-9552-6aab598d1fcb.png)

嗯，我也发现了，这个问题 @chenshuai2144 是否可以跟进一下？麻烦

**Comment by chenshuai2144** [comment]
来个pr吧

**Comment by zzcan** [comment]
@chenshuai2144 提了个pr，麻烦review一下

**Comment by alvin0216** [comment]
> @chenshuai2144 提了个pr，麻烦review一下

**Comment by chenshuai2144** [comment]
爱你❤️

**Comment by alvin0216** [comment]
强 ，刚想提上去的
