### ISSUE TITLE
🐛[BUG] 使用protable时，最左侧表格样式会发生变化，第一次进入表格是没有问题，当在表格中点击一个操作，跳转到其他页面，再使用浏览器的返回按钮返回时，最左侧的样式会多出一个单元格

### ISSUE THREAD

**Issue by doulongfei** [ant-design/pro-components#4271]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

 使用protable时，最左侧表格样式会发生变化，第一次进入表格是没有问题，当在表格中点击一个操作，跳转到其他页面，再使用浏览器的返回按钮返回时，最左侧的样式会多出一个单元格。就是复选框的宽度会变宽。

正常是这样的。
![image](https://user-images.githubusercontent.com/52975061/146109287-f0ff74a9-f133-402d-890e-aeb1858fe485.png)
单击表格中的一个操作，发生页面跳转后，使用浏览器的返回按钮，返回后的效果是这样的，样式会发生改变。左边的复选框明显会变宽很多。使用浏览器F5刷新一次会恢复。

![image](https://user-images.githubusercontent.com/52975061/146109767-d9136ec5-eca6-42c4-ac31-443be7728839.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]   
    "@ant-design/pro-card": "^1.14.0",
    "@ant-design/pro-descriptions": "^1.6.8",
    "@ant-design/pro-form": "^1.49.6",
    "@ant-design/pro-layout": "^6.19.0",
    "@ant-design/pro-table": "^2.38.0",

- umi 版本  "umi": "^3.5.19",
- Chrome
- 开发环境 Windows

**Comment by doulongfei** [comment]
我上传了图片，但是好像没看见

**Comment by doulongfei** [comment]
我上传了图片，但是好像没看见

**Comment by doulongfei** [comment]
.ant-checkbox-wrapper{
    width:16px;
}
当我给这个样式指定了一个宽度后，问题可以得到解决。

**Comment by chenshuai2144** [comment]
等antd 解决一下吧。最近还有一些漂移问题
