### ISSUE TITLE
🐛[BUG] EditableProTable中自定义actionRender内的state无法被更新

### ISSUE THREAD

**Issue by ralph-wh** [ant-design/pro-components#4273]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

在actionRender中配置自定义按钮并绑定事件，但通过onValuesChange去修改组件内state时（其他任何地方也一样），actionRender内并无变化，绑定的自定义事件输出也是原始state

### 🏞 期望结果

actionRender能被及时更新

### © 版本信息

- ProTable 版本: 2.60.0
- umi 版本：3.5.20
- 浏览器环境 Chrome96.0.4664.93
- 开发环境 macOS 12.0.1

**Comment by ralph-wh** [comment]
![image](https://user-images.githubusercontent.com/24559259/146121360-516c8b62-9684-4b2e-b007-4b07596c32da.png)
![image](https://user-images.githubusercontent.com/24559259/146121517-f969423a-77bb-4678-a7cf-3791832b811e.png)

**Comment by chenshuai2144** [comment]
hooks 是闭包的哥哥，要想解决就用ref

**Comment by zhoufeng215207** [comment]
请问解决了吗?

**Comment by ralph-wh** [comment]
> 请问解决了吗?
解决了，使用useRef声明。

**Comment by ltte** [comment]
> > 请问解决了吗?
> > 解决了，使用useRef声明。
在哪使用了useRef声明啊，请问

**Comment by soulcm** [comment]
所以应该怎么解决，完全没看懂啊，咋就 closed 了

**Comment by chenshuai2144** [comment]
`import { useRefFunction } from '@ant-design/pro-components';`

<img width="662" alt="image" src="https://user-images.githubusercontent.com/8186664/177143330-05c547a2-0fcd-4f88-b370-d464b99d04c3.png">

最无脑的方法，useRefFunction 包一下
