### ISSUE TITLE
🧐[问题]如何一行展示两个ProFormUploadButton上传组件

### ISSUE THREAD

**Issue by yang-chuanjiang** [ant-design/pro-components#4275]
### 🧐 问题描述
我一直无法实现一行展示两个ProFormUploadButton组件，求指导
![image](https://user-images.githubusercontent.com/38531906/146154246-b6a32c0b-d57d-4bbf-82c2-2a8879c51a4d.png)
![image](https://user-images.githubusercontent.com/38531906/146154346-320c4df4-dbcd-43ad-b332-473daa8cea93.png)
![image](https://user-images.githubusercontent.com/38531906/146154322-1cabe2e2-f847-4405-aca9-963feffbe163.png)

**Comment by 1247748612** [comment]
```typescript

<div style={{ display: "flex" }}>
    <ProFormUploadButton />
    <ProFormUploadButton />
</div>
      
<Space>
    <ProFormUploadButton />
    <ProFormUploadButton />
</Space>
```
