### ISSUE TITLE
devScripts.js:6523 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?  Check the render method of `ForwardRef(ProField)`.

### ISSUE THREAD

**Issue by 0x457** [ant-design/pro-components#4277]
### 🧐 问题描述

使用官方的例子：
ProForm 和 EditableTable 同时使用
[https://procomponents.ant.design/components/form/#proform-%E5%92%8C-editabletable-%E5%90%8C%E6%97%B6%E4%BD%BF%E7%94%A8](https://procomponents.ant.design/components/form/#proform-%E5%92%8C-editabletable-%E5%90%8C%E6%97%B6%E4%BD%BF%E7%94%A8)

 以上链接点击，页面上感觉#定位也不准， 可以看这个
[https://procomponents.ant.design/~demos/form-pro-form-editabletable](https://procomponents.ant.design/~demos/form-pro-form-editabletable)
下，在V5新建初始项目下，跑这个例子，只要点击删除报错了。
 

### 💻 示例代码
 
![image](https://user-images.githubusercontent.com/5813610/147406392-7a712543-4fec-4af5-8a1c-62d3577f3909.png)
![image](https://user-images.githubusercontent.com/5813610/147406404-ede99c3b-37fb-4b3c-8ebd-25c5306a0016.png)

        
```
<!--
如果你有解决方案，在这里清晰地阐述
-->

**Comment by chenshuai2144** [comment]
用style 去掉一下 margin 就好了
