### ISSUE TITLE
🐛[BUG] 官网白屏

### ISSUE THREAD

**Issue by iugsm** [ant-design/pro-components#4279]
### 🐛 bug 
prolayout 右边两个导航锚点白屏

### 📷 复现步骤
https://procomponents.ant.design/components/layout/#menu
https://procomponents.ant.design/components/layout/#routecontext

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/75230916/146289302-0b39a41c-9393-453b-8b91-f1103360d747.png)

**Comment by chenshuai2144** [comment]
修复了，清空缓存刷新一下
