### ISSUE TITLE
EditableProTable 实时保存的编辑表格，新增数据后，删除任一行，导致新增数据丢失🐛[BUG]

### ISSUE THREAD

**Issue by penglittlebai** [ant-design/pro-components#4286]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

  EditableProTable 实时保存的编辑表格，新增数据后，删除任一行，导致新增数据丢失，然后修改任意值，下方新增多条空项，@ant-design/pro-table@2.59.2没有这个问题，应该是7天前做性能优化导致bug

### 📷 复现步骤

进到官方"实时保存的编辑表格"demo地址: https://procomponents.ant.design/components/editable-table/#%E5%AE%9E%E6%97%B6%E4%BF%9D%E5%AD%98%E7%9A%84%E7%BC%96%E8%BE%91%E8%A1%A8%E6%A0%BC
点击‘添加一行数据按钮’，添加两条数据
![image](https://user-images.githubusercontent.com/87426994/146321895-b3d9b601-26bf-4155-bc65-d899d7b0c491.png)
删除任意一条
![image](https://user-images.githubusercontent.com/87426994/146322072-e3f58ef7-3324-415f-b485-cc92ec6911c8.png)
导致刚刚新增的两条数据也被删掉
![image](https://user-images.githubusercontent.com/87426994/146322479-17fd21e6-1ca2-422d-a0ec-91691967f320.png)

再修改任意值，表象为每触发一次change，下方会多出两条数据结构有问题的数据
![image](https://user-images.githubusercontent.com/87426994/146322678-6bc77eab-9109-468e-b489-4e59126f482e.png)
![image](https://user-images.githubusercontent.com/87426994/146322791-305fb38d-8037-4922-8262-6f698d7457bf.png)

### © 版本信息

@ant-design/pro-table 2.59.5 至 2.6都有这个问题
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by penglittlebai** [comment]
复现地址： 官方案例 https://procomponents.ant.design/components/editable-table/#%E5%AE%9E%E6%97%B6%E4%BF%9D%E5%AD%98%E7%9A%84%E7%BC%96%E8%BE%91%E8%A1%A8%E6%A0%BC

**Comment by chenshuai2144** [comment]
key相同了，官方的例子我改一下，本地要你自己改了

**Comment by penglittlebai** [comment]
> key相同了，官方的例子我改一下，本地要你自己改了

key并没有相同哦，不是这个问题，测试相同的代码，pro-table 2.59.2没问题， 2.60有问题

**Comment by Tinyuen** [comment]
有解决么？我是 EditableProTable在 ProForm中使用，通过name来做数据的维护。初始化数据新增一行都没问题。唯独删除中间行后，后面的所有行只要带了 proFormItem: { rules: [] } 配置的表单项数据就会被全部清空，其他表单正常。删除最后一行也是一切正常。看现象就是key的问题，可是我key并没有问题啊，也没有重复，都是接口数据回来之后的唯一数据字段id，问题真是多啊，一步一个坑。
