### ISSUE TITLE
EditableProTable 如何使用select 配上 onsearch 获取数据，

### ISSUE THREAD

**Issue by Mr-Jies** [ant-design/pro-components#4289]

**Comment by chenshuai2144** [comment]
写详细一点，一句话需求接不了

**Comment by linxi-1214** [comment]
就是EditableProTable 中有一列设置为：
valueType: 'select',
fieldProps: {
onSearch: (value) => {xxxx}
}

这个地方 onSearch 方法在搜索的时候，没有调用

**Comment by akira0912** [comment]
> 就是EditableProTable 中有一列设置为： valueType: 'select', fieldProps: { onSearch: (value) => {xxxx} }
> 
> 这个地方 onSearch 方法在搜索的时候，没有调用

哥，这个问题解决了吗
