### ISSUE TITLE
👑 [需求] pro-table   时间字段在编辑的form 里valueType是datetime在搜索中 往往是 dateTimeRange

### ISSUE THREAD

**Issue by goodve** [ant-design/pro-components#429]
### 🥰 需求描述
时间字段在 编辑的form 里  valueType  是datetime，在搜索中 往往是  dateTimeRange

### 🧐 解决方案

在设置  列的类型时  valueType    有两种重载 : string  或者  { inForm：type1, inSearch : type2 }

**Comment by chenshuai2144** [comment]
我觉得你说的是这个 https://github.com/ant-design/pro-components/pull/426

**Comment by goodve** [comment]
> 我觉得你说的是这个 #426

提完后我 发现和 #423  是一样的 需求

**Comment by goodve** [comment]
`export declare type ProFieldValueTypeFunction<T> = (item: T) => ProFieldValueType | ProFieldValueObjectType;`
这个函数的参数  没办法判断   item  是在table里 还是  form，search 里

**Comment by juxiaowei** [comment]
hideInSearch
hideIntable

**Comment by goodve** [comment]
> hideInSearch
> hideIntable

一两个可以这么干，多了的话 就很烦

**Comment by chenshuai2144** [comment]
已发布，可以试试自定义了
