### ISSUE TITLE
🐛[BUG] 自从升级pro-table之后，yarn start 一直报错

### ISSUE THREAD

**Issue by huashi** [ant-design/pro-components#4291]
更新pro-table最新版本，之后执行yarn start,报这个错误：

This dependency was not found:

* rc-util/es/Dom/scrollLocker in ./node_modules/@ant-design/pro-form/es/layouts/DrawerForm/index.js, ./node_modules/@ant-design/pro-form/es/layouts/ModalForm/index.js

To install it, you can run: npm install --save rc-util/es/Dom/scrollLocker。

然后执行npm install --save rc-util/es/Dom/scrollLocker，又报错：
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'rc-util/es/Dom/scrollLocker'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v12.22.1
4 verbose npm-session 593b5613e41c8fa0
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for file:rc-util\es\Dom\scrollLocker Could not install from "rc-util\es\Dom\scrollLocker" as it does not contain a package.json file.
8 timing stage:rollbackFailedOptional Completed in 0ms
9 timing stage:runTopLevelLifecycles Completed in 2550ms
10 verbose stack Error: ENOENT: no such file or directory, open 'E:\mywork\DHZG\rc-util\es\Dom\scrollLocker\package.json'
11 verbose cwd E:\mywork\DHZG
12 verbose Windows_NT 10.0.19042
13 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "rc-util/es/Dom/scrollLocker"
14 verbose node v12.22.1
15 verbose npm  v6.14.12
16 error code ENOLOCAL
17 error Could not install from "rc-util\es\Dom\scrollLocker" as it does not contain a package.json file.
18 verbose exit [ 1, true ]。

尝试退回原版本、卸载再安装等等方法，都一样报这个错误。 到底是哪里的问题啊？

**Comment by huashi** [comment]
重装了node.js 可以了，这到底是为什么啊...

**Comment by chenshuai2144** [comment]
依赖没找到，锁包了导致安装不到最新的
