### ISSUE TITLE
🧐[问题]在文档中找不到解决方案

### ISSUE THREAD

**Issue by RoyKwok94** [ant-design/pro-components#4292]
在可编辑表单中EditableProTable， 利用renderFormItem渲染出表单，renderFormItem只能reutrn表单组，但我想丰富这个DOM结构，例  renderFormItem: () => {
      return <div>
<InputNumber min={1} max={100} />
</div>
    },
这样的结构，架框是不允许的，这样开发法如何解决，文档的介绍在哪里？

 {
    title: '评分',
    dataIndex: 'score',
    align: 'center',
    formItemProps: () => {
      return {
        rules: [{ required: true, message: '此项为必填项' }],
      };
    },
    renderFormItem: () => {
      return <InputNumber min={1} max={100} />;
    },
  },

**Comment by chenshuai2144** [comment]
先看看你提了什么issue？是不是什么东西忘记写上来了
