### ISSUE TITLE
🧐[问题] 表头分组时- 工具栏 - 列设置 - 取消父节点的选择后无法再单独选择子节点

### ISSUE THREAD

**Issue by wl521** [ant-design/pro-components#4294]
1:  我设置了表头分组，在列设置中先是点击 “应用名称” 使所有列隐藏，但此时只能通过点击 “应用名称” 这个父节点全选回来，无法再单独选择子项, 这是正常的表现吗？
 ![image](https://user-images.githubusercontent.com/46065253/146480159-9a18d340-16dd-495a-ab36-a62b1d7616ae.png)

  2：这种情况也无法通过点击 “应用名称” 进行全选
![image](https://user-images.githubusercontent.com/46065253/146480510-b91a5327-daeb-47cb-b110-db4e5a9f33d7.png)

  3: 当我将子项一个个取消选择，父节点依旧停留再table上
![image](https://user-images.githubusercontent.com/46065253/146480386-abebf464-240b-40d7-b65f-1b004939a0bc.png)

 4: 子项的顺序能调整吗？以上的问题时正常表现吗？

**Comment by wl521** [comment]
pro-table 版本是2.56.3

**Comment by wl521** [comment]
https://github.com/wl521/test.git @chenshuai2144

**Comment by chenshuai2144** [comment]
来个codebox吧，git 太难跑了

**Comment by wl521** [comment]
https://codesandbox.io/s/blazing-fire-6essp @chenshuai2144  ,不知道为什么一直跑不起来，我不怎么会用这个

**Comment by wl521** [comment]
`import React from 'react';
import { Button, Tooltip } from 'antd';
import { DownOutlined, QuestionCircleOutlined } from '@ant-design/icons';
import ProTable from '@ant-design/pro-table';
import 'antd/dist/antd.css';
const valueEnum = {
  0: 'close',
  1: 'running',
  2: 'online',
  3: 'error',
};
const tableListDataSource = [];
const creators = ['付小小', '曲丽丽', '林东东', '陈帅帅', '兼某某'];
for (let i = 0; i < 5; i += 1) {
  tableListDataSource.push({
    key: i,
    name: 'AppName',
    containers: Math.floor(Math.random() * 20),
    creator: creators[Math.floor(Math.random() * creators.length)],
    status: valueEnum[Math.floor(Math.random() * 10) % 4],
    createdAt: Date.now() - Math.floor(Math.random() * 100000),
    memo: i % 2 === 1 ? '很长很长很长很长很长很长很长的文字要展示但是要留下尾巴' : '简短备注文案',
  });
}
const columns = [
  {
    title: '应用名称',
    width: 80,
    dataIndex: 'name',
    children: [
      {
        title: '容器数量',
        dataIndex: 'containers',
        align: 'right',
        sorter: (a, b) => a.containers - b.containers,
      },
      {
        title: '状态',
        width: 80,
        dataIndex: 'status',
        initialValue: 'all',
        valueEnum: {
          all: { text: '全部', status: 'Default' },
          close: { text: '关闭', status: 'Default' },
          running: { text: '运行中', status: 'Processing' },
          online: { text: '已上线', status: 'Success' },
          error: { text: '异常', status: 'Error' },
        },
      },
      {
        title: '创建者',
        width: 80,
        dataIndex: 'creator',
        valueEnum: {
          all: { text: '全部' },
          付小小: { text: '付小小' },
          曲丽丽: { text: '曲丽丽' },
          林东东: { text: '林东东' },
          陈帅帅: { text: '陈帅帅' },
          兼某某: { text: '兼某某' },
        },
      },
    ]
  },
  {
    title: (<>
      创建时间
      <Tooltip placement="top" title="这是一段描述">
        <QuestionCircleOutlined style={{ marginLeft: 4 }} />
      </Tooltip>
    </>),
    width: 140,
    key: 'since',
    dataIndex: 'createdAt',
    valueType: 'date',
    sorter: (a, b) => a.createdAt - b.createdAt,
  },
  {
    title: '备注',
    dataIndex: 'memo',
    ellipsis: true,
    copyable: true,
  },
];
// eslint-disable-next-line import/no-anonymous-default-export
export default () => {
  return (<ProTable columns={columns} request={(params, sorter, filter) => {
    // 表单搜索项会从 params 传入，传递给后端接口。
    console.log(params, sorter, filter);
    return Promise.resolve({
      data: tableListDataSource,
      success: true,
    });
  }} rowKey="key" pagination={{
    showQuickJumper: true,
  }} search={false} dateFormatter="string" headerTitle="表格标题" toolBarRender={() => [
    <Button key="show">查看日志</Button>,
    <Button key="out">
      导出数据
      <DownOutlined />
    </Button>,
    <Button type="primary" key="primary">
      创建应用
    </Button>,
  ]} />);
};`

**Comment by wl521** [comment]
``import React from 'react';
import { Button, Tooltip } from 'antd';
import { DownOutlined, QuestionCircleOutlined } from '@ant-design/icons';
import ProTable from '@ant-design/pro-table';
import 'antd/dist/antd.css';
const valueEnum = {
  0: 'close',
  1: 'running',
  2: 'online',
  3: 'error',
};
const tableListDataSource = [];
const creators = ['付小小', '曲丽丽', '林东东', '陈帅帅', '兼某某'];
for (let i = 0; i < 5; i += 1) {
  tableListDataSource.push({
    key: i,
    name: 'AppName',
    containers: Math.floor(Math.random() * 20),
    creator: creators[Math.floor(Math.random() * creators.length)],
    status: valueEnum[Math.floor(Math.random() * 10) % 4],
    createdAt: Date.now() - Math.floor(Math.random() * 100000),
    memo: i % 2 === 1 ? '很长很长很长很长很长很长很长的文字要展示但是要留下尾巴' : '简短备注文案',
  });
}
const columns = [
  {
    title: '应用名称',
    width: 80,
    dataIndex: 'name',
    children: [
      {
        title: '容器数量',
        dataIndex: 'containers',
        align: 'right',
        sorter: (a, b) => a.containers - b.containers,
      },
      {
        title: '状态',
        width: 80,
        dataIndex: 'status',
        initialValue: 'all',
        valueEnum: {
          all: { text: '全部', status: 'Default' },
          close: { text: '关闭', status: 'Default' },
          running: { text: '运行中', status: 'Processing' },
          online: { text: '已上线', status: 'Success' },
          error: { text: '异常', status: 'Error' },
        },
      },
      {
        title: '创建者',
        width: 80,
        dataIndex: 'creator',
        valueEnum: {
          all: { text: '全部' },
          付小小: { text: '付小小' },
          曲丽丽: { text: '曲丽丽' },
          林东东: { text: '林东东' },
          陈帅帅: { text: '陈帅帅' },
          兼某某: { text: '兼某某' },
        },
      },
    ]
  },
  {
    title: (<>
      创建时间
      <Tooltip placement="top" title="这是一段描述">
        <QuestionCircleOutlined style={{ marginLeft: 4 }} />
      </Tooltip>
    </>),
    width: 140,
    key: 'since',
    dataIndex: 'createdAt',
    valueType: 'date',
    sorter: (a, b) => a.createdAt - b.createdAt,
  },
  {
    title: '备注',
    dataIndex: 'memo',
    ellipsis: true,
    copyable: true,
  },
];
// eslint-disable-next-line import/no-anonymous-default-export
export default () => {
  return (<ProTable columns={columns} request={(params, sorter, filter) => {
    // 表单搜索项会从 params 传入，传递给后端接口。
    console.log(params, sorter, filter);
    return Promise.resolve({
      data: tableListDataSource,
      success: true,
    });
  }} rowKey="key" pagination={{
    showQuickJumper: true,
  }} search={false} dateFormatter="string" headerTitle="表格标题" toolBarRender={() => [
    <Button key="show">查看日志</Button>,
    <Button key="out">
      导出数据
      <DownOutlined />
    </Button>,
    <Button type="primary" key="primary">
      创建应用
    </Button>,
  ]} />);
};

**Comment by wl521** [comment]
``import React from 'react';
import { Button, Tooltip } from 'antd';
import { DownOutlined, QuestionCircleOutlined } from '@ant-design/icons';
import ProTable from '@ant-design/pro-table';
import 'antd/dist/antd.css';
const valueEnum = {
  0: 'close',
  1: 'running',
  2: 'online',
  3: 'error',
};
const tableListDataSource = [];
const creators = ['付小小', '曲丽丽', '林东东', '陈帅帅', '兼某某'];
for (let i = 0; i < 5; i += 1) {
  tableListDataSource.push({
    key: i,
    name: 'AppName',
    containers: Math.floor(Math.random() * 20),
    creator: creators[Math.floor(Math.random() * creators.length)],
    status: valueEnum[Math.floor(Math.random() * 10) % 4],
    createdAt: Date.now() - Math.floor(Math.random() * 100000),
    memo: i % 2 === 1 ? '很长很长很长很长很长很长很长的文字要展示但是要留下尾巴' : '简短备注文案',
  });
}
const columns = [
  {
    title: '应用名称',
    width: 80,
    dataIndex: 'name',
    children: [
      {
        title: '容器数量',
        dataIndex: 'containers',
        align: 'right',
        sorter: (a, b) => a.containers - b.containers,
      },
      {
        title: '状态',
        width: 80,
        dataIndex: 'status',
        initialValue: 'all',
        valueEnum: {
          all: { text: '全部', status: 'Default' },
          close: { text: '关闭', status: 'Default' },
          running: { text: '运行中', status: 'Processing' },
          online: { text: '已上线', status: 'Success' },
          error: { text: '异常', status: 'Error' },
        },
      },
      {
        title: '创建者',
        width: 80,
        dataIndex: 'creator',
        valueEnum: {
          all: { text: '全部' },
          付小小: { text: '付小小' },
          曲丽丽: { text: '曲丽丽' },
          林东东: { text: '林东东' },
          陈帅帅: { text: '陈帅帅' },
          兼某某: { text: '兼某某' },
        },
      },
    ]
  },
  {
    title: (<>
      创建时间
      <Tooltip placement="top" title="这是一段描述">
        <QuestionCircleOutlined style={{ marginLeft: 4 }} />
      </Tooltip>
    </>),
    width: 140,
    key: 'since',
    dataIndex: 'createdAt',
    valueType: 'date',
    sorter: (a, b) => a.createdAt - b.createdAt,
  },
  {
    title: '备注',
    dataIndex: 'memo',
    ellipsis: true,
    copyable: true,
  },
];
// eslint-disable-next-line import/no-anonymous-default-export
export default () => {
  return (<ProTable columns={columns} request={(params, sorter, filter) => {
    // 表单搜索项会从 params 传入，传递给后端接口。
    console.log(params, sorter, filter);
    return Promise.resolve({
      data: tableListDataSource,
      success: true,
    });
  }} rowKey="key" pagination={{
    showQuickJumper: true,
  }} search={false} dateFormatter="string" headerTitle="表格标题" toolBarRender={() => [
    <Button key="show">查看日志</Button>,
    <Button key="out">
      导出数据
      <DownOutlined />
    </Button>,
    <Button type="primary" key="primary">
      创建应用
    </Button>,
  ]} />);
};

**Comment by wl521** [comment]
`import React from 'react';
import { Button, Tooltip } from 'antd';
import { DownOutlined, QuestionCircleOutlined } from '@ant-design/icons';
import ProTable from '@ant-design/pro-table';
import 'antd/dist/antd.css';
const valueEnum = {
  0: 'close',
  1: 'running',
  2: 'online',
  3: 'error',
};
const tableListDataSource = [];
const creators = ['付小小', '曲丽丽', '林东东', '陈帅帅', '兼某某'];
for (let i = 0; i < 5; i += 1) {
  tableListDataSource.push({
    key: i,
    name: 'AppName',
    containers: Math.floor(Math.random() * 20),
    creator: creators[Math.floor(Math.random() * creators.length)],
    status: valueEnum[Math.floor(Math.random() * 10) % 4],
    createdAt: Date.now() - Math.floor(Math.random() * 100000),
    memo: i % 2 === 1 ? '很长很长很长很长很长很长很长的文字要展示但是要留下尾巴' : '简短备注文案',
  });
}
const columns = [
  {
    title: '应用名称',
    width: 80,
    dataIndex: 'name',
    children: [
      {
        title: '容器数量',
        dataIndex: 'containers',
        align: 'right',
        sorter: (a, b) => a.containers - b.containers,
      },
      {
        title: '状态',
        width: 80,
        dataIndex: 'status',
        initialValue: 'all',
        valueEnum: {
          all: { text: '全部', status: 'Default' },
          close: { text: '关闭', status: 'Default' },
          running: { text: '运行中', status: 'Processing' },
          online: { text: '已上线', status: 'Success' },
          error: { text: '异常', status: 'Error' },
        },
      },
      {
        title: '创建者',
        width: 80,
        dataIndex: 'creator',
        valueEnum: {
          all: { text: '全部' },
          付小小: { text: '付小小' },
          曲丽丽: { text: '曲丽丽' },
          林东东: { text: '林东东' },
          陈帅帅: { text: '陈帅帅' },
          兼某某: { text: '兼某某' },
        },
      },
    ]
  },
  {
    title: (<>
      创建时间
      <Tooltip placement="top" title="这是一段描述">
        <QuestionCircleOutlined style={{ marginLeft: 4 }} />
      </Tooltip>
    </>),
    width: 140,
    key: 'since',
    dataIndex: 'createdAt',
    valueType: 'date',
    sorter: (a, b) => a.createdAt - b.createdAt,
  },
  {
    title: '备注',
    dataIndex: 'memo',
    ellipsis: true,
    copyable: true,
  },
];
// eslint-disable-next-line import/no-anonymous-default-export
export default () => {
  return (<ProTable columns={columns} request={(params, sorter, filter) => {
    // 表单搜索项会从 params 传入，传递给后端接口。
    console.log(params, sorter, filter);
    return Promise.resolve({
      data: tableListDataSource,
      success: true,
    });
  }} rowKey="key" pagination={{
    showQuickJumper: true,
  }} search={false} dateFormatter="string" headerTitle="表格标题" toolBarRender={() => [
    <Button key="show">查看日志</Button>,
    <Button key="out">
      导出数据
      <DownOutlined />
    </Button>,
    <Button type="primary" key="primary">
      创建应用
    </Button>,
  ]} />);
}; `

**Comment by wl521** [comment]
`import React from 'react';
import { Button, Tooltip } from 'antd';
import { DownOutlined, QuestionCircleOutlined } from '@ant-design/icons';
import ProTable from '@ant-design/pro-table';
import 'antd/dist/antd.css';
const valueEnum = {
  0: 'close',
  1: 'running',
  2: 'online',
  3: 'error',
};
const tableListDataSource = [];
const creators = ['付小小', '曲丽丽', '林东东', '陈帅帅', '兼某某'];
for (let i = 0; i < 5; i += 1) {
  tableListDataSource.push({
    key: i,
    name: 'AppName',
    containers: Math.floor(Math.random() * 20),
    creator: creators[Math.floor(Math.random() * creators.length)],
    status: valueEnum[Math.floor(Math.random() * 10) % 4],
    createdAt: Date.now() - Math.floor(Math.random() * 100000),
    memo: i % 2 === 1 ? '很长很长很长很长很长很长很长的文字要展示但是要留下尾巴' : '简短备注文案',
  });
}
const columns = [
  {
    title: '应用名称',
    width: 80,
    dataIndex: 'name',
    children: [
      {
        title: '容器数量',
        dataIndex: 'containers',
        align: 'right',
        sorter: (a, b) => a.containers - b.containers,
      },
      {
        title: '状态',
        width: 80,
        dataIndex: 'status',
        initialValue: 'all',
        valueEnum: {
          all: { text: '全部', status: 'Default' },
          close: { text: '关闭', status: 'Default' },
          running: { text: '运行中', status: 'Processing' },
          online: { text: '已上线', status: 'Success' },
          error: { text: '异常', status: 'Error' },
        },
      },
      {
        title: '创建者',
        width: 80,
        dataIndex: 'creator',
        valueEnum: {
          all: { text: '全部' },
          付小小: { text: '付小小' },
          曲丽丽: { text: '曲丽丽' },
          林东东: { text: '林东东' },
          陈帅帅: { text: '陈帅帅' },
          兼某某: { text: '兼某某' },
        },
      },
    ]
  },
  {
    title: (<>
      创建时间
      <Tooltip placement="top" title="这是一段描述">
        <QuestionCircleOutlined style={{ marginLeft: 4 }} />
      </Tooltip>
    </>),
    width: 140,
    key: 'since',
    dataIndex: 'createdAt',
    valueType: 'date',
    sorter: (a, b) => a.createdAt - b.createdAt,
  },
  {
    title: '备注',
    dataIndex: 'memo',
    ellipsis: true,
    copyable: true,
  },
];
// eslint-disable-next-line import/no-anonymous-default-export
export default () => {
  return (<ProTable columns={columns} request={(params, sorter, filter) => {
    // 表单搜索项会从 params 传入，传递给后端接口。
    console.log(params, sorter, filter);
    return Promise.resolve({
      data: tableListDataSource,
      success: true,
    });
  }} rowKey="key" pagination={{
    showQuickJumper: true,
  }} search={false} dateFormatter="string" headerTitle="表格标题" toolBarRender={() => [
    <Button key="show">查看日志</Button>,
    <Button key="out">
      导出数据
      <DownOutlined />
    </Button>,
    <Button type="primary" key="primary">
      创建应用
    </Button>,
  ]} />);
};`  代码

**Comment by wl521** [comment]
https://codesandbox.io/s/cha-xun-wu-an-niu-biao-ge-forked-fqbur?file=/App.tsx  @chenshuai2144

**Comment by wl521** [comment]
@chenshuai2144  有时间验证下这个问题吗？ 我发现这种情况下 点击父节点的固定在列首 也是不生效的，好像需要所有子节点都设置fixed才可以生效

**Comment by chenshuai2144** [comment]
子列是不能固定到某一边的，这个是antd的实现原理导致的。

**Comment by chenshuai2144** [comment]
你提供的demo是有问题的，打开是官方默认的，你要fork一下

**Comment by wl521** [comment]
https://codesandbox.io/s/cha-xun-wu-an-niu-biao-ge-forked-fqbur?file=/App.tsx  @chenshuai2144  ,我是直接在官方的连接上进行了一点点改动 
![image](https://user-images.githubusercontent.com/46065253/146901330-af7a0496-ec55-40af-aaee-6e7af62dd0bc.png)

**Comment by wl521** [comment]
> 

我的意思是我设置父容器固定在列首，但并没有生效

**Comment by wl521** [comment]
issues比较赶，上周我直接更改了组件的部分代码来解决我遇到的问题，但我比较怀疑是不是自己没用对，下面是我的改动，
这是想着让父节点设置固定的时候，子节点能跟着
![lQLPDhr7LVE1DzXNAejNBs2w4gAukETBDRsByMVt3cDSAA_1741_488](https://user-images.githubusercontent.com/46065253/146931653-58b2395b-3d9f-4a06-9a2c-9441c0cfe8d3.png)
这个是在点击选择的时候加了点逻辑，用来解决1,2问题
![lQLPDhr7LYptfzHNA3jNA3uwPJ0ZXPbPPakByMXLh4B0AA_891_888](https://user-images.githubusercontent.com/46065253/146932167-202243d1-714f-4473-9365-cb828920fb61.png)
这个用来解决 问题 3
![lQLPDhr7LajTeuHNA2DNA7GwT4RBXNG5BZgByMX9uQBWAA_945_864](https://user-images.githubusercontent.com/46065253/146932337-d2ffd0fb-9618-4bbe-b1b1-f41c8da16609.png)

是不是我使用过程中某些API没有正确使用导致我遇到这些问题，  @chenshuai2144

**Comment by chenshuai2144** [comment]
新版本使用了tree，没有这个问题了。更新试试
