### ISSUE TITLE
🐛[BUG] 文档 ProLayout 页面滚动到 #settingdrawer 时白屏

### ISSUE THREAD

**Issue by GOWxx** [ant-design/pro-components#4295]
### 🐛 bug 描述
ProLayout - 高级布局 文档页面滚动到 #SettingDrawer 时报错页面白屏崩溃
https://procomponents.ant.design/components/layout/

### 📷 复现步骤
打开 ProLayout - 高级布局 文档页面，滚动到 SettingDrawer 位置
https://procomponents.ant.design/components/layout/
或直接访问
https://procomponents.ant.design/components/layout/#settingdrawer

### 🏞 期望结果
修复错误内容

- 浏览器环境
win10 google chrome v96

### 🚑 其他信息
报错信息：
![image](https://user-images.githubusercontent.com/12870715/146481546-caa75ac2-5b2d-4a17-bd4d-e4f3db0bb281.png)

**Comment by chenshuai2144** [comment]
修复了，刷新下吧

**Comment by GOWxx** [comment]
> 修复了，刷新下吧

我尝试了下，控制台停用缓存 + 强刷新
在该页面滚动还是会白页

https://procomponents.ant.design/components/layout/
