### ISSUE TITLE
🐛[BUG]ProFormUploadButton组件onChange每个status都会执行两次

### ISSUE THREAD

**Issue by Iveon** [ant-design/pro-components#4297]
### 🐛 bug 描述

ProFormUploadButton组件onChange每个status都会执行两次

### 🏞 期望结果

只执行一次

![image](https://user-images.githubusercontent.com/21276534/146500399-de49d750-0fc8-4640-990b-7c3a81b3a13a.png)

**Comment by Iveon** [comment]
把onChange放到fieldProps中就不会了.

请问一下,表单编辑的时候怎么把数据传给ProFormUploadButton,其他的组件设置name就好了,这个组件报错了(fileList || []).forEach is not a function

边做边学中,还望赐教.

另外 codesandbox 一直在 Transpiling Modules...

**Comment by chenshuai2144** [comment]
fileList 要是一个数组，你给的应该不是一个数组

**Comment by Iveon** [comment]
`          <ProFormUploadButton
            // onChange={onChange}
            name='images'
            label='图片'
            max={6}
            fieldProps={{
              name: 'file',
              listType: 'picture-card',
              onChange: onChange,
            }}
            action='/api/meal/template/upload'
          />`
我返回的数据中 images 是一个数组,我需要先拿到images数组再创建一个变量赋值给fileList才可以吗?

**Comment by chenshuai2144** [comment]
name='images' 他拿的是form里面的这个，你应该给了个空对象之类的了

**Comment by Iveon** [comment]
真的抱歉,是我错了,是的我传进去的是一个字符串.

我是以字符串存入数据库的,拿出来没有转换.先可以了.
