### ISSUE TITLE
🐛[BUG] ProTable column 设置 valueEnum 时，文档描述与实际不符

### ISSUE THREAD

**Issue by LeeHarlan** [ant-design/pro-components#430]
### 🐛 bug 描述

ProTable 文档描述
> 设置了 valueEnum 的列将会生成 Select,Select 会自动插入一个全部选项，并且默认选中，但是值为 all 在查询时会被丢弃。

官方文档的示例查询值为 all 时并没有被丢弃

### 📷 复现步骤

官方文档就有这样的问题

### 🏞 期望结果

值为 all 在查询时会被丢弃

### © 版本信息

- ProComponents  ProTable 2.7.0
- umi 版本 3.2.2
- 浏览器环境 chrome 85
- 开发环境 win10

**Comment by chenshuai2144** [comment]
这个功能因为影响不好被删掉了，你有兴趣帮我们删除一下吗？
