### ISSUE TITLE
EditableProTable 实时保存的编辑表格，手动调用actionRef.current?.addEditRecord新增数据，不能添加多条🐛[BUG]

### ISSUE THREAD

**Issue by penglittlebai** [ant-design/pro-components#4304]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/87426994/146721605-7e2fe6ac-1469-42d3-9380-fc76e5523796.png)

### © 版本信息

pro-table 2.60.1

**Comment by penglittlebai** [comment]
https://codesandbox.io/s/whuzd?file=/App.tsx

**Comment by ChinaMrAlvin** [comment]
actionRef.current?.addEditRecord?.(
    {
      id,
      title: '新的一行',
    },
    { newRecordType: 'dataSource', recordKey: id },
  ); 第二个参数传 recordKey 即可
