### ISSUE TITLE
EditableProTable 实时保存的编辑表格，手动调用actionRef.current?.addEditRecord新增数据，或复制一条数据，不会触发onValuesChange或onChange，导致新增的数据不会更新dataSource🐛[BUG]

### ISSUE THREAD

**Issue by penglittlebai** [ant-design/pro-components#4305]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 💻 复现代码

![image](https://user-images.githubusercontent.com/87426994/146720407-06aaa066-3d3b-4cf7-a34e-3d1ef09bcda6.png)

![image](https://user-images.githubusercontent.com/87426994/146721318-580a7b7e-a158-45e8-9282-176a7ec6e015.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by penglittlebai** [comment]
> 

https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-whuzd?file=/App.tsx

**Comment by penglittlebai** [comment]
同时点复制，不能新增多条

**Comment by 2724635499** [comment]
最好的解决办法是这个：
`actionRef.current?.addEditRecord({
                    ...row,
                    id: Date.now()
                  }, {
                    newRecordType: 'dataSource'
                  });`
