### ISSUE TITLE
EditableProTable 文档能否出个简单联动的案例，比如第一项输入10，第二项的值设置为第一项的一半，目前只有与编辑表格外的内容联动的案例👑 [需求]

### ISSUE THREAD

**Issue by penglittlebai** [ant-design/pro-components#4306]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/~demos/editabletable-form-linkage

https://procomponents.ant.design/components/editable-table#%E4%B8%8E%E7%BC%96%E8%BE%91%E8%A1%A8%E6%A0%BC%E5%A4%96%E7%9A%84%E5%86%85%E5%AE%B9%E8%81%94%E5%8A%A8

看看这个demo。

**Comment by simplast** [comment]
这还是与表格外联动啊
