### ISSUE TITLE
🐛[BUG]  pro-table   valueEnum 设置 initialValue 为数值时 无法选中select 的item

### ISSUE THREAD

**Issue by goodve** [ant-design/pro-components#431]
### 🐛 bug 描述
valueEnum 设置 initialValue 为数值时 无法选中select 的item

### 📷 复现步骤

```
 initialValue:1,
      valueEnum: {
        1: {
          text: '正常',
          status: 'Processing',
        },
        2: {
          text: '停用',
          status: 'Error',
        }
}
```
无法选中

换成  
 ```
 initialValue:'1',
      valueEnum: {
        1: {
          text: '正常',
          status: 'Processing',
        },
        2: {
          text: '停用',
          status: 'Error',
        },  
      },
```
就可以了
### 🏞 期望结果

 initialValue 为数值时也能选上

### © 版本信息

- ProComponents 版本: [2.7.1]
- umi 版本 3.2.19
- 浏览器环境  electron 10.0.1 （谷歌 Chrome/85.0.4183.93）
- 开发环境 [win10]

**Comment by itsuki0927** [comment]
这是因为js中的object key会自动转成string类型的.先用这种方式HACK一下把

**Comment by itsuki0927** [comment]
我不确定这是不是bug, 因为在js中object的key会自动转成string.

**Comment by chenshuai2144** [comment]
这是 javascript 的设计，js 的 object 只允许 string 作为 key。

你要用别的数据类型要用map， valueEnum 也是支持的

**Comment by itsuki0927** [comment]
@chenshuai2144  我刚试了下 new Map() 只支持[string,any]类型

**Comment by Mr-zhuxing** [comment]
> 这是 javascript 的设计，js 的 object 只允许 string 作为 key。
> 
> 你要用别的数据类型要用map， valueEnum 也是支持的

如果map的键为0的时候，也是无法选中

**Comment by RP152** [comment]
mark
