### ISSUE TITLE
👑 ProTable 的Json 表单中valueType使用dependency不生效

### ISSUE THREAD

**Issue by haulong** [ant-design/pro-components#4314]
### 🧐 问题描述

使用Json配置表单的 ProFormDependency功能时，配置了valueType为dependency却报错

### 💻 示例代码

import { useState, useRef, useEffect } from 'react';
import { useRequest } from 'umi';
import { BetaSchemaForm } from '@ant-design/pro-form';
import type { FormInstance, ProFormColumnsType } from '@ant-design/pro-form';
import { getRule, getOrderType } from '@/services/configRules';

export default (props: any) => {
  const { visible, auditWayData, onVisibleChange } = props;

  const formRef = useRef<FormInstance>();

  const [ruleOp, setRuleOp] = useState<any[]>([]);

  useRequest(getRule, {
    onSuccess: (res) => {
      setRuleOp(res);
    }
  });

  const { data = {} } = useRequest(getOrderType);
  const { orderOp = [], orderMap = {} } = data as any;

  useEffect(() => {
    formRef?.current?.setFieldsValue(auditWayData)
  }, [auditWayData])

  const onFinish = async () => {

  }

  const columns: ProFormColumnsType<any>[] = [
    {
      title: '请选择',
      dataIndex: 'ruleNum',
      valueType: 'select', 
      fieldProps: {
        options: ruleOp,
      },
      formItemProps: {
        rules: [
          {
            required: true,
            message: '必填项',
          },
        ],
      },
    },
    {
      valueType: 'dependency',
      fieldProps: {
        name: ['ruleNum'],
      },
      columns: (record: any) => {
        const { ruleNum } = record;
        if (ruleNum === '01') {
          return [
            {
              dataIndex: 'ruleRemark',
              title: '订单分类',
              valueType: 'checkbox',
              fieldProps: {
                options: orderOp,
              },
            },
          ]
        }
        return null;
      }
    }
  ]

  return (
    <BetaSchemaForm
      layoutType='ModalForm'
      layout='horizontal'
      title="新增限制规则"
      formRef={formRef}
      visible={visible}
      columns={columns}
      onFinish={onFinish}
      onVisibleChange={onVisibleChange}
      labelCol={{ span: 6 }}
      wrapperCol={{ span: 14 }}
    />
  )
}

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/44863231/146706963-e61f983d-68d2-4e2b-b290-87ff03e2ee10.png)
![image](https://user-images.githubusercontent.com/44863231/146706970-4d90478b-b9f4-469c-88af-8c5785dfc4ba.png)

**Comment by 1247748612** [comment]
升级到最新版本

**Comment by haulong** [comment]
![image](https://user-images.githubusercontent.com/44863231/146707729-71e0c2f6-a1cc-4c68-8ea4-3ee433959c30.png)
已经最新了

**Comment by 1247748612** [comment]
![image](https://user-images.githubusercontent.com/29533304/146707948-60d4e16e-9857-4242-84c5-99471267a46e.png)

pro-form也不是最新啊

**Comment by haulong** [comment]
是我弄错了，已经好用了，十分感谢
