### ISSUE TITLE
🧐[问题]<SchemaForm>如何自定义类似ProForm.Group的表单控件容器

### ISSUE THREAD

**Issue by ppmmwozuiai** [ant-design/pro-components#4315]
### 🧐 问题描述

本想通过定制valueType的形式自定义一个表单控件，但是SchemaForm对ProForm.Group有特殊的[处理过程](https://github.com/ant-design/pro-components/blob/0987af01e63faa18e8d398fab659bc6c010ec1c6/packages/form/src/components/SchemaForm/index.tsx#L170)，但是这个过程并没有对外部暴露；
然后想到通过定制ProForm.Group的样式达到目的，但是dom结构又和SchemaForm完全不同，这条路也行不通。
借问大家有没有可行的操作方式。

**Comment by 1247748612** [comment]
valueType: 'group'
