### ISSUE TITLE
🐛[BUG] DrawForm下动态request出现一直加载中

### ISSUE THREAD

**Issue by ldwonday** [ant-design/pro-components#4316]
如题，bug复现地址：https://codesandbox.io/s/schema-biao-dan-forked-jz0wj?file=/App.tsx

**Comment by chenshuai2144** [comment]
这个demo 跑不起来？

**Comment by ldwonday** [comment]
@chenshuai2144 可以的，少了一个css，我加上了

**Comment by chenshuai2144** [comment]
有点神奇，你放到layout里面试试

**Comment by 1247748612** [comment]
只有这一行会触发这个bug
```typescript
request={visible ? () => [] : undefined}
```

为什么会这样写？

一定要这样的逻辑可以改成这样

```typescript
request={async () => {
  if (!visible) return [];
  // 调用查询函数
  return (() => [])();
}}
```

> 具体原因未知，可能由于request变更导致原来的request未被cancel到

**Comment by ldwonday** [comment]
@1247748612 这样写应该没问题，不过感觉不是最优方案。

**Comment by ldwonday** [comment]
@1247748612 是的只有那个request如果是动态计算的话就会触发那个bug，一定要和visible结合才会出现

**Comment by 1247748612** [comment]
你是想惰性请求吗

**Comment by chenshuai2144** [comment]
这个问题不是很好解决，默认会缓存掉swr 的请求，只能先绕开或者params 里面多设置一下。
