### ISSUE TITLE
🐛 pro-table  点击sorter后会触发多次请求

### ISSUE THREAD

**Issue by goodve** [ant-design/pro-components#432]
### 🐛 bug 描述

pro-table  点击sorter后会触发多次请求
### 📷 复现步骤

点击升序 会触发两次  ASC请求，
点击降序   一次   DESC  后两次 ASC

### © 版本信息

- ProComponents 版本: [2.7.1]
- umi 版本 3.2.19
- 浏览器环境   Chrome/85.0.4183.93 
- 开发环境 [win10]

**Comment by goodve** [comment]
@chenshuai2144  这个最近版本能修复么？

**Comment by chenshuai2144** [comment]
试了一下，没有问题，需要怎么复现呢？

**Comment by goodve** [comment]
> 试了一下，没有问题，需要怎么复现呢？

就是 umi ui添加的区块  什么都没改的  就是出现了

**Comment by goodve** [comment]
使用不当导致的  这个可以删除了
