### ISSUE TITLE
🐛[BUG] PageContainer刷新然后返回上一页的时候会报Warning: React state update 

### ISSUE THREAD

**Issue by greenking19** [ant-design/pro-components#4324]
### 🐛 bug 描述

A页面进入B页面，浏览器刷新然后返回上一页的时候报👇:
Warning: Can't perform a React state update on an unmounted component. This is a no-op,
          but it indicates a memory leak in your application. To fix, cancel all subscriptions and
          asynchronous tasks in a useEffect cleanup function.

### 📷 复现步骤
运行项目
1. 登陆后进入首页点击下方按钮 👇
2. F12 打开面板
3. F5 刷新页面然后点击浏览器的返回上一页
4. 🤯 控制台会提示以下 Warning

### 🏞 期望结果
没有Warning

### 💻 复现代码
clone项目运行即可

仓库代码: [git@github.com:greenking19/PageContainer-Bug.git](https://github.com/greenking19/PageContainer-Bug)
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 umi@3.5.2
- 浏览器环境 Chrome
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个一般不是 PageContainer的问题，应该是你上一个页面还在做什么没有清理掉。

PageContainer 是个纯静态的

**Comment by greenking19** [comment]
> 这个一般不是 PageContainer的问题，应该是你上一个页面还在做什么没有清理掉。
> 
> PageContainer 是个纯静态的

你可以看一下源码，什么也没有做，就是history.push(pathName)
就两个简单静态页面

**Comment by greenking19** [comment]
> 这个一般不是 PageContainer的问题，应该是你上一个页面还在做什么没有清理掉。
> 
> PageContainer 是个纯静态的

1. A to B 
2. B刷新然后back的时候就报错了

这个项目使用umi创建的简单模版，没做其他的代码

**这是A页面的代码**
```tsx
import React from 'react';
import { PageContainer } from '@ant-design/pro-layout';
import { Button, Typography } from 'antd';
import { useHistory } from 'umi';

const { Title } = Typography;
const Home: React.FC = () => {
  const history = useHistory();
  const toBugPage = () => {
    history.push(`/show-bug/test-bug`);
  };
  return (
    <PageContainer>
      <Title>Bug复现操作:</Title>
      <Title>点击下方按钮👇</Title>

      <div>
        <Button type="primary" onClick={toBugPage}>
          To Bug Page
        </Button>
      </div>
    </PageContainer>
  );
};

export default Home;

```
**这是B页面的代码**
```tsx
import React from 'react';
import { PageContainer } from '@ant-design/pro-layout';
import { Typography } from 'antd';

const { Title } = Typography;

const PageContainerBug: React.FC = () => {
  return (
    <PageContainer key="ttrttt">
      <Title>显示Bug操作👇</Title>
      <Title>F12打开面板</Title>
      <Title>F5 刷新页面</Title>
      <Title>点击浏览器的返回上一页</Title>
      <Title>🤯 控制台会提示一下Wrining</Title>
      <div style={{ background: 'red', width: 480, padding: 16 }}>
        <div style={{ color: 'white' }}>
          Warning: Can't perform a React state update on an unmounted component. This is a no-op,
          but it indicates a memory leak in your application. To fix, cancel all subscriptions and
          asynchronous tasks in a useEffect cleanup function.
        </div>
      </div>
    </PageContainer>
  );
};

export default PageContainerBug;

```

**Comment by wh77572** [comment]
同样是静态的两个页面   使用history.push(pathName)后就会出现此warning

**Comment by greenking19** [comment]
> 同样是静态的两个页面 使用history.push(pathName)后就会出现此warning

提了两个月了 不知道现在修复没有. 是Container组件的里面有一个函数监听了一些事件 自己改的话 不方便
