### ISSUE TITLE
🐛[BUG]ProList 调用actionRef.current?.reload()不刷新数据

### ISSUE THREAD

**Issue by gaspire** [ant-design/pro-components#4325]
### 🐛 bug 描述
ProList 调用actionRef.current?.reload()不刷新数据
 
### 🏞 期望结果
期望刷新数据

### 💻 复现代码
 const actionRef = useRef<ActionType>();

<ProList actionRef={actionRef} rowKey="id"/>

actionRef.current?.reload()
### © 版本信息

- @ant-design/pro-list: "^1.21.0
- umi ^3.5.0
- chrome
- 开发环境 [ mac OS]

**Comment by chenshuai2144** [comment]
你要actionRef 绑定到 list上面
