### ISSUE TITLE
pro-table的展开功能可以实现手动展开全部行、折叠全部行吗？👑 [需求]

### ISSUE THREAD

**Issue by showtan001** [ant-design/pro-components#4326]
### 🥰 需求描述
pro-table的expandable可以实现手动设置展开全部行和折叠全部行吗？目前的expandable没有这个属性，只有个初始时展开所有行。

![image](https://user-images.githubusercontent.com/32892347/146865074-fed6a1f3-0cc0-4185-8fa8-8cac51dec5e2.png)

**Comment by chenshuai2144** [comment]
受控的哦
