### ISSUE TITLE
🐛[BUG]ProFormTimePicker getFieldValue()获取的时间不对

### ISSUE THREAD

**Issue by Donlei** [ant-design/pro-components#4328]
### 🐛 bug 描述

ProFormTimePicker，在DrawerForm中通过onFinish获取的时间是正确的，但是通过formRef.current?.getFieldsValue()获取的时间却始终不对

### 📷 复现步骤

![1640067111(1)](https://user-images.githubusercontent.com/24711571/146880994-2466adf9-
![1640067297(1)](https://user-images.githubusercontent.com/24711571/146881000-1f4487a0-dfb8-424c-8415-8145e08cdc2d.png)
39ab-42fd-8224-e1cb3177357b.png)

### 🏞 期望结果

formRef.current?.getFieldsValue()能够获得正确的时间
### © 版本信息

- ProComponents 版本: [@ant-design/pro-form": "^1.18.3]
- umi 版本 ^3.5.0
- 浏览器环境 chrome  96.0.4664.45
- 开发环境 [win11]

**Comment by chenshuai2144** [comment]
你触发一下formart 就能看到真实的时间了，这个东西是个引用。不是真实的moment 里面的时间。

**Comment by Donlei** [comment]
@chenshuai2144 

> 你触发一下formart 就能看到真实的时间了，这个东西是个引用。不是真实的 moment 里面的时间。

我就是用moment(time, 'YYYY/MM/DD HH:mm:ss')转换了 ，时间还是不对

**Comment by Donlei** [comment]
@chenshuai2144 用错方法了 ，用format是对的 ，谢谢指点
