### ISSUE TITLE
🧐[问题]我目前有一个需求是要控制proformlist里面可以添加的item数量，比如超过5个隐藏添加按钮，剩1个的时候隐藏删除按钮，就是这么一个正常的需求，怎么都拿不到 proformlist的length，求帮忙，谢。

### ISSUE THREAD

**Issue by Sundyfuther** [ant-design/pro-components#4331]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by Sundyfuther** [comment]
Proformlist有嵌套，临上线发现这个问题，急寻帮助，谢谢。。。

**Comment by niunai2016** [comment]
我也想自定义”添加一行数据“的按钮，在超过一定数量后隐藏这个按钮

**Comment by niunai2016** [comment]
可以用额外的方法处理你的问题
let len = 0
// 通过这个可以计算添加的行数
itemRender={({ listDom, action }, { record, fields }) => {
  len = fields.length
  console.log('@@@ length', fields.length);
}}
// 隐藏添加按钮
creatorButtonProps={len >= 5 ? false : {
  creatorButtonText: '再添加一个',
}}
// 控制删除按钮
actionRender={(props, action, defaultActionDom) => {
  // 只显示删除按钮，也可以通过
  let dom = defaultActionDom.filter((item) => item.key === 'delete');
  return len === 1 ? [] : dom;
}}

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这是一个很友好的回复，提供了直接贡献代码的方式，同时也提到了需要提供的相关信息。感谢开发者的积极回复和贡献精神！
