### ISSUE TITLE
🐛[BUG]页码刷新和条数切换刷新的问题

### ISSUE THREAD

**Issue by azx1985** [ant-design/pro-components#4333]
### 🐛 bug 描述

protable，在筛选栏中输入值，直接使用页码刷新或者是条数切换刷新，不会讲筛选栏中的值带入查询，但是查询按钮有loading的效果，这样导致用户以为把筛选栏中的值带入查找了

### 📷 复现步骤

网址https://procomponents.ant.design/components/table/?current=2&pageSize=10   
1、在查询表格的标题输入框里输入一个值；
2、用页码刷新表格，接口里面可以看到未传入输入框的值，但是查询按钮有loading的效果；

### 🏞 期望结果

当未传入参数时查询按钮的loading效果去掉；
或者直接可以传入参数；

**Comment by chenshuai2144** [comment]
没看懂你的意思是什么？

**Comment by azx1985** [comment]
在https://procomponents.ant.design/components/table/?current=2&pageSize=10这里，我用查询表格的demo，在标题里输入aa，然后点击查询，接口是https://proapi.azurewebsites.net/github/issues?current=2&pageSize=10&title=aa，然后我把标题里输入的内容去掉，我不点击查询，直接用，页码调用接口，还是https://proapi.azurewebsites.net/github/issues?current=2&pageSize=10&title=aa，也就是查询才变更了传的参数

**Comment by azx1985** [comment]
https://procomponents.ant.design/components/table/?current=2&pageSize=10，
我用查询表格的demo，在标题里输入aa，然后点击查询，
查看接口是https://proapi.azurewebsites.net/github/issues?current=2&pageSize=10&title=aa，
然后我把标题里输入的内容去掉，我不点击查询，直接用页码调用接口，还是https://proapi.azurewebsites.net/github/issues?current=2&pageSize=10&title=aa，
也就是查询才变更了传的参数

**Comment by chenshuai2144** [comment]
只能想办法在设计上规避一下了，暂时没有比较好的办法
