### ISSUE TITLE
🧐[问题]页面引入 ProList，报该错误：Unhandled Rejection (Error): Module build failed (from ./node_modules/@umijs/bundler-webpack/lib/webpack/plugins/mini-css-extract-plugin/src/loader.js):

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#4337]
![image](https://user-images.githubusercontent.com/12421552/147059930-fe0be359-014d-4453-adf2-a0a2b9696cbc.png)

![image](https://user-images.githubusercontent.com/12421552/147060024-6008e633-3e7f-43e6-a37d-118e6370937f.png)

![image](https://user-images.githubusercontent.com/12421552/147060085-002d032a-3bc3-4e6b-badd-7c3432fd661c.png)

页面引入 ProList，报该错误

v5版本

**Comment by wulei7528** [comment]
![image](https://user-images.githubusercontent.com/19732041/147063910-912feae3-c298-4e93-addf-64f1d5ead763.png)
pro-table好像都报这样的错了

**Comment by chenshuai2144** [comment]
不要锁antd 的包，把 antd 升级到4.17
