### ISSUE TITLE
breadcrumbRender is not working in PageContainer's header🐛[BUG]

### ISSUE THREAD

**Issue by lb603487485** [ant-design/pro-components#4338]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

The method passed to breadcrumbRender under PageContainer's header never run.
It was working "@ant-design/pro-layout": "6.14.0",

### 📷 复现步骤

<PageContainer 
    header={{
        breadcrumbRender: (props, original) => {
                    console.log("any console");
                    return ReactNode
               }
    }}
>

</PageContainer>

### 🏞 期望结果

The breadcrumb would be replaced by my ReactNode. But right now, the console didn't even log "any console".

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
    "@ant-design/icons": "^4.5.0",
    "@ant-design/pro-card": "^1.18.3",
    "@ant-design/pro-descriptions": "^1.10.3",
    "@ant-design/pro-form": "1.49.1",
    "@ant-design/pro-layout": "6.31.7",
    "@ant-design/pro-list": "^1.20.1",
    "@ant-design/pro-table": "2.57.3",
    "@umijs/route-utils": "^1.0.37",
    "antd": "^4.17.0",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "react-pdf": "^5.4.1",
    "umi": "^3.5.20",
    "umi-serve": "^1.9.10",
    "xlsx": "^0.17.4"
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS] Windows
-

**Comment by 2724635499** [comment]
确实存在这个问题
