### ISSUE TITLE
🐛[BUG]ModalForm和DrawerForm没有关闭动画

### ISSUE THREAD

**Issue by zXuff** [ant-design/pro-components#4339]
### 🐛 bug 描述

ModalForm和DrawerForm在配置了visible和destroyOnClose=true时，没有关闭动画

### 📷 复现步骤

ModalForm配置visible
modalProps配置destroyOnClose=true
关闭ModalForm
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
最新版本已经修复，更新下

**Comment by zXuff** [comment]
> 最新版本已经修复，更新下

还是不好使，普通情况下没问题，但在配置visible和destroyOnClose为true时，还是没有关闭动画

**Comment by chenshuai2144** [comment]
看看你的版本是不是最新的。最新的没有问题的。
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/8186664/154203036-749ab798-806d-4074-b565-c0834e61b8f7.png">
