### ISSUE TITLE
🐛[BUG]pro-table一堆问题

### ISSUE THREAD

**Issue by antgodev** [ant-design/pro-components#434]
### 🐛 bug 描述

pro-table一堆问题
之前CreateForm无样式，一系列问题，导致我花了几天出来，目前发现的是已经严重影响开发了
1、fieldProps无效、formItemProps报错
2、formItemProps rules设置居然控制了搜索
3、能不能不要搞这种低级BUG

### 📷 复现步骤

"@ant-design/pro-table": "^2.7.1",

``

{
      title: '登录账号',
      dataIndex: 'account',
      //sorter: true,
      formItemProps: {
        rules: [
          {
            required: true,
            message: '登录账号为必填项',
          },
        ]
      }
    },

``

<img width="1617" alt="WX20200909-151917@2x" src="https://user-images.githubusercontent.com/63995295/92567192-ea295f80-f2af-11ea-91c1-7a633e5d0036.png">

### 🏞 期望结果

能不能不要搞这种低级BUG，测试好了再发布行不行，没测试的能不能法不测试版，不要把用户当小白了

### 💻 复现代码

``
{
      title: '登录账号',
      dataIndex: 'account',
      //sorter: true,
      formItemProps: {
        rules: [
          {
            required: true,
            message: '登录账号为必填项',
          },
        ]
      }
    },

``

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 ^3.2.19
- 浏览器环境 Microsoft Edge 85.0.564.44 
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="567" alt="WX20200909-152425@2x" src="https://user-images.githubusercontent.com/63995295/92568055-2b6e3f00-f2b1-11ea-902e-e2b1e9611c91.png">

**Comment by chenshuai2144** [comment]
多来看看github ，我们在2.5-2.7 之间更换了架构，导致了一些bug，提了之后我们会及时相应修复的。



你这个表格做的挺漂亮的，信息密度很高

**Comment by itsuki0927** [comment]
@chenshuai2144 原来是换了架构, 现在有一些代码, 看的我有点云里雾里,没搞懂为啥要这么用,最直接的就是`formItemProps`和`fieldProps, 文档还有一些需要相对应的更新, 比如说`renderFormItem`.

**Comment by chenshuai2144** [comment]
是的 ，最终是为了能用一个组件实现增删改查.所以需要很多透传.这几个收起来就是防止需要透传的太多了

**Comment by itsuki0927** [comment]
@chenshuai2144  我感觉`@ant-design/pro-utils`里面的一些方法名有歧义, 比如说`pickUndefined`,就我个人从字面上来理解是挑选出值为undefined的字段组成一个新对象,但是源码确实刚刚相反, 我感觉`omitUndefined`更适合一些, 不知道你的意见?

**Comment by chenshuai2144** [comment]
我英语很差 你可以提pr的

**Comment by hengkx** [comment]
所有的库 出来 都是需要一个时间的 没有什么 可以一出来 就那么 完美 包括 antd 也一直都存在 bug 也一直 在修复

**Comment by blinkMyEyesConsciously** [comment]
@antgodev 你好  我看你这个布局非常好 请问是自己写的吗 还是Pro的功能

**Comment by jockey100332** [comment]
> > 你这个表格做的挺漂亮的，信息密度很高
> 
> 多来看看github ，我们在2.5-2.7 之间更换了架构，导致了一些bug，提了之后我们会及时相应修复的。
> 
> 我们正在努力的提高测试覆盖率，现在只有百分之82左右，你也可以帮忙来做一些用例来保证你的项目稳定运行。开源项目的优点就在于你可以影响这个项目

确实是需要锁定一个版本号。现在一到部署就出现问题，多数使用pro-table 的组件开发的，很揪心

**Comment by sillybbb** [comment]
可以 暴躁老哥 这些我也遇见了 曲线救国 解决了
