### ISSUE TITLE
🧐[问题]ProTable组件有什么API能改变某一列的背景色

### ISSUE THREAD

**Issue by jcai** [ant-design/pro-components#4340]
ProTable/Table 组件有什么办法能改变某一列的背景色?

**Comment by haungxinyan** [comment]
render?

**Comment by chenshuai2144** [comment]
antd 有个斑马行的设置，你可以去看看

**Comment by jcai** [comment]
斑马行,rowClassName 只是设置行，我想设置某一列的颜色。 @chenshuai2144

**Comment by chenshuai2144** [comment]
你css写个hover不就好了

**Comment by jcai** [comment]
不是响应鼠标hover，直接变成某种颜色

**Comment by TangMonk** [comment]
render: (text) => {
                return {
                   children: text,
                    props: {
                        style: { background: 'red' }
                    }
                }
            }
