### ISSUE TITLE
Variable @primary-color-hover is undefined

### ISSUE THREAD

**Issue by Iveon** [ant-design/pro-components#4343]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
yarn upgrade

### What is expected?
不出现

### What is actually happening?
ModuleBuildError: Module build failed (from ./node_modules/@umijs/deps/compiled/less-loader/cjs.js):

    &:hover {
      color: @primary-color-hover;
           ^
Variable @primary-color-hover is undefined
      in Admin\node_modules\@ant-design\pro-form\es\components\List\index.less (line 54, column 13)

**Comment by zhiyuanL** [comment]
Exactly the same issue here, @ant-design/pro-table 2.61.0

**Comment by hellozhaoxudong** [comment]
"@ant-design/pro-card": "^1.18.2"
该问题需要怎么解决？

**Comment by seek-x2y** [comment]
将一个个包回退版本并指定版本安装，不采用最新版本
```
 npm i @ant-design/pro-card@1.18.0 --save
 npm i @ant-design/pro-form@1.50.0 --save
 npm i @ant-design/pro-tabel@2.61.0 --save
```

**Comment by jackieli123723** [comment]
同问

**Comment by wangmeijian** [comment]
> 将一个包回滚到该版本并安装指定版本而不是使用最新版本 将一个包回退版本，指定版本安装，不采用最新版本
> 
> ```
>  npm i @ant-design/pro-card@1.18.0 --save
>  npm i @ant-design/pro-form@1.50.0 --save
>  npm i @ant-design/pro-tabel@2.61.0 --save
> ```
> 
> 我这里的已经解决了

没有这个版本 @ant-design/pro-tabel@2.61.0

**Comment by Iveon** [comment]
我是暂时在node_modules/antd/es/style/themes/default.less
第116行 添加了
@primary-color-hover: @link-hover-color;

`// LINK
@link-color: @primary-color;
@link-hover-color: color(~`colorPalette('@{link-color}', 5) `);
@link-active-color: color(~`colorPalette('@{link-color}', 7) `);
@link-decoration: none;
@link-hover-decoration: none;
@link-focus-decoration: none;
@link-focus-outline: 0;
@primary-color-hover: @link-hover-color;`

**Comment by Peterlhx** [comment]
将antd包更新到最新版本即可

**Comment by frankgo81** [comment]
> antd

prob. solved. thanks.

**Comment by kid1412z** [comment]
> 将antd包更新到最新版本即可

更新的最新的包  protable expandedRowRender 鼠标移动到行上会多次执行， 不更新就出现这个错误

**Comment by kid1412z** [comment]
"@ant-design/pro-form": "~1.42.0",
"@ant-design/pro-table": "~2.54.4",
"antd": "~4.16.13",
目前尝试了很多 这个版本组合是可以跑起来的

**Comment by chenshuai2144** [comment]
最好的办法是升级antd，不要乱搞

**Comment by CHENbt** [comment]
antd 版本从低到高换了个遍，还是一样的
`
"antd": "^4.1.0",
"@ant-design/pro-card": "^1.18.0",
`



异常信息：
`
in ./node_modules/@ant-design/pro-card/es/components/Card/index.less

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/af-webpack/node_modules/less-loader/dist/cjs.js):


  &-extra {
    color: @card-head-extra-color;
         ^
Variable @card-head-extra-color is undefined
      in /usr/local/webWorkspace/AppTestAdminWeb/node_modules/@ant-design/pro-card/es/components/Card/index.less (line 168, column 11)
    at /usr/local/webWorkspace/AppTestAdminWeb/node_modules/webpack/lib/NormalModule.js:316:20
    at /usr/local/webWorkspace/AppTestAdminWeb/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /usr/local/webWorkspace/AppTestAdminWeb/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/usr/local/webWorkspace/AppTestAdminWeb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)

 @ ./node_modules/@ant-design/pro-card/es/components/Card/index.js 22:0-22
 @ ./node_modules/@ant-design/pro-card/es/ProCard.js
 @ ./node_modules/@ant-design/pro-card/es/index.js
 @ ./src/pages/Dashboard/HomePage/components/IntrodeuceRow.jsx
 @ ./src/pages/Dashboard/HomePage/index.jsx
 @ ./src/pages/.umi/router.js
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js
`

哪位大佬能帮忙从中看出些端倪

**Comment by chenshuai2144** [comment]
那就锁版本吧，锁包一时爽

**Comment by zcge** [comment]
我比较简单，既然它没有定义就定义一下，，你可以在config 的theme 里配置下 
 theme: {
    'primary-color-hover': defaultSettings.primaryColor,
    'primary-color': defaultSettings.primaryColor,
  },   这样解决是不是比较简单

**Comment by 377781209** [comment]
Variable @primary-color-hover is undefined
这个报错可以先暂时设置一下@primary-color-hover
在config/config.ts中设置一个less变量可解

export default defineConfig({
  theme: {
    'primary-color-hover': '#fff',
  },
});

**Comment by HeWenKe** [comment]
在pro-xxx 需要的基础样式是从antd引入过来的，但是antd 的基础变量里面 把这个删除了，导致使用pro-xx系列 组件的时候会报错这个问题手动改当然它也可以解决，但是这样不合适

**Comment by HeWenKe** [comment]
把antd 更新到最新版，如果可能的话，全部更新到最新版
