### ISSUE TITLE
🧐[问题] 我的 SettingDrawer 无法出现主题色，请问是什么地方没有配置对吗？

### ISSUE THREAD

**Issue by lgh-qt** [ant-design/pro-components#4344]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 💻 示例代码
 <SettingDrawer
              enableDarkTheme
              settings={initialState?.settings}
              hideHintAlert={true}
              hideCopyButton={true}
              disableUrlParams={true}
              enableDarkTheme={true}
              colorList={[
                { key: 'daybreak', color: '#1890ff' },
                { key: 'dust', color: '#F5222D' },
                { key: 'volcano', color: '#FA541C' },
                { key: 'sunset', color: '#FAAD14' },
                { key: 'cyan', color: '#13C2C2' },
                { key: 'green', color: '#52C41A' },
                { key: 'geekblue', color: '#2F54EB' },
                { key: 'purple', color: '#722ED1' },
              ]}
              onSettingChange={(settings) => {
                console.log(settings, 'settingssettingssettingssettingssettings');
                setInitialState((preInitialState) => ({ ...preInitialState, settings }));
              }}
            />

**Comment by lgh-qt** [comment]
![image](https://user-images.githubusercontent.com/33716733/147306217-d5462918-119e-41c3-bbf1-00a6220c5e02.png)

**Comment by rongxingsun** [comment]
同问

**Comment by chenshuai2144** [comment]
升级到beta版本 现在正式版本还没上这个功能 存量用户太多

**Comment by lgh-qt** [comment]
同样还有一个问题，国际化配置并不生效，不管是 ConfigProvider  包裹  以及删除 国际化  都无法更改语言（会跟随系统语言）

**Comment by chenshuai2144** [comment]
注意下 es 和 lib 的区别

**Comment by chenshuai2144** [comment]
注意下 es 和 lib的区别
