### ISSUE TITLE
🐛[BUG]build 又失败了，提示ts error

### ISSUE THREAD

**Issue by PlutoCA** [ant-design/pro-components#4345]
![image](https://user-images.githubusercontent.com/31099607/147308382-bfc9e929-de2f-427f-82f4-578e8e3c4cd1.png)
 
像是这里的类型不兼容了 https://github.com/ant-design/pro-components/commit/ae47b86dea7bbe2fb059701b393fe49cc1093d66

**Comment by Harvey-zhu** [comment]
遇到了同样的问题，求解决方案

**Comment by PlutoCA** [comment]
> 遇到了同样的问题，求解决方案

得大佬重新发版，还得修复兼容type

**Comment by PlutoCA** [comment]
@chenshuai2144 大佬

**Comment by chenshuai2144** [comment]
来个pr吧
