### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by adkslf** [ant-design/pro-components#4346]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述 

引入pro-table后，配置columns中valueType为image，控制台会出现警告： Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### 📷 复现步骤
columns中 valueType:'image'或valueType:{type:'image',width:80}

### 🏞 期望结果

控制台不出现警告

### 💻 复现代码

const columns: ProColumns<TableListItem>[] = [
...
  {
    title: '图片',
    dataIndex: 'pic',
   // valueType:'image',
    valueType: {
      type: 'image',
      width:80
    },
    hideInSearch: true,
  },
 ...
 ]

### © 版本信息

- ProComponents 版本: pro-table:2.56.3
- umi 版本:^3.5.0
- 浏览器环境:Google
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![Uploading image.png…]()
![Uploading image.png…]()

**Comment by floki2020** [comment]
是这个告警吗？
`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

**Comment by 13632632437** [comment]
> 

我也遇到这个,不知怎么解决
表格添加
  {
            title: '图片',
            dataIndex: 'image',
            key: 'image',
            valueType: 'image',
        },
就会报错
devScripts.js:6523 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ForwardRef(ProField)`.

**Comment by 13632632437** [comment]
{
            title: '图片',
            dataIndex: 'image',
            key: 'image',
            render: (_) => <Image
                width={40}
                src={_}
            />
        },

**Comment by 13632632437** [comment]
这样一样的效果   
{
            title: '图片',
            dataIndex: 'image',
            key: 'image',
            render: (_) => <Image
                width={40}
                src={_}
            />
        },

**Comment by 13632632437** [comment]
<Image width={40} src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png"/>

**Comment by 13632632437** [comment]
<Image width={40} src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png" onClick={()=>alert(123)} />

**Comment by 13632632437** [comment]
<Image width={40} src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png" onclick={()=>alert(123)} />

**Comment by 13632632437** [comment]
这样一样的效果  
{
            title: '图片',
            dataIndex: 'image',
            key: 'image',
            render: (_) => <Image(啊啊啊,这个标签会被识别,难受)
                width={40}
                src={_}
            />
        },

**Comment by zhouzyc** [comment]
同样问题请问解决了吗？

**Comment by lisalin880505** [comment]
遇到同样的问题了，有解决方案了吗

**Comment by lisalin880505** [comment]
我用yarn install了后，居然没报错了。。。。。。。。。。。。。。。

**Comment by baibaibai455** [comment]
我依然存在这个问题 

       "@ant-design/pro-table": "^2.62.0",
        "antd": "^4.18.2",
        "umi": "^3.5.20",

**Comment by baibaibai455** [comment]
我依然存在这个问题 

       "@ant-design/pro-table": "^2.62.0",
        "antd": "^4.18.2",
        "umi": "^3.5.20",
