### ISSUE TITLE
🧐[问题]可否对ProList Metas的编辑输入框进行style配置？

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#4347]
![image](https://user-images.githubusercontent.com/12421552/147330395-23e65705-4ec5-4a17-9deb-4fcac0ba1d80.png)

比如我想配置title的长度，description的默认高度之类的配置。

如果我想做其他样式的，是不是需要用自定义更好一些？

**Comment by edifangyi** [comment]
找到了，
![Uploading image.png…]()

**Comment by 1247748612** [comment]
formItemProps: { width: 'xl', }
这样不行吗？

**Comment by edifangyi** [comment]
> formItemProps: { width: 'xl', } 这样不行吗？

![image](https://user-images.githubusercontent.com/12421552/147334200-ebc4b12e-c1bf-4ec3-8bfd-38e7f47f5349.png)

没有这个项。最新的ProList

**Comment by chenshuai2144** [comment]
应该能用，但是ts定义确实，有兴趣来个pr，把prolist 和 table 的能力对其一下
