### ISSUE TITLE
🧐[问题]  请问 antdprotable 如何配置pagination，使其page和pagesize参数不要被带入到浏览器url中

### ISSUE THREAD

**Issue by dataknower** [ant-design/pro-components#4348]
![image](https://user-images.githubusercontent.com/19550451/147336043-45ebd58e-c89a-4283-9cb8-e3e783ff8098.png)
如图，初始化和切换页码时，不希望把翻页参数带到url中，该如何配置？

**Comment by chenshuai2144** [comment]
关掉 syncToUrl

**Comment by chenshuai2144** [comment]
syncToUrl | 同步参数到 url 上,url 只支持 string，在使用之前最好读一下url 中的参数类型 | true \| (values,type)=>values | -
-- | -- | -- | --
