### ISSUE TITLE
🧐[问题]pro-table是否有封装"通过 filterDropdown 自定义的列筛选功能，并实现一个搜索列的示例。"

### ISSUE THREAD

**Issue by l745230** [ant-design/pro-components#4351]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

我印象中好像Pro-table有封装了列的自定义筛选. 并提供了一个文本框的搜索条件.  最近想看下此API,发现文档已经被替换掉了,并且很多内容都不齐. 已经找不到了.

### 💻 示例代码

https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel

**Comment by chenshuai2144** [comment]
table的配置会覆盖掉的，放心用吧
