### ISSUE TITLE
ProFormSelect  如何传递对象集合给后端,🧐[问题]

### ISSUE THREAD

**Issue by zhangyuanlin666** [ant-design/pro-components#4354]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

在使用表单提交数据时, 表单中的数据时从后端获取的, 数据格式是个对象集合. 我需要原样传递给后端.   ProFormSelect传递的是个数组
### 💻 示例代码
/**
 * 新增用户角色下拉列表
 */
const handleRoleList = async () => {
  
  try {
    //前端显示的用户角色数据
    const _roles = [];
    //获取角色列表
    const roles = await getAllRoles();
    //遍历角色列表
    roles.map(item => {
      _roles.push({
        label: item.roleName, value: item.roleId
      })
    });
    return _roles;
  } catch (error) {
    return [];
  }
}
//表单部分
<ProFormSelect
            width="md"
            request={handleRoleList}
            fieldProps={{ mode: 'multiple', }}
            name="roles"
            label="用户角色" />

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/66874263/147431227-0c05da5a-6cb2-4e64-ab4c-4e767d347050.png)

**Comment by 1247748612** [comment]
**给value就够了，为何要这么传？？**

你可以拿到role的value，然后遍历roleList取到对应对象

**Comment by Renderz** [comment]
> 提问前先看看：
> 
> https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
> 
> ### 🧐 问题描述
> 在使用表单提交数据时, 表单中的数据时从后端获取的, 数据格式是个对象集合. 我需要原样传递给后端. ProFormSelect传递的是个数组
> 
> ### 💻 示例代码
> /**
> 
> * 新增用户角色下拉列表
>   */
>   const handleRoleList = async () => {
> 
> try { //前端显示的用户角色数据 const _roles = []; //获取角色列表 const roles = await getAllRoles(); //遍历角色列表 roles.map(item => { _roles.push({ label: item.roleName, value: item.roleId }) }); return _roles; } catch (error) { return []; } } //表单部分 <ProFormSelect width="md" request={handleRoleList} fieldProps={{ mode: 'multiple', }} name="roles" label="用户角色" />
> 
> ### 🚑 其他信息
> ![image](https://user-images.githubusercontent.com/66874263/147431227-0c05da5a-6cb2-4e64-ab4c-4e767d347050.png)

参照antd 的select组件，可以选择labelInValue试试？然后具体结构自己转一下

**Comment by zhangyuanlin666** [comment]
> **给value就够了，为何要这么传？？**
> 
> 你可以拿到role的value，然后遍历roleList取到对应对象

**Comment by zhangyuanlin666** [comment]
> **给value就够了，为何要这么传？？**
> 
> 你可以拿到role的value，然后遍历roleList取到对应对象

是的给后端value也是可以的, 但是这样的话后端还要处理,比较麻烦.   对象是可以拿到，但是不知道如何传递。目前该字段的value是个数组。

**Comment by Renderz** [comment]
数组转对象。 for或者Object.keys进去遍历一下

**Comment by zhangyuanlin666** [comment]
> > 提问前先看看：
> > https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
> > ### 🧐 问题描述
> > 在使用表单提交数据时, 表单中的数据时从后端获取的, 数据格式是个对象集合. 我需要原样传递给后端. ProFormSelect传递的是个数组
> > ### 💻 示例代码
> > /**
> > 
> > * 新增用户角色下拉列表
> >   */
> >   const handleRoleList = async () => {
> > 
> > try { //前端显示的用户角色数据 const _roles = []; //获取角色列表 const roles = await getAllRoles(); //遍历角色列表 roles.map(item => { _roles.push({ label: item.roleName, value: item.roleId }) }); return _roles; } catch (error) { return []; } } //表单部分 <ProFormSelect width="md" request={handleRoleList} fieldProps={{ mode: 'multiple', }} name="roles" label="用户角色" />
> > ### 🚑 其他信息
> > ![image](https://user-images.githubusercontent.com/66874263/147431227-0c05da5a-6cb2-4e64-ab4c-4e767d347050.png)
> 
> 参照antd 的select组件，可以选择labelInValue试试？然后具体结构自己转一下

![image](https://user-images.githubusercontent.com/66874263/147478510-cbc4b5d3-c526-49a1-af29-3cc00c2046d9.png)
数据结构是我想要的了,但是键值无法改变了,传给后台还是需要修改.

**Comment by chenshuai2144** [comment]
试试 transform ，在提交之前会执行这个转化，你可以对value做任何事

```
transform: (value) => {
        return {
          startTime: value[0],
          endTime: value[1],
        };
      },
```
