### ISSUE TITLE
🧐[问题]动态表单的值重置

### ISSUE THREAD

**Issue by ALongLi** [ant-design/pro-components#4358]
### 🧐 问题描述

官方例子 搜索表单自定义 ，当切换月份和周后，如何将动态表单的值重置为空
现在月份之后，选择一月，切换自定义后，一月对应的值 1出现在 输入框中
### 💻 示例代码

https://codesandbox.io/s/sou-suo-biao-dan-zi-ding-yi-forked-4zf1f?file=/App.tsx

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20749911/147454916-63773382-82a2-41d7-b643-102dde2f5970.png)

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/editable-table#与编辑表格外的内容联动

```tsx
{
      title: '计分方式',
      dataIndex: 'scoringMethod',
      valueType: 'select',
      request: async () => [
        {
          value: 'discrete',
          label: '离散型',
        },
        {
          value: 'continuous',
          label: '连续型',
        },
      ],
      fieldProps: (form, { rowKey }) => {
        return {
          onSelect: () => {
            // 每次选中重置参数
            const newValue = set({}, [rowKey || [], 'fraction'].flat(1), []);
            form.setFieldsValue(newValue);
          },
        };
      },
    },
```

这里有个demo，可以看下。
