### ISSUE TITLE
🐛[BUG]proTable组件数据编辑时会影响相似id数据状态

### ISSUE THREAD

**Issue by Ryang-H** [ant-design/pro-components#4359]
组件：antd的proComponents，其中proTable组件。
    问题：对数据进行单编辑或多编辑时，设置rowkey='id'，例如对数据id为574的数据进行编辑，这时id为5,7,4,57,74的数据都会变为编辑状态，且这些数据无法取消编辑状态，必须通过id为574的数据取消。
    期望：编辑当前数据时其它数据不会收到影响
    版本："@ant-design/pro-table": "^2.57.1"

Component: procomponents of antd, where protable component.
Problem: when editing data in a single or multiple way, set rowkey ='id '. For example, when editing data with data ID 574, the data with ID 5,7,4,57,74 will change to the editing state, and these data cannot be cancelled. They must be cancelled through the data with ID 574.
Expectation: other data will not be affected when editing the current data
Version: '@ Ant Design / Pro table': '^ 2.57.1'

**Comment by chenshuai2144** [comment]
已经修掉了，更新到最新版本就可以。

是算法的问题
