### ISSUE TITLE
🧐[问题]ProTable、ProList 是否有ghost（幽灵模式）？

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#4360]
ProTable、ProList 想让他们背景是透明的
设置

![image](https://user-images.githubusercontent.com/12421552/147463867-f09d5db7-0bf4-4683-b9ad-504a4ef2ad07.png)

上面的使用ProList
下面使用的是List

**Comment by edifangyi** [comment]
cardProps 好像没得这类参数

**Comment by chenshuai2144** [comment]
现在只能card props 硬设置了，有个style 可以打上去

**Comment by chenshuai2144** [comment]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/8186664/147539235-5e8cc0c2-dd63-44f2-9e74-3c0241444109.png">



等待下官方支持
