### ISSUE TITLE
🐛[BUG]valueType 分别选了text，digst宽度表现居然不一样

### ISSUE THREAD

**Issue by 0x457** [ant-design/pro-components#4361]
### 🐛 bug 描述
valueType 分别选了text，digst宽度表现居然不一样

![image](https://user-images.githubusercontent.com/5813610/147522611-b36e804f-8619-44be-b539-6ce9c23c66fe.png)
![image](https://user-images.githubusercontent.com/5813610/147522661-fe5a002b-c43d-485c-9f5a-97eb682a12b2.png)
![image](https://user-images.githubusercontent.com/5813610/147522674-a836a3d1-d811-4e46-896e-f8f50c7144ea.png)
![image](https://user-images.githubusercontent.com/5813610/147522693-64cde07c-05cd-40b8-af0a-bbe5ac339022.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by PlutoCA** [comment]
得手动设置宽度100%

**Comment by 0x457** [comment]
I done
