### ISSUE TITLE
🐛[BUG] 列配置，取消勾选任意数量后，刷新页面，点击重置，无效果

### ISSUE THREAD

**Issue by linxianxi** [ant-design/pro-components#4364]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by linxianxi** [comment]
@chenshuai2144  官网文档第一个例子就行

**Comment by 2724635499** [comment]
> @chenshuai2144 官网文档第一个例子就行

哪个？

**Comment by linxianxi** [comment]
> > @chenshuai2144 官网文档第一个例子就行
> 
> 哪个？

就第一个啊，有本地存储的

**Comment by chenshuai2144** [comment]
再试试。
