### ISSUE TITLE
重新给LightFilter内的表单项指定属性不生效🐛[BUG]

### ISSUE THREAD

**Issue by xiaoquzhao** [ant-design/pro-components#4366]
packages/form/src/layouts/LightFilter/index.tsx文件中判断是否重新渲染子组件的依据的是子组件的数量变化，这样会导致当给LightFilter内的表单项重新指定属性时不生效，例如给内部的下拉框赋新的数据源时就会一直不生效，最简单的改法是将props.items.length改为props.items
<img width="601" alt="code" src="https://user-images.githubusercontent.com/8214514/147557222-bfcb7036-efda-4ebf-829b-2d4ee245e29a.png">

**Comment by 2724635499** [comment]
确实存在这个问题，本地可以直接复现
