### ISSUE TITLE
🐛[BUG]ProTable  设置了locale ,但是pagination不生效

### ISSUE THREAD

**Issue by leehomeok** [ant-design/pro-components#4367]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 💻 复现代码

import enUSIntl from 'antd/lib/locale/en_US';
import zhCNIntl from 'antd/lib/locale/zh_CN';

 let locale = localStorage.getItem('umi_locale') || 'en-US'
  let localeMap = {
    'en-US': enUSIntl,
    'zh-CN': zhCNIntl
  }
  let curLocale = localeMap[locale]
<ProTable<LogListItem>
        scroll={{ scrollToFirstRowOnChange: true, x: 'max-content' }}
        actionRef={actionRef}
        rowKey="loginTime"
        request={params => onLoad(params)}
        columns={columns}
        toolBarRender={false}
        locale={curLocale['Pagination']}
        search={
          {
            searchText: formatMessage({id: 'search'}),
            resetText: formatMessage({id: 'reset'}),
          }
        }
      />

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
pagination 是antd的，按照antd的办法来修改
