### ISSUE TITLE
👑 [需求]proTable实现表格可伸缩列

### ISSUE THREAD

**Issue by hwf520** [ant-design/pro-components#437]
### 🧐 解决方案
    结合官方文档，进行封装，写成配置的形式，拉伸为true/false进行控制是否可以拉伸。

**Comment by hwf520** [comment]
抱歉，已经修改了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "陈帅"<notifications@github.com&gt;; 
发送时间: 2020年9月9日(星期三) 下午4:51
收件人: "ant-design/pro-components"<pro-components@noreply.github.com&gt;; 
抄送: "Traveling light"<1798274010@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ant-design/pro-components] 👑 [需求] (#437)





 
不写标题会关掉你

**Comment by chenshuai2144** [comment]
这个 antd 官方有个 demo，我们暂时不会支持的

**Comment by hwf520** [comment]
我知道官方有一个demo，但他还需要安装依赖，如果想每个使用的话，要先进行封装，每个页面要引用的话，也要加上额外的代码，我感觉本应该就要像layui那种原生就有，但不知道是基于什么考虑，官方没有封装这个功能，还需要自己加代码才生效。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "陈帅"<notifications@github.com&gt;; 
发送时间: 2020年9月9日(星期三) 晚上7:00
收件人: "ant-design/pro-components"<pro-components@noreply.github.com&gt;; 
抄送: "Traveling light"<1798274010@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ant-design/pro-components] 👑 [需求]proTable实现表格可伸缩列 (#437)





 
这个 antd 官方有个 demo，我们暂时不会支持的

**Comment by chenshuai2144** [comment]
@hwf520 因为事先成本搞 收益小，大家也不紧急。
antd 四五年了

**Comment by hengkx** [comment]
实现这个功能 需要 在内部加依赖把，并不是 所有都有这个 功能， 或者可不可以 判断 用户 有没有 安装依赖 来决定 该功能 是否可用？ 这一块 不确定 是否 可以直接用react native的一些库 可以实现

**Comment by chenshuai2144** [comment]
> react native

和web 生态不兼容的

**Comment by hengkx** [comment]
描述 不正确，我的意思 是 指 用 那种方式 来实现 不是 使用react native的库， 就是 用户 没有安装特定的 依赖 就没有 该功能
