### ISSUE TITLE
🐛[BUG] 分布式表单配合Drawer 使用，样式存在问题

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#4381]
![image](https://user-images.githubusercontent.com/30397655/147725963-937fa3d9-db39-43e6-a985-561ed72e6db1.png)

**Comment by DerrickTel** [comment]
来个demo

**Comment by leshalv** [comment]
直接用官网的demo，把Model改成Drawer即可

**Comment by leshalv** [comment]
这个好处理吗？

**Comment by chenshuai2144** [comment]
用 Space 包一下，或者用 flex 加个 gap
