### ISSUE TITLE
Editable 如下案例，联动场景，如何实时更新dataSource 🧐[问题]

### ISSUE THREAD

**Issue by penglittlebai** [ant-design/pro-components#4382]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 💻 示例代码

代码演示地址： https://codesandbox.io/s/9syj7?file=/App.tsx

需求：修改下图‘状态’的同时，修改‘备注’（非编辑态）和 ‘描述’（编辑态）的值，要求dataSource的值是实时更新的，或者说提交的时候能获取到‘备注’字段的值。这里只是举一个简单例子，真实场景可能是修改‘状态‘字段，然后根据‘状态‘的值调接口后，再设置‘备注’的值

![image](https://user-images.githubusercontent.com/87426994/147731536-3ffaf503-e4fd-4d3c-a819-1fd31dd1ac15.png)

**Comment by chenshuai2144** [comment]
dataSource没有缓存的，你要用map 或者别的方法搞个新的 dataSource，然后赋值给表格。
