### ISSUE TITLE
🐛[BUG] pro-table valueType 为 select 时，options value 为 0 时显示不正常

### ISSUE THREAD

**Issue by calimanco** [ant-design/pro-components#4387]
### 🐛 bug 描述

 pro-table valueType 为 select 时，options value 为 0 时显示不正常，会显示为 0 ，而不是 label 对应的文字。

### 📷 复现步骤

版本："@ant-design/pro-table": "2.61.8","@umijs/preset-react": "^1.8.30",

```javascript
const columns = [{
        title: 'way',
        dataIndex: 'way',
        key: 'way',
        align: 'center',
        valueType: 'select',
        fieldProps: {
          options: [{label: '低', value: 0},{label: '中', value: 1},{label: '高', value: 1}]
        }
}]
```

EditableProTable 的 columns 输入上面配置，当数据为 0 时，非编辑模式会显示 0，而不是“低”。

### 🏞 期望结果

非编辑模式下显示为 “低”。

**Comment by ooPG233** [comment]
#4389 看起来是被修复了
