### ISSUE TITLE
ant pro是否可以支持多页签？？

### ISSUE THREAD

**Issue by linrenqing008** [ant-design/pro-components#439]
ant pro layout框架是否可以实现动态配置多页签

**Comment by chenshuai2144** [comment]
不支持的，在 umi 支持 keep alive 之前都不会支持。

不过你可以自定义来实现，pro 的社区里有很多方案，搜一下 issue 就出来了；

**Comment by blackboy1987** [comment]
https://www.bilibili.com/video/BV1Yf4y167rZ/ 可以看看这个up主的视频

**Comment by drizzlesconsin** [comment]
> 不支持的，在 umi 支持 keep alive 之前都不会支持。
> 
> 不过你可以自定义来实现，pro 的社区里有很多方案，搜一下 issue 就出来了；

看来是不会支持 keep alive https://github.com/umijs/umi/discussions/5989，只能找社区实现方案。
![image](https://user-images.githubusercontent.com/69514654/109456424-c6dbb200-7a93-11eb-8395-c97bbb9c0105.png)

**Comment by drizzlesconsin** [comment]
> 不支持的，在 umi 支持 keep alive 之前都不会支持。
> 
> 不过你可以自定义来实现，pro 的社区里有很多方案，搜一下 issue 就出来了；

看来是不会支持 keep alive https://github.com/umijs/umi/discussions/5989 只能找社区实现方案。
![image](https://user-images.githubusercontent.com/69514654/109456424-c6dbb200-7a93-11eb-8395-c97bbb9c0105.png)

**Comment by feiChen0522** [comment]
> https://www.bilibili.com/video/BV1Yf4y167rZ/ 可以看看这个up主的视频

都没更新完，最后还是没有解决问题
