### ISSUE TITLE
🐛[BUG] protablde的onloaingchange问题

### ISSUE THREAD

**Issue by gary123123** [ant-design/pro-components#4390]
onloadingchange一直返回的是true

https://codesandbox.io/s/cha-xun-biao-ge-forked-ehxgx?file=/App.tsx

![image](https://user-images.githubusercontent.com/26196061/147803478-abf4cbf7-888f-4efe-81f2-177c4b716bb7.png)

**Comment by DerrickTel** [comment]
useMergedState的一个问题。如果是默认值就不调用了，目前看来不符合场景。onXXXValueChange的场景

**Comment by gary123123** [comment]
> useMergedState的一个问题。如果是默认值就不调用了，目前看来不符合场景。onXXXValueChange的场景

那这个会修复吗，还是只能这样

**Comment by DerrickTel** [comment]
> > useMergedState的一个问题。如果是默认值就不调用了，目前看来不符合场景。onXXXValueChange的场景
> 
> 那这个会修复吗，还是只能这样

会的，这个肯定是一个bug
