### ISSUE TITLE
👑 [需求] ProTable 列状态配置 支持传入disabled属性

### ISSUE THREAD

**Issue by D-lyw** [ant-design/pro-components#4392]
### 🥰 需求描述

在我们的业务中，经常通过ProTable的列状态配置属性`columnsState `指定列表每一项的展现与否和浮动情况，目前用户是可以通过列设置操作栏对每一项进行变更的。但在某些列表场景中，我们是希望一经设置，用户是无法通过列设置操作栏对某些列表项进行手动调整的

### 🧐 解决方案

期望在原有的配置能力基础上添加`disabled`属性，配置之后，用户无法通过列操作栏重新设置该列表项的展现和浮动情况
```ts
export type ColumnsState = {
  show?: boolean;
  fixed?: 'right' | 'left' | undefined;
  order?: number;
  // 新增配置项
  disabled?: boolean;
};
```

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/33343571/147815478-e5b33607-972f-4225-bc5e-d787de220f85.png)

**Comment by PlutoCA** [comment]
可以用hideInSetting

**Comment by D-lyw** [comment]
> 可以用hideInSetting

现在业务上就是使用这个方式作为一个妥协方案来实现的，但某些场景上需要展示该列表项但又不允许用户调整该列表项，所以想看ProTable组件能不能在能力上支持这块的配置能力。或者我提个PR补充下这块的能力？

**Comment by zhaomenglu** [comment]
有没有不能设置左固定，过着不能设置右固定的这种配置项
