### ISSUE TITLE
🐛[BUG]ProTable的columns里如果用request，下拉选项内容串了

### ISSUE THREAD

**Issue by caofuchang** [ant-design/pro-components#4393]
### 🐛 bug 描述
一个页面里有两个ProTable，columns里都有一个字段名称是“state”，并且valueType: "select",下拉选项数据用request，
页面渲染之后，两个ProTable的两个“state”下拉框下拉选项内容串了。
![image](https://user-images.githubusercontent.com/40530974/147814606-873a3953-00d3-4c73-81c6-1916a0bbb645.png)

`  <>
    <Page1 />
    <Page2 />
  </>
`

同时显示这两个组件，每个组件内有一个ProTable。搜索条件“状态”，下拉选项数据用request
`  {
    title: "状态",
    dataIndex: "state",
    filters: true,
    onFilter: true,
    valueType: "select",
    request: requestStateMap
  },
`

Page1 里下拉选项请求是 "/selectMap1"
Page2 里下拉选项请求是 "/selectMap2"

### 📷 复现步骤

页面渲染之后，在第一个ProTable里，选中“状态”，然后清空。
在第二个ProTable里，选中“状态”，然后清空。此时，两个下拉框的下拉数据已经串了。
打开浏览器的network，你会发现，请求地址是错的。

点击“重置”按钮的时候，请求才是对的。
![image](https://user-images.githubusercontent.com/40530974/147815304-79475282-dd2c-40f4-a899-693873676175.png)

### 🏞 期望结果

期望这两个下拉框的下拉数据不要串。

### 💻 复现代码
codesandbox 地址：
https://codesandbox.io/s/cha-xun-biao-ge-liang-ge-ye-mian-3y28c?file=/page1.tsx

### © 版本信息
-"@ant-design/pro-table"   2.61.9
- 浏览器环境  Chrome 版本 96.0.4664.110（正式版本） （64 位）

### 🚑 其他信息

我尝试过，在ProTable的配置form里添加name，但是不管用。
`form={{
  name: "form111",
}}`

添加name之后，两个ProTable的搜索form里，字段“状态”的id添加了前缀“form111_”，但是还是会串。

**Comment by 1247748612** [comment]
应该是key相同复用了同一个request，尝试在column定义一个param参数再给个任意值

**Comment by caofuchang** [comment]
> 应该是key相同复用了同一个request，尝试在column定义一个param参数再给个任意值

感谢。
已测试，添加params之后就好了。
 {  
    title: "状态",  
    dataIndex: "state",  
    filters: true,  
    onFilter: true,  
    valueType: "select",  
    request: requestStateMap2,  
    params: { timestamp: Math.random() }  
}
心中还有些疑问。
这两个下拉框，除了字段名相同，dataIndex: "state"。
请求的方法名，请求的地址，都是不一样的。
并且，这两个下拉框分别隶属于两个ProTable，理论上，是不应该判断为同一个request，或者是复用同一个request的。

**Comment by 1247748612** [comment]
> > 应该是key相同复用了同一个request，尝试在column定义一个param参数再给个任意值
> 
> 感谢。 已测试，添加params之后就好了。 { title: "状态", dataIndex: "state", filters: true, onFilter: true, valueType: "select", request: requestStateMap2, params: { timestamp: Math.random() } } 心中还有些疑问。 这两个下拉框，除了字段名相同，dataIndex: "state"。 请求的方法名，请求的地址，都是不一样的。 并且，这两个下拉框分别隶属于两个ProTable，理论上，是不应该判断为同一个request，或者是复用同一个request的。

看了下源码

SWR缓存的key是这样获取的：

![image](https://user-images.githubusercontent.com/29533304/148158550-5aa96d37-7ae7-480a-b9b3-94b89498d1dc.png)

你试试为这两个column分别指定一个不同的key会不会隔离缓存

---

考虑到枚举可以在不同的form，table中复用, 用dataIndex是个合理的实现
假设多个form和table在同一个页面都隔离开，如果这些组件都使用了一个共同的参数dataIndex: 'same'，那这会发起多个请求，response都是同一个结果，造成不必要的开销。

主动隔离缓存可能会是个好选择

**Comment by caofuchang** [comment]
> > > 应该是key相同复用了同一个request，尝试在column定义一个param参数再给个任意值
> > 
> > 
> > 感谢。 已测试，添加params之后就好了。 { title: "状态", dataIndex: "state", filters: true, onFilter: true, valueType: "select", request: requestStateMap2, params: { timestamp: Math.random() } } 心中还有些疑问。 这两个下拉框，除了字段名相同，dataIndex: "state"。 请求的方法名，请求的地址，都是不一样的。 并且，这两个下拉框分别隶属于两个ProTable，理论上，是不应该判断为同一个request，或者是复用同一个request的。
> 
> 看了下源码
> 
> SWR缓存的key是这样获取的：
> 
> ![image](https://user-images.githubusercontent.com/29533304/148158550-5aa96d37-7ae7-480a-b9b3-94b89498d1dc.png)
> 
> 你试试为这两个column分别指定一个不同的key会不会隔离缓存
> 
> 考虑到枚举可以在不同的form，table中复用, 用dataIndex是个合理的实现 假设多个form和table在同一个页面都隔离开，如果这些组件都使用了一个共同的参数dataIndex: 'same'，那这会发起多个请求，response都是同一个结果，造成不必要的开销。
> 
> 主动隔离缓存可能会是个好选择

刚才测试了，添加不同的key确实可以隔离缓存，但是点击“查询”按钮的时候，传的字段名，不是dataIndex的值，而是key的值。
效果等同于，把dataIndex的值改为不同的两个。
截图如下：
![image](https://user-images.githubusercontent.com/40530974/148160727-c6d07315-dbf6-49c9-8bda-bb3ec98bc571.png)

**Comment by 1247748612** [comment]
先用着params做唯一key，之后看看有没有更好的方式

**Comment by caofuchang** [comment]
> 先用着params做唯一key，之后看看有没有更好的方式

好的。谢谢啦！☺

**Comment by chenshuai2144** [comment]
这个两难了，我试着支持一下params的function

**Comment by JoDring** [comment]
改成不同的dataIndex然后用search的transform成同一个, 可以省多次请求接口, 我们项目用到了react keepalive
{
      title: '产品线',
      dataIndex: 'category_id-cn',      
      fieldProps: { showSearch: true },
      request: () => pubProLineList({ business_scope: 'CN' }),
      search: {
        transform: (category_id: any) => ({ category_id }), 
      },
    },
{
      title: '产品线',
      dataIndex: 'category_id-in',
      fieldProps: { showSearch: true },
      request: () => pubProLineList({ business_scope: 'IN' }),
      search: {
        transform: (category_id: any) => ({ category_id }), 
      },
    },

**Comment by JoDring** [comment]
改成不同的dataIndex然后用search的transform成同一个, 可以省多次请求接口, 我们项目用到了react keepalive
{
      title: '产品线',
      dataIndex: 'category_id-cn',      
      fieldProps: { showSearch: true },
      request: () => pubProLineList({ business_scope: 'CN' }),
      search: {
        transform: (category_id: any) => ({ category_id }), 
      },
    },
{
      title: '产品线',
      dataIndex: 'category_id-in',
      fieldProps: { showSearch: true },
      request: () => pubProLineList({ business_scope: 'IN' }),
      search: {
        transform: (category_id: any) => ({ category_id }), 
      },
    },
