### ISSUE TITLE
🧐[问题]自定义组件使用了DatePicker，值是moment，但是使用了自定义组件的ProForm，onFinish中拿到的值是dateString的格式

### ISSUE THREAD

**Issue by B-sirius** [ant-design/pro-components#4395]
### 🧐 问题描述

1. ProForm中使用了自定义组件
2. 自定义组件中用到了DatePicker
3. DatePicker的value绑定的是moment实例
4. 自定义组件对应的value也是moment实例
5. 自定义组件value更新，仍然是moment实例
6. ProForm的onFinish回调，values中拿到的值不是moment实例，而是dateString字符串

这种不一致在实际编码中很容易造成迷惑，不知道这是个feature还是bug

### 💻 示例代码

https://codesandbox.io/s/zi-ding-yi-zu-jian-forked-crv1m?file=/DDatePicker.js

**Comment by rojer95** [comment]
目前好像只能通过`ProForm`的`dateFormatter `设置为`false`使整个表单获取的都是moment才能获取到，
单独某个表单项好像还不行

**Comment by B-sirius** [comment]
> 目前好像只能通过`ProForm`的`dateFormatter `设置为`false`使整个表单获取的都是moment才能获取到， 单独某个表单项好像还不行

我震惊了原来有这个设置！！可以解决我的问题了，不过感觉有点坑呢orz
