### ISSUE TITLE
🧐[问题] 如何动态控制左侧菜单栏隐藏显示

### ISSUE THREAD

**Issue by liushuhui** [ant-design/pro-components#4398]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

有一个场景是，需要在导航头部加一个按钮，控制菜单栏的显示隐藏，请问如何控制，如下图所示

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26155477/148000020-cd74a12a-4ada-432e-8125-ad557a260835.png)

**Comment by 1247748612** [comment]
https://procomponents.ant.design/components/layout#prolayout

![image](https://user-images.githubusercontent.com/29533304/148150594-88b6b21e-b5a4-4c77-bf9d-70a8c0412e0c.png)

自行管理

**Comment by hsg4ok** [comment]
> 

官方文档是写给自己看的，新手在摸索的时候遇到的问题一定是官方文档解决不了的。你要么就不要回答，要么就能帮助被人真正解决问题。你的回答让人感受到了满满的傲慢。

**Comment by 1247748612** [comment]
> 官方文档是写给开发团队自己看的，新手在摸索的时候遇到的问题一定是官方文档解决不了的。你要么就不要回答，要么就能帮助被人真正解决问题。你的回答让人感受到了满满的傲慢。

我认为使用这个库的开发者默认都是掌握react的，但是从你的这段话中，我看出了你对react都是不了解的。

我建议你看看这里的[文档](https://zh-hans.reactjs.org/docs/forms.html#controlled-components)，然后再看看我截的图，你就能理解我说的`自行管理`是什么意思了

---

我觉得我的回答能帮助到需要帮助且看过文档的人，而不是你这种不用闹思考随意指责别人的人。你的评论让你显得非常的**愚蠢**。

**Comment by chenshuai2144** [comment]
用开源项目要有手才行的，如果想要贴身服务最好去购买商业支持的项目。而不是使用开源的

**Comment by hsg4ok** [comment]
> 

这里在说文档的问题，你把问题上升到这么高的层次，是怎么想的？

**Comment by hsg4ok** [comment]
> 



> 用开源项目要有手才行的，如果想要贴身服务最好去购买商业支持的项目。而不是使用开源的

这里在讨论文档问题，你将问题上升到如此的高度，到底是咋想的？

**Comment by hsg4ok** [comment]
> > 官方文档是写给开发团队自己看的，新手在摸索的时候遇到的问题一定是官方文档解决不了的。你要么就不要回答，要么就能帮助被人真正解决问题。你的回答让人感受到了满满的傲慢。
> 
> 我认为使用这个库的开发者默认都是掌握react的，但是从你的这段话中，我看出了你对react都是不了解的。
> 
> 我建议你看看这里的[文档](https://zh-hans.reactjs.org/docs/forms.html#controlled-components)，然后再看看我截的图，你就能理解我说的`自行管理`是什么意思了
> 
> 我觉得我的回答能帮助到需要帮助且看过文档的人，而不是你这种不用脑思考随意指责别人的人。你的评论让你显得非常的**愚蠢**。

这个文档的定位如果不是新手，那就没有问题了。大家随意就好。
