### ISSUE TITLE
🐛[BUG]pro-layout6.4.8版本面包屑不显示

### ISSUE THREAD

**Issue by s464446877** [ant-design/pro-components#440]
### 🐛 bug 描述

目前最新的6.4.8版本不显示面包屑
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/layout#example-%E5%B1%95%E7%A4%BA

看这里

**Comment by s464446877** [comment]
必须要加上PageHeaderWrapper才会显示吗？最新的这个文档里没有这个

**Comment by chenshuai2144** [comment]
这个是的，面包屑就是 PageHeaderWrapper 做的 ，一直都是这样

**Comment by s464446877** [comment]
这个是加在layout里的children外层比较好还是在每个页面都单独添加比较好

**Comment by chenshuai2144** [comment]
每个页面单独添加会比较好一点这样可以支持一下自定义，默认是会自动帮你生成 title 的，但是不是一定是你想要的

**Comment by s464446877** [comment]
好的，谢谢

**Comment by s464446877** [comment]
还请教一下，关于PageHeaderWrapper的配置在哪里

**Comment by itsuki0927** [comment]
@s464446877 可以看看[PageContainer](https://procomponents.ant.design/components/layout#pagecontainer)的API.

**Comment by chenshuai2144** [comment]
改名叫 PageContainer 了
