### ISSUE TITLE
🧐[问题]StepsForm分布表单无法通过className修改ProFormCheckbox.Group样式

### ISSUE THREAD

**Issue by yang-chuanjiang** [ant-design/pro-components#4401]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

![image](https://user-images.githubusercontent.com/38531906/148023363-4b9f15cc-b6c0-42c9-8803-12b047233716.png)
![image](https://user-images.githubusercontent.com/38531906/148023381-7bf8f1cf-7c47-4a25-baa4-29ea93d55b1a.png)

**Comment by yang-chuanjiang** [comment]
注：通过css覆盖去掉required的红色*号

**Comment by chenshuai2144** [comment]
好像不支持这个 api 。required 的 * 号 可以通过 requiredMark 来修改的 

<html>
<body>


requiredMark | 必选样式，可以切换为必选或者可选展示样式。此为 Form 配置，Form.Item 无法单独配置 | boolean \| optional | true | 4.6.0
-- | -- | -- | -- | --



</body>
</html>
