### ISSUE TITLE
👑 [需求]columnEmptyText 逻辑优化

### ISSUE THREAD

**Issue by twinh** [ant-design/pro-components#4402]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

#### 背景

1. 当列数据为空时，`render` 方法里获取到的数据为 `-`，预期为空，与预期不一致，容易导致逻辑错误
2. 如果要获取列的原始数据，需通过第二个参数获取，不够直观

如下例子，头像为空未能如愿展示默认头像

```js
columns={[
    {
      title: '头像',
      dataIndex: 'avatarUrl',
      render: (avatarUrl, row) =>  <Avatar src={{avatarUrl || defaultAvatar}}/>,
    },
}
```

#### 需求

希望 `render` 方法第一个参数能返回原始数据。

### 🧐 解决方案

1. 如果没有设置 `render`，自定义 `render` 来输出 `columnEmptyText`
2. 进一步，即使设置了 `render`，判断 render 返回值为空，也输出 `columnEmptyText`

1 的参考代码

```js
const defaultRenderer = (value) => {
  if (typeof value === 'undefined' || value === '' || value === null) {
    return columnEmptyText;
  } else {
    return value;
  }
};

columns.map((column) => {
  if (typeof column.render === 'undefined') {
    column.render = defaultRenderer;
  }
});
```

**Comment by 1247748612** [comment]
你应该拿row.avatarUrl去做判断
render的第一个参数是dom

**Comment by twinh** [comment]
> 你应该拿row.avatarUrl去做判断 render的第一个参数是dom

是的，所以第二点说了，通过 `row.avatarUrl` 不直观

**Comment by 1247748612** [comment]
> > 你应该拿row.avatarUrl去做判断 render的第一个参数是dom
> 
> 
> 
> 是的，所以第二点说了，通过 `row.avatarUrl` 不直观

renderText处理不了吗

**Comment by twinh** [comment]
> > > 你应该拿row.avatarUrl去做判断 render的第一个参数是dom
> > 
> > 
> > 是的，所以第二点说了，通过 `row.avatarUrl` 不直观
> 
> renderText处理不了吗

`renderText` 也可以处理的

我再举个场景，新用户从 antd 的 Table 组件转过来，或者是参考 ProTable 的例子来写，很自然的就使用 `render` 来输出内容，结果发现输出的不是自己想要的。

这是我提出这个需求想解决的问题。

**Comment by chenshuai2144** [comment]
ts 的类型里面写的很明确的，这个东西就是个dom。
