### ISSUE TITLE
🐛[BUG]ModalForm和DrawerForm在配置visible和destroyOnClose为true时，没有关闭动画

### ISSUE THREAD

**Issue by zXuff** [ant-design/pro-components#4405]
### 🐛 bug 描述

ModalForm和DrawerForm在配置visible和destroyOnClose为true时，没有关闭动画

### 📷 复现步骤

ModalForm或DrawerForm配置visible和onVisibleChange
配置modalProps或drawerProps的destroyOnClose为true
关闭时动画消失

### 💻 复现代码

https://codesandbox.io/s/shi-yong-visible-he-onvisiblechange-forked-eguv3?file=/App.tsx
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by std4453** [comment]
该 bug 于 pro-form 1.50.0 引入，对比 git history 应该是 [这个 commit](https://github.com/ant-design/pro-components/commit/f986ecb9d89d4e3edef18d50eee4c37e730227d9) 导致的

**Comment by slmev** [comment]
我遇到ModalForm destroyOnClose设置为true后，afterClose没有效果的情况

**Comment by std4453** [comment]
bug 的核心原因似乎是这里：

https://github.com/ant-design/pro-components/blob/51a7f1082e64d29920e111b3fa44511c2e7e230f/packages/form/src/layouts/ModalForm/index.tsx#L69-L74

这里的 `isDestroy` 与 `rest.visible` 同步，为 `false` 时则不渲染 trigger 以外的 form 元素，实现 `destroyOnClose` 的效果。

问题在于 Modal 和 Drawer 关闭需要时间，现在这样写，在 `rest.visible` 从 `true` 变为 `false` 时，会立刻使 `isDestroy` 变成 `false`，从而立即 unmount 里面的元素，因此关闭动画就没了。

解决的思路应当是推迟 `isDestroy` 的变化，在关闭动画结束后才设为 `false`，这在 ModalForm 里已经实现了：

https://github.com/ant-design/pro-components/blob/51a7f1082e64d29920e111b3fa44511c2e7e230f/packages/form/src/layouts/ModalForm/index.tsx#L216-L219

唯一的问题是上面的 `useEffect` 在 visible 从 `true` 到 `false` 时也会 `setIsDestroy`，因此我的 MR 里做一个判断，去除这一行为就行了。（单测和手动测试能过）

DrawerForm 我本来也是按这个思路改的，但 DrawerForm 的代码里没有用 `afterClose` 而是用了 `onClose`：

https://github.com/ant-design/pro-components/blob/51a7f1082e64d29920e111b3fa44511c2e7e230f/packages/form/src/layouts/DrawerForm/index.tsx#L220-L223

问题在于 `onClose` 只在主动点击关闭时调用，在修改 visible 时则不会触发，因此我改完之后单测过不了了。至于为什么说 drawer 的 afterClose 有问题、无法使用，这个我就不知道具体是什么原因了，也许可以请 commit 作者 @chenshuai2144 解释一下？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/pull/4597

重写了
