### ISSUE TITLE
🐛[BUG] ProTable 在ProColumns配置了 `ellipsis: true` 时会出现性能问题。

### ISSUE THREAD

**Issue by Itherma** [ant-design/pro-components#4407]
### 🐛 bug 描述
```ts
const columns: ProColumns<TableListItem>[] = [
    {
      title: '登录账号',
      hideInSearch: true,
      ellipsis: true,
      dataIndex: 'userName',
    },
    ....
]
```
### 📷 复现步骤
然后protable 这个页面就会变得很卡，原因是`pro-components/packages/utils/src/genCopyable/index.tsx ` 这个组件里面用到了<Typography>这个组件，<Typography>这个组件里面有获取行高的代码，会导致回流重绘，每一个单元格都有一个<Typography>会导致大量的回流重绘，导致页面卡顿。

### 🏞 期望结果

配置了 `ellipsis: true` 不会导致页面卡顿，只会超出省略号，而且有tool-tip提示
### © 版本信息

- ProComponents 版本: "1.28.4",
- 开发环境 : windows

### 🚑 其他信息

![图片](https://user-images.githubusercontent.com/24877853/148159944-5b4567e2-3f77-401f-ad33-55a57da29713.png)
``

**Comment by DerrickTel** [comment]
https://github.com/ant-design/ant-design/issues/33353
不知道是不是同一个问题

**Comment by yxxuweb** [comment]
我也遇到了这样的问题。如果有该配置，当数据量上白条时，速度严重变慢

**Comment by chenshuai2144** [comment]
那用css 搞吧，因为js搞得很费劲。自定义render 一下吧

**Comment by Itherma** [comment]
> [ant-design/ant-design#33353](https://github.com/ant-design/ant-design/issues/33353) 不知道是不是同一个问题

对的，是一个问题，<Typography.Text />这个组件内部实现会获取DOM的高度和宽度，导致回流重绘，少量的<Typography.Text />渲染没问题，超过一定数量页面就掉帧严重。

**Comment by Itherma** [comment]
> 我也遇到了这样的问题。如果有该配置，当数据量上百条数据时，速度严重变慢

是的，又不想每个都重写render。写个函数处理 columnOption遍历处理每一项的render，加上tooltip的效果，然后返回新的columnOption，或者把<protable /> 再自己封装一层吧。。。
