### ISSUE TITLE
🧐[问题]ProList，自定义卡片模式与最外边框对齐问题

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#4408]
![image](https://user-images.githubusercontent.com/12421552/148195759-3b6593a1-cbe5-405d-ba11-810b5f63f3c2.png)

如图，上部使用ProList，下面使用List，自定义的class只对卡片里的内容有影响，
使用ProList两边对不齐。

List版本："antd": "^4.17.4",
ProList："@ant-design/pro-list": "^1.21.12",
代码如下：

![image](https://user-images.githubusercontent.com/12421552/148196274-c6fb4852-37d6-49cd-8911-800df728fdfc.png)

![image](https://user-images.githubusercontent.com/12421552/148196288-c3400536-04c3-4406-b13f-0fc9b61c346b.png)

**Comment by DerrickTel** [comment]
样式覆盖一下吧

**Comment by chenshuai2144** [comment]
我们是通过给外面的容器-16px 的margin 实现的，你可以参考一下
