### ISSUE TITLE
🧐[问题]onvalueschange record recordlist如何表现保持一致

### ISSUE THREAD

**Issue by 0x457** [ant-design/pro-components#4414]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
金额 amount在数量onchange通过setfieldw修改后，界面是正确，回调onvalueschange也可以，但是在onvalueschange中三处得到amount不一样，所以我用了formRef.current?.setFieldsValue({ detail: recordList });里面recordlist不是最新的amount值

![image](https://user-images.githubusercontent.com/5813610/148323107-84f4cc1b-6c07-4cc1-9ca5-6ed7a9417be5.png)
![image](https://user-images.githubusercontent.com/5813610/148323151-bd746e4d-575c-4e72-84ca-ce9e4424c156.png)
 
![image](https://user-images.githubusercontent.com/5813610/148323423-42b82432-43f6-403d-9496-e661fb1a22a8.png)

**Comment by chenshuai2144** [comment]
set 不会触发 onValuesChange 的，你最好用form 重新取一下，才能保证数据是最新的。
