### ISSUE TITLE
👑 [需求]更新一下官网release的文档吧

### ISSUE THREAD

**Issue by Kun8018** [ant-design/pro-components#4417]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述

更新一下官网release的文档吧，有的文档里有的组件不知道是哪个release上的，不知道该升到哪个版本

### 🧐 解决方案

更新一下官网release的文档吧

**Comment by s464446877** [comment]
+1

**Comment by xlboy** [comment]
+2

**Comment by chenshuai2144** [comment]
脚本坏了，可以先看看 git logs，有空我修下脚本问题

**Comment by chenshuai2144** [comment]
已经恢复了
