### ISSUE TITLE
🐛[BUG] DragSortTable columns render 内 无法获取 dataResource

### ISSUE THREAD

**Issue by rzp1** [ant-design/pro-components#4420]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/43344910/148353055-d6ec9c6c-7997-4ddd-b77d-a1dabf5a5e9b.png)
此data 无效.
DragSortTable columns render 内 无法获取 dataResource

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by rzp1** [comment]
> 请附上复现代码：https://codesandbox.io

https://codesandbox.io/s/ke-bian-ji-biao-ge-forked-pew9k?file=/App.tsx

**Comment by rzp1** [comment]
> 请附上复现代码：https://codesandbox.io

https://codesandbox.io/s/ke-bian-ji-biao-ge-forked-pew9k?file=/App.tsx

这里无法获取最新的dataSource1.

**Comment by chenshuai2144** [comment]
学习一下 react hooks的实现原理。这是闭包的原因
