### ISSUE TITLE
👑 [需求]protable 没有ref 属性吗？通过什么方法能直接获取datasource？

### ISSUE THREAD

**Issue by algz** [ant-design/pro-components#4423]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述
希望提供一个直接获取datasource的方法，而不要自已在去定义一个状态来装载请求的数据datasource.
protable已经把数据源datasource存储了，为什么不能提供一个接口直接获取呢。
场景：protable嵌入到ModalForm中，需要在提交时，验证protable数据中是否有空，否则不允许提交。

### 🧐 解决方案
希望提供ref属性或者直接提供datasource获取方法。

**Comment by chenshuai2144** [comment]
| dataSource | Table 的数据，protable 推荐使用 request 来加载 | `T[]` | - |
| onDataSourceChange | Table 的数据发生改变时触发 | `(dataSource: T[]) => void` | - |

用 onDataSourceChange  来存储吧
