### ISSUE TITLE
Protable defaultSelectedRowKeys not work 🐛[BUG]

### ISSUE THREAD

**Issue by lyj505** [ant-design/pro-components#4424]
提问前先看看：

### 🐛 bug 描述 

在使用ProTable的时候 使用rowSelection的defaultSelectedRowKeys 想给table 默认值的时候,没有效果
但是让表格成为受控 添加selectedRowKeys 则可以

### 📷 复现步骤

1.打开
https://codesandbox.io/s/cha-xun-biao-ge-forked-xlb40?file=/App.tsx。

2. 查看代码里面设置了defaultSelectedRowKeys

3. `Object literal may only specify known properties, and 'defaultSelectedRowKeys' does not exist in type 'TableRowSelection<GithubIssueItem> & { alwaysShowAlert?: boolean; }
`
4. （在事例代码里面我同样列出了ant design 普通table是可以的）

### 🏞 期望结果

input : defaultSelectedRowKeys
output: 按照key正常选择行
![image](https://user-images.githubusercontent.com/17819611/148490154-66c573b7-1b8b-4bae-8369-8d80afcc3ccf.png)

### © 版本信息

- antd 版本: [e.g. 4.18.2]
- umi 版本
- 浏览器环境

**Comment by chenshuai2144** [comment]
protable的数据是异步加载的 ，defaultSelectedRowKeys  类型的api都不能用，如果想用，需要使用dataSource

**Comment by ftlynx** [comment]
有没其它办法先解决这个问题呢？

**Comment by lyj505** [comment]
@chenshuai2144 老哥我看你修复的代码在master了 有计划更新版本吗 我们可以直接使用defaultSelectedRowKeys了

**Comment by chenshuai2144** [comment]
等这周发版本
