### ISSUE TITLE
🐛[BUG] ProTable 搜索时renderFormItem的参数不能通过request的params参数传递

### ISSUE THREAD

**Issue by blueandhack** [ant-design/pro-components#443]
### 🐛 bug 描述

选择过滤的条件（使用renderFormItem的控件），点击查询按钮

### 📷 复现步骤

[![Edit vigilant-gauss-oj402](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigilant-gauss-oj402?fontsize=14&hidenavigation=1&theme=dark)
选择Date Rangae，然后查看console中的params，并没有相应参数的传递

### 🏞 期望结果

根据用户选择的筛选条件（使用renderFormItem的控件），显示相应的结果

### 💻 复现代码

[![Edit vigilant-gauss-oj402](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigilant-gauss-oj402?fontsize=14&hidenavigation=1&theme=dark)

### © 版本信息

- ProTable: 2.7.0 - 2.7.1

### 🚑 其他信息

Null

**Comment by itsuki0927** [comment]
这应该不是bug, onChange有三个参数`(params, sorter, filter) => {}`,我们一般只采用了第一个参数当作params, 然而如果有sort或者filter条件的话,需要同时采用后面两个参数当作params, 也就是说在request请求里面把这三个参数当作params就可以了.

大概是这样子,如果这样子不行的话,应该就是bug了.
```tsx
<ProTable requset={(params, sorter, filter) => fetchData({ ...params, filter, sorter }) }/>
```

**Comment by blueandhack** [comment]
> 这应该不是bug, onChange有三个参数`(params, sorter, filter) => {}`,我们一般只采用了第一个参数当作params, 然而如果有sort或者filter条件的话,需要同时采用后面两个参数当作params, 也就是说在request请求里面把这三个参数当作params就可以了.
> 
> 大概是这样子,如果这样子不行的话,应该就是bug了.
> 
> ```tsx
> <ProTable requset={(params, sorter, filter) => fetchData({ ...params, filter, sorter }) }/>
> ```

感谢解答，原来如此，经过详细测试，发现是我在项目中使用了非常多的renderFormItem，使用renderFormItem设置搜索的条件，并不能正确的传递到params中

**Comment by chenshuai2144** [comment]
```
  renderFormItem: (item, props) => {
      return (
        <DatePicker.RangePicker value={props.value} onChange={props.onChange} />
      );
    }
```

不要用传入 `value={props.value} onChange={props.onChange` 就可以，现在会自动帮你加了

**Comment by chenshuai2144** [comment]
文档已经修改

**Comment by TengChongChong** [comment]
如果我自己封装了一个组件，组件中包含了一个select，会导致查询的时候没办法把参数传给后端
![image](https://user-images.githubusercontent.com/11783658/95535407-f887aa00-0a1a-11eb-8b3a-c2fec33e2439.png)
![image](https://user-images.githubusercontent.com/11783658/95535422-00474e80-0a1b-11eb-87e1-2cf77c5ef2a2.png)
