### ISSUE TITLE
👑 [需求]ProFormText添加onClick事件

### ISSUE THREAD

**Issue by chenzw8** [ant-design/pro-components#4434]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述
存在需求，表单中点击输入框弹出选项弹窗，而ProFormText组件没有onClick事件，只能使用Input实现，再单独配CSS调节样式与其余表单项保持一致的显示效果，希望能补充ProFormText的onClick事件，使用会更便捷。

### 🧐 解决方案
补充ProFormText的onClick事件

**Comment by 1247748612** [comment]
ant-design就没提供onClick事件的支持

试试使用ref获取input实例然后监听onClick事件

**Comment by chenzw8** [comment]
ProFormText里好像没ref属性，倒是找到一个fieldProps，实现了点击事件。
fieldProps={{
   onClick: () => {
      console.log('click');
   },
}}
