### ISSUE TITLE
搜索表单怎么多个合并成一个，就是怎么设置每个搜索项col的span，而不是统一在search里面设置👑 [需求]

### ISSUE THREAD

**Issue by hong418884611** [ant-design/pro-components#4439]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述

搜索表单怎么多个合并成一个，就是怎么设置每个搜索项col的span，而不是统一在search里面设置

**Comment by chenshuai2144** [comment]
可以通过 colsize 来修改。

真实栅格 =  colsize * span
