### ISSUE TITLE
🧐[问题]layout 设置成mix 模式后怎么设置 top 是 light theme， side是dark theme

### ISSUE THREAD

**Issue by q389491729** [ant-design/pro-components#444]
### 🧐 问题描述

layout 设置成mix 模式后怎么设置 top 是 light theme， side是dark theme

**Comment by chenshuai2144** [comment]
还不支持的，现在只支持 navTheme，下个月会支持一下

**Comment by veici** [comment]
希望top 跟 side都支持配置 theme，看代码现在 top 是硬编码成 dark 的，感谢
