### ISSUE TITLE
🧐[问题] vite  build 的时候，发现样式引入了四次。basicLayout的样式

### ISSUE THREAD

**Issue by lovelyyl** [ant-design/pro-components#4445]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

很简单的引入，和使用。构建的时候，发现样式引入多次。

![image](https://user-images.githubusercontent.com/45654799/148896148-c3dad8c7-61b8-4f8c-b8a9-b36726f3a8c7.png)

### 💻 示例代码

![image](https://user-images.githubusercontent.com/45654799/148896205-746e96b2-ad1d-46d5-af0e-9ac292212952.png)

**Comment by chenshuai2144** [comment]
已经修复了，可以试试了

**Comment by lovelyyl** [comment]
已解决。
![image](https://user-images.githubusercontent.com/45654799/153802115-f77cf1b2-3d49-4fe6-a79d-11d66faee1ee.png)
