### ISSUE TITLE
🐛[BUG]使用<ProFormDependency> input隐藏显示，input变大，标签不隐藏

### ISSUE THREAD

**Issue by HalcyonDaysssss** [ant-design/pro-components#4449]
代码如下
![Xnip2022-01-11_22-09-58](https://user-images.githubusercontent.com/24239032/148958239-889558f9-1dd9-4e1b-883e-8f94fdfb37dd.jpg)

`<div
          style={{
            marginBottom: 10,
          }}
        >
          <ModalForm
            trigger={
              <Button type="primary">
                <PlusOutlined />
                新增
              </Button>
            }
            visible={visible}
            title={modalTitle}
            onVisibleChange={onVisibleChange}
            formRef={formRef}
            {...{
              labelCol: { span: 4 },
              wrapperCol: { span: 14 },
            }}
            layout="horizontal"
            onFinish={async (values: any) => {
              console.log(values);
            }}
            initialValues={{
              type: false,
            }}
          >
            <ProFormDependency name={['type']}>
              {({ type }) => {
                return (
                  <ProFormText
                    name="name"
                    label="菜单名称"
                    placeholder="请输入菜单名称"
                    fieldProps={{
                      style: {
                        display: type ? 'none' : 'block',
                      },
                    }}
                    rules={[{ required: true, message: '请输入菜单名称!' }]}
                  />
                );
              }}
            </ProFormDependency>
            <ProFormText
              name="path"
              label="菜单标识"
              placeholder="请输入菜单标识"
              rules={[{ required: true, message: '请输入菜单标识!' }]}
            />
            <ProFormText
              name="component"
              label="菜单文件路径"
              placeholder="请输入菜单文件路径"
              rules={[{ required: true, message: '请输入菜单文件路径!' }]}
            />
            <ProFormText
              name="permission"
              label="菜单权限"
              placeholder="请输入菜单权限"
              rules={[{ required: true, message: '请输入菜单权限!' }]}
            />
            <ProFormDigit name="sort" label="排序" min={1} />
            <ProFormRadio.Group
              name="type"
              label="类型"
              radioType="button"
              options={[
                {
                  label: '菜单',
                  value: false,
                },
                {
                  label: '权限',
                  value: true,
                },
              ]}
            />
          </ModalForm>
        </div>`
![image](https://user-images.githubusercontent.com/24239032/148957676-ed378474-e6fd-4df1-aa36-4ce84d6d6f8f.png)
input变大;
![image](https://user-images.githubusercontent.com/24239032/148957731-528cce0b-dae9-414f-afb1-c53527adc4d8.png)
标签不隐藏

**Comment by DerrickTel** [comment]
方不方便出一个  https://codesandbox.io/
