### ISSUE TITLE
🐛[BUG]文档描述demo地址错误

### ISSUE THREAD

**Issue by wuchaoya** [ant-design/pro-components#445]
### 📷 复现步骤

1.  打开https://procomponents.ant.design/docs/getting-started-layout
2. 布局介绍中的点击 `这里` 
3. 打开了https://procomponents.ant.design/_demos/base-2 这个应该是ProTable的demo吧
4. ProLayout 应该是https://procomponents.ant.design/_demos/base-3

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个 pr 吧？
