### ISSUE TITLE
🧐[问题]request请求返回空，表单值还保存上一次编辑的值

### ISSUE THREAD

**Issue by learning-go123** [ant-design/pro-components#4450]
### 🧐 问题描述

request请求返回空，表单值还保存上一次编辑的值

![动画1](https://user-images.githubusercontent.com/88469563/149069172-aa9b7910-abcd-417b-95e0-f16920d9c2d0.gif)

### 💻 示例代码

https://codesandbox.io/s/schema-biao-dan-forked-o5h9r?file=/App.tsx

**Comment by DerrickTel** [comment]
https://codesandbox.io/s/schema-biao-dan-forked-wdt4l?file=/App.tsx

`setCurrentRow({});`
清空应该是这个，而不是undefined

**Comment by learning-go123** [comment]
@DerrickTel setCurrentRow({}); 这个我也试了啊，也不行。

我是想做动态表单，不同的id就重新请求渲染表单. 如果没有id就是新增

https://codesandbox.io/s/schema-biao-dan-forked-5bcw5?file=/App.tsx

**Comment by DerrickTel** [comment]
![image](https://user-images.githubusercontent.com/24643779/149288661-0ff63da5-59ba-434f-9e39-02de8ae41c89.png)
改成`setCurrentRow({});`

**Comment by learning-go123** [comment]
你那个地址也不行啊
这个 https://codesandbox.io/s/schema-biao-dan-forked-wdt4l?file=/App.tsx

**Comment by DerrickTel** [comment]
https://user-images.githubusercontent.com/24643779/149288888-f85e0425-f45a-46e6-b1d4-9e96be7944f3.mp4

**Comment by Breezess** [comment]
@DerrickTel 你啥浏览器？我的不行
 Chrome 已是最新版本
版本 97.0.4692.71（正式版本） （64 位）

**Comment by DerrickTel** [comment]
> @DerrickTel 你啥浏览器？我的不行 Chrome 已是最新版本 版本 97.0.4692.71（正式版本） （64 位）

和浏览器应该没关系，他这个是在线的沙盒。你的是啥情况。。

**Comment by Breezess** [comment]
我看到你了 你点完新增再点编辑，编辑里就是空了

**Comment by learning-go123** [comment]
我看到了 你点完新增再点编辑，编辑里就是空了

**Comment by DerrickTel** [comment]
确实是这样的，我看一下

**Comment by DerrickTel** [comment]
`request` 是用来初始化用的，只有第一次return的内容才有效。当你这个表单生成完之后，request返回的内容就无效了。你应该通过form 这个props来控制表单内容的呈现。如果一定要用initvalue应该将表单销毁了，重塑，不过这样不太优雅

**Comment by learning-go123** [comment]
之前的这个写法可以触发params然后request会重新请求的覆盖initvalue
![image](https://user-images.githubusercontent.com/88469563/149298312-a5a1bb03-6f72-4539-bbe6-81940cf68609.png)

这个新增我后面字段可能有十几个，写起来就麻烦了

**Comment by DerrickTel** [comment]
> 之前的这个写法可以触发params然后request会重新请求的覆盖initvalue ![image](https://user-images.githubusercontent.com/88469563/149298312-a5a1bb03-6f72-4539-bbe6-81940cf68609.png)
> 
> 这个新增我后面字段可能有十几个，写起来就麻烦了

后端如果返回的结构体和前端定义的一样，应该就可以直接扔进去了。要是不一样，确实也要拆开写，或者弄一个转换函数

**Comment by learning-go123** [comment]
新增我不需要请求后端，只有在编辑的时候需要。

**Comment by learning-go123** [comment]
所以我为了置空要把所有的字段写一遍。。
