### ISSUE TITLE
🐛[BUG] JSON 表单应该要兼容 JSON

### ISSUE THREAD

**Issue by tonny008** [ant-design/pro-components#4451]
### 🐛 bug 描述

当前的 JSON 表单并不完全能用 JSON 表示， 都是以 js 对象作为输入的，和 JSON 表单这个名字不符合

### 📷 复现步骤

dependency 的示例中用到arrow function， columns 传 `JSON.parse(JSON.stringify(columns)` 得不到正确的结果。

### 🏞 期望结果

JSON 表单 columns 的定义应该是能序列化成 json 和 反序列化的

### 💻 复现代码

https://codesandbox.io/s/schema-biao-dan-forked-97qg6?file=/App.tsx

``` js
columns: ({ type }) => {
      if (type === "money") {
        return [
          {
            dataIndex: "money",
            title: "优惠金额",
            width: "m",
            valueType: "money"
          }
        ];
      }

      if (type === "discount") {
        return [
          {
            dataIndex: "discount",
            title: "折扣",
            valueType: "digit",
            width: "m",
            fieldProps: {
              precision: 2
            }
          }
        ];
      }

      return [];
    }

```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by tonny008** [comment]
另外是否有工具可以生成这个 json。类似 formjs 那种 https://demo.bpmn.io/form/new

**Comment by chenshuai2144** [comment]
json 的表达能力太弱了，现在只能先这样了。

使用人数很少，我们的维护压力也很大。不值得大规模投入。

**Comment by pengyongqi** [comment]
各位有没有什么办法将columns的值保存到数据库，方便前端回显，因为不是json，且里面有jsx语法，整个columns代码的对应字符串怎么才能在js中生效啊？
