### ISSUE TITLE
🧐[问题] antd版本等问题

### ISSUE THREAD

**Issue by killdada** [ant-design/pro-components#4452]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

背景

旧项目组件： 基于antd封装了一个formGroup组件

因为需要抽离项目组件做成公共组件，小伙伴又有QueryFilter 额外包裹了一层，做了一个新的组件

![image](https://user-images.githubusercontent.com/16487810/149075597-dfabe820-1165-4e44-9447-25dce53152d6.png)

![image](https://user-images.githubusercontent.com/16487810/149075636-95aff7bd-cb69-4663-8058-79a7d74f90c7.png)

组件demo使用方式

![image](https://user-images.githubusercontent.com/16487810/149075902-0c195fb2-b6e1-4d16-b257-a29d7b2e55c9.png)

demo使用的过程中搜索的 values值都是正常的。

场景

有一次更新了公共组件库的antd版本到了最新版本 4.18.2，项目的本身的antd还停留在 4.16.2，然后直接发布到生产环境上去了，
后面测试反馈，搜索没有传递查询参数，自行定位发现 此时公共组件
```js
 const values = await formRef.current.validateFields();
```
此时这个values始终是空对象

后面自己修复的时候尝试 更新主项目的antd的版本也到最新版本，然后values可以正常拿到值

这种公共组件的 antd升级，前端怎么可以提前发现这一类不容易察觉的问题？？？因为即使更新了antd版本，demo跑的时候也是正常，但是别人一更新公共组件库的版本，但是没有更新本身的antd版本带来了问题，，或者有什么好的方案可以提前发现，或者避免？

**Comment by DerrickTel** [comment]
锁版本吧，升级的时候让测试帮忙走一下回归

**Comment by chenshuai2144** [comment]
自动化回归是最简单的办法
