### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by scolleen** [ant-design/pro-components#4453]
### 🐛 bug 描述

antd 默认英文版，pro-table设置语言为英文后，table里面的分页组件部分是英文部分是中文

详情如下

![image](https://user-images.githubusercontent.com/28476268/149059619-f6875810-7bb7-47b8-9dd2-30b17534fbf5.png)

配置如下

![image](https://user-images.githubusercontent.com/28476268/149060434-32285abc-f3a7-4e2a-8cf9-f52dc9d9de7c.png)

![image](https://user-images.githubusercontent.com/28476268/149059918-d87b1af1-76a7-47fd-aa56-956146562b1e.png)

### 🏞 期望结果

设置语言为某一语言时，保证所有组件是同一种语言的 ；

### © 版本信息

- pro-table: [2.61.0]
- antd version: [4.17.3]
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
设置antd的语言到英文。
