### ISSUE TITLE
🧐[问题]proTable搜索是否支持下拉多选?

### ISSUE THREAD

**Issue by Ryang-H** [ant-design/pro-components#4456]
### 🧐 问题描述
    某列查询数据需支持选择多个数据，如antd的select，mode:'multiple'，请问proTable列查询是否支持，相关示例中并没有找到

**Comment by DerrickTel** [comment]
https://codesandbox.io/s/cha-xun-biao-ge-forked-6e0pg?file=/App.tsx
    fieldProps:{
      mode: 'multiple'
    }
