### ISSUE TITLE
嵌套表格 使用pro-table里的 rowExpandable控制'+'这个展开按钮的展示 不起作用  🐛[BUG]

### ISSUE THREAD

**Issue by superAo005** [ant-design/pro-components#4457]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
pro-table里使用 rowExpandable这个属性 控制'+'这个展开按钮的展示不起作用

### 🏞 期望结果
使用 rowExpandable 设置是否允许行展开 | (record) => boolean 

### 💻 复现代码
![image](https://user-images.githubusercontent.com/22334521/149270678-443783f4-5e2a-4081-ba0f-4ab626129e2a.png)

### © 版本信息
antd：4.14
pro-table：2.57.1

**Comment by 1247748612** [comment]
更到最新版本

**Comment by wangyun122** [comment]
antd: 4.19
pro-table: 2.71.7
使用rowExpandable无法控制'+'

**Comment by watsonhaw5566** [comment]
> antd: 4.19 pro-table: 2.71.7 使用rowExpandable无法控制'+'

 貌似 rowExpandable 是控制的  expandedRowRender 而不是 children 的内容
