### ISSUE TITLE
pro-table useEditableArray 对于树形table未处理的错误 🐛[BUG]

### ISSUE THREAD

**Issue by lyj505** [ant-design/pro-components#4459]
### 🐛 bug 描述

当前使用的的组件是
1. EditableProTable ,可编辑每一行。
2. dateSource是树形结构的数据。
3. 在props onValuesChange 的时候 获取第一个参数的时候出现问题。
4. 无法拿到完整的数据返回。

### 🐛 正常处理
1. 如果将dateSource改成list结构就没有问题了。

### 📷 复现步骤

1.这个可能由于代码和时间问题暂时无法提交。

### 🏞 期望结果
1. onValuesChange 正确返回参数。

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 3.5.0
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

1. 尝试阅读源码给予提示。
![image](https://user-images.githubusercontent.com/17819611/149298069-dc8e9480-e5f1-4e73-a28c-70f7a60a3677.png)
![image](https://user-images.githubusercontent.com/17819611/149298276-fdce9ac2-7b4d-4beb-a73d-7aafd93d985e.png)

2. 期待在初始化dataSourceKeyIndexMapRef的时候 考虑树形数据结构。
3. 在判断dataSourceKeyIndexMapRef的时候从缓存的datasource里面取到值然后spread一下object。

**Comment by 1247748612** [comment]
来个codesandbox复现吧

**Comment by lyj505** [comment]
我明后天看有空提一个
