### ISSUE TITLE
ProDescriptions高级定义列表能否包裹在Modal/Drawer中实现类似浮层表单的功能👑 [需求]

### ISSUE THREAD

**Issue by sunxia628** [ant-design/pro-components#4461]
### 🥰 需求描述
我想实现包裹在Modal/Drawer中的只读表单，使用disabled的效果样式很不友好；查看了ProDescriptions和浮层表单的文档之后，发现把浮层表单中的form替换为ProDescriptions就是我想要的效果。

### 🧐 解决方案
希望浮层表单可以增加一个接口，支持传入自定义渲染ReactNode，实现ModalDescriptions/DrawerDescriptions的功能；当然我的需求只是一个只读表单而已！

自己思考的方案是封装两个组件ModalDescriptions/DrawerDescriptions，但是发现这种逻辑和浮层表单高度重合，所以希望浮层表单可以暴露API或者封装新的组件ModalDescriptions/DrawerDescriptions，实现只读表单的效果，这种查看功能在后台管理页面是非常常用的！

### 🚑 其他信息

只读状态的高级定义列表：
![只读状态的ProDescriptions](https://user-images.githubusercontent.com/26341016/149489980-697d0ef2-064c-417f-ba70-cc0b39a9be94.png)
查看表单弹框：
![查看表单弹框](https://user-images.githubusercontent.com/26341016/149489849-e742d05b-4c4b-4ff6-881e-eb1458669f2b.png)

**Comment by chenshuai2144** [comment]
试试 readonly 呢？

**Comment by sunxia628** [comment]
disabled对于所有的表单元素都有效，包括select, radio, checkbox, button等；[Readonly](https://so.csdn.net/so/search?q=Readonly&spm=1001.2101.3001.7020)只针对input(text / password)和textarea有效。
disabled可以实现只读效果，但是样式不太友好也不能保留表单项的值，就使用样式控制；但是使用Pro之后发现[ProComponents]的样式类非常nice，如果能实现只读效果的ModalDescriptions/DrawerDescriptions就太好了！
