### ISSUE TITLE
🐛[BUG]ProFormTreeSelect使用treeData无效

### ISSUE THREAD

**Issue by HalcyonDaysssss** [ant-design/pro-components#4469]
const treeData = [
  {
    title: 'Node1',
    value: '0-0',
    children: [
      {
        title: 'Child Node1',
        value: '0-0-1',
      },
      {
        title: 'Child Node2',
        value: '0-0-2',
      },
    ],
  },
  {
    title: 'Node2',
    value: '0-1',
  },
];

<ProFormTreeSelect
              fieldProps={{
                treeData: treeData,
                fieldNames: {
                  label: 'title',
                },
              }}
            ></ProFormTreeSelect>

**Comment by 1247748612** [comment]
请使用options

**Comment by BresterWang** [comment]
文档写的不清不楚，蛋疼

**Comment by BresterWang** [comment]
用request={async () => {}}

**Comment by HalcyonDaysssss** [comment]
> 用request={async () => {}}

初始化查询的时候，已经有数据了，所以没必要在查询一次

**Comment by BresterWang** [comment]
![image](https://user-images.githubusercontent.com/39109415/149622606-3ee19f56-b14c-4a93-adc7-22679650809a.png)
不行 @1247748612

**Comment by BresterWang** [comment]
![image](https://user-images.githubusercontent.com/39109415/149622666-772a7a72-535f-4e48-b216-c22bf8cf8ed7.png)
ProFormSelect 就OK @1247748612

**Comment by HalcyonDaysssss** [comment]
不纠结了用了TreeSelect组件了

```
<ProForm.Item label="上级节点" name="parentId">
              <TreeSelect
                treeData={menusTreeSelectData}
                fieldNames={{ label: 'title', value: 'ID', children: 'routes' }}
                placeholder="请选择上级节点"
              />
            </ProForm.Item>
```
