### ISSUE TITLE
🐛[BUG]  form.setFields 更新的值在EditableProTable的Summary中有延迟

### ISSUE THREAD

**Issue by chanTanya** [ant-design/pro-components#4472]
### 🐛 bug 描述
数量变化， Summary总金额延迟。pro-table": "2.56.9"之前的版本是正常的

提供可复现的代码，仓库，或线上示例
https://codesandbox.io/s/ke-bian-ji-biao-ge-forked-sjbrx?file=/App.tsx

### © 版本信息

 "dependencies": {
    "@ant-design/pro-table": "2.56.9",
    "antd": "4.18.3",
    "react": "16.14.0",
    "react-dom": "16.14.0"
  },

**Comment by chenshuai2144** [comment]
看起来没什么问题。应该是修复了

**Comment by chenshuai2144** [comment]
https://codesandbox.io/s/ke-bian-ji-biao-ge-forked-l77fy?file=/package.json

**Comment by chanTanya** [comment]
![image](https://user-images.githubusercontent.com/45809356/153526023-069a9605-5c2b-42a4-9a62-7204e1d02a3a.png)

**Comment by chanTanya** [comment]
还是有问题的，将第一行的数量增加为2的时候，总金额应该是6

**Comment by chenshuai2144** [comment]
看看是不是你的算法问题，改金额是没问题的，机制是一样样的

**Comment by chanTanya** [comment]
没有使用复杂的算法，只是在数量onChange的时候通过form.setFields更新金额。同样的算法在 "@ant-design/pro-table": "2.56.8"的时候是正常的哦。

**Comment by chenshuai2144** [comment]
form.setFields 是不会触发onvalueschange得。你手动更新下dataSource吧

**Comment by chanTanya** [comment]
好滴，谢谢大佬解惑
