### ISSUE TITLE
🐛[BUG] ProFormList 中的 ProFormDatePicker.Year 获取到的时间没有格式化为年

### ISSUE THREAD

**Issue by canxiyuanzhe** [ant-design/pro-components#4480]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProFormList 中的使用 ProFormDatePicker.Year 获取到的时间格式为“YYYY-MM-DD”，没有格式化为“YYYY”。

### 📷 复现步骤
在 ProFormList 中的使用 ProFormDatePicker.Year

### 🏞 期望结果
期望直接得到年的数据，不需要在onFinish

### 💻 复现代码
https://codesandbox.io/s/proform-forked-kq9v4?file=/App.tsx

### 🚑 其他信息
![截屏2022-01-17 10 43 48](https://user-images.githubusercontent.com/82920343/149700414-779b23c5-7f28-4579-b5f5-dd81aaff4741.png)

**Comment by DerrickTel** [comment]
https://ant.design/components/form-cn/#components-form-demo-time-related-controls

我猜主要是为了适配更多的情况，而且，就算由Pro处理也是在antd内部的onFinish处理，官方的onFinish 无法知晓这个是Year 还是 Month。只能做统一的处理：
Moment.isMoment()
↓是
用dateFormat统一处理

**Comment by canxiyuanzhe** [comment]
> https://ant.design/components/form-cn/#components-form-demo-time-related-controls
> 
> 我主要是为了在内部处理更多的情况，而且，由 Pro 处理的 onFinish，官方的 onFinish 无法 处理 。是 用dateFormat统一处理

好的，感谢
