### ISSUE TITLE
🐛[BUG] ProFormDigit 没有 allowClear 属性，但是 TS 中定义了

### ISSUE THREAD

**Issue by bdoycn** [ant-design/pro-components#4482]
### 🐛 bug 描述

ProFormDigit 组件在 TS 中定义了 allowClear 属性
但是实际使用中 React 会报错 提示无法识别此属性 并且也没有清除的效果

proTable 搜索表单中的 digit 类型也有同样问题

### 🏞 期望结果

为 ProFormDigit 增加 allowClear 属性

### 💻 复现代码

<ProFormDigit name="no" label="编号" allowClear />

### © 版本信息

- ProComponents 版本: 
- - @ant-design/pro-form: 1.52.10
- - @ant-design/pro-table: 2.62.4
- umi 版本: 3.5.20
- 浏览器环境: chrome 99.0.4818.0（正式版本）dev (x86_64)
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/31044988/149728412-91d82188-8743-488f-a107-27e23404a054.png)
![image](https://user-images.githubusercontent.com/31044988/149728460-15995afa-ed26-4780-8af9-d6c758b3692b.png)

**Comment by 1247748612** [comment]
使用InputNumber实现的，本身就不支持allowClear，会把类型去掉
