### ISSUE TITLE
🐛[BUG] ProFormSelect 使用 request 结合 fieldNames 控制台爆红 Encountered two children with the same key, `null`

### ISSUE THREAD

**Issue by ikonan** [ant-design/pro-components#4483]
### 🐛 bug 描述

ProFormSelect 使用 request 结合 fieldNames 控制台提示多个 key 为null

使用代码:
 <ProFormSelect
        label="业务角色"
        name="roleIdList"
        params={{ orgRoleTypeEnum: currentUser.classifiedOrgTypeEnum.name }}
        request={(params) => API.getUserRole({ ...params })}
        fieldProps={{
          mode: 'multiple',
          fieldNames: { label: 'name', value: 'id' },
          optionLabelProp: 'name',
        }}
      />

### © 版本信息

- "@ant-design/pro-form": "^1.52.10",
- umi:^3.5.20
- 浏览器环境
- 开发环境 [e.g. windows]

### 🚑 其他信息
浏览器控制台输入：
![image](https://user-images.githubusercontent.com/20334137/149733624-ec8e0983-8f34-4e46-9caf-92f59138cd5a.png)

**Comment by 1247748612** [comment]
不是ProFormSelect的bug，你的数据有相同的key，自己排查下bug

**Comment by 1247748612** [comment]
点击一个选项后复现
