### ISSUE TITLE
EditableProTable columns 设置readonly 与 直接给ProFormText设置readonly 表现不一致 🧐[问题]

### ISSUE THREAD

**Issue by penglittlebai** [ant-design/pro-components#4487]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

原issues地址： https://github.com/ant-design/pro-components/issues/4458
最新版本EditableProTable columns 实现直接设置readonly， 但是与 直接给ProFormText设置readonly 表现不一致；

### 💻 示例代码
代码演示地址： https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-jk353?file=/App.tsx
![image](https://user-images.githubusercontent.com/87426994/149864640-b506a0c2-bc6b-4040-8ed4-0b93ffc31e5c.png)

**Comment by 1247748612** [comment]
表现其实是一样的，只是你的renderFormItem会在数据更新时重新渲染

这其实应该算是一个bug，虽然是readonly模式，但取得仍然是传进去的值而不是form的最新值，导致一直展示的还是旧的值，其实已经更新上去了。

展示的是 text ?? fieldProps?.value ?? '',

https://github.com/ant-design/pro-components/blob/dda609f028d843c92ed90e2cb185966efaf42007/packages/field/src/index.tsx#L389-L418

**Comment by penglittlebai** [comment]
> 

这个能改吗，form值变化，展示值跟着变合理一点吧（并且这种场景挺需要的）
