### ISSUE TITLE
🧐[问题]在SchemaForm中当数据类型为dependency时，依赖项变化时配置不同的fieldProps

### ISSUE THREAD

**Issue by momo-mao** [ant-design/pro-components#4488]
### 🧐 问题描述

在现在的业务中，我们利用SchemaForm通过接口返回的数据来渲染表单，大部分情况，都是没有问题的，但是在通过dependency类型来渲染带有依赖关系的表单项时，如果只是控制表单项的显示和隐藏是没有问题的，但是，想要通过依赖项发生变化时去重设对应的输入项的配置就不行了，如果是formItemProps配置的变动可以看触发到formItem的更新，如果是fieldProps配置的变动则无法触发formItem中包裹的输入项的更新，如果隐藏一下再显示可以的，但是如果输入项一直在的时候就不行了，不知道有什么方法可以让我手动去更新一下输入项吗？

**Comment by 1247748612** [comment]
联动的 ProFormSelect

````ts
  <ProFormText name="name" label="姓名" />
  <ProFormSelect
    name="addr"
    width="md"
    label="与 name 联动的选择器"
    // dependencies 的内容会注入 request 中
    dependencies={['name']}
    request={async (params) => [
      { label: params.name, value: 'all' },
      { label: 'Unresolved', value: 'open' },
      { label: 'Resolved', value: 'closed' },
      { label: 'Resolving', value: 'processing' },
    ]}
  />
```

应该符合你的需求吧

**Comment by momo-mao** [comment]
> 联动的 ProFormSelect
> 
> ```ts
>   <ProFormText name="name" label="姓名" />
>   <ProFormSelect
>     name="addr"
>     width="md"
>     label="与 name 联动的选择器"
>     // dependencies 的内容会注入 request 中
>     dependencies={['name']}
>     request={async (params) => [
>       { label: params.name, value: 'all' },
>       { label: 'Unresolved', value: 'open' },
>       { label: 'Resolved', value: 'closed' },
>       { label: 'Resolving', value: 'processing' },
>     ]}
>   />
> ```
> 
> 应该符合你的需求吧
> ```

感觉不太一样，表层我并没有使用ProFormItem来处理，我直接使用的是Schema Form这个组件，我只是创建了一个json来渲染表单，整个渲染是在这个组件内部完成，他内部通过ProFormDependency实现了表单项依赖的变化，就像你提供的示例这样的功能是可以实现的，但是如果我希望通过dependencies 注入的值来更新一下输入项本身的属性就没有办法触发更新，比如，我想通过dependencies 注入的值来改变数字输入框的min或者max之类的属性，就没有办法成功

**Comment by 1247748612** [comment]
能否提供一个例子，codesandbox？

**Comment by momo-mao** [comment]
> 能否提供一个例子，codesandbox？
我用官方例子写了一个demo，发现是可以变动的，我自己再研究一下，打扰了

**Comment by momo-mao** [comment]
> 能否提供一个例子，codesandbox？
自己研究了好久，还是不行，只要不是直接传columns数据进去，果然还是没有办法更新组件
这是我用官方demo改写的 https://codesandbox.io/s/schema-biao-dan-forked-6vy0h?file=/SchemaForm.tsx
大体思路就是需要先将接口返回的数据处理成符合 SchemaForm 规则的数据，里面的生成依赖关系这一块代码比较复杂，需要进行后种状态判断，然后就是返回处理好后的 columns 数据，我这边打印出来的数据是符合我的预期的，但是交互的时候，效果达不到，期望通过切换优惠方式，来控制优惠金额的最大值限制，配置的extra能正确更新，但是max就不行了，麻烦帮我看一下，是不是我的书写逻辑的问题。
