### ISSUE TITLE
🐛[BUG] ProTable无法手动设置当前页码

### ISSUE THREAD

**Issue by owendswang** [ant-design/pro-components#4490]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

通过pagination控制页码，不生效，传不到request的params里，表格下面的页码数还是1。

### 📷 复现步骤

```
<ProTable
  pagination={{
    defaultCurrent: 1,
    defaultPageSize: 1,
    current: 2,
    pageSize: 2,
  }}
>
```

### 🏞 期望结果

当我设置多少页码的时候，他应该显示该页码的数据，能够传给request，也能让页面下面的分页显示当前为第2页。

### 💻 复现代码

```
<ProTable
  pagination={{
    defaultCurrent: 1,
    defaultPageSize: 1,
    current: 2,
    pageSize: 2,
  }}
>
```

### © 版本信息

- ProTable 版本: 2.62.1
- umi 版本: ice.js 2.4.3
- 浏览器环境 Firefox
- 开发环境 Windows

### 🚑 其他信息

无

**Comment by kiner-tang** [comment]
请提供具体的可执行代码，这边在官方示例中测试是没问题的
![image](https://user-images.githubusercontent.com/10286961/150048900-afe6799a-d7a9-4ba5-b500-41c928f9a16e.png)
![image](https://user-images.githubusercontent.com/10286961/150048929-4eecc6ef-fc57-4944-9f82-76656e8d84f3.png)

**Comment by owendswang** [comment]
> 请提供具体的可执行代码，这边在官方示例中测试是没问题的 ![image](https://user-images.githubusercontent.com/10286961/150048900-afe6799a-d7a9-4ba5-b500-41c928f9a16e.png) ![image](https://user-images.githubusercontent.com/10286961/150048929-4eecc6ef-fc57-4944-9f82-76656e8d84f3.png)

`import { PageContainer } from '@ant-design/pro-layout';
import { message, Tag } from 'antd';
import { Link, useRequest } from 'ice';
import tableService from '@/services/table';
import type { ProColumns } from '@ant-design/pro-table';
import ProTable from '@ant-design/pro-table';
import { useRef, useEffect } from 'react';

export default function Table(props) {

  const { history, location, searchParams } = props;
  let { current, pageSize, ...restParams } = searchParams;
  const ref = useRef<ProFormInstance>();

  function itemRender(route, params, routes, paths) {
    const last = routes.indexOf(route) === routes.length - 1;
    return last ? (
      <span>{route.breadcrumbName}</span>
    ) : (
      <Link to={['', ...paths].join('/')}>{route.breadcrumbName}</Link>
    );
  }

  const { request } = useRequest(tableService.getTableList);

  type TableListItem = {
    key: number;
    TABLE_NAME: string;
  };

  const tableListDataSource: TableListItem[] = [];

  const columns: ProColumns<TableListItem>[] = [
    {
      title: '排序',
      dataIndex: 'key',
      valueType: 'number',
      hideInSearch: true,
      width: 60,
      align: 'center',
      render: (text, record, index, action) => [
        <Tag key='index'>{record.key}</Tag>
      ],
    },
    {
      title: '表名',
      dataIndex: 'TABLE_NAME',
      valueType: 'string',
      sorter: (a, b) => a.containers - b.containers,
      renderFormItem: (item,{ type, defaultRender, formItemProps, fieldProps, ...rest },form) => {
        item.set
        return defaultRender(item);
      }
    },
    {
      title: '操作',
      key: 'option',
      valueType: 'option',
      align: 'center',
      render: (text, record, index, action) => [
        <Link key='detail' to={'/table/' + record.TABLE_NAME}>查看</Link>,
      ],
    },
  ];

  let initParams = true;
  const fetchData = async (params, sorter) => {
    // console.log(params, sorter);
    history.replace({
      search: '?' + Object.keys(params).map((key, index) => {
        // console.log(typeof(params[key]));
        if(typeof(params[key]) === 'object') {
          // console.log(params[key]);
          let param = [];
          params[key].forEach((ele) => {
            param.push(key + '[]=' + ele);
          });
          // console.log(param);
          return param.join('&');
        } else {
          return key + '=' + params[key];
        }
      }).join('&'),
    });
    try {
      let res = await request({ params, sorter });
      let data = [];
      for (let i = 0; i < res['dataSource'].length; i += 1) {
        data.push({
          key: i + res['pageSize'] * ( res['current'] - 1 ),
          ...res['dataSource'][i],
        });
      }
      // console.log(data);
      return ({
        data,
        total: res['total'],
        success: true,
      });
    } catch(e) {
      console.log(e);
      message.error('Failed to fetch data!');
      return ({
        success: false,
      });
    }
  }

  useEffect(() => {
    if(restParams) {
      if(ref.current) {
        // console.log(ref);
        ref.current.setFieldsValue(restParams);
      }
      ref.current.submit();
    }
  }, []);
  
  return (
    <PageContainer
      header={{
        title: 'Table',
        ghost: true,
        breadcrumb: {
          itemRender,
          routes: [
            {
              path: '/',
              breadcrumbName: 'Home',
            },
            {
              path: '/table',
              breadcrumbName: 'Table',
            },
          ],
        },
      }}
    >
      <ProTable<TableListItem>
        columns={columns}
        request={fetchData}
        rowKey='key'
        search={{
          defaultCollapsed: false,
        }}
        dateFormatter='string'
        pagination={{
          showQuickJumper: true,
          showSizeChanger: true,
          defaultCurrent: parseInt(current) || 1,
          defaultPageSize: parseInt(pageSize) || 10,
          // current: parseInt(current) || 1,
          // pageSize: parseInt(pageSize) || 10,
        }}
        onChange={(pagination, filters, sorter, extra) => {
          if(extra.action === 'sort') {
            let params = { ...searchParams, current: 1 };
            history.replace({
              search: '?' + Object.keys(params).map((key, index) => {
                return key + '=' + params[key];
              }).join('&'),
            });
          }
        }}
        formRef={ref}
        manualRequest={true}
      />
    </PageContainer>
  );
}
`

**Comment by owendswang** [comment]
好像是我的onchange打断了，没事了，谢谢

**Comment by chenyu1990** [comment]
我也有这个问题，可能是我useState太多了。有20个。defaultCurrent,defaultPageSize 我设置了完全没用，还是跳第一页
