### ISSUE TITLE
ProTable 中 在定义 某个column的 filedProps 字段时，参数 form 会由 formInstance 变为 null

### ISSUE THREAD

**Issue by JoMartinezZhu** [ant-design/pro-components#4497]
### 🐛 bug 描述

ProTable 中 在定义 某个column的 filedProps 字段时，参数 form 会由 formInstance 变为 null

![image](https://user-images.githubusercontent.com/43346131/150090847-47e144f3-c3e1-40a0-8180-7fe492e11dd7.png)

### 📷 复现步骤

https://codesandbox.io/s/cha-xun-wu-an-niu-biao-ge-forked-vtioo?file=/App.tsx

### 🏞 期望结果

希望在可以得到 formInstance ，并可以实现 
fieldProps.onChange:form.submit

field change 后自动 submit ,send request

### 💻 复现代码

https://codesandbox.io/s/cha-xun-wu-an-niu-biao-ge-forked-vtioo?file=/App.tsx

### © 版本信息

![image](https://user-images.githubusercontent.com/43346131/150090942-96cd518a-dabb-4beb-98fc-1bc08e53e883.png)

**Comment by 1247748612** [comment]
这是一个有趣的问题🤣

### 结论

这是正常现象，放心使用formInstance他一定存在

--- 
### 为什么会存在这种现象？

在ProTable中当你未把该column.hideInSearch设置为true时
会在搜索表单渲染一个form控件
会在table中也渲染这个form控件但mode为read模式
这都会导致fieldProps被执行，所以你看到了formInstance为null，因为在table渲染时form就是不存在的

**Comment by kiner-tang** [comment]
楼上正解，使用时可以判断form存在时再调用查询表单的方法
