### ISSUE TITLE
🐛[BUG] 网站上的 CodeSandbox 跳转，都跑不起来

### ISSUE THREAD

**Issue by WynterDing** [ant-design/pro-components#45]
### 🐛 bug 描述

如题，使用体感很差，得修复一下

**Comment by shaohuatsou** [comment]
有VPN的话会好很多

**Comment by WynterDing** [comment]
> 有VPN的话会好很多

和 VPN 无关，就是错的

https://codesandbox.io/s/fiksw?module=/demo.tsx

![image](https://user-images.githubusercontent.com/11213298/88684200-2bfaae00-d127-11ea-8288-ab617c22102e.png)

**Comment by shaohuatsou** [comment]
> > 有VPN的话会好很多
> 
> 和 VPN 无关，就是错的
> 
> https://codesandbox.io/s/fiksw?module=/demo.tsx
> 
> ![image](https://user-images.githubusercontent.com/11213298/88684200-2bfaae00-d127-11ea-8288-ab617c22102e.png)

我看不到你的图，应该是缺少依赖，点左侧栏增加依赖 '@ant-design/pro-table'

![image](https://user-images.githubusercontent.com/50793943/88756706-e5449c80-d196-11ea-88c4-95c996cf1e58.png)

**Comment by WynterDing** [comment]
这也是要解决的问题，正在找 dumi 那边帮看怎么解决

**Comment by xiangxiong** [comment]
卧槽，这项目组件一堆bug,能不能修好在放出来。。。。

**Comment by rdmclin2** [comment]
近期修复，已找 dumi 的同学查看问题。

**Comment by KIngCrzy** [comment]
请问依赖装不上是什么原因呢？
These dependencies were not found:

* antd/es/space in ./node_modules/@ant-design/pro-field/es/components/Checkbox/index.js, ./node_modules/@ant-design/pro-field/es/components/Options/index.js and 11 others
* antd/es/space/style in ./node_modules/@ant-design/pro-field/es/components/Checkbox/index.js, ./node_modules/@ant-design/pro-field/es/components/Options/index.js and 11 others
* antd/lib/config-provider/SizeContext in ./node_modules/@ant-design/pro-field/es/components/DatePicker/index.js, ./node_modules/@ant-design/pro-field/es/components/RangePicker/index.js and 3 others

To install them, you can run: npm install --save antd/es/space antd/es/space/style antd/lib/config-provider/SizeContext

**Comment by chenshuai2144** [comment]
这个是antd的版本问题

**Comment by promotion-xu** [comment]
@chenshuai2144  我也遇到了这个问题， 版本："antd": "^3.11.6",
请问要升级antd到哪个版本呢

**Comment by chenshuai2144** [comment]
4.9以上

**Comment by mwb-27** [comment]
@chenshuai2144 我这antd版本最新的4.10.0  也是报
These dependencies were not found:
* antd/es/space in ./node_modules/@ant-design/pro-utils/es/components/LabelIconTip/index.js
* antd/es/space/style in ./node_modules/@ant-design/pro-utils/es/components/LabelIconTip/index.js
* antd/lib/table/hooks/useLazyKVMap in ./node_modules/@ant-design/pro-utils/es/useEditableArray/index.js

To install them, you can run: npm install --save antd/es/space antd/es/space/style antd/lib/table/hooks/useLazyKVMap
