### ISSUE TITLE
🐛[BUG] BetaSchemaForm setFieldsValue 失效

### ISSUE THREAD

**Issue by wangxin305** [ant-design/pro-components#4501]
### 🐛 bug 描述

ant-design/pro-form 1.52.9还是可以的，之后的版本就不能用了

### 💻 复现代码

https://umg4y.csb.app/

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by 1247748612** [comment]
这两个commit 36902434300a65f1cf707e953b9c528ebf8ae295 db98d79f876b8a4dd56b6fe040c0537fff1b6c0c 影响到了formRef获取实例
cc @chenshuai2144

**Comment by 1247748612** [comment]
### workaround

使用useForm代替
![image](https://user-images.githubusercontent.com/29533304/150313901-8be15e57-a579-49ba-8b3c-c3af621359a4.png)

**Comment by zjjjjjjjjjjd** [comment]
> ### workaround
> 使用useForm代替 ![image](https://user-images.githubusercontent.com/29533304/150313901-8be15e57-a579-49ba-8b3c-c3af621359a4.png)

大佬问一哈，这个属于是bug还是以后的新用法？如果是新用法那么我需要改写代码，如果是bug我们就暂时退一下版本，等修复了再升级

**Comment by 1247748612** [comment]
> 大佬问一哈，这个属于是bug还是以后的新用法？如果是新用法那么我需要改写代码，如果是bug我们就暂时退一下版本，等修复了再升级

这是bug

form的写法本身就有，改动太多的话就回退版本，等待修复后再更新上来
