### ISSUE TITLE
🧐[问题]使用了Pro的Query控件，请问如何修改【收起/展开】按钮的文字，在文档中未找到相关的解释，请大牛指点

### ISSUE THREAD

**Issue by super-chen** [ant-design/pro-components#4503]
### 🧐 问题描述

使用了Pro的Query控件，请问如何修改【收起/展开】按钮的文字，在文档中未找到相关的解释，请大牛指点

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/1482026/150292476-763cc75e-924d-42df-9ba9-3b80e2b1aedb.png)

**Comment by 1247748612** [comment]
看了下源码本地化是支持，不支持动态传递参数去修改，但提供了这个collapseRender自行渲染收起和折叠的按钮

**Comment by super-chen** [comment]
@1247748612 谢谢你。通过语言本地化解决的
