### ISSUE TITLE
🐛[BUG]BetaSchemaForm 的ModalForm 模式下  无法使用method赋值

### ISSUE THREAD

**Issue by zjjjjjjjjjjd** [ant-design/pro-components#4505]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ModalForm 模式下打印 formRef 只暴露这几个method并且调用完啥都没发生

![image](https://user-images.githubusercontent.com/32830366/150305992-0eef386a-d099-4096-999e-10ef284a6e8f.png)

### 📷 复现步骤

如上

### 🏞 期望结果

正常

### 💻 复现代码

无

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] "@ant-design/pro-form": "1.52.12",
- umi 版本 3.5.0
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS] win10

**Comment by zjjjjjjjjjjd** [comment]
而且官网好久没更新了额，官网的版本貌似还是去年10月份的

**Comment by 1247748612** [comment]
same issue #4501

**Comment by 1247748612** [comment]
先降低版本到1.52.9

**Comment by zjjjjjjjjjjd** [comment]
了改
