### ISSUE TITLE
🐛[BUG] ProDescriptions  数据项为空值时，自定义valueType不生效

### ISSUE THREAD

**Issue by xiaomansjw** [ant-design/pro-components#4506]
version: v1.10.5

### 🐛 bug 描述
 当数据项值不为空时，自定义valueType正常显示， 数据项为空值时，自定义valueType不执行，直接显示“-”

**Comment by kiner-tang** [comment]
请提供具体可执行的示例：https://codesandbox.io

**Comment by hanwenbo** [comment]
> 
大佬  这不用提供的  直接测一下就知道了 而且Object 不是组件也不行  看源码就能看出来
