### ISSUE TITLE
🧐[问题]ProFormDateTimePicker 的format格式

### ISSUE THREAD

**Issue by lyon913** [ant-design/pro-components#4508]
### 🧐 问题描述

请问下是否可以实现时间展示格式为YYYY-MM-DD HH:mm:ss ，表单送到后台的格式为UTC？
目前设置了format后展示格式和送到后台的格式都是UTC格式

### 💻 示例代码
const isoFormat = (value: Moment) => value.toISOString()
<ProFormDateTimePicker name="time" label="Time"  fieldProps={{format: isoFormat}}  />

**Comment by 1247748612** [comment]
有个transform属性是提交时转换结果的，你可以试试

**Comment by lyon913** [comment]
@1247748612 有效！感谢
