### ISSUE TITLE
🐛[BUG] ProTable 获取不到 Table 的 ref，antd 的 Table 是有 ref 的

### ISSUE THREAD

**Issue by linxianxi** [ant-design/pro-components#4509]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
Table ref
![image](https://user-images.githubusercontent.com/47104575/150475728-073a5d99-e474-449b-a1c4-8a3f476b7508.png)

**Comment by chenshuai2144** [comment]
你需要这个做什么？
我们没有暴露这个api

**Comment by lx815** [comment]
> 你需要这个做什么？ 我们没有暴露这个api

我们最近项目有一个需求，需要打印页面上表格的内容。这个时候我就需要拿到table的ref，才能只打印表格。还是希望官方能把这个api抛出来

**Comment by chenshuai2144** [comment]
用 id 吧 嵌套太多了🥹

**Comment by jasonz1987** [comment]
> 用 id 吧 嵌套太多了🥹

怎么用id，我的场景是 使用 `ReactHTMLTableToExcel` 需要用到table的id

**Comment by larrygogo** [comment]
antd table 在处理自适应高度的时候需要获取 tableRef
[[](url)](https://github.com/ant-design/ant-design/issues/23974#issuecomment-2365035091)
