### ISSUE TITLE
🐛[BUG]pro-table分页设置topLeft,topRight均不生效(元素存在但是页面上看不到)

### ISSUE THREAD

**Issue by iamgian-coder** [ant-design/pro-components#451]
### 🐛 bug 描述

pro-table分页设置topLeft,topRight均不生效(元素存在但是页面上看不到)，不论是单独使用还是和其他位置一起使用，均在页面上无法看到

### 📷 复现步骤

bug复现repo:https://github.com/iamgian-coder/reproducebug.git
### 🏞 期望结果

分页设置 topLeft topRight生效

### 💻 复现代码
bug复现repo:https://github.com/iamgian-coder/reproducebug.git

### © 版本信息

- ProComponents 版本: [e.g. 2.7.1]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26590255/92693652-7901af00-f378-11ea-9043-3cf5fccf9ab8.png)

**Comment by hengkx** [comment]
https://github.com/ant-design/ant-design/issues/26617

**Comment by iamgian-coder** [comment]
> [ant-design/ant-design#26617](https://github.com/ant-design/ant-design/issues/26617)

ok
