### ISSUE TITLE
👑 [需求] EditableProTable行编辑实时判断修改

### ISSUE THREAD

**Issue by HalcyonDaysssss** [ant-design/pro-components#4512]
EditableProTable行编辑实时判断修改；
需求如下：
当某行在编辑的时候，我需要进行首字母大小写判断，并实时写入，这个要怎么处理？

**Comment by 1247748612** [comment]
判断可以用rules校验结果，实时写入没明白

**Comment by chenshuai2144** [comment]
这个听起来应该自定义组件，而不是同过 onValuesChange
