### ISSUE TITLE
👑 [需求]ProFormList中删除和复制是否可以增加代理事件或可以自定义每条数据的操作按钮

### ISSUE THREAD

**Issue by didashine** [ant-design/pro-components#4514]
### 🥰 需求描述
遇到一个在表单编辑回显的应用场景，删除某一条数据前需要做一个相应的是否可以执行删除操作的判断；

### 🧐 解决方案
想到的方法是希望在点击删除按钮时候能抛出一个接收promise结果的回调函数，对这个操作进行拦截；不知道还有没有什么其他方案可以实现，望解答。

**Comment by chenshuai2144** [comment]
ref https://github.com/kiner-tang/pro-components/commit/9285bcf734dea2ba2fe531938eb71f0a4667348d

这里正在讨论
