### ISSUE TITLE
搜索的search表单 枚举内容串台，可能是因为字段一样🐛[BUG]

### ISSUE THREAD

**Issue by hanwenbo** [ant-design/pro-components#4521]
### 💻 复现代码
在2个不同的路由页面pages/a1  pages/a2，都存在status字段，100%的概率会导致search上的status枚举串台，先进入哪个界面search表单里的status就是哪个页面的status
```
订单的枚举
export const statusEnum = [
  {label: `全部`, value: `all`},
  {label: `订单关闭`, value: `-1`},
  {label: `未支付`, value: `0`},
  {label: `待支付`, value: `1`},
  {label: `已支付`, value: `2`},
  {label: `准备中`, value: `3`},
  {label: `已完成`, value: `4`},
  {label: `申诉中`, value: `5`},
  {label: `申请退款中`, value: `6`},
  {label: `退款中`, value: `7`},
  {label: `退款完成`, value: `8`},
]

餐厅的枚举
title: '营业状态',
    dataIndex: 'status',
    valueEnum: {
      1: {text: '经营中', status: 'Success', value: 1},
      0: {text: '已关闭', status: 'Error', value: 0},
    },
    request: () => [
      {label: "经营中", value: 1},
      {label: "已关闭", value: 0},
    ],
```

### © 版本信息

 "@ant-design/plots": "1.0.7",
    "@ant-design/pro-card": "1.18.25",
    "@ant-design/pro-descriptions": "1.10.35",
    "@ant-design/pro-form": "1.46.0",
    "@ant-design/pro-layout": "6.32.6",
    "@ant-design/pro-list": "^1.21.20",
    "@ant-design/pro-skeleton": "1.0.4",
    "@ant-design/pro-table": "2.62.7",
    "@ant-design/pro-utils": "1.32.7",

umi  3.5.20
antd 4.18.4
- 开发环境 [e.g. mac OS]

![image](https://user-images.githubusercontent.com/5869741/150669673-e57894a2-2e24-4f3d-bccf-4ca4152c12c3.png)

先进入哪个页面就显示哪个页面的status了 

![image](https://user-images.githubusercontent.com/5869741/150669757-d81bea7a-55c4-4dd5-9496-f9dc7e2b3777.png)
![image](https://user-images.githubusercontent.com/5869741/150669764-d74e3e8c-3495-4cf2-af8b-0442f2b9cfb3.png)
![image](https://user-images.githubusercontent.com/5869741/150669777-bb4584c0-dcee-4ac8-866e-0db340149e26.png)

**Comment by hanwenbo** [comment]
好在，目前项目的组件上封装了一层为了统一管理，现在通过 CustomerProTable的 自定义的 getTableListColumns = ({columns, module})  循环给每个字段加key = module + dataIndex

**Comment by hanwenbo** [comment]
目前观察是当pro-components 页面渲染后一个字段对应一个静态地址似得，再也不会触发 一样字段的column的request

**Comment by 1247748612** [comment]
参考: https://github.com/ant-design/pro-components/issues/4393#issue-1091498238

**Comment by hanwenbo** [comment]
@1247748612 谢谢了，加  ``` 
      params: { timestamp: Math.random() },

```
确实好使，通过这几个小时的倒腾我也发现我用法有问题，我用这个request其实是想解决valueEnum排序的问题，后来搜索帖子，发现可以用Map排序
```
 valueEnum: new Map([
        ['all', {text: '全部', status: 'Default'}],
        ['1', {text: '已上线', status: 'Success'}],
        ['0', {text: '已关闭', status: 'Default'}],
      ]),
```
