### ISSUE TITLE
BetaSchemaForm自定义组件过多会导致其他输入框输入非常卡顿

### ISSUE THREAD

**Issue by ldwonday** [ant-design/pro-components#4525]
如题，BetaSchemaForm上用renderFormItem定义了很多自定义组件，结果发现输入框非常输入起来卡顿，请问有什么好的办法吗？已经尝试过shouldUpdate和React.memo，还是卡顿。求助！
以下是自定义组件的一部分
![image](https://user-images.githubusercontent.com/4630157/150725859-5f994d7b-e20a-450a-8726-0bf40e1720af.png)

**Comment by rojer95** [comment]
自定义组件尝试过用valueType吗？https://procomponents.ant.design/components/schema#%E8%87%AA%E5%AE%9A%E4%B9%89-valuetype

**Comment by ldwonday** [comment]
自定义valueType也试过了，一样的卡顿，目前写了一个对betaSchema的columns的转换器，转成antd的FormItem，运行正常，输入不卡顿，经过调试发现，renderFormItem传给组件的onchange每次都发生变化，导致组件各种优化都失效，麻烦检查下代码，具体应该是你们代码useChange的某个依赖每次发生变化，导致的onChange每次变化

**Comment by ldwonday** [comment]
@rojer95

**Comment by ldwonday** [comment]
@chenshuai2144

**Comment by 1247748612** [comment]
提供个复现

**Comment by ldwonday** [comment]
https://codesandbox.io/s/schema-biao-dan-forked-h99iz?file=/App.tsx

自定义组件是一个渲染比较耗时的组件，大量的自定义组件会直接导致输入框卡死。

**Comment by ldwonday** [comment]
@1247748612

**Comment by 1247748612** [comment]
### 卡顿确实离谱

虽然这种情况是很不常见的，但目前来看renderXXXX被其他字段的变动后导致重新执行确实大幅影响性能，这个优化肯定需要提上日程了

### workaround

在此案例上你所能做的就是抽出逻辑同步任务改成异步任务，可以用上webworker把需要计算花时间的逻辑抽离，能暂时优化下这个问题

**Comment by rojer95** [comment]
@ldwonday  

自定义valueType情况下，目前能跑

https://codesandbox.io/s/schema-biao-dan-forked-plcfp?file=/App.tsx

不要在`columns`中使用
- renderFormItem
- fieldProps（仅`typeof fieldProps === 'function'`时）
- formItemProps（仅`typeof formItemProps === 'function'`时）

以上三种用法会导致每个onValuesChange都去重复构建DomList。
目前只能先这样workaround了

**Comment by ldwonday** [comment]
@rojer95 谢谢，valuType之前也有试过，也是卡，后来实在没办法就放弃了，直接用了antd的Form，我还是等你们修复好这个问题吧，毕竟renderFormItem可以直接依赖上下文，有的时候直接写renderFormItem更方便，valueType得多安装一个provider，并且得包裹组件。

**Comment by ldwonday** [comment]
大佬们这个问题在最新版又出问题了，卡的飞起啊，完全输不动
https://codesandbox.io/s/schema-biao-dan-forked-xemw24?file=/App.tsx

**Comment by ldwonday** [comment]
心好累

**Comment by ldwonday** [comment]
@chenshuai2144 重新打开的这个issue吧

**Comment by ldwonday** [comment]
https://github.com/ant-design/pro-components/pull/6874
