### ISSUE TITLE
🐛[BUG]模块 ""@ant-design/pro-form"" 没有导出的成员 "ProFormInstance"。

### ISSUE THREAD

**Issue by nickrogit** [ant-design/pro-components#4526]
import type { ProFormInstance } from '@ant-design/pro-form';
报：模块 ""@ant-design/pro-form"" 没有导出的成员 "ProFormInstance"。你是想改用 "import ProFormInstance from "@ant-design/pro-form"" 吗?

环境：vs code，ts，antd prov5

这是什么问题，如何解决？实际编译运行没有报错。

**Comment by 1247748612** [comment]
更新版本试试，1.52.7正常

**Comment by nickrogit** [comment]
> 更新版本试试，1.52.7正常
更新哪个的版本？

**Comment by nickrogit** [comment]
> 更新版本试试，1.52.7正常

更新哪个的版本？pro-form版本："@ant-design/pro-form": "^1.18.3",

**Comment by 1247748612** [comment]
> 更新哪个的版本？pro-form版本："@ant-design/pro-form": "^1.18.3",

往最新的升级
