### ISSUE TITLE
🧐[问题]使用BetaSchemaForm组件生成Select时出现问题

### ISSUE THREAD

**Issue by 8283792** [ant-design/pro-components#4528]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

使用BetaSchemaForm组件创建带有下拉新增的Select时，组件事件异常
在json配置的fieldProps中添加dropdownRender方法，在dropdownRender中绑定的事件会出现异常
如antdesign中的dropdownRender列子，输入框会无法输入

**Comment by 8283792** [comment]
https://ant.design/components/select-cn/#components-select-demo-custom-dropdown-menu能否提供一个使用schema方式生成类似的带有dropdown的例子，万分感谢

**Comment by 1247748612** [comment]
麻烦提供个复现
