### ISSUE TITLE
🧐[问题]ProForm  中的ProFormList   使用IE浏览器的加载会导致界面卡死 

### ISSUE THREAD

**Issue by DJGDragon** [ant-design/pro-components#4530]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

ProForm  中的ProFormList   使用IE浏览器的加载会导致界面卡死 
### 💻 示例代码

<ProFormList
      name={['list']}
      
      copyIconProps={false}
      itemRender={({ listDom, action }, { field, operation, record, meta }) => {
        return "xxx"
      }}
    >

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23696556/150743192-f3892d58-14fc-4a06-91a2-1a65ef631030.png)

**Comment by chenshuai2144** [comment]
这个看不出来是什么报错了
