### ISSUE TITLE
👑 [需求] ModalForm是否可以添加Loading属性，用于加载数据时候显示Spin  

### ISSUE THREAD

**Issue by lujiujiuyj** [ant-design/pro-components#4539]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述
ModalForm是否可以添加Loading属性，用于加载数据时候显示Spin

**Comment by chenshuai2144** [comment]
支持 request 属性的，可以用来解决这个问题
