### ISSUE TITLE
👑 [需求]  虚拟列表 也支持使用 列设置

### ISSUE THREAD

**Issue by zhangjiana** [ant-design/pro-components#4543]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述

使用proTable 后， 由于要使用大量数据，所以就使用了 虚拟列表的方案。但问题是，使用了虚拟列表后， proTable的列设置无效了。只能变动表头，不能变动`body`里面的值。 

### 🧐 解决方案

希望可以把`rc-table`中的`cell`暴露出来，然后在`columnState`的`onChange`时，每次给出所有现有的`columns`。

或者有其他可以实现虚拟列表中，可以进行列设置的方案。

**Comment by chenshuai2144** [comment]
去antd 提吧，我们这里是个高级封装

**Comment by zhangjiana** [comment]
能不能提供一个思路呢？ 怎么在虚拟的列表中 ，实现列设置功能。现在用了antd中 table的那个方案，但是只有头部可以固定，body里面的不会跟着变动。
