### ISSUE TITLE
🐛[BUG]PageContainer 当 title 为空时有多余空白

### ISSUE THREAD

**Issue by vision-ken** [ant-design/pro-components#4545]
### 🐛 bug 描述
升级到最新的"@ant-design/pro-layout": "^6.32.7", 并且设置：
```js
<PageContainer title={false}>
```
还是会有多余的空白，如下图：
![image](https://user-images.githubusercontent.com/24715266/151004051-470e5950-2189-49bb-b5b8-0cf270c3d3c0.png)

### 🏞 期望结果

不要出现多余空白

### © 版本信息

- ProComponents 版本: "@ant-design/pro-layout": "^6.32.7",
- umi 版本："^3.5.0"
- 浏览器环境：chrome， 97.0.4692.71
- 开发环境  mac OS 10.15.7

**Comment by leshalv** [comment]
<img width="737" alt="image" src="https://user-images.githubusercontent.com/30397655/154954355-e348533a-bb76-4aca-9e39-477a0b825aa1.png">
<img width="994" alt="image" src="https://user-images.githubusercontent.com/30397655/154954450-fd06fd39-f624-4765-bbdf-91b888487181.png">
@chenshuai2144  大佬看看是否存在样式问题

**Comment by chenshuai2144** [comment]
margin都是自带的。配置了就会有
