### ISSUE TITLE
Variable @primary-color-hover is undefined       in node_modules\@ant-design\pro-card\es\components\Actions\index.less 🐛[BUG]

### ISSUE THREAD

**Issue by digisquares** [ant-design/pro-components#4546]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by 1247748612** [comment]
更新antd版本试试
