### ISSUE TITLE
Multiple Field with path 'xxx' set 'initialValue'. Can not decide which one to pick

### ISSUE THREAD

**Issue by luoyifanff** [ant-design/pro-components#4550]
### 🧐 问题描述
我已经阅读过相关issue https://github.com/ant-design/pro-components/issues/1036
该问题仍存在，本地运行可以看到warning，或许判断了NODE_ENV？

### 💻 示例代码
使用defaultRender直接render schema：

renderFormItem: (schema, { defaultRender }) => {
  return defaultRender(schema);
}

### 🚑 其他信息
dom会是这样，多包了一层formItem：
![image](https://user-images.githubusercontent.com/31697066/151149803-3142f90e-ecd5-4a40-ba7d-507130bab1a6.png)

**Comment by NanYeYe** [comment]
+1！！

**Comment by chenshuai2144** [comment]
这个报错是多次设置了 initialValues 导致的，能来个重现吗？

**Comment by luoyifanff** [comment]
我贴图就是官网上的第一个例子

**Comment by weiboipad** [comment]
@chenshuai2144 

https://github.com/ant-design/pro-components/blob/2058bf4179246bd3dd9b2fc7888fb2665e316d30/packages/table/src/utils/cellRenderToFromItem.tsx#L177

这里看上去应该直接返回fieldDom

<img width="663" alt="image" src="https://user-images.githubusercontent.com/74544768/177329675-d6d7f022-9fe2-43a7-bb6a-ccdeaf23c37a.png">
