### ISSUE TITLE
🧐[问题]请教如何修改左侧菜单栏的背景色和菜单样式？

### ISSUE THREAD

**Issue by zlhy** [ant-design/pro-components#4552]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
请教下如何修改左侧菜单栏的背景色和菜单的样式？

### 🚑 其他信息

![无标题](https://user-images.githubusercontent.com/34714338/151281552-40354fb9-da73-4663-b5a4-e6b3e3622c20.jpg)

**Comment by chenshuai2144** [comment]
css 直接覆盖一下，现在不支持 api 切换
