### ISSUE TITLE
🐛[BUG] EditableProTable 加上name属性后删除会固定删最后一行

### ISSUE THREAD

**Issue by huangkaibo** [ant-design/pro-components#4553]
### 🐛 bug 描述

EditableProTable 如果加上name属性, 删除任意一行, 效果都是固定删最后一行

### 💻 复现代码

https://codesandbox.io/s/ke-bian-ji-biao-ge-forked-p55ri?file=/App.tsx

**Comment by kiner-tang** [comment]
为何要加`name`属性，什么场景？

**Comment by chenshuai2144** [comment]
name 属性必须要放到Form 里才能使用。

![image](https://user-images.githubusercontent.com/8186664/152683002-caec4980-323a-4d8d-9ff8-88543eb97f68.png)


控制台有报错的。
