### ISSUE TITLE
👑 [需求]Protable当页数据量超过500，勾选严重卡顿

### ISSUE THREAD

**Issue by strongyc** [ant-design/pro-components#4555]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述
]Protable当页数据量超过500，勾选严重卡顿

]Protable当页数据量超过500，勾选严重卡顿，该如何优化呀

**Comment by PlutoCA** [comment]
试试shouldCellUpdate
