### ISSUE TITLE
🧐[问题]设置了prefixCls，prolayout里有部分dom的class还是ant-pro开头

### ISSUE THREAD

**Issue by zlhy** [ant-design/pro-components#4559]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

设置了prefixCls，prolayout里有部分dom的class还是ant-pro开头

**Comment by chenshuai2144** [comment]
一般都是因为导入了两份 antd 导致的，你看看是不是 es 和 lib 的问题

**Comment by JoMartinezZhu** [comment]
> 一般都是因为导入了两份 antd 导致的，你看看是不是 es 和 lib 的问题

hello ,这个问题具体怎么解决的
为什么会导入两份 antd？

**Comment by mjj7890** [comment]
我也遇到了此问题，有解决方案嘛

**Comment by xian107** [comment]
> 我也遇到了此问题，有解决方案嘛

问题怎么解决？
![image](https://github.com/user-attachments/assets/2b8f4bbd-e63b-48eb-af80-ae09d50f70b2)
