### ISSUE TITLE
🐛[BUG] EditableProTable fixed table layout

### ISSUE THREAD

**Issue by 3hson** [ant-design/pro-components#4560]
### 🐛 bug description

there is a default value for EditableProTable tableLayout=fixed in the code that makes columns  crowded together and wrapped on mobile size 

### 📷 Steps to reproduce
![Screenshot from 2022-02-01 10-18-13](https://user-images.githubusercontent.com/36244081/151924616-e26e460d-aa62-40eb-af42-2444bff61b4b.png)

![Screenshot from 2022-02-01 10-22-53](https://user-images.githubusercontent.com/36244081/151924830-8d9a84cb-d5c9-403a-991a-6dace73c8e74.png)

**Comment by chenshuai2144** [comment]
开一下scroll 吧。不开layout，里面的组件就没有办法控制宽度了

**Comment by amin168** [comment]
@chenshuai2144 这里不能改一下，如果用户没有传参数的话，就默认是 `fixed` 么
