### ISSUE TITLE
🧐[问题] V5 How can I start signalR service

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/pro-components#4561]
Hello, Where can I start my signaling service? I couldn't find the appropriate place to start it in the app.tsx file.

Ant Design Pro V5

**Comment by chenshuai2144** [comment]
signaling service？

I don't know what this is

**Comment by xXAvoraXx** [comment]
Microsoft SignalR, In any state change, I send a signal to my API service to inform the clients that are on other connections that they need to renew the state, so there is an instant information exchange.

For now, I solved this situation as follows, I wanted to consult you if it is the right approach.

I initialize it in getInitialState in the app.tsx file. After the user is logged in, the signalR connection is opened.

I defined the signals coming from SignalR in the header components.

App.tsx

`  const startSignalR = async () => {
    const signalRService = new SignalRService();
    if (!signalRService.isConnected()) {
      await signalRService?.connect();
      await signalRService.define('GetConnectionId', (id: any) => {
        window.localStorage.setItem('connectionId', id);
      });
    }

    return signalRService;
  };
    if (currentUser) {
signalRService = await startSignalR();

    return {
      fetchUserInfo,
      currentUser,
      settings: defaultSettings,
      startSignalR,
      signalRService,
      signalRConnectionId,
    };
}
else{
history.push(loginPath);
}
  return {
    fetchUserInfo,
    startSignalR,
    settings: defaultSettings,
  };

--------------------------------------
Components -> HeaderSignalR
  const { initialState, setInitialState } = useModel('@@initialState');
  const { signalRConnectionId, signalRService} = initialState || {};
  useEffect(() => {
    if (initialState) {
      if (isEmpty(signalRConnectionId)) {
        setInitialState((preInitialState) => ({
          ...preInitialState,
          signalRConnectionId: window.localStorage.getItem('connectionId')!,
        }));
      }
    }
  }, [initialState, signalRConnectionId, setInitialState]);

  useEffect(() => {
    if (signalRService) {
      if (signalRService.isConnected()) {
        if (!isEmpty(signalRConnectionId)) {
          signalRService.define(
            'GetSignal',
            (signalEntity: object, connectionId: string) => {
              if (signalRConnectionId !== connectionId) {

                setInitialState((preInitialState) => ({
                  ...preInitialState,
                  entity: signalEntity,
                }));
              }
            },
          );

        }
      }
    }
  }, [signalRService, business, setInitialState, signalRConnectionId]);

`

**Comment by chenshuai2144** [comment]
You can set a custom layout, set it in the layout
