### ISSUE TITLE
🧐[问题]ProTable中valueType为option时怎么修改操作之间的间隔？

### ISSUE THREAD

**Issue by adkslf** [ant-design/pro-components#4571]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

ProTable高级表格 columns的valueType为option时怎么修改操作之间的间隔？当前默认间隔为16px，想要修改为8px

### 💻 示例代码
{
    title: '操作',
    valueType: 'option',
    width: 160,
    render: () => [
      <a key="link">查看</a>,
      <a key="link2" onClick={() => history.push('/goods/management/edit/1')}>
        编辑
      </a>,
      <TableDropdown
        key="actionGroup"
        menus={[
          {
            key: 'delete',
            name: '删除',
            onClick: () => {
              message.success('删除');
            },
          },
        ]}
      />,
    ],
  },

**Comment by 1247748612** [comment]
写死了16

或许你可以这样做
```typescript
<Space size={16}>
  <Button />
  <Button />
</Space>
```
