### ISSUE TITLE
Using ProLayout is causing error when running yarn dev or yarn build 🐛[BUG]

### ISSUE THREAD

**Issue by zerefati** [ant-design/pro-components#4573]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

Using **ProLayout** is causing error when running `yarn dev` or `yarn build`

### 🏞 期望结果

Below error comes up after running `yarn dev` or `yarn build`

<img width="1670" alt="Screen Shot 2022-02-08 at 2 03 06 PM" src="https://user-images.githubusercontent.com/17648619/152974866-89fe3739-b676-4cc8-bc1d-63ccaa2d0ca6.png">
<img width="1676" alt="Screen Shot 2022-02-08 at 2 03 24 PM" src="https://user-images.githubusercontent.com/17648619/152974877-f60c5131-2eb5-4af2-8edc-76562962f093.png">

### © 版本信息

- ProLayout 版本: 6.32.8
- NextJs 版本 v12.0.10
- 浏览器环境 Chrome Version 97.0.4692.99 (Official Build) (x86_64)
- 开发环境 MacOS

### 🚑 其他信息

<img width="1680" alt="Screen Shot 2022-02-08 at 2 10 53 PM" src="https://user-images.githubusercontent.com/17648619/152975790-7238a429-44d5-49ac-8e4e-f4968a6a7186.png">
<img width="1680" alt="Screen Shot 2022-02-08 at 2 10 55 PM" src="https://user-images.githubusercontent.com/17648619/152975793-b033c350-64ed-4213-a011-9242780823b6.png">
<img width="1680" alt="Screen Shot 2022-02-08 at 2 10 58 PM" src="https://user-images.githubusercontent.com/17648619/152975795-d09c8ff6-68a3-40b0-9de8-1c9dc73b744a.png">
<img width="1680" alt="Screen Shot 2022-02-08 at 2 11 00 PM" src="https://user-images.githubusercontent.com/17648619/152975797-1626aef4-860c-4c09-8550-083b20b32bbf.png">

**Comment by 1247748612** [comment]
It looks like your project doesn't support import statements, nothing to do with ProLayout

**Comment by zerefati** [comment]
Thanks for your comment.

But it happened when I update the ProLayout package, and when I remove the ProLayout package, the project work perfectly.

**Comment by chenshuai2144** [comment]
Did you set the loader for less?

**Comment by zerefati** [comment]
Yes, As you can see on the attached screenshots I have set up a loader for less in the next.config.js file.

**Comment by thdk** [comment]
I have a simple github repo with a bare nextjs application which suffers from the same error:

https://github.com/thdk/antd-pageheader

I see that some packages in ant design pro components have both a `lib` (commonjs)  and a `es` (es modules) output. However, some modules only have `es` (pro-layout). Usually the bundler (webpack) should be in charge of picking the correct files to import depending on the `type` (commonjs of modules) property in package.json. However, it seems some files directly import from the `..../es/...` path wich I believe could cause these issues.

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/commit/c25065e13953020bc88591a2e7d8829387ecd1ab
