### ISSUE TITLE
🧐[问题]ProTable在columns发生改变的时候，defaultSortOrder无法发挥作用。

### ISSUE THREAD

**Issue by kilik52** [ant-design/pro-components#4575]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

我们这边有一个特殊情况：columns的配置的定义是和datasource一起从一个接口中返回的。

也就是说ProTable在最开始的时候，columns为空数组。当request函数调用之后，columns才会被确定下来。这个时候，如果在某一个column里面设置属性：defaultSortOrder = 'ascend'，ProTable并不会显示这个sort处于ascend状态。

我是否有办法在columns发生改变的时候让table回到带有defaultSortOrder的状态？

我试了这几个都没用：

```js
// 刷新
ref.current.reload();

// 刷新并清空,页码也会重置，不包括表单
ref.current.reloadAndRest();

// 重置到默认值，包括表单
ref.current.reset();
```

### 💻 示例代码

无

**Comment by chenshuai2144** [comment]
这个不支持受控的，用 antd 原生的办法吧
