### ISSUE TITLE
🐛[BUG] EditableProTable currency symbol does not change on Money Field.

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/pro-components#4577]
Hello, I have created money field in EditableProTable, but there is a problem. Not every country has a currency symbol based on its location information, so I set up a library that contains currency symbols for all countries. I want to show this symbol according to the user's country, but the customssymbol property is not working.

![screensh](https://user-images.githubusercontent.com/6988989/153080986-8293a366-16e9-456e-895b-00d6e894ee9d.png)

```
   {
      title: 'Unit Price',
      dataIndex: 'unitPrice',
      valueType: 'money',
      fieldProps: {
        min: 0,
        max: 200000,
        locale: "en-GB" // ---> NOT WORK
        customSymbol: "GB" // ---->> NOT WORK
      },
      formItemProps: (form, { rowIndex }) => {
        return {
          rules: [{ required: true }],
        };
      },
    },
```

**Comment by 1247748612** [comment]
customSymbol and locale are at the root level

use like this

```typescript

   {
      title: 'Unit Price',
      dataIndex: 'unitPrice',
      valueType: 'money',
      customSymbol: "GB",
      locale: "en-GB",
      fieldProps: {
        min: 0,
        max: 200000,
      },
      formItemProps: (form, { rowIndex }) => {
        return {
          rules: [{ required: true }],
        };
      },
    },
```

**Comment by xXAvoraXx** [comment]
> 

Not work

**Comment by xXAvoraXx** [comment]
> customSymbol and locale are at the root level
> 
> use like this
> 
> ```ts
>    {
>       title: 'Unit Price',
>       dataIndex: 'unitPrice',
>       valueType: 'money',
>       customSymbol: "GB",
>       locale: "en-GB",
>       fieldProps: {
>         min: 0,
>         max: 200000,
>       },
>       formItemProps: (form, { rowIndex }) => {
>         return {
>           rules: [{ required: true }],
>         };
>       },
>     },
> ```

Not Work

**Comment by chenshuai2144** [comment]
```tsx
 {
      title: 'Unit Price',
      dataIndex: 'unitPrice',
      valueType: 'money',
      fieldProps: {
        min: 0,
        max: 200000,
        customSymbol: "GB",
        locale: "en-GB",
      },
      formItemProps: (form, { rowIndex }) => {
        return {
          rules: [{ required: true }],
        };
      },
    },
```

**Comment by xXAvoraXx** [comment]
> ```tsx
>  {
>       title: 'Unit Price',
>       dataIndex: 'unitPrice',
>       valueType: 'money',
>       fieldProps: {
>         min: 0,
>         max: 200000,
>         customSymbol: "GB",
>         locale: "en-GB",
>       },
>       formItemProps: (form, { rowIndex }) => {
>         return {
>           rules: [{ required: true }],
>         };
>       },
>     },
> ```

React does not recognize the `customSymbol` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `customsymbol` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by xXAvoraXx** [comment]
Yesterday I turned off my computer after I wrote this problem here, today I was going to open the project and try the change you made after seeing that this problem has been fixed, but I encountered this error. The console screen was not printing such an error yesterday.
![problem](https://user-images.githubusercontent.com/6988989/153582363-600a74d8-6346-4edd-a973-29c6434a6a1b.png)

Digit fields appear to be corrupted.
![fields](https://user-images.githubusercontent.com/6988989/153582412-c582697c-7cd6-4616-bbe4-7d1c2f52e2fa.png)

To test if the problem is with me, I opened a new project and moved all the code there, but the problem is not solved.

**Comment by xXAvoraXx** [comment]
> Yesterday I turned off my computer after I wrote this problem here, today I was going to open the project and try the change you made after seeing that this problem has been fixed, but I encountered this error. The console screen was not printing such an error yesterday. ![problem](https://user-images.githubusercontent.com/6988989/153582363-600a74d8-6346-4edd-a973-29c6434a6a1b.png)
> 
> Digit fields appear to be corrupted. ![fields](https://user-images.githubusercontent.com/6988989/153582412-c582697c-7cd6-4616-bbe4-7d1c2f52e2fa.png)
> 
> To test if the problem is with me, I opened a new project and moved all the code there, but the problem is not solved.

I guess this error is related to the editable table component itself.

If we go back to our topic, customSymbol seems to be working, only react gives a typo. customSymbol works on the form field as desired, but still another currency unit comes in the table.

`Warning: React does not recognize the `customSymbol` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `customsymbol` instead. If you accidentally passed it from a parent component, remove it from the DOM element`

**Comment by chenshuai2144** [comment]
i add this code for next version
```tsx
{...omit(fieldProps, [
          'numberFormatOptions',
          'precision',
          'numberPopoverRender',
          'customSymbol',
        ])}
```

**Comment by yogithesymbian** [comment]
why width field is not 100% ?

**Comment by yogithesymbian** [comment]
why when use valueType: "money" the width is not working ? 
for example 
```
{
                title: "Harga",
                dataIndex: "harga_kg",
                valueType: "money", // with this with doesnt work
                // width: WidgetWidth.w50,
                width: "50%",
              },
```

**Comment by xXAvoraXx** [comment]
> why when use valueType: "money" the width is not working ? for example
> 
> ```
> {
>                 title: "Harga",
>                 dataIndex: "harga_kg",
>                 valueType: "money", // with this width doesnt work
>                 // width: WidgetWidth.w50,
>                 width: "50%",
>               },
> ```

did you try this -> style: {{ width: "50%" }}
