### ISSUE TITLE
🐛[BUG] pro-layout 在使用react-router-dom@6的HashRouter不会选中菜单

### ISSUE THREAD

**Issue by binvb** [ant-design/pro-components#4581]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
如题

### 📷 复现步骤
https://codesandbox.io/live/a734c683363

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]
- react-router-dom: @6.2.1

**Comment by chenshuai2144** [comment]
暂时还没有支持 react-router-6 欢迎来提pr。
