### ISSUE TITLE
🧐[问题] EditableProTable - How do I trigger the cancel button when I switch between tabs?

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/pro-components#4586]
I added tab to editable table, when tab state changes, I change the entity scheme of the table. For example, if products are selected above, API.Product is added to the table, if Categories are selected, API.ProductCategory is added.

The problem is, in both cases, I get an error when I switch between tabs without making any changes after pressing the create new product or new category button. In addition, whichever tab I switch to, empty data occurs in the table on that tab.

![product](https://user-images.githubusercontent.com/6988989/153229275-7124425d-d6dd-4b6c-a1e1-c4c83c4e30cb.png)

In the first example, when I click the create new product button while on the products tab, and switch to the categories tab without making any changes, the problem seen in the picture below occurs.

![category](https://user-images.githubusercontent.com/6988989/153230287-e94de8b8-9b1e-425a-b645-27f66967843f.png)

**How do I trigger the cancel button when I switch between tabs?**

![err](https://user-images.githubusercontent.com/6988989/153230850-796ec7eb-f33b-442c-b7f0-93ea3474a644.png)

```
      <EditableProTable<API.Product | API.ProductCategory>
        rowKey={tableTabKey === 'products' ? 'productId' : 'productCategoryId'}
        maxLength={5}
        loading={loading}
        search={{ filterType: 'query' }}
        pagination={{ position: ['bottomRight'] }}
        toolbar={{
          menu: {
            type: 'tab',
            activeKey: tableTabKey,
            items: tabList,
            onChange: (key: any) => {
              setTableTabKey(key);
            },
          },
        }}
        recordCreatorProps={{
          position: 'top',
          creatorButtonText: tableTabKey === 'products' ? 'New Product' : 'New Category'
          record: () =>
            tableTabKey === 'products'
              ? { productId: newID, isActive: true, onKitchen: true }
              : { productCategoryId: newID, isActive: true, onKitchen: true },
        }}
        columns={tableTabKey === 'products' ? columns : columnsCategory}
        value={
          tableTabKey === 'products'
            ? products
            : categories
        }
        editable={{
          type: 'multiple',
          editableKeys,
          form: editForm,
          onSave: async (rowKey, data, row) => {
            console.log(rowKey, data, row);
            await waitTime(2000);
          },
          onChange: setEditableRowKeys,
        }}
      />
```

**Comment by chenshuai2144** [comment]
I think you should give a different key to destroy the table.

```tsx
 <EditableProTable<API.Product | API.ProductCategory key={tableTabKey} />
```
