### ISSUE TITLE
🧐[问题]请问pro-components支持的浏览器版本

### ISSUE THREAD

**Issue by charminghiker** [ant-design/pro-components#4587]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

测试使用的chrome 49.0.2623.75版本。
项目用的umi+antd+proComponents，载入页面后一直是加载中，图片如下。
![image](https://user-images.githubusercontent.com/34738577/153332241-5fefaa49-362a-433e-ae1b-861e30e15431.png)
请问是因为这个浏览器版本不支持吗？
pro-components默认支持版本是多少？如何配置？

**Comment by chenshuai2144** [comment]
https://umijs.org/config#targets


看这里

**Comment by charminghiker** [comment]
@chenshuai2144
umi的已经配置过了：
targets: {
    ie: 11,
    chrome: 38,
 }
未指定chrome: 38时中间加载图标不旋转，指定38后加载图标旋转了，依然进不了页面。
