### ISSUE TITLE
🐛[BUG] ProFormUploadButton 中使用data属性的时候ts会报错.提示不存在data属性

### ISSUE THREAD

**Issue by HengCC** [ant-design/pro-components#459]
### 🐛 bug 描述

ProFormUploadButton 中使用data属性的时候ts会报错.提示不存在data属性

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/6167532/92773522-4505a880-f3cf-11ea-9be9-618eb010a731.png)

**Comment by HengCC** [comment]
emmm..似乎 fileList onPreview onChange 也都提示属性不存在..

**Comment by chenshuai2144** [comment]
用 fieldProps ，这个才是组件的，ProFormUploadButton 是 fromItem 的
