### ISSUE TITLE
🧐[问题] 文档的margin边距为何要去掉，现在看着很奇怪

### ISSUE THREAD

**Issue by 1247748612** [ant-design/pro-components#4594]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

ref: https://github.com/umijs/dumi/issues/1009#issue-1125691120

**Comment by chenshuai2144** [comment]
css 写的有问题，一会加回来
