### ISSUE TITLE
🧐[问题] 对Pro-Form里当syncUrl为 true时设置 initialValues 优先级的疑问

### ISSUE THREAD

**Issue by luotongzhou** [ant-design/pro-components#4595]
### 🧐 问题描述

当使用pro-table时，透传form的props syncUrl 为true，第一次挂载pro-form里的BaseForm会从url 中读取search参数作为一个State(urlParamsMergeInitialValues)，并与透传的initialValues合并作Form的initialValues,但透传的initialValues props优先级更高。
我的需求是：当url search上有该字段的值时，以url search上的值为初始值，若没有，则以定义的initialValues为准。
但BaseForm initialValues的设定不符合我的需求。并且如果通过设置pro-table column中的initialValue字段设置初始值的话，虽然符合我的需求，但控制台会给我警告
```
react_devtools_backend.js:4061 Warning: Form already set 'initialValues' with path 'xxx'. Field can not overwrite it.
```

### 💻 示例代码

```
const column = [
  {
      title: t('campaign.campaign.type'),
      dataIndex: 'intention',
      initialValue: CampaignIntention.App,
      valueType: 'select',
      width: 85,
      fieldProps: {
        allowClear: false,
        options: [
          {
            label: <LocaleFormatter id="campaign.campaign.type.app" />,
            value: CampaignIntention.App,
          },
        ],
      },
  }
]
```
如果这样设置初始值，控制台报警告

```
<ProTable form={{initialValues: { intention: CampaignIntention.App }}} />
```
如果这样设置初始值，从url search值始终会被这个initialValues代替，原因是BaseForm中的代码

![image](https://user-images.githubusercontent.com/27920863/153375207-629f4ef7-ac9a-4a15-a820-5186142821cb.png)

我看了下，如果urlParamsMergeInitialValues的优先级更高，写在下面，是不是更合理一点

**Comment by chenshuai2144** [comment]
url 的优先级低一点。url的输入毕竟不可靠一点

**Comment by luotongzhou** [comment]
> 

意思是从url上取得的值没有经过完全的合法转化到表单导致错误吗？
确实存在这种可能性

**Comment by chenshuai2144** [comment]
还可能被复写什么的，不好控制。
