### ISSUE TITLE
🐛[BUG] ProFormChecbox 表单获取值错误

### ISSUE THREAD

**Issue by T-Flynn** [ant-design/pro-components#4596]
### 🐛 bug 描述

表单校验获取到的值为checkbox的event对象

### 📷 复现步骤

在checkbox onChange 之后，表单获取到的值为event对象

### 🏞 期望结果

正常获取Checkbox的值

### 💻 复现代码
```javascript
  const handleSubmit = async (values) => {
    console.log(values);
....

  <ProFormCheckbox noStyle name="rememberPassword">
         记住密码
  </ProFormCheckbox>
```

### © 版本信息

- ProComponents 版本: @ant-design/pro-form 1.53.1
- umi 版本: 3.5.20
- 浏览器环境: chrome 98.0.4758.80 (正式版本) (arm64)
- 开发环境: mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/32189234/153386823-147a029a-e5af-42d3-b73b-c8731e5e8a78.png)

**Comment by chenshuai2144** [comment]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/8186664/153532666-0c4a219a-e8ab-4fd6-bd13-304a1c471dcd.png">


试了一下，并不会。


```tsx
import React from 'react';
import ProForm, { ProFormText, ProFormCheckbox, ProFormRadio } from '@ant-design/pro-form';

import { Button } from 'antd';

const layout = {
  labelCol: { span: 8 },
  wrapperCol: { span: 16 },
};
const tailLayout = {
  wrapperCol: { offset: 8, span: 16 },
};

export default () => {
  return (
    <>
      <ProForm
        {...layout}
        layout="horizontal"
        submitter={false}
        name="basic"
        initialValues={{ remember: true }}
        onFinish={async (e) => {
          console.log(e);
        }}
      >
        <ProFormText label="Name" name="name" />
        <ProFormText.Password
          label="Password"
          name="password"
          rules={[{ required: true, message: 'Please input your password!' }]}
        />
        <ProFormCheckbox noStyle name="remember" {...tailLayout}>
          Remember me
        </ProFormCheckbox>
        <ProFormRadio name="remember" {...tailLayout}>
          Remember me
        </ProFormRadio>
        <ProForm.Item {...tailLayout}>
          <Button type="primary" htmlType="submit">
            Submit
          </Button>
        </ProForm.Item>
      </ProForm>
    </>
  );
};

```

**Comment by T-Flynn** [comment]
> <img alt="image" width="1552" src="https://user-images.githubusercontent.com/8186664/153532666-0c4a219a-e8ab-4fd6-bd13-304a1c471dcd.png">
> 
> 试了一下，并不会。
> 
> ```tsx
> import React from 'react';
> import ProForm, { ProFormText, ProFormCheckbox, ProFormRadio } from '@ant-design/pro-form';
> 
> import { Button } from 'antd';
> 
> const layout = {
>   labelCol: { span: 8 },
>   wrapperCol: { span: 16 },
> };
> const tailLayout = {
>   wrapperCol: { offset: 8, span: 16 },
> };
> 
> export default () => {
>   return (
>     <>
>       <ProForm
>         {...layout}
>         layout="horizontal"
>         submitter={false}
>         name="basic"
>         initialValues={{ remember: true }}
>         onFinish={async (e) => {
>           console.log(e);
>         }}
>       >
>         <ProFormText label="Name" name="name" />
>         <ProFormText.Password
>           label="Password"
>           name="password"
>           rules={[{ required: true, message: 'Please input your password!' }]}
>         />
>         <ProFormCheckbox noStyle name="remember" {...tailLayout}>
>           Remember me
>         </ProFormCheckbox>
>         <ProFormRadio name="remember" {...tailLayout}>
>           Remember me
>         </ProFormRadio>
>         <ProForm.Item {...tailLayout}>
>           <Button type="primary" htmlType="submit">
>             Submit
>           </Button>
>         </ProForm.Item>
>       </ProForm>
>     </>
>   );
> };
> ```

![image](https://user-images.githubusercontent.com/32189234/153545371-35c8f88e-86c6-4dce-87b8-9f1d926a6d7b.png)
这是当前示例在点击checkbox前后，点击提交的效果

**Comment by chenshuai2144** [comment]
修复了，等我发布
