### ISSUE TITLE
👑 [需求] layout 在 top 和 mix 模式下，顶部菜单提供居左（现在默认的）、居中、居右设置

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-components#46]
### 🥰 需求描述

layout 在 top 和 mix 模式下，顶部菜单提供居左（现在默认的）、居中、居右设置

![image](https://user-images.githubusercontent.com/18542211/88679592-26e73000-d122-11ea-9639-1aa4998a8a97.png)

**Comment by chenshuai2144** [comment]
设计师不会同意的。。。。

**Comment by rdmclin2** [comment]
居左 + 1
