### ISSUE TITLE
🐛[BUG]proTable 搜索组件问题

### ISSUE THREAD

**Issue by maochongzi** [ant-design/pro-components#460]
proTable搜索表单问题

下拉选择内容太长时会出现样式错乱

如图：
![image](https://user-images.githubusercontent.com/34764808/92851052-be2cec00-f41f-11ea-83ec-0772a423ea2f.png)

**Comment by chenshuai2144** [comment]
不写标题会被关掉

**Comment by hengkx** [comment]
搞个 机器人 自动 处理吧

**Comment by maochongzi** [comment]
@chenshuai2144
