### ISSUE TITLE
🐛[BUG]关于搜索表单重复请求 原先bug#1055  没有修复

### ISSUE THREAD

**Issue by wh77572** [ant-design/pro-components#4601]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProTable组件的搜索表单，在多个字段展开和收起的时候，都会调用请求接口请求数据
原先bug  #1055

### 📷 复现步骤

点击展开和收起，都会调用请求接口，浪费了资源

### 🏞 期望结果

只调用一次接口

### 💻 复现代码

https://codesandbox.io/s/peaceful-dream-u0yol

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
展开收齐dom是被销毁的，浪费一点吧，能省一些渲染资源。
