### ISSUE TITLE
ProTable  row selection checkbox 长度太大，怎么控制长度？

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#4602]
用CSS控制ProTable  row selection checkbox的 长度不管用。
怎么控制长度？
![image](https://user-images.githubusercontent.com/5349879/153544244-e7beff72-0cc5-4fd1-bbee-9bda9a1d9a34.png)

**Comment by chenshuai2144** [comment]
在列里面直接控制长度。table 要求一定要撑满的。你留一行不要设置，让他自由控制

**Comment by gaohongwei** [comment]
> 

ProTable row selection checkbox 不是自己定义的列，能在列里面定义width吗？给个例子看看
