### ISSUE TITLE
🐛[BUG]ProLayout在mix模式下，头部面包屑看不到

### ISSUE THREAD

**Issue by gehaijun** [ant-design/pro-components#4603]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

混合布局下，头部面包屑存在，但是是黑色，且样式错乱

### 💻 复现代码

`<ProLayout
        logo={false}
        headerContentRender={() => {
          return <ProBreadcrumb />;
        }} ...rest/>`

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/35563401/153548465-54e00984-3c9a-4e09-8d8a-c3b45eb7cb6b.png)
![image](https://user-images.githubusercontent.com/35563401/153548519-863d80fb-25a8-4bea-8fb7-787253dfc4b5.png)

**Comment by chenshuai2144** [comment]
自定的时候要自己处理一下的。外面包一下 style ，自己处理一把

**Comment by jiayongchang** [comment]
外面包一下 style是怎么一回事？
