### ISSUE TITLE
🧐[问题]请问有遇到 createField_default is not a function 这个错误信息的吗？

### ISSUE THREAD

**Issue by weiheli** [ant-design/pro-components#4604]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

我把以前的使用了 ProComponents 组件的页面迁移到新项目，发现使用 `@ant-design/pro-table` `@ant-design/pro-form` `@ant-design/pro-descriptions` 组件的页面会报如下错误

```
TypeError: createField_default is not a function
```

把这些组件注释掉就是不报错，使用了就报如上错误，即使我从官网把这些组件的Demo代码考进来也是报这个错，所以我觉得不是业务代码逻辑的问题，不知道是不是依赖版本的问题，或者有冲突

### 🚑 其他信息

部分依赖如下

```
"@ant-design/icons": "~4.7.0",
"@ant-design/pro-layout": "~6.32.8",
"@emotion/react": "~11.7.1",
"@emotion/styled": "~11.6.0",
"antd": "^4.18.6",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-router-dom": "~6.2.1",
"mobx": "~6.3.13",
"mobx-react-lite": "~3.2.3",
"moment": "~2.29.1",
"react-i18next": "~11.15.4",
"i18next": "~21.6.11",
"axios": "~0.25.0",
"@ant-design/pro-table": "~2.63.1",
"nanoid": "~3.2.0",
"@ant-design/pro-form": "~1.53.1",
"@ant-design/pro-descriptions": "~1.10.39",
```

**Comment by Jungzl** [comment]
[repo](https://github.com/Jungzl/vite-prop-components)

尝试了一下，单独安装使用`@ant-design/pro-table` 或者`@ant-design/pro-form` 都没问题，同时使用会有这个报错

**Comment by Jungzl** [comment]
不过umi项目中没有这个问题，可能是vite相关的

**Comment by lovelyyl** [comment]
vite循环引用报错了。


Export "default" of module node_modules/.pnpm/registry.npmmirror.com+@ant-design+pro-form@1.53.3_9944c2e905c8c7df36c01d9be8a6e3e0/node_modules/@ant-design/pro-form/es/components/Field/index.js was reexported through module node_modules/.pnpm/registry.npmmirror.com+@ant-design+pro-form@1.53.3_9944c2e905c8c7df36c01d9be8a6e3e0/node_modules/@ant-design/pro-form/es/index.js while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.

**Comment by lovelyyl** [comment]
<img width="934" alt="image" src="https://user-images.githubusercontent.com/45654799/153702424-8f40bae3-94b1-48ad-a3b2-f3cce8ed842c.png">

**Comment by 1247748612** [comment]
> vite循环引用报错了。

这块的路径没写好导致的

我这边直接修改node_modules的dependency路径
![image](https://user-images.githubusercontent.com/29533304/153702954-d6c26359-d378-473c-9caf-97db584eb06e.png)

正常打开了
![image](https://user-images.githubusercontent.com/29533304/153702971-3cabfb6a-f463-4cc1-9a60-dd83a34200d4.png)

我想问下你这个报错是哪里看到的，我运行起来没任何报错

**Comment by lovelyyl** [comment]
> > vite循环引用报错了。
> 
> 这块的路径没写好导致的
> 
> 我这边直接修改node_modules的dependency路径 ![image](https://user-images.githubusercontent.com/29533304/153702954-d6c26359-d378-473c-9caf-97db584eb06e.png)
> 
> 正常打开了 ![image](https://user-images.githubusercontent.com/29533304/153702971-3cabfb6a-f463-4cc1-9a60-dd83a34200d4.png)
> 
> 我想问下你这个报错是哪里看到的，我运行起来没任何报错

vite升级到最新版本，然后build就会有这个警告。

dev 运行，就会报这个createFilexxx的错误。

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/45654799/153709508-a0a9f990-5642-42f9-92c8-d19c43066ed2.png">

**Comment by 1247748612** [comment]
> vite升级到最新版本，然后build就会有这个警告。
> 
> dev 运行，就会报这个createFilexxx的错误。
> 
> <img alt="image" width="1082" src="https://user-images.githubusercontent.com/45654799/153709508-a0a9f990-5642-42f9-92c8-d19c43066ed2.png">

了解了
