### ISSUE TITLE
🐛[BUG]useDeepCompareMemoize中使用isEqual来进行深比较会出现infinite loop的情况

### ISSUE THREAD

**Issue by LeoooY** [ant-design/pro-components#461]
### 🐛 bug 描述

useDeepCompareMemoize中使用isEqual来进行深比较会出现infinite loop的情况

### 📷 复现步骤
在dev环境开发时，偶尔出现页面直接卡死的情况，使用chrome开发者工具查看调用堆栈发现isEqual一直循环调用。
![bug](https://user-images.githubusercontent.com/38848201/92850547-2202e500-f41f-11ea-989e-43e20072c063.png)

### © 版本信息

- ProComponents 版本: latest
- umi 版本 2.12.5
- 浏览器环境 chrome 85.0.4183.102
- 开发环境 ubuntu20.04

### 🚑 其他信息
参考[react-use](https://github.com/streamich/react-use)实现的useDeepCompareMemoize中使用的是[fast-deep-equal](https://github.com/epoberezkin/fast-deep-equal)的react版本特殊处理的isEqual。

处理了react元素比较时候的循环引用问题：
![Screenshot from 2020-09-11 11-14-37](https://user-images.githubusercontent.com/38848201/92851375-119f3a00-f420-11ea-9d17-423ba6a5d652.png)

**Comment by chenshuai2144** [comment]
有兴趣来个 pr 吗？

**Comment by LeoooY** [comment]
我在自己的项目中是直接copy了[fast-deep-equal]()的react版本实现，关键代码其实就是这块![Screenshot from 2020-09-11 11-14-37](https://user-images.githubusercontent.com/38848201/92851375-119f3a00-f420-11ea-9d17-423ba6a5d652.png)在开源项目中不知道怎么处理比较好？1 直使用引用[fast-deep-equal](https://github.com/epoberezkin/fast-deep-equal)的react版本 2 拷贝[fast-deep-equal](https://github.com/epoberezkin/fast-deep-equal)的实现到项目中


还有个思路就是用lodash的[isEqualWith](https://lodash.com/docs/4.17.15#isEqualWith)自定义一个react版本的实现

**Comment by LeoooY** [comment]
补充信息：React会在dev环境添加一个_owner属性
![Screenshot from 2020-09-11 14-26-21](https://user-images.githubusercontent.com/38848201/92874643-ce05f980-f43a-11ea-91bc-2db7534a386f.png)

**Comment by chenshuai2144** [comment]
@LeoooY  这个库的大小能解决，直接依赖好了 
https://www.npmjs.com/package/fast-deep-equal

**Comment by LeoooY** [comment]
在react下提了同样的issue，dan的建议是不要将两个react元素做深比较，对性能上好像有些影响
facebook/react#19811

**Comment by chenshuai2144** [comment]
@LeoooY  我们没办法控制 用户的 icon 是不是 ReactNode, 可以自定义一下如果是 ReactNode 直接忽略一下
