### ISSUE TITLE
🧐[问题] EditableProTable如何在重新加载时去掉loading的动画

### ISSUE THREAD

**Issue by jayt1001** [ant-design/pro-components#4619]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

我的弹窗中有如下代码，
![1644760647(1)](https://user-images.githubusercontent.com/29675005/153756475-a01d23b9-b0e6-406f-81cf-971a42d38f1b.png)

在我useState变更后，可编辑表格都会出现下面的动画后才会进行展示，我想将其去除不知如何处理

![image](https://user-images.githubusercontent.com/29675005/153756442-73b927f4-eddd-40e5-b161-180d539b858e.png)

**Comment by chenshuai2144** [comment]
来个重现来看看呢
