### ISSUE TITLE
🐛[BUG]  ProForm 表单输入框清除操作控制台报错 "this.elements[0][s].split is not a function"

### ISSUE THREAD

**Issue by MsmileLDM** [ant-design/pro-components#4624]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤
链接：https://procomponents.ant.design/playground/pro-form
![image](https://user-images.githubusercontent.com/99628554/153794088-82743c39-722c-409f-b8f4-f016602eb1cf.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
浏览器版本的问题吧？ 我试了没问题

**Comment by MsmileLDM** [comment]
> 浏览器版本的问题吧？ 我试了没问题
> 
> 或者是你的插件

我移除了插件，确实没问题了，谢啦！
