### ISSUE TITLE
🐛[BUG] When <ProFormList> wraps <ProFormTimePicker.RangePicker> the transform attribute  is invalid

### ISSUE THREAD

**Issue by Huangqye** [ant-design/pro-components#4625]
### 📷 复现步骤

![image](https://user-images.githubusercontent.com/24401771/153783641-eaebe132-1001-4437-b3a0-fb0b08e40054.png)
![image](https://user-images.githubusercontent.com/24401771/153783815-ab8f91d0-4fb5-4952-b1c6-91513ee57c8d.png)

### © 版本信息

- "@ant-design/pro-table": "^2.62.0",
- 浏览器环境
- 开发环境 [win]

**Comment by 469346971** [comment]
Sorry, there are 4 useless records caused by submitting issues for the first time. Could you help me delete them——[4620,4621,4622,4623,]

**Comment by ratelgogo** [comment]
+1

**Comment by ncnt257** [comment]
I can't use transform in an item of ProFormList too :((

**Comment by leshalv** [comment]
+1

**Comment by chenshuai2144** [comment]
看看 dayjs 是不是重复了，这个功能现在已经修复了
