### ISSUE TITLE
👑 [需求]ProTable某列设置hideInTable后，列设置中可以设置该列展示隐藏

### ISSUE THREAD

**Issue by tina316** [ant-design/pro-components#4627]
### 🥰 需求描述
我发现某一列数据设置hideInTable后，列设置中不能设置改列展示，
能否在设置hideInTable为true后，列设置中hideInTable为true的列表也可以展示。

**Comment by chenshuai2144** [comment]
不想显示用 columnsState 来操作，hideInTable 直接就不渲染了
