### ISSUE TITLE
🧐[问题] esm和lib模块相关的polyfill

### ISSUE THREAD

**Issue by 1247748612** [ant-design/pro-components#4628]
### esm/lib 无需引入polyfill相关代码

esm和lib都是打包后的产物，这些模块都不能直接在浏览器中使用，需要经过编译工具去打包成浏览器能执行的code，这时候也会做polyfill的支持。

按这种情况来说，pro-components打包后的lib和esm文件是不需要做兼容性的处理，交给使用方处理就可以了。

### 这样做的好处有
1. 减小代码体积
2. 避免开发环境引入这些polyfill代码

可能我有未考虑到情况，可以指正一下

**Comment by chenshuai2144** [comment]
webpack 为了性能不会处理 nodemoudles 里面的代码吧。
lib还是要处理的，es 处理的已经很少了

**Comment by 1247748612** [comment]
倒也不是很多

无论是在vite和webpack的开发环境都引入了，目前polyfill相关引入都是在father-build中写死了，想去掉也没办法
