### ISSUE TITLE
> > vite循环引用报错了。

### ISSUE THREAD

**Issue by sudongyuer** [ant-design/pro-components#4630]
> > vite循环引用报错了。
> 
> 这块的路径没写好导致的
> 
> 我这边直接修改node_modules的dependency路径 ![image](https://user-images.githubusercontent.com/29533304/153702954-d6c26359-d378-473c-9caf-97db584eb06e.png)
> 
> 正常打开了 ![image](https://user-images.githubusercontent.com/29533304/153702971-3cabfb6a-f463-4cc1-9a60-dd83a34200d4.png)
> 
> 我想问下你这个报错是哪里看到的，我运行起来没任何报错

vite升级到最新版本，然后build就会有这个警告。

dev 运行，就会报这个createFilexxx的错误。

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/45654799/153709508-a0a9f990-5642-42f9-92c8-d19c43066ed2.png">

_Originally posted by @lovelyyl in https://github.com/ant-design/pro-components/issues/4604#issuecomment-1037161103_

**Comment by chenshuai2144** [comment]
修复了，尽量不要用 lib 包

**Comment by sudongyuer** [comment]
> 修复了，尽量不要用 lib 包

我是用的vite 很多问题 并没有修复哦

**Comment by chenshuai2144** [comment]
vite是社区在维护，官方不保证百分百能用
