### ISSUE TITLE
🐛[BUG]settings里，拖拽列排序之后，固定列消失、不起作用了

### ISSUE THREAD

**Issue by Harry-Yu-01** [ant-design/pro-components#4633]
settings里，拖拽列排序之后，固定列消失、不起作用了
![img_20220214163837](https://user-images.githubusercontent.com/18259784/153829193-9c3eac1d-73b2-45de-aee9-f70dede803d9.png)
![img_20220214164014](https://user-images.githubusercontent.com/18259784/153829258-9996f10d-3364-4d3b-94f3-26fb01032814.png)

**Comment by Harry-Yu-01** [comment]
您好，您的邮件我已收到，将尽快给您回复。

**Comment by Harry-Yu-01** [comment]
https://codesandbox.io/s/cha-xun-wu-an-niu-biao-ge-forked-gdx78?file=/App.tsx
这里能看到复现

**Comment by Harry-Yu-01** [comment]
或者设置一列固定，在settings里拖动其他的列排序就能复现

**Comment by shijie-chen-0810** [comment]
我也碰到了这个情况，这种情况只在第一次有固定的列，并且给下面不固定的列排序才会出现问题

**Comment by chenshuai2144** [comment]
改了下方案，不能跨tree 拖拽了

**Comment by Harry-Yu-01** [comment]
您好，您的邮件我已收到，将尽快给您回复。

**Comment by Harry-Yu-01** [comment]
您好，您的邮件我已收到，将尽快给您回复。

**Comment by Harry-Yu-01** [comment]
Thank you.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月4日(周一) 下午3:23
收件人: ***@***.***&gt;;
抄送: "Harry ***@***.******@***.***&gt;;
主题: Re: [ant-design/pro-components] 🐛[BUG]settings里，拖拽列排序之后，固定列消失、不起作用了 (Issue #4633)




 
Closed #4633 as completed.

**Comment by Harry-Yu-01** [comment]
您好，您的邮件我已收到，将尽快给您回复。
