### ISSUE TITLE
🐛[BUG]protable的search默认带rules

### ISSUE THREAD

**Issue by lsh-sihong** [ant-design/pro-components#4635]
当columns中配置了
formItemProps: {
        rules: [
          {
            required: true,
            message: "请输入通道名称",
          },
        ],
      },

搜索表单会带“*”

**Comment by lsh-sihong** [comment]
> requiredMark	必选样式，可以切换为必选或者可选展示样式。此为 Form 配置，Form.Item 无法单独配置	boolean | optional	true	4.6.0
> 配置这个关掉
![image](https://user-images.githubusercontent.com/49470467/153858851-439cb297-ec0f-4f7e-843a-73d45d668dee.png)


依然会校验必填，因为columns配置除了表格在使用，也会应用type="form"，需要formItemProps配置

**Comment by chenshuai2144** [comment]
formItemProps | 传递给 Form.Item 的配置,可以配置 rules，但是默认的查询表单 rules 是不生效的。需要配置 ignoreRules | (form,config)=>formItemProps \| formItemProps | -
-- | -- | -- | --




 那你配置这个是true吧。

**Comment by codering** [comment]
ignoreRules 应该配置在哪里？ 文档上并没有具体介绍，也没有demo。。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/blob/259f237c89986d7b76c7f076f57a420a0fed738a/packages/table/src/demos/open-rules.tsx#L130

看这个demo

**Comment by codering** [comment]
我试过了， 不生效，好像是bug。 
```
@ant-design/pro-table@2.63.5
@ant-design/pro-form@1.53.5

```

**Comment by chenshuai2144** [comment]
测试用例没问题，你搞个重现试试

**Comment by codering** [comment]
https://codesandbox.io/s/bi-tian-de-cha-xun-biao-dan-forked-g5isy8?file=/App.tsx

这是官网上的demo，搜索框一直是必填
```
form={{
        ignoreRules: true
 }}
```

**Comment by chenshuai2144** [comment]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/8186664/154603544-87a1ff3e-f8c7-437a-9206-8c1772f88ecc.png">
