### ISSUE TITLE
🧐[问题] 'FieldContext' is not exported from 'rc-field-form' (imported as 'RcFieldContext').

### ISSUE THREAD

**Issue by qq969409112** [ant-design/pro-components#4636]
"@ant-design/pro-form": "^1.52.14",
    "@ant-design/pro-table": "^2.63.0",
 无法引入@ant-design/pro-table  [提示]
Failed to compile.

./node_modules/@ant-design/pro-table/node_modules/@ant-design/pro-form/es/BaseForm/createField.js
Attempted import error: 'FieldContext' is not exported from 'rc-field-form' (imported as 'RcFieldContext').

**Comment by qq969409112** [comment]
请问该怎么办呢

**Comment by chenshuai2144** [comment]
升级一下 antd 的版本。
保证 rc-field-form 是高版本

**Comment by qq969409112** [comment]
> 升级一下 antd 的版本。 保证 rc-field-form 是高版本

感谢
