### ISSUE TITLE
ProTable表格组件，搜索表单是日期区间选择时，可以限制日期选择范围吗？

### ISSUE THREAD

**Issue by maqian-haha** [ant-design/pro-components#4637]
ProTable表格组件，当valueType: 'dateRange'时，搜索表单是日期区间选择时，可以限制日期区间选择范围吗？比如选择不超过7天的范围。

**Comment by chenshuai2144** [comment]
https://ant.design/components/date-picker-cn/#components-date-picker-demo-disabled-date

可用 disabledDate 和 disabledTime 分别禁止选择部分日期和时间，其中 disabledTime 需要和 showTime 一起使用。
