### ISSUE TITLE
🐛[BUG] ProFormDigitRange 设置 width 不生效

### ISSUE THREAD

**Issue by BeDay** [ant-design/pro-components#4638]
<ProFormDigitRange
          name="range"
          //style={{width:'200px'}}
          width="xs"
          label="范围"
        />
使用 ProFormDigitRange 设置 width 无效果

**Comment by chenshuai2144** [comment]
ProFormDigitRange 不支持的，你试试filedProps 吧

**Comment by topb25** [comment]
I have the same problem

**Comment by BeDay** [comment]
> filedProps



> ProFormDigitRange 不支持的，你试试filedProps 吧

fieldProps={{ width: "xs" }} 一样无效，自己在外面套了个 div 设置宽度这个可以

**Comment by chenshuai2144** [comment]
那估计没有实现这个功能了，我看看怎么支持以下

**Comment by chenshuai2144** [comment]
range 的都不好搞这个，加个 div  手动设置下吧
