### ISSUE TITLE
👑 [需求]ProTable的form表单能不能配置可筛选项，像table中可以筛选列一样

### ISSUE THREAD

**Issue by 1040961807** [ant-design/pro-components#4641]
### 🥰 需求描述
ProTable组件
form表单项也非常的多，需要像table支持的筛选列一样，同样支持表单项目的筛选；
search区域的form收起时，展示的表单项是固定的，或者可以配置form收起时默认展示的表单项？

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/44770447/154034248-5cac1467-ffbc-40ed-94ac-4ac838b3879a.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，感谢您对ProTable组件的使用。针对您提出的需求，目前ProTable还没有对form表单项进行可筛选配置的功能。不过我们可以尝试通过如下方法来达到您的需求：

1. 在search区域的form表单项中添加Select组件，当用户选择某一项时，使用ProTable的onRequest方法重新请求数据；

2. 在table的columns中添加筛选表头，通过设置筛选项的数据源来实现筛选。例如：

```
import { Table } from "antd";

const columns = [
  {
    title: "姓名",
    dataIndex: "name",

    // 添加下拉框筛选
    filters: [
      { text: "张三", value: "张三" },
      { text: "李四", value: "李四" },
    ],
    onFilter: (value, record) => record.name.indexOf(value) === 0,
  },
  {
    title: "年龄",
    dataIndex: "age",
    // 添加下拉框筛选
    filters: [
      { text: "20岁", value: 20 },
      { text: "30岁", value: 30 },
      { text: "40岁", value: 40 },
    ],
    onFilter: (value, record) => record.age === value,
  },
];

// 数据源，用于渲染表格数据
const dataSource = [
  { key: "1", name: "张三", age: 20 },
  { key: "2", name: "李四", age: 30 },
  { key: "3", name: "王五", age: 40 },
];

function App() {
  return <Table columns={columns} dataSource={dataSource} />;
}
```

针对form表单项的收起展示，可以使用antd的CollapsePanel组件或ProForm组件实现。通过设置defaultActiveKey或者collapsedProps属性来控制表单项的展示或者隐藏，具体使用方式可以查看官方文档。

希望以上内容能够帮到您。如果还有其他问题，欢迎继续询问。

**Comment by chenshuai2144** [comment]
这样表单太多会卡死的，不是个好主意
