### ISSUE TITLE
🧐[问题]table 工具栏如何修改图标为文字

### ISSUE THREAD

**Issue by 1040961807** [ant-design/pro-components#4642]
### 🧐 问题描述
table工具栏三个按钮（刷新、密度、列设置）是固定的按钮，能不能自定义文字或者ReactNode

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/44770447/154035098-6834e388-0c28-4f56-afb2-df2df59d76e6.png)

**Comment by chenshuai2144** [comment]
options | table 工具栏，设为 false 时不显示 | {{ fullScreen: boolean \| function, reload: boolean \| function,setting: true, density?: boolean }} | { fullScreen: false, reload:true, setting: true}
-- | -- | -- | --




只能不显示，不支持自定义dom，只支持自定义行为。
