### ISSUE TITLE
👑 [需求]复杂下拉列表选择组件

### ISSUE THREAD

**Issue by zwjsoft** [ant-design/pro-components#4643]
### 🥰 需求描述

ProFormSelect的下拉内容比较简单，就1列文本，有没有更加复杂的列表显示，类似表格显示，有表头和列表内容，例如我们选择一个物料，可以显示编码、名称、规格型号、供应商、当前库存等多维信息。

入下图的模式：
![image](https://user-images.githubusercontent.com/35764692/154076714-270d4157-3a83-471e-9111-375c0cfcdaab.png)

**Comment by hjqlc** [comment]
可以参考这个例子改造，ProFormSelect的dropdownRender渲染一个table，ProFormSelect和Select的事件需要用table的覆盖掉https://ant.design/components/select-cn/#components-select-demo-custom-dropdown-menu
