### ISSUE TITLE
是否应该避开使用开umijs？

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#4646]
我的应用是原来建立在umijs基础上。
umijs提供的功能基本就是菜单系统。其他的，例如api 调用，价值不大。
感觉umijs 菜单系统也有很多限制。例如，根据API数据再确定动态菜单，这些没法实现。
是否应该避开开umijs，直接使用react？

大侠们给个意见？

**Comment by chenshuai2144** [comment]
`API数据再确定动态菜单，这些没法实现。`

这个能实现的吧。你可以自己写插件，插件的api效果比较强。

**Comment by gaohongwei** [comment]
在react APP里面，值得使用umijs吗？

**Comment by chenshuai2144** [comment]
那没必要，umi 和 cra 不好混用
