### ISSUE TITLE
👑 [需求]多种表单类型

### ISSUE THREAD

**Issue by Venus-WXP** [ant-design/pro-components#465]
### 🥰 需求描述

ProTable的Form模式增加表单类型，常见的表单分类有：添加表单和更新表单。一个常见的需求就是一个功能的某些字段只在添加表单中展示而更新表单则不显示或显示禁用状态，反之有些字段只有更新表单才需要。那么现有ProTable控制的表单是清一色的单一类型，如果用作添加表单，那么更新表单就要创建不一样的columns列信息传入更新表单的ProTable组件。这样虽能解决问题，但是无法共用一个columns列定义，我的想法是尽可能的，表格、添加表单、更新表单、详情(ProDescriptions)都共用一个columns的定义，这样一个功能的CRUD就可以做到非常的简洁了。请问有什么好的法子吗？

### 🧐 解决方案

暂时，针对不同的表单重复定义columns列信息。

### 🚑 其他信息

无

**Comment by itsuki0927** [comment]
请写好标题

**Comment by chenshuai2144** [comment]
ProForm 支持了 readonly，你可以自由切换是否只读了

**Comment by BooYeu** [comment]
readonly的内容不提交到表单，这个可以实现吗？

**Comment by BooYeu** [comment]
因为点击编辑后，有的内容是不能修改的还是保持readonly属性，但是为了保持样式一致，还是用的proformtext组件

**Comment by BooYeu** [comment]
去除name属性后，initialValue的内容又无效了
