### ISSUE TITLE
🐛[BUG] 页面上多个ProTable存在同名的SelectColumn只触发了一个request

### ISSUE THREAD

**Issue by walker27** [ant-design/pro-components#4650]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
页面上存在两个ProTable同时具有相同dataIndex的valueType为‘select'的column时，其request只触发了其中一个,
用column.key虽然可以避开这个问题，但是同时也会改变search的查询字段名

### 💻 复现代码

https://codesandbox.io/s/cha-xun-biao-ge-forked-03t2vu?file=/App.tsx

### © 版本信息

- @ant-design/pro-table @ 2.63.6

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/6702568/154226867-973a3013-b895-4cb4-abfb-c7e6933832f6.png)
上图中enumRequest2没有被触发

**Comment by walker27** [comment]
在sandbox上逐个版本检测pro-table@2.59.5是好的，pro-table@2.59.6就有这个问题了

**Comment by chenshuai2144** [comment]
每个加个不同的params的，这个是故意这么做的，防止每行都重复发
