### ISSUE TITLE
🐛[BUG] protable search labelWidth:0 不生效

### ISSUE THREAD

**Issue by nanianlisao** [ant-design/pro-components#4651]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

protable组件中 search配置了labelWidth:0 但是还是按照 labelWidth:80来渲染的

<img width="795" alt="image" src="https://user-images.githubusercontent.com/22850210/154227199-c3571a50-6245-4e45-b295-3ddc691b2452.png">

### 📷 复现步骤

在线链接  https://codesandbox.io/s/tong-guo-formref-lai-cao-zuo-cha-xun-biao-dan-forked-xq4tfl?file=/App.tsx

### 🏞 期望结果

希望是这样的  
<img width="790" alt="image" src="https://user-images.githubusercontent.com/22850210/154227292-730ac8ba-c7df-46e5-9f98-f02f96f45179.png">

### 💻 复现代码

```javascript
import React, { useRef, useState } from "react";
import { Button } from "antd";
import type { ProColumns } from "@ant-design/pro-table";
import ProTable from "@ant-design/pro-table";

export type TableListItem = {
  key: number;
  name: string;
};

const columns: ProColumns<TableListItem>[] = [
  {
    title: "标题",
    dataIndex: "name",
    key: "name",
    fieldProps: {
      placeholder: "请输入标题"
    }
  },
  {
    title: "创建时间",
    key: "since",
    dataIndex: "createdAt",
    valueType: "dateTime",
    fieldProps: {
      placeholder: "请选择创建时间"
    }
  }
];

export default () => {
  return (
    <ProTable<TableListItem>
      columns={columns}
      request={() =>
        Promise.resolve({
          data: [
            {
              key: 1,
              name: `TradeCode ${1}`,
              createdAt: 1602572994055
            }
          ],
          success: true
        })
      }
      rowKey="key"
      search={{
        labelWidth: 0
      }}
      toolBarRender={false}
      options={false}
      headerTitle="表单赋值"
    />
  );
};

```

### © 版本信息

 "@ant-design/pro-table": "2.63.6",
    "antd": "4.18.6",
    "react": ">=16.9.0",
    "react-dom": ">=16.9.0"
- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
labelWidth 不能设置为 0 的， 0 会当成不设置。要是想不展示，直接 display 掉呗

**Comment by nanianlisao** [comment]
> 

有具体的配置项吗  不太希望通过classname去控制

**Comment by chenshuai2144** [comment]
没有的，一般不会有人设置这个东西的。

**Comment by nanianlisao** [comment]
> 没有的，一般不会有人设置这个东西的。

感觉这种ui还是挺常见的  之前我是通过 formItemProps 甚至 renderFormItem去实现的 但是整个成本太大了·· 希望配置能更全面一点 兼顾到这种使用场景

**Comment by chenshuai2144** [comment]
> 感觉这种ui还是挺常见的 之前我是通过 formItemProps 甚至 renderFormItem去实现的 但是整个成本太大了·· 希望配置能更全面一点 兼顾到这种使用场景


我们希望每个页面千篇一律，不想要特殊的样式。而且也维护不动
