### ISSUE TITLE
🧐[问题] 使用pro-layout组件,设置menu={{ locale: false }}打包之后国际化翻译多余

### ISSUE THREAD

**Issue by ybf970928** [ant-design/pro-components#4652]
### 🧐 问题描述
项目当中并没有使用到国际化, 所以设置locale: false.
所以我打包出来的这些翻译是哪儿来的

### 💻 示例代码
```ts
import { BasicLayout } from '@ant-design/pro-layout';
<BasicLayout
      title="123"
      logo={() => null}
      rightContentRender={() => <GlobalHeaderRight />}
      menu={{ locale: false, request: async () => menuDataRender(defaultRouters) }}
      menuItemRender={(menuItemProps, defaultDom) => {
        if (!menuItemProps.path || location.pathname === menuItemProps.path) {
          return defaultDom;
        }
        return <Link to={menuItemProps.path}>{defaultDom}</Link>;
      }}
    >
      {children}
</BasicLayout>
```
### 🚑 其他信息

<img width="824" alt="image" src="https://user-images.githubusercontent.com/63764959/154238367-94dcdfda-164c-454b-968c-465d9208a62e.png">

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/63764959/154238192-39fa40db-b6c9-4f06-b9cf-82f1dcbee26d.png">

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/63764959/154237646-b32bcbe1-7ec2-439c-b5c7-7ff75c5965b3.png">

**Comment by chenshuai2144** [comment]
这是组件库自带的， locale= false 只会关掉 moment 和 你系统里面自带的。


组件库自带的因为太小了，所以也没做 treeshaking
