### ISSUE TITLE
🐛[BUG]protable在宽度超长加了scroll的时候cell与表头对不齐

### ISSUE THREAD

**Issue by Zhangbu** [ant-design/pro-components#4655]
### 🐛 bug 描述
protable在宽度超长加了scroll的时候cell边框与表头对不齐

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- "antd": "^4.18.6",
-  "umi": "^3.5.20",
- "@ant-design/pro-table": "2.56.2",
- 浏览器环境
- chrome 版本 98.0.4758.80
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

https://s4.ax1x.com/2022/02/17/H4OXex.jpg

**Comment by chenshuai2144** [comment]
留一列用来自适应，不要每一列都设置死宽度，不然这种情况很容出现。
