### ISSUE TITLE
🐛[BUG]ProTable 疑惑

### ISSUE THREAD

**Issue by RoyKwok94** [ant-design/pro-components#4656]
问题 ：
ProTable （表格） 里参数 columns
其中一个参数是：
    {
      title: '时间',
      dataIndex: 'date',
      align: 'center',
      valueType: 'select',   //是个select形式
      fieldProps: {
        options: timeArray,   //  请求的数据 ，是一个数组集合
        value: timeArray[0].value,  // 默认第一项
      },
}
-------------------表格组件 -----
<ProTable columns={columns}   
request={(params)=>{
console.log(params) //这时候的params里没有date参数
}}
/>
-------------------表格组件 -----
求解决方法，我的数据是请求回来，默认第一个数据作为筛选条件，在表格中的params里并没有这个参数，文档中fieldProps.options较少，请指导

**Comment by chenshuai2144** [comment]
有个参数叫 initialvalues 我们不支持使用value 赋值的。
