### ISSUE TITLE
🐛[BUG] valueType设置为digit后配置renderText表格出现NaN

### ISSUE THREAD

**Issue by beeant0512** [ant-design/pro-components#466]
### 📷 复现步骤
columns=[
{
...，
valueType： 'digit'，
renderText： text = ` ${text} 天`
}
]

### 🏞 期望结果

显示 **天 而不是NaN
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by itsuki0927** [comment]
因为内部格式化的时候是使用`Number(text)`, 在你的示例中等同于`Number(`xxx天`)`, 所以就是NaN.

你是希望在搜索表单中展示<inputNumber/>, 而且在Table中展示`xxx天`嘛?

**Comment by chenshuai2144** [comment]
@beeant0512  直接用 render 就能用了
