### ISSUE TITLE
🐛[BUG] FooterToolbar 组件样式问题

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#4660]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/30397655/154595517-fdbf8c73-c8bc-49bf-8729-2c69b773c11f.png">

FooterToolbar 组件样式问题

**Comment by leshalv** [comment]
https://preview.pro.ant.design/form/advanced-form

**Comment by kiner-tang** [comment]
请详细清楚的描述问题

**Comment by leshalv** [comment]
感觉 FooterToolbar 应该和 Layout 下面高度一致更好看一些？
<img width="493" alt="image" src="https://user-images.githubusercontent.com/30397655/154876346-55c302b1-50c7-4f88-863d-c76a8c5d7f1c.png">

**Comment by chenshuai2144** [comment]
不好保证的，等新版本的layout把
