### ISSUE TITLE
🐛[BUG] selections设置Table.SELECTION_ALL， 跨页全选忽略了checkbox的状态

### ISSUE THREAD

**Issue by meyerlee** [ant-design/pro-components#467]
### 🐛 bug 描述
表格选择时，使用了跨页的全选菜单，这个功能没有看getCheckboxProps().disabled。

### 🏞 期望结果
选择时应该check行状态

### 💻 复现代码
  {
    selections: [Table.SELECTION_ALL, Table.SELECTION_INVERT],
    getCheckboxProps: () => ({
      disabled: true,
    }),
  } 

### © 版本信息

- ProTable 版本: [e.g. 2.4.4  2.7.2]
- umi 版本 3.2.16
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![checkall](https://user-images.githubusercontent.com/8414971/92871712-cb55d500-f437-11ea-8f75-9db94adc0ae3.png)

**Comment by chenshuai2144** [comment]
看起来是 antd 问题， 去 antd 提？

**Comment by meyerlee** [comment]
🆗！
