### ISSUE TITLE
👑 [需求]params改变page.current不重置?我想不到不重置的场景，望告知

### ISSUE THREAD

**Issue by zuosamu** [ant-design/pro-components#4672]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by kiner-tang** [comment]
哪个组件，什么场景没有重置呢？请提供可复现的代码。https://codesandbox.io/

**Comment by chenshuai2144** [comment]
已经修改了


![image](https://user-images.githubusercontent.com/8186664/155078408-b6e2247f-06de-4868-befe-4517bbcad802.png)
