### ISSUE TITLE
🐛[BUG] ModalForm和DrawerForm会有多余的提交和重置按钮一闪而过

### ISSUE THREAD

**Issue by gehaijun** [ant-design/pro-components#4677]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤

官方文档里就看看到
https://procomponents.ant.design/components/form/#%E4%BD%95%E6%97%B6%E4%BD%BF%E7%94%A8-proform
DrawerForm一打开就会在表单里出现多余的按钮闪一下，ModalForm也是

![image](https://user-images.githubusercontent.com/35563401/154898134-36f2cb36-ea33-45a8-ad75-b97504da90f3.png)
![image](https://user-images.githubusercontent.com/35563401/154898306-1be6e851-e5d5-4b77-b9c6-d9171a4b483e.png)

**Comment by leshalv** [comment]
我也发现了这个BUG

**Comment by leshalv** [comment]
@chenshuai2144

**Comment by kiner-tang** [comment]
看情况是刚开始`footerRef`的元素还没有被挂载的时候会先在内容区渲染一下按钮
