### ISSUE TITLE
🧐[问题]Prolayout左边菜单栏折叠面板保持全部打开 defaultOpenAll为true但不能保持打开

### ISSUE THREAD

**Issue by CiciIvory** [ant-design/pro-components#468]
### 🧐 问题描述

使用Prolayout
想要左边的菜单折叠面板保持全部打开状态
但是 现在初始化的时候可以全部打开
点击第二次的时候就又关闭了

使用的是
` menu:{defaultOpenAll:true}`

想知道是使用上有问题还是 暂时无法满足这个场景

### 🚑 如下

![20200911_142431](https://user-images.githubusercontent.com/40973214/92874487-a9118680-f43a-11ea-87c9-676bc7c21275.gif)

代码设置如下

![微信图片_20200911142748](https://user-images.githubusercontent.com/40973214/92874901-09a0c380-f43b-11ea-8b30-97255d5e5495.png)

**Comment by chenshuai2144** [comment]
是这么设计的 所以叫 defaultOpenAll,,而不是叫openAll

**Comment by CiciIvory** [comment]
> 是这么设计的 所以叫 defaultOpenAll,,而不是叫openAll

已经找到对应属性
openkeys:false
