### ISSUE TITLE
🐛[BUG] 设置列状态之后默认的fixed被清空

### ISSUE THREAD

**Issue by JS-an** [ant-design/pro-components#4691]
### 🐛 bug 描述
设置列状态之后默认的fixed被清空,详情如图;

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/25688878/155076937-fc11500e-c91f-45bd-9635-a0cf5f7d9e6e.png)
![image](https://user-images.githubusercontent.com/25688878/155077037-3327507c-81cf-4dd7-9ba0-ed2e9ffe4665.png)

### 🏞 期望结果

不清空默认fixed;

### 💻 复现代码

官网上的例子

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，根据你提供的信息，这个问题可能与 antd 的 Table 组件的 bug 有关。这个 bug 可以通过手动设置 `fixed` 属性的值来解决。

以下代码演示了如何在使用 column 配置时手动设置 `fixed` 属性的值：

```js
import React from 'react';
import { Table } from 'antd';

const columns = [
  { title: 'Name', dataIndex: 'name', key: 'name' },
  { title: 'Age', dataIndex: 'age', key: 'age', fixed: 'left' },
  { title: 'Address', dataIndex: 'address', key: 'address', fixed: 'left' },
  // ...
];

const TableComponent = () => {
  return (
    <Table
      columns={columns.map((col) => ({ ...col, fixed: col.fixed || 'right' }))}
      // ...
    />
  );
};

export default TableComponent;
```

详细文档请参考 antd 的官方文档：[Table - Fixed columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)。

**Comment by chenshuai2144** [comment]
已经修复了重新试试

**Comment by JS-an** [comment]
> 已经修复了重新试试

完美解决🎉 谢谢🤞
