### ISSUE TITLE
🧐[问题]Form中使用EditableProTable时，colunms中的formItemProps和fieldProps无法使用函数式配置

### ISSUE THREAD

**Issue by zjb19970804** [ant-design/pro-components#4696]
### 🧐 问题描述
需求是我需要根据table的name来取值赋值，给table设置name和editable后，问题出现

查看[源码](https://github.com/ant-design/pro-components/blob/master/packages/table/src/Table.tsx#L217)发现下面的判断导致无法渲染table包裹的form，导致在utils包中的方法[getFieldPropsOrFormItemProps](https://github.com/ant-design/pro-components/blob/master/packages/utils/src/getFieldPropsOrFormItemProps/index.tsx#L18)无法执行函数，请问这里的name判断是有其他原因吗？

### 💻 示例代码
官网的示例，formItemProps无效：
https://procomponents.ant.design/components/editable-table#%E4%B8%8E-formitem-%E9%85%8D%E5%90%88

### 🚑 其他信息
ProTable源码
![image](https://user-images.githubusercontent.com/37135411/155095035-5b44c12f-d4c9-421b-8fe7-933ed434fef3.png)

**Comment by chenshuai2144** [comment]
你在外面放个 ProForm 呢？

**Comment by zjb19970804** [comment]
> 

放了没用呀，官网示例不就是放了个ProFrom在外面吗

**Comment by zjb19970804** [comment]
> 你在外面放个 ProForm 呢？

放了没用呀，官网示例不就是放了个ProFrom在外面吗

**Comment by zjb19970804** [comment]
我的理解是去掉name的判断，或者在TableRender组件中加上
```typescript
useEffect(() => {
  counter.setEditorTableForm(form);
}, [props.form])
```
使EditTable中的form有值

**Comment by chenshuai2144** [comment]
来个pr吧。
