### ISSUE TITLE
🧐[问题]ProTable有没有一条数据的时候，可以铺满容器

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#4697]
如图所示，一条数据的时候，这个样子有点丑···有没有哪个配置可以让它默认铺满容器
![image](https://user-images.githubusercontent.com/12421552/155102250-7f438a77-efba-40bd-91b4-e60294e724cd.png)

**Comment by chenshuai2144** [comment]
让设计师换个设计吧，数据多了超出去也不好看
