### ISSUE TITLE
🐛[BUG] ProFormTreeSelect 样式问题

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#4699]
分布式表单，不同步骤，同样的布局策略，ProFormTreeSelect 和输入框等组件同事使用时，样式是可以撑开争取的，单独只有一个ProFormTeeSelect时候，样式不能撑开

<img width="784" alt="image" src="https://user-images.githubusercontent.com/30397655/155131258-78c3cfde-022c-42c8-bcdc-836d8bc54cd5.png">

<img width="550" alt="image" src="https://user-images.githubusercontent.com/30397655/155131232-7a421205-af30-4220-bad4-15f62dcf4413.png">

**Comment by leshalv** [comment]
@1247748612

**Comment by chenshuai2144** [comment]
默认都是不撑开的，你手动设置下width？
