### ISSUE TITLE
🐛[BUG] #4668 pro-descriptions的复制和省略问题修复后似乎依然无效

### ISSUE THREAD

**Issue by a97077088** [ant-design/pro-components#4703]
更新到最新版，看起来问题仍然没有解决
问题1: 省略号
问题2: 可复制的
问题3: 可穿到效果的标签上的问题类型={"datetime"}
@ant-design/pro-descriptions": "1.10.45",

### © 版本信息

- ProComponents 版本: [e.g. 1.10.45]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

#4668

**Comment by chenshuai2144** [comment]
还没发
