### ISSUE TITLE
🧐[问题]请问下umi使用ProLayout自定义混合菜单栏有demo吗？headerRender具体怎么使用啊

### ISSUE THREAD

**Issue by nicolelei** [ant-design/pro-components#4706]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
看看代码 帮忙搞个demo？

现在还没有这样的场景
