### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by decadez** [ant-design/pro-components#4707]
### 🧐 问题描述
使用renderFormItem自定义了表单的某一搜索项
传入初始值为Moment[] 类型，但搜索组件接收到的却是String[]类型
这直接导致了组件内momentjs报错

### 💻 示例代码
```
  {
      initialValue: [moment(new Date()).add(-7, 'day'), moment(new Date())],
      dataIndex: 'time',
      renderFormItem: (item,{ type, defaultRender, formItemProps, fieldProps, ...rest }, form) => {
         console.log(item);
         return <RangePicker placeholder={['开始时间', '结束时间']} />
      },
  },
```

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/49861866/155272490-e61cfdf3-e478-4f02-ad61-577d369845c4.png)
![image](https://user-images.githubusercontent.com/49861866/155272729-a3aa6fba-fe79-4396-b624-cb3244a120f5.png)

**Comment by yuanAIhan** [comment]
所以这个问题并没有答案，结果也直接关闭了吗？
