### ISSUE TITLE
🧐[问题] ProFormSelect options必须要有label属性？不能通过fieldNames自定义吗？

### ISSUE THREAD

**Issue by cxn123** [ant-design/pro-components#4709]
### 🧐 问题描述
ProFormSelect options必须要有label属性？不能通过fieldNames自定义吗？ts中options没有label属性会报错

![image](https://user-images.githubusercontent.com/26789701/155289459-51a5c161-70a0-4f98-a2d5-70168d9c520e.png)

**Comment by 1247748612** [comment]
升级最新版本是支持的
