### ISSUE TITLE
🧐[问题]ProTable onFilter 的执行次数是不是有些多了。

### ISSUE THREAD

**Issue by meyerlee** [ant-design/pro-components#471]
### 🧐 问题描述
设置了 onFilter方法，一次数据过滤，试了两个版本。
V2.4.4  执行了7遍 （对每一行数据都执行了7次哦， 100条数据就需要执行700次）
V2.7.2  执行了5遍

    onFilter: (value: string | number | boolean, record: any): boolean => {      
      console.debug('enum filter', value);
      return true;
    },

### 🚑 其他信息
我这里是39条数据， 2.4.4版本跑出来的信息。

![filter](https://user-images.githubusercontent.com/8414971/92880789-f133a780-f440-11ea-9e05-82123279b32f.png)

**Comment by chenshuai2144** [comment]
现在已经减少了 render 了
