### ISSUE TITLE
🐛[BUG]分页器的showSizeChanger不生效

### ISSUE THREAD

**Issue by WT-Road** [ant-design/pro-components#4711]
### 🐛 bug 描述

"自 4.1.0 起，Pagination 在 total 大于 50 条时会默认显示 size 切换器以提升用户交互体验。如果你不需要该功能，可以通过设置 showSizeChanger 为 false 来关闭。"
在使用ProTable时,发现小于50条时也显示size 切换器,设置showSizeChanger为true还是显示

### 📷 复现步骤

`<ProTable
        ...
        pagination={{
          showSizeChanger: true, //小于50条还是出现size 切换器
        }}
      />`

### 🏞 期望结果

Pagination 在 total 小于 50 条时隐藏size 切换器

### 💻 复现代码

[官网示例-dateFormatter - 日期格式化](https://codesandbox.io/s/ri-qi-ge-shi-hua-forked-1iswit?file=/App.tsx)

### © 版本信息

- ProComponents 版本: [e.g. 2.64.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kiner-tang** [comment]
不想显示应该设置为`showSizeChanger: false`吧

**Comment by WT-Road** [comment]
> 不想显示应该设置为`showSizeChanger: false`吧

自 4.1.0 起Antd的table是不需要设置showSizeChanger, 默认大于50条才显示size 切换器,所以想保持一致,现在使用ProTable无论设置与否,都会出现 size 切换器
