### ISSUE TITLE
🐛[BUG]DrawerForm确认后，清空部分表单字段，导致提交失败

### ISSUE THREAD

**Issue by charminghiker** [ant-design/pro-components#4713]
### 🐛 bug 描述

DrawerForm点击确认后，会清空部分表单字段，导致提交失败。
![image](https://user-images.githubusercontent.com/34738577/155437939-a3f005af-9af7-48c4-bc1c-5547035ae94a.png)

### 📷 复现步骤

`@ant-design/pro-form`使用`1.54.0`，其他保持最新，就会出现此问题。
`1.53.7`就没有问题。

### 🏞 期望结果

不清空字段，提交成功。

### © 版本信息

```js
    "@ant-design/pro-descriptions": "^1.10.45",
    "@ant-design/pro-form": "^1.54.0",
    "@ant-design/pro-layout": "^6.32.14",
    "@ant-design/pro-table": "^2.63.7",
    "@umijs/route-utils": "^1.0.37",
    "antd": "^4.18.8",
    "umi": "3.5.18",
```
- 浏览器环境：Firefox、Chrome
- 开发环境 ：MacBook、Win10

**Comment by 1247748612** [comment]
在最新版本中正常，1.57.0
