### ISSUE TITLE
🧐[问题] ProList size 现在还没有支持吗？我调整使用size三个属性，看样式没有具体变化呢？

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#4718]

**Comment by leshalv** [comment]
https://procomponents.ant.design/components/list#%E5%A4%A7%E5%B0%8F%E5%92%8C%E5%88%86%E5%89%B2%E7%BA%BF @chenshuai2144

**Comment by chenshuai2144** [comment]
一直都不好用把，没有支持过这个API

**Comment by leshalv** [comment]
> 一直都不好用把，没有支持过这个API

<img width="930" alt="image" src="https://user-images.githubusercontent.com/30397655/165017448-4c087567-588c-4968-ab5d-01d1636aa74b.png">
官网ProList突然这样了...

**Comment by chenshuai2144** [comment]
dumi的锅，等他修复一下
