### ISSUE TITLE
👑 [需求] ProList Card 布局时，Title 文本过长自动缩略

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#4719]

**Comment by leshalv** [comment]
<img width="349" alt="image" src="https://user-images.githubusercontent.com/30397655/155474095-20523496-6e0c-4404-9281-5143cf33417a.png">
展示效果更好

**Comment by DerrickTel** [comment]
title 和 subTitle都是ReactNode不太好加自动省略，可以自己传一个进去呀。（不过文档确实没有体现。）
然后avatar的bug不是更应该关注吗？。。。直接被挤没了可还行，一起改了好了。
