### ISSUE TITLE
🧐[问题] 上传组件如何控制在上传达到某个数量后隐藏上传按钮呢? 

### ISSUE THREAD

**Issue by HengCC** [ant-design/pro-components#472]
### 🧐 问题描述

 上传组件如何控制在上传达到某个数量后隐藏上传按钮呢? ant.design中的是直接通过隐藏props.children的渲染内容来做的. 
如果用ProFormUploadButton该如何实现呢? 我按照原生upload那样的写法似乎不太行.现在只能判定上传的filelist长度去做控制和提示. 没法隐藏上传的按钮.

**Comment by lsabella** [comment]
好像还是没有解决

**Comment by WuJiY** [comment]
picture-card 没有用

**Comment by WuJiY** [comment]
> picture-card 没有用

不好意思 我的错。fileList 应该写的fieldProps 里就可以了，我写外层了。。。
