### ISSUE TITLE
🐛[BUG] Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.     at ProDescriptions

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#4721]
<img width="417" alt="image" src="https://user-images.githubusercontent.com/30397655/155537596-fa5174f7-6688-4503-9b81-3bd04f4e044e.png">

**Comment by chenshuai2144** [comment]
看一下是不是组件写在了还触发了 setState

**Comment by soeasyjx** [comment]
我也遇到 了这个问题，有解决了么，现在，还是直接无视了

**Comment by gaollard** [comment]
我也遇到 了这个问题，有解决了么，现在，还是直接无视了

**Comment by shiwofeiwo** [comment]
我也遇到 了这个问题，有解决了么，现在，还是直接无视了

**Comment by jiazez** [comment]
![image](https://github.com/ant-design/pro-components/assets/51707274/6eedbdbd-ce4b-4403-9e40-0714f42eefa1)
