### ISSUE TITLE
👑 [需求] ProForm和SchemaForm提供栅格布局

### ISSUE THREAD

**Issue by hejinguo** [ant-design/pro-components#4723]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

ProForm
SchemaForm

### 🥰 需求描述

目前ProForm和SchemaForm提供有width进行表单项宽度设置，但无法根据屏幕大小进行栅格自适应

### ⛰ 功能需求适用场景

通常需要根据屏幕自适应栅格化布局

### 🧐 解决方案

建议提供width 的 span属性进行栅格化布局

**Comment by hejinguo** [comment]
提供colSize支持也行

**Comment by 1247748612** [comment]
不是有吗？

![image](https://user-images.githubusercontent.com/29533304/157835401-b17915b0-a1be-4e52-b464-0070f762388d.png)

**Comment by hejinguo** [comment]
> 不是有吗？
> 
> ![image](https://user-images.githubusercontent.com/29533304/157835401-b17915b0-a1be-4e52-b464-0070f762388d.png)

width 根据枚举目前宽度是定死的，不能像栅格一样自适应屏幕。
如果设置width:xs，宽度就是104px。

XS=104px 适用于短数字、短文本或选项。
SM=216px 适用于较短字段录入、如姓名、电话、ID 等。
MD=328px 标准宽度，适用于大部分字段长度。
LG=440px 适用于较长字段录入，如长网址、标签组、文件路径等。
XL=552px 适用于长文本录入，如长链接、描述、备注等，通常搭配自适应多行输入框或定高文本域使用。

**Comment by 1247748612** [comment]
一直没注意到这个，确实可以支持下的，但感觉改起来会造成不少的breaking change

**Comment by hejinguo** [comment]
> 一直没注意到这个，确实可以支持下的，但感觉改起来会造成不少的breaking change

退而求其次，若能有像ProTable、QueryFilter中的colSize参数配置出表单栅格达到自适应，感觉已能满足日常使用

**Comment by 1247748612** [comment]
> 退而求其次，若能有像ProTable、QueryFilter中的colSize参数配置出表单栅格达到自适应，感觉已能满足日常使用

有空我尝试下

**Comment by Loomark** [comment]
盯一个
