### ISSUE TITLE
🧐[问题] ProTable不支持ConfigProvider自定义空状态吗？

### ISSUE THREAD

**Issue by HejieShao** [ant-design/pro-components#4724]
我用ConfigProvider包裹ProTable，自定义空组件，ProTable的数据为空的样式并没有改成自定义的。
如果我想要修改ProTable的空样式，要怎么做呢
`<ConfigProvider locale={zh_CN} renderEmpty={() => <CustomEmpty/>}>
<ProTable />
</ConfigProvider>`

**Comment by chenshuai2144** [comment]
<html>
<body>


locale | 默认文案设置，目前包括排序、过滤、空数据文案 | object | 默认值
-- | -- | -- | --



</body>
</html>locale	默认文案设置，目前包括排序、过滤、空数据文案	object	[默认值](https://github.com/ant-design/ant-design/blob/6dae4a7e18ad1ba193aedd5ab6867e1d823e2aa4/components/locale/zh_CN.tsx#L20-L37)

table 要用这个，

**Comment by HejieShao** [comment]
这个只是改文案，我想要改图标呢？

**Comment by HejieShao** [comment]
这个只是改文案，我想要改图标呢？

**Comment by chenshuai2144** [comment]
看看 antd table 更换的demo。

**Comment by lihao6666** [comment]
> 

antd table 使用ConfigProvider是ok的啊，但是protable就不行

**Comment by HejieShao** [comment]
是的，Protable就没办法更换图标

**Comment by yeesunday** [comment]
怎么关闭了，@chenshuai2144 @HejieShao 这个问题后面有解决方案了么
