### ISSUE TITLE
🐛[BUG]启动项目报错：Cannot use import statement outside a module

### ISSUE THREAD

**Issue by sjzpengyuyan** [ant-design/pro-components#4742]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 💻 复现代码

![image](https://user-images.githubusercontent.com/51074402/156126849-aa9e2686-2f88-46d4-81d3-ab036edc03ae.png)

### © 版本信息

-  "@ant-design/pro-form": "^1.53.7",
    "@ant-design/pro-layout": "^6.32.14"
- umi 版本 3.5.20
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/51074402/156127018-de77d3bc-6bf2-4de3-82eb-027846389c70.png)

**Comment by sjzpengyuyan** [comment]
安装ahooks后启动项目报错，然后删除ahooks依然报错，尝试删除node_modules以及yarn.lock后依然报错

**Comment by sjzpengyuyan** [comment]
已解决：删除@ant-design/pro-layout，然后启动，启动成功后再安装@ant-design/pro-layout，具体原因不知道为啥

**Comment by sjzpengyuyan** [comment]
但是再次重新yarn start还是会报错，希望官方看到呀
![image](https://user-images.githubusercontent.com/51074402/156133038-10970bc1-b651-4113-8f6f-757609b37d5d.png)

**Comment by chenshuai2144** [comment]
这个是什么问题？ 没有安装好loader？

**Comment by sjzpengyuyan** [comment]
> 这个是什么问题？ 没有安装好loader？

问题找到了，是因为我在config/layout.tsx中导出了两个函数，可能导致layout组件不知道哪个是主要的布局函数，感谢回复~
