### ISSUE TITLE
🧐[问题]proTable列筛选重置事件是否可以自定义赋值

### ISSUE THREAD

**Issue by Ryang-H** [ant-design/pro-components#4743]
### 🧐 问题描述

1、因为表格列中自己带有默认的筛选值，并且某几列中筛选条件特别多，所以点击筛选条件的重置按钮，不希望清空全部值，想恢复初始的默认值，有相关事件可以控制吗。
2、或者在列筛选中修改重置按钮文本内容，实现全选及反选功能，在使用filterDropdown自定义时，如何只修改事件中选中项赋值，而控件自带的排版，样式，其它事件不受到影响

![image](https://user-images.githubusercontent.com/79308283/156143255-1a5acf9d-437c-430c-bd82-e16b24b7e279.png)

**Comment by 1247748612** [comment]
之前的逻辑有delete确实会引起findIndex < 0的情况，现在不delete了一定存在走不到这里了

![image](https://user-images.githubusercontent.com/29533304/156506387-d597288d-e79e-4a76-bc9d-5c73e46487c2.png)

可以之后再优化一下这里

**Comment by Ryang-H** [comment]
hello,proTable筛选这块是你在维护吗，我想反馈下两个bug，
一个是筛选的时候，设置columns某列filterMode='tree'，然后点击全选，取消下方某项选择数据，这时全选按钮依然为选中状态，重新调用数据接口，该列全选按钮依然为选中状态，而此时并不是所有数据为选中状态。
二是筛选时设置了defaultFilteredValue,点击重置时，应该是恢复默认值，而不是清空所有。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 下午2:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 🧐[问题]proTable列筛选重置事件是否可以自定义赋值 (Issue #4743)





 
之前的逻辑有delete确实会引起findIndex < 0的情况，现在不delete了一定存在走不到这里了
 

 
可以之后再优化一下这里
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1247748612** [comment]
这块是antd实现的，去antd提issue
