### ISSUE TITLE
🧐[问题]ProCard多行卡片，list盒子比包裹卡片大一圈，导致出现滚动条

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#4744]
使用ProCard多行卡片，list盒子比包裹卡片大一圈，导致出现滚动条，导致有一些场景滚动条频繁出现，造成界面抖动。

不知道有没有什么可以临时解决方案，比较急┭┮﹏┭┮

运行环境：
![image](https://user-images.githubusercontent.com/12421552/156159357-f5ce9dd5-5e18-496c-998d-0d5a7c0f1da7.png)

代码：
![image](https://user-images.githubusercontent.com/12421552/156159468-f550853f-9b9d-4b07-93d2-f8d3516ab825.png)

问题：
![image](https://user-images.githubusercontent.com/12421552/156159561-5d199048-f9db-45a7-bcec-496c6c6732b3.png)

![image](https://user-images.githubusercontent.com/12421552/156159756-129e6fe6-40da-4820-8929-b835ad4cdd06.png)

**Comment by edifangyi** [comment]
找到解决方案了，但是没找到这个margin谁加上去的
![image](https://user-images.githubusercontent.com/12421552/156161421-14d99aa6-801e-4963-a243-7edbfe2d6598.png)

![image](https://user-images.githubusercontent.com/12421552/156161600-be0e781c-a8b5-4808-b5d3-308a37dee4ed.png)

**Comment by chenshuai2144** [comment]
30px 看起来是手动加上去的，是不是js里面算出来的。

官方一般都用 24 px
