### ISSUE TITLE
ProTable查询表格为什么在url自带参数🧐[问题]

### ISSUE THREAD

**Issue by suruirui** [ant-design/pro-components#4753]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

http://127.0.0.1/list**?current=1&pageSize=10**
页面使用了ProTable查询表格，路由后面自动带了?current=1&pageSize=10 
麻烦问下从哪儿来的 ？

**Comment by suruirui** [comment]
怎么能去掉

**Comment by 1247748612** [comment]
syncToUrl 置为false

![image](https://user-images.githubusercontent.com/29533304/156321043-4d0e2fd3-2242-47e6-ae1e-0deb4f9fc2fa.png)

**Comment by 1247748612** [comment]
这来的

https://procomponents.ant.design/components/form#%E5%90%8C%E6%AD%A5%E6%8F%90%E4%BA%A4%E7%BB%93%E6%9E%9C%E5%88%B0-url

**Comment by suruirui** [comment]
> 这来的
> 
> https://procomponents.ant.design/components/form#%E5%90%8C%E6%AD%A5%E6%8F%90%E4%BA%A4%E7%BB%93%E6%9E%9C%E5%88%B0-url

不太熟悉这个，谢谢
