### ISSUE TITLE
ProTable ellipsis属性在大于2k分辨率的屏幕下会不停闪烁🐛[BUG]

### ISSUE THREAD

**Issue by hjc0930** [ant-design/pro-components#4758]
### 🐛 bug 描述
使用ProTable开发表格，默认不设置ellipsis属性，在2K以上屏幕中会出现字体闪烁，观察Element发现是ant-typography-ellipsis属性不断切换导致
### 🏞 期望结果

表格不再闪烁

### © 版本信息

- pro-table版本：@2.51.2
- umi 版本：umi@3.5.20
- 浏览器环境：Chrome@98.0.4758.102
- 开发环境 Windows

### 🚑 其他信息

![proTable](https://user-images.githubusercontent.com/70308058/156358969-62368e02-a755-4ad1-8765-e621da320ccf.gif)
![Element](https://user-images.githubusercontent.com/70308058/156359442-e1de1572-c62f-4eeb-9efb-fde099cca144.png)

**Comment by chenshuai2144** [comment]
去 antd 提一下吧，估计是 js 的计算问题
