### ISSUE TITLE
🧐[问题]pro-table的postdata必须是post请求才能获取到值吗

### ISSUE THREAD

**Issue by s464446877** [ant-design/pro-components#476]
### 🧐 问题描述

pro-table的postdata必须是post请求才能获取到值吗？
我现在request是get请求，postdata里的data一直是undefined

**Comment by chenshuai2144** [comment]
不是的，postData是 request 出来的任何 data

**Comment by s464446877** [comment]
可是现在得到的是undefined，版本2.6.1

**Comment by s464446877** [comment]
是返回数据里必须要有data这个字段吗，如果没有就是undefined？

**Comment by itsuki0927** [comment]
是的, `{ data, success, total }`, 目前是这样子的, 必须要有data字段.
