### ISSUE TITLE
🐛[BUG]关于 menu 的 parentKeys 的行为

### ISSUE THREAD

**Issue by zqran** [ant-design/pro-components#4762]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/15389209/156504951-900e164e-525c-44f1-8d0d-747ad2cd5f9b.png)

antd-pro 中，这种情况下，访问 /bala/add 时，/bala/index 这个菜单不会高亮；但访问 /bala/add/1 时，/bala/index 菜单会高亮。 这是预期行为吗？

### 📷 复现步骤

如图配置路由

### 🏞 期望结果

访问 /bala/add 时，/bala/index 这个菜单会高亮

### 💻 复现代码

如图配置路由

### © 版本信息

- @ant-design/pro-layout: "^6.32.0"
- umi 版本: "^3.5.0"
- 浏览器环境: Chrome
- 开发环境 [e.g. mac OS]: mac OS

**Comment by 1247748612** [comment]
可能是你设置了parentKey会高亮？

`/bala/add`和`/bala/index`没有关联，无法高亮

一般这种情况下我会这么设置路由
`/bala/index`
`/bala/index/add`

**Comment by zqran** [comment]
/bala/add和/bala/index 是没有关联，所以，可以通过 parentKeys 来“关联”。[参考文档：自定义高亮](https://pro.ant.design/zh-CN/docs/advanced-menu/#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%AB%98%E4%BA%AE)

比如，设置后，访问 /bala/add/1 时，/bala/index 菜单会高亮

**Comment by zqran** [comment]
> 一般这种情况下我会这么设置路由 `/bala/index` `/bala/index/add`

这种方式是可行的，我现在疑惑的是 parentKeys 的行为

**Comment by zqran** [comment]
> 访问 /bala/add/1 时，/bala/index 菜单会高亮
> 访问 /bala/add 时，/bala/index 菜单不会高亮

@chenshuai2144 这是预期行为吗？

**Comment by chenshuai2144** [comment]
这个是个正则匹配。
/bala/add/:id 和  /bala/add/ 是匹配不起来的。

**Comment by zqran** [comment]
所以，此处的 parentKeys 也是有局限的，并不是配置了 parentKeys 就会高亮。而前提就是：parentKeys 和 当前的 path 要匹配才可以？
