### ISSUE TITLE
🐛[BUG] ProFormSelect request 执行两次

### ISSUE THREAD

**Issue by wangxin305** [ant-design/pro-components#4763]
### 🐛 bug 描述

 ProFormSelect request 初始执行两次

### 💻 复现代码

<ProFormSelect
          request={async () => {
            console.log(1111);
          }}
        />

### © 版本信息

- ProComponents 版本: "@ant-design/pro-form": "^1.55.1",
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by 1247748612** [comment]
没复现，建议升级到最新版本再试试

**Comment by wangxin305** [comment]
在ModalForm,BetaSchemaForm,DrawerForm都有这个问题

https://zrbddl.csb.app/


`import React from "react";
import { Button, message } from "antd";
import { ProFormSelect, ModalForm } from "@ant-design/pro-form";

export default () => {
  return (
    <ModalForm<{
      name: string;
      company: string;
    }>
      onFinish={async (values) => {
        console.log(values);
        message.success("提交成功");
      }}
      initialValues={{
        name: "蚂蚁设计有限公司",
        useMode: "chapter"
      }}
      trigger={<Button>打开表单</Button>}
    >
      <ProFormSelect
        width="sm"
        name="id"
        label="主合同编号"
        request={async () => {
          console.log(new Date().toString());
        }}
      />
    </ModalForm>
  );
};`
