### ISSUE TITLE
procard高级卡片如何加【key】🧐[问题]

### ISSUE THREAD

**Issue by changlin0501** [ant-design/pro-components#4765]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
procard高级卡片如何加【key】🧐[问题]

**Comment by chenshuai2144** [comment]
`<ProCard key="xxx"/>`

**Comment by changlin0501** [comment]
> `<ProCard key="xxx"/>`
Each child in a list should have a unique "key" prop. 出现这个报错呢

**Comment by chenshuai2144** [comment]
列表里面要加的每个项目都要 + key

**Comment by changlin0501** [comment]
好的，已经尝试过后发现没报错，谢谢了！
