### ISSUE TITLE
🐛[BUG] EditableProTable 自定义renderFormItem 不会自动注入fieldProps

### ISSUE THREAD

**Issue by LOVEtheWayuLie** [ant-design/pro-components#4766]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

![1646304182](https://user-images.githubusercontent.com/22782088/156549018-604ebfd4-5294-496a-a186-8fb386cfe5bb.jpg)
自定义renderFormItem 不会自动注入

### 📷 复现步骤

ProTable自动生成的Form表单, 有renderFormItem 是会自动注入fieldProps的

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by xXAvoraXx** [comment]
There are many problems with EditableProTable, if you make nested EditableProTable and parent table's state changes, child table's state doesn't change.

**Comment by LOVEtheWayuLie** [comment]
@xXAvoraXx Yes, so many problems , so many that I'm afraid

**Comment by LOVEtheWayuLie** [comment]
@chenshuai2144 bug是不是修错了,
![image](https://user-images.githubusercontent.com/22782088/157151127-219ac2d6-5a5f-4e33-967c-57d6f951261f.png)
就这么一行,  还是config参数, 根本不是自动注入,     自动注入是React.cloneElement 注入到  renderdom 中.
像这样子的? 
![image](https://user-images.githubusercontent.com/22782088/157151796-5339405b-7f4c-4109-9622-99a385b0a4eb.png)

**Comment by chenshuai2144** [comment]
欢迎来个pr

**Comment by LOVEtheWayuLie** [comment]
@chenshuai2144 陈总阿, 要不咱重新设计edit table吧, 这个真的惨不忍睹, 操作一致性太差了,  还特别能卡

**Comment by chenshuai2144** [comment]
欢迎来个pr
