### ISSUE TITLE
🐛[BUG] ProFormList 表单项无法基于label右对齐

### ISSUE THREAD

**Issue by rawbin-** [ant-design/pro-components#4767]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
使用ProFormList包裹的表单项无法label右对齐
<img width="605" alt="image" src="https://user-images.githubusercontent.com/8169783/156552164-7356e88b-b1e4-4a9e-afde-6b6d816017d4.png">

### 📷 复现步骤
https://codesandbox.io/s/jin-e-forked-knvchd?file=/App.tsx
https://codesandbox.io/s/biao-qian-yu-biao-dan-xiang-bu-ju-forked-juh3kt?file=/App.tsx:443-698

### 🏞 期望结果
ProFormList可以不影响表单对齐结果

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个实在是没法实现，你 ProFormList 里面包个 Row 手动实现一把。

ProFormList  这个块要和 form 做切分的。

**Comment by rawbin-** [comment]
最后通过给每一个ProFormText ProFormCheckBox 都传入layout配置实现了，虽然有点怪，但可用

https://codesandbox.io/s/jin-e-forked-xdk03o?file=/App.tsx
