### ISSUE TITLE
👑 [需求] ProTable 【查询（无按钮）表格】，怎么监听表单变化

### ISSUE THREAD

**Issue by scrapstation** [ant-design/pro-components#4768]
### 🔩 所属模块或组件
ProTable 

### 🥰 需求描述
表单变化自动触发搜索

### ⛰ 功能需求适用场景
https://procomponents.ant.design/components/table#%E6%9F%A5%E8%AF%A2%E6%97%A0%E6%8C%89%E9%92%AE%E8%A1%A8%E6%A0%BC

**Comment by 1247748612** [comment]
`onValuessChange`

 ![image](https://user-images.githubusercontent.com/29533304/156879817-d0b13199-155f-475e-b2c7-3376ebdd6903.png)

**Comment by cuijiudai** [comment]
onValuesChange
