### ISSUE TITLE
🐛[BUG]proTable组件偶尔会卡在loading状态

### ISSUE THREAD

**Issue by Atercia** [ant-design/pro-components#4771]
### 🐛 bug 描述

proTable组件偶尔会卡在loading状态，request里面的方法未被调用

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/34149452/156723312-8e20476d-ba4c-41fa-9b1a-9a3c50b3fb74.png)

进入一个只有proTable组件的页面时，proTable有时会一直卡在loading状态，（未发现有调用传入request的方法），刷新页面才恢复正常
![image](https://user-images.githubusercontent.com/34149452/156723430-16bf433a-e44f-4b23-8560-3345c7115142.png)

### © 版本信息

"@ant-design/pro-table": "~2.27.2",

windows10 谷歌浏览器、火狐浏览器

**Comment by chenshuai2144** [comment]
try catch 一下吧。看起来是 request 直接挂掉了的

**Comment by kklldog** [comment]
遇到同样的问题 ，request 偶尔不会触发 ，loading一直转转 。

**Comment by ChenWeihua123** [comment]
遇到同样的问题 ，request 偶尔不会触发 ，loading一直转转 。
