### ISSUE TITLE
🐛[BUG] No matching version found for @ant-design/pro-utils@1.35.2 

### ISSUE THREAD

**Issue by caoquy2000** [ant-design/pro-components#4772]
Hi, first of all, thanks for all the work you do here.
Today my Ant Design Pro project  can't  run npm install, with the next error. 

Describe the bug
When I try to install dependencies takes this error:

npm install

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @ant-design/pro-utils@1.35.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@ant-design/pro-descriptions'
npm ERR! notarget

My dependencies

"dependencies": {
    "@ant-design/icons": "^4.7.0", 
    "@ant-design/pro-descriptions": "^1.0.1",
    "@ant-design/pro-form": "^1.52.14",
    "@ant-design/pro-layout": "^6.32.7",
    "@ant-design/pro-provider": "^1.5.6",
    "@ant-design/pro-skeleton": "^1.0.5",
    "@ant-design/pro-table": "^2.62.8",
    "@umijs/route-utils": "^2.0.0",
    "antd": "^4.17.0",
    "classnames": "^2.3.0",
    "firebase": "^8.2.3",
    "git-cz": "^4.8.0",
    "immutable": "^4.0.0",
    "lodash": "^4.17.0",
    "moment": "^2.29.0",
    "omit.js": "^2.0.2",
    "prop-types": "^15.8.1",
    "rc-menu": "^9.1.0",
    "rc-util": "^5.16.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.7.0",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.2.0",
    "react-quill": "^1.3.5",
    "umi": "^3.5.0",
    "umi-request": "^1.0.8"
  },

Node: v14.15.3
NPM: v6.14.9
Thank You!

**Comment by kangtaku** [comment]
I got same issue as it.

**Comment by kangtaku** [comment]
https://github.com/ant-design/pro-components/commit/1e5f42d772faa98c4caea985e889d7785044eafa

this change seems like to relate to this issue.

**Comment by mengtongun** [comment]
@kangtaku 
How can I fixed that issue?

**Comment by 1247748612** [comment]
### Workaround

lock previous version

 - @ant-design/pro-card@1.18.34
 - @ant-design/pro-descriptions@1.10.47
 - @ant-design/pro-field@1.32.1
 - @ant-design/pro-form@1.55.1
 - @ant-design/pro-layout@6.33.1
 - @ant-design/pro-list@1.21.32
 - @ant-design/pro-table@2.65.0
 - @ant-design/pro-utils@1.35.1

**Comment by kangtaku** [comment]
@mengtongun I used 2.66.1 version instead of 2.27.2 which was previous one. It looks working on `npm install`

**Comment by 1247748612** [comment]
@chenshuai2144  Please republish new version to fix the issue

**Comment by caoquy2000** [comment]
@1247748612  Why it auto install @ant-design/pro-utils@1.35.2 bro ? While i didn't define it in package.json.

**Comment by mengtongun** [comment]
@caoquy2000  Other package required @ant-design/pro-utils@1.35.2. You can check in package.json.lock to see other package.

You can check this release.

https://github.com/ant-design/pro-components/commit/1e5f42d772faa98c4caea985e889d7785044eafa

**Comment by mengtongun** [comment]
@caoquy2000  Other packages required @ant-design/pro-utils@1.35.2. You can check in package.json.lock to see that requirement.

You can check this release.

https://github.com/ant-design/pro-components/commit/1e5f42d772faa98c4caea985e889d7785044eafa

**Comment by leonalicious** [comment]
having the same issue here 
![image](https://user-images.githubusercontent.com/4065175/156767041-1eaa1866-606f-4ef2-8c13-1b67bc75043a.png)

**Comment by fitterfizzle** [comment]
Having the same problem

![Screenshot 2022-03-04 at 13 55 03](https://user-images.githubusercontent.com/96863959/156767165-0c05da62-a12a-4b8c-9db6-a0dadff06fc8.png)

How can we fix this?

**Comment by mengtongun** [comment]
@fitterfizzle 
We are waiting for the response from the owner too.

But you really wish to fix it. You can downgrade the package of Antd that required @ant-design/pro-utils@1.35.2 .
Noted: It might break your current component.

**Comment by leonalicious** [comment]
@fitterfizzle what i did is i temporary revert those version number based on this [recent published](https://github.com/ant-design/pro-components/commit/1e5f42d772faa98c4caea985e889d7785044eafa)

and here are the screenshot for your reference, this may only works as temporary solution, we still need someone from the team to publish, most likely Monday I believe

![image](https://user-images.githubusercontent.com/4065175/156768475-7f5ba5a4-0ee1-4155-a24f-4c4ee2b4bcd8.png)

**Comment by mengtongun** [comment]
@fitterfizzle 
We are waiting for the response from the owner too.

But if you really wish to fix it. You can downgrade the package of Antd that required @ant-design/pro-utils@1.35.2 .
Noted: It might break your current component.

**Comment by xyy7260** [comment]
我从8点调测到了11点 居然是出现在这里

**Comment by xyy7260** [comment]
大晚上，而且周五正好要放假休息，没想到 一直在弄这个问题

**Comment by xyy7260** [comment]
为什么发布之前不测试呢 兄弟  🌛

**Comment by fanartie** [comment]
stuck for 5 hours !!!

**Comment by tnduc** [comment]
Huge impact on users

**Comment by sajidnagari** [comment]
I'm facing the same issue.

**Comment by cjbi** [comment]
I also encountered the same problem, if you know how to fix it, please tell me

**Comment by chenshuai2144** [comment]
sync 一下你们的  npm 私有库吧。

npm 有点抽风，包同步速度有点慢

**Comment by xyy7260** [comment]
哥还没解决了， 是发布版本安装过程中出现这样问题。

**Comment by xyy7260** [comment]
> sync 一下你们的 npm 私有库吧。
> 
> npm 有点抽风，包同步速度有点慢

async  npm 是什么意思呢

**Comment by mengtongun** [comment]
` npm show @ant-design/pro-utils` 
 But I still faced the same issue.

![image](https://user-images.githubusercontent.com/60088954/156912595-b7512d0b-c400-4acc-ac25-55b8170c0b04.png)

**Comment by mengtongun** [comment]
`yarn info  @ant-design/pro-utils`

**Comment by caoquy2000** [comment]
@mengtongun  Can yarn solve this problem bro?

**Comment by mengtongun** [comment]
It cannot solve bro @caoquy2000

**Comment by sajidnagari** [comment]
When I remove the node module. re-install module.
I upgrade Node version v16.14.0. It's working for me.

**Comment by kangtaku** [comment]
Why did it be closed? it seems still not work

**Comment by cjbi** [comment]
It works locally, not within Github Actions

**Comment by BobbleHatkjh** [comment]
its still not work

**Comment by trieutran81** [comment]
![image](https://user-images.githubusercontent.com/66985628/156965533-416963a2-2869-4e44-ad0d-5355693dc59e.png)
Fix it.

**Comment by FlowerWrong** [comment]
Waiting for release.
```js
"@ant-design/pro-layout": "^6.33.1",
"@ant-design/pro-utils": "^1.35.1", # 1.35.2 is missing on npm
"@ant-design/pro-form": "1.55.1", # old version
"@ant-design/pro-table": "2.65.0", # old version
```

**Comment by xXAvoraXx** [comment]
What to write to get new updates.

**Comment by mengtongun** [comment]
`yarn config set registry https://registry.npm.taobao.org/`

Try to add this to your Github Action. Or your CI/CD.

Reference
https://github.com/ant-design/pro-components/issues/4782
