### ISSUE TITLE
👑 [需求]Schema Form 的layoutType能否增加自定义的？

### ISSUE THREAD

**Issue by konhon** [ant-design/pro-components#4774]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

Schema Form

### 🥰 需求描述

假如我扩展了ModalForm，增加了某些功能(如拖动)，Schema Form的layoutType能用我扩展后的ModalForm吗？

**Comment by konhon** [comment]
目前我是用内嵌模式实现的，但感觉有些繁琐，每次都要在外面再包一层

**Comment by 1247748612** [comment]
我觉得可以支持一下，类似于valueTypeMap的方式

cc @chenshuai2144

**Comment by chenshuai2144** [comment]
太复杂了，会用的人不多。

直接用   contentRender 吧，内部用的也是这个api。
