### ISSUE TITLE
🧐[问题] 发现 ProTable 页面查询表单自动获取焦点，该怎么取消？

### ISSUE THREAD

**Issue by houkunlin** [ant-design/pro-components#4780]
提问前先看看：

### 🧐 问题描述
我不清楚是 AntDesignPro 的问题 还是 pro-components 的问题，在之前的版本还是正常的（进入页面不会自动获取焦点），但是当我升级了一些依赖后发现了进入列表页时，ProTable 的自带查询表单的第一个输入框会自动获取焦点，我该如何取消这个行为？

node_modules `@ant-design/pro-table@^2.66.1`

**Comment by chenshuai2144** [comment]
<html>
<body>


autoFocusFirstInput | 自动 focus 表单第一个输入框 | boolean | -
-- | -- | -- | --



</body>
</html>



在 protable的 form 配置里配置一下这个
