### ISSUE TITLE
copyable=false时ellipsis和width失效问题🐛[BUG]

### ISSUE THREAD

**Issue by tanwei0425** [ant-design/pro-components#479]
### 🐛 bug 描述
想实现width为30%，多余...，不想要复制
把copyable=false 会出现当前列很宽，不受width限制，其余列被挤压（别的列设置宽度为200也无效）

### 🏞 期望结果
copyable=false 和 copyable=true效果一样，只是把复制图标和功能去掉，其余样式不受影响

### 💻 复现代码
`{
        title: '序号',
        dataIndex: 'index',
        valueType: 'indexBorder',
        width: 80,
    },
    {
        title: '课程名称',
        dataIndex: 'title',
        // copyable: true,
        ellipsis: true,
        tip: '标题过长会自动收缩',
        // width: '30%',
    },
    {
        title: '状态',
        dataIndex: 'state',
        initialValue: 'all',
        filters: true,
        valueEnum: {
            all: { text: '全部', status: 'Default' },
            open: {
                text: '未解决',
                status: 'Error',
            },
            closed: {
                text: '已解决',
                status: 'Success',
            },
            processing: {
                text: '解决中',
                status: 'Processing',
            },
        },
        width: 150,
    },`

### © 版本信息
2.7.2
- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]
mac Os
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/37789693/93009488-6b386d80-f5b4-11ea-8b87-34f41bd9618a.png)

**Comment by chenshuai2144** [comment]
你要给这个列设置宽度了吗？

**Comment by yeesunday** [comment]
升级到 2.7.4 之后，设置宽度无效，ellipsis 被展开

```
  {
      title: 'title',
      dataIndex: 'index',
      ellipsis: true,
      width: 300,
      hideInSearch: true,
   },
```

**Comment by chenshuai2144** [comment]
看看你的dom，宽度是不是没放上去
