### ISSUE TITLE
新create项目 install报错 🐛[BUG]

### ISSUE THREAD

**Issue by goddesses98** [ant-design/pro-components#4792]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

Couldn't find any versions for "@ant-design/pro-utils" that matches "1.35.2"

目前在package.json  添加
```
"resolutions": {
    "@ant-design/pro-utils": "1.35.1"
  },
```
来强制使用旧版本解决问题

### 📷 复现步骤

yarn create umi xxx
cd xxx
yarn install

### 🏞 期望结果

项目依赖了未发布的"@ant-design/pro-utils"

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="651" alt="image" src="https://user-images.githubusercontent.com/95401505/157149140-0b544021-861c-43d0-bf04-e38a1732428d.png">

**Comment by chenshuai2144** [comment]
用用淘宝源，官方的源好像出问题了。。。
