### ISSUE TITLE
🐛[BUG] EditableProTable responsive problems

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/pro-components#4796]
If you view the page as mobile, you can see the problem.
https://procomponents.ant.design/components/editable-table

![responsivetable](https://user-images.githubusercontent.com/6988989/157245627-b1c7b9b6-7834-4d8e-aae8-ba24569b0e88.png)

version: "@ant-design/pro-table": "^2.61.0",

**Comment by 1247748612** [comment]
refer [scroll](https://ant.design/components/table/#scroll) property
