### ISSUE TITLE
🧐[问题]如何单独只自定义ProTable 右侧工具栏的刷新事件？

### ISSUE THREAD

**Issue by strongyc** [ant-design/pro-components#4797]
ProTable使用中，不使用request查询，右侧工具栏刷新按钮失效，如何单独自定义该按钮的事件？

![image](https://user-images.githubusercontent.com/51156342/157248510-2c1da462-c030-4963-9246-48c67f84f732.png)

**Comment by chenshuai2144** [comment]
<html>
<body>


options | table 工具栏，设为 false 时不显示 | {{ fullScreen: boolean \| function, reload: boolean \| function,setting: true, density?: boolean }} | { fullScreen: false, reload:true, setting: true}
-- | -- | -- | --



</body>
</html>


reload 支持设置为一个方法，这样就可以重置掉默认的reload了

**Comment by strongyc** [comment]
还有一个问题
![image](https://user-images.githubusercontent.com/51156342/157258503-3a0f02c8-7fbb-4a71-b038-98288522fae7.png)
ActionType无法调用清空选中方法

**Comment by strongyc** [comment]
![image](https://user-images.githubusercontent.com/51156342/157258987-5c9b8f65-a47a-4021-96ac-4e28f475074a.png)
fangf方法已经定义了，这个该怎么用呢

**Comment by chenshuai2144** [comment]
继续加个 ?.
