### ISSUE TITLE
EditableProTable 要怎么自定义操作栏 没找到方法

### ISSUE THREAD

**Issue by hreochen** [ant-design/pro-components#4800]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by 1247748612** [comment]
https://procomponents.ant.design/components/editable-table#actionrender-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%93%8D%E4%BD%9C%E6%A0%8F 这里有写
