### ISSUE TITLE
🐛[BUG] table切换分页时，去掉选中项，现在是切换分页，选中项还保留

### ISSUE THREAD

**Issue by believeZJP** [ant-design/pro-components#4805]
### 🐛 bug 描述

Table切换到第二页时，怎样清除选中项

### 📷 复现步骤
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/15198091/157419269-32c2f007-9ff1-4028-9941-6b9154bf7001.png">

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/15198091/157419358-fd381a05-3f85-4fc5-9dd5-323ab1614b3d.png">
### 🏞 期望结果
切换分页时，选中项清除

### 💻 复现代码

https://codesandbox.io/s/biao-ge-pi-liang-cao-zuo-forked-xthe2d?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by 1247748612** [comment]
这个实现和antd保持一致的

--- 

按你说的可以这么做：


监听[页码切换](https://ant.design/components/table-cn/#pagination)然后执行[`clearSelected`](https://procomponents.ant.design/components/table#protable)

**Comment by believeZJP** [comment]
> 这个实现和antd保持一致的
> 
> 按你说的可以这么做：
> 
> 监听[页码切换](https://ant.design/components/table-cn/#pagination)然后执行[`clearSelected`](https://procomponents.ant.design/components/table#protable)
这个属性是干什么的，
rowSelection={{
        preserveSelectedRowKeys: false,
}}

如果要监听切换页面并清除，在protable里怎么加，是要自己实现分页功能吗，能给个示例不

**Comment by 1247748612** [comment]
preserveSelectedRowKeys 这个属性设置为true貌似可以解决你的问题 你尝试一下

**Comment by believeZJP** [comment]
> preserveSelectedRowKeys 这个属性设置为true貌似可以解决你的问题 你尝试一下

不生效，代码链接  https://codesandbox.io/s/biao-ge-pi-liang-cao-zuo-forked-xthe2d?file=/App.tsx

**Comment by 1247748612** [comment]
> 不生效，代码链接  https://codesandbox.io/s/biao-ge-pi-liang-cao-zuo-forked-xthe2d?file=/App.tsx

看起来是ProTable缓存了与antd无关

**Comment by 1247748612** [comment]
antd Table的问题
