### ISSUE TITLE
🐛[BUG] valueType: 'digit' 和 renderText 同时配置 出现NaN

### ISSUE THREAD

**Issue by beeant0512** [ant-design/pro-components#481]
### 🐛 bug 描述

对一个column配置了valueType: 'digit'和renderText，表格显示NaN

### 📷 复现步骤

columns = [
  ...
  {
      ...
      valueType: 'digit',
      renderText: (text) => `${text} 元`
  }
]

### 🏞 期望结果

表格显示 *** 元而不是NaN

### 💻 复现代码

columns = [
  ...
  {
      ...
      valueType: 'digit',
      renderText: (text) => `${text} 元`
  }
]

### © 版本信息

- ProComponents 版本: @ant-design/pro-table 2.7.2
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/issues/466
