### ISSUE TITLE
🧐[问题] toolBarRender 中的按钮的 loading 状态如何与 request 中管理的 loading 同步？

### ISSUE THREAD

**Issue by hooliy** [ant-design/pro-components#4811]
toolBarRender 中的按钮的 loading 状态如何与 request 中管理的 loading 同步？

**Comment by 1247748612** [comment]
toolbarRender使用request的loading？

可以实现但可能会造成性能影响，目前request发起请求不会重新执行toolbarRender，就算把loading传给了toolbarRender也更新不上。

这样就得调整代码，loading变了重新执行toolbarRender的执行，这就可能造成性能开销

已经有一个全局的loading按钮级别的可以不需要展示了

**Comment by hooliy** [comment]
> 

好像不是全局的loading，点击查询的时候，loading作用于表格和查询按钮，比如在页面的 toolbarRender 里添加有 新增，导出，之类的按钮，当点击查询的时候 loading 并不会作用于   toolbarRender 里的按钮
