### ISSUE TITLE
🐛[BUG] ProForm 行编辑数据被非预期缓存

### ISSUE THREAD

**Issue by rawbin-** [ant-design/pro-components#4812]
### 🐛 bug 描述
编辑表格行，预期每行编辑的时候表单加载当前行数据，结果编辑编辑过的行的时候数据始终不变了

### 📷 复现步骤
在这里 https://codesandbox.io/s/proformlistbian-ji-shu-ju-bei-fei-yu-qi-huan-cun-7khfkm?file=/App.tsx
先点击第一行的编辑（加载第一行ok）
再点击第二行的编辑（加载第二行ok）
然后可以点击第三行的编辑（加载第三行ok）
最后点击第一行的编辑（这个时候数据还是第二行或者第三行的 不ok）

### 🏞 期望结果
期望不管怎么玩，点哪一行就加载哪一行的数据

### 💻 复现代码
https://codesandbox.io/s/proformlistbian-ji-shu-ju-bei-fei-yu-qi-huan-cun-7khfkm?file=/App.tsx

### © 版本信息

- ProComponents 版本: ProForm 1.57.0
- umi 版本
- 浏览器环境 Chrome99
- 开发环境 macOS

**Comment by 1247748612** [comment]
![image](https://user-images.githubusercontent.com/29533304/157617848-92a22ad5-7dda-4ae1-9e07-6561286f40e1.png)

已经弹出警告了，只要重复打开同一个数据就会出现，request是用于初始化值的但你的实现里感觉是用于赋值，然后就出错了没赋值上新的值就等同于你说的缓存了，其实并没有缓存。

### 解决方法

加个key避免复用vdom
![image](https://user-images.githubusercontent.com/29533304/157617556-afc49be3-ff87-4ae9-8dcc-1927d1dd55b6.png)

或使用Fome.setFieldsValue设置值

**Comment by rawbin-** [comment]
看到警告了，感觉我没有用initialValues，也用了request，怎么知道这个地方还需要用个key呢

**Comment by 1247748612** [comment]
> 看到警告了，感觉我没有用initialValues，也用了request，怎么知道这个地方还需要用个key呢

看你的代码其实就是一个ProForm处理了不同currentId的表单数据，request + params({currentId}) 只是做初始化，当你的currentId已经初始化过了(已经执行了一次request)就会触发这个错误，因为这个params应该已经缓存了，但你加了个随机数那就一直是新的数据，没有被缓存。

加key其实是react的东西，不同的key避免复用dom，也就是切换了currentId，ProForm就等同于一个新渲染的dom，从没初始化过也就不会出现那个警告啦

另外，看你是想实现弹窗加Form，可以直接使用ModalForm或者DrawerForm更加方便

**Comment by rawbin-** [comment]
嗯呢 多谢啦，加key的话一般不是区分重复DOM么，咱们这里其实是希望复用独一份，可能使用setFieldsValue更符合直观的理解，没问题 谢谢耐心解答~

**Comment by wanglihuaya** [comment]
Modal 加上 destroyOnClose: true,关闭销毁，复用独一份
