### ISSUE TITLE
EditableProTable 在某一行编辑状态时，不能通过js或者某api调用自动填充某个字段的值吗？

### ISSUE THREAD

**Issue by viprespro** [ant-design/pro-components#4815]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

在编辑table中的某一行时，我通过交互打开地图，选择某个位置并拿到位置及经纬度，想要通过代码的方式来设置某一字段的坐标而不是手动输入，我看了相关文档，发现并没有可以操作api，想确认下是本来没有这个功能，但是觉得这个应该是常见的功能，所以不是很确认？谢谢解答

### 🚑 其他信息

![微信截图_20220310204720](https://user-images.githubusercontent.com/38908500/157664842-f21f7e0d-bb76-4ad5-ab06-b1c0ab44fec7.png)

**Comment by viprespro** [comment]
> https://procomponents.ant.design/components/editable-table/#editable-%E7%BC%96%E8%BE%91%E8%A1%8C%E9%85%8D%E7%BD%AE
> 
> 有个form属性可以操作里面的数据

我试过了不行 你可有实际做过吗 其他地方我也找不到相关的说明 因为table它是多行多列  表单设置值的话只需要设置提供字段名，但是这个是和编辑的行之类的。无法指定具体某个字段

**Comment by 1247748612** [comment]
数据结构确实是不可以，但可以操作里面的数据
我的使用方式是设置了个rowKey
然后使用form 就是 form.setFieldsValue({
[rowKey]: value
})

要改哪行就用哪行的rowKey值去设置就行了

要摸索一下，这个EditableTable确实很奇怪

**Comment by viprespro** [comment]
> 

按照你的描述，设置了rowKey也只能知道编辑行，但编辑是哪个字段值还需要指定吧 form.setFieldsValue({
[rowKey]: value
})   之前探索的时候 有个api actionRef.current.addEditRecord.({ id: '12' , name: '12312'}) 即增加一行的时候 可以为此编辑行的某个字段赋值，我以为也有之类的api， 然后官方也没人给我确认下。

**Comment by 1247748612** [comment]
> 按照你的描述，设置了rowKey也只能知道编辑行，但编辑是哪个字段值还需要指定吧 form.setFieldsValue({ [rowKey]: value }) 

看你的描述你应该是知道你要动态插入值的rowKey的

> 之前探索的时候 有个api actionRef.current.addEditRecord.({ id: '12' , name: '12312'}) 即增加一行的时候 可以为此编辑行的某个字段赋值，我以为也有之类的api， 然后官方也没人给我确认下。

现在是没有的，如果有这种api会更方便可以提个 feature，或者直接动手pr

**Comment by viprespro** [comment]
> 

在配置editable属性的时候，加了form属性之后拿到form实例。我猜想是当某一项变为可以编辑的时候，可以把它当成一个form，而上面的form就是此时的表单实例，但是我想通过此form去获取字段名称时得到的是undefined，resetFields也不起作用，就像是这些input表单没有设置name一般。你这个方式  form.setFieldsValue( {[rowKey]: value }) 比较疑惑？

**Comment by yzwxk** [comment]
改为dataSource模式 直接编辑dataSource

**Comment by viprespro** [comment]
form.setFieldsVlaue({ [rowkey]: { title: 'xxx', desc: 'xxx' } })
