### ISSUE TITLE
🐛[BUG] ProForm 的Input设置了readonly,如果没有值时，显示 -，怎样去掉这个

### ISSUE THREAD

**Issue by believeZJP** [ant-design/pro-components#4818]
### 🐛 bug 描述
<img width="298" alt="image" src="https://user-images.githubusercontent.com/15198091/157671227-e27bae80-9947-487d-826c-af1f25c6d97e.png">

<img width="517" alt="image" src="https://user-images.githubusercontent.com/15198091/157671524-90f2cacf-9b84-47a8-8160-524fae90274c.png">

### 📷 复现步骤
```js
<ProFormText
        width="md"
        readonly
        name="company"
        label="我方公司名称"
        placeholder="请输入名称"
      />
```
### 🏞 期望结果
数据为空时，可以自定义显示内容

**Comment by 1247748612** [comment]
emptyText = ''

**Comment by believeZJP** [comment]
> emptyText = ''

试过了，可以生效
