### ISSUE TITLE
[Pro-Provider] Files es_ES.d.ts and es_ES.js in the locale folder are missing some translation for the spanish Intl

### ISSUE THREAD

**Issue by jjtorres93** [ant-design/pro-components#4820]
Currently the files to use the config provider for spanish language are missing some translation that are available in other language, at the es_ES.d.ts file the object "form" is not defined so when you use the por-table with the property search:{ filterType: 'light' } the buttons for the form are not translated. The spanish community would appreciate if you guys could complete the translation in future releases. Thank you. These files are located in the node_modules > @ant-design/pro-provider/es/locale

en_US.js File:
<img width="217" alt="en_US.js" src="https://user-images.githubusercontent.com/63448726/157765887-acb5b1ad-876e-499b-8046-e51ac52dc5d4.png">

es_ES.js File
<img width="324" alt="es_ES.js" src="https://user-images.githubusercontent.com/63448726/157765899-11888908-8272-4439-b415-88cd409d94cc.png">

en_US.d.ts File:
<img width="245" alt="en_US.d.ts" src="https://user-images.githubusercontent.com/63448726/157765892-393a13c3-6a35-49a7-919a-bf00a341c720.png">

es_ES.d.ts File:
<<img width="294" alt="es_ES.d.ts" src="https://user-images.githubusercontent.com/63448726/157767083-3bdff885-8d75-474c-8a80-e2ffd905ced0.png">

Component using ConfigProdiver locale={esESIntl}
<img width="261" alt="Rendered Component without intl" src="https://user-images.githubusercontent.com/63448726/157765901-296f36ba-b2ac-4cf8-9f16-99eb1ee92179.png">

**Comment by 1247748612** [comment]
We don't speak Spanish, can you translate for us?

**Comment by jjtorres93** [comment]
Thanks for the quick reply, the translations for the missing items would be:
```lightFilter{
  more: 'Más',
  clear: 'Limpiar',
  confirm: 'Confirmar',
  itemsUnits: 'Objetos'
},
```
When it comes to the itemsUnits translation I'm not really sure where it's being use so I used a literal translation, it might be safer to let with the english translation ('items')

While comparing the two files (en_US and es_ES) I also noticed that the following attributes were also missing : 
<img width="227" alt="en_US.d.ts editableTable props" src="https://user-images.githubusercontent.com/63448726/157859642-3cb537b3-39ed-417f-9537-de3591ce52bb.png">
<img width="181" alt="en_US.js editableTable props" src="https://user-images.githubusercontent.com/63448726/157859831-897cc3cd-3605-46e8-814b-d32d673f192f.png">

For this one the translations would be this:

```
editableTable: {
  action: {
    save: 'Guardar',
    cancel: 'Descartar',
    delete: 'Borrar'
  }
}
```

**Comment by 1247748612** [comment]
Thanks for help us translate,

 I also noticed that the following attributes were also missing:
  
![image](https://user-images.githubusercontent.com/29533304/158044487-79d2e6bf-798f-4b9e-87f1-a36fe80dd79e.png)

Can you help translate?

**Comment by 1247748612** [comment]
Thanks you, trace pr #4849
