### ISSUE TITLE
🐛[BUG]ProTable、SchemaForm、ProForm自定义'valueType'，'LightFilter'模式下，fieldLabel显示值出现'[object Object],[object Object]'

### ISSUE THREAD

**Issue by ilywan1104** [ant-design/pro-components#4821]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
> ProTable、SchemaForm、ProForm自定义'valueType'，'LightFilter'模式下，fieldLabel显示值出现'[object Object],[object Object]'

![image](https://user-images.githubusercontent.com/8229719/157784198-10b8a9d3-131b-408c-a4a9-8339ce24c7fe.png)

### 📷 复现步骤
[codesandbox 代码演示](https://codesandbox.io/s/schema-biao-dan-forked-7g60iq?file=/App.tsx)

### 🏞 期望结果
![image](https://user-images.githubusercontent.com/8229719/157784661-bbf83bed-78c5-4979-a560-65b1276f6b20.png)

### 💻 复现代码
[codesandbox 代码演示](https://codesandbox.io/s/schema-biao-dan-forked-7g60iq?file=/App.tsx)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by 1247748612** [comment]
onChange不要传对象实现方式其实类似于select

**Comment by 1247748612** [comment]
展示的时候用value去取对对应的label，否则就会造成这样的问题

**Comment by chenshuai2144** [comment]
```
formItemProps: {
      lightProps: {
        labelFormatter: (value) => `app-${value}`,
      },
    },
```

可以用这个自定义格式化一下
