### ISSUE TITLE
🧐[问题]ProFormUploadButton，再Edge浏览器内点击下载，.docx文件默认跳转到微软在线预览

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#4825]
开发环境
![image](https://user-images.githubusercontent.com/12421552/157831488-c0f58216-a108-451e-8b74-e273f591aa79.png)

使用环境
![image](https://user-images.githubusercontent.com/12421552/157831602-2e4a71a7-9040-4ae3-8ee0-29db8eb71b91.png)

点击右边下载，
![image](https://user-images.githubusercontent.com/12421552/157831712-4925c91c-38e5-49f0-858d-ebbf7bc35fba.png)

浏览器会默认跳转到这里，使用谷歌浏览器就没得问题，
![image](https://user-images.githubusercontent.com/12421552/157831817-82da57fd-cfde-44e3-b0e8-2d90d397d012.png)

**Comment by 1247748612** [comment]
antd的问题去那提issue

**Comment by chenshuai2144** [comment]
这是微软浏览器自带的特性，为了推广他们的office 365
