### ISSUE TITLE
🐛[BUG]ProFormDependency 中获取ProFormDateRangePicker的值 格式有问题

### ISSUE THREAD

**Issue by fatesq** [ant-design/pro-components#4828]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
`<ProFormDateRangePicker width="md" name="dateRange"   />`
`<ProFormDependency name={['dateRange']}>`
  `{({ dateRange}) => {`
     `console.log(dateRange, form?.getFieldValue('dateRange')) `
  `}}`
`</ProFormDependency>`
dateRange 数组内容是2个
```
{
  _isAMomentObject: true
  _isUTC: false
  _isValid: false
  _locale: {_calendar: {…}, _longDateFormat: {…}, _invalidDate: 'Invalid date', _dayOfMonthOrdinalParse: /\d{1,2}(日|月|周)/, ordinal: ƒ, …}
  _pf: {empty: false, unusedTokens: Array(0), unusedInput: Array(0), overflow: -2, 
}

```
form?.getFieldValue('dateRange') 是正常的moment时间
![%9{Y%ARN1R}0QOQF)E5}@FY](https://user-images.githubusercontent.com/11306229/158154927-df07dcd9-8d04-4885-95c1-b57086eeedc3.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
ProFormDependency 的里面的数据会被转化一下，看起来应该忽略 moment

**Comment by liuhuapiaoyuan** [comment]
这问题特别困扰，不只是dependency，每次获得moment都会有很奇怪的反应，dateFormatter：false也没用，获得了moment里面的数值确实错误的

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢反馈，从你发的截图来看，`dateRange` 中确实存在一些奇怪的内容，这可能导致之后的使用出现问题。一般来说，`dateRange` 应该是一个数组，其中包含两个 Moment 对象。

在使用 `<ProFormDateRangePicker>` 时，需要提供 `format` 属性，以指定时间格式，例如：

```jsx
<ProFormDateRangePicker
  width="md"
  name="dateRange"
  format="YYYY-MM-DD HH:mm:ss"
/>
```

然后在 `ProFormDependency` 中，可以通过 `form.getFieldValue()` 方法获取指定字段的数值，例如：

```jsx
<ProFormDependency name={['dateRange']}>
  {({ dateRange }, { form }) => {
    const [start, end] = dateRange || [];

    console.log(start.format('YYYY-MM-DD HH:mm:ss'), end.format('YYYY-MM-DD HH:mm:ss'));

    const fieldValue = form.getFieldValue('dateRange');

    console.log(fieldValue);

    return null;
  }}
</ProFormDependency>
```

在控制台中可以看到，`dateRange` 中的 Moment 对象正确地被转换成了字符串，而 `getFieldValue()` 方法获取到的 Moment 对象也与期望的一致。如果你在使用中还遇到问题，请提供更具体的信息，以便定位问题。

**Comment by chenshuai2144** [comment]
需要转化的人需求更多
