### ISSUE TITLE
🐛[BUG] ModalForm destroyOnClose 不生效

### ISSUE THREAD

**Issue by fanck0605** [ant-design/pro-components#4832]
### 🐛 bug 描述

由于 destroyOnClose 不生效，在 visible 为 false 时，ModalForm 中的 Form 节点仍然存在

### 📷 复现步骤

点击编辑，虽然 initalValues 被修改了，但是由于 destroyOnClose 不生效，Form 节点没有被重建，因此 initialValues 的变化没有任何作用

### 🏞 期望结果

destroyOnClose 为 true, 且 visible 为 false 时，ModalForm 中的 Form节点被销毁

### 💻 复现代码

pro-form: 1.57 有问题
https://codesandbox.io/s/modalform-destoryonvisible-p9omvl?file=/App.tsx

pro-form: 1.52 正常
https://codesandbox.io/s/modalform-destoryonvisible-8zl10i?file=/App.tsx

### © 版本信息

- ProComponents 版本: pro-form: 1.57
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by 1247748612** [comment]
得加上个forceRender: false

**Comment by 1247748612** [comment]
看看这个#4773

**Comment by 1247748612** [comment]
目前看来加上了默认forceRender为true 导致了更多的问题出现 @chenshuai2144

**Comment by fanck0605** [comment]
好了, 但是这个应该只能算是个 workaround 吧

> 得加上个forceRender: false

**Comment by 1247748612** [comment]
> 好了, 但是这个应该只能算是个 workaround 吧

不算workaround，antd 的 Modal forceRender默认为false，这里是true

现在统一为false

**Comment by fanck0605** [comment]
好的

**Comment by brysonLin247** [comment]
> 

加了之后还是不行呀

**Comment by fanck0605** [comment]
> > 
> 
> 加了之后还是不行呀

最新版不是修复了吗？只要开启 destroyOnClose 就可以了。

**Comment by wanglihuaya** [comment]
> > > 
> > 
> > 
> > 加了之后还是不行呀
> 
> @brysonLin247 最新版不是修复了吗？只要开启 destroyOnClose 就可以了。

是不是还需要 `form?.resetFields();` 一下，我这边只加 `destroyOnClose: true` 不可以 最新的 `pro-form": "^1.65.0`
