### ISSUE TITLE
🐛[BUG] 使用lazy引入的 procomponent组件会使antd动态主题失效

### ISSUE THREAD

**Issue by leesama** [ant-design/pro-components#4834]
### 🐛 bug 描述

使用lazy引入的 procomponent组件会使antd动态主题失效
### 📷 复现步骤

lazy引入procomponent有关组件后 ，无法动态去改变主题色

### 🏞 期望结果

正常使用动态主题

### 💻 复现代码

https://github.com/leesama/procomponent-dynamic-theme-issue

https://codesandbox.io/s/cocky-nova-i3ndbu

**Comment by leesama** [comment]
因为procomponent把antd的样式在引入了一次 把自定义的样式覆盖掉了

**Comment by chenshuai2144** [comment]
不要用lazy 呗。动态主题可以等antd v5了。会更好用
