### ISSUE TITLE
👑 [需求] proList  defaultExpandAllRows api文档完善

### ISSUE THREAD

**Issue by Deja-vuuu** [ant-design/pro-components#4835]
### 🔩 所属模块或组件
@ant-design/pro-list

### 🥰 需求描述
配置ProList 默认展开所有   即defaultExpandAllRows为true时  expandedRowKeys 初始值不能为空数组
翻了半天源码才看到这里 ，希望文档能表明一下，避免大家犯重复错误

### 🚑 其他信息
源码在 LiseVIew 129行

如果初始配置为空数组，没办法判断到defaultExpandAllRows的值
<img width="785" alt="image" src="https://user-images.githubusercontent.com/27748682/158009941-5ea2e33a-1e93-450e-add5-71ec9b00f967.png">

**Comment by chenshuai2144** [comment]
这个是js的基础，空数组代表值。null 和 "" 都是的
