### ISSUE TITLE
How can I propely format the a dateTime using EditableTable for the editable form and for the search form

### ISSUE THREAD

**Issue by jalopez526** [ant-design/pro-components#4838]
So I have an <EditableProTable /> which has variaty of columns:

I wish to have the option to handle all my dates in the following format: DD/MM/YYYY HH:mm:ss

```js
{
      title: 'Fecha/Hora',
      dataIndex: 'FechaHora',
      key: 'FechaHora',
      width: '14%',
      valueType: 'dateTime',
      formItemProps: {
        rules: [required],
      },
    },
    {
      title: 'TA Sistólica',
      dataIndex: 'TensionArterial',
      key: 'TensionArterial',
      width: '14%',
      valueType: 'digit',
      hideInTable: true,
    },
    {
      title: 'TA Diastólica',
      dataIndex: 'TensionArterialDiastolica',
      key: 'TensionArterialDiastolica',
      width: '13%',
      valueType: 'digit',
      hideInTable: true,
    },
```

Im having a littlebit of issue as I haven't found a way to identify how can I set this format (DD/MM/YYYY HH:mm:ss) to the column *FechaHora*

I've tried using custom *render* and *renderFormitem* and maybe I can come up with something but I it won't be a reusable option in the future. I also tried using the *dateFormatter* prop from the EditableTable and is not working.

Is there anything for this that can be used to customize the date format without actually having to tweak to much the node im rendering?

**Comment by 1247748612** [comment]
You can set fieldProps.format to override the default format

![image](https://user-images.githubusercontent.com/29533304/158048296-f372407a-4815-43e3-ad99-7a884a673a80.png)

**Comment by jalopez526** [comment]
That actually solved my problem, thanks @1247748612!

**Comment by jalopez526** [comment]
Hey @1247748612 do you know how can I set initial value without getting this warning message:
`Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.`

So im trying to pass an initial value to a column with valueType: dateTime. But im getting that error message. The initial value im passing is an string with the format of `DD/MM/YYYY HH:mm:ss` I tried using moment like: `moment(dateField, 'DD-MM-YYYY HH:mm:ss') but Im still getting the warning when I press save on the EditableProTable. Not sure if there's any tweak for that.

**Comment by 1247748612** [comment]
Can your provider reproduce in the [codesandbox](https://codesandbox.io/)?
