### ISSUE TITLE
🧐[问题] 使用mix模式，点击进入自定义渲染的menuData以外的路由，路由拆分失效，

### ISSUE THREAD

**Issue by q389491729** [ant-design/pro-components#484]
### 🧐 问题描述
使用mix模式，点击进入自定义渲染的menuData以外的路由，路由拆分失效, Top的menu被全部放到了右边。不知道这个是bug还是本身就是这么设计的？

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/pro-components/issues/458
