### ISSUE TITLE
🐛[BUG] StepsForm分步表单动态渲染无效，只有点击下一步才会更新

### ISSUE THREAD

**Issue by wxq851685279** [ant-design/pro-components#4841]
```{
  isLink ? (
    <StepsForm.StepForm
      title="第二步"

    >
     分步表单-第二步
      />
    </StepsForm.StepForm>
  ) : null
}
```

**Comment by 1247748612** [comment]
提供个复现代码 https://codesandbox.io/

**Comment by wxq851685279** [comment]
> 提供个复现代码 https://codesandbox.io/

https://codesandbox.io/s/sharp-glitter-jiodhv?file=/src/pages/TableList/index.tsx

**Comment by wxq851685279** [comment]
> > 提供个复现代码 https://codesandbox.io/
> 
> https://codesandbox.io/s/sharp-glitter-jiodhv?file=/src/pages/TableList/index.tsx

就是需要通过按钮来控制分布表单是否隐藏某一步

**Comment by 1247748612** [comment]
确实不支持，可以尝试下SchemaForm来生成，动态控制columns的列数试试
https://procomponents.ant.design/components/schema-form#json-%E6%9D%A5%E7%94%9F%E6%88%90%E5%88%86%E6%AD%A5%E8%A1%A8%E5%8D%95

**Comment by haobarry** [comment]
正好有这个需求

**Comment by jasoncheow** [comment]
我也有这个需求。其中之一的`StepsForm.StepForm`里会有的选择，而接下来的步骤会因这个选择而改。想问一下之后的pro-component版本会支持吗？

**Comment by toored2** [comment]
我也遇到了相同的问题

**Comment by zxf6677** [comment]
你可以添加一个key值，获取数据后通过setstate修改key值，让组件重新渲染

**Comment by haobarry** [comment]
> 你可以添加一个key值，获取数据后通过setstate修改key值，让组件重新渲染

有例子么
