### ISSUE TITLE
🐛[BUG] pro-table valueType percent 精度问题

### ISSUE THREAD

**Issue by xiexingen** [ant-design/pro-components#4845]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤

配置某个列为percent，代码如下
 valueType: () => ({
    type: 'percent',
    precision: 0,
  })
当实际的值为70.11的时候，配置precision为0,也照样显示70.11
ps： 如果precision:1 显示70.1 是正常的
### 🏞 期望结果
配置precision:0 应该不显示小数

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by yzwxk** [comment]
Same issue here.
PR: https://github.com/ant-design/pro-components/pull/4863
