### ISSUE TITLE
🐛[BUG]pro-table column定义有设置key时，动态设置fixed不生效

### ISSUE THREAD

**Issue by edision** [ant-design/pro-components#4847]
### 🐛 bug 描述

pro-table column定义有设置key时，动态设置fixed不生效。

### 📷 复现步骤

https://codesandbox.io/s/zen-sara-bitkh0

### 🏞 期望结果

由于需要同时存在多个同名的dataIndex的列，比如，搜索表单需要时间区间，而表格显示普通时间
,所以需要使用key，期望是设置了key不会影响动态设置fixed

### 💻 复现代码

[](https://codesandbox.io/s/zen-sara-bitkh0)

### © 版本信息

- ProComponents 版本:  "@ant-design/pro-table": "^2.66.4",
- umi 版本 3.5.21
- 浏览器环境 Microsoft Edge  99.0.1150.36
- 开发环境 [e.g. mac OS] windows 11

**Comment by chenshuai2144** [comment]
修复了使用了 dataIndex 来代替 index
