### ISSUE TITLE
🐛[BUG]pro-table valueType为date 时设置 <DatePicker picker="month" />后选择日期后依然显示day

### ISSUE THREAD

**Issue by goodve** [ant-design/pro-components#485]
### 🐛 bug 描述

 valueType为date 时设置 `<DatePicker picker="month" />`后选择日期后依然显示day

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/17634299/93038430-8d46f400-f677-11ea-9e9f-e58e30123fb9.png)

这是选择 date  后只能输出 yyyy-MM-dd  格式么

### © 版本信息

- ProComponents 版本: [2.7.1]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
date 永远都是 YYYY-mm-dd

**Comment by goodve** [comment]
> date 永远都是 YYYY-mm-dd

antd  的<DatePicker picker="month" />  输出就是  yyyy-MM  这里既然时继承过来的为何要限定死

**Comment by chenshuai2144** [comment]
@goodve valueType= dateMonth 才是月份
