### ISSUE TITLE
🐛[BUG] showSizeChanger

### ISSUE THREAD

**Issue by WT-Road** [ant-design/pro-components#4850]
### 🐛 bug 描述
对于之前提的问题,https://github.com/ant-design/pro-components/issues/4711
更新到"@ant-design/pro-table": "2.67.0"后发现还是有问题
测试了下Antd的Table

1.showSizeChanger: false // 切换器永远不会显示
2.showSizeChanger: true // 切换器永远显示
3.不设置showSizeChanger // 当大于50条时显示, 小于等于50不显示

测试了下2.67.0的ProTable
1.showSizeChanger: false // 切换器永远不会显示
2.showSizeChanger: true // 切换器永远显示
3.不设置showSizeChanger // 切换器永远显示

### 🏞 期望结果

由于项目中是Antd和<ProTable/>混用, 希望能保持一致,即:
不设置showSizeChanger // 当大于50条时显示, 小于等于50不显示

### 💻 复现代码

<Table columns={columns1} dataSource={data} pagination={{ pageSize: 10 }} scroll={{ y: 240 }} />
<ProTable pagination={{pageSize: 10, // showSizeChanger: false}} />
### © 版本信息

- ProComponents 版本: [e.g. 2.67.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by DerrickTel** [comment]
2.68.1可以的，要不你升级一下？

**Comment by WT-Road** [comment]
> 2.68.1可以的，要不你升级一下？
额...刚升级了下2.68.1,没有设置showSizeChanger,少于50条还是显示切换器

**Comment by WT-Road** [comment]
@DerrickTel 好像并没有效果切换器还常在...

**Comment by DerrickTel** [comment]
https://codesandbox.io/s/cha-xun-biao-ge-forked-w9xsbu?file=/App.tsx

**Comment by DerrickTel** [comment]
里面有注释，你放开和打开看看

**Comment by DerrickTel** [comment]
https://user-images.githubusercontent.com/24643779/158755375-50b67d86-5004-4a40-9049-c1395c1db03f.mp4

**Comment by WT-Road** [comment]
> https://codesandbox.io/s/cha-xun-biao-ge-forked-w9xsbu?file=/App.tsx

额,抱歉,codesandbox中测试2.67.0就是没问题了, 那就是我项目的问题, 我再找找原因,感谢
