### ISSUE TITLE
🧐[问题]以下组件是否兼容ant3.x版本？

### ISSUE THREAD

**Issue by dengshicheng1996** [ant-design/pro-components#4858]
涉及相关组件：
1.  ProForm 高级表单
2. ProFormFields 表单项
3. 浮层表单
4. ProTable - 高级表格

项目依赖版本：
react：16.8  
ant ：3.20.0

疑问：
以上相关涉及的组件是否兼容3.x 版本的使用？如果使用的话对应组件的版本分别是多少？

**Comment by 1247748612** [comment]
均不支持

同步antd最新版本，目前4.19

**Comment by dengshicheng1996** [comment]
> 
protable 2.3.4支持，我知道这个2.4之前做过一次架构的升级仓库进行过迁移，但是其他的没有关注过
