### ISSUE TITLE
🧐[ProFormSelect 使用问题] 如何配置某个Option为disabled？

### ISSUE THREAD

**Issue by zjians** [ant-design/pro-components#486]
### 🧐 问题描述

使用ProFormSelect的时候，怎么控制某些Option选项为disabled呢？

**Comment by zjians** [comment]
其实我只是想使用QueryFilter自带的自适应布局效果，或者怎么单独使用自带的布局效果去渲染antd的Form.item，而不使用pro封装的组件，比如ProFormSelect，ProFormText这些。现在直接在QueryFilter中写Form.item的话不能实现自适应布局。

**Comment by chenshuai2144** [comment]
和 antd 用法一样的，配置一个 disable 就好了

**Comment by zjians** [comment]
> 和antd适当一样的，配置一个disable就好了

你意思是让我写renderFormItem吗，我意思是可以在options或者valueEnum的选项中支持disabled属性吗？比如[{ label: 'a', value: 'b', disabled: true }] 来禁用一个选项？

**Comment by chenshuai2144** [comment]
```
filedProps:{
  options:[]
}
```

可以这样，你的这个功能你可以提个 pr，倒是满常见的

**Comment by 15755037307** [comment]
下拉选择之后 怎么把选中参数全部 传过去 而不是只传参value
