### ISSUE TITLE
🐛[BUG]ProCard同时设置了tabs和extra显示错位

### ISSUE THREAD

**Issue by ldd27** [ant-design/pro-components#4862]
### 🐛 bug 描述

ProCard同时设置了tabs和extra显示错位
<img width="1686" alt="image" src="https://user-images.githubusercontent.com/11850305/158512655-0b3e1319-afa1-4de8-9785-0fcaae37ae74.png">

### 🏞 期望结果

tabs 和 extra在同一行展示

### 💻 复现代码

```jsx
    <ProCard
      tabs={{
        tabPosition: 'top',
        activeKey: tab,
        onChange: (key) => {
          setTab(key);
        },
      }}
      extra={<RedoOutlined />}
    >
      <ProCard.TabPane key="tab1" tab="tab1">
      </ProCard.TabPane>
      <ProCard.TabPane key="tab2" tab="tab2">
      </ProCard.TabPane>
      <ProCard.TabPane key="tab3" tab="tab3">
      </ProCard.TabPane>
    </ProCard>
```

### © 版本信息

- ProComponents 版本: @ant-design/pro-card@1.18.39
- umi 版本
- 浏览器环境
- 开发环境 mac OS

**Comment by DerrickTel** [comment]
extra 的内容放到
tabs={{
        tabPosition: 'top',
        activeKey: tab,
        onChange: (key) => {
          setTab(key);
        },
tabBarExtraContent:{放到这里}
      }}

**Comment by ldd27** [comment]
@DerrickTel 3q，已解决
