### ISSUE TITLE
🐛[BUG] File upload error 文件上传异常，405格式不正确

### ISSUE THREAD

**Issue by beautifure** [ant-design/pro-components#4868]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
使用文件上传组件，不配置文件上传路径，当文件上传后，返回405，官网API中组件也报错

链接：https://procomponents.ant.design/components/field-set

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by DerrickTel** [comment]
不是很理解你的问题是什么。为什么不配置呢？
