### ISSUE TITLE
🐛[BUG]. 紧急！！！！ 当前下载的包查询条件为空

### ISSUE THREAD

**Issue by jockey100332** [ant-design/pro-components#487]
### 🐛 bug 描述
当前开发环境下，所有的查询都是没有问题的，但是到生产环境导致 查询条件为空，在request 中 拿不到相对应的params。

刚开始我是2.7.2 的版本，现在回退到2.4.0.仍然不可以。紧急处理一下大佬，今天上线的

**Comment by chenshuai2144** [comment]
有复现的例子吗？

**Comment by jockey100332** [comment]
> 有复现的例子吗？
> 
> 看这个官方的 demo
> https://procomponents.ant.design/_demos/single

当前这个demo 也是存在问题的，按照状态查询出来的数据不正确

**Comment by hengkx** [comment]
测试没有问题🙃

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/93071903-51318480-f6b3-11ea-8643-1a7ebce72189.png)

**Comment by jockey100332** [comment]
> 测试没有问题🙃

当前版本是多少？这是版本所带来的兼容问题吗 
![image](https://user-images.githubusercontent.com/63291240/93080639-9c05c900-f6c0-11ea-9886-4712a1dc8f77.png)

**Comment by chenshuai2144** [comment]
你这个截图，成功避开了所有的有用信息
