### ISSUE TITLE
🐛[BUG] DragSortTable rowClassName not working

### ISSUE THREAD

**Issue by bakuryukhanh** [ant-design/pro-components#4873]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
修复了

**Comment by justLearner** [comment]
我在 2.x 版本里使用，设置 rowClassName 还是无效

**Comment by chenshuai2144** [comment]
搞个重现试试
