### ISSUE TITLE
EditableProTable在newRecordType: 'dataSource'模式下，字段onChange中editForm.setFieldsValue设置字段值，自动还原

### ISSUE THREAD

**Issue by zwjsoft** [ant-design/pro-components#4874]
可编辑表格EditableProTable，字一个字段修改时触发另外一个字段复制，当  newRecordType: 'dataSource'时，editForm.setFieldsValue执行后可以看到界面数字变成赋值后的值后，立即还原了？
代码如下：
import React, { useRef, useState } from 'react';
import type { ProColumns } from '@ant-design/pro-table';
import { EditableProTable } from '@ant-design/pro-table';
import type { ProFormInstance } from '@ant-design/pro-form';
import ProForm, { ProFormRadio, ProFormField, ProFormDependency } from '@ant-design/pro-form';
import {message,Modal,Divider,Form,Tabs } from 'antd';

type DataSourceType = {
  id: React.Key;
  title?: string;
  decs?: string
  state?: string;
  created_at?: string;
  update_at?: string;
  children?: DataSourceType[];
};

export default () => {
  const [editableKeys, setEditableRowKeys] = useState<React.Key[]>(() => []);
  const [currentRowKey,setCurrentRowKey]=useState() 
  const [position, setPosition] = useState<'top' | 'bottom' | 'hidden'>('bottom');
  const formRef = useRef<ProFormInstance<any>>();
  const [editForm] = Form.useForm()

  const columns: ProColumns<DataSourceType>[] = [
    {
      title: '活动名称',
      dataIndex: 'title',
      formItemProps: () => {
        return {
          rules: [{ required: true, message: '此项为必填项' }],
        };
      },
      width: '30%',
    },
    {
      title: 'id',
      dataIndex: 'id',
    },         
    {
      title: '状态',
      key: 'state',
      dataIndex: 'state',
      valueType: 'select',
      fieldProps:{
        onChange:()=>{
          debugger
          editForm.setFieldsValue({0:{decs:'aaaaaa'}})
        }
      },
      valueEnum: {
        all: { text: '全部', status: 'Default' },
        open: {
          text: '未解决',
          status: 'Error',
        },
        closed: {
          text: '已解决',
          status: 'Success',
        },
      },
    },
    {
      title: '描述',
      dataIndex: 'decs',
    },
    {
      title: '活动时间',
      dataIndex: 'created_at',
      valueType: 'date',
    },
    {
      title: '操作',
      valueType: 'option',
      width: 200,
      render: (text, record, _, action) => [
        <a
          key="editable"
          onClick={() => {
            action?.startEditable?.(record.id);
          }}
        >
          编辑
        </a>,
        <a
          key="delete"
          onClick={() => {
            const tableDataSource = formRef.current?.getFieldValue('table') as DataSourceType[];
            formRef.current?.setFieldsValue({
              table: tableDataSource.filter((item) => item.id !== record.id),
            });
          }}
        >
          删除
        </a>,
      ],
    },
  ];

  return (

    <ProForm>
      <ProForm.Item name='table'>
      <EditableProTable<DataSourceType>
        rowKey="id"
        headerTitle="可编辑表格"
        maxLength={5}

        controlled={true}
        recordCreatorProps={{
          newRecordType: 'dataSource',
          record: () => ({
            //id:new Date()
          }),
        }}        
        onRow={(record, index)=>{
          return {
            onClick: ()=>{
              debugger
              console.log(record,index)
              setCurrentRowKey(record?.id ? record?.id : index)
            }
        }
          
        }  
      }  
        columns={columns}
        editable={{
          type: 'multiple',
          form:editForm,
          editableKeys,
          onChange: (editableKeys)=>{
            debugger
            setEditableRowKeys(editableKeys)

          },
        }}
      />
</ProForm.Item>
</ProForm>

  );
};

**Comment by chenshuai2144** [comment]
感觉是闭包了，用的 ref 搞一下，防止闭包把。



```tsx
import { useCallback, useRef } from 'react';
const useRefFunction = <T extends (...args: any) => any>(reFunction: T) => {
  const ref = useRef<any>(null);
  ref.current = reFunction;
  return useCallback((...rest: Parameters<T>): ReturnType<T> => {
    return ref.current?.(...(rest as any));
  }, []);
};

export { useRefFunction };
```

```tsx
const change = useRefFunction(()=>{
  formRef.current?.setFieldsValue({
   table: tableDataSource.filter((item) => item.id !== record.id),
   });
})

change();
```

试试这样搞
