### ISSUE TITLE
🧐[问题] 如何更新表单的initialValue

### ISSUE THREAD

**Issue by jiangxiaoqiang** [ant-design/pro-components#4877]
### 🧐 问题描述

当props传入的值改变时，如何更新表单的值，现在只有第一次会更新，已经尝试了网络上提供的解决方案

https://stackoverflow.com/questions/61422607/update-antd-form-if-initialvalue-is-changed

### 💻 示例代码

https://stackoverflow.com/questions/71523100/how-to-refresh-the-antd-pro-proformtext-initialvalue

**Comment by 1247748612** [comment]
initialValues是做数据初始化的，后续的改动使用form.setFieldsValues和form.setFieldValue都是可以的

**Comment by jiangxiaoqiang** [comment]
我按照答案给的方法，可以刷新initialValues，它每次改变的时候重置，重新赋值，不过还有一个小小的问题： https://stackoverflow.com/questions/71523742/instance-created-by-useform-is-not-connected-to-any-form-element-forget-to-pa
