### ISSUE TITLE
🧐[问题] 求助 怎么给ProTable中表单的时间选择器设置 时间范围快捷按钮

### ISSUE THREAD

**Issue by ZXYT** [ant-design/pro-components#4886]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

怎么给ProTable中表单的时间选择器设置 时间范围快捷按钮

**Comment by chenshuai2144** [comment]
fieldProps 里面可以设置的

**Comment by ZXYT** [comment]
好的 谢谢大佬
