### ISSUE TITLE
🧐[问题] antd ConfigProvider 设置 componentSize 属性对 BetaSchemaForm 组件无效？

### ISSUE THREAD

**Issue by ming200854** [ant-design/pro-components#4889]
### 🧐 问题描述

BetaSchemaForm  无法通过 antd ConfigProvider 设置表单大小

### 💻 示例代码
https://codesandbox.io/s/v9hgfq?file=/App.tsx:0-795

**Comment by 1247748612** [comment]
确实是个bug。

另外可以使用size属性调整大小
