### ISSUE TITLE
🧐[问题] 如何在EditableProTable的onSave里面如何获得parentKey

### ISSUE THREAD

**Issue by peter064226** [ant-design/pro-components#4893]
### 🧐 问题描述

做了一个EditableProTable里面有children的树型结构，用EditableProTable.RecordCreator新建或保存child，在onSave中却拿不到parentKey

### 💻 示例代码

```jsx
<EditableProTable.RecordCreator
              parentKey={record.id}
              record={{
                en: '',
                zh: '',
              }}
              newRecordType="dataSource"
>
              <a>添加二级类名</a>
</EditableProTable.RecordCreator>

<EditableProTable
     editable={{
          type: 'single',
          onSave: async (key, record, originRow, newLineConfig) => {
            //上面四个参数里没有找到parentKey
            // 这里如何拿到parentKey
          },
        }}
/>
```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🌈 解决方案 

在EditableProTable.RecordCreator组件中传入的parentKey是用于新建子项时，通过该键值将新建的子项与其父项关联起来，不需要在onSave里获取到该键值。如果需要获得parentKey可以考虑在EditableProTable中添加额外的字段进行传递。

示例代码：

```jsx
<EditableProTable
  dataSource={dataSource}
  columns={columns}
  rowKey="id"
  editable={{
    type: 'single',
    onSave: async (key, record, originRow, newLineConfig) => {
      // 通过originRow中的parentKey获取父项的key
      const parentKey = originRow.parentKey;
      console.log(`parentKey: ${parentKey}`);
    },
  }}
  // 在EditableProTable中添加额外的字段传递parentKey
  extraActions={[
    <Button
      key="extraAction"
      onClick={() => {
        setParentKey('parent-key');
        tableActionRef.current?.createEditableRow?.();
      }}
    >
      添加根节点
    </Button>,
  ]}
/>
```

在 extraActions 中添加一个按钮，点击该按钮可以设置父项的key值，然后调用 createEditableRow 方法新建一行。当 onSave 触发时，通过 originRow 中的 parentKey 属性获得父项的key值。

### 📚 相关文档

- [EditableProTable API](https://protable.ant.design/api/editable-table#editable)
