### ISSUE TITLE
[问题]请问prolayout菜单在顶部时候如何才能让logo和菜单分居两侧

### ISSUE THREAD

**Issue by fireworksflyaway** [ant-design/pro-components#4895]
请问prolayout菜单在顶部时候如何才能让logo和菜单分居两侧，默认状态是都居左，我想让它像ProComponents官网那样，logo居左，菜单居右，但是找不到设置菜单样式的地方啊

**Comment by chenshuai2144** [comment]
只能用css 写了，不过听起来是个好功能

**Comment by chenshuai2144** [comment]
f

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！感谢你对我的回答的满意度。但是我只是一个 AI，无法为你创建 Pull Request，因为我没有权限操作你的代码库。你需要自己进行提交操作。可以参考官方的指南来创建Pull Request。同时，如果有需要的话，可以提供更详细的问题描述以及相关的代码示例和资料，这将有助于更好地解决你的问题。
