### ISSUE TITLE
🐛[BUG] ProField demo bug

### ISSUE THREAD

**Issue by Ashwin-op** [ant-design/pro-components#4896]
### 🐛bug description

Clicking on `edit` in the demo throws console error and page becomes unresponsive

### 📷Steps to reproduce

- Go to https://procomponents.ant.design/en-US/components/field#demo
- Click on the `edit` radio button as shown in the below image
![image](https://user-images.githubusercontent.com/60032753/159435534-3d010223-116c-478b-914c-4a27c907561e.png)
- Open console to check the error
![image](https://user-images.githubusercontent.com/60032753/159436086-65bede38-166c-47cd-8ff1-4bc6295c8144.png)

### © version information
- Browser: Chrome v99

🚑other information

**Comment by 1247748612** [comment]
work for me

**Comment by Ashwin-op** [comment]
Finally figured it out

Try to translate the site with Google Chrome (right-click on the site and choose "Translate to English"). You can see the error happening in the console, it's caused by Google Translate.

Related GitHub issue: https://github.com/facebook/react/issues/11538.
