### ISSUE TITLE
🐛[BUG] ProTable 的column 类型是dateTime的话，如果值是String类型,会显示Invalid date

### ISSUE THREAD

**Issue by believeZJP** [ant-design/pro-components#4897]
### 🐛 bug 描述

ProTable 的column 类型是dateTime的话，如果值是String类型,会显示Invalid date

### 📷 复现步骤
<img width="689" alt="image" src="https://user-images.githubusercontent.com/15198091/159495954-f5e6fe67-aa58-4de0-b2f6-f1fc4494d61e.png">

<img width="368" alt="image" src="https://user-images.githubusercontent.com/15198091/159496014-92f6d260-468a-42ab-9d6e-3bd4b1b7b25e.png">

### 🏞 期望结果

期望如果是字符串类型的话，能兼容，正常显示格式化的时间

所有这种时间转化的，是不是都可以直接转化一下

### 💻 复现代码

[复现链接](https://codesandbox.io/s/cha-xun-wu-an-niu-biao-ge-forked-teuk8d?file=/App.tsx)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by 1247748612** [comment]
不可以，这不是标准的时间格式，自己转吧
代码可不知道你的字符串时间戳是不是标准时间戳

**Comment by believeZJP** [comment]
我们目前遇到的问题是 通过long类型返回时间戳到前端，采用google的grpc框架，该框架使用proto协议，我们和google开发人员沟通，得到的答案是js的long类型是54位，而java后端的long类型是64位，直接从后端返回给前端会丢失精度，因此该框架会将long类型默认转换为string返回给前端（防止精度丢失），希望proTable组件可以兼容一下。

**Comment by 1247748612** [comment]
> 我们目前遇到的问题是 通过long类型返回时间戳到前端，采用google的grpc框架，该框架使用proto协议，我们和google开发人员沟通，得到的答案是js的long类型是54位，而java后端的long类型是64位，直接从后端返回给前端会丢失精度，因此该框架会将long类型默认转换为string返回给前端（防止精度丢失），希望proTable组件可以兼容一下。

原生 Date 就是不支持的

可以自己支持下，使用renderText把stirng转成number，像这样`renderText(time) => +time`试试

**Comment by chenshuai2144** [comment]
@believeZJP 接受 js 的奇怪限制吧
