### ISSUE TITLE
🐛[BUG]editable的表格，调用form滚动方法无法滚动至错误处

### ISSUE THREAD

**Issue by daisybaicai** [ant-design/pro-components#4899]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
在antd表单中，使用了editbTable，希望提交时校验表格，并且滚动至错误处,有触发校验，但无法滚动至错误处

### 📷 复现步骤

1.点击提交

### 🏞 期望结果
希望滚动至表格处

### 💻 复现代码
https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-u4xxr1?file=/App.jsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
好像支持不了这个功能，因为滚动条的位置算不出来。你是用了多长的表单吗？

**Comment by Yang-yibu** [comment]
> 好像支持不了这个功能，因为滚动条的位置算不出来。你是用了多长的表单吗？

我测试了这里的功能是可以的
