### ISSUE TITLE
🐛[BUG] 可编辑表格 EditableProTable 设置 rowClassName 属性无效

### ISSUE THREAD

**Issue by MircoSans** [ant-design/pro-components#4902]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

做了个可编辑拖拽表格，在给表格的行设置class时无效

``` html
<EditableProTable 
  rowClassName="test"
  components={{
                body: {
                    wrapper: DraggableContainer,
                    row: DraggableBodyRow,
                },
            }}
/>
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 
- 浏览器环境 edge chrome
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="692" alt="image" src="https://user-images.githubusercontent.com/51395487/159687889-00afad08-f185-4561-bc64-90add717d152.png">

**Comment by 1247748612** [comment]
正常的，目测你写的有问题
![image](https://user-images.githubusercontent.com/29533304/160083404-5b28733f-a198-41b7-b9e5-fadb7b9ca7e5.png)

![image](https://user-images.githubusercontent.com/29533304/160083501-415160eb-9a22-4325-a59d-610a84b3155f.png)

**Comment by MircoSans** [comment]
> 

好像加上拖拽的组件就不行了，我去创建个sandbox看看

**Comment by MircoSans** [comment]
好的找到问题了，是因为使用tuo拖拽把手的时候没把props穿进去
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/51395487/160091565-24cb4fa3-fd32-42ea-be14-8533cc18024f.png">
