### ISSUE TITLE
ProFormDateRangePicker组建返回值中如何去掉时间

### ISSUE THREAD

**Issue by caizhehao** [ant-design/pro-components#4906]
代码及页面效果如下：
![image](https://user-images.githubusercontent.com/26589188/159856391-532e5b31-4e85-44ee-8eb9-422ea384bbc9.png)
![image](https://user-images.githubusercontent.com/26589188/159856419-e2707ef6-26eb-4b25-b745-d79246a28332.png)
返回结果如下：
![image](https://user-images.githubusercontent.com/26589188/159856547-90aba366-2512-4913-99b8-4848f1ed4f1d.png)
问题如何设置ProFormDateRangePicker才能将返回结果中的时间去掉，只显示日期

**Comment by 1247748612** [comment]
看起来像个bug

**Comment by 1247748612** [comment]
![image](https://user-images.githubusercontent.com/29533304/160078063-ac0d906b-98a6-4b4b-83f0-d2cbfbd1f31c.png)

work的升级下版本，再试试
