### ISSUE TITLE
👑 [需求]EditableProTable多数据情况下，某列里配置renderFormItem支持动态切换时，表格内定义的下拉选择器收起速度较慢

### ISSUE THREAD

**Issue by youqiting** [ant-design/pro-components#4907]
### 🔩 所属模块或组件

可编辑表格：EditableProTable
### 🥰 需求描述

EditableProTable 根据A列值（A列是valueType: select配置），B列的renderFormItem里动态根据A列值切换显示dom时，A列的下拉选择器选择完成后，收起时间持续较久，迟钝2-3秒左右，期待优化下拉选择器收起的速度。

### ⛰ 功能需求适用场景

1.EditableProTable 表格数据非常多；
2. A列用表格定义的下拉选择器配置；
3. B列renderFormItem里动态根据A列值切换显示dom；

**Comment by 1247748612** [comment]
来个复现demo？
