### ISSUE TITLE
🐛[BUG]  ProFormTreeSelect fieldProps 提示没有　options　属性的类型错误，实际上有

### ISSUE THREAD

**Issue by backtolife2021** [ant-design/pro-components#4909]
![image](https://user-images.githubusercontent.com/24669431/159873469-fe2e0593-c1ff-4333-a6a2-130d5b7919f4.png)

see #4469

**Comment by 1247748612** [comment]
options与fieldProps同级，另外TreeSelect是使用`treeData`

**Comment by zlllya** [comment]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/6331020/195813800-f1e0d853-e02a-48f0-9a09-c96024ca8ebc.png">

fieldProps内的`treeData`没有效果，使用`options`可以，但是`options`没有声明类型

@ant-design/pro-components: 1.1.1
antd: 4.20.0
