### ISSUE TITLE
🐛[BUG]ProTable的columnsState参数中的onChange函数返回值有问题

### ISSUE THREAD

**Issue by kilik52** [ant-design/pro-components#4910]
### 🐛 bug 描述

关于ProTable的columnsState参数有两个Bug，第一个是文档错误。第二个是onChange函数返回值有问题。

### 📷 复现步骤

**一、文档错误(typo)**

链接地址： 

https://procomponents.ant.design/components/table/#protable

文档里面关于columnsState参数，写的是columnState，少了个s。类型写的是columnStateType，应该是ColumnsStateType。

**二、onChnage返回错误**

ColumnsStateType的onChange函数，函数定义是：

```typescript
(value:Record<string, ColumnsState>)=>void
```

但实际打印value，会发现如下图所示：

<img width="207" alt="截屏2022-03-24 下午4 35 59" src="https://user-images.githubusercontent.com/37238/159875674-d6577315-51a2-4764-969d-ad7bc3f5545f.png">

也就是说，这个value把数组和object合并了。并且这个数组里面的信息还有缺失，这样非常不方便使用者去遍历value里面的keys。

### 🏞 期望结果

1. 正确的文档
2. onChange的回调函数中，没有数组信息

### 💻 复现代码

打印下onChange就可以看到了，没什么特别的操作

### © 版本信息

- ProTable 版本: [v2.68.3]

**Comment by 1247748612** [comment]
![image](https://user-images.githubusercontent.com/29533304/160097531-b99a57e8-c8b5-441a-b3cd-4094a4c8b41c.png)

第二个问题没复现，建议升级版本后再试试，或提供个复现demo
![image](https://user-images.githubusercontent.com/29533304/160097577-1ff5845b-943e-43c6-816d-df4b47312fa7.png)

**Comment by kilik52** [comment]
> 第二个问题没复现，建议升级版本后再试试，或提供个复现demo ![image](https://user-images.githubusercontent.com/29533304/160097577-1ff5845b-943e-43c6-816d-df4b47312fa7.png)

用的就是你们官网的例子： https://procomponents.ant.design/components/table#%E6%9F%A5%E8%AF%A2%E8%A1%A8%E6%A0%BC


用codeSandbox fork出来后加了个onChange的回调，截图如下：
<img width="1434" alt="截屏2022-03-25 下午9 37 55" src="https://user-images.githubusercontent.com/37238/160132101-0c0351ba-0e24-4d0a-8e0d-1a1dc2cc5911.png">


codeSandbox地址为：

https://codesandbox.io/s/cha-xun-biao-ge-forked-dsbf3i?file=/App.tsx

**Comment by 1247748612** [comment]
确实存在，问题在于默认只取了column中的key做索引名，调整一下取key和dataIndex做索引名
