### ISSUE TITLE
🐛[BUG]Field 日期格式季度输入， 显示和实际输入不一致。

### ISSUE THREAD

**Issue by oneplusonecy** [ant-design/pro-components#4912]
🐛 bug 描述
日期格式季度输入， 显示和实际输入不一致。

📷 复现步骤
https://procomponents.ant.design/components/schema/#valuetype-%E5%88%97%E8%A1%A8
选择季度输入类型，选择具体季度界面显示2022-Q2，实际控制台打印2022-22。

🏞 期望结果
显示与实际一直。显示2022-Q2 ，输出2022-Q2，非2022-22

💻 复现代码
© 版本信息
ProComponents 版本: [e.g. 4.0.0]
umi 版本
浏览器环境
开发环境 [e.g. mac OS]
🚑 其他信息

**Comment by tonywu6** [comment]
https://github.com/ant-design/pro-components/blob/4e297e6d1cf05973561b5056a6f9c270d00b3e8b/packages/utils/src/conversionMomentValue/index.ts#L19

utils 中负责打印 moment 日期值的函数使用的 format string 缺失了一个斜线 \ 导致

```
YYYY-\QQ → 2022-Q1
YYYY-QQ → 2022-11
```
