### ISSUE TITLE
🧐[问题]edittableprotable如何关掉提示框不显示校验提示框

### ISSUE THREAD

**Issue by jingxiawl** [ant-design/pro-components#4914]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
在edittableprotable里面使用了以下组件，因为加了disable的原因，导致校验提示一直不消失，如何有方法能关闭校验提示。或者直接不显示
```javascript
<ProFormText
        name={id}
        disabled
        placeholder="请选择"
        fieldProps={{
          addonAfter: <div onClick={() => setVisible(true)}>选择</div>,
        }}
      />
```

### 💻 示例代码

![image](https://user-images.githubusercontent.com/11657532/160048040-ef81b14f-f6ba-4b6c-a763-f5064d5e22b7.png)

**Comment by chenshuai2144** [comment]
不能去掉 rule 吗？

**Comment by jingxiawl** [comment]
> 不能去掉 rule 吗？
就是因为要校验必填。去掉rule就没法校验必填了，但是写了rule之后那个提示就永远消失不了了

**Comment by chenshuai2144** [comment]
在 formItem 里面配置 popoverProps


visible设置位  false

**Comment by KamChing** [comment]
> 在 formItem 里面配置 popoverProps
> 
> visible设置位 false

上了生产环境之后不生效是为啥
