### ISSUE TITLE
👑 [需求] valueType treeSelect 大多数值都是Number,但现在必须要求string  不知道怎么转

### ISSUE THREAD

**Issue by hanwenbo** [ant-design/pro-components#4918]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

让valueType 支持number的值，或者提供一个可以转value类型的方法

### 🥰 需求描述

我认为大多数后端都和我一样习惯把分类的字段设计为索引的id，但是在antd上tree select必须是string的值，用默认的antd写法比较容易，外面改变value类型就行了，但是在protable中怎么做呢？renderFormItem里我在代码最外层过滤所有的id为 `${item.id}`来解决强行要求string 的问题

```
 {
      title: '标题',
      dataIndex: 'title',
      valueType: 'textarea',
      width: 300,
    },
    {
      title: '分类',
      dataIndex: 'tid',
      valueType: 'treeSelect',
      renderFormItem: () => {
        return <TreeSelect
          multiple={true}
          treeData={categoryTree}
          fieldNames={{label: 'title', value: 'id', children: 'children'}}
          placeholder="请选择上级节点"
          style={{
            width: 200
          }}
        />
      },
    },
```

**Comment by 1247748612** [comment]
没看明白你想表达什么

目前就单看你的代码。不用使用renderFormItem改成这样就行
```typescript
 {
      title: '标题',
      dataIndex: 'title',
      valueType: 'textarea',
      width: 300,
    },
    {
      title: '分类',
      dataIndex: 'tid',
      valueType: 'treeSelect',
      fieldProps: {
        options: categoryTree,
        multiple: true,
        fieldNames: {label: 'title', value: 'id', children: 'children'},
        placeholder: "请选择上级节点",
        style: {
            width: 200
        },
      }
    },
```

**Comment by hanwenbo** [comment]
@1247748612 不行吧  默认展示出来是数字    应该是 对应的label才对

**Comment by hanwenbo** [comment]
这个问题   我用了2年都存在 只是一直没反馈

**Comment by 1247748612** [comment]
这个 valueType: 'treeSelect' 我好像是今年才实现的

**Comment by chenshuai2144** [comment]
他的问题应该是 obj 自动会把 number 转化成数字，后端喜欢用数字。

你可以用renderText toString 一下，提交的时候再转化一把。 不过说实话用 数字表示枚举是很偷懒的行为，现在的数据库已经没那么紧张了

**Comment by li379395535** [comment]
> 他的问题应该是 obj 自动会把 number 转化成数字，后端喜欢用数字。
> 
> 你可以用renderText toString 一下，提交的时候再转化一把。 不过说实话用 数字表示枚举是很偷懒的行为，现在的数据库已经没那么紧张了

ts枚举的枚举默认值都是number吧。。。哪里偷懒了。。
