### ISSUE TITLE
🧐[江湖救急！！！]新建-输入控件为啥默认最大宽度328px

### ISSUE THREAD

**Issue by gameruleCEO** [ant-design/pro-components#492]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/32796170/93157027-f859fe80-f73b-11ea-891d-1ae352c91e8b.png)

table组件(v2.7.1)-新建操作即type="form"的时候，为啥输入控件给了默认最大宽度328px？在哪里可以改？

**Comment by chenshuai2144** [comment]
```
filedProps:{
  width:"m"
}
```

https://procomponents.ant.design/components/form#%E9%80%9A%E7%94%A8%E7%9A%84%E5%B1%9E%E6%80%A7

**Comment by gameruleCEO** [comment]
> 可以这样
> 
> ```
> filedProps:{
>   width:"m"
> }
> ```
> 
> https://procomponents.ant.design/components/form#%E9%80%9A%E7%94%A8%E7%9A%84%E5%B1%9E%E6%80%A7

这个写到filedProps不好使呢，写到formItemProps里才行
