### ISSUE TITLE
ProTable 全屏无效

### ISSUE THREAD

**Issue by jwmxushang** [ant-design/pro-components#4920]
### Reproduction link

[https://pro.jwmyun.com/](https://pro.jwmyun.com/)

### Steps to reproduce

ProTable 全屏无效在QQ/360等浏览器下点击无反应，在谷歌、火狐及Edge下好使

### What is expected?

ProTable 全屏无效在QQ/360等浏览器下点击无反应，在谷歌、火狐及Edge下好使

### What is actually happening?

ProTable 全屏无效在QQ/360等浏览器下点击无反应，在谷歌、火狐及Edge下好使

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | win10 |
| Browser | QQ,360极速模式 |

**Comment by chenshuai2144** [comment]
这个 API 的兼容不是很好，360 QQ 这种超级低版本的浏览器估计不行。

<img width="834" alt="image" src="https://user-images.githubusercontent.com/8186664/160319435-cec62880-6951-4227-b351-264f1f8c5030.png">

换个实现方式吧
