### ISSUE TITLE
👑 [需求] Able to replace the text of botton "登 录" to "Login"

### ISSUE THREAD

**Issue by zhenlizhong** [ant-design/pro-components#4928]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件
LoginForm 
import { LoginForm, } from '@ant-design/pro-form';

### 🥰 需求描述

The login button cannot customize the text, default text is "登 录".

### ⛰ 功能需求适用场景
there is a need for internationalization

### 🧐 解决方案
The button text can be passed to the parent component by propping

### 🚑 其他信息
https://procomponents.ant.design/components/form
<img width="421" alt="image" src="https://user-images.githubusercontent.com/85025370/160210410-bfece85d-af86-4f34-9c73-ca351e98c79c.png">

**Comment by AntonioVentilii** [comment]
Hello,

It doesn't seem to be solved... how can I pass the text of the login button?

**Comment by chenshuai2144** [comment]
you can use `submitter` props.

**Comment by shkim** [comment]
submitter={{ searchConfig: { submitText: "Login" } }}

**Comment by AntonioVentilii** [comment]
shouldn't it be automatic once i choose the local EN?
