### ISSUE TITLE
🐛[BUG]ProLayout-Next和Umi-Next配合使用中的几个问题

### ISSUE THREAD

**Issue by Iveon** [ant-design/pro-components#4933]
### © 版本信息

"@ant-design/pro-layout": "7.0.1-beta.11",
"@umijs/max": "4.0.0-rc.9",

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/21276534/160232139-87ac8520-ef7c-423b-a583-4deb640bc681.png)

### 🐛 bug 描述

如上图所示:

1. 在config中的配置只有title生效了,其他的比如layout、iconfontUrl等设置都无效
2. 我通过export const layout运行时设置layout、iconfontUrl等都有效
3. 我在运行时中设置了avatarProps，但是默认的蓝色小蚂蚁依然存在。

**Comment by Iveon** [comment]
换了一种方式来实现，config中直接不做配置。
在运行时中导入setting的配置数据。

**Comment by Iveon** [comment]
![image](https://user-images.githubusercontent.com/21276534/160237814-7c0045a7-0405-48c1-933d-dc3414c5713f.png)
@chenshuai2144 可不可把渐变颜色去了，或者把这个背景色的设定开放出来？
这个渐变真的太丑了....token中layoutBgColor这个效果我设置了完全没有任何变化。

**Comment by chenshuai2144** [comment]
可以来个pr。 

设计师很喜欢这个渐变的设计，逼着我做的

**Comment by mashirozx** [comment]
avatarProps我设置了无效啊QAQ

**Comment by ywzou** [comment]
mix 模式 avatarProps和actionsRender均无效

**Comment by xptela** [comment]
@chenshuai2144 大半年过去了，这个问题还是存在，是由什么含义吗？
![image](https://user-images.githubusercontent.com/102938946/200236131-6ee4c16f-3919-4881-a525-43c83519abc4.png)

**Comment by xptela** [comment]
> 

@chenshuai2144  umi-plugin-layout-right 貌似是umi中的 我没有引入这个插件....

**Comment by chenshuai2144** [comment]
rightRender 设置成false好了
