### ISSUE TITLE
🐛[BUG] [ProFormSelect] valueEnum wrong write

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/pro-components#4937]
While there are no errors in my other ProFormSelect Enums, but it writes zero in the input here.

The problem is that the value of the status field is integer, when I convert it to string, the problem is fixed, but it should accept it as an integer.

![status](https://user-images.githubusercontent.com/6988989/160295189-da2c0750-c90a-41e4-90d8-35095594f455.png)
```
 // Initial Values
  useEffect(() => {
    formRef.current?.setFieldsValue(receipt);
  }, [receipt]);


        <ProFormSelect
          label="Status"
          name="status"
          width="lg"
          valueEnum={{
            0: 'Paid',
            1: 'NotPaid',
            2: 'HalfPaid'),
          }}
        />
```

**Comment by weicong** [comment]
增加 convertValue={(value) => `${value}`} 
`
        <ProFormSelect
          label="Status"
          name="status"
          width="lg"
          valueEnum={{
            0: 'Paid',
            1: 'NotPaid',
            2: 'HalfPaid'),
          }}
          **convertValue={(value) => `${value}`}**
        />
`
