### ISSUE TITLE
🐛[BUG]ProForm.Item 设置自定义组件的宽度不生效

### ISSUE THREAD

**Issue by believeZJP** [ant-design/pro-components#4938]
自定义组件的宽度希望和ProFromText的宽度一样通过配置设置宽度一样宽
<img width="559" alt="image" src="https://user-images.githubusercontent.com/15198091/160326104-2be369ba-2f8a-4cf5-8193-57c0a61c5a05.png">

### 📷 复现步骤
```js
//这个是ProFrom表单项都有的宽度，width='md'

 <ProFormText width="md" name="name" label="name" />

//这个是自定义表单项，怎么设置宽度和width='md'一样宽
  <ProForm.Item name="name2" label="name2" width="md">
    <Input width="md" />
  </ProForm.Item>
```

### 🏞 期望结果
两个组件宽度保持一致

### 💻 复现代码

[复现代码](https://codesandbox.io/s/biao-dan-xiang-forked-x88j5g?file=/App.tsx:387-549)
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by 1247748612** [comment]
像sm, md这种宽度只有Pro有，且不支持在ProForm.Item中使用
