### ISSUE TITLE
🐛[BUG] pro-list升级后metas中的部分内容不显示

### ISSUE THREAD

**Issue by 7937505** [ant-design/pro-components#4939]
升级前：
![1648441533491](https://user-images.githubusercontent.com/19165229/160326860-01cbbfaf-e2c2-4be9-aa66-5e59f142ecfa.jpg)

升级后：
![1648441454950](https://user-images.githubusercontent.com/19165229/160326884-45c981ae-8b13-456e-992e-30dd32f69068.jpg)

**Comment by zhengby** [comment]
遇到同样问题，求跟进
