### ISSUE TITLE
🧐 ProTable 搜索表单能否回车提交？

### ISSUE THREAD

**Issue by zhang0ZGC** [ant-design/pro-components#494]
### 🧐 问题描述
ProTable 搜索表单能否回车快速提交搜索？而不是点击查询按钮

**Comment by chenshuai2144** [comment]
这个需求还是蛮合理的

**Comment by fangzhengjin** [comment]
之前版本是有回车查询这个功能的, 但是更新之后...没 有 了

**Comment by zhang0ZGC** [comment]
> 之前版本是有回车查询这个功能的, 但是更新之后...没 有 了

以前可以回车查询主要是取决于` Form` 表单里面的`Button` 组件是否设置了 `htmlType="submit"` 属性

**Comment by gaoxianglyx** [comment]
是的，更新后不能回车搜索了，希望能加上

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/883
