### ISSUE TITLE
👑 [需求] ProForm  <ProFormSelect /> 默认request

### ISSUE THREAD

**Issue by lifegit** [ant-design/pro-components#4940]
### 🔩  ProForm

ProFormSelect

### 🥰 需求描述

目前进入页面时 ProFormSelect 会直接调用 request 方法。在大表单场景会请求非常多个接口，这对于后端来讲压力比较大。

### ⛰ 功能需求适用场景

1. 进入编辑表单，直接请求request渲染默认数据。
2. 进入新建表单，不请求request。当用户点击select组件时，启用loading，同时request。

### 🧐 解决方案

存在initialValue时，再请求request来渲染默认数据。

### 🚑 其他信息

<img width="2347" alt="image" src="https://user-images.githubusercontent.com/33006878/160328047-2257ef88-955a-4935-9bd8-93a1b67d8542.png">

**Comment by lifegit** [comment]
如果觉得这个建议不错，我可以来修复这个问题。

**Comment by 1247748612** [comment]
为何是存在initialValue时请求request，如果就是没有初始值也需要请求接口。

你的想法是想实现类似懒加载的行为吧，需要的时候再请求接口，这里的request不只是在表单中会使用，table也需要而且是要立马展示出来的，可能不太容易实现

枚举的接口一般都很小，而且有缓存只需要请求一次就可以了，对于后端的压力可以忽略不记，如果这就把后端服务搞炸了，应该先优化后端接口服务

**Comment by lifegit** [comment]
@1247748612 

1. table 指的是在search中吗？
2. 通常要考虑到搜索一个用户、员工，等业务数据（实际是进行一个列表带条件的的查询）。

**Comment by 1247748612** [comment]
table search 也是表单，我指的是表格中的内容也用到了request
类似这种查询的接口我的做法是，限制返回数量如20条数据，然后模糊搜索匹配的方式去查找是更好的方案，返回太多的数据也是不好找的

**Comment by 1247748612** [comment]
你可以尝试下能不能做到按需请求的功能，确实可以优化下性能

**Comment by lifegit** [comment]
> 我指的是表格中的内容也用到了request
1. 这个您可以举个例子吗？
> 你可以尝试下能不能做到按需请求的功能，确实可以优化下性能。
3. 是的，现在确实是按需请求的。你可以从图中看到分页 `current=1&pageSize=5`

**Comment by 1247748612** [comment]
> 1. 这个您可以举个例子吗？

https://codesandbox.io/s/cha-xun-biao-ge-forked-ywss14?file=/App.tsx

是的，现在确实是按需请求的。你可以从图中看到分页 `current=1&pageSize=5`

可以在pro-components实现下

**Comment by lifegit** [comment]
1. 您指的是在表格的编辑状态下，对吧？

**Comment by 1247748612** [comment]
> 1. 您指的是在表格的编辑状态下，对吧？

不是的，展示下也会使用的，因为表格中有些数据只会返回id这种唯一的标识。如果你想人能看懂，你就可以使用request，返回id所对应的label展示

**Comment by lifegit** [comment]
明白了，您上述例子指的是 columns.dataIndex === 'state' 的render，使用到的 request。

**Comment by 1247748612** [comment]
> 明白了，您上述例子指的是 columns.dataIndex === 'state' 的render，使用到的 request。

是的

**Comment by lifegit** [comment]
嗯嗯，明白您的意思啦！明后天研究下。
