### ISSUE TITLE
🧐[问题] proForm 的某个表单项在其他位置,如何关联?

### ISSUE THREAD

**Issue by Valar103769** [ant-design/pro-components#4941]
接口所需要的搜索项数据,来自于头部的formForm,和table右侧的下拉选项

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/36926073/160328411-8e41466f-cc8d-42a2-bdf2-e2b0244af071.png">
请问proForm能关联proForm组件外部的表单项吗?
 因为 proForm里能支持valueType,对于外部是时间选择器的情况,直接获取字符串,比较方便

**Comment by 1247748612** [comment]
无法关联外部的Form

但可以使用useState管理
