### ISSUE TITLE
🧐[问题]5.0.17版本的pro-layout在不升级版本的前提下可以实现左侧菜单栏的手动折叠与展开吗？

### ISSUE THREAD

**Issue by NikitaChrn** [ant-design/pro-components#4942]
如果可以的话，具体要如何实现呢？
![image](https://user-images.githubusercontent.com/75491296/160346162-f7d46b69-c836-4f14-a028-92c0b3315e39.png)

**Comment by chenshuai2144** [comment]
api应该是有的。 去看看 layout 的源码。

用法应该和demo是相同的
