### ISSUE TITLE
🐛[BUG]我在移动端点击菜单之后,菜单不会自动收回去。我尝试使用menu的autoClose参数，但是不生效。不知道这个有什么解决方案。

### ISSUE THREAD

**Issue by tankpanv** [ant-design/pro-components#4946]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
你好，我之前在discussions里提过一个问题，"我在移动端点击菜单之后,菜单不会自动收回去。我尝试使用menu的autoClose参数，但是不生效。不知道这个有什么解决方案。" 我查看了相关文档以及以往的issue。虽然可能可以通过设置collapsed 收回菜单。但是由于我使用的是antd pro 5 ，我了解到似乎antd pro 5只可以通过配置修改layout的信息。关于对应如何配置判断是否是移动端，然后再判断点击菜单项操作，动态设置collapsed 的问题 我没找到好的解决方案。希望官方可以跟进解决一下这个问题

### 🏞 期望结果
在移动端点击菜单栏跳转到路由页面后，菜单栏自动关闭

### © 版本信息

- ProComponents 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/13927744/160431420-c9f67483-49f9-4699-9f30-ebd4000f34a4.png)

![image](https://user-images.githubusercontent.com/13927744/160431144-887d41ad-b15c-4785-90eb-dd7e38f3b5f2.png)

**Comment by chenshuai2144** [comment]
是专门这么做的，用户点错之后需要三步才能再次点击。

你可以在 menuItemRender 里面掉用一下 setCollapsed 强制关掉
