### ISSUE TITLE
🐛[BUG] 使用ProFormTreeSelect时，当一个父项的所有子项均为禁用，即disabled=true时，父项可以选择，但是选择框里不会显示

### ISSUE THREAD

**Issue by CementSealing** [ant-design/pro-components#4949]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

 使用ProFormTreeSelect时，当一个父项的所有子项均为禁用，即disabled=true时，父项可以选择，但是选择框里不会显示

### 📷 复现步骤

`<ProFormTreeSelect
  name="name"
  placeholder="Please select"
  allowClear
  width={330}
  secondary
  request={async () => {
    return [
      {
        title: 'Node1',
        value: '0-0',
        children: [
          {
            title: 'Child Node1',
            value: '0-0-0',
            disabled: true,
          },
        ],
      },
      {
        title: 'Node2',
        value: '0-1',
        children: [
          {
            title: 'Child Node3',
            value: '0-1-0',
          },
          {
            title: 'Child Node4',
            value: '0-1-1',
          },
          {
            title: 'Child Node5',
            value: '0-1-2',
          },
        ],
      },
    ];
  }}
  // tree-select args
  fieldProps={{
    showArrow: false,
    filterTreeNode: true,
    showSearch: true,
    dropdownMatchSelectWidth: false,
    labelInValue: true,
    autoClearSearchValue: true,
    multiple: true,
    treeNodeFilterProp: 'title',
    fieldNames: {
      label: 'title',
    },
  }}
/>`

### 🏞 期望结果

无论一个选项的子项是否可选，当选择这个选项时，它的title都能显示在选择框中。

### © 版本信息

- ProComponents 版本: "@ant-design/pro-form": "^1.51.0",
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![图片](https://user-images.githubusercontent.com/97492682/160512912-c8658520-abc0-4a00-87d9-f3a9903f3980.png)

**Comment by DerrickTel** [comment]
升级看看。

https://user-images.githubusercontent.com/24643779/160555638-14704ac2-6349-43c5-9745-5de835b824c5.mp4

**Comment by CementSealing** [comment]
> 升级看看。
> QQ20220329-151847-HD.mp4

升级之后可以了，谢谢
