### ISSUE TITLE
🐛[BUG] pro-table 组件的自定义搜索 renderformItem中formitem不能很好的使用嵌套结构

### ISSUE THREAD

**Issue by kcunitary** [ant-design/pro-components#495]
### 🐛 bug 描述

自定义搜索使用了select+input组合，想把结果组合成一个对象，结果request结果中的select传递参数完全错乱。

### 📷 复现步骤

第一次选择select后，再去输入input会清空select的选择，再重新选择select后，提交后变成了list的键值对。

### 🏞 期望结果

把select 和input的值包装成一个对象，传递给request里

### 💻 复现代码
```
      renderFormItem: (item, {defaultRender,...rest}, form) => {
        console.log('item:',item)
        console.log('config:',{...rest})
        console.log('form:',form)
        return (

           <Form.Item {...rest} label="" >
           <Input.Group compact>

            <Form.Item 
            name={['registeredInfo','type']}
            >
              <Select >
              <Option value={1}>11</Option>
              <Option value={2}>22</Option>
              </Select>
            </Form.Item>
            <Form.Item name={['registeredInfo','searchTxt']}>
              <Input />
            </Form.Item>
            </Input.Group>
            </Form.Item>

        )
```
### © 版本信息

- ProComponents 版本: "@ant-design/pro-table": "^2.7.2",
- umi 版本:"umi": "^3.2.20",
- 浏览器环境:chrome
- 开发环境 :arch linux

### 🚑 其他信息

![截屏2020-09-15 上午10 45 39](https://user-images.githubusercontent.com/20908273/93159457-cb5c1a80-f740-11ea-9eae-4cce73269a06.png)

**Comment by chenshuai2144** [comment]
这个需要自己封装的，你需要先支持 value 和 onChange 。

这个的用法和antd的 formItem 是相同的
