### ISSUE TITLE
🧐[问题]EditableProTable中当我保存的时候是否可以拦截，修改保存得数据

### ISSUE THREAD

**Issue by sysysy-byte** [ant-design/pro-components#4950]
EditableProTable中当我保存的时候是否可以拦截，修改保存得数据

**Comment by 1247748612** [comment]
目前没有比较好的方案

**Comment by chenshuai2144** [comment]
现在还没有方案，因为 save 之后可能id不一样，会导致表格发生比较大的变化。
这里推荐直接 reload 整个 table

**Comment by 110635164** [comment]
我直接在onSave那里throw new Error("xxx")😊
