### ISSUE TITLE
如何将布局设置图标隐藏然后再系统设置中显示

### ISSUE THREAD

**Issue by changlin0501** [ant-design/pro-components#4952]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

如何将布局设置图标隐藏然后再系统设置中显示
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/47729295/160546052-03b9448c-9061-45c7-a416-14d09e087041.png)
![image](https://user-images.githubusercontent.com/47729295/160546136-4dfd366a-6bed-4251-9d15-bdaf6ee9009d.png)

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/layout#settingdrawer

<html>
<body>
<table style="box-sizing: border-box; border: 1px solid rgb(63, 65, 65); border-collapse: collapse; max-width: 100vw !important; width: 912px;"><thead style="box-sizing: border-box;"><tr style="box-sizing: border-box;"><th style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65); font-weight: 600; background: rgb(39, 40, 39); white-space: nowrap;">参数</th><th style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65); font-weight: 600; background: rgb(39, 40, 39); white-space: nowrap;">说明</th><th style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65); font-weight: 600; background: rgb(39, 40, 39); white-space: nowrap;">类型</th><th style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65); font-weight: 600; background: rgb(39, 40, 39); white-space: nowrap;">默认值</th></tr></thead><tbody style="box-sizing: border-box;"><tr style="box-sizing: border-box;"><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65); font-weight: 500;">settings</td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);">layout 的设置</td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);"><a href="https://procomponents.ant.design/components/layout#Settings" style="box-sizing: border-box; color: rgb(97, 144, 198); text-decoration: none; background-color: transparent; outline: none; cursor: pointer; transition: opacity 0.2s ease 0s; touch-action: manipulation;"><code style="box-sizing: border-box; font-size: 1em; font-family: Consolas, Monaco, &quot;andale mono&quot;, &quot;ubuntu mono&quot;, monospace; padding: 2px 5px; color: rgb(204, 112, 108); background: rgb(40, 41, 41);">Settings</code></a><span> </span>|<span> </span><a href="https://procomponents.ant.design/components/layout#Settings" style="box-sizing: border-box; color: rgb(97, 144, 198); text-decoration: none; background-color: transparent; outline: none; cursor: pointer; transition: opacity 0.2s ease 0s; touch-action: manipulation;"><code style="box-sizing: border-box; font-size: 1em; font-family: Consolas, Monaco, &quot;andale mono&quot;, &quot;ubuntu mono&quot;, monospace; padding: 2px 5px; color: rgb(204, 112, 108); background: rgb(40, 41, 41);">Settings</code></a></td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);">-</td></tr><tr style="box-sizing: border-box;"><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65); font-weight: 500;">onSettingChange</td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);"><a href="https://procomponents.ant.design/components/layout#Settings" style="box-sizing: border-box; color: rgb(97, 144, 198); text-decoration: none; background-color: transparent; outline: none; cursor: pointer; transition: opacity 0.2s ease 0s; touch-action: manipulation;"><code style="box-sizing: border-box; font-size: 1em; font-family: Consolas, Monaco, &quot;andale mono&quot;, &quot;ubuntu mono&quot;, monospace; padding: 2px 5px; color: rgb(204, 112, 108); background: rgb(40, 41, 41);">Settings</code></a><span> </span>发生更改事件</td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);"><code style="box-sizing: border-box; font-size: 1em; font-family: Consolas, Monaco, &quot;andale mono&quot;, &quot;ubuntu mono&quot;, monospace; padding: 2px 5px; color: rgb(204, 112, 108); background: rgb(40, 41, 41);">(settings: [</code>Settings<code style="box-sizing: border-box; font-size: 1em; font-family: Consolas, Monaco, &quot;andale mono&quot;, &quot;ubuntu mono&quot;, monospace; padding: 2px 5px; color: rgb(204, 112, 108); background: rgb(40, 41, 41);">](#Settings) ) =&gt; void</code></td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);">-</td></tr><tr style="box-sizing: border-box;"><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65); font-weight: 500;">hideHintAlert</td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);">删除下方的提示信息</td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);"><code style="box-sizing: border-box; font-size: 1em; font-family: Consolas, Monaco, &quot;andale mono&quot;, &quot;ubuntu mono&quot;, monospace; padding: 2px 5px; color: rgb(204, 112, 108); background: rgb(40, 41, 41);">boolean</code></td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);">-</td></tr><tr style="box-sizing: border-box;"><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65); font-weight: 500;">hideCopyButton</td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);">不展示 copy 功能</td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);"><code style="box-sizing: border-box; font-size: 1em; font-family: Consolas, Monaco, &quot;andale mono&quot;, &quot;ubuntu mono&quot;, monospace; padding: 2px 5px; color: rgb(204, 112, 108); background: rgb(40, 41, 41);">boolean</code></td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);">-</td></tr><tr style="box-sizing: border-box;"><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65); font-weight: 500;">disableUrlParams</td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);">禁止同步设置到查询参数</td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);"><code style="box-sizing: border-box; font-size: 1em; font-family: Consolas, Monaco, &quot;andale mono&quot;, &quot;ubuntu mono&quot;, monospace; padding: 2px 5px; color: rgb(204, 112, 108); background: rgb(40, 41, 41);">boolean</code></td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);"><code style="box-sizing: border-box; font-size: 1em; font-family: Consolas, Monaco, &quot;andale mono&quot;, &quot;ubuntu mono&quot;, monospace; padding: 2px 5px; color: rgb(204, 112, 108); background: rgb(40, 41, 41);">false</code></td></tr><tr style="box-sizing: border-box;"><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65); font-weight: 500;">enableDarkTheme</td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);">打开黑色主题切换功能 ｜<span> </span><code style="box-sizing: border-box; font-size: 1em; font-family: Consolas, Monaco, &quot;andale mono&quot;, &quot;ubuntu mono&quot;, monospace; padding: 2px 5px; color: rgb(204, 112, 108); background: rgb(40, 41, 41);">boolean</code></td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);"><code style="box-sizing: border-box; font-size: 1em; font-family: Consolas, Monaco, &quot;andale mono&quot;, &quot;ubuntu mono&quot;, monospace; padding: 2px 5px; color: rgb(204, 112, 108); background: rgb(40, 41, 41);">false</code></td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65);"></td></tr><tr style="box-sizing: border-box;"><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65); font-weight: 500; color: rgb(179, 171, 158); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(36, 37, 37); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">colorList</td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65); color: rgb(179, 171, 158); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(36, 37, 37); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">自带的颜色切换系统 ｜<span> </span><code style="box-sizing: border-box; font-size: 1em; font-family: Consolas, Monaco, &quot;andale mono&quot;, &quot;ubuntu mono&quot;, monospace; padding: 2px 5px; color: rgb(204, 112, 108); background: rgb(40, 41, 41);">{key,color}[]</code></td><td style="box-sizing: border-box; padding: 10px 24px; border: 1px solid rgb(63, 65, 65); color: rgb(179, 171, 158); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(36, 37, 37); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code style="box-sizing: border-box; font-size: 1em; font-family: Consolas, Monaco, &quot;andale mono&quot;, &quot;ubuntu mono&quot;, monospace; padding: 2px 5px; color: rgb(204, 112, 108); background: rgb(40, 41, 41);">ColorList</code></td><br class="Apple-interchange-newline">
</body>
</html>参数	说明	类型	默认值
settings	layout 的设置	[Settings](https://procomponents.ant.design/components/layout#Settings) | [Settings](https://procomponents.ant.design/components/layout#Settings)	-
onSettingChange	[Settings](https://procomponents.ant.design/components/layout#Settings) 发生更改事件	(settings: [Settings](#Settings) ) => void	-
hideHintAlert	删除下方的提示信息	boolean	-
hideCopyButton	不展示 copy 功能	boolean	-
disableUrlParams	禁止同步设置到查询参数	boolean	false
enableDarkTheme	打开黑色主题切换功能 ｜ boolean	false	
colorList	自带的颜色切换系统 ｜ {key,color}[]	ColorList




用   collapse?: boolean;   和  onCollapseChange?: (collapse: boolean) => void; 来控制
