### ISSUE TITLE
🐛[BUG] 请求没有返回之前再次触发reloadAndRest，不发请求

### ISSUE THREAD

**Issue by KellenHe** [ant-design/pro-components#4953]
protable版本是2.57.2

触发reloadAndRest后查询接口有点慢，如果没有返回之前再次reloadAndRest，不会发出请求。

请问这个要怎么处理？

**Comment by KellenHe** [comment]
@chenshuai2144 大佬有什么方法吗，这个好像是表格内部管理的状态。

**Comment by chenshuai2144** [comment]
fetch 是不支持打断的，所以你必须等前一个请求回来，不然整个table的数据会乱掉
