### ISSUE TITLE
🐛[BUG]ProList 在antd@4.19.4下，数据不显示以及样式严重错位的情况

### ISSUE THREAD

**Issue by vVvlife** [ant-design/pro-components#4955]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProList 在antd@4.19.4下，数据不显示以及样式严重错位的情况

### 📷 复现步骤

复现例子：
https://codesandbox.io/s/ji-ben-shi-yong-forked-c69pd4?file=/index.tsx

### 🏞 期望结果

恢复正常

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] ProList 1.21.45
- umi 版本 3.5.21
- 浏览器环境 Edge 101.0.1198.0
- 开发环境 [e.g. mac OS] Ubuntu 20.04

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20148964/160579318-04f0566c-767b-423a-8880-80f40b1f24b4.png)

**Comment by 1247748612** [comment]
duplicate issue #4939
