### ISSUE TITLE
👑 [需求]表单项的colProps属性，指定的栅格大小md/xl等，现在是整个页面的宽度，希望能改成使用表单的宽度

### ISSUE THREAD

**Issue by cui-xxu** [ant-design/pro-components#4956]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

ProForm

### 🥰 需求描述

表单项的colProps属性，指定的栅格大小md/xl等，现在是整个页面的宽度，希望能改成使用表单的宽度

### ⛰ 功能需求适用场景

表单的宽度，很多情况下是不固定的，如果按照整个页面的宽度进行布局，就会出现不同功能表单项宽度不同的情况，不够美观

### 🧐 解决方案

无

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/46043564/160582154-4767553f-3eb9-48a0-8686-f868776ed4d0.png)
![image](https://user-images.githubusercontent.com/46043564/160582379-a10231f0-4f11-4440-8933-e045bc174c89.png)

**Comment by 1247748612** [comment]
提供下代码，我看看你咋使用的

**Comment by cui-xxu** [comment]
看咱官网上的这个样例代码就行
https://procomponents.ant.design/components/form#%E6%A0%85%E6%A0%BC%E5%8C%96%E5%B8%83%E5%B1%80 
这里设的是 xl: 8，意思是超过1200像素的时候使用3列布局，现在是整个界面宽1200，表单宽686的时候还在使用3列布局，窗口宽度缩到1200一下才变成2列

3列布局

2列布局



***@***.***
 
发件人： dengqing
发送时间： 2022-03-30 15:17
收件人： ant-design/pro-components
抄送： cui-xxu; Author
主题： Re: [ant-design/pro-components]  [需求]表单项的colProps属性，指定的栅格大小md/xl等，现在是整个页面的宽度，希望能改成使用表单的宽度 (Issue #4956)
提供下代码，我看看你咋使用的

**Comment by 1247748612** [comment]
![image](https://user-images.githubusercontent.com/29533304/160778628-67f9337b-476d-4f34-9957-5d643792fb46.png)
官网的看着挺正常的

**Comment by cui-xxu** [comment]
这个机制确实有效，问题是控制效果的宽度，不是form的，而是整个页面的



***@***.***
 
发件人： dengqing
发送时间： 2022-03-30 15:44
收件人： ant-design/pro-components
抄送： cui-xxu; Author
主题： Re: [ant-design/pro-components]  [需求]表单项的colProps属性，指定的栅格大小md/xl等，现在是整个页面的宽度，希望能改成使用表单的宽度 (Issue #4956)

官网的看着挺正常的

**Comment by 1247748612** [comment]
是form的，你只要限制你的form宽度就可以按照form的宽度来布局了

**Comment by 1247748612** [comment]
参考： https://procomponents.ant.design/~demos/schemaform-schema

调整为ModalForm看看效果

**Comment by wang000919** [comment]
> 

> ### ``
