### ISSUE TITLE
🐛[BUG] layout 设置 collapsedWidth 不起作用，SiderMenu 写死了 collapsedWidth 为 48

### ISSUE THREAD

**Issue by yejiajiehz** [ant-design/pro-components#496]
### 🐛 bug 描述

在最外层传递 collapsedWidth  属性，发现不起作用。查看源代码发现代码里写死了 48  
https://github.com/ant-design/pro-components/blob/master/packages/layout/src/SiderMenu/SiderMenu.tsx#L153 

### © 版本信息

- ProComponents 版本: 6.4.15
- umi 版本 3.0.10
- 浏览器环境 chrome
- 开发环境 ubuntu

**Comment by chenshuai2144** [comment]
collapsedWidth  不允许设置，不然动画和对齐会挂掉
