### ISSUE TITLE
Proper way to configure locale in ant and pro-components

### ISSUE THREAD

**Issue by acanimal** [ant-design/pro-components#4962]
Hi, 
I would appreciate if anybody could give me some light on how to configure the locale with pro-components.

Im using create-react-app application with next versions of ant: 
```json
    "@ant-design/pro-descriptions": "1.10.59",
    "@ant-design/pro-form": "1.59.3",
    "@ant-design/pro-layout": "6.34.7",
    "@ant-design/pro-table": "2.69.0",
    "antd": "4.19.3",
```

The code I'm using to initialize locale both for ant and pro-components is:

```jsx
// Locale for ant.design and pro-coponents
import { ConfigProvider } from 'antd';
import enUS from 'antd/lib/locale/en_US';
import enUSProComponents from '@ant-design/pro-provider/lib/locale/en_US';

const locale = { ...enUS, ...enUSProComponents };

ReactDOM.render(
  <React.StrictMode>
    <BrowserRouter>
      <Provider store={store}>
        <ConfigProvider locale={locale}>
          <App />
        </ConfigProvider>
      </Provider>
    </BrowserRouter>
  </React.StrictMode>,
  document.getElementById('root')
);
```

But pro-components are not properly localized.

Anybody can give me some advice?
Thanks in advance

**Comment by 1247748612** [comment]
remove enUSProComponents

try this
```typescript
// Locale for ant.design and pro-coponents
import { ConfigProvider } from 'antd';
import enUS from 'antd/lib/locale/en_US';

ReactDOM.render(
  <React.StrictMode>
    <BrowserRouter>
      <Provider store={store}>
        <ConfigProvider locale={enUS}>
          <App />
        </ConfigProvider>
      </Provider>
    </BrowserRouter>
  </React.StrictMode>,
  document.getElementById('root')
);


```

**Comment by acanimal** [comment]
That doesn't works. After testing a following the source code I found next is the only way to make it works:

```
import { ConfigProvider } from 'antd';
import { ConfigProviderWrap } from '@ant-design/pro-provider';
import enUS from 'antd/lib/locale/en_US';

ReactDOM.render(
  <React.StrictMode>
    <BrowserRouter>
      <Provider store={store}>
        <ConfigProvider locale={enUS}>
          <ConfigProviderWrap>
            <App />
          </ConfigProviderWrap>
        </ConfigProvider>
      </Provider>
    </BrowserRouter>
  </React.StrictMode>,
  document.getElementById('root')
```

`ConfigProviderWrap` detects the locale and loads the corresponde pro-component locales.

**Comment by hsbtr** [comment]
> That doesn't works. After testing a following the source code I found next is the only way to make it works:
> 
> ```js
> import { ConfigProvider } from 'antd';
> import { ConfigProviderWrap } from '@ant-design/pro-provider';
> import enUS from 'antd/lib/locale/en_US';
> 
> ReactDOM.render(
>   <React.StrictMode>
>     <BrowserRouter>
>       <Provider store={store}>
>         <ConfigProvider locale={enUS}>
>           <ConfigProviderWrap>
>             <App />
>           </ConfigProviderWrap>
>         </ConfigProvider>
>       </Provider>
>     </BrowserRouter>
>   </React.StrictMode>,
>   document.getElementById('root')
> ```
> 
> `ConfigProviderWrap` detects the locale and loads the corresponde pro-component locales.

The solution is that the DateTime component is invalid

**Comment by adarshaacharya** [comment]
> That doesn't works. After testing a following the source code I found next is the only way to make it works:
> 
> ```js
> import { ConfigProvider } from 'antd';
> import { ConfigProviderWrap } from '@ant-design/pro-provider';
> import enUS from 'antd/lib/locale/en_US';
> 
> ReactDOM.render(
>   <React.StrictMode>
>     <BrowserRouter>
>       <Provider store={store}>
>         <ConfigProvider locale={enUS}>
>           <ConfigProviderWrap>
>             <App />
>           </ConfigProviderWrap>
>         </ConfigProvider>
>       </Provider>
>     </BrowserRouter>
>   </React.StrictMode>,
>   document.getElementById('root')
> ```
> 
> `ConfigProviderWrap` detects the locale and loads the corresponde pro-component locales.

can't find configwrap now what's the new component in the latest version?
