### ISSUE TITLE
🧐[问题] 新手求问，怎样添加react quill field

### ISSUE THREAD

**Issue by simon-zhangmuye** [ant-design/pro-components#4964]
请问怎么在pro from中添加react quill的富文本编辑

**Comment by 1247748612** [comment]
看这 https://procomponents.ant.design/components/field-set#proformfields-%E8%A1%A8%E5%8D%95%E9%A1%B9

**Comment by chenshuai2144** [comment]
包个组件，调用一下 FormItem 给你的value 和 onChange。
