### ISSUE TITLE
🐛[BUG] EditableProTable中新增加一行时必填项缓存问题

### ISSUE THREAD

**Issue by yanhcao** [ant-design/pro-components#4965]
rt： 
问题1: 缓存无法清除，除非不设置必填项
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/33095737/160729233-546cfab6-80bf-42b9-9dd2-92fd92a53cdc.png">

问题2: select的枚举enumValue无法使用boolean，默认会转为字符串
`
valueType: 'select',
  valueEnum: {
    true: { text: 'true' },
    false: {
      text: 'false',
    },
  },
`
问题3: 可否配置国际化？希望内部antd组件都使用英文展示可行吗？

版本：@ant-design/pro-table 2.70.0

**Comment by yanhcao** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [[🐛[BUG]EditableProTable分页新增行问题 #3354](https://github.com/ant-design/pro-components/issues/3354)][🐛[BUG]EditableProTable分页新增行问题][67%]

好像不太吻合

**Comment by DerrickTel** [comment]
问题2：用new Map

**Comment by chenshuai2144** [comment]
rowKey 重复了吗？

**Comment by yanhcao** [comment]
> 问题2：用new Map

**Comment by PlutoCA** [comment]
问题1我也遇见了，请问有什么方案避免么

**Comment by 1247748612** [comment]
这个问题之前是好的还是，还是才使用发现这个问题的？

不知道是不是之前的改动影响到了

**Comment by fuxiaojian111** [comment]
这个有解决办法吗

**Comment by yanhcao** [comment]
> 

这个不清楚。。以前没使用过

**Comment by 1247748612** [comment]
没复现，来个codesandbox？

**Comment by 1247748612** [comment]
已复现
