### ISSUE TITLE
👑 [需求]ProForm.useForm()返回值得类型可不可以是ProFormInstance

### ISSUE THREAD

**Issue by ILoveChy** [ant-design/pro-components#4967]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

ProForm

### 🥰 需求描述

就是用ProForm的时候不是很喜欢用ref,因为还需要多写个.current,所以习惯性的会使用Form.useForm(),
但是这种返回的(包括ProForm.useForm)格式都是FormInstance,这里面少了几个格式化方法,一些时间字段处理起来就会比较麻烦
所以想问下 可不可以支持下 ProForm的useForm方法返回的是跟formRef一样的类型ProFormInstance

**Comment by chenshuai2144** [comment]
这个不行，封装hooks难度太大了。还是用ref吧

**Comment by chenshuai2144** [comment]
或者你有好方法是欢迎pr的

**Comment by vaynevayne** [comment]
https://github.com/mantinedev/mantine/blob/master/src/mantine-form/src/use-form.ts
@chenshuai2144 这个库实现的比较简单，useForm内部使用useState
，然后返回各种读写state的对象，这是在用户侧调用useForm并且传进组件，所以可以直接把这个对象放到useImmhandle上，我没看过antd的，感觉你们内部还做了依赖收集吧，不知道这样能不能行
