### ISSUE TITLE
🧐[问题]ProTable中的search:false隐藏表单项,也能动态传值到request处接收

### ISSUE THREAD

**Issue by mayhai** [ant-design/pro-components#4968]
### 🧐 问题描述
ProTable中的search:false隐藏表单项，同时又想动态的设置表单的值给request去接收。

 💻 示例代码
const columns = [
    {
      title: '序号',
      dataIndex: 'index',
      valueType: 'index',
      // width: 80,
    },
    {
      title: '血型',
      dataIndex: 'zcje',
      hideInSearch:true
    }];

<ProTable
              columns={columns}
              actionRef={actionRef}
              formRef={formRef}   
              rowKey={'id'}
              request={getList}
              headerTitle={buttons?.boolButton}
              scrollX={'150%'}
            />

<Button
                onClick={() => {
                  formRef?.current?.setFieldsValue({
                    zcje:'123'
                  });
                  formRef.current.submit()
                }}
              >给form中隐藏的查询条件赋值</Button>

就是想实现一个字段，在search中即是隐藏的，又能通过formRef将值传值request中去
### 🚑 其他信息

![1648645046(1)](https://user-images.githubusercontent.com/31497480/160840281-9228501d-b43b-41ff-b9b1-a1e819c09f98.jpg)
![1648645321(1)](https://user-images.githubusercontent.com/31497480/160840452-d9ab6de8-876c-4be2-9552-2b346ce3afbe.jpg)
![1648645374(1)](https://user-images.githubusercontent.com/31497480/160840619-3bf76034-5074-488f-81e8-96f5b4ab2661.jpg)

**Comment by DerrickTel** [comment]
直接在request里面把参数写进去这样好一点吧，这个场景并不多见

**Comment by mayhai** [comment]
> 直接在request里面把参数写进去这样好一点吧，这个场景并不多见

那就只能直接传入request了，场景还是有的 “左树右表”

**Comment by chenshuai2144** [comment]
有个叫 parmas 的配置，就是为了做这件事。
