### ISSUE TITLE
🧐[问题] React upgrade version 18, how to handle to replace render with createRoot

### ISSUE THREAD

**Issue by JennyLeung030** [ant-design/pro-components#4971]
### 🧐 问题描述
The React upgrade version to 18. I see error in the console log, which is taking react upgrade problem. I don't know ant design pro to change or not?

### 🚑 其他信息
Below link is about replace render with createRoot information.
https://github.com/reactwg/react-18/discussions/5

![image](https://user-images.githubusercontent.com/51438629/160972132-73ecd01f-0115-4931-828a-b05b0a876c65.png)

**Comment by chenshuai2144** [comment]
When anti support is complete, we will also support it

**Comment by JennyLeung030** [comment]
> When anti support is complete, we will also support it

Thank you!
