### ISSUE TITLE
🧐[问题]EditableProTable如何才能在我新增一行时，不默认填写我之前输入的值

### ISSUE THREAD

**Issue by jayt1001** [ant-design/pro-components#4975]
### 🧐 问题描述
1.例如我先随便输入一些内容：`活动名称19asdad12331`

---
![image](https://user-images.githubusercontent.com/29675005/161017524-2d4a040b-cc7b-4252-886f-8b0f81daec9b.png)

---
2.再点击“新增一行”按钮时，新增按钮的值会默认填写我刚输入的内容，我期望的效果是添加一条无内容的空行:
![image](https://user-images.githubusercontent.com/29675005/161017907-aac1318c-dcac-4c20-8843-f9bf9b14f74b.png)

---
尝试了record设置不能达到我的预期
![image](https://user-images.githubusercontent.com/29675005/161017871-07a636e2-caba-4724-918b-89198d83e9ee.png)

### 🚑 其他信息

pro-table@2.70.0

**Comment by 1247748612** [comment]
duplicate issue: #4965

**Comment by laosandegudai** [comment]
> duplicate issue: #4965

最新版本 2.71.1 还有这问题。

**Comment by laosandegudai** [comment]
> duplicate issue: #4965

最新版本 2.71.1 还有这问题。
