### ISSUE TITLE
🧐[问题]新人求问，如何在NextJS中使用antd pro component.

### ISSUE THREAD

**Issue by simon-zhangmuye** [ant-design/pro-components#4979]
新手请问大佬，我想在nextjs中使用antd pro form。但是在引入后报这个错。请问有人知道怎么解决吗？
![image](https://user-images.githubusercontent.com/10706610/161053195-90b09cc7-13f6-4a7b-b3a0-9c9c7ab9635c.png)

**Comment by simon-zhangmuye** [comment]
把引入放在了NextJS得global.css里边，但是也不行，难道必须要装less支持吗？
![`_NU 4E29KQV4S%KLDA~VJG](https://user-images.githubusercontent.com/10706610/161047546-5d1c6985-25ae-4fa9-bb32-cb601f66848a.jpg)

**Comment by simon-zhangmuye** [comment]
@chenshuai2144 我看之前也有人问，请问问题解决了吗？

**Comment by chenshuai2144** [comment]
我看到别的issue是说有个 antd-less 的插件，你安装一下。

https://github.com/ant-design/pro-components/issues/4852#issuecomment-1086804425

**Comment by crazyshakalaka** [comment]
请问解决了吗

**Comment by simon-zhangmuye** [comment]
@

> 我看到别的issue是说有个 antd-less 的插件，你安装一下。
> 
> [#4852 (comment)](https://github.com/ant-design/pro-components/issues/4852#issuecomment-1086804425)

不行，问题没有解决。请问大佬试过了吗？问的人挺多的

**Comment by simon-zhangmuye** [comment]
@chenshuai2144 我用less插件之后不报错了，但是不支持ssr。需要dynamic import。

**Comment by Edwin-WB-Li** [comment]
所以这个 next 到底能不能用 antd pro component
