### ISSUE TITLE
🧐[问题] LightFilter 模式下的 ProFormSelect 怎么清空搜索过滤的 input

### ISSUE THREAD

**Issue by MircoSans** [ant-design/pro-components#4982]
### 🧐 问题描述

LightFilter 模式下的 ProFormSelect 在选择选项后，搜索的过滤条件依然存在搜索框内。
希望在 ProFormSelect 选择选项后能够清空 input 搜索框的内容。

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/51395487/161187161-41208cef-7ae6-4a47-a3b6-56de1e750cba.png)

**Comment by chenshuai2144** [comment]
应该是自定清空的，来个 pr 支持下？

**Comment by DerrickTel** [comment]
<img width="458" alt="image" src="https://user-images.githubusercontent.com/24643779/161204923-d974f4c3-7584-4ac7-bfff-88aca3f08c17.png">
传`true`

**Comment by MircoSans** [comment]
> <img alt="image" width="458" src="https://user-images.githubusercontent.com/24643779/161204923-d974f4c3-7584-4ac7-bfff-88aca3f08c17.png">
> 
> 传`true`

设置 true 只是允许选项清空。
点开 LightFilter ProSelect 里面的筛选框输入关键词，选择选项后再点开，关键词依然存在 input 中。

**Comment by MircoSans** [comment]
![943cj-cmape](https://user-images.githubusercontent.com/51395487/161207630-0d5731f0-6bc2-4ad9-8014-56f8fd95ba18.gif)

**Comment by DerrickTel** [comment]
> ![943cj-cmape](https://user-images.githubusercontent.com/51395487/161207630-0d5731f0-6bc2-4ad9-8014-56f8fd95ba18.gif)

懂你意思了，等pr merge

**Comment by Taoziyayayaya** [comment]
@chenshuai2144  我已升级"@ant-design/pro-form": "^1.63.1", 但是现在问题还是没有被解决

**Comment by Taoziyayayaya** [comment]
![image](https://user-images.githubusercontent.com/103577054/163175751-4746d090-0316-4365-9054-4db3146bcfe7.png)
@chenshuai2144

**Comment by Taoziyayayaya** [comment]
@chenshuai2144 
![image](https://user-images.githubusercontent.com/103577054/163176016-269174f9-f21c-4c35-804d-5ff781328d72.png)

**Comment by Taoziyayayaya** [comment]
![image](https://user-images.githubusercontent.com/103577054/163176090-d3d850b7-c7b6-46ea-a269-48a6a7a71d50.png)
