### ISSUE TITLE
🧐[问题] 能否拿到 ProTable 的 datsSource

### ISSUE THREAD

**Issue by DearVikki** [ant-design/pro-components#4988]
### 🧐 问题描述

通过 request 请求到的数据源，能否通过某种方式（比如在 actionRef 上挂载一个 getDateSource 的方式）暴露给外界用户？目前没在文档里看到对应的 api。

消费这份数据的需求应该不常见但存在。比如我的场景是，点击列表的每个 item 可以弹出弹窗展示并编辑，弹窗数据就是取的列表 item 数据。用户编辑完弹窗后，期望列表更新、弹窗不关闭且展示出刚刚更新的信息，因此我会需要读到更新后的列表数据。

**Comment by DerrickTel** [comment]
在request里面补一个state变量呢？

**Comment by DearVikki** [comment]
是我粗心了，有对应的 api 的 
![image](https://user-images.githubusercontent.com/18145936/161371025-5d726a90-0927-406b-acc3-fec90508621d.png)
