### ISSUE TITLE
🧐[问题] ProFormSelect 清空提交问题

### ISSUE THREAD

**Issue by 569202812** [ant-design/pro-components#4994]
### 🧐 问题描述
`ProFormSelect` 清空后提交 `onFinish` 直接不传递值而 `Form`是返回个`undefined`的值

### 🚑 其他信息
Form表单
![image](https://user-images.githubusercontent.com/34082148/161369851-0a049f43-93c7-4418-be67-7014d7eec047.png)

ProForm表单
![image](https://user-images.githubusercontent.com/34082148/161369847-baa6ace3-e5fe-4afe-a9f6-c1758dbe490c.png)

**Comment by chenshuai2144** [comment]
有个omitNil 配置，你关掉之后就会带 undefined 了
