### ISSUE TITLE
🐛[BUG] 【ProTable】columnsState.onChange 方法回调的 columnsState 格式不对

### ISSUE THREAD

**Issue by DearVikki** [ant-design/pro-components#4996]
### 🐛 bug 描述

背景：非受控模式 只是想统计用户对列的操作
问题 ：columnsState.onChange 方法接受到的 columnsState 应该统一使用 column 的 dataIndex 作为 key，现在收到的结果是 Object.keys(所有column) + 不展示的那几列 column 的 dataIndex 集合。

![image](https://user-images.githubusercontent.com/18145936/161373637-d0949705-7007-4601-a834-b9ef17ffba0e.png)

### 📷 复现步骤

```tsx
<ProTable
  ...
  columnsState={{
    onChange: (value) => {
      console.log('column state', value);
    },
 }}
/>
```

**Comment by 1247748612** [comment]
更到最新了吗？优先使用key然后使用dataIndex

https://github.com/ant-design/pro-components/pull/4931#discussion_r835750928

**Comment by ChinaMrAlvin** [comment]
Because you did not set the key or valueType, the columnKey was not returned, so the index is displayed.
![ed778de2501e8e577f0e9015586d5a3d](https://github.com/ant-design/pro-components/assets/22882440/e02839f9-2e8f-4168-b5ed-2a8927532197)
