### ISSUE TITLE
🧐[问题]ProTable设置search=>filterType: 'light',选择标签使用‘OptGroup’数据结构的样式跟预想的不一样

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#4998]
"antd": "^4.18.3",
"@ant-design/pro-table": "^2.61.2",

使用 OptGroup 数据结构填充 valueType: 'select' 的 columns，
默认情况：
![image](https://user-images.githubusercontent.com/12421552/161397026-1b1b846f-f420-4502-a973-056afb0f48a2.png)

![image](https://user-images.githubusercontent.com/12421552/161397005-4057c58e-efb4-4c95-9748-d1f2e4ca23c8.png)

![image](https://user-images.githubusercontent.com/12421552/161397069-46e8a826-853e-477c-acf4-f4237693b885.png)

当把ProTable的search=>filterType: 'light'时，
![image](https://user-images.githubusercontent.com/12421552/161397099-beef84c7-95fd-4ac6-b373-799f0219572c.png)
就成下图样式
![image](https://user-images.githubusercontent.com/12421552/161397127-efd893d2-4731-43af-ad0d-13120803a161.png)

请问有什么方法可以跟默认情况一样吗？
或者我自定义一个？？？

**Comment by chenshuai2144** [comment]
是个bug，要想办法修复一下

**Comment by chenshuai2144** [comment]
已经修复，试试
