### ISSUE TITLE
🐛[BUG] 试用新版prolayout，外层layout配置为false，内层配置为true，内层路由页面layout布局展示默认，而非系统设置的样式。

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#4999]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/30397655/161417795-56f74e66-abee-4e56-a472-9d924bfbcdcf.png">

**Comment by chenshuai2144** [comment]
好像不支持这种用法，我记得是会继承覆盖的
