### ISSUE TITLE
👑 [需求]ProDescriptions自定义valueType，ProProvider.Provider 对 render 函数 props 参数增加 dataSource

### ISSUE THREAD

**Issue by darin-lao** [ant-design/pro-components#5002]
### 🥰 需求描述
ProDescriptions在使用 `column` 配置自定义valueType,可以获取ProDescription的 dataSource 属性。

```
<ProProvider.Provider
      value={{
        ...values,
        valueTypeMap: {
          link: {
            renderFormItem: (text, props: any) => {
              const noStyle = props.noStyle ? props.noStyle : true;
              return <ProFormText {...props} noStyle={noStyle} />;
            },
            render: (text: any, props: Omit<ProFieldFCRenderProps, 'onChange' | 'text'>) => {
              // console.log('text>>', text, props);
              return <LinkText {...props} />;
            },
          },

        },
      }}
    >
      {children}
    </ProProvider.Provider>
```

在ProCompnent自定义valueType,`valueTypeMap`中`render`方法第一个参数只是dataIndex的 value。在一些通用的业务，可能要信组件的其它字段判断处理，自定义valueType 是为了进一步封装业务组件，减少页面的重复代码

### ⛰ 功能需求适用场景

* 做 Link 组件，例如，`dataIndex`是只是返回一个单号，但这个单号在不同的状态要做不同跳转、显示处理。
* 业务组件的二次封装

### 🧐 解决方案
在 ProTable 自定义` valueType`,在`ProProvider.Provider`下`render`中 props 属性中有当前数据列表的 `record` 属性获取当前行的数据对象。ProDescriptions组件应该也增加`record`属性返回ProDescriptions的 `dataSource`,`record`这个属性名只是建议

**Comment by frankcou** [comment]
希望能跟外面配置的columns中render以及renderFormItem是同样的类型，可以传入同样的参数

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，感谢反馈。你的需求是让 `render` 和 `renderFormItem` 的参数相同，这样能让这两个方法的逻辑更加统一，同时也可以提高代码的可复用性。

我们了解到您的需求，我们会考虑在未来的版本中增加这个功能。在目前版本中，您可以使用以下方法来实现这个需求：

您可以使用 `render` 和 `renderFormItem` 中的公共参数 `text` 以及 `record` 进行处理，这两个参数在 ProTable 中定义。同时，您也可以在 `ProDescriptions` 的 `column` 中使用 `render` 方法并传入相应的参数：

```tsx
{
  title: 'Name',
  dataIndex: 'name',
  render: (text: string, record: any) => renderName(text, record),
},     
```

其中 `renderName` 方法可以封装 `render` 和 `renderFormItem` 的公共逻辑。

另外，您还可以使用 `ProDescriptions` 中新增的 `params` 参数，可以让 `render` 和 `renderFormItem` 方法在一个函数中处理公共逻辑，进一步提高代码的可复用性：https://procomponents.ant.design/components/descriptions-cn/#params

**Comment by chenshuai2144** [comment]
暂时没有计划
