### ISSUE TITLE
👑 [EditableProTable需求]

### ISSUE THREAD

**Issue by fuxiaojian111** [ant-design/pro-components#5005]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述
1.EditableProTable性能问题有计划吗，antd官网的虚拟滚动好像不太行，渲染的始终是一个div，其他市面上的也是有bug的
2.pro-table在升级版本之后，EditableProTable会出现复制行值的问题

**Comment by chenshuai2144** [comment]
好好写标题
