### ISSUE TITLE
🐛[BUG] ProFormSelect 在 LightFilter 模式下设置 placement 无法控制 select 弹出位置

### ISSUE THREAD

**Issue by MircoSans** [ant-design/pro-components#5007]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

由于业务需求需要在页面左上角使用 LightFilter , 在 LightFilter 模式下设置ProFormSelect placement 无法控制 select 弹出位置。

### 📷 复现步骤

![i8p7r-w7zym](https://user-images.githubusercontent.com/51395487/161952833-1bf2e99e-882b-4e69-b762-ca00db7f93ae.gif)

### 🏞 期望结果

希望能够控制select组件下拉选项出现的位置

### 💻 复现代码

``` jsx
<ProFormSelect
  name="area"
  showSearch
  allowClear={false}  
  fieldProps={{
    labelInValue: true,
    // 该属性无效
    placement: 'bottomRight',
  }}
/>
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
不支持这个属性，需要支持一下。

**Comment by MircoSans** [comment]
设置  `dropdownMatchSelectWidth` 属性可以让弹出的选项不溢出窗口。
但是位置还是没对齐。

``` jsx
 <ProFormSelect
  name="area"
  showSearch
  allowClear={false}
  fieldProps={{
  labelInValue: true,
  dropdownMatchSelectWidth: false,
  placement: 'bottomLeft',
  }}
/>
```

**Comment by chenshuai2144** [comment]
现在支持了，可以在filedProps 里试试了
