### ISSUE TITLE
👑 [需求] 希望在ProList的rowSelection里添加alwaysShowAlert选项，支持关闭选框的Alert功能。

### ISSUE THREAD

**Issue by owendswang** [ant-design/pro-components#5009]
### 🔩 所属模块或组件

ProList

### 🥰 需求描述

ProList有和ProTable类似的rowSelection选项功能，但是缺少了ProTable的alwaysShowAlert选项功能。

### ⛰ 功能需求适用场景

我不想在选中某一项时，在列表上方出现取消选项，我想关掉它。

### 🧐 解决方案

在rowSelection里添加alwaysShowAlert选项，用以关闭上方的选择alert。

**Comment by chenshuai2144** [comment]
<html>
<body>


ableAlertRender | 自定义批量操作工具栏左侧信息区域, false 时不显示 | ({ selectedRowKeys: Key[], selectedRows: T[], onCleanSelected: ()=>void }) => ReactNode)\|false | -
-- | -- | -- | --



</body>
</html>

你需要的是这个api把

**Comment by owendswang** [comment]
> 

不是啊是点选之后上面出现的alert。不是左侧信息。

**Comment by chenshuai2144** [comment]
左侧信息 是什么东西。table 有这个功能吗？

**Comment by owendswang** [comment]
这几个选项是ProTable的，不是antd Table的，我是希望这几个选项，在ProList上也生效，现在的情况是，这几个ProTable的专属rowSelection选项，在ProList里没有，所以我不能自定义那些点选之后的效果，不能关闭选择后在上方出现的“已选择1个 [清除选择]”这个Alert。抱歉我不会贴图，不然会好理解一些……

**Comment by chenshuai2144** [comment]
那就是这个 tableAlertRender

你去试试

**Comment by owendswang** [comment]
> 

刚试的，那几个选项都试了……一点效果没有……
`rowSelection={{
              alwaysShowAlert: false,
              tableAlertRender: false,
              tableAlertOptionRender: false
            }}`

**Comment by chenshuai2144** [comment]
在全局，不是在 rowSelection

**Comment by owendswang** [comment]
> 在全局，不是在 rowSelection

我的天，恍然大悟！……跪了跪了……我可能是需要换换脑子了。抱歉打扰了！
感谢大佬耐心解答！T_T
