### ISSUE TITLE
👑 [需求]ProTable type="form" 默认提交按钮增加loading状态

### ISSUE THREAD

**Issue by qq382724935** [ant-design/pro-components#501]
### 🥰 需求描述

ProTable type="form" 默认提交按钮增加loading状态
### 🧐 解决方案
1. 设置ProTable API loading 传给提交按钮?
2. modal footer本身能够自定义loading,增加个隐藏Form默认按钮API？

**Comment by gameruleCEO** [comment]
@chenshuai2144 这个需求什么时候或者哪个版本开始支持呢?

**Comment by gameruleCEO** [comment]
希望可以自定义提交+重置按钮的样式(名称、位置等)和loading状态。

**Comment by chenshuai2144** [comment]
还没写！ 你有空可以提个pr

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/619
