### ISSUE TITLE
🐛[BUG] ProFormSelect 在 LightFilter 模式下点击激活下拉选项后再次点击未隐藏下拉框

### ISSUE THREAD

**Issue by MircoSans** [ant-design/pro-components#5010]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProFormSelect 在 LightFilter 模式下点击激活下拉选项后再次点击未隐藏下拉框

### 📷 复现步骤

![d3bpf-lamne](https://user-images.githubusercontent.com/51395487/162110367-675c64ac-5d7d-4bbd-b10f-e640cc9be23c.gif)

### 🏞 期望结果

在 select 激活状态下再次点击隐藏下拉框

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by wangmeijian** [comment]
尝试解决中~
