### ISSUE TITLE
🐛[BUG]在 SchemaForm 中当数据类型为 dependency 时，依赖项变化时配置不同的 fieldProps，不触发对应项更新

### ISSUE THREAD

**Issue by momo-mao** [ant-design/pro-components#5011]
### 🐛 bug 描述

动态改变依赖项时，重新赋值的 columns 不会触发相关组件的更新，在1月份的时候，我有针对这个情况提过一个[issue](https://github.com/ant-design/pro-components/issues/4488)，后面版本更新有解决了，但是升级到1.53.7后，此问题又出现了，试了一下目前最新的 1.61.0 版本，问题依旧

### 📷 复现步骤

对 BetaSchemaForm 进行了一层封装，主要是要处理业务接口的数据，构造成符合 pro columns 的数据，对于依赖数据要实现，不同的依赖对象使用不同的配置，这个流程我已在 codesandbox 中实现

### 🏞 期望结果

将优惠方式从"按金额"切换到"按金额(最多5块)"后，优惠金额输入框应该变成报错状态的红色框框，因为这时的 max 是 5，输入框中内容为 8

### 💻 复现代码

https://codesandbox.io/s/you-yi-lai-guan-xi-de-schema-biao-dan-forked-6vy0h?file=/SchemaForm.tsx

### © 版本信息

- @ant-design/pro-form 版本: 1.61.0

**Comment by chenshuai2144** [comment]
有没有兴趣一起维护，我不怎么用这个组件。不是很懂

**Comment by momo-mao** [comment]
> 有没有兴趣一起维护，我不怎么用这个组件。不是很懂

好，我试看看

**Comment by 1247748612** [comment]
在看了吗

**Comment by momo-mao** [comment]
> 在看了吗

本来在看了，临时有紧急业务要发布，这两周都被占用了，要缓一缓，没那么忙的时候来
