### ISSUE TITLE
Protable筛选initialValue异步赋值问题

### ISSUE THREAD

**Issue by caizhehao** [ant-design/pro-components#5013]
Protable某个筛选column的initialValue是通过异步获取，初始值获取后initialValue赋值无效，并且protable的request参数没有该值
业务场景：protable筛选项中有个select，该select的option是通过后端接口返回的，初始值initialValue是option的第一个值，initialValue异步赋值无效，另protable的首次request参数也没有该异步的initialValue

**Comment by chenshuai2144** [comment]
initialValue 不支持异步。

在没有  initialValue 的时候不要渲染 table。

`initialValue && <Protable/>`

**Comment by caizhehao** [comment]
> 
如果有一个筛选项到还好控制，现在有好几个这种筛选项，那样的话就得：
（initialValue1 && initialValue2 && initialValue3) && <Protable/>

**Comment by chenshuai2144** [comment]
对的。initial 的意思就是这样的。

觉得麻烦就等好了之后调用一下 form.submit

**Comment by caizhehao** [comment]
>


> 对的。initial 的意思就是这样的。
> 
> 觉得麻烦就等好了之后调用一下 form.set 然后 form.submit
你的意思是等接口返回后` form.setFieldsValue`赋值，然后在调用 form.submit，那样的话会至少调用2次protable的request

**Comment by chenshuai2144** [comment]
异步不就是这样的吗？ table 有个手动模式，你可以可以直接用手动模式全部自己手动控制

**Comment by hanwenbo** [comment]
> > 
> 
> > 对的。initial 的意思就是这样的。
> > 觉得麻烦就等好了之后调用一下 form.set 然后 form.submit
> 
> 你的意思是等接口返回后` form.setFieldsValue`赋值，然后在调用 form.submit，那样的话会至少调用2次protable的request
 form.setFieldsValue 之前没bug，更新最新版本后    会有bug   无法赋值  谨慎使用

**Comment by hanwenbo** [comment]
> > 
> 
> > 对的。initial 的意思就是这样的。
> > 觉得麻烦就等好了之后调用一下 form.set 然后 form.submit
> 
> 你的意思是等接口返回后` form.setFieldsValue`赋值，然后在调用 form.submit，那样的话会至少调用2次protable的request

form.setFieldsValue 之前没bug，更新最新版本后 会有bug 无法赋值 谨慎使用

**Comment by kirincc** [comment]
> 

请问是什么bug？目前我碰到form.setFieldsValue后，getValueProps获取到的依然是旧值

**Comment by kirincc** [comment]
> > > 
> > 
> > 
> > > 对的。initial 的意思就是这样的。
> > > 觉得麻烦就等好了之后调用一下 form.set 然后 form.submit
> > 
> > 
> > 你的意思是等接口返回后` form.setFieldsValue`赋值，然后在调用 form.submit，那样的话会至少调用2次protable的request
> 
> form.setFieldsValue 之前没bug，更新最新版本后 会有bug 无法赋值 谨慎使用

我目前在2.56.9和2.43.1都碰到了这问题，form.setFieldsValue 后，columns中的getValueProps获取到的依然是旧值

**Comment by lovewinders** [comment]
> 感觉这种场景很普遍啊，官方居然没有解决方案

同上
