### ISSUE TITLE
👑 [需求]ProTable的表格主体自定义怎么使用接口返回的数据

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/pro-components#5014]
### 🔩 所属模块或组件

ProTable

### 🥰 需求描述

ProTable的表格主体自定义主要使用的是tableExtraRender方法，这个方法第二个参数是datasource，ProTable的datasource是个数组
自定义主体的时候，除了表格要用的数组，还需要用到其他接口返回的数据。
能不能再添加一个参数，可以获取到接口返回的所有数据。

### ⛰ 功能需求适用场景

基本上用到表格自定义主体的，处了表格使用的列表数据外，还要用到接口返回的其他数据

### 🧐 解决方案

暂时没有

**Comment by chenshuai2144** [comment]
封装个组件，在组件里面请求了一下拼接。
