### ISSUE TITLE
🐛[BUG] ProTable 使用renderFormItem 渲染 ProFormCascader 组件，展示宽度不能百分百

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#5016]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/30397655/162201505-55b3d372-2eec-4460-9bd6-200a6315ba8f.png">

<img width="537" alt="image" src="https://user-images.githubusercontent.com/30397655/162201740-59e5504c-0ff1-4d39-9941-fa05fa9cfd92.png">

<img width="409" alt="image" src="https://user-images.githubusercontent.com/30397655/162201962-c0be4339-9f05-441f-b98d-3dac15622c45.png">

**Comment by leshalv** [comment]
多选时，点击搜索，只能搜索一个

**Comment by Dunqing** [comment]
不能用valueType: cascader吗？

**Comment by leshalv** [comment]
要根据后端数据渲染的

**Comment by Dunqing** [comment]
cascader 也可以根据后端数据渲染。来个example？

**Comment by caizhehao** [comment]
我也遇到同样的问题，请问解决了吗
