### ISSUE TITLE
🐛[BUG]BetaSchemaForm中绑定form会导致destroyOnClose失效

### ISSUE THREAD

**Issue by sunxia628** [ant-design/pro-components#5017]
### 🐛 bug 描述
BetaSchemaForm中绑定自定义form实例会导致destroyOnClose: true时，表单值仍然存在，推测时BetaSchemaForm弹框中元素未重新渲染，DrawerForm可能存在同样问题

### 📷 复现步骤
      <BetaSchemaForm<DataItem>
        form={form}
        modalProps={{ destroyOnClose: true, forceRender: false, handle: false }}
        onVisibleChange={(visible) => {
          console.log("onVisibleChange visible", visible);
          // !visible && form.resetFields();
        }}
        trigger={<a>点击我</a>}
        layoutType={layoutType}
        steps={[
          {
            title: "ProComponent"
          }
        ]}
        rowProps={{
          gutter: [16, 16]
        }}
        grid={layoutType !== "LightFilter" && layoutType !== "QueryFilter"}
        onFinish={async (values) => {
          console.log(values);
        }}
        columns={(layoutType === "StepsForm" ? [columns] : columns) as any}
      />
    </>

### 🏞 期望结果

form={form}
modalProps={{ destroyOnClose: true, }}
form不影响destroyOnClose销毁子元素效果

### 💻 复现代码

https://codesandbox.io/s/schema-biao-dan-forked-jgny3r?file=/App.tsx
### © 版本信息

- pro-form 版本: [1.62]
- antd 版本: [4.19.3]
- react 版本: [>=16.9.0]
- Google Chrome  91.0.4472.106（正式版本） （64 位）
- 开发环境 [window7]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26341016/162354113-d073d824-0f9b-470d-a7f9-d118119cb2bd.png)

**Comment by chenshuai2144** [comment]
值是存在 form 里面的，只要form不销毁，他总是存在的。

你可以关闭的时候销毁一下。

**Comment by sunxia628** [comment]
@chenshuai2144 ,Antd的Modal组件和BetaSchemaForm实现不同吗，如果BetaSchemaForm也是Modal包裹Form，destroyOnClose: true时，Form组件被销毁、绑定也失去，Form重新渲染和绑定；
我是看Modal不存在这个问题：
https://codesandbox.io/s/dan-chu-ceng-zhong-de-xin-jian-biao-dan-antd-4-19-5-forked-y5fuq6?file=/index.js

**Comment by chenshuai2144** [comment]
代码能看看？

**Comment by sunxia628** [comment]
> 代码能看看？

代码有点多，大致情况是，基于ProTable封装了一个增删改查的组件，里面的查询表单、表格都是ProTable原生，新增表单使用的BetaSchemaForm，复用的ProTable的columns配置，通过按钮弹出新增表单，我是使用新增表单时存在这种问题！
应用入口：
`
import React, { useState, useEffect, } from "react";
import { Form } from "antd";
import { QueryList, ActionBtn, FileUpload, HocAction, } from "../../components";
import { debounce, } from "../../components/utils/utils";
import CheckModal from "./checkModal";
import { getPageList, save, downloadSit, deleteData } from "./service";
import {
  getCompanyOptions,
  getWellOptions,
  getProjectOptions,
  // getLoggingOptions,
  // getExplainOptions,
  getCategoryOptions,
  getBoreholeOptions,
  getCurveOptions,
} from "./options";
import { singleLayout } from "../../utils/constant";
import moment from 'moment';

import styles from "./index.module.scss";
export default function Index() {
  const [form] = Form.useForm(); // 查询表单对象
  const [addForm] = Form.useForm(); // 新增表单对象
  // const [editForm] = Form.useForm(); // 编辑表单对象
  const [added, setAdded] = useState(true); // 是否初次加载新增弹框
  const [wellOptions, setWellOptions] = useState([]); // 井号下拉框枚举
  const [projectOptions, setProjectOptions] = useState([]); // 测井项目下拉框枚举
  const [categoryOptions, setCategoryOptions] = useState([]); // 资料类别下拉框枚举
  const [boreholeOptions, setBoreholeOptions] = useState([]); // 井眼下拉框枚举
  const [curveOptions, setCurveOptions] = useState([]); // 测井曲线解析后复选框枚举
  const [currentRecord, setCurrentRecord] = useState({}); // 弹框触发的当前数据
  const [visible, setVisible] = useState(false); // 复选弹框展示/隐藏
  const [curveLoading, setCurveLoading] = useState(false); // 测井曲线解析按钮loading

  const forms = {
    query: form,
    add: addForm,
    // edit: editForm,
  };

  function getDateValidator (key = 'jsrq', msg = "测井时期不能大于解释日期!", direction = true, type = "add") {
    const currentForm = forms?.[type];
    return (_, value) => {
      const date = currentForm.getFieldValue(key);
      if (value && date) {
        const flag = direction ? moment(value).valueOf() > moment(date).valueOf() : moment(value).valueOf() < moment(date).valueOf()
        return flag ? Promise.reject(new Error(msg)) : Promise.resolve();
      }
      return Promise.resolve();
    }
  }

  // 初始化下拉框枚举列表
  useEffect(() => {
    async function init() {
      await getWellOptions('', setWellOptions);
      await getProjectOptions({setOptions: setProjectOptions,});
      await getCategoryOptions(setCategoryOptions);
    }
    init();
  }, []);

  const props = {
    rowKey: "dbid",
    columns: [
      {
        title: "管理单位",
        dataIndex: "gldwdm",
        onFilter: true,
        hideInTable: true,
        hideInForm: true,
        valueType: "treeSelect",
        formItemProps: {
          rules: [
            {
              required: true,
            },
          ],
        },
        request: getCompanyOptions,
        fieldProps: {
          placeholder: "请选择",
          allowClear: true,
        },
      },
      {
        title: "井号",
        dataIndex: "jhdm",
        hideInTable: true,
        valueType: "select",
        formItemProps: {
          rules: [
            {
              required: true,
            },
          ],
        },
        fieldProps: {
          labelInValue: true, // value 类型从 string 变为 { value: string, label: ReactNode } 的格式
          options: wellOptions,
          placeholder: "输入关键字模糊搜索",
          allowClear: true,
          showSearch: true,
          onSearch: debounce((value) => getWellOptions(value, setWellOptions)),
        },
        search: {
          transform: (value) => {
            return {
              jhdm: value?.value,
            };
          },
        },
      },
      {
        title: "井号",
        dataIndex: "jhbm",
        hideInForm: true,
        hideInSearch: true,
      },
      {
        title: "测井日期",
        dataIndex: "created_at",
        valueType: "dateRange",
        hideInTable: true,
        hideInForm: true,
        search: {
          transform: (value) => {
            return {
              cjrqs: value[0],
              cjrqe: value[1],
            };
          },
        },
        fieldProps: {
          placeholder: ["最小日期", "最大日期"],
        },
      },
      {
        title: "测井项目",
        dataIndex: "cjxmdm",
        hideInTable: true,
        valueType: "treeSelect",
        formItemProps: {
          rules: [
            {
              required: true,
            },
          ],
        },
        fieldProps: {
          allowClear: true,
          labelInValue: true, // value 类型从 string 变为 { value: string, label: ReactNode } 的格式
          options: projectOptions,
          placeholder: '请选择',
          // placeholder: "输入关键字模糊搜索",
          // showSearch: true,
        },
        search: {
          transform: (value) => {
            return {
              cjxmdm: value?.value,
            };
          },
        },
      },
      {
        title: "测井项目",
        dataIndex: "cjxmmc",
        hideInForm: true,
        hideInSearch: true,
      },
      {
        title: "测井日期",
        dataIndex: "cjrq",
        valueType: "date",
        dependencies: ["jsrq"],
        formItemProps: {
          rules: [
            {
              required: true,
            },
            {validator: getDateValidator()}
          ],
        },
        hideInSearch: true,
        sorter: (rowA, rowB) => rowA.cjrq > rowB.cjrq,
      },
      {
        title: "解释日期",
        dataIndex: "jsrq",
        valueType: "date",
        dependencies: ["cjrq"],
        // formItemProps: getExplainItemProps('add'),
        formItemProps: {
          rules: [
            {
              required: true,
            },
            {validator: getDateValidator('cjrq', '解释日期不能小于测井时期!', false)}
          ],
        },
        hideInSearch: true,
        sorter: (rowA, rowB) => rowA.jsrq > rowB.jsrq,
      },
      {
        title: "井段",
        dataIndex: "jddings",
        hideInForm: true,
        search: false,
        render: (text, record, index, action) => `${text}~${record?.jddis}`
      },
      {
        title: "资料类别",
        dataIndex: "cjcgqxzllbdm",
        hideInTable: true,
        valueType: "select",
        formItemProps: {
          rules: [
            {
              required: true,
            },
          ],
        },
        fieldProps: {
          labelInValue: true, // value 类型从 string 变为 { value: string, label: ReactNode } 的格式
          options: categoryOptions,
        },
        search: {
          transform: (value) => {
            return {
              cjcgqxzllbdm: value?.value,
            };
          },
        },
      },
      {
        title: "资料类别",
        dataIndex: "cjcgqxzllbmc",
        hideInForm: true,
        hideInSearch: true,
      },
      {
        title: "井眼名称",
        dataIndex: "czjydm",
        hideInSearch: true,
        hideInTable: true,
        valueType: "treeSelect",
        formItemProps: {
          rules: [
            {
              required: true,
            },
          ],
        },
        fieldProps: {
          allowClear: true,
          labelInValue: true, // value 类型从 string 变为 { value: string, label: ReactNode } 的格式
          options: boreholeOptions,
          placeholder: '请选择',
          // placeholder: "输入关键字模糊搜索",
          // showSearch: true,
          // onSearch: (value) => getBoreholeOptions(value, setBoreholeOptions),
        },
      },
      {
        title: "解释日期",
        dataIndex: "updated_at",
        valueType: "dateRange",
        hideInTable: true,
        hideInForm: true,
        search: {
          transform: (value) => {
            return {
              jsrqs: value[0],
              jsrqe: value[1],
            };
          },
        },
        fieldProps: {
          placeholder: ["最小日期", "最大日期"],
        },
      },
      {
        title: "测井曲线解析前",
        dataIndex: "lock",
        search: false,
        hideInForm: true,
        render: (text, record, index, action) => {
          const {cjqxsjt_id: cjqxsjtId, cjqxsjtmc: fileName} = {...record};
          return (
            <ActionBtn
              type="link"
              title={fileName}
              onClick={async (e) => downloadSit({ cjqxsjtId, }, fileName)}
            >
              下载
            </ActionBtn>
          );
        },
      },
      {
        title: "测井曲线解析后",
        dataIndex: "locked",
        search: false,
        hideInForm: true,
        render: (text, record, index, action) => {
          return (
            <ActionBtn
              // type="primary"
              icon="icon-download"
              // title="测井曲线"
              loading={
                currentRecord?.dbid === record?.dbid ? curveLoading : false
              }
              onClick={async (e) => {
                setCurrentRecord({ ...record });
                setCurveLoading(true);
                // 测井曲线解析接口异步处理
                getCurveOptions(record, (data) => {
                  setCurveLoading(false);
                  setCurveOptions([...data]);
                  setVisible(true);
                });
              }}
            >
              测井曲线
            </ActionBtn>
          );
        },
      },
      {
        title: "测井曲线",
        dataIndex: "sjt",
        search: false,
        hideInTable: true,
        formItemProps: {
          ...singleLayout,
          className: styles["single-item-wrap"],
          rules: [
            {
              required: true,
            },
          ],
          valuePropName: "fileList",
          getValueFromEvent: (e) => {
            if (Array.isArray(e)) {
              return e;
            }
            return e && e.fileList;
          }
        },
        fieldProps: (form,config) => {
          return {
            extra: "文件格式支持(FORWARDTXT、TXT、LAS、WIS)",
            maxCount: 1,
          }
        },
        renderFormItem: (schema, config, form) => {
          return <FileUpload {...schema} />;
        },
      },
      {
        width: 128,
        title: "操作",
        valueType: "option",
        render: (text, record, index, action) => {
          return [
            <ActionBtn
              key="shanchu"
              type="link"
              size="small"
              // disabled={disable}
              mode={4}
              icon="icon-shanchu"
              title="删除"
              onClick={async (e) => {
                // 删除接口异步处理
                await deleteData({dbid: record?.dbid});
                action?.reload();
              }}
            >
              删除
            </ActionBtn>,
          ];
        },
      },
    ],
    request: async (params = {}, sort, filter) => getPageList(params),
    form: {
      ...singleLayout,
      form: form, // 经 Form.useForm() 创建的 form 控制实例，不提供时会自动创建
    },
    addForm: {
      title: '测井数据解编录入',
      className: styles["detail-form-wrapper"],
      ...singleLayout,
      layout: "horizontal",
      onFinish: async(values, action) => {
        save(values).then((res) => {
          action?.reload();
          addForm.resetFields();
        }).catch(error => {
          console.log("save error", error)
        })
      },
      trigger: <HocAction icon="icon-plus-lg" title="新增" onClick={async () => {
        added &&
          (await getBoreholeOptions('', (boreholeOptions) => {
            setBoreholeOptions(boreholeOptions);
            setAdded(false);
          }));
      }} />,
      autoFocusFirstInput: true,
      form: addForm, // 经 Form.useForm() 创建的 form 控制实例，不提供时会自动创建
      // modalProps: { destroyOnClose: true }, // form绑定会导致destroyOnClose失效
      // onVisibleChange: visible => {
      //   !visible && addForm.resetFields()
      // }
    },
    editForm: false, // 关闭自定义编辑表单
    viewForm: false, // 关闭自定义查看表单
    pagination: { pageSize: 15 },
  };

  const modalProps = {
    key: currentRecord?.dbid,
    record: currentRecord,
    visible,
    setVisible,
    options: curveOptions,
  };

  return (
    <>
      <QueryList {...props} />;
      <CheckModal {...modalProps} />
    </>
  );
}
`
QueryList ：
`
/**
 * @Description 查询列表组件，包含增、删、改、查等常见功能
 * @Date 2021-11-29 10:31:34
 * @LastEditTime 2022-04-01 09:05:10
 * @Author sunxia <sunxia@chinairi.com>
 * @LastEditors sunxia <sunxia@chinairi.com>
 * @FilePath \src\components\QueryList\index.jsx
 */

import React from "react";
import { HocProTable, HocSchemaForm, ActionBtn, HocAction } from "../index";
import PropTypes from "prop-types";
import {
  setClassName,
  findOption,
  getType,
  reduceUnshift,
} from "../utils/utils";
import "./index.scss";

export default function QueryList(props) {
  const {
    className,
    columns,
    addForm,
    toolBarRender,
    editForm,
    viewForm,
    ...rest
  } = props;

  rest.className = setClassName(className, "query-list-wrapper");

  function getCols(cols, attrs) {
    return [...columns].map((column) => {
      const { key, dataIndex } = { ...column };
      const temp = cols?.filter((item) => item.key === (key || dataIndex))?.[0];
      return { ...column, ...attrs, ...temp };
    }); // 重设columns
  }

  function getInitialValues(initialValues, transform) {
    return getType(transform) === "function"
      ? transform(initialValues)
      : initialValues;
  } // 获取转化后的初始值

  // 有自定义新增表单配置时，生成自定义toolBarRender配置
  if (addForm) {
    rest.toolBarRender = (...params) => {
      const {
        initialValues,
        onFinish,
        showBtn,
        transform,
        trigger,
        columns: addCols = [],
        ...other
      } = {
        ...defaultAddForm,
        ...addForm,
      };
      const show =
        getType(showBtn) === "function" ? showBtn(...params) : showBtn;
      let btns =
        typeof toolBarRender === "function"
          ? toolBarRender(...params) || []
          : [];
      if (show) {
        const action = params?.[0]; // action
        other.columns = getCols(addCols); // 重设columns
        other.initialValues = getInitialValues(initialValues, transform);
        other.onFinish = async (values) => {
          // console.log("addForm onFinish values", values);
          typeof onFinish === "function" && (await onFinish(values, action));
          // action?.reload(); // 刷新列表
          return true; // 返回true,会关掉抽屉
        };
        other.trigger =
          typeof trigger === "function" ? trigger(...params) : trigger;
        // console.log("addForm btns other", btns, other);
        btns?.unshift(<HocSchemaForm {...other} />); // 新增
      }

      return btns;
    };
  }

  // 生成自定义option编辑配置
  const getEditBtn = (params) => {
    const {
      initialValues,
      onFinish,
      showBtn,
      transform,
      trigger,
      columns: editCols = [],
      ...other
    } = {
      ...defaultEditForm,
      ...editForm,
    };
    const show = getType(showBtn) === "function" ? showBtn(...params) : showBtn;
    if (show) {
      const record = params?.[1]; // text, record, index, action
      const action = params?.[3]; // text, record, index, action
      // other.key = params?.[2];
      other.columns = getCols(editCols); // 重设columns
      other.initialValues = getInitialValues(
        initialValues || record,
        transform
      );
      other.onFinish = async (values) => {
        // console.log("getEditBtn onFinish values", values);
        typeof onFinish === "function" && (await onFinish(values, action));
        // action?.reload(); // 刷新列表
        return true; // 返回true,会关掉抽屉
      };
      other.trigger =
        typeof trigger === "function" ? trigger(...params) : trigger;
      // btns?.unshift(<HocSchemaForm {...other} />); // 编辑
      return <HocSchemaForm {...other} />;
    }
    return;
  };

  // 生成自定义option查看配置
  const getViewBtn = (params) => {
    const {
      initialValues,
      onFinish,
      showBtn,
      transform,
      columns: viewCols,
      ...other
    } = {
      ...defaultViewForm,
      ...viewForm,
    };
    const show = getType(showBtn) === "function" ? showBtn(...params) : showBtn;
    if (show) {
      const record = params?.[1]; // text, record, index, action
      // other.key = params?.[2];
      other.columns = getCols(viewCols, { proFieldProps: { mode: "read" } }); // 重设columns
      other.initialValues = getInitialValues(
        initialValues || record,
        transform
      );
      other.onFinish = async (values) => {
        // console.log("getViewBtn onFinish values", values);
        typeof onFinish === "function" && (await onFinish(values, action));
        // action?.reload(); // 刷新列表
        return true; // 返回true,会关掉抽屉
      };
      // btns?.unshift(<HocSchemaForm {...other} />); // 查看
      return <HocSchemaForm {...other} />;
    }
    return;
  };

  const option = findOption(columns);
  if (option) {
    const { render } = { ...option };
    option.render = (...params) => {
      let btns = typeof render === "function" ? [...render(...params)] : [];
      let viewBtn = viewForm ? getViewBtn(params) : null; // 有自定义查看表单配置时
      let editBtn = editForm ? getEditBtn(params) : null; // 有自定义编辑表单配置时
      btns = viewBtn
        ? reduceUnshift(
            btns,
            viewBtn,
            (target, current) => current?.key !== target?.key
          )
        : btns;
      btns = editBtn
        ? reduceUnshift(
            btns,
            editBtn,
            (target, current) => current?.key !== target?.key
          )
        : btns;
      // console.log('option render btns', btns);
      return btns;
    };
  }
  // 过滤非空渲染项，重设render方法，添加默认值

  rest.columns = [...columns];

  return <HocProTable {...rest} />;
}

QueryList.propTypes = {
  columns: PropTypes.array.isRequired, // 表格列的配置描述，查询、编辑表单也从此处获取表单配置项
  addForm: PropTypes.oneOfType([PropTypes.object, PropTypes.bool]), // 新增表单的FormProps,此处指HocSchemaForm,若要关闭自定义新增表单，传false
  editForm: PropTypes.oneOfType([PropTypes.object, PropTypes.bool]), // 编辑表单的FormProps,此处指HocSchemaForm,若要关闭自定义编辑表单，传false
  viewForm: PropTypes.oneOfType([PropTypes.object, PropTypes.bool]), // 查看表单的FormProps,此处指HocSchemaForm,若要关闭自定义查看表单，传false
};

const defaultAddForm = {
  key: "add", // btn的唯一标识，默认add
  layoutType: "ModalForm", // 表单的渲染方式，默认ModalForm
  showBtn: true, // 是否展示触发按钮，支持bool/func，默认true
  trigger: <HocAction icon="icon-plus-lg" title="新增" />, // ModalForm || DrawerForm新增按钮
};

const defaultEditForm = {
  key: "edit", // btn的唯一标识，默认edit
  layoutType: "ModalForm", // 表单的渲染方式，默认ModalForm
  showBtn: true, // 是否展示触发按钮，支持bool/func，默认true
  // trigger: <HocAction icon="icon-edit" title="编辑" />, // ModalForm || DrawerForm编辑按钮
  trigger: (text, record, index, action) => (
    <ActionBtn icon="icon-edit" title="编辑">
      编辑
    </ActionBtn>
  ),
  // transform: (values) => values, // 对初始化数据进行转化处理的函数，一般用于日期处理
};

const defaultViewForm = {
  key: "view", // btn的唯一标识，默认view
  layoutType: "ModalForm", // 表单的渲染方式，默认ModalForm
  showBtn: true, // 是否展示触发按钮，支持bool/func，默认true
  trigger: <HocAction icon="icon-chakan" title="查看" />, // ModalForm || DrawerForm查看按钮
  // trigger: <HocAction icon="icon-chakan" title="查看" >查看</HocAction>,
  // transform: (values) => values, // 对初始化数据进行转化处理的函数，一般用于日期处理
};

QueryList.defaultProps = {
  addForm: defaultAddForm,
  editForm: defaultEditForm,
  viewForm: defaultViewForm,
};
`
HocSchemaForm ：
`
/**
 * @Description JSON 表单组件，初始化BetaSchemaForm部分参数，根据 JSON Schema 来生成表单
 * @Date 2021-12-14 10:50:27
 * @LastEditTime 2022-03-16 10:48:01
 * @Author sunxia <sunxia@chinairi.com>
 * @LastEditors sunxia <sunxia@chinairi.com>
 * @FilePath \src\components\HocSchemaForm\index.jsx
 */

import React, { Component } from 'react';
import { BetaSchemaForm } from '@ant-design/pro-form';
import { IconFont, HocAction } from '../index';
import { defaultValidateMessages } from '../utils/messages';
import { getTimePreRand, setClassName, setProps, getDisplayName } from '../utils/utils';
import './index.scss';

const SchemaFormHoc = (Wrapper) => {
  class HocSchemaForm extends Component {
    render() {
      const {
        className,
        validateMessages,
        modalProps,
        layoutType,
        trigger = <HocAction icon="icon-edit" title="编辑" />,
        ...rest
      } = this.props;
      const props = {
        colon: false, // 是否显示 label 后面的冒号
        name: 'schema-form-' + getTimePreRand(), // 表单名称，会作为表单字段 id 前缀使用
        className: setClassName(className, 'schema-form-wrapper'),
        validateMessages: setProps(validateMessages, defaultValidateMessages), // 验证提示模板
        layoutType,
      };
      // ModalForm || DrawerForm时生效
      if (layoutType === 'ModalForm' || layoutType === 'DrawerForm') {
        props.trigger = trigger;
        props.modalProps = setProps(modalProps, {
          closeIcon: <IconFont type={'icon-close'} />,
        });
      }
      return <Wrapper {...props} {...rest} />;
    }
  }
  HocSchemaForm.displayName = `HocSchemaForm(${getDisplayName(Wrapper)})`;
  return HocSchemaForm;
};

export default SchemaFormHoc(BetaSchemaForm);
`
