### ISSUE TITLE
🧐[问题]ProTale，表单校验不生效

### ISSUE THREAD

**Issue by zhushenhang** [ant-design/pro-components#502]
### 🧐 问题描述
我模仿示例，写了一个必填校验。但是校验未生效，具体看图。
### 💻 示例代码
{
      title: '联系电话',
      dataIndex: 'phone',
      rules: [
        {
          required: true,
          message: '联系电话为必填项',
        },
      ],
    },
### 🚑 其他信息
![图](https://user-images.githubusercontent.com/24982716/93205618-b310ed80-f78a-11ea-9eff-0658999911ff.jpg)

**Comment by chenshuai2144** [comment]
```tsx
formItemProps={
   rules:[]
}
```

要这么用

**Comment by zhushenhang** [comment]
@chenshuai2144 
const columns = [
    {
      title: '联系电话',
      dataIndex: 'phone',
      formItemProps:{
        rules:[
          {
            required: true,
            message: '联系电话为必填项',
          },
        ]
     }
]
还是不生效哟？还需要改哪些配置吗？

**Comment by zhushenhang** [comment]
https://procomponents.ant.design/components/table#%E6%9F%A5%E8%AF%A2%E8%A1%A8%E6%A0%BC 
我模仿这里的例子，搞了一个相同的代码，还是不行。
代码如下
![图](https://user-images.githubusercontent.com/24982716/93458024-580a0280-f912-11ea-8d9b-9e24dbf339b9.jpg)

 const columns =[
  {
    title: '标题',
    dataIndex: 'title',
    copyable: true,
    ellipsis: true,
    tip: '标题过长会自动收缩',
    formItemProps: {
      rules: [
        {
          required: true,
          message: '此项为必填项',
        },
      ],
    },
    width: '30%',
    hideInSearch: true,
  },
];
不过很奇怪的是，我重新新建了一个项目，能生效。这到底是缺了啥配置还是说偶发性问题？

**Comment by Wmstone** [comment]
请问解决了么，我把版本升到最新，还是显示不出校验
