### ISSUE TITLE
🧐[问题] pro-table 2.71.2版本，Columns 列定义里的order属性，影响table列顺序

### ISSUE THREAD

**Issue by zhanghsoft** [ant-design/pro-components#5034]
之前版本里，order属性只负责查询表单中的权重，2.71.2版本里，似乎对table列的顺序也有作用。

**Comment by 321802282** [comment]
遇到了同样的问题，order 对表格列也起到效果了

**Comment by 321802282** [comment]
> 

降回 2.70.0 就可以了

**Comment by kaidouya** [comment]
也遇到同样的问题了

**Comment by chenshuai2144** [comment]
试了下好像不行，谁能搞个重现吗

**Comment by zhanghsoft** [comment]
> 好像下不了了，可能搞个试一下吗

> codesandbox没法用，直接上图了

![image](https://user-images.githubusercontent.com/8437911/162892070-9f63148a-2238-4241-af91-562b191a88aa.png)
![image](https://user-images.githubusercontent.com/8437911/162892186-c077099d-c110-433e-96a5-4d8c3ef2ab2d.png)

**Comment by ILoveChy** [comment]
> > 好像下不了了，可能搞个试一下吗
> 
> > codesandbox没法用，直接上图了
> 
> ![image](https://user-images.githubusercontent.com/8437911/162892070-9f63148a-2238-4241-af91-562b191a88aa.png) ![image](https://user-images.githubusercontent.com/8437911/162892186-c077099d-c110-433e-96a5-4d8c3ef2ab2d.png)

你这两张图看上去没有问题啊..时间因为order数字更大Form在前,table时间在后

**Comment by ILoveChy** [comment]
好吧 自己更新了下..同样的问题 order影响了table顺序

**Comment by chenshuai2144** [comment]
重新更新一下试试
