### ISSUE TITLE
👑 [需求] 希望 Protable 的 search 、 QueryFilter  能够支持单个表单项单独设置所占用 span 属性

### ISSUE THREAD

**Issue by MircoSans** [ant-design/pro-components#5036]
### 🔩 所属模块或组件

搜索组件 ProTable 、 QueryFilter

### 🥰 需求描述

现在配置每个搜索表单的占用空间只能让所有的搜索组件设置同一宽度，希望能给每个表单项单独设置占用空间

``` typescript
export declare type SpanConfig = number | {
    xs: number;
    sm: number;
    md: number;
    lg: number;
    xl: number;
    xxl: number;
};
```

### ⛰ 功能需求适用场景

表单筛选项数据长度短时，占用屏幕空间过大。

**Comment by chenshuai2144** [comment]
可以 用colSize 来设置

**Comment by MircoSans** [comment]
> 可以 用colSize 来设置

如果使用 ProFormItem 的话会提示没有这个属性，但是可以生效
