### ISSUE TITLE
🧐[问题]表单中，有类似key属性吗？key不同，就重新渲染表单项

### ISSUE THREAD

**Issue by wooxyz** [ant-design/pro-components#5037]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/33221294/162707294-569aacfd-8481-4256-901e-a8e07bdb82f2.png)
1、表单联动项中，有公共部分表单项，从item1切换到其他时，能清空里面的值（name保留与后台字段保持一致）。能否通过增加key区分为不同的表单项，这样切换就能清空里面的值。
2、增加类似一个key，便于区分表单，也好维护代码。
3、你可能推荐通过onChange事件来处理，项目业务中由于有大量的联动和公共部分。
 

### 💻 示例代码

https://codesandbox.io/s/ji-ben-shi-yong-forked-bh6hwg?file=/App.tsx

**Comment by chenshuai2144** [comment]
key 是 React 的能力，只要是个组件就有的。

**Comment by wooxyz** [comment]
![image](https://user-images.githubusercontent.com/33221294/162866084-21109af5-5915-407f-8b3f-111b074a1ce8.png)
选择不同的item，对应不同的key（代码里有写啊），那为啥上一次的值还在，不是重新渲染吗?@chenshuai2144

**Comment by chenshuai2144** [comment]
值在form里面存的，form 不清空他一直在的。和dom是分离的
