### ISSUE TITLE
👑 [需求] ModalForm 点击确定按钮后，禁用取消按钮和右上角关闭按钮

### ISSUE THREAD

**Issue by CementSealing** [ant-design/pro-components#5040]
### 🔩 所属模块或组件
  `ModalForm`

### 🥰 需求描述

在`ModalForm`中点击确定按钮，确定按钮loading后，禁用取消按钮和右上角关闭按钮，直到`onFinish`函数完成或代码主动关闭`ModalForm`。

### 🚑 其他信息

![图片](https://user-images.githubusercontent.com/97492682/162916765-21f3fe0b-3fb4-4bab-88f2-a49c00c18686.png)

**Comment by chenshuai2144** [comment]
很有道理呀

**Comment by DerrickTel** [comment]
假如网络较差，那用户体验就很差了，得等待请求完成才可以做别的操作

**Comment by CementSealing** [comment]
> 假如网络较差，那用户体验就很差了，得等待请求完成才可以做别的操作

那可以设置一个超时时间之类的，当超过一定时间还没完成操作时，取消禁用关闭按钮，用户可以选择关闭模态框去做别的操作
