### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by mayaoting** [ant-design/pro-components#5041]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProFormText 内 的onChange 事件，实现将获取到的值存储在一个 已经存有其他值的 store中， 但是在onChange内获取到的 store的值为空对象。

### 🏞 期望结果

原来的store 对象内的值还存在， 并写入新输入的值

### 💻 复现代码
'''
const listenListStore = {
    baseInfo: {
        type:  '1'
    }
}
<ProFormText
              width="lg"
              name="sceneryName"
              label="地标名称"
              placeholder="请输入实际地标名称，不超过10个字"
              required
              rules={[
                { required: true, message: '听单简介不能为空!' },
                { max: 200, message: '字数不能超过200个' },
              ]}
              initialValue={listenListStore.baseInfo.sceneryName}
              fieldProps={{
                onChange: (e) => {
                  const { baseInfo } = listenListStore;
                  console.log('地标名称输入', listenListStore.baseInfo);
                  listenListStore.setInfo({
                    ...baseInfo,
                    sceneryName: e.target.value,
                  });
                },
              }}
            />
'''

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本   3.5.0
- 浏览器环境
- 开发环境 [e.g. mac OS] 
- "@ant-design/pro-form": "^1.18.3",

**Comment by chenshuai2144** [comment]
注意下闭包的问题
