### ISSUE TITLE
👑 [需求] CacheClean 优化

### ISSUE THREAD

**Issue by sarufarr** [ant-design/pro-components#5043]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

`pro-layout` or `pro-provider`

### 🥰 需求描述

`BasicLayout` 使用的 `ConfigProviderWrap` 下有个缓存清理的 `<CacheClean />`
这个处理没问题
只是在 `effect` 里面进行 `cache.clear()` 对用使用了 `<React.StrictMode>` 的项目实在不友好
```
destroy = create()
destroy() // 这里的 cache 已经没了
create()
```
这个问题在 `react@18^` 里尤为明显

### 🧐 解决方案

`clean cache` 放到引用的组件进行初始化`swr config`的副作用中是不是更好

**Comment by sarufarr** [comment]
### 环境:
`react@18.0.0`
`react-dom@18.0.0`
`vite@2.9.1`
`@ant-design/pro-layout@6.34.10`

### 简述:
代码在 `react@18` 下运行 `swr` 无法正常读取 `context` 中的 `cache` 报错被 `ErrorBoundary` 捕捉

## 详情:
`react@18` 的新特性需要使用 `createRoot` [release note](https://github.com/facebook/react/releases/tag/v18.0.0)
项目同时使用了 `StrictMode` 
页面用到了类似文档中[嵌套布局](https://procomponents.ant.design/components/layout/#%E5%B5%8C%E5%A5%97%E5%B8%83%E5%B1%80)的结构
~~嵌套布局导致 `layout` 需要实例化两次 而 `StrictMode` 又完成两次生命周期~~

根据报错简单做了追踪
`BasicLayout` -> `WrapContent` -> `ConfigProviderWrap` -> `CacheClean` -> `useSWRConfig().cache.clear()`

在运行时 `layout-1` 中调用了 `cache` 同时副作用 `cache.clear()` 被执行 组件正常挂载渲染
到了 `layout-1` 内部的 `layout-2` 中 在加载时出现问题：**`cache` 已经被 `clear` 了**
报错 `Uncaught TypeError: Cannot read properties of undefined (reading '0')` 执行终止

但是 `react@17` 下执行同样的代码(**`StrictMode`**) 并不会出现类似的问题 甚至 `ConfigProviderWrap` 的副作用触发次数还少了一次

没有深究 但我觉得是 `concurrent ` 带来的差别

## 其他:
由于`swr` 的 `cache` 实现方案有点。。 或许在每个使用了 `useSWR` 的组件外包一个独立的 `provider` 是不是更好的策略
这样也能放心的在业务代码里面 `cache.clear()` 而不用担心出现不可控的副作用

**Comment by chenshuai2144** [comment]
我这里也没啥好的想法。swr 官方的解决方案是什么？

**Comment by sarufarr** [comment]
swr 似乎不在意这点 不是他们关注点
扔了个 `provider` 出来 补了一句不推荐手动操作
