### ISSUE TITLE
🧐[问题]请问 ProLayout -> Icon not rendering in sidebar submenu 

### ISSUE THREAD

**Issue by umeshn1** [ant-design/pro-components#5049]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

Icon not rendering in sidebar submenu 

![image](https://user-images.githubusercontent.com/53205290/163139056-146d921c-f113-44b8-aabd-cf1a1c58fbe9.png)

**Comment by 1247748612** [comment]
之前有看到 @chenshuai2144  说为了美观故意不展示的

**Comment by umeshn1** [comment]
@Dunqing 是否有任何解决方法可以使它们可见

**Comment by chenshuai2144** [comment]
暂时没有，有兴趣来搞个 PR 吧。
