### ISSUE TITLE
👑 [需求] pro-table 的 beforeSearchSubmit 方法输出值的数据类型是否能支持自定义泛型？

### ISSUE THREAD

**Issue by bluescurry** [ant-design/pro-components#505]
### 🥰 需求描述

``` ts
beforeSearchSubmit?: (params: Partial<U>) => Partial<U>;
```
目前 beforeSearchSubmit 类型是这么定义，有一种场景会有些问题，比如搜索项多选，给后端传数据的时候会要求多个值的情况用逗号连接成一个字符串给后端，这时候就要用到 beforeSearchSubmit 方法。搜索项多选时入参的 params 的值为一个数组，输出是一个字符串，这时候类型定义就会有问题，因为 beforeSearchSubmit 方法要求入参和返回结果的类型一致，但是在某些场景下无法保证一致。

### 🧐 解决方案

是否能让 beforeSearchSubmit 的方法结果支持传入一个自定义的类型，默认还是`U`。

### 🚑 其他信息

目前的解决方法是使用的 `as` 断言
```ts
beforeSearchSubmit={params => {
    const processParams = {
      ...params,
      class: params.class?.join(),
    };
    return processParams as Partial<SearchParams>;
  }}
```

**Comment by chenshuai2144** [comment]
来个 pr？

**Comment by bluescurry** [comment]
1

**Comment by chenshuai2144** [comment]
方法要支持泛型有点难度，你这种方式可能是最合适的。
