### ISSUE TITLE
Protable setActiveKey 和 reload 参数不一致

### ISSUE THREAD

**Issue by Valar103769** [ant-design/pro-components#5050]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/36926073/163152277-d586d7c3-0f43-45a4-b188-342d605a121e.png">
<img width="580" alt="image" src="https://user-images.githubusercontent.com/36926073/163152296-b041e3a9-b0c8-4802-8a7e-9002882086a4.png">

因为setState是异步的,所以`console.log('activeKey', activeKey)`的是上一次的值,这是正常的,
但是为什么`actionRef.current?.reloadAndRest?.()` 能收到最新的值呢? 虽然效果达到了但是感觉不太理解, 希望指点一下

**Comment by chenshuai2144** [comment]
reloadAndRest 拿不到的，是params 改变从新触发了 request，所以request里面拿到了。reloadAndRest也是同样的逻辑。你不 reloadAndRest 也会看到更新了的。
