### ISSUE TITLE
🐛[BUG] ProTable 国际化无效

### ISSUE THREAD

**Issue by Ortonzhang** [ant-design/pro-components#5051]
## 🐛 bug 描述
如图，已将locale设置为英文 antd的Pagination组件是好的 但ProTable依旧是英文

<img width="815" alt="image" src="https://user-images.githubusercontent.com/32766653/163154368-b95f4ae4-6cf3-4959-8a0c-3be996008bf4.png">

## 现象
![image](https://user-images.githubusercontent.com/32766653/163154747-f36ee234-8bbf-470e-8dd5-d746bef30d81.png)

## © 版本信息
"@ant-design/pro-table": "^2.71.5"
"antd": "^4.19.5"

## 🚑 其他信息
1、没有使用 babel-plugin-import 动态加载 antd  
2、使用的微前端架构 antd的语音就是默认的 没有设置中文

**Comment by 1247748612** [comment]
看这 https://github.com/ant-design/pro-components/issues/4962#issuecomment-1083021416
ConfigProvider是配置antd的locale，pro-components需要另外配置

**Comment by Ortonzhang** [comment]
没用 这样试了还是错的 最后的解决方案是添加 babel的babel-plugin-import

```json
{
  "presets": [["@babel/preset-env"], ["@babel/preset-react"]],
    "plugins": [["import", {
    "libraryName": "antd",
    "libraryDirectory": "es"
  }]]
}

```
之前是没有plugins的

**Comment by yaohwu** [comment]
The same happened to me

**Comment by yaohwu** [comment]
same code and using umi to build, it works. wooo

**Comment by Ortonzhang** [comment]
线上更新了版本后发现表格变成了中文，特来更新下，工程现有以下版本，需要将babel的plugins删除才能正常显示英文
"@ant-design/pro-table": "2.78.3"
"antd": "4.22.3"
