### ISSUE TITLE
🐛[BUG]ProTable 在动态主题variable 模式下a标签颜色问题

### ISSUE THREAD

**Issue by faner11** [ant-design/pro-components#5052]
### 🐛 bug 描述
ProTable 在动态主题variable 模式下a标签颜色不与主题色一致

### 📷 复现步骤

项目引入ProTable，改为动态主题模式，修改主题色，添加一个a标签

### 🏞 期望结果
a标签颜色与主题色一致
a 标签为蓝色

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
       "@ant-design/pro-table": "^2.66.4",
        "antd": "^4.19.2",

**Comment by 1247748612** [comment]
一个普通的a标签 并不属于Antd和ProComponents的组件，当然不会继承主题色

你想拥有主题色可以使用 [Typography.Link](https://ant.design/components/typography-cn/) 组件，或给a标签的样式设置`color: var(--ant-primary-color)`

**Comment by faner11** [comment]
> 

antd会将a标签的颜色改为主题色，但是好像pro-table 并不支持动态主题variable 模式下，又将a标签编译为默认的蓝色

**Comment by chenshuai2144** [comment]
搞个截图看看是被谁设置的？

**Comment by cl1107** [comment]
<img width="1577" alt="image" src="https://user-images.githubusercontent.com/21985353/167247938-d05df5ed-4ebc-48da-981d-5cdfc840c948.png">
<img width="515" alt="image" src="https://user-images.githubusercontent.com/21985353/167247962-0f008296-d92d-4298-9a9a-4fd33c61ea88.png">
@chenshuai2144

**Comment by faner11** [comment]
> <img alt="image" width="1577" src="https://user-images.githubusercontent.com/21985353/167247938-d05df5ed-4ebc-48da-981d-5cdfc840c948.png">
> 
> <img alt="image" width="515" src="https://user-images.githubusercontent.com/21985353/167247962-0f008296-d92d-4298-9a9a-4fd33c61ea88.png">
> 
> <img alt="image" width="1606" src="https://user-images.githubusercontent.com/21985353/167248064-29dc1fd0-ee38-40e8-bc0a-88b9919c5cc2.png">
> 
> 看source-map这个样式应该是来自pro-components吧 @chenshuai2144

<img width="601" alt="image" src="https://user-images.githubusercontent.com/26560612/167248560-f8b35378-362d-4b9e-8461-ea40c1a11dec.png">
我通过修改组件和css文件的引入顺序解决了这个问题

**Comment by faner11** [comment]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/26560612/167248806-3ea75d5f-0ea6-4fe9-b606-358a3a3ab37c.png">

**Comment by cl1107** [comment]
> <img alt="image" width="519" src="https://user-images.githubusercontent.com/26560612/167248806-3ea75d5f-0ea6-4fe9-b606-358a3a3ab37c.png">

我是用umi我在最上层layout引入的antd样式

**Comment by chenshuai2144** [comment]
换了主题模式还是不要用css 用了less 吧
