### ISSUE TITLE
🐛[BUG] 'RangePicker' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#5053]
在 ProTable 中 renderFormItem 使用 RangePicker，报错 RangePicker' cannot be used as a JSX component.

**Comment by 1247748612** [comment]
贴代码或codesandbox

**Comment by leshalv** [comment]
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/30397655/163556900-46e68832-89c5-4911-9665-cbb3ebf4ccbd.png">

**Comment by 1247748612** [comment]
完整的，RangePicker哪来的？

**Comment by rivercome** [comment]
maybe you should use it
`const { RangePicker }: any = DatePicker;`

**Comment by leshalv** [comment]
> 完整的，RangePicker 哪来的？

const { RangePicker } = DatePicker;

**Comment by chenshuai2144** [comment]
这个是react 甚至导致的，升级到antd@latest，已经支持了react18

**Comment by katoto** [comment]
> 

不升级react18 咋搞呢，安装哪个版本的proTables

**Comment by Dunqing** [comment]
> > 
> 
> 
> 
> 不升级react18 咋搞呢，安装哪个版本的proTables

最新就行，支持16.8-18
