### ISSUE TITLE
👑 [需求] CheckCard 选中角标

### ISSUE THREAD

**Issue by scrapstation** [ant-design/pro-components#5055]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

CheckCard

### 🥰 需求描述

单选带角标。目前角标不可以配置，多选有角标

### ⛰ 功能需求适用场景

-

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/56467036/163302394-9bd84b78-0811-44f0-b3b6-0d87914ab438.png)

**Comment by wangmeijian** [comment]
@chenshuai2144 这玩意也要加个配置决定显不显示吗？

**Comment by chenshuai2144** [comment]
可以的

**Comment by asself** [comment]
角标怎么去掉呀

**Comment by asself** [comment]
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/17953208/165949813-192c09da-3d2b-4df3-984e-06f4acc326de.png">
把这玩意要么支持配置，默认没有，要么就直接去掉
