### ISSUE TITLE
🐛[BUG]新版本中ProColumns接口无提示

### ISSUE THREAD

**Issue by ikun** [ant-design/pro-components#5056]
### 🐛 bug 描述

当前版本 pro-table@2.71.5 ，在vscode@1.66.2中使用ProColumns接口定义变量时没有补全提示

目测在pro-table版本`小于2.67.0`时是好的

### 📷 复现步骤

```
import type { ProColumns } from '@ant-design/pro-table';

const item: ProColumns = {
  // 在这里呼不出需要的提示
};

item.//在这里可以呼出提示
```

### 🏞 期望结果

能正常使用ts的语法提示

### 💻 复现代码

同复现步骤

### © 版本信息

-  pro-table@2.71.5
-  vscode@1.66.2

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/1317328/163320276-5d8094fe-f035-4daf-8c99-963c0204385d.png)

![image](https://user-images.githubusercontent.com/1317328/163320308-42c1347a-e89d-4f2e-8c4a-26b8ccc2f2f9.png)

**Comment by ikun** [comment]
刚才试了一下
2.56.9也没有提示，2.57.3就可以，不知道为啥

**Comment by 1247748612** [comment]
![image](https://user-images.githubusercontent.com/29533304/163557840-4472420c-cb51-41ff-92e5-e2ab9c731d5d.png)

我这看起来好的

**Comment by 1247748612** [comment]
![image](https://user-images.githubusercontent.com/29533304/163558657-2374f28a-0544-4f9f-be2f-c70101cd0eab.png)

实际项目也可以

试试删除node_modules后重新install下看看

**Comment by chenshuai2144** [comment]
感觉和 TypeScript 的更新有关系。

**Comment by weicong** [comment]
“ProColumns”类是不是应该是单数形式呢，Table的columns属性接受的应该是个数组，那么单数形式 ProColumn 类的数组 ProColumn[] 才对吧。
