### ISSUE TITLE
🧐[问题]EditableProTable，editable为false的情况下，getRowsData可以拿到数据吗？

### ISSUE THREAD

**Issue by Volume3** [ant-design/pro-components#5057]
### 🧐 问题描述
希望实现的功能：一行中有的单元格可以进行编辑，有的单元格不可进行编辑。（如下图的任务名称单元格）
新增一行数据时，原本不可编辑的单元格也可以输入数据。同时getRowsData可以拿到表格所有的数据。

尝试过的方法：
方法一：使用renderFormItem，根据record中的数据判断是否是新增数据，来决定是否返回Input控件。问题是此时getRowsData拿不到新增的数据。
方法二：使用valueType：text，那么（如下图，任务名称单元格）单元格会全部都是可编辑的，但是希望某些单元格不可编辑。
方法三：使用valueType：text，同时editable根据record判断返回true或者false，但是getRowsData拿不到editable为false的数据。
方法四：使用readonly，但是readonly不可以动态进行赋值。

想问一下，有什么办法可以实现我的需求，同时可以使用getRowsData拿到所有数据吗？

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/47254392/163331959-51b10b2e-d005-4067-9b12-1c50cf275bea.png)

**Comment by chenshuai2144** [comment]
```
/**
   *  @name 可编辑表格是否可编辑
   *
   * @example 不允许编辑
   * editable=false
   *
   * @example 如果id=1不允许编辑
   * editable={(value,row,index)=> row.id !==1 }
   */
  editable?: false | ProTableEditableFnType<Entity>;
```

**Comment by Volume3** [comment]
> ```
> /**
>    *  @name 可编辑表格是否可编辑
>    *
>    * @example 不允许编辑
>    * editable=false
>    *
>    * @example 如果id=1不允许编辑
>    * editable={(value,row,index)=> row.id !==1 }
>    */
>   editable?: false | ProTableEditableFnType<Entity>;
> ```

尝试了，如果editable是false的话，getRowsData拿不到这行的数据

**Comment by chenshuai2144** [comment]
这是合理的吧，不然编辑了

**Comment by simplast** [comment]
> 这是合理的吧，不在form里面了，你自己拼下？

数据组件id就不能编辑，但是获取数据居然没有id，这不正常呀

**Comment by YooEcho** [comment]
> > 这是合理的吧，不在form里面了，你自己拼下？
> 
> 数据主键id就不能编辑，但是获取数据居然没有id，这不正常呀

有找到好的解决方案吗？

**Comment by MellowCo** [comment]
离谱

**Comment by q1uxu** [comment]
在表格只有部分行数据可以编辑时，getRowsData获取到的只是这部分行的可编辑单元格数据而不是所有行的数据，而且rowKey的值也不能获取到。。
