### ISSUE TITLE
proTable 照DEMO引入后报错Object(...) is not a function🧐[问题]

### ISSUE THREAD

**Issue by aiyudeleng** [ant-design/pro-components#5059]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
原来的项目使用的是ant design，想使用protable，结果一直报错Object(...) is not a function。在网上看到有人说重新添加一下就可以解决，我重新添加了也不行。具体见截图

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/31436484/163339327-a2219d89-4b24-4cdf-82d2-ee866fed4780.png)
![image](https://user-images.githubusercontent.com/31436484/163339587-1d3139c1-7c16-4267-80aa-470e1a770905.png)

**Comment by aiyudeleng** [comment]
当前已经是最新版本的protable了，2.71.5




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 下午3:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/pro-components] proTable 照DEMO引入后报错Object(...) is not a function🧐[问题] (Issue #5059)





 
以下的 Issues 可能会帮助到你 / The following issues may help you
  
[#4424][Protable defaultSelectedRowKeys not work 🐛[BUG]][62%]

**Comment by chenshuai2144** [comment]
升级的是antd的版本。

**Comment by aiyudeleng** [comment]
antd应该用哪个版本？我现在是4.18.6




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月14日(星期四) 下午4:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/pro-components] proTable 照DEMO引入后报错Object(...) is not a function🧐[问题] (Issue #5059)





 
升级的是antd的版本。
 
&mdash;

**Comment by chenshuai2144** [comment]
最新就行了，干嘛要锁版本
