### ISSUE TITLE
🧐[问题]ProForm声明文件不完全

### ISSUE THREAD

**Issue by itsuki0927** [ant-design/pro-components#506]
### 🧐 问题描述

很奇怪, 安装最新的ProForm, 导入的时候发现没得声明文件, 然后我运行`yarn add @types/ant-design__pro-form -D`说找不到这个包.
然后看到了打包后的ProForm的interface.d.ts,只声明了几个(见下图).

### 🚑 其他信息

<img width="961" alt="Screen Shot 2020-09-16 at 10 35 45 AM" src="https://user-images.githubusercontent.com/40518195/93285840-64099d80-f808-11ea-9a3c-80c5d2f33025.png">

<img width="1001" alt="Screen Shot 2020-09-16 at 10 48 09 AM" src="https://user-images.githubusercontent.com/40518195/93286557-1f7f0180-f80a-11ea-8cf3-b277c8de72ca.png">

**Comment by newketom** [comment]
+1

**Comment by chenshuai2144** [comment]
是 dist-tag 的原因，大家可以重新安装一下依赖解决这个问题
