### ISSUE TITLE
🐛[BUG] ProFormSelect莫名其妙的触发request请求

### ISSUE THREAD

**Issue by wooxyz** [ant-design/pro-components#5065]
### 🐛 bug 描述
操作控制台，无缘无故的会触发ProFormSelect的request请求

### 📷 复现步骤

浏览器的控制台打开：1、拖动改变控制台大小、(或者Console→Network→Console)。2、点击页面的任意处，amazing，居然会触发request。这是什么骚操作。

### 💻 复现代码
https://codesandbox.io/s/ji-ben-shi-yong-forked-tg9tpl?file=/App.tsx

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/33221294/163543286-5841e75e-970d-4807-a53b-4074fcf57793.png)

**Comment by chenshuai2144** [comment]
swr 的功能，离开屏幕重新回来就会触发重新更新。
默认关掉了

**Comment by wooxyz** [comment]
> 默认关掉了，更新下版本

提供的案例pro-Form是1.64.0，咋个更新？
