### ISSUE TITLE
🐛[BUG]ProFromDigit addonAfter 增加seelct样式不对

### ISSUE THREAD

**Issue by ratelgogo** [ant-design/pro-components#5070]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProFromDigit addonAfter 增加seelct样式不对，
不知道怎么设置样式`display: flex; align-items: center;` 改成`align-item:flex-start`就好了

### 📷 复现步骤

https://codesandbox.io/s/yang-shi-cuo-wu-7dhq65?file=/App.tsx
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
"antd": "^4.19.2",
"@ant-design/pro-form": "^1.64.0",
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
求一个修改样式的方法 😄 

<img width="562" alt="image" src="https://user-images.githubusercontent.com/23555154/163677354-60d06cd9-1978-49db-becd-0ddbf9afdca1.png">
<img width="544" alt="image" src="https://user-images.githubusercontent.com/23555154/163677374-15cf387a-2fd7-48bf-b36f-db604abc6cb5.png">

**Comment by Ortonzhang** [comment]
这样写你的ProFormSelect。添加noStyle 属性

<ProFormDigit
        name={["userLimit", "type"]}
        label="用户限购"
        addonAfter={
          <ProFormSelect
            name={["userLimit", "number"]}
            noStyle
            request={async () => [
              { value: "forever", label: "永久" },
              { value: "day", label: "每日" },
              { value: "week", label: "每周" },
              { value: "month", label: "每月" }
            ]}
          />
        }
      />

**Comment by aix-soft** [comment]
> 这样写你的ProFormSelect。添加noStyle 属性
> 
> ```js
> <ProFormDigit
>         name={["userLimit", "type"]}
>         label="用户限购"
>         addonAfter={
>           <ProFormSelect
>             name={["userLimit", "number"]}
>             noStyle
>             request={async () => [
>               { value: "forever", label: "永久" },
>               { value: "day", label: "每日" },
>               { value: "week", label: "每周" },
>               { value: "month", label: "每月" }
>             ]}
>           />
>         }
>       />
> ```

我也有同样的问题。使用noStyle以后可以解决。但是好像不能改宽度？

**Comment by lovewinders** [comment]
> 这样写你的ProFormSelect。添加noStyle 属性
> 
> ```js
> <ProFormDigit
>         name={["userLimit", "type"]}
>         label="用户限购"
>         addonAfter={
>           <ProFormSelect
>             name={["userLimit", "number"]}
>             noStyle
>             request={async () => [
>               { value: "forever", label: "永久" },
>               { value: "day", label: "每日" },
>               { value: "week", label: "每周" },
>               { value: "month", label: "每月" }
>             ]}
>           />
>         }
>       />
> ```

设置noStyle 属性后虽然样式对齐了，但是丢失了rules 必填项错误提示dom

**Comment by lovewinders** [comment]
@chenshuai2144 麻烦看下上述ProFormSelect设置noStyle 属性后，会ProFormSelect设置属性rules={[{ required: true, message: '请输入xxx' }]}【必填项错误提示文字无法显示出来】，但是控制台会报错。我感觉Procomponent Form.Item源码此处应该还是设置align-item:flex-start；
<img width="954" alt="image" src="https://github.com/ant-design/pro-components/assets/22837419/16cbefeb-2056-475b-9d74-b6e2ce29d468">
