### ISSUE TITLE
🐛[BUG] 对antd组件使用按需加载时，全局配置 getPopupContainer无效

### ISSUE THREAD

**Issue by chqfly** [ant-design/pro-components#5072]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

对antd组件使用按需加载时，全局配置 getPopupContainer

<ConfigProvider getPopupContainer={getPopupContainer} locale={zhCN}>
  ...
</ConfigProvider>
pro-components中组件对此无效。

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
看看是不是打包了两份。

https://github.com/ant-design/pro-components/blob/565164193d35d3a9fa1e70c5284a1fedeb416445/.umirc.js#L38

配置应该都用es
