### ISSUE TITLE
🐛[BUG] yarn add @ant-design/pro-table 安装的版本是 1.2.5

### ISSUE THREAD

**Issue by bluescurry** [ant-design/pro-components#508]
### 🐛 bug 描述

npm 发布的版本目前是 1.2.5，不知道为啥，不是都2.x的版本了？？？

### 📷 复现步骤

yarn add @ant-design/pro-table

### 🏞 期望结果

下载最新的 2.x 版本

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
dist -tag 错了
