### ISSUE TITLE
🐛[BUG] 暗黑主题下，color选择器有问题

### ISSUE THREAD

**Issue by jiaicon** [ant-design/pro-components#5082]
![image](https://user-images.githubusercontent.com/34124517/163911731-3f071c8d-e077-418a-a69a-eadee6537250.png)

### 🐛 bug 描述

暗黑主题下，输入框的文字颜色也是白色。

### 📷 复现步骤

https://codesandbox.io/s/schema-biao-dan-forked-vl8zdp?file=/App.tsx

### 💻 复现代码

https://codesandbox.io/s/schema-biao-dan-forked-vl8zdp?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by wangmeijian** [comment]
你的demo无法正常访问 @jiaicon

**Comment by chenshuai2144** [comment]
color组件不支持暗黑模式，等antd@4 支持一下

**Comment by chenshuai2144** [comment]
推荐使用 antd@5  的颜色选择器
