### ISSUE TITLE
🐛[BUG] ModalForm组件设置destroyOnClose为true，弹出Modal窗口时formRef.current为undefined

### ISSUE THREAD

**Issue by zxj963577494** [ant-design/pro-components#5083]
### ProForm v1.57.0 以上

ModalForm组件设置destroyOnClose为true，弹出Modal窗口时formRef.current为undefined

### ProForm v1.57.0

表现正常

### 📷 复现步骤

--

### 🏞 期望结果

最新本正常

### 💻 复现代码

[codesandbox](https://codesandbox.io/s/shi-yong-visible-he-onvisiblechange-forked-o7nsyv?file=/App.tsx)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Dunqing** [comment]
目前还没有适配react@18

**Comment by Arco1ris** [comment]
目前最高适配的是 react 哪个版本，react@17.x 也不行，一直没适配到吗？

**Comment by askurat** [comment]
@zxj963577494 Were you able to workaround this issue?

**Comment by Dunqing** [comment]
看起来在17~18都有这个问题，其实不是没值只是慢了一点，这个问题需要确认下是不是bug

### Workaround

@askurat  You can wrap the code with setTimeout, like this
```ts
setTimeout(() => {
  console.log(formRef.current)
})
```

**Comment by Dunqing** [comment]
突然想了下，这不是bug。虽然拿到了visible是true但此时Modal还未打开，所以也就是Form表单还未渲染出来，所以必须加个setTimeout才能拿到formRef。

可以在ModalForm的onInit事件去使用formRef

**Comment by askurat** [comment]
@Dunqing onInit worked. Thanks.

**Comment by asd116725** [comment]
@Dunqing 很棒，以前编辑内容打开抽屉老是写setTimeout来延时设置表单总感觉不靠谱，现在加一层onInit兼容完美解决。

**Comment by enhengenheng-hubowen** [comment]
onInit并没有在api中标志出来,参数类型也无法得知

**Comment by 1998729** [comment]
这问题啥时候解决
