### ISSUE TITLE
Cannot read properties of undefined (reading '_context')

### ISSUE THREAD

**Issue by dj356988** [ant-design/pro-components#5086]
### 💻 示例代码
![image](https://user-images.githubusercontent.com/24800947/163942362-e740e6ba-f673-4102-bb4b-1757b69ff1a2.png)

**Comment by chenshuai2144** [comment]
升级antd 的版本

**Comment by hxmhxm1** [comment]
> 升级antd 的版本
升级antd到最新版本但是报错仍然存在

**Comment by chenshuai2144** [comment]
好好搞下包管理这个错误只有一个可能，就是antd 低于4.20

**Comment by hxmhxm1** [comment]
您好~这里是黄晓敏邮箱，您的邮件我已经收到了，辛苦了！
