### ISSUE TITLE
🧐[问题]ProTable 表单中其中的一个字段怎么请求接口获取默认值。

### ISSUE THREAD

**Issue by zhushenhang** [ant-design/pro-components#509]
### 🧐 问题描述
小白刚用pro，我现在有个需求，点击新建，打开表单后，其中有个编码字段是默认请求后台接口生成的默认值。请问我怎么在Column 里面去请求接口。或者有什么更好的方法可以生成这个默认值，能否给个示例代码，万分感谢！

**Comment by chenshuai2144** [comment]
initialValue | 设置子元素默认值，如果与 Form 的 initialValues 冲突则以 Form 为准 | string | - | 4.2.0
-- | -- | -- | -- | --


你需要的估计是这个 api
