### ISSUE TITLE
🧐[问题] prolayout菜单side模式收缩状态如何隐藏tooltip

### ISSUE THREAD

**Issue by GuanJdoJ** [ant-design/pro-components#5090]
### 🧐 问题描述

如图，默认情况下hover时会显示一个tooltip，有没有配置隐藏tooltip

### 🚑 其他信息

<img width="175" alt="image" src="https://user-images.githubusercontent.com/30386473/163968554-887ff6c9-33bd-4069-9809-374e3aca8acf.png">

**Comment by qq1170623178** [comment]
写css隐藏呗，这个简单

**Comment by chenshuai2144** [comment]
现在还不支持，有这个还是很重要的
