### ISSUE TITLE
🐛[BUG] ModalForm 第一次打开时 setFieldsValue 无效

### ISSUE THREAD

**Issue by zqran** [ant-design/pro-components#5091]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

使用 ModalForm 组件时，通过 visible 属性控制弹窗的展示或隐藏。
第一次打开 ModalForm 时，`formRef.current?.setFieldsValue()` 无效；关闭对话框，再次打开时，setFieldsValue 才会生效

### 📷 复现步骤

https://codesandbox.io/s/shi-yong-visible-he-onvisiblechange-forked-qtypdx?file=/App.tsx

### 🏞 期望结果

第一次打开 ModalForm 时，`formRef.current?.setFieldsValue()` 有效

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- pro-form: [1.64.1]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Dunqing** [comment]
same issue #5083

**Comment by terrysGp** [comment]
有找到解决办法吗？
