### ISSUE TITLE
🐛[BUG] pro-table type='form' 设置tip没有效果

### ISSUE THREAD

**Issue by meyerlee** [ant-design/pro-components#510]
### 🐛 bug 描述
pro-table type='form'  column.tip  fieldProps.tip 都没有效果。
倒是table模式下，表格头有提示。
an按文档的说法，应该时profield支持tip属性呀。
![image](https://user-images.githubusercontent.com/8414971/93294541-59a5ce80-f81d-11ea-9848-cf67d4256711.png)

### 🏞 期望结果
希望lable有tip效果
### 💻 复现代码

  {
    title: "标题",
    tip: "test",
    fieldProps: { tip: "test" },
    dataIndex: "title",
    copyable: true,
    ellipsis: true,
    width: 200,
    hideInSearch: true
  },
  {
    title: "创建时间",
    key: "since",
    dataIndex: "created_at",
    valueType: "dateTime"
  }

### © 版本信息

- ProTable 版本: [e.g. 2.7.2+]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by gameruleCEO** [comment]
写到formItemProps，透传给item。写到fieldProps不会生效的
