### ISSUE TITLE
🐛[BUG]切换2个protable页面，同字段select筛选request方法不执行

### ISSUE THREAD

**Issue by cfljue** [ant-design/pro-components#5100]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

2个不同的路由页面，页面结构都是ProTable，以page1和page2来表示它们。
这2个页面的搜索表单有相同字段的2个select控件，并各自在2个columns里面配置了request方法。
首先打开page1，查看它的对应的select控件，下拉列表正常。
打开page2页面，查看它的对应的select控件，下拉列表异常。
经测试，page2页面select控件配置的request方法未执行。

### 📷 复现步骤

首先打开page1，查看它的对应的select控件，下拉列表正常。
打开page2页面，查看它的对应的select控件，下拉列表异常。
经测试，page2页面select控件配置的request方法未执行。

### 💻 复现代码
//page1
const columns: ProColumns<ImportClassProps>[] = [
    {
      title: 'page1',
      dataIndex: 'type',
      valueType: "select",
      request: async () => {
        alert('page1执行');
      }
    ]

//page2
const columns: ProColumns<ImportClassProps>[] = [
    {
      title: 'page2',
      dataIndex: 'type',
      valueType: "select",
      request: async () => {
        alert('page2执行');
      }
    ]

### © 版本信息

- @ant-design/pro-table 2.61.0、antd 4.17.0
- umi 3.5.0
- chrome
- 开发环境 [e.g. mac OS]

**Comment by Dunqing** [comment]
这个问题已修复 请更新到最新版本
