### ISSUE TITLE
🧐[问题]当layoutType="Embed"，外层没有form标签时无法监听值变化，是否只能配置fieldProps:{onChange}去各自监听？

### ISSUE THREAD

**Issue by lsh-sihong** [ant-design/pro-components#5101]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
当layoutType="Embed"，外层没有form标签时无法监听值变化，是否只能配置fieldProps:{onChange}去各自监听？

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/49470467/164225567-981c0f57-4f9e-4175-ae03-dadde6641ed0.png)

**Comment by Dunqing** [comment]
embed是让组件嵌套在form组件中使用的

你这个使用场景是什么呢？
