### ISSUE TITLE
🧐[问题] EditableProTable pagination warning after adding a new record

### ISSUE THREAD

**Issue by jalopez526** [ant-design/pro-components#5104]
I've been experiencing the following warning from EditableProTable using pagination:
![image](https://user-images.githubusercontent.com/8070933/164351058-af7aaaec-da24-4379-a32c-49c06ebfdba8.png)

This happen when I try to add a new record using the EditableProTable. Here's a small demo to reproduce:
https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-mfdvth?file=/App.tsx

Steps to reproduce:
1. Open JS console.
2. Click **Add** button
3. You should see the warning on the console.

NOTE: It only happens the first time the button **Add** is clicked. In case you need to reproduce again, you should reload the app.

I'm not sure if this is a bug or if it's maybe something im doing wrong.

**Comment by jalopez526** [comment]
@chenshuai2144 any thoughts on this?

**Comment by chenshuai2144** [comment]
update size and total have no merged update problem, which will not exist in react 18. You can uninstall it first

**Comment by jalopez526** [comment]
You mean update to react 17?

**Comment by chenshuai2144** [comment]
I misunderstood, you can only ignore this question for now. You inserted a row that exceeds the PageSize

**Comment by jalopez526** [comment]
I don't understand. I'm not using data source as new record type. I'm using cache which is default. The pageSize shouldn't be considered until I store in in the data source or am I wrong?

**Comment by chenshuai2144** [comment]
You can ignore it.

There are 10 pages on a page, which is correct. However, after adding a new data, it becomes 11, so an error is reported.

You can refresh your table after adding to make sure the data is correct.

**Comment by jalopez526** [comment]
How can I do that, I just want to get rid of the error. Could you make the fix you mention on the codesandbox?

**Comment by chenshuai2144** [comment]
There is no solution now, you can only pretend it doesn't exist

**Comment by jalopez526** [comment]
I see thanks @chenshuai2144
