### ISSUE TITLE
🧐[问题]renderFormItem中使用ProFormUploadButton组件，上传文件时报错

### ISSUE THREAD

**Issue by guogeer** [ant-design/pro-components#5107]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
renderFormItem中使用ProFormUploadButton组件，上传文件时报错。是使用方式有误还是其他原因，请问Protable中如何上传文件啊

![image](https://user-images.githubusercontent.com/5010851/164398690-b3f2ee84-ec5d-45ac-b1fc-3bda4a5cdc8d.png)

### 💻 示例代码

```
    {
      title: '批量用户',
      dataIndex: 'userfile',
      hideInTable: true,
      renderFormItem: (item, { defaultRender, ...rest }) => {
        return (
          <ProFormUploadButton {...rest} />
        );
      },
    },
```

**Comment by yang-chuanjiang** [comment]
你好！请问你这个问题最后怎么解决的

**Comment by guogeer** [comment]
ProFormUploadButton的问题我解决不了，改用ant design的Upload空间了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月27日(星期五) 上午10:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [ant-design/pro-components] 🧐[问题]renderFormItem中使用ProFormUploadButton组件，上传文件时报错 (Issue #5107)





 
你好！请问你这个问题最后怎么解决的

**Comment by yang-chuanjiang** [comment]
可以贴一下代码吗，困在这好久了，谢谢！

**Comment by guogeer** [comment]
{

&nbsp; &nbsp; &nbsp; title: '批量用户',

&nbsp; &nbsp; &nbsp; dataIndex: 'userfile',

&nbsp; &nbsp; &nbsp; hideInTable: true,

&nbsp; &nbsp; &nbsp; renderFormItem: (item, { defaultRender, type, ...rest }) =&gt; {

&nbsp; &nbsp; &nbsp; &nbsp; return (

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <Upload

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; accept='text/csv'

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; maxCount={1}

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; action='/api/game/upload'

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {...rest}

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &gt;

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <Button icon={<UploadOutlined /&gt;}&gt;上传csv</Button&gt;

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </Upload&gt;

&nbsp; &nbsp; &nbsp; &nbsp; )

&nbsp; &nbsp; &nbsp; },

&nbsp; &nbsp; }







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月27日(星期五) 中午11:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [ant-design/pro-components] 🧐[问题]renderFormItem中使用ProFormUploadButton组件，上传文件时报错 (Issue #5107)





 
可以贴一下代码吗，困在这好久了，谢谢！
