### ISSUE TITLE
👑 [需求] pro-layout  自定义collapsed的位置能否设置的更加灵活

### ISSUE THREAD

**Issue by qq1170623178** [ant-design/pro-components#5111]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

proLayout

### 🥰 需求描述

官方demo里自定义伸缩菜单按钮的位置比较局限，如果在菜单列表里的话，只能放在下方，我看了一下，想放在中间这个位置的方法并没有，或者是我没发现？

### ⛰ 功能需求适用场景

适配ui或者和别的产品嵌套时保持样式一样

**Comment by chenshuai2144** [comment]
看看源码，每个位置都有很多的口子开给你的。
