### ISSUE TITLE
👑 [需求] ProTable column列定义中设置默认不展示 但在options setting中可将它勾选显示出来

### ISSUE THREAD

**Issue by owendswang** [ant-design/pro-components#5112]
### 🔩 所属模块或组件

ProTable

### 🥰 需求描述

目前ProTable的columns定义中，可以设置hideInTable将该列设置为不显示，但前端没有将其手动显示出来的功能。
我想让某些列默认不显示，但是在ProTable的optons的setting中，可以将这些默认不显示的列，打勾显示出来。

### ⛰ 功能需求适用场景

就是让某些列默认不显示，但是可以在options setting中手动打勾显示出来。

### 🧐 解决方案

我没有找到对应功能的方法，所以不得不想你们求助。

### 🚑 其他信息

无

**Comment by owendswang** [comment]
没事了，找到了，它叫“受控的表格设置栏”：
https://procomponents.ant.design/components/table#%E5%8F%97%E6%8E%A7%E7%9A%84%E8%A1%A8%E6%A0%BC%E8%AE%BE%E7%BD%AE%E6%A0%8F

另外还找到了hideInSetting选项，控制是否在setting里显示这一列。

抱歉打扰了！

**Comment by wenqi73** [comment]
感谢楼主

**Comment by NinoHuang** [comment]
感谢楼主
