### ISSUE TITLE
🧐[问题] ProFormSelect怎么样只获取key啊

### ISSUE THREAD

**Issue by jiangxiaoqiang** [ant-design/pro-components#5113]
### 🧐 问题描述

现在用ProFormSelect编辑用户角色，但是提交或者change事件里，用户目前的角色获取到的是名字(当前用户已经有的角色)，新的编辑的角色获取到的是key，是否能够统一？我怎么做才能够获取统一的角色ID？https://stackoverflow.com/questions/71976565/how-to-handle-the-antd-proformselect-multiselect-submit-value

### 💻 示例代码

```
<ProFormSelect
          name="roles"
          width="md"
          fieldProps={{
            mode: 'multiple',
            onChange: handleChange
          }}
          initialValue={rolesNames}
          valueEnum={getRolePair(users?.roles)}
          label={
            intl.formatMessage({
              id: 'pages.permission.user.searchTable.roles',
              defaultMessage: '角色',
            })
          }
        >
        </ProFormSelect>
```

### 🚑 其他信息

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/4521375/164874479-e463577c-e15b-4903-9cd2-8f44814356f4.png">

**Comment by chenshuai2144** [comment]
数据要自己拼的，select 返回你的都 valueEnum 里面的 value，你自己处理数据的时候要处理好

**Comment by jiangxiaoqiang** [comment]
第一次选择的时候是key，自动加载上次选择的时候是value，新选择的是key。要么统一key，要么统一value，要么key value都给啊。这样怎么处理？


<img width="1227" alt="image" src="https://user-images.githubusercontent.com/4521375/166171920-c2f3ee1c-f227-43cb-9328-b276496774f2.png">

**Comment by symbolbit** [comment]
可以换一种思路做
