### ISSUE TITLE
🐛[BUG] Form.Item 自定义组件，无法触发表单校验

### ISSUE THREAD

**Issue by twinkle77** [ant-design/pro-components#5115]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
使用 create-react-app 创建的项目，引入 pro-form，使用 antd 的 Form.Item 组件，在提交时，无法触发表单校验

![image](https://user-images.githubusercontent.com/17792166/164953975-80bacd48-58a2-4708-a9c4-953f6fdef9cb.png)

### 🏞 期望结果

提交时，会有表单验证不通过的提示

### 💻 复现代码

```

import './App.css';
import React from 'react'
import ProForm, { ProFormText } from '@ant-design/pro-form';
import { message, Form, Input, version } from 'antd'

const waitTime = (time = 100) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(true);
    }, time);
  });
};

console.log('version', version)

function App() {
  return (
    <div className="App">
      <ProForm
        onFinish={async (values) => {
          await waitTime(2000);
          console.log(values);
          message.success('提交成功');
        }}
      >
      <Form.Item
        label="Username"
        name="username"
        required
        rules={[{ required: true, message: "1233Please input your username!" }]}
      >
        <Input />
      </Form.Item>
    </ProForm>
    </div>
  );
}
```

### © 版本信息

"@ant-design/pro-form": "^1.64.1",
"antd": "^4.19.5",
"react": "^17.0.2",
"react-dom": "^17.0.2",

mac 机器

### 🚑 其他信息

奇怪的是， codeSanbox 无法复现- https://codesandbox.io/s/proform-he-editabletable-tong-shi-shi-yong-forked-qvh63d?file=/App.tsx

但在本地几个工程都能复现 bug

**Comment by chenshuai2144** [comment]
应该是antd 和 ProForm 没对上，你打包了两份antd 进去，你可以试着都从es包引入代码
