### ISSUE TITLE
🐛[BUG]EditableProTable 改变value数据的顺序后, 在actionRender中无法获取数据最新的状态

### ISSUE THREAD

**Issue by zhoufeng215207** [ant-design/pro-components#5125]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by 15723185734** [comment]
用box写个dom吧

**Comment by chenshuai2144** [comment]
hooks 是闭包的，要实时数据请用ref
