### ISSUE TITLE
有没有angular的例程？🧐[问题]

### ISSUE THREAD

**Issue by wen2204** [ant-design/pro-components#5126]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

文档示例都是react的，有没有angular的示例的？

**Comment by wangmeijian** [comment]
这是基于React技术栈封装的，Angular请看https://ng.ant.design/docs/introduce/zh
