### ISSUE TITLE
🐛[BUG]pro-layout发布忘了去掉log

### ISSUE THREAD

**Issue by Ives7** [ant-design/pro-components#5128]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

pro-layout发布忘了去掉log
### 📷 复现步骤

运行即可

### 🏞 期望结果

看不到log
### 💻 复现代码

  var menuData = props.menuData;
  /** 如果是分割菜单模式，需要专门实现一下 */

  if (splitMenus && (openKeys !== false || layout === 'mix') && !isMobile) {
    var _matchMenuKeys = _slicedToArray(matchMenuKeys, 1),
        key = _matchMenuKeys[0];

    if (key) {
      var _props$menuData, _props$menuData$find;

      menuData = ((_props$menuData = props.menuData) === null || _props$menuData === void 0 ? void 0 : (_props$menuData$find = _props$menuData.find(function (item) {
        return item.key === key;
      })) === null || _props$menuData$find === void 0 ? void 0 : _props$menuData$find.routes) || [];
    } else {
      menuData = [];
    }
  } // 这里走了可以少一次循环

  var clearMenuData = clearMenuItem(menuData || []);
  console.log(clearMenuData);

  if (clearMenuData && (clearMenuData === null || clearMenuData === void 0 ? void 0 : clearMenuData.length) < 1 && splitMenus) {
    return null;
  }

### © 版本信息

- ProComponents 版本: 6.36.0

### 🚑 其他信息

去掉这行  console.log(clearMenuData); 即可

**Comment by chenshuai2144** [comment]
pr 合并了，明天发
