### ISSUE TITLE
🐛[BUG] Not work in NextJS with SSR

### ISSUE THREAD

**Issue by simon-zhangmuye** [ant-design/pro-components#5129]
I found a way to use NextJS with AntD Pro Components.
It works with next with less package.
The only problem is that i have to use dynamic import and set SSR to false.
Hope the author can fix this bug.

**Comment by simon-zhangmuye** [comment]
It is not recommended to use AntD pro components in NextJS.
There are more bugs than the number of stars in the universe.

**Comment by abdeljalil09** [comment]
you can use @mpth/react-no-ssr worked for me at least to remove React Hydration Error

**Comment by abdeljalil09** [comment]
```
interface Props {
  children: any; // React.ReactNode
  fallback?: any; // JSX.Element
}

const NoSSR = ({ children, fallback = null }: Props) => {
  const [mounted, setMounted] = useState(false);

  useEffect(() => setMounted(true), []);

  if (!mounted) {
    return fallback;
  }

  return children;
};

export default NoSSR;
```
