### ISSUE TITLE
🐛[BUG] 升级 ant 4.2.0 Warning: [antd: Menu] `children` will be removed in next major version. Please use `items` instead.

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#5130]
Warning: [antd: Menu] `children` will be removed in next major version. Please use `items` instead.

**Comment by chenshuai2144** [comment]
ref to https://github.com/ant-design/pro-components/commit/e7606ff2990719402b14d7bc1c2b32c2113ccfac

**Comment by puxiao** [comment]
修改如下即可解决：

```diff
- <Menu>
-    <Menu.Item> ... </Menu.Item>
- </Menu>

+ const menuItems = [
+    {
+        key: 'center',
+        icon: <UserOutlined />,
+        label: '个人中心',
+    },
+    {
+        key: 'settings',
+        icon: <SettingOutlined />,
+        label: '个人设置',
+    },
+    {
+        key: 'logout',
+        icon: <LogoutOutlined />,
+        label: '退出登录',
+    },
+];
+ <Menu items={menuItems} />
```



更多示例可参考：

https://github.com/ant-design/ant-design/pull/34559/commits/72468a2015f5aa7397d9b41792adc8f50e4f93ab

**Comment by gudh** [comment]
anyone knows how to add className to menu item?

Seems [there](https://ant.design/components/menu/#MenuItemType) isn't a property for adding CSS classes

Before, v4.20.0, I was adding it directly to `Menu.item`

```jsx
<Menu.Item className="blabla"> ... </Menu.Item>
```

**Comment by zhugexinxin** [comment]
![image](https://user-images.githubusercontent.com/42615243/165548526-dee84767-9ced-4050-9aa3-fa0495c53d05.png)
已经将src/components/RightContent/AvatarDropdown.tsx文件做了修改还是报这个警告
![image](https://user-images.githubusercontent.com/42615243/165548738-4e143524-8000-436f-97c6-2c6df3b4d0e8.png)

**Comment by zhouzyc** [comment]
一样问题：
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/18420689/165660382-93e0c79c-d8ff-4bb2-8ef1-05a8cf0e3a5a.png">
看这个错误应该是侧边栏报出来的，目前还是一直存在

**Comment by Mankvis** [comment]
同样的问题，暂未解决

**Comment by zhugexinxin** [comment]
> @zhugexinxin 我看了一下源码： https://github.com/ant-design/ant-design/blob/master/components/menu/index.tsx
> 
> ```
> devWarning(
>     !!items && !children,
>     'Menu',
>     '`children` will be removed in next major version. Please use `items` instead.',
> );
> ```
> 
> devWarning = (valid: boolean, component: string, message: string): void => { ... }
> 
> devWarning() 第一个参数值应该为 false(无效) 时会发出警告。
> 
> 按照 `!!items && !children` 这个条件，我们使用了 items，并且没有使用 children 情况下，其结果为 true(有效)，确实不应该报这个警告了。

layout版本我尝试升级到最新是如此

**Comment by Mankvis** [comment]
> ![image](https://user-images.githubusercontent.com/42615243/165548526-dee84767-9ced-4050-9aa3-fa0495c53d05.png)
> 
> 在antdpro里已经将src/components/RightContent/AvatarDropdown.tsx文件做了修改还是报这个警告
> 
> ![image](https://user-images.githubusercontent.com/42615243/165548738-4e143524-8000-436f-97c6-2c6df3b4d0e8.png)
> 
> 看起来是像是侧边栏的封装里报的

请问您这个问题解决了吗

**Comment by Mankvis** [comment]
> 已经

请问您这个问题解决了吗

**Comment by chenshuai2144** [comment]
已经发布了新版本了，更新

**Comment by Es-Rell** [comment]
> 已经发布了新版本了，更新一下

@ant-design/pro-layout v6.35.0  最新版问题依旧

**Comment by dake0505** [comment]
> > 已经发布了新版本了，更新一下
> 
> @ant-design/pro-layout v6.35.0  最新版问题依旧
 V6.37.0 问题依旧

**Comment by zhouzyc** [comment]
> 已经发布了新版本了，更新一下

新版本的npm似乎没有发布
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/18420689/166853575-2d3a1a01-c257-40d8-8ed8-4c70b771a897.png">

**Comment by Es-Rell** [comment]
强制更新6.37.0已解决

**Comment by xingw-z** [comment]
更新了 @ant-design/pro-layout@6.37.0  也没有解决

**Comment by zhangyuezhong** [comment]
我用antd  4.20.6,没有使用pro-layout， 也出现这个警告。 我连antd: Menu 都没有用。

**Comment by puxiao** [comment]
我看你们还在说这个事情，2 周前我忘了升级哪个包之后就不再报这个警告了。

后来 ant-pro 官方也升级了版本，目前最新版的 ant-pro，已经不报这个错误了。

**Comment by Junaid300** [comment]
I have impletement onClick event on Menu.Item
`<Menu >
      <Menu.Item key={1} onClick={handleLogOut}>
        Log Out
      </Menu.Item>
    </Menu>`
    I was getting this warning
![image](https://user-images.githubusercontent.com/66414908/170932628-9f625dd3-b15a-4d68-8196-4d219c0f69ed.png)

and changed my code to this.


`
<Menu  items={item} />
`
Now how can i implement onClick event ?

**Comment by choi2k** [comment]
```js

const onMenuClick = (event: MenuInfo) => {
      const { key } = event
... 
}


  const menuItems = [
    {
      key: 'logout',
      icon: <LogoutOutlined />,
      label: '退出登录',
    },
  ]

  const menuHeaderDropdown = () => (
    <Menu className={styles.menu} selectedKeys={[]} onClick={onMenuClick} items={menuItems} />
  )
```

try this?

**Comment by Junaid300** [comment]
@choi2k  thank you it worked for me. I hope AntD community will update its documentation soon.

**Comment by buraketmen** [comment]
How can we use the Popconfirm component in this new design?
```
<Popconfirm
    title="Are you sure?"
    placement="leftBottom"
    cancelButtonProps={{ type: 'primary', danger: true }}
    onConfirm={() => this.deleteRecord(record.id)}
    okText="Yes"
    cancelText="No"
>
    <Menu.Item key="Delete"><i className='ik ik-trash' />Delete</Menu.Item>
</Popconfirm>
```

**Comment by faysal-hub** [comment]
warning.js:6 Warning: [antd: Menu] `children` will be removed in next major version. Please use `items` instead.
` <Menu theme="dark">
          <Menu.Item icon={<HomeOutlined />}>
            <Link to="/">Home</Link>
          </Menu.Item>
          <Menu.Item icon={<FundOutlined />}>
            <Link to="cryptocurrencies">Cryptocurrencies</Link>
          </Menu.Item>
          <Menu.Item icon={<MoneyCollectOutlined />}>
            <Link to="/exchanges">Exchanges</Link>
          </Menu.Item>
          <Menu.Item icon={<BulbOutlined />}>
            <Link to="/news">News</Link>
          </Menu.Item>
        </Menu>`

what about link inside of the Menu.Item?? Advance thanks

**Comment by peter-popluhar** [comment]
> warning.js:6 Warning: [antd: Menu] `children` will be removed in the next major version. Please use `items` instead. what about the link inside of the Menu.Item?? Thanks
> 
> ```
>       <Menu.Item icon={<HomeOutlined />}>
>         <Link to="/">Home</Link>
>       </Menu.Item>
> ```

Look at this example, there is a custom link in Items (Navigation Four - link):
https://ant.design/components/menu/#components-menu-demo-horizontal

**Comment by ghazyhm** [comment]
warning.js:6 Warning: [antd: Menu] `children` will be removed in next major version. Please use `items` instead.

**Comment by EbokianKnight** [comment]
What if we need to render a badge or have custom styling for a single menu item?

**Comment by buraketmen** [comment]
> How can we use the Popconfirm component in this new design?
> 
> ```
> <Popconfirm
>     title="Are you sure?"
>     placement="leftBottom"
>     cancelButtonProps={{ type: 'primary', danger: true }}
>     onConfirm={() => this.deleteRecord(record.id)}
>     okText="Yes"
>     cancelText="No"
> >
>     <Menu.Item key="Delete"><i className='ik ik-trash' />Delete</Menu.Item>
> </Popconfirm>
> ```

Are there any updates regarding this problem?

**Comment by uneconomicalfairy14** [comment]
> > warning.js:6 Warning: [antd: Menu] `children` will be removed in the next major version. Please use `items` instead. what about the link inside of the Menu.Item?? Thanks
> > ```
> >       <Menu.Item icon={<HomeOutlined />}>
> >         <Link to="/">Home</Link>
> >       </Menu.Item>
> > ```
> 
> Look at this example, there is a custom link in Items (Navigation Four - link): https://ant.design/components/menu/#components-menu-demo-horizontal

can someone convert this to the latest format

**Comment by leqnam** [comment]
> > > warning.js:6 Warning: [antd: Menu] `children` will be removed in the next major version. Please use `items` instead. what about the link inside of the Menu.Item?? Thanks
> > > ```
> > >       <Menu.Item icon={<HomeOutlined />}>
> > >         <Link to="/">Home</Link>
> > >       </Menu.Item>
> > > ```
> > 
> > 
> > Look at this example, there is a custom link in Items (Navigation Four - link): https://ant.design/components/menu/#components-menu-demo-horizontal
> 
> can someone convert this to the latest format

Try this:

```
const onSelectMenu= (item: any): void => {
      history.push(item.key);
}

<Menu
      // mode=
      onClick={onSelectMenu}
      items={[
            {
                  key: '/',
                  icon: <HomeOutlined />,
                  label: 'Home',
            },
]}
```

**Comment by RagnorLixiaomeng** [comment]
in antd 5 what about the link inside of the Menu.Item?? Thanks,i still can't find the right way 
 
       <Menu.Item icon={<HomeOutlined />}>
        <Link to="/">Home</Link>
      </Menu.Item>

**Comment by kirasiris** [comment]
> in antd 5 what about the link inside of the Menu.Item?? Thanks,i still can't find the right way
> 
> ```
>    <Menu.Item icon={<HomeOutlined />}>
>     <Link to="/">Home</Link>
>   </Menu.Item>
> ```

@RagnorLixiaomeng , @EbokianKnight 

I believe someone already posted what to do about the children components of X menu; take a look:

```
const getItem = (key, icon, children, label, type, className, link) => {
  return {
    key,
    icon,
    children,
    label: <Link to={link}>{label}</Link>,
    type,
    className,
    link,
  }
}

const items = [
  getItem(
    'blogs',
    <i className="fa-solid fa-file-lines" />,
    [
      getItem('blogs-1', null, null, 'All Blogs', null, null, '/admin/blogs'),
      getItem(
        'blogs-2',
        null,
        null,
        'Add New',
        null,
        null,
        '/admin/blogs/create'
      ),
      getItem(
        'blogs-3',
        null,
        null,
        'Categories',
        null,
        null,
        '/admin/blogs/categories'
      ),
    ],
    'Blogs',
    null,
    null,
    null
  ),
]

return (
  <Menu
    mode="inline"
    defaultSelectedKeys={['blogs-1']}
    defaultOpenKeys={['blogs']}
    items={items}
  />
)
```

That's what I came up with and it works great so far.

**Comment by pranavkangale5** [comment]
<Menu
        theme="dark"
        items={[
          {
            key: "1",
            icon: <HomeOutlined />,
            label: "Home",
            
          },
          {
            key: "2",
            icon: <FundOutlined />,
            label: "Cryptocurrencies",
            link: "/cryptocurrencies",
          },
          {
            key: "3",
            icon: <MoneyCollectOutlined />,
            label: "News",
            link: "/news",
          },
          {
            key: "4",
            icon: <BulbOutlined />,
            label: "Exchanges",
            link: "/exchanges",
          },
        ]}
      />
    </div>
  );
};

**Comment by rayyventura** [comment]
> 

Any solutions to this. How to use a HOC with this new approach ?

**Comment by Sumanthbabu-Muthineni** [comment]
import { Menu, Button } from "antd";
import {
  MenuUnfoldOutlined,
  MenuFoldOutlined,
  DesktopOutlined,
  PieChartOutlined,
} from "@ant-design/icons";
import { useState } from "react";
import ReactPlayer from "react-player";
import Reference from "../videoReference";
import "./index.css";

// Function to create menu item object
function getItem(key, videoid, icon, label, items) {
  return {
    key,
    videoid,
    icon,
    label: label || key, // set the label to the provided value or the key if not provided
    items:
      items &&
      items.map((childItem) =>
        getItem(
          childItem.title,
          childItem.id,
          childItem.icon,
          childItem.name,
          childItem.items
        )
      ), // recursively map sub-options
  };
}

function AntNav() {
  const [collapsed, setCollapsed] = useState(false);
  const [videoUrl, setVideoUrl] = useState("https://www.w3schools.com/html/mov_bbb.mp4");

  const jsonData = [
    {
      title: "Option 1",
      id: "Copy%20of%20Virinchi_DB101",
      icon: <PieChartOutlined />,
      name: "Option 1",
      items: null,
    },
    {
      title: "Option 2",
      id: "N9pRgID9Vz0",
      icon: <DesktopOutlined />,
      name: "Option 2",
      items: null,
    },
    {
      title: "Option 3",
      id: "nxLaOaGqML8",
      icon: <PieChartOutlined />,
      name: "Option 3",
      items: [
        {
          title: "Sub-Option 1",
          id: "gS9_zZxQnVE",
          icon: <PieChartOutlined />,
          name: "Sub-Option 1",
          items: null,
        },
        {
          title: "Sub-Option 2",
          id: "l0U7SxXHkPY",
          icon: <DesktopOutlined />,
          name: "Sub-Option 2",
          items: null,
        },
      ],
    },
    {
      title: "Option 4",
      id: "IdycGVN4z0I",
      icon: <DesktopOutlined />,
      name: "Option 4",
      items: null,
    },
    {
      title: "Option 5",
      id: "XATIxcou220",
      icon: <PieChartOutlined />,
      name: "Option 5",
      items: null,
    },
    {
      title: "Option 6",
      id: "PiqgERZKoIM",
      icon: <DesktopOutlined />,
      name: "Option 6",
      items: [
        {
          title: "Sub-Option 3",
          id: "kmf-p-pTi40",
          icon: <PieChartOutlined />,
          name: "Sub-Option 3",
          items: null,
        },
        {
          title: "Sub-Option 4",
          id: "jWx5hYj4pOI",
          icon: <DesktopOutlined />,
          name: "Sub-Option 4",
          items: null,
        },
        {
          title: "Sub-Option 5",
          id: "jgYX6vE7W-I",
          icon: <DesktopOutlined />,
          name: "Sub-Option 5",
          items: null,
        },
      ],
    },
    {
      title: "Option 7",
      id: "PiqgERZKoIM",
      icon: <DesktopOutlined />,
      name: "Option 7",
      items: [
        {
          title: "Sub-Option 6",
          id: "kmf-p-pTi40",
          icon: <PieChartOutlined />,
          name: "Sub-Option 6",
          items: null,
        },
        {
          title: "Sub-Option 7",
          id: "jWx5hYj4pOI",
          icon: <DesktopOutlined />,
          name: "Sub-Option 7",
          items: null,
        },
        {
          title: "Sub-Option 8",
          id: "jgYX6vE7W-I",
          icon: <DesktopOutlined />,
          name: "Sub-Option 8",
          items: null,
        },
        {
          title: "Sub-Option 9",
          id: "jgYX6vE7W-I",
          icon: <DesktopOutlined />,
          name: "Sub-Option 9",
          items: null,
        },
        {
          title: "Sub-Option 10",
          id: "jgYX6vE7W-I",
          icon: <DesktopOutlined />,
          name: "Sub-Option 10",
          items: null,
        },
      ],
    },
    {
      title: "Option 8",
      id: "PiqgERZKoIM",
      icon: <DesktopOutlined />,
      name: "Option 8",
      items: [
        {
          title: "Sub-Option 11",
          id: "kmf-p-pTi40",
          icon: <PieChartOutlined />,
          name: "Sub-Option 11",
          items: null,
        },
        {
          title: "Sub-Option 12",
          id: "jWx5hYj4pOI",
          icon: <DesktopOutlined />,
          name: "Sub-Option 12",
          items: null,
        },
        {
          title: "Sub-Option 13",
          id: "jgYX6vE7W-I",
          icon: <DesktopOutlined />,
          name: "Sub-Option 13",
          items: null,
        },
        {
          title: "Sub-Option 14",
          id: "jgYX6vE7W-I",
          icon: <DesktopOutlined />,
          name: "Sub-Option 14",
          items: null,
        },
        {
          title: "Sub-Option 15",
          id: "jgYX6vE7W-I",
          icon: <DesktopOutlined />,
          name: "Sub-Option 15",
          items: null,
        },
      ],
    },
  ];

  // Convert JSON data to menu item objects

  const items = jsonData.map((item) => {
    const { title, id, icon, name, items } = item;
    return getItem(title, id, icon, name, items);
  });

  const toggleCollapsed = () => {
    setCollapsed(!collapsed);
  };

  const getMenuItems = (items) => {
    const handleMenuItemClick = (videoid) => {
      setVideoUrl(`https://dai.ly/${videoid}`);
    };

    return items.map((item) => {
      if (item.items) {
        // Sub-menu item
        const subMenuItems = getMenuItems(item.items); // Recursively get the menu items for sub-options
        return (
          <Menu.SubMenu key={item.key} icon={item.icon} title={item.label}>
            {subMenuItems}
          </Menu.SubMenu>
        );
      } else {
        const { key, videoid, icon, label } = item;
        return (
          <Menu.Item
            key={key}
            icon={icon}
            onClick={() => handleMenuItemClick(videoid)}
          >
            {label}
          </Menu.Item>
        );
      }
    });
  };

  const handleMenuItemClick = (videoid) => {
    setVideoUrl(`https://dai.ly/${videoid}`);
  };

  return (
    <div style={{ display: "flex"}}>
      <div className={collapsed ? "navWidth" : "navBarOverflow"} >
        <div>
          <Button
            type="primary"
            onClick={toggleCollapsed}
            style={{
              backgroundColor: "#001529",
              borderRadius: "0px",
              height: "50px",
            }}
          >
            {collapsed ? (
              <MenuUnfoldOutlined
                style={{ fontSize: "1.5rem", width: "48px" }}
              />
            ) : (
              <MenuFoldOutlined style={{ fontSize: "2rem", width: "224px" }} />
            )}
          </Button>
        </div>

        {/* course Menu  */}
        <Menu
          style={{ fontSize: "1rem", height: "100vh" }}
          defaultSelectedKeys={["1"]}
          defaultOpenKeys={["sub1"]}
          mode="inline"
          theme="dark"
          inlineCollapsed={collapsed}
          onClick={({ key }) => {
            if (typeof key === "string") {
              handleMenuItemClick(key);
            }
          }}
        >
          {getMenuItems(items)}
        </Menu>
      </div>
      <div
        className={collapsed ? "videoPageContainer2" : "videoPageContainer1"}
      >
        <div className="videoplayer">
          {videoUrl && (
            <ReactPlayer
              //disabled download button
              config={{ file: { attributes: { controlsList: "nodownload" } } }}
              // Disabled right click to avoid downloading
              onContextMenu={(e) => e.preventDefault()}
              width="70%"
              height="100%"
              padding="15px"
              url={videoUrl}
              controls
            />
          )}
        </div>

        <Reference />
      </div>
    </div>
  );
}


export default AntNav; 
 got this error: warning.js:6 Warning: [antd: Menu] children will be removed in the next major version. Please use items instead...how can i rid off this warning,tried different ways,no use..

**Comment by dzcpy** [comment]
Actually why should it be changed in the first place? What's wrong with Menu.Item? And how to style the menu item?

**Comment by jonasmarco** [comment]
Can someone help me? I did the implementation in a Next JS project, the issue is that here I use the Next Link to direct me to other pages and if I use the Menu items props, the clicks on the links do not work.

```
const menuItens = [
    {
      key: '/',
      label: 'Home'
    },
    {
      key: 'characters',
      label: 'Characters'
    },
    {
      key: 'episodes',
      label: 'Episodes'
    }
  ]
  <Menu theme="dark" mode="horizontal" items={menuItens}>
    {menuItens.map((item) => (
      <Menu.Item key={item.key}>
        <Link href={`/${item.key}`}>{item.label}</Link>
      </Menu.Item>
    ))}
  </Menu>
```

**Comment by AnanduKarthi** [comment]
`export const MenuItems = styled(Menu.Item)`
  &.ant-menu-item-selected {
    background-color: ${colorChange} !important;
  }
`;`

I'm  using the ant d menu as shown above to the extent to build my style component, how come after the update Im able to do that

**Comment by smile199705** [comment]
> 相同问题： 看这个错误应该是侧边栏出来的，目前还是一直存在 <img alt="图像" width="1038" src="https://user-images.githubusercontent.com/18420689/165660382-93e0c79c-d8ff-4bb2-8ef1-05a8cf0e3a5a.png">

xdm这个问题解决了吗？

**Comment by smile199705** [comment]
> 其实，为什么首先要改变它呢？Menu.Item 有什么问题？以及如何设置菜单项的样式？

你这边有解决吗？

**Comment by andyFang94** [comment]
![image](https://github.com/ant-design/pro-components/assets/54627989/5f4f6b5b-ca88-4069-80ca-5d616260accb)

**Comment by junkiet** [comment]
"antd": "^5.12.8" 也一样包错

**Comment by khamid4575** [comment]
```
const items = [
    {
        key: "home",
        icon: <HomeOutlined />,
        label: "Home"
    },
    {
        key: "activity",
        icon: <AppstoreOutlined />,
        label: "Activity"
    },
    {
        key: "tasks",
        icon: <BarsOutlined />,
        label: "Tasks",
        children: [
            { key: "task-1", label: "Task 1" },
            { key: "task-2", label: "Task 2" },
            { key: "subtasks", label: "Subtasks", children: [
              { key: "subtask-1", label: "Subtask 1" },
              { key: "subtask-2", label: "Subtask 2" },
            ]},
          ]
    },
    {
        key: "progress",
        icon: <AreaChartOutlined />,
        label: "Progress"
    },
    {
        key: "payment",
        icon: <PayCircleOutlined />,
        label: "Payment"
    },
    {
        key: "settings",
        icon: <SettingOutlined />,
        label: "Settings"
    },
    
]
```

**Comment by HT-35** [comment]
I fixed the error "children will be removed in the next major version. Please use items instead." as follows:

"use client";
import {
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
} from "@ant-design/icons";
import { ButtonIcon } from "@radix-ui/react-icons";
import { Button, Menu } from "antd";
import Sider from "antd/es/layout/Sider";
import { ItemType, MenuItemType } from "antd/es/menu/interface";
import MenuItem from "antd/es/menu/MenuItem";
import Link from "next/link";
import { useRouter } from "next/navigation";

import React from "react";

const AdminSideBar = () => {
  const router = useRouter();

  const items = [
    {
      key: "1",
      icon: React.createElement(UserOutlined),
      label: "user",
      href: "/dashboard/user", // Đường dẫn liên kết
    },
    {
      key: "2",
      icon: React.createElement(VideoCameraOutlined),
      label: "product",
      href: "/dashboard/product", // Đường dẫn liên kết
    },
  ];

  console.log("items:", items);
  return (
    <Sider
      breakpoint="lg"
      collapsedWidth="0"
      onBreakpoint={(broken) => {
        //console.log(broken);
      }}
      onCollapse={(collapsed, type) => {
        //console.log(collapsed, type);
      }}
    >
      <div className="demo-logo-vertical" />
      <Menu
        theme="dark"
        mode="inline"
        defaultSelectedKeys={["0"]}
        items={items.map((item) => ({
          key: item.key,
          icon: item.icon,
          label: <Link href={item.href}>{item.label}</Link>,
        }))}
      ></Menu>
    </Sider>
  );
};

export default AdminSideBar;



![fix](https://github.com/user-attachments/assets/ae419f58-98f9-4651-8af9-e380ce6302e9)

**Comment by HT-35** [comment]
`"use client";
import {
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
} from "@ant-design/icons";
import { ButtonIcon } from "@radix-ui/react-icons";
import { Button, Menu } from "antd";
import Sider from "antd/es/layout/Sider";
import { ItemType, MenuItemType } from "antd/es/menu/interface";
import MenuItem from "antd/es/menu/MenuItem";
import Link from "next/link";
import { useRouter } from "next/navigation";

import React from "react";

const AdminSideBar = () => {
  const router = useRouter();

  const items = [
    {
      key: "1",
      icon: React.createElement(UserOutlined),
      label: "user",
      href: "/dashboard/user", // Đường dẫn liên kết
    },
    {
      key: "2",
      icon: React.createElement(VideoCameraOutlined),
      label: "product",
      href: "/dashboard/product", // Đường dẫn liên kết
    },
  ];

  console.log("items:", items);
  return (
    <Sider
      breakpoint="lg"
      collapsedWidth="0"
      onBreakpoint={(broken) => {
        //console.log(broken);
      }}
      onCollapse={(collapsed, type) => {
        //console.log(collapsed, type);
      }}
    >
      <div className="demo-logo-vertical" />
      <Menu
        theme="dark"
        mode="inline"
        defaultSelectedKeys={["0"]}
        items={items.map((item) => ({
          key: item.key,
          icon: item.icon,
          label: <Link href={item.href}>{item.label}</Link>,
        }))}
      ></Menu>
    </Sider>
  );
};

export default AdminSideBar;
![Uploading fix.png…]()
`

**Comment by HT-35** [comment]
I fixed the error "children will be removed in the next major version. Please use items instead." as follows:
`
"use client";
import {
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
} from "@ant-design/icons";
import { ButtonIcon } from "@radix-ui/react-icons";
import { Button, Menu } from "antd";
import Sider from "antd/es/layout/Sider";
import { ItemType, MenuItemType } from "antd/es/menu/interface";
import MenuItem from "antd/es/menu/MenuItem";
import Link from "next/link";
import { useRouter } from "next/navigation";

import React from "react";

const AdminSideBar = () => {
  const router = useRouter();

  const items = [
    {
      key: "1",
      icon: React.createElement(UserOutlined),
      label: "user",
      href: "/dashboard/user", // Đường dẫn liên kết
    },
    {
      key: "2",
      icon: React.createElement(VideoCameraOutlined),
      label: "product",
      href: "/dashboard/product", // Đường dẫn liên kết
    },
  ];

  console.log("items:", items);
  return (
    <Sider
      breakpoint="lg"
      collapsedWidth="0"
      onBreakpoint={(broken) => {
        //console.log(broken);
      }}
      onCollapse={(collapsed, type) => {
        //console.log(collapsed, type);
      }}
    >
      <div className="demo-logo-vertical" />
      <Menu
        theme="dark"
        mode="inline"
        defaultSelectedKeys={["0"]}
        items={items.map((item) => ({
          key: item.key,
          icon: item.icon,
          label: <Link href={item.href}>{item.label}</Link>,
        }))}
      ></Menu>
    </Sider>
  );
};

export default AdminSideBar;



`

![fix](https://github.com/user-attachments/assets/009e8e50-1198-4aad-9ef9-09f27a9094f5)
