### ISSUE TITLE
👑 [需求]兼容Angular，而不仅仅是react

### ISSUE THREAD

**Issue by wen2204** [ant-design/pro-components#5135]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### ⛰ 功能需求适用场景

增加angular框架的适配性

### 🧐 解决方案

适当收费，以扩展适用的框架

**Comment by Dunqing** [comment]
依赖react实现，无法适配angular
