### ISSUE TITLE
👑 [需求]ProTable 增加简单合计行功能

### ISSUE THREAD

**Issue by zwjsoft** [ant-design/pro-components#5136]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

在ProTable 组件中增加简单的合计行功能

### 🥰 需求描述

表格中经常需要合计行，是否可以简单的在表格属性和字段属性中设置是否合计，界面自动增加合计行功能。able.Summary有汇总行功能，但总体上用起来还是比较繁琐。

### ⛰ 功能需求适用场景

有表格的场景就有需求

### 🧐 解决方案

在表格属性及字段属性中增加合计属性

**Comment by chenshuai2144** [comment]
暂时没有好的想法，先用antd的吧，写起来也不麻烦
