### ISSUE TITLE
👑 [需求] proTable column 如何设置时间选择器的预设范围

### ISSUE THREAD

**Issue by jiujiaonuannan** [ant-design/pro-components#5138]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述
可以通过支持配置ranges的属性来支持一些常用日期的预设选项
比如下面这种可以支持“Today”，“This month”
![截屏2022-04-26 上午10 52 51](https://user-images.githubusercontent.com/26728614/165210443-e171ae40-ff6f-4c2b-9774-ae7f81d7be15.png)

**Comment by Dunqing** [comment]
需要antd实现，去那提issues
