### ISSUE TITLE
🐛[BUG] ProForm的ProDependency在1.58.1及其之后版本的bug

### ISSUE THREAD

**Issue by conorzhong** [ant-design/pro-components#5140]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProForm的ProDependency在1.58.1及其之后版本中
depValues能触发更新, 但是里面没有内容

### 📷 复现步骤

https://codesandbox.io/s/bug-report-pro-form-1-58-0-gvolqj?file=/App.tsx
1. 更新表单
2. 查看控制台

### 🏞 期望结果

depValues有正常值
### 💻 复现代码

https://codesandbox.io/s/bug-report-pro-form-1-58-0-gvolqj?file=/App.tsx
### © 版本信息

- ProComponents 版本: 1.58.1
- 浏览器环境 Edg/100.0.1185.36
- 开发环境 mac OS

**Comment by chenshuai2144** [comment]
你这个用法属实惊到我了。
