### ISSUE TITLE
🐛[BUG]ProFormDigit的addonAfter的样式问题

### ISSUE THREAD

**Issue by weiheli** [ant-design/pro-components#5143]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

addonAfter 的宽度不在 width="md" 之内，造成对齐有问题，不管 addonAfter 是写到外面还是放到 fieldProps 都有问题

### 📷 复现步骤

```
<ProFormDigit
  name="aveInvoke"
  label={t('调用量均值', { ns: RESOURCE.LIST_LIBRARY })}
  width="md"
  rules={[{ required: true }]}
  addonAfter={t('次/日', { ns: RESOURCE.LIST_LIBRARY })} // 放到外面
  fieldProps={{
    min: 1,
    precision: 0,
  }}
  disabled={readonly}
/>

<ProFormDigit
  name="overtime"
  label={t('超时时间', { ns: RESOURCE.LIST_LIBRARY })}
  width="md"
  rules={[{ required: true }]}
  fieldProps={{
    addonAfter: 'ms', // 写到 fieldProps 里面
    min: 1,
    precision: 0,
  }}
  disabled={readonly}
/>
```

![image](https://user-images.githubusercontent.com/5600837/165258416-3582b2a2-55f7-41d8-ac2b-f34287d6922d.png)

### 🏞 期望结果

希望 addonAfter 也在 width="md" 的宽度内

**Comment by 15723185734** [comment]
这个是antd 中InputNumber不支持   **suffix | 带有后缀图标的 input** 导致的

**Comment by 15723185734** [comment]
> 

inputNumber 又是用的[ rc-inputNumber](https://github.com/react-component/input-number) rc-inputNumber 不支持suffix后缀，所以估计官方也不想去支持，自己写个[自定义type](https://procomponents.ant.design/components/schema#%E8%87%AA%E5%AE%9A%E4%B9%89-valuetype)或者重新render

**Comment by StevenChu1125** [comment]
关注
