### ISSUE TITLE
关于EditableProTable的editorFormRef?.current?.setRowData问题

### ISSUE THREAD

**Issue by rgz665** [ant-design/pro-components#5145]
调用setRowData方法不会触发onValuesChange，在ProFormList中无法获取到最新的值。

**Comment by chenshuai2144** [comment]
setXXX 都不会触发，不然会死循环

**Comment by jasonwang1109** [comment]
> 

有什么其它解决办法吗？现在无法当前更新的值
![image](https://user-images.githubusercontent.com/2103331/183374782-93e66ff0-dba9-4d09-afa8-c0deb0054c51.png)
比如选择Today， 直接带出日期

**Comment by chenshuai2144** [comment]
自己做个组件把。
