### ISSUE TITLE
👑 [需求] ProTable的columnsState参数中的onChange返回值中添加一个dropedNodeKey参数

### ISSUE THREAD

**Issue by wenweicui** [ant-design/pro-components#5146]
### 🔩 所属模块或组件

率属组件：ProTable

### 🥰 需求描述

现有的columnsState参数中的onChange函数只返回改变后的一整个columnsState，不能直接的知道是哪一个column key发生了变化。

在我们的项目的需求中我们想要在columnsState的onChange函数里做一个API request，将变化的column key保存到后端，我目前的做法是将现有的columnsState和变化后的进行各种比较而找出改变的column key，但我觉得既然antd Tree的onDrag函数本就返回dragNode参数, 是否可能也把这个key值返回到columnsState中的onChange里。

### 🧐 解决方案

将ColumnSetting的Tree组件的onDrop函数所返回的dragNode参数添加到columnsState参数中的onChange返回值中

**Comment by 2218675712** [comment]
请问这个功能什么时候能上线，项目遇到了同样问题

**Comment by 2218675712** [comment]
请问这个功能什么时候能上线，项目遇到了同样问题

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


很抱歉，这个问题的解决方案需要先被antd官方接受和合并到主干代码才能上线。我建议你可以先fork一份antd的代码，然后在antd的Tree组件中加入你希望添加的参数，本地进行测试和使用。如果确实有需求，你也可以向antd提交pull request，分享你的代码实现并帮助这个问题得到更快的解决。当然，这个过程可能会比较漫长，你可以在自己的项目中先使用自己fork出来的antd版本进行开发。

**Comment by chenshuai2144** [comment]
官方不能很好的算出来，自己坐下 diff 吧
