### ISSUE TITLE
🧐[问题]在使用EditableProTable时，通过拖拽移动复制一列数据时，很容易移动到其他列下，这时释放鼠标会将该列改为编辑状态

### ISSUE THREAD

**Issue by jayt1001** [ant-design/pro-components#5147]
### 🧐 问题描述

这个问题不好描述，效果如下：
![2](https://user-images.githubusercontent.com/29675005/165421665-4110bec7-89ba-4d77-930a-b58d1e0860d0.gif)

---
如上图所示，用户在操作的时候往往只想复制“字段值”这行的内容，但实际情况很容易拖拽到其他行上，这时松开鼠标会导致改为了其他行的编辑状态。如何在不改变列间距的情况下解决这个问题呢?

**Comment by jayt1001** [comment]
好久能修复啊。大佬

**Comment by SilentFlute** [comment]
@jayt1001 大佬, 你实现拖拽编辑的表格了啊, 求分享一下代码
