### ISSUE TITLE
🧐[问题]EditableProTable可编辑表格通过setFieldsValue赋值后，能触发什么事件？

### ISSUE THREAD

**Issue by zwjsoft** [ant-design/pro-components#5148]
### 🧐 问题描述

EditableProTable可编辑表格通过setFieldsValue赋值后，能触发什么事件？因为需要根据dataSource进行一些后续操作处理，目前测试的各种事前好像都没执行，例如onChange，onValuesChange，onDataSourceChange等均未执行。

### 🚑 其他信息
    "@ant-design/pro-table": "^2.69.0",

**Comment by scrapstation** [comment]
+1

**Comment by chenshuai2144** [comment]
setFieldsValue 你自己触发的，你知道什么时候发生变化了，为什么还需要事件呢？
