### ISSUE TITLE
🧐[问题]EditableProTable数据量大时，默认展开树状结构会导致页面卡死且渲染不出数据

### ISSUE THREAD

**Issue by Volume3** [ant-design/pro-components#5149]
### 🧐 问题描述
使用defaultExpandAllRows或者expandedRowKeys都会有这样的问题
同样的代码在数据量小的时候可以默认展开。
想问下是性能问题还是我API使用问题？
### 💻 示例代码
https://codesandbox.io/s/ke-bian-ji-biao-ge-forked-jz94yc?file=/App.tsx

### 🚑 其他信息
示例代码中把defaultExpandAllRows和expandedRowKeys都注释了, 展示的就正常不展开的表格。取消注释任一，表格就无法正常展示了。

**Comment by Dunqing** [comment]
EditableTable内部处理的东西太多了，应该是组件性能问题，最好还是限制展开数量使用
