### ISSUE TITLE
🧐[问题] 请问在刚进入页面时useEffect中调用actionRef.current.reload为什么不能触发request？

### ISSUE THREAD

**Issue by JoeyYoung1997** [ant-design/pro-components#5153]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
在刚进入页面时useEffect中调用actionRef.current.reload不能触发request，而通过settimeout(() => { actionRef.current.reload() }, 500)延迟500ms左右才能触发

### 💻 示例代码
``` JavaScript
 useEffect(() => {
    setTimeout(() => console.log('actionRef.current.timeout', actionRef.current), 500) // 可以触发request
    actionRef.current.reload() // 不能触发request
  }, [history.location.query])

return <ProTable
        columns={columns}
        actionRef={actionRef}
        manualRequest={true}
        request={(params = {}, sort, filter) => {
          console.log('sort & filter', sort, filter);
          const { current, ...other } = Object.assign({}, params, {
            ...history.location.query,
            current: history.location.query.pageNumber
          })
          const _params = {
            pageNumber: current,
            ...other
          }
          return enterprise.queryList(_params)
            .then(res => {
              return {
                data: res.data.data,
                success: res.success,
                total: res.data.total
              }
            })
        }}
        debounceTime={200}
        rowKey="id"
        pagination={{
          onChange: (pageNumber, pageSize) => {
            history.push({ pathname: history.location.pathname, query: {...history.location.query, pageSize, pageNumber }})
          },
          showSizeChanger: true,
          showQuickJumper: true,
          defaultPageSize: history.location.query.pageSize || 10,
          defaultCurrent: history.location.query.pageNumber || 1
        }}
      />
```

**Comment by JoeyYoung1997** [comment]
经测试，通过取消manualRequest时可触发request，那这样其实就是我的思维误区，我本想在每次跳转页面后push({pathname: 'xx', query: { pageNumber： xx, pageSize: xx }})，然后useEffect中actionRef.current.reload()调用后触发request，以此达到记忆分页参数的目的，现在来看还是让proTable自行触发吧。。。

**Comment by studyyiran** [comment]
> 经测试，通过取消manualRequest时可触发request，那这样其实就是我的思维误区，我本想在每次跳转页面后push({pathname: 'xx', query: { pageNumber： xx, pageSize: xx }})，然后useEffect中actionRef.current.reload()调用后触发request，以此达到记忆分页参数的目的，现在来看还是让proTable自行触发吧。。。

hello @JoeyYoung1997 ，我觉得你这个思路没问题呀~~
你是直接解决了这个问题，然是绕过去了

**Comment by Dunqing** [comment]
ProTable有个onLoad事件在这里里面触发reload()试试

**Comment by JoeyYoung1997** [comment]
> ProTable有个onLoad事件在这里里面触发reload()试试

这个是数据加载完成后触发，但是我是需要先加载数据的

**Comment by JoeyYoung1997** [comment]
> > 经测试，通过取消manualRequest时可触发request，那这样其实就是我的思维误区，我本想在每次跳转页面后push({pathname: 'xx', query: { pageNumber： xx, pageSize: xx }})，然后useEffect中actionRef.current.reload()调用后触发request，以此达到记忆分页参数的目的，现在来看还是让proTable自行触发吧。。。
> 
> hello @JoeyYoung1997 ，我觉得你这个思路没问题呀~~ 你是直接解决了这个问题，然是绕过去了

思路是这样，就是刚进页面useEffect调用reload触发不了request，要么延迟调用，要么等下一次页面路由push

**Comment by EHL995** [comment]
> loading 的时候是不能触发的，要等第一次请求结束了才行

manualRequest设置为true后不会自动触发首次请求啊，应该不是loading状态吧，在useEffect里面actionRef.current.reload还是不生效啊
