### ISSUE TITLE
🐛[BUG] 嵌套 2 层 ProFormList 调用 getCurrentRowData 返回 undefined

### ISSUE THREAD

**Issue by AtLastDopamine** [ant-design/pro-components#5155]
### 🐛 bug 描述

嵌套 2 层 ProFormList 使用 RenderProps 模式，调用 getCurrentRowData 没有按照预期返回本行数据，而是返回 undefined

### 📷 复现步骤

在第二层的 ProFormText 输入框在输入，控制台会打印

### 🏞 期望结果

应该返回本行数据

### 💻 复现代码

[https://codesandbox.io/s/proform-list-forked-yhbb9m](url)

```
import React from "react";
import ProForm, { ProFormList, ProFormText } from "@ant-design/pro-form";

const Demo = () => {
  return (
    <ProForm
      onFinish={async (v) => {
        console.log(v);
      }}
    >
      <ProFormList
        name="lv1"
        label="第一层"
        itemContainerRender={(doms) => <ProForm.Group>{doms}</ProForm.Group>}
      >
        {() => {
          return (
            <>
              <ProFormText name="lv1Name" label="层级" />

              <ProFormList
                name="lv2"
                label="第二层"
                itemContainerRender={(doms) => (
                  <ProForm.Group>{doms}</ProForm.Group>
                )}
              >
                {(f, index, action) => {
                  return (
                    <ProFormText
                      name="lv2Name"
                      label="层级"
                      fieldProps={{
                        onChange: () => {
                          console.log(
                            "我是第二层的 getCurrentRowData：",
                            action.getCurrentRowData()
                          );
                        }
                      }}
                    />
                  );
                }}
              </ProFormList>
            </>
          );
        }}
      </ProFormList>
    </ProForm>
  );
};

export default Demo;

```

### © 版本信息

- ProComponents 版本: @ant-design/pro-form：1.65.0、antd：4.20.1
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="583" alt="image" src="https://user-images.githubusercontent.com/33427467/165533997-50a478dd-5578-4a3a-b834-defff88ec88f.png">

**Comment by 15723185734** [comment]
demo链接是不是给错了？

**Comment by 15723185734** [comment]
第一层的action.getCurrentRowData()打印出来是什么效果？

**Comment by bowencool** [comment]
> demo链接是不是给错了？

https://codesandbox.io/s/proform-list-forked-yhbb9m

**Comment by bowencool** [comment]
@AtLastDopamine 你最后怎么解决的？

**Comment by AtLastDopamine** [comment]
> @AtLastDopamine你最后怎么解决的？

`ProForm` 自身不是有 `ref`（`formRef`），我直接使用的是`formRef`
使用`formRef`例如 `formRef.current.setFields()` 方法，核心的问题是如何获取`path`；
因为我的有多层，其中一些部分我抽成了公共组件，所以都是由父组件传递进来`path`；
在`ProFormList`的 Children Props 中你可以获取到当前的下标，有了下标你就可以生成当前的`path`；

我的代码在内网，不能分享出来。在问题修复之前，这是我现在用的解决办法，确实要麻烦不少

**Comment by bowencool** [comment]
> > @AtLastDopamine你最后怎么解决的？
> 
> `ProForm` 自身不是有 `ref`（`formRef`），我直接使用的是`formRef` 使用`formRef`例如 `formRef.current.setFields()` 方法，核心的问题是如何获取`path`； 因为我的有多层，其中一些部分我抽成了公共组件，所以都是由父组件传递进来`path`； 在`ProFormList`的 Children Props 中你可以获取到当前的下标，有了下标你就可以生成当前的`path`；
> 
> 我的代码在内网，不能分享出来。在问题修复之前，这是我现在用的解决办法，确实要麻烦不少

谢谢，我刚才用 ProFormDependency 也能取到当前行了

**Comment by liudiming** [comment]
你没设置值，所以获取的是undefined

**Comment by AtLastDopamine** [comment]
> 第一层的action.getCurrentRowData()打印出来是什么效果？

链接没有错，要复制出来打开浏览器，直接点好像不行。
第一层是正确的，能获得预期值

<img width="560" alt="image" src="https://user-images.githubusercontent.com/33427467/172287105-17cf4a6c-73b8-4238-ab1c-dfab83ae2a84.png">

**Comment by AtLastDopamine** [comment]
> 你没设置值，所以获取的是undefined

额，不是很懂你的意思🤔。
我是获取输入框的值（表单项），为什么要设置值呢。
也可以理解为我想获取 `ProForm` 中维护的最新的 `Store` 的属性

**Comment by mumian2** [comment]
> > @AtLastDopamine你最后怎么解决的？
> 
> `ProForm` 自身不是有 `ref`（`formRef`），我直接使用的是`formRef` 使用`formRef`例如 `formRef.current.setFields()` 方法，核心的问题是如何获取`path`； 因为我的有多层，其中一些部分我抽成了公共组件，所以都是由父组件传递进来`path`； 在`ProFormList`的 Children Props 中你可以获取到当前的下标，有了下标你就可以生成当前的`path`；
> 
> 我的代码在内网，不能分享出来。在问题修复之前，这是我现在用的解决办法，确实要麻烦不少

这个获取path是什么

**Comment by mumian2** [comment]
大佬这个解决不是很懂   能再讲讲吗

**Comment by mumian2** [comment]
> 



> 大佬这个解决不是很懂 能再讲讲吗
@AtLastDopamine

**Comment by bowencool** [comment]
> 大佬这个解决不是很懂 能再讲讲吗

``` js
formRef.current?.getFieldValue([
            ...fullPath,
            name,
            index,
          ])
```

**Comment by mumian2** [comment]
>你这个是获取的什么

**Comment by mumian2** [comment]
> 

这是在子类获取父类的的吗

**Comment by AtLastDopamine** [comment]
@mumian2 
我更新了一下 [示例代码](https://codesandbox.io/s/proform-list-forked-yhbb9m?file=/App.tsx)，你重点看 49 行。

如果链接打不开，你把链接在复制一边用浏览器打开。就是我`复现代码`标题的链接，App.ts 文件

我尽力描述啦🤣

**Comment by mumian2** [comment]
> @mumian2 我更新了一下 [示例代码](https://codesandbox.io/s/proform-list-forked-yhbb9m?file=/App.tsx)，你重点看 49 行。
> 
> 如果链接打不开，你把链接在复制一边用浏览器打开。就是我`复现代码`标题的链接，App.ts 文件
> 
> 我尽力描述啦🤣

@AtLastDopamine 我点开这个示例还是获取的undefined 
![image](https://user-images.githubusercontent.com/107187885/172990983-8aced674-1a03-4121-81d3-1ca420069af1.png)

**Comment by AtLastDopamine** [comment]
@mumian2 

咦，不对呀，我更新了的呢。
这是我的打印结果，你这个明显是老的

<img width="604" alt="image" src="https://user-images.githubusercontent.com/33427467/172991074-4c14cc34-c67f-4b62-ba7c-f6f6e397ec21.png">

**Comment by mumian2** [comment]
> https://codesandbox.io/s/proform-list-forked-yhbb9m
好的好的 谢谢了

**Comment by mumian2** [comment]
@AtLastDopamine 大佬 我自己的ProFormList封装成一个组件引入父类中  然后我这个组件需要被<Form.Item>包裹才能获取到子类的值吗

**Comment by mumian2** [comment]
> 
![image](https://user-images.githubusercontent.com/107187885/173014334-f72b9da9-9659-4099-88af-38bd927d4ebc.png)
只用了父类的path都可以获取到内层ProFormList的值

**Comment by mumian2** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/107187885/173014334-f72b9da9-9659-4099-88af-38bd927d4ebc.png) 只用了父类的path都可以获取到内层ProFormList的值

我自己的ProFormList当作组件引入的时候只能获取到外层的值

**Comment by bowencool** [comment]
啥意思，修好了吗

**Comment by chenshuai2144** [comment]
大佬不是给解决了？

**Comment by bowencool** [comment]
这楼里面都是些备用方案吧

> 大佬不是给解决了？

**Comment by AtLastDopamine** [comment]
> 这楼里面都是些备用方案吧
> 
> > 大佬不是给解决了？

臣附议。

虽然作为伸手党很不好，但是想想还要提供测试用例和读源码，对我个人而言还是有些劝退。我表示很抱歉。

目前解决是借助 `ProForm ` 的 `Api` 来实现的，但是这个问题是 `ProFormList` 中 `getCurrentRowData` 的方法没有按照文档中的描述运行🤔。

**Comment by privatez** [comment]
升级 pro-form 版本到 1.74.6，问题已解决。
