### ISSUE TITLE
🧐[问题]ProForm底下有一个Table，在ProForm.submit的时候，Table会被重建导致数据丢失，是否有什么方式可以避免Table被重建？

### ISSUE THREAD

**Issue by TFacestudio** [ant-design/pro-components#5157]
### 🧐 问题描述

ProForm底下有一个Table，在ProForm.submit的时候，Table会被重建导致数据丢失，是否有什么方式可以避免Table被重建？

### 💻 示例代码
`<ProForm>
    <ProFormDigit/>
    <Table/>
</ProForm>`

**Comment by Dunqing** [comment]
table为啥会在ProForm里面？是表单项吗？

**Comment by TFacestudio** [comment]
> table为啥会在ProForm里面？是表单项吗？

不算表单项，因为布局的关系放在ProForm里面了。

**Comment by Dunqing** [comment]
> 不算表单项，因为布局的关系放在ProForm里面了。

table套一个ProFormDependency，name传递空数组
