### ISSUE TITLE
🐛[BUG]关于1.65.0 LoginForm 默认给了width:328的问题

### ISSUE THREAD

**Issue by zisitiankong** [ant-design/pro-components#5158]
### 🐛 bug 描述
关于1.65.0 LoginForm 默认给了width:328的问题

关于这一条提交https://github.com/ant-design/pro-components/pull/5077

那之前项目上用到了loginForm没设置width的，都需要加上contentStyle={{width:"auto"}}

这个提交确认可行吗

**Comment by chenshuai2144** [comment]
已经支持自定义了
