### ISSUE TITLE
🧐[问题] 如何不引入less

### ISSUE THREAD

**Issue by x1ny** [ant-design/pro-components#5159]
### 🧐 问题描述

我的项目无法使用less，但是引入pro-components的组件时都会引入对应的less文件。
能否做到像antd一样，样式和组件分开引入

**Comment by faner11** [comment]
期待

**Comment by chenshuai2144** [comment]
https://unpkg.alibaba-inc.com/browse/@ant-design/pro-table@2.74.3/dist/

每个库都有个 dist 文件夹，里面有css

**Comment by x1ny** [comment]
> https://unpkg.alibaba-inc.com/browse/@ant-design/pro-table@2.74.3/dist/
> 
> 每个库都有个 dist 文件夹，里面有css

但是引入组件的时候 会附带引入less
