### ISSUE TITLE
🐛[BUG]prolist 组件的 pagination：改变pagesize后，前端组件选中了第一页，但是pageNum的值还是之前的值

### ISSUE THREAD

**Issue by dakotaliang** [ant-design/pro-components#5161]
### 🐛 bug 描述

prolist 组件的 pagination：改变pagesize后，前端组件选中了第一页，但是pageNum的值还是之前的值

### 📷 复现步骤
https://codesandbox.io/s/naughty-sanne-rzrcfs

1、当前状态： total = 50， pageNum = 2， pageSize = 10
2、更改pageSize为20：打印出：pageNum = 2， pageSize = 20，但是此时前端组件选中的是第一页

### 🏞 期望结果

pageNum更新为 1

### 💻 复现代码

  import React from 'react';
import { Progress, Tag } from 'antd';
import { EllipsisOutlined } from '@ant-design/icons';
import ProList from '@ant-design/pro-list';

const data = [
  '语雀的天空',
  'Ant Design',
  '蚂蚁金服体验科技',
  'TechUI',
  'TechUI 2.0',
  'Bigfish',
  'Umi',
  '语雀的天空',
  'Ant Design',
  '蚂蚁金服体验科技',
  'TechUI',
  'TechUI 2.0',
  'Bigfish',
  'Umi',
  '语雀的天空',
  'Ant Design',
  '蚂蚁金服体验科技',
  'TechUI',
  'TechUI 2.0',
  'Bigfish',
  'Umi',
  '语雀的天空',
  'Ant Design',
  '蚂蚁金服体验科技',
  'TechUI',
  'TechUI 2.0',
  'Bigfish',
  'Umi',
  '语雀的天空',
  'Ant Design',
  '蚂蚁金服体验科技',
  'TechUI',
  'TechUI 2.0',
  'Bigfish',
  'Umi',
  '语雀的天空',
  'Ant Design',
  '蚂蚁金服体验科技',
  'TechUI',
  'TechUI 2.0',
  'Bigfish',
  'Umi',
  '语雀的天空',
  'Ant Design',
  '蚂蚁金服体验科技',
  'TechUI',
  'TechUI 2.0',
  'Bigfish',
  'Umi',
  '语雀的天空',
  'Ant Design',
  '蚂蚁金服体验科技',
  'TechUI',
  'TechUI 2.0',
  'Bigfish',
  'Umi',
].map(item => ({
  title: item,
  subTitle: <Tag color="#5BD8A6">语雀专栏</Tag>,
  actions: [
    <a>邀请</a>,
    <a>操作</a>,
    <a>
      <EllipsisOutlined />
    </a>,
  ],
  avatar: 'https://gw.alipayobjects.com/zos/antfincdn/UCSiy1j6jx/xingzhuang.svg',
  content: (
    <div
      style={{
        flex: 1,
        display: 'flex',
        justifyContent: 'flex-end',
      }}
    >
      <div
        style={{
          width: 200,
        }}
      >
        <div>发布中</div>
        <Progress percent={80} />
      </div>
    </div>
  ),
}));

export default () => {
  return (
    <ProList<any>
      pagination={{
        defaultPageSize: 5,
        showSizeChanger: true,
        onChange: () => {
          console.log(`pageNum: ${pageNum}  pageSize: ${pageSize}`);
        },
      }}
      metas={{
        title: {},
        subTitle: {},
        type: {},
        avatar: {},
        content: {},
        actions: {},
      }}
      headerTitle="翻页"
      dataSource={data}
    />
  );
};

### © 版本信息

- ProComponents 版本:  "@ant-design/pro-list": "1.20.2"

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20038501/165721622-a50ce4c9-9539-4b0b-8832-d9ad099ae20b.png)

**Comment by dakotaliang** [comment]
https://codesandbox.io/s/naughty-sanne-rzrcfs
![image](https://user-images.githubusercontent.com/20038501/165905086-66ec8ef0-1ccb-4243-aaf7-649f79e4f9e5.png)

**Comment by dakotaliang** [comment]
@Dunqing

**Comment by Dunqing** [comment]
> @Dunqing

小bug来个pr修复下？
