### ISSUE TITLE
能提供 EditableProTable联合 Upload 一起使用的示例么，EditableProTable可以一次性添加多条数据

### ISSUE THREAD

**Issue by soeasyjx** [ant-design/pro-components#5164]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
EditableProTable可以一次性添加多条数据  可以多次添加的，只要保证 key 都相同

**Comment by chenshuai2144** [comment]
联合 Upload 一起使用的示例

这个和普通form相同， upload 使用很复杂，要结合你的业务来看

**Comment by china-english** [comment]
EditableProTable  在columns 中的 renderFormItem 中如何设置 valuePropName 和 getValueFromEvent
