### ISSUE TITLE
🧐[问题]StepsForm和StepsForm.StepForm后指定的类型有什么意义？

### ISSUE THREAD

**Issue by shadowfish07** [ant-design/pro-components#5166]
### 🧐 问题描述

看到文档里

```
<StepsForm<{name: string;}> ....>....</>
<StepsForm.StepForm<{name: string;}> ....>....</>
```

请问<{name: string;}>起到什么作用？自己写逻辑时应该怎么写这里面的东西？

**Comment by Dunqing** [comment]
这是typescript的东西。只是一个范型，jsx是这样传递范型的{ name: string } 指的是一个类型传递给了StepsForm。不传也可以，默认类型是Record<string, any>。

最终会传递给`FormInstance<{name: string}>`

**Comment by Dunqing** [comment]
怎么写这里面的东西取决于你的表单数据是怎样的
比如你有一个表单有name, id, age三个参数则定义的类型为Entity：
```tsx
// 根据表单数据创建的一个类型
type Entity = {
   name: string,
   id: number,
   age: number
}

那你可以这样使用
<StepsForm<Entity> ....>....</>
<StepsForm.StepForm<Entity> ....>....</>
```

**Comment by shadowfish07** [comment]
@Dunqing 感谢回复！！
