### ISSUE TITLE
🧐[问题]ProCard里面嵌套ProTable的页面，切换Chrome浏览器Tab回来时，会自动触发ProTable的request，如何不触发？

### ISSUE THREAD

**Issue by TFacestudio** [ant-design/pro-components#5168]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

ProCard里面嵌套ProTable的页面，切换Chrome浏览器页面Tab回来时，会自动触发ProTable的request，这是为啥呢？

### 💻 示例代码

`<ProCard>
<ProTable request={()=>{
console.log('触发request')
}} />
</ProCard>`

**Comment by leepood** [comment]
PageContainer 同样遇到此问题，mark下

**Comment by leepood** [comment]
@TFacestudio  大概看了下，是新版本的pro-table引起的，固定到 2.72.1 版本可解决

**Comment by TFacestudio** [comment]
> @TFacestudio 大概看了下，是新版本的pro-table引起的，固定到 2.72.1 版本可解决

好滴 多谢解答

**Comment by XB-Paul** [comment]
设置revalidateOnFocus为false试试看

**Comment by Dunqing** [comment]
监听了 visibilitychange事件，重新聚焦会发起请求

设置revalidateOnFocus为false会关闭这个feature

**Comment by chenshuai2144** [comment]
evalidateOnFocus | 窗口聚焦时自动重新请求 | boolean | true
-- | -- | -- | --

**Comment by hihuangwei** [comment]
> evalidateOnFocus	窗口聚焦时自动重新请求	boolean	true

为何默认不是 false @chenshuai2144

**Comment by taoliujun** [comment]
这种break change默认打开选项，官方怎么想的？

**Comment by Muralitob** [comment]
哎 测试一顿问 我就给改成Table写的了，结果还是这种情况

**Comment by xgj1988** [comment]
哎，我也不知道官方怎么想的。。这种应该默认为false啊

**Comment by huhm** [comment]
怎么全局关
