### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by wls-helianthus** [ant-design/pro-components#517]
### 🧐 问题描述

默认简单项目，查询表格界面报警告：
Warning: 'formItemProps' will be deprecated, please use 'fieldProps'
点击新建按钮报下面两个警告：
devScripts.js:5836 Warning: React does not recognize the `defaultCollapsed` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `defaultcollapsed` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
React does not recognize the `labelWidth` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `labelwidth` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

以前使用的时候没有，是版本更新的问题吗？如何解决。

**Comment by chenshuai2144** [comment]
写title
