### ISSUE TITLE
🐛[BUG] ProForm 1.59.3后 FormSelect 组件request 频繁切换路由不加载接口

### ISSUE THREAD

**Issue by xujinxing-5549** [ant-design/pro-components#5170]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Dunqing** [comment]
可能和SWR缓存有关

**Comment by 15723185734** [comment]
有没有用react keepalive

**Comment by xujinxing-5549** [comment]
没有的，现在改用options和state动态获取了

**Comment by chenshuai2144** [comment]
form 里面的关掉了，升级到最新版本
