### ISSUE TITLE
🐛[BUG] shouldCellUpdate and columnsState not working together properly

### ISSUE THREAD

**Issue by Andreybest** [ant-design/pro-components#5175]
### 🐛 Bug

Good day everyone. There is a bug that is happening in versions of pro-table after 2.56.0.

The bug is that columnState settings or "fixed: 'left'" does not work when shouldCellUpdate function has it's own logic (not shouldCellUpdate: () => true)

So the problem is when column moves its position and this column is fixed to left, it stays on same place and column becomes shadowed by other column. Only after hover - this disappears (I guess rerenders?)

### 📷 Reproduce

https://codesandbox.io/s/valuetype-xuan-ze-lei-forked-oetrmf?file=/App.tsx

1. Open columnState settings (cogwheel)
2. Move column "Test1" to be first (so that "Test" column would be second)
3. Try scrolling columns to the left - enjoy interesting view.

### 🏞 Expected result

Columns should render the same as with shouldCellUpdate: () => true when columnState being changed

### 💻 Reproduce code

```js
{
    title: "Test",
    dataIndex: "test",
    fixed: "left",
    width: 100,
    shouldCellUpdate: (record, prevRecord) => {
      console.log(record);
      return record["test"] !== prevRecord["test"];
    }
},
{
    title: "Test1",
    dataIndex: "test1",
    fixed: "left",
    width: 100,
    shouldCellUpdate: (record, prevRecord) => {
      return record["test1"] !== prevRecord["test1"];
    }
},
```

### © Dependency versions

- ProComponets pro-table: 2.73.0
- umi 3.5.20
- Brave Latest
- macOS 12.3.1

**Comment by Dunqing** [comment]
This is an interesting issue

**Comment by 15723185734** [comment]
你自己翻译一下：
![image](https://user-images.githubusercontent.com/61341868/168246992-9fc53f91-0337-4d7e-a613-c3e2df271a26.png)
把截图的内容删除就不会出现这个问题，可以说这不算是个bug吧，只能说兼容性不强，官方文档是否也没有支持这个属性：shouldCellUpdate

**Comment by Dunqing** [comment]
> ![image](https://user-images.githubusercontent.com/61341868/168246992-9fc53f91-0337-4d7e-a613-c3e2df271a26.png) 把截图的内容删除就不会出现这个问题，可以说这不算是个bug吧，只能说兼容性不强，官方文档似乎也没有支持这个属性：shouldCellUpdate

理论上Table的所有功能都是要支持的，Antd 的 Table 是支持这个属性的。如果在ProTable使用了这个属性出现了Bug那就应该去做适配修复它

**Comment by Dunqing** [comment]
> 在proTable中shouldCellUpdate似乎没有意义

看起来是个优化性能的一个属性，应该是有用的

**Comment by Andreybest** [comment]
> > > ![image](https://user-images.githubusercontent.com/61341868/168246992-9fc53f91-0337-4d7e-a613-c3e2df271a26.png) 把截图的内容删除就不会出现这个问题，可以说这不算是个bug吧，只能说兼容性不强，官方文档似乎也没有支持这个属性：shouldCellUpdate
> > 
> > 
> > 理论上Table的所有功能都是要支持的，Antd 的 Table 是支持这个属性的。如果在ProTable使用了这个属性出现了Bug那就应该去做适配修复它
> 
> 在proTable中shouldCellUpdate似乎没有意义

ProTable is not performant when using lots of rows and columns, we can't unuse shouldCellUpdate functions

**Comment by Andreybest** [comment]
@15723185734 thats the point of this issue, columnsState and shouldCellUpdate is not working together.
