### ISSUE TITLE
🧐[问题] Replace moment ProFormDatePicker

### ISSUE THREAD

**Issue by ZeroLTV** [ant-design/pro-components#5177]
### 🧐 问题描述

I want to use dayjs to replace moment of ProFormDatePicker like antd's DatePicker

### 🚑 其他信息

import { Dayjs } from 'dayjs';
import dayjsGenerateConfig from 'rc-picker/lib/generate/dayjs';
import generatePicker from 'antd/es/date-picker/generatePicker';
import 'antd/es/date-picker/style/index';

const DatePicker = generatePicker<Dayjs>(dayjsGenerateConfig);

export default DatePicker;

**Comment by Dunqing** [comment]
This is currently not possible.
Please consider replacing `moment` with `dayjs` using webpack plugin or other bundler plugin.

Related plugins:
- [antd-dayjs-webpack-plugin](https://www.npmjs.com/package/antd-dayjs-webpack-plugin) support for use in webpack
- [unplugin-moment-to-dayjs](https://www.npmjs.com/package/unplugin-moment-to-dayjs) support for use in webpack, vite and rollup
