### ISSUE TITLE
🧐[问题] Language Translation ProFormDatePicker

### ISSUE THREAD

**Issue by ZeroLTV** [ant-design/pro-components#5178]
### 🧐 问题描述
I can't change the language of ProFormDatePicker

### 🚑 其他信息
https://github.com/X-neuron/x-plat
![image](https://user-images.githubusercontent.com/45669286/166878886-d1af8b6f-d58d-4bc6-9b07-4aefa3cbcf98.png)

**Comment by Dunqing** [comment]
You try to set moment/dayjs locale
