### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by wxf-start** [ant-design/pro-components#518]
### 🐛 bug 描述

设置pro table 的options 报错

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/37679380/93313774-7a7d1c80-f83b-11ea-9285-3f9e95652a06.png)

### 🏞 期望结果

不会报错

### 💻 复现代码

![image](https://user-images.githubusercontent.com/37679380/93313755-73eea500-f83b-11ea-98e1-773b8bc1b324.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 "umi": "^3.2.14",
- 浏览器环境  谷歌
- 开发环境 window 7

### 🚑 其他信息

     options={{ fullScreen: true, reload: false, setting: true }}    fullScreen 为true时报错

**Comment by chenshuai2144** [comment]
写title
