### ISSUE TITLE
🧐[问题] ProTable Columns数组为后端存储的JSON数据，请问如何解析字符串render函数

### ISSUE THREAD

**Issue by zxbit2011** [ant-design/pro-components#5181]
### 🧐 问题描述
> ProTable Columns数组为后端存储的JSON数据，请问如何解析字符串`render`函数
* 正常代码写法：
````
    {
      title: '标题',
      dataIndex: 'Title',
      render: (_) => <a>{_}</a>,
    }
````
* 服务器后端存储方式为：
````
    {
      title: '标题',
      dataIndex: 'Title',
      render: "(_) => <a>{_}</a>",
    }
````
请问服务器返回的JSON，在渲染时如何将`render:"(_) => <a>{_}</a>"`转换为 `render: (_) => <a>{_}</a> `

**Comment by Dunqing** [comment]
JSX无法直接在浏览器上运行，就算你转成了`render: (_) => <a>{_}</a>`也跑不起来

这种情况可以自定义valueType

**Comment by kjlixx** [comment]
同问，要实现这样的功能怎么做。。

**Comment by chenshuai2144** [comment]
new function
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Function/Function

试试这东西
