### ISSUE TITLE
🐛[BUG] TableDropdown 在antd(v4.20.0)之后报警告Menu Children

### ISSUE THREAD

**Issue by Es-Rell** [ant-design/pro-components#5184]
### 🐛 bug 描述

TableDropdown 在antd(v4.20.0)之后报警告Menu Children
```[antd: Menu] `children` will be removed in next major version. Please use `items` instead.```
antd即将废弃Menu children 使用items替换，但目前该组件还未更新

### 🏞 期望结果

使用items替换children 不报警告

### 💻 复现代码

```
<TableDropdown 
    key="actionGroup"
    menus={[
        { key: 'copy', name: '复制' },
        { key: 'delete', name: '删除' }
    ]}
/>
```

### © 版本信息

- @ant-design/pro-table 版本: [^2.73.0]
- umi 版本 [^3.5.23]
- 浏览器环境 [Google Chrome]
- 开发环境 [e.g. mac OS]

**Comment by Es-Rell** [comment]
@chenshuai2144  大佬快来

**Comment by chenshuai2144** [comment]
更新到最新版本吧，修复了

**Comment by Es-Rell** [comment]
> 更新到最新版本吧，修复了

"@ant-design/pro-table": "^2.74.0", 大佬，刚刚更新了 问题还是存在 
```import  { TableDropdown } from '@ant-design/pro-table'```
TableDropdown组件hover上去就会报警告

**Comment by Es-Rell** [comment]
> 更新到最新版本吧，修复了

@chenshuai2144 大佬 ，问题还是存在 
`"@ant-design/pro-table": "^2.74.1"`
