### ISSUE TITLE
🧐[问题]protable  filters筛选项在部分windows系统中chrome上不显示底部按钮 

### ISSUE THREAD

**Issue by houkeepmoving** [ant-design/pro-components#5185]
![image](https://user-images.githubusercontent.com/29296595/167074412-276557b1-10b2-46da-9548-02702c161bd9.png)
![image](https://user-images.githubusercontent.com/29296595/167074635-9dfdc436-9b40-4f58-8410-d5c0284b1b80.png)

**Comment by 15723185734** [comment]
建议看一下是不是桌面分辨率导致的 显示基数是不是100% 有些笔记本是75%，如果如此应该是个BUG
