### ISSUE TITLE
🐛[BUG] ProTable 在配置request属性后，切换浏览器标签页，再回到当前页面（页面获取焦点）会额外触发一次request请求

### ISSUE THREAD

**Issue by czb128abc** [ant-design/pro-components#5187]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProTable 在配置request属性后，切换浏览器标签页，再回到当前页面（页面获取焦点）会额外触发一次request请求

### 💻 复现代码

https://codesandbox.io/s/cha-xun-biao-ge-forked-38oeff?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Dunqing** [comment]
same issue: https://github.com/ant-design/pro-components/issues/5168#issuecomment-1118260050
