### ISSUE TITLE
🐛[BUG]未知原因导致的鼠标悬停table cell时触发column的render方法

### ISSUE THREAD

**Issue by haungxinyan** [ant-design/pro-components#5188]
### 🐛 bug 描述
鼠标悬停在table上时，都会触发我在render中的打印
![image](https://user-images.githubusercontent.com/40256365/167085071-195687cb-252f-4144-8a02-b0902b21c75a.png)
![image](https://user-images.githubusercontent.com/40256365/167085140-60551258-2260-4b8c-a4aa-99049bf996c8.png)

### 📷 复现步骤
不知道该怎么复现，不知道是什么导致

### 💻 复现代码

就官方示例代码随机拷贝了一个

### © 版本信息

{
  "name": "zkbio_att",
  "version": "5.0.0",
  "private": true,
  "description": "ZKBIO ATT",
  "scripts": {
    "analyze": "cross-env ANALYZE=1 umi build",
    "build": "umi build",
    "deploy": "npm run build && npm run gh-pages",
    "dev": "npm run start:dev",
    "docker-hub:build": "docker build  -f Dockerfile.hub -t  ant-design-pro ./",
    "docker-prod:build": "docker-compose -f ./docker/docker-compose.yml build",
    "docker-prod:dev": "docker-compose -f ./docker/docker-compose.yml up",
    "docker:build": "docker-compose -f ./docker/docker-compose.dev.yml build",
    "docker:dev": "docker-compose -f ./docker/docker-compose.dev.yml up",
    "docker:push": "npm run docker-hub:build && npm run docker:tag && docker push antdesign/ant-design-pro",
    "docker:tag": "docker tag ant-design-pro antdesign/ant-design-pro",
    "gh-pages": "gh-pages -d dist",
    "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
    "postinstall": "umi g tmp",
    "lint": "umi g tmp && npm run lint:js && npm run lint:style && npm run lint:prettier && npm run tsc",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src && npm run lint:style",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "prettier -c --write \"src/**/*\" --end-of-line auto",
    "lint:style": "stylelint --fix \"src/**/*.less\" --syntax less",
    "openapi": "umi openapi",
    "precommit": "lint-staged",
    "prettier": "prettier -c --write \"src/**/*\"",
    "start": "cross-env UMI_ENV=dev umi dev",
    "start:dev": "cross-env REACT_APP_ENV=dev PORT=8081 MOCK=none UMI_ENV=dev umi dev",
    "start:no-mock": "cross-env MOCK=none UMI_ENV=dev umi dev",
    "start:no-ui": "cross-env UMI_UI=none UMI_ENV=dev umi dev",
    "start:pre": "cross-env REACT_APP_ENV=pre UMI_ENV=dev umi dev",
    "start:test": "cross-env REACT_APP_ENV=test MOCK=none UMI_ENV=dev umi dev",
    "pretest": "node ./tests/beforeTest",
    "test": "umi test",
    "test:all": "node ./tests/run-tests.js",
    "test:component": "umi test ./src/components",
    "serve": "umi-serve",
    "tsc": "tsc --noEmit"
  },
  "lint-staged": {
    "**/*.less": "stylelint --syntax less",
    "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
    "**/*.{js,jsx,tsx,ts,less,md,json}": [
      "prettier --write"
    ]
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ],
  "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-card": "^1.18.31",
    "@ant-design/pro-descriptions": "^1.10.42",
    "@ant-design/pro-form": "^1.53.5",
    "@ant-design/pro-layout": "^6.32.13",
    "@ant-design/pro-table": "^2.72.0",
    "@emotion/react": "^11.7.1",
    "@emotion/styled": "^11.6.0",
    "@fullcalendar/daygrid": "^5.10.1",
    "@fullcalendar/interaction": "^5.10.1",
    "@fullcalendar/react": "^5.10.1",
    "@mui/icons-material": "5.2.5",
    "@mui/material": "^5.2.8",
    "@uiw/react-baidu-map": "^2.0.8",
    "@umijs/plugin-qiankun": "^2.36.0",
    "@umijs/route-utils": "^2.0.5",
    "antd": "^4.18.7",
    "chart.js": "^3.7.0",
    "classnames": "^2.3.1",
    "formik": "^2.2.9",
    "js-cookie": "^3.0.1",
    "jsdom": "^19.0.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "omit.js": "^2.0.2",
    "react": "^17.0.2",
    "react-bmap": "^1.0.130",
    "react-bmapgl": "^0.1.28",
    "react-chartjs-2": "^4.0.0",
    "react-dev-inspector": "^1.7.1",
    "react-dom": "^17.0.2",
    "react-google-maps": "^9.4.5",
    "react-helmet-async": "^1.2.2",
    "umi": "^3.5.20",
    "umi-serve": "^1.9.10",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.1.5",
    "@types/express": "^4.17.13",
    "@types/history": "^4.7.10",
    "@types/jest": "^27.4.0",
    "@types/lodash": "^4.14.178",
    "@types/react": "^17.0.38",
    "@types/react-dom": "^17.0.11",
    "@types/react-helmet": "^6.1.5",
    "@umijs/fabric": "^2.10.0",
    "@umijs/plugin-esbuild": "^1.4.1",
    "@umijs/preset-ant-design-pro": "^1.3.3",
    "@umijs/preset-dumi": "^1.1.38",
    "@umijs/preset-react": "^2.1.1",
    "@umijs/yorkie": "^2.0.5",
    "carlo": "^0.9.46",
    "cross-env": "^7.0.3",
    "cross-port-killer": "^1.4.0",
    "detect-installer": "^1.0.2",
    "enzyme": "^3.11.0",
    "eslint": "^8.7.0",
    "express": "^4.17.2",
    "gh-pages": "^3.2.3",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^12.1.7",
    "mockjs": "^1.1.0",
    "prettier": "^2.5.1",
    "puppeteer-core": "^13.0.1",
    "stylelint": "^14.2.0",
    "typescript": "^4.5.4"
  },
  "engines": {
    "node": ">=10.0.0"
  },
  "create-umi": {
    "ignoreScript": [
      "docker*",
      "functions*",
      "site",
      "generateMock"
    ],
    "ignoreDependencies": [
      "netlify*",
      "serverless"
    ],
    "ignore": [
      ".dockerignore",
      ".git",
      ".github",
      ".gitpod.yml",
      "CODE_OF_CONDUCT.md",
      "Dockerfile",
      "Dockerfile.*",
      "lambda",
      "LICENSE",
      "netlify.toml",
      "README.*.md",
      "azure-pipelines.yml",
      "docker",
      "CNAME",
      "create-umi"
    ]
  },
  "gitHooks": {
    "commit-msg": "fabric verify-commit"
  }
}

- 浏览器环境 chrome
- 开发环境  windows

**Comment by Dunqing** [comment]
是feature
你可以使用[shouldUpdateCell](https://ant.design/components/table-cn/#Column)控制是否需要重新执行

**Comment by haungxinyan** [comment]
> 是feature 你可以使用[shouldUpdateCell](https://ant.design/components/table-cn/#Column)控制是否需要重新执行

标准版的没有这个问题  现在是我项目中出现这个  不知道是什么设置导致的  使用这个shouldUpdateCell返回false也没有生效  但是理论上不需要使用这个的吧  毫无头绪

**Comment by haungxinyan** [comment]
> 是feature 你可以使用[shouldUpdateCell](https://ant.design/components/table-cn/#Column)控制是否需要重新执行

你们问题关的太快了吧

**Comment by Dunqing** [comment]
更新到最新版本试试
