### ISSUE TITLE
👑 [需求] 感觉  ModalForm,   DrawerForm做成HoC或hook使用更合适

### ISSUE THREAD

**Issue by skyblue** [ant-design/pro-components#5189]
感觉  ModalForm,   DrawerForm做成HoC或hook使用更合适

**Comment by Dunqing** [comment]
在SchemaForm使用ModalForm还是挺舒服的

**Comment by chenshuai2144** [comment]
配置太多了很难满足所有的需求。有兴趣可以自己封装。
官方支持了就要维护，做不好会被人喷的
