### ISSUE TITLE
表单的colums和table的colums可以用一个吗？🧐[问题]

### ISSUE THREAD

**Issue by vs0533** [ant-design/pro-components#5193]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
想从服务器端下发colums 请问form和table是否需要单独下发一份

首先，我注意到文档里提到
**SchemaForm 表单最重要就是 Schema 的类型定义，我们使用了与 table 的相同的表单定义，同时扩展了部分字段**

但同时又注意到form的colums类型是
**ProFormColumnsType | ProFormColumnsType[]**

而table的colums则是**ProColumns**

搞不清楚区别 很糊涂

**Comment by PlutoCA** [comment]
可以一起用的
试一试就知道了
