### ISSUE TITLE
🧐[问题] EditableProTable作为ProFormDependency的子项，如果用户不主动修改table，那么submit时获取不到table的数据

### ISSUE THREAD

**Issue by scrapstation** [ant-design/pro-components#5194]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

功能：输入商品规格会自动计算用户需要填写的SKU表格，用户直接提交，或者修改表格后提交

问题：如果用户不去改变表格内容，ProForm.Item 的 trigger 不会被触发，继而proform拿不到表格的值

用户未操作table（submit没有skus表格数据）:
<kbd><img src="https://user-images.githubusercontent.com/56467036/167265386-942f2ecd-13f9-4fa3-9e55-9c7e22f2b5e3.png" width="300px" /></kbd>

用户操作过table（submit包含skus表格数据）:
<kbd><img src="https://user-images.githubusercontent.com/56467036/167265618-260fa1fc-62ef-412f-a554-670ba27793bc.png" width="300px" /></kbd>

### 💻 示例代码

```
<ProFormDependency name={["attributes"]}>
  {({ attributes }) => {
    const tableData = calculateData(attributes);
    return (
      <ProForm.Item trigger="onValuesChange" label="规格明细" name="skus">
        <EditableProTable
          cardProps={{ bodyStyle: { padding: 0 } }}
          rowKey="id"
          size="small"
          bordered
          columns={calculateColumns(attributes)}
          value={tableData}
          recordCreatorProps={false}
          editable={{
            type: "multiple",
            editableKeys: tableData.map((x) => x.id),
            actionRender: (row, config, defaultDoms) => {
              return [defaultDoms.delete];
            },
          }}
        />
      </ProForm.Item>
    );
  }}
</ProFormDependency>

```

### 🚑 其他信息

**Comment by scrapstation** [comment]
找到一个方案：包一层，props自己定义一个onxxxchange，ProForm.Item上tigger=“onxxxchange”，初始化数据的时候调一下这个onxxxchange

**Comment by scrapstation** [comment]
@chenshuai2144 rc-field-form这个包，tigger只能写一个，后续会不会支持数组

**Comment by chenshuai2144** [comment]
你可以用 initialvalue 来注入的，没必要搞这么复杂

**Comment by scrapstation** [comment]
EditTable的值会随FormItem变化，初始值应该解决不了

**Comment by chenshuai2144** [comment]
ProFormDependency  值变化之后销毁一下 可编辑表格呢？

**Comment by scrapstation** [comment]
问题出在:

当ProEditTable的值是由ProFormDependency生成的时候，ProForm并不会收集生成的值
直到ProEditTable被编辑，触发onValuesChange，ProForm才能收集到ProEditTable的值

因此如果用户不编辑ProEditTable，那么ProForm就拿不到生成的值


一个简单但不严谨的例子：

1. 输入成本价1，表格内的销售价默认填充为成本价1
    **a.直接提交，结果为{"costPrice":"1"}, 不能输出销售价，问题复现**
    b.修改默认销售价为2，结果为{"costPrice":"1","table":[{"id":"1","sellingPrice":"2"}]}，可以输出销售价

https://codesandbox.io/embed/yu-formitem-pei-he-forked-jyohfu

**Comment by scrapstation** [comment]
我现在的方案是
```
<ProForm.Item trigger="onChange" label="规格明细" key={newGuid()} name="skus">
       <SkuTable attributesCellSize={attributesCellSize} value={calculateSkuTableData(attributes)} attributes={attributes ?? []} />
</ProForm.Item>
```

``` 
// SkuTable.tsx
useEffect(() => {
  props.onChange?.(props.value);
}, []);
```

在包一层，初始化的时候调用以下onChange，为的是让form收集一下初始值
