### ISSUE TITLE
🧐[问题] ProList新UI吗？

### ISSUE THREAD

**Issue by DerrickTel** [ant-design/pro-components#5196]
### 🧐 问题描述

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/24643779/167332999-d4190d46-46aa-46f1-bf2a-e09756ec1023.png">

### 💻 示例代码

官网
https://procomponents.ant.design/components/list

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
被 markdown覆盖了样式了。

@PeachScript  辟起看看

**Comment by PeachScript** [comment]
@chenshuai2144 应该是预渲染的 DOM 和 CSR 对不齐引起的，从首页开始、再进入该页面是正常的
