### ISSUE TITLE
🐛[BUG] pro-layout, type 遺失

### ISSUE THREAD

**Issue by kudorori** [ant-design/pro-components#5197]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
pro-layout 的 type 遺失

### 📷 复现步骤
https://codesandbox.io/s/antd-pro-layout-type-not-define-gei7zh?file=/src/App.tsx

### 🏞 期望结果
type 正確

### 💻 复现代码

https://codesandbox.io/s/antd-pro-layout-type-not-define-gei7zh?file=/src/App.tsx

### © 版本信息
6.38.0

### 🚑 其他信息
推測是 GlobalTypes 有異常

**Comment by chenshuai2144** [comment]
重新更新下试试，重新编辑了

**Comment by NickeyLin** [comment]
最新版本还是有问题呢。 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/2948405/174774664-7738b8d5-c275-4df7-93e8-ac6caa7c162c.png">

```
└─ @ant-design/pro-layout@6.38.9
```
