### ISSUE TITLE
🧐[问题] 表单模式下的重置按钮如何隐藏

### ISSUE THREAD

**Issue by wehuss** [ant-design/pro-components#52]
### 🧐 问题描述

如何在表单模式下隐藏重置按。
由于网站迁移还未完成，无法查阅相关API，故提交Issue，希望有人能解答

**Comment by mtianyan** [comment]
search={{
              optionRender: false,
            }}

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/table#search
看看这里
