### ISSUE TITLE
🧐[问题] ProTable 每页显示最大条数切换无反应

### ISSUE THREAD

**Issue by 2984350008** [ant-design/pro-components#520]
ProTable 分页功能，切换表格每页最大显示条数时没有反应，比如默认每页显示20条数据，切换点击切换为每页显示10条数据，表格没有变化。

代码如下（是官网上的案例）：
export default () => {
  return (
    <ProTable
      columns={columns}
      request={(params, sorter, filter) => {
        // 表单搜索项会从 params 传入，传递给后端接口。
        console.log(params, sorter, filter);
        return Promise.resolve({
          data: tableListDataSource,
          success: true,
        });
      }}
      rowKey="key"
      pagination={{
        showQuickJumper: true,
      }}
      search={false}
      dateFormatter="string"
      headerTitle="表格标题"
      toolBarRender={() => [
        <Button>查看日志</Button>,
        <Button>
          导出数据
          <DownOutlined />
        </Button>,
        <Button type="primary">创建应用</Button>,
      ]}
    />
  );
};

如下图点击切换无反应
![image](https://user-images.githubusercontent.com/21216448/93317806-769fc900-f840-11ea-824d-58894dec4ab3.png)

**Comment by chenshuai2144** [comment]
试了一下没有问题，你的demo方便展示一下吗？

**Comment by thathappiness** [comment]
@chenshuai2144 我也遇到这个问题，用ProTable官方页面的示例代码同样无法切换每页最大条目数量

**Comment by chenshuai2144** [comment]
升级一下antd 的版本呢，官网的demo是没有问题的

**Comment by thathappiness** [comment]
问题解决了，是我是用的pro-table的版本太低的问题，更新到最新版的pro-table 后就正常了
