### ISSUE TITLE
🐛[BUG]ProFormList组件alwaysShowItemLabel属性为false失效

### ISSUE THREAD

**Issue by Shurangan** [ant-design/pro-components#5200]
### 🐛 bug 描述
ProFormList组件alwaysShowItemLabel属性为false失效

### 📷 复现步骤
https://codesandbox.io/s/proform-list-position-forked-ll3j1r?file=/App.tsx

### 🏞 期望结果
正常通过alwaysShowItemLabel属性展示Form Item 中的label

### 💻 复现代码
https://codesandbox.io/s/proform-list-position-forked-ll3j1r?file=/App.tsx

### © 版本信息

- @ant-design/pro-form 版本: [e.g. 1.67.1]
- 浏览器环境 "Google Chrome";v="101.0.4951.54"
- 开发环境 [e.g. Windows 10  19043.1645]

**Comment by DerrickTel** [comment]
<img width="601" alt="image" src="https://user-images.githubusercontent.com/24643779/167622315-55802731-480d-412a-8d53-b86e7632a86f.png">

加了itemRender了，不适用了

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，感谢你向我们反馈问题。

经过分析，这似乎是一个已知问题，你可以参考相关的 issue：[#5004][🧐[问题] ProFormList设置alwaysShowItemLabel，但新增的行并未展示label][66%]。在该 issue 中也许可以找到一些解决方案或者 workarounds。

另外，如果你使用的是旧版本的 @ant-design/pro-form，建议升级到最新版本。最新版本的文档已经明确了 alwaysShowItemLabel 属性的作用，并提供了详细的示例代码，可以让你更好地使用该属性。

如果你需要更多帮助或者有其他问题，请随时在该 issue 或者其他合适的地方提出，我们会尽力帮助你解决问题。
