### ISSUE TITLE
🐛[BUG] 鼠标在 ProFormText 处松开会导致选中当前输入框

### ISSUE THREAD

**Issue by BBREEZE** [ant-design/pro-components#5204]
🐛 bug 描述
鼠标在 ProFormText 处松开会导致选中当前输入框

📷 复现步骤
鼠标在 ProFormText 处松开会导致选中当前输入框

🏞 期望结果
鼠标在 ProFormText 处松开不选中当前输入框

💻 复现代码
https://procomponents.ant.design/components/form

© 版本信息
最新

**Comment by BBREEZE** [comment]
日期表单表现也不一致 : )

**Comment by chenshuai2144** [comment]
hove是 mouseover+mouseout

**Comment by BBREEZE** [comment]
大佬  有方便的好改的方式吗， 对于我来说无所谓的，只是产品那边希望这样。
比如 取消监听onmouseup？

**Comment by chenshuai2144** [comment]
你可以把 onmouseup 事件防止冒泡掉，这样就没问题了

**Comment by chenshuai2144** [comment]
产品 总是把程序员当成耗材
