### ISSUE TITLE
🐛[BUG] ProTable 切换浏览器页面标签，再回去会导致表格重新request

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#5205]
### 🐛 bug 描述

ProTable 切换浏览器页面标签，再回去会导致表格重新request

### 📷 复现步骤

ant-design-pro 拉取后，再 npm install ，启动项目 打开表格 即可复现

**Comment by kungege** [comment]
[#5168 (comment)](https://github.com/ant-design/pro-components/issues/5168#issuecomment-1118260050)

**Comment by chenshuai2144** [comment]
evalidateOnFocus | 窗口聚焦时自动重新请求 | boolean | true
-- | -- | -- | --
