### ISSUE TITLE
🐛[BUG] menu access控制失效, 回饋的值為false時Menu還會顥示 

### ISSUE THREAD

**Issue by JennyLeung030** [ant-design/pro-components#5207]
### 🐛 bug 描述
menu 沒有辨法跟據access的值控制每個角色可以顥示的內容

### 🏞 期望结果

根據角色顥示不同的Menu

### © 版本信息

- ProComponents 版本: 5.0.0 
- umi 版本 3.5.0
- 浏览器环境 Chrome
- 开发环境 win10

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/51438629/167767228-a7295b70-7443-44d1-a5d7-e428907dac74.png)

![image](https://user-images.githubusercontent.com/51438629/167767614-4d174bcb-710a-4c49-9dfa-9a0eb14be469.png)

![image](https://user-images.githubusercontent.com/51438629/167767637-f5d72cd1-6f84-4597-8f88-e41a77e1f1c8.png)

**Comment by hastings0714** [comment]
同样的问题，有解决吗？

**Comment by hastings0714** [comment]
@chenshuai2144 pro-layout 更新后 menu access功能失效，降级到6.26.5这个版本是正常的。
![image](https://user-images.githubusercontent.com/13328882/168515248-fd350508-8285-4334-a54c-d52a71cd4b9a.png)

**Comment by fanck0605** [comment]
同样的问题，我这里是必须显式的声明权限为 false 才能生效，默认 undefined 就还是会显式菜单

**Comment by vVvlife** [comment]
看来大家都遇到了，问题出现在二级，权限false却能返回栏目

**Comment by vVvlife** [comment]
@chenshuai2144 ant-design/pro-layout@6.38.2 会报没有权限的二级栏目无法对应中文
![image](https://user-images.githubusercontent.com/20148964/169467288-50566d64-5ce2-44cd-b343-afe0cbc83d44.png)
虽然点进去是403无权限，但是会暴露栏目

**Comment by vVvlife** [comment]
> 
版本采用6.38.2
我rm 了node_modules 和lock文件
重新npm install后，解决了这个问题

**Comment by vVvlife** [comment]
> 同样的问题，有解决吗？

版本采用6.38.2
我rm 了node_modules 和lock文件
重新npm install后，解决了这个问题

**Comment by JennyLeung030** [comment]
> 

rm lock file ?

**Comment by vVvlife** [comment]
> > 
> 
> rm lock file? 你指package-lock.json嗎?

是的

**Comment by JennyLeung030** [comment]
> > > 
> > 
> > 
> > rm lock file? 你指package-lock.json嗎?
> 
> 是的

我剛剛嚐試你寫方的方法,解決不了

**Comment by vVvlife** [comment]
> > > > 
> > > 
> > > 
> > > rm lock file? 你指package-lock.json嗎?
> > 
> > 
> > 是的
> 
> 我剛剛嚐試你寫的方法,解決不了

你pro-layout的版本是多少

**Comment by vVvlife** [comment]
> > > > 
> > > 
> > > 
> > > rm lock file? 你指package-lock.json嗎?
> > 
> > 
> > 是的
> 
> 我剛剛嚐試你寫的方法,解決不了

你pro-layout的版本是多少

**Comment by JennyLeung030** [comment]
> > > > > 
> > > > 
> > > > 
> > > > rm lock file? 你指package-lock.json嗎?
> > > 
> > > 
> > > 是的
> > 
> > 
> > 我剛剛嚐試你寫的方法,解決不了
> 
> 你pro-layout的版本是多少

![image](https://user-images.githubusercontent.com/51438629/169724977-e3c4ae2a-cd32-4882-bb98-e1968b4a57a2.png)

**Comment by vVvlife** [comment]
> 
> 我剛剛嚐試你寫的方法,解決不了

你pro-layout的版本是多少

> > > > > > 
> > > > > 
> > > > > 
> > > > > rm lock file? 你指package-lock.json嗎?
> > > > 
> > > > 
> > > > 是的
> > > 
> > > 
> > > 我剛剛嚐試你寫的方法,解決不了
> > 
> > 
> > 你pro-layout的版本是多少
> 
> ![image](https://user-images.githubusercontent.com/51438629/169724977-e3c4ae2a-cd32-4882-bb98-e1968b4a57a2.png)
> 
> 跟你一樣都是使用6.38.2

那你可以验证下 canAccessAdminFunction 返回的是否是个false值，找个页面引用umi的useAccess
毕竟我上周就是这样解决的，觉得问题出在依赖冲突的问题

**Comment by JennyLeung030** [comment]
> 

![image](https://user-images.githubusercontent.com/51438629/169726566-69b701cb-9f82-4a07-8ba7-2a8848d629a6.png)
我在config.js 添加了 access: {}, menu就根據access顥示

**Comment by vVvlife** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/51438629/169726566-69b701cb-9f82-4a07-8ba7-2a8848d629a6.png) 我在config.js 添加了 access: {}, menu就根據access顥示

早期的版本没有这个属性，我也没注意到，解决就好

**Comment by JennyLeung030** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/51438629/169726566-69b701cb-9f82-4a07-8ba7-2a8848d629a6.png) 我在config.js 添加了 access: {}, menu就根據access顥示
> 
> 早期的版本没有这个属性，我也没注意到，解决就好

3Q~

**Comment by chenshuai2144** [comment]
已经修复，全部升级到最新版本即可
