### ISSUE TITLE
🐛[BUG] ProTable 触发 request 不合理？

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-components#5210]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

其它软件全部遮挡浏览器时或点浏览器任务显示与隐藏时

### 📷 复现步骤

https://codesandbox.io/s/cha-xun-biao-ge-forked-hx8yxu?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kaoding** [comment]
浏览器多标签切换时也会触发。

**Comment by Dunqing** [comment]
cc https://github.com/ant-design/pro-components/issues/5168#issuecomment-1118260050

**Comment by kaoding** [comment]
谢谢
