### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by Kun8018** [ant-design/pro-components#5212]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProSelect的多选框右侧没有箭头 也没有开启箭头的选项

### 📷 复现步骤

正常使用ProSelect，添加mode="multiple"

### 🏞 期望结果

正常使用ProSelect，添加mode="multiple"之后选框内依然有箭头符号

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个是设计，去antd 官网看看
