### ISSUE TITLE
🧐[问题] 使用proTable request调用后端接口报错

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/pro-components#5214]
### 🧐 问题描述

 尝试使用ProTable的request属性调用后端接口，但是控制台报错
![image](https://user-images.githubusercontent.com/33271366/167987300-17e19079-3954-49a3-a8bb-f07e6644c6a8.png)

### 💻 示例代码

![image](https://user-images.githubusercontent.com/33271366/167987349-faf156cb-55b2-474c-bbe0-daddb8389b04.png)

**Comment by PLUTO06210331** [comment]
e

**Comment by chenshuai2144** [comment]
这是接口报错，看看你的接口把
