### ISSUE TITLE
🐛[BUG] proLayout 函数 menuItemRender 参数类型定义问题

### ISSUE THREAD

**Issue by 569202812** [ant-design/pro-components#5215]
### 🐛 bug 描述
`BaseMenuProps`的类型中缺少了 PrivateSiderMenuProps的返回
`
 // 类型
menuItemRender?: WithFalse<
    (
      item: MenuDataItem & {
        isUrl: boolean;
        onClick: () => void;
      },
      defaultDom: React.ReactNode,
      menuProps: BaseMenuProps,
    ) => React.ReactNode
  >;

  // 组件
  const BaseMenu: React.FC<BaseMenuProps & PrivateSiderMenuProps> = (props) => { 
    const [menuUtils] = useState(() => new MenuUtil(props));
    menuUtils.props = props;

    return ‘xxx’ 
  }

  // 回调时
   if (menuItemRender) {
      const renderItemProps = {
        ...item,
        isUrl: isHttpUrl,
        itemPath,
        isMobile,
        replace: itemPath === location.pathname,
        onClick: () => {
          if (isHttpUrl) window.open(itemPath);
          if (onCollapse) onCollapse(true);
        },
        children: undefined,
      };
      return menuItemRender(renderItemProps, defaultItem, this.props);
    }
`

### 🏞 期望结果

返回类型修改

**Comment by chenshuai2144** [comment]
这个是故意的，尽量不要用
