### ISSUE TITLE
🐛[BUG] 轻量筛选替换查询表单css 顺序变更导致 padding 异常

### ISSUE THREAD

**Issue by faner11** [ant-design/pro-components#5220]
### 🐛 bug 描述
当设置轻量筛选后,padding与官方demo不一致
```
 search={{
    filterType: 'light'
 }}
```
- 官网版本
![image](https://user-images.githubusercontent.com/26560612/168050716-f4196706-fc0e-4b4c-a857-424a67bbfe0c.png)

- 本地代码
![image](https://user-images.githubusercontent.com/26560612/168050548-7aa5feeb-9f41-4e18-a293-fa500e5eacda.png)

css 顺序变了，导致了这个问题

### © 版本信息

- ProComponents 版本: [e.g. 2.74.3]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
https://procomponents.ant.design/components/table/?current=1&pageSize=5#%E8%BD%BB%E9%87%8F%E7%AD%9B%E9%80%89%E6%9B%BF%E6%8D%A2%E6%9F%A5%E8%AF%A2%E8%A1%A8%E5%8D%95

**Comment by Dunqing** [comment]
顺序无法影响被覆盖，得调整权重
