### ISSUE TITLE
👑 [需求]希望LightFilter能提供trigger

### ISSUE THREAD

**Issue by KamChing** [ant-design/pro-components#5221]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

LightFilter
### 🥰 需求描述

<html>
<body>

trigger | 触发下拉的行为
-- | --

</body>
</html>

### ⛰ 功能需求适用场景

使用LightFilter包含ProFormSelect，目前只能鼠标点击性别出现下拉列表，需要增加鼠标移上性别，出现下拉列表，鼠标移出到性别和下拉列表以外的地方，需要隐藏。

### 🧐 解决方案

无

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/30040491/168054118-4f444f29-1853-4e22-81fc-ed95c331c212.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您对我们项目的关注和支持！我们非常欢迎您的贡献。您可以按照上述方式创建一个 Pull Request，我们会尽快对您的贡献进行评审并合并到主干。如果您有任何问题，请随时提出，我们会尽力提供帮助。
