### ISSUE TITLE
🧐[问题] Protable 通过request请求数据 没有分页

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/pro-components#5223]
我通过proTable的request请求后端数据，修改pageSize为10，返回为11条，页面没有分页

### 💻 示例代码

![image](https://user-images.githubusercontent.com/33271366/168190850-517a149c-7e60-404b-a860-f5332c7168c4.png)

**Comment by JennyLeung030** [comment]
要自己做分頁處理

**Comment by PLUTO06210331** [comment]
@JennyLeung030  自己重写分页吗

**Comment by chenshuai2144** [comment]
pageSize 一定要和data 里面的数据相同，不然 table 会认为你是本地分页。
