### ISSUE TITLE
🧐[问题]ProTable的自定义查询表单renderFormItem如何设置表单的值，才不会报错？

### ISSUE THREAD

**Issue by songhechuan** [ant-design/pro-components#5224]
🧐 问题描述
功能需求：
  ProTable的查询表单，根据其中的表单项，动态显隐其它字段，并且对隐藏的字段值进行初始化，再次显示隐藏的字段，字段值为初 
始化（空值）的状态。

“搜索表单自定义” 官方的示例代码：https://procomponents.ant.design/components/table?current=1&pageSize=5#%E6%90%9C%E7%B4%A2%E8%A1%A8%E5%8D%95%E8%87%AA%E5%AE%9A%E4%B9%89

做完以下步骤，如何实现：动态表单 项的值应该为空，而不是 “一月” 的效果。
1.状态选择：月份，动态表单选择：一月；
2.状态选择：不显示；
3.状态选择：月份；

期望结果：
![image](https://user-images.githubusercontent.com/85599708/168219325-ccbe7562-8f07-4061-91d4-2cbac9e38a7f.png)

实际结果：
![image](https://user-images.githubusercontent.com/85599708/168219371-1cb1a310-eb72-4ab8-b1a2-edb75cc54c75.png)

💻 示例代码
我试过在判断不显示时，使用form.setFieldsValue( { direction: undefined } ) 或 form.resetFields( ['direction'] )来初始化direction字段，实际上是可以初始化 direction 字段的值，但是控制台会报错。
![image](https://user-images.githubusercontent.com/85599708/168219054-45ac4c9b-b8db-4dd5-8044-149c140bcc57.png)

![image](https://user-images.githubusercontent.com/85599708/168218253-09c4b325-bbd0-4ea7-bedf-3c16ff541a81.png)

如何才能解决这个问题？

**Comment by Dunqing** [comment]
没看明白，提供个codesandbox示例

**Comment by chenshuai2144** [comment]
renderFormItem 里面最好不要设置值，不然会导致死循环的，这个报错就是频繁销毁和重建导致的。

你可以在 renderFormItem  返回的组件生命周期里面去做，性能会好很多

**Comment by chenshuai2144** [comment]
renderFormItem 里面最好不要设置值，不然会导致死循环的，这个报错就是频繁销毁和重建导致的。
