### ISSUE TITLE
👑 [需求]目前有login-form，但是没有register-form

### ISSUE THREAD

**Issue by topwood** [ant-design/pro-components#5226]
### 🔩 所属模块或组件
目前有login-form，但是没有register-form

### 🥰 需求描述

希望有register-form

### ⛰ 功能需求适用场景

能用来给用户注册使用

### 🚑 其他信息

如果用Login-form去实现register-form，比如输入密码的二次校验目前就没有看到api可以去解决

**Comment by chenshuai2144** [comment]
register 做起来有点复杂，主要是每个功能不一样，你的需求应该让ProFormPassWord 来实现
