### ISSUE TITLE
🧐[问题]rowProps和colProps如何在ProForm中使用？

### ISSUE THREAD

**Issue by simon-zhangmuye** [ant-design/pro-components#5229]
能不能给个例子？给我整蒙了

**Comment by Dunqing** [comment]
SchemaForm: https://procomponents.ant.design/~demos/schemaform-schema
ProForm: https://procomponents.ant.design/~demos/form-form-layout-grid

**Comment by cqb421392034** [comment]
SchemaForm 不能在json中单独列配置的吗

**Comment by Dunqing** [comment]
> SchemaForm 不能在json中单独列配置的吗

可以
