### ISSUE TITLE
🐛[BUG] ProTable 轻量筛选替换查询表单 日期范围改成时间范围无法显示全

### ISSUE THREAD

**Issue by stantoxt** [ant-design/pro-components#5232]
### 🐛 bug 

ProTable 轻量筛选替换查询表单 日期范围改成时间范围无法显示全

### 📷 复现步骤
将官方文档 轻量筛选替换查询表单 的 日期范围的valueType 改为 dateTimeRange
```
const columns: ProColumns<TableListItem>[] = [
  {
    title: '日期范围',
    dataIndex: 'startTime',
    valueType: 'dateTimeRange',
    hideInTable: true,
    initialValue: [moment(), moment().add(1, 'day')],
  }
];
```

https://codesandbox.io/s/qing-liang-shai-xuan-ti-huan-cha-xun-biao-dan-forked-lb4fcv?file=/App.tsx:992-1001

### 🏞 期望结果
轻量筛选替换查询表单  显示的结束时间

### © 版本信息

- ProTable 版本: [2.74.3]
- chrome
- 开发环境 [e.g. window 11 OS]

**Comment by Dunqing** [comment]
看起来这个pr正在修复 https://github.com/ant-design/pro-components/pull/5169

**Comment by stantoxt** [comment]
> 看起来这个pr正在修复 #5169

@Dunqing 感谢

**Comment by nyl1223** [comment]
请问这个问题解决了吗

**Comment by chenshuai2144** [comment]
解决了，可以更新版本了
