### ISSUE TITLE
🧐[问题] ProForm 中 如何获取 request 返回的值

### ISSUE THREAD

**Issue by xiexingen** [ant-design/pro-components#5235]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
某些场景下，新增和编辑复用同一个 ProForm，但是编辑模式下可能会根据 request 返回的值来禁用某几个字段的编辑功能。怎么获取到 reqeust 里面返回的值

**Comment by chenshuai2144** [comment]
ProForm  的 request  会交给 initialvalues，你可以在request里面写个.then 来进行保存和编辑。
