### ISSUE TITLE
👑 [需求] ProFormUploadButton上传请求不走请求拦截器

### ISSUE THREAD

**Issue by CementSealing** [ant-design/pro-components#5236]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件 
ProFormUploadButton

### 🥰 需求描述
在ProFormUploadButton组件中，配置 action上传地址，并在项目app.ts中配置了requestInterceptors请求拦截器时，上传图片的请求不会经过请求拦截器。

### ⛰ 功能需求适用场景

项目配置了请求拦截器，并在使用上传组件时，上传请求会走拦截器。

**Comment by creampnx-x** [comment]
试试 antd 的 upload 组件吧，大概率是那里的问题

**Comment by CementSealing** [comment]
> 试试 antd 的 upload 组件吧，大概率是那里的问题

好像也是不行噢，它有个配置是`headers`，不知道是不是因为不走拦截器，所以只能通过组件来配置请求头，要是这样的话那还是挺麻烦的

**Comment by Dunqing** [comment]
Upload组件是内部发的请求，和你拦截器的request不是同一个东西

**Comment by RhysZhao** [comment]
Upload组件上传用的XMLHttpRequest。你用的拦截器是axios的，只能拦截axios发出的请求
