### ISSUE TITLE
🧐[问题]对于protable组件，列的类型为select时，有办法插入antd那样的不可选中状态的选项、或者分组选项吗

### ISSUE THREAD

**Issue by mojerro** [ant-design/pro-components#5237]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

对于`protable`组件，列的类型为`select`时，有办法插入antd那样的不可选中状态的选项、或者分组选项吗。
![image](https://user-images.githubusercontent.com/15071824/168721854-66f29550-1dea-4706-ae42-41878c02b9a5.png)

### 🚑 其他信息

antd截图
![image](https://user-images.githubusercontent.com/15071824/168722051-4b9e589a-cd1d-4957-a618-eab3f431e57d.png)
![image](https://user-images.githubusercontent.com/15071824/168722073-4a67a405-e48e-4fbf-8259-2b2027a96d90.png)

**Comment by chenshuai2144** [comment]
可以的 和antd 的使用一样，你拼接 options 是什么样子我们就是会什么样子
