### ISSUE TITLE
🧐[问题] 关于文档参数的问题

### ISSUE THREAD

**Issue by simon-zhangmuye** [ant-design/pro-components#5241]
很多参数没有说明，比如
![image](https://user-images.githubusercontent.com/10706610/168930616-990b8e12-059a-4e27-8211-2ccdd4e02cd8.png)
colsize这个应该是QueryFilter才有，但是文档没写。
还有很多参数不知道去哪里找对应文档
![image](https://user-images.githubusercontent.com/10706610/168930879-652b675e-94e7-4354-b82c-95b97cc65eed.png)

**Comment by DerrickTel** [comment]
这个可能要dumi来看看啥情况了，你可以看看是哪个组件的属性。比如`ProFormList`里面的`alwaysShowItemLabel`。
可以先进入相应的组件然后，Ctrl/Command + F
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/24643779/168984186-5ba32f62-4674-4022-8ebc-98e3660fd312.png">

**Comment by chenshuai2144** [comment]
[Dunqing](https://github.com/Dunqing) 要补充一下 col 这些的文档了
