### ISSUE TITLE
可编辑表格的表格联动操作怎么做呢，官网能不能出个示例🧐[问题]

### ISSUE THREAD

**Issue by zhaomenglu** [ant-design/pro-components#5246]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

可编辑表格中的一行的数据中，修改某个数据，希望使用setFieldsValue赋值给另外一个字段，例如下图中如果状态选择已解决，描述默认设置为‘开心’

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/39189837/169002900-0e5756cc-8bd4-48a0-93be-9ccc5f165078.png)

**Comment by zhaomenglu** [comment]
在proTable里的可编辑状态，如何实现表格联动

**Comment by zhaomenglu** [comment]
proTable里的form没有editableFormRef的这个属性，那应该怎么用呢

**Comment by chenshuai2144** [comment]
editableFormRef 是个ref，你保存出来哪里用的都可以的。

**Comment by zzcbnz** [comment]
有实现方案了吗

**Comment by earthaYan** [comment]
@chenshuai2144 尝试使用editableFormRef  使用setRowData或者setFieldValue给需要联动的字段设置默认值，并不生效

**Comment by hoosin** [comment]
这个没解决关了干啥
