### ISSUE TITLE
ProList light模式下工具栏出现了滚动条 生产环境下工具栏出现了滚动条，开发环境下没有

### ISSUE THREAD

**Issue by chrisFan-cc** [ant-design/pro-components#5249]
### 🐛 bug 描述
这是开发环境下的，正常清空：
![image](https://user-images.githubusercontent.com/56374279/169194404-e44f9575-5407-489f-b25a-87b687132601.png)
这是部署到生产环境后，工具栏出现了滚动条
![image](https://user-images.githubusercontent.com/56374279/169194786-eb49c9e6-dd68-4e35-89d0-84b88461fe16.png)

### © 版本信息
Ant Design Pro v5
"@ant-design/pro-list": "^1.21.61",

**Comment by Dunqing** [comment]
用devtools看看样式有什么不一样

**Comment by ONLY-yours** [comment]
确实有这个情况出现，官网的例子就有：
https://procomponents.ant.design/components/list#%E5%B8%A6%E7%AD%9B%E9%80%89%E5%92%8C%E5%BC%82%E6%AD%A5%E8%AF%B7%E6%B1%82%E7%9A%84%E5%88%97%E8%A1%A8

不是很清楚出现条件是什么

![image](https://user-images.githubusercontent.com/52664827/172148002-de908b6e-897c-4b3e-84d2-51d22b16e096.png)

**Comment by ONLY-yours** [comment]
![image](https://user-images.githubusercontent.com/52664827/172148382-16c3c195-3b66-48da-a0d5-8ddaedc597b0.png)

@chenshuai2144  有必要改动为Hidden么？
