### ISSUE TITLE
👑 [需求] ProDescriptions editable 状态下 valueType="select" 时能通过输入条件查询request

### ISSUE THREAD

**Issue by Saraph1nes** [ant-design/pro-components#5251]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

ProDescriptions

### 🥰 需求描述

ProDescriptions  editable 状态下 valueType="select" 时能通过输入条件 request

### ⛰ 功能需求适用场景

选择根据搜索条件返回的数据

**Comment by Saraph1nes** [comment]
找到解决方案了，谢谢

**Comment by WuJiY** [comment]
什么解决方案 分享一下
