### ISSUE TITLE
👑 [需求] 希望有一个不需要 Total 的分页组件，仅有 pageSize，currentPage 参数

### ISSUE THREAD

**Issue by zhwwashere** [ant-design/pro-components#5254]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件
Pagination分页组件：https://ant.design/components/pagination-cn/

### 🥰 需求描述
目前分页组件 Pagination 必须要传 total 参数，但对于一些数据，db 的total 查询十分浪费性能，且存在很大的服务端慢SQL隐患，希望能够提供一个不需要传 Total 的分页器，仅保留 pageSize，currentPage 两个 Props。
在页面上，保留上一页、下一页的选项，即使下一页没数据，直接显示空白即可。

**Comment by DerrickTel** [comment]
那你自己写死一个9999呢？

**Comment by chenshuai2144** [comment]
Total 都浪费性能了，total 语法加了索引性能很好的。感觉你过度优化了。

你可以自定义一个  Pagination
