### ISSUE TITLE
🧐[问题]使用 PageContainer 组件发现内容区域最下面有一段 DOM 如何除去？

### ISSUE THREAD

**Issue by Grain-full** [ant-design/pro-components#5259]
我使用 PageContainer 组件包裹一个 ProTable 组件，现在做动态适配屏幕，发现内容区域内有一段 DOM 代码
代码为 `<div style="height: 48px; margin-top: 24px;"></div>`，为什么会生成这段代码？如何去除？@ant-design/pro-layout 为v6.26.0

**Comment by Grain-full** [comment]
“<div style="height: 48px; margin-top: 24px;"></div>”

**Comment by Grain-full** [comment]
<div style="height: 48px; margin-top: 24px;"></div>

**Comment by LittleChives** [comment]
请问你如何解决的呢
