### ISSUE TITLE
🧐[问题]的  proform下如何赋初始值    ProFormSelect不显示问题 

### ISSUE THREAD

**Issue by zhangle1** [ant-design/pro-components#5263]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
我给表单传递了如下json
{
"sysEmpInfo":{
   positions:[
    {
              "posId": 142307070910549,
              "posCode": "bmjl",
              "posName": "部门经理"
     },
    {
              "posId": 1423070709105492,
              "posCode": "bmjl",
              "posName": "部门经理2"
     },
   ]
  }
}
我尝试给ProFormSelect 写name 属性如下
     <ProFormSelect
                mode="multiple"
                **name={['sysEmpInfo','positions','posCode']}**
                label="职位信息"
                }
                placeholder="请选择职位信息"
                rules={[{ required: true, message: '请选择职位信息' }]}
            />

这里positions 是一个数组, 好像这么写并不生效

**Comment by Dunqing** [comment]
`['sysEmpInfo','positions']` 就可以了吧？
