### ISSUE TITLE
[bug] ProFormCheckbox.Group 设置defaultValue无效

### ISSUE THREAD

**Issue by director-zhou** [ant-design/pro-components#5271]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProFormCheckbox.Group 设置defaultValue无效

### 📷 复现步骤
<ProFormCheckbox.Group options={[{label: 1, value: 1}]} fieldProps={{defaultValue: [1]}}></ProFormCheckbox.Group>

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
日经问题，自己去看看issue吧

**Comment by Harry-Wei** [comment]
最后怎么解决的啊，这就Close了？
