### ISSUE TITLE
🧐[问题] 按照官方文档模板进行，提示pro-components 没有导出成员Procard

### ISSUE THREAD

**Issue by liuhui1999** [ant-design/pro-components#5277]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

pro-components没有导出某些成员

### 💻 示例代码
import { ProCard } from '@ant-design/pro-components';

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/71832496/169729007-47f70271-496b-4447-a559-0865401c5c31.png)

**Comment by chenshuai2144** [comment]
升级到最新的版本呢？

**Comment by liuhui1999** [comment]
@chenshuai2144   OK了通过其他方式弄好了
