### ISSUE TITLE
🧐[问题]ProFormDatePicker 没有 showToday API

### ISSUE THREAD

**Issue by TinsFox** [ant-design/pro-components#5278]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

[ProFormDatePicker](https://ant.design/components/date-picker-cn/) 组件没有透传  DatePicker 的 showToday属性
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/33956589/169734556-e59c0953-2d19-480c-905d-6753f56d1b7e.png">

### © 版本信息

-  "antd": "^4.20.0",
-   "umi": "^3.5.0"
-   "@ant-design/pro-form": "^1.64.0"

**Comment by creampnx-x** [comment]
写到`fieldProps`字段里
