### ISSUE TITLE
🐛[BUG]升级ProForm 报错

### ISSUE THREAD

**Issue by strongyc** [ant-design/pro-components#5284]
s\node_modules\@babel\runtime (see exports field in D:\reactProject\yc-archives\node_modules\@babel\runtime\package.json)

 error  in ./node_modules/@ant-design/pro-table/es/components/Form/FormRender.js

**Comment by strongyc** [comment]
一打包就报错，这是什么原因，proTable也报错

**Comment by cuitianze** [comment]
same issue
https://github.com/babel/babel/issues/14576

**Comment by strongyc** [comment]
Module not found: Error: Package path ./helpers/esm/regeneratorRuntime is not exported from package D:\reactProject\yc-archives\node_modules\@ant-design\pro-layout\node_modules\@babel\runtime (see exports field in D:\reactProject\yc-archives\node_modules\@ant-design\pro-layout\node_modules\@babel\runtime\package.json) 很无奈啊，怎么修复啊

**Comment by strongyc** [comment]
急啊，项目无法启动~~~~~~~~

**Comment by strongyc** [comment]
> same issue
> 
> `[CompileProject][INFO] Error: [vite]: Rollup failed to resolve import "@babel/runtime/helpers/esm/regeneratorRuntime" from "node_modules/@ant-design/pro-card/node_modules/@ant-design/pro-utils/es/hooks/useDebounceFn/index.js".`
> 
> [babel/babel#14576](https://github.com/babel/babel/issues/14576)

感谢，解决了，谢谢大佬

**Comment by nicolo-ribaudo** [comment]
This is the same as https://github.com/ant-design/pro-components/issues/5273#issuecomment-1133843012

**Comment by snowrain0722** [comment]
> 同样的问题
> 
> `[CompileProject][INFO] Error: [vite]: Rollup failed to resolve import "@babel/runtime/helpers/esm/regeneratorRuntime" from "node_modules/@ant-design/pro-card/node_modules/@ant-design/pro-utils/es/hooks/useDebounceFn/index.js".`
> 
> [通天塔/通天塔#14576](https://github.com/babel/babel/issues/14576)

mfsu开启后报错：Unhandled Rejection (Error): Cannot find module '@babel/runtime/helpers/esm/regeneratorRuntime'

**Comment by nicolo-ribaudo** [comment]
As a workaround, make sure that you are using `@babel/runtime` at least 7.18.0 and not an older version.
