### ISSUE TITLE
🧐[问题]protable组件属性request第二个参数sort如何重置/设置

### ISSUE THREAD

**Issue by caizhehao** [ant-design/pro-components#5285]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

![image](https://user-images.githubusercontent.com/26589188/169953539-a9d37ad1-a75f-4d6a-b5eb-10387bd20fe9.png)
如上页面，通过点击4个tab(红框)切换加载对应的columns的table；tab(红框)点击通过调用`actionRef?.current?.reloadAndRest()`来实现表格切换，tab切换过程中会将前一个table的排序值带到当前table属性request第二个参数sort中，会影响最新table的request，protable组件属性request第二个参数sort如何重置/设置

### 💻 示例代码

![image](https://user-images.githubusercontent.com/26589188/169954954-3fd6bf0d-c5c3-42d5-b552-550969631ddb.png)

**Comment by chenshuai2144** [comment]
简单一点销毁掉表格吧，sorter受控写起来好难的

**Comment by caizhehao** [comment]
这几个tab表格筛选用的是同一个，销毁表格的话，切换tab筛选的值也会一并清空无法保留公用

**Comment by qiuziGirl** [comment]
> 这几个tab表格筛选用的是同一个，销毁表格的话，切换tab筛选的值也会一并清空无法保留公用

请问最后怎么解决了，可以分享一下吗
