### ISSUE TITLE
👑 [需求]ProTable的columns列定义中的属性tooltip需要跟表格工具栏一样可以配置settings，实现自定义图标

### ISSUE THREAD

**Issue by KamChing** [ant-design/pro-components#5287]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

ProTable组件的columns列定义

### 🥰 需求描述

表格的列标题右侧需要自定义图标，可以设置tooltip，但是只能是默认的图标，需要自定义图标

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/30040491/170006511-05bcc2a9-4fb7-4524-b78a-3a858206f8f5.png)

**Comment by KamChing** [comment]
找到解决方法：Columns列定义的title标题可以写自定义的图标：

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/170442591-8f0cff60-ec52-4e0c-b60e-b595bd67e9ed.png)

可以配置的。
```

 tooltip={{
          icon: '<span>icon</span>',
          title: '包含了从服务器请求，columns等功能',
        }
```
