### ISSUE TITLE
👑 [需求] ProFormList > actionGuard > beforeRemoveRow 增加 currentRowData 参数

### ISSUE THREAD

**Issue by bowencool** [ant-design/pro-components#5288]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

ProForm

### 🥰 需求描述

在编辑场景，有旧数据的时候，我要根据当前行的数据判断能不能删，但是 beforeRemoveRow 参数只有 index ，没有 当前行 的参数

### ⛰ 功能需求适用场景

在编辑场景，有旧数据的时候，我要根据当前行的数据判断能不能删

### 🧐 解决方案

1. 最简单：beforeRemoveRow 增加 currentRowData 参数 
2. 使用 [ProFormList RenderProps 模式](https://procomponents.ant.design/components/group#proformlist-renderprops-%E6%A8%A1%E5%BC%8F)，但我的场景复杂，遇到另外一个[问题](https://github.com/ant-design/pro-components/issues/5155)

**Comment by chenshuai2144** [comment]
提供了一个新的api，get 等发布了可以试试
```tsx
const actionRef = useRef<
    FormListActionType<{
      name: string;
    }>
  >();
```
```tsx
 actionRef={actionRef}
 beforeRemoveRow: async (index, count) => {
            const row = actionRef.current?.get(index as number);
            console.log('--->', index, count, row);
            return new Promise((resolve) => {
              if (index === 0) {
                resolve(false);
                return;
              }
              setTimeout(() => resolve(true), 1000);
            });
          },
```
