### ISSUE TITLE
🐛[BUG]proTable 列设置无法从下拖到第一个

### ISSUE THREAD

**Issue by ttjimsen** [ant-design/pro-components#5289]
![20220526_143801](https://user-images.githubusercontent.com/31235202/170638634-d9bd5966-99d1-4bea-aa46-2be2a2056ad7.gif)
@chenshuai2144

**Comment by ttjimsen** [comment]
![20220526_143801](https://user-images.githubusercontent.com/31235202/170638223-291f5e1e-48d0-4813-966e-df47f645e1ab.gif)

**Comment by zhaomenglu** [comment]
所以这个问题解决了么。。
