### ISSUE TITLE
👑 [需求]ProTable设置size的时候，搜索行也能跟随size变化吗？

### ISSUE THREAD

**Issue by bthulu** [ant-design/pro-components#5293]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件
ProTable

### 🥰 需求描述
当前变更ProTable的size后，仅列表项响应大小变化，上面的搜索行大小维持不变。
希望搜索行也能跟随size变大变小。

### ⛰ 功能需求适用场景
搜索项多的时候，塞不下了。原以为把ProTable的size改成small就行了，谁知道光列表行变紧凑了，上面的搜索行还是那么大。

**Comment by chenshuai2144** [comment]
size是table得，form得可以用 span，span 默认是8，你可以设置为 6
