### ISSUE TITLE
🧐[问题]proComponent的可编辑表单 在 form组件里面行为不受控，该怎么处理

### ISSUE THREAD

**Issue by LbhFront-end** [ant-design/pro-components#5294]
### 🧐 问题描述

没有包裹form之前，可编辑表单可以自由操作，包裹form后，只能更新对应的name，是不是要用form的方法

### 💻 示例代码

能复现的最小例子：https://codesandbox.io/s/ke-bian-ji-biao-dan-bao-guo-zai-formli-mian-gai-zen-me-shou-kong-tejs4n?file=/containers/EditTableForm.tsx

流程演示：
没有包裹Form的，可以正常更新
![image](https://user-images.githubusercontent.com/30042334/170245786-2dfd8c54-68e7-44c3-b670-72bf5b85de78.png)
![image](https://user-images.githubusercontent.com/30042334/170245806-2d408a77-795b-404e-9a43-3e7122b199cd.png)
![image](https://user-images.githubusercontent.com/30042334/170245829-5449604d-c9e0-469f-a277-0bb4fd009616.png)
![image](https://user-images.githubusercontent.com/30042334/170245860-e0c7e42b-c0fe-4ea3-b579-8049d8869756.png)
![image](https://user-images.githubusercontent.com/30042334/170245876-36f73120-932e-4638-87fc-9ee840479f94.png)

而有包裹的只能修改对应的name下的value
![image](https://user-images.githubusercontent.com/30042334/170245969-97d7ebce-a343-441c-af4c-e439d5094e66.png)
![image](https://user-images.githubusercontent.com/30042334/170246008-6712fb96-0528-49c9-81e6-40bff88dddf4.png)

**Comment by chenshuai2144** [comment]
包裹form之后要当成一个 input 来操作，都要走form 来操作。

**Comment by chenshuai2144** [comment]
```
 initialValues={{
        table: defaultData,
      }}


` formRef.current?.setFieldsValue({table: [] })`
```

**Comment by LbhFront-end** [comment]
> ```
>  initialValues={{
>         table: defaultData,
>       }}
> 
> 
> ` formRef.current?.setFieldsValue({table: [] })`
> ```

emmm 谢谢你的解惑，但是我发现原来是 onValueChange出去就行，onChange不起作用 是因为edittable用的trigger是onValueChange 所以我在props拿到这个函数，onValueChange出去我的数组后 解决了这个问题。
