### ISSUE TITLE
🐛[BUG]valueType自定义又挂了

### ISSUE THREAD

**Issue by hanwenbo** [ant-design/pro-components#5295]
提问前先看看：

### 🐛 bug 描述

升级到最新版本后，valueType里的值如果是对象就报错，比如提示：
Objects are not valid as a React child (found: object with keys {id, store_id, user_id, state, name, create_time, update_time, delete_time, user}). If you meant to render a collection of children, use an array instead.

但它就是个对象，我看代码都没有进入到自定义的valueType  render里就挂了，以前没有，只是昨天升级了最新版本，为什么说又挂了，因为之前遇到过，升级解决了，昨天刚解决完 "@babel/runtime": "@^7.18.0" 的bug问题，今天又遇到了object问题，我擦 一个列表调了我4个小时了

### 📷 复现步骤

用最新的版本就行
    "@ant-design/pro-card": "^1.20.4",
    "@ant-design/pro-descriptions": "^1.10.74",
    "@ant-design/pro-form": "^1.68.2",
    "@ant-design/pro-layout": "^6.38.2",
    "@ant-design/pro-list": "^1.21.62",
    "@ant-design/pro-skeleton": "^1.0.6",
    "@ant-design/pro-table": "2.74.4",
    "@ant-design/pro-utils": "^1.41.2",

### 🏞 期望结果

期望正常渲染自定义的组件

### 💻 复现代码

下载最新版本的
    "@ant-design/pro-card": "^1.20.4",
    "@ant-design/pro-descriptions": "^1.10.74",
    "@ant-design/pro-form": "^1.68.2",
    "@ant-design/pro-layout": "^6.38.2",
    "@ant-design/pro-list": "^1.21.62",
    "@ant-design/pro-skeleton": "^1.0.6",
    "@ant-design/pro-table": "2.74.4",
    "@ant-design/pro-utils": "^1.41.2",
然后自定义一个valueType, 值是object的，比如一个用户字段，里面包含了头像、昵称、id

### © 版本信息

- ProComponents 版本: 最新的
- umi 版本 3.5.24
- 浏览器环境  谷歌浏览器
- 开发环境 mac OS]

### 🚑 其他信息

没了

**Comment by hanwenbo** [comment]
前几天还好好的，升个级就空了
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/5869741/170409948-3b4ef597-16a5-4a4b-bc26-c7a68f3bea05.png">

**Comment by hanwenbo** [comment]
我测了  就算是 valueTypeMap 存在也是无法渲染，哎 ，这个功能期待早日发布稳定版 ，每次升级这儿都会调一天，先降级了

**Comment by hanwenbo** [comment]
> 确定是那个版本包的问题吗？我需要固定哪个包的版本才能正常？

需要一个个试  valueTypeMap 一直都不稳定  不知道官方遇到了什么技术难点

**Comment by chenshuai2144** [comment]
https://www.npmjs.com/package/@ant-design/pro-components

统一用这个库，不要自己管理版本就不会有问题
