### ISSUE TITLE
🐛[BUG]ProTable search optionRender->false 时，ant-pro-table-search-option 依然存在Dom中，未移除掉。

### ISSUE THREAD

**Issue by mtianyan** [ant-design/pro-components#53]
### 🐛 bug 描述

type="form" 时 已经设置optionRender->false，只是隐藏了按钮，但是Dom中还存在search-option 。

![image](https://user-images.githubusercontent.com/15145231/88777076-644acc80-d1b9-11ea-8c69-1c94337e6428.png)

### 📷 复现步骤

<ProTable
  search={{
              optionRender: false,
            }}
>

### 🏞 期望结果

希望optionRender->false ，按钮消失，ant-pro-table-search-option 也消失掉。

### 💻 复现代码

<ProTable
  search={{
              optionRender: false,
            }}
>

### © 版本信息

- Ant Design Pro Table 版本: 2.4.0
- umi 版本 3.2.0
- 浏览器环境 Chrome
- 开发环境   mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/15145231/88777076-644acc80-d1b9-11ea-8c69-1c94337e6428.png)

**Comment by chenshuai2144** [comment]
架构修改，已经删除
