### ISSUE TITLE
🐛[BUG]pro-form 1.0.0-beta.26 中 switch 样式错误，date 相关的组件报警告

### ISSUE THREAD

**Issue by zhou0818** [ant-design/pro-components#530]
### 🐛 bug 描述

ProFormSwitch 样式错误，应该是新增的 width 导致的
![image](https://user-images.githubusercontent.com/25949890/93411423-bbbe0c80-f8cd-11ea-8a82-673e998dfb79.png)

ProFormDatePicker ProFormDateRangePicker 和日期相关的都会报警告
![image](https://user-images.githubusercontent.com/25949890/93411591-10618780-f8ce-11ea-9e5f-6b615fcc8330.png)

### 📷 复现步骤

直接使用文档的代码就能复现
```
<ProFormDatePicker name="date" label="日期" />
<ProFormSwitch name="switch" label="Switch" />
```

### 🏞 期望结果

修复bug

### © 版本信息

- "@ant-design/pro-form": "^1.0.0-beta.26"
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
@zhou0818  fix 了，等待发布好了

**Comment by chenshuai2144** [comment]
已发布
