### ISSUE TITLE
🐛[BUG] ProTable dateTime column UI失效

### ISSUE THREAD

**Issue by JennyLeung030** [ant-design/pro-components#5311]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

columns 是dateTime時,選擇時間的界面出bug, 它UI失效了
![image](https://user-images.githubusercontent.com/51438629/170910566-51fa908f-64d7-4f85-998b-b0cf54a4139c.png)

![image](https://user-images.githubusercontent.com/51438629/170910521-48b6e05e-5616-4262-bbb8-84cebb544059.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 3.5.0
- 浏览器环境 chrome
- 开发环境 Windows 10

**Comment by chenshuai2144** [comment]
删除下 .umi 然后重新安装一下
