### ISSUE TITLE
🐛[BUG] colProps在SchemaForm下无效

### ISSUE THREAD

**Issue by ldwonday** [ant-design/pro-components#5315]
https://codesandbox.io/s/schema-biao-dan-forked-7vc0lu?file=/App.tsx

期望配置了coProps后可以应用到每个column上

**Comment by ldwonday** [comment]
https://github.com/ant-design/pro-components/blob/981886d746b380f05ce1a7b904e02c7a13630e15/packages/form/src/BaseForm/BaseForm.tsx#L227

这行只处理了RowProps?

**Comment by chenshuai2144** [comment]
应该是故意的，你@一下作者看看。

**Comment by Dunqing** [comment]
是个bug
这个colProps应该是要传递到context中暴露给实际使用了ColWrapper的地方，但在这里传递到了useGridHelpers其实等于没作用

**Comment by ldwonday** [comment]
@Dunqing D流水线失败了

**Comment by Dunqing** [comment]
> @Dunqing 流水线失败了

有点忙，得晚上修一下
