### ISSUE TITLE
🐛[BUG]Schema Form内嵌模式下（Embed）dependencies表单联动失效

### ISSUE THREAD

**Issue by wuguanglin** [ant-design/pro-components#5316]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by wuguanglin** [comment]
复现地址： https://codesandbox.io/s/dawn-paper-5p005f?file=/src/App.js

**Comment by wuguanglin** [comment]
新的复现地址： https://codesandbox.io/s/schema-biao-dan-forked-4mi57j?file=/App.tsx

**Comment by wuguanglin** [comment]
> 新的复现地址： https://codesandbox.io/s/schema-biao-dan-forked-4mi57j?file=/App.tsx

@chenshuai2144

**Comment by chenshuai2144** [comment]
这个demo 好像生效了，

<img width="602" alt="image" src="https://user-images.githubusercontent.com/8186664/174001246-2e7fc33a-d933-4acb-b7ce-1c3a0ae884bc.png">

**Comment by wuguanglin** [comment]
> 这个demo 好像生效了，
> 
> <img alt="image" width="602" src="https://user-images.githubusercontent.com/8186664/174001246-2e7fc33a-d933-4acb-b7ce-1c3a0ae884bc.png">
![image](https://user-images.githubusercontent.com/56418832/174002178-d8d90c8b-2cad-4304-8a04-2f521b55654b.png)

**Comment by wuguanglin** [comment]
> 这个demo 好像生效了，
> 
> <img alt="image" width="602" src="https://user-images.githubusercontent.com/8186664/174001246-2e7fc33a-d933-4acb-b7ce-1c3a0ae884bc.png">

是这里没生效
![image](https://user-images.githubusercontent.com/56418832/174002333-7949a72b-0f61-48ac-96ac-0deac3ba2979.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，这个问题出现的原因是因为 `dependencies` 里的属性名需要使用 `$` 符号包裹起来，例如 `$visible` 而不是 `visible`，所以在你的 schema 中，需要把 `field1Dependent` 里的 `value` 属性改成 `$value`，如下：

```json
{
  "field1Dependent": {
    "type": "string",
    "title": "Field1 dependent",
    "enum": [
      "a",
      "b",
      "c"
    ],
    "enumNames": [
      "Option A",
      "Option B",
      "Option C"
    ],
    "dependencies": {
      "field1": {
        "oneOf": [
          {
            "properties": {
              "$value": {
                "const": "a"
              }
            }
          },
          {
            "properties": {
              "$value": {
                "enum": [
                  "b",
                  "c"
                ]
              }
            }
          }
        ]
      }
    }
  }
}
```

这样修改后就会生效了。

**Comment by chenshuai2144** [comment]
要升级到 2.0  才能生效的
