### ISSUE TITLE
👑 [需求] 增加 离开页面防止ProTable 自动刷新的 功能

### ISSUE THREAD

**Issue by CHENJKNB** [ant-design/pro-components#5319]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 ProTable

ProTable

### 🥰 需求描述

ProTable 只要离开该页面 ，就会自动刷新。现在需要增加可以控制自动刷新的 属性。

### ⛰ 功能需求适用场景

ProTable 在新增数据 弹出 Model 的时候，我离开页面去复制数据，重新进来就会刷新页面。这个时候很影响操作。

**Comment by chenshuai2144** [comment]
看看issue，已经默认关了

**Comment by lcc908** [comment]
> 查看问题，已经默认关闭了

哪个issue？我看现在有这种问题

**Comment by Oliver-GMJ** [comment]
> 看看issue，已经默认关了
https://procomponents.ant.design/components/table?current=1&pageSize=5#api
![image](https://user-images.githubusercontent.com/20814213/172143408-a38f2a70-aee8-442f-8ae7-5d74dd120852.png)
文档里面是true的
