### ISSUE TITLE
🧐[问题]proTable的columns属性中，当ellipsis为true而没有写width，鼠标悬浮偶尔不会出现tooltip的问题

### ISSUE THREAD

**Issue by GloriaJiang12** [ant-design/pro-components#5322]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
"@ant-design/pro-table": "^2.34.4"
这个proTable是写在一个弹窗上的。
proTable的columns数组中每个item数据如下：
   {
      title: '物品编号',
      dataIndex: 'number',
      ellipsis: true,
    }
鼠标悬浮到某一行的物品编号，大多数会在鼠标上方出现tooltip显示完整内容。但是存在个别无法出现tooltip。之后给有ellipsis属性的加上width，就不会出现没有tooltip的情况了。表示很疑惑为什么？？

正常出现如下图：
![image](https://user-images.githubusercontent.com/50451944/171146366-e9443519-947e-4cb1-890e-a0343a27bc60.png)
异常情况如下图：
![image](https://user-images.githubusercontent.com/50451944/171146805-20ee06d1-11c1-4be8-8666-b89c1a89c6e5.png)

图示绿色选中的部分为鼠标悬浮位置

**Comment by chenshuai2144** [comment]
width 还是要写的，不然 td的宽度会跟随内容一直变化，性能也不好
