### ISSUE TITLE
🐛[BUG] pro-form validateField 后, 部分场景失效

### ISSUE THREAD

**Issue by Mider0325** [ant-design/pro-components#5325]
### 🐛 bug 描述
pro-form:"@ant-design/pro-form": "1.65.0",

pro-form validateField 后, 部分场景错误不提醒

### 📷 复现步骤
1. pro-form 使用grid 布局
2. 主动调用 validateField() 方便, 并在 catch callback 中随意setState 
3. form-item 使用colsprops 属性 就生效, 不使用就正常提示

### 🏞 期望结果
正常提示错误

### 💻 复现代码

``
import {
  ProForm,
  ProFormDatePicker,
  ProFormDateRangePicker,
  ProFormDigit,
  ProFormSelect,
  ProFormText,
  ProFormTextArea
} from "@ant-design/pro-form";
import { Col, message, Row, Space } from "antd";
import type { FormLayout } from "antd/lib/form/Form";
import React, { useState, useRef } from "react";

const LAYOUT_TYPE_HORIZONTAL = "horizontal";

const waitTime = (time: number = 100) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(true);
    }, time);
  });
};

export default () => {
  const [formLayoutType, setFormLayoutType] = useState(false);

  const formRef = useRef();

  const [formValue, setFormValue] = useState("");

  const handleValuesChange = (_, values) => {
    setFormValue(values);
  };
  const submit = async () => {
    try {
      await formRef.current?.validateFields();
    } catch (err) {
      setFormLayoutType(!formLayoutType);
      console.log(err, "err----");
    }
  };

  return (
    <span>
      <button onClick={submit}>test</button>
      <ProForm<{
        name: string;
        company?: string;
        useMode?: string;
      }>
        submitter={false}
        onValuesChange={handleValuesChange}
        formRef={formRef}
        /// <reference path="" />

        // layout={formLayoutType}
        grid={true}
        onFinish={async (values) => {
          await waitTime(2000);
          console.log(values);
          message.success("提交成功");
        }}
        params={{}}
        request={async () => {
          await waitTime(100);
          return {
            name: "蚂蚁设计有限公司",
            useMode: "chapter"
          };
        }}
      >
        <ProFormText
          colProps={{ xl: 8, md: 12 }}
          name="name"
          label="标题"
          tooltip="最长为 24 位"
          placeholder="请输入名称"
        />
        <ProFormText
          colProps={{
            span: 12
          }}
          rules={[
            { required: true, message: "请输入任务名称" },
            { max: 10, message: "任务名称长度不能超过10" }
          ]}
          name="company"
          label="姓名"
        />
        <ProFormDigit colProps={{ md: 12, xl: 8 }} name="phone" label="电话" />
        <ProFormText colProps={{ md: 12, xl: 8 }} name="email" label="邮箱" />
        <ProFormTextArea
          name="address"
          label="详细的工作地址或家庭住址"
          rules={[
            { required: true, message: "请输入任务名称" },
            { max: 10, message: "任务名称长度不能超过10" }
          ]}
        />
        <ProFormDatePicker
          colProps={{ xl: 8, md: 12 }}
          label="入职日期"
          name="date"
        />
        <ProFormDateRangePicker
          colProps={{ xl: 8, md: 12 }}
          label="工作周期"
          name="dateRange"
        />
        <ProFormSelect
          colProps={{ xl: 8, md: 12 }}
          label="职位"
          name="level"
          valueEnum={{
            1: "front end",
            2: "back end",
            3: "full stack"
          }}
        />
      </ProForm>
    </span>
  );
};

``
https://codesandbox.io/s/zha-ge-hua-bu-ju-forked-7h0igq?file=/App.tsx:0-2992

### © 版本信息

- pro-form:"@ant-design/pro-form": "1.65.0",
- umi 版本
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据用户提供的代码可以看到，出现错误的场景是当 form-item 使用 colsProps 属性时，并且通过主动调用 validateField() 触发校验，校验出错后无法正常提示错误信息。

首先需要明确 validateField() 方法只会返回一个 Promise 对象，并不会自动校验表单项的值，需要手动调用这个方法进行校验。所以根据代码来看，如果在 formRef.current?.validateFields() 出现校验错误时，手动调用 setFormLayoutType(!formLayoutType); 只会导致表单的布局改变，而并没有影响校验的结果。

那么正确的做法应该是在 Promise 对象的 catch() 回调中处理校验错误的情况，例如使用 message.error() 方法进行提示。

下面是修改后的代码示例：


```
import {
  ProForm,
  ProFormDatePicker,
  ProFormDateRangePicker,
  ProFormDigit,
  ProFormSelect,
  ProFormText,
  ProFormTextArea
} from '@ant-design/pro-form';
import { message } from 'antd';
import React, { useRef } from 'react';

const waitTime = (time: number = 100) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(true);
    }, time);
  });
};

export default function App() {
  const formRef = useRef();

  const handleValuesChange = (_, values) => {
    console.log('values:', values);
  };

  const submit = async () => {
    try {
      await formRef.current?.validateFields();
    } catch (err) {
      console.log(err, 'err----');
      message.error(err.message);
    }
  };

  return (
    <ProForm
      submitter={false}
      onValuesChange={handleValuesChange}
      formRef={formRef}
      grid={true}
      onFinish={async (values) => {
        console.log(values);
        message.success('提交成功');
      }}
      params={{}}
      request={async () => {
        await waitTime(100);
        return {
          name: '蚂蚁设计有限公司',
          useMode: 'chapter'
        };
      }}
    >
      <ProFormText
        colProps={{ xl: 8, md: 12 }}
        name="name"
        label="标题"
        tooltip="最长为 24 位"
        placeholder="请输入名称"
      />
      <ProFormText
        colProps={{
          span: 12
        }}
        rules={[
          { required: true, message: '请输入任务名称' },
          { max: 10, message: '任务名称长度不能超过10' }
        ]}
        name="company"
        label="姓名"
      />
      <ProFormDigit colProps={{ md: 12, xl: 8 }} name="phone" label="电话" />
      <ProFormText colProps={{ md: 12, xl: 8 }} name="email" label="邮箱" />
      <ProFormTextArea
        name="address"
        label="详细的工作地址或家庭住址"
        rules={[
          { required: true, message: '请输入任务名称' },
          { max: 10, message: '任务名称长度不能超过10' }
        ]}
      />
      <ProFormDatePicker
        colProps={{ xl: 8, md: 12 }}
        label="入职日期"
        name="date"
      />
      <ProFormDateRangePicker
        colProps={{ xl: 8, md: 12 }}
        label="工作周期"
        name="dateRange"
      />
      <ProFormSelect
        colProps={{ xl: 8, md: 12 }}
        label="职位"
        name="level"
        valueEnum={{
          1: 'front end',
          2: 'back end',
          3: 'full stack'
        }}
      />
    </ProForm>
    <button onClick={submit}>test</button>
  );
};

``` 

具体的修改内容是在 submit() 函数中，在 catch() 回调中使用 message.error() 方法进行提示。在操作按钮处增加了一行代码，用于触发表单校验，代码如下：
<button onClick={submit}>test</button> 

另外，也没有必要在 catch() 回调中手动修改表单的布局。

希望这个解决方案能够帮助用户解决问题，如果还有其它问题可以继续讨论。

**Comment by chenshuai2144** [comment]
记得给组件增加一个  25  的高度出来，不然会被压制掉的。
