### ISSUE TITLE
动态表单项触发外部验证不通过子组件输入框也为错误状态

### ISSUE THREAD

**Issue by zzperfect** [ant-design/pro-components#5327]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
动态表单项触发外部验证不通过后子组件输入框为红色

在动态表单项中自定义valueType，这个控件可以打开一个弹出框，并且弹出框内有表格，表格支持toolbar中的search，
当验证动态表单不通过为红色后，在验证不通过状态下打开模态框，模态框中表格输入框也为红色
### 💻 示例代码

https://codesandbox.io/s/cha-xun-biao-ge-forked-rqru3p?file=/App.tsx

### 🚑 其他信息

<img width="825" alt="image" src="https://user-images.githubusercontent.com/33208512/171177054-d744ad13-db70-4e96-bb1e-154ee1bffe2c.png">
<img width="834" alt="image" src="https://user-images.githubusercontent.com/33208512/171177098-fcf61e76-ed61-4bd4-b766-6680df4ce007.png">

**Comment by chenshuai2144** [comment]
这个问题始料未及，试试antd的版本升级一下。

因为这个是用className实现的，会影响子节点

**Comment by zzperfect** [comment]
已升级最新版antd，还是会影响到子节点，暂时只能先规避触发校验来解决这个问题

**Comment by zzperfect** [comment]
> 这个问题始料未及，试试antd的版本升级一下。
> 
> 因为这个是用className实现的，会影响子节点

麻烦问下，这个问题后续你们会跟进吗？

**Comment by drizzlesconsin** [comment]
这个应该是 antd 的问题，好像跟之前提的一个[问题](https://github.com/ant-design/ant-design/issues/35360)类似，都是用了 `useContext`

可以先用样式去掉错误样式

**Comment by WuJiY** [comment]
是有这个问题

**Comment by wangxin305** [comment]
`toolbar={{
                search: {
                  status: " ",
                  onSearch: (value) => {
                    console.log(value);
                  }
                }
              }}`

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


是的，这个问题可能是 antd 内部实现的一个 bug，可以先用样式去掉错误样式，或者规避触发校验来解决这个问题。一旦官方修复了这个问题，就可以恢复正常的校验流程，去掉规避部分的代码即可。
