### ISSUE TITLE
🐛[BUG] ProList 卡片列表头像的HTML结构可能不合理

### ISSUE THREAD

**Issue by drizzlesconsin** [ant-design/pro-components#5332]
### 🐛 bug 描述

[官网DEMO Card List](https://procomponents.ant.design/en-US/components/list#card-list)

### 📷 复现步骤

<img width="859" alt="image" src="https://user-images.githubusercontent.com/69514654/171364021-0e1918c2-89f9-46aa-949c-f46923891f5c.png">

### 🏞 期望结果

影响到自定义图片大小

### 💻 复现代码

官网 F12

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 
- 浏览器环境 Chrome
- 开发环境 Mac OS

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常感谢您的反馈，我了解到你在使用 Ant Design Pro 组件库的 `ProList` 组件时，发现在自定义卡片列表中的头像时，有问题影响到自定义图片大小。

经过我的检查，发现该问题主要是因为 `ProList` 组件的头像是使用 `Avatar` 组件实现的，而 `Avatar` 组件默认的 HTML 结构使用了一个固定大小的 div 元素包裹 img 元素，且不能自由调整尺寸，因此导致你不能够自由指定图片大小。

针对此问题，建议你可以使用 `Avatar` 组件提供的 `size` 属性来指定头像的尺寸，例如：

```jsx
<ProList.Item
  avatar={{
    src: 'https://cdn.pixabay.com/photo/2015/04/19/13/10/margarita-729510__340.jpg',
    size: 48, // 指定头像尺寸为 48
  }}
  ...
/>
```

或者你也可以自定义 Avatar，将其 HTML 结构通过 CSS 自行调整，达到自由指定图片大小的效果，如下所示：

```jsx
<ProList.Item
  avatar={
    <div className="custom-avatar">
      <img src="https://cdn.pixabay.com/photo/2015/04/19/13/10/margarita-729510__340.jpg" />
    </div>
  }
  ...
/>

// 在 CSS 中加入如下样式：
.custom-avatar {
  width: 48px;
  height: 48px;
  border-radius: 50%;
  overflow: hidden;
}
.custom-avatar img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
```

希望我的解答能够帮助到你，如果你还有任何问题，欢迎随时回复。另外，我们也欢迎你在 Ant Design Pro 的 Github Issue 中提出你的问题，我们会及时回复和解决。
