### ISSUE TITLE
🐛[BUG] Uncaught TypeError: Cannot read properties of null (reading 'match')

### ISSUE THREAD

**Issue by jiawen4760256** [ant-design/pro-components#5333]
新建项目 （npx create-react-app my-app --template typescript）使用 ProLayout 组件，代码是官网的demo code，切换导航样式后，点击菜单必报错。package.json 、报错信息和代码如下图：
![image](https://user-images.githubusercontent.com/100251578/171783896-7f1f5954-b27e-4649-b8e1-524925fae83e.png)
![image](https://user-images.githubusercontent.com/100251578/171784036-5515a6ef-a3c0-4a3d-86ad-6d8b1beb5043.png)
![image](https://user-images.githubusercontent.com/100251578/171784389-44bf0bff-d27c-417d-a550-7cf95ce03aef.png)
![image](https://user-images.githubusercontent.com/100251578/171784430-18457fe4-7e07-4ea7-9043-2bf78057f51d.png)

**Comment by chenshuai2144** [comment]
路有数据没有给吐进去吧，仓库给我下
