### ISSUE TITLE
🧐ProForm提交表单前未进入到onFinish方法

### ISSUE THREAD

**Issue by colorbeach** [ant-design/pro-components#5334]
### 🧐 问题描述

麻烦看下实例代码里render中的2个button操作。

以前一直是用方式1，button的htmlType类型设定为submit，在点击之后，会自动进入到ModalForm的onFinish方法。

某次小改动发布之后，方式一行不通了，点击按钮无法再进入到onFinish，而必须采用方式二显式地调用submit方法才行。package.json里依赖版本是采用^的写法，但是现在将代码回退到老版本（同时将yarn.lock回退），也是无法正常用方式1。

想请问的是，方式1这种写法是合理的吗，还是说可能是由我本地环境(比如说node环境)或者ProForm版本变动引起的？

谢谢！

### 💻 示例代码
```
<ModalForm
            trigger={...}
            onFinish={async (values) => {...}}
            submitter={{
                render: (props) => [
                    <Button htmlType="submit" loading={buttonLoading} onClick={() => {
                              // some code
                                        }}>方式1</Button>,

                    <Button loading={buttonLoading} onClick={() => {
                              // some code
                             props.form?.submit?.();
                                        }}>方式2</Button>,
                ]
            }}
        >
```

**Comment by wangmeijian** [comment]
代码乱了

**Comment by chenshuai2144** [comment]
ModalForm 的 button 不在form里面在modal上面所以不生效了，用第二种吧

**Comment by colorbeach** [comment]
> ModalForm 的 button 不在form里面在modal上面所以不生效了，用第二种吧

感谢回复。现在已经用第二种方式。

就是想知道一下，第一种方式失效是因为版本变化导致的吗，还是说原先那样用就是不合理的

**Comment by chenshuai2144** [comment]
> 就是想知道一下，第一种方式失效是因为版本变化导致的吗，还是说原先那样用就是不合理的


实现方式变化了，算是使用了未声明的API
