### ISSUE TITLE
🐛[BUG] ProFormText 组件 addonAfter 样式问题

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#5336]
<img width="881" alt="image" src="https://user-images.githubusercontent.com/30397655/172042806-eab2f891-6363-4f42-b625-f92f514f12c1.png">

**Comment by leshalv** [comment]
@chenshuai2144

**Comment by Sharklegs** [comment]
同问

**Comment by chenmeiling1997** [comment]
同问+1

**Comment by leshalv** [comment]
https://github.com/ant-design/pro-components/issues/5406

**Comment by leshalv** [comment]
这个BUG没有修复吧？ @chenshuai2144

**Comment by chenshuai2144** [comment]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/8186664/177100228-0385280a-6b73-45f8-a9e2-402c039fef38.png">

不是你提了一个pr吗？

**Comment by chenshuai2144** [comment]
7cb9362cf - fix(form): fix the abnormal width caused by addonAfter and addonB… (#5417) (4 天前) <王美建>

是这个

**Comment by leshalv** [comment]
FormItem 可以用了，但是ProFormText 还是不行呀。
<img width="932" alt="image"  @src="https://user-images.githubusercontent.com/30397655/177101030-c8ab1170-aa0c-461b-af28-a0332f29ca19.png">
@chenshuai2144

**Comment by chenshuai2144** [comment]
来个pr搞下？

**Comment by leshalv** [comment]
> 来个pr搞下？

弄不了呀，干后端的。。。
