### ISSUE TITLE
🐛[BUG]ProFormList嵌套两层以上，自带的action中的setCurrentRowData的方法不生效，设置不上去

### ISSUE THREAD

**Issue by liudiming** [ant-design/pro-components#5340]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/67784740/172286825-049140e3-f03f-436a-af40-e58a4a73b707.png)

### 💻 复现代码
`<>
      <Button>收集数据</Button>
      <ProForm>
        <ProFormList
          name={"firstFilter"}
        >
          {(field, index, action) => {
            return <>
              <Button onClick={() => {
                action.setCurrentRowData({firstSelect: ['first', 'second'], secondSelect: ['first', 'second']})
              }}>设置first值</Button>
              <ProFormSelect mode='tags' name={"firstSelect"}/>
              <ProFormSelect mode='tags' name={"secondSelect"}/>
              <ProFormList name={"secondFilter"}>
                {(f, i, a) => {
                  return <>
                    <Button onClick={() => {
                      a.setCurrentRowData({threeSelect: ['first', 'second'], fourSelect: ['first', 'second']})
                    }}>设置second值</Button>
                    <ProFormSelect mode='tags' name={"threeSelect"}/>
                    <ProFormSelect mode='tags' name={"fourSelect"}/>
                  </>
                }}
              </ProFormList>
            </>
          }}
        </ProFormList>
      </ProForm>
    </>`

### © 版本信息

- @ant-design/pro-form版本: [1.69.0]
- umi 版本: 3.5.25
- 浏览器环境
- 开发环境 [windows10]

**Comment by chenshuai2144** [comment]
在这里看吧 https://github.com/ant-design/pro-components/issues/5415
