### ISSUE TITLE
🧐[问题] pro-table筛选所有的筛选项，再依次取消，筛选显示错误

### ISSUE THREAD

**Issue by earthaYan** [ant-design/pro-components#5343]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

表格筛选所有的筛选项，再依次取消，当删除完最后一个筛选项的时候，筛选图标变成筛选状态，且再点击排序按钮或者选中其中一个筛选条件的时候，之前清空的redux数据恢复，筛选条件恢复到全选的状态

### 💻 示例代码
[示例代码](https://codesandbox.io/s/table-filter-2bkrts)
[仓库地址](https://github.com/earthaYan/test_demo)

### 🚑 其他信息

正常筛选全部：
![dkfz4q77Ee](https://user-images.githubusercontent.com/25888900/172518725-88fdb3d1-b907-401e-a24f-689140495d70.png)
删除其中任意一个筛选条件：
![waQdI35iV3](https://user-images.githubusercontent.com/25888900/172518871-c3d67097-f089-44f6-916e-7b8bb0a11deb.png)
删除最后一个删除条件，预期此时应该是非筛选状态，但是实际上显示的是筛选状态：
![8UFI1dSRBI](https://user-images.githubusercontent.com/25888900/172519135-79f092c1-f581-4e13-a7fb-92c745d8324a.jpg)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


针对这个问题，可以尝试在删除最后一个删除条件后手动触发一次表格的筛选和重置操作，来使表格处于正确的状态。

修改代码如下：

```jsx
const onFilterChange = (fil: any, record: any) => {
  setFilter(fil);
  // 在筛选条件为空时手动触发一次重置操作
  if (Object.keys(fil).length === 0) {
    tableRef.current?.reset();
    tableRef.current?.reload();
  }
};

const onReset = () => {
  setFilter({});
};

/* 在删除最后一个删除条件后手动触发一次筛选和重置操作 */
const onCancel = () => {
  setSelectedRows([]);
  setSelectedRowKeys([]);
  onReset(); // 先重置
  tableRef.current?.reload(); // 再筛选
};
```

具体地，我们在 `onFilterChange` 函数中，对筛选条件为空的情况手动触发了一次表格的重置操作。在 `onCancel` 函数中，我们在清空选中行的同时，调用 `onReset` 函数进行表单重置，然后再手动调用表格的重载操作 `tableRef.current?.reload()` 进行筛选操作即可。

更多详细信息和使用方法可以参考 pro-table 的官方文档：

- pro-table: https://procomponents.ant.design/components/table/#API

建议在阅读文档时结合代码实现来更好地理解和掌握组件的使用方法。
