### ISSUE TITLE
ProTable

### ISSUE THREAD

**Issue by lovesL** [ant-design/pro-components#5348]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
问题一
![image](https://user-images.githubusercontent.com/27960630/172551875-f58d96be-6a91-4217-b729-411f0246781e.png)
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/27960630/172551933-328d43fe-c695-4df0-938f-0526f028bd84.png">

问题二

![image](https://user-images.githubusercontent.com/27960630/172552188-27a24def-33da-43d1-bdc5-1ef5734e9297.png)
这个批量操作有没有什么API控制checkbox  显示隐藏

### 🚑 其他信息
"@ant-design/pro-table": "^2.71.0",

**Comment by chenshuai2144** [comment]
好好写标题
