### ISSUE TITLE
🧐[问题] ProTable分页pagination设置和行合并rowSpan导致表格显示条数不符合预期

### ISSUE THREAD

**Issue by xinxinziloveqingqingzi** [ant-design/pro-components#5349]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

1. 需求：列表包含分页，并且分页条数按根据rowSpan合并后显示的条数进行分页
2. 实现：根据数据中的`rowSpan`合并某些行，数据返回的每页条数可能大于设置的默认每页记录数`defaultPageSize`
3. 问题：最终页面只会显示`defaultPageSize`所设置的条数，而不是合并显示后的条数，如下图
    [![Xr46RH.png](https://s1.ax1x.com/2022/06/08/Xr46RH.png)](https://imgtu.com/i/Xr46RH)
预期本应该显示两条记录，包含三个版本

### 💻 示例代码

```typescript
import React from "react";
import ProTable, { ProColumns } from "@ant-design/pro-table";

async function getApplicationList() {
  try {
    let temp = [
      {
        dataAppId: "1",
        rowSpan: 2,
        name: "001",
        version: "1.0.0",
      },
      {
        dataAppId: "1",
        rowSpan: 0,
        name: "001",
        version: "2.0.0",
      },
      {
        dataAppId: "2",
        rowSpan: 1,
        name: "002",
        version: "1.0.0",
      },
    ];
    return {
      data: temp,
      total: 4,
    };
  } catch (e) {
    return { data: [], total: 0 };
  }
}

export default () => {
  const columns: ProColumns[] = [
    {
      title: "应用ID",
      dataIndex: "dataAppId",
      width: 150,
      ellipsis: true,
      search: false,
      render: (dom, entity) => {
        return {
          children: dom,
          props: {
            rowSpan: entity.rowSpan,
          },
        };
      },
    },
    {
      title: "名称",
      dataIndex: "name",
      ellipsis: true,
      render: (dom, entity) => {
        return {
          children: dom,
          props: {
            rowSpan: entity.rowSpan,
          },
        };
      },
    },
    {
      title: "版本号",
      dataIndex: "version",
      width: 100,
      search: false,
    },
  ];

  return (
    <ProTable
      pagination={{ pageSize: 2 }}
      columns={columns}
      request={async () => {
        return await getApplicationList();
      }}
      bordered
    />
  );
};
```

**Comment by chenshuai2144** [comment]
是符合预期的，table 就是这么设计的。

**Comment by zhaohongyan** [comment]
我也遇到了同样的问题，请问是怎么解决的？

**Comment by xinxinzi-WFqing** [comment]
> 我也遇到了同样的问题，请问是怎么解决的？

没有解决，不合并行了，分成两部分展示

**Comment by zhaohongyan** [comment]
> > 我也遇到了同样的问题，请问是怎么解决的？
> 
> 没有解决，不合并行了，分成两部分展示

我在网上找到解决办法了，通过改变样式，column设置了className，搭配render函数渲染结果加className就可以搞定了

**Comment by ZivvW** [comment]
> > > 我也遇到了同样的问题，请问是怎么解决的？
> > 
> > 
> > 没有解决，不合并行了，分成两部分展示
> 
> 我在网上找到解决办法了，通过改变样式，column设置了className，搭配render函数渲染结果加className就可以搞定了

@zhaohongyan  您好，我也遇到这个问题了，没太理解这个解决办法。可以发下找到这个解决方法的网址吗

**Comment by zhaohongyan** [comment]
> 理解
我写了一个demo,你可以参考下。
https://stackblitz.com/edit/react-ezsiuo?file=demo.tsx

**Comment by zhaohongyan** [comment]
> > > > 我也遇到了同样的问题，请问是怎么解决的？
> > > 
> > > 
> > > 没有解决，不合并行了，分成两部分展示
> > 
> > 
> > 我在网上找到解决办法了，通过改变样式，column设置了className，搭配render函数渲染结果加className就可以搞定了
> 
> @zhaohongyan 您好，我也遇到这个问题了，没太理解这个解决办法。可以发下找到这个解决方法的网址吗

我写了一个demo,你可以参考下。
https://stackblitz.com/edit/react-ezsiuo?file=demo.tsx

**Comment by ZivvW** [comment]
> > > > > 我也遇到了同样的问题，请问是怎么解决的？
> > > > 
> > > > 
> > > > 没有解决，不合并行了，分成两部分展示
> > > 
> > > 
> > > 我在网上找到解决办法了，通过改变样式，column设置了className，搭配render函数渲染结果加className就可以搞定了
> > 
> > 
> > @zhaohongyan 您好，我也遇到这个问题了，没太理解这个解决办法。可以发下找到这个解决方法的网址吗
> 
> 我写了一个demo,你可以参考下。 https://stackblitz.com/edit/react-ezsiuo?file=demo.tsx

感谢您的回复。
理解了，这种方式是放弃了 antd 的合并功能，通过 css 模拟了行合并的效果。
我后来是把 Table 的 pagination 设为 null ，下面另外加了个 Pagination 组件去解决这个问题。
