### ISSUE TITLE
🧐[问题] 求助，引入组件，浏览器报错cannot use import statement outside a module

### ISSUE THREAD

**Issue by bigbigmyworld** [ant-design/pro-components#5350]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/22515433/172574832-b0df26d3-602c-406c-b56e-13f015e5e6e9.png)
![image](https://user-images.githubusercontent.com/22515433/172574979-39cc5a28-f9f9-4673-ad92-3d1dc4310970.png)

**Comment by chenshuai2144** [comment]
是不是在浏览器里加载node模块了。有些年没看到这种报错了。
