### ISSUE TITLE
EditableProTable 使用ProForm的name属性时导致删除异常🐛[BUG]

### ISSUE THREAD

**Issue by Cooolyu** [ant-design/pro-components#5353]
### 🐛 bug 描述
在ProForm下使用EditableProTable并添加name属性，导致删除时顺序错乱或最后1行无法删除，如截图所示：删除1后，再删除2，则组件会去删除3所在行，且最后的2无法删除；
注释掉   name={'table'} 则操作正常！

### 💻 复现代码
```
import React, {useRef, useState} from 'react';
import {ActionType, EditableFormInstance, EditableProTable, ProColumns} from "@ant-design/pro-table";
import ProForm from "@ant-design/pro-form";
import ProFormItem from "@ant-design/pro-form/es/components/FormItem";



const default
() => {

    const [editableKeys, setEditableRowKeys] = useState<React.Key[]>([]);
    const [position, setPosition] = useState<'top' | 'bottom' | 'hidden'>('bottom');
    const editableActionRef = useRef<ActionType>();
    const editableFormRef = useRef<EditableFormInstance>();

    const columns: ProColumns[] = [
        {
            title: '活动名称',
            dataIndex: 'title',
            tooltip: '只读，使用form.getFieldValue获取不到值',
            formItemProps: (form, {rowIndex}) => {
                return {
                    rules: rowIndex > 1 ? [{required: true, message: '此项为必填项'}] : [],
                };
            },
            width: '15%',
        },
        {
            title: '活动名称二',
            dataIndex: 'readonly',
            tooltip: '只读，使用form.getFieldValue可以获取到值',
            readonly: true,
            width: '15%',
        },
        {
            title: '状态',
            dataIndex: 'state',
            valueType: 'select',
            valueEnum: {
                all: {text: '全部', status: 'Default'},
                open: {
                    text: '未解决',
                    status: 'Error',
                },
                closed: {
                    text: '已解决',
                    status: 'Success',
                },
            },
        },
        {
            title: '描述',
            dataIndex: 'decs',
            fieldProps: (from, {rowKey, rowIndex}) => {
                if (from.getFieldValue([rowKey || '', 'title']) === '不好玩') {
                    return {
                        disabled: true,
                    };
                }
                if (rowIndex > 9) {
                    return {
                        disabled: true,
                    };
                }
                return {};
            },
        },
        {
            title: '变量解释',
            dataIndex: 'description',
            valueType: 'text',
            width: '20%',
        },
        {
            title: '操作',
            valueType: 'option',
            width: 200,
        },
    ];

    return (
        <>
            <ProForm formRef={editableFormRef}>
                <ProFormItem>
                    <EditableProTable
                        name={'table'}
                        rowKey="id"
                        actionRef={editableActionRef}
                        formRef={editableFormRef}
                        headerTitle="可编辑表格"
                        recordCreatorProps={{
                            position: position as 'top',
                            newRecordType: 'dataSource',
                            record: () => ({id: (Math.random() * 1000000).toFixed(0)}),
                        }}
                        loading={false}
                        columns={columns}
                        editable={{
                            type: 'multiple',
                            editableKeys,
                            onChange: setEditableRowKeys,
                            actionRender: (row, config, defaultDom) => {
                                return [defaultDom.delete];
                            },
                        }}
                    />
                </ProFormItem>
            </ProForm>
        </>
    );
};
```

### © 版本信息
    "@ant-design/pro-form": "^1.69.3",
    "@ant-design/pro-table": "^2.76.3",

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/16718459/172689773-19433cde-be2d-4bba-ba9c-7c0a52f6985f.png)

**Comment by Mzhang1994** [comment]
![image](https://user-images.githubusercontent.com/69185609/172980591-c6a09aa5-d284-46c8-8cb2-eae42cd0101b.png)
自己对比一下，看少了啥。

**Comment by Cooolyu** [comment]
@Mzhang1994 把value、onChange、onValuesChange方法加上后问题还是会出现

**Comment by Mzhang1994** [comment]
你没必要写name属性，除非你要单独写删除的功能。
![image](https://user-images.githubusercontent.com/69185609/173022027-c3e9faf5-f051-4a73-bb19-f635c3980d65.png)

**Comment by Cooolyu** [comment]
我这边需要表格里的两列select进行联动，目前看必须要加name才能生效，另外重写delete方法时行删除和添加依然有这个问题

**Comment by chen-jianpeng** [comment]
与 FormItem 配合使用的时候，我这里删除功能也是有问题，会乱。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题是由于 `EditableProTable` 的删除功能在删除时是依靠 `rowKey` 来进行查找的，而在配合 `ProForm` 使用时，添加了 `name` 属性后，会给每一行数据的 `rowKey` 加上一个前缀，导致删除时出现了找不到对应的 `rowKey` 的问题。

解决办法是在传入 `EditableProTable` 的 `rowKey` 中加上前缀即可。前缀的值可以通过 `ProForm` 的 `name` 属性获取，代码示例如下：

```typescript
const [form] = Form.useForm();
const name = 'table';
const [prefix, setPrefix] = useState<string>('');

useEffect(() => {
  setPrefix(form.getFieldName([name]));
}, [form, name]);

const columns: ProColumns[] = [
  {
    title: '姓名',
    dataIndex: 'name',
    formItemProps: {
      rules: [{ required: true }],
    },
  },
  {
    title: '电话号码',
    dataIndex: 'phone',
    formItemProps: {
      rules: [{ required: true }],
    },
  },
  {
    title: '操作',
    valueType: 'option',
    width: 200,
    render: (text, record, _, action) => [
      <a
        key="editable"
        onClick={() => {
          action.startEditable?.(record.id);
        }}
      >
        编辑
      </a>,
      <a
        key="delete"
        onClick={() => {
          action?.cancelEditable?.(record.id);
          const newData = dataSource.filter((item) => item.id !== record.id);
          setDataSource(newData);
        }}
      >
        删除
      </a>,
    ],
  },
];

return (
  <ProForm form={form}>
    <EditableProTable
      rowKey={(record) => `${prefix}-${record.id}`}
      recordCreatorProps={{
        newRecordType: 'dataSource',
      }}
      columns={columns}
      dataSource={dataSource}
      editable={{
        onChange: setDataSource,
      }}
    />
  </ProForm>
);
```

在这个示例里，我们通过 `form.getFieldName([name])` 获取到了 `name` 属性的前缀，然后在 `rowKey` 中加上了这个前缀，在删除时就不会再出现问题。

希望这个解决办法可以解决你的问题。

**Comment by canqi0** [comment]
我也遇到了这个问题 绑定name时 操作更新表格数据 设置了必填的列数据会丢失
看日志触发了两次渲染 第一次还有数据 第二次就没了
`
import type { ProColumns } from '@ant-design/pro-table';
import { EditableProTable } from '@ant-design/pro-table';
import { hooks } from '@wove/react';
import { Button, Form } from 'antd';
import { nanoid } from 'nanoid';
import React, { useEffect } from 'react';

type DataSourceType = {
  key: React.Key;
  title?: string;
  type?: number;
};

const initialValues: { editableData: DataSourceType[] } = {
  editableData: [
    {
      key: nanoid(),
      title: '活动名称1',
      type: 1,
    },
  ],
};

export const TableDemo = () => {
  const [form] = Form.useForm<{ editableData: DataSourceType[] }>();

  // 全表可编辑
  const editableKeys = Form.useWatch('editableData', form)?.map((item) => item.key);

  useEffect(() => {
    form.setFieldsValue(initialValues);
  }, []);

  // 上移
  const onUpClick = hooks.useCallbackRef((index) => {
    const oldEditableData = form.getFieldValue('editableData');
    const editableData = [...oldEditableData];
    editableData[index] = editableData.splice(index - 1, 1, editableData[index])[0];
  // 数据存在
    form.setFieldValue('editableData', editableData);
  });

  // 下移
  const onDownClick = hooks.useCallbackRef((index) => {
    const oldEditableData = form.getFieldValue('editableData');
    const editableData = [...oldEditableData];
    editableData[index] = editableData.splice(index + 1, 1, editableData[index])[0];
    form.setFieldValue('editableData', editableData);
  });

  const columns: ProColumns<DataSourceType>[] = [
    {
      title: '活动名称',
      dataIndex: 'title',
      // 必填校验 该列丢失
      formItemProps: {
        rules: [{ required: true, message: '请输入!' }],
      },
    },
    {
      title: '活动类型',
      dataIndex: 'type',
      valueType: 'select',
      fieldProps: {
        options: [
          { value: 1, label: '类型1' },
          { value: 2, label: '类型2' },
        ],
      },
    },
    {
      title: '操作',
      valueType: 'option',
      render: () => {
        return null;
      },
    },
  ];

  return (
    <Form form={form}>
      <EditableProTable<DataSourceType>
        headerTitle="可编辑表格"
        columns={columns}
        scroll={{ x: 'max-content' }}
        rowKey="key"
        name="editableData" 
        recordCreatorProps={{
          record: {
            key: nanoid(), 
          },
        }}
        editable={{
          type: 'multiple',
          editableKeys,
          // 操作
          actionRender: (row, config, defaultDoms) => {
            console.log(row, config);
            return [
              <Button
                type="link"
                style={{ padding: 0 }}
                disabled={config.index == 0}
                onClick={onUpClick.bind(null, config.index)}
              >
                上移
              </Button>,
              <Button
                type="link"
                style={{ padding: 0 }}
                disabled={config.index == editableKeys.length - 1}
                size="small"
                onClick={onDownClick.bind(null, config.index)}
              >
                下移
              </Button>,
              defaultDoms.delete,
            ];
          },
        }}
      />
    </Form>
  );
}
`
完整demo https://www.jianshu.com/p/a58bd3a744a5 
日志
<img width="717" alt="image" src="https://github.com/ant-design/pro-components/assets/89558157/d38a7e20-9d47-463c-91f7-367f0afe7d2d">

**Comment by chenshuai2144** [comment]
已经修复了，是保留删除数据导致的
