### ISSUE TITLE
🧐[问题] StepsForm onFinish 怎么能拿到Form中没使用的字段

### ISSUE THREAD

**Issue by hreochen** [ant-design/pro-components#5355]

**Comment by Mzhang1994** [comment]
![Snipaste_2022-06-09_11-14-41](https://user-images.githubusercontent.com/69185609/172756539-9a62cdff-90d5-42b7-9dc5-54a824630c3e.png)
这是proform的属性，stepform应该也能用。

**Comment by chenshuai2144** [comment]
Form中没使用的字段 在form 中拿有点不合理。
你可以做个不可见的组件，然后把数据存进去
