### ISSUE TITLE
schemeForm的columns 使用正则验证不生效🧐[问题]

### ISSUE THREAD

**Issue by cqb421392034** [ant-design/pro-components#5361]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
schemeForm的columns 使用正则验证不生效 用自带的type可以生效 如下面的电话跟邮箱

### 💻 示例代码
onst formItem=[
{
title: '电话',
dataIndex: 'lxdh',
key: 'lxdh',
formItemProps: {
hasFeedback: true,
rules: [

			{
				required: true,
				message: '电话不能为空',
			},
			{ pattern: /^1[3|4|5|7|8|9][0-9]\d{8}$/, message: "请输入正确的手机号" }
		],
	},
},
{
	title: '邮箱',
	dataIndex: 'email',
	key: 'email',
	rules: [{ type: 'email' }],
	formItemProps: {
		hasFeedback: true,
		rules: [
			{ type: 'email' }
		],
	},
}
];
<BetaSchemaForm
form={form}
layoutType='Form'
rowProps={{
gutter: [0, 0],
}}
colProps={{
span: 12
}}
labelCol={{
span: 6
}}
requiredMark
labelWrap={true}
labelAlign="left"
layout="horizontal"
grid={true}
columns={formItem}
submitter={false}
onFinish={(e) => { console.log(e) }}
/>

**Comment by cqb421392034** [comment]
有人用这个功能吗

**Comment by chenshuai2144** [comment]
要不要先看看自己提了个什么issue，保证下格式正确吧
