### ISSUE TITLE
👑 [需求] ProTable查询卡片中，按钮所占列宽如何调整？

### ISSUE THREAD

**Issue by owendswang** [ant-design/pro-components#5365]
### 🔩 所属模块或组件

ProTable

### 🥰 需求描述

如何调整查询card中查询按钮那个框框的宽度，就是当我设置search={{ span: 4 }}时，按钮会挤到一起。

### ⛰ 功能需求适用场景

能够独立调整查询卡片中，查询按钮的列宽。

### 🧐 解决方案

每一列可以设置colSize来指定站多少个span，是不是可以做个类似的选项。

### 🚑 其他信息

不会github传图，抱歉……

**Comment by chenshuai2144** [comment]
只能通过span来调整。 为了保证对齐没有增加其他方式

**Comment by owendswang** [comment]
> 只能通过span来调整。 为了保证对齐没有增加其他方式

非常感谢回复！

但是当我把span设置的非常小时，按钮那一栏也会非常小，无法像其他项目一样通过colSize来调整。
可是我不希望他挤到一起去，我该怎么办？

**Comment by chenshuai2144** [comment]
用样式硬写吧

**Comment by owendswang** [comment]
好的，感谢回复。
