### ISSUE TITLE
如何开启路由菜单搜索功能呢👑 [需求]

### ISSUE THREAD

**Issue by zhoujiaxu2014** [ant-design/pro-components#5370]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述
因为菜单越来越多了 怎么添加搜索功能呢

**Comment by chenshuai2144** [comment]
有一个demo的去看看

**Comment by cuijiudai** [comment]
> 有一个demo的去看看

哪里啊

**Comment by drizzlesconsin** [comment]
[search-menu](https://procomponents.ant.design/en-US/components/layout#search-menu)

**Comment by werrtyuiu** [comment]
> [search-menu](https://procomponents.ant.design/en-US/components/layout#search-menu)

但是使用这个之后 为什么布局错乱了
