### ISSUE TITLE
🧐[问题] 根据文档 renderFormItem 会自动注入value,onChange，但是我打印出来却没有

### ISSUE THREAD

**Issue by zhugexinxin** [ant-design/pro-components#5376]
### 🧐 问题描述
🧐[问题] 根据文档 renderFormItem 会自动注入value,onChange，但是我打印出来却没有

### 💻 示例截图
![image](https://user-images.githubusercontent.com/42615243/173754515-c902bd1a-f3e4-4452-aba1-692eb48cded3.png)

打印结果
![image](https://user-images.githubusercontent.com/42615243/173754639-cffc9a8c-ce49-4a29-89f3-2a5c59c50680.png)

### 🚑 其他信息
我是比较早就在使用protable，这次升级到最新发生的。
是我使用方法有问题还是遗漏了什么？

版本信息:     "@ant-design/pro-table": "^2.71.0"

**Comment by zhugexinxin** [comment]
原来是注入到后面组件里了，和以前地方不一样了。

**Comment by hurole** [comment]
> 原来是注入到后面组件里了，和以前地方不一样了。

我也很疑惑这个问题，请问你是怎么解决的
