### ISSUE TITLE
🐛[BUG]ProTable只有一个搜索项时内容区域小于560px会显示展开/收起的操作

### ISSUE THREAD

**Issue by 974973202** [ant-design/pro-components#5379]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProTable只有一个搜索项时内容区域小于560px会显示展开/收起的操作

### 📷 复现步骤

https://codesandbox.io/s/biao-ge-zhi-you-yi-ge-sou-suo-xiang-jcsvic

### 🏞 期望结果

ProTable只有一个搜索项时小于一定的内容区域不会显示展开/收起的操作

### © 版本信息

- ProTable 版本: [2.76.0]

**Comment by chenshuai2144** [comment]
没有听懂。你是希望做自适应？

**Comment by 974973202** [comment]
只有一个搜索项不显示展开/收起的操作。用户会误以为不止一个搜索项。其实只有一个搜索项



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月16日 11:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ant-design/pro-components] 🐛[BUG]ProTable只有一个搜索项时内容区域小于560px会显示展开/收起的操作 (Issue #5379) |

没有听懂。你是希望做自适应？

**Comment by chenshuai2144** [comment]
soga，只有一个竟然会出现，不会的呀

**Comment by 974973202** [comment]
表格小于560px就会出现这种情况，仔细看下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月16日 11:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ant-design/pro-components] 🐛[BUG]ProTable只有一个搜索项时内容区域小于560px会显示展开/收起的操作 (Issue #5379) |

soga，只有一个竟然会出现，不会的呀

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/pull/5442

看起来这里修复了
