### ISSUE TITLE
bug: Could not find dependency: '@ant-design/pro-components' relative to '/App.tsx'🐛[BUG]

### ISSUE THREAD

**Issue by binyellow** [ant-design/pro-components#5380]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

所有在线demo打开都报错，open demo on CodeSandbox.io报错
![image](https://user-images.githubusercontent.com/29519985/173975788-41237107-9350-4116-b763-755326e32bdb.png)
![image](https://user-images.githubusercontent.com/29519985/173976203-fde287e2-66ba-4a8b-b3d2-010e882fa852.png)

### 📷 复现步骤

1. 打开链接https://codesandbox.io/s/swsnsf?file=/App.tsx
2. [其他pro-components的在线demo都会报错](https://procomponents.ant.design/components/form)

### 🏞 期望结果

不报错
### 💻 复现代码

https://github.com/ant-design/pro-components
### © 版本信息

- ProComponents 版本: [2.76.2]
- umi 版本 [3.5.26]
- 浏览器环境 [版本 102.0.5005.61（正式版本） (x86_64)]
- 开发环境 [macOs monterey 12.0.1]

### 🚑 其他信息
排查到是dumi的问题，但是影响pro-components文档页挺久了，有时候想在线调试代码就报错，不太友好，麻烦跟进一下
[关联issue](https://github.com/umijs/dumi/issues/1105)

**Comment by chenshuai2144** [comment]
暂时没空搞dumi的事情，手动搞下
