### ISSUE TITLE
ProComponents文档：架构设计/通用配置总览往下滑页面会白屏🐛[BUG]

### ISSUE THREAD

**Issue by XT-0515** [ant-design/pro-components#5385]
### 🐛 bug 描述

ProComponents文档：架构设计/通用配置总览往下滑页面会白屏

### 📷 复现步骤

1、ProComponents文档/架构设计/通用配置总览
2、页面往下滑

### 🏞 期望结果

正常展示

### © 版本信息

- 浏览器环境：google chrome 版本 102.0.5005.115（正式版本） (x86_64)
- 开发环境 mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/47058891/174031832-b89bd385-f3c6-4206-b934-29cd2a181931.png)

**Comment by 868618** [comment]
我的也是

**Comment by Lpbzzz** [comment]
+1

**Comment by netcore-jroger** [comment]
往下滑动到这个位置就会报错。
![图片](https://user-images.githubusercontent.com/3223890/174786902-f29652ed-08c0-4966-b67b-e409a969fa40.png)

**Comment by wangmeijian** [comment]
已修复，等发版吧
