### ISSUE TITLE
🐛[BUG] queryFilter收起/展开时会重新触发组件的生命周期

### ISSUE THREAD

**Issue by mraiguo** [ant-design/pro-components#5389]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

点击搜索展开后，组件的生命周期 componentDidMount, ComponentWillUnmount 完整走了一遍。  
因为此组件是个有请求的业务组件，导致每次都会去重新请求一遍数据

### 📷 复现步骤

https://codesandbox.io/s/cha-xun-shai-xuan-forked-57xfqx?file=/App.tsx:0-1196 
点击展开、收起按钮查看控制台的打印

### 🏞 期望结果

搜索表单项只是单纯的隐藏，不触发react的生命周期

### © 版本信息

- ProComponents 版本: [1.1.6]
- umi 版本
- 浏览器环境[chrome]
- 开发环境 [mac OS]

### 🚑 其他信息

<img width="988" alt="image" src="https://user-images.githubusercontent.com/22299421/174206965-608cbd15-c82e-4b4d-b47a-4abd2cfe3438.png">

**Comment by chenshuai2144** [comment]
为了节省性能一点，所以隐藏的时候直接删除的dom
