### ISSUE TITLE
🐛[BUG] 求助，pro-table valueType="date"时 fieldProps未生效

### ISSUE THREAD

**Issue by bluescurry** [ant-design/pro-components#539]
### 🐛 bug 描述

pro-table 的 columns 设置 valueType="date"时，设置 fieldProps 的 picker 字段为 "month" 未生效，2.5.x的用 formItemProps 字段设置是没问题的

### 📷 复现步骤

```
{
    title: '月份',
    dataIndex: 'month',
    valueType: 'date',
    fieldProps: {
      picker: 'month',
      format: 'YYYY-MM',
    },
  },
```

### 🏞 期望结果

![image](https://user-images.githubusercontent.com/19237129/93550335-c34ce680-f99d-11ea-9050-99b94df79e73.png)

### © 版本信息

- ProComponents 版本: pro-table：2.7.4
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by bluescurry** [comment]
我看了下源码，设置：valueType: 'dateMonth'。可以展示出月份，但是是英文的，还需要配啥国际化的？
![image](https://user-images.githubusercontent.com/19237129/93551147-c21cb900-f99f-11ea-8d40-1f95da7cf7b8.png)

**Comment by chenshuai2144** [comment]
直接用   | 'dateMonth'

https://github.com/ant-design/pro-components/blob/83c31dc447f1f73b686a53aecea487f350991294/packages/field/src/index.tsx#L47
