### ISSUE TITLE
🧐[问题] 性能问题：requestAnimationFrame handler took xxxms

### ISSUE THREAD

**Issue by fayeah** [ant-design/pro-components#5393]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

在使用pro-table组件时，浏览器出现了warning：

![image](https://user-images.githubusercontent.com/29644978/174244770-e131a693-a339-406e-ac00-17196d4c3537.png)

并且列越多，页面渲染耗时越多，不知道pro-table渲染的逻辑，但是应该是性能优化的方法。
### 💻 示例代码

```
<ProTable
...
 columns={[]}
/>
```

### 🚑 其他信息
我在使用pro-table时需要渲染大量数据，列数也较多，期望在性能上有一些可以借鉴和提高的方案。

**Comment by chenshuai2144** [comment]
数据比较多直接上虚拟滚动吧
