### ISSUE TITLE
🐛[BUG] 官网 通用组件总览页面 滚动到底部后页面白屏

### ISSUE THREAD

**Issue by xuzeshen** [ant-design/pro-components#5394]
### 🐛 bug 描述

用chrome浏览器/Firefox浏览器打开pro官网 [通用配置总览](https://procomponents.ant.design/components/schema)
往下滚动，滚动到一定程度，网页白屏，打开控制台，发现一堆error（隐私模式无插件情况下亦出现）

### © 版本信息

- 浏览器环境
chrome：102
Firefox：102

**Comment by xu-Aurora** [comment]
我也是，刚开始我以为是我电脑的问题

**Comment by wangmeijian** [comment]
fixed，等发版吧 https://github.com/ant-design/pro-components/pull/5408
