### ISSUE TITLE
🐛[BUG] layoutV6.3.0 页面首次加载完，首次点击菜单会再次加载菜单，会闪烁一下

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#54]
### 🐛 bug 描述

layoutV6.3.0 页面首次加载完，首次点击菜单会再次加载菜单，会闪烁一下

### 📷 复现步骤

http://preview.pro.ant.design/ 预览页面也是这样

**Comment by shaohuatsou** [comment]
> ### 🐛 bug 描述
> layoutV6.3.0 页面首次加载完，首次点击菜单会再次加载菜单，会闪烁一下
> 
> ### 📷 复现步骤
> http://preview.pro.ant.design/ 预览页面也是这样

咋关闭了啊？找到解决方案了吗？共享一下吧

**Comment by hihuangwei** [comment]
> > ### 🐛 bug 描述
> > layoutV6.3.0 页面首次加载完，首次点击菜单会再次加载菜单，会闪烁一下
> > ### 📷 复现步骤
> > http://preview.pro.ant.design/ 预览页面也是这样
> 
> 咋关闭了啊？找到解决方案了吗？共享一下吧 @hihuangwei

升级umi到最新即可解决
