### ISSUE TITLE
🐛[BUG]官方文档无法完整正常浏览

### ISSUE THREAD

**Issue by zooPanda** [ant-design/pro-components#5400]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

[文档链接](https://procomponents.ant.design/components/schema/)
这个页面打开后，滑动到[远程数据部分](https://procomponents.ant.design/components/schema/#远程数据)会出现白屏。

控制台打印 TypeError: undefined is not an object (evaluating 'e.createElement')

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]
macOS 12.3.1
Safari 版本15.4 (17613.1.17.1.13)
Chrome 版本 102.0.5005.115（正式版本） (x86_64)

**Comment by wangmeijian** [comment]
修复中

**Comment by chenshuai2144** [comment]
fixed
