### ISSUE TITLE
ModalForm的onFinish控制不了多次点击

### ISSUE THREAD

**Issue by xu-Aurora** [ant-design/pro-components#5402]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/35291465/174573954-35876286-5688-4755-86c3-ec3c29928d60.png">

通过useRequest实现节流，但快速点击触发onFinish，会在modal关闭的时候再次触发一次请求。猜测是onFinish和useRequest冲突嘛？

umi：3.5.24
ant-design/pro-form": 1.69.3

**Comment by chenshuai2144** [comment]
你 await 一下  run 。run 也是异步的。
