### ISSUE TITLE
🐛[BUG] FormItem中addonAfter、addonBefore导致宽度异常

### ISSUE THREAD

**Issue by Mrchangchang** [ant-design/pro-components#5406]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

proForm组件bug，当Form.Item 存在 `addonAfter` 或 `addonBefore` ，会增加内样式 `width: 'max-content',maxWidth: '100%',`。
`max-content`会导致 `FormItem`  宽度异常。

### 📷 复现步骤
https://codesandbox.io/s/keen-wind-mhdpiz

### 🏞 期望结果

 `FormItem`  宽度自然撑开

### 💻 复现代码

[](https://codesandbox.io/s/keen-wind-mhdpiz)

### © 版本信息

- ProComponents 版本: @ant-design/pro-[form@1.69.2
- umi 版本 3.x
- 浏览器环境 谷歌浏览器
- 开发环境 win11

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/25929184/174703102-770f01fe-8060-4da3-8fce-11c2a3eb8141.png)

**Comment by wangmeijian** [comment]
修复中

**Comment by leshalv** [comment]
已更新新版本，这个问题并没有被解决
<img width="662" alt="image" src="https://user-images.githubusercontent.com/30397655/176653954-8fba0f7b-e9d9-4aee-8fec-20a449ad5e52.png">
<img width="669" alt="image" src="https://user-images.githubusercontent.com/30397655/176654062-d48196bf-bcb8-4f86-9798-881062b8dde0.png">

**Comment by Mrchangchang** [comment]
我看一下。

**Comment by Mrchangchang** [comment]
更新一下依赖，然后跑下 npm list  看下@ant-design/pro-form 版本号。
我这边问题已经修复了。
