### ISSUE TITLE
如何在ProFormList自定义操作按钮，修改当前list的某个字段呢，现在我看默认方法只有新增删除和移动

### ISSUE THREAD

**Issue by zhangzheyi1** [ant-design/pro-components#5411]
/**
   * @name 自定义操作按钮
   *
   * @example 删除按钮
   * actionRender:(field,action)=><a onClick={()=>action.remove(field.key)}>删除</a>
   * @example 最多只能新增三行
   * actionRender:(f,action,_,count)=><a onClick={()=>
   *   count>2?alert("最多三行！"):action.add({id:"xx"})}>删除
   * </a>
   */
  actionRender?: (
    field: FormListFieldData,
    /**
     * 操作能力
     * @example  action.add(data) 新增一行
     * @example  action.remove(index) 删除一行
     * @example  action.move(formIndex,targetIndex) 移动一行
     */
    action: FormListOperation,
    /**
     * 默认的操作dom
     * [删除，复制，新增]
     */
    defaultActionDom: ReactNode[],
    /**
     * 当前共有几个列表项
     */
    count: number,
  ) => ReactNode[];
  
  只有这三种方法啊，不知道用ProFormList能否可以操作当前列数据，有大佬们知道怎么写么

**Comment by chenshuai2144** [comment]
用 formRef 当成表单项目来操作数据。

`formRef.setFiledvalues({ listName:[] })`
