### ISSUE TITLE
👑 [需求]LoginForm有form={form}属性吗？

### ISSUE THREAD

**Issue by qian-zs** [ant-design/pro-components#5416]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

登录表单：LoginForm

### 🥰 需求描述

LoginForm可以加一下 form={form} 属性吗？

### ⛰ 功能需求适用场景

记住账号等，对登录表单进行赋值操作

### 🧐 解决方案

目前用useRef解决了

**Comment by chenshuai2144** [comment]
formRef 有这个api 的，功能是相同的
