### ISSUE TITLE
🐛[BUG] @ant-design/pro-form 16.9.4 onVisibleChange 事件后续不触发

### ISSUE THREAD

**Issue by LengYXin** [ant-design/pro-components#5423]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
@ant-design/pro-form 16.9.4 onVisibleChange 事件后续不触发
触发第一次 后 第二次打开 就无法关闭

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
修复了，升级一下依赖
