### ISSUE TITLE
🐛[BUG] 官网上的pro-table的select性能表现异常差

### ISSUE THREAD

**Issue by wdaglb** [ant-design/pro-components#5425]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

windows10上pro-table的select性能表现异常差，antd的官网性能则正常
在mac上感知则没那么明显，但是其实也是有一点点卡，没那么容易感知

### 📷 复现步骤

官网的demo就是复现，这是我录的一段视频：https://github.com/wdaglb/antd-video/blob/master/video.mp4

### © 版本信息

- ProComponents 版本: 官网
- 浏览器环境: edge
- 开发环境 windows10

### 🚑 其他信息

CPU e5 2680
显卡 1050
内存 32G

**Comment by chenshuai2144** [comment]
新版本看起来已经好了，性能好多了
