### ISSUE TITLE
🧐[问题] Pro Table 通过操作dataSource来添加行，如何才能增加多行？

### ISSUE THREAD

**Issue by Ripple0416** [ant-design/pro-components#5429]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

因为要做到同级或子级添加，所以我是在表格上方有两个按钮，通过按钮点击事件来修改dataSource，但现在的问题是每次只能新增一行

### 💻 示例代码
```
	rowKey="id"
	recordCreatorProps={false} 
	tableAlertRender={false}
	rowSelection={{ ...rowSelection }} 
```

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/issues/5054#issuecomment-1168395770
这里里面讨论了。

**Comment by chenshuai2144** [comment]
> 通过按钮点击事件来修改dataSource

push 几下不是你自己空的吗？怎么会有每次新增一行的问题？

**Comment by Ripple0416** [comment]
他报了一个每次只能新增一行的提醒

**Comment by Ripple0416** [comment]
>> push 几下不是你自己控制吗？
>
> 我并未使用recordCreatorProps和actionRef.current?.addEditRecord(row)这两种方法，但是他新增一行之后再点击新增就会提示只能新增一行，除非新增的那一行进行保存或取消，才能接着新增一行数据

**Comment by mansion-sun** [comment]
源码中：if(f.current&&!1!==n.onlyAddOneLineAlertMessage)return r.ZP.warn(n.onlyAddOneLineAlertMessage||"只能新增一行"),!1;
@chenshuai2144 f.current没看懂，但onlyAddOneLineAlertMessage传false可以避免触发提示；
实际使用感觉是受editableKeys控制的，只要editableKeys不唯一就不会触发这个提示，你dataSource修改之后，没有同步setEditableRowKeys导致的吧？ @Ripple0416 
猜你想要实时保存的指定位置插入多行编辑表格:
https://codesandbox.io/s/shi-shi-bao-cun-de-zhi-ding-wei-zhi-cha-ru-duo-xing-bian-ji-biao-ge-forked-5vh0n5?file=/App.tsx

**Comment by cangsnage** [comment]
> 

问下如果使用actionRef怎么才能不触发这个提示，一直新增呢

**Comment by xqb0407** [comment]
@chenshuai2144 如果结合ProForm.Item 用dataSource 如何添加呢，我尝试了一下，没法添加上去
