### ISSUE TITLE
🐛[BUG]Pro-Table Colums

### ISSUE THREAD

**Issue by jassonxian** [ant-design/pro-components#543]
### 🐛 bug 描述

Colums 中 ellipsis, width同时设置，width参数无效
![image](https://user-images.githubusercontent.com/21199561/93570843-336f6280-f9c6-11ea-8577-94d93fb15c03.png)

### © 版本信息

- @ant-design/pro-table 版本: [2.7.4]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by sgknight2020** [comment]
我也碰到这个问题了，希望能够尽快解决。

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/483

**Comment by sgknight2020** [comment]
`"@ant-design/pro-table": "^2.8.1",`今天升级到最新版本，依然有问题。
![image](https://user-images.githubusercontent.com/59961046/93980300-07325800-fdb1-11ea-96be-c2788c058b51.png)

**Comment by jassonxian** [comment]
"@ant-design/pro-table": "^2.9.3",今天升级到最新版本，依然有问题。
