### ISSUE TITLE
🐛[BUG]ProFormText  fieldProps指定type="search"页面表现没有出现图标，和antd Search不一样

### ISSUE THREAD

**Issue by imoxuan** [ant-design/pro-components#5430]
ProFormText  fieldProps指定type="search"页面表现没有出现图标，和antd Search不一样。
<ProForm.Group>
<ProFormText
              width="md"
              name="icon"
              label="菜单图标"
              placeholder=""
              fieldProps={{
                type: "search"
              }}
            />
</ProForm.Group>
![image](https://user-images.githubusercontent.com/11343073/175437394-bd926844-09c4-416b-9300-4456f6a4e5e6.png)

"dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-card": "^1.19.0",
    "@ant-design/pro-descriptions": "^1.10.0",
    "@ant-design/pro-form": "^1.64.0",
    "@ant-design/pro-layout": "^6.35.0",
    "@ant-design/pro-table": "^2.71.0",
    "@umijs/route-utils": "^2.0.0",
    "antd": "4.20.7",
    "classnames": "^2.3.0",
    "lodash": "^4.17.0",
    "moment": "^2.29.0",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.1.0",
    "rc-util": "^5.16.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.7.0",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.2.0",
    "umi": "^3.5.0"
  },

**Comment by chenshuai2144** [comment]
antd 也不支持这个用呀。

```
import { Input } from 'antd';
import React from 'react';

const { Search } = Input;
```

用input 的api加个图标上去？
