### ISSUE TITLE
🧐[问题] proTable 查询表单部分的查询操作列能否动态的配置offset 及align 方式

### ISSUE THREAD

**Issue by xuchunwei123** [ant-design/pro-components#5431]
现在protable 的查询表单部分中 无论查询条件的多少 查询操作列都是在最右侧  但是在只有一个 活着两个查询条件的时候 中间就会空很大一段 尤其在大显示器下尤为明显  所以考虑能否在查询条件少的情况下 操作列改为跟随在查询条件后面 或者提供动态配置操作列offset 及align的配置

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好，针对你的问题，可以通过调整样式来改变查询操作列的位置，同时可以使用 `toolbarRender` 来动态设置查询操作列的位置。

下面是一个示例代码，你可以在其中尝试修改 `offset` 和 `align` 的值，以达到你想要的效果：

```jsx
import ProTable from '@ant-design/pro-table';

const columns = [/* 表格列配置 */];

const fetchData = (params) => {
  // 获取数据的逻辑
};

const toolbarRender = (action) => {
  return [
    <div
      style={{
        display: 'inline-block',
        justifyContent: 'space-between',
        width: '100%',
      }}
    >
      <div>{action[0]}</div>
      <div
        style={{
          float: 'right',
          textAlign: 'right',
        }}
      >
        {action[1]}
      </div>
    </div>,
  ];
};

<ProTable
  columns={columns}
  request={fetchData}
  toolbarRender={toolbarRender}
/>;
```

除此之外，你还可以使用 `sizeEnum` 和 `search` 属性来控制查询表单和操作列是否显示。

你可以参考以下文档了解更多相关属性：

- ProTable API：https://procomponents.ant.design/components/table/#api
- toolbarRender 属性：https://procomponents.ant.design/components/table/#toolbarrender
- sizeEnum 属性：https://procomponents.ant.design/components/table/#sizeenum
- search 属性：https://procomponents.ant.design/components/table/#search

**Comment by chenshuai2144** [comment]
不太推荐，如果有 pr 我会review
