### ISSUE TITLE
🧐[问题] WaterMark 水印组件 如何添加多行文字

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#5435]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

WaterMark 水印组件 如何添加多行文字

**Comment by chenshuai2144** [comment]
现在不支持。

https://github.com/ant-design/pro-components/blob/d882705b6c2e98e6261e981509b24a62ad66b56c/packages/layout/src/components/WaterMark/index.tsx#L130-L131

这里可以支持一下数组就可以配置多行了，你有兴趣来个pr吗？
