### ISSUE TITLE
🧐[问题] 可移植的语言环境

### ISSUE THREAD

**Issue by robrob-creator** [ant-design/pro-components#5436]
是仅限于 zhCN, enUS,  enGB, viVN, itIT, jaJPInt, esES, caES, ruRU, srRS, msMY, zhTW,frFR, and ptBR,FRFR，和 ptBR 我通过配置提供程序尝试了 thTh，但过滤器只是翻译成中文

**Comment by chenshuai2144** [comment]
> 过滤器只是翻译成中文

这个是antd 的，你要配置antd的 provide
