### ISSUE TITLE
🐛[BUG]Pro Layout 官方文档的 “Example 展示” 这个示例结合react-hot-loader使用会报错

### ISSUE THREAD

**Issue by hzyhbk** [ant-design/pro-components#544]
### 🐛 bug 描述

https://procomponents.ant.design/components/layout#example-%E5%B1%95%E7%A4%BA
这个例子的代码结合react-hot-loader使用，在修改项目的代码保存之后会使整个应用崩溃。
### 📷 复现步骤
1. clone仓库 https://github.com/hzyhbk/pro-layout-bug
2. 安装依赖
3. 启动项目
4. 随意修改Layout/index.js，保存

### 🏞 期望结果
热更新成功

### 💻 实际结果
页面崩溃
![image](https://user-images.githubusercontent.com/42671099/93574284-d033ff00-f9ca-11ea-9c87-c79e76ed9e55.png)

### © 版本信息

- ProComponents 版本: pro-layout 6.4.18
- 浏览器环境 Edge  84.0.522.40
- 开发环境 mac OS 10.15.4

**Comment by chenshuai2144** [comment]
你使用的是 umi 吗？

**Comment by hzyhbk** [comment]
最初发现问题是我们自己内部的框架，然后我用create-react-app创建的项目也能复现此bug。

**Comment by jiachaosun** [comment]
我这里也发现有此问题，没有使用任何脚手架，纯手工搭建的内部react框架

```
(AppContainer, in BasicLayout (created by PageLayout)) TypeError: Cannot read property 'breadcrumb' of undefined
```

**Comment by chenshuai2144** [comment]
@jiachaosun 能提供一个repo码？

**Comment by jiachaosun** [comment]
有解决吗？1L已经提供了repo吧

**Comment by joker77877** [comment]
@chenshuai2144 Don't you solve this bug.

**Comment by JM-Master** [comment]
这个问题近期会考虑修复吗？

**Comment by jiachaosun** [comment]
> 这个问题近期会考虑修复吗？

不要使用hot-reload来热更新，用 React Fast Refresh就不会有这问题了

**Comment by jiachaosun** [comment]
> @chenshuai2144 Don't you solve this bug?

Finally i use React Fast Refresh instead of React hot-reload and problem solved.

**Comment by rumunanfeng** [comment]
> 最初发现问题是我们自己内部的框架，然后我用create-react-app创建的项目也能复现此bug。

遇到了一样的问题，请问您最后解决了吗？

**Comment by wen-haoming** [comment]
> > 最初发现问题是我们自己内部的框架，然后我用create-react-app创建的项目也能复现此bug。
> 
> 遇到了一样的问题，请问您最后解决了吗？

react-hot-loader 已经弃坑了 https://github.com/gaearon/react-hot-loader#moving-towards-next-step， 官方推荐使用使用 react-refresh  https://github.com/facebook/react/issues/16604

**Comment by JayMo666** [comment]
我也遇到类似的问题，除了更换为react-refresh还有其他方法吗？

**Comment by chenshuai2144** [comment]
感觉可以关掉这个了，我专门支持了一下 react-refresh

**Comment by gt-hans** [comment]
我用cra建的項目用antd components的Layout/Sider/Menu hot-reload沒有問題, 但換成pro-component的pro-layout就無法hot-reload, cra的react-refresh@0.8.3
我是直接用yarn add @ant-design/pro-layout
