### ISSUE TITLE
🐛[BUG] BetaSchemaForm中，当valuetype=code 或者jsonCode时，展示的组件是输入框

### ISSUE THREAD

**Issue by chenxiao6323** [ant-design/pro-components#5444]
提问前先看看：

https://procomponents.ant.design/components/schema
![image](https://user-images.githubusercontent.com/108327434/176121757-30837e2a-6579-47f9-87ad-fb47cd40f1dc.png)

### 🐛 bug 描述
BetaSchemaForm中，当valuetype=code 或者jsonCode时，展示的组件是输入框

### 🏞 期望结果
展示对应的code或者jsonCode组件

### 💻 复现代码
![Uploading image.png…]()

**Comment by chenshuai2144** [comment]
图片上传失败了

**Comment by yiyi17** [comment]
遇到了同样的问题

**Comment by PineSongCN** [comment]
> format

请问是什么意思？`format `该怎么加？
