### ISSUE TITLE
🐛[BUG] ProTable 设置 scroll 后没有出现滚动条，造成无法滚动

### ISSUE THREAD

**Issue by sakura-flutter** [ant-design/pro-components#5445]
### 🐛 bug 描述
设置 scroll x 或 y 后没有出现对应的滚动条，造成无法滚动

### 📷 复现步骤
启动项目，切换到查询表格菜单 /list/table-list
在 ProTable 中设置 scroll，x 或 y 都可以

### 🏞 期望结果
设置 scroll 后应该要像线上示例那样出现滚动条

### 💻 复现代码
用的是 Pro 创建出来的项目，仅添加了 scroll 的设置
https://github.com/sakura-flutter/ant-design-pro-components-issues
在项目上可以复现，但在官方例子上复现不出来，不知道是什么原因
https://codesandbox.io/s/cha-xun-wu-an-niu-biao-ge-forked-de9mkk?file=/App.tsx:2775-2802

### © 版本信息

- @ant-design/pro-table 版本: 2.76.4
- umi 版本 3.5.26
- 浏览器环境 Chrome 102.0.5005.115
- 开发环境 Windows 11 与 mac OS

### 🚑 其他信息

![微信截图_20220628172443](https://user-images.githubusercontent.com/28331128/176144087-a01a78f6-26b6-4bc1-b423-519ff4b860e5.png)
滚动条不见了，仅有 table 两边的阴影

**Comment by chenshuai2144** [comment]
Ant Design 4.21.5 发布日志
◆ 🐞 修复 Checkbox 不会被 Form disabled 属性禁用的问题。#36345
◆ 🐞 修复 Button loading 属性传入 null 时错误问题。#36288 @kejianfeng
◆ 🐞 修复弹出框箭头在某些浏览器上的兼容性问题。#36266
◆ 🐞 修复 Table 滚动阴影在内嵌表格内出现的问题。#36277
◆ 🐞 修复 Divider 部分类名无法自定义的问题。#36271 @alanhaledc
◆ 🇧🇾 调整白俄罗斯国际化语言。#36265


更新一下 antd 的版本是是，我看了一下是代码生成错了的样子

**Comment by sakura-flutter** [comment]
解决了~
