### ISSUE TITLE
EditableProTable 频繁执行 编辑 取消操作，会清空字段值 🐛[BUG]

### ISSUE THREAD

**Issue by beysong** [ant-design/pro-components#5447]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

EditableProTable 频繁执行 编辑 取消操作，会清空字段值

### 📷 复现步骤

新增一行数据，填充完整，保存->编辑->取消->编辑，原来保存的数据会被清空

### 🏞 期望结果

保留原来保存的数据

### 💻 复现代码

https://codesandbox.io/s/yu-formitem-pei-he-forked-7t47i6?file=/App.tsx

### © 版本信息

- ProComponents 版本: 1.1.6
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

https://user-images.githubusercontent.com/5705613/176435835-1c561d67-326b-415c-81a2-481f07f14907.mov

**Comment by beysong** [comment]
定位到是校验问题
#2210 这个可以解决

**Comment by WuJiY** [comment]
感觉解决的方案不够纯
