### ISSUE TITLE
👑 [需求]建议antd pro的less名称不使用antd 的 ant-prefix 变量。

### ISSUE THREAD

**Issue by KellenHe** [ant-design/pro-components#545]
### 🥰 需求描述

antd pro的less变量前缀和antd使用的同一个变量@ant-prefix。建议单独使用一个自定义的变量前缀。
在使用qiankun时，angular和react都使用了antd，想通过修改@ant-prefix的方式让react引用antd样式失效，统一使用angular的antd。但是修改后发现antd pro的也被修改了。

### 🧐 解决方案

建议单独使用一个自定义的变量前缀。例如@ant-pro-prefix ?

**Comment by chenshuai2144** [comment]
可以定义一个 @ant-pro-prefix = @ant-prefix-pro


你就可以重置  @ant-pro-prefix  改回来。 你不应该是用 react 的样式吗？

**Comment by KellenHe** [comment]
@chenshuai2144 是想angular和react使用一套样式。不区分angular和react

**Comment by KellenHe** [comment]
改了@ant-prefix之后需要自己打包antd，组件样式名称才会生效。
