### ISSUE TITLE
👑 [需求]是否有计划升级至react-router@6

### ISSUE THREAD

**Issue by lanzhi-lee** [ant-design/pro-components#5451]
### 🥰 需求描述

是否有计划升级至react-router@6?

以及react-router-dom?

### ⛰ 原因

react-router已经升级至6版本，而本仓库仍然依赖的是5版本，发现pro-layout在与6版本共存是，pro-layout依赖的@types/history会出现找不到类型定义的问题

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/36190508/176650318-8647723d-acdb-42f8-8e9e-0c11af1d229b.png">

**Comment by chenshuai2144** [comment]
umi@4 就是了。layout 和 react-router 没关系的
