### ISSUE TITLE
proLayout里如何动态加载路由？🧐[问题]

### ISSUE THREAD

**Issue by ZeXinWork** [ant-design/pro-components#5452]
![image](https://user-images.githubusercontent.com/71616798/176651398-72a361db-dedc-4e50-a1c5-a1bd27129975.png)
这些component加载不出来，请问这个方法如何解决？因为要做动态路由，没办法再route.ts里直接配置路由

**Comment by chenshuai2144** [comment]
动态路由无法实现的
