### ISSUE TITLE
🐛[BUG] ProTable Columns 设置 valueType: 'select' 后无法显示省略号

### ISSUE THREAD

**Issue by sakura-flutter** [ant-design/pro-components#5453]
### 🐛 bug 描述

ProTable Columns 设置 valueType: 'select' 后无法显示省略号 ...

### 📷 复现步骤
  columns: 
  ```
{
      dataIndex: "email",
      key: "ellipsis2",
      title: "select valueType 无法显示省略号",
      ellipsis: true,
      valueType: "select",
      fieldProps: {
        options: [
          { label: "超长".repeat(50), value: "超长".repeat(50) },
          { label: "1", value: "1" }
        ]
      }
}
```
### 🏞 期望结果

正常显示省略号 ...

### 💻 复现代码

https://codesandbox.io/s/wu-toolbar-de-biao-ge-forked-nu7s5c?file=/App.tsx:1213-1240

### © 版本信息

- ProComponents 版本: 1.1.6
- 浏览器环境 103.0.5060.66
- 开发环境 win11

### 🚑 其他信息
默认情况下能否不加这个 div？
![微信截图_20220630180806](https://user-images.githubusercontent.com/28331128/176651940-5a2fa630-e568-4827-8d77-bb03703717c3.png)

**Comment by chenshuai2144** [comment]
看了以下跨域了多个dom，的确是没法实现

**Comment by dongyuwhz** [comment]
怎么解决的，我也看到了一样的情况
