### ISSUE TITLE
👑 [需求]

### ISSUE THREAD

**Issue by fjj199741** [ant-design/pro-components#5456]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

BetaSchemaForm->StepsForm

BetaSchemaForm  layoutType 为 StepsForm 时  layout 参数设置为 horizontal 不生效
源码里面写死了  vertical ,而按照客户的需求，需要表单标签水平排列

### 🧐 解决方案

将源码写死部分改为从 props 里面取 layout 属性

**Comment by fjj199741** [comment]
> 提问前先看看：
> 
> https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
> 
> BetaSchemaForm->StepsForm
> 
> BetaSchemaForm layoutType 为 StepsForm 时 layout 参数设置为 horizontal 不生效 源码里面写死了 vertical ,而按照客户的需求，需要表单标签水平排列
> 
> ### ⛰ 功能需求适用场景
> ### 🧐 解决方案
> 将源码写死部分改为从 props 里面取 layout 属性

**Comment by rawbin-** [comment]
这个问题有跟进么

**Comment by Laurieliuren** [comment]
> 在steps里写 `steps={[ { title: '子步骤', layout: 'horizontal', labelCol: { span: 6 }, wrapperCol: { span: 18 }, }, ]}`

感谢！费了老大劲，终于找到答案了！
