### ISSUE TITLE
🧐[问题]ProFormDatePicker的colProps指定span没效果

### ISSUE THREAD

**Issue by wooxyz** [ant-design/pro-components#5461]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/33221294/176840537-4eced14c-cbe5-4f30-867b-3c7feca70e2e.png)

```
<ProFormTextArea colProps={{ span: 24 }} name="address"  label="详细的工作地址或家庭住址" />
<ProFormDatePicker colProps={{ span: 24 }} label="入职日期" name="date" />
```
ProFormDatePicker的宽度设定，如何指定才能生效？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


### 💡 解决方案

ProFormDatePicker 组件的 `colProps` 属性是用来设置该组件在布局中所占用的列数的。在 antd 的栅格系统中，一行被分成了 24 个列，通过 `span` 属性来指定占用的列数。

在上面的代码示例中，`colProps={{ span: 24 }}` 设置了该组件占用整个一行，因此不能生效。

要想设置 ProFormDatePicker 组件的宽度，我们可以在外层套一层 `div`，然后通过内嵌样式或者 CSS 类来设置宽度。

以下是通过内嵌样式的示例代码：

```jsx
<div style={{ width: '200px' }}>
  <ProFormDatePicker label="入职日期" name="date" />
</div>
```

以上代码中，通过给包裹 `ProFormDatePicker` 的 `div` 添加 `style={{ width: '200px' }}`，来设置组件的宽度为 200 像素。

以下是通过 CSS 类的示例代码：

```jsx
<div className="date-picker-wrapper">
  <ProFormDatePicker label="入职日期" name="date" />
</div>

// CSS
.date-picker-wrapper {
  width: 200px;
}
```

以上代码中，给包裹 `ProFormDatePicker` 的 `div` 添加了类名 `date-picker-wrapper`，然后通过 CSS 来设置该类的宽度为 200 像素。

另外，需要注意的是：在 antd 的栅格系统中，每个列的宽度不是固定的像素值，而是根据网格系统和屏幕宽度自动计算的。因此，我们可以通过自定义网格间距、断点和栅格比例来调整整个布局的响应式效果，具体可以参考 antd 官方文档。

参考文档：
- [ProFormDatePicker API 文档](https://procomponents.ant.design/components/form-cn/#ProFormDatePicker)
- [antd - 栅格系统](https://ant.design/components/grid-cn/)

**Comment by chenshuai2144** [comment]
你这个用 label width  感觉更合适一些。
colProps用起来有一写前提条件

| 字段名称 | 类型 | 说明 |
| --- | --- | --- |
| `colProps` | [ColProps](https://ant.design/components/grid/#Col) | 在开启 `grid` 模式时传递给 Col |
