### ISSUE TITLE
👑 [需求] ProLayout 扩展的 umi 的 router 配置， router的path不支持外链自适应协议

### ISSUE THREAD

**Issue by liwei511** [ant-design/pro-components#5462]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

ProLayout
 

### 🥰 需求描述

ProLayout router配置

```
export default {
  route: {
    path: '/',
    routes: [
      {
        path: '//ant.design',
        name: 'Ant Design 官网外链',
        icon: <AntDesignOutlined />,
      },
    ],
  },
  location: {
    pathname: '/',
  },
};
```

path: '//ant.design' 报错, path: 'http://ant.design' 或 path: 'https://ant.design' 正常运行。

### ⛰ 功能需求适用场景

配置外链

### 🧐 解决方案

判断path的正则修改下，使支持‘//’。

### 🚑 其他信息

无

**Comment by liwei511** [comment]
源码在这里node_modules/@ant-design/pro-layout/node_modules/@ant-design/pro-utils/lib/isUrl/index.js

```
var isUrl = function isUrl(path) {
  if (!path) return false;

  if (!path.startsWith('http')) {
    return false;
  }

  try {
    var url = new URL(path);
    return !!url;
  } catch (error) {
    return false;
  }
};
```

**Comment by chenshuai2144** [comment]
为啥不用https？
