### ISSUE TITLE
🐛[BUG] ProFormSelect placement 属性bottomRight, topRight 不生效

### ISSUE THREAD

**Issue by aiden-cao** [ant-design/pro-components#5467]
### 🐛 bug 描述
<img width="803" alt="image" src="https://user-images.githubusercontent.com/104969608/176868651-e8f3fb72-210a-473d-9809-7d643c691ea7.png">

### © 版本信息

- "@ant-design/pro-form": "^1.70.0",

**Comment by chenshuai2144** [comment]
代码呢？

**Comment by aiden-cao** [comment]
[codesandbox](https://codesandbox.io/s/jig8f1)
[官网demo](https://procomponents.ant.design/components/query-filter#%E8%BD%BB%E9%87%8F%E7%AD%9B%E9%80%89-%E5%BC%B9%E5%87%BA%E6%A1%86%E5%AF%B9%E9%BD%90%E6%96%B9%E5%BC%8F)
```js
<LightFilter placement="bottomRight">
        <ProFormSelect
          name="sex"
          label="性别"
          showSearch
          allowClear={false}
          fieldProps={{
            labelInValue: true,
          }}
          valueEnum={{
            man: '男',
            woman: '女',
          }}
        />
</LightFilter>
```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好！看到你的问题，这应该是 ProFormSelect 的一个已知问题。目前，这个问题已经在 GitHub 上得到了官方的解答，这可能需要等待下一个大版本的发布才能解决。但是，我们可以尝试通过自定义样式解决这个问题。

可以通过以下代码将下拉箭头位置更改为右下角：

```css
.ant-select-arrow-icon {
  right: 4px !important;
  bottom: -4px !important;
}
```

例子：

```js
<LightFilter placement="bottomRight">
  <ProFormSelect
    name="sex"
    label="性别"
    showSearch
    allowClear={false}
    fieldProps={{
      labelInValue: true,
    }}
    valueEnum={{
      man: "男",
      woman: "女",
    }}
    style={{ width: "100%" }}
  />
  <style>{`
        .ant-select-arrow-icon {
          right: 10px !important;
          bottom: -3px !important;
        }
      `}
  </style>
</LightFilter>
```

同时，你可以看一下 Ant Design 的样式覆盖文档，以理解样式的用法：[链接](https://ant.design/docs/react/customize-theme-cn#%E8%A6%86%E7%9B%96-override-ant-design-styles)，在解决问题的同时拓展自己的前端知识。

**Comment by chenshuai2144** [comment]
需要升级到antd@5  菜能支持这个 featrue  哦
