### ISSUE TITLE
🐛[BUG] antd pro 6，Layout 含有多级菜单的，与只有二级菜单的高度不一致

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#5468]
### 🐛 bug 描述

![微信截图_20220702165941](https://user-images.githubusercontent.com/3166799/176993968-7cccc390-c0e1-48f2-b0d0-778f050ae1f5.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。




### 解决方案

根据问题描述，可知是由于多级菜单与二级菜单的高度不一致导致的问题，建议在多级菜单中手动设置高度以保持一致性。

在 `src/layouts/BasicLayout.tsx` 文件中，可以查找到多级菜单的代码，根据需要修改样式。例如，设置所有多级菜单的高度为 `50px`：

```tsx
<Menu.SubMenu key={submenu.key} title={submenu.title}>
  {submenu.children?.map(item => (
    <Menu.Item key={item.path} icon={item.icon}>
      <Link to={item.path}>{item.title}</Link>
    </Menu.Item>
  ))}
</Menu.SubMenu>
```

```css
.ant-menu-submenu {
  height: 50px;
}
```

如果仍然存在问题，可以将多级菜单的样式与二级菜单的样式进行比较，找出差异并进行调整。

### 相关文档

- [Ant Design Pro](https://pro.ant.design/)
- [Ant Design Menu](https://ant.design/components/menu/)

**Comment by chenshuai2144** [comment]
已经修复了
