### ISSUE TITLE
🐛[BUG] playground 的依赖不对

### ISSUE THREAD

**Issue by Lantianyou** [ant-design/pro-components#5476]
## 🐛 bug 描述
文档里 codesandbox 里的依赖不太对：

没有 @ant-design/pro-components
建议 index.tsx 文件用 React 18，否则如果没有 import React from 'react' 会报错
建议 playground 不只限于 codesandbox，还可以用下更快的 StackBliz

**Comment by Lantianyou** [comment]
@chenshuai2144 方不方便指点下 doc 里 playground 的依赖在哪里配置，我去提个 PR，相信能提升很多人的文档使用体验 :)

**Comment by chenshuai2144** [comment]
我也没找到，

@PeachScript 辟起老师 看看
