### ISSUE TITLE
🐛[BUG] ProFormText 组件 addonAfter 样式问题

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#5479]
![image](https://user-images.githubusercontent.com/30397655/177142581-0240592f-3e45-47d7-b773-4c40c623609c.png)

**Comment by chenshuai2144** [comment]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/8186664/178659452-b153fc64-75d3-4e90-b4d4-32206e09f916.png">


看起来已经修复了9

**Comment by leshalv** [comment]
看着像是被修复了，但是 width 撑不起来
