### ISSUE TITLE
🧐[问题] proForm表单减小表单之间的间距，设置style={{ marginBottom: 8 }}不起作用

### ISSUE THREAD

**Issue by wooxyz** [ant-design/pro-components#5488]
### 💻 示例代码

```
ant design Form是可以设置的：<Form.Item style={{ marginBottom: 12 }}>

但是proForm表单却不行，如<ProFormText style={{ marginBottom: 12 }} />
```

### 🚑 其他信息
咋个写法？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


在 ProForm 组件中，可以通过添加 className 属性来给表单元素添加自定义的 CSS 类名，进而通过 CSS 样式来控制表单元素的样式。

具体做法如下：

1. 在 ProForm 组件中指定 className 属性，如下所示：

```
<ProFormText
  name='username'
  label='用户名'
  className='my-proform-text'
  placeholder='请输入用户名'
/>
```

2. 在 CSS 样式表中编写样式，如下所示：

```
.my-proform-text {
  margin-bottom: 8px;
}
```

这样就可以把 ProFormText 组件的底部 margin 设置为 8px 了。注意，这里不能使用 style 属性，应该使用 className 属性来指定自定义的 CSS 类名。

另外，如果您需要了解更多关于 ProForm 组件的使用方法，可以参考官方文档：https://procomponents.ant.design/components/form#proform-%E7%BB%84%E4%BB%B6

**Comment by wooxyz** [comment]
不行，你试过了吗？

**Comment by Jieshion** [comment]
可以试试formItemProps={{ style: { marginBottom: '10px' } }}

**Comment by heyhealth** [comment]
> 可以试试formItemProps={{ style: { marginBottom: '10px' } }}

请教下，新版本没有这个参数了吗？
