### ISSUE TITLE
🧐[问题]主站组件数据展示部分代码展开显示不正常。

### ISSUE THREAD

**Issue by snowwindsand** [ant-design/pro-components#5490]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

主站的“组件”的“数据展示”部分一些组件的代码展开有问题。

### 💻 示例代码

无

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/13346090/177440709-416df4bf-088c-4269-aacc-e582662ad444.png)

**Comment by mt0129** [comment]
同上，什么情况

**Comment by TUZI2018QH** [comment]
对头

**Comment by xuan085** [comment]
+1，而且页面宽度也变小了

**Comment by abbottjjj** [comment]
+1

**Comment by Sheepeer** [comment]
![image](https://user-images.githubusercontent.com/78125933/177453211-be0a164f-bfa9-418e-9912-191436bada05.png)

**Comment by jeryqwq** [comment]
![image](https://user-images.githubusercontent.com/25569373/177456856-6c29b49e-e867-4b9f-939e-1b519c58501c.png)
为啥外层div要给一个计算的高度呢

**Comment by tong233** [comment]
暂时用 https://next-procomponents.ant.design/components

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题可能是由于使用了错误的CSS样式，导致了组件的展示出现了问题。最好的解决方案是检查组件的CSS样式，找到出现问题的元素，并对其进行调整。可以尝试将该元素的position属性设置为relative或unset，或者对其它可能影响该元素显示的属性进行调整。同时，也需要注意该元素是否有父元素的尺寸过小，导致该元素的溢出。  

至于页面的宽度变小了的问题，可能是由于某些父元素的设置或者某些组件的样式导致的，可以尝试去除外层div的高度计算样式，或者查看代码中是否有其他的样式可能会造成宽度变小的问题。 

如无法准确定位问题的根源，也可尝试使用其他可靠的组件库，比如Ant Design Pro Components，它的组件都有官方支持和优秀的代码质量。拥有官方的支持，也更容易定位和解决问题。同时也可参考其它网站的代码实现，学习到更多的前端技巧。

**Comment by chenshuai2144** [comment]
修复啦
