### ISSUE TITLE
🧐好奇为什么renderFormItem里的组件，在收起和打开的时候会被重载

### ISSUE THREAD

**Issue by lirl-cn** [ant-design/pro-components#5494]
### 🧐 问题描述

在开发中发现，renderFormItem里的组件里自带接口请求获取数据的话，在收起和打开搜索项时会再次触发请求，useEffect return function里的日志会被打印出来，说明是被卸载了，但是页面明明是组件节点还在，父级元素display: none，好奇为啥会触发

<img width="837" alt="image" src="https://user-images.githubusercontent.com/23329045/177518241-1acae817-cd78-4d6c-aa63-2df8e7217193.png">
<img width="456" alt="image" src="https://user-images.githubusercontent.com/23329045/177518494-3bf184fc-288c-4c84-9a7b-2f8285ee7ba5.png">
<img width="1750" alt="image" src="https://user-images.githubusercontent.com/23329045/177518618-3eb305e1-8f2a-4585-9dcd-fc232679a976.png">
页面引入了三个组件，所以打印了3次；
<img width="568" alt="image" src="https://user-images.githubusercontent.com/23329045/177518862-7f672595-cb82-409c-91f5-b21746c8d5c4.png">
元素还在的

**Comment by lirl-cn** [comment]
是被改了key吗

**Comment by lirl-cn** [comment]
是被改了key吗

**Comment by lirl-cn** [comment]
@chenshuai2144

**Comment by lirl-cn** [comment]
@sorrycc

**Comment by lirl-cn** [comment]
> 收起的时候就被销毁掉了，query 的实现逻辑

有没有暴露出api或者参数啥的可以让我去优化吗？不想每次都被销毁

**Comment by jeryqwq** [comment]
@lirl-cn 外部存住这个vdom对象就行了，let _temp  = <CnSearchSelect />,  然后直接返回_temp
