### ISSUE TITLE
🐛[BUG] Field valueType='money' 时设置 moneySymbol 无效

### ISSUE THREAD

**Issue by sakura-flutter** [ant-design/pro-components#5496]
### 🐛 bug 描述

Field valueType='money' 时设置 moneySymbol 无效，无论 moneySymbol 的值为布尔或是字符串。
还有就是 moneySymbol 设置为 false 是不显示符号的意思？用了好像没有生效。

### 📷 复现步骤

ProDescriptions columns：
``` 
{
              title: 'money',
              key: 'money',
              dataIndex: 'money',
              valueType: 'money',
              fieldProps: {
                moneySymbol: '$',
              },
 }
```

### 🏞 期望结果

符号 ￥ 应该显示为 $ 

### 💻 复现代码

官网的例子
https://procomponents.ant.design/components/descriptions#columns-配置

另外，在这里的例子中 valueType='money' 时 moneySymbol 的 ￥ 符号没有显示出来，编辑时的输入框倒是有的
https://procomponents.ant.design/components/descriptions/#可编辑的定义列表

### © 版本信息

- 浏览器环境 chrome 103.0.5060.66
- 开发环境 win11

### 🚑 其他信息

![微信截图_20220706181412](https://user-images.githubusercontent.com/28331128/177527882-28d27dfb-feff-4e70-ac8f-01bce535184b.png)

**Comment by chenshuai2144** [comment]
ref in https://github.com/ant-design/pro-components/commit/398415cd79318d6e56340d0a60f5d5bea40c0684

**Comment by chenshuai2144** [comment]
配置一下 moneySymbol=en-US
