### ISSUE TITLE
🐛[BUG] 国际化设置

### ISSUE THREAD

**Issue by singingBoy** [ant-design/pro-components#55]
### 🐛 bug 描述

官网例子：
![image](https://user-images.githubusercontent.com/22296047/88784321-7da44680-d1c2-11ea-9c6e-b476e0e115ee.png)

项目使用：
![image](https://user-images.githubusercontent.com/22296047/88784669-e390ce00-d1c2-11ea-8910-0e8f54711c73.png)

### 📷 相关代码

````

var IntlContext = _react.default.createContext(intlMap[(0, _util.getLang)() || ''] || zhCNIntl);

<IntlProvider value={zhCNIntl}>
      <ProTable {...props} />
</IntlProvider>

````

### 🏞 期望结果

期望表现与antd-pro官方例子

### © 版本信息

- Ant Design Pro-table 版本: 2.4.4
- umi 版本 3.2.4
- 浏览器环境 Google Chrome 78.0.3904.108
- 开发环境 [win10]

**Comment by chenshuai2144** [comment]
dumi 没有默认用 antd 的 config 包了一下。
在 umi 中使用会自动包，不用担心的

**Comment by johnnylc** [comment]
> dumi 没有默认用 antd 的 config 包了一下。
> 在 umi 中使用会自动包，不用担心的

在使用cra搭建框架时，没有使用umi脚手架，ProTable的国际化存在问题，ProTable内组件不受antd ConfigProvider设置控制。

如下示例，外层使用antd ConfigProvider设置locale为zhCN，Empty与Table为antd组件，ProTable为@ant-design/pro-table组件。

```
        <ConfigProvider locale={zh_CN}>
          <Space direction='vertical' style={{width: '100%'}}>
            <Empty />
            <Table dataSource={[]} columns={columns} />
            <ProTable dataSource={[]} headerTitle='Pro-table' columns={columns} search={false}/>
          </Space>
        </ConfigProvider>
```

以上示例渲染结果如下图：
![image](https://user-images.githubusercontent.com/12717523/88929758-24651180-d2ad-11ea-9684-c4276350c80a.png)

结果中，antd组件的国际化为中文，但是ProTable的国际化仍为英语。
请问如何在不使用umi时解决ProTable的国际化问题？

**Comment by AaronTon** [comment]
我也出现这个问题，用的也是cra脚手架搭的，需要解决方法！

**Comment by shenjo** [comment]
我看了下代码，目前我得到的结论大致是pro-table当前使用的antd（4.1.5）版本的问题

当我把pro-table的源代码拷贝到项目中时，国际化一切正常，但是切到包依赖就有问题（我的项目中使用的antd是最新的antd 4.5.3)
![image](https://user-images.githubusercontent.com/13912646/89253736-06523500-d650-11ea-8ce3-56ba0fb14cf4.png)

看代码的过程中，还发现如下问题
1. 查询条件【查询】【重置】按钮始终是英文
原因：在intlContext中，是这样定义的
![image](https://user-images.githubusercontent.com/13912646/89253633-b8d5c800-d64f-11ea-845a-5c1616c5f3d9.png)
其中使用的getLang() 方法
![image](https://user-images.githubusercontent.com/13912646/89253653-ca1ed480-d64f-11ea-8ad8-cf4d9f472857.png)
会在navigator.language上添加一个{{xxx}}导致intlMap找不到这样的key,所以默认中文



@chenshuai2144

**Comment by chenshuai2144** [comment]
我在最近的脚本里面删除了这个方法，全部使用了 antd 类似的 key，应该可以解决这个问题

**Comment by glzcc** [comment]
我也遇到了同样的问题，独立引入的proTable，proTable为英文显示，其他ant控件都是中文

**Comment by 4tj** [comment]
遇到同样问题还没解决，主要在2个点上不能接受：
1.如果在最外层包裹了Antd的 `<ConfigProvider locale={zhCN}/>` 时，ProTable会**直接报错** `Cannot read property 'locale' of undefined`。
2.即便在ProTable外层再次包裹一次来自ProTable包的`ConfigProvider`，涉及form内的如DatePicker之类的都还是英文。官方实例上也是这样。

**Comment by chenshuai2144** [comment]
@4tj 你是不是使用了不同的 包类型。 protable 会用 es 的，你是不是使用了lib 的 ConfigProvider

**Comment by 4tj** [comment]
> @4tj 你是不是使用了不同的 包类型。 protable 会用 es 的，你是不是使用了lib 的 ConfigProvider

我后来定位出了问题现象，antd 和 pro最新版情况下，使用了babel-plugin-import动态载入antd，会导致国际化报错。原因未知

**Comment by liuweiGL** [comment]
加油改下呀~

**Comment by 4tj** [comment]
> 加油改下呀~

我自己后来定位出了问题，其实是babel-plugin-import。不过这里的确对于非umi方案不太友好

**Comment by 4tj** [comment]
> 请问有解决方法吗？

可以尝试先去掉babel-plugin-import看看是否正常。

**Comment by liuweiGL** [comment]
那我还是选择先不国际化~

**Comment by liuweiGL** [comment]
说下解决方法：
1. 在 `dist\table.js` 中复制对应的语言配置：
```ts
const zhCN = {
  moneySymbol: '￥',
  form: {
    lightFilter: {
      more: '更多筛选',
      clear: '清除',
      confirm: '确认',
      itemUnit: '项'
    }
  },
  tableForm: {
    search: '查询',
    reset: '重置',
    submit: '提交',
    collapsed: '展开',
    expand: '收起',
    inputPlaceholder: '请输入',
    selectPlaceholder: '请选择'
  },
  alert: {
    clear: '清空',
    selected: '已选择',
    item: '项'
  },
  pagination: {
    total: {
      range: '第',
      total: '条/总共',
      item: '条'
    }
  },
  tableToolBar: {
    leftPin: '固定在列首',
    rightPin: '固定在列尾',
    noPin: '不固定',
    leftFixedTitle: '固定在左侧',
    rightFixedTitle: '固定在右侧',
    noFixedTitle: '不固定',
    reset: '重置',
    columnDisplay: '列展示',
    columnSetting: '列设置',
    fullScreen: '全屏',
    exitFullScreen: '退出全屏',
    reload: '刷新',
    density: '密度',
    densityDefault: '正常',
    densityLarger: '默认',
    densityMiddle: '中等',
    densitySmall: '紧凑'
  }
}

const zhCNIntl = createIntl('zh_CN', zhCN)

export default zhCNIntl
```
2. App.tsx ：
```tsx
import React from 'react'

import { UseRequestProvider } from '@ahooksjs/use-request'
import { BaseOptions } from '@ahooksjs/use-request/lib/types'
import { IntlProvider, zhCNIntl } from '@ant-design/pro-table'
import { ConfigProvider as AntdConfigProvider } from 'antd'
import zhCN from 'antd/es/locale/zh_CN'
import { BrowserRouter } from 'react-router-dom'
import 'src/components/Formily/setup'

import { ConfigProvider } from 'src/context/config'
import { UserProvider } from 'src/context/user'
import fetcher from 'src/lib/fetcher'
import Router from 'src/router'
import 'src/style'

import API from './services'

window.apis = API

const useRequestConfig: BaseOptions<unknown, string[]> = {
  manual: true,
  requestMethod: fetcher.request
}

const App: React.FC = () => {
  return (
    <UserProvider>
      <ConfigProvider>
        <AntdConfigProvider locale={zhCN}>
          <IntlProvider value={{ intl: zhCNIntl }}>
            <UseRequestProvider value={useRequestConfig}>
              <BrowserRouter>
                <Router />
              </BrowserRouter>
            </UseRequestProvider>
          </IntlProvider>
        </AntdConfigProvider>
      </ConfigProvider>
    </UserProvider>
  )
}
export default App

```

**Comment by liuweiGL** [comment]
依赖：
```json
  "dependencies": {
    "@ant-design/icons": "^4.2.2",
    "@ant-design/pro-layout": "^6.4.18",
    "@ant-design/pro-table": "^2.7.4",
    "@formily/antd": "^1.3.2",
    "@formily/antd-components": "^1.3.2",
    "ahooks": "^2.6.0",
    "antd": "^4.6.2",
    "axios": "^0.20.0",
    "classnames": "^2.2.6",
    "craco-less": "^1.17.0",
    "dayjs": "^1.8.34",
    "lodash-es": "^4.17.15",
    "query-string": "^6.13.2",
    "react": "^16.13.1",
    "react-contexify": "^4.1.1",
    "react-dom": "^16.13.1",
    "react-helmet-async": "^1.0.6",
    "react-router-dom": "^5.2.0",
    "styled-components": "^5.2.0"
  }
```
craco.config.js：
```nodejs
/* eslint-disable @typescript-eslint/no-var-requires */
const AntdDayjsWebpackPlugin = require('antd-dayjs-webpack-plugin')
const CracoAntDesignPlugin = require('craco-antd')

module.exports = {
  devServer: {
    writeToDisk: true
  },
  plugins: [
    { plugin: CracoAntDesignPlugin },
    {
      plugin: AntdDayjsWebpackPlugin
    }
  ]
}
```

**Comment by liuweiGL** [comment]
#### 版本
```json
{
 "@ant-design/pro-table": "^2.8.1"
}
```

#### App.tsx
```ts
import React from 'react'

import { UseRequestProvider } from '@ahooksjs/use-request'
import { BaseOptions } from '@ahooksjs/use-request/lib/types'
import { ConfigProvider as AntdConfigProvider } from 'antd'
import zhCN from 'antd/es/locale/zh_CN'
import { BrowserRouter } from 'react-router-dom'

import fetcher from 'src/lib/fetcher'
import Router from 'src/router'
import 'src/style'

import LayoutSwitch from './layouts/LayoutSwitch'


const useRequestConfig: BaseOptions<unknown, string[]> = {
  manual: true,
  requestMethod: fetcher.request
}

const App: React.FC = () => {
  return (
        <AntdConfigProvider locale={zhCN}>
          <UseRequestProvider value={useRequestConfig}>
            <BrowserRouter>
              <LayoutSwitch>
                <Router />
              </LayoutSwitch>
            </BrowserRouter>
          </UseRequestProvider>
        </AntdConfigProvider>
  )
}

export default App
```

#### 问题
分页组件国际化不完全：
![image](https://user-images.githubusercontent.com/21048878/94326988-a5553680-ffda-11ea-995d-7d5b38c077ce.png)

#### 其他
是需要额外配置什么吗？

**Comment by arifszn** [comment]
![image](https://user-images.githubusercontent.com/45073703/95870827-c49be400-0d8e-11eb-9547-d8f3962ecf6f.png)

I can not convert the placeholder to English.  My code is as following:
```
<ConfigProvider locale={enUS}>
   <ProTable
    ......
    />
</ConfigProvider>
```

**Comment by caro-li** [comment]
所以，这个问题到底怎么解决！前面这么多不同的看法，哪个有权威的解释一下

**Comment by YanYuanFE** [comment]
我也遇到这个问题，"@ant-design/pro-layout": "^6.9.0",
    "@ant-design/pro-table": "^2.17.0","antd": "^4.9.4", 解决办法是修改babel-plugin-import的babel配置，
```
["import", {
        "libraryName": "antd",
        "libraryDirectory": "es",
        "style": true
      }
```
libraryDirectory修改lib为es，ok

**Comment by leohxj** [comment]
如果使用了 `babel-plugin-import` 动态加载 antd 的话, 默认是从 `lib` 目录加载文件.

但 pro-components 被构建的时候,一般是读取 `module` 字段, 对应了 `es` 目录文件, 导致了组件获取 antd ConfigProvider 上下文为 null ,从而使用了默认的中文文案.

解决方法就是设置 `libraryDirectory` 为 `es`!!!

懂的点个赞.

**Comment by hsbtr** [comment]
> 如果使用了 `babel-plugin-import` 动态加载 antd 的话, 默认是从 `lib` 目录加载文件.
> 
> 但 pro-components 被构建的时候,一般是读取 `module` 字段, 对应了 `es` 目录文件, 导致了组件获取 antd ConfigProvider 上下文为 null ,从而使用了默认的中文文案.
> 
> 解决方法就是设置 `libraryDirectory` 为 `es`!!!
> 
> 懂的点个赞.

这个方案在DateTime组件中不好使
