### ISSUE TITLE
👑 [需求] EditableProTable 支持 requiredMark

### ISSUE THREAD

**Issue by bowencool** [ant-design/pro-components#5504]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

EditableProTable

### 🥰 需求描述

像 Form 组件一样，通过 [requiredMark](https://ant.design/components/form-cn/#components-form-demo-required-mark) 自动在 label 前面添加红色*必填样式
![image](https://user-images.githubusercontent.com/20217146/177913387-009aeda3-e038-4c01-ace1-30946940e845.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


针对这个需求，可以通过在 EditableProTable 组件中实现类似 Form 组件的 requiredMark 功能。具体实现步骤如下：
1. 在 EditableProTable 组件 props 中新增 requiredMark 属性，并默认为 false，用于控制是否显示 required 标识。
2. 在 renderFormItem 方法中，通过 getFieldProps 获取表单项属性 props，然后根据 requiredMark 为 true 的情况，在表单项 label 前面添加一个红色的 * 必填标识。
例如：

```jsx
renderFormItem = ({ dataIndex, record, editing, type, ...restProps }) => {
  const handleChange = (value) => {
    const { onChange } = this.props;
    if (onChange) {
      onChange(record?.[this.keyField], dataIndex, value);
    }
  };
  const { requiredMark } = this.props;
  const formItemProps = getFieldProps(restProps);
  return (
    <Form.Item
      {...formItemProps}
      label={
        <span>
          {restProps.title}
          {requiredMark && <span style={{ color: 'red' }}>*</span>}
        </span>
      }
      name={dataIndex}
      rules={restProps.rules}
      key={dataIndex}
    >
      {/*渲染对应的输入组件*/}
    </Form.Item>
  );
};
```

这样就可以在 EditableProTable 组件中增加 requiredMark 属性并控制是否显示必填标识了。

参考文档：
- [Ant Design Form](https://ant.design/components/form-cn/)
- [React 表单相关的属性及方法](https://zh-hans.reactjs.org/docs/forms.html)

**Comment by chenshuai2144** [comment]
这个没有很好的地方实现，没法做
