### ISSUE TITLE
🧐[问题] ProDescriptions 使用 request 返回 success: false 后无法再触发 request

### ISSUE THREAD

**Issue by sakura-flutter** [ant-design/pro-components#5506]
### 🧐 问题描述

ProDescriptions 使用 request 返回 success: false 后无法再触发 request。
调用 actionRef.current?.reload() 或者改变 params 参数都不能让 request 执行。
是刻意为之还是 bug 呢？
返回 success:false 骨架屏一直显示，但再次 request 返回 true 时应该关闭骨架屏并正常显示数据会不会好一点
在 ProTable 返回 success: false 并没有这个问题的

### 💻 示例代码

https://codesandbox.io/s/yuan-cheng-qing-qiu-shu-ju-forked-301tef?file=/App.tsx

**Comment by Statfine** [comment]
应该是失败的场景下request的loading状态没变更，导致不能再次进行请求
