### ISSUE TITLE
🐛[BUG] ProTable 官方文档中第一个 查询表格示例，表格筛选莫名消失

### ISSUE THREAD

**Issue by thefakeworld** [ant-design/pro-components#5507]
官网文档地址：

https://procomponents.ant.design/components/table/#%E6%9F%A5%E8%AF%A2%E8%A1%A8%E6%A0%BC

### 💻 复现代码

![image](https://user-images.githubusercontent.com/17455100/177946235-5659f7b8-0bb5-4ac0-9b77-5e83bfab5fe6.png)
### 屏幕宽度大于 1317会发现创建时间筛选项消失了
![image](https://user-images.githubusercontent.com/17455100/177946376-c05efd82-d885-4fa2-b7cd-eb7271380f78.png)

**Comment by Phecda** [comment]
大概是因为这个 https://github.com/ant-design/pro-components/commit/a3758b019665d7c707ebad2991fbfc5f09de47c2

**Comment by sushi-su** [comment]
同遇到这个问题，暂时先回退到 1.1.6 版本了

**Comment by chenshuai2144** [comment]
是 bug  已经修复了
