### ISSUE TITLE
SchemaForm layoutType 设为 ModalForm或DrawerForm时 设置destroyOnClose 有bug🐛[BUG]

### ISSUE THREAD

**Issue by Vermouth-vi** [ant-design/pro-components#5508]
### 🐛 bug 描述

如题，第一次打开弹窗或抽屉，表单正常加载，如果设置了destroyOnClose，关闭后再次打开，表单消失

### © 版本信息

- "@ant-design/pro-form": "^1.67.1",

**Comment by chenshuai2144** [comment]
升级一下antd的版本。

建议清空依赖，`git clean -dfx`
