### ISSUE TITLE
🧐[问题]ant4.0之前版本如何使用pro-components

### ISSUE THREAD

**Issue by TUZI2018QH** [ant-design/pro-components#5509]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
求助一下，antd4.0之前的项目想要使用pro-components该怎么操作，能用不？antd版本升不了，影响范围太大

**Comment by chenshuai2144** [comment]
不要挣扎了，早点升级吧，antd5都要出来了
