### ISSUE TITLE
👑 [需求]请问ProTable能提供 Table组件的components API 覆盖默认的 table 元素吗

### ISSUE THREAD

**Issue by liezh** [ant-design/pro-components#551]
### 🥰 需求描述

现在我需要做一些类似于拖拽调整table布局的功能（如伸缩列，拖拽调整列顺序等），但是ProTable似乎没有提供，像antd Table组件的components这样的API所以我没办法使用ProTable完成类似的需求。

### 🧐 解决方案

像antd Table 组件提供components API 用于扩展

### 🚑 其他信息

如果有其他的解决方案，请告知

**Comment by chenshuai2144** [comment]
ProTable 支持 antd table的所有 api，你可以把它当作antd 的table 来用
