### ISSUE TITLE
🐛[BUG] ProTable 无法获取 EditableFormInstance

### ISSUE THREAD

**Issue by Dreamcreative** [ant-design/pro-components#5510]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

给 ProTable 组件设置 editable 属性，通过 editable.formProps 设置formRef 获取当前可编辑列的 form 实例。获取到的是一个通用的 formInstance。
而可编辑表格的 formInstance 拥有独特的三个 方法getRowData、getRowsData、setRowData。通过 ProTable 的 editable.formProps 获取到的 formInstance 没有这三个方法

### 📷 复现步骤

1. 打开复现链接
2. 进入页面后，打开 console
3. 点击表格操作栏的 编辑 按钮
4. 点击 获取formInstance 按钮
5. 在 console 中可以看到当前可编辑列的 formInstance

### 🏞 期望结果

期望 ProTable 可以获取 EditableFormInstance ,而不是通用的 formInstance

### 💻 复现代码
[复现链接](https://codesandbox.io/s/protable-huo-qu-editable-ke-bian-ji-biao-ge-de-forminstance-m9d61y?file=/App.tsx)

### © 版本信息

- ProComponents 版本: 1.1.8
- umi 版本
- 浏览器环境 版本 103.0.5060.53（正式版本） (x86_64)
- 开发环境 mac OS 10.15.7

**Comment by fsrm365** [comment]
我看了你的代码。
1、EditableFormInstance是EditableProTable才有的。而不是ProTable。
2、EditableFormInstance这个ref，是EditableProTable的，而不是EditableProTable的editable
明白了吗？
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/5212478/211544653-95cd111e-0841-4bf6-88f9-fa5a4a74af6e.png">
