### ISSUE TITLE
🐛[BUG]官网例子为什么没有分页下拉框了，，超过50条就有了

### ISSUE THREAD

**Issue by wanxiaoshengwanxiaosheng** [ant-design/pro-components#5511]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/89174214/178130786-febc6266-0c96-4450-a2de-fdfc8e9958a4.png)

**Comment by PisecesPeng** [comment]
这是 [Pagination分页](https://ant.design/components/pagination-cn) 的默认配置.
<img width="629" alt="image" src="https://user-images.githubusercontent.com/29013341/178172008-7ea7ce4b-2b69-478b-8a7c-f98e3c1ba9b5.png">
默认是`小于50时, 隐藏切换器的`, 你可以在`ProTable`的`pagination`属性里配置.
