### ISSUE TITLE
🧐[问题] ProTable 的 request ，当接口失败的时候是否可以更新dataSource为空

### ISSUE THREAD

**Issue by dcycurry** [ant-design/pro-components#5512]
### 🧐 问题描述

ProTable 的 request ，当接口失败的时候是否可以更新dataSource为空
比如：
1. 先输入正确的搜索信息，搜出了20条结果
2. 输入错误的信息，使接口报错，这时依然显示之前的20条结果

### 💻 示例代码
```
request={async (params = {}) => {
    return listTables(params)
      .then(({ data, errCode }) => {
        const { totalCount, list } = data;
        return { data: list, success: true, total: totalCount };
      })
      .catch(() => {
        return { success: false, data: [], total: 0 };
      });
  }}
```

**Comment by chenshuai2144** [comment]
自定义处理一下错误吧。

这个需求很奇怪呀，出现了异常就应该清空数据的，不然可能展示一些错误的信息上去

**Comment by dcycurry** [comment]
> 自定义处理一下错误吧。
> 
> 这个需求很奇怪呀，出现了异常就应该清空数据的，不然可能展示一些错误的信息上去

我就是要清空数据，我在catch里设置data: [], 没有效果

**Comment by dcycurry** [comment]
https://codesandbox.io/s/cha-xun-biao-ge-forked-6gzi6v?from-embed=&file=/App.tsx
这是一个例子，count===3时, { success: false, data: [] }, 没有清空数据
如果改成{ success: true, data: [] }， 则清空数据了，也就正常了
@chenshuai2144
