### ISSUE TITLE
🧐[问题]项目中用了多个ProTable，搜索表单的按钮key值都是相同的，哪里可以配置每个按钮的key值

### ISSUE THREAD

**Issue by 1040961807** [ant-design/pro-components#5514]
🧐 问题描述

项目中用了多个ProTable，搜索表单的按钮key值都是相同的，请问哪里可以配置每个按钮的key值？

🚑 其他信息
![lQLPJxZ8QMTmRKnNAZ_NA9CwE4cCOubfYdICzKR19cAnAA_976_415](https://user-images.githubusercontent.com/44770447/178214375-b61c1f26-06e1-4aaa-8397-1f0cdf7b385d.png)

**Comment by chenshuai2144** [comment]
保证每个Table  中唯一就行了，不用这么复杂
