### ISSUE TITLE
PageContainer无法设置自己的高度

### ISSUE THREAD

**Issue by dhj99116** [ant-design/pro-components#5515]
### 🔩 所属模块或组件

PageContainer

### 🥰 需求描述

无法给PageContainer组件设置高度，只能靠子元素高度撑起

### ⛰ 功能需求适用场景

需要给pageContainer设置背景图沾满整个内容区域

**Comment by chenshuai2144** [comment]
可以  vh  来设置的，是支持的。推荐设置最小值，不然会导致滚动条不在 body 上
