### ISSUE TITLE
🧐[问题] ModalForm 重置表单行为和文档中不一致

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/pro-components#5516]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

https://github.com/ant-design/pro-components/blob/0a2393aa87d75824c98fa58e7bd513d97d12a5a2/packages/form/src/layouts/ModalForm/index.tsx#L209-L217

此处代码只要返回`true`既重置表单，这和文档中有差异

![image](https://user-images.githubusercontent.com/23520283/178248627-e028b620-e155-4974-8226-8cfe938f4352.png)

这样想要在`onFinish`后保留表单内容只能返回`false`并手动关闭`Modal`

**Comment by Cmc0** [comment]
对的，我也遇到了，确实不生效

**Comment by lahvey** [comment]
是的，即使配置了`destroyOnClose: false`，`onFinish`返回true也会重置表单
