### ISSUE TITLE
🧐[问题]Editable行数变多后，会有延迟卡顿

### ISSUE THREAD

**Issue by charminghiker** [ant-design/pro-components#5517]
如官方例子
https://codesandbox.io/s/q5virj?file=/App.tsx

当修改数据为200行后，删除一行会出现明显卡顿。

放在本地项目中，因列数较多，30行卡顿就非常明显了。

请问大佬们，这种卡顿有没有好的解决方式。

**Comment by wenhuacode** [comment]
我也有这个问题

**Comment by charminghiker** [comment]
@chenshuai2144 请问一下有什么好的解决方式吗

**Comment by chenshuai2144** [comment]
暂时没什么好办法，antd的table 还不支持虚拟化。要自己做很多复杂的功能
