### ISSUE TITLE
👑 [需求]protable的列展示配置，能否增加控制是否展示全选按钮或者配置列展示的列表项有哪些

### ISSUE THREAD

**Issue by s464446877** [ant-design/pro-components#5518]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

protable

### 🥰 需求描述

在列展示里面，增加属性控制全选按钮是否展示和列展示列表内容

### ⛰ 功能需求适用场景

有些场景需要某些列不能被隐藏，必须要保留，可以通过隐藏全选按钮然后用目前受控模式操作或者列展示列表是受控的，某些列不在列展示里显示

**Comment by chenshuai2144** [comment]
可以在 stateMap  中配置 disable
