### ISSUE TITLE
👑 [需求]layout 设置成mix后，点击一级菜单，能否默认选择第一个子菜单，而不是空白页

### ISSUE THREAD

**Issue by JaylanChen** [ant-design/pro-components#553]
### 🥰 需求描述

layout 设置成mix后，点击一级菜单，能否默认选择第一个子菜单，而不是空白页

如果第一个子菜单，又包含子菜单，则选中它的第一个子菜单， 简而言之，选中第一个  `末级菜单`

**Comment by chenshuai2144** [comment]
我们不会做这个的，可以在 config 中配置的 重定向，我们很难知道第一个到底是不是你真的想去的

**Comment by JaylanChen** [comment]
比如菜单根据权限走的，不同用户权限，菜单不一样，很难通过config配置 重定向，固定某个菜单 解决；

比如第一个不是想要的，就切换想要的菜单呗；因为mix，菜单分开了，不点击，无法知道子菜单，只能点开，才知道左侧子菜单，但显示空白页面 体验不是很好。

对于这种情况，你有什么建议？

**Comment by zhouLJ-ww** [comment]
请问这个有好的解决方案了吗，空白页体验真的不是很好

**Comment by zhouLJ-ww** [comment]
如果使用redirect相当于写死了，如果写死的那个设置了没有权限，将显示403，不设置redirect将会空白页，请问有好的解决方案吗
