### ISSUE TITLE
使用valueTypeMap自定义valueType后，使用valueType时typescript会警告

### ISSUE THREAD

**Issue by weiguangchen** [ant-design/pro-components#5531]
![image](https://user-images.githubusercontent.com/20532969/178623979-0e16ed04-1576-410f-8bec-43855de7d5ce.png)

![image](https://user-images.githubusercontent.com/20532969/178623953-3c5d18bb-798a-496d-8a05-c6712682d78f.png)

**Comment by Nicolana** [comment]
mark一下，我也遇到了类似的问题

**Comment by chenshuai2144** [comment]
记得把类型注入一下。

`const columns: ProColumns<GithubIssueItem, 'image'>[];`
