### ISSUE TITLE
🧐antd外层ConfigProvider配置了中文语言，里面使用了pro-components的EditableProTable却仍是英文语言

### ISSUE THREAD

**Issue by 1246365871** [ant-design/pro-components#5532]
### 🧐 问题描述

在antd外层ConfigProvider配置了中文语言，antd正常的日期组件是中文，但里面使用了pro-components的EditableProTable日期却仍是英文。
![image](https://user-images.githubusercontent.com/14016747/178637840-69622972-be4f-4842-9355-e53ed1ae1162.png)
尝试网上搜了各种方法都无法解决，自己尝试更换pro-components版本（^1.1.6 -> 1.1.5），里面的日期英文却好了一半。
![image](https://user-images.githubusercontent.com/14016747/178637869-4f39451c-9f07-4a2e-8fcb-755a92a2be02.png)

### 💻 示例代码

package.json:
    "@ant-design/pro-components": "^1.1.6",
    "@ant-design/pro-table": "2.56.3",
    "antd": "^4.21.2",
    "react": "^17.0.2",

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/14016747/178636313-6b97fbca-6b5b-429c-8730-007015ab58be.png)
![image](https://user-images.githubusercontent.com/14016747/178636511-4285bd8a-1fdb-419e-b7a4-28ae5df952a3.png)
![image](https://user-images.githubusercontent.com/14016747/178636466-cad77390-2006-4d4f-82f5-4f0934c099c2.png)
![image](https://user-images.githubusercontent.com/14016747/178636571-430b49b7-fa3b-4f4c-8e0c-bd7a984bcf0f.png)

**Comment by hejinguo** [comment]
+1

**Comment by lilililee** [comment]
+1

"@ant-design/pro-components": "2.3.36",
"antd": "5.0.3",

![image](https://user-images.githubusercontent.com/24242242/205051386-5c0c3c65-a377-4149-a94c-928148025eb4.png)

**Comment by chenshuai2144** [comment]
umi 已经修复了，大家可以直接在 locale中设置了，同时也会处理 dayjs的问题
