### ISSUE TITLE
🧐[问题] ProTable<TableListItem> TS 报错

### ISSUE THREAD

**Issue by BianXuerui** [ant-design/pro-components#5537]
提问前先看看：

### 🧐 问题描述

复制官方的例子，<ProTable    <      TableListItem>

这个符号TS报错

### 💻 示例代码
<ProTable<TableListItem>
            formRef={ref}
            columns={columns}
            request={() =>
                Promise.resolve({
                    data: tableListDataSource,
                    success: true,
                })
            }
            rowKey="key"
            .....

### 🚑 其他信息

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/50104688/178883320-131afa14-d603-4474-9601-e1b218ee65c0.png">

**Comment by liangchaofei** [comment]
> 提问前先看看：
> 
> ### 🧐 问题描述
> 复制官方的例子，<ProTable < TableListItem>
> 
> 这个符号TS报错
> 
> ### 💻 示例代码
> <ProTable formRef={ref} columns={columns} request={() => Promise.resolve({ data: tableListDataSource, success: true, }) } rowKey="key" .....
> 
> ### 🚑 其他信息
> <img alt="image" width="1083" src="https://user-images.githubusercontent.com/50104688/178883320-131afa14-d603-4474-9601-e1b218ee65c0.png">

贴个在线地址看下？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


很抱歉，没有给出该在线地址，可以提供一下吗？

**Comment by chenshuai2144** [comment]
要在  tsx  中使用
