### ISSUE TITLE
🐛[BUG] 官网的EditableProTable【有子列的表格增加】的demo，点击新增时第一个列的Input显示异常

### ISSUE THREAD

**Issue by zXuff** [ant-design/pro-components#5539]
### 🐛 bug 描述

 官网的EditableProTable【有子列的表格增加】的demo，点击新增时第一个列的Input显示异常

### 📷 复现步骤

官网的EditableProTable【有子列的表格增加】的demo，点击新增，查看第一个列的Input，位置异常

### 🏞 期望结果

正常显示

### 💻 复现代码

https://procomponents.ant.design/components/editable-table#有子列的表格增加

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by liangchaofei** [comment]
> 

异常具体是指什么地方不正常？可以截图发下

**Comment by zXuff** [comment]
> > 
> 
> 
> 
> 异常具体是指什么地方不正常？可以截图发下

![Uploading 179150197...]()

**Comment by zXuff** [comment]
![image](https://user-images.githubusercontent.com/37427840/179150300-48873f48-ea9c-40ce-afd9-f3f2f1a4a107.png)

**Comment by zXuff** [comment]
> > 
> 
> 
> 
> 异常具体是指什么地方不正常？可以截图发下

![image](https://user-images.githubusercontent.com/37427840/179150364-602575e3-613d-4aed-8b69-fd241f66b23c.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


根据您提供的截图，我能看到当您在表单的第一列中点击了“新增”，它的输入框和下拉菜单的位置都不对，导致无法正常输入或选择。这个问题可能是由于页面渲染时第一列的宽度计算错误所导致的。 

解决方案：

这个问题可以通过为第一列设置宽度来解决，可以尝试以下样式：

```css
.ant-pro-table .ant-table-thead > tr > th:first-child,
.ant-pro-table .ant-table-tbody > tr > td:first-child {
  width: 200px; /* 或者使用其他合适的宽度 */
}
```

这个样式将为表格中的每一行的第一列指定一个固定的宽度。您可以根据您的需求修改宽度。

另外，我也建议您检查一下Ant Design Pro组件库的版本，是否需要升级到最新版本。如果问题仍然存在，您可以尝试创建一个最小可行的代码示例，用于演示问题并且方便其他开发人员能够复现问题和帮助您解决问题。

**Comment by chenshuai2144** [comment]
修复了，样式问题
