### ISSUE TITLE
🧐[问题] When using ProDescription in edit or update mode, ProField values are empty.

### ISSUE THREAD

**Issue by berkaygure** [ant-design/pro-components#554]
### 🧐 问题描述

I want to use ProDescription with update or edit mode. I have created fields with mode property. It is drawing components but their values were blank.

I think They should be filled by renderText or dataIndex property.

### 💻 示例代码

Here is codesandbox.
https://codesandbox.io/s/pedantic-johnson-0wcb1?file=/src/App.js

**Comment by chenshuai2144** [comment]
yep

**Comment by chenshuai2144** [comment]
this is relebase
