### ISSUE TITLE
🐛[BUG] step form步骤的图标数字不居中

### ISSUE THREAD

**Issue by simon-zhangmuye** [ant-design/pro-components#5541]
![image](https://user-images.githubusercontent.com/10706610/178897849-d1f5cac4-32dc-4c2f-879f-edec6be9e06a.png)

**Comment by liangchaofei** [comment]
> ![image](https://user-images.githubusercontent.com/10706610/178897849-d1f5cac4-32dc-4c2f-879f-edec6be9e06a.png)

贴个codeopen地址看看？

**Comment by simon-zhangmuye** [comment]
很奇怪，打开codepen之后就各种报错

**Comment by simon-zhangmuye** [comment]
![image](https://user-images.githubusercontent.com/10706610/178926816-8d75ff8e-c793-449c-bf86-c06f290d7fab.png)
