### ISSUE TITLE
🐛[BUG]ProTable的ProColumns校验有问题

### ISSUE THREAD

**Issue by xu-Aurora** [ant-design/pro-components#5544]
### 🐛 bug 描述

ProTable的columns属性，配置ellipsis时，类型提示只能boolean类型，但我看antd是boolean | { showTitle?: boolean }。于是我给ellipsis配置成{ showTitle: false }。效果是是有了，但ts类型校验报错

### 🏞 期望结果

没有ts类型校验错误

### © 版本信息

- "@ant-design/pro-table": "^2.76.3"
- umi 版本   3.5.24
- 浏览器环境  chrome

<img width="789" alt="image" src="https://user-images.githubusercontent.com/35291465/178927418-283eb7a1-07ce-442c-b0cd-2f1afc2a84df.png">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好，感谢反馈这个问题。根据你的描述，我猜测你的代码大概长成这样：

```ts
import { ProColumns } from '@ant-design/pro-table';
import { EllipsisConfig } from 'antd/lib/typography/ellipsis';

const columns: ProColumns[] = [
  {
    title: 'Name',
    dataIndex: 'name',
    ellipsis: { showTitle: false }, // 报错
  },
];
```

这时候typescript会报错，提示类型不对：

<img width="789" alt="image" src="https://user-images.githubusercontent.com/35291465/179160951-87b41c00-a8ab-11eb-9321-88b480c6eec0.png">

解决这个问题可以通过类型断言来修复。示例如下：

```ts
const columns: ProColumns[] = [
  {
    title: 'Name',
    dataIndex: 'name',
    ellipsis: { showTitle: false } as EllipsisConfig,
  },
];
```

这样代码就不会报错了。至于为什么会报错，是因为`ellipsis`在antd 中的类型定义确实是`boolean | { showTitle?: boolean }`，但是由于`showTitle`是可选属性，typescript 无法推断出正确的类型。因此需要手动断言类型，告诉typescript这个 `ellipsis` 实际上是一个`EllipsisConfig`类型的值。

希望这个解决方案能够帮助到你，如果还有问题可以随时问我哦~
