### ISSUE TITLE
🧐[问题]如何让PageContainer的高度自动占满屏幕。

### ISSUE THREAD

**Issue by simon-muyezhang** [ant-design/pro-components#5545]
![image](https://user-images.githubusercontent.com/10706610/178929245-0c309fc7-a238-40f0-b9c2-c90946612baa.png)

如果用height:"100vh"这种方法会超出

**Comment by dhj99116** [comment]
我给pageContainer设置了一个类名: page_container_box
然后一层一层的找他自动渲染的子级
.page_container_box {
  display: flex;
  flex-direction: column;
  height: 100%;

  .ant-pro-grid-content {
    flex: 1;
  }

  .ant-pro-grid-content-children,
  .ant-pro-layout-watermark-wrapper,
  .ant-pro-page-container-children-content {
    height: 100%;
  }
}
可以试试这样的方式

**Comment by simon-zhangmuye** [comment]
谢谢，我怎么忘了注入css了

**Comment by wulaizi** [comment]
> page_container_box

好像不行

**Comment by dhj99116** [comment]
@wulaizi 一层一层元素类名找下去

**Comment by wulaizi** [comment]
我给它设置了个min-height:100vh解决了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月15日(星期四) 下午5:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 🧐[问题]如何让PageContainer的高度自动占满屏幕。 (Issue #5545)





 
@wulaizi 一层一层元素类名找下去
