### ISSUE TITLE
🧐[问题] ProTable 设置搜索表单的onInit不生效？

### ISSUE THREAD

**Issue by Vermouth-vi** [ant-design/pro-components#5546]
### 🧐 问题描述

tableProps中设置 form -> onInit 但是没有执行

<ProTable
    ...
    form: {
            onInit: () => {
                console.log('init');
            },
    },
></ProTable>

是bug还是用法不对？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


### 🌈 解决方案

根据您提供的信息，可能是您的 onInit 函数格式不对导致无法执行。正确的格式应该是：

```jsx
onInit: (f) => {
    console.log('init');
    return f;
}
```
需要将表单实例返回，才能确保 onInit 函数生效。

```jsx
<ProTable
    ...
    form={{
            onInit: (f) => {
                console.log('init');
                return f;
            },
    }}
>
</ProTable>
```

此外，请确认您的表单配置是否正确，是否缺少必要的 props。可以参考 Ant Design Pro 的文档进行配置，特别是关于表单配置的部分：

- [ProTable 表单](https://pro.ant.design/components/table-cn/#%E9%AB%98%E7%BA%A7%E7%89%B9%E6%80%A7-ProTable.form)

希望这些信息对您有所帮助。

**Comment by chenshuai2144** [comment]
onInit 被我用掉了，你不能使用，你是什么场景要使用这个？
