### ISSUE TITLE
🐛[BUG] ProTable 编辑列 二级树 有状态时,无法切换全选全不选

### ISSUE THREAD

**Issue by 2218675712** [ant-design/pro-components#5547]
### 🐛 bug 描述

ProTable 编辑列 二级树 有状态时,无法切换全选全不选

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/38459269/179147931-c5852ea6-2e52-4afb-ae20-f5c6a5b6bd0e.png)

### 🏞 期望结果

点击帧率,下面的选项应该自动全选或者 全不选

**Comment by chenshuai2144** [comment]
已经修复啦
