### ISSUE TITLE
👑 [需求] ProList 设置 showActions="hover" 和 Popconfirm 配合不佳

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/pro-components#5555]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件
ProList

### 🥰 需求描述
当设置 showActions="hover" 时，鼠标移动到 action 的 popoverlay 区域时，希望保持 hover 效果

![image](https://user-images.githubusercontent.com/37258382/179328506-10a05496-cd07-4903-8902-8aab4aa46411.png)
![image](https://user-images.githubusercontent.com/37258382/179328510-8885ba8c-dd18-4c35-b832-647223e1f6b9.png)

目前只能全部展示

![image](https://user-images.githubusercontent.com/37258382/179328488-ed587502-8358-46bf-8eef-3c486e4033fa.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


根据需求描述，可以通过设置 Popconfirm 的 trigger 属性为 hover 来实现悬停显示，代码示例如下：

```jsx
import { Popconfirm } from 'antd';

<Popconfirm
  title="Are you sure to delete this item?"
  onConfirm={confirm}
  okText="Yes"
  cancelText="No"
  trigger="hover"
>
  <a href="#">Delete</a>
</Popconfirm>
```

同时需要注意的是在 ProList 中配置 Popconfirm 也要设置 trigger 属性为 hover，代码示例如下：

```jsx
import { List, Popconfirm } from 'antd';

<List
  dataSource={data}
  renderItem={(item) => (
    <List.Item
      actions={[
        <Popconfirm
          key="delete"
          title="Are you sure to delete this item?"
          onConfirm={() => handleDelete(item.id)}
          okText="Yes"
          cancelText="No"
          trigger="hover"
        >
          <a>Delete</a>
        </Popconfirm>,
      ]}
    >
      <List.Item.Meta
        title={<a href={item.href}>{item.title}</a>}
        description={item.description}
      />
      <div>{item.content}</div>
    </List.Item>
  )}
/>
```

关于 Popconfirm 的详细文档可以查看 Ant Design 官方文档：https://ant.design/components/popconfirm-cn/。
