### ISSUE TITLE
🧐[问题] 在Form.Item中使用EditableProTable可编辑表格能否实现表格内数据联动

### ISSUE THREAD

**Issue by zzcbnz** [ant-design/pro-components#5556]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

能否实现修改 ``数量`` 金额根据 ``数量*单价`` 自动计算
<img width="780" alt="image" src="https://user-images.githubusercontent.com/28007171/179388784-55f6e969-8c6d-4d6a-ab9e-59088e0166e5.png">

### 💻 示例代码

按文档案例https://procomponents.ant.design/components/editable-table#%E5%AE%9E%E6%97%B6%E4%BF%9D%E5%AD%98%E7%9A%84%E7%BC%96%E8%BE%91%E8%A1%A8%E6%A0%BC
尝试用``value``和``editable.onValuesChange``实现后发现数据是改变了，但是value作用不到表格上
demo：https://codesandbox.io/s/optimistic-chihiro-qldpoi

### 🚑 其他信息

**Comment by drizzlesconsin** [comment]
controlled | 是否受控, 如果受控每次编辑都会触发 onChange，并且会修改 dataSource | boolean | false

**Comment by drizzlesconsin** [comment]
controlled | 是否受控, 如果受控每次编辑都会触发 onChange，并且会修改 dataSource | boolean | false
-- | -- | -- | --

**Comment by zzcbnz** [comment]
> controlled	是否受控, 如果受控每次编辑都会触发 onChange，并且会修改 dataSource	boolean	false

试过了 还是不生效

**Comment by zzcbnz** [comment]
是否有方案能实现可编辑表格内的数据联动

**Comment by gloriousknight** [comment]
> 是否有方案能实现可编辑表格内的数据联动
请问大佬是否有解决方案了呢？

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/editable-table#editabletable-form-linkage

这个不可以吗？

**Comment by chenshuai2144** [comment]
<img width="733" alt="image" src="https://user-images.githubusercontent.com/8186664/204766123-bf0132ec-b8ba-41ae-ae98-d013eda50b4a.png">

**Comment by chenshuai2144** [comment]
时机问题有点不好搞，推荐你自己拿一下或者延迟一下再用
