### ISSUE TITLE
🐛[BUG] 输入框设为必输项清除内容重新填写时会有抖动

### ISSUE THREAD

**Issue by KingThq** [ant-design/pro-components#5564]
### 🐛 bug 描述
按照 pro 官网步骤创建新项目，登录页面用户名清楚后重新填写会产生抖动现象。

### 🏞 期望结果
在校验时表单不会抖动

### © 版本信息

- @ant-design/pro-components 版本: [ 1.1.1 ]
- umi 版本 v4
- react 17.0.0
- 浏览器环境 [ chrome ]
- 开发环境 [ mac OS]

### 🚑 其他信息

https://user-images.githubusercontent.com/39801991/179496383-3d04b401-ea5b-47a6-8c20-0f9343d3f557.mov

**Comment by KingThq** [comment]
antd 升级到 v4.21.5，正常输入删除不会出现这个问题了，如果快速输入删除会有抖动问题

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


如果您升级了 Antd 到 v4.21.5 但是仍然存在问题，那么可以考虑以下方案： 

1. 确认是否是 Antd 内部的问题导致抖动，请确认没有覆盖重写 Antd 组件的样式.
2. 检查输入框清除时的动画效果，是否是自定义的，如果是自定义的动画效果，可能需要更改动画参数，确认是否能够解决抖动问题。
3. 调整输入框校验的时机，将校验推迟到用户填写完整个表单后再进行，比如在提交表单前校验，而不是在用户输入时立即校验。
4. 提交一个 Issue 给 Antd 组件仓库，让 Antd 组件维护者检查是否有类似的问题，以获得更好的解决方案。 

下面提供一些相关文档链接和示例代码，帮助您更好的解决这个问题： 

- Antd 官方文档：https://ant.design/components/form-cn/#components-form-demo-validate-static
- Antd v4.21.5 版本更新日志：https://github.com/ant-design/ant-design/releases/tag/4.21.5
- React 官方文档：https://reactjs.org/docs/refs-and-the-dom.html
- 一个使用 Antd 表单组件的示例代码：https://codesandbox.io/s/antd-form-example-forked-wti1z?file=/index.js

**Comment by chenshuai2144** [comment]
有  error没有 error  会触发重新渲染，这个是 bug 已经修复了
