### ISSUE TITLE
🐛[BUG]屏幕伸缩的时候，搜索条件显示不全，没有“展开”标识

### ISSUE THREAD

**Issue by wynziguanhui** [ant-design/pro-components#5567]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: @ant-design/pro-table 2.56.0
- umi 版本 umi 3.5
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS] mac

**Comment by chenshuai2144** [comment]
修复啦，计算的时候少算了一个 col
