### ISSUE TITLE
🐛[BUG] ant design protable 多列排序报错

### ISSUE THREAD

**Issue by zhangle1** [ant-design/pro-components#5569]
1.主要是想实现服务端多列排序

2.复现例子:

2.1: ant design table  点击排序,可以正常返回数据 
https://codesandbox.io/s/shai-xuan-he-pai-xu-antd-4-21-7-forked-8xdvtd?file=/demo.js

2.2 ant design protable 点击排序，出现异常错误

https://codesandbox.io/s/wu-cha-xun-biao-dan-forked-lkc7k7?file=/App.tsx:2866-2903
实际调试返回的数据格式也很奇怪，只有一个排序的时候返回的是一个对象，点了两个列排序后返回空数组？

**Comment by tianyuan233** [comment]
报错是因为这一行
```js
JSON.stringify(sorter) // 断点看了一下 这里的sorter 并不是排序后的数据
```
排序后的数据是这个`extra.currentDataSource`

另外 排序是不是 还需要 写排序函数 比如这样

```js
{
    title: "容器数量",
    dataIndex: "containers",
    align: "right",
    sorter: {
      multiple: 1,
      compare: (a,b) => a.containers - b.containers
    }
  },
```

**Comment by zhangle1** [comment]
@tianyuan233  我是用服务端排序的 前端只管告诉当前状态字段列状态就行 ，目前解决方法是新建一个表格列里手动选升序降序 22223，  还做了字段的查询 包含,大于小于这些，也是放在头部 新建的自己的查询里。。。   感觉找不到类似的demo 自己在ant design 以我的水平有点不好调啊  2223

**Comment by chenshuai2144** [comment]
<img width="411" alt="image" src="https://user-images.githubusercontent.com/8186664/209086499-caa6a8ae-4636-478a-a739-dd5113f9ce5b.png">

问题估计出现在嵌套的排序上面了。是个bug

**Comment by chenshuai2144** [comment]
用  table  原生的 filter 吧。我的这个设计有点蠢
