### ISSUE TITLE
🧐[问题]请问protable的列能否通过权限控制

### ISSUE THREAD

**Issue by KellenHe** [ant-design/pro-components#557]
### 🧐 问题描述

例如列的设置里有access属性，可以通过权限控制列的显示与隐藏

### 💻 示例代码

`  const columns: ProColumns<TableListItem>[] = [
    {
      title: '名称',
      dataIndex: 'keyword',
      access: 'canViewName'
    }
]
`

**Comment by chenshuai2144** [comment]
这个是不支持你可以用filter，fulter一下。

`columns = columns.filter(()=>canViewName)`
