### ISSUE TITLE
🧐[问题]如何给整个 SchemaForm 设置 readonly ?

### ISSUE THREAD

**Issue by Vermouth-vi** [ant-design/pro-components#5576]
如题

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


可以通过在 SchemaForm 组件外层包裹一个 `el-form` 组件，并设置 `:readonly="true"` 来实现整个表单的只读状态。代码如下：

```
<template>
  <el-form :model="formData" :readonly="true">
    <schema-form :schema="schema" :form-data="formData" />
  </el-form>
</template>
```

同时，由于 `SchemaForm` 内部是依赖 `ElementUI` 组件库实现的，`SchemaForm` 中的表单元素也可以通过设置 `:disabled="true"` 来达到只读状态。例如：

```
{
  type: 'input',
  label: 'Input',
  model: 'input',
  disabled: true
}
```

这里的 `disabled: true` 就会使得 input 元素处于只读状态。更多详细的使用方法可以参考 [SchemaForm 文档](https://vue-component.github.io/schema-form/#/usage?id=%e5%b1%9e%e6%80%a7)。

**Comment by chenshuai2144** [comment]
现在支持了，可以在 form 中配置
