### ISSUE TITLE
👑 [需求] ProForm 的 submitter render 未提供是否 loading 的状态

### ISSUE THREAD

**Issue by denghongcai** [ant-design/pro-components#5577]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

ProForm

### 🥰 需求描述

ProForm 的 submitter render 未提供是否 loading 的状态，自定义时按钮感知不到当前是否处于提交中。

### ⛰ 功能需求适用场景

自定义表单提交按钮的场景

### 🧐 解决方案

render 传入的 props 中增加 `loading` 字段

**Comment by liangchaofei** [comment]
提供一个在线链接的demo?

**Comment by liangchaofei** [comment]
> 提问前先看看：
> 
> https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
> 
> ### 🔩 所属模块或组件
> ProForm
> 
> ### 🥰 需求描述
> ProForm 的 submitter render 未提供是否 loading 的状态，自定义时按钮感知不到当前是否处于提交中。
> 
> ### ⛰ 功能需求适用场景
> 自定义表单提交按钮的场景
> 
> ### 🧐 解决方案
> render 传入的 props 中增加 `loading` 字段

提供一个在线链接的demo？

**Comment by denghongcai** [comment]
@liangchaofei https://codesandbox.io/s/ce-shi-1-ukydnt?file=/App.tsx

自定义后，button 无法取到 loading 状态

**Comment by Mzhang1994** [comment]
> @liangchaofei https://codesandbox.io/s/ce-shi-1-ukydnt?file=/App.tsx
> 
> 自定义后，button 无法取到 loading 状态

你自定义之后，Button应该需要自己配置loading。antd的Button组件应该是不会默认loading配置的。

**Comment by denghongcai** [comment]
@Mzhang1994 form 并没有把 loading 的状态传递给 submitter 的 render，导致只要自定义，就需要额外去维护一个提交 loading 的状态，而不能利用现有的 异步 onFinish

**Comment by zzcbnz** [comment]
> @Mzhang1994 form 并没有把 loading 的状态传递给 submitter 的 render，导致只要自定义，就需要额外去维护一个提交 loading 的状态，而不能利用现有的 异步 onFinish

`    
/** @name 自定义操作的渲染 */
    render?: ((props: SubmitterProps & T & {
        submit: () => void;
        reset: () => void;
    }, dom: JSX.Element[]) => React.ReactNode[] | React.ReactNode | false) | false;
`

SubmitterProps里面的submitButtonProps就有loading 的状态，再传递给你的自定义按钮就可以了
