### ISSUE TITLE
🐛[BUG] 页面刷新导航菜单渲染异常

### ISSUE THREAD

**Issue by foreverForCode** [ant-design/pro-components#5580]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/23717603/179932032-e86b2d03-ca7a-4137-8561-02d591562816.png)
员工是有子项的
![image](https://user-images.githubusercontent.com/23717603/179932177-1168462b-5550-4cb4-a25d-f34612080e3d.png)

### 📷 复现步骤

点击浏览器刷新按钮，部分菜单没有渲染
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- @ant-design/pro-layout 6.30.0
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


根据你提供的信息，首先应该检查以下几个方面：

1. 确认数据源是否正确，即检查菜单数据是否正确加载。

2. 确认组件是否正确使用，即检查菜单组件是否被正确配置和使用。

3. 确认是否有相关的 CSS 样式缺失，即检查菜单组件是否有正确的样式。

4. 检查是否有浏览器缓存问题，建议清理浏览器缓存和 LocalStorage。

下面提供一些代码示例：

1. 检查菜单数据是否正确加载

检查菜单的请求接口是否正确，并且确认获取到的数据是否正确。如果数据有误，可以进一步检查接口返回的数据是否符合 API 规范。

2. 检查菜单组件是否被正确配置和使用

你可以检查菜单组件是否正确被引入，在组件中是否正确设置属性，比如是否正确设置样式、颜色等信息。

3. 检查是否有相关的 CSS 样式缺失

你可以在浏览器的调试工具中检查菜单组件的样式，看是否有样式缺失或者样式被覆盖。

4. 检查是否有浏览器缓存问题

你可以清理浏览器缓存和 LocalStorage，然后重新加载页面，看是否还有问题。

以上是一些常见的解决方案，如果还无法解决问题，建议提供更多详细信息，包括具体的代码示例，以便更好地理解和解决问题。同时，在提问时请使用更加明确的语言和专业术语，这有助于更好地沟通和解决问题。
