### ISSUE TITLE
🧐[问题] 如何封装ProFormFields ?

### ISSUE THREAD

**Issue by Valar103769** [ant-design/pro-components#5583]
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/36926073/179951467-e8ea0d71-3b2a-474a-8bd7-aaff36427517.png">
 是否组件只要向外提供onChange 和value prop就行?

**Comment by drizzlesconsin** [comment]
是的。红框的 input 如果是自定义组件，接收 onChange value 就行。
