### ISSUE TITLE
DragSortTable的表格数据接口获取的，拖拽出现异常🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/pro-components#5587]
### 🐛 bug 描述
使用DragSortTable的request属性使用接口获取表格数据， 不是用datasource, 发现拖拽出现异常，代码如图
![image](https://user-images.githubusercontent.com/20655248/180118471-ccaa269a-a15f-4b12-ad72-8bb881c0c82e.png)
![image](https://user-images.githubusercontent.com/20655248/180118547-d8118fc7-e67e-4565-aa25-61cb777e021a.png)
![image](https://user-images.githubusercontent.com/20655248/180118757-bacba658-5fd3-49e6-a201-2d759365bb84.png)

### © 版本信息

- ProComponents 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你需要先发dataSource 存下来。

你的key 也注意一一下，要保证每列唯一
