### ISSUE TITLE
ProFormCheckbox.Group中使用convertValue无效🧐[问题]

### ISSUE THREAD

**Issue by kateli** [ant-design/pro-components#5589]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

复选框展示数据的时候，利用convertValue进行前置转换无效  
比如 
从服务端拿到的值是 [1,2]
想展示为 ["a","b"]
但是配置了convertValue 后 还是显示的如截图
不知道我的用法是不是不对

### 💻 示例代码

<ProFormCheckbox.Group
        name="scene"
        label="scene"
        options={[2, 3]}
        convertValue={() => {
          return ['a', 'b'];
        }}
      />

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/8436428/180121518-5b78f962-4244-4d3c-9d61-e3e0fb871945.png)

**Comment by chenshuai2144** [comment]
```
<ProFormCheckbox.Group
        name="scene"
        label="scene"
        options={['a', 'b', 'c']}
        convertValue={() => {
          return ['a', 'b'];
        }}
      />
```

可以使用的，你再试试
