### ISSUE TITLE
🐛[BUG]ProForm中，date 类的组件在嵌套的 namePath 下，格式化不正确。

### ISSUE THREAD

**Issue by zhou0818** [ant-design/pro-components#559]
### 🐛 bug 描述

namePath 嵌套时，不是按 YYYY-mm-dd 返回的时间格式

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/25949890/93857258-ea345100-fcec-11ea-9ba0-12c8c505e727.png)

嵌套
![image](https://user-images.githubusercontent.com/25949890/93857328-00421180-fced-11ea-8d4a-2e9dc06286ae.png)

非嵌套
![image](https://user-images.githubusercontent.com/25949890/93857381-118b1e00-fced-11ea-8664-da8fe404e974.png)

### 🏞 期望结果

都按 YYYY-mm-dd 返回

### © 版本信息

- ProForm 版本: ["^1.0.0-beta.27"]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by itsuki0927** [comment]
在ProTable中通过指定`key`来生成格式化`valueTypeMap`,所以可以保证即便是有`dataIndex: ['a','b']`也能生成正确的`valueTypeMap`.

但是在ProForm中却保证不了, 因为在生成它的`valueTypeMap`有两种情况: 
1. name: 数组的的时候,会将数组隐式转换成string(数组转成字符串默认调用`数组.join(',')`)当作key.
2. name: string的时候, 恭喜能被正确格式化!!!
遍历的时候是直接将value的key拿出来(不一致问题), 这样子就产生了不能正确格式化的问题.

比如说`{ name: ['a', 'b'] }`,生成的valueTypeMap是 `{ 'a,b': 'xxx' }`, 而value: `{ a: { b: 'xxx' } }`, 这样子就格式化不成功.
```tsx
<ProForm
  onFinish={async (values) => {
    console.log(values);
  }}
>
  <ProFormDateRangePicker name={['a', 'b']} label="合同生效时间" />
</ProForm>;

// valueTypeMap
// { 'a,b': 'dateRange' }

// value 
// { a: { b: 1 } }
```
<img width="935" alt="Screen Shot 2020-09-29 at 06 36 01" src="https://user-images.githubusercontent.com/40518195/94492969-0caef880-021e-11eb-8508-5c3e0cb9d15c.png">

所以这里采用什么方案? 跟ProTable一样设置key保证唯一还是说有更好的思路?, 


在看源码的时候, 也发现一些其他问题, 最直接的我感觉就是嵌套对象的格式化问题, 像这个issue的
1. 嵌套name的format
2. 嵌套对象的 omitUndefined等等

或者说这不是一个bug, 我们本来不处理嵌套对象的值,比如说omitUndefined, 只过滤掉第一层对象的undefined value.

**Comment by itsuki0927** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
是失误，没想到这个 case
