### ISSUE TITLE
🧐[问题] queryFilter 中的 ProFormFields(自定义的) 如何调整宽度? 

### ISSUE THREAD

**Issue by Valar103769** [ant-design/pro-components#5590]
<img width="1718" alt="image" src="https://user-images.githubusercontent.com/36926073/180129201-fc4184ab-4c0c-4ccf-a6a2-6c8d4020c589.png">

这是自定义的组件, 应该如何调整宽度呢?
```
  >
          <DateRange2
            wrapperCol={{ span: 100 }}
            label="安装时间"
            tooltip="北京时间"
            initialValue={[
              moment().subtract(6, 'day').format('YYYY-MM-DD HH:mm:ss'),
              moment().format('YYYY-MM-DD HH:mm:ss'),
            ]}
            fieldProps={{ mode: 'date', showTime: true }}
          />
```

**Comment by drizzlesconsin** [comment]
用 colSize https://github.com/ant-design/pro-components/blob/c716078dc8bfc72d76836b56cca68eba13960787/packages/form/src/components/QueryFilter/demos/query-filter-test.tsx#L68=

**Comment by Valar103769** [comment]
> 用 colSize https://github.com/ant-design/pro-components/blob/c716078dc8bfc72d76836b56cca68eba13960787/packages/form/src/components/QueryFilter/demos/query-filter-test.tsx#L68=

colSize=2 也很大啊,能指定具体宽度吗

**Comment by drizzlesconsin** [comment]
指定宽度应该会影响对齐

可以考虑改成三列一行，通过 span 调整响应式规则。[SpanConfig](https://github.com/ant-design/pro-components/blob/e5b84eb2fe18cd14693436cf351ebb38da168911/packages/form/src/layouts/QueryFilter/index.tsx#L78=)
也可以把时间放到最后。

**Comment by Valar103769** [comment]
> 
默认已经是三列一行了, 时间放最后老板不同意
我记得好像有人提了个pr 说日期时间组件的时间被遮挡的问题, 怎么找不到pr了

**Comment by drizzlesconsin** [comment]
https://github.com/ant-design/pro-components/issues/109
