### ISSUE TITLE
ProTable设置name和editable属性导致表格不显示🐛[BUG]

### ISSUE THREAD

**Issue by ccisman** [ant-design/pro-components#5598]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProTable设置name属性后UI发生变化，如果和editable一起设置，表格甚至不显示。而且这在旧版本（具体哪个版本现在也不确定）好像不存在。

### 📷 复现步骤
引入ProTable，设置name和editable属性

### 💻 复现代码
https://codesandbox.io/s/qia-pian-biao-ge-forked-yj2722

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by xccjk** [comment]
这个问题是因为**同时设置了`name`与`editable`的时候没有在editable中传入from**导致的问题，并发bug

具体可以查看源码文件[ProTable](https://github.com/ant-design/pro-components/blob/master/packages/table/src/Table.tsx)

![1](https://user-images.githubusercontent.com/21093699/180385920-6012da7f-1934-4e93-af32-114f15c4f301.png)

解决方案：

```
import { Form } from 'antd';
...
const [form] = Form.useForm();
...
<ProTable<TableListItem>
  columns={columns}
  request={(params, sorter, filter) => {
    // 表单搜索项会从 params 传入，传递给后端接口。
    console.log(params, sorter, filter);
    return Promise.resolve({
      data: tableListDataSource,
      success: true,
    });
  }}
  cardProps={{ title: '业务定制', bordered: true }}
  headerTitle={
    <Button
      key="primary"
      type="primary"
      onClick={() => {
        alert('add');
      }}
    >
      添加
    </Button>
  }
  rowKey="key"
  search={false}
  name="whatever"
  editable={{
    form
  }}
/>
```

问题原因感觉应该是文档不完善导致的@ccisman

**Comment by xccjk** [comment]
修改后的代码@ccisman 

[https://codesandbox.io/s/qia-pian-biao-ge-forked-dlz0tn?file=/App.tsx](https://codesandbox.io/s/qia-pian-biao-ge-forked-dlz0tn?file=/App.tsx)

**Comment by ccisman** [comment]
> 修改后的代码@ccisman
> 
> https://codesandbox.io/s/qia-pian-biao-ge-forked-dlz0tn?file=/App.tsx

了解，谢谢啦。
