### ISSUE TITLE
👑 [需求]pro-table 需求重置表单的initialValues

### ISSUE THREAD

**Issue by sunkaigoon** [ant-design/pro-components#56]
### 🥰 需求描述

页面A 内使用pro-table显示数据，当使用查询表单筛选了数据之后，点击table里的数据跳转到页面B，当返回页面A后需要显示原先的数据。这时先将页面A的筛选条件filter，页码current，长度pageSize储存起来，返回页面A时，将filter放入form的initialValues中，current和pageSize设置为pagination的初始参数，可以达到显示原先数据的目的。问题在于，当点击表单的reset按钮时，无法重置到空状态，这是设置了初始值得原因，但不符合使用的场景。

我尝试在onReset方法中使用setState(维护一个initialValues，初始值为储存的filter)重置initialValues为{}，这种办法需要点击两次reset按钮才能达到置空的目的，第一次设置initialValues为{}，第二次将表单置为{}状态（置空）

### 🧐 解决方案

能否提供一个api，强制将表单置空并刷新table

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26641822/88793037-c3670c00-d1ce-11ea-9d65-4a423e3272f4.png)
页面A筛选数据
![image](https://user-images.githubusercontent.com/26641822/88793077-d4b01880-d1ce-11ea-84cc-7433d5ef6227.png)
页面B
![image](https://user-images.githubusercontent.com/26641822/88793098-dd085380-d1ce-11ea-803e-1ed5300c1987.png)
返回页面A
![image](https://user-images.githubusercontent.com/26641822/88793122-e8f41580-d1ce-11ea-997e-4bf05ae3dbb8.png)
点击两次重置按钮后

一下部分代码：
![image](https://user-images.githubusercontent.com/26641822/88793375-44be9e80-d1cf-11ea-9d2b-7e4a92f21f61.png)
![image](https://user-images.githubusercontent.com/26641822/88793382-4720f880-d1cf-11ea-88f3-d3f66368a117.png)

或者是不是有其它的方法解决这个问题

**Comment by fangniu** [comment]
同求

**Comment by infnan** [comment]
供参考：https://github.com/ant-design/pro-table/issues/126#issuecomment-672664804
不要在columns或form中设置initialValues，而是在useEffect中setInitialValues。不过分页的逻辑还是不好看。

**Comment by l745230** [comment]
我也遇到了这个需求.. 

最后选择使用link打开一个新页面查看详情页. antdPro里实现不了tab页,干脆用上浏览器的tab页. 综合体验下来,用户能接收. 反馈过来比单页中跳转详情页,再返回列表 操作更简单,体验也好.

**Comment by l745230** [comment]
除了记录表单的查询参数, 还要记录当前列表的滚动条高度,  点返回的时候,回到上次页面的状态. 尝试过倒也能实现,但是写起来麻烦,封装的自定义组件的功力不够,最后放弃了.

**Comment by linxianxi** [comment]
这个有办法实现么

**Comment by linxianxi** [comment]
@chenshuai2144   同有需求，这个有办法实现么。我觉得不行的话可以在 request 加上第二个参数，判断是不是重置触发的，让我们自定义请求

**Comment by linxianxi** [comment]
我想到一个办法，将 initialValues 存在 state 中，在 request 中清空 initialValues。点击重置就是清空状态了！

**Comment by chenshuai2144** [comment]
@linxianxi  你的方法是正解，initialValues  只在组件没有初始化的时候生效

**Comment by Liu123233** [comment]
我的方法是当点击重置的时候,手动将对应的文本框设置为空

**Comment by winwangqi** [comment]
> @linxianxi 你的方法是正解，initialValues 只在组件没有初始化的时候生效

请问正解应该怎么做？

**Comment by chenshuai2144** [comment]
`initialValues && <组件/>`

**Comment by darknessjs** [comment]
这居然没有标准方案而是各种hack...

**Comment by soulcm** [comment]
所以现在有解决方案了没，我现在有个下拉框，想要的初始值可能是异步请求回来的（若有，则置为disabled），若setFieldsValue设置值之后，点击重置按钮，这个框就被置空了

**Comment by jiangxiaoqiang** [comment]
所以没有非hack方法解决？

**Comment by lcc908** [comment]
> 我根据这个答案来处理的：https://stackoverflow.com/questions/71523100/how-to-refresh-the-antd-pro-proformtext-initialvalue

有用，ProForm本身就是基于ant的from开发的，调用setFieldsValue来实现数据编辑回显

**Comment by ycshill** [comment]
> 

牛！我想了好久，刷到你的解决办法，解决了！

**Comment by believeZJP** [comment]
```js
onReset={() => {
      setInitDate([]);
      // 通过这种方式解决有默认值的重置
      setTimeout(() => {
          actionRef.current.reset();
      }, 0);
  }}
```

**Comment by cdx111** [comment]
我用这个解决了保存搜索条件后无法重置的问题。

 const formRef = useRef<ProFormInstance<any>>();
 const [params,setParams] = 外部数据 比如redux zustand之类的状态管理
   useEffect(() => {
    formRef.current?.setFieldsValue({ ...params });
  },[]);
  
   <ProTable  request={async (p)=>{
    const pp = formRef.current?.getFieldsValue();
    setParams({...p,...pp})
     reqeust({...p,...pp})
   }}
  这是最完美的方案

**Comment by luohuiqun** [comment]
> 我用这个解决了保存搜索条件后无法重置的问题。
> 
> const formRef = useRef<ProFormInstance>(); const [params,setParams] = 外部数据 比如redux zustand之类的状态管理 useEffect(() => { formRef.current?.setFieldsValue({ ...params }); },[]);
> 
> <ProTable request={async (p)=>{ const pp = formRef.current?.getFieldsValue(); setParams({...p,...pp}) reqeust({...p,...pp}) }} 这是最完美的方案

嗯嗯 有所启发 但不是最佳
1、useEffect(() => {
    // 需要给表单初始化的数据
    if (data) {
      formRef.current?.setFieldsValue(data);
    }
  }, [data]);

2、<img width="680" alt="Image" src="https://github.com/user-attachments/assets/4499f5ec-c393-4985-a1f8-94a2e2a090ef" />
3、columns中也不需要设置initialValue这个字段了
4、

<img width="633" alt="Image" src="https://github.com/user-attachments/assets/9f61df30-100e-49fe-857f-00b0a9cb83b7" />

这才是最佳的
