### ISSUE TITLE
当pro-table 使用的是dataSource 会有个默认的ant-empty，请问如何控制pro-table内置的这个文案呢？

### ISSUE THREAD

**Issue by wxf-start** [ant-design/pro-components#560]
### 🥰 需求描述

当pro-table 使用的是dataSource 会有个默认的ant-empty，请问如何控制pro-table内置的这个文案呢？
因为我想换个图片和文案，使用了ConfigProvider 只能改变table的空数据状态，并不能改变数据没请求回来的ant-empty
![image](https://user-images.githubusercontent.com/37679380/93860081-18b42b00-fcf1-11ea-9f51-9b9ba0dbd609.png)

### 🚑 其他信息

![Uploading image.png…]()

**Comment by chenshuai2144** [comment]
locale | 默认文案设置，目前包括排序、过滤、空数据文案 | object | filterConfirm: 确定filterReset: 重置emptyText: 暂无数据默认值
-- | -- | -- | --


https://ant.design/components/table-cn/#Table
