### ISSUE TITLE
🐛[BUG] EditableProTable与 FormItem 配合在编辑状态“删除”行为和预期不符

### ISSUE THREAD

**Issue by zzcbnz** [ant-design/pro-components#5600]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

#### 问题1：添加多行后无法删除最后一行
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/28007171/180352721-d83c35d8-d000-430f-849b-f00ed4e16ad4.png">

添加多行数据后，从上到下依次删除，最后一行删不掉
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/28007171/180352888-5cefd87a-3837-49d8-9339-13b7f5cce0c0.png">
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/28007171/180353451-88b6e400-efba-44c1-a8ea-76301dc7c62b.png">

#### 问题2：删除一行后导致其他行的数据被清空
在编辑状态下表格内有数据
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/28007171/180353897-129985ea-4489-4460-9f4a-fc8dd4b2084e.png">

随便删除一行后 表格内数据被清空
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/28007171/180353825-d812228c-e50a-421b-b922-d71ff1e1c575.png">

#### 问题3：添加到最大行后表格数据会被清空，而且还会出现部分默认值
添加4行的时候没问题
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/28007171/180354706-52a6eb25-9eda-4270-bc2c-6c3b2ee3ef07.png">
添加到第5行的时候数据异常
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/28007171/180354782-3c75fff5-8615-4304-8e14-7529aadcfa11.png">

#### 问题4：在编辑状态下删除行出现异常行为
在编辑状态下删除第一行
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/28007171/180355338-79c89d4e-335f-481d-8880-917a9b43803f.png">

第一行没被删掉，第二行的数据异常
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/28007171/180355405-703caefb-f4b4-4398-baa4-716d31430c33.png">

### 📷 复现步骤
官网文档demo：https://procomponents.ant.design/components/editable-table/#%E4%B8%8E-formitem-%E9%85%8D%E5%90%88
官网文档的demo存在以上问题

### 💻 复现代码
查看官网文档demo

### © 版本信息

- ProComponents 版本: 1.1.1
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by year9** [comment]
我已复现，确实有这个问题

**Comment by wannafre** [comment]
+1

**Comment by xiaofubufu** [comment]
+2

**Comment by 245938767** [comment]
+1

**Comment by yaoguoba** [comment]
+1

**Comment by yaoguoba** [comment]
+1

**Comment by Hexl2018** [comment]
+1

**Comment by henryzp** [comment]
我想问，你们为什么不用formily呢？

**Comment by wangmeijian** [comment]
我来看看这个问题

**Comment by WuJiY** [comment]
+1

**Comment by wowtrxqn** [comment]
+1
