### ISSUE TITLE
🐛[BUG]ProFormList嵌套为二维数组时，子List调用setCurrentRowData修改数据的NamePath不正确

### ISSUE THREAD

**Issue by soradaisuke** [ant-design/pro-components#5606]
### 🐛 bug 描述

```typescript
<ProFormList name="list">
  <ProFormList name={[]}>
    {
      (_, __, action) => {
      }
    }
  </ProFormList>
</ProFormList>
```
比如按照这种方式嵌套，action.getCurrentRowData()获取结果是正确的，但是action.setCurrentRowData()并没有把数据设置到正确的NamePath上

https://github.com/ant-design/pro-components/commit/47fe90c1d90ef6b8e28bdbdda86a915454cb1d64

跟这个fix是同样的问题，filter(Boolean)会把NamePath里的数值0过滤掉，其他的地方的filter(Boolean)都被替换了，只有setCurrentRowData里没有改

### 📷 复现步骤

如上

### © 版本信息

- ProForm：1.70.0

**Comment by wmy94827** [comment]
+1
