### ISSUE TITLE
protable能全局配置columnEmptyText么🧐[问题]

### ISSUE THREAD

**Issue by undefined9999** [ant-design/pro-components#5607]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
项目中有很多页面用到了protable, 想统一定制columnEmptyText, 但是又不想每一个protable都写一遍columnEmptyText

### 🚑 其他信息
是否考虑和antd的message组件一样也支持进行全局config配置
![image](https://user-images.githubusercontent.com/35595635/180399193-d50d8c7b-915d-4e53-9eea-e92d4fc89738.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


在protable中，可以通过customRenderEmpty方法来实现对所有表格的empty文案进行统一自定义：

```typescript
import { ConfigProvider } from 'antd';
import ProTable, { ProColumns } from '@ant-design/pro-table';

const tableColumns: ProColumns<DataType>[] = [
  // table columns config
];

// 定义一个renderEmpty方法
const renderEmpty = () => <div>Custom Empty Text</div>;

// 使用ConfigProvider将protable包裹起来，并传入renderEmpty配置
<ConfigProvider renderEmpty={renderEmpty}>
  <ProTable
    columns={tableColumns}
    // ...
  />
</ConfigProvider>;
```

这里使用了ConfigProvider来进行全局的配置，renderEmpty配置可以接受一个ReactNode或() => ReactNode，用于自定义empty文案。

具体可以参考官方文档：

- [ConfigProvider](https://ant.design/components/config-provider-cn/)
- [Table - customRenderEmpty](https://procomponents.ant.design/components/table/#customrenderempty)

**Comment by chenshuai2144** [comment]
自己做个 ProTable 的封装好了。ProProvide 暂时不支持
