### ISSUE TITLE
Antd EditableProTable valueNum is column based how to set different value in each row

### ISSUE THREAD

**Issue by nirmesh** [ant-design/pro-components#5609]
I am using Antd EditableProTable where i am trying to create select box and i am setting options value in valueEnum but for second row for same column my valueEnum is different but how to set that? In normal antd table there is concept of datasource but here that takes just the data which have to be shown on first time render but not the select options you have to define it in column levels only but then the problem is it render the same in each row.

**How to provide different select box data for each row.Any help would be great.**

attach screenshot
https://i.stack.imgur.com/zzSFz.png

even though if i able to achieve it by using render , i wont be able to get value under editable property of it i mean inside this even though if i able to achive it by using render , i wont be able to get value under editable property of it i mean inside this 
editable = {{     type: 'multiple',     
    editableKeys,     
    onValuesChange: (record, recordList) => {   console.log(record);  }     
    }}

 am unable to get that drop down value which i rendered custom. rest all column values are present in record. how to get that custom render drop down value?

**Comment by chenshuai2144** [comment]
` ((entity: Entity, type: ComponentsType) => Type | ProFieldValueObject<Type>);`

you can use  valueType is function。


```
 valueType: (row) => {
      if (row.name) {
        return 'avatar';
      }
      return 'text';
    },
```
