### ISSUE TITLE
🧐[问题]多层ProList使用dataSource加载数据，更新了数据源，为什么界面没有改变

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#5611]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

嵌套了3层，更新了最里层的数据一个字段，但是UI没有改变
### 💻 示例代码
![image](https://user-images.githubusercontent.com/12421552/180647525-f2b40ad4-bb1c-469c-9aec-8dc0805e4bfe.png)

![image](https://user-images.githubusercontent.com/12421552/180647483-3a338a3a-a47e-47e9-b197-c5c905c6cb22.png)

` <ProList
              ghost
              rowKey="id"
              actionRef={ref}
              dataSource={checkChilds}
              showActions="hover"
              showExtra="hover"
              renderItem={(item) => (
                <ProCard
                  style={{ marginTop: '24px' }}
                  title={item.group}
                  headerBordered
                  bodyStyle={{ padding: '15px' }}
                  onCollapse={(collapse) => console.log(collapse)}
                  extra={
                    segmentedValue == '违规' ? (
                      <Tag color="red">异常：{item.count}</Tag>
                    ) : (
                      <Tag color="green">正常</Tag>
                    )
                  }
                >
                  <ProList
                    ghost
                    rowKey="id"
                    dataSource={item.groups}
                    showActions="hover"
                    showExtra="hover"
                    renderItem={(child) => (
                      <ProCard
                        title={child.name}
                        size="small"
                        bodyStyle={{ paddingLeft: '0', paddingRight: '0', paddingBottom: '0' }}
                        // collapsed={true}
                        // collapsible={false}
                        // defaultCollapsed={false}
                      >
                        {child.details != undefined && (
                          <ProList
                            bordered={true}
                            rowKey="id"
                            dataSource={child.details}
                            showActions="hover"
                            showExtra="hover"
                            renderItem={(detail, index) => (
                              <Badge.Ribbon text={index + 1} placement="start" color="red">
                                <List.Item style={{ paddingLeft: 20 }}>
                                  {detail.errorWord}
                                  {detail.rightWord != undefined && ' -> ' + detail.rightWord}
                                  == {detail.click}
                                </List.Item>
                              </Badge.Ribbon>
                            )}
                          />
                        )}
                      </ProCard>
                    )}
                  />
                </ProCard>
              )}
            />`

**Comment by 666-arch** [comment]
要针对datasource做个拷贝然后再setState一下，好像是因为 react只是针对他做了一个浅监听
