### ISSUE TITLE
🧐[高级表格数据做批量选择的时候后端必须返回一个key提供给前端吗？好像如果不传key多选会出现错乱的情况？]

### ISSUE THREAD

**Issue by 666-arch** [ant-design/pro-components#5612]
![image](https://user-images.githubusercontent.com/65932450/180677632-38a0e8c5-33aa-4cfc-bf9c-fde93ac411ca.png)
![image](https://user-images.githubusercontent.com/65932450/180677644-ebbf53e8-02ac-4f2d-8155-a304aa134622.png)
我选择任意一个其他也会被判定为选中状态！！！

**Comment by ILoveChy** [comment]
> ![image](https://user-images.githubusercontent.com/65932450/180677632-38a0e8c5-33aa-4cfc-bf9c-fde93ac411ca.png) ![image](https://user-images.githubusercontent.com/65932450/180677644-ebbf53e8-02ac-4f2d-8155-a304aa134622.png) 我选择任意一个其他也会被判定为选中状态！！！

就是得给个唯一id啊,不一定非要是key这个字段名,可以是xxxKey,xxxId

**Comment by wangmeijian** [comment]
是的，React的问题，你可以自己构造唯一id
