### ISSUE TITLE
👑 [需求]  可以增加表格的列的拖拽功能， elementUi AntdVue的Surely Vue 都有这个功能

### ISSUE THREAD

**Issue by ngwszsd** [ant-design/pro-components#5614]
### 🥰 需求描述 | Requirements description
+ 可以增加表格的列的拖拽功能， elementUi AntdVue的Surely Vue 都有这个功能  这是高性能组件 Surely Vue 的一个  [Demo ](https://www.surely.cool/doc/dragable#columns)  它只需要在column数据设置一个参数resizable = true就可以实现
+ 虽然有react-resizable这个插件可以在原生Table实现列的拖拽功能（ps: 体验也不太好） 但在Pro组件的ProTable会特别卡 体验非常差
下图是Surely Vue 例子 

![image](https://user-images.githubusercontent.com/45424459/180356599-5284aea2-1f06-4319-8ac9-a2f90ccd2d3f.png)

**Comment by undefined9999** [comment]
也有同样是的需求, 希望官方能安排此功能

**Comment by mtiger95** [comment]
需求加1

**Comment by chenshuai2144** [comment]
官方暂时不打算加，可以去antd 提个pr加个demo

**Comment by jschyz** [comment]
为什么 ProTable 跟 react-resizable 配置一起会非常卡？

**Comment by ngwszsd** [comment]
> 为什么 ProTable 跟 react-resizable 配置一起会非常卡？
别用protable了 好久都不更新了 用用form还行 table有很多其他解决方案
