### ISSUE TITLE
🧐[问题]ProFormList里的ProFormTable

### ISSUE THREAD

**Issue by RoyKwok94** [ant-design/pro-components#5618]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
用ProFormList 循环组 <SelectModal />，组件里有个Modal，Modal又有 ProFormTable ，ProFormTable  request={async (params) 
params 打印的结构是 {0:{state: 1},current: 1,pageSize: 20} ， {1:{state: 1},current: 1,pageSize: 20}，为什么这样，对象key值是数字？

#####   ---------------------------------ProFormList
<ProForm onFinish={async (e) => console.log(e)}>
      <ProFormList
        name="labels"
        label="用户信息"
        initialValue={[
          {
            value: "333",
            label: "333",
          },
          {
            value: "222",
            label: "222",
          },
          {
            value: "111",
            label: "111",
          },
        ]}
        creatorButtonProps={false}
        copyIconProps={false}
        deleteIconProps={false}
      >
        <ProFormGroup key="group">
          <SelectModal />
        </ProFormGroup>
      </ProFormList>
    </ProForm>
#####   ---------------------------------SelectModal 
<Fragment>
      <ProFormText name="text" label="名称" placeholder="请输入名称" />
      <Button type="primary" onClick={showModal}>
        打开modal
      </Button>
      <Modal
        width={1000}
        title="Basic Modal"
        visible={isModalVisible}
        onOk={handleOk}
        onCancel={handleCancel}
      >
        <ProTable<GithubIssueItem>
          columns={columns}
          request={async (params) => {
            console.log(params)
            return {
              data: [
                {
                  key: 1,
                  name: `TradeCode ${1}`,
                  createdAt: 1602572994055,
                  state: "closed",
                },
              ],
              success: true,
            }
          }}
          rowKey="key"
          dateFormatter="string"
          search={{
            defaultCollapsed: false,
            optionRender: (searchConfig, formProps, dom) => [
              ...dom.reverse(),
              <Button
                key="out"
                onClick={() => {
                  const values = searchConfig?.form?.getFieldsValue()
                  console.log(values)
                }}
              >
                导出
              </Button>,
            ],
          }}
        />
      </Modal>
    </Fragment>

**Comment by RoyKwok94** [comment]
---------------------------------SelectModal

 <Fragment>
      <ProFormText name="text" label="名称" placeholder="请输入名称" />
      <Button type="primary" onClick={showModal}>
        打开modal
      </Button>
      <Modal
        width={1000}
        title="Basic Modal"
        visible={isModalVisible}
        onOk={handleOk}
        onCancel={handleCancel}
      >
        <ProTable<GithubIssueItem>
          columns={columns}
          request={async (params) => {
            console.log(params)
            return {
              data: [
                {
                  key: 1,
                  name: `TradeCode ${1}`,
                  createdAt: 1602572994055,
                  state: "closed",
                },
              ],
              success: true,
            }
          }}
          rowKey="key"
          dateFormatter="string"
          search={{
            defaultCollapsed: false,
            optionRender: (searchConfig, formProps, dom) => [
              ...dom.reverse(),
              <Button
                key="out"
                onClick={() => {
                  const values = searchConfig?.form?.getFieldsValue()
                  console.log(values)
                }}
              >
                导出
              </Button>,
            ],
          }}
        />
      </Modal>
    </Fragment>

**Comment by RoyKwok94** [comment]
---------------------------------SelectModal
<ProTable<GithubIssueItem>
          columns={columns}
          request={async (params) => {
            console.log(params)
            return {
              data: [
                {
                  key: 1,
                  name: `TradeCode ${1}`,
                  createdAt: 1602572994055,
                  state: "closed",
                },
              ],
              success: true,
            }
          }}
          rowKey="key"
          dateFormatter="string"
          search={{
            defaultCollapsed: false,
            optionRender: (searchConfig, formProps, dom) => [
              ...dom.reverse(),
              <Button
                key="out"
                onClick={() => {
                  const values = searchConfig?.form?.getFieldsValue()
                  console.log(values)
                }}
              >
                导出
              </Button>,
            ],
          }}
        />

**Comment by chenshuai2144** [comment]
升级下版本试试，这个是因为 portable 本质上是个列表，所以用了 0 1 来当key。保证每一行都有一个唯一的key
