### ISSUE TITLE
🐛[BUG] proTable走2.77.0版本开始，使用手动request时，初次请求会请求（渲染）两次

### ISSUE THREAD

**Issue by jayt1001** [ant-design/pro-components#5619]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

proTable走2.77.0版本开始，使用手动request时，初次请求会请求（渲染）两次，亲测2.76.2 2.76.0不会出现这个问题，之后的版本都会有这个问题

### 📷 复现步骤

使用内置方法：reloadAndRest()、.reload()等都可以复现
### 🏞 期望结果

初次请求只会请求一次

### © 版本信息

pro-table@2.77.0及之后

**Comment by gdmec07140512** [comment]
+1
