### ISSUE TITLE
👑 [需求]protable搜索表单折叠保留行数可配置化

### ISSUE THREAD

**Issue by lixin0724** [ant-design/pro-components#562]
### 🥰 需求描述

目前搜索表单折叠默认展示一行。在小屏的显示器上可能就只有两个筛选项，项目经常遇到交互会要求搜索表单收起时能保留2行这样的需求。
希望能收起后展示的表单行数可以配置化。

### 🚑 其他信息

如截图等其他信息可以贴在这里
![390B8057-68E7-4228-9380-743088C8C89F](https://user-images.githubusercontent.com/53106140/93865949-9e3bd900-fcf9-11ea-98c7-0459a3010ffe.png)

**Comment by JackDan9** [comment]
问下目前这个问题还是没有解决是吧。

**Comment by chenshuai2144** [comment]
可以配置span 一行是24 宽度等于24/span

**Comment by JackDan9** [comment]
OK，了解，问下为什么会用span这个作为控制字段？不会存在误解吗？

**Comment by JackDan9** [comment]
OK, 了解！

**Comment by cqb421392034** [comment]
单独给每个columns设置搜索宽度，现在可以用了吗， 统一设的话 有的太长有的又太短

**Comment by justLearner** [comment]
最后还是没有设置属性吗

**Comment by liucys** [comment]
如何设置默认两行或其他多行呢？
