### ISSUE TITLE
ProFormSelect组件的dropdownRender 失效🐛[BUG]

### ISSUE THREAD

**Issue by erichow** [ant-design/pro-components#5621]
https://codesandbox.io/s/qing-liang-shai-xuan-bian-kuang-mo-shi-forked-bq5x5c?file=/App.tsx

**Comment by chenshuai2144** [comment]
轻量组件里面 ProFormSelect 的dropdownRender  被使用掉了，你不能再次使用他

**Comment by 1998729** [comment]
请问有相关方案么？

**Comment by qianggechao** [comment]
我的解决办法
` <ProFormText label="标题" name="title" /> 
 <ProForm.Item label="分类" name="type">
          <Select
            dropdownRender={(menu) => (
              <>
                {menu}
                <Space size="large" style={{ padding: '12px' }}>
                  <Input />
                  <Button>添加分类</Button>
                </Space>
              </>
            )}
          ></Select>
  </ProForm.Item>`
