### ISSUE TITLE
使用ProFormDependency 关联表单项为ProFormCheckbox.Group时的问题🧐[问题]

### ISSUE THREAD

**Issue by Ricky816845** [ant-design/pro-components#5624]
### 🧐 问题描述

我有一个表单项是需要关联另外两个表单项 其中一个是ProFormCheckbox.Group
关键是我对这个表单项 做了transform和convert 处理
proformdependency 对这个字段值就变成undifined了

### 💻 示例代码

![a1](https://user-images.githubusercontent.com/20158450/180969030-7b1a5cff-b804-4911-841b-bfb577234a4c.png)
![a2](https://user-images.githubusercontent.com/20158450/180969042-4beaed83-3f88-4349-a1cb-d83abba76ac4.png)

**Comment by Ricky816845** [comment]
找到问题了,prodependency 强制吧transform返回值按对象处理了 

![image](https://user-images.githubusercontent.com/20158450/180981328-76677072-e8c4-402c-aba4-2d8af8224ac2.png)

这算bug吧?能修么?

**Comment by drizzlesconsin** [comment]
transform **提交时转化**
transform **发生在提交的时候**，一般来说都是吐给后端的存在数据库里的数据。

[doc](https://procomponents.ant.design/en-US/components/form#transform-transform-when-submitting)

**Comment by chenshuai2144** [comment]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/8186664/209088252-1073614a-0817-4ed6-ba4c-a0de0ba09485.png">


返回的时候把你的name加一下 renturn  `{ [name] :value }`
