### ISSUE TITLE
ProTable异常卡顿🧐[问题]

### ISSUE THREAD

**Issue by WT-Road** [ant-design/pro-components#5625]
### 🧐 问题描述

table列数大于50时,使用Tab切换异常卡顿,求解惑问题出在哪

### 🚑 其他信息

https://user-images.githubusercontent.com/14371925/180973872-2b0bb3e7-f6e8-4a12-8a7d-b069794c0c41.mp4

**Comment by drizzlesconsin** [comment]
可以先把 Tabs 的动画关了，排除问题。
如果表格列多，需要考虑虚拟表格。

**Comment by WT-Road** [comment]
> 可以先把 Tabs 的动画关了，解决问题。 如果表格列多，需要考虑虚拟表格。
animated={false}卡顿解决,但是还是有延迟效果,自定义Tab解决了卡顿...
