### ISSUE TITLE
protable 分页功能，切换分页的时候，页码一直被重置为1🐛[BUG]

### ISSUE THREAD

**Issue by lcc908** [ant-design/pro-components#5628]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

protable pagination里面的onchange事件执行了两次，第一次是我点击的页码，第二次的时候当前一直被重置回1，导致无法切换分页，请问可能是哪里的问题

### 🏞 期望结果
翻页的onchang事件，只执行一次

### 💻 复现代码

const [params, setParamDatas] = useState({
    platform_id:"",
    page_size: 10,
    current:1,
    ipaddress:'',
    host_name:""
  })
  const onChangePagination = (page, pageSize) => {
    console.log(page, pageSize);
    setParamDatas(val => {
      return {...val, current: page, page_size: pageSize,}
    })
  }
  return (
    <PageContainer>
      <ProTable
        columns={columns}
        // rowKey="vm_uuid"
        rowKey={record => record.vm_id}
        params={params}
        request={(par) => {
          return getSourceVmList(params)
        }}
        pagination={{
          position: ['bottomCenter'],
          showQuickJumper: true,
          onChange: onChangePagination,
          pageSize: 10,
        }}
      />
）
### © 版本信息

- "@ant-design/pro-table": "^2.77.0",
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lcc908** [comment]
该问题我用其他方案解决了，然后看源码发现这段代码，为什么要重置current呢？：  
useDeepCompareEffect(() => {
    // request 存在且params不为空，且已经请求过数据才需要设置。
    if (props.request && params && action.dataSource && action?.pageInfo?.current !== 1) {
      action.setPageInfo({
        current: 1,
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [params]);

**Comment by youtiao66** [comment]
虽然这个 Issue 已经被关闭，但对我却起到了很大的作用。主要因为新增了以下功能：

[fix(table): table 的 param发生变化时重置分页为1 #4648](https://github.com/ant-design/pro-components/pull/4648)

既解答了 @lcc908 的疑惑，同时也希望遇到相同问题的开发者能够快速定位并解决问题。

**Comment by gezichenshan** [comment]
是啊，^2.80.8问题还是有！

**Comment by AsskaMa** [comment]
我用最新版bug还在，请问大佬们怎么解决的？

**Comment by fireword** [comment]
> 我用最新版bug还在，请问大佬们怎么解决的？

need remove params={curReqParam},   use like these code:

     type StReqLstAnt = {
         pageSize: number;   // ant request
        current: number;    // ant request
     }

     <ProTable<DataSourceType, StReqLstAnt>

        pagination={{
          showSizeChanger: true,
          current: curReqParam.current,
          pageSize: curReqParam.pageSize,
          onChange: (page, pageSize) => funChgPage(page, pageSize),
        }}

       request={async (params, sort, filter) => {
          if (sort.idx === 'descend') {
            params.sort_type = SortType.Descend;
          } else {
            params.sort_type = SortType.Ascend;
          }
          var data = await reqLst(params);
          return data;
        }}

**Comment by DengJie001** [comment]
> 我用最新版bug还在，请问大佬们怎么解决的？

**Comment by Cosimac** [comment]
设置了dataSrouce 会出现这种情况 原因大概是自定义的列表数据和组件的total总数对应不上, 我是用Pagination组件自己控制分页解决的

**Comment by Zoupers** [comment]
我是去掉params中的current参数，然后可以正常使用

**Comment by thomasliew** [comment]
pageSize: 10修改为defaultPageSize: 10
