### ISSUE TITLE
🐛[BUG] SettingDrawer 页面不展示设置按钮了

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#5629]
<img width="507" alt="image" src="https://user-images.githubusercontent.com/30397655/181152751-5ca931d3-7c8b-4e4f-a8bf-b1765c1b6f41.png">

**Comment by chenshuai2144** [comment]
新版本 drawer 去掉了这个功能，安装下最新版本，pro 做了兼容

**Comment by 3463135482** [comment]
最新的1.1.15还是看不到

**Comment by chenshuai2144** [comment]
pro-layout  的版本哦

**Comment by LiuYyunHao** [comment]
<img width="856" alt="image" src="https://user-images.githubusercontent.com/34497040/187108152-45288bb5-8ed4-4ef7-a3da-640b9e058f0b.png">
