### ISSUE TITLE
👑 [需求] ProTable的toolbar 里面 tabs 可否支持tabs的全部属性、目前只支持activeKey={tabs.activeKey} onChange={tabs.onChange} tabBarExtraContent={filtersNode}

### ISSUE THREAD

**Issue by liguonan888** [ant-design/pro-components#5630]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### ⛰ 功能需求适用场景
ProTable的toolbar 里面 tabs 可否支持tabs的全部属性、

### 🧐 解决方案

可以在ListToolBarTabBar里面将传入的tabs属性都传入到Tabs组件当中么

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


感谢回复! 我会跟进你们的建议，尽快创建 Pull Request 来解决这个问题。同时我会提供必要的文档和测试用例来确保贡献的质量，并尽量在改动中提供清晰的 changelog 以及 TypeScript 定义，让代码更加易于维护。再次感谢您和团队的耐心和支持！

**Comment by chenshuai2144** [comment]
支持啦
