### ISSUE TITLE
🐛[BUG] 关于ProForm中使用tranform的一些问题

### ISSUE THREAD

**Issue by zd5043039119** [ant-design/pro-components#5637]
### 📷 复现步骤
问题1
1. 在NamePath:['a','b'] 下的输入框修改,得到错误的结果

问题2
1. 在NamePath:['b']下的b.c下的输入框输入为任意值 x,得到 {'b': {x:x} }
2. 在NamePath:['b']下的b.c下的输入框输入为空字符串,得到 {'b':{'':''}}
3. 在NamePath:['b']下的b.c下的输入框输入为'a', b.c丢失
4. 在NamePath:['b']下的b.c下的输入框输入为'range',b.range的值被覆盖

问题3
1. 在list.id中输入任意值,控制台没有输出内容

### 🏞 期望结果

请参考复现代码

### 💻 复现代码

[https://codesandbox.io/s/tong-bu-ti-jiao-jie-guo-dao-url-forked-w6lrzo](https://codesandbox.io/s/tong-bu-ti-jiao-jie-guo-dao-url-forked-w6lrzo)

### © 版本信息

- ProComponents 版本: [1.1.11]
- antd: [4.21.7]

**Comment by narutohinata** [comment]
#5592

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


Hi，感谢您使用ProForm，并向我们反馈问题。根据您的描述，我们已经通过您提供的复现代码进行了测试，并且发现以下问题：

问题1: 如果是有嵌套结构数据比如{a:{b:string}},希望变成{a:{new_b:string}},返回object是被放到根节点的
问题2: 返回的是字符串或者是字符串数组时,该返回值会作为namepath ,直接放置到当前元素的父元素上
问题3: formList 下的 formItem 中的所有transform不生效

我们对每个问题分别做如下的解答和调研：

问题1: 
通过代码测试，我们可以发现，在对嵌套字段做 transform 处理时，ProForm 的具体行为取决于 transform 函数的返回值类型，如果返回的也是一个对象，则会将这个对象直接合并到当前节点上（即根节点）；如果返回别的类型（如数组），则会将当前节点设置为当前节点所在对象的相应字段值。这一点在 ProForm 源码中也有明确的实现逻辑，可以在如下文件中查看：
https://github.com/ant-design/pro-components/blob/main/packages/form/src/components/FormItem/proFormField.tsx # L229

如果您希望直接修改子节点而不改变根节点，可以使用 lodash 库中的 set 函数，手动将子节点修改在原始数据中，示例代码如下：

```
const newForm = produce(formData, (draftData) => {
  _.set(draftData, ['a', 'new_b'], draftData.a.b);
  _.unset(draftData, ['a', 'b']);
});
```

问题2:
当 transform 函数返回值为字符串或字符串数组时，ProForm 会将其作为 namepath，将当前节点插入到名为 namepath 的父节点中。这一点也可以在 ProForm 源码中的如下位置代码上得到佐证：
https://github.com/ant-design/pro-components/blob/main/packages/form/src/components/FormItem/proFormField.tsx # L193-L203

为了解决这个问题，您可以在 transform 函数中将字符串或字符串数组类型的参数进行处理，并将其分离成一个层级嵌套的对象，示例代码如下：

```
const MY_VALUES = {
  A: {
    "a1.b1": "test111"
  },
  B: {
    c: "test2"
  },
  D: "test3",
  E: ["test4", "test5"]
};
function transformObjectByDot(object) {
  let result = {};
  Object.entries(object).forEach(([key, value]) => {
    let currentResult = result;
    let currentKey = key;
    if (typeof currentKey === "string") {
      const paths = currentKey.split(".");
      for (let i = 0; i < paths.length - 1; i++) {
        const path = paths[i];
        currentResult[path] = currentResult[path] || {};
        currentResult = currentResult[path];
      }
      currentKey = paths[paths.length - 1];
    }
    currentResult[currentKey] = value;
  });
  return result;
}
```

在调用 transform 函数的时候，可以这样使用：

```
const transformedFormData = transformObjectByDot(MY_VALUES);
```

这里已经把上述三个问题的共同解决方案提供给您，希望可以帮助到您，如果您在使用中遇到了其他问题，欢迎您及时跟我们反馈。谢谢！
