### ISSUE TITLE
🧐[问题] FormColSelect表单提交onFinish 怎样在values添加额外的字段？

### ISSUE THREAD

**Issue by sendy-dev** [ant-design/pro-components#5640]
比如说我现在的下拉列表字段名是goodsName
![image](https://user-images.githubusercontent.com/56161847/181184458-f01b4167-35e7-48f8-ad1a-0853a5cf5f7e.png)
 
onFinish是在项目里已经封装好的公用组件，如果是单个表单我知道可以使用values.label和values.value添加字段，但是如果onFinish是在项目里已经封装好的公用组件，我在onFinish提交的时候怎样在values怎样把这个选择的对象label和value一起拿到提交呢？有没有其他方法在特定的场景下修改要提交的字段名呢？
![image](https://user-images.githubusercontent.com/56161847/181184990-58b54bb2-0bc0-40dc-bc72-33784aa9080d.png)

**Comment by chenshuai2144** [comment]
labelnValues 然后要自己筛选
