### ISSUE TITLE
[bug] ProForm表单触发校验失败时，页面会闪烁

### ISSUE THREAD

**Issue by taajason** [ant-design/pro-components#5641]
环境：官方 npx create-umi myapp  创建的示例 
复现操作：登录页面，选择账户登录，在键盘输入与删除操作时，可见页面抖动
![image](https://user-images.githubusercontent.com/34680966/181191187-f103ac25-39ef-448e-b955-3b8344fa3fd1.png)
![image](https://user-images.githubusercontent.com/34680966/181191779-3ca18305-75ea-4cbe-b411-e669d994b03b.png)

antd 有类似 issue ：https://github.com/ant-design/ant-design/issues/28056

**Comment by chenshuai2144** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-725er?file=/index.css


配合这个demo修改一下

**Comment by carol99115566** [comment]
我试了上面 demo 不行，这样是生效的

**Comment by Gilinfen** [comment]
我去2年了不修复吗
