### ISSUE TITLE
ModalForm组件：layout设置为horizontal时，labelCol失效

### ISSUE THREAD

**Issue by ljkk** [ant-design/pro-components#5647]
ModalForm组件：layout设置为horizontal时，labelCol失效

示例：
https://codesandbox.io/s/modal-biao-dan-forked-7r43e8?file=/App.tsx:431-440

**Comment by drizzlesconsin** [comment]
没有失效，应该你窗口太小，命中了响应尺寸。span 换成响应尺寸 sm xs xl ...
