### ISSUE TITLE
🐛[BUG] EditableProTable 作为 ProForm 表单项，编辑多个数据情况下点击删除会清除其他行数据

### ISSUE THREAD

**Issue by BeDay** [ant-design/pro-components#5650]
直接以官网演示代码为例
https://procomponents.ant.design/components/editable-table/#%E4%B8%8E-formitem-%E9%85%8D%E5%90%88

![22(98L870J%{$7W`)G7IEWH](https://user-images.githubusercontent.com/9448445/181454374-f67335a4-bc16-4fd6-a29d-72569d84e7cb.png)

问题1. 多行编辑时，点击编辑行删除按钮 会将其他编辑行数据清除  或者 变为保存
问题2. 将数据全部删除后，点击添加一行数据出现 自动添加  活动名称1或者  活动名称2

![image](https://user-images.githubusercontent.com/9448445/181454592-7967b455-dc66-46fc-bf67-23102fcae998.png)

问题3 本地运行演示代码 首次点击编辑行 删除 出现下图 警告
 
![image](https://user-images.githubusercontent.com/9448445/181458439-715ffaa6-3582-419a-8c34-e4c42fe6c1b4.png)

**Comment by chenshuai2144** [comment]
已经解决了，ae3854a1b
