### ISSUE TITLE
🐛[BUG] ProFormText 等的width属性设置为"lg/md/xs" 时，打包后样式丢失

### ISSUE THREAD

**Issue by xiezht** [ant-design/pro-components#5652]
### 🐛 bug 描述

添加 width 属性到 ProFormText 等组件，值为 md/lg/xs/sm/... 皆可。

本地开发环境显示正常。

生产环境打包后，缺少了包含 ".pro-field-md" 等类名的样式表。

在 umi4 和 umi3 中表现略有不同，umi4 似乎是样式chunk加载时机问题。

这里提供umi3的复现步骤。

### 📷 复现步骤

```bash
npm i @ant-design/pro-cli -g
pro create myapp
```

在 `user/Login.tsx` 组件添加代码

```tsx
import {
  ProFormText,
  ProForm
} from '@ant-design/pro-components';

<ProForm>
  <ProFormText width="md"></ProFormText>
</ProForm>
```

本地开发环境显示宽度正常。

执行 `yarn run build` 后，部署静态资源，所有资源均可正常请求。

但页面样式显示为 全宽，而非 .pro-field-md 的宽度。

### 🏞 期望结果

本地开发环境与打包后页面样式一致。

### © 版本信息

- ProComponents 版本: latest
- umi 版本：umi3/um4
- 浏览器环境：chrome
- 开发环境: mac OS 

### 🚑 其他信息

打包前本地开发环境页面

![V2 _7%WP%DPH0_XL$0B4AFA](https://user-images.githubusercontent.com/18051618/181591543-602df0c8-dee6-4830-825f-a198b93cfdc7.png)

打包后页面
![YD2S74CI9K{Y518SHEG($0P](https://user-images.githubusercontent.com/18051618/181591211-341828b7-e1b8-43c3-8f6d-a71eaf1b65ca.png)

**Comment by hsbtr** [comment]
我的项目也出现了这个问题，请问你最后解决这个问题了吗

**Comment by xiezht** [comment]
> 我的项目也出现了这个问题，请问你最后解决这个问题了吗

我的解法比较粗暴，，直接在项目的 global.less 文件引入ProForm缺失的样式表

```
@import '~@ant-design/pro-form/es/index.less';
```

**Comment by chenshuai2144** [comment]
新版本中用css in js 已经解决了

**Comment by simplast** [comment]
> 新版本中用css in js 已经解决了

具体是哪个版本以后支持？
