### ISSUE TITLE
🧐[问题]   valueType: 'digit', 这个上下箭头能有参数去掉吗？丑死了。

### ISSUE THREAD

**Issue by chenyu1990** [ant-design/pro-components#5653]
server端语言强校验json类型，只有digit会转成int的类型
![微信截图_20220729114346](https://user-images.githubusercontent.com/15179320/181678485-4dbdf23c-3f2a-45e9-b22e-29ab5a57fbfa.png)

**Comment by echoyl** [comment]
提交前处理一下数据，而且你这个箭头的样式出了问题吧？

**Comment by chenyu1990** [comment]
感谢，重新 yarn 了一下，恢复了。
