### ISSUE TITLE
🧐[问题]Table工具类是否可以和搜索表单放一起

### ISSUE THREAD

**Issue by WT-Road** [ant-design/pro-components#5654]
### 🧐 问题描述

由于页面内容比较多,所以想紧凑点显示,期望把options内容放在search后面,展示成一行显示,目前是分区显示为两行,文档看了很久,也没找到太合适的方法

### 💻 示例代码
![WeChatc67f21b83df5fcd5a734c3832fc47d1e](https://user-images.githubusercontent.com/14371925/181702866-4bdeae93-c07f-4db3-af5a-7dbf8cd14796.png)

![WeChat066d6c8af54ec01c573272bcf14adf15](https://user-images.githubusercontent.com/14371925/181702943-4a734070-3ffa-4c53-a582-db45308d25d8.png)

**Comment by drizzlesconsin** [comment]
https://github.com/ant-design/pro-components/blob/83ecccdf3198e9986861185a585483af55723b68/packages/form/src/BaseForm/BaseForm.tsx#L46-L56
隐藏掉再自定义，后面查询按钮

参考：https://procomponents.ant.design/en-US/components/query-filter#query-filter-search

**Comment by WT-Road** [comment]
> https://github.com/ant-design/pro-components/blob/83ecccdf3198e9986861185a585483af55723b68/packages/form/src/BaseForm/BaseForm.tsx#L46-L56
> 
> 
> 隐藏掉另一个自定义，背面查询按钮
> 参考：https://procomponents.ant.design/en-US/components/query-filter#query-filter-search

如果是自定义内容我知道怎么写,但是我需要的是OptionConfig里的setting和fullScreen,这个怎么获取到呢?
![image](https://user-images.githubusercontent.com/14371925/181705388-a6c9f235-78ce-4590-b9fe-5e17cd030b33.png)

**Comment by WT-Road** [comment]
![image](https://user-images.githubusercontent.com/14371925/181705832-36d9a3fd-0992-479e-bfe6-4fcf656082b2.png)

**Comment by drizzlesconsin** [comment]
自定义

打破了模板设计的结构，都得自定义，别无他法。

> 当功能越加越多，放在上面早晚会有问题的。这个需求就应该顶回去。

**Comment by WT-Road** [comment]
> 自定义
> 
> 打破了模板设计的结构，都得自定义，别无他法。
> 
> > 当功能越加越多，放在上面早晚会有问题的。这个需求就应该顶回去。

好的, 感谢
