### ISSUE TITLE
🐛[BUG] modal form 的样式和最新版本antd不兼容

### ISSUE THREAD

**Issue by csc-bo** [ant-design/pro-components#5656]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

更新antd 4.22.2后样式错乱

### 📷 复现步骤

https://codesandbox.io/s/modal-biao-dan-forked-kwrd9b?file=/App.tsx

### 🏞 期望结果

和官网示例样式一致

### © 版本信息

- ProComponents 版本: 1.1.14
- umi 版本
- 浏览器环境
- 开发环境  mac OS

### 🚑 其他信息
<img width="736" alt="Screen Shot 2022-07-29 at 21 10 30" src="https://user-images.githubusercontent.com/59941818/181767422-6234feb0-74fb-4407-ae6f-8e22a5b4d8da.png">

**Comment by drizzlesconsin** [comment]
https://github.com/ant-design/ant-design/issues/36780

https://github.com/ant-design/ant-design/pull/36575#issuecomment-1199017020=

**Comment by zwd609258057** [comment]
遇到相同问题 + 1  @chenshuai2144

**Comment by liangchaofei** [comment]
![image](https://user-images.githubusercontent.com/37739354/182542695-78f4d6da-aa4b-4870-b3be-c4febc360437.png)

具体哪里不一样？ 输入框的长度？

**Comment by xiaobing1120** [comment]
最新版本已经解决  4.22.3
