### ISSUE TITLE
🧐[问题] 怎样更改antd的prefixCls，现在是css样式前缀改了，开发预览也是正确的，但是打包之后，还是ant的前缀？寻求帮助

### ISSUE THREAD

**Issue by bici-fed** [ant-design/pro-components#5657]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
打包的时候导入了css了吧 不用less是不能更换类名的哦
