### ISSUE TITLE
🐛[BUG]antd外层ConfigProvider配置了中文语言，里面使用了pro-components的EditableProTable却仍是英文语言

### ISSUE THREAD

**Issue by strongyc** [ant-design/pro-components#5661]
antd外层ConfigProvider配置了中文语言，里面使用了pro-components的EditableProTable却仍是英文语言
![image](https://user-images.githubusercontent.com/51156342/182018521-b98cf755-0700-416d-9e49-2ea67cf57f89.png)

**Comment by chenshuai2144** [comment]
设置下moment的语言

**Comment by hsulei** [comment]
父组件
import moment from "moment"
import 'moment/locale/zh-cn'
moment.locale('zh-cn')
在EditableProTable中的日期选择框中 today 显示是今天。 星期和月份依旧显示的是英文 pro-table 版本 2.78.2

**Comment by greenking19** [comment]
> 父组件 import moment from "moment" import 'moment/locale/zh-cn' moment.locale('zh-cn') 在EditableProTable中的日期选择框中 today 显示是今天。 星期和月份依旧显示的是英文 pro-table 版本 2.78.2 使用的是vite，这应该和vite没有关系吧？
脚手架生成的项目怎么配置呢？ 我找不到根组件啊

**Comment by hsulei** [comment]
解决了，还是vite的问题， import "moment/dist/locale/zh-cn"; 需要import这个
