### ISSUE TITLE
🐛[BUG]`protable`批量操作中，必须定义`defaultSelectedRowKeys`，否则`selectedRows`的类型会变为`undefined`

### ISSUE THREAD

**Issue by cgfeel** [ant-design/pro-components#5662]
### 🐛 bug 描述
先看文档是这么描述`tableAlertRender `类型的[文档链接](https://procomponents.ant.design/components/table#%E6%89%B9%E9%87%8F%E6%93%8D%E4%BD%9C)

```
({ selectedRowKeys: Key[], selectedRows: T[], onCleanSelected: ()=>void }) => ReactNode)|false
```
注意`selectedRows: T[]`，不是`selectedRows?: T[]`

- 而当我没有提供`defaultSelectedRowKeys: []`这个值的时候`selectedRows`的值是`undefined`，显然和描述不符。
- 我是从以前的版本升级上来的，以前`defaultSelectedRowKeys`没有定义的时候`selectedRows`默认是一个空数组

下面开始复现

### 📷 复现步骤
先看官方文档批量操作Demo，一切正常
https://codesandbox.io/s/v0m5es

我仅仅将`defaultSelectedRowKeys`删除，就会报错，因为`selectedRows`的值此时并非数组
https://codesandbox.io/s/biao-ge-pi-liang-cao-zuo-forked-x7uu8x?file=/App.tsx

### © 版本信息

- ProComponents 版本: 1.1.11
- 浏览器环境：chrome
- 开发环境：codesandbox

**Comment by liangchaofei** [comment]
我看下这个问题
