### ISSUE TITLE
🧐[问题] ProTable文档缺少pagination相关说明

### ISSUE THREAD

**Issue by zjstudy** [ant-design/pro-components#5665]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

ProTable官方文档缺少pagination相关说明，ProTable示例代码是有pagination这个配置项的，但是官方文档里面没找到任何关于这个配置项的说明

### 💻 示例代码

文档的代码可以看见使用了pagination配置，但是文档没有pagination这个配置的相关内容，建议加上相关内容的文档

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/19684111/182284455-978f662c-4477-497c-b5aa-4ae19b951d23.png)

**Comment by chenshuai2144** [comment]
去看看antd的文档，pro组件是antd的简单封装
