### ISSUE TITLE
🧐[问题]proTbale能不能自适应填充父容器后自动滚动高度

### ISSUE THREAD

**Issue by goodve** [ant-design/pro-components#567]
### 🧐 问题描述
proTbale 自适应填充父容器后滚动高度设置为容器高度？

@chenshuai2144

**Comment by chenshuai2144** [comment]
会死循环的，这种逻辑不敢做成自动化的

**Comment by johnnylc** [comment]
> 会死循环的，这种逻辑不敢做成自动化的

同样遇到这个需求，希望表格最大高度（包括表格的header footer等等）能够填充满父组件容器，当表格内容过多时表格内部滚动，而不在父容器滚动，请问这个需求有没有最佳实践或者推荐实现方式？

**Comment by goodve** [comment]
> > 会死循环的，这种逻辑不敢做成自动化的
> 
> 同样遇到这个需求，希望表格最大高度（包括表格的header footer等等）能够填充满父组件容器，当表格内容过多时表格内部滚动，而不在父容器滚动，请问这个需求有没有最佳实践或者推荐实现方式？

antd table也只能写死滚动的高度....

**Comment by chenshuai2144** [comment]
只要自动就一定会死循环的，
