### ISSUE TITLE
🧐[问题] 有没有办法在nextjs直接import而不是dynamic import使用。

### ISSUE THREAD

**Issue by simon-zhangmuye** [ant-design/pro-components#5670]
目前antd可以在nextjs中直接import，但是pro component还需要dynamic import。
这样出来就没有ssr效果了。请问大家有没有办法能够直接import。

**Comment by LengYXin** [comment]
不行 而且还有 样式丢失的问题

**Comment by chenshuai2144** [comment]
2.0 新版本使用了 css in js ，已经避免了这个问题
