### ISSUE TITLE
🐛[BUG] 如果通过 Form.useForm 传递了 form，那么 destroyOnClose 关闭自动重置表单就失效了

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/pro-components#5671]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

如果通过 Form.useForm 传递了 form，那么 destroyOnClose 关闭自动重置表单就失效了

### 📷 复现步骤

https://codesandbox.io/s/drawer-biao-dan-forked-zbryyu?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] 最新
- umi 版本 最新
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个你自己处理一下吧
