### ISSUE TITLE
👑 [需求]Layouts Form 可以提供更多的插槽选项吗

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/pro-components#5672]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

Form

### 🥰 需求描述

有些组件希望放置在容器内，而不是其 Form 内，比如另一个 Form，否则会出现表单嵌套警告

### 🧐 解决方案

bottom 则是在 Drawer 的底下，top 同理
![image](https://user-images.githubusercontent.com/37258382/182428108-35179f56-fdc2-43cf-8efc-42585444e3f0.png)

```tsx
<DrawerForm bottom={...} top={...}>
<ProFormText name="name" label="动作名称" placeholder="请输入" />
</DrawerForm>
```

or

```tsx
<DrawerForm renderFormWrapper={(formDom) => ...}>
<ProFormText name="name" label="动作名称" placeholder="请输入" />
</DrawerForm>
```

**Comment by chenshuai2144** [comment]
那你直接用 Drawer 就好了吧
