### ISSUE TITLE
🐛[BUG]ptoTable  简单来说 就是用表格的实例 tableField.current.reload()时候 假如我上次点击的分页器是在第四页 那么当tableField.current.reload()方法时候 在表格request属性里面打印params.curent不是1而是上一次点击的值  ui分页器停留在小于等于上次点击值

### ISSUE THREAD

**Issue by fengwei-ff** [ant-design/pro-components#5675]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fengwei-ff** [comment]
已经解决

**Comment by zjstudy** [comment]
@fengwei-ff  我也遇到了这个问题，请问你是怎么处理的

**Comment by zjstudy** [comment]
我也遇到这个问题了，不过后面在文档里面发现是有api可以直接用的, 其中reloadAndRest可以重置分页参数

![image](https://user-images.githubusercontent.com/19684111/184566308-3d6e4288-a8c7-4f7a-9bb1-fbc7ee6e196a.png)
