### ISSUE TITLE
ProTable中 使用request获取数据后，如何取出当前table的list数据呢？🧐[问题]

### ISSUE THREAD

**Issue by Lpbzzz** [ant-design/pro-components#5677]
### 🧐 问题描述

ProTable中 使用request获取数据后，如何取出当前table的list数据呢？
在columns 如何有没有api能获取list

**Comment by chenshuai2144** [comment]
postData | 对通过 request 获取的数据进行处理 | (data: T[]) => T[] | -
-- | -- | -- | --



这里面用ref 存一下吧
