### ISSUE TITLE
🐛[BUG]pro-layout@6.4.19启动报错

### ISSUE THREAD

**Issue by victorWuxz** [ant-design/pro-components#568]
### 📷 复现步骤
在umi项目中安装pro-layout@6.4.19版本，umi dev

提示rc-utils/useMergedState不存在，需要安装依赖

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个截图

**Comment by victorWuxz** [comment]
![image](https://user-images.githubusercontent.com/36194121/94005496-f4c81680-fdd0-11ea-9de5-77a5492bff70.png)

**Comment by victorWuxz** [comment]
![image](https://user-images.githubusercontent.com/36194121/94005622-1f19d400-fdd1-11ea-9e1d-7392c2321557.png)

**Comment by victorWuxz** [comment]
启动的问题解决了，网络问题，但启动后又有新的问题，截图如上

**Comment by victorWuxz** [comment]
> 来个截图

启动的问题解决了，网络问题，但启动后又有新的问题，截图如上

**Comment by chenshuai2144** [comment]
升级一下antd 的版本，这使用了antd@4.6.4 的新特性。

**Comment by Denver-Ning** [comment]
我遇到了同样的问题
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/66343210/157159786-71742a84-7f75-45f0-80e3-ab8995bd1447.png">

**Comment by Denver-Ning** [comment]
> 我遇到了同样的问题 <img alt="image" width="1680" src="https://user-images.githubusercontent.com/66343210/157159786-71742a84-7f75-45f0-80e3-ab8995bd1447.png">

已经解决，也是antd的问题
