### ISSUE TITLE
🐛[BUG]ProTable:当鼠标悬浮在某一行的时候，自定义的扩展按钮会显示不全 

### ISSUE THREAD

**Issue by elmelloi** [ant-design/pro-components#5680]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤

当鼠标悬浮在某一行的时候，自定义的扩展按钮会显示不全。在最新的antd中则不会有这样的情况（https://codesandbox.io/s/clever-moser-imbot7）。

### 💻 复现代码
https://codesandbox.io/s/cha-xun-biao-ge-forked-tq5vst?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
去antd 看看？这个用法我都没见过
