### ISSUE TITLE
🐛[BUG] EditableProTable 处于编辑状态下被删除后 新增数据异常回显

### ISSUE THREAD

**Issue by Hexl2018** [ant-design/pro-components#5682]
### 🐛 bug 描述
EditableProTable 处于编辑状态下被删除后 新增数据异常回显

### 📷 复现步骤

https://procomponents.ant.design/components/editable-table#%E4%B8%8E-formitem-%E9%85%8D%E5%90%88

1. 删除已有的两条数据
2. 新增三条以上的数据
3. 从上到下依次删除
4. 此时第一列数据异常回显了
![image](https://user-images.githubusercontent.com/36258693/182756334-02a49d8b-477b-4368-b90a-1bfe7df0c165.png)

### 🏞 期望结果

解决bug

### 💻 复现代码

https://procomponents.ant.design/components/editable-table#%E4%B8%8E-formitem-%E9%85%8D%E5%90%88

### © 版本信息

- ProComponents 版本: [e.g. 1.1.1]
- umi 版本：^3.5.0
- 浏览器环境 edge 103.0.1264.77
- 开发环境 [e.g.  win11]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/36258693/182756342-8fbf87d3-fbcd-4cb3-9742-addce505f186.png)

**Comment by wangmeijian** [comment]
duplicate issue https://github.com/ant-design/pro-components/issues/5600

**Comment by dglxiaoyi** [comment]
请问修复后的版本是多少。我更新到 "@ant-design/pro-table": "^2.80.4",还是有上述问题

**Comment by Hexl2018** [comment]
> 请问修复后的版本是多少。我更新到 "@ant-design/pro-table": "^2.80.4",还是有上述问题

并没解决
