### ISSUE TITLE
🧐[问题]pro-table 如何自定义 loading 是否显示？

### ISSUE THREAD

**Issue by forzalianjunting** [ant-design/pro-components#569]
### 🧐 问题描述

目前需求为首次获取或者用户主动点击获取的时候需要 loading 状态，但当页面轮询的时候不需要 loading，请问目前的 pro-table 能实现这个效果吗？

### 💻 示例代码

无

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
这个 pr  https://github.com/ant-design/pro-components/pull/563   发了，你就可以使用了
