### ISSUE TITLE
🐛[BUG]ProFormList中使用action.setCurrentRowData设置表单值的时候 会导致整个FormList的重新render ProFormSelect的request会重新发起不必要的请求

### ISSUE THREAD

**Issue by sunhailongisme** [ant-design/pro-components#5690]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

🐛[BUG]ProFormList中在ProFormSelect的onchange里使用action.setCurrentRowData设置表单值的时候 会导致整个FormList的重新render ProFormSelect的request会重新发起不必要的请求，如果select的option都是异步获取的话 会产生好多无用接口请求。

### 💻 复现代码

<ProFormList
              name={['focusSkuList']}
              copyIconProps={false}
              min={1}
              max={3}
              itemContainerRender={(doms) => {
                return (
                  <ProForm.Group spaceProps={{ style: { width: '100%' }, className: styles['add-sku-form-item'] }}>
                    {doms}
                  </ProForm.Group>
                );
              }}
              initialValue={[
                {
                  label: '333',
                  value: '333',
                },
              ]}
            >
              {(f, index, action) => {
                console.log('action: ', action);
                console.log('index: ', index);
                console.log('f: ', f);
                return (
                  <Row gutter={8}>
                    <Col span={4}>
                      <ProFormSelect
                        label="品牌"
                        name="brand"
                        rules={[{ required: true, message: '请选择' }]}
                        placeholder="请选择"
                        request={async () => {
                          return await skuService.getSapBrandList().then((res) => {
                            return res.data;
                          });
                        }}
                        fieldProps={{
                          labelInValue: true,
                          showSearch: true,
                          filterOption: true,
                          // searchOnFocus: true,
                          fieldNames: {
                            label: 'brandName',
                            value: 'brandCode',
                          },
                          onChange: () => {
                            action.setCurrentRowData({ sku: undefined });
                          },
                          // onChange: brandChange
                        }}
                      />
                    </Col>
                    <Col span={4}>
                      <ProFormSelect
                        label="子品牌"
                        name="subBrand"
                        dependencies={['brand']}
                        rules={[{ required: true, message: '请选择' }]}
                        placeholder="请选择"
                        fieldProps={{
                          labelInValue: true,
                          onChange: () => {
                            action.setCurrentRowData({ sku: undefined });
                          },
                          fieldNames: {
                            label: 'subBrandName',
                            value: 'subBrandCode',
                          },
                        }}
                        request={async (p) => {
                          console.log('p: ', p);
                          if (!p?.brand?.value) {
                            return [];
                          }
                          return await skuService.getSapSubBrandList({ brandCode: p?.brand?.value }).then((res) => {
                            return res.data?.subBrandList;
                          });
                        }}
                      />
                    </Col>
                    <Col span={3}>
                      <ProFormSelect
                        label="容量"
                        name="capacity"
                        rules={[{ required: true, message: '请选择' }]}
                        placeholder="请选择"
                        request={async () => {
                          return skuService.skuNorms({ type: 1 }).then((res) => {
                            return res.data;
                          });
                        }}
                        fieldProps={{
                          labelInValue: true,
                          showSearch: true,
                          filterOption: true,
                          fieldNames: {
                            label: 'ctnName',
                            value: 'ctnCode',
                          },
                          onChange: () => {
                            action.setCurrentRowData({ sku: undefined });
                          },
                        }}
                      />
                    </Col>
                    <Col span={3}>
                      <ProFormSelect
                        label="包装"
                        name="pack"
                        rules={[{ required: true, message: '请选择' }]}
                        placeholder="请选择"
                        request={async () => {
                          return skuService.skuNorms({ type: 2 }).then((res) => {
                            return res.data;
                          });
                        }}
                        fieldProps={{
                          labelInValue: true,
                          fieldNames: {
                            label: 'ctnName',
                            value: 'ctnCode',
                          },
                          onChange: () => {
                            action.setCurrentRowData({ sku: undefined });
                          },
                        }}
                      />
                    </Col>
                    <Col span={4}>
                      <ProFormDependency key="sku" name={['brand', 'subBrand', 'capacity', 'pack']}>
                        {({ brand, subBrand, capacity, pack }) => {
                          return (
                            <PaginationProFormSelect
                              label="产品"
                              name="sku"
                              rules={[{ required: true, message: '请选择' }]}
                              placeholder="请选择"
                              debounceTime={500}
                              pagination
                              keyWordsName="skuName"
                              fieldProps={{
                                showSearch: true,
                                filterOption: false,
                                labelInValue: true,
                                fieldNames: {
                                  label: 'skuName',
                                  value: 'skuCode',
                                },
                                onChange: (e) => skuChange(e, action),
                              }}
                              customRequest={async (p) => {
                                if (!(brand || subBrand || capacity || pack || p?.skuName)) {
                                  return [];
                                }
                                console.log('p: ', p);
                                return await skuService
                                  .externalSkuList({
                                    brandCode: brand?.value,
                                    subBrandCode: subBrand?.value,
                                    capacityCode: capacity?.value,
                                    packCode: pack?.value,
                                    ...p,
                                  })
                                  .then((res) => {
                                    return res.data?.list;
                                  });
                              }}
                            />
                          );
                        }}
                      </ProFormDependency>
                    </Col>

                    <Col span={2}>
                      <ProFormDependency key="skuCode" name={['sku']}>
                        {({ sku }) => {
                          return (
                            <Form.Item label="产品编码">
                              <span>{sku?.productCode}</span>
                            </Form.Item>
                          );
                        }}
                      </ProFormDependency>
                    </Col>
                    <Col span={3}>
                      <ProFormDependency key="gradeName" name={['sku']}>
                        {({ sku }) => {
                          return (
                            <Form.Item label="档次">
                              <span>{sku?.productName}</span>
                            </Form.Item>
                          );
                        }}
                      </ProFormDependency>
                    </Col>
                  </Row>
                );
              }}
            </ProFormList>

### © 版本信息

- ProComponents 版本: pro-form 1.70.2
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
故意这么设计的，为了保证数据都是及时的，如果想要定向渲染可以使用 shoudupdate 手动控制一下

**Comment by sunhailongisme** [comment]
我是这么想的pro-form的组件 request 方法应在初次渲染 和 依赖的parames 变化的时候才执行
