### ISSUE TITLE
🐛[BUG] ProLayout menu高亮问题

### ISSUE THREAD

**Issue by xoptimal** [ant-design/pro-components#5691]
### 🐛 bug 描述

配置一个3级菜单
micro
|-------micro-1
           |-------micro/sub-app-1/list  (访问这级的时候, 因为被隐藏掉了, 预期正常应该高亮micro-1,  结果是触发了一个折叠操作

### 🏞 期望结果

期待正常选中, 没有触发额外的折叠事件

### 💻 复现代码

```
name: 'micro',
path: '/micro',
routes: [
    {
        name: 'micro-1',
        path: '/micro/sub-app-1',
        microApp: 'sub-app-1',
        layout: true,
        exact: false,
        hideChildrenInMenu: true,
        routes: [
            {
                name: 'micro-1-list',
                path: '/micro/sub-app-1/list',
                exact: false,
            },
            {
                name: 'micro-1-sub',
                path: '/micro/sub-app-1/sub',
                exact: false,
            },
            {
                name: 'micro-1-detail',
                path: '/micro/sub-app-1/detail',
                exact: false,
            }
        ]
    }
```

### © 版本信息

- ProComponents 版本: 4.x
- umi 版本: 4.x
- 浏览器环境: google chrome
- 开发环境: windows

**Comment by chenshuai2144** [comment]
`"micro/sub-app-1/list".split("/")`

layout 的算法就是这么简单，别的花活都要自定义。尽量保持父子之间纯粹的关系把

**Comment by cuijiudai** [comment]
> 



> `"micro/sub-app-1/list".split("/")`
> 
> layout 的算法就是这么简单，别的花活都要自定义。尽量保持父子之间纯粹的关系把

这个问题这么多人提了，能来个开关吗？为什么非要按照 path 来，那路由树的优先级不应该比这个高吗？
