### ISSUE TITLE
🐛[BUG]ProList设置itemCardProps的extra无效

### ISSUE THREAD

**Issue by astudentat** [ant-design/pro-components#5692]
### 🐛 bug 描述

设置extra无效，通过codesandbox修改官网demo也无效

### 💻 复现代码

https://codesandbox.io/s/qia-pian-lie-biao-forked-l1w378?file=/App.tsx:1712-1714

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kiner-tang** [comment]
不太明白你的意思，`extra`目前是鼠标移入卡片时才会显示的哟，你上面给出的实例，鼠标移入卡片是有显示`extra`的
