### ISSUE TITLE
🧐[问题]在Antd项目中使用ProTable，分页显示英文，配置了中文也没用

### ISSUE THREAD

**Issue by MARKX97** [ant-design/pro-components#5695]
### 🧐 问题描述

package.json:{
"antd": "^4.18.2",
"@ant-design/pro-components": "^1.1.14",
 "@ant-design/pro-table": "^2.78.3",
}

在Antd项目中使用ProTable，pagination={{
        showQuickJumper: true,
      }}
PorTable显示英文

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/50320229/183361149-54bb09e9-54ec-449d-9962-d1ff167a8a64.png)
![image](https://user-images.githubusercontent.com/50320229/183361209-587ced57-5fc2-46af-9d86-a5dd64697779.png)

**Comment by chenshuai2144** [comment]
antd 的provide是不是没有配置？

**Comment by MARKX97** [comment]
配置了
![image](https://user-images.githubusercontent.com/50320229/183548665-8da7c06a-1f94-4923-9b29-3c4d6d21b8f9.png)

**Comment by greenking19** [comment]
> 配置了 ![image](https://user-images.githubusercontent.com/50320229/183548665-8da7c06a-1f94-4923-9b29-3c4d6d21b8f9.png)

你是用umi生成的项目吗？ 我用umi生成的项目 配置了默认英文 日历组件都是英文的。  我不知道怎么去修复。 umi生成的项目 没有根组件 ConfigProvider也不知道放哪里

**Comment by MARKX97** [comment]
> > 配置了 ![image](https://user-images.githubusercontent.com/50320229/183548665-8da7c06a-1f94-4923-9b29-3c4d6d21b8f9.png)
> 
> 你是用umi生成的项目吗？ 我用umi生成的项目 配置了默认英文 日历组件都是英文的。 我不知道怎么去修复。 umi生成的项目 没有根组件 ConfigProvider也不知道放哪里

不是

**Comment by Mzhang1994** [comment]
> > 配置了 ![image](https://user-images.githubusercontent.com/50320229/183548665-8da7c06a-1f94-4923-9b29-3c4d6d21b8f9.png)
> 
> 你是用umi生成的项目吗？ 我用umi生成的项目 配置了默认英文 日历组件都是英文的。 我不知道怎么去修复。 umi生成的项目 没有根组件 ConfigProvider也不知道放哪里

我这边是开发环境没问题，一到生产环境日历组件就变成部分英文。也不知道是不是antd那边的问题。

**Comment by greenking19** [comment]
> > > 配置了 ![image](https://user-images.githubusercontent.com/50320229/183548665-8da7c06a-1f94-4923-9b29-3c4d6d21b8f9.png)
> > 
> > 
> > 你是用umi生成的项目吗？ 我用umi生成的项目 配置了默认英文 日历组件都是英文的。 我不知道怎么去修复。 umi生成的项目 没有根组件 ConfigProvider也不知道放哪里
> 
> 我这边是开发环境没问题，一到生产环境日历组件就变成部分英文。也不知道是不是antd那边的问题。

我开发环境都是这样 嗨不知道怎么去搞了

**Comment by Mzhang1994** [comment]
> > > > 配置了 ![image](https://user-images.githubusercontent.com/50320229/183548665-8da7c06a-1f94-4923-9b29-3c4d6d21b8f9.png)
> > > 
> > > 
> > > 你是用umi生成的项目吗？ 我用umi生成的项目 配置了默认英文 日历组件都是英文的。 我不知道怎么去修复。 umi生成的项目 没有根组件 ConfigProvider也不知道放哪里
> > 
> > 
> > 我这边是开发环境没问题，一到生产环境日历组件就变成部分英文。也不知道是不是antd那边的问题。
> 
> 我开发环境都是这样 嗨不知道怎么去搞了

我试了下，你把moment的包版本别写死了，开发环境倒是可以解决。但生产环境是真的搞不懂。

**Comment by greenking19** [comment]
> > antd的provide是不是没有配置？
> 
> 是pro-components的问题， import ProTable from '@ant-design/pro-table'; // 分页可以正常显示中文 import { ProTable } from '@ant-design/pro-components'; // 分页只能显示英文 希望能早点修复，感谢！

ProTable的 日期选择器 月份是英文的 你遇到吗？ 真的好奇怪 我心在都不知道怎么去配置 我用的是 @antd/pro-cli生成的项目。
其他issue说配置Provider但是 cli生成的项目都没有跟组件 难受

**Comment by greenking19** [comment]
> > > > antd的provide是不是没有配置？
> > > 
> > > 
> > > 是pro-components的问题， import ProTable from '@ant-design/pro-table'; // 分页可以正常显示中文 import { ProTable } from '@ant-design/pro-components'; // 分页只能显示英文 希望能早点修复，感谢！
> > 
> > 
> > ProTable的 日期选择器 月份是英文的 你遇到吗？ 真的好奇怪 我心在都不知道怎么去配置 我用的是 @antd/pro-cli生成的项目。 其他issue说配置Provider但是 cli生成的项目都没有跟组件 难受
> 
> 最新版本的antd修复这个问题了
> 
> 首先安装npm-check-updates插件： cnpm i -g npm-check-updates
> 
> 然后检查是否有更新： ncu -u
> 
> 最后确认更新： cnpm install （我这边antd ^4.20.7 → ^4.22.4 升级后日期显示英文的问题就解决了，您也可以试一下哈）

我升级了 但是没见效果。。。你是用 cli生成的项目吗？ 具体怎么配置中文啊

**Comment by MARKX97** [comment]
> 
我这里用的是import ProTable from '@ant-design/pro-table' ，antd也升到最新的了，分页还是显示英文

**Comment by chenshuai2144** [comment]
要用provide 配置一下的，或者配置一下 umi 的 locale

**Comment by greenking19** [comment]
> 要用provide 配置一下的，或者配置一下 umi 的 locale

我用的antd-pro 已经配置了 umi的locale 但是还是英文的， provide怎么用呢？ 找不到根组件啊。试过包ProTable组件 但是没有效果啊

**Comment by codedart2018** [comment]
webpack4直接购建的也遇到此问题了　日历组件英文！　provide配置也没有用！

**Comment by BallerJay** [comment]
> provide 配置

我也遇到了这样的问题，请问你说如何解决的

**Comment by MARKX97** [comment]
> > provide 配置
> 
> 我也遇到了这样的问题，请问你说如何解决的

我现在是
`{    "@ant-design/pro-components": "^2.6.35",
    "antd": "^5.12.7",
}`
`import { ProTable } from '@ant-design/pro-components'
`
App.tsx
`<ConfigProvider locale={locale.zhCN}>`
可以尝试一下

**Comment by BallerJay** [comment]
> > > provide 配置
> > 
> > 
> > 我也遇到了这样的问题，请问你说如何解决的
> 
> 我现在是 `{ "@ant-design/pro-components": "^2.6.35", "antd": "^5.12.7", }` `import { ProTable } from '@ant-design/pro-components' ` App.tsx `<ConfigProvider locale={locale.zhCN}>` 可以尝试一下

试过了，还是不行。我的{ "@ant-design/pro-table": "^2.48.0", "antd": "4.22.8"}
