### ISSUE TITLE
🐛[BUG]Uncaught RangeError: Maximum call stack size exceeded     at Function.isArray (<anonymous>)

### ISSUE THREAD

**Issue by coderlcb** [ant-design/pro-components#5697]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

antd pro中使用LoginForm组件登录时，路由跳转，报错。

### © 版本信息

- ProComponents 版本: 1.1.1
- @umijs/max:  4.0.7,
- 浏览器环境：chrome
- 开发环境 : windows

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/55039022/183386793-cb0ef0d0-7c07-422e-b7ed-767f4d6e82e7.png)

**Comment by chenshuai2144** [comment]
建议清楚锁包之后升级依赖。

如果还是死循环了，是不是 登录其实没有成功。

去 app.tsx 下面看看跳转为啥失败，如果代码没问题，

**Comment by coderlcb** [comment]
> 建议清楚锁包之后升级依赖。
> 
> 如果还是死循环了，是不是 登录其实没有成功。
> 
> 去 app.tsx 下面看看跳转为啥失败，如果代码没问题，只能用二分法删除一半的代码看看，慢慢找到问题所在的代码

谢谢，删了yarn.lock就没报错了。。。。
