### ISSUE TITLE
🧐[问题]ProTable 的分页无法手动更新 pagination 中的 current 字段吗

### ISSUE THREAD

**Issue by soulcm** [ant-design/pro-components#5698]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

ProTable 设置 pagination 的 current 字段，但点击分页之后，仍然会自动跳转分页，分页参数无法受控

### 💻 示例代码

https://codesandbox.io/s/wu-toolbar-de-biao-ge-forked-r56tb1

示例代码中，点击分页就自动跳转了，但 current 设置的是1，无法受控

**Comment by ChenAlmost** [comment]
更新到了  `"@ant-design/pro-table": "2.80.4"` ，current 字段还是不受控。
