### ISSUE TITLE
👑 [需求] 可以出一个操作指引组件吗？

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#5699]
https://devui.design/components/zh-cn/steps-guide/demo#basic-usage

<img width="653" alt="image" src="https://user-images.githubusercontent.com/30397655/183604993-338eb482-a282-4bb7-b1d8-66d3b70f9b03.png">

**Comment by chenshuai2144** [comment]
暂时不会搞，我们主要还是crud
