### ISSUE TITLE
🧐[问题]pro-table中使用了renderFormItem，在type=form时，这个渲染的宽度和其他自动渲染的宽度不同

### ISSUE THREAD

**Issue by lhf-nife** [ant-design/pro-components#570]
### 🧐 问题描述

pro-table中使用了renderFormItem，在type=form时，这个渲染的宽度和其他自动渲染的宽度不同
其他自动渲染的宽度中，style中width是有固定值的，而通过renderFormItem渲染出来的宽度是100%
如下图所示
![image](https://user-images.githubusercontent.com/27995008/93970904-9cc5eb80-fda1-11ea-821a-f0ec3a58859f.png)

### 💻 示例代码
const columns: ProColumns<any>[] = [
    {
      title: '人员姓名',
      dataIndex: 'name',
      renderFormItem: (item, { defaultRender, ...rest }, form) => {
        return <Input />
      }
    },
....
];

望解答，谢谢！

**Comment by chenshuai2144** [comment]
`renderFormItem `是你自定义的，我们没有自动包裹，你可以手动设置一下

**Comment by lhf-nife** [comment]
> `renderFormItem `是你自定义的，我们没有自动包裹，你可以手动设置一下

就是我需要自己去设定里面的input的宽度，让其去跟你们的宽度达到一致吗？但是我设置了你们的328的宽度的话，在search栏里，宽度又无法跟其他一致了，我没找到对应的可以达到一致宽度的配置。
还是说我直接参考你们自动包裹的地方的代码，去包裹一下呢？
