### ISSUE TITLE
🐛[BUG]Table dataIndex重复时，设置栏滚动后显示异常 操作失效

### ISSUE THREAD

**Issue by tong233** [ant-design/pro-components#5703]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

列dataIndex有重复时，并且列数足够多列设置出现滚动条，设置栏滚动后会全部变成重复那列的标题，拖拽和显示隐藏功能也失效了

### 📷 复现步骤
标题5 dataIndex="title4" 和标题4重复，列设置滚动一下就不正常了

### 💻 复现代码

https://codesandbox.io/s/cha-xun-biao-ge-forked-7shw4y?file=/App.tsx:1722-1742

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/21073132/184074026-699644e4-11e8-496d-ac17-657cb619061b.png)

**Comment by kiner-tang** [comment]
`dataIndex`作为标识该列数据的唯一标识，本来就不应该重复呀。你在什么场景下一定要`dataIndex`重复呢？

**Comment by kiner-tang** [comment]
如果`dataIndex`不可避免会出现重复的，请设置`key`字段，并且确保每一列的`key`是唯一，这样也可以正常渲染
