### ISSUE TITLE
EditableProTable columns中的renderFormItem form.getFieldValue(dataIndex)实例无法获取到编辑单元的值，也不能使用setFieldsValue设置值

### ISSUE THREAD

**Issue by soeasyjx** [ant-design/pro-components#5704]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

EditableProTable columns中的renderFormItem form.getFieldValue(dataIndex)实例无法获取到编辑单元的值

### 📷 复现步骤

columns.renderFormItem 中使用 form.getFieldValue(dataIndex) 能得到编辑单元格的值

const voucherRulesColumns: ProColumns<IVoucherRuleEditTableItem>[] = [
{
      title: 'sku',
      dataIndex: 'skuInfo',
      valueType: 'select',
      render: (_, row) => {
        console.log('afdfdsfds', row);
        return row?.skuInfo?.label;
      },
      renderFormItem(_, { record },form) {
        const { goodsID } = record!;
        form.getFieldValue('skuInfo');
        return <SkuSelectFormItem goodsID={goodsID} />;
      },
      formItemProps: () => {
        return {
          validateTrigger: 'onSubmit',
          rules: [{ required: true, message: '此项为必填项' }],
        };
      },
    },
{
      title: 'sku',
      dataIndex: 'test',
      valueType: 'select',
      render: (_, row) => {
        console.log('afdfdsfds', row);
        return row?.skuInfo?.label;
      },
      renderFormItem(_, { record },form) {
        form.getFieldValue('skuInfo');
        return <SkuSelectFormItem goodsID={goodsID} />;
      },
      formItemProps: () => {
        return {
          validateTrigger: 'onSubmit',
          rules: [{ required: true, message: '此项为必填项' }],
        };
      },
    };
]
<EditableProTable
        name="voucherRules"
        columns={voucherRulesColumns}
        editableFormRef={edittableref}
        formItemProps={{
          label: '适用类型',
        }}
        size="small"
        rowKey="virtualId"
        value={dataSource}
        onChange={onTableChange}
        recordCreatorProps={{
          record: () =>
            (({
              virtualId: (Math.random() * 1000000).toFixed(0),
            } as unknown) as IVoucherRuleEditTableItem),
          creatorButtonText: '新增适用规则',
        }}
        editable={{
          type: 'multiple',
          editableKeys,
          onChange: setEditableRowKeys,
          actionRender: (row, config, defaultDom) => {
            return [defaultDom.save, defaultDom.delete];
          },
        }}
      />

### © 版本信息

- ProComponents 版本: [e.g. 1.1.14]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by bugfix2020** [comment]
+1

**Comment by chenshuai2144** [comment]
` form.getFieldValue([rowkey, dataIndex])`

这样搞
