### ISSUE TITLE
🐛[BUG] ProForm中valueType为money时, 输入框中的金额没有格式化, 小数点也没有显现

### ISSUE THREAD

**Issue by jaykou25** [ant-design/pro-components#5707]
### 📷 复现步骤
https://codesandbox.io/s/schema-dependencies-forked-3vit1b?file=/App.tsx

**Comment by kiner-tang** [comment]
可以在`fieldProps`中传入格式化函数(`formatter`,`parser`)实现金额格式化显示，可以参考一下这个：
https://codesandbox.io/s/currency-wrapper-antd-input-3ynzo?file=/src/index.js

**Comment by jaykou25** [comment]
恩，这样确实可以实现。但是money组件不就是要实现这部分的功能吗。我看源码里有用到formatter和parser

**Comment by kiner-tang** [comment]
> 恩，这样确实可以实现。但是money组件不就是要实现这部分的功能吗。我看源码里有用到formatter和parser

看起来是内置的格式化正则表达式有问题
