### ISSUE TITLE
🐛[BUG] pro-table 组件提供的分页能力拓展性太弱

### ISSUE THREAD

**Issue by dmljc** [ant-design/pro-components#571]
### 🐛 bug 描述

pro-table 组件提供的分页能力拓展性太弱。另外，建议  “第 1-10 条/总共 30 条” 文案放在左侧，并且文案颜色稍微浅些。

### 📷 复现步骤

目前 pro-table 组件分页器默认每页条数 defaultPageSize 是20条，但是很多场景下我们需要默认显示10条或者30条的数据。另外，建议  “第 1-10 条/总共 30 条” 文案放在左侧，放在右侧和分页器的操作性按钮放在一起显得特别拥挤，不够美观。如果此文案的颜色能稍微浅一些会更优雅。

### 🏞 期望结果

1、希望组件能够提供入口支持用户自定义 defaultPageSize。
2、“第 1-10 条/总共 30 条” 相关文案放在左侧， 文案颜色稍微浅一些。

### 💻 复现代码

![image](https://user-images.githubusercontent.com/28803668/93977776-93db1700-fdad-11ea-99ef-20cd6edfd15e.png)

### © 版本信息

- "@ant-design/pro-table":版本: [e.g. 2.8.1]
- umi 版本:3.2.2
- 浏览器环境：chrome 版本号为：85.0.4183.102（正式版本
- 开发环境 [mac OS 版本：10.15.6 ]

**Comment by lixin0724** [comment]
1、props有个pagination的接口可以配置分页相关配置

**Comment by lixin0724** [comment]
> 1、props有个pagination的接口可以配置分页相关配置，具体API和antd的分页器应该是一致的
> https://ant.design/components/pagination-cn/
> 我用的2.4.4的版本是可以配每页多少条记录的,新版应该也一样
> 2、自己写样式覆盖应该还是比较容易实现的吧
> ![image](https://user-images.githubusercontent.com/53106140/93985303-71e69200-fdb7-11ea-9d13-be7674d51421.png)


![image](https://user-images.githubusercontent.com/53106140/93985341-83c83500-fdb7-11ea-92d5-6f3e9a95fb29.png)
