### ISSUE TITLE
ProForm的验证提示文字被遮盖，样式有问题🐛[BUG]

### ISSUE THREAD

**Issue by hst-Sunday** [ant-design/pro-components#5711]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProForm的验证提示文字被遮盖，样式有问题

### 📷 复现步骤
![1660272197975](https://user-images.githubusercontent.com/18478530/184275586-31030f69-02bf-4efd-b1e1-2b251cc352a2.jpg)

![1660273780357](https://user-images.githubusercontent.com/18478530/184277913-d17446f6-f799-44c0-b568-6b76b369bcac.jpg)

### 🏞 期望结果

提示文字不该被遮挡

### © 版本信息

- ProComponents 版本: latest
- umi 版本
- 3.5.0
- 浏览器环境
- chrome latest
- 开发环境 [e.g. mac OS]
- mac os latest

**Comment by drizzlesconsin** [comment]
antd 新版有调整过 Form.Item 结构

要看你是不是有重置过样式, eg.
```css
.ant-form-item-with-help {
    margin-bottom: 0;
}
```

**Comment by hst-Sunday** [comment]
没有重置过样式 @drizzlesconsin

**Comment by hst-Sunday** [comment]
调整antd的版本至4.21.7 正常

**Comment by chenshuai2144** [comment]
升级到最新的antd 能解决

**Comment by hst-Sunday** [comment]
@chenshuai2144 已将antd 和 antd-components 的依赖更新至最新的版本，问题
![1661743628606](https://user-images.githubusercontent.com/18478530/187117264-9aa3330f-7ff0-4d01-a175-21619b6cd9f9.jpg)
还在

**Comment by hst-Sunday** [comment]
![1661743832036](https://user-images.githubusercontent.com/18478530/187117540-5f8aa385-beaf-4bd2-b13e-eff5f4e54347.jpg)
勾掉 display:flex 正常

**Comment by hst-Sunday** [comment]
还有 ProForm 的属性 layout="vertical" 失效了
