### ISSUE TITLE
🧐[问题]ProTable 自定义查询表单的数据如何传给 request 的 params？

### ISSUE THREAD

**Issue by KingThq** [ant-design/pro-components#572]
### 🧐 问题描述

自定义查询 form，如何把提交的数据交给 request 的 params？

**Comment by chenshuai2144** [comment]
自动的，和 antd 的 FormItem 行为是一致的

**Comment by KingThq** [comment]
我的意思是自己写一个 form 不用 ProTable 封装的 form ，能做到将数据传给 request 的 params 吗？或者说怎么触发 request 方法并把 form 的数据传过去？

**Comment by chenshuai2144** [comment]
params | 用于 request 查询的多余参数，一旦变化会触发重新加载 | object | -
-- | -- | -- | --




这个 api
