### ISSUE TITLE
🐛[BUG] 表格rowKey失效问题，EditableProTable内存泄漏

### ISSUE THREAD

**Issue by neo-of-matrix** [ant-design/pro-components#5726]
### 🐛 bug 描述

问题一：表格rowKey失效问题
问题二：表格点击操作按钮，弹出窗口里面有EditableProTable，进行保存操作会有内存泄漏问题

### 📷 复现步骤

https://codesandbox.io/s/modal-biao-dan-forked-gcoqtc

### 🏞 期望结果

rowKey生效，内存不会泄漏

### © 版本信息

react 17.0.2
react-dom 17.0.2
@ant-design/pro-components 1.1.9
antd 4.21.6

**Comment by chenshuai2144** [comment]
搞个最小重现吧，这么多代码。感觉像对着代码算命

**Comment by chenshuai2144** [comment]
key 的问题是你哪个地方忘记写的数组的key了，和rowkey没有关系
