### ISSUE TITLE
🧐[问题] nextjs12.2.4版本中引入pro-table样式没引入

### ISSUE THREAD

**Issue by yangxiaoguai132** [ant-design/pro-components#5727]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

在next的12.2.4版本中使用proComponnets组件，引入了pro-table，但是table的样式没有引入，antd的table是没有问题的
<img width="420" alt="image" src="https://user-images.githubusercontent.com/17949045/184780590-c29a1d22-ad86-4563-a4f3-5403a610948c.png">

**Comment by chenshuai2144** [comment]
proComponnets 都是依赖的less，，你要配置 下less-loader
