### ISSUE TITLE
🐛[BUG] schemaForm 配置了 required: true 不显示 *

### ISSUE THREAD

**Issue by alicejxr** [ant-design/pro-components#5728]
### 🐛 bug 描述

schemaForm column 配置，配置了下面的属性，但是没有显示 * 标识

`formItemProps: {
        rules: [
            { required: true, message: '请填写' },
        ],
 },`

### 📷 复现步骤

https://codesandbox.io/s/schema-dependencies-forked-xxm43c?file=/App.tsx

查看「必填但没显示* 」配置项，配置 required: true 不生效

### 🏞 期望结果

查看「必填但没显示* 」配置项，配置 required: true 生效
### © 版本信息

- @ant-design/pro-components 1.1.15
- antd 4.22.3
- react 18.2.0
- react-dom 18.2.0

### 🚑 其他信息
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/18376661/184788570-b47327ad-9a3d-43ef-8368-ec8194f214d8.png">

**Comment by alicejxr** [comment]
问题解决了，required: true 需要添加到 fieldProps 中，而不是 formItemProps 中的 rules 中，是有什么区别吗？

**Comment by alicejxr** [comment]
required: true 需要添加到 fieldProps 中，虽然可以显示 *，但是 submit 时不会进行必填校验，有没有更具体的文档说明呢

**Comment by chenshuai2144** [comment]
antd 系列也不支持的，用 formItemProps.rules 吧
