### ISSUE TITLE
🧐[问题] 最新的umi4+next-prolayout，自己传入route，面包屑不显示

### ISSUE THREAD

**Issue by Ruboyq** [ant-design/pro-components#5729]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

没有用umi4的运行时配置，自己写的BasicLayout，自己用umi提供的appdata里的clientroute处理了一下传入了prolayout，现在面包屑怎么搞都出不来。。看了半天文档了，写死也不行。。求大佬帮忙看看是不是哪里配错了

**Comment by Ruboyq** [comment]
解决了，包要引一样的。。
解决前：
import { DefaultFooter, ProBreadcrumb } from '@ant-design/pro-component';
import { ProLayout } from '@ant-design/pro-layout';
解决后：
import { DefaultFooter, ProBreadcrumb, ProLayout } from '@ant-design/pro-layout';

**Comment by jiayongchang** [comment]
我想问问这玩意什么区别，antd 内部就不能统一？
