### ISSUE TITLE
👑 [需求]  Protable的横向滚动条如何浮动在页面底部?

### ISSUE THREAD

**Issue by darkfiredarkhalo** [ant-design/pro-components#5732]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

Protable

### 🥰 需求描述

Protable当设置`scroll={x: ***}`后会出现横向滚动条, 此时如果每页数据量多,表格高度就会向下延伸,此时如果想看表格右侧的内容就需要横向滑动表格, 但是滚动条固定在表格最底部, 需要先滑动页面到最底部, 横向拖动滚动条之后再上划的起始位置, 在操作上会非常麻烦....
而设置了`scroll={y: xxx}`后因为页面高度不固定, 当页面高度过大或过小时, 表格占据整个页面的区域是固定的, 会造成整体布局不好看...
  
### ⛰ 功能需求适用场景

table出现横向滚动条后, 如果页面数据多, 表格高度高, 此时查看表格右侧内容会非常麻烦

### 🧐 解决方案

增加一种方法或者属性, 可以控制滚动条(最好带上分页器)使其浮动在页面(屏幕可见区域)底部

### 🚑 其他信息

![飞书20220817-100721](https://user-images.githubusercontent.com/13959162/185019609-76613613-bacf-4a96-b838-b77cfede24cc.jpg)

**Comment by chenshuai2144** [comment]
你给 table 设置一下宽度就能实现你的想法。

我推荐不要乱搞花活，这点优化没啥意义
