### ISSUE TITLE
🐛[BUG]ProFormText 暗黑模式下 样式不对

### ISSUE THREAD

**Issue by jwmxushang** [ant-design/pro-components#5734]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProFormText 控件在暗黑模式下，设置showcount = true时，显示不清楚，同时在校验为空时，背景演示不是暗黑模式显示
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
等下个版本吧，这个版本有点费了。
你要是有兴趣就来个pr吧
