### ISSUE TITLE
🧐[问题]问题]想请教一下proTable怎么做本地排序 

### ISSUE THREAD

**Issue by congwa** [ant-design/pro-components#5737]
sorter为true的时候点击表格头的排序按钮每次触发request，求教如何本地排序，不去触发request

**Comment by dxall** [comment]
不使用dataSource作为数据源，使用request怎么处理

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


如果你需要使用 `request` 来获取数据，同时又需要实现本地排序的功能，你可以按照下面的方式进行处理：

1. 在 `request` 函数中添加排序功能：在这个函数中通过只有 `params` 参数（包含分页、排序等信息）进行数据的请求。其中 `params.sorter` 即用于记录当前的排序信息，我们可以根据这个信息对数据进行排序，最后返回正确排序的列表数据。示例代码如下：

```jsx
import { request } from 'umi';

const fetchTableData = async (params, sort, filters) => {
  const response = await request('/api/tableData', { params });
  let listData = response || [];
 
  // 如果当前有排序操作，根据 sorter 对 listData 进行排序
  if (params.sorter && params.sorter.field) {
    const { field, order } = params.sorter;
    listData = listData.sort((a, b) => {
      if (order === 'ascend') {
        return a[field] - b[field];
      } else {
        return b[field] - a[field];
      }
    });
  }

  // ...

  return {
    data: listData,
    // ...
  };
};
```

在上述代码中，`fetchTableData()` 函数通过调用 `request` 函数从服务器获取表格数据。进行排序之后，我们返回可用于渲染表格的正确排序的列表数据。

2. 在 ProTable 组件中配置请求函数 `request`：在 ProTable 的配置中，你需要传递请求数据的 `request` 函数，同时需要为每个可排序的列设置 `sorter` 属性。当用户点击排序按钮时，`sorter.field` 和 `sorter.order` 将会记录排序列和排序方式，在请求中作为参数传递到 `fetchTableData()` 函数中处理。

```jsx
import ProTable from '@ant-design/pro-table';

const columns = [
  {
    title: '姓名',
    dataIndex: 'name',
    key: 'name',
    sorter: true, // 允许表格列的排序
  },
  {
    title: '年龄',
    dataIndex: 'age',
    key: 'age',
    sorter: true, // 允许表格列的排序
  },
  {
    title: '地址',
    dataIndex: 'address',
    key: 'address',
  },
];

function Page() {
  return (
    <ProTable
      columns={columns}
      request={params => fetchTableData(params)} // 配置请求函数
      rowKey="key"
      search={false}
      pagination={{ pageSize: 10 }}
    />
  );
}
```

在上述代码中，我们将请求函数 `fetchTableData` 作为参数传递给了 `ProTable` 组件的 `request` 属性。同时为实现排序功能，将需要进行排序的列的 `sorter` 属性设置为 `true`。

这样当你在页面中运行这段代码时，你应该会发现每次点击该表格头部的可排序列时都会直接对当前分页数据进行排序处理，并且不会触发任何request请求。

**Comment by dxall** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> 如果你需要使用 `request` 来获取数据，同时又需要实现本地排序的功能，你可以按照下面的方式进行处理：
> 
> 1. 在 `request` 函数中添加排序功能：在这个函数中通过只有 `params` 参数（包含分页、排序等信息）进行数据的请求。其中 `params.sorter` 即用于记录当前的排序信息，我们可以根据这个信息对数据进行排序，最后返回正确排序的列表数据。示例代码如下：
> 
> ```js
> import { request } from 'umi';
> 
> const fetchTableData = async (params, sort, filters) => {
>   const response = await request('/api/tableData', { params });
>   let listData = response || [];
>  
>   // 如果当前有排序操作，根据 sorter 对 listData 进行排序
>   if (params.sorter && params.sorter.field) {
>     const { field, order } = params.sorter;
>     listData = listData.sort((a, b) => {
>       if (order === 'ascend') {
>         return a[field] - b[field];
>       } else {
>         return b[field] - a[field];
>       }
>     });
>   }
> 
>   // ...
> 
>   return {
>     data: listData,
>     // ...
>   };
> };
> ```
> 
> 在上述代码中，`fetchTableData()` 函数通过调用 `request` 函数从服务器获取表格数据。进行排序之后，我们返回可用于渲染表格的正确排序的列表数据。
> 
> 2. 在 ProTable 组件中配置请求函数 `request`：在 ProTable 的配置中，你需要传递请求数据的 `request` 函数，同时需要为每个可排序的列设置 `sorter` 属性。当用户点击排序按钮时，`sorter.field` 和 `sorter.order` 将会记录排序列和排序方式，在请求中作为参数传递到 `fetchTableData()` 函数中处理。
> 
> ```js
> import ProTable from '@ant-design/pro-table';
> 
> const columns = [
>   {
>     title: '姓名',
>     dataIndex: 'name',
>     key: 'name',
>     sorter: true, // 允许表格列的排序
>   },
>   {
>     title: '年龄',
>     dataIndex: 'age',
>     key: 'age',
>     sorter: true, // 允许表格列的排序
>   },
>   {
>     title: '地址',
>     dataIndex: 'address',
>     key: 'address',
>   },
> ];
> 
> function Page() {
>   return (
>     <ProTable
>       columns={columns}
>       request={params => fetchTableData(params)} // 配置请求函数
>       rowKey="key"
>       search={false}
>       pagination={{ pageSize: 10 }}
>     />
>   );
> }
> ```
> 
> 在上述代码中，我们将请求函数 `fetchTableData` 作为参数传递给了 `ProTable` 组件的 `request` 属性。同时为实现排序功能，将需要进行排序的列的 `sorter` 属性设置为 `true`。
> 
> 这样当你在页面中运行这段代码时，你应该会发现每次点击该表格头部的可排序列时都会直接对当前分页数据进行排序处理，并且不会触发任何request请求。

fetchTableData的params.sorter不存在

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


如果你的 `params` 中没有 `sorter`，则说明还没有进行排序操作。你可以默认当做是没有排序需求，直接从服务器端获取数据并返回。示例如下：

```js
const fetchTableData = async (params, sort, filters) => {
  const response = await request('/api/tableData', { params });
  const listData = response || [];

  return {
    data: listData,
    current: params.current || 1,
    pageSize: params.pageSize || 10,
    total: 100,
    success: true,
  };
};
```

这样就可以让 ProTable 的分页及搜索功能正常工作，并允许用户对表格列进行排序。

如果 `sorter` 参数存在，我们就可以对获取到的数据进行本地排序。具体实现方法可按前文提到的示例代码中实现。

**Comment by mansion-sun** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> 如果你的 `params` 中没有 `sorter`，则说明还没有进行排序操作。你可以默认当做是没有排序需求，直接从服务器端获取数据并返回。示例如下：
> 
> ```js
> const fetchTableData = async (params, sort, filters) => {
>   const response = await request('/api/tableData', { params });
>   const listData = response || [];
> 
>   return {
>     data: listData,
>     current: params.current || 1,
>     pageSize: params.pageSize || 10,
>     total: 100,
>     success: true,
>   };
> };
> ```
> 
> 这样就可以让 ProTable 的分页及搜索功能正常工作，并允许用户对表格列进行排序。
> 
> 如果 `sorter` 参数存在，我们就可以对获取到的数据进行本地排序。具体实现方法可按前文提到的示例代码中实现。
已经做了排序，但是params.sorter并不存在，sort是存在的
![image](https://github.com/ant-design/pro-components/assets/26341016/e3d8cf8e-4ec0-4307-a00a-9408a12eddfc)
![image](https://github.com/ant-design/pro-components/assets/26341016/f239bf3b-3d8d-40a9-b25a-5c19f8d12307)
