### ISSUE TITLE
🧐[问题]  ProTable如何将查询按钮左浮动挨着最后一个筛选表单的配置项

### ISSUE THREAD

**Issue by LittleDropsOfWater** [ant-design/pro-components#5738]
### 🧐 问题描述

因为ui需求，要让查询按钮左浮动挨着最后一个筛选表单的配置项， 但现在的按钮会自动撑开到最右展示。
有可以改写查询按钮外侧span属性和style的地方吗？

### 🚑 其他信息
ui 
![image](https://user-images.githubusercontent.com/48471571/185357640-e7b4909f-3183-4b97-9ece-984a53aac068.png)

目前的情况
![image](https://user-images.githubusercontent.com/48471571/185358300-eb0cf31b-3f42-4993-b395-696bf40ebb46.png)

**Comment by chenshuai2144** [comment]
尽量不要搞这种东西，没啥意义。

真的很想要就完全自己写吧
