### ISSUE TITLE
🧐[问题]protable中大部分的valueType对应的轻量搜索都是以下拉菜单的方式展示吗？

### ISSUE THREAD

**Issue by felixjichao** [ant-design/pro-components#5740]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
protable中大部分的valueType对应的轻量搜索都是以下拉菜单的方式展示吗？比如图中的Switch，不能直接显示的外侧吗？

### 🚑 其他信息

<img width="959" alt="image" src="https://user-images.githubusercontent.com/17485165/185548916-485106ac-a744-48d6-8b1e-b1f0f55a1433.png">

**Comment by chenshuai2144** [comment]
有兴趣可以来个pr

**Comment by chenshuai2144** [comment]
做了一些修改，但是这种的只能这样浮层了
