### ISSUE TITLE
🐛[BUG] ProTable 使用columnsState之后，只要persistenceType给了值，页面就无限渲染了

### ISSUE THREAD

**Issue by zcSkr** [ant-design/pro-components#5742]
### 🐛 bug 描述
devScripts.js:6523 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.

### 📷 复现步骤
使用columnsState ，persistenceType设置了localStorage 或者 sessionStorage。
只要不写persistenceType 就正常

### 🏞 期望结果
columnsState可以持久化缓存状态列的显示隐藏

### 💻 复现代码
`
columnsState={{
        persistenceKey: 'pro-table-singe-demos',
        persistenceType: 'sessionStorage',
        onChange(value) {
          console.log('value: ', value);
        },
      }}
`

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] 1.1.16
- umi 版本 3.5.26
- 浏览器环境 Chrome  103.0.5060.114
- 开发环境 [e.g. mac OS]  macOS 12.15.1

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/30515821/185560903-78c82ec5-4a38-4e13-9c22-e60510a76e13.png)

**Comment by luotongzhou** [comment]
这周会解吗？更新了版本，但不知道回退到哪个版本才能没有这个问题

**Comment by 982528494** [comment]
> 这周会解吗？更新了版本，但不知道回退到哪个版本才能没有这个问题



> ### 🐛 bug 描述
> devScripts.js:6523 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
> 
> ### 📷 复现步骤
> 使用columnsState ，persistenceType设置了localStorage 或者 sessionStorage。 只要不写persistenceType 就正常
> 
> ### 🏞 期望结果
> columnsState可以持久化缓存状态列的显示隐藏
> 
> ### 💻 复现代码
> `columnsState={{ persistenceKey: 'pro-table-singe-demos', persistenceType: 'sessionStorage', onChange(value) { console.log('value: ', value); }, }}`
> 
> ### © 版本信息
> * ProComponents 版本: [e.g. 4.0.0] 1.1.16
> * umi 版本 3.5.26
> * 浏览器环境 Chrome  103.0.5060.114
> * 开发环境 [e.g. mac OS]  macOS 12.15.1
> 
> ### 🚑 其他信息
> ![image](https://user-images.githubusercontent.com/30515821/185560903-78c82ec5-4a38-4e13-9c22-e60510a76e13.png)

不知道什么原因，新建的项目就没这个问题，就的项目同样版本的库就出现了相同的问题

最厚不写persistenceType，onchange里面存session解决

 columnsState={{
            //列设置-操作
            value: columnsStateMap, //列状态的值，支持受控模式
            onChange: handleOnChangeColumn, //列状态的值发生改变之后触发
          }}

 const columnsStore =
    JSON.parse(localStorage.getItem("columnsManagement")) || {};
  const [columnsStateMap, setColumnsStateMap] = useState(columnsStore);
  const handleOnChangeColumn = (val) => {
    localStorage.setItem("columnsManagement", JSON.stringify(val));
    setColumnsStateMap(val);
  };

**Comment by luotongzhou** [comment]
看了下源码是三周前的一个 table -> container.js 一个 useEffect 的代码造成的，一直在执行

**Comment by 982528494** [comment]
vite 版本小于2.8.0会出现以上问题，提升vite版本不出现以上问题

**Comment by zpaimon** [comment]
同样问题，知道回退那个版本会避免这个问题吗？

**Comment by chenshuai2144** [comment]
我没法重现这个问题，有demo 吗

**Comment by luotongzhou** [comment]
```
  /**  配置或列更改时对columnsMap重新赋值 */
  useLayoutEffect(() => {
    const { persistenceType, persistenceKey } = props.columnsState || {};

    if (persistenceKey && persistenceType && typeof window !== 'undefined') {
      /** 从持久化中读取数据 */
      const storage = window[persistenceType];
      try {
        const storageValue = storage?.getItem(persistenceKey);
        if (storageValue) {
          setColumnsMap(JSON.parse(storageValue));
        } else {
          setColumnsMap(defaultColumnKeyMap);
        }
      } catch (error) {
        console.warn(error);
      }
    }
  }, [props.columnsState, defaultColumnKeyMap, setColumnsMap]);
```
是这段代码的问题，但我不知道怎么提 pr

**Comment by zcSkr** [comment]
好了，兄弟们。
今天想起来又试了一下，已经没之前的问题了。

ProComponents 版本:  1.1.25
umi 版本   "@umijs/max": "^4.0.30",
浏览器环境 Chrome 103.0.5060.114
开发环境  macOS 13.0.1

**Comment by Li-mengbo** [comment]
> 好了，兄弟们。 今天想起来又试了一下，已经没之前的问题了。
> 
> ProComponents 版本: 1.1.25 umi 版本 "@umijs/max": "^4.0.30", 浏览器环境 Chrome 103.0.5060.114 开发环境 macOS 13.0.1

兄弟想问下ProComponents 版本: 1.1.25里的pro-table版本是多少？同样遇到了这个问题，升级了pro-table依然没解决

**Comment by luotongzhou** [comment]
> 

尽量升级pro-components 到最新版本，之前的无限渲染是因为本地node_modules 里面的pro-utils的 useMergedState 代码比较老导致的，更新之后就不会了

**Comment by Li-mengbo** [comment]
> > 
> 
> 尽量升级pro-components 到最新版本，之前的无限渲染是因为本地node_modules 里面的pro-utils的 useMergedState 代码比较老导致的，更新之后就不会了

只用到了pro-table现在已经是最新版本3.2.2还是有这个问题

**Comment by luotongzhou** [comment]
> 

所以你保证pro-utils的useMergedState的代码跟线上仓库保持一致

**Comment by Li-mengbo** [comment]
老哥 我看了下最新的pro-table版本3.2.2的依赖pro-utils是最新的包了，结果还是有这个问题

**Comment by luotongzhou** [comment]
建议删除依赖重新拉取

**Comment by xiaoshengwpp** [comment]
24 年了 刚遇到  问题还在

**Comment by 982528494** [comment]
https://github.com/982528494/customColumnTable
自己写的自定义列表组件，没弄npm包，可以copy代码参考修改试试

**Comment by 1474282816** [comment]
2024.6.25    现在问题依然存在

**Comment by mighoocool** [comment]
找到解决方案了，亲测有效。
主要是因为useMergedState这个hook依赖的defaultColumnKeyMap变量变更导致的无限进入 代码中95行的分支。
https://github.com/ant-design/pro-components/blob/6b51b6f750d7fd0f833d4536e578ea22ce94f708/packages/table/src/Store/Provide.tsx#L121-L153

在看defaultColumnKeyMap变量是useMemo且依赖props.columns（ProTable传入的columns）
https://github.com/ant-design/pro-components/blob/6b51b6f750d7fd0f833d4536e578ea22ce94f708/packages/table/src/Store/Provide.tsx#L64-L79

所以解决方案是：将传入ProTable的columns用useMemo包裹

以下是复现代码
https://stackblitz.com/edit/react-persistencekey-maximum-rendering?file=App.tsx
