### ISSUE TITLE
🐛[BUG] ProFormDigit组件设置 precision=0, 输入多个小数点的数字字符串, 输入框内值变为整数, 但是表单获取值仍为小数

### ISSUE THREAD

**Issue by darkfiredarkhalo** [ant-design/pro-components#5743]
### 🐛 bug 描述

在ModalForm中使用ProFormDigit组件, 设置`fieldProps={{precision: 0, addonAfter: '%'}}`, 当输入有多个小数点的数字字符串时, 输入框内值改变为整数, 但是表单获取值变成了小数, 如输入`22.3.4.5.6.7`, 输入框内值变为`22`, 表单实际捕获的值为`22.3`

### 📷 复现步骤
ModalForm内使用ProFormDigit, 设置如下  
``` 
<ProFormDigit
        name={FormParamsKey.percent}
        label="百分比"
        placeholder="请输入百分比"
        tooltip="xxxxxxx"
        rules={[{ required: true, message: '请输入百分比!' }]}
        min={1}
        max={100}
        fieldProps={{
          precision: 0,
          addonAfter: '%',
        }}
      />
```
然后输入`22.3.4.5.6.7`, 提交表单, 查看表单捕获的值
### 🏞 期望结果

当输入有多个小数点的数字字符串时, 输入框内的值和最终表单捕获的值保持一致

### 💻 复现代码

``` 
<ProFormDigit
        name={FormParamsKey.percent}
        label="百分比"
        placeholder="请输入百分比"
        tooltip="xxxxxxx"
        rules={[{ required: true, message: '请输入百分比!' }]}
        min={1}
        max={100}
        fieldProps={{
          precision: 0,
          addonAfter: '%',
        }}
      />
```
### 其他信息  
输入正常小数,表现正常, 会自动变化为四舍五入的整数
### © 版本信息

- ProComponents 版本:  1.1.1
- umi 版本: 最新版
- 浏览器环境: Chrome
- 开发环境: Windows11

**Comment by guansss** [comment]
@chenshuai2144 请问这个 issue 真的被解决了吗？目前我在最新的 2.3.47 版本还是有这个问题：

https://codesandbox.io/s/agitated-blackburn-yjv36p?file=/App.tsx
（打开之后输入 1.2.3，点击提交，弹窗里是 1.2 而输入框里是 1）

我看到上面的 PR 里貌似只测试了 22.22，没有测试多个小数点的情况

**Comment by chenshuai2144** [comment]
"@ant-design/pro-components": "2.3.52",

是可以的，你试试

**Comment by guansss** [comment]
@chenshuai2144 好像还是不行呢
![image](https://user-images.githubusercontent.com/46285865/217452806-67581987-d14b-4472-a9b5-f1bceb482896.png)

**Comment by chenshuai2144** [comment]
你看起来好像没刷新

**Comment by guansss** [comment]
刷新过了，现在 codesandbox 的网络连接好像有些问题，不过我在本地测试也是一样的情况

https://github.com/guansss/repro-pro-precision

**Comment by wenshan** [comment]
修了2年都没修好这个BUG

**Comment by quanjinduo** [comment]
是可以的，后续版本已修复这个问题。测试版本@ant-design/pro-form": "^2.30.2"
