### ISSUE TITLE
🐛[BUG]ProForm 中 ProFormSelect,ProFormSwitch 设置了 onChange ，onFinish 的 value 取不到其值。

### ISSUE THREAD

**Issue by zhou0818** [ant-design/pro-components#575]
### 🐛 bug 描述
ProFormSelect
![image](https://user-images.githubusercontent.com/25949890/94003090-600fe980-fdcd-11ea-8362-6d21a624ac6c.png)
还有 valueEnum 的 key 设置为 number 类型，取到的值还是 string 类型
ProFormSwitch
![image](https://user-images.githubusercontent.com/25949890/94003053-51c1cd80-fdcd-11ea-8853-e8e2eab18948.png)

### © 版本信息

- ProComponents 版本: [1.0.0-beta.28]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> 还有 valueEnum 的 key 设置为 number 类型，取到的值还是 string 类型

number 是不能作为 object 的 key 的， 如果需要建议使用 Map

**Comment by giamchen** [comment]
刚好碰到这个问题，接管了onChange组件就没法获取值，然后校验规则就报错了

**Comment by chenshuai2144** [comment]
接管  onChange 是为什么呢？

**Comment by zhou0818** [comment]
> 接管 onChange 是为什么呢？

有时候要根据选择的值做一些判断啊

**Comment by chenshuai2144** [comment]
使用 onValueChange 做判断把
