### ISSUE TITLE
🐛[BUG] 一级菜单配置了 access 为 false 不能隐藏菜单，二级及以下可以隐藏菜单

### ISSUE THREAD

**Issue by kaoding** [ant-design/pro-components#5753]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/18542211/185824630-f6c362d6-7a37-4e7d-9872-01e60bf41d5c.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by drizzlesconsin** [comment]
https://github.com/ant-design/ant-design-pro/issues/10103

**Comment by phoema** [comment]
这个问题关闭了，请问需要怎么解决，我升级到umi4.0.15,layout6.38.21后，还是上述表现。

**Comment by kaoding** [comment]
这个问题还是没有解决。

**Comment by phoema** [comment]
> 这个问题还是没有解决。

请问我回滚到什么版本能够规避这个问题？

**Comment by chb584890926** [comment]
同问题，有解决办法么

**Comment by MyAuntIsPost90s** [comment]
我也遇到了这个问题，我自己从后端取数据后过滤了没有权限的menu，但是现在还有一个新的问题，路由切换时，access不会执行，只有页面刷新的时候会执行，导致access路由权限失效
