### ISSUE TITLE
🐛[BUG]proform带有request属性时，formRef.current为空对象

### ISSUE THREAD

**Issue by wangxin305** [ant-design/pro-components#5756]
### 🐛 bug 描述

更新 @ant-design/pro-form 1.74.0 后，proform带有request属性时，formRef.current为空对象

### 💻 复现代码

[https://vpgk9w.csb.app/](https://vpgk9w.csb.app/)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Seven777Z** [comment]
我也碰到了

**Comment by vobile-wangzhenfeng** [comment]
同样碰到了

**Comment by vobile-wangzhenfeng** [comment]
> 同样碰到了

不过我测了一下，1.74.6好像修复了这个问题
