### ISSUE TITLE
🧐为什么在ProFormList中每一层的Item上包裹了一个div，如何设置这个div的宽度呢？

### ISSUE THREAD

**Issue by yuanAIhan** [ant-design/pro-components#5758]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

我的场景是，我想在每一个List中都是使用Row和Col的方式来完成布局，即使用Col提供的flex的方式来使得每一个item平均分配当前行。但是我现在发现在每一个item中的宽度没法设置？是我哪里搞错了嘛？
![image](https://user-images.githubusercontent.com/80769611/185931240-a8b1260b-3c82-4f02-af9b-134cb1be8d2a.png)
主要的目的是使得ProFormList中每一个List布局可以使用Row和col但是我发现不起效，可以告诉我的问题所在嘛？

### 💻 示例代码
const FormGroups = (isEdit: boolean) => {
  return (
    <>
    <Col span={7}>
      <ProFormSelect
        name="taxCountryName"
        label="Tax Country Name:"
        // width={290}
        readonly={!isEdit}
        valueEnum={{
          china: 'Malay',
          usa: 'ID',
        }}
        placeholder="Please select a country"
        rules={[{ required: true, message: 'Please select your country!' }]}
      />
    </Col>
    <Col span={7}>
      <ProFormText
        name="email"
        label="Email:"
        readonly={!isEdit}
        // width={290}
        rules={[
          {
            required: true,
          },
          {
            max: 128,
            message: 'Exceed the max input length',
          },
        ]}
      />
    </Col>
    <Col span={7}>
    </Col>
    </>
  )
}

<ProFormList
name="taxInfoList"
initialValue={taxInfo}
copyIconProps={false}
creatorButtonProps={!isEdit ? false : <AddBtn />}
actionRef={actionRef}
itemContainerRender={(doms) => {
  return <Row className={style.formList} justify="space-between">{doms}</Row>
}}
alwaysShowItemLabel
>
{(f, index, action) => {
  console.log(f, index, action)
  return FormGroups(isEdit)
}}
</ProFormList>

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/blob/b403cbe291e19235138ed0efe05775d5343a1a40/packages/descriptions/src/demos/dynamic-descriptions.tsx#L213


看看这里的用法
