### ISSUE TITLE
🐛[BUG] 表单项选择某些后查询 清除掉某些表单项，切换分页的时候，清除的项还在查询条件里

### ISSUE THREAD

**Issue by hrong86** [ant-design/pro-components#576]
### 📷 复现步骤

https://procomponents.ant.design/components/table

![image](https://user-images.githubusercontent.com/12147023/94003697-2ee3e900-fdce-11ea-8088-dcf46a6bf9da.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
只有点击了查询，table 才会更新保存的参数
