### ISSUE TITLE
🧐[问题] ProLayout->menu添加徽标数

### ISSUE THREAD

**Issue by WT-Road** [ant-design/pro-components#5760]
### 🧐 问题描述

使用ProLayout时在菜单中，目前只能显示icon和name。但实际在我的后台管理系统中，需要明显的提醒用户某个子菜单或一级菜单有数据更新，在子菜单上显示徽标数是很好的用户体验。请问有什么便捷的方法可以实现这个需求吗

**Comment by mushroomlb** [comment]
```
 // 二级icon
    menuItemRender: (menuItemProps, defaultDom) => {
      if (menuItemProps.isUrl || !menuItemProps.path) {
        return defaultDom;
      }
      return (
        <Link to={menuItemProps.path} >
          {menuItemProps.pro_layout_parentKeys && menuItemProps.pro_layout_parentKeys.length > 0 && menuItemProps.icon}
          {defaultDom}
        </Link>
      )
    },
```

**Comment by imgoby** [comment]
// 二级icon
    menuItemRender: (menuItemProps, defaultDom) => {
      if (menuItemProps.isUrl || !menuItemProps.path) {
        return defaultDom;
      }
      return (
        <Link to={menuItemProps.path} >
          {menuItemProps.pro_layout_parentKeys && menuItemProps.pro_layout_parentKeys.length > 0 && menuItemProps.icon}
          {defaultDom}
           {menuItemProps.path=='/test1'?<MyBadge style={{marginLeft: "1em"}} ></MyBadge>:null}
        </Link>
      )
    },

<MyBadge>做成独立组件，在组件内部，定时查询后台，如果有新消息，就显示<Badge count={5} overflowCount={10} ></Badge>
