### ISSUE TITLE
v2.0.0 版本 export 'theme' (imported as 'antdTheme') was not found in 'antd'

### ISSUE THREAD

**Issue by oswayne** [ant-design/pro-components#5762]
### 🧐 问题描述

依赖：

```json
"dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^2.0.0",
    "axios": "^0.27.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.3.0",
    "react-scripts": "5.0.1"
  },
```

Index.js

```
import React from 'react';
import ReactDOM from 'react-dom/client';
import {BrowserRouter, Route, Routes} from "react-router-dom";

import 'antd/dist/antd.min.css';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<BrowserRouter>
    <Home/>
</BrowserRouter>);
```

启动后控制台信息：

```bash
Failed to compile.

Attempted import error: 'theme' is not exported from 'antd' (imported as 'antdTheme').
ERROR in ./node_modules/@ant-design/pro-utils/es/useStyle/index.js 35:69-78
export 'theme' (imported as 'antdTheme') was not found in 'antd' (possible exports: Affix, Alert, Anchor, AutoComplete, Avatar, BackTop, Badge, Breadcrumb, Button, Calendar, Card, Carousel, Cascader, Checkbox, Col, Collapse, Comment, ConfigProvider, DatePicker, Descriptions, Divider, Drawer, Dropdown, Empty, Form, Grid, Image, Input, InputNumber, Layout, List, Mentions, Menu, Modal, PageHeader, Pagination, Popconfirm, Popover, Progress, Radio, Rate, Result, Row, Segmented, Select, Skeleton, Slider, Space, Spin, Statistic, Steps, Switch, Table, Tabs, Tag, TimePicker, Timeline, Tooltip, Transfer, Tree, TreeSelect, Typography, Upload, message, notification, version)

webpack compiled with 1 error
```

**Comment by BestDingSheng** [comment]
我也碰到了这个问题

**Comment by sushi-su** [comment]
应该是发错版本了，v2 得搭配 antdv5 使用

**Comment by BaoXiaoShuai** [comment]
一样的问题

**Comment by chenshuai2144** [comment]
这个没办法去掉，可以先忽略，
我们兼容了一下 antd 版本，但是warning 去不掉

**Comment by radeon8** [comment]
我也遇到了，导致 umi/max 项目升级，在vite模式下，直接崩溃了

**Comment by gaofengGo** [comment]
不仅仅是 warning，直接项目启动不了了

**Comment by gaofengGo** [comment]
> 这个没办法去掉，可以先忽略， 我们兼容了一下 antd 版本，但是warning 去不掉

大佬，项目用的是 vite 的话不仅仅是警告，项目启动和 build 都报错了

**Comment by Chastrlove** [comment]
报error可能是因为设置了strictExportPresence:true, webpack的可以使用如下配置。
```js
 module: {
      parser: {
        javascript: {
          exportsPresence: 'warn', //'error' | 'warn' | 'auto' | false，自己看着调，设置为false可以避免警告，但会带来不稳定性
        },
      }
}
```

**Comment by Chastrlove** [comment]
如果是vite,可以自定义个插件
```js
optimizeDeps: {
    esbuildOptions: {
      plugins: [
        {
          name: "add-missing-theme",
          setup(build) {
            build.onLoad({ filter: /antd(?:\/|\\{1,2})es(?:\/|\\{1,2})index\.js/ }, async(args) => {
              let text = await fs.promises.readFile(args.path, 'utf8')
              return {
                contents: `
              ${text}\nexport const theme = undefined;
              `,
                loader: "js",
              };
            });
          },
        },
      ],
    }
  },
```

**Comment by hqwlkj** [comment]
> ```js
> esbuildOptions: {
>       plugins: [
>         {
>           name: "add-missing-theme",
>           setup(build) {
>             build.onLoad({ filter: /antd(?:\/|\\{1,2})es(?:\/|\\{1,2})index\.js/ }, async(args) => {
>               let text = await fs.promises.readFile(args.path, 'utf8')
>               return {
>                 contents: `
>               ${text}\nexport const theme = undefined;
>               `,
>                 loader: "js",
>               };
>             });
>           },
>         },
>       ],
>     }
> ```

这样配置 了编译不报错，但是 运行时还是会报于这相关的错误信息

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/12181423/189066808-af1c6c9c-0ed3-44cd-ad6e-c59742eeb1bf.png">

**Comment by Ariaszzzhc** [comment]
@hqwlkj 这个问题我发现是由于 SWR 的版本问题。使用 `1.2.0` 的 swr 就可以正常运行

**Comment by hqwlkj** [comment]
> swr

没有使用到 swr 这个依赖
![image](https://user-images.githubusercontent.com/12181423/189068769-84f28296-bbb3-4cbe-b865-5f2f7ccf245f.png)

**Comment by sibaiabis** [comment]
> > ```js
> > esbuildOptions: {
> >       plugins: [
> >         {
> >           name: "add-missing-theme",
> >           setup(build) {
> >             build.onLoad({ filter: /antd(?:\/|\\{1,2})es(?:\/|\\{1,2})index\.js/ }, async(args) => {
> >               let text = await fs.promises.readFile(args.path, 'utf8')
> >               return {
> >                 contents: `
> >               ${text}\nexport const theme = undefined;
> >               `,
> >                 loader: "js",
> >               };
> >             });
> >           },
> >         },
> >       ],
> >     }
> > ```
> 
> 这样配置 了编译不报错，但是 运行时还是会报于这相关的错误信息
> 
> <img alt="image" width="1046" src="https://user-images.githubusercontent.com/12181423/189066808-af1c6c9c-0ed3-44cd-ad6e-c59742eeb1bf.png">

咋解决的，我也遇到了。。。

**Comment by hsbtr** [comment]
> 报error可能是因为设置了strictExportPresence:true, webpack的可以使用如下配置。
> 
> ```js
>   ignoreWarnings: [
>       /export 'theme' \(imported as 'antdTheme'\) was not found in 'antd'/
>     ],
> ```

pro-components@2.3.30，使用这个方法还是失效了，webpack直接终止了编译，看来暂时没法用了
![image](https://user-images.githubusercontent.com/46487804/200541766-02df3abe-df04-4ff1-ba77-e14a1aac129e.png)
