### ISSUE TITLE
🧐[问题].  LoginForm 为何要在页面写死一个宽度呢？

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/pro-components#5764]
### 🧐 问题描述

          width: 328,
https://github.com/ant-design/pro-components/blob/master/packages/form/src/layouts/LoginForm/index.tsx#L107

### 💻 示例代码

         
          
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/12181423/186304403-ca167f2f-b60d-43d6-a426-8b4586d1e89f.png">

**Comment by chenshuai2144** [comment]
为了美观。你可以用 API 删掉他

**Comment by hqwlkj** [comment]
> 为了美观。你可以用 API 删掉他

使用那个API能删除呢？
