### ISSUE TITLE
🐛[BUG]ProDescriptions设置ellipsis不生效

### ISSUE THREAD

**Issue by darkfiredarkhalo** [ant-design/pro-components#5765]
### 🐛 bug 描述

`ProDescriptions`设置`ellipsis`不生效, 测试一下两种方法: 
- 在`ProDescriptions`上设置, `ts`下会提示`ProDescriptions`上不存在这个属性, 且不生效  
- 在`columns`中设置(共用`ProTable`的, `ProTable`中`ellipsis`正常生效), 不生效 

### 📷 复现步骤
```
ProDescriptions
            column={1}
            ellipsis={true}
....
```  
或  
```
const columns = [
...
{
      title: 'xxx',
      align: 'center',
      ellipsis: true,
      dataIndex: "xxx,
    }
...
]
```

### 🏞 期望结果

`ProDescriptions`设置`ellipsis`生效

### 💻 复现代码

```
ProDescriptions
            column={1}
            ellipsis={true}
....
```  
或  
```
const columns = [
...
{
      title: 'xxx',
      align: 'center',
      ellipsis: true,
      dataIndex: "xxx,
    }
...
]
```
### © 版本信息

- ProComponents 版本: 1.1.1
- umi 版本: v4
- 浏览器环境: chrome
- 开发环境 : windows11

### 🚑 其他信息
无

**Comment by darkfiredarkhalo** [comment]
发现重写`column`的`render`方法, 自己用`tooltip`组件实现超长省略即可  
或者在`render`方法内对要显示的内容外包括一层html标签, 此时如果设置了`ellipsis`, `ProTable`内正常依据设置省略, `ProDescriptions`可实现自动换行, 界面布局就正常了

**Comment by chenshuai2144** [comment]
ellipsis 实现的兼容性不好，如果有比较强的需求，建议自己render一下
