### ISSUE TITLE
🐛[BUG] readonly 长文本样式导致不美观

### ISSUE THREAD

**Issue by shanzhaozhen** [ant-design/pro-components#5767]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

readonly 长文本样式导致不美观

### 💻 复现代码

```
<ProFormSelect
  width="md"
  name="clientAuthenticationMethodList"
  label="客户端认证方式"
  mode="multiple"
  options={clientAuthenticationMethodOptions}
  placeholder="请选择客户端认证方式"
  rules={[{ required: true, message: '请选择客户端认证方式' }]}
  readonly={formType === 'view'}
/>
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你的例子呢？ 看代码算命？

**Comment by mwj610** [comment]
> 你的例子呢？ 看代码算命？

readonly 时候可以配置多选项展示的分隔符吗？ @chenshuai2144
