### ISSUE TITLE
👑 [需求]antd ProFormSelect 开启showSearch，然后配置了 filterOption 同时配置了request，每次输入都会先调request里的接口，可以加个开关，是否调用request的吗？

### ISSUE THREAD

**Issue by zwd609258057** [ant-design/pro-components#5768]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

ProFormSelect
```javascript
<ProFormSelect
  name="select2"
  label="Select"
  params={{}}
  valueType="select"
  debounceTime={1000}
  request={request}
  fieldProps={{ 
     showSearch,
     filterOption: (input, option) => option.label.includes(input)
 }}
  placeholder="Please select a country"
/>
```

**Comment by zwd609258057** [comment]
可以使用 state + options 解决

**Comment by chenshuai2144** [comment]
正解，要么去抖一下

**Comment by hsbtr** [comment]
pro-form 1.70+的版本增加了一个属性解决了这个问题

**Comment by zwd609258057** [comment]
> 

现在最新是1.44，1.7啥时候能出来

**Comment by hsbtr** [comment]
> > 
> 
> 现在最新是1.44，1.7啥时候能出来

出来有一段时间了，你可以看下更新日志

**Comment by lovewinders** [comment]
> pro-form 1.70+的版本增加了一个属性解决了这个问题
你好，属性名字是什么啊？给一点提示

**Comment by lovewinders** [comment]
> pro-form 1.70+的版本增加了一个属性解决了这个问题

如果ProFormTreeSelect也有fetchDataOnSearch属性最好

**Comment by hsbtr** [comment]
> 

目前没有发现TreeSelect提供这个功能，官方可能会看有多少人提这个相关得issue

**Comment by hsbtr** [comment]
> > pro-form 1.70+的版本增加了一个属性解决了这个问题
> 
> 如果ProFormTreeSelect也有fetchDataOnSearch属性最好

目前没有发现TreeSelect提供这个功能，官方可能会看有多少人提这个相关得issue

**Comment by lovewinders** [comment]
> > > pro-form 1.70+的版本增加了一个属性解决了这个问题
> > 
> > 
> > 如果ProFormTreeSelect也有fetchDataOnSearch属性最好
> 
> 目前没有发现TreeSelect提供这个功能，官方可能会看有多少人提这个相关得issue

ProFormSelect已经有这个属性了，只不过文档没写出来。但是ProFormTreeSelect这个搜索本地数据需求也是很常见的

**Comment by Eliot00** [comment]
> > > > pro-form 1.70+的版本增加了一个属性解决了这个问题
> > > 
> > > 
> > > 如果ProFormTreeSelect也有fetchDataOnSearch属性最好
> > 
> > 
> > 目前没有发现TreeSelect提供这个功能，官方可能会看有多少人提这个相关得issue
> 
> ProFormSelect已经有这个属性了，只不过文档没写出来。但是ProFormTreeSelect这个搜索本地数据需求也是很常见的

ProFormTreeSelect现在也支持了 https://github.com/ant-design/pro-components/pull/6638
