### ISSUE TITLE
👑 [需求]基于ProTable封装一个ProTableSelect

### ISSUE THREAD

**Issue by Hikarien** [ant-design/pro-components#577]
### 🥰 需求描述

antd原生的Select选择器在复杂业务场景下的选择显得捉襟见肘，需要封装基于ProTable能分页查询的选择器

### 🧐 解决方案

目前在项目上我们临时封装了一个，看看能不能由pro-component团队统一考虑做进基线里

![image](https://user-images.githubusercontent.com/41961907/94088717-c9324400-fe43-11ea-989d-f45ddd53ccf1.png)

有些数量多或者复杂模型的选择需要进一步查询的，可以用这种，如果能整合到ProForm的组件里就更好了！

**Comment by Hikarien** [comment]
![image](https://user-images.githubusercontent.com/41961907/98648849-c77bfb80-2371-11eb-8a40-99d5c562fd5b.png)
用pro-table的轻量模式改造了一个版本，感觉稍微好看点了。
不过目前只能在pro-table 2.9.3上用。。

**Comment by chenshuai2144** [comment]
show 一下你的设计

**Comment by Hikarien** [comment]
@chenshuai2144 
原型是参照了http://www.miniui.com/demo/index.html#src=lookup/lookup.html 这个mini ui的 lookup
曾经我们的项目也用过，但是因为这个组件只支持jquery框架所以我们转型React后就不用了。

于是参照这个套路搞了一个乞丐版，下面上个截图和部分代码吧，看其他issue也有人提到了 #990 

在你们知乎的ant deisgn 4.0 吐槽我也回了类似的想法，不过设计师并没有理我😭

截个完整一点的样式：
比方说这种物料的复杂选择的情况，用普通的Select做非常不理想
![image](https://user-images.githubusercontent.com/41961907/99638551-5d560b80-2a81-11eb-8090-4391da2f6a32.png)

代码的思路就是在input点击的时候呼出来pro-table实体，选择完对应项的时候回写form，并且更新展示的值。
或者再次点击input就关闭pro-table的展示，因为团队不是很擅长前端，仅仅封装到这个程度，而且2.9.4以后的pro-table这个套路就会有问题，不会发生数据请求了 。

如果能做到pro-compoents内置就最好了！
```js

    return (
        <div className="tableselect_wrap">
            <Input
                placeholder="请点击选择"
                allowClear
                onClick={handleClick}
                value={inputValue}
                onChange={handleInputChange}
                disabled={disabled}
            />
            <div
                className="tableSelect_box"
                style={{
                    width: width || '100%',
                    height: height,
                    display: dropDownVis ? 'block' : 'none'
                }}
            >
                <MetaTable
                    rowKey={curPK}
                    size="small"
                    tableAlertRender={false}
                    reqQuery={requestData}
                    columns={columns || []}
                    search={{
                        filterType: 'light'
                    }}
                    pagination={{
                        defaultCurrent: 1,
                        defaultPageSize: 5,
                        showSizeChanger: false
                    }}
                    rowSelection={{
                        selectedRowKeys,
                        onChange: handleSelectChange,
                        type: 'radio'
                    }}
                    {...otherProps}
                />
            </div>
        </div>
```

**Comment by Hikarien** [comment]
@chenshuai2144  这个select目前发现能用于antd自带的Form以及ProForm（均为最新版本），但是当pro-table升级到2.9.4后，在table的form下的渲染都出错了（表单模式和search模式）。

难道pro-table的form模式不是直接透传到pro-form的嘛😭😭

**Comment by Hikarien** [comment]
后来发现是pro-table更新后renderFormItem透传的属性的问题，我这边没其他问题就凑合着用了。。

**Comment by zwjsoft** [comment]
提过同样需求
