### ISSUE TITLE
🐛[BUG] pro-table 2.28.0之后，搜索部分，不必要的search,transform方法调用。

### ISSUE THREAD

**Issue by oxygen-xx** [ant-design/pro-components#5771]
我们的机器人，能不能不要进行不必要的issue 关闭？

    {
      title: '修改日期',
      width: 120,
      hideInDescriptions: true,
      hideInForm: true,
      dataIndex: 'updated_at',
      valueType: 'dateRange',
      search: {
        transform: (value) => {
          return  {
            begin_date: value[0],
            end_date: value[1],
          };
        },
      },
    },

pro-table 2.28.0之后，table的搜索部分出现二个问题。
1. 比如，如果在其它的搜索条件中输入信息，就会触发所有其它搜索条件的search方法中的transform方法，之前的版本没有这个问题。
2. 点击上面的搜索组件的，右侧的X号，清空，重置些组件的状态时，又会再次调用search中的transform方法。

上面的二个问题，都是在之前版本中没出现的过。

"antd": "^4.22.7",

**Comment by chenshuai2144** [comment]
不写标题就会关掉你的
