### ISSUE TITLE
🐛[BUG] ProFormDigit 打包后输入小数会被格式化整数

### ISSUE THREAD

**Issue by pingjintao** [ant-design/pro-components#5772]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProFormDigit 打包后输入小数会被格式化整数

### 💻 复现代码
```ts
<ProFormDigit
      name="skuPrice"
      label="售卖价格"
      width={328}
      rules={[
        {
          required: true,
          message: "请输入售卖价格",
        },
        {
          pattern: /^(\d+)(.\d{0,2})?$/,
          message: "售卖价格最多两位小数",
        },
      ]}
      min={0.01}
      fieldProps={{
        addonAfter: <Box className="w-[81px] text-left">元/箱</Box>,
      }}
  />
```

### © 版本信息

- @ant-design/pro-components: 1.1.18
- vite: 3.0.9
- 浏览器环境 chrome
- 开发环境 window11

**Comment by xingming2020** [comment]
我也遇到了，本地没问题，线上环境不行。我的解决方案：升级@ant-design/pro-form到1.74.4，在fieldProps中配置precision

**Comment by yangjie21** [comment]
我也遇到了同样的问题 @xingming2020 用你的方法不能解决

**Comment by pingjintao** [comment]
@yangjie21 我是将 ant-design/pro-components更新到 1.1.20 得到解决,另外后面 发现打包后和打包前不同的情况在我 `npm i`更新了本地依赖后消失了. 希望对你的问题有所帮助
