### ISSUE TITLE
👑 [优化建议]  针对pro-table，ellipsis为true时，出现tooltips以及title，建议去除title

### ISSUE THREAD

**Issue by JesonSirius** [ant-design/pro-components#578]
### 🥰 需求描述

ellipsis为true时，出现tooltips以及title，两种展现形式，同时出现会显得很怪

### 🧐 解决方案

建议在ellipsis为true时干掉title属性

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/35722299/94097563-503de700-fe59-11ea-9a8b-a74ddebfcc50.png)

![image](https://user-images.githubusercontent.com/35722299/94097706-98f5a000-fe59-11ea-9906-4036666cd6b7.png)

**Comment by chenshuai2144** [comment]
来个 pr？
