### ISSUE TITLE
🧐[问题] ProTable的options选项里设置了search的onSearch方法，搜索时会调用两次

### ISSUE THREAD

**Issue by yutao33** [ant-design/pro-components#5780]
### 🧐 问题描述

ProTable的options选项里设置了search的onSearch方法，搜索时会触发两次搜索，想问下相关代码里为什么要这样做，是不是bug?

### 💻 示例代码

```js
<ProTable
	....
	options={{
		search: {
			onSearch: (value) =>{
				console.log(value);
			}
		}
	}}
/>

```

关联的代码，两个onSearch都不为空，而且都会触发参数里的onSearch方法

https://github.com/ant-design/pro-components/blob/55f44e2d5b2fb57d9944e5c9969cd075b95c0abe/packages/table/src/components/ListToolBar/index.tsx#L161-L162

**Comment by chenshuai2144** [comment]
是故意的，每种配置都希望可以触发。所以才导致了这个问题。
