### ISSUE TITLE
🐛[BUG] 【proTable】onRest时未重置pageSize

### ISSUE THREAD

**Issue by Lpbzzz** [ant-design/pro-components#5782]
### 🐛 bug 描述

proTable 使用request请求数据，onRest时未重置pageSize

### 📷 复现步骤

proTable 要开启 showSizeChanger

### 🏞 期望结果

期望重置查询条件时，不光page重置，size也要重置

### 💻 复现代码

https://codesandbox.io/s/resetpagesize-ph4pq3

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

无

**Comment by kiner-tang** [comment]
`pageSize`用于规定一页获取的数量，通常修改了`pageSize`之后，重置是不需要重置`pageSize`的，不然页面上展示数据的数量会变来变去，不明白有什么场景需要再点击重置时重置`pageSize`，如果这个场景不常见，建议在`onReset`时手动重置。没必要继承到库中

**Comment by Lpbzzz** [comment]
> `pageSize`用于规定一页获取的数量，通常修改了`pageSize`之后，重置是不需要重置`pageSize`的，不然页面上展示数据的数量会变来变去，不明白有什么场景需要再点击重置时重置`pageSize`，如果这个场景不常见，建议在`onReset`时手动重置。没必要集成到库中

但是onReset时没发现有什么能控制proTable的page参数。除非不用request改用dataSource

**Comment by kiner-tang** [comment]
`pageSize`用`state`进行管理，`reset`的时候重置不行么？

**Comment by Lpbzzz** [comment]
> `pageSize`用`state`进行管理，`reset`的时候重置不行么？

当然可以用state管理。不过那不就放弃了用request了么？ 已经用了request的情况下，最好不改这里

**Comment by Lpbzzz** [comment]
> 

试了一下，感觉有点麻烦,如果想reset页码大小最好是用dataSource 而不是 request 。分页大小也算是查询参数，我觉得产品说的也有道理
