### ISSUE TITLE
Table如何手动修改Request返回的数据？

### ISSUE THREAD

**Issue by ldwonday** [ant-design/pro-components#5783]
ProTable使用Request请求后，我在对话框中的form编辑了某一行数据后，希望前端回写刚才编辑的数据，怎么实现？
同样还有删除数据、新增数据

**Comment by AlanKnightly** [comment]
@ldwonday 兄弟 你找到方法了嘛？

**Comment by ldwonday** [comment]
@chenshuai2144 这个问题看看哈

**Comment by ldwonday** [comment]
@chenshuai2144 这个问题麻烦看看哈

**Comment by 985563349** [comment]
@ldwonday 手动触发 table 的 reload 刷新列表即可。

**Comment by chenshuai2144** [comment]
用别的网络请求库吧。

或者修改数据提交给数据库，然后再刷新

**Comment by ldwonday** [comment]
@chenshuai2144 “或者修改数据提交给数据库，然后再刷新”，这个是要支持，但是有时还是希望能够前端实现列表刷新即可，要实现这个只能自己实现request然后传DataSource给table吧？

**Comment by chenshuai2144** [comment]
是的 


不过数据多个来源很危险 推荐不要这么搞
