### ISSUE TITLE
🧐[问题]ProFormCheckbox.Group 通过request 请求数据

### ISSUE THREAD

**Issue by kddloong** [ant-design/pro-components#5784]
### 🧐 问题描述

ProFormCheckbox.Group 通过request 请求数据, 请求的数据如果是空的, 想要设置个跳转的链接去配置, 该怎么做

proFieldProps 里面的emptyText 没有用

**Comment by chenshuai2144** [comment]
不支持这个用法的，你可以能需要用  renderFormItem 自定义
