### ISSUE TITLE
👑 [需求] 简化 submitter 的 layout 设置

### ISSUE THREAD

**Issue by zation** [ant-design/pro-components#5785]
### 🔩 所属模块或组件

ProForm

### 🥰 需求描述

可以增加 api 来设置 submitter 的 grid 吗？或者在在 horizontal layout 的情况下，默认让 wrapperCol.span 作为 submitter 的 span，让 labelCol.span 作为 submitter 的 offset

### ⛰ 功能需求适用场景

正常来说我们我们的按钮都是要跟输入框对齐的，现在的实现方式是每次自己用 row, col 组件写 submiter 的 render 方法，希望可以有更方便的配置来简化这里

**Comment by chenshuai2144** [comment]
我们不推荐对其，所以官方不会做更简单办法来推荐这个用法
