### ISSUE TITLE
🧐[问题]EditableProTable每次删除或新增一行的时候，都非常卡

### ISSUE THREAD

**Issue by HoraceZ919** [ant-design/pro-components#5787]
EditableProTable每次删除或新增一行的时候，都是必须要重新渲染整个table吗？官网给的那个actionRef.current?.addEditRecord(row)有没有demo能看下怎么用啊？

**Comment by chenshuai2144** [comment]
设计是这样的，最好控制一下渲染的格子数和列表。

如果有大数据的场景推荐使用一下虚拟表格。
