### ISSUE TITLE
🧐[问题]EditableProTable组件，添加子项时候，视图展示错乱

### ISSUE THREAD

**Issue by liuchuan-alex** [ant-design/pro-components#5789]
EditableProTable组件，添加子项时候，视图展示错乱，帮忙看看如何解决， 如下图所示：

![image](https://user-images.githubusercontent.com/17784679/187023137-09e6de76-1af6-46e7-a42f-7db791c45494.png)

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/~demos/editabletable-children

这个demo看起来没问题，检查下是不是样式污染了
