### ISSUE TITLE
🐛[BUG] ProTable列设置dataRange后第一次请求日期不格式化、点击查询参数才格式化

### ISSUE THREAD

**Issue by zim-lee** [ant-design/pro-components#579]
### 🐛 bug 描述

```js
title: '归档日期',
dataIndex: 'archiveDate',
key: 'archiveDate',
align: 'center',
valueType: 'dateRange',
fieldProps: {
	disabledDate: current => current && current > moment().subtract(1, 'd'),
	showToday: false,
	showTime: false,
	showNow: false,
	allowEmpty: [true, true],
},
render: (_, { archiveDate }) => archiveDate,
```

配置设置了key值，所以跟  #382 不是同一个问题

### © 版本信息

- ProTable 版本:2.7.2（新版2.8.1一样存在）
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

初始查询：
![1](https://user-images.githubusercontent.com/6970789/94113490-8be8a900-fe79-11ea-9935-ed73061ce308.png)
点击查询按钮查询：
![2](https://user-images.githubusercontent.com/6970789/94113496-90ad5d00-fe79-11ea-965a-3be09cf8436e.png)

另外2.8.1列设置`ellipsis=true`后`width`无效，tooltip和原生的title一起展示

**Comment by chenshuai2144** [comment]
> 另外2.8.1列设置ellipsis=true后width无效，tooltip和原生的title一起展示

2.8.2修了
