### ISSUE TITLE
normalize属性的第二个参数如果是undefined,返回第二个参数的时候就会出现卡死的状态

### ISSUE THREAD

**Issue by ILoveChy** [ant-design/pro-components#5791]
### Reproduction link

https://codesandbox.io/s/tong-bu-ti-jiao-jie-guo-dao-url-forked-lcc1lr?file=/App.tsx

### Steps to reproduce

```ts
<ProFormSelect
  label="测试选择框"
  name={'test'}
  options={[
    { label: '选我回到上一个', value: '111' },
    { label: '选我没有事情发生', value: '2222' },
  ]}
  normalize={(cur, pre) => {
    if (cur === '111') {
      message.error('你没选对,现在我要把你恢复成你选之前的样子');
      return pre;
    }
    return cur;
  }}
  rules={[
    {
      required: true,
      message: '我是必填校验',
    },
  ]}
/>
```
> 步骤大概是  首先下拉必填 下拉A和B 在选择A时候我自己写了个校验,提示选择错误并且返回上一个,但是如果我先选择B=>清空下拉=>选择A, 就会提示required校验文字,但是选择框的显示上就还是A的那个选项(其实现在下拉在Form上的值已经是undefined了)

### What is expected?

在pre为undefined的时候 如果要回到上一个,也就是回到pre,显示上下拉跟Form数据同步

### What is actually happening?

显示跟Form数据不同步

| Environment | Info |
| --- | --- |
| antd | 4.22.7 |
| React | 17  |
| System | mac12 |
| Browser | edge 100  |

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


感谢提供在线重现实例。

经测试，根据你的代码实现，在重现的情况下，在变量cur为'111'，pre为undefined的情况下，确实出现了无法复原回到前一个选项的问题。

现在有两个解决办法：
1. 当pre为undefined时，强制返回空字符串：

```ts
normalize={(cur, pre) => {
    if (cur === '111') {
      message.error('你没选对,现在我要把你恢复成你选之前的样子');
      return pre || '';
    }
    return cur;
  }}
```

2. 当pre为undefined时，强制返回一个默认值（比如第一个选项）：

```ts
normalize={(cur, pre, options) => {
    if (cur === '111') {
      message.error('你没选对,现在我要把你恢复成你选之前的样子');
      return pre || options[0].value;
    }
    return cur;
  }}
```

此外，可以指定下拉框的初始选项默认值（如果需要），这可以保证第一次打开页面时的显示跟Form数据也是同步的。

```ts
<ProFormSelect
  label="测试选择框"
  name={'test'}
  options={[
    { label: '选我回到上一个', value: '111' },
    { label: '选我没有事情发生', value: '2222' },
  ]}
  normalize={(cur, pre, options) => {
    if (cur === '111') {
      message.error('你没选对,现在我要把你恢复成你选之前的样子');
      return pre || options[0].value;
    }
    return cur;
  }}
  initialValue="2222"
  rules={[
    {
      required: true,
      message: '我是必填校验',
    },
  ]}
/>
```

希望这些解决方案可以解决你的问题。

**Comment by ILoveChy** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。
> 
> 感谢提供在线重现实例。
> 
> 经测试，根据你的代码实现，在重现的情况下，在变量cur为'111'，pre为undefined的情况下，确实出现了无法复原回到前一个选项的问题。
> 
> 现在有两个解决办法：
> 
> 1. 当pre为undefined时，强制返回空字符串：
> 
> ```ts
> normalize={(cur, pre) => {
>     if (cur === '111') {
>       message.error('你没选对,现在我要把你恢复成你选之前的样子');
>       return pre || '';
>     }
>     return cur;
>   }}
> ```
> 
> 2. 当pre为undefined时，强制返回一个默认值（比如第一个选项）：
> 
> ```ts
> normalize={(cur, pre, options) => {
>     if (cur === '111') {
>       message.error('你没选对,现在我要把你恢复成你选之前的样子');
>       return pre || options[0].value;
>     }
>     return cur;
>   }}
> ```
> 
> 此外，可以指定下拉框的初始选项默认值（如果需要），这可以保证第一次打开页面时的显示跟Form数据也是同步的。
> 
> ```ts
> <ProFormSelect
>   label="测试选择框"
>   name={'test'}
>   options={[
>     { label: '选我回到上一个', value: '111' },
>     { label: '选我没有事情发生', value: '2222' },
>   ]}
>   normalize={(cur, pre, options) => {
>     if (cur === '111') {
>       message.error('你没选对,现在我要把你恢复成你选之前的样子');
>       return pre || options[0].value;
>     }
>     return cur;
>   }}
>   initialValue="2222"
>   rules={[
>     {
>       required: true,
>       message: '我是必填校验',
>     },
>   ]}
> />
> ```
> 
> 希望这些解决方案可以解决你的问题。
这个是chatGPT回答的嘛,深啦~
上面给的三种处理方式可以解决form的校验不同步还有pre为undefined的问题.
但是按照上面的方式不太符合我这边的业务需求,那个下拉是需要联动决定的.
当时处理方式是砍掉了需求,在下拉属性上加了
```js
allowClear={false}
```
避免掉了pre是undefined的可能.
但是还是觉得本身的normalize属性的pre是可以再优化下的

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您的回复，确实，现有的两种解决方案针对您的业务场景不够准确，如果直接设置`allowClear={false}`，会影响用户体验。

实际上，Ant Design Pro使用的Form组件中validateFieldsAndScroll、validateFields、getFieldValue等方法的normalizeNestedPathVal函数中，是将当前值与上一次的值比较的。因此，我们可以仿造这种方法，在`normalize`方法中也将当前值与上一次的值进行比较，下一次进入`normalize`方法时就可以保证上一次的值肯定不为undefined了。

在表单组件的`Props`中增加一个类似于`fieldName`的`Props`即可实现此目的（这个Props是出于示例考虑取的名字，您可以给这个Props取个更加符合业务场景的名字，例如`previousValue`）。

```ts
interface ProFormSelectProps {
  label: string;
  name: string;
  options: { label: string; value: any }[];
  normalize?: (value: any, previousValue: any, previousValueFieldName?: string) => any;
  previousValueFieldName?: string; // 新加这个字段
  initialValue?: any;
  loading?: boolean;
  rules?: Rule[];
}
```

给`previousValueFieldName`设置默认值为undefined，然后在组件内部，在第一次执行`normalize`函数时，将上一次的值记录下来，并且保存这个值的`fieldName`。下次执行`normalize`函数时，就将这个值传递给`previousValue`，保证可以拿到有意义的上一次的值。示例如下：

```tsx
import React from "react";
import { Form, message } from "antd";
import { ProFormSelect } from "@ant-design/pro-form";
import { Rule } from "rc-field-form/es/interface";
import "./styles.css";

interface ProFormSelectProps {
  label: string;
  name: string;
  options: { label: string; value: any }[];
  normalize?: (value: any, previousValue: any, previousValueFieldName?: string) => any;
  previousValueFieldName?: string; // 新加这个字段
  initialValue?: any;
  loading?: boolean;
  rules?: Rule[];
}

const TestComponent = () => {
  const [form] = Form.useForm();

  const handleFinish = (values: any) => {
    console.log(values);
  };

  const handleChange = (val: any) => {
    console.log(val);
  };

  const handleNormalize = (cur: any, pre: any, preName: string) => {
    if (cur === "111") {
      message.error(
        "你没选对,现在我要把你恢复成你选之前的样子"
      );
      return pre;
    }
    return cur;
  };

  const previousValueFieldNames: string[] = [];

  const testProps: ProFormSelectProps = {
    label: "测试选择框",
    name: "test",
    options: [
      { label: "选我回到上一个", value: "111" },
      { label: "选我没有事情发生", value: "2222" }
    ],
    normalize: (cur, pre, name) => {
      if (name) {
        previousValueFieldNames.push(name);
      }
      const previousFieldName = previousValueFieldNames[previousValueFieldNames.length - 2];
      return handleNormalize(cur, pre, previousFieldName);
    },
    previousValueFieldName: previousValueFieldNames[previousValueFieldNames.length - 1],
    rules: [
      {
        required: true,
        message: "我是必填校验"
      }
    ]
  };

  return (
    <Form form={form} onFinish={handleFinish}>
      <ProFormSelect {...testProps} onChange={handleChange} />
      <Form.Item>
        <button type="submit">提交</button>
      </Form.Item>
    </Form>
  );
};

export default TestComponent;

```

这样就可以实现在不影响用户体验的情况下，保证点击"回到上一个"可以恢复到确切的上一个选项。为保证正常运行，`normalize`函数的函数签名增加了一个参数：字符串类型的`previousValueFieldName`，这个参数表示上一轮的值所在的字段（经过多轮测试后只能通过这种方式正确指向上一个值的位置），需要将其保存在之前提到的`previousValueFieldNames`数组中。

希望这个解决方案可以解决您的疑惑。

**Comment by chenshuai2144** [comment]
normalize 感觉不应该做这种事情。看了下源码也不好改，先算了吧
