### ISSUE TITLE
🐛[BUG] BetaSchemaForm 配置 request 时，第一次打开取不到 form 不正确

### ISSUE THREAD

**Issue by wangxin305** [ant-design/pro-components#5794]
### 🐛 bug 描述
BetaSchemaForm 表单 配置request时，第一次打 form取值为 {}

### 💻 复现代码

```
<BetaSchemaForm
        trigger={<Button>取不到form</Button>}
        request={async () => {
          return {
            test: 666,
          };
        }}
        columns={[
          {
            title: 'ID',
            dataIndex: 'test',
            fieldProps: (form) => {
              console.log(form);
              //配置request 时，第一次打开,form为空
              return {
                onChange: () => {
                  console.log(form);
                  //这里没有问题
                },
              };
            },
          },
        ]}
        layoutType={'ModalForm'}
      />
```

### © 版本信息

@ant-design/pro-form："1.74.3",

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


根据你提供的代码，发现当 BetaSchemaForm 首次渲染时，form 实例确实为空。这是因为 request 方法需要一定的异步执行时间，以获取数据并渲染 BetaSchemaForm，因此需要一些额外的处理来避免这个问题。

一种解决方法是使用 useState 保存表单的值，并在 request 回调中更新，示例代码如下：

```jsx
import React, { useState } from 'react';
import { BetaSchemaForm, ModalForm } from '@ant-design/pro-form';
import { Button } from 'antd';

const Demo = () => {
  const [formData, setFormData] = useState({});

  return (
    <BetaSchemaForm
      trigger={<Button>取不到form</Button>}
      request={async () => {
        const data = {
          test: 666,
        };
        setFormData(data);
        return data;
      }}
      columns={[
        {
          title: 'ID',
          dataIndex: 'test',
          fieldProps: {
            onChange: (_, value) => {
              setFormData({
                test: value,
              });
            },
            value: formData.test, // 绑定表单值
          },
        },
      ]}
      layoutType={ModalForm}
    />
  );
};

export default Demo;
```

在这个 Demo 中，我们使用 useState 来保存表单的值，请求回来后通过 setFormDate 更新表单的值，这样就能正常渲染表单了，同时我们将表单的值绑定到 fieldProps 上，以保证表单一直是最新的值。

另外，`fieldProps` 不需要传递 `form` 参数，因为 BetaSchemaForm 的所有表单项都会自动绑定 form 上下文。

最后，给你提供的一个链接，介绍 ProForm 的使用：[https://procomponents.ant.design/components/form#%E5%AE%9E%E4%BE%8B-1](https://procomponents.ant.design/components/form#%E5%AE%9E%E4%BE%8B-1)，希望对你有所帮助。

**Comment by chenshuai2144** [comment]
已经修复了，可以更新版本啦
