### ISSUE TITLE
🐛[BUG] BetaSchemaForm中，设置valueType为digit时候，输入小数，会自动重置为整数

### ISSUE THREAD

**Issue by HaileyGermanotta** [ant-design/pro-components#5800]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

BetaSchemaForm中，设置valueType为digit时候，输入小数，会自动重置为整数

### 📷 复现步骤

https://codesandbox.io/s/digitwu-fa-shu-ru-xiao-shu-gjvyyu?file=/App.tsx

1. 输入小数0.1，控件失去焦点后，会显示0
2. 输入小数9.9，控件失去焦点后，会显示10

### 🏞 期望结果

1. 输入小数0.1，控件失去焦点后，会显示0.1
2. 输入小数9.9，控件失去焦点后，会显示9.9

### 💻 复现代码

https://codesandbox.io/s/digitwu-fa-shu-ru-xiao-shu-gjvyyu?file=/App.tsx

### © 版本信息

- ProComponents 版本: 2.2.1
- 浏览器环境 chrome
- 开发环境 mac OS

**Comment by Dunqing** [comment]
![image](https://user-images.githubusercontent.com/29533304/187336871-0cf91840-7b57-4409-a0c5-6bd8c6eeebc6.png)

默认是整数，可以在fieldProps中设置参数，参数同[InputNumber](https://ant.design/components/input-number/#API)

**Comment by drizzlesconsin** [comment]
@Dunqing 默认就是支持小数的，antd InputNumber 默认也是支持小数的。

~~实在是不知道从哪个版本开始改成整数的。或是被最近哪个PR改掉了~~

https://procomponents.ant.design/components/field-set#proformdigit
<img width="686" alt="image" src="https://user-images.githubusercontent.com/69514654/195605558-b00dde99-42e5-40ee-96b9-9782eae399ad.png">

https://codesandbox.io/s/gu-ding-ye-jiao-forked-5v4wzv?file=%2FApp.tsx

**应该是 pro-form 导致的问题，还没细看。**

@chenshuai2144 建议reopen
