### ISSUE TITLE
👑 [需求] ProTable中通过数值而不是档位来设置行高

### ISSUE THREAD

**Issue by jiyu-sheng** [ant-design/pro-components#5806]
### 🔩 所属模块或组件
ProTable

### 🥰 需求描述
目前ProTable的行高有三个档位，在某些需要密集数据展示的场景下，即便设为紧凑的情况下，表格中仍然有相当的空白，可否通过数值来设置行高来满足不同的展示需求呢？

**Comment by chenshuai2144** [comment]
不可能支持的，太自由反而不好用。跟着设计师节奏来吧
