### ISSUE TITLE
🧐[求助] 如何解决这个库引入@import '~antd/es/style/themes/default.less'; 导致覆盖项目中的自定义样式的问题

### ISSUE THREAD

**Issue by Wang-yubo** [ant-design/pro-components#5809]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🚑 其他信息

<img width="935" alt="image" src="https://user-images.githubusercontent.com/59524432/187340780-24691730-c855-4fd3-85cb-d8c1a463c65c.png">

**Comment by folt** [comment]
I am getting the same problem

```
    resolve: {
      alias: [
        { find: /^~/, replacement: '' },
        .....
      ],
```
with this decision, mine have less priority

**Comment by Wang-yubo** [comment]
> I am getting the same problem
> 
> ```
>     resolve: {
>       alias: [
>         { find: /^~/, replacement: '' },
>         .....
>       ],
> ```
> 
> with this decision, mine have less priority

Thank you for your help, but I still failed.I use create-react-app and webpack-5, which do not support find and replacement.
I also try to use “~”：/”,but it didn't achieve the desired effect.
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/59524432/188044461-c6f6bd25-1d6f-45f8-b1df-9242b702a68d.png">
<img width="846" alt="image" src="https://user-images.githubusercontent.com/59524432/188044490-b77d3b18-1ef5-4fe6-815a-9eca6318fd7c.png">

**Comment by folt** [comment]
my vite config 
![image](https://user-images.githubusercontent.com/3757488/188234486-274c78dc-c3f3-44e1-a77b-a6ce2c37892b.png)

**Comment by Wang-yubo** [comment]
@folt I am very happy to tell you that I have solved this problem today. I use webpack config "[additionalData](https://webpack.docschina.org/loaders/less-loader/#additionaldata)"  removed all antd styles in the compilation phase。
<img width="787" alt="image" src="https://user-images.githubusercontent.com/59524432/188270305-c339ab73-a9cf-4b0d-90ed-d449c20a8e59.png">
