### ISSUE TITLE
🐛[BUG] EditableProTable action cancelEditable 取消后不重置已经修改的 

### ISSUE THREAD

**Issue by ghost** [ant-design/pro-components#5813]
### 🐛 bug 描述

 调用后，不重置
tableRef.current?.cancelEditable?.(record.id, true);

### © 版本信息

- ProComponents 版本: 1.1.15
- umi 版本 3.5.0
- 浏览器环境 chrome
- 开发环境 mac OS

**Comment by chenshuai2144** [comment]
不重置，只是取消了编辑模式
