### ISSUE TITLE
🐛[BUG] 打包上生产之后，ProTable分页不起作用

### ISSUE THREAD

**Issue by 1998729** [ant-design/pro-components#5815]
"@ant-design/pro-table": "^2.71.0",
"antd": "^4.19.0",
"umi": "^3.5.0"

我在测试环境使用分页一切正常，生产之后选择分页之后，后端正常返回分页几对应的pageSize数量，但是前端不渲染！

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/88186802/187434322-262e3109-2fea-4651-ae92-f50ab331a74e.png">

<img width="527" alt="image" src="https://user-images.githubusercontent.com/88186802/187434456-dea91470-ba86-4392-bf8d-fad03df0e94d.png">

**Comment by 1998729** [comment]
const asyncTableSearchRequest = async (params: SearchItem, sort: any, filter: any) => {
    // 通用请求参数
    const combinationParams = {
      pageNum: params.current,
      pageSize: params.pageSize,
    }

    // 查询参数
    const searchParams = {}

    for (const key in params) {
      if (!SearchParamsReverse[key]) {
        continue
      }
      searchParams[SearchParamsReverse[key]] = params[key]
    }

    if (Object.keys(searchParams).length !== 0) {

      // 声明查询条件
      // 用于后端搜索使用
      let searchStr = ""

      // 循环遍历字符串
      for (const key in searchParams) {
        searchStr += `${key}=${searchParams[key]},`
      }

      // @ts-ignore
      combinationParams.filter = searchStr.substr(0, searchStr.lastIndexOf(','))
    }

    const result = await queryBusinessRule(query.businessId, combinationParams)

    return {
      data: result.data.list,
      // success 请返回 true，
      // 不然 table 会停止解析数据，即使有数据
      success: result.success,
      // 不传会使用 data 的长度，如果是分页一定要传
      total: result.data.total,
    };
  }

**Comment by JackPennnnn** [comment]
pageSize: 10, 改成 defaultPageSize:10 看看

**Comment by 1998729** [comment]
> pageSize: 10, 改成 defaultPageSize:10 看看

我可以尝试试试，但是能确定的是同样的代码，生产环境就不好使，fetch没问题， loading也会加载，数据返回之后列和pagesize不起作用

**Comment by 1998729** [comment]
> pageSize: 10, 改成 defaultPageSize:10 看看
 确实可以了， 这是bug么？ chenshuai在吗， 给个结论啊

**Comment by Mzhang1994** [comment]
> > pageSize: 10, 改成 defaultPageSize:10 看看
> > 确实可以了， 这是bug么？ chenshuai在吗， 给个结论啊

你pro-table的包升级成2.80.3以上，先前页码受控有问题。

**Comment by JackPennnnn** [comment]
> > pageSize: 10, 改成 defaultPageSize:10 看看
> > 确实可以了， 这是bug么？ chenshuai在吗， 给个结论啊

应该不算，pageSize写死了10，就改不了了。类似value跟defaultValue的关系吧

**Comment by 1998729** [comment]
> > > pageSize: 10, 改成 defaultPageSize:10 看看
> > > 确实可以了， 这是bug么？ chenshuai在吗， 给个结论啊
> 
> 应该不算，pageSize写死了10，就改不了了。类似value跟defaultValue的关系吧

比较奇怪的是本地环境没问题， build的时候package里面的版本应该不会变的

**Comment by 1998729** [comment]
> > > pageSize: 10, 改成 defaultPageSize:10 看看
> > > 确实可以了， 这是bug么？ chenshuai在吗， 给个结论啊
> 
> 你pro-table的包升级成2.80.3以上，先前页码受控有问题。

好的哥。

**Comment by SergioMaldonado2108** [comment]
Hi 1998729,
Do you resolve the issue? I'm facing the same situation
"@ant-design/pro-table": "^2.74.1",
"antd": "^4.19.4",
"umi": "^3.5.21"
"react": "^17.0.0",

Thanks in advance
