### ISSUE TITLE
🐛[BUG]打包上uat和生产之后，ProTable分页bug

### ISSUE THREAD

**Issue by thefinccc** [ant-design/pro-components#5818]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by powerXuDong** [comment]
请问解决的版本是哪个

**Comment by youtiao66** [comment]
@thefinccc @powerXuDong 看看是不是这个原因（table 的 param发生变化时重置分页为1）导致的 https://github.com/ant-design/pro-components/issues/5628#issuecomment-1253171082

**Comment by jiangyanfu** [comment]
请问这个问题解决了吗
