### ISSUE TITLE
🐛[BUG] QueryFilter 中表单第一项使用ColSize设置为4时不生效，使用的默认span={6}

### ISSUE THREAD

**Issue by DJGDragon** [ant-design/pro-components#5821]
在使用QueryFilter 时使用defaultColsNumber 来设置默认的展开项 但是只要第一项的数据设置的colSize设置的值等于24/span时的默认展开是不正常的  这边想要的效果是第一项单独展示一行  默认展开项是按照defaultColsNumber设置的值来显示
![image](https://user-images.githubusercontent.com/23696556/187606677-7c0de782-334f-4e21-bf1d-380ad44e9fda.png)

![1661926256211](https://user-images.githubusercontent.com/23696556/187606454-215abd80-6e83-4eb5-a474-a18c4b7e2462.jpg)

**Comment by DJGDragon** [comment]
能不能解决这个bug呀  导致我一直不能升级新的form   旧版本的form就没有这个bug

**Comment by DJGDragon** [comment]
实例：https://codesandbox.io/s/cha-xun-shai-xuan-forked-7g081i?file=/App.tsx

其实别人也有提同样得问题，只是一直没有解决，同https://github.com/ant-design/pro-components/issues/5903

现在默认查询条件第一个输入框单独占用一行用的colSize={4}，但是又想默认展示三个（或者三行）查询条件，只要第一行设置了colSize>2, 那么设置的defaultColsNumber不管是多少都是无效的，现在想要defaultColsNumber是有效的。
 以前老版本就是好用的，在1.60.1之后就出现了这个bug之前也有人提过这个问题https://github.com/ant-design/pro-components/issues/5328，但是实际上并没有在后续版本把这个问题修复掉，有好多人都提了这个问题，希望大神看看修复一下吧

**Comment by DJGDragon** [comment]
实例：https://codesandbox.io/s/cha-xun-shai-xuan-forked-7g081i?file=/App.tsx

其实别人也有提同样得问题，只是一直没有解决，同https://github.com/ant-design/pro-components/issues/5903

现在默认查询条件第一个输入框单独占用一行用的colSize={4}，但是又想默认展示三个（或者三行）查询条件，只要第一行设置了colSize>2, 那么设置的defaultColsNumber不管是多少都是无效的，现在想要defaultColsNumber是有效的。
以前老版本就是好用的，在1.60.1之后就出现了这个bug之前也有人提过这个问题见：https://github.com/ant-design/pro-components/issues/5328  

但是实际上并没有在后续版本把这个问题修复掉，有好多人都提了这个问题，希望大神看看修复一下吧

**Comment by chenshuai2144** [comment]
这个 demo 写的真好

**Comment by chenshuai2144** [comment]
这个逻辑好像没问题，你需要的是 defaultRowNumber 把

**Comment by DJGDragon** [comment]
> 这个逻辑好像没问题，你需要的是 defaultRowNumber 把。默认展示的行

对 也可以加一个这个参数defaultRowNumber   如果按照之前1.60.1的的版本设置defaultColsNumber默认展开几个列的显示也是可以的  只要能用就行

**Comment by chenshuai2144** [comment]
> 对 也可以加一个这个参数defaultRowNumber 如果按照之前1.60.1的的版本设置defaultColsNumber默认展开几个列的显示也是可以的 只要能用就行

来个pr吧。我们内部不需要这个功能，我们就没做
