### ISSUE TITLE
🐛[BUG]QueryFilter的defaultColsNumber=0时无效

### ISSUE THREAD

**Issue by Vibrant-Robert** [ant-design/pro-components#5824]
### 🐛 bug 描述

用QueryFilter实现布局，点击收起按钮时预期结果为全部收起，即展示项为0。设置defaultColsNumber为0，但仍显示一行

**Comment by chenshuai2144** [comment]
不支持这样配置的，太奇怪了。

有条件自己实现一个吧，没条件就用官方的逻辑
