### ISSUE TITLE
🐛[BUG] Uncaught TypeError: Cannot read property '_context' of undefined

### ISSUE THREAD

**Issue by forzalianjunting** [ant-design/pro-components#583]
### 🐛 bug 描述

pro-table 同样一套代码，从 2.7.4 升级 2.8.1 就报错

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/15181706/94153427-5a8ad000-feaf-11ea-91cc-9389f2dce245.png)

**Comment by meyerlee** [comment]
2.81 应该是有bug， 用了最简单的代码

  const columns = [
    {
      title: 't1', 
      dataIndex: 't1',
    },
    {
      title: 't2', 
      dataIndex: 't2',
    },
  ];

  return <ProTable columns={columns} />;

也会报这个错误。

**Comment by forzalianjunting** [comment]
> 2.81 应该是有bug， 用了最简单的代码
> 
> const columns = [
> {
> title: 't1',
> dataIndex: 't1',
> },
> {
> title: 't2',
> dataIndex: 't2',
> },
> ];
> 
> return ;
> 
> 也会报这个错误。

@meyerlee 是的，我先以为我写法有误，但改成最简单的 pro-table demo 也会报错

**Comment by ffalconjs** [comment]
用到pro组件的地方全都抛异常

**Comment by chenshuai2144** [comment]
升级antd的版本，用了 4.6.4 的新功能
