### ISSUE TITLE
🐛[BUG]日历国际化问题

### ISSUE THREAD

**Issue by Mzhang1994** [ant-design/pro-components#5833]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

日历国际化的问题真的需要你们统一处理一下。现在官网也出现这个问题了。我先前调版本调了好久都没啥用。provider也不能解决问题。

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/69185609/187874987-ac2a6be3-3b4b-4971-bb67-2411fa28614d.png)

### 🏞 期望结果

日历国际化，语言统一

**Comment by erguotou520** [comment]
The same question

**Comment by jiangkaifree** [comment]
pro component 文档确实没说明相关的解决，下面是我的曲线救国方式，
![image](https://user-images.githubusercontent.com/50451924/197484519-4eafde73-4f1b-4850-8d33-a7a01a27fb97.png)

1.  安装 `momentjs` ， 
> antd 的日期选择依赖于 `moment`，但不排除有部分使用者，讲 `momentjs` 改成了 `dayjs`。如果改成了 `dayjs` 我并不知道能不能成功。
2. 导入 `moment` 的语言
```js
import 'moment/locale/zh-cn';

<ProFormDatePicker
        name="expirationDate"
        rules={[{ required: true, message: '请选择到期时间!' }]}
        fieldProps={{
          locale: { locale },
        }}
        label="到期时间"
      />
```

**Comment by jiangkaifree** [comment]
> 提问前先看看：
> 
> https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
> 
> ### 🐛 bug 描述
> 日历国际化的问题真的需要你们统一处理一下。现在官网也出现这个问题了。我先前调版本调了好久都没啥用。provider也不能解决问题。
> 
> ### 📷 复现步骤
> ![image](https://user-images.githubusercontent.com/69185609/187874987-ac2a6be3-3b4b-4971-bb67-2411fa28614d.png)
> 
> ### 🏞 期望结果
> 日历国际化，语言统一


解决方式： https://github.com/ant-design/pro-components/issues/5833#issuecomment-1288661470

**Comment by Mzhang1994** [comment]
> pro component 文档确实没说明相关的解决，下面是我的曲线救国方式， ![image](https://user-images.githubusercontent.com/50451924/197484519-4eafde73-4f1b-4850-8d33-a7a01a27fb97.png)
> 
> 1. 安装 `momentjs` ，
> 
> > antd 的日期选择依赖于 `moment`，但不排除有部分使用者，讲 `momentjs` 改成了 `dayjs`。如果改成了 `dayjs` 我并不知道能不能成功。
> 
> 2. 导入 `moment` 的语言
> 
> ```js
> import 'moment/locale/zh-cn';
> 
> <ProFormDatePicker
>         name="expirationDate"
>         rules={[{ required: true, message: '请选择到期时间!' }]}
>         fieldProps={{
>           locale: { locale },
>         }}
>         label="到期时间"
>       />
> ```

我知道这个方法，我这边项目是双语的，后面可能还会扩展语言。而且，项目里用到特别多这个组件，一个个改，太麻烦了。我就想有没有方法可以直接配置。一劳永逸。

**Comment by soulcm** [comment]
> > pro component 文档确实没说明相关的解决，下面是我的曲线救国方式， ![image](https://user-images.githubusercontent.com/50451924/197484519-4eafde73-4f1b-4850-8d33-a7a01a27fb97.png)
> > 
> > 1. 安装 `momentjs` ，
> > 
> > > antd 的日期选择依赖于 `moment`，但不排除有部分使用者，讲 `momentjs` 改成了 `dayjs`。如果改成了 `dayjs` 我并不知道能不能成功。
> > 
> > 
> > 
> > 2. 导入 `moment` 的语言
> > 
> > ```js
> > import 'moment/locale/zh-cn';
> > 
> > <ProFormDatePicker
> >         name="expirationDate"
> >         rules={[{ required: true, message: '请选择到期时间!' }]}
> >         fieldProps={{
> >           locale: { locale },
> >         }}
> >         label="到期时间"
> >       />
> > ```
> 
> 我知道这个方法，我这边项目是双语的，后面可能还会扩展语言。而且，项目里用到特别多这个组件，一个个改，太麻烦了。我就想有没有方法可以直接配置。一劳永逸。

+1

**Comment by chenshuai2144** [comment]
这个应该是脚手架要处理的事情，umi 打开 antd 插件会自动处理，如果是其他脚手架按照 antd 官网的文档设置一下就能解决

**Comment by soulcm** [comment]
迷之操作，就这样关了吗，你们有自己看pro官网 https://procomponents.ant.design/components/table#%E9%80%9A%E8%BF%87-formref-%E6%9D%A5%E6%93%8D%E4%BD%9C%E6%9F%A5%E8%AF%A2%E8%A1%A8%E5%8D%95，查询表单的日期也变成英文了吗，之前都还是正常的

**Comment by hsbtr** [comment]
> pro component 文档确实没说明相关的解决，下面是我的曲线救国方式， ![image](https://user-images.githubusercontent.com/50451924/197484519-4eafde73-4f1b-4850-8d33-a7a01a27fb97.png)
> 
> 1. 安装 `momentjs` ，
> 
> > antd 的日期选择依赖于 `moment`，但不排除有部分使用者，讲 `momentjs` 改成了 `dayjs`。如果改成了 `dayjs` 我并不知道能不能成功。
> 
> 2. 导入 `moment` 的语言
> 
> ```js
> import 'moment/locale/zh-cn';
> 
> <ProFormDatePicker
>         name="expirationDate"
>         rules={[{ required: true, message: '请选择到期时间!' }]}
>         fieldProps={{
>           locale: { locale },
>         }}
>         label="到期时间"
>       />
> ```

fieldProps中的locale： { locale }不太明白，locale这个变量那里来的啊

**Comment by hsbtr** [comment]
这个问题是不会修复了嘛

**Comment by jiangkaifree** [comment]
import locale from 'antd/es/date-picker/locale/zh_CN';


来自于 antd




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 🐛[BUG]日历国际化问题 (Issue #5833)





  
pro component 文档确实没说明相关的解决，下面是我的曲线救国方式， 
  
安装 momentjs ，
   
antd 的日期选择依赖于 moment，但不排除有部分使用者，讲 momentjs 改成了 dayjs。如果改成了 dayjs 我并不知道能不能成功。
   
导入 moment 的语言
  import 'moment/locale/zh-cn'; <ProFormDatePicker         name="expirationDate"         rules={[{ required: true, message: '请选择到期时间!' }]}         fieldProps={{           locale: { locale },         }}         label="到期时间"       /&gt;
  
fieldProps中的locale： { locale }不太明白，locale这个变量那里来的啊

**Comment by hsbtr** [comment]
> import locale from 'antd/es/date-picker/locale/zh_CN'; 来自于 antd
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ant-design/pro-components" ***@***.***&gt;; 发送时间:&nbsp;2022年11月24日(星期四) 上午10:33 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ant-design/pro-components] 🐛[BUG]日历国际化问题 (Issue #5833) pro component 文档确实没说明相关的解决，下面是我的曲线救国方式， 安装 momentjs ， antd 的日期选择依赖于 moment，但不排除有部分使用者，讲 momentjs 改成了 dayjs。如果改成了 dayjs 我并不知道能不能成功。 导入 moment 的语言 import 'moment/locale/zh-cn'; <ProFormDatePicker name="expirationDate" rules={[{ required: true, message: '请选择到期时间!' }]} fieldProps={{ locale: { locale }, }} label="到期时间" /&gt; fieldProps中的locale： { locale }不太明白，locale这个变量那里来的啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

非常感谢

**Comment by edifangyi** [comment]
最新版的     "@ant-design/pro-components": "^2.3.47",

只需要在页面中引入：

import 'dayjs/locale/zh-cn';

就可以恢复成中文，其他没有配置

**Comment by ideaviewes** [comment]
> 最新版的 "@ant-design/pro-components": "^2.3.47",
> 
> 只需要在页面中引入：
> 
> import 'dayjs/locale/zh-cn';
> 
> 就可以恢复成中文，其他没有配置

现在这个又不行了

**Comment by chenshuai2144** [comment]
注意下多版本 dayjs 的问题

**Comment by yudioll** [comment]
> 注意下多版本 dayjs 的问题

到底解决没？
