### ISSUE TITLE
🐛[BUG] Warning: [antd: Radio] `optionType` is only support in Radio.Group. 

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#5834]
分布式表单控制台错误，使用  pro-components 2X 版本

<img width="868" alt="image" src="https://user-images.githubusercontent.com/30397655/187914825-038bbeae-cd92-46fa-b41d-d192798c6027.png">

**Comment by leshalv** [comment]
@chenshuai2144

**Comment by bigmgreen** [comment]
https://github.com/ant-design/pro-components/blob/e20446fd95d676c6b2da12903282985297dd102c/packages/field/src/components/Radio/index.tsx#L81

https://github.com/ant-design/ant-design/blob/c0b9b07f87e73388653df0ccfcc0f1668ba2bce0/components/radio/radio.tsx#L22

会不会这里导致的？

**Comment by leshalv** [comment]
https://github.com/ant-design/pro-components/pull/5871

**Comment by hb1707** [comment]
同样遇到这个问题
