### ISSUE TITLE
🐛[BUG]官方文档出bug了 搜索

### ISSUE THREAD

**Issue by sjhowyou** [ant-design/pro-components#5837]
![image](https://user-images.githubusercontent.com/41765845/188039119-f6c95a0d-569c-4f5e-8fe7-6bd1c3f6eb6c.png)

**Comment by sjhowyou** [comment]
官网出bug啦

**Comment by kiner-tang** [comment]
可以提供一下链接么

**Comment by Marainer-ZS** [comment]
[ProComponents](https://procomponents.ant.design/)，搜索功能无法使用，搜索框输入任何字符都会造成页面白屏

**Comment by kiner-tang** [comment]
看起来是`dumi`的`useSearch`不支持`title`为对象的搜索方式，最近的一次更新的一些文档同时包含了中英文的标题
<img width="772" alt="image" src="https://user-images.githubusercontent.com/10286961/188292805-a90b10f8-6947-48dc-b967-f18a69c1bcee.png">
<img width="499" alt="image" src="https://user-images.githubusercontent.com/10286961/188292814-6df62505-2675-4c01-adf6-111b70cef607.png">
@chenshuai2144
