### ISSUE TITLE
🐛[BUG]Protable分页器每页条数切换失效，页码切换正常

### ISSUE THREAD

**Issue by 15390410330** [ant-design/pro-components#584]
### 🐛 bug 描述
proTable集成的分页器切换每页展示条目的时候无效，会触发分页器的onChang事件和onShowSizeChange事件，但是没有发起请求。

当页码不是第一页时点击每页展示条目切换时会发起请求，但是每页展示条目数仍然没有变化，只是会将页码重置为第一页

### 🏞 期望结果

点击20条后每页展示20条

### 💻 复现代码

import ProTable from '@ant-design/pro-table';

<ProTable
    actionRef={actionRef}
    pagination={{ pageSize: 10 }}
    rowKey="Id"
    onChange={(_, _filter, _sorter) => {
        const sorterResult = _sorter;
        if (sorterResult.field) {
            setSorter(`${sorterResult.field}_${sorterResult.order}`);
        }
    }}
    params={{
        sorter,
    }}
    toolBarRender={(_, selectedRows) => toolBarRender(selectedRows)}
    tableAlertRender={false}
    columns={columns}
    request={(params) => {
        const afterArr = {};
        if (state.current !== 'all') {
            afterArr.BillStatus = state.current;
        }
        return proGetData(params, dispatch, 'assetInStockBillHead/getLists', { OrderByName: 'InputTime', IsAsc: false }, afterArr)
    }}
/>

### © 版本信息

- ProComponents 版本:   "@ant-design/pro-table": "^2.2.0",
- umi 版本 "umi": "^3.1.0",
- 浏览器环境 chrome  83.0.4103.61
- 开发环境  Windows 7

### 🚑 其他信息
![QQ截图20200925092758](https://user-images.githubusercontent.com/45443940/94216216-6e671e00-ff11-11ea-858d-8e71f6427442.png)

**Comment by jockey100332** [comment]
> ### 🐛 bug 描述
> proTable集成的分页器切换每页展示条目的时候无效，会触发分页器的onChang事件和onShowSizeChange事件，但是没有发起请求。
> 
> 当页码不是第一页时点击每页展示条目切换时会发起请求，但是每页展示条目数仍然没有变化，只是会将页码重置为第一页
> 
> ### 📷 复现步骤
> ### 🏞 期望结果
> 点击20条后每页展示20条
> 
> ### 💻 复现代码
> import ProTable from '@ant-design/pro-table';
> 
> <ProTable
> actionRef={actionRef}
> pagination={{ pageSize: 10 }}
> rowKey="Id"
> onChange={(_, _filter, _sorter) => {
> const sorterResult = _sorter; if (sorterResult.field) { setSorter(`${sorterResult.field}_${sorterResult.order}`); } }} params={{ sorter, }} toolBarRender={(_, selectedRows) => toolBarRender(selectedRows)}
> tableAlertRender={false}
> columns={columns}
> request={(params) => {
> const afterArr = {};
> if (state.current !== 'all') {
> afterArr.BillStatus = state.current;
> }
> return proGetData(params, dispatch, 'assetInStockBillHead/getLists', { OrderByName: 'InputTime', IsAsc: false }, afterArr)
> }}
> />
> 
> ### © 版本信息
> * ProComponents 版本:   "@ant-design/pro-table": "^2.2.0",
> * umi 版本 "umi": "^3.1.0",
> * 浏览器环境 chrome  83.0.4103.61
> * 开发环境  Windows 7
> 
> ### 🚑 其他信息
> ![QQ截图20200925092758](https://user-images.githubusercontent.com/45443940/94216216-6e671e00-ff11-11ea-858d-8e71f6427442.png)
在pagination 对象中加入current 或者defaultCurrent，

**Comment by 15390410330** [comment]
> > ### 虫子 错误描述
> > proTable集成的分页器切换每页展示放置的时间无效，会触发分页器的onChangEvent和onShowSizeChangeEvent，但没有发起请求。
> > 当页码不是第一页时点击每页展示并切换时会发起请求，但是每页显示数量仍然没有变化，只是替换页码重置为第一页
> > ### 相机 复现步骤
> > ### 国家公园 期望结果
> > 点击20条后每页展示20条
> > ### 电脑 复现代码
> > 从'@ ant-design / pro-table'导入ProTable；
> > <ProTable 
> > actionRef = {actionRef} 
> > 分页= {{pageSize：10}} 
> > rowKey =“ Id” 
> > onChange = {（_，_filter，_sorter）=> { 
> > const sorterResult = sorter _; 如果（sorterResult.field）{setSorter（`${sorterResult.field}_${sorterResult.order}`）; }}} params = {{sorter，}} toolBarRender = {（_，selectedRows）=> toolBarRender（selectedRows）} 
> > tableAlertRender = {false} 
> > column = {columns} 
> > request = {{params）=> { 
> > const afterArr = {}; 
> > 如果（state.current！=='all'）{ 
> > afterArr.BillStatus = state.current; 
> > } 
> > return proGetData（params，dispatch，'assetInStockBillHead / getLists'，{OrderByName：'InputTime'，IsAsc：false}，afterArr）
> > }} 
> > />
> > ### ©版本信息
> > 
> > * ProComponents 版本:   "@ant-design/pro-table": "^2.2.0",
> > * umi 版本 "umi": "^3.1.0",
> > * 浏览器环境 chrome  83.0.4103.61
> > * 开发环境  Windows 7
> > 
> > ### 救护车 其他信息
> > ![QQ截图20200925092758](https://user-images.githubusercontent.com/45443940/94216216-6e671e00-ff11-11ea-858d-8e71f6427442.png)
> > 在pagination 对象中加入current 或者defaultCurrent，

加了之后，问题没有得到改善

**Comment by chenshuai2144** [comment]
升级 antd 的版本 或者 protabled 的版本，有个不兼容的修改

**Comment by 15390410330** [comment]
谢谢，把protable和antd都升级到最新版之后问题解决了

**Comment by whereiscode** [comment]
@15390410330 @chenshuai2144 我俩都升级到最新版本   它也不触发reuqest  只有第一页是可以的

**Comment by gaoxianglyx** [comment]
> @15390410330 @chenshuai2144 我俩都升级到最新版本 它也不触发reuqest 只有第一页是可以的

我也遇到了这个问题，根据测试，你在pagenation里面增加current参数，就能解决

**Comment by jiagouview** [comment]
> 升级 antd 的版本 或者 protabled 的版本，有个不兼容的修改

哪个版本的antd和protable版本，分页就没有bug了。我昨天升级到最新的版本，有些组件不好使了。

**Comment by Cathyccccc** [comment]
- 本人练习项目亲测~~这个触发正确展示条数的关键是**pagination属性中pageSize的改变**。**页面初始渲染条数**和**params的pageSize值**就是来自于pagination中的这个pageSize。因此手动更改这个pageSize，如在onShowSizeChange事件中借助useState重新设置，然后pagination中的pageSize和useState的值绑定。

`const [pageInfo, setPageInfo] = useState({ pageSize: 5, current: 1 });
// ......一些代码
<ProTable
  columns={...}
  request={...}
  actionRef={...}
  rowKey={...}
  pagination={{
    pageSize: pageInfo.pageSize, // 需要修改这个pageSize才会触发显示条数的实际改变
    onShowSizeChange: (current, pageSize) => setPageInfo({ pageSize, current: 1 }),
    // ... 其他配置
  }}
/>
`

- 当然你也可以使用pagination的onChange事件来修改pageSize，因为源码里边好像是两个事件都会触发，不管你是点击分页的哪个按钮。

- 测试：不采用上述方法而通过actionRef.current.setPageInfo修改pageSize，并不能触发显示条数的改变，所以这个方法不ok。因为此时我pagination的pageSize属性是固定值5，重新渲染还是5条数据啊.......通过ProTable的onChange属性可以看到页面确实重新渲染了。

- 如果删除了一条数据想重新渲染table，需通过actionRef.current.reload方法，触发ProTable的重新渲染。
