### ISSUE TITLE
🐛[BUG] layout 内容区域超出屏幕区域

### ISSUE THREAD

**Issue by wangchangkang** [ant-design/pro-components#5841]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/32864125/188051407-7b80ddb2-5060-4445-afa3-c71a37520b37.png)

### 🏞 期望结果
![image](https://user-images.githubusercontent.com/32864125/188051546-9f3fa700-c280-4eae-bd1e-8ed0b454c4a0.png)

### © 版本信息

 "@ant-design/pro-components": "^2.3.2",

**Comment by ByYogi** [comment]
这种只能等修复了吧
