### ISSUE TITLE
🐛[BUG] 使用ProFormSelect时，如果options项中有{ value: 'xx' }，并且和跟 fieldNames 搭配使用会触发label变value的问题

### ISSUE THREAD

**Issue by WaterHong** [ant-design/pro-components#5844]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

使用ProFormSelect时，如果options项中有{ value: 'xx' }，并且和跟 fieldNames 搭配使用会触发label变value的问题

### 📷 复现步骤
如图所示：
![image](https://user-images.githubusercontent.com/7614653/188101086-612113e2-a2e8-4791-a51a-6f8058e7f0cc.png) 

会出现：
![image](https://user-images.githubusercontent.com/7614653/188100620-8c94dd9b-bec1-4bad-aeb6-74ca92f5251d.png)

### 🏞 期望结果

下拉框的值正常显示 
![image](https://user-images.githubusercontent.com/7614653/188100761-6af5094f-35a6-45d5-9354-4df2f0b5ea8f.png)

### 💻 复现代码
https://codesandbox.io/s/schema-biao-dan-forked-o83qer?file=/App.tsx

### © 版本信息

- ProComponents 版本: 2.3.2
- umi 版本
- 浏览器环境：Chrome 104.0.5112.101
- 开发环境 [e.g. mac OS]

**Comment by kiner-tang** [comment]
为什么要这样用呢？传入的数据保证包含`label`和`label`属性不就可以么？具体应用场景是什么？

**Comment by WaterHong** [comment]
> 为什么要这样用呢？传入的数据保证包含`label`和`label`属性不就可以么？具体应用场景是什么？

这个使用方法还是很常见的吧，后端有个已有的接口，接口里的数据需要放在下拉选项中，数据格式是
```json
[
    {
        'id':1,
        'value': '苹果'
    },
    {
        'id':2,
        'value': '梨'
    }
]
```
自然就会想到用 fieldNames 转换

**Comment by chenshuai2144** [comment]
你这个用法简直就是在挑战组件的健壮性。我建议你最好用 option.map 转化一下
