### ISSUE TITLE
🐛[BUG] ProTable actionRef 的 reload 丢失了 promise

### ISSUE THREAD

**Issue by conorzhong** [ant-design/pro-components#5845]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProTable actionRef 的 reload 丢失了 promise

### 📷 复现步骤

1. request 中 throw
2. try 一个 reload
3. catch 中无法捕获

### 🏞 期望结果

catch 中捕获

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by conorzhong** [comment]
<img width="381" alt="image" src="https://user-images.githubusercontent.com/39456642/188110752-583675cb-e03a-4ca7-8179-e6e7d6e304b5.png">

这里我加上了还是没有用，用 ahooks 的 useDebounceFn 复现了，应该是 useDebounceFn 的 bug
https://codesandbox.io/s/usedebouncefn-async-report-wurwux?file=/App.tsx

**Comment by chenshuai2144** [comment]
修复了，感谢
