### ISSUE TITLE
🧐[问题] 缺少 Header Token 的示例 和文档

### ISSUE THREAD

**Issue by hyzx86** [ant-design/pro-components#5847]
https://procomponents.ant.design/components/layout#token
写了各种属性，但是怎么使用呢。。。
能通过  ` ...initialState?.settings,` 注入吗？

![image](https://user-images.githubusercontent.com/15613121/188202258-b978387c-128a-4c34-85d0-117577b9a5ec.png)

**Comment by hyzx86** [comment]
上面那个网站搜索框些东西白屏了。。

**Comment by kiner-tang** [comment]
> 上面那个网站搜索框些东西白屏了。。

因为多语言文档写在了同一个文档导致的，已经在这次PR中修复了 #5855 ，官网搜索功能等重新发版后会恢复

**Comment by hyzx86** [comment]
测试了一下。。这东西貌似只有在新版本中有用，但是升级Layout 会报一个 PageLoading 找不到的错误😢

**Comment by drizzlesconsin** [comment]
> 测试了一下。。这东西貌似只有在新版本中有用，但是升级Layout 会报一个 PageLoading 找不到的错误😢

新版本移除了导出，新建个 `src/loading.tsx`，复制：

https://github.com/ant-design/pro-components/blob/master/packages/layout/src/components/PageLoading/index.tsx

**Comment by hyzx86** [comment]
@drizzlesconsin  好的，谢谢，看来升级的话 最好是 搞一个完整模板再2把旧代码贴进来，不然很多细节要调整
