### ISSUE TITLE
ProForm 在提交后，如何将 所有输入内容都清空🧐[问题]

### ISSUE THREAD

**Issue by wangwpf** [ant-design/pro-components#585]
Proform， 目前只能点击重置来清空， 但是有提交后也需要能手动来清空所有输入内容，但不知道如何操作

**Comment by chenshuai2144** [comment]
formRef | 可以获取到查询表单的 form 实例，用于一些灵活的配置 | React.MutableRefObject<ActionType> \| ((actionRef: ActionType) => void) | -
-- | -- | -- | --


用这个api

**Comment by 1024wxx** [comment]
formRef.current?.resetFields()
将这个方法放在ProForm 提交后的操作里就可以将所有输入内容都清空
