### ISSUE TITLE
🐛[BUG] StatisticCard 报 Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by scrapstation** [ant-design/pro-components#5853]
![image](https://user-images.githubusercontent.com/56467036/188278608-82de991f-f600-4de7-a0ab-656d238c8ff3.png)
![image](https://user-images.githubusercontent.com/56467036/188278620-5f207463-463f-4331-82ec-4e5104298815.png)

**Comment by WillWuWeijie** [comment]
+1

**Comment by chenshuai2144** [comment]
修复了，可以更新版本了
