### ISSUE TITLE
🐛[BUG] ProTable@3.0.3  dateFormatter 配置在处理 dateRange 时不生效

### ISSUE THREAD

**Issue by Aliveing** [ant-design/pro-components#5858]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProTable  dateFormatter 配置在处理 dateRange 时不生效，点击查询会返回两个 moment 对象，不论 dateFormatter 是 `string | number`

### 📷 复现步骤
 点击复现代码链接，选择时间范围，点击查询，查看 console 中的 `params.createdAt` 输出为两个 moment 对象，而非 string[]

### 🏞 期望结果
1. 与更新前版本一样，默认返回 string[]，即：['2022-01-01', '2022-01-05']
2. dateFormatter 配置生效

### 💻 复现代码
[复现代码](https://codesandbox.io/s/ri-qi-ge-shi-hua-forked-80ynlx?file=/App.tsx)

### © 版本信息

- ProComponents 版本: 2.3.4
- @ant-design/pro-table 版本: 3.0.3
- umi 版本: 4.0.17
- 浏览器环境: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
- 开发环境 macOS

### 🚑 其他信息
![CleanShot 2022-09-05 at 16 08 10](https://user-images.githubusercontent.com/11768879/188403954-12340ddc-8a41-4e1c-a8b8-4ae87e6f1556.png)

**Comment by chenshuai2144** [comment]
已经修复了，更新版本
