### ISSUE TITLE
request 接口返回的data数据大于10条的时候，render里面的action?.pageInfo?.current有问题

### ISSUE THREAD

**Issue by csy1994** [ant-design/pro-components#5859]
request 接口返回的data数据大于10条，点击不同的页码时不刷新数据，同时columns的render拿到的action?.pageInfo?.current时不准确的，每次得到的值是上一次点击页码的值

**Comment by chenshuai2144** [comment]
pagesize 要和 data 想同或者小于。
另外的 action?.pageInfo?.current 不保证时效的.要保证时效用useEffect 监听一下

**Comment by csy1994** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
