### ISSUE TITLE
🐛[BUG] antd升级版本为4.23.0时 使用ConfigProvider设置语言ProTable没有效果还是英文

### ISSUE THREAD

**Issue by tetap** [ant-design/pro-components#5860]
![image](https://user-images.githubusercontent.com/57606461/188417375-3d99b08e-23c2-42ac-86c6-916eaccdee0b.png)

**Comment by chenshuai2144** [comment]
要和procomponent用的antd 版本相同，这种情况一般是引入了两种不同的antd 版本。

另外如果是日期还要设置 dayjs 和 moment 的语言也设置一下
