### ISSUE TITLE
🐛[BUG] Warning: [antd: Modal] `visible` will be removed in next major version, please use `open` instead. 

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#5862]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/30397655/188441049-5e2dee24-c00d-4c40-b35e-fd8fb1787600.png">

**Comment by DebugIllus1on** [comment]
`<ModalForm<CreateFormField>
      title="创建用户"
      **modalProps={{
        open: visible,
        onCancel: () => {
          setVisibleCreateModal(false);
        },
      }}**
      autoFocusFirstInput
      form={form}
    >`

**Comment by DebugIllus1on** [comment]
![image](https://user-images.githubusercontent.com/53471930/189104889-91272091-2d46-4fbe-8f28-7931cba3d9ca.png)

**Comment by GuoDapeng** [comment]
目前遇到了两个警告
```
Warning: [antd: Drawer] `visible` is deprecated which will be removed in next major version, please use `open` instead.
Warning: [antd: Modal] `visible` will be removed in next major version, please use `open` instead.
```

本来一个多月之前开始的项目没这个个警告的。昨天新开了一个项目，出了这个警告。

我就在之前的项目 `yarn upgrade` 了一下。舒服了，都报警告就说明不是我错了……哈哈

**Comment by leshalv** [comment]
> 目前遇到了两个警告
> 
> ```
> Warning: [antd: Drawer] `visible` is deprecated which will be removed in next major version, please use `open` instead.
> Warning: [antd: Modal] `visible` will be removed in next major version, please use `open` instead.
> ```
> 
> 本来一个多月之前开始的项目没这个警告的。昨天新开了一个项目，出了这个警告。
> 
> 我就在之前的项目 `yarn upgrade` 了一下。舒服了，都报警告就说明不是我错了……哈哈

后来代码做了兼容，建议用 open。

**Comment by GuoDapeng** [comment]
> > 目前遇到了两个警告
> > ```
> > Warning: [antd: Drawer] `visible` is deprecated which will be removed in next major version, please use `open` instead.
> > Warning: [antd: Modal] `visible` will be removed in next major version, please use `open` instead.
> > ```
> > 本来一个多月之前开始的项目没这个警告的。昨天新开了一个项目，出了这个警告。
> > 我就在之前的项目 `yarn upgrade` 了一下。舒服了，都报警告就说明不是我错了……哈哈
> 
> 后来代码做了兼容，建议用 open。

知道这个警告在说什么。但是 在 Welcome.tsx 页面也会输出警告，我就不想管它了，对框架了解不深，找不到该那里合适，就这么放着吧，也不影响啥。
