### ISSUE TITLE
protable筛选栏的"提交"和"重置"按钮可以另起一行吗    🧐[问题]

### ISSUE THREAD

**Issue by bestdqf** [ant-design/pro-components#5867]
### 🧐 问题描述
protable筛选栏的"提交"和"重置"按钮可以另起一行吗  

目前想到的解决方案是 : 把自带的按钮隐藏 重新包装一层 , 但是这毕竟不是自带的,用起来不那么舒服 ,有没有api可以直接实现一下

### 💻 示例代码

![image](https://user-images.githubusercontent.com/4651759/188531470-37c50028-5f54-4006-976e-7d6fdf1b358d.png)

**Comment by chenshuai2144** [comment]
官方不会支持这种模式的，你继续自己实现吧，这种操作习惯统一最重要
