### ISSUE TITLE
🐛[BUG] ProFormCheckbox.Group layout 应该是反了?

### ISSUE THREAD

**Issue by drizzlesconsin** [ant-design/pro-components#5869]
### 🐛 bug 描述

是新版设计如此，还是bug
应该不给默认值，`&-horizontal` 改成 `&-vertical`？

<img width="479" alt="image" src="https://user-images.githubusercontent.com/69514654/188537909-4985fc9b-e44c-41bf-b82d-188a8047c1eb.png">

### 📷 复现步骤

https://github.com/ant-design/pro-components/blob/master/packages/field/src/components/Checkbox/index.tsx#L33-L37

### © 版本信息

- ProComponents 版本: [e.g. 2.3.5]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by leshalv** [comment]
https://github.com/ant-design/pro-components/issues/5838
