### ISSUE TITLE
如何获取ant desgin menu 组件dom信息，不知道是不是全网最难搞的问题

### ISSUE THREAD

**Issue by yangyangdg** [ant-design/pro-components#5874]
1、自定义expandIcon:
![image](https://user-images.githubusercontent.com/49295228/188574796-2e7eef15-4cab-42f5-9058-2c9c4c76504a.png)
2、运行效果：
![image](https://user-images.githubusercontent.com/49295228/188575094-3bfdc27e-aff5-4757-8585-32d855b81316.png)
3、期望点击【功能1】可以获取到所在的菜单项【Navigation Three】相关dom信息，比如name，key等等，怎么做尼，搞了两天也没有搞定，大神出出手吧，救救小弟
4、代码仓库：https://github.com/yangyangdg/ant-design-demo1-menu

**Comment by PlutoCA** [comment]
设置同一个key 关联一下咯，再去menu 里面find一下

**Comment by yangyangdg** [comment]
> 
find怎么操作的，可以指导一下吗，大神

**Comment by drizzlesconsin** [comment]
expandIcon | 自定义展开图标 | ReactNode \| (props: SubMenuProps & { isSubMenu: boolean }) => ReactNode | - | 4.9.0
-- | -- | -- | -- | --


用函数，看看 props 里面有没有

**Comment by yangyangdg** [comment]
> expandIcon	自定义展开图标	ReactNode | (props: SubMenuProps & { isSubMenu: boolean }) => ReactNode	-	4.9.0
> 用函数，看看 props 里面有没有

一语中的，谢谢！！
