### ISSUE TITLE
🧐[问题] 如何获取由breakpoint产生的collapsed 折叠状态值

### ISSUE THREAD

**Issue by zhanchengkun** [ant-design/pro-components#5876]
### 🧐 问题描述

antd Layout有 onBreakpoint ， ProLayout 没有了；

初始化时onCollapse也不执行，只有手动点击折叠按钮才触发。

问:menuItemRender 中 如何获取 collapsed 折叠状态值

**Comment by drizzlesconsin** [comment]
接管 collapsed 再传给 menuItemRender

参考: https://procomponents.ant.design/components/layout/#layout-customize-collapsed
