### ISSUE TITLE
🐛[BUG] ModalForm使用destroyOnClose在onFinish返回false也会清空表单！

### ISSUE THREAD

**Issue by yirandidi** [ant-design/pro-components#5881]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by yirandidi** [comment]
@sorrycc @andriijas @craxyz @dlcmh

**Comment by wangmeijian** [comment]
文档是这么说的：
提交数据时触发，如果返回一个 true。会关掉抽屉,如果配置了 destroyOnClose 还会重置表单
意思是只要配置了destroyOnClose就会重置

**Comment by yirandidi** [comment]
> 文档是这么说的： 提交数据时触发，如果返回一个 true。会关掉抽屉,如果配置了 destroyOnClose 还会重置表单 意思是只要配置了destroyOnClose就会重置

问题就是返回的是false表单也被重置。这个问题已经在上面的合并解决了。
