### ISSUE TITLE
👑 [需求] SchemaForm表单最使用了与 table 的相同的表单定义，对于width无法区分？

### ISSUE THREAD

**Issue by seap** [ant-design/pro-components#5882]
### 🔩 所属模块或组件
Schema Form 使用的schema属性中如何区分width属性，是form和table应该都有各自的width
` const schema = [
  {
    title: 'ID',
    dataIndex: 'id',
    width: 200,
    columnWidth: 180,
    hideInForm: true,
  }
]
`
### 🥰 需求描述
增加columnWidth

**Comment by chenshuai2144** [comment]
不要控制宽度就好了，没什么意义。反而想太多

**Comment by lanbin1017** [comment]
如果列特别多的时候，设置行允许换行，不设置宽度，就特别挤啊，我也觉得这里form和table的宽度只能用同一个非常难受
