### ISSUE TITLE
🐛[BUG] ProTable 在微信浏览器样式异常

### ISSUE THREAD

**Issue by lwQin** [ant-design/pro-components#5886]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProTable 在微信浏览器样式异常

### 📷 复现步骤
[官网 demo](https://procomponents.ant.design/components/table?current=1&pageSize=5)

### © 版本信息

- ProComponents 版本: ProTable 3.0.4
- umi 版本 3.5.33
- 浏览器环境 windows 微信浏览器
- 开发环境  mac OS Chrome 105

### 🚑 其他信息

![WechatIMG493](https://user-images.githubusercontent.com/11586662/188827236-585b3602-e05b-44c6-89c1-814a878ef816.png)
![WechatIMG492](https://user-images.githubusercontent.com/11586662/188827447-0991581c-c155-4bbb-84da-7bafae49cc97.png)

**Comment by lwQin** [comment]
`padding-block` 和 `padding-inline` 只支持 chrome 87 以上

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


对于 `padding-block` 和 `padding-inline` ，这是 CSS Box Alignment Module Level 3 中的一部分，它们在最新版本的 Chrome 浏览器中得到了支持，但在其他浏览器中的支持情况可能会有所不同。

如果你使用的浏览器版本较早，那么这些属性可能不会被支持，因此你可以考虑使用传统的 `padding-top`、`padding-bottom`、`padding-left` 和 `padding-right` 属性来达到同样的效果。

如果你需要使用 `padding-block` 和 `padding-inline`，并且希望在不支持这些属性的浏览器上实现类似的效果，可以使用 Flexbox 应用单独的样式。你可以查看参考文档 [Box Alignment](https://www.w3.org/TR/css-flexbox-1/#box-alignment) 里面使用 Flexbox 的例子。

对于其他的浏览器兼容性问题，你可以参考 [Can I Use](https://caniuse.com/) 查看浏览器对 CSS 属性和 JavaScript 方法的支持情况。

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/docs/faq#chrome88-以下浏览器兼容问题

看这里
