### ISSUE TITLE
👑 [需求]轻量型查询支持回车确认查询

### ISSUE THREAD

**Issue by nyl1223** [ant-design/pro-components#5888]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述

轻量型查询支持回车确认查询

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


对于这个需求，建议对轻量型查询组件的输入框添加一个按键监听器，当用户按下回车键时，执行查询操作。可以通过在 `<Input.Search>` 组件中添加 `onPressEnter` 属性来监听回车键事件。

示例代码如下：

```jsx
import { Input } from 'antd';

function handleSearch(value) {
  console.log('执行查询操作', value);
}

<Input.Search
  placeholder="请输入搜索内容"
  onSearch={handleSearch}
  onPressEnter={handleSearch}
/>
```

在这个示例中，我们向 `Input.Search` 组件中添加了 `onPressEnter` 属性，并将其指向 `handleSearch` 函数。当用户在输入框中按下回车键时，`handleSearch` 函数会被执行，从而实现了轻量型查询组件支持回车确认查询的功能。

更多关于 `Input.Search` 组件的使用相关信息可以参考 Ant Design 官方文档：https://ant.design/components/input-cn/#Input.Search
