### ISSUE TITLE
🧐[问题] 菜单开合按钮样式问题

### ISSUE THREAD

**Issue by kuake** [ant-design/pro-components#5891]
之前的pro-layout里菜单开合按钮collapsedButton是这个样的
<img width="41" alt="oldbtn" src="https://user-images.githubusercontent.com/815653/189012459-9d6c3522-460b-4e07-9d34-d02f8c133a2e.png">
新版pro-components里如何使用旧的样式？

**Comment by Fiuck** [comment]
将collapsedButtonRender设置为false并且通过headerContentRender来自定义图标
