### ISSUE TITLE
🧐[问题]如何在request外部获取当前proTable的filter参数?

### ISSUE THREAD

**Issue by jianmaikj** [ant-design/pro-components#5896]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

如何在request外部获取当前proTable的filter参数?
有些情况需要手动请求，需要用获取当前的筛选参数

**Comment by wangmeijian** [comment]
protable 有个 formRef属性，参考 https://procomponents.ant.design/components/table#%E9%80%9A%E8%BF%87-formref-%E6%9D%A5%E6%93%8D%E4%BD%9C%E6%9F%A5%E8%AF%A2%E8%A1%A8%E5%8D%95
通过formRef.current.getFieldsValue拿到参数

**Comment by chenshuai2144** [comment]
最好的办法是用antd的用法， 通过state自己去存
