### ISSUE TITLE
🧐[问题]无法通过 yarn add @ant-design/pro-layout  下载最新的 pro-layout npm 包

### ISSUE THREAD

**Issue by Gzbox** [ant-design/pro-components#59]
### 🧐 问题描述
看到 pro-layout 已发布最新的 6.3.0 版本  但是 无法通过 yarn add @ant-design/pro-layout  下载最新的 pro-layout npm 包
只能安装到6.2.5
![image](https://user-images.githubusercontent.com/21010051/88876234-695d5980-d255-11ea-8655-baed5d43b8ea.png)

**Comment by chenshuai2144** [comment]
npm 已经有了，可以用 npm 源下载一下
https://www.npmjs.com/package/@ant-design/pro-layout?activeTab=versions


估计是使用了淘宝源吧。我 sync 了一下
