### ISSUE TITLE
👑 [需求]ProTable 列值的枚举valueEnum的key值能否支持多类型，比如布尔

### ISSUE THREAD

**Issue by giamchen** [ant-design/pro-components#590]
### 🥰 需求描述

ProTable 列值的枚举valueEnum的key值能否支持多类型，比如数字；
目前我设置 key为数字 0 1会自动给我转为 false true ,但是当用作搜索条件的参数又变成字符串，导致取值很不方便

### 🚑 其他信息

![微信图片_20200925142013](https://user-images.githubusercontent.com/33769348/94233302-40e29a80-ff3a-11ea-9ea2-e4ddea492e85.png)

**Comment by chenshuai2144** [comment]
使用Map ， object 是不支持你的这种行为的
