### ISSUE TITLE
🧐[问题]ProTable中的request和useRequest对返回数据的默认结构为啥不设计成一样？

### ISSUE THREAD

**Issue by seap** [ant-design/pro-components#5901]
### 🧐 问题描述
ProTable的request默认返回结构：
{ success, data, total }

useRequest的默认返回结构：
{ success, data: { total, list }}

### 💻 示例代码

同一套，为什么要有两个不一样的默认结构？

**Comment by chenshuai2144** [comment]
不是同一套，你手动转化下吧。

我们不推荐protable+ useRequest，这样会导致数据流重复
