### ISSUE TITLE
🐛[BUG] QueryFilter defaultColsNumber 设置3行，只展示一行

### ISSUE THREAD

**Issue by oneMoreTime1357** [ant-design/pro-components#5903]
环境
- @ant-design/pro-form@1.71.2
- antd@4.23.0

QueryFilter defaultColsNumber 设置收起时默认展示3行，实际收起时只展示一行的高度。
升级版本

## codeSandbox 链接
https://codesandbox.io/s/cha-xun-shai-xuan-forked-7g081i?file=/App.tsx

## 问题截图
![截屏2022-09-09 下午2 49 14](https://user-images.githubusercontent.com/14797594/189288859-4bb39307-64b2-438e-a630-0d176eab4296.png)

**Comment by liangchaofei** [comment]
defaultColsNumber 是表单控件的数量，不是行数

**Comment by oneMoreTime1357** [comment]
> defaultColsNumber 是表单控件的数量，不是行数

第一行表单控件设置`colSize={4}` 占了一行的高度，目的是想收起时展示两行的表单控件，不管我defaultColsNumber设置是几，最终都只展示第一行的表单控件

**Comment by oneMoreTime1357** [comment]
@liangchaofei 这个问题在版本几会修复？

**Comment by DJGDragon** [comment]
同样的问题（我是想默认查询条件第一行用的colSize={4}，但是又想默认展示三个查询条件）。。  我提这个问题提了几遍了 还是没有人修复  也不知道能不能修复  因为这个bug  我根本无法升级新版本的pro-form  以前老版本就是好用的

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


@SonGongTang 这个问题是因为`defaultColsNumber`会被收起时展示的表单控件占用的高度所影响，而不是收起时展示的行数。具体来说，如果你希望收起时展示3行表单控件，你需要调整第一行表单控件的`colSize`大小，使其所占高度不超过1/3。可以尝试调整为`colSize={2}`，这样默认展示三行时，表单控件会排列成两列，每列展示两个控件。这样就可以达到你想要的效果了。

关于版本问题，我们正在尽力修复这个问题，可以关注我们的 GitHub Issue 进行跟踪。同时，你也可以尝试使用其他方法实现你的需求，比如使用 React 状态管理工具等。
