### ISSUE TITLE
🐛[BUG]ProTable中加载树型结构数据后，点击展开收缩图标，整个树一起展开或收缩，而不是单独的节点展开或收缩

### ISSUE THREAD

**Issue by 18310880751** [ant-design/pro-components#5904]
ProTable中加载树型结构数据后，点击展开收缩图标，整个树一起展开或收缩，而不是单独的节点展开或收缩

### 🏞 期望结果
点击展开图标应该只展开当前节点的叶子

### © 版本信息

- ProComponents 版本:1.1.1
- umi 版本    3.5
- 浏览器环境 chrome104
- 开发环境 [e.g. mac OS] window11

**Comment by chenshuai2144** [comment]
你的rowKey重复了，请保证是唯一的
