### ISSUE TITLE
🧐[问题] ProTable的搜索栏可以设置input属性吗？

### ISSUE THREAD

**Issue by mac-boss** [ant-design/pro-components#5907]
### 🧐 问题描述

ProTable的搜索栏可以设置input属性吗？例如字符限制，正则，只能输入数字等功能。。。

### 💻 示例代码

columns里设置maxLength

**Comment by chenshuai2144** [comment]
fieldProps 里面可以配置输入框的属性。formItemProps 里面能配置 form 的属性
