### ISSUE TITLE
🐛[BUG]ProCard切分卡片模式会出现 缺少key错误

### ISSUE THREAD

**Issue by WuJiY** [ant-design/pro-components#5916]
ProCard 卡片切分 时会出现如下错误
<img width="838" alt="截屏2022-09-12 14 21 46" src="https://user-images.githubusercontent.com/183884/189586583-fd5038db-52a4-4e94-948d-215fe89fe539.png">

**Comment by GuanRunhua** [comment]
我也是，用StaticCard的时候也会出现同样的错误，即使加上了key。
![image](https://user-images.githubusercontent.com/5419683/190871127-a5345d18-915a-4a98-8579-8bf3f4f06623.png)
![image](https://user-images.githubusercontent.com/5419683/190871139-2e2d44b8-712d-46ae-937c-5e1f364c53dd.png)

**Comment by WuJiY** [comment]
2.3.12 已解决
