### ISSUE TITLE
🐛[BUG]Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by netcore-jroger** [ant-design/pro-components#5919]
### 🐛 bug 描述

Cannot read properties of undefined (reading '0')

### 📷 复现步骤

1. 使用 vite 启动项目代码
2. 查看控制台报错日志

### 🏞 期望结果

正常渲染 ProLayout

### 💻 复现代码

参见：https://stackblitz.com/edit/vitejs-vite-tmydrg?file=package.json,src%2FApp.tsx

### © 版本信息

- ProComponents 版本: 2.3.7
- "@ant-design/pro-layout": "^7.0.5",
- "react": "^18.2.0",
- "react-dom": "^18.2.0",
- umi 版本: 未使用 umi
- 浏览器环境 Microsoft Edge 版本 105.0.1343.34 (正式版本) beta (64 位)
- 开发环境 Windows 11

### 🚑 其他信息
 构建工具：vite v3.1.0

**Comment by lzm0x219** [comment]
+1

**Comment by lzm0x219** [comment]
> ### 🐛 bug 描述
> Cannot read properties of undefined (reading '0')
> 
> ### 📷 复现步骤
> 1. 使用 vite 启动项目代码
> 2. 查看控制台报错日志
> 
> ### 🏞 期望结果
> 正常渲染 ProLayout
> 
> ### 💻 复现代码
> 参见：https://stackblitz.com/edit/vitejs-vite-tmydrg?file=package.json,src%2FApp.tsx
> 
> ### © 版本信息
> * ProComponents 版本: 2.3.7
> * "@ant-design/pro-layout": "^7.0.5",
> * "react": "^18.2.0",
> * "react-dom": "^18.2.0",
> * umi 版本: 未使用 umi
> * 浏览器环境 Microsoft Edge 版本 105.0.1343.34 (正式版本) beta (64 位)
> * 开发环境 Windows 11
> 
> ### 🚑 其他信息
> 构建工具：vite v3.1.0

```
"@ant-design/pro-components": "2.3.7",
"@ant-design/pro-layout": "6.38.22",
```
ProLayout组件先用`@ant-design/pro-layout`@6.x先顶着

**Comment by lzm0x219** [comment]
```
"@ant-design/pro-components": "2.3.7",
"@ant-design/pro-layout": "6.38.22",
```
ProLayout组件先用`@ant-design/pro-layout@6.x`先顶着，其他组件用components包

**Comment by netcore-jroger** [comment]
是的 `@ant-design/pro-layout` 6.x 的版本是没有问题的。

**Comment by lzm0x219** [comment]
> 是的 `@ant-design/pro-layout` 6.x 的版本是没有问题的。

等作者fix了😼

**Comment by hylerrix** [comment]
Mark, 就 CRA 新项目安装了下 pro-layout 就有这个问题，期待早点 Fix, 本来还想在正式环境升级 v7 立马用上呢！

**Comment by netcore-jroger** [comment]
![image](https://user-images.githubusercontent.com/3223890/190093491-1a7f91b3-86fb-42f7-8732-ee6ce4dae036.png)
第二次断点进入的时候为 `undefined`

**Comment by sushi-su** [comment]
去掉 react 18 的严格模式

**Comment by netcore-jroger** [comment]
> 去掉 react 18 的严格模式

去掉严格模式可以了，请问能讲一下原因吗？

**Comment by sushi-su** [comment]
等 swr 更新 v2 后可解  https://github.com/vercel/swr/issues/1904

**Comment by netcore-jroger** [comment]
> 等 swr 更新 v2 后可解 [vercel/swr#1904](https://github.com/vercel/swr/issues/1904)

谢谢

**Comment by arifszn** [comment]
Same issue with vite `3.1.7`.

**Comment by franka107** [comment]
it worked for me:

package.json
`  "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-layout": "^7.1.8",
    "@types/antd": "^1.0.0",
    "antd": "^4.23.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "swr": "2.0.0-rc.0"
  },`

vite.config.ts
`import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  css: {
    preprocessorOptions: {
      less: {
        javascriptEnabled: true,
      },
    },
  },
  resolve: {
    alias: [
      {
        find: /^~/,
        replacement: "",
      },
      {
        find: "@",
        replacement: path.resolve(__dirname, "./src"),
      },
    ],
  },
});
`

**Comment by dingyanhe** [comment]
+1

**Comment by arifszn** [comment]
> it worked for me:
> 
> package.json
> 
> ```
>     "@ant-design/icons": "^4.7.0",
>     "@ant-design/pro-layout": "^7.1.8",
>     "@types/antd": "^1.0.0",
>     "antd": "^4.23.5",
>     "react": "^18.2.0",
>     "react-dom": "^18.2.0",
>     "swr": "2.0.0-rc.0"
>   },
> ```
> 
> vite.config.ts
> 
> ```
> import { defineConfig } from "vite";
> import react from "@vitejs/plugin-react";
> import path from "path";
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [react()],
>   css: {
>     preprocessorOptions: {
>       less: {
>         javascriptEnabled: true,
>       },
>     },
>   },
>   resolve: {
>     alias: [
>       {
>         find: /^~/,
>         replacement: "",
>       },
>       {
>         find: "@",
>         replacement: path.resolve(__dirname, "./src"),
>       },
>     ],
>   },
> });
> ```

Have you turned off `react strict mode`?

**Comment by xezzon** [comment]
版本 `2.3.28` ，问题依然存在。

**Comment by samotoo** [comment]
pro-layout依赖的还是swr 1，目前看来只有先override这个版本，或者去掉`StrictMode`绕一下了。
