### ISSUE TITLE
🐛[BUG] pro-table columns 的 width 和 ellipsis 同时设置时，width 不生效

### ISSUE THREAD

**Issue by forzalianjunting** [ant-design/pro-components#592]
### 🐛 bug 描述

单独设置 width 时是生效的

### © 版本信息

- pro-table 2.8.1

**Comment by chenshuai2144** [comment]
使用 2.8.2 ，修复了这个问题

**Comment by forzalianjunting** [comment]
> 使用 2.8.2 ，修复了这个问题

2.8.2还没发布？

**Comment by iambool** [comment]
> 使用 2.8.2 ，修复了这个问题

2.8.2发布了吗？

**Comment by chenshuai2144** [comment]
你们的问题应该和 table layout 有关，配置 

` tableLayout="fixed"` 就能解决你们的问题，但是 table 的单元格不会自动拉伸宽度了

**Comment by forzalianjunting** [comment]
> 你们的问题应该和 table layout 有关，配置
> 
> ` tableLayout="fixed"` 就能解决你们的问题，但是 table 的单元格不会自动拉伸宽度了,或者给 每个 td 设置宽度，然后加起来等于 100%

不可兼得吗？之前都是支持的

**Comment by sgknight2020** [comment]
根本就没有2.8.2这个版本，说话能负责一点不？？？

**Comment by chenshuai2144** [comment]
原来是强制设置了宽度 导致了tooltip对不准 
也是个问题

**Comment by iambool** [comment]
我设置了表格的scroll属性后，width 和 ellipsis就可以同时使用了（还固定了某几个列）

**Comment by iambool** [comment]
设置了百分比宽度后（总和100%），操作表格右上角工具栏中的调整列前后顺序，调整顺序后，页面列宽度失效了，直接超出可视范围
