### ISSUE TITLE
proTable 组件里面的toolbar中的search自带的Input输入框支持配置placeholder吗

### ISSUE THREAD

**Issue by duzuimoye** [ant-design/pro-components#5920]
## 问题描述

proTable 组件里面的toolbar中的search自带的Input输入框支持配置**placeholder**吗？

## 示例代码

        toolbar={{
          actions: [
            <Button
              key="button"
              icon={<PlusOutlined />}
              type="primary"
              onClick={() => {
                setCurrentType('add');
                setAddModal(true);
              }}
            >
              新增
            </Button>,
          ],
          search: {
            formProp: {
              component: 'Input', // 使用的组件
              options: {
                // 组件的配置信息
                placeholder: '请输入应用名称',
                clearable: true,
              },
            },
            onSearch: (value) => {
              setSearchParmas({ name: value });
            },
            // formItemOptions: {
            //   // form-item的配置
            //   // prop: 'name1', // 可不写，若有，此处的prop级别高于第一层的prop，用于搜索提交时的字段
            //   // label: '姓名', // 可不写，前面的label一直，配置则按此处的显式在搜索区
            //   rules: [
            //     {
            //       required: true,
            //       message: '姓名必填！',
            //     },
            //   ],
            // },
          },
        }}

**Comment by chenshuai2144** [comment]
<img width="308" alt="image" src="https://user-images.githubusercontent.com/8186664/209545714-2caceb30-a45f-42ad-a865-5b5290f3506e.png">


支持所有的配置。
