### ISSUE TITLE
🐛[BUG]ProTable组件列展示勾选单一的子项没反应

### ISSUE THREAD

**Issue by orage714** [ant-design/pro-components#5921]
### 🐛 bug 描述

ProTable组件columns列里包含children配置，反选勾选子项没反应，反选之后父级的key不存在了

### 📷 复现步骤

import ReactDOM from 'react-dom';
import React from 'react';
import { EllipsisOutlined } from '@ant-design/icons';
import type { ProColumns } from '@alipay/tech-ui';
import { ProTable } from '@alipay/tech-ui';
import { Button } from 'antd';

export type TableListItem = {
  key: number;
  name: string;
  containers: number;
  creator: string;
};
const tableListDataSource: TableListItem[] = [];

const creators = ['付小小', '曲丽丽', '林东东', '陈帅帅', '兼某某'];

for (let i = 0; i < 5; i += 1) {
  tableListDataSource.push({
    key: i,
    name: 'AppName',
    containers: Math.floor(Math.random() * 20),
    creator: creators[Math.floor(Math.random() * creators.length)],
  });
}

const columns: ProColumns<TableListItem>[] = [{
  title: '应用名称',
  dataIndex: 'title',
  children: [
    {
      title: '应用名称',
      dataIndex: 'name',
      render: (_) => <a>{_}</a>,
    },
    {
      title: '容器数量',
      dataIndex: 'containers',
      align: 'right',
      sorter: (a, b) => a.containers - b.containers,
    },
    {
      title: '创建者',
      dataIndex: 'creator',
      valueType: 'select',
      valueEnum: {
        all: { text: '全部' },
        付小小: { text: '付小小' },
        曲丽丽: { text: '曲丽丽' },
        林东东: { text: '林东东' },
        陈帅帅: { text: '陈帅帅' },
        兼某某: { text: '兼某某' },
      },
    },
  ]
},

{
  title: '操作',
  key: 'option',
  width: 120,
  valueType: 'option',
  render: () => [
    <a key="link">链路</a>,
    <a key="warn">报警</a>,
    <a key="more">
      <EllipsisOutlined />
    </a>,
  ],
},
];

const DumiDemo = () => {
  return (
    <ProTable<TableListItem>
      columns={columns}
      request={(params, sorter, filter) => {
        // 表单搜索项会从 params 传入，传递给后端接口。
        console.log(params, sorter, filter);
        return Promise.resolve({
          data: tableListDataSource,
          success: true,
        });
      }}
      cardProps={{ title: '业务定制', bordered: true }}
      headerTitle={
        <Button
          key="primary"
          type="primary"
          onClick={() => {
            alert('add');
          }}
        >
          添加
        </Button>
      }
      rowKey="key"
      search={false}
    />
  );
};
ReactDOM.render(<DumiDemo />, mountNode);

### 🏞 期望结果

反选之后，勾选子项父级key也能被勾选

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/40633486/189818849-37ae68b0-2447-4eb1-b5bc-08426ce93ad9.png)

**Comment by chenshuai2144** [comment]
已经修复了
