### ISSUE TITLE
🐛[BUG] Tabs.TabPane is deprecated

### ISSUE THREAD

**Issue by mashirozx** [ant-design/pro-components#5923]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

antd 4.23.1 弃用了TabPane，但是pro-component 2.3.7 的 ProCard 还在用，于是控制台报错了

<img width="593" alt="image" src="https://user-images.githubusercontent.com/16148054/189848493-42777c0c-e43e-415d-95b8-7dcbd41c5c19.png">

https://github.com/ant-design/pro-components/blob/2088f06a75a91c051c197fabb9072df17799d132/packages/card/src/components/TabPane/index.tsx#L27-L40

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/16148054/189848589-7faa406a-5c14-4cb4-89bb-78f15a63d088.png">

### © 版本信息

- ProComponents 版本: 2.3.7
- antd：4.23.1
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by bigmgreen** [comment]
如何解决的？

**Comment by bigmgreen** [comment]
@mashirozx 如何解决的？
