### ISSUE TITLE
🧐[问题] ProFormList嵌套，无法获取到内部当前行的值

### ISSUE THREAD

**Issue by shanhuaji** [ant-design/pro-components#5927]
<ProForm onFinish={async (e) => console.log(e)}>
      <ProFormText name="name" label="姓名" />
      <ProFormList
        name="users"
        label="用户信息"
        initialValue={[
          {
            name: '1111',
          },
        ]}
        itemRender={({ listDom, action }, { record }) => {
          return (
            <ProCard
              bordered
              extra={action}
              title={record?.name}
              style={{
                marginBlockEnd: 8,
              }}
            >
              {listDom}
            </ProCard>
          );
        }}
      >
        {(_, index, action) => {
          return (
            <>
              <ProFormGroup>
                <ProFormText
                  name="name"
                  label="姓名"
                  fieldProps={{
                    onChange: () => {
                      console.log(action?.getCurrentRowData());  可以获取
                    },
                  }}
                />
                <ProFormText name="nickName" label="昵称" />
              </ProFormGroup>
              <ProFormList
                name="labels"
                label="用户信息"
                initialValue={[
                  {
                    value: '333',
                    label: '333',
                  },
                ]}
                copyIconProps={{
                  tooltipText: '复制此行到末尾',
                }}
                deleteIconProps={{
                  tooltipText: '不需要这行了',
                }}
              >
                {(aa, index1, action1) => {
                  return (
                    <ProFormGroup key="group">
                      <ProFormText
                        name="value"
                        label="值"
                        fieldProps={{
                          onChange: () => {
                            console.log(action1?.getCurrentRowData());  无法获取
                          },
                        }}
                      />
                      <ProFormText name="label" label="显示名称" />
                    </ProFormGroup>
                  );
                }}
              </ProFormList>
            </>
          );
        }}
      </ProFormList>
    </ProForm>

**Comment by chenshuai2144** [comment]
修复了，可以重新安装到最新版本
