### ISSUE TITLE
🐛[BUG] ProCard Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by PlayApple** [ant-design/pro-components#5928]
### 🐛 bug 描述
新建一个pro.antd的模板工程，升级所有依赖为最新。在空白页面中写<ProCard>内嵌套多个<ProCard>，会提示丢失Key

这两种写法都会提示key丢失
`<PageContainer>
     <ProCard key="key1">
        <ProCard key="key2">123123</ProCard>
        <ProCard key="key3">123213</ProCard>
      </ProCard>
    </PageContainer>
`

`<PageContainer>
      <ProCard>
        <ProCard>123123</ProCard>
        <ProCard>123213</ProCard>
      </ProCard>
    </PageContainer>
`
我目前的解决办法是用Space代替父级ProCard.
另外：以前这个写法是没问题的，最近1个月发现的。具体在ProCard哪个版本我没有深入查，可能是新版中ProCard 循环中的pro-card-col-{index}失效了。

### © 版本信息
 @ant-design/pro-components@2.3.7
antd@4.23.1
@umijs/max@4.0.20

![screenshot-20220914-115141](https://user-images.githubusercontent.com/3360969/190055584-84fe3daf-daa1-4d00-a0c4-69c25a737215.png)

**Comment by amin168** [comment]
我也是这个情况，更新到最新版也一样

**Comment by zzcbnz** [comment]
一样的情况，嵌套ProCard就会出现

**Comment by chenshuai2144** [comment]
修复了，更新版本即可
