### ISSUE TITLE
🧐[问题] umi/max ，pro-component都是最新版本，提示未导入（pnpm安装）？

### ISSUE THREAD

**Issue by WuJiY** [ant-design/pro-components#5939]
```
"@ant-design/pro-components": "2.3.8",
"@umijs/max": "^4.0.21",
```

```
pnpm 安装
```
![1663290438607](https://user-images.githubusercontent.com/183884/190534927-462e2329-ce36-4ce8-8068-03836d8a8f46.png)
![image](https://user-images.githubusercontent.com/183884/190534901-3b6617ea-1454-46f0-bada-8f404cb2a41f.png)
![image](https://user-images.githubusercontent.com/183884/190534912-4c2dadef-6e86-4ddd-9c97-cf4ef88ebf71.png)

**Comment by JaylanChen** [comment]
+1

**Comment by ywzou** [comment]
+1

**Comment by zwd609258057** [comment]
提示未导出 影响组件使用吗

**Comment by JaylanChen** [comment]
> 提示未导出 影响组件使用吗

如果是使用ts开发，那么：1.打开项目，文件报错；2. 提交时代码检查也过不了（tsc）

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/blob/0bf30baa16ad05a71004dd73e4cbfa31caf83f2a/packages/components/package.json#L31-L40


看起来没啥问题，能帮忙排查下妈

**Comment by ypli0629** [comment]
在 .npmrc 添加
```
public-hoist-pattern[]=*@ant-design/*
```

**Comment by he1237596** [comment]
tsconfig.json的 添加"compilerOptions"的paths添加 "antd": ["/node_modules/@ant-design/pro-components/es/index.d.ts"],
