### ISSUE TITLE
🧐[问题] ProTable 弹出创建表单的栅格布局怎么设置

### ISSUE THREAD

**Issue by winyh** [ant-design/pro-components#594]
### 🧐 有没有小伙伴知道，ProTable 弹出创建表单，想实现栅格布局在哪里配置啊？

目前弹出的表单默认是 一行一个表单，能支持一行多个吗？

<img width="1170" alt="屏幕快照 2020-09-25 下午9 28 50" src="https://user-images.githubusercontent.com/20592185/94273168-9fc60500-ff76-11ea-8dd2-21d64307cc92.png">

**Comment by chenshuai2144** [comment]
@winyh  现在还不支持的，api 没有想搞，这个东西要配置还是比较难的

**Comment by winyh** [comment]
感谢回复，这个配置应该用到的还比较多，比较繁杂的数据录入一行只放置一个就撑的很高了。用Vue 我实现过类似的ProTable，也是共用comlnum 数据源。我自己研究下，再次感谢

**Comment by winyh** [comment]
> @winyh 现在还不支持的，api 没有想搞，这个东西要配置还是比较难的

感谢回复，这个配置应该用到的还比较多，比较繁杂的数据录入一行只放置一个就撑的很高了。用Vue 我实现过类似的ProTable，也是共用comlnum 数据源。我自己研究下，再次感谢

**Comment by chenshuai2144** [comment]
ref https://github.com/ant-design/pro-components/issues/203
