### ISSUE TITLE
🐛[BUG] 最新版 2.8.1 国际化仍然有问题

### ISSUE THREAD

**Issue by liuweiGL** [ant-design/pro-components#595]
#### 版本
```json
{
 "@ant-design/pro-table": "^2.8.1"
}
```

#### App.tsx
```ts
import React from 'react'

import { UseRequestProvider } from '@ahooksjs/use-request'
import { BaseOptions } from '@ahooksjs/use-request/lib/types'
import { ConfigProvider as AntdConfigProvider } from 'antd'
import zhCN from 'antd/es/locale/zh_CN'
import { BrowserRouter } from 'react-router-dom'

import fetcher from 'src/lib/fetcher'
import Router from 'src/router'
import 'src/style'

import LayoutSwitch from './layouts/LayoutSwitch'


const useRequestConfig: BaseOptions<unknown, string[]> = {
  manual: true,
  requestMethod: fetcher.request
}

const App: React.FC = () => {
  return (
        <AntdConfigProvider locale={zhCN}>
          <UseRequestProvider value={useRequestConfig}>
            <BrowserRouter>
              <LayoutSwitch>
                <Router />
              </LayoutSwitch>
            </BrowserRouter>
          </UseRequestProvider>
        </AntdConfigProvider>
  )
}

export default App
```

#### 问题
分页组件国际化不完全：
![image](https://user-images.githubusercontent.com/21048878/94326988-a5553680-ffda-11ea-995d-7d5b38c077ce.png)

#### 其他
`CRA` 脚手架搭建的项目，是需要额外配置什么吗？

**Comment by liuweiGL** [comment]
#55

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/~demos/src-table-15

挨个重现的repo把

**Comment by liuweiGL** [comment]
> https://procomponents.ant.design/~demos/src-table-15
> 
> 挨个重现的repo把

你这个 demo 里面也是有问题的呀：
![image](https://user-images.githubusercontent.com/21048878/95949541-77b71c80-0e25-11eb-8176-0e02d08e8a86.png)

**Comment by chenshuai2144** [comment]
没配置 antd 的config-provide， https://procomponents.ant.design/~demos/src-table-14 这个就配置ile

**Comment by liuweiGL** [comment]
[demo.zip](https://github.com/ant-design/pro-components/files/5383031/demo.zip)
![image](https://user-images.githubusercontent.com/21048878/96089206-13fe2380-0ef9-11eb-9615-fe94c494447e.png)

**Comment by lklslkla** [comment]
@chenshuai2144 怎么样才可以国际化呢,日期还是原来的问题,我把zhcn换成lib下的也没用啊;
@liuweiGL 哥们,你的国际化怎么样了啊,有实现的demo吗

**Comment by liuweiGL** [comment]
pro-table 升级到最新版本，然后配置 antd 的 ConfigProvider 就好了吧。
