### ISSUE TITLE
🐛[BUG] 参数splitMenus改为false,Layout Header Title 显示有问题

### ISSUE THREAD

**Issue by lhzhou180606** [ant-design/pro-components#5951]
参数splitMenus改为false,Layout Header Title 显示有问题

### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/39972617/190885299-9c1edc14-8037-43ab-924e-9663ad53bbe5.png)
参数splitMenus改为false,Layout Header Title 显示有问题
### 📷 复现步骤

https://codesandbox.io/s/14qw2y

### 🏞 期望结果

参数splitMenus改为false,Layout Header Title 显示为白色字体与整体样式适配

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lhzhou180606** [comment]
不行，这个问题没解决

**Comment by chenshuai2144** [comment]
升级版本把，如果还没有解决看看是不是 样式污染了
