### ISSUE TITLE
🧐[问题] module is not defined in Vite

### ISSUE THREAD

**Issue by textnumber085** [ant-design/pro-components#5954]
I created a test project with `yarn create vite my-react-app --template react-ts`.

After everything is settled, then `yarn add @ant-design/pro-components`.

However when I add this page, it can not be loaded.

```
import { ProCard } from "@ant-design/pro-components";

const About = () => {
    return (
        <>
            <h1>About</h1>
            <ProCard title="默认尺寸" extra="extra" tooltip="这是提示" style={{ maxWidth: 300 }}>
                <div>Card content</div>
                <div>Card content</div>
                <div>Card content</div>
            </ProCard>
            <ProCard
                title="小尺寸卡片"
                extra="extra"
                tooltip="这是提示"
                style={{ maxWidth: 300, marginBlockStart: 24 }}
                size="small"
            >
                <div>Card content</div>
                <div>Card content</div>
                <div>Card content</div>
            </ProCard>
        </>
    );
};

export default About;

```

useHMR.js:14 Uncaught ReferenceError: module is not defined

**Comment by 1589625130** [comment]
有没有人解决啊

**Comment by textnumber085** [comment]
> [ant-design/cssinjs#46](https://github.com/ant-design/cssinjs/issues/46)

@sushi-su  Just install `@ant-design/cssinjs`? still not working 
![undefined](https://user-images.githubusercontent.com/7994054/192133709-966676fd-c3fe-48da-be6b-edd97618cd72.jpg)

**Comment by sushi-su** [comment]
@textnumber085 cssinjs 用 0.0.0-alpha.45 版本

**Comment by 1589625130** [comment]
怎么用啊

**Comment by 1589625130** [comment]
> @textnumber085 cssinjs 用 0.0.0-alpha.45 版本

老哥，这个怎么用进去啊

**Comment by 1589625130** [comment]
> [ant-design/cssinjs#46](https://github.com/ant-design/cssinjs/issues/46)

哥，出个教程引导一下吧

**Comment by sushi-su** [comment]
@1589625130 ...在自己项目安装上指定版本就行 
![image](https://user-images.githubusercontent.com/50985188/192146166-83390e4b-8b9e-4ced-abae-0a47c714fe71.png)

**Comment by sushi-su** [comment]
https://github.com/QNAV/RuoYi-X-Admin 可以参考我还在开发的一个项目

**Comment by 1589625130** [comment]
> https://github.com/QNAV/RuoYi-X-Admin 可以参考我还在开发的一个项目
谢谢老哥

**Comment by textnumber085** [comment]
> @textnumber085 cssinjs 用 0.0.0-alpha.45 版本

Thanks, but still...

![undefined2](https://user-images.githubusercontent.com/7994054/192148415-1c971453-9a71-4097-95db-f70aaa5c63e3.jpg)


I'll look at your project :)

**Comment by Jungzl** [comment]
pnpm:
```json
  "pnpm": {
    "overrides": {
      "@ant-design/pro-utils>@ant-design/cssinjs": "0.0.0-alpha.45"
    }
  }
```

yarn:
```json
  "resolutions": {
    "@ant-design/pro-utils/**/@ant-design/cssinjs": "0.0.0-alpha.45"
  }
```

npm:
```json
  "overrides": {
    "@ant-design/pro-utils": {
      "@ant-design/cssinjs": "0.0.0-alpha.45"
    }
  }

**Comment by 1589625130** [comment]
> ```json
>   "pnpm": {
>     "overrides": {
>       "@ant-design/pro-utils>@ant-design/cssinjs": "0.0.0-alpha.45"
>     }
>   }
> ```
多谢大佬，完美解决

**Comment by 583540970** [comment]
> > ```json
> >   "pnpm": {
> >     "overrides": {
> >       "@ant-design/pro-utils>@ant-design/cssinjs": "0.0.0-alpha.45"
> >     }
> >   }
> > ```
> 
> 多谢大佬，完美解决



> > ```json
> >   "pnpm": {
> >     "overrides": {
> >       "@ant-design/pro-utils>@ant-design/cssinjs": "0.0.0-alpha.45"
> >     }
> >   }
> > ```
> 
> 多谢大佬，完美解决

大佬,这段加在哪里

**Comment by 1589625130** [comment]
> > > ```json
> > >   "pnpm": {
> > >     "overrides": {
> > >       "@ant-design/pro-utils>@ant-design/cssinjs": "0.0.0-alpha.45"
> > >     }
> > >   }
> > > ```
> > 
> > 
> > 多谢大佬，完美解决
> 
> > > ```json
> > >   "pnpm": {
> > >     "overrides": {
> > >       "@ant-design/pro-utils>@ant-design/cssinjs": "0.0.0-alpha.45"
> > >     }
> > >   }
> > > ```
> > 
> > 
> > 多谢大佬，完美解决
> 
> 大佬,这段加在哪里

package.json

**Comment by textnumber085** [comment]
> Add code snippets below to your `package.json` and reinstall.
> 
> pnpm:
> 
> ```json
>   "pnpm": {
>     "overrides": {
>       "@ant-design/pro-utils>@ant-design/cssinjs": "0.0.0-alpha.45"
>     }
>   }
> ```
> 
> yarn:
> 
> ```json
>   "resolutions": {
>     "@ant-design/pro-utils/**/@ant-design/cssinjs": "0.0.0-alpha.45"
>   }
> ```
> 
> npm:
> 
> ```json
>   "overrides": {
>     "@ant-design/pro-utils": {
>       "@ant-design/cssinjs": "0.0.0-alpha.45"
>     }
>   }
> ```

thanks! error resolved!!
