### ISSUE TITLE
👑 [需求] prolayout的左侧菜单栏滚动条，可以给个重写滚动条的classname接口吗

### ISSUE THREAD

**Issue by amin168** [ant-design/pro-components#5956]
### 🔩 所属模块或组件

ProLayout

### 🥰 需求描述

添加可以重写滚动条样式的接口，现在的滚动条太大了

![image](https://user-images.githubusercontent.com/10808093/190940118-3f5e1f6a-f438-43c3-984e-712fac4548cf.png)
![image](https://user-images.githubusercontent.com/10808093/190940276-ffa4fcde-a316-4394-808e-400cc786b581.png)

**Comment by vobile-wangzhenfeng** [comment]
以前的版本滚动条是没这个问题的。迁移到proComponents后才有的

**Comment by meyerlee** [comment]
以前菜单的深色配色现在也没有了，那个样式挺好的，啥时候能回来？

**Comment by chenshuai2144** [comment]
直接全局覆盖把，滚动条尽量全部都一样

**Comment by hihuangwei** [comment]
> 直接全局覆盖把，滚动条尽量全部都一样

希望菜单这部分的滚动条样式可以自定义

**Comment by chenshuai2144** [comment]
那也一样用 css 覆盖，我们没做hack的

**Comment by hihuangwei** [comment]
> 

实在不知从何入手  来个demo吧

**Comment by chenshuai2144** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/CSS/::-webkit-scrollbar

**Comment by amin168** [comment]
```
.ant-layout-sider-children {
  ::-webkit-scrollbar {
    width: 6px !important;
  }

  /* stylelint-disable-next-line no-duplicate-selectors */
  ::-webkit-scrollbar {
    width: 6px;
    height: 6px;
  }

  ::-webkit-scrollbar-button {
    width: 0;
    height: 0;
  }

  ::-webkit-scrollbar-thumb {
    background: #ccc;
  }

  ::-webkit-scrollbar-track {
    background-color: #e6e5e5;
  }
}
```

**Comment by hihuangwei** [comment]
已解决
