### ISSUE TITLE
🐛[BUG] Pro-form 中 request获取的数据和initialValues 优先级问题

### ISSUE THREAD

**Issue by HYhuangyuan** [ant-design/pro-components#5957]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

在v1.69.4 中 request获取的数据比initialValues优先级高，新一点的版本中（比如v.1.74.4） initialValues 优先级更高， 

### 📷 复现步骤

v1.69.4
![image](https://user-images.githubusercontent.com/108987669/190945999-c36b9fa1-9a6d-47ca-a000-adb0a12fecc5.png)
![image](https://user-images.githubusercontent.com/108987669/190946040-743ccb72-2a52-447c-86c7-a2f9ca42d7f7.png)

v.1.74.4
![image](https://user-images.githubusercontent.com/108987669/190946133-6cbc8883-0c6b-41ff-8e27-cac1963c6fdf.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
数据来源太多了，的确没啥好办法了。你的诉求是什么？

**Comment by HYhuangyuan** [comment]
感觉initialValues 优先级应该最低吧，很多时候新建和编辑是会复用一个组件的，新建时候没有远程数据，initialValues 直接生效， 编辑时候 request 获取的数据应该要覆盖掉initialValues ;  而且这个优先级在小版本中做调整， 不太合适；项目中有人升级了proTable, 然后给这个pro-form顺带升级， 项目中所有的这种form 都有问题了
