### ISSUE TITLE
pro-layout在360极速模式中显示有问题

### ISSUE THREAD

**Issue by mwj610** [ant-design/pro-components#5960]
https://procomponents.ant.design/~demos/layout-classicmode?layout=mix&splitMenus=true

**Comment by amin168** [comment]
+1，360浏览器下，直接访问官网的 [https://procomponents.ant.design/components/layout](https://procomponents.ant.design/components/layout) 也有问题

**Comment by chenshuai2144** [comment]
不支持非现代浏览器 和  版本太低的浏览器
