### ISSUE TITLE
🐛[BUG] 升级到protable组件到最新版本后，表格筛选日期选择器返回未格式化数据

### ISSUE THREAD

**Issue by zhouzyc** [ant-design/pro-components#5963]
### 🐛 bug 描述

1.升级最新组件版本："dependencies": {
    "@ant-design/pro-card": "^2.0.7",
    "@ant-design/pro-descriptions": "^2.0.8",
    "@ant-design/pro-form": "^2.1.1",
    "@ant-design/pro-layout": "^7.0.7",
    "@ant-design/pro-list": "^2.0.8",
    "@ant-design/pro-skeleton": "^2.0.3",
    "@ant-design/pro-table": "^3.0.8",
  },
2.使用protable，配置表格筛选：{
      title: '创建时间',
      dataIndex: 'created_at',
      valueType: 'dateRange',
      hideInTable: true,
      search: {
        transform: (value) => {
          return {
            startTime: value[0],
            endTime: value[1],
          };
        },
      },
    },
3.点击查询后出现错误的返回值。
![1663727656022](https://user-images.githubusercontent.com/18420689/191401462-0809b02a-f93d-4e03-b87f-21f84736e1e2.jpg)

### 📷 复现步骤
下载复现代码，运行启迪到 首页，点击查询
### 🏞 期望结果

正常返回
### 💻 复现代码

https://gitee.com/JS-VeryHappy/vh-admin-template-default.git

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 4+
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
已经修复了，你看一下
