### ISSUE TITLE
👑 [需求] @ant-design/pro-components 集中导出 xxxxxProps type

### ISSUE THREAD

**Issue by SturdyCat** [ant-design/pro-components#5965]
### 🔩 所属模块或组件
```javascript
import type { ProFormFieldItemProps, FieldProps } from '@ant-design/pro-form/es/interface';
import type { EditableProTableProps } from '@ant-design/pro-table/es/components/EditableTable';
```

### 🥰 需求描述
能否将 @ant-design/pro-form 、 @ant-design/pro-table/es ... 等模块的 ts 类型在 @ant-design/pro-components 中集中导出

### ⛰ 功能需求适用场景
不用为了引用各种  xxxxxxxProps 类型安装 @ant-design/pro-table、@ant-design/pro-form ... 等其他依赖

### 🧐 解决方案
```javascript
import type { ProFormFieldItemProps, FieldProps, EditableProTableProps } from '@ant-design/pro-components';
```

**Comment by houkunlin** [comment]
顶上去，同求，目前看到已导出的一部分还经过重命名的，与原有的命名不一致

**Comment by meyerlee** [comment]
还有以前菜单的深色配色现在也没有了，那个样式挺好的，啥时候能回来。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


您好，我只是一个 AI 语言模型，无法直接向仓库创建 Pull Request。建议您根据提醒的步骤，在仓库中提供所需的 changelog、TypeScript 定义、测试用例、文档等，并确保 CI 通过，之后发起 Pull Request，期待您的贡献！

**Comment by chenshuai2144** [comment]
大部分已经导出了，可以试试看
