### ISSUE TITLE
🐛[BUG]ProFormSwitch无法获取默认值

### ISSUE THREAD

**Issue by giamchen** [ant-design/pro-components#597]
### 🐛 bug 描述
ProFormSwitch 组件必须要点击一下开关，onFinish 参数才会有对应值，否则参数不存在

### 📷 复现步骤

- 创建一个ProFormSwitch组件在表单中
- 设置defaultChecked和checked 
- 不操作直接提交表单没有获得开关的值，但是提交之前点击一下则正常获取

### 🏞 期望结果
ProFormSwitch 组件无需点击就能够获取默认值

### © 版本信息

- ProComponents 版本: 1.0.0-beta.2
- umi 版本 : 3.2.22
- 浏览器环境 : Google Chrome 85.0.4183.102 (64 位)
- 开发环境 : Windows 10

**Comment by SeaStars-beep** [comment]
![image](https://user-images.githubusercontent.com/72014072/94420095-3c2a1a80-01b6-11eb-9caa-b943f5e4b4c0.png)
设置下initialValue值即可 
![Uploading image.png…]()

**Comment by giamchen** [comment]
> 在ProFormSwitch设置下initialValue属性值即可

![image](https://user-images.githubusercontent.com/33769348/95611988-28739380-0a95-11eb-8f18-2d3267b2e90d.png)
但是控制台就会报警告

**Comment by Deja-vuuu** [comment]
> > 在ProFormSwitch设置下initialValue属性值即可
> 
> ![image](https://user-images.githubusercontent.com/33769348/95611988-28739380-0a95-11eb-8f18-2d3267b2e90d.png) 但是控制台就会报警告

我也遇到了同样的问题

**Comment by chenshuai2144** [comment]
default 不会注入的

**Comment by Deja-vuuu** [comment]
> default

defaultChecked吗？

```
  <ProFormSwitch name="enabled" label="任务开关" fieldProps={{defaultChecked: true  }} />
```


这在表单里面回显会有问题。

**Comment by Deja-vuuu** [comment]
defaultChecked吗？
```
  <ProFormSwitch name="enabled" label="任务开关" fieldProps={{defaultChecked: true  }} />
```
这样写表单里面回显会有问题。
我在 外层<ProForm>设置的这值为false 但是展示还是选中true

是我哪里写的有问题吗？

**Comment by Deja-vuuu** [comment]
> default 不会注入的

大佬帮忙看看 我这个有什么问题吗 

https://codesandbox.io/s/biao-dan-xiang-forked-3kdt6?file=/App.tsx

**Comment by Deja-vuuu** [comment]
> https://codesandbox.io/s/biao-dan-xiang-forked-3kdt6?file=/App.tsx

![image](https://user-images.githubusercontent.com/27748682/145527373-a842bc70-d777-4340-bc66-c58dab5ed145.png)

我的需求是 ProFormSwitch没默认值的时候读取 default值  有返回的时候读取返回值

**Comment by Deja-vuuu** [comment]
> default 不会注入的

又更新了一下 demo

问题就是 switch1为 啥不行    switch4可以 ？ 希望大佬有时间帮忙看看

**Comment by chenshuai2144** [comment]
好像是false被裁减掉了，因为都不生效的，是个bug。
