### ISSUE TITLE
ProTable 的column里用了request动态加载选项，在render里能获取到这些选项吗。

### ISSUE THREAD

**Issue by 774265230** [ant-design/pro-components#5970]
### 🧐 问题描述

ProTable 的column里用了request动态加载选项，但是需要渲染成Tag标签的样式，用hooks的话因为层级太深，而且是Tab的Table，React会报错提示我使用了太多的钩子。

**Comment by chenshuai2144** [comment]
先学一下基础语法，你连报错原因都没定位到
