### ISSUE TITLE
🐛[BUG] route-utils 导致 ProLayout 的面包屑没了

### ISSUE THREAD

**Issue by amin168** [ant-design/pro-components#5971]
### 🐛 bug 描述

[route-utils](https://github.com/umijs/route-utils) 这个项目，如果路径 `/admin/sub-page3/*`，会导致以下错误，并且会导致 `ProLayout` 的面包屑没了

具体原因可能是这个路径中 * 的问题，可能是 pathToRegexp 在进行 test 时导致出错

<img width="477" alt="1663812182044_3F4D61AA-F60C-4985-80E4-4B6DF0CEB5B8" src="https://user-images.githubusercontent.com/10808093/191642811-2edf8c3a-e3c9-4dcc-aab2-8cdc0afc69e9.png">

### 📷 复现步骤

<img width="399" alt="1663812206579_4EF9C018-A24F-4a75-B5E2-0385AC7D5C8B" src="https://user-images.githubusercontent.com/10808093/191642827-0aeab31d-6b0e-4b17-94e3-e42c736a26d9.png">

### © 版本信息

route-utils 3.0.0

ProComponents 2.3.10

**Comment by chenshuai2144** [comment]
来个pr？

**Comment by chenshuai2144** [comment]
fixed, try again
