### ISSUE TITLE
ModalForm里面包ProTable有点问题

### ISSUE THREAD

**Issue by lovesL** [ant-design/pro-components#5973]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/27960630/191672116-61389d94-83e1-4eeb-a658-88dfb05b8371.png">
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/27960630/191672240-1dd63abd-7f08-4f07-b711-3cb0b12257ff.png">
而且样式也有些错乱了

**Comment by lovesL** [comment]
希望能支持modal里面 放表格

**Comment by chenshuai2144** [comment]
用 Modal 不要用 ModalForm 就可以了，不然可能会有 form 套  form 的冲突
