### ISSUE TITLE
🐛[BUG]ProTable - 高级表格 路由刷新后重置按钮无法还原搜索

### ISSUE THREAD

**Issue by JonnyLiu** [ant-design/pro-components#5974]
### 🐛 bug 描述

ProTable - 高级表格 带条件查询后 路由刷新后重置按钮无法还原搜索

### 🏞 期望结果

带条件查询后 路由刷新后重置按钮还原搜索框

### 💻 复现代码

https://procomponents.ant.design/components/table/?current=1&pageSize=5&state=all#%E6%9F%A5%E8%AF%A2%E8%A1%A8%E6%A0%BC  进去点重置就无效

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by wangmeijian** [comment]
可以还原啊

**Comment by chenshuai2144** [comment]
rest 会还原到 initialvalues ，你看看你的 initialvalues  是不是被改变了
