### ISSUE TITLE
🐛[BUG] pro-components 2.3.12 出现 routes 将会废弃，为了保证兼容请使用 children 作为子节点定义方式

### ISSUE THREAD

**Issue by amin168** [ant-design/pro-components#5977]
### 🐛 bug 描述

更新 `pro-components` 到 `2.3.12` 版本后，控制台出现以下警告

![image](https://user-images.githubusercontent.com/10808093/191710019-62a8a353-eac3-4bf9-bc7e-a9990fb4339f.png)

### © 版本信息

- ProComponents : 2.3.12
- umi : 4.0.21
- antd : 4.23.2

**Comment by zcSkr** [comment]
+1

**Comment by netcore-jroger** [comment]
就算修改为 children 还是会有这个警告。原因大概是因为这里：
![image](https://user-images.githubusercontent.com/3223890/191720591-7fe50078-6eeb-402f-9efb-43723178bcce.png)

**Comment by netcore-jroger** [comment]
原来是这里 https://github.com/umijs/route-utils/blob/master/src/transformRoute/transformRoute.ts#L141

**Comment by WillWuWeijie** [comment]
+1

**Comment by 0fan** [comment]
用的umi4, pro-components升级到2.3.12后把路由routes改成chidren连项目都启动不起来

**Comment by WuJiY** [comment]
> 用的umi4, pro-components升级到2.3.12后把路由routes改成chidren连项目都启动不起来

+1

**Comment by houkunlin** [comment]
相同问题。
在 `config/routes.ts` 配置文件中使用 `routes` 来配置路由是正常可以编译运行的，但是浏览器访问的时候控制台提示警告信息，如果改为 `children` 则无法编译通过。

https://github.com/ant-design/ant-design-pro/issues/10258

`@umijs/max` 已安装版本: 4.0.21
`@ant-design/pro-components` 已安装版本: 2.3.10

**Comment by lovewinders** [comment]
+1

**Comment by xguan2014** [comment]
+1

**Comment by hancens1024** [comment]
+10086

**Comment by Fiuck** [comment]
+10010

**Comment by panhezeng** [comment]
这种提示应该用 waring 而不是 error 吧， 还有改成 children 直接编译报错， 能不能不要这么激进，就算提示修改，也要修改后不出问题吧。

**Comment by cxhcmc** [comment]
遇到同样的问题

**Comment by kaindy7633** [comment]
同样的问题 +1

**Comment by mushroomlb** [comment]
升级pro-components 到2.3.14依然存在

**Comment by liuzhaowei55** [comment]
升级pro-components 到2.3.16依然存在

**Comment by peterpanBest** [comment]
+1

**Comment by hejinguo** [comment]
+1

**Comment by Rainyun** [comment]
+1

**Comment by xj89959853** [comment]
+1

**Comment by xj89959853** [comment]
我到处寻找解决方案，看来大家都遇到了

**Comment by jurieo** [comment]
++++++11111，目前依然没有解决。。

**Comment by chenshuai2144** [comment]
这个提示不会有任何问题，大家只要没有操作过 router 就不会有问题

**Comment by netcore-jroger** [comment]
@chenshuai2144 不知道你测试了没有，项目里面已经改成 children 了，但还是有这个提示。

**Comment by mashirozx** [comment]
> 这个提示不会有任何问题，大家只要没有操作过 router 就不会有问题

大佬，请问一下怎样算是操作过router，我怕怕😱

**Comment by houkunlin** [comment]
看到控制台的警告信息，强迫症有点受不了

**Comment by vominhtrius** [comment]
I encountered similar problem. Has anyone solved this problem yet?

**Comment by peterpanBest** [comment]
+1

**Comment by zhangxinyong12** [comment]
'@ant-design/pro-components': 2.3.12_w5ozx5g45rrkuycam7gstefluy
我也遇到了。


请问，企业级还敢用吗？

**Comment by mashirozx** [comment]
2.4.2 已经没有这个问题了

"@ant-design/pro-components": "2.4.2",
"antd": "5.3.2",
"@umijs/max": "4.0.57",
"umi-presets-pro": "2.0.3",

**Comment by zhangxinyong12** [comment]
> 2.4.2 已经没有这个问题了
> 
> "@ant-design/pro-components": "2.4.2", "antd": "5.3.2", "@umijs/max": "4.0.57", "umi-presets-pro": "2.0.3",

好的。确实没问题了。我光想着降低版本号了。。。。。
