### ISSUE TITLE
🐛[BUG] ProForm 中自定义 FormItem 定义了 defaultProps 导致 value 不更新

### ISSUE THREAD

**Issue by alicejxr** [ant-design/pro-components#5978]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤

https://codesandbox.io/s/formrefde-shi-yong-forked-qdwxml?file=/App.tsx

自定义 FormItem 定义了 defaultProps  的 value 默认值，输入内容后 value 没有同步更新

### 🏞 期望结果

输入内容后 value 同步更新

### 💻 复现代码

https://codesandbox.io/s/formrefde-shi-yong-forked-qdwxml?file=/App.tsx

### © 版本信息

- ProComponents 版本:  2.3.12

**Comment by wangmeijian** [comment]
两个问题：  
1. 不要封装Input，直接用ant design的Input组件  
2. 设置默认值，请使用 initialValues

**Comment by alicejxr** [comment]
> 

1. 是为了快速复现才这么写的，具体实现场景肯定不会这么写的
2. 使用 [nitialValues](https://procomponents.ant.design/components/form#:~:text=%E5%A6%82%E6%9E%9C%E4%BD%A0%E6%83%B3%E8%A6%81%E8%AE%BE%E7%BD%AE%E9%BB%98%E8%AE%A4%E5%80%BC%EF%BC%8C%E8%AF%B7%E4%BD%BF%E7%94%A8%20initialValues) 的确可以解决问题（目前也在用了），但不太明白为什么使用 defaultProps 会导致这个问题

**Comment by alicejxr** [comment]
> 两个问题：
> 
> 1. 不要封装Input，直接用ant design的Input组件
> 2. 设置默认值，请使用 [initialValues](https://procomponents.ant.design/components/form#:~:text=%E5%A6%82%E6%9E%9C%E4%BD%A0%E6%83%B3%E8%A6%81%E8%AE%BE%E7%BD%AE%E9%BB%98%E8%AE%A4%E5%80%BC%EF%BC%8C%E8%AF%B7%E4%BD%BF%E7%94%A8%20initialValues)

1. 是为了快速复现才这么写的，具体实现场景肯定不会这么写的
2. 使用 [nitialValues](https://procomponents.ant.design/components/form#:~:text=%E5%A6%82%E6%9E%9C%E4%BD%A0%E6%83%B3%E8%A6%81%E8%AE%BE%E7%BD%AE%E9%BB%98%E8%AE%A4%E5%80%BC%EF%BC%8C%E8%AF%B7%E4%BD%BF%E7%94%A8%20initialValues) 的确可以解决问题（目前也在用了），但不太明白为什么使用 defaultProps 会导致这个问题

**Comment by chenshuai2144** [comment]
因为覆盖了 onChange ，导致 FormItem 监听导致的
