### ISSUE TITLE
portable 点刷新图标触发查询按钮loading

### ISSUE THREAD

**Issue by ycshill** [ant-design/pro-components#5981]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

点击刷新图标，查询按钮自动loading，怎么禁用loading

### 💻 示例代码

https://codesandbox.io/s/4dhjkl

### 🚑 其他信息

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/16410254/191940300-280a0d2b-1bf6-4d08-a377-01298678661b.png">

**Comment by ONLY-yours** [comment]
这就是默认的loading逻辑，并不是bug，而是设计使然
