### ISSUE TITLE
🐛[BUG]layout中的appList配置，在导航模式为侧边菜单布局和顶部菜单布局模式下无法跳转

### ISSUE THREAD

**Issue by Cyan-Xmw** [ant-design/pro-components#5987]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

layout中的appList配置，在导航模式为侧边菜单布局和顶部菜单布局模式下无法跳转

在这两种模式下点击会跳转到主页

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lihao6666** [comment]
问题依然存在，pro-components2.3.54

**Comment by gao525280067** [comment]
同样的有这个问题  https://github.com/ant-design/pro-components/issues/7606
