### ISSUE TITLE
边框跟官方有出入

### ISSUE THREAD

**Issue by lecd** [ant-design/pro-components#5989]
圆形边框为什么没有？

使用新的        "@ant-design/pro-components": "2.3.12",

依赖：
  "@umijs/max": "^4.0.0-rc.22",
 "@ant-design/pro-components": "2.3.12",

项目图
![image](https://user-images.githubusercontent.com/17017158/192187938-8a8c9a54-d0b8-45ea-b75b-22c76cbe8956.png)
官方图
![image](https://user-images.githubusercontent.com/17017158/192188007-94545ec5-22de-41da-8e16-73603e49809f.png)

**Comment by Kaby-Lake** [comment]
https://github.com/ant-design/pro-components/blob/bf3fd221d18610fd76c02147b72bdce02278ee9c/.umirc.js#L105
