### ISSUE TITLE
🐛[BUG]SettingDrawer 组件显示不完全

### ISSUE THREAD

**Issue by phoema** [ant-design/pro-components#599]
### 🐛 bug 描述

antd pro 官网
![image](https://user-images.githubusercontent.com/8730272/94353390-34c61c80-00a3-11eb-8a65-b50dbdbaa13f.png)

自己的项目
![image](https://user-images.githubusercontent.com/8730272/94353402-663ee800-00a3-11eb-8700-7777334ee8d5.png)

本地获取的antd pro 源码  
![image](https://user-images.githubusercontent.com/8730272/94353412-7eaf0280-00a3-11eb-958c-7d9d496124d0.png)

### 📷 复现步骤

我就是把下面代码放到BasicLayout.tsx了。现在有3种表现，很奇怪，是组件内部某个属性的判断问题吗？
      <SettingDrawer
        settings={settings}
        onSettingChange={(config) =>
          dispatch({
            type: 'settings/changeSetting',
            payload: config,
          })
        }
      />

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
加这个插件就有了 
https://github.com/chenshuai2144/umi-plugin-antd-theme

**Comment by phoema** [comment]
自己的项目加了这个插件，只能展示成和antd pro下载源码一样的效果
还是达不到antd pro 官网的效果啊

**Comment by phoema** [comment]
你肯定有啥东西瞒着我。。。
