### ISSUE TITLE
protable🐛[BUG]

### ISSUE THREAD

**Issue by zyp932** [ant-design/pro-components#5991]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/23090567/192419719-f2c41cbf-59e6-4688-acec-c64685cdf1cc.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
重新部署
