### ISSUE TITLE
🐛[BUG] ProFormList 配置 rules required 低版本生效，高版本不生效

### ISSUE THREAD

**Issue by rawbin-** [ant-design/pro-components#5992]
### 🐛 bug 描述

pro-form 1.43版本中ProFormList 配置required 会生效，有样式; pro-form 1.67 版本中 ProFormList 配置required 会生效，但加星样式无效

### 📷 复现步骤
直接配置ProFormList rules 或者 formItemProps都无效，
https://codesandbox.io/s/proform-list-forked-5ibx9k?file=/App.tsx

同时如果rule 不配message，会出现'请输入undefined‘，希望可以像其他表单组件一样用label 来补充

### 🏞 期望结果

希望rules required 正常生效，如果不配rule message希望可以像其他表单组件一样用label 来补充

### 💻 复现代码

https://codesandbox.io/s/proform-list-forked-5ibx9k?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Zeng-J** [comment]
可以直接使用isValidateList属性；或者`<ProFormList required />`（忽略ts类型）

**Comment by rawbin-** [comment]
> 可以直接使用isValidateList属性；或者`<ProFormList required />`（忽略ts类型）

required 靠谱，可以把星号加回来，isValidateList看起来无效是后来才加的属性，请输入 undefined 这个使用习惯跟普通表单差异太大，这里面的变更也比较大不兼容，都不敢升级了，不同项目用了不同版本效果完全不一样
