### ISSUE TITLE
🐛[BUG] ProFormTreeSelect配置fieldNames导致数据映射错误

### ISSUE THREAD

**Issue by daifuyang** [ant-design/pro-components#5993]
### 🐛 bug 描述
ProFormTreeSelect下的fieldNames配置化数据对应不上
### 📷 复现步骤

看下方代码
https://codesandbox.io/s/delicate-dawn-40m58k?file=/App.tsx

### 🏞 期望结果

正确的显示树形层级

### 💻 复现代码
https://codesandbox.io/s/delicate-dawn-40m58k?file=/App.tsx

### © 版本信息

- ProComponents 版本: 2.3.12
- 浏览器环境 chrome
- 开发环境 mac os

### 🚑 其他信息
暂无

**Comment by Dunqing** [comment]
![image](https://user-images.githubusercontent.com/29533304/192929909-8d2dcda2-5aa9-4002-9507-aedb86ec2094.png)

两个 value 一样导致的
