### ISSUE TITLE
👑 [需求]ProformTreeSelect使用request会有loading图标，但是ProformSelect是没有的。如何去除ProformTreeSelect的loading图标 

### ISSUE THREAD

**Issue by KamChing** [ant-design/pro-components#5994]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述
网速慢的时候，这个ProformTreeSelect使用request会有多一个loading，但是ProformSelect不会有。期望ProformTreeSelect不会有这个loading出现

![image](https://user-images.githubusercontent.com/30040491/192457131-587b6d33-102d-4348-868a-bd52f196b8ac.png)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30040491/192457168-6ec852b8-2f62-42b7-9321-4330dbbd6024.png)
![image](https://user-images.githubusercontent.com/30040491/192457275-f5187725-a85b-43cf-9ad7-69bd6798fdea.png)

**Comment by KamChing** [comment]
代码如上

**Comment by Dunqing** [comment]
没有办法去掉，可以提个 PR 传个 `loading: false` 支持关闭 loading
