### ISSUE TITLE
🧐[问题]关于ProForm 日期控件的问题

### ISSUE THREAD

**Issue by cqb421392034** [ant-design/pro-components#5996]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

 在linux上面build的代码 在服务器上运行日期控件有问题，在本地（window10）build完上传服务器则是正常的
linux环境：
    Linux localhost.localdomain 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux 
         node : v16.17.1
         yarn:  1.22.19
          build命令： cross-env NODE_OPTIONS=--max-old-space-size=8192 REACT_APP_ENV=test MOCK=none umi build

window环境跟linux一样
能否帮忙看下是哪个地方出问题了？
### **config.js:**
import { defineConfig } from 'umi';
import defaultSettings from './defaultSettings'; 
import proxy from './proxy';
import routes from './routerConfig'
const { REACT_APP_ENV } = process.env;
const devToolType = REACT_APP_ENV == "dev" ? "source-map" : "eval";
export default defineConfig({
  hash: true,
  antd: {},
  dva: {
    hmr: true,
  },
  layout: {
    name: 'aaa',
    locale: false,
    siderWidth: 208,
  },
  locale: { 
    default: 'zh-CN', 
    antd: true,
    baseNavigator: true,
  }, 
  targets: {
    chrome: 79,
    ie: 11,
    firefox: false,
    safari: false,
    edge: false,
    ios: false,
  }, 
  routes: routes, 
  theme: { 
    'primary-color': defaultSettings.primaryColor,

  }, 
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  manifest: {
    basePath: '/',
  },
  define: {
    REACT_APP_ENV: REACT_APP_ENV, //全局变量
  },
  nodeModulesTransform: {
    type: 'none',
    exclude: [],
  },
  dynamicImport: {
    loading: '@/components/PageLoading/index',

  },

  devServer: {
    port: 8900,
    open: true,
  },
  devtool: devToolType,
  esbuild: {},
  mfsu: {},
  webpack5: {},
  exportStatic: {}, 
});
### **packge.json:**
{
  "name": "aaa",
  "version": "5.0.0",
  "private": true,
  "description": "prajna worker order manager",
  "scripts": {
    "analyze": "cross-env ANALYZE=1 umi build",
    "build": "umi build", 
    "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none umi dev", 
    "prepare": "husky install"
  },
  "lint-staged": {
    "**/*.less": "stylelint --syntax less",
    "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
    "**/*.{js,jsx,tsx,ts,less,md,json}": [
      "prettier --write"
    ]
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie < 11"
  ],
  "dependencies": {
    "@ant-design/charts": "^1.3.6",
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-card": "^1.19.0",
    "@ant-design/pro-components": "^2.3.12",
    "@ant-design/pro-form": "^1.64.0",
    "@ant-design/pro-layout": "^6.35.0",
    "@ant-design/pro-table": "^2.71.0",
    "@hanyk/rc-viewer": "^0.0.3",
    "@umijs/route-utils": "^2.0.0",
    "antd": "^4.20.7",
    "better-xlsx": "^0.7.5",
    "braft-editor": "^2.3.9",
    "classnames": "^2.3.0",
    "file-saver": "^2.0.5",
    "moment": "^2.29.3",
    "numeral": "^2.0.6",
    "nzh": "^1.0.3",
    "omit.js": "^2.0.2",
    "path-to-regexp": "2.4.0",
    "qs": "^6.9.0",
    "rc-menu": "^9.1.0",
    "rc-tree": "4.1.5",
    "rc-util": "^5.16.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.7.0",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.2.0",
    "react-load-script": "^0.0.6",
    "react-router": "^4.3.1",
    "react-vcode": "^1.0.8",
    "umi": "^3.5.0",
    "umi-request": "^1.0.8",
    "unstated-next": "^1.1.0",
    "use-merge-value": "^1.0.1"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.1.0",
    "@babel/runtime": "^7.18.3",
    "@types/classnames": "^2.3.1",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.0",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.0",
    "@types/qs": "^6.5.3",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.8.0",
    "@umijs/max": "^4.0.0-rc.22",
    "@umijs/plugin-blocks": "^2.2.0",
    "@umijs/plugin-esbuild": "^1.4.0",
    "@umijs/preset-ant-design-pro": "^1.3.0",
    "@umijs/preset-dumi": "^1.1.0",
    "@umijs/preset-react": "^2.1.0",
    "@umijs/preset-ui": "^2.0.9",
    "@umijs/yorkie": "^2.0.3",
    "carlo": "^0.9.46",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.3.0",
    "dayjs": "1.8.30",
    "detect-installer": "^1.0.0",
    "dva-core": "^2.0.4",
    "enzyme": "^3.11.0",
    "eslint": "^7.32.0",
    "express": "^4.17.1",
    "gh-pages": "^3.2.0",
    "husky": "^7.0.4",
    "js-export-excel": "^1.1.2",
    "jsdom": "^19.0.0",
    "jsdom-global": "^3.0.0",
    "lint-staged": "^10.0.0",
    "lodash": "^4.17.0",
    "lodash.merge": "^4.6.2",
    "mockjs": "^1.1.0",
    "prettier": "^2.5.0",
    "pro-download": "1.0.1",
    "puppeteer-core": "^5.0.0",
    "react-cookies": "^0.1.0",
    "stylelint": "^13.0.0",
    "typescript": "^4.5.0",
    "typescript-eslint": "^0.0.1-alpha.0",
    "umi-presets-pro": "^1.0.1",
    "umi-serve": "^1.9.10",
    "webpack": "^5.74.0",
    "webpack-cli": "^4.10.0"
  },
  "engines": {
    "node": ">=10.0.0"
  }
}
### **demo代码**

import { BetaSchemaForm, ProForm, ProFormDatePicker } from '@ant-design/pro-components';
import { DatePicker, Divider, Form } from 'antd';
import React from 'react';
const Test: React.FC<any> = () => {
	return <>
		<Divider>BetaSchemaForm</Divider>
		<BetaSchemaForm
			layoutType='Form'
			rowProps={{
				gutter: [0, 0],
			}}
			colProps={{
				span: 12
			}}
			labelCol={{
				span: 6
			}}
			preserve={false}
			requiredMark
			labelWrap={true}
			labelAlign="left"
			layout="horizontal"
			grid={true}
			columns={[
				{
					title: '创建时间',
					key: 'showTime',
					dataIndex: 'createName',
					valueType: 'date',
				},
			]}
			submitter={false}
		/>
		<Divider>ProForm组件</Divider>
		<ProForm>
			<ProFormDatePicker colProps={{ xl: 8, md: 12 }} label="入职日期" name="date" />
		</ProForm>
		<Divider />
		<Divider>Form组件</Divider>
		<Form
			labelCol={{ span: 4 }}
			wrapperCol={{ span: 14 }}
			layout="horizontal"
		>

			<Form.Item label="DatePicker">
				<DatePicker />
			</Form.Item>
		</Form>
	</>
};

export default Test;

demo1:linux环境构建的   http://121.43.101.201:60010/test/
demo2:window环境构建的   http://121.43.101.201:60011/test/

**Comment by cqb421392034** [comment]
node_modules 清空  yarn.lock删除  .umi清空  都试过了

**Comment by chenshuai2144** [comment]
所以有什么问题？

**Comment by cqb421392034** [comment]
> 所以有什么问题？

dayjs  moment 升级到最新  node_modules 清空 yarn.lock删除 .umi清空后可以了
