### ISSUE TITLE
🐛[BUG] 本地运行时，页面样式无法正常显示

### ISSUE THREAD

**Issue by Dssssds** [ant-design/pro-components#5998]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤
1. yarn dev
2. 异常界面
<img width="1599" alt="image" src="https://user-images.githubusercontent.com/17268259/192577643-86933fc5-2f4f-4777-9d1e-207d17ff4a03.png">
3. 正常界面
4. 
<img width="1692" alt="image" src="https://user-images.githubusercontent.com/17268259/192577710-e8531e93-7cde-42c2-8e71-fae5950ad020.png">

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by zwd609258057** [comment]
这两个图有什么区别吗

**Comment by Dssssds** [comment]
就是样式出问题了。内容没问题的，上面的图，明显table 样式不对， 下面的table 才算正确的。 用的是Protable

**Comment by meyerlee** [comment]
dom结构可能变了，你得看看你的css是不是用上了
