### ISSUE TITLE
👑 [需求]希望使用modal的visible属性以及onVisibleChange属性的组件更新为open属性和onOpenChange

### ISSUE THREAD

**Issue by zwd609258057** [ant-design/pro-components#6001]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

所有使用modal的visible属性以及onVisibleChange属性的组件

### 🥰 需求描述
希望使用modal的visible属性以及onVisibleChange属性的组件更新为open属性和onOpenChange

Ant design 因为历史原因，弹层类组件展示命名并不统一，出现了 open 与 visible 都在使用的情况。这使得非 tsx 用户在开发时遭遇的记忆成本。同样导致新增 feature 时选择何种命名的模棱两可。因而我们希望统一该属性命名，你仍然可以使用原本的 visible 它仍然会向下兼容，但是从 v5 起我们将从文档中移除该属性。

### ⛰ 功能需求适用场景

有助于去除相关错误提示：
Warning: [antd: Tooltip] `visible` is deprecated which will be removed in next major version, please use `open` instead. 

Warning: [antd: Tooltip] `onVisibleChange` is deprecated which will be removed in next major version, please use `onOpenChange` instead.

**Comment by zwd609258057** [comment]
更新到最新版本已解决

**Comment by 13736375699xl** [comment]
我也遇见了提示说要用open，但是参数里面还不支持得情况，open属性和onOpenChange 无效参数

**Comment by 13736375699xl** [comment]
hhah
