### ISSUE TITLE
🐛[BUG]customSymbol

### ISSUE THREAD

**Issue by WT-Road** [ant-design/pro-components#6003]
### 🐛 bug 描述
由于不想出现货币符号,设置customSymbol: false时小数点消失,我记得之前有人提过,目前解决了吗,截图是官网的例子.
正常情况显示小数点
![image](https://user-images.githubusercontent.com/14371925/192743798-4659d3ef-d21d-4ce1-a044-d8069cb59d4b.png)
小数点消失
![image](https://user-images.githubusercontent.com/14371925/192743956-396d9775-b49a-4307-b1ce-af1ed0faeb2d.png)

### 📷 复现步骤

https://procomponents.ant.design/components/descriptions#columns-%E9%85%8D%E7%BD%AE

### © 版本信息

- ProComponents 版本: "2.3.11"

**Comment by kiner-tang** [comment]
我来看看
