### ISSUE TITLE
🐛[BUG]DrawerForm 的 onFinish 触发关闭动画时，录入值闪跳初始值

### ISSUE THREAD

**Issue by SturdyCat** [ant-design/pro-components#6006]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
DrawerForm 的 onFinish 触发关闭动画时，录入值闪跳初始值

### 📷 复现步骤
1. 点按钮
2. 修改录入框值
3. 保存后触发关闭动画
4. 动画期间数据会闪跳初始值

### 🏞 期望结果
动画过程中保持不变

### 💻 复现代码
[![codesandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/drawer-biao-dan-bug-he3wrd?file=/App.tsx)

### © 版本信息

- ProComponents 版本: 2.3.11

**Comment by kiner-tang** [comment]
mark
