### ISSUE TITLE
🐛[BUG]ProLayout遮挡了antd 的Alert组件

### ISSUE THREAD

**Issue by scfido** [ant-design/pro-components#6008]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

在Pro-Layout布局中不能使用ANTD 的Alert组件中页面顶端显示，1.x版本是可以的。
![image](https://user-images.githubusercontent.com/5214402/192932105-0ef1cf36-1178-4df6-af31-138cb2a9cbf9.png)

### 📷 复现步骤

```sh
git clone https://github.com/scfido/demo-antd-pro-layout.git
cd demo-antd-pro-layout
pnpm install
pnpm start
```

### 🏞 期望结果

能直接使用Alert显示如下效果
![image](https://user-images.githubusercontent.com/5214402/192931803-20b3ff33-2c3e-4482-b898-67f9e12f326f.png)

### 💻 复现代码

```tsx
export default function Layout() {
  return (
    <div>
      <Alert message="站点通知"  banner/>
      <ProLayout>
        <PageContainer >
          <Outlet />
        </PageContainer>
      </ProLayout>
    </div>
  );
}
```

### © 版本信息

- ProComponents 版本: 2.3.13
- antd:4.23.3
- umi 版本:4.0.22
- 浏览器环境 edge

### 🚑 其他信息

虽然Layout示例[页脚工具栏和全局公告](https://procomponents.ant.design/components/layout#%E9%A1%B5%E8%84%9A%E5%B7%A5%E5%85%B7%E6%A0%8F%E5%92%8C%E5%85%A8%E5%B1%80%E5%85%AC%E5%91%8A)也可以达到效果，但是仅支持`mix`模式的`layout`，设置也非常复杂，不方便动态控制显示和隐藏。

**Comment by chenshuai2144** [comment]
把 fixheader 去掉，不去掉他就会浮动掉顶端。另外推荐通知做到 layout 里面，不然遮挡问题很难解决。

**Comment by scfido** [comment]
fixedHeader设置为`false`或`true`，对这个问题的显示效果都没有任何改变。 
layout里面没有位置放通栏的元素，是否可以考虑增加这个位置？
@chenshuai2144

**Comment by chenshuai2144** [comment]
提个功能请求issue吧
