### ISSUE TITLE
🐛[BUG] Can't resolve '@ant-design/pro-table/dist/table.css'

### ISSUE THREAD

**Issue by fitterfizzle** [ant-design/pro-components#6014]
As stated in the title, using latest version of ant design and pro-table, following error appears upon `npm run start`

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/96863959/192990634-814e0cd6-4a88-4dd4-a163-0400fa18bb6c.png">

**Comment by chenshuai2144** [comment]
已经不需要了，你可以删除掉了，在最新的 procomponents 中我们已经没有 css 和 less 了

**Comment by fitterfizzle** [comment]
I don't understand what you wrote nor why the issue was closed. I tried updating again to the latest version and this problem still persists. As of now v3 can't be used. Is there any resolution?
