### ISSUE TITLE
🧐[问题]1.1.1的文档还有吗，在哪能看

### ISSUE THREAD

**Issue by xyylb** [ant-design/pro-components#6015]
🧐[问题]1.1.1的文档还有吗，在哪能看

**Comment by ONLY-yours** [comment]
https://github.com/ant-design/pro-components/tree/v1 
仓库里面doc还在，但是没有部署到环境上去。

@chenshuai2144  要部署一个v1的文档站点用用么

**Comment by chenshuai2144** [comment]
功能差不都， 感觉没啥必要，是有什么特别大的区别吗？
