### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by ananiahfox** [ant-design/pro-components#6017]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
The syncToUrl  parameter of the form attribute of ProTable modify URL,  Click the New button to pop up the Modal, Unable to get the current URL parameters in the component.

The syncToUrl  parameter of the form attribute of ProTable modify URL,  Click the New button to pop up the Modal, Unable to get the current URL parameters in the component.
### 💻 示例代码
![image](https://user-images.githubusercontent.com/41354027/193012762-ee5b8007-e8c5-4d48-8825-e034e983ed2f.png)
![image](https://user-images.githubusercontent.com/41354027/193012871-82640d03-035b-47f4-aa7f-3a9768d17597.png)

### 🚑 其他信息

https://user-images.githubusercontent.com/41354027/193013965-855c1d56-7aa5-4a20-99b7-dc95fc73cde1.mov

**Comment by Evil-GitHub** [comment]
ProTable 的 columns 可以渲染不同的组件，那么如果我想要写通过个 json生成页面表单，有没有具体的方案，参照ProTable 的 columns
