### ISSUE TITLE
🐛[BUG]ProTable 中使用  syncToUrl: true,弹出的modal中获取不到最新的url参数

### ISSUE THREAD

**Issue by ananiahfox** [ant-design/pro-components#6019]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProTable 中使用form={{
          syncToUrl: true,
          syncToInitialValues: false
        }} 改变url之后，在弹出的modal中获取不到最新的url参数，需要刷新一下页面才能获取到最新的参数

### 💻 复现代码

![image](https://user-images.githubusercontent.com/41354027/193168946-8bec5061-739c-42c4-a008-648e1adbd724.png)
![image](https://user-images.githubusercontent.com/41354027/193169114-59901f45-a9f6-4e34-83ba-ebed82b9531d.png)
![image](https://user-images.githubusercontent.com/41354027/193169207-fbbfe953-e4c1-4a20-a15a-ee926271b238.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]
"@ant-design/pro-components": "^2.0.0",
 "@umijs/route-utils": "^2.1.3",
    "antd": "^4.20.0",
 "react-dom": "^17.0.0",
"react": "^17.0.0",
"@umijs/fabric": "^2.11.1",
    "@umijs/max": "^4.0.0-rc.22",
    "@umijs/openapi": "^1.3.0",
我是在https://pro.ant.design/zh-CN中下载的antd pro的代码 测试的，我们zhi qian之前的项目也有这个问题

https://user-images.githubusercontent.com/41354027/193169375-9035e1bf-73e6-4fbf-b706-0e373ecad1a0.mov

**Comment by chenshuai2144** [comment]
只有在第一次渲染的时候才会去拿，如果你需要每次是最新的，要把表格先销毁一下然后重建一下
