### ISSUE TITLE
Drawer 里面使用Tree，如果用ProTable进行弹窗，则Tree没方法进行不同切换渲染，每次都是第一次的记录

### ISSUE THREAD

**Issue by huanghaifen** [ant-design/pro-components#6020]
### What problem does this feature solve?

Drawer 里面使用Tree，如果用ProTable进行弹窗，则Tree没方法进行不同切换渲染，每次都是第一次的记录

### What does the proposed API look like?

Drawer 里面使用Tree，如果用ProTable进行弹窗，则Tree没方法进行不同切换渲染，每次都是第一次的记录

**Comment by kiner-tang** [comment]
可以在`https://codesandbox.io/`当中提供一下复现代码吗？
