### ISSUE TITLE
👑 [需求]onFinish无论return什么，有没有return，配置了destoryOnClose都会重置表单。

### ISSUE THREAD

**Issue by ChrisZyy3** [ant-design/pro-components#6021]
### 🥰 需求描述

<html>
<body>

onFinish ： 提交数据时触发，如果返回一个 true。会关掉抽屉,如果配置了 destroyOnClose 还会重置表单
onFinish无论return什么，有没有return都会重置。
常理来说接口请求失败（比如后端校验没通过）的时候不想要关闭这个ModalForm，会继续留在当前Modal并且填写的表单都留存。但是如果配置了destroyOnClose的话，表单内容就重置掉了，但是因为表单提交失败了就没有return true，表单却没有关掉就很奇怪。不知道是bug还是文档没写清楚导致理解差异

</body>
</html>

### 🧐 解决方案

最好是即使配置了destoryOnClose为true，return true的时候销毁表单+关闭表单，没有return true也不会重置这个表单内容也不会关闭表单。

**Comment by kiner-tang** [comment]
- #6009 
已经在这一次`PR`当中，将重置表单的逻辑放到浮层表单关闭后才执行，你可以看看是否能够满足你的需求

**Comment by ChrisZyy3** [comment]
> * [feat(form): 修复 ModalForm 和 DrawerForm 关闭过程中表单内容闪现初始值的问题 #6009](https://github.com/ant-design/pro-components/pull/6009)
>   已经在这一次`PR`当中，将重置表单的逻辑放到浮层表单关闭后才执行，你可以看看是否能够满足你的需求

感谢，请问下这个是在哪个版本修复？我可以通过npm install @ant-design/pro-components来更新吗，现在的班本是1.1.21。顺便问下v2升级了哪些？

**Comment by kiner-tang** [comment]
> > * [feat(form): 修复 ModalForm 和 DrawerForm 关闭过程中表单内容闪现初始值的问题 #6009](https://github.com/ant-design/pro-components/pull/6009)
> >   已经在这一次`PR`当中，将重置表单的逻辑放到浮层表单关闭后才执行，你可以看看是否能够满足你的需求
> 
> 感谢，请问下这个是在哪个版本修复？我可以通过npm install @ant-design/pro-components来更新吗，现在的班本是1.1.21。顺便问下v2升级了哪些？

@chenshuai2144 我们的版本更新计划是怎样的，有地方可以看吗？

**Comment by kiner-tang** [comment]
> > * [feat(form): 修复 ModalForm 和 DrawerForm 关闭过程中表单内容闪现初始值的问题 #6009](https://github.com/ant-design/pro-components/pull/6009)
> >   已经在这一次`PR`当中，将重置表单的逻辑放到浮层表单关闭后才执行，你可以看看是否能够满足你的需求
> 
> 感谢，请问下这个是在哪个版本修复？我可以通过npm install @ant-design/pro-components来更新吗，现在的班本是1.1.21。顺便问下v2升级了哪些？

@ChrisZyy3 看更新日志已经发布了，你安装这个版本看看
<img width="961" alt="image" src="https://user-images.githubusercontent.com/10286961/195236882-3905d1e6-e650-488e-9daa-860d5e0786dc.png">

**Comment by ChrisZyy3** [comment]
> > > * [feat(form): 修复 ModalForm 和 DrawerForm 关闭过程中表单内容闪现初始值的问题 #6009](https://github.com/ant-design/pro-components/pull/6009)
> > >   已经在这一次`PR`当中，将重置表单的逻辑放到浮层表单关闭后才执行，你可以看看是否能够满足你的需求
> > 
> > 
> > 感谢，请问下这个是在哪个版本修复？我可以通过npm install @ant-design/pro-components来更新吗，现在的班本是1.1.21。顺便问下v2升级了哪些？
> 
> @ChrisZyy3 看更新日志已经发布了，你安装这个版本看看 <img alt="image" width="961" src="https://user-images.githubusercontent.com/10286961/195236882-3905d1e6-e650-488e-9daa-860d5e0786dc.png">

感谢，想问下从v1到v2有什么版本大更新吗？我在文档上都没有找到v2的release note之类的，担心会有break change，所以不是太敢升级到v2

**Comment by cangsnage** [comment]
> ### 🔩 所属模块或组件 ModalForm 和 DrawerForm
> ### 🥰 需求描述
> onFinish ： 提交数据时触发，如果返回一个 true。会关掉抽屉,如果配置了 destroyOnClose 还会重置表单 onFinish无论return什么，有没有return都会重置。 常理来说接口请求失败（比如后端校验没通过）的时候不想要关闭这个ModalForm，会继续留在当前Modal并且填写的表单都留存。但是如果配置了destroyOnClose的话，表单内容就重置掉了，但是因为表单提交失败了就没有return true，表单却没有关掉就很奇怪。不知道是bug还是文档没写清楚导致理解差异
> 
> ### 🧐 解决方案
> 最好是即使配置了destoryOnClose为true，return true的时候销毁表单+关闭表单，没有return true也不会重置这个表单内容也不会关闭表单。
> 
> ### 🚑 其他信息

想问下楼上这个怎么解决的呢，我这边如果没有return 提交按钮一直在加载中
