### ISSUE TITLE
🐛[BUG] pro-layout将route.routes改为route.children未兼容wrapper的场景

### ISSUE THREAD

**Issue by wkeylin** [ant-design/pro-components#6022]
### 🐛 bug 描述

pro-layout最近的改动将route.routes改为route.children，无wrapper情况下没问题，但是有wrapper之后，children会比routes多一层wrapper, 导致过滤菜单的时候wrapper没有name被过滤，导致有wrapper的菜单无法展示
### 🏞 期望结果
有wrapper的菜单正常展示

### © 版本信息

- ProComponents 版本: 2.3.13
- umi 版本: 4.0.24
- 浏览器环境: Edge
- 开发环境 mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/21221921/193201349-59d4f8bf-983e-46c4-af45-5884ed70bcd9.png)

<img width="709" alt="image" src="https://user-images.githubusercontent.com/21221921/193201520-e979177d-f23e-4714-805a-d47cacff0cd5.png">

**Comment by chenshuai2144** [comment]
umi 会解决的

**Comment by chenshuai2144** [comment]
fixed, try again
