### ISSUE TITLE
🧐[问题]请问ProLayout的导航栏怎么修改height，以前版本有个headerHeight属性，升级新版没了

### ISSUE THREAD

**Issue by fireworksflyaway** [ant-design/pro-components#6023]
如题，以前项目用的是"@ant-design/pro-layout": "^6.34.6",这个版本，最近整体升级umi4，升级了"@ant-design/pro-components": "^2.3.13",这个版本，发现headerHeight这个属性没有了，请问有什么替代方法吗，为什么要取消这个啊，我看siderWidth还在呢

**Comment by Teeoo** [comment]
```js
token:{
  header:{
    heightLayoutHeader:48
  }
}
```

**Comment by fireworksflyaway** [comment]
> ```js
> token:{
>   header:{
>     heightLayoutHeader:48
>   }
> }
> ```

感谢，请问这些token从哪里可以查到，我看pro-components官网里面没有这个heightLayoutHeader啊

**Comment by Teeoo** [comment]
一般在d.ts或者interface & type里都能看到

**Comment by ONLY-yours** [comment]
大部分 token 有写 https://procomponents.ant.design/components/layout#token
没放出来估计是不常用，或者不建议改写的，d.ts 里面能看得到
