### ISSUE TITLE
🧐[问题]我想要控制pagination

### ISSUE THREAD

**Issue by zhugexinxin** [ant-design/pro-components#6025]
### 🧐 问题描述
需求很简单，就是想要自己通过state控制pagination的current，但是奇怪是我将current设置为2，刷新页面，页数就会被重置为1。
业务场景很简单，我将current记录在了url上，用户刷新还停留在该页。
目前测试过来我似乎无法完全控制pagination
似乎组件内部在某种情况会强制回到第一页，我查看了下源码并没有找到，或者告知下在哪里。

### 💻 示例代码
https://codesandbox.io/s/cha-xun-biao-ge-forked-lfgwfh?file=/App.tsx
demo里我已经写死了current=2还是回到了1

经过仔细排查总结:
1. 利用state存pagination信息，每次setPagination都会多发起一次请求，这个看了源码似乎每次set都会重新发起

2. 利用props或者在初始state的pagination信息，即使写死，第一次也不会选择到正确的current.

**Comment by zhugexinxin** [comment]
似乎这里执行了action.setPageInfo，更改了PageInfo
![image](https://user-images.githubusercontent.com/42615243/193438897-5e2e17f1-9ba8-4706-9935-ee34bd36c012.png)

但是这里拿到PageInfo还是老的？
![image](https://user-images.githubusercontent.com/42615243/193438922-612c77e1-e011-4866-aff5-38b05d2b2e0e.png)

**Comment by wenlittleoil** [comment]
跟你遇到了相似的问题，因为manualRequest默认为false，自动请求模式下，pagination的onChange每次初始化时都会自动被调用一次，将current强制重置为1，导致无法在业务层控制分页参数。我是用ProTable内置方法来调整分页参数的，例如：
```
    actionRef.current?.setPageInfo?.({
      current: 2, // 你想设置的页码
      pageSize: 10, // 你想设置的页面数据条数
    });
```
