### ISSUE TITLE
🐛[BUG] Summary row didn't scroll correctly, overlap other column

### ISSUE THREAD

**Issue by doiya46** [ant-design/pro-components#6027]
### 🐛 bug 描述

Summary row didn't scroll correctly, overlap other column

![Peek 2022-10-04 15-56](https://user-images.githubusercontent.com/61301244/193778187-ed3c846a-6011-4108-a54e-ec9ba2eee7fb.gif)

### 📷 复现步骤
Resize view area width: 800px 

Demo codesandbox: https://codesandbox.io/s/demo-ant-pro-table-qfltps?file=/Demo.tsx

### 🏞 期望结果

Summary row cell scroll correctly, don't overlap other column.

### © 版本信息

Ubuntu 20.04 / codesandbox

```
"dependencies": {
    "@ant-design/icons": "4.7.0",
    "@ant-design/pro-components": "2.3.13",
    "antd": ">=4.20.0",
    "react": ">=16.9.0",
    "react-dom": ">=16.9.0"
  },
```

**Comment by Zeng-J** [comment]
man,I guess there's something wrong with your code
![image](https://user-images.githubusercontent.com/48742371/196078143-cc588bc9-ad7b-4dfb-b483-64346977d2fb.png)
Correct demo: https://codesandbox.io/s/demo-ant-pro-table-forked-37lr7h?file=/Demo.tsx
