### ISSUE TITLE
Can you support bottom menu option?

### ISSUE THREAD

**Issue by veeramarni** [ant-design/pro-components#6028]
Is it possible if we can get some options to add a bottom menu as you see below? 

Below design

![image](https://user-images.githubusercontent.com/3382355/194337085-93013ad1-928c-495a-99be-3effc695e9e8.png)

**Comment by chenshuai2144** [comment]
you can user menuFooterRender

| menuFooterRender | Render a block at the bottom of the layout | `(menuProps)=>ReactNode` | - |
