### ISSUE TITLE
👑 [需求] Protable 的 column的valueType 为 index，序号不会累加，而是每一页都是从1开始。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-components#603]
### 🥰 需求描述
Protable 的 column的valueType 为 index，序号不会累加，而是每一页都是从1开始。

### 🧐 解决方案

应该支持序号累加。比如第一页是 1-20 ，第二页则是21-40.
### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
自己实现一下吧，这是我们的设计
