### ISSUE TITLE
🐛[BUG] 给二级路由配置上wrappers后，菜单中没有渲染该路由

### ISSUE THREAD

**Issue by qq79952008** [ant-design/pro-components#6032]
## 问题描述
在二级路由中配置上wrappers属性后，菜单无法渲染该路由

![image](https://user-images.githubusercontent.com/29473553/193230083-428bedd3-41e0-4d0c-9978-59198b3f41d2.png)
![image](https://user-images.githubusercontent.com/29473553/193230150-b3dca577-c32d-4560-8943-4085a4c7058b.png)
![image](https://user-images.githubusercontent.com/29473553/193230310-962eec4a-cc3f-4aa9-ae5d-00c38affef70.png)

## 复现代码
https://github.com/qq79952008/umi-wrapper-test

**Comment by chenshuai2144** [comment]
fixed, try again
