### ISSUE TITLE
🧐[问题]defaultSettings配置主题颜色失效

### ISSUE THREAD

**Issue by ByYogi** [ant-design/pro-components#6035]
### 🧐 问题描述
关系版本：@ant-design/pro-components 2.3.13。
问题场景：我在 `defaultSettings.ts` 配置文件中修改了主题色 `colorPrimary: '#FAAD14'`
    当我去除 `SettingDrawer ` 主题组件按钮后，配置的 `colorPrimary` 主题色就会失效

![definedColor](https://user-images.githubusercontent.com/111735598/194695080-9d799e16-aa25-4b87-a9c2-fb9debbf4364.png)

![codeComment](https://user-images.githubusercontent.com/111735598/194695082-563fef01-620c-4024-aa17-fc23d1d7ca27.png)

**Comment by chenshuai2144** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/8186664/194751844-740d6507-e22e-4e7a-b2d6-4c88452da9de.png">


```
  mfsu: false,
  theme: {
    'root-entry-name': 'variable',
  },
```

记得配置一下

**Comment by ByYogi** [comment]
> <img alt="image" width="603" src="https://user-images.githubusercontent.com/8186664/194751844-740d6507-e22e-4e7a-b2d6-4c88452da9de.png">
> 
> ```
>   mfsu: false,
>   theme: {
>     'root-entry-name': 'variable',
>   },
> ```
> 
> 记得配置一下

配置了，无效

**Comment by ByYogi** [comment]
相关issue: 
[#9768 ](https://github.com/ant-design/ant-design-pro/issues/9768)
[#9608](https://github.com/ant-design/ant-design-pro/issues/9608)

打包了那个`SettingDrawer`组件还留着
最终·解决方案，放弃自定义主题
