### ISSUE TITLE
🧐[问题]ProTable 搜索区域配置showSearch过滤后鼠标hover选项为什么无效果呢？

### ISSUE THREAD

**Issue by fei199225** [ant-design/pro-components#6036]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

使用ProTable，搜索区域尝试将某一项下拉单选框showSearch: true，发现单选框搜索之前鼠标hover选项是有展示效果的，但搜索后鼠标hover就没有反应了。（使用复选mode: 'multiple'是没有这个问题的），请问是我缺少配置或使用方式不对，还是说确实是不支持呢？
配置代码：
   ```
 {
      title: '模板名称',
      dataIndex: 'templateName',
      hideInTable: true,
      fieldProps: {
        showSearch: true,
      },
      valueEnum: () => {
        let obj = {}
        templateNames.forEach((item: any) => {
          obj[item] = {text: item}
        })
        return obj
      },
    },
```
注：mode: 'multiple', // 不会有这个问题

### 🚑 其他信息

未搜索前hover有效果：
![截屏2022-10-08 下午6 40 03](https://user-images.githubusercontent.com/11814691/194703464-9904d6ed-5700-48b3-8b07-afa1d338c3eb.png)
搜索后hover无效果：
![截屏2022-10-08 下午6 41 25](https://user-images.githubusercontent.com/11814691/194703528-0798e26d-b9ec-41e1-ba07-1c1db92becd2.png)

**Comment by chenshuai2144** [comment]
算个bug吧，hhh 因为 title 没有了
