### ISSUE TITLE
🐛[BUG] PageContainer 标题和面包屑无法关联，ghost属性不生效

### ISSUE THREAD

**Issue by 569202812** [ant-design/pro-components#6039]
### 🐛 bug 描述

`umi`3.0版本使用`PageContainer`标题和面包屑无法关联,并且设置`ghost`不生效

### 🏞 期望结果
`PageContainer`标题和面包屑关联,并且设置`ghost`生效

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] 2.3.13
- umi 版本 3.5.20
- 浏览器环境 chorme
- 开发环境 [e.g. mac OS] win

**Comment by chenshuai2144** [comment]
详细描述一下？，没有听懂是什么意思

**Comment by 569202812** [comment]
> 详细描述一下？，没有听懂是什么意思

我路由设置了name，`PageContainer`的`title`和`breadcrumb`都不自动生成了，之前的6.0的`layout`版本是可以的

![image](https://user-images.githubusercontent.com/34082148/194746421-f6206044-dce8-4867-9114-2ab0912cc8c5.png)

开发环境的效果

![image](https://user-images.githubusercontent.com/34082148/194746528-658975c1-6bc8-4bd3-a4dd-97b163a559c9.png)

线上的效果
![image](https://user-images.githubusercontent.com/34082148/194746561-2fe01e3b-572e-4a03-8077-3e1dbd918b0f.png)

**Comment by 569202812** [comment]
> PageContainer

`ghost`的问题就是无论是否设置都有`ant-pro-page-container-ghost`这个样式，我看源码是直接写死了

**Comment by hqwlkj** [comment]
> > PageContainer
> 
> `ghost`的问题就是无论是否设置都有`ant-pro-page-container-ghost`这个样式，我看源码是直接写死了

目前是存在这个问题，如果需要急用可以设置  PageContainer 中的 header 属性， 如下：

```tsx
<PageContainer
      header={{
        ghost: false,
      }}
    >你的内容</PageContainer>
```

**Comment by 569202812** [comment]
> > > PageContainer
> > 
> > 
> > `ghost`的问题就是无论是否设置都有`ant-pro-page-container-ghost`这个样式，我看源码是直接写死了
> 
> 目前是存在这个问题，如果需要急用可以设置 PageContainer 中的 header 属性， 如下：
> 
> ```tsx
> <PageContainer
>       header={{
>         ghost: false,
>       }}
>     >你的内容</PageContainer>
> ```

这个我直接先用样式覆盖掉了

**Comment by ksh033** [comment]
`  const pageHeaderDom = memoRenderPageHeader({
    ...restProps,
    breadcrumbRender: memoBreadcrumbRender,
    ghost: true,
    hashId,
    prefixCls: undefined,
    prefixedClassName: basePageContainer,
    value,
  });
`
ghost快已经被写死了

**Comment by 569202812** [comment]
> 

是的我也看到了

**Comment by 569202812** [comment]
> > 详细描述一下？，没有听懂是什么意思
> 
> 我路由设置了name，`PageContainer`的`title`和`breadcrumb`都不自动生成了，之前的6.0的`layout`版本是可以的
> 
> ![image](https://user-images.githubusercontent.com/34082148/194746421-f6206044-dce8-4867-9114-2ab0912cc8c5.png)
> 
> 开发环境的效果
> 
> ![image](https://user-images.githubusercontent.com/34082148/194746528-658975c1-6bc8-4bd3-a4dd-97b163a559c9.png)
> 
> 线上的效果 ![image](https://user-images.githubusercontent.com/34082148/194746561-2fe01e3b-572e-4a03-8077-3e1dbd918b0f.png)

@chenshuai2144 麻烦帮忙看下这个问题

**Comment by panhezeng** [comment]
ghost 没了，设置为真也不行了，样式都乱套了，升级后

**Comment by 569202812** [comment]
> ghost 没了，设置为真也不行了，样式都乱套了，升级后

是的rightContentRender没了我看着

**Comment by panhezeng** [comment]
锁定到2.3.13了，之后的版本，样式大变样，等你们稳定下来再说吧，我都不知道是你们估计改了样式，还是出了bug

**Comment by chenshuai2144** [comment]
这种情况一般是项目中有两份layout实例 你检查下是不是安了两个layout

**Comment by 569202812** [comment]
> 这种情况一般是项目中有两份layout实例 你检查下是不是安了两个layout

哦哦好的，是不是umi3.0还需要单独安装pro-layout不能只安装pro-compoents

**Comment by chenshuai2144** [comment]
umi3.0 应该都切成 pro-compoents了，可以用  npm ls 包名看看

**Comment by panhezeng** [comment]
![image](https://user-images.githubusercontent.com/354878/195557783-e5372d74-28c7-4c26-b232-c47c92bdc78d.png)

**Comment by 569202812** [comment]
> umi3.0 应该都切成 pro-compoents了，可以用 npm ls 包名看看

我删了pro-layout的依赖后，运行还是让添加pro-layout的依赖的

**Comment by 569202812** [comment]
> 我使用的 umi 4 ，只装了 pro-compoents ，ghost 没了，设置为真也不行了，样式都乱套了，升级后

是的 ghost  不生效了 我用样式覆盖的
