### ISSUE TITLE
👑 [需求]proTable的search input可以加下清除按钮吗，其他search组件默认是有的，还有就是可以加一个配置吗隐藏lable

### ISSUE THREAD

**Issue by David2k13** [ant-design/pro-components#604]
### 🥰 需求描述

proTable的search input可以加下清除按钮吗，其他search组件默认是有的，还有就是可以加一个配置吗隐藏lable，然后再placeholder来显示label描述。

**Comment by chenshuai2144** [comment]
来个截图

**Comment by David2k13** [comment]
> 来个截图

![image](https://user-images.githubusercontent.com/22017991/94383481-c3ee3580-0172-11eb-81e1-7c7c5c97c02b.png)
