### ISSUE TITLE
🧐[问题]pro-layout layout='side' 怎么把头像放到右上角

### ISSUE THREAD

**Issue by mwj610** [ant-design/pro-components#6044]
### 🧐 问题描述

pro-layout layout='side' 怎么把头像放到右上角

![image](https://user-images.githubusercontent.com/52907799/194767359-58ddda74-1c50-431b-87ab-397d49202708.png)

**Comment by Teeoo** [comment]
文档不是写了么`layout 的头像设置，不同的 layout 放在不同的位置`觉得不好用的话就直接上`rightContentRender`自定义

**Comment by mwj610** [comment]
> 文档不是写了么`layout 的头像设置，不同的 layout 放在不同的位置`觉得不好用的话就直接上`rightContentRender`自定义

pro-layout 7.0 之后  layout='side'时候headerRender不起作用了

**Comment by chenshuai2144** [comment]
side 不支持header了，要放到上面可以用 mix 模式

**Comment by mwj610** [comment]
> 
那layout='side'时候有什么办法可以加个header吗

**Comment by Teeoo** [comment]
> side 不支持header了，要放到上面可以用 mix 模式

mix 模式下 avatarProps 和 actionsRender 均无效 @chenshuai2144 

#4933

**Comment by harrisyangbo** [comment]
layout='side'时候 根本无法搞右侧的header，这次更新真是败笔

**Comment by YuPengZhangL** [comment]
覆盖原本布局的css样式就行～
.ant-pro-sider-actions {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-block: 4px;
  margin-inline: 0;
  color: #7a80b4;
  position: fixed;
  top: 10px;
  right: 30px;
  z-index: 1000;
}

**Comment by 985563349** [comment]
有一个比较hack的方案，在 layout plugins 运行时配置中，设置 rightContentRender: () => <></>, childrenRender: (children) => <><Header />{children}</>。这样你可以自定义Header组件。
