### ISSUE TITLE
🐛[BUG] 文档中的所有 CodesandBox 示例没有配置好环境，不能正常浏览

### ISSUE THREAD

**Issue by ByYogi** [ant-design/pro-components#6049]
![Snipaste_2022-10-10_15-52-59](https://user-images.githubusercontent.com/111735598/194820647-b379ccd0-740c-404b-b030-4944b8ee9238.png)
![Snipaste_2022-10-10_15-57-36](https://user-images.githubusercontent.com/111735598/194821316-ab8b8c2f-88cc-4f7d-85ef-b34eccacb639.png)

**Comment by panhezeng** [comment]
+1

**Comment by xiaohp** [comment]
+1

**Comment by tianyuan233** [comment]
看了一下 umi的改动记录 最新的版本移除了`injectReact`https://github.com/umijs/dumi/pull/1206

另外 这些组件比如pro-card 的依赖中 react 的版本是 `"react": ">=16.9.0"`所以生成的codesandbox中的react依赖也是`"react": ">=16.9.0"`,严格来讲 这里其实不是 dumi 的问题而是 如果用了react16.x的版本 那你的demo代码中就应该自己包含 
```jsx
import React from 'react'
```
@chenshuai2144

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


很抱歉这个问题对您带来的不便，可能是由于环境配置的问题导致 CodesandBox 示例无法正常浏览。以下是一些可能的解决方案：

1. 确认您的浏览器是否支持 CodesandBox，在浏览器中按 F12 打开控制台查看是否有报错信息，如果是，则可以参考报错信息进行调试和解决。

2. 确认您的浏览器是否启用了 JavaScript，如果没有启用 JavaScript，请在浏览器中启用它。

3. 可以考虑更换浏览器，推荐使用最新版的 Google Chrome 或 Firefox 浏览器。

4. 如果您已经尝试了以上方法仍然无法解决问题，可以参考以下教程手动配置 CodesandBox 的环境：

   1. 下载项目代码，在本地环境中安装 React 和相关依赖。

   2. 打开代码中的 `src` 目录，查看当前示例的入口文件（通常为 `index.js` 或 `App.js`）。

   3. 将入口文件复制到 CodesandBox 中的 `index.js` 文件中。

   4. 打开 CodesandBox 终端并安装 React 和相关依赖：

   ```shell
   npm install react react-dom
   ```

   5. 运行代码：

   ```shell
   npm start
   ```

   6. 在 CodesandBox 中查看代码是否正常运行。

希望以上方案能够解决您的问题。如果还有其他问题或疑问，可以在该 issue 下进行补充或重新开一个 issue。
