### ISSUE TITLE
👑 [需求] PageContainer 多tab场景时，可否增加url同步当前激活的tab项，有很多场景需要同url跳转到指定页面指定的tab

### ISSUE THREAD

**Issue by jeryqwq** [ant-design/pro-components#6051]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩  PageContainer
率属组件：PageContainer

### 🥰 需求描述
PageContainer下的tab项状态与url查询参数同步，方便分享和跳转指定tab

### ⛰ 功能需求适用场景

当前我有多个tab，当我需要分享某个tab时，能够复制url给别人，别人通过url跳转进来制定的tab项

### 🧐 解决方案
状态保存到url查询参数中，这样分享就会把查询参数带上type=key1，当其他用户这样进入时，读取key1后再次进入分享的tab

### API:
isUrlState: 是否开启url状态同步， 默认type为当前tab的key
urlKey： 当type与当前业务冲突时，可自定义字符串， 例如： type2, 就会在路由写入type2="key2"

### 🚑 其他信息

demo地址: https://jeryqwq.github.io/build-docs/#/~demos/Workspace-demo-4?type=dashboard2

**Comment by lovewinders** [comment]
+1

**Comment by jeryqwq** [comment]
@lovewinders  手动使用ahooks的[useUrlState](https://ahooks.js.org/zh-CN/hooks/use-url-state/)去兼容吧，我们是重写了个，刚好布局和PageContainer不一致
