### ISSUE TITLE
🐛[BUG] ConfigProviderWrap组件导致子组件重新渲染

### ISSUE THREAD

**Issue by xblj** [ant-design/pro-components#6054]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

使用`@ant-design/pro-provider`的`ConfigProviderWrap`组件，父组件每次重新渲染都会导致，使用了`useIntl`的子级组件重新渲染 

### 📷 复现步骤

1. 打开console
2. 点击页面的"counter"
3. 控制台会输出 “重新渲染 ”
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/23544997/195012190-c162648a-e42d-4635-8852-76f74fb6e93e.png">

### 🏞 期望结果

不要重新渲染子组件`User`

### 💻 复现代码

https://codesandbox.io/s/pedantic-cray-ucg429?file=/src/App.js

### © 版本信息

-@ant-design/pro-provider 版本: [2.0.5]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/23544997/195012150-4f4d5103-88b8-451b-8643-e401656511ac.png">

**Comment by yqz0203** [comment]
遇到过同样的问题，期待修复。
