### ISSUE TITLE
🐛[BUG] Dark mode is removed from Pro Layout

### ISSUE THREAD

**Issue by arifszn** [ant-design/pro-components#6056]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

`navTheme` and `headerTheme` props are removed in version 7.x.x. No explanation for removing is there on the changelog. Also, can't find any alternative to enable the dark mode.

An undocumented prop type `navTheme` is available but it only adds a drop shadow.
```jsx
<ProLayout navTheme="realDark">HELLO</ProLayout>
```

![image](https://user-images.githubusercontent.com/45073703/195015024-908913db-9e9a-4971-9eb2-205be3b3a9df.png)

In this [commit](https://github.com/ant-design/pro-components/commit/deec835d910fdae853b76a237632463b00e293c8) it's removed.

Version: `"@ant-design/pro-layout": "^7.1.4"`

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by hejinguo** [comment]
navTheme 删除了？

**Comment by arifszn** [comment]
Looks like it from this [commit ](https://github.com/ant-design/pro-components/commit/deec835d910fdae853b76a237632463b00e293c8).

Still, there is a prop definion for `navTheme` but it only adds a drop shadow. In the actual documentation, it is removed also.

![image](https://user-images.githubusercontent.com/45073703/195043060-707c5480-43bf-4256-940e-be8e6babee5e.png)

**Comment by chenshuai2144** [comment]
We recommend using the token method to configure, we have a related demo

**Comment by arifszn** [comment]
@chenshuai2144, i see the `token` can be the alternative for the darkmode. But the problem is it is not dynamic anymore.

```jsx
<ProLayout
   token={{
     bgLayout: darkMode ? '#000' : '#f0f2f5',
   }}
```

Even I changed the darMode state, the bg color remained the same when it was first rendered.

The previous `navTheme` and `headerTheme` were dynamic.

```jsx
<ProLayout
   navTheme={darkMode ? 'dark' : 'light'}
   headerTheme={darkMode ? 'dark' : 'light'}
```

Should I create a separate ticket?
