### ISSUE TITLE
🧐[问题]ProFormText.Password怎样取消密码显示（没有visibilityToggle属性）

### ISSUE THREAD

**Issue by BATTLEHAWK00** [ant-design/pro-components#6060]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

ProFormText.Password 没有visibilityToggle属性？

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/45313304/195062012-7cdeaea4-55a8-4fda-91c3-434342977c2f.png)

**Comment by chenshuai2144** [comment]
直接用 input 框不能解决吗

**Comment by BATTLEHAWK00** [comment]
> 直接用 input 框不能解决吗？

那请问为什么没有在pro组件上保留这个属性呢

**Comment by chenshuai2144** [comment]
要用 fieldProps

**Comment by hehepeng** [comment]
> 
大佬，
![image](https://github.com/ant-design/pro-components/assets/23272117/9206d47a-8528-4601-b894-e2653dc87910)
我这么写还是无法隐藏
