### ISSUE TITLE
【求助】做编辑ProForm 中 ProFormSelect 类型字段 如何同时设置 label, value 值

### ISSUE THREAD

**Issue by jasonwang1109** [ant-design/pro-components#6061]
ProFormSelect 在表单里做一个国家的选择框，每次输入只是显示匹配的30条数据，当form 第一次打开处于编辑状态时，只是设置value=CN，是无法显示china，怎么样让 lable: china 与 value: cn 一起设置到当前的ProFormSelect, 而不触发request.

**Comment by chenshuai2144** [comment]
`lableInValue`吧，然后用 transform 转化一下，这样能保证label 和 value 总是存在也不用找网络请求

**Comment by jasonwang1109** [comment]
> `lableInValue`吧，然后用 transform 转化一下，这样能保证label 和 value 总是存在也不用找网络请求

感谢回复，比如Form数据源是 {companyName:"test",countryCode: 'CN', countryName: 'China'}
select 数据源是[{countryCode: 'CN', countryName: 'China'},{countryCode: 'US', countryName: 'USA'}]
ProFormSelect 应该怎么样用transform ？我自己尝试不行
<ProFormSelect colProps={{ span: 23 }} label="Country Name / Region" name="countryName"
                                fieldProps={{
                                    labelInValue:true,
                                    fieldNames:{label:"countryName", value:"countryCode"}
                                }}

                            />
