### ISSUE TITLE
🐛[BUG] 多级分组表头使用列展示功能报堆栈错误

### ISSUE THREAD

**Issue by Shen120** [ant-design/pro-components#6062]
### 🐛 bug 描述

在使用多级分组表头时，控制列的显隐会出现堆栈错误

### 📷 复现步骤

1. 打开demo
2. 点击右上角列设置
3. 取消勾选 other -> age -> address字段；注意：仅取消address字段

### 🏞 期望结果

正常使用此功能

### 💻 复现代码

[demo地址](https://codesandbox.io/s/cha-xun-biao-ge-forked-u803ey)

### © 版本信息

- ProComponents 版本: 2.3.16
- 浏览器环境 latest
- 开发环境 [e.g. mac OS] windows

### 🚑 其他信息

此示例是官方示例，只是加了分组表头的数据，其余都没改动

**Comment by chenshuai2144** [comment]
给每个 列配置key就不会报错了，你先绕开一下
