### ISSUE TITLE
🐛[BUG] protable自定义render，导致copyable无效。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-components#6063]
### 🐛 bug 描述

自定义protable的render 导致copyable无效。因为有可能要对data 的某个字段进行字符传拼接之后再显示，但是内容又要可以复制，导致不能被复制。

### 📷 复现步骤
column 的copyable设置为true，并且重写render
```
  {
    title: "标题不能复制",
    dataIndex: "title",
    key: "title2",
    copyable: true,
    ellipsis: true,
    tip: "标题不能复制",
    render: (value, record) => {
      return `${record.title}____123131`;
    }
  }
```

### 🏞 期望结果

应该可以被复制。

### 💻 复现代码

https://codesandbox.io/s/cha-xun-biao-ge-forked-8iuo25?file=/App.tsx

### © 版本信息

  "dependencies": {
    "@ant-design/icons": "4.6.4",
    "@ant-design/pro-table": "2.80.3",
    "antd": "4.x",
    "react": ">=16.9.0",
    "react-dom": ">=16.9.0",
    "umi-request": "1.4.0"
  },

- 浏览器环境 chrome 
- 开发环境 windows
![image](https://user-images.githubusercontent.com/8272614/195244072-748df8c9-fc6a-4c4b-909f-5d598369b22a.png)

**Comment by amin168** [comment]
其实你可以自己用 `Typography` 渲染做复制，或者可以类型下面的做法
```
{
    title: "标题不能复制",
    dataIndex: "title",
    key: "title2",
    copyable: true,
    ellipsis: true,
    tip: "标题不能复制",
    render: (dom, record) => {
	return <div>
		// 这个dom里面，就包含 copy 了
		{dom}

		// 这里可以自定义其他渲染
		.......
	</div>
    }
  }
```

**Comment by xgj1988** [comment]
@amin168  这种方法当然可以。。只是对原来的设计，就增加了使用的不确定性，API就不够职责单一，，导致API的学习成本增加，一般正常看API，都会觉得我那么写应该没问题。

**Comment by amin168** [comment]
这里设计我觉得是没有问题的，因为实际需要复制内容是不确定的，特别复杂的，还需要你自己指定。

比如如果你自定义的 `render` 里面是由两个或者多个字段组成，但是你只需要 `copy` 其中的订单号字段，你提到的情况，就不适用了

**Comment by xgj1988** [comment]
@amin168  谢谢。。看来我先自己封装一个render了。

**Comment by TangMonk** [comment]
same problem， 这个需求其实挺强烈的
