### ISSUE TITLE
🐛[BUG] copyable 样式丢失

### ISSUE THREAD

**Issue by sarufarr** [ant-design/pro-components#6066]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

至少 `pro-table` 中的 `copyable` 组件样式丢失

### © 版本信息

    "@ant-design/pro-components": "^2.3.16"
    "antd": "4.23.5"
    "vite": "3.2.0-beta.1"

**Comment by leonardo110** [comment]
问题解决了么？我的4.17版本也无法出现 复制  的图标样式了
