### ISSUE TITLE
🐛[BUG]国际化有问题

### ISSUE THREAD

**Issue by lklslkla** [ant-design/pro-components#607]
加入这个
```
<ConfigProvider locale={antd.locales.zh_CN}>
 </ConfigProvider>后
```
下边分页的国际化实现了,但是搜索框,日期还是英文

**Comment by chenshuai2144** [comment]
你的脚手架是什么？

**Comment by lklslkla** [comment]
> 你的脚手架是什么？

我直接在项目里用的antd-with-locales.min.js和table.min.js 用到的是ProTable这个,自动生成的搜索框里的日期不显示为中文,下边的分页什么的都没有问题
<img width="791" alt="微信截图_20201009094917" src="https://user-images.githubusercontent.com/20960539/95533044-b5c2d380-0a14-11eb-83ff-8c9edac0134e.png">

**Comment by lklslkla** [comment]
官网的例子 也没有见到 日期国际化成功的 也没这块儿说明 国际化那块儿的那个例子,别的都没问题,但是日期有问题,不确定是不是不支持日期中文啊

**Comment by chenshuai2144** [comment]
@lklslkla  日期是写死的，不支持国际化
