### ISSUE TITLE
模块“"@ant-design/pro-components"”没有导出的成员“ProTable”。

### ISSUE THREAD

**Issue by jiangkaifree** [ant-design/pro-components#6070]
使用 antd pro 创建的ts项目，并不能很好的识别 ProComponents  中的导出项. ，导致爆红色警告。并没有找到解决方法，

![image](https://user-images.githubusercontent.com/50451924/195558141-d202e87a-8555-4760-98e9-1e02d8d2c90f.png)

![image](https://user-images.githubusercontent.com/50451924/195559266-9d13a999-c713-4bde-b493-e3ad0a578a3c.png)

下面是我的 依赖版本
```json
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^2.3.13",
    "@umijs/max": "^4.0.24",
    "antd": "^4.20.7"
```

**Comment by drizzlesconsin** [comment]
这种情况重新 `yarn install` 一遍，重启编辑器。一个解法不一定对你有效，但可以试试。

**Comment by chenshuai2144** [comment]
一般都是安装没有成功，删除重装吧
