### ISSUE TITLE
调用 ProFormSegmented 抛出 allowClear 属性拼写错误

### ISSUE THREAD

**Issue by dreammaker7** [ant-design/pro-components#6075]
### 🐛 bug 描述

引入 ProFormSegmented 组件并使用，控制台抛出 allowClear 属性拼写错误告警。

### 📷 复现步骤

ModalForm 中使用 ProFormSegmented 组件

### 💻 复现代码

https://codesandbox.io/s/gu-ding-ye-jiao-forked-4s112u?file=/App.tsx

### © 版本信息

- ProComponents 版本: 2.3.14
- umi 版本
- 浏览器环境 Chrome
- 开发环境 [e.g. windows]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/74588098/195789189-1841820e-0ab0-4cda-b1cb-4c382b1c9670.png)

**Comment by chenshuai2144** [comment]
fixed in 2.3.20
