### ISSUE TITLE
🐛[BUG]valueType: 'money'

### ISSUE THREAD

**Issue by WT-Road** [ant-design/pro-components#6079]
### 🐛 bug 描述

如果是负数,则显示正数,期望能正常显示为负数的金额

### 📷 复现步骤

金额是正数时,没问题,-1000时,则显示为1000

### 💻 复现代码

valueType: 'money',
      fieldProps: {
        moneySymbol: false,
      },

### © 版本信息

- ProComponents 版本: [e.g. 2.3.18]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kiner-tang** [comment]
我看看
