### ISSUE TITLE
🐛[BUG] layout token sider colorTextMenu 未生效

### ISSUE THREAD

**Issue by sushi-su** [ant-design/pro-components#6082]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/50985188/196071522-326e1d18-f3b9-411e-b26e-385802d3c01c.png)

### 📷 复现步骤

官方文档中的 [通过 token 修改样式](https://procomponents.ant.design/components/layout/#%E9%80%9A%E8%BF%87-token-%E4%BF%AE%E6%94%B9%E6%A0%B7%E5%BC%8F) 示例

### 🏞 期望结果

colorTextMenu: 'rgba(255,255,255,0.75)'

**Comment by chenshuai2144** [comment]
fixed, try again
