### ISSUE TITLE
🐛[BUG] Layout's token is not dynamic

### ISSUE THREAD

**Issue by arifszn** [ant-design/pro-components#6083]
### 🐛 bug 描述

`navTheme` and `headerTheme` were removed and as a replacement `token` can be used to achieve dark mode.

But the problem is it is not dynamic anymore.

```jsx
const [darkMode, setDarkMode] = useState(false);

<ProLayout
   token={{
     bgLayout: darkMode ? '#000' : '#f0f2f5',
   }}
```

Even I changed the darMode state, the bg color remained the same when it was first rendered.

The previous `navTheme` and `headerTheme` were dynamic.

```jsx
<ProLayout
   navTheme={darkMode ? 'dark' : 'light'}
   headerTheme={darkMode ? 'dark' : 'light'}
```

For this issue, I am not able to use custom dark mode switch. A working version with `@ant-design/pro-layout v6` can be found [here](https://arifszn.github.io). With v7, I can't replicate the same functionality even with token. 

Related comment: https://github.com/ant-design/pro-components/issues/6056#issuecomment-1278520925

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
fixed, try again

**Comment by iFonny** [comment]
It doesn't work anymore in `[3.1.0-0](https://www.npmjs.com/package/@ant-design/pro-components/v/3.1.0-0)` 

Does anyone know of a workaround?
