### ISSUE TITLE
🐛[BUG] ProTable的Column的render中的record会自动带上value和label属性

### ISSUE THREAD

**Issue by Cyan-Xmw** [ant-design/pro-components#6085]
### 🐛 bug ProTable的Column的render中的record会自动带上value和label属性

![image](https://user-images.githubusercontent.com/40554571/196407043-e2111502-c3f4-4a87-ba9f-91d162d7a389.png)

源数据上是没有这两个字段的：
![image](https://user-images.githubusercontent.com/40554571/196407138-18358064-46ca-4631-831f-8263227e1437.png)

### 📷 复现步骤

点击操作栏，编辑回显，formData会自动带上value和label属性，导致我需要手动去除这两个属性

![image](https://user-images.githubusercontent.com/40554571/196407416-d2354920-4f20-4c9a-ac99-8ff171edfb81.png)

我记得之前是不会的，不知道是不是因为更新了版本的原因

### 🏞 期望结果

不要带上这两个字段

### 💻 复现代码

https://github.com/Cyan-Xmw/react-umi-xmw/blob/Cyan/Xmw_web/src/pages/System/Internationalization/components/TableTemplate.tsx)

### © 版本信息

- ProComponents 版本: ^2.3.13
- umi 版本: ^4.0.22
- 浏览器环境: Google
- 开发环境 : Window

**Comment by chenshuai2144** [comment]
搞个重现吧，我没法复现
