### ISSUE TITLE
🐛[BUG]引入样式报错Can't resolve 'antd/es/theme/style'

### ISSUE THREAD

**Issue by RedsMario** [ant-design/pro-components#6087]
### 🐛 bug 描述

我按照antd官网的步骤按需引入了组件和样式，一切都显示正常，但是当我引入ProComponents 后，报错了。
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/76934904/196423327-1fe6c58b-6373-4a33-a104-00dac2afc079.png">

### 📷 复现步骤

1、创建一个react项目，引入第三方插件: 
- craco-antd版本：2.0.0
- @craco/craco版本： 6.4.5
- antd版本：4.2.36
- @ant-design/pro-components版本： 2.3.19

2、在根目录创建craco.config.js文件
```
const CracoAntDesignPlugin = require('craco-antd')
module.exports = {
  plugins: [
    {
      plugin: CracoAntDesignPlugin,
      options: {
        customizeTheme: {
          '@primary-color': '#1DA57A',
        },
      },
    },
  ],
}
```
3、修改package.json
```
  "scripts": {
    "start": "craco start",
    "build": "craco build",
    "test": "craco test",
    "eject": "react-scripts eject"
  }
```
4、在App.tsx中的代码如下：
```
import { Button } from 'antd'
import { ProForm, ProFormText } from '@ant-design/pro-components'
function App() {
  return (
    <div className="App">
      <ProForm
        onFinish={async (values) => {
          console.log(values)
        }}
      >
        <ProFormText name="name" label="姓名" />
      </ProForm>
      <Button type="primary">Button</Button>
    </div>
  )
}

export default App
```

### 💻 复现代码

复现仓库地址: https://github.com/RedsMario/antd-demo.git

### © 版本信息

- ProComponents 版本: [2.3.19]
- antd版本: [4.23.6]
- 浏览器环境 Chrome
- 开发环境 [mac OS]

### 🚑 其他信息
我尝解决了一下，以下两种方法是有效的
1、不按需引入样式，全局引入antd的样式时，它是正常的。
2、修改ProComponents的版本为1.1.24是，它也是正常的。

**Comment by ldwonday** [comment]
遇到同样的问题

**Comment by ldwonday** [comment]
@chenshuai2144 尽快解决下这个问题吧。

**Comment by chenshuai2144** [comment]
配置一个空的alias吧

https://webpack.js.org/configuration/resolve/

**Comment by RedsMario** [comment]
补充下：
修改`craco.config.js`中的`alias`是有效的，如果你使用了`craco-antd`来进行按需导入的话，它默认是从`antd/lib`
目录导入的
```
const CracoAntDesignPlugin = require('craco-antd')
module.exports = {
  webpack: {
    alias: {
      'antd/lib/theme': false,
    },
  },
  plugins: [
    {
      plugin: CracoAntDesignPlugin,
      options: {
        customizeTheme: {
          '@primary-color': '#1DA57A',
        },
      },
    },
  ],
}
```
或者你可以选择这种方式
```
module.exports = {
  webpack: {
    alias: {
      'antd/es/theme': false,
    },
  },
  plugins: [
    {
      plugin: CracoAntDesignPlugin,
      options: {
        customizeTheme: {
          '@primary-color': '#1DA57A',
        },
        babelPluginImportOptions: {
          libraryName: 'antd',
          libraryDirectory: 'es',
          style: true,
        },
      },
    },
  ],
}
```

**Comment by lianer3588** [comment]
这个问题我也遇到了 大佬解决了吗

**Comment by bihongbin3027** [comment]
@Bosaidonio 你好 你解决了吗 我也遇到这个问题了 antd 4.16.13

**Comment by bihongbin3027** [comment]
> @Bosaidonio你好你解决了吗 我也遇到了这个问题 antd 4.16.13

![image](https://github.com/ant-design/pro-components/assets/15045200/d4935995-454a-4db7-975d-f23e167648cb)
