### ISSUE TITLE
🐛[BUG] ProFormTreeSelect 配置 fieldNames 会导致编辑回显时formData会自动带上value和label属性

### ISSUE THREAD

**Issue by Cyan-Xmw** [ant-design/pro-components#6090]
### 🐛ProFormTreeSelect 配置 fieldNames 会导致编辑回显时formData会自动带上value和label属性

问题如标题所示，之前是没问题的，不知道是升级了版本还是咋地

### 📷 复现步骤
1、源数据是没有这两个字段的
![image](https://user-images.githubusercontent.com/40554571/196581751-c55fa2aa-f75c-4e24-baad-b334988f12b9.png)

2、 ProFormTreeSelect 配置字段
![image](https://user-images.githubusercontent.com/40554571/196581862-e53fe705-a5b6-450d-9bbc-68efe7bb9dde.png)

3、传递的formData  回显会带上 value 和 label 属性
![image](https://user-images.githubusercontent.com/40554571/196582022-23d7572d-b285-47b8-9914-6dd83a2828e2.png)

4、去掉这个配置，回显则正常显示，由此可见是 ProFormTreeSelect 组件的问题

### 🏞 期望结果

去掉这两个字段

### 💻 复现代码

https://github.com/Cyan-Xmw/react-umi-xmw/blob/Cyan/Xmw_web/src/pages/System/Internationalization/components/FormTemplateItem.tsx

### © 版本信息

- ProComponents 版本：^2.3.19
- umi 版本：^4.0.22
- 浏览器环境：Google
- 开发环境 ： Window

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好，这个问题可能是 ProFormTreeSelect 的一个 bug，可以试试升级 ProComponents 看看是否能够解决。或者你可以尝试手动设置 defaultValue 来设置初始值，然后在 onChange 回调中获取当前选中的值并更新 formData。示例如下：

```
import ProFormTreeSelect from '@ant-design/pro-form/lib/components/TreeSelect';

const FormTemplateItem = (props: any) => {
  const { field, options, label } = props;

  const handleChange = (value: any, option?: any) => {
    props.onChange && props.onChange(value);
  };

  return (
    <ProForm.Item
      label={label || '未命名字段'}
      name={field}
      rules={[{ required: true, message: `请选择 ${label}` }]}
    >
      <ProFormTreeSelect
        showCheckedStrategy="SHOW_ALL"
        treeData={options || []}
        onChange={handleChange}
        value={props.value}
      />
    </ProForm.Item>
  );
};
``` 

希望这能帮到你！如果还有其他问题可以继续追问。同时你可以参考一下官方文档：https://procomponents.ant.design/components/tree-select。

**Comment by chenshuai2144** [comment]
已经修复了，再试试
