### ISSUE TITLE
👑 [需求]

### ISSUE THREAD

**Issue by SilvaQ** [ant-design/pro-components#6091]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

ProTable

### 🥰 需求描述
ProTable 的 tableAlertOptionRender 现在没有一个控制table 刷新的 action ，不能像 toolBarRender 那样参数中就得到一个 action 实例控制table。 搞得只能定义个 action ref 来达到目的。
如果参数携带一个 action 使得可以控制table ，常规的刷新等操作就得到满足避免少一份 ref.
```jsx
 tableAlertOptionRender={(selectedRowKeys, selectedRows, onCleanSelected,假设我是action) => {
          return (
            <Space size={16}>
              <a
                onClick={(e) => {
                  // some logic code to update data 
                  
                  假设我是action.reloadAndReset(); 方便刷新table
                }}
              >
                批量删除
              </a>
              <a>导出数据</a>
            </Space>
          );
        }}
```

### ⛰ 功能需求适用场景
刷新，重置 table 等

### 🧐 解决方案
参数携带action

**Comment by rozbo** [comment]
+1
