### ISSUE TITLE
🧐[问题] How to use SettingDrawer with pro-layout v7 ?

### ISSUE THREAD

**Issue by codering** [ant-design/pro-components#6093]
### 🧐 问题描述

之前的版本可以直接配置主题，现在没有了，token 配置对于非前端开发者来说太复杂了，希望可以兼容下老版本，哪怕是通过 SettingDrawer 能配置出兼容原来的主题配置参数也好啊， 但是最新版本我没看到 SettingDrawer 的demo。

### 🚑 其他信息
```json
{
 "@ant-design/pro-components": "^2.3.20",
 "@umijs/max": "^4.0.25",
}

```

**Comment by chenshuai2144** [comment]
学一下 token吧，antd 和 pro 都会切换到token。

另： SettingDrawer 没有任何使用上的变化
