### ISSUE TITLE
👑 [需求] CheckCard 多选卡片能否支持必须选择一个

### ISSUE THREAD

**Issue by showonne** [ant-design/pro-components#6094]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

CheckCard

### 🥰 需求描述

结合 form 表单使用时给定一个默认值后，希望多选卡片必须选择其中一个，不能一个都不选

### ⛰ 功能需求适用场景

类似表单中的 radio 场景，但想使用 CheckCard 展示选项

### 🧐 解决方案

希望能新增个 prop 支持

**Comment by ONLY-yours** [comment]
看起来是需要一个 ProFromCheckCard 的样子？ 感觉需要又不需要

**Comment by showonne** [comment]
> 看起来是需要一个 ProFromCheckCard 的样子？ 感觉需要又不需要

现在这个组件的表现像高级版的 checkbox，我需要的场景是高级版的 radio，现有组件也许可以通过 chang 监听再重新修改值的方式实现，但是页面应该会有卡片从取消选中再自动选中的过程，体验不太好

**Comment by chenshuai2144** [comment]
使用 rule 去配置吧，卡片本身不应该带这种逻辑的
