### ISSUE TITLE
ProTable使用formRef.current.setFieldsValue时并不会触发onValuesChange事件

### ISSUE THREAD

**Issue by frankcou** [ant-design/pro-components#6095]
不单止是EditableProTable，ProTable也有同样问题。

```jsx
<ProTable
          rowKey={'id'}
          formRef={formRef}
          request={getTableData}
          columns={columns}
          form={{
            onValuesChange: onValuesChange,
          }}
/>
```
这里面使用formRef.current.setFieldsValue({aaa:'222'})，并不会触发onValuesChange

@ant-design/pro-components版本1.1.16
对应"@ant-design/pro-form": "1.73.0"，"@ant-design/pro-table": "2.79.0"

_Originally posted by @frankcou in https://github.com/ant-design/pro-components/issues/5148#issuecomment-1284808191_

**Comment by Mzhang1994** [comment]
setFieldsValue均不能触发onChange或者onValuesChange。你在setFieldsValue后面加onChange或者onValuesChange的触发函数或者用钩子函数吧。

**Comment by chenshuai2144** [comment]
setFieldsValue 就是不能触发的，你要手动去处理数据
