### ISSUE TITLE
🧐[问题] ProForm.Group的title与其children在水平方向排布

### ISSUE THREAD

**Issue by wooxyz** [ant-design/pro-components#6097]
### 🧐 问题描述

如何使ProForm.Group的title和children在水平方向布局，有horizontal值吗？也不知道咋设计的
```
<ProForm.Group title="详情">
   <ProFormText name="age" label="年龄" />
   <ProFormDatePicker name="birth" label="生日" />
</ProForm.Group>
```
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/33221294/196849779-bc974049-32ae-4f2c-9ff7-972680b0fdb0.png)

**Comment by chenshuai2144** [comment]
没有的，ProForm.Group 追求的是错落有致

**Comment by wooxyz** [comment]
> 没有的，ProForm.Group 追求的是错落有致

那就不追求水平设计了？尤其是在表单中，一行显示几个表单项。
