### ISSUE TITLE
🧐[问题]请问如何将Protable 的column 设置和Editable ProTable 的增删改整合到一个table组件呢？

### ISSUE THREAD

**Issue by sooneeatwork** [ant-design/pro-components#6099]
🧐 问题描述
请问如何把 [PROTABLE](https://procomponents.ant.design/components/table)里实现column 设置和[EDITABLE-PROTABLE](https://procomponents.ant.design/components/editable-table)中的增删改功能放在同一个Table组件呢？

我想要实现一个比较完整的Table，其中我想要有的功能是

Editable pro table 中的增删改功能
![Capture](https://user-images.githubusercontent.com/12389790/196880070-28f69874-033a-4795-b809-c6720ad3c689.PNG)

Protable 中查寻和设置栏位（column）visibilty的功能
![Capture](https://user-images.githubusercontent.com/12389790/196879963-d539c251-3fb6-4c03-bb20-c7bb37f7faf8.PNG)

我面对到的问题是

如果只用 Editable pro table 的话我就没法用Protable 的设置栏位（column）visibilty的功能
如果只用 pro table 的话我就没法用Editable pro table 的新增一行功能.
有没有办法就是两种功能都在一个Pro Table 组件同时拥有呢？

**Comment by chenshuai2144** [comment]
现在就是同一个组件的，你可以通过配置打开所有的功能，在可编辑表格中我们关闭了一些不常用的配置，代码是相同的

**Comment by sooneeatwork** [comment]
謝謝
