### ISSUE TITLE
🧐[问题] AntDesignPro 在表单页面使用了 FooterToolbar 组件后，页面底部多了很多的空白问题。

### ISSUE THREAD

**Issue by houkunlin** [ant-design/pro-components#6102]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
AntDesignPro 在表单页面使用了 FooterToolbar 组件后，页面底部多了很多的空白问题，这个问题改怎么解决？
![image](https://user-images.githubusercontent.com/12333292/196904799-c0279392-068a-4fb8-b9c2-10da345b038f.png)

我的相关配置：
路由
```json
{
  path: '/system/user/user-info/edit',
  name: 'user-edit',
  icon: 'smile',
  hideInMenu: true,
  component: './system/User/FormPage',
  exact: true
}
```
文件
```tsx
export default ()=>{
  return (
    <PageContainer header={{ onBack: goBack }}>
      <ProForm
        formRef={formRef}
        params={query}
        request={loadUser}
        onFinish={onSubmit}
        submitter={{
          render: (_, dom) => <FooterToolbar>{dom}</FooterToolbar>,
        }}
      />
    </PageContainer>
  )
}
```

经查看，在 `PageContainer` 末尾自动加了一个 `div#heigth=64` 的高度，但是我们的 `Footer` 还在 `PageContainer` 的外面，这就造成了 `PageContainer` 的 `div#heigth=64` 把 `Footer` 挤到更下面了
https://github.com/ant-design/pro-components/blob/a6f0fcd0ec02f6d35196fa15250a7f5f32351f17/packages/layout/src/components/PageContainer/index.tsx#L341

**Comment by chenshuai2144** [comment]
这个宽度是为了防止页面被 FootToolBar 挡住设置的。会影响到你的功能吗？

**Comment by houkunlin** [comment]
倒是不影响主要功能，主要是视觉上看起来有问题。
因为用了 FooterToolbar 组件后，页面的 Footer 被挡住了，但是 Footer 上方又多了很多的空白。
想要的效果是用了 FooterToolbar 组件后，在 Footer 下方增加空白，让 Footer 可以正常显示出来

**Comment by chenshuai2144** [comment]
footer 的位置layout不知道，所以只能这样了，你可以手动 padding 一下，或者在某些页面把footer去掉

**Comment by chenshuai2144** [comment]
其实可以知道的，我想办法换下位置。

**Comment by houkunlin** [comment]
感谢:smiley::pray::+1:

**Comment by dadede999** [comment]
> 某些页面把footer去掉

怎么在某些页面把footer去掉呢？
