### ISSUE TITLE
单测出现问题：Cannot find module 'antd/es/theme/style' from 'node_modules/@ant-design/pro-provider/es/index.js'

### ISSUE THREAD

**Issue by ldwonday** [ant-design/pro-components#6104]
![image](https://user-images.githubusercontent.com/4630157/197092237-10c72a4b-5792-4c55-9f36-3f9fe3d63f4b.png)

babel.config.js配置：
```
module.exports = {
  presets: [
    ['@babel/preset-env', { targets: { node: 'current' } }],
    '@babel/preset-react',
    '@babel/preset-typescript',
  ],
  plugins: [
    ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }],
    [
      '@babel/plugin-transform-runtime',
      {
        regenerator: true,
      },
    ],
    ['@babel/plugin-transform-modules-commonjs'],
  ],
};
```

去掉babel-plugin-import，jest跑单测正常，加上就报上面的错误，这个问题以前1.0不存在，更新pro-components到2.3.20最新版就有问题了，antd版本4.23.5.
求看啥问题。

**Comment by ldwonday** [comment]
@chenshuai2144 尽快解决下这个问题吧。

**Comment by ldwonday** [comment]
看了下原因，全部是因为
```
import { theme, ConfigProvider } from 'antd';
```
这个theme导致的，去掉这个theme就正常了。啥原因啊

**Comment by ldwonday** [comment]
两处地方：pro-util和pro-provider都有引入这个theme，去掉就运行ok了

**Comment by ldwonday** [comment]
`[babel-plugin-import]`的问题，因为`import { theme, ConfigProvider } from 'antd';`这句中的theme不是组件，但是`babel-plugin-import`把它当成组件处理了，所以导致找不到`antd/es/theme/style`
@chenshuai2144 有啥好的解决方案吗？

**Comment by chenshuai2144** [comment]
给 antd/es/theme/style 设置一个为空的别名吧
https://webpack.js.org/configuration/resolve/
