### ISSUE TITLE
侧边栏菜单的二级菜单重叠

### ISSUE THREAD

**Issue by Hades-li** [ant-design/pro-components#6107]
### Reproduction link

[https://procomponents.ant.design/components/layout/](https://procomponents.ant.design/components/layout/)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/12124478/197135891-42d63bf7-42f7-4fed-a0d5-00121166730a.png)

侧栏导航->鼠标处于第二个菜单项的第二个二级菜单项上->然后往左滑动至第三个菜单项上，会出现两个 二级菜单项重叠

### What is expected?

菜单项不重叠，即第一个二级菜单项会消失

### What is actually happening?

二级菜单重叠展示

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | react 18.2.0 |
| System | win/mac |
| Browser | chrome/edge/safari |

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


感谢反馈问题，这是一个已知问题，官方文档里也提到了。对此，建议您使用最新版本的 Ant-Design Pro（v5）避免此问题。

如果您不想更新版本，可以尝试手动调整css样式，通过将第一个二级菜单项的 z-index 属性值设为 1，则该菜单项将覆盖第二个菜单项。

```css
.ant-menu-submenu.ant-menu-submenu-inline.ant-menu-submenu-active > .ant-menu-submenu-title {
  z-index: 1;
}
```

希望可以帮到您！

**Comment by chenshuai2144** [comment]
修复了，state 更新的不及时
