### ISSUE TITLE
🐛[BUG] renderFormItem注入了placeholder属性

### ISSUE THREAD

**Issue by jaykou25** [ant-design/pro-components#6110]
### RenderFormItem自动注入了placeholder `请输入` 对于Select等组件并不友好

renderFormItem可以对valueType里的组件类型自动注入placeholder, 但是对于用户自定义的组件还是不要自动注入为好.

现在的情况是我封装了一个select组件, 但是在renderFormItem里被强行加入了placeholder属性, 我只能一个一个手动加入placeholder来覆盖自动注入的属性. 用的地方多了就不太方便.

希望理解😅

![renderFormItem](https://user-images.githubusercontent.com/86033222/197158231-693f6226-0bcf-4635-b541-1291392ee398.jpg)

**Comment by chenshuai2144** [comment]
你都自定义了，自己设置一下吧

**Comment by jaykou25** [comment]
> 你都自定义了，自己设置一下吧，默认行为是为了满足大部分人的

自定组件的话除非写死placeholder, 如果想要提供一个默认值, 用户又可以输入的话, 默认值始终会被注入的`请输入`覆盖.
