### ISSUE TITLE
🧐[问题]Protable中的table区域为何存在两种Dom结构？

### ISSUE THREAD

**Issue by Song-aff** [ant-design/pro-components#6115]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
Protable组件中的表格，在.ant-table-container 下会存在 div.ant-table-header>table 和div.ant-table-content>table>thead.ant-table-header两种dom结构。
![image](https://user-images.githubusercontent.com/24764561/197323901-ae8a60e9-6e8a-403d-adcd-5c6266e4b044.png)
![image](https://user-images.githubusercontent.com/24764561/197323910-9c07caaf-fdb6-4820-8af0-fa5647cfe883.png)
问题1: 为什么会存在两种不同dom结构？
问题2: 发现通过不同tab切换时（通过disable:none），已渲染表格的dom结构会在两种结构之间变化。

**Comment by chenshuai2144** [comment]
![Uploading image.png…]()

你是不是打开了浮动吸顶的功能，默认看起来是没有这个dom的

**Comment by chenshuai2144** [comment]
<img width="977" alt="image" src="https://user-images.githubusercontent.com/8186664/197965013-f8a0c8d8-4ed2-4af7-ad1d-307da5255b3d.png">

`<Table columns={columns} dataSource={data} scroll={{ x: 1500, y: 300 }} />`
