### ISSUE TITLE
👑 [需求]强烈建议文档不要更新到不稳定的版本了

### ISSUE THREAD

**Issue by BongBongBang** [ant-design/pro-components#6117]
现在最新的procomponents 2.0.x的版本，基于antd5跟umi4。本身umi4就还没有完善文档，antd5更是还在experienmental版本中，procomponents的文档是不是应该保留一份老版本的文档呢？
拿ModalForm举例，现在文档里的字段如visible -> open，全是新字段，老的逻辑都不知道到哪看了。
### 🔩 所属模块或组件

所有模块、组件

### 🥰 需求描述

不兼容老版本的更新，希望留一份老版本的文档。

**Comment by lsy934127847** [comment]
现在文档还能不能看了，样式错乱

**Comment by BongBongBang** [comment]
我放弃了。。【面向文档开发】转向【面向源码开发】。。。

**Comment by lsy934127847** [comment]
搞什么玩意 组件升级之后各种问题

**Comment by Mzhang1994** [comment]
我也赞同，组里来了新前端。让别人开发时多看文档，结果文档里的一些API用了报错。组件也不敢乱升级。毕竟有break change存在。作为开源组件，没人要求像付费方案那样做。但至少大部分的框架使用者的利益要顾及到吧。留一份历史的文档公开出来给使用者看，也不是什么很花功夫的事情。

**Comment by ldwonday** [comment]
自从加了个什么token后这样Prolayout的样式真是无语，从原来的白色全部变成透明了

**Comment by chenshuai2144** [comment]
拥抱变化，visible  -> open 修改 是 antd 的计划，有需求可以自己部署文档的。
或者直接来提供一个 pr 修改文档
