### ISSUE TITLE
🧐[问题]StepsForm分步表单应该如何使用setFieldsValue

### ISSUE THREAD

**Issue by 15191362069** [ant-design/pro-components#6119]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by 15191362069** [comment]
const [FormRef] = Form.useForm();
stepsform上属性formRef={FormRef}
但是在他onCurrentChange函数里面去执行setFieldsValue不生效

**Comment by chenshuai2144** [comment]
时机不对导致的，你可以用 formRefMap 里面有所有form的实例
