### ISSUE TITLE
ProLayout的样式默认能不能不要突然变成透明了？

### ISSUE THREAD

**Issue by ldwonday** [ant-design/pro-components#6125]
如题，以前的Prolayout背景色，菜单，面包屑这些背景色都是默认的白色，现在一升级全部全变成透明了，我真是不知道说啥好，
ProLayout的文档上的组件也全部是透明背景色，正常吗？

**Comment by ldwonday** [comment]
https://github.com/ant-design/pro-components/blob/640ecb52e887c15761b6353714b509a105972817/packages/provider/src/typing/layoutToken.ts#L140

这里的默然值都是透明的，不会对原组件产生影响吗？？为啥不设置默认值是unset之类的？？？

**Comment by ldwonday** [comment]
@chenshuai2144

**Comment by ldwonday** [comment]
![image](https://user-images.githubusercontent.com/4630157/197940219-795e3918-d28b-486a-94bf-82e9f4ebac26.png)这样子设置也没有用，还是透明色背景，哎，我好难

**Comment by chenshuai2144** [comment]
设计就是这样，你可以参考demo配置一下token

**Comment by ldwonday** [comment]
@chenshuai2144 那为什么通过ProConfigProvider的token设置不了ProLayout的样式呢？例如上面图上的配置，我看了下代码，
应该是在这行合并的时候有问题了https://github.com/ant-design/pro-components/blob/eb25214465c9a6e705e91b084d1003f4401c88ff/packages/layout/src/ProLayout.tsx#L732

应该是：
```tsx
<ConfigProviderWrap
        autoClearCache
        token={{
          ...tokenContext.token,
          layout: {
              ...tokenContext.token.layout
              ...props.token,
           },
        }}
      >
        <BaseProLayout {...props} />
      </ConfigProviderWrap>
```

**Comment by ldwonday** [comment]
@chenshuai2144
