### ISSUE TITLE
🐛[BUG] protable 使用valuetype === ’radio‘ 样式错误

### ISSUE THREAD

**Issue by zozopen** [ant-design/pro-components#6127]
![image](https://user-images.githubusercontent.com/23204297/197969772-08d238ed-fa6b-4c5f-8adb-e72a2618ad21.png)

demo样例里面应当是横排列
![image](https://user-images.githubusercontent.com/23204297/197969989-c7751a29-0ba2-475d-9bbc-41a354ef977a.png)

**Comment by chenshuai2144** [comment]
fixed, retry build

**Comment by zozopen** [comment]
> fixed, retry build

请问下是哪个版本，我重新跑了还是没有修复
