### ISSUE TITLE
🧐[问题]pro layout左右布局问题

### ISSUE THREAD

**Issue by gdmec07140512** [ant-design/pro-components#6128]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
layout设置为**mix** / **side** 都无法满足这种布局，想问一下 这种pro-layout里的这种布局要怎么实现，下面是我在antd官网上截的图：
<img width="844" alt="image" src="https://user-images.githubusercontent.com/14307947/197977669-810f4897-9c10-488b-8223-73fb8eb23603.png">

<img width="897" alt="image" src="https://user-images.githubusercontent.com/14307947/197978283-12d49fb2-2b79-4efe-84e3-85c8e891b2c0.png">

**Comment by gdmec07140512** [comment]
除了在setting里 设置 layout: 'side'， 还有什么办法还是改变布局？

**Comment by chenshuai2144** [comment]
我们已经不支持header了，这种的你要自己实现一下了，或者直接用  antd 的 layout
