### ISSUE TITLE
🐛[BUG]ProFormUploadButton fileList不可控

### ISSUE THREAD

**Issue by wyh-skr** [ant-design/pro-components#613]
### 🐛 bug 描述

ProFormUploadButton fileList不可控 ，设置fileList为空，仍然会显示上传后的文件  antd 的上传组件fileList可控

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
要用 Form 的 方式来支持受控，而不是用 直接传 value 的方法
