### ISSUE TITLE
样式问题🧐[问题]

### ISSUE THREAD

**Issue by xu-Aurora** [ant-design/pro-components#6134]
### 🧐 问题描述

@ant-design/pro-form从1.69.3升级到2.2.12，但样式没有发生任何变化。按理来说应该和官网一样的风格了，2版本不是换风格了嘛？

**Comment by chenshuai2144** [comment]
官网是配合 antd@5 的效果，你可以使用antd@5 来打到同样的效果

**Comment by xu-Aurora** [comment]
> 官网是配合 antd@5 的效果，你可以使用antd@5 来打到同样的效果

好吧，建议官网里面给个提示antd的版本，不然不知道antd要升级到5才行呢
