### ISSUE TITLE
BetaSchemaForm定义layoutType="ModalForm"时bug🐛[BUG]

### ISSUE THREAD

**Issue by wanglianjie91** [ant-design/pro-components#6137]
### 🐛 bug 描述

配置destoryOnClose为true后， 页面的任何状态变成，都会导致弹窗中的form直接消失。

### © 版本信息

- ProComponents 版本: "@ant-design/pro-form": "^1.18.3",
- umi 版本: "umi": "^3.5.0",
- 浏览器环境
- 开发环境 mac OS

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


抱歉，由于您的问题与 React 的前端问题无关，无法提供有效的解决方案，请您联系相关技术支持或者咨询社区其他人员。谢谢理解。
