### ISSUE TITLE
🐛[BUG]protable新建行，未配置的字段显示-，然后再次新增行，未配置字段显示1，依次递增

### ISSUE THREAD

**Issue by puxinhe** [ant-design/pro-components#614]
### 🐛 bug 描述
protable新建行，未配置的字段显示-，然后再次新增行，未配置字段显示1，依次递增

protable新建行，未配置的字段显示-，然后再次新增行，未配置字段显示1，依次递增
### 🏞 期望结果
应该都显示为 -  

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本4.1
- 浏览器环境 chrome
- 开发环境 [win10]

**Comment by chenshuai2144** [comment]
很久之前的bug了，更新一下依赖
