### ISSUE TITLE
🧐[问题]pro-table版本升级后报错

### ISSUE THREAD

**Issue by saberKafu** [ant-design/pro-components#6140]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

我将pro-table版本从2.56.3升级到3.1.0之后项目启动报错，以下是错误提示
This dependency was not found:

* antd/es/segmented/style in ./node_modules/@ant-design/pro-table/node_modules/@ant-design/pro-field/es/components/Segmented/index.js

To install it, you can run: npm install --save antd/es/segmented/style

### 🚑 其他信息
下图是我项目当前使用的依赖版本
![image](https://user-images.githubusercontent.com/36984386/198491335-58e28d5a-36e7-4508-9fdf-9c38485fc7fc.png)

**Comment by sushi-su** [comment]
antd 版本不匹配，缺了 Segmented 组件，需要升级到 [4.20](https://github.com/ant-design/ant-design/releases/tag/4.20.0) 以上的版本

**Comment by saberKafu** [comment]
> antd 版本不匹配，缺了 Segmented 组件，需要升级到 [4.20](https://github.com/ant-design/ant-design/releases/tag/4.20.0) 以上的版本

谢谢，antd版本之后确实没问题
