### ISSUE TITLE
🐛[BUG] 例子在 codesandbox 上运行报错

### ISSUE THREAD

**Issue by gMan1990** [ant-design/pro-components#6141]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤

1. https://procomponents.ant.design/components/table/#table-single
2. 点 codesandbox 去运行
3. `Cannot set property ProForm of #<Object> which has only a getter`

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境 `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
有同样的issue了 不要重复开

**Comment by gMan1990** [comment]
@chenshuai2144 是哪个issue，我去看看？有解决方法吗？

**Comment by chenshuai2144** [comment]
搜下就看见了

**Comment by gMan1990** [comment]
@chenshuai2144 没搜到，你用的啥关键字搜?
