### ISSUE TITLE
🐛[BUG] 拖拽排序编辑表格 拖动后顺序没有改变

### ISSUE THREAD

**Issue by mraiguo** [ant-design/pro-components#6142]
### 🐛 bug 描述

拖动表格第一行到第二行位置，放开鼠标后第一行顺序没有移动到第二行，还是还原到第一行的位置

### 🏞 期望结果

能拖动表格第一行到第二行位置

### 💻 复现代码

官网demo即可复现  
https://procomponents.ant.design/components/drag-sort-table#%E6%8B%96%E6%8B%BD%E6%8E%92%E5%BA%8F%E7%BC%96%E8%BE%91%E8%A1%A8%E6%A0%BC 

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
没复现问题
