### ISSUE TITLE
🐛[BUG] ProTable基本表单在严格模式下报findDomNode错误

### ISSUE THREAD

**Issue by fnoopv** [ant-design/pro-components#6156]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

pro-components版本: 2.3.27
react版本: 18.2.0
antd版本: 4.23.6
直接复制官网的查询表格代码，在严格模式下报`findDomNode is deprecated in StrictMode`错误，确认不是`antd`的问题，直接使用`antd`的`Form`表单不会报这个错误
![image](https://user-images.githubusercontent.com/24599198/199308248-b5a50fb8-18e2-4aab-a525-7418354edbfa.png)

### 📷 复现步骤

https://codesandbox.io/s/crazy-http-7oikqr?file=/src/App.tsx

### 🏞 期望结果

在react的严格模式下不报`findDomNode is deprecated in StrictMode`

### 💻 复现代码

见复现步骤中的sandbox链接

### © 版本信息

- ProComponents 版本: 2.3.27
- umi 版本: 没有使用
- 浏览器环境: windows 11 22H2，microsoft edge: 107
- 开发环境: windows WSL

**Comment by chenshuai2144** [comment]
应该是我们的依赖库导致的，能帮我排查一下吗

**Comment by fnoopv** [comment]
确认是rc-util的问题,见[issue](https://github.com/react-component/util/issues/98)

**Comment by JunVincetHuo** [comment]
同样的问题

**Comment by chenshuai2144** [comment]
ref https://github.com/react-component/util/issues/98

**Comment by Over-reaction** [comment]
现在是否解决 我现在使用还是有这个报错"@ant-design/pro-components": "^2.6.2",

**Comment by 0x457** [comment]
我也遇到了，现在解决了吗？

"@ant-design/pro-components": "^2.7.13",
    "@reduxjs/toolkit": "^2.2.6",
    "antd": "^5.19.1", 
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
