### ISSUE TITLE
🐛[BUG]ProTable的toolBarRender，按钮过多会溢出，不会换行

### ISSUE THREAD

**Issue by Grain-full** [ant-design/pro-components#6157]
在按钮过多时，但屏幕分辨率不够大，工具栏的按钮就会溢出，超过整个ProTable

期待：按钮过多能换行，或者有更换的解决方案

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


感谢提出 ProTable 工具栏按钮溢出的问题。

为了解决这个问题，可以考虑在 `toolBarRender` 中使用 antd 的 `Dropdown` 组件对多余的按钮进行收纳，在原来的工具栏上增加一个“更多”按钮，点击后弹出收纳多余按钮的下拉菜单。

以下是一个示例代码，具体可以根据自己的需求进行修改：

```javascript
import { DownOutlined } from '@ant-design/icons';
import { Menu, Dropdown } from 'antd';

const ToolBar = ({ buttons }) => {
  // 将 buttons 分成两部分，第一部分是直接显示在工具栏上的，第二部分是需要进行收纳的
  const [visibleButtons, hiddenButtons] = buttons.reduce(
    ([visible, hidden], button) => {
      if (visible.length <= 3) {
        return [[...visible, button], hidden];
      } else {
        return [visible, [...hidden, button]];
      }
    },
    [[], []],
  );

  // 下拉菜单的渲染函数
  const menu = (
    <Menu>
      {hiddenButtons.map((button, index) => (
        <Menu.Item key={index}>{button}</Menu.Item>
      ))}
    </Menu>
  );

  // 工具栏的渲染函数
  const toolBarRender = () => (
    <>
      {visibleButtons}
      {hiddenButtons.length > 0 && (
        <Dropdown overlay={menu}>
          <a className="ant-dropdown-link" onClick={(e) => e.preventDefault()}>
            更多 <DownOutlined />
          </a>
        </Dropdown>
      )}
    </>
  );

  return <ProTable toolBarRender={toolBarRender} />;
};
```

关于 antd 的 `Dropdown` 组件和 `Menu` 组件的使用方法，可以参考官方文档：https://ant.design/components/dropdown-cn/。

**Comment by liusure** [comment]
提供一个比较笨的解决办法，全部放到数组第一个dom里，然后控制这个dom就可以了，可以配合Space这个组件的wrap实现换行。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢分享这个解决方案，将所有的按钮放到一个数组中，并结合 `Space` 的 `wrap` 属性进行换行，确实也是一种解决办法。不过这种方式可能会导致工具栏的按钮过多时出现滚动条，比较影响使用体验。

另外，如果你想让工具栏按钮能够自动换行，也可以使用 CSS 的 `flex-wrap` 属性，在 `toolBarRender` 的父元素上通过样式来实现：

```javascript
toolBarRender={() => (
  <div style={{ display: 'flex', flexWrap: 'wrap' }}>
    // your buttons here
  </div>
)}
```

这种方式会根据按钮数量和可视区域的大小自动换行，相对来说比较灵活。如果你对 CSS 中的 `flex` 和 `flex-wrap` 不熟悉，可以参考这份官方文档：https://developer.mozilla.org/zh-CN/docs/Web/CSS/flex-wrap。

**Comment by chenshuai2144** [comment]
已经修复啦
