### ISSUE TITLE
🐛[BUG]Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by xezzon** [ant-design/pro-components#6164]
### 🐛 bug 描述

```
Uncaught ReferenceError: process is not defined
    at openVisibleCompatible2 (openVisibleCompatible.js:5:31)
    at SiderMenuWrapper2 (index.js:51:25)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
```

### 📷 复现步骤

命令行运行 `vite` 。

### 🏞 期望结果

正常渲染 ProLayout

### 💻 复现代码

```jsx
function App() {
  const { pathname } = useLocation()
  const main = useRoutes(route.routes)

  return (
    <ProLayout
      layout="mix"
      fixSiderbar
      fixHeader
      route={route}
      location={{ pathname }}
      menu={{ autoClose: false }}
      menuItemRender={(item, dom) => <Link to={item.path}>{dom}</Link>}
      className="min-vh-100"
    >
      {main}
    </ProLayout>
  )
}
```

### © 版本信息

- ProComponents 版本: 2.3.28
- Ant Design 版本: 4.24.0
- node 版本: v18.12.0
- vite 版本: 3.2.2
- pnpm 版本: 7.14.2
- 浏览器环境 Microsoft Edge 版本 107.0.1418.26 (正式版本) (64 位)
- 开发环境 Windows 11

**Comment by xezzon** [comment]
https://github.com/ant-design/pro-components/blob/a853c53a3f4bb5c850da9cd176c5399d13e9a15f/packages/utils/src/compareVersions/openVisibleCompatible.ts#L7

**Comment by Kaby-Lake** [comment]
同样的问题，在webpack下也出现了

**Comment by macjohson** [comment]
vite.config.ts 下加入
```ts
define: {
    'process.env': {}
  }
```

**Comment by nhatncb** [comment]
> vite.config.ts 下加入
> 
> ```ts
> define: {
>     'process.env': {}
>   }
> ```

This will lead to another bug related to useSWR

**Comment by Jungzl** [comment]
```typescript
// vite.config.ts

import { version } from 'antd'

export default defineConfig(() => ({
  define: {
    'process.env.ANTD_VERSION': `"${version}"`,
  }
}))
```

**Comment by xezzon** [comment]
用户侧处理不太友好吧？能不能从代码层面解决，比如链式操作符。

**Comment by Lucien-X** [comment]
> 用户侧处理不太友好吧？能不能从代码层面解决，比如链式操作符。

Same issue here...
我还以为vite出问题了，升了个vite版本还是这个问题

**Comment by abdeljalil09** [comment]
this bug has come back

**Comment by abdeljalil09** [comment]
> ```ts
> // vite.config.ts
> 
> import { version } from 'antd'
> 
> export default defineConfig(() => ({
>   define: {
>     'process.env.ANTD_VERSION': `"${version}"`,
>   }
> }))
> ```

this work only in dev mode when shipping to production it comes back again

**Comment by abdeljalil09** [comment]
package is fully broken

**Comment by abdeljalil09** [comment]
this is my workaround the problem because the above work only in dev mode , to make it work in production

![image](https://user-images.githubusercontent.com/101262837/235758241-fdc5a13d-932e-47aa-a925-6d9fb38e03e4.png)
