### ISSUE TITLE
🐛[BUG]收不到 release 通知了？

### ISSUE THREAD

**Issue by yingzhiji** [ant-design/pro-components#617]
### 🐛 bug 描述

之前是 pro-table 放在单个仓库，现在是 monorepo 的形式放在 pro-components 仓库中，但是现在订阅了 release 后就收不到更新通知了，首页看到的最新的 release 版本也还是 pro-table 的那一次发布。

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
现在不会自动写 release了，正式发布这个仓库的时候会解决 changelog 和   release 的问题

**Comment by yingzhiji** [comment]
OK
