### ISSUE TITLE
🐛[BUG] Antd Pro Layout show error of using useSWR

### ISSUE THREAD

**Issue by nhatncb** [ant-design/pro-components#6172]
I'm using the latest ant-pro/layout with Vite 3 but it still keep throwing error.
Although I follow the exact example on https://procomponents.ant.design/en-US/components/layout/, I can't figure out.
![image](https://user-images.githubusercontent.com/49893714/200381443-9bc1057a-09d0-4b2b-9f3c-c860702a9a29.png)

**Comment by zjf9035** [comment]
> I'm using the latest ant-pro/layout with Vite 3 but it still keep throwing error. Although I follow the exact example on https://procomponents.ant.design/en-US/components/layout/, I can't figure out. ![image](https://user-images.githubusercontent.com/49893714/200381443-9bc1057a-09d0-4b2b-9f3c-c860702a9a29.png)

hello,Have you solved this problem
