### ISSUE TITLE
🐛[BUG]ProFrom + EditableProTable  删除当前行数据后 使用formRef.current.setFieldsValue赋值，会使当前行数据后面的有数据验证的字段删除

### ISSUE THREAD

**Issue by wenhuacode** [ant-design/pro-components#6175]
删除当前行数据后 使用formRef.current.setFieldsValue赋值，会使当前行数据后面的有数据验证的字段删除

**Comment by WuJiY** [comment]
外部 formRef.current.setFieldsValue 时，多次多条数据时 会清空部分数据 估计是index变了，是在设置rules 会发生这样的情况

**Comment by wenhuacode** [comment]
有好的解决方法吗？ @WuJiY

**Comment by WuJiY** [comment]
还没发现啥解决方案，不知道是不是bug

**Comment by wenhuacode** [comment]
谢谢大哥 @WuJiY

**Comment by wenhuacode** [comment]
目前找到一种解决方案， 用ProForm.Item 包裹 EditableProTable  然后 formRef.current.setFieldsValue就没问题。

**Comment by WuJiY** [comment]
> 目前找到一种解决方案， 用ProForm.Item 包裹 EditableProTable 然后 formRef.current.setFieldsValue就没问题。

但是你无法使用 EditableProTable 内置的验证规则

**Comment by wenhuacode** [comment]
@WuJiY 只能组合一下了 formref + EditableProTableref
