### ISSUE TITLE
🐛[BUG] 配置了 `renderFormItem` 时，`dateTimeRange` 组件的默认 `placeholder` 展示不正确

### ISSUE THREAD

**Issue by wyhooo** [ant-design/pro-components#6176]
### 🐛 bug 描述

`valueType` 为 `dateTimeRange` 时，如果设置了 `renderFormItem` 但没有设置 `fieldProps.placeholder`，渲染出来的默认 `placeholder` 不正确。

### 📷 复现步骤

https://codesandbox.io/s/amazing-moon-v1lemv?file=/App.tsx

初步判断是这里的问题 [source](https://github.com/ant-design/pro-components/blob/master/packages/field/src/index.tsx#L497)

注入的 placeholder 没有判断组件接收字符串还是数组，并且文案不对，比如 `dateTimeRange` 应该为「请选择」。

### 🏞 期望结果

展示正确的 placeholder。

### © 版本信息

- ProComponents 版本: latest
- umi 版本: latest
- 浏览器环境 Chrome latest
- 开发环境 macOS

**Comment by kiner-tang** [comment]
我来改一下吧
