### ISSUE TITLE
Umi4.0组件ProFormUploadButton在弹窗关闭的时候报错

### ISSUE THREAD

**Issue by Connor-lipalater** [ant-design/pro-components#6177]
### Reproduction link

[https://blog.csdn.net/miaomiao_1024/article/details/125276262](https://blog.csdn.net/miaomiao_1024/article/details/125276262)

### Steps to reproduce

ProFormUploadButton 在弹窗关闭的时候会报错： Uncaught TypeError: (fileList || []).forEach is not a function

### What is expected?

正常清空ProFormUploadButton的数据

### What is actually happening?

Uncaught TypeError: (fileList || []).forEach is not a function

| Environment | Info |
| --- | --- |
| antd | 4.20.4 |
| React | 18.6 |
| System | windows10 |
| Browser | Version 104.0.5112.102 |

**Comment by chenshuai2144** [comment]
默认主句给个数字，这个是js常见报错，自己debug就能解决
