### ISSUE TITLE
🐛[BUG] 高级表格的form中，添加Cascader级联选择的功能，Cascader设置onChange事件时，输入框不显示选择后的内容

### ISSUE THREAD

**Issue by iambool** [ant-design/pro-components#618]
### 🐛 bug 描述

高级表单中，设置了一个column字段如下：
const columns: ProColumns<TableListItem>[] = [
    ...... ,
    {
      title: '业务',
      dataIndex: 'business',
      renderFormItem: (_, { type, defaultRender, ...rest }, form) => {
        if (type === 'form') {
          return null;
        }
        return <Cascader options={options} allowClear **onChange={handleBusinessChange}**/>;
      },
      hideInTable: true,
    },
  ];
  const **handleBusinessChange** = (value, selectedOptions) => {
    console.log(value, selectedOptions);
  }

设置完成后，在表单操作页面选择完成后，onChange事件触发了的，但是，输入框里的东西却没有显示，操作如下：

### 📷 复现步骤

1、选择如下路径：
![image](https://user-images.githubusercontent.com/30134533/94427111-28d07c80-01c1-11eb-8ee6-18ab3653936f.png)

2、完成后会打印内容，但是输入框内数据不显示
![image](https://user-images.githubusercontent.com/30134533/94427158-3f76d380-01c1-11eb-9038-95bf79d4a22c.png)

但是，如果不绑定 onChange 事件，输入框内的内容就可以正常显示

### 🏞 期望结果

期望在绑定 onChange 事件的情况下，也能正常显示选择的内容

### © 版本信息

- ProComponents 版本: 
   "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-descriptions": "^1.0.16",
    "@ant-design/pro-layout": "^6.4.16",
    "@ant-design/pro-table": "^2.7.2",
- umi 版本
"umi": "^3.2.14",
- 浏览器环境
Chrome最新版本
- 开发环境 [e.g. mac OS]
windows

**Comment by chenshuai2144** [comment]
你为什么要绑定 onChange？

**Comment by iambool** [comment]
> 你为什么要绑定 onChange？ onValueChange 碰到了什么问题吗？

因为我的查询表单真正提交的是选中内容对应的id，而不是输入框中的文字，所以需要在onChange时，对 id 项赋值

**Comment by chenshuai2144** [comment]
@iambool  自己封装一下吧，这样可以保证吐出的value，永远是自己想要的

`const  myCascader  =  ()=> Cascader `

**Comment by iambool** [comment]
> @iambool 自己封装一下吧，这样可以保证吐出的value，永远是自己想要的
> 
> `const myCascader = ()=> <Cascader/> `

单独封装后没有上述问题，已成功，谢谢
