### ISSUE TITLE
🧐[问题] 如何在request接口异步保存数据前hook住进行处理【格式化数据】

### ISSUE THREAD

**Issue by ByYogi** [ant-design/pro-components#6183]
### 🧐 问题描述
`ProFormSelect` 使用 `request` 属性通过API获取数据列。
后端必须要以`[{label:"", value:""}, {label:"", value:""}]` 返回数据。
有没有针对`request`格式化数据的接口可以使用？

### 💻 解决思路
如果没有类似接口，那就不得不使用`useStatus来`保存api数据，再格式化赋值到 `options` 属性
再问：目前我没有找到针对 `request` API 请求的异常处理方式，求大佬给建议😶‍🌫️

### 🚑 其他信息
【本人新人，在提问前有努力寻找答案至少2小时，实在迷茫来此发问】
![Snipaste_2022-11-09_16-28-58](https://user-images.githubusercontent.com/111735598/200779461-c13d2da0-d299-4608-a372-f08b37cf3ea4.png)

**Comment by WuJiY** [comment]
fieldNames 了解一下

**Comment by WuJiY** [comment]
```reqest = {（）=>{
  调用后台接口 任意处理你想要的...
  return {
     success:true,
     data
   }
}}
```

**Comment by ByYogi** [comment]
> ```
> request = {（）=>{
>   调用后台接口 任意处理你想要的...
>   return {
>      success:true,
>      data
>    }
> }}
> ```
谢谢，我就是想知道有没有其他方式。最后，无论如何，这种处理方式才是正确的。
