### ISSUE TITLE
🧐[问题]：关于版本问题，控制台报警告怎么解决？

### ISSUE THREAD

**Issue by anearseeyou** [ant-design/pro-components#6184]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 💻 示例代码

![image](https://user-images.githubusercontent.com/24536619/200796720-33bb90ff-ff0f-4dd3-be97-165eed9c1e56.png)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/24536619/200796743-daafec3b-c60a-47f6-81a5-9bc2acc91f45.png)

![image](https://user-images.githubusercontent.com/24536619/200796861-2a990c45-ee38-417e-a1c4-1a99c5bcbda1.png)

**Comment by chenshuai2144** [comment]
可以 先等等，这个是要废弃 api 的提示，pro 还没有完成

**Comment by chenshuai2144** [comment]
已经修复，发布版本就好了

**Comment by amin168** [comment]
更新了，依然有这个问题
