### ISSUE TITLE
🐛[BUG] StatisticCard->Statistic组件 trend up和down的 css样式丢失

### ISSUE THREAD

**Issue by huanlirui** [ant-design/pro-components#6186]
### 🐛 bug 描述

css失效，缺少类？

### 📷 复现步骤

未使用umi 

### 🏞 期望结果

红色与绿色的箭头 ，css正确生效，像官网示例一样
<img width="666" alt="image" src="https://user-images.githubusercontent.com/40491203/200850088-ed7c959d-f2ca-48e7-9fbb-c85dc076ef3c.png">

### 💻 复现代码

```
        <StatisticCard style={{ width: 160 }}>
        <Statistic title="日环比" value="7.60%" trend="up" />
        <Statistic title="周环比" value="7.60%" trend="down" />
        <Statistic title="周环比" value="0.00%" />
      </StatisticCard>
```

### © 版本信息

- ProComponents 版本:  2.3.30
- umi 版本 未使用umi
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
<img width="141" alt="image" src="https://user-images.githubusercontent.com/40491203/200849672-370a968a-9a08-4cd4-952b-764c14a70fbb.png">

**Comment by amelia-coding** [comment]
i also get this problem

**Comment by sb-child** [comment]
Also, can reproduce with umi:

### © 版本信息
- antd 版本: 5.0.1
- ProComponents 版本: 2.3.35
- umi 版本: 4.0.32
- 浏览器环境: Firefox
- 开发环境: Linux

**Comment by thierryxing** [comment]
遇到同样的问题

**Comment by ONLY-yours** [comment]
> 遇到同样的问题

现在还有么？我在antd 5 + ProComponents 2.3.34 版本下完全ok，换成antd4也是好的

**Comment by thierryxing** [comment]
> 

是的，一直存在，尝试使用 Pro 命令新建一个项目也存在同样的情况。
研究了一下，发现 ant-pro-card-statistic-trend-up 对应的 div 里缺少 css-dev-only-do-not-override 属性，导致 css 的 where 条件没有生效

**Comment by thierryxing** [comment]
接着上文补充一下，升级 Antd 到了 5.0，ant-pro-card-statistic-trend-up 对应的 div 里有了 css-dev-only-do-not-override 属性，但后面的 suffix 和其他元素的不同。

如：

![image](https://user-images.githubusercontent.com/64818/204991142-4629d18f-d7f6-48f1-b949-3d7237d8aed0.png)


故该问题仍然存在

**Comment by thierryxing** [comment]
接上文，找到原因了：

https://github.com/ant-design/pro-components/blob/0ca55b37c26937dd212318ee491c9c488bec868f/packages/card/src/components/Statistic/index.tsx#L63

在 Antd 4.x 中，这块代码中 hashId 在 classNames 处理 object 时，取的是 Key，所以导致最终生成的 className 中是静态字符 hashId，而非「css-dev-only-do-not-override-${hashId}」
导致 css 样式没有生效

而 Antd 5.x，应该是编译时，编译器发现这里的 dom 节点没有 css-dev-only-... 属性，故追加了一个，但 hashId 已经发生了变化，故 css 样式也未能生效

**Comment by hexiaomin496** [comment]
> 接上文，找到原因了：
> 
> https://github.com/ant-design/pro-components/blob/0ca55b37c26937dd212318ee491c9c488bec868f/packages/card/src/components/Statistic/index.tsx#L63
> 
> 在 Antd 4.x 中，这块代码中 hashId 在 classNames 处理 object 时，取的是 Key，所以导致最终生成的 className 中是静态字符 hashId，而非「css-dev-only-do-not-override-${hashId}」 导致 css 样式没有生效
> 
> 而 Antd 5.x，应该是编译时，编译器发现这里的 dom 节点没有 css-dev-only-... 属性，故追加了一个，但 hashId 已经发生了变化，故 css 样式也未能生效

请问怎么解决呢？

**Comment by thierryxing** [comment]
> > 接上文，找到原因了：
> > https://github.com/ant-design/pro-components/blob/0ca55b37c26937dd212318ee491c9c488bec868f/packages/card/src/components/Statistic/index.tsx#L63
> > 
> > 在 Antd 4.x 中，这块代码中 hashId 在 classNames 处理 object 时，取的是 Key，所以导致最终生成的 className 中是静态字符 hashId，而非「css-dev-only-do-not-override-${hashId}」 导致 css 样式没有生效
> > 而 Antd 5.x，应该是编译时，编译器发现这里的 dom 节点没有 css-dev-only-... 属性，故追加了一个，但 hashId 已经发生了变化，故 css 样式也未能生效
> 
> 请问怎么解决呢？

已经提了 PR 修复

**Comment by punkin6** [comment]
这个修复预计什么时候发布正式版本？
