### ISSUE TITLE
🐛[BUG] 页面级别的登录表单未兼容手机端

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#6189]
<img width="487" alt="image" src="https://user-images.githubusercontent.com/30397655/200982808-83e5eaa1-3d69-44b4-a05b-204f61eb3a24.png">
<img width="911" alt="image" src="https://user-images.githubusercontent.com/30397655/200983103-f6c6e614-4b6c-4fa1-97d6-1423167969c6.png">

**Comment by chenshuai2144** [comment]
已经修复了，更新下版本
