### ISSUE TITLE
🧐[问题] Input style not effected

### ISSUE THREAD

**Issue by hmz22** [ant-design/pro-components#6191]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
ant design Input Component not styled. can tell me how fix it? 
### 💻 示例代码
https://stackblitz.com/edit/vitejs-vite-xmuyer?file=src/App.tsx
### 🚑 其他信息
```
"dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^2.3.29",
    "@babel/core": "^7.20.2",
    "@emotion/css": "^11.10.5",
    "antd": "^4.24.1",
    "less": "^4.1.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.24",
    "@types/react-dom": "^18.0.8",
    "@vitejs/plugin-react": "^2.2.0",
    "typescript": "^4.6.4",
    "vite": "^3.2.3"
  }
```

and this my vite config:

```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { version } from "antd";

export default defineConfig({
  plugins: [react()],
  define: {
    "process.env.ANTD_VERSION": `"${version}"`,
  },
  css: {
    preprocessorOptions: {
      less: {
        javascriptEnabled: true,
        modifyVars: {
          "root-entry-name": "variable",
        },
      },
    },
  },
});
```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


👉 解决方案：

首先，确保已经正确安装了 `antd` 库和其样式 `antd/dist/antd.less`。然后，在你的代码中引入样式文件：

```jsx
import 'antd/dist/antd.less';
```

还需要通过 `babel-plugin-import` 对 `antd` 进行按需引入，可以在你的 `.babelrc` 或者 `babel.config.js` 中进行如下配置：

```js
module.exports = {
  plugins: [
    ['import', { libraryName: 'antd', style: true }]
  ]
}
```

最后，将您的 `Input` 组件包裹在一个 `Form` 表单中，并设置相应的 `Form.Item`，如下所示：

```jsx
import React from 'react';
import { Form, Input } from 'antd';

const FormItem = Form.Item;

function MyForm() {
  const onFinish = (values) => {
    console.log('Received values of form: ', values);
  };

  return (
    <Form
      name="basic"
      initialValues={{ remember: true }}
      onFinish={onFinish}
    >
      <FormItem
        label="Username"
        name="username"
        rules={[
          { required: true, message: 'Please input your username!' },
        ]}
      >
        <Input />
      </FormItem>

      <FormItem>
        <button type="submit">Submit</button>
      </FormItem>
    </Form>
  );
}
```

最后，您可以查看 `antd` 的官方文档来了解更多关于 `Form` 和 `Input` 组件的信息。

参考文献：

1. [Ant Design - Usage with Create React App](https://ant.design/docs/react/use-in-typescript-cn#Use-with-Create-React-App)
2. [Ant Design - Form](https://ant.design/components/form-cn/)
3. [Ant Design - Input](https://ant.design/components/input-cn/)
