### ISSUE TITLE
🐛[BUG]使用谷歌翻译页面后，编辑表格操作报错

### ISSUE THREAD

**Issue by xkim1994** [ant-design/pro-components#6194]
### 🐛 bug 描述
使用谷歌翻译页面后，编辑表格报错

### 📷 复现步骤
编辑表格前先使用谷歌翻译，翻译页面成功后，点击编辑操作，页面异常

### 🏞 期望结果
使用谷歌翻译页面不影响编辑操作

### 💻 复现代码
https://procomponents.ant.design/~demos/table-single?current=1&pageSize=5

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![Snipaste_2022-11-10_17-51-40](https://user-images.githubusercontent.com/43065993/201059201-baed3a8c-7271-4b02-9b28-69c7ff0d984f.png)

**Comment by chenshuai2144** [comment]
react 下最好不要用翻译软件，diff 算法会报错
