### ISSUE TITLE
🐛[BUG]pro-layout7.1.12及以上版本编译后CSS使用了:where()选择器，360、搜狗等浏览器不兼容，导致样式错误

### ISSUE THREAD

**Issue by zhouwenwu30** [ant-design/pro-components#6195]
### 📷 复现步骤

1、分别使用7.1.11版本和7.1.12版本测试；
2、浏览器中调试查看html中\<head\>标签里的<style>标签样式；
3、7.1.11版本正常（见截图）;
4、7.1.12版本出现:where()选择器，存在兼容问题（见截图）。

### 🏞 期望结果

不使用:where()选择器，或者提供开关配置

### © 版本信息

- ProLayout 版本: 7.1.12
- umi 版本：4.0.30
- 浏览器环境：360浏览器极速模式或搜狗浏览器
- 开发环境 ：mac OS

#### 7.1.11版本编译结果：
<img width="1376" alt="iShot_2022-11-10_18 10 24" src="https://user-images.githubusercontent.com/52321849/201071228-aac2599b-9a1c-4cdf-8dec-dd1b13ef5a35.png">

#### 7.1.12版本编译结果：
<img width="1336" alt="iShot_2022-11-10_18 44 11" src="https://user-images.githubusercontent.com/52321849/201071281-816e99f0-7529-4645-99fd-735102f07835.png">

**Comment by chenshuai2144** [comment]
不打算兼容这些了，推荐用chrome。或者低版本。

有个黑科技是关掉 hash 功能，但是可能造成样式污染。

![image](https://user-images.githubusercontent.com/8186664/201476754-9743ebc5-af10-4522-bdd1-1c91f7c11a0e.png)

**Comment by a992681784** [comment]
@chenshuai2144 能否增加和antd5.0一样的样式兼容方案？像360这种浏览器用户量还是很大的！
![图片](https://user-images.githubusercontent.com/20497118/206338309-56a8af99-9145-4e6e-a95e-6a6baf163f84.png)

**Comment by lovewinders** [comment]
我也碰到了该问题，竟然不兼容市面常见浏览器

**Comment by chenshuai2144** [comment]
可以 配置 hashed 关掉一下 where 的限制
还是推荐不要支持这种低级浏览器，它们的流行指挥增加整个前端的负担成本

**Comment by a992681784** [comment]
> 可以 配置 hashed 关掉一下 where 的限制 还是推荐不要支持这种低级浏览器，它们的流行指挥增加整个前端的负担成本

@chenshuai2144 请问下 在哪里配置hashed 文档里好像没有这个属性。看源码是在antd的ConfigProvider的theme属性里有hashed。但是通过antd的ConfigProvider配置后没有效果。
ConfigProvider.config({
  theme: {
    primaryColor: '#4B64EE',
    hashed: false,
  },
});

**Comment by chenshuai2144** [comment]
要用 ProComponents 的 ProConfigVide

**Comment by Statfine** [comment]
> 要用 ProComponents 的 ProConfigVide

@chenshuai2144 app.tsx下的childrenRender 全局设置不生效

```
childrenRender: (children) => {
  return <><ProConfigProvider hashed={false}>{children}</ProConfigProvider></>;
},
```
