### ISSUE TITLE
ProTable optionRender params序列化不一致 🐛[BUG]

### ISSUE THREAD

**Issue by wanglianjie91** [ant-design/pro-components#6200]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

search.optionRender方法。  searchConfig.form?.getFieldsValue();  取得的search form参数与request中的search form参数序列化不一致。

例如： valueType: 'dateRange'。 searchConfig.form?.getFieldsValue(); 未按照预期，去掉'HH:mm:ss'.

### © 版本信息

- ProComponents 版本: [2.3.24]
- umi 版本 [3.5.x]
- 浏览器环境 [chrome]
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
数组的转化有bug来着。已经修复了
