### ISSUE TITLE
🐛[BUG] pro table点击重置 没有回到初始值

### ISSUE THREAD

**Issue by is-cool** [ant-design/pro-components#6203]
### 🐛 bug 描述

pro table点击重置 没有回到初始值

### 📷 复现步骤

复制带有query的url重新打开 点击重置无效

### 🏞 期望结果

点击重置 回到初始值

### 💻 复现代码

[
](https://codesandbox.io/s/cha-xun-biao-ge-forked-rqpp17?file=/App.tsx)

**Comment by is-cool** [comment]
复现代码
https://codesandbox.io/s/cha-xun-biao-ge-forked-rqpp17?file=/App.tsx

**Comment by wangmeijian** [comment]
增加这个配置：```syncToInitialValues: false```

完整代码
```js
form={{
        // 由于配置了 transform，提交的参与与定义的不同这里需要转化一下
        syncToUrl: (values, type) => {
          if (type === 'get') {
            return {
              ...values,
              created_at: [values.startTime, values.endTime],
            };
          }
          return values;
        },
        syncToInitialValues: false,
   }}
```

**Comment by is-cool** [comment]
> 
谢谢

**Comment by hyl1374961656** [comment]
设置valueType: 'dateRange'后搜索条件依然不会清空
