### ISSUE TITLE
有没有antd对应该组件的使用版本信息? 3.26.x版本应该选哪个

### ISSUE THREAD

**Issue by chenzhengWin** [ant-design/pro-components#6205]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

请问antd的3.26.x版本应该选哪个版本的pro-compoent使用？

### 💻 示例代码
package.json:

    "antd": "^3.26.20",

**Comment by chenshuai2144** [comment]
放弃吧，不支持的
