### ISSUE TITLE
ProFormList里面嵌套ModalForm下面嵌套一个根据ProFormSelect变化的ProFormDependency时，联动不生效，日志打印不出变化

### ISSUE THREAD

**Issue by Flora-cc** [ant-design/pro-components#6206]
### Reproduction link

[https://.com](https://.com)

### Steps to reproduce

ProFormList里面嵌套ModalForm下面嵌套一个根据ProFormSelect变化的ProFormDependency时，联动不生效，日志打印不出变化

### What is expected?

确认下是不是写法有问题

### What is actually happening?

联动不生效，日志打印不出变化

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 无 |
| System | 无 |
| Browser | 无 |

**Comment by afc163** [comment]
请给一个重现链接

**Comment by yangjie21** [comment]
import {
  ProFormDateRangePicker,
  ProFormRadio,
  ProFormDigit,
  ModalForm,
  ProFormText,
  ProFormCheckbox,
  ProFormList,
  ProForm,
  ProFormTextArea,
  ProCard,
  ProFormDependency,
} from '@ant-design/pro-components';
import { CloseCircleOutlined } from '@ant-design/icons';
import { useRef } from 'react';
import { Divider,Button, Typography, Tag } from 'antd';
import moment from 'moment';
const addrs = ['校区', '远程'];
const { Text } = Typography;

const UpdateForm = (props) => {
  const students = [{ id: "123213", comments: [{ lable: '', value: '' }], name: "1231" }]
  console.log('students=>', students);
  const formRef = useRef();

  return (
    <>
    <ModalForm
      title={'新增报告'}
      formRef={formRef}
      trigger={
        <Button type="primary">
          新建表单
        </Button>
      }
      initialValues={{
        rules: ['only_schedule'],
        dateRange: [
          moment().startOf('day').format('YYYY-MM-DDTHH:mm'),
          moment().endOf('day').format('YYYY-MM-DDTHH:mm'),
        ],
        duration: 24,
        addr: '校区',
        ...props.values,
        students,
      }}
      modalProps={{
        maskClosable: false,
        width: 1200,
      }}
      onFinish={(value) => {
        console.log('params =>', value);
        // props.onSubmit({ ...params });
      }}
    >
      <Divider />
      <ProForm.Group>
        <ProFormRadio.Group
          name="addr"
          width="md"
          label="学习地点"
          options={addrs.map((item) => ({
            label: item,
            value: item,
          }))}
        />
        <ProFormCheckbox.Group
          name="rules"
          label="规则"
          width="md"
          options={[
            { value: 'only_schedule', label: '仅生成计划' },
            { value: 'show_practise', label: '显示计划中的详情' },
          ]}
        />
      </ProForm.Group>
      <ProForm.Group>
        <ProFormDigit label="时长(h)" name="duration" width="md" min={1} max={10} />
        <ProFormDateRangePicker width="md" name="dateRange" label="学习时间" />
      </ProForm.Group>
      <ProFormList
        name="students"
        deleteIconProps={{
          Icon: CloseCircleOutlined,
          tooltipText: '不需要这行了',
        }}
        initialValue={students}
        min={students.length}
        max={students.length}
        itemRender={({ listDom, action }, { index }) => (
          <ProCard
            bordered
            style={{ marginBlockEnd: 8 }}
            title={
              <Text>
                <Tag color="green">{students && students[index].name}</Tag>学习总结
              </Text>
            }
            extra={action}
            bodyStyle={{ paddingBlockEnd: 0 }}
          >
            {listDom}
          </ProCard>
        )}
      > <ProForm.Group style={{ display: 'none' }}>
      <ProFormText name="id" label="id" />
    </ProForm.Group>
    <ProFormDependency name={['rules', 'dateRange']}>
      {({ rules, dateRange }) => {
        console.log("rules, dateRange=>", rules, dateRange)
        return <div />;
      }}
    </ProFormDependency>
    <ProFormList
      name="comments"
      max={4}
      min={1}
      creatorButtonProps={{
        creatorButtonText: '新增评语',
      }}
      copyIconProps={{
        tooltipText: '复制此行到末尾',
      }}
      deleteIconProps={{
        tooltipText: '不需要这行了',
      }}
    >
      <ProForm.Group key="comment">
        <ProFormText name="label" label="老师" width="sm" placeholder="请输入名称" />
        <ProFormTextArea name="value" label="评语" width="md" placeholder="请输入名称" />
      </ProForm.Group>
    </ProFormList></ProFormList>
    </ModalForm>
    </>
  );
};

export default UpdateForm;
