### ISSUE TITLE
🐛[BUG] ProLayout - Uncaught TypeError: Cannot read properties of undefined (reading '0'))

### ISSUE THREAD

**Issue by tailoc-hcmus** [ant-design/pro-components#6208]
### 🐛 bug 描述
ProLayout error:
Uncaught TypeError: Cannot read properties of undefined (reading '0'))
![image](https://user-images.githubusercontent.com/57663409/201330984-a292d3f0-fa03-4885-a092-7fbf867c93bb.png)

### 📷 复现步骤

I followed the steps in Code Demo Basic usage at [https://procomponents.ant.design/en-US/components/layout](https://procomponents.ant.design/en-US/components/layout)

### © 版本信息

@ant-design/pro-components": "^2.3.30",
"antd": "^4.24.1",
"typescript": "^4.8.4",

**Comment by 110635164** [comment]
我也是，就跑个demo都报错

**Comment by liukai3586** [comment]
我也是哎 一大堆报错

**Comment by tailoc-hcmus** [comment]
目前的解决方：者去掉StrictMode绕一下了。

**Comment by tailoc-hcmus** [comment]
> ### 🐛 bug 描述
> ProLayout error: Uncaught TypeError: Cannot read properties of undefined (reading '0')) ![image](https://user-images.githubusercontent.com/57663409/201330984-a292d3f0-fa03-4885-a092-7fbf867c93bb.png)
> 
> ### 📷 复现步骤
> I followed the steps in Code Demo Basic usage at https://procomponents.ant.design/en-US/components/layout
> 
> ### © 版本信息
> @ant-design/pro-components": "^2.3.30", "antd": "^4.24.1", "typescript": "^4.8.4",

目前的解决方：者去掉StrictMode绕一下了。

**Comment by tailoc-hcmus** [comment]
目前的解决方：者去掉StrictMode绕一下了。

**Comment by ChenXiangY** [comment]
同样这个问题，烦死了。

**Comment by ChenXiangY** [comment]
> 目前的解决方：者去掉StrictMode绕一下了。

去掉可行

**Comment by AriaAto** [comment]
> > 目前的解决方：者去掉StrictMode绕一下了。
> 
> 去掉可行

我去掉了StrictMode，也时好时坏

**Comment by chenshuai2144** [comment]
升级一下layout版本。swr 不这次  react18，升级到了2.0
