### ISSUE TITLE
🐛[BUG] ProTable type=‘form’时，field宽度固定为328px

### ISSUE THREAD

**Issue by dumeng-chn** [ant-design/pro-components#621]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/29587964/94509660-52cc8200-0247-11eb-9f52-aeef99c9789c.png)

如图，上面的个输入框的款式才是正常的宽度，固定宽度导致以下属性失效
`form={{ layout: 'horizontal', labelCol: { span: 7 },wrapperCol: { span: 15 }}}`

- ProTable 版本: [2.8.2]

**Comment by dumeng-chn** [comment]
不太理解这个设计，希望还是默认100%，不然使用renderFormItem自定义输入组件时，宽度不一致。 @chenshuai2144

**Comment by xoptimal** [comment]
关联了, 但是这里并没有提出解决方案耶  0.0

**Comment by xoptimal** [comment]
@chenshuai2144   版本是还没有更新上去是吗
