### ISSUE TITLE
🐛[BUG] 无法正常使用ProLayout

### ISSUE THREAD

**Issue by tKlint** [ant-design/pro-components#6216]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

<img width="726" alt="image" src="https://user-images.githubusercontent.com/49471670/201631140-773e76fc-ee0a-44bc-a129-863d20f703ee.png">

<img width="726" alt="image" src="https://user-images.githubusercontent.com/49471670/201631225-0aef7441-035b-4b4b-b946-7cec5bcda807.png">

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
升级一下layout，swr导致的兼容性问题
