### ISSUE TITLE
🐛[BUG] Data in collapsed section is not validated on form submit (BetaSchemaForm)

### ISSUE THREAD

**Issue by badigina-merck** [ant-design/pro-components#6218]
### 🐛 Issue description

Data within collapsed group of BetaSchemaForm is not validated on submit.

Steps to reproduce:

1. Create a collapsible group
2. Make one of the fields within the group invalid
3. Collapse the group
4. Submit form

**Expected**: `onFinish` is not called due to validation error (as it works when section is expanded)
**Actual**: `onFinish` is called

### Dependencies versions
latest

https://codesandbox.io/s/schema-biao-dan-forked-0zco51?file=/App.tsx

**Comment by chenshuai2144** [comment]
fixed by https://github.com/ant-design/pro-components/commit/769177f5acdad0126fd146e8e6a1346a7c21d882
