### ISSUE TITLE
👑 [需求]EditableProTable需求是这样的，在编辑的时候，自定义的编辑组件在校验数据失败不会有红框，所以我想在点击“保存”的时候，外部去调用表单校验去给自定义组件添加样式，我看了下api，onSave好像并不能满足我的需求，请问我该如何处理？

### ISSUE THREAD

**Issue by zhengyunsen** [ant-design/pro-components#6221]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
尽量用默认的rules配置不要自己搞的这个花.如果你非要这样做,需要用formitem 来自定义一下
