### ISSUE TITLE
🐛[BUG] 当 BetaSchemaForm 的 layoutType="ModalForm" 时，外部组件 state 更新时，弹窗错误隐藏了

### ISSUE THREAD

**Issue by Fiber-Man** [ant-design/pro-components#6223]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

RT，BetaSchemaForm 设置 layoutType="ModalForm" 时，外部组件 state 更新时，弹窗错误隐藏了

### 📷 复现步骤

如下代码

### 🏞 期望结果

外部 state 值发生变化时候，弹窗不保持。
ps：
1. 与 BetaSchemaForm 同级组件 state 更新，无此问题。
2. 测试 ModalForm 组件，无此问题。

### 💻 复现代码

```
import React, { useState } from "react";
import { Button } from "antd";
import { BetaSchemaForm } from "@ant-design/pro-components";

export default function Route() {
  const [_, setA] = useState("");
  function C({}) {
    return (
      <BetaSchemaForm
        trigger={
          <Button key="button" type="primary">
            xyz...
          </Button>
        }
        layoutType={"ModalForm"}
        onFinish={async (values) => {
          console.log(values);
          setA(Date.now());
          return false;
        }}
        columns={[
          {
            title: "标题",
            dataIndex: "value",
          },
        ]}
      />
    );
  }

  return <C></C>;
}
```

### © 版本信息

- ProComponents 版本: [2.0.0-alpha.43]
- Antd 版本：[5.0.0-beta.0]
- 浏览器环境： chrome
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

无

**Comment by sushi-su** [comment]
用的版本太低了，更新到最新版试试

**Comment by Fiber-Man** [comment]
请问如果想用 "antd": "next" （Antd 5.0），应该正确选用哪个版本？

**Comment by Fiber-Man** [comment]
> 用的版本太低了，更新到最新版试试

"@ant-design/pro-components": "^2.3.33", 仍然有问题

**Comment by sushi-su** [comment]
仔细看了一下，是你的写法有问题，C 应该放到 Route 的外部，现在这么写每次 setA 都会重新初始化一次 C，所以每次 setA 弹窗会变成默认到隐藏状态
