### ISSUE TITLE
🐛[BUG] SchemaForm 配置 column 的 dataIndex 与 key 问题

### ISSUE THREAD

**Issue by Yang-yibu** [ant-design/pro-components#6224]
### 🐛 bug 描述
两个表单使用相同的 dataIndex 时，控制台报 key 相同的错误；添加 key 后，表单值有问题

### 📷 复现步骤

必现

### 💻 复现代码

官方示例就可以复现（通用配置总览 - 自定义 ValueType 示例）

### © 版本信息

- ProComponents 版本: 从 1.1.1 就有问题

### 🚑 其他信息
![lQLPJxbf70Lvnm7NA0zNA9CwZiJVMPv8hlgDb_X1gAAQAA_976_844](https://user-images.githubusercontent.com/23130670/201836334-975e782f-9ab7-49fb-a072-12fed3401711.png)
![lALPJvDqXSa3sWnNAefNBbw_1468_487](https://user-images.githubusercontent.com/23130670/201836384-3bef1c6a-a77d-4630-b4ca-8f4964c364d0.png)

**Comment by chenshuai2144** [comment]
为什么会需要同样的 key 设置两个输入框？

**Comment by Yang-yibu** [comment]
是两个表单项需要渲染同一个字段即 dataIndex。
如果使用 Schema 的配置，控制台会让提供 key，如果配置了 key，表单渲染就会出问题（绿色箭头是组件源码）。
