### ISSUE TITLE
🧐[问题]ProFormSelect 的选中回调函数onChange: (value , option) = void,  options类型无法推断

### ISSUE THREAD

**Issue by edwards19900128** [ant-design/pro-components#6227]
### 🧐 问题描述
如题所示， typescript新手请教一下是否标注中的问题...
貌似ant-design的select<T, E> 泛型参数是两个，到ProFormSelect这边就剩一个了...

![image](https://user-images.githubusercontent.com/11594850/201911034-3f5c2a10-e381-4215-9887-a83912462687.png)

**Comment by chenshuai2144** [comment]
我应该支持一下，你没有支持导致的
