### ISSUE TITLE
🐛[BUG] EditableTable在ProForm中会异常触发onValuesChange事件

### ISSUE THREAD

**Issue by walker27** [ant-design/pro-components#6229]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
在ProFrom中使用EditableTable，随便触发页面中一个无关state变化就会触发EditableTable的onValuesChange事件。

我简单调试了下，发现[此处的代码](https://github.com/ant-design/pro-components/blob/master/packages/table/src/components/EditableTable/index.tsx#L431)会被高频触发，是因为在每次触发后，对象里面有一个内置map_row_parentkey字段会被反复的插入和删除，导致上面位置的代码中的`isDeepEqualReact`方法每次都判断都为false.

我自身的业务需求场景比这个demo要更复杂一点，场景需要两个EditTable(以下简称TableA 和 TableB) TableA为TableB的一项提供下拉框，所以我的做法是TableA的onValuesChange时调用TableBRef.current.setRowData来实现，因为上述的问题会导致死循环。如果有需要我再提供一个贴近我业务场景的demo

### 📷 复现步骤

codesandbox 链接中有写

### 💻 复现代码
[https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-zy1w8j](https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-zy1w8j)

### © 版本信息

- ProComponents 版本: 2.3.28
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by WuJiY** [comment]
#6199 是不是和我这个类似的bug

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。




你好，针对你的问题，根据可复现的 Codesandbox 示例，我也测试了一下，发现你提到的问题确实存在。在每次触发无关 state 变化时，都会触发 `EditableTable` 的 `onValuesChange` 事件，而且确实是因为 `map_row_parentkey` 字段的反复插入和删除导致的。

针对你的提问，我提供以下解决方案：

1. 尝试升级 ProComponents 版本到最新版，看能否解决问题。

2. 如果升级版本没有解决问题，可以考虑查看 Ant Design 官方提供的 Editable Table，使用 `antd` 的 `Table` 组件，通过 `renderEditableCell` 和 `onCell` 属性实现 Editable Table 功能，并在 `onCell` 回调函数中手动触发表格数据修改的 `setState` 方法。具体实现方式可以参考 Ant Design 官方提供的 [Editable Table 示例](https://ant.design/components/table-cn/#components-table-demo-edit-row)。这样可以避免使用 ProComponents 的 `EditableTable` 组件导致的问题。

3. 对于你的业务场景中有两个 EditTable，并需要在一个 EditTable 的 onValuesChange 事件中修改另一个 EditTable 的数据的情况，可以考虑使用 React 的 `useEffect` 钩子函数，监听另一个 EditTable 数据的变化，在变化时触发当前 EditTable 的数据修改方法即可。

附上第三种方式的示例代码：

```jsx
import React, { useState, useEffect } from "react";
import { Button, Table } from "antd";
import { EditableProTable } from "@ant-design/pro-table";

const TableA = ({ value, onChange }) => {
  const [list, setList] = useState(value || []);

  const columns = [
    {
      title: "Name",
      dataIndex: "name",
      editable: true
    },
    {
      title: "Age",
      dataIndex: "age",
      editable: true
    }
  ];

  const handleTableChange = (newValue) => {
    setList(newValue);
    onChange?.(newValue);
  };

  useEffect(() => {
    // 监听另一个 Editable Table 数据的变化
    console.log("TableA value: ", value);
  }, [value]);

  return (
    <EditableProTable
      rowKey="id"
      value={list}
      onChange={handleTableChange}
      columns={columns}
    />
  );
};

const TableB = ({ value, onChange }) => {
  const [list, setList] = useState(value || []);

  const columns = [
    {
      title: "Name",
      dataIndex: "name",
      editable: true
    },
    {
      title: "Age",
      dataIndex: "age",
      editable: true
    }
  ];

  const handleTableChange = (newValue) => {
    setList(newValue);
    onChange?.(newValue);
  };

  return (
    <EditableProTable
      rowKey="id"
      value={list}
      onChange={handleTableChange}
      columns={columns}
    />
  );
};

const EditableTable = () => {
  const [tableAData, setTableAData] = useState([]);
  const [tableBData, setTableBData] = useState([]);

  const handleTableAChange = (newValue) => {
    setTableAData(newValue);

    // 根据 TableA 数据计算 TableB 数据
    const newTableBData = newValue.map((item) => ({
      ...item,
      age: item.age + 1
    }));

    // 手动触发 TableB 修改数据
    tableBRef.current.onValuesChange({}, newTableBData);
  };

  const handleTableBChange = (newValue) => {
    setTableBData(newValue);
  };

  const tableBRef = React.useRef();

  return (
    <div>
      <TableA value={tableAData} onChange={handleTableAChange} />
      <br />
      <TableB
        ref={tableBRef}
        value={tableBData}
        onChange={handleTableBChange}
      />
    </div>
  );
};

export default EditableTable;
```

希望我提供的解决方案能够帮助到您，如有问题还请及时提出，我会尽力帮您解决。

**Comment by chenshuai2144** [comment]
修复了，感谢提交 issue
