### ISSUE TITLE
🐛[BUG] ProFormDigitRange in LightFilter renders incorrect value

### ISSUE THREAD

**Issue by ko2in** [ant-design/pro-components#6230]
### 🐛 bug 描述

When using ProFormDigitRange in LightFilter, the value is not correctly renders in UI after selecting the digit range. The UI renders the date range with value (1970-01-01 - 1970-01-01) instead of the digits.

![digit-range](https://user-images.githubusercontent.com/930315/202119892-0797a17c-23a3-4f4d-95d5-a49897052157.gif)

### 📷 复现步骤

* Import LightFilter and ProFormDigitRange
* Add LightFilter and ProFormDigitRange in the app

### 🏞 期望结果

The UI should render the digit range the user selected (eg., 1 - 2) instead of the date range (1970-01-01 - 1970-01-01)

### 💻 复现代码

```
import { LightFilter, ProFormDigitRange } from '@ant-design/pro-components';

export default () => (
  <LightFilter>
    <ProFormDigitRange name="range" label="Range" />
  </LightFilter>
);
```

### © 版本信息

- ProComponents 版本: ^2.0.0
- 浏览器环境: Chrome, Firefox (Other browsers might be effected too)
- 开发环境: Ubuntu 20.04 LTS

**Comment by chenshuai2144** [comment]
close by 6250094da
