### ISSUE TITLE
🐛[BUG]在ProFormList中使用ModalForm，ModalForm不能正常工作(values值为{})

### ISSUE THREAD

**Issue by yuan-ze** [ant-design/pro-components#6233]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

在ProFormList中使用自己封装的ModalForm组件时，ModalForm能展示，但是onFinish的时候不能拿到填写的values

### 📷 复现步骤

codesandbox复现https://codesandbox.io/s/heng-xiang-bu-ju-forked-5teknb?file=/package.json

- 正常的
![image](https://user-images.githubusercontent.com/53718020/202135356-761e5527-6821-4769-a8a7-374970a898fd.png)

- 有问题的
![image](https://user-images.githubusercontent.com/53718020/202135401-93a0810c-7455-45c1-a86d-a332dc0d6acc.png)

### 🏞 期望结果

期望ModalForm在任意位置都能正常使用

### 💻 复现代码

codesandbox复现https://codesandbox.io/s/heng-xiang-bu-ju-forked-5teknb?file=/package.json

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 
- 浏览器环境 chrome
- 开发环境 MAC

**Comment by ZijieSong** [comment]
+1同遇到，有人解决吗

**Comment by chenshuai2144** [comment]
新版本中已经修复了,大家更新版本即可

**Comment by MircoSans** [comment]
> 新版本中已经修复了,大家更新版本即可

请问一下1.0的版本会修复吗
