### ISSUE TITLE
🧐[问题]求教各位大大：EditableProTable如何实现双击编辑

### ISSUE THREAD

**Issue by yang-chuanjiang** [ant-design/pro-components#6236]
![image](https://user-images.githubusercontent.com/38531906/202339332-1173b51f-b979-4fe9-a5a1-bb794fa72792.png)
不想要操作列，想鼠标双击编辑行数据

**Comment by yy305736605** [comment]
const Row = ({ ...restProps })=>(
    <tr onDoubleClickCapture={()=>setEditableRowKeys([restProps['data-row-key']])}  {...restProps}  />
  )
配置属性  components={{
          body: {
            row: Row,
          },
        }}

**Comment by seifenk** [comment]
> ```
> const Row = ({ ...restProps })=>(
>     <tr onDoubleClickCapture={()=>setEditableRowKeys([restProps['data-row-key']])}  {...restProps}  />
>   )
> 配置属性  components={{
>           body: {
>             row: Row,
>           },
>         }}
> ```

我爱你
