### ISSUE TITLE
🐛[BUG]ProFormDatePicker在赋值之后disabledDate获取错误的currentDate

### ISSUE THREAD

**Issue by anysunflower** [ant-design/pro-components#6237]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProFormDatePicker填写日期之后，再次填写disabledDate失效，因为填写日期之后disabledDate 中的参数currentDate 获取的是当前填写的值，导致失效

### 🏞 期望结果

disabledDate设置只能选择今天之后的时间，今天之前的日期不可选择，修改日期的时候也应该生效。

### 💻 复现代码

```
        export const disabledDate = (currentDate: Moment) => {
            return moment(currentDate).isBefore(moment.now());
        };
        <ProFormDatePicker
            name={['expireTime']}
            label="请选择过期时间"
            rules={[{required: true, message: '请选择过期时间'}]}
            extra={question.showExpireTime || null}
            fieldProps={{
                disabledDate,
            }}
        />

```

### © 版本信息

- ProComponents 版本:~2.2.7
- umi 版本： ^3.5.0
- 开发环境 macOS

### 🚑 其他信息

改成antd 的datepicker之后可以正常使用

```
        <ProForm.Item
            label="请选择过期时间"
            name={['expireTime']}
            rules={[{required: true, message: '请选择过期时间'}]}
            extra={question.showExpireTime || null}
        >
            <DatePicker disabledDate={disabledDate} />
        </ProForm.Item>
```

**Comment by chenshuai2144** [comment]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/8186664/210711466-235453bb-5b35-4641-87e7-a17a7e7a02d8.png">

<img width="227" alt="image" src="https://user-images.githubusercontent.com/8186664/210711495-c6825bd8-d338-4c00-aa13-05155ae2aaf8.png">



没有复现

**Comment by rabbit-y** [comment]
> datepicker

第一次没问题，选择一个时间后控制台打印的时间类型不是moment的。我是在可编辑的表格中复现的。
![image](https://github.com/ant-design/pro-components/assets/35751066/577fd351-1569-4960-bc38-7cb74aea43a0)
 打印后
<img width="772" alt="image" src="https://github.com/ant-design/pro-components/assets/35751066/0ad0c4a9-adc4-4026-bff3-4f1b40281864">

**Comment by NeverGiveUp1995** [comment]
![Image](https://github.com/user-attachments/assets/b1feddb3-3a12-4854-a920-4f3147e6f35b)

![Image](https://github.com/user-attachments/assets/e0108fb2-f6e4-41f5-ad53-e8ab977dcf6d)

我也遇到了，在设置了initialValue之后能复现
