### ISSUE TITLE
🐛[BUG]低版本的Chromium内核新版pro-layout样式错乱

### ISSUE THREAD

**Issue by Aug-Sunrise** [ant-design/pro-components#6238]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

在低版本的chromium内核浏览器（chrome70、最新版的QQ浏览器）中，新版pro-layout的样式错乱，旧版样式（6.38.X）不存在此问题

### 📷 复现步骤

直接使用低版本的浏览器查看新版pro-layout即可，例如chrome70，基于chromium 70的最新版本的国产浏览器（QQ等）等

### 🏞 期望结果

样式正常

### 💻 复现代码

线上示例（请用chrome70浏览器打开）：https://api.augsunrise.com/

### © 版本信息

- ProComponents 版本: [2.3.34]
- umi 版本: 4.0.30
- 浏览器环境: 最新版QQ浏览器（基于chromium内核）
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![1668672251669](https://user-images.githubusercontent.com/51350414/202391291-0562a7ed-89fa-4129-bd86-71c9833b320a.jpg)

**Comment by jianfenkezhan** [comment]
same issue.
谷歌浏览器版本 81.0.4044.138（正式版本） （64 位)

**Comment by chenshuai2144** [comment]
最低保持的 chrome 89 吧，国产浏览器的兼容问题太多了
