### ISSUE TITLE
🐛[BUG] [Pro-Table] rowSelection设置preserveSelectedRowKeys为true，翻页只保留了rowKeys没有保留rows

### ISSUE THREAD

**Issue by luotongzhou** [ant-design/pro-components#6240]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

owSelection设置preserveSelectedRowKeys为true，翻页只保留了rowKeys的值没有保留rows的值

### 📷 复现步骤

1. 设置pro-table rowSelection.preserveSelectedRowKeys = true
2. 设置pro-table toolBarRender={(action, { selectedRows, selectedRowKeys }) => {
        console.log('selectedRows: ', selectedRowKeys, selectedRows)
        return <div />
      }}
3. 第一页选中几个，翻页异步获取数据，继续选中几个，查看控制台
<img width="510" alt="image" src="https://user-images.githubusercontent.com/27920863/202430940-7a796cba-463c-4c21-a4e7-5c581b551d8b.png">

### 🏞 期望结果

设置 rowSelection.preserveSelectedRowKeys = true时，rowKeys 和 rows 的值都能得到保留

### 💻 复现代码
源码相关信息, 每次 dataSource 变化 preserveRecordsRef 和 newCache 都会变， 导致 selectedRowsRef 只能拿到当前页的 rows数据
<img width="548" alt="image" src="https://user-images.githubusercontent.com/27920863/202431158-80e571b1-b6c1-4aeb-a2dc-e3fdc44c585f.png">

### © 版本信息

- ProComponents 版本: [2.3.34]
- 浏览器环境 chrome 100+
- 开发环境 [ mac OS]

### 🚑 其他信息
 antd 5.0.0-rc.1

**Comment by luotongzhou** [comment]
虽然可以在 rowSelection.onChange 事件通过受控方式解决的我的需求，但无疑增加了整个页面的渲染负担，毕竟除了表格还会有其他组件在当前页面，会增加性能优化的负担

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


对于 `ProTable` 组件中的 `rowSelection` 设置 `preserveSelectedRowKeys` 属性为 `true` 后，在翻页时只保留了 `rowKeys` 而没有保留 `rows` 的问题，可以通过以下两个步骤解决：

1. 在这个 `ProTable` 组件的 state 中增加一个 `selectedRows` 的数组，用来存储选中的所有行数据。

```jsx
const [selectedRows, setSelectedRows] = useState([]);
```

2. 在 `rowSelection` 的 `onChange` 事件中，更新这个 `selectedRows` 的值。

```jsx
const rowSelection = {
  onChange: (selectedRowKeys, selectedRows) => {
    setSelectedRows(selectedRows);
  },
  selectedRowKeys,
  type: 'checkbox',
  preserveSelectedRowKeys: true,
};

return (
  <ProTable
    ...
    rowSelection={rowSelection}
    dataSource={dataSource}
    // 在 ProTable 中增加 onSelectRow 函数来记录选中的行数据
    onSelectRow={(record, selected, selectedRows) => {
      setSelectedRows(selectedRows);
    }}
    ...
  />
);
```

这样，我们就可以在 `selectedRows` 数组中存储所有选中的行数据，并在翻页时保留下来。另外，`onSelectRow` 函数也很关键，它记录了选中的所有行数据，并触发了 `rowSelection` 的 `onChange` 事件，从而更新了 `selectedRows` 数组的值。

参考文档：

- [antd pro-table 的rowSelection 还原选中数据](https://blog.csdn.net/weixin_47368643/article/details/113874657)

**Comment by chenshuai2144** [comment]
已经全部使用了antd的语法了，再试试
