### ISSUE TITLE
🐛[BUG] EditableProTable中valueEnum的map的key是数字时初始值不会根据map表替换

### ISSUE THREAD

**Issue by frank-pian** [ant-design/pro-components#6241]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

当可变表格初始值设置为number时，不会根据columns中的valueEnum map表进行替换，但是字符串是可以的。

### 📷 复现步骤

![火狐截图_2022-11-17T17-24-18 782Z](https://user-images.githubusercontent.com/8214804/202515126-680c9dc0-24bc-418d-8f94-873ab42f6599.png)

### 🏞 期望结果

能支持初始值number时也进行自动替换
![火狐截图_2022-11-17T17-29-38 834Z](https://user-images.githubusercontent.com/8214804/202516240-f6bd0a16-6e82-485a-888f-847dd8c6afdd.png)

### 💻 复现代码

columns列定义
```
{
title: '权限等级',
key: 'user_level',
dataIndex: 'user_level',
valueType: 'select',
valueEnum: {
//初始值不能根据这里自动替换
  1: { text: '系统管理员', status: 'Success' },
  2: {
    text: '终端用户',
    status: 'Success',
  },
  3: {
    text: '网络管理用户',
    status: 'Success',
  },
},
},
```
EditableProTable新建行的初始值
```
recordCreatorProps={{
  position: 'bottom',
  record: {
    key: (Math.random() * 1000000).toFixed(0),
    user_name: '',
//当user_level改为字符串时才可以替换
    user_level: 1,
  },
}}
```

### © 版本信息

- ProComponents 版本: 1.1.1
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by xliez** [comment]
valueEnum 其实是普通的Object类型，遵循js对象的规范：属性的键必须是字符串或者 symbol
所以这里key其实是字符串的“1”
