### ISSUE TITLE
🧐[问题] ModalForm 标题和在Form表单内容展示中，间距是否过小呢？是否需要在设计上进行调整？

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#6244]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/30397655/202659941-80250e7c-51d2-4878-9289-072f596ab5da.png">

**Comment by leshalv** [comment]
@chenshuai2144 名望程序员

**Comment by chenshuai2144** [comment]
有减少间距的设计倒是没有放大的，你可以调整下padding 和 margin的token试试。
不推荐在这种不影响使用的样式上雕花，浪费精力
