### ISSUE TITLE
🐛[BUG] ProFormCheckbox.Group 在 ModalForm 不会自动换行布局

### ISSUE THREAD

**Issue by Adherentman** [ant-design/pro-components#6247]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProFormCheckbox.Group 在 ModalForm 不会自动换行布局
![image](https://user-images.githubusercontent.com/26477346/202890043-e788bbbd-89b3-4e46-a08a-f62496310527.png)

### 📷 复现步骤

```jsx
<ModalForm
      title={title}
      form={form}
      visible={visible}
      modalProps={{
        destroyOnClose: true,
        onCancel: close,
      }}
    >
      <Spin spinning={loading}>
        <ProForm.Group>
          <ProFormText width="md" name="title" label="单品名称" placeholder="请输入单品名称" disabled={disabled} />
          <ProFormText
            width="md"
            name="name"
            label="单品标识"
            placeholder="请输入单品标识"
            tooltip="长度4位，类似1001"
            disabled={disabledName}
          />
        </ProForm.Group>
        <ProFormCheckbox.Group
          name="checkbox-group"
          label="Checkbox.Group"
          options={[
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
          ]}
        />
      </Spin>
    </ModalForm>
```

### © 版本信息

- ProComponents 版本: 
  - "@ant-design/pro-components": "^2.3.34",
  - "@ant-design/pro-descriptions": "^2.0.30",
  - "@ant-design/pro-form": "^2.3.2",
  - "@ant-design/pro-table": "^3.1.8",
  - "antd": "5.x",
- 浏览器环境 edge
- 开发环境 mac

**Comment by Bill-sh** [comment]
等待修复

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


问题分析：

ProFormCheckbox.Group 是 antd 中的 Checkbox.Group 的封装组件，它默认的布局是一行展示。而使用 ProFormCheckbox.Group 在 ModalForm 中时，由于 Modal 的宽度限制，导致多个 Checkbox 没有办法自动换行，从而出现了上面的问题。

解决方案：

1. 自定义样式

可以通过自定义样式解决这个问题。将 ProFormCheckbox.Group 的样式设置为 display: block，这样 Checkbox 会自动换行。

```CSS
.ant-form-item-control-input-content {
  display: block;
}
```

2. 自定义 ProFormCheckbox 组件

可以自定义一个 ProFormCheckbox 组件，将 Checkbox.Group 放到一个 Flex 布局的容器中，实现自动换行。

```jsx
import { Checkbox } from 'antd';
import Field from '@ant-design/pro-field';

const ProFormCheckboxGroup = (props) => {
  const { options, label, name } = props;
  const group = options.map((option) => (
    <Checkbox value={option} key={option}>
      {option}
    </Checkbox>
  ));

  return (
    <Field
      name={name}
      label={label}
      valueType="checkbox"
      mode="edit"
      initialValue={[]}
      render={(formItemProps, { getFieldValue, setFieldsValue }) => {
        const value = getFieldValue(name) || [];

        function onChange(checkedValues) {
          setFieldsValue({ [name]: checkedValues });
        }

        return (
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px' }}>
            <Checkbox.Group options={options} onChange={onChange} value={value} />
          </div>
        );
      }}
    />
  );
};
```

使用时，可以将 ProFormCheckbox.Group 替换为自定义的 ProFormCheckboxGroup 组件。

```jsx
<ProFormCheckboxGroup
  name="checkbox-group"
  label="Checkbox.Group"
  options={[
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
  ]}
/>
```

参考文档：

- antd Checkbox.Group：https://ant.design/components/checkbox-cn/#Checkbox-Group
- CSS display 属性：https://developer.mozilla.org/zh-CN/docs/Web/CSS/display
- Flex 布局：https://developer.mozilla.org/zh-CN/docs/Learn/CSS/CSS_layout/Flexbox
