### ISSUE TITLE
👑 [需求] 希望ProLayout 移动端菜单展开后可以点击遮罩（mask）关闭，并将autoclose功能加上

### ISSUE THREAD

**Issue by hinego** [ant-design/pro-components#6248]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

ProLayout

### 🥰 需求描述

ProLayout 移动端菜单展开后可以点击遮罩（mask）关闭，并将autoclose功能加会

如果两者都开启的情况下就是点击一个菜单后自动关闭，或者点击遮罩后关闭

### ⛰ 功能需求适用场景

移动端收起菜单

### 🧐 解决方案

没找到给遮罩层添加onClick的API

**Comment by xXAvoraXx** [comment]
这个问题有什么解决办法吗？

**Comment by Bollie15** [comment]
@chenshuai2144 我发现官网的案例还是无法点击遮罩层关闭啊
