### ISSUE TITLE
🐛[BUG]拖拽组件放到抽屉或者弹窗中进行拖拽时, 被拖拽的元素会消失

### ISSUE THREAD

**Issue by xieww** [ant-design/pro-components#6250]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

1. 拖拽组件放到抽屉或者弹窗中进行拖拽时, 虽然可以可以拖拽，但是被拖拽的元素会消失；
2. 不在抽屉或者弹窗里面的拖拽表格，被拖拽样式丢失

### 📷 复现步骤

1. 在弹窗或者抽屉拖拽元素，被拖拽元素会消失；

### 🏞 期望结果

不管是否在弹窗或者抽屉里面都能正常拖拽排序，且被拖拽元素在拖拽过程中元素可见，样式不丢失，

### 💻 复现代码

https://codesandbox.io/s/small-dust-qf91wo?file=/src/App.tsx

### © 版本信息

- ProComponents 版本: 2.3.34
- umi 版本: 无
- 浏览器环境: 谷歌105.0.5195.102
- 开发环境: window

### 🚑 其他信息
![20221121114914](https://user-images.githubusercontent.com/26969239/202961748-553c9490-c2d9-41dd-8a60-84e3c979c403.gif)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


根据复现步骤和期望结果的描述，可以推断这个问题是由于被拖拽的元素在弹窗或抽屉组件内部，导致元素在拖拽过程中因为样式问题而被隐藏或丢失。为了解决这个问题，我们可以尝试以下方案：

1. 设置被拖拽的元素的 z-index 值，确保元素在拖拽过程中始终处于最上层，不被其他元素遮挡；
2. 在弹窗或抽屉组件中，禁用 overflow 属性，确保元素能够正常显示，不被容器裁剪；
3. 使用第三方拖拽库，如 react-beautiful-dnd、react-dnd 等，这些库可以更好地处理拖拽和样式问题，并且可以提供更多的可定制化选项；

对于第一种解决方案，我们可以将被拖拽的元素设置一个较高的 z-index 值，例如：

```tsx
const handleDragStart = (item, monitor, component) => {
  const dragDom = findDOMNode(component);
  dragDom.style.zIndex = 9999; // 设置元素的 z-index 值
  setDragging(true);
  setDraggedItem(item);
};
```

对于第二种解决方案，我们可以在弹窗或抽屉组件中禁用 overflow 属性，例如：

```tsx
// Drawer.tsx
const Drawer = ({ children, ...restProps }) => {
  return (
    <AntdDrawer
      {...restProps}
      style={{ overflow: 'visible' }} // 禁用 overflow 属性
    >
      {children}
    </AntdDrawer>
  );
};
```

对于第三种解决方案，我们可以使用 react-beautiful-dnd 库来替换 ProTable 中自带的拖拽功能。具体用法和示例可以参考该库的官方文档：https://github.com/atlassian/react-beautiful-dnd

同时，建议自己阅读代码进行优化。

**Comment by chenshuai2144** [comment]
修复啦，换个底层实现
