### ISSUE TITLE
🧐[问题] Ant Design v5 dark mode pro table header wrong color

### ISSUE THREAD

**Issue by fitterfizzle** [ant-design/pro-components#6252]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

When using the dark mode from ant design v5, the table color header is wrong, as it is black on black

<img width="251" alt="image" src="https://user-images.githubusercontent.com/96863959/203057900-e6f5f71e-0d44-4343-943b-8608a5eaeecb.png">

Same for the buttons 

<img width="202" alt="image" src="https://user-images.githubusercontent.com/96863959/203057988-ae4ba446-6df2-455b-a8cb-90b741e1ea57.png">

How to achieve the dark mode color as it is on the official documentation?

<img width="998" alt="image" src="https://user-images.githubusercontent.com/96863959/203057694-cf303e11-e71a-4f06-a715-3452c3aed5ae.png">

**Comment by fitterfizzle** [comment]
Any news?

**Comment by fitterfizzle** [comment]
Any news?

**Comment by fitterfizzle** [comment]
Thank you @chenshuai2144 with the latest version this is now also fixed. Feel free to close the issue.

**Comment by chenshuai2144** [comment]
Please upgrade to the latest version because of hasid
