### ISSUE TITLE
🐛[BUG]ProFormSelect下的request在option清除后会重新请求（参数keyWords变化了）

### ISSUE THREAD

**Issue by lybdx** [ant-design/pro-components#6255]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProFormSelect或者table的column的valueType为select，使用request远程请求后，在点击清除按钮后，request会重新请求，因为参数keyWords变了

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/7543537/203190573-61cd002d-0868-41d3-915f-6de62822d8a6.png)
1、点击右侧的清除按钮
2、会重新请求request，因为参数的keyWords变化了
![image](https://user-images.githubusercontent.com/7543537/203190730-2d97aede-3acd-4df8-ad61-821124d42ff6.png)

查了下源码，clear的时候，会把keyword赋值为空字符串
![image](https://user-images.githubusercontent.com/7543537/203190874-b4fec4f6-dcaf-4cb1-aff1-a0bd2139c332.png)

### 🏞 期望结果

不重新请求

### 💻 复现代码

提供可复现的代码，仓库，或线上示例

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/commit/387d2d7108a9e555158e4afc7e7096ff729eeecf
