### ISSUE TITLE
❓[帮助] EditableProTable 中的Request请求是不是有缓存？

### ISSUE THREAD

**Issue by ByYogi** [ant-design/pro-components#6257]
### 🧐 问题描述
`EditableProTable` 行的`Select-request`好像有缓存。第一次进页面会发送api请求，第二次进会使用上一次请求的数据，调式网络看没有发送请求。
以为是umi-request的缓存问题，尝试在`request`加随机参数，加`useCache: false`都没用。通过日志打印发现是列属性的request没有调用api请求方法。

**请问是不是 `ProTable-columns` 有缓存的问题?该如何解决**
### 💻 示例代码
``` typescript
const columns:ProColumns<DS_Data.PR1_Item>[] = [
  {
    dataIndex: "VatGroup",
    title: "GST",
    valueType: "select",
    request: GetVatgroups,
  }
]
```
![image](https://user-images.githubusercontent.com/111735598/203254055-47cf2e47-24b0-4d5f-9198-77fe6eff711f.png)

**Comment by ByYogi** [comment]
#3688  
> rquest 请求的是 initvalues，他只会第一次生效
> 给他设置一个key。key 变化就会清空重来
> -- [chenshuai2144](https://github.com/chenshuai2144)

#4393 `params: { timestamp: Math.random() }`

通过搜寻总结，以下配置能解决我的问题：
``` typescript
dataIndex: "VatGroup",
key: "noRepeat",  //防止被记录
title: "GST",
valueType: "select",
params: { timestamp: Math.random() }, //传随机值
request: GetVatgroups,
```

**Comment by ByYogi** [comment]
最后还是选择将数据存储在`useState`中，这样就不会出现啥乱起八糟的问题了
`const [taxcodes, setTaxcodes] = useState<DefaultOptionType[]>();`
`GetVatgroups().then((res) => setTaxcodes(res));`
``` typescript
dataIndex: "VatGroup",
title: "GST",
valueType: "select",
fieldProps: {
  allowClear: false,
  options: taxcodes,
},
```

**Comment by seifenk** [comment]
我就是想让它走缓存怎么办，现在每添加一行select就会请求一次

**Comment by ByYogi** [comment]
> 我就是想让它走缓存怎么办，现在每添加一行select就会请求一次

options存放在state中。useEffect 检查依赖项没有收到行数据影响。
``` tsx
fieldProps: {
  options: options,
},
```

**Comment by 52906** [comment]
定义：  const [timestamp] = useState(Math.random());

使用：params: { timestamp },

这样应该就只在进入页面重新request了
