### ISSUE TITLE
❓[帮助]更新了pro-components后，加载动画中间会插个 “loading...” text文本

### ISSUE THREAD

**Issue by ByYogi** [ant-design/pro-components#6262]
更新了pro-components后，加载动画中间会插个 “loading...” text文本  #6261

**Comment by chenshuai2144** [comment]
是umi 给默认提供的吧，pro-components 也没提供文本loading

**Comment by ByYogi** [comment]
> 是umi 给默认提供的吧，pro-components 也没提供文本loading

谢谢你，我找到了umi相关说明文档：[umi_v3: 如何禁用掉每次刷新路由时出现的-loading-状态？](https://v3.umijs.org/docs/faq#%E5%A6%82%E4%BD%95%E7%A6%81%E7%94%A8%E6%8E%89%E6%AF%8F%E6%AC%A1%E5%88%B7%E6%96%B0%E8%B7%AF%E7%94%B1%E6%97%B6%E5%87%BA%E7%8E%B0%E7%9A%84-loading-%E7%8A%B6%E6%80%81%EF%BC%9F)
