### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by hsulei** [ant-design/pro-components#6263]
### 🧐 问题描述

更新antd5.0和ProComponents2.0 使用antd中的ConfigProvider 定义theme token 无法影响ProTable 中的按钮主题色，如何通过ConfigProvider修改ProComponents的主题色？

### 💻 示例代码

```tsx
 <ConfigProvider locale={zhCN} theme={{ token: { colorPrimary: '#7ED321', borderRadius: 4 } }}>
        <ConfigProviderWrap>
          <RouterProvider router={router} />
        </ConfigProviderWrap>
      </ConfigProvider>
```

### 🚑 其他信息
"antd": "^5.0.1",
"@ant-design/pro-components": "^2.3.34",
"vite": "^3.0.0"

**Comment by XuJin186** [comment]
等待解决  我也遇到了

**Comment by Teeoo** [comment]
```tsx
import { ConfigProvider } from "antd";

ConfigProvider.config({
  theme: {
    primaryColor: '#1677FF',
    // primaryColor: '#FF6F00',
  },
});
```

没啥问题啊

**Comment by hs-ltbyce** [comment]
也有同样问题

**Comment by Teeoo** [comment]
```tsx
<ConfigProvider
        theme={{
            token: {
                colorPrimary: '#5A54F9'
            }
        }}
    >
        <Outlet />
</ConfigProvider>
```

好像没啥问题

**Comment by hs-ltbyce** [comment]
@Teeoo 不行吧，colorPrimary改的只是antd的seedToken ，而pro本来就是基于antd开发的上层组件，所以看起来是有效的。但是它内部还有很多自定义样式，没有办法通过token进行修改。

**Comment by hsulei** [comment]
我使用`ConfigProvider` 只是改变了单独的`Antd`组件， `ProTable`这些`pro-components`中的按钮主题色是不能改变的

**Comment by Teeoo** [comment]
0.0 有可能我们说的按钮不是一个东西
我说的按钮是toolBarRender中的东西你们说的是啥

**Comment by hsulei** [comment]
@Teeoo 你的能变色？ 我`ProTable`中的toolBarRender 不行啊， `search`中的按钮也不行

**Comment by hsulei** [comment]
@Teeoo  还是说我ConfigProvider放的位置不对？

**Comment by Teeoo** [comment]
可以啊

**Comment by hsulei** [comment]
@Teeoo  我那样写法没有效果啊，组件版本应该都是对的啊

**Comment by hsulei** [comment]
@Teeoo  很奇怪， 我是吧ConfigProvider加在<RouterProvider router={router} />上的，LoginFormPage的主题色可以改变，但ProTable里面的主题色改不了，需要再改<Outlet />外面再包一个

**Comment by KarasuShin** [comment]
``` ts
 <ConfigProvider theme={{
      token: {
        colorPrimary: palette.primary,
        colorPrimaryHover: palette.primary,
      },
    }}>
    <RouterProvider router={routes} />
  </ConfigProvider>
```
我通过这种方式传递token，colorPrimaryHover生效了，但是colorPrimary未生效

**Comment by hsulei** [comment]
> 

不知道是不是ProLayout里是不是又干了啥，我要在ProLayout中在加一个ConfigProvider才有用

**Comment by Teeoo** [comment]
![image](https://user-images.githubusercontent.com/25023667/204413930-f1ccdcf7-29f9-4bfb-a1a9-6a0d0e142836.png)
![image](https://user-images.githubusercontent.com/25023667/204414017-c8421f3d-4aed-40a2-b9c3-24309b190dab.png)

**Comment by hsulei** [comment]
@Teeoo  没用umi..

**Comment by Teeoo** [comment]
应该和umi没啥关系吧

**Comment by hsulei** [comment]
![image](https://user-images.githubusercontent.com/12029069/204414598-2f34ce7b-ffc3-4b50-b644-2b327b3db5f0.png)
![image](https://user-images.githubusercontent.com/12029069/204414646-8f8667bd-0efb-484e-8b27-a5b29297758b.png)

**Comment by Teeoo** [comment]
啊这.... 不清楚啥情况你这块是写哪的？(这是gql项目么0.0

**Comment by hsulei** [comment]
@Teeoo  你的这个配置，是在ProLayout的children里面的吧？

**Comment by Teeoo** [comment]
新建的layout

**Comment by hsulei** [comment]
@Teeoo  有用ProLayout吗？

**Comment by Teeoo** [comment]
```json
"dependencies": {
    "@ant-design/icons": "^4.8.0",
    "@ant-design/pro-components": "^2.3.35",
    "@lottiefiles/react-lottie-player": "^3.4.9",
    "@umijs/max": "^4.0.33",
    "ahooks": "^3.7.2",
    "antd": "^5.0.2",
    "crypto-js": "^4.1.1",
    "fuzzy": "^0.1.3",
    "inquirer-autocomplete-prompt": "^3.0.0",
    "lodash": "^4.17.21",
    "nunjucks": "^3.2.3",
    "qiniu-js": "^3.4.1",
    "typed.js": "^2.0.12",
    "umi-presets-pro": "^1.0.8"
  }
```

**Comment by hsulei** [comment]
不是这个，我的layout组件里面是
![image](https://user-images.githubusercontent.com/12029069/204415760-a354be3d-cf16-427c-b649-3303c748f3b4.png)
然后<ConfigProvider>是在这个<ProLayout>组件外面的

**Comment by hs-ltbyce** [comment]
@hsulei 因为 ProConfigProvider 是这样搞得：
path: packages\provider\src\index.tsx
```
  return (
    <AntdConfigProvider {...configProvider}>
      <ConfigProVoidContainer {...props} token={token} />
    </AntdConfigProvider>
  );
```
昨天看了一下源码, pro里面自己写了一套defaultToken,默认使用了antd的defaultAlgorithm算法作为缺省，目前确实是不支持用antd的token
packages\provider\src\useStyle\token.ts
```
export const defaultToken = {
customToken,
...(theme?.defaultAlgorithm?.(theme?.defaultSeed) as any),
...
}
```

**Comment by Teeoo** [comment]
你在不受影响的地方单独套个ConfigProvider生效不？

**Comment by hsulei** [comment]
那需要再ProLayout里面在包一下了

**Comment by chenshuai2144** [comment]
我修复了一下这个问题，发完版本就可以完美使用了

**Comment by XuJin186** [comment]
> 我修复了一下这个问题，发完版本就可以完美使用了

坐等更新

**Comment by XuJin186** [comment]
@chenshuai2144  这是啥奇葩设计？      algorithm: dark ?? proProvide.dark ? darkAlgorithm : defaultAlgorithm,
https://github.com/ant-design/pro-components/blob/0044bcdba504f4c7c610a9d3720995a4d4d40460/packages/provider/src/index.tsx#L465

除了dark我不能设置别的了嘛？compact和dark一起用不行嘛

**Comment by hsulei** [comment]
2.3.36?

**Comment by XuJin186** [comment]
> 2.3.36?

是的

**Comment by hsulei** [comment]
@XuJin186  我指的是说修复的版本，我更新了还是不行么

**Comment by XuJin186** [comment]
本质上ant的Provide和pro的Provide  用户自己都要去配置,现在这个设计更偏向umi 一个dark属性搞定

**Comment by XuJin186** [comment]
的确无效

**Comment by hooliy** [comment]
解决了吗？在config下配置token不生效

![image](https://user-images.githubusercontent.com/3368691/206380291-d469e2dd-0806-4da3-a3df-e9291a20a9d4.png)

**Comment by hsulei** [comment]
没得，现在我的做法 在PayLayout里面再写一遍

**Comment by hooliy** [comment]
刚发的 [2.3.42](https://github.com/ant-design/pro-components/releases/tag/%40ant-design%2Fpro-components%402.3.42) 版本解决了，已经支持 configProvider 配置了，但是 theme 配置方法还不支持，不过已经很好了

**Comment by hsulei** [comment]
额，我最新版本更新不了么。。找不到包

**Comment by hsulei** [comment]
> ```tsx
> #7ED321
> ```

我试试看

**Comment by hooliy** [comment]
@hsulei 切换到国外源，淘宝源还没同步

**Comment by XuJin186** [comment]
现在的本质就是pro版本根本没用antd token那一套  感觉还在兼容antd4的写法      我理想状态就是pro引用绝大部分antd的token 自己只定义一些必要的token   那这样antd设置为dark  pro也会跟着变

**Comment by XuJin186** [comment]
![image](https://user-images.githubusercontent.com/43058612/206406619-f391a728-34ca-4662-9ad5-0e0d156a177a.png)
官方的demo也出现了一定的问题

**Comment by Thyiad** [comment]
> > ```tsx
> > #7ED321
> > ```
> 
> 我试试看

Hi，请问你最后怎么解决的？

**Comment by iCyris** [comment]
问题依旧存在...

不引入 Pro 组件的情况下，Button 的样式是正常的；但只要引入了 Pro 组件，用 ConfigProvider theme token 配置的形式配置的主题就会失效，会被 Pro 的样式资源覆盖掉。

```
import { ConfigProvider, Button } from 'antd';
import { ProTable } from '@ant-design/pro-components'; // 去掉这行，Button 的样式就是正常的

const THEME_CONFIG = {
    token: {
      colorPrimary: '#4f84cf',
      colorBgContainer: '#fffffe',
      borderRadius: 4,
      wireframe: true,
    },
  };

export default () => {
  return (
      <ConfigProvider theme={THEME_CONFIG}>
        <Button>xxx</Button>
        <ProTable {...} />
      </ConfigProvider>
  )
}

```
<img width="333" alt="image" src="https://user-images.githubusercontent.com/27601858/233817343-028bd08a-ba0a-4288-8993-5d05b75a81db.png">
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/27601858/233817357-a4347cd9-7407-4314-a8d0-0ba958adc115.png">
