### ISSUE TITLE
🐛[BUG]ProLayout does not work with React 18 

### ISSUE THREAD

**Issue by shjerryzhou** [ant-design/pro-components#6264]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

升级到React 18后, ProLayout无法渲染，查看浏览器里面的日志，出现很多错误：
index.mjs:634 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at useSWRHandler (index.mjs:634:1)
    at useSWRArgs (index.mjs:612:1)
    at BaseProLayout (ProLayout.js:201:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
useSWRHandler @ index.mjs:634
useSWRArgs @ index.mjs:612
BaseProLayout @ ProLayout.js:201
renderWithHooks @ react-dom.development.js:16305
updateFunctionComponent @ react-dom.development.js:19588
beginWork @ react-dom.development.js:21601
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performSyncWorkOnRoot @ react-dom.development.js:26096
flushSyncCallbacks @ react-dom.development.js:12042
commitRootImpl @ react-dom.development.js:26959
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18687 The above error occurred in the <BaseProLayout> component:

    at BaseProLayout (http://localhost:3001/static/js/bundle.js:14779:13)
    at FormProvider (http://localhost:3001/static/js/bundle.js:88668:31)
    at LocaleProvider (http://localhost:3001/static/js/bundle.js:46893:90)
    at ProviderChildren (http://localhost:3001/static/js/bundle.js:40521:24)
    at LocaleReceiver (http://localhost:3001/static/js/bundle.js:46768:90)
    at ConfigProvider (http://localhost:3001/static/js/bundle.js:40624:13)
    at div
    at SWRConfig$1 (http://localhost:3001/static/js/bundle.js:169152:21)
    at ConfigProviderWrap (http://localhost:3001/static/js/bundle.js:20702:24)
    at ProviderChildren (http://localhost:3001/static/js/bundle.js:40521:24)
    at LocaleReceiver (http://localhost:3001/static/js/bundle.js:46768:90)
    at ConfigProvider (http://localhost:3001/static/js/bundle.js:40624:13)
    at ProLayout (http://localhost:3001/static/js/bundle.js:15073:28)
    at header
    at div
    at App

经过调试，发现ProLayout.js下面的userState进去了两次，第二次，defaultId=’pro-layout-2'的时候报错。
  var _useState = useState(function () {
      layoutIndex += 1;
      return "pro-layout-".concat(layoutIndex);
    }),

### 📷 复现步骤
1. 通过yarn create react-app web-test --template typescript创建一个react项目.
2. yarn add antd @ant-design/pro-components添加依赖。
3. 检查react, react-dom版本，均为18.2.0.
4. 修改App.tsx, 添加最简单的ProLayout。
```
   function App() {

  return (
    <div className="App">
        <ProLayout id="layout">
          <PageContainer title="测试" />
        </ProLayout>
    </div>
  );
}
```

5. 启动项目 yarn start.
6. 浏览器中打开地址”http://localhost:3000，页面无法显示。
7. 修改index.tsx代码：
```
// const root = createRoot(
//     document.getElementById('root') as HTMLElement
// );
//
// root.render(
//     <React.StrictMode>
//       <App />
//     </React.StrictMode>
// );

ReactDOM.render(
    <React.StrictMode>
      <App />
    </React.StrictMode>,
    document.getElementById('root') as HTMLElement);
```
8. 错误消失。页面可以正常显示。
9. 结论：ReactDOM.render在react18中列为将被移除的功能，官方要求改成createRoot的方式。但是createRoot的方式ProLayout无法正常显示。

### 🏞 期望结果

在createRoot方式下，页面正常显示ProLayout，不出现错误。

### 💻 复现代码
index.tsx
```
// 不能正常显示的代码
// const root = createRoot(
//     document.getElementById('root') as HTMLElement
// );
//
// root.render(
//     <React.StrictMode>
//       <App />
//     </React.StrictMode>
// );

// 可以正常显示的代码
ReactDOM.render(
    <React.StrictMode>
      <App />
    </React.StrictMode>,
    document.getElementById('root') as HTMLElement);

```

app.tsx
```
function App() {

  return (
    <div className="App">
        <ProLayout id="layout">
          <PageContainer title="测试" />
        </ProLayout>
    </div>
  );
}
```
### © 版本信息

- ProComponents 版本: 2.3.34
- Antd版本：4.23.3
- 浏览器环境：Chrome
- 开发环境 : mac OS

### 🚑 其他信息
试过其它版本ProComponents：2.3.35， Antd： 5.0.0，同样的问题

**Comment by yikuyirong** [comment]
去掉 <React.StrictMode /> 试试

**Comment by liuzhaowei55** [comment]
> 去掉 <React.StrictMode /> 试试

遇到相同的问题，这个解决方案有效。

**Comment by folt** [comment]
I am getting this error. StrictMode is the mode that reports a potential problem. ProLayout has some potential problems that weren't there before.

**Comment by DODO7419** [comment]
什么时间能修复这个问题呢

**Comment by liu-wh** [comment]
去掉<React.StrictMode />可以正常渲染, 但是当使用路由跳转时, 会再次报错

**Comment by zjf9035** [comment]
> 去掉<React.StrictMode />可以正常渲染, 但是当使用路由跳转时, 会再次报错

同路由跳转报错，有啥解决办法吗

**Comment by chenshuai2144** [comment]
各位更新下最新版本，升级到了 swr@2

**Comment by liu-wh** [comment]
> 各位更新下最新版本，升级到了 swr@2
刚刚试了一下, 升级到了2.3.37, 还是会报错, 不过报错变
![image](https://user-images.githubusercontent.com/52809998/208611619-8fd46bb7-8b80-48d7-9eb8-f95812c14573.png)

**Comment by chenshuai2144** [comment]
create react app 看起来是没有问题的。

**Comment by horizon0514** [comment]
这个问题有进展吗

**Comment by horizon0514** [comment]
> create react app 看起来是没有问题的。

nextjs 有问题

**Comment by guojiabing** [comment]
![image](https://user-images.githubusercontent.com/39938818/221462412-35828d81-a0bc-47b9-b1c7-1aba3e15b356.png)
我也是相同的问题，你那解决了吗？


> ![image](https://user-images.githubusercontent.com/52809998/208611619-8fd46bb7-8b80-48d7-9eb8-f95812c14573.png)

**Comment by zhiwehu** [comment]
+1

**Comment by hsbtr** [comment]
这个问题有进展吗？在使用antd 5.4.7 pro-component 2.4.14还是有这个问题；路由跳转就会报错

**Comment by hsbtr** [comment]
> create react app 看起来是没有问题的。

react 18.x版本使用路由跳转就会有这个问题

**Comment by hsbtr** [comment]
> > 去掉<React.StrictMode />可以正常渲染, 但是当使用路由跳转时, 会再次报错
> 
> 同路由跳转报错，有啥解决办法吗

如何组件是以react.lazy导入，那么在prolayout中就必须使用react.suspense包裹outlet组件，不能再prolayout外层使用react.outlet，这样会造成prolayout出现闪烁问题，同时也会造成路由跳转就报错
![image](https://github.com/ant-design/pro-components/assets/46487804/4560e979-15ab-4c40-bdb8-1bfa7389bf45)

**Comment by liu-wh** [comment]
> > > 去掉<React.StrictMode />可以正常渲染, 但是当使用路由跳转时, 会再次报错
> > 
> > 
> > 同路由跳转报错，有啥解决办法吗
> 
> 如何组件是以react.lazy导入，那么在prolayout中就必须使用react.suspense包裹outlet组件，不能再prolayout外层使用react.outlet，这样会造成prolayout出现闪烁问题，同时也会造成路由跳转就报错 ![image](https://user-images.githubusercontent.com/46487804/238528265-4560e979-15ab-4c40-bdb8-1bfa7389bf45.png)

试着在Outlet外侧加了Suspense, 解决了 感谢!!!
