### ISSUE TITLE
👑 [需求] ProLayout侧边栏收起展示title字数增加

### ISSUE THREAD

**Issue by cjnchk** [ant-design/pro-components#6265]
### 🔩 所属模块或组件
组建：ProLayout

### 🥰 需求描述

目前收起时展示title布局没有实用价值，按照文档描述，收起时无法调整侧栏宽度，title只能展示1个字，希望能增加到3~4个字的展示宽度

**Comment by chenshuai2144** [comment]
<img width="131" alt="image" src="https://user-images.githubusercontent.com/8186664/205216631-55144ec6-a02a-46d6-9026-fd1354f48693.png">

推荐这样展示两个字为主
