### ISSUE TITLE
👑 [需求] ProLayout增加一种布局方式

### ISSUE THREAD

**Issue by cjnchk** [ant-design/pro-components#6267]
### 🔩 所属模块或组件

组件：ProLayout

### 🥰 需求描述

希望能增加一种布局方式：在侧栏为一级路由的基础上增加一个顶栏的布局，如下图：
![image](https://user-images.githubusercontent.com/11740050/203484221-9dbd2326-3a4d-4afc-b8de-cd94c83c6741.png)

**Comment by ONLY-yours** [comment]
看起来用两个layout就可以？
外层side 内层header

**Comment by chenshuai2144** [comment]
楼上正解
