### ISSUE TITLE
🐛[BUG] ProProvider valueTypeMap不生效

### ISSUE THREAD

**Issue by yuegongzi** [ant-design/pro-components#6269]
### 🐛 bug 描述

从 3.2.27 升级到3.3.35后发现 ProProvider包裹的自定义 valueTypeMap不生效,降级回去后又可以了

### 🏞 期望结果

和3.2.27一致

### © 版本信息

- ProComponents 版本: [e.g. 3.2.35]
- umi 版本 4.0.29
- 浏览器环境 Google Chrome 107.0.5304.110
- 开发环境 [ mac OS Windows 11 ]

**Comment by chenshuai2144** [comment]
他应该是自己管理了 pro-依赖，建议都从pro-components 导入
