### ISSUE TITLE
🧐[问题] ProLayout 左侧菜单，展开的时候，子菜单会抖动一下

### ISSUE THREAD

**Issue by zerox-v** [ant-design/pro-components#6270]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

ProLayout 左侧菜单，展开的时候，子菜单会抖动一下。请问是故意这么设计的么还是BUG?
antd 版本5   
pro-components版本2.3.13  

### 💻 示例代码

无代码官方Demo也会出现这种情况。见下图

### 🚑 其他信息

![123](https://user-images.githubusercontent.com/24620885/203588634-d6b6e195-3c10-4a3d-9a6e-30b89a39d384.gif)

**Comment by xXAvoraXx** [comment]
在手机屏幕上菜单不关闭，你解决了这个问题吗？

**Comment by chenshuai2144** [comment]
是样式的bug，已经修复了，更新一下
