### ISSUE TITLE
🐛[BUG]设置 ProTable columns valueType 为 select 显示的下拉框不能搜索

### ISSUE THREAD

**Issue by bigmgreen** [ant-design/pro-components#6272]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
- 设置 ProTable columns valueType 为 select 显示的下拉框不能搜索

### 🏞 期望结果

- 可以进行搜索
![image](https://user-images.githubusercontent.com/15407254/203706101-f1ad7822-718f-42e9-869c-036373fc38b3.png)

### 💻 复现代码

```js
    {
      ...
      valueType: 'select',
      ...
    }
```

**Comment by bigmgreen** [comment]
renderFormItem: ({ fieldProps }) => {
        return <ProFormSelect showSearch options={fieldProps.options} />
      }
自定义组件可解决

**Comment by chenshuai2144** [comment]
`filedProps ={{ showSearch:true  }}`

加一下这个

**Comment by guwan** [comment]
> `filedProps ={{ showSearch:true }}`
> 
> 加一下这个

这个解决了我的问题。谢谢
