### ISSUE TITLE
🧐[问题] ProFormList里面嵌套ProFormList想要在内层加个按钮校验内层ProFormList

### ISSUE THREAD

**Issue by JackRoy1992** [ant-design/pro-components#6275]
![企业微信截图_20221125105315](https://user-images.githubusercontent.com/49305419/203891013-323d5414-38bf-4774-9247-b0d61f9778f1.png)
期望点击删除的时候只校验当前配置下的所有起始、终止、比例值

**Comment by chenshuai2144** [comment]
用formRef+name 来做判断就行了。

```
  formInstance.validateFields([name])
```
