### ISSUE TITLE
🧐[问题] EditableProTable双击点击编辑保存，但是验证的是全部行

### ISSUE THREAD

**Issue by yang-chuanjiang** [ant-design/pro-components#6276]
<EditableProTable<DataSourceType>
        bordered
        rowKey="id"
        columns={columns}
        className={styles.tableStyle}
        recordCreatorProps={false}
        request={async () => {
          return {
            data: originalData,
            total: originalData.length,
            success: true,
          };
        }}
        value={dataSource}
        onChange={(value) => {
          setDataSource(value);
        }}
        actionRef={actionRef}
        editable={{
          type: 'multiple',
          editableKeys,
          form: form,
          onValuesChange: (record, recordList) => {
            setDataSource(recordList);
          },
          onChange: setEditableKeys,
        }}
        pagination={pagination}
        onRow={(record) => {
          return {
            onDoubleClick: async () => {
              message.info('双击');
              // 判断是否填写内容
              if (editableKeys.includes(record.id)) {
                message.info('通过验证');
                await form.validateFields();
                actionRef?.current?.cancelEditable(record.id);
                // 验证必填项是否填写完成
              }
              if (!editableKeys.includes(record.id)) {
                message.info('不存在值');
                actionRef?.current?.startEditable(record.id);
              }
            },
          };
        }}
      />

**Comment by yang-chuanjiang** [comment]
请问怎么验证单独行，并与其他行没有关联

**Comment by ubbcou** [comment]
> 请问怎么验证单独行，并与其他行没有关联

有方案吗？
