### ISSUE TITLE
🧐[问题]renderFormItem自定义编辑模式

### ISSUE THREAD

**Issue by WT-Road** [ant-design/pro-components#6277]
### 🧐 问题描述

使用可编辑表格时,需要以下这种这种复杂的组合控件怎么获取值
![image](https://user-images.githubusercontent.com/14371925/203904904-fb5c8057-2c1c-4f7f-969a-4329852b22bc.png)
![image](https://user-images.githubusercontent.com/14371925/203905120-b95b0be5-c12c-4e7a-9ec7-12a6df244427.png)
目前使用renderFormItem会自动包裹 value 和 onChange没问题
当然我知道renderFormItem等于<Form.Item>{dom}</Form.Item>;
一个表单项内有多个控件,就需要使用内嵌的 Form.Item 完成
文档中有个ignoreFormItem属性不知道怎么配合使用

**Comment by WT-Road** [comment]
@chenshuai2144 这个问题可以帮忙看下嘛,实在找不到解决方法,表单的name设置为['id', schema.index, 'name']时,在onValuesChange里可以拿到变化的值,但是value没法注入

**Comment by Gip886** [comment]
这个咋解决的？

**Comment by WT-Road** [comment]
> 这个咋解决的？

没搞定,最后点击下出弹窗修改了,放弃编辑表格了
