### ISSUE TITLE
🧐[问题] 引入 ProDescriptions 组件后，会有一堆警告 

### ISSUE THREAD

**Issue by zhushenhang** [ant-design/pro-components#628]
### 🧐 问题描述
yarn add @ant-design/pro-descriptions 后，引入组件 ，保存后，控制台弹出警告，警告内容如图。

![1601375679(1)](https://user-images.githubusercontent.com/24982716/94548211-f6875380-0282-11eb-984a-98816ea8bdc9.jpg)

请问如何解决警告？谢谢各位

**Comment by chenshuai2144** [comment]
看起来是依赖的问题，全量更新一下
