### ISSUE TITLE
🐛[BUG] Cannot use import statement outside a module

### ISSUE THREAD

**Issue by nonam4** [ant-design/pro-components#6280]
### 🐛 Bug

Cannot use `PageHeader` component in my project because when I try to import it, I'm getting `Cannot use import statement outside a module` error

### 📷 Reproduce

here is a [codesandbox](https://codesandbox.io/p/sandbox/quizzical-worker-fkxf74?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A31%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A31%2C%22startLineNumber%22%3A8%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8skx9az000nlpgeaw1kc72o%2522%252C%2522openFiles%2522%253A%255B%2522%252Fpackage.json%2522%252C%2522%252Fpages%252Findex.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clawvr6u1000n3b6hv0mkau9x%2522%253A%257B%2522key%2522%253A%2522clawvr6u1000n3b6hv0mkau9x%2522%252C%2522name%2522%253A%2522Default%2520Space%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clawvs2o4015u7nge51ix6v5t%2522%252C%2522key%2522%253A%2522clawvs2i5007l3b6h8bz7t8mc%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clawvr6u2000o3b6h7x31xmm2%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clawvr6u1000n3b6hv0mkau9x%2522%257D) example I've made.

run `npm run dev` and you'll see in console the error

### 🏞 Expected

The component should work without errors

### © Version

- "@ant-design/pro-components": "^2.3.35"
- Google Chrome browser
- mac OS

**Comment by thdk** [comment]
See also #4573 although the cause there might be different than what we are experiencing now. 

I have a simple github repo with a bare nextjs application which suffers from the same error:

https://github.com/thdk/antd-pageheader

I see that some packages in ant design pro components have both a lib (commonjs) and a es (es modules) output. However, some modules only have es (pro-layout). Usually the bundler (webpack) should be in charge of picking the correct files to import depending on the type (commonjs of modules) property in package.json. However, it seems some files directly import from the ..../es/... path wich I believe could cause these issues.

**Comment by jameskennethrobinson** [comment]
+1

**Comment by dzcpy** [comment]
Has anyone solved this problem? Why it is closed without solving the actual problem? I'm experincing the same error with Next.js

**Comment by nonam4** [comment]
> Has anyone solved this problem? Why it is closed without solving the actual problem? I'm experincing the same error with Next.js

See #6312

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/commit/c25065e13953020bc88591a2e7d8829387ecd1ab
