### ISSUE TITLE
🧐[问题]ProTable 列设置ellipsis: true build后tooltip不显示，只显示title

### ISSUE THREAD

**Issue by dongtao0725** [ant-design/pro-components#6284]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

🧐[问题]ProTable 列设置ellipsis: true
测试环境tooltip显示正常，
 但build后tooltip不显示，只显示title

### 💻 示例代码
{
      title: '接收人',
      dataIndex: 'phoneNumbers',
      ellipsis: true,
 },

### 🚑 其他信息

测试环境：
![image](https://user-images.githubusercontent.com/30116184/204152857-7df50fec-0026-4294-9fbe-fe6c4e5d7637.png)

build后生产环境：
![1669573512367](https://user-images.githubusercontent.com/30116184/204152921-19c560b0-2546-47ac-86ad-407a63af0eee.png)

**Comment by dongtao0725** [comment]
请问ProTable设置ellipsis: true，都默认使用title了么？看文档应该是自动调用<Tooltip>显示

**Comment by dongtao0725** [comment]
https://codesandbox.io/embed/bi-tian-de-cha-xun-biao-dan-forked-73jq5k?fontsize=14&hidenavigation=1&theme=dark

antd 版本为4.x时无法显示Tooltip

**Comment by chenshuai2144** [comment]
要不升级到antd@5 试试，我没有antd@4 的构建环境

**Comment by dongtao0725** [comment]
antDesign Pro v4升级antd@5很多错误

**Comment by masquerader0** [comment]
> https://codesandbox.io/embed/bi-tian-de-cha-xun-biao-dan-forked-73jq5k?fontsize=14&hidenavigation=1&theme=dark
> 
> antd 版本为4.x时无法显示Tooltip

可以试试全局加个样式
.ant-typography-ellipsis {
  display: inline-block;
  max-width: 100%;
  word-break: break-word;
  overflow: hidden;
  text-overflow: ellipsis;
}

**Comment by dongtao0725** [comment]
ProTable 列单纯ellipsis:true Tooltip显示正常，但如果加上同时ellipsis:true，copyable:true，还是异常

**Comment by dongtao0725** [comment]
全局再把这个样式加回去后恢复，感谢各位
.ant-typography-expand, .ant-typography-edit, .ant-typography-copy {
  color: #1890ff;
  outline: none;
  cursor: pointer;
  transition: color 0.3s;
  margin-left: 4px;
}
