### ISSUE TITLE
🐛[BUG] protable valuetype 为switch无法正常渲染

### ISSUE THREAD

**Issue by susanforme** [ant-design/pro-components#6288]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/51266600/204232571-88995532-b131-41f3-bddc-d7b12a8a3c17.png)
valueType为switch不能正确展示为switch

### 🏞 期望结果
![image](https://user-images.githubusercontent.com/51266600/204233001-584388d9-f31a-439e-a202-08b2cfadc77d.png)

### 💻 复现代码

https://codesandbox.io/s/ke-bian-ji-biao-ge-forked-6fopzs?file=/App.tsx

### © 版本信息

![image](https://user-images.githubusercontent.com/51266600/204232830-83fb870b-57d3-4d0c-8be5-8c6900c41224.png)

- ProComponents 版本: [.2.3.4]
- 浏览器环境 chrome
- 开发环境 [win11]

**Comment by LeiSir16** [comment]
请问这个问题最后怎么解决的？只能用render了么
