### ISSUE TITLE
🐛[BUG] SchemaForm 中 JSX中自定义transform不被调用

### ISSUE THREAD

**Issue by kala888** [ant-design/pro-components#6291]
自定义valueType
```
import useRemoteOption from "@/components/value-type/remote-enum/use-remote-option";
import { ProFormCascader } from "@ant-design/pro-components"; // 这里有bug https://github.com/ant-design/pro-components/issues/6290

export const RemoteCascade = (props) => {
  const { names = [], joinBy = '-', linkToUrl, ...rest } = props
  const { data } = useRemoteOption({ linkToUrl });

  const handleTransform = (values) => {
    console.log("handleTransform", values)
    const result = { [props.name]: values }
    names.forEach((name, idx) => {
      result[name] = values![idx]
    })
    return result;
  }
  return (
    <ProFormCascader
      {...rest}
      fieldProps={{
        displayRender: label => label.join(joinBy),
        options: data,
      }}
      transform={handleTransform}
    />
  )
}

/**
 * fieldProps:{
 *   names:["province","city"],
 *   joinBy:'-',
 *   linkToUrl: 'xxxx' //remote返回candidateValues
 * }
 */
const RemoteCascadeValueType = {
  render: (item, props) => {
    const { fieldProps } = props;
    const { joinBy = "-", names = [] } = fieldProps || []
    const value = names.map(it => item![it]).join(joinBy)
    return <div>{value}</div>
  },
  renderFormItem: (__, props) => {
    const { fieldProps } = props;
    return <RemoteCascade {...props} {...fieldProps} />;
  },
};
export default RemoteCascadeValueType;

```

测试代码：

```
import { BetaSchemaForm, ProForm } from '@ant-design/pro-components';
import { message } from "antd";
import EleProProvider from "@/components/value-type/ele-pro-provider";
import { RemoteCascade } from "@/components/value-type/remote-cascade";


export default () => {

  return (
    <EleProProvider>
      <ProForm onFinish={async (values) => {
        message.success('提交成功' + JSON.stringify(values));
      }}>
        <BetaSchemaForm
          layoutType="Embed"
          columns={[
            {
              title: '所在城市',
              valueType: 'RemoteCascade',
              dataIndex: "addressProvinceCity",
              fieldProps: {
                width: 'md',
                names: ['addressProvince', 'addressCity'],
                linkToUrl: '/api/test/cities',
                placeholder: "请选择所22在城市",
              },
            },
          ]} />

        <RemoteCascade
          linkToUrl={"/api/test/cities"}
          width="md"
          name="data2"
          label="合同生效时间"
          names={['addressProvince2', 'addressCity2']}
          placeholder="请选择所2在城市"
        />

      </ProForm>
    </EleProProvider>
  );
};


```
addressProvinceCity中的定义，并未触发handleTransform

运行结果如下
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/1215976/204433413-775d7dca-c675-4c15-91ce-d04cc274bd26.png">

tips:
package.json
```
 "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^2.3.13",
    "@umijs/route-utils": "^2.1.3",
    "antd": "^4.23.3",
    "classnames": "^2.3.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.6.4",
    "rc-util": "^5.24.4",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.8.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.3.0",
    "ahooks": "^3.7.2",
    "deepdash": "^5.3.9",
    "echarts": "5.3.3",
    "echarts-for-react": "^3.0.2",
    "file-saver": "^2.0.5",
    "jwt-decode": "^3.1.2",
    "numeral": "^2.0.6",
    "path-to-regexp": "^6.2.0",
    "rc-texty": "^0.2.0",
    "react-fast-marquee": "^1.3.5"
  },
```

**Comment by kala888** [comment]
demo：https://github.com/kala888/antd-procomponnet-bug

**Comment by chenshuai2144** [comment]
搞个在线的，

**Comment by kala888** [comment]
> values

https://codesandbox.io/p/github/kala888/antd-procomponnet-bug/master?workspace=%257B%2522activeFileId%2522%253A%2522clf4yb74r0009g1j5b6p09e0r%2522%252C%2522openFiles%2522%253A%255B%2522%252Fsrc%252Findex.js%2522%252C%2522%252Fsrc%252Fcust.js%2522%252C%2522%252Fsrc%252FApp.js%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clb62bmg9000f3b6v3d6vn8mr%2522%253A%257B%2522key%2522%253A%2522clb62bmg9000f3b6v3d6vn8mr%2522%252C%2522name%2522%253A%2522Default%2520Space%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clf4yb9p0000d3b6ybq49mwgk%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clf4ydjwy00an3b6yddggb4xm%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522clf4ydh91007z3b6yvzj10956%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clb62bmg9000f3b6v3d6vn8mr%2522%252C%2522spacesOrder%2522%253A%255B%2522clb62bmg9000f3b6v3d6vn8mr%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

**Comment by kala888** [comment]
找到问题。总结一下：
问题如下：
1. 自定义valueType=“RemoteCascade”的Component，RemoteCascade，其中返回的Component是 ProFormCascader。RemoteCascade 定义transform。
2. 单独以JSX方式是一个RemoteCascade，transform生效
3. 在schema form中使用valueType=“RemoteCascade”，ProFormCascader中定义的transform，不生效。
4. 在3的基础上，如果在JSON中使用transform:()=>xxxx, 失效

在schema form中transform失效原因是：
1. schema form 在创建组件的时候，首先会更具JSON定义创建一个ProFormItem，并建立transform的缓存，key是dataIndex，代码如下：
<img width="735" alt="image" src="https://github.com/ant-design/pro-components/assets/1215976/e3a7d931-8d6a-4fab-aa3d-5237e4ece6fe">
由于没有定义transform，这里缓存为空。

2. 以JSX方式是一个RemoteCascade的时候，也会创建ProFormItem，并建立transform的缓存，key是name。
3.  出问题的自定义ValueType Component，中没有指定name属性(rest 中并没有name，而是id)
```
  <ProFormCascader
      {...rest}
      fieldProps={{
        displayRender: label => label.join(joinBy),
        options: data,
      }}
      transform={handleTransform}
    />
```

解决方案 ：
在ProFormCascader中传递name, 建立name：transform的缓存，

正确代码：

```
mport useRemoteOption from "@/components/value-type/remote-enum/use-remote-option";
import { ProFormCascader } from "@ant-design/pro-components";

export const RemoteCascade = (props) => {
  const { names = [], joinBy = '-', linkToUrl, ...rest } = props
  const { data } = useRemoteOption({ linkToUrl });

  const handleTransform = (values) => {
    console.log("handleTransform", values)
    const result = { [props.name]: values }
    names.forEach((name, idx) => {
      result[name] = values![idx]
    })
    return result;
  }
  return (
    <ProFormCascader
      // 这里很重要
      name={rest.id}
      {...rest}
      fieldProps={{
        displayRender: label => label.join(joinBy),
        options: data,
      }}
      transform={handleTransform}
    />
  )
}

```

同理，convertValue也有这个问题，指定name就行了。
