### ISSUE TITLE
👑 [需求] 希望 SiderMenu 的滚动条样式可以开放接口自定义

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#6292]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

希望 SiderMenu 的滚动条样式可以开放接口自定义

**Comment by chenshuai2144** [comment]
直接用css 覆盖吧，这东西没啥接口
