### ISSUE TITLE
🧐[问题] EditableProTable 表格内联动，编辑中UI修改成功，保存后UI未修改，且数据未保存

### ISSUE THREAD

**Issue by yang-chuanjiang** [ant-design/pro-components#6298]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
🧐[问题] EditableProTable 表格内联动，编辑中UI修改成功，保存后UI未修改，且数据未保存，修改概要，分数自动修改或填充

![image](https://user-images.githubusercontent.com/38531906/204693762-0e0f6691-989e-4bcd-a1ae-9ac1389a322a.png)

![image](https://user-images.githubusercontent.com/38531906/204694033-0e20c75f-28b2-4d0f-9c73-3e1c8ac17cc0.png)

**Comment by yang-chuanjiang** [comment]
https://codesandbox.io/s/zealous-grass-5rhjmo?file=/src/app.tsx
你好，我无法在codesandbox上运行，但是代码我放上去了，双击编辑，选择概要修改分数，但是分数的值不会保存到源数据中。@chenshuai2144

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好，经过我简单的排查发现，这个问题可能是由于你更新了 `dataSource` 的某一项，但是并没有更新 `valueType` 的情况，导致编辑的时候不起作用。这个问题可以通过在 `columns` 中对应的 `valueType` 属性中添加对应状态的 `key` 来解决。例如：

```tsx
<EditableProTable
  ...
  columns={[
    ...
    {
      title: "概要",
      dataIndex: "name",
      valueType: "text", // 这个 valueType 的值必须要和 updateDataSource 中的值一样
      ...
    },
    {
      title: "分数",
      dataIndex: "score",
      valueType: "digit", // 这个 valueType 的值必须要和 updateDataSource 中的值一样
      ...
    },
    ...
  ]}
  ...
  recordCreatorProps={{
    ...
    onFinish: (values) => {
      console.log("Received values of form: ", values);
      const { name, score } = values;
      const newVal = [...dataSource];
      newVal.push({
        key: uuid(),
        name,
        score: parseInt(score),
      });
      console.log(newVal);
      setDataSource(newVal);
    }
  }}
  ...
  editable={{
    ...
    onChange: async (_, record) => {
      try {
        const index = dataSource.findIndex((item) => record.key === item.key);
        if (index > -1) {
          const item = dataSource[index];
          const updated = {
            ...item,
            ...record
          };
          console.log("updated: ", updated);
          const newData = [...dataSource];
          newData.splice(index, 1, updated);
          console.log("newData", newData);
          setDataSource(newData);
        }
      } catch (err) {
        console.error(err);
      }
    },
  }}
  ...
/>
```

如果还有什么问题，请随时和我联系。

**Comment by chenJJ-88** [comment]
我也遇到了一样的问答题，修改上一个select的值后，ui变了但是datasource没有改变，onvaluechange中拿到的数据是没有改变前的数据
