### ISSUE TITLE
🧐[问题]ProFormDependency无法获取到由依赖项动态修改的表单值

### ISSUE THREAD

**Issue by gloriousknight** [ant-design/pro-components#6299]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
[codesandbox地址](https://codesandbox.io/s/proformdependency-heyn21?file=/App.tsx:467-497)
![image](https://user-images.githubusercontent.com/34735844/204704310-7a674836-5b14-4ee5-aa19-ce3ff457d6e4.png)

需求是有两个数字输入框，第二个数字框的值为只读，值等于第一个数字输入框的值*10，我直接在ProFormDependency中增加了一个ProFormDigit，修改fieldProps={{
                value: digit * 10,
              }}
但是在onFinish或formRef.current.getFieldsValue中无法获取到第二个数字框的值，我尝试设置ProFormDigit的initialValue={ digit * 10}，也尝试在 fieldProps里增加
`onChange: (value) => {
                  formRef.current.setFieldValue("dependency", digit * 10);
              }`同样无法获取到值
请问各位大佬正确的写法应该是什么呢？

**Comment by chenshuai2144** [comment]
通过initvalues 注入，你不编辑他是不会在 form中保存的

**Comment by HaileyGermanotta** [comment]
> 通过initvalues 注入，你不编辑他是不会在 form中保存的

通过 initialValue 去设置的话，就不能根据依赖项动态更新了
