### ISSUE TITLE
🐛[BUG] Table 第一列设置fixed=left，下拉选项展示存在问题。

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#6303]
<img width="107" alt="image" src="https://user-images.githubusercontent.com/30397655/204738979-a0990695-af42-4f2e-9019-2fcc6ab84987.png">

**Comment by leshalv** [comment]
https://codesandbox.io/s/kij7iq

https://procomponents.ant.design/~demos/table-batchoption

[官网案例
](https://procomponents.ant.design/components/table#%E8%A1%A8%E6%A0%BC%E6%89%B9%E9%87%8F%E6%93%8D%E4%BD%9C)

**Comment by chenshuai2144** [comment]
没有发现问题。详细描述下？

**Comment by leshalv** [comment]
<img width="300" alt="image" src="https://user-images.githubusercontent.com/30397655/204745352-ad80d7d8-f8ff-4a6b-b45b-40da3548c26c.png">

**Comment by chenshuai2144** [comment]
没看见这个功能。我提给antd 团队看看

**Comment by zombieJ** [comment]
@leshalv 方便搞个 antd 重现给 antd 发 issue？
