### ISSUE TITLE
🐛[BUG] Layout token is not loaded while on mobile screen.

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/pro-components#6306]
### 🐛 bug 描述

Layout token is not loaded while on mobile screen.

### 🏞 期望结果 | Expected results

The token defined in the layout must also be valid on the mobile screen.

### 💻 复现代码 | Recurrence code

![token](https://user-images.githubusercontent.com/6988989/203997737-c2676c53-0325-4555-89cf-de9a841db46f.PNG)

### Mobile Screen
![notwork](https://user-images.githubusercontent.com/6988989/203997743-ecb394ce-794c-44dc-8c3b-254ca3d9605f.PNG)

### © 版本信息

- Ant Design Pro 版本: 4.23.3
- umi 版本: 4.0.24
- 浏览器环境: Chrome
- 开发环境: Windows

**Comment by chenshuai2144** [comment]
I am very sorry to cause you trouble, but this is our intention because there will be different elements in the drawer and in the page, and we cannot guarantee that a token can meet these two conditions

**Comment by xXAvoraXx** [comment]
> I am very sorry to cause you trouble, but this is our intention because there will be different elements in the drawer and in the page, and we cannot guarantee that a token can meet these two conditions

I did not fully understand. Is it not displayed because the tokens of the mobile and normal screen will be different?
我没有完全理解。 不显示是不是因为移动端和普通屏的token会不一样？

**Comment by xXAvoraXx** [comment]
other problem is maskclosable
https://github.com/ant-design/pro-components/issues/6305

**Comment by chenshuai2144** [comment]
暂时不会支持，我们还没有找到很好的办法
