### ISSUE TITLE
🐛[BUG] 通过 token 修改 layout 的背景颜色失败

### ISSUE THREAD

**Issue by sushi-su** [ant-design/pro-components#6307]
### 🐛 bug 描述

代码：
![image](https://user-images.githubusercontent.com/50985188/204782344-bb7ab100-e9ae-4105-ae44-80b9e2dd4e48.png)

2.3.35 的实现：
![image](https://user-images.githubusercontent.com/50985188/204782517-ebcde598-8737-488e-9c4e-d81b4f883a13.png)

2.3.36 的实现：
![image](https://user-images.githubusercontent.com/50985188/204782591-8fa0666d-2f53-4de5-b529-316f5eca6702.png)

**Comment by mwj610** [comment]
antd 5的  compactAlgorithm  darkAlgorithm  也失效了
