### ISSUE TITLE
🐛[BUG] Table 进入scroll 状态后，底部边框重复展示。

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#6310]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/30397655/204793172-ad7ef8a2-ec03-4641-86bf-7642ecb4fb8e.png">

**Comment by chenshuai2144** [comment]
这个看起来是浏览器的滚动条的 border 和 table 的border 重叠了，可以试试自定义滚动条
