### ISSUE TITLE
🐛[BUG] Unexpected token 'export'

### ISSUE THREAD

**Issue by nonam4** [ant-design/pro-components#6312]
### 🐛 Bug
Cannot use `PageHeader` component in my project because when I try to import it, I'm getting `Unexpected token 'export' at '.../node_modules/ant-design/pro-components/es/index.js:1'` error

### 📷 Reproduce
here is a [codesandbox](https://codesandbox.io/p/sandbox/quizzical-worker-fkxf74?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A57%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A57%2C%22startLineNumber%22%3A5%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8skx9ay000hlpge4cua49bz%2522%252C%2522openFiles%2522%253A%255B%2522%252Fpackage.json%2522%252C%2522%252Fpages%252Findex.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clawvr6u1000n3b6hv0mkau9x%2522%253A%257B%2522key%2522%253A%2522clawvr6u1000n3b6hv0mkau9x%2522%252C%2522name%2522%253A%2522Default%2520Space%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clawvr6u2000o3b6h7x31xmm2%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clawvr6u1000n3b6hv0mkau9x%2522%257D) example I've made.

run npm run dev and you'll see in console the error

### 🏞 Expected
The component should be imported without errors

### © Version
"@ant-design/pro-components": "^2.3.35"
Google Chrome browser
mac OS

#6280

**Comment by nonam4** [comment]
#6311

**Comment by dl0312** [comment]
I am experiencing the same issue and because of this problem, it is difficult to move from v4 to v5.

If I import like this,

```tsx
import { PageHeader } form '@ant-design/pro-layout'
```

I got `Cannot use import statement outside a module` error message

If I import like this,

```tsx
import { PageHeader } form '@ant-design/pro-components'
```

I got `Unexpected token 'export' at ...` error message

@chenshuai2144 
The v4 to v5 guide says like this,

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/3915393/204970165-9c2efde8-7f3d-4112-9d28-8235ab96dbb1.png">

but you says
> you need use `import { PageHeader } form '@ant-design/pro-components'`

which one is right??

**Comment by rubenkaiser** [comment]
Having the same issue. I can get past the `Unexpected token 'export'` by changing the import to the dist/components folder:

```
import { PageHeader } from '@ant-design/pro-components/dist/components';
```

This however gives me another error: `Module not found: Can't resolve 'ReactDOM'`. Waiting for a proper fix, following this thread.

**Comment by chenshuai2144** [comment]
I'm very sorry, I didn't see that you are using next.js, we only provide the es version of js, do you need to configure a special conversion tool in next.js?

**Comment by chenshuai2144** [comment]
I found this, can it help you?

https://stackoverflow.com/questions/65936222/next-js-syntaxerror-unexpected-token-export

**Comment by dl0312** [comment]
@chenshuai2144 
The problem has not been solved at all. I don't understand why the usability of the basic ant library and the pro-component library should be different.

**Comment by rubenkaiser** [comment]
The suggestion from @chenshuai2144 is correct. However it is quite some puzzling to get it done. You actually need to trace which things have to be transpiled. In this case only @ant-design/pro-components is far from enough. I got it working with the following in my next.config:

```
const withTM = require('next-transpile-modules')([
  'antd',
  '@ant-design/pro-components',
  '@ant-design/pro-layout',
  '@ant-design/pro-utils',
  '@ant-design/pro-provider',
  'rc-pagination',
  'rc-picker'
]);

module.exports = (nextConfig = {}) => {
  return withTM();
};

```

But I guess other projects need more modules to be transpiled as they use other components from antd and/or ant-design/pro. When running you actually can get a good idea of what to include in the transpile step next.

This was my last error that indicated I should add 'rc-picker' as well:

```
event - compiled client and server successfully in 324 ms (4379 modules)
/xxxxxxxxxxxxxxxxxx/node_modules/**rc-picker**/es/locale/zh_CN.js:29
export default locale;
^^^^^^

SyntaxError: Unexpected token 'export'
```

**Comment by thibaultmthh** [comment]
Waiting for a fix too. my issue is with JEST.

I found a bypass using  PageHeader from antd 4 while the rest of my app is on antd 5

Install via : 
`
yarn add antd-4@npm:antd@4.24.5
`
And i made a css file with the page-header rules ( from ant4 css file ) 

Then I can use : 
`
import './pageHeaderCssPatch.css';
import { PageHeader } from 'antd-4';
`

**Comment by abstractalgo** [comment]
I had a NextJS project throwing this error. As a workaround, instead of using:
```ts
import { CodeFilled } from '@ant-design/icons';
```
This worked:
```ts
import CodeFilled from '@ant-design/icons/CodeFilled';
```
