### ISSUE TITLE
🐛[BUG] Layout 折叠状态下样式出现问题。

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#6313]
<img width="81" alt="image" src="https://user-images.githubusercontent.com/30397655/204819622-f2c53d99-2d00-45d6-a996-ac2ac0eaf1e6.png">

**Comment by DAOLIDEWONIU** [comment]
+1，生产环境还是少用这玩意儿，bug 不少

**Comment by XuJin186** [comment]
2.3.36版本特有的bug

**Comment by leshalv** [comment]
> +1，生产环境还是少用这玩意儿，bug 不少

个人来说 pro-components 给我解决了不少问题，我是后端，用 pro-components 让我能胜任一些前端开发工作，bug多主要是目前处于更新迭代，慢慢的就好了。

**Comment by chenshuai2144** [comment]
修复了，重新更新
