### ISSUE TITLE
🐛[BUG] migrate react-sortable-hoc to @dnd-kit

### ISSUE THREAD

**Issue by folt** [ant-design/pro-components#6315]
### What problem does this feature solve?

I got an error when running `npm i @ant-design/pro-components --save` installation command.

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-sortable-hoc@2.0.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN peer react@">=16.0.0" from @ant-design/cssinjs@1.1.0
npm WARN node_modules/@ant-design/cssinjs
npm WARN @ant-design/cssinjs@"^1.0.0" from antd@5.0.3
npm WARN node_modules/antd
npm WARN 66 more (@ant-design/icons, @ant-design/pro-card, ...)
```

After investigating the problem, it turned out that the react-sortable-hoc package is no longer supported. There is a message about this in the README of the project.
https://github.com/clauderic/react-sortable-hoc#readme

### What does the proposed API look like?

The earner recommends replacing this package with https://github.com/clauderic/dnd-kit

**Comment by thoughtpalette** [comment]
This seems to _still_ be an issue. Any updates on a PR @folt?

**Comment by folt** [comment]
> This seems to _still_ be an issue. Any updates on a PR @folt?

I tried to change dependencies, but dnd-kit has a slightly different interface.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


I see. Can you provide more details about the issue you're facing? Maybe someone in the community can help you find a way to migrate to dnd-kit.

**Comment by arifszn** [comment]
After adding `@ant-design/pro-layout` or `@ant-design/pro-components`, the warnings are shown any time we run `npm install`.

![image](https://user-images.githubusercontent.com/45073703/223153747-99b2acb6-34c4-4323-9189-55715e1a730d.png)

The concerned package is abandoned and the react version has not been updated. https://github.com/clauderic/react-sortable-hoc/blob/caf3c4f5bfb30894639391ae75c1bfc2b707a127/package.json#L57

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


You can try using a package called `react-dnd` instead of `dnd-kit`. It has similar functionality to the abandoned `react-sortable-hoc` package.

To migrate from `react-sortable-hoc` to `react-dnd`, you can follow these steps:

1. Install the react-dnd packages:

   ```
   npm install --save react-dnd react-dnd-html5-backend
   ```

2. Replace the import of the `SortableContainer` HOC from react-sortable-hoc with `DndProvider` HOC from react-dnd:

   ```js
   // Before:
   import { SortableContainer } from "react-sortable-hoc";

   const MySortableList = SortableContainer(props => <ul {...props}>{/* ...items */}</ul>);

   // After:
   import { DndProvider } from "react-dnd";
   import { HTML5Backend } from "react-dnd-html5-backend";

   const MySortableList = props => (
     <DndProvider backend={HTML5Backend}>
       <ul {...props}>{/* ...items */}</ul>
     </DndProvider>
   );
   ```

3. Replace the `SortableElement` HOC with `DragSource` from react-dnd:

   ```js
   // Before:
   import { SortableElement } from "react-sortable-hoc";

   const MySortableItem = SortableElement(({ value }) => <li>{value}</li>);

   // After:
   import { DragSource } from "react-dnd";

   const ItemTypes = { CARD: "card" };

   const cardSource = {
     beginDrag(props) {
       return {
         id: props.id,
         index: props.index
       };
     }
   };

   function collect(connect, monitor) {
     return {
       connectDragSource: connect.dragSource(),
       isDragging: monitor.isDragging()
     };
   }

   const MySortableItem = ({ connectDragSource, isDragging, value }) => {
     const opacity = isDragging ? 0.4 : 1;
     return connectDragSource(
       <li style={{ opacity }} className="card-item">
         {value}
       </li>
     );
   };

   MySortableItem = DragSource(ItemTypes.CARD, cardSource, collect)(MySortableItem);
   ```

Here are some relevant links for the migration steps:

- [React DND documentation](https://react-dnd.github.io/react-dnd/about)
- [React DND example](https://react-dnd.github.io/react-dnd/examples/sortable/simple)
- [Blog post with a react-sortable-hoc to react-dnd migration example](https://blog.jakoblind.no/react-dnd-tutorial)
