### ISSUE TITLE
🧐[问题]如何让protable的某一个搜索项回车不触发搜索事件，并且回车可以正常使用

### ISSUE THREAD

**Issue by wsm14** [ant-design/pro-components#6317]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
filedProps 里面取消一下函数冒泡

`filedProps={ onClick:(e)=>{停止冒泡} }`

**Comment by zhadongmin** [comment]
`
      fieldProps: {
        onKeyPress: (e: any) => {
          if (e.code === 'Enter') {
            console.log('停止冒泡', e)
            e.stopPropagation()
          }
        }
      }
`
