### ISSUE TITLE
@ant-design/pro-components 依赖的ant版本什么时候会升级成antv5？

### ISSUE THREAD

**Issue by GitVitality** [ant-design/pro-components#6322]
### What problem does this feature solve?

项目中ant组件升级成antv5后，@ant-design/pro-components样式失效

### What does the proposed API look like?

期望@ant-design/pro-components 依赖的ant版本升级成antv5

**Comment by zombieJ** [comment]
```json
"peerDependencies": {
  "antd": ">=4.23.0",
  "react": ">=16.9.0",
  "react-dom": ">=16.9.0"
},
```

`>= 4.x` 包含 v5 的，你的项目用了 v5 就会是 v5。如果不是的话 npm ls antd 看看是否是有提升的情况哈。

**Comment by Vsion** [comment]
![image](https://user-images.githubusercontent.com/11804448/212843582-c1838720-3881-452f-8629-9833c665be87.png)
