### ISSUE TITLE
安装依赖时，发现库的地址存在问题 /User => /user🧐[问题]

### ISSUE THREAD

**Issue by evanyangg** [ant-design/pro-components#6326]
### 🧐 问题描述
安装后发现，库的本地地址出现路径上的大小写问题，导致异常，
不确认问题出在什么地方，请大佬指教

@ant-design/pro-components": "^2.3.39
"@umijs/max": "4.0.34",

### 🚑 其他信息
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/22952321/205256482-3e5ae701-7550-4ea2-86e5-b6af6b0c4f64.png">

**Comment by chenshuai2144** [comment]
这个和库没有关系吧，是 umi 做的还是这个插件做的？
