### ISSUE TITLE
pro-table新升级bug🐛[BUG]

### ISSUE THREAD

**Issue by quarkcms** [ant-design/pro-components#633]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/60868863/94632411-fdeb4300-02fc-11eb-9a73-2cee09f46bed.png)

**Comment by chenshuai2144** [comment]
这个dom出现的位置很奇怪，来个复现

**Comment by quarkcms** [comment]
昨天更新的新版本
` 
 <ProTable
      // key={props.table.key}
      // actionRef={actionRef}
      rowKey={props.table.rowKey}
      headerTitle={props.table.headerTitle}
      columns={parseColumns(props.table.columns)}
      // options={props.table.options}
      request={async (params, sorter, filter) => {
        let query = {};
        query['api'] = history.location.query.api;
        query['page'] = params.current;
        query['pageSize'] = params.pageSize;

        delete params['current'];
        delete params['pageSize'];

        query['search'] = params;
        query['sorter'] = sorter;
        query['filter'] = filter;

        history.push(history.location.pathname+'?'+stringify(query));

        const datasource = await getTableDatasource(props.table.key);

        return Promise.resolve({
          data: datasource,
          success: true,
        });
      }}
      // pagination={props.table.pagination}
      // dateFormatter={props.table.dateFormatter}
      // columnEmptyText={props.table.columnEmptyText}
      toolbar={{
        multipleLine: true,
        actions: [<Button type="primary">新建应用</Button>],
      }}
    />
`

**Comment by chenshuai2144** [comment]
试了一下没法复现，你的那个文案是怎么出来的

**Comment by yunuo-tech** [comment]
同样的问题

**Comment by chenshuai2144** [comment]
更新一下所有的依赖？

**Comment by niufen0420** [comment]
同样的问题
![image](https://user-images.githubusercontent.com/15320052/96419920-5ee4a780-1227-11eb-86c3-9961e45728b4.png)

**Comment by niufen0420** [comment]
> ### 🐛 bug 描述
> ![image](https://user-images.githubusercontent.com/60868863/94632411-fdeb4300-02fc-11eb-9a73-2cee09f46bed.png)

你找到原因了吗

**Comment by niufen0420** [comment]
> 同样的问题
> ![image](https://user-images.githubusercontent.com/5960864/95684206-8ed9ec80-0c22-11eb-857a-70ea7af769ba.png)

你找到原因了吗

**Comment by ccloveak** [comment]
# the same issue 一样的问题
![image](https://user-images.githubusercontent.com/38686314/99221293-a9a41000-2823-11eb-82cb-a12f1011d871.png)
## 具体：
* 之前页面展示 
![image](https://user-images.githubusercontent.com/38686314/99221716-73b35b80-2824-11eb-9096-6eaa8c46b5b4.png)
* 之前protable版本‘2.6.3’
* 用了 toolBarRender
* 现在需要对 列设置 列展示 重置  做国际化 把 toolBarRender删了 照着示例 用toolbar渲染
* 现在protable版本‘2.10.1’
* 现在的代码结构 
```
<ProTable 
       ,,,,
       search={{
          ,,,,some code,,,,
       }}
      toolbar={{
         title: 'アカウント一覧',
         search:null,
      }}
/>
```
## 期望： 
* 现在版本暂时有问题的话，之前哪个版本可以实现  列设置 列展示 重置 的国际化

**Comment by zhoulingfengofcd** [comment]
一样的问题：
![image](https://user-images.githubusercontent.com/25604004/99935272-4d00a200-2d9b-11eb-8cdb-df6d4d96c163.png)
问题原因：
![image](https://user-images.githubusercontent.com/25604004/99935144-f7c49080-2d9a-11eb-90fa-01ba6c49ec57.png)
处理方式：
![image](https://user-images.githubusercontent.com/25604004/99935343-77eaf600-2d9b-11eb-8500-3124aa10d11e.png)
