### ISSUE TITLE
🐛[BUG]在ProForm中使用EditableProTable时，重新渲染后通过formRef得到其属性值异常，会将原值变为Json（字典）对象

### ISSUE THREAD

**Issue by jayt1001** [ant-design/pro-components#6331]
### 🐛 bug 描述

我设定了在切换radio到文本后，将form中data字段的值改为json字符串。这时再切换表格时，通过formRef获取的data就变为了一个Json对象，而不是期望的json字符串（控制台有打印）：

![image](https://user-images.githubusercontent.com/29675005/205502742-eca810b3-6d29-4fd3-a8d4-935cccc895cd.png)

---
![image](https://user-images.githubusercontent.com/29675005/205502545-cb880989-163c-4b42-8014-6b78a20ac80b.png)

---
### 📷 复现步骤
打开下面box，然后切换Radio到【文本】再切换【表格】，再查看控制台打印即可复现：
[https://codesandbox.io/s/gu-ding-biao-tou-forked-x3m2gt?file=/App.tsx](https://codesandbox.io/s/gu-ding-biao-tou-forked-x3m2gt?file=/App.tsx)

### 🏞 期望结果

返回字符串数组

### 💻 复现代码

[https://codesandbox.io/s/gu-ding-biao-tou-forked-x3m2gt?file=/App.tsx](https://codesandbox.io/s/gu-ding-biao-tou-forked-x3m2gt?file=/App.tsx)

### © 版本信息

- ProComponents 版本: 2.3.37
- umi 版本:3.5.35
- 浏览器环境:chrome
- 开发环境 :win10

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好，根据你的描述和提供的代码，这个问题是由于你在 ProForm 中使用 EditableProTable 时，重新渲染后通过 formRef 获取属性值时，将存储为字符串的 data 字段变成了对象的问题。请尝试将以下代码注释掉：

```jsx
// onChange={(value) =>{
//   console.log(value);
//   form.setFieldsValue({
//     'data': JSON.stringify(value),
//   });
// }}
```

然后切换到“表格”选项卡，你会发现通过 formRef 获取到的 data 字段值是一个字符串数组，而不是对象。这是因为你的 onChange 事件中手动调用了 form.setFieldsValue，改变了表单的值。而 ProForm 中的 Editable 表格组件也会改变表单的值，导致出现冲突。

如果你需要将 Editable 表格中的值传递到后端，你可以使用表单提交，例如：

```jsx
const onFinish = (values) => {
  console.log('Received values: ', values);
};

const queryData = [
  {
    key: '0',
    name: '',
    age: '',
    address: '',
  },
];

return (
  <ProForm onFinish={onFinish}>
    <Radio.Group value={type} onChange={(e) => setType(e.target.value)}>
      <Radio value="text">文本</Radio>
      <Radio value="table">表格</Radio>
    </Radio.Group>

    {type === 'table' && (
      <EditableProTable
        rowKey="key"
        maxLength={5}
        columns={columns}
        value={data}
        onChange={setData}
        editable={{
          type: 'multiple',
          editableKeys,
          onChange: setEditableRowKeys,
          onDelete: handleDelete,
        }}
      />
    )}

    <ProFormList name="data">
      <ProFormGroup>
        <ProFormText name="name" />
        <ProFormText name="age" />
        <ProFormText name="address" />
      </ProFormGroup>
    </ProFormList>

    <ProFormSubmitButton>提交</ProFormSubmitButton>
  </ProForm>
);
```

具体实现可以参考[官方文档](https://procomponents.ant.design/components/table-row-editable-cn/)和[示例代码](https://codesandbox.io/s/row-editable-form-pro-components-demo-forked-ciftv?file=/src/pages/TableList.tsx)。

希望能帮助你解决问题，有问题可以继续提出。

**Comment by chenshuai2144** [comment]
修复好了，判断写错了导致的
