### ISSUE TITLE
🧐[问题] 几乎都是复制的demo的代码，但是我Pro-Layout中的Content的宽度没有100%，求问是哪里的问题？

### ISSUE THREAD

**Issue by textnumber085** [ant-design/pro-components#6337]
### 🧐 问题描述

我在写一个测试代码，很简单目前几乎内有自己额外写css。主要测试各个组件，我发现我这用的pro-layout，content的宽度并没有占满100%的宽度

### 💻 示例代码

```
ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
            <BrowserRouter>
                <Route />
            </BrowserRouter>
    );
```

```
<Routes>
        <Route path="/" element={<Layout />}>
            // ...
        </Route>
        <Route path="*" element={<p>Not Found</p>} />
</Routes>
```

截图里的这个 "About" 页面，也是直接把 `ProCard` 的代码直接复制过来的, 没有额外加css。

按理说，layout的content应该是占满整个宽度的才对，为啥我这里只占了这一小坨？

我试了下直接在index.html加一个100%的宽度可以解决这个问题，但是这不是最好的方案吧
```
<body>
        <div id="root" style="height: 100%; width: 100%;"></div>
</body>
```

### 🚑 其他信息
![屏幕截图 2022-12-05 175718](https://user-images.githubusercontent.com/7994054/205608506-2cc0d692-9b4b-4ff3-b812-dade07622ed4.jpg)

**Comment by sushi-su** [comment]
[应该是 pageContainer 的 padding](https://procomponents.ant.design/components/layout#pagecontainer-token)

**Comment by chenshuai2144** [comment]
看起来是antd的样式没有成功加载，如果没有用umi推荐你 手动 import，
如果用了umi，试试清空依赖重新启动
