### ISSUE TITLE
🐛[BUG] ProTable 搜索栏 input 和 button 错位

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#6339]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

![微信截图_20221205195431](https://user-images.githubusercontent.com/3166799/205631588-7ad539aa-38ee-4646-bd9a-98c0b5763bb2.png)

### © 版本信息

- ProComponents 版本:  2.3.40
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
升级一下antd 的版本试试

**Comment by hihuangwei** [comment]
https://github.com/ant-design/ant-design/issues/40440 @chenshuai2144
