### ISSUE TITLE
如何自定义search🧐[问题]

### ISSUE THREAD

**Issue by quarkcms** [ant-design/pro-components#634]
### 🧐 问题描述
如何自定义search？有些时候search里面的表单并不是table里展示的字段，这时候需要自定义表单控件
![image](https://user-images.githubusercontent.com/60868863/94632910-62f36880-02fe-11eb-8b53-d073fd2a5b7d.png)

**Comment by quarkcms** [comment]
@chenshuai2144 帅哥，帮忙指点一下

**Comment by chenshuai2144** [comment]
hideInTable 和 hideInSearch 配合一把。或者用 renderFormItem 完全自定义

**Comment by quarkcms** [comment]
@chenshuai2144 @afc163 感觉可以增加一个formItemRender，交给用户自由选择，因为一个筛选条件并不一定是某个字段，可能是多个字段条件的组合，尤其像涉及到商品订单这类业务的时候

**Comment by quarkcms** [comment]
而且把搜索表单与表格绑定有点儿别扭，与现实的业务也有点儿出入，不能说这样做不对，但是这样做就不够自由化了

**Comment by quarkcms** [comment]
我的建议是这里可以分开，搜索表单就完全交给用户定义，这样还能减少table组件的复杂度

**Comment by chenshuai2144** [comment]
@quarkcms 大部分没那么复杂的。

**Comment by quarkcms** [comment]
嗯，还是建议加上一个formItemRender；我现在自己加了一个search表单，没有用官方的

**Comment by quarkcms** [comment]
还有就是search的版式，还不如下图那样好看
![image](https://user-images.githubusercontent.com/60868863/94648195-98ab4800-0324-11eb-92a5-c7795bbfd9c2.png)
