### ISSUE TITLE
🐛[BUG] StatisticCard Styles

### ISSUE THREAD

**Issue by tailoc-hcmus** [ant-design/pro-components#6340]
### 🐛 bug 描述

Error Style fontSize StatisticCard:
![image](https://user-images.githubusercontent.com/57663409/205793546-88e5dcce-3d4d-4f89-a0f4-0bb442c04ceb.png)
![image](https://user-images.githubusercontent.com/57663409/205793855-2dc5a0dc-0acf-49a1-98b5-5d86e1e9af31.png)

RAW: 
![image](https://user-images.githubusercontent.com/57663409/205794340-47646175-6cf0-4011-9c79-f42cafc48fc1.png)

- ProComponents 版本: 2.3.40
+ antd : 5.0.4

**Comment by chenshuai2144** [comment]
Please upgrade to the latest version because of hasid

**Comment by jayceyang** [comment]
> Please upgrade to the latest version because of hasid

这个问题依然存在。都是最新版了。
```
"@ant-design/pro-components": "^2.3.54",
"antd": "^5.2.1",
```

使用StatisticCard和Statistic都一样，改不了value的字体。
