### ISSUE TITLE
@chenshuai2144  这是啥奇葩设计？      algorithm: dark ?? proProvide.dark ? darkAlgorithm : defaultAlgorithm,

### ISSUE THREAD

**Issue by fitterfizzle** [ant-design/pro-components#6342]
@chenshuai2144  这是啥奇葩设计？      algorithm: dark ?? proProvide.dark ? darkAlgorithm : defaultAlgorithm,
https://github.com/ant-design/pro-components/blob/0044bcdba504f4c7c610a9d3720995a4d4d40460/packages/provider/src/index.tsx#L465

除了dark我不能设置别的了嘛？compact和dark一起用不行嘛

_Originally posted by @XuJin186 in https://github.com/ant-design/pro-components/issues/6263#issuecomment-1331965530_
      
How can you combine compact algorith with dark or light algorithm when using both <ConfigProvider/> of ant design and Pro Components?

**Comment by chenshuai2144** [comment]
修复了
