### ISSUE TITLE
🐛[BUG] ProTable 使用 SettingDrawer 设置为黑色主题无效

### ISSUE THREAD

**Issue by zerox-v** [ant-design/pro-components#6343]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

使用 SettingDrawer 设置为黑色主题的时候 ProTable 背景颜色还是白色，使用ConfigProvider 给 ProTable 设置 colorBgContainer ，背景颜色也没效果。

@ant-design/pro-components 版本 2.3.40
antd  版本 5.0.4

### 📷 复现步骤

[点击查看效果](https://codesandbox.io/s/cha-xun-biao-ge-forked-w7k4tx?file=/App.tsx:4992-5010)

### 🏞 期望结果

希望能适配 黑色主题

### 💻 复现代码

```javascript
<ConfigProvider
      theme={{
        token: {
          //这里修改背景不作用
          colorBgContainer: "#ff0000"
        }
      }}
    >
  //这里是 ProTable
 </ConfigProvider>
```

### © 版本信息

- ProComponents 版本: [2.3.40]
- umi 版本 4.0.32
- 浏览器环境 Chrome  107.0.5304.123
- 开发环境 [windows]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/24620885/205936927-077b2a59-be30-4e49-a342-98dc4630df30.png)

**Comment by tilkofjin** [comment]
+1

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/~demos/packages-layout-src-components-layout-demo-base?layout=mix&splitMenus=true&navTheme=realDark

看看这里的用法

**Comment by chatter-ai** [comment]
navTheme 想要 dark 但只能选 realDark
