### ISSUE TITLE
🐛[BUG] QueryFilter 中使用 ProFormDependency，如果返回 null，会占一个空位

### ISSUE THREAD

**Issue by HaileyGermanotta** [ant-design/pro-components#6347]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

QueryFilter 中使用 ProFormDependency，如果返回 null，会占一个空位 

### 📷 复现步骤

请查看链接：https://codesandbox.io/s/cha-xun-shai-xuan-y0dtbw?file=/App.tsx
![image](https://user-images.githubusercontent.com/51814693/206126710-c6f4f178-313f-4161-9d80-d10f9d2e6c03.png)

![image](https://user-images.githubusercontent.com/51814693/206126568-771cdf6a-19ab-4137-89ea-48fb33dff148.png)

### 🏞 期望结果

返回有内容时候占位，返回 null 时候不占位。

### 💻 复现代码

请查看链接：https://codesandbox.io/s/cha-xun-shai-xuan-y0dtbw?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] 2.3.36
- umi 版本
- 浏览器环境 Chrome
- 开发环境 [e.g. mac OS] Mac OS

**Comment by adw2022** [comment]
same error +1

**Comment by wangmeijian** [comment]
someone is fix
