### ISSUE TITLE
🧐[问题]Protable加载数据后, postData初始获取的total数量不正确

### ISSUE THREAD

**Issue by jtc23** [ant-design/pro-components#6348]
### 🧐 问题描述
依赖
"dependencies": {
    "@ant-design/pro-components": "^1.1.15",
    "@ant-design/pro-table": "^2.80.4",
       "@umijs/max": "^4.0.13",
       "antd": "^4.22.4",
},
]Protable加载数据后, postData初始获取的total数量不正确
### 💻 示例代码

![详情](https://user-images.githubusercontent.com/30261508/206130586-dc28dc82-7997-44b6-aa2e-95334c3b6bde.jpg)
![1670403691406(1)](https://user-images.githubusercontent.com/30261508/206134900-e00e445d-0b0b-4df8-87f9-555dab4f96d6.jpg)

![1670402511619(1)](https://user-images.githubusercontent.com/30261508/206130704-8f1c4b0e-4e24-4209-9dae-4cd52d0e41f4.jpg)

我在自己写的Protable HOC中希望通过actionRef获取total总数,但是我发现如果直接直接获取第一次是无法获取正确的值,但是如果设置了延迟是没有问题的,请问这个原因是啥

**Comment by chenshuai2144** [comment]
因为 hooks 都是异步的，你最好不要用这个 hack 的方式看做操作。

你应该直接在request中去记录日哥 ref 然后再去更新
