### ISSUE TITLE
如何自定义search表单中其中一个列的span🧐[问题]

### ISSUE THREAD

**Issue by hyyqcweb** [ant-design/pro-components#635]
### 🧐 问题描述

如何自定义search表单中其中一个列的span

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/17583072/94636397-7eaf3c80-0307-11eb-9219-6125eca84a8b.png)

**Comment by hyyqcweb** [comment]
统一的span, 不太适合业务场景, 能不能单独为某个条件设置span???

**Comment by chenshuai2144** [comment]
现在是不支持的，我们希望他是整整齐齐的

**Comment by hyyqcweb** [comment]
@chenshuai2144 那有什么办法能使让这列变长吗? 调样式?

**Comment by quarkcms** [comment]
所以说这里search表单还不如交给用户自由定义

**Comment by hyyqcweb** [comment]
那我只能重写样式了, 不然这东西不能用啊

**Comment by chenshuai2144** [comment]
如果有需要大改的样式需求，建议关掉自带的，自己实现一下
