### ISSUE TITLE
🐛[BUG] EditableProTable 的 Select 组件在设置了 showSearch 和 mode: 'tags' 模式下，输入关键词并回车后，关键词被误认为枚举选中

### ISSUE THREAD

**Issue by RyanKwok888** [ant-design/pro-components#6351]
### 🐛 bug 描述
EditableProTable 的 Select 组件在设置了 showSearch 和 mode: 'tags' 模式下，输入关键词并回车后，关键词被误认为枚举选中

### 📷 复现步骤

- 在Select组件中，输入关键词
- 回车

### 💻 复现代码
```js
    {
      title: '状态',
      key: 'state',
      dataIndex: 'state',
      valueType: 'select',
      valueEnum: {
        all: { text: '全部', status: 'Default' },
        open: {
          text: '未解决',
          status: 'Error',
        },
        closed: {
          text: '已解决',
          status: 'Success',
        },
      },
      fieldProps: { showSearch: true, mode: 'tags' },
    },
```

### © 版本信息

- ProComponents 版本: [2.3.40]
- umi 版本: 3.50
- 浏览器环境: Chrome
- 开发环境 [mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23159401/206373342-183bfd8b-4030-4b9b-8482-4af40e0efd6e.png)

**Comment by chenshuai2144** [comment]
tags 模式就是这么设计的，如果不需要我推荐你用 多选模式。
