### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by titld** [ant-design/pro-components#6352]
在proform里面引入了自定义组件<Form.Item>， 但是在onValueChange方法里面拿不到这个参数，应该怎么解决呢？pro-form原版本1.21.5可以的，现在换成了2.2.7版本就拿不到了, 我期望onValueChange方法能够拿到所有的字段（包括自定义组件的switch字段）

### © 版本信息

- ProComponents 版本: 2.3.19
- ProForm 版本：2.2.7
- umi 版本 4.0.34
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
```js
<ProForm
 onValuesChange={(changeValues) => console.log(changeValues)}
>
  <ProFormText name="name" label="name" />
 <Form.Item name="switch" label="Switch" valuePropName="checked">
    <Switch />
  </Form.Item>
</ProForm>
```js

**Comment by chenshuai2144** [comment]
注意一下 antd的版本相同，如果不同就会拿不到
