### ISSUE TITLE
👑 [需求] QueryFilter 添加类似 LightFilter 的 collapseLabel 属性

### ISSUE THREAD

**Issue by guaijie** [ant-design/pro-components#6355]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件
QueryFilter

### 🥰 需求描述
QueryFilter 添加类似 LightFilter 的 collapseLabel 属性

QueryFilter 默认collapseText 是 展开/收起， 想通过新的属性 collapseLabel 能自定义展开/收起按钮

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/30885718/206417444-e0609515-e2c2-416f-ab6c-bd2b8df96323.png)

**Comment by chenshuai2144** [comment]
用 submitter 可以想怎么改就怎么改,        collapseRender 只能修改展开收起按钮

```tsx
<QueryFilter<{
        name: string;
        company: string;
      }>
        submitter={{
          render: () => {},
        }}
     />
```
