### ISSUE TITLE
👑 [需求]ProTable的查询条件能否实时同步查询表单值，目前仅在查询表单提交时候更新

### ISSUE THREAD

**Issue by myloveGy** [ant-design/pro-components#6356]
### 🔩 所属模块或组件

率属组件：ProTable

### 🥰 需求描述

目前发现在使用ProTable的时候，查询表单修改后，如果不点击提交，查询条件不会更新，从而导致查询结果和查询表单显示不一致；是否能在查询表单修改后，实时同步到查询条件中

### 🧐 解决方案

代码 [https://github.com/ant-design/pro-components/blob/master/packages/table/src/Table.tsx](https://github.com/ant-design/pro-components/blob/master/packages/table/src/Table.tsx)
<img width="792" alt="image" src="https://user-images.githubusercontent.com/11523869/206489873-8111432a-8db9-44ab-aace-e3acd48a5579.png">

只在查询表单的提交和重置事件中修改了 `formSearch`

可以在查询表单 `onValuesChange` 事件中也修改 `formSearch`

### 🚑 其他信息

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/11523869/206486750-84121fa9-d757-4482-ab37-0d7d04677dbc.png">

**Comment by chenshuai2144** [comment]
每次 onvaluechange 的时候，用 formRef 触发一下 submit。

不过性能可能会差一些

**Comment by myloveGy** [comment]
onValuesChange 的时候调用 setFormSearch ？ 目前就是通过调用查询表单的 submit 来代替表格 reload 的

**Comment by chenshuai2144** [comment]
你做的是对的，setFormSearch 不能实现你的需求
