### ISSUE TITLE
👑 [需求] umijs ProLayout 插件能否获支持获取 isMobile

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#6357]
umijs ProLayout 插件能否获支持获取 isMobile，在某些场景下，需要根据是否是手机端来定制样式token。

<img width="582" alt="image" src="https://user-images.githubusercontent.com/30397655/206600987-c9697c58-caf6-48ef-b585-32873091b603.png">

@chenshuai2144

**Comment by qiutian00** [comment]
`window.navigator.userAgent` ?

**Comment by leshalv** [comment]
> `window.navigator.userAgent` ?
这种方式肯定不行，是要根据设备屏幕大小来判断的。

**Comment by chenshuai2144** [comment]
```
  const colSize = useAntdMediaQuery();

  const isMobile = (colSize === 'sm' || colSize === 'xs') && !props.disableMobile;
```

直接用这个代码吧。反正开销不大

**Comment by leshalv** [comment]
useAntdMediaQuery是hooks的，umijs插件场景，用不了吧。

**Comment by chenshuai2144** [comment]
useAntdMediaQuery 里面是个简单的方法， 你可以看看源码
