### ISSUE TITLE
Table 黑色主题样式问题

### ISSUE THREAD

**Issue by afc163** [ant-design/pro-components#6360]
https://procomponents.ant.design/components/table#table-theme

<img width="1050" alt="图片" src="https://user-images.githubusercontent.com/507615/206642049-55827200-c7a9-4929-8793-0b66fc88763a.png">

**Comment by chenshuai2144** [comment]
@zombieJ  豆酱老师这算不算一个bug，config Provide 设置了黑色主题之后 如果还存在白色主题的card，样式不会插入进来。
理论上应该插入一下 黑色的吧

**Comment by afc163** [comment]
问题没了。
