### ISSUE TITLE
pro-table tableAlertOptionRender 方法中拿到的selectedRows不是最新的

### ISSUE THREAD

**Issue by zwb474287221** [ant-design/pro-components#6362]
### 🧐 问题描述

pro-table tableAlertOptionRender 方法中拿到的selectedRows不是最新的

### 问题定位

  useEffect(() => {
    selectedRowsRef.current = selectedRowKeys!?.map(
      (key): T => preserveRecordsRef.current?.get(key) as T,
    );
  }, [selectedRowKeys]);

如上代码所示将值存入 ref 后没有触发重新渲染。

### 解决建议
重新触发一次渲染，或者只触发Alert组件的渲染，或者把渲染时机重新调整下。

**Comment by chenshuai2144** [comment]
selectedRows 是个 ref，你可以延迟一点再去拿一下。如果对数据要求高推荐自己算一下
