### ISSUE TITLE
🐛[BUG]umi3升级到umi4，ProForm下的<Form.Item>无法获取上下文，报错Can not find FormContext. Please make sure you wrap Field under Form；

### ISSUE THREAD

**Issue by titld** [ant-design/pro-components#6364]
### 🐛 bug 描述

ProForm里面引入自定义组件<Form.Item>，
![image](https://user-images.githubusercontent.com/57819648/206696146-3e5872cc-0c88-4c38-901f-9c7a172bb775.png)
此时没有问题；但是如果我把
![image](https://user-images.githubusercontent.com/57819648/206696228-734e9eac-f1e9-416b-8774-46a45d960c4f.png)
这一部分抽出来，封装成一个插件'@umijs/plugin-my-demo'，插件导出`MyPlugins`组件（真实的插件，从自定的插件中导出），然后以组件的方式引入
```js
import { MyPlugins } from '@umijs/plugin-my-demo';
<ProForm><MyPlugins /></ProForm>
```
就会破坏原有的Form结构，会报错：【Antd】Warning: Can not find FormContext. Please make sure you wrap Field under Form；
在umi3当中没有问题，但在umi4中就会出错而无法使用，是不是umi插件机制有问题，拿不到context？

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
打包了两份antd了，你注意一下antd的版本相同
