### ISSUE TITLE
🐛[BUG] 日期选择器月份和星期未实现本地化

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#6368]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

https://procomponents.ant.design/components/field-set/

**Comment by chenshuai2144** [comment]
手动配置一下 dayjs 或者moment的国际化配置，这是和组件是两个体系。
