### ISSUE TITLE
🧐[问题] StepsForm， 能否将每个step放入单独文件，并相互传递数据？

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#6369]
能否将每个step放入单独文件？因为都放在一起，内容太多
如果上面的可以，能否相互传递数据？

大致试了一下，没成功。

**Comment by Gip886** [comment]
把最外层的StepsForm 绑定formMapRef 传递给每个stepform组件中操作 可以？

**Comment by chenshuai2144** [comment]
可以的，新版本上能做了，用了context 来进行数据 传输了

**Comment by chenshuai2144** [comment]
>  把最外层的StepsForm 绑定formMapRef 传递给每个stepform组件中操作 可以？

  Form.useFormInstance() 试试这个api

**Comment by yxf18** [comment]
> 

最后你是怎么解决的？

**Comment by gaohongwei** [comment]
用context， 或  store， 不依赖props。我是用zustand store

**Comment by csywweb** [comment]
有代码吗？

**Comment by chenshuai2144** [comment]
现在官方支持了，你可以直接放了，不用特殊处理
