### ISSUE TITLE
devScripts.js:6523 TypeError: Cannot read properties of undefined (reading 'setExtraStackFrame')

### ISSUE THREAD

**Issue by LGHhua** [ant-design/pro-components#6376]
### 🧐 问题描述

设置了唯一的rowKey（ rowKey="id"，， rowKey={row => row.id}都试过），但会存在报错

### 💻 示例代码
![02dbacdf48750cd059c09c2849f2bb1](https://user-images.githubusercontent.com/48945910/207007413-6b0e281a-87bf-462f-8cd1-57d3a728b46e.png)

**Comment by LGHhua** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [[🐛[BUG] ProLayout - Uncaught TypeError: Cannot read properties of undefined (reading '0')) #6208](https://github.com/ant-design/pro-components/issues/6208)][🐛[BUG] ProLayout - Uncaught TypeError: Cannot read properties of undefined (reading '0'))][67%]
> * [[🐛[BUG] Cannot read properties of undefined (reading 'colorTextBase') #6109](https://github.com/ant-design/pro-components/issues/6109)][🐛[BUG] Cannot read properties of undefined (reading 'colorTextBase')][60%]

还没得到解决

**Comment by LGHhua** [comment]
版本   "@ant-design/pro-components": "^2.3.46",

**Comment by chenshuai2144** [comment]
这个报错一般是key不是 string 导致的，排查下你的数据把
