### ISSUE TITLE
🧐[问题] ProLayout中navTheme menuProps.theme错误

### ISSUE THREAD

**Issue by hsbtr** [ant-design/pro-components#6381]
`navTheme` 设置为 `realDark` 改变的是整个`ProLayout`主题变为暗黑模式，而不是只改变`side`或`header`的主题，menuProps.theme改变则未生效

![image](https://user-images.githubusercontent.com/46487804/207278152-d3597204-402d-4729-b0c5-82f87b2df86c.png)
![image](https://user-images.githubusercontent.com/46487804/207278247-34cc94f6-e8f0-4f91-a656-3946b789800c.png)
![image](https://user-images.githubusercontent.com/46487804/207278525-fa8c8f24-b421-4016-82e5-70ec4e42aaa4.png)
![image](https://user-images.githubusercontent.com/46487804/207278567-13754aa8-de58-46bd-a487-6a3ef4489605.png)

pro-components ^2.3.46
antd ^5.0.5

**Comment by chenshuai2144** [comment]
看看文档了，navTheme 不支持 dark了，现在要用的 token配置
