### ISSUE TITLE
🐛[BUG] SettingDrawer is not hidden in production environment

### ISSUE THREAD

**Issue by ngminhthanh12a3** [ant-design/pro-components#6386]
### 🐛 bug SettingDrawer is not hidden in production environment
I cannot close the Drawer when it is opened.
In the production mode, the SettingDrawer and MenuDrawer (in mobile responsive) can't be closed.
![Screenshot 2022-12-15 082031](https://user-images.githubusercontent.com/93377382/207750558-c41af697-ca1e-4c08-873e-9c064f47ef99.png)
![Screenshot 2022-12-15 081939](https://user-images.githubusercontent.com/93377382/207750564-40b6d364-20f7-4d39-913d-41d0f6124b88.png)

### © 版本信息
- ant-design-pro: [6.0.0-beta.1]
- antd: [^4.23.3]
- ProComponents 版本: [^2.3.13]

**Comment by houkunlin** [comment]
using ant-design-pro ? update https://github.com/ant-design/ant-design-pro/blob/master/src/app.tsx#L98

add `if(!isDev){return children;}`

**Comment by ngminhthanh12a3** [comment]
> using ant-design-pro ? update https://github.com/ant-design/ant-design-pro/blob/master/src/app.tsx#L98
> 
> add `if(!isDev){return children;}`



> using ant-design-pro ? update https://github.com/ant-design/ant-design-pro/blob/master/src/app.tsx#L98
> 
> add `if(!isDev){return children;}`

Sorry for not describing the bug particularly. The bug is that I cannot close the Drawer when it is opened.

**Comment by chenshuai2144** [comment]
Is collapse set wrong, or is an older version of antd used

**Comment by ngminhthanh12a3** [comment]
> Is collapse set wrong, or is an older version of antd used？

I don't think so, because MenuDrawer and SettingDrawer still work correctly in the development environment. However, in the production environment, Drawers can't be closed when they're opened.

**Comment by monkeykingblack** [comment]
I don't know why this issue is close, I am using latest version pro-component with max plugin now, and I can not close Menu drawer on Mobile responsive by click on overlay

**Comment by ngminhthanh12a3** [comment]
> I don't know why this issue is close, I am using latest version pro-component with max plugin now, and I can not close Menu drawer on Mobile responsive by click on overlay

Did you solve your problem? If you didn't, you would set up an Ant Design Pro 5.0 with Umi version 3.x to solve this problem.
Because you said you used "max", you are using umi version 4.x and it causes that issue.
