### ISSUE TITLE
🧐[问题] ProLayout的menuRender自定义菜单，不能实现左右布局

### ISSUE THREAD

**Issue by wangyuan0108** [ant-design/pro-components#6387]
提问前先看看：

### 🧐 问题描述

在使用ProLayout的menuRender自定义菜单的时候，渲染出来的节点不会与内容的content页面构成左右布局，而是直接在content页面的上方，如果带上dom参数就能达到左右布局，但是又不能完全的自定义了，也没有看到这个menuRender的使用方法的demo

### 💻 示例代码
```jsx
const renderMenu = (props) => {
    return (
      <div style={{
        display: 'flex',
        height: '100vh',
      }}>
        <div>{props.menuData?.map(item => <div>{item.name}</div>)}</div>
      </div>
    )
  }
```
### 🚑 其他信息

<img width="690" alt="image" src="https://user-images.githubusercontent.com/22407253/207751830-e655e506-a1df-4075-acba-f54c5639057d.png">

**Comment by chenshuai2144** [comment]
图图好评，

console下dom 是什么，模仿dom里面的结构设置下你菜单。我记得是一个 sider 组件，来自于antd的layout.sider

**Comment by wangyuan0108** [comment]
> 图图好评，
> 
> console下dom 是什么，模仿dom里面的结构设置下你菜单。我记得是一个 sider 组件，来自于antd的layout.sider

dom是一个返回的默认的默认的菜单，源码里面是直接返回的的sider，我的意思我不用那个dom就不能实现左右布局。但是用dom就直接是默认的菜单。。。

**Comment by wangyuan0108** [comment]
> 图图好评，
> 
> console下dom 是什么，模仿dom里面的结构设置下你菜单。我记得是一个 sider 组件，来自于antd的layout.sider

意思我也得用个sider来实现菜单？那我去试试

**Comment by wangyuan0108** [comment]
这个自定义菜单不能用随意的div自己完全自定义去写吗？

**Comment by chenshuai2144** [comment]
可以的，但是要处理的内容太多了，要学会layout的配置和各种数据的用处
