### ISSUE TITLE
👑 [需求]how can i set default label in cascader? 我如何才能在级联选择中设置一个缺省的标签名？

### ISSUE THREAD

**Issue by symnetry** [ant-design/pro-components#6390]
### 🔩 所属模块或组件
在protable中，总是能遇到需要valueType为cascader的需求，它的options是由label和value为对象的数组组成
比如下面这个数据

···
[
  {
    value: 'zhejiang',
    label: '浙江',
    children: [
      {
        value: 'hangzhou',
        label: '杭州',
        children: [
          {
            value: 'xihu',
            label: '西湖',
          },
          {
            value: 'xiasha',
            label: '下沙',
            disabled: true,
          },
        ],
      },
    ],
  }
  },
];
···

假设我的数据是['zhejiang','hangzhou','xihu']
那么这将在表格中很好的展示我要的数据 浙江/杭州/西湖

但是一旦上面的全集某一项被删除掉了以后
比如xihu这一项没了  那么我显示的数据则变成了  浙江/杭州/xihu

在现实场景中，我们会遇到各种产品列表以及它们的记录
产品列表中的某一项是可以被删除的 但是对应到它们的记录时 产品id还在记录中而产品本身倍删除了 这样用cascader就只能显示到它的id了

如果可以自定义的配置这个缺省项目就好了

**Comment by chenshuai2144** [comment]
我建议你最好用你的['zhejiang','hangzhou','xihu']，先差回来列表，然后再处理，或者打开 lableInvalue模式手动注入 label
`[{value:'zhejiang',"label":"浙江"},{value:'Hangzhou',"label":"杭州"},{value:'xihu',"label":"西湖"}]`
