### ISSUE TITLE
🧐[问题]ProTable 列字段 值类型设置成 digit 查询表单项编辑过会无法清空数据

### ISSUE THREAD

**Issue by BeDay** [ant-design/pro-components#6391]
### 🧐 问题描述
ProTable 列的值类型 配置成  digit 时 使用查询表单，就无法清空该表单项数据，删除数据后会被重置成 数字 0，只能使用重置按钮清除，但这样会同时清除其他表单项
{
        title: 'xxxx',
        dataIndex: 'xxxx',
        valueType: 'digit',
}

**Comment by chenshuai2144** [comment]
好像有这个设计，没办法设置成空，最小就是 0
