### ISSUE TITLE
🐛[BUG] ProForm 组件 dateFormmater 类型错误

### ISSUE THREAD

**Issue by guaijie** [ant-design/pro-components#6393]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProForm 组件 dateFormmater 类型错误，文档中明确可以使用 'date', 'time' 作为传值，当类型中并没有 ‘date' |'time' 等联合类型导致 ts 报错

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/30885718/208009501-0f20871b-da38-4730-8849-ceeb64fe8ad6.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/208704161-ff1e5c84-bbf3-4f18-8704-f5e9b9c1190a.png)


连夜改了文档
