### ISSUE TITLE
SettingDrawer 怎么忽略指定 dom或者 class下样式，现在有部分地方需要亮色背景，设置后被强制改变

### ISSUE THREAD

**Issue by luzhiy123** [ant-design/pro-components#6405]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### ⛰ 功能需求适用场景
部分功能点需要样式突出，要求采用亮色背景，但是被realDark功能强制改成暗色背景

**Comment by chenshuai2144** [comment]
https://darkreader.org/help/zh-CN/

我们用的这个库，你可以自行实现一下
