### ISSUE TITLE
🧐[问题] How to create/add form input fields/columns  with Form.List, and add headers for each column? 

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/pro-components#6406]
找到这个，   https://stackoverflow.com/questions/71865438/antd-form-list-can-i-add-label-on-top-only-one-line-not-repeat?rq=1， 方法不是很理想。

**Comment by gaohongwei** [comment]
@chenshuai2144 有空支个招？

**Comment by chenshuai2144** [comment]
要是想用 columns ，推荐可编辑表格
