### ISSUE TITLE
🧐[问题] protable search query form 'LightFilter' validation 

### ISSUE THREAD

**Issue by jinseonghee** [ant-design/pro-components#6409]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

I'am attempting to try and customize the "search" using search filterType= "light" with protable.
when I use search query form my protable adding validation, It didn't work.
Do you guys have any solve this problem which I'am using light filterType with default validation in protable?

### 🚑 其他信息

Here's my code.
I'm using react with typescript.

const Columns: ProColumns<ListItem>[] = [
```
{
		title: 'userID',
		dataIndex: 'user_id'
		key: 'user_id',
		valueType: 'text',
		formItemProps: {
		lightProps: {
		rules: [
			{
	            required: true,
	             validator(rule, value){
	       if (value.length < 2 || value.length > 32) {
	         return Promise.reject('userID must be between 2 and 32 characters');
	       } else {
	         return value;
	         return Promise.resolve();
	       }
	     },
	   },
	 ],
	},

```
return (
            <>
	    <ProTable<ListItem, PageParams, string>
             search = {{
		filterType: ‘light’
                }}
	     </>

**Comment by chenshuai2144** [comment]
| 属性 | 描述 | 类型 | 默认值 |
| --- | --- | --- | --- |
| `formItemProps` | The configuration passed to Form.Item allows rules to be configured, but the default query form rules are not valid. The 'ignoreRules' | needs to be configured `(form,config)=>formItemProps` | `formItemProps` | - |
