### ISSUE TITLE
🐛[BUG] StepsForm.StepForm onFinish 返回 false，并未生效。

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#6412]

**Comment by chenshuai2144** [comment]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/8186664/217454465-1d94c884-0964-4004-9ca5-27c0e6a940a0.png">


https://github.com/ant-design/pro-components/commit/e0b4858f176730748f0f18eac6936f9b89d92d61

代码在这里，你看看原因，是不是报错了
