### ISSUE TITLE
👑 [需求] CheckCard能支持修改选中的颜色、自定义选中的角标比如支持ReactNode、选中的角标支持自定义的位置

### ISSUE THREAD

**Issue by wangyuan0108** [ant-design/pro-components#6413]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件
CheckCard

### 🥰 需求描述
比如我想让选中的背景色事黑色半透明，选中的icon是一个对号放中间，或者我想自定义一个角标，可能放在右上方，也有可能放在右下方，所以需要支持自定义角标的位置

### ⛰ 功能需求适用场景
<img width="550" alt="image" src="https://user-images.githubusercontent.com/22407253/209046612-df6e5930-d6e1-402f-8279-3b1d17c5dc63.png">

**Comment by chenshuai2144** [comment]
这样我们的样式就没法自定义了，不是很推荐
