### ISSUE TITLE
🐛[BUG] disabledTime of the ProFormDateTimePicker is not typed.

### ISSUE THREAD

**Issue by nomikura** [ant-design/pro-components#6415]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
`disabledTime` of the `ProFormDateTimePicker` is not typed.
- `disabledTime: (date)`, date is any
- `disabledMinutes: (hour)`, hour is any
- `disabledSeconds: (hour, minute)`, hour and minute are any

### 📷 复现步骤
https://codesandbox.io/s/aged-cherry-5x0c2w?file=/src/App.tsx
![image](https://user-images.githubusercontent.com/20913381/209091312-849a2df9-00d8-4075-b38a-c1082b358ea4.png)

### 🏞 期望结果
Typed `disabledTime`

### © 版本信息

- ProComponents 版本: 2.3.47
- umi 版本: unused
- 浏览器环境: Google Chrome
- 开发环境: mac OS

**Comment by chenshuai2144** [comment]
检查下你的ts版本，我试了下是可以的


<img width="842" alt="image" src="https://user-images.githubusercontent.com/8186664/217454915-d5fa56da-5387-495f-b4de-bc9a6d4568bb.png">
