### ISSUE TITLE
🐛[BUG] 升级 antd5 之后，ProLayout 使用 rightContentRender 渲染 dropdown 组件时报错

### ISSUE THREAD

**Issue by flyingmylo** [ant-design/pro-components#6416]
### 🐛 bug 描述
antd 升级到 `^5.1.0` 版本后，项目中原有的 `ProLayout` 使用 `rightContentRender` 渲染 `Dropdown` 时报错如下，试了 `actionsRender` 和 `avatarProps` 虽然不报错但是渲染不出来内容。
![AKFaN.png](https://i.328888.xyz/2022/12/22/AKFaN.png)

### 📷 复现步骤
鼠标hover或者trigger时，控制台报错

### © 版本信息

"@ant-design/pro-layout": "^6.38.22",
"@ant-design/pro-components": "^2.3.47",

以上两种版本都试过是报错的

"antd": "^5.1.0",
"umi": "3.5.8",

**Comment by chenshuai2144** [comment]
按照报错你修改一下，这个是不让你多层组件
