### ISSUE TITLE
🐛[BUG] Cannot find module './index.less'

### ISSUE THREAD

**Issue by arifszn** [ant-design/pro-components#642]
### 🐛 bug 描述

Ignoring issue template as I don't understand Chinese. (You should use English or maintain separate repo for Chinese people who don't know English). My issue is when I importing any pro components, the error prompts:  **Uncaught Error: Cannot find module './index.less'**

I have installed ant and ant design pro components. I have imported 'antd/dist/antd.css' and don't want to use less. I am using in Laravel, so my project uses laravel mix.

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
you should  install  add less-loader

**Comment by arifszn** [comment]
> you should install add less-loader

less file location to compile?

**Comment by chenshuai2144** [comment]
This component library always needs to use less loader. You can try our umi

**Comment by arifszn** [comment]
@chenshuai2144  Can I use pro component standalone versions without umi? As far as I know, laravel supports less file. But it needs the location to comply it. 
![image](https://user-images.githubusercontent.com/45073703/94984735-37c47f80-0571-11eb-81f1-e10096cd92db.png)
Can you help me find the location? I have never worked with less file before.

**Comment by chenshuai2144** [comment]
You need set less-loader  

We support cra.

**Comment by chenshuai2144** [comment]
file in node_moudles/pro-table/es/index.js

**Comment by arifszn** [comment]
Finally was able to run pro components in Laravel. Here's how:
1. install less-loader
2. install less.
- If less version is 2.x.x, no configuration is needed.
- If less version is 3.x.x,  paste in webpack.mix.js:
```
mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.less$/,
                loader: 'less-loader',
                options: {
                    lessOptions: {
                        javascriptEnabled: true
                    }
                }
            }
        ]
    }
});
```

**Comment by arifszn** [comment]
As my issue has been solved, I will close it. Just one last query. What is the difference between pro-components and ant design pro's single component(https://v1.pro.ant.design/docs/use-components-alone)? Which is the recommend usage? As I can not use cra or umi in Laravel.

**Comment by chenshuai2144** [comment]
antd is basic and clear and can be used everywhere

 pro-components is heavy, complex, it is only suitable for  admin  applications
