### ISSUE TITLE
🐛[BUG] pro-components 1.1.1版本的SettingDrawer组件开发模式没有，生产模式出现

### ISSUE THREAD

**Issue by 596094101** [ant-design/pro-components#6428]
### © 版本信息

- ProComponents 版本: 1.1.1
- umi 版本: 3.5.0
- 浏览器环境：chrome
- 开发环境 mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/28803960/209541042-ac2c40c1-2a12-4db0-a7f4-a79feedf147f.png)

**Comment by chenshuai2144** [comment]
需要自己处理的，不是自动的
