### ISSUE TITLE
Customise SortOrder enums

### ISSUE THREAD

**Issue by ofuochi** [ant-design/pro-components#643]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, the SortOrder enums in the ProColumns is either 'ascend' or 'descend'. It should be customizable to allow any other value pair such as 1 and -1 or 'up' and 'down'

### What does the proposed API look like?
```js
...
CustomSortOrder: any
...
```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


To customize the SortOrder enums in the ProColumns, you can use the `sortOrder` prop in the `ColumnProps` interface to pass a custom `SortOrder`.

Here's an example on how to customize the SortOrder to use 1 and -1:

```jsx
import { Table } from 'antd';
import { ColumnProps } from 'antd/es/table';

interface DataProps {
  key: string;
  name: string;
  age: number;
  address: string;
}

interface CustomColumnProps<DataProps> extends ColumnProps<DataProps> {
  sortOrder: number | undefined;
}

const columns: CustomColumnProps<DataProps>[] = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
    sorter: (a, b) => a.name.localeCompare(b.name),
    sortOrder: undefined,
  },
  {
    title: 'Age',
    dataIndex: 'age',
    key: 'age',
    sorter: (a, b) => a.age - b.age,
    sortOrder: undefined,
  },
  {
    title: 'Address',
    dataIndex: 'address',
    key: 'address',
    sorter: (a, b) => a.address.localeCompare(b.address),
    sortOrder: undefined,
  },
];

const data: DataProps[] = [
  {
    key: '1',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
  },
  {
    key: '2',
    name: 'Jim Green',
    age: 42,
    address: 'London No. 1 Lake Park',
  },
  {
    key: '3',
    name: 'Joe Black',
    age: 32,
    address: 'Sidney No. 1 Lake Park',
  },
  {
    key: '4',
    name: 'Jim Red',
    age: 32,
    address: 'London No. 2 Lake Park',
  },
];

function onChange(pagination, filters, sorter, extra) {
  console.log('params', pagination, filters, sorter, extra);
}

function App() {
  return <Table dataSource={data} columns={columns} onChange={onChange} />;
}

export default App;
```

In this example, we defined a `CustomColumnProps` interface that extends the `ColumnProps` and adds a `sortOrder` prop that accepts `number` or `undefined` as a value.

Then we defined our columns as an array of `CustomColumnProps` and set the `sortOrder` prop to `undefined` initially.

To create a custom `SortOrder` logic, we pass a sorting function to the `sorter` prop of each column that compares the values of that column in each row. 

Finally, we pass the `columns` and `dataSource` to the `Table` component and provide a function to the `onChange` prop to retrieve the sorting information. 

You can modify this code to customize the SortOrder enums to use any other value pair of your choice. 

You can check out the Antd Table documentation for more information about the `sorter` and `sortOrder` props: https://ant.design/components/table/.
