### ISSUE TITLE
查询，重置，导出...搜索表单也会错位，只把搜索表单调大一点，或者另起一行

### ISSUE THREAD

**Issue by YM-20191008** [ant-design/pro-components#6437]
### 🧐 问题描述

span设置成8，查询，重置，导出...搜索表单也会错位，只把搜索表单调大一点，搜索表单span=16，其他的span=8
或者搜索表单另起一行

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/56300836/209813232-5e3321f6-c10d-43e4-a841-bf3af5db09af.png)

**Comment by chenshuai2144** [comment]
现在不支持的，要一起调整大， 或者用三个点省略

**Comment by YM-20191008** [comment]
> 现在不支持的，要一起调整大， 或者用三个点省略

你好，这个大概什么时候可以支持下（**搜索表单另起一行** 这个更好点，或者可以**分开设置span的大小**），，
我们搜索表单一般都会**超过两个**【查询，导出，重置，导出明细...】并且需要展示出来，不能省略调

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


如果您使用的是Ant Design的Form组件，可以尝试以下做法：

1. 设置搜索表单单独占一行

您可以使用`Form.Item`组件的`wrapperCol`属性将搜索表单布局到单独的一行。

```jsx
<Form layout="inline">
  <Row>
    <Col span={24}>
      <Form.Item label="关键词" name="search">
        <Input />
      </Form.Item>
    </Col>
  </Row>
  <Row gutter={24}>
    <Col>
      <Form.Item>
        <Button type="primary" htmlType="submit">查询</Button>
      </Form.Item>
    </Col>
    <Col>
      <Form.Item>
        <Button>导出</Button>
      </Form.Item>
    </Col>
    <Col>
      <Form.Item>
        <Button>重置</Button>
      </Form.Item>
    </Col>
  </Row>
</Form>
```

2. 将搜索表单展示为下拉框

对于过多的操作按钮，您可以考虑将其展示为下拉框，这样可以更好的节省空间。

```jsx
<Form layout="inline">
  <Form.Item label="关键词" name="search">
    <Input />
  </Form.Item>
  <Form.Item style={{ marginLeft: 'auto' }}>
    <Dropdown overlay={menu}>
      <Button>
        更多操作 <DownOutlined />
      </Button>
    </Dropdown>
  </Form.Item>
</Form>
```

更多关于Ant Design Form的使用和API，请查看官方文档：https://ant.design/components/form-cn/ 。

**Comment by YM-20191008** [comment]
用的ProTable，上边的两个解决都不太合适 ，看看还有其他的方式吗@chenshuai2144

**Comment by chenshuai2144** [comment]
我来跟进一下😏

**Comment by chenshuai2144** [comment]
| 参数 | 说明 | 类型 | 默认值 |
| --- | --- | --- | --- |
| submitterColSpanProps | 提交按钮所在 col 的 props | ColProps | - |

**Comment by haobarry** [comment]
> 参数	说明	类型	默认值
> submitterColSpanProps	提交按钮所在 col 的 props	ColProps	-

请问 这个选项什么时候添加的？哪个版本可以设置。

**Comment by YM-20191008** [comment]
能给具体的例子吗，我试了，没生效,下面是我写的
<QueryFilter >
<ProTable<ExpenseResult>
                    formRef={formRef}
                    {...expenseTableBaseProps() as any}
                    beforeSearchSubmit={setFormDefaultParam}
                    columns={getColumns()}
                    search={{
                        optionRender: (searchConfig, formProps, dom) => [
                            ...dom.reverse(),
                            <ExportButton  exportCode={'xxxexport_list'} key={"exportList"} requestData={onExportListParam} buttonText={"导出"}/>,
                            <ExportExpenseDetailButton  rootExpenseTypeOptions={(dropDownListMap[enumList]||[]).filter(e=>e.hasDetail)} exportCode={'xxxx_export_self'} key={"exportDetailList"} requestData={onExportDetailList} buttonText={"导出明细"}/>,
                            <Button type={"link"} style={{textAlign:"right"}} key={"help"}
                                    href="xxxx.mp4" target="_blank">
                                <span style={{verticalAlign:-2,fontWeight:"bold",fontSize:15,color:"#c00"}}>操作视频指引</span>
                                <img src="XXXXX.png" style={{display:"inline-block"}}/>
                            </Button>
                        ],
                        collapseRender: false,
                        collapsed: false,
                        span:16,
                    }}
                />
</QueryFilter>

**Comment by YM-20191008** [comment]
能给具体的例子吗，我试了，没生效,下面是我写的
`<ProTable
formRef={formRef}
{...expenseTableBaseProps() as any}
beforeSearchSubmit={setFormDefaultParam}
columns={getColumns()}
search={{
optionRender: (searchConfig, formProps, dom) => [
...dom.reverse(),
<ExportButton exportCode={'xxxexport_list'} key={"exportList"} requestData={onExportListParam} buttonText={"导出"}/>,
<ExportExpenseDetailButton rootExpenseTypeOptions={(dropDownListMap[enumList]||[]).filter(e=>e.hasDetail)} exportCode={'xxxx_export_self'} key={"exportDetailList"} requestData={onExportDetailList} buttonText={"导出明细"}/>,
<Button type={"link"} style={{textAlign:"right"}} key={"help"}
href="xxxx.mp4" target="_blank">
<span style={{verticalAlign:-2,fontWeight:"bold",fontSize:15,color:"#c00"}}>操作视频指引
<img src="XXXXX.png" style={{display:"inline-block"}}/>

],
collapseRender: false,
collapsed: false,
span:16,
}}
/>`

**Comment by YM-20191008** [comment]
能给具体的例子吗，我试了，没生效,下面是我写的
`<QueryFilter>
<ProTable<ExpenseResult>
                    formRef={formRef}
                    {...expenseTableBaseProps() as any}
                    beforeSearchSubmit={setFormDefaultParam}
                    columns={getColumns()}
                    search={{
                        optionRender: (searchConfig, formProps, dom) => [
                            ...dom.reverse(),
                            <ExportButton  exportCode={'exportList_self'} key={"exportList"} requestData={onExportListParam} buttonText={"导出"}/>,
                            <ExportExpenseDetailButton  rootExpenseTypeOptions={(dropDownListMap[EXPENSE_TYPE_LIST]||[]).filter(e=>e.hasDetail)} exportCode={'Detail_export_self'} key={"exportDetailList"} requestData={onExportDetailList} buttonText={"导出明细"}/>,
                            <Button type={"link"} style={{textAlign:"right"}} key={"help"}
                                    href="xxx.mp4" target="_blank">
                                <span style={{verticalAlign:-2,fontWeight:"bold",fontSize:15,color:"#c00"}}>操作视频指引</span>
                                <img src="xxxx.png" style={{display:"inline-block"}}/>
                            </Button>
                        ],
                        collapseRender: false,
                        collapsed: false,
                        span:16,
                    }}
                />
</QueryFilter>`
