### ISSUE TITLE
🐛[BUG]useStyle返回的token主题始终是蓝色

### ISSUE THREAD

**Issue by helloJincheng** [ant-design/pro-components#6439]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [2.3.48]
- umi 版本
- 浏览器环境
- 开发环境 [mac OS]

**Comment by helloJincheng** [comment]
![image](https://user-images.githubusercontent.com/27672145/209930049-42216e97-fe95-437e-9269-4b87f7073b1d.png)
![image](https://user-images.githubusercontent.com/27672145/209930116-17848cb2-40cd-4097-9391-3cd56990d774.png)
![image](https://user-images.githubusercontent.com/27672145/209930216-9ae89423-7587-45fe-a3da-829300b38977.png)

**Comment by helloJincheng** [comment]
2.3.47版本正常，2.3.48版本出现问题

**Comment by chenshuai2144** [comment]
升级到2.3.50 就能解决了，是个bug
