### ISSUE TITLE
🐛[BUG] 菜单展开背景透明

### ISSUE THREAD

**Issue by helloJincheng** [ant-design/pro-components#6441]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

 菜单展开背景透明
### © 版本信息

- ProComponents 版本: [2.3.48]
- umi 版本
- 浏览器环境
- 开发环境 [mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/27672145/209973530-c9dbb929-39b3-48c9-a4c1-ee98b7f5fdf2.png)

**Comment by hihuangwei** [comment]
![image](https://user-images.githubusercontent.com/3166799/210034714-50e8a28a-cd61-4430-b1b1-36f5c1f9e8b0.png)
折叠也透明了

**Comment by hihuangwei** [comment]
@afc163

**Comment by chenshuai2144** [comment]
会有新token来解决

**Comment by sushi-su** [comment]
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/50985188/210297336-8577f461-1a86-41c3-a68a-d326be2271a7.png">
可以修改 token 处理这个问题
