### ISSUE TITLE
🐛[BUG] 自定义ValueType ProDescriptions报错

### ISSUE THREAD

**Issue by EchOneJY** [ant-design/pro-components#6442]
### 🐛 bug 描述

按官网示例自定义ValueType，ProDescriptions会报错

### 📷 复现步骤

复制运行官网自定义 valueType的示例代码，渲染ProDescriptions会报错

### 🏞 期望结果

ProDescriptions自定义valueType中的render能正常渲染

### 💻 复现代码

https://procomponents.ant.design/components/schema#%E8%87%AA%E5%AE%9A%E4%B9%89-valuetype

### © 版本信息

- ProComponents 版本:  2.3.47
- umi 版本： 4.0.36
- 浏览器环境 Chrome
- 开发环境 Windows

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30290016/209987500-9f65291d-c4b0-41d1-97c7-dab5af6ab4ec.png)

**Comment by chenshuai2144** [comment]
保证一下全部基于 components 来导出，这种一般是多版本共存
```
import type { ProFormColumnsType } from '@ant-design/pro-components';
import { ProConfigProvider } from '@ant-design/pro-components';
```
