### ISSUE TITLE
🐛[BUG] ProTable  type="form"  request not work

### ISSUE THREAD

**Issue by Kastrcn** [ant-design/pro-components#6443]
### 🐛 bug 描述

ProTable  type="form"  request not work

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


### 可能原因及解决方法

1. 确认 ProTable 的 type 属性是否设置为 "form"，因为 request 仅支持 type="table" 的 ProTable 使用

2. 确认 request 属性是否正确设置了请求方法和接口地址，以及是否返回正确的数据格式，例如以下代码示例中的接口返回格式：

```typescript
import { request } from 'umi';
import { ProTable } from '@ant-design/pro-table';

const columns = [
  { title: '姓名', dataIndex: 'name' },
  { title: '年龄', dataIndex: 'age' },
  { title: '地址', dataIndex: 'address' },
];

const MyTable = () => (
  <ProTable
    columns={columns}
    type="form"
    request={async () => {
      const data = await request('/api/users');
      return {
        data: data.list,
        success: true,
        total: data.total,
      };
    }}
  />
);
```

3. 确认接口返回的数据格式是否与 ProTable 的 columns 属性中定义的字段一致，例如以上代码示例中的 columns 定义中必须包含 "name"、"age" 和 "address" 这三个字段。 

4. 如果以上检查都没有问题，建议尝试使用 react-devtools 查看组件的 Props 是否正确传递。 

### 相关文档

- [ProTable request 属性文档](https://procomponents.ant.design/components/table#request)
- [umi-request 请求库文档](https://github.com/umijs/umi-request)

**Comment by chenshuai2144** [comment]
就应该不工作的，因为 table 没有渲染了
