### ISSUE TITLE
铁子们 pro components 5.0 还能还原出经典布局么？👑 [需求]

### ISSUE THREAD

**Issue by hyzx86** [ant-design/pro-components#6445]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### ⛰ 功能需求适用场景
pro components 还能还原出这个 主题布局么？
![lQLPJxDsrmvBdXzNB3rNDCCw3kD-Pcs7etoDrNPuMgBWAA_3104_1914](https://user-images.githubusercontent.com/15613121/210167432-1b6286a4-aa28-4b86-93b3-a423a004c50f.png)
这个布局好尴尬啊。。 我想 让 用户信息 回到上面怎么搞啊?

![1672568345135_395C4119-586C-4777-AFAC-F000F17C65C5](https://user-images.githubusercontent.com/15613121/210167439-e78d461d-03d0-4219-bc09-8c0b376be694.png)

**Comment by hihuangwei** [comment]
妥妥可以的

**Comment by mwj610** [comment]
layout:'mix'  splitMenus:false   稍微看起来像一点😂

**Comment by hyzx86** [comment]
> layout:'mix' splitMenus:false 稍微看起来像一点😂

但是 头部 在 菜单 以上了~

**Comment by Gzbox** [comment]
移动到左下角的设计真的好尴尬啊    能不能提供成可选的啊  @chenshuai2144

**Comment by hyzx86** [comment]
是啊大帅 @chenshuai2144

**Comment by chenshuai2144** [comment]
用 mix 吧，设计师为了扩大可视区域
