### ISSUE TITLE
🐛[BUG]ProList 编辑模式下，各个位置编辑框挤在一起了

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#6446]
### 🐛 bug 描述

效果如图所示，几个编辑框挤在一起了

适用版本：    "@ant-design/pro-components": "^2.3.47",

![image](https://user-images.githubusercontent.com/12421552/210175121-95394a1a-e747-41a1-8139-13a43b8e11d9.png)

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/12421552/210175153-88acb4b7-661d-4c5b-87b1-44512dff9648.png)

`
<ProList
          key={item.menuKey + item.menuLabel}
          rowKey="id"
          headerTitle={item.menuLabel}
          dataSource={item.selecteds}
          showActions="always"
          editable={{
            type: 'multiple',
          }}
          metas={{
            title: {
              dataIndex: 'title',
              render: (dom: React.ReactNode, entity, index, action, schema) => {
                return (
                  <a
                    href={entity.sourceUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    key={`view-${entity.id}`}
                  >
                    {entity.title}
                  </a>
                );
              },
            },
            description: {
              dataIndex: 'summaries',
            },
            subTitle: {
              dataIndex: 'site',
              render: (dom: React.ReactNode, entity, index, action, schema) => {
                return (
                  <Space size={0}>
                    <Tag color="blue">{entity?.site}</Tag>
                  </Space>
                );
              },
            },
            actions: {
              render: (text, row, index, action) => [
                <a
                  onClick={() => {
                    action?.startEditable(row.id);
                  }}
                  key={`edit-${row.id}`}
                >
                  编辑
                </a>,
              ],
            },
          }}
        />
`

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


Hello! 首先需要确认用户给出的问题是否属于 Ant Design Pro 组件的 bug。如果是，可以尝试以下解决方案：

1. 检查是否有自定义 css 对组件样式进行了修改，尝试注释掉相关 css；
2. 将 "@ant-design/pro-components" 升级至最新版本，看是否能够解决该问题；
3. 如果最新版本并未解决问题，可以在 GitHub 上提交 issue，并提供尽可能详细的问题描述、重现步骤以及代码示例。


如果以上解决方案均无效，可以尝试自己修改源代码进行修复。对于 Ant Design Pro 组件库，源代码一般都是开源的，可以从 GitHub 上找到相应的组件源码。找到相应组件的源码后，可以通过修改相关样式或者结构来尝试解决问题。

最后提醒一下，在提 issue 时，一定要提供最小化的代码示例，包括组件的引入方式、使用方式以及样式。这样可以尽快帮助解决问题。
