### ISSUE TITLE
🐛[BUG]ProFormSelect.SearchSelect不支持自定义筛选

### ISSUE THREAD

**Issue by XinYueXiao** [ant-design/pro-components#6449]
### 🐛 bug 描述

ProFormSelect.SearchSelect不支持自定义筛选，例如：去除前后空格筛选

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/31272499/210310725-05283297-ddec-4bad-ae5f-11e2d4d006a0.png)

### 🏞 期望结果

支持前后去空格筛选

### 💻 复现代码

(https://codesandbox.io/s/cha-xun-biao-dan-forked-vt0mwf?file=/App.tsx)

### © 版本信息

![image](https://user-images.githubusercontent.com/31272499/210310756-eccf22e5-404f-417e-99e9-86111c223f98.png)

**Comment by chenshuai2144** [comment]
这个还是自己处理吧，组件内置这个感觉怪怪的
