### ISSUE TITLE
proList 设置分页，并未设置showTotal 也会展示 total信息, 有什么参数可以隐藏吗

### ISSUE THREAD

**Issue by holmesliang** [ant-design/pro-components#6453]
<img width="970" alt="image" src="https://user-images.githubusercontent.com/120447205/210480513-552af10c-97e4-4526-8754-2eb35fe20711.png">

**Comment by holmesliang** [comment]
<img width="913" alt="image" src="https://user-images.githubusercontent.com/120447205/210501642-d02d32a3-d807-401c-b67d-ea55f7855e3f.png">

**Comment by kungege** [comment]
```js
pagination={{
  showTotal: () => false
}}
```
