### ISSUE TITLE
🐛[BUG] ProLayout 浏览器切换到移动端

### ISSUE THREAD

**Issue by GuanErShuiShou** [ant-design/pro-components#6454]
### 🐛 bug 描述

1. 移动端菜单区域`token.sider`部分配置不生效，例如：`colorMenuBackground` `colorBgMenuItemSelected`等
2. 当`collapse`受控时移动端展开菜单后点击mask区域不触发`onCollapse`事件

### 📷 复现步骤
1. sider token 设置为 `{
          colorMenuBackground: '#001529',
        colorBgMenuItemCollapsedHover: 'rgba(0,0,0,0.09)',
        colorBgMenuItemCollapsedSelected: initialState?.settings?.colorPrimary,
        colorBgMenuItemCollapsedElevated: 'rgba(0,0,0,0.85)',
        colorMenuItemDivider: 'rgba(255,255,255,0.15)',
        colorBgMenuItemHover: 'rgba(0,0,0,0.09)',
        colorBgMenuItemSelected: initialState?.settings?.colorPrimary,
        colorTextMenuSelected: '#fff',
        colorTextMenuItemHover: 'rgba(255,255,255,0.75)',
        colorTextMenu: 'rgba(255,255,255,0.75)',
        colorTextMenuSecondary: 'rgba(255,255,255,0.65)',
        colorTextMenuTitle: 'rgba(255,255,255,0.95)',
        colorTextMenuActive: 'rgba(255,255,255,0.95)',
        colorTextSubMenuSelected: '#fff',
}`，浏览器切换到移动端展开菜单
2.  `collapse`受控时浏览器切换到移动端展开，点击mask区域复现

### © 版本信息

- ProComponents 版本: 2.3.49
- umi 版本 4.0.40
- 浏览器环境 chorme
- 开发环境 win

### 🚑 其他信息

设置移动端样式字体相关生效
![image](https://user-images.githubusercontent.com/34082148/210510282-b19046ef-182e-48d8-b329-585eb038a0b4.png)

**Comment by GuanErShuiShou** [comment]
@chenshuai2144 这个移动端token不生效在排期内了嘛

**Comment by XSmarter** [comment]
+1

**Comment by chenshuai2144** [comment]
这个暂时不打算做，因为收起来在另外一个容器里的风格会更特殊一些，如果要做要增加一套新的api出来
