### ISSUE TITLE
🧐[问题] Layout 菜单，li 的 title 和 Tooltip 重复，如何隐藏 Tooltip

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#6457]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

Layout 菜单，li 的 title 和 Tooltip 重复，如何隐藏 Tooltip。或者去掉
而且 Tooltip 会在 菜单收缩的情况下  卡在页面中

![无标题](https://user-images.githubusercontent.com/3166799/210572824-465ba803-c519-4629-8c5e-2372b6be224f.png)

![image](https://user-images.githubusercontent.com/3166799/210573452-e3b102c1-3817-406e-939c-fa94777a5ba7.png)

**Comment by chenshuai2144** [comment]
layout 做了一些改进了，试试

**Comment by gonghanleiq** [comment]
> layout 做了一些改进了，
什么改进

**Comment by chenshuai2144** [comment]
重写了 layout 的tooltip
