### ISSUE TITLE
🧐[问题] ProTable 中 column 设置 valueType: 'option'，是右对齐的，能否改成左对齐

### ISSUE THREAD

**Issue by weijie-he** [ant-design/pro-components#6459]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

ProTable 中 column 设置 valueType: 'option'，是右对齐的，能否改成左对齐

### 🚑 其他信息
官网的例子：

![image](https://user-images.githubusercontent.com/16081489/210699098-0142c6b7-7d2d-4418-afbc-3237b4018c89.png)

**Comment by jayt1001** [comment]
+1
顺便shuai总看看这个问题
https://github.com/ant-design/pro-components/issues/6331

**Comment by chenshuai2144** [comment]
是bug，我修复了
