### ISSUE TITLE
🐛[BUG] Pro table localization

### ISSUE THREAD

**Issue by smddzcy** [ant-design/pro-components#646]
Pro table localization is not working on the latest version (2.9.1)

**Comment by xXAvoraXx** [comment]
I have same issue problem. When I change to set english, It good work However, When I change to any other language, It had been settings to default language to Chinese.

**Comment by xXAvoraXx** [comment]
I think, It should be settings to language like locales folders and we should set to any language what we want.

**Comment by rbrugnollo** [comment]
Same issue here.

Even the example on [this page](https://procomponents.ant.design/components/table#%E5%9B%BD%E9%99%85%E5%8C%96%E7%A4%BA%E4%BE%8B) is not working.
