### ISSUE TITLE
🧐[问题]creacte react app创建的项目使用protable报错

### ISSUE THREAD

**Issue by yy305736605** [ant-design/pro-components#6461]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
umi和ice创建的都可以直接使用proTable及其他组件，cra的不行（有之前cra的项目想用pro），是有什么需要配置的吗，求解

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/75480124/210724862-57e3d449-ea9a-48fc-ad2a-69a5b42ae84b.png)

**Comment by chenshuai2144** [comment]
antd的版本太低了，建议直接全部用最新的，不然搞来搞去很麻烦。


procomponent一般会用最新的api
