### ISSUE TITLE
🐛[BUG] pro-layout 手动设置 breadcrumbs 构建后会丢失样式

### ISSUE THREAD

**Issue by jeasonstudio** [ant-design/pro-components#6462]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

见下方复现步骤描述

### 📷 复现步骤

```js
<PageContainer
    breadcrumb={{
               routes: [
                    {
                         path: '/customers',
                         breadcrumbName: '客户管理',
                    },
                    {
                         path: '/customers/:customerId',
                         breadcrumbName: '客户详情',
                    },
               ],
               itemRender: (routes) => (
                    <Link to={routes.path}>{routes.breadcrumbName}</Link>
               ),
          }}
/>
```

如上方式设置面包屑，在本地开启 mfsu 后样式正常，本地关闭 mfsu 或构建后的样式丢失（.antd-breadcrumb 都没有打包进来），目前手动在项目中引入兼容性代码可以解决：`import 'antd/es/breadcrumb/style';`

### 🏞 期望结果

本地关闭 mfsu 和构建后，面包屑样式正常

### 💻 复现代码

见上方代码示例

### © 版本信息

* @ant-design/pro-layout@7.5.2
* antd@4.24.7
* babel-plugin-import@1.13.5
* umi@4.0.0-canary.20221230.1

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好！根据你提供的信息，是手动设置面包屑的样式丢失，可能是由于依赖缺少样式文件，在构建时没有正确打包。你手动引入兼容性代码可以解决，但是更好的解决方案是检查一下是否安装了正确的 `babel-plugin-import` 插件。插件可以帮你在引入 antd 组件时自动引入相关的样式文件，以及优化代码。你可以查看你的配置文件 `babel.config.js` 是否正确引入了这个插件，同时检查一下插件的版本是否正确。这样在构建时，应该可以正确打包样式文件了。如果还不能解决问题，可以尝试调整 webpack 的构建配置，具体可以参考文档：https://umijs.org/docs/advanced-config#chainwebpack

**Comment by chenshuai2144** [comment]
修复了，我手动增加了一下

另外还是推荐升级 antd5
