### ISSUE TITLE
pro-table 列设置功能，列展示功能点击后，隐藏的列（hideInSetting）也不显示了🐛[BUG]

### ISSUE THREAD

**Issue by chenwei0824** [ant-design/pro-components#6463]
![image](https://user-images.githubusercontent.com/120008663/210740668-c7aeff81-0ffa-48b2-82be-5e0d57b71c44.png)
这里部分列设置了hideInSetting:true，点击了列设置后，这些列也被隐藏了，这是设计成这样的吗？

**Comment by chenshuai2144** [comment]
<img width="335" alt="image" src="https://user-images.githubusercontent.com/8186664/217462404-a9909413-6ea8-40e4-9cef-43de6a33c1f4.png">



是的，就是这么设计
