### ISSUE TITLE
Please let us use the component in english i am unable to do that🐛[BUG]

### ISSUE THREAD

**Issue by rohitkumar93** [ant-design/pro-components#6465]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
What problem did you run into?

**Comment by arifszn** [comment]
@rohitkumar93 Wrap your pro component with `ConfigProvider` and set the locale to English.

```jsx
import enUSIntl from 'antd/locale/en_US';


<ConfigProvider locale={enUSIntl}>
  <ProTable/>
</ConfigProvider>
```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


If you're using a ProComponent from the antd library, you can wrap it with the `ConfigProvider` component and set the locale to English using the `en_US` locale provided by antd. Here's an example:

```jsx
import { ConfigProvider } from 'antd';
import enUSIntl from 'antd/lib/locale/en_US';
import { ProTable } from '@ant-design/pro-table';

<ConfigProvider locale={enUSIntl}>
  <ProTable/>
</ConfigProvider>
``` 

By doing this, the language of your ProComponent should switch to English. You can find more information about the `ConfigProvider` component in the antd documentation: https://ant.design/components/config-provider/.

**Comment by rohitkumar93** [comment]
> @rohitkumar93 Wrap your pro component with `ConfigProvider` and set the locale to English.
> 
> ```js
> import enUSIntl from 'antd/locale/en_US';
> 
> 
> <ConfigProvider locale={enUSIntl}>
>   <ProTable/>
> </ConfigProvider>
> ```

_ I tried that but it did not help. I even tried several variations for that. I ended up not using that feature at all._

**Comment by arifszn** [comment]
Submit a reproducible link or repo.

**Comment by chenshuai2144** [comment]
你可以尝试使用 ConfigProvider 组件来切换你的组件语言。在该组件中，你可以设置 locale 属性为 'zh-CN'，即中文。这样，你的组件就会显示为中文了。

如果你使用的是日期组件，并且国际化设置仍然不生效，你可以尝试配置 dayjs.locale('zh-cn') 并检查你本地的 dayjs 版本和 antd 依赖的 dayjs 版本是否一致。这通常可以解决问题。
