### ISSUE TITLE
🧐[问题] 如何让滚动条仅在 内容区域滚动，而不穿过 导航栏

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#6466]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

如何让滚动条仅在 内容区域滚动，而不穿过 导航栏

![微信截图_20230105233826](https://user-images.githubusercontent.com/3166799/210820435-058a1e8a-6223-4edb-b18d-fa548efb2ecf.png)
![微信截图_20230105233350](https://user-images.githubusercontent.com/3166799/210820442-2e51bf69-2ae2-4bf3-948e-28045eee6ba3.png)

**Comment by chenshuai2144** [comment]
推荐不要玩花活了，大家都是这么搞的。兼容性最棒
