### ISSUE TITLE
👑 [需求] pro-components 有没有 CDN 版本

### ISSUE THREAD

**Issue by zeusyaoyao** [ant-design/pro-components#6469]
本人想在要 external pro-components，但是没有找到 pro-components 对应的 CDN 版本

**Comment by chenshuai2144** [comment]
https://unpkg.com/@ant-design/pro-components@2.3.52/dist/

看这里

**Comment by myzhoulang** [comment]
@chenshuai2144 2.3.52 后的CDN 版本一直报错 请问怎么解决
[https://github.com/ant-design/pro-components/issues/7139](https://github.com/ant-design/pro-components/issues/7139)

**Comment by fengyuchaochao** [comment]
> https://unpkg.com/@ant-design/pro-components@2.3.52/dist/
> 
> 看这里

只引入pro-components这一个cdn文件就可以了吗？好像只引入这一个，页面表单那些有问题，pro-form，pro-table等这些库需要单独处理吗？
