### ISSUE TITLE
列设置的拖拽顺序有时候会乱🐛[BUG]

### ISSUE THREAD

**Issue by chenwei0824** [ant-design/pro-components#6470]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 2.76.2]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


请提供更具体的问题和相关代码，以便我们能够更好地帮助您解决问题。同时，请参考如何提问问题的指南，以提供更准确和清晰的问题描述。谢谢！
