### ISSUE TITLE
🧐[问题] 如何全局覆盖 PageContainer 页容器 style

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#6480]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

如何全局覆盖 PageContainer 页容器 style

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/blob/master/packages/layout/src/components/GridContent/index.tsx

在这里，估计要搞个pr了，但是推荐还是用classname覆盖
