### ISSUE TITLE
🐛[BUG] Layout menu 图标在菜单收起开启时会动画错位，建议可关闭动画

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#6482]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

Layout menu 图标在菜单收起开启时会动画错位，建议可关闭动画

建议采取 and-design 的 Layout menu 方案
https://ant.design/components/layout-cn#components-layout-demo-custom-trigger 

### 📷 复现步骤

https://procomponents.ant.design/~demos/layout-menu-group

**Comment by Chastrlove** [comment]
![CleanShot 2023-02-14 at 18 25 02](https://user-images.githubusercontent.com/17813559/218708464-d31c402d-a241-45a8-9b9f-83ec884a5ae6.gif)

@chenshuai2144 
打开menu的时候，顶部有字体错位，好像也是动画的原因。
https://procomponents.ant.design/components/layout#packages-layout-src-components-layout-demo-theme

**Comment by Chastrlove** [comment]
antd默认的菜单没这个问题

**Comment by Muralitob** [comment]
我升级了半天，结果突然发现菜单是这个样子的。。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


您好，感谢您的反馈。我认为此问题可能是由于 CSS 样式冲突引起的。解决这个问题需要检查您的项目中菜单所依赖的 CSS 样式，并查看是否与主题样式冲突。

另外，antd 大多数组件的样式都是可定制和覆盖的。您可以通过修改它们的 CSS 类名和样式来调整它们的外观和行为。以下是一些示例，可以帮助您更好地了解如何使用 CSS 自定义样式：

- 如果您需要修改Layout组件的菜单宽度，您可以使用`Sider`的`width`属性并覆盖样式类`.ant-layout-sider`。
```
<Layout>
  <Sider width={200} className="custom-sider-style">
    <Menu></Menu>
  </Sider>
  <Content>Content</Content>
</Layout>

// CSS custom styles
.custom-sider-style .ant-layout-sider {
  background-color: #f0f2f5;
}
```

- 如果您需要自定义菜单图标或其他元素的样式，您可以使用`MenuItem`或`SubMenu`的`icon`属性，并覆盖默认图标或样式。
```
<Menu>
  <SubMenu key="sub1" title="Navigation One" icon={<Icon component={CustomIcon} />}>
    <MenuItem key="1">Menu Item 1</MenuItem>
    <MenuItem key="2">Menu Item 2</MenuItem>
  </SubMenu>
</Menu>

// CSS custom styles
.ant-menu-submenu-title {
  color: #1890ff;
}
```

- 如果您需要定制菜单的主题颜色或字体等样式，您可以使用`Menu`的`theme`属性，并覆盖默认主题样式。
```
<Menu theme="dark" mode="inline">
  <MenuItem key="1">
    <Icon type="pie-chart" />
    <span>Option 1</span>
  </MenuItem>
  <MenuItem key="2">
    <Icon type="desktop" />
    <span>Option 2</span>
  </MenuItem>
</Menu>

// CSS custom styles
.ant-menu-dark {
  background-color: #001529;
}

.ant-menu-item {
  font-size: 16px;
}
```

- 如果您需要关闭菜单图标在菜单收起开启时的动画，您可以使用`Menu`的`inlineCollapsed`属性，禁用内置的动画。
```
<Menu inlineCollapsed={true}>
  <MenuItem key="1">
    <Icon type="pie-chart" />
    <span>Option 1</span>
  </MenuItem>
  <MenuItem key="2">
    <Icon type="desktop" />
    <span>Option 2</span>
  </MenuItem>
</Menu>
```

希望这些示例可以帮助您更好地理解如何使用 CSS 自定义样式。如果问题仍然存在，请提供更多信息，我将尽力为您解决问题。

**Comment by chenshuai2144** [comment]
修复啦，给title加了个动画
