### ISSUE TITLE
🐛[BUG]导航菜单为什么一直带着原生的title？既然是菜单了还带着title多次一举

### ISSUE THREAD

**Issue by Elaine87** [ant-design/pro-components#6484]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

导航菜单为什么一直带着原生的title

**Comment by lnstock** [comment]
同问

**Comment by chenshuai2144** [comment]
这个应该是bug，我更新了一下，看看还有吗
