### ISSUE TITLE
EditableProTable 使用formItem模式，并且字段设置了formItemProps的rules时数据会出错🧐

### ISSUE THREAD

**Issue by WuJiY** [ant-design/pro-components#6485]
[示例代码](https://codesandbox.io/s/funny-cherry-ivgg7u?file=/src/App.tsx)

### 🧐 问题描述
EditableProTable 使用formItem模式，并且字段设置了formItemProps的rules时数据会出错。
![1](https://user-images.githubusercontent.com/183884/201242955-c3178025-4f49-4d6f-98df-3c086968b1ba.jpg)
当未开启（注释掉）formItemProps的rules时一切正常，
当开启使用formItemProps的rules时数据会出现错误
具体两种错误
步骤一：规格1 规格2分别新增两个规格值，生成好sku后填写好sku的库存此时有四条数据
![2](https://user-images.githubusercontent.com/183884/201243007-bcaaf2e4-01e3-4fb3-9b29-c189fc5ade40.jpg)
步骤二：新增一个规格2的规格值，现在应该sku的顺序变化了，如果开启了formItemProps的rules，则会清空顺序变化的库存值（预期不变化，因为是根据id判断的，id并没有变）。或者填写新增的sku的库存的时候 也会清空下面一条的值（应该也是顺序问题）
![3](https://user-images.githubusercontent.com/183884/201243072-27da76be-d1c6-4a5e-9e04-c969cf7b7b41.jpg)
![4](https://user-images.githubusercontent.com/183884/201243081-833d3fd8-d990-4a44-b5dd-d37e70d15fd5.jpg)

**Comment by huyongtao-cmd** [comment]
我也遇到了同样的问题，请问解决了吗

**Comment by WuJiY** [comment]
> 我也遇到了同样的问题，请问解决了吗

并没有

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你可以尝试更新 `antd` 的版本。根据该问题的 [GitHub issue #6199](https://github.com/ant-design/ant-design/issues/6199#issuecomment-809324418) 上的回答，更新到 `antd@4` 版本修复了此问题。

另外，你也可以试着使用 `validateTrigger` 代替 `rules`。在你的示例代码中，修改 `formItemProps` 为以下形式：

```tsx
formItemProps: {
    validateTrigger: ['onChange', 'onBlur'],
    // rules: [{ required: true }],
},
```

并在相关的组件中添加 `onFinishFailed` 事件来捕获验证失败的情况。具体可以参考[文档](https://ant.design/components/form-cn/#%E8%A7%84%E5%88%99)。

```tsx
const onFinishFailed = (err: any) => {
    console.log('Validation failed:', err);
};

<Form onFinish={onFinish} onFinishFailed={onFinishFailed}>
```

希望能对你有所帮助。

**Comment by huyongtao-cmd** [comment]
antd用的是4.17版本，还是有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月6日(星期一) 晚上6:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/pro-components] EditableProTable 使用formItem模式，并且字段设置了formItemProps的rules时数据会出错🧐 (Issue #6485)





  
TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。
  
你可以尝试更新 antd 的版本。根据该问题的 GitHub issue #6199 上的回答，更新到 ***@***.*** 版本修复了此问题。
 
另外，你也可以试着使用 validateTrigger 代替 rules。在你的示例代码中，修改 formItemProps 为以下形式：
 formItemProps: {     validateTrigger: ['onChange', 'onBlur'],     // rules: [{ required: true }], },
 
并在相关的组件中添加 onFinishFailed 事件来捕获验证失败的情况。具体可以参考文档。
 const onFinishFailed = (err: any) =&gt; {     console.log('Validation failed:', err); }; <Form onFinish={onFinish} onFinishFailed={onFinishFailed}&gt;
 
希望能对你有所帮助。

**Comment by chenshuai2144** [comment]
根据你提供的代码和问题描述，我了解到你在使用 EditableProTable 组件时遇到了一些问题。当你设置了字段的 formItemProps.rules 属性时，数据会出错。

出现的两个错误分别是：
1. 当你按照步骤一新增规格值并生成 SKU 后，填写对应的库存时，会出现四条数据。这个时候如果开启了 formItemProps.rules，会在填写库存时清空顺序变化的库存值。预期是不应该发生变化，因为它是根据 ID 判断的，而 ID 没有变化。
2. 当你新增一个规格2的规格值后，SKU 的顺序应该发生变化。但如果开启了 formItemProps.rules，会清空顺序变化的库存值。也就是说，填写新增的 SKU 的库存时，会清空下面一条 SKU 的库存值。这也是一个顺序问题。

这个问题可能是由于表单项的校验规则导致的。可能是规则校验的顺序不正确，导致出现了清空数据的问题。你可以尝试调整校验规则的顺序，确保先校验规格值的变化，再校验库存的填写。

此外，你还可以查看 EditableProTable 组件的文档，看是否有关于校验规则的特殊说明或使用方法。也可以查看组件的 GitHub 仓库，看是否有其他人遇到了类似的问题，并找到解决方案。

希望我的回答能对你有所帮助！如有更多问题，请随
