### ISSUE TITLE
🐛[BUG] ProLayout 样式错误

### ISSUE THREAD

**Issue by javahuang** [ant-design/pro-components#6486]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤

刷新页面有一定的概率出现页面样式错乱，上图是错乱的样式，下图是正常的样式

<img width="527" alt="image" src="https://user-images.githubusercontent.com/3992393/211244723-235a5424-0972-4980-bf10-271e27a22af1.png">

<img width="550" alt="image" src="https://user-images.githubusercontent.com/3992393/211244741-44444888-8752-4bfa-b830-e1a416032a07.png">

我查了下，样式错误的页面是有一段 css 没加载上

```css
:where(.css-teuonv).ant-page-header :where(.css-teuonv).ant-page-header-heading {
...
}
```

### 🏞 期望结果

期望样式能正常加载

### © 版本信息

- ProComponents 版本: [2.3.50]
- umi 版本 4.0.40
- 浏览器环境 chrome108
- 开发环境  mac OS

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好，看起来你遇到了一个样式错乱的问题。根据你提供的信息，可能是某些 `css` 没有加载上的原因。你可以尝试以下几个方法解决该问题：

1. 确定对应的文件是否正常加载

首先，可以通过控制台查看对应的 `css` 文件是否已经被加载了。如果没有加载，可能是路径不对或者文件没有被正确引用。

2. 确认版本是否匹配

查看官方文档或者该组件的 `Github` 仓库，确认 `ProComponents` 版本和 `umi` 版本是否匹配，否则可能会出现不兼容的情况，导致样式错乱。

3. 确认是否有其他样式文件覆盖了该文件的样式

检查是否有其他样式文件覆盖了该文件的样式，可能会导致该部分的样式出现问题。

如果以上方法无法解决该问题，你可以提供更多的信息，例如复现代码、更详细的错误描述等，这样我们能更好地帮助你解决问题。

**Comment by chenshuai2144** [comment]
修复了。hash重复导致的
