### ISSUE TITLE
🧐[问题] 获取不到formRef

### ISSUE THREAD

**Issue by ty01** [ant-design/pro-components#6490]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

pro-form版本1.74.7      log出来的 Formref.current   始终是 空对象 {} 

### 💻 示例代码

const Index = () => {
    const Formref = useRef()
    return <>
        <Button onClick={() => {
            console.log(Formref.current)
        }}>获取</Button>
        <BetaSchemaForm
            formRef={Formref}
            columns={[{
                title: "姓名",
                dataIndex: "name"
            }]}
            request={() => {
                return Promise.resolve({
                    name: "张三"
                })
            }}
        >

        </BetaSchemaForm>
    </>
}

### 🚑 其他信息

<!--
如截图等其他信息可以贴在这里

![image](https://user-images.githubusercontent.com/26292353/211312057-fe39c183-deb1-4d37-bfef-ea5566b1b859.png)

**Comment by chenshuai2144** [comment]
我记得修复了 能搞个在线的复现吗

**Comment by laosandegudai** [comment]
> 我记得修复了 能搞个在线的复现吗
这个我也遇到了，目前表象是request的使用导致的,去掉request一切正常，目前我的版本是
@ant-design/pro-form 1.74.7
@ant-design/pro-components@1.1.25

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题可能是由于 `BetaSchemaForm` 组件在请求数据时，导致 `formRef.current` 没有被正确地赋值。可以在请求完成之后，手动调用一下 `Formref.current?.resetFields()` 方法重置表单域的值，并打印一下 `Formref.current` 对象。

代码示例：

```
const Index = () => {
    const Formref = useRef();

    const handleRequest = () => {
        return Promise.resolve({
            name: "张三"
        }).then((data) => {
            Formref.current?.resetFields(); // 手动重置表单域的值
            console.log(Formref.current); // 打印Formref.current 看是否正确赋值
            return data;
        });
    };

    return (
        <>
            <Button onClick={() => {
                console.log(Formref.current);
            }}>获取</Button>
            <BetaSchemaForm
                formRef={Formref}
                columns={[{
                    title: "姓名",
                    dataIndex: "name"
                }]}
                request={handleRequest}
            >
            </BetaSchemaForm>
        </>
    );
}
```

如果上述方法无效，也可以尝试升级 `@ant-design/pro-form` 和 `@ant-design/pro-components` 包的版本至最新版本看是否已经修复此问题。

参考文档：

- [Ant Design Pro Form 文档 - formRef](https://procomponents.ant.design/components/form-cn/#formref)
- [Ant Design Form 文档 - resetFields](https://ant.design/components/form-cn/#API)

**Comment by chenshuai2144** [comment]
升级到 2.0 把

`    "@ant-design/pro-form": "2.15.1",`
