### ISSUE TITLE
🐛[BUG] actionRef.reset 重置后状态没有更新到UI上

### ISSUE THREAD

**Issue by Rey-Wang** [ant-design/pro-components#6495]
### 🐛 bug 描述

当调用actionRef.current.reset后，request被重新触发，参数中的filters以及sorter会被清空，但是UI上Column的filter dropdown没有发生任何变化，如何同步这个行为？即filter dropdown在reset后也被清空
### 📷 复现步骤
![reset](https://user-images.githubusercontent.com/45580554/211524152-f667221a-5b91-446f-a12e-be0913bbe2ac.gif)

https://codesandbox.io/s/toolbar-zi-ding-yi-forked-j5bxcz?file=/App.tsx:476-495

### 🏞 期望结果
期望UI在reset后和当前的filter sorter保持一致

### © 版本信息
@ant-design/pro-components 2.3.51
antd >=4.23.0
react >=16.9.0
react-dom =16.9.0

**Comment by chenshuai2144** [comment]
用 formref 清空一下试试

**Comment by Rey-Wang** [comment]
@chenshuai2144 formRef 是拿查询表单实例的，不是column filter

**Comment by chenshuai2144** [comment]
filters 和 sorter 还不支持受控，所以不会生效，有兴趣来个pr
