### ISSUE TITLE
🐛[BUG] In ProForm > StepsForm is changed to StepsFrom but not in Demo files.

### ISSUE THREAD

**Issue by SyedAsimAliSE** [ant-design/pro-components#650]
### 🐛 bug 描述

 In ProForm > **StepsForm** is changed to **StepsFrom** but not in Demo files.

### © 版本信息

- @ant-design/pro-form": "^1.0.0-beta.30"

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/44644354/95037703-52b80080-06e5-11eb-9872-5b1354f1a0ec.png)

![image](https://user-images.githubusercontent.com/44644354/95037733-69f6ee00-06e5-11eb-970a-4827c0d7298c.png)

**Comment by chenshuai2144** [comment]
you should update this components. this is a error. I fix it
