### ISSUE TITLE
🐛[BUG] ProTable的render方法actions.pageInfo取值不同步

### ISSUE THREAD

**Issue by ByYogi** [ant-design/pro-components#6500]
看复现
[CodeSandBox](https://codesandbox.io/s/protable-render-actions-pageinfohuo-qu-bu-ji-shi-6xup1s)

当切换table页时，render方法中`action.pageinfo.current`一直获取的是上次点击页的页码. 
可能是`usestate`更新问题.
![image](https://user-images.githubusercontent.com/111735598/211756984-bfaaa1ca-ee53-4791-83ab-f7b62f3c5528.png)

**Comment by xueyang996** [comment]
解决了吗？这个table 的columns渲染和antd 差别有点大，都没有拿到最新值

**Comment by ByYogi** [comment]
> 解决了吗？这个table 的columns渲染和antd 差别有点大，都没有拿到最新值

没解决，只能换种方式了

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


很抱歉听到你没有解决这个问题，ProTable 确实有时候在 `render` 函数中取值会存在一些小问题，但是我们可以换一个方式去解决。

这个 `render` 函数最主要的目的是渲染当前的表格项，如果我们把 `pageInfo` 当做 `props` 传进来的话，在到 `render` 函数的时候就已经是最新值了。因此，我们可以参考如下代码：

```jsx
import React from 'react';
import { ProTable } from '@ant-design/pro-table';

const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: 'Age',
    dataIndex: 'age',
    key: 'age',
  },
  {
    title: 'Address',
    dataIndex: 'address',
    key: 'address',
  },
];

export function Demo() {
  const [pageInfo, setPageInfo] = React.useState({}); // 初始为空对象

  const onLoad = (params) => { // 定义onLoad函数，用于获取分页信息
    setPageInfo(params);
    console.log(params);
    // 其他请求代码...
  };

  return (
    <ProTable
      columns={columns}
      request={onLoad}
      pagination={{
        current: pageInfo.current,
        pageSize: pageInfo.pageSize,
        total: pageInfo.total,
        onChange: (current, pageSize) => {
          onPageInfoChange(
            Object.assign({}, pageInfo, { current: current, pageSize: pageSize }),
          );
        },
      }}
    />
  );
}
```

在这个例子中，我们将 `pageInfo` 定义为一个 `props`，并在 `onLoad` 函数中更新最新的分页信息。在 `ProTable` 组件中，我们传递了 `pagination` 属性（这里只涉及分页信息），并设置了 `onChange` 属性，当表格页码改变时，我们可以通过 `onPageInfoChange` 函数来更新 `pageInfo` 状态。

总结：以上就是一个简单的解决方案，如果这个方案不符合你的需求，请告诉我。
