### ISSUE TITLE
ProList  和 ProTable 使用request 作为数据源的时候，如何手动触发request 函数调用，获取api数据 🧐[问题]

### ISSUE THREAD

**Issue by jmy2022** [ant-design/pro-components#6502]
ProList  和 ProTable 

![Screenshot 2023-01-11 at 22 10 51](https://user-images.githubusercontent.com/116630592/211827527-4c8a60ff-29ae-4416-96b7-7a433e87830f.png)
![Screenshot 2023-01-11 at 22 11 27](https://user-images.githubusercontent.com/116630592/211827656-230b34db-1621-4f2a-b4c9-4a7b3eefa76c.png)
需要手动，添加参数 触发调用api

**Comment by chenshuai2144** [comment]
如果你正在使用Ant Design Pro中的ProList或ProTable组件，并使用request作为数据源，那么你可以通过在组件中调用refetch函数来手动触发request函数。

具体实现方法如下：

使用useRef来定义一个ref，并与ProList或ProTable组件进行关联：
```
const actionRef = useRef();

<ProList
  ref={actionRef}
  ...
/>
```
在你想要手动触发request函数的时候，调用refetch函数：

`actionRef.current.refetch();`

这将触发ProList或ProTable组件中的request函数，从而获取api数据。
