### ISSUE TITLE
chrome 32位样式错乱

### ISSUE THREAD

**Issue by siliushi** [ant-design/pro-components#6503]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
chrome 32位样式错乱

### 📷 复现步骤
必现，官方demo也有问题
https://procomponents.ant.design/components/layout/

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
chrome 32 是什么？

**Comment by siliushi** [comment]
> chrome 32 是什么？

32位，chrome有64位和32位

**Comment by chenshuai2144** [comment]
是版本太低了吧
