### ISSUE TITLE
🧐[问题] EditableProTable: How to Add PopConfirm Text

### ISSUE THREAD

**Issue by thoughtpalette** [ant-design/pro-components#6509]
### 🧐 问题描述

I'm attempting to add locale/text to the PopConfirm component buttons that are displayed when Delete (defaultDom.delete) button is clicked. I don't see anywhere in the documentation or Internationalization where this functionality is listed.

I would like to add text to the Cancel and Delete button.

For example, properties such as:
`popConfirmText: (React.ReactNode)`
`popDeleteText: (React.ReactNode.`

### 🚑 其他信息

![Screenshot 2023-01-12 at 9 47 43 AM](https://user-images.githubusercontent.com/690624/212113761-0a790bcc-620f-48a4-ae3f-66f0bc290fbd.png)

**Comment by thoughtpalette** [comment]
Solution: You have to manually add the keys to an ConfigProvider wrapper.

```jsx
		<ConfigProvider locale={{
				locale: rootStore.locale,
				Popconfirm: {
					cancelText: t('code.codeMain.batchEdit.cancelDelete'),
					okText: t('code.codeMain.batchEdit.confirmDelete')
				}
			}}>
                    <EditableTable<T>>
                    ....
                    </EditableTable>
               </ConfigProvider>
```

**Comment by chenshuai2144** [comment]
### editable 编辑行配置

| 属性 | 描述 | 类型 | 默认值 |
| --- | --- | --- | --- |
| deletePopconfirmMessage | 删除时弹出的确认框提示消息 | `ReactNode` | `删除此行？` |

**Comment by resetsix** [comment]
> ### editable 编辑行配置
> 属性 	描述 	类型 	默认值
> deletePopconfirmMessage 	删除时弹出的确认框提示消息 	`ReactNode` 	`删除此行？`

请问如何关闭删除提示框？
