### ISSUE TITLE
🐛[BUG] ProTable columns initialValue does not work

### ISSUE THREAD

**Issue by scotty595** [ant-design/pro-components#651]
### 🐛 bug 描述

When using initialValue with any valueType, the initial value is not set for the filter.

### 📷 复现步骤

Using any of the example demos in the pro-table package ([https://github.com/ant-design/pro-components/tree/master/packages/table/src/demos](https://github.com/ant-design/pro-components/tree/master/packages/table/src/demos)), setting the initialValue of the column does not affect the filter.

End goal is to start the table with an initial filtered value (much like the `defaultFilteredValue` prop in the Ant Design Table), unless my understanding is incorrect the initial value is how this should be done in Pro Table?

### 🏞 期望结果

Expected default filter should be the initialValue

### 💻 复现代码

```

import React, { useRef } from 'react';
import { PlusOutlined } from '@ant-design/icons';
import { Button } from 'antd';
import ProTable, { ProColumns, ActionType } from '@ant-design/pro-table';
import request from 'umi-request';

const columns: ProColumns<any>[] = [
  {
    title: '序号',
    dataIndex: 'index',
    valueType: 'indexBorder',
    width: 72,
  },
  {
    title: 'State',
    dataIndex: 'state',
    initialValue: 'open',
    filters: true,
    valueEnum: {
      all: { text: 'All', status: 'Default' },
      open: {
        text: 'Open',
        status: 'Success',
      },
      closed: {
        text: 'Closed',
        status: 'Error',
      },
      processing: {
        text: 'Processing',
        status: 'Processing',
      },
    },
  },
];

export default () => {
  const actionRef = useRef<ActionType>();

  return (
    <ProTable<any>
      columns={columns}
      pagination={{
        showQuickJumper: true,
      }}
      actionRef={actionRef}
      request={async (params = {}) =>
        request<{
          data: any[];
        }>('https://proapi.azurewebsites.net/github/issues', {
          params,
        })
      }
      rowKey="id"
      dateFormatter="string"
      headerTitle="高级表格"
      toolBarRender={() => [
        <Button key="3" type="primary">
          <PlusOutlined />
          新建
        </Button>,
      ]}
    />
  );
};
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
it's work, you need update table verison is lastest

**Comment by iloveip** [comment]
Hi @scotty595 
Did you manage to get it working? I have the same problem.
