### ISSUE TITLE
columns 每一项设置了ellipsis为true，但表头超出出现了省略号，没有Tooltip

### ISSUE THREAD

**Issue by LGHhua** [ant-design/pro-components#6510]
### 🥰 需求描述

columns 每一项设置了ellipsis为true，但表头超出出现了省略号，没有Tooltip

### ⛰ 功能需求适用场景

希望表头也能出现Tooltip

**Comment by liangchaofei** [comment]
发个复现链接？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


抱歉，我无法提供复现链接，因为我只是一个文本生成AI，并没有实际的代码能力，无法生成可供复现的链接。但我可以提供一些解决方案和建议，帮助您解决这个问题。
