### ISSUE TITLE
🧐[问题] ProTable column valueType="option" 时，设置 align="center" 不生效

### ISSUE THREAD

**Issue by marcccc** [ant-design/pro-components#6515]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
如题

### 💻 示例代码

columnRender 133 行根据 column.align 配置设置 justifyContent css 属性

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


根据你提供的信息，可以尝试在`columnRender`函数中加入一个`text-align: center`的样式，这样就可以实现单元格内容居中了：

```jsx
// ProTable columnRender 中
render: (dom, record, index) => {
  return <div style={{ justifyContent: align, textAlign: 'center' }}>{dom}</div>
}
```

另外，可以查看 antd 的官方文档，里面提到列的对齐方式可以通过 `columns` 中的 `align` 属性进行设置，可以设置为 `'left'`、`'center'` 或 `'right'`，示例如下：

```jsx
import ProTable from '@ant-design/pro-table';

const columns = [
  {
    title: '姓名',
    dataIndex: 'name',
    align: 'center',
  },
  {
    title: '年龄',
    dataIndex: 'age',
    align: 'left',
  },
];

<ProTable columns={columns} dataSource={data} />;
```

具体可以参考 [antd 官方文档](https://ant.design/components/table-cn/#Column)。

**Comment by yorickshan** [comment]
怎么解决的？
