### ISSUE TITLE
🐛[BUG] ProForm 的 request 回显会有警告

### ISSUE THREAD

**Issue by Cyan-Xmw** [ant-design/pro-components#6516]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/40554571/212613775-ed5aea7d-3347-492e-87df-4beb8ca953d0.png)
### 🏞 期望结果

去除警告

### © 版本信息

- ProComponents 版本: ^2.3.52
- umi 版本:  ^4.0.33
- 浏览器环境: Google Chrome
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


根据截图，警告信息显示为`Warning: A value did not update within the time specified by the "transitionConfigurator" prop`. 这个警告是由`rc-select`组件引起的。可以在`rc-select`的文档中查看相关信息。https://github.com/react-component/select/blob/master/README.md

一个解决方案是添加一个props`transitionConfigurator={null}`到`<ProFormSelect>`组件上。这样可以禁止`rc-select`使用默认的`transitionConfigurator`。示例代码如下：

```
import { ProFormSelect } from '@ant-design/pro-form';
import { Form } from '@ant-design/compatible';
import '@ant-design/compatible/assets/index.css'

const FormItem = Form.Item;

const options = [
  {
    label: '选项1',
    value: 1,
  },
  {
    label: '选项2',
    value: 2,
  },
];

const Demo = () => {
  return (
    <Form>
      <FormItem label="姓名" name="username">
        <ProFormSelect
          width="md"
          valueEnum={{
            1: '张三',
            2: '李四',
          }}
          transitionConfigurator={null}
        />
      </FormItem>
    </Form>
  );
};

export default Demo;
``` 

除了这个解决方案，还有其他的解决方式。如果您的问题没有解决，请在github上向组件开发者或者社区提问。

**Comment by chenshuai2144** [comment]
不要重复设置 intalvalues 和 intalvalue
