### ISSUE TITLE
升级@ant-design/pro-components跟antd版本之后报错🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/pro-components#6519]
### 🐛 bug 描述
升级了@ant-design/pro-components版本到^2.3.52，升级antd版本到4.24.7，删除了.umi文件重新启动yarn start后，引入import { EditableProTable} from '@ant-design/pro-components' 报错，如图所示
![image](https://user-images.githubusercontent.com/20655248/212797954-890d5cca-bee0-422b-8a1a-b8a54d315e0f.png)
![image](https://user-images.githubusercontent.com/20655248/212798053-68f57842-f7ed-41a3-8d67-7f950ba0af37.png)
![image](https://user-images.githubusercontent.com/20655248/212798077-e4c464ff-a717-4d7c-b170-862e9d023b54.png)
![image](https://user-images.githubusercontent.com/20655248/212798168-7bf3302d-144a-46f3-b270-6dfd3dc45eb4.png)

版本如图所示：
![image](https://user-images.githubusercontent.com/20655248/212798290-183ad89e-cbe2-46e5-bb27-85f3fe21ef4b.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


### 🌟 解决方案

这个报错的原因是引入的组件库版本不匹配导致的，可以参考以下解决方案：

1. 把@ant-design/pro-table和@ant-design/pro-utils升级到最新版本

``` 
yarn add @ant-design/pro-table@2.10.0 @ant-design/pro-utils@3.4.4
```

2. 在Webpack配置中加入以下alias配置 （如果使用的是 TypeScript 4.x 需要加）

``` 
alias: {
    '@ant-design/pro-table': path.resolve(__dirname, '../node_modules/@ant-design/pro-table'),
},
```

3. 验证 pro-table 是否成功安装

``` 
// 引入组件
import { EditableProTable } from '@ant-design/pro-table';

// 添加以下代码
<EditableProTable actionRef={actionRef} recordCreatorProps={{ disabled: false }}/>
```

以上解决方案参考了[这篇issue](https://github.com/ant-design/ant-design-pro-components/issues/4542)的解决方案，如果还有问题欢迎在issue中提出。

**Comment by chenshuai2144** [comment]
修复啦，用了antd5导致的，现在不用了
