### ISSUE TITLE
🐛[BUG]ProFormSelect和dependencies或者ProFormDependency联合使用，ProFormSelect的request会触发多次

### ISSUE THREAD

**Issue by TianJianJun727** [ant-design/pro-components#6522]
### 🐛 bug 描述
ProFormSelect和dependencies或者ProFormDependency联合使用，当ProFormSelect的值首次发生改变后会触发request

### 📷 复现步骤
1.选择Select   ->  Dependency Select 因为依赖的参数发生改变 触发一次request请求，返回Dependency Select 的下拉选择项 （正常）
2.再次选择 Dependency Select ，由于keyWords由undefined变成 ""，又一次触发request(异常)

### 🏞 期望结果
再次选择 Dependency Select不触发request

### 💻 复现代码
```
<ProForm>
                    <ProFormSelect
                        name="a"
                        label="Select"
                        valueEnum={{
                            open: '未解决',
                            closed: '已解决',
                        }}
                    />
                    <ProFormSelect
                        name="b"
                        label="Dependency Select"
                        showSearch
                        dependencies={['a']}
                        fieldProps={{
                            fetchDataOnSearch: false
                        }}
                        request={async ({keyWords}, {params}) => {
                            console.log(keyWords, params);
                            console.log('ProFormSelect --- request');
                            if (params.a === 'open') {
                                return [
                                    {label: '未解决', value: 'open'},
                                ]
                            }
                            if (params.a === 'closed') {
                                return [
                                    {label: '已解决', value: 'closed'},
                                ]
                            }
                            return [];

                        }}
                    />
</ProForm>
```
### © 版本信息

- ProComponents 版本: 2.3.52
- umi 版本 :4.0.46
- 浏览器环境:edge 109
- 开发环境 🪟

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好，这个问题已经有人提交过并且已有官方解决方案。你可以参考如下的连接，看看是否能够解决你的问题： https://github.com/ant-design/pro-components/issues/6520 。其中给出的解决方案是在 dependencies 中添加一个字段，用来存储上一次 keyWords 的值，这样就可以避免重复触发 request 了。如果你还有其他问题或者需要更详细的解答，请随时告诉我，我会尽力帮助你。
