### ISSUE TITLE
🐛[BUG] 面包屑链接错误

### ISSUE THREAD

**Issue by wyzwhp** [ant-design/pro-components#6523]
### 🐛 bug 描述

在routes配置相应的菜单信息，{
    name: '个人中心',
    path: '/account',
    routes: [
      {
        path: '/account/center',
        component: './account/center',
        name: '个人中心',
      },
      {
        path: '/account/setting',
        component: './account/setting',
        name: '个人设置',
      },
    ],
  },
面包屑在umi设置成hash的情况下，按道理生成的链接应该是`#${path}`这个样的方式，现在却是`${path}`的方式，左侧的菜单栏是没有这样的问题的，不知道是我哪里缺少设置还是自身的bug

- ProComponents 版本: ["@ant-design/pro-components": "2.3.52",]

**Comment by chenshuai2144** [comment]
Ant Design 的面包屑组件支持通过 itemRender 属性来自定义面包屑的每一项的渲染，并且可以使用 hash 模式。

例如，你可以通过以下代码实现：
```

import { Link } from 'react-router-dom';

const breadcrumbItemRender = (route, params, routes, paths) => {
  const last = routes.indexOf(route) === routes.length - 1;
  return last ? (
    <span>{route.breadcrumbName}</span>
  ) : (
    <Link to={`#${paths.join('/')}`}>{route.breadcrumbName}</Link>
  );
};

<Breadcrumb itemRender={breadcrumbItemRender} routes={routes} />

```


这里的 routes 数组是面包屑路由的数组，每一项都包含路由的信息，如名称、路径等。

itemRender 函数的参数：

route：当前路由信息。
params：路由参数。
routes：所有路由信息。
paths：当前路径的所有组成部分。
通过这个函数，你可以根据需要定制面包屑的每一项的渲染，例如这里的代码将面包屑渲染成了一个带有链接的列表，每一项的链接都是使用 hash 模式实现的
