### ISSUE TITLE
🐛[BUG] Thai translation is not working as expected

### ISSUE THREAD

**Issue by EugeneGohh** [ant-design/pro-components#6529]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

Refer to the Ant Design repository on [GitHub Discussions](https://github.com/ant-design/ant-design/discussions/40263).

### 💻 复现代码

```
"antd": "^4.24.7",
"react": "^17.0.0",
"umi": "^3.5.0",
"umi-serve": "^1.9.10",
"@ant-design/pro-components": "^2.3.8",
"@ant-design/pro-descriptions": "^1.6.8",
"@ant-design/pro-form": "^1.18.3",
"@ant-design/pro-layout": "^6.15.3",
"@ant-design/pro-table": "^2.30.8",
```
- **MacBook Air M1**
- **MacOS Ventura**
- **Brave: v1.47.171**

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by EugeneGohh** [comment]
Refer #6535

**Comment by EugeneGohh** [comment]
@chenshuai2144 Can I have some input on this? The **thai** translation is not working as expected but it's working in this pull request #6535 

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/64187129/217976418-606deb97-510a-4b69-b14d-5a41beb2882a.png">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


Hi there! Thank you for reaching out to me. Based on the information you provided, it seems that the Thai translation is not working as expected in Ant Design's Table component. However, it is working in pull request #6535.

To diagnose this issue further, could you please provide more details on how the Thai translation is not working as expected? Also, could you please provide the version of Ant Design and any relevant code snippets you have?

In the meantime, I suggest checking the Ant Design documentation on internationalization configuration to see if there are any additional steps you may have missed: https://ant.design/docs/react/i18n.
