### ISSUE TITLE
🐛[BUG]ProTable 列样式错误

### ISSUE THREAD

**Issue by jwmxushang** [ant-design/pro-components#6530]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
当ProTable 列属性 valueType= 'option' ，align = 'center' 时，只有标题居中而内容未居中，左对齐显示

### © 版本信息

- ProComponents 版本: [2.3.52]
- antd 版本：4.24.4
- umi 版本: 3.4.7
- 浏览器环境 现代浏览器
- 开发环境 [windows 10]

### 🚑 其他信息

![U%{O8ZBXXJ_QUA5)~UT1%Y4](https://user-images.githubusercontent.com/96456999/213389500-7ec9bd89-674d-43cc-8a1d-667a5218b369.png)

**Comment by Seven777Z** [comment]
同

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


请尝试更新 ProComponents 的版本，例如升级到 2.4.2，或者参考该 Issue 中的讨论进行调整：

https://github.com/ant-design/pro-components/issues/1672

具体来说，可以在列定义中使用 render 函数来自定义渲染方式，并且在渲染时添加 align 样式即可。例如：

```
{
  title: 'Option',
  valueType: 'option',
  render: (_, row) => {
    return <div style={{ textAlign: 'center' }}>{row.option}</div>;
  },
},
```

此外，还可以使用 tableLayout: 'fixed' 和 columnWidth 配合来实现一些特殊的布局。

参考文档：

- ProTable: https://procomponents.ant.design/components/table-cn/
- React 渲染函数：https://reactjs.org/docs/rendering-elements.html
- tableLayout: https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout
- columnWidth: https://developer.mozilla.org/en-US/docs/Web/CSS/column-width

**Comment by chenshuai2144** [comment]
因为 render 里面的是个dom，所以不能居中，要居中的话可以在render的时候加个flex
