### ISSUE TITLE
🐛[BUG] 多余的console信息

### ISSUE THREAD

**Issue by jayt1001** [ant-design/pro-components#6531]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🏞 复现结果

![image](https://user-images.githubusercontent.com/29675005/213415528-00468f81-0eb0-4de3-8aee-7f27890c7a23.png)

### © 版本信息

@ant-design/pro-components@2.3.52
@ant-design/pro-table@3.2.12

**Comment by chenshuai2144** [comment]
感谢回复，已经删除
