### ISSUE TITLE
🐛[BUG] ProTable toolbar 抖动

### ISSUE THREAD

**Issue by jwmxushang** [ant-design/pro-components#6533]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
ProTable Toolbar控件较多挨在一起的时候出现控件抖动现象，QueryFilter同样有该问题
### © 版本信息

- ProComponents 版本: 2.3.52
- antd 版本：4.24.4
- umi 版本 3.4.7
- 浏览器环境 现代浏览器
- 开发环境 win10

### 🚑 其他信息

https://user-images.githubusercontent.com/96456999/213608402-914a0a37-c48a-4afe-b41b-44860c4d33f2.mp4

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好，根据你的描述以及视频，我大致理解你遇到了ProTable和QueryFilter的Toolbar抖动问题。这个问题可能是由于Toolbar中的图标大小和位置计算不准确，导致每次渲染时都会有微小的变化。

解决方案

可以尝试以下方法解决该问题：

1. 确认ProTable和QueryFilter的版本号，是否是最新版本，如果不是，可以进行升级；
2. 将Toolbar中的图标改为固定宽度和高度的SVG图片，例如：

   ```react
   import { PlusOutlined } from '@ant-design/icons';

   <PlusOutlined style={{ width: 16, height: 16 }} />
   ```

   这样可以保证图标的大小不会因为计算不准确而产生微小变化，从而减少抖动的问题；
   
3. 如果以上方法不行，可以在Toolbar组件外层加一个`div`，用`position: sticky`使其固定位置，例如：

   ```react
   <div style={{ position: 'sticky', top: 0 }}>
     <ProTable
       ...
       toolbar={{
         ...
       }}
     />
   </div>
   ```

   这样可以保证Toolbar不再和Table或Filter中的其他元素挨在一起，从而减少抖动的问题。

参考资料

- [ProTable Issue #3052](https://github.com/ant-design/pro-components/issues/3052)
- [StackOverflow: CSS Sticky + Bootstrap Navbar Works for Desktop, But Not for Mobile](https://stackoverflow.com/questions/54023670/css-sticky-bootstrap-navbar-works-for-desktop-but-not-for-mobile)
