### ISSUE TITLE
🐛[BUG] itemClick 遇到警告：A future version of React will block javascript:

### ISSUE THREAD

**Issue by silentbalanceyh** [ant-design/pro-components#6534]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

在配置ProLayout组件时，通过appList设置应用列表，由于我们项目使用了`react-router`做路由，所以放弃使用属性`url`，而改用`itemClick`执行自定义脚本，执行时遇到了如下警告信息：

```shell
Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:;"
```

### 📷 复现步骤

直接在官方Demo中追加ProLayout的`itemClick`即可重现问题。

### 🏞 期望结果

不出现该警告

### 💻 复现代码

此处提供源码位置：packages/layout/src/components/AppsLogoComponents/

- DefaultContent.tsx（37到48行）
- SimpleContent.tsx（67到77行）

```tsx
              <a
                href={itemClick ? 'javascript:;' : app.url}
                onClick={() => itemClick?.(app)}
                target={app.target}
                rel="noreferrer"
              >
                {defaultRenderLogo(app.icon)}
                <div>
                  <div>{app.title}</div>
                  {app.desc ? <span>{app.desc}</span> : null}
                </div>
              </a>
```

此处设置`href`时，若存在itemClick可直接将href设置成`#`或`""`而不使用`javascript:;`，这个警告就会消失。

### © 版本信息

- ProComponents：2.3.52
- umi 版本：无
- 浏览器环境：Chrome
- 开发环境：MacOs

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/10274220/213863565-b888d127-93af-4a26-97d5-ef7595a048fa.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好，目前看来，这个问题是由于使用了 `javascript:` 形式的链接造成的，而这种形式已经被标记为不安全，未来的 React 版本可能会默认禁用。为了避免这个问题，可以考虑将链接设置为一个不包含 `javascript:` 的形式，比如使用一个 `#` 或者 `""` 作为链接地址。

对于 ProLayout 组件的 `itemClick` 属性，你可以尝试直接将链接地址设置为 `#` 或者 `""`，这样就无需使用 `javascript:` 形式的链接了。同时，我也建议你向组件的开发人员提交一个 issue，提出这个问题并说明解决方案，以帮助他们更快地修复这个问题。如果你有能力并且感兴趣，也可以提交一个 pull request 来解决这个问题。

如果你需要更多帮助，请告诉我。

**Comment by silentbalanceyh** [comment]
目前没有更新的计划么？关于这个警告？

**Comment by chenshuai2144** [comment]
ai 已经解释的很清楚了，react router不支持 javascript: 的 url，因为这样是不安全的
