### ISSUE TITLE
🐛[BUG]EditableProTable 使用editableFormRef后，无法用formRef.current.setFieldsValue改变table的值

### ISSUE THREAD

**Issue by jayt1001** [ant-design/pro-components#6539]
### 🐛 bug 描述

使用editableFormRef后，无法用formRef.current.setFieldsValue改变table的值：

![1](https://user-images.githubusercontent.com/29675005/214486640-2b9af0d0-b3b2-476a-9d1a-a455c4e89996.gif)

### 📷 复现步骤
https://codesandbox.io/s/edittable-7ih3ww?file=/App.tsx

复现代码：
```
import { EditableFormInstance, ProColumns, ProFormInstance, ProFormItem } from '@ant-design/pro-components';
import { EditableProTable, ProForm, ProFormTextArea, ProFormRadio } from '@ant-design/pro-components';
import React, { useRef, useState } from 'react';
import { Button } from 'antd';

const defaultData: any = [
  {
    id: 624748504,
    title: '活动名称一',
    decs: '这个活动真好玩',
    state: 'open',
    created_at: '1590486176000',
    update_at: '1590486176000',
  },
  {
    id: 624748505,
    title: '活动名称一2',
    decs: '这个活动真好玩',
    state: 'open',
    created_at: '1590486176000',
    update_at: '1590486176000',
  },
];

export default () => {
  const [editableKeys, setEditableRowKeys] = useState<React.Key[]>(() => [624748504]);
  const formRef = useRef<any>();
  const editorFormRef = useRef<EditableFormInstance<any>>();
  const columns: ProColumns<any>[] = [
    {
      title: '活动名称',
      dataIndex: 'title',
      formItemProps: () => {
        return {
          rules: [{ required: true, message: '此项为必填项' }],
        };
      },
      width: '30%',
    },
    {
      title: '状态',
      key: 'state',
      dataIndex: 'state',
      valueType: 'select',
      valueEnum: {
        all: { text: '全部', status: 'Default' },
        open: {
          text: '未解决',
          status: 'Error',
        },
        closed: {
          text: '已解决',
          status: 'Success',
        },
      },
    },
    {
      title: '描述',
      dataIndex: 'decs',
    },
    {
      title: '活动时间',
      dataIndex: 'created_at',
      valueType: 'date',
    },
  ];
  return (
    <>
      {' '}
      <Button
        onClick={() => {
          const rowId = Date.now();
          //通过formRef改变值
          formRef.current.setFieldsValue({
            data: [
              {
                id: rowId,
                title: rowId.toString(),
                decs: '这个活动真好玩',
                state: 'open',
                created_at: '1590486176000',
                update_at: '1590486176000',
              },
            ],
          });
          setEditableRowKeys([rowId]);
        }}
      >
        设置Editable值
      </Button>
      <ProForm<{
        table: any;
      }>
        formRef={formRef}
        submitter={false}
        initialValues={{ data: defaultData }}
      >
          <EditableProTable<any>
            rowKey="id"
            scroll={{
              x: 960,
            }}
            editableFormRef={editorFormRef}
            headerTitle="可编辑表格"
            maxLength={5}
            name="data"
            toolBarRender={false}
            columns={columns}
            editable={{
              type: 'multiple',
              editableKeys,
              onChange: setEditableRowKeys,
              actionRender: (row, _, dom) => {
                return [dom.delete];
              },
            }}
          />
      </ProForm>
    </>
  );
};

```

### 🏞 期望结果
能够改变其值

### © 版本信息

- ProComponents 版本: [2.3.52]

**Comment by chengmaoning** [comment]
> Table外层增加ProFormItem，ProFormItem使用name="data"可以解决这个问题
> 
> ```
> <ProFormItem name="data">
>   <EditableProTable<any>
>     rowKey="id"
>     scroll={{
>       x: 960
>     }}
>     editableFormRef={editorFormRef}
>     headerTitle="可编辑表格"
>     maxLength={5}
>     toolBarRender={false}
>     columns={columns}
>     editable={{
>       type: "multiple",
>       editableKeys,
>       onChange: setEditableRowKeys,
>       actionRender: (row, _, dom) => {
>         return [dom.delete];
>       }
>     }}
>   />
> </ProFormItem>
> ```

大哥，强，强烈建议官方示例增加ProFormItem包围EditableProTable，以免出现以上问题及其他问题（我在编辑-cancel时候发现，cancel了cell的值就没了。。。）

**Comment by liushuhui** [comment]
> Table外层增加ProFormItem，ProFormItem使用name="data"可以解决这个问题
> 
> ```
> <ProFormItem name="data">
>   <EditableProTable<any>
>     rowKey="id"
>     scroll={{
>       x: 960
>     }}
>     editableFormRef={editorFormRef}
>     headerTitle="可编辑表格"
>     maxLength={5}
>     toolBarRender={false}
>     columns={columns}
>     editable={{
>       type: "multiple",
>       editableKeys,
>       onChange: setEditableRowKeys,
>       actionRender: (row, _, dom) => {
>         return [dom.delete];
>       }
>     }}
>   />
> </ProFormItem>
> ```

大佬能解释下原理吗  @XueMeijing

**Comment by liushuhui** [comment]
> > Table外层增加ProFormItem，ProFormItem使用name="data"可以解决这个问题
> > ```
> > <ProFormItem name="data">
> >   <EditableProTable<any>
> >     rowKey="id"
> >     scroll={{
> >       x: 960
> >     }}
> >     editableFormRef={editorFormRef}
> >     headerTitle="可编辑表格"
> >     maxLength={5}
> >     toolBarRender={false}
> >     columns={columns}
> >     editable={{
> >       type: "multiple",
> >       editableKeys,
> >       onChange: setEditableRowKeys,
> >       actionRender: (row, _, dom) => {
> >         return [dom.delete];
> >       }
> >     }}
> >   />
> > </ProFormItem>
> > ```
> 
> 大哥，强，强烈建议官方示例增加ProFormItem包围EditableProTable，以免出现以上问题及其他问题（我在编辑-cancel时候发现，cancel了cell的值就没了。。。）

能解释下原理吗  @chengmaoning
