### ISSUE TITLE
🐛[BUG] ModalForm在使用BaseForm缺少第二个类型

### ISSUE THREAD

**Issue by hsbtr** [ant-design/pro-components#6540]
### 🐛 bug 描述

ModalForm使用params和request时; 自行定义request的params类型会提示类型不兼容错误

![image](https://user-images.githubusercontent.com/46487804/215254233-fa9d56d2-d13e-44a2-be41-52c17f5866f9.png)
![image](https://user-images.githubusercontent.com/46487804/215254253-63b85217-624f-4636-aed6-35749ab4a1ff.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


### ⚙️ 处理步骤

在看完您的问题截图之后，您在使用 `ModalForm` 中调用 `BaseForm` 组件的时候缺少了第二个类型。为了让 `request` 参数的类型能够兼容您定义的参数类型，您需要定义一个泛型参数为您的 `request` 的参数类型。下面是一个处理的思路：

1. 为您的 `request` 定义参数类型：

```typescript
interface YourParamsType {
  xxx: number;
  yyy: string;
}
```

2. 在创建 `ModalForm` 组件时使用定义好的泛型参数替换 `BaseForm` 的第二个类型参数。

```typescript
import { ModalForm, ProFormText } from '@ant-design/pro-form';
import type { ProColumns } from '@ant-design/pro-table';

// 添加泛型参数
const YourModalForm: React.FC<{
  onCancel: () => void;
  onSubmit: (values: any) => Promise<boolean>;
}> = ({ onCancel, onSubmit }) => {
  // 使用定义好的泛型参数
  return (
    <ModalForm<YourParamsType>
      title="TitlesModalForm "
      visible={true}
      onCancel={onCancel}
      onFinish={onSubmit}
      layout="horizontal"
      width={500}
    >
      <ProFormText name="text1" label="Text1" />
      <ProFormText name="text2" label="Text2" />
    </ModalForm>
  );
};
```

3. 在 `onFinish` 回调函数中使用泛型指定的类型获取表单参数。

```typescript
const handleSubmit = async (values: Partial<YourParamsType>) => {
  try {
    await YourRequestFunction(values); // 请求参数的类型就是定义好的 YourParamsType
    return true;
  } catch {
    return false;
  }
};

<YourModalForm onCancel={handleCancel} onSubmit={handleSubmit} />;
```

### 📚 相关文档

- [ModalForm](https://procomponents.ant.design/components/modal-form)
- [BaseForm](https://procomponents.ant.design/components/base-form)
