### ISSUE TITLE
🐛[BUG] ProLayout的fixedHeader属性失效，升级到@ant-design/pro-components:2.3.52后

### ISSUE THREAD

**Issue by louis-web** [ant-design/pro-components#6541]
### 🐛 bug 描述

升级到@ant-design/pro-components:2.3.52后，ProLayout的fixedHeader属性失效。
在defaultSettings.ts中配置 fixedHeader: false, 或在 app.tsx中layout配置fixedHeader: false,均不生效。header始终固定。

### © 版本信息

- ProComponents 版本:2.3.52
- umi 4.0.44
- 浏览器环境 Google Chrome 109.0.5414.75
- 开发环境 windows10
- node  v14.18.1

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


### 💡 解决方案

在新版本的@ant-design/pro-layout中，fixedHeader属性已被移除，现在需要使用fixedHeader.footerRender来控制header是否固定。

修改defaultSettings.ts中的配置：

```typescript
export default {
  fixedHeader: false,
  // 修改为
  layout: {
    footerRender: (_, defaultDom) => {
      return (
        <>
          {/* header是否固定 */}
          {defaultDom}
        </>
      );
    },
  },
};
```

修改app.tsx中的配置：

```typescript
import { BasicLayout, BasicLayoutProps } from '@ant-design/pro-layout';

const layout: BasicLayoutProps = {
  title: 'Ant Design Pro',
  logo: logo,
  // 修改为
  layout: {
    footerRender: (_, defaultDom) => {
      return (
        <>
          {/* header是否固定 */}
          {defaultDom}
        </>
      );
    },
  },
};

const BasicLayoutWrapper = (props: any) => (
  <BasicLayout {...props} {...layout} />
);

export default BasicLayoutWrapper;
```

详细文档请参考：https://procomponents.ant.design/components/layout#API

**Comment by chenshuai2144** [comment]
试了下没有问题，估计是依赖没有更新导致的
