### ISSUE TITLE
🐛[BUG]拖动排序表格拖动的元素样式丢失

### ISSUE THREAD

**Issue by mraiguo** [ant-design/pro-components#6548]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/22299421/215746405-f686ebef-4250-4678-88b6-661d0063942f.png)

### 📷 复现步骤

拖动表格行，样式丢失（我知道可以通过设置 class 来手动设置，能不能提供自动处理的方案？）

### 🏞 期望结果

拖动的行的样式不丢失

### 💻 复现代码

https://procomponents.ant.design/components/drag-sort-table#dragsorttable-drag

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


由于截图不能看到完整的代码，因此我只能暂时提供以下方式来解决问题。

你可以在你的 CSS 样式中为拖动时的元素添加一个样式：`user-select: none;`。这样做可以防止未选择的文本在拖动时出现。

你可以在你的代码中这样添加：

```
td, th {
  user-select: none;
}
```

对 `td` 和 `th` 应用这样的样式，这样就可以避免文本的选择。

如果您认为这仍未解决问题，请您提供一个更详细更全面的 code 示例，我们会尽快为您解决。

可以参考文档：

- [user-select](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select)

**Comment by bigmgreen** [comment]
出现样式丢失问题的原因是拖拽时会 clone 一个元素跟随鼠标移动，这个元素就是丢失样式的元素，react-sortable-hoc 默认会把这个元素插入到 body 上，而 ProTable 组件的样式有嵌套层级，因此丢失了样式，简单的解决方式通过 helperClass 重新复写下样式，如果想少写些样式，可以再设置下 helperContainer 让把 clone 元素插入到指定位置，我是这样指定的
```jsx
const SortContainer = SortableContainer((props: any) => <tbody ref={tbodyRef} {...props} />)
```

这个时候会发现大部分样式已经回来了，但是 td 宽度失效，观察后了解到，是由于 clone 元素的 ```position: fixed;``` 导致，需要手动设置下各个 td 的宽度，目前我就解决到这里了...

**Comment by mraiguo** [comment]
> 出现样式丢失问题的原因是拖拽时会 clone 一个元素跟随鼠标移动，这个元素就是丢失样式的元素，react-sortable-hoc 默认会把这个元素插入到 body 上，而 ProTable 组件的样式有嵌套层级，因此丢失了样式，简单的解决方式通过 helperClass 重新复写下样式，如果想少写些样式，可以再设置下 helperContainer 让把 clone 元素插入到指定位置，我是这样指定的
> 
> ```js
> const SortContainer = SortableContainer((props: any) => <tbody ref={tbodyRef} {...props} />)
> ```
> 
> 这个时候会发现大部分样式已经回来了，但是 td 宽度失效，观察后了解到，是由于 clone 元素的 `position: fixed;` 导致，需要手动设置下各个 td 的宽度，目前我就解决到这里了...

是的，目前也是处理到这一步（就是issue上说的自定义class方式），因为fixed的元素会脱离table的colgroup 的 col 配置这个td宽度问题无法处理

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


是的，因为设置了 `position: fixed;`，将元素从文档流中移除。由于每个 table 都有自己的 colgroup 和 col 配置，我们需要手动将每个 td 的宽度复制到 clone 元素的对应 td 上，以保持与原始表格中的样式一致。

这里有一些代码示例，用于解决这个问题：

```jsx
import React, { useCallback, useEffect, useRef } from "react";
import { SortableContainer, SortableElement } from "react-sortable-hoc";

const DragSortTable = ({ dataSource, onSortEnd }) => {
  const tbodyRef = useRef(null);

  // 复制 td 的样式
  const setCellWidth = useCallback(() => {
    if (!tbodyRef.current) return;

    const tHeadCols = tbodyRef.current.previousElementSibling.querySelectorAll("col");
    const tBodyCols = tbodyRef.current.querySelectorAll("col");

    const tBodyTd = tbodyRef.current.querySelector("tr > td");

    const tableOffsetLeft = tbodyRef.current.parentNode.parentNode.offsetLeft;

    [...tHeadCols, ...tBodyCols].forEach((col, i) => {
      const width = col.offsetWidth;
      const left = col.offsetLeft;

      const cloneTds = tbodyRef.current.querySelectorAll(`tr > td:nth-child(${i + 1})`);

      cloneTds.forEach((td) => {
        td.style.width = `${width}px`;
        td.style.position = "absolute";
        td.style.left = `${left}px`;
        td.style.top = "0px";
      });
    });

    tBodyTd && (tbodyRef.current.parentElement.parentElement.style.width = `${tBodyTd.offsetWidth}px`);
    tbodyRef.current.parentElement.parentElement.style.position = "relative";
    tbodyRef.current.parentElement.parentElement.style.left = `${tableOffsetLeft}px`;
  }, []);

  useEffect(() => {
    setCellWidth();
    window.addEventListener("resize", setCellWidth);
    return () => window.removeEventListener("resize", setCellWidth);
  }, [setCellWidth]);

  const SortableItem = SortableElement(({ item }) => (
    <tr className="drag-sort-body-row">
      {item.map((cell, i) => (
        <td key={i}>{cell}</td>
      ))}
    </tr>
  ));

  const sortableDataSource = dataSource.map((item) => item.slice());

  const SortableList = SortableContainer(({ items }) => (
    <tbody ref={tbodyRef}>
      {items.map((item, index) => (
        <SortableItem key={index} index={index} item={item} />
      ))}
    </tbody>
  ));

  return (
    <table className="drag-sort-table">
      <colgroup>
        {dataSource[0].map((_, i) => (
          <col key={i} />
        ))}
      </colgroup>
      <SortableList items={sortableDataSource} onSortEnd={onSortEnd} helperClass="dragging-item" />
    </table>
  );
};
```

恢复样式的关键在于手动计算并设置每个 td 的样式属性（如宽度，位置等）。上面的代码展示了如何使用 helperClass 和 helperContainer 以及如何监听 window 的 resize 事件并重新设置每个 td 的宽度。

如果您的表格不是拖动排序，您可以使用 css 方式来防止用户选择拖动期间的文本。

```css
td,
th {
  user-select: none;
}
```

这可以防止未选择的文本在拖动时出现。

这就是我可以为您提供的解决方案。希望这对你有所帮助！

**Comment by haobarry** [comment]
为了样式处理 怎么麻烦的么

**Comment by haobarry** [comment]
> ### 🐛 bug 描述
> 
> ![image](https://user-images.githubusercontent.com/22299421/215746405-f686ebef-4250-4678-88b6-661d0063942f.png)
> ### 📷 复现步骤
> 
> 拖动表格行，样式丢失（我知道可以通过设置 class 来手动设置，能不能提供自动处理的方案？）
> ### 🏞 期望结果
> 
> 拖动的行的样式不丢失
> ### 💻 复现代码
> 
> https://procomponents.ant.design/components/drag-sort-table#dragsorttable-drag
> ### © 版本信息
> 
>     * ProComponents 版本: [e.g. 4.0.0]
> 
>     * umi 版本
> 
>     * 浏览器环境
> 
>     * 开发环境 [e.g. mac OS]
> 
> 
> ### 🚑 其他信息
、
如何使用自定义类处理？

**Comment by chenshuai2144** [comment]
修复啦，我们换了底层，这次不会碰到这个问题了

**Comment by awesomeWay** [comment]
> 修复啦，我们换了底层，这次不会碰到这个问题了

如何覆写样式，如果在弹窗上，拖动表格行，样式因为z-index的原因显示不出来
