### ISSUE TITLE
'ModalForm' was not found in '@ant-design/pro-form'

### ISSUE THREAD

**Issue by HuabeiYou** [ant-design/pro-components#655]
### 🧐 问题描述

Console报错: export 'ModalForm' was not found in '@ant-design/pro-form'

对应的import为：
`import ProForm, {
  ModalForm,
  ProFormText,
} from '@ant-design/pro-form';`

**Comment by cheuk3** [comment]
same here

**Comment by chenshuai2144** [comment]
还没发布，要等等了

**Comment by niexq** [comment]
> 还没发布，要等等了

大佬，计划什么时候发布？

**Comment by chenshuai2144** [comment]
发布了

**Comment by niexq** [comment]
> 发布了

👏👏👏👏👏👏

**Comment by Tenodec** [comment]
1.1.5 还是不行啊
