### ISSUE TITLE
🐛[BUG]与 FormItem 配合的EditableProTable  如果数据源id为数字1,2,3，点击编辑第一行，第二行也会呈现可编辑状态

### ISSUE THREAD

**Issue by zhangchunxia** [ant-design/pro-components#6550]
### 🐛 bug 描述

在官方例子上 https://codesandbox.io/s/drbvbj?file=/App.tsx:502-833
把数据源的id 改为，1,2  点击编辑会出现同时编辑两行的情况
const defaultData: DataSourceType[] = [
  {
    id: 1,
    title: "活动名称一",
    decs: "这个活动真好玩",
    state: "open",
    created_at: "1590486176000",
    update_at: "1590486176000"
  },
  {
    id: 2,
    title: "活动名称二",
    decs: "这个活动真好玩",
    state: "closed",
    created_at: "1590481162000",
    update_at: "1590481162000"
  }
];

### 📷 复现步骤

https://codesandbox.io/s/yu-formitem-pei-he-forked-fiuipg?file=/App.tsx

### 🏞 期望结果
id为数字的情况很常见，希望能支持id，为1,2,3的数字类型，
并且不会被认为是index

**Comment by zhangchunxia** [comment]
已解决

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


这个问题的原因在于组件内部的实现逻辑是通过数组下标进行索引获取数据的，而数字类型的id与数组下标很容易混淆。

解决方法：
可以将id的类型设置为字符串类型，或是通过将id与数组下标的关系分开处理来解决这个问题。

第一种解决方案，将id的类型设置为字符串类型，即将defaultData中的id改为字符串类型，例如：
```
const defaultData: DataSourceType[] = [
  {
    id: "1",
    title: "活动名称一",
    decs: "这个活动真好玩",
    state: "open",
    created_at: "1590486176000",
    update_at: "1590486176000"
  },
  {
    id: "2",
    title: "活动名称二",
    decs: "这个活动真好玩",
    state: "closed",
    created_at: "1590481162000",
    update_at: "1590481162000"
  }
];
```

第二种解决方案，通过将id与数组下标的关系分开处理来解决这个问题，即将defaultData中的id设置为自增的数字类型，通过另外一个变量保存当前编辑的数据的id，例如：
```
const defaultData: DataSourceType[] = [
  {
    id: 0,
    title: "活动名称一",
    decs: "这个活动真好玩",
    state: "open",
    created_at: "1590486176000",
    update_at: "1590486176000"
  },
  {
    id: 1,
    title: "活动名称二",
    decs: "这个活动真好玩",
    state: "closed",
    created_at: "1590481162000",
    update_at: "1590481162000"
  }
];
let editingId = null; // 记录当前正在编辑的id
```

然后在EditableCell组件中将id与数组下标分开处理，例如：
```
// 判断当前格是否为编辑状态
const isEditing = record.id === editingId;

// 获取要编辑的数据，这里需要通过id与数组下标分开处理
const editItem = defaultData.find(item => item.id === record.id);

// 将要编辑的数据的id保存到变量中
editingId = record.id;
```
