### ISSUE TITLE
👑 [需求]antd5 PageContainer 只设置header背景

### ISSUE THREAD

**Issue by dongtao0725** [ant-design/pro-components#6551]
模块：ProLayout

### 🥰 需求描述

antd5 <PageContainer> 只设置header背景，目前pageContainer Token 中的colorBgPageContainer会把整个<PageContainer>背景色，现系统有antd4的效果，能单独设置<PageContainer>中header部分的背景色

**Comment by Gin-X** [comment]
我是这么干的。
<PageContainer
      tabList={[
        {
          tab: '在线会话',
          key: 'online',
        },
        {
          tab: '历史会话',
          key: 'history',
        },
      ]}
      header={{
        style: { backgroundColor: token.colorBgContainer },
      }}
>
      <>123</>
</PageContainer>

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


嗨，根据您提供的描述和代码，您已经成功地设置了 PageContainer 的 header 的背景色。

如果您想设置 antd5 PageContainer 中 header 的背景色，您可以在 header 中添加一个 style 属性，并将 backgroundColor 设置为您想要的颜色值即可。

例如：

```
<PageContainer
  header={{
    style: { backgroundColor: '#F5F5F5' },
  }}
>
  // 页面内容
</PageContainer>
```

需要注意的是，如果您想让此配置只对特定页面生效，您可以在单独页面中进行配置，而不是在整个项目中进行配置。

希望这能帮助您解决问题。如果您有任何其他问题，请随时问我。
