### ISSUE TITLE
🐛[BUG]protable列表显示bug

### ISSUE THREAD

**Issue by letmetellaman** [ant-design/pro-components#6554]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


感谢你的反馈！根据你提供的信息，可能是由于在使用`ellipsis`属性和`render`的第一个参数时，代码执行错误。建议可以先尝试升级ProComponents版本，如果问题仍然存在，可以在该组件的GitHub仓库中提出一个issue。 

同时，可以通过去看其他类似的issue来判断自己的问题是否已经有了解决方案，提供了代码示例和相关文档。在指定的GitHub仓库中搜索相似的问题，或者在搜索引擎中搜索相关关键字，可能会找到解决方案。

比如在ProComponents的GitHub仓库中，有一个和你类似的issue [#6161](https://github.com/ant-design/pro-components/issues/6161)，可能会对你有所帮助，可以尝试查看它提供的解决方案。
