### ISSUE TITLE
🐛[BUG] EditTableProTable数据莫名清空 之前 #5650 的问题一致，添加 name属性，问题依旧存在

### ISSUE THREAD

**Issue by zzq1101921989** [ant-design/pro-components#6559]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

编辑多个输入框的时候，删除掉第一个，剩下输入框的数据都会清除掉，和之前 https://github.com/ant-design/pro-components/issues/5650 的问题一致

### 📷 复现步骤

EditableProTable 添加了name属性之后就还是存在这个问题

### 🏞 期望结果

删除一行，不影响其他的数据

### 💻 复现代码

![image](https://user-images.githubusercontent.com/48540122/216265324-7035568d-87cd-420d-aceb-b06164052125.png)

### © 版本信息

- ProComponents 版本: [e.g. 2.3.52]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


对于这个问题，可能是由于 key 的问题导致的，建议在每行数据中加入唯一的 key，例如可以使用时间戳作为 key。代码示例：

```jsx
<EditableProTable
  recordCreatorProps={{ creatorButtonText: '添加新的字段' }}
  columns={columns}
  request={(params) => {
    // mock 数据
    return Promise.resolve({
      data: [...dataSource],
      success: true,
    });
  }}
  value={dataSource} // 将 value 属性赋值为 dataSource，这样可以保证删除数据后重新渲染时可以保留数据
  onChange={setDataSource}
  rowKey={(record) => record.key} // 指定每行数据的 key
/>
```

需要注意的是，rowKey 的返回值应该具有唯一性，如果有重复会导致渲染错误。更多信息请参考 Ant Design ProTable 中的 [rowKey](https://procomponents.ant.design/components/table/)。

**Comment by RyanKwok888** [comment]
这个问题在官方给的demo中也出现
![image](https://user-images.githubusercontent.com/23159401/223305450-f9fe9d30-31e7-4ae7-9837-854864912b38.png)

删除后
![image](https://user-images.githubusercontent.com/23159401/223305579-71c27494-0bb3-4c43-83c7-999feac3dcf3.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


对于在 Ant Design 官方提供的 Demo 中出现的问题，经分析可能出现这个问题的原因是没有正确地指定每一行的 key。当删除某一行数据的时候，如果没有正确指定每一行的 key，可能会导致 React 无法判断哪一行数据发生了改变从而导致数据错误。

解决方案同样可以参考上面在这个问题中提供的解决方案，即在每一行数据中加一个唯一的 key，并将返回值具有唯一性，以此来正确地指定每一行数据的 key。

具体的代码示例如下：

```jsx
  <EditableProTable 
    rowKey="id"  // 通过 rowKey 属性确保每一行的 key 是唯一的
    ...
  />
```

需要注意的是将 `rowKey` 属性值设置为数据源中某一列或唯一标识符来确保每一行数据的 key 是唯一的。更多关于 `rowKey` 属性的信息可以查看 Ant Design ProTable 的官方文档：https://procomponents.ant.design/components/table/#rowKey

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


如果之前已经在每一行数据上定义了唯一的 key，而问题还是没有解决，那么可能需要进一步分析。

这个问题有可能是因为每次编辑都会从当前的数据源 dataSource 去重新 render 组件而导致的，因此我们在删除每一条数据之后都把删除时的 dataSource 作为参数传递给 onChange 事件的回调函数，以便停止重新渲染，并且通过 useState 定义 dataSource 数据的状态。代码示例如下：

```jsx
import React, { useState } from 'react';
import { EditableProTable } from '@ant-design/pro-table';

const DemoEditableProTable = () => {
  const [dataSource, setDataSource] = useState([
    {
      id: '1',
      name: 'Edward King 0',
      age: 32,
      address: 'London, Park Lane no. 0',
    },
    {
      id: '2',
      name: 'Edward King 1',
      age: 32,
      address: 'London, Park Lane no. 1',
    },
    {
      id: '3',
      name: 'Edward King 2',
      age: 32,
      address: 'London, Park Lane no. 2',
    },
  ])

  const columns = [
    {
      title: '姓名',
      dataIndex: 'name',
      key: 'name',
      editable: true,
      // other props
    },
    {
      title: '年龄',
      dataIndex: 'age',
      key: 'age',
      editable: true,
      // other props
    },
    {
      title: '住址',
      dataIndex: 'address',
      key: 'address',
      editable: true,
      // other props
    },
    {
      title: '操作',
      valueType: 'option',
      render: (text, record, _, action) => [
        <a
          onClick={() => {
            action?.delete(record);
            setDataSource([...dataSource]); // 将删除后的 dataSource 重新赋值给 state，使组件停止重新渲染
          }}
        >
          删除
        </a>,
      ],
    },
  ];

  return <EditableProTable
    rowKey={(record) => record.id} // 将 id 作为每条数据的唯一标识并设置为 rowKey
    columns={columns}
    value={dataSource}
    onChange={setDataSource}
  />
}

export default DemoEditableProTable;
```

需要注意的是在代码中，我们将删除后的 dataSource 数据重新设置到 state 中，以便在组件重新渲染时防止每次都是编辑后的 dataSource 触发 rerender。如果状态没更新，组件将不会重新渲染。

**Comment by chenshuai2144** [comment]
更新下最近版本试试，最近解决了一个类似的问题

> 你描述的我无法重现。如果还有问题提交一个新的issue 并提供一个最小重现
