### ISSUE TITLE
🐛[BUG] pro-layout报错_interopRequireDefault is not a function

### ISSUE THREAD

**Issue by BillCao1997** [ant-design/pro-components#6561]
### 🐛 bug 描述
`antd`版本为`5.1.7`的情况下，安装`@ant-design/pro-layout`版本`7.6.1`以后，网页会报错`Uncaught TypeError: _interopRequireDefault is not a function`。查看错误信息像是从`@ant-design/icons`来的，感觉可能是`pro-layout`里面依赖的icons库版本太老了的原因（？），目前是4.0.0。

推断的原因是一开始提示的问题在`@ant-design/icons`，后来升级它到最新版本`5.0.1`以后错误提示就变到`pro-layout`去了

大概是这样的错误提示：
![image](https://user-images.githubusercontent.com/13502481/216519034-a3a57ff0-5f29-4361-b030-ab6d938ca72c.png)

谢谢啦

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


### 🚀 解决方案

这个问题应该是`pro-layout`依赖的`@ant-design/icons`版本过低导致的，可以升级`@ant-design/icons`。但是升级完之后，还需要在`pro-layout`里面使用最新的`@ant-design/icons`才能生效，需要在`pro-layout`里面做一个修改。

- 先升级`@ant-design/icons`到最新版本：

  ```
  npm install @ant-design/icons@latest
  ```

- 修改`pro-layout`依赖的`@ant-design/compatible`库，将其中的`@ant-design/icons`的引入路径指向新版本：

  ```
  // node_modules/@ant-design/compatible/lib/index.js
  import { ConfigConsumer } from 'antd/es/config-provider';
  import Form, { FormProps, useForm } from 'antd/es/form/Form';
  // 添加以下两行
  import * as allIcons from '@ant-design/icons';
  export { allIcons };
  import 'antd/es/form/style';
  ```

- 在`pro-layout`中导入需要使用的`@ant-design/icons`：

  ```
  // src/components/SiderMenu/SiderMenu.tsx
  import React, { Component } from 'react';
  import { Spin } from 'antd';
  import isEqual from 'lodash/isEqual';
  import memoizeOne from 'memoize-one';
  import { urlToList } from '../_utils/pathTools';
  
  import styles from './index.less';
  // 导入
  import { allIcons } from '@ant-design/compatible';
  
  const { SubMenu } = Menu;
  const Icon = ({ icon }) => {
    if (typeof icon === 'string') {
      return <LegacyIcon type={icon} />;
    }
    return icon;
  };
  
  // ...其他代码
  ```

这个修改应该能够解决问题，具体的解决方案详见[这篇讨论](https://github.com/ant-design/ant-design/issues/28855#issuecomment-886658397)。

**Comment by chenshuai2144** [comment]
升级到 5.0 了。试试还有问题吗？
