### ISSUE TITLE
🐛[BUG] LoginForm 嵌套ProTable问题

### ISSUE THREAD

**Issue by jilx951102** [ant-design/pro-components#6563]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

在LoginForm嵌套了ProTable，ProTable的type=”form“， 但是初始化的时候发现ProTable中绑定的formref首次取值错误，取到了外层的form引用。
<img width="688" alt="image" src="https://user-images.githubusercontent.com/36940549/216746468-651d639f-f042-49a0-9b7f-f339ec15bf0a.png">

<img width="596" alt="image" src="https://user-images.githubusercontent.com/36940549/216746435-07f4901f-5e19-4303-a6ba-9fbe20b0de1e.png">

图一是LoginForm, 图二是EditModal（里面包含了ProTable）

### 📷 复现步骤

调试源码发现可能是 BetaSchemaForm中的 propsFormRef首次赋值的逻辑有问题。
<img width="529" alt="image" src="https://user-images.githubusercontent.com/36940549/216746181-f02f69ed-6227-4f7e-94ed-817e914e9ed3.png">

如果源码修改成我上图第二个框中的代码，问题就可以解决

### 🏞 期望结果

ProTable被嵌套的时候，首次初始化，formref取值正常

### © 版本信息

- ProComponents 版本: 2.3.52
- umi 版本
- 浏览器环境  chrome
- 开发环境 [mac OS]

### 🚑 其他信息
<img width="347" alt="image" src="https://user-images.githubusercontent.com/36940549/216745976-8e61365e-477a-472a-b553-cd06513ca304.png">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


根据描述推断出问题原因为在 BetaSchemaForm 组件中的 propsFormRef 首次赋值逻辑有问题，导致在初始化时无法获取到正确的 form 引用，因此可以考虑在组件初始化时手动设置 propsFormRef 的值，避免首次赋值的问题。

可以尝试在 BetaSchemaForm 组件的 componentDidMount 生命周期内添加以下代码：

```javascript
if (!this.props.propsFormRef.current) {
  this.props.propsFormRef.current = this.props.formRef;
}
```

这段代码的作用是，如果在组件初始化之前 propsFormRef 还没有被赋值，就手动将其赋值为 formRef。这样就可以确保在初始化时获取到正确的 form 引用了。

如果以上方法不可行，也可以将 propsFormRef 从 BetaSchemaForm 组件中移出来，改为在 LoginForm 组件中手动创建 ref，并在初始化 ProTable 时手动将其传递给 ProTable 组件，确保能够获取到正确的 form 引用。

另外，在问题描述中提到了源码修改后可以解决问题，对于这种情况，建议提交一个 PR 给项目的维护者进行讨论和审核，以确保改动符合项目的质量要求并能够被合并进入代码库。

关于如何使用 ProTable 的 type="form" 属性，可以参考 ProTable 官方文档中的示例和说明：https://procomponents.ant.design/components/table#%E5%8A%9F%E8%83%BD%E6%BC%94%E7%A4%BA-%E5%85%A5%E5%8F%A3

**Comment by chenshuai2144** [comment]
你可以设置 props.form  来设置一下，是故意设置接收父组件的  form 示例的
