### ISSUE TITLE
🐛[BUG] optionFilterProp doesn't work with LightFilter

### ISSUE THREAD

**Issue by arwtyxouymz** [ant-design/pro-components#6564]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

`Select` component has a prop `optionFilterProp` to control the filtering behaviour and `ProFormSelect` component passes it to `Select` through `fieldProps`.
But if I use `ProFormSelect` with `LightFilter`, `optionFilterProp` doesn't work.

### 📷 复现步骤

https://codesandbox.io/s/qing-liang-shai-xuan-forked-8vmbeo?file=/App.tsx

### 🏞 期望结果

`optionFilterProp=label` can filter only by label, and `optionFilterProp=value` can filter only by value with `LightFilter`.

### 💻 复现代码

https://codesandbox.io/s/qing-liang-shai-xuan-forked-8vmbeo?file=/App.tsx

**Comment by kungege** [comment]
Working on this
