### ISSUE TITLE
🐛[BUG]LightFilter 筛选表单边框模式没有边框

### ISSUE THREAD

**Issue by johnwayen** [ant-design/pro-components#6566]
### 🐛 bug 描述
LightFilter 筛选表单边框模式没有边框

### 📷 复现步骤
官网文档上查看该组件示例就可以到看，筛选表单边框模式没有边框（原因是样式写得有问题 border: 1 solid #d9d9d9）

### 🏞 期望结果
1、边框样式：border: 1px solid #d9d9d9
2、边框样式也可以跟随全局token.borderRadius动态生成

### 💻 复现代码
官网文档上查看该组件示例就可以到看，筛选表单边框模式没有边框（原因是样式写得有问题 border: 1 solid #d9d9d9）

### © 版本信息
- umi 版本 4.0
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
<img width="1534" alt="image" src="https://user-images.githubusercontent.com/3950749/216937191-34d8e400-c01f-4e56-9d1f-822903105d5b.png">

**Comment by kungege** [comment]
@chenshuai2144 pr没合这个没解决。。。
