### ISSUE TITLE
vite搭建的项目，直接按照文档来安装pro-comp，启动会报错，需要安装rc-field-form🧐[问题]

### ISSUE THREAD

**Issue by Sunny-117** [ant-design/pro-components#6574]
只跑了这一个：https://procomponents.ant.design/docs

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/73089592/217249083-7b933ace-d5ef-4ff6-adde-31e2050d22dd.png">

**Comment by Sunny-117** [comment]
安装antd问题也可以解决，是需要安装antd吗？

**Comment by chenshuai2144** [comment]
antd 是必须的，

```
  "peerDependencies": {
    "antd": ">=4.23.0",
    "react": ">=16.9.0"
  },
```

你应该自动安装了antd 了吧

**Comment by ldwonday** [comment]
@chenshuai2144 安装antd是解决不了问题的，在npm 6下rc-field-form是不会提升到root下的，会安装在antd下，导致pro-form拿不到rc-field-form，建议解决，npm7+无问题，
<img width="849" alt="企业微信截图_fe62731a-6319-45d7-926b-95d2818e016d" src="https://github.com/ant-design/pro-components/assets/4630157/7c389cbb-67e8-48f2-9824-4a4a85a5bf85">
