### ISSUE TITLE
🧐[BUG]ProFormList 嵌套 ProFormDependency name={['name']} 获取不到内层数据

### ISSUE THREAD

**Issue by houkeepmoving** [ant-design/pro-components#6575]
![image](https://user-images.githubusercontent.com/29296595/217422436-5ab286c8-a2cc-4290-80a4-e128ae108333.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好，根据你提供的截图，可以看到你在使用 antd-pro 的 `ProFormList` 和 `ProFormDependency` 组件进行表单项的配置。但是在嵌套 `ProFormList` 中使用 `ProFormDependency` 组件无法获取到内层数据。这一问题可能是由于 `ProFormDependency` 组件和 `ProFormList` 组件的嵌套使用方式不正确导致的。

你可以尝试使用如下代码片段来解决这个问题：

```jsx
import { useState } from 'react';
import { ProFormList, ProFormDependency } from '@ant-design/pro-form';

const Demo = () => {
  const [data, setData] = useState([{ id: 1, name: '', intro: '' }]);

  return (
    <ProFormList
      name="test"
      creatorButtonProps={{
        position: 'bottom',
      }}
      children={(fields, { add, remove }) => {
        return (
          <>
            {fields.map((field, index) => (
              <ProFormDependency key={field.key} name={[field.name, 'id']} value={data[index]?.id}>
                <ProFormList key={field.key} name={field.name}>
                  <ProFormDependency name={[field.name, 'name']}>
                    <ProFormText />
                  </ProFormDependency>
                  <ProFormDependency name={[field.name, 'intro']}>
                    <ProFormTextArea />
                  </ProFormDependency>
                </ProFormList>
              </ProFormDependency>
            ))}
            <Button
              type="dashed"
              onClick={() => {
                add();
              }}
            >
              <PlusOutlined />
              新增
            </Button>
          </>
        );
      }}
    />
  );
};

export default Demo;
```

这里使用了 `useState` hook 来维护 `ProFormList` 中表单项的数据，并将数据作为 `ProFormDependency` 的默认值，这样可以实现嵌套表单项的联动更新。

希望这个解决方案能够帮助你解决问题。另外，也欢迎你查看 antd-pro 官方文档来更好地理解相关组件的使用方式。

**Comment by houkeepmoving** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。
> 
> 你好，根据你提供的截图，可以看到你在使用 antd-pro 的 `ProFormList` 和 `ProFormDependency` 组件进行表单项的配置。但是在嵌套 `ProFormList` 中使用 `ProFormDependency` 组件无法获取到内层数据。这一问题可能是由于 `ProFormDependency` 组件和 `ProFormList` 组件的嵌套使用方式不正确导致的。
> 
> 你可以尝试使用如下代码片段来解决这个问题：
> 
> ```js
> import { useState } from 'react';
> import { ProFormList, ProFormDependency } from '@ant-design/pro-form';
> 
> const Demo = () => {
>   const [data, setData] = useState([{ id: 1, name: '', intro: '' }]);
> 
>   return (
>     <ProFormList
>       name="test"
>       creatorButtonProps={{
>         position: 'bottom',
>       }}
>       children={(fields, { add, remove }) => {
>         return (
>           <>
>             {fields.map((field, index) => (
>               <ProFormDependency key={field.key} name={[field.name, 'id']} value={data[index]?.id}>
>                 <ProFormList key={field.key} name={field.name}>
>                   <ProFormDependency name={[field.name, 'name']}>
>                     <ProFormText />
>                   </ProFormDependency>
>                   <ProFormDependency name={[field.name, 'intro']}>
>                     <ProFormTextArea />
>                   </ProFormDependency>
>                 </ProFormList>
>               </ProFormDependency>
>             ))}
>             <Button
>               type="dashed"
>               onClick={() => {
>                 add();
>               }}
>             >
>               <PlusOutlined />
>               新增
>             </Button>
>           </>
>         );
>       }}
>     />
>   );
> };
> 
> export default Demo;
> ```
> 
> 这里使用了 `useState` hook 来维护 `ProFormList` 中表单项的数据，并将数据作为 `ProFormDependency` 的默认值，这样可以实现嵌套表单项的联动更新。
> 
> 希望这个解决方案能够帮助你解决问题。另外，也欢迎你查看 antd-pro 官方文档来更好地理解相关组件的使用方式。

I have solved the problem in other ways

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


Glad to hear that you've solved the problem! If you have any other questions or concerns, feel free to ask. And thank you for your kind words about ChatGPT!
