### ISSUE TITLE
pro-layout，展开某个菜单后，点击收起按钮收起左侧菜单后再次打开左侧菜单原先展开的菜单应该保持展开，现在会关闭🐛[BUG]

### ISSUE THREAD

**Issue by shmily-jianjian** [ant-design/pro-components#6577]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


抱歉，您的问题并未涉及到具体的代码或技术问题，因此无法提供解决方案。请您阅读并遵守如何聪明地提问的指南，在提问时提供详细的信息和代码示例，以便更好地获得帮助。如果您有关于 React 前端问题的具体问题，欢迎重新提问并提供更详细的信息。谢谢！
