### ISSUE TITLE
🐛[BUG] 色弱模式弹出（Popup）菜单底色依旧是白色的

### ISSUE THREAD

**Issue by shanlaomao** [ant-design/pro-components#658]
### 🐛 bug 描述

色弱模式弹出（Popup）菜单底色依旧是白色的

### 📷 复现步骤

1、设置为色弱模式；
2、收起菜单栏，鼠标放在菜单图标上触发弹出菜单。

### 🏞 期望结果

色弱模式下菜单底色与整体颜色契合，暗色背景，亮色文字。

### © 版本信息

- ProComponents 版本: pro-layout: ^6.4.16

**Comment by chenshuai2144** [comment]
antd 默认挂载body，但是色弱挂在了 root上面需要优化一下
