### ISSUE TITLE
🐛[BUG] 首页文档页ProTable样式bug

### ISSUE THREAD

**Issue by luxiangxiong** [ant-design/pro-components#6584]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

首页文档页ProTable Demo无限鬼畜

### 📷 复现步骤

https://procomponents.ant.design/components/table?current=1&pageSize=5#packages-table-src-components-table-demo-menu

### 🏞 期望结果

应该是table尺寸临界值导致的bug

### 💻 复现代码

官方文档页
https://procomponents.ant.design/components/table?current=1&pageSize=5#packages-table-src-components-table-demo-menu

### © 版本信息

无

### 🚑 其他信息

https://user-images.githubusercontent.com/65578067/217745973-84998d1a-d303-4342-a9c7-49baec75004a.mov

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。




感谢反馈问题。这似乎是样式问题导致的bug，ProTable是Ant Design Pro的一部分，可能是样式文件版本的问题。您可以尝试更新相应的依赖包或手动更改样式以解决此问题。

具体可以尝试以下几种方法：

1. 更新依赖包。请在 package.json 文件中找到 @ant-design/pro-table 和 @ant-design/pro-components 的版本号，并尝试将它们升级到最新版本。

2. 手动更改样式。您可以通过在您的项目中使用 CSS 样式表、优先级覆盖或使用 `!important` 关键字来手动更改您的样式。具体实现方法请参考CSS相关文档，可使用调试工具查找哪些样式被应用到了ProTable中。

3. 尝试寻求Antd官方的库维护者询问问题。这种方式可能需要等待一段时间，但他们可能会为您提供更好的解决方案。

希望这些方法可以帮助您解决问题。如果您有任何其他问题，请随时在 GitHub 上开启新的 issue。
