### ISSUE TITLE
🧐[问题] ProTable中 一行包含树形数据+嵌套子表格，如何将 嵌套子表格 显示在 树形数据的下方

### ISSUE THREAD

**Issue by zzlxhczy** [ant-design/pro-components#6585]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
![image](https://user-images.githubusercontent.com/64792675/217757380-3e06252b-6edb-4965-ae50-d29fbc92331f.png)
嵌套子表格默认是在树形数据上方，请问如何才能让嵌套表格显示在树形数据下方呢。
因为嵌套子表格的数据较多，用户需要往下滑很长一部分才能看到树形数据。
或者有没有办法能让嵌套子表格默认不展开，用户点击后再展开。
感谢解答！！

### 💻 示例代码

<ProTable
     expandable={{ childrenColumnName: 'skus', expandedRowRender }}
/>

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


对于ProTable中的嵌套子表格，默认的展示方式是在对应数据的前面展示子表格，可以通过修改ProTable的展开配置实现将子表格展示在对应数据的下方。

可以先将 ProTable 的 `expandable` 配置项改为：

```javascript
<ProTable
  expandable={{
    childrenColumnName: 'skus',
    expandedRowRender,
    expandedRowClassName: 'expanded-row',
    expandRowByClick: true
  }}
/>
```

然后在 CSS 中添加以下样式：

```css
.expanded-row td {
  border: none;
}

.expanded-row .ant-table-cell {
  padding: 0;
}
```

通过添加 `expandedRowClassName` 配置项添加自定义的类名，并在 CSS 中修改该类名下的单元格样式，即可将子表格展示在树形数据的下方。

如果需要将嵌套子表格默认不展开，需要将 `expandRowByClick` 设置为 `false`，同时使用 `defaultExpandAllRows` 或 `defaultExpandedRowKeys` 配置项指定需要展开的行。具体配置可以参考官方文档中的 [展开配置](https://procomponents.ant.design/components/table#%E5%B1%95%E5%BC%80)。
