### ISSUE TITLE
Checkbox.Group childrenRender or every child classname needed

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/pro-components#6587]
### Steps to reproduce

When using ProformCheckbox.group, the classNames of the options cannot be manipulated or a render is required for each children element. Sometimes it may be necessary to interfere with the colors of the checkboxes.

### What is expected?

When using ProformCheckbox.group, the classNames of the options cannot be manipulated or a render is required for each children element. Sometimes it may be necessary to interfere with the colors of the checkboxes.

export interface CheckboxOptionType {
    label: React.ReactNode;
    value: CheckboxValueType;
    style?: React.CSSProperties;
    disabled?: boolean;
    onChange?: (e: CheckboxChangeEvent) => void;
   //className needed
   //render, prop need
}

### What is actually happening?

When using ProformCheckbox.group, the classNames of the options cannot be manipulated or a render is required for each children element. Sometimes it may be necessary to interfere with the colors of the checkboxes.

export interface CheckboxOptionType {
    label: React.ReactNode;
    value: CheckboxValueType;
    style?: React.CSSProperties;
    disabled?: boolean;
    onChange?: (e: CheckboxChangeEvent) => void;
   //className needed
   //render, prop need
}

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 17.0.0 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
Seems you are reporting a bug, then could you please provide a online reproduce to show what is unexpeced?

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


您好，@xXAvoraXx，根据您的描述，似乎您遇到了一个问题，但是缺少在线的重现实例。在没有重现实例的情况下，我们很难定位和解决问题，因此还请提供一个在线的重现实例，以便我们更好地帮助您解决这个问题。您可以通过以下方式创建重现实例：

1. 在 CodeSandbox 上创建一个最小化的可复现示例并分享链接。

   您可以访问 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 或者 [antd@5.x](https://u.ant.design/codesandbox-repro) 提供的在线实例，创建一个最简单的复现 Bug 实例，并分享该项目的链接。

2. 上传一个包含最简化步骤的代码仓库。

   如果您的问题不适合在 CodeSandbox 上重现，或者您需要使用 git 等工具进行版本控制，则您可以创建一个包含最小化步骤的代码仓库，并且在 issue 中分享该仓库的链接。

    请注意，如果您未在 issue 中提供可重现的代码或信息，我们将无法帮助您解决问题，该 issue 也可能会被关闭，希望您配合，谢谢！

**Comment by xXAvoraXx** [comment]
> 
I want to change the styles of some options in the checkBoxGroupValues array. I can't give styled-components values because there is no ClassName or rendering property. I don't want to change the color of all of them, I want to change the color of some of them.

我想更改 checkBoxGroupValues 数组中某些选项的样式。 我不能给 styled-components 值，因为没有 ClassName 或渲染功能。 我不想改变所有的颜色，我想改变其中一些的颜色。

https://codesandbox.io/s/antd-reproduction-template-forked-bygd8y

**Comment by chenshuai2144** [comment]
"Label" 可以是 React 节点，您只需要直接设置标签即可。

**Comment by xXAvoraXx** [comment]
Not work. @chenshuai2144 
![image](https://user-images.githubusercontent.com/6988989/224303394-096364fc-f110-4558-b917-b26c59a88a5b.png)
