### ISSUE TITLE
🐛[BUG] 文档更新后 ProDescriptions 页面丢失

### ISSUE THREAD

**Issue by xingming2020** [ant-design/pro-components#6590]
### 🐛 bug 描述

https://procomponents.ant.design/components/description

多说一句，文档更新是好事，可是旧版的文档不能保留一个入口吗？

### 🚑 其他信息

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67719106/218030922-283a96c0-a4d2-4db4-a53c-ba09f9c562fb.png">

**Comment by chenshuai2144** [comment]
修复了。


只是换了个主题，不要担心
