### ISSUE TITLE
🐛[问题] 导入 @ant-design/pro-components TypeScript 报错无解

### ISSUE THREAD

**Issue by drizzlesconsin** [ant-design/pro-components#6592]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤

<img width="695" alt="image" src="https://user-images.githubusercontent.com/69514654/218176509-65686730-3d6e-4e5f-8398-73371cba34ac.png">
升级后，报错。

```ts
文件名“xxxxxx/node_modules/@ant-design/pro-components/es/index.d.ts”仅在大小写方面与包含的文件名“xxxxxx/node_modules/@ant-design/pro-components/es/index.d.ts”不同。
  程序包含该文件是因为:
    通过 "xxxxxx/node_modules/@ant-design/pro-components" 从具有 packageId "@ant-design/pro-components/es/index.d.ts@2.3.54" 的文件 "xxxxxx/src/.umi/plugin-layout/types.d.ts" 引用了库类型
```

已重装过

### © 版本信息

- ProComponents 版本: 2.3.54
- @umijs/max: 4.0.51
- antd: 4.24.7
- typescript: 4.9.5
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://unpkg.com/browse/@ant-design/pro-components@2.3.54/


目测是安装依赖出问题了，`git clean -dfx` 删除一下重新安装

**Comment by 985563349** [comment]
> https://unpkg.com/browse/@ant-design/pro-components@2.3.54/
> 
> 目标是安装依赖出题了，`git clean -dfx`删除一下重新安装

已按步骤进行操作，但问题仍然存在。

**Comment by chenshuai2144** [comment]
打开这个路径看看为啥有大小写的问题 是不是你的项目名重复了

**Comment by drizzlesconsin** [comment]
> 原来不只我遇到这个问题。

```ts
"/xxxxxxx/src/.umi/plugin-layout/types.d.ts" 引用了库类型
```
```ts
// src/.umi/plugin-layout/types.d.ts
/// <reference types="/xxxxxxx/node_modules/@ant-design/pro-components" />
```

往次都是删掉 node_modules 重装就行。这次实在是没看出是哪的问题。@chenshuai2144

**Comment by hxuelun** [comment]
最后怎么解决了？我也出现了这个问题

**Comment by 985563349** [comment]
> 打开这个路径看看为啥有大小写的问题 是不是你的项目名重复了

项目并没有重名。最后pro-compoents版本回滚到2.3.37后错误消失了😢

**Comment by hxuelun** [comment]
> > 打开这条路看看为啥有大小写的问题是不是你的项目名称重新了
> 
> 项目并没有重名。最后pro-components版本返回滚到2.3.37后错误消失了😢

我把pro-components版本返回滚到2.3.37也还是存在这个问题😢

**Comment by SilkageNet** [comment]
是否有新的解决方案呢？升级了哪个已修复的版本呢？

**Comment by chongyi** [comment]
问题依然存在，有无解决办法，前面的方案都不行

**Comment by yang-xianzhu** [comment]
应该是项目名有中文问题。

**Comment by kateli** [comment]
今天也遇到了这样的问题  最后找到了解决方法
产生原因：
vscode升级后，本地的ts版本和项目的ts版本不一致导致
解决方法：
vscode里面 按住 Ctrl + Shift + P ---->  选择typescript版本 ----> 选择使用工作区版本
![image](https://user-images.githubusercontent.com/8436428/230821454-f785e922-49f7-4980-a053-61bf6119ea21.png)
![image](https://user-images.githubusercontent.com/8436428/230821508-5752a019-4c81-4ea5-a520-babba14b3218.png)

**Comment by Locter9001** [comment]
> 今天也遇到了这样的问题 最后找到了解决方法 产生原因： vscode升级后，本地的ts版本和项目的ts版本不一致导致 解决方法： vscode里面 按住 Ctrl + Shift + P ----> 选择typescript版本 ----> 选择使用工作区版本 ![image](https://user-images.githubusercontent.com/8436428/230821454-f785e922-49f7-4980-a053-61bf6119ea21.png) ![image](https://user-images.githubusercontent.com/8436428/230821749-8e6e0626-a729-4a52-b14b-3c6ec8e76e6c.png)

问题解决，感谢大佬

**Comment by RogerPeng123** [comment]
> 今天也遇到了这样的问题 最后找到了解决方法 产生原因： vscode升级后，本地的ts版本和项目的ts版本不一致导致 解决方法： vscode里面 按住 Ctrl + Shift + P ----> 选择typescript版本 ----> 选择使用工作区版本 ![image](https://user-images.githubusercontent.com/8436428/230821454-f785e922-49f7-4980-a053-61bf6119ea21.png) ![image](https://user-images.githubusercontent.com/8436428/230821749-8e6e0626-a729-4a52-b14b-3c6ec8e76e6c.png)

感谢大佬，问题解决了

**Comment by KunioHaha** [comment]
我的项目因为外部目录有大写字母，导致vscode飘红，但并不影响使用，tsconfig加入下面配置解决红字问题
"compilerOptions": {
    "forceConsistentCasingInFileNames": true
  }

**Comment by g1091541365** [comment]
typescriptv5.0.3的版本下仍有该问题

**Comment by xjiejie97** [comment]
ts版本4.9.5，使用该方法已解决。感谢大佬

**Comment by Jingws** [comment]
> 
感谢，还是强制禁止改检查来的靠谱

**Comment by Er-XiaoQi** [comment]
> 今天也遇到了这样的问题 最后找到了解决方法 产生原因： vscode升级后，本地的ts版本和项目的ts版本不一致导致 解决方法： vscode里面 按住 Ctrl + Shift + P ----> 选择typescript版本 ----> 选择使用工作区版本 ![image](https://user-images.githubusercontent.com/8436428/230821454-f785e922-49f7-4980-a053-61bf6119ea21.png) ![image](https://user-images.githubusercontent.com/8436428/230821749-8e6e0626-a729-4a52-b14b-3c6ec8e76e6c.png)

解决了我的问题，谢谢

**Comment by Xiakeming97** [comment]
问题解决了，感谢🙏

**Comment by Sallyfafafa** [comment]
> 今天也遇到了这样的问题 最后找到了解决方法 产生原因： vscode升级后，本地的ts版本和项目的ts版本不一致导致 解决方法： vscode里面 按住 Ctrl + Shift + P ----> 选择typescript版本 ----> 选择使用工作区版本 ![image](https://user-images.githubusercontent.com/8436428/230821454-f785e922-49f7-4980-a053-61bf6119ea21.png) ![image](https://user-images.githubusercontent.com/8436428/230821749-8e6e0626-a729-4a52-b14b-3c6ec8e76e6c.png)

谢谢老板，问题解决🙏

**Comment by nasa1024** [comment]
出现相同问题，已经按照大佬方式解决

**Comment by mjkohoh** [comment]
> 今天也遇到了这样的问题 最后找到了解决方法 产生原因： vscode升级后，本地的ts版本和项目的ts版本不一致导致 解决方法： vscode里面 按住 Ctrl + Shift + P ----> 选择typescript版本 ----> 选择使用工作区版本 ![image](https://user-images.githubusercontent.com/8436428/230821454-f785e922-49f7-4980-a053-61bf6119ea21.png) ![image](https://user-images.githubusercontent.com/8436428/230821749-8e6e0626-a729-4a52-b14b-3c6ec8e76e6c.png)

实测有用，跪谢。

**Comment by yunstv** [comment]
如果选择为工作区间版本还报红,那么在试一试改下tsconfig,中forceConsistentCasingInFileNames项为false再看看
![image](https://github.com/ant-design/pro-components/assets/17945292/8285c5c5-21e7-42f9-9dd9-d4bd78e45201)
![image](https://github.com/ant-design/pro-components/assets/17945292/272c2c14-49ce-4023-b5c5-dc94362a74e1)

**Comment by 5201314999** [comment]
> 我的项目因为外部目录有大写字母，导致vscode飘红，但并不影响使用，tsconfig加入下面配置解决红字问题 "compilerOptions": { "forceConsistentCasingInFileNames": false }

你这种强行关闭不太好吧，太暴力了

**Comment by 5201314999** [comment]
> > 今天也遇到了这样的问题 最后找到了解决方法 产生原因： vscode升级后，本地的ts版本和项目的ts版本不一致导致 解决方法： vscode里面 按住 Ctrl + Shift + P ----> 选择typescript版本 ----> 选择使用工作区版本 ![image](https://user-images.githubusercontent.com/8436428/230821454-f785e922-49f7-4980-a053-61bf6119ea21.png) ![image](https://user-images.githubusercontent.com/8436428/230821749-8e6e0626-a729-4a52-b14b-3c6ec8e76e6c.png)
> 
> 解决了我的问题，谢谢

我的不行。。。

**Comment by 5201314999** [comment]
这个飘红只在yarn 安装依赖才有，换成pnpm 就不会，不过pnpm 下又会引入其他一些问题。官方是否可以支持梳理定位下原因，解释下

**Comment by 662** [comment]
npm下仍然存在该问题，ts 5.2.2

**Comment by linzchan** [comment]
通过设置typescript的工作区版本的确是可以生效，不过如果本地安装了。Typescript Vue Plugin(Volar)的话，需要配置工作区禁用
<img width="617" alt="image" src="https://github.com/ant-design/pro-components/assets/7448035/c4f5912b-29cb-475b-a441-0dd4d5a07afd">

**Comment by CYLee2020** [comment]
使用umijs构建的,可以尝试在.umirc.ts或config.ts中增加
`{npmClient: 'npm'}`

**Comment by study366** [comment]
![image](https://github.com/ant-design/pro-components/assets/39559336/eea153ae-68f3-48aa-8301-c4a33f2c7bd0)
ts: 5.4.5 关闭 vs code 这个设置后生效
