### ISSUE TITLE
👑 [需求]对antd pro v6 正式版预览的小小建议

### ISSUE THREAD

**Issue by tnngo** [ant-design/pro-components#6593]
### 🔩 所属模块或组件

不是ProComponents中的模块或组件，而是https://procomponents.ant.design 首页效果

### 🥰 需求描述

希望能将https://procomponents.ant.design 网站的部分效果集成到antd pro 预览中，比如背景的动态效果加入到登录页面中，右上角的主题切换集成到antd pro 登录后内部的右上角，和头像位置并列。

### ⛰ 功能需求适用场景

只是对antd pro v6 正式版预览的小小建议。

### 🧐 解决方案

无

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


非常感谢您对Ant Design Pro的关注和热情反馈！

关于您提出的建议，感谢您的宝贵意见，我们会在设计和开发中考虑这部分的优化，并尽可能实现您的建议。但目前Ant Design Pro的预览版本仅为测试版，难免存在各种不足和问题，我们期待您的持续关注和反馈。

另外，我们建议您参考Ant Design Pro官方文档以及其提供的组件库来构建自己的应用。如果您需要帮助或有问题，请随时在Ant Design的GitHub上创建一个issue来寻求帮助，我们的社区和开发者们将竭诚为您服务！
