### ISSUE TITLE
🐛[BUG] Failed to switch theme using vitejs

### ISSUE THREAD

**Issue by andersonrochas** [ant-design/pro-components#6594]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
Theme switching fails from the third switch when using StrictMode with the vitejs and Layout pro components. In the demo, if you perform the theme switch 3x, you will see that from the third attempt, the theme does not switch anymore, if you remove StrictMode from React, the switch occurs fluidly.

### 📷 复现步骤
Just click on the icon to change to Dark, then to Light, and finally to Dark again.
![image](https://user-images.githubusercontent.com/121313313/218284217-35e4004d-2a60-4342-ab25-07b13263ce46.png)

### 🏞 期望结果
![image](https://user-images.githubusercontent.com/121313313/218284268-5a572036-1946-49e1-899b-6c2e5f476cc4.png)

### 💻 复现代码
https://stackblitz.com/edit/vitejs-vite-th7stb

### © 版本信息

- ProComponents 版本: 2.3.54
- vitejs 版本: 4.1.1
- antd: 5.2.0
- React: 18.2.0
- 开发环境: Windows 11

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


根据您提供的信息，这可能是一个与 React 18 中 StrictMode 有关的问题。您可以尝试更新到最新版本的 React（目前是18.2.0）以解决此问题。

同时，也可以尝试使用 `React.unstable_useTransistioin` 函数来获取更多的跟踪信息，以便更好地找出问题所在：

```jsx
import { useTransition } from 'react';

const animation = {
  from: { opacity: 0 },
  enter: { opacity: 1 },
  leave: { opacity: 0 },
};

function App() {
  const [theme, setTheme] = useState('light');

  const transitions = useTransition(theme, {
    ...animation,
    config: { duration: 200 },
  });

  const changeTheme = () => {
    setTheme((prevTheme) => (prevTheme === 'light' ? 'dark' : 'light'));
  };

  return (
    <div>
      <h1>Hello React</h1>

      {transitions((style, item) => (
        <div style={{ ...style }}>
          <MyLayout style={{ ...style }} theme={item} />
        </div>
      ))}

      <button onClick={changeTheme}>Toggle Theme</button>
    </div>
  );
}
```

这里使用了 `useTransition` 函数，它支持 `Spring` 风格的动画，可以帮助您在切换过程中进行更细致的控制和调试。

对于 Layout Pro 的使用，您也可以尝试参考官方文档，了解更多的使用技巧和最佳实践：

- 官方文档：https://procomponents.ant.design/components/layout-cn/

**Comment by andersonrochas** [comment]
>

**Comment by andersonrochas** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。
> 
> 根据您提供的信息，这可能是一个与 React 18 中 StrictMode 有关的问题。您可以尝试更新到最新版本的 React（目前是18.2.0）以解决此问题。
> 
> 同时，也可以尝试使用 `React.unstable_useTransistioin` 函数来获取更多的跟踪信息，以便更好地找出问题所在：
> 
> ```js
> import { useTransition } from 'react';
> 
> const animation = {
>   from: { opacity: 0 },
>   enter: { opacity: 1 },
>   leave: { opacity: 0 },
> };
> 
> function App() {
>   const [theme, setTheme] = useState('light');
> 
>   const transitions = useTransition(theme, {
>     ...animation,
>     config: { duration: 200 },
>   });
> 
>   const changeTheme = () => {
>     setTheme((prevTheme) => (prevTheme === 'light' ? 'dark' : 'light'));
>   };
> 
>   return (
>     <div>
>       <h1>Hello React</h1>
> 
>       {transitions((style, item) => (
>         <div style={{ ...style }}>
>           <MyLayout style={{ ...style }} theme={item} />
>         </div>
>       ))}
> 
>       <button onClick={changeTheme}>Toggle Theme</button>
>     </div>
>   );
> }
> ```
> 
> 这里使用了 `useTransition` 函数，它支持 `Spring` 风格的动画，可以帮助您在切换过程中进行更细致的控制和调试。
> 
> 对于 Layout Pro 的使用，您也可以尝试参考官方文档，了解更多的使用技巧和最佳实践：
> 
> * 官方文档：https://procomponents.ant.design/components/layout-cn/

Hello, I tried it your way and I tried using ChatGPT too, using transitions there was no effect, already using the AI ​​suggestion (Add the key property passing the theme value), it worked perfectly. I've updated the example with the suggestion: https://stackblitz.com/edit/vitejs-vite-qlm1xy
