### ISSUE TITLE
🐛[BUG]ProFormList 组件无法通过actionRef获取某一行数据

### ISSUE THREAD

**Issue by 2018Cool** [ant-design/pro-components#6599]
### 🐛 bug 描述
ProFormList 组件无法通过actionRef获取某一行数据和formlist中的所有数据
const row = actionRef.current?.get(1); // 返回的是undefined

### 💻 复现代码
https://codesandbox.io/s/rzvhik

### © 版本信息

- ProComponents 版本: [2.3.54]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by 2018Cool** [comment]
加上了也不行

**Comment by flyingmylo** [comment]
> 

示例中加上了是可以的，可能你逻辑里写的有问题吧。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


根据你提供的信息，发现你使用的是 ProFormList 的 actionRef 功能无法获取到某一行和获取所有数据。

通过查阅 ProFormList 的文档，发现在早期的版本有个 issue 关于无法得到 FormInstance 案例(https://github.com/ant-design/pro-components/issues/1473)。在最新的 2.3.54 版本已经修复。

因此建议你先更新 ProComponents 的版本，如果仍有问题可以提供更多细节，以便我能够更好的帮助你。同时，可以参考官方文档对 ProFormList 的讲解(https://procomponents.ant.design/components/form-list-cn/)。

另外，在你的代码实现的时候，建议对 list 和 ref 进行遍历以及优先绑定 actionRef 以便调用组件内部的方法。

```jsx
import React, { useRef } from 'react';
import ProForm, {
  ProFormList,
  ProFormText,
  ProFormDatePicker,
  ProFormDateTimePicker,
} from '@ant-design/pro-form';

const handleAdd = (values, ref) => {
  console.log('handleAdd call');
  console.log(values);
  console.log(ref.current.getFieldValue());
};

const Page: React.FC = () => {
  const actionRef = useRef();

  return (
    <div>
      <ProForm initialValues={{ users: [{ name: 'cjf', sex: 'male' }] }}>
        <ProFormList
          name="users"
          label="用户信息"
          rules={[{ required: true, message: '请输入至少一个用户信息' }]}
          key="UserList"
          actionRef={actionRef}
        >
          {(fields, { add, remove }, { list }) => {
            console.log(11111); // 此处应该输出两次，分别是第一次渲染和添加一行记录的之后触发。
            console.log(actionRef.current); // 此处应该可以输出非空的值
          return (
            <>
              {fields.map((field, index) => (
                <div style={{ display: 'flex', marginBottom: 8 }} key={field.key}>
                  <ProFormText
                    // 你的实现可能还需要根据表单值的实时变化去修改某个 field 的值，这种情况下可以在这里通过 setFieldValue 更新值
                    width="md"
                    name={[field.name, 'name']}
                    fieldKey={[field.fieldKey, 'name']}
                    label={`用户 ${index + 1} 姓名`}
                    placeholder="请输入"
                    rules={[{ required: true, message: '请输入用户姓名' }]}
                  />
                  <ProFormDatePicker
                    width="md"
                    name={[field.name, 'birth']}
                    label="生日"
                    fieldKey={[field.fieldKey, 'birth']}
                    rules={[{ required: true, message: '请选择用户生日' }]}
                  />
                  <ProFormDateTimePicker
                    width="md"
                    name={[field.name, 'time']}
                    label="时间"
                    fieldKey={[field.fieldKey, 'time']}
                  />
                  <div style={{ marginLeft: 8 }}>
                    <a key={`${field.name}_${field.key}_remove`} onClick={() => remove(field.name)}>
                      删除
                    </a>
                  </div>
                </div>
              ))}
              <div
                style={{
                  display: 'flex',
                  justifyContent: 'center',
                }}
              >
                <a onClick={() => {add(); handleAdd(list, actionRef)}}>添加用户</a>
              </div>
            </>
          );
        }}
        </ProFormList>
      </ProForm>
    </div>
  );
};

export default Page;

```

**Comment by tsuyoii** [comment]
> ```js
> const actionRef = useRef();
> ```
报错啦哥
<img width="619" alt="image" src="https://user-images.githubusercontent.com/49632080/233245571-76b166f3-e7e9-4958-b063-43e9c2cc2b54.png">

**Comment by tsuyoii** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。
> 
> 根据你提供的信息，发现你使用的是 ProFormList 的 actionRef 功能无法获取到某一行和获取所有数据。
> 
> 通过查阅 ProFormList 的文档，发现在早期的版本有个 issue 关于无法得到 FormInstance 案例([https://github.com/ant-design/pro-components/issues/1473)。在最新的](https://github.com/ant-design/pro-components/issues/1473)%E3%80%82%E5%9C%A8%E6%9C%80%E6%96%B0%E7%9A%84) 2.3.54 版本已经修复。
> 
> 因此建议你先更新 ProComponents 的版本，如果仍有问题可以提供更多细节，以便我能够更好的帮助你。同时，可以参考官方文档对 ProFormList 的讲解([https://procomponents.ant.design/components/form-list-cn/)。](https://procomponents.ant.design/components/form-list-cn/)%E3%80%82)
> 
> 另外，在你的代码实现的时候，建议对 list 和 ref 进行遍历以及优先绑定 actionRef 以便调用组件内部的方法。
> 
> ```js
> import React, { useRef } from 'react';
> import ProForm, {
>   ProFormList,
>   ProFormText,
>   ProFormDatePicker,
>   ProFormDateTimePicker,
> } from '@ant-design/pro-form';
> 
> const handleAdd = (values, ref) => {
>   console.log('handleAdd call');
>   console.log(values);
>   console.log(ref.current.getFieldValue());
> };
> 
> const Page: React.FC = () => {
>   const actionRef = useRef();
> 
>   return (
>     <div>
>       <ProForm initialValues={{ users: [{ name: 'cjf', sex: 'male' }] }}>
>         <ProFormList
>           name="users"
>           label="用户信息"
>           rules={[{ required: true, message: '请输入至少一个用户信息' }]}
>           key="UserList"
>           actionRef={actionRef}
>         >
>           {(fields, { add, remove }, { list }) => {
>             console.log(11111); // 此处应该输出两次，分别是第一次渲染和添加一行记录的之后触发。
>             console.log(actionRef.current); // 此处应该可以输出非空的值
>           return (
>             <>
>               {fields.map((field, index) => (
>                 <div style={{ display: 'flex', marginBottom: 8 }} key={field.key}>
>                   <ProFormText
>                     // 你的实现可能还需要根据表单值的实时变化去修改某个 field 的值，这种情况下可以在这里通过 setFieldValue 更新值
>                     width="md"
>                     name={[field.name, 'name']}
>                     fieldKey={[field.fieldKey, 'name']}
>                     label={`用户 ${index + 1} 姓名`}
>                     placeholder="请输入"
>                     rules={[{ required: true, message: '请输入用户姓名' }]}
>                   />
>                   <ProFormDatePicker
>                     width="md"
>                     name={[field.name, 'birth']}
>                     label="生日"
>                     fieldKey={[field.fieldKey, 'birth']}
>                     rules={[{ required: true, message: '请选择用户生日' }]}
>                   />
>                   <ProFormDateTimePicker
>                     width="md"
>                     name={[field.name, 'time']}
>                     label="时间"
>                     fieldKey={[field.fieldKey, 'time']}
>                   />
>                   <div style={{ marginLeft: 8 }}>
>                     <a key={`${field.name}_${field.key}_remove`} onClick={() => remove(field.name)}>
>                       删除
>                     </a>
>                   </div>
>                 </div>
>               ))}
>               <div
>                 style={{
>                   display: 'flex',
>                   justifyContent: 'center',
>                 }}
>               >
>                 <a onClick={() => {add(); handleAdd(list, actionRef)}}>添加用户</a>
>               </div>
>             </>
>           );
>         }}
>         </ProFormList>
>       </ProForm>
>     </div>
>   );
> };
> 
> export default Page;
> ```
报错啦哥
<img width="612" alt="image" src="https://user-images.githubusercontent.com/49632080/233245735-16c476a5-f362-4838-912d-f8c8920d0781.png">
