### ISSUE TITLE
🐛[BUG] ProForm 中添加回车事件时触发两次

### ISSUE THREAD

**Issue by flyingmylo** [ant-design/pro-components#6601]
### 🐛 bug 描述
在 `ProForm` 中配置 `submitter` 属性，为了可以支持回车事件，添加 `submitButtonProps: {htmlType: 'submit'}` 配置，但是回车事件被触发了两次。

### 📷 复现步骤

`ProForm` 中配置 `submitButtonProps: {htmlType: 'submit'}` 时的回车事件被触发了两次。

### 🏞 期望结果

回车事件触发一次

### 💻 复现代码

https://codesandbox.io/s/ji-ben-shi-yong-forked-5417hw?file=/App.tsx

### © 版本信息

- ProComponents 版本: @ant-design/pro-components 2.3.54
- umi 版本："umi": "3.5.8"
- 浏览器环境：Chrome Version 109.0.5414.119 (Official Build) (arm64)
- 开发环境：mac OS Monterey 12.2.1

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/22828986/218429074-11720dad-f266-4f5c-82c1-000afc7f8b6f.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


### 🌈 解决方案

我们知道，事件冒泡是指某个节点触发某个事件时，该事件会从该节点开始向上冒泡到祖先节点。由于该问题是触发了两次点击事件，我们可以避免使用冒泡事件，而改用 `onClick` 事件。在 `submitButtonProps` 中设置 `onClick={handleSubmit}`，`handleSubmit` 在该示例代码中是表单提交的回调函数。这里提供一个示例代码，建议进行测试。

```tsx
<ProForm
  submitter={{
    submitButtonProps: {
      htmlType: 'button',
      onClick: handleSubmit // 使用 onClick 事件
    }
  }}
>
  {/* 表单项 */}
</ProForm>
``` 

### 📚 文档资料

Ant Design Pro 官方文档：[ProForm 表单](https://procomponents.ant.design/components/form#%e7%99%bb%e5%bd%95%e8%a1%a8%e5%8d%95)

**Comment by flyingmylo** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。
> 
> ### 🌈 解决方案
> 我们知道，事件冒泡是指某个节点触发某个事件时，该事件会从该节点开始向上冒泡到祖先节点。由于该问题是触发了两次点击事件，我们可以避免使用冒泡事件，而改用 `onClick` 事件。在 `submitButtonProps` 中设置 `onClick={handleSubmit}`，`handleSubmit` 在该示例代码中是表单提交的回调函数。这里提供一个示例代码，建议进行测试。
> 
> ```tsx
> <ProForm
>   submitter={{
>     submitButtonProps: {
>       htmlType: 'button',
>       onClick: handleSubmit // 使用 onClick 事件
>     }
>   }}
> >
>   {/* 表单项 */}
> </ProForm>
> ```
> 
> ### 📚 文档资料
> Ant Design Pro 官方文档：[ProForm 表单](https://procomponents.ant.design/components/form#%e7%99%bb%e5%bd%95%e8%a1%a8%e5%8d%95)

测试了一下，`htmlType` 改为 `submit` 时生效。
```
submitButtonProps: {
    htmlType: 'submit',
    onClick: handleSubmit // 使用 onClick 事件
  }
```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常感谢您的补充和纠正，确实是我所疏漏的点。在修改表单类型为 `submit` 时，我们可以直接使用 `htmlType: 'submit'` 替换之前的 `htmlType: 'button'`，这样可以直接触发表单的默认提交事件。非常抱歉因我原本的方案给您带来的困惑。
