### ISSUE TITLE
🧐[问题]ProTable设置栏的列筛选可以加搜索吗？表格的列非常多，急急急，有大佬看下吗

### ISSUE THREAD

**Issue by wujunhong2000** [ant-design/pro-components#6602]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
<img width="755" alt="屏幕截图_20230213_224525" src="https://user-images.githubusercontent.com/45730064/218490004-6b8915d6-339d-4c57-9688-10064781f81c.png">

ProTable设置栏的列筛选可以加搜索吗？表格的列非常多，急急急，有大佬看下吗

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好，可以使用 ProTable 的搜索功能来实现对列筛选的搜索。

首先需要在 ProTable 组件的 columns 中对需要搜索的列进行配置，例如：

```jsx
import { ProTable, SelectColumns } from '@ant-design/pro-table';

const columns = [
  {
    title: '姓名',
    dataIndex: 'name',
    // 配置需要搜索的列
    search: true,
  },
  {
    title: '年龄',
    dataIndex: 'age',
    // 配置需要搜索的列
    search: true,
  },
  {
    title: '性别',
    dataIndex: 'gender', 
    // 不需要搜索的列不配置 search 属性
  },
];

// 这里假设 dataSource 已经准备好了
const dataSource = [...];

function MyTable() {
  return (
    <ProTable dataSource={dataSource} columns={columns} />
  );
}
```

然后在 ProTable 中使用 `search` 属性来开启搜索框，例如：

```jsx
function MyTable() {
  return (
    <ProTable dataSource={dataSource} columns={columns} search={{}} />
  );
}
```

此时会显示一个搜索框，输入关键字后会自动筛选出包含关键字的数据。

你可以在 `search` 属性中设置更多的配置项，例如：

```jsx
function MyTable() {
  return (
    <ProTable 
      dataSource={dataSource} 
      columns={columns} 
      search={{
        placeholder: '请输入关键字',
        // 设置输入框名称
        name: 'search',
        // 设置搜索 debounce 时间
        debounceInterval: 500,
        // 自定义搜索函数
        onSearch: async (value) => {
          // 使用自定义搜索函数实现更多的搜索逻辑
        }
      }} 
    />
  );
}
```

更多的文档可以参考 ProTable 官方文档：https://protable.ant.design/table/search。

**Comment by chenshuai2144** [comment]
不支持的，有兴趣来搞个pr吧。

**Comment by souldjl** [comment]
如何拿到整个表格search 或者filter 之后的数据呢
