### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by MrsHuiL** [ant-design/pro-components#6605]
### 🧐 问题描述

ProTable组件的列设置属性columnsState，该属性的onChange事件的回调，返回的data，有时候只有当前设置的列对象（图二），有时候返回所有列对象（图一）。总结发现，当点击【重置】之后，再去进行隐藏（或固定列）操作，返回的data只有当前设置的列对象，不是所有的列对象；页面刷新，只要没有点【重置】的时候，返回的都是所有列对象，请问这是bug吗？就不能给一致的吗，这样让我们很难处理

### 💻 示例代码

 columnsState={{
          value: columnsStateMap,
          onChange: (data) => onChangeColumnsState(data),
 }}

### 🚑 其他信息

图一：
![image](https://user-images.githubusercontent.com/92795771/218686091-80aef808-b94c-4250-9693-da4a1f4b9c6f.png)
图二：
![image](https://user-images.githubusercontent.com/92795771/218686143-8e417ecb-9fb4-4a4c-a6a7-0879faeb77d3.png)

**Comment by zhengguodong** [comment]
使用defaultValue时，重置时会帮我恢复成默认的列表展示，change事件返回的也是{}，符合我的预期；当我使用value时，重置时change事件会给我返回当前的显示的对象，不会帮我恢复成默认的列表展示，达不到重置的效果，不符合我的预期。使用value的时候，重置的问题要怎么解决
