### ISSUE TITLE
🐛[BUG] EditableProTable不能正确的改变pageSize

### ISSUE THREAD

**Issue by zlllya** [ant-design/pro-components#6607]
### 🐛 bug 描述

EditableProTable改变pageSize没有达到预期效果

### 📷 复现步骤

点击分页切换pageSize

### 💻 复现代码

[codesandbox](https://codesandbox.io/s/antd-reproduction-template-forked-fryz2v?file=/index.js)

### © 版本信息

- ProComponents 版本: [e.g. 2.3.54]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lyndonliu89757** [comment]
pagination 的 pageSize改为 defaultPageSize。
你使用了pageSize，相当于自己用state来控制。

**Comment by zlllya** [comment]
> pagination 的 pageSize 改为 defaultPageSize。 你使用了 pageSize，相对当自己使用状态来控制。

感谢，是我的疏忽

**Comment by peter064226** [comment]
刚好解决了我这个问题，感觉所有人
