### ISSUE TITLE
👑 [需求] ProTable不在第一页时删除当前唯一数据后表格为空问题

### ISSUE THREAD

**Issue by zzz111** [ant-design/pro-components#661]
### 🥰 需求描述

![image](https://user-images.githubusercontent.com/23628650/95567875-1c1c1600-0a56-11eb-8a1d-b752c20d4127.png)

第二页只有一条数据，删除之后第二页为空，但是分页显示“第 11-10 条/总共 10 [条”，页码也只有1，这里会有歧义

### 🧐 解决方案
删除之后如果为空，且页码不为1，建议跳转到第一页

**Comment by opamine** [comment]
这个问题我从来都是自己从代码里判断

**Comment by chenshuai2144** [comment]
试了一下框架做这个事情有点危险
