### ISSUE TITLE
🐛[BUG] proTable 重置，自定义组件值联动有问题

### ISSUE THREAD

**Issue by Sundayuu** [ant-design/pro-components#6613]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


很抱歉，你的问题描述还不够清晰。请提供更多相关信息，以便我们更好地理解问题。同时，请注意问题描述中的格式和语法，避免让别人阅读时出现困难。感谢配合！
