### ISSUE TITLE
🐛[BUG]valueType为textarea时文字展示未对齐

### ISSUE THREAD

**Issue by helloJincheng** [ant-design/pro-components#6618]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

valueType为textarea时未对齐
[#6524](https://github.com/ant-design/pro-components/pull/6524)的提交造成

![image](https://user-images.githubusercontent.com/27672145/219252911-90158023-2c92-47f8-b105-8dba6c99df3a.png)

### © 版本信息

- ProComponents 版本: [2.3.54]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


根据给出的信息，初步判断这是一个样式问题。可能是因为样式被覆盖或者针对不准确导致的。可以尝试通过以下步骤解决：

1. 确认是否有在项目中自定义过相关样式，如果有可能会导致样式冲突，需要进行排查和调整。

2. 确认是否有在使用该组件时修改过props或者样式，比如其他的父组件改变了组件的CSS类或者样式属性，需要定位出问题所在并进行调整。

3. 如果还是无法解决，可以尝试在组件外层嵌套一个div，并设置该div的样式属性text-align:center，从而达到垂直居中的效果。

最后，可以查看该组件的官方文档，是否提供了相应的样式属性或者方法进行调整。如果都无法解决，建议到组件仓库中提出具体的bug并提供复现步骤和环境信息。

**Comment by chenshuai2144** [comment]
有兴趣来个pr吗？
