### ISSUE TITLE
🧐[问题]ProTable里搜索表单中Select，如何在使用request请求远程数据的时候自定义渲染选项，比如加个图标

### ISSUE THREAD

**Issue by zmm2tysu** [ant-design/pro-components#6620]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

ProTable里搜索表单中Select，如何在使用request请求远程数据的时候自定义渲染选项，比如加个图标

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


在使用 `ProTable` 的搜索表单中的 `Select` 控件时，如果想要自定义渲染选项中的图标，可以使用 `ProTable` 提供的 `optionsRender` 属性进行自定义处理。

具体做法如下：

1. 在 `columns` 中定义 `Select` 控件，可以使用 `valueEnum` 指定选项列表。例如：

```javascript
const columns = [
  {
    title: 'Select',
    dataIndex: 'select',
    valueType: 'select',
    valueEnum: {
      1: { text: '选项一' },
      2: { text: '选项二' },
      3: { text: '选项三' },
    }
  }
]
```

2. 在 `ProTable` 组件中使用 `optionsRender` 属性对选项进行自定义渲染，可以使用 `option.key` 获取选项的值，使用 `option.value` 获取选项的文本值。例如：

```javascript
import { Table, Select } from 'antd';
import { ProTable } from '@ant-design/pro-table';

const MySelect = ({ option }) => {
  return (
    <span>
      {option.key === '1' ? <span style={{ marginRight: 8 }}>🍎</span> : null}
      {option.key === '2' ? <span style={{ marginRight: 8 }}>🍊</span> : null}
      {option.value}
    </span>
  );
};

const columns = [
  {
    title: 'Select',
    dataIndex: 'select',
    valueType: 'select',
    valueEnum: {
      1: { text: '选项一' },
      2: { text: '选项二' },
      3: { text: '选项三' },
    }
  },
];

const MockData = [
  { id: 1, select: 1 },
  { id: 2, select: 2 },
  { id: 3, select: 3 }
];

const remoteRequest = async () => {
  return {
    data: MockData,
    success: true,
  }
}

const TestComponent = () => {
  return (
    <ProTable
      columns={columns}
      request={remoteRequest}
      optionsRender={(option) => <MySelect option={option} />}
      rowKey="id"
      search={false}
    />
  )
}

ReactDOM.render(<TestComponent />, mountNode);
```

在上面的例子中，我们定义了一个自定义组件 `MySelect`，通过 `option.key` 判断当前选项的值，然后向选项前添加一个图标。使用 `optionsRender` 属性将自定义组件传递给 `ProTable`，完成自定义渲染。

参考文档：

- [Ant Design ProTable 中的自定义 Select 选项渲染](https://www.yuque.com/docs/share/f2d37f1d-3c27-43e8-8dc0-7dbe325f9540?# 《Ant Design ProTable 中的自定义 Select 选项渲染》)

**Comment by chenshuai2144** [comment]
暂时不支持，默认有个loading 已经够用了。没必要玩的太花，在这种细节上下功夫不如多写几个table
