### ISSUE TITLE
🧐[问题]  官方文档上的很多demo链接如codesandbox或者stackblitz打开都运行失败

### ISSUE THREAD

**Issue by earthaYan** [ant-design/pro-components#6626]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
demo链接打开之后报错，无法成功展示出页面，比如可编辑表格 [文档](https://procomponents.ant.design/components/editable-table#%E4%BB%A3%E7%A0%81%E6%BC%94%E7%A4%BA)：[codesandbox](https://codesandbox.io/s/iu66fr?file=/App.tsx)

**Comment by jaluik** [comment]
已提交pr修复
