### ISSUE TITLE
🐛[BUG] DrawerForm 中配置form.item的required属性 使用form.validateFields 不生效

### ISSUE THREAD

**Issue by mathcw** [ant-design/pro-components#6635]
### 🐛 bug 描述

DrawerForm 中配置form.item的required属性后,使用form.validateFields 不生效

### 📷 复现步骤

codebox : https://codesandbox.io/s/shi-yong-open-he-onopenchange-forked-wb3qnd?file=/App.tsx

### 🏞 期望结果

希望validateFileds和其他form组件一样生效，表现一致

### © 版本信息

- ProComponents 版本: 2.3.57
- react 18.2.0

**Comment by DerrickTel** [comment]
`rules={[{ required: true, message: 'Please input your username!' }]} `
