### ISSUE TITLE
🧐[问题] 如官方文档示例  校验问题

### ISSUE THREAD

**Issue by ty01** [ant-design/pro-components#6639]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
如官方文档该示例：
https://procomponents.ant.design/components/schema-form#%E5%8A%A8%E6%80%81%E6%8E%A7%E5%88%B6%E6%98%AF%E5%90%A6%E9%87%8D%E6%B8%B2%E6%9F%93

需求：当标题栏输入必填时，标签那一栏要求必填，否则标签那一栏不必填

操作：1.标题栏输入必填，点击提交。此时触发校验，请输入标签，没问题
![image](https://user-images.githubusercontent.com/26292353/220239335-149159d7-6102-4a66-bb3f-f128c20813e3.png)
2. 修改标题栏为123，此时标签不必填，必填*号消失没问题，但是标签校验依旧存在，此处是否有问题？
![image](https://user-images.githubusercontent.com/26292353/220239552-573dee6a-c05e-41ae-94ff-34c4ac681e48.png)

**Comment by chenshuai2144** [comment]
可以使用自定义校验规则来对表单数据进行校验。下面是一个简单的示例：

```tsx
import { Form, Input } from 'antd';
import { Rule } from 'rc-field-form/lib/interface';

interface MyFormValues {
  name: string;
  age: number;
}

const MyForm = () => {
  const [form] = Form.useForm<MyFormValues>();

  const validateAge: Rule = (rule, value) => {
    if (value < 18 || value > 60) {
      return Promise.reject('年龄必须在18岁到60岁之间');
    }
    return Promise.resolve();
  };

  return (
    <Form form={form}>
      <Form.Item label="姓名" name="name" rules={[{ required: true, message: '请输入姓名' }]}>
        <Input />
      </Form.Item>
      <Form.Item label="年龄" name="age" rules={[{ required: true, message: '请输入年龄' }, { validator: validateAge }]}>
        <Input type="number" />
      </Form.Item>
    </Form>
  );
};

```

在上面的示例中，我们定义了一个名为 validateAge 的自定义校验规则，它接收一个 rule 对象和一个 value 值作为参数，用来验证年龄是否在指定的范围内。如果验证失败，我们使用 Promise.reject 返回一个错误信息，否则使用 Promise.resolve 返回空。然后在 <Form.Item> 组件的 rules 属性中，我们将自定义校验规则传递给了 validator 属性，表示在验证表单数据时使用该规则进行校验。

需要注意的是，自定义校验规则的函数签名是 Rule，它包含两个参数：rule 和 value，并返回一个 Promise 对象。其中，rule 是一个包含验证规则的对象，包括 required、pattern 等属性；value 是表单项的值。在自定义校验规则函数中，可以根据具体的业务逻辑进行校验，如果校验失败，返回一个 Promise 对象，Promise 的 reject 方法可以传递错误信息；如果校验成功，返回一个 Promise 对象，Promise 的 resolve 方法不传递任何值。

另外，需要注意的是，在使用自定义校验规则时，需要将该规则传递给 rules 属性的数组中，并将其作为对象传递给 validator 属性。


通过上面的办法，你可以用form 来获取到当前的输入，同时将你的业务落写入其中
