### ISSUE TITLE
🐛[BUG] ProFormSelect 搜索关键词发生变化时请求远程数据参数未携带

### ISSUE THREAD

**Issue by lyndonliu89757** [ant-design/pro-components#6645]
### 🐛 bug 描述
ProFormSelect 搜索关键词变化时，请求远程数据参数未携带，请求一直是第一次默认的参数。

### 📷 复现步骤
ProFormSelect request将 keywords置于请求的参数中，关键词发生变化时，请求参数未跟随变化。

### 🏞 期望结果
请求参数正常携带。

### 💻 复现代码

![image](https://user-images.githubusercontent.com/20126128/220506585-4258a5dd-7823-4452-b742-438ca63da650.png)

### © 版本信息

- ProComponents 版本: 2.3.57
- umi 版本: 4.0.52
- 浏览器环境 Chrome
- 开发环境 mac OS

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


### 🌟 解决方案
可能是因为在 `onSearch` 内部没有更新 `initialValues`。`initialValues` 是初始化表单控件的默认值，请查看该字段是否设置了 keywords 的值。

另外，在 `onSearch` 函数中，可以尝试修改 `params` 参数，将 `keywords` 加入到请求参数中。可以参考以下代码：

```
const handleSearch = (value: string) => {
  setParams((prevParams) => ({ ...prevParams, keywords: value }));
  ref?.current?.fetchList();
};
```

以上代码通过使用 `setParams` 函数更新 `params`，将 `keywords` 设置为输入框的值。然后通过调用 `fetchList()` 函数来刷新表格数据。

如果仍然存在问题，建议查看接口响应数据，并根据实际数据结构调整代码。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


针对该问题，可能的解决方法如下：

1. 在 ProFormSelect 表单控件的定义中，添加 initialValues 字段，并将其设置为 { keywords: '' }，如下所示：

```jsx
<ProFormSelect
  name="xxx"
  label="xxx"
  initialValues={{ keywords: '' }}
  request={xxx}
  onSearch={xxx}
/>
```

这样，每次表单被初始化时，keywords 字段的初始值便会被设为空值。

2. 在 onSearch 函数内部，手动更新 ProTable 的 params 参数，将新的关键字值添加进去，然后通过 fetchList 方法向后端发起请求，并更新表格的数据。示例代码如下：

```jsx
const onSearch = (value) => {
  const newParams = { ...params, keywords: value };
  setParams(newParams);
  ref?.current?.fetchList(newParams);
};
```

这个示例代码中，setParams 是一个 useState 定义的 setter 函数，用来更新 params 的值。
关键字 value 必须由一个类型为 string 的输入框组件传递进来。
ref 是一个 useRef 定义的 ref 对象，用来获取表格控件的实例对象。
fetchList 是 ProTable 组件提供的方法之一，它会向后端发起 AJAX 请求，并更新表格的数据。

3. 如果前两步都无法解决该问题，则建议检查一下发往后端的请求参数以及响应报文中是否包含了正确的关键字值。例如，如果后端 API 中期望的请求参数是 query，而不是 keywords，那么你需要将 onSearch 函数中的代码做出相应修改，也就是在新的 params 参数中将 keywords 字段改为 query，然后再将新的 params 参数发往后端 API 服务。
