### ISSUE TITLE
不算太严重的BUG，但还是忍不住笑了（无恶意）🐛[BUG]

### ISSUE THREAD

**Issue by tnngo** [ant-design/pro-components#6647]
### 🐛 bug 描述

官方protable示例中，出现抽风式闪烁。见最下方视频。示例位置应该是最后一个，滚动条滚到最下面就可以看到了。

### 📷 复现步骤

官方网站

### 🏞 期望结果

期望v6更稳定点，总觉得v6上的有点仓促。

### 💻 复现代码

官方网站

### © 版本信息

- ProComponents 版本: 不确定官网的版本是多少
- umi 版本：不确定官网的版本是多少
- 浏览器环境 ：chrome，version: 109.0.5414.119
- 开发环境：MAC OS

### 🚑 其他信息

https://user-images.githubusercontent.com/26067526/220612462-53e8a72e-8e80-4b4d-ad5e-ebd31453dcbd.mov

**Comment by ByYogi** [comment]
这个新官方页面有太多问题

**Comment by jeryqwq** [comment]
修复了，下个版本 #6641

**Comment by bans-hou** [comment]
请问,这个问题不升级版本,如何处理

**Comment by jeryqwq** [comment]
@bans-hou  把commit的css加到对应的class里面就好了，但是好像还有兼容性问题
