### ISSUE TITLE
🧐[问题]希望EditableProTable 日期选择器在选中后返回时间戳格式的数据，应该怎么设置？

### ISSUE THREAD

**Issue by dglxiaoyi** [ant-design/pro-components#6650]
在使用EditableProTable中要用到日期选择器，但是返回的数据格式是格式化后的数据，我想要拿到时间戳格式的数据。

![image](https://user-images.githubusercontent.com/29661975/220816232-33cc9574-ab4b-4296-83bc-3fcb202ec06a.png)

**Comment by XueMeijing** [comment]
自己用momentjs或者dayjs转一下？或者 new Date('2022-03-02' + ' 00:00:00').getTime()

**Comment by dglxiaoyi** [comment]
那我需要在什么时机，或者监听什么事件去转呢。我并没有找到日期选择器支持format和parse？
除了重新封装日期选择器，作为自定义组件，还有别的方法可以实现吗？

**Comment by XueMeijing** [comment]
```选中```后返回时间戳格式的数据，这里的选中指保存，还是点击日期组件的确定按钮，前者的话editable的onSave中改，后者columns的fieldProps里传format: 'x' 试一下，我也不确定 

日期fomat看这三个文档 
https://ant.design/components/date-picker-cn#%E5%9B%BD%E9%99%85%E5%8C%96%E9%85%8D%E7%BD%AE
https://day.js.org/docs/zh-CN/display/format
https://day.js.org/docs/zh-CN/plugin/advanced-format

**Comment by XueMeijing** [comment]
如果你需要的是这种需求，这样改就可以了

```
{
  title: '活动时间',
  key: 'created_at',
  dataIndex: 'created_at',
  valueType: 'date',
  fieldProps: {
    format: 'x',
  },
},
```


https://user-images.githubusercontent.com/35559153/222608095-3d38fc76-035e-4ec6-8798-07ac0ba21dd7.mp4

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


这个建议很好，可以通过在`EditableProTable`的`columns`中设置`fieldProps`来实现。具体可以将日期选择器的`format`属性设置为`x`，表示返回时间戳格式的数据。以下是一个示例：

```javascript
const columns = [
  {
    title: '日期',
    dataIndex: 'date',
    valueType: 'date',
    fieldProps: {
      format: 'x',
    },
  },
  // ...
];

// ...
<EditableProTable
  // ...
  columns={columns}
/>
```

这里的`date`是数据中存储日期的属性名，`valueType`表示数据类型是日期型，`format: 'x'`表示返回时间戳格式的数据。

另外，在用户选中日期后，会传递给`EditableProTable`的`onSave`回调函数中，可以在这里将格式化后的日期数据转换为时间戳格式的数据，例如：

```javascript
<EditableProTable
  // ...
  onSave={async (key, row) => {
    row.date = moment(row.date).valueOf();
    // ...
  }}
/>
```

这里使用了`moment.js`来将格式化后的日期转换为时间戳格式。如果你不想使用第三方库，也可以使用`Date`对象来进行转换，例如`new Date(row.date).getTime()`。

**Comment by dglxiaoyi** [comment]
尝试了上述两种方法，目前还是没有达到我的需求：
方法一，确实返回了时间戳的数据，但是我希望在选择的时候还是YYYY-MM-DD这样的展示，只是存储的数据格式是时间戳
方法二，在onSave中修改数据格式后，但是onChange抛出的仍是年月日格式的数据

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


感谢你详细说明问题。实际上，你的需求是在日期选择器中显示格式化的日期，同时保存为时间戳格式是吗？在这种情况下，可以将日期选择器的 `showTime` 属性设置为 `false` 并将其 format 属性设置为 `YYYY-MM-DD`（或任何其他所需的显示格式）。

以下是一个示例：

```javascript
const columns = [
  {
    title: '日期',
    dataIndex: 'date',
    valueType: 'date',
    fieldProps: {
      format: 'YYYY-MM-DD',
      showTime: false,
    },
    render: (text, record) => moment(text).format('YYYY-MM-DD'),
  },
  // ...
];

<EditableProTable
  // ...
  columns={columns}
  onSave={async (key, row) => {
    row.date = moment(row.date).valueOf();
    // ...
  }}
/>;
```

在这个示例中，我们通过 `fieldProps.showTime` 将时间选择器设置为不显示时间，然后将 `fieldProps.format` 设置为 `YYYY-MM-DD`。这将允许用户在日期选择器中选择日期，并在输入框中显示格式化的日期字符串。

而 `render` 属性将会把存储的日期格式化成需要展示的格式，在以上示例中展示的格式是 YYYY-MM-DD。`onSave` 回调函数将日期数据从格式化的字符串转换为时间戳。

这样，你就可以同时满足两方面的需求了。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


如果您需要选择日期时显示格式化的日期字符串，但保存日期时保存为时间戳格式的数据，可以如下所示修改 `EditableProTable` 的 `columns` 选项描述符（Descriptor）：

```javascript
import moment from 'moment';

// ...

const columns = [
  // ...
  {
    title: '日期',
    dataIndex: 'date',
    valueType: 'date',
    fieldProps: {
      format: 'YYYY-MM-DD',
      showTime: false,
      onChange: (value) => moment(value).valueOf(),
    },
    // 将日期转换为格式化的字符串
    render: (text) => moment(text).format('YYYY-MM-DD'),
  },
];

// ...

<EditableProTable
  // ...
  columns={columns}
  onSave={async (key, row) => {
    row.date = moment(row.date).valueOf();
    // ...
  }}
/>;
```

在这个示例中，我们添加了 `fieldProps.onChange` 属性以在选择日期时将日期值转换为时间戳格式。此外，我们还将 `fieldProps.showTime` 属性设置为 `false` 并将 `fieldProps.format` 属性设置为显示所需日期格式的字符串。

最后，我们还添加了 `render` 属性以在数据表格中显示格式化的日期字符串，并在 `onSave` 回调函数中将日期值转换为时间戳格式。

**Comment by dglxiaoyi** [comment]
我在onSave时已经将数据从格式化的字符串转换为时间戳，但是在onChange中接收到的数据格式仍是格式化的字符串
![image](https://user-images.githubusercontent.com/29661975/223098441-c47c7242-67aa-4bd6-b507-e990be074db8.png)

**Comment by XueMeijing** [comment]
> 我在onSave时已经将数据从格式化的字符串转换为时间戳，但是在onChange中接收到的数据格式仍是格式化的字符串 ![image](https://user-images.githubusercontent.com/29661975/223098441-c47c7242-67aa-4bd6-b507-e990be074db8.png)

还是不明白你的意思，那你在onChange里再处理不是也可以从格式化字符串变时间戳吗，你是要实现什么功能呢？

**Comment by chenshuai2144** [comment]
是的  onsave  的数据来自 onchange
