### ISSUE TITLE
🐛[BUG]升级Antd5之后，ProTable 自带搜索Form，日期格式未格式化

### ISSUE THREAD

**Issue by dongtao0725** [ant-design/pro-components#6651]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/30116184/220857800-57a4593f-48b8-43cc-89b6-a2c3cee8d945.png)

### 🏞 期望结果
格式化日期格式，与之前一样，默认YYYY-MM-DD

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by zoro-r** [comment]
不仅没有格式化 还丢失了继承的方法

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


感谢您提供了这份bug描述。根据您的描述，我了解到您升级了Antd5后，发现ProTable 自带搜索Form的日期格式未格式化且丢失了继承的方法。下面，我将提供一些可能解决您问题的方法。

1. 格式化日期格式

您可以尝试在字段配置处添加 `valueType` 属性配置日期格式，例如将其配置为 `date`，即可让ProTable自带搜索Form中的日期输出为默认格式(YYYY-MM-DD)：

```jsx
// columns 配置
{
  title: '日期',
  dataIndex: 'date',
  valueType: 'date',
}

// 或者

// form 配置
{
  type: 'date',
}

// 如果您想格式化日期输出的格式:
{
  title: '日期',
  dataIndex: 'date',
  valueType: 'date',
  valueEnum: timeEnum,
  fieldProps: {
    format: 'YYYY-MM-DD',
  },
},
```
关于valueType属性的更多详细信息请查阅antd官方文档：[配置 value、valueEnum 等值的类型](https://ant.design/components/form-cn/#%E9%85%8D%E7%BD%AE-value-valueenum-%E7%AD%89%E5%80%BC%E7%9A%84%E7%B1%BB%E5%9E%8B)。

2. 继承丢失

在升级Antd5后，由于部分API及组件属性配置的变化，可能导致ProTable自带带搜索Form的某些属性无法正确继承。您可以尝试查看[ProTable的API文档](https://procomponents.ant.design/components/table)，看看官方是否已经更新API说明，并进行相应的更改即可。

如果问题仍然存在，可以将您的问题与您的代码一起提交到ProTable的[issue](https://github.com/ant-design/pro-components/issues)中，并等待官方的解答。

希望以上内容能够帮助到您。如果您还有其他问题或需要更多帮助，请随时在github的issue中提出。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


补充一些帮助您进一步调试问题的方式：

1. 检查字段类型是否正确

在升级 Antd5 后，如果您的表格数据的类型发生了变化，可能会导致ProTable无法正确地格式化日期等数据类型。请确保您的数据类型与您的页面配置匹配。

2. 使用控制台进行调试

您可以在控制台先将需要的内容解构出来，检查数据结构是否正确。在调试过程中，您可以使用console语句进行调试:

```javascript
import { useState } from 'react';
import ProTable from '@ant-design/pro-table';

export default function App(props) {
  const [data, setData] = useState([]);

  const columns = [
    {
      title: '商品名称',
      dataIndex: 'name',
    },
    {
      title: '日期',
      dataIndex: 'date',
      valueType: 'date',
      fieldProps: {
        format: 'YYYY-MM-DD',
      },
    },
  ];

  return (
    <ProTable
      columns={columns}
      request={() => {
        fetch('/api/getData')
          .then((result) => result.json())
          .then((result) => setData(result.data));
      }}
      dataSource={data}
      rowKey="id"
      dateFormatter="string"
      search={{
        layout: 'vertical',
      }}
      options={{ search: true }}
    />
  );
}
```

在这个简单的示例中，您可以编辑类型、格式、搜索配置等，以检查是否有任何错误。另外，您还可以探索Protable的配置选项，如 `formStyle`, `toolBarRender` 和`loading`, 等等，这些选项也可能影响搜索表单的功能。

3. 查看Antd 文档和例子

Antd 做为一个优秀的UI组件库，有完整的文档支持，您可以查看[Antd的日期选择](https://ant.design/components/date-picker-cn/)和[ProTable的例子](https://procomponents.ant.design/components/table)获取更多支持。

希望这些提示对您有所帮助！

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您的反馈。关于您提出的这几点问题，可以针对性地给出以下解决方案。

1. dateFormatter='string'无效

在ProTable组件中，`dateFormatter='string'`是用来控制数据源中日期数据的转化格式。如果您的API返回的数据源格式是ISO格式，您可以尝试将`dateFormatter`配置为 `YYYY-MM-DD` 或 `YYYY-MM-DD HH:mm:ss`，或者您可以使用moment或dayjs等工具库将其转化为JS日期对象，并按照您所需的格式进行渲染。

例如：

```jsx
import moment from 'moment';

// columns配置
{
  title: '日期',
  dataIndex: 'date',
  render: (value) => moment(value).format('YYYY-MM-DD'),
}

// 或者使用valueType属性
{
  title: '日期',
  dataIndex: 'date',
  valueType: 'date',
}

// request请求
request={async () => {
  const resData = await getData();
  return resData.map(item => {
    item.date = moment(item.date).format('YYYY-MM-DD');
    return item;
  });
}}
```

对于其他可选的格式，请参考moment或dayjs文档。

2. columns设置valueType: 'dateRange'，无法生成YYYY-MM-DD格式

`valueType: 'dateRange'` 是用来指定日期区间类型的。如果需要自定义日期格式，可以设置`valueType`和`fieldProps: { ... }`以覆盖默认的格式，例如：

```jsx
//columns配置
{
  title: '日期',
  dataIndex: 'date',
  valueType: 'dateRange',
  fieldProps: {
    format: 'YYYY-MM-DD'
  }
}
```

此外，由于Ant Design的限制，可能需要使用Moment.js（>= 2.22.x版本）或 dayjs（>= 1.8.x版本）来处理日期数据的相关属性。

3. 设置fieldProps: {format: 'YYYY-MM-DD'}也无效

如果使用fieldProps的方式无法改变日期格式，建议通过 `render` 属性来手动控制日期的显示格式。例如：

```jsx
//columns配置
{
  title: '日期',
  dataIndex: 'date',
  render: (text) => moment(text).format('YYYY-MM-DD'),
}
```

如果以上方法都不能帮助您修改日期格式，可能需要查看Antd和ProTable的官方文档，以了解日期格式的包装方法。

希望这些解决方案能够帮助您解决问题。如果您仍有疑问，请随时更新您的问题。

**Comment by amusiq** [comment]
![image](https://github.com/ant-design/pro-components/assets/28551646/2ff5c09e-6de0-438d-8097-e09f432a7d3e)
我也出现了

**Comment by Aliveing** [comment]
我也有类似情况，具体原因不太了解，我是执行 `rm -r src/.umi* node_modules yarn.lock` 后再 `yarn install` 就好了，有时只删除 `src/.umi*` 就可以，猜测可能和 mfsu 的编译缓存有关系。

**Comment by chenshuai2144** [comment]
是 dayjs 的版本问题，大家注意下 不好安装两份 dayjs

**Comment by lovewinders** [comment]
> 是 dayjs 的版本问题，大家注意下 不好安装两份 dayjs

如果自己项目中安装过不同版本dayjs，有几率会导致这个问题，这时删除package.json中的dayjs应该能解决

**Comment by semmywong** [comment]
> 是 dayjs 的版本问题，大家注意下 不好安装两份 dayjs

如果没有再安装一份dayjs，无法在项目中使用，（我用的是pnpm，幽灵库无法使用的），所以有其他办法吗？

**Comment by anhao** [comment]
升级到最新的2.7.12 也出现这个问题了

**Comment by mx52jing** [comment]
> 是 dayjs 的版本问题，大家注意下 不好安装两份 dayjs

感谢，已解决。

下面是我遇到的问题和解决办法：

`search.transform`函数中吐出的`value`的值不是`dayjs`格式的，而是和上面一样的格式，使用`dayjs.isDayjs(start)`得到的值为`false`

我获取到的也是个对象，而且没有`$isDayjsObject`属性，没办法做转换，正确的`DayjsObject`应该是下面的格式，
```
{                                                                                                                                                                                     
      '$L': 'en',
      '$u': undefined,
      '$d': 2023-12-31T16:00:00.000Z,
      '$y': 2024,
      '$M': 0,
      '$D': 1,
      '$W': 1,
      '$H': 0,
      '$m': 0,
      '$s': 0,
      '$ms': 0,
      '$x': {},
      '$isDayjsObject': true // 我获取到的值没有这个属性
}
```

解决方法：

1. 查看本地是否有两个`dayjs`版本，我查看后发现存在两个版本一个是`1.11.12`，一个是`1.11.7`，我统一升级到`1.11.12`就好了

```js
        search: {
          transform: (value: any) => {
            const [start, end] = value ?? []
            console.log(",,transform,,,", {start, end })
            return { orderDate: start }
          }
        },
```
打印如下：
```
,,transform,,, {start: '2024-08-01', end: '2024-08-31'}
```
