### ISSUE TITLE
🐛[BUG]单元测试EditableProTable发现onValuesChange不回调/回调的record没有id

### ISSUE THREAD

**Issue by LittleChives** [ant-design/pro-components#6658]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

component内用了EditableProTable，本地和部署后功能都正常，onValuesChange的回调也都正常。但是单元测试的时候发现onValuesChange的回调不正常

**在公司和家里复现出的bug还不一样**
公司：onValuesChange会回调，但是record拿不到没有在column用到的field（比如在column没用到id、decs2这两个column，onValuesChange的record里面就没有id和desc2这两个字段，加上就有了！！）
家里：onValuesChange直接不回调了。

以上bug都是单元测试环境才会有的bug，浏览器环境正常。单元测试代码是一模一样的，怀疑是单元测试library版本的问题？

### 📷 复现步骤

1. component App2内使用EditableProTable （代码截图在下面）
2. EditableProTable属性：controlled，可同时多行编辑（type: 'multiple'），使用onValuesChange回调监听某些字段
3. 对App2编写单元测试，发现onValuesChange不回调(没打印log)。

### 🏞 期望结果

单元测试一样能够回调onValuesChange，因为实际代码里有很多判断。。。

### 💻 复现代码

App2.tsx:
`

import type { ProColumns } from '@ant-design/pro-table';
import { EditableProTable, } from '@ant-design/pro-table';
import React, { useEffect, useState } from 'react';

type DataSourceType = {
    id: React.Key;
    title: string;
    decs: string;
    decs2: string;
    state: string;
};
const App2 = ({
    editable,
}: {
    editable: boolean;
}) => {

    const [editableKeys, setEditableRowKeys] = useState<React.Key[]>([]);
    const [dataSource, setDataSource] = useState<DataSourceType[]>(
        [
            {
                id: 'uuid-1',
                title: '活动名称一',
                decs: '这个活动真好玩1-1',
                decs2: '这个活动真好玩1-2',
                state: 'true',
            },
            {
                id: 'uuid-2',
                title: '活动名称二',
                decs: '这个活动真好玩2-1',
                decs2: '这个活动真好玩2-2',
                state: 'true',
            },
        ]
    );

    const columns: ProColumns<DataSourceType>[] = [
        {
            title: '活动名称',
            dataIndex: 'title',
        },
        {
            title: '状态',
            dataIndex: 'state',
            valueType: 'radio',
            valueEnum: {
                true: { text: 'true', },
                false: { text: 'false', },
            },
        },
        {
            title: '描述',
            dataIndex: 'decs',
        },
        {
            title: '描述2',
            dataIndex: 'decs2',
        },
    ];

    useEffect(() => {
        console.log('dataSource updates:', JSON.stringify(dataSource));
        setEditableRowKeys(dataSource.map(item => item.id));
    }, [dataSource]);

    const onValuesChange = (record: DataSourceType, dataSource: DataSourceType[]) => {
        console.log('onValuesChange, record:', JSON.stringify(record));
        console.log(record.id.toString());
        setDataSource(dataSource);
    }

    return (
        <EditableProTable<DataSourceType>
            headerTitle="可编辑表格"
            columns={columns}
            rowKey="id"
            value={dataSource}
            recordCreatorProps={false}
            controlled
            editable={{
                type: 'multiple',
                editableKeys,
                onValuesChange: onValuesChange,
            }}
        />
    );
};

export default App2;`

App2.test.tsx:
`import { act, cleanup, fireEvent, render } from '@testing-library/react';
import { waitForComponentToPaint } from '../../tests/util';
import App2 from './App2';

describe('App2', () => {
  afterEach(() => {
    cleanup();
  });

  it('App2: change item radio', async () => {

    const wrapper = render(<App2 editable={true} />,);
    expect(wrapper.container.querySelectorAll('tr.ant-table-row.ant-table-row-level-0').length).toBeGreaterThan(0);
    const firstRadioElement = wrapper.container.querySelectorAll('tr.ant-table-row.ant-table-row-level-0')[0].querySelectorAll('input.ant-radio-input')[0];
    expect(firstRadioElement).toBeInTheDocument();
    const previousValue = firstRadioElement.checked;
    expect(previousValue).toEqual(true);

    const secondRadioElement = wrapper.container.querySelectorAll('tr.ant-table-row.ant-table-row-level-0')[0].querySelectorAll('input.ant-radio-input')[1];
    expect(secondRadioElement).toBeInTheDocument();
    await act(async () => {
      fireEvent.click(secondRadioElement);
    })
    waitForComponentToPaint(wrapper, 100);
    const firstRadioElementContent = wrapper.container.querySelectorAll('tr.ant-table-row.ant-table-row-level-0')[0].querySelectorAll('input.ant-radio-input')[0].checked;
    expect(firstRadioElementContent).toEqual(false);
    // wrapper.debug(wrapper.container, 100000)
  });

});`

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本  V3的
- 浏览器环境 chrome正常，单元测试环境（jsdom）不正常
- 开发环境 [e.g. mac OS] windows

**package.json:**
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-card": "^1.19.0",
    "@ant-design/pro-descriptions": "^1.10.0",
    "@ant-design/pro-form": "^1.64.0",
    "@ant-design/pro-layout": "^6.35.0",
    "@ant-design/pro-table": "^2.71.0",
    "antd": "^4.19.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.0",
    "react-window": "^1.8.8",
    "umi": "^3.5.0",
**devDependencies:**
    "@ant-design/pro-cli": "^2.1.0",
    "@testing-library/dom": "^8.20.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "12.1.5",
    "@testing-library/react-hooks": "^8.0.1",
    "@testing-library/user-event": "^14.4.3",
    "@types/jest": "^26.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "jsdom-global": "^3.0.0",

**node版本**
公司jenkins默认是14.17.3 

### 🚑 其他信息

浏览器环境下标黄的log都能打印：
![image](https://user-images.githubusercontent.com/22339523/221275606-0df24c91-a751-44e8-aec5-e4c8f54a1ca2.png)

单元测试环境下只打印第一个
![image](https://user-images.githubusercontent.com/22339523/221275760-496ae783-5a35-4b8c-b704-96c0889f033f.png)

麻烦帮忙看一下谢谢了

**Comment by tnngo** [comment]
建议删除掉单元测试就行了

**Comment by LittleChives** [comment]
您好,邮件已经收到,谢谢!

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


不客气，有其他问题可以继续联系我。祝您工作愉快！
