### ISSUE TITLE
🧐[问题]ProTable如何实现点击某一个cell进行搜索？

### ISSUE THREAD

**Issue by TangMonk** [ant-design/pro-components#6659]
### 🧐 问题描述

<img width="175" alt="image" src="https://user-images.githubusercontent.com/3498786/221333668-957bf623-61f8-4cf1-be98-cfbe3ba9af2b.png">

比如说这一列都有个Filter按钮，点击之后就可以自动填入到表单，然后进行搜索。

我本来想对Filter按钮做一个onClick，但是找不到类似`protable.form.submit()`的方法

**Comment by hihuangwei** [comment]
可以在表头实现搜索，是这样吗
![Screenshot_2023-02-25-22-46-33-707_com android chrome-edit](https://user-images.githubusercontent.com/3166799/221363233-37eed966-29da-48dd-98af-6d70547797cb.jpg)

**Comment by TangMonk** [comment]
> 可以在表头实现搜索，是这样吗 ![Screenshot_2023-02-25-22-46-33-707_com android chrome-edit](https://user-images.githubusercontent.com/3166799/221363233-37eed966-29da-48dd-98af-6d70547797cb.jpg)

不是表头搜索，就是点击某一个cell旁边的Filter按钮，就自动搜索

**Comment by hihuangwei** [comment]
这个可以自己实现的。带入参数，重新请求 request

**Comment by XueMeijing** [comment]
给ProTable加formRef，然后使用 formRef?.current?.submit() 就可以重新请求接口了
或者加actionRef然后actionRef.current.reload() 也可以

**Comment by TangMonk** [comment]
> 给ProTable加formRef，然后使用 formRef?.current?.submit() 就可以重新请求接口了 或者加actionRef然后actionRef.current.reload() 也可以

谢谢，懂了

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


不客气，如果您还有其他问题，欢迎提出。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


如您还有其他问题，请告知并留下相应的信息，我会尽快为您解答。
