### ISSUE TITLE
🧐[问题]dark={true}在antd:4上不生效？

### ISSUE THREAD

**Issue by ItsJackWang** [ant-design/pro-components#6667]
pro-components: 2.3.57
antd: 4.24

按照官方文档https://procomponents.ant.design/components/layout#packages-layout-src-components-layout-demo-dark 设置了dark后不生效，换成antd：5生效。

请教大家2个问题：
1. pro-components: 2兼容antd：4吗？如何使dark生效
2. pro-components: 1的文档在哪里看？

**Comment by owendswang** [comment]
pro-component: 2.3.58
antd: 4.24.8
ice.js: 2.6.6
vite: 2.9.15

同样按照文档https://procomponents.ant.design/components/layout#packages-layout-src-components-layout-demo-dark设置了dark={true}不生效。

**Comment by owendswang** [comment]
> pro-components: 2.3.57 antd: 4.24
> 
> 按照官方文档https://procomponents.ant.design/components/layout#packages-layout-src-components-layout-demo-dark 设置了dark后不生效，换成antd：5生效。
> 
> 请教大家2个问题：
> 
>     1. pro-components: 2兼容antd：4吗？如何使dark生效
> 
>     2. pro-components: 1的文档在哪里看？

1. 我的环境下试了antd@4.24.8的确也不行，但你所给出的antd@5.2.3的确好使，发现了新大陆我的天，十分感谢！
2. 在我的印象里pro-component的文档里，一开始都是引用的独立的组件，例如@ant-design/pro-layout、@ant-desing/pro-card等，不是从@ant-design/procomponents里引用的，文档是在这个包版本为2.0之后才改成一概从@ant-design/procomponents里引用的。另外从你的antd@4替换为antd@5的操作推断，他的功能只是对antd的调用，没有依赖于antd的版本，所以我觉得他的功能和文档，其实与他是1.0还是2.0没太大关系。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


关于dark={true}不生效的问题，试试在ProLayout标签上添加theme属性，并在属性值中设置dark为true即可。示例：

```jsx
import { ProLayout } from '@ant-design/pro-layout';
import { MenuDataItem } from '@ant-design/pro-layout/lib/typings';

const menuData: MenuDataItem[] = [
  {
    path: '/welcome',
    name: '欢迎',
    icon: 'smile',
  },
  // 其他菜单项...
];

<View>
  <ProLayout
    title="Pro 计划"
    logo={logo}
    menuData={menuData}
    headerContentRender={() => <CustomHeader />}
    footerRender={() => <CustomFooter />}
    navTheme="dark"
    theme={{ dark: true }}
    layout="side"
  >
    {children}
  </ProLayout>
</View>
```

关于pro-components: 1的文档，可以在GitHub上的release页面找到对应版本的文档。注意，pro-components: 1与pro-components: 2之间的API有较大差异，使用时需要注意。最好是直接使用最新版本的pro-components。

**Comment by chenshuai2144** [comment]
是的，因为antd@4 不支持 token

**Comment by ItsJackWang** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。
> 
> 关于dark={true}不生效的问题，试试在ProLayout标签上添加theme属性，并在属性值中设置dark为true即可。示例：
> 
> ```js
> import { ProLayout } from '@ant-design/pro-layout';
> import { MenuDataItem } from '@ant-design/pro-layout/lib/typings';
> 
> const menuData: MenuDataItem[] = [
>   {
>     path: '/welcome',
>     name: '欢迎',
>     icon: 'smile',
>   },
>   // 其他菜单项...
> ];
> 
> <View>
>   <ProLayout
>     title="Pro 计划"
>     logo={logo}
>     menuData={menuData}
>     headerContentRender={() => <CustomHeader />}
>     footerRender={() => <CustomFooter />}
>     navTheme="dark"
>     theme={{ dark: true }}
>     layout="side"
>   >
>     {children}
>   </ProLayout>
> </View>
> ```
> 
> 关于pro-components: 1的文档，可以在GitHub上的release页面找到对应版本的文档。注意，pro-components: 1与pro-components: 2之间的API有较大差异，使用时需要注意。最好是直接使用最新版本的pro-components。

试了下，并不生效

**Comment by ItsJackWang** [comment]
> 

是pro-components@2不支持antd@4的深浅切换吗？
