### ISSUE TITLE
🧐[问题]Protable如何实时更新？

### ISSUE THREAD

**Issue by TangMonk** [ant-design/pro-components#6668]
### 🧐 问题描述

服务端通过websocket实时的发送新的数据到Protable的表格里，但是如何实时刷新呢？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。

**Comment by TangMonk** [comment]
@chenshuai2144 牛逼啊

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


感谢夸奖，如有其他问题也欢迎随时提出。
