### ISSUE TITLE
🐛[BUG] ProForm validateMessages 显示${label}为undefined

### ISSUE THREAD

**Issue by roytan883** [ant-design/pro-components#667]
### 🐛 bug 描述

设置validateMessages为
```
  const validateMessages = {
    required: "${label} 是必选字段",
  };
```
显示结果为:
```
undefined 是必选字段
```
似乎是不能象antd的form那样用validateMessages的${label}?

然后尝试了不手动设置validateMessages,默认对required显示的错误是
```
请输入undefined
```

**Comment by roytan883** [comment]
再比如设置一个字段为:
```
rules={[{required: true}, { type: 'number', min: 0, max: 99 }]}
```
输入1,提示
```
undefined不是一个有效的number
```

**Comment by chenshuai2144** [comment]
我们覆盖了 antd 的label，不过现在可以加回来了

**Comment by roytan883** [comment]
@chenshuai2144 
> 我们覆盖了 antd 的label，不过现在可以加回来了

但是我测试
```
rules={[{required: true}]}
```

使用了pro form最新版本1.0.2还是显示undefined

![image](https://user-images.githubusercontent.com/4022752/95944372-aa0f4c80-0e1a-11eb-9090-b4967f091191.png)

**Comment by roytan883** [comment]
```
rules={[{required: true}, { type: 'number', min: 0, max: 99 }]}
```
输入数字1的时候提示:
![image](https://user-images.githubusercontent.com/4022752/95944746-7da80000-0e1b-11eb-91f7-902bb966d220.png)

**Comment by roytan883** [comment]
@chenshuai2144 ???
