### ISSUE TITLE
[需求] addEditRecord 新增加了一行，怎么表格外的批量删除中删除新增这一行  [需求]

### ISSUE THREAD

**Issue by shijy01350** [ant-design/pro-components#6677]
![image](https://user-images.githubusercontent.com/40890258/221812484-ba6b2a0a-ac88-4896-9d67-856f55943992.png)
![Uploading image.png…]()

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


非常抱歉，由于您提供的图片我无法显示，无法对您的问题提供准确的解答。但是，如果您的需求是在表格外的批量删除中删除新增的行，可以考虑使用一个标志位来表示新增的行，并在进行批量删除时跳过该标志位对应的行。以下是一个可能的解决方案：

```javascript
// 在添加新行时设置标志位
const data = [...this.state.data];
const newRow = { /* 新行的数据 */ };
newRow.isNew = true; // 给新行设置标志位
data.push(newRow);
this.setState({ data });

// 在删除行时判断是否是新增的行
handleBulkDelete = () => {
  const { selected } = this.state;
  const data = [...this.state.data].filter((_, i) => !selected.includes(i) || this.state.data[i].isNew); // 过滤掉被选中的行以及新增的行
  this.setState({
    data,
    selected: []
  });
};
```

以上只是一个简单的示例，具体实现方式还需要根据您的具体场景进行调整。同时，如果您需要更详细的帮助，可以参考 React 官方文档（https://reactjs.org/docs/getting-started.html）或者在 GitHub 上搜索相关的 React 问题，可能会有更好的解决方案。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。
