### ISSUE TITLE
In the mobile view, if we click anywhere on the center page, the sidebar doesn't close

### ISSUE THREAD

**Issue by beeena** [ant-design/pro-components#6678]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sad-bohr-zsogie?file=/src/App.js)

### Steps to reproduce

In the mobile view, if we click anywhere on the center page, the sidebar gets closed.

### What is expected?

In the mobile view, if we click anywhere on the center page, the sidebar gets closed.

![image](https://user-images.githubusercontent.com/38552626/221651121-466ecf5c-fb38-4fee-8e0d-77dc4390dfd8.png)

### What is actually happening?

In the mobile view, if we click anywhere on the center page, the sidebar doesn't close.

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | "react": "18.0.0" |
| System | ubuntu 20 |
| Browser | Google Chrome  Version 110.0.5481.77 (Official Build) (64-bit) |

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


Thanks for the update! So as I understand, the issue is that in the mobile view, clicking on the center page does not close the sidebar, and this is not the expected behavior. Is that correct? 

If so, you can solve this by adding an `onClick` handler to the center page that sets the `collapsed` state to `true`, which should close the sidebar. 

Here's some sample code that should achieve that:

```jsx
import React, { useState } from "react";
import { Layout, Menu } from "antd";

import "./styles.css";

const { Sider, Content } = Layout;

const App = () => {
  const [collapsed, setCollapsed] = useState(false);

  return (
    <Layout style={{ minHeight: "100vh" }}>
      <Sider collapsible collapsed={collapsed} onCollapse={() => setCollapsed(!collapsed)}>
        <Menu theme="dark" defaultSelectedKeys={["1"]} mode="inline">
          <Menu.Item key="1">
            <span>Option 1</span>
          </Menu.Item>
          <Menu.Item key="2">
            <span>Option 2</span>
          </Menu.Item>
        </Menu>
      </Sider>
      <Layout>
        <Content style={{ padding: "50px" }} onClick={() => setCollapsed(true)}>
          <div style={{ background: "#fff", minHeight: "100vh" }}>Hello World!</div>
        </Content>
      </Layout>
    </Layout>
  );
};

export default App;
```

Here, I've added an `onClick` handler to the `Content` component, which represents the center page. This handler sets the `collapsed` state to `true`, which should close the sidebar. 

Let me know if this helps or if you have any further questions!

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


Please kindly try the solution mentioned above, and see if it solves your problem. 

Additionally, you may refer to the official documentation of [Ant Design Layout](https://ant.design/components/layout/) to learn more about how to use it. If you encounter any issues or have any further questions, feel free to ask!
