### ISSUE TITLE
ProFormSwitch无法设置选中、未选中的内容🐛[BUG]

### ISSUE THREAD

**Issue by quarkcms** [ant-design/pro-components#668]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/60868863/95649316-7fb64a00-0b0f-11eb-9e5a-d444ce3bc4e3.png)

**Comment by quarkcms** [comment]
@chenshuai2144

**Comment by quarkcms** [comment]
已经自己摸索出来了，希望文档更详细一点儿

**Comment by chenshuai2144** [comment]
可以写出来吗？
