### ISSUE TITLE
🐛[BUG] ProLayout 导致 antd StyleProvider hashPriority='high' 失效问题

### ISSUE THREAD

**Issue by faner11** [ant-design/pro-components#6681]
### 🐛 bug 描述

ProLayout 导致 antd StyleProvider hashPriority='high' 失效，导致使用tailwindcss后在layout里面的button就有问题，外边的正常

### 📷 复现步骤

[codesandbox](https://codesandbox.io/p/github/faner11/react-antd/draft/goofy-solomon)

### 🏞 期望结果

在layout 组件内的  button样式也正常 

### 💻 复现代码
https://codesandbox.io/p/github/faner11/react-antd/draft/goofy-solomon?file=%2Fsrc%2Fmain.tsx

### © 版本信息

- "@ant-design/pro-components": "^2.3.58"
- "antd": "^5.2.3"
- "@ant-design/cssinjs": "^1.6.0",

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好，根据你的描述和提供的代码，我认为这个问题的原因是 `ProLayout` 组件的样式优先级高于 `antd` 的 `StyleProvider`，导致部分样式无法生效。

解决方案是在 `ProLayout` 组件上加上 `style={{ zIndex: 11 }}` 来调整样式优先级。具体代码如下：

```tsx
<ProLayout style={{ zIndex: 11 }}>
  ...
</ProLayout>
```

关于 `zIndex` 属性可以参考[官方文档](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index)。或者你可以尝试升级你的 `antd` 版本，新版本的 `antd` 已经将 `StyleProvider` 的优先级设置为 `important`，可能可以解决这个问题。 

希望这个解决方案对你有帮助，如果还有其他问题，请随时提问。

**Comment by faner11** [comment]
可能不是这个原因
我升级到最新的antd 之后还是遇到了这个问题，在pro-components 之外和button的类名有明显区别
![image](https://user-images.githubusercontent.com/26560612/223071635-e216dcd3-cbc4-42d0-bc95-a57876c0ea87.png)

**Comment by faner11** [comment]
StyleProvider 设置hashPriority=high，是生效的，但是在pro-components组件里里这个设置好像又失效了 @chenshuai2144

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


根据您的描述，我建议您增加 `ProLayout` 内部的样式优先级来覆盖 `ProLayout` 的样式，从而保证 `StyleProvider` 的设置不会被覆盖。具体来说，您可以在 `ProLayout` 内部对要修改的组件样式添加一个类名，并使用类名来覆盖组件样式。代码示例如下：

```jsx
import { ProLayout } from '@ant-design/pro-layout';
import styles from './index.css';

export default () => (
  <ProLayout>
    <div className={styles.myButton}>
      <Button>样式覆盖测试</Button>
    </div>
  </ProLayout>
);
```

其中 `styles.myButton` 是一个 CSS 模块化生成的类名，它会自动添加一个哈希值以避免命名冲突。您需要在代码中引入该类名所在的样式文件，并使用该类名来覆盖组件样式。此外，您需要为该组件设置一个更高的样式优先级，例如：

```css
.myButton {
  /* 优先级更高的样式规则 */
  /* 需要使用 `!important` 来覆盖 ProLayout 中的样式 */
  background-color: red !important;
}
```

需要注意的是，使用 `!important` 来覆盖样式会带来一定的风险，可能导致其他组件的样式受到影响。因此，请尽量在目标组件的范围内使用上述方案，并避免在全局样式中使用 `!important`。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。

**Comment by chenshuai2144** [comment]
试试antd 或者 cssinjs 有两份实例导致的，你可以用alias 来让大家都使用一个实例

**Comment by faner11** [comment]
> 试试antd 或者 cssinjs 有两份实例导致的，你可以用alias 来让大家都使用一个实例

没理解，可以说的具体一些吗 @chenshuai2144

**Comment by chenshuai2144** [comment]
npm ls antd 

看看是不是有两个版本。


当我们在一个项目中使用了多份相同的依赖库（比如 React、Antd、CSS-in-JS 等），就容易出现依赖版本冲突的问题。这可能造成一些难以排查的问题，影响项目正常运行。


为了解决这个问题，我们可以使用 Webpack 的 alias 功能，将这些库们都指向同一个实例。这样既可以保证版本一致性，也可以减小打包体积。

```

// webpack.config.js

const path = require('path')

module.exports = {
  // ...其他配置
  resolve: {
    alias: {
      // 引用时使用的路径：实际的文件路径
      react: path.resolve(__dirname, 'node_modules/react'),
      antd: path.resolve(__dirname, 'node_modules/antd'),
      'styled-components': path.resolve(__dirname, 'node_modules/styled-components') webpack.config.js

const path = require('path')

module.exports = {
  // ...其他配置
  resolve: {
    alias: {
      // 引用时使用的路径：实际的文件路径
      react: path.resolve(__dirname, 'node_modules/react'),
      antd: path.resolve(__dirname, 'node_modules/antd'),
      'styled-components': path.resolve(__dirname, 'node_modules/styled-components')
    }
  }
}

webpack配置文件：webpack.config.js

const path = require('path')

module.exports = {
  // ...其他配置
  // 解析配置
  resolve: {
    alias: {
      // 引用时使用的路径：实际的文件路径
      // React库的路径别名
      react: path.resolve(__dirname, 'node_modules/react'),
      // Ant Design库的路径别名
      antd: path.resolve(__dirname, 'node_modules/antd'),
      // styled-components库的路径别名
      'styled-components': path.resolve(__dirname, 'node_modules/styled-components')
    }
  }
}
    }
  }
}
```

**Comment by faner11** [comment]
可能不是alias的问题， @chenshuai2144

**Comment by chenshuai2144** [comment]
我试了一下。没有问题。要不你手动设置一下的 hashed=false。

**Comment by faner11** [comment]
@chenshuai2144 大哥，你看一下Demo，明显就是有问题的呀，hashed是那里的配置

**Comment by chenshuai2144** [comment]
按钮问题是因为  App  里面带的 reset css，hashed  看看  ConfigProvide

**Comment by faner11** [comment]
> 按钮问题是因为 App 里面带的 reset css，hashed 看看 ConfigProvide

demo 没有引用antd App组件, hashed 设了也没有用，你可能是是把tailwind.config.cjs的preflight设为false了，所以看到的都是正常的
<img width="690" alt="image" src="https://github.com/ant-design/pro-components/assets/26560612/16f6171f-55bf-4174-a22a-2397f787a041">
