### ISSUE TITLE
👑 [需求] 新增商品使用带二级分类选择器，在ProTable里面如何通过枚举进行回显分类中文？

### ISSUE THREAD

**Issue by Connor-lipalater** [ant-design/pro-components#6683]
所属模块或组件：
项目模块是product，框架组件是：ProTable

🥰 需求描述：
新增商品使用带二级分类选择器，可以选择一级也可以选择二级，接口报错的分类code值，在ProTable里面如何通过枚举进行回显分类中文？如下图：
![a2d4d1cba6929f26f3baf595dbb8368](https://user-images.githubusercontent.com/105040671/222069126-c3c328dc-9f2d-4af4-93df-be2ec5843132.png)
![image](https://user-images.githubusercontent.com/105040671/222069258-7a2acfa1-ec46-46e0-8e82-40ce2d2ad9d2.png)

项目地址：https://spdev.lipalaterapis.com/home
账号：383963742@qq.com 密码：1234567

仓库地址：https://github.com/lipa-later/web-store-admin.git

**Comment by XueMeijing** [comment]
仓库地址404了，不太明白你的意思，如果你能拿到数据的话可以用 renderFormItem 进行自定义渲染

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


非常抱歉，可能链接过期了。我的意思是，如果你使用的是 Ant Design Pro 框架的 ProTable 组件，并且你将选择器的分类信息存储为 code 值，你可以在列表页回显时通过 `render` 属性和枚举对象的方式显示分类名称。

具体做法可以参照以下步骤：

1. 定义枚举对象，将分类的 code 值作为 key，分类名称作为 value：

```javascript
const categoryOptions = {
  1: "分类一",
  2: "分类二",
  3: "分类三",
  // ......
};
```

2. 在 ProTable 的 columns 中，使用 `render` 属性进行自定义渲染。在 render 函数中，通过枚举对象和当前行的数据，将分类的 code 值转换为分类名称：

```javascript
const columns = [
  // 其他列的配置......
  {
    title: "分类",
    dataIndex: "category",
    render: (_, record) => {
      const categoryCode = record.category;
      return categoryOptions[categoryCode];
    },
  },
];
```

在上述代码中：

- `title` 设置了这一列的标题名称；
- `dataIndex` 设置了该列对应数据源的属性名；
- `render` 属性使用了箭头函数简写的方式，该函数有两个参数：`text` 和 `record`。这里只使用了 `record`，表示这一行的数据对象。这里的 `_` 表示当前列的值不需要被直接渲染出来；
- `render` 函数返回分类的中文名称。

以上是一个简单的示例，具体实现会根据具体情况有所不同，但核心思想是一样的。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


另外，如果在选择器中没有获取到分类名称对应的中文值，可能需要在后端接口中手动添加该字段进行返回。如果无法更改后端接口，可以在前端使用 `useEffect` 和 `async/await` 的方式在组件加载时获取枚举对象并存储到本地进行使用，方法如下：

```javascript
import { useEffect, useState } from "react"

const [categoryOptions, setCategoryOptions] = useState({});

useEffect(() => {
  async function fetchCategoryOptions() {
    const response = await fetch("/api/category/options");
    const options = await response.json();
    setCategoryOptions(options);
  }

  fetchCategoryOptions();
}, []);
```

在上述代码中，`fetchCategoryOptions` 函数通过 fetch API 发送请求，并将返回结果解析为对象存储到本地。在组件加载时，通过 `useEffect` 自动触发该函数。 `[]` 参数表示只有组件初次挂载时执行该函数，之后组件更新时不再执行。

将该本地存储的分类名称与分类 code 值对应的映射关系传递给 `ProTable`，就可以通过 `render` 属性进行解析并在前端网页中显示分类名称。
