### ISSUE TITLE
🐛[BUG] EditableProTable 的column 配置renderFormItem 自定义组件，连续输入会失去焦点

### ISSUE THREAD

**Issue by believeZJP** [ant-design/pro-components#6687]
### 🐛 bug 描述

EditableProTable的column里的renderFormItem，渲染了一个自定义的input组件，在这个input输入时，每次都会失去焦点

### 📷 复现步骤

<https://codesandbox.io/s/editableprotable-performance-issue-forked-b2z3lm?file=/App.tsx:1246-1260>

在ID列的输入框中连续输入值

### 🏞 期望结果

在ID列输入时，能跟在product列输入时一样不失去焦点

### 💻 复现代码
<https://codesandbox.io/s/editableprotable-performance-issue-forked-b2z3lm?file=/App.tsx:1246-1260>

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by thinkasany** [comment]
似乎是你使用不当才出现的问题，我尝试了以下两步解决这个问题。
1. EditableProTable 的 rowKey="id"， 所以我觉得你要修改的id应该换成product_id比较好
2. 你在renderFormItem中return 的组件<TagList /> 使用useMemo包裹一下，这样子就不会每次其他子组件都跟着重新render了。

**Comment by believeZJP** [comment]
> 

优秀，用useMemo完美解决问题

**Comment by believeZJP** [comment]
还有种解决办法是在`handleInputChange`时不触发onChange,加一个onBlur监听，在onBlur时触发更新，也能解决问题，不过体验没有用`useMemo`的方法好。修改代码示例：<https://codesandbox.io/s/editableprotable-performance-issue-forked-kgv06r?file=/App.tsx:684-701>

**Comment by thinkasany** [comment]
nice，能够完美解决这个问题，挺好的

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


很高兴能够帮到你，如果有其他问题可以随时找我哦！

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


非常感谢，我会记住的！
