### ISSUE TITLE
文档或者是库有一处笔误🐛[BUG]

### ISSUE THREAD

**Issue by quarkcms** [ant-design/pro-components#669]
### 🐛 bug 描述

文档实例与库不一样
![image](https://user-images.githubusercontent.com/60868863/95650424-36b5c400-0b16-11eb-9892-3904e90eef42.png)

![image](https://user-images.githubusercontent.com/60868863/95650438-5220cf00-0b16-11eb-9b11-cf3728911bf2.png)
password的W大小写不一致

**Comment by quarkcms** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
直接开个pr?

**Comment by chenshuai2144** [comment]
非常给力
