### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by fengzehao** [ant-design/pro-components#6691]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProLayout 混合模式下且actionsRender未配置，则avatarProps配置失效；
配置上如下的actionsRender，avatarProps配置才生效。

`actionsRender={(props) => {
                        if (props.isMobile) return []
                        return []
                    }}`

### 📷 复现步骤

ProLayout 混合模式下且actionsRender不配置任何代码

### 🏞 期望结果

未配置actionsRender，且avatarProps正常生效

### 💻 复现代码

`<div style={{height: '100vh'}}>
            <ProConfigProvider hashed={false}>
                <ProLayout
                    title='管理平台'
                    layout='mix'
                    //splitMenus={true}
                    fixSiderbar={false}
                    //token={layoutToken}
                    route={routes}
                    location={{pathname}}
                    menu={{
                        locale: false
                    }}
                    menuItemRender={(item, dom) => {
                        return (
                            <Link
                                to={item.path}
                                onClick={() => {
                                    if (pathname !== item.path) {
                                        setPathname(item.path)
                                    }
                                }}
                            >
                                {dom}
                            </Link>
                        )
                    }}
                    actionsRender={(props) => {
                        if (props.isMobile) return []
                        return []
                    }}
                    avatarProps={{
                        src: 'https://gw.alipayobjects.com/zos/antfincdn/efFD%24IOql2/weixintupian_20170331104822.jpg',
                        size: 'small',
                        title: '七妮妮',
                        render: (props, dom) => {
                            // noinspection JSValidateTypes
                            return (
                                <Dropdown
                                    menu={{
                                        items: [
                                            {
                                                key: 'logout',
                                                icon: <LogoutOutlined/>,
                                                label: '退出登录'
                                            }
                                        ]
                                    }}
                                >
                                    {dom}
                                </Dropdown>
                            )
                        }
                    }}
                >
                    <Outlet/>
                </ProLayout>
            </ProConfigProvider>
        </div>`

### © 版本信息

- ProComponents 版本: [2.3.58]
- 浏览器环境 [chrome 110]
- 开发环境 [e.g. mac OS]

**Comment by xliez** [comment]
+1

**Comment by RiverThrimp** [comment]
+1

Reopen this issue please
