### ISSUE TITLE
🐛[BUG]EditableProTable 的column 配置renderFormItem 自定义组件，怎样清除输入框的值

### ISSUE THREAD

**Issue by believeZJP** [ant-design/pro-components#6693]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/15198091/222333529-11114851-fd45-456e-bad8-62828b2d98b9.png)

如图，点击按钮”点击清楚，数据已经发生变化，但表格里的输入框不发生变化“

### 📷 复现步骤

<https://codesandbox.io/s/editableprotable-performance-issue-forked-hqs01e?file=/App.tsx>
### 🏞 期望结果

点击清除，数据发生变化的同时，界面里数据也发生变化

### 💻 复现代码
https://codesandbox.io/s/editableprotable-performance-issue-forked-hqs01e?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by XueMeijing** [comment]
你这样就可以了 

![image](https://user-images.githubusercontent.com/35559153/222371036-bcf1dd3c-64dc-4cf2-ab15-53f671b07bf5.png)

**Comment by XueMeijing** [comment]
如果你想同时修改ID和Product两列，你需要改这些地方，绑定formRef 再通过formRef控制数据

![image](https://user-images.githubusercontent.com/35559153/222389222-36319d2f-5292-49f2-b264-418c86a99ef3.png)

![image](https://user-images.githubusercontent.com/35559153/222389561-a51abb07-06a5-43c1-bc6d-2619da0ee61a.png)

**Comment by believeZJP** [comment]
> 你这样就可以了
> 
> ![image](https://user-images.githubusercontent.com/35559153/222371036-bcf1dd3c-64dc-4cf2-ab15-53f671b07bf5.png) 是要清除整行的数据，这种方式不生效

**Comment by believeZJP** [comment]
> 如果你想同时修改ID和Product两列，你需要改这些地方，绑定formRef 再通过formRef控制数据
> 
> ![image](https://user-images.githubusercontent.com/35559153/222389222-36319d2f-5292-49f2-b264-418c86a99ef3.png)
> 
> ![image](https://user-images.githubusercontent.com/35559153/222400459-f4949674-be76-4a6e-8881-dfd927443823.png)

能提供一个代码链接吗

**Comment by XueMeijing** [comment]
你可以在线diff下改了哪些地方 https://tool.chinaz.com/tools/diff

```
import React, { useRef, useState } from "react";
import {
  ProForm,
  EditableProTable,
  ProColumns,
  ProFormField,
  ProCard,
  ProFormItem
} from "@ant-design/pro-components";
import enUS from "antd/lib/locale/en_US";
import { ConfigProvider, Input, Button } from "antd";

const defaultData = Array.from(Array(3), (_, index) => {
  return {
    id: index,
    product_name: `Product ${index}`
  };
});

export default function Page() {
  const [dataSource, setDataSource] = useState(defaultData);
  const [editableKeys, setEditableRowKeys] = useState<React.Key[]>(() =>
    defaultData.map((item) => item.id)
  );
  const TagList = ({ value, onChange, index, record }) => {
    const [inputValue, setInputValue] = useState(value);
    const handleInputChange = (e) => {
      setInputValue(e.target.value);
      onChange?.(e.target.value);
    };
    return (
      <div>
        <Input
          // ref={ref}
          type="text"
          style={{ width: 158 }}
          value={inputValue}
          // value={value}
          onChange={handleInputChange}
        />
        <Button
          onClick={() => {
            dataSource[index] = { product_name: "", id: Math.random() };
            console.log(dataSource, "结果");
            setDataSource([...dataSource]);
            formRef?.current?.setFieldsValue({
              table: [...dataSource]
            });
            setEditableRowKeys(dataSource.map((item) => item.id));
          }}
        >
          点击清除
        </Button>
      </div>
    );
  };

  const columns: ProColumns[] = [
    {
      dataIndex: "id",
      title: "ID",
      valueType: "digit",
      renderFormItem: ({ index }, { record }) => {
        return <TagList index={index} record={record} />;
      }
    },
    { dataIndex: "product_name", title: "Product", valueType: "text" }
  ];
  const formRef = useRef();
  return (
    <ConfigProvider locale={enUS}>
      <ProCard>
        <ProForm
          initialValues={{
            table: defaultData
          }}
          formRef={formRef}
        >
          <ProFormItem trigger="onValuesChange" name="table">
            <EditableProTable
              formItemProps={{
                label: "Product list"
              }}
              rowKey="id"
              scroll={{
                y: 340
              }}
              columns={columns}
              recordCreatorProps={{
                record: (index) => {
                  return { id: index };
                }
              }}
              editable={{
                type: "multiple",
                editableKeys,
                onChange: setEditableRowKeys,
                onValuesChange: (record, recordList) => {
                  console.log(record, recordList, "bian");
                  setDataSource(recordList);
                  // setApplyAftersaleEditableKeys(recordList.map(i => i.id));
                }
              }}
            />
          </ProFormItem>

          <ProFormField
            ignoreFormItem
            fieldProps={{
              style: {
                width: "100%"
              }
            }}
            mode="read"
            valueType="jsonCode"
            text={JSON.stringify(dataSource)}
          />
        </ProForm>
      </ProCard>
    </ConfigProvider>
  );
}

```

**Comment by believeZJP** [comment]
> 你可以在线diff下改了哪些地方 https://tool.chinaz.com/tools/diff
> 
> ```
> import React, { useRef, useState } from "react";
> import {
>   ProForm,
>   EditableProTable,
>   ProColumns,
>   ProFormField,
>   ProCard,
>   ProFormItem
> } from "@ant-design/pro-components";
> import enUS from "antd/lib/locale/en_US";
> import { ConfigProvider, Input, Button } from "antd";
> 
> const defaultData = Array.from(Array(3), (_, index) => {
>   return {
>     id: index,
>     product_name: `Product ${index}`
>   };
> });
> 
> export default function Page() {
>   const [dataSource, setDataSource] = useState(defaultData);
>   const [editableKeys, setEditableRowKeys] = useState<React.Key[]>(() =>
>     defaultData.map((item) => item.id)
>   );
>   const TagList = ({ value, onChange, index, record }) => {
>     const [inputValue, setInputValue] = useState(value);
>     const handleInputChange = (e) => {
>       setInputValue(e.target.value);
>       onChange?.(e.target.value);
>     };
>     return (
>       <div>
>         <Input
>           // ref={ref}
>           type="text"
>           style={{ width: 158 }}
>           value={inputValue}
>           // value={value}
>           onChange={handleInputChange}
>         />
>         <Button
>           onClick={() => {
>             dataSource[index] = { product_name: "", id: Math.random() };
>             console.log(dataSource, "结果");
>             setDataSource([...dataSource]);
>             formRef?.current?.setFieldsValue({
>               table: [...dataSource]
>             });
>             setEditableRowKeys(dataSource.map((item) => item.id));
>           }}
>         >
>           点击清除
>         </Button>
>       </div>
>     );
>   };
> 
>   const columns: ProColumns[] = [
>     {
>       dataIndex: "id",
>       title: "ID",
>       valueType: "digit",
>       renderFormItem: ({ index }, { record }) => {
>         return <TagList index={index} record={record} />;
>       }
>     },
>     { dataIndex: "product_name", title: "Product", valueType: "text" }
>   ];
>   const formRef = useRef();
>   return (
>     <ConfigProvider locale={enUS}>
>       <ProCard>
>         <ProForm
>           initialValues={{
>             table: defaultData
>           }}
>           formRef={formRef}
>         >
>           <ProFormItem trigger="onValuesChange" name="table">
>             <EditableProTable
>               formItemProps={{
>                 label: "Product list"
>               }}
>               rowKey="id"
>               scroll={{
>                 y: 340
>               }}
>               columns={columns}
>               recordCreatorProps={{
>                 record: (index) => {
>                   return { id: index };
>                 }
>               }}
>               editable={{
>                 type: "multiple",
>                 editableKeys,
>                 onChange: setEditableRowKeys,
>                 onValuesChange: (record, recordList) => {
>                   console.log(record, recordList, "bian");
>                   setDataSource(recordList);
>                   // setApplyAftersaleEditableKeys(recordList.map(i => i.id));
>                 }
>               }}
>             />
>           </ProFormItem>
> 
>           <ProFormField
>             ignoreFormItem
>             fieldProps={{
>               style: {
>                 width: "100%"
>               }
>             }}
>             mode="read"
>             valueType="jsonCode"
>             text={JSON.stringify(dataSource)}
>           />
>         </ProForm>
>       </ProCard>
>     </ConfigProvider>
>   );
> }
> ```

感谢问题解决了，详细的代码链接<https://codesandbox.io/s/editableprotable-performance-issue-forked-jxmkdm?file=/App.tsx:0-4016>

**Comment by believeZJP** [comment]
> 你可以在线diff下改了哪些地方 https://tool.chinaz.com/tools/diff
> 
> ```
> import React, { useRef, useState } from "react";
> import {
>   ProForm,
>   EditableProTable,
>   ProColumns,
>   ProFormField,
>   ProCard,
>   ProFormItem
> } from "@ant-design/pro-components";
> import enUS from "antd/lib/locale/en_US";
> import { ConfigProvider, Input, Button } from "antd";
> 
> const defaultData = Array.from(Array(3), (_, index) => {
>   return {
>     id: index,
>     product_name: `Product ${index}`
>   };
> });
> 
> export default function Page() {
>   const [dataSource, setDataSource] = useState(defaultData);
>   const [editableKeys, setEditableRowKeys] = useState<React.Key[]>(() =>
>     defaultData.map((item) => item.id)
>   );
>   const TagList = ({ value, onChange, index, record }) => {
>     const [inputValue, setInputValue] = useState(value);
>     const handleInputChange = (e) => {
>       setInputValue(e.target.value);
>       onChange?.(e.target.value);
>     };
>     return (
>       <div>
>         <Input
>           // ref={ref}
>           type="text"
>           style={{ width: 158 }}
>           value={inputValue}
>           // value={value}
>           onChange={handleInputChange}
>         />
>         <Button
>           onClick={() => {
>             dataSource[index] = { product_name: "", id: Math.random() };
>             console.log(dataSource, "结果");
>             setDataSource([...dataSource]);
>             formRef?.current?.setFieldsValue({
>               table: [...dataSource]
>             });
>             setEditableRowKeys(dataSource.map((item) => item.id));
>           }}
>         >
>           点击清除
>         </Button>
>       </div>
>     );
>   };
> 
>   const columns: ProColumns[] = [
>     {
>       dataIndex: "id",
>       title: "ID",
>       valueType: "digit",
>       renderFormItem: ({ index }, { record }) => {
>         return <TagList index={index} record={record} />;
>       }
>     },
>     { dataIndex: "product_name", title: "Product", valueType: "text" }
>   ];
>   const formRef = useRef();
>   return (
>     <ConfigProvider locale={enUS}>
>       <ProCard>
>         <ProForm
>           initialValues={{
>             table: defaultData
>           }}
>           formRef={formRef}
>         >
>           <ProFormItem trigger="onValuesChange" name="table">
>             <EditableProTable
>               formItemProps={{
>                 label: "Product list"
>               }}
>               rowKey="id"
>               scroll={{
>                 y: 340
>               }}
>               columns={columns}
>               recordCreatorProps={{
>                 record: (index) => {
>                   return { id: index };
>                 }
>               }}
>               editable={{
>                 type: "multiple",
>                 editableKeys,
>                 onChange: setEditableRowKeys,
>                 onValuesChange: (record, recordList) => {
>                   console.log(record, recordList, "bian");
>                   setDataSource(recordList);
>                   // setApplyAftersaleEditableKeys(recordList.map(i => i.id));
>                 }
>               }}
>             />
>           </ProFormItem>
> 
>           <ProFormField
>             ignoreFormItem
>             fieldProps={{
>               style: {
>                 width: "100%"
>               }
>             }}
>             mode="read"
>             valueType="jsonCode"
>             text={JSON.stringify(dataSource)}
>           />
>         </ProForm>
>       </ProCard>
>     </ConfigProvider>
>   );
> }
> ```
按照你的提示稍微改了一下，如果不改变id的话还是要用`<ProFormItem noStyle>`的方式才能清除，代码链接<https://codesandbox.io/s/editableprotable-performance-issue-forked-jxmkdm?file=/App.tsx>

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


非常感谢你的分享和修改，这个问题看来需要组件内部去做一些处理才能更好解决，同时也提醒我们在使用组件时需要仔细查看官方文档和API，避免踩坑。
