### ISSUE TITLE
🧐[问题]怎么从外部传入数据来调用CreateForm实现代码内部的setState，从而从CreateForm外面自定义setState的值？

### ISSUE THREAD

**Issue by fengnex** [ant-design/pro-components#670]
### 🧐 问题描述
需求：弹出form上一个第三方组件的内容需要通过setState的方式来对不同的情况设置不同的值。初始值从form之外传入，不同的操作对象，弹出form时传入的数据不同。
form参考Antd Pro使用ProTable后的CreateForm实现。

问题：虽然可以通过类似columns={columns}这样的方式向Form传递数据，但是form这样获得的数据是个常量，因此导致第三方组件的值无法响应用户在form上的操作来相应地变化，原因是这个组件显示的内容只能通过setState的方式改变。
为了解决这个问题，目前能想到的方案是希望能在form实现代码中的setState接收从form外部传入的数据，但怎么才能实现呢？
也就是说：怎么才能在从外部弹出form时，去同步调用CreateForm内部的方法并传入数据？

下面的CreateForm 是采用ProTable之后，官方提供的代码。另外，虽然可以通过类似columns={columns}这样的方式向Form传递数据，但是form这样获得的数据是个常量：
```
<CreateForm onCancel={() => handleModalVisible(false)} modalVisible={createModalVisible}>
                <ProTable<TableListItem, TableListItem>
                    onSubmit={async value => {
                        const success = await handleAdd(value);
                        if (success) {
                            handleModalVisible(false);
                            if (actionRef.current) {
                                actionRef.current.reload();
                            }
                        }
                    }}
                    rowKey="key"
                    type="form"
                    columns={columns}
                    rowSelection={{}}
                />
            </CreateForm>
```

**Comment by fengnex** [comment]
请熟悉的同行指教！

**Comment by chenshuai2144** [comment]
听起来可以试试 formRef

**Comment by fengnex** [comment]
@chenshuai2144 谢谢！
能否提供一个示例供参考？

**Comment by chenshuai2144** [comment]
Demo里面有

**Comment by fengnex** [comment]
@chenshuai2144 
查了资料，看起来没办法，原因：
1、我需要在一个类A里面通过类似下面的代码调用、控制弹窗（弹窗的实现类是RunEval）：
{scripts && Object.keys(scripts).length ? (
        <RunEval
          onCancel={() => {
            handleRunModalVisible(false);
          }}
          runModalVisible={runModalVisible}
          scripts={scripts} 
          。。。
        />
      ) : null}
现在实际需要在打开弹窗时，调用RunEval里面的一个方法。
2、弹窗相关的主要实现（这里虽然能对Modal加ref，但是无法在RunEval外面调用）：
const RunEval: React.FC<CreateFormProps> = props => {  
     return (
    <Modal width={1024} ref='evalForm'
      destroyOnClose
      title="运行评测"
      visible={runModalVisible}
      onCancel={() => handleRunModalVisible(false)}
      footer={renderFooter()}
    >
      <div style={{ textAlign: 'left' }}>    
          。。。
      </div>
}
怎么才能从外面（打开弹窗的时候）调用RunEval的方法呢？

**Comment by fengnex** [comment]
Pro组件现在的方法与传统的Web开发差异较大，导致以往的做法无法在用了Pro+react的项目中复用，希望官方能提供上面的问题相关的资源、链接，谢谢

**Comment by chenshuai2144** [comment]
@fengnex  用 ref 一层层传就好了。
react 的 多组件传递要么用 provide 要么用 ref 透传

**Comment by fengnex** [comment]
利用第三方组件的事件处理机制解决了--这个做法还是依靠对其他技术的掌握推出来的。

提点小建议：使用antd包括Pro的过程中，体会到.Net、JDK、iOS、安卓等框架的成熟和资料丰富，可以说从未出现使用antd的过程中遇到的一些问题很难解决又缺少资源的情况。一方面确实文档挺丰富了，但是相对于国际上的那些知名企业的同类产品，差距可以说还是“明显”；
另外象Pro自身有些后继乏力，同时对于一些复杂、深入的问题，非常缺少相关资源，官方可以考虑怎么逐步改善。

**Comment by fengnex** [comment]
谢谢chenshuai2144！
作为antd和Pro的资深用户，昨天说的那些是希望能帮助到这些工具的发展。
国内做这块的、做到这个程度的也就这里了，点赞！

**Comment by chenshuai2144** [comment]
国内的开发者的社区太小了，大部分也没有贡献的想法。
再加上我们很少有专门的文档岗位，所以很难写出非常高质量且数量大的文档

**Comment by itsuki0927** [comment]
其实很多时候,自己懂那个意思,就是不知道怎么去表达,或者说表述不准确,会导致文档读起来有点难以理解

**Comment by chenshuai2144** [comment]
@itsuki0927  我邮箱是 qixian.cs@hotamil*com

方便发一下联系方式，加个钉钉吗？
