### ISSUE TITLE
🧐[问题]如何在开发模式下打包（watch 模式），并输出到磁盘，供 npm link 使用。

### ISSUE THREAD

**Issue by kaneruan** [ant-design/pro-components#6702]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
如何在开发模式下打包（watch 模式），并输出到磁盘，供 npm link 使用。

### 💻 示例代码

无

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
你可以使用 webpack 中的 watch 模式来实现开发模式下持续打包，同时使用 output.path 配置项指定打包输出的目录。然后使用 npm link 命令将该输出目录链接到本地包下。
简单的 webpack 配置示例：

```javascript
const path = require('path');

module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist') // 指定打包输出目录为 dist
  },
  watch: true, // 开启 watch 模式
  mode: 'development'
  // ...其他配置项
}
```

具体操作步骤如下：
1. 在你的项目根目录下执行 `npm init` 初始化一个 `package.json` 文件
2. 安装 webpack 和 webpack-cli 依赖，执行 `npm install webpack webpack-cli --save-dev`
3. 使用以上 webpack 配置文件，创建一个 `webpack.config.js` 文件，并放在项目根目录下
4. 在终端中进入项目根目录，使用 `npm link` 命令链接到 webpack 打包输出的 dist 目录，具体操作如下：

   ```javascript
   // 在项目根目录下执行
   npm link ./dist
   
   // 此处的 ./dist 就是你在 webpack 配置文件中设置的 output.path
   // npm link 后终端会提示链接成功
   ```

5. 在项目任意目录下使用该本地包，先执行 `npm link <your-package-name>`，然后在项目中直接引入包即可

   ```javascript
   // 以 React 为例，假设你的本地包名称为 my-react-component
   // 进入项目目录下，先执行 npm link my-react-component
   // 然后在项目中直接引入并使用你的组件即可
   import MyComponent from 'my-react-component';
   ```

参考文档：
- [Webpack watch API](https://webpack.js.org/api/node-watch-api/)
- [Webpack output 配置项](https://webpack.js.org/configuration/output/)
 > This sentence can be automatically replied to using ChatGPT.
 > 此回复基于 ChatGPT 自动生成。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


希望以上回答能够解决你的问题，如果还有其他问题可以继续提问哦~

**Comment by chenshuai2144** [comment]
最好不要 components 的编译速度不是很给力
如果非要这么做，你要使用 `build -w`
