### ISSUE TITLE
🐛[BUG]ConfigProvider 中theme设置Design Token， controlHeight 属性对ProFormText无效

### ISSUE THREAD

**Issue by zzperfect** [ant-design/pro-components#6705]
### 🧐 问题描述

Antd提供的ConfigProvider全局配置主题设置控件高度，对ProFormText无效

### 💻 示例代码

复现网址：https://codesandbox.io/s/form-de-layout-qie-huan-forked-blbm0d?file=/App.tsx

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/33208512/222645107-60908d54-eae2-4205-b7a7-af3969d955b6.png)

**Comment by chenshuai2144** [comment]
你好，关于ConfigProvider设置控件高度对ProFormText无效的问题，可能是ProFormText的style被覆盖了。目前比较好的解决方法是通过覆盖ProFormText里的样式来解决。

在App.tsx这个文件中，可以添加一个自定义的样式，在style里定义ProFormText的高度样式。

```jsx
import { ConfigProvider, Form, Input } from "antd";
import "antd/dist/antd.css";
import ProForm, { ProFormText } from "@ant-design/pro-form";
import zhCN from "antd/lib/locale/zh_CN";
import "./index.css";

function App() {
  return (
    <ConfigProvider locale={zhCN} componentSize="middle">
      <ProForm>
        <ProFormText label="名称" name="name" />
        <Form.Item label="标准名称" name="nickName">
          <Input />
        </Form.Item>
      </ProForm>
    </ConfigProvider>
  );
}

export default App;
```

在index.css中添加样式。

```css
.ant-form-item-control-input {
  height: 40px !important;
}
```

另外，我们可以通过查看ProFormText的文档，可以发现它的props里有一个fieldProps，可以直接将样式传递进去。

```jsx
<ProFormText label="名称" name="name" fieldProps={{ style: { height: 40 } }} />
```

以上两种方法都可以解决ConfigProvider里控件高度对ProFormText无效的问题。希望能够帮助你解决问题。
 > This sentence can be automatically replied to using ChatGPT.
 > 此回复基于 ChatGPT 自动生成。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。

**Comment by chenshuai2144** [comment]
[`height: token.controlHeight,`](https://github.com/ant-design/ant-design/blob/master/components/input/style/index.ts#L146)

要用 lineHeigth 来控制
