### ISSUE TITLE
🐛[BUG] pro在 chrome 83 无法正常使用

### ISSUE THREAD

**Issue by xiefengnian** [ant-design/pro-components#6708]
### 🐛 bug 描述

运行环境：
- chrome83 
- @ant-design/pro-components: ^2.0.1
- antd: ^5.0.0

现象：
pro 整体错乱无法使用

### 📷 复现步骤

1. `$ pnpm create umi`，初始化 antd-design pro 项目
2. 修改 .umirc：
```ts
legacy: { buildOnly: false, checkOutput: true },
targets: {
  chrome: 83,
},
```
3. 启动项目，在 chrome83 中打开

### 🏞 期望结果

正常兼容 chrome

### 💻 复现代码

无

### 🚑 其他信息

<img width="1589" alt="image" src="https://user-images.githubusercontent.com/20136563/222659707-d49370bf-d32b-4fe1-b136-9bac81d7b231.png">

**Comment by chenshuai2144** [comment]
很抱歉，您提供的问题并不能完全看出来是前端问题，但是根据您提供的截图，我们可以看到整个页面布局错乱，可能是由于样式层面的问题导致的。建议您可以先检查样式是否引入有误或者存在冲突等问题。

如果确认是样式问题导致的，您可能需要深入了解 Ant Design Pro 组件库的内部样式处理方式，以便定位问题所在。可以参考 Ant Design 官网提供的样式覆盖方式，将样式的优先级提升，消除样式冲突问题。

另外，您提供的环境版本比较老，可以尝试升级组件包或者切换到相对稳定的版本进行测试处理。若还有问题，可以提供更多详细信息以便更好地定位解决问题。
 > This sentence can be automatically replied to using ChatGPT.
 > 此回复基于 ChatGPT 自动生成。

**Comment by xiefengnian** [comment]
已经解决了：按这个文档配置

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


非常感谢您的更新和分享，确实，按照文档中提供的方法提高 antd 的样式优先级是一个不错的解决方案。同时，按照您提供的配置方式在 `umi` 项目中进行配置，也可以避免前端问题出现：

```ts
import { StyleProvider, legacyLogicalPropertiesTransformer } from '@ant-design/cssinjs';

export function rootContainer(container: React.ReactElement) {
  return React.createElement(
    StyleProvider,
    {
      hashPriority: 'high',
      transformers: [legacyLogicalPropertiesTransformer],
    },
    container,
  );
}
```

感谢您仔细阅读和遵循官方文档的建议，欢迎在日后有任何前端问题再次向我们求助。
