### ISSUE TITLE
🐛[BUG] ProTable 官网示例UI抖动

### ISSUE THREAD

**Issue by conorzhong** [ant-design/pro-components#6709]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

UI抖动

https://user-images.githubusercontent.com/39456642/222663994-138d6bab-4636-4e82-ac51-aa6602e57e55.mov

### 📷 复现步骤

1. 打开官网
2. 找到 列表工具栏-标题下拉菜单
3. 窗口尺寸如图
<img width="173" alt="Snipaste_2023-03-03_15-56-21" src="https://user-images.githubusercontent.com/39456642/222664562-3574c79c-4d86-49ab-9d00-74f0d7e67839.png">

### 🏞 期望结果

不抖动

### 💻 复现代码

无

### © 版本信息

- ProComponents 版本: 官网
- umi 版本 无
- 浏览器环境 Microsoft Edge 版本 110.0.1587.50 (正式版本) (arm64)
- 开发环境 [e.g. mac OS] macOS

**Comment by chenshuai2144** [comment]
感谢你向我提问。根据你所提供的信息，我了解到你在使用 ProTable 组件时出现了 UI 抖动的问题。
针对此问题，我建议你试试以下方法：

1. 升级 ProTable 版本到最新稳定版本，看是否能够解决问题。ProTable 组件在不断维护和更新中，新版本可能会修复一些已知的 Bug，你可以通过到官方网站 https://protable.ant.design/ 中查看最新版本的使用说明和更新记录。
   
2. 可以尝试了解一下 CSS 相关知识，尤其是关于 flex、position、overflow 等属性的使用。如果列表工具栏的标题下拉菜单的高度发生了变化，有可能是因为相关元素的定位或布局方式不当，导致页面出现了抖动。你可以试试在调整元素大小时，是否需要进行一些 CSS 调整。
   
3. 如果以上方法都未能解决问题，那么建议你将复现步骤、期望结果、复现代码等信息反馈给 ProTable 组件的开发者，以获得更详细的帮助和指导。你可以在 https://github.com/ant-design/pro-table/issues 中提 issue，当你提交 issue 时，最好提供能够复现问题的在线示例或者代码片段，这样开发者就可以更快地定位问题并提供解决方案。

希望以上方法能够帮助你解决问题。如有其他问题，欢迎随时向我提问。
 > This sentence can be automatically replied to using ChatGPT.
 > 此回复基于 ChatGPT 自动生成。

**Comment by Muluk-m** [comment]
我也出现了同样的问题,在我的项目中, 根据我的观察好像是   toolbar.menu.type =  'tab' 时, tab的label宽度初始化后, 再改变他,会导致这个问题

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


根据你提供的信息，我可以尝试给出以下解决方案：

1. 检查样式是否正确：建议检查 CSS 样式表中是否设置了合适的宽度和高度，以及是否包含了重复的样式规则。你可以使用浏览器的开发者工具来检查这些问题。如果样式表出现了问题，可能会导致标签宽度初始化后再改变导致 UI 抖动。

2. 重写 tab 的样式：如果问题确实是由于 tab 的 label 宽度初始化后再改变引起的，可以尝试通过重新编写标签的样式来解决问题。你可以根据需要修改标签的尺寸或者布局方式，并通过 CSS 样式表来实现。同时，建议设置一个固定宽度，而不是使用百分比宽度。

3. 提交 issue：如果以上的方法都无法解决你的问题，那么你可以在 ProTable 的 Github 仓库中提交一个 issue，以便得到更专业的帮助。在提交 issue 时，你可以提供尽可能详细的信息，在复现步骤、期望结果、复现代码等方面提供尽可能多的细节，有利于开发者定位问题并提供解决方案。

如果这些方法都没有解决你的问题，建议查看 ProTable 的文档和源代码，了解其内部原理以及更好地使用它。

**Comment by chenshuai2144** [comment]
发布了新的版本使用了 flex 来解决宽度问题。

目测是百分百导致的宽度一直变化，然后tabs就一直重新渲染

**Comment by chenshuai2144** [comment]
修复了
