### ISSUE TITLE
antd v5 : Unable to modify the colors of the sidebar menu to correspond with the theme color,

### ISSUE THREAD

**Issue by beeena** [ant-design/pro-components#6710]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 Problem Description

I am currently utilizing ProLayout in Ant Design Pro. However, after upgrading to antd v5, I am encountering an issue where I am unable to modify the colors of the sidebar menu to correspond with the theme color. This appears to be a result of the removal of Less variables in v5, as opposed to v4 where the color modification was possible without any complications.

### 💻 sample code

```
 <ProLayout
        title={settings?.title}
        token={{
          colorPrimary: "var(--ant-primary-color)",
          header: {
            colorTextMenuSelected: "var(--ant-primary-color)",
            colorBgMenuItemSelected: "var(--ant-primary-1)",
            colorBgMenuItemHover: "var(--ant-primary-1)",
            colorBgRightActionsItemHover: "var(--ant-primary-color)",
            colorTextMenuActive: "var(--ant-primary-color)",
          },
          sider: {
            colorTextMenuActive: "var(--ant-primary-color)",
            colorTextMenuSelected: "var(--ant-primary-color)",
            colorBgMenuItemSelected: "var(--ant-primary-1)",
            colorBgMenuItemHover: "var(--ant-primary-1)",
            colorTextMenuItemHover: "var(--ant-primary-color)"
          }
        }}
        formatMessage={formatMessage}
        {...props}
        {...newSettings}
        onMenuHeaderClick={onMenuHeaderClick}
        menuItemRender={menuItemRender}
        menuContentRender={menuContentRender}
        menuFooterRender={menuFooterRender}
        breadcrumbRender={breadCrumbs}
        itemRender={itemRender}
        footerRender={GlobalFooter}
      >
        {children}
      </ProLayout>
      <SettingDrawer
        settings={newSettings}
        onSettingChange={onSettingChange}
        enableDarkTheme
        disableUrlParams={true}
      />
```

### What is expected?

Is there a specific method or approach that can be employed to change the colors of the sidebar menu to align with the theme color in antd v5? In other words, are there any specific guidelines to follow when attempting to modify the sidebar colors?

### 🚑 other information

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | "react": "18.0.0" |
| System | ubuntu 20 |
| Browser | Google Chrome |

**Comment by chenshuai2144** [comment]
Hi there! It sounds like you're running into an issue with modifiying the colors of the ProLayout sidebar menu in Ant Design Pro after upgrading to antd v5.

With the removal of Less variables in v5, it seems that the process for modifying the colors has changed. However, there are still ways to modify the colors of components in Ant Design Pro. Here are a few possible solutions:

1. Use CSS variables to define colors in your application. This way, you can define your theme color in one place and use it throughout your application. Here's an example:

```
:root {
  --primary: #1890ff; // define your theme color as a CSS variable
}

.ant-pro-sider-menu .ant-menu-item-selected, // modify the color of the selected menu item
.ant-pro-sider-menu .ant-menu-item:hover { // modify the color of the menu item on hover
  background-color: var(--primary);
  color: #fff;
}
```

2. Utilize the `theme` property in the `ConfigProvider` component to define your theme colors. Here's an example:

```
<ConfigProvider theme={{ primaryColor: '#1890ff' }}> // define your primary color here
  <ProLayout>
    // your layout code here
  </ProLayout>
</ConfigProvider>
```

Additionally, you may want to take a look at the Ant Design Pro documentation for more information on customizing the theme in v5: https://beta-pro.ant.design/docs/theme-cn.

I hope this helps! Let me know if you have any further questions.
 > This sentence can be automatically replied to using ChatGPT.
 > 此回复基于 ChatGPT 自动生成。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


Hello! It seems that you are facing an issue with modifying the colors of the ProLayout sidebar menu in Ant Design Pro after upgrading to antd v5.

With the removal of Less variables in v5, you can no longer modify the colors in the same way as before. However, there are still some methods that you can use to accomplish this. Here are a few possible solutions:

1. Use CSS variables to define colors in your application. This way, you can define your theme color in one place and use it throughout your application. Here's an example:

```
:root {
  --primary: #1890ff; // define your theme color as a CSS variable
}

.ant-pro-sider-menu .ant-menu-item-selected, // modify the color of the selected menu item
.ant-pro-sider-menu .ant-menu-item:hover { // modify the color of the menu item on hover
  background-color: var(--primary);
  color: #fff;
}
```

2. Use the `theme` property in the `ConfigProvider` component to define your theme colors. Here's an example:

```
<ConfigProvider theme={{ primaryColor: '#1890ff' }}> // define your primary color here
  <ProLayout>
    // your layout code here
  </ProLayout>
</ConfigProvider>
```

You might want to take a closer look at the Ant Design Pro documentation to learn more about how to customize the theme in v5: https://beta-pro.ant.design/docs/theme-cn.

I hope this helps! Feel free to let me know if you have any other questions.

**Comment by veeramarni** [comment]
link is broken https://beta-pro.ant.design/docs/theme-cn.

**Comment by DavidNorena** [comment]
why is this closed? the issue is still happening look

![image](https://user-images.githubusercontent.com/26279057/235245606-2f18f960-1e3d-41af-9115-4e4989cae60b.png)

Primary color is working for antdesign but not for the pro layout components

**Comment by smi97** [comment]
Same thing here, can't change sider color with ConfigProvider

**Comment by ChikenBro** [comment]
ColorBgMenuItemSelected cannot take effect

**Comment by austyking** [comment]
It has been over 2 years and this issue is persisting. Link [https://beta-pro.ant.design/docs/theme-cn](url) is still broken
