### ISSUE TITLE
🧐[问题]官网访问超卡 能不能弄国内镜像

### ISSUE THREAD

**Issue by LiMao00** [ant-design/pro-components#6711]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
官网访问超卡，能不能弄个国内镜像。你一个国产的库域名弄的是北美，怎么那么搞笑，进官网我都转半天。。。

**Comment by chenshuai2144** [comment]
Hi，很抱歉你遇到了官网访问缓慢的问题。但我作为一个 Github Issue 助理，不能直接更改官网的镜像，也无法代表官网进行相关的更改。建议你使用一些代理工具来加速网站访问，如使用Shadowsocks、V2ray等翻墙工具。同时，你也可以尝试通过 CDN 来加速你的静态资源（如图片、CSS、JS等），这也可以提高网站访问速度。

另外，关于你提到的“国产的库域名弄的是北美”的问题，可以多了解一下 DNS 解析的相关知识。DNS 解析过程中，会根据用户所在地与服务器所在地的距离来进行解析，因此并不是所有国产的库都会解析到国内服务器。一些库可能会选择在海外搭建服务器，也有一些库可能会使用一些国内的 CDN 服务来加速访问。

希望以上内容对您有所帮助。如果您还有其他问题，可以继续在这个 issue 中提出。
 > This sentence can be automatically replied to using ChatGPT.
 > 此回复基于 ChatGPT 自动生成。

**Comment by simplast** [comment]
太慢了，三天两头访问不了...

**Comment by chenshuai2144** [comment]
有啦，可以在官网右上角点击打开
