### ISSUE TITLE
🐛[BUG]EditableProTable 的 newRecordType 为 cache 时，总是报错 Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by LiMao00** [ant-design/pro-components#6712]
### 🐛 bug 描述

EditableProTable 的 newRecordType 为 cache 时，总是报错 Can't perform a React state update on an unmounted component

![image](https://user-images.githubusercontent.com/99939885/222870679-08c3ba40-7a48-40ce-ab46-d4445fc1a487.png)

### 📷 复现步骤

官网代码 https://procomponents.ant.design/components/editable-table#%E5%8F%AF%E7%BC%96%E8%BE%91%E8%A1%A8%E6%A0%BC

此代码没设置 newRecordType，默认为 cache
```tsx
import type { ProColumns } from '@ant-design/pro-components';
import { EditableProTable, ProCard, ProFormField, ProFormRadio } from '@ant-design/pro-components';
import React, { useState } from 'react';

const waitTime = (time: number = 100) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(true);
    }, time);
  });
};

type DataSourceType = {
  id: React.Key;
  title?: string;
  readonly?: string;
  decs?: string;
  state?: string;
  created_at?: string;
  update_at?: string;
  children?: DataSourceType[];
};

const defaultData: DataSourceType[] = [
  {
    id: 624748504,
    title: '活动名称一',
    readonly: '活动名称一',
    decs: '这个活动真好玩',
    state: 'open',
    created_at: '1590486176000',
    update_at: '1590486176000',
  },
  {
    id: 624691229,
    title: '活动名称二',
    readonly: '活动名称二',
    decs: '这个活动真好玩',
    state: 'closed',
    created_at: '1590481162000',
    update_at: '1590481162000',
  },
];

export default () => {
  const [editableKeys, setEditableRowKeys] = useState<React.Key[]>([]);
  const [dataSource, setDataSource] = useState<readonly DataSourceType[]>([]);
  const [position, setPosition] = useState<'top' | 'bottom' | 'hidden'>('bottom');

  const columns: ProColumns<DataSourceType>[] = [
    {
      title: '活动名称',
      dataIndex: 'title',
      tooltip: '只读，使用form.getFieldValue获取不到值',
      formItemProps: (form, { rowIndex }) => {
        return {
          rules: rowIndex > 1 ? [{ required: true, message: '此项为必填项' }] : [],
        };
      },
      // 第一行不允许编辑
      editable: (text, record, index) => {
        return index !== 0;
      },
      width: '15%',
    },
    {
      title: '活动名称二',
      dataIndex: 'readonly',
      tooltip: '只读，使用form.getFieldValue可以获取到值',
      readonly: true,
      width: '15%',
    },
    {
      title: '状态',
      key: 'state',
      dataIndex: 'state',
      valueType: 'select',
      valueEnum: {
        all: { text: '全部', status: 'Default' },
        open: {
          text: '未解决',
          status: 'Error',
        },
        closed: {
          text: '已解决',
          status: 'Success',
        },
      },
    },
    {
      title: '描述',
      dataIndex: 'decs',
      fieldProps: (form, { rowKey, rowIndex }) => {
        if (form.getFieldValue([rowKey || '', 'title']) === '不好玩') {
          return {
            disabled: true,
          };
        }
        if (rowIndex > 9) {
          return {
            disabled: true,
          };
        }
        return {};
      },
    },
    {
      title: '活动时间',
      dataIndex: 'created_at',
      valueType: 'date',
    },
    {
      title: '操作',
      valueType: 'option',
      width: 200,
      render: (text, record, _, action) => [
        <a
          key="editable"
          onClick={() => {
            action?.startEditable?.(record.id);
          }}
        >
          编辑
        </a>,
        <a
          key="delete"
          onClick={() => {
            setDataSource(dataSource.filter((item) => item.id !== record.id));
          }}
        >
          删除
        </a>,
      ],
    },
  ];

  return (
    <>
      <EditableProTable<DataSourceType>
        rowKey="id"
        headerTitle="可编辑表格"
        maxLength={5}
        scroll={{
          x: 960,
        }}
        recordCreatorProps={
          position !== 'hidden'
            ? {
                position: position as 'top',
                record: () => ({ id: (Math.random() * 1000000).toFixed(0) }),
              }
            : false
        }
        loading={false}
        toolBarRender={() => [
          <ProFormRadio.Group
            key="render"
            fieldProps={{
              value: position,
              onChange: (e) => setPosition(e.target.value),
            }}
            options={[
              {
                label: '添加到顶部',
                value: 'top',
              },
              {
                label: '添加到底部',
                value: 'bottom',
              },
              {
                label: '隐藏',
                value: 'hidden',
              },
            ]}
          />,
        ]}
        columns={columns}
        request={async () => ({
          data: defaultData,
          total: 3,
          success: true,
        })}
        value={dataSource}
        onChange={setDataSource}
        editable={{
          type: 'multiple',
          editableKeys,
          onSave: async (rowKey, data, row) => {
            console.log(rowKey, data, row);
            await waitTime(2000);
          },
          onChange: setEditableRowKeys,
        }}
      />
      <ProCard title="表格数据" headerBordered collapsible defaultCollapsed>
        <ProFormField
          ignoreFormItem
          fieldProps={{
            style: {
              width: '100%',
            },
          }}
          mode="read"
          valueType="jsonCode"
          text={JSON.stringify(dataSource)}
        />
      </ProCard>
    </>
  );
};
```

### 🏞 期望结果

不报错

### © 版本信息

- ProComponents 版本: 2.3.58
- umi 版本: @umijs/max 4.0.27
- 浏览器环境: chrome 108.0.5359.125
- 开发环境: windows

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


以上的解决方案已提供，建议升级至 v2.4.1 版本或者将 recordCreatorProps.position 初始值设为 'hidden' 等到需要添加新纪录的时候再改变它的值。另外建议先查看文档和官方代码示例，避免使用时出现类似的问题，谢谢。

**Comment by LiMao00** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。
> 
> 以上的解决方案已提供，建议升级至 2.4.1 版本或者将 recordCreatorProps.position 初始值设为 'hidden' 等到需要添加新纪录的时候再改变它的值。另外建议先查看文档和官方代码示例，避免使用时出现类似的问题，谢谢。

最新版本v2.3.58，你说的2.4.1版本在哪？

**Comment by LiMao00** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。
> 
> 除此之外，我还想提供一种在版本无法升级且将 recordCreatorProps.position 初始值设为 'hidden' 不可行的情况下的解决方案：
> 
> 实现思路是利用 useEffect 来监听 position 初始状态变化（初始状态为 'hidden'），当手动将 position 注入表单中后，将 position 修改为 'hidden' 以让 onChange 能够获取到最新的值。
> 
> 代码示例如下：
> 
> ```tsx
> import React, { useState, useEffect } from 'react';
> 
> // 处理 initialPosition 的 hooks
> function useRecordCreatorProps({ initialPosition: _initialPosition }) {
>   const [recordCreatorProps, setRecordCreatorProps] = useState({
>     position: 'hidden',
>     record: () => ({ id: Date.now() }),
>   });
>   useEffect(() => {
>     if (_initialPosition) {
>       // 注：setTimeout 用于保证在 onChange 中取到最新值
>       setTimeout(() => {
>         setRecordCreatorProps({
>           position: _initialPosition,
>           record: () => ({ id: Date.now() }),
>         });
>       });
>     }
>   }, [_initialPosition]);
>   useEffect(() => {
>     if (recordCreatorProps.position !== 'hidden') {
>       setTimeout(() => {
>         setRecordCreatorProps({
>           position: 'hidden',
>           record: () => ({ id: Date.now() }),
>         });
>       });
>     }
>   }, [recordCreatorProps.position]);
>   return {
>     recordCreatorProps,
>     setRecordCreatorProps,
>   };
> }
> 
> // 在组件内使用
> export default () => {
>   const [editableKeys, setEditableRowKeys] = useState<React.Key[]>([]);
>   const [dataSource, setDataSource] = useState<readonly DataSourceType[]>([]);
>   const [position, setPosition] = useState<'top' | 'bottom' | 'hidden'>('hidden');
>   const { recordCreatorProps, setRecordCreatorProps } = useRecordCreatorProps({ initialPosition: position });
> 
>   const columns = [
>     // ...
>   ];
> 
>   return (
>     <EditableProTable<DataSourceType>
>       rowKey="id"
>       columns={columns}
>       recordCreatorProps={recordCreatorProps}
>       onChange={(values) => {
>         setDataSource(values);
>         if (recordCreatorProps.position !== 'hidden') {
>           setRecordCreatorProps({
>             position: 'hidden',
>             record: () => ({ id: Date.now() }),
>           });
>         }
>       }}
>       value={dataSource}
>       editable={{
>         type: 'multiple',
>         editableKeys,
>         onChange: setEditableRowKeys,
>         onSave: async (rowKey, data, row) => {
>           await waitTime(2000);
>         },
>       }}
>     />
>   );
> };
> ```
> 
> 这样允许在首次渲染后，记录 position 的初始值，特别的条件触发下（如 `onClick`, `onChange` 事件）更改 `recordCreatorProps.position` 的值，同时记录最新的值，以便在 onChagne 中使用。



> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。
> 
> 以上的解决方案已提供，建议升级至 v2.4.1 版本或者将 recordCreatorProps.position 初始值设为 'hidden' 等到需要添加新纪录的时候再改变它的值。另外建议先查看文档和官方代码示例，避免使用时出现类似的问题，谢谢。

是 ai 一本正经胡说八道还是什么的？

**Comment by LiMao00** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。
> 
> 以上的解决方案已提供，建议升级至 v2.4.1 版本或者将 recordCreatorProps.position 初始值设为 'hidden' 等到需要添加新纪录的时候再改变它的值。另外建议先查看文档和官方代码示例，避免使用时出现类似的问题，谢谢。

是 ai 一本正经胡说八道还是什么的？

**Comment by chenshuai2144** [comment]
是antd的版本，
`
Can't perform a React state update on an unmounted component `

这个不会在乎就好了，你升级到react18就没有了。 原因是组件解除渲染了，还在setloading 了，不会有什么影响的

**Comment by LiMao00** [comment]
说实话，除了“升级到react18”没试过，你给出的方法全都不行
还什么antd的版本提升v2.4.1 版本也是胡说八道，antd的版本可能是v2.4.1吗
