### ISSUE TITLE
🧐[问题]ProTable columns 设置 valueType: dateRange ， fieldProps: { presets: [...] } ，无法展示预设时间范围快捷选择

### ISSUE THREAD

**Issue by AceLing** [ant-design/pro-components#6713]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

ProTable columns 设置 valueType: dateRange ， fieldProps: { presets: [...] } ，无法展示预设时间范围快捷选择

### 💻 示例代码

```
{
  title: toLocale('gmtCreate'),
  dataIndex: 'gmtCreate',
  key: 'gmtCreate',
  width: 160,
  align: 'center',
  ellipsis: true,
  onFilter: false,
  initialValue: [],
  valueType: 'dateRange',
  fieldProps: {
    presets: [
      { label: 'Last 7 Days', value: [dayjs().add(-7, 'd'), dayjs()] },
      { label: 'Last 14 Days', value: [dayjs().add(-14, 'd'), dayjs()] },
      { label: 'Last 30 Days', value: [dayjs().add(-30, 'd'), dayjs()] },
      { label: 'Last 90 Days', value: [dayjs().add(-90, 'd'), dayjs()] },
    ],
  },
  search: {
    transform: (value: any) => ({ startTime: value[0], endTime: value[1] }),
  },
  render: (_, record) => (
    dayjs(record.gmtCreate).format('YYYY-MM-DD HH:mm:ss')
  ),
},
```

### 🚑 其他信息
官网效果(https://ant.design/components/date-picker-cn#components-date-picker-demo-preset-ranges)
![image](https://user-images.githubusercontent.com/7394322/222872552-7dae7fb3-785b-4e05-a1d1-af0005dc49eb.png)

示例代码效果
![image](https://user-images.githubusercontent.com/7394322/222872502-a268e1ce-ef34-420f-8a87-1595c2619d97.png)

**Comment by XueMeijing** [comment]
在antd 5.x里叫presets，在4.x叫 [ranges](https://4x.ant.design/components/date-picker-cn/#components-date-picker-demo-presetted-ranges) 你的版本应该是4.x吧

**Comment by chenshuai2144** [comment]
确实，在antd 4.x 中，预设时间范围的属性为`ranges`，`fieldProps`中的`presets`属性在antd 5.x 中。

针对您的问题，考虑到antd的版本不同，在antd 4.x 中可以使用`ranges`属性来展示预设时间范围的快捷选择。

建议修改示例代码如下：

```
{
  title: toLocale('gmtCreate'),
  dataIndex: 'gmtCreate',
  key: 'gmtCreate',
  width: 160,
  align: 'center',
  ellipsis: true,
  onFilter: false,
  initialValue: [],
  valueType: 'dateRange',
  fieldProps: {
    ranges: {
      'Last 7 Days': [dayjs().add(-7, 'd'), dayjs()],
      'Last 14 Days': [dayjs().add(-14, 'd'), dayjs()],
      'Last 30 Days': [dayjs().add(-30, 'd'), dayjs()],
      'Last 90 Days': [dayjs().add(-90, 'd'), dayjs()],
    },
  },
  search: {
    transform: (value: any) => ({ startTime: value[0], endTime: value[1] }),
  },
  render: (_, record) => (
    dayjs(record.gmtCreate).format('YYYY-MM-DD HH:mm:ss')
  ),
},
```

同时，您也可以在antd 4.x 中使用`renderExtraFooter`属性来自定义展示在预设时间范围下方的额外内容，具体代码如下：

```
{
  title: 'Date',
  dataIndex: 'date',
  key: 'date',
  valueType: 'dateRange',
  fieldProps: {
    ranges: {
      'Last 7 Days': [moment().subtract(7, 'days'), moment()],
      'Last 30 Days': [moment().subtract(30, 'days'), moment()],
      'This Month': [moment().startOf('month'), moment().endOf('month')],
      'Last Month': [
        moment().subtract(1, 'month').startOf('month'),
        moment().subtract(1, 'month').endOf('month'),
      ],
    },
    renderExtraFooter: () => (
      <div>
        <a
          href="https://ant.design"
          target="_blank"
          rel="noopener noreferrer"
        >
          Extra footer content
        </a>
      </div>
    ),
  },
},
```

您可以根据自己的需求修改`ranges`和`renderExtraFooter`属性来实现预设时间范围的快捷选择界面的展示效果。

关于antd 4.x的文档，可以访问 [https://4x.ant.design/components/date-picker-cn/](https://4x.ant.design/components/date-picker-cn/)。
 > This sentence can be automatically replied to using ChatGPT.
 > 此回复基于 ChatGPT 自动生成。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


希望对您有所帮助，若还有问题可以再提出。

**Comment by AceLing** [comment]
> ranges

Thx.
