### ISSUE TITLE
🐛[BUG] 使用antd 5.3.0版本ProList报错

### ISSUE THREAD

**Issue by fnoopv** [ant-design/pro-components#6714]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
antd升级至5.3.0版本，然后使用ProList组件，页面直接报错无法渲染

### 📷 复现步骤
antd升级至5.3.0版本，然后使用ProList组件即可

### 🏞 期望结果
ProList正常渲染

### 💻 复现代码

https://codesandbox.io/s/quizzical-montalcini-ndn6il?file=/src/App.tsx

### © 版本信息

- ProComponents 版本:  2.3.58
- umi 版本 无
- 浏览器环境 chrome 110
- 开发环境 Linux Kde

**Comment by chenshuai2144** [comment]
我来试试，暂时还没有兼容 5.3.0

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


感谢您的反馈，的确在目前的 ProList 组件中，还不支持 antd 5.3.0 版本。可以先退回到 antd 5.2.0 版本，等待组件更新。

另外，ProList 主要是用于数据展示，如果只是渲染一些简单的列表，可以考虑使用 antd Table 组件，这个组件在 antd 5.3.0 版本中仍然支持，并且有更多的功能。以下是一个简单的示例：

```tsx
import { Table } from 'antd';

const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
  },
  {
    title: 'Age',
    dataIndex: 'age',
  },
  {
    title: 'Address',
    dataIndex: 'address',
  },
];

const data = [
  {
    key: '1',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
  },
  {
    key: '2',
    name: 'Jim Green',
    age: 42,
    address: 'London No. 1 Lake Park',
  },
  {
    key: '3',
    name: 'Joe Black',
    age: 32,
    address: 'Sidney No. 1 Lake Park',
  },
];

function App() {
  return (
    <Table columns={columns} dataSource={data} />
  );
}
``` 

这个组件可以满足绝大多数的前端展示需求，也已经更新了适配 antd 5.3.0 版本。希望可以帮助到您。

**Comment by chenshuai2144** [comment]
修复了，更新版本吧

**Comment by fnoopv** [comment]
收到，感谢

**Comment by iAmber** [comment]
使用 antd 5.3.0 版本 + ProList 组件，依旧报错，使用的是官方demo，ProList 组件报错

![image](https://github.com/ant-design/pro-components/assets/14261428/f96cd450-293f-4cf6-8b36-613c49b8c7ff)

![image](https://github.com/ant-design/pro-components/assets/14261428/dbb85d58-6ca2-4458-98a1-55aab3205394)
