### ISSUE TITLE
EditableProTable的maxLength选项设置0的等效于Infinity，多少有点迷惑？

### ISSUE THREAD

**Issue by hans000** [ant-design/pro-components#6715]
### 🐛 bug 描述
EditableProTable的maxLength选项设置0的等效于Infinity，有点迷惑

### 📷 复现步骤
分别配置为-1 0 Infinity 1 -2
```
<EditableProTable
     maxLength={0} />
```

```
// 源码中的逻辑
  const creatorButtonDom = useMemo(() => {
    if (maxLength && maxLength <= value?.length) {
      return false;
    }
```

### 🏞 期望结果
配置为数字正常比较，当然也可以开放一个选项专门配置Infinity或关闭的效果（毕竟Infinity不好书写）
一般来说配置-1有特殊含义：为无限制或关闭，这里可以再讨论一下配置具体配置的含义

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by hans000** [comment]
另外，该组件有value、onChange配置却没有disabled表单选项是有什么考虑吗

**Comment by chenshuai2144** [comment]
不允许为 0 好了，0没啥意义。


disable 可以用不支持编辑态来支持，api越少越好

**Comment by hans000** [comment]
> 不允许为 0 好了，0没啥意义。
> 
> disable 可以用不支持编辑态来支持，api越少越好

那小修一下吧

**Comment by chenshuai2144** [comment]
好的，针对maxLength选项为0的情况，将其判定为不限制长度，相当于不设置此选项。

另外关于是否支持disabled模式，由于EditableProTable旨在提供表格的编辑功能，所以没有提供直接的disabled选项。但是，它提供了很多与编辑相关的props，如editable、columns、recordCreatorProps等，用户可以通过设置这些props来达到禁止编辑的效果。如果需要直接禁用点击操作，可以在table上绑定一个onClick事件，在禁用时阻止冒泡即可。

代码示例：

```jsx
<EditableProTable
  // 绑定禁用
  onClick={(e) => { if (isDisabled) { e.preventDefault(); e.stopPropagation() } }}
  // 禁用时将editable置为false
  editable={!isDisabled}
  // 禁用时将新建按钮置为空
  recordCreatorProps={isDisabled ? false : recordCreatorProps}
  // 设置columns的render方法，在禁用时显示不可编辑的文本
  columns={columns.map(col => {
    if (isDisabled) {
      const { render: cRender = text => text, ...others } = col;
      return {
        render: (text, record, _, action) => {
          const cRenderResult = cRender(text, record, _, action);
          return <div style={{ color: 'gray' }}>{cRenderResult}</div>;
        },
        ...others
      };
    }
    return col;
  })}
  />
```


关于禁用情况下的API更多说明，也可以参考官方文档：[https://procomponents.ant.design/components/editable-table/](https://procomponents.ant.design/components/editable-table/)
 > This sentence can be automatically replied to using ChatGPT.
 > 此回复基于 ChatGPT 自动生成。

**Comment by hans000** [comment]
我是用editable实现的，大概是这样
```
<EditableProTable
  columns={[
    ...
    {
      title: '名称',
      editable: (_, record) => (record.userDefined ? !props.disabled : false)
    }
  ]}
/>
```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


根据您的描述，似乎是设置EditableProTable的maxLength属性时对于0的含义有所困惑。实际上，根据官方文档中的说明，maxLength为0时确实等效于Infinity，也就是没有限制。这样设计的原因可能是为了方便用户理解与编写代码。

如果您希望为maxLength属性配置一个特殊含义，比如-1表示无限制或者关闭，您可以自行在代码中进行相应的判断和处理。例如，可以在EditableProTable组件的props中新增一个属性，比如allowNoMaxLength，用于控制当maxLength为0时是否等效于Infinity。具体代码实现可以参考以下示例：

```jsx
<EditableProTable
  maxLength={-1} 
  allowNoMaxLength={true}
/>
```

```jsx
const EditableProTable = ({ maxLength, allowNoMaxLength }) => {
  const creatorButtonDom = useMemo(() => {
    // 根据用户设置判断maxLength是否生效
    if (!allowNoMaxLength && maxLength === 0) {
      return true;
    } else if (maxLength && maxLength <= value?.length) {
      return false;
    }
    return undefined;
  }, [maxLength, value, allowNoMaxLength]);

  // ...
}
```

这里我们新增了一个allowNoMaxLength属性，并在构造creatorButtonDom时根据用户设置来判断是否需要将maxLength清除（即允许用户禁用掉最大长度限制）。

希望以上的回答能够帮助您解决问题。如果您还有其他疑问，请随时回复。

**Comment by chenshuai2144** [comment]
已经发布了，可以试试了
