### ISSUE TITLE
🧐[问题]portable 2.3.58 toolBarRender 的类名ant-pro-table-list-toolbar-left打包出来样式会多余一个 width：100%

### ISSUE THREAD

**Issue by zwd609258057** [ant-design/pro-components#6720]
### 🧐 问题描述
版本：2.3.58
toolBarRender 的类名ant-pro-table-list-toolbar-left打包出来样式会多余一个 width：100%

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/8108601/223064701-29024a75-427c-4eb3-88eb-7c972877df5d.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


### 💡 解决方案
这个问题可能是由于样式覆盖或者继承导致的，建议用户检查是否有自定义的样式或者全局样式会影响到该类名。如果是全局样式的问题，可以考虑给这个类名添加一个专门的命名空间，防止其他样式的影响。如果是覆盖样式的问题，可以在自定义的样式中加上 `!important`，强制覆盖 antd 的样式。

另外，建议用户查看 antd 的官方文档，寻找类名的含义和用法，以帮助更好地理解和解决问题。

对于样式问题，可以参考 antd 的官方文档：
- [Ant Design of React - 样式覆盖](https://ant.design/docs/react/customize-theme-cn#样式覆盖)
- [Ant Design of React - 样式](https://ant.design/components/style-cn/)

如果问题依然存在，请提供更多的问题描述，具体的代码示例和重现步骤，以便更好地帮助解决问题。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


修改完善一下回复，争取更好的解决用户问题

### 🧐 问题描述
版本：2.3.58
toolBarRender 的类名ant-pro-table-list-toolbar-left打包出来样式会多余一个 width：100%


### 🚑 分析解决
通常情况下，antd 已经为样式添加命名空间，这样就不会被其他样式所影响。猜测这可能是其他样式所导致的。 通常情况下，建议在不是必要的情况下，不要使用 `!important` 来重写样式。此外，还建议检查此样式的父元素是否具有固定的宽度。

建议您查看 antd 官方文档以寻找命名空间和使用方法：
- [Ant Design of React - Customize Theme-cn#样式覆盖](https://ant.design/docs/react/customize-theme-cn#样式覆盖)
- [Ant Design of React - 样式](https://ant.design/components/style-cn/)

如果问题依然存在，请提供更多的问题描述，具体的代码示例和重现步骤，以便更好地帮助您解决这个问题。

**Comment by zwd609258057** [comment]
2.3.58 toolBarRender 的类名ant-pro-table-list-toolbar-left打包出来样式会多余一个 width：100%

**Comment by splitter12138** [comment]
同样的问题，这会导致 toolbarRender 渲染的内容发生意外的折行

**Comment by zwd609258057** [comment]
> 同样的问题，这会导致 toolbarRender 渲染的内容发生意外的折行

你也是2.3.58 可以考虑降版本，或者全局复写掉 先解决问题

**Comment by chenshuai2144** [comment]
新版本中删掉了，再试试
