### ISSUE TITLE
🐛[BUG] ProLayout 选中二级菜单，收起侧边栏，在展开侧边栏，标题出现在左上角，随后消失

### ISSUE THREAD

**Issue by pc110** [ant-design/pro-components#6722]
![image](https://user-images.githubusercontent.com/29336835/223084029-fdab5d2d-e111-4d3c-a882-683b9ffa1830.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


您好，感谢使用 Github Issue 助理。根据您提供的信息，可能是 ProLayout 的一个已知问题，由于点击二级菜单并折叠侧边栏后，ProLayout 会尝试对当前路径进行修改。而在下一次展开侧边栏时，ProLayout 将使用上一次操作的路径，这导致了标题出现在左上角，但很快消失。

为了解决此问题，您可以尝试在 `ProLayout` 组件上添加 `route` 属性，来确保路由路径的正确。例如：

```jsx
import ProLayout from '@ant-design/pro-layout';
import { history } from 'umi';

export default () => (
  <ProLayout
    // 其他配置
    route={{
      routes: [
        // 这里填写路由配置
      ],
    }}
    location={{
      pathname: history.location.pathname,
    }}
  >
    Hello World
  </ProLayout>
);
```

此外，建议您查看 ProLayout 的文档以获取更多信息和示例代码，文档链接：https://procomponents.ant.design/components/layout。

希望这可以帮助您解决问题。

**Comment by chenshuai2144** [comment]
我这里没有复现，你看看是不是低版本的样式不兼容导致的

**Comment by pc110** [comment]
官网例子就能重现啊，选中二级菜单，点击展开收缩侧边栏，就能重现， 您在另一个Issues中已经确认是bug了
![1678281554647](https://user-images.githubusercontent.com/29336835/223723595-fd93e500-18b4-4fa5-aa63-810df2ee3409.png)

经过我的测试发现，当内容区域滚动条，滚动到内容区域的标题不显示的时候，展开收缩侧边栏是正常的。
![1678281810760](https://user-images.githubusercontent.com/29336835/223724404-254af18a-5b4e-4109-bdba-fc80e9dc6016.png)
否则会有问题，希望尽快解决。
![image](https://user-images.githubusercontent.com/29336835/223725513-6ae56ee0-60a3-4d5e-aeb3-ba2657bb1e85.png)

**Comment by pc110** [comment]
> 我这里没有复现，你看看是不是低版本的样式不兼容导致的
官网例子就能重现啊，选中二级菜单，点击展开收缩侧边栏，就能重现， 您在另一个Issues中已经确认是bug了
![image](https://user-images.githubusercontent.com/29336835/223727088-37ba2127-995f-4eae-a70c-c31f18ccb738.png)


经过我的测试发现，当内容区域滚动条，滚动到内容区域的标题不显示的时候，展开收缩侧边栏是正常的。
![image](https://user-images.githubusercontent.com/29336835/223727120-bc47c8b5-663e-4f81-b839-87ff0e7e5654.png)
否则会有问题，希望尽快解决。
![image](https://user-images.githubusercontent.com/29336835/223727150-c254306f-c98f-4545-9d54-c1c3fa47ee52.png)

**Comment by yaohwu** [comment]
The same thing happened to me.

**Comment by yaohwu** [comment]
<img width="772" alt="image" src="https://github.com/ant-design/pro-components/assets/9320666/8685b380-1383-4075-b106-14d0bf82979e">

看起来是这部分 div 导致的，加了 display:none 后就消失了

**Comment by coco723** [comment]
遇到了相同的问题，请问怎么解决的？

**Comment by yaohwu** [comment]
> 遇到了相同的问题，请问怎么解决的？

try
```css
div .ant-menu-submenu-popup {
    display: none;
}
```
