### ISSUE TITLE
EditableProTable的formItemProps选项使用函数时，如果配置了rules选项required就会失效

### ISSUE THREAD

**Issue by hans000** [ant-design/pro-components#6723]
### 🐛 bug 描述
EditableProTable的formItemProps选项使用函数时，如果配置了rules选项required就会失效（还有就是如果只想要*只能配置一下label）
```
      columns={[
        {
          dataIndex: 'name',
          formItemProps() {
            return {
              required: true,
              label: '\t',
              colon: false,
              rules: [ { required: true } ]
            }
          },
        },
        {
          dataIndex: 'email',
          formItemProps() {
            return {
              required: true,
              label: '\t',
              colon: false,
            }
          }
        }
      ]}
```
### 🏞 期望结果
两列都有requiredMark标识

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/26105827/223083811-ae760359-e8e7-4024-8355-153660a32592.png">

**Comment by hans000** [comment]
issue #5504

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


感谢提供问题，你的问题是因为 `EditableProTable` 组件中的 `formItemProps` 选项的函数返回值没有传递给 Ant Design 中的 `FormItem` 组件。

解决方案是在 `EditableProTable` 组件的内部使用传递的 `formItemProps` 函数来为每一列的 `FormItem` 组件传递 `rules`，本质上是将返回函数的结果依次向下传递。

如果只想为该列配置 label，可以修改 `EditableProTable` 组件内部的 `FormItem` 组件的 labelCol 属性，让其宽度为零，这样即可实现只有一个 label，同时也可以配置 `FormItem` 的 `required`。

下面是示例代码：

```tsx
import { EditableProTable } from '@ant-design/pro-table';
import { FormItemProps } from 'antd/lib/form/FormItem';

interface TableData {
  name?: string;
  email?: string;
}

const columns = [
  {
    dataIndex: 'name',
    title: '姓名',
    formItemProps: (record: TableData, _, form: FormInstance) => {
      return {
        required: true,
        label: '\t',
        labelCol: { span: 0 }, // 这里配置 labelCol，宽度为 0，也可以只是一个空格
        rules: [{ required: true }],
      };
    },
  },
  {
    dataIndex: 'email',
    title: '邮箱',
    formItemProps: (record: TableData, _, form: FormInstance) => {
      return {
        required: true,
        label: '\t',
        labelCol: { span: 0 }, // 这里配置 labelCol，宽度为 0，也可以只是一个空格
        rules: [{ required: true }],
      };
    },
  },
];

export default () => {
  return <EditableProTable<TableData> columns={columns} />;
};
```

需要注意，上面的代码中，我们将 `EditableProTable` 的泛型类型设为 `TableData`，可以简单定义为 `{ name?: string; email?: string; }`。因为 `EditableProTable` 默认为空数组，不传递其中的数据，在不设置泛型时无法正确的推断列的数据类型。

希望以上解决方案可以帮到你，如有其他问题请随时问我。

**Comment by hans000** [comment]
@chenshuai2144 是因为配置rules后走InternalFormItemFunction过滤label属性导致的，这里是有什么考量还是怎么？
<img width="816" alt="image" src="https://user-images.githubusercontent.com/26105827/223321117-3724ca38-938d-4915-8571-fef55b215950.png">

<img width="781" alt="image" src="https://user-images.githubusercontent.com/26105827/223320819-e52ba164-aa39-4462-8a5d-452d3d49c71f.png">
