### ISSUE TITLE
🐛[BUG] 使用antd5.3.0，ProTable报错

### ISSUE THREAD

**Issue by qc-z** [ant-design/pro-components#6724]
"antd": "^5.3.0",
"@ant-design/pro-components": "^2.3.58"
![image](https://user-images.githubusercontent.com/22362903/223296455-b04fe018-0908-41c3-b719-7f3ce7f4f0a5.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好，根据你提供的错误信息，可以看出是一个关于 ProTable 的问题。它可能依赖于 `antd@5.2.0`，而你正在使用 `antd@5.3.0`，导致了不兼容的问题。你可以通过以下两种方式来解决这个问题：

方法一：降级到 `antd@5.2.0` 版本

在你的项目中，如果你要使用 ProTable，那么它依赖于 `antd`，因此你需要先卸载 `antd@5.3.0`，然后安装 `antd@5.2.0`： 

```
npm uninstall antd@5.3.0 
npm install antd@5.2.0 
```

接下来，你需要清理一下你的 `node_modules` 目录，然后重新安装依赖：

```
rm -rf node_modules # Windows下需要在Git Bash中执行
npm install
```

方法二：升级到 `@ant-design/pro-components` 的最新版本 

如果你想保持 `antd@5.3.0` 的版本，那么你可以尝试升级 `@ant-design/pro-components` 到它的最新版本，这样它就能兼容 `antd@5.3.0` 了。你可以通过以下命令来升级：

```
npm update @ant-design/pro-components
```

重新编译你的项目，这个错误就应该不存在了。如果你在使用过程中还有其他问题，可以查看官方的文档，其中有对 ProTable 的详细介绍和使用示例：[https://procomponents.ant.design/components/table](https://procomponents.ant.design/components/table)。

希望这能够帮助你解决问题。

**Comment by qc-z** [comment]
@chenshuai2144 排除出来了，ProTable 的options={false}就不报错，传入参数或者不传就会报错

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据你提供的信息，如果 `options={false}` 可以解决问题，但是传入参数就会报错的话，可能是传入参数的方式不正确导致的。在官方文档中， `ProTable` 的 `options` 属性应该是一个对象，例如：

```jsx
<ProTable options={{fullScreen: false, reload: true}} />
```

请确保你传入的 `options` 是一个对象。另外，你也可以尝试打印一下你传入的 `options` 对象，看看它的类型和内容是否正确。如果问题仍然存在，可以提供更多的信息，我们会尽力协助解决问题。

**Comment by chenshuai2144** [comment]
修复了，是因为 antd@5 中修改了 configprovide 的参数，试试最新发布的版本
