### ISSUE TITLE
🐛[BUG] ProLayout 收起侧边栏，鼠标移入MenuItem，无Icon配置的Item 标题首字符重复

### ISSUE THREAD

**Issue by wangs1203** [ant-design/pro-components#6725]
### 🐛 bug 描述

ProLayout 收起侧边栏，鼠标移入MenuItem，无Icon配置的Item 标题首字符重复

<img width="1132" alt="截屏2023-03-07 10 04 07" src="https://user-images.githubusercontent.com/26623688/223300499-03985cb1-ee11-4a6f-ad94-1bfe8b8855ee.png">

### 📷 复现步骤

收起导航侧边栏，鼠标移入menu。

### 🏞 期望结果

title 展示“欢迎” 首字符不重复

### 💻 复现代码

复现链接 https://codesandbox.io/s/hun-he-dao-hang-forked-7cvtbi?file=/App.tsx

### © 版本信息

- ProComponents 版本: 2.3.57
- antd: 5.3.0
- 浏览器环境:  chrome 110.0.5481.177
- 开发环境 [e.g. mac OS] win11 and macos 12.3.1

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题可能是由于收起导航侧边栏时，标题和图标的位置重叠导致的。可以从样式上解决这个问题。

可以在`Menu`组件中添加`collapsedWidth`属性，将侧边栏收起时的宽度设置为0。然后在样式中设置标题和图标的位置，在`collapsedWidth`之后。具体代码如下：

```tsx
<Menu
  ...
  collapsedWidth={0} // 设置侧边栏收起时的宽度为0
>
  ...
  <Menu.Item key="1" icon={<MailOutlined />}>
    <span style={{ paddingLeft: 24 }}>欢迎</span>
  </Menu.Item>
  ...
</Menu>
```

此外，可以尝试使用`ProLayout`组件的`menuRender`属性，自定义菜单渲染逻辑，以实现更细致的样式控制。可以参考官方文档中的示例：

https://procomponents.ant.design/components/layout/#menuRender

希望以上解决方案能够帮到你！

**Comment by chenshuai2144** [comment]
修复啦，更新下版本即可
