### ISSUE TITLE
protable 表格form table 之间的联动不能用shouldUpdate。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/pro-components#6726]
### 🔩 所属模块或组件

protable 查询表单
官方例子：https://codesandbox.io/s/h4dnkq
### 🥰 需求描述

 protable 查询表单的联动问题，比如要求先选择一级分类，然后根据一级分类展示二级分类，现在好像只能通过useState来做，而给formItemProps传入shouldUpdate并不能做到这个效果。

 
### 🧐 解决方案

应该让shouldUpdate能在protable里面起作用。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


对于这个问题，目前应该只能通过 useState 来实现查询表单和表格之间的联动。具体实现方式可以参考以下代码示例：

```jsx
// 定义一个 state 存储一级分类和二级分类的数据
const [categoryData, setCategoryData] = useState({
  level1: [],
  level2: []
});

// 在 useEffect 中获取一级分类数据并存储到 state 中
useEffect(() => {
  getCategoryData().then((data) => {
    setCategoryData({
      level1: data.level1,
      level2: []
    });
  });
}, []);

// 定义一个方法，用于获取二级分类数据并更新 state
const handleCategoryChange = (value) => {
  getCategoryData(value).then(data => {
    setCategoryData({
      level1: categoryData.level1,
      level2: data.level2
    });
  });
};

// 在表单中渲染一级分类和二级分类的选择器，并绑定 onChange 事件
<ProFormSelect
  label="一级分类"
  name="level1"
  options={categoryData.level1}
  onChange={(value) => {
    setFormValues({ ...formValues, level1: value, level2: '' });
    handleCategoryChange(value);
  }}
/>

<ProFormSelect
  label="二级分类"
  name="level2"
  options={categoryData.level2}
/>

```

需要注意的是，这里使用了 useEffect 来获取一级分类数据，并在 render 方法中渲染了一级分类和二级分类的选择器。在用户选择一级分类时，会触发 onChange 事件，然后会再次获取对应的二级分类数据并更新存储在 state 中的 categoryData。这样，就可以通过 useState 来实现查询表单和表格之间的联动。

目前，ProTable 组件中并没有提供一个比较简单的解决方案来解决这个问题，但是该组件支持自定义 Filter 和 Table，因此如果您的需求比较复杂，可以考虑使用自定义 Filter 和 Table 来实现联动。自定义 Filter 和 Table 的使用可以参考 ProTable 的官方文档：https://procomponents.ant.design/components/table#自定义-filter。

**Comment by chenshuai2144** [comment]
因为内部太复杂 导致 shouldUpdate 是不生效的，只能通过尽量减少 formItem 的方式来提升性能，如果你有好的办法可以来帮忙提个pr

**Comment by ahuigo** [comment]
我使用这个代替：https://procomponents.ant.design/components/dependency
