### ISSUE TITLE
🧐[问题]使用react-activation从ProTable去详情页，再返回列表查询条件会渲染失败

### ISSUE THREAD

**Issue by zwd609258057** [ant-design/pro-components#6727]
### 🧐 问题描述
从ProTable去详情页，再返回列表查询条件会渲染失败（使用隐藏显示模拟跳转，路由跳转是一样的问题）
快速点击没问题，去详情页等3-5s再返回就有问题了
### 💻 示例代码
https://codesandbox.io/s/cha-xun-biao-ge-forked-nzkw0b?file=/App.tsx

![image](https://user-images.githubusercontent.com/8108601/223311029-b30475a2-f326-40dd-b937-2bb99da6d1a0.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🌟 解决方案

可能出现这个问题的原因是，当你从详情页返回列表页时，列表页的组件并不会重新渲染，而是继续使用之前的 DOM 元素和状态。因此，当你再次搜索时，搜索框和表格的状态已经不同步，导致渲染出错。

可以尝试在ProTable组件中加入key属性，每次切换时都改变其值，强制React重新渲染ProTable组件。

代码示例：

```tsx
<ProTable
  key={Date.now()} // 添加 key 属性
  ...
/>
```

这样，每次切换时就会强制重新渲染 ProTable 组件，解决了状态不同步的问题。

参考文档：

- [React 文档 - Key](https://zh-hans.reactjs.org/docs/lists-and-keys.html#keys)
