### ISSUE TITLE
Form with many inputs are extremely slow

### ISSUE THREAD

**Issue by merabtenei** [ant-design/pro-components#6729]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shi-yong-open-he-onopenchange-forked-y7qvf0?file=/App.tsx)

### Steps to reproduce

Try write anything in one of the inputs of comment column.

### What is expected?

Writing should not cause latency or performance issues.

### What is actually happening?

Typing is lagging, and causing performance issues.

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | react |
| System | Windows 10 |
| Browser | Chrome |

---
This uses EditableProTable from Pro-Components which is a wrapper around Ant Design. After some debugging I found that all inputs are re-rendering on each keystroke which shouldn't happen.
I found some workaround by using:
```typescript
trigger: "onBlur" and 
valuePropName: "defaultValue"
```
This indeed improves things a bit but the input will no longer receive any update made directly to the form using Form.setFieldValue for example and in my use case I need to automatically display the price after choosing a product (and allowing it to be edited).

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hello!

Thank you for your message.

It looks like the issue you are encountering has already been reported to the Ant Design GitHub repository. You may want to check out issue ant-design/ant-design#39413 and see if the suggested solutions and workarounds provided in the thread can help resolve your issue.

If you have any further questions or concerns, please let me know!

**Comment by chenshuai2144** [comment]
There is currently no good solution for the performance issue. If you have any solution, please feel free to submit a pull request.
