### ISSUE TITLE
🐛[BUG] ProTable options 里面的刷新等按钮 hover 到 边界时 tooltip 会一直闪烁

### ISSUE THREAD

**Issue by LeeRayno** [ant-design/pro-components#6733]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
展现如下，hover 到刷新按钮边界时 tooltip 会一直闪烁（请看到最后）

![refresh](https://user-images.githubusercontent.com/18265584/223377265-b50b6138-f12b-4445-89d2-ccf7b1df211f.gif)

### 📷 复现步骤
hover 到 刷新按钮边界（多试几次）

### 🏞 期望结果
hover 时不会一直闪烁

### 💻 复现代码
ProTable 里面默认的代码

### © 版本信息

- ProComponents 版本: [2.3.54]
- umi 版本
- 浏览器环境- chrome 最新版本
- 开发环境 [e.g. mac OS]
- System:
    OS: macOS 12.5.1
    CPU: (10) x64 Apple M1 Pro
- Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.19.1/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm

**Comment by Nicolana** [comment]
因为图标变小的原因，hover边界缩小了，tooltip就关闭了。但是hover结束，图标又变大了，就又触发了tooltip。我觉得是这样，你把图标固定到16px以后再试试

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您提供的问题描述和复现步骤以及版本信息。

从您的问题描述和复现步骤中可以看出，当将鼠标悬停在ProTable中的刷新按钮的边界上时，它的tooltip会一直闪烁。这可能是因为图标的大小发生了变化，导致hover边界缩小，tooltip就会关闭，但是当hover结束时，图标又会变大，就会再次触发tooltip。因此，我们可以将图标的大小固定为16px并重新测试。

下面是我编写的一个例子，其中将图标的大小设置为16px，并且在hover的时候通过CSS将其大小保持不变：

```jsx
import { Button } from "antd";
import { ReloadOutlined } from "@ant-design/icons";

const MyTable = () => {
  return (
    <div style={{ display: "flex", alignItems: "center" }}>
      <Button icon={<ReloadOutlined style={{ fontSize: 16 }} />} style={{ fontSize: 16 }}>
        刷新
      </Button>
    </div>
  );
};

export default MyTable;
```

在上面的例子中，我使用了antd的Button组件，并将其图标设置为带有固定大小的ReloadOutlined。同时，我还将Button组件的字体大小设置为16px以确保其与图标的大小相同。这样当鼠标悬停在按钮上时，它的tooltip就不会闪烁。

希望这个例子能够帮助您解决问题。如果您还有任何问题，请随时向我提出。
