### ISSUE TITLE
🐛[BUG] Can't resolve @ant-design/pro-card 

### ISSUE THREAD

**Issue by Skandar-Ln** [ant-design/pro-components#6743]
🐛 bug 描述
我只安装了@ant-design/pro-layout，但是他依赖了@ant-design/pro-card找不到了，今天升级才出现的问题
Module not found: Error: Can't resolve '@ant-design/pro-card' in 'xxx/node_modules/@ant-design/pro-layout/es/components/Help'
ERROR in ./node_modules/@ant-design/pro-layout/es/components/Help/index.js 9:0-43

📷 复现步骤
npm i @ant-design/pro-layout
npm start

🏞 期望结果
解决依赖问题，还是说以后不能单独用@ant-design/pro-layout了？

💻 复现代码
同上

© 版本信息
最新版

**Comment by DercilioFontes** [comment]
I solved installing the `@ant-design/pro-card`

`npm install --save  @ant-design/pro-card`

**Comment by kyun** [comment]
Or you can use fixed version. `@ant-design/pro-layout": "7.8.3"`

**Comment by chenshuai2144** [comment]
这是个 bug，我来解决一下
