### ISSUE TITLE
🐛[BUG] 官网例子bug, 收起菜单侧边栏， 菜单显示异常

### ISSUE THREAD

**Issue by pc110** [ant-design/pro-components#6744]
官网例子bug, 收起菜单侧边栏， 菜单显示异常
https://procomponents.ant.design/components/layout
重现步骤
1. 选中菜单，收起侧边栏
![image](https://user-images.githubusercontent.com/29336835/223731297-7bd04252-b37a-4108-b15d-0fdfc52a0e3d.png)
2. 菜单名称显示在做上角
![image](https://user-images.githubusercontent.com/29336835/223730687-c2e0bb32-d75c-46f9-a7d2-3a5dce13cbee.png)
3. 鼠标悬停到菜单处，显示正常
![image](https://user-images.githubusercontent.com/29336835/223732934-4414e024-18ec-4739-915c-6b7101355982.png)
4.再次展开收缩侧边栏，菜单直接显示了，而且都显示出来了 
![1678283483216](https://user-images.githubusercontent.com/29336835/223730344-826cb09f-3c49-4f10-8f66-74017acc0f96.png)

**Comment by yufengwang** [comment]
@pc110 我刚准备用的，也发现了你这个问题。。。。。没想到你提issue这么快，难顶啊。
我大晚上，花了三小时，先是想用 next.js 13 + ant-design 起个项目，遇到刷新页面，首屏没样式，闪屏的问题，搞了我一小时，
遂转战 umi，跟着官方文档，起了个 demo，跑起来了，美滋滋，然后鼠标悬浮，就遇到了你这个问题。。。。我折腾了一个晚上，连个项目都没起来，真的是。。。。


真的心累啊。。。

**Comment by loupengju** [comment]
我也遇到了这个问题 搞的心累

**Comment by gitlwz** [comment]
我也遇到了这个问题，现在好心累啊

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


很抱歉你遇到了这个问题，这似乎是一个已知的bug，可能是由于ant-design的菜单组件和layout组件之间的某些交互导致的。您可以尝试使用以下几个方案解决这个问题：

1. 使用固定宽度的菜单，而不是自适应宽度的菜单。

2. 使用CSS来调整菜单的样式，例如添加一个min-width属性：

```CSS
.ant-menu {
  min-width: 200px;
}
```

3. 在组件中手动设置菜单的宽度，例如在layout中，您可以将宽度设置为layout宽度的百分比：

```JSX
<Layout>
  <Sider width="20%">
    <Menu mode="inline" ...>
      ...
    </Menu>
  </Sider>
  <Content>...</Content>
</Layout>
```

希望这些方案能够帮助你解决这个问题。
