### ISSUE TITLE
🐛[BUG] ProList 添加 HeaderTitle 出现样式问题

### ISSUE THREAD

**Issue by amin168** [ant-design/pro-components#6746]
### 🐛 bug 描述

ProList 添加 HeaderTitle 后，出现了滚动条，样式有问题

### 📷 复现步骤

官网的例子就有问题，`https://codesandbox.io/s/bf7fr3`

### © 版本信息

- ProComponents 版本: 2.3.59

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/10808093/223897210-fc3d4e9a-2aeb-456e-a1ab-ad826cdfc498.png)
![image](https://user-images.githubusercontent.com/10808093/223897230-fbea89ac-2760-4c04-aa1a-8956d644590c.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，根据你提供的信息，可能是由于添加了 HeaderTitle 后导致了 ProList 的高度变化，从而出现了滚动条和样式问题。

解决方案：

可以通过设置 ProList 的高度为自适应，使得它的高度会根据内容自动调整，从而避免这个问题。具体做法如下：

```jsx
import { ProList } from '@ant-design/pro-list';

<ProList
  headerTitle="ProList"
  // 设置高度为 auto
  style={{ height: 'auto' }}
>
  { /* content */ }
</ProList>
```

如果这个方案不能解决你的问题，请提供更多信息，我会尽可能地帮你解决这个问题，并提供更详细的文档和代码示例，感谢你的支持！

**Comment by chenshuai2144** [comment]
已经修复了，可以更新下试试了
