### ISSUE TITLE
🐛[BUG]react-scripts5.0.1最新版启动的项目，:where丢失导致样式错乱问题

### ISSUE THREAD

**Issue by Cslove** [ant-design/pro-components#6747]
### 🐛 bug 描述

最新版create-react-app react-scripts5.0.1版启动的项目，:where丢失导致样式错乱问题

### 📷 复现步骤
npx create-react-app my-app
cd my-app
npm i @ant-design/pro-components
npm start

### 💻 复现代码

代码
```
<>
  <PageContainer>
      <Button key="3">重置</Button>
        <Button key="2" type="primary">
          提交
        </Button>
        <Statistic title="sds" value={123} />
    </PageContainer>
<Button key="3">重置</Button>
</>
```
使用PageContainer类似组件包裹的原声antd组件的:where选择器丢失，样式错乱
![image](https://user-images.githubusercontent.com/23312535/223905152-c3e4a350-46ca-4415-95dd-56b725291a86.png)
![image](https://user-images.githubusercontent.com/23312535/223905400-fd5d0e4f-7319-492f-8548-b6ec502fc2d2.png)
下面是没有包在ProComponent的组件内部的原生antd组件，是正常的

### © 版本信息

- ProComponents 版本: [e.g. 2.3.59]
- react-scripts5.0.1
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，这个问题是因为 `:where` 是 CSS Selectors Level 4 中的一个新特性，目前不是所有浏览器都支持它。在使用 `:where` 选择器时，需要确保您的浏览器支持这个选择器。您可以使用 [caniuse](https://caniuse.com/mdn-css_selectors_where) 网站来查看支持情况。

如果你需要在不支持 `:where` 选择器的浏览器上使用样式，可以将 `:where` 选择器替换成一个 CSS 类选择器。

对于 `PageContainer` 类似的组件包裹的原生 antd 组件，你可以尝试将这些组件的 `className` 设置为包含一个 `.my-where` 的类名，然后将这个类名应用到 `:where` 中。示例如下：

```jsx
<PageContainer>
  <div className="my-where :where .ant-btn">
    <Button key="3">重置</Button>
    <Button key="2" type="primary">
      提交
    </Button>
    <Statistic title="sds" value={123} />
  </div>
</PageContainer>
```

然后在 CSS 中定义 `.my-where` 类，应用选择器 `:where(.my-where .ant-btn)` 即可：

```css
.my-where :where(.ant-btn) {
  /* Your styles go here */
}
```

这样即可保证在不支持 `:where` 选择器的浏览器上，也能正确应用样式。更多的信息可以查看 [PostCSS Nesting & :not() Provides a CSS Only Solution to the Dead Class Problem](https://www.smashingmagazine.com/2019/03/css-nesting-not-provides-ive-dead-class-problem/)。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/pull/6741

低版本浏览器看这里

**Comment by Cslove** [comment]
> #6741
> 
> 低版本浏览器看这里

非低版本浏览器，是chrome最新版，与浏览器没关系，create-react-app（react-scripts5.0.1）最新版生成的项目就会有以上问题，降级到react-scripts4.0.3就没问题了

**Comment by Cslove** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/pull/6741

看这个 faq

**Comment by Cslove** [comment]
@chenshuai2144 以下代码包了之后，还是没有效果
```
<>
    <StyleProvider hashPriority="high" transformers={[legacyLogicalPropertiesTransformer]}>
      <PageContainer>
          <Button key="2" type="primary">
            提交
          </Button>
          <Statistic title="sds" value={123} />
      </PageContainer>
    </StyleProvider>
    <Button key="3">重置</Button>
  </>
```
![image](https://user-images.githubusercontent.com/23312535/224459424-bbd00af2-d6bc-4a82-b89d-1ebcc4a17b72.png)
Statistic字体原来的是24px
```
<>
    <StyleProvider hashPriority="high" transformers={[legacyLogicalPropertiesTransformer]}>
      <PageContainer>
          <Button key="2" type="primary">
            提交
          </Button>
      </PageContainer>
    </StyleProvider>
    <Statistic title="sds" value={123} />
    <Button key="3">重置</Button>
  </>
```
这样拿出ProComponent的PageContainer组件是OK的
