### ISSUE TITLE
🐛[BUG]使用pro create xx 生成的umi4项目报  Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.

### ISSUE THREAD

**Issue by gitlwz** [ant-design/pro-components#6755]
### 🐛 bug 描述

使用pro create xx 生成的项目报 a链接 下套a链接的警告
mf-dep____vendor.5fb22d69.js:107762 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/23609865/224218209-cdcc7b8f-5713-4df9-aa64-0bb19a377d45.png)

### 🏞 期望结果

不再报警告

### 💻 复现代码

直接生成的项目

### © 版本信息

![image](https://user-images.githubusercontent.com/23609865/224218368-8293fdfd-af9b-4e69-8ebe-31031fc30167.png)

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/23609865/224218459-cd00837a-381c-4f85-833f-dd9daab8e0eb.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。




这是一个常见的错误提示，它表示你尝试在一个 <a> 标签中嵌套了另一个 <a> 标签。

这个问题的原因是 HTML5 规范中规定了 <a> 标签只是用来表示一个超链接，不能用来包含其他的 <a> 标签。

为了解决这个问题，你可以通过使用其他元素替代其中一个 <a> 标签，例如使用 <span> 标签等。

此外，你还可以使用 React 的事件委托机制来代替多个链接的嵌套，代码示例如下：

```jsx
function handleClick(event) {
  const target = event.target;
  if (target.tagName.toLowerCase() === 'a') {
    // 处理点击事件
  }
}

// 在 render 中使用
<div onClick={handleClick}>
  <a href="#">Link 1</a>
  <a href="#">Link 2</a>
</div>
```

这样做的好处是可以将点击事件委托给父级元素，避免了在多个 <a> 标签中添加事件处理器的重复代码。

关于事件委托的机制可以参考 React 官方文档中的介绍：https://zh-hans.reactjs.org/docs/events.html#event-delegation

**Comment by chenshuai2144** [comment]
升级一下 pro-components 的版本吧，新版本的面包屑改了 api 我兼容了一下

**Comment by boxunsoft** [comment]
> 升级一下 pro-components 的版本吧，新版本的面包屑改了 api 我兼容了一下

升级到2.4.1版本后解决，2.3.59版本有这个问题

**Comment by keer6** [comment]
升级到2.4.1依然存在

**Comment by chenshuai2144** [comment]
看起来需要 umi 那边解决一下😂

**Comment by metafysik** [comment]
2.4.1 版本问题依然存在 +1。

**Comment by tnngo** [comment]
二级路由就会报这个错
