### ISSUE TITLE
🐛[BUG] Pro 2.4.0 菜单样式与 antd 不一致

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#6756]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

菜单圆角，以及 菜单高度 有差异

![微信截图_20230310142942](https://user-images.githubusercontent.com/3166799/224240776-b8ff31a6-76af-4724-9f20-ecc41f61e17d.png)

**Comment by chenshuai2144** [comment]
专门改的，你看看 token 的配置

**Comment by hihuangwei** [comment]
@chenshuai2144 未配置任何 token
