### ISSUE TITLE
🧐[问题] 我在使用BetaSchemaForm组件时收到了antd的警告

### ISSUE THREAD

**Issue by wty-gogo** [ant-design/pro-components#6757]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

[antd: ConfigProvider] ConfigProvider.SizeContext is deprecated. Please use `ConfigProvider.useConfig().componentSize` instead. 

根据信息像是pro-components中的BetaSchemaForm使用了antd废弃的特性？

![image](https://user-images.githubusercontent.com/44995715/224258124-ce558d85-78a1-4c54-9b19-6cb07a9dc5ea.png)

### 🚑 其他信息
依赖版本：  
    "@ant-design/pro-components": "^2.4.0"
    "antd": "^5.3.0",

**Comment by chenshuai2144** [comment]
升级新版本，procomponents 已经没有在用了。
