### ISSUE TITLE
🐛[BUG]ProCard  hidden无效

### ISSUE THREAD

**Issue by 17624050** [ant-design/pro-components#6758]
### 🐛 bug 描述
import {
     ProCard
} from '@ant-design/pro-components';
...
return (
      <ProCard hidden={true}>
....
procard隐藏不了，还是能看见

### © 版本信息

- ProComponents 版本: 2.4.0
- umi 版本 4.0.53
- 浏览器环境：Google Chrome  110.0.5481.177
- 开发环境 win11

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好！根据您的描述，我了解到您在使用 `ProCard` 组件时设置 `hidden={true}` 无法隐藏该组件。

根据 `ProCard` 的 API 文档中的描述，`hidden` 属性用于设置是否隐藏组件并不影响组件其它属性的展示，在官网上这样解释：

> hide or not in card.

因此，如果您想要隐藏 `ProCard` 组件，可以使用 CSS 样式将其隐藏。您可以在样式中针对该组件设置 `display: none;` 属性实现隐藏，如下所示：

```jsx
import { ProCard } from '@ant-design/pro-components';
import styles from './index.less';

const Example = () => {
  return (
    <ProCard className={styles.hidden}>
      ...
    </ProCard>
  );
}

export default Example;
```

另外，您需要在该页面的 LESS/CSS 文件中添加样式类并设置其 `display: none;` 属性，如下所示：

```css
.hidden {
  display: none;
}
```

这样，当您设置 `hidden={true}` 时，`ProCard` 组件将被隐藏。

希望这些信息能够对您有所帮助！如果您有任何疑问或需要更多帮助，请随时提出。

**Comment by fengshengxie** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> 您好！根据您的描述，我了解到您在使用 `ProCard` 组件时设置 `hidden={true}` 无法隐藏该组件。
> 
> 根据 `ProCard` 的 API 文档中的描述，`hidden` 属性用于设置是否隐藏组件并不影响组件其它属性的展示，在官网上这样解释：
> 
> > hide or not in card.
> 
> 因此，如果您想要隐藏 `ProCard` 组件，可以使用 CSS 样式将其隐藏。您可以在样式中针对该组件设置 `display: none;` 属性实现隐藏，如下所示：
> 
> ```js
> import { ProCard } from '@ant-design/pro-components';
> import styles from './index.less';
> 
> const Example = () => {
>   return (
>     <ProCard className={styles.hidden}>
>       ...
>     </ProCard>
>   );
> }
> 
> export default Example;
> ```
> 
> 另外，您需要在该页面的 LESS/CSS 文件中添加样式类并设置其 `display: none;` 属性，如下所示：
> 
> ```css
> .hidden {
>   display: none;
> }
> ```
> 
> 这样，当您设置 `hidden={true}` 时，`ProCard` 组件将被隐藏。
> 
> 希望这些信息能够对您有所帮助！如果您有任何疑问或需要更多帮助，请随时提出。

这个方法ProCard 仍然占着位置

**Comment by fengshengxie** [comment]
用 colSpan={0}可以隐藏起来

**Comment by chenshuai2144** [comment]
<ProCard/> 好像并不支持这个功能，建议用css吧
