### ISSUE TITLE
🐛[BUG] ProFormSelector 使用 reuqets 丢失数据

### ISSUE THREAD

**Issue by oswayne** [ant-design/pro-components#6763]
### 🐛 bug 描述
request 函数返回的数据在 ProFormSelect 中不会显示

### 📷 复现步骤
无

### 🏞 期望结果
在 ProFormSelect 中看到选项

### 💻 复现代码

```jsx
<ProFormSelect colProps={24}
                            name="address"
                            label="Address"
                            placeholder="请输入内容以搜索"
                            showSearch
                            request={request}
                            debounceTime={200}/>)
```

### © 版本信息

- ProComponents 版本: 2.4.0
- umi 版本
- 浏览器环境 Safari 16.3
- 开发环境 macOS 13.2.1

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题可能是由于 ProFormSelect 中的 options 数据没有被正确设置导致的，建议尝试传递 options 属性作为 request 函数返回数据的一个映射。

例如：

```jsx
<ProFormSelect
  colProps={24}
  name="address"
  label="Address"
  placeholder="请输入内容以搜索"
  showSearch
  request={request}
  options={data=>data.map(({ id, name }) => ({ label: name, value: id }))}
  debounceTime={200}
/>
```

此外，您可以在 request 函数中打印返回的数据以确保其存在，并检查 options 对象中是否包含正确的值以确保其正确设置。

如果还有问题，请尝试使用 React Developer 工具检查组件的 props 是否正确设置，并使用相关文档进行错误排查。

参考文档：
- [ProFormSelect API 文档](https://procomponents.ant.design/components/Form?id=proformselect)。
- [Ant Design Select API 文档](https://ant.design/components/select-cn/)。

**Comment by oswayne** [comment]
复现不出来，先关了吧
