### ISSUE TITLE
👑 [需求] 关于digit，text的onChange调用时机是否可以增加一个onBlur

### ISSUE THREAD

**Issue by Dzxwind** [ant-design/pro-components#6765]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

Proform 预设valueType：digit，text

### 🥰 需求描述
当前digit与text都是调用的Input与InputNumber中的onChange事件然后触发pro-components里的onChange()
但是实际有些表单需要自动保存的，那么onChange过于频繁了，做防抖节流看起来也不那么合适。所以更希望在blur的时候调用onChange

### ⛰ 功能需求适用场景

pro-form自动保存下节省与后端交互

### 🧐 解决方案

看起来应该是在`/src/components/Digit/index.tsx`文件里加一个onBlur就可以了（甚至可以写成一个配置项）

### 🚑 其他信息

PS：本来想用patch改一下，但是发现npm上的包居然是uglify过了，直接束手无策。TAT

**Comment by Dzxwind** [comment]
所以，这边处理业务，可能得自己单独写一个digit的valueType，其实感觉这个操作很没必要，真的就只是需要多加一个blur的事件罢了。。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，关于你的需求，你可以通过自定义一个 digit 的 valueType，来实现在 `blur` 时触发 onChange 事件的操作。

以下是示例代码：

```typescript
// 自定义 valueType

import { Input } from 'antd';
import { ProFormFieldItem } from '@ant-design/pro-form';
import React from 'react';

export const myDigit: ProFormFieldItem['valueType'] = {
  transform: (value: any) => {
    if (!value) return undefined;
    return String(value);
  },
  render: (dom, entity, ...rest) => {
    return <Input {...rest} value={dom} />;
  },
  onChange: (e) => {
    return e.target.value.replace(/[^\-?\d.]/g, '');
  },
  onBlur: (e, oProps) => {
    const { onChange } = oProps;
    if (onChange) {
      onChange(e);
    }
  },
};
```

然后在 Form 中使用：

```tsx
// 使用自定义 valueType

import { Form } from 'antd';
import ProForm, { ProFormDigit } from '@ant-design/pro-form';
import { myDigit } from './myDigit';
import React from 'react';

const MyForm = () => {
  const onFinish = async (values: any) => {
    console.log(values);
  };

  return (
    <ProForm
      onFinish={onFinish}
    >
      <ProFormDigit name="digit" label="digit" value="123" valueType={myDigit} />
    </ProForm>
  );
};

export default MyForm;
```

这样，在输入框失焦时，就会触发 `onBlur` 事件，并执行 `onChange` 函数，从而实现了在 `blur` 时触发 `onChange` 事件的操作。

希望这个解决方案能满足你的需求，如有疑问可以进一步交流。

**Comment by chenshuai2144** [comment]
可以通过 formItemProps 设置一下 trigger 来绕过。默认还是希望数据是一直更新的，这样数据的准确性是对的

**Comment by Dzxwind** [comment]
> 可以通过 formItemProps 设置一下 trigger 来绕过。默认还是希望数据是一直更新的，这样数据的准确性是对的

这个方案我试过了，但是不知道为什么没有使用formItemProps的时候，digit返回的是Number。使用了formItemProps的时候，返回的却是string，不知道这是不是bug。（虽然我可以通过transform来转回Number）

**Comment by Dzxwind** [comment]
> > 可以通过 formItemProps 设置一下 trigger 来绕过。默认还是希望数据是一直更新的，这样数据的准确性是对的
> 
> 这个方案我试过了，但是不知道为什么没有使用formItemProps的时候，digit返回的是Number。使用了formItemProps的时候，返回的却是string，不知道这是不是bug。（虽然我可以通过transform来转回Number）

而且，如果是这样设置的话，点击inputNumber的上下箭头也是无效的。

从业务上看，如果是自动保存的表单，当前onChange的方式数据更新频率过于频繁了，此时是不需要完全最新的数据了。

**Comment by chenshuai2144** [comment]
修复了一下，你可以用了。 修改 trigger = 'onBlur'
