### ISSUE TITLE
🐛[BUG] Pro 的菜单圆角与 antd 菜单圆角不一致，希望可以同步为一致

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#6768]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

antd 为 border-radius: 8px;
pro 为 border-radius: 4px;

![微信截图_20230313193918](https://user-images.githubusercontent.com/3166799/224691710-88ad4db7-0c59-4fd0-a7a7-0ce60d1aaa9c.png)

### 📷 复现步骤

https://procomponents.ant.design/~demos/packages-layout-src-components-layout-demo-base?layout=mix&splitMenus=true

**Comment by chenshuai2144** [comment]
设计师专门要求的，理论上应该都改成 4px

**Comment by chenshuai2144** [comment]
通过 configprovide 配置一下吧

**Comment by pc110** [comment]
> configprovide

### 如何增加一个全局的configprovide ？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


要在 React 应用程序中使用 `ConfigProvider`，必须在组件树的上层位置中包装应用程序，这样它将被添加到组件树的上下文中，供组件使用。

你可以通过下面两种方式来创建一个全局的 `ConfigProvider`：

#### 1. 自己手动包装

找到应用程序的根组件（通常是 `src/index.js` 中的 `ReactDOM.render()` 语句），在这个组件的 `render()` 方法中包装整个应用程序：

```jsx
import React from "react";
import ReactDOM from "react-dom";
import { ConfigProvider } from "antd";
import App from "./App";

ReactDOM.render(
  <ConfigProvider>
    <App />
  </ConfigProvider>,
  document.getElementById("root")
);
```

上面的代码可以将 `ConfigProvider` 挂载到 `App` 的父级组件上，从而实现全局使用。

#### 2. 使用 `generateAntdLoader` 自动注入

如果你使用的是 `create-react-app` 或 `umi` 框架，Antd 框架提供了一个工具函数 `generateAntdLoader` 用于自动化注入 `ConfigProvider` 组件。只需要在 `src/index.js` 文件中导入该函数并修改 `ReactDOM.render` 方法即可：

```jsx
import ReactDOM from "react-dom";
import { generateAntdLoader } from "antd-tools";
import App from "./App";

ReactDOM.render(generateAntdLoader(App), document.getElementById("root"));
```

这种方式会对应用程序进行修改，并自动引入 `ConfigProvider` 组件。

无论你选哪种方式，只要确保在应用程序中只需要包装一次，就能全局使用 `ConfigProvider`。
