### ISSUE TITLE
🐛[BUG] Argument appears to not be a ReactComponent. Keys: forceAlign,forcePopupAlign

### ISSUE THREAD

**Issue by fitterfizzle** [ant-design/pro-components#6770]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

Argument appears to not be a ReactComponent. Keys: forceAlign,forcePopupAlign

This error happens after updating Ant Design to v5.3.0 and v5.3.1

![image](https://user-images.githubusercontent.com/96863959/224704781-0e280b3f-a40b-422c-82a8-e42b8b282059.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by deng-yc** [comment]
同样问题

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


请提供你的问题描述和相关信息，我可以为你提供帮助。

**Comment by hooliy** [comment]
同样的问题，升级后项目跑不起来了

**Comment by hooliy** [comment]
<img width="601" alt="image" src="https://user-images.githubusercontent.com/3368691/225806161-a753d4a0-f125-4f90-8875-2430183f1e0c.png">

**Comment by deng-yc** [comment]
> 同样的问题，升级后项目跑不起来了

https://github.com/ant-design/ant-design/issues/41206#issuecomment-1472752108

我参考这个，把 `node_modules` 删掉重新 `npm install` 后能跑起来了

**Comment by hooliy** [comment]
> > 同样的问题，升级后项目跑不起来了
> 
> [ant-design/ant-design#41206 (comment)](https://github.com/ant-design/ant-design/issues/41206#issuecomment-1472752108)
> 
> 我参考这个，把 `node_modules` 删掉重新 `npm install` 后能跑起来了

还是不行，并且降到之前的版本了，重新再 yarn 也跑不起来了！ 。。。

**Comment by hooliy** [comment]
<img width="187" alt="image" src="https://user-images.githubusercontent.com/3368691/225809283-a353ed1e-cc35-4fff-b5e8-87a50a692845.png">
只有把 setting: false, 设置成 false 才不报错，
但是项目中 setting 还是有用的。

**Comment by xuqiang1227** [comment]
@afc163 @zombieJ 
我这个问题我尝试在codesandbox，都没办法复现，但是本地依然存在问题。
尝试debug了一下发现在 `resize-observer` 工程中的 `src\SingleObserver\index.tsx` 文件里第42行的 `getDom`方法中：
```
  const getDom = () =>
    findDOMNode<HTMLElement>(elementRef.current) || findDOMNode<HTMLElement>(wrapperRef.current);
```
当这个问题出现时：`elementRef.current` 的 值为：
```
{
   forceAlign: () => {},
   forcePopupAlign: () => {}
}
```
![image](https://user-images.githubusercontent.com/4525647/227862924-ee36f053-f036-48ba-91e4-1cf8aaea05b3.png)

该值应该为antd 中 `ant-design\components\tooltip\index.tsx` 第221行定义的 ref。
所以麻烦再review一下这里的代码，看看是否存在bug。

**Comment by zombieJ** [comment]
rc-util 的 `findDOMNode` 是会检测 ref 内的元素是否是 DOM 节点的，如果不是则使用原生的 `findDOMNode`。如果没有办法提供复现的话，就无法定位问题了。

**Comment by xuqiang1227** [comment]
破案了，@rc-component/trigger中的rc-util的 `findDomNode` 版本不一致：
![企业微信截图_16800805117292](https://user-images.githubusercontent.com/4525647/228698603-a41d407f-2013-4d81-8144-ee177773130f.png)

@zombieJ 是否可以考虑更新一下这个路径上的相关库版本：
`\node_modules\@rc-component\trigger\node_modules\rc-resize-observer\node_modules\rc-util`

以下是最新版本的rc-util 中的 `findDomNode` 代码

```
export function isDOM(node: any): node is HTMLElement | SVGElement {
  // https://developer.mozilla.org/en-US/docs/Web/API/Element
  // Since XULElement is also subclass of Element, we only need HTMLElement and SVGElement
  return node instanceof HTMLElement || node instanceof SVGElement;
}

/**
 * Return if a node is a DOM node. Else will return by `findDOMNode`
 */
export default function findDOMNode<T = Element | Text>(
  node: React.ReactInstance | HTMLElement | SVGElement,
): T {
  if (isDOM(node)) {
    return (node as unknown) as T;
  }

  if (node instanceof React.Component) {
    return (ReactDOM.findDOMNode(node) as unknown) as T;
  }

  return null;
}
```

` yarn list rc-uitl `后，这是一个@umijs/max项目：
![企业微信截图_16801377743081](https://user-images.githubusercontent.com/4525647/228700561-aa8584df-d8b4-4892-98b7-56187c08ad09.png)

**Comment by zombieJ** [comment]
`rc-util` 版本是不锁的，删除一下 lock 文件重新安装就会是最新的哈

**Comment by Asanio06** [comment]
Thanks, delete yarn.lock and install again work for me
