### ISSUE TITLE
🐛[BUG]Uncaught TypeError: Cannot read properties of undefined (reading 'token')

### ISSUE THREAD

**Issue by ldwonday** [ant-design/pro-components#6773]
![image](https://user-images.githubusercontent.com/4630157/224879404-b515098a-501c-4f3b-8b35-978e9e820ad5.png)
![image](https://user-images.githubusercontent.com/4630157/224879797-de110752-6cc4-4ee5-a8cc-8e2b1466de2e.png)

升级最新版2.4.1报错

**Comment by ldwonday** [comment]
@chenshuai2144 尽快修复下这个问题吧

**Comment by chenshuai2144** [comment]
注意一下provide 的版本。最好用procomponents 来统一导入一下

**Comment by ldwonday** [comment]
> 注意一下provide 的版本。最好用 procomponents 来统一导入一下
> 
> ```
>   "dependencies": {
>     "@ant-design/pro-card": "^2.3.0",
>     "@ant-design/pro-descriptions": "^2.2.0",
>     "@ant-design/pro-field": "^2.5.0",
>     "@ant-design/pro-form": "^2.8.0",
>     "@ant-design/pro-layout": "^7.10.1",
>     "@ant-design/pro-list": "^2.3.1",
>     "@ant-design/pro-provider": "^2.6.0",
>     "@ant-design/pro-skeleton": "^2.1.0",
>     "@ant-design/pro-table": "^3.5.1",
>     "@ant-design/pro-utils": "^2.7.0",
>     "@babel/runtime": "^7.16.3"
>   },
> ```

我引入的就只有pro-components最新版的

**Comment by zhanglin1993** [comment]
same issue
