### ISSUE TITLE
EditableProTable  + ProForm可编辑表格数据太多，非常卡顿有好的解决方法么

### ISSUE THREAD

**Issue by zhuiluo0987** [ant-design/pro-components#6776]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


问题描述：

使用 EditableProTable 和 ProForm 组合的可编辑表格数据太多，很卡顿，需要一个优化方法。

解决方案：

1. 尽量减少 Render 次数

卡顿的主要原因是 Render 次数过多，所以制定优化策略时可以尽量减少 Render 次数。可以使用 React.memo 包裹组件，或者使用 shouldComponentUpdate 生命周期函数来手动控制组件是否更新。

2. 使用虚拟滚动

如果数据量很大，可使用虚拟滚动来进行优化。antd 提供了一个 Table 组件，支持虚拟滚动，详情见文档。

3. 不要频繁更新数据

避免频繁更新数据，最好是在一定条件下批量更新。比如，在点击保存按钮时批量保存多条数据。

4. 使用 ImmutableJS

使用 ImmutableJS 来优化数据的更新操作。它可以减少数据对象深度，提高更新性能。

5. 使用数据分页

将数据划分为多页，每次加载一页数据，可以提高渲染效率。

示例代码：

1. 使用 React.memo 包裹组件

```jsx
const MyComponent = React.memo(props => {
  // 组件内容
});
```

2. shouldComponentUpdate 示例

```jsx
class MyComponent extends React.Component {
  shouldComponentUpdate(nextProps, nextState) {
    // 判断 props 和 state 是否变化，返回 true 或 false
  }
  render() {
    return (
      // 组件内容
    );
  }
}
```

3. 虚拟滚动

```jsx
import { Table } from 'antd';

const columns = [
  { title: 'Name', dataIndex: 'name' },
  { title: 'Age', dataIndex: 'age' },
  { title: 'Address', dataIndex: 'address' },
];

const data = [];
for (let i = 0; i < 100000; i++) {
  data.push({
    key: i,
    name: `Edward King ${i}`,
    age: 32,
    address: `London, Park Lane no. ${i}`,
  });
}

const App = () => {
  return (
    <Table
      columns={columns}
      dataSource={data}
      pagination={false}
      scroll={{ y: 240 }}
    />
  );
};

ReactDOM.render(<App />, mountNode);
```

参考文档：

- [React.memo](https://zh-hans.reactjs.org/docs/react-api.html#reactmemo)
- [shouldComponentUpdate](https://zh-hans.reactjs.org/docs/react-component.html#shouldcomponentupdate)
- [antd Table 虚拟滚动](https://ant.design/components/table-cn/#components-table-demo-virtualized)

**Comment by chenshuai2144** [comment]
试试 AI 的办法，另外等 https://github.com/ant-design/ant-design/issues/43557  

这个issue 发布之后会好一些

**Comment by Qyokizzzz** [comment]
其实卡顿主要发生在点击全选的时候，这个时候每个editableCell的type都改变了，diff不会复用而是根据新元素创建新fiber，个数为行数*列数，使用memo\shouldComponentUpdate并不能解决这个问题
