### ISSUE TITLE
🐛[BUG]ProFormMoney组件使用trigger="onBlur"会导致重复出现货币符号

### ISSUE THREAD

**Issue by a295470799** [ant-design/pro-components#6779]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProFormMoney组件使用trigger="onBlur"会导致重复出现货币符号

### 📷 复现步骤

https://codesandbox.io/s/elated-shockley-cqi5r0?file=/src/App.js

### 🏞 期望结果

没有多余的货币符号出现

### 💻 复现代码

`<ProFormMoney`
      `  name="base_origin_price"`
      `  label="Base origin price"`
      `  customSymbol={country.symbol}`
      `  min={0.01}`
      `  rules={[{ required: true }]}`
     `   trigger="onBlur"`
    `/>`

### © 版本信息

- ProComponents 版本: 2.3.57
- umi 版本 4.0.52
- 浏览器环境 Chrome
- 开发环境 Win10

### 🚑 其他信息

![20230314162635](https://user-images.githubusercontent.com/42329829/224941291-35570c34-41e2-4dcb-b0be-29eec0ef76c6.gif)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据复现步骤可以看出，重复出现货币符号是因为使用了`customSymbol`自定义货币符号，并在`trigger`中使用了`onBlur`触发规则校验，但在输入完成后，组件的值还没有更改，所以出现了重复的货币符号。可以使用`formatter`对输入框值进行格式化，去除多余的货币符号。

修改代码如下：
```jsx
<ProFormMoney
  name="base_origin_price"
  label="Base origin price"
  customSymbol={country.symbol}
  min={0.01}
  rules={[{ required: true }]}
  trigger="onBlur"
  formatter={value => {
    return value.replace(new RegExp(`\\${country.symbol}`, 'g'), '')
  }}
/>
```

这里使用了`RegExp`和`replace`方法，将输入框中的货币符号替换为空字符串，保留数字内容。这样就可以解决重复出现货币符号的问题。

参考文档：
- [ProFormMoney 使用指南](https://procomponents.ant.design/components/form-money)

**Comment by a295470799** [comment]
> 



> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> 根据复现步骤可以看出，重复出现货币符号是因为使用了`customSymbol`自定义货币符号，并在`trigger`中使用了`onBlur`触发规则校验，但在输入完成后，组件的值还没有更改，所以出现了重复的货币符号。可以使用`formatter`对输入框值进行格式化，去除多余的货币符号。
> 
> 修改代码如下：
> 
> ```js
> <ProFormMoney
>   name="base_origin_price"
>   label="Base origin price"
>   customSymbol={country.symbol}
>   min={0.01}
>   rules={[{ required: true }]}
>   trigger="onBlur"
>   formatter={value => {
>     return value.replace(new RegExp(`\\${country.symbol}`, 'g'), '')
>   }}
> />
> ```
> 
> 这里使用了`RegExp`和`replace`方法，将输入框中的货币符号替换为空字符串，保留数字内容。这样就可以解决重复出现货币符号的问题。
> 
> 参考文档：
> 
> * [ProFormMoney 使用指南](https://procomponents.ant.design/components/form-money)

不使用自定义货币符号也是有问题的，而且用正则替换的话就没有货币符号和千分位了，那就没必要用这个组件了

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常抱歉，我在回复中没有考虑到使用默认货币符号和千分位的情况。在这种情况下，我们可以通过设置组件的`outputMoney`为`true`来解决问题，如下所示：

```jsx
<ProFormMoney
  name="base_origin_price"
  label="Base origin price"
  min={0.01}
  rules={[{ required: true }]}
  trigger="onBlur"
  outputMoney
/>
```

这样就可以在组件的输出中使用默认货币符号和千分位了。当然，你也可以通过设置`formatter`和`parser`的方式自定义格式。

非常感谢你提出问题，并指出我在前一个回答中的错误。如果还有其他问题，欢迎继续提问。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常抱歉，感谢您指出这个问题。如果不使用自定义货币符号，也出现重复货币符号的问题，这可能是由于组件内部逻辑导致的。目前可以通过在`formatter`里使用正则表达式替换的方式解决，但是这样确实会导致货币符号和千分位分隔符都消失了。另外，还需要注意的一点是，组件文档中提到的`digit`属性是控制小数点后的位数，而不是小数点之前的位数，这也可能会导致问题。可以尝试在组件的`formatter`和`parser`两个属性中分别进行格式化和解析，对值进行处理。对于具体如何进行格式化和解析，可以根据具体需求进行相应调整。如果问题仍然存在，建议提供更多代码信息和具体问题描述。
