### ISSUE TITLE
[In mobile]: The PageContainer wrapper does not work properly on mobile screens.

### ISSUE THREAD

**Issue by beeena** [ant-design/pro-components#6782]
### 🧐Problem Description

At present, we are utilizing **ProLayout** from antd-pro. I have enclosed the content with a **PageContainer** wrapper, which functions well on larger screens. However, on mobile screens, it does not work as intended, as the content overflows the **PageContainer**.

![image](https://user-images.githubusercontent.com/3382355/220844542-efd2f1ed-38ce-4460-b55b-08fec7f124d6.png)

### What is expected?

We cannot use custom sizing, as the PageContainer wrapper must automatically adjust the sizing.

### 💻 Sample code

```
  <ProLayout
          title={settings?.title}
          formatMessage={formatMessage}
          {...props}
          {...newSettings}
          onMenuHeaderClick={onMenuHeaderClick}
          menuItemRender={menuItemRender}
          menuContentRender={menuContentRender}
          menuFooterRender={menuFooterRender}
          breadcrumbRender={breadCrumbs}
          itemRender={itemRender}
          footerRender={GlobalFooter}
          /**
           * MenuDataRender was causing problem as it was not
           * filtering out the menuData properly for each component,
           * so had to comment it and now we are using custom menuDataRender
           * function which is called for each menu render components
           * separately so that menus can be filtered out from props.menuData
           * when passed to the function
           */
          // menuDataRender={menuDataRender}
          postMenuData={postMenuData}
          actionsRender={rightProps => {
            const menuSeparation = getMenuSeparation(rightProps?.menuData);
            return [
              ...(menuSeparation && menuSeparation.upperMenus?.map((item) => {
                return item.children?.map((menu) => {
                  return (
                    <HeaderDropdown key={menu?.key || menu?.name} overlay={() => getHeaderMenus(menu)}>
                      <div className={` anticon`}>
                        <Link
                          style={{
                            fontSize: '20px',
                            cursor: 'pointer',
                            color: '#6b6767',
                          }}
                          key={menu?.key || menu?.name}
                          to={generateMenuPath(menu?.path, routeParams)}
                        >
                          {menu?.icon}
                        </Link>
                      </div>
                    </HeaderDropdown>
                  )
                })
              })),
              <RightContent
                upperMenus={getMenuSeparation(rightProps?.menuData).upperMenus}
                routeParams={props?.routeParams}
                collapsed={props?.collapsed}
                settings={settings}
                {...rightProps}
              />
            ]
          }}
        >
          <PageContainer>
            {children}
          </PageContainer>
        </ProLayout>
```

### 🚑 Other information

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | "react": "18.0.0" |
| System | ubuntu 20 |
| Browser | Google Chrome |

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


To fix the PageContainer overflow issue on mobile screens, you can use CSS media queries to set the maximum width of the PageContainer on mobile devices. Try adding the following CSS code to your stylesheet or style section:

```
@media (max-width: 767px) {
  .ant-pro-page-container {
    max-width: 100%;
  }
}
```

This will set the maximum width of the PageContainer to 100% on screens narrower than 768 pixels (the default breakpoint for Ant Design).

You can also adjust the breakpoint to meet your specific needs.

For more information on CSS media queries, you can refer to the following documentation: 
- [CSS media queries - Mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) 
- [CSS media queries - W3Schools](https://www.w3schools.com/css/css_rwd_mediaqueries.asp)

**Comment by beeena** [comment]
@chenshuai2144 the above solution didn't works for me?
