### ISSUE TITLE
🐛[BUG] Protable 高度超过页面可视宽度后，往下滚动出现白块

### ISSUE THREAD

**Issue by zFitness** [ant-design/pro-components#6783]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
Protable 高度超过页面可视宽度后，往下滚动出现白块， 需要等一会儿才能全部显示：
如下图所示，箭头指向的地方出现卡顿，隔了0.5s后才完全显示。

这里我使用了 shouldUpdateCell 优化性能，依然没办法解决。
![image](https://user-images.githubusercontent.com/41500499/225013163-4f9bba8c-04b2-4504-ab66-db43fc71b6b8.png)

### © 版本信息

- ProComponents 版本: [^2.3.57]
- umi 版本 4.0
- 浏览器环境 chrome
- 开发环境 [mac OS m1 pro]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题可能是由于 ProTable 高度超过页面可视宽度后，懒加载（lazy load）的数据导致的，建议取消懒加载或者提前加载数据来解决这个问题。

可以参考官方文档：https://procomponents.ant.design/components/table/#%E6%A6%82%E5%BF%B5

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


很高兴听到你解决了这个问题，并感谢你的反馈和分享！如果你以后有其他的问题或疑问，请不要犹豫地在 GitHub 上向相关仓库提出问题和建议。同时，也欢迎继续使用和掌握 React 和 ProTable 等技术，加油！
