### ISSUE TITLE
👑 [需求] ProTable的columns的copyable属性支持复制部分内容

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/pro-components#6784]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述
现在产品有个需求，就是表格一块的内容，只复制后面的内容，前面的内容不复制，这要怎么用columns中的copyable操作

![image](https://user-images.githubusercontent.com/20655248/225201509-aeb01806-711c-4248-a4fa-7e164fe521b0.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


可以使用 ProTable 中的 `render` 函数来实现复制后面的内容，前面的内容不复制。具体实现方法如下：

```jsx
import { ProTable, EditableProTable } from '@ant-design/pro-table';

const columns = [
  {
    title: '姓名',
    dataIndex: 'name',
    copyable: (text, record) => ({text: record.age.toString() + ' ' + record.address}),
  },
  {
    title: '年龄',
    dataIndex: 'age',
  },
  {
    title: '地址',
    dataIndex: 'address',
  },
];

const data = [
  {
    key: '1',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
  },
  {
    key: '2',
    name: 'Joe Black',
    age: 42,
    address: 'London No. 1 Lake Park',
  },
  {
    key: '3',
    name: 'Jim Green',
    age: 32,
    address: 'Sidney No. 1 Lake Park',
  },
  {
    key: '4',
    name: 'Jim Red',
    age: 32,
    address: 'London No. 2 Lake Park',
  },
];

function App() {
  return (
    <ProTable
      columns={columns}
      dataSource={data}
      rowKey="key"
      search={false}
      options={false}
    />
  )
}
```

在上面的代码中，使用 `copyable` 属性可以传入一个函数，函数的参数为当前行的文本和记录，函数的返回值是一个对象，其中 `text` 属性为要复制的文本。

所以我们可以在 `copyable` 中拼接要复制的内容，实现只复制后面的内容，前面的内容不复制。同时，由于我们要拼接多个字段，可以将要拼接的字段放在一起，使用 `toString()` 方法转换成字符串。

**Comment by lovehebe330** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> 可以使用 ProTable 中的 `render` 函数来实现复制后面的内容，前面的内容不复制。具体实现方法如下：
> 
> ```js
> import { ProTable, EditableProTable } from '@ant-design/pro-table';
> 
> const columns = [
>   {
>     title: '姓名',
>     dataIndex: 'name',
>     copyable: (text, record) => ({text: record.age.toString() + ' ' + record.address}),
>   },
>   {
>     title: '年龄',
>     dataIndex: 'age',
>   },
>   {
>     title: '地址',
>     dataIndex: 'address',
>   },
> ];
> 
> const data = [
>   {
>     key: '1',
>     name: 'John Brown',
>     age: 32,
>     address: 'New York No. 1 Lake Park',
>   },
>   {
>     key: '2',
>     name: 'Joe Black',
>     age: 42,
>     address: 'London No. 1 Lake Park',
>   },
>   {
>     key: '3',
>     name: 'Jim Green',
>     age: 32,
>     address: 'Sidney No. 1 Lake Park',
>   },
>   {
>     key: '4',
>     name: 'Jim Red',
>     age: 32,
>     address: 'London No. 2 Lake Park',
>   },
> ];
> 
> function App() {
>   return (
>     <ProTable
>       columns={columns}
>       dataSource={data}
>       rowKey="key"
>       search={false}
>       options={false}
>     />
>   )
> }
> ```
> 
> 在上面的代码中，使用 `copyable` 属性可以传入一个函数，函数的参数为当前行的文本和记录，函数的返回值是一个对象，其中 `text` 属性为要复制的文本。
> 
> 所以我们可以在 `copyable` 中拼接要复制的内容，实现只复制后面的内容，前面的内容不复制。同时，由于我们要拼接多个字段，可以将要拼接的字段放在一起，使用 `toString()` 方法转换成字符串。

![image](https://user-images.githubusercontent.com/20655248/226892681-6b19b365-b37e-4594-a639-1e4678d16e7f.png)
copyable不是只支持布尔值吗，不能支持返回函数吧
