### ISSUE TITLE
🐛[BUG]树表格在展开时，无缩进

### ISSUE THREAD

**Issue by Elieen-v** [ant-design/pro-components#6786]
### 🐛 bug 描述

树表格的展开功能，在第一级和第二级之间没有缩进

### 📷 复现步骤

点击树表格展开按钮，一级二级三级在同一水平线

### 🏞 期望结果

点击一级展开时，二级缩进

### 💻 复现代码

        <ProTable<SYSTEM_ENTITY.SystemList>
          headerTitle="体系表格"
          rowKey="id"
          actionRef={actionRef}
          expandable={{ expandedRowKeys: expandedRowKeys }}
          onExpand={(expanded, record) => {
            if (expanded) {
              setExpandedRowKeys(expandedRowKeys.concat(record.id));
            } else {
              if (expandedRowKeys.indexOf(record.id) !== -1)
                setExpandedRowKeys(expandedRowKeys.filter((item) => item !== record.id));
            }
          }}
          request={async (params) => {
            return getData(params);
          }}
          pagination={false}
          columns={columns}
          revalidateOnFocus={false}
          onReset={() => {
            setExpandedRowKeys([]);
            setFlag(false);
          }}
        />

### © 版本信息

- ProComponents 版本: [@2.4.2]
- umi 版本 [v3.x]
- 浏览器环境[edge ,google]
- 开发环境 [window]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


尝试修改 expandable 属性里面的相关属性，例如indentSize和childrenColumnName，具体操作如下：

```javascript
<ProTable
  // ...
  expandable={{
    expandedRowKeys: expandedRowKeys,
    indentSize: 20, // 缩进的大小，单位为 px
    childrenColumnName: 'children', // 子节点的属性名称
  }}
  // ...
/>
```

这里将indentSize设为20，可以根据实际情况进行调整。childrenColumnName则是在dataProvider中定义树形结构数据时使用的属性名称，如果不一致的话需要根据实际情况进行修改。

更多关于ProTable树形表格的属性和用法，可以参考Ant Design Pro官方文档中的TreeTable部分：https://pro.ant.design/components/table#%E6%A0%91%E8%A1%A8%E6%A0%BC
