### ISSUE TITLE
🐛[BUG] PageHeader 沒有正常 render backIcon

### ISSUE THREAD

**Issue by EvenC-tw** [ant-design/pro-components#6788]
### 🐛 bug 描述
PageHeader 沒有正常 render backIcon

### 📷 复现步骤
加入 PageHeader，並使用 backIcon

### 🏞 期望结果
backIcon 應該要渲染出來

### 💻 复现代码
[問題復現](https://codesandbox.io/s/nifty-christian-jz506u?file=/App.tsx)

### © 版本信息
@ant-design/pro-layout@7.10.2

- 浏览器环境: [Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (arm64)](https://brave.com/latest/)
- 开发环境 mac OS

### 🚑 其他信息
<img width="529" alt="image" src="https://user-images.githubusercontent.com/67179608/225511842-a2a99eec-c470-4589-a96b-db10bb08272d.png">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据提供的代码以及截图，可以看出 backIcon 是被渲染出来了的，只是颜色是透明的，导致看不到，可以通过设置颜色为黑色或其他颜色来解决，如下示例代码：

```jsx
<PageHeader
  extra={action}
  onBack={() => this.props.history.goBack()}
  title="Title"
  subTitle="This is a subtitle"
  backIcon={<Icon type="left" style={{ color: '#000' }} />}
/>
```

更多关于 PageHeader 的用法，可以查看官方文档：https://ant.design/components/page-header-cn/

**Comment by chenshuai2144** [comment]
onBack 一定要存在的

**Comment by EvenC-tw** [comment]
感謝回覆，問題已解決。
建議官方文檔上附註說明兩屬性的關聯使用方式。
