### ISSUE TITLE
🧐[问题]valueEnum支持像ProFormSelect一样支持request，从从网络请求枚举数据？

### ISSUE THREAD

**Issue by liuchuangjun321** [ant-design/pro-components#679]

**Comment by chenshuai2144** [comment]
暂时是不会的，valueEnum 希望是个静态的，而不是动态的

**Comment by liuchuangjun321** [comment]
> 暂时是不会的，valueEnum 希望是个静态的，而不是动态的

valueEnum 希望是个静态的，而不是动态的
请问是出于什么样的考虑呢？

**Comment by chenshuai2144** [comment]
>  valueEnum 希望是个静态的，而不是动态的
请问是出于什么样的考虑呢？

render 这个函数会被执行很多次，如果支持远程，会被请求非常多次，而且还要处理什么时候更新的问题。

**Comment by zhoufeii** [comment]
> > valueEnum 希望是个静态的，而不是动态的
> > 请问是出于什么样的考虑呢？
> 
> render 这个函数会被执行很多次，如果支持远程，会被请求非常多次，而且还要处理什么时候更新的问题。

#150 这个issue里面可以动态赋值，并且表格表头中的筛选选项中有新的值，但是顶部表单筛选里面仍然取不到新的值
![image](https://user-images.githubusercontent.com/36029402/97677464-3f723800-1acd-11eb-9745-b1e6b8cc6eff.png)
