### ISSUE TITLE
🐛[BUG] breadcrumbProps 配置 itemRender 后，会多包一层a标签

### ISSUE THREAD

**Issue by Cyan-Xmw** [ant-design/pro-components#6790]
### 🐛 bug 描述

breadcrumbProps 配置 itemRender 后，会多包一层a标签，会导致控制台报错
![image](https://user-images.githubusercontent.com/40554571/225554088-57aca199-1ad1-4593-a702-c107026bd367.png)
![image](https://user-images.githubusercontent.com/40554571/225554865-efeed1e7-b8e8-4496-b685-0eddf345d83f.png)

### 🏞 期望结果
在使用 itemRender 后，去掉外层的 a 标签，好像之前没有这个问题

### 💻 复现代码

[](https://github.com/Cyan-Xmw/Xmw-Admin/blob/Cyan/Xmw_web/src/components/BasiLayout/index.tsx)

### © 版本信息

- ProComponents 版本: ^2.4.2
- umi 版本: ^4.0.59
- 浏览器环境: Google Chrome
- 开发环境 : Windows

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


可能是 itemRender 回调函数返回的元素包含了一层 a 标签，可以尝试在回调函数内部组装需要的元素，而不是返回一个包含 a 标签的元素。例如：

```jsx
import { Breadcrumb } from 'antd';

function itemRender(route, params, routes, paths) {
  const { path, breadcrumbName } = route;
  return (
    <span>{breadcrumbName}</span>
  );
}

function MyBreadcrumb(props) {
  const { routes } = props;
  
  return (
    <Breadcrumb itemRender={itemRender} routes={routes} />
  );
}
```

在上面的例子中，itemRender 回调函数内部组装了一个仅包含文字的 span 元素，避免了包含 a 标签的问题。

更详细的关于 Breadcrumb 组件和 itemRender 配置的使用可以参考官方文档：https://ant.design/components/breadcrumb-cn/

**Comment by Cyan-Xmw** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> 可能是 itemRender 回调函数返回的元素包含了一层 a 标签，可以尝试在回调函数内部组装需要的元素，而不是返回一个包含 a 标签的元素。例如：
> 
> ```js
> import { Breadcrumb } from 'antd';
> 
> function itemRender(route, params, routes, paths) {
>   const { path, breadcrumbName } = route;
>   return (
>     <span>{breadcrumbName}</span>
>   );
> }
> 
> function MyBreadcrumb(props) {
>   const { routes } = props;
>   
>   return (
>     <Breadcrumb itemRender={itemRender} routes={routes} />
>   );
> }
> ```
> 
> 在上面的例子中，itemRender 回调函数内部组装了一个仅包含文字的 span 元素，避免了包含 a 标签的问题。
> 
> 更详细的关于 Breadcrumb 组件和 itemRender 配置的使用可以参考官方文档：https://ant.design/components/breadcrumb-cn/

![image](https://user-images.githubusercontent.com/40554571/225787835-630e454d-b02f-4712-bb2e-6992a8d5b603.png)
但是还是会包裹一层a标签，而且还是 哈希链接，跳转无反应，在我的理解，如果使用了 itemRender ，那么子元素里面应该就是用户自定义的，不用包裹什么。
![image](https://user-images.githubusercontent.com/40554571/225789319-57fd0a0c-278d-4fb9-9a93-ee6f0f271b37.png)
不然官方这个描述也不对，渲染还是有两层 a 标签，虽然功能不受影响，但是控制台一直警告，希望可以去掉

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢反馈。我看到你的截图中确实出现了两层 a 标签的情况。根据你提供的代码和截图，可以尝试如下解决方案：

```jsx
import { Breadcrumb } from 'antd';

function itemRender(route, params, routes, paths) {
  const { path, breadcrumbName } = route;
  if (route.component !== undefined) {
    return <span>{breadcrumbName}</span>;
  }
  return null;
}

function MyBreadcrumb(props) {
  const { routes } = props;
  
  return (
    <Breadcrumb itemRender={itemRender} routes={routes} />
  );
}
```

这里通过判断 route 对象是否存在 component 属性来决定是否需要渲染链接。如果 component 存在说明当前是一个可跳转的页面，则渲染 span 标签的包裹，否则返回 null。

希望这个问题能够解决，如果还有其他问题，请随时在 issue 中提出来。

**Comment by Cyan-Xmw** [comment]
> ```js
> const { path, breadcrumbName } = route;
>   if (route.component !== undefined) {
>     return <span>{breadcrumbName}</span>;
>   }
>   return null;
> ```

![image](https://user-images.githubusercontent.com/40554571/225860322-dad92d22-ad79-49e6-ba39-31714133f46f.png)
不知道你是不是误解我的意思，我意思是说，如果像截图这样写法，我希望组件不要再给我套一层 a 标签，而且套的链接还不对，我就希望 li 里面就只有 一个 span 标签
