### ISSUE TITLE
使用ProTable 的ellipsis:true 时候 只展示Tooltip ,不能使用title 方式 ,非常需要去展示title 的样子 ,而不是Tooltip 样子

### ISSUE THREAD

**Issue by ganxueping** [ant-design/pro-components#6793]
使用ProTable 的ellipsis:true 时候 只展示Tooltip ,不能使用title 方式 ,非常需要去展示title 的样子 ,而不是Tooltip 样子

**Comment by chenshuai2144** [comment]
自定义render 是最好的办法，如果你和默认的不同

**Comment by ganxueping** [comment]
已经解决 非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月16日(星期四) 晚上10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 使用ProTable 的ellipsis:true 时候 只展示Tooltip ,不能使用title 方式 ,非常需要去展示title 的样子 ,而不是Tooltip 样子 (Issue #6793)





 
自定义render 是最好的办法，如果你和默认的不同
