### ISSUE TITLE
🐛[BUG] ProFormTextArea  readonly 时内容包含英文不会换行

### ISSUE THREAD

**Issue by mwj610** [ant-design/pro-components#6795]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProFormTextArea ` readonly`时内容包含英文不会换行
### 📷 复现步骤
https://codesandbox.io/s/adoring-moser-lxfefm?file=/App.tsx

### 🏞 期望结果
可以换行

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


可以通过在 ProFormTextArea 组件中设置 whiteSpace 属性为 "pre-wrap" 来解决该问题。代码示例如下：

```jsx
<ProFormTextArea
  name="demo"
  label="Multiline"
  placeholder="Please enter"
  readonly
  style={{ whiteSpace: "pre-wrap" }} // 设置 whiteSpace
/>
```

此外，该属性还可以将其他特殊字符也转换为可显示的字符，具体可以参考文档：[white-space](https://developer.mozilla.org/zh-CN/docs/Web/CSS/white-space)。
