### ISSUE TITLE
protable 列对不齐 🐛[BUG]

### ISSUE THREAD

**Issue by yangzhibin-git** [ant-design/pro-components#6796]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

![图片](https://user-images.githubusercontent.com/5546391/225610563-3f8bf07f-0da6-48f4-8c59-5fbbe62a4624.png)

**Comment by chenshuai2144** [comment]
title 和内容走的不是一个属性，你要剧中要用flex再render包裹一下
