### ISSUE TITLE
🐛prolayout对StatisticCard样式有影响 [BUG]

### ISSUE THREAD

**Issue by yangzhibin-git** [ant-design/pro-components#6798]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
![图片](https://user-images.githubusercontent.com/5546391/225802409-fdec349f-e2a6-4a79-add2-476be758dbf0.png)

![图片](https://user-images.githubusercontent.com/5546391/225802191-d8632acf-47e9-499a-b2a5-25ab25816738.png)

**Comment by chenshuai2144** [comment]
能看看是什么样子被覆盖了吗？

**Comment by yangzhibin-git** [comment]
![图片](https://user-images.githubusercontent.com/5546391/225807399-4ff763f0-2a98-43b2-b497-a45cfd3f71b4.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


看到您的截图，这应该是antd的一个已知问题，ProLayout甚至是其它根据antd封装的组件都会出现类似的问题。这是由于antd的一些样式的问题导致了这个问题。

为了解决这个问题，可以使用以下两种方法的一种，具体方法如下：

1.在您的index.less中加入如下代码：
```less
@import '~antd/lib/style/themes/default.less';
```

2.或者在问题组件所在的页面中加入如下代码，例如：
```javascript
import 'antd/dist/antd.css';
```

这些代码可以解决antd样式问题，并且在该页面中引入antd的统计卡片组件（StatisticCard）时，样式不会被覆盖。此外，我们建议大家在使用antd组件时，优先使用antd的官方组件文档进行开发。

参考链接：
[antd的GitHub首页](https://github.com/ant-design/ant-design) 。

**Comment by chenshuai2144** [comment]
get，看来是样式优先级的问题

**Comment by yangzhibin-git** [comment]
![图片](https://user-images.githubusercontent.com/5546391/234480915-42d92ac1-fdc1-4d62-8593-3d7154a811d6.png)

升级到^2.4.3 还是不行

**Comment by yangzhibin-git** [comment]
![图片](https://user-images.githubusercontent.com/5546391/234481154-8aeeda66-23b7-4bed-abf5-dcfbc320ce87.png)

**Comment by yangzhibin-git** [comment]
@chenshuai2144 这个bug没修复
