### ISSUE TITLE
对于chrome88版本之下的浏览器是不准备兼容了吗  官网这个样

### ISSUE THREAD

**Issue by SGDS666** [ant-design/pro-components#6800]
![image](https://user-images.githubusercontent.com/86196091/225825693-33ce8bed-860f-41d0-8354-436b7ca9ac29.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您的提问。针对您的问题，我可以给出以下解决方案：

根据官网提示，Chrome 88 版本之前的浏览器将不再兼容 React。但对于已经安装的老版本的浏览器，您仍可以使用 polyfill 等工具来提供相应的支持。

具体来说，您可以使用 babel 和 @babel/preset-env 插件来转译代码，在打包构建时使用 core-js 和 regenerator-runtime 等 polyfill 转换器进行代码适配，从而兼容较老浏览器。

以下是一个简单的示例，仅供参考：

```js
// .babelrc

{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": [
            "last 2 versions",
            "not ie <= 10"
          ]
        }
      }
    ],
    "@babel/preset-react"
  ]
}

// package.json
{
  "dependencies": {
    "@babel/core": "^7.12.10",
    "@babel/preset-env": "^7.12.11",
    "@babel/preset-react": "^7.12.10",
    "core-js": "^3.10.1",
    "regenerator-runtime": "^0.13.7"
  }
}

// webpack.config.js
module.exports = {
  // ...
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            cacheDirectory: true
          }
        }
      }
    ]
  }
};
```

希望能够帮到您，如有不清楚的地方可以再向我提问。同时，如果您需要更详细的文档，可以参考以下链接：

- [React文档：支持的浏览器与平台](https://zh-hans.reactjs.org/docs/react-dom.html#browser-support)
- [Babel官网](https://babeljs.io/docs/en/)
- [Core JS官网](https://github.com/zloirock/core-js)
- [Webpack官网](https://webpack.js.org/)

**Comment by chenshuai2144** [comment]
要做特殊的兼容性处理，官网推荐> 以下浏览器版本

<img width="421" alt="image" src="https://user-images.githubusercontent.com/8186664/226099987-202b2701-fd4b-4dd0-8c1d-78dc521dad4b.png">
