### ISSUE TITLE
ProTable中tableAlertOptionRender中selectedRowKeys有值,selectedRows为空？

### ISSUE THREAD

**Issue by zyxmz** [ant-design/pro-components#6803]
### Reproduction link

[https://procomponents.ant.design/components/table](https://procomponents.ant.design/components/table)

### Steps to reproduce

tableAlertOptionRender={({selectedRows})=>{}}
selectedRows打印出来为空数组

### What is expected?

---

### What is actually happening?

----

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.0 |
| System | 4.16.1 |
| Browser | chrome |

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，可能的原因有以下几点：

1. 是否有一些其他的操作改变了 selectedRows 的值。可以在获取到该值时进行一次打印确认，确定是否有值。

2. 是否使用了 pagination 等分页插件，如果使用，需要将 tableAlertOptionRender 和 selectedRowKeys 放在 PageHeaderWrapper 组件的 settings 参数中，具体的使用可以参考官方文档：

   https://procomponents.ant.design/components/layout#pageheaderwrapper

3. 是否在表格中使用了 rowSelection 参数，并且将其与 tableAlertOptionRender 参数绑定。如果使用了 rowSelection 参数，需要确认其是否已正确的绑定到 tableAlertOptionRender 中，可以查看官方文档来确认使用方法：

   https://procomponents.ant.design/components/table/#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95

若以上方法无法解决问题，建议提供更多的代码来使问题更明确。

**Comment by chenshuai2144** [comment]
demo 看起来没问题，是不是 rowkey 配置错了？

**Comment by zyxmz** [comment]
感谢你的回复！我跟朋友最后发现用selectedRowKeys确实会有问题。比如我勾选三条数据，会返回两条，两条会返回一条，一条的话就返回空。因为我之前都是勾选一条，没有返回，所有我误以为是返回空。但实际操作下来返回的会减掉最后一条。但是最后用defaultSelectedRowKeys就不会有这个问题。

发自我的iPhone

**Comment by zyxmz** [comment]
发自我的iPhone
