### ISSUE TITLE
🐛[BUG] ProTable 中 formRef 为 null

### ISSUE THREAD

**Issue by hooliy** [ant-design/pro-components#6804]
### 🐛 bug 描述

 ProTable 中 设置了 formRef ，但是获取到的 formRef 值为 null

<img width="214" alt="image" src="https://user-images.githubusercontent.com/3368691/225847659-75bab287-a731-404b-8c60-7e0bca77ff18.png">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 可能的原因和解决方案

1. 确认是否在 `ProTable` 中正确配置和使用 `formRef`，参考 [Antd Form 官方文档](https://ant.design/components/form-cn/#Form.useForm)

2. 若确保配置正确，可以尝试升级 `antd` 和 `pro-table` 版本，因为此问题在低版本中有可能存在，升级后再尝试。

3. 可能是因为在获取 `formRef` 的时候组件还未完成渲染，可以尝试使用 `useEffect` 延迟一些时间再获取 `formRef`。

```jsx
import { useRef, useEffect } from 'react';
import { ProForm, ProTable } from '@ant-design/pro-table';
import { Button } from 'antd';

export default function Demo() {
  const formRef = useRef();
  useEffect(() => {
    console.log(formRef.current); // undefined
    // 延迟1s再获取
    setTimeout(() => {
      console.log(formRef.current); // 正常输出formRef
    }, 1000);
  }, []);

  return (
    <div>
      <ProTable
        formRef={formRef}
        columns={[
          {
            title: '编号',
            dataIndex: 'index',
            valueType: 'indexBorder',
          },
          {
            title: '标题',
            dataIndex: 'title',
          },
        ]}
        request={async () => {
          return {
            data: [
              {
                title: '示例标题1',
              },
              {
                title: '示例标题2',
              },
            ],
            success: true,
          };
        }}
        rowKey="title"
        footer={() => (
          <Button onClick={() => console.log(formRef.current)}>获取 formRef</Button>
        )}
      />
      <ProForm
        onFinish={(values) => console.log(values)}
        submitter={{
          resetButtonProps: false,
          submitButtonProps: false,
        }}
        formRef={formRef}
      >
        <ProFormText name="field1" label="输入框" />
      </ProForm>
    </div>
  );
}
```


### 参考链接

- [Antd Form 官方文档](https://ant.design/components/form-cn/#Form.useForm)
- [github issue 相关讨论](https://github.com/ant-design/pro-components/issues/4918)
