### ISSUE TITLE
umi3.5中升级pro-table报错

### ISSUE THREAD

**Issue by bans-hou** [ant-design/pro-components#6807]
### in ./node_modules/@ant-design/pro-table/node_modules/swr/_internal/dist/index.mjs

Module not found: Error: Can't resolve 'F:/androidworkspace/frontend/node_modules/@umijs/bundler-utils/node_modules/@babel/runtime/helpers/esm/createForOfIteratorHelper' in 'F:\androidworkspace\frontend\node_modules\@ant-design\pro-table\node_modules\swr\_internal\dist'

![升级pro-table报错](https://user-images.githubusercontent.com/28709540/225853764-13b8002c-0eda-4fa8-9c7d-0a00689eb3a0.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题是由于部分插件在 umi3.5 中升级后与 pro-table 不兼容导致的。

解决方案：

1. 确认你的 umi 版本是3.5及以上，antd 版本是4.16以上，pro-table 版本是3.1.1及以上。
2. 升级 node.js 至最新版本。
3. 在 package.json 文件中将 pro-table 的版本降级到 3.0.4。
4. 在终端执行 `npm install` 命令重新安装依赖。

如果以上方法不能解决问题，可能需要升级其他的插件或者等待插件作者更新兼容性。

如果你想了解更多关于 pro-table 和 swr 之间的兼容性问题，请查阅以下文档：

1. pro-table 安装指南：https://protable.ant.design/guide/install-cn
2. swr 官方文档：https://swr.vercel.app/docs/getting-started
3. 常见兼容性问题解决办法：https://protable.ant.design/guide/question-cn

**Comment by bans-hou** [comment]
因为我用到Protable的toobars的menu,出现抖动,我想升级.倒是报错阻止了我.您有相关案例吗分享一下.
