### ISSUE TITLE
🐛[BUG]ProDescriptions部分valueType存在垂直样式不居中的bug

### ISSUE THREAD

**Issue by finalmachine** [ant-design/pro-components#6808]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProDescriptions 使用columns属性的时候，如果有的columns是valueType是digit、money等，垂直方向不能居中显示，跟align-items是baseline有关。

### 📷 复现步骤

<ProDescriptions
                dataSource={{
                    rate: 5,
                    id: '这是一段文本columns',
                    date: '20200809',
                    money: '1212100',
                    state: 'all',
                    state2: 'open',
                }}
                editable={{}}
                columns={[
                    {
                        title: '分值',
                        dataIndex: 'fraction',
                        valueType: "digit"
                    }
                ]}
/>

点击编辑按钮，然后看打钩和打叉两个按钮的垂直位置

实际的结果
![image](https://user-images.githubusercontent.com/12266907/225885700-69d50da1-21ba-4559-bdcc-9b5a326f7f97.png)

期望的结果
![image](https://user-images.githubusercontent.com/12266907/225887605-409fad19-66a8-4f83-b5c5-0a1796c66a18.png)

### © 版本信息
- ProComponents 版本: 
"@ant-design/pro-components": "2.4.2",
"antd": "5.3.1",
- 浏览器环境 edge 111.0.1661.41
- 开发环境  mac OS

### 🚑 其他信息

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，根据您提供的信息，这个问题可能是由于 ProDescriptions 组件的 align-items 默认值为 baseline 导致的。您可以尝试在样式中添加以下代码来强制将 align-items 设为 center：

```css
.ant-descriptions-row > td {
  align-items: center;
}
```

如果您需要进一步了解 ProDescriptions 的样式方案，可以参考其官方文档：https://procomponents.ant.design/components/descriptions-cn/ 

希望对您有所帮助！

**Comment by finalmachine** [comment]
![image](https://user-images.githubusercontent.com/12266907/226252680-323a8b3b-39fb-4400-a80a-59e9470d942c.png)

这个链接无效

**Comment by finalmachine** [comment]
虽然最后不是用的你给的代码，但是用你给的思路强制修改了css样式，谢谢你
