### ISSUE TITLE
👑 [需求] ProLayout  搜索菜单。如何仅返回有子菜单的结果

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#6810]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

比如搜索“其他”，“其他”菜单是一个父级菜单，含有子菜单。搜索结果仅返回当前父级菜单，造成当前父级菜单无法点击

https://procomponents.ant.design/~demos/packages-layout-src-components-layout-tab-api-demo-searchmenu

**Comment by chenshuai2144** [comment]
有兴趣来个pr吗？
