### ISSUE TITLE
🐛[BUG]树表格展开时的缩进问题

### ISSUE THREAD

**Issue by Elieen-v** [ant-design/pro-components#6811]
### 🐛 bug 描述

使用proTable，树表格在展开时，二级，三级没有缩进，尝试修改了expandable 属性里面的相关属性，例如indentSize和childrenColumnName依然无效，但相同数据使用table可以实现缩进。
![image](https://user-images.githubusercontent.com/110799511/226230511-5728c922-c00e-4615-b837-d1d4612d4ffe.png)

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/110799511/226230465-9f79d540-4940-4a06-b5fb-7a4caba63ae6.png)

### 🏞 期望结果

展开一级，二级三级，默认缩进。
![image](https://user-images.githubusercontent.com/110799511/226230623-73827a84-526b-4419-a12c-647d81b0b2cc.png)

### 💻 复现代码

    <ProTable<SYSTEM_ENTITY.SystemList>
      headerTitle="体系表格"
      rowKey="id"
      actionRef={actionRef}
      expandable={{ expandedRowKeys: expandedRowKeys }}
      onExpand={(expanded, record) => {
        if (expanded) {
          setExpandedRowKeys(expandedRowKeys.concat(record.id));
        } else {
          if (expandedRowKeys.indexOf(record.id) !== -1)
            setExpandedRowKeys(expandedRowKeys.filter((item) => item !== record.id));
        }
      }}
      request={async (params) => {
        return getData(params);
      }}
      pagination={false}
      columns={columns}
      revalidateOnFocus={false}
      onReset={() => {
        setExpandedRowKeys([]);
        setFlag(false);
      }}
    />

### © 版本信息

ProComponents 版本: [@2.4.2]
umi 版本 [v3.x]
浏览器环境[edge ,google]
开发环境 [window]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


可以在columns中使用render方法自定义展示每一行的内容，利用缩进实现树形结构的效果。

示例代码如下：

```jsx
const columns = [
  {
    title: '名称',
    dataIndex: 'name',
    key: 'name',
    render: (text, record) => (
      <span style={{ paddingLeft: (record.level - 1) * 20 }}>
        {record.children && record.children.length > 0 ? (
          <a onClick={() => handleExpand(record)}>{text}</a>
        ) : (
          text
        )}
      </span>
    ),
  },
  // 其他列配置
];

const handleExpand = (record) => {
  const keys = [...expandedRowKeys];
  if (keys.includes(record.id)) {
    // 关闭
    keys.splice(keys.indexOf(record.id), 1);
  } else {
    // 打开
    keys.push(record.id);
  }
  setExpandedRowKeys(keys);
};
```

在render中根据record的level属性设置对应的paddingLeft值来控制缩进的距离，handleExpand方法则用于处理展开和关闭的逻辑。同时，注意要在ProTable中加入rowClassName属性，用于为每一行添加对应的className，否则样式可能会出现问题。

```jsx
<ProTable
  columns={columns}
  dataSource={dataSource}
  rowKey="id"
  rowClassName={(record) => record.children && record.children.length > 0 ? 'tree-node' : ''}
  expandable={{
    expandedRowKeys: expandedRowKeys,
    onExpand: (expanded, record) => handleExpand(record),
  }}
  pagination={false}
/>
```

参考文档：https://ant.design/components/table-cn/#props

**Comment by Elieen-v** [comment]
> ```js
> keys.indexOf(record.id)
> ```

可以实现~感谢！

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


回答不周，非常抱歉。这个方法是用于在数组 `keys` 中查找下标，即返回 `record.id` 在 `keys` 中第一次出现的位置，如果没找到则返回 -1。这里的作用是用于控制展开和关闭的逻辑，用于判断是否在 `expandedRowKeys` 中。

如果您还有其他问题或疑问，请随时回复。

**Comment by lookdczar** [comment]
和我之前遇到的一样。因为columns里面，你的立体名称不是第一列，前面还有一列专门用来放那个 + icon。这个缩进只对第一列有效
