### ISSUE TITLE
🐛[BUG] pro layout 收缩样式错误

### ISSUE THREAD

**Issue by susanforme** [ant-design/pro-components#6814]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

pro layout 收缩样式错误

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- "@ant-design/pro-components": "2.3.53",
- umi 版本
-     "@umijs/max": "^4.0.32",

- 浏览器环境

### 🚑 其他信息
pro layout 展开正常
![7215B98F-063E-4e7a-A9B7-3A3FB6A81450](https://user-images.githubusercontent.com/51266600/226235091-c4973afd-0b3f-41ce-9481-388e5917326e.png)

收缩不正常
![image](https://user-images.githubusercontent.com/51266600/226235123-ba8c14a2-ee97-4351-84e8-1ff0b2511249.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，根据你提供的信息，我们暂时无法确定具体的问题出在哪里。可能是 CSS 样式没有设置好，也可能是组件的属性没有设置正确。不过下面是一些可能有帮助的解决方案：

1. 检查 CSS 样式，特别是收缩状态下的元素的样式。你可以使用浏览器的调试工具检查这些元素的样式是否正确。如果样式没有设置好，你可以使用 CSS 来调整。

2. 检查 pro layout 组件的属性是否设置正确。特别是 `collapsed` 属性、`collapsedButtonRender` 属性和 `menuRender` 属性。你可以检查这些属性的值是否正确，并根据需要调整它们的值。

3. 查看相关文档，了解 pro layout 组件的用法。你可以在官方文档中找到关于该组件的详细用法和配置方法。如果你在使用组件时遇到问题，你可以在文档中寻找更多信息，并解决你的问题。文档链接：https://procomponents.ant.design/components/layout。

希望这些信息可以帮助到你解决问题。如果仍然存在问题，请提供更多信息，以便我们更好地解决你的问题。
