### ISSUE TITLE
🐛[BUG]树表格tableAlertRender属性中使用selectedRows只能拿到一级信息，二级信息undefined

### ISSUE THREAD

**Issue by Eileen-v** [ant-design/pro-components#6815]
### 🐛 bug 描述
在树表格的tableAlertRender属性中使用selectedRows只能拿到一级信息，二级三级信息undefined
![image](https://user-images.githubusercontent.com/110799511/226235327-0557a3db-26ab-4c40-8c5a-1eaf82c84ad5.png)

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/110799511/226235150-72433378-cb67-435c-9436-6984be973de9.png)

### 🏞 期望结果

选中之后可以拿到选中行的所有信息

### 💻 复现代码

<ProTable<SYSTEM_ENTITY.SystemList>
          headerTitle="体系表格"
          rowKey="id"
          actionRef={actionRef}
          expandable={{ expandedRowKeys: expandedRowKeys }}
          onExpand={(expanded, record) => {
            if (expanded) {
              setExpandedRowKeys(expandedRowKeys.concat(record.id));
            } else {
              if (expandedRowKeys.indexOf(record.id) !== -1)
                setExpandedRowKeys(expandedRowKeys.filter((item) => item !== record.id));
            }
          }}
          request={async (params) => {
            return getData(params);
          }}
          pagination={false}
          columns={columns}
          revalidateOnFocus={false}
          search={{
            filterType: filterType ? 'light' : 'query',
          }}
          onReset={() => {
            setExpandedRowKeys([]);
            setFlag(false);
          }}
          scroll={filterType ? { y: 600 } : undefined}
          rowSelection={{type: 'checkbox',}}
          tableAlertRender={({ selectedRows }) => {
            console.log(selectedRows,'selectedRow');
            return 0
          }}
          tableAlertOptionRender={({ selectedRows })=>{
            console.log(selectedRows,'selectedRowsaaaaa');
            return <span>aaaaaaaaaaaaaaaaaa</span>
          }}
        />

### © 版本信息

ProComponents 版本: [@2.4.2]
umi 版本 [v3.x]
浏览器环境[edge ,google]
开发环境 [window]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


该问题可能是 ProTable 内部的一个问题，您可以在参考 [ProTable 的官方文档中的树形表格部分](https://procomponents.ant.design/components/table#%E6%A0%91%E5%BD%A2%E8%A1%A8%E6%A0%BC) 中提出该问题。

关于您的问题，可能是因为 `selectedRows` 只会返回第一层选择的行信息，因此无法拿到所有选定行的信息，您可以尝试使用 `onSelection` 而不是 `tableAlertRender` 来获取选定的行信息。具体操作如下：
- 设置 `rowSelection` 的 `onChange` 属性来更新已选择的行
- 在 `onSelection` 中处理选定行信息

以下是代码示例：

```jsx
<ProTable
  /* 其他的配置和属性 */
  rowSelection={{
    type: 'checkbox',
    onChange: (selectedRowKeys, selectedRows) => {
      setCheckedKeys(selectedRowKeys);
      setCheckedRows(selectedRows);
    }
  }}
  onSelection={(keys, rows) => console.log("Selected Rows: ", rows)}
/>  
```

希望能够帮助您。

**Comment by Elieen-v** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> 该问题可能是 ProTable 内部的一个问题，您可以在参考 [ProTable 的官方文档中的树形表格部分](https://procomponents.ant.design/components/table#%E6%A0%91%E5%BD%A2%E8%A1%A8%E6%A0%BC) 中提出该问题。
> 
> 关于您的问题，可能是因为 `selectedRows` 只会返回第一层选择的行信息，因此无法拿到所有选定行的信息，您可以尝试使用 `onSelection` 而不是 `tableAlertRender` 来获取选定的行信息。具体操作如下：
> 
> * 设置 `rowSelection` 的 `onChange` 属性来更新已选择的行
> * 在 `onSelection` 中处理选定行信息
> 
> 以下是代码示例：
> 
> ```js
> <ProTable
>   /* 其他的配置和属性 */
>   rowSelection={{
>     type: 'checkbox',
>     onChange: (selectedRowKeys, selectedRows) => {
>       setCheckedKeys(selectedRowKeys);
>       setCheckedRows(selectedRows);
>     }
>   }}
>   onSelection={(keys, rows) => console.log("Selected Rows: ", rows)}
> />  
> ```
> 
> 希望能够帮助您。

可以实现~感谢！

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


很高兴能够帮到您，如果有任何其他问题或疑问，请随时联系。祝您使用愉快！
