### ISSUE TITLE
🐛[BUG] ProTable 重置 columns 中某个 filteredValue (空数组)的时候 UI 显示/数据有误

### ISSUE THREAD

**Issue by onlyling** [ant-design/pro-components#682]
### 🐛 bug 描述

columns 中带有筛选，filteredValue 默认是空数组，筛选一个值后，手动 setDate 更新已有值 filteredValue 为空数组，目的是为了清空筛选项。ProTable 并没有更新对应的筛选 UI 状态。

把 ProTable 换成 Table 就显示正常。

目前看起来是 [ProTable 初始化数据的时候做了一次数组过滤 `return omitUndefinedAndEmptyArr(tempColumns)`](https://github.com/ant-design/pro-components/blob/master/packages/table/src/Table.tsx#L467)

### 📷 复现步骤

1. 访问 TestFC 对应的页面；
2. 筛选一个状态，例如「待审核」；
3. 点击「清除筛选」；

按照预期「筛选」不会有对应的已选数据。

### 🏞 期望结果

与 Table 组件表现一致

### 💻 复现代码

```js
const TestFC = () => {
  const [columns, setColumns] = useState([
    {
      title: "筛选",
      dataIndex: "test",
      filteredValue: ["0"],
      filters: [
        { text: "草稿", value: 0, color: "magenta" },
        { text: "待审核", value: 1, color: "red" },
        { text: "已发布", value: 2, color: "green" },
        { text: "已驳回", value: 3, color: "volcano" },
        { text: "已下架", value: 4, color: "orange" },
      ],
    },
  ]);
  // 列表数据，不通过 ProTable 的 request 方式获取的
  const [list] = useState([]);

  /**
   * 手动重置筛选
   */
  const onClickClearTest = () => {
    setColumns((cs) => [
      {
        ...cs[0],
        filteredValue: [],
      },
    ]);
  };

  // 其他操作
  // ...

  return (
    <>
      <p>
        <span onClick={onClickClearTest}>清除筛选</span>
      </p>

      <ProTable rowKey="id" dataSource={list} columns={columns} />
    </>
  );
};

```

> 实际方案是把参数放到 URL 上，每次参数变化都会重新生成一个新的 `columns`，数据变现和上面的变现的状况差不多。

### © 版本信息

- ProComponents 版本：mac OS
- umi 版本：3.2.23
- 浏览器环境：Google Chrome 85.0.4183.121
- 开发环境：mac OS 10.15.7 

### 🚑 其他信息

没有使用 request 方案还是自带 onFilter，[onFilter: propsRef.current?.request ? undefined : (value: string, row: T) => defaultOnFilter(value, row, dataIndex as string[])](https://github.com/ant-design/pro-components/blob/master/packages/table/src/Table.tsx#L439)，这有不清楚是怎么了。

**Comment by chenshuai2144** [comment]
来个pr把

**Comment by chenshuai2144** [comment]
已经修了

**Comment by onlyling** [comment]
> 已经修了

对应的代码变更

```tsx
// 制造筛选的数据
setProFilter(omitUndefined<any>(filters));
```

> proFilter 用于 request 时的一个参数。

好像没有修复。

ProTable 使用 Table 的时候，数据来源 [tableProps(Table.tsx#L821)](https://github.com/ant-design/pro-components/blob/master/packages/table/src/Table.tsx#L821)，`columns` 的数据来自内部的 `container.columns`，它的数据来源来自 [tableColumn(Table.tsx#L650)](https://github.com/ant-design/pro-components/blob/master/packages/table/src/Table.tsx#L650)。

饶了一圈，问题还是回到了上文中提到的 [`return omitUndefinedAndEmptyArr(tempColumns)`(#L467)](https://github.com/ant-design/pro-components/blob/master/packages/table/src/Table.tsx#L467)。

这里不清楚为什么要过滤数组，初步打算是在 `omitUndefinedAndEmptyArr` 上添加一个 `excludes` 字符串数组参数，用于跳过不需要过滤的字段，不确定这样的更改是否合理。
