### ISSUE TITLE
columnEmptyText 这个属性我加了没有用 是bug吗🐛[BUG]

### ISSUE THREAD

**Issue by 18262992561** [ant-design/pro-components#6820]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

<ProTable
      headerTitle={headerTitle}
      className="sctable-demo"
      actionRef={actionRef}
      toolBarRender={() => getRenderButton(buttonList)}
      columns={columns}
      rowKey={rowKey}
      rowSelection={{
        ...rowSelection(selectedRows, setSelectedRows, rowKey, selectedRecords, setSelectedRecords),
        getCheckboxProps: getCheckboxProps,
      }}
      pagination={{
        showSizeChanger: true,
        showQuickJumper: true,
        defaultPageSize: 10,
        showTotal: (total) => <span className="paginationText">{`共${total}条`}</span>,
      }}
      tableAlertRender={({ selectedRowKeys }) =>
        tableAlertRender(selectedRowKeys, setSelectedRows, setSelectedRecords)
      }
      request={async (params) => {
       
        return {
          data: [],
          success: true,
          total: 0,
        };
      }}
      columnEmptyText="为什么不是自定义的空text呀呀呀"
      
      {...others}
    />

### 📷 复现步骤

我只是相加一个属性  自定义我的空数据描述 但是好像没有生效  一直是暂无数据

### 🏞 期望结果

希望那个暂无数据的提示被替换成我自定义的文字描述

### © 版本信息

- ProComponents 版本: [2.3.48]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/103157749/226533172-4167f67f-243e-48c5-9b80-e430b07ddf8c.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，根据你提供的信息看起来似乎没什么问题，但我需要确认一下一些细节。

1. 你的 ProTable 组件是哪个版本的？请提供完整的版本号。

2. 你确定你使用的是 columnEmptyText 属性而不是 emptyText 属性吗？请确认一下代码是否有误。

3. 另外，在 ProTable 组件文档中，有一些说明：

```
// 设置空标识信号，当 dataSource.length === 0 && loading === false 的时候触发、
// 支持 空字符串 | ReactNode | () => ReactNode 三种类型。
emptyText: '暂无数据',
```

你可以尝试设置 emptyText 属性，看看是否可以生效。

如果以上步骤无法解决你的问题，请留下你的详细环境信息和运行环境，以便更好地定位问题。同时，你也可以参考以下文档：

https://procomponents.ant.design/components/table/#API

希望这些信息能对你有所帮助。

**Comment by 18262992561** [comment]
1、版本依赖
"dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-components": "^2.3.48",
    "@ant-design/pro-descriptions": "^1.2.0",
    "@ant-design/pro-form": "^1.3.0",
    "@ant-design/pro-layout": "^6.9.0",
    "@ant-design/pro-table": "^2.17.0",
    "antd": "^4.24.5",
...
}
"engines": {
    "node": ">=10.0.0"
  },
2、import { ProTable } from "@ant-design/pro-components"; 这是我import的代码
request={} 返回的对象是 { data:[] ,total:0} 这样子应该会出现空text 但是仍然是 "暂无数据"

**Comment by 18262992561** [comment]
```
1、版本依赖
"dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-components": "^2.3.48",
    "@ant-design/pro-descriptions": "^1.2.0",
    "@ant-design/pro-form": "^1.3.0",
    "@ant-design/pro-layout": "^6.9.0",
    "@ant-design/pro-table": "^2.17.0",
    "antd": "^4.24.5",
...
}
"engines": {
    "node": ">=10.0.0"
  },
2、import { ProTable } from "@ant-design/pro-components"; 这是我import的代码
request={} 返回的对象是 { data:[] ,total:0} 这样子应该会出现空text 但是仍然是 "暂无数据"
```
