### ISSUE TITLE
🐛[BUG]EditProTable的props中editorFormRef与value获取的值不一致（表格与表单数据不一致）

### ISSUE THREAD

**Issue by TaurusWood** [ant-design/pro-components#6821]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
在使用EditProTable多行表单时，存在一个给行排序的场景，本质上改变传入value的`dataSource`的数组的顺序。例如mount时`dataSource`的顺序是[A,B]，用户操作后，`dataSource`的顺序是[B,A]。此时通过`editorFormRef.current.getRowsData()`那倒是的数组顺序还是[A,B]和mounted时一致

### 📷 复现步骤

1. 点击上移、下移，dataSource实时更新
2. 点击表单数据card中的获取，拿到`editorFormRef.current.getRowsData()`的值

### 🏞 期望结果

在dataSource update数组顺序后，与`editorFormRef.current.getRowsData()`获取到的数据顺序一致

### 💻 复现代码

[示例codesandbox](https://codesandbox.io/embed/ke-bian-ji-biao-ge-forked-yzrufg?fontsize=14&hidenavigation=1&theme=dark)

### © 版本信息

- ProComponents 版本: [2.4.2]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题可能由于获取数据的方式不正确导致，可以尝试在重新排序后，重新通过`editorFormRef.current.getRowsData()`获取数据文件并更新组件。具体代码实现如下：

```javascript
// ⬇️ 这部分为通过数组的顺序重新排序 dataSource 的函数

const moveRow = (dragIndex, hoverIndex) => {
  const dragRow = dataSource[dragIndex];
  const replaceDataSource = update(dataSource, {
    $splice: [
      [dragIndex, 1],
      [hoverIndex, 0, dragRow]
    ]
  });
  setDataSource(replaceDataSource);
};

// ⬇️ 这部分为重新获取数据的部分

const handleSave = async () => {
  const newData = await formRef.current?.validateFields();
  const newRowData = replaceDataSource;
  const data = newRowData.map((item, index) => {
    return {
      ...item,
      ...newData[index]
    };
  });
  console.log('new row data:', data);
  // 这里将获取到的data放到需要接收数据的地方，例如将其放到state中
  setData(data);
};

``` 

此外，还可以尝试在调用移动组件时传入`shouldRender`参数， 其中`shouldRender`为布尔值，来避免只更新状态而不重新挂载组件的问题。具体代码示例如下：

```javascript
// ⬇️ 这部分为传入shouldRender参数的例子

<EditableProTable
  ...
  recordCreatorProps={{
    position: 'top'
  }}
  components={{
    body: {
      row: DragableBodyRow
    }
  }}
  rowKey="id"
  onChange={handleOnChange}
  value={dataSource}
  // ⬇️ shouldRender这里设置为true
  shouldRender={() => true}
  editable={{
    type: 'multiple',
    editableKeys,
    onChange: setEditableRowKeys,
    onDelete: handleDelete,
    onSave: handleSave
  }}
/>
``` 

可以通过上述的两种方式，解决 EditProTable 的`editorFormRef`与`value`的获取的值不一致，导致表格与表单数据不一致的问题。如果还有其他疑惑，可以参考 ProTable 的官方文档，或者询问相关专家的帮助。

**Comment by TaurusWood** [comment]
1.  我认为这是一种hack方法，并不能解决form中的数据与dataSource中的数据不一致的问题。
> ```js
> const newRowData = replaceDataSource;
>   const data = newRowData.map((item, index) => {
>     return {
>       ...item,
>       ...newData[index]
>     };
>   });
> ```
2. EditableProTable 并没有`shouldRender={() => true}`或者类似的属性

@chenshuai2144

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常感谢你的反馈！对于我的回答确实有一些误解。下面是针对你提出的问题的更正：

1. 对于在表单中与`dataSource`中传递的数据不一致的问题，个人认为无论在使用EditProTable中还是在其他的状态管理中，确保传递的数据结构一致是至关重要的，否则可能会导致出现不可预测的结果。在这种情况下，我个人可能会调整表单数据的结构以匹配新的`dataSource`上传递给组件。当然，这个调整的方式可能因应用程序的特定情况而异。

2. 我回答中的shouldRender只是一个可能的解决方法，并不是EditProTable默认的属性。我非常抱歉如果我引起了任何误解。

再次感谢你的反馈，希望我这次的回答更加明确。如果你还有任何疑问或问题，欢迎继续跟我讨论。

**Comment by chenshuai2144** [comment]
通过form的方式set进去把，form 和 value之间通信考的onchange，你绕开了 onchange 就会导致 form 里的数据和实际的不符合。

`form.setFieldValues({name:newData})`
