### ISSUE TITLE
🧐[问题] ProCard doesn't working with Dark Mode on Antd v5 or Did I configure it incorrectly?

### ISSUE THREAD

**Issue by doiya46** [ant-design/pro-components#6823]
### 🧐 问题描述

Button and Text working but ProCard doesn't.

### 💻 示例代码

https://codesandbox.io/s/pro-provider-dark-bj1bk2?file=/App.tsx

### 🚑 其他信息

![Screenshot from 2023-03-21 16-11-44](https://user-images.githubusercontent.com/61301244/226561874-08572c27-a6a9-4438-82d5-f322e2854286.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，感谢您向 Github 助理寻求帮助。根据您提供的信息，您的问题是在 Antd v5 的 Dark Mode 中 ProCard 不生效的问题。

根据查阅文档得知，在 Ant Design 中，使用 Dark Mode 需要在根组件处引入相应的样式文件，例如：

```tsx
import 'antd/dist/antd.dark.css';
```

同时，您需要在 `<ConfigProvider>` 组件中设置 `theme` 属性为 `'dark'`。参考代码如下：

```tsx
import { ConfigProvider, ProCard } from 'antd';

import 'antd/dist/antd.dark.css'; // 引入 Antd 的 Dark Mode 样式文件

function App() {
  const theme = 'dark'; // 设置 ConfigProvider 的主题为 dark

  return (
    <ConfigProvider theme={theme}> 
      <div>
        <ProCard title="Basic Card" bordered style={{ width: '300px' }}>
          <div>Card content</div>
          <div>Card content</div>
          <div>Card content</div>
        </ProCard>
      </div>
    </ConfigProvider>
  );
}

export default App;

```

补充说明：另外，如果您使用的是 TypeScript，需要在 tsconfig.json 文件中配置 `dom` 和 `esnext`，例如：

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "esnext"]
  },
  "include": ["src"]
}
```

希望以上内容可以帮助您解决问题，如有疑问，请随时回复。同时，您也可以参考 Ant Design 官方文档了解更多信息：https://ant.design/components/card-cn/#components-card-demo-borderless

**Comment by chenshuai2144** [comment]
![image](https://github.com/ant-design/pro-components/assets/8186664/54438b76-4b02-4de4-a413-73a265723263)


fixed
