### ISSUE TITLE
🧐[问题]BreadcrumbItem 出现 <a> cannot appear as a descendant of <a> 多套了一层a标签  及 ConfigProvider.SizeContext is deprecated warning

### ISSUE THREAD

**Issue by echoyl** [ant-design/pro-components#6824]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
升级后出现如题报错

### 🚑 其他信息
antd:5.3
pro-components:2.4

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


关于 `BreadcrumbItem` 多套了一层 `a` 标签的问题，这是因为在 `antd@5` 中 `BreadcrumbItem` 的 `overlay` 组件默认返回了一个带有 `a` 标签的 `Menu` 组件，导致 `BreadcrumbItem` 外层又套了一个 `a` 标签。我们可以通过自定义 `BreadcrumbItem` 的 `overlay` 组件来解决这个问题，将返回的 `Menu` 组件中的 `a` 标签改为 `span` 标签即可。示例代码如下：

```jsx
import { Breadcrumb, Menu } from 'antd';

const CustomMenu = (props) => {
  const { activeKey, onItemClick } = props;
  return (
    <Menu selectedKeys={activeKey} onClick={onItemClick}>
      {props.children.map((child, index) => {
        const { href, ...restProps } = child.props;
        return (
          <Menu.Item key={index} {...restProps}>
            <span>{child.props.children}</span> {/* 将 a 标签替换为 span 标签 */}
          </Menu.Item>
        );
      })}
    </Menu>
  );
};

const MyBreadcrumb = (props) => {
  return <Breadcrumb overlay={CustomMenu} {...props} />;
};
```

关于 `ConfigProvider.SizeContext is deprecated` 的警告，这是因为 `antd@5.3` 中已经废弃了这个 `SizeContext`，所以我们需要将组件中使用到的 `SizeContext` 替换为 `ConfigContext.SizeContext`。示例代码如下：

```jsx
import { ConfigProvider } from 'antd';

const MyComponent = () => {
  const size = React.useContext(ConfigProvider.ConfigContext).globalConfig.size;
  
  // ...
}
``` 

同时，建议查看 [Ant Design 官方文档](https://ant.design/components/breadcrumb-cn/) 了解更多 `Breadcrumb` 组件的使用细节。

**Comment by chenshuai2144** [comment]
升级最新的版本即可。

**Comment by yao378186268** [comment]
> @chenshuai2144 升级到最新版 依然存在该问题
> 
> `Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.`

我升到 ^2.4.4 版本，我没有了
