### ISSUE TITLE
👑 [需求] ProTable 有请求拦截相关的方法吗？ 

### ISSUE THREAD

**Issue by halodong** [ant-design/pro-components#6825]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件
ProTable

### 🥰 需求描述
目前我没找到一个可以在proTable 的 request 请求之前做拦截判断的方案。

### ⛰ 功能需求适用场景
比如我需要提醒用户是否进行数据的刷新，然后通过用户的反馈来进行对应的操作。

### 🧐 解决方案
是否可以添加相关的 prop ，在 request 对应的时机去执行某些操作，比如添加类似于 requestHooks 这样的 props 
```
<ProTable
      requestHooks={{
        onBefore: () => {
           //  可以返回一个 Promise， 如果是reject则不进行request
        }，
        onAfter: () => {
           //  在请求后的一些操作，可以让request的代码逻辑更清晰
         }
      }}
      request={(params, sorter, filter) => {
        console.log(params, sorter, filter);
        return Promise.resolve({
          data: tableListDataSource,
          success: true,
        });
      }}


    />
```

### 🚑 其他信息
如果已有更好的解决方案，抱歉打扰。
如果需要，我可以尝试做相关的代码贡献。

**Comment by chenshuai2144** [comment]
AI 说的对
