### ISSUE TITLE
🧐[问题] 关于编码规范是否需要切换为 umi lint

### ISSUE THREAD

**Issue by sushi-su** [ant-design/pro-components#6827]
### 🧐 问题描述

clone 项目到本地 pnpm 安装后， 用 webstorm 打开 eslint 会提示错误，估计是 [@umijs/fabric](https://github.com/umijs/fabric) 的内部依赖没锁版本导致不兼容，主要这个库基本不维护了，是否考虑切换为 [umi lint](https://umijs.org/docs/guides/lint)，我有兴趣完成这个 PR

### 🚑 其他信息

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/50985188/226633091-294ec4cb-1577-456c-8881-2dc04ff995fe.png">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 💡 解决方案

根据您的描述，可以尝试切换为 umi lint 进行代码的 eslint 检查。

您可以按照以下步骤进行操作：

1. 安装 `eslint-config-umi`：

   ```shell
   npm install eslint-config-umi -D
   ```

2. 修改 `.eslintrc.js` 配置文件：

   ```javascript
   module.exports = {
     extends: ['umi'],
     rules: {
       // 这里可以添加一些项目特有的规则配置
     },
   };
   ```

3. 运行预设的脚本命令：

   ```shell
   yarn lint
   # 或者
   npm run lint
   ```

这样就可以使用 umi lint 进行代码的 eslint 检查了。

你也可以查看[官方文档](https://umijs.org/docs/guides/lint)获取更多有关 umi lint 的信息和配置方式。
