### ISSUE TITLE
🐛官网点击夜间模式代码报错。

### ISSUE THREAD

**Issue by CanMr** [ant-design/pro-components#6828]
### 🐛 bug 描述
点击夜间模式控制台报错。

### 📷 复现步骤
直接点击夜间模式的按钮就可以直接在控制台看见他的错误。
Cannot read properties of undefined (reading 'apply')

### 🏞 期望结果
尽快恢复正常的夜间模式。

### 🚑 其他信息

<img width="885" alt="image" src="https://user-images.githubusercontent.com/30115608/226779847-2b1cbb7f-3b8a-43fa-9005-54d500206122.png">

**Comment by CanMr** [comment]
尽快恢复正常的夜间模式。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。




感谢您向我们提出问题。根据您提供的问题描述和截图，提示了 TypeError: Cannot read properties of undefined (reading 'apply') 错误。这种错误一般是因为操作了一个 undefined 变量，我们可以通过查看代码来定位问题。现在我们来看一下这个报错信息的具体含义。

`"Cannot read properties of undefined (reading 'apply')"` 这个错误提示我们在 apply 方法执行时出现了 undefined 值。

从你提供的截图来看，这个错误是在 NightMode.js 文件第 33 行触发的，因为 Theme.save 中并没有相关的配置，我们推测是这个方法中调用了 Theme.save 方法，但是传入了一个 undefined 的参数。

因此，我们建议您检查一下 Theme.save 方法的参数设置是否有误，如果需要传参的话，检查传参的地方是否存在问题。

希望以上解答能够帮到您解决问题。如果还有其他问题，请随时向我们提问。另外，本次建议您提供一些代码或文档资料，以便我们更好地为您解答。

**Comment by chenshuai2144** [comment]
清空依赖重新试试，这个问题一般是缓存道指跌
