### ISSUE TITLE
🐛[BUG]onCell参数不支持editable，支持rowSpan

### ISSUE THREAD

**Issue by guxingke201** [ant-design/pro-components#6829]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

onCell参数不支持editable，支持rowSpan
### 💻 复现代码
`{
      title: '预约日期',
      dataIndex: 'orderDate',
      valueType: 'date',
      onCell: (record, index) => {
        if (index === 0) {
          return { editable: false };
        }
        // if (index === 1) {
        //   return { rowSpan: 0 };
        // }
        // return record.orderNum ? { editable: false } : {};
      },`

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]
"@ant-design/pro-components": "^2.4.2",

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据用户描述的问题，可以看出用户在使用 Ant Design Pro 中的 ProTable 组件时遇到了问题，具体表现为 onCell 参数不支持 editable，但是支持 rowSpan。解决方案如下：

1. onCell 中添加 editable 属性

根据用户提供的代码可知，onCell 中只有 rowSpan 属性被添加了，而 editable 属性并没有添加。如果需要支持 editable 属性，只需要在 onCell 中添加 editable 即可。

示例代码：

```js
{
  title: '预约日期',
  dataIndex: 'orderDate',
  valueType: 'date',
  onCell: (record, index) => {
    if (index === 0) {
      return { editable: false };
    } else {
      return { editable: true };
    }
  },
}
```

2. Ant Design Pro 官方文档

如果您需要了解更多关于 Ant Design Pro 中使用 ProTable 的问题，请参考 Ant Design Pro 官方文档：https://procomponents.ant.design/components/table-cn/ 。在此文档中，您可以了解到 ProTable 的基本使用方式和各种参数的具体含义。

**Comment by chenshuai2144** [comment]
onCell 是 antd的，editable自然不支持，你可以存个ref到时候用
