### ISSUE TITLE
🐛[BUG] pro-form field组件的宽度如何自适应

### ISSUE THREAD

**Issue by xoptimal** [ant-design/pro-components#683]
### 🐛 bug 描述

目前field是支持一个width属性的, 默认有个宽度 input style: width: 328px 默认选择是m

不想设置该属性, 自动填充宽度, 如何实现~

目前的做法是: 
```fieldProps={{style: {width: '100%'}}}```

但是width这个属性就没有作用了, 期望默认填充宽度, 设置width则优先width

form field 的labelCol , wrapperCol2个属性, 并未产生任何作用~

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/pro-components/issues/621
