### ISSUE TITLE
🐛[BUG] ProFormTreeSelect组件fetchDataOnSearch属性设置为false无效

### ISSUE THREAD

**Issue by cyc2016** [ant-design/pro-components#6830]
### 🐛 bug 描述

ProFormTreeSelect组件，设置fetchDataOnSearch为false，还是会发起远程请求

### 📷 复现步骤

https://codesandbox.io/s/funny-dream-39m8mn

### © 版本信息

- ProComponents 版本: 2.4.2

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，感谢您的反馈！

根据您提供的信息，我们可以看出该问题在ProComponents的版本为2.4.2上存在，还没有被修复。在最新的版本中是否修复了该问题暂无法确定。

我们可以建议您使用下面的代码作为一种解决方案来解决这个问题：

```
<ProFormTreeSelect
  name="name"
  label="label"
  request={async (params, sorter, filter) => {
    if (!fetchDataOnSearch) {
      return Promise.resolve([]);
    }
    // your request logic here
  }} 
/>
```

即在自定义request函数中判断fetchDataOnSearch的值，若为false则直接返回一个空的Promise。

另外，我这里也提供了一个ProComponents中关于相关问题的链接，希望对您有帮助。

**Comment by chenshuai2144** [comment]
还不支持的，有个issue就是这个问题
