### ISSUE TITLE
🐛[BUG]ProFormList 删除之后表单值出现空对象

### ISSUE THREAD

**Issue by giamchen** [ant-design/pro-components#6831]
### 🐛 bug 描述
运行官方的例子，发现复制或者新增一行，接着删除某一行，表单数据会有一个空对象在数组，图片打印所示。按正常逻辑应该是直接删除对应的对象，不知道官方是故意保留还是其他原因，不知道算不算bug，新手有点疑问

### 📷 复现步骤
官方示例链接:https://procomponents.ant.design/components/group#%E8%A1%A8%E5%8D%95%E4%BA%92%E7%9B%B8%E5%B5%8C%E5%A5%97

线上代码:https://codesandbox.io/s/heuristic-pascal-y8hzsx

### 🏞 期望结果
如果ProFormList删除某一项，则把对应项数据清除，而不是保留一个空对象，不然会影响数组长度判断

### © 版本信息

- ProComponents 版本: 2.4.2

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/33769348/226830247-a50c4fb4-4b43-4d8d-b809-6b3b2edeb137.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，感谢你向我们反馈这个问题。根据你的描述，我了解到你在使用 `ProFormList` 组件时，删除某一项后表单数据会有一个空对象在数组中，而你期望这个对象直接被清除。这是一个常见问题，也是 `rc-field-form` 库自身的限制所导致的，官方文档也有提到这个问题。

解决方法是在删除某一项时，手动调用表单的 `setFieldsValue` 方法，重新设置表单数据。下面是一个示例代码片段供你参考：

```jsx
const handleDeleteItem = (index: number) => {
  const newData = [...data];
  newData.splice(index, 1);
  setData(newData);

  // 取出表单的所有数据，把删除项的数据清空
  const values = form.getFieldsValue(true);
  values.list.splice(index, 1, undefined);
  // 重新设置表单数据
  form.setFieldsValue({ list: values.list });
};
```

其中，`form` 是由 `ProFormList` 的 `useForm()` 方法返回的表单对象。这里通过 `getFieldsValue` 方法取出表单的所有数据，手动清空了删除项的数据，并再次调用了 `setFieldsValue` 方法重新设置表单数据。

希望能帮到你，如有问题请随时联系我。
