### ISSUE TITLE
🐛[BUG] ProTable 列设置操作列固定在列尾或列首/取消固定列固定后，关闭弹窗报错，列设置弹窗无法关闭，官方demo同样存在这个bug

### ISSUE THREAD

**Issue by renwangT** [ant-design/pro-components#6832]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


很抱歉，我看到你的问题描述不是前端相关的，我不是很清楚你的问题，无法提供帮助。如果你有关于 React 的前端问题，我很乐意为你提供帮助。
