### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by renjinhui** [ant-design/pro-components#6833]
### 🐛 使用ProTable的时候， request对应函数偶尔不执行，一直处在loading状态。

项目中有三个menu，分别对应了三个不同的路由，每个路由对应的页面中都是用了ProTable组件，但是当menu切换的时候，对应页面的Protable的request对应函数偶尔不执行，导致table一直处在一个loading的状态。

### 📷 复现步骤

在第一个menu中使用 “清空缓存并硬性重新加载”，然后点击进入其他menu的时候，能偶现不执行request的情况。目前业务中是通过使用定时器来判断是否加载了，没有加载就执行组件的reload方法来解决了这个问题。

### 🏞 期望结果

想要了解是我的用法缺少了什么属性，还是ProTable本身的问题。

### 💻 复现代码/
`const QualityList = ({ tabKey }) => {
  
  let isFirstRequestSuccess = false;
  const updateActivityList = async (params = {}, sort, filter) => {
    
    console.log("requset执行了")
  };

  return (
    <>
      <ProTable
        columns={[]}
        
        request={updateActivityList}
        
      />

      
    </>
  );
};

export default QualityList;
`

### © 版本信息

- "@ant-design/pro-table": "^2.17.0",
- umi 版本 "3.2.17"
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/16096319/226871946-3f1b357b-6764-4158-9fa7-4dcdbd0af250.png)

**Comment by ChenWeihua123** [comment]
同样的问题 请问怎么解决的
