### ISSUE TITLE
👑 [需求]EditableProTable组件的onSave方法怎么实现接口返回错误信息不添加一行

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/pro-components#6834]
### 🥰 需求描述

![image](https://user-images.githubusercontent.com/20655248/226893717-e1aabdf3-283b-4aef-8aa1-5955b0865877.png)

点击表格内的保存按钮会调接口，如果接口返回错误信息不添加这行要怎么做，是不是在onSave方法里面做操作

![image](https://user-images.githubusercontent.com/20655248/226894152-d096fdb0-c99c-40fc-97c2-10a39c26e37f.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！针对你的问题，我的建议是在onSave方法中对返回结果进行判断，若返回结果为错误信息则不添加这一行。可以参考以下代码：

```javascript
const onSave = async (key, row) => {
  const res = await saveData({key, row});
  if (res.code !== 0) {
    notification.error({ message: '保存失败', description: res.msg });
    return;
  }
  // 保存成功才添加行
  const newData = [...data];
  const index = newData.findIndex(item => key === item.key);
  if (index > -1) {
    const item = newData[index];
    newData.splice(index, 1, { ...item, ...row });
    setData(newData);
  } else {
    newData.push(row);
    setData(newData);
  }
};
```

另外，EditableProTable的官方文档中提供了完整的使用示例和API文档，可以帮助你更好地理解和使用该组件：

- [EditableProTable使用示例](https://ant.design/components/table-cn/#components-table-demo-edit-row)
- [EditableProTable API文档](https://ant.design/components/table-cn/#EditableProTable)

**Comment by ByYogi** [comment]
> 

感觉AI回复解决方案都没啥用

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


很抱歉，我的回答没有很好地满足您的需求。我会尽力改进和提高我的回答质量。如果您对我的回答不满意，您可以具体说明您的需求和问题，我会尽力为您提供更加贴切的解决方案。

**Comment by MI-Class** [comment]
> 

```js
editable={{
              type: "multiple",
              editableKeys,
              onSave: async (rowKey, data, row) => {
                console.log(rowKey, data, row);
               return
              },
              actionRender: (row, config, defaultDom) => [
                defaultDom.save, // 考虑重写下这个,判断是否成功也在这里
                defaultDom.cancel,
              ],
              onChange: setEditableRowKeys,
            }}
```

**Comment by chenshuai2144** [comment]
![image](https://github.com/ant-design/pro-components/assets/8186664/305a2ec9-e6df-4473-84b9-9211d9fd4956)

throew 一个error 出来就可以了
