### ISSUE TITLE
🐛[BUG] DrawerForm 嵌套 ProTable时， ProTable.search.layout 不起作用，搜索表单一直处于块级状态

### ISSUE THREAD

**Issue by otwayxf** [ant-design/pro-components#6838]
### 🐛 bug 描述

DrawerForm 嵌套 ProTable时， ProTable.search.layout 不起作用，搜索表单一直处于块级状态

### 📷 复现步骤

`
  <DrawerForm>
      <ProTable<API.RuleListItem, API.PageParams>
        search={{
          layout: 'inline',
          labelWidth: 'auto'
        }}
   </ProTable>
  </DrawerForm>
`

### 🏞 期望结果

ProTable.search.layout 起作用

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


从你的描述中可以看出，你嵌套的是 `DrawerForm`，并且使用了 `ProTable` 组件，但是 `search` 属性中设置的 `layout` 没有起作用，搜索表单一直处于块级状态。解决这个问题，有一个简单的方法就是将 `ProTable` 属性中的 `form` 属性设置为 `formRef.current`，其中 `formRef` 是 `DrawerForm` 的引用。

```tsx
const formRef = useRef<FormInstance>();

<DrawerForm title="新建规则" width={426} visible={visible}>
  <ProTable<API.RuleListItem, API.PageParams>
    formRef={formRef.current}
    search={{
      layout: 'inline',
      labelWidth: 'auto',
    }}
  </ProTable>
</DrawerForm>;
```

这样，`ProTable` 组件的搜索表单就会根据 `layout` 属性设置的方式进行布局了。对于使用 `DrawerForm` 的情况来说，`form` 属性的设置非常重要。

如果还有疑问，可以参考 [Ant Design Pro Table - formRef](https://procomponents.ant.design/components/table#formref) 官方文档中的 `formRef` 相关内容。

**Comment by otwayxf** [comment]
> 
1. 其中formRef={formRef.current} 会引起ts报错，要写成formRef={formRef}
2. 这样写之后，layout: 'inline'也没有起作用，页面布局label和input还是呈现上下两行的布局。😊

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢反馈！对于第一个问题，将 `formRef={formRef.current}` 改为 `formRef={formRef}` 即可解决。对于第二个问题，如果仅按照上述修改仍未生效，还需要确保在这段代码中，确实使用了 antd 的 Form 组件，具体可参考下面的示例代码。

```tsx
import { Form, Input } from 'antd';

<Form form={form} initialValues={{ xxx }}>
  <ProTable<API.RuleListItem, API.PageParams>
    formRef={formRef}
    search={{
      layout: 'inline',
      labelWidth: 'auto',
    }}
  >
    <ProTable.Column<API.RuleListItem> title="xxx" dataIndex="xxx" />
    <ProTable.Column<API.RuleListItem> title="xxx" dataIndex="xxx" />
  </ProTable>
</Form>
```

以上示例中，Form 组件在 `ProTable` 外层包裹，并且 `form` 属性传入了一个 FormGroup 实例，这样组合使用，可以实现正常的内联布局。另外，不要忘记在外层组件包裹标签中添加 `form` 属性，如：`<Form form={form}></Form>`。如果还有其他疑问，欢迎继续咨询。

**Comment by chenshuai2144** [comment]
这个要antd支持一下了，暂时不支持嵌套layout context
