### ISSUE TITLE
🐛[BUG]access权鉴false的时候，未移除没有权限的导航菜单

### ISSUE THREAD

**Issue by hangaoke1** [ant-design/pro-components#684]
### 🐛 bug 描述
未移除干净，图标仍然显示在导航中

![image](https://user-images.githubusercontent.com/19623160/95723166-6b0cba00-0ca7-11eb-962b-dd1660fc3dca.png)

### 📷 复现步骤

1. 配置菜单access权鉴，直接搞成false即可
2. 配置菜单混合模式，并自动分割菜单
```js
{
  layout: 'mix',
  splitMenus: true,
}
```

### 🏞 期望结果

顶部导航中，移除没有权鉴的菜单，目前名称被移除，但是图标未被移除

### © 版本信息

- ProComponents 版本: [6.5.1]
- umi 版本 [3.2.14]
- 浏览器环境[chrome80]
- 开发环境 [mac OS]

**Comment by rojer95** [comment]
现在直接access失效了。

```
"@ant-design/pro-layout@^6.15.3":
  version "6.24.1"
```
![image](https://user-images.githubusercontent.com/20662049/130454782-1ef412b1-3bf2-49f0-a2a3-57370056dd4c.png)
