### ISSUE TITLE
怎么给ProLayout根据页面初次加载设置自动Loading🧐[问题]

### ISSUE THREAD

**Issue by Lands-1203** [ant-design/pro-components#6844]
我是一个微前端应用，在主应用中初次进入菜单页面时没有自动loading，但是进入微应用会自动loading，因为微应用有autoLoading属性。

![image](https://user-images.githubusercontent.com/61341868/227403500-721cd9d4-4583-47be-8b0a-968d21098e80.png)
```

  "dependencies": {
    "@ant-design/icons": "^4.8.0",
    "@ant-design/pro-components": "^2.3.57",
    "@ant-design/use-emotion-css": "1.0.4",
    "@umijs/route-utils": "^2.2.2",
    "antd": "^5.2.2",
    "classnames": "^2.3.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.8.2",
    "rc-util": "^5.27.2",
    "react": "^18.2.0",
    "react-dev-inspector": "^1.8.4",
    "react-dom": "^18.2.0",
    "react-helmet-async": "^1.3.0"
  },
```
通过ant design Pro 生成的项目都没有autoLoading了

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，针对你的问题，可以尝试使用 `ProLayout` 中的 `loading` 属性来控制页面初次加载时的自动loading。具体使用方法如下：

1. 在菜单页面的入口文件中，先引入 `ProLayout` 组件，然后在组件中加入 `loading` 属性，设为 `true`，表示页面初次加载时需要自动loading：

```
import ProLayout from '@ant-design/pro-layout';

const MenuPage = () => {
  return (
    <ProLayout loading={true}>
      ... // 页面内容
    </ProLayout>
  );
};
```

2. 在组件渲染完成后，可以通过 setState 来控制 loading 的状态，例如在 componentDidMount 中调用接口完成后，将 loading 设为 false：

```
import ProLayout from '@ant-design/pro-layout';

class MenuPage extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      loading: true,
    };
  }

  componentDidMount() {
    // 调用接口
    api.fetchData()
      .then((res) => {
        // 完成后将 loading 设为 false
        this.setState({
          loading: false,
        });
      });
  }

  render() {
    const { loading } = this.state;

    return (
      <ProLayout loading={loading}>
        ... // 页面内容
      </ProLayout>
    );
  }
}
```

以上两种方式都可以控制页面初次加载时的自动loading。如果使用第二种方式，则需要在组件中自行控制接口请求完成后的状态，需要注意的是 loading 一般都是通过接口调用完成后才能设置成 false。如果是全局的loading，可以考虑使用 redux 等状态管理工具，将 loading 状态存放在全局状态中，然后在组件中进行监听和更新。希望这些信息能对你有帮助。

**Comment by chenshuai2144** [comment]
试试 AI 的办法，比较靠谱i
