### ISSUE TITLE
🐛[BUG]切换暗色后 侧边栏背景色仍然是白色

### ISSUE THREAD

**Issue by zhu-mingye** [ant-design/pro-components#6845]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

切换暗色后 侧边栏背景色仍然是白色

### 📷 复现步骤

切换主题色为暗色   发现侧边栏仍然为白色  不会随主题色变化

### 🏞 期望结果

期望侧边栏跟随主题色变化

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据你提供的信息，我假设你是在使用 antd Pro 的 ProLayout 组件，在切换主题色为暗色后发现侧边栏的背景色没有跟随变化。

解决方案：

1. 确定主题色配置是否正确

antd Pro 支持使用 webpack 的 less-loader 针对配置的 less 变量进行主题定制。检查一下你的主题配置是否正确，可以参考[官方文档](https://pro.ant.design/docs/style-cn)。

2. 修改 ProLayout 组件的样式

如果主题色配置没有问题，可能是 ProLayout 组件的样式问题。可以尝试修改 ProLayout 组件的样式，在暗色模式下给侧边栏添加一个背景色。可以在大屏幕模式下添加如下样式：

```
@media screen and (min-width: 768px) {
  .ant-pro-basicLayout-sider {
    background: #001529; // 这里是你需要修改的颜色，可以替换为你选择的暗色
  }
}
```

该样式会在大屏幕模式下生效，给侧边栏添加一个指定颜色的背景。如果你需要在小屏幕模式下也修改背景色，可以参考 antd 的响应式设计文档进行适配：[响应式设计](https://ant.design/docs/react/responsive-cn)。

注意事项：

- 修改样式可能会影响其他组件的展示，请仔细查看页面效果，确保修改后不会影响其他地方的显示效果。
- 在修改样式之前，最好先备份一下原始样式，方便进行恢复。

希望以上信息可以帮到你解决问题。如果仍然有问题，可以提供更多信息，我会尽力帮助你解决。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


如果你使用了 Antd Pro 的 ProLayout 组件，配合 Antd Pro 的主题功能来实现主题切换，你可以通过在切换主题时修改 less 全局变量的值来达到样式随主题变化的效果，具体操作步骤可以参考``Antd Pro``文档的[主题配置](https://pro.ant.design/docs/style-cn#%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE)章节，其中有提供了示例代码，可以供你参考实现修改主题颜色。

如果你想让侧边栏的样式也能随主题变化，可以在使用 ``Antd Pro`` 的 ``ProLayout`` 组件的同时，使用 ``Antd`` 的 ``Menu`` 组件实现侧边栏的渲染，并且通过全局 less 变量修改侧边栏的背景色/字体颜色等样式属性，配合主题切换时修改 less 变量的值，就可以实现侧边栏随主题变化的效果了。

示例代码如下：

```jsx
import { Menu } from 'antd';
import { useModel } from 'umi';  // 导入 umi 的 useModel hook, 可以用于获取整个应用范围内的全局数据

const CustomMenu = () => {
  const { settings } = useModel('@@initialState') as {
    settings: {
      navTheme: string;
    };
  };  // 从 umi 的全局状态中获取当前的主题配置，注意需要使用 as 将数据类型断言为 umi 的全局状态

  return (
    <Menu
      // 使用 theme 样式属性根据主题配置设置侧边栏的样式
      theme={settings.navTheme === 'dark' ? 'dark' : 'light'}
      // ...其他属性
    >
      {/* 菜单项 */}
    </Menu>
  );
};

const CustomLayout = ({ children }) => {
  return (
    <ProLayout>
      {/* ...其他子组件 */}
      <CustomMenu />
      {/* ...其他子组件 */}
    </ProLayout>
  );
};
```

在以上代码中，我们使用了 ``useModel`` hook，通过从 umi 的全局状态中获取当前的主题配置，然后将这个配置传递给 ``Menu`` 组件的 ``theme`` 样式属性，来决定侧边栏的样式。当然你可以添加其他的样式属性，来修改侧边栏的其他样式效果。

希望以上信息可以帮助你解决问题。如果你还有其他的疑问，请随时回复。
