### ISSUE TITLE
🐛[BUG] 菜单的name里包含'-'会产生问题

### ISSUE THREAD

**Issue by yaoguoba** [ant-design/pro-components#685]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/18393410/95726503-98f3fd80-0cab-11eb-94bb-9efe8863e397.png)
![image](https://user-images.githubusercontent.com/18393410/95726578-add09100-0cab-11eb-978e-3da362417b31.png)

点击分类或者套餐时，商品菜单也会被选中

### © 版本信息

- ProLayout 版本: 6.5.1

**Comment by chenshuai2144** [comment]
是根据path 来的，把path 做一下区分把，现在是贪婪模式，会匹配后缀相同的

**Comment by yaoguoba** [comment]
ok, thanks
