### ISSUE TITLE
🐛[BUG]@ant-design/cssinjs missing as dependency in @ant-design/pro-layout

### ISSUE THREAD

**Issue by ntucker** [ant-design/pro-components#6851]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

This is a problem when using pnp.

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，根据您提供的信息无法给出有针对性的解决方案。请提供以下信息以便更好地帮助您解决问题：

1. 问题的具体描述
2. 复现步骤，包括可执行代码或线上示例
3. 您期望看到的结果
4. 使用的版本信息，例如 ProComponents 版本，umi 版本等
5. 您的开发环境，例如操作系统和浏览器环境

请参考上面的提问规范并提供更多信息，我们将尽快为您解决问题。
