### ISSUE TITLE
🧐[问题] PageContainer自定义面包屑路由模式是browser无法

### ISSUE THREAD

**Issue by wppeng520** [ant-design/pro-components#6853]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

PageContainer设置自定义面包屑，当路由模式是browser 跳转走的是hash

### 💻 示例代码
```
<PageContainer
      title="审批详情"
      breadcrumb={{
        routes: [
          {
            path: '/home',
            breadcrumbName: '首页',
          },
          {
            path: '/auditview/:id',
            breadcrumbName: '审批详情',
          },
        ],
      }}
    >
```

### 🚑 其他信息
![1679887453861](https://user-images.githubusercontent.com/70751511/227833249-03787e1e-6024-4f01-9797-02e143fdd998.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🤔问题分析

根据用户提供的信息和截图，可以看到实际生成的面包屑跳转链接是以 hash 开头的，并不符合预期使用 browserRouter 跳转。这个问题的根本原因是 Ant Design Pro V5 中默认的路由组件实现使用的是 hash，需要手动更改为 browser。

### 👍解决方案

1. 修改路由组件

在 `src/app.tsx` 中我们可以找到默认导入的路由组件，即 `BrowserRouter`。我们需要将其更改为 `HashRouter`。

```tsx
import { HashRouter as Router } from 'react-router-dom';
```

2. 修改 router 配置

在 `config/config.ts` 中，我们可以看到根路由配置，找到 `history` 字段，务必将其更改为 `browser`。

```tsx
routes: [
  {
    path: '/',
    component: '@/layouts/BlankLayout',
    routes: [
      {
        path: '/user',
        component: '@/layouts/UserLayout',
        routes: [
          {
            name: 'login',
            path: '/user/login',
            component: './user/login',
          },
        ],
      },
      {
        path: '/',
        component: '@/layouts/BasicLayout',
        authority: ['admin', 'user'],
        routes: [
          //...
        ],
      },
    ],
  },
],
/**
 * history 配置项 https://umijs.org/zh-CN/plugins/plugin-history
 */
history: {
  type: 'browser',
},
```

修改后，Ant Design Pro V5 将使用 browser 跳转链接，该问题应该可以得到解决。

### 📚参考文档

- [Ant Design Pro V5 官方文档 - 依赖](https://pro.ant.design/docs/dependencies-cn)
- [umi-plugin-history](https://umijs.org/zh-CN/plugins/plugin-history)

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/blob/c31259b13f71f7c649b2b9796d7253ef360e4d44/packages/plugins/src/layout.ts#L275

看这里要自己处理一下呢

**Comment by ideaviewes** [comment]
这个是个bug吧，就这样不管了吗？
