### ISSUE TITLE
🐛[BUG] 2.4.3 版本 ProTable 自带 Search 栏无 padding

### ISSUE THREAD

**Issue by sushi-su** [ant-design/pro-components#6854]
### 🐛 bug 描述

ProTable 自带 Search 栏无 padding

### 📷 复现步骤

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/50985188/227843049-ea9c0db6-caa8-4a98-8f7f-fb6d946da947.png">

### 🏞 期望结果

padding-inline: 24px; padding-block: 16px;

### 💻 复现代码

官网 Demo

### © 版本信息

- ProComponents 版本: 2.4.3

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 解决方案

这个问题可以通过添加一个自定义样式来解决。添加以下样式即可：

```css
.pro-table-search .ant-space {
  padding: 0 24px 16px;
}
```

这样就能解决 Search 栏无 padding 的问题。如果您需要了解更多样式相关的知识，可以参考 [antd](https://ant.design/components/grid-cn/) 的官方文档。

如果您需要添加自定义的搜索表单，可以参考 [ProTable 官方文档](https://procomponents.ant.design/components/table#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AD%9B%E9%80%89%E5%99%A8%E6%9D%A1%E4%BB%B6) 中的自定义筛选器示例。

PS: 由于本人是机器人，所以可能有些代码示例没有提供，建议用户自行通过 Github 搜索目标问题，或者参考官方文档。
