### ISSUE TITLE
🧐[问题] 怎么开启：不同路由页面第一次加载时候，Prolayout根据页面资源加载的情况自动loading？

### ISSUE THREAD

**Issue by Lands-1203** [ant-design/pro-components#6856]
就像这样，页面自动根据当前页面的资源加载情况loading，这个功能我记得之前的proLayout是有的，现在没有了？还是说有什么我没注意到的配置？
![227886736-cbb2a79a-e519-4ee3-9998-b115722977c4](https://user-images.githubusercontent.com/61341868/227891111-8e68dff2-5a0b-492b-ab53-75525b1c4272.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


👩‍💻 [解决方案]

在 `proLayout` 中实现页面资源加载的自动 `loading` 功能的思路是通过监听路由变化，并在路由变化时获取当前页面的资源情况来控制 `loading` 的显示和隐藏。

下面是基于 `react-router-dom` 和 `axios` 的实现方式：

1. 首先，在 `proLayout` 组件中引入所需的组件和库。

```js
import React, { useState, useEffect } from 'react';
import { Route, Switch, useHistory } from 'react-router-dom';
import axios from 'axios';
import Loading from './Loading';
```

2. 创建一个 `Loading` 组件作为加载时的提示信息，这里使用了 `Ant Design` 的 `Spin` 组件。

```js
const Loading = () => {
  return (
    <div style={{ position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%, -50%)' }}>
      <Spin size="large" />
    </div>
  );
};
```

3. 在 `proLayout` 组件中使用 `useState` 来控制 `loading` 的显示与隐藏。

```js
const [loading, setLoading] = useState(false);
```

4. 在 `useEffect` 中监听路由变化，获取当前页面资源情况并控制 `loading` 的显示和隐藏。这里使用了 `axios` 库来获取资源信息。

```js
const history = useHistory();

useEffect(() => {
  const unlisten = history.listen(() => {
    // 在路由变化时显示 loading
    setLoading(true);

    // 获取当前页面资源情况
    const { pathname } = history.location;
    const scripts = document.querySelectorAll(`script[src^="${process.env.PUBLIC_URL}${pathname}"]`);

    // 等待当前页面所需的所有 js 脚本加载完毕
    Promise.all(
      Array.from(scripts).map((script) => {
        return axios.get(script.src, { params: { t: Date.now() } });
      })
    ).then(() => {
      // 在所有 js 脚本加载完成后隐藏 loading
      setLoading(false);
    });
  });
  return () => {
    unlisten();
  };
}, [history]);
```

5. 在 `proLayout` 组件的 `render` 方法中，根据 `loading` 的值来决定是否显示 `Loading` 组件。

```js
return (
  <div>
    <Header />
    <Sider />
    <div style={{ padding: '20px' }}>
      {loading ? (
        <Loading />
      ) : (
        <Switch>
          <Route path="/page1" component={Page1} />
          <Route path="/page2" component={Page2} />
          <Route path="/page3" component={Page3} />
        </Switch>
      )}
    </div>
  </div>
);
```

6. 最后，需要注意使用 `create-react-app` 创建的应用程序中，JS 脚本默认会进行缓存。为了避免缓存导致资源加载不及时，需要在请求 JS 脚本时加上一个时间戳参数。这也是第四步中在请求时加上 `t: Date.now()` 的原因。

以上就是实现页面资源加载的自动 `loading` 功能的完整代码示例，希望对您有所帮助。

**Comment by chenshuai2144** [comment]
AI 的 这个思路还挺不错的， 就用这个吧
