### ISSUE TITLE
table 标题过长时控制列状态的 columnsSetting 样式问题

### ISSUE THREAD

**Issue by mraiguo** [ant-design/pro-components#6865]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cha-xun-biao-ge-forked-9mitit?file=/App.tsx)

### Steps to reproduce

点击右上角设置列显隐，鼠标hover上去时 Checkbox没有对齐，标题抖动

![image](https://user-images.githubusercontent.com/22299421/228172278-0f0f7170-7c14-4745-85b9-04e207df0228.png)

### What is expected?

Checkbox对齐，标题不抖动，布局正常

### What is actually happening?

布局不正常

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | macOS |
| Browser | chrome |

---
这个问题通过项目样式覆盖处理也比较简单。
想知道这个布局调整成什么样比较合理，hover上去的固定左右侧图标默认不显示的话当显示的时候必然会造成抖动，这种交互怎么处理比较合适

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！感谢你向我们反馈问题。

根据你提供的信息和截图，你碰到的问题是一个 `antd` 的样式问题，而非 `React` 的问题。

经过分析，该问题可以通过覆盖 `antd` 的样式来解决。在 `index.css` 中添加以下代码，即可解决该问题。

```css
/* 覆盖antd样式 */
.ant-checkbox + label {
  display: inline-flex;
  align-items: center;
  margin-bottom: 0;
}
```

至于如何调整布局比较合理，我们建议在显示左右侧图标时，可以通过慢慢渐变的效果把左右侧展示出来，以此来避免抖动。

另外，我们也建议在使用 `antd` 组件时确保已经引入了正确的 `antd` 样式。你可以在 `index.css` 中添加以下样式，引入 `antd` 默认样式。

```css
@import "~antd/dist/antd.css";
```

参考文档：

- [Ant Design React 官方文档](https://ant.design/docs/react/introduce-cn)
