### ISSUE TITLE
🐛[BUG] ProFormRadio.Group设置layout="vertical"时，radio 与 text 没有水平对齐

### ISSUE THREAD

**Issue by leila-huang** [ant-design/pro-components#6869]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProFormRadio.Group设置layout="vertical"时，radio 与 text 没有水平对齐

### 📷 复现步骤
没有水平对齐的原因是这里引起 ？
![image](https://user-images.githubusercontent.com/22982196/228449405-ba6b25d4-fd08-4efd-87a2-8eda35e9c724.png)

### 🏞 期望结果
跟 ProFormCheckbox.Group 设置layout="vertical"时，保持 radio 与 text 水平对齐

### 💻 复现代码

ProComponents官网展示的表单项demo网址：https://procomponents.ant.design/~demos/packages-form-src-components-field-set-demo-components-other

### © 版本信息

- ProComponents 版本: [2.3.57]
- 浏览器环境 [Chrome]
- 开发环境 [Windows OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题是因为在 ProFormRadio 中，label 标签默认是块级元素，与 radio 不在同一行，导致 layout="vertical" 时文本和 radio 不对齐。可以通过设置 label 的 display 属性为 "inline-block" 来解决。代码如下：

```
<ProFormRadio.Group layout="vertical">
  <Radio value="1">
    <span style={{ display: 'inline-block', minWidth: 120 }}>Radio A</span>
  </Radio>
  <Radio value="2">
    <span style={{ display: 'inline-block', minWidth: 120 }}>Radio B</span>
  </Radio>
</ProFormRadio.Group>
```
另外，ProComponents 官网展示的表单项 demo 已更新该改动。可以访问更新后的 demo 进行查看：https://procomponents.ant.design/~demos/packages-form-src-components-field-set-demo-components-other。 

关于 label 的相关属性，可以查看 Ant Design 官方文档：https://ant.design/components/form-cn/#components-form-demo-horizontal-login-form。
