### ISSUE TITLE
 pro-form field组件的时间类型，Moment会报错

### ISSUE THREAD

**Issue by ttjimsen** [ant-design/pro-components#687]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by ttjimsen** [comment]
in ForwardRef(FieldDatePicker) (created by ForwardRef(ProField))

**Comment by chenshuai2144** [comment]
详细一点，这个什么都看不出来的

**Comment by ttjimsen** [comment]
> 详细一点，这个什么都看不出来的

          <Field
            text={Moment('2019-11-16 12:50:26').valueOf()}
            valueType="dateTime"
            mode={state}
            plain={plain}
          />
会报 FieldDatePicker 里value 的错误，我不清楚具体问题，当前版本是4.1+

**Comment by chenshuai2144** [comment]
低级的语法错误，`Moment('2019-11-16 12:50:26').valueOf()` 看样子是个类型，你输出一下就知道了

**Comment by ttjimsen** [comment]
> valueOf
.valueOf() 返回的是时间戳，不是类型，而且这是实例代码，我都没动

**Comment by chenshuai2144** [comment]
```
 <Field
            text={moment('2019-11-16 12:50:26').valueOf()}
            valueType="date"
            mode={state}
            plain={plain}
          />
```

例子是这样的

**Comment by ttjimsen** [comment]
> ```
>  <Field
>             text={moment('2019-11-16 12:50:26').valueOf()}
>             valueType="date"
>             mode={state}
>             plain={plain}
>           />
> ```
> 
> 例子是这样的

问题已经解决，版本问题，从4.1 - 4.7 ，小版本更新也会有大问题，还是感谢及时的解答，虽然还是让我走了坑 ^_^
