### ISSUE TITLE
🐛[BUG]protable 当接口请求http状态码非200时，request被一直调用

### ISSUE THREAD

**Issue by vscing** [ant-design/pro-components#6870]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤

request={async (params: ParamsType = {}, sort: any, filter: any) => {
    const res: any = await 错误请求;
    return {
      data: res?.list || [],
      // success 请返回 true，
      // 不然 table 会停止解析数据，即使有数据
      success: true,
      // 不传会使用 data 的长度，如果是分页一定要传
      total: res?.total || 0,
    };
  }}
错误请求http 400

request一直执行

### 🏞 期望结果

request请求一次

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


针对你的问题，建议你可以参考以下步骤来解决：

1. 在 ProTable 的 params 配置项中，使用 fetch 方法进行请求。fetch 函数是基于 Promise 设计，可以自动终止请求。
```typescript
import { request } from 'umi';

const fetchData = async (params: ParamsType = {}, sort: any, filter: any) => {
  const res:any = await request('/api/demo', {
    method: 'GET',
    params,
  });
  return {
    data: res?.data || [],
    success: true,
    total: res?.total || 0,
  };
};

<ProTable
  onRequestError={() => message.error('请求数据失败')}
  params={{
    // 通过fetch方法进行请求
    fetch: fetchData,
  }}
  columns={columns}
/>
```

2. 在 request 中处理错误的请求。
```typescript
import { message } from 'antd';
import { request } from 'umi';

const fetchData = async (params: ParamsType = {}, sort: any, filter: any) => {
  try {
    const res:any = await request('/api/demo', {
      method: 'GET',
      params,
    });
    return {
      data: res?.data || [],
      success: true,
      total: res?.total || 0,
    };
  } catch(e) {
    message.error('请求数据失败');
    // 抛出错误终止请求
    throw new Error('请求数据失败');
  }
};

<ProTable
  onRequestError={() => message.error('请求数据失败')}
  params={{
    // 通过fetch方法进行请求
    async request() {
      try {
        const res = await fetchData();
        return res;
      } catch(e) {
        // 抛出错误，终止请求
        return {
          data: [],
          success: false,
          total: 0,
        };
      }
    }
  }}
  columns={columns}
/>
```

希望以上两个方案可以帮助到你。此外，还可以参考 ProTable 的官方文档，了解更多相关配置的使用方法。
[ProTable 官方文档](https://procomponents.ant.design/components/table)
