### ISSUE TITLE
👑 [需求] ProList 的 ProListMeta 类型是否可以支持 renderFormItem

### ISSUE THREAD

**Issue by yitengruntu** [ant-design/pro-components#6871]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/12508042/228479394-eed5dd40-0618-4a09-bd73-4ccf54802a04.png">

当前使用 metas 字段扩展其他搜索字段时，配置 renderFormItem 可以正常渲染，但类型报错。

<img width="559" alt="image" src="https://user-images.githubusercontent.com/12508042/228479707-53603c8f-9cc2-4115-a40b-92b0663b982c.png">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，感谢你的反馈。根据你的描述，目前 ProList 的 ProListMeta 类型不支持配置 renderFormItem，导致类型报错。确实这是一个需要修改的问题。

针对您的问题，我们的建议是直接使用 `renderFormItem`，不要使用 `metas` 字段。

可以按照以下示例的方式扩展搜索表单：

```jsx
import { ProFormText } from '@ant-design/pro-form';
import { ProList } from '@ant-design/pro-list';

<ProList<API.UserListItem, API.PageParams>
  // 其他配置...
  search={{
    filterType: 'light',
  }}
  toolBarRender={() => [
    <ProFormText key="name" name="name" label="名称" placeholder="请输入名称" />,
    // 其他搜索表单组件...
  ]}
  // 其他配置...
/>
```

这种方式可以直接使用 `renderFormItem`，并且不需要在类型声明时对 `metas` 进行扩展，可以避免类型报错的问题。

如果您仍然需要使用 `metas` 字段，请参考如下代码进行扩展：

```tsx
export type CustomMeta = {
  dataIndex: string;
  hideInSearch?: boolean;
  hideInTable?: boolean;
  renderFormItem?: (item: ProFormColumnsType<any>) => JSX.Element;
};

export interface CustomProListProps<T, U> extends ProListProps<T, U> {
  metas?: CustomMeta[];
}

// 使用 CustomProListProps 代替原始的 ProListProps 即可
<CustomProList
  // 其他配置...
  metas={[
    {
      dataIndex: 'name',
      renderFormItem: (item) => <ProFormText {...item} width="md" />,
    },
    // 其他搜索字段...
  ]}
  // 其他配置...
/>
```

当然，使用 `CustomProListProps` 的方式要比直接使用 `renderFormItem` 更麻烦，需要自己进行类型声明和组件的封装，不过如果您有使用该方式的需求，可以参考上述代码进行实现。

希望这些信息能够帮助到您，如果您还有其他问题，请随时联系我们。
