### ISSUE TITLE
本地用ProTable的dateTime组件报错🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/pro-components#6872]
### 🐛 bug 描述
本地环境，在ProTable组件的columns中增加valueType: 'dateTimeRange',在时间控件选择完时间点确定报错
如图：

![image](https://user-images.githubusercontent.com/20655248/228479727-4d93d7e3-5599-4853-a113-721f1ed3bcc2.png)

![image](https://user-images.githubusercontent.com/20655248/228479904-886ac5cf-5d83-4889-bb34-ef4ce33187c2.png)
![image](https://user-images.githubusercontent.com/20655248/228480005-d34da817-1775-4c60-abf3-0826746b99ec.png)
![image](https://user-images.githubusercontent.com/20655248/228480103-92735cce-6bde-4fa0-8455-49df9f0c0471.png)
![image](https://user-images.githubusercontent.com/20655248/228480221-4bdabc63-9840-4bcc-b782-ef2a1aa5c39f.png)
只有本地开启mfsu会报错，测试跟线上环境不会报错.
- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by cheneyg916** [comment]
升级ProComponents最新版本，或者关闭mfsu

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您的反馈，根据您提供的问题描述，我们建议您升级ProComponents到最新版本。同时，检查您的浏览器是否为最新版本。

此外，通过您提供的问题描述，我们还发现您的问题是在开启mfsu时才会报错。因此，我们建议您关闭mfsu，如果关闭mfsu后问题仍存在，则可以通过升级ProComponents解决该问题。

关于ProComponents的升级可以参考以下官方文档：

https://procomponents.ant.design/docs/getting-started-cn#%E5%AE%89%E8%A3%85

如果您的问题仍无法得到解决，请尽可能提供更多的信息，以便我们更快地帮助您解决问题。

**Comment by lovehebe330** [comment]
关闭了mfsu，procomponents更新到最新版本，浏览器也更到最新，依然报错
![image](https://user-images.githubusercontent.com/20655248/230558154-231e983e-443c-42ea-a6a1-4b5372f7dbf2.png)
![image](https://user-images.githubusercontent.com/20655248/230558315-df77f523-fa43-43ba-bd98-b68633813d55.png)
![image](https://user-images.githubusercontent.com/20655248/230558350-34502025-a1c1-4d3b-acbd-548d2690c958.png)

**Comment by lovehebe330** [comment]
关闭了mfsu，procomponents更新到最新版本，浏览器也更到最新，依然报错
![image](https://user-images.githubusercontent.com/20655248/230558154-231e983e-443c-42ea-a6a1-4b5372f7dbf2.png)
![image](https://user-images.githubusercontent.com/20655248/230558315-df77f523-fa43-43ba-bd98-b68633813d55.png)
![image](https://user-images.githubusercontent.com/20655248/230558350-34502025-a1c1-4d3b-acbd-548d2690c958.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据您提供的截图，错误代码是 "Uncaught TypeError: Cannot read property 'map' of undefined"，这可能是由于您在 "columns" 中使用了不正确的键值对导致的。请确保使用正确的属性名称来描述每列数据。

此外，我们还建议您检查您在引入 ProTable 组件时是否正确设置了所有需要的依赖项，以及您是否正确引入了 ProTable 组件的样式文件。您可以参考 ProTable 的官方文档来进行检查：

https://protable.ant.design/getting-started-cn#%E4%BE%9D%E8%B5%96%E4%BF%A1%E6%81%AF

最后，如果问题仍然存在，请提供更多的相关代码和问题描述，以便我们更好地帮助您。

**Comment by chenshuai2144** [comment]
dayjs 多版本导致的。

当你在使用npm包时，遇到多个版本的问题，有几种解决方法：

1. **更新依赖项**：首先，检查你的项目的依赖项（`package.json`文件中的`dependencies`和`devDependencies`）。确定是否有任何可以更新的包版本。在控制台中，使用`npm outdated`命令可以列出过时的包。然后，使用`npm update`命令来更新包到最新版本。

2. **手动指定版本号**：如果你需要在项目中使用特定的版本，可以在`package.json`文件中手动指定所需的版本号。在依赖项列表中，将版本号定义为需要的版本，例如：`"package-name": "1.2.3"`。然后使用`npm install`来安装特定版本的包。

3. **使用版本管理工具**：如果项目中有多个包版本冲突，并且无法解决冲突，你可以考虑使用版本管理工具，如`npm-shrinkwrap`或`yarn`。这些工具可以帮助你锁定依赖项的版本，以确保在不同环境中安装相同的包版本。

4. **使用npm包的别名**：如果你的项目同时依赖于多个使用不同版本的相同包，你可以使用npm包的别名功能（通过`npm install --save-optional`安装）来减少冲突。别名允许你在不同的模块中通过不同的名称引用不同版本的包。

5. **分离依赖环境**：如果你的项目中存在不同的子模块或组件，每个模块或组件都有自己的依赖关系，并且可能需要不同版本的包，你可以将这些模块或组件分离为独立的子项目，并使用不同的`package.json`文件来管理它们的依赖项。这样，每个子项目都可以独立选择和管理它们所需的包版本。

无论采用哪种方法，确保在更改依赖项时进行测试，并确保项目能够正常工作。
