### ISSUE TITLE
🧐[问题]  菜单收起展开，logo上方出现菜单文字 #6791， 这个bug 什么时候解决，已经过去一个月了，等着升级。

### ISSUE THREAD

**Issue by pc110** [ant-design/pro-components#6873]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
![image](https://user-images.githubusercontent.com/29336835/228705610-5edb23e2-f96a-4d6f-9116-72ea06370564.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


很抱歉，根据您所提供的信息，无法准确地判断问题的具体原因和解决方案。请您提供更多信息，尽可能详细地描述您遇到的问题，提供相关的代码示例、错误信息、操作环境等信息，以便更好地帮助您解决问题。同时，请注意本服务仅限于处理关于 React 的前端问题，如非前端问题，我们可能无法提供有效的帮助。谢谢！

**Comment by chenshuai2144** [comment]
修复了，antd 的样式有一些不一样了，更新版本就能看到，关掉了 antd 换成了自己实现的
