### ISSUE TITLE
👑 [需求]QueryFilter展开折叠时不触发组件的生命周期

### ISSUE THREAD

**Issue by wangru-chen** [ant-design/pro-components#6876]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

QueryFilter 

### 🥰 需求描述

QueryFilter展开折叠时都会触发组件的生命周期，导致自定义组件里的接口在重复调用

### ⛰ 功能需求适用场景

希望QueryFilter里的内容遵循组件生命周期规律，仅在页面初始化时添加，不要重复销毁添加

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


针对该需求，建议在 QueryFilter 组件中记录当前是否是展开状态，只在第一次展开时动态渲染子组件并加入到 DOM 中，之后的展开和折叠只更改组件内部的状态，避免重复调用接口和触发生命周期。具体实现方式可以使用 React 的状态或者 Redux 进行管理。示例如下：

```javascript
import React, { useState } from 'react';

function QueryFilter() {
  const [isExpanded, setIsExpanded] = useState(false);

  const handleToggle = () => {
    setIsExpanded(!isExpanded);
  }

  const queryFilterContent = (
    <div className="query-filter-content">
      {/* 此处放置 QueryFilter 的具体内容 */}
    </div>
  )

  return (
    <div className="query-filter">
      <div className="query-filter-header" onClick={handleToggle}>
        {/* 此处放置展开/折叠按钮 */}
      </div>
      {/* 根据展开状态决定是否渲染 QueryFilter 内容 */}
      {isExpanded && queryFilterContent}
    </div>
  )
}
```

需要注意的是，由于 QueryFilter 内部的状态不会因为折叠而重置，如果某些操作需要在组件销毁时进行清理，可能需要手动实现清理逻辑，例如在组件销毁时调用某个方法进行清理。

**Comment by chenshuai2144** [comment]
设计就是这样的，为了保证组件的纯粹性。
