### ISSUE TITLE
🧐[问题] Can't change the language in some places to korean in Ant Design Pro

### ISSUE THREAD

**Issue by jinseonghee** [ant-design/pro-components#6877]
提问前先看看：

Can't change the language in some places to korean in Ant Design Pro

I have tried setting up Ant Design protable using the toolbar, 
And I want to modify the language pack to be in my language for the question mark that appears when I hover the mouse over clicking the toolbar render of reload 
how do I have to do?  

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🚑 其他信息

<img width="863" alt="image" src="https://user-images.githubusercontent.com/68724297/229022592-81b35368-65ac-4224-8e24-7ae1ec145400.png">

![12](https://user-images.githubusercontent.com/68724297/229022592-81b35368-65ac-4224-8e24-7ae1ec145400.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🧐 问题描述

在 Ant Design Pro 中，想要将一些地方的语言设置为韩文。我已经尝试使用工具栏设置 Ant Design Pro，但是当我悬停鼠标并单击工具栏渲染重新加载时，出现了一个问号。我该如何解决这个问题?

### 💻 示例代码

Ant Design 提供了国际化的支持，你需要为组件设置相应的语言包，在 `src/locales` 目录下创建一个相应的语言文件，比如 `ko-KR.js`，然后将需要翻译的文本对照表放入其中。比如：

```javascript
export default {
  'app.reload': '새로 고침', // 'Reload' 的韩语翻译
  // 其他需要翻译的文本...
}
```

在组件中使用 `formatMessage` 方法来获取翻译后的文本，比如：

```javascript
import { formatMessage } from 'umi-plugin-locale';

//...

<Menu.Item key="reload" onClick={window.location.reload}>
   <Icon type="reload" />
   {formatMessage({ id: 'app.reload' })}
</Menu.Item>
```

这样就可以将 Ant Design Pro 中的一些文本和提示信息翻译成韩语。

### 🚑 其他信息

你需要保证选用的语言包在 `src/locales` 目录中存在，否则会出现找不到对应语言包的错误信息。你可以参考 Ant Design Pro 的[国际化文档](https://ant.design/docs/react/i18n-cn)，对组件进行自定义翻译。同时，有时候可能需要将一些 Ant Design Pro 自带的组件进行二次封装以达到更好的翻译效果。
