### ISSUE TITLE
🧐[问题] layout 配置了menu.request 但是没有执行request方法

### ISSUE THREAD

**Issue by YuDaChao** [ant-design/pro-components#6882]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
版本信息："@ant-design/pro-components": "^1.1.1"

### 💻 示例代码
menu: {
      params: initialState,
      request: async (params, defaultMenuData) => {
        console.log(params, defaultMenuData);
        return defaultMenuData;
      },
    },

**Comment by YuDaChao** [comment]
已解决

**Comment by zkamisama** [comment]
> 已解决

请问你是如何解决的， 我遇到的问题和你类似， 经过排查发现是和SettingDrawer有关  去掉了SettingDrawer就不会触发请求

**Comment by fooliker** [comment]
> > 已解决
> 
> 请问你是如何解决的， 我遇到的问题和你类似， 经过排查发现是和SettingDrawer有关 去掉了SettingDrawer就不会触发请求

我也遇到了同样的问题，请问你是怎么解决的？

**Comment by dysonchan1985** [comment]
我遇到的情况是我在`config/defaultSettings`里设置了`menu`,把`defaultSettings`里的`menu`删了,在`app.tsx`里设置就能正常`menu.request`了
