### ISSUE TITLE
🐛[BUG]有时候页面样式会丢失，刷新才行，是不是使用了tailwind导致

### ISSUE THREAD

**Issue by wppeng520** [ant-design/pro-components#6887]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![微信图片_20230404095108](https://user-images.githubusercontent.com/70751511/229666835-5965cef4-5f58-46ec-9c61-efd29fe206a4.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，根据您的描述，推断出的可能原因是使用了 Tailwind CSS 导致的。

可能的解决方法：

1. 确认 Tailwind CSS 版本是否正确，如果版本过低可能会导致问题。您可以参考 Tailwind 官网的文档来检查版本并升级：

   https://tailwindcss.com/docs/installation#installing-tailwind-css-as-a-dependency

2. 检查是否正确使用 Tailwind CSS 的配置文件，特别是关于样式的 Purge 配置。您可以查看官方文档中的相关章节，以确保配置正确：

   https://tailwindcss.com/docs/optimizing-for-production#purge-css-options

3. 如果以上方法都没有解决问题，则可能是其他的样式冲突导致的。您可以通过检查浏览器的开发者工具来排除冲突，或者将冲突样式重命名，以避免影响到您的页面。

希望以上方法对您有所帮助。如果还有问题，请提供更多的详细信息，以便我们能够帮助您更好地解决问题。

**Comment by funnyproblemboy** [comment]
我这边偶尔也会出现了这种样式丢失的问题，使用的是umi自动集成的@ant-design/pro-components

**Comment by wppeng520** [comment]
我还以为是使用tailwind导致，然后重新构建了一个，把我写的页面复制到新项目里面，暂时还没咋出现过，当时使用tailwind出现的频率高的很
&nbsp;


王鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月17日(星期一) 上午9:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/pro-components] 🐛[BUG]有时候页面样式会丢失，刷新才行，是不是使用了tailwind导致 (Issue #6887)





 
我这偶尔也会出现类似的问题，但我没有使用tailwind，与楼上使用的一致，请问楼主解决这个问题了吗？

**Comment by wppeng520** [comment]
tailwind从项目里面也不知道咋删除，我就重新构建了个项目，把之前写的页面复制进去，删除使用了tailwind的代码，tailwind就是个坑，暂时还没出现过丢失，当时使用tailwind丢失的可频繁了
&nbsp;


王鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月15日(星期六) 晚上8:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/pro-components] 🐛[BUG]有时候页面样式会丢失，刷新才行，是不是使用了tailwind导致 (Issue #6887)





 
***@***.***/pro-components

**Comment by chenshuai2144** [comment]
更新一下版本，ant-design/cssinjs 发了新版本，可以解决这个问题

https://github.com/ant-design/cssinjs
https://npmjs.org/package/@ant-design/cssinjs
