### ISSUE TITLE
🧐[问题] ProFormSelect 选中item为什么会触发onSearch方法

### ISSUE THREAD

**Issue by mwj610** [ant-design/pro-components#6888]
https://codesandbox.io/s/biao-dan-xiang-forked-xbm68h?file=/App.tsx:964-972

**Comment by thinkasany** [comment]
在组件pro-components/packages/field/src/components/Select/SearchSelect/index.tsx 下，将搜索框置空 和 antd 行为保持一致, 做了一个 setSearchValue(undefined);和 onSearch?.(''); 的操作，就是当你选中选项的时候，会清空输入框，因为proselect组件在onSearch的时候操作了setSearchValue和fetchData了，如果不清空，就会导致行为和select组件不一，必须你手动清空输入的值，才能选择其他选项。

<img width="615" alt="image" src="https://user-images.githubusercontent.com/117748716/229862427-d1d4dede-0ac5-44c5-aa2b-b49840e934ae.png">

**Comment by mwj610** [comment]
> 在组件pro-components/packages/field/src/components/Select/SearchSelect/index.tsx 下，将搜索框置空 和 antd 行为保持一致, 做了一个 setSearchValue(undefined);和 onSearch?.(''); 的操作，就是当你选中选项的时候，会清空输入框，因为proselect组件在onSearch的时候操作了setSearchValue和fetchData了，如果不清空，就会导致行为和select组件不一，必须你手动清空输入的值，才能选择其他选项。
> 
> <img alt="image" width="615" src="https://user-images.githubusercontent.com/117748716/229862427-d1d4dede-0ac5-44c5-aa2b-b49840e934ae.png">

好像和antd 不一致
https://codesandbox.io/s/biao-dan-xiang-forked-4uw0c8?file=/App.tsx

**Comment by thinkasany** [comment]
能具体的描述一下你说的不一致么，你说会antd空的时候并不会打印你的console.log("antd search：" + v)么，如果说这样子的话，就是我说的那个因为他调用了一下onSearch，所以执行了你传入的这个函数，他要保持的一致是如果搜索了一个options的时候点击选中了之后清空，可以再选所有的options，如果注释了下面这个onsearch的话，那么在onSearch那些步骤的操作没有清空会导致行为不一致，就是过滤条件还显示在输入框

**Comment by mwj610** [comment]
> 能具体的描述一下你说的不一致么，你说antd选中options的时候并不会打印你的console.log("antd search：" + v)么，如果说这样子的话，就是我说的那个因为他调用了一下onSearch，所以执行了你传入的这个函数，他要保持的一致是如果搜索了一个options的时候点击选中了之后清空，可以再选所有的options，如果注释了下面这个onsearch的话，那么在onSearch那些步骤的操作没有清空会导致行为不一致，就是过滤条件还显示在输入框

就是我在ProFormSelect里面写了onSearch方法，然后在多选的时候每次选中options都会调用一下onSearch方法。

**Comment by thinkasany** [comment]
Onchange的时候调用了一下你props中解构出来的onSearch?.('')呀， 这个onSearch?.('')是你传入的， Onchange嘛不就是监听change，因为他传给antd的select的Onsearch里面做了其他操作，需要在传给antd的select的onchange中做清空处理，

**Comment by mwj610** [comment]
就是我希望选中options的时候不掉用我传的onSearch.

**Comment by jingxiawl** [comment]
> 就是我希望选中options的时候不掉用我传的onSearch.

请问这个问题解决了么，这样导致了我输入查询数据有问题

**Comment by chenshuai2144** [comment]
老哥解释的很清楚了，如果你需要避开的话，可以是看这里避开

![1689496297413](https://github.com/ant-design/pro-components/assets/8186664/ed986971-4ec3-4e3b-baae-a2ebb27fd4d4)

**Comment by jingxiawl** [comment]
> 老哥解释的很清楚了，如果你需要避开的话，可以是看这里避开
> 
> ![1689496297413](https://user-images.githubusercontent.com/8186664/253793459-ed986971-4ec3-4e3b-baae-a2ebb27fd4d4.png)

不是需要避开，如果你设置了autoClearSearchValue为false导致不会清空输入框，但是不加入的话，我输入了一个搜索value ，渲染出来了下拉选择的数据，但是一选择又调用了onSearch方法，导致我的下拉数据变成空了

**Comment by lizm-21** [comment]
解决了么

**Comment by yqz0203** [comment]
> 老哥解释的很清楚了，如果你需要避开的话，可以是看这里避开
> 
> ![1689496297413](https://private-user-images.githubusercontent.com/8186664/253793459-ed986971-4ec3-4e3b-baae-a2ebb27fd4d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODk3MTMsIm5iZiI6MTcyMTI4OTQxMywicGF0aCI6Ii84MTg2NjY0LzI1Mzc5MzQ1OS1lZDk4Njk3MS00ZWMzLTRlM2ItYmFhZS1hMmViYjI3ZmQ0ZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MThUMDc1NjUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjg4MWFiMDFjM2ZhNDRmNWNhZTE5NTkwYjAxNjdkYjk4YWZhZDM2ZjhhYzc5MGFiOGYxZjM1NmM3ZGNkZjUyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JgXPYSQ84WLkBwY0RGdz_s1nBxbEU52Z8JojsRslpzU)

![image](https://github.com/user-attachments/assets/e324ff87-4a6c-43c7-ba53-9e3c35960586)
图一
![image](https://github.com/user-attachments/assets/b7e9eff3-9197-468c-9feb-d89ea1e9f47d)
图二
![image](https://github.com/user-attachments/assets/cf82fe18-6eaa-4062-91f9-be405f812f1d)
图三
![image](https://github.com/user-attachments/assets/41b4fd7d-a046-4d94-99ef-085300db5de2)
图四


调试发现有2个坑点会和antd表现不一致

1. `rc-select`内部的`onInternalSearch`会判断searchValue是否一致（见图一）。如果在SearchSelecton的onChange回调不清理searchValue，那么onInternalSearch的判断会始终未true，从而导致了onSearch触发。
2. 即使调用了`setSearchValue(undefined)`，但rc-select的mergedSearchValue是过滤了外部传入的searchValue值，导致中途有一次渲染图二中的判断不相等（可能是更新值时机不同步问题，待进一步排查）。这时mergedSearchValue 仍有值而newSearchText是空字符串，从而导致了onSearch触发。

综上我的解决方案是：onChange单选始终会设置searchValue为空字符串为不是undefined，同时不会触发加载数据的回调。目前的效果和官网搜索demo是一致的，大家可以试试。

下面是补丁。

```
diff --git a/es/components/Select/SearchSelect/index.js b/es/components/Select/SearchSelect/index.js
index a252d8babb8c5b7637564bf9d3eccd24d8388839..b7aef85867157b8a6ac699836450a30b1f37996e 100644
--- a/es/components/Select/SearchSelect/index.js
+++ b/es/components/Select/SearchSelect/index.js
@@ -152,10 +152,10 @@ var SearchSelect = function SearchSelect(props, ref) {
     } : undefined,
     onChange: function onChange(value, optionList) {
       // 将搜索框置空 和 antd 行为保持一致
-      if (showSearch && autoClearSearchValue) {
-        fetchData(undefined);
-        onSearch === null || onSearch === void 0 ? void 0 : onSearch('');
-        setSearchValue(undefined);
+      if (showSearch && (autoClearSearchValue || !mode)) {
+        // fetchData(undefined);
+        // onSearch === null || onSearch === void 0 ? void 0 : onSearch('');
+        setSearchValue('');
       }
       for (var _len = arguments.length, rest = new Array(_len > 2 ? _len - 2 : 0), _key = 2; _key < _len; _key++) {
         rest[_key - 2] = arguments[_key];
diff --git a/lib/components/Select/SearchSelect/index.js b/lib/components/Select/SearchSelect/index.js
index d6c4ca92665990292740448205a9aa882c2bc185..b4bbc60f59b07659f2859df642846f60ccd12012 100644
--- a/lib/components/Select/SearchSelect/index.js
+++ b/lib/components/Select/SearchSelect/index.js
@@ -156,10 +156,10 @@ var SearchSelect = function SearchSelect(props, ref) {
     } : undefined,
     onChange: function onChange(value, optionList) {
       // 将搜索框置空 和 antd 行为保持一致
-      if (showSearch && autoClearSearchValue) {
-        fetchData(undefined);
-        onSearch === null || onSearch === void 0 ? void 0 : onSearch('');
-        setSearchValue(undefined);
+      if (showSearch && (autoClearSearchValue || !mode)) {
+        // fetchData(undefined);
+        // onSearch === null || onSearch === void 0 ? void 0 : onSearch('');
+        setSearchValue('');
       }
       for (var _len = arguments.length, rest = new Array(_len > 2 ? _len - 2 : 0), _key = 2; _key < _len; _key++) {
         rest[_key - 2] = arguments[_key];
```

**Comment by zhenghuanhuan** [comment]
还没解决吗？
