### ISSUE TITLE
🧐[问题] 为什么使用ProColumns中的formItemProps重新渲染输入组件后，会多出一个空行？

### ISSUE THREAD

**Issue by xLikeWATCHDOG** [ant-design/pro-components#6890]
### 🧐 问题描述

如标题

### 💻 示例代码

![F D7 D(Y@P@ N8$XAO28~{W](https://user-images.githubusercontent.com/73741466/229965922-af745273-8fb9-4c83-b4e1-9f290437d218.png)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/73741466/229966085-416e69a5-bf6b-4037-9d1b-7bf6cc41859f.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 📝 解决方案

问题原因：使用了`formItemProps`配置项时，在重新渲染输入组件时，会产生一个空行。

解决方法：将`formItemProps`配置项改为`formItemRender`配置项，并在该配置项中自定义表单项的渲染方式。

具体代码如下：

```jsx
import { ProFormText } from '@ant-design/pro-form';
import { Input } from 'antd';

<ProFormText
  name="username"
  label="用户名"
  formItemRender={() => (
    <Input placeholder="请输入用户名" />
  )}
/>;
```

文档：[ProForm - 自定义FormItem](https://procomponents.ant.design/components/form-cn/#feed-%E8%AE%A1%E5%88%92)

**Comment by chenshuai2144** [comment]
是 formItem 用来展示错误信息的地方，你可以用 style 关掉
