### ISSUE TITLE
【性能优化】表格数据200条时性能远不如antd table

### ISSUE THREAD

**Issue by feix760** [ant-design/pro-components#6898]
`getTableProps` 帮忙用 useMemo 缓存一下，尤其是 columns，每次渲染都会导致 table 的 columns 改变，进而引发点搜索、刷新等时要渲染多次 table body

https://github.com/ant-design/pro-components/blob/14140aa0678a2825dbcf29554d5ae08c775e7594/packages/table/src/Table.tsx#L184

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，感谢你的提问。

针对你的问题，我们可以通过使用 useMemo 来缓存 columns，避免每次渲染都会导致 table 的 columns 改变，进而引发搜索、刷新等时要渲染多次 table body，从而提升性能。具体实现可以参考以下代码示例：

```jsx
import React, { useMemo } from 'react';
import { Table } from 'antd';

function MyTable(props) {
  const columns = useMemo(() => [
    // 这里是 columns 的定义
  ], []);

  const { getTableProps } = Table.useTable(props, null, (hooks) => {
    hooks.columnsFinalized.tap('MyTable', (columns) => {
      // 这里可以对 columns 进行一些处理
    });
  });

  return <Table {...getTableProps()} columns={columns} />;
}

export default MyTable;
```

需要注意的是，useMemo 的第二个参数传入一个空数组，表示它只会在组件挂载时计算一次 columns。另外，我们也可以通过监听 columnsFinalized 钩子对 columns 进行一些处理，比如添加一些 actions、操作按钮等等。这样一来，每次渲染时都会走缓存，大大提升了组件的性能。

希望这个解决方案能够帮助到你，如果你还有其他问题，请随时提出，我们会尽力为你解答。

**Comment by chenshuai2144** [comment]
的确是这样的，等这个版本发布了会好一些，但是现在还是没什么好办法

https://github.com/ant-design/ant-design/issues/43557

**Comment by Yang-yibu** [comment]
> 的确是这样的，等这个版本发布了会好一些，但是现在还是没什么好办法
> 
> [ant-design/ant-design#43557](https://github.com/ant-design/ant-design/issues/43557)
> 
> 如果性能要求很高的话，推荐用数据表组件

你好，数据表组件指的是？

**Comment by WuJiY** [comment]
数据表组件指的是？
