### ISSUE TITLE
🐛[BUG] ProLayout - 高级布局 AppList - Top 顶部菜单布局 点击无法正确跳转 

### ISSUE THREAD

**Issue by itmeryn** [ant-design/pro-components#6899]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProLayout - 高级布局 AppList - Top 顶部菜单布局 点击无法正确跳转 
### © 版本信息

@ant-design/pro-components 2.4.4
@umijs/max 4.0.63
antd 5.3.3
@types/react 18.0.31
@types/react-dom 18.0.11

**Comment by itmeryn** [comment]
![image](https://user-images.githubusercontent.com/18156931/230354300-540c05e5-1674-47af-bbbf-db2fd18ea76c.png)

**Comment by itmeryn** [comment]
https://github.com/ant-design/pro-components/blob/master/packages/layout/src/components/GlobalHeader/index.tsx#L41

**Comment by zhanyeye** [comment]
大佬，请问是如何解决的呀
