### ISSUE TITLE
🧐[问题] ProFormList  支持一维数组吗？

### ISSUE THREAD

**Issue by rozbo** [ant-design/pro-components#6902]
我看现在ProFormList 的例子都是支持的 object array，但假如我想实现一个比较简单的数组，比如string array, ["111",“222”]
也就是这种情况
https://ant.design/components/form-cn#components-form-demo-dynamic-form-item

不知道ProFormList 有方案吗？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，感谢您的提问。根据您的描述，您想要实现一个简单的 string array，应该是可以通过 ProFormList 来实现的。

ProFormList 默认是支持 object array 的，但是您可以通过设置 ProFormFieldProps 的 name 属性为一个字符串来实现 string array。示例如下：

```tsx
import { ProFormText, ProFormList } from '@ant-design/pro-form';

const Demo = () => {
  return (
    <ProFormList
      name="list"
      label="String Array"
      creatorButtonProps={{
        position: "bottom",
        children: "Add",
      }}
    >
      <ProFormText name="list" label="Item" />
    </ProFormList>
  );
};
```

在上述示例中，我们将 ProFormText 的 name 属性设置为“list”，并将其包裹在 ProFormList 中。这样，ProFormList 就会将所有输入的 string 放到一个名为“list”的数组中，可以通过表单数据来获取。

另外，如果需要对 ProFormList 中的每一个 string 进行校验，也可以通过在 ProFormText 中使用 rules 属性来实现。例如：

```tsx
import { ProFormText, ProFormList } from '@ant-design/pro-form';

const Demo = () => {
  return (
    <ProFormList
      name="list"
      label="String Array"
      creatorButtonProps={{
        position: "bottom",
        children: "Add",
      }}
    >
      <ProFormText
        name="list"
        label="Item"
        rules={[{ required: true, message: "Please input the item!" }]}
      />
    </ProFormList>
  );
};
```

在上述示例中，我们通过在 ProFormText 中设置 rules 属性来校验每一个输入的 string 是否为空。您可以根据需要调整校验规则。

希望这个回答可以帮到您，如有任何疑问或者需要更详细的解释，请随时追问。

**Comment by chensrry** [comment]
用了作者给的demo，发现还是 {}[]这种数据结构

**Comment by chenshuai2144** [comment]
`ProFormSet` 有这个组件的，你试试

**Comment by Zzm0809** [comment]
> ProFormSet

+1

**Comment by Zzm0809** [comment]
> 用了作者给的demo，发现还是 {}[]这种数据结构

+1

**Comment by hyyzzz111** [comment]
研究了半天，我是用下面的代码解决的
` <ProFormList
        name={['config',  'repositories']}
        label={'path'}
      >
        {props => {
          const path = ['config', 'repositories', props.name];
          return (
            <ProFormText
              {...props}
              fieldProps={{
                onChange: e => {
                  form.setFieldValue(path, e.target.value);
                },
              }}
              getValueProps={() => {
                return {
                  value: form.getFieldValue(path),
                };
              }}
            ></ProFormText>
          );
        }}
      </ProFormList>`

**Comment by nondanee** [comment]
可以支持

children 可以传入函数，第一个参数 field 里面有 key 和 name，直接用 Form.Item 注册字段就行

新建的默认值要 hack 处理一下

```jsx
<ProFormList
  name="list"
  label="String Array"
  creatorRecord={() => ({
    toString: () => '',
  })}
  creatorButtonProps={{
    position: 'bottom',
    children: 'Add',
  }}
>
  {(field, index, action) => (
    <Form.Item {...field} label="Item">
      <Input />
    </Form.Item>
  )}
</ProFormList>
```

**Comment by one-pieces** [comment]
竟然不支持一维数组，也是服了

**Comment by clownM** [comment]
> `ProFormSet` 有这个组件的，你试试

ProForm没有自带增删等操作呢

**Comment by shenshouer** [comment]
> 用了作者给的demo，发现还是 {}[]这种数据结构

+1

**Comment by shenshouer** [comment]
> 可以支持
> 
> children 可以传入函数，第一个参数 field 里面有 key 和 name，直接用 Form.Item 注册字段就行
> 
> 新增 item 的默认值要 hack 处理一下
> 
> ```js
> <ProFormList
>   name="list"
>   label="String Array"
>   creatorRecord={() => ({
>     toString: () => '',
>   })}
>   creatorButtonProps={{
>     position: 'bottom',
>     children: 'Add',
>   }}
> >
>   {(field, index, action) => (
>     <Form.Item {...field} label="Item">
>       <Input />
>     </Form.Item>
>   )}
> </ProFormList>
> ```

初始化的值显示是对的，但新增一项显示[object Object]
![image](https://github.com/ant-design/pro-components/assets/1491181/5517d4ea-ad69-473e-9b19-4d67392b1d62)

**Comment by nondanee** [comment]
> > 可以支持
> > children 可以传入函数，第一个参数 field 里面有 key 和 name，直接用 Form.Item 注册字段就行
> > 新增 item 的默认值要 hack 处理一下
> > ```js
> > <ProFormList
> >   name="list"
> >   label="String Array"
> >   creatorRecord={() => ({
> >     toString: () => '',
> >   })}
> >   creatorButtonProps={{
> >     position: 'bottom',
> >     children: 'Add',
> >   }}
> > >
> >   {(field, index, action) => (
> >     <Form.Item {...field} label="Item">
> >       <Input />
> >     </Form.Item>
> >   )}
> > </ProFormList>
> > ```
> 
> 初始化的值显示是对的，但新增一项显示[object Object] ![image](https://private-user-images.githubusercontent.com/1491181/345372291-5517d4ea-ad69-473e-9b19-4d67392b1d62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTk5ODMsIm5iZiI6MTcyMDE5OTY4MywicGF0aCI6Ii8xNDkxMTgxLzM0NTM3MjI5MS01NTE3ZDRlYS1hZDY5LTQ3M2UtOWIxOS00ZDY3MzkyYjFkNjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDVUMTcxNDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJjOTdmZTVhYWIxYTUwMzgzZDVhZjAzZDlmZTk2ODkzYjdhYTk4NmY3OWJhZGMxOTRjNDM4YTZmOGY5ZjA0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Cs9BXK8l98L-uliuBZrrjdjejvHjxYif7UbcoX4DJNM)
> 
> 如果修改改成
> 
> ```
> {(meta, idx) => (
>                     <ProFormText {...meta} />
>                 )}
> ```
> 
> 给的初始化值只会显示字符串的第一个字符 ![image](https://private-user-images.githubusercontent.com/1491181/345373041-c3ef22e1-4726-4fa4-b335-8cdd76458cab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTk5ODMsIm5iZiI6MTcyMDE5OTY4MywicGF0aCI6Ii8xNDkxMTgxLzM0NTM3MzA0MS1jM2VmMjJlMS00NzI2LTRmYTQtYjMzNS04Y2RkNzY0NThjYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDVUMTcxNDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWY5YjI5ZjQzMDBkZWI5ODQzMWY1YmY5MDdhNDMzM2ZiNTgyNzk2OTg2MzIwNWJkOGQ4ZjM1ZTdiN2EzZDI1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1_ppIicrvRV25oVRwyNjeyDa14koUkpMyqtjHYd_8pg)

https://codesandbox.io/p/sandbox/proformlist-stringarraydemo-xw5fqx?file=%2FApp.tsx%3A22%2C30

我在 codesandbox 试了下没问题呀，不会显示 [object Object]

另外 `creatorRecord` 用 `new String()` 也可以过非空判断

```js
        creatorRecord={() => {
          const record = new String("");
          return record;
        }}
```
