### ISSUE TITLE
🐛[BUG] SchemaForm 自定义valueType 渲染 EditableProTable FormItem 无法与其关联

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#6903]
使用SchemaForm ，自定义valueType，实现 renderFormItem 方法，并给EditableProTable组件传递了fieldProps，点击提交，Form并未获取到EditableProTable的值。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，根据您提供的信息，可能是由于自定义valueType没有正确与EditableProTable的值关联导致的问题，您可以参考以下解决方案：

1. 确认自定义valueType是否正确实现了fromValue和toValue方法。fromValue方法用于将valueProps的值转换为组件初始值，toValue方法用于将组件的值转换为valueProps的值。

例如：

```javascript
const valueType = {
  fromValue: (value) => ({
    dataSource: value || []
  }),
  toValue: (value) => value.dataSource
}
```

2. 在EditableProTable的fieldProps属性中，指定valueType为自定义的valueType，并将值绑定到valueProps中。您可以在valueProps中指定一个onDataChange函数，以在值更改时更新Form数据。

例如：

```javascript
<SchemaForm initialValues={initialValues} fields={fields} onSubmit={onSubmit}>
  <SchemaMarkupField type="array" name="dataSource" title="Table">
    <ProFormList {...fieldProps} />
  </SchemaMarkupField>
  <SchemaMarkupField type="object" name="form">
    <Form.Item label="Form">
      <Input {...formProps.itemProps} />
    </Form.Item>
  </SchemaMarkupField>
  <FormButtonGroup>
    <Button type="primary" htmlType="submit">Submit</Button>
  </FormButtonGroup>
</SchemaForm>

const fieldProps = {
  valueType: 'table',
  valueProps: {
    onChange: (value) => {
      form.setFieldsValue({
        dataSource: value
      })
    },
    onDataChange: (value) => {
      form.setFieldsValue({
        dataSource: value
      })
    },
    props: {
      columns: columns,
      editable: true
    }
  }
}
```

3. 提交时，确认Form表单中是否可以正确获取值。如果仍然无法获取值，可能是由于自定义valueType的fromValue/toValue方法有误或存在其他错误。这时，可以使用调试工具进行排查。

希望以上方案能够帮助您解决问题。如果还有疑问或其他问题，请随时回复。
