### ISSUE TITLE
ProTable当设置preserveSelectedRowKeys为true时读取selectedRows值错误🐛[BUG]🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/pro-components#6904]
### 🐛 bug 描述

在ProTable组件中设置preserveSelectedRowKeys为true，并且设置selectedRowKeys默认选中值, 并且设置默认不可选中的条目，在onChange中打印selectedRows值时出现undefined的情况。
![image](https://user-images.githubusercontent.com/20655248/230552312-c19a09b6-0f57-4b49-9a7f-a211bec2f578.png)
![image](https://user-images.githubusercontent.com/20655248/230553205-d22f75df-70c0-405d-bae2-4dc3fe79fa57.png)

@ant-design/pro-components":版本"2.3.58

### © 版组件中设置本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🌈 解决方案

根据你提供的情况，从截图上看选择框中的条目是可选的，但是在onChange事件中会出现选中的条目为undefined的情况。对于这种情况，我们需要注意一下几点：

1. 可能是selectedRowKeys没有正确设置

在你的代码中，你有通过selectedRowKeys属性对选中的条目进行了初始化。但是在onChange事件中，如果selectedRowKeys值为undefined，显然选中的条目也会为undefined。因此，我们需要确认一下selectedRowKeys属性有没有正确设置。可以通过打印输出确认一下。如果selectedRowKeys确实没有正常设置，可以根据需求进行修改。

2. 可能是preserveSelectedRowKeys设置不正确

preserveSelectedRowKeys设置为true的话，会保存这个表格的选中状态。如果你希望设置只能选中某些条目，可以通过设置disabled属性让某些条目不可选。但是需要注意的是，由于preserveSelectedRowKeys的存在，当你全部的条目都设置了disabled时，onChange事件中打印的selectedRows值会为undefined。因此，合理设置disabled属性会有助于解决这个问题。

3. 可能是selectedRows事件没有处理

在ProTable组件中，selectedRows事件一般是在onChange事件中调用的。如果你没有对selectedRows事件进行处理，或者处理不正确，那么在onChange事件中打印出来的selectedRows值很可能为undefined。

如果以上步骤都没有解决问题，可以尝试检查一下其他的代码。

### 📖 参考文档

- [ProTable API 文档](https://procomponents.ant.design/components/table-cn/)
- [Antd 选项 API 文档](https://ant.design/components/select-cn/#API)
- [Antd Table API 文档](https://ant.design/components/table-cn/#API)

**Comment by chenshuai2144** [comment]
如果在使用 `ProTable` 组件时，设置了 `preserveSelectedRowKeys` 为 `true`，并且通过 `selectedRowKeys` 属性设置了默认选中的行，但在 `onChange` 事件中打印 `selectedRows` 时出现 `undefined` 的情况，可能是由于配置问题导致的。

一种可能的解决方法是，确保 `ProTable` 组件的 `rowSelection` 属性与 `selectedRowKeys` 和 `onChange` 事件正确配合使用。

以下是一个示例代码，展示如何在 `ProTable` 中设置选中行和处理 `onChange` 事件：

```jsx
import React, { useState } from 'react';
import { ProTable } from '@ant-design/pro-table';

function MyTable() {
  const [selectedRowKeys, setSelectedRowKeys] = useState([]);

  const handleTableChange = (selectedRowKeys, selectedRows) => {
    setSelectedRowKeys(selectedRowKeys);
    console.log(selectedRows);
    // 执行其他操作...
  };

  return (
    <ProTable
      rowSelection={{
        selectedRowKeys,
        onChange: handleTableChange,
        preserveSelectedRowKeys: true,
      }}
      // 其他ProTable组件的配置项...
    />
  );
}

export default MyTable;
```

在上述代码中，我们使用 `useState` 钩子创建了 `selectedRowKeys` 状态来存储选中行的值。`handleTableChange` 函数用于处理 `onChange` 事件，其中我们更新了 `selectedRowKeys` 状态，并打印了 `selectedRows` 值。请确保在 `selectedRowKeys` 更新后再打印 `selectedRows`，以便获取最新的选中行数据。

在 `ProTable` 组件中，我们使用了 `rowSelection` 属性来配置行选择功能。通过设置 `selectedRowKeys` 属性为 `selectedRowKeys` 状态的值，以及设置 `onChange` 属性为 `handleTableChange` 函数，实现了对选中行的控制和数据的接收。

请根据您的实际需求和组件配置进行相应的调整，确保属性的正确设置和事件处理的逻辑。
