### ISSUE TITLE
ellipsis:true 时，表头内容过长也会触发省略，但是表头没有在tooltip的功能呢？

### ISSUE THREAD

**Issue by chenJJ-88** [ant-design/pro-components#6908]
![image](https://user-images.githubusercontent.com/118970817/230752887-eb99a6f3-4ead-4233-9331-eec9d7411870.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


如果您使用的是 Ant Design 的表格组件，可以通过设置表头的 `title` 属性为表头内容来实现在tooltip中显示表头文本。示例代码如下：

```jsx
import { Table } from 'antd';

const columns = [
  {
    title: '表头文本',
    dataIndex: 'dataIndexName',
    ellipsis: true,
    // 添加title属性
    title: '这是一个非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常长的表头文本',
  },
  {
    title: '数据',
    dataIndex: 'data',
  },
];

const data = [
  {
    key: 1,
    dataIndexName: '这是一个非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常非常长的表头文本',
    data: '数据1',
  },
  {
    key: 2,
    dataIndexName: '表头文本2',
    data: '数据2',
  },
];

function App() {
  return <Table columns={columns} dataSource={data} />;
}
```

更多关于 Ant Design 表格组件的文档请参考 [Ant Design Table](https://ant.design/components/table-cn/)。

**Comment by chenJJ-88** [comment]
> 你试试 antd

就是不想换antd，Pro这里比较快，是在不行我就让其中一些不缩略吧，谢谢

**Comment by vaynevayne** [comment]
> 

快在哪里? 我感觉一样的啊

**Comment by vaynevayne** [comment]
ProTable 的第一个例子, ellipsis时, 标题太长会截断,  并不会显示...啊 
@chenJJ-88 

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/124666577/231399852-da9e297f-78d5-470f-b3cc-b3106864cc1e.png">

https://codesandbox.io/s/dsekbp?file=/App.tsx

**Comment by vaynevayne** [comment]
antd 的ellipsis 是显示...,  protable是截断,  至于你使用protable, 却显示了..., 那就很奇怪了

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/124666577/231400337-f10a6131-d581-4bdb-bc11-49333bc76e0c.png">

**Comment by chenJJ-88** [comment]
> ProTable 的第一个例子, ellipsis时, 标题太长会截断, 并不会显示...啊 @chenJJ-88
> 
> <img alt="image" width="1190" src="https://user-images.githubusercontent.com/124666577/231399852-da9e297f-78d5-470f-b3cc-b3106864cc1e.png">
> 
> https://codesandbox.io/s/dsekbp?file=/App.tsx

他是加了一个tip属性，截断后会有一个！号，hover上去会显示出完整的表头，如果去掉tip属性，就是显示省略了

**Comment by vaynevayne** [comment]
那就是跟antd一致, protable没有问题,  至于你的需求,估计得设置宽度

**Comment by hanwenbo** [comment]
ellipsis.showTitle 也关不掉  第一次有效 路由再进入还是会显示
