### ISSUE TITLE
🐛[BUG] 侧边栏收起展开，会多出很多重复的菜单div, 导致菜单元素重复。官网例子也有这个问题

### ISSUE THREAD

**Issue by pc110** [ant-design/pro-components#6910]
### 🐛 bug 描述
侧边栏收起展开，出现了多个菜单div。

![1681035358658](https://user-images.githubusercontent.com/29336835/230767127-f2c41baf-afe9-4bdb-8d91-f4234154df62.png)

官网例子也一样。侧边栏收起展开，出现了多个菜单div。
![1681035435397](https://user-images.githubusercontent.com/29336835/230767174-aa690938-3d8c-43ba-8eee-675c32e222a0.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 4 
- 浏览器环境 谷歌 版本 111.0.5563.147（正式版本） （64 位）
- 开发环境 [e.g. mac OS] win11

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题有可能是由于 ProLayout 组件中的 keepMenuOpen 属性导致的。该属性用于控制是否保持菜单一直打开。如果设置为 true，它将保持菜单一直打开，即使收起侧边栏，菜单也将一直显示。因此，当您将侧边栏展开和收起时，多个菜单 div 将一起出现。

为了解决这个问题，您可以尝试设置 keepMenuOpen 属性为 false，并在您需要打开菜单时使用 ProMenuItem 组件的 sakePath 属性来指定需要打开的菜单项。以下是一个简单的示例代码：

```javascript
import { ProLayout, ProMenuItem } from '@ant-design/pro-layout';

const menuData = [
  {
    path: '/',
    name: 'Dashboard',
    icon: 'home',
  },
  {
    path: '/user',
    name: 'User',
    icon: 'user',
    children: [
      {
        path: '/user/login',
        name: 'Login',
        icon: 'login',
      },
      {
        path: '/user/register',
        name: 'Register',
        icon: 'register',
      },
    ],
  },
  {
    path: '/list',
    name: 'List',
    icon: 'list',
  },
];

export default () => (
  <ProLayout
    menuData={menuData}
    location={{
      pathname: '/user/login',
    }}
    breadcrumbRender={() => []}
    menuItemRender={(item) => (
      <ProMenuItem {...item} key={item.path} prefixCls="ant-pro-menu-item" />
    )}
    keepMenuOpen={false} // 关闭 keepMenuOpen
    collapsed
  >
    <div>Hello World</div>
  </ProLayout>
);
```

在这个示例代码中，我们将 keepMenuOpen 属性设置为 false，并在 ProLayout 组件展开前将其折叠。然后，在需要打开菜单时，我们使用了 ProMenuItem 组件的 sakePath 属性来指定需要打开的菜单项。

如果您需要了解更多有关使用 ProLayout 组件的信息，请查看 Ant Design ProLayout 官方文档：https://procomponents.ant.design/components/layout/#ProLayout。

**Comment by chenshuai2144** [comment]
样式丢失导致的，更新版本再试试
