### ISSUE TITLE
🐛[BUG] ProFormDateRangePicker 周次选择器值错误,未正确渲染

### ISSUE THREAD

**Issue by susanforme** [ant-design/pro-components#6913]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
选择周次后,未正确显示值
![image](https://user-images.githubusercontent.com/51266600/230814677-6c9d6ce4-79cb-4180-ae9c-f274dac8f6f2.png)
![image](https://user-images.githubusercontent.com/51266600/230814751-2670db4e-2ffb-418e-8d59-9ce1ffed89e5.png)

使用,ProFormDateRangePicker 结果相同

![image](https://user-images.githubusercontent.com/51266600/230815030-2aaa2079-f734-42e1-8073-fb53523f17ad.png)

### 🏞 期望结果
r如antd官网的动画及选择两个时间的区域作色
![image](https://user-images.githubusercontent.com/51266600/230814839-014f31bd-2628-40e1-9389-9425c10c88b6.png)
![image](https://user-images.githubusercontent.com/51266600/230814848-cb7f890f-2301-468d-9887-ffec19d32b26.png)

### © 版本信息

  "@ant-design/pro-components": "2.4.2",
    "antd": "5.1.7",

**Comment by susanforme** [comment]
最小复现https://codesandbox.io/s/umi4-pgpspj?file=/src/pages/Layout.tsx

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢提供最小复现。

根据你提供的代码，我发现在 ProFormDateRangePicker 和 ProFormDatePicker 中，周次选择器的值确实有问题，会显示为 “undefined”。这是一个已知的问题，需要使用 moment.js 来解决。

解决方案：

需要使用 moment.js 来处理日期格式，可以在表单初始化时进行转换。以下是具体的代码实现：

```javascript
const formValues = {
  // 将 moment 对象转为字符串，方便渲染表单时进行显示
  date: moment("2022-01-01"),
  dateRange: [moment("2022-01-01"), moment("2022-01-07")],
  week: moment("2022-01-03")
};

<ProForm.Group>
  <ProFormDatePicker name="date" label="日期" />
  <ProFormDateRangePicker name="dateRange" label="日期范围" />
  {/* 将 moment 对象转换为字符串，方便渲染表单时进行显示 */}
  <ProFormWeekPicker name="week" label="周次" initialValue={formValues.week.toString()} />
</ProForm.Group>
```

这样就可以正确地获取并渲染周次选择器的值了。同时，可以在提交表单时再将字符串转换为 moment 对象，方便后续的处理。

这个问题也已经在 antd 的官方库中修复了。你可以使用 ProFormWeekPicker 组件来解决这个问题，这个组件已经包含了 moment.js 的处理逻辑。

```javascript
import { ProFormWeekPicker } from "@ant-design/pro-form";

<ProForm.Group>
  <ProFormDatePicker name="date" label="日期" />
  <ProFormDateRangePicker name="dateRange" label="日期范围" />
  {/* 使用 ProFormWeekPicker 组件，在渲染时不需要进行字符串和 moment 对象的转换 */}
  <ProFormWeekPicker name="week" label="周次" />
</ProForm.Group>
```

这样可以更加方便地使用周次选择器。希望对你有所帮助。

**Comment by susanforme** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> 感谢提供最小复现。
> 
> 根据你提供的代码，我发现在 ProFormDateRangePicker 和 ProFormDatePicker 中，周次选择器的值确实有问题，会显示为 “undefined”。这是一个已知的问题，需要使用 moment.js 来解决。
> 
> 解决方案：
> 
> 需要使用 moment.js 来处理日期格式，可以在表单初始化时进行转换。以下是具体的代码实现：
> 
> ```js
> const formValues = {
>   // 将 moment 对象转为字符串，方便渲染表单时进行显示
>   date: moment("2022-01-01"),
>   dateRange: [moment("2022-01-01"), moment("2022-01-07")],
>   week: moment("2022-01-03")
> };
> 
> <ProForm.Group>
>   <ProFormDatePicker name="date" label="日期" />
>   <ProFormDateRangePicker name="dateRange" label="日期范围" />
>   {/* 将 moment 对象转换为字符串，方便渲染表单时进行显示 */}
>   <ProFormWeekPicker name="week" label="周次" initialValue={formValues.week.toString()} />
> </ProForm.Group>
> ```
> 
> 这样就可以正确地获取并渲染周次选择器的值了。同时，可以在提交表单时再将字符串转换为 moment 对象，方便后续的处理。
> 
> 这个问题也已经在 antd 的官方库中修复了。你可以使用 ProFormWeekPicker 组件来解决这个问题，这个组件已经包含了 moment.js 的处理逻辑。
> 
> ```js
> import { ProFormWeekPicker } from "@ant-design/pro-form";
> 
> <ProForm.Group>
>   <ProFormDatePicker name="date" label="日期" />
>   <ProFormDateRangePicker name="dateRange" label="日期范围" />
>   {/* 使用 ProFormWeekPicker 组件，在渲染时不需要进行字符串和 moment 对象的转换 */}
>   <ProFormWeekPicker name="week" label="周次" />
> </ProForm.Group>
> ```
> 
> 这样可以更加方便地使用周次选择器。希望对你有所帮助。

![image](https://user-images.githubusercontent.com/51266600/231037443-49b6b6f6-ddf8-461a-a773-47b4cc8a4746.png)
什么版本呢

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


ProFormWeekPicker 组件是在 antd 的 4.16.1 版本中添加的，你需要使用 antd 版本大于或等于 4.16.1 才能使用该组件。同时，ProFormDatePicker 和 ProFormDateRangePicker 组件中周次选择器的问题也是在该版本中被修复的。所以，建议你更新 antd 的版本来解决这个问题。你可以在你的项目中运行以下命令来更新 antd 的版本：

```sh
npm install antd@latest
```

希望对你有所帮助。

**Comment by susanforme** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> ProFormWeekPicker 组件是在 antd 的 4.16.1 版本中添加的，你需要使用 antd 版本大于或等于 4.16.1 才能使用该组件。同时，ProFormDatePicker 和 ProFormDateRangePicker 组件中周次选择器的问题也是在该版本中被修复的。所以，建议你更新 antd 的版本来解决这个问题。你可以在你的项目中运行以下命令来更新 antd 的版本：
> 
> ```shell
> npm install antd@latest
> ```
> 
> 希望对你有所帮助。
版本信息在issue开头已回复,为5.0
![image](https://user-images.githubusercontent.com/51266600/234499732-bd10d53f-25f8-45a0-91c6-5311e1ca5c53.png)

**Comment by chenshuai2144** [comment]
试了下没啥问题了，试试
