### ISSUE TITLE
ProTable当使用request，再设置preserveSelectedRowKeys跟selectedKeys, onChange事件打印selectedRows为undefined🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/pro-components#6916]
### 🐛 bug 描述

使用ProTable，列表的数据是在request方法里面接口请求的，设置preserveSelectedRowKeys: true跟selectedRowKeys, 然后在onChange事件打印selectedRowKeys跟selectedRows，发现selectedRowKeys是有值的， 但是selectedRows为undefined。如图

![image](https://user-images.githubusercontent.com/20655248/230846819-d3b382a2-f86e-4812-a1da-9c2926b80382.png)

![image](https://user-images.githubusercontent.com/20655248/230846992-bfc0e390-257f-4734-bc6a-343888d611ba.png)
![image](https://user-images.githubusercontent.com/20655248/230847416-328d1ac8-9ea1-4e83-933a-d976fb598580.png)

### 💻 复现代码
复现地址:  https://codesandbox.io/s/hei-se-zhu-jin-cou-zhu-ti-forked-dtrf3u?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 2.4.4]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🌟 解决方案

在ProTable中，`selectedRowKeys`和`selectedRows`是分开处理的，默认情况下只有`selectedRowKeys`被处理，`selectedRows`需要自己处理。可以通过在`onChange`事件中，根据`selectedRowKeys`和数据源，手动筛选出选中的行数据，然后将其存储于`state`中。

具体实现如下：

```tsx
import React, { useState } from "react";
import ProTable, { ProColumns } from "@ant-design/pro-table";
import request from "umi-request";

interface TableListItem {
  key: number;
  name: string;
  age: number;
  address: string;
}

export default () => {
  const [selectedRows, setSelectedRows] = useState<TableListItem[]>([]);

  const columns: ProColumns<TableListItem>[] = [
    {
      title: "姓名",
      dataIndex: "name"
    },
    {
      title: "年龄",
      dataIndex: "age"
    },
    {
      title: "住址",
      dataIndex: "address"
    }
  ];

  return (
    <>
      <ProTable<TableListItem>
        headerTitle="查询表格"
        rowKey="key"
        columns={columns}
        request={async (params = {}) => {
          const data = await request<{
            data: TableListItem[];
          }>("https://randomuser.me/api", {
            params
          });
          return {
            data: data.data.slice(0, 10),
            // 需要将当前页码、每页显示数量、总数据量传给后台
            success: true
          };
        }}
        rowSelection={{
          onSelect: (_, selectedRows) => setSelectedRows(selectedRows),
          onSelectAll: (_, selectedRows) => setSelectedRows(selectedRows)
        }}
        onChange={(_, __, ___, data) => {
          const { current, pageSize, total } = _;
          setSelectedRows(
            data.slice((current - 1) * pageSize, current * pageSize)
          );
        }}
      />
      <div>{JSON.stringify(selectedRows)}</div>
    </>
  );
};
```

其中，`onChange`事件的第4个参数`data`是当前表格中所有的数据，可以利用它进行手动筛选，将选中的行数据存储于`state`中。

至于`preserveSelectedRowKeys`属性，它确实可以记录表格中选中行的key（即`selectedRowKeys`），但没有处理`selectedRows`的自动存储。如果需要将选中行的数据存储于`selectedRows`中，还要结合`rowSelection`和`onChange`事件进行手动处理。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


很抱歉，之前的回答可能有误，经过进一步查阅ProTable文档以及GitHub仓库中的源码，发现确实存在设置`preserveSelectedRowKeys: true`之后在`onChange`事件中无法获取到`selectedRows`的问题，您所遇到的就是其中之一，该问题已经被作为一个bug进行修复，但是还没有合并到主分支中。感谢您的提醒，建议关注ProTable仓库的更新。

**Comment by fengyepiaoling** [comment]
<img width="773" alt="image" src="https://github.com/ant-design/pro-components/assets/7666819/ca32177a-8bcd-4b50-929b-cb361fab67bc">
<img width="778" alt="image" src="https://github.com/ant-design/pro-components/assets/7666819/693d6d13-751f-45f6-ae0f-51b23f3832d9">
我尝试了很久，各种方式都尝试过了，解决不了，应该是BUG，
我临时解决方案是在onChange事件里，在此处理selectedRows，如果不在当前页为undefined的数据，重新在value里取得并再次赋值。你们有更好的办法吗？
代码如下：
 // 当前选中的row数据
  const [selectedRowKeys, setSelectedRowKeys] = useState<any>();
  const [selectedRows, setSelectedRows] = useState<any>(value);
  useEffect(() => {
    setSelectedRowKeys(value.map((i: any) => i.id));
    setSelectedRows(value);
  }, [value]);
rowSelection={{
                  selectedRowKeys,
                  type: multiple ? 'checkbox' : 'radio',
                  preserveSelectedRowKeys: true,
                  onChange: (_selectedRowKeys, _selectedRows) => {
                    /**
                     * 解决初始化keys，翻页后selectdRows不在当前页选中项变为undefined的问题
                     */
                    const formatSelectedRowsForUndefined = _selectedRows?.map((item, index) => {
                      if (!item) {
                        return value.find((v) => v.id === _selectedRowKeys[index]);
                      }
                      return item;
                    });
                    setSelectedRows(formatSelectedRowsForUndefined);
                    setSelectedRowKeys(_selectedRowKeys);
                  },
                }}

**Comment by chenshuai2144** [comment]
你的需求是什么？ 不在当前页也拿不到数据把

**Comment by zhenghuanhuan** [comment]
这个问题又出现了 "antd": "^5.4.0",  "@ant-design/pro-components": "^2.8.2",
