### ISSUE TITLE
👑 [需求]PR合入已一周多了，为什么还不发布新版，求发布

### ISSUE THREAD

**Issue by ldwonday** [ant-design/pro-components#6917]
如题

**Comment by ldwonday** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，感谢联系 GitHub issue 助理。请问你的问题是关于 React 的前端问题吗？如果是的话，请描述你的问题和相关环境、步骤等细节信息，让我更好地了解你的问题并提供帮助。 鉴于你提到的是一个和 GitHub release 相关的问题，我先回答这个问题。

首先，GitHub release 与 PR（Pull Request）是不同的概念。PR 是一种给开源项目贡献代码、修改bug或者提出新特性的方式，需要经过开源项目管理者的审核。而 GitHub release 是开源项目发布新版本的一种方式，通过打标签（Tag）的方式来标识并且附上发布日志、二进制文件等信息。

如果你的问题是关于 GitHub release 的，我建议你先确认你有权限发布新版本，并且对应的 PR 已经被合并且包含你想要发布的新特性或修复的 bug。如果确认无误，可以按照以下步骤发布一个新版本：

1. 进入对应仓库的 release 页面：https://github.com/<your_github_name>/<your_repo_name>/releases
2. 点击页面右上角的 "Draft new release" 或 "Create new release" 按钮。
3. 填写版本号（Tag version）和发布日志（Release title），可以添加标签（Label）、附件（Attach binaries）等信息。
4. 选择 “Publish release” 发布新版本。

如果你的问题是关于 React 的前端问题，可以请你在这里提出你的问题，我会尽力帮助你解决问题。同时，请按照以下格式给出问题的细节信息，这样我可以更好的理解和回答你的问题：

问题描述：

问题复现步骤：

预期效果：

实际效果：

相关代码（请提供关键代码片段）：

使用的环境和库版本：

其他补充信息（可选）：

**Comment by pc110** [comment]
> @chenshuai2144
最近修复问题越来越慢了

**Comment by leshalv** [comment]
+1

**Comment by Gzbox** [comment]
难道在憋大招 ？😄

**Comment by ldwonday** [comment]
@chenshuai2144 求发版啊！！！
