### ISSUE TITLE
🐛[BUG] Antd升级到5.4后，使用DatePicker出现弃用API的警告

### ISSUE THREAD

**Issue by xiaoqiang1999** [ant-design/pro-components#6918]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [2.4.4]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/40377409/230859565-245dedc0-058e-4b84-82e1-662df9e1661b.png)
![image](https://user-images.githubusercontent.com/40377409/230859867-30c4d41e-e998-4aa2-a45d-46d2b27f197b.png)

Antd 5.4.0更新日志：https://ant.design/changelog-cn#540

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，根据你提供的信息，你可以尝试将代码中使用的 `dateRender` 替换为 `cellRender`。这是由于 Antd 的升级导致 `dateRender` 被标记为已废弃，新版本中使用 `cellRender` 代替。

以下是一个示例代码：

```
import { DatePicker } from 'antd';

function onChange(date, dateString) {
  console.log(date, dateString);
}

function App() {
  return (
    <DatePicker 
      cellRender={value => (
        <div className="custom-cell">
          {value.date()}
        </div>
      )}
      onChange={onChange} 
    />
  );
}
```

你可以为 `cellRender` 属性设置一个函数，这个函数渲染一个数据单元的内容。

更多信息可以查看 Antd 官网的相关文档：https://ant.design/components/date-picker-cn/

**Comment by timecommunication** [comment]
DatePicker 属性里 就没有使用 dateRender 这个属性 ，也会遇到这个报错，一定要定义 cellRender 吗？

**Comment by timecommunication** [comment]
@chenshuai2144

**Comment by AprildreamMI** [comment]
@chenshuai2144 这时antd组件内部在使用dateRender 导致的警告
![image](https://user-images.githubusercontent.com/31964372/231081509-7b3ab42b-ecfa-4e6f-94c0-1312c275d61a.png)
![image](https://user-images.githubusercontent.com/31964372/231081567-cd14603f-8920-4aba-b272-7f7171048c31.png)

**Comment by netcore-jroger** [comment]
这估计是又改成bug了

**Comment by AprildreamMI** [comment]
https://github.com/ant-design/ant-design/issues/41751，提了，已经修复了，但不知道什么时候会合

**Comment by netcore-jroger** [comment]
已发布新版本，升级一下就不提示了。
