### ISSUE TITLE
EditProTable columns 配置中多个rules，弹出提示异常

### ISSUE THREAD

**Issue by zhuiluo0987** [ant-design/pro-components#6920]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
EditProTable columns 配置中多个rules，弹出提示异常，期望能显示红框。点击时，弹出错误提示信息。

### 💻 示例代码
<img width="909" alt="image" src="https://user-images.githubusercontent.com/20220029/230891944-b8cc1f74-cab6-48e8-b8d2-4bbcc1afd136.png">
![image](https://user-images.githubusercontent.com/20220029/230892276-13994fab-bc1e-4ab7-af7f-41cdad58454a.png)

**Comment by zhuiluo0987** [comment]
![image](https://user-images.githubusercontent.com/20220029/230892482-7d703dd1-97e1-4c7e-a535-36b4d2fc1ca9.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


从截图可以看出，在代码中对 `rules` 进行了多次设置，其中最后一次设置的是一个字符串 `"required"` 而不是一个数组，这会导致在表单验证时出现异常。

为了解决问题，我们需要将 `rules` 配置项设置为一个数组，每个元素表示一个验证规则。例如，下面是一个设置了两个验证规则的 `rules` 配置项的示例：

``` javascript
[
  { required: true, message: 'Please input your username' },
  { min: 4, max: 10, message: 'Length should be between 4 and 10' }
]
```

另外，需要在组件中添加 `validateMessages` 配置项，用于自定义验证提示信息。例如：

``` javascript
<EditProTable
  // 其他配置项...
  columns={[
    {
      title: 'Name',
      dataIndex: 'name',
      rules: [
        { required: true, message: 'Please input the name' },
        { min: 2, max: 10, message: 'Length should be between 2 and 10' },
      ],
    },
    // 其他列配置...
  ]}
  validateMessages={{ required: 'Please fill out this field' }}
/>
```

这样，当验证未通过时，会显示自定义提示信息。同时，表单元素也会有红框提示。
