### ISSUE TITLE
🧐[问题] 为什么ProTable的搜索表单在点击展开/收起和重置按钮时，会销毁其中的表单项组件再重新渲染？

### ISSUE THREAD

**Issue by cloudwww** [ant-design/pro-components#6924]
### 🧐 问题描述

在使用ProTable的过程中，发现点击ProTable组件上方的搜索表单的展开/收起、重置按钮时，其中的表单项会销毁重载（已使用useEffect验证了组件确实会被销毁）

这就导致一个问题：我的表单项很多都是下拉框，而下拉数据都是通过请求接口获取的， 当我点击展开/收起、重置按钮时，表单项便会销毁重载，组件会重新请求已经请求过的接口造成资源浪费，有好的解决办法吗

### 🚑 其他信息

项目所用版本：
"antd": "^4.23.3",
"@ant-design/pro-components": "^2.3.52",

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 💡 解决方案

根据Ant Design Pro Table的代码实现，ProTable搜索表单的展开/收起、重置功能都是通过控制state的方式来实现的，而这些state的变化则会导致整个ProTable组件重新渲染。

针对你提到的表单项销毁重载的问题，可以参考以下方案：

1. 使用state管理表单项数据

可以将下拉框的数据保存到ProTable父组件的state中，而不是在表单项组件中请求接口获取数据。这样在ProTable重新渲染时，下拉框的数据已经存在于父组件的state中，并不会影响后续的渲染，也不会浪费资源重新请求数据。

2. 使用memo优化表单项组件

对于表单项组件，可以使用React.memo进行优化。React.memo会对组件的props进行浅比较，只有当props改变时才会重新渲染组件。这样在ProTable重新渲染时，如果表单项的props没有变化，那么表单项组件也不会被销毁重载。

3. 使用缓存优化数据请求

针对下拉框数据的请求可以做缓存处理，已请求过的数据可以缓存在内存或本地存储中，这样在重新请求数据时可以先从缓存中获取数据，减少请求接口的次数，提高性能。

参考文档：

- React.memo: https://reactjs.org/docs/react-api.html#reactmemo

**Comment by chenshuai2144** [comment]
因为是真的把组件销毁了，设计如此。

**Comment by arhebin** [comment]
> 因为是真的把组件销毁了，设计如此。

都卸载了memo 还有什么用
