### ISSUE TITLE
🧐[问题] pro-components站点经过如下操作嘎了，100%复现

### ISSUE THREAD

**Issue by decadez** [ant-design/pro-components#6930]
### 🚑 其他信息
![image](https://user-images.githubusercontent.com/49861866/231345500-f73fd231-73d9-42c3-a713-2cd92fce3956.png)
![image](https://user-images.githubusercontent.com/49861866/231344783-493351fd-1c37-4863-90ba-39585dd42243.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


很抱歉看不清楚您的问题是什么，可以再具体一点吗？例如，您是否遇到了某个具体的错误，或您对某个组件的使用感到困惑？请提供更多细节和上下文，以便我能够帮助您更好地解决问题。另外，如果这不是一个关于 React 前端问题的话，我就需要返回一个得体的拒绝了。

**Comment by chenshuai2144** [comment]
404 呀。清空下缓存再刷新。
应该是缓存和线上的问题没对上
