### ISSUE TITLE
🐛[BUG] columns中valueType='cascader'，表格数据展示错误

### ISSUE THREAD

**Issue by zoley** [ant-design/pro-components#6936]
### 📷 复现步骤 
[https://codesandbox.io/s/cha-xun-biao-ge-forked-lhgf84?file=/App.tsx:1171-1192](url)

![1681370239206.png](https://img.fy6b.com/2023/04/13/ff588a3d77790.png)

### 🏞 期望结果
表格栏显示应该同搜索栏一致

### © 版本信息
![1681370353731.png](https://img.fy6b.com/2023/04/13/f9a6ca3add63e.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据复现步骤，可以发现`valueType='cascader'`的列的数据展示不正确。这是因为在`render`函数中，将`text`和`record`的键值对解构出来直接返回，而`valueType='cascader'`时的`text`应该是一个`string`，而解构出来的`text`却是一个`array`，导致展示出错。

解决方案为：在`valueType='cascader'`时需要针对`text`的类型进行判断，如果是`array`，则需要使用`join()`方法将数组合并为一个字符串，才能正确展示。修改代码如下：

```tsx
render: (text: string | string[], record: TableListItem) => {
  if (Array.isArray(text)) { // 判断text是否为数组
    return text.join(' / ');
  }
  return text;
},
```

完整的修改后的代码如下：

```tsx
<Table
  columns={[
    // 省略其他列
    {
      title: '地区',
      dataIndex: 'area',
      valueType: 'cascader',
      render: (text: string | string[], record: TableListItem) => {
        if (Array.isArray(text)) { // 判断text是否为数组
          return text.join(' / ');
        }
        return text;
      },
    },
  ]}
  dataSource={dataSource}
/>
```

此外，还可以在文档中增加说明，`valueType`为`cascader`时的`text`类型为数组，并提供解决方案。可以在Ant Design官网中的Table的column配置项中的valueType属性文档中进行补充说明。

**Comment by zoley** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> 根据复现步骤，可以发现`valueType='cascader'`的列的数据展示不正确。这是因为在`render`函数中，将`text`和`record`的键值对解构出来直接返回，而`valueType='cascader'`时的`text`应该是一个`string`，而解构出来的`text`却是一个`array`，导致展示出错。
> 
> 解决方案为：在`valueType='cascader'`时需要针对`text`的类型进行判断，如果是`array`，则需要使用`join()`方法将数组合并为一个字符串，才能正确展示。修改代码如下：
> 
> ```tsx
> render: (text: string | string[], record: TableListItem) => {
>   if (Array.isArray(text)) { // 判断text是否为数组
>     return text.join(' / ');
>   }
>   return text;
> },
> ```
> 
> 完整的修改后的代码如下：
> 
> ```tsx
> <Table
>   columns={[
>     // 省略其他列
>     {
>       title: '地区',
>       dataIndex: 'area',
>       valueType: 'cascader',
>       render: (text: string | string[], record: TableListItem) => {
>         if (Array.isArray(text)) { // 判断text是否为数组
>           return text.join(' / ');
>         }
>         return text;
>       },
>     },
>   ]}
>   dataSource={dataSource}
> />
> ```
> 
> 此外，还可以在文档中增加说明，`valueType`为`cascader`时的`text`类型为数组，并提供解决方案。可以在Ant Design官网中的Table的column配置项中的valueType属性文档中进行补充说明。

![微信图片_20230508151544.png](https://img.fy6b.com/2023/05/08/690e44aab462e.png)
并没有起作用。
而且其中重要的不是对value进行数组转字符串格式化（/），而是获取到对应的label值。
另外 displayRender 属性对于表格列的渲染也是无效的

**Comment by chenshuai2144** [comment]
自定义render一下吧。
