### ISSUE TITLE
🐛[BUG] table 表头分组后的 setting 列显示选择有问题

### ISSUE THREAD

**Issue by qqqrr** [ant-design/pro-components#6937]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
 table 表头分组后的 setting 列显示选择有问题

### 🏞 期望结果
**点击 setting 的类型1 多选框，列表中 类型1的 children 字段隐藏，类型1多选框变为未选状态
实际：列表中 类型1的 children 字段隐藏，但类型1多选框还是选中状态，且不可在操作**

***总的来说就是表头分组的列显示多选框不起作用***

### 💻 复现代码
代码详情
 const columns1: ProColumns[] = [
    {
      key: 1,
      title: '类型1',
      children: [
        {
          title: 'id',
          dataIndex: 'id',
        },
        {
          title: 'id1',
          dataIndex: 'id1',
        },
      ],
    },
    {
      key: 2,
      title: '类型2',
      children: [
        {
          title: 'id2',
          dataIndex: 'id2',
        },
        {
          title: 'id3',
          dataIndex: 'id3',
        },
      ],
    },
  ];

<ProTable
        bordered 
        columns={columns1}
        dataSource={[
          {
            id: '000',
            id1: '111',
            id2: '222',
            id3: '333',
          }
        ]}
        rowKey={(record) => record.id}
      />

不会贴图

### © 版本信息

- ProTable 版本: [3.6.1]
- umi 版本 [3.5.35]
- 浏览器环境 [版本 112.0.5615.49（正式版本） (arm64)]
- 开发环境 [e.g. mac OS]

**Comment by qqqrr** [comment]
<img width="341" alt="截屏2023-04-13 15 17 24" src="https://user-images.githubusercontent.com/78259079/231687556-e0eaa83f-9802-4309-ab36-7054fc9b2df3.png">

**就是这样**

**Comment by qqqrr** [comment]
![Uploading 截屏2023-04-13 15.36.57.png…]()

就是这样

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢你的反馈，确实可能是由于 key 类型的问题导致的。使用 string 类型的 key 是一个更加规范的做法。如果还有其他问题，请随时提出。
