### ISSUE TITLE
🐛[BUG]BetaSchemaForm的formRef获取的ProFormInstance没有proform扩展的方法 ，formRef.current对象中没有getFieldsFormatValue方法

### ISSUE THREAD

**Issue by ty01** [ant-design/pro-components#6939]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

原本用的proForm1.7.x无此问题，由于valueType = group 折叠状态下组件销毁获取不到值，升级到2.10.1才出现的此问题

### 💻 复现代码
import { BetaSchemaForm } from '@ant-design/pro-form';
import { Input } from 'antd';
import React, { useRef } from 'react'

const valueEnum = {
    all: { text: '全部', status: 'Default' },
    open: {
        text: '未解决',
        status: 'Error',
    },
    closed: {
        text: '已解决',
        status: 'Success',
        disabled: true,
    },
    processing: {
        text: '解决中',
        status: 'Processing',
    },
};

const columns = [
    {
        title: "折叠父级",
        valueType: "group",

        fieldProps: {
            collapsible: true,
        },

        columns: [
            {
                title: '标题',
                dataIndex: 'title',
                initialValue: '必填',
                colProps: {
                    span: 24

                },
                formItemProps: {
                    rules: [
                        {
                            required: true,
                            message: '此项为必填项',
                        },
                    ],
                },
            },
            {
                title: '状态',
                dataIndex: 'state',
                valueType: 'select',
                valueEnum,
                tooltip: '当title为disabled时状态无法选择',
                dependencies: ['title'],
                fieldProps: (form) => {
                    if (form.getFieldValue('title') === 'disabled') {
                        return {
                            disabled: true,
                            placeholder: 'disabled',
                        };
                    } else {
                        return {
                            placeholder: 'normal',
                        };
                    }
                },
            },
            {
                title: '标签',
                dataIndex: 'labels',
                tooltip: '当title为必填时此项将为必填',
                dependencies: ['title'],
                formItemProps(form) {
                    if (form.getFieldValue('title') === '必填') {
                        return {
                            rules: [
                                {
                                    required: true,
                                },
                            ],
                        };
                    } else {
                        return {};
                    }
                },
            },
            {
                valueType: 'dependency',
                name: ['title'],
                columns: ({ title }) => {
                    return title !== 'hidden'
                        ? [
                            {
                                title: 'title为hidden时隐藏',
                                dataIndex: 'hidden',
                                valueType: 'date',
                                renderFormItem: () => {
                                    return <Input />;
                                },
                            },
                        ]
                        : [];
                },
            }
        ]
    },

    {
        title: '创建时间',
        key: 'showTime',
        dataIndex: 'createName',
        valueType: 'date',
    }

];

export default () => {

    const formRef = useRef()
    return <div style={{
        margin: "20px 300px"
    }}>
        <BetaSchemaForm
            formRef={formRef}
            shouldUpdate={false}
            layoutType="Form"
            onFinish={async (values) => {
 //此时formRef.current对象中没有getFieldsFormatValue方法
                console.log(formRef)

            }}
            columns={columns}
        />
    </div>

};

### © 版本信息

"@ant-design/pro-form": "^2.10.1",

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26292353/231758578-e6fea6b1-cc15-469a-a160-3a7d4d83e361.png)

**Comment by ldwonday** [comment]
BetaSchemaForm的formRef有bug

**Comment by ty01** [comment]
/* 
        为了解决BetaSchemaForm获取的实例没有proform的扩展信息，必须手动更新下才能获取到
    */
    const [_count, _setCount] = useState(0)
    useEffect(() => {
        if (!formRef.current || !formRef.current.getFieldsFormatValue) {
            setTimeout(() => {
                _setCount(v => v + 1)
            }, 100)
        }
    }, [_count])

临时解决此问题，等待官方回答

**Comment by ldwonday** [comment]
@ty01 试试按照我提的pr里的代码修改下你node_modules里的SchemaForm里的代码，然后看看是否解决了你的问题
