### ISSUE TITLE
🐛[BUG] Pro Table 组件，使用 token 进行背景色切换时仅会生效一次

### ISSUE THREAD

**Issue by Hellager** [ant-design/pro-components#6944]
### 🐛 bug 描述

使用 Configprovider 和 token 实现组件的背景色切换，但 pro table 切换后只会生效一次，如从默认模式切换至暗黑模式，当再切换回默认模式后切换暗黑模式将无效

### 📷 复现步骤

通过 pro table 顶部 switch 组件实现主题模式切换，发现对于 pro table，切换主题效果仅第一次生效

### 🏞 期望结果

切换主题效果应响应对应的主题设置

### 💻 复现代码

[pro-table-issue-template](https://github.com/Hellager/pro-table-issue-template)

### © 版本信息

- ProComponents 版本: "^2.4.4"
- umi 版本: 无
- 浏览器环境：Chrome 112.0.5615.87
- 开发环境 ：win11

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🌟 解决方案

这个问题的原因是因为 `ProTable` 组件在挂在时会计算表格的元素高度，当改变主题时元素高度没有发生变化，导致后续主题切换时没有重新计算高度，从而出现样式错乱的问题。

解决这个问题可以通过传入 `key` 属性来强制刷新组件。具体做法如下：

```tsx
import React, { useState } from 'react';
import { ConfigProvider, Switch } from 'antd';
import ProTable from '@ant-design/pro-table';

const columns = [
  { title: '标题', dataIndex: 'title' },
  { title: '描述', dataIndex: 'desc' },
];

const Demo: React.FC = () => {
  const [theme, setTheme] = useState('light');

  const tableKey = `pro-table-${theme}`; // 添加table key

  const toggleTheme = () => {
    const newTheme = theme === 'light' ? 'dark' : 'light';
    setTheme(newTheme);
  };

  return (
    <ConfigProvider prefixCls={`my-prefix-${theme}`}> {/* 自定义前缀，方便单独定位 */}
      <div>
        <Switch onChange={toggleTheme} />
        <ProTable
          style={{ marginTop: 16 }}
          key={tableKey} // 这里设置table key
          columns={columns}
          request={() => {
            return new Promise((resolve) => {
              resolve({
                data: [
                  { title: 'foo', desc: 'foo description' },
                  { title: 'bar', desc: 'bar description' },
                ],
              });
            });
          }}
          pagination={{ pageSize: 2 }}
          search={false}
          rowKey="title"
        />
      </div>
    </ConfigProvider>
  );
};

export default Demo;
```

通过将表格的 `key` 属性设置为 `${theme}` 来实时刷新表格组件。

### 📚 参考文档

- [ProTable GitHub Issue #858](https://github.com/ant-design/pro-components/issues/858)

**Comment by Hellager** [comment]
搞定了，谢谢！
