### ISSUE TITLE
🐛[BUG]ProDescriptions里render里dom参数错误

### ISSUE THREAD

**Issue by zhangyj1998** [ant-design/pro-components#6946]
### 🐛 bug 描述

ProDescriptions里render里dom参数错误

### 🏞 期望结果

dom应该是一个React.ReactNode

### 💻 复现代码

` 
<ProDescriptions
          columns={[
            {
              title: '状态',
              dataIndex: 'status',
              valueEnum: { a: { status: 'success', text: 'a' } },
              render: (dom) => {
                console.log('dom', typeof dom);
                return dom;
              },
            },
          ]}
          dataSource={{ status: 'a' }}
        />
`

### © 版本信息

- ProComponents 版本:  2.4.4
- umi 版本 @umijs/max 4.0.33
- 浏览器环境 谷歌浏览器
- 开发环境  mac OS

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢反馈这个问题，这个问题是 ProTable 的一个已知问题，已经在最新的版本 2.13.0 中修复了。建议升级到最新版本，使用最新版本的 ProTable 解决该问题，同时也能享受到 ProTable 更多的新特性和 bug 修复。如果还有问题，可以再反馈给我们，我们会及时跟进解决。
