### ISSUE TITLE
🐛[BUG]proTable只对二级表头进行筛选，不会触发request方法，必须存在一个一级表头有筛选配置，才会触发

### ISSUE THREAD

**Issue by zhou0322-lab** [ant-design/pro-components#6952]
### 💻 复现代码
[https://codesandbox.io/s/cha-xun-biao-ge-forked-8jqxrh?file=/App.tsx:842-3151](url)

**Comment by zhou0322-lab** [comment]
EditableProTable 是编辑表格不会触发

**Comment by zhou0322-lab** [comment]
`/** 如果所有列中的 filters=true| undefined 说明是用的是本地筛选 任何一列配置 filters=false，就能绕过这个判断 */`
  `const useLocaleFilter = useMemo(
    () =>
      columns?.every(
        (column) =>
          (column.filters === true && column.onFilter === true) ||
          (column.filters === undefined && column.onFilter === undefined),
      ),
    [columns],
  );`

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


是的，根据你提供的代码和描述，经过分析发现这段代码存在问题。在这段代码中，当所有的列都没有配置`filters`或者`onFilter`属性时，`useLocaleFilter`变量的值才会是`true`，即所有表格的筛选都是本地筛选。但是如果某一列配置了`filters=false`，就能绕过这个判断，导致出现了你描述的问题。

为了解决这个问题，建议修改这段代码，可以使用数组的every()方法和includes()方法来检测每个列的筛选是否是本地筛选，实现代码如下：

```javascript
const useLocaleFilter = useMemo(() => {
  // 判断每个列的筛选是否是本地筛选
  const isLocaleFilter = columns.every((col) => !col.filters || col.filters.length === 0 || !col.onFilter);

  // 判断每个一级表头的筛选是否是本地筛选
  const hasCustomConfig = columns.some((col) => col.title && !col.children);

  // 如果所有的列都没有配置 filters 或者 onFilter ，并且存在至少一个一级表头有配置筛选，则是用的是本地筛选
  return isLocaleFilter && hasCustomConfig;
}, [columns]);
```

上面代码中，我们首先判断每个列的筛选是否是表格的本地筛选，如果每个列的筛选都不是本地筛选，则判断一级表头是否存在配置筛选的情况，如果存在则说明表格的筛选是本地筛选，否则说明表格的筛选是远程筛选。这样就能解决在存在一级表头配置`filters=false`的情况下，依然触发请求的问题。

另外，如果你还想了解`every`和`some`方法的更多用法，可以查看它们的官方文档：[Array.prototype.every()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every)、[Array.prototype.some()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some)。

**Comment by chenshuai2144** [comment]
有兴趣直接来个pr吗？
