### ISSUE TITLE
🧐[问题] Please provide some way to access the inner DOM of a component.

### ISSUE THREAD

**Issue by jinseonghee** [ant-design/pro-components#6953]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
Please provide some way to access the inner DOM of a component.
I have tried to setting up Ant Design protable using Toolbar search form based filter light type.
And I am trying to convert to be my languages in button text.
I just want to replace text in button accessing to DOM element in Html
but it didn't work at all.

Here's my code.
I'm using react with typescript.

### 💻 示例代码

useEffect(() => {
	const btnElement  = document.getElementByClass(‘.site-btn.css-1vtf12y.site-btn-link.site-btn-sm’); 
	btnElement.innerText = ‘newText’;
},[])

### 🚑 其他信息

<img width="863" alt="image" src="https://user-images.githubusercontent.com/68724297/232512577-98cda4d4-2250-41d4-aa12-820524f19a9e.png">
<img width="863" alt="image" src="https://user-images.githubusercontent.com/68724297/232512667-7a4f8642-eb02-4c70-9c3a-be51e2a00e6d.png">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🤔 问题分析

根据用户的描述，他想要修改 Ant Design 的按钮中的文本内容，但是通过访问 DOM 元素后设置按钮的 `innerText` 却没有生效。我们可以分析问题：

1. 可能是获取 DOM 元素的方式不太正确，导致找到的是空元素。
2. 可能是组件更新后，DOM 元素被重新渲染，之前取到的引用已经失效了。

下面，我们来一步步解决这个问题。

### 🏋️‍♀️ 解决方案

#### 1. 确定获取 DOM 元素的方式

首先，我们需要确定获取 DOM 元素的方式是否正确。根据用户提供的代码和截图，我们可以知道想要修改的按钮是一个 Ant Design 的按钮。因此，我们可以想到可能是 Ant Design 组件的渲染方式导致了无法正确获取 DOM 元素。

解决这个问题的方法是，首先用浏览器的开发者工具检查一下这个按钮的 DOM 结构，确认一下代码中获取元素的方式是否正确。具体步骤如下：

1. 打开浏览器的开发者工具（如 Chrome 中按下 `F12`）。
2. 点击选中工具（如 Chrome 中在顶部工具栏中选择 “选择元素”）。
3. 选择 Ant Design 的按钮，查看对应的 DOM 结构。

根据用户提供的截图，我们发现这个按钮有一些类名，类似于 `site-btn css-1vtf12y site-btn-link site-btn-sm`。因此，我们可以尝试通过类名来获取这个按钮。但是需要注意的是，这个按钮同时有多个类名，我们需要使用多个类名的组合来准确定位到这个按钮。

替换代码如下：

```
useEffect(() => {
  const btnElement = document.querySelector(
    ".site-btn.css-1vtf12y.site-btn-link.site-btn-sm"
  );
  btnElement.innerText = "newText";
}, []);
```

#### 2. 确定修改按钮文本的时机

我们可以看到，用户的代码是写在 `useEffect` 中的，这意味着这个代码块只会在组件挂载（即初次渲染）时执行一次。但是按钮的文本内容可能会在组件的生命周期中被修改，例如用户进行了操作，或者组件的某个状态发生了变化。如果我们只在组件挂载时修改了 DOM 元素的文本内容，那么后续的修改都不会生效。

因此，我们需要在组件的生命周期中选择一个时机来更新按钮的文本内容。以此为例，我们可以在组件更新后，重新获取 DOM 元素的引用，然后再修改按钮的文本内容。

```
const DemoComponent = () => {
  const [counter, setCounter] = useState(0);

  useEffect(() => {
    const btnElement = document.querySelector(
      ".site-btn.css-1vtf12y.site-btn-link.site-btn-sm"
    );
    btnElement.innerText = "newText";
  }, []);

  useEffect(() => {
    const btnElement = document.querySelector(
      ".site-btn.css-1vtf12y.site-btn-link.site-btn-sm"
    );
    btnElement.innerText = `Counter: ${counter}`;
  }, [counter]);

  return (
    <div>
      <button onClick={() => setCounter(counter + 1)}>Count</button>
      <br />
      <button className="site-btn css-1vtf12y site-btn-link site-btn-sm">
        Original Text
      </button>
    </div>
  );
};
```

在这个例子中，我们定义了一个计数器 `counter`，然后在每次更新组件时，用计数器的值来修改按钮的文本内容。如果你希望在其他状态更新时修改按钮的文本内容，也可以将 `counter` 改成其他状态即可。

### 📚 相关文档

1. [React 组件的生命周期](https://react.docschina.org/docs/state-and-lifecycle/)
2. [querySelector()](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector)
