### ISSUE TITLE
🐛[BUG] ProFormSwitch点击label 也会触发点击事件

### ISSUE THREAD

**Issue by cangsnage** [ant-design/pro-components#6956]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，您的问题并没有与 React 的前端相关。请您提供与 React 前段相关的问题，方便我们为您提供更好的帮助。如果您有 React 的前端问题，请继续提供详细的描述以及可复现的代码，我们会尽力提供解决方案。同时，提供文档也是非常有用的，让我们更好地理解您的问题并为您提供帮助。

**Comment by chenshuai2144** [comment]
https://developer.mozilla.org/en-US/docs/web/html/element/label

html的设计
