### ISSUE TITLE
使用protable的renderFormItem自定义表单选项时，搜索栏的选项不应该显示*（必选） 🐛[BUG]

### ISSUE THREAD

**Issue by kate2014** [ant-design/pro-components#696]
### 🐛 bug 描述

使用protable的renderFormItem自定义表单选项时，搜索栏的选项不应该显示*（如果该Field的rules设置了required必选）

默认的ProformField设置了rules属性为：rules={type === 'form' ? rest.rules : undefined}

而当用户使用rederFormItem时，没有设置rules，设置rules={type === 'form' ? rest.rules : undefined} 即可。

 // 已用户的为主，不然过于 magic
    return (
      <ProFormField
        key={`${item.dataIndex || ''}-${item.key || ''}-${item.index}`}
        {...rest}
        ref={ref}
        initialValue={item.initialValue}
        name={item.key || item.dataIndex}
        _**rules={type === 'form' ? rest.rules : undefined}**_
      >
        {React.cloneElement(dom, { ...rest, ...defaultProps })}
      </ProFormField>
    );

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by BarronLin** [comment]
### 遇到同样问题

`    {
      title: '所属部门',
      dataIndex: 'hrDeptId',
      width: 140,
      formItemProps: {
        rules: [
          {
            required: true,
          },
        ],
      },
      renderFormItem: () => {
        return <DeptSelect />;
      },
    }`

然后搜索栏就出现了红：
![image](https://user-images.githubusercontent.com/9267731/99255396-d4578e00-284e-11eb-8b5c-394c2a6a0b5e.png)

**Comment by chenshuai2144** [comment]
@BarronLin  有兴趣来个 pr 吗？

**Comment by chenshuai2144** [comment]
fixed
