### ISSUE TITLE
🧐[问题]EditableProTable或者ProTable自定义编辑的时候，无论时renderFormitem返回InputNumber控件还是valueType:'digit'，只要rules填写了max

### ISSUE THREAD

**Issue by jyforward** [ant-design/pro-components#6960]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 💻 示例代码
formItemProps: {
        rules: [
          {
            max: 999,
            message: "领用数量输入值仅可大于0且 小于等于当前库存",
          },
        ],
      },
      renderFormItem(_, { record }) {
        return <InputNumber placeholder="请输入" />;
      }

### 🚑 其他信息
![Snipaste_2023-04-18_17-04-33](https://user-images.githubusercontent.com/72787501/232732459-4b3956dd-b25f-4339-b43b-91e13061441c.jpg)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，请问有什么问题可以帮助你解决吗？我看到你之前发了一个关于 EditableProTable 和 ProTable 的问题。

**Comment by nwangwei** [comment]
{
max: 999,
message: "领用数量输入值仅可大于0且 小于等于当前库存",
},

=====>

{
**type: 'number',**
max: 999,
message: "领用数量输入值仅可大于0且 小于等于当前库存",
},
