### ISSUE TITLE
🧐[问题]在EditableProTable中使用实时保存功能，但是无法获取renderFormItem自定义编辑组件的value值

### ISSUE THREAD

**Issue by Sakuraxo** [ant-design/pro-components#6961]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
columns中图片一列用的renderFormItem封装了一个组件，其他列采用valueType能正常获取。（用onSave能正常获取，但是为什么用onValuesChange就获取不了？）

### 💻 示例代码
![1](https://user-images.githubusercontent.com/47910711/232761613-283ae65c-cf69-4776-8c64-9dc97b4ab6bb.png)
![2](https://user-images.githubusercontent.com/47910711/232761626-88898be9-58c6-48d7-9405-0526fce26a6d.png)
![3](https://user-images.githubusercontent.com/47910711/232761637-bc21c38c-d398-4c93-a698-2e2000c40e01.png)
![4](https://user-images.githubusercontent.com/47910711/232761946-bedd75e6-7232-4ff1-88de-3a1bdc655ce5.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据您提供的信息，很难得出一个可以直接工作的代码解决方案。但是我可以提供一些思路，以帮助您诊断问题：

1. 从React组件的生命周期入手，检查render函数是否正确返回您的自定义组件，并使用canRowBeEdited props来检查行是否处于编辑状态。

2. 您可以尝试添加console.log语句和使用React的dev工具来检查组件的渲染和状态是否正确更新。 

3. 您也可以检查对 renderFormItem 组件的 value 的处理，这包括使用哪个 state，并在 componentWillUnmount 钩子函数中进行清理（如果您使用了）。

这里有几份可供参考的文档和示例：

- EditableProTable 官方文档：https://procomponents.ant.design/components/table/#EditableProTable

- Rendering Custom Forms in Editable Cell: https://ant.design/components/table-cn/#components-table-demo-edit-row

- 如何在 React 中使用 renderProps 获取子组件的值：https://medium.com/@navinmozhi/how-to-get-the-value-of-a-child-component-in-react-using-renderprops-8f7b1c4b4f92 。

- a modified version of EditableCell component provided in [editable-table](https://github.com/ant-design/ant-design/edit/master/components/table/demo/edit-row.tsx)

希望这些资料和提供的思路对您有所帮助，如果您仍然遇到困难，请随时更新您的问题。
