### ISSUE TITLE
🧐[问题] ProLayout 如何设置整个项目的颜色

### ISSUE THREAD

**Issue by zFitness** [ant-design/pro-components#6963]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
ProLayout 如何设置整个项目的颜色

目前我的方法如下：
```
// app.tsx
export const layout: RunTimeLayoutConfig = ({ initialState }) => {
     return {
       childrenRender(dom) {
          return <Layout>{dom}</Layout>;
      },
    }
}

// Layout.tsx  
const Layout = ({ children }) => {
  useEffect(() => {
    return () => {
      xxx
    };
  }, []);
  return <ConfigProvider theme={baseTheme}>{children}</ConfigProvider>;
};

```
存在的问题，设置的样式只能在 layout 页面下才能使用，如果在登录/注册页面无法设置全局的 antd 样式。

### 🚑 其他信息
umi: 4
antd: 5
ant-pro: 6

**Comment by Teeoo** [comment]
你`登录/注册`路由在`Layout `下么？没有的话你需要在你`登录/注册`页加上`ConfigProvider `

**Comment by zFitness** [comment]
> 你`登录/注册`路由在`Layout `下么？没有的话你需要在你`登录/注册`页加上`ConfigProvider ` [定制主题 ](https://ant.design/docs/react/customize-theme-cn)
我其实想能不能给Layout包一层

**Comment by Teeoo** [comment]
Layout包了也没用啊，除非你路由在这下边

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


如果你想要在整个项目中应用同一种样式，那么可以考虑在`app.tsx`中使用`ConfigProvider`来设置主题色和其他样式。

以下是一个示例代码，你可以参考一下：

```jsx
import { ConfigProvider } from 'antd';
import zhCN from 'antd/es/locale/zh_CN';
import 'moment/locale/zh-cn';

const MyApp = ({ Component, pageProps }) => {
  return (
    <ConfigProvider locale={zhCN}>
      <Component {...pageProps} />
    </ConfigProvider>
  );
};

export default MyApp;
```

在这里，我们引入了`antd`的本地化组件`zh_CN`，并用`ConfigProvider`将`Component`包裹起来。

对于具体的样式设置，你可以参考`antd`的定制主题来进行设定，例如：

```jsx
import { ConfigProvider } from 'antd';
import zhCN from 'antd/es/locale/zh_CN';
import 'moment/locale/zh-cn';
import { createFromIconfontCN } from '@ant-design/icons';

const MyIcon = createFromIconfontCN({
  scriptUrl: '//at.alicdn.com/t/font_1234567_aaaaaaa.js',
});

const theme = {
  'primary-color': '#1890ff',
  'link-color': '#1890ff',
  'border-radius-base': '2px',
};

const MyApp = ({ Component, pageProps }) => {
  return (
    <ConfigProvider theme={theme} locale={zhCN}>
      <MyIcon type="icon-demo" />
      <Component {...pageProps} />
    </ConfigProvider>
  );
};

export default MyApp;
```

在这里，我们首先将`ICONS_URL`替换成你的阿里云图标库的地址，并使用`createIconFromFontCN`创建了一个自定义图标组件`MyIcon`。同时，在`ConfigProvider`中使用了一个对象`theme`，用于设置主题色、边框圆角等样式。

**Comment by zFitness** [comment]
解决了，直接用 app.tsx 的一个函数就行：

```
// 重置主题
export function rootContainer(container: any) {
  return React.createElement(ConfigProvider, { theme: baseTheme }, container);
}

```
