### ISSUE TITLE
🐛[BUG] Protable一直未解决的渲染三次问题，对性能影响极大

### ISSUE THREAD

**Issue by gaoobin** [ant-design/pro-components#6964]
版本发布太频繁，完全没必要，少发点版，稳定才是正道
之前用Protable 2.30.8使用丝滑。
现在真心不知道能用哪个版本？

**Comment by gaoobin** [comment]
说早了。发现确实是三次渲染导致的性能问题，还在找解决方案

**Comment by gaoobin** [comment]
**大家谁有解决方案，尝试好久不知道怎么解决，三次渲染如下：
1、Protable onchange，第一次渲染；
2、pagination onchange，渲染第二次；
3、数据更新，第三次渲染。
如何禁止前两次渲染？**

**Comment by gaoobin** [comment]
**这个问题很重要，因为会对性能影响很大。但是却好像是一直没有解决。
最终通过React.memo解决了，但是这个就先不关了，因为是个重要问题，希望后面ProTable和EditableProTable两个组件能解决这个问题**

**Comment by rickythink** [comment]
有没有可以复现的 demo 看看？

**Comment by gaoobin** [comment]
> 

你直接复制Protable下的示例d，都有这个问题。在任意一列的渲染中打印日志，onchange、pagination.onchange、request都打印日志看的很清楚

**Comment by gaoobin** [comment]
> 有没有可以复现的 demo 看看？

你直接复制Protable下的示例d，都有这个问题。在任意一列的渲染中打印日志，onchange、pagination.onchange、request都打印日志看的很清楚
我原来以为老版本是好的，打印日志看后发现都有问题

**Comment by WuJiY** [comment]
![image](https://user-images.githubusercontent.com/183884/234175827-dbd942b8-5770-4694-8ed5-6ed2b1902974.png)
我在 tableAlertRender 里console.log一下

**Comment by XinYueXiao** [comment]
尝试解决了以下渲染的问题
https://juejin.cn/post/7276257954297479220
