### ISSUE TITLE
🐛[BUG] ProTable 中 编辑表格 的 valueEnum 数据渲染问题

### ISSUE THREAD

**Issue by yinsel** [ant-design/pro-components#6969]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
在ProTable表格中原本未编辑”用户角色“的数据渲染为”管理员“，点击编辑后输入框的显示初始值却为1。其中”用户角色”在数据传递过程用数值类型的0与1来表示。

### 📷 复现步骤
在表格中用 valueEnum 来渲染 数值类型 0 和 1 表示 的 “普通用户” 和 “管理员” 的文本，点击编辑后会出现输入框初始值渲染不正确。在这之后，我用抓包工具将下面的JSON数据中userRole: 1 拦截并更改为 userRole: "1", 点击编辑后输入框初始值正常渲染。

下面是我的表格页面代码和表格数据传递的JSON数据：

`declare namespace API {
  type CurrentUser = {
    id: string,
    username: string,
    userAccount: string,
    avatarUrl?: string,
    gender: number,
    phone: string,
    email: string,
    userStatus:number,
    userRole: number,
    planetCode: string,
    createTime: Date,
    updateTime: Date,
    }
}`

`import type {ActionType, ProColumns} from '@ant-design/pro-components';
import { ProTable, TableDropdown } from '@ant-design/pro-components';
import { useRef } from 'react';
import {modify, remove, searchUsers} from "@/services/ant-design-pro/api";
import {Image, message} from "antd";
export const waitTimePromise = async (time: number = 100) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(true);
    }, time);
  });
};

export const waitTime = async (time: number = 100) => {
  await waitTimePromise(time);
};

const columns: ProColumns<API.CurrentUser>[] = [
  {
    dataIndex: 'index',
    valueType: 'indexBorder',
    width: 48,
  },
  {
    title: '用户名',
    dataIndex: 'username',
    copyable: true,
  },
  {
    title: '用户账户',
    dataIndex: 'userAccount',
    copyable: true,
  },
  {
    title: '性别',
    dataIndex: 'gender',
    valueEnum: {
      0: {text: "男"},
      1: {text: "女"}
    },
  },
  {
    title: '手机号',
    dataIndex: 'phone',
    copyable: true,
  },
  {
    title: '邮箱',
    dataIndex: 'email',
    copyable: true,
  },
  {
    title: '状态',
    dataIndex: 'userStatus',
    valueEnum: {
      0: {text: "正常", status: "Success"},
      1: {text: "封号", status: "Error"}
    },
    valueType: "text"
  },
  {
    title: '星球编号',
    dataIndex: 'planetCode',
  },
  {
    disable: true,
    filters: true,
    onFilter: true,
    ellipsis: true,
    title: '用户角色',
    dataIndex: 'userRole',
    valueType: "select",
    valueEnum: {
      0: {text: "普通用户", status: "Default"},
      1: {text: "管理员", status: "Success"}
    },
  },
  {
    title: '创建时间',
    dataIndex: 'createTime',
    valueType: "dateTime"
  },
  {
    title: '操作',
    valueType: 'option',
    key: 'option',
    render: (text, record, _, action) => [
      <a
        key="editable"
        onClick={() => {
          action?.startEditable?.(record.id);
        }}
      >
        编辑
      </a>,
      <a href={record.url} target="_blank" rel="noopener noreferrer" key="view">
        查看
      </a>,
      <TableDropdown
        key="actionGroup"
        onSelect={() => action?.reload()}
        menus={[
          { key: 'delete', name: '删除',onClick: async (info) => {
              await remove(record.id).then(function (result) {
                if (result) {
                  message.success("删除成功")
                }
              })
            } },
        ]}
      />,
    ],
  },
];
export default () => {
  const actionRef = useRef<ActionType>();
  return (
    <ProTable<API.CurrentUser>
      columns={columns}
      actionRef={actionRef}
      cardBordered
      request={async (params = {}, sort, filter) => {
        console.log(sort, filter);
        await waitTime(500);
        const userList = await searchUsers()
        return {
          data: userList
        }
      }}
      editable={{
        type: 'multiple',
        onSave: async (key,user) => {
          await modify(user).then((result) => {

            if (result) {
              message.success("保存成功")
            }
          })
        },
        onChange: () => {

        }
      }}
      columnsState={{
        persistenceKey: 'pro-table-singe-demos',
        persistenceType: 'localStorage',
        onChange(value) {
          console.log('value: ', value);
        },
      }}
      rowKey="id"
      search={{
        labelWidth: 'auto',
      }}
      options={{
        setting: {
          listsHeight: 400,
        },
      }}
      form={{
        // 由于配置了 transform，提交的参与与定义的不同这里需要转化一下
        syncToUrl: (values, type) => {
          if (type === 'get') {
            return {
              ...values,
              created_at: [values.startTime, values.endTime],
            };
          }
          return values;
        },

      }}
      pagination={{
        pageSize: 5,
        onChange: (page) => console.log(page),
      }}
      dateFormatter="string"
      headerTitle="高级表格"/>
  );
};
`

`{
	"code": 0,
	"data": [{
		"id": 1,
		"username": null,
		"userAccount": "admin",
		"userPassword": null,
		"avatarUrl": "https://yupi.icu/logo.png",
		"gender": 0,
		"phone": "",
		"email": "",
		"userStatus": 0,
		"createTime": "2023-04-23T08:09:53.000+00:00",
		"updateTime": "2023-04-23T11:28:03.000+00:00",
		"isDelete": null,
		"userRole": 1,
		"planetCode": "1"
	}],
	"message": "ok",
	"description": ""
}`

### © 版本信息

- ProComponents 版本: 1.1.1
- umi 版本 3.5.0
- 浏览器环境 Microsoft Edge
- 开发环境 [e.g. mac OS] windows 11

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据描述分析，可能是 ProTable 中 `valueType` 为 `select` 的 `valueEnum` 数据渲染的问题，建议检查代码中是否有以下情况：

1. `valueEnum` 中将 `value` 转为数字类型，导致渲染时出现问题；
2. `valueType` 为 `select` 时，在编辑时只能接收字符串类型的值，但原始数据为数字类型。

针对第一点问题，可以尝试将 `valueEnum` 中的值改为字符串类型，如将 `0` 改为 `"0"`。

针对第二点问题，可以尝试对编辑时的数据进行转型，将数字类型的值转为字符串类型，如下所示：

```tsx
{
  title: '用户角色',
  dataIndex: 'userRole',
  valueType: 'select',
  editable: true,
  renderFormItem: (item, { type, defaultRender, ...rest }, form) => {
    return (
      <Input
        {...rest}
        value={form.getFieldValue(item.dataIndex)?.toString()}
        onChange={(e) => {
          form.setFieldsValue({ [item.dataIndex]: e.target.value });
        }}
      />
    );
  },
  valueEnum: {
    0: { text: '普通用户', status: 'Default' },
    1: { text: '管理员', status: 'Success' },
  },
},
```

此外，可以参考官方文档，了解如何正确使用 `valueType` 和 `valueEnum` 属性：

- `valueType`：https://procomponents.ant.design/components/table#valueformat
- `valueEnum`：https://procomponents.ant.design/components/table#valueenum

**Comment by yinsel** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。↳
> 
> 根据描述分析，可能是 ProTable 中 `valueType` 为 `select` 的 `valueEnum` 数据渲染的问题，建议检查代码中是否有以下情况：
> 
> 1. `valueEnum` 中将 `value` 转为数字类型，导致渲染时出现问题；
> 2. `valueType` 为 `select` 时，在编辑时只能接收字符串类型的值，但原始数据为数字类型。
> 
> 针对第一点问题，可以尝试将 `valueEnum` 中的值改为字符串类型，如将 `0` 改为 `"0"`。
> 
> 针对第二点问题，可以尝试对编辑时的数据进行转型，将数字类型的值转为字符串类型，如下所示：
> 
> ```tsx
> {
>   title: '用户角色',
>   dataIndex: 'userRole',
>   valueType: 'select',
>   editable: true,
>   renderFormItem: (item, { type, defaultRender, ...rest }, form) => {
>     return (
>       <Input
>         {...rest}
>         value={form.getFieldValue(item.dataIndex)?.toString()}
>         onChange={(e) => {
>           form.setFieldsValue({ [item.dataIndex]: e.target.value });
>         }}
>       />
>     );
>   },
>   valueEnum: {
>     0: { text: '普通用户', status: 'Default' },
>     1: { text: '管理员', status: 'Success' },
>   },
> },
> ```
> 
> 此外，可以参考官方文档，了解如何正确使用 `valueType` 和 `valueEnum` 属性：
> 
> * `valueType`：https://procomponents.ant.design/components/table#valueformat
> * `valueEnum`：https://procomponents.ant.design/components/table#valueenum

感谢回复。经过测试上述问题与valueType的类型无关，例如我之前给出的例子的展示“状态”一列valueType的值为“text”,依旧渲染不正确，并且只是初始值渲染不正确，当鼠标尝试点击valueType为select的输入框时，发现下拉展示的数据渲染是正确的。之后我用了renderFormItem 尝试转为字符串，测试之后发现其中onChange方法是在尝试修改输入框的值后才会触发，也就是无法对点击编辑后的初始值进行转换并赋值，暂时只能通过修改后端数据类型为string来解决问题，但大多数时候一些数据还是需要用数值类型与前端交互，目前还需进一步分析该问题的原因及解决方案。

**Comment by chenshuai2144** [comment]
object 是不支持 number，如果要用 number 需要使用 map 这个数据结构

**Comment by xyovo** [comment]
> 

OK，这对我有用~ 谢谢
