### ISSUE TITLE
🐛[BUG]process is not defined

### ISSUE THREAD

**Issue by rzyanhao** [ant-design/pro-components#6973]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

https://github.com/ant-design/pro-components/commit/1de7341e954ffff3426bc156dc2dc2eefa8b8a4e
这次提交的改动，对process使用了链式操作符
![image](https://user-images.githubusercontent.com/9431954/234218625-3c263ba4-5b74-432f-ae0a-10944764a23b.png)
编译后为
![image](https://user-images.githubusercontent.com/9431954/234218775-a2a62bee-44f5-4473-8f41-d03a7041f382.png)

此时process是未定义的，严格模式下直接访问会报错，而原先先通过typeof判断的方式是可以的

### 📷 复现步骤
见bug描述

### 🏞 期望结果

revert掉链式操作符的判断，或者换种写法

### © 版本信息

@ant-design/pro-provider   2.8.0版本

**Comment by fengzehao** [comment]
+1

**Comment by youzaiyouzai666** [comment]
+1

**Comment by zhuyankun** [comment]
+1

**Comment by youzaiyouzai666** [comment]
+1

**Comment by kaplax** [comment]
看 npm 上 publish 了好几个版本，怎么全有问题

**Comment by chenshuai2144** [comment]
你们用的是什么框架呀，为什么没有 process

**Comment by chenshuai2144** [comment]
> 看 npm 上 publish 了好几个版本，怎么全有问题

npm 今天抽风，发版本成功不了

**Comment by fengzehao** [comment]
> 你们用的是什么框架呀，为什么没有 process

create-react-app 5.0.1
另外，问题依然存在
![image](https://user-images.githubusercontent.com/23555315/234438392-9f0bcc27-fd50-4c1a-a13e-87d55f091e48.png)

**Comment by AnLiBoBo** [comment]
为什么历史版本也会收到影响, 目前用的是2.4.3

**Comment by kaplax** [comment]
@chenshuai2144 https://github.com/ant-design/pro-components/commit/0d9cba1a7fe74a87c6daf93a36f768801059f42d 啥时候合呢， 线上等着发版

**Comment by chenshuai2144** [comment]
已经发布啦

**Comment by AnLiBoBo** [comment]
> 已经发布啦

但是2.4.8的版本还是会有这个错啊

**Comment by chenshuai2144** [comment]
报错贴一下

**Comment by chuangwei** [comment]
![image](https://user-images.githubusercontent.com/5902016/234492538-8bcc5150-692b-4d67-8b87-07fdc9aa2215.png)
![image](https://user-images.githubusercontent.com/5902016/234492652-f6fd43d4-874a-4e08-80e7-853350a21fc8.png)

**Comment by chuangwei** [comment]
还是 process出问题

**Comment by kaplax** [comment]
@chenshuai2144 
npm 上看产物问题依旧没有解决 https://www.npmjs.com/package/@ant-design/pro-provider?activeTab=code
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/25189091/234496197-ce603c79-2e3e-492a-b568-059dec3c9833.png">

**Comment by Carl0608** [comment]
为什么关了啊！ 我在新版本遇到了同样的问题
<img width="262" alt="Snipaste_2023-04-28_17-05-35" src="https://user-images.githubusercontent.com/52045291/235105643-e7eb1771-ec48-47fc-a600-81674021196a.png">
<img width="787" alt="Snipaste_2023-04-28_17-06-19" src="https://user-images.githubusercontent.com/52045291/235105710-b378537b-01e7-4ff7-8706-b5b53fae9eb4.png">
<img width="643" alt="Snipaste_2023-04-28_17-05-59" src="https://user-images.githubusercontent.com/52045291/235105749-8debceac-a767-4038-8797-bb8228541995.png">

**Comment by Adherentman** [comment]
```
"vite" 4.3.1,
"@ant-design/pro-components": "^2.4.4",
"@ant-design/pro-form": "^2.10.1",
"@ant-design/pro-table": "^3.6.1",
"antd": "^5.4.5",
```
依然有以上报错process is not defined

**Comment by gujiwuqing** [comment]
> ```
> "vite" 4.3.1,
> "@ant-design/pro-components": "^2.4.4",
> "@ant-design/pro-form": "^2.10.1",
> "@ant-design/pro-table": "^3.6.1",
> "antd": "^5.4.5",
> ```
> 
> 依然有以上报错process is not defined
一样报错

**Comment by zhuyankun** [comment]
index.html中添加全局变量解决
    <script>
      var process = process || {env: {}}
    </script>
