### ISSUE TITLE
🐛[BUG]ProTable 列设置中存在层级关系时，子级列取消选中，父级列还是会显示在table中

### ISSUE THREAD

**Issue by zhou0322-lab** [ant-design/pro-components#6975]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

]ProTable 列设置中存在层级关系时，子级列取消选中，父级列还是会显示在table中

### 📷 复现步骤
<img width="842" alt="image" src="https://user-images.githubusercontent.com/24800947/234507068-82f6f809-624d-4458-834c-58e41331abb7.png">
应该是这段选中代码没有处理子级全部未选中，父级的状态也应该改变
<img width="726" alt="image" src="https://user-images.githubusercontent.com/24800947/234508415-e9a3147a-76b1-4411-997f-38d230154b6b.png">

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by zhou0322-lab** [comment]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/24800947/234506657-4d2135ef-12ba-4ec5-ba8f-ecd17b0acd7d.png">

**Comment by chenshuai2144** [comment]
有兴趣来个pr嘛？

**Comment by niuniuaikeji** [comment]
遇到同样的问题，有被修复吗？还有另外一个问题：选中子列，父列不选中，子列不能在页面Table中渲染出来

Has the same problem been fixed? There is another issue: if the child column is selected and the parent column is not selected, the child column cannot be rendered in the page table
