### ISSUE TITLE
最新的pro-components2.4.8导致菜单栏变形左边多出180px的空格🐛[BUG]

### ISSUE THREAD

**Issue by zhengmenghuang** [ant-design/pro-components#6978]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

🐛 bug 描述
升级到最新的 pro-components 组件到2.4.8后导航菜单样式变形

📷 复现步骤
无

🏞 期望结果
菜单正常

💻 复现代码
"dependencies": {
"@ant-design/icons": "^5.0.1",
"@ant-design/pro-components": "^2.4.8",
"@umijs/max": "^4.0.66",
"ahooks": "^3.7.6",
"antd": "5.4.5",
"crypto-js": "^4.1.1",
"react-draggable": "^4.4.5"
},
"devDependencies": {
"@types/crypto-js": "^4.1.1",
"@types/lodash": "^4.14.194",
"@types/react": "^18.2.0",
"@types/react-dom": "^18.2.1",
"cross-env": "^7.0.3",
"eslint-plugin-unused-imports": "^2.0.0",
"husky": "^8.0.3",
"lint-staged": "^13.2.1",
"prettier": "^2.8.8",
"prettier-plugin-organize-imports": "^3",
"prettier-plugin-packagejson": "^2",
"typescript": "^4.9.5"
}

© 版本信息
ProComponents 版本: 2.4.8
umi 4.0.66
浏览器环境 Google Chrome 版本 112.0.5615.138（正式版本） （64 位）
开发环境 windows
🚑 其他信息
不正常
![image](https://user-images.githubusercontent.com/29627098/234465234-c59b0da6-20ae-4abf-8894-fa65983daf66.png)

正常
![image](https://user-images.githubusercontent.com/29627098/234465246-2cf401ef-acc4-4d60-90fe-28e4ac0239f1.png)

**Comment by zhengmenghuang** [comment]
.ant-layout-has-sider {
  & > div:first-child {
    display: none !important;
  }
}
先把用不到的隐藏

**Comment by Cacivy** [comment]
这应该是antd的问题，https://github.com/ant-design/ant-design/pull/41993
解决方案：
```
.baisc-layout-prefix-layout .baisc-layout-prefix-sider-fixed {
      position: fixed !important;
    }
···

**Comment by hihuangwei** [comment]
> 这应该是antd的问题，[ant-design/ant-design#41993](https://github.com/ant-design/ant-design/pull/41993)

更新了  还是存在问题

**Comment by hrjoyce1990** [comment]
同样问题，antd5.4.6没问题，pro回滚到2.4.4就好了

**Comment by chenshuai2144** [comment]
再更新一下呢，我看到没问题了

**Comment by hihuangwei** [comment]
> 再更新一下呢，我看到没问题了

"@ant-design/pro-components": "^2.4.9", 还是存在问题，

**Comment by zhengmenghuang** [comment]
1. 更新依赖如下
![image](https://user-images.githubusercontent.com/29627098/234739230-969472f3-6254-470e-8d1e-f57babbd5595.png)

2. 删除 package-lock.json
3. 删除 node_modules

问题还在

**Comment by liyupengsGit** [comment]
> 1. 更新依赖如下
>    ![image](https://user-images.githubusercontent.com/29627098/234739230-969472f3-6254-470e-8d1e-f57babbd5595.png)
> 2. 删除 package-lock.json
> 3. 删除 node_modules
> 
> 问题还在

2.4.9的问题，我也出现了，要么等更新，要么自己写css。 类选择器的优先级大于where优先级导致的

**Comment by hihuangwei** [comment]
@chenshuai2144 混合菜单布局 还是存在问题

**Comment by luoyepiaoling123** [comment]
> @chenshuai2144 混合菜单布局 还是存在问题

为什么要发布一个有问题的版本

**Comment by luoyepiaoling123** [comment]
希望作者看到后及时修复更新下

**Comment by hyzx86** [comment]
把三角扒了试试
"@ant-design/pro-components": "2.4.9",

**Comment by hyzx86** [comment]
晕 。。扒了也不行。。
确实是 2.4.9了
![image](https://user-images.githubusercontent.com/15613121/235083199-3dd9881c-828f-4ad0-bd52-73ce761a3f4e.png)

https://github.com/ant-design/ant-design-pro/issues/10706

**Comment by hyzx86** [comment]
> > @chenshuai2144 混合菜单布局 还是存在问题
> 
> 为什么要发布一个有问题的版本

@luoyepiaoling123 
都白嫖了 ，别这么理直气壮好不好。。人家不欠你的

**Comment by q1uxu** [comment]
> > > @chenshuai2144 混合菜单布局 还是存在问题
> > 
> > 
> > 为什么要发布一个有问题的版本
> 
> @luoyepiaoling123 都白嫖了 ，别这么理直气壮好不好。。人家不欠你的

开源的东西，人人都可以用，这算什么白嫖？怕别人白嫖开源出来的东西，那就别开源。再说就算别人白嫖了，维护者就能发布出来没经过测试的有问题的版本吗？这算什么理由？

**Comment by q1uxu** [comment]
我升级到最新的版本，修复好了

**Comment by zhengmenghuang** [comment]
2.4.12 已经好了
