### ISSUE TITLE
🧐[问题]pro-provider中报process未定义的错误解决了吗

### ISSUE THREAD

**Issue by yangyuanchao-tal** [ant-design/pro-components#6979]
昨天有大佬提过这个issue，目前还是报错
node版本：v16.20.0
npm版本：8.19.4
pro-components版本：2.4.4
描述：
<img width="957" alt="image" src="https://user-images.githubusercontent.com/129848566/234493783-8683a801-0384-468d-85a5-3f4984e702c5.png">
![image](https://user-images.githubusercontent.com/129848566/234494013-310b208f-dd75-45e9-98db-458f61ba9609.png)

**Comment by yangyuanchao-tal** [comment]
pro-provider版本：2.8.2

**Comment by NNNaix** [comment]
@chenshuai2144 
问题出在 https://github.com/ant-design/pro-components/blob/0d9cba1a7fe74a87c6daf93a36f768801059f42d/packages/provider/src/index.tsx#L272
这里也用 typeof process !== 'undefined' && process.env.NODE_ENV?. toLowerCase() != 'test' 来判断就可以了

**Comment by Lucien-X** [comment]
> ## 临时修复方案
> ### vite
> ```tsx
> // vite config
> 
> define: {
>   'process.env': '{}', 
> },
> ```
> 
> #### webpack
> ```tsx
> // webpack config
> 
> plugins: [
>   new DefinePlugin({
>     'process': { env: { NODE_ENV: JSON.stringify('production') } },
>   })
> ],
> ```

vite 3.x 在生产构建下不生效

**Comment by chenshuai2144** [comment]
楼主好人，我加个测试用例

**Comment by jiialinn** [comment]
> 楼主好人，我加个测试用例

还是报错啊哥，构建产物有问题，源码看着是加了链式，但是产物还是没有判断undefined

**Comment by yangyuanchao-tal** [comment]
@chenshuai2144 哥npm包上还是没有判断undefined啊，你们没有重新构建npm包啊

**Comment by labLuLu** [comment]
> 2.4 的版本 均有问题

**Comment by kaplax** [comment]
俩个 issue 都是还没完全解决就 close 了 https://github.com/ant-design/pro-components/issues/6973

**Comment by NNNaix** [comment]
> > ## 临时修复方案
> > ### vite
> > ```tsx
> > // vite config
> > 
> > define: {
> >   'process.env': '{}', 
> > },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### webpack
> > ```tsx
> > // webpack config
> > 
> > plugins: [
> >   new DefinePlugin({
> >     'process': { env: { NODE_ENV: JSON.stringify('production') } },
> >   })
> > ],
> > ```
> 
> vite 4.x 在生产构建下不生效，我直接降级写死 @ant-design/pro-components 2.3.x 版本，问题就解决了。。。

我的环境是 
vite - 4.1.1
@ant-design/pro-components - 2.4.8
测试是 ok 的.

**Comment by blinkcat** [comment]
@chenshuai2144 npm上 latest tag 指向2.4.9 而不是 2.4.10 ，正常安装下不到最新的

**Comment by ZhangLinkang** [comment]
+1

**Comment by abdeljalil09** [comment]
+1

**Comment by doiya46** [comment]
+1

**Comment by Lucien-X** [comment]
> ## 临时修复方案
> ### vite
> ```tsx
> // vite config
> 
> define: {
>   'process.env': '{}', 
> },
> ```
> 
> #### webpack
> ```tsx
> // webpack config
> 
> plugins: [
>   new DefinePlugin({
>     'process': { env: { NODE_ENV: JSON.stringify('production') } },
>   })
> ],
> ```

vite中得写成
```
'process.env': '({})',
```
否则会出现构建时报错，babel 不会把这个字符串当成对象，会当成花括号
