### ISSUE TITLE
🧐[问题]pro-table columns 的 width 和 ellipsis 同时设置时，width 不生效

### ISSUE THREAD

**Issue by jassonxian** [ant-design/pro-components#698]
### 🧐 问题描述

pro-table columns 的 width 和 ellipsis 同时设置时，width 不生效，当设置tableLayout="fixed"，内容会超出可是区域
当我设置了仅设置copyable: true时，就能正常显示

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/pro-components/issues/592
