### ISSUE TITLE
🐛[BUG]ProFormSwitch点击label的位置也会触发Switch的onChange

### ISSUE THREAD

**Issue by leila-huang** [ant-design/pro-components#6981]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProFormSwitch点击label的位置也会触发Switch的onChange

### 📷 复现步骤

![switch-bug](https://user-images.githubusercontent.com/22982196/234558705-838857ae-7c81-4cdb-8d67-cbbafa65cf28.gif)

### 🏞 期望结果

点击label不会引起switch的变化

### 💻 复现代码

官网demo地址：https://procomponents.ant.design/~demos/docs-components-schema-demo-valuetype

### © 版本信息

- ProComponents 版本: 2.3.57
- 开发环境：Windows OS

**Comment by chenshuai2144** [comment]
就是这么设计的，label 增加了一个for 的字段
具体规范看这里

https://developer.mozilla.org/en-US/docs/web/html/element/label
