### ISSUE TITLE
🐛[BUG] antd-pro-merge-less运行/打包时报错

### ISSUE THREAD

**Issue by liangxiao-zs** [ant-design/pro-components#6984]
### 🐛 bug 描述

不管是run start还是run build的时候都会出现报错，非阻碍性报错，还是能跑起dev服务或者打包。但是线上CI之后样式会出问题。报错内容：

```
TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2195:5)
    at loop (H:\ssp_frontend\node_modules\antd-pro-merge-less\index.js:285:12)
    at build (H:\ssp_frontend\node_modules\antd-pro-merge-less\index.js:299:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
SyntaxError: (postcss) CssSyntaxError Unknown word (14993:1)
```
与ant-pro-merge-less库中这个issue问题完全一致：[antd design pro v4 LessError: variable @alert-prefix-cls is undefined](https://github.com/chenshuai2144/antd-pro-merge-less/issues/25)

与umi-plugin-antd-theme库中的这个问题也完全一致：[less building error](https://github.com/chenshuai2144/umi-plugin-antd-theme/issues/40)

### © 版本信息
- pro-components: ^2.4.0
- umi-plugin-antd-theme：2.1.2
- Ant design 版本: ^4.16.0
- umi 版本: 3.2.14
- 浏览器环境 Chrom最新版本
- 开发环境: Windows 11

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/35052827/234754095-b79c7504-878b-4df7-a4c8-e48b701dffb4.png)
![image](https://user-images.githubusercontent.com/35052827/234754135-a057b383-3ab5-43f4-8779-fe245817adb5.png)

**Comment by liangxiao-zs** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
这个库不在维护了，最好用最新的cssinjs，不然就要自己解决了
