### ISSUE TITLE
🧐[问题]react版本可以兼容一下16.x的吗，不然会出现依赖冲突，需要--force 或者--legacy-peer-deps

### ISSUE THREAD

**Issue by jiialinn** [ant-design/pro-components#6985]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
尽量升级 17 吧，17和  16 几乎没有区别
