### ISSUE TITLE
🐛[BUG]  pro-utils 没有es模块，导致vite启动失败

### ISSUE THREAD

**Issue by liuxsen** [ant-design/pro-components#6988]
- ProComponents 版本: 2.3.59
![image](https://user-images.githubusercontent.com/12598696/234798261-fb170f9a-9f15-420b-ae9f-e09e5489160c.png)

启动报错信息如下

![image](https://user-images.githubusercontent.com/12598696/234798342-650688b1-bfc4-4727-b9ee-1738c17dbcd5.png)

**Comment by DroganC** [comment]
2.8.4的pro-utils就一lib包
并且引用的pro-provider版本也没有和其他的同步

麻烦发版的时候注意下

**Comment by abdeljalil09** [comment]
what's the solution for this?

**Comment by chenshuai2144** [comment]
升级到最新版本吧，那个版本编译的有问题
