### ISSUE TITLE
🐛[BUG] Can't resolve './array-move' in  pro-utils/lib（@ant-design_pro-utils@2.8.4）

### ISSUE THREAD

**Issue by into-piece** [ant-design/pro-components#6989]
@ant-design_pro-utils@2.8.4 构建失败

### 🐛 bug 描述

Module not found: Error: Can't resolve './array-move' in '/cloud/source_code/node_modules/_@ant-design_pro-utils@2.8.4@@ant-design/pro-utils/lib

**Comment by wangyun122** [comment]
+1

**Comment by silencesy** [comment]
+1

**Comment by markdashi** [comment]
+1

**Comment by markdashi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by into-piece** [comment]
已修复

**Comment by markdashi** [comment]
> 已修复

是因为发布了新版本吗？ 
如何锁定版本避免后续出现这个问题？

**Comment by markdashi** [comment]
@ant-design/pro-utils 使用 2.8.3 版本就 OK 了

**Comment by zegezs** [comment]
> @ant-design/pro-utils 使用 2.8.3 版本就 OK 了

我这边使用2.8.3 版本还是报错

**Comment by teamco** [comment]
+1

**Comment by markdashi** [comment]
> 我这边使用2.8.3 版本还是报错

清除本地node_module后重新拉一次

**Comment by teamco** [comment]
> > I am using the 2.8.3 version here and still report an error
> 
> Pull again after clearing the local node_module

the same issue
<img width="1184" alt="issue" src="https://user-images.githubusercontent.com/18106/235059783-556c86e1-361e-49df-8e44-4f0951f836c5.png">
