### ISSUE TITLE
🐛[BUG] renderFormItem missing onChange/value when search={{filterType: 'light'}}

### ISSUE THREAD

**Issue by scotty595** [ant-design/pro-components#699]
### 🐛 bug 描述

onChange/value props are missing from the rendered form item when filterType is set to 'light'

### 📷 复现步骤

```typescript
  const columns: ProColumns<ChangeType>[] = [
    {
      title: 'Name',
      dataIndex: 'name',
    },
    {
      title: 'Project',
      dataIndex: 'project',
      renderFormItem: () => <ProjectSelect />,
    },
]

  return (
    <ProTable
      columns={columns}
      pagination={{
        showQuickJumper: true,
      }}
      search={{filterType: 'light'}}
      formRef={ref}
      actionRef={actionRef}
      request={(params = {}) => request(params)}
      rowKey="id"
  />
```

When filterType is 'light' as above, initial props on the `<ProjectSelect />` are:

`{label: "Project", name: "project"}`

when filterType is 'query', initial props on the `<ProjectSelect />` are:

`{label: "Project", name: "project", hidden: true, value: undefined, onChange: ƒ}`

Is this expected behaviour? If so, how do we use renderFormItem or custom selects etc when using 'light' mode?

-ProTable 版本: 2.9.3

**Comment by chenshuai2144** [comment]
this is bad, I will fix it
