### ISSUE TITLE
🐛[BUG] table toolbarrender UI问题

### ISSUE THREAD

**Issue by liuxsen** [ant-design/pro-components#6990]
- ProComponents 版本: [2.3.58]

如果有多个按钮，就会换行！

![image](https://user-images.githubusercontent.com/12598696/234801156-7bdd6de5-5e9a-4d0e-8ae7-0db3340f11ac.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好！感谢您向我们反馈这个问题。

根据您提供的截图，我理解您遇到的问题是在使用 ProComponents 的表格组件时，当按钮数量过多时，会导致按钮换行的 UI 问题。

要解决这个问题，您可以尝试使用按钮组的方式来展示按钮，这样可以更好地控制按钮的排列和布局。

下面是一个代码示例，演示如何使用 ProComponents 的按钮组来展示按钮：

```jsx
import { ToolbarRender } from '@ant-design/pro-layout';
import { Button } from 'antd';

const actions = [
  <Button key="1">按钮一</Button>,
  <Button key="2">按钮二</Button>,
  // 添加更多按钮...
];

const ToolbarRenderUI = () => (
  <ToolbarRender actions={actions} />
);

export default ToolbarRenderUI;
```
您可以根据实际需要添加更多按钮，并根据您的布局需求进行样式调整。

关于 ProComponents 的使用，您可以查阅官方文档来获取更详细的信息和示例代码：
- 官方文档：https://procomponents.ant.design/components/table

希望这个答案能够帮助到您！如果您还有任何问题，请随时向我们提问。

**Comment by chenshuai2144** [comment]
可以用 span  把宽度弄的长一点，不然宽度一直不够
