### ISSUE TITLE
🧐[问题] protable的列展示动态切换columns显示时有事件抛出吗

### ISSUE THREAD

**Issue by Fang-CB** [ant-design/pro-components#6993]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/52224884/234836860-f456788f-2948-464e-88a0-27634eca1827.png)

**Comment by Fang-CB** [comment]
已解决

**Comment by Huhui-coder** [comment]
> 已解决

已解决 是如何解决的，方便在这里贴一下解决方案吗，遇到同样的问题了。

**Comment by Fang-CB** [comment]
> > 已解决
> 
> 已解决是如何解决的，方便在这里贴一下解决方案吗，遇到相同的问题了。

columnsState参数里面的onChange事件
