### ISSUE TITLE
🐛[BUG] 2.4.9 layout mix模式左边空白

### ISSUE THREAD

**Issue by rozbo** [ant-design/pro-components#6995]
![image](https://user-images.githubusercontent.com/7907969/234935204-f1dfd5a4-964f-42aa-9b1d-45396227d5fc.png)

原因是ant-pro-sider-fixed的权重不够，未能覆盖掉`position: relative`

![image](https://user-images.githubusercontent.com/7907969/234935378-ca9837fb-b3d3-43f5-a477-28211b9ff488.png)

**Comment by likaistevens** [comment]
同样的问题。

**Comment by hihuangwei** [comment]
@chenshuai2144 还是存在问题

**Comment by rozbo** [comment]
其实这不仅仅是样式优先级的问题，本上是antd-layout的css被inline了两次
![image](https://user-images.githubusercontent.com/7907969/235077334-ed1dab10-eba4-49f6-8c11-f834cbad40fb.png)

是第二次又重复引入而又覆盖了，所以这不是用户简单写个css再覆盖下就行的。。

**Comment by luoyepiaoling123** [comment]
> ![image](https://user-images.githubusercontent.com/7907969/234935204-f1dfd5a4-964f-42aa-9b1d-45396227d5fc.png)
> 
> 原因是ant-pro-sider-fixed的权重不够，未能覆盖掉`position: relative`
> 
> ![image](https://user-images.githubusercontent.com/7907969/234935378-ca9837fb-b3d3-43f5-a477-28211b9ff488.png)

所以会被修复么，都那么久了，没动静

**Comment by Gzbox** [comment]
+1

**Comment by yezongyang** [comment]
+1

**Comment by wppeng520** [comment]
这个问题现在解决了吗，我都不敢升级了

**Comment by chenshuai2144** [comment]
antd的兼容性问题 一起升级依赖就不会有问题
