### ISSUE TITLE
🐛[BUG]官网layout demo无法打开，会导致浏览器崩溃

### ISSUE THREAD

**Issue by silent181** [ant-design/pro-components#6996]
### 🐛 bug 描述

ProLayout组件[官网demo](https://procomponents.ant.design/components/layout)无法打开，一点击demo tab，等几秒钟浏览器就会崩溃
![image](https://user-images.githubusercontent.com/26674132/235038599-b7d2951b-fd82-4568-95f2-93525a42515c.png)

### 📷 复现步骤

1、打开官网https://procomponents.ant.design/components/layout
2、点击"demo" tab
![image](https://user-images.githubusercontent.com/26674132/235038669-13a2424d-a0b6-48e4-9520-22475c703f2f.png)

3、等待几秒，浏览器会崩溃
![image](https://user-images.githubusercontent.com/26674132/235039025-b6e0af9f-4e02-4ddb-88f2-43a9b2609a1a.png)

### 🏞 期望结果

demo正常展示

### 💻 复现代码

无

### © 版本信息

- 浏览器环境 Windows Chrome 112.0.5615.122（正式版本） （32 位）

**Comment by chenshuai2144** [comment]
懒加载没打开的原因，我加一下
