### ISSUE TITLE
🐛[BUG] ProLayout breadcrumbProps 覆写路由行为时渲染异常，并且 itemRender 推断的类型有问题

### ISSUE THREAD

**Issue by dreammaker7** [ant-design/pro-components#6997]
### 问题一：itemRender 类型异常

ItemType 中是有定义 path 和 title 属性的，并且 items 里定义结构也是正常的。

![image](https://user-images.githubusercontent.com/74588098/235053859-07247228-b785-4ecb-a902-418cee99d2a1.png)
![1682655955416](https://user-images.githubusercontent.com/74588098/235054014-cc5bb7cc-08a4-4c90-896f-61344f9e7733.png)

### 问题二：同问题一的代码，在实际渲染时自动对 items 中 path 渲染了一层跳转，itemRender 的覆写没有覆盖自带渲染，反而多内嵌了一层 Link

![1682656311327](https://user-images.githubusercontent.com/74588098/235054739-b66442e5-68f6-46fe-9266-03be377f1ad9.png)

### 📷 复现步骤

正常定义 breadcrumbProps 属性，问题必现

### 🏞 期望结果

类型推断正常，实际渲染结果正常。

### 💻 复现代码

https://codesandbox.io/s/ji-chu-shi-yong-forked-gjxjnt?file=/App.tsx

### © 版本信息

- ProComponents 版本: [2.4.5]
- antd 版本: [5.4.5]
- umi 版本
- 浏览器环境 [chrome]
- 开发环境 [Windows 11]

**Comment by chenshuai2144** [comment]
你不要设置 path 就不会这样啦

https://github.com/ant-design/ant-design/blob/af0f8904b21f68aedd0bb3a2b7ae31398d357b7e/components/breadcrumb/BreadcrumbItem.tsx#LL95C25-L95C26


antd  就是 这样设计的，最近改的

**Comment by netcore-jroger** [comment]
@chenshuai2144 不设置 path 则不能点击。其实想要的结果是只有一层 a 标签包裹。
如果 `items` 里面没有 path 属性生成的 `Breadcrumb` 是不能点击的。
如果设置 `items` 里面的 path 属性且 `itemRender` 如下这样写：
```js
itemRender: (route) => {
  return route.title;
}
```
则生成的 a 标签的 href 只有 hash 模式的形式，即使使用的是 history 模式。

**Comment by netcore-jroger** [comment]
为了使用 history 模式需要 `itemRender` 返回一个 a 标签，但最终结果会是两个 a 标签嵌套。

**Comment by netcore-jroger** [comment]
另外
```js
itemRender: (route) => {
    return route.path
    // route 是 ItemType 类型，通过导航也能找到定义，定义里面明明包含 path ，但 vscode 会提示不包含 path 属性.
}
```

**Comment by dreammaker7** [comment]
antd 5.4.7 已修复：[https://github.com/ant-design/ant-design/pull/42049](https://github.com/ant-design/ant-design/pull/42049)
