### ISSUE TITLE
🐛[BUG] table组件url 参数同步问题

### ISSUE THREAD

**Issue by liuxsen** [ant-design/pro-components#6998]
版本： @ant-design/pro-components": "2.3.58"

1. table组件点击重置按钮，不会触发syncToUrl;

2. 在table组件中查询完之后，点击跳转到详情页面，然后用navigate返回列表页面，table组件竟然带了详情页面的参数并同步参数到了url；

如何做到命令式跳转到table页面后，不携带参数？

**Comment by chenshuai2144** [comment]
你的框架用的什么？默认 push 是会清空所有 params 的
