### ISSUE TITLE
renderFormItem没有像以前一样渲染，但示例代码一直保留在

### ISSUE THREAD

**Issue by w3cshare** [ant-design/pro-components#700]
### 📷 复现步骤

pro v5示例选择异常的时候，上次调度时间应改换成输入框，并且占位符显示“请输入异常原因！”

### 🏞 期望结果

表单 renderFormItem能再次渲染

### 💻 复现代码
{
      title: '上次调度时间',
      dataIndex: 'updatedAt',
      sorter: true,
      valueType: 'dateTime',
      hideInForm: true,
      renderFormItem: (item, { defaultRender, ...rest }, form) => {
        const status = form.getFieldsValue('status');
        console.warn(status, 'status===');
        if (`${status}` === '0') {
          return false;
        }
        if (`${status}` === '3') {
          return <Input {...rest} placeholder="请输入异常原因！" />;
        }
        return defaultRender(item);
      },
    },
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/22211924/95811535-1704e280-0d46-11eb-8312-35552aeeed03.png)

**Comment by liuchuangjun321** [comment]
我也遇到这个问题了，如果有表单联动的问题，要怎么解决呢？有什么新的方案吗？
