### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by urielvan** [ant-design/pro-components#7000]
### 🐛 bug 描述

使用 message 静态方法时报，以下警告
warning: [antd: message] Static function can not consume context like dynamic theme. Please use 'App' component instead.

### 📷 复现步骤

message.success('successfully');

### 🏞 期望结果

控制台无警告

### 💻 复现代码

message.success('successfully');

### © 版本信息

- ProComponents 版本: 2.4.4
- Ant Design 5.4.5
- 浏览器环境 Chrome 112
- 开发环境 Windows

### 🚑 其他信息

ant design 这个 [commit](https://github.com/ant-design/ant-design/commit/36f44575c891f42d1c2f7c18270751524025440b) 增加了校验，proComponents 这里哪怕没任何 theme 设置，也会注入一个 { theme: { algorithm: undefined } }, 导致触发警告

**Comment by hsulei** [comment]
这个是使用问题吧，antd 现在推荐使用 const {message} = App.useApp() 这种方式来获取message， 而不是直接使用message.success().   [App组件](https://ant.design/components/app-cn)

**Comment by urielvan** [comment]
@hsulei 
我承认他们推荐改变用法，但是原本用法并没有废弃，同时两个库如果在没有breaking changes的情况下我认为需要保持同样会代码运行结果一致

**Comment by zhyblack** [comment]
> 这个是使用问题吧，antd 现在推荐使用 const {message} = App.useApp() 这种方式来获取message， 而不是直接使用message.success(). [App组件](https://ant.design/components/app-cn)

const {message} = App.useApp() 获取的 message，使用不了 message.loading('')

**Comment by xiaopujun** [comment]
> 这个是使用问题吧，antd 现在推荐使用 const {message} = App.useApp() 这种方式来获取message， 而不是直接使用message.success(). [App组件](https://ant.design/components/app-cn)

想问下，有些场景下没法依托于组件，无法使用hook，比如快捷键。这种场景下执行的仅是纯js逻辑，想要弹出提示就没有其他方案了嘛。

**Comment by bignancy** [comment]
> > 这个是使用问题吧，antd 现在推荐使用 const {message} = App.useApp() 这种方式来获取message， 而不是直接使用message.success(). [App组件](https://ant.design/components/app-cn)
> 
> 拦截器里面咋用app.useApp()

```typescript

class GMessage {
    public messageApi: MessageInstance | null = null;

    public setMessageApi(messageApi: any) {
        this.messageApi = messageApi;
    }

}

const globalMessage = new GMessage();
export {globalMessage};


export default function GlobalMessage() {
    const [messageApi, contextHolder] = message.useMessage();

    useEffect(() => {
        globalMessage.setMessageApi(messageApi);
        return () => {
            globalMessage.setMessageApi(null);
        }
    }, []);

    return (
        <>
            {contextHolder}
        </>
    )
}
```
可以用这种方式，设置一个全局的message变量，然后在其他地方使用这个变量调用message API而不是通过app.useApp()调用 @ShingLi
