### ISSUE TITLE
🐛[BUG] 使用 message 静态方法时报错

### ISSUE THREAD

**Issue by urielvan** [ant-design/pro-components#7001]
### 🐛 bug 描述

使用 message 静态方法时报以下警告
warning: [antd: message] Static function can not consume context like dynamic theme. Please use 'App' component instead.

### 📷 复现步骤

message.success('successfully');

### 🏞 期望结果

控制台无警告

### 💻 复现代码

message.success('successfully');

### © 版本信息

- ProComponents 版本: 2.4.4
- Ant Design 5.4.5
- 浏览器环境 Chrome 112
- 开发环境 Windows

### 🚑 其他信息

ant design 这个 [commit](https://github.com/ant-design/ant-design/commit/36f44575c891f42d1c2f7c18270751524025440b) 增加了校验，proComponents 这里哪怕没任何 theme 设置，也会注入一个 { theme: { algorithm: undefined } }, 导致触发警告

**Comment by urielvan** [comment]
@chenshuai2144 
EditableProTable 设置 editable={{ type: 'single' }}

**Comment by ShaoClean** [comment]
昨天拉的最新代码，，，，找了一早上，终于找到解决方案了，好难用啊，，，，，无语
