### ISSUE TITLE
🐛[BUG] ProTable syncToUrl 的特性能不能增加区分 browserHistory 和 hashHistory 的选项？

### ISSUE THREAD

**Issue by dreammaker7** [ant-design/pro-components#7002]
### ProTable syncToUrl 的特性无法区分 browserHistory 和 hashHistory，导致地址中的 search 参数混乱，而且使用 react-router 编程式路由 push、replace 等方法时，上一个带有 ProTable search 的页面的参数也会被带入新地址，因为 ProTable form 的参数被放在了 **#** 号前面。

![1682677917915](https://user-images.githubusercontent.com/74588098/235124745-c7647432-beb5-45de-a0bf-46d3df81ceef.png)

![image](https://user-images.githubusercontent.com/74588098/235124991-fdff4c61-677b-4009-93bf-a12165a692fa.png)

### 📷 复现步骤

任意使用了 syncToUrl 配置的 ProTable。

### 🏞 期望结果

希望可以增加例如 form={{ routerMode: 'hash' }} 的配置，以区分路由模式并且在对应模式正常使用 syncToUrl 特性。

### 💻 复现代码

https://codesandbox.io/s/3ie3v9

**Comment by chenshuai2144** [comment]
没办法实现通用模式吗？
