### ISSUE TITLE
🐛[BUG] ant design pro 刷新之后侧边栏样式变了，侧边栏位置发生了改变

### ISSUE THREAD

**Issue by PeiRunWu** [ant-design/pro-components#7003]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

在web端按F12出现调试框的时候进行刷新，侧边栏的样式出现改变，这是改变之后的样式，侧边栏样式直接丢失了，这是丢失样式的图片：

### 📷 复现步骤
这个是视频详细描述

https://user-images.githubusercontent.com/42695882/235151673-9de1d978-4e28-48f8-a616-e2e4d8b47c39.mp4

### 🏞 期望结果

刷新之后还是显示正常,样式没有丢失

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] 
- umi 版本 umi 4.0.66
- 浏览器环境 edge
- 开发环境 [e.g. mac OS] window

### 🚑 其他信息
package.json信息： 

{
  "private": true,
  "scripts": {
    "dev": "max dev",
    "build": "max build",
    "format": "prettier --cache --write .",
    "prepare": "husky install",
    "postinstall": "max setup",
    "setup": "max setup",
    "start": "npm run dev"
  },
  "dependencies": {
    "@ant-design/icons": "^5.0.1",
    "@ant-design/pro-components": "^2.4.6",
    "@umijs/max": "^4.0.66",
    "antd": "5.4.6"
  },
  "devDependencies": {
    "@types/react": "^18.0.33",
    "@types/react-dom": "^18.0.11",
    "husky": "^8.0.3",
    "lint-staged": "^13.2.0",
    "prettier": "^2.8.7",
    "prettier-plugin-organize-imports": "^3.2.2",
    "prettier-plugin-packagejson": "^2.4.3",
    "typescript": "^5.0.3"
  }
}

**Comment by chenshuai2144** [comment]
重新更新一下依赖，是一个简单的样式优先级问题
