### ISSUE TITLE
🐛[BUG]使用BetaSchemaForm的ModalForm布局，多次打开表单内容不渲染问题

### ISSUE THREAD

**Issue by yijiehuanshen** [ant-design/pro-components#7004]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

使用BetaSchemaForm和ModalForm布局进行动态表单渲染。
在同时使用onOpenChange属性和modalProps: {destroyOnClose: true}两个属性同时使用时
第一次打开可正常渲染表单内容，取消后再次打开对话框中的表单元素为空

### 📷 复现步骤
[https://codesandbox.io/s/schema-biao-dan-forked-oce2kb](url)

关键代码
```
  const [open, setOpen] = useState(false);
  return (
    <>
      <h1 onClick={() => setOpen(true)}>对话框表单（点击打开） </h1>
      <BetaSchemaForm<DataItem>
        // 对话框表单布局
        layoutType="ModalForm"
        open={open}
        // 打开/关闭状态变更事件
        onOpenChange={setOpen}
        modalProps={{
          // 关闭自动销毁
          destroyOnClose: true
        }}
        columns={[
          // 表单项定义
          {
            title: "创建时间",
            key: "showTime",
            dataIndex: "createName",
            valueType: "date"
          },
        ]}
      />
    </>
  );
```

1、第一次打开表单对话框后可以直接点击“取消”按钮
2、再次打开对话框

### 🏞 期望结果
多次打开/关闭对话框表单可以正常显示

### 💻 复现代码
https://codesandbox.io/s/schema-biao-dan-forked-oce2kb

### © 版本信息
  "dependencies": {
    "@ant-design/pro-components": "2.4.5",
    "antd": "5.4.6",
    "react": "latest",
    "react-dom": "latest"
  },
  "devDependencies": {
    "@types/react": "^18.2.0",
    "typescript": "^4"
  }

**Comment by WuJiY** [comment]
还是有问题

**Comment by kasnti** [comment]
你解决了吗？我在使用中也有相同的问题。
并且官网例子 [浮层窗口](https://procomponents.ant.design/components/schema-form#betaschemaform-demo-modalanddrawerform) 中ModalForm是正常的，但是DrawerForm也是不渲染。
![image](https://github.com/ant-design/pro-components/assets/18499852/8bc54b7d-31b9-49e7-9ad6-eeb13fca375d)
