### ISSUE TITLE
👑 [需求] 优化官网文档在暗色模式下的体验

### ISSUE THREAD

**Issue by wrote-code** [ant-design/pro-components#7005]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

[官网文档](https://procomponents.ant.design/)。

### 🥰 需求描述

暗黑模式下，无法看清组件demo中的文字。

默认文字颜色是黑色，背景色是白色。切暗色模式后，背景色变为黑色，黑色文字完全看不见。

这是正常情况：

![图片](https://user-images.githubusercontent.com/39870481/235317990-18fedb4c-5b18-4f6b-8d04-5754e3b39ce0.png)

这是切暗色后的情况：

![图片](https://user-images.githubusercontent.com/39870481/235318007-73dbec10-0975-4984-8442-006ee70826e5.png)

**Comment by chenshuai2144** [comment]
更新吧，已经解决啦
