### ISSUE TITLE
[Question] How to change the options of a table filter depending on another filters value

### ISSUE THREAD

**Issue by erdemkeren** [ant-design/pro-components#7006]
### Description

I have two filterable columns with valueType: `select`. I want the options of the second select to change when the selected option of the first filter changes.

### 💻 Example Code

```typescript
{
    title: 'city',
    valueType: 'select',
    request: async () => {},
},
{
    title: 'district',
    valueType: 'select',
    request: async (form) => { // <- I know that doesn't exists but it would have been great to have such a feature
        return await getDistrictList(form.getFieldValue('city_id'))
    }
},
```

### 🚑 Additional Information

This is not a feature request but is there a way to accomplish this without a custom implementation?

**Comment by chenshuai2144** [comment]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/8186664/236142319-42cc112d-f1ad-4f7b-97d8-81d4c8e4b791.png">


you can use dependencies，if set dependencies=['city'] , city change will trigger request relaod
