### ISSUE TITLE
Can't resolve './array-move' in pro-utils/lib（@ant-design_pro-utils@2.8.4）🐛[BUG]

### ISSUE THREAD

**Issue by veshen** [ant-design/pro-components#7007]
### 🐛 bug 描述

info  - Umi v4.0.67
info  - Preparing...
[info] [webpackbar] Compiling Webpack
[success] [webpackbar] Webpack: Compiled with some errors in 28.03s
info  - Memory Usage: 926.97 MB (RSS: 1173.36 MB)
fatal - Error: ERROR in ./node_modules/@ant-design/pro-card/node_modules/@ant-design/pro-utils/lib/index.js 393:17-40
Module not found: Error: Can't resolve './array-move' in '/home/runner/work/plutus-nice-pro/plutus-nice-pro/node_modules/@ant-design/pro-card/node_modules/@ant-design/pro-utils/lib'
 @ ./node_modules/@ant-design/pro-card/es/components/CheckCard/index.js 6:0-59 16:28-46
 @ ./node_modules/@ant-design/pro-card/es/index.js 1:0-47 6:0-56
 @ ./node_modules/@ant-design/pro-components/es/index.js 1:0-37 1:0-37
 @ ./src/.umi-production/plugin-layout/Layout.tsx 11:0-118 123:27-36
 @ ./src/.umi-production/core/route.tsx
 @ ./src/.umi-production/umi.ts 12:0-41 29:17-26

ERROR in ./node_modules/@ant-design/pro-card/node_modules/@ant-design/pro-utils/lib/index.js 394:22-60
Module not found: Error: Can't resolve './components/DropdownFooter' in '/home/runner/work/plutus-nice-pro/plutus-nice-pro/node_modules/@ant-design/pro-card/node_modules/@ant-design/pro-utils/lib'
 @ ./node_modules/@ant-design/pro-card/es/components/CheckCard/index.js 6:0-59 16:28-46
 @ ./node_modules/@ant-design/pro-card/es/index.js 1:0-47 6:0-56
 @ ./node_modules/@ant-design/pro-components/es/index.js 1:0-37 1:0-37
 @ ./src/.umi-production/plugin-layout/Layout.tsx 11:0-118 123:27-36
 @ ./src/.umi-production/core/route.tsx
 @ ./src/.umi-production/umi.ts 12:0-41 29:17-26

ERROR in ./node_modules/@ant-design/pro-card/node_modules/@ant-design/pro-utils/lib/index.js 395:21-58
Module not found: Error: Can't resolve './components/ErrorBoundary' in '/home/runner/work/plutus-nice-pro/plutus-nice-pro/node_modules/@ant-design/pro-card/node_modules/@ant-design/pro-utils/lib'
 @ ./node_modules/@ant-design/pro-card/es/components/CheckCard/index.js 6:0-59 16:28-46
 @ ./node_modules/@ant-design/pro-card/es/index.js 1:0-47 6:0-56
 @ ./node_modules/@ant-design/pro-components/es/index.js 1:0-37 1:0-37
 @ ./src/.umi-production/plugin-layout/Layout.tsx 11:0-118 123:27-36
 @ ./src/.umi-production/core/route.tsx
 @ ./src/.umi-production/umi.ts 12:0-41 29:17-26

ERROR in ./node_modules/@ant-design/pro-card/node_modules/@ant-design/pro-utils/lib/index.js 396:18-52
Module not found: Error: Can't resolve './components/FieldLabel' in '/home/runner/work/plutus-nice-pro/plutus-nice-pro/node_modules/@ant-design/pro-card/node_modules/@ant-design/pro-utils/lib'
 @ ./node_modules/@ant-design/pro-card/es/components/CheckCard/index.js 6:0-59 16:28-46
 @ ./node_modules/@ant-design/pro-card/es/index.js 1:0-47 6:0-56
 @ ./node_modules/@ant-design/pro-components/es/index.js 1:0-37 1:0-37
 @ ./src/.umi-production/plugin-layout/Layout.tsx 11:0-118 123:27-36
 @ ./src/.umi-production/core/route.tsx
 @ ./src/.umi-production/umi.ts 12:0-41 29:17-26

ERROR in ./node_modules/@ant-design/pro-card/node_modules/@ant-design/pro-utils/lib/index.js 397:22-60
Module not found: Error: Can't resolve './components/FilterDropdown' in '/home/runner/work/plutus-nice-pro/plutus-nice-pro/node_modules/@ant-design/pro-card/node_modules/@ant-design/pro-utils/lib'
 @ ./node_modules/@ant-design/pro-card/es/components/CheckCard/index.js 6:0-59 16:28-46
 @ ./node_modules/@ant-design/pro-card/es/index.js 1:0-47 6:0-56
 @ ./node_modules/@ant-design/pro-components/es/index.js 1:0-37 1:0-37
 @ ./src/.umi-production/plugin-layout/Layout.tsx 11:0-118 123:27-36
 @ ./src/.umi-production/core/route.tsx
 @ ./src/.umi-production/umi.ts 12:0-41 29:17-26

### © 版本信息
 ant-design-pro@6.0.0
- ProComponents 版本: [^2.4.8]
- umi 版本  Umi v4.0.67
- 浏览器环境 
- 开发环境 [centos build node 14.x]

**Comment by veshen** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [[🐛[BUG] Can't resolve './array-move' in  pro-utils/lib（@ant-design_pro-utils@2.8.4） #6989](https://github.com/ant-design/pro-components/issues/6989)][🐛[BUG] Can't resolve './array-move' in  pro-utils/lib（@ant-design_pro-utils@2.8.4）][70%]
> * [[🐛[BUG] Can't resolve @ant-design/pro-card ，@ant-design/pro-layout的依赖找不到了 #6742](https://github.com/ant-design/pro-components/issues/6742)][🐛[BUG] Can't resolve @ant-design/pro-card ，@ant-design/pro-layout的依赖找不到了][67%]
> * [[🐛[BUG] Can't resolve @ant-design/pro-card  #6743](https://github.com/ant-design/pro-components/issues/6743)][🐛[BUG] Can't resolve @ant-design/pro-card ][64%]

然而并没有什么卵用

**Comment by abdeljalil09** [comment]
there is no es  folder

**Comment by leshalv** [comment]
+1

**Comment by leshalv** [comment]
@chenshuai2144

**Comment by ZhangLinkang** [comment]
+1

**Comment by oswayne** [comment]
+1

**Comment by wangqiaoling01** [comment]
所以这个怎么解决呀？

**Comment by chenshuai2144** [comment]
已经修复，请更新版本

**Comment by chieway** [comment]
2.85，2.86版本都试过了，node_modules也删除重装过，还是会报错。 Cannot find module './array-move'
