### ISSUE TITLE
🧐[问题] 前端接收数据，菜单动态生成了，但是component 失效了，访问404

### ISSUE THREAD

**Issue by PeiRunWu** [ant-design/pro-components#7008]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

前端接收数据，菜单动态生成了，但是component 失效了，访问404

<img width="651" alt="image" src="https://user-images.githubusercontent.com/42695882/235657753-c4608687-23cf-4799-bb72-55cd73553238.png">

`// 运行时配置
import Footer from '@/components/Footers';
import { GithubAction, Wechat } from '@/components/RightContent';
import AvatarDropdown from '@/components/RightContent/AvatarDropdown';
import * as AllIcons from '@ant-design/icons';
import { AlipayCircleFilled, GitlabFilled } from '@ant-design/icons';
import type { MenuDataItem } from '@ant-design/pro-components';
import {
  Settings as LayoutSettings,
  SettingDrawer,
} from '@ant-design/pro-components';

import { RunTimeLayoutConfig, history } from '@umijs/max';
import defaultSettings from '../config/defaultSettings';
import Icon from './components/Icon';
import { SysMenuType } from './repository/system/SysMenu';
import { SysUserType } from './repository/system/sysUser';
import { requestConfig } from './requestConfig';
import { queryCurrentUserMenus } from './services/system/sysMenuService';
import { queryCurrentUser } from './services/system/sysUserService';

const loginPath = '/user/login';

export interface ExtendedMenuDataItem extends MenuDataItem {
  component?: string;
}

const loopMenuItem = (menus: SysMenuType.MenuItem[]): ExtendedMenuDataItem[] =>
  menus.map(({ icon, routes, ...item }) => ({
    ...item,
    icon: icon && <Icon name={icon as keyof typeof AllIcons} />,
    children: routes && loopMenuItem(routes),
    component: item.component,
  }));

// 全局初始化数据配置，用于 Layout 用户信息和权限初始化
// 更多信息见文档：https://umijs.org/docs/api/runtime-config#getinitialstate
export async function getInitialState(): Promise<{
  currentUser?: SysUserType.CurrentUser;
  settings?: Partial<LayoutSettings>;
  fetchUserMenus?: () => Promise<ExtendedMenuDataItem[] | undefined>;
  menuData?: ExtendedMenuDataItem[];
  fetchUserInfo?: () => Promise<SysUserType.CurrentUser | undefined>;
}> {
  const fetchUserInfo = async () => {
    try {
      const response = await queryCurrentUser();
      return response.data;
    } catch (error) {
      history.push(loginPath);
    }
    return undefined;
  };

  const fetchUserMenus = async () => {
    try {
      const response = await queryCurrentUserMenus();
      return loopMenuItem(response.data || []);
    } catch (error) {
      history.push(loginPath);
    }
    return undefined;
  };

  // 如果不是登录页面，执行
  const { location } = history;
  if (location.pathname !== loginPath) {
    const currentUser = await fetchUserInfo();
    const currentUserMenus = await fetchUserMenus();
    return {
      menuData: currentUserMenus,
      fetchUserInfo,
      currentUser,
      settings: defaultSettings as Partial<LayoutSettings>,
    };
  }

  return {
    menuData: [],
    fetchUserMenus,
    fetchUserInfo,
    settings: defaultSettings as Partial<LayoutSettings>,
  };
}

export const layout: RunTimeLayoutConfig = ({
  initialState,
  setInitialState,
}) => {
  return {
    menu: {
      locale: false,
    },
    //设置头像和登入名称
    avatarProps: {
      src: initialState?.currentUser?.headUrl,
      title: initialState?.currentUser?.username,
      render: (_: any, avatarChildren: any) => {
        return <AvatarDropdown>{avatarChildren}</AvatarDropdown>;
      },
    },
    postMenuData: () => {
      return initialState?.menuData || [];
    },

    onPageChange: () => {
      const { location } = history;
      // 如果没有登录，重定向到 login
      if (!initialState?.currentUser && location.pathname !== loginPath) {
        history.push(loginPath);
      }
    },

    // 设置显示图标
    actionsRender: () => [
      <GithubAction key="github" />,
      <GitlabFilled key="gitlabFilled" />,
      <Wechat key="wechatFilled" />,
      <AlipayCircleFilled key="alipayCircleFilled" />,
    ],

    // 设置页脚
    footerRender: () => <Footer />,
    // 配置默认setting 属性
    childrenRender: (children) => {
      return (
        <>
          {children}
          <SettingDrawer
            disableUrlParams
            enableDarkTheme
            settings={initialState?.settings}
            onSettingChange={(settings: Partial<LayoutSettings>) => {
              setInitialState((preInitialState) => ({
                ...preInitialState,
                settings,
              }));
            }}
          />
        </>
      );
    },
    ...initialState?.settings,
  };
};

/**
 * @name request 配置，可以配置错误处理
 * 它基于 axios 和 ahooks 的 useRequest 提供了一套统一的网络请求和错误处理方案。
 * @doc https://umijs.org/docs/max/request#配置
 */
export const request = {
  ...requestConfig,
};
`

**Comment by chenshuai2144** [comment]
菜单和路由是两个东西

菜单只是 menu 组件的数据，而路由会影响  build，一般来说都是写死的。

菜单可以在这里使用，路由需要写死 
https://pro.ant.design/zh-CN/docs/advanced-menu
