### ISSUE TITLE
🧐[问题]ProForm嵌套ProTable时，ProForm设置disabled后样式问题

### ISSUE THREAD

**Issue by leila-huang** [ant-design/pro-components#7009]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
在有一些业务场景下会出现ProForm嵌套ProTable时，ProForm设置disabled后ProTable的多选和tableAlert部分还可以操作，想请问一般这部分是自己手动处理一下禁用逻辑还是应该 ProTable 加上这部分的兼容？

### 💻 示例代码

[ProForm嵌套ProTable](https://codesandbox.io/s/biao-ge-pi-liang-cao-zuo-forked-2jgl0e?file=/App.tsx)

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/22982196/236095034-c60f4a70-b0b6-4b01-8405-641281738ea1.png)

**Comment by chenshuai2144** [comment]
这个难度还挺大的，因为数据不同，你可以动态把 rowSelection 设置为 false 来绕过一下，如果需要更极致的体验，推荐去 antd 中提一个 pr，让  rowSelection 支持一下  disable
