### ISSUE TITLE
👑 [需求]ProTable,搜索框日期英文怎么改为中文

### ISSUE THREAD

**Issue by lklslkla** [ant-design/pro-components#701]
目前用ConfigProvider包裹没有用,原生的antd组件没有问题.这边没有说明文档,不知道具体怎么操作.帮忙给出个文档或者demo,可以实现搜索框日期为中文

**Comment by chenshuai2144** [comment]
看看这个呢？

https://procomponents.ant.design/~demos/src-table-15

你使用的是 es 还是 lib 模式？

**Comment by chenshuai2144** [comment]
是这个导致的

https://github.com/ant-design/pro-components/pull/738

删除 lock 文件，更新一下依赖就好了

**Comment by YanYuanFE** [comment]
https://github.com/ant-design/pro-components/issues/55，重复issue
