### ISSUE TITLE
🧐[问题] ProTable 列设置中怎么设置某些列默认不勾选

### ISSUE THREAD

**Issue by SuperZhanggy** [ant-design/pro-components#7011]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/50569825/236359666-6919023c-e254-49c9-a4ca-2dad142173f8.png)

**Comment by SuperZhanggy** [comment]
大佬们有知道教教小弟，ant design 初学者

**Comment by chenshuai2144** [comment]
columnsState | 受控的列状态，可以操作显示隐藏 | columnsStateType | -
-- | -- | -- | --




文档里有，你看看 demo

**Comment by SuperZhanggy** [comment]
大佬，有没有群，拉我进钉钉群，13456217896

**Comment by seveneElevenup** [comment]
columnState里面如何隐藏某一列  不使用hideInTable

**Comment by SuperZhanggy** [comment]
ProTable 组件官方文档的demo 里有，类似以下的设置


// 设置某些列隐藏
    const [columnsStateMap, setColumnsStateMap] = useState<Record<string, ColumnsState>>({
        option: {
            show: false,
            order: 2,
        },
    });

<ProTable
columnsState={{
                              value: columnsStateMap,
                              onChange: setColumnsStateMap,
                          }}
/>

**Comment by seveneElevenup** [comment]
不是不勾选，是在这个列展示里面隐藏掉某一列

&nbsp;


€€€
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月27日(星期二) 中午11:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/pro-components] 🧐[问题] ProTable 列设置中怎么设置某些列默认不勾选 (Issue #7011)





 
ProTable 组件官方文档的demo 里有，类似以下的设置
 
// 设置某些列隐藏
 const [columnsStateMap, setColumnsStateMap] = useState<Record<string, ColumnsState&gt;&gt;({
 option: {
 show: false,
 order: 2,
 },
 });
 
<ProTable
 columnsState={{
 value: columnsStateMap,
 onChange: setColumnsStateMap,
 }}
 /&gt;

**Comment by SuperZhanggy** [comment]
不勾选，表格里默认就不会展示出来啊，不理解你想干什么

**Comment by seveneElevenup** [comment]
抱歉，不是不勾选，是列展示里面隐藏某一列

**Comment by seveneElevenup** [comment]
{
      title: '测试',
      dataIndex: 'statusList',
      key: 'statusList',
      // hideInTable: true, // 此项为了解决EditableProTable指标状态切换导致options取值错误的bug
      render: () => null,
    },为了解决编辑表格的一个问题，表格上多存了一个表头，需要在列展示里面把这个隐藏掉

**Comment by SuperZhanggy** [comment]
我只知道hideInTable ，其他的你可以问下 [chenshuai2144](https://github.com/chenshuai2144)

**Comment by seveneElevenup** [comment]
感谢，用hideInTable可以隐藏，但是不能解决我编辑表格options取值的问题

**Comment by seveneElevenup** [comment]
@chenshuai2144

**Comment by SuperZhanggy** [comment]
{
  title: '测试',
  dataIndex: 'statusList',
  key: 'statusList',
  // hideInTable: true,
},

你这样只是让这一列的内容变成空值了吧

**Comment by seveneElevenup** [comment]
是的，statusList是select的options,每一行的option不同，后台返回在当条数据里面，编辑的时候这个options是动态改变的

**Comment by seveneElevenup** [comment]
换行切换一直切换这个select，会导致editableFormRef.current?.getRowData?.(rowIndex)取statusList的值存在覆盖的问题，所以就想绕过这个问题，通过columnState来处理这个问题，用这个处理就导致隐藏的问题了
