### ISSUE TITLE
🐛[BUG] layout token 失效

### ISSUE THREAD

**Issue by 7ingning** [ant-design/pro-components#7012]
### 🐛 bug 描述

pro-component版本2.4.4+开始，layout token 失效，锁死2.4.4的版本是正常的，但是发布了2.4.12后，依赖默认拿小版本，也出现了token失效问题，layoutTokenConfig.sider 的 token 配置不生效，build后展示的不是token配置的效果。

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/131357495/236370066-1293f40e-8af3-4dd1-85c7-5b87c82aaa04.png)
![image](https://user-images.githubusercontent.com/131357495/236370559-56964bf3-016f-4f1f-982e-48e1a9765cfc.png)

### © 版本信息

- ProComponents 版本: [^2.4.4]
- umi 版本 v4
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
更新到最新版本就能解决这个问题

**Comment by zbl400** [comment]
请问最新版本是哪个版本？官网示例 2.4.12 仍然有部分 token 不生效
![image](https://user-images.githubusercontent.com/2020731/236591074-ffc032a7-9339-4f6b-8adc-6c78b2fa45ea.png)

**Comment by zhengmenghuang** [comment]
2.4.12 部分token 不生效

![image](https://user-images.githubusercontent.com/29627098/236591280-fecd97fb-db5d-43a8-9bb2-9f05d95868b6.png)
![image](https://user-images.githubusercontent.com/29627098/236591321-17d534ed-219c-41a4-a030-bee44c1cb1d0.png)

**Comment by zhengmenghuang** [comment]
2.4.14又把2.4.13修复的改坏了

**Comment by echoyl** [comment]
pageContainer  2.5.5也失效了  先直接写样式里了
