### ISSUE TITLE
🐛[BUG] EditableProTable 中配置 columns 关联列无法生效

### ISSUE THREAD

**Issue by itenl** [ant-design/pro-components#7014]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
EditableProTable 中配置 columns 列，其中有两列类型是  valueType: 'select' 是相互关联联动的，使用A改变后联动给到B，在B中设定 dependencies: ['A'] 并不能生效

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境：Chrome
- 开发环境： mac OS

**Comment by itenl** [comment]
reproduce link: https://codesandbox.io/s/zen-curran-i7w6g4?file=/src/App.js
@chenshuai2144

**Comment by avivadepp** [comment]
@chenshuai2144  EditableProTable能支持一下valueType:'dependency'吗？
