### ISSUE TITLE
🐛[BUG]  列设置关闭弹框时报错 not read properties of null (reading 'contains')

### ISSUE THREAD

**Issue by sadianliaoer** [ant-design/pro-components#7015]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

在使用 ProTable  的列设置功能时，将 table 的某一列上移或者下移，之后点击页面关闭设置弹框时报错

### 📷 复现步骤

配置好table 的 columns ，之后点击标题栏中的设置图标，进行类列的上下移动，移动固定首尾操作之后，单击任意位置关闭设置弹框，页面出现错误

### 🏞 期望结果

希望能正确设置列，不报错

### 💻 复现代码
  
 codesandbox 示例代码：  https://codesandbox.io/s/antd-pro-table-xenqe5

```jsx
import "./styles.css";
import { ProTable } from "@ant-design/pro-components";

export default function App() {
  const columns = [
    {
      dataIndex: "de",
      title: "ces1"
    },
    {
      dataIndex: "de2",
      title: "ces2"
    },
    {
      dataIndex: "de3",
      title: "ces3"
    }
  ];

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>

      <ProTable columns={columns}  />
    </div>
  );
}

```

### © 版本信息

- ProComponents 版本: [e.g. 4.4.4]
- react-script [e.g. 5.0.1]
- 浏览器环境 : 所有浏览器都报错
- 开发环境 [e.g. mac OS]  mac &  windows 11  
- React  [e.g. 18.0.0]
- Antd [e.g. 5.3.1]

### 🚑 其他信息

![20230505164523](https://user-images.githubusercontent.com/24228407/236414514-6d452c4f-247d-4385-9843-f1f2ed77c136.png)
![_20230505165350](https://user-images.githubusercontent.com/24228407/236416184-2168969a-87c9-4709-958e-fd0c22ab64b8.png)

**Comment by chenshuai2144** [comment]
看起来是什么必要的数据为空了，你有详细的堆栈吗？

**Comment by chenshuai2144** [comment]
好像没有报错，是有什么特殊的配置吗？

**Comment by sadianliaoer** [comment]
@chenshuai2144  你可以看看我提供那个简易复现例子 ，你看看您使用的版本是否和我的一致哈，项目式通过 create react app  创建的项目

**Comment by lucas200631** [comment]
@sadianliaoer  我也出现了同样的问题 请问作者解决了这个问题嘛？？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，作为一个 GitHub Issue 助理，我无法直接和作者沟通或查看他们是否解决了问题。然而，我可以尝试为你提供一些解决方法。

根据你提供的信息和复现代码，我看到你使用的是 ProTable 组件，并且在操作列设置时出现了错误。这可能是因为在关闭设置弹框时，一些必要的数据未被正确处理，导致出现报错。

首先，建议你确保你正在使用最新的版本，以便利用最新的 Bug 修复和功能改进。

另外，你可以尝试以下解决方法：

1. 清除缓存和重新安装依赖：首先尝试清除缓存，然后重新安装所有依赖项，可能会有助于解决依赖项版本不匹配的问题。
   在你的项目根目录下执行以下命令：
   ```
   npm cache clean --force
   rm -rf node_modules
   npm install
   ```

2. 更新相关的依赖：尝试更新 ProComponents、React 和 Antd 的相关依赖。可以通过运行以下命令来更新：
   ```
   npm update @ant-design/pro-components
   npm update react
   npm update antd
   ```

3. 查看官方文档和问题报告：浏览 ProComponents 的官方文档和问题报告，看看有没有类似的问题和解决方法。这将帮助你了解是否有已知的 Bug 或者官方提供的解决方案。你可以在以下链接中找到官方文档和问题报告：

   - ProComponents 官方文档：https://procomponents.ant.design/
   - ProComponents GitHub 仓库：https://github.com/ant-design/pro-components

如果以上方法都不能解决你的问题，建议在 ProComponents 的 GitHub 仓库中提出一个 issue，详细描述你的问题，提供你的代码和错误堆栈信息。这样作者和社区的其他人就有机会帮助你解决问题了。

希望这些方法能帮到你！如果你有更多的问题或者需要进一步的帮助，请随时告诉我。

**Comment by chenshuai2144** [comment]
![image](https://github.com/ant-design/pro-components/assets/8186664/da990562-ebc0-4106-aa2a-3a1ad8b34901)

这个版本没问题了
