### ISSUE TITLE
🐛[BUG] npm包体中pro-card丢失es目录下的typing.d.ts文件

### ISSUE THREAD

**Issue by AndrewAdam** [ant-design/pro-components#7017]
### 🐛 bug 描述

npm包体中pro-card丢失es目录下的typing.d.ts文件

### 📷 复现步骤

npm install最新版本的ant-design/pro-components
前往node_modules/@ant-design/pro-card/es
发现没有typing.d.ts文件

![image](https://user-images.githubusercontent.com/1585544/236418107-8de77754-08f9-46ce-a787-39fda551bb6c.png)

**Comment by chenshuai2144** [comment]
ref 715c57a1a
