### ISSUE TITLE
👑 [需求] valueType当值为index时，序号能根据当前页的current和pageSize关联计算

### ISSUE THREAD

**Issue by jassonxian** [ant-design/pro-components#702]
### 🥰 需求描述

序号能根据当前页的current和pageSize关联计算；

eg：current = 2， pageSize=10；

序号第一个应该为 11；

**Comment by chenshuai2144** [comment]
自己 render 一下吧，样式太不好写了。一般也不会这么用

**Comment by ChenWeihua123** [comment]
最新版的 proTable columns render函数中 action 中 获取不到current和pageSize了，现在需要在哪里获取呢
render?: (dom: React.ReactNode, entity: T, index: number, action: ProCoreActionType, schema: ProSchema<T, U, Extra>) => React.ReactNode;

**Comment by ChenWeihua123** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
用 受控的方式 ，在 onChange 里 拿一下

**Comment by chhpt** [comment]
@chenshuai2144 表格和 column render 可能是在不同的文件中，onChange 获取并不方便，还是希望能恢复之前的行为
