### ISSUE TITLE
🐛[BUG]Pro Layout组件中Token 自定义header的menu字体颜色不成功

### ISSUE THREAD

**Issue by hexiaomin496** [ant-design/pro-components#7023]
### 🐛 bug 描述

在app.tsx中对Layout进行深度定制：使用了ProLayout的tokenAPI对header进行了定制化。
但其中header的背景色都设置成功，但colorTextMenu、colorTextMenuSelected未如目标效果呈现。

### 📷 复现步骤

如下图的复现代吗，在app.tsx进行了token配置。
得到如下结果。
![image](https://user-images.githubusercontent.com/23149314/236608342-61927b8c-5d3f-44ca-b44b-0192fd3d920a.png)

### 🏞 期望结果

希望可以将menuItem的字体颜色和选中字体颜色进行定制化。

### 💻 复现代码
` token: {
      header: {
        colorBgHeader: '#1677ff',
        colorHeaderTitle: 'rgba(255,255,255,1)',
        colorTextMenu: 'rgba(255,255,255,0.7)',
        // colorTextMenu:'#fff',
        colorTextMenuSelected: '#fff',
        heightLayoutHeader: 48,
        colorTextRightActionsItem: '#fff',
      },
    }`

![image](https://user-images.githubusercontent.com/23149314/236608379-40c173e7-36a1-4011-b2b7-d11fefdc9202.png)

### © 版本信息

- ProComponents 版本: [e.g. 2.4.12]
- umi 版本  [4.0.63]
- 浏览器环境  [Chrome]
- 开发环境 [ mac OS]

**Comment by boiboif** [comment]
一样问题，我是sider menuItem选中颜色设置无效

**Comment by zhengmenghuang** [comment]
插眼

**Comment by zhengmenghuang** [comment]
2.4.14又把2.4.13修复的改坏了

**Comment by chenshuai2144** [comment]
优先级问题，安装下最新版本
