### ISSUE TITLE
ProTable valueType 该怎么实现页面刷新后搜索内容回显并且携带搜索条件

### ISSUE THREAD

**Issue by hyl1374961656** [ant-design/pro-components#7029]
https://codesandbox.io/s/musing-monad-gi7ysz?file=/App.tsx

**Comment by chenshuai2144** [comment]
你要缓存状态嘛？syncUrl 不能实现你的需求？

**Comment by hyl1374961656** [comment]
> 你要缓存状态嘛？syncUrl 不能实现你的需求？

我想实现自定义valueType然后结合protable的syncToUrl使用，但是官网给的例子在页面刷新后并不能回显到form

**Comment by hyl1374961656** [comment]
https://codesandbox.io/s/musing-monad-gi7ysz?file=/NumberInterval.tsx
比如这个案例，我在输入内容点击查询后url里是保存了信息的，然后刷新页面后输出的params里值就是undefined

**Comment by chenshuai2144** [comment]
```
syncToUrl: (values, type) => {
            if (type === "get") {
              console.log(values, "=============");
              return {
                ...values,
                betNum: [values.betBegin, values.betEnd]
              };
            }
            return values;
          },
```

这个 get 和 set 都要设置的，因为url里面没有具体的数据结构，你要转化下

**Comment by hyl1374961656** [comment]
> ```
> syncToUrl: (values, type) => {
>            if (type === "get") {
>              console.log(values, "=============");
>              return {
>                ...values,
>                betNum: [values.betBegin, values.betEnd]
>              };
>            }
>            return values;
>          },
> ```
> 
> 这个 get 和 set 都要设置的，因为url里面没有具体的数据结构，你要转化下

能不能提供个案例呀，实在不清楚用法

**Comment by chenshuai2144** [comment]
自己 debug，上面已经是案例了
