### ISSUE TITLE
🐛[BUG] LightFilter 折叠模式下   折叠icon显示有问题

### ISSUE THREAD

**Issue by datoou** [ant-design/pro-components#7033]
https://codesandbox.io/s/qing-liang-shai-xuan-zhe-die-mo-shi-forked-w9lg5u?file=/App.tsx

ProFormSelect 多选时值是数组就会有问题

![image](https://user-images.githubusercontent.com/52907799/236801409-097572a3-c3b3-40dc-9590-a32d93e4947e.png)

**Comment by chenshuai2144** [comment]
找到问题了，直接来个pr吧
