### ISSUE TITLE
StepForm onCurrentChange触发问题🧐[问题]

### ISSUE THREAD

**Issue by lxfzerolearning** [ant-design/pro-components#7034]
### 🧐 问题描述
 在使用stepForm时一个步骤中内包裹了一个组件，进行下一步时调用该组件的验证方法。当第一次验证不通过时，无法再次触发 onCurrentChange方法
查找一个资料，没有找到一个适当的方法。希望得到一点思路，感谢感谢

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 💡 解决方案
根据你的描述，我理解你在使用 StepForm 组件时遇到了一个问题。当一个步骤中包含一个组件，并且在进行下一步时调用该组件的验证方法时，如果第一次验证不通过，无法再次触发 `onCurrentChange` 方法。

这个问题可能是由于 StepForm 组件内部的逻辑导致的，建议先检查一下你的代码是否正确。

如果问题还未解决，可能需要采取以下的步骤来处理该问题：

1. 确保你的 StepForm 组件的 `onCurrentChange` 方法被正确调用。你可以在该方法内部打印一些调试信息来确认是否被触发。

2. 检查验证方法的逻辑是否正确。验证方法应该返回一个布尔值，表示验证是否通过。如果验证不通过，你可以在方法内部抛出一个错误或者返回`false`，以便在外部处理验证失败的情况。

3. 确认你的验证方法是否与 StepForm 组件的生命周期钩子函数关联起来。可以通过在 `componentDidUpdate` 生命周期钩子函数中检查验证方法的返回值，并根据验证结果来处理相应的逻辑。

4. 如果以上步骤都无法解决问题，你可以尝试使用第三方的表单验证库，如 `formik`、`yup` 或 `antd` 提供的表单验证功能，这些库具有更强大的验证能力和丰富的文档，可以更方便地处理表单验证逻辑。

希望以上提示能对你有所帮助。如果问题还未解决，请提供更多的相关代码和错误信息，以便我们更好地帮助你解决问题。
