### ISSUE TITLE
🐛[BUG] 移动端的菜单样式炸了

### ISSUE THREAD

**Issue by mashirozx** [ant-design/pro-components#7035]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

移动端的菜单样式炸了，见文档上的demo：https://procomponents.ant.design/~demos/packages-layout-src-components-layout-tab-api-demo-mixmode

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/16148054/236981991-c49945a0-21d4-4c0a-8161-e9f85b558816.png">

### 📷 复现步骤

https://procomponents.ant.design/~demos/packages-layout-src-components-layout-tab-api-demo-base?layout=mix&splitMenus=true

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好！感谢您报告移动端菜单样式的问题。根据您提供的描述和截图，我了解到您遇到了菜单样式的错乱问题。我将为您提供一个解决方案。

首先，我建议您检查以下几个方面：

1. 检查您是否在移动端使用了正确的 CSS 样式。确保您的菜单组件能够适应移动端屏幕大小。

2. 检查您是否正确引入了 ProComponents 的相关依赖和样式文件。请确保您在项目中正确引入了 ProComponents 组件，并且应用了所需的样式。

3. 检查您的代码逻辑是否正确。例如，是否正确设置了菜单项的布局和样式。

如果以上检查都没有解决问题，您可以尝试以下解决方案：

1. 确保您在布局组件中正确设置了菜单项的响应式属性。您可以使用 CSS 媒体查询或组件库自带的响应式属性来适配移动端屏幕大小。具体的代码示例如下：

```jsx
import { Menu } from 'pro-components';

function Layout() {
  return (
    <div>
      {/* 其他布局内容 */}
      <Menu
        mode="inline"
        // 添加响应式属性
        responsive={{ minWidth: 576 }}
      >
        {/* 菜单项 */}
      </Menu>
    </div>
  );
}
```

2. 检查您使用的 ProComponents 版本是否最新。如果不是最新版本，尝试升级到最新版本，以确保您能够使用最新的修复和改进功能。

3. 如果您仍然无法解决问题，请尝试在 ProComponents 的 GitHub 仓库中提交一个 issue。在提交 issue 时，请提供尽可能详细的复现步骤、代码示例和截图，让开发者更好地了解和排查问题。

在解决问题的过程中，您可能需要参考 ProComponents 的文档和示例来了解更多关于菜单组件的用法和样式定制。您可以访问以下文档和示例链接：

- ProComponents 官方文档：https://procomponents.ant.design/
- ProComponents 菜单组件文档：https://procomponents.ant.design/components/menu-cn/

希望以上解决方案能够帮助您解决问题。如果您还有任何疑问，请随时向我提问。

**Comment by mashirozx** [comment]
ping @chenshuai2144 

炸了大半年了，产品要上线了，急急急😭

**Comment by mashirozx** [comment]
ping @chenshuai2144 求真人回复

炸了大半年了，产品要上线了，急急急😭

<img width="1624" alt="image" src="https://github.com/ant-design/pro-components/assets/16148054/109b8ccd-0244-4f1d-b396-ad98ddce274a">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常抱歉这么晚回复你，我是一个 AI 助理，无法查看你提到的图片。请确保你提供的链接是正确的，并且可以在公共网络上访问。

关于你的问题，根据你的描述，你遇到了移动端菜单样式的问题，并且已经持续了几个月。这是一种很不幸的情况，我理解你的紧急需求。作为一个 AI 助理，我会尽力提供帮助，但无法处理真实人员的回复。

我推荐你尝试以下几个步骤解决问题：

1. 检查最新版本：确保你正在使用 ProComponents 的最新版本。你可以查看官方文档或仓库来获取最新版本的详细信息。

2. 提交 issue：如果你已经确认你使用的是最新版本，并且问题仍然存在，请在 ProComponents 的 GitHub 仓库中提交一个 issue。在提交 issue 时，请提供明确的复现步骤、代码示例和相关截图，这将有助于开发人员更好地理解和排查问题。

3. 自定义样式：如果你对默认的菜单样式不满意，你可以尝试自定义菜单样式。ProComponents 提供了丰富的样式定制选项，你可以通过修改组件的 CSS 类名或使用内联样式来自定义菜单的外观。

另外，请确保你已经详细阅读了 ProComponents 的文档和示例，以获取更多关于菜单组件的用法和样式定制的信息。如果你遇到了特定的问题或困惑，可以在文档或示例中查找相关部分，并阅读相应的解释和示例代码。

希望以上信息对你有所帮助！如果你还有其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
看起来没问题，是不是你浏览器版本太低了。如果是就要搞下兼容性了、

https://procomponents.ant.design/docs/faq#chrome88-%E4%BB%A5%E4%B8%8B%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E9%97%AE%E9%A2%98

**Comment by mashirozx** [comment]
@chenshuai2144 mix模式下还是有问题，试试把窗口拉窄，打开侧边栏，把页面滚动到下面：
https://procomponents.ant.design/~demos/packages-layout-src-components-layout-tab-api-demo-mixmode

<img width="1624" alt="image" src="https://github.com/ant-design/pro-components/assets/16148054/42e7181e-4cba-4ea0-aa5a-5f3d075509a7">

我用的已经是最新的 chrome 了
<img width="1624" alt="image" src="https://github.com/ant-design/pro-components/assets/16148054/6954bbf7-50c8-4054-85f6-64fd0115998a">

**Comment by chenshuai2144** [comment]
:where(.css-1xpagez).ant-drawer-inline

好像是  antd  加了什么东西，但是我本地没问题

**Comment by mashirozx** [comment]
所以现在演示站是修好了嘛？

**Comment by chenshuai2144** [comment]
演示好像一直是好的

**Comment by mashirozx** [comment]
好嘛，刚刚那会儿好像忽然好了，现在又不对了🥲

请问大佬这边近期打算修吗？不修改的话我就得自己魔改了

**Comment by hyl1374961656** [comment]
问题依然存在

**Comment by hyl1374961656** [comment]
@chenshuai2144 
https://codesandbox.io/p/sandbox/fy5gxw这个就是演示里的demo
![Image](https://github.com/user-attachments/assets/41fbc33f-cefa-4187-90ff-f9fbafaf0066)

**Comment by hyl1374961656** [comment]
@chenshuai2144
