### ISSUE TITLE
ProList metas配置valueType: 'select'时，placement没有起作用🧐[问题]

### ISSUE THREAD

**Issue by dwdc529** [ant-design/pro-components#7039]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
页面上有个列表组件要显示在屏幕右侧，列表的select搜索项默认弹出位置在左侧，这样会产生滚动条，右侧宽度也会超出。
我在ProList 组件配置metas，filterType: 'light'，设置 valueType: 'select' ，在fieldProps 中配置了弹出位置placement为bottomRight，但是不生效。
在文档中找了一圈，不确定是placement属性配置错了还是什么？

### 💻 示例代码

const metas = {
  user_id: {
        title: '用户',
        dataIndex: 'user_id',
        valueType: 'select',
        request: () => _.values(userNameData.current),
        fieldProps: { showSearch: true, placement: 'bottomRight' },
   },
   ......
}

演示：
https://codesandbox.io/s/happy-river-80ubco?file=/App.tsx

### 🚑 其他信息

_官方的钉钉群或其它群谁有？网上的二维码都过期了_

版本：
 "antd": "^4.24.8",
"react": "^17.0.0",
"umi": "^3.5.0"

系统：
windows 11

客户端：
Chrome 111.0.5563.65

截图：
![image](https://user-images.githubusercontent.com/12961611/236986938-f624f9b3-4ad3-413c-99f1-df45dd99d292.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi there! 我是 GitHub 的 issue 助理，专门处理关于 React 前端问题的。看到你的问题了，关于 ProList 组件中 metas 配置的 valueType 为 select 时，设置的 placement 属性不起作用的问题。

根据你提供的代码和截图，placement 属性应该是没有被正确应用到 Select 组件上。经过查阅文档和代码，我发现在 ProList 组件中的 valueType 为 select 时，并不能直接通过 fieldProps 来配置 Select 组件的属性，而是需要使用 fieldProps 里的 formItemProps 属性来配置。

你可以修改你的代码如下：

```jsx
const metas = {
  user_id: {
    title: '用户',
    dataIndex: 'user_id',
    valueType: 'select',
    request: () => _.values(userNameData.current),
    fieldProps: {
      showSearch: true,
      formItemProps: {
        style: { textAlign: 'right' }, // 设置样式，达到 placement 为 bottomRight 的效果
        placement: 'bottomRight', // 设置弹出位置为 bottomRight
      },
    },
  },
  // 其他字段...
};
```

你可以在 ProList 组件的 fieldProps 里的 formItemProps 属性中添加样式属性，例如 textAlign 来设置弹出框右对齐。然后将 placement 属性放在 formItemProps 中配置。

希望以上解决方案能够帮助到你！如果还有其他问题，请随时告诉我。

**Comment by chenshuai2144** [comment]
![lQDPJyCgparmknLNBP_NBEOw1UJXJCQ43l0EqU-PuwA5AA_1091_1279](https://github.com/ant-design/pro-components/assets/8186664/01f41a7d-1857-47e8-a842-4425131aa4a6)
