### ISSUE TITLE
两个单纯的ProTable，在tabs标签下切换，protable会抖动，底部footer也会抖动，代码如下:

### ISSUE THREAD

**Issue by wanxiaoshengwanxiaosheng** [ant-design/pro-components#7040]
```
   <div style={{ position: 'sticky', top: 0, margin: 0 }}>
      <Tabs defaultActiveKey="1" >
        <TabPane tab="汽运计划" key="10">
          <ProTable headerTitle="测试1"  />
        </TabPane>
        <TabPane tab="备料计划" key="11">
          <ProTable headerTitle="测试2" />
        </TabPane>
      </Tabs>
    </div>
```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您提供的代码片段。根据您的代码，问题可能出现在滚动时导致ProTable和底部footer抖动的情况。这可能是因为ProTable的高度在切换tab时发生变化，导致页面布局产生抖动。

为了解决这个问题，您可以尝试以下几个解决方案：

1. 针对ProTable设置固定高度：您可以在ProTable的外层div上设置固定的高度，以确保在切换tab时，ProTable的高度不会改变。例如：

```jsx
<ProTable headerTitle="测试1" style={{ height: '400px' }} />
```

2. 使用CSS的`will-change`属性：通过将`will-change`属性应用于ProTable组件，可以让浏览器在动画开始之前优化相关元素的渲染。这可以减少抖动问题。您可以尝试在ProTable所在的div上添加`will-change`属性，例如：

```jsx
<div style={{ willChange: 'transform' }}>
  <ProTable headerTitle="测试1" />
</div>
```

请注意，以上解决方案可能需要根据您页面的具体布局和需求进行调整。同时，为了提供更准确的答案，您可能需要提供更多的代码和具体的错误表现。

关于以上解决方案的更多细节和其他解决方案，您可以参考以下资源：

- ProTable文档：https://procomponents.ant.design/components/table-cn

希望能帮助到您！如果您有任何其他问题，请随时提问。
