### ISSUE TITLE
🐛[BUG]两个单纯的ProTable，在tabs标签下切换

### ISSUE THREAD

**Issue by wanxiaoshengwanxiaosheng** [ant-design/pro-components#7041]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

@umijs/max": "^4.0.52",版本 antd design pro ，两个单纯的ProTable，在tabs标签下切换，protable会抖动，底部footer也会抖动

### 🏞 期望结果

切换不抖动

### 💻 复现代码
 <div style={{ position: 'sticky', top: 0, margin: 0 }}>
      <Tabs defaultActiveKey="1" >
        <TabPane tab="汽运计划" key="10">
          <ProTable headerTitle="测试1"  />
        </TabPane>
        <TabPane tab="备料计划" key="11">
          <ProTable headerTitle="测试2"  />
        </TabPane>
      </Tabs>
    </div>

### © 版本信息

- ProComponents 版本: 2.3.57
- umi 版本    umijs4,
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/89174214/237026783-c72658d1-2fe3-4796-bbe8-14184c66556d.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！根据你的问题描述和提供的代码，问题可能出现在 ProTable 在 tabs 标签下切换时抖动的情况。为了解决这个问题，你可以尝试以下几个方案：

1. 确保你的项目依赖项已经更新到最新版本，尤其是 "@umijs/max" 和 "ProComponents"。你可以使用 `npm update` 命令来更新依赖项。

2. 尝试在你的 ProTable 组件中添加一个固定的高度，可以使用样式来实现。这可以防止在切换 tabs 时发生抖动。你可以尝试如下代码：

```jsx
<ProTable headerTitle="测试1" style={{ height: 400 }} />
```

3. 如果上述方法无效，你可以尝试使用 `useEffect` 钩子函数来延迟加载 ProTable 组件。这样可以确保在切换 tabs 时，ProTable 组件已经完全加载并正确渲染。你可以尝试如下代码：

```jsx
import React, { useEffect, useState } from 'react'
import { Tabs } from 'antd'
import ProTable from 'your-protable-component'

const { TabPane } = Tabs

const YourComponent = () => {
  const [activeKey, setActiveKey] = useState('10')

  useEffect(() => {
    // 根据你的实际需求来决定何时加载 ProTable 组件
    // 这里仅提供一个示例
    setTimeout(() => {
      setActiveKey('10')
    }, 200)
  }, [])

  const handleTabChange = (key) => {
    setActiveKey(key)
  }

  return (
    <div>
      <Tabs activeKey={activeKey} onChange={handleTabChange}>
        <TabPane tab="汽运计划" key="10">
          {activeKey === '10' && <ProTable headerTitle="测试1" />}
        </TabPane>
        <TabPane tab="备料计划" key="11">
          {activeKey === '11' && <ProTable headerTitle="测试2" />}
        </TabPane>
      </Tabs>
    </div>
  )
}

export default YourComponent
```

请注意，以上方案仅供参考。如果仍然存在问题，请确保你已仔细阅读 ProComponents 的文档和 GitHub 问题页面，查看是否有其他人遇到相似的问题并提供了解决方案。如果问题仍然存在，建议你在 GitHub 的 ProComponents 仓库中提出一个 issue，以便得到更专业的帮助。

希望能帮到你！

**Comment by chenshuai2144** [comment]
试试 把 tabs 的动画关掉试试
