### ISSUE TITLE
🐛[BUG]ProTable，Columns的valueType是dateRange，时间选择框偏移出屏幕外，导致无法选择

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#7043]
![image](https://github.com/ant-design/pro-components/assets/12421552/f05367c6-12fb-48dd-ace1-5cca363b5411)

![image](https://github.com/ant-design/pro-components/assets/12421552/81ae0c73-2db9-4f9d-85b8-96a8e2539898)

"@ant-design/pro-components": "^2.3.57",

**Comment by edifangyi** [comment]
"@ant-design/pro-components": "^2.4.16",

升级了也不得行，没有办法自适应，导致日期选择框一直是靠左打开，一半的选择框被盖住了

现在的解决方法只能是 设置 fieldProps -> placement: 'bottomRight'，凑活用。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，

针对ProTable中Columns的valueType为dateRange时时间选择框偏移出屏幕外的问题，您可以尝试以下解决方案：

1. 使用最新版本的"@ant-design/pro-components"：请确保您的依赖包的版本是最新的。您提到的版本为"^2.4.16"，请检查是否有更高的版本可用。可以使用以下命令更新依赖包：

   ```
   npm install @ant-design/pro-components@latest
   ```

2. 调整选择框的位置：尝试调整选择框的显示位置，从而避免偏移问题。您可以尝试设置fieldProps中的placement属性为'bottomRight'，示例如下：

   ```jsx
   import ProTable from '@ant-design/pro-table';
   import { DatePicker } from 'antd';
   
   const columns = [
     {
       title: '日期范围',
       dataIndex: 'dateRange',
       valueType: 'dateRange',
       fieldProps: {
         placement: 'bottomRight',
       },
       renderFormItem: (_, { defaultRender }) => {
         return <DatePicker.RangePicker />;
       },
     },
   ];
   
   // 在ProTable组件中使用columns
   <ProTable columns={columns} />
   ```

   通过将选择框位置设置为'bottomRight'，可以尝试解决选择框偏移的问题。

另外，如果以上解决方案无效，建议您查看相关的官方文档或提交一个issue给该组件的维护者，以便他们能够提供更具体的解决方案。

希望以上信息能对您有所帮助！如果您有任何问题，请随时提问。
