### ISSUE TITLE
🐛[BUG] 2.4.14 layout中部分token依然不生效

### ISSUE THREAD

**Issue by chenyanxiself** [ant-design/pro-components#7046]
### 🐛 bug 描述

2.4.14中layout token优先级有问题, colorTextMenuActive以及colorTextMenuSelected不生效, 在点击menu的情况下字体颜色依旧沿用colorTextMenu

### 💻 复现代码

![image](https://github.com/ant-design/pro-components/assets/48513344/568b53d4-a4b6-4f6e-ac67-6ced20da3077)

![image](https://github.com/ant-design/pro-components/assets/48513344/0ac35bb7-15d5-4397-9da1-701abccb3b81)

### © 版本信息

- "@ant-design/pro-components": "^2.4.14"
- "@umijs/max": "^4.0.57"
- Chrome
- Windows 10

**Comment by zhengmenghuang** [comment]
.ant-menu-item-selected * {
  color: var(--color-primary);
}

**Comment by zhengmenghuang** [comment]
2.4.15 没有修复

**Comment by zhengmenghuang** [comment]
2.4.16 已修复

**Comment by chenshuai2144** [comment]
colorTextMenuActive 这个应该是在 antd@5 中不需要了，我会删掉它
