### ISSUE TITLE
valueTypes使用digit,会默认显示两位小数，而且查询的字段会自动变成千位符，怎么用整数呢

### ISSUE THREAD

**Issue by garwer** [ant-design/pro-components#705]
问题如上

**Comment by chenshuai2144** [comment]
来个图

**Comment by garwer** [comment]
[](url)
![52A6C7AE-3197-4A2B-B085-6017B2D90DB7](https://user-images.githubusercontent.com/29226511/95840474-c5c11700-0d76-11eb-90d2-436b3dfa2ded.png)

**Comment by chenshuai2144** [comment]
这个不应该用数字格式吧，用 text 就好了

**Comment by garwer** [comment]
先用text好了，谢谢哈(老哥，其实我就是想在前端限制数字不想再做校验才不用text的 -0- )。

**Comment by gaofei019** [comment]
同问
