### ISSUE TITLE
🧐[问题]用什么控件可以达到“点击搜索后才展示对应的内容”

### ISSUE THREAD

**Issue by Twinkle123321** [ant-design/pro-components#7050]
我想实现的功能：点击搜索后，就在表格里展示对应的内容，请问我应该用什么控件呢？
准备用proTable，发现不知道如何让所有的table数据默认不展示（达到点击搜索后，才展示对应内容的效果）。 
我这里用的是ProFormSelect，却又不知道怎么【点击搜索后才展示对应的数据】。 希望有大佬可以帮忙解答一下，感谢🙏！！！
![image](https://github.com/ant-design/pro-components/assets/32992310/9715cf6c-85ff-4341-ba52-5278b4d4e716)

**Comment by tjj727** [comment]
判断params除分页参数外是否为空就行了

**Comment by ldwonday** [comment]
Protable的manualRequest参数了解下。
