### ISSUE TITLE
ProTable使用编辑功能，修改tableListDataSource，UI没有对应修改🐛[BUG]

### ISSUE THREAD

**Issue by Mrheqiang** [ant-design/pro-components#7056]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProTable使用编辑功能，当外部动态修改了tableListDataSource，ProTable的UI没有对应的修改。如果将startEditable一行注释掉，那么ProTable的UI可以正常变换

### 📷 复现步骤
进入页面，点击改变数据，查看表格数据的第一列input的value，在控制台中可以明确的看到数据已经修改，但是UI并未修改

### 🏞 期望结果
点击改变数据后，ProTable使用编辑功能后，也能正确的修改对应的UI

### 💻 复现代码
https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-v2fslx?file=/App.tsx:2530-2708

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


嗨，感谢您向我们提出问题！

根据您的描述，我了解到您使用ProTable的编辑功能时，发现当您外部动态修改了tableListDataSource时，ProTable的UI没有相应地更新。如果您将startEditable一行注释掉，那么ProTable的UI可以正常更新。

我建议您检查一下您的代码，确保以下几点：

1. 确保您正确地更新了tableListDataSource数据源。您可以通过在控制台中打印tableListDataSource来确认数据是否被修改了。

2. 确保您使用的是最新版本的ProComponents。您可以通过查询ProComponents的版本号来确认。

3. 确保您没有遗漏任何必要的配置或参数。您可以查阅ProTable的文档，了解关于编辑功能的详细配置和参数信息。

以下是一些可能会帮助您解决问题的代码示例：

```typescript
import { useState } from 'react';
import ProTable, { TableEditableRow } from '@ant-design/pro-table';

export default function App() {
  const [tableListDataSource, setTableListDataSource] = useState([]);

  const handleDataChange = (newData) => {
    setTableListDataSource(newData);
  };

  return (
    <ProTable
      dataSource={tableListDataSource}
      editable={{
        type: 'multiple',
        onChange: handleDataChange,
        rowEditable: (record) => { /* 根据您的需求进行设置 */ },
      }}
      columns={[
        { title: 'Name', dataIndex: 'name' },
        { title: 'Age', dataIndex: 'age', editable: true },
        // 其他列配置...
      ]}
    />
  );
}
```

如果问题仍然存在，请提供更多的代码示例，特别是与tableListDataSource相关的代码，以便我们更好地理解和复现问题。

希望我的回答能够解决您的问题！如果您有任何其他疑问，请随时提问。

**Comment by chenshuai2144** [comment]
要使用  form setfieldValue  来进行设置，form  是通过  onchange  进行数据同步的， 如果不通过setfieldValue设置，数据可能会不同步
