### ISSUE TITLE
ProFormDigit addonBefore/addonAfter的值为ProFormSelect时显示异常🐛[BUG]

### ISSUE THREAD

**Issue by dwdc529** [ant-design/pro-components#7060]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProFormDigit addonBefore/addonAfter的值为ProFormSelect组件时，addon渲染出来的ant-form-item margin导致页面上两个组件不能水平居中

### 📷 复现步骤

线上示例
https://codesandbox.io/s/biao-dan-xiang-forked-4nw405?file=/App.tsx

### 🏞 期望结果

水平对齐

### 💻 复现代码

<ProFormDigit
        label="InputNumber"
        name="input-number"
        width="sm"
        min={1}
        max={10}
        addonBefore={
          <ProFormSelect
            name="select"
            valueEnum={{
              china: "China",
              usa: "U.S.A"
            }}
            placeholder="Please select a country"
            rules={[
              { required: true, message: "Please select your country!" }
            ]}
          />
        }
  />

### © 版本信息

- ProComponents 版本: [2.3.17]
- umi 版本 ^3.5.0
- 浏览器环境 chrome 111.0.5563.65
- 开发环境 [windows 11] 

### 🚑 其他信息
![image](https://github.com/ant-design/pro-components/assets/12961611/4982ee60-71b0-4b27-a42c-10ea8cf378b2)

![image](https://github.com/ant-design/pro-components/assets/12961611/34b7e37d-fcc4-4f64-9b06-b51c18e32ca9)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi there! 感谢您向我们的 GitHub issue 助理寻求帮助。我很抱歉，根据您的描述，这似乎不是一个关于 React 前端问题的问题。我只能处理关于 React 的前端问题。如果您有其他关于 React 前端的问题，请随时提问，我将竭诚为您提供帮助。

如果您的问题涉及其他方面或其他技术，请提供更多详细信息，以便我可以更好地帮助您。谢谢！
