### ISSUE TITLE
🐛[BUG] .ant-page-header 样式偶尔会丢失，需要浏览器刷新页面后恢复正常

### ISSUE THREAD

**Issue by hooliy** [ant-design/pro-components#7061]
样式偶尔会丢失，需要浏览器刷新页面后恢复正常

### 🐛 bug 描述

<img width="384" alt="image" src="https://github.com/ant-design/pro-components/assets/3368691/883108e6-7985-4722-be0f-b6cada6af2d1">

<img width="464" alt="image" src="https://github.com/ant-design/pro-components/assets/3368691/2befda6b-64b2-46e5-be4f-e79956a9dc8e">

### 📷 复现步骤

操作过程中偶尔会出现此现象，无法复现。

**Comment by lzm0x219** [comment]
mark

**Comment by 7ingning** [comment]
![1684290040302](https://github.com/ant-design/pro-components/assets/131357495/d854636d-539f-425d-a037-c1861f5ee616)
部分组件出现样式丢失，偶现，初次加载页面复现概率大

**Comment by wppeng520** [comment]
我也遇到过，发现，跳到404页面，在返回后很容易出现PageContainer组件面包屑样式就没了

**Comment by cmKangkang** [comment]
我也遇到过，路由来回切换后 ProTable 的 actionBar 样式没了

**Comment by isliqian** [comment]
这个怎么解决？切换页面的时候样式丢失了

**Comment by helloJincheng** [comment]
怎么解决呢

**Comment by chenshuai2144** [comment]
<img width="340" alt="image" src="https://github.com/ant-design/pro-components/assets/8186664/e1cae04a-63e0-4364-a59a-cab18e9a2514">

18 和 17 的渲染时序不一样导致的。大家可以升级到  18 试试

**Comment by hooliy** [comment]
> <img alt="image" width="340" src="https://user-images.githubusercontent.com/8186664/253893884-e1cae04a-63e0-4364-a59a-cab18e9a2514.png">
> 18 和 17 的渲染时序不一样导致的。大家可以升级到 18 试试

18也是存在同样的问题的

**Comment by hooliy** [comment]
一直用的都是18 , 问题始终存在

<img width="270" alt="image" src="https://github.com/ant-design/pro-components/assets/3368691/07a0d1bb-7c12-4e7c-aa88-15529ae26fca">

**Comment by hooliy** [comment]
刚把 pro-components  ,  antd 和 react 都升级到最新版了, 暂无发现问题, 用一段时间再来反馈是否还存在问题

**Comment by Tomfish0902** [comment]
同样发现问题 感觉与history.push有关 @chenshuai2144
