### ISSUE TITLE
🧐[问题]EditableProTable 的 formItem 如何去除input的空格

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/pro-components#7066]
```jsx

const columns= [
 {
    title: '事件名称',
    dataIndex: 'event_name',
    key: 'event_name',
    formItemProps: () => { // 这种用法无效
      return {
        transform: (value: string) => {
          console.log('event_name', value)

          return value?.trim?.()
        },
      }
    },
  },
]


<EditableProTable
            bordered
          
     
            columns={columns}
            rowKey="id"
          />
```

**Comment by varown** [comment]
问题可以描述清楚点，不是很理解

**Comment by varown** [comment]
const columns = [
  {
    title: '事件名称',
    dataIndex: 'event_name',
    key: 'event_name',
    formItemProps: () => {
      return {
        rules: [
          {
            validator(_, value) {
              if (value && /\s/.test(value)) {
                return Promise.reject(new Error('空格不允许输入'))
              }
              return Promise.resolve()
            },
          },
        ],
      }
    },
  },
]
建议使用这个禁止输入

**Comment by varown** [comment]
```
const columns: ProColumns<DataType>[] = [
  {
    title: '事件名称',
    dataIndex: 'event_name',
    key: 'event_name',
    renderFormItem: (_, { value, onChange }) => (
      <Input
        value={value}
        onChange={(e) => {
          const newValue = e.target.value.trim();
          onChange(newValue);
        }}
      />
    ),
  },
];
```
这个也可以满足你的需求

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


对于EditableProTable组件中的formItem，你可以使用renderFormItem属性来自定义输入框的样式和行为。为了去除输入内容中的空格，你可以在renderFormItem中进行处理。

以下是一个示例代码：

```jsx
import { EditableProTable, ProColumns } from '@ant-design/pro-table';
import { Input } from 'antd';

type DataType = {
  event_name: string;
};

const columns: ProColumns<DataType>[] = [
  {
    title: '事件名称',
    dataIndex: 'event_name',
    key: 'event_name',
    renderFormItem: (_, { value, onChange }) => (
      <Input
        value={value}
        onChange={(e) => {
          const newValue = e.target.value.trim();
          onChange(newValue);
        }}
      />
    ),
  },
];

const YourComponent = () => {
  return (
    <EditableProTable
      bordered
      columns={columns}
      rowKey="id"
    />
  );
};
```

在上述代码中，我们使用Input组件来作为编辑时的输入框，通过onChange事件监听输入值的变化。在onChange事件处理函数中，我们使用`e.target.value.trim()`来去除输入内容中的空格，并将处理后的值通过onChange方法传递给EditableProTable组件。

这样，用户在表格中输入内容时输入框中的空格将被自动去除。

**Comment by chenshuai2144** [comment]
transform 只有在提交的时候生效，不会在 onchange 的时候生效的，你需要重写一个onchange 方法
