### ISSUE TITLE
🧐[问题]文档可以不可以搞一个国内镜像，打开太慢了

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/pro-components#7069]
### 🧐 问题描述

文档可以不可以搞一个国内镜像，打开太慢了
这个站
https://procomponents.ant.design/
doc目录里面内容又不全，看起来真的很费劲。
ant design都有
https://ant-design.antgroup.com/

**Comment by haobarry** [comment]
翻墙解决

**Comment by ideaviewes** [comment]
> 翻墙解决

有没有什么好的工具呀，
搞不懂，明明是个国内的项目，非要把网站放到境外的服务器，而且还是中文

**Comment by ONLY-yours** [comment]
mark

**Comment by ideaviewes** [comment]
不用等什么国内镜像了
把这个项目clone到本地，编译一下，dist目录就是

**Comment by mashirozx** [comment]
慢的要死，我梯子上其他网站都是很快的，唯独这个页面每次等半天打不开

![image](https://github.com/ant-design/pro-components/assets/16148054/8bbc5a7c-eb3b-4c22-b42e-c93fc496e780)
