### ISSUE TITLE
🧐[问题]接口数据格式为 {data:Array, success:Boolean, total:number, summary: any}, 在Table的Footer里如何获取 summary的数据？

### ISSUE THREAD

**Issue by America-first-melon** [ant-design/pro-components#707]
### 🧐 问题描述

footer 拿不到 每次拿到的都是 current page data, 难道需要把summary再挂到data里？

postData 貌似也不行

**Comment by chenshuai2144** [comment]
要用 postData  存下来，然后再设置进去了

**Comment by America-first-melon** [comment]
postData 保存之后  再分别设置 Table 的DataSource pagination 这些吗

**Comment by chenshuai2144** [comment]
@America-first-melon  嗯，或者再request 的时候存一下，protable 不支持多余的参数

**Comment by America-first-melon** [comment]
> @America-first-melon 嗯，或者再request 的时候存一下，protable 不支持多余的参数

谢谢
