### ISSUE TITLE
🧐[问题] @ant-design/pro-components 中的 resetButtonProps 中未发现能展示重置按钮的配置

### ISSUE THREAD

**Issue by wellsmitch** [ant-design/pro-components#7072]
@ant-design/pro-components 中的 resetButtonProps 中未发现能展示重置按钮的配置
\node_modules\_@ant-design_pro-form@2.11.7@@ant-design\pro-form\es\components\Submitter\index.d.ts 中未发现相关API敬请赐教

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！感谢你的问题。根据你提供的信息，@ant-design/pro-components 中的 resetButtonProps 并没有直接提供展示重置按钮的配置选项。但是你可以使用其他方式来实现这个功能。以下是一种可能的解决方案：

1. 在表单组件中，使用 `ProForm` 组件包裹表单字段和按钮：

```jsx
import { ProForm, ProFormText, ProFormResetButton, ProFormSubmitButton } from '@ant-design/pro-form';

const MyForm = () => {
  const handleSubmit = (values) => {
    // 处理表单提交逻辑
  };

  const handleReset = () => {
    // 重置表单逻辑
  };

  return (
    <ProForm onFinish={handleSubmit}>
      <ProFormText name="name" label="名称" />
      {/* 其他表单字段 */}

      <ProFormResetButton onReset={handleReset} />

      <ProFormSubmitButton>提交</ProFormSubmitButton>
    </ProForm>
  );
};
```

2. 在上面的示例中，我们使用了 `ProFormResetButton` 组件，并传递了一个 `onReset` 回调函数来处理重置逻辑。你可以在该回调函数中执行你希望的重置操作，比如清空表单字段的值。

这是一个基本的示例，你可以根据需要自定义表单字段、按钮样式等。更多关于 @ant-design/pro-form 的使用方法，你可以参考官方文档：https://procomponents.ant.design/components/form

希望这个解决方案对你有帮助！如果你有任何其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
<img width="709" alt="image" src="https://github.com/ant-design/pro-components/assets/8186664/28a7bf6d-1e44-4fa6-a476-55740111494c">


`resetButtonProps=false`
