### ISSUE TITLE
ProTable 如何设置默认的 defaultPageSize 🧐[问题]

### ISSUE THREAD

**Issue by yjcvme89** [ant-design/pro-components#7074]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
默认的 pageSize 是 20，我想修改为默认 pageSize 为 100，应该怎么修改

**Comment by kaishuige** [comment]
pagination={{
          defaultPageSize: 10,
        }}

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你可以在 ProTable 组件的 `pagination` 属性中设置 `defaultPageSize` 来修改默认的 `pageSize` 值。将 `defaultPageSize` 的值设为你期望的默认值即可。下面是一个示例代码：

```jsx
import ProTable from '@ant-design/pro-table';

const columns = [
  // 列定义...
];

const data = [
  // 数据...
];

const MyTable = () => {
  return (
    <ProTable
      columns={columns}
      dataSource={data}
      pagination={{
        defaultPageSize: 100,
      }}
    />
  );
};

export default MyTable;
```

在上面的示例中，我们将 `pagination` 属性的 `defaultPageSize` 设置为 100，即将默认的 `pageSize` 修改为 100。

关于 ProTable 的更多用法和配置，你可以参考官方文档：[ant-design/pro-table](https://procomponents.ant.design/components/table)。这个文档中提供了 ProTable 的详细介绍、示例代码和API文档，可以帮助你更好地使用这个组件。
