### ISSUE TITLE
🐛[BUG] DrawerForm，刚打开就进行必输校验

### ISSUE THREAD

**Issue by yuweiqi1995** [ant-design/pro-components#7077]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

第一个ProFormText设置必选，并且validateTrigger为onBlur，打开抽屉就会进行必输校验

### 🏞 期望结果

打开抽屉不进行必输校验

### 💻 复现代码

import { PlusOutlined } from '@ant-design/icons';
import {
  DrawerForm,
  ProForm,
  ProFormDateRangePicker,
  ProFormSelect,
  ProFormText,
} from '@ant-design/pro-components';
import { Button, Form, message } from 'antd';

const waitTime = (time: number = 100) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(true);
    }, time);
  });
};

export default () => {
  const [form] = Form.useForm<{ name: string; company: string }>();

  return (
    <DrawerForm<{
      name: string;
      company: string;
    }>
      title="新建表单"
      form={form}
      trigger={
        <Button type="primary">
          <PlusOutlined />
          新建表单
        </Button>
      }
      autoFocusFirstInput
      drawerProps={{
        destroyOnClose: true,
      }}
      submitTimeout={2000}
      onFinish={async (values) => {
        await waitTime(2000);
        console.log(values.name);
        message.success('提交成功');
        // 不返回不会关闭弹框
        return true;
      }}
    >
      <ProForm.Group>
        <ProFormText
          rules={[
            {
              required: true,
            },
          ]}
          validateTrigger="onBlur"
          width="md"
          name="company"
          label="我方公司名称"
          placeholder="请输入名称"
        />
      </ProForm.Group>
    </DrawerForm>
  );
};

### © 版本信息

- ProComponents 版本: [2.3.54]
- umi 版本 4.0.51
- 浏览器环境 Chrome 113.0.5672.64（正式版本） （64 位）
- 开发环境 [windows]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！根据你的描述，问题在于打开抽屉时会进行必输校验，而你希望只在离开文本框时进行校验。你可以尝试使用 `validateTrigger="onSubmit"` 来实现该需求。修改代码如下：

```jsx
<ProFormText
  rules={[
    {
      required: true,
    },
  ]}
  validateTrigger="onSubmit"
  width="md"
  name="company"
  label="我方公司名称"
  placeholder="请输入名称"
/>
```

这样，只有在点击提交按钮后才会进行必输校验。

另外，你提到的 `ProForm` 组件可用于快速生成表单，但你的代码中并没有使用到该组件。如果你需要使用 `ProForm`，可以参考以下代码示例：

```jsx
import { ProForm, ProFormDateRangePicker, ProFormSelect, ProFormText } from '@ant-design/pro-form';
import { Button, Drawer, message } from 'antd';

const waitTime = (time: number = 100) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(true);
    }, time);
  });
};

export default () => {
  const [form] = Form.useForm<{ name: string; company: string }>();

  return (
    <Drawer
      title="新建表单"
      visible={true} // 设置为true即可打开抽屉
      onClose={() => {
        // 关闭抽屉的逻辑
      }}
    >
      <ProForm
        form={form}
        initialValues={{
          // 设置表单的初始值
          name: '',
          company: '',
        }}
        onFinish={async (values) => {
          await waitTime(2000);
          console.log(values.name);
          message.success('提交成功');
          // 不返回不会关闭抽屉
          return true;
        }}
      >
        <ProFormText
          rules={[
            {
              required: true,
            },
          ]}
          validateTrigger="onBlur"
          label="公司名称"
          name="company"
        />
      </ProForm>
      <div style={{ marginTop: 24 }}>
        <Button type="primary" htmlType="submit" onClick={() => form.submit()}>
          提交
        </Button>
      </div>
    </Drawer>
  );
};
```

你可以根据实际需求进行适当调整。希望对你有帮助！如果还有其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
可以设置这个关掉
| 参数 | 说明 | 类型 | 默认值 |
| --- | --- | --- | --- |
| autoFocusFirstInput | 自动 focus 表单第一个输入框 | `boolean` | - |
