### ISSUE TITLE
🐛[BUG]轻量筛选使用多选时设置显示最大tag数无效

### ISSUE THREAD

**Issue by Zoe-Lu** [ant-design/pro-components#7079]
![image](https://github.com/ant-design/pro-components/assets/77383426/a0a6805b-ae18-46a5-ac5a-8536246818e9)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi! 感谢您报告的问题。根据您提供的截图和描述，看起来您是在使用 `ant design` 的 `pro-components` 库中的轻量筛选组件时遇到了问题。

根据您的描述，您正在尝试使用多选模式，并设置了最大显示标签数，但是该设置似乎没有生效。

针对这个问题，您可以尝试以下解决方案:

1. 确保您使用的是最新版本的 `ant design` 和 `pro-components` 库。您可以通过更新依赖项来解决可能存在的 bug，例如在您的 `package.json` 文件中运行`npm update ant-design pro-components`命令。

2. 确保您正确配置了 `<ProFormSelect>` 组件的 `maxTagCount` 属性。您可以尝试将其设置为一个较小的值，例如 `2`，并检查是否仍然存在问题。

```jsx
<ProFormSelect
  mode="multiple"
  maxTagCount={2}
  // other props...
/>
```

3. 如果上述解决方案仍然不起作用，您可以尝试手动处理多选的标签显示，并使用 `Tooltip` 组件来显示被截断的标签。这样您将完全控制标签的显示方式。

```jsx
import { ProFormSelect, Tooltip } from '@ant-design/pro-components';

function ExampleComponent() {
  const options = [ /* options for select */ ];
  const value = [ /* selected values */ ];

  return (
    <ProFormSelect
      mode="multiple"
      value={value}
      // other props...
      render={() => {
        return value.map((val, index) => {
          // 控制显示的标签数量
          if (index < 2) {
            return (
              <Tooltip title={val} key={val}>
                <span>{val}</span>
              </Tooltip>
            );
          } else if (index === 2) {
            return (
              <Tooltip title={`+ ${value.length - 2} more`} key={val}>
                <span>{val}</span>
              </Tooltip>
            );
          } else {
            return null;
          }
        });
      }}
    />
  );
}

export default ExampleComponent;
```

这些解决方案应该可以帮助您解决问题。如果没有解决您的问题，请提供更多的细节或代码，以便我可以更好地帮助您。同时，您还可以参考 `ant design` 和 `pro-components` 的官方文档以获取更多信息：

- `ant design` 文档：https://ant.design/docs/react/introduce-cn
- `pro-components` 文档：https://github.com/ant-design/pro-components

**Comment by chenshuai2144** [comment]
只有  tag  模式才能设置。



maxTagCount | 最多显示多少个 tag，响应式模式会对性能产生损耗 | number \| responsive | - | responsive: 4.10
-- | -- | -- | -- | --
maxTagPlaceholder | 隐藏 tag 时显示的内容 | ReactNode \| function(omittedValues) | - |  
maxTagTextLength | 最大显示的 tag 文本长度 | number

**Comment by MMMMoriaty** [comment]
我也遇到了这个问题，并不是只有tag模式才能设置，单独的ProFormSelect是可以work的，但是外面包了LightFilter或者设置light为true的时候maxTagCount就失效了，可以看下是不是lightSelect里是不是哪里逻辑除了问题
