### ISSUE TITLE
ProFormText 设置hidden 属性导致 name 无效 🐛[BUG]

### ISSUE THREAD

**Issue by myloveGy** [ant-design/pro-components#7082]
### 🐛 bug 描述

![企业微信截图_8dd45fe7-314a-4455-bbaf-25b30fbe39a1](https://github.com/ant-design/pro-components/assets/11523869/e0406798-b6bd-4f3c-8848-e1a0513d6b7c)

![企业微信截图_727ff2b9-05d2-46ee-bafc-88a8574e080d](https://github.com/ant-design/pro-components/assets/11523869/ad8d80aa-18a4-4f14-bddd-ea9c99725ed6)

### 🏞 期望结果

name 属性需要渲染出来

### © 版本信息

- ProComponents 版本: @ant-design/pro-form 2.12.0
- umi 版本 ^3.5.36
- 浏览器环境 Chrome
- 开发环境 [e.g. mac OS]

**Comment by hans000** [comment]
你不用hidden它也没效果啊，name是form的专用选项，input的属性需要在fieldProps里配置
