### ISSUE TITLE
🐛[BUG]配置valueType: "dateRange"时，清空后没有按照transform字段要求输出

### ISSUE THREAD

**Issue by frankcou** [ant-design/pro-components#7085]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

清空后没有出现transform里面配置的对象

### 📷 复现步骤

1.选择时间，提交。
2.点击选择框后的清空，清空时间

### 🏞 期望结果

空值打印`{startTime:1,endTime:2}`

### 💻 复现代码

```
import type { ProFormColumnsType } from "@ant-design/pro-components";
import { BetaSchemaForm } from "@ant-design/pro-components";

const columns: ProFormColumnsType[] = [
  {
    title: "创建时间",
    dataIndex: "created_at",
    valueType: "dateRange",
    transform: (value) => {
      return {
        startTime: value[0] || 1,
        endTime: value[1] || 2
      };
    }
  }
];

export default () => {
  return (
    <>
      <BetaSchemaForm
        onFinish={async (values) => {
          console.log(values);
        }}
        columns={columns as any}
      />
    </>
  );
};

```

### © 版本信息

- @ant-design/pro-components : 2.4.14
- @umijs/max：4.0.68

**Comment by kaneruan** [comment]
<img width="1111" alt="image" src="https://github.com/ant-design/pro-components/assets/13065289/37a56075-4f58-4e6b-b30f-416618033bee">

**Comment by kaneruan** [comment]
https://procomponents.ant.design/components/form#transform-%E6%8F%90%E4%BA%A4%E6%97%B6%E8%BD%AC%E5%8C%96

**Comment by chenshuai2144** [comment]
清空之后这个字段就没了，不会触发 transform
