### ISSUE TITLE
🐛[BUG] dropdownMatchSelectWidth is deprecated. Please use popupMatchSelectWidth instead.

### ISSUE THREAD

**Issue by ellisfan** [ant-design/pro-components#7087]
### 🐛 bug 描述

在使用[ProFormTreeSelect](https://ant.design/components/tree-select-cn/)时候控制台会报下面错误：
Warning: [antd: Select] `dropdownMatchSelectWidth` is deprecated. Please use `popupMatchSelectWidth` instead.

### © 版本信息

- ProComponents 版本:  @ant-design/pro-components: "^2.4.15",
- umi 版本：4
- 浏览器环境：Chrome 113.0.5672.92
- 开发环境 [e.g. mac OS]

**Comment by leshalv** [comment]
+1

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，我无法直接处理你的问题。请提供关于React前端开发的问题，我将尽力提供解决方案和代码示例。谢谢理解！

**Comment by h7ml** [comment]
+1
