### ISSUE TITLE
🐛[BUG] 2.4.15版本下的proTable自定义表单组件，onchange事件只触发一次，包括input输入和select多选场景

### ISSUE THREAD

**Issue by 7ingning** [ant-design/pro-components#7088]
### 🐛 bug 描述

2.4.15版本下的proTable自定义表单组件，onchange事件只触发一次，包括input输入和select多选场景

### 📷 复现步骤

用2.4.15版本下的proTable自定义表单组件可复现

### 🏞 期望结果

2.4.12版本下是正常的，看15的发版日志

### 💻 复现代码

![image](https://github.com/ant-design/pro-components/assets/131357495/731c0b8b-71b1-4c56-8092-0a02433eabf9)

### © 版本信息

- ProComponents 版本: 2.4.15
- umi 版本 
- 浏览器环境 chrome
- 开发环境 

### 🚑 其他信息

CI通过package.json锁死2.4.12下的field和from版本解决
![image](https://github.com/ant-design/pro-components/assets/131357495/16ba2857-4998-4658-8beb-5fe856672267)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi there! 

I understand that you're experiencing an issue with the `proTable` custom form component in version 2.4.15 where the `onchange` event is only triggered once for both input and select multiple scenarios. I'll try my best to help you with a solution.

To resolve this issue, you can try updating your `proTable` component to the latest version available. Make sure to follow the upgrade guide provided by the `proTable` documentation to ensure compatibility with your existing codebase.

If updating to the latest version doesn't resolve the issue, you can try the following steps:

1. Ensure that you have correctly implemented the `onChange` event handler for your custom form component. Double-check if you're using it correctly and if it's correctly bound to the input/select elements.

2. Check if there are any specific props or configuration options that you need to set for the `proTable` component to enable proper triggering of the `onChange` event. Look for any documented examples or demos provided by the `proTable` documentation that showcase the usage of custom form components.

3. Examine your code to ensure that there are no other conflicting event handlers or code that might interfere with the `onChange` event. Sometimes, other event listeners or code can unintentionally prevent the `onChange` event from being triggered multiple times.

If the issue still persists after following these steps, you can try reaching out to the `proTable` GitHub repository for additional support. They may be able to provide more specific guidance or investigate if it's a bug in the library.

Please let me know if you need further assistance or if you have any more specific information regarding your issue.

**Comment by chenshuai2144** [comment]
更新版本试试
