### ISSUE TITLE
🐛[BUG] QueryFilter clean icon style bug

### ISSUE THREAD

**Issue by afc163** [ant-design/pro-components#7089]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

清除按钮样式异常。

<img width="351" alt="图片" src="https://github.com/ant-design/pro-components/assets/507615/4db87ec2-56b7-479a-828f-de191d9b950a">

### 💻 复现代码

重现链接：https://procomponents.ant.design/components/query-filter#queryfilter,lightfilter-demo-light-filter-placement

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
merge 了一下，一起搞掉了
