### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by 18257552642** [ant-design/pro-components#7100]
### 🐛 bug 描述

使用ProTable组件, 当columns中设置className,其className会同步设置到对应的FormItem下的组件

### 📷 复现步骤

如图 : 我给gradeCode项设置了className属性"hahahah", 控制台节点树上显示列表单元格和form单元格中都同时设置里class为"hahahah", 这导致css样式冲突

### 🏞 期望结果

我认为列的className应该只作用于列单元格,而不应该作用于FormItem

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://github.com/ant-design/pro-components/assets/47145714/9b535acb-11e1-4102-9e7b-3e19ca127436)
![image](https://github.com/ant-design/pro-components/assets/47145714/476d0846-f316-4c73-b4dd-834de6a03801)
![image](https://github.com/ant-design/pro-components/assets/47145714/68411742-1590-4dd6-b772-428a2e9238a4)

**Comment by chenshuai2144** [comment]
用 formItemProps
