### ISSUE TITLE
🐛[BUG] proTable 在初始化时偶尔会卡在一个 loading 状态，导致table不渲染，

### ISSUE THREAD

**Issue by ChenWeihua123** [ant-design/pro-components#7104]
### 🐛 bug 描述
有两个页面都使用了 proTable 组件，在页面切换时，proTable 偶尔会卡在loading状态，不渲染表格了（仅proTable 的搜索表单会被渲染出来）
![image](https://github.com/ant-design/pro-components/assets/33150900/fc500d0c-dd48-4375-89f0-37d1b1201d68)
貌似这个loading和表格的loading不是一个，因为表格loading我已经控制了，并且出现这种情况时 onLoadingChange 根本不会触发，request 方法也不会触发，就完全是一个卡死的状态。
![image](https://github.com/ant-design/pro-components/assets/33150900/f0240614-46dc-4b76-878a-8249bbf6fb81)

### 🏞 期望结果

- 不出现卡死的问题，可以正常渲染表格
-  或者可以提供一个方式关掉这个loading

### © 版本信息

- ProTable 版本: [2.30.4]
- umi 版本 [3.3.9]
- 浏览器环境 Microsoft Edge 版本 113.0.1774.5
- 开发环境 [windows11]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi there! 我是 GitHub Issue 助理，专注于处理关于 React 前端问题的。感谢你描述了你的问题，并提供了一些截图和额外的信息。

根据你的描述，你遇到了 proTable 组件在初始化时偶尔卡在 loading 状态的问题，并且导致表格无法渲染。你表示这个 loading 状态和表格本身的 loading 不同，并且 onLoadingChange 方法和 request 方法也不会被触发。

首先，这个问题可能是由于异步请求导致的。你可以确保在请求完成之前，表格的数据已经准备好，以避免出现 loading 状态卡死的情况。你可以尝试在页面渲染之前，使用一个 loading 状态来标记表格组件，直到数据完全加载完成。

另外，你也可以检查 proTable 组件的 props，确保没有意外的值导致了 loading 状态的异常，比如数据格式错误或者请求参数的问题。同时，你可以尝试使用开发者工具来调试问题，并查看是否有错误或警告消息。

最后，如果以上方法都没有解决你的问题，你可以尝试查看 proTable 的官方文档，看是否有相关的已知问题或解决方案。你可以在官方文档中找到组件的使用示例、详细的配置参数说明以及常见问题的解答。

尽可能提供更多的代码示例是非常有帮助的，这样我可以更好地理解和复现你的问题。如果有其他问题，请随时提问，我会尽力帮助你解决。

**Comment by chenshuai2144** [comment]
是不是  request  失败了，搞个重现再开吧
