### ISSUE TITLE
🐛[BUG]prolayout在移动端样式出现异常

### ISSUE THREAD

**Issue by liyupengsGit** [ant-design/pro-components#7105]
### 🐛 bug 描述
当右侧内容高度过长滑动到底部后点击左侧菜单时超出部分样式没有生效

### 🚑 其他信息

![IMG_20230521_001305](https://github.com/ant-design/pro-components/assets/26829290/65cfd1be-e83a-44f7-b6c2-7c22093a7b83)

**Comment by xyovo** [comment]
这个问题问的好，可以添加以下全局样式解决：
```
.ant-drawer-content-wrapper {
  position: fixed !important;
  min-height: 100vh !important;
  left: 0 !important;
  top: 0 !important;
}

.ant-drawer-mask {
  position: fixed !important;
  min-height: 100vh !important;
  left: 0 !important;
  top: 0 !important;
}
```

**Comment by liyupengsGit** [comment]
> 这个问题问的好，可以添加以下全局样式解决：
> 
> ```
> .ant-drawer-content-wrapper, .ant-drawer-mask {
>   position: fixed !important;
>   min-height: 100vh !important;
>   left: 0 !important;
>   top: 0 !important;
> }
> ```

谢谢，我对照过V4，好像去掉一个class还是style里面的一项就行了
