### ISSUE TITLE
🐛[BUG]pro-layout中token下sider中的colorBgMenuItemHover无效

### ISSUE THREAD

**Issue by daifuyang** [ant-design/pro-components#7107]
### 🐛 bug 描述
通过修改token下的sider下的colorBgMenuItemHover，但是选择的背景色没有改变
![image](https://github.com/ant-design/pro-components/assets/19951467/b76ff3fd-0106-4e9d-8b9d-4b13c81ff26c)

检查了下仓库的代码，发现这个属性实在header下，是否是文档错误？感觉这块不是很优雅
![image](https://github.com/ant-design/pro-components/assets/19951467/301e80ce-4d03-439c-b145-05b074087ff1)

### 📷 复现步骤
https://codesandbox.io/s/ji-chu-shi-yong-forked-dfy81d?file=/App.tsx
文字已经生效，但是背景色无效

### 🏞 期望结果
背景色变成修改的值

### © 版本信息

- ProComponents 版本: [e.g. 2.4.16]
- umi 版本 4
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
antd@5 顶部菜单是没有背景颜色的，我来找antd py一下

**Comment by ONLY-yours** [comment]
mark

**Comment by natashaamin** [comment]
mark

**Comment by by0126** [comment]
解决了吗？我现在也是这样，修改header的菜单hover背景色不生效

**Comment by Caladog** [comment]
我也发现 header 的二级菜单是没有样式可以设置的，默认跟一级菜单一样，如果header背景设置成深色，二级菜单会看不清。

**Comment by chenshuai2144** [comment]
更新到最新的 antd 和 procomponent

**Comment by Chill7773** [comment]
还是不生效哈

> 更新到最新的 antd 和 procomponent

**Comment by Caladog** [comment]
我更新到"antd": "^5.5.1","@ant-design/pro-layout": "^7.15.2", 还是不行。

**Comment by xliez** [comment]
+1
antd: 5.7.0 + pro-components: 2.6.5
版本依旧不生效

复现：https://codesandbox.io/s/tong-guo-token-xiu-gai-yang-shi-forked-wwkngl?file=/App.tsx

@chenshuai2144

**Comment by daifuyang** [comment]
![image](https://github.com/ant-design/pro-components/assets/19951467/b94bf75a-3314-4080-97dd-f596f8d80ce4)
确实还有问题
