### ISSUE TITLE
🧐[问题] ProFormCheckbox.Group 只能获取最后一次选择的值？

### ISSUE THREAD

**Issue by hiscaler** [ant-design/pro-components#7108]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

显示正常，但是每次都只能获取到最后一次选择的值。请问是哪里处理不对呢？感谢！

### 💻 示例代码

```
<ProFormCheckbox.Group
                              noStyle={true}
                              id={`${moduleName}.${actionDescription.page}`}
                              name={['permissions', moduleName, actionDescription.page]}
                              options={options}
                              fieldProps={{
                                onChange: (values) => console.info("onChange values = ", values),
                              }}                            
                            />
```

**Comment by chenshuai2144** [comment]
搞个demo出来看看

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常抱歉，作为 GitHub Issue 助理，我无法访问外部链接或在线编辑代码。但我会尽力协助解决你的问题。

从你提供的示例代码来看，似乎你想使用 `ProFormCheckbox.Group` 组件来进行多选操作，但无法获取到所有选中项，只能获取到最后一次选择的值。这可能是因为你在 `onChange` 事件处理程序中没有正确地更新状态。

在你的示例代码中，你使用了 `ProFormCheckbox.Group` 组件，并将 `onChange` 事件处理程序传递给 `fieldProps` 属性。但是，根据你的描述，它只能获取到最后一次的选择。这表明你的状态管理可能存在问题。

在处理多选框组的值时，通常需要使用状态来保存所有选中的值。你可以使用 React 的 `useState` 钩子来创建一个状态，并在 `onChange` 事件处理程序中更新它。以下是一个示例代码，可以按照你的需求进行修改：

```jsx
import React, { useState } from 'react';
import { ProFormCheckbox } from 'your-react-library';

const ExampleComponent = () => {
  const [selectedValues, setSelectedValues] = useState([]);

  const handleCheckboxChange = (values) => {
    setSelectedValues(values);
    console.log('selected values:', values);
  };

  const options = [
    { label: 'Option 1', value: 'option1' },
    { label: 'Option 2', value: 'option2' },
    // more options...
  ];

  return (
    <ProFormCheckbox.Group
      options={options}
      value={selectedValues}
      onChange={handleCheckboxChange}
    />
  );
};

export default ExampleComponent;
```

在上述代码中，我们使用 `useState` 创建了一个名为 `selectedValues` 的状态，并将其初始值设置为空数组。然后，我们定义了一个 `handleCheckboxChange` 事件处理程序，它会接收到所选中的值，并将其更新到状态中。最后，我们将状态的值传递给 `ProFormCheckbox.Group` 的 `value` 属性，以便正确显示选中的选项，并将 `handleCheckboxChange` 事件处理程序传递给 `onChange` 属性。

请注意，实际的解决方案可能会因你使用的库或组件而有所不同。如果以上示例代码无法解决你的问题，请提供更多关于你使用的库和组件的信息，以便我们能够更好地帮助你。此外，请确保你已经阅读并尝试过相关库或组件的文档，以获取更多关于其用法和选项的信息。

希望这对你有所帮助！如果你有任何进一步的问题，请随时提问。
