### ISSUE TITLE
V6版本 菜单收缩动画异常渲染问题🐛 [BUG]

### ISSUE THREAD

**Issue by TangDeYu** [ant-design/pro-components#7109]
### 🐛 bug 描述

视频如下
https://github.com/ant-design/ant-design-pro/assets/52319042/a7752a74-20a8-40af-ad20-47525584b867
当前菜单数据是从服务的获取的

### © 版本信息

Ant Design Pro 版本: [e.g. 6.0.0]
umi 版本 "@umijs/max": "^4.0.52",
浏览器环境 Google
开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
神奇，怎么飞了

**Comment by chenshuai2144** [comment]
修复了， tooltip的问题

**Comment by TangDeYu** [comment]
> 

大佬，我这边重新安装了依赖。目前还是视频中这个效果，请问怎么能更新到已经修复的状态?
