### ISSUE TITLE
🧐[问题]请教：ant-design-pro的proTable是否支持特殊列排序？Table.EXPAND_COLUMN

### ISSUE THREAD

**Issue by jiajiaxing1** [ant-design/pro-components#7115]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

代码中使用的了ant-design-pro的proTable，需要展示嵌套子表格，但是展开的icon需要展示在特定的列前面；
看了antd的Table组件有提供Table.EXPAND_COLUMN支持，但是项目中使用的proTable，自己尝试引入之后，不生效

### 💻 示例代码

antd Table的示例https://4x-ant-design.antgroup.com/components/table-cn/#components-table-demo-order-column

### 🚑 其他信息

如截图等其他信息可以贴在这里
![image](https://github.com/ant-design/pro-components/assets/130677115/c8fc429f-1b6a-4129-96cc-13ce99fc5c56)
感谢！

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！根据你的问题描述，你想在使用 ant-design-pro 的 ProTable 组件展示嵌套子表格时，将展开的图标展示在特定的列前面，类似于 antd 的 Table.EXPAND_COLUMN 功能。但是在引入之后，功能没有生效。

根据我的了解，ant-design-pro 并没有直接提供类似于 Table.EXPAND_COLUMN 的属性来实现该功能。但是你可以通过自定义渲染方法来达到需求。下面是一种可能的解决方案：

首先，你可以使用 ProTable 的 expandable 属性来展示嵌套的子表格。在 expandable 属性中，你可以通过设置 expandedRowRender 方法来自定义子表格的展示方式。

在这个方法中，你可以使用 render 方法自定义每一行展开的图标，并将其展示在特定的列前面。例如，你可以使用 ExpandedRowRender 方法中的 record 参数来判断是否展开，并根据需要展示展开的图标。以下是一个示例代码：

```jsx
import { ProTable } from '@ant-design/pro-table';

const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: 'Age',
    dataIndex: 'age',
    key: 'age',
  },
  {
    title: 'Expand',
    dataIndex: 'expand',
    render: (text, record, index, action) => {
      return (
        <span>
          {record.expand ? (
            <span>-</span> // 展开的图标
          ) : (
            <span>+</span> // 未展开的图标
          )}
        </span>
      );
    },
  },
];

const data = [
  {
    key: '1',
    name: 'John Brown',
    age: 32,
    expand: true,
  },
  {
    key: '2',
    name: 'Jim Green',
    age: 42,
    expand: true,
  },
];

const expandedRowRender = (record) => {
  return <p>{record.name} is {record.age} years old</p>;
};

export function MyTable() {
  return (
    <ProTable
      columns={columns}
      dataSource={data}
      expandable={{
        expandedRowRender: expandedRowRender,
        rowExpandable: (record) => record.expand,
      }}
      rowKey="key"
    />
  );
}
```

通过以上代码，你可以根据数据中的 expand 属性来判断是否展开，然后显示不同的图标。当你点击图标时，相应行的子表格会展开或折叠。

如果你需要更多的帮助、文档和示例，你可以参考 ant-design-pro 的官方文档（https://procomponents.ant.design/components/table）和 antd 的 Table 组件文档（https://ant.design/components/table-cn/）。

希望这个解决方案对你有帮助！如果还有其他问题，请随时提问。

**Comment by Mrtaochen** [comment]
最新版本的protable使用这个功能是有bug的，参考这个是可以的   https://codesandbox.io/p/sandbox/wu-toolbar-de-biao-ge-forked-dh965l?file=%2FApp.tsx%3A69%2C7

**Comment by samotoo** [comment]
> 最新版本的protable使用这个功能是有bug的，参考这个是可以的 https://codesandbox.io/p/sandbox/wu-toolbar-de-biao-ge-forked-dh965l?file=%2FApp.tsx%3A69%2C7

@Mrtaochen 老哥，请问你是怎么解决这个问题的？你贴的codesandbox已经打不开了。
