### ISSUE TITLE
👑 [需求]ant-pro-table 能计算获取搜索框高度吗

### ISSUE THREAD

**Issue by Joahyan** [ant-design/pro-components#7116]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

ant-pro-table

### 🥰 需求描述

```
  const formRef = useRef<ProFormInstance>();
  const actionRef = useRef<ActionType>();

  <ProTable
            className='bg-secondary sm-table'
            scroll={{
              y: `${windowSize.innerHeight - 64 - 32 - 66 - 16 - 34 - 40 - 40}px`
            }}
            columns={columns}
            formRef={formRef}
            actionRef={actionRef}
</Protable>
```
> formRef 本身应该就是 searh框 form表单的ref，如果能暴露出form的dom元素就太棒了，再者pagenation的高度如果方便也可暴露

### ⛰ 功能需求适用场景

解决由于搜索框高度、及页码高度导致的双滚动条出现，特别是折叠展开功能，或表单校验让计算搜索框高度变得麻烦，避免使用者繁琐计算
### 🧐 解决方案

暴露方法 类似这样
```
formRef.current.offsetHeight
actionRef.current.getPagenationHeight()
```

**Comment by zhengbigbig** [comment]
scrollY我觉得二封可以直接通过ahooks useSize，获取搜索框高度和页码高度，来动态计算高度

**Comment by ElsaOOo** [comment]
> scrollY我觉得二封可以直接通过ahooks useSize，获取搜索框高度和页码高度，来动态计算scrollY 譬如：tableHeight - queryHeight - paginationHeight

对，但是通过原生的querySelector 获取搜索框高度有问题，在多个tab keepAlive的情况下，获取当前tab下的搜索框高度不好获取

**Comment by chenshuai2144** [comment]
你这个玩的挺花的，推荐你挂个 id 异步计算一下吧，不然会很卡
