### ISSUE TITLE
🐛[BUG]当ProForm开启grid的时候，子元素ProForm.Item或Form.Item没有被添加任何栅格属性

### ISSUE THREAD

**Issue by 741599086** [ant-design/pro-components#7118]
当ProForm开启grid的时候，子元素ProForm.Item或Form.Item没有被添加任何栅格属性

![1684909752640](https://github.com/ant-design/pro-components/assets/14175254/750b40fb-68cc-45e8-98b1-03f1d62c3433)

**Comment by LittleChives** [comment]
+1 正在看这个问题。。这个时候要怎么栅格化

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi! 感谢你提交这个问题。我明白你遇到了在ProForm中开启grid时子元素ProForm.Item或Form.Item没有添加栅格属性的问题。

要在ProForm中使用栅格化(grid)，你可以使用`layout`属性来指定每个表单项所占据的栅格空间。例如，你可以将`layout`属性设置为`colSpan: 4`表示该表单项占据4个栅格。

下面是一个示例，展示如何在ProForm中使用grid：

```jsx
import { ProForm, ProFormText } from '@ant-design/pro-form';
import { Form } from 'antd';

const DemoForm = () => {
  return (
    <Form>
      <ProForm
        layout={{
          labelCol: { span: 4 },
          wrapperCol: { span: 8 },
        }}
      >
        <ProFormText
          name="name"
          label="姓名"
          rules={[{ required: true, message: '请输入姓名' }]}
          fieldProps={{ placeholder: '请输入姓名' }}
        />
        <ProFormText
          name="email"
          label="邮箱"
          rules={[{ required: true, message: '请输入邮箱' }]}
          fieldProps={{ placeholder: '请输入邮箱' }}
          layout={{
            colSpan: 4,
          }}
        />
      </ProForm>
    </Form>
  );
};

export default DemoForm;
```

在上面的示例中，我们为`ProFormText`组件的`layout`属性设置了`colSpan: 4`，表示该表单项将占据4个栅格。

你可以根据你的具体需求，调整`layout`属性的值来实现不同的栅格布局。

在这里是Ant Design Pro组件库的[栅格化文档](https://procomponents.ant.design/components/grid)，这里你可以找到更多关于栅格化的用法和示例。

希望这个解决方案对你有所帮助！如果你还有其他问题，请随时提问。

**Comment by LittleChives** [comment]
您好,邮件已经收到,谢谢!

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！很高兴你已经收到了邮件，并且感谢你的反馈！如果你还有任何其他问题或者需要进一步的帮助，请随时告诉我。我会尽力继续帮助你解决问题。

**Comment by chenshuai2144** [comment]
grid 只对自带组件生效的，暂时还不支持自定义组件

**Comment by caijiang** [comment]
有对自定义组件支持更完善(包括 gird, 文档)的时间表么？

**Comment by LittleChives** [comment]
您好,邮件已经收到,谢谢!
