### ISSUE TITLE
🐛[BUG]微信浏览器ProTable的scroll.x横向滚动条显示一下就会隐藏，很容易误导用户表格项就那么多

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#7121]
![098967eb37e5225ae48d71868bed044](https://github.com/ant-design/pro-components/assets/12421552/bc22085c-2832-47e9-888b-306d7e68aa7f)

页面加载完成后，滚动条显示一会就隐藏了，如图所示，完全无法分辨该Table是否还有其他的项目，
鼠标重新挪上去，滚动条也不会显示出来，

在Chrome和Edge里就没得问题，滚动条一直显示
![image](https://github.com/ant-design/pro-components/assets/12421552/8b3f9e90-2554-4ae3-a440-d249d9672ac6)

**Comment by ONLY-yours** [comment]
有没有一种可能这是VX浏览器的逻辑？这个和组件库似乎没有关系

**Comment by edifangyi** [comment]
> 

但是现在很多用户都在用微信默认浏览器办公，不考虑到微信的话，很难办的。

**Comment by chenshuai2144** [comment]
这个组件库也没什么办法，你可以加个提示。

我们组件库不好做什么
