### ISSUE TITLE
🐛[BUG] formItemProps使用Upload组件时不提示错误信息

### ISSUE THREAD

**Issue by xiaozheqiu** [ant-design/pro-components#7122]
### 🐛 bug 描述
formItemProps使用Upload组件时不提示错误信息

在FroForm和EditableProTable结合使用中，发现以下情况
formItemProps在使用upload组件时，页面会轻微向下抖动一下，无法在页面中看到错误提示内容，但是控制台可以看到错误信息，然后把组件切换成input则可以正常显示

### 🏞 期望结果
![image](https://github.com/ant-design/pro-components/assets/49509790/5231ffa7-ff4a-4e0d-b53f-746feb0f9c9a)

### 💻 复现代码
这是代码地址
https://codesandbox.io/s/yu-formitem-pei-he-forked-v0pg6z?file=/App.tsx

**Comment by xiaozheqiu** [comment]
麻烦有大佬帮忙看看，这个项目很急0.0

**Comment by ONLY-yours** [comment]
Upload应该要自定义校验规则，不能用通用的rules
