### ISSUE TITLE
🧐[问题]EditableProTable 如何修改成提示语展示在控件下方

### ISSUE THREAD

**Issue by liushuhui** [ant-design/pro-components#7125]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

EditableProTable的必填提示默认是hover弹出，有没有什么方式改成必填提示在单元格控件下方提示，和form表单提示效果保持一致

### 🚑 其他信息
<img width="208" alt="fd137546c7b6e2a5f97f34e337ce980" src="https://github.com/ant-design/pro-components/assets/26155477/27a62d71-c39b-4204-bf37-a8164c33dc21">

**Comment by chenshuai2144** [comment]
`formItemProps={{ errorType:"default" }}`

这样设置一下
