### ISSUE TITLE
DrawerForm 配合ant的useWatch报错🐛[BUG]

### ISSUE THREAD

**Issue by wanglianjie91** [ant-design/pro-components#7130]
### 🐛 bug 描述
DrawerForm 配合ant的useWatch报错

### 📷 复现步骤

关键步骤，设置destroyOnClose: true，关闭弹窗此时formRef?.current值为null。 传入useWatch第二个参数，报错。

判断formRef?.current值为null时，传入undefined则正常运行。关键代码如下。

### 🏞 期望结果

这个bug不知道是该报给antd, 还是报这里。

### 💻 复现代码

`
const formRef = useRef<ProFormInstance>();
const name = Form.useWatch("name", formRef?.current || undefined);
<DrawerForm
      drawerProps={{
        destroyOnClose: true,
      }}
 />

`

### © 版本信息

- ProComponents 版本:^2.4.2
- umi 版本: "@umijs/max": "^4.0.8"
- 浏览器环境：chrome stable
- 开发环境 [mac OS]

**Comment by q1uxu** [comment]
遇到了同样的问题

**Comment by chenshuai2144** [comment]
不要 destroyOnClose 就好了吧，因为关闭之后form就没了
