### ISSUE TITLE
🐛[BUG] sider从折叠到展开，顶部会闪现一下，当前页的菜单标题。

### ISSUE THREAD

**Issue by Caladog** [ant-design/pro-components#7132]
sider从折叠到展开，顶部会闪现一下，当前页的菜单标题。

![image](https://github.com/ant-design/pro-components/assets/30135964/7a2f33ff-b084-4037-a5f7-6259197d0378)

![image](https://github.com/ant-design/pro-components/assets/30135964/1d855022-14d8-4cb3-a1f6-816ca6257f7b)

**Comment by kungege** [comment]
Duplicate with  #7109.

**Comment by chenshuai2144** [comment]
已经修复了，tooltip 的问题
