### ISSUE TITLE
🐛[BUG] pro-components@latest + antd@4.24.10，全部样式都继承 antd4.0 了，design token 也失效了

### ISSUE THREAD

**Issue by dreammaker7** [ant-design/pro-components#7134]
### 📷 复现步骤

安装指定版本 antd + pro-components

### 🏞 期望结果

样式与原有设计一致，antd@4.24 + pro-components@2 是为了平滑的过渡到 antd@5.x。

### 💻 复现代码

[https://stackblitz.com/edit/vitejs-vite-5fyjrb?file=package.json,src%2FApp.tsx,vite.config.ts,src%2F_defaultProps.tsx,src%2Fmain.tsx](https://stackblitz.com/edit/vitejs-vite-5fyjrb?file=package.json,src%2FApp.tsx,vite.config.ts,src%2F_defaultProps.tsx,src%2Fmain.tsx)

### © 版本信息

- ProComponents 版本: [2.4.16]
- 浏览器环境 Chrome
- 开发环境 [windows 11]

### 🚑 其他信息

![image](https://github.com/ant-design/pro-components/assets/74588098/b23b8d18-bd04-4977-8188-27702f9ec0fd)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi there,

感谢您报告这个问题。根据您的描述，当您将 pro-components@2.4.16 与 antd@4.24.10 结合使用时，原有的布局样式失效，并且设计的 tokens 也不再起作用。

这可能是由于 pro-components@2.4.16 与 antd@4.x 版本之间存在不兼容性。为了平滑过渡到 antd@5.x，您可以尝试升级 pro-components 版本到与 antd 版本兼容的最新版本。

另外，为了更好地帮助您解决该问题，请提供一些额外的信息或复现代码。您提供的 StackBlitz 链接已失效，如果可能的话，请提供一个可以复现问题的最小代码示例，这样我们才能更准确地了解并解决您遇到的问题。

在等待您的进一步回复时，您可以参考官方文档，查看相关的更新日志和问题。

- pro-components 文档：[https://procomponents.ant.design/](https://procomponents.ant.design/)
- antd 更新日志：[https://ant.design/changelog](https://ant.design/changelog)

谢谢！

**Comment by chenshuai2144** [comment]
<img width="1419" alt="image" src="https://github.com/ant-design/pro-components/assets/8186664/50b984da-8115-4f34-af6e-85b93f6048e8">


看起来好像没啥问题，还有问题详细试试
