### ISSUE TITLE
🐛[BUG] Attempted import error: 'arrayMoveImmutable' is not exported from '@ant-design/pro-components' (imported as 'arrayMoveImmutable').

### ISSUE THREAD

**Issue by da-xia** [ant-design/pro-components#7140]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by ycshill** [comment]
> @ant-design/pro-utils新版本把arrayMoveImmutable删掉了

那改成什么了呢

**Comment by chenshuai2144** [comment]
直接去掉了。用开源库 arrayMove把 

https://www.npmjs.com/package/array-move
