### ISSUE TITLE
🐛[BUG] utils 的 transformKeySubmitValue 的 _transformArray 存在问题

### ISSUE THREAD

**Issue by Soulwail** [ant-design/pro-components#7141]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

![WX20230530-105116](https://github.com/ant-design/pro-components/assets/34655106/ba89e77d-7052-4eeb-8571-88238adb0224)

第 101 行和第 106 行，当 `_itemValue[idx][curK]` 或 `_itemValue[idx]` 的结果为 `undefined`，`_transformArray` 会继续执行，导致报错，需要添加判断

### © 版本信息

- ProComponents 版本: 
- ProUtils 版本: 2.11.0
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个 pr  我来发个版本
