### ISSUE TITLE
🐛[BUG]刷新或进入页面，经常出现搜索框的内容会没掉，只剩下搜索和重置按钮

### ISSUE THREAD

**Issue by xian107** [ant-design/pro-components#7142]
https://github.com/ant-design/pro-components/assets/13252682/25a3b3f7-27b2-4ade-a031-68e0473f4293

示例很难复现，代码是这样的
：https://codesandbox.io/s/cranky-benji-4bf43v?file=/src/App.js

columns的useMemo加上依赖shipment_status，就会出问题
求大神们指点，困扰很久了这个问题
 "antd": "^5.5.0",
"@ant-design/pro-components": "^2.4.16",

**Comment by hooliy** [comment]
兄弟，标签卡是怎么实现的？

**Comment by xian107** [comment]
> 兄弟，标签卡是怎么实现的？

自己写的

**Comment by chenshuai2144** [comment]
看起来是   react 的更新被拦截了，你把他放到最外面，然后试试呢

**Comment by xian107** [comment]
> 看起来是 react 的更新被拦截了，你把他放到最外面，然后试试呢

哪个放到最下面？

**Comment by xian107** [comment]
请问有人遇到过同样的问题吗？
@chenshuai2144 求帮助

**Comment by hooliy** [comment]
偶发性的，新版一直都有的，还有莫名的组件样式丢失

**Comment by edifangyi** [comment]
我也碰到过类似的情况，而且这个Table的搜索使用时间范围，选择框没办法自适应，一直都从左边显示，会跑出窗口外

**Comment by chenshuai2144** [comment]
搜索框问题修复了，别的升级antd 即可解决
