### ISSUE TITLE
🧐[问题]如何使用列自定义的功能，在该按钮之外

### ISSUE THREAD

**Issue by daisybaicai** [ant-design/pro-components#7143]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
![image](https://github.com/ant-design/pro-components/assets/25605435/a173911e-6626-43db-89f3-474576af6f4f)

1. 目前procomponents的ProTable本身提供了一个列自定义的功能，但是希望能够在其他自定义的位置，去使用该列自定义的功能，可能有一些样式的调整，因此需要找到能够自定义的地方

类似如下图
![image](https://github.com/ant-design/pro-components/assets/25605435/8bb00922-d572-4759-ac94-8ee9ca69efab)

**Comment by chenshuai2144** [comment]
不支持的，建议关掉然后完全自己实现。 改动过大了
