### ISSUE TITLE
🐛[BUG] 2.5.2 没有类型声明文件

### ISSUE THREAD

**Issue by 0scarecrow0** [ant-design/pro-components#7148]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

2.5.2 版本依赖的 pro-layout 未生成类型声明文件，pro-table 部分api也未生成类型声明

### 📷 复现步骤

安装最新版

### 🏞 期望结果

有类型声明

### 💻 复现代码

安装最新版本

### © 版本信息
![image](https://github.com/ant-design/pro-components/assets/45458124/d671831e-f63c-4f18-9b7a-73aab526af40)

**Comment by 0scarecrow0** [comment]
<img width="457" alt="49a39158f419c53da058eea1fa13252e" src="https://github.com/ant-design/pro-components/assets/45458124/1e096c7b-94f7-4cd4-acf9-7ba4e4323fbd">

**Comment by goodjun** [comment]
+1

**Comment by BlueCat918** [comment]
+1

**Comment by chenshuai2144** [comment]
已经修复了，重新更新即可

**Comment by SnowWinterMaye** [comment]
> 已经修复了，重新更新即可

ProCard \CheckCard, EditableProTable里 record的类型依然没有被导出
