### ISSUE TITLE
🐛[BUG] Localization issue in search form

### ISSUE THREAD

**Issue by arifszn** [ant-design/pro-components#715]
I am following the [Internationalization example](https://procomponents.ant.design/components/table#%E5%9B%BD%E9%99%85%E5%8C%96%E7%A4%BA%E4%BE%8B) of Protable.  The example converts every Chinese to English perfectly. 

However when I am using the exact same code, the placeholders in search form remain in Chinese.
![image](https://user-images.githubusercontent.com/45073703/95879826-9b805100-0d98-11eb-9c69-9decdc65c6e5.png)

**Comment by chenshuai2144** [comment]
show you code or give me a repo

**Comment by arifszn** [comment]
@chenshuai2144 
Here's the code: https://github.com/arifszn/protableissue
Here's the demo: https://arifszn.github.io/protableissue

**Comment by arifszn** [comment]
Also another issue: if copyable is not true in columns, elipse does not work. You can see in the demo.

**Comment by chenshuai2144** [comment]
> Also another issue: if copyable is not true in columns, elipse does not work. You can see in the demo.

you can set table layout is fixed

**Comment by arifszn** [comment]
> layout



> > Also another issue: if copyable is not true in columns, elipse does not work. You can see in the demo.
> 
> you can set table layout is fixed

Sorry did not get that.

**Comment by arifszn** [comment]
> > Also another issue: if copyable is not true in columns, elipse does not work. You can see in the demo.
> 
> you can set table layout is fixed

Sorry did not get that.

**Comment by chenshuai2144** [comment]
@arifszn  

like this code `tableLayout="fixed" `

**Comment by chenshuai2144** [comment]
@arifszn  remove your lock, update your dependencies
