### ISSUE TITLE
ProFormTreeSelect组件一级数据主动设置disabled为true无效果🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/pro-components#7151]
### 🐛 bug 描述

ProFormTreeSelect组件在onchange事件设置父级数据disabled为true后样式没有改变，按钮没有置灰
![image](https://github.com/ant-design/pro-components/assets/20655248/f71280eb-9d3a-464c-9800-310227e35c37)
代码如下：
![image](https://github.com/ant-design/pro-components/assets/20655248/5504aad4-eb85-4241-8271-560aede5f26f)

发现用antd的TreeSelect组件是可以的

![image](https://github.com/ant-design/pro-components/assets/20655248/2e57a8a0-82c8-4de4-86a5-526e45ed321f)
![image](https://github.com/ant-design/pro-components/assets/20655248/c30bbb2e-c178-425c-9ec2-bf23f60fb90e)

所以应该是ProFormTreeSelect组件的问题

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
要触发重新渲染，修改引用没有意义的
