### ISSUE TITLE
🐛[BUG] Schema Form 使用自定义valueType upload报错

### ISSUE THREAD

**Issue by tjj727** [ant-design/pro-components#7153]
### 🐛 bug 描述
```

import {
  ProConfigProvider,
  ProFormUploadDragger,
} from '@ant-design/pro-components';

export default (props: { children: any }) => {
  return (
    <ProConfigProvider
      valueTypeMap={{
        upload: {
          render: (text) => text,
          renderFormItem: (text, props) => {
            return (
              <ProFormUploadDragger
                {...props}
                {...props?.fieldProps}
                onChange={(a) => {
                  props?.fieldProps.onChange(a.fileList);
                }}
              />
            );
          },
        },
      }}
      hashed={false}
    >
      {props.children}
    </ProConfigProvider>
  );
};
```
![image](https://github.com/ant-design/pro-components/assets/129740535/630cd166-c1f3-4725-abc6-d0f301711187)

BetaSchemaForm使用自定义valueType ProFormUploadDragger，value的值是object而不是array，正常值应该是fileList的值

### 🏞 期望结果

value值正常

### © 版本信息
- ProComponents 版本: [2.5.0]

**Comment by tjj727** [comment]
复现案例

import {
  BetaSchemaForm,
  ProConfigProvider,
  ProFormUploadDragger,
} from '@ant-design/pro-components';
import React from 'react';


const columns: any = [
  {
    title: '标签',
    valueType: 'upload',
    dataIndex: 'file'
  },
];


export default () => {
  return (
    <ProConfigProvider
      valueTypeMap={{
        upload: {
          render: (text) => text,
          renderFormItem: (text, props) => {
            return (
              <ProFormUploadDragger
                {...props}
                {...props?.fieldProps}
                onChange={(a) => {
                  props?.fieldProps.onChange(a.fileList);
                }}
              />
            );
          },
        },
      }}
      hashed={false}
    >
        <BetaSchemaForm<any>
          columns={columns}
          title="自定义 valueType"
        />
    </ProConfigProvider>
  );
};

![image](https://github.com/ant-design/pro-components/assets/129740535/d0d885e7-f145-4482-adb0-dfb57ab2a443)

**Comment by chenshuai2144** [comment]
需要自己处理  value  和  onchange  的，你研究一下  upload 的参数
