### ISSUE TITLE
ProLayout 选中二级菜单，收起侧边栏，再展开侧边栏，会在body下面生成多余的div🐛[BUG]

### ISSUE THREAD

**Issue by 305371179** [ant-design/pro-components#7155]
### 🐛 bug 描述

凡是当前显示的路由是二级菜单的，展开之后就会在body的子级生成多余的div。问题跟[ #6722](https://github.com/ant-design/pro-components/issues/6722)是一样的，这个bug很明显的，为什么没解决就close了啊。如下图：
![image](https://github.com/ant-design/pro-components/assets/35661936/6f4ed26f-5cba-4aed-8fe1-d8e45ec5bf2e)

即使是官网的例子也是一样 [layout](https://procomponents.ant.design/components/layout?tab=api#%E8%87%AA%E5%AE%9A%E4%B9%89-menu-%E7%9A%84%E5%86%85%E5%AE%B9)

### 📷 复现步骤

随便点击一个二级菜单，然后收缩菜单，再展开，查看dom下body是不是被追加了一个子级的div，然后左上角的顶部显示是这样的
![image](https://github.com/ant-design/pro-components/assets/35661936/ad4fc9a0-1b33-4466-9bfa-418b1934e9dc)

### 🏞 期望结果

不会生成多余的div，不影响菜单的收缩展开的显示

### 💻 复现代码

在官网上的例子按复现步骤即可

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 4.x
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
tooltip的问题，等待antd修复就好了
