### ISSUE TITLE
🧐[问题] pro-components的依赖版本问题

### ISSUE THREAD

**Issue by JackRoy1992** [ant-design/pro-components#7156]
我记得之前的依赖都是固定的版本，现在好像所有版本都是向上升级的
```
"@ant-design/pro-card": "^2.4.11",
"@ant-design/pro-descriptions": "^2.3.2",
"@ant-design/pro-field": "^2.9.2",
"@ant-design/pro-form": "^2.13.2",
"@ant-design/pro-layout": "^7.14.1",
"@ant-design/pro-list": "^2.4.2",
"@ant-design/pro-provider": "^2.10.0",
"@ant-design/pro-skeleton": "^2.1.3",
"@ant-design/pro-table": "^3.7.2",
"@ant-design/pro-utils": "^2.11.1",
"@babel/runtime": "^7.16.3"
```
这样如果我某个版本遇到了你们设计上的失误导致的功能问题，无法通过降低pro-components的版本来规避，因为实际出问题的是最新的依赖的版本，比如pro-form，即使我在我依赖中固定pro-form的版本，安装依赖时也会因为pro-components对pro-form的依赖安装最新的版本。感觉还是之前固定pro-components依赖版本的形式比较好，你们觉得呢

**Comment by buquan** [comment]
我也遇到了个问题，删除lock重新安装直接报错了

<img width="985" alt="image" src="https://github.com/ant-design/pro-components/assets/23711051/1d74d287-8681-4c94-85ca-6aa683615ede">

**Comment by chenshuai2144** [comment]
写死了
