### ISSUE TITLE
🐛[BUG] 2.5.3 没有类型声明文件

### ISSUE THREAD

**Issue by BlueCat918** [ant-design/pro-components#7158]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
2.5.3 版本依赖的 pro-card 及pro-descriptions 未生成类型声明文件

### 📷 复现步骤
安装最新版

### 🏞 期望结果
有正确的类型声明文件

### 💻 复现代码
安装最新版本

### © 版本信息

- ProComponents 版本: [2.5.3]

### 🚑 其他信息
![image](https://github.com/ant-design/pro-components/assets/32082464/2577e1b1-c130-4a86-9a7c-fec5e779d685)

**Comment by ZhangLinkang** [comment]
+1

**Comment by Hahahaooovvv** [comment]
+1

**Comment by JackRoy1992** [comment]
+1

**Comment by fnoopv** [comment]
+1

**Comment by Hahahaooovvv** [comment]
我把版本号锁定了一下 "@ant-design/pro-card": "2.4.10"就行了

**Comment by hsulei** [comment]
"@ant-design/pro-card": "2.4.13" 修复了，更新一下就行
