### ISSUE TITLE
🐛[BUG] typescript 代码提示错误

### ISSUE THREAD

**Issue by qq382724935** [ant-design/pro-components#716]
### 🐛 bug 描述

使用ProFormText情况下 props 需要传一个status，否在在编译器会出现报错
### 🏞 期望结果

在没有传入status属性情况下不应该出现ts错误提示
### © 版本信息

- @ant-design/pro-form 版本: [e.g. 1.0.2]
- umi 版本 3.2.23
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/24310904/95945700-a3360900-0e1d-11eb-999a-337237cbbf42.png)

**Comment by qq382724935** [comment]
ProFormSelect有相同情况

**Comment by chenshuai2144** [comment]
看了一下不会出现这个问题，有重现的repo吗？

**Comment by zhahaoyu** [comment]
一样的，这个问题还是有。为什么关掉了呢？

**Comment by chenshuai2144** [comment]
按照上面的操作来

**Comment by zhahaoyu** [comment]
> 按照上面的操作来

问题解决了。但是删掉yarn.lock导致几乎所有的依赖版本都变化了，对于production环境下跑的应用风险太高了。

这样解决的原因是某些库的依赖是implict的吗？能不能明确表明最低依赖，让yarn选择性的管理依赖升级。
