### ISSUE TITLE
🧐[问题]proTable colums search.transform 转换date后 form.getFieldsValue()获取到的值是没有转换的

### ISSUE THREAD

**Issue by yy305736605** [ant-design/pro-components#7161]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
![9B50C24D-838B-436f-9869-3B7096CAEA3E](https://github.com/ant-design/pro-components/assets/75480124/c500acad-e302-4d4a-b9d0-705fc9953b70)

   
![350B30B9-FB52-4bc8-9102-21BB547892D7](https://github.com/ant-design/pro-components/assets/75480124/1779f879-24d0-4c9b-8feb-1445e388bde0)

![image](https://github.com/ant-design/pro-components/assets/75480124/a73a0158-6a34-493b-a808-f7c1ac06834e)

### 1.
        如图，用transform转换后  查询的时候能正常获取转换后的值
        但是导出需要表单的参数 ， 然后用formRef.current.getFieildsValue(true) 获取到的值却是【moment,monent】
        只能再手动转换了吗？

### 2.
        transform是如何实现 submit拿到转换后的值
        在antd form中如果form.setFieldValue() set了之后 submit
        form的onFinish 并不能获取到set的值 
        只会收集 定义了formItem  属性name的值

**Comment by chenshuai2144** [comment]
```
/**
       * 获取被 ProForm 格式化后的单个数据, 包含他的 name
       * @param nameList (string|number)[]
       * @returns T
       *
       * @example  {a:{b:value}} -> getFieldFormatValueObject(['a', 'b']) -> {a:{b:value}}
       */
      /** 获取格式化之后的单个数据 */
      getFieldFormatValueObject: (paramsNameList?: NamePath) => {
        const nameList = covertFormName(paramsNameList);
        const value = getFormInstance()?.getFieldValue(nameList!);
        const obj = nameList ? set({}, nameList as string[], value) : value;
        return transformKey(obj, omitNil, nameList);
      },
```
用这个 api
