### ISSUE TITLE
🐛[BUG]DragSortTable - 拖动排序表格 添加sticky属性,加载数据时表头出现闪烁

### ISSUE THREAD

**Issue by lxzmo** [ant-design/pro-components#7164]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
DragSortTable - 拖动排序表格 添加sticky属性,加载数据时表头出现闪烁
DragSortTable - 拖动排序表格 拖拽排序按钮放在表格右侧时,拖拽表格会样式出现漂移

### © 版本信息

- ProComponents 版本: [e.g. 2.5.3]
- umi 版本[4.0.67]
- 浏览器环境[谷歌]
- 开发环境 [e.g. mac OS]

**Comment by xinghongying** [comment]
DragSortTable - 拖动排序表格  表格出现下滚动条是,拖拽表格会样式出现漂移

**Comment by chenshuai2144** [comment]
搞个重现看看， DragSortTable  不太适合太复杂的表格，样式变化会很大

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好 @用户，请提供一个在线的重现实例或者一个最小化的代码示例来详细说明你的问题，这将有助于我们更好地理解并解决你的问题。你可以通过以下的步骤来创建一个在线的重现实例：

1. 请访问 [CodeSandbox](https://codesandbox.io/) 网站。
2. 创建一个新的沙箱项目。
3. 在项目中复现你遇到的问题，并且尽可能地提供简化后的代码。
4. 在完成后保存项目，并且将沙箱的链接分享给我们。

如果你无法使用 CodeSandbox，也可以提供一个 GitHub 仓库链接，确保里面包含了能够复现问题的最小化代码示例。

如果你还不清楚如何提供代码示例，请参考 [如何写好一个问题](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。

期待你的在线重现实例，这样我们便可以更好地帮助你解决问题。谢谢！
