### ISSUE TITLE
🧐[问题] 如何获取到ProTable 中table的真实dom节点

### ISSUE THREAD

**Issue by yoke0104x** [ant-design/pro-components#7165]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
无法获取到ProTable 中table的真实dom节点

### 💻 示例代码
https://codesandbox.io/s/cha-xun-wu-an-niu-biao-ge-forked-k7elyb?file=/App.tsx

**Comment by chenshuai2144** [comment]
搞个id获取把，react 里面获取 dom 还挺麻烦的
