### ISSUE TITLE
🐛[BUG] × Unhandled Rejection (TypeError): _formRef$current.validateFieldsReturnFormatValue is not a function

### ISSUE THREAD

**Issue by hooliy** [ant-design/pro-components#7167]
不知道从哪个版本开始 await formRef.current?.validateFieldsReturnFormatValue(); 为提示 alidateFieldsReturnFormatValue not is function

**Comment by mxsl-gr** [comment]
相同的那问题, 2.5.x 版本之后. 切到 2.4.x 是好的

**Comment by czf0321** [comment]
@ant-design/pro-components  2.4.x的也不好，他会依赖最新版本的@ant-design/pro-form。很是都头疼

**Comment by chenshuai2144** [comment]
已经修复了，更新下版本
