### ISSUE TITLE
🐛[BUG] 2.5.x 的 FormRef 中 validateFieldsReturnFormatValue 方法丢失

### ISSUE THREAD

**Issue by mxsl-gr** [ant-design/pro-components#7168]
### 🐛 bug 描述

FormRef 中的 `validateFieldsReturnFormatValue` 方法丢失.

### 📷 复现步骤

BetaSchemaForm 配置 formRef, 之后调用 `formRef.current.validateFieldsReturnFormatValue()`

触发后会提示 validateFieldsReturnFormatValue is not a function

### 🏞 期望结果

可以正常调用方法

### 💻 复现代码

2.5.x 该方法丢失: https://codesandbox.io/s/form-lost-method-2-5-2-8i7dse?file=/package.json
2.4.x 是可以工作的: https://codesandbox.io/s/form-lost-method-58t5jg?file=/App.tsx

核心代码:
```TypeScript
import type { ProFormInstance } from "@ant-design/pro-components";
import { BetaSchemaForm } from "@ant-design/pro-components";
import React from "react";

export default () => {
  const formRef = React.useRef<ProFormInstance>();

  return (
    <BetaSchemaForm<any>
      formRef={formRef}
      onFinish={async (values) => {
        const data = await formRef.current.validateFieldsReturnFormatValue();
        console.log(values, data);
      }}
      columns={[
        {
          title: "标题",
          dataIndex: "title"
        }
      ]}
    />
  );
};

```

### © 版本信息

- ProComponents 版本: 2.5.x
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by mxsl-gr** [comment]
临时可以通过分别调用 `validateFields` 和 `getFieldsValue` 方法绕过. 

但还是希望可以修复, 或者删除 API 以免误导

```TypeScript
await this.formRef.current?.validateFields?.()
const formData = await this.formRef.current?.getFieldsValue?.()
```

**Comment by hooliy** [comment]
> 临时可以通过分别调用 `validateFields` 和 `getFieldsValue` 方法绕过.
> 
> 但还是希望可以修复, 或者删除 API 以免误导
> 
> ```ts
> await this.formRef.current?.validateFields?.()
> const formData = await this.formRef.current?.getFieldsValue?.()
> ```

这样能拿到格式化后的值吗？

**Comment by chenshuai2144** [comment]
是dayjs 的包多实例了，可以用 alias 保证一下永远只有一份

**Comment by xiao-xiansheng** [comment]
**ModalForm DrawerForm** 也存在相同的问题

**Comment by xiao-xiansheng** [comment]
ModalForm DrawerForm 也存在相同的问题   <br /> validateFieldsReturnFormatValue方法应该存在此API 表单最终应该拿到转换后的值

**Comment by xiao-xiansheng** [comment]
> 是dayjs 的包多实例了，可以用 alias 保证一下永远只有一份

有解决示例吗?

**Comment by hooliy** [comment]
> 

具体要怎么解决呢？

**Comment by sushi-su** [comment]
https://codesandbox.io/s/form-lost-method-2-5-2-forked-mvxs26?file=/App.tsx
一个临时解决方案供参考，通过 formRef.current?.submit() 触发执行 onFinish 获取到校验并格式化后的值

**Comment by chenshuai2144** [comment]
已经修复了，更新下版本
