### ISSUE TITLE
🧐[问题] Vite生产环境构建提示 Rollup failed to resolve import "antd/es/theme/style/css"

### ISSUE THREAD

**Issue by hzeeli** [ant-design/pro-components#7169]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

[vite]: Rollup failed to resolve import "antd/es/theme/style/css" from "node_modules/@ant-design/pro-provider/es/useStyle/index.js".

### 🚑 其他信息
版本信息：
"@ant-design/pro-components": "^2.4.15",
"antd": "^4.23.1",
"vite": "^2.2.3",
"vite-plugin-importer": "^0.2.4"

vite.config.ts 配置

`plugins:[ usePluginImport({ libraryName: 'antd', libraryDirectory: 'es', style: 'css' })]`

**Comment by hzeeli** [comment]
vite.config.ts 配置

`plugins:[
usePluginImport({
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: 'css'
      })]`

**Comment by chenshuai2144** [comment]
忽略一下 antd/es/theme ，为了同时支持 antd4 和 antd@5，或者 usePluginImport 插件
