### ISSUE TITLE
🐛[BUG] BetaSchemaForm layoutType="ModalForm" 受控模式下首次渲染无表单项 

### ISSUE THREAD

**Issue by sushi-su** [ant-design/pro-components#7170]
### 🐛 bug 描述
<img width="766" alt="image" src="https://github.com/ant-design/pro-components/assets/50985188/886088e4-f0bf-446d-8abf-343f1bcd8b85">

### 💻 复现代码

https://codesandbox.io/s/form-lost-method-2-5-2-forked-733wyp?file=/App.tsx

### © 版本信息

- ProComponents 版本: 2.5.5

**Comment by Cmc0** [comment]
我也遇到了，之前都是好的

**Comment by Hongbusi** [comment]
+1

**Comment by Hongbusi** [comment]
我也遇到了这个问题。不能和 `ProTable` 共用 `columns` 很难受。

**Comment by chenshuai2144** [comment]
我记得修掉了 是因为 form 的缓存问题

**Comment by Cmc0** [comment]
我也还是遇到了这个问题

**Comment by broncha** [comment]
I can confirm this is not fixed in 2.6.3 as well

**Comment by tommytroylin** [comment]
2.6.4  + StrictMode 开启 可以稳定复现
2.6.4  + StrictMode 关闭 无法复现
2.6.2 无法复现

**Comment by lookdczar** [comment]
2.8.9 trigger 可以了，但是 open 受控模式不行了
