### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by hungtcs** [ant-design/pro-components#7171]
### 🐛 bug 描述

在全局 ProConfigProvider 中配置的 token 不生效，以 ProLayout 为例，必须在 ProLayout 的 props 中配置 token 才会生效，全局配置不生效。

### 📷 复现步骤

使用 ProConfigProvider  在最外层包裹所有组件，并配置 token。

### 🏞 期望结果

token 生效。

### 💻 复现代码

https://codesandbox.io/s/ji-chu-shi-yong-forked-pio434?file=/App.tsx

### © 版本信息

- ProComponents 版本: 2.5.5
- 浏览器环境 Chrome
- 开发环境 mac OS

### 🚑 其他信息

可能是此处覆盖了全局配置，但是没有从全局配置中继承。

https://github.com/ant-design/pro-components/blob/76bf097aa5644045cc8ee5f3c36f6a228d469804/packages/layout/src/ProLayout.tsx#L920-L925

**Comment by MiniSuperDev** [comment]
I see the same error, please reopen :)

**Comment by zhengtan2003** [comment]
遇到相同问题了

**Comment by xuyanzhuqing** [comment]
一样
