### ISSUE TITLE
👑 [需求]在ProTable中没办法设置默认的分页条数

### ISSUE THREAD

**Issue by lan-an** [ant-design/pro-components#7178]
在^2.3.57这个版本中还可以使用defaultPageSize设置条目数但是在最新的版本中设置就没有作用了。文档也没给出具体的说明。

**Comment by chenshuai2144** [comment]
![image](https://github.com/ant-design/pro-components/assets/8186664/f9097993-8824-4458-812e-aaf4e28552ee)


试了一下是可以的，搞个重现出来？
