### ISSUE TITLE
🐛[BUG] pnpm8 install安装出多个antd版本

### ISSUE THREAD

**Issue by lovewinders** [ant-design/pro-components#7181]
### 🐛 bug 描述

pnpm 8.6.0：pnpm install会安装出2个antd版本，这样会因版本导致下图很多报错

#### 在antd-pro v6 demo
```
pnpm install // pnpm版本 8.6.0
```

#### .npmrc
```
engine-strict=true
shamefully-hoist=true
resolution-mode=highest
registry="https://registry.npmjs.org/"
```

#### 根目录package.json
```
"dependencies": {
    "@ant-design/icons": "^4.8.0",
    "@ant-design/pro-components": "^2.5.5",
    "@umijs/route-utils": "^4.0.1",
    "antd": "^5.5.1"
  },
```

### 🏞 期望结果

期望pnpm 8.6.0执行：pnpm install后只安装1个最新antd版本

### © 版本信息

- ProComponents 版本: "^2.5.5"
- umi 版本："@umijs/max": "^4.0.70",
- 浏览器环境：常见浏览器
- 开发环境 mac OS

### 🚑 其他信息

<img width="1522" alt="image" src="https://github.com/ant-design/pro-components/assets/22837419/3cc4aed5-7246-482c-85f5-33f57522862e">

![image](https://github.com/ant-design/pro-components/assets/22837419/e989db6e-bee3-413a-8e76-592684f83063)

![image](https://github.com/ant-design/pro-components/assets/22837419/3444b1ce-855f-4b79-9f22-e36f69993d33)

![image](https://github.com/ant-design/pro-components/assets/22837419/3e8d84ce-1731-4b63-bb70-17ec77e50812)

**Comment by chenshuai2144** [comment]
pro  组件都是 peerDependencies  的，pnpm  有什么特殊的规则吗

**Comment by lovewinders** [comment]
> pro 组件都是 peerDependencies 的，pnpm 有什么特殊的规则吗

@chenshuai2144 感觉pnpm8是多个大版本冲突以低版本那个为准，或是umijs max的锅
<img width="1437" alt="image" src="https://github.com/ant-design/pro-components/assets/22837419/69e60cbf-3d45-429d-9007-450050d56266">

**Comment by lovewinders** [comment]
我找到问题所在了，就是umijs/max的问题，它的依赖版本是"antd": "^4.20.6",这个umijs太坑了
![image](https://github.com/ant-design/pro-components/assets/22837419/d2ea7c37-88e8-4694-8e9f-dd78038feaef)
