### ISSUE TITLE
👑 [需求] ProTable的组件筛选模块

### ISSUE THREAD

**Issue by Asence** [ant-design/pro-components#7183]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

率属组件：ProTable

### 🥰 需求描述

我希望筛选模块有一个收起筛选头的默认展示多少行的控制字段。现在收起以后默认是只显示了第一行。但是我们公司的筛选条件有点多，所以想询问一下，有没有办法做一个展示多行的功能。

目前使用的版本为
"@ant-design/pro-table": "^2.25.1",
"@ant-design/pro-layout": "^6.10.9",

### ⛰ 功能需求适用场景

![image](https://github.com/ant-design/pro-components/assets/45235142/2e74dd36-e6aa-4880-8685-71383108e813)

![image](https://github.com/ant-design/pro-components/assets/45235142/4f6a1b4f-0315-4435-b046-954a565756ef)

**Comment by Asence** [comment]
@chenshuai2144 大佬，目前有解决办法吗

**Comment by chenshuai2144** [comment]
现在不支持的，试试 defaultColsNumber 能不能满足你的需求
