### ISSUE TITLE
👑 [需求] 希望可以自定义appList组件的渲染

### ISSUE THREAD

**Issue by sansheng741** [ant-design/pro-components#7185]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件
ProLayout

### 🥰 需求描述
希望可以自定义appList组件的渲染

### ⛰ 功能需求适用场景
目前组件的样式太简单了，想自定义组件。

**Comment by chenshuai2144** [comment]
直接来个pr把
