### ISSUE TITLE
🐛[BUG]  安装了@ant-design/pro-components以后build报错

### ISSUE THREAD

**Issue by Asence** [ant-design/pro-components#7186]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

我原本是用的
"@ant-design/pro-table": "^2.25.1",
"@ant-design/pro-layout": "^6.10.9",

但是由于需求的问题，我把依赖改成了
"@ant-design/pro-components": "^2.4.0",
删除了上面2个

然后在执行build命令。
打包失败，报错JavaScript heap out of memory

由于项目比较大，文件数量很多 。我的build命令为
"build": "cross-env ANALYZE=1 REACT_APP_ENV=dev set NODE_OPTIONS=--max_old_space_size=8192&&umi build",

### 🏞 期望结果

正常打包

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]  "@ant-design/pro-components": "^2.4.0",
- umi 版本  "umi": "^3.2.16",
- 浏览器环境
- 开发环境 [e.g. mac OS]  window

### 🚑 其他信息

![image](https://github.com/ant-design/pro-components/assets/45235142/7186a390-1907-4f84-8543-c3ae2d12a5a6)

**Comment by Asence** [comment]
请问我该怎么修改或者怎么解决这个问题

**Comment by chenshuai2144** [comment]
看样子是循环依赖了，这种情况最好要用二分法，删除掉一半的路由再 build，定位到是哪个组件循环了
