### ISSUE TITLE
🐛[BUG] Error that disable:true value does not work in children => we can select tree checkbox in setting popup

### ISSUE THREAD

**Issue by bongcall36** [ant-design/pro-components#7187]
example
const columns = [
    {
      disable: true, 
      title : 'aaa', 
      dataIndex: 'aaa',
      key: 'aaa',
      children : [
      {
        disable: true, 
        title: 'aaa1',
        width: 120,
        dataIndex: 'aaa1',
      },
      {
        disable: true, 
        title: 'aaa2',
        width: 120,
        dataIndex: 'aaa2',
      }]
    },
   ...
  ]

**Comment by chenshuai2144** [comment]
<html>
<body>


columnsState | 受控的列状态，可以操作显示隐藏 | ColumnStateType | -
-- | -- | -- | --



</body>
</html>

要在这里配置哦
