### ISSUE TITLE
🐛[BUG] ant design 5.6.0 token过时警告

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#7188]
<img width="570" alt="image" src="https://github.com/ant-design/pro-components/assets/30397655/4d2375ef-2019-483c-9235-4ce53eae1581">

**Comment by maddemon** [comment]
过期是次要的，菜单选中的背景色不是透明的了，只能强制使用5.5.2，不能升级到5.6

**Comment by zhangrongbing** [comment]
![image](https://github.com/ant-design/pro-components/assets/41978324/cd233fc0-1230-4132-b3e0-6dfef621211b)
看起来真心不舒服

**Comment by zhangrongbing** [comment]
可是我集成了 pro-components
我改如何指定 pro-layout的版本呀？

**Comment by ideaviewes** [comment]
> 过期是次要的，菜单选中的背景色不是透明的了，只能强制使用5.5.2，不能升级到5.6

我使用5.5.2也不行，也是这样的
