### ISSUE TITLE
🧐[问题] ProFormCheckbox layout 参数疑似描述有误

### ISSUE THREAD

**Issue by ldc-37** [ant-design/pro-components#7189]
### 🧐 问题描述

1. https://procomponents.ant.design/components/field-set#proformcheckbox
ProFormCheckbox 实际上并不支持 layout 和 options，这两个参数只在 ProFormCheckbox.Group 上有

2. 咨询：是否有办法让 ProForm 部分表单项使用独立的布局，例如：

<img width="377" alt="image" src="https://github.com/ant-design/pro-components/assets/34739463/007551fe-e911-4d91-8fe0-c9a44ff4965b">

**Comment by chenshuai2144** [comment]
1.  ProFormCheckbox.Group 文档写错了，求 pr
2. 用 ProForm.Group 包一下
