### ISSUE TITLE
🐛[BUG]ProFormColorPicker组件，设置disabled={true} ,组件禁用不生效。

### ISSUE THREAD

**Issue by angOne1** [ant-design/pro-components#7190]
🧐 问题描述
ProFormColorPicker组件，设置disabled={true} ,组件禁用不生效。

💻 示例代码
<ProFormColorPicker
label="end"
name={['secondaryButton', 'bg', 1]}
disabled={true}
>

**Comment by chenshuai2144** [comment]
先尽量别用这个组件了，用 https://ant.design/components/color-picker-cn ，现在为了兼容 antd @4  的用户还不能迁移，以后会迁移掉
