### ISSUE TITLE
文档不知道为什么 感觉难以理解，大概率是我的问题  但我还是想问问

### ISSUE THREAD

**Issue by lizesheng0313** [ant-design/pro-components#7196]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
比如说
<img width="1057" alt="image" src="https://github.com/ant-design/pro-components/assets/23352222/941ac3ba-16ed-4697-92cc-0d5c2574a2af">
这个按钮配置 是配置什么的 没看明白

再比如
<img width="1109" alt="image" src="https://github.com/ant-design/pro-components/assets/23352222/4b1ddd67-496d-4432-9bcf-eaed5e6a7d31">
有些时候指的哪些时候 没看到具体场景  对我这种初级开发者确实难以理解

其它的我就不列举了 不知道官方维护团队是怎么看待这件事

**Comment by chenshuai2144** [comment]
try it
