### ISSUE TITLE
🐛[BUG]ProFormList下，Form.Item设置rules，校验异常

### ISSUE THREAD

**Issue by angOne1** [ant-design/pro-components#7198]
### 🐛 bug 描述
ProFormText 里面设置 rules，提交表单时会校验正常，但是
Form.Item里面设置rules，提交表单时，即使图片有上传ok，rules仍会触发，页面仍然会提示报错。

假如我不使用ProFormList组件，Form.Item里面设置rules就会校验正常。
### 💻 复现代码
        <ProFormList
          name={['socialLinks']}
          itemContainerRender={(doms) => {
            return <ProForm.Group>{doms}</ProForm.Group>
          }}
        >
          {(f, index, action) => {
            return (
              <>
                <ProFormText
                  width="md"
                  name={['link']}
                  label="link"
                  rules={[{ required: true, message: '${label} is required' }]}
                />
                <Form.Item
                  label="icon link"
                  name={['socialLinks', index, 'iconLink']}
                  rules={[{ required: true, message: '${label} is required' }]}
                >
                  <Upload
                    accept="image/png, image/jpeg,.svg"
                    maxCount={1}
                    customRequest={(e) =>
                      customRequest(e, ['socialLinks', index, 'iconLink'])
                    }
                    {...props}
                    listType="picture"
                    defaultFileList={
                      [{
                        uid: '-1',
                        name: 'image.png',
                        status: 'done',
                        url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
                      }]
                    }
                  >
                    <Button icon={<UploadOutlined rev={undefined} />}>
                      Click to Upload
                    </Button>
                  </Upload>
                </Form.Item>
              </>
            )
          }}
        </ProFormList>

### © 版本信息

- ProComponents 版本: "^2.5.5"
- 浏览器环境 google
- 开发环境 [mac OS]

**Comment by ycshill** [comment]
我也遇到了个问题

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，没有解决你的问题。请提供一个在线的重现实例或者一个最小化的代码示例，这样我才能更好地帮助你解决问题。谢谢！

**Comment by stojkov-z** [comment]
我也遇到了个问题，你解决了吗

**Comment by Alexsandro91** [comment]
我也遇到了个问题，你解决了吗
