### ISSUE TITLE
👑 [需求]ProTable删除最后一页唯一一条数据

### ISSUE THREAD

**Issue by Nninth** [ant-design/pro-components#72]
### 🥰 需求描述
目前删除最后一页唯一一条数据后，表格显示为空？

### 🧐 解决方案
判断是否为该页唯一一条数据，若是，删除数据之后自动回到上一页

**Comment by chenshuai2144** [comment]
你需要自己控制一下了，我们不会做这么魔法的事情。
你可以根据页码和 total 做一下判断

**Comment by Nninth** [comment]
> 你需要自己控制一下了，我们不会做这么魔法的事情。
> 你可以根据页码和 total 做一下判断

您好，关于这个问题，有几个不解之处向您请教：

1、设置了两个状态
![image](https://user-images.githubusercontent.com/54738906/89121522-3be10c00-d4f2-11ea-9693-e67fcfd2c8ff.png)
2、ProTable 的 pagination 属性
![image](https://user-images.githubusercontent.com/54738906/89121580-9e3a0c80-d4f2-11ea-90a3-93f3cc1b8457.png)
3、ProTable 的 toolBarRender 属性，“批量删除”点击事件
![image](https://user-images.githubusercontent.com/54738906/89121602-c164bc00-d4f2-11ea-8864-b3aea60518d3.png)
4、获取 DataSource（设定 total 为101）
![image](https://user-images.githubusercontent.com/54738906/89121622-f244f100-d4f2-11ea-8789-0c7996954912.png)
**5、现象**：翻页至最后一页（如第6页），且该页只有一条数据，删除该数据之后，表格页面位于第5页，但是 pagination 显示不正确
**删除前**
![image](https://user-images.githubusercontent.com/54738906/89121741-19e88900-d4f4-11ea-926a-40a6e43121a4.png)
**删除后**
![image](https://user-images.githubusercontent.com/54738906/89121752-3b497500-d4f4-11ea-8c21-b9127f0a0fde.png)
**6、问题**：pagination 的 `showTotal` 属性在此没有生效？请求数据前的 `setPageNumber(pageNo -1)` 也没有立即生效，应该进行什么操作使 pagination 显示正常呢？期待您的回答，感谢~

**Comment by yangzhenwang** [comment]
我也遇到同样的问题  请问解决了吗

**Comment by wjf40390** [comment]
我自己写了一个工具方法：

```
/**
 * reloadTable 兼容table删除最后一页的全部数据，table.reload()回退到上一页
 * @param {*} tableRef tableRef
 * @param {*} deleteNum 删除的任务数
 */
export const reloadTable = (
  tableRef: React.MutableRefObject<ActionType | undefined>,
  deleteNum: number,
) => {
  const cur = tableRef?.current;
  if (!cur || !cur.pageInfo) {
    return;
  }
  const {
    pageInfo: { current, total, pageSize },
  } = cur;
  // 总页数
  const pageNum = Math.ceil(total / pageSize);
  // 最后一页任务数
  const taskNum = total - (pageNum - 1) * pageSize;
  // 删除的是最后一页的任务，并且全部删除
  const lastPageIsEmpey = current === pageNum && deleteNum === taskNum && current !== 1;
  if (lastPageIsEmpey) {
    // 重置为上一页的页码并刷新
    cur.setPageInfo!({
      ...cur.pageInfo,
      current: current - 1,
      total: total - deleteNum,
    });
    cur.reload();
  } else {
    cur.reload();
  }
};
```
在删除成功后调用该方法即可。

![1677033081004](https://user-images.githubusercontent.com/41931794/220505881-5bb85ca0-8c7b-4a2b-a925-e63fc0464974.jpg)

ActionRef 参照https://procomponents.ant.design/components/table?current=1&pageSize=5#actionref-%E6%89%8B%E5%8A%A8%E8%A7%A6%E5%8F%91

**Comment by ChenZiyi921** [comment]
> 我自己写了一个工具方法：
> 
> ```
> /**
>  * reloadTable 兼容table删除最后一页的全部数据，table.reload()回退到上一页
>  * @param {*} tableRef tableRef
>  * @param {*} deleteNum 删除的任务数
>  */
> export const reloadTable = (
>   tableRef: React.MutableRefObject<ActionType | undefined>,
>   deleteNum: number,
> ) => {
>   const cur = tableRef?.current;
>   if (!cur || !cur.pageInfo) {
>     return;
>   }
>   const {
>     pageInfo: { current, total, pageSize },
>   } = cur;
>   // 总页数
>   const pageNum = Math.ceil(total / pageSize);
>   // 最后一页任务数
>   const taskNum = total - (pageNum - 1) * pageSize;
>   // 删除的是最后一页的任务，并且全部删除
>   const lastPageIsEmpey = current === pageNum && deleteNum === taskNum && current !== 1;
>   if (lastPageIsEmpey) {
>     // 重置为上一页的页码并刷新
>     cur.setPageInfo!({
>       ...cur.pageInfo,
>       current: current - 1,
>       total: total - deleteNum,
>     });
>     cur.reload();
>   } else {
>     cur.reload();
>   }
> };
> ```
> 
> 在删除成功后调整使用该方法即可行。
> 
> ![1677033081004](https://user-images.githubusercontent.com/41931794/220505881-5bb85ca0-8c7b-4a2b-a925-e63fc0464974.jpg)
> 
> ActionRef 参考https://procomponents.ant.design/components/table?current=1&pageSize=5#actionref-%E6%89%8B%E5%8A%A8%E8%A7%A6%E5%8F%91

大佬，没有其他办法了吗

**Comment by jiangxiaoxin** [comment]
> 我自己写了一个工具方法：
> 
> ```
> /**
>  * reloadTable 兼容table删除最后一页的全部数据，table.reload()回退到上一页
>  * @param {*} tableRef tableRef
>  * @param {*} deleteNum 删除的任务数
>  */
> export const reloadTable = (
>   tableRef: React.MutableRefObject<ActionType | undefined>,
>   deleteNum: number,
> ) => {
>   const cur = tableRef?.current;
>   if (!cur || !cur.pageInfo) {
>     return;
>   }
>   const {
>     pageInfo: { current, total, pageSize },
>   } = cur;
>   // 总页数
>   const pageNum = Math.ceil(total / pageSize);
>   // 最后一页任务数
>   const taskNum = total - (pageNum - 1) * pageSize;
>   // 删除的是最后一页的任务，并且全部删除
>   const lastPageIsEmpey = current === pageNum && deleteNum === taskNum && current !== 1;
>   if (lastPageIsEmpey) {
>     // 重置为上一页的页码并刷新
>     cur.setPageInfo!({
>       ...cur.pageInfo,
>       current: current - 1,
>       total: total - deleteNum,
>     });
>     cur.reload();
>   } else {
>     cur.reload();
>   }
> };
> ```
> 
> 在删除成功后调用该方法即可。
> 
> ![1677033081004](https://user-images.githubusercontent.com/41931794/220505881-5bb85ca0-8c7b-4a2b-a925-e63fc0464974.jpg)
> 
> ActionRef 参照https://procomponents.ant.design/components/table?current=1&pageSize=5#actionref-%E6%89%8B%E5%8A%A8%E8%A7%A6%E5%8F%91

如果遇到需要自己设置页码的情况，setPageInfo之后会自动触发一次请求，不需要再单独调 reload 方法。

而且遇到批量删除的情况，选中的数据里面可能有不能删除的情况，比如被别的地方正在引用，我们会过滤掉这些数据，把真的能删的数据删掉，所以最后真实的删除数量是不确定的。

相对好的方案是，在删除接口的返回中，返回当前的 total，由前端结合pageInfo判断当前页码还有没有数据。如果有，那直接调用 reload 就可以了。如果没有，那如果接受直接回第1页，那也只是调用 reload(true) 就可以了。如果必须是回到最后一页有数据的，那也可以判断出最后一页的页码，通过 actionRef.current?.setPageInfo({current: xxx}) 更新页码，pro-table内部有个useEffect 监听 pageInfo，变了会自动触发一次 request。
