### ISSUE TITLE
portable自定义搜索项名称👑 [需求]

### ISSUE THREAD

**Issue by skyunBoss** [ant-design/pro-components#720]
### 🥰 需求描述

如题，不支持自定义搜索项名称
![image](https://user-images.githubusercontent.com/29365288/95957699-9b349400-0e32-11eb-96ff-e640bf460d7a.png)

**Comment by chenshuai2144** [comment]
title 支持传入一个function，你可以用 function 的参数做判断。

`((config: ProColumnType<T>, type: ProTableTypes) => ReactNode)`
