### ISSUE TITLE
🐛[BUG]BetaSchemaForm bug 刷新页面columns里面的字段会没掉，ProTabel也是有这个问题

### ISSUE THREAD

**Issue by xian107** [ant-design/pro-components#7200]
@chenshuai2144 大神看下吗

https://github.com/ant-design/pro-components/assets/13252682/d51186fb-89d3-42ff-ac07-f1d3ad4b5a51

终于可以复现出来了
![image](https://github.com/ant-design/pro-components/assets/13252682/45a94302-9147-4c2a-80fa-47c4ab955d87)

guthub地址： https://github.com/xian107/proForm_bug
codesandbox地址 ： ttps://codesandbox.io/s/xenodochial-brattain-jfjqrf

**Comment by a77uu** [comment]
#7170 是不是和这个 Issue 一样？

**Comment by chenshuai2144** [comment]
是的 一起看吧

**Comment by Cmc0** [comment]
现在表单能显示输入框了，但是输入框没有值，要第二次打开，输入框才有值
