### ISSUE TITLE
🐛[BUG] ModalForm modalProps onCancel无效

### ISSUE THREAD

**Issue by qq382724935** [ant-design/pro-components#721]
### 🐛 bug 描述

ModalForm使用visible控制显示隐藏，modalProps传入onCancel隐藏弹出框，右上角叉能调用成功，取消按钮调用无效，使用ModalForm onReset也没反应
### 📷 复现步骤
![image](https://user-images.githubusercontent.com/24310904/95960912-f2d4fe80-0e36-11eb-90f2-839aa8b40cf1.png)

### © 版本信息

- @ant-design/pro-form版本：[1.0.2]
- umi 版本 3.2.23
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
@qq382724935  

```
/**
     * @name 受控的打开关闭
     */
    visible?: DrawerProps['visible'];

    /**
     * @name 打开关闭的事件
     */
    onVisibleChange?: (visible: boolean) => void;
```
