### ISSUE TITLE
🐛[BUG] ProTable 动态搜索表单失效

### ISSUE THREAD

**Issue by xiao-xiansheng** [ant-design/pro-components#7212]
### 🐛 bug 描述
ProTable 动态搜索表单失效
官网文档上也有此问题
https://procomponents.ant.design/components/table?tab=api&current=1&pageSize=5#%E6%90%9C%E7%B4%A2%E8%A1%A8%E5%8D%95%E8%87%AA%E5%AE%9A%E4%B9%89

### 📷 复现步骤
自定义 renderFormItem 根据其他表单项值 渲染不同组件 renderFormItem 不会二次执行

### 🏞 期望结果
能够正常触发

### 💻 复现代码
https://codesandbox.io/s/28qlxd?file=/App.tsx:1659-1673

### © 版本信息

- ProComponents 版本: 5.x.x
- umi 版本 4.0.70
- 浏览器环境 
- 开发环境 [e.g. Windows OS]

**Comment by chenshuai2144** [comment]
修复了，可以重新更新一下
