### ISSUE TITLE
🐛[BUG]希望把每一次发布的版本固定一下

### ISSUE THREAD

**Issue by ldwonday** [ant-design/pro-components#7213]
![image](https://github.com/ant-design/pro-components/assets/4630157/44167502-3d64-42cb-955d-6990ad93842d)
线上环境fa发布后突然出现这个bug，发现是pro-form装了最新的版本导致的，希望pro-component发布时把组件的版本固定下，这样子就不会出现这种问题了

**Comment by ldwonday** [comment]
![image](https://github.com/ant-design/pro-components/assets/4630157/fcdf0b84-a3f2-423b-9c4e-bfc1a1199d78)
赶紧修复下吧，拜托了，到处都是这个错误

**Comment by WuJiY** [comment]
是的 出错了~~~

**Comment by JackRoy1992** [comment]
+1
