### ISSUE TITLE
🧐[问题]ProFormDateRangePicker组件使用中，新建没有问题，编辑的时候，从form中得到的数据显示今天

### ISSUE THREAD

**Issue by Dnzzk2** [ant-design/pro-components#7217]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

新建的时候，不会出现问题，进入编辑状态，数据回显无问题，formSet进去也是moment格式，但是点击编辑按钮，拿到form的值，显示为当天，我set进去的不是当天的，直接点击编辑没有任何问题，但是当我点击时间选择好日期，从form中拿到的值是当天，不知道是什么问题导致的。

### 💻 示例代码

    // 验证表单，通过后拿到表单的值
    const formValue = await form.validateFields();
    console.log(formValue);
 ### 
    // 转化值为相应的格式，新建没有问题
    console.log(moment(formValue.registrationTime[0]).format('YYYY-MM-DD'));

 ###
    // registrationTime是ProFormDateRangePicker的值，第一个打印的registrationTime值没问题，moment转化格式之后的 
    // formValue.registrationStartTime的值是当天，但此转化方式在新建时，并没有出现问题。
    if (registrationTime) {
      console.log(registrationTime); // [M,M] 内部显示的时间没问题
      formValue.registrationStartTime = moment(registrationTime[0]).format('YYYY-MM-DD'); // 6-12当天，非我所选择的时间
      formValue.registrationEndTime = moment(registrationTime[1]).format('YYYY-MM-DD');// 6-12当天，非我所选择的时间
      console.log(registrationTime, formValue.registrationStartTime, formValue.registrationEndTime);
      delete formValue.registrationTime;
    }
 ### 回显的代码
    //编辑回显的代码 转化成moment格式。
      newGroupCurrent.registrationTime = [
        moment(registrationStartTime),
        moment(registrationEndTime),
      ];

### 版本
 "@ant-design/pro-components": "^2.4.12",

### 🚑 其他信息

将ProFormDateRangePicker组件换成Form.Item包裹下的DatePicker.RangePicker组件则不会出现该问题，可以实现我的需求。

**Comment by oxygen-xx** [comment]
{"$L":"zh-cn","$d":"2023-06-01T08:09:55.435Z","$x":{},"$y":2023,"$M":5,"$D":1,"$W":4,"$H":16,"$m":9,"$s":55,"$ms":435}

**Comment by Dnzzk2** [comment]
@oxygen-xx 我这不是ProTable，是在ProForm中使用ProFormDateRangePicker

**Comment by oxygen-xx** [comment]
> @oxygen-xx 我这不是ProTable，是在ProForm中使用ProFormDateRangePicker

你把你的环境和版本补充上，方便人家帮你分析。

**Comment by chenshuai2144** [comment]
看看是不是两份 dayjs 了 😃 我们推荐使用 dayjs 哦

**Comment by Dnzzk2** [comment]
> 看看是不是两份 dayjs 了 😃 我们推荐使用 dayjs 哦

Pro是推荐dayjs吗，我在pro中使用的是momentjs，谢谢回复。

**Comment by 2678041235** [comment]
> ProTable ，查询的时候，日期格式是 ： {"$L":"zh-cn","$d":"2023-06-01T08:09:55.435Z","$x":{},"$y":2023,"$M":5,"$D":1,"$W":4,"$H":16,"$m":9,"$s":55,"$ms":435}

这个问题有解决嘛 我的也是拿到这种格式的数据
