### ISSUE TITLE
🐛[BUG] 通过 token 自定义菜单样式  无法覆盖二级下拉菜单

### ISSUE THREAD

**Issue by Gzbox** [ant-design/pro-components#7218]
<img width="472" alt="image" src="https://github.com/ant-design/pro-components/assets/21010051/f60ecdf1-e4f0-45cb-896d-c2188922fdf0">

主要依赖的版本信息如何：
    "@ant-design/pro-components": "2.5.7",
    "antd": "5.6.1",
    
token 配置信息如下：
```
token:{
      colorBgAppListIconHover: 'rgba(0,0,0,0.06)',
      colorTextAppListIconHover: 'rgba(255,255,255,0.95)',
      colorTextAppListIcon: 'rgba(255,255,255,0.85)',
      header: {
        heightLayoutHeader: 50,
        colorBgHeader:  globalToken?.colorPrimary,
        colorTextMenu: 'rgba(255,255,255,0.75)',
        colorTextMenuSecondary: 'rgba(255,255,255,0.65)',
        colorTextMenuSelected: '#fff',
        colorBgMenuItemSelected: 'rgba(0,0,0,0.15)',
        colorTextMenuActive: 'rgba(255,255,255,0.95)',
        colorTextRightActionsItem: '#dfdfdf',
        colorBgRightActionsItemHover:'#fff',
        colorBgMenuItemHover: 'rgba(0,0,0,0.06)',
        colorBgRightActionsItemHover: 'rgba(0,0,0,0.06)',
      },
      pageContainer: {
        paddingBlockPageContainerContent: 8,
        paddingInlinePageContainerContent: 20,
      },
    },
```

**Comment by Gzbox** [comment]
@chenshuai2144 
被它给覆盖了
<img width="596" alt="image" src="https://github.com/ant-design/pro-components/assets/21010051/dcaa74a2-297b-467e-92d7-2b8abcf6224f">

**Comment by chenshuai2144** [comment]
get 我来看看

**Comment by chenshuai2144** [comment]
想办法绕开了一下，要完美解决还得靠antd 
https://github.com/ant-design/ant-design/blob/46c67ab607aa468de13c256fa1000aba122c2bca/components/menu/style/index.tsx#LL584C24-L584C39

**Comment by Gzbox** [comment]
👍👍

**Comment by Gzbox** [comment]
> 想办法绕开了一下，要完美解决还得靠antd https://github.com/ant-design/ant-design/blob/46c67ab607aa468de13c256fa1000aba122c2bca/components/menu/style/index.tsx#LL584C24-L584C39

这个修复，今天会发版吗？

**Comment by Gzbox** [comment]
@chenshuai2144 
这个能发一版吗？
还是说有发布周期，下一个周期是什么时间？

**Comment by iambocai** [comment]
暂时找到了一个hack手段： 在global.less中覆盖二级下拉菜单的背景色:

```css
.ant-menu.ant-menu-sub.ant-menu-vertical {
  background: rgba(0, 0, 0, 0.85);
}
```

![image](https://github.com/ant-design/pro-components/assets/2259715/5dd1b7c1-0bcf-4b85-b81e-3df433193e1b)

当然css选择条件也许可以写的更严格一些，不过对我的项目来说这么写就够用了（主要是我也不太会写复杂的css select条件...）。一劳永逸的解决还是得靠大佬修复上面说那个覆盖问题。
