### ISSUE TITLE
🐛[BUG] 一级菜单 hover 样式错误

### ISSUE THREAD

**Issue by lbggithub** [ant-design/pro-components#7220]
🐛 bug 描述
umi4 新建的 pro 模版，左侧菜单收起后，一级菜单 hover 样式错误，没有显示出菜单名称

📷 复现步骤
收起菜单后，hover一级菜单

🏞 期望结果
浮层中显示一级菜单名称

💻 复现代码
使用命令新建模版就可以复现

© 版本信息
ProComponents 版本: "@ant-design/pro-components": "^2.5.7",
umi 版本 --- 4
浏览器环境
开发环境 [e.g. mac OS]

**Comment by leshalv** [comment]
+1

**Comment by BBKmaisi** [comment]
+1，什么时候修复一下
