### ISSUE TITLE
🧐[问题] ProLayout 和 UMI一起使用，在umi app.tsx 的 layout中定制 prolayout 的 token 如何将样式设置为动态的 token

### ISSUE THREAD

**Issue by Gzbox** [ant-design/pro-components#7221]
<img width="656" alt="image" src="https://github.com/ant-design/pro-components/assets/21010051/8141bfd2-d1e8-444b-a8ee-5c72188023eb">

我希望这些样式都是从当前主题中读取的颜色，以便我在切换暗黑的时候，能动态的去变化，我该如何处理？
目前我只能通过关闭 umi 的 layout  然后自己配置全局布局来实现，可以直接在 umi 的 app.tsx  运行时配置文件中实现吗？

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/max/data-flow#%E5%85%A8%E5%B1%80%E5%88%9D%E5%A7%8B%E7%8A%B6%E6%80%81

@umi/max 内置了全局初始状态管理[插件](https://github.com/umijs/umi/blob/master/packages/plugins/src/initial-state.ts)，允许您快速构建并在组件内获取 Umi 项目全局的初始状态。

全局初始状态是一种特殊的 Model。

全局初始状态在整个 Umi 项目的最开始创建。编写 src/app.ts 的导出方法 getInitialState()，其返回值将成为全局初始状态。例如：
```

// src/app.ts
import { fetchInitialData } from '@/services/initial';
 
export async function getInitialState() {
  const initialData = await fetchInitialData();
  return initialData;
}
```

在 app.tsx 里面可以 

`const  layout = (initialState)=>LayoutProps`
