### ISSUE TITLE
🐛[BUG] 在LightFilter中使用ProFormSelect的两个bug反馈

### ISSUE THREAD

**Issue by oldevil** [ant-design/pro-components#7225]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

🐛 bug 描述
场景：在LightFilter中使用ProFormSelect
问题1：当ProFormSelect的label是dom时，选中label后，回显的内容为[object,object]
问题2：为了解决问题1，我选择用optionLabelProp自定义回显内容，但是不生效

📷 复现代码
问题1：
```
<LightFilter>
        <ProFormSelect
          name="sex"
          label="性别"
          mode="multiple"
          options={[
            { label: <div>男</div>, value: 'aaa' },
            { label: <div>女</div>, value: 'bbb' },
          ]}
        />
</LightFilter>
```

问题2：
```
<LightFilter>
        <ProFormSelect
          name="sex"
          label="性别"
          mode="multiple"
          options={[
            { label: '男', value: 'aaa' },
            { label: '女', value: 'bbb' },
          ]}
          fieldProps={{
            optionLabelProp: 'value',
          }}
        />
</LightFilter>
```
🏞 期望结果
问题1：能正常回显下拉中可视的label内容
问题2：能按照optionLabelProp指定的key进行回显

© 版本信息
ProComponents 版本: ^2.5.3
umi 版本： umi4 umi max
antd版本：^5.5.2
浏览器环境：chrome 版本 114.0.5735.106（正式版本） (arm64)
开发环境：mac OS

🚑 其他信息
注：去掉LightFilter包裹后，以上问题均不存在

**Comment by SYJ0414** [comment]
在LightFilter包裹的ProFormSelect时，fieldProps里多个属性都没有效果，如optionLabelProp、dropdownRender、onDropdownVisibleChange等没效果，去掉外层LightFilter就没有问题

**Comment by dlspacezero** [comment]
> 在LightFilter包裹的ProFormSelect时，fieldProps里多个属性都没有效果，如optionLabelProp、dropdownRender、onDropdownVisibleChange等没效果，去掉外层LightFilter就没有问题

optionItemRender 也不生效

**Comment by OlyaKastsiukova** [comment]
still reproduced
