### ISSUE TITLE
👑 [需求] ProTable支持简单分页

### ISSUE THREAD

**Issue by udoless** [ant-design/pro-components#7227]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件
ProTable

### 🥰 需求描述
现在的ProTable分页必须要求有total，而有些场景后端返回只包括`还有没有更多数据`字段，比如`has_more`

### ⛰ 功能需求适用场景

有些场景后端返回只包括`还有没有更多数据`字段，比如`has_more`

### 🧐 解决方案

支持简单分页，只用提供`是否有上一页`、`是否有下一页`信息，然后交互上只包含`上一页`、`下一页`按钮。

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
这就不是table了，你试试用list把
