### ISSUE TITLE
🧐[问题] Why use less for styling?

### ISSUE THREAD

**Issue by arifszn** [ant-design/pro-components#723]
Why ant design uses less method for styling? Why not traditional css or scss?

To use less, two additional packages (less and less-loader) are needed. Also less discourages to use inline JavaScript and even turned off in the latest version(^3.x.x). To use pro-component, inline js is needed to enable.

The most problematic situation occurs, when dynamic theming is needed. For example, I need to change primary color in run time. If antd used traditional css variable like: var(--ant-primary-color), I could achieve that easily by overriding the variable. But in current setup, I can not find any solution without breaking Laravel's mix or cra's default configuration. 

I am not a css guy actually so I don't really know why less was needed in the first place. I tried to make it work in Laravel with many struggles but now I am in the verge of switching to alternatives.

**Comment by rdmclin2** [comment]
I suppose less is just a selection for antd, it can be scss or less or something else. 

As for the problem of  changing primary color, refer to https://ant.design/docs/react/customize-theme

**Comment by arifszn** [comment]
> I suppose less is just a selection for antd, it can be scss or less or something else.
> 
> As for the problem of changing primary color, refer to https://ant.design/docs/react/customize-theme

I have checked the doc but how to do it dynamically? And if you are referring to this [article](https://medium.com/@mzohaib.qc/ant-design-dynamic-runtime-theme-1f9a1a030ba0), then again one more plugin to install and not a easy solution compared to overriding css variables.

**Comment by arifszn** [comment]
Used [antd-theme-webpack-plugin](https://github.com/mzohaibqc/antd-theme-webpack-plugin) in the end.
