### ISSUE TITLE
🐛[BUG] 开启多标签后路由使用 redirect 导致一直重定向

### ISSUE THREAD

**Issue by LoptrX** [ant-design/pro-components#7235]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

当开启多标签后首页使用 redirect 重定向到某个路由子菜单会导致一直重定向

### 📷 复现步骤

开启多标签，首页路由 / 配置 redirect 到子菜单

### 🏞 期望结果

正常的使用 redirect 

### 💻 复现代码

这是路由信息，使用 component 时正常，使用 redirect 就会出现问题
`[ { path: '/user', layout: false, routes: [ { name: 'login', path: '/user/login', component: './User/Login', }, ], }, { name: 'analysis', key: 'analysis', icon: 'BarChartOutlined', access: true, routes: [ { exact: true, path: '/analysis/aggregate', name: 'aggregate', access: true, component: './analysis/aggregate', }, { exact: true, path: '/analysis/workbench', name: 'workbench', access: true, component: './analysis/workbench', }, { redirect: './analysis/aggregate', }, ], }  { path: '/', // component: './analysis/aggregate', **redirect: '/analysis/aggregate',** }, { path: '/*', layout: false, component: './404', }, ];`

### © 版本信息

- ProComponents 版本: 2.5.9
- umi 版本 4.0.70
- 浏览器环境 chrome
- 开发环境 win11

### 🚑 其他信息

![16867972663354](https://github.com/ant-design/pro-components/assets/120624326/8356b315-710b-4b3a-839e-f83ac2047610)

**Comment by fnoopv** [comment]
应该提到 ant-design-pro ? pro-components 里面没有路由相关的功能

**Comment by fnoopv** [comment]
看样子是和路由无关的，检查对应组件的`useEffect`，`useEffect`没有传入依赖数组, 导致反复执行

**Comment by LoptrX** [comment]
> 

不是的，页面并没有什么逻辑，纯静态页面，手写的测试数据

**Comment by LoptrX** [comment]
新建了个 demo 发现不能复现问题，应该是业务代码有逻辑问题
