### ISSUE TITLE
🐛[BUG]getFieldsFormatValue和validateFieldsReturnFormatValue缺少返回值问题

### ISSUE THREAD

**Issue by dwdc529** [ant-design/pro-components#7236]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

我表单里面有几个pro select，分别有多选和单选，表单里每个select都有convert和transform，当我使用上述两个方法获取格式化后的值时，单选的select，如果有值是正常的，但是当select的值叉掉后保存，这个属性就没有了。

比如第一次提交表单，select有选值，getFieldsFormatValue返回正常 { prop1:‘aaaa’, prop2:'aaa,bbb,ccc' }
select把 prop1的值叉掉后，想要的是返回{ prop1:'',  prop2:'aaa,bbb,ccc' }，实际返回的是{ prop2:'aaa,bbb,ccc' }

所以，这是正常的设计吗？如果是正常的设计，那岂不是还得结合getFieldsValue做一次合并？
不然这个prop1属性就永远只能保存，不能清空

https://codesandbox.io/s/ji-ben-shi-yong-forked-wz8t3v?file=/App.tsx

![image](https://github.com/ant-design/pro-components/assets/12961611/58ecd1a1-52ee-44d5-92f4-1ec6ec8a1374)

**Comment by chenshuai2144** [comment]
close 是 undefined 不会是 string 的，你如果要搞，可以用 form 的 omitNil 来关闭删除 undefined  的值，如果想变成 string 就要自己特殊处理了
