### ISSUE TITLE
🧐[问题] EditableProTable使用renderFormItem自定义表单搜索项，对于日期组件初始化的问题

### ISSUE THREAD

**Issue by yuanAIhan** [ant-design/pro-components#7243]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
我在EditableProTable之中使用renderFormItem的属性来添加一个自定义的RangePicker组件，添加的时候都不会出现报错，但是点击Edit之后就会出现下述的错误。
![image](https://github.com/ant-design/pro-components/assets/80769611/63548114-11dd-4f09-9a9f-24f000a68e66)
而且我将columns中输出的结果是这样的。
![image](https://github.com/ant-design/pro-components/assets/80769611/42bf2f18-3aa3-45be-be49-0edfaf898f3d)

如果直接添加的时候，对应的时间组件可以正常添加，添加成功以后，我点击编辑的时候，便会出现上述的错误。

我当前使用的版本是4.0的版本，该版本中的RangePicker需要传递的值为一个moment的数组，但是我传递的就是对应的数组，也还是会出现对应的错误。

在已经关闭的issue中我发现了相同的问题，但是并没得到解决的方法。

### 
renderFormItem: (text: string, { record, dataIndex }: any) => {
        const { type, isMul } = record
        if (type === 'text') {
          if (isMul) {
            return <Select mode="tags" allowClear notFoundContent={null} open={false} />
          }
          return <Input />
        } else if (type === 'number') {
          if (isMul) {
            return <Select mode="tags" allowClear notFoundContent={null} open={false} />
          }
          return <InputNumber />
        } else if (type === 'boolean') {
          return (
            <Select>
              <Select.Option value="true">true</Select.Option>
              <Select.Option value="false">false</Select.Option>
            </Select>
          )
        } else if (type === 'date') {
          const defaultValues = [
            moment(record?.defaultValue?.[0], 'YYYY-MM-DD HH:mm:ss').isValid()
              ? moment(record?.defaultValue?.[0], 'YYYY-MM-DD HH:mm:ss')
              : null,
            moment(record?.defaultValue?.[1], 'YYYY-MM-DD HH:mm:ss').isValid()
              ? moment(record?.defaultValue?.[1], 'YYYY-MM-DD HH:mm:ss')
              : null,
          ]
          if (defaultValues?.every(value => moment.isMoment(value))) {
            return <RangePicker showTime format="YYYY/MM/DD HH:mm:ss" value={defaultValues} defaultValue={defaultValues} />
          } else {
            return <RangePicker ranges={{}} />
          }
        } else if (type === 'dateTime') {
          return (
            <RangePicker  />
          )
        }
        return <Input />
      },
###

### 🚑 其他信息
组件的版本信息：
"@ant-design/pro-components": "^2.3.54",
"antd": "^4.20.2",

**Comment by chenshuai2144** [comment]
升级一下 dayjs 的版本这个报错是  api 没对上导致的
