### ISSUE TITLE
🐛[BUG]EditableProTable给column设置valueType为digit时，通过fieldProps设置addonAfter单位，选择后的值脱离了table的控制

### ISSUE THREAD

**Issue by Yezhuming** [ant-design/pro-components#7244]
### 🐛 bug 描述

表单包裹EditableProTable，需要一个数字输入框后面加上单位选择，通过fieldProps设置addonAfter（通过Form.Item包裹的Select组件）后，通过调用外层表单的form.getFieldsValue()无法获取到单位的数据，只能获取到输入的数值

![image](https://github.com/ant-design/pro-components/assets/43959617/febd4c95-f111-424c-bc90-0ec9fef51abf)
只有duration的数据没有durationSuffix

但是通过onValuesChange能触发表单修改，发现能监听到durationSuffix的修改，只是脱离了table
![image](https://github.com/ant-design/pro-components/assets/43959617/07cf7587-a859-41a9-9725-08ff5b8ac780)

### 🏞 期望结果

能在table中获取到durationSuffix

### 💻 复现代码

https://codesandbox.io/s/yu-formitem-pei-he-forked-254ncc

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Yezhuming** [comment]
新的复现代码链接，上面的有问题
https://codesandbox.io/s/yu-formitem-pei-he-forked-254ncc?file=/App.tsx

**Comment by chenshuai2144** [comment]
不支持这种用法的，table 每一行的 name 可以在开发者工具里面看见，是不同的，不支持放个 formItem 进去就能用
