### ISSUE TITLE
👑 [需求]StepsForm auto reset to step one on finish

### ISSUE THREAD

**Issue by HuabeiYou** [ant-design/pro-components#725]
### 🥰 需求描述

Modal分步表单可以在提交后自动重置回第一步吗？Document的例子里提交后再打开Modal依然是最后一步，我也没找到相关的props。链接：https://procomponents.ant.design/~demos/src-form-3

目前我只能传入current的prop给StepsForm，然后自己写了Modal的submitter，onFinish的时候set current=0。不知道有没有更简单的解决方法？

**Comment by chenshuai2144** [comment]
你现在的处理方式是现有最好的了，应该提供一个干掉 dom 的方法
