### ISSUE TITLE
🐛[BUG] Schema Form 使用 DrawerForm 表单不显示

### ISSUE THREAD

**Issue by kimkit** [ant-design/pro-components#7250]
### 🐛 bug 描述

<img width="1512" alt="image" src="https://github.com/ant-design/pro-components/assets/1448791/31b4d686-143b-45d9-b4d4-40b28e00e61d">

### 📷 复现步骤

如上，官网示例就有问题

### 🏞 期望结果

表单正常显示

### 💻 复现代码

无

### © 版本信息

- ProComponents 版本: 2.5.11
- umi 版本 /
- 浏览器环境 chrome 114.0.5735.133 / edge 113.0.1774.57
- 开发环境 macOS Ventura 13.4

**Comment by LengYXin** [comment]
我也遇到了一样的问题。我强制把 "@ant-design/pro-form": "2.12.1", 降低到 了 就好使了

**Comment by LengYXin** [comment]
#7018 貌似是这次提交后 版本到2.13.0导致的。我不确定哈~

**Comment by LengYXin** [comment]
用 patch-package 先打个补丁用着吧
![image](https://github.com/ant-design/pro-components/assets/19631404/6b3812ad-4f2a-4dd2-b783-7c8645fe0404)

**Comment by def-wang** [comment]
这个问题又出现了

**Comment by yaoguoba** [comment]
+1
