### ISSUE TITLE
🐛[BUG] 2.5.11  pro-table 没有类型声明文件

### ISSUE THREAD

**Issue by dxhuii** [ant-design/pro-components#7251]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 2.5.11]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://github.com/ant-design/pro-components/assets/2328917/bd5099f1-9df8-442d-92c9-d15cd7d2e0a3)

**Comment by hsulei** [comment]
3.7.11 也一样
![image](https://github.com/ant-design/pro-components/assets/12029069/7a2a07ba-ea30-44f4-9f83-839de9b5ee12)
![image](https://github.com/ant-design/pro-components/assets/12029069/58ff97da-c2a5-43a5-a06c-9d87f985a3d6)

**Comment by MadratJerry** [comment]
> 3.7.11 也一样 ![image](https://user-images.githubusercontent.com/12029069/246700086-7a2a07ba-ea30-44f4-9f83-839de9b5ee12.png) ![image](https://user-images.githubusercontent.com/12029069/246700073-58ff97da-c2a5-43a5-a06c-9d87f985a3d6.png) 看了一下 3.7.10 导出了typing.d.ts 3.7.11 没有，更新时候，所有的column的render方法都是ts报错，类型都是any， ProTable的pagination onChange的参数也都是any

same problem here

**Comment by dxhuii** [comment]
组件库写死 2.5.10 暂时可以解决，希望官方及时修复

**Comment by dxhuii** [comment]
@hsulei @MadratJerry 

升级到最新版： "@ant-design/pro-components": "^2.6.2",
