### ISSUE TITLE
🐛[BUG] 关于菜单收后起来无法展示菜单名

### ISSUE THREAD

**Issue by killvf** [ant-design/pro-components#7254]
### 🐛 bug 描述

菜单收起来后 鼠标移到图标上 鼠标右侧菜单名无法显示

### 📷 复现步骤
本地环境
![image](https://github.com/ant-design/pro-components/assets/23251559/68987b97-fc48-4aa5-bb45-53eeb05fb2e3)

线上环境
![image](https://github.com/ant-design/pro-components/assets/23251559/94fa950b-a6a8-451b-acf1-8aafe3d92b8a)

### 🏞 期望结果

希望显示菜单名

### © 版本信息

- ProComponents 版本:  6.0.0

**Comment by chenshuai2144** [comment]
修复了，更新下antd和 pro 的版本
