### ISSUE TITLE
🐛[BUG] ProTable expandable 中的 defaultExpandAllRows 属性不生效

### ISSUE THREAD

**Issue by oswayne** [ant-design/pro-components#7255]
### 🐛 bug 描述

 ProTable expandable 中的 defaultExpandAllRows 属性不生效

### 📷 复现步骤

1. 将树形结构数据作为 ProTable 的数据源
2. 配置默认展开所有行：`expandable={{defaultExpandAllRows: true}}`

### 🏞 期望结果

表格中的树形节点全部默认展开

### 💻 复现代码

`<ProTable expandable={{defaultExpandAllRows: true}}/>`

### © 版本信息

- ProComponents 版本: 2.6.2
- umi 版本
- 浏览器环境 Safari 16.5
- 开发环境 macOS 13.4

**Comment by chenshuai2144** [comment]
defaultExpandAllRows 只有默认才会生效，远程加载数据是不行的

**Comment by Deja-vuuu** [comment]
> defaultExpandAllRows 只有默认才会生效，远程加载数据是不行的

为啥这样设计？感觉不合理

**Comment by aspirantzhang** [comment]
应该搞一下这块，很重要啊

**Comment by chenshuai2144** [comment]
default 就是这样的， render 之后才执行的 request，当然就不生效了.

**Comment by abuyao** [comment]
那有没有办法手动让它全部展开？

**Comment by oswayne** [comment]
> 那有没有办法手动让它全部展开？

我目前是通过自己把树中的含有子元素的数据项 ID  取出来，保存到 state 中，再通过 expandedRowKeys 属性实现全部展开功能的

**Comment by guwan** [comment]
> > 那有没有办法手动让它全部展开？
> 
> 我目前是通过自己把树中的含有子元素的数据项 ID 取出来，保存到 state 中，再通过 expandedRowKeys 属性实现全部展开功能的

我也有这样的问题。你这样还是会有个问题，每次都会重新折叠然后再展开，当页面较长时滚动条会滚到上面去。

**Comment by jiaodingding** [comment]
onExpandedRowsChange: (e) => {
  setDefaultExpandedRowKeys(e)
},
expandedRowKeys: defaultExpandedRowKeys,
