### ISSUE TITLE
🐛[BUG] pro-layout 菜单收起展开的时候，存在二级菜单未闭合的话，会导致动画效果卡顿

### ISSUE THREAD

**Issue by fiorayang** [ant-design/pro-components#7257]
### 🐛 bug 描述 
 pro-layout 菜单收起展开的时候，存在二级菜单未闭合的话，会导致动画效果卡顿

### 📷 复现步骤 
官网自带的示例就会存在目前的问题

https://github.com/ant-design/pro-components/assets/32921954/9efd5931-ab12-4da9-b440-6dcbe082a0bf

### 🏞 期望结果 
菜单收起展开的时候，存在二级菜单未闭合的话，动画效果流畅

### © 版本信息

- ProComponents 版本: 2.6.0
- umi 版本 4.0.52
- 浏览器环境 chrome
- 开发环境 windows10

**Comment by chenshuai2144** [comment]
看起来还好？有点掉帧？

**Comment by fiorayang** [comment]
> 看起来还好？有点掉帧？

主要是展开的时候二级菜单标题会出来闪一下，视觉效果很奇怪。之前2.3还好好的，升级了就有这个问题，请问这个有什么办法可以解决吗？

**Comment by keer6** [comment]
+1，收起没问题，展开标题会闪一下

**Comment by keer6** [comment]
> > 看起来还好？有点掉帧？
> 
> 主要是展开的时候二级菜单标题会出来闪一下，视觉效果很奇怪。之前2.3还好好的，升级了就有这个问题，请问这个有什么办法可以解决吗？

解决了踢我一下，xx

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


很抱歉，我是一个 GitHub Issue 助理，无法直接推送更新并解决问题。但我可以为您提供一个可能的解决方案。

这个问题有点复杂，可能是由于动画效果引起的，您可以尝试以下几个步骤来解决或缓解这个问题：

1. 确保您的 React 和相关的依赖库（如 `pro-layout`）都是最新版本，以便获取最新的修复和改进。

2. 尝试将 CSS 动画相关的属性添加到您的样式表中，以使动画更加平滑。比如可以尝试添加以下样式：

```css
transition-property: transform;
transition-duration: 0.3s;
```

3. 检查您的代码，特别是与动画相关的代码是否存在性能问题。确保您的代码逻辑和渲染逻辑是合理且高效的。您可以使用 React 开发者工具来分析性能瓶颈。

4. 如果问题仍然存在，可能需要查看 `pro-layout` 的 GitHub 仓库或官方文档，寻找类似问题的解决方案或提交新的 issue。

希望这些方法可以帮助您解决问题。如果还有其他问题，请随时追问。
