### ISSUE TITLE
🐛[BUG] BetaSchemaForm  layoutType="DrawerForm" 无法渲染 item 

### ISSUE THREAD

**Issue by LengYXin** [ant-design/pro-components#7258]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
代码
![image](https://github.com/ant-design/pro-components/assets/19631404/c79c0348-4ef4-47f3-b28e-34a4fd6fd954)
结果 没有被渲染
![image](https://github.com/ant-design/pro-components/assets/19631404/1c306b29-3ca2-47bc-8f4e-bcdeda3e420a)
简单的排查了一下
<img width="1138" alt="image" src="https://github.com/ant-design/pro-components/assets/19631404/53b3c1de-d78b-4ae1-b2bb-b57794b29a23">

### 📷 复现步骤

我已经把我的配置代码全注释了，只留了 columns 和触发按钮。

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by LengYXin** [comment]
#7250 一样的问题

**Comment by LengYXin** [comment]
@chenshuai2144  我把这行 ref 注释掉就没有这个问题了。不过不清楚有别的影响没 目前只是我本地调试的
<img width="885" alt="image" src="https://github.com/ant-design/pro-components/assets/19631404/4eea0de1-d066-4c7c-a244-79ddfdb51023">

**Comment by chenshuai2144** [comment]
搞个 pr？看起来是 formref 没了

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/issues/7250

fixed
