### ISSUE TITLE
🐛[BUG] LightFilter组件中使用ProFormFieldSet和ProFormSelect，选择完成ProFormSelect值是value不是label

### ISSUE THREAD

**Issue by zhaoyantong** [ant-design/pro-components#7259]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
LightFilter组件中使用ProFormFieldSet和ProFormSelect，单选选择完成后可以拿到value，但是确认后上边显示的是value不是中文

https://codesandbox.io/s/nervous-framework-zz9w7m?file=/src/App.tsx
![image](https://github.com/ant-design/pro-components/assets/45806455/ee41b346-0623-4741-a83d-c995be49da4a)

**Comment by chenshuai2144** [comment]
不要写 name 试试

**Comment by zhaoyantong** [comment]
> 

![image](https://github.com/ant-design/pro-components/assets/45806455/f772fca9-c776-461b-b815-9b496d50f30f)
不写name，确认后不显示已选择的值

**Comment by zhaoyantong** [comment]
> 不要写 name 试试
![image](https://github.com/ant-design/pro-components/assets/45806455/c7e3d023-fa84-454a-bf6a-ca43993d0d56)
不写name，确认后不显示已选择的值

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您提供的信息。

根据您的描述，问题可能是由于在`ProFormSelect`组件中没有正确配置`options`的`label`属性导致的。您可以尝试按照以下步骤解决问题：

1. 在`ProFormFieldSet`中的`ProFormSelect`组件中，确保提供了正确的`options`选项，并正确设置了`label`属性。例如：

   ```tsx
   <ProFormSelect
     options={[
       { value: 'option1', label: '选项1' },
       { value: 'option2', label: '选项2' },
       { value: 'option3', label: '选项3' },
     ]}
     name="select"
     label="选择选项"
   />
   ```

2. 在`ProForm`组件中，确保没有为`ProFormSelect`组件设置了`name`属性，因为您在之前的描述中提到不设置`name`后可以正常获取到`value`值。

   ```tsx
   <ProForm onFinish={handleFinish}>
     <ProFormFieldSet name="test" title="测试组">
       <ProFormSelect
         options={[
           { value: 'option1', label: '选项1' },
           { value: 'option2', label: '选项2' },
           { value: 'option3', label: '选项3' },
         ]}
         label="选择选项"
       />
     </ProFormFieldSet>
     <ProFormSubmitButton>确认</ProFormSubmitButton>
   </ProForm>
   ```

尝试以上步骤后，可以重新运行您的代码并确认问题是否解决。如果问题仍然存在，请提供更多代码和详细的复现步骤，以便我们更好地帮助您解决问题。另外，您也可以查阅以下文档来了解更多关于`ProFormSelect`的信息：

- [ProFormSelect 文档](https://procomponents.ant.design/components/form#proformselect)
- [ProForm 文档](https://procomponents.ant.design/components/form#proform)

希望以上信息能对您有所帮助！如果您还有任何疑问，请随时提问。

**Comment by chenshuai2144** [comment]
现在看起来直接不能用了，我看看

**Comment by chenshuai2144** [comment]
支持了一下 labelFormatter

```tsx
import {
  LightFilter,
  ProFormFieldSet,
  ProFormSelect,
  ProFormText,
} from '@ant-design/pro-components';

export default function App() {
  return (
    <div className="App">
      <LightFilter
        initialValues={{
          name: [
            {
              label: '包含',
              value: 'Like',
            },
            '123',
          ],
        }}
        placement={'bottomLeft'}
      >
        <ProFormFieldSet
          label="筛选"
          name={'name'}
          lightProps={{
            labelFormatter: (value) => {
              return value.join(' ');
            },
          }}
          transform={(value: any) => {
            return {
              filter: [
                {
                  operator: value[0],
                  value: value[1],
                },
              ],
            };
          }}
        >
          <ProFormSelect
            fieldProps={{
              labelInValue: true,
            }}
            valueEnum={{
              Like: '包合',
              NotLike: '不包合',
              Eq: '等于',
              NotEq: '不等于',
            }}
          />
          <ProFormText placeholder="请输入" />
        </ProFormFieldSet>
      </LightFilter>
    </div>
  );
}

```
