### ISSUE TITLE
🐛[BUG][Pro-Layout] PageContainer fixedHeader显示问题

### ISSUE THREAD

**Issue by xiexingen** [ant-design/pro-components#726]
### 🐛 bug 描述

在Pro-Layout中使用，当设置了fixedHeader:false的情况下，PageContainer的距离顶部的距离应该是0
### 📷 复现步骤
没滚动之前正常
![image](https://user-images.githubusercontent.com/7939085/96061770-9faa8c80-0ec6-11eb-95b4-fdca570e1fd3.png)
设置了fixedHeader:false 滚动
![image](https://user-images.githubusercontent.com/7939085/96061941-016af680-0ec7-11eb-9601-716a6a95acbb.png)

### 🏞 期望结果

看是不是可以提供一个配置值比如fixedHeader=0
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个重现地址把

**Comment by chenshuai2144** [comment]
来个重现地址把

**Comment by xiexingen** [comment]
可以就用pro的v5分支，修改
defaultSetting中这两个配置
![image](https://user-images.githubusercontent.com/7939085/96074394-2701fb00-0edb-11eb-9976-3039cea664cf.png)
然后找个使用了PageContainer的页面 加上配置fixedHeader
