### ISSUE TITLE
👑 [需求]ProFormList 能支持下排序功能吗？ 自己封装的，放到valueTypeMap里面使用感觉很卡

### ISSUE THREAD

**Issue by echoyl** [ant-design/pro-components#7263]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
暂时没有计划，你可以debug一下为啥会卡顿，正在是不会的。

**Comment by echoyl** [comment]
> 暂时没有计划，你可以debug一下为啥会卡顿，正在是不会的。

将封装的ProFormList 直接放到 ProForm下没有任何问题，放到 BetaSchemaForm 中使用就炸了，数据大小也就20行*5列。

看了下 BetaSchemaForm 里面的formList 没走renderFormItem 走的是tasks，封装后放到 valueTypeMap 后，每次修改值后就会渲染一次组件，比如input的时候输入快的话看不到字过好久才会显示文本。
