### ISSUE TITLE
👑 prolayout 的滚动条，在不hover的时候可以隐藏掉么

### ISSUE THREAD

**Issue by hohogpb** [ant-design/pro-components#7265]
### 🔩 所属模块或组件

prolayout

### 🥰 需求描述

👑 prolayout 的滚动条，在不hover的时候可以隐藏掉么

### ⛰ 功能需求适用场景

如题

### 🧐 解决方案

暂无

**Comment by chenshuai2144** [comment]
https://juejin.cn/post/7041076781746487304

你需要的是这个
