### ISSUE TITLE
🐛[BUG] ProFormSelect is missing the following properties from type 'ProFormFieldRemoteProps'

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/pro-components#7266]
I am getting the following typescript error.

```
      <ProFormSelect
        name={['idInformationParam', 'nationalityId']}
        label={<Title level={5}>nationality</Title>}
        width="xl"
        options={countries?.map((c) => ({
          label: c.countryName_ENG,
          value: c.countryID,
        }))}
        fieldProps={{ loading: loadingCountries }}
      />
```

Type '{ name: string[]; label: Element; width: "xl"; options: { label: string | undefined; value: number | undefined; }[] | undefined; fieldProps: { loading: boolean; }; placeholder: string; }' is missing the following properties from type 'ProFormFieldRemoteProps': params, request, debounceTime, valueEnumts(2739)

**Comment by chenshuai2144** [comment]
![1687533943794](https://github.com/ant-design/pro-components/assets/8186664/7b06c22b-eb41-470a-88e0-8a5e3792775e)

It seems that there is no problem, try upgrading to the latest version.
