### ISSUE TITLE
@chenshuai2144

### ISSUE THREAD

**Issue by TaurusWood** [ant-design/pro-components#7270]
@chenshuai2144 
我用shouldupdate依然会渲染，也没有生效。

https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-3hdrsv?from-embed=&file=/App.tsx

_Originally posted by @TaurusWood in https://github.com/ant-design/pro-components/issues/7239#issuecomment-1596819286_

**Comment by chenshuai2144** [comment]
更新下  antd ，antd  最近修复了这个问题
