### ISSUE TITLE
接口返回的total直接当作了当前页的条数。但是我设置的一页只有5条 。应该是第1-5条/总共7条

### ISSUE THREAD

**Issue by kabudaLiu** [ant-design/pro-components#7271]
### 🧐 问题描述

接口返回的total直接当作了当前页的条数。但是我设置的一页只有5条 。应该是第1-5条/总共7条

### 💻 示例代码

写了这行代码可以解决，但是我之前 使用这个组件不需要写这个就能正确实现分页
 // pagination={{ pageSize: 5, current: 1 }}

### 🚑 其他信息

>   
![20230625-111315](https://github.com/ant-design/pro-components/assets/130575923/988d4980-0d6e-48c0-ab00-91563e014876)
![image](https://github.com/ant-design/pro-components/assets/130575923/5834c65c-1479-4702-937d-0b4423ec3b13)

**Comment by kabudaLiu** [comment]
解决了。默认是20条一页

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！根据你的问题描述，你遇到了一个接口返回的总条数不正确的问题，并且你设置的每页只有5条数据。你想要正确显示当前页第1-5条/总共7条的信息。问题可能是由于默认的分页设置导致的。你可以尝试在使用的组件中手动设置分页的每页条数为5，来解决这个问题。

在你的代码中，你可以像这样设置分页的每页条数为5：

```jsx
...
pagination={{ pageSize: 5 }}
...
```

这样设置之后，分页组件将按照每页5条数据进行分页，显示第1-5条/总共7条的信息。

如果你发现在之前的使用中并不需要手动设置分页的每页条数，那可能是因为不同的环境或组件版本导致的差异。你可以查看组件的文档，了解具体的默认配置和参数设置。对于Ant Design的分页组件，你可以参考其官方文档：[Pagination](https://ant.design/components/pagination-cn/)。

希望以上解决方案对你有帮助！如果还有其他问题，请随时提问。
