### ISSUE TITLE
🐛[BUG]ProTable筛选列没有入参到request中

### ISSUE THREAD

**Issue by ByYogi** [ant-design/pro-components#7272]
### 🐛 bug 描述
筛选列没有入参到request中

### 📷 复现步骤
地址：
[ProTable 查询表格](https://procomponents.ant.design/components/table?current=1&pageSize=5&tab=api#%E6%9F%A5%E8%AF%A2%E8%A1%A8%E6%A0%BC)
[独立页面](https://procomponents.ant.design/~demos/packages-table-src-components-table-tab-api-demo-single?current=1&pageSize=5)

![image](https://github.com/ant-design/pro-components/assets/111735598/3397faec-e2ab-43ec-85c4-5f15bd23410c)

![image](https://github.com/ant-design/pro-components/assets/111735598/d3a6f3d4-fbe8-4f37-bae6-8464f6379522)

**Comment by chenshuai2144** [comment]
这个用的是是本地的  filter，不走服务器的。

<img width="1013" alt="image" src="https://github.com/ant-design/pro-components/assets/8186664/411a6773-6d45-4523-92fc-9a1abadfdc50">

https://github.com/ant-design/pro-components/blob/275e9c108ec939f13dbea002b5d287a074fce42e/packages/table/src/demos/single.tsx#L60

**Comment by ByYogi** [comment]
配置 `onFilter: false`  就能走服务器了
