### ISSUE TITLE
🐛[BUG]ProTable使用Api请求排序 第三下默认排序未响应

### ISSUE THREAD

**Issue by ByYogi** [ant-design/pro-components#7273]
[文档位置](https://procomponents.ant.design/components/table?current=1&pageSize=5&tab=api#%E6%9F%A5%E8%AF%A2%E8%A1%A8%E6%A0%BC)

https://github.com/ant-design/pro-components/assets/111735598/6f5a03f6-f4a0-4341-ba4d-2e0e728a13f6

**Comment by ByYogi** [comment]
为什么第三下不触发Request @chenshuai2144

**Comment by winil** [comment]
同样遇到了这个问题，请问什么时候解决这个Bug呢？

**Comment by winil** [comment]
有什么解决方案吗@chenshuai2144

**Comment by ByYogi** [comment]
> 同样遇到了这个问题，请问什么时候解决这个Bug呢？

我是开发时有这个bug。生成部署文件后可能就好了，点击三下排序都会请求api

**Comment by winil** [comment]
请问使用的 @ant-design/pro-components 和 antd 分别是哪个版本呢，我升级到最新版本（"antd": "^5.6.3"，"@ant-design/pro-components": "^2.6.2",），部署之后第3下取消排序还是没触发 request@ByYogi

**Comment by ByYogi** [comment]
> 请问使用的 @ant-design/pro-components 和 antd 分别是哪个版本呢，我升级到最新版本（"antd": "^5.6.3"，"@ant-design/pro-components": "^2.6.2",），部署之后第3下取消排序还是没触发 request@ByYogi

不要用最新版ProComp. 这个问题好像就出在v2.6.2
这里有一个 ProComp v2.4.4的[在线demo](https://codesandbox.io/s/antcompro-pai-xu-bu-qing-qiu-requestwen-ti-c45lgt)

**Comment by winil** [comment]
好的，谢谢！

**Comment by zhouzyc** [comment]
> [文档位置](https://procomponents.ant.design/components/table?current=1&pageSize=5&tab=api#%E6%9F%A5%E8%AF%A2%E8%A1%A8%E6%A0%BC)
> 
>  bandicam.2023-06-25.14-20-45-455.mp4

同样问题请问解决了吗 @craxyz

**Comment by ByYogi** [comment]
> 同样问题请问解决了吗 @chenshuai2144
刚刚看了一下，官方文档好像没问题了
