### ISSUE TITLE
多次刷新表格，在请求未响应时，后续请求被忽略

### ISSUE THREAD

**Issue by tzz-v** [ant-design/pro-components#7277]
### 🐛 bug 描述

当我在调用tableRef.current.reload()之后但未收到响应之前，再次调用tableRef.current.reload()，第二次刷新请求会被忽略。

### 📷 复现步骤
出于某种原因，我在组件外面单独维护我的筛选条件项，当我的筛选条件连续发生两次变化的时候，他的刷新只响应了一次。

### 🏞 期望结果
解决这个问题，或提供一个办法绕过这个问题。

### 💻 复现代码

```
React.useEffect(() => {
  // 两次触发
  tableActionRef.current?.reload();
}, [tableFilterInfo]);

```

### © 版本信息

- ProComponents 版本: [e.g. 3.0.20]
- umi 版本
- 浏览器环境
- 开发环境 [mac OS]

### 🚑 其他信息

简单看了下源码，发现loading为true的时候，会直接return空数组
<img width="870" alt="image" src="https://github.com/ant-design/pro-components/assets/45192602/6dcd18ba-86ed-4070-a4d8-f945005d64cd">

**Comment by tzz-v** [comment]
解决了，或者说绕过了，让筛选、排序、刷新等会发送请求的动作和table的loading进行绑定，当table loading为true的时候，禁止用户触发refresh相关动作，直至当前的请求完成。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常好，你的解决方法是正确的。通过将筛选、排序、刷新等发送请求的动作和table的loading状态进行绑定，在table loading为true时禁止用户触发refresh相关的动作，直到当前请求完成。

下面是一个示例代码，展示了如何通过监听loading状态来禁用refresh相关的动作：

```jsx
import React, { useState, useEffect } from "react";
import { Table, Button } from "antd";

const MyTable = () => {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);

  const handleReload = () => {
    // 在发送请求前设置loading为true
    setLoading(true);
    // 这里模拟一个异步请求
    setTimeout(() => {
      // 请求完成后设置loading为false，并更新数据
      setLoading(false);
      setData(getDataFromServer());
    }, 1000);
  };

  useEffect(() => {
    handleReload();
  }, []);

  return (
    <div>
      <Table dataSource={data} loading={loading} />
      <Button onClick={handleReload} disabled={loading}>
        刷新
      </Button>
    </div>
  );
};

export default MyTable;
```

在上面的示例代码中，我们使用`loading`状态来控制Table组件的loading状态，并在发送请求前将loading设置为true，请求完成后将loading设置为false。在Button组件上添加了`disabled={loading}`属性来禁用刷新按钮，在loading为true时禁止用户触发刷新。

此外，你可以通过增加一些额外的界面提示来提醒用户当前正在进行请求，以避免用户的多次刷新操作。

希望这个解决方案能够帮助到你。如果你还有其他问题，请随时向我提问。

**Comment by chenshuai2144** [comment]
等发新版本， 我默认关掉了去抖
