### ISSUE TITLE
🐛[BUG]使用ProTable 报错

### ISSUE THREAD

**Issue by Over-reaction** [ant-design/pro-components#7279]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

使用ProTable 报错 关闭严格模式就不会 但是关闭严格模式不是一个好办法 使用antd一切正常 我看到之前提出的也没有解决方法啊

### 📷 复现步骤
直接使用就会报错

### © 版本信息

"@ant-design/pro-components": "^2.6.2",

### 🚑 其他信息

![image](https://github.com/ant-design/pro-components/assets/88490404/c1eab9b8-ce39-45ad-abea-4d7dc2c013d8)

**Comment by Over-reaction** [comment]
有人遇到过么 求解决

**Comment by ldwonday** [comment]
![image](https://github.com/ant-design/pro-components/assets/4630157/2708bf4d-4aa8-4406-8432-c13e20328713)

去掉这行

**Comment by chenshuai2144** [comment]
等 antd 解决下 里面还是用了这个 api，还要等
