### ISSUE TITLE
🐛[BUG] ProFormList里面嵌套ModalForm下面 ProFormDependency 不能用

### ISSUE THREAD

**Issue by yangjie21** [ant-design/pro-components#7282]
ProFormList里面嵌套ModalForm下面 ProFormDependency 不能用

https://codesandbox.io/s/modal-biao-dan-forked-6t9cp5?file=/App.tsx

<img width="1268" alt="image" src="https://github.com/ant-design/pro-components/assets/19204745/5c81f589-c66b-47ba-bd69-7204f00a66a2">

### © 版本信息

"@ant-design/icons": "5.1.4",
    "@ant-design/pro-components": "2.6.2",
    "antd": "5.6.2",
    "moment": "2.29.4",
    "react": "latest",
    "react-dom": "latest"

**Comment by mtiger95** [comment]
我也遇到了，不过是直接ProFormList里面嵌套 ProFormDependency 不能用，状态不能更新，内部小组件也不能完全渲染label，就第一个label渲染了
