### ISSUE TITLE
🐛[BUG] 使用setFieldsValue给表单的某一项赋值后，满足校验条件，但是校验仍提示。

### ISSUE THREAD

**Issue by zyxmz** [ant-design/pro-components#7290]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

给表单的输入密码随机生成密码后，赋值。该文本框校验条件是要长度大于六，随机生成的密码长度正好满足，但仍提示错误。

### 📷 复现步骤

![Uploading image.png…]()

### 🏞 期望结果

期待setFieldsValue赋值后，能自动校验条件。

### 💻 复现代码

<ProForm.Group>
                  <ProFormText.Password
                    name="password"
                    label="登录密码:"
                    rules={[{ required: true }, { min: 6, message: '密码长度至少为6位。', }]}
                  />
                  <ProFormDependency name={['password']}>
                    {({ password }) => {
                      return (
                        <ProFormText.Password
                          name="repeatPassword"
                          label="重复密码:"
                          rules={[{ required: true }, {
                            validator: (rule, value, callback) => {
                              if (password !== value) {
                                callback('两次密码输入不一致。')
                              }
                              callback();
                            }
                          }]}
                          addonAfter={<Button type="primary" onClick={async () => {
                           formRef.current?.setFieldsValue({ password: '123456' , repeatPassword: '123456'})
                          }}>随机</Button>}
                        />
                      );
                    }}
                  </ProFormDependency>
                </ProForm.Group>

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi，感谢您提供的信息，让我们来看一下问题的解决方案吧。

问题出现在使用`setFieldsValue`给表单赋值后，虽然赋值满足了校验条件，但在界面上仍然提示错误。

要解决这个问题，您可以在调用`setFieldsValue`方法之后，手动触发表单的校验，以更新校验状态。可以使用`validateFields`或`validateFieldsAndScroll`方法进行校验。

以下是针对您的代码示例的修改建议：

```jsx
import { Button } from 'antd';
import { ProForm, ProFormText, ProFormDependency } from '@ant-design/pro-form';

const YourComponent = () => {
  const formRef = useRef();

  const handleRandomPassword = async () => {
    formRef.current?.setFieldsValue({ password: '123456', repeatPassword: '123456' });
    formRef.current?.validateFields(); // 手动触发校验
  };

  return (
    <ProForm
      formRef={formRef}
      onFinish={values => {
        console.log(values);
      }}
    >
      <ProForm.Group>
        <ProFormText.Password
          name="password"
          label="登录密码:"
          rules={[{ required: true }, { min: 6, message: '密码长度至少为6位。' }]}
        />
        <ProFormDependency name={['password']}>
          {({ password }) => {
            return (
              <ProFormText.Password
                name="repeatPassword"
                label="重复密码:"
                rules={[
                  { required: true },
                  {
                    validator: (rule, value, callback) => {
                      if (password !== value) {
                        callback('两次密码输入不一致。');
                      }
                      callback();
                    }
                  }
                ]}
                addonAfter={
                  <Button type="primary" onClick={handleRandomPassword}>
                    随机
                  </Button>
                }
              />
            );
          }}
        </ProFormDependency>
      </ProForm.Group>
    </ProForm>
  );
};

export default YourComponent;
```

在上述代码中，我们通过`handleRandomPassword`函数来处理随机生成密码的逻辑。在调用`setFieldsValue`方法后，我们通过`validateFields`方法手动触发了表单的校验。

这样，当您点击随机按钮随机生成密码并赋值给表单后，表单会自动进行校验，并更新校验状态。

希望这个方案能够解决您的问题。如果您有任何疑问，请随时向我提问。

**Comment by chenshuai2144** [comment]
触发一下重新校验，默认是 onchange  才重新触发，你也可以  api  触发一下
```

 await form.validateFields(namePath, {
        // @ts-expect-error
        recursive: true,
      });
```
