### ISSUE TITLE
表格只想保留toolbar的列设置其他两个不要

### ISSUE THREAD

**Issue by hyl1374961656** [ant-design/pro-components#7291]
![image](https://github.com/ant-design/pro-components/assets/56420042/8ec83127-be22-4037-b947-af8e7488df0a)
只保留这一个功能

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


如果你只想保留表格中的Toolbar列，并移除其他两列，你可以使用Ant Design的ProTable组件，根据你提供的截图，我假设你已经在项目中使用了Ant Design Pro组件库。

首先，你需要根据你的需求配置ProTable组件的columns属性。在columns属性中，你可以为每一列指定要展示的内容以及其他配置选项。对于你的需求，你可以定义一个只包含Toolbar列的配置，而其他两列则为空。

这里是一个示例代码：

```javascript
import { ProTable } from '@ant-design/pro-table';

const columns = [
  {
    title: 'Toolbar',
    dataIndex: 'toolbar',
    key: 'toolbar',
    valueType: 'option',
    render: () => [
      <Button key="edit" type="link" onClick={() => handleEdit(record)}>
        Edit
      </Button>,
      <Button key="delete" type="link" onClick={() => handleDelete(record)}>
        Delete
      </Button>,
    ],
  },
];

const data = [
  // 表格数据
];

const ExampleTable = () => {
  return (
    <ProTable columns={columns} dataSource={data} />
  );
};
```

在这个示例中，我们定义了一个唯一的列，标题为"Toolbar"。我们为该列指定了一个valueType为"option"，这告诉ProTable该列是一个操作列。然后，在render方法中，我们返回了一个包含两个按钮的数组，分别对应"Edit"和"Delete"操作。你可以根据你的需求自定义这些按钮的行为和UI样式。

请确保在组件中导入所需的依赖，并将表格数据传递给ProTable的dataSource属性。

有关更多ProTable的使用和配置，请参考Ant Design ProTable的官方文档：https://procomponents.ant.design/components/table

希望这个解决方案对你有帮助！如果你有任何其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
| 参数 | 说明 | 类型 | 默认值 | 版本 |
| --- | --- | --- | --- | --- |
| options | 指定可选项 | string\[] \|<{ title: ReactNode, value: string, description?: ReactNode, avatar?: link or ReactNode, cover?:ReactNode, disabled?: boolean }> | \[] |
