### ISSUE TITLE
👑 [需求] ProFormList 里面嵌了一个ProFormText ，ProFormText 支持必填

### ISSUE THREAD

**Issue by ycshill** [ant-design/pro-components#7294]
问题：
1: 不显示 红色的星 ，也就是必填的标识；
2: 新增的时候也不会提示必填

期望：能够实现1，2的问题

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi，感谢您的提问！针对您的问题，在ProFormList组件中嵌套ProFormText组件时，如果需要实现必填的功能，可以使用ProFormText的`required`属性。下面是一份示例代码来解决您的问题：

```jsx
import { ProFormList, ProFormText } from '@ant-design/pro-form';

const ExampleForm = () => {
  return (
    <ProFormList name="users" initialValue={[{}]}>
      {(fields, { add, remove }) => (
        <>
          {fields.map((field, index) => (
            <ProFormText
              key={field.key}
              name={[field.name, 'name']}
              fieldKey={[field.fieldKey, 'name']}
              label="姓名"
              placeholder="请输入姓名"
              rules={[
                {
                  required: true,
                  message: '请输入姓名',
                },
              ]}
            />
            // 其他表单项...
          ))}
        </>
      )}
    </ProFormList>
  );
};

export default ExampleForm;
```

解决方案说明：
1. 在ProFormText的`rules`属性中设置`required: true`，这样就会显示红色的星标来表示必填项。
2. `required`属性是用来设置验证规则的必填项，当表单提交时，如果这个字段为空，会自动触发校验并提示必填。
  
具体可以参考Ant Design Pro的官方文档：
- [ProFormList](https://procomponents.ant.design/components/form-list/)
- [ProFormText](https://procomponents.ant.design/components/form/#proformtext)
