### ISSUE TITLE
🐛[BUG] 升级umi4后面包屑选中问题

### ISSUE THREAD

**Issue by zyc329** [ant-design/pro-components#7295]
当前 Issue 未检测到标题，请规范填写，谢谢！

The title of the current issue is not detected, please fill in according to the specifications, thank you!

_Originally posted by @github-actions[bot] in https://github.com/ant-design/pro-components/issues/7293#issuecomment-1608928799_

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好！感谢您提交关于在升级umi4后面包屑选中问题的反馈。

根据您的问题描述，我理解您遇到的问题是在升级umi4后，面包屑选中状态不正确的问题。针对这个问题，您可以尝试以下解决方案：

1. 确保您的路由配置正确：在umi4中，路由的配置方式可能会有所改变。请确保您的路由配置正确，特别是与面包屑相关的路由配置。

2. 使用官方提供的面包屑组件：umi框架提供了内置的面包屑组件，您可以直接使用它。在您的页面组件中添加以下代码：

```jsx
import { Breadcrumb } from 'antd';

export default function MyPage() {
  return (
    <div>
      <Breadcrumb>
        <Breadcrumb.Item>Home</Breadcrumb.Item>
        <Breadcrumb.Item>Category</Breadcrumb.Item>
        <Breadcrumb.Item>Sub-Category</Breadcrumb.Item>
        <Breadcrumb.Item>Current Page</Breadcrumb.Item>
      </Breadcrumb>
      {/* 页面内容 */}
    </div>
  );
}
```

您可以根据您的路由配置，动态生成对应的面包屑。

3. 自定义面包屑逻辑：如果您需要更加灵活地自定义面包屑逻辑，可以使用umi提供的路由API来获取当前页面的路由信息，并根据路由信息生成面包屑。以下是一个简单的示例：

```jsx
import { useEffect, useState } from 'react';
import { Breadcrumb } from 'antd';
import { useLocation, Link } from 'umi';

export default function MyPage() {
  const [breadcrumbData, setBreadcrumbData] = useState([]);

  const location = useLocation();

  useEffect(() => {
    const pathname = location.pathname;
    const paths = pathname.split('/').filter((path) => path !== '');

    // 根据路径生成面包屑数据
    const data = paths.map((path, index) => ({
      path: paths.slice(0, index + 1).join('/'),
      name: /* 通过path获取面包屑的名称，可以根据需要自定义 */,
    }));

    setBreadcrumbData(data);
  }, [location]);

  return (
    <div>
      <Breadcrumb>
        {breadcrumbData.map((item) => (
          <Breadcrumb.Item key={item.path}>
            <Link to={item.path}>{item.name}</Link>
          </Breadcrumb.Item>
        ))}
      </Breadcrumb>
      {/* 页面内容 */}
    </div>
  );
}
```

您可以根据需要修改上述代码来适应您的项目。

此外，您还可以参考umi和Ant Design官方文档以获取更详细的信息和示例代码：

- [umi 路由](https://umijs.org/zh-CN/docs/routing)
- [Ant Design Breadcrumb](https://ant.design/components/breadcrumb-cn/)

希望这些信息和代码能够帮助您解决问题。如有任何进一步的疑问，请随时提问。
