### ISSUE TITLE
🐛[BUG] ProTable request从服务器请求枚举，无法发起请求

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#7296]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProTable request从服务器请求枚举，无法发起请求。配置后未有请求发起

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi，感谢您报告这个问题！我可以为您提供一些关于ProTable请求从服务器请求枚举的解决方案。

首先，请确保您已经正确配置了ProTable，并且指定了用于请求枚举数据接口的URL。以下是一个示例配置：

```jsx
import { ProTable } from '@ant-design/pro-table';

const columns = [
  // ...其他列配置
  {
    title: '枚举列',
    dataIndex: 'enumColumn',
    valueType: 'select',
    request: async () => {
      const response = await fetch('https://your-api-url/enums');
      const data = await response.json();

      return data;
    },
  },
];

const YourTable = () => {
  return <ProTable columns={columns} />;
};
```

在上面的示例中，请确保将`https://your-api-url/enums`替换为您自己的API URL，用于获取枚举数据。

如果您遇到了请求未发起的问题，请确保按照上述示例正确配置了`request`属性。

此外，还要确保请求的URL是可访问的，并且返回符合ProTable的要求的数据格式。具体要求可以参考ProTable的文档：

- ProTable 文档: https://protable.ant.design/api
- ProTable 请求方法说明: https://protable.ant.design/api#request

如果上述解决方案无效，请提供更多关于您的代码和错误信息的详细信息，以便我更好地帮助您解决问题。谢谢！
