### ISSUE TITLE
🧐[问题] ProTable  列表工具栏toolbar的settings，如何增加按钮的同时保留原有的的三个按钮

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#7297]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

ProTable  列表工具栏toolbar的settings，如何增加按钮的同时保留原有的的三个按钮

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


👋 你好！对于你的问题，你可以尝试以下方式来增加按钮并保留原有的三个按钮：

1. 使用 `actionRender` 属性：ProTable 组件提供了 `actionRender` 属性用于自定义操作列的按钮显示。你可以在这个属性中返回一个自定义的 JSX 元素来添加额外的按钮。

示例代码：
```jsx
import { ProTable } from 'pro-table';

const CustomTable = () => {
  // 自定义操作列的按钮
  const actionRender = (_, record) => {
    return (
      <>
        {/* 原有的编辑、删除、复制按钮 */}
        {record.id !== 1 && (
          <>
            <a>Edit</a>
            <a>Delete</a>
            <a>Copy</a>
          </>
        )}

        {/* 新增的自定义按钮 */}
        <a>Custom Button</a>
      </>
    );
  };

  return (
    <ProTable
      // 其他配置项...
      actionRender={actionRender}
    />
  );
};
```

在 `actionRender` 中，我检查了 `record.id` 是否为 1，如果不是，则显示原有的编辑、删除和复制按钮。然后添加了一个名为 "Custom Button" 的自定义按钮。你可以根据自己的需求进行更改和扩展。

2. 使用自定义的工具栏组件：ProTable 组件还提供了 `toolbarRender` 属性，可以用于自定义工具栏的显示。你可以在这个属性中返回一个自定义的工具栏组件来添加额外的按钮。

示例代码：
```jsx
import { ProTable } from 'pro-table';
import { Button } from 'antd';

const CustomToolbar = () => {
  return (
    <div>
      {/* 原有的三个按钮 */}
      <Button>新增</Button>
      <Button>导出</Button>
      <Button>导入</Button>

      {/* 新增的自定义按钮 */}
      <Button>Custom Button</Button>
    </div>
  );
};

const CustomTable = () => {
  return (
    <ProTable
      // 其他配置项...
      toolbarRender={() => [<CustomToolbar />, false]}
    />
  );
};
```

在 `toolbarRender` 中，我返回了一个自定义的工具栏组件 `<CustomToolbar />`，在这个组件中添加了原有的三个按钮，以及一个名为 "Custom Button" 的自定义按钮。

希望这些解决方案能对你有所帮助！如果还有其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
新增了一个 optionsRender 来解决这个问题。
