### ISSUE TITLE
ProForm在ios上会自动聚集第一个输入框🐛[BUG]

### ISSUE THREAD

**Issue by tKlint** [ant-design/pro-components#7298]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
在IOS设备上 ProForm会自动给第一个input元素添加聚焦效果但是并没有拉出键盘。需要触摸下屏幕其他区域这个效果才会消失。

### 📷 复现步骤
比如这个例子： https://procomponents.ant.design/~demos/docs-docs-demo-0在IOS上打开

### 💻 复现代码

return (
 \<ProForm\>
      \<ProFormText name="ok" />
  \</ProForm\>
)
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS] IOS

**Comment by chenshuai2144** [comment]
你可以通过 api 关掉自动  foucs，我们在手机端使用体验很差。也不保证有维护
