### ISSUE TITLE
🐛[BUG] procomponents 2.6.2版本打包发布版本有问题，发布的版本和源码对应不上

### ISSUE THREAD

**Issue by Lands-1203** [ant-design/pro-components#7299]
这是使用npm拉取的包版本2.6.2，
![image](https://github.com/ant-design/pro-components/assets/61341868/acaa04bd-87b2-4581-b6fb-ccbadb1a6d4e)

这是master源码
![image](https://github.com/ant-design/pro-components/assets/61341868/c2e77a3b-fa84-44d6-a1f8-9f2d9af3d8cb)

由于npm拉取的2.6.2版本的`SchemaForm`组件文件中的`formChildrenDoms memo`依赖缺少`!!formRef.current`，导致`ModalForm`中的`useImperativeHandle`更新`formRef`后， 无法更新`formChildrenDoms memo`.

**Comment by sushi-su** [comment]
修复代码在 2.6.2 之后，还没发版

**Comment by silent-tan** [comment]
still meet this problem with react strict mode

version: 2.6.49
