### ISSUE TITLE
🐛[BUG] pro-layout v6.3.0 左上角logo a标签无路径，无法回到首页

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#73]
### 🐛 bug 描述

![QQ浏览器截图20200731220331](https://user-images.githubusercontent.com/3166799/89042803-1630f700-d37a-11ea-857c-89fb994d7625.png)

### 📷 复现步骤

https://preview.pro.ant.design

**Comment by chenshuai2144** [comment]
可以是用 

onMenuHeaderClick | menu 菜单的头部点击事件 | (e: React.MouseEvent<HTMLDivElement>) => void | -
-- | -- | -- | --


这个 api 来附加

**Comment by hihuangwei** [comment]
> 官网是用的这个api
> 
> onMenuHeaderClick	menu 菜单的头部点击事件	(e: React.MouseEvent) => void	-

`onMenuHeaderClick={() => history.push('/')}` mix 模式下无法生效
