### ISSUE TITLE
🐛[BUG]  menu的request配置 受SettingDrawer影响

### ISSUE THREAD

**Issue by zkamisama** [ant-design/pro-components#7302]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

app.ts menu的request配置 受SettingDrawer影响， 如果不使用SettingDrawer就不会触发menu的更新

![微信图片_20230629171835](https://github.com/ant-design/pro-components/assets/6882016/9a68f1e5-ed9b-434a-9130-57857f7b086a)
![微信图片_20230629171843](https://github.com/ant-design/pro-components/assets/6882016/3c778eda-15a3-4bf6-b48a-6538eeb6b4ee)

注释SettingDrawer后 menu的request 不会触发
![微信图片_20230629171853](https://github.com/ant-design/pro-components/assets/6882016/8b941173-3053-49a6-b41f-e2ca43452a93)
![微信图片_20230629171900](https://github.com/ant-design/pro-components/assets/6882016/7019559b-b082-43c2-ac32-d5e24696654d)

依赖
```json
{
"dependencies": {
    "@ant-design/icons": "^4.8.0",
    "@ant-design/pro-components": "^2.5.5",
    "@ant-design/use-emotion-css": "1.0.4",
    "@map-component/react-tmap": "^0.1.4",
    "@tinymce/tinymce-react": "^4.3.0",
    "@umijs/route-utils": "^2.2.2",
    "ahooks": "^3.7.7",
    "antd": "^5.5.2",
    "classnames": "^2.3.2",
    "crypto-js": "^4.1.1",
    "dayjs": "^1.11.8",
    "jsonp": "^0.2.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.9.2",
    "rc-util": "^5.33.0",
    "react": "^18.2.0",
    "react-dev-inspector": "^1.8.4",
    "react-dom": "^18.2.0",
    "react-helmet-async": "^1.3.0",
    "react-transition-group": "^4.4.5"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.1.5",
    "@testing-library/react": "^13.4.0",
    "@types/classnames": "^2.3.1",
    "@types/crypto-js": "^4.1.1",
    "@types/express": "^4.17.17",
    "@types/history": "^4.7.11",
    "@types/jest": "^29.5.2",
    "@types/jsonp": "^0.2.1",
    "@types/lodash": "^4.14.195",
    "@types/react": "^18.2.8",
    "@types/react-dom": "^18.2.4",
    "@types/react-helmet": "^6.1.6",
    "@umijs/fabric": "^2.14.1",
    "@umijs/lint": "^4.0.70",
    "@umijs/max": "^4.0.70",
    "cross-env": "^7.0.3",
    "eslint": "^8.42.0",
    "express": "^4.18.2",
    "gh-pages": "^3.2.3",
    "husky": "^7.0.4",
    "jest": "^29.5.0",
    "jest-environment-jsdom": "^29.5.0",
    "lint-staged": "^10.5.4",
    "mockjs": "^1.1.0",
    "prettier": "^2.8.8",
    "swagger-ui-dist": "^4.19.0",
    "tailwindcss": "^3.3.2",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.5",
    "umi-presets-pro": "^2.0.3"
  },
}
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi，感谢您向 GitHub Issue 助理寻求帮助。我是一位专门处理关于 React 前端问题的助理。请提供您的问题描述，我将尽力为您提供解决方案。

如果您的问题不是关于 React 前端的问题，很抱歉，我只能处理关于 React 的问题。请提供关于 React 的问题，以便我可以为您提供适当的帮助。

**Comment by chenshuai2144** [comment]
<img width="362" alt="image" src="https://github.com/ant-design/pro-components/assets/8186664/b5f9975b-03f2-4dea-81f5-90befb981fa3">

是因为这个，你可以判断一下做个 diff，不修改就不更新。
