### ISSUE TITLE
试试 ： <ProForm layout="horizontal" labelCol={{ span: 3 }} > ......  </ProForm>

### ISSUE THREAD

**Issue by Ceilon** [ant-design/pro-components#7306]
试试 ： <ProForm layout="horizontal" labelCol={{ span: 3 }} > ......  </ProForm>

_Originally posted by @harry0071 in https://github.com/ant-design/pro-components/issues/2533#issuecomment-859327676_
            还是参差不齐的

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢你的提问！根据你的代码示例，看起来你正在使用 Ant Design Pro 的 ProForm 组件，并希望将表单布局设为水平布局，同时设置标签的栅格占据列数为 3。

要实现这个需求，你需要确保你已经正确导入了 ProForm 组件和相关的依赖。然后，你可以使用 `layout` 属性将表单布局设置为水平布局，使用 `labelCol` 属性指定标签的栅格配置。

下面是修改后的示例代码：

```jsx
import { ProForm } from '@ant-design/pro-form';

// ...

<ProForm layout="horizontal" labelCol={{ span: 3 }}>
  {/* 表单项 */}
</ProForm>
```

请注意，`labelCol` 属性接受一个对象，其中的 `span` 属性指定了标签所占据的栅格列数。你可以根据需要进行调整。

关于 Ant Design ProForm 组件的更多用法和配置选项，你可以查阅官方文档：
- [Ant Design ProForm](https://procomponents.ant.design/components/form)

希望这能帮到你！如果你有任何其他的问题，请随时提问。

**Comment by chenshuai2144** [comment]
给提供一个可重现的例子在开issue，看着代码算不了命
