### ISSUE TITLE
🐛[BUG] 当页面有滚动条，弹出的 DrawerForm 也有滚动条的情况下 ，会滚动页面滚动条

### ISSUE THREAD

**Issue by hooliy** [ant-design/pro-components#7313]
### 🐛 bug 描述

当使用 DrawerForm 组件时，当页面有滚动条，弹出的 DrawerForm 也有滚动条的情况下，用鼠标滚动时页面上的滚动条也会滚动。

![image](https://github.com/ant-design/pro-components/assets/3368691/d3d42ea0-5ebe-4cd4-8482-36f2aee26202)

### 🏞 期望结果

只滚动 DrawerForm 组件里的滚动条。

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
如果页面上存在滚动条，并且弹出的 DrawerForm 也有自己的滚动条，那么默认情况下，当你在 DrawerForm 内部滚动时，页面的滚动条会被禁用，即只会滚动 DrawerForm 内部的内容。这是因为滚动事件会在最内层的滚动容器中进行处理。

如果你想要在 DrawerForm 内部滚动时同时保持页面的滚动条可用，你可以尝试阻止事件冒泡。具体来说，当鼠标滚动事件发生时，你可以检查是否滚动到了 DrawerForm 的边界，如果是，则阻止事件继续冒泡到页面上，从而保持页面滚动条的功能。

以下是一个示例的代码片段，展示了如何实现该效果：

```javascript
// 获取 DrawerForm 的元素
const drawerForm = document.getElementById('drawer-form');

// 监听鼠标滚动事件
drawerForm.addEventListener('wheel', (event) => {
  const { scrollTop, scrollHeight, clientHeight } = drawerForm;

  // 判断是否滚动到了边界
  const isScrolledToTop = scrollTop === 0;
  const isScrolledToBottom = scrollTop + clientHeight === scrollHeight;

  // 阻止事件冒泡到页面上
  if ((event.deltaY < 0 && isScrolledToTop) || (event.deltaY > 0 && isScrolledToBottom)) {
    event.stopPropagation();
  }
});
```

请注意，上述代码是一个简单示例，具体实现可能需要根据你的项目和代码框架进行适当调整。另外，确保在正确的时机添加和移除事件监听器，以防止内存泄漏和意外行为发生。

**Comment by hooliy** [comment]
如果页面上存在滚动条，并且弹出的 DrawerForm 也有自己的滚动条，那么默认情况下，当你在 DrawerForm 内部滚动时，页面的滚动条会被禁用，即只会滚动 DrawerForm 内部的内容。这是因为滚动事件会在最内层的滚动容器中进行处理。


@chenshuai2144 内部滚动时,页面的滚动条没有被禁用, 而是页面滚动条也会滚动! 正常应该是只滚动内部, 页面滚动禁用 , 但现在是内外两个滚动条会滚动!
