### ISSUE TITLE
🐛[BUG] 升级到最新版本后，ProLayout 侧边栏展开收缩有重影

### ISSUE THREAD

**Issue by pc110** [ant-design/pro-components#7314]
https://github.com/ant-design/pro-components/assets/29336835/c977b583-c308-412d-929a-b5ceccdc1219

**Comment by keer6** [comment]
而且这个侧边菜单栏的滚动条样式是丢了吗？之前蛮好看的，现在就是原始滚动条了，好丑哦

**Comment by keer6** [comment]
> 而且这个侧边菜单栏的滚动条样式丢了吗？以前蛮漂亮的，现在就是原始滚动条了，好丑哦哦

https://procomponents.ant.design/playground/pro-layout 官网样例就能浮现哦
