### ISSUE TITLE
🐛[BUG] 新版本迭代导致生成的className 不一致

### ISSUE THREAD

**Issue by itmeryn** [ant-design/pro-components#7319]
### 🐛 bug 描述

@pro-components 2.6.3
 
![image](https://github.com/ant-design/pro-components/assets/18156931/854fdf2d-8134-4129-b0bd-baaa95bd225f)

pro-components 2.4.4 
<img width="952" alt="image" src="https://github.com/ant-design/pro-components/assets/18156931/53d58a65-8a62-4a70-950e-45e8a18d192f">

### 🏞 期望结果
保持一致的 className 

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
故意改的，因为无法兼容。我们已经尽力减少 隐形 api 的变更
