### ISSUE TITLE
protable 在设置 scroll={{x:''}}这个属性且设置 fixed: 'right',在一些较大的分辨率时即使滚动条滑动到最右侧，这一列的左侧阴影仍然存在🐛[BUG]

### ISSUE THREAD

**Issue by xxxxxxxk** [ant-design/pro-components#7323]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
设计就是这样的，你可以设置为  max-content  绕开一下
