### ISSUE TITLE
🧐[问题]请问一下使用actionRef.current来存储参数是否存在什么隐形副作用或者bug

### ISSUE THREAD

**Issue by DJGDragon** [ant-design/pro-components#7328]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
在子组件中使用actionRef.current.selectedRows = selectedRows 来存储当前选择的行，便于父组件直接使用actionRef.current.selectedRows 就能获取到最新的值，在代码测试中是可以这样进行使用，但是不知道是不会会造成什么副作用

### 💻 示例代码
![image](https://github.com/ant-design/pro-components/assets/23696556/a3b51283-1f9c-48bb-a145-153fad8e06d2)
![image](https://github.com/ant-design/pro-components/assets/23696556/ced2d112-a7e9-47e6-99cf-9991faa57709)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


👋你好！根据你的问题描述，使用`actionRef.current`来存储参数并没有明显的隐性副作用或bug。这是一种常见的模式，用于在组件之间共享数据。

然而，需要注意的是，直接修改`actionRef.current`的属性可能会导致一些不可预测的行为。由于这是直接修改引用的属性，父组件对这些属性的引用可能会在不同的时间点获取到不同的值。

为了避免潜在的问题，推荐使用`useState`或者`useRef`来管理需要在组件间共享的状态。这样可以确保在React的生命周期中，状态的更新是可追踪、可控制的。

下面给出一个使用`useState`的示例代码：

```jsx
import React, { useState } from 'react';

const ParentComponent = () => {
  const [selectedRows, setSelectedRows] = useState([]);

  // 将setSelectedRows函数传递给子组件
  const actionRef = { current: { setSelectedRows } };

  return (
    <div>
      {/* 父组件通过props将actionRef传递给子组件 */}
      <ChildComponent actionRef={actionRef} />
    </div>
  );
};

const ChildComponent = ({ actionRef }) => {
  const handleSelectRows = (rows) => {
    actionRef.current.setSelectedRows(rows);
  };

  return (
    <div>
      {/* 子组件通过actionRef.current.selectedRows获取最新的选择行 */}
      <button onClick={() => handleSelectRows(['row1', 'row2'])}>选择行</button>
    </div>
  );
};
```

通过使用`useState`，可以确保状态的更新是可控的，并且能够在React的生命周期中正确地触发组件的重新渲染。

希望这个解决方案对你有帮助！如果还有其他问题，请随时提问。
