### ISSUE TITLE
🐛[BUG]在renderFormItem中使用ProFormList，提示ProFormList必须要放到ProForm中，否则会造成行为异常

### ISSUE THREAD

**Issue by AfraXenia** [ant-design/pro-components#7332]
### 🐛 bug 描述
在renderFormItem中使用ProFormList，提示ProFormList必须要放到ProForm中，否则会造成行为异常

### 📷 复现步骤
![image](https://github.com/ant-design/pro-components/assets/138770448/4b15c7ea-191c-4024-bf44-e220dba3fc00)
![image](https://github.com/ant-design/pro-components/assets/138770448/757b5231-4b75-4056-aeaa-380d5ee411e6)

### 🏞 期望结果

不报错并且正常显示
### 💻 复现代码
![image](https://github.com/ant-design/pro-components/assets/138770448/efa194cf-9a9f-42dc-9c9a-f1da5accf1cf)

### © 版本信息

- ProComponents 版本: 2.0.1以上
- umi 版本 4.0.7
- 浏览器环境 Chrome 112
- 开发环境 windows

**Comment by keer6** [comment]
你看看你的ProFormList 是不是从@ant-design/pro-form 导入的？你把所有东西都换成@ant-design/pro-components导入试试

**Comment by AfraXenia** [comment]
> 你看看你的ProFormList 是不是从@ant-design/pro-form 导入的？你把所有东西都换成@ant-design/pro-components导入试试

![image](https://github.com/ant-design/pro-components/assets/138770448/4e24d08c-b582-4fee-bf61-98e48830c2d6)
是直接引用的pro-components

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢提供更多信息。根据你的描述，问题可能是由于引入的库不正确导致的。ProFormList 应该从 `@ant-design/pro-form` 导入，而不是 `@ant-design/pro-components`。请尝试将导入的库更换成正确的版本，然后重新运行代码。

请确保你的代码中的导入语句如下所示：

```javascript
import { ProForm, ProFormList } from '@ant-design/pro-form';
```

如果你还没有安装 `@ant-design/pro-form`，可以通过以下命令进行安装：

```shell
npm install @ant-design/pro-form
```

一旦你修改了导入语句，并重新安装所需的库，你可以在你的代码中使用 `ProFormList` 组件来渲染表单项，并将其放在 `ProForm` 组件中，以确保正常的行为。

此外，你可以在 `@ant-design/pro-form` 的文档中查找更多关于如何正确使用 `ProFormList` 的示例和用法：

- [ProFormList 文档](https://procomponents.ant.design/components/form#proformlist)

希望这能帮助到你解决问题！如果还有其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
是  formRef  还不存在，下次更新就有了，他有点慢
