### ISSUE TITLE
🐛[BUG] 菜单栏折叠时FooterToolbar宽度超出一点点

### ISSUE THREAD

**Issue by mwj610** [ant-design/pro-components#7333]
![image](https://github.com/ant-design/pro-components/assets/52907799/b74721d0-8c36-4a14-906f-71bc1c999072)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，感谢您向我报告此问题。根据您的描述和提供的截图，似乎在菜单栏折叠时，FooterToolbar的宽度超出了一点。

要解决这个问题，您可以尝试以下步骤：

1. 确保您正在使用最新版本的 antd（Ant Design）和 pro-components，以获得最新的修复和功能。

2. 检查您的布局代码，确保正确地使用了栅格系统。FooterToolbar应该是位于容器内部并占满整个宽度。以下是一个示例：

```jsx
import { FooterToolbar } from '@ant-design/pro-layout';

// 在您的组件中使用
<FooterToolbar>这里放置您的内容</FooterToolbar>
```

3. 如果以上步骤无效，您可以尝试为FooterToolbar设置一个固定的宽度，以确保它不超出菜单栏的界限。例如：

```jsx
<FooterToolbar style={{ width: '100%', maxWidth: '1200px', margin: '0 auto' }}>这里放置您的内容</FooterToolbar>
```

请注意，您可以根据实际需要调整宽度值来适应您的页面布局。

如果问题仍然存在，请确保在您的代码中没有其他自定义样式或组件干扰FooterToolbar的宽度，并且确认您是否可以提供更多的代码和细节，以便更好地帮助您解决问题。

此外，您还可以查阅antd和pro-components的官方文档，其中提供了更多关于使用和自定义这些组件的详细信息：

- [Ant Design 官方文档](https://ant.design/docs/react/introduce-cn/)
- [Pro Components 官方文档](https://procomponents.ant.design/)

希望这些信息对您有帮助！如果您有任何其他问题，请随时向我提问。
