### ISSUE TITLE
🧐[问题] DragSortTable: 每次 render 执行时 Table DOM 会销毁重建新的 DOM

### ISSUE THREAD

**Issue by zjfresh** [ant-design/pro-components#7335]
需求：ProTable 的标题栏支持拖动调整宽度
问题：ProTable 下正常，DargSortTable 由于每次更新都会销毁重新创建 Table 的整个 DOM，导致标题栏 DOM 的鼠标事件监听被打断，无法拖动调整

> DndKit 的 DndContext 也会随之增加其内部的自增id 

https://github.com/ant-design/pro-components/assets/28496323/d662a8a2-fe82-4f35-978d-30d0748412c9

DragSortTable 问题示例
[Demo](https://codesandbox.io/s/tuo-zhuai-pai-xu-forked-jqzsm7?file=/App.tsx)

原因：
DragSortTable 在 tableViewRender 中包裹 Table 的封装的 DndContext 组件未使用 useMemo，导致每次更新产生了新的 JSX Node

https://github.com/ant-design/pro-components/blob/338734acc4faf6e85beb525e2e5d24ec7e42c925/packages/table/src/components/DragSortTable/index.tsx#L98-L100

https://github.com/ant-design/pro-components/blob/338734acc4faf6e85beb525e2e5d24ec7e42c925/packages/table/src/utils/useDragSort.tsx#L180-L190

解决：
在 useDragSort 中使用 useMemo 缓存 DndContext
![image](https://github.com/ant-design/pro-components/assets/28496323/81ae1aef-fba7-4ebc-a1a4-a927c071ca98)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！对于你提出的问题，可以尝试按照以下步骤解决：

1. 在 `DragSortTable` 组件的实现中，找到 `tableViewRender` 方法。
2. 在 `tableViewRender` 方法中，可以看到封装了 `DndContext` 组件的部分代码。这里需要修改代码，使用 `useMemo` 来缓存 `DndContext` 组件，以避免每次更新都重新创建组件的问题。
3. 将下列代码添加到 `useDragSort` 方法中：

```javascript
const dndContext = useMemo(() => (
  <DndContext 
    ... // 其他属性
  >
    ...
  </DndContext>
), [/* 需要添加依赖项 */]);
```

4. 确保将之前的 `DndContext` 组件替换为 `dndContext` 变量，如下所示：

```javascript
return (
  <div>
    {dndContext}
    ...
  </div>
);
```

这样，在每次更新时，`DndContext` 组件不会重新创建，从而解决了标题栏 DOM 鼠标事件监听被打断的问题。

此外，如果你在使用 `useDragSort` 遇到其他问题，可以参考 [官方文档](https://github.com/ant-design/pro-components/blob/338734acc4faf6e85beb525e2e5d24ec7e42c925/packages/table/README.md#DndContext) 了解更多详情。

希望以上解决方案能够帮助到你！如果还有其他问题或需要进一步的帮助，请随时提问。
