### ISSUE TITLE
🐛[BUG]EditableProTable 中调用setRowData报错 rowData.some is not function

### ISSUE THREAD

**Issue by atseaside** [ant-design/pro-components#7336]
### 🐛 bug 描述

EditableProTable 中调用setRowData报错 rowData.some is not function

### 📷 复现步骤

EditableProTable 与 FormItem 共用时报错，复现步骤为，在可编辑表格中点击按钮通过ref调用setRowData时报错。
rowData初始值为EditableProTable 的数组数据。调用setRowData(index, {title: 'xxx'}); 修改单行中指定的表格数据时，rowData的值被修改为了 map对象 { index: {title: 'xxx'} }。

### © 版本信息

- ProComponents 版本: ^2.6.3
- antd 版本:  ^4.14.0
- 浏览器环境  114.0.5735.198（正式版本） (x86_64)
- 开发环境 mac OS

**Comment by atseaside** [comment]
antd 版本: ^4.22.8

**Comment by zyc329** [comment]
+1

**Comment by atseaside** [comment]
> +1

如果不想升级 antd v5.x 可以将 antd 版本更换为 v4.x 的最新版 v4.24.0 就不会出现该问题。具体原因未知，待官方回复。

**Comment by atseaside** [comment]
> +1
@zyc329  

这个问题我目前的解决方案是升级antd版本至 v4.24.0。

如果不想升级 antd v5.x 可以将 antd 版本更换为 v4.x 的最新版 v4.24.0 就不会出现该问题。具体原因未知，待官方回复。

**Comment by zyc329** [comment]
> > +1
> 
> 这个问题我目前的解决方案是升级antd版本至 v4.24.0。
> 
> 如果不想升级 antd v5.x 可以将 antd 版本更换为 v4.x 的最新版 v4.24.0 就该问题不会出现。具体原因未知，待官方回复。

我也是可以的本来，代码都写好了，但是部署的时候，走自动化，包没锁（^4.xx），感觉锁了也没用，^会升级，就是getRowData可以用，另外的set都无法使用，我也觉得是某个版本的升级问题

**Comment by Wang-yubo** [comment]
+1

**Comment by Wang-yubo** [comment]
> * 2.6.3

·

> +1

对我来说，把Pro-components降级到2.3.53版本就可以用了，配合antd 4.24.0 正常使用；

**Comment by LoveEocding** [comment]
+1 出现问题
