### ISSUE TITLE
DragSortTable 使用editable属性，更新表格中的内容，会导致正在修改项不选中

### ISSUE THREAD

**Issue by hsulei** [ant-design/pro-components#7339]
在使用`DragSortTable`对`table`中的内容进行修改的时候，尤其修改`input`中的内容，只要有修改`id="DndDescribedBy"`会自增，然后展示的效果，当前被修改 
![image](https://github.com/ant-design/pro-components/assets/12029069/3f80e84b-3a3e-4d92-9729-f54c7b176d86)
被选中状态消失，且通过键盘输入中文，无法实现
<img width="1198" alt="image" src="https://github.com/ant-design/pro-components/assets/12029069/0cbdad6e-9ccb-4072-b2ad-bdfc8dcd6c54">
怀疑问题应该是同[issues 7335](https://github.com/ant-design/pro-components/issues/7335)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常抱歉，我只能处理关于React前端问题。对于你提供的问题，我建议你参考以下方式来解决：

1. 确保你的React版本和antd的版本是兼容的。可以尝试升级React和antd版本，以确保没有已知的问题。
2. 检查DragSortTable组件的文档和示例，确保你正确地配置了editable属性，并且提供了正确的回调函数来处理修改。
3. 根据你提供的截图和问题描述，看起来你正在使用的antd组件可能存在一些bug。我建议你在antd的GitHub仓库或相关社区中提交一个issue，详细描述你的问题并提供复现代码和截图。这样antd的维护人员就可以帮助你解决问题了。
4. 如果你希望尝试其他类似的库，可以考虑使用`react-dnd`和`react-dnd-html5-backend`来实现拖放排序的功能。这是一个常见的React拖放库，拥有许多社区支持和示例。

希望这些建议对你有所帮助！如果你有其他关于React前端问题的疑问，请随时向我提问。

**Comment by chenshuai2144** [comment]
两个尽量不要一起用
这个应该是值更新之后直接的销毁了组件。
