### ISSUE TITLE
🧐 更新API 自动生成需要的 TS 描述信息

### ISSUE THREAD

**Issue by rdmclin2** [ant-design/pro-components#734]
### 🧐 问题描述

为配合 dumi 根据 TS 类型定义自动生成  API 文档，需要对组件的 TS 定义进行改写，注释写法为: 

@ignore：忽略该属性，会生成 hidden: true
@default：属性的默认值，要使用 JSON 格式的数据来配置（双引号）
@name：属性的名称，出现在属性面板上的 label
@description：属性的描述，会出现在属性的解释信息

### 💻 示例代码

```
import * as React from 'react';

export interface Friend {
  /**
   * @description 名字
   */
  name: string;
}

export interface F {
  /**
   * @ignore
   * @default "hihi"
   */
  print: string;

  /**
   * @default [{ "name": "jared" }]
   */
  friends: Friend[];
}

export const C: React.FC<F> = () => {
  return <div>123</div>;
};
```

**Comment by rdmclin2** [comment]
@chenshuai2144 API 注释的写法

**Comment by chenshuai2144** [comment]
### 需要修改的组件

- [ ] ProForm - 高级表单
- [ ] ProLayout - 高级布局
- [ ] ProTable - 高级表格
- [ ] ProList - 高级列表
- [ ] ProCard - 标准卡片
- [ ] ProDescriptions - 定义列表
- [ ] ProField - 原子组件
- [ ] ProSkeleton - 骨架屏

**Comment by rdmclin2** [comment]
暂时不需要改了，采用文档直出API方式了。
