### ISSUE TITLE
🐛[BUG] ProCard的ghost属性生效位置是应用错位置了吗？

### ISSUE THREAD

**Issue by fnoopv** [ant-design/pro-components#7340]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

`ProCard` 的ghost 属性，官网的描述是 `幽灵模式，即是否取消卡片内容区域的 padding 和 卡片的背景颜色`, 但使用时是取消了tab区域的padding和背景颜色

### 📷 复现步骤

[复现链接](https://codesandbox.io/s/nifty-galois-3qlvdy?file=/src/App.tsx)
背景颜色为红色，设置ghost之后tab区域变成透明了，可以看到背景的红色

### 🏞 期望结果

ghost应该取消卡片内容区域的 padding 和 卡片的背景颜色, 而不是tab区域的

### 💻 复现代码

[复现链接](https://codesandbox.io/s/nifty-galois-3qlvdy?file=/src/App.tsx)

### © 版本信息

- ProComponents 版本: 2.6.4
- umi 版本 没有使用
- 浏览器环境 chrome 114
- 开发环境 arch linux kde

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您提交的问题。在您提供的代码示例中，您提到 `ProCard` 的 `ghost` 属性和 `bodyStyle` 属性在使用时并没有按预期生效。

根据您的描述，`ghost` 属性应该取消卡片内容区域的 padding 和卡片的背景颜色，而不是取消 tab 区域的样式。同时，您也提到 `bodyStyle` 属性也没有生效。

首先，关于 `ghost` 属性的问题，根据官方文档，`ghost` 属性默认为 `true`，取消了卡片内容区域的 padding 和背景颜色。但在您提供的代码示例中，我没有找到任何使用 `ProCard` 的代码。请确保您在代码中正确使用了 `ProCard` 组件，并正确设置了 `ghost` 属性。

对于 `bodyStyle` 属性，根据 Ant Design Pro 组件库的文档，`bodyStyle` 属性用于自定义卡片内容区域的样式。您可以通过传递一个对象给 `bodyStyle` 属性来设置样式，例如：

```jsx
<ProCard
  title="Card Title"
  ghost
  bodyStyle={{ padding: '20px', backgroundColor: '#fff' }}
>
  Card Content
</ProCard>
```

请确保您的代码中正确使用了 `bodyStyle` 属性，并传递了正确的样式对象。

如果您的问题仍然存在，请提供更多的代码细节以便我们更好地帮助您解决问题。另外，您也可以提供相关的截图或其他信息，以便更好地理解和复现问题。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/blob/17ccf69bb4af2e6ffdf3d992b5cff5b6faeadafc/packages/card/src/components/Card/style.ts#L80-L81

代码看起来没问题，搞个重现吧

**Comment by fnoopv** [comment]
是我理解有点问题，是针对`tabs`中配置的`items`里的内容不生效
