### ISSUE TITLE
🧐[问题]ProTable如何在startEditable编辑前，手动处理row的初始值？

### ISSUE THREAD

**Issue by Handpear** [ant-design/pro-components#7342]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

期望 Input 输入框中的内容初始值为 myPath 而不是 fullPath，
在 `action?.startEditable?.(row.id)` 之前是否有机会处理表单初始值？或者说需要接管整个 ProTable 的 form 实例？
我不太熟悉 Pro，希望得到一个示例

### 💻 示例代码

https://codesandbox.io/s/bold-browser-8kgswf?file=/src/App.js

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！针对你的问题，我了解到你想要在 ProTable 的 startEditable 编辑前手动处理 row 的初始值，确保 Input 输入框中的内容初始值为 myPath 而不是 fullPath。

根据你的描述，我建议你使用 ProTable 的 onRow 事件来自定义行的操作行为。在该事件中，你可以手动更改行数据的初始值。

你可以按照以下步骤操作：

1. 在 ProTable 组件上添加 onRow 属性，并指定一个处理函数。示例如下：

```jsx
<ProTable
  // 其他属性...
  onRow={(record) => ({
    onClick: () => {
      // 处理行点击事件
    },
    // 如果需要编辑前的处理，则可以在这里处理初始值
    onStart: () => {
      if (record.fullPath) {
        record.myPath = record.fullPath;
      }
    },
  })}
/>
```

2. 在 onStart 函数中，你可以使用 if 判断，如果行数据的 fullPath 存在，就将其赋值给 myPath 字段。

这样，当你触发 startEditable 事件时，表单的初始值会被正确赋值。

注意：上述示例是基于 antd ProTable 的假设，如果你使用的是其他库或框架，可能需要针对相应的 API 进行修改。

希望这个解决方案对你有帮助！如果还有任何问题，请随时向我提问。

**Comment by chenshuai2144** [comment]
不太行，一个数据处理起来很麻烦。你可以开始之后 setRowData
```

   editorFormRef.current?.setRowData?.(config.index!, {
                    title: '动态设置的title' + i,
                  });
```
