### ISSUE TITLE
ProFormMoney 无法键盘输入-0.1  🐛[BUG]

### ISSUE THREAD

**Issue by lluoxiao** [ant-design/pro-components#7344]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProFormMoney 无法键盘输入-0.x 的数值；
键盘输入-0的时候，逻辑规则会自动将数值转化成0，导致无法按正常顺序输入-0.1之类大于-1的负数

### 🏞 期望结果
需要支持按正常顺序输入大于-1的负数

### © 版本信息

官网上示例就可以复现操作

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！对于你提出的问题，我理解你遇到了在 ProFormMoney 组件中无法键盘输入小于 -1 的负数的问题。为了解决这个问题，你可以尝试通过自定义校验规则来实现。

首先，在 ProFormMoney 组件上，你可以使用 `validator` 属性来自定义校验规则。你可以利用正则表达式来判断输入的数值是否符合要求。以下是一个示例代码：

```jsx
import { ProFormMoney } from 'ant-design-pro-form';

const CustomProFormMoney = () => {
  // 自定义校验规则
  const customValidator = (rule, value) => {
    if (value < -1) {
      return Promise.reject('请输入大于-1的负数');
    }
    return Promise.resolve();
  };

  return (
    <ProFormMoney
      name="money"
      label="Money"
      fieldProps={{
        formatter: (value) => `$ ${value}`,
        parser: (value) => value.replace('$', ''),
      }}
      validator={customValidator}
    />
  );
};

export default CustomProFormMoney;
```

在这个示例中，我们传入了一个自定义的校验规则 `customValidator`，这个规则会在表单提交前进行校验。如果输入的数值小于 -1，校验将会失败并显示错误信息。

请注意，在 `ProFormMoney` 组件中，我们还使用了 `formatter` 属性来格式化输入的数值。在这个示例中，我们在输入框中显示的数值前面添加了 `$` 符号。

希望这个解决方案对你有帮助！如果你还有其他问题，请随时告诉我。

**Comment by chenshuai2144** [comment]
设置一下 min，默认的 min 是 0
