### ISSUE TITLE
🧐[可编辑表格EditableProTable有没有方法可以直接删除一行?(不使用行内自带的删除)]

### ISSUE THREAD

**Issue by ASAMUL** [ant-design/pro-components#7346]
🧐 问题描述
可编辑表格EditableProTable有没有方法可以直接删除一行?(不使用行内自带的删除)

详细地描述问题，让大家都能理解
-->
问题大概就是,需要在别的地方通过rowKey删除指定的一行,用表格的ref只有新增的方法
希望得到帮助,谢谢

**Comment by ASAMUL** [comment]
没有useEditableUtils 这个对象.是我版本太低了吗?我的版本号是    "@ant-design/pro-table": "^2.61.0",希望得到帮助,谢谢

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，针对您使用的版本 @ant-design/pro-table@2.61.0，确实没有提供`useEditableUtils`对象。在该版本下，您可以尝试使用以下方法来删除表格中的一行数据：

首先，你需要获取 EditableProTable 的 ref 引用，以便在其他地方操作表格：

```jsx
import { useRef } from 'react';
import { EditableProTable } from '@ant-design/pro-table';

const YourComponent = () => {
  const tableRef = useRef(null);

  // 删除指定行
  const deleteRow = (rowData) => {
    tableRef.current.removeEditRecord(rowData.key);
  };

  return (
    <EditableProTable
      // 其他配置项...
      rowRef={tableRef}
    />
  );
};
```

上述代码中，我们通过`tableRef.current.removeEditRecord(rowData.key)`来删除指定的一行。请确保在渲染 EditableProTable 时，将其 `ref` 属性设置为 `rowRef`。

希望这个解决方案对您有帮助。如果还有其他问题，请随时提问。
