### ISSUE TITLE
🐛[BUG] SelectLang does not effect to dayjs.locale

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/pro-components#7349]
I have a two type of languages.
- en
- tr

When I changed language by SelectLang component, dayjs.locale does not affecting.

console.log(dayjs.locale()); always return 'en'.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi there! It seems like you are facing an issue where the `dayjs.locale()` is not being affected when changing the language using the `SelectLang` component. To resolve this, you can follow the steps below:

1. Make sure you have properly installed and imported the necessary dependencies. You need to have both `dayjs` and `dayjs/locale` packages installed.

   ```
   npm install dayjs
   npm install dayjs/locale
   ```

2. Import the required locales in your code. In your case, you need to import the 'en' and 'tr' locales:

   ```javascript
   import dayjs from 'dayjs';
   import 'dayjs/locale/en';
   import 'dayjs/locale/tr';
   ```

3. Create a function that sets the locale based on the selected language. This function should be triggered when the language is changed. This can be achieved by adding an `onChange` event handler to your `SelectLang` component.

   ```javascript
   const handleLanguageChange = (selectedLanguage) => {
     if (selectedLanguage === 'tr') {
       dayjs.locale('tr');
     } else {
       dayjs.locale('en');
     }
   };
   ```

4. Ensure that you are correctly passing the selected language value to the `handleLanguageChange` function.

   ```javascript
   <SelectLang onChange={handleLanguageChange} />
   ```

By following these steps, the `dayjs.locale()` should be affected when changing the language using the `SelectLang` component. Remember to include the necessary import statements and library installations.

You can find more information about `dayjs` and its locale customization in the official documentation: 

- `dayjs` documentation: https://day.js.org/
- `dayjs` locale documentation: https://day.js.org/docs/en/i18n/i18n

**Comment by xXAvoraXx** [comment]
SelectLang procuded by Umi, So I can't change.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


I see, if you are using the `SelectLang` component provided by Umi and unable to change it, you can still manually change the `dayjs.locale()` based on the selected language. Here's how you can do it:

1. Import the required dependencies and locales in your code:

```javascript
import dayjs from 'dayjs';
import 'dayjs/locale/en';
import 'dayjs/locale/tr';
```

2. Create a function that sets the locale based on the selected language. This function should be triggered when the language is changed. You can use the existing `onChange` event handler of the `SelectLang` component. 

```javascript
const handleLanguageChange = (selectedLanguage) => {
  if (selectedLanguage === 'tr') {
    dayjs.locale('tr');
  } else {
    dayjs.locale('en');
  }
};
```

3. Make sure that you are passing the selected language value to the `handleLanguageChange` function within the `onChange` event handler of the `SelectLang` component. Please note that the actual implementation may vary based on your code structure.

```javascript
<SelectLang onChange={handleLanguageChange} />
```

With the above steps, you should be able to manually change the `dayjs.locale()` based on the selected language, even if you cannot modify the `SelectLang` component provided by Umi.

Remember to handle any other logic or state updates in your application that may be required when the language changes.

**Comment by chenshuai2144** [comment]
umi 有 moment2dayjs 的插件，你可以使用这个插件

**Comment by xXAvoraXx** [comment]
> umi 有 moment2dayjs 的插件，你可以使用这个插件

Yes, I am using this plugin already. The problem is having to manually change the language. In previous ant design pro versions, when the language was changed, the moment locale was also changed.

**Comment by chenshuai2144** [comment]
Go to umi to submit a PR? The umi authors do not support the use of DayJS
