### ISSUE TITLE
🐛[BUG] sider bg color 表现不一致

### ISSUE THREAD

**Issue by 0x457** [ant-design/pro-components#7350]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤

设置了colorBgMenuItemSelected颜色后，选中item生效了，父menu的背景色不变，但是text颜色为白色，2者都是menu item，父子关系，背景色表现不一样，那也应该提供一个父背景token吧，反正很奇怪，即然用一样的text color，bgcolor为啥不一致
### 💻 复现代码
![image](https://github.com/ant-design/pro-components/assets/5813610/11736f20-a295-4a35-894f-4e5ada6c6e6a)

![image](https://github.com/ant-design/pro-components/assets/5813610/82d994c0-1dde-468f-aad1-88ffbf577d9e)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 4
- 浏览器环境
- 开发环境 [e.g. mac OS]
![image](https://github.com/ant-design/pro-components/assets/5813610/e2cb628d-38ff-4cc5-8e69-a459ae899b96)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi there,

非常感谢你提出的问题！我是这个 GitHub Issue 助理，专门处理与 React 前端相关的问题。对于你描述的问题，我很抱歉，但是缺少一些重要的细节，例如代码示例和相关文档链接。我需要更多信息来帮助你解决问题。

首先，关于背景色不一致的问题，根据你提供的截图和描述，看起来是一个 CSS 样式的问题。可能是因为父组件和子组件的样式设置不一致，导致背景色表现不同。尝试检查以下几个方面来解决问题：

1. 确保父组件和子组件都使用了相同的 CSS 类名或者样式属性，比如 `bgColorMenuItemSelected`。
2. 检查两个组件的继承关系和样式优先级。子组件的样式可能会覆盖父组件的样式，导致表现不一致。你可以尝试使用 `!important` 来提高父组件样式的优先级。

可以提供更多的代码示例和相关文档，我就可以帮你更详细地解释并解决该问题。还有，如果你有任何其他关于 React 前端的问题，也可以告诉我哦！

期待你的回复！

**Comment by chenshuai2144** [comment]
升级到最新的antd 试试，估计是token覆盖失效了。

antd 新版本改了一下token的名字，理论上你这洋和官网一样的应该都没问题
