### ISSUE TITLE
🐛[BUG]  ProFormUploadButton  配置 width 无效

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#7351]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

![image](https://github.com/ant-design/pro-components/assets/3166799/e96eddb4-3089-4c00-abf1-d53555b1cb8c)

**Comment by hihuangwei** [comment]
@chenshuai2144 看看这个问题吧

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


嗨 @chenshuai2144，

感谢您的提醒！我们继续处理这个问题。

对于 ProFormUploadButton 组件配置 width 无效的问题，您可以尝试以下几种解决方案：

1. 使用 className 设置宽度：尝试为 ProFormUploadButton 组件添加一个 className，并在 CSS 中设置宽度。
```jsx
import { ProFormUploadButton } from 'pro-components';
import 'pro-components/dist/button/style/index.less'; // 引入样式文件

...

<ProFormUploadButton className="custom-upload-button" />

...
```

在 CSS 文件中：
```css
.custom-upload-button {
  width: 200px; /* 根据实际需求设置宽度 */
}
```

2. 使用 CSS-in-JS 库设置宽度：如果您的项目使用了 CSS-in-JS 库，如 styled-components 或 emotion，可以在样式中直接设置宽度。
```jsx
import { ProFormUploadButton } from 'pro-components';
import 'pro-components/dist/button/style/index.less'; // 引入样式文件
import styled from 'styled-components';

const CustomUploadButton = styled(ProFormUploadButton)`
  width: 200px; /* 根据实际需求设置宽度 */
`;

...

<CustomUploadButton />

...
```

3. 使用 style 属性设置宽度：直接在 ProFormUploadButton 组件上使用 style 属性来设置宽度。
```jsx
<ProFormUploadButton style={{ width: '200px' }} />

```

请注意确保已正确导入所需的组件和样式文件。

如果尝试了以上解决方案仍然无效，可能是 ProFormUploadButton 组件本身的问题。建议您在 GitHub 上向组件作者报告此问题，并提供详细的复现步骤和代码示例，以便他们能够帮助您解决问题。

希望这些解决方案对您有所帮助！如果您有任何其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
itemRender | 自定义上传列表项 | (originNode: ReactElement, file: UploadFile, fileList: object[], actions: { download: function, preview: function, remove: function }) => React.ReactNode | - | 4.16.0
-- | -- | -- | -- | --




用这个自己实现，或者要给 form 实现一下的。antd  不支持控制
