### ISSUE TITLE
🐛[BUG] protable 时间组件搜索条件格式问题

### ISSUE THREAD

**Issue by zyc329** [ant-design/pro-components#7355]
### 🐛 bug 描述

![image](https://github.com/ant-design/pro-components/assets/51154195/6afaadd9-beef-4e0c-ae3b-291ab4664be7)

### 📷 复现代码
{
      title: '创建时间',
      dataIndex: 'createdTime',
      valueType: 'dateRange',
      search: {
        transform: (value) => {
          return {
            startDateStr: value[0],
            endDateStr: value[1],
          };
        },
      },
      colSize: 2,
      render: (_, record) => record.createdTime,
    },

### 🏞 期望结果

之前的 年-月-日

### © 版本信息

- ProComponents 版本: [e.g. ^2.6.4]
- umi4
- edge
- 开发环境 [e.g. mac OS]

**Comment by zyc329** [comment]
这种返回结果我连moment都转不了

**Comment by lovewinders** [comment]
建议用dayjs替代momentjs

**Comment by AlexErnsberger** [comment]
> 这种返回结果我连moment都转不了

+1，我也遇到了。

**Comment by AlexErnsberger** [comment]
dayjs版本问题，我项目中用的版本是1.11.1。但是pro-components用的是1.11.9。替换day.js版本后问题解决

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您提供的信息和复现代码。根据您的问题描述，我理解到您在protable时间组件的搜索条件中遇到了日期格式问题。

根据您提供的代码，如果您想要以"年-月-日"的格式进行搜索，可以使用dayjs库进行处理。请确认您的项目中已经安装了dayjs。

根据您的描述，您需要将日期范围转换为{startDateStr: 'xxxx-xx-xx', endDateStr: 'xxxx-xx-xx'}的格式。您可以按照以下方式进行转换：

```javascript
import dayjs from 'dayjs';

// 获取选择的日期范围
const handleDateRangeChange = (value) => {
  // 将日期范围的起始日期和结束日期格式化为'年-月-日'的格式
  const startDateStr = dayjs(value[0]).format('YYYY-MM-DD');
  const endDateStr = dayjs(value[1]).format('YYYY-MM-DD');

  // 返回转换后的结果
  return {
    startDateStr,
    endDateStr,
  };
};
```

在代码中，我们使用dayjs将选择的日期范围进行格式化，并返回转换后的格式。

然后，将`handleDateRangeChange`方法应用到您的搜索配置中：

```javascript
{
  title: '创建时间',
  dataIndex: 'createdTime',
  valueType: 'dateRange',
  search: {
    transform: handleDateRangeChange,
  },
  colSize: 2,
  render: (_, record) => record.createdTime,
},
```

这样配置后，您应该可以正常获得格式为"年-月-日"的搜索条件。

如果您的项目中没有安装dayjs，请使用以下命令安装：

```shell
npm install dayjs
```

希望这个解决方案能够帮助到您！如果您还有任何问题，请随时提问。

**Comment by chenshuai2144** [comment]
这种的一般是两份dayjs导致的，那个实例是就版本的 dayjs 新版本的不认

**Comment by killer-wu** [comment]
> 

这样解决版本兼容的问题，可是无法汉化了，呜呜呜~
