### ISSUE TITLE
🐛[BUG] transformKeySubmitValue 方法中貌似直接忽略了 falsy 值

### ISSUE THREAD

**Issue by tommytroylin** [ant-design/pro-components#7357]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

使用 transform 尝试修改提交的表单值时。返回空字符串。但 submit 时结果无变化

若返回 { [key]: "" } 则可成功修改

### 📷 复现步骤

设置表单 omitNil 为 false
```js
const columes = [
  {
    valueType: 'select',
    transform: (value, key) => {
      if (value === undefined) {
        return '';
      }
      return value;
    },
    // 下面写法 ok
    // transform: (value, key) => {
    //   if (value === undefined) {
    //     return { [key]: '' };
    //   }
    //   return value;
    // },
  },
];

```

### 🏞 期望结果
两种情况均正常识别

### 💻 复现代码
无需

### © 版本信息

- ProComponents 版本:   "@ant-design/pro-components": "^2.6.4",

### 🚑 其他信息
https://github.com/ant-design/pro-components/blob/master/packages/utils/src/transformKeySubmitValue/index.ts#L154

如果返回对象时逻辑在 148 行处理。后续 merge 之后正常。

但返回数据的时候 154 行直接忽略了所有 falsy 值。

是否需要修正为 undefined 判断？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据你提供的调试结果，可以看到问题可能出现在 `transformKeySubmitValue` 方法中。根据你的描述，该方法在返回空字符串时无法成功修改提交的表单值。你还建议在条件判断为假值时返回 `undefined` 以便修正这个问题。

根据你提供的代码截图，我注意到该问题可能是因为在 `transform` 函数中，当值为 `undefined` 时，直接返回了空字符串。根据你的期望结果，你希望能够正常识别这种情况。

我建议你尝试返回一个包含键值对的对象，而不是直接返回空字符串。你可以像你的注释中那样修改 `transform` 函数，使用 `{ [key]: "" }` 的形式来返回一个对象。

这样修改后的代码示例如下：

```js
const columes = [
  {
    valueType: 'select',
    transform: (value, key) => {
      if (value === undefined) {
        return { [key]: '' };
      }
      return value;
    },
  },
];
```

这样修改后，当值为 `undefined` 时，将返回一个包含键值对的对象 `{ [key]: '' }`，而不是直接返回空字符串。

关于这个问题的修复，你还可以提交一个 issue 到 `ant-design/pro-components` 项目中，提醒开发者注意到这个问题并进行修复。

此外，你还可以阅读 `ant-design/pro-components` 文档，了解更多关于如何使用和定制该组件库的信息。

希望这些信息能帮助到你解决问题！如果你还有其他问题，请随时提问。

**Comment by tommytroylin** [comment]
@chenshuai2144 看下是否需要 pr 修复和补充测试。我可以提供
如果是个 feature 的话 issue 我就关了🐶

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


@chenshuai2144 如果你认为这是一个 bug，并且你可以提供修复代码和相应的测试，那么你可以考虑提交一个 Pull Request 修复该问题。

你可以按照以下步骤进行操作：

1. 首先，Fork `ant-design/pro-components` 仓库到你自己的 GitHub 账号下。

2. 克隆你 Fork 的仓库到本地：

   ```
   git clone https://github.com/你的GitHub用户名/pro-components.git
   ```

3. 创建一个分支并切换到该分支：

   ```
   git checkout -b fix/transformKeySubmitValue-bug
   ```

4. 根据你的修复意见，修改 `transformKeySubmitValue` 方法中的代码，并确保它能解决问题。

5. 添加相应的测试用例，确保修复的问题可以被正确地覆盖。

6. 提交你的修改：

   ```
   git commit -m "Fix transformKeySubmitValue bug"
   ```

7. 将你的分支推送到你 Fork 的仓库：

   ```
   git push origin fix/transformKeySubmitValue-bug
   ```

8. 最后，通过 GitHub 创建一个 Pull Request，将你的修复代码提交到 `ant-design/pro-components` 仓库，说明清楚你的修改内容和解决的问题。

你可以在提PR之前先与 `ant-design/pro-components` 项目的维护者进行讨论，以确保你的解决方案符合他们的要求和期望。他们可能会提供一些指导和反馈。

希望这对你有帮助！如果你有其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
打算重写下 你可以先关掉
