### ISSUE TITLE
🐛[BUG] EditableTable 两个 column 的联动如何处理，使用setRowData修改，onValuesChange不能获取最新的值

### ISSUE THREAD

**Issue by America-first-melon** [ant-design/pro-components#7358]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

EditableTable 两个 column 的联动如何处理，使用setRowData修改，onValuesChange不能获取最新的值

### 📷 复现步骤

https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-n75jqs?file=/App.tsx:3148-3162

### 🏞 期望结果

column 联动，联动双方都可以被修改。

### 💻 复现代码

[[](https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-n75jqs?file=/App.tsx:3148-3162)](https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-n75jqs?file=/App.tsx:3148-3162)

### © 版本信息

- ProComponents 版本: 2.6.3
- umi 版本
- 浏览器环境
- 开发环境  chrome

### 🚑 其他信息

![image](https://github.com/ant-design/pro-components/assets/21686182/78c51995-231e-48c6-b3e7-5ff04aa18928)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！感谢提供详细的问题描述和复现步骤。

根据你的描述，你想要处理 EditableTable 中两个 column 的联动问题，使用 setRowData 修改数据后，在 onValuesChange 回调中无法获取到最新的值。

根据你提供的代码示例，我注意到 EditableTable 是基于 Ant Design ProComponents 的，所以下面我将提供一个解决方案，帮助你处理这个问题。

在 EditableTable 的 props 中，可以使用 onValuesChange 回调函数来监听每个 cell 的值变化。但是，在 onValuesChange 中调用 setRowData 修改数据时，onValuesChange 不会立即更新。这是因为 setRowData 是一个异步操作，React 的 state 更新也是异步的。

为了获取最新的值，你需要在 onValuesChange 中使用 setState 或者 useEffect 来监听数据变化。这样可以确保在数据更新完毕后获取到最新的值。

下面是一个可能的解决方案：

```jsx
import React, { useEffect, useState } from "react";
import { EditableProTable } from "@ant-design/pro-table";

const Example = () => {
  const [dataSource, setDataSource] = useState([]);

  const handleValuesChange = (key, values) => {
    // 更新 setState 或 useEffect
    setDataSource((prevDataSource) => {
      const newData = [...prevDataSource];
      const index = newData.findIndex((item) => item.key === key);
      if (index > -1) {
        newData[index] = { ...newData[index], ...values };
      }
      return newData;
    });
  };

  useEffect(() => {
    console.log("dataSource:", dataSource);
  }, [dataSource]);

  return (
    <EditableProTable
      value={dataSource}
      onChange={setDataSource}
      onValuesChange={handleValuesChange}
      columns={[
        {
          title: "Column 1",
          dataIndex: "column1",
          valueType: "text",
          editable: true
        },
        {
          title: "Column 2",
          dataIndex: "column2",
          valueType: "text",
          editable: true
        }
      ]}
    />
  );
};

export default Example;
```

在这个示例中，handleValuesChange 函数使用了 useState 和 setDataSource 更新数据的方法。在 useEffect 中，我使用了 dataSource 来打印最新的值。

希望这个解决方案能够帮助你解决问题！如果还有其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/blob/d8d1e6efea124241ac46b2381a339d84a6ba68cf/packages/table/src/components/EditableTable/demos/form-linkage.tsx#L109

看这个demo，可以用form reset，也可以直接操作 value
