### ISSUE TITLE
🐛[BUG] ProFormUploadButton多选设置multiple没用

### ISSUE THREAD

**Issue by shangchuan123** [ant-design/pro-components#7359]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
🐛[BUG] ProFormUploadButton多选设置multiple没用，
<ProFormUploadButton name="detailUrls" label="产品详情图" fileList={mainImgList} multiple={true}

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by shangchuan123** [comment]
<ProFormUploadButton
								name="upload"
								label="图片"
								fileList={imgList}
								multiple={true}
								max={10}
								fieldProps={{
									name: "file",
									listType: "picture-card",
									multiple:true
								}}
multiple放到fieldProps里就可以了

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您的反馈！通过将`multiple`属性放到`fieldProps`中，您可以实现`ProFormUploadButton`多选的需求。下面是修改后的代码示例:

```jsx
<ProFormUploadButton
	name="upload"
	label="图片"
	fileList={imgList}
	fieldProps={{
		name: "file",
		listType: "picture-card",
		multiple: true
	}}
/>
```

请注意，`multiple`属性仅适用于上传组件支持多选的情况。如果您使用的上传组件不支持多选，则无法实现多选功能。

另外，如果您还遇到其他问题，可以提供更多的相关信息，我们会尽力提供帮助。
