### ISSUE TITLE
🐛[BUG]ProTable中search.collapseRender配置仍不起作用

### ISSUE THREAD

**Issue by ziitar** [ant-design/pro-components#736]
### 🐛 bug 描述

将search.collapseRender设置为false仍然有展开收起按钮
### 📷 复现步骤

将search.collapseRender设置为false
### 🏞 期望结果

将search.collapseRender设置为false没有展开收起按钮
### 💻 复现代码

https://codesandbox.io/s/quizzical-river-dg695
### © 版本信息

- ProTable 版本: [2.9.3][2.5.15]等
- umi 版本 [2.9.0]
- 浏览器环境
- 开发环境 [window10]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/33385784/96111607-01451800-0f14-11eb-869e-0928fbe41ddc.png)

**Comment by chenshuai2144** [comment]
@ziitar 这个是不支持的，你可以自己 render 一下

**Comment by ziitar** [comment]
那这个属性设置为false代表的含义是？

**Comment by fleetscythe** [comment]
用这个吧  
```
 search={{
     collapseRender: () => false,
 }}
```
