### ISSUE TITLE
Customize ProFormList

### ISSUE THREAD

**Issue by merabtenei** [ant-design/pro-components#7360]
I need a ProFormList to display as a Table, so I created a copy of the ProFormList as below :

Here is the sandbox sample :
[https://codesandbox.io/s/proform-list-forked-qgwggs?file=/App.tsx](https://codesandbox.io/s/proform-list-forked-qgwggs?file=/App.tsx)

When I edit a single row in the CustomProFormList all other rows change at the same time.
What do we need to do to create a modified version of an existing Component.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


To create a modified version of an existing component, such as the ProFormList in this case, you can follow these steps:

Step 1: Create a new component
In your project, create a new component called CustomProFormList (or any desired name) with the necessary imports. You can start by copying the code from the ProFormList component.

```jsx
import React from 'react';
import ProForm, { ProFormList } from '@ant-design/pro-form';

const CustomProFormList = (props) => {
  const { dataSource, ...restProps } = props;
  
  // Custom logic or modifications can be added here
  
  return (
    <ProFormList
      {...restProps}
      initialValues={dataSource}
    >
      {(fields) =>
        fields.map((field, index) => (
          <ProForm.Group key={field.key}>
            {/* render your custom form fields for each row */}
          </ProForm.Group>
        ))
      }
    </ProFormList>
  );
};

export default CustomProFormList;
```

Step 2: Use the CustomProFormList component
You can now replace the ProFormList component in your App.tsx with the CustomProFormList component.

```jsx
import React from 'react';
import { ProForm, ProFormList } from '@ant-design/pro-form';
import CustomProFormList from './CustomProFormList';

const App = () => {
  return (
    <div>
      <h1>Custom ProFormList</h1>
      <ProForm
        name="basic"
        layout="horizontal"
        onFinish={(values) => {
          console.log(values);
        }}
      >
        <CustomProFormList
          name="list"
          label="List"
          rules={[
            { required: true, message: 'Please input list items!' },
          ]}
          dataSource={[
            { name: 'Item 1' },
            { name: 'Item 2' },
            { name: 'Item 3' },
          ]}
        />
        
        {/* render any other form fields */}
        
        <ProForm.Item>
          <button type="submit">Submit</button>
        </ProForm.Item>
      </ProFormField>
    </div>
  );
};

export default App;
```

Step 3: Customize the new component
Within the CustomProFormList component, you can add any desired modifications to meet your requirements. In your case, you mentioned that when editing a single row, all other rows change at the same time. To prevent this behavior, you can add a unique `key` prop to each row:

```jsx
<ProForm.Group key={field.key}>
  {/* render your custom form fields for each row */}
</ProForm.Group>
```

By providing a unique key to each row, React will be able to identify and track individual rows, allowing them to be edited independently.

Remember to adjust the code as needed for your specific requirements and styling. Also, make sure to import any necessary packages and dependencies.

For more information and customization options, you can refer to the ProFormList documentation:

[https://procomponents.ant.design/components/form-list](https://procomponents.ant.design/components/form-list)
