### ISSUE TITLE
🐛[BUG] 2.6.3 版本中对 Card 的 extra 属性的改动导致了 Checkbox 只有第一次生效

### ISSUE THREAD

**Issue by xliez** [ant-design/pro-components#7361]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

extra 内的 Checkbox 只有第一次点击会生效，之后无法点击

### 📷 复现步骤

复现 demo: https://codesandbox.io/s/ji-chu-qia-pian-forked-w9nyx5?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

查阅资料后发现原因：https://zhuanlan.zhihu.com/p/431268270

[fix(card): close onClick and onchange Propagation](https://github.com/ant-design/pro-components/commit/c86532f) 这个commit 中因为加了 preventDefault 导致触发了这个问题

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！

根据你提供的信息，问题是在 ProComponents 2.6.3 版本中，Card 组件的 extra 属性的改动导致 Checkbox 只有第一次点击生效。这个问题是由于一个 commit 中引入的 preventDefault 造成的。

为了解决这个问题，你可以尝试升级 ProComponents 到最新版本，这个问题应该在后续版本中得到修复。

另外，如果你无法立即升级 ProComponents，你可以手动修改代码来解决这个问题。在 Card 组件的 extra 属性中，添加一个 onClick 事件，并通过 event.stopPropagation() 来阻止事件冒泡。这样可以确保 Checkbox 的点击事件能够正常触发。以下是一个示例代码：

```jsx
import React from "react";
import { Card, Checkbox } from "antd";

const MyCard = () => {
  const handleCheckboxChange = (event) => {
    event.stopPropagation();
    // 处理 Checkbox 的逻辑
  };

  return (
    <Card
      title="Card title"
      extra={
        <Checkbox onChange={handleCheckboxChange}>
          Checkbox
        </Checkbox>
      }
    >
      <p>Card content</p>
    </Card>
  );
};

export default MyCard;
```

这个示例代码中，我们在 Checkbox 的 onChange 事件中调用了 event.stopPropagation() 来阻止事件冒泡，确保 Checkbox 的点击事件直接生效。

希望这个解决方案对你有帮助！如果还有其他问题，请随时提问。

**Comment by xliez** [comment]
感谢回复😄

已确认 master 代码中已在该 [commit](https://github.com/ant-design/pro-components/commit/5f4bb4849ffd70f3fd44d0a73183dc38df30c87a) 修复了问题，只是还未发版

目前先把版本降至了 2.6.2，等待您的发版
