### ISSUE TITLE
🐛[BUG] ProDescriptions 开启ellipsis后，文字重叠

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#7367]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

````
{
          title: '文本',
          key: 'text',
          dataIndex: 'id',
          ellipsis: true,
},
````
开启ellipsis后，文字重叠
![image](https://github.com/ant-design/pro-components/assets/3166799/8d5ecdb4-3164-4390-b733-e669bb9dc37d)

### 📷 复现步骤

https://codesandbox.io/s/columns-pei-zhi-forked-s22wfh

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您报告的问题！根据您的描述和提供的信息，您遇到了 ProDescriptions 在开启 ellipsis 后文字重叠的问题。

根据您提供的复现步骤和代码示例，可以尝试以下解决方案：

1. 确保您的代码中引入了正确的 ProDescriptions 组件以及相关的样式文件。

2. 首先，您可以尝试为 ProDescriptions.Item 设置一个固定的宽度，以确保文本能够正确显示，并避免文字重叠。例如：

```jsx
{
  title: '文本',
  key: 'text',
  dataIndex: 'id',
  ellipsis: true,
  render: (text) => (
    <ProDescriptions.Item span={2} style={{ width: '200px' }}>{text}</ProDescriptions.Item>
  ),
},
```

在上面的示例中，我将宽度设置为 `200px`，您可以根据实际需求进行调整。

3. 如果固定宽度的解决方案不适用于您的情况，您可以尝试使用 CSS 的 `text-overflow` 属性来控制文本的溢出。例如：

```jsx
{
  title: '文本',
  key: 'text',
  dataIndex: 'id',
  ellipsis: true,
  render: (text) => (
    <ProDescriptions.Item span={2} className="ellipsis-text">{text}</ProDescriptions.Item>
  ),
},
```

然后，在您的 CSS 文件中添加以下样式：

```css
.ellipsis-text {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  /* 可以根据需要设置容器的宽度 */
  max-width: 200px;
}
```

上述代码将使用 CSS 对文本进行截断并添加省略号。

这些解决方案可能可以帮助您解决文字重叠的问题。如果问题仍然存在，请确保您的 React 和 ProDescriptions 版本是最新的，并查看相关的官方文档和社区讨论，以获取更多帮助和支持。

希望以上信息对您有帮助！如有任何进一步的问题，请随时提问。

**Comment by chenshuai2144** [comment]
![image](https://github.com/ant-design/pro-components/assets/8186664/d7e0a426-18fe-4e00-bddb-501ae4f6d822)


官方的demo看起来没问题，提供一下重现吧

**Comment by destinytaoer** [comment]
我也遇到同样的问题，ProDescriptions 的样式不太合理，包括编辑态的表单。

按上面描述的解决方案，如果设置 ellipsis 之后还要通过设置宽度和溢出样式来解决，那这个属性有什么意义。

官方文档示例中，设置了样式，而且是独占一行的，没有什么参考价值。
contentStyle={{
    maxWidth: '80%',
}}

其实就是 flex 为 1 时，仍然会溢出的样式问题

**Comment by chenshuai2144** [comment]
先加个这个，估计要 antd 那边想想办法了，不太好搞
```
  contentStyle={{
            display: 'flex',
            maxWidth: 'calc(100% - 80px)',
          }}
```
