### ISSUE TITLE
浏览器返回弹窗或抽屉仍不关闭🧐[问题]

### ISSUE THREAD

**Issue by zhuiluo0987** [ant-design/pro-components#7370]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
在一个页面打开一个弹窗或抽屉。点击浏览器返回。弹窗或抽屉仍不关闭

### 💻 示例代码

<img width="952" alt="image" src="https://github.com/ant-design/pro-components/assets/20220029/41d25e0e-c2b6-4770-b1e9-115eddb5760c">

<img width="675" alt="image" src="https://github.com/ant-design/pro-components/assets/20220029/2d4c5e57-4fac-4ed2-bc58-1abb486f3a1a">

### 🚑 其他信息

"@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^2.3.16",
    "@ant-design/pro-layout": "^6.38.8",
    "@ddmc/auto-update": "^1.0.12",
    "@umijs/route-utils": "^2.0.0",
    "antd": "^4.24.12",
    "classnames": "^2.3.0",
    "jsbarcode": "^3.11.5",
    "lodash": "^4.17.0",
    "moment": "^2.29.0",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.1.0",
    "rc-util": "^5.16.0",
    "react": "^17.0.0",
    "react-activation": "^0.12.4",
    "react-dev-inspector": "^1.7.0",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.2.0",
    "react-resizable": "^3.0.4",
    "umi": "^3.5.0",
    
    node： 14.20.0

**Comment by zhuiluo0987** [comment]
![image](https://github.com/ant-design/pro-components/assets/20220029/7fe7e61f-5e39-4baa-ba9c-5cca1365ec40)

点击浏览器左上角返回按钮

![image](https://github.com/ant-design/pro-components/assets/20220029/806e418c-de67-4adf-815a-2b9c6fbcaa20)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您提供的信息。根据您的描述和提供的示例代码和截图，看起来您正在使用 `@ant-design/pro-components` 中的弹窗或抽屉组件，并且在点击浏览器返回按钮时，它们没有关闭。

这个问题可能是由于您没有正确处理浏览器的返回事件导致的。您可以尝试使用 React 的 `useEffect` 钩子函数来监听浏览器的返回事件，并在触发时关闭弹窗或抽屉。

以下是一个可能的解决方案：

```jsx
import React, { useEffect } from 'react';
import { Drawer, Modal } from 'antd';

const YourComponent = () => {
  // 设置弹窗或抽屉的可见状态
  const [visible, setVisible] = useState(false);

  // 监听浏览器的返回事件
  useEffect(() => {
    const handleBackButton = () => {
      // 关闭弹窗或抽屉
      setVisible(false);
    };

    // 添加事件监听
    window.addEventListener('popstate', handleBackButton);

    return () => {
      // 移除事件监听
      window.removeEventListener('popstate', handleBackButton);
    };
  }, []);

  const showDrawer = () => {
    setVisible(true);
  };

  const closeDrawer = () => {
    setVisible(false);
  };

  return (
    <>
      <button onClick={showDrawer}>打开弹窗或抽屉</button>
      <Drawer visible={visible} onClose={closeDrawer}>
        {/* 弹窗或抽屉的内容 */}
        Your content here...
      </Drawer>
    </>
  );
};

export default YourComponent;
```

在上面的示例代码中，我们使用 `useEffect` 钩子函数来监听浏览器的返回事件 (`popstate`)。当返回事件触发时，我们关闭弹窗或抽屉，即将 `visible` 设置为 `false`。

此外，还要确保您的 React 版本与 `@ant-design/pro-components` 中使用的版本兼容。您提供的信息中显示您正在使用 React `17.0.0`，这应该是兼容的。

您还可以参考 Ant Design 官方文档中有关弹窗和抽屉组件的使用方式，以获取更多信息和示例代码：[Ant Design Modal](https://ant.design/components/modal-cn/) 和 [Ant Design Drawer](https://ant.design/components/drawer-cn/)。

希望这些信息和示例代码对您有所帮助！如果您有任何进一步的问题，请随时提问。祝您编程顺利！

**Comment by chenshuai2144** [comment]
要你自己处理的，现在浏览器的返回都不是刷新页面，而是堆栈。状态会被保持的。
如果你需要关闭，需要自己处理一下url改成时的状态
