### ISSUE TITLE
🐛[BUG] ProComponents打包后的antd样式，覆盖了自定义的主题

### ISSUE THREAD

**Issue by vscing** [ant-design/pro-components#7376]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProComponents打包后的antd样式，覆盖了自定义的主题

### 📷 复现步骤

引入ProComponents依赖包，项目使用了antd，并配置了antd主题色。打包后，未用ProComponents组件的页面颜色正常，使用了的颜色被还原。

### 🏞 期望结果

使用ProComponents组件的页面颜色正常

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个我做不到，推荐你升级antd@5 ，或者自己改webpack

**Comment by vscing** [comment]
> 这个我做不到，推荐你升级antd@5 ，或者自己改webpack

webpack修改有相关例子吗?

**Comment by zifeiyu666** [comment]
我也遇到这样的问题了，antd 组件都正常，但是 procompoent 组件都是默认样式
![image](https://github.com/ant-design/pro-components/assets/23133123/900ec600-c760-42fa-9208-991903a70f12)
加的前缀都只在 antd 组件生效

**Comment by linvic** [comment]
请问怎么解决的
