### ISSUE TITLE
👑 [需求]ProTable 怎么解决最后一页最后一行数据删除不会返回前一页

### ISSUE THREAD

**Issue by pingguoping** [ant-design/pro-components#7377]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，我只能处理关于 React 的前端问题。您的问题涉及到 ProTable 组件，这是一个后端的库，所以我不能给出相应的解决方案。如果您有其他关于 React 的前端问题，我将很乐意为您提供帮助。

**Comment by chenshuai2144** [comment]
最简单的办法删除之后回到第一页。剩下就要自己控制的 pageInfo了

**Comment by jintao-lai** [comment]
您好，这个问题解决了吗？我也遇到了相同的问题@pingguoping

**Comment by cdx111** [comment]
我也遇到这个问题

**Comment by cdx111** [comment]
> 您好，这个问题解决了吗？我也遇到了相同的问题@pingguoping

export function calcPagination(pageInfo: PageInfo) {
  const { pageSize, total, current } = pageInfo;
  const tp = total % pageSize === 0 ? total / pageSize : Math.floor(total / pageSize) + 1;
  return current > tp ? tp : current;
}
然后直接actionRef.setPageInfo，然后actionRef.reload

**Comment by pingguoping** [comment]
> 最简单的办法删除之后回到第一页。剩下就要自己控制的 pageInfo了
> 
> 要实现从当前页返回到第一页，可以通过antd的`Pagination`组件的`current`属性来控制当前页的值。当需要返回第一页时，将`current`属性设置为1即可。
> 
> 以下是一个示例代码片段，展示如何使用antd的`Pagination`组件并控制当前页：
> 
> ```js
> import React, { useState } from 'react';
> import { Pagination } from 'antd';
> 
> function MyComponent() {
>   const [currentPage, setCurrentPage] = useState(1);
> 
>   const handlePageChange = (page) => {
>     setCurrentPage(page);
>     // 执行其他操作...
>   };
> 
>   const handleGoToFirstPage = () => {
>     setCurrentPage(1);
>     // 执行其他操作...
>   };
> 
>   return (
>     <>
>       <Pagination
>         current={currentPage}
>         onChange={handlePageChange}
>         // 其他Pagination组件的配置项...
>       />
>       <button onClick={handleGoToFirstPage}>返回第一页</button>
>       {/* 其他组件内容... */}
>     </>
>   );
> }
> 
> export default MyComponent;
> ```
> 
> 在上述代码中，我们使用了`useState`钩子来创建`currentPage`状态，用于存储当前页的值。`handlePageChange`函数用于处理页码改变的事件，其中我们更新了`currentPage`状态，并可以执行其他与分页相关的操作。`handleGoToFirstPage`函数用于处理返回第一页的按钮点击事件，它将`currentPage`状态设置为1，从而返回到第一页。
> 
> 请根据实际需求和组件结构对示例代码进行调整，以便与您的项目适配。

请问下

> > 您好，这个问题解决了吗？我也遇到了相同的问题@pingguoping
> 
> export function calcPagination(pageInfo: PageInfo) { const { pageSize, total, current } = pageInfo; const tp = total % pageSize === 0 ? total / pageSize : Math.floor(total / pageSize) + 1; return current > tp ? tp : current; } 然后直接actionRef.setPageInfo，然后actionRef.reload



> 最简单的办法删除之后回到第一页。剩下就要自己控制的 pageInfo了
> 
> 要实现从当前页返回到第一页，可以通过antd的`Pagination`组件的`current`属性来控制当前页的值。当需要返回第一页时，将`current`属性设置为1即可。
> 
> 以下是一个示例代码片段，展示如何使用antd的`Pagination`组件并控制当前页：
> 
> ```js
> import React, { useState } from 'react';
> import { Pagination } from 'antd';
> 
> function MyComponent() {
>   const [currentPage, setCurrentPage] = useState(1);
> 
>   const handlePageChange = (page) => {
>     setCurrentPage(page);
>     // 执行其他操作...
>   };
> 
>   const handleGoToFirstPage = () => {
>     setCurrentPage(1);
>     // 执行其他操作...
>   };
> 
>   return (
>     <>
>       <Pagination
>         current={currentPage}
>         onChange={handlePageChange}
>         // 其他Pagination组件的配置项...
>       />
>       <button onClick={handleGoToFirstPage}>返回第一页</button>
>       {/* 其他组件内容... */}
>     </>
>   );
> }
> 
> export default MyComponent;
> ```
> 
> 在上述代码中，我们使用了`useState`钩子来创建`currentPage`状态，用于存储当前页的值。`handlePageChange`函数用于处理页码改变的事件，其中我们更新了`currentPage`状态，并可以执行其他与分页相关的操作。`handleGoToFirstPage`函数用于处理返回第一页的按钮点击事件，它将`currentPage`状态设置为1，从而返回到第一页。
> 
> 请根据实际需求和组件结构对示例代码进行调整，以便与您的项目适配。

Protable 请问源码在哪部分进行修改  总不能每个Protable组件都要区调用这个方法吧?

**Comment by pingguoping** [comment]
> 最简单的办法删除之后回到第一页。剩下就要自己控制的 pageInfo了
> 
> 要实现从当前页返回到第一页，可以通过antd的`Pagination`组件的`current`属性来控制当前页的值。当需要返回第一页时，将`current`属性设置为1即可。
> 
> 以下是一个示例代码片段，展示如何使用antd的`Pagination`组件并控制当前页：
> 
> ```js
> import React, { useState } from 'react';
> import { Pagination } from 'antd';
> 
> function MyComponent() {
>   const [currentPage, setCurrentPage] = useState(1);
> 
>   const handlePageChange = (page) => {
>     setCurrentPage(page);
>     // 执行其他操作...
>   };
> 
>   const handleGoToFirstPage = () => {
>     setCurrentPage(1);
>     // 执行其他操作...
>   };
> 
>   return (
>     <>
>       <Pagination
>         current={currentPage}
>         onChange={handlePageChange}
>         // 其他Pagination组件的配置项...
>       />
>       <button onClick={handleGoToFirstPage}>返回第一页</button>
>       {/* 其他组件内容... */}
>     </>
>   );
> }
> 
> export default MyComponent;
> ```
> 
> 在上述代码中，我们使用了`useState`钩子来创建`currentPage`状态，用于存储当前页的值。`handlePageChange`函数用于处理页码改变的事件，其中我们更新了`currentPage`状态，并可以执行其他与分页相关的操作。`handleGoToFirstPage`函数用于处理返回第一页的按钮点击事件，它将`currentPage`状态设置为1，从而返回到第一页。
> 
> 请根据实际需求和组件结构对示例代码进行调整，以便与您的项目适配。

请问ProTable在哪部分源码可以修改,总不能每个ProTable进行过滤操作都要执行这个方法吧?

**Comment by kikcmime** [comment]
这个问题他会把page分页自动跳回前一页，哪怕不跳是好的，假设第三页只有一条，删除了，然后这个时候给后端的页码是3，查回来肯定是没数据的，但是页面的页码显示成了2，第二页其实是有数据的，哪怕展示成3也好呀
