### ISSUE TITLE
MenuItem custom style，classname 

### ISSUE THREAD

**Issue by wulucxy** [ant-design/pro-components#7378]
### 🔩 所属模块或组件

ProLayout

### 🥰 需求描述

希望 MenuItem 能够提供自定义修改 样式 or className 的能力

### ⛰ 功能需求适用场景

有些场景需要自定义 MenuItem 的样式，比如高度，类似于以下场景：

<img width="225" alt="image" src="https://github.com/ant-design/pro-components/assets/5326403/158a4a3e-3fad-4bae-ab4a-afa7acbd320b">

### 🧐 解决方案

期望给 MenuItem 属性支持 style 和 className

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


在 ProLayout 的 MenuItem 中添加自定义样式和 className 的功能可以通过以下步骤实现：

#### 步骤 1:
在你的组件文件中，引入 MenuItem 组件，并为其添加一个 `style` 和 `className` 的属性。

```jsx
import { Menu } from 'antd';
const { Item } = Menu;

function CustomMenuItem() {
  return (
    <Menu>
      <Item style={{ height: '50px' }} className="custom-menu-item">
        Custom MenuItem
      </Item>
    </Menu>
  );
}

export default CustomMenuItem;
```

#### 步骤 2：
在你的 CSS 文件或样式模块中，添加 `custom-menu-item` 的样式规则，来自定义 MenuItem 的样式。

```css
.custom-menu-item {
  /* 添加你想要的自定义样式 */
  /* 比如修改背景颜色和字体颜色 */
  background-color: #f5f5f5;
  color: #333;
  /* 修改高度 */
  height: 50px;
}
```

#### 步骤 3：
确保你已经在你的项目中引入了相关的样式表，比如 antd 的样式。

```jsx
import 'antd/dist/antd.css';
```

### 📚 参考文档

- [Ant Design Menu](https://ant.design/components/menu-cn/)：了解 MenuItem 的更多属性和用法。
- [Ant Design Customization](https://ant.design/docs/react/customize-theme-cn)：自定义 Ant Design 样式的方法。
- [CSS Modules](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet)：如果你正在使用 CSS Modules 来管理样式，这里有关于如何使用 CSS Modules 的文档。
- [React CSS Modules](https://github.com/gajus/react-css-modules)：如果你正在使用 React CSS Modules 来管理样式，这里有它的 GitHub 页面。

**Comment by chenshuai2144** [comment]
menuItemRender 自己处理一下吧，不少同学玩的很花

**Comment by 349989153** [comment]
> menuItemRender 自己处理一下吧，不少同学玩的很花

menuItemRender 已经包在你们内置的Menu.Item里面了，现在想改你们内置的Menu.Item的样式，比如height，要怎么玩得花？

**Comment by 349989153** [comment]
> 其

这个又有什么用呢？我创建这个自定义组件，然后通过那个props给ProLayout用？
