### ISSUE TITLE
🧐[问题]请问下 ProTable 在哪个部分统一处理最后一页删除最后一天数据且返回当前页的前一页

### ISSUE THREAD

**Issue by pingguoping** [ant-design/pro-components#7379]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
再删除前判断呗，用ref 存一下当前数据的，然后删除之前先翻页
