### ISSUE TITLE
🐛[BUG] 布局top模式，下拉菜单透明

### ISSUE THREAD

**Issue by yuandalu** [ant-design/pro-components#7381]
### 🐛 bug 描述

布局top模式，下拉菜单透明

### 📷 复现步骤

布局设置为top，背景透明

### 🏞 期望结果

不应该透明，混合在一起很难辨认

### 💻 复现代码

基础项目拉一下，菜单设置多点，直接重现

### © 版本信息

- ProComponents 版本: [e.g. 2.6.5]
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![iwEcAqNwbmcDAQTRAcYF0QLYBrB24k_joC2TawSqHOs7QAYAB9IAeWHhCAAJomltCgAL0gABG4U png_720x720q90](https://github.com/ant-design/pro-components/assets/3860040/e4c1c2f7-4ab3-42fe-80ee-ea1cea2a78cd)

**Comment by chenshuai2144** [comment]
![image](https://github.com/ant-design/pro-components/assets/8186664/7b62fb01-b2f1-4308-a707-db96dbd1f288)


提供下 antd 和  procomponents 的版本。

**Comment by Lukiya** [comment]
Same here.

    "@ant-design/icons": "^5.1.4",
    "@ant-design/pro-components": "^2.6.7",
    "@umijs/max": "^4.0.72",
    "antd": "^5.7.1",

**Comment by chenshuai2144** [comment]
给个在线的重现

**Comment by yuandalu** [comment]
> 给个在线的重现

https://nxslvk-8000.csb.app/welcome

**Comment by chenshuai2144** [comment]
好像是故意搞的半透明。

**Comment by yuandalu** [comment]
> 好像是故意搞的半透明。

实际使用中挺影响业务的，用户觉得体验很不好

**Comment by Lukiya** [comment]
体验很不好，看不清楚

**Comment by JackyLeeCS** [comment]
好像并没有解决，最新的2.6.10版本还是半透明的

**Comment by MorriosL** [comment]
@chenshuai2144  ProLayout文档里的demo是可以复现的，如图
<img width="1874" alt="image" src="https://github.com/ant-design/pro-components/assets/25663540/0d2eb6aa-a648-4c5a-9c49-a936ab46c2df">

只是demo里背景是白色的不明显，加了一堆文字之后就明显了

**Comment by chenshuai2144** [comment]
![image](https://github.com/ant-design/pro-components/assets/8186664/595a3263-d7e8-4d9d-b3bd-b2d7c7c1a1fa)


并不会，是不是什么兼容性问题

**Comment by MorriosL** [comment]
<img width="2560" alt="image" src="https://github.com/ant-design/pro-components/assets/25663540/a4475c55-176d-4413-8c7c-d53c17d3b7cd">
可以在这里复现

**Comment by yuandalu** [comment]
暂时我在global.css中自己强制覆盖了样式，结合实际业务和用户反馈，真的是影响体验，真的

**Comment by yuandalu** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/258321602-595a3263-d7e8-4d9d-b3bd-b2d7c7c1a1fa.png)
> 
> 并不会，是不是什么兼容性问题

pro create创建一个就能重现

**Comment by Lukiya** [comment]
我也是，没办法，在global.css覆盖掉了。
`:where(.css-dev-only-do-not-override-1qy0mnp).ant-menu-light.ant-menu-submenu>.ant-menu {
    background-color: rgba(255, 255, 255, 1);   /* 修复横向Menu下拉透明 */
}`

**Comment by liangry** [comment]
2024年了，还是这个问题
