### ISSUE TITLE
🐛[BUG]混合布局模式下，header设置固定 Header，仍然固定，且固定模式下，table的sticky浮动头部会被覆盖

### ISSUE THREAD

**Issue by yuandalu** [ant-design/pro-components#7382]
### 🐛 bug 描述

混合布局模式下，header设置固定 Header，仍然固定，且固定模式下，table的sticky浮动头部会被覆盖

### 📷 复现步骤

创建项目，通过配置主题工具配置混合布局，header不固定，结果仍然固定
设置table的sticky属性为true实现表格表头的浮动，浮动生效，但是会被固定的header盖住，看代码是top值没有根据浮动头部更新

### 🏞 期望结果

header设置固定和不固定正常
table的浮动头部不被覆盖

### 💻 复现代码

```javascript
rowSelection={{
          onChange: (_, selectedRows) => {
            setSelectedRows(selectedRows);
          },
        }}
        sticky={true}
```

### © 版本信息

- ProComponents 版本: [e.g. 2.6.5]
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="383" alt="lQLPJxFHoUVHHcLNBDjNAv6wwaYHYXkDxs8EqiTpjEAQAA_766_1080" src="https://github.com/ant-design/pro-components/assets/3860040/aa074e6c-ee5b-4233-91c2-a836025575d2">

<img width="508" alt="image" src="https://github.com/ant-design/pro-components/assets/3860040/ed76ff23-e114-408c-9a5b-4d7d34794d61">

<img width="331" alt="image" src="https://github.com/ant-design/pro-components/assets/3860040/bdb1c483-a980-48aa-82db-67653389fbd0">

正确：
<img width="309" alt="image" src="https://github.com/ant-design/pro-components/assets/3860040/1b0eeb78-c1f4-4058-b8ae-552502cb5ae7">

**Comment by chenshuai2144** [comment]
看了下，没办法计算，是两个组件。可能要你自己处理了

**Comment by yuandalu** [comment]
> 看了下，没办法计算，是两个组件。可能要你自己处理了

![image](https://github.com/ant-design/pro-components/assets/3860040/8d7cd944-657e-4c90-8187-03c6802cce7e)
内联都写死了，我自己不好处理，

**Comment by chenshuai2144** [comment]
css 硬写

**Comment by yuandalu** [comment]
![image](https://github.com/ant-design/pro-components/assets/3860040/625ea577-eeeb-430f-be53-3b59b7739252)


已找到官方解决方案，可以设置更多的参数解决问题
