### ISSUE TITLE
🐛[BUG] Warning: `children` will be removed in next major version. Please use `items` instead. 

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#7383]
<img width="599" alt="image" src="https://github.com/ant-design/pro-components/assets/30397655/7d6a2bf6-c005-433f-9c99-c8ad3eaaade2">

**Comment by chenshuai2144** [comment]
写的清楚一些是哪个组件？

**Comment by leshalv** [comment]
看起来就是 ProForm
