### ISSUE TITLE
🐛[BUG]使用manualRequest阻止首次请求失败

### ISSUE THREAD

**Issue by cxbf** [ant-design/pro-components#7384]
#7363 详细内容见7363
在使用了贵方提出的方法给table添加不同的key值并不能解决此问题，望请贵方提出有效的解决方案
感觉像是在请求的时候更换页面导致请求串线了

**Comment by cxbf** [comment]
在数据量大时会很明显，本地触发一般需要多点几次，但是上线之后快速切换页面就很容易触发了

**Comment by chenshuai2144** [comment]
不要重复提同样的
