### ISSUE TITLE
🧐[问题]ProTable是否有获取当前展示列的方法？

### ISSUE THREAD

**Issue by Wei0809** [ant-design/pro-components#7386]
### 🧐 问题描述
我发现columnsState里面的onChange方法只有在操作勾选列展示时会出发onChange，如果我手动修改了表格的columns，那么onChange是不会触发的，重新请求数据也不会触发；请问目前有提供获取当前列状态的方法吗？或者以后可以提供一个？

![image](https://github.com/ant-design/pro-components/assets/43309547/d8f4f7fd-64c8-4a91-bc97-b3544f2d5a4e)

**Comment by chenshuai2144** [comment]
受控就好了吧，或者你封装一个事件出来。 不是很理解为啥你能手动改列，是修改代码热更新吗?

**Comment by Wei0809** [comment]
> 受控就好了吧，或者你封装一个事件出来。 不是很理解为啥你能手动改列，是修改代码热更新吗?

有需求需要通过state修改columns的值然后重新请求，但是在这种情况下受控的columnsState 的onChange事件不会触发

**Comment by Wei0809** [comment]
> 受控就好了吧，或者你封装一个事件出来。 不是很理解为啥你能手动改列，是修改代码热更新吗?

@chenshuai2144 有需求colums的值是动态的，改变之后会重新请求数据。受控的columnsState在这种情况下不会触发onChange时间，并且也拿不到初始值

**Comment by chenshuai2144** [comment]
动态的初始值你设置的吧，搞个  state  存起来呗

**Comment by chenshuai2144** [comment]
> 修改 columns之后onChange事件不会触发

修改 columns 是个什么概念？不是用这个修改吗？

| columnsState | 受控的列状态，可以操作显示隐藏 | `ColumnStateType` | - |

**Comment by Wei0809** [comment]
> 修改 columns 是个什么概念？不是用这个修改吗？
> 
> | columnsState | 受控的列状态，可以操作显示隐藏 | `ColumnStateType` | - |

@chenshuai2144 可以理解为根据请求参数的不同后端会返回不同的dataSource的结构，例如
```
  const c1 = [
    {
      dataIndex: 'a',
      title: 'a',
    },
    {
      dataIndex: 'b',
      title: 'b',
    },
  ];

  const c2 = [
    {
      dataIndex: 'c',
      title: 'c',
    },
    {
      dataIndex: 'd',
      title: 'd',
    },
  ];

  const c3 = [
    {
      dataIndex: 'e',
      title: 'e',
    },
    {
      dataIndex: 'f',
      title: 'f',
    },
  ];
```
最终的columns会根据条件取`[...c1,...c3]`或者说`[...c2,...c3]`，如果用户修改了columnsState中列的展示，又改了查询条件导致columns改变了，就造成我获取当前展示的列 有点麻烦（主要用在导出表格时保障导出内容和当前表格显示的一致）；我可以通过columns和columnsState来获取，但是会增加非常多的逻辑；

**Comment by chenshuai2144** [comment]
这个没办法的，这就是动态的代价，你必须要存起来才能受控
