### ISSUE TITLE
🧐[问题]ProFormUploadButton能获取当前ProForm的mode模式

### ISSUE THREAD

**Issue by lovewinders** [ant-design/pro-components#7390]
### 🧐 问题描述
在ProForm表单中，自定义嵌套多层子组件，末端子组件使用ProFormUploadButton必须通过props 层层传递readonly属性才能动态控制上传组件 只读模式 不显示 删除图标按钮，实属不雅；

ProFormUploadButton能获取当前ProForm的mode或readonly的值？
方案一：例如获取mode的值为 edit / read，这样可以方便设置ProFormUploadButton -> fieldProps -> showUploadList: mode === 'edit' ；
方案二：例如获取readonly的值boolean也行

### 💻 示例代码
之前我使用方案：
import { EditOrReadOnlyContext } from '@ant-design/pro-form/es/BaseForm/EditOrReadOnlyContext';

const modeContext = useContext(EditOrReadOnlyContext);
// 当前表单处于编辑还是只读
const mode = modeContext.mode === 'edit'

因为现在推荐import { *** } from '@ant-design/pro-components'
所以能否把EditOrReadOnlyContext 暴漏到 @ant-design/pro-components？

**Comment by chenshuai2144** [comment]
export  的， 你直接从文件里面拿吧。

fileList 的  readony 不是很好做。

**Comment by lovewinders** [comment]
> export 的， 你直接从文件里面拿吧。
> 
> fileList 的 readony 不是很好做，我们暂时不会做

@ant-design/pro-components上没有导入的EditOrReadOnlyContext，所以取不到啊

**Comment by chenshuai2144** [comment]
pro form  里面有，用文件拿一下

**Comment by lovewinders** [comment]
> pro form 里面有，用文件拿一下

pnpm是无法获取到文件的：Cannot find module '@ant-design/pro-form' or its corresponding type declarations.

**Comment by chenshuai2144** [comment]
你再安装一下呢？

**Comment by lovewinders** [comment]
> 你再安装一下呢？

@chenshuai2144 刚看了pro-components@2.6.7版本改动地方确实可以，但不是最佳方案。如后续图文属于个人建议改进方案
![image](https://github.com/ant-design/pro-components/assets/22837419/9f117d9e-e19b-42ad-ad85-ac97396eee72)

## 个人推荐 export { EditOrReadOnlyContext } 源码放到packages/form/src/index.tsx内位置更佳：

### 推荐原因：
> 1.EditOrReadOnlyContext属于BaseForm的，例如ProForm、ModalForm、StepForm都可以用到，如果仅挂到ProForm上是不是有点范围过窄？

> 2.packages/form/src/index.tsx本身已经export 出ProFormContext、FormListContext、FieldContext，这个地方再加EditOrReadOnlyContext内聚更佳

![image](https://github.com/ant-design/pro-components/assets/22837419/e6c3f367-871a-4267-9674-75c8df8b7c00)

**Comment by chenshuai2144** [comment]
全部走 proform 用就好了 只是提供一个导出的地方 这个内部 api 本来就不推荐用 就是给你个后门而已

**Comment by lovewinders** [comment]
> 全部走 proform 用就好了 只是提供一个导出的地方 这个内部 api 本来就不推荐用 就是给你个后门而已

好的

**Comment by taoliujun** [comment]
@lovewinders  我这获取的EditOrReadOnlyContext的值，始终是`edit`。
