### ISSUE TITLE
🐛[BUG]无法自定义ProList的Metas.title宽度

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#7392]
![image](https://github.com/ant-design/pro-components/assets/12421552/87c1140e-4d9a-44ba-acb2-c435aea3b773)

![image](https://github.com/ant-design/pro-components/assets/12421552/364d7626-0dbe-4306-92bd-84b29d9fc415)

设置了 style为500，但是有个width: max-content; 给拦截了

**Comment by chenshuai2144** [comment]
给  fieldProps  设置
