### ISSUE TITLE
🐛[BUG]在官方文档下，当前黑色主题proTable options除了setting，剩下没做适配

### ISSUE THREAD

**Issue by limuen** [ant-design/pro-components#7394]
🐛 bug 描述
https://procomponents.ant.design/components/table?tab=api&current=1&pageSize=5#packages-table-src-components-table-tab-api-demo-theme
在官方文档下，当前黑色主题proTable options除了setting，剩下没做适配

🏞 期望结果
期望修复暗黑主题下那些字体的color

💻 复现代码
https://procomponents.ant.design/components/table?tab=api&current=1&pageSize=5#packages-table-src-components-table-tab-api-demo-theme

**Comment by limuen** [comment]
search也是

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/blob/226fbac4e214a912a84973f69ccdd1183ffd34f0/packages/table/src/demos/theme.tsx#L145

把这个测试代码删掉就可以了
