### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by killer-wu** [ant-design/pro-components#7397]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

antd 引入了dayjs1.11.7的版本，pro-component引入了dayjs1.11.9的版本
这样导致在使用日期选择器的时候会出现版本不兼容的问题

再次点击日期选择器的时候会报错

### 💻 示例代码

{
            title: '订单生成时间',
            dataIndex: 'create_time',
            align: 'center',
            valueType: 'dateTimeRange',
            fieldProps: {
              locale: 'zh-en'
            },
            search: {
                transform: (value) => {
                    const [start, end] = value
                    
                    // 临时解决
                    return {
                        create_time_start: moment(start.$d).unix(),
                        create_time_end: moment(end.$d).unix()
                    }
                }
            },
            render: (_, record) => {
                return record?.create_time ? moment.unix(record.create_time).format('YYYY-MM-DD HH:mm:ss') : '-'
            }
        },

### 🚑 其他信息

"antd": "^5.7.1",
"@ant-design/pro-components": "^2.6.6",

![image](https://github.com/ant-design/pro-components/assets/61451803/ea3f05e5-0ee3-4109-a9c7-9dbf3cf6b289)

**Comment by lovewinders** [comment]
我当初也碰到这个问题，pnpm管理本地项目dayjs版本和pro-components中依赖版本不一致，导致线上2套dayjs实例问题引起的，后来我把本地dayjs修改为同pro-components一致的就可以了

**Comment by killer-wu** [comment]
> 我当初也碰到这个问题，pnpm管理本地项目dayjs版本和pro-components中依赖版本不一致，导致线上2套dayjs实例问题引起的，后来我把本地dayjs修改为同pro-components一致的就可以了

是的这样确实能解决兼容问题，就是汉化有问题了

**Comment by WuJiY** [comment]
+1
