### ISSUE TITLE
🐛[BUG] 2.6.6 菜单收缩后显示异常

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#7398]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

![image](https://github.com/ant-design/pro-components/assets/3166799/acd08bc3-edbd-4ca3-84bf-394a05ceb853)

**Comment by chenshuai2144** [comment]
什么异常？

**Comment by hihuangwei** [comment]
> 什么异常？

收缩后 子菜单无法展开了
