### ISSUE TITLE
🐛[BUG]ProTable无法设置规则，fieldProps的onChange无效果

### ISSUE THREAD

**Issue by kiana-god** [ant-design/pro-components#740]
### 🐛 bug 描述

ProTable无法设置规则，fieldProps的onChange无效果
### 📷 复现步骤
ProTable  文档没有说明，我试了很多，都没成功。
rules用fieldProps和formItemProps都无法添加规则，fieldProps里面onChange也没有效果
  {
    title: '出发城市',
    dataIndex: 'beginCity',
    key: 'beginCity',
    valueType: 'select',
    fieldProps: {
      placeholder: '请不要输入',
      onChange: () => {
        console.log(333);
      },
      onBlur: () => {
        console.log(33);
      },
      onSelect: () => {
        console.log(6786786);
      },
      showSearch: true,
    },
    valueEnum: {
      arrivalCity1: '到达城市1',
      arrivalCity2: '到达城市2',
    },
    formItemProps: {
      rules: [{ required: true }],
    },
  }
这种组件就可以使用rules进行规则限制
          <ProFormDatePicker
            name="tripDate"
            label="班次日期"
            tooltip="必填"
            initialValue={moment()}
            rules={[
              {
                required: true,
                message: '请选择班次日期',
              },
            ]}
          />

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kiana-god** [comment]
> 怎么说呢，这是个 featrue

= = 意思就是没，暂不支持咯

**Comment by chenshuai2144** [comment]
就是不希望你这么用， 用 `onValueChange` 处理吧

**Comment by America-first-melon** [comment]
> 就是不希望你这么用， 用 `onValueChange` 处理吧

之前可以用个哎， 升了个版本就不管用了。
