### ISSUE TITLE
🧐[问题]请问如何触发某一个ProFormList下的所有子项的表单验证呢

### ISSUE THREAD

**Issue by HaiYangHuX** [ant-design/pro-components#7402]
目前发现只能一个一个输入框的触发validateFieldsReturnFormatValue，但是嵌套比较深，字段也多，有没有一个方法可以直接触发ProFormList下的所有子项

**Comment by csic21** [comment]
应该是能直接使用antd表单的validateFields的

**Comment by chenshuai2144** [comment]
`validateFields(namePath)`
