### ISSUE TITLE
🧐[问题]ProTable列表工具栏工具栏的设置，如何更改列设置项hover显示的内容

### ISSUE THREAD

**Issue by Chensonglin08** [ant-design/pro-components#7408]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

ProTable列表工具栏工具栏的设置，如何更改列设置项hover显示的内容
将 ‘列设置’ 改为我想要的内容
![image](https://github.com/ant-design/pro-components/assets/83406261/51701573-184d-4917-a01f-75b896fbe454)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/blob/5421e41671afc084d6ba6cdb992e5320e72c2f8d/packages/table/src/components/ColumnSetting/index.tsx#L496
看这里的国际化文案，你改下国际化文案就能修改了
