### ISSUE TITLE
🐛edittable 样式问题

### ISSUE THREAD

**Issue by zyc329** [ant-design/pro-components#7409]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

<img width="1449" alt="image" src="https://github.com/ant-design/pro-components/assets/51154195/478e4aec-95d7-48c5-a915-2dd9ffa52afb">
pro-componet 2.6.5 后可编辑表格内的表单内容不能占据一行

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi4
- edge
- 开发环境 [e.g. mac OS]

**Comment by zyc329** [comment]
![image](https://github.com/ant-design/pro-components/assets/51154195/a00a0571-976b-4913-abac-d71bdccecc51)
请问如何添加版本

**Comment by chenshuai2144** [comment]
2.4.4 就是最新的了
