### ISSUE TITLE
🧐[问题]ProFormSelect组件如何动态更改所选中的值？

### ISSUE THREAD

**Issue by kiana-god** [ant-design/pro-components#741]
### 🧐 问题描述
下拉组件的联动使用，当第一位下拉选中后，第二位之前的数据清空
### 💻 示例代码

使用          <ProFormSelect
            name="beginCityId"
            label="出发城市"
            tooltip="必填"
            showSearch
            placeholder="请输入出发城市"
            fieldProps={{
              onSelect: queryAreaList,
            }}
          <ProFormSelect
            name="beginAreaId"
            label="出发区域"
            showSearch
            initialValue={aa}
            fieldProps={{
              onSelect: querySiteList,
              options: areaList,
            }}
            placeholder="请输入出发区域"
          />

这两个进行联动，当选中出发城市的下拉项，出发区域的内容自动清空

### 🚑 其他信息
求解惑

![image](https://user-images.githubusercontent.com/65165232/96139639-a02c3d00-0f31-11eb-916c-6b1614329e7f.png)

**Comment by chenshuai2144** [comment]
`onValueChange`  和  `setFieldsValue `  配合使用，尽量使用中心化的方式

**Comment by kiana-god** [comment]
请问有使用文档或者事例吗？没有使用过，谢谢大佬(✪▽✪)------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;陈帅&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月15日(星期四) 晚上10:57
收件人:&nbsp;&quot;ant-design/pro-components&quot;<pro-components@noreply.github.com&gt;;
抄送:&nbsp;&quot;kiana-god&quot;<1364748494@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 🧐[问题]ProFormSelect组件如何动态更改所选中的值？ (#741)

**Comment by yufengstudy** [comment]
> setFieldsValue

大佬，为什么使用setFieldsValue  无法修改下拉框的候选内容，只能修改下拉框显示的内容

**Comment by yufengstudy** [comment]
> `onValueChange` 和 `setFieldsValue ` 配合使用，尽量使用中心化的方式

大佬，为什么使用setFieldsValue 无法修改下拉框的候选内容，只能修改下拉框显示的内容
