### ISSUE TITLE
🧐[问题] 如何让LoginForm在不嵌入ProLayout的情况下改变主题色

### ISSUE THREAD

**Issue by bbeas** [ant-design/pro-components#7411]
### 🧐 问题描述
使用了Ant Design Pro官方代码，已经在defaultSettings.ts文件中修改了colorPrimary让其作用于ProLayout，但login页面并未嵌入ProLayout，所以在登录页面上修改主题色没有生效。如何让其生效？

### 💻 示例代码
使用Ant Design Pro官方使用手册新建的项目
```
npm i @ant-design/pro-cli -g
pro create myapp
```
修改了`config/defaultSettings.ts`中的`colorPrimary`变量

### 🚑 其他信息
登录后的页面已生效，登录页面未更改
<img width="449" alt="image" src="https://github.com/ant-design/pro-components/assets/29697116/24ff9cbc-c8a9-48d2-b7ee-ba82efa14108">
<img width="437" alt="image" src="https://github.com/ant-design/pro-components/assets/29697116/50a64961-e195-46c1-b80c-2cc804218f8b">

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/blob/54d9afef13b21f3a502048941f787dfcda0d910a/packages/layout/src/ProLayout.tsx#L864

看着行代码 这么做就可以了
