### ISSUE TITLE
🧐[问题]StepForm分布表单能支持响应式么？

### ISSUE THREAD

**Issue by ghuan** [ant-design/pro-components#7412]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

StepForm分布表单能支持响应式么？目前官网文档例子在屏幕较小的设备下都会呈现文本框超出屏幕的情况

### 💻 示例代码

无

### 🚑 其他信息

![1690094105427](https://github.com/ant-design/pro-components/assets/15809971/1c2cc028-18e3-4ca0-9c14-cc7b0c5782d3)
![1690094044091](https://github.com/ant-design/pro-components/assets/15809971/45578173-d1ef-4bc5-81e9-2b21e64c96c0)

**Comment by chenshuai2144** [comment]
设置个最大宽度就好了，我改下

**Comment by ghuan** [comment]
> 设置个最大宽度就好了，我改下

感谢您新增这个优化，我第一次使用antd pro，想再问下，目前我如何在现有的项目中（pro create myapp），更新并使用此优化？

**Comment by chenshuai2144** [comment]
等我发版本，你更新版本即可

**Comment by chenshuai2144** [comment]
我给你开个配置，你改下吧。


这个是什么哪个代码？给我下地址
