### ISSUE TITLE
🧐[问题]pro组件影响antd全局的国际化，导致Modal 提示框默认英文

### ISSUE THREAD

**Issue by vscing** [ant-design/pro-components#7413]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

默认Modal 提示框“确认”、“取消”按钮是中文，切到pro相关组件后，再打开Modal提示框“确认”、“取消”按钮是英文

**Comment by chenshuai2144** [comment]
看看是不是 antd  两份了。 pro  和  antd  用的都是一个  Provide
