### ISSUE TITLE
🐛[BUG] ProTable当是多层表头时搜索项不能正常渲染

### ISSUE THREAD

**Issue by hejinguo** [ant-design/pro-components#7416]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProTable只有一行表头时可以正常渲染搜索条件，当时多层表头时只有第一层标题可以正常显示出搜索条件
@chenshuai2144 
### 📷 复现步骤
<img width="1781" alt="image" src="https://github.com/ant-design/pro-components/assets/19966301/4bc40062-6065-4664-8088-02140bf2599a">

### 🏞 期望结果
期望表头中的项目都可以根据配置正常渲染搜索条件

### © 版本信息

    "@ant-design/icons": "^5.0.1",
    "@ant-design/pro-components": "^2.4.4",
    "@umijs/max": "^4.0.72",
    "antd": "^5.4.0",
    "immutability-helper": "^3.1.1"

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by hejinguo** [comment]
@Eileen-v 
用BetaSchemaForm.QueryFilter和ProTable搭配组合着先使用的。没再用ProTable的search.

<img width="556" alt="image" src="https://github.com/ant-design/pro-components/assets/19966301/39f1299c-1b00-4332-9c0c-132d01ab4e1b">

**Comment by Eileen-v** [comment]
@hejinguo 尝试了一下，确实可以，非常感谢~~🙇‍
