### ISSUE TITLE
🐛[BUG] ProForm 混合使用案例中下拉框利用request获取数据

### ISSUE THREAD

**Issue by heuaxa** [ant-design/pro-components#742]
### 🐛 bug 描述

混合使用案例中下拉框利用request获取数据时，选择选项后会发生偏移。

### 📷 复现步骤

查看案例即可
https://procomponents.ant.design/components/form#%E6%B7%B7%E5%90%88%E4%BD%BF%E7%94%A8

### 🏞 期望结果

不发生偏移

### 💻 复现代码

`
<ProFormSelect
        hasFeedback
        request={async () => [
          {
            label: '全部',
            value: 'all',
          },
          {
            label: '未解决',
            value: 'open',
          },
          {
            label: '已解决',
            value: 'closed',
          },
          {
            label: '解决中',
            value: 'processing',
          },
        ]}
        name="useMode"
        label="合同约定生效方式"
      />
`

### © 版本信息

- ProComponents 版本: lastest
- umi 版本 
- 浏览器环境 chrome 86
- 开发环境 windows 10

### 🚑 其他信息

发生偏移了
![image](https://user-images.githubusercontent.com/68598111/96210703-0605dc80-0fa5-11eb-8019-f6df3b6b3890.png)

**Comment by chenshuai2144** [comment]
这个好像是antd 的锅。 会出现不对其问题

**Comment by chenshuai2144** [comment]
版本发布了已经没问题了
