### ISSUE TITLE
🐛[BUG] [ProFormList] props.actionRender 的 `defaultActionDom` 文档有误

### ISSUE THREAD

**Issue by xlboy** [ant-design/pro-components#7420]
### 🐛 bug 描述

实际效果与文档描述有差异

---
[在线文档](https://procomponents.ant.design/components/group#actionrender-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%93%8D%E4%BD%9C%E6%8C%89%E9%92%AE)：
![image](https://github.com/ant-design/pro-components/assets/63690944/131f875c-e1ab-4b5f-8bb4-f1800f940d5b)
类型描述（ `packages/form/src/components/List/ListItem.tsx#174`）：
<img width="410" alt="image" src="https://github.com/ant-design/pro-components/assets/63690944/aa5ae274-6aff-4cb2-9481-11516133f459">
源码实现（`packages/form/src/components/List/ListItem.tsx#429`）：
<img width="700" alt="image" src="https://github.com/ant-design/pro-components/assets/63690944/4b389a45-25de-49b9-8e36-aecb4718feaa">

### 💻 在线链接
https://codesandbox.io/s/form-de-layout-qie-huan-forked-2nrgqy?file=/App.tsx:0-405

---

实际应该是 `[复制，删除]`？

**Comment by chenshuai2144** [comment]
是的，来个pr 吧

**Comment by chenshuai2144** [comment]
非常感谢，😘
