### ISSUE TITLE
🧐[问题] antd pro-components 样式兼容問題，添加 StyleProvider 沒有效果

### ISSUE THREAD

**Issue by XXuain** [ant-design/pro-components#7438]
遇到了不兼容舊版瀏覽器樣式問題
依照[官網样式兼容](https://ant-design.gitee.io/docs/react/compatible-style-cn)的方式添加 `<StyleProvider />` 後 沒有效果

```javascript
ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    {/* <ConfigProvider theme={{ hashed: false }}> */}
      <StyleProvider
        hashPriority="high"
        transformers={[legacyLogicalPropertiesTransformer]}
      >
      <RouterProvider router={router} />
      </StyleProvider>
    {/* </ConfigProvider> */}
  </React.StrictMode>
)
```

反而是加了 ` <ConfigProvider theme={{ hashed: false }}> ` 這樣子 antd 有效果，但 antd pro-components 依舊無法支持兼容

```javascript
ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <ConfigProvider theme={{ hashed: false }}>
      {/* <StyleProvider
        hashPriority="high"
        transformers={[legacyLogicalPropertiesTransformer]}
      > */}
      <RouterProvider router={router} />
      {/* </StyleProvider> */}
    </ConfigProvider>
  </React.StrictMode>
)
```

![截圖 2023-07-28 下午5 36 31](https://github.com/ant-design/pro-components/assets/34267828/c91c8397-bf0d-441c-ac1c-f13eb7a905da)

使用的版本：
```
    "@ant-design/cssinjs": "^1.16.0",
    "antd": "^5.6.2",
    "@ant-design/pro-components": "2.4.3",
    "@ant-design/icons": "^5.1.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "vite": "^4.3.9"
```

- 想請問有什麼方式能讓 pro-components  和 antd 一樣能支持舊版瀏覽器嗎？
- 不知道是不是我的 ` @ant-design/cssinjs ` 版本問題 ? 官網上說 ` 请注意版本保持与 antd 一致 ` 但我找到的版本就 `1.16.0` 這個

麻煩幫我解答一下了 謝謝

**Comment by suxin1** [comment]
遇到了同样的问题，ConfigProvider 提供的主题在 pro-components 中没有生效。

**Comment by chenshuai2144** [comment]
"@ant-design/cssinjs": "^1.16.0", 和 antd 的版本要保证只有一份的，你们可以用  `npm ls packageName` 来看看版本

**Comment by ningkehua** [comment]
> "@ant-design/cssinjs": "^1.16.0", 和 antd 的版本要保证只有一份的，你们可以用 `npm ls packageName` 来看看版本

这个能解释下什么意思吗
