### ISSUE TITLE
🐛[BUG] DatePicker组件中的周一周二等展示为了英文，期望展示中文

### ISSUE THREAD

**Issue by a526800921** [ant-design/pro-components#7439]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

DatePicker组件中的周一周二等展示为了英文，日历组件也是如此
<img width="1886" alt="image" src="https://github.com/ant-design/pro-components/assets/26155877/6ae9159f-5014-4f08-8ef1-49b69829900b">

### 📷 复现步骤

pro官网也是英文的

### 🏞 期望结果

期望是ant官网中一样的中文
<img width="1205" alt="image" src="https://github.com/ant-design/pro-components/assets/26155877/46e2b6d6-6a5c-47c9-b17d-c91ea861d8b4">

**Comment by chenshuai2144** [comment]
判断一下 dayjs 是不是重复了，官网是故意这么做的。
