### ISSUE TITLE
pro-table 的复选框错位 🐛[BUG]

### ISSUE THREAD

**Issue by liuweiGL** [ant-design/pro-components#744]
### 🐛 bug 描述

复选框没对齐。

### 🏞 期望结果
复选框对齐。

### © 版本信息

@ant-design/pro-table": "^2.9.5"

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/21048878/96224926-e382bc00-0fc2-11eb-81d4-54b6e76e1161.png)

**Comment by chenshuai2144** [comment]
修改了实现，不会有问题了
