### ISSUE TITLE
ProLayout布局menu 收缩后hover时menu首字母出现重复的问题

### ISSUE THREAD

**Issue by chenJJ-88** [ant-design/pro-components#7440]
![image](https://github.com/ant-design/pro-components/assets/118970817/eea5de8b-f69d-417c-8499-cfa44bf8bd94)
下面是我的  menuItemRender方法，这个是bug嘛？
   
 ```
menuItemRender={(menuItemProps, defaultDom) => {
              return (
                <div
                  onClick={() => {
                    setPathname(menuItemProps.path as string);
                  }}
                >
                  <Link to={menuItemProps.path}>
                    {/* {menuItemProps.icons && Icon[menuItemProps.icons]
                      ? React.createElement(Icon[menuItemProps.icons])
                      : ''} */}
                    {defaultDom}
                  </Link>
                </div>
              );
            }}
```

**Comment by chenshuai2144** [comment]
看起来是tootip 重复了，你给个在线demo吧

**Comment by chenJJ-88** [comment]
> 看起来是tootip 重复了，你给个在线demo吧

![image](https://github.com/ant-design/pro-components/assets/118970817/df401e93-1b3c-4cb4-9b0c-92d9a463028c)看了一下节点，这里多了一个字，在线实例没做出来呢

**Comment by chenshuai2144** [comment]
那你检查下你的本地版本是不是有问题。

不过的确有这个逻辑，会拿第一个字当 icon

**Comment by chenJJ-88** [comment]
> 那你检查下你的本地版本是不是有问题。
> 
> 不过的确有这个逻辑，会拿第一个字当 icon
![image](https://github.com/ant-design/pro-components/assets/118970817/8dbde38b-3c93-4eab-a0f3-681d7a31bc9c)
![image](https://github.com/ant-design/pro-components/assets/118970817/b56658fc-e28a-4944-a632-6d183317a0f4)
![image](https://github.com/ant-design/pro-components/assets/118970817/4eaa18fb-b853-4a1c-ad21-21c8273075a5)

使用的umi + Pro的，升级后也不行，而且我看版本也没低几个版本的。我把Layout的代码注释掉后再umi的运行时配置里面用layout插件，umi的menu 也是这样会出现重复的情况，

**Comment by chenshuai2144** [comment]
已经修复啦
