### ISSUE TITLE
🐛[BUG]TypeError: lo.useFormInstance is not a function 可编辑表格

### ISSUE THREAD

**Issue by fqblog** [ant-design/pro-components#7443]
TypeError: lo.useFormInstance is not a function 可编辑表格
"antd": "4.24.12",版本
"@ant-design/pro-components": "2.6.8", 版本

本地跑是好的，发到测试，线上环境渲染可编辑表格组件EditableProTable报错，，版本兼容性改了几次还是不行，这是为什么呢
<img width="613" alt="image" src="https://github.com/ant-design/pro-components/assets/19185036/55544b8c-1d1a-4f65-950b-383deb53d018">

**Comment by chenshuai2144** [comment]
![image](https://github.com/ant-design/pro-components/assets/8186664/f7da11f2-f7dd-478c-a758-b5fd68992cea)


检查下你的版本的， `npm ls antd`  是不是打包很多份

**Comment by lius14** [comment]
> TypeError: lo.useFormInstance is not a function 可编辑表格 "antd": "4.24.12",版本 "@ant-design/pro-components": "2.6.8", 版本
> 
> 本地跑是好的，发到测试，线上环境渲染可编辑表格组件EditableProTable报错，，版本兼容性改了几次还是不行，这是为什么呢 <img alt="image" width="613" src="https://user-images.githubusercontent.com/19185036/256811606-55544b8c-1d1a-4f65-950b-383deb53d018.png">

请问后来怎么解决的？
