### ISSUE TITLE
👑 [需求] ProFormColorPicker组件相比Antd的ColorPicker缺少属性

### ISSUE THREAD

**Issue by j511002** [ant-design/pro-components#7445]
### 🔩 所属模块或组件

ProForm组件：ProFormColorPicker。

### 🥰 需求描述

在使用ProFormColorPicker组件时，因为相比Antd的ColorPicker少了一些属性导致有些需求不好处理。

### ⛰ 功能需求适用场景

比如需要在picker的后面增添自定义文字，Antd的ColorPicker只需要添加showText功能即可实现，但是ProFormColorPicker就不行。

### 🧐 解决方案

是否可以将antd的ColorPicker的功能挪过来？

### 🚑 其他信息

<img width="410" alt="image" src="https://github.com/ant-design/pro-components/assets/14238111/46311eb9-1d4b-4fea-9991-85494ebe8ada">

**Comment by chenshuai2144** [comment]
两个不是一个组件，不一样的。
因为要兼容 旧 版本 antd 所以没用新版本的antd的，如果你要用推荐还是用 antd 自己的
