### ISSUE TITLE
🧐[问题]SettingDrawer 会适配左侧菜单的样式吗？自己配置还是不太方便，而且好像少了一选中菜单悬浮后字体颜色的设置

### ISSUE THREAD

**Issue by echoyl** [ant-design/pro-components#7448]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
放到  layout  里面就可以的。
