### ISSUE TITLE
ProTable的search配置中设置layout值为inline样式不生效🐛[BUG]

### ISSUE THREAD

**Issue by alucardhyx** [ant-design/pro-components#7450]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProTable的search配置中设置layout值为inline样式不生效
`<ProTable<ListItem>
...
search={{
	span: 7,
	searchText: '搜索',
	layout: 'inline',
	defaultCollapsed: false,
}}
...
`
![企业微信截图_16907811863250](https://github.com/ant-design/pro-components/assets/6358031/c2c10cca-bd18-469a-9239-d29031962377)
实际配置后页面效果
![企业微信截图_16907812858820](https://github.com/ant-design/pro-components/assets/6358031/d7891e06-8df3-4b58-8ada-0aadbeb55b8d)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
不能改的哦
