### ISSUE TITLE
🧐[问题] 哪个版本侧边导航改成了抽屉弹出的样式？

### ISSUE THREAD

**Issue by Hongbusi** [ant-design/pro-components#7451]
### 🧐 问题描述

哪个版本侧边导航改成了抽屉弹出的样式？

### 🚑 其他信息

[截图 demo 链接](https://procomponents.ant.design/~demos/packages-layout-src-components-layout-tab-api-demo-base?siderMenuType=sub&layout=mix)

![image](https://github.com/ant-design/pro-components/assets/53554371/95ad6619-b91f-433b-bfd9-e8fd65e49e52)

**Comment by chenshuai2144** [comment]
是个 bug，已经修复了。
