### ISSUE TITLE
🧐[问题]DrawerForm 或 ModalForm request 请求问题！

### ISSUE THREAD

**Issue by codedart2018** [ant-design/pro-components#7458]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
🧐[问题]DrawerForm 或 ModalForm request 请求问题！

rquest请求后返回一个对象，然后界面一直loding,我想用request替代init初始值。但我试过和table一样的data, success值返回，但它一样loding.不知道正确应该返回什么值。

### 💻 示例代码

```
      request={async () => {
        return {
          menus: [],
        };
      }}
```

**Comment by chenshuai2144** [comment]
返回一个对象，和  initalvalues  的类型是相同的
