### ISSUE TITLE
🧐[问题] 2.6.10 ProLayout 可否关闭菜单动画

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#7460]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

 2.6.10 ProLayout 可否关闭菜单动画

**Comment by chenshuai2144** [comment]
```
 '*': {
              transition: 'none !important',
            },
```
