### ISSUE TITLE
👑 [需求] transform 合并时，支持对象嵌套合并

### ISSUE THREAD

**Issue by wyhooo** [ant-design/pro-components#7463]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

`ProForm` 的 `transform` 功能

### 🥰 需求描述

`ProFormItem` 的 `transform` 功能，期望支持对象的多级合并

### ⛰ 功能需求适用场景

在表单项较多时，会有根据 `namePath` 分组的需求。此时如果传入 `transform` 合并时，并不会把 `value` assign 上去，而是直接覆盖（猜的，没看源码）。如果能用 assign 的方式就更好了。

详见 https://codesandbox.io/s/ri-qi-biao-dan-forked-y6dfrf?file=/App.tsx

可以看到控制台只输出了最后一个 transform 出来的结果，猜测之前的被直接覆盖掉了。

### 🧐 解决方案

调整 merge 策略

**Comment by BaoXianSheng** [comment]
transform 返回一个对象不想被merge，没有办法操作么。
 transform={(value, path) => {
        return { [path]: pick(value, ['key1', 'key2', 'key3']) };        
}

**Comment by k4281613** [comment]
本来用的好好的。。。，就是不需要原本的值的，现在这个版本会传递这个值，怎么去掉，会影响到后端取数据。
