### ISSUE TITLE
🧐[问题]PageContainer切换Tab，需要列表加载完成才能使蓝色线段彻底移动到正确位置。

### ISSUE THREAD

**Issue by edifangyi** [ant-design/pro-components#7464]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

Tab的下划线，切换的时候，需要等列表加载完成才能完成移动到正下方。

如何解决这个问题？

![image](https://github.com/ant-design/pro-components/assets/12421552/88f5bb7d-9855-4fec-883a-060aca08b2e5)

**Comment by chenshuai2144** [comment]
卡住了，你晚 300ms  再开始加载 tab
