### ISSUE TITLE
🐛[BUG] ProTable 的columns设置ellipsis后，title出现了省略号，但是移上去没有tooltip弹窗

### ISSUE THREAD

**Issue by xian107** [ant-design/pro-components#7468]
![image](https://github.com/ant-design/pro-components/assets/13252682/64bbecf6-4295-4a31-8883-9f8c92438842)

设置<ProTable onHeaderCell={column => ({title: '1111111111'})} />也是不起作用

**Comment by thinkasany** [comment]
<img width="1440" alt="image" src="https://github.com/ant-design/pro-components/assets/117748716/9c85f163-2956-444f-8d75-025b0f961375">

**Comment by chenshuai2144** [comment]
title  好像就是没有的，不知道 antd 那边怎么设计的

**Comment by xian107** [comment]
> title 就是没有的，不知道 antd 那边怎么设计的

但是antd标签上属性上会有title，移上去会出来title

**Comment by chenshuai2144** [comment]
debug 下？ 我这里没有更改过 title 的逻辑

**Comment by xian107** [comment]
> debug 下？ 我这里没有更改过 title 的逻辑

![image](https://github.com/ant-design/pro-components/assets/13252682/ff3c4466-e2c6-4181-ad43-46bc510a15ce)
antd官网的例子

**Comment by xian107** [comment]
@chenshuai2144  请问我要怎么才能把table中th省略的标题，用要原生的th的title属性显示出来
![image](https://github.com/ant-design/pro-components/assets/13252682/529f3f09-15fe-4063-9fa3-002c902550ae)
