### ISSUE TITLE
🐛[BUG] 使用 ProDescriptions.Item 报错，DescriptionsItem: `key` is not a prop.

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#7469]
Warning: DescriptionsItem: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.

<img width="554" alt="image" src="https://github.com/ant-design/pro-components/assets/30397655/739c5efc-b1bb-4ee1-9a92-7595aa246de1">

**Comment by leshalv** [comment]
<img width="697" alt="image" src="https://github.com/ant-design/pro-components/assets/30397655/f520952d-92a2-4b12-977d-3d1daa066ca2">

**Comment by WuJiY** [comment]
same question

**Comment by zhangheng0317** [comment]
我也发现了同样问题,在使用columns和dataSource时会报这个警告.
![image](https://github.com/ant-design/pro-components/assets/76459860/ab046335-3da0-4ea6-a394-8a77fbaaa624)

我又测试使用items就不报警告了
![image](https://github.com/ant-design/pro-components/assets/76459860/edff326f-00fa-4f47-9cde-03eb63d0bdb2)

**Comment by 662** [comment]
same question

**Comment by imjinbo** [comment]
> 我也发现了同样问题,在使用columns和dataSource时会报这个警告. ![image](https://user-images.githubusercontent.com/76459860/259617107-ab046335-3da0-4ea6-a394-8a77fbaaa624.png)
> 
> 我又测试使用items就不报警告了 ![image](https://user-images.githubusercontent.com/76459860/259617326-edff326f-00fa-4f47-9cde-03eb63d0bdb2.png)

非常感谢，请问这个items你是从哪里看到的，proComponents的官方文档可没有这个呀

**Comment by zhangheng0317** [comment]
> > 我也发现了同样问题,在使用columns和dataSource时会报这个警告. ![image](https://user-images.githubusercontent.com/76459860/259617107-ab046335-3da0-4ea6-a394-8a77fbaaa624.png)
> > 我又测试使用items就不报警告了 ![image](https://user-images.githubusercontent.com/76459860/259617326-edff326f-00fa-4f47-9cde-03eb63d0bdb2.png)
> 
> 非常感谢，请问这个items你是从哪里看到的，proComponents的官方文档可没有这个呀

antd5版本[Descriptions](https://ant-design.antgroup.com/components/descriptions-cn#api)组件的参数
