### ISSUE TITLE
👑 [需求]ignoreRules功能改进扩展建议

### ISSUE THREAD

**Issue by mansion-sun** [ant-design/pro-components#7472]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件
ProTable ProForm

### 🥰 需求描述
1.文档未明确ignoreRules使用方法， 在formItemProps处提及ignoreRules，但在ProForm中却未提及；
这不得不让人疑惑，ignoreRules是属于formItemProps或Columns 的一个属性，直到在Issue中找到了答案！！！
2.ignoreRules相当于对同一套rules做了开关，建议在Columns.formItemProps下添加searchRules，对查询表单的rules进行设置用来取代ignoreRules；
很大可能查询表单和编辑表单的校验字段、校验规则不完全一致，ignoreRules无法做到这一点进行精确校验

### ⛰ 功能需求适用场景
查询表单和编辑表单的校验字段、校验规则不完全一致

### 🧐 解决方案
在Columns.formItemProps下添加searchRules，对查询表单的rules进行设置用来取代ignoreRules；

**Comment by chenshuai2144** [comment]
这个东西就是不想让人用才做的这个难用的。

search 就不应该有  rule
