### ISSUE TITLE
🧐[问题] How to submit form on 'Enter' in a lightweight search filter with a protable.

### ISSUE THREAD

**Issue by jinseonghee** [ant-design/pro-components#7475]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
I' am customizing to search data while I' am using to protable. 
whenever I' am using search box in my protable, I have to click the submit button on my mouse. I want it to submit my form on enter with button as well.
but I don't know how to add the key event in a submit button.
when using search form component, they've already setting the reset and submit button. so I want to add on ther event handler but I don't know where I can handle it.
currently, I'am customizing several search box to search in my table data. and I want to add on the enter key event in all search box .
Is there any way to add on key event while I'am using default search box submit button in order to searching a data in my protable?

### 💻 示例代码
<img width="863" alt="image" src="https://github.com/ant-design/pro-components/assets/68724297/3f6fba1b-f1c1-4872-bf10-8950303ab8b1.png">

### 🚑 其他信息

<img width="863" alt="image" src="https://github.com/ant-design/pro-components/assets/68724297/c8de2269-f70c-49a5-960d-69820864ba9e.png">

**Comment by chenshuai2144** [comment]
| 参数 | 说明 | 类型 | 默认值 |
| --- | --- | --- | --- |
| isKeyPressSubmit | 是否使用回车提交 | `boolean` | - |

use this app

**Comment by jinseonghee** [comment]
I've used that Api that you've been knows me. but when I added on the api to use searcing the data putting like isKeyPressSubmit={true}, They operated event trigger, but I could not submit with parameter what I want to search it.
