### ISSUE TITLE
 ProFormText 不支持Input的suffix ？

### ISSUE THREAD

**Issue by codering** [ant-design/pro-components#748]
### 🐛 bug 描述

ProFormText 不支持Input的suffix

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
用 `fieldProps `来设置，suffix 用的比较少，不在第一层
