### ISSUE TITLE
🐛[BUG] 升级 pro-components 到 ^2.4.4，浏览器样式错误

### ISSUE THREAD

**Issue by YuDaChao** [ant-design/pro-components#7482]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🏞 期望结果

![image](https://github.com/ant-design/pro-components/assets/23699765/0cb54a77-cb97-4f43-98f8-372da8705eae)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- "@ant-design/icons": "^4.7.0",
- umi 版本
- "umi": "^3.5.34",
- 浏览器环境
- 开发环境 [e.g. mac OS]
- mac OS
- antd 版本
- "antd": "^4.20.0",

### 🚑 其他信息

360极速浏览器（Safariy也会出现）
![image](https://github.com/ant-design/pro-components/assets/23699765/5764fb65-4001-462a-bc61-e8056284e3af)

**Comment by YuDaChao** [comment]
出现两个 header
这个正常显示的样式
![image](https://github.com/ant-design/pro-components/assets/23699765/dcf4c66b-ae9a-4ba1-8fa6-ee0ff6be5191)

这是 360 极速浏览器显示的样式
![image](https://github.com/ant-design/pro-components/assets/23699765/071ce52b-9b11-4efa-bc15-8edfac61c407)

请知道的大佬帮忙看看， 谢谢🙏

**Comment by chenshuai2144** [comment]
https://pro-components.antdigital.dev/docs/faq#chrome88-%E4%BB%A5%E4%B8%8B%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E9%97%AE%E9%A2%98
看这里
