### ISSUE TITLE
🧐[问题] ProCard dark mode issue

### ISSUE THREAD

**Issue by Skyriis** [ant-design/pro-components#7485]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

I'm using the `ProCard` component inside of an Antd `ConfigProvider` with a theme that is in dark mode but for some reason the `ProCard` does appear to remain in the light mode.

Is there any setup i need to do to make it work?

#### Light Mode
![image](https://github.com/ant-design/pro-components/assets/128689017/26218f73-38fa-4380-87d0-725dea5a2af1)

#### Dark Mode
![image](https://github.com/ant-design/pro-components/assets/128689017/6c0a76d0-3d3e-44ae-b9f0-64a4eaf9c339)

**Comment by Skyriis** [comment]
I only got one antd version:

```
PS C:\Users\A92615470\IdeaProjects\myproject> pnpm ls antd
Legend: production dependency, optional only, dev only

myproject@0.0.1 C:\Users\A92615470\IdeaProjects\myproject

dependencies:
antd 5.8.2
```

**Comment by zhaohuanlei** [comment]
遇到同样问题，无解

**Comment by zhaohuanlei** [comment]
> 我只有一个 antd 版本：
> 
> ```
> PS C:\Users\A92615470\IdeaProjects\myproject> pnpm ls antd
> Legend: production dependency, optional only, dev only
> 
> myproject@0.0.1 C:\Users\A92615470\IdeaProjects\myproject
> 
> dependencies:
> antd 5.8.2
> ```
> 
> 但我仍然遇到了这个问题

你解决了么
