### ISSUE TITLE
🐛[BUG] ProTable 分页报错

### ISSUE THREAD

**Issue by YuDaChao** [ant-design/pro-components#7487]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
这个问题偶尔复现，本地没问题，部署上线后点击切换分页，控制台报错。
报错截图如下
![image](https://github.com/ant-design/pro-components/assets/23699765/aaa270d6-2ce9-4ed2-bd1a-6ee21d222195)
其他项目分页也会报错，但是错误不是这个。

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- ^2.3.57
- antd 版本
- ^5.2.2
- umi 版本
- ^4.0.52
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
能点进去看看具体是哪一行吗、

**Comment by YuDaChao** [comment]
已经使用迫不得已的方式修复了（使用 codeup 流水线打包部署就会有问题，本地打包的不会。），下次复现再提哈。

**Comment by YuDaChao** [comment]
@chenshuai2144 点击分页报错 本地复现了 
![image](https://github.com/ant-design/pro-components/assets/23699765/bbddba8f-378d-48fe-b6e8-a7f6519c0f74)
![image](https://github.com/ant-design/pro-components/assets/23699765/422e3f1c-4720-46f9-832c-f7af3fe3f6b8)
