### ISSUE TITLE
🐛[BUG]ProFormDatePicker组件，编辑时再次点击会出现clone.weekday is not a function的错误

### ISSUE THREAD

**Issue by zhangyj1998** [ant-design/pro-components#7488]
### 🐛 bug 描述

在使用ProFormDatePicker组件时，第一次修改日期不会报错，第二次再次点击组件时，会出现"clone.weekday is not a function"错误

### 📷 复现步骤

```
// 会出现错误
<ProFormDatePicker name="date" />
// 不会出现错误
<Form.Item name="date">
  <DatePicker />
</Form.Item>
```

### 🏞 期望结果

不会出现错误

### © 版本信息
- antd:5.8.2
- ProComponents 版本: 2.6.11
- umi 版本:4.0.33
- 浏览器环境:谷歌
- 开发环境 mac OS

**Comment by pc110** [comment]
我也遇到过，在package.json 加上 "dayjs":"1.11.9"。 就没有问题了

**Comment by chenshuai2144** [comment]
是因为dayjs 打包了两份导致的

**Comment by j7-dev** [comment]
`package.json` 加上

```
  "resolutions": {
    "dayjs": "^1.11.10"
  }
```
也有用
