### ISSUE TITLE
🐛[BUG] ModalForm 上传文件，由于改变高度样式变形

### ISSUE THREAD

**Issue by bxvs888** [ant-design/pro-components#7489]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]  2.6.11
- umi 版本  4.0.74
- 浏览器环境  safari 
- 开发环境 [e.g. mac OS]  Macos

### 🚑 其他信息

<img width="759" alt="截屏2023-08-07 22 36 47" src="https://github.com/ant-design/pro-components/assets/298322/36403886-bf64-4c1f-bf2e-b526c0fcfa3f">

**Comment by chenshuai2144** [comment]
设置一下 overflow 吧。组件不好做限制
