### ISSUE TITLE
🐛[BUG]使用ProForm完成表单时触发跳转路由事件，这个导致报错Can't perform a React state update on an unmounted component...

### ISSUE THREAD

**Issue by wscart** [ant-design/pro-components#749]
### 🐛 bug 描述

使用proForm完成创建表单再次提交，然后在当前页面的时候触发跳转路由事件才会导致产生 Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.的错误。

尝试操作：
1、报错之后再次刷新就会好了
2、在编辑模式的时候提交触发跳转路由都没有报错的

这个原因应该是说，创建表单的字段数据与获取详情的字段数据不一样会导致报错的

另附：这个页面有两个模式： 表单与详情

### 💻 复现代码

```
  const getDetail = useRequest(getDetailInfo, {
    manual: state === 'create' ? true : false,
    onSuccess: (result: any) => {
      if (result.code !== 0) {
        message.warning(result.msg);
      }
    },
  });

  const submit = useRequest(setDetailInfo, {
    manual: true,
    onSuccess: (result: any) => {
      if (result.code !== 0) {
        message.warning(result.msg);
      } else {
        const path = route.path;
        const rowKey = route.rowKey;
        const res = result.data;
        const id = res[rowKey];
        message.success('一会儿进入详情');
        history.push(path.replace(`:${rowKey}`, id) + '?mode=read');
      }
    },
  });

<PageContainer title={false}>
      <Card>
        {getDetail.loading ? <ProSkeleton type="descriptions" /> : <Row>
          <Col span={14}>
            <ProForm
              submitter={state === 'edit' || state === 'create' ? {
                render: (_, dom) => {
                  return <FooterToolbar>{dom}</FooterToolbar>
                },
              } : { render: () => null }}
              onFinish={async (values) => {
                await submit.run(values);
              }}
              form={form}
            >
              {state === 'edit' || state === 'create' ? getInfoColumns(route.name, true).filter((column: any) => column.mode.includes(state)).map((column: any, index: number) => {
                return ProFormItem(column, getDetail.data?.data, index, state)
              }) : getInfoColumns(route.name, false).map((column: any, index: number) => {
                return <Descriptions column={24} key={index}>{ProFormItem(column, getDetail.data?.data, index, 'info')}</Descriptions>
              })}
            </ProForm>
          </Col>
        </Row>}
      </Card>
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本： 3.2.23
- 浏览器环境： chrome
- 开发环境 [e.g. mac OS] : 10.15.7

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/3970076/96232154-7c690580-0fca-11eb-8e36-f313e9deeb7e.png)

**Comment by chenshuai2144** [comment]
不是的，这个错误的原因，是因为组件解除卸载还去更新dom导致的。

form 中有个loading的设置，在 onFinsh结束之后去设置，结果onFinsh中解除挂在了组件，导致了这个问题

**Comment by wscart** [comment]
好了，我解决了 谢谢！ @chenshuai2144

**Comment by zhouzyc** [comment]
请问除了使用setTimeout调整执行顺序外。还有其他解决办法吗

**Comment by chenshuai2144** [comment]
嗯，因为状态是异步的，除非 做专门的控制把组件都变成异步的

**Comment by joker77877** [comment]
> 不是的，这个错误的原因，是因为组件解除卸载还去更新dom导致的。
> 
> form 中有个loading的设置，在 onFinsh结束之后去设置，结果onFinsh中解除挂在了组件，导致了这个问题
> 
> 有一个简单的绕开办法，你可以在 setTimeout 里，执行跳转的代码

这里还是没搞懂什么意思，我也是相同问题而且我没有跳转操作，我只要点击浏览器的返回就会出现这个问题，我如何避免这个报错

**Comment by erniu** [comment]
> 不是的，这个错误的原因，是因为组件解除卸载还去更新dom导致的。
> 
> form 中有个loading的设置，在 onFinsh结束之后去设置，结果onFinsh中解除挂在了组件，导致了这个问题
> 
> 有一个简单的绕开办法，你可以在 setTimeout 里，执行跳转的代码

如果是点击浏览器自身的返回上一页，这个问题也无法通过setTimeout返回呀？
