### ISSUE TITLE
🐛[BUG] ProLayout 升级最新版本后出现bug

### ISSUE THREAD

**Issue by pc110** [ant-design/pro-components#7498]
ProLayout 升级最新版本后出现bug

https://github.com/ant-design/pro-components/assets/29336835/80c42cd3-3ef2-46e7-95ea-d1b4f649b21a

**Comment by huangsheng7271** [comment]
Why is your sidebar white instead of the gray one in the demo? How did you set it up?

**Comment by pc110** [comment]
> Why is your sidebar white instead of the gray one in the demo? How did you set it up?

defaultSettings.ts

  token:{
    bgLayout:"#f5f6f8",
    sider : {
      colorTextMenuSelected :"#1890ff",
      colorTextMenuActive :"#1890ff",
      colorTextMenuItemHover:"#1890ff",
    }
  }

**Comment by pc110** [comment]
这个bug, 能优先解决么？

**Comment by chenshuai2144** [comment]
详细描述一下，我看到好像是动画乱了？

**Comment by pc110** [comment]
> 详细描述一下，我看到好像是动画乱了？

大佬，提了个新bug #7518. 详细描述了重现过程，麻烦帮忙看看哈。

**Comment by chenshuai2144** [comment]
好啦 

![1691913630894_1691913627258](https://github.com/ant-design/pro-components/assets/8186664/4f2f6916-3cf4-4fa3-9d31-c23325b8d949)


看到是这里的问题
