### ISSUE TITLE
🐛[BUG] 菜单现在是居中的，如何左对齐？

### ISSUE THREAD

**Issue by pc110** [ant-design/pro-components#7499]
🐛[BUG] 菜单现在是居中的，如何左对齐？ 
![03ef228bb5f96e0da840356a95c6841](https://github.com/ant-design/pro-components/assets/29336835/2fdff723-df4c-4fad-8027-38bd03912070)

antd的菜单是左对齐的。
![image](https://github.com/ant-design/pro-components/assets/29336835/76240886-4080-4489-a157-693779da4348)

**Comment by chenshuai2144** [comment]
修复了，更新下版本
