### ISSUE TITLE
🐛[BUG] 升级完以后就这样了

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#750]
![image](https://user-images.githubusercontent.com/30397655/96238573-39f6f700-0fd1-11eb-8993-036ad8ee8268.png)

**Comment by chenshuai2144** [comment]
更新一下依赖呢？
看起来是是hooks不存在的问题

**Comment by leshalv** [comment]
翻译过来是这样，不要在useEffect（...），useMemo（...）或其他内置的Hook中调用Hook。您只能在React函数的顶层调用Hook。有关更多信息

**Comment by Matthew10r** [comment]
應該要怎麼解決 我升級了都有這errors 喔...
