### ISSUE TITLE
🐛[BUG] ProTable 自定义搜索条件，renderFormItem 时不能默认设置某一项条件不展示

### ISSUE THREAD

**Issue by lx815** [ant-design/pro-components#7501]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

按照官方文档的自定义搜索条件代码进行调试，将select的默认值设置为4，想要上一个input框不展示。但是还是展示了input框。需要手动切换select的值，再次选到4的时候才会隐藏input框.

### 📷 复现步骤

按照官方文档的自定义搜索条件代码进行调试，将select的默认值设置为4，想要上一个input框不展示。但是还是展示了input框。需要手动切换select的值，再次选到4的时候才会隐藏input框。

### 🏞 期望结果

renderFormItem 支持默认不展示某个form.item

### 💻 复现代码

[](https://codesandbox.io/s/plgrj4?file=/App.tsx)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
renderFormItem  支持返回一个 null 的，这样就不会展示了
