### ISSUE TITLE
🐛[BUG]protable 开启全屏工具fullScreen会导致syncToUrl变化时异常

### ISSUE THREAD

**Issue by ranvk** [ant-design/pro-components#7508]
### 🐛 protable 开启全屏工具fullScreen会导致syncToUrl变化时异常

第一次点击搜索，正常，改变搜索条件时再次搜索，url不再变化，去掉fullScreen参数，恢复正常

### 📷 复现步骤

       syncToUrl: true和 fullScreen: true, 

### 🏞 期望结果

fullScreen=true时功能正常

### 💻 复现代码
     form={{
          syncToUrl: true,
        }}
        options={{
          fullScreen: true, 
        }}

### © 版本信息

- ProComponents 版本: ^2.6.11
- umi 版本 4.0.24
- 浏览器环境
- 开发环境 mac OS

### 🚑 其他信息

-->

**Comment by jokyczq** [comment]
+1，我也遇到这个问题
