### ISSUE TITLE
🐛[BUG] EditableProTable 使用 defaultRender(scheme) 导致选时间组件 bug

### ISSUE THREAD

**Issue by TubeTexas** [ant-design/pro-components#7514]
### 🐛 bug 描述

在 EditableProTable 的 columns 中，valueType 为 'date' 且 renderFormItem 使用 defaultRender(scheme) 时，编辑模式输入非数字会显示 ”Invalid date“。如图是我输入拼音时候的效果：
![image](https://github.com/ant-design/pro-components/assets/48426450/3e5c283f-c5f4-4d76-a291-8c0e9212b1a4)

### 📷 复现步骤

![image](https://github.com/ant-design/pro-components/assets/48426450/53c31908-be0d-4060-b4eb-35164afdb30b)

### 🏞 期望结果

和 renderFormItem 不用 defaultRender 时渲染的选日期组件一样，输入非数字组件自动忽略。

### 💻 复现代码

暂无

### © 版本信息

- ProComponents 版本: "@ant-design/pro-table": "2.80.6"

### 🚑 其他信息
无

**Comment by kungege** [comment]
我在 `3.10.6` 上没有复现，升级版本看看

**Comment by chenshuai2144** [comment]
dayjs 的版本固定一下
