### ISSUE TITLE
🧐[问题] PageContainer 的 token 配置不生效

### ISSUE THREAD

**Issue by QiuMing** [ant-design/pro-components#7515]
### 🧐 问题描述

我在使用 PageContainer ，我想实现 Container 中 content 部分，padding 为0 。
![image](https://github.com/ant-design/pro-components/assets/11348698/994cfa44-d821-462d-8849-c0d538f55bfc)

我阅读了官方文档： https://procomponents.ant.design/components/layout#pagecontainer-token 
发现它有这么个参数 token?:pageContainerToken 可以设置。 我做了以下尝试：
* 在全局的配置文件中设置 token ，这个可以生效，**但我期望只在指定的页面生效，所以这不符合的期望**
* 在指定的 PageContainer 中设置token ，不生效，代码如下：

```
 <PageContainer
      ghost
      token={{
        paddingInlinePageContainerContent: 0,
        paddingBlockPageContainerContent: 0
      }}
      header={{
        title: "单价运营"
      }}
      extra={
        <Space size={[0, 8]} wrap>
          {tagsData.map((tag) => (
            <CheckableTag
              key={tag}
              checked={selectedTags === tag}
              onChange={() => handleChange(tag)}
            >{tag}
            </CheckableTag>
          ))}
        </Space>
      }
    ></PageContainer>
```
我不确定这个 token 是不是只能作用于全局，所以来这请教。
如果token 不能单独作用于 PageContainer ，还有什么别的办法达到 padding 为 0 的效果

**Comment by chenshuai2144** [comment]
你可以用 childrenContentStyle，强制覆盖一下

**Comment by QiuMing** [comment]
感谢，解决了我的问题
