### ISSUE TITLE
ConfigProvider设置marginLG后ProFormList的action没有生效🐛[BUG]

### ISSUE THREAD

**Issue by mengsui** [ant-design/pro-components#7526]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

<ConfigProvider
  theme={{
    token: {
      marginLG: 8
    },
  }}
>
设置marginLG后ProFormList的action的marginBlockEnd不生效，但是formitem生效了导致样式错位。

### 🏞 期望结果

希望marginLG设置后action的marginBlockEnd生效

### 💻 复现代码

  <ConfigProvider
    theme={{
      token: {
        marginLG: 8
      },
    }}
  >
    <ProForm
      layout="horizontal"
    >
      <ProFormList
        label="测试"
        name="test"

      >
        <ProFormText
          name="name"
        />
      </ProFormList>
    </ProForm>
  </ConfigProvider>

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
<img width="1420" alt="image" src="https://github.com/ant-design/pro-components/assets/22537028/1073f120-526c-455c-9aec-b547014de7f2">

**Comment by hanwenbo** [comment]
应该不行吧 代码里固定写法
