### ISSUE TITLE
🧐[问题]请问怎么获取组件的DesignToken呢？

### ISSUE THREAD

**Issue by NickeyLin** [ant-design/pro-components#7527]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

比如我想要获取ProLayout.Header下方有一个副标题，希望这个副标题的背景色和Header的背景色表现一致（亮色模式及暗色模式）。
但是通过`useToken`拿到的token中没有组件的token。

```
import { theme } from 'antd';

// ...
// 拿不到组件的token
const { token } = theme.useToken();
// ...
```

**Comment by chenshuai2144** [comment]
```
import { proTheme } from '@ant-design/pro-provider';  
const { token } = proTheme.useToken?.();
```

用这个token

**Comment by JasonJunMa** [comment]
@chenshuai2144 还是无法获取组件的token哎，是我用法错误吗
```
  import { proTheme } from '@ant-design/pro-provider';
  import { useEmotionCss } from '@ant-design/use-emotion-css';
  const headerRowClass = useEmotionCss(() => {
    const { token } = proTheme.useToken?.();
    return {
      padding: '2px',
      position: 'sticky',
      textAlign: 'center',
      background: token.Table?.headerBg,
    };
  });
```
这种 token.Table?.headerBg 获取不到

**Comment by minisola** [comment]
> @chenshuai2144 还是无法获取组件的token哎，是我用法错误吗
> 
> ```
>   import { proTheme } from '@ant-design/pro-provider';
>   import { useEmotionCss } from '@ant-design/use-emotion-css';
>   const headerRowClass = useEmotionCss(() => {
>     const { token } = proTheme.useToken?.();
>     return {
>       padding: '2px',
>       position: 'sticky',
>       textAlign: 'center',
>       background: token.Table?.headerBg,
>     };
>   });
> ```
> 
> 这种 token.Table?.headerBg 获取不到

```
import { ProProvider } from "@ant-design/pro-components";

const {token} = useContext(ProProvider);
```
我试了下要这样才可以取到

**Comment by flowkscai** [comment]
上面的几种方式试过都获取不到，请问现在是换了获取方式吗？
