### ISSUE TITLE
🐛[BUG]DrawerForm关闭时调用onFinish

### ISSUE THREAD

**Issue by eric-chaw** [ant-design/pro-components#753]
### 🐛 bug 描述

ProForm中DrawerForm在点击关闭时, 调用onFinish方法.

### 📷 复现步骤

1. 使用trigger控制打开/关闭的情况下, 点击关闭, 调用onFinish (同时触发表单验证)
2. 使用visible控制打开/关闭的情况下, 点击关闭, 同样调用onFinish (同时触发表单验证)

### 🏞 期望结果
1.  不触发表单验证
2.  不触发回调onFinish

### 💻 复现代码
```
<DrawerForm
      drawerProps={{
        title: `新增`,
        maskClosable: false,
        onClose: () => props?.onClosed && props.onClosed()
      }}
      form={form}
      layout="vertical"
      onFinish={onSubmit}
      onVisibleChange={(visible) => {
        if (!visible) {
          form.resetFields();
        }
      }}
      submitter={{
        submitButtonProps: {loading: submitting},
      }}
      {...props}
    >
```
### © 版本信息

- ProForm: 1.0.2
- umi 版本: 3
- 浏览器环境: chrome 86.0.4240.75
- 开发环境: Windows

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/pro-components/issues/722
