### ISSUE TITLE
[BUG] 使用 message 静态方法时报错 

### ISSUE THREAD

**Issue by kavout-it** [ant-design/pro-components#7532]
在封装 request.ts 请求工具方法中，使用了 `message.error(errorMessage);` 
报错：Static function can not consume context like dynamic theme.

请不要直接简单指向另外一个 Issue，都已经按相关 Issue 方案尝试过了。无法解决问题。

特别说明：我不是在组件中使用 message，是在 `request.ts` 普通TS 文件中使用。

以往给出正面、直接的修复方案和示例

**Comment by chenshuai2144** [comment]
request.ts  报错这个很合理吧。
你要不换个提醒库，或者用 window 上挂一个
