### ISSUE TITLE
🐛[BUG] Select 组件初始化时有一个空值

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/pro-components#7542]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

```jsx
 {
      title: '选择区服',
      dataIndex: 'group_id',
      valueType: 'select',
      hideInTable: true,
      initialValue: null,
      renderFormItem: () => <AreaServiceSelect />,
      search: {
        transform: (value) => {
          console.log('sas1,', value, Array.isArray(value) ? value.join(',') : value)

          return {
            group_id: Array.isArray(value) ? value.join(',') : value,
          }
        },
      },
    },
```

<img width="423" alt="image" src="https://github.com/ant-design/pro-components/assets/124666577/79ae21b4-2a2d-47c7-92bb-35034eb11069">

**Comment by chenshuai2144** [comment]
![image](https://github.com/ant-design/pro-components/assets/8186664/d88f5822-64f1-429d-b12d-a36e897aba18)

你的组件里面处理一下，是不是把undfinded 当成 一个object了

**Comment by vaynevayne** [comment]
<img width="723" alt="image" src="https://github.com/ant-design/pro-components/assets/124666577/d108648d-294b-462a-b612-f5b511431be5">

@chenshuai2144  这需要修改哪里? 没看出来

**Comment by chenshuai2144** [comment]
props.value 里面。你用的自定义组件，form会给你注入 value的
