### ISSUE TITLE
🧐[问题]ModalForm 关闭时 onOpenChange 触发2次 open 都是fasle

### ISSUE THREAD

**Issue by YuShai** [ant-design/pro-components#7545]
### 🧐 问题描述
ModalForm  onOpenChange function在关闭时候被触发2次，打开的时候触发1次，关闭时触发2次的open都是false。求解惑
### 💻 示例代码

```html
 <ModalForm
                open={open}
                title={'测试'}
                form={form}
                autoFocusFirstInput
                width={500}
                onOpenChange={(open) => {
                    console.log('open', open);//关闭时候2次都是false
                    setOpen(false)
                }}
                modalProps={{ destroyOnClose: true, forceRender: false, }}
                submitter={{
                    render: (props, defaultDoms) => {
                        return [
                            <Button key="extra-reset" onClick={() => {
                                props.reset();
                            }}  >  重置 </Button>,
                            ...defaultDoms,
                        ];
                    },
                }}
                onFinish={async (values) => {
                    return true;
                }}
                autoComplete="off"
            >
            </ModalForm>
```

**Comment by liujiayii** [comment]
@chenshuai2144 应该是onFinish触发了一次 setOpen(false)又触发了一次，

**Comment by chenshuai2144** [comment]
搞个 pr 吧，做个判断。而且没不影响。

**Comment by YuShai** [comment]
> 搞个公关吧，做个判断。而且没影响。

试了，还是存在一点影响的，我没有去使用onOpenChange

**Comment by YuShai** [comment]
> @chenshuai2144应该是onFinish触发了一次setOpen(false)又触发了一次，

onFinish我没有去return true;
取消了使用onOpenChange
使用了onCancel，就正常了

**Comment by chenshuai2144** [comment]
绕开了 也不是啥好办法

**Comment by HaceraI** [comment]
今天在查询Redux Actions时偶然发现了`onOpenChange`为false时会触发两次Action，起初以为是代码哪块重复调用了，仔细检查确实没有重复调用; 研究发现是组件本身在`trigger={undefined}`回传了两次 `onOpenChange(false)`:
![image](https://github.com/ant-design/pro-components/assets/48341368/e3c9c711-3dfe-4ec7-bad2-ed45de10cb89)

对于为何在传入`trigger`时，onOpenChange 即会恢复正常，本人功力尚浅，百思不得其解，盲猜涉及到了状态更新机制

我觉得最简单的修复方法就是修改 `afterClose`: `open && setOpen(false);`
