### ISSUE TITLE
editableprotable批量添加新行时遇到的奇怪问题

### ISSUE THREAD

**Issue by RickyX2012** [ant-design/pro-components#7546]
我获取到一组数据，试图通过map（或者for循环），使用addEditRecord完成所有行的添加。
但是每次都只有最后一条数据被添加到新行中，通过输出可以看到，每个循环都正确执行，就是每次的数据都填写在同一行中，没有新增，后面的数据总数覆盖了前面的。
如果使用timeout延时处理，有时候会出现多一些的行，但是并不完整，也不能稳定重现。
示例代码：
for(let i=0;i<value.length;i++){
          let uId = GetUID();
          let e = value[i];
          
          // setTimeout(()=>{
            let r = actionRef?.current?.addEditRecord({
            id: 0,   
            _UID: uId,
            ProductId: e.Id,
            ProductName: e.ProductName,
          });
}
_UID是用来做RowKey的。
使用console输出，循环的指令都正确执行了，_UID也确定每次都不一样，而且数据都正确，就是都只在一行上完成操作，导致的结果就只增加了一行，数据是最后一条，前面的都被覆盖了。输出editableFormRef?.current?.getRowsData?.() 就会明确看到添加前是上一条记录，添加后没有变成多条记录，而是仍然只有一条记录，数据是新加的那条。
新增行添加参数 {newRecordType: 'dataSource', recordKey: uId, } 也是一样没能解决这个问题。

**Comment by chenshuai2144** [comment]
await 一下 `actionRef?.current?.addEditRecord`
