### ISSUE TITLE
🐛[BUG]ProFormMoney通过键盘输入16个9时数值变为1个1和16个0

### ISSUE THREAD

**Issue by kglive** [ant-design/pro-components#7547]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

金额录入组件ProFormMoney在通过键盘输入15个9时显示正常，再输入一个9时，控件中的数字变为10000000000000000，同时控件的上下累加操作也无效。

### 📷 复现步骤

1. 随便一个金额录入组件，通过键盘输入15位9，控件显示999999999999999，正常；
2. 紧接着再通过键盘输入一个9，控件显示10000000000000000，不正常；

### 🏞 期望结果

键盘输入16个9，控件显示9999999999999999（16个9）

### 💻 复现代码

官方文档案例即可复现
[官方文档案例](https://procomponents.ant.design/components/form#proform-demo-money)

### © 版本信息

- ProComponents 版本: 官网文档使用的版本

### 🚑 其他信息

似乎设置了trigger="onBlur"属性，不会出现此问题。
![image](https://github.com/ant-design/pro-components/assets/28862191/785c0ee0-753c-4d6a-a7e4-51cb07568f64)

15个9的正确结果
![image](https://github.com/ant-design/pro-components/assets/28862191/f5c00d1a-3cb4-42fe-900a-a83d1aeba454)

16个9的错误结果
![image](https://github.com/ant-design/pro-components/assets/28862191/085e97e7-fd8e-4941-a17c-0c145d7b73bb)

**Comment by chenshuai2144** [comment]
超过 js 支持的number 最大值了，如果需要这么大的数据建议用 string 靠谱一些
