### ISSUE TITLE
🐛 [BUG] layout为top，路由菜单背景变为透明了

### ISSUE THREAD

**Issue by wanglihuaya** [ant-design/pro-components#7549]
### 🐛 bug 描述

创建最新的pro，`defaultSettings.ts` 设置 `layout` 为 `top`，当有多级路由菜单时，`menu` 背景变为 `(255,255,255,0,6)` 了 

### 📷 复现步骤 | Recurrence steps

同上

### 🏞 期望结果 | Expected results

和 组件 menu 一样

### 💻 复现代码 | Recurrence code

脚手架创建的最新本的ant-design-pro

### © 版本信息

- Ant Design Pro 版本: 6.0.0
- umi 版本: 4.0.52
- 浏览器环境: chrome 115
- 开发环境  mac OS

<img width="433" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/49522285/ac3a79e3-47c9-414c-98a3-56e152d54a1f">

**Comment by wanglihuaya** [comment]
大佬们 帮忙看看

**Comment by chenshuai2144** [comment]
![image](https://github.com/ant-design/pro-components/assets/8186664/4710260c-95f8-4426-a283-ec46b96af535)


你的毛玻璃没生效吗？

**Comment by wanglihuaya** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/264676077-4710260c-95f8-4426-a283-ec46b96af535.png)
> 
> 你的毛玻璃没生效吗？

毛玻璃有生效，只是路由菜单变成透明的了

**Comment by dqrjz** [comment]
@chenshuai2144 不是顶部菜单栏本身，是弹出的子菜单popup的背景变透明了：
![Screenshot 2023-09-05 at 5 07 44 PM](https://github.com/ant-design/pro-components/assets/38813747/f6572724-2a29-4717-9fa1-974c2ebaf290)

在暗色模式下是不透明的：
![Screenshot 2023-09-05 at 5 07 52 PM](https://github.com/ant-design/pro-components/assets/38813747/37dedfd0-e7a9-4c66-ae10-317929f42f2d)

复现：https://github.com/dqrjz/ant-design-pro-debug

**Comment by zhongjiaguo001** [comment]
这个有解决方案，透明看不清菜单中的内容

**Comment by zhongjiaguo001** [comment]
这个有解决方案了吗，菜单中的内容看不见

**Comment by chenshuai2144** [comment]
升级到最新版本试试，antd默认设置成白色或者黑色了

**Comment by someok** [comment]
> 升级到最新版本试试，antd默认设置成白色或者黑色了

antd 和 pro-components 均为最新版，top 模式下菜单仍然是半透明效果
