### ISSUE TITLE
🐛[BUG] - Type Error from @ant-design/pro-layout/lib/index.d.ts

### ISSUE THREAD

**Issue by carpben** [ant-design/pro-components#755]
Installed pro-layout in a CRA-Typescript project. Also have antd installed.

I had copy pasted code from an example (https://codesandbox.io/s/mkesj?file=/App.tsx) which resulted in an type error which seems to come from the library itself: 

![image](https://user-images.githubusercontent.com/13496178/96261257-dcf74300-0fc8-11eb-9e7d-e84b4c633e49.png)

Typescript version 3.75. 
Any idea what the problem is and how I can solve it?

**Comment by tomlo0925** [comment]
try upgrade to typescript 3.8 which supports export type
