### ISSUE TITLE
👑 [需求] 表格搜索表单是否可以增加设置成在表头下方展示

### ISSUE THREAD

**Issue by zhongjiaguo001** [ant-design/pro-components#7550]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

ProTable

### 🥰 需求描述

ProTable中通过列生成的搜索表单，可以设置成在表格的表头中下方展示

### ⛰ 功能需求适用场景

减少页面占用大小

### 🧐 解决方案

无

### 🚑 其他信息
非常感谢您宝贵的时间
![image](https://github.com/ant-design/pro-components/assets/44691489/1a339410-4e7b-4c36-8871-8fc053b9e0e7)

![image](https://github.com/ant-design/pro-components/assets/44691489/7dcf6aad-dbdd-43d2-bfdb-43bcbbbb96e2)

**Comment by chenshuai2144** [comment]
这个不符合antd的设计规范，你可以通过自定义表头来实现一下
