### ISSUE TITLE
👑 [需求]使用ProLayout期待一个keep alive的效果

### ISSUE THREAD

**Issue by blankzust** [ant-design/pro-components#7553]
### 🔩 所属模块或组件
率属组件：ProLayout

### 🥰 需求描述

类似这样的效果：
![image](https://github.com/ant-design/pro-components/assets/8541906/ba64a824-c833-4f78-bc6b-64208210896a)

### ⛰ 功能需求适用场景

proLayout本身已经实现了顶部菜单，顶部菜单点击后本能感觉是状态不变的，所以需要一个keep alive的效果

**Comment by chenshuai2144** [comment]
等待react来做呢，社区有些的，你可以去看看。各有各的缺点，看你能忍受哪个
