### ISSUE TITLE
🐛[BUG] columns 配置了枚举之后 render 的表现在 ProTable 和 ProDescriptions 中表现不一致

### ISSUE THREAD

**Issue by 662** [ant-design/pro-components#7554]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProTable 中的 columns 配置了枚举之后， render 第一个参数拿到的是枚举转换 **之后** 的值
ProDescriptions  中的 columns 配置了枚举之后， render 第一个参数拿到的是枚举转换 **之前** 的值

* 不确定哪个是正确的表现，如果拿到转换 **之后** 的值可能会更符合预期
* 不确定其他类似的组件是否存在该现象
* 不确定是否需要表现一致，但如果表现一致可能会降低心智成本

### © 版本信息

- ProComponents 版本: 2.6.11
- umi 版本: 4.x
- 浏览器环境: chrome@latest
- 开发环境 MacOS

**Comment by liu-xuewen** [comment]
+1 , 这个枚举问题很常见，

ProTable到valueEnum枚举在ProDescriptions不生效；

另外还有个问题：ProTable的valueType为digit/dateTime 也在ProDescriptions不生效
