### ISSUE TITLE
🐛[BUG] ProForm request 是不是有缓存? 

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/pro-components#7555]
切到该页面, request 触发, 切走, 切回来 request 触发了, 但是页面没有应用最新值

```jsx
     request={async () => {
            const res = await request('/api/report/get')
            const a = res.data ? postData(res.data) : {}
return a 
          }}


```
<img width="725" alt="image" src="https://github.com/ant-design/pro-components/assets/124666577/edd72c8d-4e77-44e2-a99e-f323be333402">

**Comment by chenshuai2144** [comment]
request  修改的是默认值，默认值只有 首次render才生效，之后是不会生效的

**Comment by vaynevayne** [comment]
> request 修改的是默认值，默认值只有 首次render才生效，之后是不会生效的

1. 问题是我路由切走了, Form组件不是应该销毁吗? 
2. 默认值是 useState,组件 mounted 就给的, 你异步接口回来还能再次修改默认值?  这不科学
