### ISSUE TITLE
🧐[问题]ProColumns 类型校验问题

### ISSUE THREAD

**Issue by js1121302139** [ant-design/pro-components#7556]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
webstrom中类型校验提示异常，但是在vscode中不会出现
    "@ant-design/pro-components": "^2.6.13",
    "typescript": "^5.0.2",

### 💻 示例代码
const columns: ProColumns<SysUserPageItem_RES>[] = [
  { dataIndex: 'userName', title: '姓名', align: 'center', ellipsis: true, width: '100px' },
  { dataIndex: 'rybs', title: '人员标识', align: 'center', ellipsis: true },
  { dataIndex: 'bmbsVal', title: '所在部门', align: 'center', ellipsis: true, search: false },
  { dataIndex: 'teamName', title: '团队', align: 'center', ellipsis: true, search: false },
  { dataIndex: 'userTypeVal', title: '人员类型', align: 'center', ellipsis: true, search: false }
]

![image](https://github.com/ant-design/pro-components/assets/24861005/a9e4b1f5-ff38-428e-806d-e3fffcec523f)
![image](https://github.com/ant-design/pro-components/assets/24861005/f750deba-9e0c-440f-ba2f-8157e760f8fc)

**Comment by chenshuai2144** [comment]
试着升级一下antd版本，听说 webstrom 的 ts 类型是自己实现的和 官方的不一样
