### ISSUE TITLE
🧐[问题]ProTable自定义valueType， transform该如何使用？

### ISSUE THREAD

**Issue by AlexErnsberger** [ant-design/pro-components#7557]
### 🧐 问题描述

我现在只能在使用组件的时候，注册transfrom。这个时候transform是生效的。
```
...
{
      title: '所属题库',
      dataIndex: 'categoryId',
      width: 150,
     //  自定义valueType
      valueType: 'examTypeCascader',
     //  value转换
      search: {
        transform: (value) => getProFormExamTypeCascaderValue(value),
      },
    },
...
```
但是如果我想把上述的transform放在注册级别（即valueTypeMap中），好像不生效：

```
const valueTypeMap = {
  examTypeCascader: {
    search: {
      transform: (value) => getProFormExamTypeCascaderValue(value),
    },
    render: (categoryId) => {
      return getProFormExamTypeCascaderName(categoryId);
    },
    renderFormItem: (text: string, props, dom) => {
      return <ExamTypeCascader {...props} {...props.fieldProps} />;
    },
  },
}
```
放在注册级别的初衷是不用每次使用的时候都去写transform。

**Comment by Wei0809** [comment]
`{
      dataIndex: 'StatisticalTime',
      title: 'Date Range',
      hideInTable: true,
      valueType: 'dateRange',
      initialValue: [dayjs(), dayjs()],
      fieldProps: {
        allowClear: false,
        ranges: getRangePickerRanges(),
      },
      search: {
        transform: (value) => ({
          start_date: dayjs(value[0]).format('YYYYMMDD'),
          end_date: dayjs(value[1]).format('YYYYMMDD'),
        }),
      },
    },`
