### ISSUE TITLE
🐛[BUG] 使用ProDescriptions.Item label 不显示

### ISSUE THREAD

**Issue by faner11** [ant-design/pro-components#7560]
### 🐛 bug 描述

升级到 2.6.13 后 
<ProDescriptions>
  <ProDescriptions.Item label='name'>张三</ProDescriptions.Item>
</ProDescriptions>

label 不显示

### 🏞 期望结果

正常

### 💻 复现代码

```
<ProDescriptions>
  <ProDescriptions.Item label='name'>张三</ProDescriptions.Item>
</ProDescriptions>
```

https://codesandbox.io/s/columns-pei-zhi-forked-443v66?file=/App.tsx

- ProComponents 版本: [e.g. 2.6.13]

![image](https://github.com/ant-design/pro-components/assets/26560612/6faa063d-e42f-4897-814b-b0960d126ba1)

**Comment by NeverStop1024** [comment]
我们开发环境也遇到了相同问题，请问有解决吗？
