### ISSUE TITLE
🐛[BUG] 大佬，bug #7518 没有修改好哦，并出现了一个新的问题，帮忙在看一下

### ISSUE THREAD

**Issue by pc110** [ant-design/pro-components#7563]
bug #7518 这个bug 还有问题
重现步骤：
1. 打开官网demo
https://procomponents.ant.design/~demos/packages-layout-src-components-layout-tab-api-demo-sidermode
![1692709786088](https://github.com/ant-design/pro-components/assets/29336835/d51f615e-48ae-4d5c-a059-353a89c47490)
2. 选择欢迎菜单
![1692710109286](https://github.com/ant-design/pro-components/assets/29336835/390b0552-6d1e-40a0-b451-f904caeaf16e)
3. 收起侧边栏，显示Tips菜单
![1692710177159](https://github.com/ant-design/pro-components/assets/29336835/d4f48b74-d8da-4738-934b-bf44137ac12e)
4. 在展示开侧边栏，收缩二级菜单原来的Tips又显示出来了

https://github.com/ant-design/pro-components/assets/29336835/5c648f5f-9d0a-4ecb-a735-a7e1fc2397be

另一个问我提了另外一个bug #7564

**Comment by chenshuai2144** [comment]
我看了下官网可以了，是antd 版本是多少

**Comment by pc110** [comment]
> 我看了下官网可以了，是antd 版本是多少

不可以哦，需要先打开欢迎菜单， 不要选择二级菜单，然后收起侧边栏，鼠标移入有二级菜单的浮现出Tips菜单。然后展开侧边栏，在展开收缩二级菜单就能出现视频的效果   。 按照这个bug的步骤就能官网重现

**Comment by pc110** [comment]
https://github.com/ant-design/pro-components/assets/29336835/8138ee18-9de8-45b3-91de-705dab94347c

**Comment by pc110** [comment]
有时间看么？
