### ISSUE TITLE
🧐[问题]pro-table在antd4.x的情况下，无法编译，控制台less报错

### ISSUE THREAD

**Issue by lk0606** [ant-design/pro-components#7569]
### 🧐 问题描述
本地环境使用pro-table，搜索表单无法展示显示，查询重置按钮在，playground切换到antd4.x的情况下，编辑报错。切换到5.x后编译成功。
本地环境
umi2.x
antd-pro2.x
antd4.x
pro-components最新版本
### 💻 示例代码
在线地址： https://codesandbox.io/s/cha-xun-biao-ge-forked-tpj66x?file=/App.tsx
### 🚑 其他信息

![image](https://github.com/ant-design/pro-components/assets/43233310/49438f9b-ccc6-4e30-9cab-cddecff640b5)

**Comment by chenshuai2144** [comment]
搞下脚手架吧。这个和组件应该没关系的

**Comment by lwpersonal** [comment]
我也遇到类似的问题，老版本的 antd 使用 proC 的时候，根本不知道要使用哪个版本的包。他俩的版本不匹配就有各种资源引用问题。
