### ISSUE TITLE
🐛[BUG] Cannot find module 'packages/utils/es' or its corresponding type declarations.

### ISSUE THREAD

**Issue by whh8162880** [ant-design/pro-components#7573]
环境
vite + electron +  ant design + ts + react 引用了 "@ant-design/pro-form": "^2.18.1"

### 🐛 bug 描述

用tsc编译代码 会报错

`
node_modules/_@ant-design_pro-form@2.18.1@@ant-design/pro-form/es/components/Cascader/index.d.ts:11:28 - error TS2307: Cannot find module 'packages/utils/es' or its corresponding type declarations.

11     proFieldProps?: import("packages/utils/es").ProFieldProps | undefined;

`

index.d.ts 中的定义

` proFieldProps?: import("packages/utils/es").ProFieldProps | undefined; `

packages/utils/es 是什么？我需要怎么做才能编译成功呢？

**Comment by LangWuyue** [comment]
解决了吗？我升级到"@ant-design/pro-components": "^2.6.18"还是有这个问题
![dd72a26a8deec93fac44f3343dbdbbc8](https://github.com/ant-design/pro-components/assets/25575108/835d6760-adf1-4f3e-8552-d42734a15211)
