### ISSUE TITLE
👑 [需求] ProTable 搜索表单条件改变时自动触发查询

### ISSUE THREAD

**Issue by YooEcho** [ant-design/pro-components#7577]
### 🔩 所属模块或组件
ProTable

### 🥰 需求描述
在后台系统中，经常会有切换状态值、时间范围、下拉选择框等搜索条件，希望能修改值后自动触发查询。

目前也可以通过设置 onValueChange 再调用 formRef.submit 去更新，但这样每个表格都需要设置，挺不优雅的。

### 🧐 解决方案
建议在  ProColumns 中加个设置，是否允许修改值后触发查询，或自动触发查询的类型（比如：change、blur）

**Comment by YooEcho** [comment]
> ### 以下问题可能会对您有帮助 / 以下问题可能对您有帮助
> * [ [🧐[问题] ProTable 搜索表单的onInit 不生效？](https://github.com/ant-design/pro-components/issues/5546)[ #5546](https://github.com/ant-design/pro-components/issues/5546) ][🧐[问题] ProTable 搜索表单的onInit 不生效？][62%][](https://github.com/ant-design/pro-components/issues/5546)

**Comment by PlutoCA** [comment]
应该可以监听搜索表单onValuesChange, 再去调用表格的actionRef

**Comment by chenshuai2144** [comment]
不推荐这样做，点了submit去查询最优雅
