### ISSUE TITLE
Form  loading一直不结束

### ISSUE THREAD

**Issue by whereiscode** [ant-design/pro-components#758]
请问 https://procomponents.ant.design/~demos/query-filter
这个loading什么时机才会结束呢？

**Comment by whereiscode** [comment]
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/55313887/96280991-4b5cf500-100b-11eb-80fe-b0ddecf4aef5.png">

**Comment by chenshuai2144** [comment]
有了返回值才会结束，我改一下 demo

**Comment by whereiscode** [comment]
@chenshuai2144 您好这个版本什么时候发布呢？
