### ISSUE TITLE
🧐[问题] ProTable何如监听 设置展示列的变化，设置默认显示的列

### ISSUE THREAD

**Issue by YuDaChao** [ant-design/pro-components#7580]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
<img width="217" alt="image" src="https://github.com/ant-design/pro-components/assets/23699765/bca51b56-5725-478a-a414-06a549d26294">

**Comment by PlutoCA** [comment]
https://procomponents.ant.design/components/table#columnstatetype
多看下文档~
