### ISSUE TITLE
🐛[BUG] 组件菜单不能完全显示

### ISSUE THREAD

**Issue by SnowballXueQiu** [ant-design/pro-components#7591]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

- 在`Antd-Pro-Components`中, 左侧组件菜单不能完全显示.

### 📷 复现步骤

- 打开 [`组件总览 - ProComponents`](https://procomponents.ant.design/components) 即可在左侧看到我所描述的问题.

### 🏞 期望结果

- 将整个列表完整的显示出来.

### 💻 复现代码

- 打开浏览器即可复现

### © 版本信息

- ProComponents 版本: 2.6.13
- 浏览器环境: Google Chrome
- 开发环境: Windows 10

### 🚑 其他信息

- 但我在浏览器开发人员工具中发现, `原子组件` 已经是最后一个组件了, 如果您方认为后面如果的确没有组件, 应在下方留出一块区域, 或放上其他元素.

- 图示如下: **(此处我已将鼠标滚轮划至底部)**
![bug.png](https://s2.loli.net/2023/08/28/ahSGdusxMoH47Kt.png)

**Comment by chenshuai2144** [comment]
浏览器兼容性问题吧

![image](https://github.com/ant-design/pro-components/assets/8186664/e3deaec3-65b2-41c3-a845-dde4e0e75344)

**Comment by SnowballXueQiu** [comment]
## **首先**, 我不认为这是由于我浏览器导致错误, 因换到 `Safari浏览器` 也有同样的问题.
可能是由于我之前的描述不清导致了您的理解偏差, 故我现在重新描述问题.
- 只有将整个页面拉到最底部才可以j将列表显示完全, 而正常情况下应该是将侧边导航栏拉到最底部就可以显示完整列表.
- 只要整个页面的滚动条没有拉到最底部, 即使导航栏的滚动条已经拉到了最底部, 仍然会出现如上情况.
---
## 希望开发者重新检查是否存在以上我描述的问题, 若存在, 请 `打开issue` 并在 `解决之后` 关闭issue.
---
## 附件:
![image](https://github.com/ant-design/pro-components/assets/97330394/2cc0cab2-26dd-4834-bc8c-12c3be2f3e10)

**Comment by SnowballXueQiu** [comment]
@chenshuai2144
