### ISSUE TITLE
🧐[问题]PageContainer 如何在当前页面设置header部分的padding，不影响其他页面的

### ISSUE THREAD

**Issue by daisybaicai** [ant-design/pro-components#7594]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
![image](https://github.com/ant-design/pro-components/assets/25605435/46b3b207-9918-44d1-a412-7373ca8e97ad)

希望能把这个tab底部的padding去掉，目前查找了

    <PageContainer
      title="线索处置1"
      tabList={TAB_LIST}
      token={{
        paddingBlockPageContainerContent: 0
      }}
      id="myDiv"
    >
      <Card>tabs</Card>
    </PageContainer>

目前在当前页面设置了paddingBlockPageContainerContent 会导致上下以及其他部分的padding都出现异常，如何解决

**Comment by chenshuai2144** [comment]
把这个东西弄到一个 Context 里面然后动态设置就好了
