### ISSUE TITLE
🐛[BUG]ModalForm组件底部按钮间距不对

### ISSUE THREAD

**Issue by qianchengjie** [ant-design/pro-components#7595]
### 🐛 bug 描述
ModalForm组件底部按钮间距不对

### 📷 复现步骤
直接看样式，期望按钮间距为8px，但实际为16px
<img width="265" alt="image" src="https://github.com/ant-design/pro-components/assets/27612520/3a78cb9c-4520-4597-9f11-a683d1e6eadd">

### 🏞 期望结果
按钮间距为8px

### 💻 复现代码
https://codesandbox.io/s/trcdxl

### © 版本信息

- ProComponents 版本：2.6.13
- antd 版本：5.9.2
- 浏览器环境：Chrome
- 开发环境：mac OS

**Comment by AccerYou** [comment]
按钮间距不对，你就自己写一个样式覆盖嘛，这也发一个issue.......

**Comment by ONLY-yours** [comment]
这个属于设计使然了，你的业务要是不一致的话自己覆盖下吧。

**Comment by qianchengjie** [comment]
是设计不统一，倒也不是说自己不能，牛

**Comment by qianchengjie** [comment]
而且这个一看样式就知道是样式设计的有问题

**Comment by AccerYou** [comment]
这该死的回复订阅通知。。。那就回复你一下吧~
【bug】指的是影响程序运行或导致结果不对，而不是一个因人而异的样式问题~
把issue留给哪些无法解决、且影响结果的问题上吧

**Comment by qianchengjie** [comment]
好的，不好意思，是我有强迫症
