### ISSUE TITLE
🧐[问题] EditableTable 如何实现新增一行的时候需要填写这列的字段，而编辑的时候禁止修改这列的字段？

### ISSUE THREAD

**Issue by yaochenkun** [ant-design/pro-components#7596]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by SummyGitHub** [comment]
使用 renderFormItem 自定义
https://procomponents.ant.design/components/editable-table#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%AF%E7%BC%96%E8%BE%91%E8%A1%A8%E6%A0%BC
