### ISSUE TITLE
🐛[BUG] ProForm里使用了  ProFormText 组件并设置prefix:<Icon/> 会导致界面崩溃

### ISSUE THREAD

**Issue by Merely-chao** [ant-design/pro-components#7597]
### 🐛 bug 描述

表单里使用了  ProFormText 组件并设置prefix:<Icon/> ，输入内容会导致界面崩溃

### 📷 复现步骤

[https://codesandbox.io/s/captcha-forked-xpyd6x](https://codesandbox.io/s/captcha-forked-xpyd6x)

### 🏞 期望结果

输入内容正常

### © 版本信息

    "@ant-design/icons": "5.0.1",
    "@ant-design/pro-components": "2.6.14",
    "antd": "5.8.4",
    "react": "18.2.0",
    "react-dom": "18.2.0"

### 🚑 其他信息
![image](https://github.com/ant-design/pro-components/assets/39617057/479ba6eb-b8b1-4313-87cf-d85ac49c7810)

**Comment by juntity** [comment]
所以 解决了吗 这个bug

**Comment by chenshuai2144** [comment]
升级到 2.16.4 解决了
