### ISSUE TITLE
🐛[BUG] ProForm里使用了  ProFormText 组件并设置prefix:<Icon/> 会导致界面崩溃

### ISSUE THREAD

**Issue by Merely-chao** [ant-design/pro-components#7598]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

    "@ant-design/icons": "5.0.1",
    "@ant-design/pro-components": "2.6.14",
    "antd": "5.8.4",
    "react": "18.2.0",
    "react-dom": "18.2.0"

**Comment by andyFang94** [comment]
升级后直接崩了呀
