### ISSUE TITLE
ProTable 的 columns 中的 某一行设置了  ellipsis: true，但是会出现内容超出tooltip的情况

### ISSUE THREAD

**Issue by chenJJ-88** [ant-design/pro-components#7605]
![image](https://github.com/ant-design/pro-components/assets/118970817/a2079565-b62c-49f2-8707-e201b4572b88)
这种是怎么什么情况呢

**Comment by chenshuai2144** [comment]
ellipsis 只能对付文本，dom 要自己实现哦
