### ISSUE TITLE
🐛[BUG] appList 跨站点导航列表点击不能跳转

### ISSUE THREAD

**Issue by baiwumm** [ant-design/pro-components#7606]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

实际情况可以访问复现：https://react.baiwumm.com/
![image](https://github.com/ant-design/pro-components/assets/40554571/7c435430-87a4-474a-9c72-020dee3e1823)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你的框架做了什么事情，把 a 标签的click事件全部重写了，

AppList 是用 a 标签做的跳转

**Comment by gao525280067** [comment]
我也是这个问题，只有混合布局模式下正常，关键还不能自定义

**Comment by zhanyeye** [comment]
请问大佬后来是 如何解决的呢

**Comment by baiwumm** [comment]
> 请问大佬后来是 如何解决的呢

解决个球，开源团队说我的问题，这个也不重要，后来也没管

**Comment by zhanyeye** [comment]
> > 请问大佬后来是 如何解决的呢
> 
> 解决个球，开源团队说我的问题，这个也不重要，后来也没管

为啥你的demo现在可以跳转呀，怎么做到的，好好看！
