### ISSUE TITLE
🐛[BUG] ProLayout Bug， 当显示的菜单不是浮现的Tips二级菜单的时候，展开收起该二级菜单，原本隐藏的Tips二级菜单又显示出来了

### ISSUE THREAD

**Issue by pc110** [ant-design/pro-components#7607]
🐛[BUG] ProLayout Bug， 当显示的菜单不是浮现的Tips二级菜单的时候，展开收起该二级菜单，原本隐藏的Tips二级菜单又显示出来了

https://github.com/ant-design/pro-components/assets/29336835/95a67e69-1a50-4fb9-a619-1186368727b7

重现步骤：

打开官网demo
https://procomponents.ant.design/~demos/packages-layout-src-components-layout-tab-api-demo-sidermode
![image](https://github.com/ant-design/pro-components/assets/29336835/20fb09f3-3b7e-44da-a198-a4417863d352)

选择欢迎菜单， 目前显示的欢迎菜单
![image](https://github.com/ant-design/pro-components/assets/29336835/6b99ef18-fd84-4665-be25-ae9916015ea0)

收起侧边栏，显示Tips菜单
![image](https://github.com/ant-design/pro-components/assets/29336835/bc24cdbb-2be0-4e47-9570-f22912a08753)
展开收起该二级菜单，原本隐藏的Tips二级菜单又显示出来了
![image](https://github.com/ant-design/pro-components/assets/29336835/9f2b6a28-0143-48b2-81f4-9a5e61da769b)

**Comment by chenshuai2144** [comment]
试试，新版本应该好了

**Comment by pc110** [comment]
> 试试，新版本应该好了

这就是最新版。官网可重现

**Comment by pc110** [comment]
等一个更新

**Comment by ByYogi** [comment]
我复现一下简单步骤：
1. 收缩所有菜单栏；收起`侧边栏`
3. 移入两个菜单图标；第二个要移入`三级菜单`；使显示悬浮菜单选项
4. 打开`侧边栏`；展开菜单栏
6. 第二个菜单栏三级菜单 切换展开收缩
出现异常蹦出悬浮菜单选项
![screenshots](https://github.com/ant-design/pro-components/assets/111735598/753c8f79-7798-43e1-8fff-dad8e771e9a2)
