### ISSUE TITLE
🐛[BUG] 官网组件页面左侧菜单显示不全

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/pro-components#7613]
### 📷 复现步骤

![image](https://github.com/ant-design/pro-components/assets/12181423/23fcc032-8bf2-485c-9b54-9246df60e255)

https://procomponents.ant.design/components

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
是不是浏览器兼容问题，我看到是可以的。

![image](https://github.com/ant-design/pro-components/assets/8186664/39b205da-e38b-4505-9ee1-673eec60ef33)
