### ISSUE TITLE
🐛[BUG] DrawerForm  resize 和 isResizable 是描述错误还是代码缺失？

### ISSUE THREAD

**Issue by LengYXin** [ant-design/pro-components#7614]
### 🐛 bug 描述
文档：
![image](https://github.com/ant-design/pro-components/assets/19631404/1bebd07b-066f-4fd8-89e4-c8fda714a932)
代码：代码中并没有 isResizable
![image](https://github.com/ant-design/pro-components/assets/19631404/2d2cd542-1923-4eb4-a9d2-8bf72ad5562d)

在使用的时候有点迷惑。
描述错误 我改下文档？，代码错误 我就 去更新一下代码？

**Comment by chenshuai2144** [comment]
文档忘记更新了，来个 PR 吧
