### ISSUE TITLE
👑 [需求] 使用modalForm 封装了组件，但在父组件直接里直接执行了子组件的useEffect 函数,希望可以支持只渲染trigger dom,或者有别的好的方案吗

### ISSUE THREAD

**Issue by 957651480** [ant-design/pro-components#7617]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🥰 需求描述

以下是子组件:
const UserModalPermissionForm:React.FC<ModalFormProps>=(props)=>{

    useEffect(()=>{
        console.log(0)
    },[])

    return (
        <ModalForm
        title="新建表单"

        {...props}

        >
            <Checkbox >文件管理</Checkbox>
            <ProFormCheckbox.Group

                options={['农业', '制造业', '互联网']}
            />
        </ModalForm>
    )
}

export default UserModalPermissionForm

以下是父组件(功能列表某项点击权限弹出上面子组件)
 <UserModalPermissionForm
                    trigger={
                        <Button type="primary">
                            权限
                        </Button>
                    }
                />,

**Comment by chenshuai2144** [comment]
`   forceRender?: boolean;`

试试这个api。

**Comment by Icesource** [comment]
@957651480 你有解决这个问题吗，我也遇到了同样的问题，但是forceRender并没有解决
