### ISSUE TITLE
🧐[问题]如何控制焦点

### ISSUE THREAD

**Issue by RickyX2012** [ant-design/pro-components#7620]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

有时候，我们在某个字段输入完成后，希望光标能够自动跳转到指定的格子（不一定是下一个格子），继续完成录入。
一直没有找到方法。

**Comment by chenshuai2144** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus

搞个id，然后调用这个方法

**Comment by RickyX2012** [comment]
Thanks！
就是有一些字段是可以这样跳转焦点，还有一些竟然没有反应。
使用了同样的ProformText，同样在fieldProps中使用 onPressEnter，每个字段都几乎是完全拷贝过去，只做关键的name更改。
很奇怪。
