### ISSUE TITLE
🐛[BUG] EditableProTable无法用editableFormRef 设置新建的编辑状态数据

### ISSUE THREAD

**Issue by ByYogi** [ant-design/pro-components#7624]
### 🐛 bug 描述
测试低版本不会有这个问题，是v2.6.*之后的问题

EditableProTable无法用editableFormRef 设置新建的(`编辑时状态`)数据
如果有初始数据，则不会出现这个问题。
如果没有初始数据，新建的编辑状态行数据无法通过`editableFormRef`动态设置数据。

### 📷 复现步骤
* 初始0条数据，新建2条数据: 设置第2行数据 无效
* 初始1条数据，新建1条数据: 设置第2行数据 有效; 设置第3行数据 无效
* 初始2条数据，新建0条数据: 设置第2行数据 有效
(降级版本到2.4.4则不会出现这个问题)

### 💻 复现代码
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/editableformref-no-work-of-editeditableprotable-f55f4t?file=/App.tsx)
![image](https://github.com/ant-design/pro-components/assets/111735598/93f75046-242a-4117-bce4-99034b90cad2)

### © 版本信息

- ProComponents 版本: v2.6.16
- umi 版本: v4.0.41
- 浏览器环境: Google Chrome v116.0.5845.141 (Official Build) (64-bit)
- 开发环境: Window10

**Comment by ByYogi** [comment]
我还试了`ProCom@2.4.4` + `@umijs/max@4.0.40` 以上版本 也会有这个问题。

还注意到有问题的版本丢失了验证样式。
（第一个图s是高版本没有✅，并且赋值有问题。第二个图没有该问题。并且`umijs`影响`ProCom@2.4.4`也会导致没有验证样式✅，同样赋值问题。猜测`umijs`会把自带的`ProCom`版本覆盖自己安装的）
![image](https://github.com/ant-design/pro-components/assets/111735598/cc6cd9a2-e561-4340-af00-09f3e2cbded1)
![image](https://github.com/ant-design/pro-components/assets/111735598/9948223a-3693-49d4-b0db-723ac5412d3a)

**Comment by ByYogi** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
修复啦，可以试试了，一个简单的form为空的问题

**Comment by ByYogi** [comment]
> 修复啦，可以试试了，一个简单的form为空的问题

根据你说的修复时间 11月5日. 应该是这个版本 `@ant-design/pro-components@2.6.35`
![image](https://github.com/ant-design/pro-components/assets/111735598/dd400688-52fd-4d6c-a5cd-44d34949f44d)
