### ISSUE TITLE
🧐[问题]使用proTable组件。当点击搜索的时候会自动将搜索条件更新到路由上， 能否通过配置取消？

### ISSUE THREAD

**Issue by Rookiewhs** [ant-design/pro-components#7626]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

点击搜索按钮的时候会自动将搜索条件添加到路由上，如果其中有下拉框搜索且该下拉的数据源的value不是字符串类型时，此时刷新页面，下拉框由于数据类型不一致会匹配不上，能否点击搜索的时候取消掉更新路由的动作，或者在保留的情况下如何处理这种情况

### 💻 示例代码
//当数据源类型为 valueEnum 时可以回显
              {
			title: "机构等级",
			dataIndex: "grade",
			valueType: "select",
			valueEnum: {
				1: "三级甲等",
				2: "三级乙等",
				3: "三级丙等",
				4: "三级特等",
				5: "二级甲等",
				6: "二级乙等",
				7: "二级丙等",
				8: "一级甲等",
				9: "一级乙等",
				10: "一级丙等"
			}
		},
//当数据源设置为options时，不能回显
		{
			title: "所在城市",
			dataIndex: "cityMap",
			valueType: "cascader",
			fieldProps: {
				options: options,
				loadData: loadData,
				changeOnSelect: true,
				fieldNames: {
					label: "name",
					value: "id",
					children: "children"
				}
			},
			hideInTable: true
		},

### 🚑 其他信息
![image](https://github.com/ant-design/pro-components/assets/50982616/c28ab9d5-355f-42fd-87fe-cf946b7c5770)

**Comment by dreammaker7** [comment]
form={{ syncToUrl: false }}
