### ISSUE TITLE
🐛[BUG] pro-layout 一级菜单 hideInMenu: true， 不生效

### ISSUE THREAD

**Issue by JaylanChen** [ant-design/pro-components#763]
### 🐛 bug 描述

pro-layout 6.5.0版本后（6.5.0 版本正常） 一级菜单 hideInMenu: true， 不生效，依然会显示在菜单栏

### 📷 复现步骤

安装升级 6.5.0 之后的版本出现

### 🏞 期望结果

hideInMenu：true，不显示在菜单栏

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/7055008/96393363-7c971a00-11f1-11eb-8f95-4757c22a359b.png)

**Comment by chenshuai2144** [comment]
来个重现的 repo，测试用例看起来没问题

**Comment by JaylanChen** [comment]
layout:"mix" , splitMenus: true   的情况下 会出现bug

[bug重现demo](https://codesandbox.io/s/gallant-wozniak-qgdp4)

不知道为什么这个forked的demo样式有点问题，不过不影响此bug复现；
