### ISSUE TITLE
🐛[BUG] ProFormFieldSet 仍然提示 'Input.Group' is deprecated. 

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#7632]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

index.js:1 Warning: [antd: Input.Group] 'Input.Group' is deprecated. Please use 'Space.Compact' instead.

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/commit/89e1fb4

这里已经改掉了

**Comment by HAOYI99** [comment]
你好 @chenshuai2144，
我用这些版本，还是有这个warning
 
> "@ant-design/pro-components": "^2.8.2",
> "antd": "^5.21.6",

```
<ProFormFieldSet type={"group"}>
    <ProFormDigit/>
    <ProFormDigit/>
</ProFormFieldSet>
```

**Comment by zmm2tysu** [comment]
@chenshuai2144 同上
