### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by XinYueXiao** [ant-design/pro-components#7635]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
选中查询的label 和直接选中label 返回结果不一致
### 📷 复现步骤

- 在下拉框中输入 全部
- 选中查询结果 “全部”
- 返回的结果中label 是一个对象

- 直接选中未解决
- 返回的label 是 字符串
![image](https://github.com/ant-design/pro-components/assets/31272499/e9ba318e-5eeb-46dc-b966-a5f874952793)

### 🏞 期望结果

返回结果一致

### 💻 复现代码

https://codesandbox.io/s/cha-xun-biao-dan-forked-z7rwjw?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]
![image](https://github.com/ant-design/pro-components/assets/31272499/e733f298-aa6a-47bb-86c1-03cc8eb81ab6)

**Comment by wk544863858** [comment]
同样遇到该问题，有解决掉了吗? @XinYueXiao

**Comment by wk544863858** [comment]
> 同样遇到该问题，有解决掉了吗? @XinYueXiao

观察了一下数据，配置optionLabelProp: 'title'即可解决问题
`  return <ProFormSelect name={name}
                        label={label}
                        width={width}
                        debounceTime={300}
                        placeholder={placeholder}
                        request={request}
                        fieldProps={{
                          ...fieldProps,
                          labelInValue: true,
                          showSearch: true,
                          optionLabelProp: 'title',
                        }}
                        rules={rules}/>`
