### ISSUE TITLE
🐛[BUG] StepsForm 中的StepsForm.StepForm添加request会导致formRef.current为空

### ISSUE THREAD

**Issue by AccerYou** [ant-design/pro-components#7640]
####飞常验证的问题呀，快来个大佬指点一下

### 🐛 bug 描述

StepsForm.StepForm 中添加request请求后，会导致formRef.current为空

### 📷 复现步骤

复制复现代码，点击 1 按钮，查看控制台输出

### 🏞 期望结果

formRef.current应该是当前的表单值呀~

### 💻 复现代码

import type { ProFormInstance } from "@ant-design/pro-components";
import {
  ProCard,
  ProForm,
  ProFormCheckbox,
  ProFormDatePicker,
  ProFormDateRangePicker,
  ProFormText,
  ProFormTextArea,
  StepsForm
} from "@ant-design/pro-components";
import { message, Button } from "antd";
import { useRef } from "react";

const waitTime = (time: number = 100) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(true);
    }, time);
  });
};

export default () => {
  const formRef = useRef<ProFormInstance>();

  return (
    <ProCard>
      <StepsForm<{
        name: string;
      }>
        stepsProps={{
          direction: "vertical"
        }}
        formRef={formRef}
        onFinish={async () => {
          await waitTime(1000);
          message.success("提交成功");
        }}
        formProps={{
          validateMessages: {
            required: "此项为必填项"
          }
        }}
      >
        <StepsForm.StepForm<{
          name: string;
        }>
          name="base"
          title="创建实验"
          stepProps={{
            description: "这里填入的都是基本信息"
          }}
          request={async () => {
            console.log(formRef.current?.getFieldsValue());
            return new Promise((k,l) => {
              return l({});
            });
          }}
          onFinish={async () => {
            console.log(formRef.current?.getFieldsValue());
            await waitTime(2000);
            return true;
          }}
        >
          <Button
            onClick={() => {
              console.log(formRef.current);
            }}
          >
            点击查看
          </Button>
          <ProFormText
            name="name"
            label="实验名称"
            width="md"
            tooltip="最长为 24 位，用于标定的唯一 id"
            placeholder="请输入名称"
            rules={[{ required: true }]}
          />
          <ProFormDatePicker name="date" label="日期" />
          <ProFormDateRangePicker name="dateTime" label="时间区间" />
          <ProFormTextArea
            name="remark"
            label="备注"
            width="lg"
            placeholder="请输入备注"
          />
        </StepsForm.StepForm>
      </StepsForm>
    </ProCard>
  );
};

### © 版本信息

所有组件为最新版本

### 🚑 其他信息
当移除request时，点击显示正常
![image](https://github.com/ant-design/pro-components/assets/49111598/8bad8403-1e98-4d61-9fc8-c3b6cdeeb3c6)
当添加request后，点击为空
![image](https://github.com/ant-design/pro-components/assets/49111598/bad591da-338b-4384-a6f8-de4f0b10c7bd)

**Comment by zzzzyp** [comment]
same problem

**Comment by zzzzyp** [comment]
same problem

**Comment by AccerYou** [comment]
不要太依赖于pro-components，当组件无法达到效果时，可以考虑通过antdesign来实现特定的功能。
