### ISSUE TITLE
ProTable 搜索问题

### ISSUE THREAD

**Issue by wx9999** [ant-design/pro-components#7641]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

https://github.com/ant-design/pro-components/assets/42061047/a225d9ac-e063-4824-96b5-eff7eadd6123

如视频，点击查询后，过一会儿触发查询，不是即时的。

### © 版本信息

- ProComponents 版本: [2.6.10]
- 浏览器环境 版本 116.0.5845.110
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
看看你的 form  里面 或者  request  里面是不是写了一些高耗时任务。
