### ISSUE TITLE
🐛[BUG]ProTable ColumnSetting Tree 组件 title 过长导致强制换行

### ISSUE THREAD

**Issue by huangkairan** [ant-design/pro-components#7648]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProTable ColumnSetting Tree 组件 title 过长导致展示异常，当 title 长度超过 5 时，会强制换行

![image](https://github.com/ant-design/pro-components/assets/56213366/551d5a30-9fa2-4387-b2b7-44fcfc9534f2)

### 📷 复现步骤
1. 访问链接：

https://procomponents.ant.design/components/table?tab=api&current=1&pageSize=5#valuetype---%E9%80%89%E6%8B%A9%E7%B1%BB

2. Table toolbar 的右上角-点击 `列设置`

### 🏞 期望结果

title 过长时样式优化

### 💻 复现代码

https://procomponents.ant.design/components/table?tab=api&current=1&pageSize=5#valuetype---%E9%80%89%E6%8B%A9%E7%B1%BB

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] 官网demo最新版本
- umi 版本 官网demo
- 浏览器环境 Chrome 116.0.5845.179（正式版本） (arm64)
- 开发环境 [e.g. mac OS]

**Comment by cgf520a** [comment]
本来想着修复一下，让宽度自适应。
但是文档上面写着“标题过长自动收缩”，又没看到收缩的代码，也不知道是怎么个自动收缩法

**Comment by InfernalAzazel** [comment]
> 本来修复一下，让宽度自适应。 但是文档上面写着“标题过长自动收缩”，又没看到收缩的代码，也不知道是怎么个自动收缩法

可以加上提示,  比如 字段 标题过长自动收缩又没看到收缩的代码，变成 标题过长...

**Comment by daiwenyu** [comment]
mark
