### ISSUE TITLE
🐛[BUG]renderFormItem存在多次渲染导致动态获取数据被覆盖

### ISSUE THREAD

**Issue by kiwikaki** [ant-design/pro-components#765]
### 🐛 bug 描述
renderFormItem存在多次渲染导致动态获取数据被覆盖
### 📷 复现步骤

>  1.设置搜索列表选项如下，下拉菜单为远程获取数据通过useState刷新数据。

`{
      title: '操作人类别',
      dataIndex: 'operatorType',
      hideInTable: true,
      renderFormItem: () => {
        return <Select filterOption={false} options={operatorType} />;
      },
      order: 5,
    },`

>  2.页面刷新后renderFormItem执行多次导致最后菜单选项为空。

![1](https://user-images.githubusercontent.com/5789944/96397326-eb797080-11fb-11eb-941d-1c69f3d2e3c2.png)

### 🏞 期望结果
renderFormItem 能够正确渲染数据
### © 版本信息
- ProComponents 版本: [4.2.2]
- umi 版本[ 3.2.14]

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/pro-components/issues/751
