### ISSUE TITLE
🐛[BUG] Token Layout had deprecated

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#7651]
使用 ant design 5.9.0 部分样式token过时。

The token 'colorBgBody' of Layout had deprecated, use 'bodyBg' instead.

The token 'colorBgHeader' of Layout had deprecated, use 'headerBg' instead.

**Comment by zhangxinyong12** [comment]
我还没有发布npm包吗？我的控制台还有这个警告，需要改什么吗？

**Comment by MUCZ** [comment]
same
