### ISSUE TITLE
🐛[ProTable] 搜索表单， collapse不需要时，样式存在问题。

### ISSUE THREAD

**Issue by lk0606** [ant-design/pro-components#7655]
### 🐛 bug 描述
当不需要渲染展开收起时，没有提供showCollapse这样的api控制，是通过collapseRender来处理，此处包裹组件通过space+内联style:{gutter:16}处理的，此处处理不当，有样式bug

### 📷 复现步骤
![image](https://github.com/ant-design/pro-components/assets/43233310/1d56ee77-5ccd-4804-902f-9ad160e0d9ec)
![image](https://github.com/ant-design/pro-components/assets/43233310/820cc30c-22a8-4045-82dc-f5035095dc7f)

### 🏞 期望结果
以下两种处理方式都可以
- 源代码space+内联style:{gutter:16}改为space+内联style:{gutter:0}
- 提供showCollapse控制展开收起

### 💻 复现代码
https://codesandbox.io/s/cha-xun-biao-ge-forked-2l5255?file=/App.tsx

### © 版本信息
版本都可复现

**Comment by varown** [comment]
search={{
        labelWidth: "auto",
        collapseRender:false,
        defaultCollapsed: false
      }}

**Comment by lk0606** [comment]
> search={{ labelWidth: "auto", collapseRender:false, defaultCollapsed: false }}

可以解决问题。以上可以不需要labelWidth: "auto"。

**Comment by chenshuai2144** [comment]
有  collapse 的

![Uploading image.png…]()
