### ISSUE TITLE
🐛[BUG] 最新版本 ProLayou Bug ,官网可以重现。 

### ISSUE THREAD

**Issue by pc110** [ant-design/pro-components#7664]
看视频重现步骤

https://github.com/ant-design/pro-components/assets/29336835/26da22f7-a926-4edb-acca-87c31a2020eb

**Comment by pc110** [comment]
> 没看懂

你试试呗，大佬。 官网很容易重现的。  没看懂是啥意思啊。是不知道bug在那么？

**Comment by chenshuai2144** [comment]
有啥bug, 你描述一下看起来没啥呀

**Comment by pc110** [comment]
> 有啥bug, 你描述一下看起来没啥呀

你看视频的最后一部分。
当前打开的路由，不是收起侧边栏鼠标移入显示的Tips悬浮菜单的时候，再展开收起二级菜单。原来的悬浮菜单有出现的。

1.比如当前打开的路由是欢迎菜单
2.收起侧边栏
3.鼠标移入有二级菜单的菜单项，浮现出二级菜单
4. 展开侧边栏，收缩第三步的二级菜单。原来隐藏的Tips悬浮菜单又显示了

**Comment by chenshuai2144** [comment]
不要重复提，你提了三个了

**Comment by pc110** [comment]
> 不要重复提，你提了三个了

你没解决啊

**Comment by pc110** [comment]
> 不要重复提，你提了三个了

没解决啊，ProLayout 的问题一直改不好，是技术问题么？

**Comment by chenshuai2144** [comment]
因为不重要

**Comment by pc110** [comment]
> 因为不重要，重要的问题我不修也会有 pr 的

这回复一言难尽

**Comment by gaollard** [comment]
> > 因为不重要，重要的问题我不修也会有 pr 的
> 
> 这回复一言难尽，一点开源项目应有的态度都没有

哈哈... ali style
