### ISSUE TITLE
🧐【proTable】 工具栏的列设置能否提供保存能力？？

### ISSUE THREAD

**Issue by gswei123** [ant-design/pro-components#7666]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

目前列设置更改完成后仅支持当前会话，刷新/重新加载后又恢复到最初了。

期望：能否提供保存按钮。将用户操作数据传出来，后面再次加载时初始化再传递进去？

<img width="955" alt="image" src="https://github.com/ant-design/pro-components/assets/144209895/f1cb5681-c00a-48f9-a84c-6dc894446a6b">

**Comment by fengzehao** [comment]
![image](https://github.com/ant-design/pro-components/assets/23555315/bf70a1ee-b16c-448a-855a-b787df92a671)
加上这个配置就可以了，具体可以看官网https://pro-components.antdigital.dev/components/table#columnstatetype
