### ISSUE TITLE
EditableProTable可编辑表格的验证的图标，是否可以自定义？🧐[问题]

### ISSUE THREAD

**Issue by urkknopsm30787** [ant-design/pro-components#7671]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
可编辑表格的验证的图标，是否可以自定义

EditableProTable可编辑表格的验证的图标，是否可以自定义？
### 💻 示例代码
   {
      title: '示例代码',
      dataIndex: '',
      width: 100,
      formItemProps: {
        rules: [
          {
            required: true,
            message: '必填',
            whitespace: false,
          },
        ],
      },
    },

![image](https://github.com/ant-design/pro-components/assets/139649618/519bcbc1-3653-4bbf-9319-e2bfb135471d)
如图所示，这个图标可否自定义？
没在文档中找到，希望可以获得帮助，十分感谢

**Comment by urkknopsm30787** [comment]
目前是用了Form.Item的hasFeedback属性，关闭了这个图标。但是看官方文档，这个属性是支持获得icons的，如图：
![image](https://github.com/ant-design/pro-components/assets/139649618/aff309e8-ee3b-48f7-8139-12cc3c87c842)

但是可编辑表格中Columns列中的formItemProps属性里的hasFeedback却不支持，如图：
![image](https://github.com/ant-design/pro-components/assets/139649618/7abe127e-346e-40b5-ad89-0a4557bc8383)
版本号："antd": "^4.24.12", 
"@ant-design/pro-form": "^1.64.0", 
"@ant-design/pro-table": "^2.61.0",

本人前端新手，如果有提问的不是很好请多多包含
希望可以得到帮助，十分感谢

**Comment by chenshuai2144** [comment]
试用 formItemProps 这个api
