### ISSUE TITLE
当LightFilter、DrawerForm同时使用name相同的ProFormSelect时会有bug🐛[BUG]

### ISSUE THREAD

**Issue by akira0912** [ant-design/pro-components#7674]
问题描述：
首先一个页面上用了组件LightFilter，LightFilter里面有一个ProFormSelect。
查询框旁边有一个按钮，点击之后触发会DrawerForm，DrawerForm里面也有一个ProFormSelect。
当这两个ProFormSelect的name相同时，点击drawer里面ProFormSelect的label时会触发外面的ProFormSelect的下拉框。
![image](https://github.com/ant-design/pro-components/assets/68734384/6515287b-12cb-44de-953e-aa925fb75a6a)
代码：
```JavaScript
import ProCard from '@ant-design/pro-card';
import { DrawerForm, LightFilter } from '@ant-design/pro-form';
import { ProFormSelect } from '@ant-design/pro-form';
import { PageContainer } from '@ant-design/pro-layout';
import { Button, Row, Col } from 'antd';

import React, { useState } from 'react';

const Kanban: React.FC = () => {
  const [open, setOpen] = useState(false);
  return (
    <PageContainer title={false}>
      <ProCard style={{ marginBottom: 20, borderRadius: 5 }}>
        <Row align="middle" gutter={20}>
          <Col>查询条件：</Col>
          <Col>
            <LightFilter<WorkOrderSearchItem> bordered>
              <ProFormSelect
                name="businessType"
                placeholder="业务线"
                label="业务线"
                options={[
                  { label: 'item1', value: '1' },
                  { label: 'item2', value: '2' },
                  { label: 'item2', value: '2' },
                ]}
                showSearch
                mode="multiple"
              />
            </LightFilter>
          </Col>
        </Row>
        <Row align="middle" justify="space-between">
          <Col>
            <Button
              type="primary"
              onClick={() => {
                setOpen(true);
              }}
            >
              新建问题
            </Button>
          </Col>
        </Row>
        <DrawerForm visible={open} onVisibleChange={setOpen}>
          <ProFormSelect
            name="businessType"
            placeholder="业务线"
            label="业务线"
            options={[
              { label: 'item1', value: '1' },
              { label: 'item2', value: '2' },
              { label: 'item2', value: '2' },
            ]}
            showSearch
            mode="multiple"
          />
        </DrawerForm>
      </ProCard>
    </PageContainer>
  );
};

export default Kanban;
```

**Comment by akira0912** [comment]
就是想问问如果不算bug的话，除了用不一样的name还有什么其他的办法吗？

**Comment by akira0912** [comment]
好像是LightFilter的问题？

**Comment by chenshuai2144** [comment]
加个 proFieldKey 也可以

![image](https://github.com/ant-design/pro-components/assets/8186664/6e4502f2-8850-47a9-8271-cdf08e3923fd)

**Comment by NotsayJustdo** [comment]
> 问题描述： 首先一个页面上用了组件LightFilter，LightFilter里面有一个ProFormSelect。 查询框旁边有一个按钮，点击之后触发会DrawerForm，DrawerForm里面也有一个ProFormSelect。 当这两个ProFormSelect的name相同时，点击drawer里面ProFormSelect的label时会触发外面的ProFormSelect的下拉框。 ![image](https://private-user-images.githubusercontent.com/68734384/267837283-6515287b-12cb-44de-953e-aa925fb75a6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzA4MjYsIm5iZiI6MTcwMTA3MDUyNiwicGF0aCI6Ii82ODczNDM4NC8yNjc4MzcyODMtNjUxNTI4N2ItMTJjYi00NGRlLTk1M2UtYWE5MjVmYjc1YTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA3MzUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMjVhMTgxYTczMmViYmFhZmU5OGNlNGE1MmQyMGFkODczNzhmY2NkNzRkODVkNjNhN2FiZGY1ZjdhNDkwMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2hR8TbOY0GnrpcPiryzBDz4JdEzvcK9hP739iK_idFg) 代码：
> 
> ```js
> import ProCard from '@ant-design/pro-card';
> import { DrawerForm, LightFilter } from '@ant-design/pro-form';
> import { ProFormSelect } from '@ant-design/pro-form';
> import { PageContainer } from '@ant-design/pro-layout';
> import { Button, Row, Col } from 'antd';
> 
> import React, { useState } from 'react';
> 
> const Kanban: React.FC = () => {
>   const [open, setOpen] = useState(false);
>   return (
>     <PageContainer title={false}>
>       <ProCard style={{ marginBottom: 20, borderRadius: 5 }}>
>         <Row align="middle" gutter={20}>
>           <Col>查询条件：</Col>
>           <Col>
>             <LightFilter<WorkOrderSearchItem> bordered>
>               <ProFormSelect
>                 name="businessType"
>                 placeholder="业务线"
>                 label="业务线"
>                 options={[
>                   { label: 'item1', value: '1' },
>                   { label: 'item2', value: '2' },
>                   { label: 'item2', value: '2' },
>                 ]}
>                 showSearch
>                 mode="multiple"
>               />
>             </LightFilter>
>           </Col>
>         </Row>
>         <Row align="middle" justify="space-between">
>           <Col>
>             <Button
>               type="primary"
>               onClick={() => {
>                 setOpen(true);
>               }}
>             >
>               新建问题
>             </Button>
>           </Col>
>         </Row>
>         <DrawerForm visible={open} onVisibleChange={setOpen}>
>           <ProFormSelect
>             name="businessType"
>             placeholder="业务线"
>             label="业务线"
>             options={[
>               { label: 'item1', value: '1' },
>               { label: 'item2', value: '2' },
>               { label: 'item2', value: '2' },
>             ]}
>             showSearch
>             mode="multiple"
>           />
>         </DrawerForm>
>       </ProCard>
>     </PageContainer>
>   );
> };
> 
> export default Kanban;
> ```

我也遇到了这个问题，请问一下这个问题你找到解决方案了吗？ @akira0912

**Comment by akira0912** [comment]
> 我也遇到了这个问题，请问一下这个问题你找到解决方案了吗？ @akira0912

没有 proFieldKey我加了也不行 不知道是不是写错了，目前来看只能特殊处理name

**Comment by NotsayJustdo** [comment]
> 加个 proFieldKey 也可以
> 
> ![image](https://private-user-images.githubusercontent.com/8186664/268601159-6e4502f2-8850-47a9-8271-cdf08e3923fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzA4MjYsIm5iZiI6MTcwMTA3MDUyNiwicGF0aCI6Ii84MTg2NjY0LzI2ODYwMTE1OS02ZTQ1MDJmMi04ODUwLTQ3YTktODI3MS1jZGYwOGUzOTIzZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMDczNTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDI0NTFjOWFjODk5MzEwMThiM2Q1MjEzNmU3NzQwMTkzZTg4M2M4YTVlN2JiNzE0YTU1MmViMTQ4ZDA0YjZlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XmRFzz-lCX8Pm7fKmkZ4-dJh2M-UnC3nAoSGXeSBS6w)

@chenshuai2144 请问一下这个proFieldKey加在哪个组件上？我试了下没有效果。当前我使用的pro-form版本是1.46.0

**Comment by NotsayJustdo** [comment]
> > 我也遇到了这个问题，请问一下这个问题你找到解决方案了吗？ @akira0912
> 
> 没有 proFieldKey我加了也不行 不知道是不是写错了，目前来看只能特殊处理name

通过修改不同的name的话，在查询表格或者是提交弹窗的数据时还需要转换一下，这样做组件用起来不是很方便，而且项目中要改很多的地方

**Comment by akira0912** [comment]
> @akira0912 通过修改不同的name的话，在查询表格或者是提交弹窗的数据时还需要转换一下，这样做组件用起来不是很方便，而且项目中要改很多的地方

是的 很麻烦 所以我也一直拖着没改这个bug
