### ISSUE TITLE
👑 [需求] syncToUrl 支持自定义序列化方式

### ISSUE THREAD

**Issue by 662** [ant-design/pro-components#7676]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

ProForm

### 🥰 需求描述

希望 syncToUrl 支持自定义序列化方式。

### ⛰ 功能需求适用场景

在使用 ProTable 对一个枚举字段开启搜索时，当select设置`fieldProps: { mode: 'multiple' }`后，数组序列化出来是：`a=1&a=2`，在 ProTable 的 request 中能正确拿到 `a:['1','2']`。

但当仅有一个option被选中时，由于序列化结果为 a=1，在 ProTable 的 request 中拿到的是 `a:'1'`，提交到服务器之后由于类型异常就报错了。

### 🧐 解决方案

支持序列化到 `a[]=1&a[]=2`

**Comment by chenshuai2144** [comment]
![image](https://github.com/ant-design/pro-components/assets/8186664/d5f46993-cb36-4201-a78f-ecd10e50f53a)


在这里自己处理下，多级的规范 和 你设置的这个规范是不统一的。你可以调用别的库处理下

**Comment by ldc-37** [comment]
ProForm 的 url 参数同步功能是基于 umijs/use-params 这个包提供的 hooks 实现的，其同步参数到 url 的逻辑是这样的：
<img width="573" alt="image" src="https://github.com/ant-design/pro-components/assets/34739463/8bc334d0-7360-4fdd-a439-6ebafebe9211">


目测成本较低的方式还是基于现有 syncToUrl() 的实现，提供一个大概的思路：

```js
    if (type === 'set') {
      Object.entries({...values}).forEach(([k, v]) => {
        if (Array.isArray(v) && !k.endsWith('[]')) { // && 后边的逻辑或许不需要
          values[`${k}[]`] = v
          delete values[k]
        }
      })
    } else {
      Object.entries({...values}).forEach(([k, v]) => {
        if (k.endsWith('[]')) {
          values[k.slice(0, -2)] = Array.isArray(v) ? v : [v]
          delete values[k]
        }
      })
    }
```
