### ISSUE TITLE
🧐[问题]umi环境下，直接在config.ts里配置的routes,如何使得pro-layout不展示面包屑

### ISSUE THREAD

**Issue by JesonSirius** [ant-design/pro-components#768]

**Comment by chenshuai2144** [comment]
现在不支持，面包屑是 PageContainer 负责的，你可以用 RouteContext 获取到当前路由的配置 ，然后控制 PageContainer 的显示隐藏

**Comment by JesonSirius** [comment]
> 现在不支持，面包屑是PageContainer负责的，你可以用RouteContext获取到当前路由的配置，然后控制PageContainer的显示隐藏

3Q
