### ISSUE TITLE
👑 [需求] ProTable column render 能否实现本行更新？

### ISSUE THREAD

**Issue by jsonchou** [ant-design/pro-components#7684]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

 

render?: (dom: React.ReactNode, entity: Entity, index: number, action: ProCoreActionType | undefined, schema: ProSchema<Entity, ExtraProps, ComponentsType, ValueType, ExtraFormItemProps> & {
        isEditable?: boolean;
        type: ComponentsType;
    })

在render函数，修改了一些本行的信息，通过actionRef!.current!.reload!()，刷新整个table，

能否实现类似于setEntity，刷新本行信息？

**Comment by chenshuai2144** [comment]
不能的，因为数据是一起的，datasoucrce  改变总会触发更新的，你可以用 memo 设置一个个单元格
