### ISSUE TITLE
低版本浏览器ProTable组件工具栏flex布局gap样式不支持🐛[BUG]

### ISSUE THREAD

**Issue by zwx-master** [ant-design/pro-components#7685]
### 🐛 bug 描述
低版本浏览器ProTable组件工具栏flex布局不生效

### 📷 复现步骤

为了兼容不支持:where选择器的浏览器，根据ant文档配置降级处理, 代码如下
```
<StyleProvider  hashPriority="high" transformers={[legacyLogicalPropertiesTransformer]}>
  <app>
</StyleProvider>
```

页面效果如下图
![image](https://github.com/ant-design/pro-components/assets/35915057/13c97e08-c915-4484-9920-b099ffe2c9e5)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 umi/max
- 浏览器环境  搜狗浏览器  11.0.0.33862

**Comment by chenshuai2144** [comment]
这东西太难支持了，要不直接让用户换浏览器？

**Comment by chenshuai2144** [comment]
为了支持 xp ，他们应该不会改的
