### ISSUE TITLE
👑 [需求]希望万能的StepsForm新增个点击切换第几步的api

### ISSUE THREAD

**Issue by wangweiq59** [ant-design/pro-components#7686]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
| 参数 | 说明 | 类型 | 默认值 |
| --- | --- | --- | --- |
| current | 当前表单的步骤数，从 `0` 开始 | `number` | 0 |
| onCurrentChange | current 发生改变的事件 | `(current:number)=>void` | - |


用这个搞吧，受控的
