### ISSUE TITLE
🐛[BUG]antd升级到5.9.0版本后ModalForm中的ProFormDatePicker组件选完时间报错clone.weekday is not a function

### ISSUE THREAD

**Issue by wppeng520** [ant-design/pro-components#7688]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by wppeng520** [comment]
"dayjs": 升级到1.11.9没问题了

**Comment by ByYogi** [comment]
相关 issue  关联
https://github.com/ant-design/pro-components/issues/6651#issuecomment-1622899061
