### ISSUE TITLE
产品希望点击重置按钮后不请求request不刷新table,如何实现

### ISSUE THREAD

**Issue by skyc024** [ant-design/pro-components#769]
重置为什么不需要刷新呢？

_Originally posted by @chenshuai2144 in https://github.com/ant-design/pro-components/issue_comments/679016090_

**Comment by chenshuai2144** [comment]
重置参数都变了，不执行 request 怎么拿到数据？

**Comment by skyc024** [comment]
用户只想点击重置，清除查询表单里输入的数据。table不刷新

**Comment by chenshuai2144** [comment]
用 formRef 吧，改了条件不改数据不大合理。

```tsx
formRef.current.resetFields()
```
