### ISSUE TITLE
🧐[问题]请问ProTable有没有api是可以带params参数触发表格的request更新的方法呢。

### ISSUE THREAD

**Issue by HaiYangHuX** [ant-design/pro-components#7690]
目前是自定义了搜索部分，只能是把搜索对象存储在useState中，在扔到表格的params中触发，请问有没有api是可以直接带参数触发更新表格的呢？主要想省去中间存储搜索参数的操作。

**Comment by chenshuai2144** [comment]
react 最好还是 state 的方式来出发，数据流乱了之后很难debug
