### ISSUE TITLE
👑 [需求] 提供pro-layout 卸载ssr-darkreader的方法

### ISSUE THREAD

**Issue by HZZformGD** [ant-design/pro-components#7692]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

`ProLayout`

### 🥰 需求描述

去除darkreader的引入,

### ⛰ 功能需求适用场景

看了一下代码, 貌似这个第三方库是必定引入的(即使配置了暗色模式false), 主要是想减少包体积, 目前这个包的体积是我一个业务代码的1/3,  完全没有这方面的需求, 但是找不到去除这个包的方法
### 🚑 其他信息
`
"@ant-design/pro-components": "2.3.28",
`

![image](https://github.com/ant-design/pro-components/assets/26340739/cf68b0f0-7f82-4967-b89f-30c6fae7a74f)
![image](https://github.com/ant-design/pro-components/assets/26340739/62b9bb0a-f057-46af-8ee0-44de6dbcdc1d)

**Comment by chenshuai2144** [comment]
升级新版本，直接删掉了
