### ISSUE TITLE
🐛[BUG] PageContainer 使用tabList 出现警告 Warning: [antd: Tabs] `Tabs.TabPane` is deprecated. Please use `items` instead. 

### ISSUE THREAD

**Issue by leshalv** [ant-design/pro-components#7696]
PageContainer 组件使用tabList报错 Warning: [antd: Tabs] `Tabs.TabPane` is deprecated. Please use `items` instead. 

看样子这里应该要改一下了。

https://github.com/ant-design/pro-components/blob/dd66db69b3ac03dcbe5e8afe5023b06e96adddac/packages/layout/src/components/PageContainer/index.tsx#L163

**Comment by HenryLee0** [comment]
https://4x.ant.design/components/tabs-cn/#tabs
