### ISSUE TITLE
proTable ellipsis 设置 true 时 tableLayout并没有变成fixed 🐛[BUG]

### ISSUE THREAD

**Issue by skyunBoss** [ant-design/pro-components#770]
### 🐛 bug 描述

table ellipsis 设置 true 时 tableLayout并没有变成fixed

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/29365288/96412229-605ca280-121c-11eb-9af1-d9b4bbcba186.png)

### © 版本信息

- pro-table 2.4.4
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
需要自己的设置的

**Comment by skyunBoss** [comment]
> 需要自己的设置的

那文档是不是容易让人误解？

**Comment by chenshuai2144** [comment]
这是 antd 的吗？写错了的样子
