### ISSUE TITLE
可以提供license文件吗？

### ISSUE THREAD

**Issue by LLQ350181** [ant-design/pro-components#7701]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
MIT 你随便用

**Comment by chenshuai2144** [comment]
![image](https://github.com/ant-design/pro-components/assets/8186664/a86354db-c12e-46e7-86a6-2fade0dccdd5)
