### ISSUE TITLE
文档内a标签链接缺失

### ISSUE THREAD

**Issue by simplast** [ant-design/pro-components#771]
### 🧐 问题描述
https://procomponents.ant.design/components/layout#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80

访问这个文档在页面最底部写到：
          menuDataRender 需要返回一个数组，如果你想拥有更好的性能可以试试使用 props 中的 route 属性，这里有个 demo。

问题：“demo”点击进去以后希望看到demo，但是看到的是一个空白界面

**Comment by git-lt** [comment]
https://procomponents.ant.design/ 这个文档站点404了 2020/10/20

**Comment by juzhiyuan** [comment]
https://procomponents.ant.design/menu 404

**Comment by chenshuai2144** [comment]
fixed
