### ISSUE TITLE
🐛[BUG]ProFormDigital组件，四舍与五入的表现不一致

### ISSUE THREAD

**Issue by KittyFairy-Han** [ant-design/pro-components#7711]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

与ProForm连用的ProFormDigital组件，四舍与五入的表现不一致。四舍发生在input失焦之后，五入发生在input正在输入时。

### 📷 复现步骤

这是一个有问题demo，输入框通过precision=0限制只能输入整数。复现问题很简单，比如：
如果输入1.4，输入框失焦时输入框内的值改为1
如果输入1.5，输入时（未失焦）输入框的值就实时变为了2
https://codesandbox.io/s/ji-ben-antd-5-9-2-forked-2zq7cc?file=/demo.tsx

### 🏞 期望结果

五入也发生在input失焦后

### 💻 复现代码

https://codesandbox.io/s/ji-ben-antd-5-9-2-forked-2zq7cc?file=/demo.tsx

### © 版本信息

- ProComponents 版本: @antd-design/pro-form 2.10.1
- 浏览器环境: chrom 117.0.5938.88（正式版本） (arm64)
- 开发环境: mac OS

**Comment by chenshuai2144** [comment]
改了一下都换成了 blur 之后再变化
