### ISSUE TITLE
BetaSchemaForm formRef🐛[BUG]

### ISSUE THREAD

**Issue by lattemj** [ant-design/pro-components#7713]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

BetaSchemaForm使用layoutType='ModalForm'时，如设置了forceRender: true那么formRef不为undefined，反之则为undefined。

### 🏞 期望结果
forceRender:false时也可以获取到formRef

### © 版本信息

- ProComponents 版本: 2.6.23

**Comment by chenshuai2144** [comment]
form 不加在哪来的 form ´･_･`)   

你自己用 useForm 生成下吧
