### ISSUE TITLE
🐛ProLayout组件，顶部导航模式，通过token设置菜单背景色以后二级浮动菜单显示不正常[BUG]

### ISSUE THREAD

**Issue by wangwufan** [ant-design/pro-components#7715]
### 🐛 bug 描述
ProLayout组件的最新版2.6.23，设置为layout=top后，顶部菜单，我修改了背景色为某蓝色，根菜单样式没问题，但二级浮动菜单背景色仍然是白色，由于我的文字颜色已经是白色，导致没法看，但我试了2.6.16版本是好的，我都会给出CodeSandbox链接；官网的demo也有这个问题(【通过token修改样式】)。
![image](https://github.com/ant-design/pro-components/assets/12657738/16704176-c48f-4054-b43f-36c72b54783b)

### 📷 复现步骤
设置layout='top'，token={{
        bgLayout: "#f0f2f5",
        header: {
          colorBgHeader: "#004FD9",
          colorBgRightActionsItemHover: "rgba(0,0,0,0.06)",
          colorTextRightActionsItem: "rgba(255,255,255,0.65)",
          colorHeaderTitle: "#fff",
          colorBgMenuItemHover: "rgba(0,0,0,0.06)",
          colorBgMenuItemSelected: "rgba(0,0,0,0.15)",
          colorTextMenuSelected: "#fff",
          colorTextMenu: "rgba(255,255,255,0.75)",
          // colorTextMenuSecondary: "rgba(255,255,255,0.65)",
          colorTextMenuActive: "rgba(255,255,255,0.95)"
        }
      }}

### 🏞 期望结果

![image](https://github.com/ant-design/pro-components/assets/12657738/33fa3024-a839-40e1-a37c-babfbf3903d4)

### 💻 复现代码

这是显示有问题的：https://codesandbox.io/s/tong-guo-token-xiu-gai-yang-shi-forked-hm6mt7?file=/package.json

这是低版本但显示正常的：https://codesandbox.io/s/tong-guo-token-xiu-gai-yang-shi-forked-73pkcl?file=/package.json

### © 版本信息

- ProComponents 版本: [2.6.23]
- umi 4
- 谷歌版本 114.0.5735.199
- 开发环境 [vscode]

**Comment by chenshuai2144** [comment]
在配置一下 colorBgMenuElevated ， 做了下拆分。不过的确是有问题，我修复一下，应该不要无脑覆盖
