### ISSUE TITLE
🐛[BUG]PageContainer组件样式多了个最大宽度，pro-components版本2.6.19

### ISSUE THREAD

**Issue by wppeng520** [ant-design/pro-components#7716]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![19e5cc2b444d4159d3926261c895bb7](https://github.com/ant-design/pro-components/assets/70751511/c6945458-d121-470a-8538-7c83f1ab9ac8)

**Comment by chenshuai2144** [comment]
| parameters   | description | type               | default |
| ------------ | ----------- | ------------------ | ------- |
| contentWidth | ContentMode | `Fluid` \| `Fixed` | -       |

配置一下这个 api，现在默认打开了

**Comment by merabtenei** [comment]
The behavior of contentWidth changed. Setting contentWidth="Fixed" does not work when layout != "top" why is this change ?
We used to have contentWidth: Fixed and layout: "mix" and now it's broken.

**Comment by merabtenei** [comment]
Any update ?
