### ISSUE TITLE
🐛[BUG] ProList - Cannot read properties of undefined (reading 'Provider')

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/pro-components#7719]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

使用 ProList 的组件出现错误，我不知道错误的原因。
Components using ProList give errors, I do not know the reason for the error.

### 🏞 期望结果

![image](https://github.com/ant-design/pro-components/assets/6988989/1303899e-51fa-46ac-b789-ba1321e4f0d4)

![image](https://github.com/ant-design/pro-components/assets/6988989/d8510154-7121-4a99-a3ee-0c65ca5e8fa2)

### © 版本信息

- ProComponents 版本: 2.6.23
- umi 版本 : 4.0.81
- 浏览器环境 : Chrome Latest
- 开发环境 [e.g. mac OS] : Windows

**Comment by chenshuai2144** [comment]
清空依赖 重新安装一下
