### ISSUE TITLE
🐛[BUG] 在next中使用pro-components时，ConfigProvider不能正确设置组件内部的语言

### ISSUE THREAD

**Issue by FeiPengDev** [ant-design/pro-components#7721]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

在next中使用pro-components时，ConfigProvider不能正确设置组件内部的语言
![image](https://github.com/ant-design/pro-components/assets/139141092/48610c41-01b6-4270-b571-2659538bba16)

### 📷 复现步骤

在nextjs中添加下面样例即可复现
[pro-table demo](https://procomponents.ant.design/components/table?tab=api#packages-table-src-components-table-tab-api-demo-intl)
![image](https://github.com/ant-design/pro-components/assets/139141092/7c72a851-384a-4ff0-be4a-3222c88952a9)

### 🏞 期望结果

可以在next中通过ConfigProvider正确设置pro-components的语言

### 💻 复现代码

https://codesandbox.io/p/sandbox/antd-pro-next-locale-6c6tdt

### © 版本信息
![image](https://github.com/ant-design/pro-components/assets/139141092/fb6ce132-e855-4fc4-becb-2bd3f9f55acf)
    "react": "18.2.0",
    "next": "13.5.1",
    "react-dom": "18.2.0",
    "typescript": "5.2.2",
    "@ant-design/pro-components": "2.6.21",
    "antd": "5.9.1",
    "dayjs": "1.11.9"

**Comment by FeiPengDev** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [[🐛[BUG] EMPTY TITLE #7720](https://github.com/ant-design/pro-components/issues/7720)][🐛[BUG]在next中使用pro-components时，ConfigProvider不能正确设置组件内部的语言][100%]

**Comment by FeiPengDev** [comment]
https://github.com/ant-design/pro-components/issues/7512
和此问题相同，但是目前还没有更好的解决方案。
放在transpilePackages中可以修复locale的设置，但是会导致next build时占用内存过多。个人觉得这不能算是一个正确的解决方案。

**Comment by chenshuai2144** [comment]
不要重复开issue

**Comment by FeiPengDev** [comment]
> 不要重复开issue

不好意思。想问下我们后续有在next里不配置transpilePackages就能解决ConfigProvider不能正确设置组件内部的语言问题的方法吗？

**Comment by chenshuai2144** [comment]
看样子的 netxjs的 ssr 兼容性问题，这个我组件库不好搞

**Comment by FeiPengDev** [comment]
https://github.com/ant-design/pro-components/issues/7512
和此问题相同。
