### ISSUE TITLE
🐛[BUG]`Tabs.TabPane` is deprecated ProTable 的HeaderMenu里面的tabs怎么还是有这个报错 版本 2.6.23

### ISSUE THREAD

**Issue by echoyl** [ant-design/pro-components#7723]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🏞 期望结果
消除这个报错 看了一个多星期 太碍眼了

### © 版本信息

- ProComponents 版本: 2.6.23
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by HaiYangHuX** [comment]
我的也是，"@ant-design/pro-components": "^2.6.7","antd": "^5.9.1",

**Comment by HaiYangHuX** [comment]
"antd": "^5.9.1","@ant-design/pro-components": "^2.6.7", 一样的报错，好像是更新了某个版本就开始有这个错误，之前没。

**Comment by leshalv** [comment]
https://github.com/ant-design/pro-components/pull/7731
