### ISSUE TITLE
🧐[问题]在 StepsForm 中使用 Modal，编辑场景第一次获取的 formMapRef 为空

### ISSUE THREAD

**Issue by baiwumm** [ant-design/pro-components#7724]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

这是我第一次点击编辑回显打印的 formMapRef ，里面表单为空：
![image](https://github.com/ant-design/pro-components/assets/40554571/c00300fd-7988-4ec6-aead-d0162e54df99)
 我第二次回显，这时候 formMapRef 就能正常回显：
![image](https://github.com/ant-design/pro-components/assets/40554571/144541f1-1c72-47a7-9bd3-6db76c10e262)

请问我如何第一次点击按钮就能正常获取到 ormMapRef，并且能正常回显

### 💻 示例代码

点击按钮回显：
`
editCallback={() => {
	console.log('stepFormMapRef', stepFormMapRef)
	// 表单数据回显处理,密码解密
	record.password = decryptionAesPsd(record.password)
	record.confirmPassword = record.password
	// 编辑场景下需要使用formMapRef循环设置formData
	stepFormMapRef?.current?.forEach((formInstanceRef) => {
	formInstanceRef?.current?.setFieldsValue(record);
	});
	setModalVisibleTrue()
}}
`
StepForm 配置：
`
<StepsForm
current={current}
  formMapRef={stepFormMapRef}
  onFinish={handlerSubmit}
  onCurrentChange={(current) => setCurrent(current)}
  stepsFormRender={(dom, submitter) => {
    return (
      <Modal
        title={formTitle}
        width={800}
        onCancel={() => {
          // 重置表单
          stepFormMapRef?.current?.forEach((formInstanceRef) => {
            formInstanceRef?.current?.resetFields();
          });
          resetCurrent();
          setModalVisibleFalse();
        }}
        open={modalVisible}
        footer={submitter}
        maskClosable={false}
      >
        {dom}
      </Modal>
    );
  }}
>
  {/* 遍历渲染 Step */}
  {
    StepComponents.map((step, index) => {
      return (
        <StepsForm.StepForm
          title={formatMessage({ id: step.title })}
          grid={index !== 2}
          key={step.title}
        >
          {step.component}
        </StepsForm.StepForm>
      )
    })
  }
</StepsForm>
`

### 🚑 其他信息

初次 formMapRef 已经绑定，为何获取不到 Modal 里面的表单

**Comment by lili574** [comment]
可以为`StepsForm.StepForm`指定`formRef`

**Comment by chenshuai2144** [comment]
去 useEffect 里面去拿

**Comment by zj-bling** [comment]
你好，请问解决了吗
