### ISSUE TITLE
action is undefined 🐛[BUG]

### ISSUE THREAD

**Issue by tuphampro** [ant-design/pro-components#773]
@ant-design/pro-table@2.8.0

![Screenshot 2020-10-19 165531](https://user-images.githubusercontent.com/19162524/96430097-f0eeaf00-122b-11eb-88b1-6d701674019c.jpg)

![image](https://user-images.githubusercontent.com/19162524/96430139-ffd56180-122b-11eb-85ac-9499d51f9f45.png)

**Comment by chenshuai2144** [comment]
可能要多次触发了，在刚开始的确可能是个 null
