### ISSUE TITLE
👑 [需求] ProCard组件和 ahooks 的 useClickAway同时使用时，ProCard容器会阻止事件传递的问题

### ISSUE THREAD

**Issue by hanyanxx1** [ant-design/pro-components#7730]
### 🔩 所属模块或组件

ProCard

### 🥰 需求描述

目前项目里，同时用到了ahooks的useClickAway和ProCard组件，希望在ProCard容器内的元素，作为ref赋值给useClickAway的时候，点击到该ref元素之外时，ProCard不要阻止事件冒泡，不然事件传递不到document.body层。

### 🚑 其他信息

![image](https://github.com/ant-design/pro-components/assets/10085134/715e5454-4fed-4225-9364-c8765e689807)
![image](https://github.com/ant-design/pro-components/assets/10085134/7d544722-414f-497d-91bb-01c93ad71562)

**Comment by xliez** [comment]
因为 ProCard 中[阻止了事件冒泡](https://github.com/ant-design/pro-components/commit/5f4bb4849ffd70f3fd44d0a73183dc38df30c87a)，而 useClickAway 是在 document 上监听事件

 @chenshuai2144

**Comment by xliez** [comment]
@chenshuai2144 佬
作为一个 container 来说，阻止冒泡确实会影响一些依赖事件委托的功能，比如用户行为采集、无操作注销等。
不确定当时增加阻止冒泡的原因，如果可以的话，可以去除这个逻辑吗

**Comment by hanyanxx1** [comment]
@xliez @chenshuai2144 已通过其他方式解决了，onClick事件的冒泡确实被阻止了，我换了其他和点击效果类似的事件，比如onMouseDown之类的，把问题解决了。
