### ISSUE TITLE
🐛[BUG] mix模式下, 设置splitMenus: true, 样式错乱的问题

### ISSUE THREAD

**Issue by kddloong** [ant-design/pro-components#7738]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

![image](https://github.com/ant-design/pro-components/assets/47130020/7a38d64b-92d9-4ca7-8f81-1165f6934b62)

正常情况下， 导航栏有上边和左边两个， 偶尔的时候， 在第一次登录进系统的时候， 会只有左边的导航栏，刷新浏览器之后，就正常了
![image](https://github.com/ant-design/pro-components/assets/47130020/290465a7-df22-469a-9d4d-ce0437ce1527)

检查过dom结构 ， 上边的和下边的不同

### © 版本信息

- ProComponents 版本: 2.6.23
- umi 版本 4.0.81
- 浏览器环境 chrome 116
- 开发环境 win10

**Comment by kddloong** [comment]
@chenshuai2144  已将项目  部署到 120.55.169.197:8005, 同时仓库提交到 https://github.com/kddloong/demo2.git

**Comment by kddloong** [comment]
登录进去如果正常， 就清浏览器缓存， 在重新登录， 大概率复现

**Comment by kddloong** [comment]
登录用户名 demotest, 密码 123456

**Comment by chenshuai2144** [comment]
目测是antd的css cache问题，尝试重新安装就能进科举一下
