### ISSUE TITLE
🐛[BUG] form 配置 request 后，request 忘记捕获错误后，导致请求错误丢失

### ISSUE THREAD

**Issue by Yang-yibu** [ant-design/pro-components#7740]
### 🐛 bug 描述

form 表单配置 request 为 `async function req () {}`，req 内部报错并且忘记 catch 错误，导致错误被吃掉，不利于排查错误。
源代码

### 📷 复现步骤

```tsx
const queryFormData = function () {
      a.b = 1; //  模拟报错
}

<ProForm request={async () => queryFormData()}></ProForm>
```

现在，控制台，页面没有任何反应。使用 unhandledrejection 也捕获不到错误。

### 🏞 期望结果

提供一个机制，可以捕获到用户未处理的错误。
如，Provider 可以提供 swr Proveider 配置

```tsx
      <SWRConfig
        value={{
          onError(err, key, config) {
            console.log(err);
          },
        }}
      >
        <ConfigProvider {...antdProviderProp}>
        </ConfigProvider>
      </SWRConfig>
```

**Comment by chenshuai2144** [comment]
`<ProForm request={async () => queryFormData().catch()}></ProForm>`

这样搞下，如果抛出错误会白屏的，你可以在控制台找到错误的堆栈
