### ISSUE TITLE
👑 ProTable 需要新增的两个好用的 api

### ISSUE THREAD

**Issue by sishen654** [ant-design/pro-components#7746]
目前的 protable 高度封装对大部分场景适用，但遇上更多的需求的时候就有心无力了：
1-actionRef 新增一个 getParams 用于获取填写在搜索栏上面的数据
    🚀使用场景：某个按钮需要点击根据搜索栏的查询数据去请求对应接口，目前需要每次点击一下【查询】按钮才能拿到搜索输入的内 
                           容
2-actionRef 新增一个 refresh 用于带着搜索栏输入内容去查询
    🚀使用场景：这个是由前一个问题引发的，本来我想着 reload 重新执行 request，结果搜索参数还是没带过去

**Comment by sishen654** [comment]
补充一下版本："@ant-design/pro-table": "2.72.0"

**Comment by chenshuai2144** [comment]
protable  的 search 是个 form ，是可以用 formRef 来完成你想要的操作。
  
1：  formRef.current?.getFieldFormatValue();
2： formRef.current?.submit();
```

export default () => {
  const formRef = useRef<ProFormInstance>();

  return (
    <ProTable<TableListItem>
      formRef={formRef}
      dateFormatter="string"
      headerTitle="表单赋值"
    />
  );
};
```

**Comment by sishen654** [comment]
> protable 的 search 是个 form ，是可以用 formRef 来完成你想要的操作。
> 
> 1： formRef.current?.getFieldFormatValue(); 2： formRef.current?.submit();
> 
> ```
> 
> export default () => {
>   const formRef = useRef<ProFormInstance>();
> 
>   return (
>     <ProTable<TableListItem>
>       formRef={formRef}
>       dateFormatter="string"
>       headerTitle="表单赋值"
>     />
>   );
> };
> ```

OK感谢，我回头试试👍👍👍
