### ISSUE TITLE
🧐[问题] ProTable 设置 scroll （x: 'max-content'），没有数据时，表头宽度无法设置

### ISSUE THREAD

**Issue by MellowCo** [ant-design/pro-components#7747]
### 🧐 问题描述

ProTable 设置 scroll （x: 'max-content'），没有数据时，表头宽度会平均分配导致变窄

![image](https://github.com/ant-design/pro-components/assets/47939250/0e91ef51-9b00-41b8-a3f3-691a84be6243)

有数据时
![image](https://github.com/ant-design/pro-components/assets/47939250/7c32d6ab-90b1-4347-8de4-3855746faded)

### 💻 示例代码

```ts
const defaultConfig = {
  bordered: true,
  scroll: { y: 'calc(100vh - 400px)', x: 'max-content' },
  pagination: {
    size: 'default',
  },
  rowKey: 'id',
  defaultSize: 'small',
}

<ProTable
    {...defaultConfig}
/>

```

### 🚑 其他信息
在 `columns` 设置 `className` 也只有在有数据时，才会生效

```ts
const columns = [
  {
    title: '测试',
    dataIndex: 'test',
    copyable: true,
	className: 'min-w-10'
  },
]
```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！感谢提供问题的详细描述和代码示例。根据你的描述和提供的截图，你在 ProTable 中将 scroll 的 x 设置为 'max-content' 时，在没有数据的情况下，表头宽度无法设置正确。

从你提供的截图可以看出，表头的宽度是平均分配的，这是因为没有数据时，ProTable 无法通过数据来自适应调整表头的宽度。

为了解决这个问题，你可以尝试以下几种方法：

#### 方法一：设置默认表头宽度

你可以给每列设置一个默认的宽度，当没有数据时，表头就会按照这个默认宽度来展示。

```ts
const columns = [
  {
    title: '测试',
    dataIndex: 'test',
    copyable: true,
    width: 200, // 设置默认宽度
  },
];
```

这样，当没有数据时，表头的宽度会按照设置的默认宽度展示。

#### 方法二：使用列的fixed属性

你可以使用列的 `fixed` 属性来固定表头的宽度，不受内容影响。你可以为需要固定宽度的列设置 `fixed: 'left'` 或 `fixed: 'right'`。

```ts
const columns = [
  {
    title: '测试',
    dataIndex: 'test',
    copyable: true,
    fixed: 'left', // 固定左侧
  },
];
```

或者

```ts
const columns = [
  {
    title: '测试',
    dataIndex: 'test',
    copyable: true,
    fixed: 'right', // 固定右侧
  },
];
```

这样，表头的宽度将不受内容影响，固定在左侧或右侧。

#### 方法三：使用 CSS 自定义宽度

你可以使用 CSS 来自定义表头的宽度，在表头容器上设置一个固定的宽度。

```css
ant-table-thead {
  width: 800px; // 自定义宽度
}
```

通过上述方法之一，你可以解决 ProTable 设置 scroll 时没有数据导致表头宽度无法设置的问题。

如果问题还未得到解决，请提供一个在线的重现实例，以便我们更好地帮助你解决问题。

**Comment by feiren200** [comment]
这是固定表头引起的
