### ISSUE TITLE
🧐[问题] LightFilter 中 ProFormSelect 不支持虚拟滚动

### ISSUE THREAD

**Issue by focus0802** [ant-design/pro-components#7748]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

ProFormSelect 在 LightQuery 中时虚拟滚动无效，同样的代码如果不在 LightQuery 中，单独使用 ProFormSelect 则可以正常使用虚拟滚动。

### 💻 示例代码

```
// 无法实现虚拟滚动
    <LightFilter>
    <ProFormSelect
                label="学员"
                fieldProps={{
                  options: students.map(student => {
                    return {
                      label: (
                        <div className="avatar-item">
                          <Avatar size="small" src={getAvatar(student.avatar, 40)}/>
                          <span>{student.name}</span>
                        </div>
                      ),
                      value: student.id
                    }
                  })
                }}
              >
              </ProFormSelect>
            </LightFilter>


// 可以实现虚拟滚动
              <ProFormSelect
                label="学员"
                fieldProps={{
                  options: students.map(student => {
                    return {
                      label: (
                        <div className="avatar-item">
                          <Avatar size="small" src={getAvatar(student.avatar, 40)}/>
                          <span>{student.name}</span>
                        </div>
                      ),
                      value: student.id
                    }
                  })
                }}
              >
              </ProFormSelect>
```

### 🚑 其他信息

&lt;!--
如截图等其他信息可以贴在这里
--&gt;

**Comment by chenshuai2144** [comment]
![image](https://github.com/ant-design/pro-components/assets/8186664/3758865d-bafa-4e40-aaa3-fe29123f3b21)


试着设置一下这个，我试了下默认的 select 是可以搞定的

**Comment by focus0802** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/271603864-3758865d-bafa-4e40-aaa3-fe29123f3b21.png)
> 
> 试着设置一下这个，我试了下默认的 ProFormSelect 是可以搞定的

这个设置无效，我试了一下，是在 LightFilter 中 ProFormSelect 的虚拟滚动就失效了，如果不在 LightFilter 中就正常

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hello @focus0802. Thank you for providing the additional information. 

Unfortunately, as a text-based AI assistant, I don't have the capability to access external links like Codesandbox or GitHub. However, I can still try to help you with some suggestions.

Based on your description, it seems that the issue might be related to the integration of ProFormSelect in LightFilter. One possible solution you can try is to wrap the ProFormSelect component with a virtualized container such as react-window or react-virtualized.

Here's an example of how you can achieve this using react-window:

```jsx
import { FixedSizeList } from 'react-window';
import { ProFormSelect } from 'your-pro-components-library';

const StudentsList = ({ students }) => {
  return (
    <FixedSizeList
      height={200}
      width={300}
      itemSize={50}
      itemCount={students.length}
    >
      {({ index, style }) => (
        <div style={style}>
          <ProFormSelect
            label="学员"
            fieldProps={{
              options: [
                {
                  label: (
                    <div className="avatar-item">
                      <Avatar size="small" src={getAvatar(students[index].avatar, 40)} />
                      <span>{students[index].name}</span>
                    </div>
                  ),
                  value: students[index].id,
                },
              ],
            }}
          />
        </div>
      )}
    </FixedSizeList>
  );
};

const LightFilterWithVirtualizedSelect = ({ students }) => {
  return (
    <LightFilter>
      <StudentsList students={students} />
    </LightFilter>
  );
};
```

In this example, we wrap the ProFormSelect component in a custom StudentsList component, which is a virtualized list rendered by react-window. This allows for efficient rendering of a large number of items while enabling virtual scrolling.

Please note that you would need to install and import the relevant dependencies (`react-window`, `react-virtualized`, or other virtualization libraries) as necessary.

Additionally, make sure to handle any necessary state management, event handling, and styling according to your specific application requirements.

I hope this helps to point you in the right direction. If you can provide a minimal GitHub repository or more specific details, I can offer more targeted assistance.
