### ISSUE TITLE
🐛[BUG] Form的只读模式，通过state切换不起作用

### ISSUE THREAD

**Issue by csywweb** [ant-design/pro-components#7749]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

通过state控制readonly属性，从true变成false的时候不生效

### 🏞 期望结果

可以用state在外部控制表单的readonly

### 💻 复现代码

```
const [isDetail, setIsDetail] = useState(props.isDetail);
<ProForm
        onFinish={onFinish}
        grid
        initialValues={initData}
        layout="horizontal"
        labelCol={{ flex: '110px' }}
        form={form}
        readonly={isDetail}
```

### © 版本信息

- ProComponents 版本: 2.3.57
- umi 4
- 浏览器环境 Chrome
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好 @csywweb，

感谢你提供的代码片段。根据你的描述，你想通过 `state` 来控制 `ProForm` 组件的 `readonly` 属性，但是在你将 `isDetail` 从 `true` 切换为 `false` 时，并没有生效。我将提供一个解决方案来修复这个问题。

首先，根据你提供的代码片段，我注意到你使用了 `ProForm` 组件，并且你想要控制它的 `readonly` 属性。然而，根据 ProForm 的文档（https://procomponents.ant.design/components/form#proform），`ProForm` 组件并没有名为 `readonly` 的属性。

相反，你应该使用 `disabled` 属性来控制表单是否可编辑。当你想要让表单只读时，将 `disabled` 属性设置为 `true`；当你想要启用表单编辑时，将 `disabled` 属性设置为 `false`。

以下是根据你的代码片段修改后的示例：

```jsx
const [isDetail, setIsDetail] = useState(props.isDetail);

<ProForm
  onFinish={onFinish}
  grid
  initialValues={initData}
  layout="horizontal"
  labelCol={{ flex: '110px' }}
  form={form}
  disabled={isDetail} // 使用 disabled 属性来控制表单是否可编辑
>
  {/* 表单项... */}
</ProForm>
```

通过这种方式，你可以使用 `isDetail` 状态来控制表单的只读模式。当 `isDetail` 为 `true` 时，表单将变为只读；当 `isDetail` 为 `false` 时，表单将可编辑。

希望这个解决方案对你有帮助！如果你有任何进一步的问题，请随时提问。

**Comment by csywweb** [comment]
好的谢谢
