### ISSUE TITLE
🐛[BUG] V5 umi request errorHandle not handle on any page.

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/pro-components#775]
### 🐛 bug 描述
Hi there, errorHandle (in app.tsx) is not triggered when any request fails on other pages.
Problem is, the error handle is only triggered if a request in app.tsx fails. 
**How can I define the error handle as a generic handle for umi requests on other pages.**
```
const errorHandler = (error: ResponseError) => {
  const { response } = error;
  if (response && response.status) {
    const errorText = codeMessage[response.status] || response.statusText;
    const { status, url } = response;

    notification.error({
      message: `请求错误 ${status}: ${url}`,
      description: errorText,
    });
  }

  if (!response) {
    notification.error({
      description: '您的网络发生异常，无法连接服务器',
      message: '网络异常',
    });
  }
  throw error;
};
```

### © 版本信息

- ProComponents 版本: V5
- umi 版本
- 浏览器环境
- 开发环境 Windows, Chrome

**Comment by chenshuai2144** [comment]
look here https://github.com/umijs/umi-request

you can use Middleware

**Comment by xXAvoraXx** [comment]
> look here https://github.com/umijs/umi-request
> 
> you can use Middleware

In the article, how to use middleware has briefly mentioned it, it does not mention how to catch the error.

**Comment by chenshuai2144** [comment]
you can submit a issue in umi-request
