### ISSUE TITLE
👑 [需求]DragSortTable的onDragSortEnd能否新增变化索引参数？

### ISSUE THREAD

**Issue by uliian** [ant-design/pro-components#7751]
### 🔩 所属模块或组件

DragSortTable

### 🥰 需求描述

onDragSortEnd能否新增变化索引参数，我看在Dnd的onDragEnd世间里，提供了active, over两个参数，作为原索引和变更后的索引指向。而在DragSortTable的onDragSortEnd里，只提供了变更后的数组作为参数。能否把这两个索引参数也带过来，以便后端进行处理？

### ⛰ 功能需求适用场景

后端在获取列表变更索引后，能以极低的代价进行排序逻辑的处理。我的后端排序字段采用sortId，我只需要根据记录标识（如记录ID）和新索引计算出新的sortId即可处理。现在仅仅给了新的排序后的数组，反而变得不好处理

### 🧐 解决方案

目前用下来，感觉antd的Tree组件的拖拽做得最好，能够很灵活地控制拖拽范围，给的索引也是slot索引，处理起来最为简单。建议参考它的做法。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 👑 您好！

我是 GitHub 的 issue 助理，专门处理与 React 前端问题相关的事宜。非常抱歉，根据您提供的描述，这似乎不是一个前端问题。GitHub issue 助理只能处理与 React 前端相关的问题。

如果您有任何与 React 相关的前端问题，我将非常乐意帮助您解决。如果您需要其他帮助，请告诉我，我会尽力提供合适的建议或拒绝。

谢谢您的理解！
