### ISSUE TITLE
🐛[BUG] ProForm的onValuesChange在选择框clear时不能获取变化字段

### ISSUE THREAD

**Issue by thding** [ant-design/pro-components#7753]
### 🐛 bug 描述
ProForm的onValuesChange在选择框clear时不能获取变化字段

### 📷 复现步骤

https://codesandbox.io/s/biao-dan-lian-dong-forked-k5npcn?file=/App.tsx
打开console，选择框X掉的时候观察输出，发现onValuesChange 第一个参数输出的是{} 拿不到具体的变化字段

### 🏞 期望结果
期望能看到具体的变化字段，比如如文本框，手动全部删除之后onValuesChange第一个参数{ [key]: '' }

### 💻 复现代码
https://codesandbox.io/s/biao-dan-lian-dong-forked-k5npcn?file=/App.tsx

### © 版本信息

- ProComponents 版本: "@ant-design/pro-components": "^2.6.22"
- umi 版本:"@umijs/max": "^4.0.78",
- 浏览器环境:116.0.5845.187（正式版本） (arm64)
- 开发环境 [e.g. mac OS]: mac OS 13.6

**Comment by chenshuai2144** [comment]
去找antd的提一下问题吧。

另外我觉得这种需求在 onchange里面比较合理
