### ISSUE TITLE
👑 [Bug][ProTable]使用的几点小建议

### ISSUE THREAD

**Issue by xiexingen** [ant-design/pro-components#776]
### 🥰 需求描述

1.请求的时候能否支持默认页码、搜索条件
用途:记录用户搜索条件、页面 当浏览器刷新的时候能直接使用刷新前的条件、页码、排序条件 来重新请求
2.toolBarRender中放置Imput.Search 怎么让这个控件的值跟搜索表单关联上
如demo中的:https://procomponents.ant.design/components/table#%E5%8F%97%E6%8E%A7%E7%9A%84%E5%88%97%E6%98%BE%E7%A4%BA%E9%9A%90%E8%97%8F
![image](https://user-images.githubusercontent.com/7939085/96527178-1a521e00-12b2-11eb-97e1-2a307c004529.png)
3.能否增加一个配置项 resizeable来配置拖拽调节列宽的功能
antd中的demo已经有了，如果能直接集成到pro-table来会更好，通过resizeable来直接控制
4.light搜索模式下，输入框操作有点别扭
![image](https://user-images.githubusercontent.com/7939085/96527460-abc19000-12b2-11eb-9c1a-c35296f75c19.png)
是否可以提供一个扩展，可以自定义成内联形式的Form来替换掉light搜索这整块

**Comment by chenshuai2144** [comment]
> 1.请求的时候能否支持默认页码、搜索条件

支持的，可以设置受控的 page 和  pageSzie

> toolBarRender中放置Imput.Search 怎么让这个控件的值跟搜索表单关联上

ProTable 有个 params 参数，用 state 存一下。

>  3.能否增加一个配置项 resizeable来配置拖拽调节列宽的功能

这个功能不是很常见，不会支持的

> 4.light搜索模式下，输入框操作有点别扭

by design,  你可以列举一下为什么

**Comment by xiexingen** [comment]
4.light搜索模式下，能否提供一个扩展 比如，用户可以自行使用内联的Form替换掉light搜索模式的整块内容

**Comment by xiexingen** [comment]
感觉还有一种情况，可以出个demo
表格的搜索表单不使用columns中的配置，而是采用完全自定义表单，然后通过ref形式吧自定义的form实例传递给ProTable

**Comment by chenshuai2144** [comment]
@xiexingen 这种情况就随意自定义了，不需要用protable 了
