### ISSUE TITLE
🧐[问题]protable上面的搜索框..如何控制某一列的长度，目前都是平均分的

### ISSUE THREAD

**Issue by fleetscythe** [ant-design/pro-components#777]
### 🧐 问题描述

protable 上面的搜索框..如何控制某一列的长度，目前都是平均分的

### 💻 示例代码

search={{
              defaultCollapsed: false,
              span:  8,
              collapseRender: () => false,
            }}

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/10510634/96536893-9a36b300-12c7-11eb-87f1-983bfb445e7a.png)

**Comment by chenshuai2144** [comment]
暂时只支持平均分

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/issues/203

**Comment by lizhongyue248** [comment]
这个是否打算支持呢
