### ISSUE TITLE
🧐[问题] ProTable 中 search区域 下拉选择框可以通过远程获取的数据渲染出来选项吗

### ISSUE THREAD

**Issue by ChenWeihua123** [ant-design/pro-components#778]

**Comment by chenshuai2144** [comment]
可以配置 request 来请求数据

```tsx
title:"状态",
request:() => [
              { label: '全部', value: 'all' },
              { label: '未解决', value: 'open' },
              { label: '已解决', value: 'closed' },
              { label: '解决中', value: 'processing' },
            ]
```

**Comment by lizhongyue248** [comment]
![image](https://user-images.githubusercontent.com/29678316/96576614-0257ba00-1305-11eb-93cc-aa2f1b4c74af.png)

他说的应该是这里的下拉选择框的数据怎么远程获取吧，同问。

在文档 https://procomponents.ant.design/components/table#columns-列定义 里面并没有 request 参数

**Comment by Hnnphone** [comment]
这个 request 每次点击重置或者提交 都要刷新请求一下，怎么解
