### ISSUE TITLE
🐛[BUG]使用pnpm 8.9.2后，整个项目必需引入@ant-design/pro-components和dayjs。

### ISSUE THREAD

**Issue by oxygen-xx** [ant-design/pro-components#7787]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

升级pnpm 到8.9.2后，整个项目必需引入@ant-design/pro-components和dayjs。

### © 版本信息
     "antd": "5.10.1",
    "@ant-design/pro-card": "^2.5.20",
    "@ant-design/pro-descriptions": "2.5.15",
    "@ant-design/pro-form": "2.21.2",
    "@ant-design/pro-layout": "7.17.8",
    "@ant-design/pro-table": "3.12.14",

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本  4.0.86
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]  macos 14
- node 18.18.2

**Comment by chenshuai2144** [comment]
引入一下吧，这样靠谱一些。

这些不要用了。推荐从` @ant-design/pro-components`里引出
```

"@ant-design/pro-card": "^2.5.20",
"@ant-design/pro-descriptions": "2.5.15",
"@ant-design/pro-form": "2.21.2",
"@ant-design/pro-layout": "7.17.8",
"@ant-design/pro-table": "3.12.14",
```
