### ISSUE TITLE
👑 [需求]ProCard不支持antd/Card原有的参数吗？

### ISSUE THREAD

**Issue by wood3n** [ant-design/pro-components#779]
### 🧐 问题描述

`antd/Card`原生的`actions`参数不支持吗？

### 💻 示例代码

```jsx
  <Card
    style={{ width: 300 }}
    cover={
      <img
        alt="example"
        src="https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png"
      />
    }
    actions={[
      <SettingOutlined key="setting" />,
      <EditOutlined key="edit" />,
      <EllipsisOutlined key="ellipsis" />,
    ]}
  >
    <Meta
      avatar={<Avatar src="https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png" />}
      title="Card title"
      description="This is the description"
    />
</Card>
```

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/31716713/96555704-ad0eaf00-12ea-11eb-885b-62a2291e8484.png)

**Comment by rdmclin2** [comment]
@wood3n  目前是不支持的，如果有需要可以添加。

**Comment by wood3n** [comment]
> @wood3n 目前是不支持的，如果有需要可以添加。

好像也不是那么需要，我在里面又包了一个`Card`，🤣，主要我当前这个`Card`外层不全是用的`ProCard`来做的布局，还结合了`Row`，`Col`栅格，所以不是太依赖`ProCard`的布局包裹

![image](https://user-images.githubusercontent.com/31716713/96577890-ec4af900-1306-11eb-8afc-9387ad9d40bd.png)

**Comment by rdmclin2** [comment]
@wood3n 😄，我有空也添加一下这个API。
