### ISSUE TITLE
👑 [需求] 暴露 ProFormList 容器自定义渲染函数

### ISSUE THREAD

**Issue by dominicleo** [ant-design/pro-components#7796]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

`BetaSchemaForm`

`ProFormList`

### 🥰 需求描述

暴露 valueType=formList 容器自定义渲染

### ⛰ 功能需求适用场景

用户根据自己的需求实现 ProFormList dnd

**Comment by chenshuai2144** [comment]
这个时候直接自定义 valueType 就好了，官方提供的就是一个标准的但是不灵活的方案
