### ISSUE TITLE
🐛[BUG] EditableProTable 中的 valueType checkbox 不生效

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/pro-components#7797]
```jsx
{
    title: '限时玩法',
    dataIndex: 'timeLimitedPlay',
    key: 'timeLimitedPlay',
    valueType: 'checkbox',
  }
```
<img width="872" alt="image" src="https://github.com/ant-design/pro-components/assets/124666577/17e264c7-af44-4f0f-af13-dad3c8ce076c">

**Comment by kungege** [comment]
@vaynevayne  数据字典没有配置

**Comment by kungege** [comment]
> 单独的 checkbox 怎么会要配置? 另外 ` valueEnum: { true: '未解决', closed: '已解决', },` 效果不对啊 <img alt="image" width="748" src="https://user-images.githubusercontent.com/124666577/276540253-7c3031ad-cdc7-4d70-8a8b-491389c01ed8.png">

复选框不就是这样吗？不太明白你的意思

**Comment by sunsmeil** [comment]
> > 单独的 checkbox 怎么会要配置? 另外 ` valueEnum: { true: '未解决', closed: '已解决', },` 效果不对啊 <img alt="image" width="748" src="https://user-images.githubusercontent.com/124666577/276540253-7c3031ad-cdc7-4d70-8a8b-491389c01ed8.png">
> 
> 复选框不就是这样吗？不太明白你的意思

可以 valueEnum: { true: ' ' }, 这样配置。 选中的就是数组， 没有选中的是空数组。 然后做数据转换就可以

**Comment by vaynevayne** [comment]
有问题 和解决问题 这是两个问题,你不能说问题能解决, 就不去解决真正的问题

**Comment by chenshuai2144** [comment]
renderTexr 自己转化下，转成别的数据结构，拿 boolean 当 key 也太有想象力
