### ISSUE TITLE
👑 [需求]layout 菜单 选中菜单hover后的字体颜色的没有可配置的token

### ISSUE THREAD

**Issue by echoyl** [ant-design/pro-components#7806]
示例如官网的这个demo
https://procomponents.ant.design/components/layout?tab=api#packages-layout-src-components-layout-tab-api-demo-designmenucss

菜单设置了selected的 text color hover后颜色消失

如果设置 colorTextMenuItemHover或者colorTextMenuActive hover未选中的菜单就会出现蓝色（期望是不要出现蓝色）

还有SettingDrawer的主题色 设置后 能不能左侧菜单也同时设置了这个主题色 就和上一个版本antdesign pro5 https://preview.pro.ant.design
的版本一样？

**Comment by chenshuai2144** [comment]
`colorTextMenuItemHover`或者`colorTextMenuActive` 可以考虑调整这两个 Token 的值，或者确定是否有其他样式覆盖了这个设置，需要进一步检查相关代码。
