### ISSUE TITLE
👑 [需求] LightFilter 筛选能不能可以由自己的控件props传入控制light

### ISSUE THREAD

**Issue by dabaoshu** [ant-design/pro-components#7807]
### 🔩 所属模块或组件
   proForm LightFilter

### 🥰 需求描述
筛选能不能可以由自己的控件props传入控制light
我看源码是写死light:true 希望可以自己传入控制 默认为true

 
### 🧐 解决方案

![1698203414170](https://github.com/ant-design/pro-components/assets/56434860/36a26ff2-9722-48e4-b12b-9c8da226ca49)

改为
   proFieldProps: {
                  light: true,
                  ...child.props.proFieldProps,
                  label: child.props.label,
                  bordered,
                }

**Comment by chenshuai2144** [comment]
根据你的需求描述，你希望能够通过自定义的控件来传入控制 `light` 属性的值，默认为 `true`。

根据你提供的代码片段，你可以通过修改 `proFieldProps` 的方式来实现这个需求。将 `proFieldProps` 中的 `light` 属性设置为 `true`，并且通过 `child.props.proFieldProps` 将原始的 `proFieldProps` 属性传递进去，以保持其它属性的设置不变。修改后的代码如下所示：

```javascript
proFieldProps: {
  light: true,
  ...child.props.proFieldProps,
  label: child.props.label,
  bordered,
}
```

这样就可以在自定义组件中通过 `proFieldProps` 的方式传入 `light` 属性的值了。

希望对你有帮助！如果还有其他问题，请随时提问。
