### ISSUE TITLE
👑 [需求] ProLayout menu 的 type 属性下的 group，希望能还原成 @2.6.23 版本的交互

### ISSUE THREAD

**Issue by CurlyJun1123** [ant-design/pro-components#7811]
### 🔩 所属模块或组件

ProLayout - menu - type - group

### 🥰 需求描述

在状态栏收起来的时候不希望把子菜单的所有按钮展示出来，使得要一一设置 icon，增加了工作量，希望可以还原或提供一个属性切换。

当前的效果：
![微信截图_20231025170514](https://github.com/ant-design/pro-components/assets/37525476/0befd419-2060-4136-a971-5a424e9b344f)

想要的效果：
![微信截图_20231025170806](https://github.com/ant-design/pro-components/assets/37525476/307a7788-e53c-4cf4-9a8d-c2fe22008cc6)

### ⛰ 功能需求适用场景

当 Collapse 折叠来的时候

### 🧐 解决方案

还原配置或新增参数提供更换

**Comment by chenshuai2144** [comment]
根据你的需求，你希望在ProLayout的menu的type属性下的group中实现子菜单在状态栏收起时不展示所有按钮的效果，而是只显示一个子菜单按钮。目前来说，ProLayout并没有提供直接实现这个效果的配置或参数。你有两个解决方案：
1. 还原到@2.6.23版本的ProLayout，因为你提供的效果截图正是该版本的效果；
2. 自行修改ProLayout的源码，新增一个参数或配置来实现你想要的效果。具体修改的方式取决于你对前端开发的熟悉程度。

另外，Ant Design建议支持最近2个版本的现代浏览器，如果你需要兼容旧版浏览器，你可以根据实际需求进行降级处理。
