### ISSUE TITLE
🐛[Protable] 存在多个protable切换时，column request请求没有准确调用

### ISSUE THREAD

**Issue by lk0606** [ant-design/pro-components#7814]
### 🐛 bug 描述
存在多个protable切换时，比如几个菜单的页面都是表格页，请求字段也类似，但是返回结果不同，此时筛选项下拉数据有缓存，没有正确每次请求接口

### 📷 复现步骤
1. 进入首页，出现第一张图
2. 点击切换tab2，先展示tab1的缓存数据，在请求到真实数据
3. 切换到tab1，展示的是tab2的数据
![image](https://github.com/ant-design/pro-components/assets/43233310/007dfbab-3d9c-4be3-8d18-f27ec2d3a8d7)
![image](https://github.com/ant-design/pro-components/assets/43233310/936fa15c-0914-47a7-ad88-5a2934a400e9)
![image](https://github.com/ant-design/pro-components/assets/43233310/f66ad5b6-d4c8-499d-94be-251426f179a6)

### 🏞 期望结果
每次切换，都能得到正确的结果。可以先从暂无数据开始加载。不应存在有缓存就不请求的效果

### 💻 复现代码
https://codesandbox.io/s/cha-xun-biao-ge-forked-66xhkg?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
无

**Comment by chenshuai2144** [comment]
这个问题涉及到在多个Protable切换时，每次切换都需要调用接口来获取正确的数据，而不是使用缓存的数据。根据提供的复现代码，问题出现在使用Ant Design Pro组件库中的ProTable组件。

在代码中，可以看到ProTable组件有一个`request`属性，用于定义获取数据的接口请求。当切换tab时，组件会重新渲染，但是由于请求的数据字段类似且缓存了上一次的数据，导致每次切换时请求到的数据不正确。

解决这个问题的方法是，在切换tab时，通过设置一个`key`属性给ProTable组件，当`key`属性发生变化时，会重新创建一个新的ProTable组件实例，从而确保每次都会请求正确的数据。具体的做法是将`key`属性设置为当前tab的唯一标识，比如tab的索引或者tab的名称。

```tsx
<ProTable
  key={currentTab} // 设置key属性，确保每次切换都会创建一个新的ProTable组件实例
  // 其他属性...
/>
```

这样就可以确保每次切换tab时都会重新请求接口获取正确的数据了。希望能帮到你！如果还有其他问题，请随时提问。
