### ISSUE TITLE
🧐[问题]Can't resolve 'antd/lib/theme/style'

### ISSUE THREAD

**Issue by ZhaoYuLing** [ant-design/pro-components#7816]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

我在craco创建的项目中使用 antd@4.24.12 和@ant-design/pro-components@2.6.32启动项目后会报错“Can't resolve 'antd/lib/theme in /node_modules/@ant-design/pro-provider/es/useStyle”
然后我尝试配置 alias:{'antd/lib/theme': path.resolve(__dirname, 'empty.js')}，但是出现了新的问题：“Can't resolve 'antd/lib/theme/style' in /node_modules/@ant-design/pro-provider/es/useStyle”
我没有找到antd/lib/theme/style在哪里被引用了，并且尝试添加 alias：'antd/lib/theme/style': './node_modules/antd/dist/antd.css'，没有效果
我的 craco版本@craco/craco@6.4.5

### 🚑 其他信息

<img width="1064" alt="image" src="https://github.com/ant-design/pro-components/assets/19954870/48a6b901-5f6f-4cc0-805f-61c89d27b0a2">

**Comment by ZhaoYuLing** [comment]
antd@4.24.1
@ant-design/pro-components@2.6.32
@craco/craco@6.4.5
craco-antd@1.19.0
craco-less@1.20.0

**Comment by ZhaoYuLing** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [[🐛[BUG] 引入样式报错 Can't resolve 'antd/es/theme/style' #6087](https://github.com/ant-design/pro-components/issues/6087)][🐛[BUG] 引入样式报错 Can't resolve 'antd/es/theme/style'][77%]

我尝试设置了 alias但没有解决问题

**Comment by chenshuai2144** [comment]
升级一下antd@5 就可以了，如果是antd@4 就忽略这个报错
