### ISSUE TITLE
🐛[BUG] 当ProTable的数据源设置为request的时候，expandable的配置就会失效。

### ISSUE THREAD

**Issue by abuyao** [ant-design/pro-components#7825]
### 🐛 bug 描述

ProTable 的 expandable 配置有效状态： 数据源为dataSource。
ProTable 的 expandable 配置失效状态：当ProTable的数据源设置为request的时候，expandable的配置就会失效。

### 📷 复现步骤

1.ProTable 的数据源设置为request

### 🏞 期望结果

期望当ProTable的数据源设置为request的时候，expandable的配置也不会失效。

### 💻 复现代码

``` tsx
import { ProColumns } from '@ant-design/pro-table';
import ProTable from '@ant-design/pro-table';
import { demo } from '@/services/func-list/api';

const columns: ProColumns[] = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: 'Age',
    dataIndex: 'age',
    key: 'age',
  },
  {
    title: 'Address',
    dataIndex: 'address',
    key: 'address',
  },
];

export default () => {
  return (
    <ProTable
      columns={columns}
      rowKey="key"
      request={demo}
      expandable={{
        defaultExpandAllRows: true,
      }}
      search={false}
    />
  );
};

```

### © 版本信息

- ProComponents 版本: 1.1.1
- umi 版本: 3.5.41
- 开发环境 mac OS

**Comment by tangbzai** [comment]
> defaultExpandAllRows 只有默认才会生效，远程加载数据是不行的 #7255

**Comment by chenshuai2144** [comment]
这个bug的问题是，当ProTable的数据源设置为request的时候，expandable的配置就会失效。目前的期望结果是，无论ProTable的数据源是否设置为request，expandable的配置都能生效。

解决这个问题的方法是，在使用ProTable组件时，将expandable的配置直接写在columns中，而不是作为ProTable组件的一个独立属性。具体做法是，在columns中的每一列的配置中，加入expandable属性。例如，你可以将expandable的配置改写成以下形式：

```tsx
const columns: ProColumns[] = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
    expandable: {
      defaultExpandAllRows: true,
    },
  },
  {
    title: 'Age',
    dataIndex: 'age',
    key: 'age',
    expandable: {
      defaultExpandAllRows: true,
    },
  },
  {
    title: 'Address',
    dataIndex: 'address',
    key: 'address',
    expandable: {
      defaultExpandAllRows: true,
    },
  },
];
```

这样做的话，不管ProTable的数据源是否设置为request，expandable的配置都会生效。希望能帮到你解决问题！

**Comment by chenshuai2144** [comment]
根据你提供的复现代码和描述，问题是关于 ProTable 组件在数据源设置为 request 的情况下，expandable 配置失效的问题。

根据文档说明，ProTable 的 expandable 配置只在数据源为 dataSource 的情况下有效。而当数据源设置为 request 时，expandable 配置会失效。

此外，根据你提供的截图，expandable 的效果是可展开的。

如果你希望在数据源为 request 的情况下，也能保留 expandable 的配置生效，目前来说是无法直接实现的。

如果你有其他问题，欢迎继续提问。

**Comment by zmm2tysu** [comment]
@chenshuai2144 用dataSource数据源也无法默认展开
![image](https://github.com/user-attachments/assets/013bb54b-82a8-4d5c-8b80-a54769eedd79)
