### ISSUE TITLE
点击菜单打开新窗口 新窗口需要移除layout组件

### ISSUE THREAD

**Issue by pingguoping** [ant-design/pro-components#7827]
目前在routes里面的路由设置layout:false 这种情况会导致这个路由不会再menu里面显示,因此无法通过点击菜单打开新窗口

**Comment by chenshuai2144** [comment]
用 url params  控制 layout  就可以啦。判断url 参数然后可以将headerRender、footerRender、menuRender、menuHeaderRender等设置为false，即可不展示部分layout模块。
