### ISSUE TITLE
SchemaForm不支持动态steps 吗？🧐[问题]

### ISSUE THREAD

**Issue by greenking19** [ant-design/pro-components#7829]
### 🧐 问题描述
是这样的，我有一个表单流程根据第一步的一个select去判断下一步的内容。
一般就2个步骤
但是select有一个选项选了之后想变成3个步骤，请问要如何实现呢？
我试过改SchemaForm的steps，但是发现行不通
SchemaForm的示例代码太长了，我就不放上来了。如果需要我可以建一个仓库

**Comment by greenking19** [comment]
我又试了一下发现可以了，好像是我现版本pro-compose比较低的原因。现在我升级试试

**Comment by chenshuai2144** [comment]
支持的，注意下版本。要在 antd@4.24, pro-components  最新版本中使用

**Comment by greenking19** [comment]
> 支持的，注意下版本。要在 antd@4.24, pro-components 最新版本中使用

请教一下，pro-compose支持自定义ProFormFields吗？ 我看了文档没找到，因为我又一些表单组件需要自定义
