### ISSUE TITLE
👑 [需求]无法实现一个可选中一行且没有CheckBox或者radio的简单列表

### ISSUE THREAD

**Issue by sapphirezzz** [ant-design/pro-components#783]
### 🥰 需求描述

**目前想要实现这么一个列表：**
1. 列表每一行只有一列，内容为普通文本
2. 点击某一行，选中该行（没有CheckBox或Radio）
3. 每一行之间没有分割线
4. 带分页功能

**目前使用Protable或者Prolist实现遇到的问题：**

- Protable
设置onRow属性，可以实现点击某一行时修改selectedRowKeys，达到选中的效果；
```
(record, index) => {
    return {
      onClick: () => {
        changeSelectedRowKeys(record.name);
      }
    }
}
```
_遇到的问题：_
1. 无法去掉分割线
2. 且带有CheckBox或Radio。

设置rowSelection为以下代码可以去掉Radio，但是勾选那列实际还在，内容前面会有**空白间隔**。
```
{
    type: 'radio',
    selectedRowKeys: selectedRowKeys,
    getCheckboxProps: (record: { name: string }) => {
      return {
        name: 'disable',
        disabled: true
      }
    },
    renderCell: (value: any, record: { name: string; }, index: number) => {
      return <></>
    }
}
```

- ProList

可以设置 split 去掉分割线

_遇到的问题：_
1. 使用上面的 rowSelection 代码无法去掉 Radio
2. 没有 onRow 或其他能达到设置选中效果的属性

**Comment by chenshuai2144** [comment]
这个需要 antd 的 table 来支持一下了

**Comment by fleetscythe** [comment]
直接用rowClassName 不行么?  
![image](https://user-images.githubusercontent.com/10510634/96670657-768c6f00-1392-11eb-8713-06da68f67327.png)
![image](https://user-images.githubusercontent.com/10510634/96670728-acc9ee80-1392-11eb-92c0-931ca4425b9b.png)
