### ISSUE TITLE
🧐[问题] 在非Umi 环境，如何配置国际化，比如 ProLoginPage

### ISSUE THREAD

**Issue by hyzx86** [ant-design/pro-components#7830]
我在Vite 中使用 pro-components  的 LoginPage ，
但是在英文语言环境下，登录按钮显示是中文的。我知道  antd 系列 都在 用 Intl，

我想请教下，如何在 非 Umi 环境下 配置 所有 pro-components  组件的国际化设置呢？

我现在是这么设置的，但是不管用
```tsx
const LoginPage = () => {
  return (
    <ProConfigProvider dark>
      <LocaleProvider
        locale={{
          locale:’en-US‘
        }}
      >
        <MyLoginPage />
      </LocaleProvider>
    </ProConfigProvider>
  );
};
```

**Comment by chenshuai2144** [comment]
使用ConfigProvider国际化组件：可以在入口处全局设置语言，也可以对特定组件进行单独的语言设置。

https://github.com/ant-design/ant-design/blob/master/components/date-picker/index.zh-CN.md

具体看这个文档

**Comment by hyzx86** [comment]
我这么写的，似乎没用啊
![image](https://github.com/ant-design/pro-components/assets/15613121/16dc102d-a5a4-4020-9832-a7df578c7ed9)
源码中，这两段 有什么讲究么？
还是我 设置的当前语言不对啊？怎么设置当前语言呢？

**Comment by hyzx86** [comment]
好了。。暂时不去管那些了。。
源码里找到了这个

```tsx
      <LoginFormPage
        submitter={{
          searchConfig: {
            submitText: 'Login'  //直接配就好啦
          }
        }}
```
