### ISSUE TITLE
ProTable组件中的查询部分🧐[问题]

### ISSUE THREAD

**Issue by jynlxqc** [ant-design/pro-components#7831]
我用的是ProTable组件，上方有很多查询条件，其中有一项状态查询条件是有默认值且是折叠起来的，当我根据年龄搜索的时候，会清空状态的值，此时调用的接口也确实状态为undefined，也给查询条件中的状态清空了（打印看到的），但是当我展开查询条件的时候，状态又会有值是默认值，这个要怎么解决啊

**Comment by chenshuai2144** [comment]
估计是  initvalues  的问题， initvalues去掉试试
