### ISSUE TITLE
🧐[问题]layout的mix模式下，能不能不要让头部的菜单显示子菜单？

### ISSUE THREAD

**Issue by henryzp** [ant-design/pro-components#7833]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

<img width="539" alt="image" src="https://github.com/ant-design/pro-components/assets/3849702/28c46ffb-c47c-4121-a3ed-95eceaed581d">

我不希望显示红框。。。因为有一些情况下，譬如项目这个菜单，它在进入详情之后，会有一个左侧菜单的：

<img width="600" alt="image" src="https://github.com/ant-design/pro-components/assets/3849702/6ed04922-7e2e-453a-aec0-c7afb635ea06">

如果在头部那里有这个菜单的话，就没法携带一些参数了。。

### 🚑 其他信息

<img width="578" alt="image" src="https://github.com/ant-design/pro-components/assets/3849702/9458e955-bef0-416e-8bf4-aba4fdaa2838">

**Comment by chenshuai2144** [comment]
mix  模式 头部本来就不能展示子菜单呀，你是怎么实现的？

**Comment by henryzp** [comment]
这是layout的setting

```
const Settings: ProLayoutProps & {
  pwa?: boolean;
  logo?: string;
} = {
  navTheme: 'light',
  // 拂晓蓝
  colorPrimary: '#1890ff',
  splitMenus: true,
  layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixSiderbar: true,
  colorWeak: false,
  title: '征迁全过程',
  pwa: true,
  logo: 'https://nbhs-file.oss-cn-hangzhou.aliyuncs.com/common/logo-with-color.png',
  iconfontUrl: '',
  token: {
    // 参见ts声明，demo 见文档，通过token 修改样式
    //https://procomponents.ant.design/components/layout#%E9%80%9A%E8%BF%87-token-%E4%BF%AE%E6%94%B9%E6%A0%B7%E5%BC%8F
  },
};

export default Settings;

```

<img width="676" alt="image" src="https://github.com/ant-design/pro-components/assets/3849702/8a3c6071-9b5c-4bf7-9719-9ac6a296da14">

然后路由就是嵌套个两三层

**Comment by henryzp** [comment]
splitMenus: true,
 layout: 'mix',

加了这两个之后就会生效。。。然后我现在不知道咋整了，求给个方案？

**Comment by chenshuai2144** [comment]
在`layout`的`mix`模式下，你可以通过修改配置来控制头部菜单是否显示子菜单。可以在`defaultSettings.ts`文件中将`splitMenus`设置为`true`，这样顶部菜单就会正确展示一级菜单。同时，当使用`mix`模式后，点击一级菜单不会直接定位到第一个子级菜单页面，需要在配置中设置`redirect`的地址。这样，你就可以实现头部菜单不显示子菜单的需求了。
