### ISSUE TITLE
🐛[BUG]StepsForm中formProps设置了form后onFinish无响应

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/pro-components#7834]
### 🐛 bug 描述
在分步页面中，给StepsForm的formProps设置form后，StepsForm.StepForm表单的的onFinish事件无法触发

```jsx
      const [form] = ProForm.useForm();

      <StepsForm<{
        name: string;
      }>
        onFinish={async (values) => {
          console.log(values);
          await waitTime(1000);
          message.success('提交成功');
        }}
        formProps={{
          form,
          validateMessages: {
            required: '此项为必填项',
          },
        }}
```

### 📷 复现步骤
[stackblitz](https://stackblitz.com/edit/react-d1j2uf?file=App.tsx,index.tsx)

点击去第二步按钮没反应

### 🏞 期望结果
onFinish正常调用

### © 版本信息

- ProComponents 版本: 2.6.34
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by natashaamin** [comment]
You should remove form inside formProps. look at the stackblitz below

[stackblitz](https://stackblitz.com/edit/react-d1j2uf-vhtvdw?file=App.tsx,index.tsx)

**Comment by ayonli** [comment]
我也碰到了，使用以下方式可以暂时处理：

```tsx
const [form] = StepesForm.useForm();
const formRef = useRef(form)

<StepsForm<{
        name: string;
      }>
        onFinish={async (values) => {
          console.log(values);
          await waitTime(1000);
          message.success('提交成功');
        }}
        formRef={formRef}
// ...
```

**Comment by chenshuai2144** [comment]
根据你提供的代码和描述，我注意到你在使用Ant Design Pro的StepsForm组件时遇到了一个问题。根据你的描述，当给StepsForm的formProps设置了form之后，StepsForm.StepForm表单的onFinish事件无法触发。

经过查看你提供的代码和复现步骤，我发现这是因为在StepsForm的formProps属性中，你将form对象传递给了form属性。这会导致StepsForm组件的form属性和StepForm组件的form属性指向同一个form实例，从而导致触发onFinish事件时出现问题。

为了解决这个问题，你可以尝试将form属性从formProps中移除，并直接在StepsForm组件上使用form属性，如下所示：

```jsx
<StepsForm<{
  name: string;
}>
  onFinish={async (values) => {
    console.log(values);
    await waitTime(1000);
    message.success('提交成功');
  }}
  form={form}
  validateMessages={{
    required: '此项为必填项',
  }}
>
```

通过这种方式，你可以确保StepsForm和StepForm组件使用的是同一个form实例，从而可以正常触发onFinish事件。

希望这个回答能帮到你解决问题，如果还有任何疑问，请随时追问！
