### ISSUE TITLE
🧐[问题] ProTable 的 “列设置” 如何调整宽度，在列字段非常长的情况下

### ISSUE THREAD

**Issue by zhanyeye** [ant-design/pro-components#7838]
### 🧐 问题描述

ProTable 某些列太长，导致 “列设置” 宽度不够用，字段溢出

### 🚑 问题截图

![image](https://github.com/ant-design/pro-components/assets/35565811/4d0d62c4-c3e1-413e-ba16-29b74984c0eb)

**Comment by q1uxu** [comment]
之前我也遇到了这个问题，他们不知怎么回事，给`.ant-pro-table-column-setting-list-item-title`标签添加了` max-width: 80px;`的CSS。我是通过下面这个CSS样式覆盖的`.ant-pro-table-column-setting-list-item-title {max-width: unset !important;}`
![image](https://github.com/ant-design/pro-components/assets/76635711/20417e76-ad8e-4cd5-a7ad-206bd0c227be)

**Comment by zhanyeye** [comment]
> 之前我也遇到了这个问题，他们不知怎么回事，给`.ant-pro-table-column-setting-list-item-title`标签添加了` max-width: 80px;`的CSS。我是通过下面这个CSS样式覆盖的`.ant-pro-table-column-setting-list-item-title {max-width: unset !important;}` ![image](https://user-images.githubusercontent.com/76635711/278916640-20417e76-ad8e-4cd5-a7ad-206bd0c227be.png)
超级感谢嘿！

**Comment by zhanyeye** [comment]
样式覆盖是需要注意， 这个“列设置” 元素 不在 ProTable 中，需要在全局样式 global.less 中覆盖

```
.ant-pro-table-column-setting-list-item-title {
  max-width: unset !important;
}


```
