### ISSUE TITLE
🧐[问题]props valueEnum 改变，但是ProFormSelect并未触发render渲染

### ISSUE THREAD

**Issue by liuchuangjun321** [ant-design/pro-components#784]
### 🧐 问题描述
在使用pro-form，处理表单联动的时候，某个select组件onchange函数里改变另一个select组件的valueEnum props（从state里取值），但是ProFormSelect并未触发render渲染。

**Comment by liuzhenji** [comment]
这个问题确实存在的， 而且最新版本的也存在。我是在PRO-TABLE中遇到了

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/field#%E8%BF%9C%E7%A8%8B%E6%95%B0%E6%8D%AE

写了个文章来解释为什么
