### ISSUE TITLE
A props object containing a "key" prop is being spread into JSX:

### ISSUE THREAD

**Issue by UnkAtreus** [ant-design/pro-components#7840]
### Reproduction link

[https://tmpfiles.org/2986060/screenshot2023-10-30001811.png](https://tmpfiles.org/2986060/screenshot2023-10-30001811.png)

### Steps to reproduce

const columns: ProDescriptionsItemProps<IProject>[] = [
    {
      title: 'ID',
      key: 'id',
      dataIndex: 'id',
    }, ...
]

<ProDescriptions
        dataSource={projects}
        columns={columns}
        loading={isProjectLoading}
        column={6}
        bordered
        key={projects?.id}
        layout='vertical'
      />

### What is expected?

It was happen when using columns and datasource props. I got an error 
Warning: A props object containing a "key" prop is being spread into JSX:
  let props = {key: someKey, title: ..., dataIndex: ..., mode: ..., text: ..., valueType: ..., entity: ..., index: ..., emptyText: ..., action: ..., editableUtils: ...};
  <FieldRender {...props} />

You can see full error message in this link https://tmpfiles.org/2986060/screenshot2023-10-30001811.png

### What is actually happening?

fix this key issue

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | react:18.2.0 ,@ant-design/pro-components:2.6.31 |
| System | Window |
| Browser | Google Chrome browser |

**Comment by chenshuai2144** [comment]
在你的代码片段中，当使用`<ProDescriptions>`组件时，将一个包含`key`属性的props对象作为spread操作符传递给JSX。然而，在React中，`key`是一个特殊的属性，用于帮助React识别和区分列表中的每个子元素。因此，你不能将`key`作为spread操作符传递给组件。

要解决这个问题，你可以将`key`属性从props对象中移除，并将其直接作为`<ProDescriptions>`组件的属性传递，如下所示：

```tsx
<ProDescriptions
  dataSource={projects}
  columns={columns}
  loading={isProjectLoading}
  column={6}
  bordered
  layout='vertical'
  key={projects?.id}
/>
```

这样做就能解决警告信息中的问题。请注意，在React中，组件的`key`属性应该是一个稳定的、唯一的标识符，通常与组件的数据相关联。在你的代码中，你使用了`projects?.id`作为`key`，确保每个`projects`对象都有一个唯一的`id`属性。

希望这个解答能帮到你！如果还有其他问题，请随时提出。
