### ISSUE TITLE
🧐[问题]ProLayout组件加了lazy的组件会报错

### ISSUE THREAD

**Issue by Charlie-C-810** [ant-design/pro-components#7849]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
![6fd547af377fe72e3d5efd0bc95ad94](https://github.com/ant-design/pro-components/assets/54610249/c5efb02b-a7e7-4b7f-b34d-48c1202bee57)
ProLayout组件加了lazy的组件会报错

### 💻 示例代码
ProLayout组件的route属性
![d58e882998bab6a63ea1fc205ad661ea_](https://github.com/ant-design/pro-components/assets/54610249/9be9c930-dffb-4eae-8e0c-6c48c8c9b5d2)
![a76eb68a8458493dc696ab017210c192_](https://github.com/ant-design/pro-components/assets/54610249/308297df-fe80-4022-b4bc-abb1d31cd1be)
路由信息
![9710ff3d5a5cd9a4dd93c442fd3a91fd_](https://github.com/ant-design/pro-components/assets/54610249/a7c6e01f-c876-40f9-b9b5-3183804755f6)

**Comment by fnoopv** [comment]
`lazy`组件需要`suspense`包裹
