### ISSUE TITLE
👑 [需求]

### ISSUE THREAD

**Issue by wiredgril666** [ant-design/pro-components#7857]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件
protable

### 🥰 需求描述
protable scroll={{x:"max-content"}} 和ellipsis，width 不生效

const columns =[  {
      title: '产品名称',
      dataIndex: 'productName',
      search: false,
      width: 300,
      ellipsis: true,
    }]
   设置ellipsis
   <ProTable
   ...
     scroll={{ x: 'max-content' }}/>
     设置 scroll={{ x: 'max-content' }}
     设置width的columns不生效，也不展示缩略
   
### 🧐 解决方案

认为， scroll={{ x: 'max-content' }}和ellipse同时设置的情况，该列表项也有一个默认的缩略长度，
要是同时设置width,ellipse,scroll3个，缩略长度应该以width为准
### 🚑 其他信息

![image](https://github.com/ant-design/pro-components/assets/16633837/19dea244-3f68-4541-82d4-bae63efa8ff7)
![image](https://github.com/ant-design/pro-components/assets/16633837/b802bf30-07f4-4a09-8f12-b4eecd3f22fb)

**Comment by wmy94827** [comment]
因为 scroll={{ x: 'max-content' }} 这个设置导致的，宽度写死也没用。不知道该如何同时使用 scroll={{ x: 'max-content' }}和ellipsis:true

**Comment by wells974** [comment]
同问 这个问题解决了吗

**Comment by qindj** [comment]
我碰到一样的问题，设置max-content后，width和ellipsis无效，我的场景是在ProTable某个column输出显示一个长字符串（类似于地址，可能会更长），通过自定义render解决，在render里返回一个Typography.Text，设置它的style width，类似于：`<Typography.Text ellipsis style={{ maxWidth: 150 }}>`

**Comment by whhlulu** [comment]
解决了吗
