### ISSUE TITLE
🧐[问题]怎么使用Protable创建一个没有toolbar的表格

### ISSUE THREAD

**Issue by hfmvin** [ant-design/pro-components#7858]
### 🧐 问题描述

我需要使用Protable创建一个没有toolbar的表格，但官网demo里的无toolbar表格仍存在toolbar，也没有相关api

### 🚑 其他信息
demo中仍存在toolbar
https://procomponents.ant.design/components/table?current=1&pageSize=5&tab=api#packages-table-src-components-table-tab-api-demo-no-title

**Comment by wanghui2021** [comment]
`toolBarRender={false}`

**Comment by chenshuai2144** [comment]
你好！根据你提供的信息，我看到你想使用Protable创建一个没有toolbar的表格。从官网demo中，我理解到它们似乎没有提供直接的API来创建没有toolbar的表格。

不过，你可以通过在Protable的`toolbar`属性中传入一个`null`值来实现没有toolbar的效果。下面是示例代码：

```jsx
import { ProTable } from '@ant-design/pro-table';

const dataSource = [
  // 数据源
];

const columns = [
  // 表格列配置
];

const MyTable = () => {
  return (
    <ProTable
      toolbar={null} // 设置toolbar为null
      dataSource={dataSource}
      columns={columns}
    />
  );
}

export default MyTable;
```

通过将`toolbar`属性设置为`null`，你可以创建一个没有toolbar的表格。希望能帮到你！如果还有其他问题，请随时提问。
