### ISSUE TITLE
🐛[BUG]V5 ProTable form 版本的表单属性失效

### ISSUE THREAD

**Issue by hanxinimm** [ant-design/pro-components#787]
### 🐛 bug 描述

表单组件功能丢失

![image](https://user-images.githubusercontent.com/13499426/96608266-c08e3a00-132b-11eb-970c-0594f4a9d6b2.png)

### 📷 复现步骤

        <ProTable<T, U>
          type="form"
          formRef={this.getFormRef}
          form={this.getFormOptions()}
          rowKey={this.props.rowKey}
          columns={this.props.items}
          options={false}
          // search={formConfig}
        />

![image](https://user-images.githubusercontent.com/13499426/96608288-c84dde80-132b-11eb-82b3-6a8f2b81a566.png)

### 🏞 期望结果

![image](https://user-images.githubusercontent.com/13499426/96608420-f0d5d880-132b-11eb-8860-6ad816f18ee6.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
什么丢失了?

**Comment by hanxinimm** [comment]
表单的布局设置没有效果，表单自带的重置提交按钮无法隐藏和配置，点击提交表单事件调用表单提交方法，不会触发表单提交

**Comment by chenshuai2144** [comment]
@hanxinimm  读一下文档吧， 用起来和 antd 的 form 有点区别。
这个demo 可以教你用一下字对应提交
https://procomponents.ant.design/components/form#%E7%99%BB%E5%BD%95
