### ISSUE TITLE
rightContentRender使用和官方一直为啥一直报错啊

### ISSUE THREAD

**Issue by Modplay** [ant-design/pro-components#7870]
### 🧐 问题描述
rightContentRender使用和官方一直为啥一直报错啊

### 💻 示例代码
```
export const layout: RunTimeLayoutConfig = ({initialState}) => {
  return {
    rightContentRender: ()=><HeaderDropMenu/>,
};
```

### 报错信息
X [ERROR] Expected ">" but found "/"

    src/app.ts:37:43:
      37 │     rightContentRender: ()=><HeaderDropMenu/>,
         │                                            ^
         ╵                                            >

error - [icons] build failed: Error: Build failed with 1 error:
src/app.ts:37:43: ERROR: Expected ">" but found "/"

![image](https://github.com/ant-design/pro-components/assets/35032843/a58caede-ee67-40ed-9987-1f23d519cfb2)

**Comment by tsuyoii** [comment]
> ### 🧐 问题描述
> rightContentRender使用和官方一直为啥一直报错啊
> 
> ### 💻 示例代码
> ```
> export const layout: RunTimeLayoutConfig = ({initialState}) => {
>   return {
>     rightContentRender: ()=><HeaderDropMenu/>,
> };
> ```
> 
> ### 报错信息
> X [ERROR] Expected ">" but found "/"
> 
> ```
> src/app.ts:37:43:
>   37 │     rightContentRender: ()=><HeaderDropMenu/>,
>      │                                            ^
>      ╵                                            >
> ```
> 
> error - [icons] build failed: Error: Build failed with 1 error: src/app.ts:37:43: ERROR: Expected ">" but found "/"
> 
> ![image](https://private-user-images.githubusercontent.com/35032843/280767900-a58caede-ee67-40ed-9987-1f23d519cfb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NDE4NDUsIm5iZiI6MTcwMzg0MTU0NSwicGF0aCI6Ii8zNTAzMjg0My8yODA3Njc5MDAtYTU4Y2FlZGUtZWU2Ny00MGVkLTk5ODctMWYyM2Q1MTljZmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA5MTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkM2JiMDNmMDZhNTNjZTM4NmFhODA2MTFjZGVhOTQwMzdlOTQyYWQwNWI1ZTdjYTBkYzUxMzIyY2I3ZGM2ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vET2cmalREh1mFYPB3YJvhwsB7m_0t2j8WAWE2InNQY)

把app.ts改成app.tsx
