### ISSUE TITLE
报错/node_modules/@ant-design/pro-provider/es/useStyle/index.js Module not found: Can't resolve 'antd/lib/theme/style' 🧐[问题]

### ISSUE THREAD

**Issue by Kuuga46** [ant-design/pro-components#7872]
### 🧐 问题描述
使用antd 4.23.0 procomponent 2.6.35，报错找不到 'antd/lib/theme/style' 。
antd/lib文件夹下并没有theme文件夹。但V5版本的antd是有的。

**Comment by 1Telescope1** [comment]
哥们你解决了吗？我也遇到了

**Comment by chenshuai2144** [comment]
升级 一下 antd 的版本到 4.x 的最新就有这个文件夹了
