### ISSUE TITLE
🐛[BUG]   protable组件的onloadingchange类型定义不一致

### ISSUE THREAD

**Issue by earthaYan** [ant-design/pro-components#7876]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

node_modules中的定义：
`onLoadingChange?: (loading: boolean | SpinProps | undefined) => void;
`
文档中的定义：
`(loading:boolean)=>void`
### 🏞 期望结果

两者可以一致，以及想知道 SpinProps 或者undefind在什么情况下会出现

### © 版本信息

- ProComponents 版本:  @ant-design/pro-table: "3.0.20"
- umi 版本
- 浏览器环境:Chrome
- 开发环境 [windows]

**Comment by chenshuai2144** [comment]
以 代码为主。

loading 设置为 SpinProps  就会出现 onLoadingChange 里 参数是 SpinProps，

 undefind 是 防御性编程
