### ISSUE TITLE
👑 [需求]table的select和check的状态可以设置相对独立

### ISSUE THREAD

**Issue by goodve** [ant-design/pro-components#788]
### 🥰 需求描述
table的select和check的状态可以设置相对独立，
日常的需求是单击选一行进行编辑，check多个进行批量删除

### 🧐 解决方案

参考easyui的 api  如图
![image](https://user-images.githubusercontent.com/17634299/96660485-4043f500-137c-11eb-877f-d883a3ac9cbb.png)

**Comment by goodve** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
这个需要 antd 来支持了。我们只是antd 的搬运工

**Comment by goodve** [comment]
> 这个需要 antd 来支持了。我们只是antd 的搬运工

antd那边说他们暂时不考虑................

**Comment by chenshuai2144** [comment]
礼貌的拒绝了你，哈哈
