### ISSUE TITLE
🐛[BUG] 在 App.tsx 中配置运行时 layout 的 itemClick 属性时不起作用

### ISSUE THREAD

**Issue by yq756530939** [ant-design/pro-components#7882]
### 🐛 bug 描述
在 App.tsx 配置运行时 layout时，传递 `itemClick`控制 `AppList`点击行为时，发现不起作用。研究`ProLayout`发现
`AppsLogoComponents` 中的属性名称改为 `onItemClick`，但 layout 还保持为 `itemClick`

### 🏞 期望结果
配置 App.tsx的 layout时传递的 `itemClick` 方法与AppsLogoComponents的属性 `onItemClick` 一致

### © 版本信息

- ProComponents 版本: [2.6.35]
- @umijs/max 版本: [4.0.87]
- 浏览器环境 Chromw: [119.0.6045.123]
- 开发环境 [mac OS]

### 🚑 其他信息

![image](https://github.com/ant-design/pro-components/assets/7676294/b7d1e4d1-891e-4963-b1f6-abd197219ec0)
![image](https://github.com/ant-design/pro-components/assets/7676294/a2c91659-dfad-4d11-81d8-a117481981f6)

**Comment by chenshuai2144** [comment]
这个问题通常是由于 layout 的版本问题导致的。你可以尝试删除依赖并重新安装来解决这个问题。另外，从最新的更新中可以看出，routes 中的 layout 配置选项已经被移动到了 app.ts 文件中的 runtimeConfig 中的 layout 字段中。你可以参考 [runtime-config > layout](https://umijs.org/docs/api/runtime-config#layout) 来进行配置。希望能帮到你。

**Comment by yq756530939** [comment]
ProComponent已经是最新的版本。而且配置在 runtime 的 layout中，我看了一下相关AppsLogoComponents的源码。
<img width="667" alt="image" src="https://github.com/ant-design/pro-components/assets/7676294/b746e714-36ae-44c5-9566-8397312477cf">
这个地方是原封不动的传递runtime-layout的配置，也就是 AppsLogoComponents 接收的是 onItemClick 而 runtime-layout 中传递的只能是 itemclick 。
<img width="941" alt="image" src="https://github.com/ant-design/pro-components/assets/7676294/8649441e-9368-44c3-843f-d7298f4b5826">
有三处 AppsLogoComponents 组件的调用，确只改了这一个地方
