### ISSUE TITLE
🧐[问题] Protable的options 里面的search  有没有api可以重置这个search的值

### ISSUE THREAD

**Issue by pingguoping** [ant-design/pro-components#7883]
Protable的options 里面的search  有没有api可以重置这个search的值

**Comment by chenshuai2144** [comment]
对于select元素的options，可以使用JavaScript DOM API重置search的值。可以通过给select元素设置selectedIndex属性为-1来重置选中的选项，从而重置search的值。 示例代码如下：

```javascript
// 假设select的id为mySelect
var selectElement = document.getElementById('mySelect');
selectElement.selectedIndex = -1;
```

以上代码将重置选中的选项，并清除search的值。另外 antd  也提供了相应的 api，但是使用起来相对复杂。你需要自定义下Protable的 select，如果是为了一些小问题，建议不要这么搞。
