### ISSUE TITLE
🐛[BUG]ProTable Columns ellipsis设置无效，copyable：true，ellipsis才生效

### ISSUE THREAD

**Issue by David2k13** [ant-design/pro-components#789]
### 🐛 bug 描述

ProTable Columns ellipsis设置无效，copyable：true，ellipsis才生效

### 🏞 期望结果

Columns ellipsis单独设置生效

### 💻 复现代码

https://codesandbox.io/s/happy-cerf-800d6
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by David2k13** [comment]
![image](https://user-images.githubusercontent.com/22017991/98615053-c24c8b80-2334-11eb-8305-e1098c7690d7.png)
好像在2.10.0又出现问题了

**Comment by chenshuai2144** [comment]
试了一下不会，是不是 antd 的版本没跟上？

**Comment by David2k13** [comment]
可能是我没注意antd版本
