### ISSUE TITLE
[问题] 在 vite 创建的项目中，使用 ProLayout 组件能正常渲染出来页面，但点击导航，内容子组件无法正常渲染

### ISSUE THREAD

**Issue by Faithree** [ant-design/pro-components#7892]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

1. 在 vite 创建的项目中，使用 ProLayout 组件能正常渲染出来页面，但点击导航，内容子组件无法正常渲染
2. 有两个问题，请问 vite 创建的项目，如何使用 ProLayout 组件生成类似 antd-pro的导航布局？ @ant-design/pro-components有哪几个组件是必须在 umi 环境下使用的，哪几个是能在 非 umi 环境下使用的？

### 💻 示例代码

<img width="1048" alt="image" src="https://github.com/ant-design/pro-components/assets/21101396/b650b23b-1630-47a9-9641-e6f9b43b0e86">

<img width="1146" alt="image" src="https://github.com/ant-design/pro-components/assets/21101396/66ff8dff-fdca-4698-827a-c3f61a7542bb">

### 🚑 其他信息

<img width="848" alt="image" src="https://github.com/ant-design/pro-components/assets/21101396/8382e68f-5135-4a72-85a5-876e804f5758">

**Comment by chenshuai2144** [comment]
这个问题可能是由于路由配置和组件使用不一致导致的。首先，确保在路由配置中的每个组件都有正确的 name 字段。

其次，在 ProLayout 组件的 `route` 属性中传递正确的路由信息。在上述代码片段中，使用了 `clientRoutes[0]` 来传递路由信息。请确保 `clientRoutes` 是正确的，并且包含所有的路由信息。你可以在 `useAppData` 中获取 `clientRoutes`，并将其作为参数传递给 ProLayout 组件。

最后，确保组件正确渲染，你可以使用 `Outlet` 组件来渲染子组件。在上述代码片段中，`<Outlet />` 表示渲染当前路由对应的子组件。请确保你的子组件已正确配置，并且与路由匹配。

如果上述步骤都没有解决问题，请提供更多的代码和错误信息，以便我能够更好地帮助你。
