### ISSUE TITLE
🧐[问题] 如何在 EditableProTable或者ProTable中使用 `antd` Table 的 `table ref`？

### ISSUE THREAD

**Issue by roadloser** [ant-design/pro-components#7893]
### 🧐 问题描述
我将 `pro-components` 内置的 `antd` 版本指定为 5.11.0，并启用了虚拟化功能。在尝试使用 `EditableProTable`与`ProTable` 提供的 `actionRef` 时，发现没有类似于 `table ref` 中的 `scrollTo` 方法可用。我还尝试直接注入一个 ref，希望能够实现目标，但实际上这个 ref 似乎并没有被成功注入到 `Table` 组件的 ref 上。

请问有什么方法可以解决这个问题吗？非常感谢！

**Comment by ChenAlmost** [comment]
遇到了同样的问题，

**Comment by ChenAlmost** [comment]
#4509 
遇到了同样的问题，发现是没有暴露出这个api。

**Comment by Deer404** [comment]
遇到了同样的问题，

**Comment by chenshuai2144** [comment]
在 `EditableProTable` 或 `ProTable` 中使用 `antd` 的 `Table` 的 `table ref`，可以通过 `actionRef` 属性来实现。你可以先引入 `ActionType` 类型并使用 `useRef` 创建一个 `actionRef` 对象：

```tsx
import { ProColumns, ActionType } from '@ant-design/pro-table';
import { useRef } from 'react';

const columns: ProColumns<API.CurrentUser>[] = [
  {
    title: '姓名',
    dataIndex: 'name',
    hideInSearch: true,
  },
];

const actionRef = useRef<ActionType>();

export default <ProTable actionRef={actionRef} />;
```

然后，你就可以通过 `actionRef` 来获取 `Table` 组件的实例，并调用其相关的方法来滚动至指定位置。例如，你可以在需要的地方调用 `actionRef.current?.scrollTo` 方法来实现滚动操作。

请注意，`Table` 组件的 `ref` 不会直接注入到 `ProTable` 或 `EditableProTable` 上，而是注入到 `actionRef` 对象中，通过 `actionRef.current` 来访问 `Table` 组件的实例。

如果是table本身的 dom，推荐使用 id 来设置。

**Comment by bowencool** [comment]
没有这个 scrollTo 方法，是我写错了吗

<img width="889" alt="image" src="https://github.com/ant-design/pro-components/assets/20217146/4c2cd737-4730-4327-a4fb-835718a3b4a4">

<img width="131" alt="image" src="https://github.com/ant-design/pro-components/assets/20217146/40002ed4-81c9-4a42-a884-b745146b8006">

> 在 `EditableProTable` 或 `ProTable` 中使用 `antd` 的 `Table` 的 `table ref`，可以通过 `actionRef` 属性来实现。你可以先引入 `ActionType` 类型并使用 `useRef` 创建一个 `actionRef` 对象：
> 
> ```tsx
> import { ProColumns, ActionType } from '@ant-design/pro-table';
> import { useRef } from 'react';
> 
> const columns: ProColumns<API.CurrentUser>[] = [
>   {
>     title: '姓名',
>     dataIndex: 'name',
>     hideInSearch: true,
>   },
> ];
> 
> const actionRef = useRef<ActionType>();
> 
> export default <ProTable actionRef={actionRef} />;
> ```
> 
> 然后，你就可以通过 `actionRef` 来获取 `Table` 组件的实例，并调用其相关的方法来滚动至指定位置。例如，你可以在需要的地方调用 `actionRef.current?.scrollTo` 方法来实现滚动操作。
> 
> 请注意，`Table` 组件的 `ref` 不会直接注入到 `ProTable` 或 `EditableProTable` 上，而是注入到 `actionRef` 对象中，通过 `actionRef.current` 来访问 `Table` 组件的实例。
> 
> 如果是table本身的 dom，推荐使用 id 来设置。

**Comment by xiaoshengwpp** [comment]
@chenshuai2144 请问开启虚拟列表后 滚动条怎么监听

**Comment by here-is-zhizhi** [comment]
@ChenAlmost 

> 在 `EditableProTable` 或 `ProTable` 中使用 `antd` 的 `Table` 的 `table ref`，可以通过 `actionRef` 属性来实现。你可以先引入 `ActionType` 类型并使用 `useRef` 创建一个 `actionRef` 对象：
> 
> ```tsx
> import { ProColumns, ActionType } from '@ant-design/pro-table';
> import { useRef } from 'react';
> 
> const columns: ProColumns<API.CurrentUser>[] = [
>   {
>     title: '姓名',
>     dataIndex: 'name',
>     hideInSearch: true,
>   },
> ];
> 
> const actionRef = useRef<ActionType>();
> 
> export default <ProTable actionRef={actionRef} />;
> ```
> 
> 然后，你就可以通过 `actionRef` 来获取 `Table` 组件的实例，并调用其相关的方法来滚动至指定位置。例如，你可以在需要的地方调用 `actionRef.current?.scrollTo` 方法来实现滚动操作。
> 
> 请注意，`Table` 组件的 `ref` 不会直接注入到 `ProTable` 或 `EditableProTable` 上，而是注入到 `actionRef` 对象中，通过 `actionRef.current` 来访问 `Table` 组件的实例。
> 
> 如果是table本身的 dom，推荐使用 id 来设置。

`Table` 的实例并未暴漏在 `actionRef.current` 上

**Comment by lumiaoshan** [comment]
遇到了同样的问题

**Comment by Yeti-xxx** [comment]
<img width="502" height="95" alt="Image" src="https://github.com/user-attachments/assets/5b62e57e-756e-453f-99a5-2402846140fd" /> 目前还是没暴露scrollTo
