### ISSUE TITLE
🐛[BUG]ProTable组件Children模式下，不支持表单查询？

### ISSUE THREAD

**Issue by sk142857** [ant-design/pro-components#7895]
###

```
{
      title: '订单信息',
      children: [
        {
          title: '订单类型',
          dataIndex: 'order_type',
          width: '75px',
          align: 'center',
          order: 99,
          filters: false,
          hideInSearch: false,
          valueType: 'radio',
          initialValue: '',
          valueEnum: OrderTypeEnum,
          fieldProps: {
            onChange: () => {
              formRef.current?.submit()
            },
          },
          render(value, record) {
            return value
          },
        }
}
```

![image](https://github.com/ant-design/pro-components/assets/75599950/d9e033c0-f72d-4b58-82dd-ebad293c606d)

**Comment by chenshuai2144** [comment]
ProTable组件在Children模式下不支持表单查询的BUG，意味着在使用该组件时，如果你需要通过表单来进行查询操作，可能会遇到问题。

在提供的代码片段中，我们看到了ProTable组件的使用示例链接。你可以点击链接查看更多有关该组件的使用方式和示例。

根据提供的信息，ProTable组件在Children模式下不支持表单查询。这意味着当你需要在表格中使用表单来进行查询操作时，可能会遇到问题。因此，你可能需要考虑其他的解决方案来实现表单查询功能。

你可以尝试使用其他支持表单查询的组件，或者自己编写代码来实现该功能。例如，你可以使用Ant Design的Form组件来创建表单，并与ProTable组件进行配合使用，实现表单查询的功能。具体的实现方式会根据你的具体需求和代码结构而有所不同，你可以参考官方文档和示例来帮助你完成这一功能。

希望这个回答能够帮助到你，如果还有其他问题，请随时提问。
