### ISSUE TITLE
prolayout,Menu 设置group模式后， 怎么在收缩菜单情况下， group子目录也展示 Tooltip ？

### ISSUE THREAD

**Issue by ZhouJiahao228** [ant-design/pro-components#7899]
![1ECDD291BB0](https://github.com/ant-design/pro-components/assets/81454495/cded3613-b51a-4996-be99-ea4827b1bd63)

**Comment by ONLY-yours** [comment]
感觉要写自定义 render 了，太细颗粒度的控制有点不好搞

**Comment by chenshuai2144** [comment]
介意不要弄的太花，意义不是很大
