### ISSUE TITLE
🐛[BUG]Table 样式问题

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/pro-components#79]
### 🐛 bug 描述

https://github.com/ant-design/pro-components/blob/4c0f7374af1420900b6c6698fa6f8fd2467aed1c/packages/table/src/index.less#L21-L26

此处代码导致下图的问题
![image](https://user-images.githubusercontent.com/23520283/89138525-76888a00-d56e-11ea-8663-a99f7de8c905.png)

### 📷 复现步骤

当表格中有合并单元格时出现样式错误

### 🏞 期望结果

![image](https://user-images.githubusercontent.com/23520283/89138570-9b7cfd00-d56e-11ea-8f38-f79747a41b03.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

官方设计组件时可能有很好的想法,但有时候会导致出乎开发者预料的情况,比如刚开始pro-table 会给a标签加padding增加点击面积和这次的给第一列左侧留白(个人认为这样并不美观),初衷都是好的,但不一定是大家都需要的,这不在开发者预期中,会导致我们很迷惑,希望以后减少这种情况

**Comment by veici** [comment]
该处代码还会导致在表头固定时,表头多选框跟表格主体的多选框错位
