### ISSUE TITLE
🐛[BUG]-组件 `<ProDescriptions.Item valueType="second"  label="xxxx"/>` 计算时间的小时逻辑有问题

### ISSUE THREAD

**Issue by chenmijiang** [ant-design/pro-components#7901]
### 📷 复现步骤

<img width="745" alt="lQLPJxLFniPa_IfMqM0F0rAEgXMVyplrQgVGMw45ANUA_1490_168" src="https://github.com/ant-design/pro-components/assets/62453036/8a49a787-c965-4363-a4dd-4f7ab078d592">

![lQLPJwBMPssF_IdfzQGAsKs3tQB6bQJXBUYzDjkA1QE_384_95](https://github.com/ant-design/pro-components/assets/62453036/2e8d903b-8ca2-46a1-a686-208f7cd77313)

### 源码逻辑

![lQLPJwfCLzRRAyfNA37NBLqwHvDo7tsKhAEFRjU0KEAgAA_1210_894](https://github.com/ant-design/pro-components/assets/62453036/a870fa50-4196-4511-b065-ddc226171c44)

**Comment by ONLY-yours** [comment]
看起来是 h 计算少除了 24

**Comment by chenshuai2144** [comment]
直接搞个 pr 吧

**Comment by ONLY-yours** [comment]
fixed： https://github.com/ant-design/pro-components/pull/7929
