### ISSUE TITLE
🐛[BUG] PageContainer在开启 fixedHeader 后样式错误

### ISSUE THREAD

**Issue by zhouzyc** [ant-design/pro-components#7907]
### 🐛 bug 描述

问题1:如图开启配置后，top计算错误，没有置顶，现在top被计算为56px。
![image](https://github.com/ant-design/pro-components/assets/18420689/f4e79668-78a0-4a74-9ef0-d2765df0fd1e)
问题2：临时修改     top: 0px; 样式，
1，点击“欢迎” menu 和 “管理页面-一级页面” menu来回切换，会发现height没有动态计算，导致中间有一段空白间隔
![image](https://github.com/ant-design/pro-components/assets/18420689/7235a416-3e7d-4c0b-96a7-9c274835c93a)

### 📷 复现步骤

https://codesandbox.io/s/ce-lan-dao-hang-zhong-hou-tai-chan-pin-mo-ren-tui-jian-forked-dkdftk?file=/App.tsx

### 🏞 期望结果

能正常显示

### 💻 复现代码

https://codesandbox.io/s/ce-lan-dao-hang-zhong-hou-tai-chan-pin-mo-ren-tui-jian-forked-dkdftk?file=/App.tsx

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个问题可能是由于PageContainer组件在开启fixedHeader后计算top值错误导致的。你可以尝试以下解决方法：

1. 首先，检查你的页面布局和样式，确保没有其他地方改变了top值。
2. 如果发现top值错误，可以尝试通过修改样式文件中的top值来解决问题。
3. 如果你使用了自定义的getContainer方法，并且每次都创建新的DOM节点，可能会导致死循环。你需要注意检查getContainer的实现方式，避免重复创建节点。

希望这些解决方法能帮到你，如果还有其他问题，请告诉我。
