### ISSUE TITLE
🧐[问题]有些疑问为什么从2.5.0-beta.1开始，小问题问题越来越多，也不是兼容之前配置（文档也没有做出修改），导致不敢升级

### ISSUE THREAD

**Issue by David2k13** [ant-design/pro-components#791]
### 🧐 问题描述

有些疑问为什么从2.5.0-beta.1开始，小问题问题越来越多，也不是兼容之前配置（文档也没有做出修改），导致不敢升级，比如

例子1：dateRange，dateTimeRange类就改了，明显不符合业务，一般表格内是显示时间点，搜索是时间范围，导致现在要重新写两次Columns ，table设置date，search设置dateRange；

例子2：dateFormatter类型设置后，Columns 对应的initialValue输入是不是也应该相同的dateFormatter类型；

例子3：Columns 设置initialValue，search显示了默认值，request并没有获取默认值，只有手动点搜索，request才获取了search initialValue，理解不正确的地方，请指正

**Comment by chenshuai2144** [comment]
> 例子1：dateRange，dateTimeRange类就改了，明显不符合业务，一般表格内是显示时间点，搜索是时间范围，导致现在要重新写两次Columns ，table设置date，search设置dateRange；

这个是个 bug，现在的行为才是对的，你可以render 一下

> 例子2：dateFormatter类型设置后，Columns 对应的initialValue输入是不是也应该相同的dateFormatter类型；

这个功能还没做，做起来比较复杂

> 例子3：Columns 设置initialValue，search显示了默认值，request并没有获取默认值，只有手动点搜索，request才获取了search initialValue，理解不正确的地方，请指正

这个最新版本修掉了，使用了 form.initialValues

**Comment by David2k13** [comment]
> > 例子1：dateRange，dateTimeRange类就改了，明显不符合业务，一般表格内是显示时间点，搜索是时间范围，导致现在要重新写两次Columns ，table设置date，search设置dateRange；
> 
> 这个是个 bug，现在的行为才是对的，你可以render 一下
> 
> > 例子2：dateFormatter类型设置后，Columns 对应的initialValue输入是不是也应该相同的dateFormatter类型；
> 
> 这个功能还没做，做起来比较复杂
> 
> > 例子3：Columns 设置initialValue，search显示了默认值，request并没有获取默认值，只有手动点搜索，request才获取了search initialValue，理解不正确的地方，请指正
> 
> 这个最新版本修掉了，使用了 form.initialValues

没太明白你对第三个例子的解释，table 在render的时候，request是自动执行，params是没有获取search的initialValue，手动去点搜索，request获取search设置的initialValue，
> 期望table在render的时候，request执行时候有去获取search的form值

**Comment by chenshuai2144** [comment]
@David2k13 可以试试最新版本，支持了一下，用了form.getFiledValue, 不过请求发生了一点延时

**Comment by David2k13** [comment]
> @David2k13 可以试试最新版本，支持了一下，用了form.getFiledValue, 不过请求发生了一点延时

完美，例子3解决了,不过好像修复了ellipsis，fixed又坏了
![image](https://user-images.githubusercontent.com/22017991/96703165-1ebb2b80-13c5-11eb-8c2b-5aa1188a3e90.png)

**Comment by chenshuai2144** [comment]
fixed 最好设置一下宽度，不然 table 算的会有问题

**Comment by David2k13** [comment]
> fixed 最好设置一下宽度，不然 table 算的会有问题
有呀，设置了fixed的都有加width，没设置fixed和width就都挤在一起换行了

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/98797469-91a94680-2447-11eb-8c4c-685b77de4195.png)

或者配置 tableLayout:auto
