### ISSUE TITLE
🐛[BUG] ProFormDateTimePicker的属性fieldProps中配置了format不起作用

### ISSUE THREAD

**Issue by semmywong** [ant-design/pro-components#7911]
### 🐛 bug 描述

 ProFormDateTimePicker的属性fieldProps中配置了format不起作用，必须再transform里再次转换才可以，如图
### 🏞 期望结果
期望fieldProps中format可以起作用，直接输出format格式的字符串

### 💻 复现代码

```js
 <ProFormDateTimePicker
          name="toDate"
          label="日期"
          fieldProps={{ showTime: false, picker: 'date', mode: 'date', format: 'YYYY-MM-DD' }}
          transform={(value) => {
            debugger;
            return {
              toDate: value.format('YYYY-MM-DD'),
            };
          }}
        />
```

### © 版本信息

- ProComponents 版本: 
  "antd": "^5.11.1",
  "@ant-design/pro-components": "^2.6.41"

- umi 版本："@umijs/max": "^4.0.70"
- 浏览器环境
- 开发环境 [e.g. mac OS]：window 11

### 🚑 其他信息

![image](https://github.com/ant-design/pro-components/assets/67748948/3a23ef73-869d-41ab-a4ec-86b2f7f26ffd)

**Comment by fnoopv** [comment]
用ProForm的dateFormatter

**Comment by chenshuai2144** [comment]
format 只管展示 的，传给form的还是dayjs，如果要转化要用 ProForm 或者 transform

**Comment by semmywong** [comment]
> format 只管展示 的，传给form的还是dayjs，如果要转化要用 ProForm 或者 transform

我发现，我本地开发环境，form收到的dayjs的对象，但是发布生产环境，form收到 的又是格式化后的字符串。

**Comment by Emmeet** [comment]
我遇到同样的问题，线上和别人那里都好用，只有我本地的项目不好使，请问你解决了吗？

**Comment by fnoopv** [comment]
我碰到过, 建议检查安装的 `dayjs` 版本和 `antd` 用的版本是否一致, 通常是 `dayjs` 版本不一致导致的
