### ISSUE TITLE
通过 formRef 设置值，但是在二次执行后重新调用表格加载，搜索栏值有显示变化，但是请求传递的参数并不会改变，必须手动点击查询按钮才会携带上最新值

### ISSUE THREAD

**Issue by sishen654** [ant-design/pro-components#7917]
### 🐛 bug 描述

通过 formRef 设置值，但是在二次执行后重新调用表格加载，搜索栏值有显示变化，但是请求传递的参数并不会改变，必须手动点击查询按钮才会携带上最新值

![image](https://github.com/ant-design/pro-components/assets/65691266/f9fbe218-4320-496d-badb-970923bf0bba)

### 📷 复现步骤

```ts
 // orderId 通过 href 中拿
  useEffect(() => {
    formRef.current?.setFieldValue('tradeOrderId', orderId);
    actionRef?.current?.reload();
  }, [orderId]);
```

### 🏞 期望结果

参数正常

**Comment by chenshuai2144** [comment]
关于你提到的问题，当你通过 `formRef` 设置表单的值后，如果没有触发表单的提交操作，那么请求传递的参数就不会改变。这是因为设置表单的值并不会自动触发表单的提交行为。

要解决这个问题，你可以通过调用表单的 `submit` 方法来手动触发表单的提交操作，从而携带最新的值。在你想要重新加载表格并传递最新值的时候，可以在设置表单值后，调用 `submit` 方法。

示例代码如下：

```tsx
import { useRef } from 'react';
import { Form, Button } from 'antd';

const MyComponent = () => {
  const formRef = useRef(null);

  const handleSubmit = () => {
    formRef.current.submit();
  };

  return (
    <>
    <ProTable formRef={formRef}>
    </>
  );
};
```

通过上述代码，在设置表单的值后，你可以点击 "查询" 按钮来触发表单的提交操作，从而携带最新的值进行请求。这样就能解决你的问题了。
