### ISSUE TITLE
🐛[BUG] EditableProTable 新增按钮状态没有更新

### ISSUE THREAD

**Issue by a526800921** [ant-design/pro-components#7920]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

切换新增按钮的disabled的状态时，发现没有正常更新disabled状态，查看源码后发现是button被useMemo，但是button props并没有加入依赖项进行更新导致

<img width="1183" alt="企业微信截图_a6a38cdd-70d5-4288-b544-71dae889cda0" src="https://github.com/ant-design/pro-components/assets/26155877/f764b54f-e93b-45dc-ae5a-8ed0582b14bc">

### © 版本信息

- ProComponents 版本: 2.6.43
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by ONLY-yours** [comment]
https://github.com/ant-design/pro-components/commit/b314a37b2c3de7afeba877d07963403b4ebc8a3d

为了性能优化我们去掉了动态修改 Button Props 的能力
