### ISSUE TITLE
👑 [需求]Protable点击编辑时，怎么拿到回调？以及本行的数据？ 

### ISSUE THREAD

**Issue by Cyx-0** [ant-design/pro-components#7921]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
根据代码片段中的声明，您可以使用以下方法来获取回调和行数据：

1. 点击编辑时，可以使用`onChange`回调函数获取正在编辑的列和行数据。`onChange`函数的第一个参数`editableKeys`是一个包含正在编辑的列的键的数组，第二个参数`editableRows`是正在编辑的行的数组或者单个行数据。通过使用这两个参数，您可以获取到点击编辑时的回调和行数据。

示例代码如下：

```tsx
const onChange = (editableKeys: React.Key[], editableRows: DataType[] | DataType) => {
  // 在这里可以处理点击编辑时的回调和行数据
};

<Protable onChange={onChange} />
```

2. 保存行时，可以使用`onSave`回调函数获取行的键，当前修改的行的值以及原始值。`onSave`函数的第一个参数`key`是行的唯一id，第二个参数`record`是当前修改的行的值，第三个参数`originRow`是原始值。通过使用这三个参数，您可以获取保存行时的回调和行数据。

示例代码如下：

```tsx
const onSave = (
  key: RecordKey,
  record: DataType & { index?: number },
  originRow: DataType & { index?: number },
) => {
  // 在这里可以处理保存行时的回调和行数据
};

<Protable onSave={onSave} />
```

通过使用上述方法，您可以拿到回调和行数据并进行相应的处理。希望能对您有所帮助！如果还有其他问题，请随时提问。
