### ISSUE TITLE
🐛[BUG]  ModalForm 使用 request 请求数据  如果传入  form 实例  request 返回的最新数据无法实时填充到 form，展示的还是上一次的值

### ISSUE THREAD

**Issue by Gzbox** [ant-design/pro-components#7925]
"@ant-design/pro-components": "2.6.43",
    "@umijs/max": "4.0.86",
    "antd": "5.8.3",

```jsx
  const [form] = Form.useForm();

  <ModalForm
      form={form}
      open={dslModalVisible}
      modalProps={{
        bodyStyle: {
          maxHeight: '70vh',
        },
        destroyOnClose: true,
      }}
      params={{...xxxx}}
      request={async (params) => {
        const resp = await getxxxxxxxxxApi(params);
        if (resp?.resp_code === 0) {
          return {
            ...resp?.data,
            dsl: resp?.data?.dsl || undefined,
          };
        }
        return {
          dsl: undefined
        };
      }}
    >
      <Form.Item name="dsl" style={{ width: '100%' }}>
        <Input  />
      </Form.Item>
    </ModalForm>
```
如果去掉  form={form}  表现符合预期 如何加上了  表单结果填充的就不对  是上一次请求的结果  实际请求接口已经返回了最新的

**Comment by foureyeschao** [comment]
同样的问题，求解决

**Comment by chenshuai2144** [comment]
每次 ModalForm  关闭的时候销毁一下的 Modal

**Comment by leadingtw273** [comment]
所以是指定 form Ref 的狀況下 destroyOnClose 就會失效嗎~?

**Comment by codedart2018** [comment]
这bug为什么关闭了呢。现在我也严重遇到这个问题了！

**Comment by codedart2018** [comment]
不止　ModalForm DrawerForm　同样问题！

**Comment by codedart2018** [comment]
> 每次 ModalForm 关闭的时候销毁一下的 Modal

销毁也没有用，只要挂载form ref就会存在数据回显问题，查dom元素已经消失了，但数据回显还是有问题的！只是dom结构在变，但渲染的数据是有问题的

**Comment by XiaoXiaoWu98** [comment]
> 每次 ModalForm 关闭的时候销毁一下的 Modal

销毁没用我这边复现了。我知道什么原因了，我用的是Pro 里面modalForm，只要我用下面的代码`const values = Form.useWatch([], form);

  React.useEffect(() => {
    form
      .validateFields({ validateOnly: true })
      .then(() => setSubmittable(true))
      .catch(() => setSubmittable(false));
  }, [form, values]);`

**Comment by XiaoXiaoWu98** [comment]
> 每次 ModalForm 关闭的时候销毁一下的 Modal

平常是没问题，但是只要是应用form的相关hook就会有问题。很容易复现

**Comment by XiaoXiaoWu98** [comment]
> ```js
> destroyOnClose
> ```

设置destroyOnClose为true也没用去掉form.use相关hook就是正常

**Comment by a6930216745** [comment]
这个居然没解决就关闭了

**Comment by AburronKing** [comment]
给Form表单价格key={xxxx} 我这边是解决了

**Comment by codedart2018** [comment]
> 给Form表单价格key={xxxx} 我这边是解决了

给key 没用的 还是会有问题。最好是useEffects setFileds 给值，去掉init requeset获取数据
