### ISSUE TITLE
🐛[BUG] ProFormList组件，当name为数组时（例如:name={["labels", "test"]}）。嵌套组件ProFormDatePicker，表单提交数据格式异常

### ISSUE THREAD

**Issue by shaodushu** [ant-design/pro-components#7930]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProFormList组件，当name为数组时（例如:name={["labels", "test"]}）。嵌套组件ProFormDatePicker，表单提交数据格式异常

### 📷 复现步骤

[复现demo](https://codesandbox.io/s/proform-list-forked-4xrwnp?file=/App.tsx)

### 问题定位
https://github.com/ant-design/pro-components/blob/e8ca8459a669a8fb06be42d2f74ac57a787541ed/packages/utils/src/conversionMomentValue/index.ts#L159-L195

在ProFormList中name为数组时，将valueKey作为parentKey ```const valueFormatMap = get(valueTypeMap, namePath) || 'text';``` 不能正确获取父级路径

### 🏞 期望结果

表单提交时能正确获取值

### © 版本信息

- ProComponents 版本: [2.6.42]
- antd 版本: [5.11.1]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
根据你提供的问题描述，关于ProFormList组件中嵌套的ProFormDatePicker组件提交数据格式异常的问题，可以考虑以下几点进行排查：

1. 检查代码中的onChange事件是否正确处理了输入数据的改变。可以参考React的官方文档中关于受控组件的说明，确保在onChange事件中正确更新state或者其他形式的数据变量。

2. 检查数据的格式是否与后端接口要求的格式一致。可以打印或者调试查看你提交的数据的格式，再对照后端接口的要求进行比对，确保数据格式的正确性。

3. 检查ProFormList组件和ProFormDatePicker组件的API参数是否正确使用。可以查看官方文档或者查找其他使用示例，确保你所使用的API参数和用法是正确的。

如果以上的排查方法都没有解决你的问题，我建议你可以在GitHub上提一个issue，以便开发者能够更详细地了解你的问题并给予解答。你可以访问 [这个链接](https://github.com/ant-design/ant-design/issues) 提交一个新的issue，并可以使用他们提供的 [模板](https://u.ant.design/codesandbox-repro) 来提供重现问题所需要的代码和环境信息。在提交issue之前，建议你先搜索已有的issue和阅读常见问题，以免重复提问。
