### ISSUE TITLE
🐛[BUG] DragSortTable 拖拽会导致页面持续滚动

### ISSUE THREAD

**Issue by nightsu** [ant-design/pro-components#7932]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

DragSortTable 拖拽某一行至表格区域以外，当触发页面滚动以后再松开，会导致页面持续向拖拽方向滚动并且无法恢复，只有刷新页面才会停止。

### 📷 复现步骤

可以直接在[官网](https://procomponents.ant.design/components/drag-sort-table)复现。
以向上拖拽引起 bug 为例：
1.  定位到 DragSortTable 某一个行，保证当前行在页面位置可以向上滚动。
2. 点击把手向上拖拽这一行（速度快一点几乎必现），引起页面滚动，然后再松开把手即可复现。
### 🏞 期望结果

期望页面仅在拖拽期间滚动，而在拖拽结束后页面不滚动。

### 💻 复现代码

官网 demo：https://procomponents.ant.design/components/drag-sort-table

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] 2.6.42
- 浏览器环境: Edge 119、Safari 14
- 开发环境 [e.g. mac OS] macOS、windows、iPadOS

### 🚑 其他信息

录屏：

https://github.com/ant-design/pro-components/assets/22391133/6eb49754-d894-4e37-8ee8-053b95cac995

**Comment by chenshuai2144** [comment]
根据你提供的信息，我了解到你的问题是关于拖拽导致页面持续滚动的问题。

首先，antd的Table组件在v4版本中添加了一个自定义`components`属性的示例，通过替换默认的`<tbody>`实现了虚拟滚动的效果。但是很多开发者反馈说虚拟表格无法实现一些功能，比如固定列、合并行列和展开行等。你只需要使用`<Table virtual />`来启用虚拟滚动。

关于拖放导致页面持续滚动的问题，我需要更多的代码和错误信息来帮助你解决。可以提供更多相关代码和错误信息吗？这样我才能更好地理解问题并给出准确的解决方案。

**Comment by chenshuai2144** [comment]
关于你提到的问题，你可以尝试在拖拽事件的最外层阻止事件传递。具体来说，你可以在拖拽事件的容器上添加一个事件监听器，并在该监听器中阻止事件的默认行为和冒泡。下面是一个示例代码：

```javascript
const container = document.getElementById('container');

container.addEventListener('dragover', (e) => {
  e.preventDefault();
  e.stopPropagation();
  // 其他处理逻辑
});
```

在这个示例中，我们通过`addEventListener`方法给容器元素`container`添加了一个`dragover`事件监听器。在监听器的回调函数中，我们使用`e.preventDefault()`方法取消了事件的默认行为，阻止了页面滚动，并使用`e.stopPropagation()`方法停止事件的冒泡，防止事件继续传递给其他元素。

你可以将这段代码应用到你的代码中，将`container`替换为拖拽事件的最外层容器元素的引用。这样就可以阻止拖拽事件的同时阻止页面的滚动了。

希望这个回答对你有帮助！如果还有其他问题，请随时提问。

**Comment by gtgtkiss** [comment]
楼上那个真的有试过吗？scroll事件属于UI事件，而UI事件一般是不能够取消默认行为的

**Comment by YqxLzx** [comment]
> 关于你提到的问题，你可以尝试在拖拽事件的最外层阻止事件传递。具体来说，你可以在拖拽事件的容器上添加一个事件监听器，并在该监听器中阻止事件的默认行为和冒泡。下面是一个示例代码：
> 
> ```js
> const container = document.getElementById('container');
> 
> container.addEventListener('dragover', (e) => {
>   e.preventDefault();
>   e.stopPropagation();
>   // 其他处理逻辑
> });
> ```
> 
> 在这个示例中，我们通过`addEventListener`方法给容器元素`container`添加了一个`dragover`事件监听器。在监听器的回调函数中，我们使用`e.preventDefault()`方法取消了事件的默认行为，阻止了页面滚动，并使用`e.stopPropagation()`方法停止事件的冒泡，防止事件继续传递给其他元素。
> 
> 你可以将这段代码应用到你的代码中，将`container`替换为拖拽事件的最外层容器元素的引用。这样就可以阻止拖拽事件的同时阻止页面的滚动了。
> 
> 希望这个回答对你有帮助！如果还有其他问题，请随时提问。

我感觉这是直接把ai的回复粘贴过来了

**Comment by DieHunter1024** [comment]
建议可以参照https://ant.design/components/table-cn#components-table-demo-drag-sorting进行处理。目前项目需要只能暂时换成antd的表格，但是需要从根本解决问题

**Comment by undefined996** [comment]
这么就过去了, 所以还是没解决么

**Comment by DieHunter1024** [comment]
> 这么就过去了, 所以还是没解决么
拿这个先试试吧。
https://github.com/ant-design/pro-components/issues/8583
