### ISSUE TITLE
🧐[问题]现在设置persistenceType:localStorage，一打开页面就存储到浏览器了，怎么做到点击打开设置按钮调整列之后才保存浏览器？

### ISSUE THREAD

**Issue by xian107** [ant-design/pro-components#7935]
因为项目有几百个table，如果每个table的setting没设置就保存到了localStorage，就会太多了。
有没有什么方法，可以让页面默认的不存到localStorage
![image](https://github.com/ant-design/pro-components/assets/13252682/78e0a35d-2e42-4e27-9d09-fd4aa30135d2)

![image](https://github.com/ant-design/pro-components/assets/13252682/87455699-f067-4756-bb37-63c50a332ed7)

**Comment by chenshuai2144** [comment]
根据提供的代码片段和问题描述，你想要的效果是在点击打开设置按钮之后，才保存到浏览器中。

根据给出的代码片段，`proxyWithPersistant` 函数实现了将状态对象 `state` 存储到本地存储（localStorage）中。在调用`proxyWithPersistant`函数时，通过设置`type: 'localStorage'`和`key: 'count'`来指定将数据存储到localStorage中，并将数据的键(key)设置为'count'。

根据你的需求，你可以按照以下步骤来实现点击打开设置按钮之后才保存到浏览器的功能：

1. 首先，在你的应用中，你需要引入一个按钮作为设置按钮，并监听其点击事件。
2. 当点击设置按钮时，你可以通过监听事件的方式来获取到用户所调整的列的信息。
3. 将用户调整的列信息更新到 `state` 对象中。
4. 在更新了 `state` 对象后，手动调用 `localStorage.setItem` 方法将更新后的数据存储到本地存储中。

以下是一个简单的示例代码：

```ts
import { proxyWithPersistant } from 'umi';

// 定义初始的状态对象
const initialState = {
  count: 0,
};

// 使用 proxyWithPersistant 创建一个可持久化的状态对象
const state = proxyWithPersistant(initialState, {
  type: 'localStorage',
  key: 'count',
});

// 监听设置按钮的点击事件
const setButton = document.getElementById('set-button');
setButton.addEventListener('click', () => {
  // 获取用户调整的列信息
  const adjustedColumns = getAdjustedColumns();

  // 更新状态对象
  state.columns = adjustedColumns;

  // 将更新后的数据存储到本地存储中
  localStorage.setItem('count', JSON.stringify(state));
});
```

在上面的示例中，我们监听了一个 id 为 `set-button` 的按钮的点击事件。当用户点击这个按钮时，我们获取到用户调整的列信息，并将其更新到 `state` 对象中。最后，我们将更新后的数据使用 `localStorage.setItem` 方法存储到本地存储中。

请注意，上述示例中的代码只是一个简单的示例，你需要根据你的具体业务逻辑进行适当的调整。

**Comment by chenshuai2144** [comment]
参考上面的代码自己实现一下吧。

**Comment by xian107** [comment]
> ```ts
> state 
> ```
那自己用事件存储到localStorage后，怎么跟table的setting或列关联起来呢？

**Comment by xian107** [comment]
> 参考上面的代码自己实现一下吧。

那自己用事件存储到localStorage后，怎么跟table的setting或列关联起来呢？
