### ISSUE TITLE
🧐[问题]ProFormSelect 过滤搜索label值与设置不符

### ISSUE THREAD

**Issue by zyc329** [ant-design/pro-components#7938]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

我想请问下如果select框开启了过滤搜索的时候，label为什么会变成一个对象，如下图
![image](https://github.com/ant-design/pro-components/assets/51154195/cc5e4ac5-fd74-463f-8271-9d660d8e7052)

### 💻 示例代码

![image](https://github.com/ant-design/pro-components/assets/51154195/f66a7aaa-5cda-4f79-a02e-cd12605188c3)

📷 复现步骤
select框输入过滤文本，点击后，如果直接在下拉框选就正常

© 版本信息
-“@ant-design/pro-components”： “^2.6.35”，

umi4
开发环境 [e.g. mac OS]

**Comment by zyc329** [comment]
<img width="1513" alt="image" src="https://github.com/ant-design/pro-components/assets/51154195/93280f2e-adcb-4e42-8a63-f864b20cc543">
antd v5 上的是正常的

**Comment by chenshuai2144** [comment]
针对你提出的问题：

**问题：当我设置了 `Input`/`Select` 等的 `value` 时它就无法修改了。**

这个问题是因为你设置了 `value` 属性，使得输入组件成为了受控组件。受控组件的值是由父组件来控制的，当你设置了 `value` 属性后，在用户输入时，值不会发生变化，因为它会始终保持为你设定的值。要实现能够修改值的功能，你需要通过传入 `onChange` 属性来监听值的变化，并在回调函数中更新父组件的状态。

你可以参考 React 的文档 [https://zh-hans.reactjs.org/docs/forms.html#controlled-components](https://zh-hans.reactjs.org/docs/forms.html#controlled-components) 来了解更多关于受控组件的信息和使用方法。

**问题：当我动态改变 `defaultValue` 的时候它并没有生效。**

这个问题是因为 `Input`/`Select` 等输入组件的 `defaultXxxx` 属性（例如 `defaultValue`）只在组件第一次渲染时生效，而后不再改变。如果你想要动态改变默认值，你需要使用受控组件的方式，将默认值作为组件的 `value` 属性，并在需要改变默认值时，通过更新父组件的状态来触发重新渲染。

详细信息可以在 React 的文档 [https://zh-hans.reactjs.org/docs/forms.html#controlled-components](https://zh-hans.reactjs.org/docs/forms.html#controlled-components) 中找到。

希望能帮助到你！如果还有其他问题，请随时提问。

**Comment by zyc329** [comment]
> 针对你提出的问题：
> 
> **问题：当我设置了 `Input`/`Select` 等的 `value` 时它就无法修改了。**
> 
> 这个问题是因为你设置了 属性，使得输入组件成为了受控组件。受控组件的值是由父组件来控制的，当你设置了 属性后，在用户输入时，值不会发生变化，因为它会始终保持为你设定的值。要实现能够修改值的功能，你需要通过传入 属性来监听值的变化，并在回调函数中更新父组件的状态。`value``value``onChange`
> 
> 你可以参考 React 的文档 https://zh-hans.reactjs.org/docs/forms.html#controlled-components 来了解更多关于受控组件的信息和使用方法。
> 
> **问题：当我动态改变 `defaultValue` 的时候它并没有生效。**
> 
> 这个问题是因为 / 等输入组件的 属性（例如 ）只在组件第一次渲染时生效，而后不再改变。如果你想要动态改变默认值，你需要使用受控组件的方式，将默认值作为组件的 属性，并在需要改变默认值时，通过更新父组件的状态来触发重新渲染。`Input``Select``defaultXxxx``defaultValue``value`
> 
> 详细信息可以在 React 的文档 https://zh-hans.reactjs.org/docs/forms.html#controlled-components 中找到。
> 
> 希望能帮助到你！如果还有其他问题，请随时提问。

没明白这段话的意思，我是想说当开启search后，输入再点击后的onCange的option的值 label是一个对象 而antdV5 不会，我觉得这一块并不合理，我需要typeof option.label === 'string' ? option.label : option.title, 去判断而不是像上面ant v5调试时候截图那样
![image](https://github.com/ant-design/pro-components/assets/51154195/a32d3bc2-c361-4ea9-ba20-e15551756bec)
