### ISSUE TITLE
🐛[BUG]ProFormUploadButton 自定义headers属性不生效

### ISSUE THREAD

**Issue by PixelMapping** [ant-design/pro-components#794]
### 🐛 bug 描述
ProFormUploadButton 自定义headers属性不生效

### 📷 复现步骤
<Upload
            action="api/file/upload"
            listType="picture"
            className="upload-list-inline"
            name="fileList"
            headers={{
              "Authorization":localStorage.getItem('token')
            }}
          >
            <Button icon={<UploadOutlined />}>Upload</Button>
 </Upload>
 <ProFormUploadButton label="身份证" 
           name="upload" 
           action="api/file/upload" 
           headers={{
              "Authorization":localStorage.getItem('token')
            }} />

Upload组件支持自定义headers，ProFormUploadButton 自定义headers无效
### 🏞 期望结果

期望ProFormUploadButton能够支持Upload所有属性
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
用` fieldProps. headers`

```tsx
<ProFormUploadButton
  label="身份证"
  name="upload"
  action="api/file/upload"
  fieldProps={{
    headers: {
      Authorization: localStorage.getItem("token"),
    },
  }}
/>;
```

**Comment by PixelMapping** [comment]
感谢大佬
