### ISSUE TITLE
🐛[BUG][prolayout] 关于mix布局 存在的bug和优化

### ISSUE THREAD

**Issue by yangzhibin-git** [ant-design/pro-components#7940]
### 第一个bug：
<img width="1659" alt="图片" src="https://github.com/ant-design/pro-components/assets/5546391/c2924c8b-5ba5-4549-86b3-5cfefd2881c2">

### 第二个bug：
<img width="1544" alt="图片" src="https://github.com/ant-design/pro-components/assets/5546391/2958707e-2c4a-4a91-80b9-3bf74e1e9e17">

### 第三个优化：
<img width="2038" alt="图片" src="https://github.com/ant-design/pro-components/assets/5546391/8a308f87-2ea4-4a19-b47d-8069367d531f">

### © 版本信息

- ProComponents 版本: [^2.6.42]
- vite 
- 浏览器环境 firefox chrom
- 开发环境 [ mac OS]

**Comment by chenshuai2144** [comment]
这段代码主要是关于使用 Ant Design ProLayout 的布局配置和使用方法的说明。根据代码片段中的描述，ProLayout 是一个封装了常用的菜单、面包屑、页头等功能的高级布局组件，支持三种模式（side、mix、top），并且包含了菜单选中、菜单生成面包屑、自动设置页面标题的逻辑。

具体来说，你可以通过修改 `config.js` 文件来配置 ProLayout 的样式和属性，例如更改布局的主题色、导航模式、内容区域宽度等。然后，你需要将复制的配置粘贴到 `layout` 中。

另外，你还可以在路由中新增一个 `name` 字段，用于给 ProLayout 做菜单渲染使用。在 `src/layouts/index.tsx` 文件中，通过 `useAppData` 和 `useLocation` 来获取全局客户端路由和当前页面的 location 信息，并在 `ProLayout` 组件中使用这些信息来决定菜单的高亮以及点击菜单时的路由跳转。

整体来说，使用 ProLayout 可以帮助你快速搭建一个标准的中后台页面布局，减少重复的开发工作。如果你遇到了问题或者发现了bug，可以使用 Ant Design 的 GitHub Issues 页面来进行 bug 追踪和报告。

**Comment by yangzhibin-git** [comment]
@chenshuai2144  你们没有解决上面问题
