### ISSUE TITLE
antd v5报错[antd: Menu] `children` is deprecated. Please use `items` instead.

### ISSUE THREAD

**Issue by homestylew** [ant-design/pro-components#7945]
我用的children的写法，因为items无法满足我的业务要求，不能用children了吗？
`
      <Menu.Item key={item.id} className="min-w-[7.5rem] max-w-[25rem] flex px-[1.25rem] overflow-hidden justify-center items-center">
              <span>菜单项1</span>
            </Menu.Item>
`
官方的水平菜单，没法在菜单栏的后面加图标

**Comment by fnoopv** [comment]
这只是警告，不影响正常使用

**Comment by chenshuai2144** [comment]
未来会删掉的，推荐还是用 items  会好很多
