### ISSUE TITLE
求教关于EditableProTable使用renderFormItem自定义组件

### ISSUE THREAD

**Issue by Crush0916** [ant-design/pro-components#7946]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
参照官网实现的demo，我希望select选项发生改变时，另外一列的值也发生改变，但是我使用form.setFieldValue()不生效，是我哪里写错了吗，还是说EditableProTable有其他方式可以实现，求教大佬们一下
![image](https://github.com/ant-design/pro-components/assets/97590431/90e931cc-fc8b-415d-818c-ca637c84cfdc)
![image](https://github.com/ant-design/pro-components/assets/97590431/0d8b930c-b605-479e-ac01-53b1cbbd4fcf)

**Comment by akira0912** [comment]
你想要的时候一个同一行的两个输入框的联动效果吗 这样不用自定义组件吧，在fieldProps的onChange里面使用 editorFormRef.current?.setRowData?.(id1, { '字段名': undefined });

**Comment by chenshuai2144** [comment]
EditableProTable是Ant Design Pro中提供的可编辑表格组件。可以用于实现表格的增删改功能。

在使用EditableProTable时，如果想要自定义某一列的编辑组件，可以使用renderFormItem属性。renderFormItem是EditableProTable中的一个函数属性，它接收当前行数据和当前列配置作为参数，并返回一个React组件用于渲染表格单元格的编辑区域。

在代码片段中的例子中，我们可以看到在ProTable组件中定义了一个columns数组，其中的每个列配置对象都可以包含renderFormItem属性。我们可以在renderFormItem中返回我们自定义的组件，这样就可以实现对单元格的编辑区域进行自定义。

对于你提到的同一行的两个输入框的联动效果的问题，可以在renderFormItem中定义两个输入框，并通过onChange事件来实现它们的联动。具体可以参考下面的代码示例：

```tsx
const columns: ProColumns<API.CurrentUser>[] = [
  {
    title: '姓名',
    dataIndex: 'name',
    renderFormItem: (item, { record }) => {
      const { form } = item;
      const { getFieldProps, getFieldValue } = form;
      const name = getFieldValue('name');
      
      return (
        <>
          <Input {...getFieldProps('name')} />
          <Input value={name} onChange={(e) => {
            const value = e.target.value;
            form.setFieldsValue({
              name: value,
              price: value ? value * 2 : undefined,
            });
          }} />
        </>
      );
    },
  },
  {
    title: '价格',
    dataIndex: 'price',
    renderFormItem: (item, { record }) => {
      const { form } = item;
      const { getFieldProps } = form;
      
      return (
        <InputNumber {...getFieldProps('price')} />
      );
    }
  }
];
```

在上面的代码中，我们使用了Ant Design的Input和InputNumber组件来分别表示姓名和价格的输入框。在姓名输入框的onChange事件中，我们通过form.setFieldsValue方法来改变姓名和价格的值，实现了两个输入框的联动效果。

希望这个回答能够帮到你，如果还有其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
根据你提供的问题描述和示例代码，我看到你使用了 EditableProTable 组件，并希望在 select 选项发生改变时，另一列的值也跟着改变。你尝试使用 form.setFieldValue() 来实现，但没有生效。

首先，我注意到你使用了 Pro 组件库提供的组件，该组件库可能有自己的特殊用法和行为。我建议你查阅 Pro 组件库的官方文档，以了解如何正确使用 renderFormItem 自定义组件，并确保你的代码遵循官方文档的示例和要求。

其次，你可以尝试以下方法来解决你的问题：

1. 确保你在 select 组件的 onChange 事件中调用了 form.setFieldValue() 方法，并将新的值传递给它。例如：
   ```javascript
   <Select onChange={(value) => form.setFieldValue('columnName', value)}>
     ...
   </Select>
   ```
   这样，在 select 选项发生改变时，'columnName' 字段的值会更新。

2. 检查你在 EditableProTable 组件中是否正确地绑定了表单实例 form，并设置了 initialValues 属性，以确保表单的初始值正确传递给 EditableProTable 组件。

如果以上方法仍未解决你的问题，我建议你提供更多的代码和错误调试信息，以便我们更好地帮助你解决问题。
