### ISSUE TITLE
🐛[BUG]  ProTable  Added non-passive event listener to a scroll-blocking   设置=》拖动列排序 失效

### ISSUE THREAD

**Issue by wangAhStar** [ant-design/pro-components#7948]
ProTable 组件面临 Chrome 浏览器版本 119.0.6045.200（正式版本） （64 位） 中，设置=》拖动列排序 失效。但是同样在Microsoft Edge 浏览器中不存在问题，可正常拖动排序。

Chrome 浏览器控制台比 Edge 多了一份 warn ，详细信息如下

[Violation] Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See

**Comment by chenshuai2144** [comment]
根据你提供的信息，你遇到的问题似乎是在 ProTable 组件中，设置了拖动列排序，但功能失效的问题。可能是由于添加了一个非被动的事件监听器，导致滚动被阻塞。

在 ProTable 组件中，使用了 `position: sticky` 实现了固定列的效果，而 `rc-virtual-list` 组件提供了横向滚动的支持，而不需要关心固定列的实现。

如果你在设置拖动列排序时遇到问题，可能是由于某个事件监听器被添加为非被动的，导致滚动被阻塞。被动事件监听器是指不会调用 `preventDefault()` 的事件监听器。为了避免这个问题，你可以尝试修改事件监听器为被动的。

另外，在 Pro 组件中，v5.2.0 版本之后新增了 SettingDrawer 组件，可以进行动态主题的设置。你可以通过控制 `initialValues` 来控制布局的状态。

在 ProTable 组件中，通过设置 `virtual` 属性即可开启虚拟滚动能力，同时除了自定义 `components.body` 外，其他功能都能正常使用：

```tsx
<Table virtual scroll={{ x: 2000, y: 500 }} {...otherProps} />
```

总的来说，对于重型组件来说，随着时间推移，新的 BUG 修复或功能新增很容易破坏原本的性能优化。在排查问题时，可以使用官方提供的性能工具进行调试。

希望这些回答对你有帮助！如果还有其他问题，请随时提问。
