### ISSUE TITLE
pro-layout-bg-list 可以不展示吗

### ISSUE THREAD

**Issue by Yalhu** [ant-design/pro-components#7949]
### 🐛 bug 描述

pro-layout-bg-list  这个元素不知道怎么用。
现在作为子应用（有背景色）盖在主应用页面内容上面，导致主页面内容看不见了。

看源码是`Layout 的品牌配置，表现为一张背景图片`。有配置项不展示吗？
```js
{props.pure ? (
        <>{children}</>
      ) : (
        <div className={className}>
          <div className={classNames(`${proLayoutClassName}-bg-list`, hashId)}>
            {bgImgStyleList}
          </div>
          <Layout
            style={{
              minHeight: '100%',
              // hack style
              flexDirection: siderMenuDom ? 'row' : undefined,
              ...style,
            }}
          >
```

![image](https://github.com/ant-design/pro-components/assets/27722787/b9d1b9cf-32f4-4f4b-b9c4-e0a2b954f95c)

### 🏞 期望结果
不展示上面的元素。
### © 版本信息
    "@ant-design/pro-components": "^2.6.41",
    "@umijs/max": "^4.0.71",
    "antd": "^5.11.5",

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境： chrome
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
不要配置 bgLayoutImgList 就可以了

**Comment by shijunfeng** [comment]
> 为子应用（有背景色）盖在主应用页面内容上面，导致主页面内容看不见了

怎么解决的呢？在哪儿配置
