### ISSUE TITLE
👑 [需求] protable的swicth能力是否需要增强

### ISSUE THREAD

**Issue by owenchen1004** [ant-design/pro-components#7951]
### 🔩 所属模块或组件

ProTable

### 🥰 需求描述

ProTable中switch开关在表格行中只能显示“打开”或“关闭”，是否需要自定义显示文本的能力，例如可以根据switch的开关显示“成功”或“失败”？

**Comment by chenshuai2144** [comment]
可以用  filedProps  来配置
例如，假设你想要将未选中状态显示为 "Off"，那么你可以将 unCheckedChildren 属性设置为 "Off"。

```jsx
<ProFormSwitch filedProps={{ unCheckedChildren:"Off" }}/>
```

这样，当 Switch 组件未被勾选时，它会显示为 "Off"。

需要注意的是，unCheckedChildren 属性只能接受字符串类型的值，所以你只能传入文本内容，无法传入其他 React 组件。

ProTable 中是在 列里面配置

希望这个回答对你有帮助！如果还有其他问题，请随时提问。
