### ISSUE TITLE
🐛[BUG] umi/max 设置 antd colorPrimary 对 layout 无效

### ISSUE THREAD

**Issue by crazyair** [ant-design/pro-components#7953]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 📷 复现步骤
```tsx
import { defineConfig } from '@umijs/max';

export default defineConfig({
  antd: {
    theme: { token: { colorPrimary: 'red' } }, // 设置 colorPrimary: red 无法覆盖到 layout 上
  },
  access: {},
  model: {},
  initialState: {},
  request: {},
  layout: {
    title: '@umijs/max',
  },
  // theme: { colorPrimary: 'red' },
  routes: [
    {
      path: '/',
      redirect: '/home',
    },
    {
      name: '首页',
      path: '/home',
      component: './Home',
    },
    {
      name: '权限演示',
      path: '/access',
      component: './Access',
    },
    {
      name: ' CRUD 示例',
      path: '/table',
      component: './Table',
    },
  ],
  npmClient: 'yarn',
});
```

### 💻 复现代码

https://github.com/crazyair/um-max-layout-demo

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by ONLY-yours** [comment]
ProLayout 大部分的样式都是自定义的 token（和 antd 不太一样，独有的一些 token），可以看看官网的自定义token 的例子

**Comment by crazyair** [comment]
> ProLayout 大部分的样式都是自定义的 token（和 antd 不太一样，独有的一些 token），可以看看官网的自定义token 的例子

明白了，v4时期，menu 是跟随主题的，v5 后，menu 不跟随，只是黑色。


另外配置了颜色，缺覆盖不了 menu active 的颜色(鼠标点击菜单时候的颜色是灰色)，你们有空可以测试下
```ts
sider: {
                colorMenuBackground: '#fff',
                colorTextMenu: 'rgba(0, 0, 0, 0.88)',
                colorTextMenuSelected: 'red',
                colorTextMenuItemHover: 'red',
                colorBgMenuItemSelected: 'red',
                colorBgMenuItemHover: 'red',
            },
```

**Comment by ONLY-yours** [comment]
> > ProLayout 大部分的样式都是自定义的 token（和 antd 不太一样，独有的一些 token），可以看看官网的自定义token 的例子
> 
> 明白了，v4时期，menu 是跟随主题的，v5 后，menu 不跟随，只是黑色。
> 
> 另外配置了颜色，缺覆盖不了 menu active 的颜色(鼠标点击菜单时候的颜色是灰色)，你们有空可以测试下
> 
> ```ts
> sider: {
>                 colorMenuBackground: '#fff',
>                 colorTextMenu: 'rgba(0, 0, 0, 0.88)',
>                 colorTextMenuSelected: 'red',
>                 colorTextMenuItemHover: 'red',
>                 colorBgMenuItemSelected: 'red',
>                 colorBgMenuItemHover: 'red',
>             },
> ```

colorTextMenuActive 这个token试试？ 有个 menu active 的token，应该还可以用呢

**Comment by ONLY-yours** [comment]
不过确实有点复杂 哈哈哈，token 太多了

**Comment by crazyair** [comment]
确实，token 应该可以省一些。

之前没搜到 active 字眼，我的问题😅
