### ISSUE TITLE
🐛[BUG] syncToUrl在hashRouter下无法工作

### ISSUE THREAD

**Issue by andyyxw** [ant-design/pro-components#7955]
### 🐛 bug 描述

参看 https://stackoverflow.com/questions/62249185/using-search-params-with-hashrouter-from-react-router

这个问题对`syncToUrl`功能的影响还是很大的，我看已经提了几个issue了：[2279](https://github.com/ant-design/pro-components/issues/2279)、[4335](https://github.com/ant-design/pro-components/issues/4335)、[7002](https://github.com/ant-design/pro-components/issues/7002)

### 📷 复现步骤

`ProForm`开启`syncToUrl`功能

### 🏞 期望结果

兼容hashRouter

### 💻 复现代码

```js
<ProForm syncToUrl>
   ...
</ProForm>
```

### © 版本信息

- ProComponents 版本: 2.6.43
- 浏览器环境: Google Chrome Version 119.0.6045.200 (Official Build) (64-bit)
- 开发环境: windows

### 🚑 其他信息

@chenshuai2144 建议将源码中的`useUrlSearchParams`替换为`ahooks`的 [useUrlState](https://ahooks.js.org/zh-CN/hooks/use-url-state) (基于`react-router`)

**Comment by andyyxw** [comment]
目前我copy了一份`BaseForm`，使用 [useUrlState](https://ahooks.js.org/zh-CN/hooks/use-url-state) 没什么问题

**Comment by chenshuai2144** [comment]
在前端开发中，URL参数和hash路由是可以共存的。

首先，URL参数是指在URL中以`?`开头的字符串，用于传递参数给后端或前端的一种方式。例如，`https://example.com/users?id=123`中的`id=123`就是URL参数，用于传递用户的id。

而hash路由是指URL中以`#`开头的部分，用于在前端进行路由分发。例如，`https://example.com/#/users/123`中的`#/users/123`就是hash路由，代表了前端应用的路由路径。

如果你的URL里有`#`号，想要去掉它，可以使用以下方法：

- 在使用`<a>`标签进行跳转时，可以设置`href`属性为不包含`#`号的路径，例如`https://example.com/users/123`，这样就不会出现`#`号了。
- 在使用`window.location.href`或`window.location.replace()`进行跳转时，可以将`#`号后的部分去掉，例如：`window.location.href = 'https://example.com/users/123'`。

关于URL参数和hash路由共存的问题，你可以参考文档 [前端路由与服务端的结合](/zh-CN/docs/deploy#前端路由与服务端的结合)。在这个文档中，介绍了在Ant Design Pro中使用Umi框架时，可以通过配置`config/config.ts`来选择路由方式，可以选择使用`browserHistory`或`hashHistory`。

- 使用`hashHistory`时，URL会变成类似`https://example.com/#/users/123`的形式，以`#`号后的字符作为路径。
- 使用`browserHistory`时，URL会变成类似`https://example.com/users/123`的形式，直接使用路径作为URL。

需要注意的是，使用`browserHistory`时，浏览器访问始终会访问根目录下的`index.html`，因此需要服务器正确处理URL，防止出现404找不到页面的情况。

如果你没有对服务器端的控制权限，建议在配置中开启[`exportStatic

**Comment by RickieWoo** [comment]
解决了吗就关了？
