### ISSUE TITLE
🧐[问题]想问下proformselect 使用options为啥自定义搜索筛选会覆盖原来的呢？

### ISSUE THREAD

**Issue by cangsnage** [ant-design/pro-components#7956]
### 🧐 问题描述
![image](https://github.com/ant-design/pro-components/assets/25116493/ac6dd0cd-79f2-4a92-80f2-36131d8cb0e1)
使用自带的opiotns里面自己写的数组

### 💻 示例代码
  <ProFormSelect
    fieldProps={{
        showSearch:true,
        onSearch:(e)=>{
            
        }
    }}
    options=[{
        label:'测试',
        options:options
    }]
    />
如果你有解决方案，在这里清晰地阐述
-->
想问下这个有啥解决办法么？必须要自定义下拉样式么

**Comment by chenshuai2144** [comment]
`ProFormSelect` 组件的 `options` 属性是用来设置下拉选项的，而自定义搜索筛选则是通过 `filterOption` 属性来实现的。当你设置了 `filterOption` 属性时，它会覆盖默认的筛选逻辑，导致自定义的搜索筛选覆盖原来的逻辑。

要解决这个问题，你可以通过自定义的方式来实现筛选逻辑，而不是直接使用 `filterOption` 属性。你可以通过编写自己的筛选函数来实现自定义搜索筛选，然后将该函数作为 `onSearch` 属性传递给 `ProFormSelect` 组件。

这样做的好处是你完全掌控了筛选逻辑，可以根据自己的需求对选项进行筛选。在筛选函数中，你可以根据输入的搜索关键字对选项进行过滤，并返回匹配的选项。这样就可以实现自定义的搜索筛选逻辑，而不会覆盖原来的逻辑。

以下是一个示例代码：

```jsx
import { ProFormSelect } from 'antd';

const options = [
  { label: 'Option 1', value: 'option1' },
  { label: 'Option 2', value: 'option2' },
  { label: 'Option 3', value: 'option3' },
];

const filterOptions = (inputValue, option) => {
  return option.label.toLowerCase().includes(inputValue.toLowerCase());
};

const CustomSelect = () => {
  return (
    <ProFormSelect
      options={options}
      onSearch={filterOptions}
    />
  );
};
```

在上面的示例中，我们通过定义 `filterOptions` 函数来实现自定义的筛选逻辑，然后将该函数作为 `onSearch` 属性传递给 `ProFormSelect` 组件。在 `filterOptions` 函数中，我们使用 `includes` 方法来判断选项的标签是否包含搜索关键字。

这样，当你在搜索框中输入关键字时，会根据自定义的筛选逻辑进行选项的过滤和显示。同时，不会覆盖原来的筛选逻辑。
