### ISSUE TITLE
proFormSelect组件在onChange事件里把value为null的值转成0🐛[BUG]

### ISSUE THREAD

**Issue by sunshine-23-qf** [ant-design/pro-components#7957]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🏞 期望结果
正常返回null

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
对于 proFormSelect 组件在 onChange 事件里把 value 为 null 的值转成 0 的问题，你可以在 onChange 事件处理函数中添加一个判断语句，判断当 value 为 null 时，将其转换为 0。具体代码如下：

```jsx
import { Select } from 'antd';

const { Option } = Select;

// ...

<Select onChange={(value) => {
  if (value === null) {
    value = 0;
  }
  // 其他处理逻辑
}}>
  <Option value={0}>Option 0</Option>
  {/* 其他选项 */}
</Select>
```

这样，在选择选项时，当选项的值为 null 时，会自动转换为 0。注意，此方法适用于 Ant Design 的 Select 组件，其他组件可能需要使用不同的方法来处理。
