### ISSUE TITLE
🐛[BUG] ProForm组件使用trigger 属性时，使用空标签<></>包裹时，无法打开弹框 

### ISSUE THREAD

**Issue by yxf18** [ant-design/pro-components#7959]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

使用trigger 属性时，使用空标签<></>包括时，无法打开弹框

### 📷 复现步骤

![image](https://github.com/ant-design/pro-components/assets/50571024/4ab46a3b-937b-45d4-b3f1-061eaef33f00)

### 🏞 期望结果

可以打开

### 💻 复现代码

https://codesandbox.io/p/sandbox/drawer-biao-dan-forked-jynclt?file=%2FApp.tsx%3A22%2C31

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by yxf18** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [[🐛[BUG] 使用trigger 属性时，使用空标签包裹时，无法打开弹框 #7958](https://github.com/ant-design/pro-components/issues/7958)][🐛[BUG] 使用trigger 属性时，使用空标签包裹时，无法打开弹框][65%]

并不能，，，，赶快安排人工帮忙修复一下，谢谢，，，智障机器人

**Comment by fnoopv** [comment]
`Fragment` 不能添加事件，所以点击打不开，这个不是框架的问题吧。你是想实现无权限时点击的时候打不开抽屉的这个效果吗？

**Comment by yxf18** [comment]
> `Fragment` 不能添加事件，所以点击打不开，这个不是框架的问题吧。你是想实现无权限时点击的时候打不开抽屉的这个效果吗？

是的呢

**Comment by ONLY-yours** [comment]
是的，提供的 dom 要支持点击的，你一定要使用 Fragment 的话，可能受控更适合你？

**Comment by yxf18** [comment]
目前的解决方案是 <Access visible={???}><ModalForm trigger={<Button/>} /><Access/>, 期望是<ModalForm trigger={<Access visible={???}><Button/><Access/>} />
