### ISSUE TITLE
🐛[BUG]Prolist下拉展开icon的class是固定的导致在不同主题下没效果

### ISSUE THREAD

**Issue by liuxulian** [ant-design/pro-components#7962]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

![image](https://github.com/ant-design/pro-components/assets/35675025/4b8c3b29-ac99-4309-9de9-8b19ef52607a)
如上图中红色框中的部分是写死的样式，在不同主题下应该要有不同的前缀，例如 ant-pro-list 在antd5主题下可能是 antd5-pro-list

### 📷 复现步骤

切换主题更换token时必现。

### 🏞 期望结果

如果class变量的值是“antd5”，那么icon的class应该是下面这样。
.antd5-pro-list .antd5-pro-list-row-expand-icon>.anticon>svg
![image](https://github.com/ant-design/pro-components/assets/35675025/11b10b95-eed8-4500-8d71-09d8fbf6e9c1)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
根据你提供的问题描述，问题主要是关于 Prolist 下拉展开 icon 的 class 是固定的，在不同主题下没有效果。这个问题可能是由于组件的样式没有根据不同主题进行调整导致的。

要解决这个问题，你可以尝试以下几种方法：

1. 查看组件的文档：首先，你可以查看 Pro 组件的文档，看是否提供了修改主题的选项或方法。可能有一些特定的 API 可以用来调整主题相关的样式。

2. 自定义样式：如果组件没有提供修改主题的选项，你可以尝试自定义样式。你可以通过在你的代码中添加额外的 CSS 样式，覆盖原有样式，以实现在不同主题下的展示效果。

3. 使用 CSS 变量：另一种方法是使用 CSS 变量来实现主题切换。你可以在你的代码中使用 CSS 变量来定义不同主题的颜色和样式，然后在需要的地方使用这些变量。这样，在切换主题时，只需要修改 CSS 变量的值，而不需要修改具体的样式。

以上是几种可能的解决方法，具体应该根据你所使用的组件和样式的情况来确定最适合的解决方案。希望能帮到你！

**Comment by chenshuai2144** [comment]
```
 const { getPrefixCls } = useContext(ConfigProvider.ConfigContext);
  const { hashId } = useContext(ProProvider);
  const prefixCls = getPrefixCls('pro-list', customizePrefixCls);
```
原来是这样的，看看是不是 provide  重复了

**Comment by liuxulian** [comment]
> ```
>  const { getPrefixCls } = useContext(ConfigProvider.ConfigContext);
>   const { hashId } = useContext(ProProvider);
>   const prefixCls = getPrefixCls('pro-list', customizePrefixCls);
> ```
> 
> 原来是这样的，看看是不是 provide 重复了

![image](https://github.com/ant-design/pro-components/assets/35675025/763a2223-d58c-4c38-b490-4c834bf47f50)
