### ISSUE TITLE
🐛[BUG]ProTable的columns.dataIndex的值使用"nodeName"会导致组件报错，请修复

### ISSUE THREAD

**Issue by Lands-1203** [ant-design/pro-components#7965]
![image](https://github.com/ant-design/pro-components/assets/61341868/6af995e7-0c29-4886-ae87-a9c598b9b02f)

**Comment by chenshuai2144** [comment]
根据提供的代码片段，问题出现在ProTable的columns.dataIndex的值使用"nodeName"时会导致组件报错。这是因为ProTable组件是基于Ant Design的Table封装的，而Ant Design的Table组件的dataIndex属性用于指定数据源中的字段名，而不是指定数据源中的DOM节点属性。所以在这里，将dataIndex的值改为对应的字段名即可修复这个问题。

修复后的代码如下：

```tsx
const columns: ProColumns<Member>[] = [
  {
    dataIndex: 'realName',
    title: '姓名',
  },
  {
    dataIndex: 'nickName',
    title: '昵称',
  },
  {
    dataIndex: 'email',
    title: '账号',
  },
  {
    dataIndex: 'phone',
    title: '手机号',
  },
  {
    title: '操作',
    valueType: 'option',
    render: (_, record) => {
      return [<a key="edit">编辑</a>, <a key="remove">移除</a>];
    },
  },
];
```

修复后的代码中，将columns中的dataIndex的值改为对应的字段名，即'realName'、'nickName'、'email'和'phone'，这样就能正确显示表格了。
