### ISSUE TITLE
🐛[BUG] submitter render doms中的按钮的顺序与默认不一致

### ISSUE THREAD

**Issue by annilq** [ant-design/pro-components#7966]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
submitter render doms中的按钮的顺序与默认不一致
### 📷 复现步骤
默认ProForm的提交与重置按钮的排列顺序是
提交 重置
配置了submitter render的doms排列顺序是
重置 提交

### 🏞 期望结果
期待能统一顺序以保证UI统一

### 💻 复现代码

请参考官网或者下面链接
https://codesandbox.io/s/vr8hs9
https://codesandbox.io/s/xwmh7z

### © 版本信息

- ProComponents 版本:2.6.35
- umi 版本 ： umi/max 4.0.85
- 浏览器环境 :chrome
- 开发环境 [e.g. mac OS]
windows 10

**Comment by fnoopv** [comment]
这不是 BUG, 既然你用了submitter render，那如何渲染就是你自己控制了，你可以不用 `...doms` 的方式展开, 直接 `doms[0]` 这样, 第一个是重置按钮，第二个是提交按钮。或者你直接不要`doms`都行，调用 form 的 ref 自己控制提交行为

**Comment by annilq** [comment]
> 这不是 BUG, 既然你用了submitter render，那如何渲染就是你自己控制了，你可以不用 `...doms` 的方式展开, 直接 `doms[0]` 这样, 第一个是重置按钮，第二个是提交按钮。或者你直接不要`doms`都行，调用 form 的 ref 自己控制提交行为

antd首先是一个design系统,即使是自定义render也应该遵循一些设计规范

**Comment by fnoopv** [comment]
`antd` 当然，但这是 `pro-components` ....
