### ISSUE TITLE
🐛[BUG]EditableProTable删除数据靠前的行，后面的数据（写了formItemProps的rules的字段，数据消失）

### ISSUE THREAD

**Issue by AmberSanyu** [ant-design/pro-components#7967]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

```
const tableDataSource = formRef?.current?.getFieldValue(name) || []
const columns = [
  {title: '名称', dataIndex: 'agentName'},
  {title: '金额', dataIndex: 'goal', width: 140, valueType:'money', fieldProps: { min: 0 }, formItemProps: { rules: [requiredRule]}},
  {title: '描述', dataIndex: 'description', valueType:'textare'},
  {title: '备注', dataIndex: 'remark', valueType:'textare'},
  {
    title: '操作', dataIndex: 'action', valueType: 'option', render: (text, record, _, action) => {
      return <Popconfirm description="确定要删除此条数据吗？"
        onConfirm={() => {
          formRef.current?.setFieldsValue({
            [tableName]: tableDataSource.filter((item) => item.id !== record.id),
          });
        }}
        okText="确定"
        cancelText="取消"><Button size="small" type="link" danger >删除</Button></Popconfirm>
    }
  }
]
return <ProForm formRef={formRef} >
  <EditableProTable name={tableName} columns={columns} actionRef={actionRef} rowKey='id'  ...{其他配置}>
  </EditableProTable>
</ProForm>
```

### © 版本信息

- ProComponents 版本: 2.3.57
- umi 版本：4.0.70
- 浏览器环境 chrome 119
- 开发环境 win11

### 🚑 其他信息
![image](https://github.com/ant-design/pro-components/assets/18545388/d4917732-548f-4654-aea0-0e6e29958c10)
![image](https://github.com/ant-design/pro-components/assets/18545388/4dbed32b-034f-4566-b9c8-0578f1858f75)
如果去除, formItemProps: { rules: [requiredRule]}的配置，删除就没有问题

**Comment by AmberSanyu** [comment]
升级了版本后这个问题正常，但是ProConfigProvider的valueTypeMap好像失效了

**Comment by chenshuai2144** [comment]
根据提供的代码段，可以看出你遇到了EditableProTable删除靠前行的数据后，后面的数据消失的问题。这个问题可能是由于组件的渲染机制导致的。

首先，我需要说明一下，在React中，当一个组件的数据发生变化时，React会重新渲染整个组件树。这意味着如果你修改了一个父组件的状态，即使子组件的数据没有变化，React也会重新渲染所有的子组件。

对于EditableProTable组件来说，当你删除一个靠前的行时，后面的行的索引会改变，因此后面的行在重新渲染时会丢失原来的数据。这是因为EditableProTable组件没有正确更新行数据的索引。

要解决这个问题，你可以尝试在删除行之后，手动更新后面行的索引。你可以使用React提供的map函数来遍历行数据数组，然后使用索引来更新每一行的id值。具体步骤如下：

1. 在删除行时，获取被删除行的索引。
2. 使用splice函数从行数据数组中删除该索引的行。
3. 使用map函数遍历剩余的行数据数组，更新每一行的id值。
4. 更新组件的行数据数组。

这样，当组件重新渲染时，后面的行将保留原来的数据。

以下是示例代码：

```typescript
// 在删除行时调用该函数
const handleDeleteRow = (index: number) => {
  // 从行数据数组中删除该索引的行
  const updatedRows = rows.filter((_, i) => i !== index);

  // 更新后面行的id值
  const updatedRowsWithId = updatedRows.map((row, i) => ({ ...row, id: `${i + 1}` }));

  // 更新组件的行数据数组
  setRows(updatedRowsWithId);
};

return (
  <EditableProTable
    ...
    rowKey="id"
    columns={columns}
    dataSource={rows}
    ...
  />
);
```

请注意在示例代码中，更新后面行的id值时，使用了`${i + 1}`来生成新的id。这个值可以根据你的实际需求做出相应的修改。

希望这个解决方案能够帮助你解决问题！如果还有其他问题，欢迎继续提问。

**Comment by Tinyuen** [comment]
一模一样的问题，快把我搞死了，怎么解决的啊老哥

**Comment by AmberSanyu** [comment]
> 一模一样的问题，快把我搞死了，怎么解决的啊老哥 @AmberSanyu

如果你是说我一开始提交的哪个问题的话，
解决方案1 就是单独升级这个组件的版本，单独引入 
解决方案2就是上面那位回答的一样

如果你说的是我评论里面的问题的话，就不要把使用valueType的组件外面包ProConfigProvider，去抽， 直接在当前的里面去写自定义valueType

**Comment by Tinyuen** [comment]
@AmberSanyu   升级版本肯定是不现实了，回归成本太大。我的Table是放在 ProForm中使用的，我现在的做法是把表格的 rowKey字段删掉（默认用兜底的index），然后重写了“添加行”和“删除行”逻辑（不用默认自带的）。每次新增行和删除行都是直接通用大表单的formRef来set，同时重新更新 selectedRowKeys。 目前好像这样没问题了。
