### ISSUE TITLE
🧐[问题]pro-form的一些疑问

### ISSUE THREAD

**Issue by Hikarien** [ant-design/pro-components#797]
### 🧐 问题描述

1.pro-form的提交按钮可否居中，目前是靠左侧

2. 能否提供空的pro-form占位原子组件，便于长度低的input调整位置

3. 可否根据需要删除重置按钮，尤其是在pro-table的form模式中

4. 因为提交按钮的状态外部不受控，能否在提交中的时候统一给提交button设置一个loading状态，类似现在pro-table查询的loading

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/41961907/96684922-f6283700-13ae-11eb-87f7-8acb71f35492.png)

**Comment by chenshuai2144** [comment]
升级一下版本，都会有的。

**Comment by Hikarien** [comment]
@chenshuai2144  非常感谢！

**Comment by quarkcms** [comment]
@chenshuai2144 表单的按钮如何对齐
![image](https://user-images.githubusercontent.com/60868863/96950605-458c7580-151d-11eb-9c45-12c347ebed12.png)
