### ISSUE TITLE
🐛[BUG]编辑时显示的不是label是value

### ISSUE THREAD

**Issue by day-xue** [ant-design/pro-components#7971]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

<img width="522" alt="image" src="https://github.com/ant-design/pro-components/assets/95938844/98a3baa7-2323-4c5c-92fe-6649f212848d">

### 📷 复现步骤

第一次编辑时,回显的值是value
<img width="695" alt="image" src="https://github.com/ant-design/pro-components/assets/95938844/e807179d-ff01-4e80-8a6b-3d86c859c1ef">

### 🏞 期望结果

期望是 枚举对应的值

### 💻 复现代码

{
    title: '是否激活',
    dataIndex: 'asset_active_status',
    width: 100,
    valueType: 'select',
    valueEnum: {
      0: {
        text: '否',
        status: 'Error'
      },
      1: {
        text: '是',
        status: 'Success'
      }
    }
  },

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fnoopv** [comment]
```typescript
/**
 * 支持 Map 和 Record<string,any>
 *
 * @name ValueEnum 的类型
 */
export type ProSchemaValueEnumMap = Map<string | number | boolean, ProSchemaValueEnumType | ReactNode>;
export type ProSchemaValueEnumObj = Record<string, ProSchemaValueEnumType | ReactNode>;
```

你 `valueEnum` 的值用的是`object`, object的`key`的类型为`string`, 你传的数字0但匹配时是字符串"0", 用Map

**Comment by day-xue** [comment]
谢谢

**Comment by chenshuai2144** [comment]
根据你提供的信息，我理解你的问题是当你设置了Input/Select等组件的value属性时，无法修改该值。你可以尝试使用onChange事件来改变value的值。在React中，你可以通过控制组件的状态来实现这一目的。

具体来说，你可以在组件中定义一个state来保存value的值，并在onChange事件中更新这个state。然后将这个state作为value属性的值传入组件中。这样，当你修改组件的值时，会触发onChange事件并更新state的值，进而更新组件的value属性。

以下是一个示例代码，以一个Input组件为例：

```jsx
import React, { useState } from 'react';

function App() {
  const [value, setValue] = useState('');

  const handleChange = (event) => {
    setValue(event.target.value);
  };

  return (
    <input type="text" value={value} onChange={handleChange} />
  );
}
```

在这个例子中，我们使用useState来定义了一个名为value的状态，并将其初始值设置为空字符串。在onChange事件中，我们调用了handleChange函数，并通过event.target.value获取输入框的值，然后使用setValue函数来更新value的值。最后，我们将value作为value属性的值传递给input组件。

通过这样的方式，你就可以在输入框中修改value的值了。当你修改输入框的值时，会触发onChange事件，handleChange函数会更新value的值，进而更新input组件的value属性。这样，你就可以实现可编辑的效果了。

希望这个回答能帮到你！如果还有其他问题，请随时提问。
