### ISSUE TITLE
🐛[BUG] EditableProTable - 实时保存的编辑表格,表格数量超过100会出现性能问题，输入框显示出现卡顿

### ISSUE THREAD

**Issue by Snow-pear** [ant-design/pro-components#7974]
### 🐛 bug 描述
官网示例EditableProTable-实时保存的编辑表格，列表数据量越大，表单控件改变值时越卡顿。官网地址：https://procomponents.ant.design/components/editable-table#editableprotable-demo-real-time-editing

### 📷 复现步骤
https://codesandbox.io/p/sandbox/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-2dfrlm?file=%2FApp.tsx

### 🏞 期望结果
表单控件变化时不会因为列表数据量大而卡顿

### © 版本信息

- ProComponents 版本: [e.g. 2.6.42]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
<img width="1499" alt="image" src="https://github.com/ant-design/pro-components/assets/38351649/32c5966a-195b-4e29-be10-4ff564ecc931">

**Comment by tunshiyu** [comment]
我也遇到了这个问题，我这边是100行*每行10个表单，相当于同时生成1000个formitem并且form.setfieldvalues进去。然后就点什么都卡，卡的很厉害，给每个formitem加shouldupdate也没效果

**Comment by tunshiyu** [comment]
找到了一个方案，不要一上来就setEditableRowKeys，默认都是详情项，然后通过点击某一行控制单个设置为表单项。问题的源头还是可编辑的表单项太多了，这个问题得让官方的同学给方案了。

**Comment by Snow-pear** [comment]
> 找到了一个方案，不要一上来就setEditableRowKeys，默认都是详情项，然后通过点击某一行控制单个设置为表单项。问题的源头还是可编辑的表单项太多了，这个问题得让官方的同学给方案了。

明白你的意思，主要是用户不想多一步点击操作。

**Comment by tunshiyu** [comment]
any solution?

**Comment by weiblank** [comment]
同样的问题，

**Comment by chenshuai2144** [comment]
根据你的描述，你在使用 EditableProTable 这个组件时，遇到了性能问题和输入框卡顿的情况。对于这个问题，你可以采取以下措施来解决：

1. 检查数据量：首先，你可以检查你的表格中的数据量是否超过了100，如果是的话，可以考虑对数据进行分页加载，或者使用虚拟滚动来优化性能。

2. 减少监听事件：如果你的表格中有很多的监听事件，可以尝试减少监听的事件数量，或者使用防抖或节流函数来优化性能。

3. 优化渲染逻辑：检查你的渲染逻辑是否存在不必要的重复渲染或无效的渲染操作，可以通过使用 shouldComponentUpdate 或者 PureComponent 来优化渲染性能。

4. 异步处理：如果你的表格中有一些异步操作，比如远程数据请求或者复杂的数据计算，可以考虑将这些操作放在异步队列中执行，以免阻塞主线程。

5. 使用性能工具：你可以使用 React 提供的性能工具

**Comment by chenshuai2144** [comment]
问题描述中提到，在使用 EditableProTable 进行实时保存的编辑表格时，当表格数量超过100时会出现性能问题，导致输入框显示出现卡顿的情况。这个问题可能是因为表格数据量大，导致页面渲染和输入框响应速度变慢。

要解决这个问题，可以考虑以下几个方面：

1. **分页加载数据**：对于大量数据的表格，可以将数据进行分页加载，每次只加载部分数据，避免一次性加载过多数据导致性能问题。可以使用分页组件来处理数据的分页加载。

2. **虚拟滚动技术**：虚拟滚动可以实现表格只渲染当前可见区域的数据，而不是全部数据，这样可以有效减少页面渲染的负担。可以使用一些虚拟滚动的插件来实现，比如 react-virtualized 或 react-window。

3. **优化渲染逻辑**：检查代码中是否存在不必要的渲染操作，可以使用 React 的性能工具来定位到具体的渲染问题，然后对代码进行优化，减少不必要的渲染。

4. **缓存数据**：如果表格的数据是从后端获取的，可以考虑将数据进行缓存，减少后续的网络请求，提高性能。

5. **延迟加载**：对于输入框的显示，可以使用延迟加载的方式，只在需要编辑的时候才加载输入框，避免一次性加载过多输入框导致页面卡顿。

以上是一些可能的解决方案，具体还需要根据项目的具体情况来选择合适的优化方法。另外，建议使用浏览器的性能分析工具，例如 Chrome DevTools，来进行性能分析和定位性能问题的根源。
