### ISSUE TITLE
🧐[问题]为什么官网上搜索的demo都无法使用？

### ISSUE THREAD

**Issue by liu923014086** [ant-design/pro-components#7978]
此链接下的搜索都无法使用，输入搜索条件返回的table列表并没有刷新

https://procomponents.ant.design/en-US/components/table?current=1&pageSize=5&title=123

![11](https://github.com/ant-design/pro-components/assets/14088192/88d4ace2-c77a-4962-bad0-3d80776467a4)

**Comment by ONLY-yours** [comment]
如果前一次的请求参数和这一次一样，查询是不会发送第二次的，你要改动一下顶部搜索栏的请求参数

**Comment by liu923014086** [comment]
问题没有解决，不是请求参数的事。
