### ISSUE TITLE
🐛[BUG] 可编辑表格没有列指定 valueType='option' 时，调用 saveEditable 后， onSave 不会触发

### ISSUE THREAD

**Issue by linxianxi** [ant-design/pro-components#7980]
### 🐛 bug 描述

1、看代码只有 valueType 为 option 时才会调用 actionRender
<img width="514" alt="image" src="https://github.com/ant-design/pro-components/assets/47104575/da95defc-7c40-498b-a187-a302bb6772dd">
2、所以这里是空的，一些 set 操作是在 actionRender 里执行的 [(https://github.com/ant-design/pro-components/pull/6081)](https://github.com/ant-design/pro-components/blob/master/packages/utils/src/useEditableArray/index.tsx#L818)  
<img width="741" alt="image" src="https://github.com/ant-design/pro-components/assets/47104575/69e2737c-ef99-4a9b-bedf-f517aee324eb">

### 📷 复现步骤

没有 valueType 为 option 的列的情况下，执行 actionRef.current?.saveEditable，onSave 不会触发

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
没配置option 是不会注入saveEditable 的
