### ISSUE TITLE
🐛[BUG] ProLayout组件menuItemRender属性设置后菜单栏的点击事件消失

### ISSUE THREAD

**Issue by chongdongkongjian** [ant-design/pro-components#7984]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProLayout组件menuItemRender属性设置后点击跳转路由消失，而menuItemRender返回的ReactNode只是文字区的一部分，即便自己添加onClick，Menu的Padding部分点击也是不会跳转的。

### 📷 复现步骤

正常使用即可复现
### © 版本信息

- ProComponents 版本: [v2.6.17]
- umi 4
- 浏览器环境 chrome
- 开发环境 [ mac OS]

**Comment by chenshuai2144** [comment]
问题描述：在使用 ProLayout 组件的过程中，设置了 menuItemRender 属性之后，菜单栏的点击事件消失了。

原因分析：根据代码片段，可以看出 menuItemRender 方法是用来定制菜单的渲染逻辑的。在使用 ProLayout 组件时，通过这个方法可以控制菜单项的渲染方式，包括菜单项的点击事件。然而，当前的代码中并没有对点击事件进行处理，导致点击菜单项时没有触发任何操作。

解决方案：在 menuItemRender 方法中添加点击事件的处理逻辑。

具体做法是，在 if (menuItemProps.path && location.pathname !== menuItemProps.path) 的条件语句中，给 Link 组件添加 onClick 属性，并在回调函数中添加对应的路由跳转逻辑。

修改后的代码如下：

```tsx
import { ProLayout } from '@ant-design/pro-layout';
import { Link, Outlet, useAppData, useLocation, history } from 'umi';

export default function Layout() {
  const { clientRoutes } = useAppData();
  const location = useLocation();
  return (
    <ProLayout
      route={clientRoutes[0]}
      location={location}
      title="Umi x Ant Design"
      menuItemRender={(menuItemProps, defaultDom) => {
        if (menuItemProps.isUrl || menuItemProps.children) {
          return defaultDom;
        }
        if (menuItemProps.path && location.pathname !== menuItemProps.path) {
          return (
            <Link
              to={menuItemProps.path}
              target={menuItemProps.target}
              onClick={() => {
                history.push(menuItemProps.path); // 添加路由跳转逻辑
              }}
            >
              {defaultDom}
            </Link>
          );
        }
        return defaultDom;
      }}
    >
      <Outlet />
    </ProLayout>
  );
}
```

通过以上的修改，即可在点击菜单项时触发对应的路由跳转操作。希望能对你有所帮助！
