### ISSUE TITLE
🧐[问题]我想问下 编辑表格valueType: 'digit'为啥会出现样式的问题呢

### ISSUE THREAD

**Issue by cangsnage** [ant-design/pro-components#7985]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by chenshuai2144** [comment]
在前端编辑表格中，当设置`valueType: 'digit'`时可能会出现样式问题的原因通常是由于数字对齐的问题导致的。在表格中，为了方便用户快速对比数值大小，建议将所有数值取相同的有效位数，并且右对齐显示。如果不同数值的有效位数不一致，或者没有进行右对齐显示，就会导致样式问题的出现。

解决这个问题的方法是通过调整样式来实现数字的对齐和展示。可以使用CSS中的`text-align`属性来设置数字的对齐方式为右对齐。例如，在表格中的金额列设置`text-align: right;`即可实现右对齐显示。同时，可以通过设置合适的字体大小和间距来保持数字的对齐和美观。

另外，还可以使用一些前端框架或组件库提供的特定属性或方法来实现数字对齐。具体的实现方法要根据你使用的具体框架或组件库来确定，可以查看对应的文档或源码来获取更详细的信息。

总结来说，设置`valueType: 'digit'`可能会出现样式问题主要是由于数字对齐的问题导致的，通过调整样式或使用特定的属性或方法来实现数字的对齐和展示可以解决这个问题。
