### ISSUE TITLE
🧐[问题] 想咨询如何给ProForm下面的组件添加className

### ISSUE THREAD

**Issue by gujiwuqing** [ant-design/pro-components#7989]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

因为一些业务需求，我需要给ProForm下面的组件添加className，如图所示，form.item是可以加，但是ProFormText添加className不生效，我想请问如何才能给ProForm下面的组件添加className
<img width="1223" alt="image" src="https://github.com/ant-design/pro-components/assets/44566835/59775a31-0545-4a07-a9c4-8e81895e49d3">

**Comment by chenshuai2144** [comment]
要给ProForm下面的组件添加className，可以通过以下步骤实现：

1. 首先，确定你想要添加className的具体组件。

2. 根据你给出的代码片段，我们可以看到代码中引入了组件`UserInfo`，这个组件使用了`@connect`装饰器将`user` model与组件进行连接。

3. 在组件的`render`方法中，我们可以看到`user` model的数据通过`this.props.user.name`来访问，这里可以确定我们要给的组件是`UserInfo`。

4. 在给`UserInfo`组件添加className之前，首先需要明确你想要添加的className是什么，可以是任何你希望的类名。

5. 接下来，在`UserInfo`组件的`render`方法中，在`<div>`标签上添加`className`属性，并赋予你想要添加的类名，如下所示：

```javascript
render() {
  return <div className="your-class-name">{this.props.user.name}</div>;
}
```

注意将`your-class-name`替换为你想要的实际类名。

通过以上步骤，你就可以给`ProForm`下面的`UserInfo`组件添加className了。记得在添加className之前，确保你已经正确引入了相关的组件和model。
