### ISSUE TITLE
🧐[问题] 在表格中新增第二筆資料後都會默認帶出上一筆的內容，有辦法不帶默認值嗎？

### ISSUE THREAD

**Issue by kevintsai1202** [ant-design/pro-components#7990]
### 🧐 问题描述
在表格中新增第二筆資料後都會默認帶出上一筆的內容，又辦法不帶默認值嗎？
因為我有個排序欄位想每次自動+1，可是帶默認值後我的+1都會被蓋掉

### 💻 示例代码
```
<Space className="tools">
        <Button
          type="primary"
          key="newrow"
          onClick={() => {
            console.log("listItems",listItems, listItems.length)
            
            actionRef.current?.addEditRecord?.({
              cliId: "NEW",
              orderBy: listItems.length + 1,
            });
          }}
          icon={<PlusOutlined />}
        >
          新增下拉選項
        </Button>
      </Space>

      <DragSortTable<DataSourceType>
        rowKey="cliId"
        scroll={{
          x: 500,
        }}
        actionRef={actionRef}
        headerTitle={listNode.clnId + "-" + listNode.name}
        columns={columns}
        search={false}
        pagination={false}
        dragSortKey="orderBy"
        request={getListItems}
        onDragSortEnd={handleDragSort}
        editable={{
          form,
          editableKeys,
          onSave: (key, row, oldRow,) => {
            console.log("key", key)
            console.log("row", row)
            console.log("oldRow", oldRow)
            if (key === "NEW") {
              return createListItem(row);
            }
            else { 
              return updateListItem(row);
            }
          },
          // onDelete(key, row) {
          //   return deleteFormNumber(key.toString());
          // },
          onChange: setEditableRowKeys,
          actionRender: (row, config, dom) => [
            [
              <Button key="save">{dom.save}</Button>,
              <Button key="cancel">{dom.cancel}</Button>,
            ],
          ],
        }}
      />
```

### 🚑 其他信息
加第一筆資料排序正確+1
![圖片](https://github.com/ant-design/pro-components/assets/12706683/874314cf-0234-4265-907e-79ff91e9796c)

加第二筆資料就會帶出上一筆內容
![圖片](https://github.com/ant-design/pro-components/assets/12706683/b2e006a5-cd05-46f2-aa69-25f524681c15)

**Comment by fnoopv** [comment]
设置以下 `recordCreatorProps` ?
```
{
     position: 'bottom',
     record: () => ({key: '', value: ''}),
}
```

**Comment by kevintsai1202** [comment]
> 设置一下 `recordCreatorProps` ?
> 
> ```
> {
>      position: 'bottom',
>      record: () => ({key: '', value: ''}),
> }
> ```

ProTable 沒有 recordCreatorProps 可設定，不過我在addEditRecord時加上空字串，按第一次依然會出現上一筆增加的內容，按第二次才會是空值

actionRef.current?.addEditRecord?.(
              {
                clnId: "NEW",
                name: '',
                description: '',
              },
              {
                position: 'top'
              }
            );

**Comment by fnoopv** [comment]
似乎没有更好的方法了, 只能自己封装。 或者把这个分为两个操作，默认使用 `DragSortTable` 表格可以排序，然后给出一个编辑按钮，点击后把表格换为`EditableProTable`

**Comment by kevintsai1202** [comment]
> 似乎没有更好的方法了, 只能自己封装。 或者把这个分为两个操作，默认使用 `DragSortTable` 表格可以排序，然后给出一个编辑按钮，点击后把表格换为`EditableProTable`

真的沒辦法我也只能另外放輸入欄位來新增了，只是在demo測試都沒問題，自己寫的卻有cache資料的問題實在很怪

**Comment by chenshuai2144** [comment]
在你的表格中新增第二条数据后，默认会带出上一条数据的内容，但你希望不要使用默认值。这个问题可能是由于你使用了重复的 name原因导致的。要解决这个问题，你可以检查组件的文档或者相关设置，看是否有关于默认值的配置选项。如果没有的话，你可以尝试手动清除 initvalues上一条数据的内容，然后再新增第二条数据。具体的实现方式可能因组件而异，所以建议你查阅组件的文档或者在相关论坛上寻求帮助，以获得更具体的指导。

**Comment by kevintsai1202** [comment]
> 在你的表格中新增第二条数据后，默认会带出上一条数据的内容，但你希望不要使用默认值。这个问题可能是由于你使用了重复的 name原因导致的。要解决这个问题，你可以检查组件的文档或者相关设置，看是否有关于默认值的配置选项。如果没有的话，你可以尝试手动清除 initvalues上一条数据的内容，然后再新增第二条数据。具体的实现方式可能因组件而异，所以建议你查阅组件的文档或者在相关论坛上寻求帮助，以获得更具体的指导。

请问重复的name是哪个部分??

**Comment by chenshuai2144** [comment]
可以试试设置一个合适的每次不一样的 rowkey
