### ISSUE TITLE
Pro components website is not fully internationalized

### ISSUE THREAD

**Issue by stefann01** [ant-design/pro-components#7992]
Please update https://procomponents.ant.design/en-US to be fully in English instead of Chinese.

**Comment by ONLY-yours** [comment]
looks like WaterMark StaticsCard CheckCard these three components was not fully english？ any else？

**Comment by chenshuai2144** [comment]
Pro组件网站尚未完全国际化。您可以通过使用umi插件[@umijs/plugin-locale](https://github.com/umijs/@umijs/plugin-locale)来实现全球化的功能。详情请参考[国际化](/zh-CN/docs/i18n/)页面。

如果您需要参考国际化项目示例，可以查看[Ant Design Pro国际化文档](https://pro.ant.design/docs/i18n-cn)。

如果您想要将组件的默认语言切换回中文，可以尝试使用[ConfigProvider](/components/config-provider-cn#components-config-provider-demo-locale)组件来包裹您的应用。

如果日期组件的国际化仍未生效，请配置`dayjs.locale('zh-cn')`并检查您本地的dayjs版本和antd依赖的dayjs版本是否一致。

至于英文文档的问题，根据相关issue的回复，英文文档将在未来几个月内进行翻译。您可以跟踪[ant-design/ant-design-pro#54](https://github.com/ant-design/ant-design-pro/issues/54#issuecomment-340804479)和[ant-design-pro/issues/120](https://github.com/ant-design/ant-design-pro/issues/120)获取更多详情。

**Comment by stefann01** [comment]
> Pro组件网站尚未完全国际化。您可以通过使用umi插件[@umijs/plugin-locale](https://github.com/umijs/@umijs/plugin-locale)来实现全球化的功能。详情请参考[国际化](/zh-CN/docs/i18n/)页面。
> 
> 如果您需要参考国际化项目示例，可以查看[Ant Design Pro国际化文档](https://pro.ant.design/docs/i18n-cn)。
> 
> 如果您想要将组件的默认语言切换回中文，可以尝试使用[ConfigProvider](/components/config-provider-cn#components-config-provider-demo-locale)组件来包裹您的应用。
> 
> 如果日期组件的国际化仍未生效，请配置`dayjs.locale('zh-cn')`并检查您本地的dayjs版本和antd依赖的dayjs版本是否一致。
> 
> 至于英文文档的问题，根据相关issue的回复，英文文档将在未来几个月内进行翻译。您可以跟踪[ant-design/ant-design-pro#54](https://github.com/ant-design/ant-design-pro/issues/54#issuecomment-340804479)和[ant-design-pro/issues/120](https://github.com/ant-design/ant-design-pro/issues/120)获取更多详情。

It would be better for the community if comments were in English too!

**Comment by stefann01** [comment]
I think there are still some places:
![image](https://github.com/ant-design/pro-components/assets/30937067/c8daf7da-ac5f-4e72-8fc7-38e64499ff90)
