### ISSUE TITLE
🧐[问题] 防止Prolayout的内容卸载

### ISSUE THREAD

**Issue by tanhuazh** [ant-design/pro-components#7993]
有没有什么方法可以防止Prolayout的内容卸载。

比如一个页面的控件有滚动的位置，切换之后滚动的位置还可以保持住。

**Comment by LengYXin** [comment]
我理解不是在Prolayout做。你可以自己使用React-Ruuter 实现

**Comment by chenshuai2144** [comment]
问题：如何防止Prolayout的内容卸载？

回答：要防止ProLayout的内容卸载，可以按照以下步骤进行配置：

1. 在 `config.js` 中添加 `disableRedirectHoist: true` 的配置，如下所示：

```tsx
export const config = defineConfig({
  layout: {
    ...
    disableRedirectHoist: true,
    ...
  },
});
```

这个配置是针对使用 umijs 框架引起的问题，它可以防止在页面重定向时，重新加载页面布局组件（如 BasicLayout）。

2. 在构建时，由于无法使用 dom，有些配置可能需要在运行时进行配置。可以在 `src/app.tsx` 文件中，通过 export 一个 `layout` 方法来进行配置，如下所示：

```tsx
import React from 'react';
import { RunTimeLayoutConfig } from 'umi';
import { BasicLayoutProps, Settings as LayoutSettings } from '@ant-design/pro-layout';

export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  return {
    ...
    // 在这里进行其他配置
    ...
  };
};
```

通过使用 `layout` 方法，可以将动态数据放入 `initialState` 中，并与其结合使用。每次 `initialState` 变化都会触发更新。

这样就可以防止ProLayout的内容卸载了。

希望能对你有所帮助！如有更多问题，请随时提问。

**Comment by chenshuai2144** [comment]
离屏渲染会有性能问题 ，要自己实现一下
