### ISSUE TITLE
antd的tabs嵌套proTable切换选项卡会导致表格抖动

### ISSUE THREAD

**Issue by daifuyang** [ant-design/pro-components#7996]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/cha-xun-biao-ge-forked-txx93v?file=%2FTable.tsx%3A158%2C26)

### Steps to reproduce

依次点击切换tab选项卡，会感觉到表格工具栏明显的抖动

### What is expected?

不抖动

### What is actually happening?

页面抖动

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18.2.0 |
| System | macOS |
| Browser | chrome(120.0.6099.71) |

**Comment by chenshuai2144** [comment]
在antd中，当Tabs和ProTable嵌套使用时，切换选项卡可能会导致表格抖动的问题。这是由于antd内置了一些组件交互动效，而这些动效可能会影响页面的交互性能。

要解决这个问题，可以禁用动画效果。在代码片段中，可以看到在ConfigProvider组件中设置了theme的token属性，将motion属性设置为false，即可禁用动画效果。

```
<ConfigProvider
  theme={{
    token: {
      motion: false,
    },
  }}
>
  {nodes}
</ConfigProvider>
```

通过将motion属性设置为false，可以禁用动画效果，从而解决表格抖动的问题。
