### ISSUE TITLE
🐛[BUG]FooterToolbar组件在切换页面后，还是占据底部空间

### ISSUE THREAD

**Issue by sinaper1** [ant-design/pro-components#7999]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
![image](https://github.com/ant-design/pro-components/assets/30372708/b3f7e68a-caa6-4d59-b8f1-2474deacba8e)
![image](https://github.com/ant-design/pro-components/assets/30372708/f739b4d6-11b1-4c61-a8d5-0f78769f0793)

在ProForm的submitter中使用FooterToolbar（如下图一），切换到没使用ProForm和FooterToolbar组件的页面，底部空间还是会被FooterToolbar组件原来的div占据（如下图二）。

### 🏞 期望结果

希望切换到没使用FooterToolbar组件时，把占据底部空间的元素也一并去掉。

### 🚑 其他信息
![image](https://github.com/ant-design/pro-components/assets/30372708/d1209350-acc2-4c23-8ae0-91b9942d5eab)
![image](https://github.com/ant-design/pro-components/assets/30372708/1f5df540-0321-4c8d-b3a4-2eac2a5c6917)

**Comment by chenshuai2144** [comment]
这个是基于context 的，是不是同时有两份 ProLaytou 引入了

**Comment by chenshuai2144** [comment]
从代码片段中可以看出，问题是关于FooterToolbar组件在切换页面后仍然占据底部空间的问题。这可能是由于组件在切换页面时没有正确销毁或隐藏导致的。

解决这个问题的方法是在页面切换时，手动隐藏或销毁FooterToolbar组件。可以通过监听页面切换事件，在事件回调函数中隐藏或销毁FooterToolbar组件。

具体的实现方式取决于所使用的框架或库。一般来说，可以通过以下几个步骤来解决问题：

1. 在页面组件中，引入FooterToolbar组件并设置一个状态变量来控制组件的显示与隐藏。

2. 在页面组件的生命周期方法中，监听页面切换事件（或路由变化事件）。

3. 在事件回调函数中，根据页面切换的条件，设置FooterToolbar组件的显示与隐藏。

以下是一个示例代码片段，展示了如何使用React Hooks和React Router来解决这个问题：

```jsx
import React, { useState, useEffect } from 'react';
import { Switch, Route, useHistory } from 'react-router-dom';
import FooterToolbar from 'path/to/FooterToolbar';

const App = () => {
  const [showFooter, setShowFooter] = useState(true);
  const history = useHistory();

  useEffect(() => {
    const unlisten = history.listen(() => {
      setShowFooter(false); // 页面切换时隐藏FooterToolbar组件
    });

    return () => {
      unlisten(); // 组件销毁时取消监听事件
    };
  }, [history]);

  return (
    <div>
      <Switch>
        <Route path="/page1">
          {/* 页面1的内容 */}
        </Route>
        <Route path="/page2">
          {/* 页面2的内容 */}
        </Route>
      </Switch>

      {showFooter && <FooterToolbar />}
    </div>
  );
};

export default App;
```

这个示例代码中，通过useState来定义了一个showFooter状态变量，用于控制FooterToolbar组件的显示与隐藏。在useEffect中，通过监听history对象的事件来控制showFooter状态变量的变化。当页面切换时，将showFooter状态变量设置为false，从而隐藏FooterToolbar组件。在return中，根据showFooter的值来决定是否渲染FooterToolbar组件。

当你使用这个示例代码或根据它进行修改时，请确保正确导入所需的依赖项，并将路径/to/FooterToolbar替换为实际的FooterToolbar组件路径。另外，如果你使用的是其他路由库或框架，需要相应地修改示例代码。

**Comment by sinaper1** [comment]
这个问题确实是组件在切换页面时没有正确销毁导致的，具体使用情况是类似两个tab页面，然后一个tab页面有FooterToolbar组件，一个tab组件没有FooterToolbar组件，切换页面时组件没有正确销毁，然后发现是一个ClassName为ant-pro-layout-has-footer的div占据了底部的高度。我这边采取的方法是监听ClassName：ant-pro-footer-bar的高度是否为0，然后在div上添加一个新的ClassName从而强制把ClassName：ant-pro-layout-has-footer的height和margin-block-start设置为0。然后我看源码发现是有一个名为hasFooterToolbar的useState控制这个占位div的显示的，后续会考虑把这个hasFooterToolbar变成公有属性，让用户可以自行控制这个div的显示？

**Comment by chenshuai2144** [comment]
这个难度有点大， Tabs 里面尽量保证只有一个 Toolbar  不然还要监控当前的Toolbar 是否展示。
