### ISSUE TITLE
🐛[BUG] ProLayout 中的onPageChange方法 在切换页面的时候没有触发

### ISSUE THREAD

**Issue by AllenPan03** [ant-design/pro-components#8002]
### 🐛 bug 描述

ProLayout 中的onPageChange方法 在切换页面的时候没有触发，主要是为了在切换页面的时候更新location的值，确保菜单栏、面包屑等属性自动更新展示

### 📷 复现步骤

从列表页(/list)跳转到详情页(/list/detail)的时候，没有走进onPageChange方法里

### 🏞 期望结果
走进onPageChange方法里

### 💻 复现代码
routes配置如下：
```
{
    path: '/list',
    name: '订单',
    component: 'OrderManage',
  },
  {
    path: '/list/detail',
    name: '订单详情',
    component: 'OrderManage/Detail',
    hideInMenu: true,
  },
```

```
 <ProLayout
         onPageChange={()=>{ setPathname(locaotion.pathname)///当页面切换时走进}}
         location={{ pathname }} 
          {...defaultSettings}
        >
          <Outlet />
        </ProLayout>
```

### © 版本信息

- ProComponents 版本: 2.6.43
- umi 版本 ：4.0.89
- 浏览器环境
- 开发环境mac OS

**Comment by chenshuai2144** [comment]
```
useEffect(() => {
    props.onPageChange?.(props.location);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [location.pathname, location.pathname?.search]);
```

源码是这样的，目测是是你传入的pathname 没改变

**Comment by AllenPan03** [comment]
> ```
> useEffect(() => {
>     props.onPageChange?.(props.location);
>     // eslint-disable-next-line react-hooks/exhaustive-deps
>   }, [location.pathname, location.pathname?.search]);
> ```
> 
> 源码是这样的，目测是是你传入的pathname 没改变

我用的是umi中history.push（history路由模式）的方式实现的路由跳转，这种情况在useEffect中确实监听不到，我得自己加个history.listen才行，不知道笔者能否加个基于UMI这种路由跳转方式的兼容？

**Comment by ccimage** [comment]
我也遇到这个问题  /user/login切换到/user/loginSuccess没有触发onPageChange
但是切换到/welcome或者/admin就能触发
同样的操作，都是浏览器输入地址或者使用history.push
path判断难道不包括最后一层吗
