### ISSUE TITLE
🐛[BUG] EditableProTable中valueType是select时，addonAfter、addonBefore属性不生效

### ISSUE THREAD

**Issue by cyc2016** [ant-design/pro-components#8005]
### 🐛 bug 描述

在`EditableProTable`的`columns`里，当`valueType`为`select`时，在`fieldProps`或`formItemProps`中设置`addonAfter`、`addonBefore`均不生效

### 💻 复现代码

```jsx
const columns = useMemo(
  () =>
    [
      {
        title: '测试选择',
        valueType: 'select',
        dataIndex: 's1',
        fieldProps: {
          addonAfter: 'affter',
          addonBefore: 'before',
          options: [
            {
              label: '1',
              value: 1,
            },
            {
              label: '2',
              value: 2,
            },
            {
              label: '3',
              value: 3,
            },
          ],
        },
        formItemProps:{
          addonAfter: 'affter',
          addonBefore: 'before',
        }
      },
      {
        title: '操作',
        valueType: 'option',
        width: 200,
        render: (text, record, _, action) => [
          <a
            key="editable"
            onClick={() => {
              action?.startEditable?.(record.id);
            }}
          >
            编辑
          </a>,
        ],
      },
    ],
  [],
);

const data = [{id: 1, s1: 1}];

<EditableProTable rowKey="id" columns={columns } value={data} />
```

![微信截图_20231221112829](https://github.com/ant-design/pro-components/assets/16891228/1a452fd0-5d4a-4d52-a571-042a466aca0e)

### © 版本信息

- ProComponents 版本: [2.6.28]
- umi 版本: [4.0.83]

**Comment by chenshuai2144** [comment]
根据你提供的信息，你遇到的问题是在EditableProTable组件中，当valueType设置为select时，addonAfter和addonBefore属性不生效，同时无法修改输入框的值。

对于第一个问题，当你设置了Input/Select等的value时，它就无法修改了。你可以尝试使用onChange来改变value的值。你可以参考React的文档中关于受控组件的部分，了解如何通过onChange来改变输入框的值。

对于第二个问题，当你动态改变defaultValue时，它并没有生效。Input/Select等的defaultXxxx属性(例如defaultValue)只在组件第一次渲染时生效，后续的改变不会影响默认值。这是React的规范，请参考React的文档中关于受控组件的部分。

关于页内编辑的示例，可以使用单击编辑的方式来实现。在普通的浏览模式下，不区分可编辑行和不可编辑行。当鼠标悬停时，指针变为手型，编辑区域底色变黄，同时出现"Tooltips"提示单击编辑。当鼠标点击后，出现输入框、确定、取消表单元素，并将光标定位在输入框中。

对于单字段行内编辑，当易读性比易编辑性更重要时，可以使用单击编辑的方式。在可编辑行附近出现文字链/图标，在点击编辑后，会出现输入框、确定和取消表单元素，并将光标定位在输入框中。

对于多字段行内编辑，编辑模式需要在不破坏整体性的前提下扩大空间，以容纳输入框等表单元素。在表格中切换到编辑模式时，需要保证每列的不跳动。

关于行列组合，你可以查看虚拟列表的示例来体验。此外，你还可以参考Pro组件中的SettingDrawer，它在v5.2.0之后内置了，可以通过控制initialValues来控制布局状态，同时提供了动态主题的功能。

希望以上回答能够解决你的问题！如果还有其他疑问，请随时提问。

**Comment by chenshuai2144** [comment]
EditableProTable 里面应该都不支持 addonAfter、addonBefore
