### ISSUE TITLE
🐛[BUG]Table.EXPAND_COLUMN not working

### ISSUE THREAD

**Issue by UnkAtreus** [ant-design/pro-components#8006]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

Expand icon not change position when using Table.EXPAND_COLUMN in columns. Im using ProColumns.

### 📷 复现步骤

const columns: ProColumns<IProjectColumn>[] = [
    {
      title: 'ID',
      key: 'id',
      dataIndex: ['element', 'id'],
      hideInTable: true,
    },
    {
      title: 'Product line',
      key: 'surveyPrograms',
      dataIndex: ['element', 'availableDocumentsTypes'],
      render: (_, record) => {
        return record.element.availableDocumentsTypes
          .map((program) => program.name)
          .join(', ');
      },
    },
    Table.EXPAND_COLUMN,
    {
      title: 'Total',
      key: 'total',
      dataIndex: ['total'],
    },
    {
      title: 'Status',
      key: 'status',
      dataIndex: ['status', 'name'],
    },
    {
      title: 'Current',
      key: 'current',
      dataIndex: ['current'],
    },
    ]

### 🏞 期望结果

It should have expand icon between Product line and total

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0] lastest version
- Nextjs 14

**Comment by chenshuai2144** [comment]
根据你提供的信息，我们无法直接确定问题所在。这段文本似乎是一篇关于某个版本的更新日志，其中也提到了修复了一些问题，但没有提到 "Table.EXPAND_COLUMN not working" 这个具体的问题。

如果你遇到了 "Table.EXPAND_COLUMN not working" 的问题，可以尝试以下几个步骤来解决：

1. 确保你使用的是最新版本的 Ant Design 组件库。你可以通过更新或升级相关的依赖来确保使用最新版本。

2. 检查你的代码是否正确地使用了 Table 组件的 `expandable` 属性。`expandable` 属性用于配置表格是否可展开以及展开的相关行为。你需要确保已正确地设置了 `expandable` 属性，并且相关的列配置也是正确的。

3. 检查你的代码是否有其他可能导致展开功能失效的问题。可能的原因包括但不限于：事件处理函数的错误、数据格式不正确、CSS 样式冲突等。你可以通过调试工具（如浏览器的开发者工具）来查看是否有报错信息或异常情况。

4. 如果以上步骤都没有解决问题，你可以尝试查看 Ant Design 的官方文档或 GitHub 仓库中是否有相关的问题报告或解决方案。你也可以在 Ant Design 的开发者社区中提问，寻求其他开发者的帮助和建议。

希望以上的回答对你有帮助，如果你有其他问题，可以随时提问。
