### ISSUE TITLE
👑 [需求]LightFilter+ProFormSelect，选中之后，下拉框需要自动消失。

### ISSUE THREAD

**Issue by gb853940223** [ant-design/pro-components#8009]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

属组件：LightFilter+ProFormSelect

### 🥰 需求描述

如果单选，每选中一个，期望下拉项自动消失，就像是Select一样

### 🚑 其他信息

![image](https://github.com/ant-design/pro-components/assets/24557533/c2e1477f-c5b3-429f-91c8-73d1d1e7c054)

**Comment by chenshuai2144** [comment]
根据你描述的问题，你希望在选择下拉框选项后，下拉框能自动关闭。根据你提供的代码和情况，可能是由于组件版本的问题导致的。如果你使用的是3.11.0及以上版本，该问题应该已经解决。如果你仍然在使用旧版本，可以尝试在 `<Select>` 组件中添加 `getPopupContainer={trigger => trigger.parentElement}` 来在弹出层中渲染组件，或者使用其他的 `getXxxxContainer` 参数。另外，如果你使用的是Pro自带的组件，Pro v5.2.0之后内置了SettingDrawer组件，你可以通过对 `initialValues` 的控制来调整布局的状态。可以参考相关 issue：[#3487](https://github.com/ant-design/ant-design/issues/3487) [#3438](https://github.com/ant-design/ant-design/issues/3438)。希望这些解决方法能帮到你！
