### ISSUE TITLE
👑 [需求]希望Columns列属性Search添加一个例子

### ISSUE THREAD

**Issue by zhengdongzhe** [ant-design/pro-components#801]
### 🥰 需求描述
更新最近版ProTable 之后，控制台出现这样的Warning(如下图),

### 🧐 解决方案
希望文档中增加一个关于Search的列子。如何替代hideInSearch

感谢！

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/40757625/96692608-cf6efe00-13b8-11eb-9e28-cfe85894f4dd.png)

**Comment by chenshuai2144** [comment]
`search:false`, demo 中有用法
