### ISSUE TITLE
[BUG] FooterToolbar extra and children props are in incorrect positions

### ISSUE THREAD

**Issue by gsccheng** [ant-design/pro-components#8010]
For the `FooterToolbar` component, the `extra` props implementation appears to be incorrect. For example:
```
<FooterToolbar extra="Some extra content">
  Some Children
</FooterToolbar>
```
would result in `Some extra content` being rendered to the left:
```
<div class="ant-pro-footer-bar-left css-dev-only-do-not-override-1s9mbwn">Some extra content</div>
```
while `Some Children` will be rendered to the right:
```
<div class="ant-pro-footer-bar-right css-dev-only-do-not-override-1s9mbwn">Some Children</div>
```
According to the [docs](https://procomponents.ant.design/en-US/components/page-container#//), for the `extra` prop:

> The extra content area, located to the right of content

I am using `@ant-design/pro-components` version 2.6.43.

**Comment by chenshuai2144** [comment]
这个问题的错误信息是 "FooterToolbar的extra和children属性位置不正确"。根据给出的代码，我推测你可能在使用Ant Design的FooterToolbar组件时遇到了这个问题。

问题可能出现在你使用FooterToolbar组件时传递的props中，特别是extra和children属性。根据错误信息，这两个属性的位置可能被放置到了错误的位置。

解决这个问题的方法是将extra和children属性放置在正确的位置。根据Ant Design的文档，FooterToolbar组件会将extra属性放置在右侧，将children属性放置在左侧。

你可以尝试修改你的代码，将extra和children属性放置在正确的位置。例如，将extra属性放置在FooterToolbar组件的右侧，将children属性放置在左侧。

如果问题还未解决，请提供更多的代码片段或详细描述，以便我能够更好地帮助你解决这个问题。
