### ISSUE TITLE
🧐EditableProTable 使用renderFormItem 返回 ProFormList，不能正确绑定值

### ISSUE THREAD

**Issue by yudc13** [ant-design/pro-components#8013]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🚑 其他信息

版本：
<img width="347" alt="image" src="https://github.com/ant-design/pro-components/assets/76470486/7155d02d-60a7-4d62-9f14-d6f9e79893a9">

<img width="831" alt="image" src="https://github.com/ant-design/pro-components/assets/76470486/d25af56b-d620-4792-b64f-eb3774d1fb1c">

**Comment by chenshuai2144** [comment]
根据提供的代码片段，我看到问题出在 `EditableProTable` 组件的 `renderFormItem` 中返回的 `ProFormList` 组件上。如果你在 `ProFormList` 的 `render` 属性中直接使用 `Input`/`Select` 等组件，并且给它们设置了 `value`，那么它们将成为受控组件，无法通过用户输入更改值。为了解决这个问题，你可以使用 `onChange` 属性来监听值的变化，并在回调函数中更新数据。

这是一个示例，演示了如何在 `ProFormList` 中使用 `Input` 组件并使其可编辑：

```tsx
<ProFormList name="members" initialValue={memberList}>
  {(fields, { add, remove }) => (
    <>
      {fields.map((field, index) => (
        <ProFormItem
          name={[field.name, 'realName']}
          label="姓名"
          initialValue={field.realName}
          key={field.key}
        >
          <Input
            value={field.realName}
            onChange={(e) => {
              fields[index].realName = e.target.value;
            }}
          />
        </ProFormItem>
      ))}
      <Button onClick={() => add()}>新增</Button>
    </>
  )}
</ProFormList>
```

上面的代码中，我们使用了 `ProFormList` 组件来渲染一个可编辑的成员列表。在 `render` 属性中，我们通过 `fields` 数组来遍历每个成员，并在每个成员的 `ProFormItem` 中使用 `Input` 组件。我们将 `ProFormItem` 的 `name` 属性设置为 `[field.name, 'realName']`，这样可以正确绑定每个输入框的值。然后，我们设置 `Input` 的 `value` 属性为 `field.realName`，并在 `onChange` 回调函数中更新 `field.realName` 的值。

通过这种方式，输入框的值将与 `memberList` 数组中对应成员的 `realName` 属性保持同步，从而解决了无法正确绑定值的问题。你可以根据需要修改其他字段的渲染方式，以确保所有字段的值都能正确绑定。
