### ISSUE TITLE
🧐[问题] 为什么renderFormItem用 if(!val) 不能联动，用if(val=="") 就可以联动？

### ISSUE THREAD

**Issue by ahuigo** [ant-design/pro-components#8015]
### 🧐 问题描述

为什么下面的代码  if (!val) { return null; } // 不联动
用if(val=="") 就可以联动？

### 💻 示例代码
https://codesandbox.io/p/sandbox/vigorous-bohr-pvy2s7

```
renderFormItem: (item, { type, defaultRender, ...rest }, form) => {
        const val = form.getFieldValue('user');
        // if (!val) { return null; } // 不联动
        if (val == "") { return null; } //联动
        return <Input {...rest} />;
 },
 ```

**Comment by chenshuai2144** [comment]
关于第一个问题，`if(!val)` 和`if(val=="")` 的区别在于，`if(!val)` 判断的是 `val` 是不是 falsy 值（包括 `null`、`undefined`、`''`、`0` 等），而 `if(val=="")` 判断的是 `val` 是不是空字符串。所以当你使用 `if(!val)` 来判断时，当 `val` 为 `0` 或者空字符串时，条件判断也会为真，从而无法实现联动效果。而当你使用 `if(val=="")` 来判断时，只有当 `val` 是空字符串时，条件判断才会为真，可以联动。

关于第二个问题，`defaultValue` 是在组件第一次渲染时生效的，而如果你要动态改变其值，应该使用 `value` 属性来控制，通过改变 `value` 的值来达到动态改变的效果。详情请参考 React 的文档中关于 [受控组件](https://zh-hans.reactjs.org/docs/forms.html#controlled-components) 的说明。

**Comment by ahuigo** [comment]
@chenshuai2144 感谢。不过没有解决我的疑惑。
1. 这里的val其实只有一个类型，也就是字符串。无论是`if(!val)`还是 `if(val=="")` 结果是一样的。
2. 按你的受控组件的说法，为什么 renderFormItem 这个回调函数，为什么`if(val=="")` 会变受控，``if(!val)``变非受控呢？
