### ISSUE TITLE
🐛[BUG] antd-pro 6.0打包后再谷歌58  85 等版本皆有兼容问题

### ISSUE THREAD

**Issue by zhibo59** [ant-design/pro-components#8019]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

项目打包后再谷歌58版本中无法正常加载，报错如下，
![image](https://github.com/ant-design/pro-components/assets/9378984/7a1b3b02-9659-4b88-8bb6-dad3a13d49b9)

再谷歌85内核下可以正常加载，但是css样式有问题，导致页面无法正常浏览，效果如下：
![image](https://github.com/ant-design/pro-components/assets/9378984/5fe8e266-53ea-4214-bdb4-e1e5ffe52610)

新版浏览器没有问题可以正常加载浏览
![image](https://github.com/ant-design/pro-components/assets/9378984/8d715ad8-a45e-447b-8bdd-c967c182fe8b)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 ：@umijs/max": "^4.0.52"
- 浏览器环境 chrome：59.0.3071.109&86.0.4240.198
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
问题描述：在低版本浏览器上，使用 Ant Design v5 的样式在动态主题中使用 `:where` 选择器不生效。

解决方案：Ant Design v5 为了降低 CSS-in-JS 的哈希值优先级，使用了 `:where` 选择器。然而，旧版本的浏览器（如 IE 11、360 浏览器等）不支持 `:where` 选择器。为了解决这个问题，你可以使用 `@ant-design/cssinjs` 的 `StyleProvider` 组件来去除降权操作，使样式在旧版浏览器上生效。

具体的步骤如下：
1. 阅读 Ant Design v5 的 [兼容性调整](https://ant.design/docs/react/customize-theme-cn#%E5%85%BC%E5%AE%B9%E6%80%A7%E8%B0%83%E6%95%B4) 文档，了解如何处理兼容性问题。
2. 参考动态主题文档的 [兼容旧版浏览器](https://ant.design/docs/react/compatible-style-cn) 部分，了解如何在动态主题中处理旧版浏览器的兼容性。

如果你在使用 Ant Design v5 发现了 bug，最好的办法是通过他们提供的 [issue 小助手](http://new-issue.ant.design) 来提 issue，同时使用他们提供的 [模板](https://u.ant.design/codesandbox-repro) 提供重现 bug 的例子。在提 issue 之前，请确保已经搜索过已有的 issue 和阅读了他们的 [常见问题](https://ant.design/docs/react/faq)。

希望以上解答对你有帮助！如果还有其他问题，请随时提问。
