### ISSUE TITLE
🧐[问题] 使用 modal 包裹 ProTable(type=form) 时，如何自定义 （重置，提交）这两个按钮

### ISSUE THREAD

**Issue by ChenWeihua123** [ant-design/pro-components#802]
### 🧐 问题描述
optionRender 也无效 实在找不到办法了
看文档没有看到，issue 也没找到，所以才过来提问，求大佬指教下。。

**Comment by heylear** [comment]
同问， ProForm 可以通过 submitter 来定义 submitButtonProps 实现提交按钮的loading等效果；但是ProTable中type=form时无法透传submitter;

**Comment by chenshuai2144** [comment]
form.xxx 支持 ProForm 的任何配置。

**Comment by ChenWeihua123** [comment]
@chenshuai2144 感谢帅哥

**Comment by heylear** [comment]
> form.xxx 支持 ProForm 的任何配置。
        可能我没有表述清楚，请看下例: 
         <ProTable<DataItem, DataItem>
            type="form"
            form={{
              requiredMark: false,
              layout: 'horizontal',
              submitter: {...} // 这样通不过ts语法检查的
            }}
            ...
          />

组件: ProTable 版本: 2.9.11  此版本下上例中是form对象是透传给Form的，配置不了submitter的，至少ts里没有没有定义;

**Comment by jaryway** [comment]
@heylear 
```js
<ProTable<IWarehouse, IWarehouse>
          form={
            {
              initialValues: formValues as any,
              // submitter: false,
              submitter: {
                searchConfig: { resetText: translate('取消'), submitText: translate('保存') },
                submitButtonProps: { loading: submitting },
                resetButtonProps: {
                  onClick: () => {
                    handleModalVisible(false);
                    setFormValues({});
                  },
                },
              },
            } as any
          }
          onSubmit={(value) => saveOrUpdateUser(value)}
          onReset={() => {
            handleModalVisible(false);
          }}
          key='id'
          rowKey='id'
          type='form'
          columns={columns}
        />
```

**Comment by aweiu** [comment]
> > form.xxx 支持 ProForm 的任何配置。
> > 可能我没有表述清楚，请看下例:
> > <ProTable<DataItem, DataItem>
> > type="form"
> > form={{
> > requiredMark: false,
> > layout: 'horizontal',
> > submitter: {...} // 这样通不过ts语法检查的
> > }}
> > ...
> > />
> 
> 组件: ProTable 版本: 2.9.11 此版本下上例中是form对象是透传给Form的，配置不了submitter的，至少ts里没有没有定义;

![image](https://user-images.githubusercontent.com/15623620/99348197-f5ae8d80-28d3-11eb-9f07-83ec07f588f3.png)
类型声明的确有问题 @chenshuai2144
