### ISSUE TITLE
🐛[BUG] ProFormTreeSelect 组件 readonly 模式显示错误

### ISSUE THREAD

**Issue by doveq** [ant-design/pro-components#8020]
### 🐛 bug 描述
ProFormTreeSelect 组件 readonly 模式显示错误，现在显示的数据的 value 字段, 期望显示数据的 title 字段。

### 📷 复现步骤
见下面代码

### 🏞 期望结果
期望显示数据的 title 字段。

### 💻 复现代码
```

let categories_data = [
    {
        "id": 18,
        "pId": 0,
        "title": "新2222",
        "value": 18
    },
    {
        "id": 17,
        "pId": 0,
        "title": "新111",
        "value": 17
    },
    {
        "id": 21,
        "pId": 17,
        "title": "文化生活",
        "value": 21
    },
    {
        "id": 19,
        "pId": 18,
        "title": "嘿嘿嘿",
        "value": 19
    },
    {
        "id": 20,
        "pId": 19,
        "title": "咕咕咕咕咕",
        "value": 20
    },
    {
        "id": 22,
        "pId": 21,
        "title": "哇哈哈哈",
        "value": 22
    }
];

<ProForm readonly>
    <ProFormTreeSelect
        name="categories_id"
        label="分类"
        rules={[{ required: true, message: '请选择' }]}
        fieldProps={{
          treeDataSimpleMode: true,
          treeData: categories_data,
          treeCheckable: true,
          showCheckedStrategy: TreeSelect.SHOW_PARENT,
        }}
      />
<ProForm>


```
### © 版本信息

- ProComponents 版本:  @ant-design/pro-components@2.6.43
- umi 版本: 无
- 浏览器环境: chrome 120.0.6099.130
- 开发环境: Linux 

### 🚑 其他信息
正常表单显示：
![微信截图_20231227132525](https://github.com/ant-design/pro-components/assets/8486761/8eabda1b-6960-4a32-8b67-5ceeb315d9b6)

readonly 模式显示：
![微信截图_20231227132439](https://github.com/ant-design/pro-components/assets/8486761/33651aba-263d-4f1a-88ba-fb527d02884a)

**Comment by chenshuai2144** [comment]
### 🐛 bug 描述
ProFormTreeSelect 组件 readonly 模式显示错误，现在显示的数据的 value 字段, 期望显示数据的 title 字段。

### 📷 复现步骤
见下面代码

### 🏞 期望结果
期望显示数据的 title 字段。

### 💻 复现代码
```

let categories_data = [
    {
        "id": 18,
        "pId": 0,
        "title": "新2222",
        "value": 18
    },
    {
        "id": 17,
        "pId": 0,
        "title": "新111",
        "value": 17
    },
    {
        "id": 21,
        "pId": 17,
        "title": "文化生活",
        "value": 21
    },
    {
        "id": 19,
        "pId": 18,
        "title": "嘿嘿嘿",
        "value": 19
    },
    {
        "id": 20,
        "pId": 19,
        "title": "咕咕咕咕咕",
        "value": 20
    },
    {
        "id": 22,
        "pId": 21,
        "title": "哇哈哈哈",
        "value": 22
    }
];

<ProForm readonly>
    <ProFormTreeSelect
        name="categories_id"
        label="分类"
        rules={[{ required: true, message: '请选择' }]}
        fieldProps={{
          treeDataSimpleMode: true,
          treeData: categories_data,
          treeCheckable: true,
          showCheckedStrategy: TreeSelect.SHOW_PARENT,
        }}
      />
<ProForm>


```
### © 版本信息

- ProComponents 版本:  @ant-design/pro-components@2.6.43
- umi 版本: 无
- 浏览器环境: chrome 120.0.6099.130
- 开发环境: Linux 

### 🚑 其他信息
正常表单显示：
![微信截图_20231227132525](https://github.com/ant-design/pro-components/assets/8486761/8eabda1b-6960-4a32-8b67-5ceeb315d9b6)

readonly 模式显示：
![微信截图_20231227132439](https://github.com/ant-design/pro-components/assets/8486761/33651aba-263d-4f1a-88ba-fb527d02884a)

**Comment by doveq** [comment]
这个是不是回复错了，把其他问题的回复写到了这里？

**Comment by dalianmiaodll** [comment]
fieldProps={{  
    fieldNames: {  
      label: 'title',  // 指定 title 作为显示字段  
      value: 'value'  
    }  
  }}  需要添加这个属性能正常显示
