### ISSUE TITLE
🐛[BUG] ProFormCaptcha 切换为英文是，获取验证码按钮语言还是显示中文

### ISSUE THREAD

**Issue by Orange-Yellow** [ant-design/pro-components#8027]
### 🐛 bug 描述
![image](https://github.com/ant-design/pro-components/assets/40858423/6ed7c18e-9e92-4eee-8834-d404ad3e0c1a)

### © 版本信息

- ProComponents 版本: [2.6.12]
- umi 版本
- 浏览器环境
- 开发环境 [ubuntu]

**Comment by chenshuai2144** [comment]
这个是可以自己配置的，默认没做 

欢迎你提个 pr

**Comment by Orange-Yellow** [comment]
后续可以提pr。但是这个自己配置如何使用，默认button 没有提供按钮文本的props
