### ISSUE TITLE
🐛[BUG] Pro-layout 6.5.6 菜单空白

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#803]
### 🐛 bug 描述

Pro-layout 6.5.6 菜单空白

**Comment by JoeeeeeWu** [comment]
6.5.8同样有这个问题，我的菜单是异步请求拿回来的，貌似只会加载一次菜单.....

**Comment by JoeeeeeWu** [comment]
回退到6.5.6了，害

**Comment by daifuyang** [comment]
同，6.4.8也是！menuDataRender不再次触发！是不是dva的问题？

**Comment by JoeeeeeWu** [comment]
> 同，6.4.8也是！menuDataRender不再次触发！是不是dva的问题？

不是dva的问题，我是没有有dva的，我是单纯用了这个组件而已，应该是组件本身有问题，可能是为了性能考虑只执行一次menuDataRender而导致了这个问题，指定版本"@ant-design/pro-layout": "6.5.5"用吧

**Comment by JoeeeeeWu** [comment]
https://github.com/ant-design/pro-components/commit/febb505ee6a4b5b6a15c70f94cc3b47fa6f568b0#diff-41ba823706ed42ad32ebeaad59d39689b9233b9a8c0fad5d36f0c0aa634fd9bb 看这个提交

**Comment by JoeeeeeWu** [comment]
或者其它的解决办法可以这样子，如果是loading中，展示一个loading的状态，就不要展示prolayout，等到拉取到数据并设置好menu的数据了，loading为false，再展示prolayout

**Comment by chenshuai2144** [comment]
```tsx
menu={{
    loading,
}}
menuDataRender={() => menuData}
```

menu 支持了loading，可以用这个loading 来触发重新渲染

**Comment by daifuyang** [comment]
不行，根本用不了

**Comment by hihuangwei** [comment]
> 不行，根本用不了

antd pro   需要移除 defaultSettings.ts 文件的

`  menu: {
    locale: true,
  },
`

@chenshuai2144 添加后TS报 `TS2783: 'menu' is specified more than once, so this usage will be overwritten.`

**Comment by daifuyang** [comment]
> > 不行，根本用不了
> 
> antd pro 需要移除 defaultSettings.ts 文件的
> 
> ` menu: { locale: true, },`
> 
> @chenshuai2144 添加后TS报 `TS2783: 'menu' is specified more than once, so this usage will be overwritten.`

我试过了，还是不行！loading效果是有了！菜单还是空！并且setstate只触发第一次！

**Comment by hihuangwei** [comment]
> > > 不行，根本用不了
> > 
> > 
> > antd pro 需要移除 defaultSettings.ts 文件的
> > ` menu: { locale: true, },`
> > @chenshuai2144 添加后TS报 `TS2783: 'menu' is specified more than once, so this usage will be overwritten.`
> 
> 我试过了，还是不行！loading效果是有了！菜单还是空！并且setstate只触发第一次！

````
/**
 * Ant Design Pro v4 use `@ant-design/pro-layout` to handle Layout.
 * You can view component api by:
 * https://github.com/ant-design/ant-design-pro-layout
 */
import ProLayout, {
  MenuDataItem,
  BasicLayoutProps as ProLayoutProps,
  Settings,
} from '@ant-design/pro-layout';
import React, { useEffect, useMemo, useRef } from 'react';
import { Link, useIntl, connect, Dispatch, history } from 'umi';
import Authorized from '@/utils/Authorized';
import RightContent from '@/components/GlobalHeader/RightContent';
import { ConnectState } from '@/models/connect';
import { getMatchMenu } from '@umijs/route-utils';
import Exception403 from '@/pages/exception/403';
import {
  createFromIconfontCN,
  HomeOutlined,
  ClusterOutlined,
  SettingOutlined,
  FileOutlined,
  AppstoreOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ShopOutlined,
} from '@ant-design/icons';
import logo from '../assets/logo.svg';
import defaultSettings from '../../config/defaultSettings';

const noMatch = <Exception403 />;
export interface BasicLayoutProps extends ProLayoutProps {
  breadcrumbNameMap: {
    [path: string]: MenuDataItem;
  };
  route: ProLayoutProps['route'] & {
    authority: string[];
  };
  settings: Settings;
  dispatch: Dispatch;
  loading?: boolean;
  menuData: MenuDataItem[];
}
// export type BasicLayoutContext = { [K in 'location']: BasicLayoutProps[K] } & {
//   breadcrumbNameMap: {
//     [path: string]: MenuDataItem;
//   };
// };
/**
 * use Authorized check all menu item
 */

// const menuDataRender = (menuList: MenuDataItem[]): MenuDataItem[] =>
//   menuList.map((item) => {
//     const localItem = { ...item, children: item.children ? menuDataRender(item.children) : [] };
//     return Authorized.check(item.authority, localItem, null) as MenuDataItem;
//   });

const IconFont = createFromIconfontCN({
  scriptUrl: defaultSettings.iconfontUrl,
});

const IconMap = {
  home: <HomeOutlined />,
  file: <FileOutlined />,
  team: <TeamOutlined />,
  shop: <ShopOutlined />,
  cluster: <ClusterOutlined />,
  setting: <SettingOutlined />,
  appstore: <AppstoreOutlined />,
  thunderbolt: <ThunderboltOutlined />,
  school: <IconFont type="icon-school" />,
  wxwork: <IconFont type="icon-wxwork" />,
  wechat: <IconFont type="icon-wechat" />,
  wxmini: <IconFont type="icon-wxmini" />,
};

const BasicLayout: React.FC<BasicLayoutProps> = (props) => {
  const {
    dispatch,
    children,
    settings,
    location = {
      pathname: '/',
    },
    loading,
    menuData,
  } = props;

  const menuDataRef = useRef<MenuDataItem[]>([]);

  useEffect(() => {
    if (dispatch) {
      dispatch({
        type: 'user/fetchCurrent',
      });
      dispatch({
        type: 'platform/getSwitch',
      });
      dispatch({
        type: 'menu/fetchCurrent',
      });
    }
  }, []);
  /**
   * init variables
   */

  const handleMenuCollapse = (payload: boolean): void => {
    if (dispatch) {
      dispatch({
        type: 'global/changeLayoutCollapsed',
        payload,
      });
    }
  }; // get children authority

  // get children authority
  const authorized = useMemo(
    () =>
      getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
        authority: undefined,
      },
    [location.pathname],
  );

  const { formatMessage } = useIntl();

  const loopMenuItem = (menus: MenuDataItem[]): MenuDataItem[] =>
    // eslint-disable-next-line @typescript-eslint/no-shadow
    menus.map(({ icon, children, ...item }) => ({
      ...item,
      icon: icon && IconMap[icon as string],
      children: children && loopMenuItem(children),
    }));

  return (
    <ProLayout
      logo={logo}
      // @ts-ignore
      menu={{ locale: true, loading }}
      breakpoint="xxl"
      formatMessage={formatMessage}
      onCollapse={handleMenuCollapse}
      onMenuHeaderClick={() => history.push('/')}
      menuItemRender={(menuItemProps, defaultDom) => {
        if (menuItemProps.isUrl || menuItemProps.children || !menuItemProps.path) {
          return defaultDom;
        }

        return <Link to={menuItemProps.path}>{defaultDom}</Link>;
      }}
      breadcrumbRender={(routers = []) => [
        {
          path: '/',
          breadcrumbName: formatMessage({ id: 'menu.home' }),
        },
        ...routers,
      ]}
      itemRender={(route, params, routes, paths) => {
        const first = routes.indexOf(route) === 0;
        return first ? (
          <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
        ) : (
          <span>{route.breadcrumbName}</span>
        );
      }}
      menuRender={(_, dom) => (!loading && menuData.length > 0 ? dom : false)}
      menuDataRender={() => loopMenuItem(menuData)}
      // menuDataRender={menuDataRender}
      rightContentRender={() => <RightContent />}
      postMenuData={(menuDataItem) => {
        menuDataRef.current = menuDataItem || [];
        return menuDataItem || [];
      }}
      {...props}
      {...settings}
    >
      <Authorized authority={authorized!.authority} noMatch={noMatch}>
        {children}
      </Authorized>
    </ProLayout>
  );
};

export default connect(({ global, settings, loading, menu }: ConnectState) => ({
  collapsed: global.collapsed,
  settings,
  menuData: menu.menuData,
  loading: loading.models.menu,
}))(BasicLayout);

````
参考下

**Comment by daifuyang** [comment]
> > > > 不行，根本用不了
> > > 
> > > 
> > > antd pro 需要移除 defaultSettings.ts 文件的
> > > ` menu: { locale: true, },`
> > > @chenshuai2144 添加后TS报 `TS2783: 'menu' is specified more than once, so this usage will be overwritten.`
> > 
> > 
> > 我试过了，还是不行！loading效果是有了！菜单还是空！并且setstate只触发第一次！
> 
> ```
> /**
>  * Ant Design Pro v4 use `@ant-design/pro-layout` to handle Layout.
>  * You can view component api by:
>  * https://github.com/ant-design/ant-design-pro-layout
>  */
> import ProLayout, {
>   MenuDataItem,
>   BasicLayoutProps as ProLayoutProps,
>   Settings,
> } from '@ant-design/pro-layout';
> import React, { useEffect, useMemo, useRef } from 'react';
> import { Link, useIntl, connect, Dispatch, history } from 'umi';
> import Authorized from '@/utils/Authorized';
> import RightContent from '@/components/GlobalHeader/RightContent';
> import { ConnectState } from '@/models/connect';
> import { getMatchMenu } from '@umijs/route-utils';
> import Exception403 from '@/pages/exception/403';
> import {
>   createFromIconfontCN,
>   HomeOutlined,
>   ClusterOutlined,
>   SettingOutlined,
>   FileOutlined,
>   AppstoreOutlined,
>   TeamOutlined,
>   ThunderboltOutlined,
>   ShopOutlined,
> } from '@ant-design/icons';
> import logo from '../assets/logo.svg';
> import defaultSettings from '../../config/defaultSettings';
> 
> const noMatch = <Exception403 />;
> export interface BasicLayoutProps extends ProLayoutProps {
>   breadcrumbNameMap: {
>     [path: string]: MenuDataItem;
>   };
>   route: ProLayoutProps['route'] & {
>     authority: string[];
>   };
>   settings: Settings;
>   dispatch: Dispatch;
>   loading?: boolean;
>   menuData: MenuDataItem[];
> }
> // export type BasicLayoutContext = { [K in 'location']: BasicLayoutProps[K] } & {
> //   breadcrumbNameMap: {
> //     [path: string]: MenuDataItem;
> //   };
> // };
> /**
>  * use Authorized check all menu item
>  */
> 
> // const menuDataRender = (menuList: MenuDataItem[]): MenuDataItem[] =>
> //   menuList.map((item) => {
> //     const localItem = { ...item, children: item.children ? menuDataRender(item.children) : [] };
> //     return Authorized.check(item.authority, localItem, null) as MenuDataItem;
> //   });
> 
> const IconFont = createFromIconfontCN({
>   scriptUrl: defaultSettings.iconfontUrl,
> });
> 
> const IconMap = {
>   home: <HomeOutlined />,
>   file: <FileOutlined />,
>   team: <TeamOutlined />,
>   shop: <ShopOutlined />,
>   cluster: <ClusterOutlined />,
>   setting: <SettingOutlined />,
>   appstore: <AppstoreOutlined />,
>   thunderbolt: <ThunderboltOutlined />,
>   school: <IconFont type="icon-school" />,
>   wxwork: <IconFont type="icon-wxwork" />,
>   wechat: <IconFont type="icon-wechat" />,
>   wxmini: <IconFont type="icon-wxmini" />,
> };
> 
> const BasicLayout: React.FC<BasicLayoutProps> = (props) => {
>   const {
>     dispatch,
>     children,
>     settings,
>     location = {
>       pathname: '/',
>     },
>     loading,
>     menuData,
>   } = props;
> 
>   const menuDataRef = useRef<MenuDataItem[]>([]);
> 
>   useEffect(() => {
>     if (dispatch) {
>       dispatch({
>         type: 'user/fetchCurrent',
>       });
>       dispatch({
>         type: 'platform/getSwitch',
>       });
>       dispatch({
>         type: 'menu/fetchCurrent',
>       });
>     }
>   }, []);
>   /**
>    * init variables
>    */
> 
>   const handleMenuCollapse = (payload: boolean): void => {
>     if (dispatch) {
>       dispatch({
>         type: 'global/changeLayoutCollapsed',
>         payload,
>       });
>     }
>   }; // get children authority
> 
>   // get children authority
>   const authorized = useMemo(
>     () =>
>       getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
>         authority: undefined,
>       },
>     [location.pathname],
>   );
> 
>   const { formatMessage } = useIntl();
> 
>   const loopMenuItem = (menus: MenuDataItem[]): MenuDataItem[] =>
>     // eslint-disable-next-line @typescript-eslint/no-shadow
>     menus.map(({ icon, children, ...item }) => ({
>       ...item,
>       icon: icon && IconMap[icon as string],
>       children: children && loopMenuItem(children),
>     }));
> 
>   return (
>     <ProLayout
>       logo={logo}
>       // @ts-ignore
>       menu={{ locale: true, loading }}
>       breakpoint="xxl"
>       formatMessage={formatMessage}
>       onCollapse={handleMenuCollapse}
>       onMenuHeaderClick={() => history.push('/')}
>       menuItemRender={(menuItemProps, defaultDom) => {
>         if (menuItemProps.isUrl || menuItemProps.children || !menuItemProps.path) {
>           return defaultDom;
>         }
> 
>         return <Link to={menuItemProps.path}>{defaultDom}</Link>;
>       }}
>       breadcrumbRender={(routers = []) => [
>         {
>           path: '/',
>           breadcrumbName: formatMessage({ id: 'menu.home' }),
>         },
>         ...routers,
>       ]}
>       itemRender={(route, params, routes, paths) => {
>         const first = routes.indexOf(route) === 0;
>         return first ? (
>           <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
>         ) : (
>           <span>{route.breadcrumbName}</span>
>         );
>       }}
>       menuRender={(_, dom) => (!loading && menuData.length > 0 ? dom : false)}
>       menuDataRender={() => loopMenuItem(menuData)}
>       // menuDataRender={menuDataRender}
>       rightContentRender={() => <RightContent />}
>       postMenuData={(menuDataItem) => {
>         menuDataRef.current = menuDataItem || [];
>         return menuDataItem || [];
>       }}
>       {...props}
>       {...settings}
>     >
>       <Authorized authority={authorized!.authority} noMatch={noMatch}>
>         {children}
>       </Authorized>
>     </ProLayout>
>   );
> };
> 
> export default connect(({ global, settings, loading, menu }: ConnectState) => ({
>   collapsed: global.collapsed,
>   settings,
>   menuData: menu.menuData,
>   loading: loading.models.menu,
> }))(BasicLayout);
> ```
> 
> 参考下

可以了！必须使用dva的model！为啥我直接setState不行呢？

**Comment by chenshuai2144** [comment]
> TS2783: 'menu' is specified more than once, so this usage will be overwritten.

menu 放到最后面，不然会重置掉

**Comment by qingfengmy** [comment]
我需要主动触发菜单的重新渲染，在不刷新页面的情况下，menuDataRender如何才能重新执行？

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/advanced-menu-cn

写了篇文章

**Comment by free-pan** [comment]
我也遇到类似问题。我的情况是动态菜单，菜单数据从服务器加载, 当加载到菜单数据之后，左侧菜单未显示。后来我看了pro-layout的源码, 发现是`getMenuData`那未重新计算最新的菜单(因为入参未改变，所以用的是缓存结果)

```
// pro-layout的BasicLayout.tsx

....
const [menuInfoData, setMenuInfoData] = useMergedState<{
    breadcrumb?: Record<string, MenuDataItem>;
    breadcrumbMap?: Map<string, MenuDataItem>;
    menuData?: MenuDataItem[];
  }>(() => getMenuData(route?.routes || [], menu, formatMessage, menuDataRender));
....
```

发现了原因，是因为入参未改变，所以使用了缓存，那么只要入参与上一次不同，自然就会重新计算了。而getMenuData有3个参数, 第三，第四个参数为函数，没法使函数变得不一样，第一，第二个参数为对象，因此这要这两个参数的其中一个变得不一样，这样就不会使用缓存了。因此这是我的做法(注意`useEffect`和`route={customRoute}`):

```
const Index: React.FC<IndexProps> = (props) => {
...
const [customRoute,setCustomRoute] = useState<any>(null);

  const dispatch = useDispatch();
  const effectMethods = {
    searchMenuList: 'GlobalModel/searchMenuList',
    setSelectedMenuAndBreadcrumb: 'GlobalModel/setSelectedMenuAndBreadcrumb',
  };
// @ts-ignore
  const loadingEffect = useSelector((state) => state.loading);
  // 获取菜单数据加载状态
  const menuLoading = loadingEffect.effects[effectMethods.searchMenuList];
  // 获取菜单数据
  // @ts-ignore
  const menuList = useSelector((state) => state.GlobalModel.menuList);

// 仅在组件第一次初始化时调用
  useEffect(() => {
    dispatch({
      type: effectMethods.searchMenuList,
      payload: {pathname: history.location.pathname},
    });
  }, []);

  useEffect(()=>{
    console.log('menuList',menuList,menuLoading)
    // 当菜单加载完毕,则更新自定路由数据(重点在这个d属性),使得pro-layout的菜单能够更新为最新菜单
    setCustomRoute({routes:[],d:new Date()})
  },[menuLoading])

return (
    <ConfigProvider locale={loadLocaleByCode(languageCode)}>
      <ProLayout
        route={customRoute}
        menu={{locale: false}}
        fixedHeader={true}
        fixSiderbar={true}
        headerRender={() => customHeader}
        menuContentRender={(_, dom) =>
          menuLoading ? (
            <div
              style={{
                padding: '24px 0',
              }}
            >
              <Spin tip="菜单加载中">{dom}</Spin>
            </div>
          ) : (
            dom
          )
        }
        title="后台管理模板"
        logo="https://gw.alipayobjects.com/mdn/rms_b5fcc5/afts/img/A*1NHAQYduQiQAAAAAAAAAAABkARQnAQ"
        location={{
          pathname: history.location.pathname,
        }}
        menuDataRender={() => {
          return loopMenuItem(menuList)
        }}
        menuProps={{
          onOpenChange: (keyArr) => {
            // @ts-ignore
            setOpenKeys([...keyArr]);
          },
          openKeys: openKeys,
          selectedKeys: [history.location.pathname],
          /**
           * 监听菜单项点击
           * @param key
           * @param keyPath
           */
          onClick: function ({key, keyPath, item, domEvent}) {
            dispatch({
              type: effectMethods.setSelectedMenuAndBreadcrumb,
              payload: {selectedMenuItemPath: key},
            });
            history.push(key);
          },
        }}
      >
        {props.children}
      </ProLayout>
    </ConfigProvider>
  );
...
};
```

详细代码可以参考我的开源项目:
https://gitee.com/free_pan/pzy-easy-pro
