### ISSUE TITLE
Jest测试组件的时候，报错。提示 Cannot redefine property: ProFormContext 🐛[BUG]

### ISSUE THREAD

**Issue by zzq1101921989** [ant-design/pro-components#8032]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
运行Jest测试的时候，提示 Cannot redefine property: ProFormContext
![image](https://github.com/ant-design/pro-components/assets/48540122/18d63f5e-ebc2-4277-b12d-a3b40f0d856b)

### 📷 复现步骤
运行就报错，是不是版本依赖有问题

### 🏞 期望结果
正常测试通过，或者测试失败

### 💻 复现代码
jest测试文件
import {render, screen, fireEvent, waitFor} from '@testing-library/react'
import React from "react";
import CurrencyManage from '.'
import '@testing-library/jest-dom'

describe('test currency component', () => {
	// 验证是否挂载成功了新增按钮
	it('test mount component', async () => {
		render(<CurrencyManage/>)
		const addCurrencyButton = await screen.findByText(/新增币种/i)
		expect(addCurrencyButton).toBeInTheDocument();
	})

	// 点击 新增按钮 打开新增的弹窗
	it('click the button to open addCurrencyModal', async () => {
		render(<CurrencyManage/>)
		const addCurrencyButton = await screen.findByText(/新增币种/i)
		fireEvent.click(addCurrencyButton);
		// 等待弹窗出现
		const modal = await screen.findByRole('dialog')
		// 断言弹窗存在
		expect(modal).toBeInTheDocument();
	})

	// 填写表单需要的信息，并且创建币种
	it('Fill in the form information and create currency', async () => {

		render(<CurrencyManage/>)

		const addCurrencyButton = await screen.findByText(/新增币种/i)

		fireEvent.click(addCurrencyButton);

		// 等待弹窗出现
		const modal = await screen.findByRole('dialog')

		// 找到表单输入框
		const codeInput = screen.getByLabelText(/币种代码/i);
		const nameInput = screen.getByLabelText(/中文名称/i);

		// 模拟填写表单
		fireEvent.change(nameInput, {target: {value: '111'}});
		fireEvent.change(codeInput, {target: {value: '222'}});

		// 找到提交按钮
		const submitButton = modal.querySelector('.ant-modal-footer>button.ant-btn-primary');

		// 模拟提交表单
		fireEvent.click(submitButton);

		await waitFor(async () => {
			expect(true).toBe(true);
		});
	})
})
测试的组件文件
import { PageContainer } from '@ant-design/pro-components'
import { Button } from 'antd';
import styles from './style.less';

const CurrencyManage: React.FC = () => {

	return (
		<PageContainer>
			<div className={ styles.standardList }>
				<Button>新建币种</Button>
			</div>
		</PageContainer>
	);
};

export default CurrencyManage

### © 版本信息

- ProComponents 版本: [2.6.28]
- umi 版本 4.0.90
- 浏览器环境 120.0.6099.110
- 开发环境 [window10]
- @testing-library/jest-dom": "6.0.0,
- @testing-library/react": "14.0.0,
-  jest: "29.7.0"

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据报错提示和复现步骤，可能是因为在测试文件中重复定义了组件的上下文（Context）。解决方案如下：

1. 检查被测试的组件是否使用了Context，并确认是哪个Context导致的错误。
2. 在测试文件开头，使用jest.mock()来模拟被测试组件所用到的Context，并避免重复定义。

假设被测试组件使用了名为`ProFormContext`的Context，可以按照以下步骤修改代码：

1. 在测试文件的开头，添加以下代码：

```javascript
jest.mock('路径/到/ProFormContext', () => ({
  __esModule: true,
  default: {}
}));
```

将`路径/到/ProFormContext`替换为实际的Context路径。

2. 运行测试文件，查看是否还会报错。如果不报错了，说明问题已解决。

这样做的目的是使用jest.mock()来模拟被测试组件所使用的Context，避免重复定义导致的错误。
