### ISSUE TITLE
🐛[BUG]RecordCreatorProps.OnClick 内部无法同步状态的值

### ISSUE THREAD

**Issue by ByYogi** [ant-design/pro-components#8033]
### 🐛 bug 描述

`EditableProTable` 的 `RecordCreatorProps` 里面的 `Click` 事件 使用的状态来判断是否能添加行. 但是当状态发生变化. Click 事件里面的区域状态没有变化. 

### 📷 复现步骤
1. 切换状态
2. 查看打印
![image](https://github.com/ant-design/pro-components/assets/111735598/6b3353f6-6f0d-4bd8-a184-302658c623dd)
![image](https://github.com/ant-design/pro-components/assets/111735598/375320d3-ee14-43d8-8938-613ddaddf916)

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recordcreatorprops-onclick-nwfczk?file=%2Fsrc%2Fpages%2FEditableTableContent.tsx%3A39%2C17)

### 🏞 期望结果

之前 v2.6.18 版本状态时能同步的.

### © 版本信息

- ProComponents 版本: 2.6.43

**Comment by ByYogi** [comment]
经过我不断的排除法. 最后确定了错误出现在该版本之后`@ant-design/pro-components@2.6.36`
https://procomponents.ant.design/changelog#ant-designpro-components2636
![image](https://github.com/ant-design/pro-components/assets/111735598/03bf1fb1-1a02-4db1-a25f-a2757182a412)

**Comment by ByYogi** [comment]
然后我想问问. 这个源代码要怎么打包呀. 我本想自己改改源代码然后打包使用做临时替补. 但是我使用`pnpm build`打包出的产物好分散. 根本不能直接引用. 求指导 @chenshuai2144

**Comment by ByYogi** [comment]
我使用 `@ant-design/pro-components@2.6.35` 版本一段时间又遇到日期控件值 `Invalid data` 问题, 真是服了. 如果清空日期数据. 在重新赋值就会出现
![image](https://github.com/ant-design/pro-components/assets/111735598/40455698-9b4d-422e-9cd8-2581601c621f)

**Comment by ByYogi** [comment]
我是为了解决这个问题才升级的. 现在升级又冒出另一个问题. 真是两难
https://github.com/ant-design/pro-components/issues/7624#issuecomment-1876718524

**Comment by ByYogi** [comment]
> 我使用 `@ant-design/pro-components@2.6.35` 版本一段时间又遇到日期控件值 `Invalid data` 问题, 真是服了. 如果清空日期数据. 在重新赋值就会出现 

将dayjs版本升级一下就好了
![image](https://github.com/ant-design/pro-components/assets/111735598/aa33a816-81d1-4ab3-8340-ea76db49d9fe)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据问题描述和提供的代码片段，可以看出存在以下问题：

1. `EditableProTable`组件的`RecordCreatorProps`中的`onClick`事件使用了状态来判断是否能添加行，但是当状态变化时，点击事件中的状态没有同步更新。这可能是由于使用了旧的状态对象，而不是传递一个新的对象。

下面是解决这个问题的步骤：
1. 在`EditableTableContent.tsx`文件中，找到`EditableProTable`组件的`RecordCreatorProps`定义的地方。
2. 首先，确保在`EditableTableContent`组件中引入`React`的`useRef`钩子：
```javascript
import React, { useRef } from 'react';
```
3. 然后，使用`useRef`钩子创建一个可变的引用变量来存储状态值：
```javascript
const canAddRowRef = useRef(true);
```
4. 在`onClick`事件中，使用`canAddRowRef.current`来进行判断条件：
```javascript
onClick: () => {
  if (canAddRowRef.current) {
    // 添加行的逻辑
  }
}
```
5. 在状态变化的地方，更新`canAddRowRef.current`的值：
```javascript
setCanAddRow(true); // 更新状态值
canAddRowRef.current = true; // 更新引用变量
```
6. 这样，点击事件中的状态值将保持最新并且同步更新。

这是基于给出的问题描述和代码片段的解决方案。请注意，根据实际情况可能会有一些调整和修改。希望能对你有所帮助！

**Comment by ByYogi** [comment]
AI 这么厉害?
