### ISSUE TITLE
pro table 组件 在 type=form 时，cloumns 如何实现联动🧐[问题]

### ISSUE THREAD

**Issue by denshicheng** [ant-design/pro-components#8040]
# 需求描述
在一个modal 弹出框中使用该protable 组件，open时，将值通过`setFieldsValue`赋值到该组件中， `职能级别`通过默认值或者修改值让`父级职能`动态显隐

# 问题
目前在`getFieldValue` 获取的值存在在初始化时获取不到set 后的情况，不会触发renderForemItem 方法

`
const columns: ProColumns<any, any>[] = [
   {
      title: '职能级别',
      dataIndex: 'level',
      hideInSearch: true,
      hideInTable: true,
      valueEnum: CategoryLevel,
      formItemProps: {
        rules: [{
          required: true,
          message: '请选择职能级别'
        }]
      },
    },
    {
      // title: '父级职能',
      // dataIndex: 'pId',
      hideInSearch: true,
      hideInTable: true,
      formItemProps: { 
        noStyle: true,
        shouldUpdate: (pre, next) => {
          return pre.level !== next.level
        }
      },
      renderFormItem: (item, config ,form) => {
        const level = form.getFieldValue('level')
        console.log(level)
        if (level === 2 || level === 3) {
          return (
            <Form.Item label={'父级'} >
              <div>1323</div>
            </Form.Item>
          )
        }
        return null
      }
    },
  ];
<Modal
        forceRender
        title={‘123’}
        open={true}
>
          <ProTable<T, U>
              formRef={formRef}
              type='form'
              columns={props.columns}
            />
</Modal>
`

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据提供的代码，问题的解决方案如下：

1. 首先，在 `renderFormItem` 方法中，使用 `form.getFieldValue` 方法获取 `level` 值时，可能存在获取不到值的情况。这是因为在 `renderFormItem` 方法被调用时，表单的值可能尚未被初始化或更新，因此无法获取正确的值。为了解决这个问题，可以使用 `useEffect` 钩子函数监听 `level` 值的变化，并在变化时执行相应的操作。

2. 其次，需要在 `renderFormItem` 方法中将获取到的 `level` 值与 `2` 或 `3` 进行比较，以判断是否显示父级职能。如果匹配成功，则返回显示父级职能的表单项，否则返回 `null`。

下面是修改后的代码示例：

```tsx
import React, { useEffect } from 'react';
import { Modal, Form } from 'antd';
import { ProColumns } from '@ant-design/pro-table';
import ProTable from '@ant-design/pro-table';

const YourModalComponent: React.FC = () => {
  const [form] = Form.useForm();

  const columns: ProColumns<any, any>[] = [
    {
      title: '职能级别',
      dataIndex: 'level',
      hideInSearch: true,
      hideInTable: true,
      valueEnum: CategoryLevel,
      formItemProps: {
        rules: [
          {
            required: true,
            message: '请选择职能级别',
          },
        ],
      },
    },
    {
      hideInSearch: true,
      hideInTable: true,
      formItemProps: {
        noStyle: true,
        shouldUpdate: (pre, next) => {
          return pre.level !== next.level;
        },
      },
      renderFormItem: (item, config, form) => {
        useEffect(() => {
          form.setFieldsValue({ pId: '' });
        }, [form]);

        const level = form.getFieldValue('level');
        console.log(level);
        if (level === 2 || level === 3) {
          return (
            <Form.Item label="父级">
              <div>1323</div>
            </Form.Item>
          );
        }
        return null;
      },
    },
  ];

  return (
    <Modal forceRender title="123" open={true}>
      <Form form={form}>
        <ProTable
          type="form"
          columns={columns}
          formRef={form}
        />
      </Form>
    </Modal>
  );
};
```

修改后的代码会在初始渲染时将 `pId` 字段的值重置为空，并通过 `useEffect` 监听表单值的变化。当 `level` 值发生变化时，会重新渲染 `ProTable` 组件，并根据 `level` 值决定是否显示父级职能表单项。

注意：为了清晰起见，此示例省略了某些细节，如引入的依赖和数据定义。请根据具体情况进行相应调整。
