### ISSUE TITLE
🐛[BUG] ProFormColorPicker 在 build 之后报错: require is not defined

### ISSUE THREAD

**Issue by dreammaker7** [ant-design/pro-components#8042]
### 🐛 bug 描述

在 vite + antd5 的环境中使用 ProFormColorPicker，build 之后进入使用了 ProFormColorPicker 组件的地方会抛出异常 **require is not defined**，实测在 pro-components v2.6.5 及以下版本正常，2.6.5 以上版本会抛异常，dev 版本中全部正常。
### 📷 复现步骤
**生产版本进入任意引用 ProFormColorPicker 的逻辑**

4173 端口为 build 后运行版本（异常版本）
5173 端口为 dev 运行版本（可正常使用）

### 🏞 期望结果

修复问题，在生产版本中正常使用 ProFormColorPicker 组件。

### 💻 复现代码

[CodeSandbox demo](https://codesandbox.io/p/devbox/vite-antd-forked-h5s8nq?file=%2Fpackages%2Fproject%2Fsrc%2FApp.tsx%3A10%2C49)
### © 版本信息

- ProComponents 版本: 2.6.43
- Vite 版本: 4.4.9
- 浏览器环境: Chrome v120.0.6099.130
- 开发环境: Windows 11

### 🚑 其他信息

**dev 正常示例：**

![1704340604600](https://github.com/ant-design/pro-components/assets/74588098/1d81d5ae-748f-4608-bf30-c3d7af49a67b)

build 后 catch 示例：

![image](https://github.com/ant-design/pro-components/assets/74588098/a4121478-0a55-4198-b452-48310db662fd)

**Comment by virzs** [comment]
> +1

![image](https://github.com/ant-design/pro-components/assets/44538687/51c376e3-5e08-4984-8170-56e1d986d50d)

**Comment by virzs** [comment]
我修改了 vite config，暂时可以了 @dreammaker7 

```js
export default defineConfig({
  build: {
    commonjsOptions: { transformMixedEsModules: true } // Change
  }
})
```

**Comment by dreammaker7** [comment]
@virzs 感谢贡献方案，我目前用 antd5.x 包的 ColorPicker 组件替代了，修改 vite 配置的话担心出现其他问题🤔

![image](https://github.com/ant-design/pro-components/assets/74588098/0ce98d2b-bed1-4625-b735-2746045206b1)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据提供的bug描述和复现步骤，该问题是在使用vite和antd5环境中，build之后使用ProFormColorPicker组件会报错"require is not defined"。以下是解决该问题的步骤：

步骤1：确认依赖版本
首先，确认使用的ProComponents版本。根据提供的信息，当前使用的是2.6.43版本。可以尝试升级ProComponents到最新版本，看看问题是否已经在新版本修复。如果升级后问题仍然存在，可以继续下面的步骤。

步骤2：排查配置问题
在使用vite和antd5的环境中，配置文件可能会对构建过程产生影响。请检查vite配置文件（通常是vite.config.js）是否正确配置了antd的按需加载（按需加载是默认的配置）。具体看是否引入了插件`vite-plugin-style-import`来实现按需加载，示例代码如下：
```javascript
// vite.config.js
import styleImport from 'vite-plugin-style-import';

export default {
  plugins: [
    ...
    styleImport({
      libs: [
        {
          libraryName: 'antd',
          esModule: true,
          resolveStyle: (name) => {
            return `antd/es/${name}/style/index`;
          },
        },
      ],
    }),
    ...
  ],
};
```

步骤3：检查构建错误
根据提供的复现代码，无法直接在本地构建来排查问题。然而，可以尝试在构建过程中查看详细的错误信息。可以尝试在构建脚本中添加`--debug`标志来查看构建详细日志。示例代码如下：
```json
// package.json
{
  "scripts": {
    "build": "vite build --debug"
  }
}
```
这样可以在终端或控制台中查看更详细的错误信息，以帮助我们更好地定位问题。

步骤4：尝试其他解决方案
如果以上步骤仍无法解决问题，可以尝试以下解决方案：
- 尝试在项目根目录下执行`yarn upgrade-interactive --latest`，更新所有依赖项到最新版本，看看是否能解决问题。
- 尝试在项目根目录下执行`yarn cache clean`来清除缓存，然后再次构建项目。

以上是解决问题的一些建议，希望能够帮助到你解决这个bug。如果问题仍然存在，请提供更多的错误信息和复现代码，以便我们进一步帮助你解决问题。
