### ISSUE TITLE
🐛[BUG] File name differs from already included file name only in casing.

### ISSUE THREAD

**Issue by AliYar-Khan** [ant-design/pro-components#8043]
In visual studio code, I am facing issue after installing the Pro version 4, 

 File name '/node_modules/@ant-design/pro-components/es/index.d.ts' differs from already included file '/node_modules/@ant-design/pro-components/es/index.d.ts' name only in casing. 
 
 
 
![Screenshot (212)](https://github.com/ant-design/pro-components/assets/37889962/1217b24a-e227-44f3-b0aa-02990c898fc4)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据问题描述和附带的截图，这个问题是文件名大小写不匹配导致的错误。解决方案如下：

1. 确认你的项目使用的是最新的 Umi 和 antd 版本，因为一些旧版本可能存在大小写敏感的问题。

2. 确认你的项目中引入的组件文件路径大小写是否与实际文件路径大小写一致，特别是在使用 import 语句引入组件的地方。

3. 检查你的代码中是否有其他地方引入了同名但大小写不一致的文件。可以使用全局搜索工具搜索文件名，确保所有引入的文件名大小写一致。

4. 如果你使用的是 Windows 系统，需要注意文件系统是大小写不敏感的，但是在 Linux 或 Mac 系统中是大小写敏感的。如果你的代码在 Windows 上运行正常，但在 Linux 或 Mac 上出现问题，那么很可能是因为文件名大小写的不匹配导致的。

5. 如果以上步骤都没有解决问题，可以考虑更新你的 Umi 和 antd 版本，或者尝试使用其他前端组件或框架进行替代。
