### ISSUE TITLE
🐛[BUG] ProForm表单项为非必填时，提交表单不能获取到非必填项的值

### ISSUE THREAD

**Issue by xiaopingyi** [ant-design/pro-components#8048]
### 🐛 ProForm表单项为非必填时，提交表单不能获取到非必填项的值
![image](https://github.com/ant-design/pro-components/assets/19259376/682910fd-dfd6-4798-a6f1-f809937034b9)
如上编辑表单点击提交时希望得到
```json
{"数字": null, "文字": "", "选择": null}
```
实际得到结果
```json
{}
```
### 📷 复现步骤
直接点击提交按钮

### 🏞 期望结果
```json
{"数字": null, "文字": "", "选择": null}
```

### 💻 复现代码
https://codesandbox.io/p/sandbox/proformbiao-dan-bian-ji-qing-kong-shu-ju-bu-fan-hui-zi-duan-huo-zhe-fan-hui-zi-duan-wei-undefined-frqmkp?file=%2FApp.tsx%3A9%2C23

### © 版本信息

- ProComponents 版本: 2.3.52
- umi 版本
- 浏览器环境
- 开发环境 macOs 14.2.1

### 🚑 其他信息
切换为最新版本依然不能得到预期结果，查看源码发现以ProFormDigit为例子，默认是undefined，这里是否改为null更好理解，undefined为未定义，但是这里是定义了未输入值
![image](https://github.com/ant-design/pro-components/assets/19259376/ad4919fc-8786-4caf-8d4e-8fab36a09531)

**Comment by chenshuai2144** [comment]
| 参数 | 说明 | 类型 | 默认值 |
| --- | --- | --- | --- |
| omitNil | ProForm 会自动清空 null 和 undefined 的数数据，如果你约定了 nil 代表某种数据，可以设置为 false 关闭此功能 | `boolean` | true |

**Comment by zouyi741599086** [comment]
> 参数	说明	类型	默认值
> 奥米特尼	形式上会自动清空空和不明确的的数数据,如果你约定了无代表某种数据,可以设置为错误的关闭此功能	`boolean`	真实的

这参数无效
