### ISSUE TITLE
🧐[问题]EditableProTable  rowKey赋值

### ISSUE THREAD

**Issue by limingj** [ant-design/pro-components#8049]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
rowKey 的定义有要求吗？简单的数据及数据类型，在编辑的时候会同时选中两行，但是key值是不一样的

### 🚑 其他信息
![微信图片_20240105192652](https://github.com/ant-design/pro-components/assets/50091007/aa4099b2-a8e1-40fe-91b9-a62ec418ff5d)
![微信图片_20240105192658](https://github.com/ant-design/pro-components/assets/50091007/6ac4a06d-44e2-4c73-b5f1-b3a699922a7d)

**Comment by chenshuai2144** [comment]
只要保证唯一就可以了

**Comment by baixiaomei** [comment]
我也遇到同样的问题，怎么解决的？

**Comment by limingj** [comment]
> 我也遇到同样的问题，怎么解决的？
我解决的办法是：id 不要设置成0、1、2、3这种简单的，取值长一些

**Comment by baixiaomei** [comment]
感谢回复，确实好用
