### ISSUE TITLE
🐛[BUG]ProTable  defaultSortOrder 和 defaultFilteredValue 

### ISSUE THREAD

**Issue by zero-fei** [ant-design/pro-components#806]
### 🐛 bug 描述
Pro-table 的defaultSortOrder 和 defaultFilteredValue bug

### 📷 复现步骤
columns设置defaultSortOrder和defaultFilteredValue

### 🏞 期望结果

希望可以设置成功，现在只能降低版本来用

### © 版本信息

- ProComponents 版本:
proTable 最新版本
- umi 版本

- 浏览器环境
- 开发环境 
mac OS

**Comment by chenshuai2144** [comment]
支持的，和 antd 行为一样，没效果一般是忘记设置 sort 方法或者 filter方法 了
