### ISSUE TITLE
🐛[BUG]: Unable to reset the Step in <StepForm/>

### ISSUE THREAD

**Issue by HelpMe-Pls** [ant-design/pro-components#8061]
In [this example](https://procomponents.ant.design/en-US/components/steps-form#step-by-step-forms---works-with-modal), the Step remains at the final step after submitting.
If you submitted the form and then reopen it again, the Step remains at Step 3. How can I reset the form to be back at the first step ?
I'm unable to find in the document any API or props to handle that. 

Thanks in advance.

**Comment by chenshuai2144** [comment]
可以通过 context 来维护一个 current number
