### ISSUE TITLE
🧐[问题] tailwindcss 跟 antd 样式问题冲突

### ISSUE THREAD

**Issue by lynn1286** [ant-design/pro-components#8063]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

为了解决 tailwindcss 的base样式与antd样式冲突问题，将config配置如下图：
<img width="605" alt="image" src="https://github.com/ant-design/pro-components/assets/40122311/52aa3550-bb49-4786-8f8b-69e59afb964d">
随之会出现a标签的颜色没有跟随antd的主题色，包括Typography.Link 组件，代码如下：
<img width="849" alt="image" src="https://github.com/ant-design/pro-components/assets/40122311/1c03acd3-bb4e-4021-9c96-c7a755511614">

### 💻 示例代码
打开控制台发现是antd的a标签样式高于tailwindcss 以及global.css ，加 !important 可以解决，但是是否可以通过其他方式设置？
<img width="1955" alt="image" src="https://github.com/ant-design/pro-components/assets/40122311/ac7fdb72-0e39-45d5-aab4-22be4b232703">

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题描述：
为了解决 tailwindcss 的 base 样式与 antd 样式冲突问题，将 config 配置如下图所示。随之会出现 a 标签的颜色没有跟随 antd 的主题色，包括 Typography.Link 组件。

示例代码：
打开控制台发现是 antd 的 a 标签样式高于 tailwindcss 和 global.css，加 !important 可以解决，但是否可以通过其他方式设置？

解决方案：
根据问题描述，可以尝试以下几种解决方案：

1. 使用 CSS-in-JS：可以使用 CSS-in-JS 的方式来避免样式冲突。可以考虑使用 antd 提供的样式覆盖机制，将 antd 的样式覆盖为 tailwindcss 的样式。

2. 调整 antd 样式优先级：可以通过调整 antd 样式的优先级来覆盖 tailwindcss 的样式。可以使用 CSS 选择器的特殊性或者!important 来提高 antd 样式的优先级。

具体实施方法可以参考 antd 文档中有关样式优先级的部分，也可以参考 antd GitHub 上的相关 issue [#38794](https://github.com/ant-design/ant-design/issues/38794) 中的讨论。
