### ISSUE TITLE
🧐[问题] ProTable type=form时，如何配置footer

### ISSUE THREAD

**Issue by overQ-N** [ant-design/pro-components#8065]
<img width="433" alt="image" src="https://github.com/ant-design/pro-components/assets/47857170/c044ec3d-c6b2-4ca2-ac42-1c8eadcdc0aa">
 如图，type=form时，重置和提交按钮是否可以自定义？

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


对于type=form时，重置和提交按钮的自定义，可以通过配置 submitter 来实现。

submitter 是个对象，可以包含以下属性：

- submitButtonProps：设置提交按钮的属性，例如按钮的类型、大小、图标等。
- resetButtonProps：设置重置按钮的属性，例如按钮的类型、大小、图标等。
- submitText：设置提交按钮的文字。
- resetText：设置重置按钮的文字。
- showResetButton：是否显示重置按钮，默认为 true。
- showSubmitButton：是否显示提交按钮，默认为 true。
- render：自定义渲染按钮的方法。

示例代码如下：

```javascript
import { ProForm, ProFormText } from '@ant-design/pro-form';

const Demo = () => {
  return (
    <ProForm submitter={{
      submitButtonProps: {
        type: 'primary',
        size: 'large',
        icon: '+',
      },
      resetButtonProps: {
        type: 'default',
        size: 'large',
        icon: '-',
      },
      submitText: '保存',
      resetText: '重置',
      showResetButton: true,
      showSubmitButton: true,
      render: (props, doms) => {
        return [
          ...doms,
          <Button key="customButton" type="ghost">自定义按钮</Button>,
        ];
      },
    }}>
      <ProFormText name="name" label="姓名" />
      <ProFormText name="age" label="年龄" />
    </ProForm>
  );
}
```

上述代码中，通过 submitter 对象的各个属性进行配置，可以自定义提交按钮和重置按钮的属性、文字和显示方式。其中，render 方法可以自定义渲染按钮，可以在默认按钮的基础上添加额外的自定义按钮。

**Comment by chenshuai2144** [comment]
和 form一样都是通过 submitter 来配置的
