### ISSUE TITLE
🐛[BUG] ProFormDependency 在QueryFilter 中不生效

### ISSUE THREAD

**Issue by hsbtr** [ant-design/pro-components#8067]
### 🐛 bug 描述

QueryFilter中只有初始化的时候，ProFormDependency才能监听到值，或者发生onFinish事件触发后；在ProForm和ModalForm中则不会有问题

### 📷 复现步骤

QueryFilter使用ProFormDependency监听任意表单项目

### 🏞 期望结果

可以正确的监听到值变化

### 💻 复现代码

https://codesandbox.io/p/sandbox/cha-xun-shai-xuan-sou-suo-forked-s8hm3p

### © 版本信息

- ProComponents 版本:  2.6.44
- vite or webpack
- 浏览器环境
- 开发环境  windows 10

**Comment by hsbtr** [comment]
这个问题这么冷门的嘛，都没有人遇到过

**Comment by ONLY-yours** [comment]
确实蛮奇怪的，在 ProTable 里面顶部 Search 是好的，但是单独使用就挂了

**Comment by xliez** [comment]
https://github.com/ant-design/pro-components/pull/7611
这个 pr 中引入了这个 BUG，很奇怪，感觉这个 pr 的 changes 和对应的 issue 没啥关联
