### ISSUE TITLE
🐛[BUG] appConfig 插件配置 message config 无效

### ISSUE THREAD

**Issue by lynn1286** [ant-design/pro-components#8069]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
为了解决antd message 静态方法报错问题，根据文档需要开启 appConfig 包裹 app 组件，并且配置 message 全局配置，但是发现配置无效，例如下图：
<img width="560" alt="image" src="https://github.com/ant-design/pro-components/assets/40122311/8116625b-05f3-466c-856f-5ef02f259b42">

由于 App.useApp() 只能在 react 组件中使用，所以需要进行一层封装：
<img width="906" alt="image" src="https://github.com/ant-design/pro-components/assets/40122311/822c96d4-b8fd-4c47-ae7f-f026da059bc7">

接着在 requestErrorConfig.ts 中使用：
<img width="741" alt="image" src="https://github.com/ant-design/pro-components/assets/40122311/dce0dd90-c31a-4a5d-99c6-f8215d10a99e">

尝试在运行时配置，也是不生效：
<img width="636" alt="image" src="https://github.com/ant-design/pro-components/assets/40122311/63bada75-f0d3-4618-9325-8a5e7e2f07a6">

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by terwer** [comment]
其实在页面上加一个 contextHolder 更好。个人觉得


```tsx
  const [messageApi, messageContextHolder] = message.useMessage()

  // 使用

messageApi.warning("来源非法，未获取到平台元数据")

return <>
 {messageContextHolder}
</>
```

**Comment by lynn1286** [comment]
> 其实在页面上加一个 contextHolder 更好。个人觉得
> 
> ```tsx
> const [messageApi, messageContextHolder] = message.useMessage()
> 
> // 使用
> messageApi.warning("来源非法，未获取到平台元数据")
> 
> return <>
>  {messageContextHolder}
> </>
> ```

那如果在非页面上如何使用呢？比如 request.js 中需要做全局信息处理

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据问题描述，我们可以看到在配置antd message全局配置时，配置无效。为了解决这个问题，我们可以尝试以下解决方案：

1. 确保在入口文件（如App.js或index.js）中正确引入了antd的message组件，并导入所需的样式文件。

2. 确保在appConfig组件中正确配置了message全局配置。可以参考antd的官方文档，确认配置项是否正确、是否按照正确的方式进行了配置。

3. 确保在使用message组件的地方，没有对配置进行了覆盖或重置。可能存在其他地方对message配置进行了修改，并导致了配置无效的情况。

4. 如果以上步骤都没有解决问题，可以尝试在Umi的配置文件中进行全局配置。可以在config文件夹下的config.js或config.prod.js中找到相关配置项，并进行相应的修改。

如果以上解决方案都没有解决问题，可以进一步检查项目中是否存在其他可能影响全局配置的配置项或代码段。可以尝试在项目中搜索所有与message相关的代码，并逐个排查。

另外，建议在提问时

**Comment by chenshuai2144** [comment]
@lynn1286  试试 useApp 


```
App.useApp();

// 使用 message 静态方法
message.success('成功提示');
```

**Comment by andyFang94** [comment]
> > App.useApp();
> 
> 在拦截器中使用会报错

在 app.tsx导入一下呢？ 
```
export function rootContainer(container: any) {
  return (
    <App>
      <EscapeMessage />
      {container}
    </App>
  );
}
```
