### ISSUE TITLE
🐛[BUG] `ProFormText.Password` 的 `PasswordStrength` 的几个需要解决的问题

### ISSUE THREAD

**Issue by xsjcTony** [ant-design/pro-components#8074]
### 🐛 bug 描述

1. 配合校验时，popover 会随着 错误信息 的 出现/消失 而位移

2. 无法改变 popover 出现的方式, 非常不便。正常来说都应该希望至少 focus 的时候就出现。
配置 `popoverProps: { open: true }` 无效，因为他被 `onClick` / `onBlur` 强制更改了:
https://github.com/ant-design/pro-components/blob/981f065f4bad476402dd4014764a75f9b45ea33d/packages/form/src/components/Text/index.tsx#L128-L135

3. （这个不一定是问题， 可能就是没办法）屏幕窄时，popover会遮住输入框。目前没有解决办法，我用 `placement: 'left'` 让他挡住右边会稍微好一点。他应该和 `top` / `bottom` 一样位置不够就移出屏幕才对。不想用 `top` / `bottom`

### 📷 复现步骤

用官网 `<LoginForm />` demo 就能快速复现

### 🏞 期望结果

1. 不定位 `<ProField />` 因为他的高度会根据 错误信息 有无 而变化。建议根据 `<Input />` 定位

2. 屏幕距离够就默认 `right`, 不够调整成 `top`

### 💻 复现代码

官网demo

### © 版本信息

- ProComponents 版本: latest
- umi 版本: N/A
- 浏览器环境: Chrome 120
- 开发环境: Windows 11

### 🚑 其他信息

1. 配合校验时，popover 会随着 错误信息 的 出现/消失 而位移
https://github.com/ant-design/pro-components/assets/45784210/6f4fcd83-5a80-4958-bc98-3e1c8ce4ffc2

3. （这个不一定是问题， 可能就是没办法）屏幕窄时，popover会遮住输入框。目前没有解决办法，我用 `placement: 'left'` 让他挡住右边会稍微好一点。不想用 `top` / `bottom`
https://github.com/ant-design/pro-components/assets/45784210/e39ef82f-fd38-4754-9037-cef581a891d6

**Comment by chenshuai2144** [comment]
有理有据 让人信服
