### ISSUE TITLE
antd4.0如何无缝使用pro-component🧐[问题]

### ISSUE THREAD

**Issue by aiyudeleng** [ant-design/pro-components#8076]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

现在的项目使用的是antd4.0，想在项目中使用proTable。但是看了proTable的文档都是Typescript的，项目都是js文件。不是很明白，怎么能无损的使用proTable及其他pro-components呢。网上看了一些示例，都是重新构建项目的

**Comment by dreammaker7** [comment]
文档和使用无关，把示例中的 ts 代码去掉一样使用，不过 pro-components 版本会跟随 antd 最新版本(5.x)变更特性的，如果你不迭代 antd 版本，最好锁定一个早期的 pro-components 版本。

**Comment by aiyudeleng** [comment]
我使用的是antd4.0，应该用哪个版本的pro合适？另外，除了引入procomponents之外，是不是还要引入css-in-js这个依赖？



                       
原始邮件
                       
                     

发件人："Ryanxc"< ***@***.*** &gt;;

发件时间：2024/1/12 14:47

收件人："ant-design/pro-components"< ***@***.*** &gt;;

抄送人："aiyudeleng"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [ant-design/pro-components] antd4.0如何无缝使用pro-component🧐[问题] (Issue #8076)




 
文档和使用无关，把示例中的 ts 代码去掉一样使用，不过 pro-components 版本会跟随 antd 最新版本(5.x)变更特性的，如果你不迭代 antd 版本，最好锁定一个早期的 pro-components 版本。

**Comment by dreammaker7** [comment]
我觉得你应该直接动手尝试，哪个版本适合你的项目只有你自己试了才知道，pro-components 从 2022 年开始就逐渐向 antd5.0 的新特性慢慢转换，你得确定你自己需要什么，每个迭代新增了哪些修复了哪些，你完全可以在 change log 里看到🤔

**Comment by chenshuai2144** [comment]
不要强行使用了，我们支持是为了防止页面暴毙，不是为了让页面乱起来
