### ISSUE TITLE
🐛[BUG] ProFormList的项不使用label首行组件样式坍塌的问题

### ISSUE THREAD

**Issue by hans000** [ant-design/pro-components#8079]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
ProFormList的项不使用label首行组件样式坍塌的问题

### 📷 复现步骤
https://codesandbox.io/p/devbox/tw69j4?file=%2Fsrc%2FApp.tsx%3A30%2C21

### © 版本信息

- ProComponents 版本: [latest]
- umi 版本 latest
- 浏览器环境 latest
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
我感觉你可以搞个空格到lable上去，不然总是对不齐的
