### ISSUE TITLE
🐛[BUG] Error when using in next.js

### ISSUE THREAD

**Issue by wolfcreative** [ant-design/pro-components#8080]
### 🐛 bug

An error appears when trying to use **_any component_** from the library:

```
⨯ node_modules\@ant-design\pro-form\lib\components\FieldSet\index.js (24:21) @ Group
⨯ TypeError: Cannot read properties of undefined (reading 'Group')
    at eval (webpack-internal:///./node_modules/@ant-design/pro-form/lib/components/FieldSet/index.js:37:24)
```

### 🏞 期望结果

Everything will work

### 💻 复现代码

```
import { FullWidthLayout } from '@/src/layouts/fullWidth'
import { ProForm, ProFormText } from '@ant-design/pro-components'

export default function TestPage() {
	return (
		<>
			<FullWidthLayout>
				<ProForm
					onFinish={async (values) => {
						console.log(values)
					}}
				>
					<ProFormText name="name" label="姓名" />
				</ProForm>
			</FullWidthLayout>
		</>
	)
}
```

### © 版本信息

- @ant-design/pro-components 2.6.43
- antd 5.12.8
- next.js 14.0.4 Page Routes

### 🚑 其他信息

The antd itself works fine. The following is written in transpilePackages:

```
[
   'antd',
   '@ant-design',
   'rc-util',
   'rc-pagination',
   'rc-picker',
   'rc-tree',
   'rc-table',
]
```

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据当前的错误信息，你可以尝试以下解决方案：

1. 确保你的依赖版本是最新的，可以通过 `npm update` 或者 `yarn upgrade` 来更新依赖版本。

2. 检查你的代码中是否有使用 Next.js 的 App Router，如果有的话，可能是因为在服务端渲染时，antd 组件中的子组件在服务器端无法访问而导致的报错。你可以尝试在页面的顶部添加 `'use client';` 标签来将该页面标记为客户端渲染，如下所示：

```javascript
'use client';

// Your code here
```

通过这样的方式，可以将页面的渲染限定为客户端渲染，避免在服务端渲染时出现报错。

3. 如果以上两种方法都无法解决问题，你可以尝试升级你的 Next.js 版本或者联系 Next.js 官方获取官方解决方案。有时候，某些 Next.js 版本可能存在一些已知的问题，升级版本可能会修复一些 bug。

希望以上解决方案对你有所帮助。如果问题仍然存在，请提供更多的信息以便我们提供更准确的解决方案。

**Comment by wolfcreative** [comment]
Really. By deleting the node_modules folder and the package-lock file.the json problem is gone. Suddenly.

Thanks for the help!

**Comment by s875515** [comment]
> Really. By deleting the node_modules folder and the package-lock file.the json problem is gone. Suddenly.
> 
> Thanks for the help!

Same error after remove all node_modules and package-lock. Do you have any idea for this plz?

**Comment by wolfcreative** [comment]
@s875515 Try adding "'use client';" to the very beginning of the page

**Comment by s875515** [comment]
> @s875515 Try adding "'use client';" to the very beginning of the page

Yes, I tried, still not work. Also, we using page router. Do you have any other thought?

**Comment by s875515** [comment]
> > @s875515 Try adding "'use client';" to the very beginning of the page
> 
> Yes, I tried, still not work. Also, we using page router. Do you have any other thought?

Notes: next@14.0.2 is working good.

**Comment by joewan** [comment]
I have met the same problem, "next": "^14.3.0-canary.38",
can you give me some help.

**Comment by joewan** [comment]
> > Really. By deleting the node_modules folder and the package-lock file.the json problem is gone. Suddenly.
> > Thanks for the help!
> 
> Same error after remove all node_modules and package-lock and pretty sure all is newest. The interesting is that work when SPA router, but not work on the page refresh. Do you have any idea for this plz?
> 
> ![image](https://private-user-images.githubusercontent.com/6601431/310434751-a9851de1-4b09-4449-a403-8052a16809cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MDk2NjksIm5iZiI6MTcxNDgwOTM2OSwicGF0aCI6Ii82NjAxNDMxLzMxMDQzNDc1MS1hOTg1MWRlMS00YjA5LTQ0NDktYTQwMy04MDUyYTE2ODA5Y2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDRUMDc1NjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDhlYjg5NGFkNWNkODkzYzJhMjI0ZTA4NzIxY2EyNjM2ZTNkZjE1ZDYyNWFlZDdjNDhmZTczNTZlZWFmMzE3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K2NYHGxXyvXacEw_qI0oJ6Yd--Tp7RJ_m-bc5Pa2EZ8)

exactly the same, may be this is a serious bug.

**Comment by joewan** [comment]
@s875515 
Notes: next@14.0.2 is working good.
exactly the same.

**Comment by joewan** [comment]
https://github.com/joewan/kblogui/
@chenshuai2144 
I have reproduced the problem,  "http://localhost:8884/user/login"
can you give some help?
thanks very much.

**Comment by joewan** [comment]
can we reopen this issue?
