### ISSUE TITLE
🐛[BUG]LoginFormPage 登录按钮没了

### ISSUE THREAD

**Issue by wanliyunyan** [ant-design/pro-components#8083]
### 🐛 bug 描述

LoginFormPage 登录按钮没了，显示了重置按钮

### 📷 复现步骤

https://procomponents.ant.design/components/login-form 官网就是错误的

### 🏞 期望结果

LoginFormPage 显示登录按钮

### © 版本信息

- ProComponents 版本: 2.6.45
- umi 4.1.0
- 浏览器环境 Chrome 120 
- 开发环境 windows 11

### 🚑 其他信息

![image](https://github.com/ant-design/pro-components/assets/10751248/68444b99-883d-42d9-b7c2-c47463a3140e)

**Comment by chenshuai2144** [comment]
修复了，再试试

**Comment by samotoo** [comment]
刚看了一下官网demo，依然是错的。。。
