### ISSUE TITLE
🐛[BUG] ProLayout 在没有设置 `bgImgStyleList` 属性时背景色丢失

### ISSUE THREAD

**Issue by notzheng** [ant-design/pro-components#8084]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
@ant-design/pro-components@2.6.45 中有一条更新：

> fix(layout): if bgImgStyleList is null ,no render bg-list dom. [0b26161](https://github.com/ant-design/pro-components/commit/0b26161)

这个更新应该是破坏性的，现在不指定 `bgImgStyleList` 这个属性， layout 的背景色会是白色。

### 📷 复现步骤

https://pro-components.antdigital.dev/playground/pro-layout

![Google Chrome  ScreentShot at 2024-01-15 16 38 11](https://github.com/ant-design/pro-components/assets/13414731/9b7523ea-15a3-4adf-a321-3d8d5da6f4a3)

### 🏞 期望结果

https://pro-components.antdigital.dev/playground/pro-layout

![Google Chrome  ScreentShot at 2024-01-15 16 38 02](https://github.com/ant-design/pro-components/assets/13414731/8e209ba6-9c5f-428f-bfdb-9f5bfa0d8f2e)

### 💻 复现代码

https://procomponents.ant.design/playground/pro-layout

### © 版本信息

- ProComponents 版本: 2.6.45

**Comment by chenshuai2144** [comment]
修复了，再试试
