### ISSUE TITLE
🐛[BUG]升级到antd 5.13.x后ProForm的一些警告

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/pro-components#8089]
### 🐛 bug 描述

bordered 被废弃，ProFormSelect，ProFormDatePicker等一些组件会报警告
Warning: [antd: Select] `bordered` is deprecated. Please use `variant` instead.
### 🏞 期望结果
没有warning信息

### © 版本信息

- ProComponents 版本: [2.6.46]
- umi 版本 4.1.0
- 浏览器环境 120.0.6099.217
- 开发环境 [windows 11]

**Comment by ONLY-yours** [comment]
为了兼容 antd 4 hahah，去掉 antd 可能就挂了 先暂时忽略下吧
