### ISSUE TITLE
🐛[BUG]@ant-design/pro-form@2.41.1 es/components/FormItemRender/index.d.ts line 24 and line 27 ts error

### ISSUE THREAD

**Issue by earlbyrd** [ant-design/pro-components#8092]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

@ant-design/pro-form@2.41.1 es/components/FormItemRender/index.d.ts line 24 and line 27 ts error

### 📷 复现步骤

@ant-design/pro-form@2.41.1
ts 5.0.4

e.g.
![image](https://github.com/ant-design/pro-components/assets/28821470/821ce700-252e-42ec-b652-c346dd66de58)

**Comment by hcxw11** [comment]
+1

**Comment by earlbyrd** [comment]
您好，邮件收到！刘沈一

**Comment by earlbyrd** [comment]
我升到5.3.3依旧不行

**Comment by earlbyrd** [comment]
resolved with ts 5.3.3 and this 
https://github.com/hipstersmoothie/react-docgen-typescript-plugin/issues/78#issuecomment-1409224863
