### ISSUE TITLE
🐛[BUG] ProFormSwitch 组件未继承 antd Switch的属性，size属性使用无效且声明文件未导出

### ISSUE THREAD

**Issue by EdisonVan** [ant-design/pro-components#8117]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
<img width="955" alt="image" src="https://github.com/ant-design/pro-components/assets/38999461/f1167ec7-1720-4fe8-a8a2-89d6eab7a3cd">
<img width="569" alt="image" src="https://github.com/ant-design/pro-components/assets/38999461/68cbed2d-5d0f-46a8-b569-0c82f9404c49">
<img width="687" alt="image" src="https://github.com/ant-design/pro-components/assets/38999461/e188c1d2-2c46-45d7-99e8-e7795c0e73ea">
![Uploading image.png…]()

ProFormSwitch 组件未继承 antd Switch的属性，size属性使用无效且声明文件未导出

### 📷 复现步骤
"@ant-design/pro-components": "^2.3.57"

引用一个ProFormSwitch组件，设置size属性
<img width="596" alt="image" src="https://github.com/ant-design/pro-components/assets/38999461/481f2862-9a3d-429b-b4db-8f39acc4b302">

### 🏞 期望结果
ProFormSwitch 组件能正常使用 antd Switch中的属性

### 💻 复现代码
 <ProFormSwitch
     name="route_show_yields"
    label={intl.formatMessage({ id: 'show-yield' })}
    size="small"
/>

### © 版本信息
- ProComponents 版本: [e.g. 4.0.0]
- umi 版本  4.0.64
- 浏览器环境 Chrome  120.0.6099.234
- 开发环境  macOS 14.3

**Comment by chenshuai2144** [comment]
使用 filedProps 来设置 size，文档第一行就是这个的说明
