### ISSUE TITLE
🧐[问题]: ProFormSelect组件 mode 设置为"tags"或"multiple"时，如何限制最大选择数量

### ISSUE THREAD

**Issue by Onion17** [ant-design/pro-components#8122]
### 🧐 问题描述
根据 Ant Design 的 Select 组件，有 maxCount 属性限制最大多选数量，但是在 ProFormSelect 中无法使用该属性。

### 💻 示例代码
```
<ProFormSelect
    name="purifierBrand"
    colProps={{ md: 12, xl: 4 }}
    label="品牌"
    request={getFilter.run}
    mode="multiple"
    debounceTime={300}
    maxCount={2}
/>

<ProFormSelect
    name="purifierBrand"
    colProps={{ md: 12, xl: 4 }}
    label="品牌"
    request={getFilter.run}
    mode="tags"
    debounceTime={300}
    fieldProps={{
      maxCount: 2,
    }}
  />
```

### 🚑 其他信息
上面两种方式均提示没有该属性
<img width="627" alt="image" src="https://github.com/ant-design/pro-components/assets/40941533/6ffe3d9f-cc5b-4ac6-85da-200bb5350b21">
<img width="597" alt="image" src="https://github.com/ant-design/pro-components/assets/40941533/af946be1-0312-481b-a921-f2db66239b2c">

**Comment by cheneyg916** [comment]
看看antd版本吧，antd版本可能不支持这个属性

**Comment by datoou** [comment]
```
<ProFormSelect
    name="purifierBrand"
    colProps={{ md: 12, xl: 4 }}
    label="品牌"
    request={getFilter.run}
    mode="multiple"
    debounceTime={300}
    fieldProps={{
       maxCount: 2,
    }}
/>
```

**Comment by tangxuelei** [comment]
maxTagCount亲测有效, 看了4.0 5.0的antd文档,都是maxTagCount这个字段,不知maxCount是哪里查到的
```
<ProFormSelect
    name="purifierBrand2"
    colProps={{ md: 12, xl: 4 }}
    label="品牌"
    options={[11,22,33,44,55,66,77]}
    mode='tags'
    debounceTime={300}
    fieldProps={{
      maxTagCount:2 
    }}
  />

```

**Comment by tangxuelei** [comment]
maxTagCount亲测有效, 看了4.0 5.0的antd文档,都是maxTagCount这个字段,不知maxCount是哪里查到的
```
<ProFormSelect
    name="purifierBrand2"
    colProps={{ md: 12, xl: 4 }}
    label="品牌"
    options={[11,22,33,44,55,66,77]}
    mode='tags'
    debounceTime={300}
    fieldProps={{
      maxTagCount:2 
    }}
  />

```

**Comment by datoou** [comment]
> maxTagCount亲测有效, 看了4.0 5.0的antd文档,都是maxTagCount这个字段,不知maxCount是哪里查到的
> 
> ```
> <ProFormSelect
>     name="purifierBrand2"
>     colProps={{ md: 12, xl: 4 }}
>     label="品牌"
>     options={[11,22,33,44,55,66,77]}
>     mode='tags'
>     debounceTime={300}
>     fieldProps={{
>       maxTagCount:2 
>     }}
>   />
> ```
这两个不一样

![image](https://github.com/ant-design/pro-components/assets/52907799/ef29f520-8ef5-4420-99cb-9b0fcf25f077)

**Comment by Onion17** [comment]
版本问题，ant design 5.13.1可以使用
