### ISSUE TITLE
🧐[问题] ProLayout 窄屏幕情况下，怎么让菜单不变成抽屉形式展示？

### ISSUE THREAD

**Issue by mzl980425** [ant-design/pro-components#8131]
### 🧐 问题描述

正常窄屏幕情况下，ProLayout 的顶部菜单和侧边菜单都会变成左侧抽屉形式展示。
但是我不希望窄屏幕情况下菜单变成抽屉形式展示，希望仍然按大屏幕情况平铺展示，请问该怎么做？

我尝试了 `breakpoint={false}` `isMobile={false}` `collapsed={false}` 均不奏效

### 💻 示例代码

```jsx
<ProLayout
  siderWidth={180}
  collapsed={false}
  breakpoint={false}
  isMobile={false}
>
</ProLayout>
```

### 🚑 其他信息

![image](https://github.com/ant-design/pro-components/assets/22958600/db28ee5f-4463-4896-883b-2c08ef946c72)
![image](https://github.com/ant-design/pro-components/assets/22958600/b0dc782d-11bd-4d55-b979-ed136aa2be3d)

**Comment by ONLY-yours** [comment]
有一个 disableMobile 可以关闭移动模式 @mzl980425

**Comment by mzl980425** [comment]
> 有一个 disableMobile 可以关闭移动模式 @mzl980425

感谢！有用！原来文档里有写
