### ISSUE TITLE
🐛[BUG] antd.xxx 语法在 nextjs 中不起作用。

### ISSUE THREAD

**Issue by LengYXin** [ant-design/pro-components#8134]
### 🐛 bug 描述
提交PR 更改一下？
![image](https://github.com/ant-design/pro-components/assets/19631404/a5426466-37a0-4c78-9d53-fe4d109d6cf6)
<img width="1689" alt="image" src="https://github.com/ant-design/pro-components/assets/19631404/cd20f8ab-ac8d-439e-9ecd-cbec7f5fb93b">
![image](https://github.com/ant-design/pro-components/assets/19631404/cf0d2b7d-0409-4704-9d5b-7a73c89e52c0)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题描述中提到了在nextjs中使用antd.xxx语法不起作用的问题，可能的解决方案如下：

1. 确保antd和相关依赖包已经正确安装，并且版本兼容。可以使用`npm ls antd`或者`yarn list antd`来查看antd及其依赖的版本。

2. 检查是否在nextjs的_app.js或者其他需要引入antd的文件中正确引入了antd的样式文件。在_next.js中，可以在_app.js文件中引入antd的样式文件，例如：`import 'antd/dist/antd.css'`。

3. 检查是否正确引入了antd组件。在使用antd组件之前，需要先导入相应的组件，例如：`import {Button} from 'antd'`。

4. 如果还是无法解决问题，可以尝试将antd的babel配置加入到nextjs的配置文件中。在next.config.js文件中，添加如下代码：
```javascript
module.exports = {
  ...
  webpack: (config) => {
    config.module.rules.push({
      test: /\.(png|jpe?g|gif|svg)$/i,
      use: [
        {
          loader: 'file-loader',
          options: {
            publicPath: '/_next',
            name: 'static/media/[name].[hash].[ext]',
          },
        },
      ],
    });
    return config;
  },
  ...
};
```

5. 如果还是无法解决问题，可以尝试使用antd的按需加载机制，避免引入整个antd库。可以使用babel-plugin-import插件按需加载antd组件。在.babelrc或babel.config.js文件中添加如下配置：
```javascript
{
  "plugins": [
    ["import", { "libraryName": "antd", "style": "css" }]
  ]
}
```

综上所述，以上是一些可能的解决方案，根据具体的问题和环境情况选择适合自己的解决方案。

**Comment by chenshuai2144** [comment]
我删除了一下。

**Comment by MyZest** [comment]
解决了吗?

    "@ant-design/cssinjs": "1.18.4",
    "@ant-design/icons": "5.3.3",
    "@ant-design/pro-components": "2.6.51",
    "antd": "5.15.2",
    "next": "14.1.0",
    
    还是会报错 
    
    ```js
 ✓ Compiled in 5.4s (7560 modules)
 ⨯ node_modules/@ant-design/pro-form/lib/components/FieldSet/index.js (24:21) @ Group
 ⨯ TypeError: Cannot read properties of undefined (reading 'Group')

````

**Comment by s875515** [comment]
> 解决了吗?
> 
> ```
> "@ant-design/cssinjs": "1.18.4",
> "@ant-design/icons": "5.3.3",
> "@ant-design/pro-components": "2.6.51",
> "antd": "5.15.2",
> "next": "14.1.0",
> 
> 还是会报错 
> 
> ```js
> ```
> 
> ✓ Compiled in 5.4s (7560 modules) ⨯ node_modules/@ant-design/pro-form/lib/components/FieldSet/index.js (24:21) @ Group ⨯ TypeError: Cannot read properties of undefined (reading 'Group')

next@14.0.2 works for me.

**Comment by xwan2034** [comment]
![image](https://github.com/ant-design/pro-components/assets/162288806/ce30230f-743c-4abe-9b1f-9322b3206d1f)
主要是这个原因造成的吧
