### ISSUE TITLE
🐛[BUG]ProFormText被禁用时鼠标的样式不正确

### ISSUE THREAD

**Issue by hans000** [ant-design/pro-components#8136]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
禁用时，鼠标的样式不对
![image](https://github.com/ant-design/pro-components/assets/26105827/de7aa352-59ff-42d8-97f1-74699d173497)
![image](https://github.com/ant-design/pro-components/assets/26105827/ed9b8b34-18f9-4d29-b376-370c2f13551e)

### 📷 复现步骤
```
      <ProFormText fieldProps={{
        variant: 'filled'
      }} initialValue={'xddd'} name={'name'} disabled />
      <ProForm.Item name={'name'} initialValue='xxx'>
        <Input variant='filled' disabled />
      </ProForm.Item>
```

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
antd官网也这样了，估计是bug，等antd下周修复把
