### ISSUE TITLE
👑 [需求]ProLayout 左侧菜单收缩时 宽度可以自定义

### ISSUE THREAD

**Issue by Zhang-ZhuYan** [ant-design/pro-components#814]
### 🥰 需求描述
左侧菜单收缩时是48px，对我来说有点窄。antd的Layout收缩宽度80px，这个比较符合我的需求

![image](https://user-images.githubusercontent.com/32959014/96841853-e0824280-147e-11eb-821f-494e885ccfc2.png)

![image](https://user-images.githubusercontent.com/32959014/96841738-bb8dcf80-147e-11eb-9aa2-2161855384d7.png)

**Comment by chenshuai2144** [comment]
样式太复杂了，所以不会支持的，你可以用 css 强制覆盖一下。
或者你可以给 antd 提个 pr，让它可以动态的设置各种样式

**Comment by chenshuai2144** [comment]
e
