### ISSUE TITLE
🧐[问题]请问ProTable使用request以后，怎么手动刷新表格数据？

### ISSUE THREAD

**Issue by fireworksflyaway** [ant-design/pro-components#8141]
请问ProTable使用request参数传入数据以后，我想在我自己做了一些CRUD操作以后，立刻刷新表格数据（也就是立刻发送一次request请求），请问要怎么操作才能实现？

**Comment by json-q** [comment]
ProTable有提供actionRef属性，额外提供有的instance，可以手动reload表格请求

**Comment by WuYiZhan** [comment]
actionRef.current.reload();

**Comment by fireworksflyaway** [comment]
谢谢解答
