### ISSUE TITLE
🧐[问题] EditableProTable的columns在配置request时，只会触发一次请求，和ProSelect的request不一致

### ISSUE THREAD

**Issue by json-q** [ant-design/pro-components#8142]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

EditableProTable 放在了 DrawerForm 中，关闭时销毁，发现 ProSelect 在打开时会重新触发 request，而同样在其中 EditableProTable columns 的 request 不会，是本来就这么设计的吗？

**Comment by json-q** [comment]
已在 issue 中找到相同问题，感谢！

**Comment by chenzs33** [comment]
> 已在 issue 中找到相同问题，感谢！

大佬，请问怎么解决的
