### ISSUE TITLE
🧐[问题]antdTablePro 怎么才能让 tableAlertRender 一直出现并且不要多选功能

### ISSUE THREAD

**Issue by LiuYyunHao** [ant-design/pro-components#8144]
### 🧐 问题描述
使用antdTablePro组件 发现tableAlertRender 依赖于rowSelection 目前想让tableAlertRender一直出现并且不需要多选功能

**Comment by ONLY-yours** [comment]
感觉你需要的是一个单独渲染的区域，试试tableExtraRender？
