### ISSUE TITLE
🐛[BUG] Pro-Table type='form'时 配置validateMessages 模板取不到label的值 显示undefined

### ISSUE THREAD

**Issue by ziitar** [ant-design/pro-components#816]
### 🐛 bug 描述
Pro-Table type='form'时 配置validateMessages 模板取不到label的值 显示undefined

### 📷 复现步骤
设置type="form" 配置validateMessages: {required: "${label} 是必选项"}, 设置表单必选，点击提交校验显示 ‘undefined 是必选项’

### 🏞 期望结果
期望能显示"${label} 是必选项" label为对应的FormItem的label属性

### 💻 复现代码
https://codesandbox.io/s/mystifying-antonelli-c7hp2

### © 版本信息

- ProTable 版本: [2.6.3]
- antd 版本: [4.4.3]
- umi 版本 [2.x]
- 浏览器环境 [chrome]
- 开发环境 [window10]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/33385784/96864260-b8a0d800-149a-11eb-8803-d960e140aa1f.png)

**Comment by chenshuai2144** [comment]
升级一下版本，已经修掉了

**Comment by ziitar** [comment]
升级到最新版本又有新问题， https://codesandbox.io/s/loving-neumann-ilizj?file=/App.tsx  如何将输入框属性传给输入框？用fieldProps似乎不行，以及使用form的initialValues属性设置Switch组件初始值不生效， console会警告`value` is not a valid prop, do you mean `checked`? 给formItemProps.valuePropName: "checked" 赋值了

**Comment by chenshuai2144** [comment]
你的写法过于大杂烩了，先学习一下 antd 的用法。

日历框的 value 应该是个 moment 对象， 而且它不应该被设置 valuePropName。

protable 中 label 被处理过了已经不是一个 string，你可以用 fieldProps.messageVariables 来自定义一个变量


```tsx
fieldProps={{
messageVariables:{test:"all"},
 validateMessages: { required: "${test} 是必选项" },
}}
```
