### ISSUE TITLE
🐛[BUG] ProTable searchbar broken in antd 4.7.1

### ISSUE THREAD

**Issue by arifszn** [ant-design/pro-components#818]
After updating `antd` from 4.7.0 to 4.7.1, the searchbar of Protable gets broken.

antd version 4.7.0: 
![image](https://user-images.githubusercontent.com/45073703/96922256-69c26500-14d1-11eb-9cd2-c5d883033dc3.png)

antd version 4.7.1:
![image](https://user-images.githubusercontent.com/45073703/96922378-94142280-14d1-11eb-88d6-7e7ebc9e9962.png)

So far I have found that the class `ant-input-affix-wrapper` is removed in updated version.

![image](https://user-images.githubusercontent.com/45073703/96922826-32a08380-14d2-11eb-98e3-9ca14cb81bd8.png)

**Comment by arifszn** [comment]
`margin-right` is missing.

![image](https://user-images.githubusercontent.com/45073703/96960205-97d09500-1523-11eb-84d8-4b580485b92d.png)

**Comment by chenshuai2144** [comment]
I will update it
