### ISSUE TITLE
🧐[问题] ProLayout 左侧菜单如何增加折叠展开过渡动画？

### ISSUE THREAD

**Issue by tucke** [ant-design/pro-components#819]
### 🧐 问题描述

ProLayout 左侧菜单如何增加折叠展开过渡动画？感觉目前折叠展开太过生硬了！

**Comment by afc163** [comment]
这个确实应该有，我记得之前的版本是支持的。

**Comment by tucke** [comment]
菜单的折叠加入动画之后， 与 layout-header 衔接有些小瑕疵
