### ISSUE TITLE
ProTable列类型选择indexBorder居中无效的问题

### ISSUE THREAD

**Issue by eaglewa** [ant-design/pro-components#82]
### 🐛 bug 描述

ProTable列类型选择indexBorder居中无效的问题

### 📷 复现步骤

    {
      title: "序号",
      dataIndex: "index",
      align: "center",
      valueType: "indexBorder",
      width: 30,
    },
### 🏞 实际结果

![image](https://user-images.githubusercontent.com/1741081/89139945-df720100-d572-11ea-9658-7bcd3aa062c8.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by afc163** [comment]
indexOrder ?

**Comment by eaglewa** [comment]
![image](https://user-images.githubusercontent.com/1741081/89140383-1694e200-d574-11ea-9823-1387486282f3.png)
indexOrder是什么意思

**Comment by chenshuai2144** [comment]
你可以这么实现
```
{
  title: "序号",
  dataIndex: "index",
  align: "center",
  valueType: "indexBorder",
  width: 30,
  render:(dom)=><div style={{display:"flex",justifyContent:"center"}}>{dom}</div>
},
```

不过一个 index 列，不应该太宽了
