### ISSUE TITLE
🐛[BUG]defaultOpenKeys 配置默认展开子菜单不生效

### ISSUE THREAD

**Issue by yingzhiji** [ant-design/pro-components#822]
### 🐛 bug 描述

配置了 defaultOpenKeys，但是对应的子菜单并没有展开

### 📷 复现步骤

最小可复现仓库：https://github.com/yingzhiji/pro-layout-bug.git

### 🏞 期望结果

展开对应的子菜单

**Comment by yingzhiji** [comment]
这个目前有解决办法吗

**Comment by chenshuai2144** [comment]
试了一下，要把 openKeys 设置为 undefined ，然后才能配置，但是自动选中的功能就没了，需要慎重使用

**Comment by yingzhiji** [comment]
是因为使用了受控属性的原因吗

**Comment by chenshuai2144** [comment]
嗯 ，受控了会覆盖了 defaultOpenKeys

**Comment by yingzhiji** [comment]
请问这个打算修复吗？受控组件应该是通过 openKeys 来设置初始值的，但是我设置了 openKeys 之后就导致点击菜单无法收起和展开了

**Comment by chenshuai2144** [comment]
不是问题，设计就是这样的，你受控了自然要完全自己控制展开收起和选中。不可能一会受控一会不受控

openKeys 要和 onOpenChange 一起用，不能使用 layout 自己的逻辑了

**Comment by purgeyao** [comment]
defaultOpenKeys 不生效 和楼上讲的一样 而且设置openKeys 后有的就不可以打开了 @chenshuai2144

**Comment by chenshuai2144** [comment]
只有第一个渲染有用的

**Comment by yingzhiji** [comment]
受控的写法怎么在 umi-plugin-layout 里用

**Comment by calmchang** [comment]
在menuProps里配置 openKeys 和 onOpenChange 来解决吧
我的菜单通过 menuDataRender 动态渲染的，用上面的方法解决的

**Comment by happyjosh** [comment]
其实是生效了，只是你默认选中其他一级菜单，会自动关闭展开的二级菜单。所以需要在menu字段内autoClose给成false。
