### ISSUE TITLE
🐛[BUG] 新版本From 组件的 `bordered`属性未修改为 `variant`，导致控制台warn

### ISSUE THREAD

**Issue by Orange-Yellow** [ant-design/pro-components#8225]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

![image](https://github.com/ant-design/pro-components/assets/40858423/5662b992-95f5-4b72-bd30-1b765fa37b7d)

### 📷 复现步骤
master 中代码还是 `bordered`

![image](https://github.com/ant-design/pro-components/assets/40858423/2034b911-5d38-4212-b083-c3ecc4bbeda1)

### © 版本信息

- ProComponents 版本: [2.6.49]
- umi 版本 [4.1.2]
- 浏览器环境 chrome
- 开发环境 [ubuntu 20.04]

**Comment by leshalv** [comment]
已经修复了，还没发版

**Comment by Orange-Yellow** [comment]
> 已经修复了，还没发版

预计什么时候发版？

**Comment by chenshuai2144** [comment]
昨天发布掉了，试试
