### ISSUE TITLE
🧐[问题]请问这个配置属性在哪里 SubmitterProps

### ISSUE THREAD

**Issue by Augustzyh** [ant-design/pro-components#823]
### 🧐 问题描述
找不到submit的配置，以及其他类型表单提交表单提交区域，更简单的配置方法
![image](https://user-images.githubusercontent.com/38031220/96965428-b8f2af00-153e-11eb-8bfd-39ba338d5db6.png)

**Comment by chenshuai2144** [comment]
```
submit={{
// 这个对象
}}
```
里面有提交按钮的配置
