### ISSUE TITLE
🧐[问题] ProTable的column 筛选项如何从request远程数据中设置默认值？

### ISSUE THREAD

**Issue by bryantnathan** [ant-design/pro-components#8233]
文档中column只有request指定获取远程筛选项的接口，但是initialValue 属性是不是可以指定request接口返回的数据呢？

**Comment by chenshuai2144** [comment]
ProForm 是支持的，你可以试试 ，但是时序问题可能比较麻烦。因为 表格发起请求也需要表单的值


```
 <ProTable<DataType, Params, ValueType>
          search={false}
          options={false}
          pagination={false}
          rowKey={rowKey}
          form={{
            request: async () => {
              return {};
            },
          }}
```

**Comment by zhouzhouya1** [comment]
> ProForm 是支持的，你可以试试 ，但是时序问题可能比较麻烦。因为 表格发起请求也需要表单的值
> 
> ```
>  <ProTable<DataType, Params, ValueType>
>           search={false}
>           options={false}
>           pagination={false}
>           rowKey={rowKey}
>           form={{
>             request: async () => {
>               return {};
>             },
>           }}
> ```
还是不行， 我的需求是 页面初始化 根据query参数来 筛选项展示出来并且 根据这些参数返回数据

**Comment by zhouzhouya1** [comment]
有解决的办法， 链接：https://blog.csdn.net/nickroprak/article/details/123052355
