### ISSUE TITLE
🐛[BUG] 使用DragSortTable 传入的components.body无效

### ISSUE THREAD

**Issue by gcdxuzhiwei** [ant-design/pro-components#8239]
![截屏2024-03-20 10 57 28](https://github.com/ant-design/pro-components/assets/62184079/e3655a97-bad7-48db-b5d7-8304070eaa4e)
看源码是把传入的覆盖了

提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by gcdxuzhiwei** [comment]
🐛 bug 描述
components传了
`{
            body: {
              row: (_props) => (
                <Dropdown
                  menu={{
                    items: contextMenuConfig.items,
                    onClick: (menuInfo) => {
                      contextMenuConfig.onItemClick({
                        row: contextMenuRow.current,
                        menuInfo,
                      })
                    },
                  }}
                  trigger={['contextMenu']}
                >
                  <tr {..._props} />
                </Dropdown>
              ),
            },
          }`
正常情况下protable可以右键弹出菜单，但当使用DragSortTable时没有菜单

© 版本信息
ProComponents 版本: [e.g. 2.6.49]
umi 版本
浏览器环境
开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
不覆盖会导致拖拽时效的，自己管理的难度还挺高的，你可以试试
