### ISSUE TITLE
🧐[问题]请问StepForm底部的Button能不能自定义

### ISSUE THREAD

**Issue by wood3n** [ant-design/pro-components#824]
### 🧐 问题描述

从[`stepsform`](https://procomponents.ant.design/components/form/#stepsform)的文档来看，没看明白支不支持自定义底部表单的操作按钮，我这边需求是需要在上一步，下一步这里添加额外的按钮，不知道是否满足

### 💻 示例代码
无
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/31716713/96967049-754d7480-1541-11eb-9e78-62bb6225aa43.png)

**Comment by wood3n** [comment]
有点没明白这个设计，`submitter`这个`props`放到`StepsForm`上干嘛呢？不能放在`StepForm`上吗？

**Comment by chenshuai2144** [comment]
@wood3n  为了方便把 submitter 放到任何地方去，StepForm 只能设置 自己的。

**Comment by quarkcms** [comment]
@chenshuai2144 form的button如何设置layout
![image](https://user-images.githubusercontent.com/60868863/96992914-27df0080-155d-11eb-8ee9-307c0b7ed869.png)

**Comment by wood3n** [comment]
> @wood3n 为了方便把 submitter 放到任何地方去，StepForm 只能设置 自己的。

那还可以自定义`StepForm`底部的按钮吗？还有一个问题是，当`ProForm`和`StepForm`被`StepsForm`包裹起来的时候，`wrapperCol` | `labelCol`都不支持了！

**Comment by chenshuai2144** [comment]
提个新issue把 proform系列支持的都有点问题

**Comment by chenshuai2144** [comment]
@quarkcms 你是怎么写的？我们应该会自动的设置 layout

**Comment by quarkcms** [comment]
@chenshuai2144 

![微信截图_20201026082538](https://user-images.githubusercontent.com/60868863/97123066-e0c35c00-1764-11eb-83a4-4a0ce26ca3d0.png)

**Comment by quarkcms** [comment]
layout设置的是horizontal

**Comment by quarkcms** [comment]
@chenshuai2144 帅哥帮忙查一下吧

**Comment by quarkcms** [comment]
还有表格可编辑可以用了吗？

**Comment by wood3n** [comment]
@quarkcms 大兄弟，提个新issue吧，我自己的问题都被埋没了😅

**Comment by xingming2020** [comment]
> @chenshuai2144 form的button如何设置layout ![image](https://user-images.githubusercontent.com/60868863/96992914-27df0080-155d-11eb-8ee9-307c0b7ed869.png)

StepForm设置`layout='horizontal'`之后submitter无法保持对齐，有解决方案吗？ @chenshuai2144

**Comment by chenshuai2144** [comment]
加个百分比margin
