### ISSUE TITLE
🧐[columnsState修改后刷新都会恢复为defaultValue]

### ISSUE THREAD

**Issue by MachiBarton** [ant-design/pro-components#8240]
### 🧐 columnsState修改后刷新都会恢复为defaultValue

columnsState修改Column Display之后刷新页面，会恢复到defaultValue数据

### 💻 示例代码

`columnsState={{
            defaultValue: columnsStateMap,
            persistenceKey:'node-table',
            persistenceType:'localStorage'
          }}`

是否应当判断已有缓存的情况下则忽略defaultValue

**Comment by s045pd** [comment]
+1  我原本是好的，版本升级后出现了这个问题
有办法可以解决（去掉defaultValue，前置初始化往localstorage预判写入columnsStateMap）但感觉太蠢啦

**Comment by MachiBarton** [comment]
> +1 我原本是好的，版本升级后出现了这个问题 有办法可以解决（去掉defaultValue，前置初始化往localstorage预判写入columnsStateMap）但感觉太蠢啦

官方没适配的时候，我自己是这么封装的。以为官方内置了可以直接迁过去，结果现在看，还是用自己的
