### ISSUE TITLE
🐛[BUG]pro-table卸载后仍然setState

### ISSUE THREAD

**Issue by Hikarien** [ant-design/pro-components#825]
### 🐛 bug 描述
现象参照 #693 #121 

![image](https://user-images.githubusercontent.com/41961907/96969139-9368a400-1544-11eb-9acd-49dc9bedab1e.png)

### 📷 复现步骤

我这边2.9.3版本之前是正常的，从2.9.4版本开始有问题了

### 🏞 期望结果

无该警告。

### 💻 复现代码

这里我封装了一个内置的pro-tabe的select，在pro-table的search的form里可以下拉选择。
![image](https://user-images.githubusercontent.com/41961907/96969346-f1958700-1544-11eb-9ad5-137482af2a33.png)

正常情况：
![image](https://user-images.githubusercontent.com/41961907/96969486-2acdf700-1545-11eb-889e-ab4fe010725c.png)

### © 版本信息

- ProComponents 版本: pro-table 2.9.4后必复现
- umi 版本
- 浏览器环境 Chrome
- 开发环境 macOS

**Comment by chenshuai2144** [comment]
网络请求的问题吧。你是不是异步去访问网络了

**Comment by Hikarien** [comment]
@chenshuai2144 
改成`manualRequest={true}`了，不发网络请求的情况下，还是有报错，但是和之前不太一样
帅哥可以帮忙再看看嘛😭😭😭
![image](https://user-images.githubusercontent.com/41961907/96998780-ad1ae300-1566-11eb-8f36-4702b2ade069.png)

**Comment by Hikarien** [comment]
再查了一下pro-table的dom已经有了，但是没渲染出来，应该是我这边的问题

我再进一步排查吧
