### ISSUE TITLE
🧐pro-table中，request里的params参数可以去掉pagesize和current吗

### ISSUE THREAD

**Issue by DunDunDunAbandon** [ant-design/pro-components#827]
### 🧐 问题描述

request里的params每次只刷新页面不查询的话不是都会主动发送pagesize和current吗，但我现在只想实现一个最简单的表格页面，就是从后端返回一条数据显示在表格里，不需要分页用的pagesize和current，该怎么处理呢？找了半天也没看到是怎么封装了params可以主动只发送这俩参数的。

**Comment by chenshuai2144** [comment]
加个分层，或者不要管。
request={(params)=>  {
   delete params.pageSize;
   delete params.current;
  // you request
} }

**Comment by DunDunDunAbandon** [comment]
> 加个分层，或者不要管。
> 
> ```tsx
> request={(params)=>  {
>    delete params.pageSize;
>    delete params.current;
>   // you request
> } }
> ```



> 加个分层，或者不要管。
> 
> ```tsx
> request={(params)=>  {
>    delete params.pageSize;
>    delete params.current;
>   // you request
> } }
> ```

不管的话后端不是要写关于pagesize和current的返回吗，没有这些返回的话数据在表格就显示不出来？我request都返回数据了但是数据显示不到表格里。。
