### ISSUE TITLE
🐛[BUG] procomponents 官网菜单显示不完全

### ISSUE THREAD

**Issue by jwors** [ant-design/pro-components#8279]
### 🐛 bug 描述
https://procomponents.ant.design/components 菜单栏显示不完全

### 🏞 期望结果

希望可以看到完整的菜单栏目

### © 版本信息
 谷歌浏览器 -version 123

### 🚑 其他信息
![image](https://github.com/ant-design/pro-components/assets/47352910/98f3d49f-b6c7-41c8-bb9a-5356eaee8328)

**Comment by Wxh16144** [comment]
主题那边已经修复了 https://github.com/arvinxx/dumi-theme-antd-style/pull/35 需要升级主题依赖。
