### ISSUE TITLE
🧐[问题]sorter的状态无法清除

### ISSUE THREAD

**Issue by lwbweb** [ant-design/pro-components#828]
### 🧐 问题描述

排序后进行操作，函数内使用ref.current.reset();，无法重置sort的状态，sorter为服务端排序，在columns中设置为sorter:true,看issues说有ref.current.reloadAndRest()函数，也不生效，pro-table的2.4.0、升级到2.9.11项目就出错了

![image](https://user-images.githubusercontent.com/17756413/97071062-130f7500-1610-11eb-89fa-2875e47da12f.png)

### 💻 示例代码
// 重置到默认值
ref.current.reset();
使用reset无法清除sort的状态、reload无法清除

**Comment by chenshuai2144** [comment]
这个现在不是受控的，所以无法清除

**Comment by cc7gs** [comment]
升级报错是你 antd版本没有同步升级 #836

**Comment by chenshuai2144** [comment]
dup of  https://github.com/ant-design/pro-components/issues/1581
