### ISSUE TITLE
🐛[BUG] 文档中表单 autoFocusFirstInput 没有默认值，但是实际使用的时候是 true

### ISSUE THREAD

**Issue by tchen-l** [ant-design/pro-components#8289]
### 🐛 bug 描述

文档中表单 autoFocusFirstInput 没有默认值，但是实际使用的时候会聚焦第一个表单项

### 📷 复现步骤
https://codesandbox.io/p/sandbox/floral-bush-yngm58?file=%2FApp.tsx%3A6%2C23

### 🏞 期望结果

默认不聚焦第一个表单项

### © 版本信息

- ProComponents 版本: [e.g. 2.6.52]
- 浏览器环境: [Chrome 123.0.6312.107]
- 开发环境 [e.g. mac OS]

**Comment by zhuba-Ahhh** [comment]
文档没写清楚，不传默认是true的

**Comment by tchen-l** [comment]
> 文档没写清楚，不传默认是true的

了解了
