### ISSUE TITLE
🐛[BUG] ProTable reset时toolbar中搜索值无法清除

### ISSUE THREAD

**Issue by gracezlj** [ant-design/pro-components#830]
### 🐛 bug 描述

ProTable toolbar中设置搜索的case，调用actionRef.current.reset()，搜索值无法清除

### 📷 复现步骤

[见demo](https://codesandbox.io/s/cool-yalow-u3q43?file=/App.tsx)

1. 输入值搜索，查看console params值
2. 点击table重置按钮，查看console params值对比，发现keyword未清除

![image](https://user-images.githubusercontent.com/1772807/97078930-7f936f80-1622-11eb-8d6d-f570ef6a9d07.png)

### 🏞 期望结果

reset时toolbar搜索值可清除

### 💻 复现代码

[codesandbox demo](https://codesandbox.io/s/cool-yalow-u3q43?file=/App.tsx)

### © 版本信息

- ProTable 版本: 2.9.7
- umi 版本: 3.2.24
- 浏览器环境: chrome
- 开发环境: mac OS

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/834
