### ISSUE TITLE
🧐[问题] 如何修改表单搜索框和表格间距

### ISSUE THREAD

**Issue by uaena001** [ant-design/pro-components#8319]
### 🧐 问题描述

我想修改search和表格的间距，使用search={{className: 'searchForm',}}没有效果
<img width="766" alt="Snipaste_2024-04-18_13-55-29" src="https://github.com/ant-design/pro-components/assets/102605409/2682a5e6-a92d-45e4-8b83-17adb120dc85">

`search={{className: 'searchForm',}}
.searchForm {
  padding-bottom: 0;
}`

**Comment by Ahong303** [comment]
能告诉我吗，怎么搞吗？
