### ISSUE TITLE
🐛[BUG]pro-component2.7.0 升级到 2.7.2 

### ISSUE THREAD

**Issue by lsy934127847** [ant-design/pro-components#8323]
pro-components -- 2.7.2
umi3.5 
react - 17

4.16号的时候还没问题  最近一天 里面所依赖的 table  等都升级了一个版本  导致bug

![image](https://github.com/ant-design/pro-components/assets/72968089/9823c9ec-9bd4-47b8-a27d-28f4e79edef2)

![image](https://github.com/ant-design/pro-components/assets/72968089/7bda3f98-5ccd-4d4e-8702-a8b67c67d614)

**Comment by xuxusheng** [comment]
+1

**Comment by chenshuai2144** [comment]
已经回滚掉了，兼容性没做好

**Comment by lsy934127847** [comment]
> 已经回滚掉了，兼容性没做好

不用发新版本吗

**Comment by chenshuai2144** [comment]
回滚就安装不上了，新版本再说
________________________________
发件人: lsy934127847 ***@***.***>
发送时间: 2024年4月19日 13:53
收件人: ant-design/pro-components ***@***.***>
抄送: 陈帅 ***@***.***>; State change ***@***.***>
主题: Re: [ant-design/pro-components] 🐛[BUG]pro-component2.7.0 升级到 2.7.2 (Issue #8323)


已经回滚掉了，兼容性没做好

不用发新版本吗

**Comment by lsy934127847** [comment]
为什么还会下载 2.7.2 的版本









2019（天猫邀请）
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月19日(星期五) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 🐛[BUG]pro-component2.7.0 升级到 2.7.2  (Issue #8323)





 回滚就安装不上了，新版本再说 
 ________________________________ 
 发件人: lsy934127847 ***@***.***&gt; 
 发送时间: 2024年4月19日 13:53 
 收件人: ant-design/pro-components ***@***.***&gt; 
 抄送: 陈帅 ***@***.***&gt;; State change ***@***.***&gt; 
 主题: Re: [ant-design/pro-components] 🐛[BUG]pro-component2.7.0 升级到 2.7.2 (Issue #8323) 
 
 
 已经回滚掉了，兼容性没做好 
 
 不用发新版本吗

**Comment by lsy934127847** [comment]
有没有内推



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 陈帅 ***@***.***&gt;
发送时间: 2024年4月19日 14:24
收件人: ant-design/pro-components ***@***.***&gt;
抄送: lsy934127847 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ant-design/pro-components] ��[BUG]pro-component2.7.0 升级到 2.7.2  (Issue #8323)





 回滚就安装不上了，新版本再说 
 ________________________________ 
 发件人: lsy934127847 ***@***.***&gt; 
 发送时间: 2024年4月19日 13:53 
 收件人: ant-design/pro-components ***@***.***&gt; 
 抄送: 陈帅 ***@***.***&gt;; State change ***@***.***&gt; 
 主题: Re: [ant-design/pro-components] 🐛[BUG]pro-component2.7.0 升级到 2.7.2 (Issue #8323) 
 
 
 已经回滚掉了，兼容性没做好 
 
 不用发新版本吗
