### ISSUE TITLE
🧐[问题]ProTable的自定义表单项，怎么从第三个参数form中获取表单数据？

### ISSUE THREAD

**Issue by shangfeiSF** [ant-design/pro-components#833]
### 🧐 问题描述
官网ProTable的示例代码，和期望的不一致
https://procomponents.ant.design/components/table#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%8D%95%E9%A1%B9
` const status = form.getFieldValue('state');`
一直拿到的是undefined

### 💻 示例代码
```
renderFormItem: (_, { type, defaultRender, ...rest }, form) => {
  if (type === 'form') {
    return null;
  }
  const status = form.getFieldValue('state');
  if (status !== 'open') {
    return <Input {...rest} placeholder="请输入" />;
  }
  return defaultRender(_);
};
```

**Comment by SilentFlute** [comment]
我也遇到了这个问题, 我是开发环境是ok的, 但是部署到测试就出现这个问题了, 部署到测试之后renderFormItem方法只在页面第一次渲染的时候执行, 后面就不再执行了, 导致结果不符合预期
最后本地打包, 配置nginx之后本地运行, 是ok的, 于是确定了是我本地和服务器node版本不一致导致的, 最后将本地打包产物提交到仓库中, 然后部署的时候直接用即可, 不再单独打包
本地node版本: 12.16.3
服务器node版本: 12.18.1

**Comment by SilentFlute** [comment]
我本地是windows环境, 服务器linux环境, 此种情形下的解决方法是提交本地打包产物给服务器使用, 但后来有位mac的小伙伴加入进来了, 他本地开发环境也是有问题, 而且node版本还是跟我一样的, 最后是使用了奇淫技巧: 添加了一个强制re-render的state, 然后每次将该state做取反操作, 那么此时render方法重新执行, 然后renderFormItem方法也重新执行, 此时就能再次form.getFieldValue获取值了, 希望对你有帮助, 但最根本的解决方法还是希望开发人员能从组件代码中着手去解决这个问题

**Comment by chenshuai2144** [comment]
性能优化搞出来的东西，我来修一下
