### ISSUE TITLE
🐛[BUG]:打包之后useControlModel这个方法ts类型检查错误

### ISSUE THREAD

**Issue by 1353823765** [ant-design/pro-components#8332]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
本地开发正常，打包显示ts类型错误 具体在
export declare function useControlModel<T extends FormControlProps>({ value, onChange, id }: WithControlPropsType, model?: T): ControlModelType;
export declare function useControlModel<const T extends readonly string[]> ({ value, onChange, id }: WithControlPropsType, model ?: T): {
  [P in T[number]]: ControlModelType;
};
export declare function useControlModel<const T extends readonly FormControlMultiProps[]> ({ value, onChange, id }: WithControlPropsType, model ?: T): {
  [P in GetArrayFieldType<T>]: ControlModelType;
};

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
dup of #8330

**Comment by yummyLcj** [comment]
参考 https://github.com/ant-design/pro-components/issues/8217
估计对ts版本更新了
