### ISSUE TITLE
组件的类型没有全部导出，只导出了一部分🐛[BUG]

### ISSUE THREAD

**Issue by ctliz** [ant-design/pro-components#8370]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

安装@ant-design/pro-components后，ProFormCheckboxGroupProps类型可以导出，但是ProFormCheckboxProps无法导出，看源码应该是忘记了，只导出了一个类型。
### 📷 复现步骤
问题很清晰，导入ProFormCheckboxProps即可看到类型报错，
### 期望
ProFormCheckboxProps 可以导出

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

未导出状态
![image](https://github.com/ant-design/pro-components/assets/26066413/0f373449-5be5-41a4-a097-5387aa5003d2)
修改源代码后
![image](https://github.com/ant-design/pro-components/assets/26066413/ffc584c4-681f-4085-b3fd-a62d4d4551a7)
成功导出
![image](https://github.com/ant-design/pro-components/assets/26066413/67892a84-7a28-4440-b6b1-71587c1a43ef)

**Comment by zhuba-Ahhh** [comment]
还有这类的
<img width="1019" alt="image" src="https://github.com/ant-design/pro-components/assets/84793349/a24d66f8-c030-4468-8ce0-c9e95a572b3d">
