### ISSUE TITLE
🐛[pro-table 搜索表单自定义组件获取数据后渲染问题]

### ISSUE THREAD

**Issue by cc7gs** [ant-design/pro-components#838]
### 🐛 bug 描述

通过自定义组件数据远程获取数据后，渲染`select`组件默认开发了虚拟滚动，但是拖到滚动条时，页面报错。

### 📷 复现步骤

1. 自定义请求

2. 搜索表单中拖动滚动条

### 🏞 期望结果

期望滚动时页面不保持。

### 💻 复现代码
```ts
const queryTypes=async ()=>{ ....};

const columns=[
  {
    title: '场景',
    dataIndex: 'scene',
    initialValue:'all',
    request:queryTypes,
    // fieldProps:{
    //   virtual:false
    // },
    sorter: true,
  }
]
```

### © 版本信息

- pro-table 版本: [2.9.11]
- umi 版本 [3.2.0]
- 浏览器环境 [chrome 86]
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

**页面显示效果**

![image](https://user-images.githubusercontent.com/36002392/97156097-2c9bf280-17b1-11eb-862b-479964cdffbc.png)

**错误信息**
![image](https://user-images.githubusercontent.com/36002392/97155508-6f10ff80-17b0-11eb-86ad-d144f3cb73cd.png)

**Comment by cc7gs** [comment]
目前通过 fieldProps 关闭了虚拟滚动后可以正常使用

**Comment by chenshuai2144** [comment]
看起来是antd 算出死循环了，antd 里有issue了，在那里跟踪吧。
https://github.com/ant-design/ant-design/issues/27393
