### ISSUE TITLE
🐛[BUG][pro-table]跨页选择时,前一页的选择被清除

### ISSUE THREAD

**Issue by chendanlin** [ant-design/pro-components#839]
### 🐛 bug 描述

当使用网络请求数据时,有不同分页的选择项,最后一页的选择会覆盖之前的选择,导致选择的数据不全

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/35648425/97161499-e34fa100-17b8-11eb-86a8-8f72d1b77ee5.png)
![image](https://user-images.githubusercontent.com/35648425/97161623-0bd79b00-17b9-11eb-8555-26bd33cdd9b0.png)

### © 版本信息

- "@ant-design/pro-table": "^2.4.0",
- "umi": "^3.2.10",
- Edge
- window10

**Comment by dmdoit** [comment]
其实这个问题一直都存在，或许说这不是一个bug，因为使用的是服务器分页，而不是组件自动分页，
之前看到个方案说用onSelect替代onChange使用，是可行的
```
rowSelection={{
  selectedRowKeys,
  // onChange: (selectedRowKeys: number[], selectedRows) => {
  //   console.log(selectedRowKeys);
  // },
  onSelect: (record, selected) => {
    const newSelectedRows = selectedRows.map((item:any) => ({ ...item }));  // currentRows是被选中的行
    const selectIndex = newSelectedRows.findIndex(item => item.Id === record.Id);
    if(selectIndex > -1){
      newSelectedRows.splice(selectIndex, 1)}
    else{
      newSelectedRows.push(record)
    }
   const newSelectedRowKeys:number[] = newSelectedRows.map(item => item.Id);
   setSelectedRows(newSelectedRows);
   setSelectedRowKeys(newSelectedRowKeys);
  }
}}
```

**Comment by zhang0ZGC** [comment]
这应该属于`antd`的特性吧😆可能为了性能，可以像楼上那样处理，或者如果楼主用的最新版`antd`, 自 `antd@4.4.0` 开始，rowSelection 支持参数支持保留key了： https://ant.design/components/table-cn/#rowSelection

![image](https://user-images.githubusercontent.com/10346399/97935257-fb27b600-1db2-11eb-87c2-97a14a2362ba.png)

**Comment by chendanlin** [comment]
preserveSelectedRowKeys属性可以解决这个问题,一直看的proTable的文档,没有发现table的文档已经改了
