### ISSUE TITLE
[问题]ProTable[2.9.12] valueEnum不能动态更新问题

### ISSUE THREAD

**Issue by liuzhenji** [ant-design/pro-components#840]
[Version]
ProTable----2.9.12
ProField----1.0.4

在ProTable的columns参数中，原本可动态修改的valueEnum，现在不能在进行更新使用了。

解决办法：
column定义中新增了一个request参数，用来动态获取valueEnum的值，举例如下：

async () => [
      { label: '全部', value: 'all' },
      { label: '未解决', value: 'open' },
      { label: '已解决', value: 'closed' },
      { label: '解决中', value: 'processing' },
    ]；
其实就是返回个antd Select 组建的options参数。

原因（猜测）：
不知某个版本开始，valueEnum最终作用的组件ProField->Select的实现中，
把通过valueEnum获取options参数的实现逻辑，改为通过useCallback 实现了，且def为[]，此举可能是为了性能优化。
所以，获取的options的值都是我们在使用ProTable时设置的初始值。

以上。

**Comment by liuzhenji** [comment]
最新发现，用request参数也不行，目前有两个问题：

**Comment by GKLL** [comment]
renderFormItem 中自定义Cascader组件的也不能更新

**Comment by dasheng523** [comment]
整个问题建议重开一下，我也遇到这困惑了

**Comment by lyctea** [comment]
我也遇到同样的问题，

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/field#%E8%BF%9C%E7%A8%8B%E6%95%B0%E6%8D%AE

看看这个文档

**Comment by ystarlongzi** [comment]
看这里

https://procomponents.ant.design/components/schema/#request-%E5%92%8C-params
