### ISSUE TITLE
expandable展开属性里嵌套的ProTable是否支持columnsState？

### ISSUE THREAD

**Issue by ytanck** [ant-design/pro-components#8401]
ProTable里的expandable嵌套了一个ProTable，请问嵌套的ProTable是否支持columnsState功能？从我调试看是不支持的

**Comment by fnoopv** [comment]
实测支持

**Comment by ytanck** [comment]
> 实测支持

上点demo？

**Comment by fnoopv** [comment]
https://codesandbox.io/p/sandbox/qian-tao-biao-ge-forked-shrn6m

**Comment by ytanck** [comment]
> https://codesandbox.io/p/sandbox/qian-tao-biao-ge-forked-shrn6m

大佬，可能是我没描述清楚。
外层的ProTable里已经使用了columnsState功能，
expandable里嵌套的ProTable是否还支持columnsState功能，可以和父 同时控制或者里外单独控制

**Comment by fnoopv** [comment]
我给的demo里面就是啊，就是expandable嵌套的表格
![image](https://github.com/ant-design/pro-components/assets/24599198/a2f8cb7c-c5c8-46c3-9fc3-3efac2e12c89)

**Comment by fnoopv** [comment]
而且你可以看 `expandable` 的 `expandedRowRender` 的签名, 返回的是 `ReactNode`，是啥都无所谓，表格、表单等等啥都行

**Comment by ytanck** [comment]
支持解决，谢谢

**Comment by ytanck** [comment]
> https://codesandbox.io/p/sandbox/qian-tao-biao-ge-forked-shrn6m
现在里外层的columnsState是各自单独控制的，可以用一个变量控制吗，就不需要里外都去点击设置隐藏或显示了

**Comment by fnoopv** [comment]
可以啊,  `value` 和 `onChange` 用一个就行, 不过最好两个 `table` 没有相同字段, 不然两个都会同时显示或不显示某个字段

**Comment by ytanck** [comment]
> 可以啊, `value` 和 `onChange` 用一个就行, 不过最好两个 `table` 没有相同字段, 不然两个都会同时显示或不显示某个字段

现在就是需要里外同时显示或隐藏，可以出个demo吗

**Comment by fnoopv** [comment]
https://codesandbox.io/p/sandbox/qian-tao-biao-ge-forked-xtv4dr

**Comment by ytanck** [comment]
> https://codesandbox.io/p/sandbox/qian-tao-biao-ge-forked-xtv4dr

谢谢大佬，demo功能都是正常的。可我按你方法写后会一直触发onchange事件setColumnsState到账死循环

**Comment by ytanck** [comment]
补充下：我添加persistenceKey，persistenceType属性了的

**Comment by fnoopv** [comment]
> 补充下：我添加persistenceKey，persistenceType属性了的

那在两个table中把这两个属性设置相同就可以了

**Comment by ytanck** [comment]
Thank you!
