### ISSUE TITLE
能否把pro-table和model以及connect结合在一起用。

### ISSUE THREAD

**Issue by babizhu** [ant-design/pro-components#841]
### 🧐 问题描述
能否把pro-table和model以及connect结合在一起用。一个page有很多数据，list只是其中的一部分。
当然可以在request的地方直接获取props中的数据，但是这样一来，reload，搜索等功能似乎又废了

**Comment by chenshuai2144** [comment]
这样只能和 antd 一样用它了，很多逻辑都要自己写了
