### ISSUE TITLE
🐛[BUG] pro-components 影响 全局dayjs 解析 gggg-ww 格式

### ISSUE THREAD

**Issue by faner11** [ant-design/pro-components#8424]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
使用pro-components 任意组件都会干扰 dayjs 解析gggg-ww
```js
// 当我没有使用pro-components 时
dayjs("2024-02","gggg-ww").format("YYYY-MM-DD HH:mm:ss") // 2024-02-01 00:00:00
// 当我使用pro-components 时
dayjs("2024-02","gggg-ww").format("YYYY-MM-DD HH:mm:ss") // 2024-05-20 00:00:00
```

### 📷 复现步骤

https://codesandbox.io/p/github/faner11/procomponents-dayjs/main

### 🏞 期望结果

无论是否使用pro-components 组件，dayjs 都可以正常工作

### 💻 复现代码

```ts
import dayjs from 'dayjs';
import { ProTable } from '@ant-design/pro-components';
/**
 * 如果注释ProTable 值为 2024-02-01 00:00:00
 * 如果不注释ProTable 值为 2024-05-20 00:00:00 ，日期为当天
 */
function App() {
  return (
    <>
    {dayjs("2024-02","gggg-ww").format("YYYY-MM-DD HH:mm:ss")}
    <ProTable/>
    </>
  )
}
export default App

```

### © 版本信息

- ProComponents 版本: [e.g. 2.7.9]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="709" alt="image" src="https://github.com/ant-design/pro-components/assets/26560612/de774dc6-64bf-42ef-ac1f-2bcd8ad424f3">

**Comment by fnoopv** [comment]
`dayjs` 的 `format` 参数就没有`g`和`w`, `moment` 有这两个参数, 根本就不支持, 所以从用法上来说你就是错的, 用法正确后再测试是不是 `pro-components` 的问题

**Comment by fnoopv** [comment]
> `dayjs` 的 `format` 参数就没有`g`和`w`, `moment` 有这两个参数, 根本就不支持, 所以从用法上来说你就是错的, 用法正确后再测试是不是 `pro-components` 的问题

更正, 是支持的, 但是需要引用 `advancedFormat` 插件, 然后必须 `dayjs().format('gggg-ww')` 调用

**Comment by faner11** [comment]
@fnoopv 你可以跑一下我提供的demo。我的问题是为什么一样的代码，引入pro-components后输出会不一致。

**Comment by fnoopv** [comment]
首先，问题是的确存在的，但是
1. 如果启用dayjs的严格解析模式`dayjs("2024-02","gggg-ww", true).isValid()`, 你会发现直接报的false，用法本身的确是错的
2. 如果你试一下只用antd，问题也是存在的，说明很大可能是antd引入的，问题提到antd去可能更好，不过基于错误用法导致的错误或者意外不确定官方会不会修
3. 我猜可能是引入`antd`时，`antd` 对dayjs做了某些默认设置，因为dayjshi全局对象

**Comment by faner11** [comment]
我试了一下，如果仅引入 Antd DatePicker 组件也会有这个问题，这应该是Antd 做了什么，我去给他们提个issues
