### ISSUE TITLE
🐛[BUG]官网挂了

### ISSUE THREAD

**Issue by huangkairan** [ant-design/pro-components#8426]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
访问 https://pro-components.antdigital.dev  切换任意路由，白屏

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境 版本 Chrome 124.0.6367.208（正式版本） (arm64)
- 开发环境 [e.g. mac OS] macos 14.0 arm64

**Comment by faner11** [comment]
你浏览器的问题吧，我打开一切正常

**Comment by BigFaceMaster** [comment]
chrome 版本为：Version 124.0.6367.208 (Official Build) (arm64) 的时候 崩溃了

**Comment by BigFaceMaster** [comment]
Version 125.0.6422.61 (Official Build) (arm64) tong同样的
![CleanShot 2024-05-21 at 11 43 16](https://github.com/ant-design/pro-components/assets/15710933/9bb36fa5-2807-4ebb-8c23-85d52b5de26b)

**Comment by bbeas** [comment]
Chrome: Version 124.0.6367.209 (Official Build) (arm64) 同样的问题

**Comment by 7gugu** [comment]
Firefox也一样

**Comment by YangFong** [comment]
Firefox 119.0 (64 位) 正常

Microsoft Edge 125.0.2535.51 (正式版本) (x86_64) 完全打不开

**Comment by TuuuNya** [comment]
俺也打不开。

chrome 版本 124.0.6367.208（正式版本） (x86_64)

**Comment by huangkairan** [comment]
这个没有人跟进吗？
