### ISSUE TITLE
🧐[问题]关于ProTable的request参数问题

### ISSUE THREAD

**Issue by yuzifu** [ant-design/pro-components#844]
ProTable的request方法有三个参数，分别是params/sort/filter，我在一个demo里尝试了一下，有两个疑问：

1，sort只支持一个字段，但是界面效果上却不是如此，在单击一个字段排序后，再单击另一个字段排序，这时两个字段都是会呈现已排序的小三角形。
2，什么动作可以产生filter参数？我尝试了我能想到了方法，都没办法让filter参数有值。

**Comment by chenshuai2144** [comment]
与 antd 是基本相同的。
可以看这个 demo https://ant.design/components/table-cn/#components-table-demo-dynamic-settings

**Comment by MoonSeeing** [comment]
> ProTable的request方法有三个参数，分别是params/sort/filter，我在一个demo里尝试了一下，有两个疑问：
> 
> 1，sort只支持一个字段，但是界面效果上却不是如此，在单击一个字段排序后，再单击另一个字段排序，这时两个字段都是会呈现已排序的小三角形。
> 2，什么动作可以产生filter参数？我尝试了我能想到了方法，都没办法让filter参数有值。

在column 配置filters
