### ISSUE TITLE
ErrorBoundary不支持传入props？

### ISSUE THREAD

**Issue by kylvia** [ant-design/pro-components#8440]
### 🧐 问题描述
当ErrorBoundary捕获异常后，需要把错误信息存储到全局的context中，本来想把dispatch方法作为参数传进ErrorBoundary组件，但发现组件不被支持，所以这儿这样设计的目的是？希望官方大大能支持props的传入。

<img width="819" alt="image" src="https://github.com/ant-design/pro-components/assets/6890744/fced715f-96fd-4d53-95e5-669ed84eccca">

**Comment by chenshuai2144** [comment]
你可以做个自己的 error 来绕开这个限制

**Comment by kylvia** [comment]
好吧，目前也只能不用这个属性了
