### ISSUE TITLE
官网地址打开白屏

### ISSUE THREAD

**Issue by hanjixin** [ant-design/pro-components#8458]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

![image](https://github.com/ant-design/pro-components/assets/30335398/67872769-8ec0-4c94-a69b-60be4c24bcca)

**Comment by Rizo0525** [comment]
我也是这种情况，Google打开白屏，点其他的也会白屏，每次都要刷新才会显示。

**Comment by LeleDallas** [comment]
Same issue here. 
For now I just refresh the page until I see it works.
Seems like a promise is failing
![image](https://github.com/ant-design/pro-components/assets/71103219/ba316cb5-fea2-4020-b523-39f216de2ae0)

**Comment by emeiziying** [comment]
关掉 Redux DevTools 插件就好了。。。

**Comment by codering** [comment]
不知道这网站在干啥。。。。demo就是打不开，一直在转圈圈，一个网页下载了几百M了。。。
<img width="877" alt="image" src="https://github.com/ant-design/pro-components/assets/2271825/92f35fbc-5ba7-423f-9c5d-8e9964f0e4b7">
<img width="821" alt="image" src="https://github.com/ant-design/pro-components/assets/2271825/b700c217-a6d9-4414-a227-0dcbd5d9f960">

**Comment by chenshuai2144** [comment]
demo太多了 本来就是些重型组件

**Comment by xiangrun** [comment]
搞的真垃圾，页面打开都是问题

**Comment by xiangrun** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
