### ISSUE TITLE
🐛[BUG]pro-table的页码page显示的英文

### ISSUE THREAD

**Issue by KellenHe** [ant-design/pro-components#849]
### 🐛 bug 描述

pro-table的页码page显示的英文

### 🏞 期望结果

显示中午

### 💻 复现代码

https://codesandbox.io/s/no5vf?file=/index.tsx

### © 版本信息

pro-table 2.9.12

### 🚑 其他信息
![企业微信截图_16038515588073](https://user-images.githubusercontent.com/9713892/97382774-186a0980-1907-11eb-8cd9-6aa1ed8918ac.png)

**Comment by chenshuai2144** [comment]
配置 antd 的 configProvide， 这个是跟着 antd 走的
