### ISSUE TITLE
🧐[问题]protable自动生成的搜索表单的参数如何获取

### ISSUE THREAD

**Issue by 312107115** [ant-design/pro-components#850]
### 🧐 问题描述
我需要在我写的导出方法方法中获取到protable自动生成的搜索表单的值，根据这些条件去导出相应的数据，protable有提供某个方法获取到这些值么

**Comment by chenshuai2144** [comment]
可以使用 `formRef`

```tsx
const formRef = useRef();

const outData = ()=> {
  console.log(formRef.current.getFieldsValue())
}

<ProTable formRef={formRef}/>
```

**Comment by Xmtd** [comment]
这取的不是protable search.transform或的值呀

**Comment by Xmtd** [comment]
formRef.current.getFieldsValue() 取的不是 protable自动生成的搜索表单的值呀，search.transform处理过的就取不到
