### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by HenryLee951020** [ant-design/pro-components#8507]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 【ProFormCheckbox.Group组件在需要将children自定义渲染时，onChange的backvalue不合法】

在<ProForm>表单组件中使用<ProFormCheckbox.Group>但是子级项不用options配置

示例代码：
<ProFormCheckbox.Group
    name="simultaneousDisplay"
    label="同时展示"
    required
>
  <Row>
    {
      ['1', '2', '3'].map((i) => {
        return <Col span={8} key={i}>
          <ProFormCheckbox value={i}>{i}</ProFormCheckbox>
        </Col>
      })
    }
  </Row>
</ProFormCheckbox.Group>

结果：在提交表单时simultaneousDisplay不是一个数组而是我最后点击的项
[https://codesandbox.io/p/sandbox/checkboxgroup-backvalueerror-cpjj3r?file=%2Fsrc%2FApp.js%3A12%2C31&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxlk3nis0006356o81xbyoww%2522%252C%2522sizes%2522%253A%255Bnull%252Cnull%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxlk3nir0002356oau0d59ke%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxlk3nir0003356od42eyxe8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxlk3nir0005356owoce94m4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxlk3nir0002356oau0d59ke%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxlk3niq0001356oc6ai8n2m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxlk7io70002356nz8qh9p7g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A31%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A31%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxlk3nir0002356oau0d59ke%2522%252C%2522activeTabId%2522%253A%2522clxlk7io70002356nz8qh9p7g%2522%257D%252C%2522clxlk3nir0005356owoce94m4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxlk3nir0004356opzrdfhh9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxlk3nir0005356owoce94m4%2522%252C%2522activeTabId%2522%253A%2522clxlk3nir0004356opzrdfhh9%2522%257D%252C%2522clxlk3nir0003356od42eyxe8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxlk3nir0003356od42eyxe8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D](url)
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by GitHdu** [comment]
还没修复
