### ISSUE TITLE
🧐[问题] 如何监听protable的搜索表单展开

### ISSUE THREAD

**Issue by djy6257** [ant-design/pro-components#8510]
### 🧐 问题描述

我这边protable的表格高度会自动计算防止整页出现滚动条，但是protable的搜索表单点击展开后会把表格顶下去，我希望监听搜索表单点的展开来重新计算表格高度，但是我查阅文档并没有找到展开文字的事件监听选项，是我查看文档遗漏了什么吗，还是有别的更好的方法实现我的需求，谢谢。

### 🚑 其他信息
![image](https://github.com/ant-design/pro-components/assets/61313387/f8105dcc-bcfe-4128-97d3-d4942435cfde)

**Comment by aojunhao123** [comment]
search配置项中提供了监听展开与收起的回调函数
![image](https://github.com/ant-design/pro-components/assets/82765353/faf13b4d-5f0d-4e81-98b5-9d90cd141e2b)

**Comment by djy6257** [comment]
> search配置项中提供了监听展开与收起的回调函数 ![image](https://private-user-images.githubusercontent.com/82765353/341654471-faf13b4d-5f0d-4e81-98b5-9d90cd141e2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTIwNzAsIm5iZiI6MTcxODk1MTc3MCwicGF0aCI6Ii84Mjc2NTM1My8zNDE2NTQ0NzEtZmFmMTNiNGQtNWYwZC00ZTgxLTk4YjUtOWQ5MGNkMTQxZTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA2MzYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YzViMWU4MWVkMDkzN2Q4MmU0N2M3NTA1Y2Y5ZTRhZmQ1NGE5ZDY1MGJiYWU3OWY3YWEzMTYxZjg5YzFkM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IQyKDOgsAK4jZYC8W59j6x4O5Um5zTzpuY7sYE3HCKc)

收到，感谢
