### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by MadiAbhilash** [ant-design/pro-components#8514]
### Checkbox Not Rendering for Boolean ValueType in Editable Table Column

When setting the `valueType` for an editable table column to **checkbox** and using a boolean value, the checkbox is not rendered. There is no checkbox element visible in the DOM.

#### Steps to Reproduce
1. Configure an editable column in Ant Design Pro Table with `valueType: 'checkbox'`.
2. Assign a boolean value to this column.
3. Observe the rendered table cell for the checkbox.

#### Expected Behavior
A checkbox should appear in the cell, corresponding to the boolean value.

#### Actual Behavior
No checkbox is rendered. Additionally, inspecting the DOM reveals no checkbox-related node.

#### Example Code
```typescript
{
  title: 'Active',
  dataIndex: 'isActive',
  valueType: 'checkbox',
  editable: true,
  render: (...params) => {
    console.log(params);
    // Should log details about the checkbox rendering
  },
}
```
No checkbox visible in the cell:
![image](https://github.com/ant-design/pro-components/assets/136574224/0b1bfe6b-ed7d-4736-9cae-a8c2cd6aac6d)

Console output of the render function:
![image](https://github.com/ant-design/pro-components/assets/136574224/88d0c978-6060-46c6-9f2e-b5075761c24b)

**Comment by wrench7** [comment]
I believe the issue here is that the `type: 'checkbox'` actually renders a checkbox group. 

I'm getting around this with:

```
{
  dataIndex: 'addFeesToBalance',
  valueType: 'checkbox',
  fieldProps: {
    options: [{label: intl.formatMessage(messages.addFeesToBalanceLabel), value: true}],
  },
  transform: (value) => ({addFeesToBalance2: value[0] ?? false})
}
```

Would definitely be preferable to have the ability to just use a simple Checkbox component without it always being wrapped in a CheckboxGroup
