### ISSUE TITLE
🐛[BUG] 官网 protable demo RTL部分 默认语言有问题

### ISSUE THREAD

**Issue by moon548834** [ant-design/pro-components#8516]
### 🐛 bug 描述

pro官网table RTL部分 默认语言有问题

https://procomponents.ant.design/components/table?tab=api&current=1&pageSize=5#rtl-%D8%A7%D9%84%D9%86%D8%B3%D8%AE%D8%A9-%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9

![截屏2024-06-24 14 03 54](https://github.com/ant-design/pro-components/assets/31240060/c200c32d-b41c-49b8-b338-75b359ed9439)

### 📷 复现步骤

访问上面的链接就可以

### 🏞 期望结果

正常显示语言

**Comment by aojunhao123** [comment]
我理解这个是国际化的问题。RTL的意思是Right To Left，即从右往左。而阿拉伯语的书写方向是从右往左的，所以这个地方提供了阿拉伯语的版本。

**Comment by moon548834** [comment]
> 我理解这个是国际化的问题。RTL的意思是Right To Left，即从右往左。而阿拉伯语的书写方向是从右往左的，所以这个地方提供了阿拉伯语的版本。

噢噢原来是这样 thk
