### ISSUE TITLE
🐛[BUG]在 columns中定义textArea属性时在 ProDescription中报警告

### ISSUE THREAD

**Issue by ray0324** [ant-design/pro-components#8524]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

在 columns中定义textArea属性时在 ProDescription中报警告

```
    {
      title: '角色描述',
      dataIndex: 'description',
      hideInSearch: true,
      valueType: 'textarea',
      fieldProps: {
        autoSize: { minRows: 2, maxRows: 3 },
      },
      formItemProps: {
        tooltip: '系统角色描述',
        rules: [
          {
            required: true,
            message: '名称为必填项',
          },
        ],
      },
    },
```
<img width="1667" alt="image" src="https://github.com/ant-design/pro-components/assets/5204198/0ecf83a6-0cc5-4ac4-a24e-daf754aebc41">

### © 版本信息

- ProComponents 版本: 2.7.10
- 浏览器环境: Chrome 126.0.6478.114

**Comment by fnoopv** [comment]
https://github.com/ant-design/pro-components/blob/9e934319fffc3b6e8155dbd25d76128dcc8138bd/packages/field/src/components/TextArea/readonly.tsx#L35-L41
只读时把`fieldProps`的所有值传递给`span`了，`span`元素没有`autoSize` 所以报错了
