### ISSUE TITLE
🧐[问题] 网站打不开了

### ISSUE THREAD

**Issue by zhanchengkun** [ant-design/pro-components#8526]
https://procomponents.ant.design/

https://pro-components.antdigital.dev/

访问空白页
 umijs 报错了

**Comment by milo-xiaomeng** [comment]
我也遇到这个问题 
<img width="1085" alt="image" src="https://github.com/ant-design/pro-components/assets/115647582/b55e1e74-dee8-47e9-9919-c1a126374bce">

**Comment by hsulei** [comment]
+1

**Comment by ww55235** [comment]
我也遇到了这个问题，用chrome和edge最新版出现了这个情况，我安装了firefox可以正常打开

**Comment by Wxh16144** [comment]
Duplicate of #8500
