### ISSUE TITLE
🐛[BUG]ProForm中的步骤表单导出时拼写错误

### ISSUE THREAD

**Issue by zhoufeii** [ant-design/pro-components#853]
### 🐛 bug 描述

按照文档中的示例引入StepForm时，IDE提示找不到这个模块
![image](https://user-images.githubusercontent.com/36029402/97421899-0197d700-1948-11eb-9232-39addaaf8ec8.png)

### 📷 复现步骤
`
import ProForm, {
  StepsForm,
  ProFormText,
  ProFormDatePicker,
  ProFormSelect,
  ProFormTextArea,
  ProFormCheckbox,
  ProFormDateRangePicker,
} from '@ant-design/pro-form';
`
复制这段代码即可复现

### 🏞 期望结果
可以正确引入 StepsForm 模块

### © 版本信息

- ProComponents 版本: 
` "name": "@ant-design/pro-form",
  "version": "1.0.0-beta.30",
`
- umi 版本
`"umi": "^3.2.14",`
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/36029402/97421783-ddd49100-1947-11eb-85ec-f1b354aff07b.png)

**Comment by chenshuai2144** [comment]
升级一下版本吧。已经发了正式版了
