### ISSUE TITLE
Extra component in sidebar?

### ISSUE THREAD

**Issue by conioX** [ant-design/pro-components#8533]
Hello guys there is any method or props to create extra component inside menu sidebar?

![image](https://github.com/ant-design/pro-components/assets/73159491/75cf78ff-6a5c-4f09-917c-4ce5f7378c1b)

**Comment by fengzehao** [comment]
try this

menuContentRender={(props, defaultDom) =><div><div>自定义内容</div>{defaultDom}</ div>}

**Comment by fengzehao** [comment]
try this.
`menuContentRender={(props, defaultDom) =><div><div>自定义内容</div>{defaultDom}</ div>}`

**Comment by conioX** [comment]
thank you @fengzehao
