### ISSUE TITLE
👑 [需求] Do not import styles in component

### ISSUE THREAD

**Issue by rps-v** [ant-design/pro-components#856]
### 🥰 需求描述

Remove [the style import](https://github.com/ant-design/pro-components/blob/fd2d5d1329b66a6a9257fab16d141a040356d0ff/packages/table/src/Table.tsx#L62) to allow users to add the styles according to their build requirements.

Adding `pro-table` to the [with-ant-design-pro-layout-less](https://github.com/vercel/next.js/tree/canary/examples/with-ant-design-pro-layout-less) example overrides any custom styles you loaded, because we are forced to dynamically load `ProTable` and it includes the `default` `antd` theme. Since it is loaded later than your app styles, it overrides them.

**Comment by chenshuai2144** [comment]
Our main user is umi user, your problem does not exist in umi, you may need to customize the webpack configuration
