### ISSUE TITLE
🐛[BUG]：你们的网站每一个页面打开都是白屏，然后强制刷新下就好了，点其他页面也是一样的，nginx 没配置好？

### ISSUE THREAD

**Issue by Chasen-Zhang** [ant-design/pro-components#8560]
https://procomponents.ant.design/docs

![image](https://github.com/ant-design/pro-components/assets/15354455/37cbdb20-fdb7-4a9e-872c-af81aa64c836)

**Comment by ChuTingzj** [comment]
好像是浏览器插件影响到了，我用 `无痕` 或者把浏览器插件全禁用就好了

**Comment by Chasen-Zhang** [comment]
![image](https://github.com/ant-design/pro-components/assets/15354455/fc7f4b7b-4dd2-4137-b503-64de1019e6b7)
我发现是这个影响了

**Comment by chenshuai2144** [comment]
我们也没用redux 呀，是不是有什么兼容性问题

**Comment by Chasen-Zhang** [comment]
> 我们也没用redux 呀，是不是有什么兼容性问题

要不你装一个试试，看下能不能复现，假如复现了再找下原因？

**Comment by 0fan** [comment]
+1, 这个问题已经好久了
