### ISSUE TITLE
🐛[BUG]ProTable渲染时报Warning: findDOMNode ，点击右上角列设置时报Warning: A props object containing a "key" prop is being spread into JSX

### ISSUE THREAD

**Issue by 741599086** [ant-design/pro-components#8574]
### 🐛 bug 描述

**ProTable渲染时报：**
findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here

**ProTable点击右上角列设置时报：**
Warning: A props object containing a "key" prop is being spread into JSX:

### 📷 复现步骤

渲染时 以及  点击右上角列设置时
[https://codesandbox.io/p/sandbox/antd-pro-typjry](https://codesandbox.io/p/sandbox/antd-pro-typjry)

### 🏞 期望结果
修复bug

### 💻 复现代码

[https://codesandbox.io/p/sandbox/antd-pro-typjry](https://codesandbox.io/p/sandbox/antd-pro-typjry)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
"react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-scripts": "^5.0.0",
    "@ant-design/pro-components": "2.7.13",
    "antd": "5.19.2"

### 🚑 其他信息

![image](https://github.com/user-attachments/assets/7e7ee6c9-ad2a-409f-aa26-6e20b0b715e7)

![image](https://github.com/user-attachments/assets/77a63dbe-efd6-4f1f-9d93-cc72b7865bf7)

**Comment by fnoopv** [comment]
第一个问题，issue里面搜一下，已知问题

**Comment by NoirVoider** [comment]
同样俩问题都遇到了
 "react": "^18.3.1",
  "react-dom": "^18.3.1",
StrictMode
