### ISSUE TITLE
🐛[BUG] pro-table和antd4.6.1不兼容

### ISSUE THREAD

**Issue by KellenHe** [ant-design/pro-components#858]
### 🐛 bug 描述

最近版本的pro-table（2.8.1和2.9.12都有）使用4.6.1的antd会报错。

使用antd4.6.1之后的版本是可以的，但是antd4.6.1之后的版本在qiankun子应用时下拉框会出现卡死界面的情况。
很尴尬。。。

### 📷 复现步骤

https://codesandbox.io/s/hungry-http-rj433?file=/index.tsx

**Comment by chenshuai2144** [comment]
antd 升级一下版本 ，有个版本的确有卡死的问题

**Comment by KellenHe** [comment]
好几个版本都有，大佬。最近的版本都试了。

**Comment by chenshuai2144** [comment]
去 antd 的 issue 看看，群里说已经修了
