### ISSUE TITLE
官网打不开

### ISSUE THREAD

**Issue by xu756** [ant-design/pro-components#8587]
官网打开问题
1.打开白屏，需要刷新才能下一步
2.部分域名访问不到（）
3.影响我使用 dumi 的信心

https://github.com/user-attachments/assets/94bf6e14-476e-43cb-8979-732c53bddfd2

**Comment by wj0990** [comment]
@xu756  我在实际项目中使用了超级好用。切换国内镜像 实在无法忍受可以 拉到本地 起服务。或者自己部署到docker里

**Comment by ww55235** [comment]
@xu756 我用firefox可以打开，但是chrome和edge浏览器不行，要重新刷新才可以。
