### ISSUE TITLE
🐛[BUG]pro-table的valueEnum列表字段不能解析，renderFormItem中自定义Cascader不能动态更新

### ISSUE THREAD

**Issue by GKLL** [ant-design/pro-components#859]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 3.2.0
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
show you code？

>  renderFormItem中自定义Cascader不能动态更新

这是性能优化，如果组件中任何一个地方状态更新就重新执行组件，浏览器不一定能受得了。
你可以可以这样 ,把组件更新只局限于自己的组件内

```tsx
const MyCom = (value,onChange)=> <Cascader />

renderFormItem = ()=><MyCom/>
```
