### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by roddc** [ant-design/pro-components#8592]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述
请问为什么在SchemaForm渲染ValueType为checkbox的时候是ProFormCheckbox.Group而不是ProFormCheckbox ? 
如何在SchemaForm里渲染单独的ProFormCheckbox，是要自定义吗？

**Comment by wrench7** [comment]
See my comment here for a "solution" (ideally the ability to render a single checkbox should be available as well)
https://github.com/ant-design/pro-components/issues/8514#issuecomment-2681809952
