### ISSUE TITLE
🐛[BUG] 分步表单垂直模式 官网示例 有bug

### ISSUE THREAD

**Issue by bxter** [ant-design/pro-components#8596]
官网示例
https://pro-components.antdigital.dev/components/steps-form#stepform

到第2步时候，页面的组件错乱了，
<img width="1088" alt="image" src="https://github.com/user-attachments/assets/64ea3b06-c161-452e-b06f-7c74dcf469ad">

**Comment by Wxh16144** [comment]
resolved #8623
