### ISSUE TITLE
ProTable 怎么能每页都添加一条汇总数据放在表格第一条呢 🐛[BUG]

### ISSUE THREAD

**Issue by TangDeYu** [ant-design/pro-components#8613]
### 🐛 bug 描述
统计的表格。 后端返回一条汇总的数据 没有和表格数据放在一起  
前端怎么能手动把一条数据放在每列返回的上方并且不影响分页的展示呢。
我手动push到第一条的话。分页就会出现问题。把我push的那一条当成真实的表格数据展示。分页就会有问题
有什么好的方法吗

**Comment by fnoopv** [comment]
https://ant.design/components/table-cn#table-demo-summary
