### ISSUE TITLE
🐛[BUG] ProTable 重置 filteredValue

### ISSUE THREAD

**Issue by onlyling** [ant-design/pro-components#864]
### 🐛 bug 描述

[[BUG] ProTable 重置 columns 中某个 filteredValue (空数组)的时候 UI 显示/数据有误](https://github.com/ant-design/pro-components/issues/682)

具体请参考上面链接

### 📷 复现步骤

```bash
## 安装依赖
yarn

## 启动应用
yarn dev

## 浏览器打开

## ProTable
http://0.0.0.0:9090/#/pro-table/demo

## Table
http://0.0.0.0:9090/#/pro-table/table

## 模拟 ProTable 状况的 Table
http://0.0.0.0:9090/#/pro-table/table-2
```

`reset` 重置 Table columns 中所有的 filteredValue。

`random data` 模拟请求数据，更新列表。

随机筛选 `type` 数据，触发数据更新。点击 `reset` 按钮，重置筛选。

ProTable 的表现是没有把 `type` 的筛选条件清空(UI 上的样子并没有恢复未选择的样子)。

### 🏞 期望结果

ProTable 与 Table 表现一致。

### 💻 复现代码

[可以复现代码](https://github.com/onlyling/react-base)

### © 版本信息

- ProComponents 版本: [e.g. 2.9.13]
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

请留意[这个补充说明](https://github.com/ant-design/pro-components/issues/682#issuecomment-708110859)

<img width="806" alt="WX20201029-174234@2x" src="https://user-images.githubusercontent.com/9999765/97551716-4ab25e80-1a0e-11eb-819a-95dfc5bce3b0.png">

<img width="816" alt="WX20201029-174303@2x" src="https://user-images.githubusercontent.com/9999765/97551763-569e2080-1a0e-11eb-8d71-277ba0418b70.png">

**Comment by onlyling** [comment]
`2.24.0` 版本还能复现。

**Comment by chenshuai2144** [comment]
filteredValue 是清空不了的，因为不是受控的
