### ISSUE TITLE
🐛[BUG]findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference

### ISSUE THREAD

**Issue by yxplus1116** [ant-design/pro-components#8640]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

控制台报错：findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference
看上去和 pro-components 的实现有关系

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://github.com/user-attachments/assets/ca64d8f9-c3b6-4109-a6b3-18afcc2e3620)

**Comment by fnoopv** [comment]
ref https://github.com/ant-design/pro-components/issues/8641#issuecomment-2283615065
