### ISSUE TITLE
👑 [需求]pro-table 缓存搜索记录

### ISSUE THREAD

**Issue by sillybbb** [ant-design/pro-components#867]
### 🥰 需求描述

pro-table 搜索表单查询数据后，在切换路由后会重置搜索状态，如查询详情，用户体验不是很友好，需每一次切换路由后重新进行搜索，目前的解决方案是通过跳转手动维护searchParams，希望可以增加这个需求

**Comment by chenshuai2144** [comment]
试试这个吧 也很方便

https://github.com/vercel/swr
