### ISSUE TITLE
🧐[问题]在mix 混合模式下顶部菜单不切割，左侧菜单显示2-3级菜单

### ISSUE THREAD

**Issue by xuchunwei123** [ant-design/pro-components#871]
### 🧐 问题描述
在mix 混合模式下顶部菜单不切割，左侧菜单显示2-3级菜单

**Comment by chenshuai2144** [comment]
详细描述一下

**Comment by xuchunwei123** [comment]
> 详细描述一下
我希望我的部署是混合模式布局，顶部有菜单，左侧也有菜单，顶部可以显示全部菜单，而左侧只显示选中的一级以下的菜单

**Comment by chenshuai2144** [comment]
splitMenus ，打开一下就好了

**Comment by xiaoshui222** [comment]
> splitMenus ，打开一下就好了

splitMenus 在哪里写

**Comment by xiaoshui222** [comment]
> splitMenus ，打开一下就好了

api文档没有看到在哪里打开mix模式

**Comment by chenshuai2144** [comment]
<ProLayou spltMenus />
