### ISSUE TITLE
ModalForm loading失效 🐛[BUG]

### ISSUE THREAD

**Issue by ouzhou** [ant-design/pro-components#881]
### 🐛 bug 描述

官方例子ModalForm点击是有一个loading效果的，复制代码运行，除了没有loading其他行为和案例一致
这个问题挺严重的，如果没有loading，**那这个按钮可能会被点击多次，导致重复提交多次**

### 📷 复现步骤
点击按钮，弹窗表单，点击提交

### 🏞 期望结果
提交按钮会变为loading状态

### © 版本信息

```
 "dependencies": {
    "@ant-design/pro-form": "^1.1.6",
    "@ant-design/pro-layout": "^5.0.12",
    "@umijs/preset-react": "1.x",
    "@umijs/test": "^3.2.24",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "umi": "^3.2.24",
    "yorkie": "^2.0.0"
  }
```
### 🚑 其他信息

这个是案例的
https://codesandbox.io/s/6o3bi

官网的demo没有问题
估计是官网的demo的版本不是最新的，codesandbox是最新的，所以可以复现这个bug

**Comment by chenshuai2144** [comment]
升级一下版本就有了，需要比较新的版本
