### ISSUE TITLE
抽梯形菜单当窗口小于768时出现，如何修改这个值

### ISSUE THREAD

**Issue by syakyou** [ant-design/pro-components#8835]
抽梯形菜单当窗口小于768时出现，如何修改这个值，我想改为1180

**Comment by chenshuai2144** [comment]
| Parameters | Description | Type | Default |
| --- | --- | --- | --- |
| breakpoint | Trigger [breakpoint](https://ant.design/components/grid/#Col) for responsive layouts | `Enum { 'xs', 'sm', 'md', 'lg', 'xl', 'xxl' }` | `lg` |
