### ISSUE TITLE
QueryFilter  重置按钮与表单initialValues属性不兼容 🐛[BUG]

### ISSUE THREAD

**Issue by skyc024** [ant-design/pro-components#884]
### 🐛 bug 描述
使用QueryFilter组件，点击重置按钮报错

页面提示错误信息：
layout.global.error.title
TypeError: date1.isAfter is not a function
控制台错误信息：
moment.js:69 Uncaught TypeError: date1.isAfter is not a function
    at Object.isAfter (moment.js:69)
    at reorderValues (RangePicker.js:31)
    at postState (RangePicker.js:144)
    at useControlledState (useMergedState.js:39)
    at InnerRangePicker (RangePicker.js:140)
    at renderWithHooks (react-dom.development.js:14803)
    at mountIndeterminateComponent (react-dom.development.js:17482)
    at beginWork (react-dom.development.js:18596)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22154)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at discreteUpdates$1 (react-dom.development.js:21893)
    at discreteUpdates (react-dom.development.js:806)
    at dispatchDiscreteEvent (react-dom.development.js:4168)

devScripts.js:5836 The above error occurred in the <InnerRangePicker> component:
    in InnerRangePicker (created by RangePicker)
    in RangePicker (created by Context.Consumer)
    in LocaleReceiver (created by RangePicker)
    in RangePicker (at saleData/index.tsx:192)
    in Unknown
    in Unknown (created by Field)
    in div (created by FormItemInput)
    in div (created by FormItemInput)
    in div (created by Context.Consumer)
    in Col (created by FormItemInput)
    in FormItemInput (created by Field)
    in div (created by Context.Consumer)
    in Row (created by Field)
    in Field (created by WrapperField)
    in WrapperField (created by FormItem)
    in FormItem (at saleData/index.tsx:191)
    in div (created by Context.Consumer)
    in Col (created by BaseForm)
    in div (created by Context.Consumer)
    in Row (created by ResizeObserver)
    in ResizeObserver (created by BaseForm)
    in form (created by ForwardRef(Form))
    in ForwardRef(Form) (created by ForwardRef(InternalForm))
    in SizeContextProvider (created by ForwardRef(InternalForm))
    in ForwardRef(InternalForm) (created by BaseForm)
    in ConfigProviderWarp (created by BaseForm)
    in BaseForm (created by QueryFilter)
    in QueryFilter (at saleData/index.tsx:177)
    in div (created by Card)
    in div (created by Card)
    in Card (at saleData/index.tsx:176)
    in div (created by PageContainer)
    in div (created by PageContainer)
    in div (created by GridContent)
    in div (created by GridContent)
    in GridContent (created by PageContainer)
    in div (created by PageContainer)
    in PageContainer (at saleData/index.tsx:175)
    in SaleData (created by LoadableComponent)
    in LoadableComponent (created by Context.Consumer)
    in Route (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in WithExceptionOpChildren (at layout/index.tsx:140)
    in ErrorBoundary (at layout/index.tsx:139)
    in main (created by Basic)
    in Basic (created by Context.Consumer)
    in Content (created by WrapContent)
    in ConfigProviderWarp (created by WrapContent)
    in WrapContent (created by BasicLayout)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Layout (created by BasicLayout)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Layout (created by BasicLayout)
    in div (created by BasicLayout)
    in Provider (created by BasicLayout)
    in BasicLayout (at layout/index.tsx:83)
    in BasicLayout
    in Unknown (created by LoadableComponent)
    in LoadableComponent (created by Context.Consumer)
    in Route (created by RouterComponent)
    in Switch (created by RouterComponent)
    in Router (created by RouterComponent)
    in RouterComponent
    in AccessProvider
    in Unknown
    in FormProvider (created by Context.Consumer)
    in LocaleProvider (created by Context.Consumer)
    in SizeContextProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (at locale.tsx:49)
    in _LocaleContainer
    in Unknown

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
initialValues 值需要是一个 moment，你传入的不是一个 moment

**Comment by skyc024** [comment]
谢谢，没想到过重置时框架会用initialValues属性。问题已解决。谢谢
