### ISSUE TITLE
👑 [需求] 建议优化ModalForm组件`visible` 为 `open`

### ISSUE THREAD

**Issue by uzhan** [ant-design/pro-components#8843]
### 🔩 所属模块或组件
**ModalForm**

### 🥰 需求描述

在使用trigger作为按钮，用于触发 Modal 打开时，内部将`visible` 改为 `open`以适应新版本的antd组件库

### ⛰ 功能需求适用场景

弹窗表单使用场景在使用trigger作为按钮，浏览器不再提示` Warning: [antd: Modal]  visible will be removed in next major version, please use open instead. Error Component Stack`

### 🧐 解决方案

内部将`visible` 改为 `open`

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
是不是版本太低了， 改了有一段时间了
