### ISSUE TITLE
👑 [需求] ProLayout 文档缺失 rightContentRender 属性

### ISSUE THREAD

**Issue by HuGtoX** [ant-design/pro-components#8860]
源码体现：
![image](https://github.com/user-attachments/assets/62dc6512-fb92-4f15-a6bd-256b85a9220c)

![image](https://github.com/user-attachments/assets/fbc79e81-6c2d-4513-9a83-807c01f43709)

![image](https://github.com/user-attachments/assets/6d9a8dff-2a79-4e85-bd27-f8261f433ce2)

文档ProLayout API中缺少该属性

**Comment by chenshuai2144** [comment]
这个属性应该要消失了，不要使用了
