### ISSUE TITLE
🧐[问题]接口数据格式为 {data:Array, success:Boolean, total:number, summary: any}，但是我司接口规范返回的json里不是data,而是result

### ISSUE THREAD

**Issue by liuchuangjun321** [ant-design/pro-components#887]
### 🧐 问题描述

接口数据格式为 {data:Array, success:Boolean, total:number, summary: any}，
但是我司接口规范返回的json里不是data,而是result。对于这种情况有办法处理吗?
看了一下postData接收的不是整个JSON，而是JSON里面的data字段???

**Comment by chenshuai2144** [comment]
在 request 里面处理一下，或者在 fetch 的时候修改一把。


```tsx
<ProTable
  request={async (params) => {
    const res = server();
    return { ...res, data: res.result };
  }}
/>;
```

```tsx
fetch().then(res=>res.json()).then(async(json)=>{ ...json,data:json. result})
```

**Comment by DunDunDunAbandon** [comment]
> 在 request 里面处理一下，或者在 fetch 的时候修改一把。
> 
> ```tsx
> <ProTable
>   request={async (params) => {
>     const res = server();
>     return { ...res, data: res.result };
>   }}
> />;
> ```
> 
> ```tsx
> fetch().then(res=>res.json()).then(async(json)=>{ ...json,data:json. result})
> ```

返回的数据里没有data也没有result字段就直接返回的数据内容应该怎么改。。。。。

**Comment by cuibty** [comment]
要想全局统一处理怎么处理呢？@chenshuai2144

**Comment by chenshuai2144** [comment]
@cuibty 只能改你们的 request 了，在网络请求库上统一改进。
可以用 umi 的 request，支持中间价可以转化一下

**Comment by cuibty** [comment]
@chenshuai2144 好的，谢谢！
