### ISSUE TITLE
PageContainer去哪里了 🧐[问题]

### ISSUE THREAD

**Issue by ouzhou** [ant-design/pro-components#890]
### 🧐 问题描述

文档里面有写用PageContainer组件，但是npm这个包里面没有这个东西，去哪里了？
"@ant-design/pro-layout": "^5.0.12",

### 💻 示例代码
![image](https://user-images.githubusercontent.com/7693866/97965125-da805000-1df4-11eb-9dbc-0755d78d0718.png)

**Comment by chenshuai2144** [comment]
PageContainer 是 6.0 新增的，5.0 没有
