### ISSUE TITLE
官方文档的库版本需要更新  🧐[问题]

### ISSUE THREAD

**Issue by ouzhou** [ant-design/pro-components#891]
### 🧐 问题描述

我复制了一遍代码在"@ant-design/pro-layout": "^5.0.12",下跑发现这个收缩按钮位置和官网的不一致，猜测是版本不一样导致的

官网
![image](https://user-images.githubusercontent.com/7693866/97965281-11eefc80-1df5-11eb-8e17-21d8d4c548c5.png)

测试
![image](https://user-images.githubusercontent.com/7693866/97965400-42cf3180-1df5-11eb-94d7-975649fb28dc.png)

 
### 🚑 其他信息

这个位置是可以修改的吗，能给个位置的配置项吗?

**Comment by chenshuai2144** [comment]
不支持修改的，可以用这两个api 来受控自定义


collapsed | 控制菜单的收起和展开 | boolean | -
-- | -- | -- | --
onCollapse | 菜单的折叠收起事件 | (collapsed: boolean) => void | -
