### ISSUE TITLE
👑 [需求] EditableProTable  可配置 scrollToFirstError；当表单提交时校验失败滚动到让第一个 失败项 进入可视区

### ISSUE THREAD

**Issue by 510279293** [ant-design/pro-components#8926]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

率属组件：EditableProTable

### 🥰 需求描述

EditableProTable 中 可编辑项比较多出现横向滚动条时，需要 借助 scrollToFirstError 让用户知道 那些表单项提交失败

**Comment by 510279293** [comment]
看到解决方案了，是定义组件的问题

**Comment by xliez** [comment]
> 看到解决方案了，是定义组件的问题

@510279293 你怎么解决的，可以分享下解决方案吗？
