### ISSUE TITLE
🐛[BUG]Pro-table： 全屏后toolbar 的按钮点击仍然无效

### ISSUE THREAD

**Issue by FinchJohnRen** [ant-design/pro-components#895]
### 🐛 bug 描述

密度 列设置 这两个按钮 
### 📷 复现步骤
https://procomponents.ant.design/components/table#%E6%99%AE%E9%80%9A%E8%A1%A8%E6%A0%BC
现在的官网直接就能验证

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
更新一下版本
