### ISSUE TITLE
pro-table，rowSelection 多选,分页后不支持获取所有的selectedRowKeys值

### ISSUE THREAD

**Issue by zmj0920** [ant-design/pro-components#897]
版本信息
ProTable版本:  2.9.12
umi 版本:3.2.14
浏览器环境

**Comment by chenshuai2144** [comment]
show your code

**Comment by zmj0920** [comment]
handleSelectRows = (selectedRowKeys, selectedRows) => {
    console.log(selectedRowKeys);
  };
    const rowSelection = {
      selectedRowKeys,
      onChange: this.handleSelectRows,
    };
       <ProTable rowSelection={rowSelection}/>

**Comment by zmj0920** [comment]
handleSelectRows = (selectedRowKeys, selectedRows) => {
console.log(selectedRowKeys);
};
const rowSelection = {
selectedRowKeys,
onChange: this.handleSelectRows,
};
 <ProTable
 rowSelection={rowSelection}
  />

**Comment by zmj0920** [comment]
> show your code

handleSelectRows = (selectedRowKeys, selectedRows) => {
console.log(selectedRowKeys);
};
const rowSelection = {
selectedRowKeys,
onChange: this.handleSelectRows,
};
<ProTable
 rowSelection={rowSelection}
 />

**Comment by chenshuai2144** [comment]
[详细请参考antd table文档 preserveSelectedRowKeys这个属性](https://ant.design/components/table-cn/)

![image](https://user-images.githubusercontent.com/58172091/114819276-cd2daf80-9def-11eb-80d3-4d4400d758e9.png)
