### ISSUE TITLE
🧐[问题]请问ProTable的renderFormItem里用到外部state的数据时，第一次渲染会为空是为什么呢

### ISSUE THREAD

**Issue by zXuff** [ant-design/pro-components#899]
### 🧐 问题描述

https://codesandbox.io/s/cranky-meninsky-d8sqd?file=/App.tsx
这是复现地址，标签筛选的下拉选第一次是为空

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/issues/751

看这个，最后状态自己管，不要放到 父亲里面，Form 是有优化的，只有 value 修改了才触发渲染

**Comment by zXuff** [comment]
那也就是说我要把这个Select写成一个自定义表单是吧

**Comment by zXuff** [comment]
> https://github.com/ant-design/pro-components/issues/751
> 
> 
> 
> 看这个，最后状态自己管，不要放到 父亲里面，Form 是有优化的，只有 value 修改了才触发渲染

那也就是说我要写一个自定义表单组件，把渲染的数据也写到这个组件里是吧

**Comment by xgj1988** [comment]
@zXuff  搞定了吗？你的问题。。

**Comment by xgj1988** [comment]
@chenshuai2144  这个问题你们还是要解决依稀吧。。
