### ISSUE TITLE
🧐[问题]请问ProTable在第一次请求时如何干预sort的值呢，是需要在request中手动处理吗？

### ISSUE THREAD

**Issue by zXuff** [ant-design/pro-components#904]
### 🧐 问题描述

🧐[问题]请问ProTable在第一次请求时如何干预sort的值呢，是需要在request中手动处理吗？
场景是将查询参数缓存到地址栏中，然后在返回到该页面时将地址栏的参数传到ProTable中，search的条件可以通过initialValue传入，那sort该怎么传到ProTable中呢

**Comment by DunDunDunAbandon** [comment]
同问

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/issues/358
