### ISSUE TITLE
🧐[问题]接口返回的数据里没有data字段应该如何处理

### ISSUE THREAD

**Issue by DunDunDunAbandon** [ant-design/pro-components#906]
### 🧐 问题描述

接口返回的数据里没有data字段应该如何处理

### 💻 示例代码

json格式：[{"Code":"1014","Name":"1014"}]

**Comment by chenshuai2144** [comment]
request 里面自己造吧

```
request = async ()=>{
   await query()
   return {data:[]}
}
```

**Comment by DunDunDunAbandon** [comment]
写出来了，修改queryRule即可：
`export async function queryRule(params?: TableListParams) {
  return Axios.get("/api/Courses")
  .then((res:any)=>{
    console.log(res.data)
    return {
        data:res.data,
        // params
    }
  })
}`
