### ISSUE TITLE
🐛[BUG]ProTable的toolBarRender第一个参数的action里面的reload方法无法清除selectedRows

### ISSUE THREAD

**Issue by ZaccheoMoon** [ant-design/pro-components#907]
### 🐛 bug 描述

设置rowSelection={{}}
const toolBarRender = (action: any, { selectedRows }: any) => [
    selectedRows && selectedRows.length > 0 && (
      <Dropdown
        key='delete'
        overlay={
            <Menu
              onClick={async(e) => {
                if (e.key === 'remove') {
                  action.reload() // 这个位置的刷新在2.2.7版本可以清空selectedRows，在2.8.0版本之后都无法清除，selectedRows仍然有数据
                }
              }}
              selectedKeys={[]}
            >
              <Menu.Item key='remove'>批量删除</Menu.Item>
            </Menu>
        }
      >
        <Button>
          批量操作 <DownOutlined />
        </Button>
      </Dropdown>
    ),
  ]

### 📷 复现步骤

如上代码

### 🏞 期望结果

期望action.reload()之后可以让selectedRows为空数组

### 💻 复现代码

如上代码

### © 版本信息

-@ant-design/pro-table 版本: 2.9.7
- umi 版本 3.2.24
- 浏览器环境 火狐82.0.2
- 开发环境 mac OS

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
`action.reloadAndRest()` 试试这个

**Comment by ZaccheoMoon** [comment]
> reloadAndRest()
action里面没有这个方法

**Comment by ZaccheoMoon** [comment]
> `action.reloadAndRest()` 试试这个

action里没有这个方法
