### ISSUE TITLE
👑 [需求]Table的列设置的显隐和排序希望下次进入页面保留上次更改

### ISSUE THREAD

**Issue by Caoqingda** [ant-design/pro-components#91]
### 🥰 需求描述

列设置的显隐数据可以通过onColumnsStateChange事件缓存到本地，下次进去页面保留上次更改，但是列的排序数据我们拿不到

### 🧐 解决方案
希望官方大大能够把负责columns排序的onChange事件暴露出来

**Comment by chenshuai2144** [comment]
已经发布
