### ISSUE TITLE
🧐[问题]请问ProTable的reload方法为什么不会触发重新请求呢？

### ISSUE THREAD

**Issue by wood3n** [ant-design/pro-components#910]
### 🧐 问题描述

我想通过外界`form`的`onValuesChange`事件改变表单值，然后在获取表单值后塞入`ProTable`的请求参数，但是执行`reload`方法并不会触发`ProTable`重新请求，`form`改变的值带不上

### 💻 示例代码

[![Edit exciting-ardinghelli-1i66i](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/exciting-ardinghelli-1i66i?fontsize=14&hidenavigation=1&theme=dark)

**Comment by chenshuai2144** [comment]
@wood3n  form 的值只有submit的时候才能带上去，你可以触发form.submit 来触发表单的提交。

**Comment by chenshuai2144** [comment]
ayo
