### ISSUE TITLE
🐛[BUG] layout侧边栏在有子项的时候需要点击2次才可以收缩

### ISSUE THREAD

**Issue by ouzhou** [ant-design/pro-components#913]
### 🐛 bug 描述

侧边栏需要点击两次才可以收起

测试页面
https://preview.pro.ant.design/form/step-form

![image](https://user-images.githubusercontent.com/7693866/98319338-82776280-201b-11eb-9fc1-1fb289b2c20d.png)

**Comment by ouzhou** [comment]
重复了

**Comment by chenshuai2144** [comment]
这个已经修了 更新一下版本就好了
