### ISSUE TITLE
🧐怎么解决表格样式不统一的问题

### ISSUE THREAD

**Issue by 2504724384** [ant-design/pro-components#92]
### 🧐 问题描述

在没有加任何自定义样式的前提下，不同页面的表格样式不同，主要表现在行高，怎么可以解决这个问题？

### 💻 示例代码
所有的表格我都是这样写的：
```
    <ProTable<RewardListItem>
        actionRef={actionRef}
        rowKey="id"
        options={false}
        request={(params: any) =>
          queryRules({
            page_size: params.pageSize || 10,
            current_page: params.current || 1,
          })
        }
        search={false}
        pagination={{
          total: pageCount,
          defaultPageSize: 10,
        }}
        columns={thirdColumns}
      />
```

### 🚑 其他信息
正常情况下：
![image](https://user-images.githubusercontent.com/41176559/89263271-859d3400-d663-11ea-8947-883f3f346074.png)

比较独特的表格：
![image](https://user-images.githubusercontent.com/41176559/89263297-9352b980-d663-11ea-940b-6a06ed9e75f9.png)

**Comment by chenshuai2144** [comment]
这个看起来是 size 的问题

**Comment by 2504724384** [comment]
> 这个看起来是size的问题

尝试过设置size，但是即使设置了size，行高也还是不和其它表格一样

**Comment by 2504724384** [comment]
找到问题了，这里是因为自己使用了 Space 组件来让两个 a 标签之前有空格，Space组件影响了该表格的行高
