### ISSUE TITLE
🐛[BUG]ModalForm DrawerForm  引用错误

### ISSUE THREAD

**Issue by zhengshubin** [ant-design/pro-components#921]
### 🐛 bug 描述
使用 <ModalForm/>就会出现以下报错：
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `_default`.

### 📷 复现步骤
官方例子  https://codesandbox.io/s/94p5q?file=/index.tsx，在codesandbox 可以，但在ant design pro 使用出错。

### 🏞 期望结果
正常运行

### 💻 复现代码
export default () => {
    return (<          ModalForm /      >);
};

### © 版本信息
ant design pro 4
antd: 4.8.0
@ant-design/pro-form": "^1.3.0"
- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
估计是别的问题，show 一下你的代码？

你估计是哪里写错了

**Comment by zhengshubin** [comment]
> 估计是别的问题，show 一下你的代码？
> 
> 你估计是哪里写错了

确实是自己写错了，谢谢！我还有个问题，就是 ProFormSelect的 onSearch 方法怎么没有效果

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/98529345-74923d80-22b8-11eb-8778-235412e22673.png)


fieldProps 里面设置

**Comment by chenshuai2144** [comment]
还真是个bug
