### ISSUE TITLE
🐛[BUG]proTable在全屏下的modal不会展示

### ISSUE THREAD

**Issue by babizhu** [ant-design/pro-components#922]
### 🐛 bug 描述

proTable,点击组件自带的全屏按钮，全屏之后，点击某个按钮想  弹出一个modal

但是看不到这个modal，退出全屏状态就能看到此modal了

非全屏的状态下，modal的弹出和关闭逻辑是正常的

### © 版本信息

- "@ant-design/pro-table": "^2.9.12",
- umi 版本
- 浏览器环境 chrome 版本 88.0.4315.5（正式版本）dev (x86_64)
- 开发环境  mac OS

**Comment by chenshuai2144** [comment]
全屏本质上是把你的表格区域  fixed 了，所以你需要把 Modal 的 getPopupContainer 设置为了 table 的区域。

详细文档看这里
https://developer.mozilla.org/zh-CN/docs/Web/API/Fullscreen_API

如果不是很理解为什么会这样，建议最好不要用这个api

```tsx
<ConfigProvider
  getPopupContainer={() => document.getElementById("ant-design-pro-table")}
>
  {proTableDom}
</ConfigProvider>;
```

**Comment by tanwei0425** [comment]
捕获全屏的状态，当全屏状态开启的时候把modal挂在table上，当全屏状态结束的时候把modal挂在body上。。暂时这么处理的，有更好的方法通知下我 。
