### ISSUE TITLE
👑 [需求]ProFormSelect 怎么进行表单联动？

### ISSUE THREAD

**Issue by yingzhiji** [ant-design/pro-components#931]
### 🥰 需求描述

有两个 ProFormSelect，选项数据都是从服务器获取的，当第一个 Select 被选中后，拿到选中的结果去获取第二个 Select 的数据，这种情况下有解决方案吗？

**Comment by yingzhiji** [comment]
找到了解决方案：
![image](https://user-images.githubusercontent.com/21698836/98513699-3ccccb00-22a3-11eb-975e-8bc997ba0aca.png)
文档中有个没有列出的参数 params，这个参数会传给 reqeust，最后会传给 swr，swr 如果参数变化了就会重新运行请求函数。不过个人感觉 swr 这个 revalidateOnFocus 特性对于 Select 来说有点不太好，而且没办法关闭

**Comment by zyhnuaa** [comment]
请问怎么解决的，也有相同的应用场景

**Comment by chenshuai2144** [comment]
用renderProps 得方法。

```tsx
<ProForm>
  <Form.Item noStyle shouldUpdate>
    {(form) => {
      return (
        <ProFormSelect
          options={[
            {
              value: "chapter",
              label: "盖章后生效",
            },
          ]}
          width="md"
          name="useMode"
          label={`与${form.getFieldValue("name")}合同约定生效方式`}
        />
      );
    }}
  </Form.Item>
</ProForm>;
```
