### ISSUE TITLE
columns 中某一列中设置valueType: 'select', 在表单里面select 的option值怎么放进去

### ISSUE THREAD

**Issue by pengxingwang** [ant-design/pro-components#932]
### 💻 示例代码
`{
      title: '父ID',
      dataIndex: 'parentId',
      align: 'center',
      search: false,
      valueType: 'select',
    },`

**Comment by chenshuai2144** [comment]
valueEnum | 值的枚举，会自动转化把值当成 key 来取出要显示的内容 | valueEnum | -
-- | -- | -- | --




```tsx
 {
    title: '状态',
    dataIndex: 'state',
    initialValue: 'open',
    filters: true,
    valueEnum: {
      all: { text: '全部', status: 'Default' },
      open: {
        text: '未解决',
        status: 'Error',
      },
      closed: {
        text: '已解决',
        status: 'Success',
      },
      processing: {
        text: '解决中',
        status: 'Processing',
      },
    },
  },
```

**Comment by pengxingwang** [comment]
这个我知道，我想的是渲染动态的值，而且不用重写renderFormItem，因为接口里写了可以支持valueType: 'select'这个类型，如果还要重写renderFormItem这个方法，那'select'属性就没意义了

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/field#%E8%BF%9C%E7%A8%8B%E6%95%B0%E6%8D%AE
