### ISSUE TITLE
🧐[问题]官网pro-table的更新日志严重滞后，是否可以继续更新？

### ISSUE THREAD

**Issue by bluescurry** [ant-design/pro-components#934]
### 🧐 问题描述

pro-table 最新版本是2.10.0，但是文档的更新日志只到了2.8.0，导致想更新版本都不知道要注意哪些点，哪些API有改动等等，能否继续更新文档呢？

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/19237129/98512746-c085b800-22a1-11eb-9f49-a431ba5b4c01.png)
![image](https://user-images.githubusercontent.com/19237129/98512759-c5e30280-22a1-11eb-85a9-b220ca8685c2.png)

**Comment by chenshuai2144** [comment]
done，写了个工具自动更新
