### ISSUE TITLE
🧐[问题]后端的搜索api路径与Protable定义的不一样时如何修改搜索的代码

### ISSUE THREAD

**Issue by DunDunDunAbandon** [ant-design/pro-components#935]
### 🧐 问题描述

官方protable组件定义的搜索用的是queryRule，且页面每次刷新时都被调用：
```
request={(params) => queryRule({...params })}
export async function queryRule(params?: TableListParams) {
  return request('/api/Courses', {
    params,
  });
}
```
请求的路径是：http://localhost:9999/api/Users?current=1&pageSize=20&userId=1&_timestamp=1604917525976
但我后端的查询请求路径是：http://localhost:9999/api/Users/9
Users后的9是某一行data的key值。
请问应该如何修改？还是我重写搜索的组件，使之与页面刷新的request分离。

**Comment by chenshuai2144** [comment]
queryRule 的源码是这样的

```tsx
export async function queryRule(params?: TableListParams) {
  return request('/api/rule', {
    params,
  });
}
```
