### ISSUE TITLE
🧐[问题]pro-table的search是后台行为还是前台行为？

### ISSUE THREAD

**Issue by hongmaoxiao** [ant-design/pro-components#938]
首先pro-table这个很有用，很感谢开发者们，小白想问下search是前台行为还是后台行为，因为在开发的时候发现官网预览**查询表格**的搜索有效果，而状态的搜索没有效果，这时候就有点懵逼。固有此问，望能得到解答，谢谢！

**Comment by yutingzhao1991** [comment]
表单值变化的时候会触发 `request` 重新执行，这里的逻辑是用户自己写的，一般来说都是在这里重新请求后端。

**Comment by hongmaoxiao** [comment]
> 表单值变化的时候会触发 `request` 重新执行，这里的逻辑是用户自己写的，一般来说都是在这里重新请求后端。

懂了 谢谢！
