### ISSUE TITLE
🐛[BUG] @ant-design/pro-table 最新版本 和 react-dnd react-dnd-html5-backend 一起使用报错

### ISSUE THREAD

**Issue by zsytssk** [ant-design/pro-components#940]
### 🐛 bug 描述
@ant-design/pro-table 最新版本 和 react-dnd react-dnd-html5-backend 一起使用报错， 报错信息
Uncaught TypeError: backendFactory is not a function
将@ant-design/pro-table使用最新 2.10.0

### 💻 复现代码
https://codesandbox.io/s/antd-protable-bug-r5pk2
将 @ant-design/pro-table 版本换成 2.3.1 错误消失 (如果出现其他错误， 刷新几次页面就可以了， 可能是sandbox的问题)

### © 版本信息

- @ant-design/pro-table 版本: 2.10.0
- chrome
- mac OS

### 🚑 其他信息

<img width="630" alt="WX20201110-093937@2x" src="https://user-images.githubusercontent.com/2304648/98619031-5b7fa000-233d-11eb-8b55-904867e3512d.png">

**Comment by chenshuai2144** [comment]
你的最新版本是多新？ proTable 已经是最新版本的依赖了

**Comment by zsytssk** [comment]
> 你的最新版本是多新？ proTable 已经是最新版本的依赖了

![Uploading image.png…]()

**Comment by zsytssk** [comment]
> 你的最新版本是多新？ proTable 已经是最新版本的依赖了

![image](https://user-images.githubusercontent.com/2304648/98620226-d8ac1480-233f-11eb-99f0-7a517f477474.png)

**Comment by chenshuai2144** [comment]
Dnd的版本

**Comment by zsytssk** [comment]
> Dnd的版本

就是@ant-design/pro-table依赖的最新版本，react-dnd react-dnd-html5-backend 这两个 几个月都没有更新了；
你去我那个[示例网址](https://codesandbox.io/s/antd-protable-bug-r5pk2)看看，示例都给你做好了，错误一目了然；
将 @ant-design/pro-table 版本换成 2.3.1 错误消失 (如果出现其他错误， 可能是codesandbox.io的问题 刷新几次页面就可以了)
那个网址需要翻墙， 你要是不会问问你的同事，应该很容易；

**Comment by chenshuai2144** [comment]
😂 给个repo吧 你好像听不懂我说啥

**Comment by zsytssk** [comment]
我的天啊， 你看看那个示例不行吗？点开就可以了，已经给你线上重现了，你还要怎样？
我听不懂你说的，你又能知道我说什么吗？说的就是Prorable最新版本的bug，你是程序员吗？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/blob/e75b97bc8a456da4eefc5545cc1c22d9b67ac2ac/packages/table/package.json#L48

是最新版本，请清晰的描述问题，搞人生攻击解决不了问题的

**Comment by zsytssk** [comment]
好吧 
@ant-design/pro-table依赖的react-dnd react-dnd-html5-backend 都是最新版本（我承认这一点，我一直都没说是这问题， 可能是我表达的有歧义， 我是说那两个模块本身在npm仓库中几个月没更新了，不是说在@ant-design/pro-table中依赖没更新），但是依然报错！！！

这应该就是@ant-design/pro-table本身的问题了，可能它升级时破坏了和react-dnd react-dnd-html5-backend交互的逻辑；

现在问题描述没有问题了吧！

我就不懂了，那个链接你是打不开吗？我们作为程序员， 我已经show you the code（里面能看到所有的package的版本）! 你点击进去就可以看到报错！这么直接的方式，怎么还搞这么多的时间...,也许我表达不清，但是你点进去, 你的疑问就可以解决啊... 天底下没有比这更直接的bug重现了。你非要纠结于我描述问题，我不知道你在想什么？

你回答两个简单问题，就可以发现交流的出现问题实质是什么！

1. 你尝试打开那个示例了吗 ？
2. 你能打开那个示例吗 ？

你能回答我这两个简单的问题吗 ？

**Comment by chenshuai2144** [comment]
来个重现仓库，没有的话我不会提供帮助了

**Comment by zsytssk** [comment]
等我明天上班创建一个

**Comment by siyi98** [comment]
> 等我明天上班创建一个
```js
import { HTML5Backend } from "react-dnd-html5-backend";
```
@zsytssk 貌似是你的姿势不对呀，我看了下react-dnd-html5-backend的源码，正确写法应该如上

**Comment by zsytssk** [comment]
> > 等我明天上班创建一个
> 
>  https://codesandbox.io/s/antd-protable-bug-forked-om6md?file=/src/protable.tsx
> ```js
> import { HTML5Backend } from "react-dnd-html5-backend";
> ```
> @zsytssk 貌似是你的姿势不对呀，翻了下react-dnd-html5-backend的源码，正确写法应该如上

好的我试试
