### ISSUE TITLE
🧐[问题] antd v3升到v4 安装pro-table 跑示例代码报错

### ISSUE THREAD

**Issue by KIngCrzy** [ant-design/pro-components#941]
### 🧐 问题描述

antdv3升到v4 安装pro-table 然后跑示例代码就报错

### 🚑 其他信息
[image](https://user-images.githubusercontent.com/37181687/98622246-0430fe00-2344-11eb-86b6-94a66aa34359.png)

**Comment by siyi98** [comment]
项目使用的react版本号是多少

**Comment by KIngCrzy** [comment]
> 项目依赖的react版本号是多少

"react": "^16.8.6",
"@ant-design/icons": "^4.0.2",
"@ant-design/pro-layout": "^4.10.0",
"@ant-design/pro-table": "^2.10.0",

**Comment by siyi98** [comment]
> > 项目依赖的react版本号是多少
> 
> "react": "^16.8.6",
> "@ant-design/icons": "^4.0.2",
> "@ant-design/pro-layout": "^4.10.0",
> "@ant-design/pro-table": "^2.10.0",
> "antd": "4.6.3",

我这里没有复现，你跑的是哪个示例代码呢，文档链接贴一下看看？😃

**Comment by KIngCrzy** [comment]
https://procomponents.ant.design/components/table 第一个查询表格  
可能是我antd版本升上来的时候包装的有点问题 我把node_modules和 package-lock.json删了重新装一次依赖就好了

**Comment by siyi98** [comment]
ok👌
