### ISSUE TITLE
👑 [需求]打开splitMenus的情况下，能否支持一级菜单渲染自身comp

### ISSUE THREAD

**Issue by 3lang3** [ant-design/pro-components#942]
### 🥰 需求描述
现在splitMenus打开，一级路由只能redirect到二级路由，不然二级路由无法显示，这样就丢失一级路由渲染能力，而splitMenus模式下的一级路由很明显是可以单独点击和渲染的。

**Comment by chenshuai2144** [comment]
自己配就好了吧，你碰到了什么问题

**Comment by 3lang3** [comment]
@chenshuai2144 
我使用`yarn create umi` pro v5，然后只改了app.ts的以下地方
```
```

**Comment by 3lang3** [comment]
@chenshuai2144 具体问题就是，
splitMenus为true现在只能二选一：
a: 点击一级路由渲染一级路由配置的comp，此时点击边栏的二级路由就无法正常显示(显示的还是一级路由的comp)
b: 点击一级路由redirect到二级路由

**Comment by chenshuai2144** [comment]
这样很合理吧？你想要什么？

**Comment by 3lang3** [comment]
一二级路由切换， 永远渲染的是一级路由的component

![Nov-10-2020 14-34-11](https://user-images.githubusercontent.com/7098719/98636467-e2467400-2361-11eb-8b89-9a0e9879cf4b.gif)

**Comment by chenshuai2144** [comment]
不要设置子节点就行

**Comment by 3lang3** [comment]
@chenshuai2144 
需求就是二级管理页是管理页的子路由，点管理页渲染管理页面，点二级管理页渲染二级管理页面，现在是不是无法通过配置实现？

**Comment by chenshuai2144** [comment]
把 router 的配置打平，这样不就行了
```
/list/:id
/list
```
听不懂你的描述，你试试，不行提供一下代码或者示例图吧，我们对 component 的理解可能不一样
