### ISSUE TITLE
🐛[BUG] pro-form的ProFormCaptcha组件loading问题

### ISSUE THREAD

**Issue by 3lang3** [ant-design/pro-components#943]
### 🐛 bug 描述
onGetCaptcha触发后loading总会为true, 即使onGetCaptcha抛出了Promise.reject
```
setLoading({
    delay: 100,
});
await restProps.onGetCaptcha(mobile);
setLoading(false);
setTiming(true);
```

### 📷 复现步骤
官网demo就可复现

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by 3lang3** [comment]
其实这里加一个onGetCaptchaBefore比较合适，一般点击获取手机验证码按钮，会弹出图片验证框来防止短信服务被刷，只有通过图形验证码才会进入loading倒计时。

**Comment by chenshuai2144** [comment]
在 onGetCaptcha 之前做这件事也行的，等图片框完成了再去触发。

```tsx
onGetCaptcha={()=>{
   await onGetCaptchaBefore();
   await getCode();
}}
```
