### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by eriksyuan** [ant-design/pro-components#946]
### 💻 示例代码
<ProTable<PushPosterItem, PushPosterItem>
          form={{
            initialValues: defaultFormData,
            layout: 'horizontal',
          }}
          formRef={editFormRef}
          rowKey="id"
          type="form"
          columns={columns}
          onSubmit={async (value) => {
            await editFormRef.current?.validateFields();
            await updatePoster({ ...value, id: defaultFormData.id });
            setDefaultFormData({});
            setEditVisible(false);
            if (actionRef.current) {
              actionRef.current.reload();
            }
          }}
        />

**Comment by WenyXu** [comment]
Hi guy, same problem here.
I just review the source code, and find a solution here, add following code may help you
```
<ProTable
...
form={{
            submitter: {
              resetButtonProps: { hidden: true },
            },
          }}
/>
```
see also https://github.com/ant-design/pro-components/blob/55dffd06015a370e1e9cd69a3aeefe76bd498360/packages/table/src/Form/index.tsx#L499
