### ISSUE TITLE
🧐[问题]ProTable的表格列宽不能自适应吗

### ISSUE THREAD

**Issue by Augustzyh** [ant-design/pro-components#948]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/38031220/98654003-b387c800-2378-11eb-82c9-842669dc95b5.png)

问题：
1、请问列过多，如何自适应横向滚动；
2、请问行过多，如何固定高度垂直滚动；
3、请问2条件下如何固定表头；

**Comment by Augustzyh** [comment]
![image](https://user-images.githubusercontent.com/38031220/98654237-0497bc00-2379-11eb-8d25-9655cd416849.png)
图片加载不出来吗？

**Comment by chenshuai2144** [comment]
开了 eslipse 就不行了，你可以试试设置 table 的宽度

**Comment by Augustzyh** [comment]
都不行，自己改了一版搞定了横向自适应滚动，纵向固定表头和高度加滚动，但是出现了一个透明度的问题，我把protable下所有元素都翻了一边没找到啥问题，如图，body的层级永远高于head，无论head设置多高层级，加什么背景颜色，body总会显示在head上，敢问大佬你知道有啥默认样式，或者怎么回事嘛

**Comment by Augustzyh** [comment]
都不行，自己改了一版搞定了横向自适应滚动，纵向固定表头和高度加滚动，但是出现了一个透明度的问题，我把protable下所有元素都翻了一边没找到啥问题，如图，body的层级永远高于head，无论head设置多高层级，加什么背景颜色，body总会显示在head上，敢问大佬你知道有啥默认样式，或者怎么回事嘛
![image](https://user-images.githubusercontent.com/38031220/98691990-97e8e580-23a9-11eb-8f2e-5c2765f901da.png)

**Comment by Augustzyh** [comment]
![image](https://user-images.githubusercontent.com/38031220/98693234-00849200-23ab-11eb-9243-31082e8d8ee4.png)
好像可以解决了，作者要不要考虑加两个props解决autoscroll的问题

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/98761311-2001d600-2410-11eb-8f23-a896947b0e44.png)

https://ant.design/components/table-cn/#API

antd 已经有 api了
