### ISSUE TITLE
👑 [需求] 轻量筛选表格 用户体验优化建议

### ISSUE THREAD

**Issue by wuhao930406** [ant-design/pro-components#949]
### 🥰 需求描述

期望  
1.轻量筛选表格的 form 右侧的Icon 可以根据类型来 input 用search的icon select用下拉的icon
2.点击展开后input自动focus
3.触发submit的方法支持 通过 input的 onEnter  / select 的 onChange事件

### 🧐 解决方案
form的位置不变 展开之后像图片这样展示：
![image](https://user-images.githubusercontent.com/18044670/98656629-d9629c00-237b-11eb-9588-6221d0645770.png)
![image](https://user-images.githubusercontent.com/18044670/98656635-db2c5f80-237b-11eb-80da-f076328adae9.png)

**Comment by chenshuai2144** [comment]
欢迎可操作性跟强的提议

**Comment by chenshuai2144** [comment]
这个功能可能需要 antd 的 table 支持一下，我们这里不好支持
