### ISSUE TITLE
🧐[问题]想请教一下proTable怎么做本地排序

### ISSUE THREAD

**Issue by David2k13** [ant-design/pro-components#951]
### 🧐 问题描述
不知道是不是自己方法不对，request获取到了sort，但是还是会发送数据请求，不知道怎么判断是排序触发(本地排序不希望触发发送请求数据，但是希望获得sort数据去缓存，下次进入作为默认排序)，还是刷新/重置/搜索(这些算一类的，都是要发送请求)触发的，还是有其它api呢

**Comment by chenshuai2144** [comment]
@David2k13  和 antd 相同，重置一下 sort 方法就可以本地排序了，不过 request 还是会被重复发

**Comment by David2k13** [comment]
> @David2k13 和 antd 相同，重置一下 sort 方法就可以本地排序了，不过 request 还是会被重复发

现在就是比较头大， request 会发请求，也没什么曲线救国的办法

**Comment by chenshuai2144** [comment]
因为 sort 发生变化了，这个展示的确没法拦住，你可以想个办法，大家讨论一下，合适可以加进去

**Comment by David2k13** [comment]
好的，有时间研究下

**Comment by David2k13** [comment]
刚刚想到一个比较蠢的办法，利用onHeaderRow保存一个state，然后request里面判断这个值来阻止接下来的请求

**Comment by chenshuai2144** [comment]
可以配置一下 onFilter:true ，来使用 ProTable 自带的筛选

**Comment by David2k13** [comment]
nice

**Comment by liuhong1happy** [comment]
请问这里怎么处理的，本地排序

**Comment by PolarBears** [comment]
> 请问这里怎么处理的，本地排序

我是在onChange里判断extra.action为sort时存个flag，再在request里做处理阻止发出请求并清除flag。

**Comment by SuperZ3** [comment]
我的需求是初始请求使用 request，后续的排序在本地进行，并且没有 filter

这种情况下，将初次 request 获取的 data 保存下来叫 dataRef，如果后续点击 sorter 时 dataRef 非空，就直接返回 dataRef

**Comment by JS-an** [comment]
request加个type参数，自行判断是由哪些类型的动作触发，应该就能完美实现这个需求

**Comment by mansion-sun** [comment]
> request加个type参数，自行判断是由哪些类型的动作触发，应该就能完美实现这个需求

更具体些由params, sort, filter，三种参数自由组合的参数类型数组，来判断是新请求，还是根据sort, filter过滤上次查询的数据

**Comment by bitbw** [comment]
Columns  建议加个字段， 用于判断是否需要发起请求

```ts

   sortType?: "local" | "request"
   
   ```

**Comment by seifenk** [comment]
> > 请问这里怎么处理的，本地排序
> 
> 我是在onChange里判断extra.action为sort时存个flag，再在request里做处理阻止发出请求并清除flag。

谢谢你
