### ISSUE TITLE
版本的升级太具有破坏性

### ISSUE THREAD

**Issue by jockey100332** [ant-design/pro-components#952]
在开发过程当中发现pro-table 的升级太具有破坏性，在做版本升级的时候需要很多api就给弃用了，包括很多依赖还有之前需求的代码都需要做修改。在多人开发的时候就发现了一个非常严重的问题，有时候导致为了升级一下版本，反而需要对很多依赖和之前的老代码做修改，这样太不稳定了。希望下次版本升级的时候可以兼容一下旧版本，最起码不要做一次升级，整个项目全是报错运行不下去了啊

**Comment by yutingzhao1991** [comment]
是哪个版本升到哪个版本？

**Comment by jockey100332** [comment]
> 是哪个版本升到哪个版本？

2.35 =》 2.40

2.40 之后的大版本做了底层代码的大升级，所以我想只升级到2.40看一下全选分页的那个bug 是否有解决，结果很多原来定义的数据结构不支持了。

**Comment by shenxiang11** [comment]
完全赞同！！！！！
Form 也是，ProFormDigit 原来默认 width 还可以，结果升级后突然变短了，虽说和圣诞彩蛋比起来不算什么，但是还是不应该这样

**Comment by hongmaoxiao** [comment]
under heavy develop 中好像有时候不可避免 说明改进之后更优秀啊😂😂😂

**Comment by chenshuai2144** [comment]
设计上的改动是有点大，因为形态还不是很确定，这个库是作为了一个底层库来运营的，发布也比较频繁。

bug 和功能是尽量兼容的，我们也专门花功夫提升了测试覆盖率

**Comment by jockey100332** [comment]
> under heavy develop 中好像有时候不可避免 说明改进之后更优秀啊😂😂😂



> 设计上的改动是有点大，因为形态还不是很确定，
> 这个库是作为了一个底层库来运营的，发布也比较频繁，在达到很大的使用量之后可能 才会稳定
> 
> bug 和功能是尽量兼容的，我们也专门花功夫提升了测试覆盖率

不知不觉中又当了小白鼠🐁。。。。。。

**Comment by chenshuai2144** [comment]
轮子就是这样的，新轮子不稳定但是支持好。旧轮子很稳定，但是基本不会理普通人的需求
