### ISSUE TITLE
🧐[问题]ProFormSelect不能使用onchange 或者 onselect

### ISSUE THREAD

**Issue by vuvivian** [ant-design/pro-components#957]
### 🧐 问题描述
ProFormSelect不能使用onchange 或者 onselect， 都说通过onValuesChange来解决 ，
但是我如果要拿 select item数据的其他属性 在onValuesChange是拿不到的啊
难道只能再请求后台？
比如 有个select 的数据结果集是 [{label: '区域', value: '001',  des: '额外的值''}]
在选择这个区域的时候我想拿到 des 是拿不到的

有什么更好的解决方案吗？

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/pro-components/issues/860

**Comment by chenshuai2144** [comment]
自己封装一下吧，ProFormSelect 很难实现这个功能，可以考虑做个 feature

**Comment by vuvivian** [comment]
> 自己封装一下吧，ProFormSelect 很难实现这个功能，可以考虑做个 feature
> 
> 或者用 fieldProps.onselect 是支持的
> 
> > 需要升级到最新的版本，原来有个 bug 没支持onselect
嗯呐

**Comment by viper140** [comment]
```html
<ProCard onChange={handleChange}>
    <ProFormSelect label='xx' name='xx'/>
</ProCard>
```
这样写也是无法监听到下拉框的变化的，虽然知道可以`fieldProps={{ onSelect: (e) => console.log(e) }}`来解决，但还是想蹲个解释
