### ISSUE TITLE
🧐[问题]请问把 ProForm 的 umd bundle单独放到 scripts 里引入时，如何获取其 ProFormItem 的各类组件？

### ISSUE THREAD

**Issue by CXHtml** [ant-design/pro-components#958]
### 🧐 问题描述
 因为某些特殊原因，需要以 script 的方式引入 ProForm，但发现在 webpack 下设置了 externals：

![image](https://user-images.githubusercontent.com/6263570/98801789-498d2280-244d-11eb-89f7-471566994d90.png)

页面内只能正常访问到注入到 window 下的 ProForm，但其他的如 ProFormText、ProFormRadio 等 ProFormItem 组件应该如何获取？

貌似以解构的方式获取不到这些组件：

### 💻 示例代码

```
import ProForm, { ProFormText, ProFormSelect, ProFormRadio } from '@ant-design/pro-form';
// 在上述的情况下获取不到 ProFormText, ProFormSelect, ProFormRadio 等

```

**Comment by chenshuai2144** [comment]
ProForm.xxxx 试试这样的。

**Comment by CXHtml** [comment]
> ProForm.xxxx 试试这样的。

um~ 这样依旧没有，只有 ProForm 自己的属性 Group、useForm

看了下 umd 的产物最后是默认以 esm 的 default 导出到 ProForm 的：

![image](https://user-images.githubusercontent.com/6263570/98894478-cec11780-24df-11eb-8279-d83a6a37217c.png)
目前暂时是把 bundle 最后`['default']` 去掉貌似就可以了：

![image](https://user-images.githubusercontent.com/6263570/98894391-a9340e00-24df-11eb-8a21-8e48aac89efd.png)

是 proComponent 打包到 umd 的 webpack 配置问题，还说用户这边 webpack 配置问题呢？

**Comment by chenshuai2144** [comment]
看起来是umd打包的问题

**Comment by liuchuangjun321** [comment]
> 看起来是umd打包的问题

同遇到了这个问题，打包构建的产物不能直接可用。

**Comment by chenshuai2144** [comment]
@liuchuangjun321 @CXHtml   修了，修改了一下打包方式，你们试试

**Comment by Atw-Lee** [comment]
请问在哪找托管的umd地址
