### ISSUE TITLE
设置initialValue的值为请求数据的第一项🧐[问题]

### ISSUE THREAD

**Issue by W-ambition** [ant-design/pro-components#959]
### 🧐 问题描述
ProColumns，搜索时，Select的值是从服务端请求的数据，需要把服务端返回的数据的第一条作为默认值。该怎么设置initialValue，因为请求前数据肯定是undefined，怎样在请求成功后设置默认值？

![image](https://user-images.githubusercontent.com/22684905/98805960-6298d200-2453-11eb-83ec-1ba68a34666d.png)

**Comment by W-ambition** [comment]
![Uploading issues.png…]()

**Comment by W-ambition** [comment]
{
      title: '仓库编码',
      dataIndex: 'WareHouseId',
      hideInTable: true,
      fieldProps: {
        allowClear: false,
      },
      initialValue: wareHouseValue,
      filters: true,
      request: async () => {
        const result = await queryWareHouse({});
        let list: OptionsType[] = [];
        if(result.Code === 200) {
          result.data.map((item: OptionData) => {
            list.push({
              label: item.WareHouseName,
              value: item.WareHouseId
            })
          })
          list[0] ? setWareHouseValue(list[0].value) : null;
        }
        return list
      }
    }

**Comment by chenshuai2144** [comment]
这个难度有点大了，你可以 loading 的时候不渲染的 ProTable 加载完成之后再 渲染。

`if(loading) return null`

**Comment by W-ambition** [comment]
> 这个难度有点大了，你可以 loading 的时候不渲染的 ProTable 加载完成之后再 渲染。
> 
> `if(loading) return null`

这样也挺好的，目前感觉最好的办法了
