### ISSUE TITLE
🧐[问题]全屏按钮被取消了嘛？

### ISSUE THREAD

**Issue by daifuyang** [ant-design/pro-components#961]
### 🧐 问题描述

为啥proTable默认不显示全屏按钮了？

### 💻 示例代码

https://codesandbox.io/s/hd1ub

**Comment by chenshuai2144** [comment]
全屏用起来需要一些技术含量，答疑成本很高
你可以用 `fullscrenn:true` 打开。

**Comment by daifuyang** [comment]
谢谢，明白了
