### ISSUE TITLE
🐛[BUG]  ProFormText.PassWord  使用报错

### ISSUE THREAD

**Issue by Jiyr0119** [ant-design/pro-components#962]
### 🐛 bug 描述

ProForm中使用 ProFormText.Password 报错：

React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### 📷 复现步骤

使用这个组件就有问题

### 🏞 期望结果

发版本解决

### 💻 复现代码

下面截图的代码里面 是一个 Modal 弹窗  我用password 就白屏  换成普通的就没问题  所以肯定是password的问题 

### © 版本信息

![image](https://user-images.githubusercontent.com/28727613/98892549-8869b980-24db-11eb-9283-91a1722659e1.png)

- umi 版本 3.2.0
- 浏览器环境 谷歌浏览器 版本 85.0.4183.102（正式版本） （64 位）
- 开发环境  mac OS 

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/28727613/98892399-345ed500-24db-11eb-9660-60e9be2ef451.png)

![image](https://user-images.githubusercontent.com/28727613/98892430-43de1e00-24db-11eb-9b01-b5ba9da6644d.png)

**Comment by chenshuai2144** [comment]
`ProFormText.Password` 记得要用 ts 哦，不然错别字很尴尬。

> ProFormText.PassWord 被老外说是错别字

**Comment by Jiyr0119** [comment]
那如果是js的话 怎么操作呀 大佬

**Comment by chenshuai2144** [comment]
靠自己牛逼的记忆力
