### ISSUE TITLE
ProFormTimePicker组件报错“date.clone is not a function”🐛[BUG]

### ISSUE THREAD

**Issue by quarkcms** [ant-design/pro-components#964]
### 🐛 bug 描述
@chenshuai2144  帅哥，ProFormTimePicker组件报错“date.clone is not a function”，我试了一下使用string类型的时间格式报错

**Comment by chenshuai2144** [comment]
要用moment类型 不然antd不支持

**Comment by quarkcms** [comment]
现在其他日期组件都是支持string类型的，所以是不是时间组件也支持string类型呢？

**Comment by chenshuai2144** [comment]
有空写个测试用例吗？ 应该都不支持的

**Comment by quarkcms** [comment]
我刚才测试了一下，ProFormDatePicker、ProFormDateTimePicker这些组件都支持string类型，唯独ProFormTimePicker组件不支持

**Comment by quarkcms** [comment]
下面是我项目中用到的：https://github.com/quarkcms/quark-ui/blob/master/src/pages/Quark/components/Form.tsx

**Comment by quarkcms** [comment]
@chenshuai2144 如果有精力可以一起玩玩https://github.com/quarkcms/quark-ui这个项目，我的想法是在Ant Design Pro上做进一步的封装，根据后台的接口返回的数据渲染页面。

**Comment by lizhiyao** [comment]
同在项目中遇到这个问题，请问这个 fix 什么时候可以发一个新版？ @chenshuai2144
