### ISSUE TITLE
🧐[问题]针对pro-table column中search是true的select组件，showSearch属性，mode属性，optionFilterProp属性均无效。

### ISSUE THREAD

**Issue by liuchuangjun321** [ant-design/pro-components#965]
### 🧐 问题描述

🧐[问题]针对pro-table column中search是true的select组件，showSearch属性，mode属性，optionFilterProp属性均无效。

### 💻 示例代码

```
{
valueEnum: [
    //...
],
fieldProps: {
    mode:'tags'
},
showSearch:true,
optionFilterProp: "children"
search:true
// ...其余配置
}
```

### 🚑 其他信息

pro-table@2.9.3

**Comment by chenshuai2144** [comment]
要用 fieldProps

![image](https://user-images.githubusercontent.com/8186664/99236802-9d737f00-2832-11eb-91d5-1b472764ed1f.png)
