### ISSUE TITLE
🐛[BUG] ProTable 自定义表单使用renderFormItem: (item, config, form)，但传入的config里面onChange是null

### ISSUE THREAD

**Issue by BarronLin** [ant-design/pro-components#967]
### ProTable 自定义表单使用renderFormItem: (item, config, form):

`{
      title: '系统模块',
      dataIndex: 'client',
      width: 120,
      renderFormItem: (item, config, form) => {
        console.log(config);
        return <ItemSelect onChange={config.onChange} value={config.value} />;
      },      
    }
`
但是结果：
![image](https://user-images.githubusercontent.com/9267731/98941829-0c499300-2528-11eb-9798-33ecae784119.png)

### © 版本信息

- ProTable 版本: 2.9.13 
- umi 版本^3.2.14
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

**Comment by beside4ever** [comment]
遇到了同样的问题

**Comment by chenshuai2144** [comment]
已经不需要这样写了，和FormItem 一样会自动接管了
