### ISSUE TITLE
🧐[问题]ProTable组件以下配置在查询表单中不生效rules配置的必填项

### ISSUE THREAD

**Issue by zc1175** [ant-design/pro-components#968]
ProTable组件以下配置在查询表单中不生效rules配置的必填项
{
      title: '规则名称',
      dataIndex: 'name',
      tip: '规则名称是唯一的 key',
      formItemProps: {
        rules: [
          {
            required: true,
            message: '规则名称为必填项',
          },
        ],
      },
      
    },

**Comment by chenshuai2144** [comment]
这是专门不打开的 查询表单应该用默认值 而不是rules
