### ISSUE TITLE
🧐[问题] 如何设置ProTable FormItem 属性

### ISSUE THREAD

**Issue by yezongyang** [ant-design/pro-components#970]
### 🧐 问题描述

设置FormItem属性

**Comment by siyi98** [comment]
@yezongyang 试试搜索表单自定义属性呢
https://procomponents.ant.design/components/table#%E6%90%9C%E7%B4%A2%E8%A1%A8%E5%8D%95%E8%87%AA%E5%AE%9A%E4%B9%89

**Comment by yezongyang** [comment]
文档缺失了，查看源码发现有formItemProps参数设置
