### ISSUE TITLE
ProFormSelect 中 width不起作用🐛[BUG]

### ISSUE THREAD

**Issue by LichiaMa** [ant-design/pro-components#972]
### 🐛 bug 描述'
升级最新的antd和procomponent之后，pro-form中的ProFormSelect组件width属性不起作用，被antd的样式覆盖

### © 版本信息

- ProComponents 版本: 1.4.1
- antd版本： 4.8.2
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
<img width="1307" alt="FEE1BF33-0385-47D7-9B91-0D9F6C1F1802" src="https://user-images.githubusercontent.com/17775060/99028100-e95fc300-25a9-11eb-8639-643bbe6c6c6c.png">

**Comment by chenshuai2144** [comment]
修掉了 再更新一下

**Comment by LichiaMa** [comment]
我看最新版本还没变，还是1.4.1

**Comment by huohongchang1026** [comment]
同问

**Comment by huohongchang1026** [comment]
哥们赶紧publish 着急用呢

**Comment by chenshuai2144** [comment]
1.4.1 已经fix了，提升了优先级

**Comment by LichiaMa** [comment]
> 1.4.1 已经fix了，提升了优先级

没有修复啊，我的就是1.4.1啊，一只有这个问题，包括官网上面的示例都有这个问题

**Comment by kenzheng2020** [comment]
1.4.1 还有这个问题
