### ISSUE TITLE
🧐 Change the format of the dateTime in ProTable

### ISSUE THREAD

**Issue by iloveip** [ant-design/pro-components#973]
Hi there,

Is it possible to change the format of the dates? For example, I would like to use `{moment(date).format('DD.MM.YYYY HH:mm')}` instead of default `dateTime` value. I know that I can use render in columns, but in this case valueType is set to string, and there is no DatePicker in search

**Comment by chenshuai2144** [comment]
I will support custom

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/table#%E8%87%AA%E5%AE%9A%E4%B9%89-valuetype

I have supported

**Comment by iloveip** [comment]
Thank you very much 🙏
