### ISSUE TITLE
🧐[问题] proTable 重置的时候如何手动清空form

### ISSUE THREAD

**Issue by hazeFlame** [ant-design/pro-components#977]
### 🧐 问题描述

我在initialValue 上设置为location.query.name
搜索的时候跳转路由进行数据查询
重置后也是跳转路由 此时location.query.name 为空
form.resetFields 并没有清理掉

**Comment by chenshuai2144** [comment]
formRef | 可以获取到查询表单的 form 实例，用于一些灵活的配置 | React.MutableRefObject<ActionType> \| ((actionRef: ActionType) => void) | -
-- | -- | -- | --



https://procomponents.ant.design/components/table#%E9%80%9A%E8%BF%87-formref-%E6%9D%A5%E6%93%8D%E4%BD%9C%E6%9F%A5%E8%AF%A2%E8%A1%A8%E5%8D%95
