### ISSUE TITLE
layout 6.5.14 table 2.10.1 需要依赖react或者其他的什么版本

### ISSUE THREAD

**Issue by Haloxylon** [ant-design/pro-components#978]
"@ant-design/icons": "^4.0.0",
"@ant-design/pro-layout": "5.0.16",
"@ant-design/pro-table": "2.3.4",
"antd": "^4.6.1",
"react": "^16.8.6",
"react-dom": "^16.8.6",

今天发现有的需求老版本没有新版本实现的方便，layout 6.5.14 table 2.10.1后  ProLayout  ProTable  都飙红了

**Comment by chenshuai2144** [comment]
是什么问题吗？ 
16.8 是可以支持的

**Comment by hankaibo** [comment]
公司项目还在使用 antd 3.x.x版本，使用layout 4.x.x组件，我看源码里写着依赖是antd4.x，我使用antd 3.x有影响吗？我还可以继续升级loyout版本吗？@chenshuai2144

**Comment by chenshuai2144** [comment]
不能的，是需要antd@4 的。不然跑不起来

**Comment by hankaibo** [comment]
我现在的项目，"antd": "^3.26.20", "@ant-design/pro-layout": "^4.10.10",项目还跑起来了。😂
去看了node_modules，pro-layout是"version": "4.11.4"，antd是"version": "3.26.20"，没有其它的了。
在考虑要不要降级回去。😂

**Comment by chenshuai2144** [comment]
@hankaibo  @ant-design/pro-layout@5 可以同时支持 4 和5
