### ISSUE TITLE
🐛[BUG]  tableAlertOptionRender 自定义批量操作工具栏右侧选项区域 设置 false仍然显示

### ISSUE THREAD

**Issue by zmj0920** [ant-design/pro-components#979]
### 🐛 bug 描述

 tableAlertOptionRender 自定义批量操作工具栏右侧选项区域 设置 false仍然显示

### 💻 复现代码

<ProTable   tableAlertOptionRender ={false} />

### © 版本信息

- "@ant-design/pro-table": "^2.10.1",
- "umi": "^3.2.27",
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/42410507/99147754-68deb680-26be-11eb-8e68-e9d9d2b34b5e.png)
文档使用说明
![image](https://user-images.githubusercontent.com/42410507/99147768-83b12b00-26be-11eb-94ef-85c466432e07.png)

**Comment by chenshuai2144** [comment]
tableAlertOptionRender  是 右侧，tableAlertRender 才会完全不显示
