### ISSUE TITLE
🐛[BUG] 表格跟formilyjs冲突的问题何时会解决

### ISSUE THREAD

**Issue by yunuo-tech** [ant-design/pro-components#98]
### 🐛 bug 描述

之前提过的，https://github.com/ant-design/ant-design-pro-layout/issues/546

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by sugov5** [comment]
我也遇到类似的问题，现在有解决方案吗？

**Comment by yunuo-tech** [comment]
> 我也遇到类似的问题，现在有解决方案吗？
> Ant Design Pro v5

将antd.css在app.tsx最前头引用就行了
