### ISSUE TITLE
proTable组件在操作区域边上中会出现一个数字0🐛[BUG]

### ISSUE THREAD

**Issue by tuyeye** [ant-design/pro-components#981]
在 toolBarRender 属性中，设置多选操作后，未选中时会出现数字0，选中出现正常的按钮

未选中
![image](https://user-images.githubusercontent.com/55080157/99207203-4fda2080-27f8-11eb-8dfe-399944b3315e.png)

选中
![image](https://user-images.githubusercontent.com/55080157/99207392-dabb1b00-27f8-11eb-86c4-919174e90755.png)

所有浏览器均是如此问题，希望尽早解决此bug

**Comment by chenshuai2144** [comment]
toolBarRender 怎么写的，我复现不了你的问题欸
