### ISSUE TITLE
🐛[BUG]在protable中使用过长的columns会导致后面的column前移至第一列

### ISSUE THREAD

**Issue by saltovo** [ant-design/pro-components#983]
### 🐛 bug 描述
在protable中使用过长的columns会导致后面的column前移至第一列

使用protable的情况
![image](https://user-images.githubusercontent.com/46911969/99209063-3687a300-27fd-11eb-979b-d64ef600fde2.png)

使用table的情况
![image](https://user-images.githubusercontent.com/46911969/99209122-60d96080-27fd-11eb-8a47-d7c0793a6969.png)

columns与datasource相同

尝试更新至最新版本的pro-table该问题依旧存在

### © 版本信息

- ProComponents 版本: pro-table 版本 2.9.11
- umi 版本 3.2.24
- 浏览器环境 chromium 63.0.3237.0 chorme  60.0.3112.90
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个重现吧，试了一下是不会的。
