### ISSUE TITLE
🧐[问题]protable搜索表单的字段长度怎么自定义？

### ISSUE THREAD

**Issue by yuzifu** [ant-design/pro-components#985]
试过在列定义里添加fieldProps，但没有效果。

```
fieldProps: { width: 30 }
```

**Comment by chenshuai2144** [comment]
```
fieldProps={
{ style: { width: "" } }
}
```
推荐使用我们的 width， 提供了预设的宽度。
https://procomponents.ant.design/components/form#%E9%80%9A%E7%94%A8%E7%9A%84%E5%B1%9E%E6%80%A7

**Comment by yuzifu** [comment]
> ```
> fieldProps={
> { style: { width: "" } }
> }
> ```
> 
> 推荐使用我们的 width， 提供了预设的宽度。
> https://procomponents.ant.design/components/form#%E9%80%9A%E7%94%A8%E7%9A%84%E5%B1%9E%E6%80%A7

实现上，您说的方法我也试过，一样无效:
```
const columns: ProColumns<RecordItem>[] = [
    {
      title: 'Name',
      dataIndex: 'name',
      fieldProps: {
        style: {
          width: 'xs',
        },
      },
    },
...
]
```

**Comment by yuzifu** [comment]
> ```
> fieldProps={
> { style: { width: "" } }
> }
> ```
> 
> 推荐使用我们的 width， 提供了预设的宽度。
> https://procomponents.ant.design/components/form#%E9%80%9A%E7%94%A8%E7%9A%84%E5%B1%9E%E6%80%A7

请看这个示例，https://codesandbox.io/s/friendly-hypatia-srq6d
我给Title列添加了如下代码
```
    fieldProps: {
      style: {
        width: 'xs'
      }
    },
```
没有效果。

**Comment by chenshuai2144** [comment]
filedProps里面的长度要用px

**Comment by askurat** [comment]
@yuzifu Did you get this to work?

Setting this has no effect:
```
fieldProps: {
      style: {
        width: '500px'
      }
    },
```

**Comment by chenshuai2144** [comment]
@askurat  try colSize, 
Grid system is used in the enquiry form

**Comment by askurat** [comment]
@chenshuai2144 I am using lightweight filters. Setting this:
```
fieldProps: {
        colSize: 500,
      }
```
or this on the ProColumn:
```
 colSize: 500
```
Neither do anything. The size of the filter stays the same.

![image](https://user-images.githubusercontent.com/9997087/103099319-a266e380-45d3-11eb-8399-42348f36a47e.png)

**Comment by chenshuai2144** [comment]
like this
```
 {
    title: '创建时间',
    key: 'since',
    colSize: 2,
    dataIndex: 'created_at',
    valueType: 'dateTime',
    width: '20%',
    render: (value) => {
      return {
        children: value,
        props: { colSpan: 2 },
      };
    },
  },
```

**Comment by askurat** [comment]
That does not work. I am trying to expand my dropdown size in the lightweight filter, not in the column.

**Comment by askurat** [comment]
Found what I was looking for:
`
 fieldProps: {
        dropdownMatchSelectWidth: 225
      }
`
