### ISSUE TITLE
🐛[BUG] proTable升级到2.8.0版本后Columns中的valueEnum属性失效了

### ISSUE THREAD

**Issue by zhuqiu** [ant-design/pro-components#986]
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
升级到最新版本呢？

**Comment by kobebing** [comment]
![image](https://user-images.githubusercontent.com/43462636/99238267-7b7afc00-2834-11eb-856e-2104ce712936.png)
升级到最新版本也不行，而且还存在其他的样式问题

**Comment by kobebing** [comment]
ant 版本是4.8.2
