### ISSUE TITLE
👑 [需求]固定表头行以及列宽的拖动功能

### ISSUE THREAD

**Issue by kobebing** [ant-design/pro-components#988]

**Comment by kobebing** [comment]
缺少固定表头行以及列宽的拖动功能

**Comment by chenshuai2144** [comment]
> 固定表头行

https://ant.design/components/table-cn/#components-table-demo-fixed-header

**Comment by kobebing** [comment]
protable缺少固定表头及列宽可拖拽的功能

**Comment by chenshuai2144** [comment]
自己加一下吧，一般人不用，看上面那个demo

**Comment by linzhaoyang** [comment]
我也希望有拖动表头控制列宽这个功能，ProTable在数据列多的情况下通过columns动态调整列宽，卡顿很明显，体验很差，除非在拖动时，清掉列表的数据。 @chenshuai2144 。

**Comment by kobebing** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
