### ISSUE TITLE
👑 [需求]支持搜索表单项 自定义单独的 span 属性或 span属性支持函数

### ISSUE THREAD

**Issue by codetalks-new** [ant-design/pro-components#99]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
目前查询表单项的大小可以通过,设置 `search` 的 `span` 属性来修改.
```tsx
 search={{ span: defaultSearchColConfig }}
```
但是这有一个问题就是, 所有的查询表单项的宽度都是一样的.一般来说这没有问题.
但是不同的表单项有时对宽度的要求差别比较大.
比如:
1) 一个搜索输入框,如果输入的值比较长,要求是 8列左右.
2) 一个简单的是/否状态 Select 则只需要4列就足够了.

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
span 属性支持设置为一个 function
比如:
```tsx
 { span: (index|key) => colConfig }
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
无

**Comment by drizzlesconsin** [comment]
![image](https://user-images.githubusercontent.com/69514654/118633522-29775b00-b804-11eb-9b22-71f4b45426e4.png)
[Demo](https://procomponents.ant.design/~demos/queryfilter-query-filter-collapsed)

在超宽屏下，表单项好像有点宽
是不是可以考虑加个 `xxxl` @chenshuai2144 

https://github.com/ant-design/pro-components/blob/master/packages/form/src/layouts/QueryFilter/index.tsx#L20-L26
