### ISSUE TITLE
👑 selectTable 结合table的选择框

### ISSUE THREAD

**Issue by mushroomlb** [ant-design/pro-components#990]
### 🥰 需求描述
在业务系统开发时需要select和table结合，如下图片，选择时可以 从table中单选或多选
[demo实例](https://lolicode.gitee.io/layui_component_tableselect/)

### 🚑 其他信息
layUI中有相似控件组合

![image](https://user-images.githubusercontent.com/1701771/99240841-05789400-2838-11eb-9e21-4b54e4b44b8d.png)

**Comment by zmj0920** [comment]
这个挺不错的

**Comment by chenshuai2144** [comment]
可编辑表格吗？
正在做了

**Comment by Hikarien** [comment]
@mushroomlb  @zmj0920   可以来这看看 #577 
一起劝一下帅哥～
