### ISSUE TITLE
ProTable 在使用search 查询后，每次查询 分页总是重置为第一页。🐛[BUG]

### ISSUE THREAD

**Issue by benson-singapore** [ant-design/pro-components#991]
### 🐛 bug 描述

ProTable 在使用search 查询后，每次查询 分页总是重置为第一页。
返回数据current 强制指定为其他页数还是跳转第一页。

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by siyi98** [comment]
@benson-singapore 贴一下依赖的版本号呢

**Comment by xiexingen** [comment]
感觉重新点击查询按钮了 应该是得回到第一页的
比如之前搜索的是2020 翻到第10页，然后修改了搜索的值为2021 点击搜索 可能按这个条件搜索的值没有10页  所以感觉到第一页更符合业务逻辑

**Comment by chenshuai2144** [comment]
这个是个设计，保留页面可能出现页面为空的
