### ISSUE TITLE
🐛[BUG]pro-table搜索表单自定义

### ISSUE THREAD

**Issue by rockPrince** [ant-design/pro-components#997]
### 🐛 bug 描述

点击重置不会重新进入renderFormItem方法

### 📷 复现步骤

状态 选择 未解决->显示 排序方式->点击重置 此时状态变更为全部 排序方式还在显示

### 🏞 期望结果

点击重置 重新进入renderFormItem

### 💻 复现代码

https://procomponents.ant.design/~demos/table-linkage_form

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by zmj0920** [comment]
嗨哥们你的mock数据如何打包发布的啊

**Comment by chenshuai2144** [comment]
排序方式发生变化需要重置 form表单吗? 感觉意义不大

**Comment by rockPrince** [comment]
https://codesandbox.io/s/3doxw?file=/App.tsx
选中 状态:星期 动态:星期一
点击重置
状态编程默认 月份  但是动态的下拉框还是星期一 星期二
所以感觉 点击重置 需要 重新执行renderFormItem

**Comment by rockPrince** [comment]
@zmj0920 这个是官方的例子 😊
