### ISSUE TITLE
🐛[BUG]ProCard colSpan无法正确换行

### ISSUE THREAD

**Issue by johnnylc** [ant-design/pro-components#998]
### 🐛 bug 描述
采用栅格布局时，设置各个Card的colSpan总和大于24时不会自动换行，而是保持在一行中。

```
<ProCard ghost gutter={16}>
          <ProCard colSpan={12} title="标题" extra="extra" tooltip="这是提示" bordered headerBordered>
            内容
          </ProCard>
          <ProCard colSpan={12} title="标题" extra="extra" tooltip="这是提示" bordered headerBordered>
            内容
          </ProCard>
          <ProCard colSpan={12} title="标题" extra="extra" tooltip="这是提示" bordered headerBordered>
            内容
          </ProCard>
          <ProCard colSpan={12} title="标题" extra="extra" tooltip="这是提示" bordered headerBordered>
            内容
          </ProCard>
</ProCard>
```
以上代码运行结果如图所示：
![image](https://user-images.githubusercontent.com/12717523/99362842-ef79da80-28ee-11eb-9ea3-6bee0d4922e4.png)

### 🏞 期望结果

期望能够正确换行展示成两行card。

### © 版本信息

- ProCard 版本:  1.4.6
- umi 版本 3.2.27
- 浏览器环境 Chrome 86.0.4240.193
- 开发环境 mac OS

**Comment by rdmclin2** [comment]
恩...现在容器就是普通的 flex，倒是没有考虑换行的问题，这种看一下。

**Comment by rdmclin2** [comment]
这个研究了一下，因为 ProCard 本身是 Card + Row + Column 的结合体，自带 border，提供宽度补足。无法利用透明border，或者margin-padding抵消等方式来进行卡片的带 gutter 无缝隙布局，所以没有办法实现精确的换行。

所以这里布局建议：
1. 用户自己计算，每个procard下的colspan 总和不要超过24，超出则换一个 procard 来套。
2. 自己style 传入 `flexWrap: 'wrap'` 来进行自动换行，不过要注意如果设置了 gutter，换行的 col 会不精确。
3. 布局仍采用 Row+ Column 。
