### ISSUE TITLE
👑 [需求]老文档的一些细节在新版本中被掩盖

### ISSUE THREAD

**Issue by liuzhenji** [ant-design/pro-components#999]
### 🥰 需求描述

Pro-Table之前的request参数，还说明了下返回结果体结构，现在文档中直接没有了，就扔了个tsx类。属实不方便，新接触
proComponent的同学都不知道如何实现分页了。老同学也只能从老接口中了解分页查询接口的返回体结构

**Comment by chenshuai2144** [comment]
我们强烈推荐使用 ts 的
